### ISSUE TITLE
[Bug] KeyError: 'InternImage is not in the models registry'

### ISSUE THREAD

**Issue by xuweidongkobe** [open-mmlab/mmdetection#10011]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

python all modles are installed

### Reproduces the problem - code sample

from mmdet.apis import init_detector, inference_detector
import mmcv

# 指定模型的配置文件和 checkpoint 文件路径
config_file = 'configs/cascade_rcnn/cascade_internimage_xl_fpn_3x_coco.py'
checkpoint_file = 'checkpoints/cascade_internimage_xl_fpn_3x_coco.pth'

# 根据配置文件和 checkpoint 文件构建模型
model = init_detector(config_file, checkpoint_file, device='cuda:0')

# 测试单张图片并展示结果
img = 'test_img/1669168462980.jpg'  # 或者 img = mmcv.imread(img)，这样图片仅会被读一次
result = inference_detector(model, img)
# 在一个新的窗口中将结果可视化
model.show_result(img, result)
# 或者将可视化结果保存为图片
model.show_result(img, result, out_file='result.jpg')

### Reproduces the problem - command or script

python test.py

### Reproduces the problem - error message

KeyError: 'InternImage is not in the models registry'

### Additional information

I use mmdet API to run internimage models, but get this error in branch v2.28.1, how can I solve it , thanks!

**Comment by hhaAndroid** [comment]
@xuweidongkobe Please refer  [this doc](https://mmyolo.readthedocs.io/zh_CN/dev/recommended_topics/troubleshooting_steps.html#xxx-is-not-in-the-model-registry)

**Comment by xuweidongkobe** [comment]
> @xuweidongkobe Please refer [this doc](https://mmyolo.readthedocs.io/zh_CN/dev/recommended_topics/troubleshooting_steps.html#xxx-is-not-in-the-model-registry)

thank you
