### ISSUE TITLE
diffusiondet_resnet_to_mmdet.py ——The following error occurs during the conversion. Thank you very much if you can get help

### ISSUE THREAD

**Issue by yuqingchen1** [open-mmlab/mmdetection#10012]
betas is not converted!!
alphas_cumprod is not converted!!
alphas_cumprod_prev is not converted!!
sqrt_alphas_cumprod is not converted!!
sqrt_one_minus_alphas_cumprod is not converted!!
log_one_minus_alphas_cumprod is not converted!!
sqrt_recip_alphas_cumprod is not converted!!
sqrt_recipm1_alphas_cumprod is not converted!!
posterior_variance is not converted!!
posterior_log_variance_clipped is not converted!!
posterior_mean_coef1 is not converted!!
posterior_mean_coef2 is not converted!!

**Comment by hhaAndroid** [comment]
@yuqingchen1 This is normal, because this data is recalculated when the class is constructed and does not need to be converted
