### ISSUE TITLE
how can I visualize the data

### ISSUE THREAD

**Issue by Charcy-yang** [open-mmlab/mmdetection#1002]
Hello, how can I visualize the data, such as painting PR curves, etc.

**Comment by hellock** [comment]
After getting the detection results of the val set, you can plot whatever curve you want.

**Comment by Stephenfang51** [comment]
@Charcy-yang  I just created the visualization program, you can check it
[Stephenfang51/mmdetection_visualize](https://github.com/Stephenfang51/mmdetection_visualize)

**Comment by Charcy-yang** [comment]
> 获得val集的检测结果后，您可以绘制所需的任何曲线。

Thanks.

**Comment by Charcy-yang** [comment]
> @Charcy-yang 我刚创建了可视化程序，你可以查一下
> [Stephenfang51 / mmdetection_visualize](https://github.com/Stephenfang51/mmdetection_visualize)

Thanks
