### ISSUE TITLE
make full utilisation of GPU during inference 

### ISSUE THREAD

**Issue by DecentMakeover** [open-mmlab/mmdetection#1003]
Related to #213 #863 #932 

Thanks for sharing your work, when running the inference script for video which looks like this 
from mmdet.apis import init_detector, inference_detector, show_result
    import time

    config_file = 'configs/faster_rcnn_r50_fpn_1x.py'
    checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'

    # build the model from a config file and a checkpoint file
    # model = init_detector(config_file, checkpoint_file, device='cuda:0')
    model = init_detector(config_file, checkpoint_file, device='cuda:0')

    # test a single image and show the results
    import cv2 
    import numpy as np 
       
    # Create a VideoCapture object and read from input file 
    cap = cv2.VideoCapture('video.mp4') 
       
    # Check if camera opened successfully 
    if (cap.isOpened()== False):  
      print("Error opening video  file") 
       
    # Read until video is completed 
    count =0
    start = time.time()
    while(cap.isOpened()): 
          
      # Capture frame-by-frame
      ret, frame = cap.read() 
      if ret == True: 
        # img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
        result = inference_detector(model, frame)
        show_result(frame, result, model.CLASSES, out_file='video_prediction/result{}.jpg'.format(count))
        count+=1
        print('Count ',count, 'Time ',time.time() - start)
    end = time.time() - start

    print('_______', end)
        # test a list of images and write the results to image files
        # imgs = ['test1.jpg', 'test2.jpg']
        # for i, result in enumerate(inference_detector(model, imgs)):
            # show_result(imgs[i], result, model.CLASSES, out_file='result_{}.jpg'.format(i))

The GPU utilisation is very low

![usage](https://user-images.githubusercontent.com/25679895/61236073-c1ade000-a754-11e9-96c7-993d53abc7ab.png)

Is there a way to use all the memory, if someone can point me in a direction ill do this myself

Thanks in advance.

**Comment by mosheliv** [comment]
I don't think this code was designed to be a video processing pipeline. To
properly handle video you need the IO (both read and write) to be done in
parallel to processing as well and NMS.
to check the actual GPU utilization, try changing your code to:
```
frame = mmcv.imread('test.jpg') #don't do and read in the loop

while True:

  result = inference_detector(model, frame)

#  show_result(frame, result, model.CLASSES,
out_file='video_prediction/result{}.jpg'.format(count))
  count+=1
  print('Count ',count, 'Time ',time.time() - start)

```

**Comment by DecentMakeover** [comment]
@mosheliv  Thanks for the suggestion let me check this
