### ISSUE TITLE
[benchmark regression] benchmark test question

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmdetection#10044]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I test the model by banchmark ， but no results

<html>
<body>
<style> td {white-space:pre-wrap;border:1px solid #dee0e3;}</style><byte-sheet-html-origin data-id="1680020000928" data-version="3" data-is-embed="true">

Model | Status | PQ (metric) | bbox_mAP (metric) | segm_mAP (metric) | PQ (baseline) | bbox_mAP (baseline) | segm_mAP (baseline)
-- | -- | -- | -- | -- | -- | -- | --
mask-rcnn_r50_fpn_albu_1x_coco | run fail |   | cant get metric |   | - |   |  
mask-rcnn_convnext-t-p4-w7_fpn_amp-ms-crop-3x_coco | run fail |   | cant get metric |   | - |   |  
deformable-detr_r50_16xb2-50e_coco | FALSE | - | 0 | - | - | 44.5 | -
detr_r50_8xb2-150e_coco | FALSE | - | 0 | - | - | 40.1 | -
mask2former_r50_8xb2-lsj-50e_coco | FALSE | - | 0 | 0 | - | 45.7 | 42.9
mask2former_r50_8xb2-lsj-50e_coco-panoptic | FALSE | 0 | 0 | 0 | 51.9 | 44.8 | 41.9
maskformer_r50_ms-16xb1-75e_coco | FALSE | 0 | - | - | 46.9 | - | -

</byte-sheet-html-origin>
</body>
</html>

### Environment

- mmcv：2.x
- mmegine：main
- branch：test-3.x
- commit_id: https://github.com/open-mmlab/mmdetection/commit/e862054981971adccff7176476717388b080f1d5

**Comment by GTrui6** [comment]
I used the FPS benchmark, but got "AttributeError: 'NoneType' object has no attribute 'Process'"

**Comment by pigfishgogogo** [comment]
> 我使用了 FPS 基准测试，但得到了“AttributeError： 'NoneType' object has no attribute 'Process'”

老哥，我也遇到了这个问题，请教一下你是怎么解决的？

**Comment by douling843** [comment]
> I used the FPS benchmark, but got "AttributeError: 'NoneType' object has no attribute 'Process'"

大佬，我也遇到了这个问题，请问您是怎么解决的？
