### ISSUE TITLE
Question about memory usage in the model zoo readme

### ISSUE THREAD

**Issue by mosheliv** [open-mmlab/mmdetection#1005]
the text says that :
```
For fair comparison with other codebases, we report the GPU memory as the maximum value of torch.cuda.max_memory_allocated() for all 8 GPUs. Note that this value is usually less than what nvidia-smi shows.
```
Most config files are using 2 images per gpu. Does this means the more or less maximum GPU memory required per image is the number in the table divided by 2?

**Comment by OceanPang** [comment]
@mosheliv The memory reported by `torch.cuda.max_memory_allocated()` is the actual memory allocated, but not used. There is another API called `torch.cuda.max_memory_cached()` that would be larger than the allocated. So the actual used memory by cached or` nvidia-smi` would be larger than the number reported.

**Comment by mosheliv** [comment]
Thanks for your prompt reply. I am a bit confused though what is the use of
this number. My problem aim is to decide what maximum batch size i can put
on a graphics card. Does this number gives any indication or is it
completely irrelevant?

**Comment by OceanPang** [comment]
@mosheliv This number is not the exact memory your GPU used for per batch. Because PyTorch would introduce into some other cached memory. So it's not the best choice for you to decide the batch size according to this memory.
