### ISSUE TITLE
how to use the tensorboardX to visualize the model

### ISSUE THREAD

**Issue by Lucy0601** [open-mmlab/mmdetection#1006]
forward function takes the img_meat as input which is not the tensor, I want to know how can I visualize the model using the tensorboardX

**Comment by bhack** [comment]
I think Tensorboardx is not required anymore in the last pytorch release.

**Comment by Lucy0601** [comment]
Can you tell me how to visualize the model structure, I countered the problem: the forward function takes the img_meta as input which is not the tensor

**Comment by hellock** [comment]
It will be supported in the next version of pytorch, the current version (1.1) has some bugs of supporting the model visualization with tensorboard.

**Comment by EchoIR** [comment]
pytorch1.2 is released, when can I visualize the model using the tensorboardX
