### ISSUE TITLE
Question about FPN

### ISSUE THREAD

**Issue by BlueBlueFF** [open-mmlab/mmdetection#1008]
In fpn, after lateral_conv, it also some fpn_convs. What the meaning of fpn_convs? In other implements of FPN, i don't see this convs.

**Comment by OceanPang** [comment]
@BlueBlueFF We think that `fpn_convs` are widely used in public FPN implementations, also in the paper. You can refer to the paper for more details.

**Comment by ujsyehao** [comment]
@BlueBlueFF In FPN paper, `we append a 3×3 convolution on each merged map to
generate the final feature map, which is to reduce the alias-
ing effect of upsampling.` you can read the paper.

**Comment by BlueBlueFF** [comment]
> @BlueBlueFF In FPN paper,
> 
> > we append a 3×3 convolution on each merged map to
> > generate the final feature map, which is to reduce the alias-
> > ing effect of upsampling.
> 
> You can read the paper.

Thank you for your reply, but in retinanet, there is no this fpn_convs, right?

**Comment by ujsyehao** [comment]
@BlueBlueFF retinanet has fpn_convs.
