### ISSUE TITLE
Impossible to get validation loss during training VFnet [Bug] 

### ISSUE THREAD

**Issue by FraCamp** [open-mmlab/mmdetection#10088]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: linux
Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu117
OpenCV: 4.7.0
MMCV: 1.7.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.7
MMDetection: 2.28.2+unknown

### Reproduces the problem - code sample

`python tools/train.py conf.py`
I am training VFnet with custom dataset, so I made a custom conf file

### Reproduces the problem - command or script

python tools/train.py conf.py

### Reproduces the problem - error message

2023-04-05 10:52:59,949 - mmdet - INFO - workflow: [('val', 1)], max: 24 epochs
2023-04-05 10:52:59,949 - mmdet - INFO - Checkpoints will be saved to /workspace/work_dirs/conf by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 249, in <module>
    main()
  File "tools/train.py", line 238, in main
    train_detector(
  File "/usr/local/lib/python3.8/dist-packages/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 72, in val
    self.run_iter(data_batch, train_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 34, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/parallel/data_parallel.py", line 99, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/base.py", line 263, in val_step
    losses = self(**data)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/single_stage.py", line 83, in forward_train
    losses = self.bbox_head.forward_train(x, img_metas, gt_bboxes,
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py", line 208, in new_func
    return old_func(*args, **kwargs)
TypeError: loss() missing 1 required positional argument: 'img_metas'

### Additional information

I cannot get the validation loss, I need it since I am fine tuning vfnet.
I am using a custom dataset, but that is not a problem since the training goes as expected
I already tried some solutions like: https://github.com/open-mmlab/mmdetection/pull/7173#issue-1139837459
But the problem persists

**Comment by FraCamp** [comment]
I tried a lot of things, but I cannot solve this, please help!

**Comment by zwhus** [comment]
Hi, the error seems to come from  that you did not specify img_metas when calculating val loss, like 'gt_bboxes', 'gt_labels'. You can try modify test_pipeline https://github.com/open-mmlab/mmdetection/blob/2.x/configs/vfnet/vfnet_r50_fpn_1x_coco.py#L86 to solve this problem.

**Comment by FraCamp** [comment]
I added in the same file this val_pipeline:
`val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
        ])
]`
and tried also with this:
`val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img']),
        ])
]`
I think you meant this right?
Anyway seams that the error persists:
`Traceback (most recent call last):
  File "tools/train.py", line 249, in <module>
    main()
  File "tools/train.py", line 238, in main
    train_detector(
  File "/usr/local/lib/python3.8/dist-packages/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 72, in val
    self.run_iter(data_batch, train_mode=False)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 34, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/parallel/data_parallel.py", line 99, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/base.py", line 263, in val_step
    losses = self(**data)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/detectors/single_stage.py", line 83, in forward_train
    losses = self.bbox_head.forward_train(x, img_metas, gt_bboxes,
  File "/usr/local/lib/python3.8/dist-packages/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py", line 208, in new_func
    return old_func(*args, **kwargs)
TypeError: loss() missing 1 required positional argument: 'img_metas'`

**Comment by FraCamp** [comment]
Maybe this could help: 
`img_metas:  [{'filename': 'data/images/train/3951.png', 'ori_filename': '3951.png', 'ori_shape': (2160, 3840, 3), 'img_shape': (651, 1157, 3), 'pad_shape': (672, 1184, 3), 'scale_factor': array([0.30130208, 0.3013889 , 0.30130208, 0.3013889 ], dtype=float32), 'flip': False, 'flip_direction': None, 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}, 'batch_input_shape': (672, 1184)}, {'filename': 'data/images/train/8527.png', 'ori_filename': '8527.png', 'ori_shape': (2160, 3840, 3), 'img_shape': (492, 875, 3), 'pad_shape': (512, 896, 3), 'scale_factor': array([0.22786458, 0.22777778, 0.22786458, 0.22777778], dtype=float32), 'flip': True, 'flip_direction': 'horizontal', 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}, 'batch_input_shape': (672, 1184)}, {'filename': 'data/images/train/16700.png', 'ori_filename': '16700.png', 'ori_shape': (2160, 3840, 3), 'img_shape': (506, 900, 3), 'pad_shape': (512, 928, 3), 'scale_factor': array([0.234375  , 0.23425926, 0.234375  , 0.23425926], dtype=float32), 'flip': True, 'flip_direction': 'horizontal', 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}, 'batch_input_shape': (672, 1184)}]
/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
I+00018.080: breakpoint() ignored - debugger not attached

losses: {'loss_cls': tensor(0.2150, device='cuda:0'), 'loss_bbox': tensor(0., device='cuda:0'), 'loss_bbox_rf': tensor(0., device='cuda:0')}`
these are the value obtained through debugging, img_metas before the loss() fun and actually the losses right after the call of the loss function (that seams like this is working 🤷🏽‍♂️?)

this the command I used:
`python3 -m debugpy --listen 0.0.0.0:5678 --log-to-stderr tools/train.py conf.py`

**Comment by zwhus** [comment]
This is not a bug. The problem is caused by https://github.com/open-mmlab/mmdetection/blob/2.x/mmdet/models/dense_heads/vfnet_head.py#L304， in  workflow: [('val', 1)], traing_mode is Fasle. I think you want compute loss, can modify this manually.

**Comment by FraCamp** [comment]
Following this solution:
https://github.com/open-mmlab/mmdetection/pull/7173#issue-1139837459
My code there is this, without the if else since the return before:
`return cls_score, bbox_pred, bbox_pred_refine
   #       if self.training:
   #          return cls_score, bbox_pred, bbox_pred_refine
   #       else:
   #         return cls_score, bbox_pred_refine`
while for the workflow =  [('val',1)] is just to operate on validation and do not wait 3h to finish one epoch of training, the error appear with or without the up mentioned if else, and even with workflow = [('train', 1),('val', 1)],  the only way to not have that problem is with workflow = [('train', 1)] but in this way I do not have the loss on validation that I need..

**Comment by FraCamp** [comment]
if I run:
`python3 -m debugpy --listen 0.0.0.0:5678 --log-to-stderr tools/train.py conf.py `
instead of:
`python3 tools/train.py conf.py`
seems that it is working, this the output of val epoch:
`        2023-04-06 21:36:47,407 - mmdet - INFO - Exp name: conf.py
2023-04-06 21:36:47,407 - mmdet - INFO - Epoch(val) [1][516]    loss_cls_val: 0.3225, loss_bbox_val: 0.2421, loss_bbox_rf_val: 0.3246, loss_val: 0.8892
2023-04-06 21:39:15,017 - mmdet - INFO - Epoch [2][50/2977]     lr: 1.000e-02, eta: 2 days, 7:24:03, time: 2.952, data_time: 0.064, memory: 6495, loss_cls: 0.4138, loss_bbox: 0.1736, loss_bbox_rf: 0.2311, loss: 0.8185
2023-04-06 21:41:40,177 - mmdet - INFO - Epoch [2][100/2977]    lr: 1.000e-02, eta: 2 days, 7:21:24, time: 2.903, data_time: 0.006, memory: 6495, loss_cls: 0.2488, loss_bbox: 0.1337, loss_bbox_rf: 0.1764, loss: 0.5589`

with the normal command (without debug) the problem is still there..
Other quick question: if I want to visualize the mAP during the validation what should I modify?

**Comment by FraCamp** [comment]
Solved, I was modifying the local version of mmdetection ( cloned with git) but I installed mmdet with pip (not the local one)

**Comment by suekarry** [comment]
> Solved, I was modifying the local version of mmdetection ( cloned with git) but I installed mmdet with pip (not the local one)

Hi, let me see. Your solution is change an environment? Still modified the pipeline
