### ISSUE TITLE
I want to add data augment function in this frame work,where could I add these augment function?

### ISSUE THREAD

**Issue by gittigxuy** [open-mmlab/mmdetection#1009]
From now on,I find that MMdetection only use random flip function to data augment in the dataset/transform.py file.so just fix transform.py to add augment function is OK or need to fix any other code?

**Comment by codeislife99** [comment]
Checkout extra_aug as shown here 
https://github.com/amirassov/kaggle-imaterialist

**Comment by OceanPang** [comment]
@gittigxuy Currently you need to modify the code by yourself to make more data augmentation. You can try to include your augmentation code in `transform.py` and used them in the data loader (`get_item`). There is also a PR ongoing #935 .

**Comment by gittigxuy** [comment]
@codeislife99 ,thanks ,a good repo,I will read it
