### ISSUE TITLE
Is there an easy way to save the backbone features and ROI features during prediction?

### ISSUE THREAD

**Issue by HuaizhengZhang** [open-mmlab/mmdetection#101]
I want to get the ROI features, backbone features, and predictions in one time.

**Comment by zhaojw219** [comment]
I have the similar idea with you.What I want is save the roi feature in any form during testing.Do you already have a solution?Thanks so much!

**Comment by HuaizhengZhang** [comment]
@zhaojw219 I use mask-rcnn-benchmark to address the issue
