### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by trungpham2606** [open-mmlab/mmdetection#1011]
@hellock  Thank you for your work, Iam trying to build your model on windows platform following by @wswday 's changes. But Iam having a problem during building sigmoid_loss.

![image](https://user-images.githubusercontent.com/35657426/61341268-d9c65200-a86f-11e9-9659-1dc8a86eea45.png)

**Comment by wswday** [comment]
This is a buy in pytorch, i am going to fix an PR.

**Comment by trungpham2606** [comment]
@wswday any update till now bro ?
