### ISSUE TITLE
Why the runtime is slow when using  nms_cpu.cpp complied by g++ self  than the .so file in  mmdetection?

### ISSUE THREAD

**Issue by t-m-k** [open-mmlab/mmdetection#1015]
Question:
I run a c++ trace model from mmdetection, and use the nms_cpu.cpp . when I use g++ complie the project， I can get the right result. But the time model used is much than the mmdetection inference.  Then I check the problem ,I found the nms_cpu.cpp take more time than the same process in mmdetection. Do you have some special args setting when you compile the nms_cpu.cpp to the .so file?

Detail:
++++++++++++++++
nms_process : 204 ms
nms_process : 201 ms
nms_process : 202 ms
nms_process : 200 ms
nms_process : 198 ms
nms_process : 206 ms
++++++++++++++++
c++ cost above.
++++++++++++++++
nms_process : 75 ms
nms_process : 82 ms
nms_process : 64 ms
nms_process : 67 ms
nms_process : 72ms
nms_process : 61 ms
++++++++++++++++
mmdetection cost above.

Do you have some special compile using the cpp_extension in torch? thank you very much.

**Comment by hellock** [comment]
We just use the default compiling args of pytorch extension. You can figure it out from the printed log.

**Comment by t-m-k** [comment]
ok, i found it and replace my settings with the printed log,  i got the same time cost. Thanks.

**Comment by zhaojw219** [comment]
Hi,can you tell me how to compile nms_cpu?What instructions should I type?Thanks!
