### ISSUE TITLE
soft teacher for rtm det for instance segmentation tasks?

### ISSUE THREAD

**Issue by zjhthu** [open-mmlab/mmdetection#10171]
Does the semi-supervised method soft teacher support RTMDet for instance segmentation tasks?

**Comment by zjhthu** [comment]
I got the error `AttributeError: 'RTMDet' object has no attribute 'rpn_head'  `. It seems the current soft teacher does not support RTMDet. Do you have any suggestions for making soft teacher work with RTMDet?

**Comment by SThrEUR** [comment]
Did you solve that? How?
