### ISSUE TITLE
some questions about distributedGroupSamper in sampler.py

### ISSUE THREAD

**Issue by gittigxuy** [open-mmlab/mmdetection#1018]
I have defined my own sampler method,and it works fine in GroupSampler to use single GPU,but I could not understand how it works in distributedGroupSamper.

Detailly,I fix the __iter__ function in the GroupSampler class .as we know,the indices is a list which contains the dataset index,thus ,I define my own sampler method to return a dataset index list.so how could I change the code to fit in distributedGroupSamper?

**Comment by hellock** [comment]
DistributedGroupSamper also returns an index list, but takes the world size and rank into account. If there are 8 processes, the DistributedGroupSamper just need to return 1/8 of the total indices.
