### ISSUE TITLE
MMEngine==0.7.0 is used but incompatible. Please install mmengine>=0.7.1, <1.0.0.

### ISSUE THREAD

**Issue by gatzf** [open-mmlab/mmdetection#10221]
MMEngine==0.7.0 is used but incompatible. Please install mmengine>=0.7.1, <1.0.0.
but i can't install MMEngine==0.7.1

**Comment by gatzf** [comment]
![image](https://user-images.githubusercontent.com/102007464/234351801-40517574-be18-4da4-b020-fb60e95021ef.png)

**Comment by LinJ0866** [comment]
try `pip install mmengine==0.7.1`

**Comment by Luxiangxianghy** [comment]
> try `pip install mmengine==0.7.1`
pip install mmengine==0.7.1 
ERROR: Could not find a version that satisfies the requirement mmengine==0.7.1 (from versions: 0.0.1rc0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0)
ERROR: No matching distribution found for mmengine==0.7.1  ？

**Comment by JielinYang** [comment]
I met the same problem. Hava you solved this?

**Comment by JielinYang** [comment]
> I met the same problem. Hava you solved this?

I have solved this problem just now.
refer to FAQ--Installation page: https://mmdetection.readthedocs.io/zh_CN/latest/notes/faq.html
I choose mmengine 0.7.0(>=0.7.1 is unable to install), mmcv 2.0.0rc4, mmdet 3.0.0rc6 and everything goes well.

**Comment by czczmr** [comment]
> > I met the same problem. Hava you solved this?
> 
> I have solved this problem just now. refer to FAQ--Installation page: https://mmdetection.readthedocs.io/zh_CN/latest/notes/faq.html I choose mmengine 0.7.0(>=0.7.1 is unable to install), mmcv 2.0.0rc4, mmdet 3.0.0rc6 and everything goes well.

您好，可以问下您详细的安装过程吗，我也遇到了这个问题

**Comment by JielinYang** [comment]
> 
我是在服务器上部署的，已经有conda环境、pytorch和CUDA了，安装mmdetection参照官网的安装步骤，但是需要指定下各个包的版本吧，具体的命令流程：
pip install -U openmim
mim install mmengine==0.7.0
mim install "mmcv==2.0.0rc4"
github上选择mmdet tag为3.0.0rc6的版本下载zip并解压
cd mmdetection
pip install -v -e .

**Comment by czczmr** [comment]
感谢，成功了！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月7日(星期三) 晚上9:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection] MMEngine==0.7.0 is used but incompatible. Please install mmengine&gt;=0.7.1, <1.0.0. (Issue #10221)





    
I met the same problem. Hava you solved this?
  
I have solved this problem just now. refer to FAQ--Installation page: https://mmdetection.readthedocs.io/zh_CN/latest/notes/faq.html I choose mmengine 0.7.0(&gt;=0.7.1 is unable to install), mmcv 2.0.0rc4, mmdet 3.0.0rc6 and everything goes well.
  
您好，可以问下您详细的安装过程吗，我也遇到了这个问题
  
我是在服务器上部署的，已经有conda环境、pytorch和CUDA了，安装mmdetection参照官网的安装步骤，但是需要指定下各个包的版本吧，具体的命令流程：
 pip install -U openmim
 mim install mmengine==0.7.0
 mim install "mmcv==2.0.0rc4"
 github上选择mmdet tag为3.0.0rc6的版本下载zip并解压
 cd mmdetection
 pip install -v -e .

**Comment by dxy2110** [comment]
ERROR: Could not find a version that satisfies the requirement mmengine==0.7.0 (from versions: 0.0.1rc0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.4.0)
ERROR: No matching distribution found for mmengine==0.7.0
How can I solve this problem?
