### ISSUE TITLE
3D input to the mmdetection

### ISSUE THREAD

**Issue by lazyDonnie** [open-mmlab/mmdetection#1022]
Hi, I'm currently trying to apply this wonderful framework for my 3D detection & classification project. I roughly figured out the structure of the code package and ran this on some random 2D image detection & classification problem. 

Now, I want to modify the framework in order to take 3D objects (like 1300x1300x800 voxels). Would it be possible to achieve this by simply converting 2D convolution to 3D convolution in the backbone and making the rest of parts (head, neck) learn the 2D projection images of the original 3D input object? The reason why I thought like this is that it would be very difficult to get the ROI head to learn the 3D features and generate 3D bbox. 

Any tips/advices would be appreciated!

**Comment by marcunzueta** [comment]
Has anyone found the same limitation in the current implementation?

**Comment by ZwwWayne** [comment]
Please refer to [MMDetection3D](https://github.com/open-mmlab/mmdetection3d).
