### ISSUE TITLE
RT-DETR

### ISSUE THREAD

**Issue by Jordan-Haidee** [open-mmlab/mmdetection#10241]
**Describe the feature**
implement RT-DETR proposed by Baidu recently.
**Motivation**
RT-DETR has defeated YOLO series models. I expected to use it on Openmmlab platform!😘

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hhaAndroid** [comment]
@Jordan-Haidee Ok, there are already community users to support

**Comment by Jordan-Haidee** [comment]
@hhaAndroid Thanks!

**Comment by Xyzhao1999** [comment]
May I ask how the progress is going on in terms of support for this model?

**Comment by Zunon** [comment]
I'm also interested in how far along this model is
