### ISSUE TITLE
F.pad get "IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)" error 

### ISSUE THREAD

**Issue by yechenzhi** [open-mmlab/mmdetection#10250]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
when i train or test mmdet in coco, i get error ""IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)". 

**Reproduction**

1. What command or script did you run?

```
 python tools/test.py configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py weights/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I use my MAC 2021 to learn mmdet code, I modified num_workers=0, persistent_workers=False in dataloader setting. 

3. What dataset did you use?
coco 2017 val

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
sys.platform: darwin
Python: 3.8.16 (default, Jan 17 2023, 16:39:35) [Clang 14.0.6 ]
CUDA available: False
numpy_random_seed: 2147483648
GCC: Apple clang version 13.0.0 (clang-1300.0.29.3)
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 14.0.0
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_PYTORCH_METAL_EXPORT -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -DUSE_COREML_DELEGATE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wvla-extension -Wno-range-loop-analysis -Wno-pass-failed -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wconstant-conversion -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Wunused-lambda-capture -Wunused-local-typedef -Qunused-arguments -fcolor-diagnostics -fdiagnostics-color=always -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=accelerate, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, USE_ROCM=OFF, 
    TorchVision: 0.14.1
    OpenCV: 4.7.0
    MMEngine: 0.7.2
    MMDetection: 3.0.0+8a8fcb1

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
     pip
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 113, in train_step
    data = self.data_preprocessor(data, True)
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/yechenzhi/CV/mmdetection/mmdet/models/data_preprocessors/data_preprocessor.py", line 122, in forward
    data = super().forward(data=data, training=training)
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/model/base_model/data_preprocessor.py", line 260, in forward
    batch_inputs = stack_batch(batch_inputs, self.pad_size_divisor,
  File "/Users/yechenzhi/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/model/utils.py", line 65, in stack_batch
    F.pad(tensor, tuple(pad[idx].tolist()), value=pad_value))
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
```

**Bug fix**

**Comment by yechenzhi** [comment]
tmp solution: i moved data from 'mps' to 'cpu' or 'cuda',  problem solved.

**Comment by Fau818** [comment]
same error here.

**Comment by davidvblumenthal** [comment]
> tmp solution: i moved data from 'mps' to 'cpu' or 'cuda', problem solved.

@yechenzhi How can you do that? Is there an option to force that in the config? Because for me it auto uses mps.
Thanks :)

**Comment by SimonPlaye** [comment]
go in train.py
locate runner.py (from the import `from mmengine.runner import Runner`)

Then modify this line

`model = model.to(get_device())`

using 'cpu' instead of 'get_device'
