### ISSUE TITLE
Understanding training epochs

### ISSUE THREAD

**Issue by MLRadfys** [open-mmlab/mmdetection#10253]
Hi,

Iam new to mmdetection and Iam having some trouble understanding the number of epochs defined in different config files, namely 1x,2x, lsj-100e, lsj-200e...

As far as I understand, training e.g. an object detector with the 1x scheduler means that the model is trained for 12 epochs, while 2x means 25 epochs.
I guess that 100e and 200e stand for 100 epochs and 200 epochs, respectively.

Now Iam wondering: Why is there such a different in training epochs?

I only have access to a single GPU and training a  model for 200 epochs takes weeks.
Detectron in example uses the 1x, 2x schedulers (though in terms of iterations). Is training an object detector for 12, 25 epochs enough?

I also noticed that all 100e and 200e configs use a multi Gpu setting. 

Thanks in avance for all help,

Cheers,

M

**Comment by hhaAndroid** [comment]
@MLRadfys This is because different algorithms require different numbers of epochs, and they have different performance. You need to check the paper on this algorithm
