### ISSUE TITLE
I wanted to detect the image, but encountered the following error: assert key in results, f'`{key}` is not found in `results`

### ISSUE THREAD

**Issue by anying111** [open-mmlab/mmdetection#10251]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

python tools/test.py \
/root/autodl-tmp/work/mask_rcnn/mask_rcnn.py \
/root/autodl-tmp/work/mask_rcnn/epoch_20.pth \
--show-dir=../autodl-tmp/ceshi/111

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I removed resize from the configuration file because it would have reported other errors.

4. What dataset did you use?
I created my own coco format data set.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

ys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: False
numpy_random_seed: 2147483648
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 2.0.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.0
OpenCV: 4.6.0
MMEngine: 0.7.2
MMDetection: 3.0.0+ecac3a7

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

pip, and I can train the model normally.

**Error traceback**
If applicable, paste the error trackback here.

assert key in results, f'`{key}` is not found in `results`, ' \
AssertionError: `scale_factor` is not found in `results`, the valid keys are ['img_path', 'img_id', 'seg_map_path', 'height', 'width', 'instances', 'sample_idx', 'img', 'img_shape', 'ori_shape', 'gt_bboxes', 'gt_ignore_flags', 'gt_bboxes_labels', 'gt_masks'].

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by anying111** [comment]
There is the following error when I do not remove resize.
Traceback (most recent call last):
  File "./tools/test.py", line 149, in <module>
    main()
  File "./tools/test.py", line 145, in main
    runner.test()
  File "/root/mmengine/mmengine/runner/runner.py", line 1759, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/root/mmengine/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/root/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/mmengine/mmengine/runner/loops.py", line 456, in run_iter
    self.runner.call_hook(
  File "/root/mmengine/mmengine/runner/runner.py", line 1775, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/root/mmdetection/mmdet/engine/hooks/visualization_hook.py", line 139, in after_test_iter
    self._visualizer.add_datasample(
  File "/root/mmengine/mmengine/dist/utils.py", line 360, in wrapper
    return func(*args, **kwargs)
  File "/root/mmdetection/mmdet/visualization/local_visualizer.py", line 351, in add_datasample
    gt_img_data = self._draw_instances(image,
  File "/root/mmdetection/mmdet/visualization/local_visualizer.py", line 186, in _draw_instances
    self.draw_binary_masks(masks, colors=colors, alphas=self.alpha)
  File "/root/mmengine/mmengine/dist/utils.py", line 360, in wrapper
    return func(*args, **kwargs)
  File "/root/mmengine/mmengine/visualization/visualizer.py", line 862, in draw_binary_masks
    assert img.shape[:2] == binary_masks.shape[
AssertionError: `binary_marks` must have the same shape with image

**Comment by hhaAndroid** [comment]
@anying111 I suggest you run success image_demo.py first, that script is much simpler and better understood

**Comment by anying111** [comment]
I've resolved the issue! It was caused by a discrepancy between the size of my image and the size set in the test pipeline. In fact, having different image sizes during training does not affect the results, but for testing purposes, it's necessary to have consistent image sizes. This could be because the code for drawing masks is different.

**Comment by Vibhuvan** [comment]
> I've resolved the issue! It was caused by a discrepancy between the size of my image and the size set in the test pipeline. In fact, having different image sizes during training does not affect the results, but for testing purposes, it's necessary to have consistent image sizes. This could be because the code for drawing masks is different.

Hi, Can you elaborate on how you resolved this issue, even I am getting the same error while testing

**Comment by W-hary** [comment]
> > I've resolved the issue! It was caused by a discrepancy between the size of my image and the size set in the test pipeline. In fact, having different image sizes during training does not affect the results, but for testing purposes, it's necessary to have consistent image sizes. This could be because the code for drawing masks is different.
> 
> Hi, Can you elaborate on how you resolved this issue, even I am getting the same error while testing

Did you solve this problem, I have the same error

**Comment by anying111** [comment]
This seems to be an error in the code of mmdetection, sorry that I have not read it for too long and have forgotten it. It seems that the test image size is first processed in python to be consistent with the configuration file, and then it will run properly.

**Comment by work1-shekhaman** [comment]
i made all my images in test set to be of same size, but gettting same error. This is not specifically for mask rcnn but I am using opencd which uses openmm as backend

**Comment by WengTzu** [comment]
In my case
I remove mask_head from mask-rcnn to conduct bbox training & predicting
so i revise LoadAnnotations without loading mask
   dict(type='LoadAnnotations', with_bbox=True, with_mask=False)

if i set with_mask=True，and conduct test.py. visualizer.py will report this error
