### ISSUE TITLE
how to output all class scores per instance ?

### ISSUE THREAD

**Issue by ZQ-zz** [open-mmlab/mmdetection#10266]
it seems hard to ouput all class scores, because filter scores were implemented in '~mmdet/models/dense_heads/base_dense_head.py'
`            results = filter_scores_and_topk(
                scores, score_thr, nms_pre,
                dict(bbox_pred=bbox_pred, priors=priors))`
so, I must to reimplement ‘predict_by_feat’
any better suggestion ?

**Comment by hhaAndroid** [comment]
@ZQ-zz Only source code can be modified at this time
