### ISSUE TITLE
A bug in mmdet3.0.0 DINO

### ISSUE THREAD

**Issue by wangzhaoyang-508** [open-mmlab/mmdetection#10275]
When i train DINO
the pretrain file ：dino-4scale_r50_8xb2-12e_coco_20221202_182705-55b2bba2.pth in mmdetection\configs\dino\README.md do not match the model since warning occur：**The model and loaded state dict do not match exactly**

unexpected key in source state_dict：level_embed, backbone.conv1.weight, backbone.bn1.bias, backbone.bn1.running_mean..........
missing key in source state_dicr: conv1.weight, bn1.bias, bn1.running_mean, ............

How can I fix  this?
I use the mmdet3.0.0 ;mmengine 0.7.2

**Comment by asizk** [comment]
I have the same problem, did you solve it?

**Comment by wangzhaoyang-508** [comment]
> 



> I have the same problem, did you solve it?

Nope

**Comment by Shahin-Mjz** [comment]
I have the same problem.
