### ISSUE TITLE
How to draw loss change versus iteration

### ISSUE THREAD

**Issue by scut-salmon** [open-mmlab/mmdetection#1028]
Hi, how can I draw the loss change w.r.t. the iteration?

**Comment by hellock** [comment]
See https://github.com/open-mmlab/mmdetection/blob/master/tools/analyze_logs.py for details.
@yhcao6 You can provide an example.

**Comment by yhcao6** [comment]
For example, if your train log is "train.log.json", use 
```
python tools/analyze_logs.py plot_curve train.log.json --keys loss
```
to plot the loss change w.r.t the iteration
