### ISSUE TITLE
soft teacher

### ISSUE THREAD

**Issue by thestars-maker** [open-mmlab/mmdetection#10297]
How to set up the dataset of soft teacher, is it to put the coco dataset of train2017,val2017 and unlabel2017 under mmdetection/data/COCO, and how to set up the dataset input? Is there any script needed to extract and divide the dataset, and if so, how is it done?

**Comment by hhaAndroid** [comment]
@thestars-maker https://github.com/open-mmlab/mmdetection/blob/main/docs/en/user_guides/semi_det.md
