### ISSUE TITLE
when train on open Image bbox is ok，but category is hardly correct

### ISSUE THREAD

**Issue by dongzhi0312** [open-mmlab/mmdetection#1029]
my train dataset is based on open image，when validation，bbox is ok，but category is hardly correct，categories is 443，I check model output is 443
![image](https://user-images.githubusercontent.com/38675877/61525567-4184c480-aa4b-11e9-8646-6f8f660b43b0.png)

**Comment by hellock** [comment]
Maybe the class id and the name string does not match.

**Comment by Antichoke** [comment]
> 
> 
> my train dataset is based on open image，when validation，bbox is ok，but category is hardly correct，categories is 443，I check model output is 443
> ![image](https://user-images.githubusercontent.com/38675877/61525567-4184c480-aa4b-11e9-8646-6f8f660b43b0.png)

Have you solve the problem,I have the same problem

**Comment by ZwwWayne** [comment]
OpenImages has been supported in https://github.com/open-mmlab/mmdetection/tree/master/configs/openimages
