### ISSUE TITLE
Super quick question on the benchmark results in Model zoo

### ISSUE THREAD

**Issue by CrazySherman** [open-mmlab/mmdetection#103]
Is the benchmark results "sec/iter" per-image iteration or "per-mini-batch" speed?
According to https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md Mask-RCNN achieves 0.6s/iter on R50-FPN backbone, however from my experiments on a single Tesla K80, I got 2.7s/batch with batch size of 4. I'm not using distributed training mode tho

**Comment by hellock** [comment]
The main reason may be the hardware and batch size. We reported the training speed on 8 Tesla V100 GPUs, 2 images per GPU. Distributed training is much faster than non-distributed training on single or multiple machines, but since you use only 1 GPU there should be no difference.
