### ISSUE TITLE
When resize_keep_ratio is False, rescaling for masks does not work.

### ISSUE THREAD

**Issue by wangg12** [open-mmlab/mmdetection#1030]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

When `resize_keep_ratio=False`, rescaling for masks in loading the dataset will not work. The error is:
```
Scale must be a number or tuple of int, but got <class 'numpy.ndarray'>
```

**Comment by hellock** [comment]
Thanks for reporting! It will be fixed.

**Comment by liushuchun** [comment]
https://github.com/open-mmlab/mmdetection/pull/883
here are the bug fix pr.

**Comment by wangg12** [comment]
@liushuchun It is not related to this bug.

**Comment by hellock** [comment]
@wangg12 You may have a try on #1050.
