### ISSUE TITLE
mmdetection2.0 to mmdetection 3.0

### ISSUE THREAD

**Issue by thestars-maker** [open-mmlab/mmdetection#10336]
为什么用2.0版本可以正常运行faster rcnn，在3.0版本同样的配置就会报错，主要是验证阶段报页面文件太小问题，但在2.0版本是没有任何问题的，我需要在后续的使用中用到3.0版本，请问该怎么修改呢

**Comment by hhaAndroid** [comment]
可能是你配置的 metainfo 写错了。不同版本 config 写法是不一样的哦
