### ISSUE TITLE
Could u tell me how to prune the model?

### ISSUE THREAD

**Issue by dmndxld** [open-mmlab/mmdetection#10332]
I want to use [Torch-Pruning](https://github.com/VainF/Torch-Pruning/tree/master) lib to prune the model in our mmdetection. But I dont know how to implement it. For example, if i want to use faster-rcnn_r50_fpn_1x_coco.py config, how to do? Some naive ideas are get the model then prune it. I dont know that is right. MUCH THANKS!!!

**Comment by ravishk007** [comment]
@dmndxld, did you find a way to prune the same config model you mentioned?
