### ISSUE TITLE
How to set schedule to save checkpoints of best epoch in mmdetection3.x

### ISSUE THREAD

**Issue by LittleWhitemi** [open-mmlab/mmdetection#10345]
I know that in mmdetection2.x I can set the evaluation in the schedule to save the best checkpoints, but in mmdetection3.x how do I set it to save the best checkpoints as well?

**Comment by akashAD98** [comment]
@LittleWhitemi how did you trained model using mmdetect 3x, what is your installation setup?im not able to run scipt provided by readme, some dependencies issue

**Comment by LittleWhitemi** [comment]
@akashAD98 I am using mmrotate1.x, which is dependent on mmengine as well as mmdetection3.x. You can check if you have the correct version of mmengine. The environment I am looking for is
python3.9+pytorch12；
mmcv                      2.0.0                    pypi_0    pypi
mmcv-full                 1.7.1                    pypi_0    pypi
mmdet                     3.0.0                     dev_0    <develop>
mmengine                  0.7.2                    pypi_0    pypi

**Comment by akashAD98** [comment]
@LittleWhitemi thank,i want to train custom segmentation model but not able to install , getting mmcv error

**Comment by Ali-Awad** [comment]
> @LittleWhitemi thank,i want to train custom segmentation model but not able to install , getting mmcv error

Please do not install mmcv using mim, instead, install it manually. Use the following link:
https://mmcv.readthedocs.io/en/v1.4.1/get_started/installation.html
Scroll down, you will find a table describing the compatible cuda, torch and mmcv versions (of course you would have to install the version you want of pytorch first!)

Trust me, this will work as charm ^_^
