### ISSUE TITLE
What is the difference between RTMDet in mmdetection and in mmyolo?

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#10361]
RTMDet is implemented both here and in https://github.com/open-mmlab/mmyolo. Why the duplication, and what are the differences between the two versions? Also, since the license for mmdetection and the license for mmyolo are different, are the licenses for these two RTMDet versions different?

**Comment by BDJohnston** [comment]
bump

**Comment by hhaAndroid** [comment]
@AndreaPi it has a significant training acceleration compared to the MMDeteciton version. The training speed is 2.6 times faster than the previous version.

**Comment by AndreaPi** [comment]
@hhaAndroid nice! Do you plan to accelerate also the MMDetection version? Or will it always be slower? Apart from the training time, are performance at inference time (mAP, latency) the same? Thank you for your answer

**Comment by BDJohnston** [comment]
@hhaAndroid thank you for confirming the difference in training times between the two implementations. 

I have a couple of follow-up questions:

1. Can you please also confirm if the difference in training speed is the only difference between the two implementations? 

2. Can you also please confirm if the RTMDet implementation in MMYOLO is under a GPL v3.0 license and the RTMDet implementation in MMDetection is under an Apache License 2.0?

**Comment by BinzheLi95** [comment]
Thank you. I have same question about the license of RTMDet in MMDet is GPL v3.0 or Apache License 2.0?
