### ISSUE TITLE
How to use TTA for mmrotate1.x?

### ISSUE THREAD

**Issue by Haru-zt** [open-mmlab/mmdetection#10368]
Hi, When I use the TTA in mmdet for the test in mmrotate1.x, I found that the function **merge_aug_bboxes** need a input tensor like  *aug_bboxes (list[Tensor]): shape (n, 4*#class) . 
However, for now, mmrotate1.x only support the output fomat like  (x, y, w, h, theta),  so i have no way to convert it.
Is there any tips for me to use TTA in mmrotate1.x correctly? Maybe I miss some document.
Thanks for help.

**Comment by Haru-zt** [comment]
Hi, I use the change in https://github.com/open-mmlab/mmrotate/pull/771. 
tta works, but the result is bad. I don't know why tta produce a lot of  wrong bboxes. I don't know why.

**Comment by hhaAndroid** [comment]
@Haru-zt Please to mmrotate create a issue
