### ISSUE TITLE
LightHead RCNN support

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmdetection#1036]
Does there any support of LightHead RCNN?

**Comment by hellock** [comment]
No recent plan for that, but community contribution is welcome.

**Comment by jinfagang** [comment]
@hellock BTW, does the maskrcnn model inside mmdetection inference more faster than maskrcnn-benchmark? I have test it but does not found significant improvement than that

**Comment by hellock** [comment]
It was faster. We tested the latest version of maskrcnn-benchmark and now the inference speed of two codebases are similar.
