### ISSUE TITLE
Multiple dataset Evaluation/Test

### ISSUE THREAD

**Issue by WassimBouatay** [open-mmlab/mmdetection#10376]
Hello, I want to evaluate and test on multiple dataset seperatly. When, I use Concat I will get the metrics of all the images of all the classes combined, I want the evaluation to be applied seperatly for each dataset. How can I achieve this (or what part should I change to get what I want). 
Thank you :)

**Comment by WassimBouatay** [comment]
Done, I changed Loops and Runner to do it.

**Comment by aviadlazar** [comment]
Hi, can you share your solution?
