### ISSUE TITLE
How do I use SWA in mmdetction 3.0?

### ISSUE THREAD

**Issue by MMMMMz** [open-mmlab/mmdetection#10385]
I found the implementation of SWA in mmdetction in this [repository](https://github.com/hyz-xmaster/swa_object_detection) but I didn't find these configurations in the latest version of mmdetction. So, how do I use SWA in mmdetction 3.0?

**Comment by hhaAndroid** [comment]
@MMMMMz We don't have access to this feature. Is there a community user to create pr.

**Comment by MMMMMz** [comment]
OK, thank you very much for your answer.
