### ISSUE TITLE
results got by using "--show-dir" didn't show ground truth box 

### ISSUE THREAD

**Issue by Yoooss** [open-mmlab/mmdetection#10382]
I've tried to run the RTMDet to detect my own dataset.
Using the command:
"python tools/test.py configs/rtmdet/rtmdet_l_8xb32-300e_coco.py /media/ls/disk1/mmdetection/work_dirs/rtmdet_l_8xb32-300e_coco/best_coco/bbox_mAP_s_epoch_187.pth --show-dir result"

However, the result I got only show the prediction box, without the ground truth box as below.
![图片](https://github.com/open-mmlab/mmdetection/assets/49121651/64417503-b0ba-4971-8482-fd3f389a6215)

I have searched for the solutions, but didn't get any useful. May I get some help?
Thanks a lot.

**Comment by hhaAndroid** [comment]
@Yoooss dev-3.x has been fixed
