### ISSUE TITLE
model.show_result(img, result, out_file='result.jpg') does not work

### ISSUE THREAD

**Issue by unique-chan** [open-mmlab/mmdetection#10380]
model.show_result(img, result, out_file='result.jpg') does not work
* faster-rcnn
* Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'FasterRCNN' object has no attribute 'show_result'

**Comment by hhaAndroid** [comment]
@unique-chan Please use the latest main branch code

**Comment by unique-chan** [comment]
I'd tried to use the latest code by cloning dev-3.x, but still I encountered the same issue... Besides, I'd tried to use the newest main-branch code today, but the same problem occurred. (I did not change any DockerFile settings and used 3090.)

**Comment by unique-chan** [comment]
> @unique-chan Please use the latest main branch code


I'd tried to use the latest code by cloning dev-3.x, but still I encountered the same issue... Besides, I'd tried to use the newest main-branch code today, but the same problem occurred. (I did not change any DockerFile settings and used 3090.)

**Comment by WjzZwd** [comment]
same error i met waitng for an answer

**Comment by elahe-badali** [comment]
same error

**Comment by Northcandle** [comment]
same error

**Comment by MarkusFox90** [comment]
same here. 
One way to visualize the results would be to follow the `demo/inference_demo.ipynb`:
```python
# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file)

image = mmcv.imread(some_img)
result = inference_detector(model, image)

# init the visualizer(execute this block only once)
visualizer = VISUALIZERS.build(model.cfg.visualizer)
# the dataset_meta is loaded from the checkpoint and
# then pass to the model in init_detector
visualizer.dataset_meta = model.dataset_meta

# show the results
visualizer.add_datasample(
    'result',
    image,
    data_sample=result,
    draw_gt=False,
    wait_time=0,
    out_file='outputs/result.png' # optionally, write to output file
)
visualizer.show()
```

**Comment by SourabhRanade** [comment]
Same error!! Could we please reopen the issue @hhaAndroid

**Comment by llllllsk** [comment]
> same here. One way to visualize the results would be to follow the `demo/inference_demo.ipynb`:
> 
> ```python
> # build the model from a config file and a checkpoint file
> model = init_detector(config_file, checkpoint_file)
> 
> image = mmcv.imread(some_img)
> result = inference_detector(model, image)
> 
> # init the visualizer(execute this block only once)
> visualizer = VISUALIZERS.build(model.cfg.visualizer)
> # the dataset_meta is loaded from the checkpoint and
> # then pass to the model in init_detector
> visualizer.dataset_meta = model.dataset_meta
> 
> # show the results
> visualizer.add_datasample(
>     'result',
>     image,
>     data_sample=result,
>     draw_gt=False,
>     wait_time=0,
>     out_file='outputs/result.png' # optionally, write to output file
> )
> visualizer.show()
> ```

so good my man !

**Comment by llllllsk** [comment]
> same here. One way to visualize the results would be to follow the `demo/inference_demo.ipynb`:
> 
> ```python
> # build the model from a config file and a checkpoint file
> model = init_detector(config_file, checkpoint_file)
> 
> image = mmcv.imread(some_img)
> result = inference_detector(model, image)
> 
> # init the visualizer(execute this block only once)
> visualizer = VISUALIZERS.build(model.cfg.visualizer)
> # the dataset_meta is loaded from the checkpoint and
> # then pass to the model in init_detector
> visualizer.dataset_meta = model.dataset_meta
> 
> # show the results
> visualizer.add_datasample(
>     'result',
>     image,
>     data_sample=result,
>     draw_gt=False,
>     wait_time=0,
>     out_file='outputs/result.png' # optionally, write to output file
> )
> visualizer.show()
> ```

you should add 
from mmdet.registry import VISUALIZERS
to import VISUALIZERS

**Comment by MarkusFox90** [comment]
> 

Thank you. I have added the imports.
