### ISSUE TITLE
Support imgs as torch, numpy and python list during testing

### ISSUE THREAD

**Issue by Ridhwanluthra** [open-mmlab/mmdetection#1039]
**Describe the feature**
Support images to be from numpy, torch or python list

**Motivation**
I am working on integrating another detector and while implementing testing, i just overload simple_test but my images are torch.tensor which is blocked by the forward_test's check that only allows python lists.

**Additional context**
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L65

I can add the support for others but I just wanted to discuss and know first if there is any particular reason to just support python lists

**Comment by hellock** [comment]
Since `simple_test` and `aug_test` share the same api, `imgs` and `img_metas` are expected to be a list. This would make it easier to implement the test time augmentation.

**Comment by Ridhwanluthra** [comment]
Yes but the way I see it the simple test and aug_test would always be overloaded by a new detector while the forward test would not right?
And allowing a tensor on gpu rather than a list would be more efficient right?
