### ISSUE TITLE
"RuntimeError: expected a non-empty list of Tensors" in "ga_rpn_head.py"

### ISSUE THREAD

**Issue by mosjoker** [open-mmlab/mmdetection#1041]
1. code ("mmdet/models/anchor_heads/ga_rpn_head.py")
```
mlvl_proposals = []
for idx in range(len(cls_scores)):
    ...
    if mask.sum() == 0:
        continue
    ...
proposals = torch.cat(mlvl_proposals, 0)
```
2. bug (There will generate an error, if mlvl_proposals is none. Sometimes the mask.sum is always  equal to 0)

**Comment by ElegantLin** [comment]
I also met this problem. First I met the same problem with @mosjoker .
The second time I ran the code, I met the problem  `‘No prediction found ’`
Third I still met `RuntimeError`.

I am not sure whether `‘No prediction found ’` is related to this. But I am sure the data I used is correct.

**Comment by zhangyunming** [comment]
ins_label = torch.stack(ins_label, 0)
RuntimeError: expected a non-empty list of Tensors

I also met the first problem. have you solve it ? @ElegantLin @mosjoker  hope your reply

**Comment by mosjoker** [comment]
@zhangyunming 
Just for a reference.
```
if len(mlvl_proposals) == 0:
   mlvl_proposals.append(torch.zeros(1, 5).cuda())
proposals = torch.cat(mlvl_proposals, 0)
```
