### ISSUE TITLE
关于3.0版本无法把多个数据集地址做成list传入dataloader中的问题

### ISSUE THREAD

**Issue by Meize0729** [open-mmlab/mmdetection#10425]
在2.0版本中，我可以尝试这样的操作，完成读取不同位置的图片和标签：
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=1, 
        dataset=dict(
        type=dataset_type,
        ann_file=[
            data_root + 'annotations/aitod_train_v1.json',
            data_root + 'annotations/aitod_val_v1.json'],
        img_prefix=[
            data_root + 'train/images/',
            data_root + 'val/images/',],
        pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/aitod_test_v1.json',
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/aitod_test_v1.json',
        img_prefix=data_root + 'test/images/',
        pipeline=test_pipeline))

但我按照方式在3.0操作会得到如下的错误：
TypeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `AITODDataset` in mmdet/datasets/aitod.py: prefix should be a string, but got <class 'list'>

**Comment by RangiLyu** [comment]
Please use ConcatDataset like this:
https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/configs/_base_/datasets/voc0712.py#L43-L72

**Comment by Meize0729** [comment]
Thank you!
