### ISSUE TITLE
hello, has this problem been solved? I had the same problem.

### ISSUE THREAD

**Issue by ssli23** [open-mmlab/mmdetection#10432]
hello, has this problem been solved? I had the same problem.

_Originally posted by @ssli23 in https://github.com/open-mmlab/mmdetection/issues/9895#issuecomment-1573532307_

**Comment by ssli23** [comment]
analyze_results :KeyError: 'gt_instances' in v3.0.0

**Comment by ssli23** [comment]
ok, I solved it

**Comment by purelovemalehigh** [comment]
> ok, I solved it
I had the same problem.How did you slove the problem?

**Comment by ssli23** [comment]
> I had the same problem.How did you slove the problem?

in mmdetection/mmdet/evaluation/metrics/dump_det_results.py

you can try to comment : l32

remove gt
        # data_sample.pop('gt_instances', None)

**Comment by HePengguang** [comment]
> > I had the same problem.How did you slove the problem?
> 
> in mmdetection/mmdet/evaluation/metrics/dump_det_results.py
> 
> you can try to comment : l32
> 
> remove gt # data_sample.pop('gt_instances', None)

i commented  line 132 and got a new result.pkl, but it didnot work. could you please gice me some advice? thanks
