### ISSUE TITLE
pytorch2onnx RuntimeError: 2.x branch

### ISSUE THREAD

**Issue by Jwy-jump** [open-mmlab/mmdetection#10451]
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray

when I checkout  the 2.x branch, and run this cmd:

Download the pretrained [model](https://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_r101_fpn_1x_coco/cascade_rcnn_r101_fpn_1x_coco_20200317-0b6a2fbf.pth). The model is also available [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/cascade_rcnn/README.md).

To convert the model to ONNX format, use this [script](https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/pytorch2onnx.py).

'python3 tools/deployment/pytorch2onnx.py configs/cascade_rcnn/cascade_rcnn_r101_fpn_1x_coco.py cascade_rcnn_r101_fpn_1x_coco_20200317-0b6a2fbf.pth --output-file cascade_rcnn_r101_fpn_1x_coco.onnx'

It shows the error:
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray

**Comment by tojimahammatov** [comment]
Hi @Jwy-jump , did you solve your problem? Please share the solution as it would be very helpful to others as well. 

The one way I concluded so far is to downgrade torch version, the one mentioned in `Dockerfile` of `2.x` branch may be ok. How was your case?
