### ISSUE TITLE
How can I get feature vectors from predicted bboxes?

### ISSUE THREAD

**Issue by MyLtYkRiTiK** [open-mmlab/mmdetection#1046]
I need features from inside bbox images for further tracking tasks.
How can I get them during detection stage?
Right vectors and in right order?

**Comment by Epiphqny** [comment]
> I need features from inside bbox images for further tracking tasks.
> How can I get them during detection stage?
> Right vectors and in right order?

I think you can use the roi_extractor module to extract bbox feature

**Comment by andreydung** [comment]
@Epiphqny Could you please show an example?

**Comment by kkissmart** [comment]
@hellock any update on this?

I am trying to use ground truth bbox to get an encoded vector. so it is a single stage (without RPN). how to set config to achieve this. I am new here. any help is appreciate it.

Thank you so much in advance!!!!!!!
