### ISSUE TITLE
TypeError: Create both the detector model and the segmentation model in a single script

### ISSUE THREAD

**Issue by wxqiankai** [open-mmlab/mmdetection#10501]
import mmdet.apis as da
import mmseg.apis as sa

det_model = da.init_detector(config_file, checkpoint_file, device='cuda:0')
seg_model = sa.init_model(config_path_seg, checkpoint_path_seg)
result = da.inference_detector(det_model, 'datasets\weice\images\\234.jpeg')
-------------------------------------------------------------------------------------------
if I create mmseg.apis.init_model() behind mmdet.apis.init_detector(), then runing mmdet.apis.inference_detector will error, error info is:
TypeError: class `LoadAnnotations` in mmseg/datasets/transforms/loading.py: LoadAnnotations.__init__() got an unexpected keyword argument 'with_bbox'
--------------------------------------------------------------------------------------------
but if you modification like this,It should be up and running :
det_model = da.init_detector(config_file, checkpoint_file, device='cuda:0')
result = da.inference_detector(det_model, 'datasets\weice\images\\234.jpeg')
seg_model = sa.init_model(config_path_seg, checkpoint_path_seg)
---------------------------------------------------------------------------------------------
why mmseg.apis.init_model() can influence mmdet.apis.init_detector(), they are different model, is it a bug! Does anyone know how to fix it

**Comment by hhaAndroid** [comment]
@wxqiankai 

```python
from mmengine import Registry

seg_model = sa.init_model(config_path_seg, checkpoint_path_seg)
det_model = da.init_detector(config_file, checkpoint_file, device='cuda:0')
with Registry('scope').switch_scope_and_registry('mmdet'):
     result = da.inference_detector(det_model, 'datasets\weice\images\\234.jpeg')
```
