### ISSUE TITLE
Differences from 2.x to 3.x for FasterRCNN for voc-format dataset.

### ISSUE THREAD

**Issue by HaMeow-lst1** [open-mmlab/mmdetection#10502]
Hello, I try to train a FasterRCNN for FLIR-aligned dataset(thermal images, voc2007 format). For model, I use "configs/pascal_voc/faster-rcnn_r50_fpn_1x_voc0712.py". For dataset, I use "configs/_base_/datasets/voc0712.py". I find that compared with mmdetection 2.x, mmdetection 3.x reduces about 25--35 AP50. Also, I find mmdetection 3.x predicts less objects, which leads to low recall.

Could you please tell me the differences for FasterRCNN training voc between mmdetection 2.x and mmdetection 3.x? Thanks a lot!

**Comment by hhaAndroid** [comment]
@HaMeow-lst1 Have you set up the metainfo correctly? You can use `browse_dataset.py` to visualize the dataset to see if it is set up correctly.

**Comment by HaMeow-lst1** [comment]
I address this problem.  I use ```browse_dataset.py``` and find that many small boxes are missing. Then I find the ```configs/_base_/datasets/voc0712.py```. For the train_dataloader,  I change "min_size=32, bbox_min_size=32" into "min_size=0, bbox_min_size=0" and address this problem. Thanks a lot!
