### ISSUE TITLE
Why the number of object classes in config files is 81, not 80?

### ISSUE THREAD

**Issue by goolhanrry** [open-mmlab/mmdetection#1052]
For example, in `configs/faster_rcnn_r50_fpn_1x.py`

https://github.com/open-mmlab/mmdetection/blob/ca7b5216d0a25a59dbfb219d8495f84e67d4bc1e/configs/faster_rcnn_r50_fpn_1x.py#L34-L46

Why does the value of `num_classes` is 81, while COCO dataset has only 80 object classes.

Thank you for your attention!

**Comment by amirassov** [comment]
because `num_classes = num(COCO classes + background)`

**Comment by goolhanrry** [comment]
> because `num_classes = num(COCO classes + background)`

Got it. Thank you so much!

**Comment by tiberium24** [comment]
Could you elaborate a little further why we need to put there "background". What difference does it make if we did not have background?

**Comment by DB11051998** [comment]
Consider if I am training with a class of 3. should I change it from 81 to 4( 3+1(as background))??
