### ISSUE TITLE
在3.0版本的 tools/train.py 中没有 --device 参数，请问怎么在多显卡机上指定单卡训练模型呢？

### ISSUE THREAD

**Issue by fullpw** [open-mmlab/mmdetection#10535]
**Describe the feature**
在3.0版本的 tools/train.py 中没有 --device 参数，请问怎么在多显卡机上指定单卡训练模型呢？

**Motivation**
demo中具有 --device 参数，可以进行cpu和gpu编号的指定，但是tools/train.py 中没有 --device 参数，是否考虑有添加该功能，实现特定编号显卡的指定训练功能，便于多卡机在不同显卡上分配不同任务。

**Comment by furh20** [comment]
CUDA_VISIBLE_DEVICES=x tools/train.py xxxx

**Comment by fullpw** [comment]
@furh20 非常感谢，
CUDA_VISIBLE_DEVICES=x python tools/train.py xxxx
先设置环境变量，再运行代码就行了
