### ISSUE TITLE
Question about the multi node test

### ISSUE THREAD

**Issue by alexwq100** [open-mmlab/mmdetection#1054]
hi,in the code below:
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py#L61, the rank 0 loads the forward result of other ranks through file , but if two or more machines used, the result file will be in different machines ,right?  But the code for transferring the files of other ranks in different machines is not here?

**Comment by hellock** [comment]
Yes you are right. Usually when we are using multiple nodes, there is a shared filesystem, which is the common case for a cluster. We have not implemented the evaluation hook for multiple nodes with independent storages. You can either 1) mount the working directory to the same node, or 2) only do the evaluation within the first node.
