### ISSUE TITLE
fp16 TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by zhiyuuu** [open-mmlab/mmdetection#10597]
When I try to train mask-rcnn with AMP, there comes an error:
```
Traceback (most recent call last):
  File "******", line 135, in <module>
    train_detector(model, datasets, cfg, distributed=False, validate=True)
  File "******\mmdet\apis\train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "D:\ProgramData\Anaconda3\envs\mmdetection\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 117, in run
    self.call_hook('before_run')
  File "D:\ProgramData\Anaconda3\envs\mmdetection\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "D:\ProgramData\Anaconda3\envs\mmdetection\lib\site-packages\mmcv\runner\hooks\optimizer.py", line 253, in before_run
    if 'fp16' in runner.meta and 'loss_scaler' in runner.meta['fp16']:
TypeError: argument of type 'NoneType' is not iterable`
```

Here is part of my code:
```
cfg = Config.fromfile('../configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py')
cfg.fp16 = dict(loss_scale=512.)
```

if without"cfg.fp16 = dict(loss_scale=512.)", there wil be no error

**Comment by zhiyuuu** [comment]
I tried to solve this by adding this code:
```
cfg.fp16 = dict(loss_scale=512.)
cfg.runner.meta = dict(fp16=cfg.fp16)
```
It seems to work, but I don't know if it's right

**Comment by MR-hyj** [comment]
if you need to override some cfg file, better do it before `Config.fromfile()`. 
In your case, create another cfg:
```python
# my_new_cfg.py
_base_ = ['mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py']
fp16 = dict(loss_scale=512)

# main.py
cfg = Config.fromfile('../configs/my_new_cfg.py')
```

**Comment by MR-hyj** [comment]
BTW, I was wondering if there is such a key named '`fp16`  in `mask_rcnn_r50_fpn_1x_coco.py`. So I did a little coding and confirm there originally was not such a key
```python
cfg = Config.fromfile('../configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py')
cfg['fp16']
# out: KeyError: 'fp16'
```

**Comment by zhiyuuu** [comment]
Thanks for your advice, there is `fp16` in `configs/mask_rcnn/mask_rcnn_r50_fpn_fp16_1x_coco.py`, but isn't in `configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py`.


> if you need to override some cfg file, better do it before `Config.fromfile()`. In your case, create another cfg:
> 
> ```python
> # my_new_cfg.py
> _base_ = ['mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py']
> fp16 = dict(loss_scale=512)
> 
> # main.py
> cfg = Config.fromfile('../configs/my_new_cfg.py')
> ```
