### ISSUE TITLE
can't start the training process

### ISSUE THREAD

**Issue by chelixuan** [open-mmlab/mmdetection#106]
I run the command that:
./tools/dist_train.sh /home1/clx/mmdetection/configs/mask_rcnn_r50_fpn_1x.py  2 --work_dir /home1/clx/mmdetection/logs/ --validat

results in terminal :
================================================================================
2018-11-09 10:43:56,631 - INFO - Distributed training: True
2018-11-09 10:43:57,021 - INFO - load model from: modelzoo://resnet50
2018-11-09 10:43:57,776 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer3.2.bn2.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, bn1.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.1.bn3.num_batches_tracked

loading annotations into memory...
loading annotations into memory...
Done (t=10.46s)
creating index...
Done (t=10.46s)
creating index...
index created!
index created!

=========================================================================

the process stopped, and there is noting in my logs file
I don't know what happened~~

**Comment by penincillin** [comment]
This bug might be related to the version of your operating system.
For my own case, I encountered with similar bugs on the server with Ubuntu 14.04 but the code runs well on server with Ubuntu 16.04.

**Comment by penincillin** [comment]
@chelixuan I encountered the same problem and now I solve it. If you have further interest in it, you could contact me and I am willing to help you.

**Comment by ybai62868** [comment]
@penincillin Hi, Can you help me to solve this problem? I encounter the problem like this, but with a Segmentation fault (core dumped)

**Comment by ybai62868** [comment]
@penincillin After updating my GCC, I have run the code successfully.

**Comment by hellock** [comment]
#24 #229
