### ISSUE TITLE
Do I need to recompile the file after adding new detector?

### ISSUE THREAD

**Issue by Epiphqny** [open-mmlab/mmdetection#1061]
I wrote new detector like **Develop new components** in https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md, but adding the detector to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/__init__.py seems not work, it says the detector is not registered, the error is  :

 File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 76, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/workdir/code/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/workdir/code/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/workdir/code/mmdetection/mmdet/utils/registry.py", line 69, in build_from_cfg
    obj_type, registry.name))
KeyError: 'None is not in the detector registry'

Do I need to recompile it?

**Comment by hellock** [comment]
That depends on the way you installed mmdetection. To be short, if you installed it with `pip install -e .` or `python setup.py develop`, then you do not need to reinstall it, otherwise you need to reinstall it after any modifications.

**Comment by Epiphqny** [comment]
> That depends on the way you installed mmdetection. To be short, if you installed it with `pip install -e .` or `python setup.py develop`, then you do not need to reinstall it, otherwise you need to reinstall it after any modifications.

I recompiled it then everything works fine, thank you very much!

**Comment by polarisV0V** [comment]
> > That depends on the way you installed mmdetection. To be short, if you installed it with `pip install -e .` or `python setup.py develop`, then you do not need to reinstall it, otherwise you need to reinstall it after any modifications.
> 
> I recompiled it then everything works fine, thank you very much!

Hi, could you please share the method how to recompile it? Thx!
