### ISSUE TITLE
How to get inference time or fps using the testing script?

### ISSUE THREAD

**Issue by ivder** [open-mmlab/mmdetection#1062]
I tested Faster R-CNN according to the guideline
```
python tools/test.py configs/faster_rcnn_r50_fpn_1x.py \
    checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth \
    --show
```
But I don't see any fps or inference time value. Here's the result on terminal :
```
loading annotations into memory...
Done (t=0.36s)
creating index...
index created!
[                              ] 57/5000, 0.2 task/s, elapsed: 287s, ETA: 24889s
```
I believe the elapsed time is the time that I've spent from the first time I executed the command, and I'm not sure what ETA is. How to get the fps or inference time per image?

**Comment by hellock** [comment]
`task/s` is fps.

**Comment by ivder** [comment]
@hellock thank you

**Comment by huihuixiaohuihui** [comment]
the 0.2 task/s.I think it is not truly fps

**Comment by Asaad-Nasrallah** [comment]
ETA: is remaining time until training process completed , you will notice in last iteration ETA always equal zero
FPS can be calculated using this formula : (1/(task/s))
in your case it will be : (1/0.2)=5 FPS
