### ISSUE TITLE
is the inference api thread safe?

### ISSUE THREAD

**Issue by mosheliv** [open-mmlab/mmdetection#1063]
Instead of using batch inference, that is not available yet, can I use several detectors at once in several threads?

**Comment by hellock** [comment]
It may not be trivial to manipulate multiple threads with PyTorch, but instead it is feasible to use multiple processes. Before PR #622, mmdetection allows running multiple detectors on each GPU, but it is actually slower.

**Comment by mosheliv** [comment]
so no simple way of speeding up inference? I am inferencing 100k images over 7 models... that`s a lot of inference.

**Comment by pkhigh** [comment]
@mosheliv  did u find a way to control threads ?

**Comment by mosheliv** [comment]
no, unfortunately. I have tried to run several instances in parallel but results were slower
