### ISSUE TITLE
Pipeline中的RandomResize是在哪里实现的？

### ISSUE THREAD

**Issue by Hellcat1005** [open-mmlab/mmdetection#10632]
在configs/rtmdet/rtmdet_l_8xb32-300e_coco.py中的train pipline里面，有一个RandomResize，在代码中完全找不到对应的类，其他的图像变换都可以找到。想问一下这个RandomResize是在哪里实现的？

**Comment by liyunlong10** [comment]
You may find the class in "mmcv/transforms/processing.py"
