### ISSUE TITLE
Incorrect rtmdet parameters counts?

### ISSUE THREAD

**Issue by mcusgithub** [open-mmlab/mmdetection#10637]
My question refers to the **rtmdet** model in both mmyolo and mmdetection.

I used mmyolo to train rtmdet but the mmdetection model implementation is identical as far as I know(*) (the training, bn part differs). For instance, for the tiny version:

**mmyolo**
- https://github.com/open-mmlab/mmyolo/blob/dev/configs/rtmdet/rtmdet_tiny_syncbn_fast_8xb32-300e_coco.py
  -  base model: https://github.com/open-mmlab/mmyolo/blob/dev/configs/rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py

**mmdetection**
- https://github.com/open-mmlab/mmdetection/blob/main/configs/rtmdet/rtmdet_tiny_8xb32-300e_coco.py
  - base model: https://github.com/open-mmlab/mmdetection/blob/main/configs/rtmdet/rtmdet_l_8xb32-300e_coco.py

After successfully converting the following RTMDet-s model to ONNX:
- rtmdet_s_syncbn_fast_8xb32-300e_coco.py
- rtmdet_s_syncbn_fast_8xb32-300e_coco_20221230_182329-0a8c901a.pth

I get:
- onnx_opcounter rtmdet_s.onnx
  - Number of parameters in the model: **~11.2M**
Which is quite larger (~ +26%) than the **8.89M** value reported in the [documentation](https://github.com/open-mmlab/mmyolo/tree/dev/configs/rtmdet) and the [publication](https://arxiv.org/pdf/2212.07784.pdf).

The exported ONNX model looks okay in Netron and seems to work as expected.

The number of parameters for other MMDet models I converted the same way (yolov5s, yolov8s, yolov8s-pose, etc...) do not have this issue and the parameter counts I obtain are the same as in the documentation ([yolov5s](https://github.com/ultralytics/yolov5), [yolov8s](https://github.com/ultralytics/ultralytics), [yolov8s-pose](https://docs.ultralytics.com/tasks/pose/)).

Same results using PyTorch: num_params = sum(param.numel() for param in model.parameters())
- (*) Note: I obtained the same param counts for the MMDet and MMYolo implementation

Why is there a discrepancy for the rtmdet models only? Is there an issue?

**Comment by mcusgithub** [comment]
Based on:
https://github.com/open-mmlab/mmyolo/blob/main/docs/en/recommended_topics/complexity_analysis.md

```
python tools/analysis_tools/get_flops.py  configs/rtmdet/rtmdet_s_syncbn_fast_8xb32-300e_coco.py
returns:
==============================
Input shape: torch.Size([640, 640])
Model Flops: 14.835G
Model Parameters: 8.887M
==============================
!!!Please be cautious if you use the results in papers. You may need to check if all ops are supported and verify that the flops computation is correct.
```
which is consistent with the [documentation](https://github.com/open-mmlab/mmyolo/tree/main/configs/rtmdet#readme)

**So**
**get_flops.py  =/= PyTorch**   and
**get_flops.py  =/= onnx_opcounter**   but
**PyTorch == onnx_opcounter**

**Something does not look right...**

**Considering the warning message above, could there be an issue with the advertised values?**

**Comment by mcusgithub** [comment]
I would like someone to prove me wrong on the model size (params count), otherwise rtmdet is not as / more efficient as / than Yolov5 (and above) as claimed.

**Comment by RangiLyu** [comment]
RTMDet uses SepBNHead which shares conv weights between different feature scales. For more details please refer to the 4.3 section of the [tech report](https://arxiv.org/abs/2212.07784) and the [code](https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/mmdet/models/dense_heads/rtmdet_head.py#L530).
The reason why the onnx model is larger than the PyTorch model is that when exporting to onnx, the program will fuse the Conv and BN layers. As a result, the same convolution is combined with different BN layers to generate different parameters. This is a limitation of the deployment code.

**Comment by mcusgithub** [comment]
@RangiLyu Thanks a lot for the explanation, I get it now! So beside the larger size for exported ONNX, the inference speed should not be affected since the number of operations for remains the same? Is that right, just to make sure I'm not missing something again.Thanks.
