### ISSUE TITLE
[Docs issue] RTMDet metafile *likely* has incorrect memory usage size for ins-x model

### ISSUE THREAD

**Issue by ryanalexmartin** [open-mmlab/mmdetection#10640]
The X (for eXtra-large?) model has:
```
      Training Memory (GB): 33.7
```
while the smaller Ins-L model (large?) has:
```
      Training Memory (GB): 59.8
```

I believe this is a typo, but I did not find any information or table in the research paper that has the correct information.

**Comment by RangiLyu** [comment]
Please notice that the RTMDet-Ins-x is trained with a mini batch size of 16 instead of 32.
![image](https://github.com/open-mmlab/mmdetection/assets/12907710/670fa967-57c2-4114-ab27-51a564f83f69)
