### ISSUE TITLE
[Docs: Getting Started] unable to verify installation

### ISSUE THREAD

**Issue by evdcush** [open-mmlab/mmdetection#10649]
**Describe the bug**

Hello and thank you for your support! 🙇🏻‍♂️ 

I am trying to verify my installation, following the steps in: [`getting-started#verify-installation`](https://mmdetection.readthedocs.io/en/latest/get_started.html#verify-the-installation).

I followed the installation instructions, but I am unable to run the installation verification step,

neither from the terminal:

```
$ python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cpu
Traceback (most recent call last):
  File "/home/foo/mmdetection/demo/image_demo.py", line 5, in <module>
    from mmdet.apis import (async_inference_detector, inference_detector,
  File "/home/foo/.pyenv/versions/foo-env/lib/python3.11/site-packages/mmdet/__init__.py", line 10, in <module>
    mmcv_version = digit_version(mmcv.__version__)
                                 ^^^^^^^^^^^^^^^^
AttributeError: module 'mmcv' has no attribute '__version__'
```

nor from a python interpreter:

```python
In [1]: from mmdet.apis import init_detector, inference_detector
   ...: 
   ...: config_file = 'rtmdet_tiny_8xb32-300e_coco.py'
   ...: checkpoint_file = 'rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth'
   ...: model = init_detector(config_file, checkpoint_file, device='cpu')  # or device='cuda:0'
   ...: inference_detector(model, 'demo/demo.jpg')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from mmdet.apis import init_detector, inference_detector
      3 config_file = 'rtmdet_tiny_8xb32-300e_coco.py'
      4 checkpoint_file = 'rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth'

File ~/Projects/mmdetection/mmdet/__init__.py:21
     19 mmcv_minimum_version = '1.3.17'
     20 mmcv_maximum_version = '1.8.0'
---> 21 mmcv_version = digit_version(mmcv.__version__)
     24 assert (mmcv_version >= digit_version(mmcv_minimum_version)
     25         and mmcv_version <= digit_version(mmcv_maximum_version)), \
     26     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
     27     f'Please install mmcv>={mmcv_minimum_version}, <={mmcv_maximum_version}.'
     29 __all__ = ['__version__', 'short_version']

AttributeError: module 'mmcv' has no attribute '__version__'
```

I either get the above `__version__` error, or I get:

```
ModuleNotFoundError: No module named 'mmcv._ext'
```

What I've tried:

- uninstall/reinstall `mmcv` via pip
- uninstall/reinstall `mmcv` via `mim`
- uninstall/reinstall `mmcv-lite` via pip and `mim`

Nothing has worked for the installation verification.

**Reproduction**

Follow the steps in https://mmdetection.readthedocs.io/en/latest/get_started.html#installation

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

☝🏻 **This does not work either**

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch: `pip`
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Comment by MahejabeenNidhi** [comment]
Hello, the following worked for me. I would suggest trying it in a fresh new environment. 

### Creating an environment

```
conda create --name openmmlab python=3.8 -y
```

Check the CUDA version. Mine is 11.3. Yours may be different.
```
nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

Install compatible PyTorch. Mine is 1.12.1. Check which PyTorch version is compatible with yours. 
```
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
```

Check if cuda is enabled for the torch install

Execute the following command 
```
python -c 'import torch;print(torch.cuda.is_available(), torch.__version__)'
```

Or open the Python interpreter and run the following
```
import torch
torch.cuda.is_available()
```

### Installing MMDetection with Tracking

Installing the dependencies
```
pip install lap
```
```
pip install -U openmim
```
```
mim install mmengine
```
```
mim install mmcv>=2.0.0rc4
```
Cloning mmdetection and installing it with tracking requirements
```
git clone https://github.com/open-mmlab/mmdetection.git
```
```
cd mmdetection
```
```
pip install -v -e . -r requirements/tracking.txt
# "-v" means verbose, or more output
# "-e" means installing a project in editable mode,
# thus any local modifications made to the code will take effect without reinstallation.
```
Installing TrackEval
```
pip install git+https://github.com/JonathonLuiten/TrackEval.git
```
Validating the installation of MMDetection
```
mim download mmdet --config rtmdet_tiny_8xb32-300e_coco --dest .
```
```
python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cpu
```
Validating the tracking 
```
mim download mmdet --config bytetrack_yolox_x_8xb4-amp-80e_crowdhuman-mot17halftrain_test-mot17halfval --dest .
```
```
python demo/mot_demo.py demo/demo_mot.mp4 bytetrack_yolox_x_8xb4-amp-80e_crowdhuman-mot17halftrain_test-mot17halfval.py --checkpoint bytetrack_yolox_x_crowdhuman_mot17-private-half_20211218_205500-1985c9f0.pth --out mot.mp4
```

**Comment by edehino** [comment]
@MahejabeenNidhi I am also having problems with mmdetection setup. Currently operating on windows. When i check my nvcc version, it prompts as unrecognized command. But when I use `nvidia-smi` , it shows my cuda version. 

Should I have to install cuda on my bare unit?

**Comment by evdcush** [comment]
Thanks for your consideration and suggestions @MahejabeenNidhi!

I have the same question as @edehino.

Is CUDA required for `mmdetection`?
I should clarify that I am attempting to verify my installation of `mmdet` on a CPU-only machine.

**Comment by evdcush** [comment]
Also, I am not using conda.
I am using virtualenvs managed through `pyenv`.

If `mmdet` only works through conda, that should be documented 🤔

**Comment by evdcush** [comment]
Closing this issue unresolved.

**Comment by evdcush** [comment]
For those who pip-installed `mmcv`, expecting that to install a working `mmcv`, but encounter the error:

```
ModuleNotFoundError: No module named 'mmcv._ext'
```

It appears you must install the mmcv build from an index that corresponds to your env:

Ref: https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip


**GPU**:

```
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html
```


**CPU** (unconfirmed):

```
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch2.1/index.html
```

**Comment by ioangatop** [comment]
I did the same as @evdcush but for CPU (as I have MacBook) but it does not seem to work..

**Comment by tam-trance** [comment]
After many similar errors, I got the installation working! Sharing the step-by-step in case it helps anyone else out :) 
https://github.com/open-mmlab/mmdetection/issues/12404

**Comment by evdcush** [comment]
> After many similar errors, I got the installation working! Sharing the step-by-step in case it helps anyone else out :) `[#12404](https://github.com/open-mmlab/mmdetection/issues/12404)`

This is the same solution as I commented here:
https://github.com/open-mmlab/mmdetection/issues/10649#issuecomment-1784000263

> It appears you must install the mmcv build from an index that corresponds to your env:
> 
> Ref: https://mmcv.readthedocs.io/en/latest/get_started/installation.html#install-with-pip
> 
> 
> **GPU**:
> 
> ```
> pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html
> ```
> 
> 
> **CPU** (unconfirmed):
> 
> ```
> pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch2.1/index.html
> ```
