### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by Younger330** [open-mmlab/mmdetection#10659]
**I'm trying to run python setup.py develop
but have the folloing error
I have no idea about how to solve this problem**
`setup.py:9: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.Distribution().fetch_build_eggs(['Cython', 'numpy>=1.11.1'])
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '1.0.rc0+c64beaf' to '1.0rc0+c64beaf'
  self.metadata.version = self._normalize_version(
running develop
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.nms.soft_nms_cpu' extension
Emitting ninja build file /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -L/home/aaa/anaconda3/envs/mmdet5/lib -Wl,-rpath=/home/aaa/anaconda3/envs/mmdet5/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-cpython-38/mmdet/ops/nms/soft_nms_cpu.cpython-38-x86_64-linux-gnu.so
building 'mmdet.ops.nms.nms_cpu' extension
Emitting ninja build file /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -L/home/aaa/anaconda3/envs/mmdet5/lib -Wl,-rpath=/home/aaa/anaconda3/envs/mmdet5/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/nms/src/nms_cpu.o -L/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/lib -L/home/aaa/anaconda3/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/mmdet/ops/nms/nms_cpu.cpython-38-x86_64-linux-gnu.so
building 'mmdet.ops.nms.nms_cuda' extension
Emitting ninja build file /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -L/home/aaa/anaconda3/envs/mmdet5/lib -Wl,-rpath=/home/aaa/anaconda3/envs/mmdet5/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/nms/src/nms_cuda.o /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/nms/src/nms_kernel.o -L/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/lib -L/home/aaa/anaconda3/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/mmdet/ops/nms/nms_cuda.cpython-38-x86_64-linux-gnu.so
building 'mmdet.ops.roi_align.roi_align_cuda' extension
Emitting ninja build file /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -L/home/aaa/anaconda3/envs/mmdet5/lib -Wl,-rpath=/home/aaa/anaconda3/envs/mmdet5/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/roi_align/src/roi_align_cuda.o /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/roi_align/src/roi_align_kernel.o -L/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/lib -L/home/aaa/anaconda3/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/mmdet/ops/roi_align/roi_align_cuda.cpython-38-x86_64-linux-gnu.so
building 'mmdet.ops.roi_pool.roi_pool_cuda' extension
Emitting ninja build file /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/roi_pool/src/roi_pool_cuda.o.d -pthread -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/TH -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/THC -I/home/aaa/anaconda3/include -I/home/aaa/anaconda3/envs/mmdet5/include/python3.8 -c -c /home/aaa/disk1/mmdetection/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp -o /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/roi_pool/src/roi_pool_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/roi_pool/src/roi_pool_cuda.o 
c++ -MMD -MF /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/roi_pool/src/roi_pool_cuda.o.d -pthread -B /home/aaa/anaconda3/envs/mmdet5/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/TH -I/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/THC -I/home/aaa/anaconda3/include -I/home/aaa/anaconda3/envs/mmdet5/include/python3.8 -c -c /home/aaa/disk1/mmdetection/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp -o /home/aaa/disk1/mmdetection/build/temp.linux-x86_64-cpython-38/mmdet/ops/roi_pool/src/roi_pool_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/aaa/disk1/mmdetection/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp:1:
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
In file included from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/core/Device.h:5:0,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/aaa/disk1/mmdetection/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp:1:
/home/aaa/disk1/mmdetection/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp:23:34: error: stray ‘#’ in program
   TORCH_CHECK(x.is_contiguous(), #x, " must be contiguous ")
                                  ^
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:214:80: note: in definition of macro ‘C10_THROW_ERROR’
   throw ::c10::err_type({__func__, __FILE__, static_cast<uint32_t>(__LINE__)}, msg)
                                                                                ^~~
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:318:3: note: in expansion of macro ‘TORCH_CHECK_WITH_MSG’
   TORCH_CHECK_WITH_MSG(error_t, cond, "", __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:341:32: note: in expansion of macro ‘TORCH_CHECK_WITH’
 #define TORCH_CHECK(cond, ...) TORCH_CHECK_WITH(Error, cond, __VA_ARGS__)
                                ^~~~~~~~~~~~~~~~
/home/aaa/disk1/mmdetection/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp:23:3: note: in expansion of macro ‘TORCH_CHECK’
   TORCH_CHECK(x.is_contiguous(), #x, " must be contiguous ")
   ^~~~~~~~~~~
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:330:3: error: expected unqualified-id before ‘if’
   if (C10_UNLIKELY_OR_CONST(!(cond))) {                               \
   ^
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:318:3: note: in expansion of macro ‘TORCH_CHECK_WITH_MSG’
   TORCH_CHECK_WITH_MSG(error_t, cond, "", __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~
/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:341:32: note: in expansion of macro ‘TORCH_CHECK_WITH’
 #define TORCH_CHECK(cond, ...) TORCH_CHECK_WITH(Error, cond, __VA_ARGS__)
                                ^~~~~~~~~~~~~~~~
/home/aaa/disk1/mmdetection/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp:23:3: note: in expansion of macro ‘TORCH_CHECK’
   TORCH_CHECK(x.is_contiguous(), #x, " must be contiguous ")
   ^~~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 131, in <module>
    setup(
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
    self.run_command('build_ext')
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/aaa/anaconda3/envs/mmdet5/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension`

**Comment by somnusyyy** [comment]
Here is my environment:
python 3.8.16
mmcv 2.0.1
torch 1.7.1
torchvision 0.8.12
And I have already replace AT_CHECK with TORCH_CHECK

**Comment by somnusyyy** [comment]
and the version of gcc and g++ are 7.5.0
