### ISSUE TITLE
How to use images without objects as negative samples

### ISSUE THREAD

**Issue by shallweiwei** [open-mmlab/mmdetection#10666]
If I want to use many images without objects as negative samples, how should I define the COCO format or how to train it. My current training method does not seem to use these images without objects

**Comment by hhaAndroid** [comment]
@shallweiwei 

```python
train_dataset = dict(dataset=dict(filter_cfg=dict(filter_empty_gt=False, min_size=32)))
```

filter_empty_gt

**Comment by shallweiwei** [comment]
I have used this,it didn't work.I have some background images without any objects.

**Comment by shallweiwei** [comment]
(^_^) Thanks.I have solved this,it's because I made mistakes in json file.All of the background images had the same id……

**Comment by JNaranjo-Alcazar** [comment]
Hi, where do I have to add this line?
to my config file?
