### ISSUE TITLE
How to use SyncBN on Backbone

### ISSUE THREAD

**Issue by VectorYoung** [open-mmlab/mmdetection#1069]
Hi, I see that in the technical report you did experiments with SyncBN. I am wondering how to use it. I want to apply it only to the 'Backbone'. Could you please offer some help? Thanks.

**Comment by cizhenshi** [comment]
add  norm_cfg = dict(type='SyncBN', requires_grad=True) in your config file

**Comment by harryhan618** [comment]
> add norm_cfg = dict(type='SyncBN', requires_grad=True) in your config file

I see almost config files don't have SyncBN. May I ask why SyncBN is not used?

**Comment by hellock** [comment]
SyncBN is a known trick for improving the performance. Most papers did not report the performance with syncbn as their main results. For fair comparison, we also follow the typical convention.
