### ISSUE TITLE
Image based 3d bounding box using Centernet

### ISSUE THREAD

**Issue by kshashankrao** [open-mmlab/mmdetection#10699]
**Describe the feature**
In Centernet (object as points) paper, the author describe the method to detect 3d bounding box using monocular images from kitti.
**Do you have plans to implement it in mmdetection3d ?**

**Motivation**
It would be nice if all the applications of centernet are implemented
 in a single framework. 
**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hhaAndroid** [comment]
@kshashankrao You can go to the MMDetection3D ask.
