### ISSUE TITLE
Are you planning to support co-detr in mmdetection 3.x and when?

### ISSUE THREAD

**Issue by Artificial-Inability** [open-mmlab/mmdetection#10704]
https://github.com/Sense-X/Co-DETR has co-detr implementation in mmdetection 2.x, are you planning to implement in mmdet 3.x and when?

**Comment by hhaAndroid** [comment]
@Artificial-Inability Yes. However, due to limited manpower, it may take a while. The community is welcome to contribute.

**Comment by VanLinLin** [comment]
@Artificial-Inability Hi, can you tell me where is the Co-DETR implement in mmdetection==2.28.0? I can only find the deformable_detr in config folder.

**Comment by Artificial-Inability** [comment]
> @Artificial-Inability, @hhaAndroid Hi, can you tell me where is the Co-DETR implement in mmdetection==2.28.0? I can only find the deformable_detr in config folder.

It's under the projects folder not config folder

**Comment by VanLinLin** [comment]
@Artificial-Inability Oh, I see. Thanks for your reply!

**Comment by hhaAndroid** [comment]
@Artificial-Inability https://github.com/open-mmlab/mmdetection/pull/10740
