### ISSUE TITLE
There is a misspelling in test_time_augs/merge_augs.py

### ISSUE THREAD

**Issue by traptinblur** [open-mmlab/mmdetection#10718]
In function `merge_aug_masks`, there is a misspelling:
``` python
flip = img_metas.get('filp', False)  #  flip = img_metas.get('flip', False)
```

**Comment by RangeKing** [comment]
@traptinblur Thanks for pointing out the mistake. Here is the [PR](https://github.com/open-mmlab/mmdetection/pull/10746) which fixes the misspelling.
