### ISSUE TITLE
How to set the img_scale parameter？

### ISSUE THREAD

**Issue by zihaozhang9** [open-mmlab/mmdetection#1071]
I am using the mask_rcnn_r50_fpn_1x.py configuration script. I have prepared my own data. I found that objects with smaller targets in my data were not recognized. My image size is (2748, 3840) and the smallest object is probably (36, 36).
How should img_scale be set?
Is it guaranteed that the minimum object pixel is greater than 1 after four times of downsampling?

**Comment by zihaozhang9** [comment]
When I set img_scale to (1374, 1920), the smallest object can be identified.
Still curious, what is the smallest object that can be detected? Four pixel sizes?
I am very much looking forward to someone to answer. Many thanks.

**Comment by sunpeng981712364** [comment]
I also have the same puzzle.  Do you try to train model with the orginal size?

**Comment by shanggdlk** [comment]
> When I set img_scale to (1374, 1920), the smallest object can be identified.
> Still curious, what is the smallest object that can be detected? Four pixel sizes?
> I am very much looking forward to someone to answer. Many thanks.

I think it depends on the anchor size. By default, the anchor size (after scaling) would be (32,64,128,256,612). So the smallest anchor size is 32x32. Let's say your ground-truth bbox is MxM, if MxM/(32x32) < 0.3, it will be recognized as background. So I think there are basically two ways to solve this problem: 1): crop your image and zoom-in each part by 2X or even 4X. By doing so, your ground-truth bbox size will get larger; do not try resizing the image using img_scale, coz a very larger size would consume up all GPU, hence introduce long latency. 2): adjust the anchor size in mask-rcnn/faster-rcnn etc.

**Comment by zihaozhang9** [comment]
> crop your image and zoom-in each part by 2X or even 4X. By doing so, your ground-truth bbox size will get larger; do not try resizing the image using img_scale, coz a very larger size would

very thank~
I am using [mask_rcnn_r101_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r101_fpn_1x.py)
1 、If I want to modify the cropped image, is it to modify the code [__getitem__](https://github.com/open-mmlab/mmdetection/blob/44ff99831a7ed1a4f14dd240b69e74d88d7944f5/mmdet/datasets/custom.py#L177)?
2 、anchor size  modify [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r101_fpn_1x.py#L22)?Set to 0.2 or less?

**Comment by zihaozhang9** [comment]
I saw the [code](https://github.com/open-mmlab/mmdetection/blob/d2483e15fc48b4166815c15a6e12be864bcc521a/mmdet/models/anchor_heads/anchor_head.py#L72).
If I want to detect smaller objects, I should modify the [anchor_scales](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r50_fpn_1x.py#L21).
If I modify anchor_scales=[4]. Anchor_strides=[4, 8, 16, 32, 64]. Anchor_scales*anchor_strides=[16, 32, 64, 128, 256]。Where is parameter 0.3 set?

**Comment by Zhangjiacheng144** [comment]
I'm still puzzled, if I use the anchor-free detection methods, and I use my own dataset, how should I set img_scale?
