### ISSUE TITLE
How to export model to onnx without post-processing

### ISSUE THREAD

**Issue by hanjian-code** [open-mmlab/mmdetection#10723]
I used mmdeploy to convert the model to ONNX, but I found that this converted ONNX model comes with post-processing. The following two figures are the onnx model obtained by using mmdeploy conversion and the structure of Direct YOLO conversion. How do I put the model into the form of yolo, by modifying the model's source code, or by modifying it in mmdeploy.

**Comment by hanjian-code** [comment]
![image](https://github.com/open-mmlab/mmdetection/assets/84496932/8e1f4796-6acb-4cb3-aed8-ca13cef87a85)
![image](https://github.com/open-mmlab/mmdetection/assets/84496932/f72d1ecb-8e09-4d32-a3b9-caeb5cf8324f)

**Comment by hanjian-code** [comment]
![image](https://github.com/open-mmlab/mmdetection/assets/84496932/ec0caff6-b5e1-448b-b8f3-6e7793a94b86)

**Comment by hhaAndroid** [comment]
@hanjian-code Please go directly to the mmdeployrepository and open an issue there.
