### ISSUE TITLE
Hi, is there any plans for support windows?

### ISSUE THREAD

**Issue by fatLime** [open-mmlab/mmdetection#1072]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hellock** [comment]
We have no official plan to test it on windows since we do not have any windows servers, but community support is available and it should work well now.

**Comment by trungpham2606** [comment]
@hellock I had followed the pull request of @wswday for building this repo on Windows but seems there's a bug.

**Comment by hellock** [comment]
#1088
