### ISSUE TITLE
How do I train on a custom dataset format with CocoMetric in 3.x?

### ISSUE THREAD

**Issue by dpovision** [open-mmlab/mmdetection#10735]
### Prerequisite

- [x] I have read the docs, especially chapter [customize_dataset](https://mmdetection.readthedocs.io/en/latest/advanced_guides/customize_dataset.html#reorganize-new-data-format-to-middle-format)
- [x] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions)
- [x] Environment is: '3.1.0'

### Task
I want to run a detection model with my own dataset format.
The dataset format is in json style with an annotation file for each image.
The evaluation should be done with the CocoMetric.

So far I have a successful registration of `MyDataset`in `/mmdet/datasets/`and overwritten the functions `load_data_list`and `parse_data_info` to provide the new data format in middle format.

### Behaviour

If I provide an `ann_file` the `mmdet/evaluation/coco_metric.py/__init__` method raises an error at `self._coco_api = COCO(local_path)`, since it is expecting one annotation file in COCO format. This is plausible so far, since I have my own annotations files in a specific format.
But the other way round if no `ann_file` is provided, the training starts and the `process` method of `coco_metric.py` complains in the evaluation phase with: 
`AssertionError: ground truth is required for evaluation when ann_file is not provided`. 
Actually I have provided the required `instances` as ground truth data via method `parse_data_info` of `MyDataset.py`,  but the `data_sample` of `CocoMetric/process` method does not get the information. Unfortunately, I am not sure what I am overseeing here.

### Question

Which module or function is best to overwrite? 
Is there any `LoadAnnotation` method I missed or do I have to subclass the `metrics\coco_metric.py`and override its methods, like `__init__`, `process` etc.?

Sorry, I have really searched the docs and found no hints what is the most convenient way and would really appreciate your help.

**Comment by MjdMahasneh** [comment]
what model are you training and what do you mean with coco metric? the default evaluation metrics in mmdetection are coco metrics!

have a look at the documentation here:


https://mmengine.readthedocs.io/en/latest/tutorials/evaluation.html?highlight=coco#using-multiple-evaluation-metrics

**Comment by dpovision** [comment]
Yes, exactly the default metric is coco metric and I am using it.

`val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'train.txt',
    metric='bbox',
    format_only=False,
    backend_args=backend_args)
test_evaluator = val_evaluator
`
But my problem is that I do not want to convert my custom dataset annotation format to standard COCO or PASCAL format, but nevertheless use the coco metric. And I am not sure which function I should override in the `mmdet/`directory.
After chapter [Reorganize new data format to middle format](https://mmdetection.readthedocs.io/en/latest/advanced_guides/customize_dataset.html#reorganize-new-data-format-to-middle-format) I have to register a new DATASETS module and inherit from base class `BaseDetDataset` as well as to override the methods 'load_data_list' and 'parse_data_info'. This I have done so far. But then the module `mmdet\evaluation\metrics\coco_metric.py`throws errors, because it is not using the `middle format` data and unfortunately expecting the standard COCO annotation file format, if I do not oversee something here.  

So the question is, what else do I have to override or provide to use my custom dataset format (with one annotation file for each image)? 
Do I also have to override the coco_metric.py module? But this seems a bit cumbersome to me, there is maybe an easier solution? Especially because there is already a `middle format` with ground truth data. 

Currently I am using faster-rcnn_r50_fpn.py as base model.

**Comment by MjdMahasneh** [comment]
I strongly recommend converting to the coco format as shown in the demo notebook for faster RCNN, it is just more intuitive and easier to deal with. it also is very easy to do, so I can't really see the reason why would you take other routes? maybe if you provide me with more context then I can help further.


However, from your comment above, particularly _"(with one annotation file for each image)"_ my understanding of this comment is that you are using a separate annotation file per image, if that is the case, then it might be the reason why you are facing issues, in the documentation https://mmdetection.readthedocs.io/en/latest/advanced_guides/customize_dataset.html#reorganize-new-data-format-to-middle-format it clearly says: _"The metainfo is a dictionary, which contains the metadata of the dataset, such as class information; data_list is a list, each element in the list is a dictionary, the dictionary defines the raw data of one image, and each raw data contains a or several training/testing samples."_ 

meaning that all annotation (of all images) must be in the same file.


Kindly note that this is my guess and understanding of the situation, and i have not done any technical inspection to confirm my speculation, so maybe try having all annotations in a single file, or better (in my opinion) is to stick to coco format as it is easy and very versatile.

Hope this helps.

**Comment by dpovision** [comment]
Yes, thank you very much.
Now, I have just written a converter which is converting my dataset into coco format and it is working fine so far. 

Do you know if in future it is planned to support one separate annotation file per image? 
With the conversion option into `middle format` it would be a really nice feature to use an arbitrary dataset annotation format with different metrics. So one could save the intermediate step of dataset conversion into coco format.

**Comment by dpovision** [comment]
Thank you very much for your answer, this would be a great option...

I have overseen it, because in the documentation [convert_balloon_to_coco](https://mmdetection.readthedocs.io/en/latest/user_guides/train.html#coco-annotation-format) and the code in your last post, I assumed it is just converting the balloon dataset to coco as annotation file on disk as a separate step? Because there is the function parameter `out_file` and in the docu it seems to be a separately callable script.

```
## your code from last post and then the next lines from the docu...

if __name__ == '__main__': 
    convert_balloon_to_coco(ann_file='data/balloon/train/via_region_data.json',
                            out_file='data/balloon/train/annotation_coco.json',
                            image_prefix='data/balloon/train')
    convert_balloon_to_coco(ann_file='data/balloon/val/via_region_data.json',
                            out_file='data/balloon/val/annotation_coco.json',
                            image_prefix='data/balloon/val')
```


Sorry, I have not seen it yet... at what place do I have to integrate my `def convert_my_data_to_coco` function?

**Comment by MjdMahasneh** [comment]
ah youre right, it does write it to disk, which BTW is even better. because now once it has been written to disk, you won't need to re-run the function again, you can use pass the generated file to config and the data loading workers will take care of the rest..

does that make sense? 


any how, to answer your question, you replace the function called _convert_balloon_to_coco()_ in [Faster RCNN demo](https://github.com/open-mmlab/mmdetection/blob/main/demo/MMDet_Tutorial.ipynb) by your own function, in fact convert_balloon_to_coco() gives you a great starting point.


I strongly suggest you follow the demo and adapt it to your needs, it is always good to do this, in the end, that is literally the point of open source.. 


be careful when referencing the documentation, make sure you're reading the right docs consistently with your mmdetection version (e.g., 2.x vs 3.x), there has been a lot of changes.

**Comment by dpovision** [comment]
Yes, it makes sense and works for me. 
Thank you very much for your help and your fast responses. 

I close this issue, because all questions are answered. Thank you. :-)
