### ISSUE TITLE
Failde building wheel for mmpycocotools

### ISSUE THREAD

**Issue by xwhkkk** [open-mmlab/mmdetection#10730]
When I run  `pip install mmpycocotools`,  it has the following  error
![image](https://github.com/open-mmlab/mmdetection/assets/50388024/d4f6d2a6-8587-40db-a26f-62551842445a)
The version of mmcv-full and mmdet is 1.2.2 and 2.4.0 ,respectively.
Could you give me some suggestions ?

**Comment by zimenglan-sysu-512** [comment]
hi @xwhkkk did u solve?

**Comment by zimenglan-sysu-512** [comment]
hi @xwhkkk 
installing cython==0.29.33 works for me

**Comment by xwhkkk** [comment]
> hi @xwhkkk installing cython==0.29.33 works for me

Hi, sorry for the late reply. 
I followed your suggestion installing Cython == 0.29.33, and it finally made it! Thank you very much!

**Comment by tlhopl** [comment]
@zimenglan-sysu-512 
you save my life.. Thanks a lot

**Comment by kinredon** [comment]
@zimenglan-sysu-512 Thanks very much!!, I have been stuck on this issue for two days. The official maintainer of mmdet gives the advice to use the latest version of the mmdet. But there are many projects which are built from the old version of mmdet. Thank you a lot again.

**Comment by hubutui** [comment]
FYI, see also https://github.com/open-mmlab/cocoapi/issues/30#issuecomment-1997672112

**Comment by lishiqiang2019** [comment]
> hi @xwhkkk installing cython==0.29.33 works for me
that works for me ,thanks a lot

**Comment by kartikeyporwal** [comment]
and this still works when we have `cython==3.0.11` out!

**Comment by ChickenSellerRED** [comment]
> > hi @xwhkkk installing cython==0.29.33 works for me
> 
> Hi, sorry for the late reply. I followed your suggestion installing Cython == 0.29.33, and it finally made it! Thank you very much!

Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by xusheng-code** [comment]
> hi @xwhkkk
> installing cython==0.29.33 works for me

it also helps me to build the wheel for mmpycocotools.

Thanks!!!

**Comment by G-Apple1** [comment]
> hi @xwhkkk installing cython==0.29.33 works for me

Thank you very much!! I have found that the version of pip is also important. The 24.2 version of pip that I am using cannot successfully install cython==0.29.33, so I need to downgrade the version to 24.0.

**Comment by lhx-666-cool** [comment]
thanks!!!

**Comment by yang13ca** [comment]
thanks!!!

**Comment by KeepNoob** [comment]
> hi @xwhkkk installing cython==0.29.33 works for me

Thanks !!!
