### ISSUE TITLE
mmcv building wheel fails on CUDA 12.1 (Pytorch Nightly)

### ISSUE THREAD

**Issue by bluejaelly** [open-mmlab/mmdetection#10748]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I tried to install everything as mentioned here: https://mmdetection.readthedocs.io/en/latest/get_started.html. While I was able to get past most steps, I cannot install mmcv using mim. This seems to be linked to the fact that I have CUDA 12.1 and using the latest version of Pytorch Nightly. I believe this is the issue: "\anaconda3\envs\openmmlab\lib\site-packages\torch\include\c10/util/C++17.h(27): fatal error C1189: #error:  You need C++17 to compile PyTorch". Is there any way I can circumvent this issue

**Reproduction**

1. What command or script did you run?

```
mim install "mmcv>=2.0.0"
```

Trying to run the RTMDet model :))

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
C:\anaconda3\envs\openmmlab\lib\site-packages\torch\include\c10/util/C++17.h(27): fatal error C1189: #error:  You need C++17 to compile PyTorch
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

**Comment by hhaAndroid** [comment]
@bluejaelly Please go directly to the mmcv repository and open an issue there.
