### ISSUE TITLE
Specific class AP appears to be 0 in KITTI

### ISSUE THREAD

**Issue by sangjinpark97** [open-mmlab/mmdetection#10741]
Hi, 

I implemented IA-SSD on the mmdetection3d. (Original repo of IA-SSD is based on OpenPCdet)

I'm trying to train IA-SSD on the KITTI dataset.

But, the pedestrian AP appears to be 0 for all metrics, and those of other classes are reasonable.

First, I think that it could be underfitting for the pedestrian class (actually, visualization results show that the model cannot detect the pedestrian).
However, I changed the order of class_names of the configuration file because I suspect the evaluation issue that may be caused by the conversion of the codebase (pcdet to mmdet3d).

["Pedestrian, "Cyclist", "Car"] > ["Car", "Pedestrian, "Cyclist"]

 Then, in this time, the Car AP appears to be 0 for all metrics! It doesn't make sense and I could not figure out why this happens.

I just use the model code of IA-SSD, create a configuration, and don't use any other part of pcdet.

Can you assume the reason?
Thank you in advance!

**Comment by hhaAndroid** [comment]
@sangjinpark97 Please go directly to the mmdet3d repository and open an issue there.
