### ISSUE TITLE
How can I migrate mmdetection version 2 to version 3

### ISSUE THREAD

**Issue by juneodie** [open-mmlab/mmdetection#10742]
I have couple of models trained using mmdetection version 2.
I'm trying to migrate my model into version 3. 
I followed the config migration rule and tried running my model on mmdetection version 3 using that config.
The result was same with yolox model but not with mask_r_cnn.( trained with mmdet 2, tested with mmdet 3)
Please let me know the general migration rule that works well in any model

**Comment by hhaAndroid** [comment]
@juneodie Can you briefly describe the issue you encountered? Alternatively, you can provide feedback in the community's WeChat group.

**Comment by juneodie** [comment]
> @juneodie Can you briefly describe the issue you encountered? Alternatively, you can provide feedback in the community's WeChat group.

Oh I solved my problem. There was an error on my config.
