### ISSUE TITLE
How to train subset classes in coco？

### ISSUE THREAD

**Issue by zengziru** [open-mmlab/mmdetection#10754]
If I only want to train subset of the 80 classes in the coco dataset, like: person. Should I just modify num_classes and metainfo without changing the original coco label.json file, or should I also modify the original coco label.json file?

**Comment by hhaAndroid** [comment]
@zengziru https://github.com/open-mmlab/mmdetection/blob/main/configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person-bicycle-car.py
