### ISSUE TITLE
When will RSPrompter be merged into mmdetection

### ISSUE THREAD

**Issue by uyzhang** [open-mmlab/mmdetection#10753]
Can you provide an overview of the progress？
The paper's title is 'RSPrompter: Learning to Prompt for Remote Sensing Instance Segmentation based on Visual Foundation Model'

**Comment by hhaAndroid** [comment]
@uyzhang Thank you very much for your attention. The RSPrompteralgorithm is currently supported by the authors of the paper, so it is necessary to communicate with them regarding the current progress.
