### ISSUE TITLE
How can I fine-tune a specific category?

### ISSUE THREAD

**Issue by MingHanLee** [open-mmlab/mmdetection#10767]
My current detector currently outputs two categories. Later, I performed fine-tuning specifically for the second category. However, the detector after fine-tuning can only detect the second category. How should I fix this issue?
Thanks!

**Comment by ryylcc** [comment]
what type of data you use for fine-tuning? whether the data only comes from the second category?

**Comment by MingHanLee** [comment]
Currently, the model can detect both persons and baseball bats. I collected additional images specifically for baseball bats and labeled them in the Coco format. I intend to improve the accuracy of baseball bat detection. Is it possible to fine-tune the model using a dataset containing only baseball bats while retaining the detection capability for persons?
Thanks!

**Comment by ryylcc** [comment]
Fine-tuning a model with data only from a specific category is hard to retain the detection capability for other categories, you can try to fine-tune the model with lots of data of baseball bats and a little of persons. Training model with a subset of COCO can be referred to [faster-rcnn_r50-caffe_fpn_ms-1x_coco-person-bicycle-car.py](https://github.com/open-mmlab/mmdetection/blob/main/configs/faster_rcnn/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person-bicycle-car.py).
