### ISSUE TITLE
如何改变推理框颜色

### ISSUE THREAD

**Issue by zbf1-999** [open-mmlab/mmdetection#10765]
请问如何改变推理单张图片时推理框的颜色，我想要更换成和mmdetection2同款的蓝色，但我无法找到文件的具体位置，另外可以告诉我mm2中蓝色的RGB吗

**Comment by HAOCHENYE** [comment]
框的颜色默认是由 dataset METAINFO 中 palette 字段的值决定的，你可以在配置文件中，通过配置 metainfo 参数来改变 palette。

```python
train_dataset = dict(
    ...
    metainfo={'palette': ...}
)
```

另外可以确认一下，目前绘制 bboxes 的逻辑，有没有出现 BGR RGB 反色的情况，可以在 issue 里给出具体复现的示例，欢迎反馈。
