### ISSUE TITLE
i also want to ask that how to change the show score?In mmdet 2.x,it can change the param of tools/test.py,--show-score-thr,but i cannot find it in mmdet3.x

### ISSUE THREAD

**Issue by Mrzhans** [open-mmlab/mmdetection#10763]

**Comment by ryylcc** [comment]
mmdet3.x currently does not support --show-score-thr for `tools/test.py`, since it may cause confusion for the visualization of the evaluated mAP. If necessary, you can modify the threshold in `mmdet/visualization/local_visualizer.py` or use `demo/image_demo.py`.
