### ISSUE TITLE
Why use caffe's models sometimes or pytorch's models sometimes?

### ISSUE THREAD

**Issue by qq237942920** [open-mmlab/mmdetection#1076]
Why use caffe's models sometimes(especially in Anchor Free model) or pytorch's models sometimes? How should we select them correctly to get better result?

**Comment by hellock** [comment]
We adopt pytorch-style models by default and provide config files and checkpoints for popular methods. Meanwhile, there are some methods that use caffe-style methods in the original implementation, thus we provide caffe-style models for reference.

**Comment by qq237942920** [comment]
Thanks for your reply! Did you compare their performance? Because I've heard some arguments about caffe-style method which can get better result in some specific task.

**Comment by hellock** [comment]
You can refer to the model zoo.

**Comment by qq237942920** [comment]
Thx bro!
