### ISSUE TITLE
 I want to use the model I trained with mmdetection before as a pretrained model

### ISSUE THREAD

**Issue by xiaoLiu0531** [open-mmlab/mmdetection#10775]
Hello, I want to use the model I trained with mmdetection before as a pre-trained model, but after modifying the path of the config file 'pretrained', the model training shows 'unexpected key in source state_dict:' and the validation indicator of val after each epoch of training is empty, what should I do?

**Comment by hhaAndroid** [comment]
@xiaoLiu0531 This indicates that your weights and model keys are not matching, which means that the pre-trained weights are not being loaded.

**Comment by xiaoLiu0531** [comment]
I found I didn't change load_from in default_runtime.py,thanks a lot!
