### ISSUE TITLE
How to set the IoU threshold in test and inference mode? 

### ISSUE THREAD

**Issue by le02146** [open-mmlab/mmdetection#10778]
When I run test or inference(demo), how to modify the threshold of IoU for NMS? 
 (For example, yolov5 can define `iou-thres`, when run detect.py )

In `image_demo.py`, we can use `--pred-score-thr` to modify the value of bbox score threshold, but I could not find the setting of `iou-threshould` in mmdetection.
```python 
parser.add_argument(
        '--pred-score-thr',
        type=float,
        default=0.3,
        help='bbox score threshold')
```

Thank you.

**Comment by ryylcc** [comment]
You can set the Iou_threshold for nms in the test and inference mode in your `config.py`
~~~
  test_cfg=dict(
      rpn=dict(
          score_thr=0.0001,
          nms_pre=1000,
          max_per_img=256,
          nms=dict(type='nms', iou_threshold=0.9),
          min_bbox_size=0),
      rcnn=dict(
          score_thr=0.02,
          nms=dict(type='nms', iou_threshold=0.5),
          max_per_img=300)))
~~~
