### ISSUE TITLE
Image inference results into json, but generate strange code in "counts"

### ISSUE THREAD

**Issue by TaoshuaiZ** [open-mmlab/mmdetection#10771]
Dear all,
 I am using box-level segmentation inference on image ,The model was trained on coco format dataset.I followed the instructions of `python ./tools/test.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py ./work_dirs/epoch_2.pth --format-only --options "jsonfile_prefix=./results"` to generate test file in json.But the result json file generate strange code in "counts",how can I solve this problem? Thanks

**Comment by TaoshuaiZ** [comment]
![image](https://github.com/open-mmlab/mmdetection/assets/140058294/2eedf15e-cf58-4e3c-973d-7ec22f256841)

**Comment by hhaAndroid** [comment]
@TaoshuaiZ You can use cocoapi to decode the rle format
