### ISSUE TITLE
How to calculate the grad_norm in the output log file?

### ISSUE THREAD

**Issue by Hwang64** [open-mmlab/mmdetection#10786]
What is the meaning of the grad_norm in the output log file, and how to calculate it?

Thank you

**Comment by ryylcc** [comment]
This is implemented in [mmengine](https://github.com/open-mmlab/mmengine/blob/a483dba9d15308f9442e87faf80c1d7279137519/mmengine/optim/optimizer/optimizer_wrapper.py#L35), you can get more detail in the [readme](https://github.com/open-mmlab/mmengine/blob/a483dba9d15308f9442e87faf80c1d7279137519/docs/en/tutorials/optim_wrapper.md?plain=1#L140).
