### ISSUE TITLE
How to get the data instance name (e.g, 00008.pkl)

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection#10780]
Hi, is there any way that I get the data instance name while training or testing the model ?

**Comment by ryylcc** [comment]
Do you mean that you want to get the info of the input images? if so, the information is in the `batch_data_samples`.

**Comment by ammaryasirnaich** [comment]
In the datapipline [link](https://gitlab.kitware.com/keu-computervision/ml/mmdetection3d/-/blob/master/docs/tutorials/data_pipeline.md) i can't see any key to access the filename information.

**Comment by hhaAndroid** [comment]
@ammaryasirnaich `img_path`

**Comment by ammaryasirnaich** [comment]
> @ammaryasirnaich `img_path`

@hhaAndroid thanks i will give it a try !
