### ISSUE TITLE
How to train mmmagic with mmdetection

### ISSUE THREAD

**Issue by EranMer** [open-mmlab/mmdetection#10798]
There are two repos, mmdetection and mmmagic, how do I concatenate two models from different repos and train them?
Is there an example in another project?

**Comment by hhaAndroid** [comment]
@EranMer I haven't used it in that way before. Could you please provide a detailed description of your requirements?

**Comment by EranMer** [comment]
Thank you for your response. My research involves training a super resolution network and  object detection together. The goal is to concatenate the super resolution results before applying the object detection method.
Are you have any suggestion How to do it ?

**Comment by hhaAndroid** [comment]
@EranMer I'm sorry, but I haven't worked on a similar task before. One feasible solution is to base your work on a specific repository and temporarily migrate the modules required by other libraries. Otherwise, it may be challenging to develop and manage two separate repositories.
