### ISSUE TITLE
Implementation difference to Detectron in the mask head.

### ISSUE THREAD

**Issue by wangg12** [open-mmlab/mmdetection#108]
In Detectron, the predicted mask is padded before resize. While in this repo, no padding before resize (see [this line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/mask_heads/fcn_mask_head.py#L149) and [this line](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py#L119)), why?

**Comment by hellock** [comment]
This difference is caused by different mask preprocessings when computing the training target. We use binary masks and crop the region on the resized masks, while Detectron uses polygons and transforms it to target masks directly. Training target and inference pipeline need to be unified.

**Comment by wangg12** [comment]
@hellock Could you explain more specifically why there is a difference between the two different mask formats? Why is padding needed in polygons format and not needed in binary mask format?
