### ISSUE TITLE
error in deform_roi_pool

### ISSUE THREAD

**Issue by Factral** [open-mmlab/mmdetection#10802]
When passing an offset of 0 to deform_roi_pool, the outputs should be identical to not using any deformation. However, I am noticing the outputs are different.

![image](https://github.com/open-mmlab/mmdetection/assets/74687828/f13590a1-2f09-4859-9a17-9ce1fd45816b)

I would expect the outputs to be identical in this case, since an offset of 0 should produce no deformation. Could you please take a look into this potential bug? Let me know if any other details would be helpful in tracking this down.

**Comment by hhaAndroid** [comment]
@Factral Please go to the mmcv repository and create a relevant issue, as this operation is implemented in mmcv.

**Comment by Factral** [comment]
thank you, I already created it [#2903](https://github.com/open-mmlab/mmcv/issues/2903)
