### ISSUE TITLE
How to evaluate a model?

### ISSUE THREAD

**Issue by alekseisolovev** [open-mmlab/mmdetection#10801]
How do I evaluate a model in mmdet 2 with the same metric I used for training? The official documentation is either missing https://mmdetection.readthedocs.io/en/latest/advanced_guides/evaluation.html or not very clear https://mmdetection.readthedocs.io/en/latest/user_guides/useful_tools.html#offline-evaluation.

**Comment by hhaAndroid** [comment]
@alekseisolovev https://mmdetection.readthedocs.io/en/latest/user_guides/test.html
