### ISSUE TITLE
The problem of gen_gaussian_target 

### ISSUE THREAD

**Issue by RookieHuang** [open-mmlab/mmdetection#10800]
I have question in centernet_head.py as folow:
https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/mmdet/models/dense_heads/centernet_head.py#L253
https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/mmdet/models/dense_heads/corner_head.py#L455
Why gen_gaussian_target function return nothing in centernet_head.py but return values in corner_head,py.Anyone knows?

**Comment by hhaAndroid** [comment]
@RookieHuang It's just a matter of writing style, and both expressions have the same meaning. You can use whichever writing style you prefer.

**Comment by RookieHuang** [comment]
Thanks for your reply!
