### ISSUE TITLE
ONNX Support example 

### ISSUE THREAD

**Issue by SnowRipple** [open-mmlab/mmdetection#1080]
**Describe the feature**
A good example of how to convert an mmdet model to ONNX format.

ONNX supports multiple deep learning frameworks. Many issues raised here are caused by lack of guidance on how to correctly convert mmdet model to ONNX and what is possible with the current mmdet version.

Especially, proper handling of dictionary type input should be discussed in detail. 

Personally I prefer mmdetection over Detectron due to speed and accuracy advantage, however since Detectron models have clear examples of how to convert them to onnx, I am stuck with Detectron.

**Comment by ujsyehao** [comment]
@SnowRipple You are right, mmdetection supports onnx not well.

**Comment by SnowRipple** [comment]
@ujsyehao AFAIK there is no onnx support at all.

I believe that if mmdetection really wants to challenge Detectron and other detection framework, onnx support is a must.

**Comment by hellock** [comment]
@SnowRipple  Thanks for your advice. You may track the progress in #1082.
