### ISSUE TITLE
Add an option to launch a dry run 

### ISSUE THREAD

**Issue by stwerner97** [open-mmlab/mmdetection#10816]
**Describe the feature**

An option (e.g., ``python tools/train.py <config> --dry-run``) that logs the composed configuration to the console without starting the experiment would be a great way to validate the experiment's parameters before starting the trial.

**Comment by hhaAndroid** [comment]
@stwerner97 Does this script at https://github.com/open-mmlab/mmdetection/blob/main/tools/misc/print_config.py meet your requirements?

**Comment by stwerner97** [comment]
@hhaAndroid Yes, it does @hhaAndroid. Thanks, I've missed that! 😊
