### ISSUE TITLE
A bigger dataset with worse generalization result?

### ISSUE THREAD

**Issue by GSusan** [open-mmlab/mmdetection#10819]
At the begining, I trained a cascade mask rcnn with swin_tiny on dataset of about 1200 images, and I got a result of best epoch is as follows: bbox_mAP=0.842、bbox_mAP_50=0.989、bbox_mAP_75=0.957、bbox_mAR=0.878; Then I expand my dataset to 3300 images, and I got a result of best epoch is as follows: bbox_mAP=0.892、bbox_mAP_50=0.989、bbox_mAP_75=0.968、bbox_mAR=0.929. It looks like that the latter is better. But when I inference on a data from different area，I found the former is better than the latter.  I trained the dataset on a single GPU of GTX3060 with batch_size=1, and size of input images is 1024*1024. I have observed the loss and some other data, they are normal. I also tried training with "accumulative_counts" to accumulate grads, and the result is much better than above two, but the inference result of the data from different area, is still worse than the firsttime training.
So, what tricks is suitable for my situation, and how to training a big dataset on big model on a single GPU?
I'll be thankful for you all if you can help me.

**Comment by hhaAndroid** [comment]
@GSusan My understanding is that mAP (mean Average Precision) cannot truly reflect your actual needs. Instead of relying on human interpretation of inference results, you should consider using a more appropriate metric.

**Comment by GSusan** [comment]
您好！我已收到邮件，会尽快回复。

**Comment by GSusan** [comment]
> @GSusan My understanding is that mAP (mean Average Precision) cannot truly reflect your actual needs. Instead of relying on human interpretation of inference results, you should consider using a more appropriate metric.

Thanks for your reply. I'll try it.
