### ISSUE TITLE
Can't find show_result_pyplot in mmdet.apis

### ISSUE THREAD

**Issue by HenryPeking** [open-mmlab/mmdetection#10829]
Can;t find show_result_pyplot in mmdet.apis, is there any way I can use the api.

my mmdet version is v3.1.0

**Comment by hhaAndroid** [comment]
@HenryPeking It has been deleted. Please use demo/image_demo.py directly.

**Comment by HenryPeking** [comment]
Whether there is anyway I can visualize the results in the jupter notebook?

**Comment by HenryPeking** [comment]
@hhaAndroid

**Comment by hhaAndroid** [comment]
@HenryPeking Certainly, in the demo folder, there are some notebooks available for reference. You can take a look at those for guidance.

**Comment by ahmetnihat** [comment]
# Note : Show_result_pyplot was removed after mmdet version 2.0. OpenCV imshow is used instead.

## import mmdet.apis module
from mmdet.apis import init_detector, inference_detector
from mmdet.registry import VISUALIZERS
import cv2
import mmcv

## path to model file
config_file = 'rtmdet_tiny_8xb32-300e_coco.py'
## path to weight file
checkpoint_file = 'rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth'

## create model and load weights
model = init_detector(config_file, checkpoint_file, device='cpu')

## init visualizer
visualizer = VISUALIZERS.build(model.cfg.visualizer)

## the dataset_meta is loaded from the checkpoint and
## then pass to the model in init_detector
visualizer.dataset_meta = model.dataset_meta

## path to the image you want to test
img = 'demo/demo.jpg'
img = cv2.imread(img)

## apply the model to the image and get the output
result = inference_detector(model, img)

img = mmcv.imconvert(img, 'bgr', 'rgb')
visualizer.add_datasample(
    name='result',
    image=img,
    data_sample=result,
    draw_gt=False,
    pred_score_thr=0.3,
    show=False)

img = visualizer.get_image()
img = mmcv.imconvert(img, 'bgr', 'rgb')
cv2.imshow('result', img)

cv2.waitKey(0)

**Comment by liuwake** [comment]
The mmdet [2.28.2](https://github.com/open-mmlab/mmdetection/tree/v2.28.2) is the lastest version of __version2.x__. You could `mim install mmdet==2.28.2` if you like.
