### ISSUE TITLE
How to generate the same random number on different GPU process

### ISSUE THREAD

**Issue by VectorYoung** [open-mmlab/mmdetection#1083]
Hi, I am training with multi-gpu. I want to generate a random number in each iteration. But the DDP seems to lead to different random numbers on different GPUs. How can I make it the same on all the GPUs. I try to set the 'seed' to a fixed number, but it doesn't work.
Thanks for your help.

**Comment by jshilong** [comment]
You can find we set different seeds in `worker_init_fn`  for each worker when building the dataloader
https://github.com/open-mmlab/mmdetection/blob/0ad399cd097cbd731d25c3fad43086be115be7a4/mmdet/datasets/builder.py#L138

**Comment by jshilong** [comment]
We do not set the same seed for all workers in all ranks, because this would cause the same random number would be generated in the augmentation of different images. And this may hurt the performance.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any questions
