### ISSUE TITLE
Padding `size` not respected when the height is longer than width

### ISSUE THREAD

**Issue by Y-T-G** [open-mmlab/mmdetection#10838]
I am using `dict(type='Pad', size=(1333, 800))` in the data preprocessor.

It works and pads the image to 800x1333 when the width is longer than height in original image.

      META INFORMATION
      img_id: 0
      scale_factor: (1.58125, 1.5810276679841897)
      img_shape: (800, 1333)
      img_path: 'data/coco/images/000000563376.jpg'
      ori_shape: (506, 640)

But if the height is longer than width, it gets arbitrary height, but constraints width to 1333.

      META INFORMATION
      img_id: 0
      scale_factor: (1.680672268907563, 1.68125)
      img_shape: (1076, 1333)
      img_path: 'data/coco/images/000000231538.jpg'
      ori_shape: (640, 476)

How do I ensure it's 800x1333 in both cases?

**Comment by hhaAndroid** [comment]
@Y-T-G It seems unlikely based on the code.

```python
elif self.size is not None:
    size = self.size[::-1]
if isinstance(pad_val, int) and results['img'].ndim == 3:
    pad_val = tuple(pad_val for _ in range(results['img'].shape[2]))
padded_img = mmcv.impad(
    results['img'],
    shape=size,
    pad_val=pad_val,
    padding_mode=self.padding_mode)
```

**Comment by aaronzs** [comment]
@Y-T-G It looks like you have `Resize(scale=(1333, 800), keep_ratio=True)` before `Pad` in your data pipeline. When `keep_ratio=True` (1333, 800) is not a fixed size but more like a range to the output image size, see https://github.com/open-mmlab/mmcv/blob/ee93530acc675231014b92a58fd6e4a59e27cc13/mmcv/transforms/processing.py#L171

Your results look correct to me. I think what is confusing you is the `Resize` module.

1. (506, 640) -Resize-> (800, 1012) -Pad-> (800, 1333)
2. (640, 476) -Resize-> (1076, 800) -Pad-> (1076, 1333) (Pad does not crop the image)

BTW, to my knowledge, we do not use a fixed size of (800, 1333) as input to a detection model, but a flexible image size, e.g. FasterRCNN-R50 use `pad_size_divisor=32` https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/configs/_base_/models/faster-rcnn_r50_fpn.py#L9

**Comment by Y-T-G** [comment]
@aaronzs Yes, there's a resize of the same size. I thought the resize and pad combined should make sure that it comes out as a fixed size. I want to get a fixed size because I want to calculate similarity between features extracted by the backbone between the images. Without a fixed size, the output of the backbones differ in size.

How do I make sure that the output is a fixed size without losing aspect ratio? Or is there any other way to overcome the feature shape mismatch for similarity calculation?

**Comment by Y-T-G** [comment]
Is this function extracting features too?

https://github.com/open-mmlab/mmtracking/blob/e79491ec8f0b8c86fda947fbaaa824c66ab2a991/mmtrack/models/reid/base_reid.py#L29

**Comment by aaronzs** [comment]
@Y-T-G 

> How do I make sure that the output is a fixed size without losing aspect ratio? Or is there any other way to overcome the feature shape mismatch for similarity calculation?

You can resize the long side to a fixed size then pad it to a square image. For most ImageNet pretrained backbone, you can use the data pipeline like `Resize(scale=224, keep_ratio=True)` -> `Pad(size(224, 224))`

> Is this function extracting features too? https://github.com/open-mmlab/mmtracking/blob/e79491ec8f0b8c86fda947fbaaa824c66ab2a991/mmtrack/models/reid/base_reid.py#L29

Yes, you can use `model.extract_feat()` to get image (multi-scale) features. mmdetection and mmtracking projects are more force on the downstream tasks. If you just want to extract image features with a backbone network, you can use the mmpretrain project.

https://mmpretrain.readthedocs.io/en/latest/user_guides/inference.html#extract-features-from-image
https://mmpretrain.readthedocs.io/en/latest/api/generated/mmpretrain.apis.FeatureExtractor.html#mmpretrain.apis.FeatureExtractor

**Comment by Y-T-G** [comment]
Thanks

**Comment by Y-T-G** [comment]
@aaronzs How does MMDetection handle batch training and inference if the images are not resized to the same size?

**Comment by smoothumut** [comment]
@aaronzs thank you sooo much!!! 🙇  
why is the info you shared like long side  not anywhere in the documentation.
https://mmcv.readthedocs.io/zh-cn/2.x/api/generated/mmcv.transforms.Resize.html#mmcv.transforms.Resize
thanks a lot, finally I have understood
