### ISSUE TITLE
What is the difference between running in a terminal and running in an IDE?  in IDE，there is an error

### ISSUE THREAD

**Issue by yanlongbinluck** [open-mmlab/mmdetection#1084]
thanks for your great repo. I have a question:
when I run 

> python ./tools/train.py configs/pascal_voc/ssd300_voc.py

it work.
but when I directly run **train.py** in IDE,there is an error:
**File "/home/yanlongbin/code/mmdetection/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>**
**from .. import deform_conv_cuda**
**libcudart.so.10.0: cannot open shared object file: No such file or directory**.
I want to know what difference of these two way of operation？
thanks.

**Comment by hellock** [comment]
You terminal and IDE have different environments.

**Comment by yanlongbinluck** [comment]
> You terminal and IDE have different environments.
But with other repo, my IDE and terminal have same results.
I only have one CUDA, one python, and IDE uses same python interpreter. what means of "different"?
thanks your reply

**Comment by yanlongbinluck** [comment]
@hellock 
But with other repo, my IDE and terminal have same results.
I only have one CUDA, one python, and IDE uses same python interpreter. what means of "different"?
thanks for your reply

**Comment by yanlongbinluck** [comment]
I have solved it, thanks

**Comment by Kerrwy** [comment]
> I have solved it, thanks

how do you solve it? can you share with me?

**Comment by yanlongbinluck** [comment]
@Kerrwy 
`sudo ldconfig /usr/local/cuda-10.0/lib64`

**Comment by Kerrwy** [comment]
Is it your environment is cuda10? but my environmrnt is cuda9.0.

**Comment by yanlongbinluck** [comment]
yes，Change it to your own environment
