### ISSUE TITLE
convert to onnx error

### ISSUE THREAD

**Issue by ujsyehao** [open-mmlab/mmdetection#1086]
When I convert the trained model to onnx, it shows the error below:
![65](https://user-images.githubusercontent.com/17454232/62126613-b20cca80-b302-11e9-8eb5-3d706f32dcc6.jpg)

**Comment by ujsyehao** [comment]
Anyone can give me some advice?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/pull/1082#issuecomment-516722304
