### ISSUE TITLE
Can sampler be used in mmyolo?

### ISSUE THREAD

**Issue by hch-xmu** [open-mmlab/mmdetection#10887]
Can sampler be used in mmyolo? I try to use this in follow code, here set the sample in (type='GroupMultiSourceSampler')>,
`train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    sampler=dict(type='GroupMultiSourceSampler'),
    dataset=dict(
        _delete_=True,
        type='ConcatDataset',
        datasets=[
            dict(
            type=_base_.dataset_type,
            data_root=data_root,
            metainfo=metainfo,
            ann_file='/jfr_data/train_dataset/02_TrainDataMerge/annotations_coco/02_TrainDataMerge_coco.json',
            data_prefix=dict(img='/jfr_data/train_dataset/02_TrainDataMerge/JPEGImages/'),
            filter_cfg=dict(filter_empty_gt=False, min_size=32),
            pipeline=_base_.train_pipeline),
            dict(
                type=_base_.dataset_type,
                data_root=data_root,
                metainfo=metainfo,
                ann_file='/jfr_data/train_dataset/06_20200120_mark/annotations_coco/06_20200120_mark_coco.json',
                data_prefix=dict(img='/jfr_data/train_dataset/06_20200120_mark/JPEGImages/'),
                filter_cfg=dict(filter_empty_gt=False, min_size=32),
                pipeline=_base_.train_pipeline)
        ]))`
But I get the error : KeyError: 'GroupMultiSourceSampler is not in the mmyolo::data sampler registry. Please check whether the value of `GroupMultiSourceSampler` is correct or it was registered as expected. 
Is there any solution to sovle this problem? The tools of mmyolo is not ok for samplers?
Note: I find this question in mmyolo， is not mmdetection. This code can run success in mmdetection, but not in mmyolo.

**Comment by hch-xmu** [comment]
Anybody can solve my question, thanks a lot. It is urgent for me to solve this question.

**Comment by Jordan-Pierce** [comment]
Unsure if it applies here, but when I was trying to use a type from mmdet with yolo, I ran into the same error. The fix was to include `mmdet.` like so:

`mmdet.GroupMultiSourceSampler`
