### ISSUE TITLE
How to freeze the backbone?

### ISSUE THREAD

**Issue by Kegard** [open-mmlab/mmdetection#10881]
When  I use ResNet as backbone, I try to freeze all stages, and I did as document. But when I compared the checkpoint saved by epoch, the parameters of backbone has changed?  I want to know how can I freeze the backbone to make the parameters unchanged.

**Comment by hhaAndroid** [comment]
https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/backbones/resnet.py#L325

**Comment by Kegard** [comment]
Thank you for your reply. The code has worked

**Comment by maxiuw** [comment]
maybe not the most elegant solution but i just added this to my model class and seems to be working fine :)

```
def freeze(self):
        if self.freeze_img:
            if self.with_img_backbone:
                for param in self.img_backbone.parameters():
                    param.requires_grad = False
```
