### ISSUE TITLE
not a supported wheel on this platform.

### ISSUE THREAD

**Issue by emrekeles-arch** [open-mmlab/mmdetection#10894]
ERROR: mmdeploy-1.0.0rc3-py3-none-win_amd64.whl is not a supported wheel on this platform.
ERROR: mmdeploy_python-1.0.0rc3-cp39-none-win_amd64.whl is not a supported wheel on this platform.

i am taking theese error,could someone help?
how can i fix this?

**Comment by hhaAndroid** [comment]
@emrekeles-arch Please go to the mmdeploy repository and create an issue. Thank you.
