### ISSUE TITLE
How to use the script `coco_eval.py`?

### ISSUE THREAD

**Issue by liliangqi** [open-mmlab/mmdetection#1092]
Hi, I'm really confused about the usage of script `coco_eval.py`. There is a command line parameter named *result* with description "result file path". So I believe it should be a **str** in Python. But when calling the function `coco_eval` [here](https://github.com/open-mmlab/mmdetection/blob/master/tools/coco_eval.py#L24) with `types=['bbox']`, the parameter *result* should be a **dict** type as required [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/coco_utils.py#L26).

If the needed *result* should be a **dict**, then what are the keys and values?

**Comment by hellock** [comment]
You may refer to [`results2json`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/coco_utils.py#L157). The keys are result types and the values are filenames.

**Comment by jshuzi** [comment]
@liliangqi have you find the right way to use coco_eval.py, i run the command: python tools/coco.eval.py result.pkl --ann ./data/coco/annotations/instances_val2017.json, but occured the error
typeerror: string indices must bu integers.

**Comment by xiayongtao** [comment]
python tools/coco_eval.py  eval/faster_rcnn_101.pkl --ann data/coco/annotations/instances_val2017.json --types bbox

**Comment by hellock** [comment]
```
python tools/coco_eval.py ${RESULT_JSON_FILE} --ann ${ANNOTATION_FILE} --types bbox
```
