### ISSUE TITLE
请教，norm_cfg=dict(type='SyncBN', requires_grad=True) 中 requires_grad 的作用是什么？

### ISSUE THREAD

**Issue by AndrewJSong** [open-mmlab/mmdetection#10939]
在各种网络的配置文件中，norm_cfg 中的requires_grad的作用是什么？norm_eval的作用是什么呢？

backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        **norm_cfg=dict(type='SyncBN', requires_grad=True),**
        norm_eval=True,
        # init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet18'),
        style='pytorch',
        ),

**Comment by hhaAndroid** [comment]
requires_grad: BN 的 weight 和 bias 可学习
norm_eval: BN 的均值和方差是否随着 iter 而更新
