### ISSUE TITLE
 Number of gt bboxes is different from gt masks?

### ISSUE THREAD

**Issue by Epiphqny** [open-mmlab/mmdetection#1095]
Hello, when i use your data loader api to load coco dataset to train my model, i found sometimes the number of gt_bboxes and gt_masks for the same image does not match, sometimes the gt_masks have 1 or 2 gt_nums than the gt_bboxes, i want to know if the problem is common for coco dataset, or it is an error of the code?

**Comment by hellock** [comment]
Could you provide the image id? The number of `gt_bboxes` and `gt_masks` should be the same.
