### ISSUE TITLE
How to export ssd-mobilenet-v2 pytorch model to onnx format

### ISSUE THREAD

**Issue by michaelnguyen11** [open-mmlab/mmdetection#1096]
Hi Supporter,

I've trained a face detection model which followed this instruction :https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_detection/face_detection.md

I dumped to pkl format and export to onnx format by using pytorch:
```
# dummy_input = "epoch_58.pth"
dummy_input = "result.pkl" 
# Obtain your model, it can be also constructed in your script explicitly
model = torchvision.models.mobilenet_v2(pretrained=True)
# Invoke export
torch.onnx.export(model, dummy_input, "test.onnx")

```
But got the error : RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got str

Could you help me to export the pytorch to onnx or tensorflow or caffe format ?

On the other hand, I tried the script of pull request #1082, but got errors :
`NotImplementedError: ONNX exporting is currently not currently supported with SingleStageDetector
`

Thank you in advance !

Regards,
Michael

**Comment by hellock** [comment]
Did you follow the [comment](https://github.com/open-mmlab/mmdetection/pull/1082#issuecomment-516722304) in #1082?

**Comment by michaelnguyen11** [comment]
work like a charm. Thank you very much @hellock
