### ISSUE TITLE
TypeError: FormatCode() got an unexpected keyword argument 'verify'

### ISSUE THREAD

**Issue by Adarsh0047** [open-mmlab/mmdetection#10962]
I get `TypeError: FormatCode() got an unexpected keyword argument 'verify'` when I try to download the config files for any model.
This error occurs since the latest release of `yapf v0.40.2`, which was released on September 22, 2023.
I am currently able to bypass this error by running `pip install yapf==0.40.1`.
Please fix this bug.

**Comment by Adarsh0047** [comment]
To add on to the issue, the issue pops up in the following script:
`File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 1475, in pretty_text
    text, _ = FormatCode(`

**Comment by muziyuhui666** [comment]
I meet the same question

**Comment by mayman99** [comment]
I get the same issue on one pc and I don't get it on the other PC, but I'm sure I'm running the same exact versions, which is very confusing

**Comment by TonojiKiobya** [comment]
Thank you so much, I struggled with this issue the whole day, a lot of my colab units were eaten because of this problem .Got a solution from here

**Comment by iriroki** [comment]
thanks a loooooot!!! I spent the whole weekend reinstalling the whole mmdet and met this error again and again

**Comment by Kerio99** [comment]
Thanks, it works!!!

**Comment by stone-cloud** [comment]
I have the same issue, this way is good, and please fix this bug.

> I get `TypeError: FormatCode() got an unexpected keyword argument 'verify'` when I try to download the config files for any model. This error occurs since the latest release of `yapf v0.40.2`, which was released on September 22, 2023. I am currently able to bypass this error by running `pip install yapf==0.40.1`. Please fix this bug.

**Comment by Nuaza** [comment]
Thanks! Finally figured out what went wrong!

**Comment by rbli-john** [comment]
I met the same issue. Please fix this bug. thanks.

**Comment by IsraaSamkari** [comment]
I was going to cry, but with you there will be no tears after today.
Thank you very much!!

**Comment by weichenrs** [comment]
Thanks!

**Comment by nidham-sony** [comment]
> Same issue, and `pip install yapf==0.40.1` bybass it, thanks OP

This solve the issue for me too

**Comment by Evolive2** [comment]
Thanks!

**Comment by Alan-D-Chen** [comment]
> Same issue, and `pip install yapf==0.40.1` bybass it, thanks OP

Much thank to you!!

**Comment by zyytyyp** [comment]
> `TypeError: FormatCode() got an unexpected keyword argument 'verify'`当我尝试下载任何型号的配置文件时，我都会遇到这种情况。此错误自2023 年 9 月 22 日发布的 最新版本以来发生。 我目前可以通过运行 绕过此错误。 请修复这个错误。`yapf v0.40.2``pip install yapf==0.40.1`

办法很好

**Comment by qianlian-mozi** [comment]
amazing! thanks a lot! I face it and now bypass the problem

**Comment by coldpark** [comment]
thanks a lot!

**Comment by roinheart** [comment]
装了0.40.1以后又不能解析np.asarray了，提示yapf.yapflib.errors.YapfError: <unknown>:85:26: invalid syntax

**Comment by Arslan-Mehmood1** [comment]
> I get `TypeError: FormatCode() got an unexpected keyword argument 'verify'` when I try to download the config files for any model. This error occurs since the latest release of `yapf v0.40.2`, which was released on September 22, 2023. I am currently able to bypass this error by running `pip install yapf==0.40.1`. Please fix this bug.

Thanks @Adarsh0047 , it worked. :)

**Comment by Shao1Fan** [comment]
new bee

**Comment by afly36-swordsman** [comment]
> Same issue, and `pip install yapf==0.40.1` bybass it, thanks OP

Thanks a millon!!

**Comment by TonyIsNotSilly** [comment]
Thanks, bro!
