### ISSUE TITLE
Python 3.10 Dependencies 

### ISSUE THREAD

**Issue by adilchhabra** [open-mmlab/mmdetection#10973]
I am currently trying to install yolox on an AWS lambda docker container running python 3.10. However, I am unsure about how to work out the dependencies for it. In particular, what version of onnx and onnxruntime do I require? It seems that 'pip install yolox' calls for onnxruntime==1.8.0 which is not installing on Python 3.10. Any tips would be really appreciated!

**Comment by hhaAndroid** [comment]
@adilchhabra Please go to mmdeloy and create a issue.
