### ISSUE TITLE
run setup.py error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by hust-kevin** [open-mmlab/mmdetection#1097]
when I run `sudo python3 setup.py develop`  in a `new machine`, meet the error 
`mmdet/ops/nms/src/nms_cpu.cpp:63:46: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
   AT_DISPATCH_FLOATING_TYPES(dets.scalar_type(), "nms", [&] {
                                              ^
/home/huzb/.local/lib/python3.5/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
     const at::Type& the_type = TYPE;                                         \
                                ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

I have try the the method in [here](https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit), but they didn't help

- Ubuntu:16.04
- python: 3.5
- pytorch:1.0.0
- cuda:10.0

**Comment by hfteng** [comment]
my solution:
upgrade pytorch1.0.0 to pytorch1.1.0

**Comment by hust-kevin** [comment]
thanks, I solved it

**Comment by lfydegithub** [comment]
> thanks, I solved it

how？

**Comment by TangDL** [comment]
> > thanks, I solved it
> 
> how？

just do as him said

**Comment by AhmedNageh08** [comment]
what about version 1.7.0 and the same error ?

**Comment by surbhi1986** [comment]
HI i am using 1.7.0+cu101, and facing the same issue.
