### ISSUE TITLE
ERROR: Could not build wheels for mmpycocotools, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Brym-Gyimah** [open-mmlab/mmdetection#10985]
I need help with this error. Can anybody help??
Thank you

**Comment by rishabhsharma22** [comment]
I am having the same issue. Were you able to solve it ?

**Comment by hhaAndroid** [comment]
@Brym-Gyimah @rishabhsharma22 This has been deprecated. Please use pycocotools. Additionally, I recommend using the latest version of mmdet.

**Comment by JoshC8C7** [comment]
Still has prominence on google, so see [here.](https://github.com/open-mmlab/mmdetection/issues/10730)
