### ISSUE TITLE
"data_list" Not Being Populated When Training a Model

### ISSUE THREAD

**Issue by cmyoung225** [open-mmlab/mmdetection#10991]
**Describe the bug**

Whenever the command to train a model using a config file is ran, an empty array error is displayed. Investigation into the issue revealed that the "load_data_list" function is never being called, and therefore "data_list" is not being populated. Why data_list is being utilized before being loaded is unknown.

**Reproduction**

1. What command or script did you run?

```none
(openmmlab) C:\Users\cmyou\Desktop\MMDetection> python tools/train.py configs/_base_/NewDST/mask-rcnn_r50_fpn.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
A new config file was added to train the model using a custom dataset. The config file was written according to this guide: https://mmdetection.readthedocs.io/en/latest/user_guides/train.html#train-a-new-model
3. What dataset did you use?
A custom coco data set was used.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```sys.platform: win32
Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
CUDA available: False
numpy_random_seed: 2147483648
GCC: n/a
PyTorch: 2.0.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
OpenCV: 4.8.0
MMEngine: 0.8.4
MMDetection: 3.1.0+f78af77
```
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
 PyTorch was installed using conda. All relevant files are located on the desktop folder.

**Error traceback**
If applicable, paste the error trackback here.

```none
 File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by Dswn888** [comment]
Hi, I have the same value error. Is there any solution?

**Comment by cmyoung225** [comment]
In VIA 2.0.12 you enter a name and description for each annotation class. The description text is what becomes the "Name" variable in the COCO format. Whatever you have as the description should match `'classes': ('NAME_HERE', ),` in the config file.

**Comment by 20231211** [comment]
> > 在 VIA 2.0.12 中，您可以为每个注释类输入名称和描述。描述文本是 COCO 格式的“Name”变量。无论您拥有什么描述，都应该与配置文件中的描述相匹配。`'classes': ('NAME_HERE', ),`
> 
> 我的问题已经解决。多谢！

你好，请问你是如何解决的，我更改了coco.py中的classes，但data_list依旧为空

**Comment by cmyoung225** [comment]
The error indicates that something is wrong with the dataset provided. I would check your coco files and images to make sure the data matches what is in your config file. Sorry I can't provide more useful advice.

**Comment by cmyoung225** [comment]
> > > 在 VIA 2.0.12 中，您可以为每个注释类输入名称和描述。描述文本是 COCO 格式的“Name”变量。无论您拥有什么描述，都应该与配置文件中的描述相匹配。`'classes': ('NAME_HERE', ),`
> > 
> > 
> > 我的问题已经解决。多谢！
> 
> 你好，请问你是如何解决的，我更改了coco.py中的classes，但data_list依旧为空

The error indicates that something is wrong with the dataset provided. I would check your coco files and images to make sure the data matches what is in your config file. Sorry I can't provide more useful advice.

**Comment by 20231211** [comment]
谢谢！之后我发现我的pycharm或者anaconda的安装有些问题，我将其全部删除重装之后，没有再出现这个问题
