### ISSUE TITLE
./Compile.sh compile ERROR

### ISSUE THREAD

**Issue by opencvfun** [open-mmlab/mmdetection#110]
Errors show up when I execute the command './Compile.sh '.
Env: ubuntu16.04.3   anaconda  cuda8.0  pytorch 0.4.1   python3.6
Error log is as below:

Building roi align op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
  File "/home/yan/anaconda3/envs/mmdetection_py36/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: /home/yan/anaconda3/envs/mmdetection_py36/lib/python3.6/site-packages/torch/lib/libshm.so: undefined symbol: _ZTI24THRefcountedMapAllocator
Building roi pool op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
  File "/home/yan/anaconda3/envs/mmdetection_py36/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: /home/yan/anaconda3/envs/mmdetection_py36/lib/python3.6/site-packages/torch/lib/libshm.so: undefined symbol: _ZTI24THRefcountedMapAllocator
Building nms op...
rm -f *.so
echo "Compiling nms kernels..."
Compiling nms kernels...
……
……

**Comment by miaomi1994** [comment]
I came across the same error,did you solve the problem? Thanks @opencvfun

**Comment by ChenConnie** [comment]
I meet the same problem,have you solved it?

**Comment by hellock** [comment]
The compiling process has been updated.
