### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 488, 5844) exited unexpectedly

### ISSUE THREAD

**Issue by nirajkark07** [open-mmlab/mmdetection#11003]
**Describe the bug**
Dataloader crashes when I specify num_workers > 0. I'm trying to train RTMdet-ins-x on a custom dataset. I've tried to proceed with num_workers = 0, but the model doesn't train.

**Reproduction**

1.     What command or script did you run?

Below is the configuration file that I prepared:

`_base_ = ['rtmdet-ins_x_8xb16-300e_coco.py',]
dataset_type = 'CocoDataset'
data_root = 'data/'
metainfo = {
        'classes':
        ('Small Gear', 'Big Gear'),
        # palette is a list of color tuples, which is used for visualization.

        'palette':
        [(225, 0, 0), (0, 225, 0)]
    }

model = dict(
    backbone=dict(deepen_factor=1.33, widen_factor=1.25),
    neck=dict(
        in_channels=[320, 640, 1280], out_channels=320, num_csp_blocks=4),
    bbox_head=dict(in_channels=320, 
                   feat_channels=320,
                   num_classes=2))

base_lr = 0.002

# optimizer
optim_wrapper = dict(optimizer=dict(lr=base_lr))
        
train_dataloader = dict(
    batch_size=4,
    num_workers=2,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file='Annotations/train.json',
        data_prefix=dict(img='Train/')))

val_dataloader = dict(
    batch_size=4,
    num_workers=2,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file='Annotations/val.json',
        data_prefix=dict(img='Val/')))
backend_args = None    

# Modify metric related settings
val_evaluator = dict(ann_file=data_root + 'Annotations/val.json')

# load_from = './pretrained/rtmdet_l_8xb32-300e_coco.pth'
load_from = './checkpoints/rtmdet-ins_x_8xb16-300e_coco_20221124_111313-33d4595b.pth'`

2. What dataset did you use?

Created a custom data set in COCO format.

**Environment**

    Please run python mmdet/utils/collect_env.py to collect necessary environment information and paste it here.

Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.140
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
GCC: n/a
PyTorch: 2.0.1+cu118
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.15.2+cu118
OpenCV: 4.8.1
MMEngine: 0.8.5
MMDetection: 3.1.0+077b491

    You may add addition that may be helpful for locating the problem, such as
        How you installed PyTorch [e.g., pip, conda, source]
        Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

I installed everything like pytorch, torchvision, mmcv, cudatoolkit, etc.

**Error traceback**

Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "C:\Users\niraj\anaconda3\envs\openmmlab2\lib\site-packages\mmengine\runner\runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "C:\Users\niraj\anaconda3\envs\openmmlab2\lib\site-packages\mmengine\runner\loops.py", line 96, in run
    self.run_epoch()
  File "C:\Users\niraj\anaconda3\envs\openmmlab2\lib\site-packages\mmengine\runner\loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "C:\Users\niraj\anaconda3\envs\openmmlab2\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "C:\Users\niraj\anaconda3\envs\openmmlab2\lib\site-packages\torch\utils\data\dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "C:\Users\niraj\anaconda3\envs\openmmlab2\lib\site-packages\torch\utils\data\dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\niraj\anaconda3\envs\openmmlab2\lib\site-packages\torch\utils\data\dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 488, 5844) exited unexpectedly

**Comment by Ray2254** [comment]
I had a similar problem when I tried to change num_works to 0 but again the error was ValueError: persistent_workers option needs num_workers > 0
