### ISSUE TITLE
Please provide the specific format of coco2017 fine-tuned on GroundingDINO.

### ISSUE THREAD

**Issue by FengheTan9** [open-mmlab/mmdetection#11002]
Could you teach me how to specifically organize the data (text and image) for fine-tuning in GroundingDINO, thanks!

**Comment by hhaAndroid** [comment]
@FengheTan9 Just the standard COCO format is sufficient. It follows the same format as traditional detection training.

**Comment by FengheTan9** [comment]
Thanks for your answer. I still have a question, if using the coco dataset for fine-tuning in GroundDINO, what are the script commands?

**Comment by FengheTan9** [comment]
> @FengheTan9 Just the standard COCO format is sufficient. It follows the same format as traditional detection training.

Thanks for your answer. I still have a question, if using the coco dataset for fine-tuning, what are the script commands?

**Comment by FengheTan9** [comment]
> @FengheTan9 Just the standard COCO format is sufficient. It follows the same format as traditional detection training.

coco instances didn't have test item.

**Comment by hhaAndroid** [comment]
@FengheTan9 Sorry. I didn't understand what you meant.

**Comment by hhaAndroid** [comment]
@FengheTan9 https://github.com/open-mmlab/mmdetection/pull/11012
