### ISSUE TITLE
In the "test_pipeline", why "LoadAnnotations"after"Resize"?

### ISSUE THREAD

**Issue by LYKlyk** [open-mmlab/mmdetection#11001]
test_pipeline = [
dict(type='LoadImageFromFile'),
dict(type='Resize', scale=(2048, 1024), keep_ratio=True),
# add loading annotation after Resize because ground truth
# does not need to resize data transform
dict(type='LoadAnnotations'),
dict(type='PackSegInputs')
]

if you put 'LoadAnnotations' after 'Resize', how do you ensure that the GT label is consistent with the predicted label?
（https://github.com/open-mmlab/mmdetection/blob/main/configs/_base_/datasets/coco_detection.py）

**Comment by hhaAndroid** [comment]
@LYKlyk The main purpose is to facilitate visualization, model cascading, and other post-processing tasks.

**Comment by LYKlyk** [comment]
感谢您的回复。但是，我所困惑的是：将“LoadAnnotations”放置在“Resize”后面，不就无法保证GT的标签box尺寸与模型预测输出的标签box尺寸不一致，那么此处计算的评价指标值不就没有任何意义了吗？

**Comment by LYKlyk** [comment]
@hhaAndroid 感谢您的回复。但是，我所困惑的是：将“LoadAnnotations”放置在“Resize”后面，不就无法保证GT的标签box尺寸与模型预测输出的标签box尺寸不一致，那么此处计算的评价指标值不就没有任何意义了吗？

**Comment by LYKlyk** [comment]
@hhaAndroid 按照我的理解：在“test_pipeline“不是应该像“train_pipeline”一样，将“LoadAnnotations”放置在“Resize”之前吗？这样才能保证“输入图像”与“对应真实标签”做同样的增强，这样才能确保计算mAP等相关评价指标时，做到模型输出结果与真实标签一一对应？谢谢！

**Comment by BIGWangYuDong** [comment]
推理得到的图片bbox会 resize 回原图大小
