### ISSUE TITLE
Modify the loss function

### ISSUE THREAD

**Issue by ElegantLin** [open-mmlab/mmdetection#1101]
Hi, I want to add some loss function which is not included in mmdetection. Could you please tell me how to do it? For now, I only know that I should add a `function` in loss folder. How about the `config` file.

Thanks.

**Comment by hellock** [comment]
You can follow any examples in `model/losses/`. The [documentation](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#develop-new-components) may also help.

**Comment by ElegantLin** [comment]
OK. Thanks for your help.
