### ISSUE TITLE
mmdetection升到版本3后 一些import位置改到哪里了 有文档说明吗

### ISSUE THREAD

**Issue by sharp-xiang** [open-mmlab/mmdetection#11013]
2.0版本的时候是这个from mmdet.core import distance2bbox, multi_apply, bbox_overlaps, reduce_mean, filter_scores_and_topk, select_single_mlvl, bbox2distance

3.0版本这些在哪里呢

**Comment by hhaAndroid** [comment]
@sharp-xiang We don't have such a detailed API migration document available here. However, you can directly search our API documentation to find the information you need.

**Comment by sharp-xiang** [comment]
> @sharp-xiang We don't have such a detailed API migration document available here. However, you can directly search our API documentation to find the information you need.

thanks

**Comment by taiwuyouxu** [comment]
> > @sharp-xiang We don't have such a detailed API migration document available here. However, you can directly search our API documentation to find the information you need.
> 
> thanks

May I ask if you have solved this problem? I am also facing the same problem. Thank you
