### ISSUE TITLE
Are you planning to support focus-detr in mmdetection 3.x and when?

### ISSUE THREAD

**Issue by Artificial-Inability** [open-mmlab/mmdetection#11018]
https://github.com/IDEA-Research/detrex/tree/main/projects/focus_detr has the implementation of focus-detr in detrex(based on detectron2). Are you planning to support it in mmdet3.x and when?

**Comment by hhaAndroid** [comment]
@Artificial-Inability Hello, we don't have plans to support it at the moment, but we welcome the community to submit pull requests (PRs).
