### ISSUE TITLE
A ERRO FOR DEMO

### ISSUE THREAD

**Issue by wtshow** [open-mmlab/mmdetection#1102]
when I run the demo which the author gives in offical websit e.g:

`from mmdet.apis import init_detector, inference_detector, show_result
import mmcv
config_file = 'configs/faster_rcnn_r50_fpn_1x.py'
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = 'timg.jpg'  
result = inference_detector(model, img)
show_result(img, result, model.CLASSES, dataset.img_norm_cfg, dataset='coco')
`
the program show an UserWarning:
`(base) root@07c09e5cf03c:/home/WT/mmdetection# python test_1.py
/home/WT/mmdetection/mmdet/apis/inference.py:39: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
: cannot connect to X server
`
I can not deal it

**Comment by hellock** [comment]
You ran the demo code on a server where the GUI is not available.
Instead you can save the image by adding the argument `out_file='xxx.jpg'`.

**Comment by wtshow** [comment]
> You ran the demo code on a server where the GUI is not available.
> Instead you can save the image by adding the argument `out_file='xxx.jpg'`.

I solved this proble in your way! thank you very much!

**Comment by Ruofei520** [comment]
> You ran the demo code on a server where the GUI is not available.
> Instead you can save the image by adding the argument `out_file='xxx.jpg'`.

I tried this method but it still doesn't work.
`from mmdet.apis import init_detector, inference_detector, show_result
import mmcv

config_file = 'configs/faster_rcnn_r50_fpn_1x.py'
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'

# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

# test a single image and show the results
img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_detector(model, img)
# visualize the results in a new window
#show_result(img, result, model.CLASSES)
# or save the visualization results to image files
show_result(img, result, model.CLASSES, out_file='result.jpg')`

UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes                                                          by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
: cannot connect to X server

**Comment by hzhang57** [comment]
show_result(img, result, model.CLASSES, show=False, out_file='result.jpg')
加上show=False
out_file='result.jpg' 你保存的地方

**Comment by squirrel16** [comment]
> show_result

请问这行代码在哪个文件里？

**Comment by squirrel16** [comment]
@hzhang57 

> show_result(img, result, model.CLASSES, show=False, out_file='result.jpg')
> 加上show=False
> out_file='result.jpg' 你保存的地方

请问这行代码在哪个文件里？
