### ISSUE TITLE
where is compile.sh??

### ISSUE THREAD

**Issue by sunyaqing125125** [open-mmlab/mmdetection#1103]
lab@lab-T640:~/anaconda3$ git clone https://github.com/open-mmlab/mmdetection.git
正克隆到 'mmdetection'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 4609 (delta 0), reused 0 (delta 0), pack-reused 4599
接收对象中: 100% (4609/4609), 2.56 MiB | 606.00 KiB/s, 完成.
处理 delta 中: 100% (3028/3028), 完成.
检查连接... 完成。
lab@lab-T640:~/anaconda3$ 
lab@lab-T640:~/anaconda3$ cd mmdetection
lab@lab-T640:~/anaconda3/mmdetection$ 
lab@lab-T640:~/anaconda3/mmdetection$ ./compile.sh
-bash: ./compile.sh: 没有那个文件或目录
lab@lab-T640:~/anaconda3/mmdetection$ 

where is compile.sh?thank you

**Comment by hellock** [comment]
There is no `compile.sh` in the latest version. You may refer to the [installation guide](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md).
