### ISSUE TITLE
Details about Guided Anchoring

### ISSUE THREAD

**Issue by yukang2017** [open-mmlab/mmdetection#1104]
I notice a detail in Section 4.1 in the Paper: 'In the multi-task loss function, we simply use λ1 = 1, λ2 = 0.1 to balance the location and shape prediction branches.'

However, all config files in 'configs/guided_anchoring/' show that loss_weight of both loss_shape and loss_loc are *1.0*.

Could you give me some hints?

**Comment by hellock** [comment]
In the original implementation, there are some minor differences with the hard coded numbers, thus the value of loc loss is 10 times larger than current implementation. In the released version, the loss weight is simply set to 1.0, which is equivalent to the original implementation with loss weight 0.1.
BTW, this loss weight actually has very limited affects to the performance.

**Comment by yukang2017** [comment]
Thanks for your explanation.
