### ISSUE TITLE
Any plans for CenterNet : Keypoint Triplets for Object Detection

### ISSUE THREAD

**Issue by Epiphqny** [open-mmlab/mmdetection#1105]
A one-stage model with AP of 47%, state of the art of object detection.

**Comment by hellock** [comment]
We planned to work with the authors but it seems that both the authors and we do not have enough time to finish that in the near future.

**Comment by Epiphqny** [comment]
> We planned to work with the authors but it seems that both the authors and we do not have enough time to finish that in the near future.

Ok, thanks for your reply!
