### ISSUE TITLE
Grounding-DINO的识别类别

### ISSUE THREAD

**Issue by lybllybl** [open-mmlab/mmdetection#11065]
您好，请问在如果需要识别出COCO数据集中全部的80个类别，是直接将80个类别名作为prompt输入进去吗？有推荐的命令吗？

**Comment by hhaAndroid** [comment]
我们跑的评估结果就是 80 个类一起输入的。你可以直接跑一下我们的评估，然后应该能看到类别名是在输入的

**Comment by lybllybl** [comment]
> 我们跑的评估结果就是 80 个类一起输入的。你可以直接跑一下我们的评估，然后应该能看到类别名是在输入的

麻烦可以提供评估的命令吗，readme里没有评估指令。

**Comment by lybllybl** [comment]
> 我们跑的评估结果就是 80 个类一起输入的。你可以直接跑一下我们的评估，然后应该能看到类别名是在输入的

使用image_demo.py文件，将80个类别全输入后，结果出错了，具体如下：
![1_person_1_sports_ball](https://github.com/open-mmlab/mmdetection/assets/48339877/87b6b335-f249-4e2f-96ed-f8da780ff683)
![1_person_1_tie](https://github.com/open-mmlab/mmdetection/assets/48339877/aafd02ec-c019-43dd-8799-4beca2b916f2)

**Comment by Johnson-Wang** [comment]
在跑img_demo.py时后面要加一个-c表示cusom_entities

**Comment by lybllybl** [comment]
> 在跑img_demo.py时后面要加一个-c表示cusom_entities

问题解决了，谢谢
