### ISSUE TITLE
COCO datasets training bug

### ISSUE THREAD

**Issue by xiaohangguo** [open-mmlab/mmdetection#11072]
发现一个bug，出现在COCO数据集上。比如我的数据集一共有两个类别，
json文件里面，应该是有三个，一个是background 一个是class1 一个是class2。
此时如果class1 和class2 的name不同，但category的值是一样的，比如都是class1。然后在训练的时候num_class填2训练是不会报错的。
我怀疑训练的时候扫描的是name的长度
但是推理的时候就会报错。因为训练出来的模型实际只有一个class。
当我发现错误以后，把josn改了，使得这两个类别都有不一样的category的值了。然后就能推理了。
但是实验不就等于白做了。这个是跟mmdetection底层有关吗。有没有某种方法考虑能解决这种问题，在训练时是不是就应该报错或者提示。

**Comment by hhaAndroid** [comment]
首先 json 文件夹中不应该存在 background，然后你说的 class1 和class2 的name不同，但category的值是一样的，这种情况实际上也是不允许的。麻烦你参考 COCO 标准 json 格式来生成数据。我们只是根据官方 COCO json 标准来解析的，对于不是这种情况，需要用户自己重写 dataset 来兼容

**Comment by xiaohangguo** [comment]
> 首先 json 文件夹中不应该存在 background，然后你说的 class1 和class2 的name不同，但category的值是一样的，这种情况实际上也是不允许的。麻烦你参考 COCO 标准 json 格式来生成数据。我们只是根据官方 COCO json 标准来解析的，对于不是这种情况，需要用户自己重写 dataset 来兼容

好的，明白了。
1.标签的第一个不应该是background的吗？category为 none
2. 嗯嗯，改dataset相比直接改标签开销太大。我debug发现然后我改了。已经解决了。谢谢。
