### ISSUE TITLE
Why is the learning rate displayed in the log different from that in the config

### ISSUE THREAD

**Issue by Jeremy-lf** [open-mmlab/mmdetection#11076]
![image](https://github.com/open-mmlab/mmdetection/assets/45171399/86896d52-42ba-4aff-8fd6-ea6bd5fe0cfe)
![image](https://github.com/open-mmlab/mmdetection/assets/45171399/a3992f45-2de3-4971-a842-82dd0dad457e)

log：1e-5
config：1e-4
and there is no warm-up

**Comment by hhaAndroid** [comment]
@Jeremy-lf I suspect that the displayed learning rate refers to the learning rate of the backbone. In the configuration, it is multiplied by 0.1.

**Comment by Jeremy-lf** [comment]
> @Jeremy-lf I suspect that the displayed learning rate refers to the learning rate of the backbone. In the configuration, it is multiplied by 0.1.

thanks, i make some experiments like change backbone's learning rate, it's changed in the log
