### ISSUE TITLE
Trying to fine tune grounding dino, but the following errors  were found

### ISSUE THREAD

**Issue by Bobby-youngking** [open-mmlab/mmdetection#11080]
1. i created a new python script to fine tune grounding_dino_swin-b_pretrain_mixeddata.py by following the cat example, but it always said "AttributeError: 'DetDataSample' object has no attribute 'text', i checked my piple, text is included

**Comment by Bobby-youngking** [comment]
_base_ = [
    'grounding_dino_swin-b_pretrain_mixeddata.py',
]
 this is my new script

**Comment by Bobby-youngking** [comment]
then i modify my code as follows:
_base_ = [
    'grounding_dino_swin-b_pretrain_mixeddata.py',
]
load_from = '/mnt/date1/wb_workspace/mmdetection-main/groundingdino_swinb_cogcoor_mmdet-55949c9c.pth'
train_pipeline = [
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'flip', 'flip_direction', 'text',
                   'custom_entities'))]
test_pipeline = [
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'text', 'custom_entities'))]
train_dataloader = dict(
    dataset=dict(
        filter_cfg=dict(filter_empty_gt=False),
        pipeline=train_pipeline,
        return_classes=True))
val_dataloader = dict(
    dataset=dict(pipeline=test_pipeline, return_classes=True))
test_dataloader = val_dataloader
max_epoch=1
train_cfg = dict(max_epochs=max_epoch, val_interval=1)

param_scheduler = [
    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end=30),
    dict(
        type='MultiStepLR',
        begin=0,
        end=max_epoch,
        by_epoch=True,
        milestones=[15],
        gamma=0.1)
]

optim_wrapper = dict(
    optimizer=dict(lr=0.00005),
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'backbone': dict(lr_mult=0.1),
            'language_model': dict(lr_mult=0),
        }))

auto_scale_lr = dict(base_batch_size=16)
but get " _batch_inputs = data['inputs']  
" KeyError: 'inputs'
i don't know why

**Comment by SoulProficiency** [comment]
> then i modify my code as follows: _base_ = [ 'grounding_dino_swin-b_pretrain_mixeddata.py', ] load_from = '/mnt/date1/wb_workspace/mmdetection-main/groundingdino_swinb_cogcoor_mmdet-55949c9c.pth' train_pipeline = [ dict( type='PackDetInputs', meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor', 'flip', 'flip_direction', 'text', 'custom_entities'))] test_pipeline = [ dict( type='PackDetInputs', meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor', 'text', 'custom_entities'))] train_dataloader = dict( dataset=dict( filter_cfg=dict(filter_empty_gt=False), pipeline=train_pipeline, return_classes=True)) val_dataloader = dict( dataset=dict(pipeline=test_pipeline, return_classes=True)) test_dataloader = val_dataloader max_epoch=1 train_cfg = dict(max_epochs=max_epoch, val_interval=1)
> 
> param_scheduler = [ dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end=30), dict( type='MultiStepLR', begin=0, end=max_epoch, by_epoch=True, milestones=[15], gamma=0.1) ]
> 
> optim_wrapper = dict( optimizer=dict(lr=0.00005), paramwise_cfg=dict( custom_keys={ 'absolute_pos_embed': dict(decay_mult=0.), 'backbone': dict(lr_mult=0.1), 'language_model': dict(lr_mult=0), }))
> 
> auto_scale_lr = dict(base_batch_size=16) but get " _batch_inputs = data['inputs'] " KeyError: 'inputs' i don't know why

have you solved this issue?

**Comment by SoulProficiency** [comment]
> It means that the dictionary `data` doesn't have a key called `inputs`

if we want to fine-tune groundDINO on coco object detection dataset and use the official config.py file,it still has "AttributeError: 'DetDataSample' object has no attribute 'text' error. should we modify the coco dataset format like cat dataset provided by official?
