### ISSUE TITLE
can it train some network like UNet?

### ISSUE THREAD

**Issue by aimhabo** [open-mmlab/mmdetection#111]
I see that several of the provided networks use ResNet as backbone directly to extract features. If I want to re-magnify features like UNet and map back to the input size step by step, can it generate by mmdetection automously? or if I build it by pytorch, could train.py use that?

**Comment by hellock** [comment]
You can add new backbones under `models/backbones`, e.g., `unet.py`, and then specify it in config files.

`unet.py`
```python
class UNet(nn.Module):

    def __init__(self):
        pass

    def forward(self):
        pass
```

config file
```
model = dict(backbone=(type='UNet', xxxx), xxxx)
```
