### ISSUE TITLE
Grounding-DINO模型如何在COCO数据集上评估

### ISSUE THREAD

**Issue by lybllybl** [open-mmlab/mmdetection#11121]
请问关于Grounding-DINO模型，如何在COCO数据集上评估，readme中没有对应指令，demo中也未看到对应文件。

**Comment by hhaAndroid** [comment]
python tools/test.py configs/glip/glip_atss_swin-t_a_fpn_dyhead_pretrain_obj365.py glip_tiny_a_mmdet-b3654169.pth

**Comment by lybllybl** [comment]
> python tools/test.py configs/glip/glip_atss_swin-t_a_fpn_dyhead_pretrain_obj365.py glip_tiny_a_mmdet-b3654169.pth

谢谢
