### ISSUE TITLE
Can I do something like mixing up data

### ISSUE THREAD

**Issue by ElegantLin** [open-mmlab/mmdetection#1113]
Thanks for your system. I read your code and I found that the system builds a dataloader and then passed it to the Runner from mmcv. If I want to do something like mixup that is to change something in every epoch. Could I do this?

Thanks.

**Comment by ujsyehao** [comment]
@ElegantLin Do you implement it?

**Comment by XGuider** [comment]
@ElegantLin @ujsyehao  Have you successfully implemented it?

**Comment by kaikaizhu** [comment]
@ElegantLin @ujsyehao @XGuider Have you successfully implemented it?

**Comment by huangrichen11** [comment]
mixup toy code:
```
@PIELINES.register_module
class Mixup(object):
    def __init__(self, mixup_dataset_list):
         # read image list from  mixup_dataset_list
    def __call__(self, results):
         # here implement mixup
         # read from mixup_dataset_list 
         # mix up image
         # using mixed image instead of results['img']
         # add labels from img to results['gt_labels']
         # modify bboxes after mix up and add bboxes to  results['gt_labels']
        return results
```

**Comment by 1771203081** [comment]
@huangrichen11  but how modify weight of loss

**Comment by huangrichen11** [comment]
> @huangrichen11 but how modify weight of loss

you can set weight value in config file

**Comment by ElegantLin** [comment]
Thanks for your code.

**Comment by yustaub** [comment]
@ElegantLin  hi, do you solve mixup in mmdetection?
