### ISSUE TITLE
torchvision://resnet101 is not a checkpoint file

### ISSUE THREAD

**Issue by zh99li** [open-mmlab/mmdetection#1118]
how to solve this problem：torchvision://resnet101 is not a checkpoint file

**Comment by hellock** [comment]
You need to upgrade mmcv to the latest version.

**Comment by zh99li** [comment]
> You need to upgrade mmcv to the latest version.

thank you very much!

**Comment by Vieeo** [comment]
help! I have the same problem, and I have upgraded mmcv-full to the latest version,but it still can't run.
