### ISSUE TITLE
Not support ROI with unequal height and width

### ISSUE THREAD

**Issue by BlakeXiaochu** [open-mmlab/mmdetection#1119]
For some applications, such as pedestrian detection or scene text detection, ROI with equal spatial sizes may lead to sub-optimal results.
It seems that ROI with unequal height and width is not supported in the current code.
In ROI extraction operations (e.g. ROIAlign), I find out_size can be a tuple of int, which respectively specifies the ROI height and width. 
But for the subsequent [bbox_head](https://github.com/open-mmlab/mmdetection/blob/d2483e15fc48b4166815c15a6e12be864bcc521a/mmdet/models/bbox_heads/bbox_head.py#L53), the roi_feat_size must be a int , which means the height and width of ROI must be equal. Also, when [generating the mask target](https://github.com/open-mmlab/mmdetection/blob/d2483e15fc48b4166815c15a6e12be864bcc521a/mmdet/core/mask/mask_target.py#L30),  the target size is (mask_size, mask_size), where mask_size is specified by train_cfg.rcnn.mask_size in the config file.
So I want to know are there some workarounds, or ROI with unequal height and width will be supported in the future? Thx~

**Comment by hellock** [comment]
You can try #1128.

**Comment by BlakeXiaochu** [comment]
Thank you, I will try it.
