### ISSUE TITLE
Can you explain more about how to distributed train on two machines each with 4 cores?

### ISSUE THREAD

**Issue by xbjxh** [open-mmlab/mmdetection#112]
Thank you so much! One machine works fine too me. But I am not sure about the setting in the configure and how to train it on two machine.

**Comment by hellock** [comment]
We just use `torch.distributed.launch` to start the training processes, see `tools/dist_train.sh` for details. If you want to train on two machines, you need to follow the "Multi-Node multi-process distributed training" part in the [documentation](https://pytorch.org/docs/stable/distributed.html#launch-utility).

Just a reminder, If multiple nodes are not connected with high-speed hardwares, it will be slow.
