### ISSUE TITLE
Finetune GroundingDINO with R50 backbone

### ISSUE THREAD

**Issue by ZitengXue** [open-mmlab/mmdetection#11201]
请问一下GroundingDINO现在只支持微调swin-t -b的版本吗，我看config只有这两个backbone的finetune，想问一下能用result里面R50的checkpoint 来Finetune吗？

**Comment by hhaAndroid** [comment]
不能，因为那个是直接训练的，不具备 zero-shot 性能，所以微调的话，其实还不如重新训练。
