### ISSUE TITLE
[Grounding Dino] A script transform from MMdetection .pth to Official version.pth

### ISSUE THREAD

**Issue by XYX1998** [open-mmlab/mmdetection#11200]
模仿tools/model_converters/groundingdino_to_mmdet.py 写了个MMdetection转官方的，把每个节点的name都对齐了，但是发现官方的模型回多几个节点，最后跑出来只有一个整张图片大小的框，请问有什么解决方法吗？

```code```
def convert(ckpt):
        new_ckpt = OrderedDict()
        for k, v in list(ckpt.items()):
        new_v = v
          
        if k[:7] == 'module.':
            # NOTE: swin-b has no module prefix and swin-t has module prefix
            parts = k.split('.')
            k = '.'.join(parts[1:])
        if 'module.transformer.decoder.bbox_embed' in k:
            print(k)
            # NOTE: bbox_embed name is swin-b is different from swin-t
            new_k = k.replace('module.transformer.decoder.bbox_embed','module.bbox_embed')
        if  'language_model.language_backbone.body.model' in k:
            new_k = k.replace('language_model.language_backbone.body.model','module.bert')
        elif 'backbone' in k:
            new_k = k.replace('backbone','module.backbone.0')
            if 'patch_embed.projection' in new_k:
                new_k = new_k.replace('patch_embed.projection','patch_embed.proj')
            elif 'drop_after_pos' in new_k:
                new_k = new_k.replace( 'drop_after_pos','pos_drop')

            if  'stages' in new_k:
                new_k = new_k.replace('stages','layers')
                if 'ffn.layers.0.0' in new_k:
                    new_k = new_k.replace('ffn.layers.0.0','mlp.fc1')
                elif 'ffn.layers.1' in new_k:
                    new_k = new_k.replace( 'ffn.layers.1','mlp.fc2')
                elif 'attn.w_msa' in new_k:
                    new_k = new_k.replace('attn.w_msa','attn')

                if 'downsample' in k:
                    if 'reduction.' in k:
                        new_v = reverse_correct_unfold_reduction_order(v)
                    elif 'norm.' in k:
                        new_v = reverse_correct_unfold_norm_order(v)
        elif  'text_feat_map' in k:
            new_k = k.replace( 'text_feat_map','module.feat_map')
        elif 'neck.extra_convs.0' in k or 'neck.convs' in k:
            # extra convs for 4th scale
            new_k = k.replace('neck.extra_convs.0','neck.convs.3')
            if 'neck.convs' in new_k:
                new_k = new_k.replace('neck.convs','module.input_proj')
                if 'conv.weight' in new_k:
                    # 0.weight -> conv.weight
                    new_k = new_k.replace('conv.weight','0.weight')
                if 'conv.bias' in new_k:
                    # 0.bias -> conv.bias
                    new_k = new_k.replace('conv.bias','0.bias')
                if 'gn.weight' in new_k:
                    # 1.weight -> gn.weight
                    new_k = new_k.replace('gn.weight','1.weight')
                if  'gn.bias' in new_k:
                    # 1.bias -> gn.bias
                    new_k = new_k.replace('gn.bias','1.bias')

        elif 'level_embed' in k:
            # module.transformer.level_embed -> level_embed
            new_k = k.replace('level_embed','module.transformer.level_embed')

        elif  'encoder'  in k:
            # if '.layers' in k:
            new_k = k.replace('encoder','module.transformer.encoder',)
            if 'norms.0' in new_k:
                new_k = new_k.replace('norms.0', 'norm1')
            if 'norms.1' in new_k:
                new_k = new_k.replace('norms.1', 'norm2')
            if 'norms.2' in new_k:
                new_k = new_k.replace('norms.2', 'norm3')
            if 'norms.w' in new_k:
                new_k = new_k.replace('norms.w', 'normse')
            if 'ffn.layers.0.0' in new_k:
                new_k = new_k.replace('ffn.layers.0.0','linear1')
            if 'ffn.layers.1' in new_k:
                new_k = new_k.replace('ffn.layers.1','linear2')

            if 'text_layers' in new_k and 'self_attn.attn' in new_k:
                new_k = new_k.replace('self_attn.attn', 'self_attn')
        elif 'memory_trans_' in k:
            if 'memory_trans_fc' in k and 'norm' not in k:
                new_k = k.replace('memory_trans_fc','module.transformer.enc_output')
            new_k = k.replace('memory_trans_fc', 'module.transformer.enc_output')
            if 'memory_trans_norm' in k:
                new_k = k.replace('memory_trans_norm','module.transformer.enc_output_norm')
        elif 'bbox_head.reg_branches.6' in k:
            if 'bbox_head.reg_branches.6.0' in k:
                new_k = k.replace(
                    'bbox_head.reg_branches.6.0',
                    'module.transformer.enc_out_bbox_embed.layers.0')
            if 'bbox_head.reg_branches.6.2' in k:
                new_k = k.replace(
                    'bbox_head.reg_branches.6.2',
                    'module.transformer.enc_out_bbox_embed.layers.1')
            if 'bbox_head.reg_branches.6.4' in k:
                new_k = k.replace(
                    'bbox_head.reg_branches.6.4',
                    'module.transformer.enc_out_bbox_embed.layers.2')
        elif 'bbox_head.reg_branches' in k:
            parts = k.split('.')
            weight_or_bias = parts[-1]
            linear_id = int(parts[-2]) // 2  # Undo the multiplication by 2
            reg_layer_id = int(parts[-3])
            new_k = f'module.transformer.decoder.bbox_embed.{reg_layer_id}.layers.{linear_id}.{weight_or_bias}'

        elif 'query_embedding' in k:
                new_k = k.replace('query_embedding',
                                'module.transformer.tgt_embed')

        elif 'decoder'in k:
            new_k = k.replace('decoder','module.transformer.decoder')
            if  'norms.2' in new_k:
                # norm1 in official GroundingDINO is the third norm in decoder
                new_k = new_k.replace( 'norms.2','norm1')
            if 'norms.1' in new_k:
                # catext_norm in official GroundingDINO is the
                # second norm in decoder
                new_k = new_k.replace('norms.1','catext_norm')
            if 'norms.0' in new_k:
                # norm2 in official GroundingDINO is the first norm in decoder
                new_k = new_k.replace('norms.0', 'norm2')
            if 'norms.3' in new_k:
                new_k = new_k.replace('norms.3', 'norm3')
            if 'cross_attn_text' in new_k:
                new_k = new_k.replace( 'cross_attn_text','ca_text')
                if 'attn.in_proj_weight' in new_k:
                    new_k = new_k.replace('attn.in_proj_weight','in_proj_weight')
                if 'attn.in_proj_bias' in new_k:
                    new_k = new_k.replace('attn.in_proj_bias','in_proj_bias')
                if 'attn.out_proj.weight' in new_k:
                    new_k = new_k.replace('attn.out_proj.weight','out_proj.weight')
                if 'attn.out_proj.bias' in new_k:
                    new_k = new_k.replace('attn.out_proj.bias','out_proj.bias')
            if  'ffn.layers.0.0' in new_k:
                new_k = new_k.replace( 'ffn.layers.0.0','linear1')
            if 'ffn.layers.1' in new_k:
                new_k = new_k.replace('ffn.layers.1','linear2')
            if 'self_attn.attn' in new_k:
                new_k = new_k.replace('self_attn.attn','self_attn')
        else:
            print('skip:', k)
            continue

        new_ckpt[new_k] = new_v
    return new_ckpt

```code```
多出来的节点名为
module.bbox_embed.4.layers.0.weight
module.bbox_embed.2.layers.1.bias
module.bbox_embed.1.layers.0.bias
module.bbox_embed.1.layers.2.weight
module.bbox_embed.0.layers.1.weight
module.bbox_embed.5.layers.0.bias
module.bbox_embed.0.layers.2.weight
module.bbox_embed.3.layers.1.weight
module.bbox_embed.5.layers.2.bias
module.bbox_embed.0.layers.1.bias
module.bbox_embed.4.layers.0.bias
module.bbox_embed.2.layers.2.weight
module.bbox_embed.5.layers.2.weight
module.bbox_embed.0.layers.2.bias
module.bbox_embed.4.layers.2.weight
module.bbox_embed.5.layers.0.weight
module.bbox_embed.3.layers.2.weight
module.bbox_embed.2.layers.1.weight
module.bbox_embed.5.layers.1.weight
module.label_enc.weight
module.bbox_embed.3.layers.0.bias
module.bbox_embed.3.layers.2.bias
module.bbox_embed.2.layers.0.weight
module.bbox_embed.4.layers.2.bias
module.bbox_embed.2.layers.0.bias
module.bbox_embed.4.layers.1.bias
module.bbox_embed.0.layers.0.weight
module.bbox_embed.5.layers.1.bias
module.bbox_embed.3.layers.1.bias
module.bbox_embed.3.layers.0.weight
module.bbox_embed.1.layers.0.weight
module.bbox_embed.2.layers.2.bias
module.bbox_embed.4.layers.1.weight
module.bbox_embed.1.layers.2.bias
module.bbox_embed.1.layers.1.weight
module.bbox_embed.1.layers.1.bias
module.bbox_embed.0.layers.0.bias

**Comment by XYX1998** [comment]
> 请问转回官方的代码进行推理的意义是啥呢？ 是有啥特殊需求在 mmdet 中无法满足吗？

用mmdetection微调之后，想转回官方的代码去进行ONNX部署

**Comment by hhaAndroid** [comment]
@XYX1998 恩，这是一个好问题，我们确实没有支持部署，我看下能不能催一下

**Comment by Justin900429** [comment]
@XYX1998 

基於你提供的程式碼，我在最後把 `module.bbox_embed` 之後加回去就可以獲得正常的結果了

```
def convert(ckpt):
    new_ckpt = OrderedDict()
    for k, v in list(ckpt.items()):
        new_v = v

        if k[:7] == 'module.':
            # NOTE: swin-b has no module prefix and swin-t has module prefix
            parts = k.split('.')
            k = '.'.join(parts[1:])
        if 'module.transformer.decoder.bbox_embed' in k:
            # NOTE: bbox_embed name is swin-b is different from swin-t
            new_k = k.replace('module.transformer.decoder.bbox_embed','module.bbox_embed')
        if  'language_model.language_backbone.body.model' in k:
            new_k = k.replace('language_model.language_backbone.body.model','module.bert')
        elif 'backbone' in k:
            new_k = k.replace('backbone','module.backbone.0')
            if 'patch_embed.projection' in new_k:
                new_k = new_k.replace('patch_embed.projection','patch_embed.proj')
            elif 'drop_after_pos' in new_k:
                new_k = new_k.replace( 'drop_after_pos','pos_drop')

            if  'stages' in new_k:
                new_k = new_k.replace('stages','layers')
                if 'ffn.layers.0.0' in new_k:
                    new_k = new_k.replace('ffn.layers.0.0','mlp.fc1')
                elif 'ffn.layers.1' in new_k:
                    new_k = new_k.replace( 'ffn.layers.1','mlp.fc2')
                elif 'attn.w_msa' in new_k:
                    new_k = new_k.replace('attn.w_msa','attn')

                if 'downsample' in k:
                    if 'reduction.' in k:
                        new_v = reverse_correct_unfold_reduction_order(v)
                    elif 'norm.' in k:
                        new_v = reverse_correct_unfold_norm_order(v)
        elif  'text_feat_map' in k:
            new_k = k.replace( 'text_feat_map','module.feat_map')
        elif 'neck.extra_convs.0' in k or 'neck.convs' in k:
            # extra convs for 4th scale
            new_k = k.replace('neck.extra_convs.0','neck.convs.3')
            if 'neck.convs' in new_k:
                new_k = new_k.replace('neck.convs','module.input_proj')
                if 'conv.weight' in new_k:
                    # 0.weight -> conv.weight
                    new_k = new_k.replace('conv.weight','0.weight')
                if 'conv.bias' in new_k:
                    # 0.bias -> conv.bias
                    new_k = new_k.replace('conv.bias','0.bias')
                if 'gn.weight' in new_k:
                    # 1.weight -> gn.weight
                    new_k = new_k.replace('gn.weight','1.weight')
                if  'gn.bias' in new_k:
                    # 1.bias -> gn.bias
                    new_k = new_k.replace('gn.bias','1.bias')

        elif 'level_embed' in k:
            # module.transformer.level_embed -> level_embed
            new_k = k.replace('level_embed','module.transformer.level_embed')

        elif  'encoder'  in k:
            # if '.layers' in k:
            new_k = k.replace('encoder','module.transformer.encoder',)
            if 'norms.0' in new_k:
                new_k = new_k.replace('norms.0', 'norm1')
            if 'norms.1' in new_k:
                new_k = new_k.replace('norms.1', 'norm2')
            if 'norms.2' in new_k:
                new_k = new_k.replace('norms.2', 'norm3')
            if 'norms.w' in new_k:
                new_k = new_k.replace('norms.w', 'normse')
            if 'ffn.layers.0.0' in new_k:
                new_k = new_k.replace('ffn.layers.0.0','linear1')
            if 'ffn.layers.1' in new_k:
                new_k = new_k.replace('ffn.layers.1','linear2')

            if 'text_layers' in new_k and 'self_attn.attn' in new_k:
                new_k = new_k.replace('self_attn.attn', 'self_attn')
        elif 'memory_trans_' in k:
            if 'memory_trans_fc' in k and 'norm' not in k:
                new_k = k.replace('memory_trans_fc','module.transformer.enc_output')
            new_k = k.replace('memory_trans_fc', 'module.transformer.enc_output')
            if 'memory_trans_norm' in k:
                new_k = k.replace('memory_trans_norm','module.transformer.enc_output_norm')
        elif 'bbox_head.reg_branches.6' in k:
            if 'bbox_head.reg_branches.6.0' in k:
                new_k = k.replace(
                    'bbox_head.reg_branches.6.0',
                    'module.transformer.enc_out_bbox_embed.layers.0')
            if 'bbox_head.reg_branches.6.2' in k:
                new_k = k.replace(
                    'bbox_head.reg_branches.6.2',
                    'module.transformer.enc_out_bbox_embed.layers.1')
            if 'bbox_head.reg_branches.6.4' in k:
                new_k = k.replace(
                    'bbox_head.reg_branches.6.4',
                    'module.transformer.enc_out_bbox_embed.layers.2')
        elif 'bbox_head.reg_branches' in k:
            parts = k.split('.')
            weight_or_bias = parts[-1]
            linear_id = int(parts[-2]) // 2  # Undo the multiplication by 2
            reg_layer_id = int(parts[-3])
            new_k = f'module.transformer.decoder.bbox_embed.{reg_layer_id}.layers.{linear_id}.{weight_or_bias}'

        elif 'query_embedding' in k:
                new_k = k.replace('query_embedding',
                                'module.transformer.tgt_embed')


        elif k.startswith('decoder'):
            new_k = k.replace('decoder','module.transformer.decoder', 1)
            if  'norms.2' in new_k:
                # norm1 in official GroundingDINO is the third norm in decoder
                new_k = new_k.replace( 'norms.2','norm1')
            if 'norms.1' in new_k:
                # catext_norm in official GroundingDINO is the
                # second norm in decoder
                new_k = new_k.replace('norms.1','catext_norm')
            if 'norms.0' in new_k:
                # norm2 in official GroundingDINO is the first norm in decoder
                new_k = new_k.replace('norms.0', 'norm2')
            if 'norms.3' in new_k:
                new_k = new_k.replace('norms.3', 'norm3')
            if 'cross_attn_text' in new_k:
                new_k = new_k.replace( 'cross_attn_text','ca_text')
                if 'attn.in_proj_weight' in new_k:
                    new_k = new_k.replace('attn.in_proj_weight','in_proj_weight')
                if 'attn.in_proj_bias' in new_k:
                    new_k = new_k.replace('attn.in_proj_bias','in_proj_bias')
                if 'attn.out_proj.weight' in new_k:
                    new_k = new_k.replace('attn.out_proj.weight','out_proj.weight')
                if 'attn.out_proj.bias' in new_k:
                    new_k = new_k.replace('attn.out_proj.bias','out_proj.bias')
            if  'ffn.layers.0.0' in new_k:
                new_k = new_k.replace( 'ffn.layers.0.0','linear1')
            if 'ffn.layers.1' in new_k:
                new_k = new_k.replace('ffn.layers.1','linear2')
            if 'self_attn.attn' in new_k:
                new_k = new_k.replace('self_attn.attn','self_attn')
        else:
            print('skip:', k)
            continue

        new_ckpt[new_k] = new_v
        
        if new_k.startswith("module.transformer.decoder.bbox_embed"):
            new_ckpt[new_k.replace("module.transformer.decoder.bbox_embed", "module.bbox_embed")] = new_v
    return new_ckpt
```

另外的反轉程式碼

```python
def reverse_correct_unfold_reduction_order(x):
    out_channel, in_channel = x.shape
    x = x.reshape(out_channel, in_channel // 4, 4)
    x = x[:, :, [0, 2, 1, 3]].transpose(1, 2).reshape(out_channel, in_channel)
    return x


def reverse_correct_unfold_norm_order(x):
    in_channel = x.shape[0]
    x = x.reshape(in_channel // 4, 4)
    x = x[:, [0, 2, 1, 3]].transpose(0, 1).reshape(in_channel)
    return x
```

**Comment by XYX1998** [comment]
> @XYX1998
> 
> 基於你提供的程式碼，我在最後把 `module.bbox_embed` 之後加回去就可以獲得正常的結果了. 有稍微更改一下，也支援 Swin-b。
> 
> ```python
> def convert(ckpt, swin_b=False):
>     new_ckpt = OrderedDict()
>     for k, v in list(ckpt.items()):
>         new_v = v
>         
>         if  "language_model.language_backbone.body.model" in k:
>             new_k = k.replace("language_model.language_backbone.body.model","module.bert")
>         elif "backbone" in k:
>             new_k = k.replace("backbone","module.backbone.0")
>             if "patch_embed.projection" in new_k:
>                 new_k = new_k.replace("patch_embed.projection","patch_embed.proj")
>             elif "drop_after_pos" in new_k:
>                 new_k = new_k.replace( "drop_after_pos","pos_drop")
> 
>             if  "stages" in new_k:
>                 new_k = new_k.replace("stages","layers")
>                 if "ffn.layers.0.0" in new_k:
>                     new_k = new_k.replace("ffn.layers.0.0","mlp.fc1")
>                 elif "ffn.layers.1" in new_k:
>                     new_k = new_k.replace( "ffn.layers.1","mlp.fc2")
>                 elif "attn.w_msa" in new_k:
>                     new_k = new_k.replace("attn.w_msa","attn")
> 
>                 if "downsample" in k:
>                     if "reduction." in k:
>                         new_v = reverse_correct_unfold_reduction_order(v)
>                     elif "norm." in k:
>                         new_v = reverse_correct_unfold_norm_order(v)
>         elif  "text_feat_map" in k:
>             new_k = k.replace( "text_feat_map","module.feat_map")
>         elif "neck.extra_convs.0" in k or "neck.convs" in k:
>             # extra convs for 4th scale
>             new_k = k.replace("neck.extra_convs.0","neck.convs.3")
>             if "neck.convs" in new_k:
>                 new_k = new_k.replace("neck.convs","module.input_proj")
>                 if "conv.weight" in new_k:
>                     # 0.weight -> conv.weight
>                     new_k = new_k.replace("conv.weight","0.weight")
>                 if "conv.bias" in new_k:
>                     # 0.bias -> conv.bias
>                     new_k = new_k.replace("conv.bias","0.bias")
>                 if "gn.weight" in new_k:
>                     # 1.weight -> gn.weight
>                     new_k = new_k.replace("gn.weight","1.weight")
>                 if  "gn.bias" in new_k:
>                     # 1.bias -> gn.bias
>                     new_k = new_k.replace("gn.bias","1.bias")
> 
>         elif "level_embed" in k:
>             # module.transformer.level_embed -> level_embed
>             new_k = k.replace("level_embed","module.transformer.level_embed")
> 
>         elif  "encoder"  in k:
>             # if ".layers" in k:
>             new_k = k.replace("encoder","module.transformer.encoder",)
>             if "norms.0" in new_k:
>                 new_k = new_k.replace("norms.0", "norm1")
>             if "norms.1" in new_k:
>                 new_k = new_k.replace("norms.1", "norm2")
>             if "norms.2" in new_k:
>                 new_k = new_k.replace("norms.2", "norm3")
>             if "norms.w" in new_k:
>                 new_k = new_k.replace("norms.w", "normse")
>             if "ffn.layers.0.0" in new_k:
>                 new_k = new_k.replace("ffn.layers.0.0","linear1")
>             if "ffn.layers.1" in new_k:
>                 new_k = new_k.replace("ffn.layers.1","linear2")
> 
>             if "text_layers" in new_k and "self_attn.attn" in new_k:
>                 new_k = new_k.replace("self_attn.attn", "self_attn")
>         elif "memory_trans_" in k:
>             if "memory_trans_fc" in k and "norm" not in k:
>                 new_k = k.replace("memory_trans_fc","module.transformer.enc_output")
>             new_k = k.replace("memory_trans_fc", "module.transformer.enc_output")
>             if "memory_trans_norm" in k:
>                 new_k = k.replace("memory_trans_norm","module.transformer.enc_output_norm")
>         elif "bbox_head.reg_branches.6" in k:
>             if "bbox_head.reg_branches.6.0" in k:
>                 new_k = k.replace(
>                     "bbox_head.reg_branches.6.0",
>                     "module.transformer.enc_out_bbox_embed.layers.0")
>             if "bbox_head.reg_branches.6.2" in k:
>                 new_k = k.replace(
>                     "bbox_head.reg_branches.6.2",
>                     "module.transformer.enc_out_bbox_embed.layers.1")
>             if "bbox_head.reg_branches.6.4" in k:
>                 new_k = k.replace(
>                     "bbox_head.reg_branches.6.4",
>                     "module.transformer.enc_out_bbox_embed.layers.2")
>         elif "bbox_head.reg_branches" in k:
>             parts = k.split(".")
>             weight_or_bias = parts[-1]
>             linear_id = int(parts[-2]) // 2  # Undo the multiplication by 2
>             reg_layer_id = int(parts[-3])
>             new_k = f"module.transformer.decoder.bbox_embed.{reg_layer_id}.layers.{linear_id}.{weight_or_bias}"
> 
>         elif "query_embedding" in k:
>                 new_k = k.replace("query_embedding",
>                                 "module.transformer.tgt_embed")
> 
> 
>         elif k.startswith("decoder"):
>             new_k = k.replace("decoder","module.transformer.decoder", 1)
>             if  "norms.2" in new_k:
>                 # norm1 in official GroundingDINO is the third norm in decoder
>                 new_k = new_k.replace( "norms.2","norm1")
>             if "norms.1" in new_k:
>                 # catext_norm in official GroundingDINO is the
>                 # second norm in decoder
>                 new_k = new_k.replace("norms.1","catext_norm")
>             if "norms.0" in new_k:
>                 # norm2 in official GroundingDINO is the first norm in decoder
>                 new_k = new_k.replace("norms.0", "norm2")
>             if "norms.3" in new_k:
>                 new_k = new_k.replace("norms.3", "norm3")
>             if "cross_attn_text" in new_k:
>                 new_k = new_k.replace( "cross_attn_text","ca_text")
>                 if "attn.in_proj_weight" in new_k:
>                     new_k = new_k.replace("attn.in_proj_weight","in_proj_weight")
>                 if "attn.in_proj_bias" in new_k:
>                     new_k = new_k.replace("attn.in_proj_bias","in_proj_bias")
>                 if "attn.out_proj.weight" in new_k:
>                     new_k = new_k.replace("attn.out_proj.weight","out_proj.weight")
>                 if "attn.out_proj.bias" in new_k:
>                     new_k = new_k.replace("attn.out_proj.bias","out_proj.bias")
>             if  "ffn.layers.0.0" in new_k:
>                 new_k = new_k.replace( "ffn.layers.0.0","linear1")
>             if "ffn.layers.1" in new_k:
>                 new_k = new_k.replace("ffn.layers.1","linear2")
>             if "self_attn.attn" in new_k:
>                 new_k = new_k.replace("self_attn.attn","self_attn")
>         else:
>             print("skip:", k)
>             continue
> 
>         if swin_b and new_k.startswith("module"):
>             new_k = new_k.replace("module.", "")
>         new_ckpt[new_k] = new_v
>         
>         if "transformer.decoder.bbox_embed" in new_k:
>             new_ckpt[new_k.replace("transformer.decoder.bbox_embed", "bbox_embed")] = new_v
>     return new_ckpt
> ```
> 
> 另外的反轉程式碼
> 
> ```python
> def reverse_correct_unfold_reduction_order(x):
>     out_channel, in_channel = x.shape
>     x = x.reshape(out_channel, in_channel // 4, 4)
>     x = x[:, :, [0, 2, 1, 3]].transpose(1, 2).reshape(out_channel, in_channel)
>     return x
> 
> 
> def reverse_correct_unfold_norm_order(x):
>     in_channel = x.shape[0]
>     x = x.reshape(in_channel // 4, 4)
>     x = x[:, [0, 2, 1, 3]].transpose(0, 1).reshape(in_channel)
>     return x
> ```

Thx, that helps a lot

**Comment by onnx20** [comment]
> @XYX1998
> 
> 基於你提供的程式碼，我在最後把 `module.bbox_embed` 之後加回去就可以獲得正常的結果了. 有稍微更改一下，也支援 Swin-b。
> 
> ```python
> def convert(ckpt, swin_b=False):
>     new_ckpt = OrderedDict()
>     for k, v in list(ckpt.items()):
>         new_v = v
>         
>         if  "language_model.language_backbone.body.model" in k:
>             new_k = k.replace("language_model.language_backbone.body.model","module.bert")
>         elif "backbone" in k:
>             new_k = k.replace("backbone","module.backbone.0")
>             if "patch_embed.projection" in new_k:
>                 new_k = new_k.replace("patch_embed.projection","patch_embed.proj")
>             elif "drop_after_pos" in new_k:
>                 new_k = new_k.replace( "drop_after_pos","pos_drop")
> 
>             if  "stages" in new_k:
>                 new_k = new_k.replace("stages","layers")
>                 if "ffn.layers.0.0" in new_k:
>                     new_k = new_k.replace("ffn.layers.0.0","mlp.fc1")
>                 elif "ffn.layers.1" in new_k:
>                     new_k = new_k.replace( "ffn.layers.1","mlp.fc2")
>                 elif "attn.w_msa" in new_k:
>                     new_k = new_k.replace("attn.w_msa","attn")
> 
>                 if "downsample" in k:
>                     if "reduction." in k:
>                         new_v = reverse_correct_unfold_reduction_order(v)
>                     elif "norm." in k:
>                         new_v = reverse_correct_unfold_norm_order(v)
>         elif  "text_feat_map" in k:
>             new_k = k.replace( "text_feat_map","module.feat_map")
>         elif "neck.extra_convs.0" in k or "neck.convs" in k:
>             # extra convs for 4th scale
>             new_k = k.replace("neck.extra_convs.0","neck.convs.3")
>             if "neck.convs" in new_k:
>                 new_k = new_k.replace("neck.convs","module.input_proj")
>                 if "conv.weight" in new_k:
>                     # 0.weight -> conv.weight
>                     new_k = new_k.replace("conv.weight","0.weight")
>                 if "conv.bias" in new_k:
>                     # 0.bias -> conv.bias
>                     new_k = new_k.replace("conv.bias","0.bias")
>                 if "gn.weight" in new_k:
>                     # 1.weight -> gn.weight
>                     new_k = new_k.replace("gn.weight","1.weight")
>                 if  "gn.bias" in new_k:
>                     # 1.bias -> gn.bias
>                     new_k = new_k.replace("gn.bias","1.bias")
> 
>         elif "level_embed" in k:
>             # module.transformer.level_embed -> level_embed
>             new_k = k.replace("level_embed","module.transformer.level_embed")
> 
>         elif  "encoder"  in k:
>             # if ".layers" in k:
>             new_k = k.replace("encoder","module.transformer.encoder",)
>             if "norms.0" in new_k:
>                 new_k = new_k.replace("norms.0", "norm1")
>             if "norms.1" in new_k:
>                 new_k = new_k.replace("norms.1", "norm2")
>             if "norms.2" in new_k:
>                 new_k = new_k.replace("norms.2", "norm3")
>             if "norms.w" in new_k:
>                 new_k = new_k.replace("norms.w", "normse")
>             if "ffn.layers.0.0" in new_k:
>                 new_k = new_k.replace("ffn.layers.0.0","linear1")
>             if "ffn.layers.1" in new_k:
>                 new_k = new_k.replace("ffn.layers.1","linear2")
> 
>             if "text_layers" in new_k and "self_attn.attn" in new_k:
>                 new_k = new_k.replace("self_attn.attn", "self_attn")
>         elif "memory_trans_" in k:
>             if "memory_trans_fc" in k and "norm" not in k:
>                 new_k = k.replace("memory_trans_fc","module.transformer.enc_output")
>             new_k = k.replace("memory_trans_fc", "module.transformer.enc_output")
>             if "memory_trans_norm" in k:
>                 new_k = k.replace("memory_trans_norm","module.transformer.enc_output_norm")
>         elif "bbox_head.reg_branches.6" in k:
>             if "bbox_head.reg_branches.6.0" in k:
>                 new_k = k.replace(
>                     "bbox_head.reg_branches.6.0",
>                     "module.transformer.enc_out_bbox_embed.layers.0")
>             if "bbox_head.reg_branches.6.2" in k:
>                 new_k = k.replace(
>                     "bbox_head.reg_branches.6.2",
>                     "module.transformer.enc_out_bbox_embed.layers.1")
>             if "bbox_head.reg_branches.6.4" in k:
>                 new_k = k.replace(
>                     "bbox_head.reg_branches.6.4",
>                     "module.transformer.enc_out_bbox_embed.layers.2")
>         elif "bbox_head.reg_branches" in k:
>             parts = k.split(".")
>             weight_or_bias = parts[-1]
>             linear_id = int(parts[-2]) // 2  # Undo the multiplication by 2
>             reg_layer_id = int(parts[-3])
>             new_k = f"module.transformer.decoder.bbox_embed.{reg_layer_id}.layers.{linear_id}.{weight_or_bias}"
> 
>         elif "query_embedding" in k:
>                 new_k = k.replace("query_embedding",
>                                 "module.transformer.tgt_embed")
> 
> 
>         elif k.startswith("decoder"):
>             new_k = k.replace("decoder","module.transformer.decoder", 1)
>             if  "norms.2" in new_k:
>                 # norm1 in official GroundingDINO is the third norm in decoder
>                 new_k = new_k.replace( "norms.2","norm1")
>             if "norms.1" in new_k:
>                 # catext_norm in official GroundingDINO is the
>                 # second norm in decoder
>                 new_k = new_k.replace("norms.1","catext_norm")
>             if "norms.0" in new_k:
>                 # norm2 in official GroundingDINO is the first norm in decoder
>                 new_k = new_k.replace("norms.0", "norm2")
>             if "norms.3" in new_k:
>                 new_k = new_k.replace("norms.3", "norm3")
>             if "cross_attn_text" in new_k:
>                 new_k = new_k.replace( "cross_attn_text","ca_text")
>                 if "attn.in_proj_weight" in new_k:
>                     new_k = new_k.replace("attn.in_proj_weight","in_proj_weight")
>                 if "attn.in_proj_bias" in new_k:
>                     new_k = new_k.replace("attn.in_proj_bias","in_proj_bias")
>                 if "attn.out_proj.weight" in new_k:
>                     new_k = new_k.replace("attn.out_proj.weight","out_proj.weight")
>                 if "attn.out_proj.bias" in new_k:
>                     new_k = new_k.replace("attn.out_proj.bias","out_proj.bias")
>             if  "ffn.layers.0.0" in new_k:
>                 new_k = new_k.replace( "ffn.layers.0.0","linear1")
>             if "ffn.layers.1" in new_k:
>                 new_k = new_k.replace("ffn.layers.1","linear2")
>             if "self_attn.attn" in new_k:
>                 new_k = new_k.replace("self_attn.attn","self_attn")
>         else:
>             print("skip:", k)
>             continue
> 
>         if swin_b and new_k.startswith("module"):
>             new_k = new_k.replace("module.", "")
>         new_ckpt[new_k] = new_v
>         
>         if "transformer.decoder.bbox_embed" in new_k:
>             new_ckpt[new_k.replace("transformer.decoder.bbox_embed", "bbox_embed")] = new_v
>     return new_ckpt
> ```
> 
> 另外的反轉程式碼
> 
> ```python
> def reverse_correct_unfold_reduction_order(x):
>     out_channel, in_channel = x.shape
>     x = x.reshape(out_channel, in_channel // 4, 4)
>     x = x[:, :, [0, 2, 1, 3]].transpose(1, 2).reshape(out_channel, in_channel)
>     return x
> 
> 
> def reverse_correct_unfold_norm_order(x):
>     in_channel = x.shape[0]
>     x = x.reshape(in_channel // 4, 4)
>     x = x[:, [0, 2, 1, 3]].transpose(0, 1).reshape(in_channel)
>     return x
> ```

你好，你这个脚本貌似只支持swinT、swinB这两种结构的模型转换，我转换swinL结构失败，需要修改哪些地方可以支持么

**Comment by YCAyca** [comment]
Hello! Thank you for this script, I have still an issue to convert mmdet fine-tuned model to official pytorch code:

![image](https://github.com/user-attachments/assets/f2b99038-be74-40f0-807b-878c6c1eecb5)

I have these layers being not converted since it doesn't have a compatible if expression in the converter, I added the following:

```
elif "bbox_head.cls_branches." in k and "log_scale" in k:
            parts = k.split(".")
            log_scale_id = int(parts[-2])  # Get the class branch ID
            new_k = f"module.transformer.decoder.cls_branches.{log_scale_id}.log_scale"  # Update this path as per your architecture
  elif "dn_query_generator.label_embedding.weight" in k:
            new_k = "module.query_generator.label_embedding.weight"
```
 But still my inference results on the converted model is nonse, having 1.0 predictions for all the classes around 100 boxes per image, totally random. Any ideas about how to convert the fine-tuned head and make it work during inference?? 
 Thanks!

**Comment by Justin900429** [comment]
@YCAyca This is the reason caused by different training objectives from the official implementation to the one in MMDetection.  See [here](https://github.com/IDEA-Research/GroundingDINO/blob/856dde20aee659246248e20734ef9ba5214f5e44/groundingdino/models/GroundingDINO/utils.py#L256-L268) and [here](https://github.com/open-mmlab/mmdetection/blob/cfd5d3a985b0249de009b67d04f37263e11cdf3d/mmdet/models/dense_heads/grounding_dino_head.py#L75-L81). 

MMDetection offers more options, such as adding bias or supporting log scale for stability. If you would like to stay with the official implementation, please set the `log_scale` option to `None` and `bias` to `False` as shown below:

```python
# Overwrite the existing config
...
bbox_head=dict(
    contrastive_cfg=dict(bias=False, log_scale=None, max_text_len=256),
    ...
),
...
```

Although this would get rid of the **skip** message, the weight provided by the MMDetection can have weird results with the official implementation. Fine-tuning with several iterations might be a must.

**Edit**: `dn_query_generator` is something for training (see [DINO](https://arxiv.org/abs/2203.03605)) and can be safely ignored for inference.

**Comment by kymroselas** [comment]
Hi @Justin900429, thank you for your help.  

You mentioned that "weight provided by the MMDetection can have weird results with the official implementation".  Why does the performance change when you convert an MMDetection model to the official implementation?  Appreciate any insight you have.
