### ISSUE TITLE
BN not frozen in neck?

### ISSUE THREAD

**Issue by EpiCabbage** [open-mmlab/mmdetection#1122]
Thank you for the amazing repo! However, I have come across freezing BN in training detection models and realize the current implementation of Neck seems to give no control of freezing BN.

In the Backbones, (taking ResNet as an example), there is a parameter called `norm_eval`

https://github.com/open-mmlab/mmdetection/blob/7b75de4dd52132080d2b9579d6736ed29c5d89b6/mmdet/models/backbones/resnet.py#L364-L382

And if it is set to True, the BN (and its variants such as SyncBN) layers is set to eval mode:

https://github.com/open-mmlab/mmdetection/blob/8f7507eb134ad3df8336931e388646647cc00727/mmdet/models/backbones/resnet.py#L518-L525
However, in the Neck (taking FPN as an example), there is no such parameter and it seems there is no line to set BN layers to eval mode. 

https://github.com/open-mmlab/mmdetection/blob/8f7507eb134ad3df8336931e388646647cc00727/mmdet/models/necks/fpn.py#L13-L24

Does this mean BN is not frozen in the Neck?

**Comment by hellock** [comment]
Usually there is no BN in `neck`.

**Comment by EpiCabbage** [comment]
Thank you for your reply. May I confirm that GN can be applied in both backbone and neck as seen in 
https://github.com/open-mmlab/mmdetection/blob/8f7507eb134ad3df8336931e388646647cc00727/configs/gn/mask_rcnn_r50_fpn_gn_2x.py#L2-L20
SyncBN can also be applied similarly by changing `type='GN'` to `type='SyncBN'`
But BN should not be applied in the neck (because there is no way to freeze it at the moment). Hence, `norm_cfg` in the neck dict should be left as None?

**Comment by qsunyuan** [comment]
Currently, my FPN neck uses BN. How should I freeze it? I cannot use the norm_eval=True as in backbone. And I think the BN will update in the forward process. 

```python
neck=dict(norm_cfg=dict('BN', required_grad=False))
"""
neck=dict(norm_cfg=dict('BN', required_grad=False), norm_eval=True)  # bug
"""
```
