### ISSUE TITLE
Unable to validate quantized or float model results when using model forward method

### ISSUE THREAD

**Issue by acg93-pixel** [open-mmlab/mmdetection#11228]
**Checklist**

1. I have searched related issues but cannot get the expected help. 
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

YES for all of the above.

**Describe the bug**
I'm using VitisAI for model quantization. I'm unable to evaluate quantized model with runner, but tried with this logic from Model's documentation (for both quantized and float model):

# Validation process
for data_batch in val_dataloader:
    data_batch = model.data_preprocessor(data_batch, training=False)
    if isinstance(data_batch, dict):
        outputs = model(**data_batch, mode='predict')
    elif isinstance(data_batch, (list, tuple)):
        outputs = model(**data_batch, mode='predict')
    else:
        raise TypeError()
    evaluator.process(data_samples=outputs, data_batch=data_batch)
metrics = evaluator.evaluate(len(val_dataloader.dataset))

and not able to get any evaluation results on COCO. Below is my script with implementation of the above logic. Building RTMDet-Ins tiny with standard config and checkpoint. Wrote script without implementing any Hooks. Please help, I'm stuck with this for days.

**Reproduction**

1. What command or script did you run?

```
import argparse
from mmengine.runner import Runner
from mmengine.config import Config

from mmdet.models.utils import unpack_gt_instances


def parse_args():
    parser = argparse.ArgumentParser(description='Testing config for the Implementation')
    parser.add_argument('-cf', '--model_config', type=str, default='')
    parser.add_argument('-c', '--checkpoint', type=str, default='')
    args = parser.parse_args()
    return args


if __name__ == '__main__':
    args = parse_args()
    ### Loading model
    config = args.model_config

    # Setup a checkpoint file to load
    checkpoint = args.checkpoint

    # Set the device to be used for evaluation
    device='cuda:0'

    # load config
    cfg = Config.fromfile(config)
    cfg.load_from = checkpoint

    runner = Runner.from_cfg(cfg)

    model = runner.model

    # implementation based on the logic from documentation
    for data_batch in runner.val_dataloader:
        data_batch = runner.model.data_preprocessor(data_batch)

        data_samples = data_batch.get('data_samples')
        batch_gt_instances, batch_gt_instances_ignore, batch_img_metas = unpack_gt_instances(data_samples)

        outputs_processed = runner.model(**data_batch, mode='predict')

        runner.val_evaluator.process(data_samples=outputs_processed, data_batch=data_batch)

        my_metrics = runner.val_evaluator.metrics[0]
    results = my_metrics.results

    metrics = my_metrics.compute_metrics(results)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Using code above, without config modifications.
3. What dataset did you use?
COCO
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3070
CUDA_HOME: /usr/local/cuda-11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.112
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.1  (built against CUDA 11.5)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2+cu117
OpenCV: 4.8.1
MMEngine: 0.9.0
MMDetection: 3.0.0+b142ca8

**Error traceback**

```Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.006
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.006
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.013
11/27 03:34:43 - mmengine - INFO - segm_mAP_copypaste: 0.000 0.000 0.000 0.000 0.000 0.000
```

**Comment by Y-T-G** [comment]
Did it actually load the checkpoint? The Runner output should say whether the checkpoint was loaded.

**Comment by Y-T-G** [comment]
You should adjust it to match [this](https://github.com/open-mmlab/mmengine/blob/85c0976bc2434157f786d44cdd8f0fb2955414f0/mmengine/evaluator/evaluator.py#L92):

```python
size=0
for data_batch in runner.val_dataloader:
        data_batch = runner.model.data_preprocessor(data_batch)

        data_samples = data_batch.get('data_samples')
        batch_gt_instances, batch_gt_instances_ignore, batch_img_metas = unpack_gt_instances(data_samples)

        outputs_processed = runner.model(**data_batch, mode='predict')

        runner.val_evaluator.process(data_samples=outputs_processed, data_batch=data_batch)

        size += len(data_batch)

    metrics = runner.val_evaluator.evaluate(size)
```
