### ISSUE TITLE
GradientCumulativeOptimizerHook does'nt work in the latest mmcv 2.1.0 ?

### ISSUE THREAD

**Issue by zhouzhen0720** [open-mmlab/mmdetection#11232]
I just add  `optimizer_config = dict(type="GradientCumulativeOptimizerHook", cumulative_iters=4)`  in projects/CO-DETR/configs/codino/co_dino_5scale_r50_lsj_8xb2_1x_coco.py, but when i debug it , I find it will still run `self.step()` and `self.zero_grad()` every iteration, so it seems GradientCumulativeOptimizerHook does'nt work in the latest mmcv 2.1.0, what should I do?

**Comment by zhouzhen0720** [comment]
I found that the reason is that many hooks have been removed in versions above mmcv2.0. So how should I use GradientCumulativeOptimizerHook in mmcv2.1.0?

**Comment by zhouzhen0720** [comment]
I found that there are significant changes in mmcv2.0 compared to the 1.x version. There have also been changes in how gradient accumulation is used. If optim_wrapper is used, you just need to add one line in the configuration file of optim_wrapper
`accumulative_counts=4`
to update the parameters with the accumulated gradients of 4 batches.

**Comment by wzwcs** [comment]
HI,i have a question.
When i set the accumulative_counts=4, should i change  lr at the same time? If i need change lr, how many i should set it?
I had one card, set batch_size=2, accumulative_counts=8, if lr=0.001 or 0.001//8 or 0.001//16?

**Comment by zhouzhen0720** [comment]
> HI,i have a question. When i set the accumulative_counts=4, should i change lr at the same time? If i need change lr, how many i should set it? I had one card, set batch_size=2, accumulative_counts=8, if lr=0.001 or 0.001//8 or 0.001//16?

I think lr should be 0.001

**Comment by wzwcs** [comment]
> > HI,i have a question. When i set the accumulative_counts=4, should i change lr at the same time? If i need change lr, how many i should set it? I had one card, set batch_size=2, accumulative_counts=8, if lr=0.001 or 0.001//8 or 0.001//16?
> 
> I think lr should be 0.001

Thank you very much!

**Comment by helloyaworld** [comment]
excuse me, I use accumulative_counts=4 but it didn't work. Can you please help me?
