### ISSUE TITLE
How to change model url ??

### ISSUE THREAD

**Issue by liugaolian** [open-mmlab/mmdetection#1124]
How to change https://s3.ap-northeast-2.amazonaws.com/open-mmlab  to https://open-mmlab.oss-cn-beijing.aliyuncs.com

Which file should we change? Thank you.

**Comment by hellock** [comment]
From `https://s3.ap-northeast-2.amazonaws.com/open-mmlab/xxxxxx` to `https://open-mmlab.oss-cn-beijing.aliyuncs.com/xxxxxxx`, where `https://s3.ap-northeast-2.amazonaws.com/open-mmlab/xxxxxx` is the model url you would like to download.

**Comment by liugaolian** [comment]
> From `https://s3.ap-northeast-2.amazonaws.com/open-mmlab/xxxxxx` to `https://open-mmlab.oss-cn-beijing.aliyuncs.com/xxxxxxx`, where `https://s3.ap-northeast-2.amazonaws.com/open-mmlab/xxxxxx` is the model url you would like to download.

Thank you！ But，Which python file should we modify?  I don't know which file to modify.
