### ISSUE TITLE
GPU memory leak during the training of Grounding-DINO

### ISSUE THREAD

**Issue by lanhas** [open-mmlab/mmdetection#11294]
During the training of Grounding-DINO, the GPU memory initially had only 19GB, but it increased to 37GB by the 1000th step.

**Comment by lanhas** [comment]
Is it related to persistent_workers=True?

**Comment by Baboom-l** [comment]
@lanhas  Hi, have you found where the problem lies

**Comment by lanhas** [comment]
> @lanhas Hi, have you found where the problem lies

Hello, this phenomenon should be a mechanism of PyTorch. When there is sufficient available GPU memory, PyTorch will allocate more space to reduce frequent memory requests in the future, even though sometimes these spaces may not be used.

I speculate that Grounding-DINO, due to the CDN, keeps requesting cache space from the GPU. Although this issue will not cause program errors, it will affect other programs running on this GPU. For example, Grounding-DINO-B can run normally with a batch size of 4 on a 24GB 4090 GPU, but on an 80GB A100 GPU, its memory usage keeps increasing and can even reach 50GB. This will impact the subsequent usage of other programs.

**Comment by Baboom-l** [comment]
Can  torch.cuda.empty_cache() solve this problem？

**Comment by lanhas** [comment]
但这样会不会导致更频繁的显存分配和释放，从而影响训练的效率。
