### ISSUE TITLE
inference on stuff class

### ISSUE THREAD

**Issue by qoo** [open-mmlab/mmdetection#1130]
I noticed the models of HTC are trained on COCO (includes stuff images). However, I used the pertained model and the result only showed 81 classes. How to show the stuff classes? 

from mmdet.apis import init_detector, inference_detector, show_result
import mmcv
config_file = 'configs/htc/htc_r50_fpn_20e.py'
checkpoint_file = 'checkpoints/htc_r50_fpn_20e_20190408-c03b7015.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
for i, result in enumerate(inference_detector(model, imgs)):
show_result(imgs[i], result, model.CLASSES, out_file='demo/{}_cascade_{}.{}'.format(filename_pre, modelName_pre, ext))

**Comment by hellock** [comment]
We just ignored predictions of the semantic segmentation branch. If you would like to show the results, you may need to add some postprocessing to the output of `HTCMaskHead`.

**Comment by Woonha** [comment]
Which kind of postprocessing should I add?

**Comment by woonhahaha** [comment]
> We just ignored predictions of the semantic segmentation branch. If you would like to show the results, you may need to add some postprocessing to the output of `HTCMaskHead`.

Which kind of postprocessing should I add?
