### ISSUE TITLE
--cfg-options 这个训练参数 指定显卡到底咋用

### ISSUE THREAD

**Issue by 15689933561** [open-mmlab/mmdetection#11308]
python tools/train.py --cfg-options device=1
这样为啥不对呢

**Comment by hhaAndroid** [comment]
指定 device 不能用这个参数，这个参数是配置的覆盖操作，要指定某一个显卡需要通过环境变量 CUDA_VISIBLE_DEVICES

**Comment by columbia617** [comment]
如何指定npu？
