### ISSUE TITLE
这是什么神奇的工具？

### ISSUE THREAD

**Issue by lanyan90** [open-mmlab/mmdetection#11311]
REDEME里第一张图，官方用的这是什么工具了？可以任选算法
![image](https://github.com/open-mmlab/mmdetection/assets/8519282/983f2602-a922-4254-b769-944714cad28c)

**Comment by hhaAndroid** [comment]
就是 gradio 做的一个演示界面而已，在 projects/gradio_demo 这里面

**Comment by lanyan90** [comment]
> 就是 gradio 做的一个演示界面而已，在 projects/gradio_demo 这里面

感谢，找到了
