### ISSUE TITLE
How to train and evaluate groundingdino on refcoco?

### ISSUE THREAD

**Issue by jiangtann** [open-mmlab/mmdetection#11321]
At [GroundingDIno RESULTS](https://github.com/open-mmlab/mmdetection/blob/main/configs/grounding_dino/README.md#results-and-models), I see the third experiment setting, i.e. `Grounding DINO-B` with pretrain data `COCO,O365,GoldG,Cap4M,OpenImage,ODinW-35,RefCOCO`. But its [config file](https://github.com/open-mmlab/mmdetection/blob/main/configs/grounding_dino/grounding_dino_swin-b_pretrain_mixeddata.py) does not contain refcoco dataset.

I need to train and evaluate on refcoco detection dataset and reproduce the result which has been reported in groundingdino paper:
![image](https://github.com/open-mmlab/mmdetection/assets/39088437/57d5787e-2cef-4d59-9e06-29d5157bf0c2)

And I see some people have raised the same question but it doesn't seem to be resolved:
https://github.com/open-mmlab/mmdetection/issues/11101
https://github.com/open-mmlab/mmdetection/issues/11010

**Comment by hhaAndroid** [comment]
@jiangtann Here https://github.com/open-mmlab/mmdetection/blob/dev-3.x/configs/mm_grounding_dino/README.md

**Comment by jiangtann** [comment]
Thanks for your work! It helps me a lot.
