### ISSUE TITLE
GDINO-T config mismatch the pretrain data

### ISSUE THREAD

**Issue by jiangtann** [open-mmlab/mmdetection#11332]
In the [GDINO-T config file](https://github.com/open-mmlab/mmdetection/blob/dev-3.x/configs/grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_cap4m.py) , it seems only use coco dataset as pretrain data, but README says its pretrain data is OGC.

![image](https://github.com/open-mmlab/mmdetection/assets/39088437/4d917ad9-6555-4adb-b066-4441b21a1302)

**Comment by hhaAndroid** [comment]
@jiangtann This is because this configuration does not currently support pretraining. If you want to train, you can consider using the configuration of mm-grounding-dino.

**Comment by hhaAndroid** [comment]
@jiangtann The main reason for not supporting pretraining is that cap4m is not open-sourced.
