### ISSUE TITLE
When do I need to change fallback_on_stride in deformable conv?

### ISSUE THREAD

**Issue by HeathHose** [open-mmlab/mmdetection#1134]
``fallback_on_stride`` is used as follows:
``if not self.with_dcn or fallback_on_stride:``
But ``fallback_on_stride`` in config is always ``False``
So,``fallback_on_stride`` means?

**Comment by hellock** [comment]
`fallback_on_stride` means fallback to the normal convolution if stride > 1.

**Comment by djangogo** [comment]
Why we will fallback to the normal convolution if stride > 1?

**Comment by hellock** [comment]
@djangogo This is just an option and turned off by default.
