### ISSUE TITLE
A confusion about mm_grounding_dino configuration file

### ISSUE THREAD

**Issue by jiangtann** [open-mmlab/mmdetection#11351]
In the mm_grounding_dino [refcoco finetuning config](https://github.com/open-mmlab/mmdetection/blob/dev-3.x/configs/mm_grounding_dino/refcoco/grounding_dino_swin-t_finetune_8xb4_5e_refcoco.py#L149) file, I find an item:

~~~py
'absolute_pos_embed': dict(decay_mult=0.)
~~~

But I don't find the model parameters related to the item. I don't know if the item is working. Can I delete it in the config file?

**Comment by hhaAndroid** [comment]
@jiangtann You can disregard it, as it was copied from Dino.
