### ISSUE TITLE
AttributeError: 'PolygonMasks' object has no attribute 'shape'

### ISSUE THREAD

**Issue by mengdongwei** [open-mmlab/mmdetection#11356]
when i try to train rtmdet-ins on  customized datasets with coco-format, i got the error 
 
<img width="917" alt="截屏2024-01-10 19 39 00" src="https://github.com/open-mmlab/mmdetection/assets/15925398/6ee03bd1-6217-47b4-99b5-064d175e2293">

``
Traceback (most recent call last):
  File tools/train.py:116 in <module>
    main()
  File tools/train.py:112 in main
    runner.train()
  File /usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py:1777 in train
    model = self.train_loop.run()  # type: ignore
  File /usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py:96 in run
    self.run_epoch()
  File /usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py:112 in run_epoch
    self.run_iter(idx, data_batch)
  File /usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py:128 in run_iter
    outputs = self.runner.model.train_step(
  File /usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py:114 in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File /usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py:346 in _run_forward
    results = self(**data, mode=mode)
  File /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1051 in _call_impl
    return forward_call(*input, **kwargs)
  File /home/mengdongwei/codes/mmdetection/mmdet/models/detectors/base.py:92 in forward
    return self.loss(inputs, data_samples)
  File /home/mengdongwei/codes/mmdetection/mmdet/models/detectors/single_stage.py:78 in loss
    losses = self.bbox_head.loss(x, batch_data_samples)
  File /home/mengdongwei/codes/mmdetection/mmdet/models/dense_heads/base_dense_head.py:123 in loss
    losses = self.loss_by_feat(*loss_inputs)
  File /home/mengdongwei/codes/mmdetection/mmdet/models/dense_heads/rtmdet_head.py:260 in loss_by_feat
    cls_reg_targets = self.get_targets(
  File /home/mengdongwei/codes/mmdetection/mmdet/models/dense_heads/rtmdet_head.py:356 in get_targets
    all_assign_metrics, sampling_results_list) = multi_apply(
  File /home/mengdongwei/codes/mmdetection/mmdet/models/utils/misc.py:219 in multi_apply
    return tuple(map(list, zip(*map_results)))
  File /home/mengdongwei/codes/mmdetection/mmdet/models/dense_heads/rtmdet_head.py:440 in _get_targets_single
    assign_result = self.assigner.assign(pred_instances, gt_instances,
  File /home/mengdongwei/codes/mmdetection/mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py:142 in assign
    gt_center = center_of_mass(gt_instances.masks, eps=EPS)
  File /home/mengdongwei/codes/mmdetection/mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py:29 in center_of_mass
    n, h, w = masks.shape
AttributeError: 'PolygonMasks' object has no attribute 'shape'

> /home/mengdongwei/codes/mmdetection/mmdet/models/task_modules/assigners/dynamic_soft_label_assigner.py(29)center_of_mass()
     27         Tensor: The masks center of mass. Has shape (num_masks, 2).
     28     """
---> 29     n, h, w = masks.shape
     30     grid_h = torch.arange(h, device=masks.device)[:, None]
     31     grid_w = torch.arange(w, device=masks.device)
``

**Comment by mengdongwei** [comment]
Here is my environment
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.8.0 (default, Dec  9 2021, 17:53:27) [GCC 8.4.0]
    CUDA available: True
    numpy_random_seed: 486853199
    GPU 0,1,2,3: NVIDIA GeForce RTX 3090
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.1, V11.1.105
    GCC: x86_64-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.9.0+cu111
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,
code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_
QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-
unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fd
iagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON
, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

    TorchVision: 0.10.0+cu111
    OpenCV: 4.5.4
    MMEngine: 0.10.2

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 486853199
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

**Comment by mengdongwei** [comment]
sorry, i found the problem, its a misunderstand

**Comment by smoothumut** [comment]
Hi @mengdongwei  so what was the problem? and how did you solve it ??
Thanks in advance

**Comment by fenglingbai** [comment]
Hi @mengdongwei and @smoothumut , I get the same error: 'PolygonMasks' object has no attribute 'shape' in dynamic_soft_label_assigner.py. Now I can use the Mask R - CNN run successfully, but complains in rtmdet - ins. Is there currently a detailed solution to this problem?
Thanks in advance !

**Comment by to505to505** [comment]
Hi! @smoothumut @mengdongwei @fenglingbai can you please provide some details on how you solved it? Also encountered it, would be really grateful!
