### ISSUE TITLE
Dist_train.sh Invalid Syntax error

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#1135]
Hi, 
I want to do multiple GPU training. For this, I use dist_train.sh. However, I get an Invalid syntax error in this file. The error is below. How can I solve this problem? Thanks...

![Ekran Görüntüsü - 2019-08-06 22-20-48](https://user-images.githubusercontent.com/34706028/62570571-7b055e80-b898-11e9-85db-e9a3ef0be48c.png)

**Comment by hellock** [comment]
Please read the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#test-a-dataset).
