### ISSUE TITLE
How can I get every class's map50 instead of map!

### ISSUE THREAD

**Issue by 1Iris** [open-mmlab/mmdetection#11358]
I have trained a model.my datasets is DIOR(tend to cocodatasets),but the output file scalars.json only have the map of every class,no map50,how can I get the every class's map50 instead of map?Should I train the model again?

**Comment by 1Iris** [comment]
solution:run test instrution:
**!python tools/test.py ./config/xx.py ./work_dirs/.../latest.pth --out ./result/result.pkl --show**
"--show "

**Comment by LINTAO5835** [comment]
> I have trained a model.my datasets is DIOR(tend to cocodatasets),but the output file scalars.json only have the map of every class,no map50,how can I get the every class's map50 instead of map?Should I train the model again?

How do I Compute Map50 in a test set?The following command does not work when I use it

python tools/test.py configs/faster_rcnn_r50_fpn_1x.py work_dirs/epoch_100.pth --out ./result/result_100.pkl --eval bbox --show

I would like to get the following effect in the test set, who can help me?
![Snipaste_2024-01-17_14-29-17](https://github.com/open-mmlab/mmdetection/assets/111735874/8013d896-1a2c-4547-9310-23e430d44615)
