### ISSUE TITLE
请问checkpoint中存储的dataset_meta是从哪里取的?

### ISSUE THREAD

**Issue by liuky74** [open-mmlab/mmdetection#11364]
我在使用demo/image_demo.py测试时发现图片上的类名为COCO的80类, 和我定义的类名不同

调试后发现这个类名是从checkpoint模型文件中的dataset_meta["classes"]中获取的, 而我在训练时使用的CoCoDataset是自定义的, 其成员变量中的METAINFO["classes"]已经经过修改, 但是保存的checkpoint中的dataset_meta["classes"]却和我修改的不同, 我有尝试过跟踪该值来自于哪, 但是mmdetection的多层封装过于复杂, 我用vscode甚至无法跳转到函数内...

请问我要修改什么地方才能避免checkpoint中保存错误的类名?

**Comment by hhaAndroid** [comment]
@liuky74 是的，mmengine 的封装逻辑是比较深，要查到这个逻辑很不容易。实际上我也没有去查过。这个可能要去 mmengine 里面提 issue 问下

**Comment by liuky74** [comment]
@hhaAndroid 好的, 非常感谢, 我去那边问问

**Comment by fengjk12138** [comment]
你有没有在val_dataloader中设置metainfo=xxxx
```python
val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        metainfo=metainfo,
        ann_file=xxxxx,
        data_prefix=xxxxx,
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args))
```

**Comment by liuky74** [comment]
已经定位到问题了, 是因为我在COCODataset中的init下对METAINFO进行定义的, 此时metainfo对象已经在其父类中被定义了, 所以失效了
