### ISSUE TITLE
在mmdet3中取消了core文件，官方文档中关于2.x移植的还未更新，那在2.x中使用的导入该怎么修改呢

### ISSUE THREAD

**Issue by mxyyy1002** [open-mmlab/mmdetection#11372]
from mmdet.core import (anchor_inside_flags, build_assigner, build_sampler, DynamicAssigner)
像这些该怎么导入呢

**Comment by mxyyy1002** [comment]
已经解决了，

**Comment by mxyyy1002** [comment]
已经解决了，
from ..task_modules.prior_generators import anchor_inside_flags
from ..task_modules.builder import build_assigner, build_sampler
from ..task_modules.assigners import DynamicSoftLabelAssigner
from mmdet.models.utils import images_to_levels, multi_apply, select_single_mlvl

**Comment by 127727** [comment]
from mmdet.core import encode_mask_results怎么导入呢

**Comment by RudyChanning** [comment]
from mmdet.core import bbox2result 如何修改呢
