### ISSUE TITLE
Load datasets from huggingface hub

### ISSUE THREAD

**Issue by ryan-minato** [open-mmlab/mmdetection#11378]
Add a loader to the `mmdet.datasets` module to download and load datasets from the huggingface hub.

**Motivation**
In our use case, this will help leverage datasets to manage dataset caching, which is faster than downloading from the original server. 
It will also help in achieving streaming (e.g., using the WebDatasets module in [datasets](https://huggingface.co/docs/hub/datasets-webdataset#webdataset)), which is crucial for large datasets like ImageNet.

**Related resources**
https://huggingface.co/docs/datasets/object_detection#object-detection

**Additional context**
I am willing to create a PR to implement this feature, although it may take some time.

**Comment by minato-ellie** [comment]
I have created a PR to implement this feature. It is here #11415 .
