### ISSUE TITLE
when iter times is too much(more than 46550 times),training process hangs

### ISSUE THREAD

**Issue by GYxiaOH** [open-mmlab/mmdetection#1137]
I found the problem on all my computer with different gpu,xp,v100 and so on . I try cuda 9.0 10.0 and 10.1, this problem always appear.and  in my case, experiments cannot run continue after 46550 iteration without any error (not random hang like others),i only can kill  Processes of mmdetection and restart again. anyone meet same question?

**Comment by hellock** [comment]
Could you use the `Error report` issue template?
