### ISSUE TITLE
关于MM GroundingDino在coco上微调的方式

### ISSUE THREAD

**Issue by jiangtann** [open-mmlab/mmdetection#11376]
1.如果采用闭集微调，为什么文本端将无法修改描述呢？在inference时，我不能用在coco上微调好的ckpt，使用[用法说明](https://github.com/open-mmlab/mmdetection/blob/main/configs/mm_grounding_dino/usage_zh-CN.md#%E6%8E%A8%E7%90%86)中提到的四种方式去inference吗？

2.开集继续预训练微调这种方式中，提到采样20个负类，减轻模型幻觉。那么如果此时用coco上全部的类别当做文本端的输入，而不是仅仅采样20个负类，是不是效果会更好呢？

3.[这里](https://github.com/open-mmlab/mmdetection/tree/main/configs/mm_grounding_dino#coco)提到不推荐使用开集继续预训练微调这种方式，但如果我希望同时去finetune coco和refcoco，以进一步提升模型在refcoco上的性能，是不是只能采用开集继续预训练微调（将refcoco和coco都做成ODVGDataset）呢？

**Comment by jiangtann** [comment]
coco如果在开集继续预训练微调中，采样所有的负类，然后作为文本端的输入，这样和coco的闭集微调还存在什么区别呢？

**Comment by jiangtann** [comment]
@hhaAndroid

**Comment by cloud6500** [comment]
> coco如果在开集继续预训练微调中，采样所有的负类，然后作为文本端的输入，这样和coco的闭集微调还存在什么区别呢？

您好，我最近在用自己的数据集微调mm-detection,想问一下你实现了开集继续与训练微调了吗？是否需要把coco格式的数据标签都转成odvg格式的呢？
