### ISSUE TITLE
MM GroundingDino数据集的预训练格式

### ISSUE THREAD

**Issue by jiangtann** [open-mmlab/mmdetection#11388]
1.目前finetune [refcoco](https://github.com/open-mmlab/mmdetection/blob/main/configs/mm_grounding_dino/refcoco/grounding_dino_swin-t_finetune_8xb4_5e_refcoco.py)时，处理好的finetune_refcoco_train_vg.json文件中，每一行都只有一个caption。由于在refcoco中，一张图像中有三个左右的object(bbox)，一个object对应三个左右的reference(caption)。因此，需要7-8个sample才能训完一张图像的所有数据。

参考[Open-Groundingdino中的dataset](https://github.com/longzw1997/Open-GroundingDino/blob/main/datasets/odvg.py#L109)代码，训refcoco的一种方法是把一张图片中的所有caption拼在一起（把每一个caption当做object的phrase），这样，就可以为每个bbox设置一个label。如果一张图片有8条不重复的caption，那么每个bbox对应的label就是0-7，这样就可以一次训多条reference，从而达到一次训练一张图片里的所有数据的目的。

而目前MM GroundingDino训练refcoco的setting中，由于每个sample中只会有一个caption/bbox，所以每个bbox对应的label必然是0，也就是一次只训一条reference。想问下这样设计（一次只训一个caption/bbox）的原因或优势是什么。

&nbsp;

2.refcoco的finetune实验证明一次只训一个bbox/caption也能达到比较好的效果。那我在finetune coco时，我能否每次也只训练一张图片里的一个bbox或一个类呢？
例如如果一次只训一个类，那么instances_train2017_od.json的变化如下：
<img width="1336" alt="image" src="https://github.com/open-mmlab/mmdetection/assets/39088437/51a573fd-8815-47ef-8801-53d550b85544">

**Comment by hhaAndroid** [comment]
1 refcoco 是可以拼起来一起训练的，但是有可能会超过 256 token 的限制，为了通用性和统一，我们没有进行合并。
2 open grounding 训练的时候并不是采用 phrase grounding 训练方式，而是类似 rec，这个和我们做法也是不一样的。我们是严格统一了所有数据的范式
3 而且 flickr30k 和 gqa 数据集在原始处理时候就已经拼接了，但是也存在一张图片多个 instance 情况。

按照目前的做法，refcoco 有部分数据确实可以合并，但是合并时候也要注意一些特殊情况

**Comment by jiangtann** [comment]
@hhaAndroid

**Comment by hhaAndroid** [comment]
按类别拆分 coco 是啥意思？如果你改成并行，那训练效果就更低了

**Comment by jiangtann** [comment]
@hhaAndroid 正常的coco数据中，jsonl文件的每一行都是一个训练sample，里面会有多个bbox，这些bbox会有多个类别。现在我需要将groundingdino和其他模型缝合起来一起训练，由于其他模型的输入限制，一个sample中只能有一个类别。所以就想按类别拆分coco，就像下图这样：

<img width="1336" alt="image" src="https://github.com/open-mmlab/mmdetection/assets/39088437/51a573fd-8815-47ef-8801-53d550b85544">

就想问下，如果这样将一个训练sample按类别拆成多个，训练效率肯定是更低的，那么这样会影响纯GroundingDino的最终的训练性能，在coco上的mAP会变低吗？
