### ISSUE TITLE
I get the error which is KeyError: '0' when I run the test.py

### ISSUE THREAD

**Issue by YinghaoZheng** [open-mmlab/mmdetection#1140]
# python3 tools/test.py configs/cascade_mask_rcnn_r101_fpn_1x.py work_dirs/cascade_mask_rcnn_r101_fpn_1x/epoch_1.pth  --out=eval/result_cascade_mask_rcnn_r101_fpn_1x.pkl --eval bbox
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 281/281, 4.5 task/s, elapsed: 62s, ETA:     0s
writing results to eval/result_cascade_mask_rcnn_r101_fpn_1x.pkl
Starting evaluate bbox
Traceback (most recent call last):
  File "tools/test.py", line 224, in <module>
    main()
  File "tools/test.py", line 201, in main
    result_files = results2json(dataset, outputs, args.out)
  File "/data/ZYH/mmdetect_8_7/mmdet/core/evaluation/coco_utils.py", line 165, in results2json
    json_results = segm2json(dataset, results)
  File "/data/ZYH/mmdetect_8_7/mmdet/core/evaluation/coco_utils.py", line 149, in segm2json
    data['score'] = float(mask_score[i])
KeyError: 0

i can't get the AP and AR,so what is wrong?

**Comment by hellock** [comment]
Please use the `Error report` issue template. If possible, you may also provide the checkpoint and test set.
