### ISSUE TITLE
MM Grounding dino读取数据有问题

### ISSUE THREAD

**Issue by zkyseu** [open-mmlab/mmdetection#11424]
您好，感谢您精彩的工作，我在训练object365时候遇到一个问题就说，我发现
```
gt_labels = [
    data_samples.gt_instances.labels
    for data_samples in batch_data_samples
]
```
中，有一个空[]，例如batchsize=2，一个有标签，一个没有标签。这个是什么原因呢

**Comment by hhaAndroid** [comment]
咦，难道是有特殊情况没有考虑吗？麻烦你在 debug 看看

**Comment by zkyseu** [comment]
@hhaAndroid 确认的，我这边一直显示有空列表，也就是没有标签，这样有个batch全是负样本，没有正样本了。

**Comment by hhaAndroid** [comment]
那是不是数据处理有问题呀，可以看下为啥全是负样本

**Comment by fx-hit** [comment]
我在跑DINO目标检测 https://github.com/open-mmlab/mmdetection/tree/main/configs/dino 的时候也遇到类似的问题：
训练集每个数据都是有标注的边界框，没有空的标注，但是读取数据拿到gt_instances就看到有个别数据label和boxes变成空了，debug好久也没找到在哪里发生的问题
