### ISSUE TITLE
mmdetection model convert to caffe-style-model

### ISSUE THREAD

**Issue by linquanxu** [open-mmlab/mmdetection#1143]
hi, I have used cascade_mask_rcnn_x101_64x4d_fpn_1x.py to training and got a mmdetection model, I want to convert it to Caffe style model, how to fix it? thanks.

**Comment by kaikaizhu** [comment]
+1
Have you sloved this problem?

**Comment by ZwwWayne** [comment]
will be solved in mmdeploy.
