### ISSUE TITLE
Why get 'WARNING - No pre-trained weights for SwinTransformer'?

### ISSUE THREAD

**Issue by Nina0109** [open-mmlab/mmdetection#11434]
I get this warning while finetuning grounding dino. Does it mean the pretrain-weight for swin-transformer is not loaded? I'm training from scratch? Why the weight is not loaded?

len cat_ids: 2081
loading annotations into memory...
Done (t=4.65s)
creating index...
index created!
len cat_ids: 2081
01/26 18:20:03 - mmengine - **WARNING - No pre-trained weights for SwinTransformer, training start from scratch**
Did not find last_checkpoint to be resumed.Did not find last_checkpoint to be resumed.

Did not find last_checkpoint to be resumed.Did not find last_checkpoint to be resumed.

Did not find last_checkpoint to be resumed.
Did not find last_checkpoint to be resumed.
Did not find last_checkpoint to be resumed.
Did not find last_checkpoint to be resumed.
01/26 18:20:03 - mmengine - INFO - Auto resumed from the latest checkpoint None.
01/26 18:20:03 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
01/26 18:20:03 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
01/26 18:20:03 - mmengine - INFO - Checkpoints will be saved to /mnt/bn/jnyang-yarnnas-01/code/mmdetection/exp_out_01.
/usr/local/lib/python3.9/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

**Comment by KarimElbarbary99** [comment]
Hello,

did you find a sloution to this issue? I have it the same and would appreciate your help. Thanks!
