### ISSUE TITLE
复现精度无法对齐

### ISSUE THREAD

**Issue by adii-t** [open-mmlab/mmdetection#11445]
我的环境是torch==1.9.0+cu102，torchvision==0.10.0+cu102,opencv-python==4.7.0.68，mmcv==2.1.0，mmdet==3.3.0，mmenigne==0.7.3，
我执行以下命令：bash ./tools/dist_train.sh configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py 4，用4张1080Ti训练，理论上应该得到的结果是37.4，但是我几次得到的结果都是36.4，差了一个点，并且在我使用双卡训练的时候精度还会下降到34.7左右，始终无法对齐精度

**Comment by hhaAndroid** [comment]
如果用 4 卡，你学习率修改了吗？我们是8卡跑的，精度是正常的

**Comment by adii-t** [comment]
> 如果用 4 卡，你学习率修改了吗？我们是8卡跑的，精度是正常的

我没有修改过学习率，想请教一下这个应该改成多少合适呢？感谢！！！

**Comment by hhaAndroid** [comment]
就对应线性缩放就行

**Comment by adii-t** [comment]
> 就对应线性缩放就行

我这就去试一下！！感谢指导！！
