### ISSUE TITLE
RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by erictan23** [open-mmlab/mmdetection#11454]
I am trying to run mmdetecting using grounding-dino weights. I managed to run the inference using CPU but could not manage to get the GPU work. I am currently running on local machine.

![image](https://github.com/open-mmlab/mmdetection/assets/74151994/0d1322d7-72bf-432d-b44b-052535caa4de)
This is my versions.
![image](https://github.com/open-mmlab/mmdetection/assets/74151994/93509098-67ee-4e25-a649-6f10420b2d42)

can anyone help me in getting my gpu to run this?

**Comment by hhaAndroid** [comment]
https://github.com/open-mmlab/mmdetection/issues/10841

**Comment by erictan23** [comment]
hi @hhaAndroid , I dont understand on the compilation of CPU mode. Could you send me over a guide for the GPU mode compilation?

I installed mmcv using the MIM package which was recommended in the guide from mmdetection's github repository.
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0"

Is this particular method on a cpu mode?

**Comment by SampWEI** [comment]
Hi, I found same problem "RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found.
". if you have any solutions?

**Comment by SampWEI** [comment]
> hi @hhaAndroid , I dont understand on the compilation of CPU mode. Could you send me over a guide for the GPU mode compilation?
> 
> I installed mmcv using the MIM package which was recommended in the guide from mmdetection's github repository. pip install -U openmim mim install mmengine mim install "mmcv>=2.0.0"
> 
> Is this particular method on a cpu mode?

should consider "Build MMCV from source". 
use command "mim uninstall mmcv" and compiled mmcv as https://mmcv.readthedocs.io/en/latest/get_started/build.html#build-mmcv-from-source  said
just solved same problem in this way.
hope it will help u

**Comment by snirlugassy-imagry** [comment]
Make sure to set MMCV_WITH_OPS=1

**Comment by marz869** [comment]
That is crazy, I tried everything but error is still there. both mmcv-full and mmcv are built for cuda124, and they are built for GPU(I check the source code and compare it with other versions). Still have the error. should be something else.

Cuda Version: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131

pip install --no-cache-dir torch==2.5.1+cu124 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124


mim install --no-cache-dir  mmcv==1.7.1 
mim install --no-cache-dir mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu124/torch2.5.1/index.html


OR 
git clone --depth 1 --branch v1.7.1 https://github.com/open-mmlab/mmcv.git

cd mmcv 
pip install -r requirements/optional.txt
pip install -e . -v
 
No way !!!

**Comment by Supdon** [comment]
> That is crazy, I tried everything but error is still there. both mmcv-full and mmcv are built for cuda124, and they are built for GPU(I check the source code and compare it with other versions). Still have the error. should be something else.
> 
> Cuda Version: nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2024 NVIDIA Corporation Built on Thu_Mar_28_02:18:24_PDT_2024 Cuda compilation tools, release 12.4, V12.4.131
> 
> pip install --no-cache-dir torch==2.5.1+cu124 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124
> 
> mim install --no-cache-dir mmcv==1.7.1 mim install --no-cache-dir mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu124/torch2.5.1/index.html
> 
> OR git clone --depth 1 --branch v1.7.1 https://github.com/open-mmlab/mmcv.git
> 
> cd mmcv pip install -r requirements/optional.txt pip install -e . -v
> 
> No way !!!



I have encountered the same problem. Have you solved it yet

**Comment by AustrianOakvn** [comment]
I encountered the same problem. I compiled from source with these 2 additional options that force mmcv to compile with GPU and it resolved, hope it could help:
`TORCH_CUDA_ARCH_LIST="device-capability" MMCV_WITH_OPS=1 python setup.py install`
Replace the `device-capability` with your GPU compute capability, eg: "8.6". You can search online to find out.
