### ISSUE TITLE
Why fp16 doesn't be faster

### ISSUE THREAD

**Issue by Lucy0601** [open-mmlab/mmdetection#1146]
When using mixed precision, the average iter time is 1.2753 s/iter, the memory is 3164;
while using fp32, the average iter time is 1.0303 s/iter, the memort is 3930
Is it the normal result?
Can you release the time and memory usage of fp16?

**Comment by hellock** [comment]
Please refer to our [tech report](https://arxiv.org/abs/1906.07155).

**Comment by Lucy0601** [comment]
Thank you~

**Comment by rydenisbak** [comment]
@Lucy0601 try to comment this line. It helps me boost perfomance
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/fp16/hooks.py#L100
