### ISSUE TITLE
RuntimeError: The size of tensor a (47) must match the size of tensor b (48) at non-singleton dimension 2

### ISSUE THREAD

**Issue by tianlanli** [open-mmlab/mmdetection#1147]
my dataset get_item is:
`    def __getitem__(self, idx):

        # ---------
        #  Image
        # ---------
        gt_labels = []
        gt_bboxes = []
        img_path = self.img_files[idx % len(self.img_files)].rstrip()
        ori_img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))
        img = mmcv.imread(osp.join(img_path))
        self.img_transform = ImageTransform(
            size_divisor=self.size_divisor, **self.img_norm_cfg)
        # apply transforms
        flip = True if np.random.rand() < self.flip_ratio else False
        # randomly sample a scale
        img_scale = random_scale(self.img_scales, self.multiscale_mode)

        img, img_shape, pad_shape, scale_factor = self.img_transform(
            img, img_scale, flip, keep_ratio=self.resize_keep_ratio)
        _ , h , w = ori_img.shape
        ori_shape = (h,w, 3)
        img_meta = dict(
            ori_shape=ori_shape,
            img_shape=img_shape,
            pad_shape=pad_shape,
            scale_factor=scale_factor,
            flip=flip)
        # ---------
        #  Label
        # ---------
        label_path = self.label_files[idx % len(self.img_files)].rstrip()
        if os.path.exists(label_path):
            boxes = np.loadtxt(label_path).reshape(-1, 5)
            gt_labels = boxes[:, 0]
            gt_bboxes = boxes[:,1:]
        if len(gt_labels) == 0 and self.skip_img_without_anno:
            print("no annotationis img is ",img_path)
            return None
        gt_bboxes = self.bbox_transform(gt_bboxes, img_shape, scale_factor,
            flip)
        imgs = to_tensor(img)
        data = dict(
            img=DC(to_tensor(img), stack=True),
            img_meta=DC(img_meta, cpu_only=True),
            gt_bboxes=DC(to_tensor(gt_bboxes)),
            gt_labels = DC(to_tensor(gt_labels))
            )
        print("the img size ",imgs.size())
        return data`

the img size  torch.Size([3, 750, 1333]) ,the batch_size is 10
 I have printed the laterals .size in fpn.py:

> /mmdetection/mmdet/models/necks/fpn.py(114)forward()
    113             laterals[i - 1] += F.interpolate(
--> 114                 laterals[i], scale_factor=2, mode='nearest')
    115 

ipdb> p laterals[0].size(),laterals[1].size()                                                                                                                                    
(torch.Size([2, 256, 188, 334]), torch.Size([2, 256, 94, 167]))
ipdb> p laterals[2].size(),laterals[3].size()                                                                                                                                    
(torch.Size([2, 256, 47, 84]), torch.Size([2, 256, 24, 42]))

the error happens in fpn.py:
`                                                                   
RuntimeError: The size of tensor a (47) must match the size of tensor b (48) at non-singleton dimension 2`

why ? I use the htc_without_semantic_r50_fpn_1x.py

**Comment by tianlanli** [comment]
my config have error

**Comment by IceSuger** [comment]
> my config have error

Hello~ same problem here. How did you fix this? Thanks for any help~!

**Comment by tianlanli** [comment]
Hi~ because I use three GPUS ,then I use two or four GPUS ,then ok

**Comment by IceSuger** [comment]
> Hi~ because I use three GPUS ,then I use two or four GPUS ,then ok

Thanks!
I figured out that I didn't properly set the padding when loading data, which caused this. Now it's ok.
