### ISSUE TITLE
mm_grounding_dino在Object365数据集上的表现

### ISSUE THREAD

**Issue by JeremyLin886** [open-mmlab/mmdetection#11492]
请问有没有在Object365数据集上的表现？用Object365测试集做的评测

**Comment by hhaAndroid** [comment]
@JeremyLin886 因为 o36比较大，我们没有对这个数据进行评测，主要关注的是 zero-shot 能力

**Comment by JeremyLin886** [comment]
> @JeremyLin886 因为 o36比较大，我们没有对这个数据进行评测，主要关注的是 zero-shot 能力

好的，感谢
