### ISSUE TITLE
object detection without mask annotation

### ISSUE THREAD

**Issue by tianlanli** [open-mmlab/mmdetection#1149]
I  want use maskrcnn or HTC to train my own dataset for object detection . my dataset ‘s  label
only have classes and boudingboxes  . Can I use maskrcnn or htc to train ? I have tried , but  I meet
the error 
`  File "/mmdetection/mmdet/core/mask/mask_target.py", line 10, in mask_target pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable`
I don't have mask annotation

**Comment by hellock** [comment]
No you cannot.

**Comment by tianlanli** [comment]
ok ， thank you
