### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by evancasey** [open-mmlab/mmdetection#115]
Hi there! Can you clarify if this project is licensed under Apache 2.0 or GPLv3? It seems that the LICENSE.md is Apache but there is a line in the `setup.py` indicating that is GPL.

**Comment by hellock** [comment]
It is licensed under Apache 2.0, we will soon update the license indicator in `setup.py`. Thanks!

**Comment by evancasey** [comment]
Great thanks for clarifying! 🙏
