### ISSUE TITLE
Grounding-DINO 在使用某些text_prompts时会出现检测框的phrases全乱了的情况

### ISSUE THREAD

**Issue by lanhas** [open-mmlab/mmdetection#11501]
模型在使用某些text_prompts，例如“the manhole cover . household trash . flame . construction waste . bus . sofa . mobile phone . rubble heap . cigarette . hut . fire hydrant . person . road . lawn . garbage bin . car . dump truck . camera . bench . electric wire . outdoor advertisement . advertisement . fence . street light . sidewalk . chair . truck . building . sign . traffic light”，出现了phrases全乱了的现象。bbox正确的框住了目标物，但是给的类别是完全凌乱的，还出现了‘unobject’这个类别。

是否因为某些词没有正确的编码或者在解码的过程中出现了某些问题。

**Comment by hhaAndroid** [comment]
可能是程序有点Bug.你可以先试着减少 prompt 输入，然后不要让他出现 unobject 类别？我猜测是当出现 unobject 类别时候推理代码的类别没有对上

**Comment by lanhas** [comment]
我记得unobject类别好像是在token数量大于256的时候才会出现，但是这个明显不可能大于256，为什么还会出现呢？
我之前用了一个79个类别的prompts，它可以正确进行微调和推理。但是当我改动了一部分词（还是79个类别）后，微调可以正确进行，但是推理出现了phrases混乱的问题。
我试着减少了prompts的数量，在某些时候可以正确推理，但是某些时候（上面的那个prompts）出现了问题。

**Comment by hhaAndroid** [comment]
可以先查一下为啥会出现 unobject，我之前没有跑出这个类别

**Comment by lanhas** [comment]
没有unobject的时候也会出现给的label和框对不上的问题。
这个在configs中的grounding_dino和mm_grounding_dino都会出现，在B和L中也都会出现；
经验证，这个问题确实和类别数量无关，我在随机注释一部分prompts进行predict的时候有时候结果正确有时候不正确；
我猜测是不是在某些prompts下pred_instances = self.bbox_head.predict(
                    **head_inputs_dict,
                    rescale=rescale,
                    batch_data_samples=batch_data_samples)[0]
生成的类别的索引出了问题，因为我在IDEA的GroundingDINO代码中使用相同的图片和prompts没有出现问题，他们没有映射到类别索引
由于我对您的代码理解还不透彻，找不出问题所在，大佬在有时间的时候可以帮我排查下问题吗
我可以把调试的图片和prompts留一下

**Comment by SoulProficiency** [comment]
> 可能是程序有点Bug.你可以先试着减少 prompt 输入，然后不要让他出现 unobject 类别？我猜测是当出现 unobject 类别时候推理代码的类别没有对上

我用grounding_dino_swin-b_pretrain_mixeddata.py这个配置文件在coco数据集上进行微调，指令如下：
`./tools/train.py configs/grounding_dino/grounding_dino_swin-b_pretrain_mixeddata.py --work-dir swinb_pre_work`
爆出如下错误：
```
02/28 06:10:58 - mmengine - WARNING - No pre-trained weights for SwinTransformer, training start from scratch
02/28 06:10:58 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
02/28 06:10:58 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
02/28 06:10:58 - mmengine - INFO - Checkpoints will be saved to /home/argo/wxj/mmdetection/swinb_pre_work.
Traceback (most recent call last):
  File "./tools/train.py", line 121, in <module>
    main()
  File "./tools/train.py", line 117, in main
    runner.train()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/argo/wxj/mmdetection/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/home/argo/wxj/mmdetection/mmdet/models/detectors/grounding_dino.py", line 421, in loss
    text_prompts = [
  File "/home/argo/wxj/mmdetection/mmdet/models/detectors/grounding_dino.py", line 422, in <listcomp>
    data_samples.text for data_samples in batch_data_samples
AttributeError: 'DetDataSample' object has no attribute 'text'
```
这个配置文件只能用来测试吗？如果用coco数据集微调的话，我还要修改coco数据集的格式吗？我看官方给的cat例子的数据集和coco数据集格式不一样呢

**Comment by lanhas** [comment]
> 可以先查一下为啥会出现 unobject，我之前没有跑出这个类别

找到问题的原因了，当prompts 里面出现部分重复的词，例如“truck”， “dump truck” ，或者"advertisement “， ”outdoor advertisement"这种的时候，推理就会出bug，类别和检测框就对不上了。

**Comment by narchitect** [comment]
@lanhas @hhaAndroid  hello, thank you for sharing this issue. I'm also exactly same with this problem. as the author mentioned, the bbox results looks fine but it maps wrong label even I saw "unobject" in the results too. 

when I debugged the code, I found that in prediction labels the predicted index range is more than the given text prompt so that label mapping becomes wrong at the visualizer instance.

but I guess the boxes accuracy is okay only label index are mixed because of wrong parsed texts or appearance of 'unojbect' label.

I'm not sure whether I can manage this by myself to modify it but seems to be a serious problem with text parsing component. 

maybe can you fix this issue or share a way to fix it by myself not modifying the given texts?

**Comment by auindoeee** [comment]
grip.py中的run_ner函数，类别和caption比对提取tokens_positive，如果前后类别有相同部分，比如caption是”container . door . plate . containernumber“，那么在提取containernumber的tokens时就会先匹配到container，导致最后的tokens_positive的个数会比实际类别多1个，出现一个unobject。不改代码的话，只要保证containernumber在container之前就好了
修改代码：
# for m in re.finditer(entity, caption.lower()):
pattern = r'\b' + re.escape(entity) + r'\b'
for m in re.finditer(pattern, caption.lower()):
    tokens_positive.append([[m.start(), m.end()]])
![image](https://github.com/user-attachments/assets/10870d22-1c61-4823-88b5-178949b2d3bd)

**Comment by auindoeee** [comment]
glip.py中的run_ner函数，类别和caption比对提取tokens_positive，如果前后类别有相同部分，比如caption是”container . door . plate . containernumber“，那么在提取containernumber的tokens时就会匹配到container，导致最后的tokens_positive错误，出现unobject。
修改代码：
# tokens_positive = []
    # for entity, label in zip(relevant_phrases, labels):
    #     try:
    #         # search all occurrences and mark them as different entities
    #         # TODO: Not Robust
    #          for m in re.finditer(entity, caption.lower()):
    #             tokens_positive.append([[m.start(), m.end()]])
    #     except Exception:
    #         print('noun entities:', noun_phrases)
    #         print('entity:', entity)
    #         print('caption:', caption.lower())

    phrase_labels = {phrase: phrase for phrase in relevant_phrases}

    all_possible_combinations = []
    for phrase in relevant_phrases:
        parts = phrase.split()
        all_possible_combinations.extend(
            [' '.join(parts[i:j + 1]) for i in range(len(parts)) for j in range(i, len(parts))])

    unique_combinations = list(set(all_possible_combinations))
    sorted_combinations = sorted(unique_combinations, key=len, reverse=True)
    tokens_positive = []

    pattern = r'\b(' + '|'.join(map(re.escape, sorted_combinations)) + r')\b'
    for m in re.finditer(pattern, caption.lower()):
        matched_entity = caption[m.start():m.end()]
        if matched_entity in phrase_labels:
            label = phrase_labels[matched_entity]
            tokens_positive.append([[m.start(), m.end()]])

**Comment by ztc20011103** [comment]
> glip.py中的run_ner函数，类别和caption比对提取tokens_positive，如果前后类别有相同部分，比如caption是”container . door . plate . containernumber“，那么在提取containernumber的tokens时就会匹配到container，导致最后的tokens_positive错误，出现unobject。 修改代码：
> 
> # tokens_positive = []
> ```
> # for entity, label in zip(relevant_phrases, labels):
> #     try:
> #         # search all occurrences and mark them as different entities
> #         # TODO: Not Robust
> #          for m in re.finditer(entity, caption.lower()):
> #             tokens_positive.append([[m.start(), m.end()]])
> #     except Exception:
> #         print('noun entities:', noun_phrases)
> #         print('entity:', entity)
> #         print('caption:', caption.lower())
> 
> phrase_labels = {phrase: phrase for phrase in relevant_phrases}
> 
> all_possible_combinations = []
> for phrase in relevant_phrases:
>     parts = phrase.split()
>     all_possible_combinations.extend(
>         [' '.join(parts[i:j + 1]) for i in range(len(parts)) for j in range(i, len(parts))])
> 
> unique_combinations = list(set(all_possible_combinations))
> sorted_combinations = sorted(unique_combinations, key=len, reverse=True)
> tokens_positive = []
> 
> pattern = r'\b(' + '|'.join(map(re.escape, sorted_combinations)) + r')\b'
> for m in re.finditer(pattern, caption.lower()):
>     matched_entity = caption[m.start():m.end()]
>     if matched_entity in phrase_labels:
>         label = phrase_labels[matched_entity]
>         tokens_positive.append([[m.start(), m.end()]])
> ```

然而没有用，mm grounding dino似乎也没有调用glip

**Comment by 0xyangl** [comment]
In mmdetection/demo/image_demo.py there's a parameter for GroundingDINO to customize entity names    
after adding -c parameter , this problem will be solved.
    
![image](https://github.com/user-attachments/assets/4863fad8-5801-4449-a224-c1ecceef1646)

this is the example code that works for me:

python demo/image_demo.py \
    data/BITVehicle/images/vehicle_0006506.jpg \
    configs/grounding_dino/grounding_dino_swin-t_finetune_8xb2_20e_yourFineTunecfg.py \
    --weights path_to_your.pth \
    --texts "Bus . Microbus . Minivan . Sedan . SUV . Truck ." \
    -c
