### ISSUE TITLE
训练模型时，显存不断增长，经过几千次迭代后，显存溢出

### ISSUE THREAD

**Issue by langli1999** [open-mmlab/mmdetection#11525]
**环境安装**
conda create -n mmdet python=3.8 -y
conda activate mmdet

conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=10.2 -c pytorch
# pip install torch==1.12.0+cu102 torchvision==0.13.0+cu102 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu102

pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0"

git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -v -e .

最终：
mmengine=0.10.3
mmcv=2.1.0
mmdetection=3.3.0

**模型配置**
faster-rcnn_r50_fpn_1x_mydataset
除了数据集替换为自己的数据集外，没有其他更改

**Comment by langli1999** [comment]
试了很多次，试了不同的模型，均有这样的问题。其中一次的报错信息如下，可以看到，模型已经正常训练了一段时间，而后报错显存溢出。
![屏幕截图 2024-03-07 222232](https://github.com/open-mmlab/mmdetection/assets/127654969/31f8a1c5-ee89-4913-a195-cfcbf3262f30)

**Comment by Morningstaripfy** [comment]
EMPTYCACHEHOOK maybe useful：https://mmengine.readthedocs.io/zh-cn/latest/tutorials/hook.html

**Comment by JinqingZhengTju** [comment]
> 试了很多次，试了不同的模型，均有这样的问题。其中一次的报错信息如下，可以看到，模型已经正常训练了一段时间，而后报错显存溢出。 ![屏幕截图 2024-03-07 222232](https://private-user-images.githubusercontent.com/127654969/310912369-31f8a1c5-ee89-4913-a195-cfcbf3262f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY3ODksIm5iZiI6MTcxNjI3NjQ4OSwicGF0aCI6Ii8xMjc2NTQ5NjkvMzEwOTEyMzY5LTMxZjhhMWM1LWVlODktNDkxMy1hMTk1LWNmY2JmMzI2MmYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNzI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmI5YTIzYTQ1YWVmZjk0NDhmYzM1ZjYzYzIyNzYyMmZmNmI5NzUyMWY5Nzc5ZDZhMzc1Y2I4ZDBkYjdhZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5MUmwBinqXYv8YcnVd-z61FE4uQNVKVmGnb_wTcoFHQ)

请问您找到出现这个问题的原因了吗？我也遇到了这个问题

**Comment by Morningstaripfy** [comment]
修改这个文件mmrotate: configs\_base_\default_runtime.py
custom_hooks = [dict(type='EmptyCacheHook', after_epoch=True, after_iter=True)]
参考：https://mmengine.readthedocs.io/zh-cn/latest/tutorials/hook.html#emptycachehook
如果跑的是自定义的模型，再检查下有没有内存泄漏。

**Comment by Morningstaripfy** [comment]
> > 试了很多次，试了不同的模型，均有这样的问题。其中一次的报错信息如下，可以看到，模型已经正常训练了一段时间，而后报错显存溢出。 ![屏幕截图 2024-03-07 222232](https://private-user-images.githubusercontent.com/127654969/310912369-31f8a1c5-ee89-4913-a195-cfcbf3262f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY3ODksIm5iZiI6MTcxNjI3NjQ4OSwicGF0aCI6Ii8xMjc2NTQ5NjkvMzEwOTEyMzY5LTMxZjhhMWM1LWVlODktNDkxMy1hMTk1LWNmY2JmMzI2MmYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNzI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmI5YTIzYTQ1YWVmZjk0NDhmYzM1ZjYzYzIyNzYyMmZmNmI5NzUyMWY5Nzc5ZDZhMzc1Y2I4ZDBkYjdhZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5MUmwBinqXYv8YcnVd-z61FE4uQNVKVmGnb_wTcoFHQ)
> 
> 请问您找到出现这个问题的原因了吗？我也遇到了这个问题

修改这个文件mmrotate: configs_base_\default_runtime.py
custom_hooks = [dict(type='EmptyCacheHook', after_epoch=True, after_iter=True)]
参考：https://mmengine.readthedocs.io/zh-cn/latest/tutorials/hook.html#emptycachehook
如果跑的是自定义的模型，再检查下有没有内存泄漏。

**Comment by JinqingZhengTju** [comment]
> > > 试了很多次，试了不同的模型，均有这样的问题。其中一次的报错信息如下，可以看到，模型已经正常训练了一段时间，而后报错显存溢出。 ![屏幕截图 2024-03-07 222232](https://private-user-images.githubusercontent.com/127654969/310912369-31f8a1c5-ee89-4913-a195-cfcbf3262f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY3ODksIm5iZiI6MTcxNjI3NjQ4OSwicGF0aCI6Ii8xMjc2NTQ5NjkvMzEwOTEyMzY5LTMxZjhhMWM1LWVlODktNDkxMy1hMTk1LWNmY2JmMzI2MmYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNzI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmI5YTIzYTQ1YWVmZjk0NDhmYzM1ZjYzYzIyNzYyMmZmNmI5NzUyMWY5Nzc5ZDZhMzc1Y2I4ZDBkYjdhZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5MUmwBinqXYv8YcnVd-z61FE4uQNVKVmGnb_wTcoFHQ)
> > 
> > 
> > 请问您找到出现这个问题的原因了吗？我也遇到了这个问题
> 
> 修改这个文件mmrotate: configs_base_\default_runtime.py custom_hooks = [dict(type='EmptyCacheHook', after_epoch=True, after_iter=True)] 参考：https://mmengine.readthedocs.io/zh-cn/latest/tutorials/hook.html#emptycachehook 如果跑的是自定义的模型，再检查下有没有内存泄漏。

好的，我试一下，感谢

**Comment by langli1999** [comment]
> > 试了很多次，试了不同的模型，均有这样的问题。其中一次的报错信息如下，可以看到，模型已经正常训练了一段时间，而后报错显存溢出。 ![屏幕截图 2024-03-07 222232](https://private-user-images.githubusercontent.com/127654969/310912369-31f8a1c5-ee89-4913-a195-cfcbf3262f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY3ODksIm5iZiI6MTcxNjI3NjQ4OSwicGF0aCI6Ii8xMjc2NTQ5NjkvMzEwOTEyMzY5LTMxZjhhMWM1LWVlODktNDkxMy1hMTk1LWNmY2JmMzI2MmYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNzI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmI5YTIzYTQ1YWVmZjk0NDhmYzM1ZjYzYzIyNzYyMmZmNmI5NzUyMWY5Nzc5ZDZhMzc1Y2I4ZDBkYjdhZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5MUmwBinqXYv8YcnVd-z61FE4uQNVKVmGnb_wTcoFHQ)
> 
> 请问您找到出现这个问题的原因了吗？我也遇到了这个问题

我找到出现这种问题的原因了，是因为数据集问题。我用的数据集是AI-TOD，其中存在许多密集的小目标，一张图中可能有数百上千个实例，从而导致在分配正负样本时显存溢出。可以通过修改max_iou_assigner.py文件中的gpu_assign_thr这个参数来解决，如下图。其默认值为-1，会全部在gpu上进行运算；我把它修改为200，当gt数量大于200时，会在cpu上计算iou，避免了一张图因为有过多的实例而爆显存。注意，gpu_assign_thr设置的越小，爆显存的风险就越小，但是相应的训练速度就会越慢。

![屏幕截图 2024-05-21 153535](https://github.com/open-mmlab/mmdetection/assets/127654969/738b3b6a-bd02-499a-a27f-8d2fc375d0b5)

这是我出现问题的原因，不知道你遇到的是不是这种情况。

**Comment by JinqingZhengTju** [comment]
> > > 试了很多次，试了不同的模型，均有这样的问题。其中一次的报错信息如下，可以看到，模型已经正常训练了一段时间，而后报错显存溢出。 ![屏幕截图 2024-03-07 222232](https://private-user-images.githubusercontent.com/127654969/310912369-31f8a1c5-ee89-4913-a195-cfcbf3262f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY3ODksIm5iZiI6MTcxNjI3NjQ4OSwicGF0aCI6Ii8xMjc2NTQ5NjkvMzEwOTEyMzY5LTMxZjhhMWM1LWVlODktNDkxMy1hMTk1LWNmY2JmMzI2MmYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNzI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmI5YTIzYTQ1YWVmZjk0NDhmYzM1ZjYzYzIyNzYyMmZmNmI5NzUyMWY5Nzc5ZDZhMzc1Y2I4ZDBkYjdhZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5MUmwBinqXYv8YcnVd-z61FE4uQNVKVmGnb_wTcoFHQ)
> > 
> > 
> > 请问您找到出现这个问题的原因了吗？我也遇到了这个问题
> 
> 我找到出现这种问题的原因了，是因为数据集问题。我用的数据集是AI-TOD，其中存在许多密集的小目标，一张图中可能有数百上千个实例，从而导致在分配正负样本时显存溢出。可以通过修改max_iou_assigner.py文件中的gpu_assign_thr这个参数来解决，如下图。其默认值为-1，会全部在gpu上进行运算；我把它修改为200，当gt数量大于200时，会在cpu上计算iou，避免了一张图因为有过多的实例而爆显存。注意，gpu_assign_thr设置的越小，爆显存的风险就越小，但是相应的训练速度就会越慢。
> 
> ![屏幕截图 2024-05-21 153535](https://private-user-images.githubusercontent.com/127654969/332334741-738b3b6a-bd02-499a-a27f-8d2fc375d0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODEwMzQsIm5iZiI6MTcxNjI4MDczNCwicGF0aCI6Ii8xMjc2NTQ5NjkvMzMyMzM0NzQxLTczOGIzYjZhLWJkMDItNDk5YS1hMjdmLThkMmZjMzc1ZDBiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwODM4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmUxMWVmN2JkOTIxMmU3NGY3ZWJmM2NmYzk2NmY1MDIzMjljOGM4NTVhNTc2Zjc0MjQyOWFiOWM1NTE1NjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cBMlzgSxxRNJ2NqqrwoMn-tWWQzN_21n2GPKmwns8gU)
> 
> 这是我出现问题的原因，不知道你遇到的是不是这种情况。

我跟您是同样的问题，样本中的目标量太大，导致得显存溢出，我修改下您说的max_iou_assigner.py文件中的gpu_assign_thr参数，试一下。非常感谢。

**Comment by zxt6174** [comment]
你好，我和你的问题是一样的，训练一段时间后才爆内存。你说的“目标量太大”，是指训练数据中的标注框太多吗？还是说，训练图形中的目标太多（与标注框无关）。期待回复。

**Comment by langli1999** [comment]
单张训练图像标注的目标太多。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月14日(周一) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [open-mmlab/mmdetection] 训练模型时，显存不断增长，经过几千次迭代后，显存溢出 (Issue #11525)




 
你好，我和你的问题是一样的，训练一段时间后才爆内存。你说的“目标量太大”，是指训练数据中的标注框太多吗？还是说，训练图形中的目标太多（与标注框无关）。期待回复。

**Comment by zxt6174** [comment]
好的，谢谢，那我的问题应该不在这里，我的单张图片标注并不多

**Comment by MrBroWinter** [comment]
检查一下自己的标签，是不是有很多目标，目标太多的话会有这种情况

**Comment by ffxxy** [comment]
> 好的，谢谢，那我的问题应该不在这里，我的单张图片标注并不多

你好，请问你的问题解决了吗？怎么解决的呢

**Comment by ffxxy** [comment]
> > > > 试了很多次，试了不同的模型，均有这样的问题。其中一次的报错信息如下，可以看到，模型已经正常训练了一段时间，而后报错显存溢出。![屏幕截图 2024-03-07 222232](https://private-user-images.githubusercontent.com/127654969/310912369-31f8a1c5-ee89-4913-a195-cfcbf3262f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzY3ODksIm5iZiI6MTcxNjI3NjQ4OSwicGF0aCI6Ii8xMjc2NTQ5NjkvMzEwOTEyMzY5LTMxZjhhMWM1LWVlODktNDkxMy1hMTk1LWNmY2JmMzI2MmYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNzI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmI5YTIzYTQ1YWVmZjk0NDhmYzM1ZjYzYzIyNzYyMmZmNmI5NzUyMWY5Nzc5ZDZhMzc1Y2I4ZDBkYjdhZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5MUmwBinqXYv8YcnVd-z61FE4uQNVKVmGnb_wTcoFHQ)
> > > 
> > > 
> > > 请问您找到出现这个问题的原因了吗？我也遇到了这个问题
> > 
> > 
> > 我找到出现这种问题的原因了，是因为数据集问题。我用的数据集是AI-TOD，其中存在许多密集的小目标，一张图中可能有数百上千个实例，从而导致在分配正负样本时显存溢出。可以通过修改max_iou_assigner.py文件中的gpu_assign_thr这个参数来解决，如下图。其默认值为-1，会全部在gpu上进行运算;我把它修改为200，当gt数量大于200时，会在cpu上计算iou，避免了一张图因为有过多的实例而爆显存。注意，gpu_assign_thr设置的越小，爆显存的风险就越小，但是相应的训练速度就会越慢。
> > ![屏幕截图 2024-05-21 153535](https://private-user-images.githubusercontent.com/127654969/332334741-738b3b6a-bd02-499a-a27f-8d2fc375d0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODEwMzQsIm5iZiI6MTcxNjI4MDczNCwicGF0aCI6Ii8xMjc2NTQ5NjkvMzMyMzM0NzQxLTczOGIzYjZhLWJkMDItNDk5YS1hMjdmLThkMmZjMzc1ZDBiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwODM4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmUxMWVmN2JkOTIxMmU3NGY3ZWJmM2NmYzk2NmY1MDIzMjljOGM4NTVhNTc2Zjc0MjQyOWFiOWM1NTE1NjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cBMlzgSxxRNJ2NqqrwoMn-tWWQzN_21n2GPKmwns8gU)
> > 这是我出现问题的原因，不知道你遇到的是不是这种情况。
> 
> 我跟您是同样的问题，样本中的目标量太大，导致得显存溢出，我修改下您说的max_iou_assigner.py文件中的gpu_assign_thr参数，试一下。非常感谢。

请问你解决了吗
