### ISSUE TITLE
No annotation file in MultiImageMixDataset?

### ISSUE THREAD

**Issue by Abhrant** [open-mmlab/mmdetection#11528]
I am trying to use yoloX for training and it uses MultiImageMixDataset . But it doesn't take ann_file . So how do I train it?

**Comment by Abhrant** [comment]
never mind, i figured it out

**Comment by liuhongyan123456** [comment]
请问您怎么解决的，我也想用这个进行mosaic数据增强，但是我没有掩膜信息，我做目标检测
