### ISSUE TITLE
How to print accuracy, recall, F1 value？P、R、F!

### ISSUE THREAD

**Issue by Idol-Dou2021** [open-mmlab/mmdetection#11538]
在tools/analysis_tools/confusion_matrix.py代码下面加上：
`	TP = np.diag(confusion_matrix)
    FP = np.sum(confusion_matrix, axis=0) - TP
    FN = np.sum(confusion_matrix, axis=1) - TP

    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    average_precision = np.mean(precision)
    average_recall = np.mean(recall)
    f1 = 2 * (average_precision * average_recall) / (average_precision + average_recall)
    print("AP ", average_precision)
    print("AR", average_recall)
    print("F1", f1)
`

**Comment by Idol-Dou2021** [comment]
[具体操作方法如下](https://blog.csdn.net/weixin_43722052/article/details/136598864)

**Comment by LazyShark2001** [comment]
@Idol-Dou2021 
you are the real hero.
