### ISSUE TITLE
关于mmground_dino的_base_文件

### ISSUE THREAD

**Issue by KDr888** [open-mmlab/mmdetection#11532]
我把configs的mmgrounddino和_base_整个文件夹都拿出来，运行image_demo然后报错_base_文件夹不存在，请问我应该在哪里修改这个_base_文件夹路径

**Comment by 15hmael** [comment]
cuda的问题你已经解决了是吗

**Comment by KDr888** [comment]
> cuda的问题你已经解决了是吗

什么问题

**Comment by 15hmael** [comment]
> > cuda的问题你已经解决了是吗
> 
> 什么问题

抱歉看错了，我这边torch能检测到cuda，但是用cuda运行就会显示 implementation for device cuda:0 not found.
