### ISSUE TITLE
data['category_id'] = self.cat_ids[label] IndexError: list index out of range

### ISSUE THREAD

**Issue by slantingsun** [open-mmlab/mmdetection#11555]
---
**This error is weird, sometimes it appears, sometimes it doesn't，Can anyone answer this question, thanks a million!**

I made changes in both the config file （num_class）and coco.py (METAINFO = {'classes':)，But the issue still arises

---
03/15 22:48:55 - mmengine - INFO - Epoch(val)  [3][50/69]    eta: 0:00:02  time: 0.1384  data_time: 0.1017  memory: 1481  
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 374, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/root/mmdetection/mmdet/evaluation/metrics/coco_metric.py", line 423, in compute_metrics
    result_files = self.results2json(preds, outfile_prefix)
  File "/root/mmdetection/mmdet/evaluation/metrics/coco_metric.py", line 243, in results2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

**Comment by slantingsun** [comment]
Looking up issue, there were the following responses
---
1. changed class names 'pedestrian','car' , .... with 0,1  (i thought its in coco.py)
2. change "classes = ('person', 'car')" to "classes = ('person', 'car',)
3. coco_metric.py line 419,         
    #self.cat_ids = None      
    self.cat_ids = self._coco_api.get_cat_ids()

**Comment by slantingsun** [comment]
i solve, the config file （categories name）should same with coco.py (METAINFO = {'classes':)

**Comment by 77h2l** [comment]
@slantingsun how did you fix the issue finally?
why did not the official repo developers fix the problem? @BIGWangYuDong

**Comment by slantingsun** [comment]
If you are using a custom dataset, ensure that the METAINFO = {'classes':} setting in the coco.py file matches the category names in the config file exactly.

**Comment by slantingsun** [comment]
@77h2l If you are using a custom dataset, ensure that the METAINFO = {'classes':} setting in the coco.py file matches the category names in the config file exactly.

**Comment by wu33learn** [comment]
> @77h2l If you are using a custom dataset, ensure that the METAINFO = {'classes':} setting in the coco.py file matches the category names in the config file exactly.

do you mean the coco.py in mmdet/dataset, and then add my category in the  ('person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
         'truck', 'boat', 'traffic light',..., 'toothbrush', **my category)**
![image](https://github.com/user-attachments/assets/ad8679f4-b825-4d21-b324-11d68bc93f3d)

**Comment by wu33learn** [comment]
> @77h2l If you are using a custom dataset, ensure that the METAINFO = {'classes':} setting in the coco.py file matches the category names in the config file exactly.

![image](https://github.com/user-attachments/assets/1cccaf7b-0245-4ade-b2b5-aee34bb5304b)
and does the class_name = ('cat', ) here also change to my category?

**Comment by Apurv-yash** [comment]
@slantingsun 

> [@77h2l](https://github.com/77h2l) If you are using a custom dataset, ensure that the METAINFO = {'classes':} setting in the coco.py file matches the category names in the config file exactly.

could you please explain in detail ? I am having the same issue.
