### ISSUE TITLE
[mmdet installation] ModuleNotFoundError: No module named 'mmcv._ext' with `pip` instal and `cpu` (macOS)

### ISSUE THREAD

**Issue by ioangatop** [open-mmlab/mmdetection#11611]
Following from [this commend](https://github.com/open-mmlab/mmdetection/issues/10649#issuecomment-1784000263), I am not able to install `mmcv` successfully with pip and CPU on a MacBook Pro M1

In short:
```sh
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch2.1/index.html
```

and
```sh
MMCV_WITH_OPS=1 pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.2/index.html
```

in macOS complains with:
```sh
ModuleNotFoundError: No module named 'mmcv._ext'
```

**Comment by ioangatop** [comment]
Ok for everyone who is struggling, here how I fixed it - make sure you installed torch first
```sh
pip install torch==2.1.0
MMCV_WITH_OPS=1 pip install git+https://github.com/open-mmlab/mmcv -v
```

**Comment by lmw0320** [comment]
> Ok for everyone who is struggling, here how I fixed it - make sure you installed torch first
> 
> ```shell
> pip install torch==2.1.0
> MMCV_WITH_OPS=1 pip install git+https://github.com/open-mmlab/mmcv -v
> ```

I try to install mmcv on an edge device which is not nvidia product. I use your method, still found the same error when test the installation

**Comment by ioangatop** [comment]
> Ok for everyone who is struggling, here how I fixed it - make sure you installed torch first
> pip install torch==2.1.0
MMCV_WITH_OPS=1 pip install git+https://github.com/open-mmlab/mmcv -v
I try to install mmcv on an edge device which is not nvidia product. I use your method, still found the same error when test the installation

@lmw0320 too bad, tbh I gave up on the library due to the installation issues
