### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by VectorYoung** [open-mmlab/mmdetection#1163]
Hi, 
- I am trying to install a previous version of mmdetection on my machine. Everything is fine until 'python setup.py develop'. It gives the error `RuntimeError: implement_array_function method already has a docstring`. I have another version installed on my machine, is it because of this?
- In the install instruction, it says we need to insert the following codes to the main file. 
```
import os.path as osp
import sys
sys.path.insert(0, osp.join(osp.dirname(osp.abspath(__file__)), '../'))
```
Do you mean add them to the train.py and test.py?
Thanks

**Comment by hellock** [comment]
You can add it to the scripts that you would like to use, i.e., `train.py` for training and `test.py` for testing.

A safer way is using different virtual environments for different mmdetection codebases.

**Comment by VectorYoung** [comment]
Hi @hellock , I use Anaconda to create different virtual environments for different versions. But when I install the second version, it gives the error `RuntimeError: implement_array_function method already has a docstring` in the final step `python setup.py develop`. Do you know what is the problem?

**Comment by hellock** [comment]
Could you follow the `Error report` issue template to provide detailed information?

**Comment by sunshiding** [comment]
error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

你好，我的GCC版本是7.4，怎么安装不成功？

**Comment by ZwwWayne** [comment]
> error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
> #error -- unsupported GNU version! gcc versions later than 6 are not supported!
> ^~~~~
> error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
> 
> 你好，我的GCC版本是7.4，怎么安装不成功？
The error message `gcc versions later than 6 are not supported`  already tells you why. So you need to change your gcc.

**Comment by ZwwWayne** [comment]
The issue is closed, feel free to reopen it if you have any further questions.

**Comment by RSKothari** [comment]
@ZwwWayne I have the same issue. `GCC` version is 5.5.

**Comment by ZwwWayne** [comment]
> @ZwwWayne I have the same issue. `GCC` version is 5.5.

Please create a new issue if you meet bug and cannot fix them following the `Error template` and make sure you describe your problem clearly.
