### ISSUE TITLE
Change checkpoint path

### ISSUE THREAD

**Issue by letanloc1998** [open-mmlab/mmdetection#1164]
Hello.
How to change checkpoint file path. I found in "train.py" file and config file but i didn't see it
Thanks

**Comment by hellock** [comment]
Checkpoints are saved in the working directory. You can specify the `work_dir` in the command line argument or the config file.

**Comment by letanloc1998** [comment]
thank you very much

**Comment by feixiangdekaka** [comment]
> Checkpoints are saved in the working directory. You can specify the `work_dir` in the command line argument or the config file.

How to change checkpoint  period ,  e.g. 10 , not 1.
