### ISSUE TITLE
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

### ISSUE THREAD

**Issue by veizei-K** [open-mmlab/mmdetection#11653]
I customized a convolution method,
![image](https://github.com/open-mmlab/mmdetection/assets/129288685/dbd1ef1d-c457-4114-9a6e-92ae93b35a42)
But when I run faster-rcnn I get an error.

Traceback (most recent call last):
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

I didn't do anything, I just defined a method, and  it reported an error. help me please.

**Comment by davidhuangal** [comment]
How did you fix this?

**Comment by veizei-K** [comment]
> How did you fix this?

The data type is incorrect, just use the data type ‘x’
