### ISSUE TITLE
Why should the value of nms_post be 2000 instead of 12000

### ISSUE THREAD

**Issue by scut-salmon** [open-mmlab/mmdetection#1167]
Hi, I found that the value of nms_pre and nms_post are both set to 2000 in most train config file. Only some caffe version of config file with value:
[https://github.com/open-mmlab/mmdetection/blob/57d34592ec9cbeb5416a5528c40f202b34487c4f/configs/faster_rcnn_r50_caffe_c4_1x.py#L75](url)
which I think is correct.

Could you please explain why should set the nms_pre=2000 instead of 12000, in this setting I don't think NMS will make some contributions.

Thanks,
Zhang

**Comment by hellock** [comment]
The NMS hyper-parameters are different in FPN and C4 models. You may refer to the original paper and codes.

**Comment by scut-salmon** [comment]
Yes, I refer to the Faster-RCNN paper, the proposal num after NMS is 2k:
![image](https://user-images.githubusercontent.com/20534039/62832933-1d428f00-bc69-11e9-8a4e-4ee345227e26.png)
But the FPN paper doesn't mention this parameter, so as the source [code](https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_1x.yaml#L29) by FAIR.

And I don't think the parameter nms_post is needed if nms_post=nms_pre=2000 in your setting, since the proposal num after NMS will less than 2k.

**Comment by hellock** [comment]
2000 is the default value in Detectron. FPN has multiple levels and `nms_pre` is for each level, so the total `nms_pre` is larger.

**Comment by scut-salmon** [comment]
Thanks for your reply. Yes you are right, the nms results from different FPN levels are concatenated by this [line](https://github.com/open-mmlab/mmdetection/blob/d2483e15fc48b4166815c15a6e12be864bcc521a/mmdet/models/anchor_heads/rpn_head.py#L95), but the RPN proposal num is determined by the parameter `cfg.max_num`, not `nms_post`.
Thanks.
