### ISSUE TITLE
Performance benchmark and pretrained models on WiderFace

### ISSUE THREAD

**Issue by yl1991** [open-mmlab/mmdetection#1169]
Hi, is there any plan to provide pretrain models and performance reports WiderFace? Thank you.

**Comment by hellock** [comment]
No such plan recently. Community contribution is welcome.

**Comment by yl1991** [comment]
Hi @hellock 
Sure, can I ask the what format the bounding box in CustomDataset is? Is it (x,y,w,h) or (x1,y1,x2,y2)?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/configs/wider_face/README.md
