### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found

### ISSUE THREAD

**Issue by SkeletonOne** [open-mmlab/mmdetection#1171]
pip list:
certifi (2016.2.28)
cffi (1.10.0)
Cython (0.26)
numpy (1.17.0)
olefile (0.44)
Pillow (4.2.1)
pip (9.0.1)
pycparser (2.18)
setuptools (36.4.0)
six (1.10.0)
torch (1.2.0)
torchvision (0.4.0a0+6b959ee)
wheel (0.29.0)

conda list:
_libgcc_mutex             0.1                        main    defaults                                                                                                                     
certifi                   2016.2.28                py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
cffi                      1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
cudatoolkit               10.0.130                      0    defaults                                                                                                                     
freetype                  2.5.5                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
intel-openmp              2019.4                      243    defaults                                                                                                                     
jbig                      2.1                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
libblas                   3.8.0               11_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge                                                              
libcblas                  3.8.0               11_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge                                                              
libffi                    3.2.1                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
libgcc-ng                 9.1.0                hdf63c60_0    defaults                                                                                                                     
libgfortran-ng            7.3.0                hdf63c60_0    defaults                                                                                                                     
liblapack                 3.8.0               11_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge                                                              
libopenblas               0.3.6                h6e990d7_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge                                                              
libpng                    1.6.30                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
libtiff                   4.0.6                         3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
mkl                       2019.4                      243    defaults                                                                                                                     
ninja                     1.7.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
numpy                     1.17.0           py36h95a1406_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge                                                              
olefile                   0.44                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
openssl                   1.0.2l                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
pillow                    4.2.1                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
pip                       9.0.1                    py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
pycparser                 2.18                     py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
python                    3.6.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch                                                                                                      
readline                  6.2                           2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
setuptools                36.4.0                   py36_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
six                       1.10.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
sqlite                    3.13.0                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
tk                        8.5.18                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
torchvision               0.4.0                py36_cu100    pytorch                                                                                                                      
wheel                     0.29.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
xz                        5.2.3                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free                                                                      
zlib                      1.2.11                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free  

raises the error in the issue title .

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by SkeletonOne** [comment]
@hellock Thanks for your reply, I already solved this problem by re-installing mmdetection. :)

**Comment by chen-chen32** [comment]
How did you solve it, iget the same problem,
