### ISSUE TITLE
Dose it miss a pretrained model of faster_rcnn voc config file?

### ISSUE THREAD

**Issue by wikiwen** [open-mmlab/mmdetection#1173]
It seems no pretrained model corresponding to the file "configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py" .The README file in this diretory only have SSD pretrained model. And the file in the model zoo has mismatched shape to expected shape because trained on coco datasets.

**Comment by hellock** [comment]
@wikiwen Yes we did not provide pretrained Faster R-CNN models on VOC, since it won't take much time for users to train it on VOC.
@yhcao6 Please verify if the SSD checkpoints in the model zoo are trained with VOC or COCO.

**Comment by yhcao6** [comment]
Which model? I just check the checkpoint of ssd300 and ssd512, they are fine.
