### ISSUE TITLE
RuntimeError: sigmoid_focal_loss_forward_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by miaomaomiaomaoda** [open-mmlab/mmdetection#11738]
I didn't have a problem with cpu training, but I ran into this problem with GPU training using the following commands:
``` python ../tools/train.py ./checkpoints/solov2_test.py ```

Here is my output：
[info.txt](https://github.com/open-mmlab/mmdetection/files/15426721/info.txt)

I tried setting the FORCE_CUDA and MMCV_WITH_OPS before installing mmcv but it didn't work.

How can I solve this problem, thank you very much.

**Comment by miaomaomiaomaoda** [comment]
I solved this problem by installing pytorch in 2.1.2. It seems that mmcv2.1.0 does not support torch12.3.

**Comment by thesonproductions** [comment]
> I solved this problem by installing pytorch in 2.1.2. It seems that mmcv2.1.0 does not support torch12.3.

thanks, it helped me solve that problem. I was really tired (LOL) of dealing with the above error until I saw your comment <3
