### ISSUE TITLE
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by JiaquanYe** [open-mmlab/mmdetection#1174]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

**Reproduction**
1. What command or script did you run?
```
python setup.py develop
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
I meet a error before I train the model, when I run setup.py, it occur error : error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

**Environment**
 - OS: [e.g., Ubuntu 18.04]
 - GCC [e.g., 5.5.0]
 - PyTorch version [e.g., 1.2.0]
- How you installed PyTorch [conda]
- GPU model [2080Ti]
- CUDA and CUDNN version
- CUDA9.0 and CUDNN 7.3.1

**Error traceback**
If applicable, paste the error trackback here.
```
/home/lab404/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '1.0.rc0+cda5fde' to '1.0rc0+cda5fde'
  normalized_version,
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.roi_align.roi_align_cuda' extension
gcc -pthread -B /home/lab404/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/lab404/anaconda3/include/python3.6m -c mmdet/ops/roi_align/src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.6/mmdet/ops/roi_align/src/roi_align_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/lab404/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/lab404/anaconda3/include/python3.6m -c mmdet/ops/roi_align/src/roi_align_kernel.cu -o build/temp.linux-x86_64-3.6/mmdet/ops/roi_align/src/roi_align_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
mmdet/ops/roi_align/src/roi_align_kernel.cu(133): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

mmdet/ops/roi_align/src/roi_align_kernel.cu(276): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

2 errors detected in the compilation of "/tmp/tmpxft_0000019e_00000000-6_roi_align_kernel.cpp1.ii".
error: command '/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
```

**Comment by hellock** [comment]
PyTorch 1.2 installed with conda is not compatible with CUDA 9.0.

**Comment by Vincent0102** [comment]
similar error while implement 'python setup.py develop'. Give this Error:
error: command '/usr/bin/nvcc' failed with exit status 1
Environment: 
PyTorch 1.2
CUDA 10.0

**Comment by JiaquanYe** [comment]
> Similar error while implement 'python setup.py develop'.
> Give this Error:
> error: command '/usr/bin/nvcc' failed with exit status 1
> Environment:
> PyTorch 1.2
> CUDA 10.0

I have fix this problem by follow the INSTALL.md step by step. You can try it.

**Comment by alaxinbaby** [comment]
> > Similar error while implement 'python setup.py develop'.
> > Give this Error:
> > error: command '/usr/bin/nvcc' failed with exit status 1
> > Environment:
> > PyTorch 1.2
> > CUDA 10.0
> 
> I have fix this problem by follow the INSTALL.md step by step. You can try it.

where is the INSTALL.md

**Comment by TinyMonsterLee** [comment]
> > > > 实现'python setup.py development'时出现类似错误。
> > > > 给出此错误：
> > > > 错误：命令'/ usr / bin / nvcc'失败，退出状态为1
> > > > 环境：
> > > > PyTorch 1.2 
> > > > CUDA 10.0
> > > 
> > > 
> > > 我已按照INSTALL.md逐步解决了此问题。你可以试试看。
> > 
> > 
> > INSTALL.md在哪里
> 
> 抱歉回复晚了。这是INSTALL.md的链接：[https](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md) :
> [//github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md)



> > > > 实现'python setup.py development'时出现类似错误。
> > > > 给出此错误：
> > > > 错误：命令'/ usr / bin / nvcc'失败，退出状态为1
> > > > 环境：
> > > > PyTorch 1.2 
> > > > CUDA 10.0
> > > 
> > > 
> > > 我已按照INSTALL.md逐步解决了此问题。你可以试试看。
> > 
> > 
> > INSTALL.md在哪里
> 
> 抱歉回复晚了。这是INSTALL.md的链接：[https](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md) :
> [//github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md)

非常感谢您的分享，我也遇到了这个问题，但是现在这个链接404了
