### ISSUE TITLE
Progress bar in in DetInferencer API

### ISSUE THREAD

**Issue by anisfakhfakh** [open-mmlab/mmdetection#11755]
```
from mmdet.apis import DetInferencer

inferencer = DetInferencer('rtmdet_tiny_8xb32-300e_coco')

result = inferencer('image.jpg')

```

The code shows a loading bar lke this:
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   

how can I avoid printing it?

**Comment by zeldace** [comment]
So ? Is there a way to avoid the progress bar ?

**Comment by EvgenyGorelik** [comment]
fyi

change [det_inferencer.py](https://github.com/open-mmlab/mmdetection/blob/cfd5d3a985b0249de009b67d04f37263e11cdf3d/mmdet/apis/det_inferencer.py#L401)

from
```
        for ori_imgs, data in (track(inputs, description='Inference')
```

to
```
        for ori_imgs, data in (inputs
```
