### ISSUE TITLE
anamaly detection when finetuning model

### ISSUE THREAD

**Issue by DecentMakeover** [open-mmlab/mmdetection#1179]
I am trying to fine tune faster rcnn on my data i have modified the config and set load from as the checkpoint path but when i run it i get

    2019-08-12 21:57:45,704 - INFO - Distributed training: False
    2019-08-12 21:57:45,919 - INFO - load model from: modelzoo://resnet50
    2019-08-12 21:57:46,064 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias

    missing keys in source state_dict: layer3.0.bn1.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer2.2.bn3.num_batches_tracked, bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer4.2.bn1.num_batches_tracked

    2019-08-12 21:57:50,268 - INFO - load checkpoint from checkpoints/faster_rcnn_r50_fpn_1x_15.pth
    2019-08-12 21:57:50,365 - INFO - Start running, host: bubbles@bubbles--pc, work_dir: /media/bubbles/fecf5b15-5a64-477b-8192-f8508a986ffe/ai/ryan/mmdetection/work_dirs/faster_rcnn_r50_fpn_1x
    2019-08-12 21:57:50,365 - INFO - workflow: [('train', 1)], max: 12 epochs
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
    Traceback (most recent call last):
      File "tools/train.py", line 98, in <module>
        main()
      File "tools/train.py", line 94, in main
        logger=logger)
      File "/media/bubbles/fecf5b15-5a64-477b-8192-f8508a986ffe/ai/ryan/mmdetection/mmdet/apis/train.py", line 62, in train_detector
        _non_dist_train(model, dataset, cfg, validate=validate)
      File "/media/bubbles/fecf5b15-5a64-477b-8192-f8508a986ffe/ai/ryan/mmdetection/mmdet/apis/train.py", line 223, in _non_dist_train
        runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
      File "/home/bubbles/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
        epoch_runner(data_loaders[i], **kwargs)
      File "/home/bubbles/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 269, in train
        self.call_hook('after_train_iter')
      File "/home/bubbles/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
        getattr(hook, fn_name)(self)
      File "/home/bubbles/.local/lib/python3.6/site-packages/mmcv/runner/hooks/optimizer.py", line 17, in after_train_iter
        runner.outputs['loss'].backward()
      File "/home/bubbles/.local/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
        torch.autograd.backward(self, gradient, retain_graph, create_graph)
      File "/home/bubbles/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
        allow_unreachable=True)  # allow_unreachable flag
    RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024, 256, 7, 7]], which is output 0 of IndexPutBackward, is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Any suggestions would be helpful.Thanks in advance.

**Comment by hellock** [comment]
You may update to the latest version. A bug has been fixed for PyTorch 1.2 a few days ago.

**Comment by DecentMakeover** [comment]
okay thanks let check, will a git pull be fine?

**Comment by hellock** [comment]
It would be fine.

**Comment by DecentMakeover** [comment]
okay Thanks

**Comment by DecentMakeover** [comment]
I have pulled the latest version and also run pip install -e .  but when  i run 
` python3 tools/train.py configs/faster_rcnn_r50_fpn_1x.py`

Traceback (most recent call last):
      File "tools/train.py", line 108, in <module>
        main()
      File "tools/train.py", line 86, in main
        datasets = [build_dataset(cfg.data.train)]
      File "/media/bubbles/fecf5b15-5a64-477b-8192-f8508a986ffe/ai/ryan/mmdetection/mmdet/datasets/builder.py", line 39, in build_dataset
        dataset = build_from_cfg(cfg, DATASETS, default_args)
      File "/media/bubbles/fecf5b15-5a64-477b-8192-f8508a986ffe/ai/ryan/mmdetection/mmdet/utils/registry.py", line 67, in build_from_cfg
        obj_type, registry.name))
    KeyError: 'None is not in the dataset registry'

Any suggestions?

**Comment by DecentMakeover** [comment]
Fixed it.

**Comment by kingwpf** [comment]
> Fixed it.

could you tell me how you fixed it, I meet the same question, Thank you!

**Comment by molyswu** [comment]
pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.

**Comment by Alibhji** [comment]
Hello, I have same problem when I run:
python3 tools/train.py   ./configs/ssd300_coco.py


2020-01-24 18:31:56,041 - INFO - Start running, host: ali@ali-ubt, work_dir: /home/ali/00_2020/mmdetection/work_dirs/ssd300_coco
2020-01-24 18:31:56,041 - INFO - workflow: [('train', 1)], max: 24 epochs
**/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.**

I am working on :
pytorch 1.4.0
 
Is there any solution for that?
