### ISSUE TITLE
trian with angle bboxs

### ISSUE THREAD

**Issue by andrew-begain** [open-mmlab/mmdetection#1183]
@hellocsi 
I want to train libra-fast- RCNN bboxs with Angle. What should I do?thank you

**Comment by hellocsi** [comment]
@hellock

**Comment by hellock** [comment]
Rotated bboxes are not supported currently. You need to implement related components.

**Comment by andrew-begain** [comment]
@hellock thanks for the quick reply,
Could you tell me more about it? Which components need to be implemented
thanks

**Comment by maksimovkonstantin** [comment]
@hellock what about tot try to implement ideas from here - https://github.com/mrlooi/rotated_maskrcnn or if it is possible to point what places should be changed?

**Comment by hhaAndroid** [comment]
duplicate: #952
