### ISSUE TITLE
没有数据集，仅仅只是测试一些图片，init_detector 如何初始化

### ISSUE THREAD

**Issue by HaoLiuHust** [open-mmlab/mmdetection#11841]
**Describe the feature**

**Motivation**
很多时候我下载一个开源模型，然后再进行图片推理，此时，如果我并不想下载coco等数据集，似乎就无法初始化模型，因为配置文件里配置了coco数据集，如何配置呢

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by HaoLiuHust** [comment]
Runner 可以达到这个目的

**Comment by stillbetter** [comment]
> Runner 可以达到这个目的

请问，如果我想自己写一个脚本，来测试模型，不想直接使用mmdetection中的代码，因为我们想要自己部署，请问后面的步骤要怎么从框架中摘出来呢

**Comment by HaoLiuHust** [comment]
> > Runner 可以达到这个目的
> 
> 请问，如果我想自己写一个脚本，来测试模型，不想直接使用mmdetection中的代码，因为我们想要自己部署，请问后面的步骤要怎么从框架中摘出来呢

自己部署的话就导出onnx
