### ISSUE TITLE
The problem of the HTC

### ISSUE THREAD

**Issue by linquanxu** [open-mmlab/mmdetection#1184]
hi, @hellock ,I want to use htc_x101_64x4d_fpn_20e_16gpu.py to train my own datasets. However, I don't have Stuff+thing annotations. In order to this network works well, can the lines of 108-122 of semantic segmentation, the lines of 229-230 be deleted and 'with_semantic_seg' be set in false?

**Comment by hellock** [comment]
#1154

**Comment by linquanxu** [comment]
@hellock , thank you very much.
