### ISSUE TITLE
Can you use init_detector for custom training loop implementation?

### ISSUE THREAD

**Issue by Lando-L** [open-mmlab/mmdetection#11856]
I am planning on writing a custom training loop with pytorch, instead of relying on mmengine's runner. I understand that `init_detector` is intended for inference rather than training. Can I still use it for that purpose or is there an alternative?

**Comment by PeterVennerstrom** [comment]
Have a look at the [tests for detectors](https://github.com/open-mmlab/mmdetection/blob/cfd5d3a985b0249de009b67d04f37263e11cdf3d/tests/test_models/test_detectors/test_conditional_detr.py).

These tests should show examples at the right level of abstraction.
