### ISSUE TITLE
HTC X-101-64x4d-FPN Training on 1GPU

### ISSUE THREAD

**Issue by bhaktatejas922** [open-mmlab/mmdetection#1186]
Is it possible to train this model on 1 GPU, if so what changes need to be made to the config X-101-64x4d-FPN.py file and how long is the estimate it would take? Sorry if this is a dumb question.

**Comment by mosheliv** [comment]
Depends on the gpu model...

**Comment by bhaktatejas922** [comment]
Nvdia 980ti

**Comment by mosheliv** [comment]
No... These are gigantic models. I can't even train them on my titan x properly as batch size is 2.on your card batch size will be 1 if at all.
Sorry... The model zoo has "memory" column. Try to find something small

**Comment by BlueWings8** [comment]
sorry，where to change the batch size.
