### ISSUE TITLE
HTC X-101-64x4d-FPN Training on 8GPUs

### ISSUE THREAD

**Issue by qq237942920** [open-mmlab/mmdetection#1187]
What you said in the readme of htc configs is  
`"We use 8 GPUs with 2 images/GPU for R-50 and R-101 models, and 16 GPUs with 1 image/GPU for X-101 models. If you would like to train X-101 HTC with 8 GPUs, you need to change the lr from 0.02 to 0.01."`
I have a question whether we should increase the epoch from 20 to 40and decrease the lr from 0.02 to 0.01 at the same time when we train X-101 HTC with 8 GPUs? Is this linear policy I learn from `Detectron` appropriate in mmdetection?

**Comment by hellock** [comment]
You don't have to modify the epochs, which is irrelevant to the gpu number.

**Comment by qq237942920** [comment]
But we still only have 1 batch size in 1 gpu. Don't need to change？

**Comment by hellock** [comment]
You may have some misunderstandings about the word `epoch`. Changing the batch size only affects the number of iterations.

**Comment by qq237942920** [comment]
Thanks for your patient reply! I have known what you mean. What's more, does the batch size affect the lr too? If I change the R50 or R101 batch size from 2 to 1, should I adjust the lr from 0.02 to 0.01?  Thanks!

**Comment by johnlanbor** [comment]
@qq237942920 yes

**Comment by qq237942920** [comment]
@hellock @johnlanbor I got it! Thank you for your commention.

**Comment by BoPengGit** [comment]
How long would the X-101 take to train on Google's open V5, 2+ Million segmentation masks? 

Thanks.
