### ISSUE TITLE
Failed to add some additional layers based on Existing model

### ISSUE THREAD

**Issue by zimoqingfeng** [open-mmlab/mmdetection#11899]
**Notice**

I am implementing other models to mmdetection, based on CO-DETR detector. I found the following bugs and what to solve it.

**Reproduction**

Add a simple layer at https://github.com/open-mmlab/mmdetection/blob/main/projects/CO-DETR/codetr/co_dino_head.py#L94.
For example, `self.class_embed = nn.Parameter(torch.empty(self.embed_dims, 512))`

**Results**

It seems that I can train the modified model on Single GPU, but meet the following bugs when training on multi gpus.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5a5a4493-34a0-4cb0-9db2-f8e736dba3ce">

**Comment by zimoqingfeng** [comment]
Fixed with find_unused_parameters=True and with_cp=False(-1) in training config.

**Comment by liuqs111** [comment]
@zimoqingfeng Could you tell me where to add find_unused_parameters = True? In which file?

**Comment by zimoqingfeng** [comment]
> @zimoqingfeng Could you tell me where to add find_unused_parameters = True? In which file?

In your train config file.

**Comment by liuqs111** [comment]
> > @zimoqingfeng Could you tell me where to add find_unused_parameters = True? In which file?
> 
> In your train config file.

Could you tell me the detail file? In this config? But I cannot find any distributed notices.
![屏幕截图 2024-08-09 135607](https://github.com/user-attachments/assets/d6f06ec5-3c9c-44ff-87f1-4cff4e5ec666)

**Comment by zimoqingfeng** [comment]
For example, if you want to train some specific detector in mmdetection. You may use the command like `bash tools/dist_train configs/xxxx.py`. You can add `find_unused_parameters=True` in the `configs/xxxx.py`

**Comment by liuqs111** [comment]
> find_unused_parameters=True
OK Thanks!
