### ISSUE TITLE
The error of runing on pytorch1.2

### ISSUE THREAD

**Issue by linquanxu** [open-mmlab/mmdetection#1189]
hi,when I installed the mmdetection and upgraded the 1.2.0 version of pytorch.I have got the error of ImportError: mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE. how to fix it?

**Comment by hellock** [comment]
If you upgrade to a newer version of pytorch, you need to remove the existing compiled files and reinstall it. The simplest way is to remove the old folder and clone a new one.

**Comment by linquanxu** [comment]
@hellock , ok, thank you very much.
