### ISSUE TITLE
训练时，调用得mmdet文件夹是在我anaconda虚拟环境 site-packages中得，而不是我得工程文件中得mmdet

### ISSUE THREAD

**Issue by hrr123-cell** [open-mmlab/mmdetection#11937]
我用fasterrcnn 还是rtmdet 配置好以后训练 ，调用得是C:\Users\user\.conda\envs\jingtang\Lib\site-packages\mmdet-3.0.0-py3.8.egg\mmdet路径中mmdet .  而不是我程序文件中git下载下来得mmdet文件。导致我在程序中修改配置。无法训练成功

**Comment by jimuIee** [comment]
请问你解决了这个问题吗
