### ISSUE TITLE
运行问题，一直卡在inference

### ISSUE THREAD

**Issue by wu33learn** [open-mmlab/mmdetection#11944]
https://github.com/open-mmlab/mmdetection/blob/main/configs/grounding_dino/README.md#4-model-training-and-visualization
![image](https://github.com/user-attachments/assets/2a03d146-84c2-4ca2-a2d3-feb64f27d112)
运行这段代码时，一直infernce
![image](https://github.com/user-attachments/assets/3eda1c29-7310-4825-8690-b7751aa41c6f)

**Comment by rookie1999** [comment]
兄弟，你怎么解决的

**Comment by rookie1999** [comment]
> https://github.com/open-mmlab/mmdetection/blob/main/configs/grounding_dino/README.md#4-model-training-and-visualization ![image](https://private-user-images.githubusercontent.com/136313119/365020914-2a03d146-84c2-4ca2-a2d3-feb64f27d112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgwMDAsIm5iZiI6MTcyNjY1NzcwMCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY1MDIwOTE0LTJhMDNkMTQ2LTg0YzItNGNhMi1hMmQzLWZlYjY0ZjI3ZDExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTgxNjNhNDM0ZjRmZWFhMGYxNjYyMTI5MGI3ZDcxMzg1N2UzMWRjNGJiNzYyM2UyZjdiMGM5Y2IxYmRhNGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JyX0vtvmj-TThZeAGwKoZjFbQ-pNez4s6AR6qWiF4tk) 运行这段代码时，一直infernce ![image](https://private-user-images.githubusercontent.com/136313119/365021018-3eda1c29-7310-4825-8690-b7751aa41c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgwMDAsIm5iZiI6MTcyNjY1NzcwMCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY1MDIxMDE4LTNlZGExYzI5LTczMTAtNDgyNS04NjkwLWI3NzUxYWE0MWM2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODYzZGQxYTZiYzkxYzc4MDAxMDI2YmUyZTUzMmMyMTAyZGJmZTRmZjI3MDEwMjA2YWUyY2IxYWNiMzZmMDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V6mp5yoAfITx37tt7VaVP4s-VTqz1CaW8Mt_JgcFQRM)

兄弟，你怎么解决的

**Comment by wu33learn** [comment]
> > https://github.com/open-mmlab/mmdetection/blob/main/configs/grounding_dino/README.md#4-model-training-and-visualization ![image](https://private-user-images.githubusercontent.com/136313119/365020914-2a03d146-84c2-4ca2-a2d3-feb64f27d112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgwMDAsIm5iZiI6MTcyNjY1NzcwMCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY1MDIwOTE0LTJhMDNkMTQ2LTg0YzItNGNhMi1hMmQzLWZlYjY0ZjI3ZDExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTgxNjNhNDM0ZjRmZWFhMGYxNjYyMTI5MGI3ZDcxMzg1N2UzMWRjNGJiNzYyM2UyZjdiMGM5Y2IxYmRhNGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JyX0vtvmj-TThZeAGwKoZjFbQ-pNez4s6AR6qWiF4tk) 运行这段代码时，一直infernce ![image](https://private-user-images.githubusercontent.com/136313119/365021018-3eda1c29-7310-4825-8690-b7751aa41c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgwMDAsIm5iZiI6MTcyNjY1NzcwMCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY1MDIxMDE4LTNlZGExYzI5LTczMTAtNDgyNS04NjkwLWI3NzUxYWE0MWM2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODYzZGQxYTZiYzkxYzc4MDAxMDI2YmUyZTUzMmMyMTAyZGJmZTRmZjI3MDEwMjA2YWUyY2IxYWNiMzZmMDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V6mp5yoAfITx37tt7VaVP4s-VTqz1CaW8Mt_JgcFQRM)
> 
> 兄弟，你怎么解决的

自己安装那个nltk到本地，下载俩东西
![5156e85c577da48947db92f17aa7400](https://github.com/user-attachments/assets/655a593c-bba7-46a9-9f98-3ab89623aa8d)
![57aee83b1ef921655b5b95b434c8456](https://github.com/user-attachments/assets/5f804cb1-1f47-4bf4-a5a7-8bfed75f8f39)

**Comment by rookie1999** [comment]
感谢

> > > https://github.com/open-mmlab/mmdetection/blob/main/configs/grounding_dino/README.md#4-model-training-and-visualization ![image](https://private-user-images.githubusercontent.com/136313119/365020914-2a03d146-84c2-4ca2-a2d3-feb64f27d112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgwMDAsIm5iZiI6MTcyNjY1NzcwMCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY1MDIwOTE0LTJhMDNkMTQ2LTg0YzItNGNhMi1hMmQzLWZlYjY0ZjI3ZDExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTgxNjNhNDM0ZjRmZWFhMGYxNjYyMTI5MGI3ZDcxMzg1N2UzMWRjNGJiNzYyM2UyZjdiMGM5Y2IxYmRhNGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JyX0vtvmj-TThZeAGwKoZjFbQ-pNez4s6AR6qWiF4tk) 运行这段代码时，一直infernce ![image](https://private-user-images.githubusercontent.com/136313119/365021018-3eda1c29-7310-4825-8690-b7751aa41c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTgwMDAsIm5iZiI6MTcyNjY1NzcwMCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY1MDIxMDE4LTNlZGExYzI5LTczMTAtNDgyNS04NjkwLWI3NzUxYWE0MWM2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxMTA4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODYzZGQxYTZiYzkxYzc4MDAxMDI2YmUyZTUzMmMyMTAyZGJmZTRmZjI3MDEwMjA2YWUyY2IxYWNiMzZmMDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V6mp5yoAfITx37tt7VaVP4s-VTqz1CaW8Mt_JgcFQRM)
> > 
> > 
> > 兄弟，你怎么解决的
> 
> 自己安装那个nltk到本地，下载俩东西 ![5156e85c577da48947db92f17aa7400](https://private-user-images.githubusercontent.com/136313119/368542763-655a593c-bba7-46a9-9f98-3ab89623aa8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTg0MzQsIm5iZiI6MTcyNjkxODEzNCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY4NTQyNzYzLTY1NWE1OTNjLWJiYTctNDZhOS05Zjk4LTNhYjg5NjIzYWE4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMTI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjUzMjQ4OWFmZjJkMzMzZWQ3YWJhMDQxYTgxZDk4ZTgxMGYwNjYzYTE3ZDQxZjFhNTdhYWQzYzA2YTk3NmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-ekNp6NuYsgZ_7pt2vGs3z3DEh1Nr8T3YZyrn0IcjfA) ![57aee83b1ef921655b5b95b434c8456](https://private-user-images.githubusercontent.com/136313119/368542816-5f804cb1-1f47-4bf4-a5a7-8bfed75f8f39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTg0MzQsIm5iZiI6MTcyNjkxODEzNCwicGF0aCI6Ii8xMzYzMTMxMTkvMzY4NTQyODE2LTVmODA0Y2IxLTFmNDctNGJmNC1hNWE3LThiZmVkNzVmOGYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMTI4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWI1YmY1ODBkMDUxN2NhNTBlOTAwYjViMDQ5YjZmMGY4MDA5MjIyZjlhMjYwOGFmOTNlMmQxOWZlOWRkNWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i6xX83sd9-lmbLpdfGPdLkJ7SMk_x9oGg1MwQLA0REg)

感谢兄弟，解决了
