### ISSUE TITLE
GPU imbalanced memory

### ISSUE THREAD

**Issue by dongsheng18** [open-mmlab/mmdetection#1194]
Hi, when i train model on 4 GPUs, it'll occurs an imbalanced memory usage. gpu0 has 4 processes. Many thanks!
![image](https://user-images.githubusercontent.com/54127351/63068702-c11c8b00-bf46-11e9-86aa-053c527ce2ff.png)

**Comment by hellock** [comment]
#206

**Comment by hellock** [comment]
Please check your pretrained model.
