### ISSUE TITLE
用自己的数据训练mmgounding dino时报错 data['category_id'] = self.cat_ids[label] IndexError: list index out of range

### ISSUE THREAD

**Issue by wu33learn** [open-mmlab/mmdetection#11947]
我模仿那个小猫的例子，https://github.com/open-mmlab/mmdetection/blob/main/configs/mm_grounding_dino/usage_zh-CN.md#4-%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83
用的数据物体有六类，需要怎么修改代码啊

**Comment by drillingself** [comment]
请问您解决了嘛 最后是怎么改的
