### ISSUE TITLE
The loss curve is almost the same with different training process

### ISSUE THREAD

**Issue by VectorYoung** [open-mmlab/mmdetection#1197]
Hi, I am trying to train mask rcnn with MobileNet backbone using Frozen BN and SyncBN. However, I found the loss curves of these two training process are almost the same. You can see the curves below. 
![Figure_1](https://user-images.githubusercontent.com/20220449/63124471-589ad180-bf79-11e9-9e81-e5a7cf96b284.png)
I feel very strange that these two losses are so synchronized, since the training process has some randomness, I think they can converge to a similar value but not in the same way. Do you think this is normal or there may be some problems with my training process?

**Comment by hellock** [comment]
The sampling order is deterministic when using distributed training.

**Comment by freshn** [comment]
This should be mentioned with a clear notification somewhere. I have gotten in trouble with this since last month.
