### ISSUE TITLE
keyerror in training mm-grounding-dino

### ISSUE THREAD

**Issue by xingmimfl** [open-mmlab/mmdetection#11971]
I install  mmegine/mmdetection step by step , but when i begin training, it shows that there is something wrong when mmegine loading pth, 
`mmengine - INFO - Loads checkpoint by local backend from path: grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det_20231204_095047-b448804b.pth
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
KeyError: 'backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table'`

**Comment by SparKgod1** [comment]
I met the same problem, could you share how u solve this isssue, thanks！
