### ISSUE TITLE
Why is the shape of 'rpn_cls_score' Nx3xHxW

### ISSUE THREAD

**Issue by Duankaiwen** [open-mmlab/mmdetection#120]
RPN predicts binary classes, why does the 'rpn_head' output 3 chananels?

**Comment by hellock** [comment]
In each location, there are 3 anchors (1 scale, 3 aspect ratio), so the output shape is n*3*h*w.

**Comment by myownskyW7** [comment]
After a sigmoid function, each channel indicates the probability of the corresponding anchor being foreground.

**Comment by Duankaiwen** [comment]
@hellock @myownskyW7 Thx!
