### ISSUE TITLE
KeyError: 'Adafactor is already registered in optimizer at torch.optim'

### ISSUE THREAD

**Issue by mobguang** [open-mmlab/mmdetection#12008]
你好，

在M2 ultra机器上，根据指导安装了相关依赖lib，执行以下demo时，遇到error。

python3.11 demo/image_demo.py demo/demo.jpg configs/glip/glip_atss_swin-t_a_fpn_dyhead_pretrain_obj365.py --weights checkpoints/glip_tiny_a_mmdet-b3654169.pth

**安装的mmcv版本是2.0.1**

error详细信息如下：
Traceback (most recent call last):
  File "/Volumes/M2SSD/Space/Workspace/llm/mmdetection/demo/image_demo.py", line 63, in <module>
    from mmdet.apis import DetInferencer
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmdet/apis/det_inferencer.py", line 14, in <module>
    from mmengine.infer.infer import BaseInferencer, ModelType
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/infer/__init__.py", line 2, in <module>
    from .infer import BaseInferencer
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/infer/infer.py", line 25, in <module>
    from mmengine.runner.checkpoint import (_load_checkpoint,
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/runner/__init__.py", line 2, in <module>
    from ._flexible_runner import FlexibleRunner
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/runner/_flexible_runner.py", line 14, in <module>
    from mmengine._strategy import BaseStrategy
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/_strategy/__init__.py", line 4, in <module>
    from .base import BaseStrategy
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/_strategy/base.py", line 19, in <module>
    from mmengine.model.wrappers import is_model_wrapper
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/model/__init__.py", line 6, in <module>
    from .base_model import BaseDataPreprocessor, BaseModel, ImgDataPreprocessor
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/model/base_model/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/model/base_model/base_model.py", line 9, in <module>
    from mmengine.optim import OptimWrapper
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/optim/__init__.py", line 2, in <module>
    from .optimizer import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/optim/optimizer/__init__.py", line 5, in <module>
    from .builder import (OPTIM_WRAPPER_CONSTRUCTORS, OPTIMIZERS,
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/optim/optimizer/builder.py", line 174, in <module>
    TRANSFORMERS_OPTIMIZERS = register_transformers_optimizers()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/optim/optimizer/builder.py", line 169, in register_transformers_optimizers
    OPTIMIZERS.register_module(name='Adafactor', module=Adafactor)
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/registry/registry.py", line 661, in register_module
    self._register_module(module=module, module_name=name, force=force)
  File "/Users/user_a/anaconda3/envs/mmdetect/lib/python3.11/site-packages/mmengine/registry/registry.py", line 611, in _register_module
    raise KeyError(f'{name} is already registered in {self.name} '
**KeyError: 'Adafactor is already registered in optimizer at torch.optim'**

**我试过了mmcv的2.0.0版，还是同样的error。**

**请问要如何解决，麻烦指导一下，感谢。**

**Comment by henryrobbins** [comment]
Same here. Looks like the recent release of pytorch 2.5 broke things. I downgraded to pytorch 2.4.1 and it fixed it. However, I'm now running into the other `mmcv._ext` issue people have been describing. Trying building from source as someone suggested in #11475 now...

**Comment by mobguang** [comment]
@henryrobbins 
Thanks very much for your reply!
I will try it.

**Comment by henryrobbins** [comment]
I managed to resolve the `mmcv._ext` issue when running the test installation script: `python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cpu`!

I have an M3 Pro and a Python 3.11 miniconda installation. I created a virtual environment with `python -m venv venv`. Then, I installed the following packages:

```
pip install torch==2.1.2
pip install torchvision==0.16.2
pip install numpy==1.26.4
pip install openmim
mim install mmengine
mim install "mmcv==2.1.0"
mim install mmdet
```

I found it's important to use `mim` and not `pip` when installing the openmmlab packages.

**Comment by mobguang** [comment]
> I managed to resolve the `mmcv._ext` issue when running the test installation script: `python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cpu`!
> 
> I have an M3 Pro and a Python 3.11 miniconda installation. I created a virtual environment with `python -m venv venv`. Then, I installed the following packages:
> 
> ```
> pip install torch==2.1.2
> pip install torchvision==0.16.2
> pip install numpy==1.26.4
> pip install openmim
> mim install mmengine
> mim install "mmcv==2.1.0"
> mim install mmdet
> ```
> 
> I found it's important to use `mim` and not `pip` when installing the openmmlab packages.

@henryrobbins 

Thanks for your suggestion that is critical for resolving my issue.

P.S. I export all related libs from my conda environment as following. I hope it can help people who have the same issue as me.

**And it is important to use mim and not pip when installing the openmmlab packages.**

# platform: osx-arm64
addict=2.4.0=pypi_0
aliyun-python-sdk-core=2.16.0=pypi_0
aliyun-python-sdk-kms=2.16.5=pypi_0
bzip2=1.0.8=h80987f9_6
ca-certificates=2024.9.24=hca03da5_0
certifi=2024.8.30=pypi_0
cffi=1.17.1=pypi_0
charset-normalizer=3.4.0=pypi_0
click=8.1.7=pypi_0
colorama=0.4.6=pypi_0
contourpy=1.3.0=pypi_0
crcmod=1.7=pypi_0
cryptography=43.0.3=pypi_0
cycler=0.12.1=pypi_0
filelock=3.14.0=pypi_0
fonttools=4.54.1=pypi_0
fsspec=2024.10.0=pypi_0
huggingface-hub=0.26.1=pypi_0
idna=3.10=pypi_0
importlib-metadata=8.5.0=pypi_0
jinja2=3.1.4=pypi_0
jmespath=0.10.0=pypi_0
joblib=1.4.2=pypi_0
kiwisolver=1.4.7=pypi_0
libffi=3.4.4=hca03da5_1
markdown=3.7=pypi_0
markdown-it-py=3.0.0=pypi_0
markupsafe=3.0.2=pypi_0
matplotlib=3.9.2=pypi_0
mdurl=0.1.2=pypi_0
mmcv=2.1.0=pypi_0
mmdet=3.3.0=pypi_0
mmengine=0.10.5=pypi_0
model-index=0.1.11=pypi_0
mpmath=1.3.0=pypi_0
ncurses=6.4=h313beb8_0
networkx=3.4.2=pypi_0
nltk=3.9.1=pypi_0
numpy=1.26.4=pypi_0
opencv-python=4.10.0.84=pypi_0
opendatalab=0.0.10=pypi_0
openmim=0.3.9=pypi_0
openssl=3.0.15=h80987f9_0
openxlab=0.1.2=pypi_0
ordered-set=4.1.0=pypi_0
oss2=2.17.0=pypi_0
packaging=24.1=pypi_0
pandas=2.2.3=pypi_0
pillow=11.0.0=pypi_0
pip=24.2=py311hca03da5_0
platformdirs=4.3.6=pypi_0
pycocotools=2.0.8=pypi_0
pycparser=2.22=pypi_0
pycryptodome=3.21.0=pypi_0
pygments=2.18.0=pypi_0
pyparsing=3.2.0=pypi_0
python=3.11.10=hb885b13_0
python-dateutil=2.9.0.post0=pypi_0
pytz=2023.4=pypi_0
pyyaml=6.0.2=pypi_0
readline=8.2=h1a28f6b_0
regex=2024.9.11=pypi_0
requests=2.28.2=pypi_0
rich=13.4.2=pypi_0
safetensors=0.4.5=pypi_0
scipy=1.14.1=pypi_0
setuptools=60.2.0=pypi_0
shapely=2.0.6=pypi_0
six=1.16.0=pypi_0
sqlite=3.45.3=h80987f9_0
sympy=1.13.3=pypi_0
tabulate=0.9.0=pypi_0
termcolor=2.5.0=pypi_0
terminaltables=3.1.10=pypi_0
tk=8.6.14=h6ba3021_0
tokenizers=0.20.1=pypi_0
tomli=2.0.2=pypi_0
torch=2.1.2=pypi_0
torchvision=0.16.2=pypi_0
tqdm=4.65.2=pypi_0
transformers=4.45.2=pypi_0
typing-extensions=4.12.2=pypi_0
tzdata=2024.2=pypi_0
urllib3=1.26.20=pypi_0
wheel=0.44.0=py311hca03da5_0
xz=5.4.6=h80987f9_1
yapf=0.40.2=pypi_0
zipp=3.20.2=pypi_0
zlib=1.2.13=h18a0788_1

**Comment by Alhanoufalsenan** [comment]
Thank you for your answer.

**Comment by Kayaba-Akihiko** [comment]
A workaround without downgrading to Torch2.4 could be like this. 
1. Make a python file like this (hack_registry.py)
```
#  hack_registry.py
import logging

from mmengine.registry import Registry
from mmengine.logging import print_log
from typing import Type, Optional, Union, List


def _register_module(self,
                     module: Type,
                     module_name: Optional[Union[str, List[str]]] = None,
                     force: bool = False) -> None:
    """Register a module.

    Args:
        module (type): Module to be registered. Typically a class or a
            function, but generally all ``Callable`` are acceptable.
        module_name (str or list of str, optional): The module name to be
            registered. If not specified, the class name will be used.
            Defaults to None.
        force (bool): Whether to override an existing class with the same
            name. Defaults to False.
    """
    if not callable(module):
        raise TypeError(f'module must be Callable, but got {type(module)}')

    if module_name is None:
        module_name = module.__name__
    if isinstance(module_name, str):
        module_name = [module_name]
    for name in module_name:
        if not force and name in self._module_dict:
            existed_module = self.module_dict[name]
            # raise KeyError(f'{name} is already registered in {self.name} '
            #                f'at {existed_module.__module__}')
            print_log(
                f'{name} is already registered in {self.name} '
                f'at {existed_module.__module__}. Registration ignored.',
                logger='current',
                level=logging.INFO
            )
        self._module_dict[name] = module


Registry._register_module = _register_module
```

2. Importing the `hack_registry` before importing mm modules (like `mmpretrain or mmdet`)
```
# main.py
import hack_registry
import mmdet
```

This file rewrites the registration logic that changes the behavior to logging rather than throwing an error when the key is already registered and the force flag is off.

**Comment by Z-MU-Z** [comment]
downgrade mmcv to 1.6.2 can fix this error

**Comment by Tracy-git** [comment]
when your gpu is 50 series ,you should modify the code in mmengine\optim\optimizer\builder.py  170 lines ,like this     else:
        # OPTIMIZERS.register_module(name='Adafactor', module=Adafactor)
        transformer_optimizers.append('Adafactor')
