### ISSUE TITLE
when i run python tools/train.py configs/faster_rcnn_x101_64x4d_fpn_1x.py, i got the error with TypeError: __init__() got an unexpected keyword argument 'groups' how should i do to fix the error?

### ISSUE THREAD

**Issue by jianpingZhonggit** [open-mmlab/mmdetection#1201]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
 - OS: [e.g., Ubuntu 16.04.6]
 - GCC [e.g., 5.4.0]
 - PyTorch version [e.g., 1.1.0]
- How you installed PyTorch [e.g., pip, conda, source]
- GPU model [e.g., 1080Ti, V100]
- CUDA and CUDNN version
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
You did not answer any questions in the template.

**Comment by jianpingZhonggit** [comment]
when i use resnet as the backbone of faster-rcnn, all thing goes right,but when i use resnext as backbone,it goes wrong.I fix the config as same as resnet.I fix the number_classes and I use Pascal VOC dataset.
I run python tools/train.py configs/faster_rcnn_x101_fpn1x.py, everything goes right,and start training;
however when I run python tools/train.py configs/faster_rcnn_x101_64x4d_fpn_1x.py, it goes wrong and return  ### **

1. TypeError: __init__() got an unexpected keyword argument 'groups'

**
My Environment:
OS:ubuntu 16.04
PyTorch version [1.1.0]
cuda:10.0
cudnn:7.5.4
GPU:RTX 2080 ti

**Comment by hellock** [comment]
Could you follow the issue template?

**Comment by jianpingZhonggit** [comment]
> Could you follow the issue template?

oh, I am sorry!I will do what you said.I am sorry
