### ISSUE TITLE
Box Predictions - Confidence Thresholding during Evaluation

### ISSUE THREAD

**Issue by laurenzheidrich** [open-mmlab/mmdetection#12016]
I am trying to compute evaluation metrics on my finetuned MM-Grounding-Dino Model.

I am doing this by running 

python tools/test.py $config_file $weight_file --work-dir ts_result --out ts_result/inference.pkl

This works fine and provides me with certain AP / AR results

![image](https://github.com/user-attachments/assets/3441c3b6-a5df-4d8c-a1d4-80c4d4b0c770)

When inspecting the .pkl file, though, I can see many instance predictions with decreasing confidence scores:

![image](https://github.com/user-attachments/assets/18cd124a-9e92-4d21-8869-08be228415d3)

When I visualise the predicted boxes using test.py, though, I see that only bounding boxes with a confidence > 0.3 are drawn into the image:

![image](https://github.com/user-attachments/assets/46f32f8f-e288-460c-a5ae-a7ec6db98cca)

So my question is, for the calculated AP / AR results, how & where can the confidence threshold be set? Maybe I only want to keep predictions with a confidence of 0.5, but I have no idea, where I could change that anywhere. Same goes for the visualizations: Where can I set, which bounding boxes are drawn?

I would gladly appreciate some help

**Comment by georgeblu1** [comment]
Hey, whats your answer to it? Especially: how & where can the confidence threshold be set?

**Comment by sjy-1995** [comment]
I have the same problem. Checked the model.predict() code, mm-grounding-dino selects and outputs 300 predicted bboxes by ordering the cls_score. Are 300 bboxes all used for calculating AP？or some score_threshold was set somewhere and only those whose cls_score larger than the score_threshold were used for calculating AP? Look forward to your reply.

**Comment by connorye** [comment]
> 我正在尝试在微调的 MM-Grounding-Dino 模型上计算评估指标。
> 
> 我通过运行来做到这一点
> 
> python tools/test.py $config_file $weight_file --work-dir ts_result --out ts_result/inference.pkl
> 
> 这工作正常，并为我提供了某些 AP / AR 结果
> 
> ![image](https://github.com/user-attachments/assets/3441c3b6-a5df-4d8c-a1d4-80c4d4b0c770)
> 
> 但是，在检查 .pkl 文件时，我可以看到许多置信度分数递减的实例预测：
> 
> ![image](https://github.com/user-attachments/assets/18cd124a-9e92-4d21-8869-08be228415d3)
> 
> 但是，当我使用 test.py 可视化预测的框时，我看到只有置信度为 0.3 >边界框才被绘制到图像中：
> 
> ![image](https://github.com/user-attachments/assets/46f32f8f-e288-460c-a5ae-a7ec6db98cca)
> 
> 所以我的问题是，对于计算出的 AP/AR 结果，如何以及在哪里设置置信度阈值？也许我只想以 0.5 的置信度保留预测，但我不知道我在哪里可以在任何地方更改它。可视化也是如此：我可以在哪里设置，绘制哪些边界框？
> 
> 我很乐意提供一些帮助
Hello, I also finetune mmgroundingDINO on medical images,but I have a question that why all these metric are zero when training.
 I follow the offical example of cat dataset,but it seemed something wrong.May I know how you set for the label_map.json and coco dataset categories?Thanks for any provided information.

**Comment by connorye** [comment]
@laurenzheidrich Hello,May I ask how do you set for label_map.json and categories id,I encounter same metrics are all zero in finetune on medical images when training?Do you follow the official example of cat?
