### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by yzl96** [open-mmlab/mmdetection#1203]
The error is related to learning_rate, I want to use 4 gpus and each gpu has 24 images to train ssd, so according to your markdown, I should set lr = 3e-3, but CUDA error occurs, if I decreasing the lr, the problem is fixed, so what's the problem?

**Comment by yhcao6** [comment]
I guess the training diverge at the begining, you can try a few more times. If you fail every time, you can reduce the `warmup_ratio`, for example, you can reduce from `1.0 / 3` to `1.0 / 10`. 

I try to run ssd300_coco and ssd300_voc with 4gpu, 24 imgs per gpu and lr of 3e-3, they run wihout any problem.

**Comment by jshuzi** [comment]
@yzl96 i have met the same error while train SSD using ssd300_coco config file, have you found the reason for this?
