### ISSUE TITLE
backbone HRNetV2p-W48 needed

### ISSUE THREAD

**Issue by QiaoranC** [open-mmlab/mmdetection#1205]
Hi:
    Need `HRNetV2p-W48` backbone to run the related config model, like `Cascade R-CNN with HRNetV2p-W48`. Now there are `msra/hrnetv2_w18', 'msra/hrnetv2_w32', 'msra/hrnetv2_w40.`

**Comment by hellock** [comment]
@wondervictor

**Comment by wondervictor** [comment]
@QiaoranC Hi, you can download pre-trained HRNets at this repo [HRNet-Image-Classification](https://github.com/HRNet/HRNet-Image-Classification). We provide several HRNets W18, W30, W32, W40, W44, W48, W64.

**Comment by QiaoranC** [comment]
Thanks, appreciate it.
