### ISSUE TITLE
how could I use multi batch test in guide anchor algorithm?

### ISSUE THREAD

**Issue by gittigxuy** [open-mmlab/mmdetection#1213]
I have seen a author implement the faster rcnn and retinanet,but it is not work in the guide anchor,how could I fix the code?Thanks

**Comment by hellock** [comment]
Not supported yet, but you may imitate the modifications in #939.

**Comment by gittigxuy** [comment]
yes，I reference by this pr，but since the difference between guide anchor and faster rcnn，I meet error.Maybe the reason is the specific guide anchor structure
