### ISSUE TITLE
Is it possible to use segmentation without bboxes?

### ISSUE THREAD

**Issue by cruigo93** [open-mmlab/mmdetection#1215]
Hi there! I am interested in making my own dataset and I face with issue, should I convert my binary mask to bbox? because objects are really little in some images.

**Comment by karlind** [comment]
If you want to use `mmdetection` to do `instance segmentation`, then `bbox` is actually necessary.

**Comment by iAhmedMaher** [comment]
@karlind Can you elaborate on this more? Do you mean that mmdetection isn't built for instance segmentation?
