### ISSUE TITLE
Handle empty masks for segmentation

### ISSUE THREAD

**Issue by oljike** [open-mmlab/mmdetection#1219]
hi, I have a question about instance segmentation. As far I understand, at the moment mmdet does not handle empty masks, i.e maskrcnn must get both bounding box and instance mask together. Will You handle these situations in the feature or there is boolean variable for empty masks?

**Comment by karlind** [comment]
What does `empty mask` means? Do you mean image without object?

**Comment by olzhaskabdolov** [comment]
> What does `empty mask` means? Do you mean image without object?

@karlind I mean situations, when You have an image and object with bounding box, but You do not have a mask for that object.

**Comment by hellock** [comment]
If you do not have mask annotations, you can try object detection models such as Faster R-CNN.

**Comment by karlind** [comment]
You can ignore images without object in mask head.

**Comment by LicharYuan** [comment]
You can set -1 for the empty mask. e.g. `mask = [[-1]*8]`.  It's ok in my case. 

Or, you can assign the bbox as its mask, as the empty mask is not much.

**Comment by zhangshen12356** [comment]
> You can set -1 for the empty mask. e.g. `mask = [[-1]*8]`. It's ok in my case.
> 
> Or, you can assign the bbox as its mask, as the empty mask is not much.

where can i set -1 for empty mask? in which config

**Comment by LicharYuan** [comment]
> > You can set -1 for the empty mask. e.g. `mask = [[-1]*8]`. It's ok in my case.
> > Or, you can assign the bbox as its mask, as the empty mask is not much.
> 
> where can i set -1 for empty mask? in which config

You have to manually add in the loading, before transforms.
