### ISSUE TITLE
Mask scoring RCNN error

### ISSUE THREAD

**Issue by trungpham2606** [open-mmlab/mmdetection#1227]
@hellock When testing mask scoring rcnn, I was having an error.
![image](https://user-images.githubusercontent.com/35657426/63401961-777ae700-c403-11e9-86b7-124b08353149.png)

This is the code I used:
import os.path as osp
import sys
sys.path.insert(0, osp.join(osp.dirname(osp.abspath(__file__)), '../'))

from mmdet.apis import init_detector, inference_detector, show_result
import glob
import os

config_file = r'E:\mmdetection-master\configs\ms_rcnn\ms_rcnn_x101_64x4d_fpn_1x.py'
checkpoint_file = r'E:\mmdetection-master\checkpoints\ms_rcnn_x101_64x4d_fpn_1x_20190628-dec32bda.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')

import time

imgs = glob.glob(os.path.join(r'E:\hand_detection-master\hand_dataset\test_data', '*.jpg'))
for img in imgs:
    start = time.time()
    result = inference_detector(model, img)
    end1 = time.time()
    show_result(img, result, model.CLASSES, out_file= None)
    end = time.time()
    print('Prediction time is', str(end1 - start))

**Comment by yhcao6** [comment]
Thanks for reporting the bug. This is the temporary solution.

```
    result = inference_detector(model, img)
    result = (result[0], result[1][0])
```
