### ISSUE TITLE
HTC cuda memory

### ISSUE THREAD

**Issue by johnlanbor** [open-mmlab/mmdetection#1232]
if I want to train htc with this config :configs/htc/htc_dconv_c3c5_mstrain_400_1400_x101_64x4d_fpn_20e.py

I got memory error. when I use V100 to train htc, I found it need 13.5GB memory for single image in a batch,so I cant to train htc with 1080Ti?

**Comment by johnlanbor** [comment]
Does anyone meet this question？

**Comment by hellock** [comment]
HTC with X-101-64x4d and dconv is a large model and requires lots of memory, you can try a smaller one if you want to train with 1080Ti.

**Comment by FeiWard** [comment]
> HTC with X-101-64x4d and dconv is a large model and requires lots of memory, you can try a smaller one if you want to train with 1080Ti.

I meet another problem, when I load the pretrain model download form the model zoo, the programer will stop in load mode. I found it is stop in mmcv/runner/checkpoint/load_state_dict/_copy(param), but it is no error

**Comment by BlueWings8** [comment]
could I use 2 rtx2080(8g) train htc_dconv_c3c5_mstrain_400_1400_x101_64x4d_fpn_20e.py?

**Comment by johnlanbor** [comment]
@BlueWings8  sorry, you cant. X101 and deformable need more than 13GB memory for a single image . may be you can use a  small  model , like resnet50 FPN. 
But If you only have two 2080 ,It may take more than 4 days to train.
