### ISSUE TITLE
Where to set the pre-trained backbone weight

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#1234]
Hi, there,

Due to some reasons, my server does not have Internet access. So I download the weight of Resnet-50 (resnet50-19c8e357.pth) to my local folder. 

My question is how to use this downloaded weight to kick off maskrcnn? I tried to modify the pretrained='torchvision://resnet50' path to pretrained='path-to-the-weight.pth' on the configuration files, but it fails. 

Thank you!

**Comment by hellock** [comment]
If should work fine. Could you provide more specific information?

**Comment by shanggdlk** [comment]
> If should work fine. Could you provide more specific information?

Thanks for the reply. What I do is as specify the model parameter on the config file:
model = dict(
    type='MaskRCNN',
    **pretrained='home/mmdetection/checkpoints/resnet50-19c8e357.pth',**

Then I kick off the train, and get the following error:

  File "/mmdetection/mmdet/models/detectors/mask_rcnn.py", line 31, in __init__
    pretrained=pretrained)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 57, in __init__
    self.init_weights(pretrained=pretrained)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 65, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/mmdetection/mmdet/models/backbones/resnet.py", line 484, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv-0.2.11-py3.6-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 156, in load_checkpoint
    raise IOError('{} is not a checkpoint file'.format(filename))
OSError: home/mmdetection/checkpoints/resnet50-19c8e357.pth is not a checkpoint file

**Comment by hellock** [comment]
Your path is wrong...

**Comment by shanggdlk** [comment]
> Your path is wrong...

Oh, my bad. I got confused about the last sentence in the error message. Anyway, solved it. Thank you!

While I got a new error when kick off the train, is it due to PyTorch version or Cuda version mismatch?

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024, 256, 7, 7]], which is output 0 of IndexPutBackward, is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by hellock** [comment]
Maybe you are using an old version of mmdetection, which does not support PyTorch 1.2. You may update to the latest version.

**Comment by AmberrrLiu** [comment]
> Your path is wrong...
I met the same problem,how to change the path.

OSError: checkpoints/DECOUPLED_SOLO_R50_3x.pth  is not a checkpoint file

**Comment by AmberrrLiu** [comment]
> > Your path is wrong...
> 
> Oh, my bad. I got confused about the last sentence in the error message. Anyway, solved it. Thank you!
> 
> While I got a new error when kick off the train, is it due to PyTorch version or Cuda version mismatch?
> 
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024, 256, 7, 7]], which is output 0 of IndexPutBackward, is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

I met the same problem,how to change the path.

OSError: checkpoints/DECOUPLED_SOLO_R50_3x.pth  is not a checkpoint file

**Comment by SUSHIL1312** [comment]
> > If should work fine. Could you provide more specific information?
> 
> Thanks for the reply. What I do is as specify the model parameter on the config file:
> model = dict(
> type='MaskRCNN',
> **pretrained='home/mmdetection/checkpoints/resnet50-19c8e357.pth',**
> 
> Then I kick off the train, and get the following error:
> 
> File "/mmdetection/mmdet/models/detectors/mask_rcnn.py", line 31, in **init**
> pretrained=pretrained)
> File "/mmdetection/mmdet/models/detectors/two_stage.py", line 57, in **init**
> self.init_weights(pretrained=pretrained)
> File "/mmdetection/mmdet/models/detectors/two_stage.py", line 65, in init_weights
> self.backbone.init_weights(pretrained=pretrained)
> File "/mmdetection/mmdet/models/backbones/resnet.py", line 484, in init_weights
> load_checkpoint(self, pretrained, strict=False, logger=logger)
> File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv-0.2.11-py3.6-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 156, in load_checkpoint
> **raise IOError('{} is not a checkpoint file'.format(filename))
> OSError: home/mmdetection/checkpoints/resnet50-19c8e357.pth is not a checkpoint file**

How did you solve this issue...I am haveing  same problem and same OSError message.
   **raise IOError('{} is not a checkpoint file'.format(filename))
OSError: /home/knight/Desktop/mtp/zip_folders/zsd_master/mmdetection/configs/backbones/resnet101.pyth is not a checkpoint file**  [i.e problem in setting path ].
 @shanggdlk @AmberrrLiu
