### ISSUE TITLE
Precision, Recall, AP from tools/test.py

### ISSUE THREAD

**Issue by dhananjaisharma10** [open-mmlab/mmdetection#1236]
Hi!

I am using a custom dataset and am running a detection model. Currently, in the module `tools/test.py`, I do not see any functionality for calculating the aforementioned statistics on non-COCO datasets. I could find a way to do it by using the function `eval_map` lying in the module `mmdet/core/mean_ap.py`. Please let me know if there is a quicker way to do it.

Thanks!

**Comment by hellock** [comment]
You can use `tools/test.py` to test the dataset and save the results, and use `tools/voc_eval.py` for evaluation.

**Comment by dhananjaisharma10** [comment]
Thanks a lot! Apparently, there seems to be a bug in the `voc_eval.py` module:
```
if not gt_ignore:
        gt_ignore = gt_ignore
```
should be
```
if not gt_ignore:
        gt_ignore = None
```
The former throws an error in the `eval_map` function as that does not correctly handle the bboxes to be ignored. Submitting a pull request for the same.
