### ISSUE TITLE
I have made utorial for beginers how to use mmdetection

### ISSUE THREAD

**Issue by MyLtYkRiTiK** [open-mmlab/mmdetection#1243]
Hello! I have made tutorial for beginners, which include work with inference and most important teaches how to train your own model on your own dataset: https://github.com/MyLtYkRiTiK/ComputerVision_Tutorials/blob/master/ObjectDetection_TransferLearning_with_mmdetection/object_detection_transfer_learning_mmdetection.ipynb

May be I can modify it, so you will be able to add this tutorial to your repository?

**Comment by yzl96** [comment]
I think that your tutorial don't have too much use, for model training, just follow getting_started, for inference , just follow test.py is ok.

**Comment by MyLtYkRiTiK** [comment]
> I think that your tutorial don't have too much use, for model training, just follow getting_started, for inference , just follow test.py is ok.

I think, that getting_started doesn't cover big amount of important information, so my tutorial is still useful.

**Comment by yzl96** [comment]
@MyLtYkRiTiK , in your notebook, 
from [1] to [5],  you just tell people use init_detector() and inference_detector, copy getting_started.md. 
from [6] to [13], you tell people about your data.
for [14], copy again from getting_started.md, to show you can run mmdetection.
from [15] - [21], just like [1] to [5].
so your tutorial cover what?
No defense, what's the important information that you have compared to getting_started?
By the way, all the option of train script is in train.py with detail explaination.

**Comment by MyLtYkRiTiK** [comment]
There is information, how to make annotations and rewrite config.
Where is that information in official tutorials?

**Comment by hellock** [comment]
@MyLtYkRiTiK Thanks a lot for your efforts! We are glad to include some tutorials in the repo, which can improve the documentation and make it more friendly for beginners.
In the next few days, I will go through the tutorial and give some comments. Awesome work!

**Comment by yuliok0715** [comment]
@MyLtYkRiTiK is this tutorial still up to date? have a lot of errors like this ```TypeError: __init__() got an unexpected keyword argument 'img_scale'```

**Comment by ydaigo** [comment]
I have encounter the same issue.
fix it.
https://gist.github.com/ydaigo/db2b6028d134b78d8c7f44c91525bedd

**Comment by MyLtYkRiTiK** [comment]
Mmdetection changed a lot since this tutorial. Now I have not enough time to update it.
