### ISSUE TITLE
"Pretrained" vs "Load from"

### ISSUE THREAD

**Issue by wrkgm** [open-mmlab/mmdetection#1247]
What is the difference between these two params?

I've been using only "pretrained" to load pretrained model checkpoints for finetuning, and seeing poor results. I have not used "load_from." 

After looking through the code, I can't seem to find a place where the value of "pretrained" is actually used to load weights, so I suspect I may actually have been training from scratch each time.

Do I need to use "load_from" in order to fine tune pretrained models? What is the purpose of each param and what is the difference? 

Thanks

**Comment by karlind** [comment]
`pretrained` means using pretrained weights in `backbone`, this can be downloaded automatically

`load_from` means using pretrained weights in full model, including `necks`, `heads`, etc. This must be download manually.

**Comment by neel04** [comment]
@karlind @hellock for using weights for both backbone and full model, do we specify `load_from`; as well as `pre-trained` for the backbone?

**Comment by sprakashdash** [comment]
@neel04 Just Load from is fine. With my experience when I specify load from a local directory for ResNeST fine-tuning, mmdetection automatically downloads the pre-trained model for the backbone (ResNet).
