### ISSUE TITLE
Ubuntu18.04下编译出现一连串的错误

### ISSUE THREAD

**Issue by CappuccinoMocha** [open-mmlab/mmdetection#1248]
环境是Ubuntu18.04，cuda10.0
最初的错误是
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...
    if PyDataType_HASSUBARRAY(d):
        return <tuple>d.subarray.shape
    else:
        return ()

cdef inline char* _util_dtypestring(dtype descr, char* f, char* end, int* offset) except NULL:
    ^
------------------------------------------------------------
接着是一堆的Exception，最后的提示是
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 312, in Cython.Compiler.Visitor.CythonTransform.visit_Node
  File "Cython/Compiler/Visitor.py", line 260, in Cython.Compiler.Visitor.VisitorTransform._process_children
  File "Cython/Compiler/Visitor.py", line 219, in Cython.Compiler.Visitor.TreeVisitor._visitchildren
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 148, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/home/shuangt/ObjectDetectionCode/mmdetection/.eggs/Cython-0.29.13-py3.7-linux-x86_64.egg/Cython/Includes/numpy/__init__.pxd>, 842, 5), 'AnalyseExpressionsTransform', 'Compiler crash in AnalyseExpressionsTransform\n\nModuleNode.body = StatListNode(__init__.pxd:17:0)\nStatListNode.stats[41] = StatListNode(__init__.pxd:842:5)\nStatListNode.stats[0] = CFuncDefNode(__init__.pxd:842:5,\n    args = [...]/4,\n    inline_in_pxd = True,\n    modifiers = [...]/1,\n    visibility = \'private\')\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit\n  File "/home/shuangt/ObjectDetectionCode/mmdetection/.eggs/Cython-0.29.13-py3.7-linux-x86_64.egg/Cython/Compiler/ParseTreeTransforms.py", line 2215, in visit_FuncDefNode\n    node.body = node.body.analyse_expressions(node.local_scope)\n  File "/home/shuangt/ObjectDetectionCode/mmdetection/.eggs/Cython-0.29.13-py3.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 436, in analyse_expressions\n    for stat in self.stats]\n  File "/home/shuangt/ObjectDetectionCode/mmdetection/.eggs/Cython-0.29.13-py3.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 436, in <listcomp>\n    for stat in self.stats]\n  File "/home/shuangt/ObjectDetectionCode/mmdetection/.eggs/Cython-0.29.13-py3.7-linux-x86_64.egg/Cython/Compiler/Nodes.py", line 6675, in analyse_expressions\n    self.item = self.item.coerce_to(self.target.type, env)\n  File "/home/shuangt/ObjectDetectionCode/mmdetection/.eggs/Cython-0.29.13-py3.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 952, in coerce_to\n    src = PyTypeTestNode(src, dst_type, env)\n  File "/home/shuangt/ObjectDetectionCode/mmdetection/.eggs/Cython-0.29.13-py3.7-linux-x86_64.egg/Cython/Compiler/ExprNodes.py", line 12999, in __init__\n    assert dst_type.is_extension_type or dst_type.is_builtin_type, "PyTypeTest on non extension type"\nAssertionError: PyTypeTest on non extension type', AssertionError('PyTypeTest on non extension type'), <traceback object at 0x7f8163413eb0>)

**Comment by hellock** [comment]
Please use English or English&Chinese.
It is very likely to be your environment issues, or you did not follow the installation guide. We have tried ubuntu 18.04 with CUDA 10 and it worked well. As an alternative, you may also try the docker image.

**Comment by huangbiubiu** [comment]
I had the same problem. Updating NCCL works for me! See this issue https://github.com/open-mmlab/mmdetection/issues/1025#issuecomment-532548138
