### ISSUE TITLE
Error when run mmdetection/demo/inference_demo.ipynb

### ISSUE THREAD

**Issue by ghost** [open-mmlab/mmdetection#1258]
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv

config_file = '../configs/faster_rcnn_r50_fpn_1x.py'
\# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = '../checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
\# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

\# test a single image
img = 'demo.jpg'
result = inference_detector(model, img)

\# show the results
show_result_pyplot(img, result, model.CLASSES)
![image](https://user-images.githubusercontent.com/50699884/63661909-fd75a400-c7ee-11e9-9e63-dace3aac08d0.png)
I can't slove it

**Comment by weihao86233531** [comment]
I have the same problem .Have you solved it ? if you solved it ,please help me,thank you!

**Comment by hellock** [comment]
#1254

**Comment by CappuccinoMocha** [comment]
> I have the same problem .Have you solved it ? if you solved it ,please help me,thank you!

It's a bug, and the author have just fix it, just redownload the mmdetection and run "python setup.py develop", it should work

**Comment by CappuccinoMocha** [comment]
![image](https://user-images.githubusercontent.com/50699884/63746845-510fec80-c8d8-11e9-959e-1c7db7f70a7a.png)
there seems another problem, but this seems triggered by mmcv., anyone know how to slove it ?
My environment is win10 + cuda10.1 + pytorch1.2

**Comment by CappuccinoMocha** [comment]
@hellock 
![image](https://user-images.githubusercontent.com/50699884/63747004-aba94880-c8d8-11e9-8da6-377dafe27921.png)
there seems another problem, but this seems triggered by mmcv., anyone know how to slove it ?
My environment is win10 + cuda10.1 + pytorch1.2

**Comment by hellock** [comment]
This issue is outdated.
