### ISSUE TITLE
test.py  error  

### ISSUE THREAD

**Issue by weihao86233531** [open-mmlab/mmdetection#1259]
(base) shen@shen:~/weihao/mmdetection-master$ python tools/test.py configs/faster_rcnn_r50_fpn_1x.py  checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth --show
loading annotations into memory...

Done (t=7.41s)
creating index...
index created!
[                              ] 0/40504, elapsed: 0s, ETA:

--------------------------------------------------------------
Then it stops here .   1  GTX 1080 Ti
can anyone help me ?  thanks!

**Comment by hellock** [comment]
You specified `--show`, which will show the detection results in a new window.

**Comment by LifeIsSoSolong** [comment]
> You specified `--show`, which will show the detection results in a new window.

I count the same problem when --show specified. But why showing detection results in a new window caused program stoped(and the image window is stationary). 
--Ubuntu GUI  + Single GPU

**Comment by LifeIsSoSolong** [comment]
> > You specified `--show`, which will show the detection results in a new window.
> 
> I count the same problem when --show specified. But why showing detection results in a new window caused program stoped(and the image window is stationary).
> --Ubuntu GUI + Single GPU


I figure it out. When specified --show, detector will detect images one by one. We need to press "Enter" to detect next image. That means program is paused instead of stopped.
