### ISSUE TITLE
How to print map during training?

### ISSUE THREAD

**Issue by MPolaris** [open-mmlab/mmdetection#1261]

**Comment by hellock** [comment]
Please refer to the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#train-with-multiple-gpus).

**Comment by MPolaris** [comment]
> Please refer to the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#train-with-multiple-gpus).

thanks for your response,but I still have some confusion.I fellow the documentation,used the code:
python analyze_logs.py plot_curve tools/work_dirs/faster_rcnn_r50_fpn_1x/20190827_094345.log.json --keys bbox_mAP --legend bbox_mAP
and console output :"does not contain metric bbox_mAP".Then,I have checked 20190827_094345.log.json,the jsonfile indeed doesn't contain any information about mAP.
Should I config something in config file(my_faster_rcnn.py)?

**Comment by weihao86233531** [comment]
Hi，I count the same problem(KeyError: 'log.json does not contain metric bbox_mAP')  .  It also can't plot the classification and regression loss of some run (python tools/analyze_logs.py plot_curve log.json --keys loss_cls loss_reg --out losses.pdf).  You can try it . And could you tell me how to print map during training?   Look forward to your reply,thanks.

**Comment by MPolaris** [comment]
> Hi，I count the same problem(KeyError: 'log.json does not contain metric bbox_mAP') . It also can't plot the classification and regression loss of some run (python tools/analyze_logs.py plot_curve log.json --keys loss_cls loss_reg --out losses.pdf). You can try it . And could you tell me how to print map during training? Look forward to your reply,thanks.

I haven't solved this problem yet.If I solved,I will post it.

**Comment by hellock** [comment]
You can only plot the keys that exist in log files. If you did not specify `--validate` when you trained the model, there is no `bbox_mAP` or `mask_mAP` in log files.

**Comment by MPolaris** [comment]
> You can only plot the keys that exist in log files. If you did not specify `--validate` when you trained the model, there is no `bbox_mAP` or `mask_mAP` in log files.

I think I understand what the problem is,what I use is _non_dist_train() not _dist_train(),and the parameter validate is useless in  _non_dist_train().

**Comment by tikboaHIT** [comment]
> > You can only plot the keys that exist in log files. If you did not specify `--validate` when you trained the model, there is no `bbox_mAP` or `mask_mAP` in log files.
> 
> I think I understand what the problem is,what I use is _non_dist_train() not _dist_train(),and the parameter validate is useless in _non_dist_train().

Hi, I have meet this. Do you have solved this problem?

**Comment by OpencvW** [comment]
> 
> 
> You can only plot the keys that exist in log files. If you did not specify `--validate` when you trained the model, there is no `bbox_mAP` or `mask_mAP` in log files.

Hi，I used the --validate parameter，does it take long time for validation?, why it stop there?

**Comment by alaa-shubbak** [comment]
i face the same error in training the centernet model, and i don't know how to solve it , there is no mAP in the log files , and i don't know how to use such --validate argument with the tools/ train.py  
any help please?

**Comment by sudokhan112** [comment]
> i face the same error in training the centernet model, and i don't know how to solve it , there is no mAP in the log files , and i don't know how to use such --validate argument with the tools/ train.py
> any help please?

CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=29001 tools/dist_train.sh configs/condlanenet/culane/train.py 4 --validate
