### ISSUE TITLE
How to get model checkpoints

### ISSUE THREAD

**Issue by LifeIsSoSolong** [open-mmlab/mmdetection#1262]
Thanks for your contributions.
The project have not contain checkpoints of models, the only way to get it is searching other projects ( like https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth) or training checkpints by myself?

**Comment by hellock** [comment]
Not sure what you mean. There has been a model zoo in mmdetection.

**Comment by LifeIsSoSolong** [comment]
Sorry for my fault, I have found docs/MODEL_ZOO.md.
Thanks~

**Comment by leopqrz** [comment]
The checkpoints URLs (for .pth files) are not in the MODEL_ZOO.md

**Comment by mtarun02** [comment]
Where can I find them? Thank you.

**Comment by Soodep** [comment]
> Sorry for my fault, I have found docs/MODEL_ZOO.md.
> Thanks~

Model Zoo only has .pth files for coco dataset. Are there any pretained models (pth) based on PASCAL VOC dataset format.

**Comment by aldakata** [comment]
Go to https://mmdetection3d.readthedocs.io/en/latest/tutorials/config.html > Model zoo statistics: click the link of the model you want  (I wanted MVXnet : https://github.com/open-mmlab/mmdetection3d/tree/master/configs/mvxnet) go to the readme.md and under the Results table there will be a download link.
