### ISSUE TITLE
plot loss curves.....          error 

### ISSUE THREAD

**Issue by weihao86233531** [open-mmlab/mmdetection#1264]
I got another problem in plot loss curve . it  can only plot one curve about loss_cls. But I can't plot loss of cls and reg togther  .  please help me . thanks

-----------------------
(base) shen@shen:~/weihao/mmdetection-master$ python tools/analyze_logs.py plot_curve 20190826_200217.log.json --keys loss_cls loss_reg --legend loss_cls loss_reg
plot curve of 20190826_200217.log.json, metric is loss_cls
plot curve of 20190826_200217.log.json, metric is loss_reg
Traceback (most recent call last):
  File "tools/analyze_logs.py", line 178, in <module>
    main()
  File "tools/analyze_logs.py", line 174, in main
    eval(args.task)(log_dicts, args)
  File "tools/analyze_logs.py", line 56, in plot_curve
    args.json_logs[i], metric))
KeyError: '20190826_200217.log.json does not contain metric loss_reg'
-----------------------

**Comment by hellock** [comment]
You need to check whether there exists the field `loss_reg` in your log file.
