### ISSUE TITLE
RetinaNet CUDA out of memory error

### ISSUE THREAD

**Issue by dhananjaisharma10** [open-mmlab/mmdetection#1267]
Hi!

I have been using a RetinaNet with the following configuration file: `retinanet_r50_fpn_1x.py`

Of late, I have been getting the `CUDA out of memory error` even with a batch size of 1. The issue occurs in the `resnet.py` module as shown below:

```
2019-08-26 16:53:18,678 - INFO - Start running, host: dhananjai@dhananjai-Alienware-Aurora-R7, work_dir: /home/dhananjai/raship/obj_detection/work/mmdetection/work_dirs/retinanet_r50_fpn_1x/08_26_16_53
2019-08-26 16:53:18,678 - INFO - workflow: [('train', 1)], max: 150 epochs
Traceback (most recent call last):
  File "tools/train_.py", line 136, in <module>
    main()
  File "tools/train_.py", line 132, in main
    logger=logger)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/apis/train.py", line 63, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/apis/train.py", line 243, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/apis/train.py", line 41, in batch_processor
    losses = model(**data)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/models/detectors/single_stage.py", line 51, in forward_train
    x = self.extract_feat(img)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/models/detectors/single_stage.py", line 40, in extract_feat
    x = self.backbone(img)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/models/backbones/resnet.py", line 516, in forward
    x = res_layer(x)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/models/backbones/resnet.py", line 263, in forward
    out = _inner_forward(x)
  File "/home/dhananjai/raship/obj_detection/work/mmdetection/mmdet/models/backbones/resnet.py", line 255, in _inner_forward
    identity = self.downsample(x)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dhananjai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 8.51 GiB (GPU 0; 10.91 GiB total capacity; 643.78 MiB already allocated; 8.53 GiB free; 34.22 MiB cached)
(open-mmlab) dhananjai@dhananjai-Alienware-Aurora-R7:~/raship/obj_detection/work/mmdetection$ 
```

Please let me know what can I do apart from getting more computation. Many thanks!

**Comment by hellock** [comment]
RetinaNet R-50 should work fine on 1080Ti (11G) with 2 images per GPU. Maybe you can check it again.

**Comment by borgarpa** [comment]
I am getting the same error with the following config file [config.txt](https://github.com/open-mmlab/mmdetection/files/5441138/config.txt).

I am using DetectoRS with a ResNeXt 101 backbone, but with only one worker per GPU, and one image. It souldn't be the case that using a 11 Gb GPU machine a memory error prompts.

```
RuntimeErrorTraceback (most recent call last)
<ipython-input-7-c4ae1e89a8af> in <module>
      9 # Create work_dir
     10 # mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 11 train_detector(model, datasets, cfg, distributed=False, validate=True)

/workspace/mmdetection/mmdet/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
    148     elif cfg.load_from:
    149         runner.load_checkpoint(cfg.load_from)
--> 150     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)

/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
    123                     if mode == 'train' and self.epoch >= self._max_epochs:
    124                         break
--> 125                     epoch_runner(data_loaders[i], **kwargs)
    126 
    127         time.sleep(1)  # wait for some hooks like loggers to finish

/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
     48             self._inner_iter = i
     49             self.call_hook('before_train_iter')
---> 50             self.run_iter(data_batch, train_mode=True)
     51             self.call_hook('after_train_iter')
     52             self._iter += 1

/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in run_iter(self, data_batch, train_mode, **kwargs)
     28         elif train_mode:
     29             outputs = self.model.train_step(data_batch, self.optimizer,
---> 30                                             **kwargs)
     31         else:
     32             outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)

/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py in train_step(self, *inputs, **kwargs)
     65 
     66         inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
---> 67         return self.module.train_step(*inputs[0], **kwargs[0])
     68 
     69     def val_step(self, *inputs, **kwargs):

/workspace/mmdetection/mmdet/models/detectors/base.py in train_step(self, data, optimizer)
    232                 averaging the logs.
    233         """
--> 234         losses = self(**data)
    235         loss, log_vars = self._parse_losses(losses)
    236 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py in new_func(*args, **kwargs)
     82                                 'method of nn.Module')
     83             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
---> 84                 return old_func(*args, **kwargs)
     85             # get the arg spec of the decorated method
     86             args_info = getfullargspec(old_func)

/workspace/mmdetection/mmdet/models/detectors/base.py in forward(self, img, img_metas, return_loss, **kwargs)
    166         """
    167         if return_loss:
--> 168             return self.forward_train(img, img_metas, **kwargs)
    169         else:
    170             return self.forward_test(img, img_metas, **kwargs)

/workspace/mmdetection/mmdet/models/detectors/two_stage.py in forward_train(self, img, img_metas, gt_bboxes, gt_labels, gt_bboxes_ignore, gt_masks, proposals, **kwargs)
    154                 gt_labels=None,
    155                 gt_bboxes_ignore=gt_bboxes_ignore,
--> 156                 proposal_cfg=proposal_cfg)
    157             losses.update(rpn_losses)
    158         else:

/workspace/mmdetection/mmdet/models/dense_heads/base_dense_head.py in forward_train(self, x, img_metas, gt_bboxes, gt_labels, gt_bboxes_ignore, proposal_cfg, **kwargs)
     52         else:
     53             loss_inputs = outs + (gt_bboxes, gt_labels, img_metas)
---> 54         losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
     55         if proposal_cfg is None:
     56             return losses

/workspace/mmdetection/mmdet/models/dense_heads/rpn_head.py in loss(self, cls_scores, bbox_preds, gt_bboxes, img_metas, gt_bboxes_ignore)
     72             None,
     73             img_metas,
---> 74             gt_bboxes_ignore=gt_bboxes_ignore)
     75         return dict(
     76             loss_rpn_cls=losses['loss_cls'], loss_rpn_bbox=losses['loss_bbox'])

/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py in new_func(*args, **kwargs)
    162                                 'method of nn.Module')
    163             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
--> 164                 return old_func(*args, **kwargs)
    165             # get the arg spec of the decorated method
    166             args_info = getfullargspec(old_func)

/workspace/mmdetection/mmdet/models/dense_heads/anchor_head.py in loss(self, cls_scores, bbox_preds, gt_bboxes, gt_labels, img_metas, gt_bboxes_ignore)
    458             gt_bboxes_ignore_list=gt_bboxes_ignore,
    459             gt_labels_list=gt_labels,
--> 460             label_channels=label_channels)
    461         if cls_reg_targets is None:
    462             return None

/workspace/mmdetection/mmdet/models/dense_heads/anchor_head.py in get_targets(self, anchor_list, valid_flag_list, gt_bboxes_list, img_metas, gt_bboxes_ignore_list, gt_labels_list, label_channels, unmap_outputs, return_sampling_results)
    343             img_metas,
    344             label_channels=label_channels,
--> 345             unmap_outputs=unmap_outputs)
    346         (all_labels, all_label_weights, all_bbox_targets, all_bbox_weights,
    347          pos_inds_list, neg_inds_list, sampling_results_list) = results[:7]

/workspace/mmdetection/mmdet/core/utils/misc.py in multi_apply(func, *args, **kwargs)
     52     pfunc = partial(func, **kwargs) if kwargs else func
     53     map_results = map(pfunc, *args)
---> 54     return tuple(map(list, zip(*map_results)))
     55 
     56 

/workspace/mmdetection/mmdet/models/dense_heads/anchor_head.py in _get_targets_single(self, flat_anchors, valid_flags, gt_bboxes, gt_bboxes_ignore, gt_labels, img_meta, label_channels, unmap_outputs)
    218         assign_result = self.assigner.assign(
    219             anchors, gt_bboxes, gt_bboxes_ignore,
--> 220             None if self.sampling else gt_labels)
    221         sampling_result = self.sampler.sample(assign_result, anchors,
    222                                               gt_bboxes)

/workspace/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py in assign(self, bboxes, gt_bboxes, gt_bboxes_ignore, gt_labels)
    103                 gt_labels = gt_labels.cpu()
    104 
--> 105         overlaps = self.iou_calculator(gt_bboxes, bboxes)
    106 
    107         if (self.ignore_iof_thr > 0 and gt_bboxes_ignore is not None

/workspace/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py in __call__(self, bboxes1, bboxes2, mode, is_aligned)
     33         if bboxes1.size(-1) == 5:
     34             bboxes1 = bboxes1[..., :4]
---> 35         return bbox_overlaps(bboxes1, bboxes2, mode, is_aligned)
     36 
     37     def __repr__(self):

/workspace/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py in bbox_overlaps(bboxes1, bboxes2, mode, is_aligned, eps)
    139                        bboxes2[..., None, :, 2:])  # [B, rows, cols, 2]
    140 
--> 141         wh = (rb - lt).clamp(min=0)  # [B, rows, cols, 2]
    142         overlap = wh[..., 0] * wh[..., 1]
    143 

RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 10.73 GiB total capacity; 9.62 GiB already allocated; 30.62 MiB free; 9.86 GiB reserved in total by PyTorch)
```

My `nvidia-smi` results:

```
Mon Oct 26 19:55:17 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
|  0%   31C    P0    53W / 250W |     11MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by observar** [comment]
> I am getting the same error with the following config file [config.txt](https://github.com/open-mmlab/mmdetection/files/5441138/config.txt).
> 
> I am using DetectoRS with a ResNeXt 101 backbone, but with only one worker per GPU, and one image. It souldn't be the case that using a 11 Gb GPU machine a memory error prompts. Besides, in the following issue #3863 it is suggested that the `iou2d_calculator.py` file might have a bug in the line 141, `wh = (rb - lt).clamp(min=0) # [B, rows, cols, 2]`.
> 
> Could it be a memory leakage?
> 
> ```
> RuntimeErrorTraceback (most recent call last)
> <ipython-input-7-c4ae1e89a8af> in <module>
>       9 # Create work_dir
>      10 # mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
> ---> 11 train_detector(model, datasets, cfg, distributed=False, validate=True)
> 
> /workspace/mmdetection/mmdet/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
>     148     elif cfg.load_from:
>     149         runner.load_checkpoint(cfg.load_from)
> --> 150     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
> 
> /opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
>     123                     if mode == 'train' and self.epoch >= self._max_epochs:
>     124                         break
> --> 125                     epoch_runner(data_loaders[i], **kwargs)
>     126 
>     127         time.sleep(1)  # wait for some hooks like loggers to finish
> 
> /opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
>      48             self._inner_iter = i
>      49             self.call_hook('before_train_iter')
> ---> 50             self.run_iter(data_batch, train_mode=True)
>      51             self.call_hook('after_train_iter')
>      52             self._iter += 1
> 
> /opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in run_iter(self, data_batch, train_mode, **kwargs)
>      28         elif train_mode:
>      29             outputs = self.model.train_step(data_batch, self.optimizer,
> ---> 30                                             **kwargs)
>      31         else:
>      32             outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
> 
> /opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py in train_step(self, *inputs, **kwargs)
>      65 
>      66         inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
> ---> 67         return self.module.train_step(*inputs[0], **kwargs[0])
>      68 
>      69     def val_step(self, *inputs, **kwargs):
> 
> /workspace/mmdetection/mmdet/models/detectors/base.py in train_step(self, data, optimizer)
>     232                 averaging the logs.
>     233         """
> --> 234         losses = self(**data)
>     235         loss, log_vars = self._parse_losses(losses)
>     236 
> 
> /opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> /opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py in new_func(*args, **kwargs)
>      82                                 'method of nn.Module')
>      83             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
> ---> 84                 return old_func(*args, **kwargs)
>      85             # get the arg spec of the decorated method
>      86             args_info = getfullargspec(old_func)
> 
> /workspace/mmdetection/mmdet/models/detectors/base.py in forward(self, img, img_metas, return_loss, **kwargs)
>     166         """
>     167         if return_loss:
> --> 168             return self.forward_train(img, img_metas, **kwargs)
>     169         else:
>     170             return self.forward_test(img, img_metas, **kwargs)
> 
> /workspace/mmdetection/mmdet/models/detectors/two_stage.py in forward_train(self, img, img_metas, gt_bboxes, gt_labels, gt_bboxes_ignore, gt_masks, proposals, **kwargs)
>     154                 gt_labels=None,
>     155                 gt_bboxes_ignore=gt_bboxes_ignore,
> --> 156                 proposal_cfg=proposal_cfg)
>     157             losses.update(rpn_losses)
>     158         else:
> 
> /workspace/mmdetection/mmdet/models/dense_heads/base_dense_head.py in forward_train(self, x, img_metas, gt_bboxes, gt_labels, gt_bboxes_ignore, proposal_cfg, **kwargs)
>      52         else:
>      53             loss_inputs = outs + (gt_bboxes, gt_labels, img_metas)
> ---> 54         losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
>      55         if proposal_cfg is None:
>      56             return losses
> 
> /workspace/mmdetection/mmdet/models/dense_heads/rpn_head.py in loss(self, cls_scores, bbox_preds, gt_bboxes, img_metas, gt_bboxes_ignore)
>      72             None,
>      73             img_metas,
> ---> 74             gt_bboxes_ignore=gt_bboxes_ignore)
>      75         return dict(
>      76             loss_rpn_cls=losses['loss_cls'], loss_rpn_bbox=losses['loss_bbox'])
> 
> /opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py in new_func(*args, **kwargs)
>     162                                 'method of nn.Module')
>     163             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
> --> 164                 return old_func(*args, **kwargs)
>     165             # get the arg spec of the decorated method
>     166             args_info = getfullargspec(old_func)
> 
> /workspace/mmdetection/mmdet/models/dense_heads/anchor_head.py in loss(self, cls_scores, bbox_preds, gt_bboxes, gt_labels, img_metas, gt_bboxes_ignore)
>     458             gt_bboxes_ignore_list=gt_bboxes_ignore,
>     459             gt_labels_list=gt_labels,
> --> 460             label_channels=label_channels)
>     461         if cls_reg_targets is None:
>     462             return None
> 
> /workspace/mmdetection/mmdet/models/dense_heads/anchor_head.py in get_targets(self, anchor_list, valid_flag_list, gt_bboxes_list, img_metas, gt_bboxes_ignore_list, gt_labels_list, label_channels, unmap_outputs, return_sampling_results)
>     343             img_metas,
>     344             label_channels=label_channels,
> --> 345             unmap_outputs=unmap_outputs)
>     346         (all_labels, all_label_weights, all_bbox_targets, all_bbox_weights,
>     347          pos_inds_list, neg_inds_list, sampling_results_list) = results[:7]
> 
> /workspace/mmdetection/mmdet/core/utils/misc.py in multi_apply(func, *args, **kwargs)
>      52     pfunc = partial(func, **kwargs) if kwargs else func
>      53     map_results = map(pfunc, *args)
> ---> 54     return tuple(map(list, zip(*map_results)))
>      55 
>      56 
> 
> /workspace/mmdetection/mmdet/models/dense_heads/anchor_head.py in _get_targets_single(self, flat_anchors, valid_flags, gt_bboxes, gt_bboxes_ignore, gt_labels, img_meta, label_channels, unmap_outputs)
>     218         assign_result = self.assigner.assign(
>     219             anchors, gt_bboxes, gt_bboxes_ignore,
> --> 220             None if self.sampling else gt_labels)
>     221         sampling_result = self.sampler.sample(assign_result, anchors,
>     222                                               gt_bboxes)
> 
> /workspace/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py in assign(self, bboxes, gt_bboxes, gt_bboxes_ignore, gt_labels)
>     103                 gt_labels = gt_labels.cpu()
>     104 
> --> 105         overlaps = self.iou_calculator(gt_bboxes, bboxes)
>     106 
>     107         if (self.ignore_iof_thr > 0 and gt_bboxes_ignore is not None
> 
> /workspace/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py in __call__(self, bboxes1, bboxes2, mode, is_aligned)
>      33         if bboxes1.size(-1) == 5:
>      34             bboxes1 = bboxes1[..., :4]
> ---> 35         return bbox_overlaps(bboxes1, bboxes2, mode, is_aligned)
>      36 
>      37     def __repr__(self):
> 
> /workspace/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py in bbox_overlaps(bboxes1, bboxes2, mode, is_aligned, eps)
>     139                        bboxes2[..., None, :, 2:])  # [B, rows, cols, 2]
>     140 
> --> 141         wh = (rb - lt).clamp(min=0)  # [B, rows, cols, 2]
>     142         overlap = wh[..., 0] * wh[..., 1]
>     143 
> 
> RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 10.73 GiB total capacity; 9.62 GiB already allocated; 30.62 MiB free; 9.86 GiB reserved in total by PyTorch)
> ```
> 
> My `nvidia-smi` results:
> 
> ```
> Mon Oct 26 19:55:17 2020
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 208...  Off  | 00000000:82:00.0 Off |                  N/A |
> |  0%   31C    P0    53W / 250W |     11MiB / 10989MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```

Did you solve it ? i training faster r-cnn on my own dataset have the same problem

**Comment by borgarpa** [comment]
@observar Unfortunately not... Check the following issue #3863. It's opened and tagged as bug, and I think somebody is alrealt looking into it.
