### ISSUE TITLE
Support multi-scale image size?

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#1268]
Hi, Kai,

Thanks for your quick responses to my past questions. Appreciate!

A quick question, does MMdetection support mult-scale image size settings? I saw in the configure file that img_scale=(1333, 800), where 1333 and 800 should be the maximum and minimum image size. Is it possible to set multiple minimum image size like in Maskrcnn-benchmark project? e.g., MIN_SIZE_TRAIN = (800,1024, 1222), MAX_SIZE_TRAIN =  (1333).

Another question is can we set different scales for the anchor. By default the scale is 8 and the stride = (4,8,16,32,64), can we set scale to (4,8,4,4,4) for example to get anchor size (16,64,64,128,256).

Thank you!

**Comment by hellock** [comment]
1. Multiscale training/inference is supported and you can refer to closed issues (e.g., #78, #840, #135).

2. You can set any anchor size you like.
