### ISSUE TITLE
How to use the deform convolution

### ISSUE THREAD

**Issue by menglin0320** [open-mmlab/mmdetection#1269]
Hi all, I only want to use deform convolution on my project. Is here a file about how to compile and use the cudnn files?

**Comment by hellock** [comment]
You can take the dcn op and write a new `setup.py` which only compiles one extension.

**Comment by Actmaiji** [comment]
> Hi all, I only want to use deform convolution on my project. Is here a file about how to compile and use the cudnn files?



> Yeah, I figured this out. The problem is that nvcc is a headache. Is it easier to install full cuda(with nvcc) with docker than with conda

Hi guy,have you solved the problem? I  only want to use deform convoltion on my project yet.Can use it from mmdetection?Or We can Only use it by compiling it ourself.

**Comment by menglin0320** [comment]
The easiest way is to install the whole thing(with venv conda or docker) then import deformconv as from mmdet.ops.dcn.deform_conv import DeformConv

**Comment by menglin0320** [comment]
If you are familiar with how to add cuda module on pytorch, you can modify the setup.py. if you do that, can you please share the script?

**Comment by Actmaiji** [comment]
yes,I have done it, import deformconv as from mmdet.ops.dcn.deform_conv import DeformConv.

unfortunately,the deformconv comsuming to much memory:RuntimeError: CUDA out of memory. Tried to allocate 996.00 MiB (GPU 0; 7.93 GiB total capacity; 4.67 GiB already allocated; 185.94 MiB free; 1.91 GiB cached). 
My batchsize is 32 or 128,and I try batchsize==1,but failed.
