### ISSUE TITLE
CPU based inference !!!

### ISSUE THREAD

**Issue by ChandanVerma** [open-mmlab/mmdetection#1274]
Can models generated using this repository be deployed on a CPU based environment for inference on new images?
If yes can you provide a link on how it can be done?

Thanks,
Chandan

**Comment by hellock** [comment]
Currently it is not feasible since we have not implemented CPU ops for RoIAlign/RoIPool.

**Comment by ChandanVerma** [comment]
Thanks for the reply... Any plans of implementing it in the near future??

**Comment by hellock** [comment]
This is in our long-term plan, but may not be implemented in the near future.

**Comment by ChandanVerma** [comment]
OK thanks
