### ISSUE TITLE
ImportError: cannot import name 'DistributedSampler'

### ISSUE THREAD

**Issue by wtshow** [open-mmlab/mmdetection#1276]
when i run a demo the code like this ：
`from mmdet.apis import init_detector, inference_detector, show_result
import mmcv

config_file = 'configs/faster_rcnn_r50_fpn_1x.py'
checkpoint_file = 'faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = 'timg.jpg'  
result = inference_detector(model, img)
show_result(img, result, model.CLASSES)`

produce an ImportError: cannot import name 'DistributedSampler'

How to solve it

**Comment by wtshow** [comment]
![image](https://user-images.githubusercontent.com/39188167/63753698-2b89df80-c8e6-11e9-992d-3de058015fec.png)

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
