### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/libra_proposals/rpn_r50_fpn_1x_train2017.pkl'

### ISSUE THREAD

**Issue by DRosemei** [open-mmlab/mmdetection#1277]
python tools/train.py configs/libra_rcnn/libra_fast_rcnn_r50_fpn_1x.py 
--autoscale-lr 
2019-08-27 16:20:39,764 - INFO - Distributed training: False
2019-08-27 16:20:40,014 - INFO - load model from: torchvision://resnet50
2019-08-27 16:20:40,138 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=9.79s)
creating index...
index created!
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/libra_proposals/rpn_r50_fpn_1x_train2017.pkl'
I did not find where to get this file. Could someone help me?

**Comment by PumayHui** [comment]
Update……
Solved. The img_scale contain 2 size, such as img_scale=[(1333, 1024), (1333, 832)],
but failed with  img_scale=[(1333, 1024), (1333, 832), (1333, 608)],
Will modify this? Thanks!

**Comment by hellock** [comment]
This proposal file is extracted with an RPN model. You need to generate the proposals by yourself with the test script.

**Comment by DRosemei** [comment]
Thanks for your help :)

**Comment by DRosemei** [comment]
Thanks for your help :) @hellock

**Comment by XCRobert** [comment]
> Thanks for your help :) @hellock

How to generate the proposals？Can you share the script?

**Comment by wmmxk** [comment]
Is it OK to train without proposals generated beforehand?

**Comment by DRosemei** [comment]
> > Thanks for your help :) @hellock
> 
> How to generate the proposals？Can you share the script?

I used libra_faster_rcnn instead cause fast rcnn does not have a rpn.

**Comment by RebornL** [comment]
Do you know how to visualiza the RPN network output result on test jpg?@DRosemei @wmmxk

**Comment by yelingyunlmm** [comment]
my solution is:
vim configs/_base_/datasets/coco_detection.py
modify 
"
test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline))
"
to
"
test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        pipeline=test_pipeline))
"
maybe help you
