### ISSUE TITLE
Support new custom optimizer, like Lookahead, RAdam?

### ISSUE THREAD

**Issue by QiaoranC** [open-mmlab/mmdetection#1282]
Hi:
   There are two new optimizer  [Lookahead implementation from LonePatient](https://github.com/lonePatient/lookahead_pytorch/blob/master/optimizer.py)  and [RAdam](https://github.com/LiyuanLucasLiu/RAdam/blob/master/radam.py), 
how to merger these into project, in `train.py` it seems only support pytorch official optimizer?
Any example or clue?

**Comment by hellock** [comment]
For a current walkaround, you can modify [`build_optimizer()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L63). We will consider a better api to support custom optimizers.

**Comment by QiaoranC** [comment]
Thanks
