### ISSUE TITLE
RuntimeError: train.py ssd300_coco.py

### ISSUE THREAD

**Issue by Kaeseknacker** [open-mmlab/mmdetection#1285]
Hi,

I try to train ssd with standard config file, but I get the following error:

```
  File "/home/user//Code/mmdetection/mmdet/core/bbox/geometry.py", line 53, in bbox_overlaps
    lt = torch.max(bboxes1[:, None, :2], bboxes2[:, :2])  # [rows, cols, 2]
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'other'

```

Last week (e.g. commit ID: 0b96173...) I had no problems with that. I suspect it has something to do with the new training pipeline.

**Comment by Kaeseknacker** [comment]
I tried different commits:
``python tools/train.py configs/ssd300_coco.py``
works until 0d5233a
Since 381f491 the error occurs.

**Comment by hellock** [comment]
Thanks for the report! We will fix this bug tomorrow.
See also https://github.com/open-mmlab/mmdetection/pull/1249#issuecomment-525320638.

**Comment by auroua** [comment]
The config file  'ssd512_coco.py'  wrongly set `img_scale`  to  (300, 300).

**Comment by hellock** [comment]
Thanks @auroua, you may open a PR to fix that if would like to.

**Comment by luyao777** [comment]
It occurs in ssd300_wider_face.py too.
I trid to use boxes = (boxes + np.tile((left, top), 2)).astype(boxes.dtype) but it didn't work.
Is there any suggestion?

**Comment by auroua** [comment]
@luyao777   
After add op the `boxes` type have changed to `float64`, using the following code.
`
boxes += np.tile((left, top), 2)
`

**Comment by luyao777** [comment]
Oh, sorry! There is something wrong in my branch. It worked after use `boxes = (boxes + np.tile((left, top), 2)).astype(boxes.dtype)` in mmdet/datasets/pipelines/transforms.py, the original `boxes = (boxes + np.tile((left, top), 2))` may have some bugs in ssd. @auroua Thanks.
Hope to fix that!
