### ISSUE TITLE
NMS across classes?

### ISSUE THREAD

**Issue by Akamight** [open-mmlab/mmdetection#1286]
When I predict the results, it is clear that there are many overlapping boxes with even nms threshold = 0.1. I found out that they are in different classes, so is there a way for me to actually use nms across classes?

**Comment by lckdl** [comment]
I have the same problem.

**Comment by hellock** [comment]
We follow the official implementation of Faster/Mask R-CNN to apply NMS for each class. If you would like to try NMS across classes, you may modify [`multiclass_nms()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/post_processing/bbox_nms.py#L6).

**Comment by teejK** [comment]
how do you select multiclass mms? Do you put

**Comment by teejK** [comment]
How would you select multi-class NMS in the config if you're using 'mmdetection/configs/tood/tood_r101_fpn_dconv_c3-c5_mstrain_2x_coco.py'?
