### ISSUE TITLE
./compile.sh ERROR

### ISSUE THREAD

**Issue by Li-Chengyang** [open-mmlab/mmdetection#129]
Hi,
I encounter some error compiling mmdetection.
I use
ubuntu14.04
gcc7.3.0
cuda9.2
cudnn7.1
pytorch0.41
python3.7

(open-mmlab) zero@amax:~/Research/WebCodes/mmdetection$ ./compile.sh 
Building roi align op...
running build_ext
building 'roi_align_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/zero/Research/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zero/Research/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/zero/Research/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/zero/Research/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zero/Research/anaconda3/envs/open-mmlab/include/python3.7m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.7/src/roi_align_cuda.o -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
**gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1**
Building roi pool op...
running build_ext
building 'roi_pool_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/zero/Research/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zero/Research/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/zero/Research/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/zero/Research/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zero/Research/anaconda3/envs/open-mmlab/include/python3.7m -c src/roi_pool_cuda.cpp -o build/temp.linux-x86_64-3.7/src/roi_pool_cuda.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
**gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1**
Building nms op...
rm -f *.so
echo "Compiling nms kernels..."
Compiling nms kernels...
python setup.py build_ext --inplace
running build_ext
building 'cpu_nms' extension
gcc -pthread -B /home/zero/Research/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zero/Research/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include -I/home/zero/Research/anaconda3/envs/open-mmlab/include/python3.7m -c cpu_nms.cpp -o build/temp.linux-x86_64-3.7/cpu_nms.o -Wno-unused-function -Wno-write-strings
**gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1**
make: *** [all] Error 1

**Comment by hushunda** [comment]
I have same error。Did you solve this?

**Comment by Li-Chengyang** [comment]
@hushunda It is caused by incompatible gcc version.

**Comment by hushunda** [comment]
@Li-Chengyang Thank you !

**Comment by joaqo** [comment]
@Li-Chengyang I have the same problem, tried gcc 6 and 5.5 and they didnt work. Which version worked for you? How did you downgrade to that specific version? Thanks!

**Comment by Li-Chengyang** [comment]
@joaqo gcc version 5.5 works for me. My initial version is 7.x which is too up-to-date I guess.
