### ISSUE TITLE
how to add Global Context ?

### ISSUE THREAD

**Issue by sloan96** [open-mmlab/mmdetection#1290]
Take cascade rcnn as an example，I want to take the whole image as a RoI, perform RoI Pooling on it and concatenating the obtained feature vector on each feature vector of RoI, as a kind of auxiliary information after the incoming R-CNN sub-network.Can you give me some advice? Such as /mmdet/models/detectors/cascade_rcnn.py

**Comment by ShihuaiXu** [comment]
have you found the solution? I am also doing this project, my qq is 531232693, please add me

**Comment by milleniums** [comment]
> Take cascade rcnn as an example，I want to take the whole image as a RoI, perform RoI Pooling on it and concatenating the obtained feature vector on each feature vector of RoI, as a kind of auxiliary information after the incoming R-CNN sub-network.Can you give me some advice? Such as /mmdet/models/detectors/cascade_rcnn.py

hi, have you resovled this problem?

**Comment by sky-fly97** [comment]
> > Take cascade rcnn as an example，I want to take the whole image as a RoI, perform RoI Pooling on it and concatenating the obtained feature vector on each feature vector of RoI, as a kind of auxiliary information after the incoming R-CNN sub-network.Can you give me some advice? Such as /mmdet/models/detectors/cascade_rcnn.py
> 
> hi, have you resovled this problem?

Anyone has done it?

**Comment by milleniums** [comment]
https://github.com/milleniums/underwater-object-detection-mmdetection/blob/master/mmdet/models/roi_extractors/single_level.py

发自我的iPhone


------------------ Original ------------------

**Comment by sky-fly97** [comment]
> https://github.com/milleniums/underwater-object-detection-mmdetection/blob/master/mmdet/models/roi_extractors/single_level.py 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: sky-fly97 <notifications@github.com&gt; Date: Thu,Sep 3,2020 8:20 PM To: open-mmlab/mmdetection <mmdetection@noreply.github.com&gt; Cc: milleniums <2926151134@qq.com&gt;, Comment <comment@noreply.github.com&gt; Subject: Re: [open-mmlab/mmdetection] how to add Global Context ? (#1290) Take cascade rcnn as an example，I want to take the whole image as a RoI, perform RoI Pooling on it and concatenating the obtained feature vector on each feature vector of RoI, as a kind of auxiliary information after the incoming R-CNN sub-network.Can you give me some advice? Such as /mmdet/models/detectors/cascade_rcnn.py hi, have you resovled this problem? Anyone has done it? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks!!!
