### ISSUE TITLE
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by chenjun2hao** [open-mmlab/mmdetection#1294]
when install mmdetection, i meet this issue.
the detail information is:
`cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/yangna/yangna/tool/anaconda2/envs/torch110/lib/python3.6/site-packages/torch/include -I/home/yangna/yangna/tool/anaconda2/envs/torch110/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/yangna/yangna/tool/anaconda2/envs/torch110/lib/python3.6/site-packages/torch/include/TH -I/home/yangna/yangna/tool/anaconda2/envs/torch110/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yangna/yangna/tool/anaconda2/envs/torch110/include/python3.6m -c mmdet/ops/nms/src/nms_kernel.cu -o build/temp.linux-x86_64-3.6/mmdet/ops/nms/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/usr/local/gcc-6.3/include/c++/6.3.0/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’:
/usr/local/gcc-6.3/include/c++/6.3.0/tuple:626:248:   required by substitution of ‘template<class ... _UElements, typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> = <missing>]’
/home/yangna/yangna/tool/anaconda2/envs/torch110/lib/python3.6/site-packages/torch/include/ATen/core/TensorMethods.h:1181:57:   required from here
/usr/local/gcc-6.3/include/c++/6.3.0/tuple:483:67: 错误：展开‘std::is_constructible<_Elements, _UElements&&>’时参数包长度不匹配
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
                                                                   ^~~~~
/usr/local/gcc-6.3/include/c++/6.3.0/tuple:484:1: 错误：body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’ not a return-statement
     }
 ^
/usr/local/gcc-6.3/include/c++/6.3.0/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_ImplicitlyMoveConvertibleTuple() [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, at::Tensor}]’:
/usr/local/gcc-6.3/include/c++/6.3.0/tuple:626:362:   required by substitution of ‘template<class ... _UElements, typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::tuple<at::Tensor, at::Tensor, at::Tensor>}; typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor, at::Tensor, at::Tensor>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor, at::Tensor, at::Tensor>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> = <missing>]’
/home/yangna/yangna/tool/anaconda2/envs/torch110/lib/python3.6/site-packages/torch/include/ATen/core/TensorMethods.h:1181:57:   required from here
/usr/local/gcc-6.3/include/c++/6.3.0/tuple:489:65: 错误：展开‘std::is_convertible<_UElements&&, _Elements>’时参数包长度不匹配
       return __and_<is_convertible<_UElements&&, _Elements>...>::value;
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
`
my Environment：
pytorch1.1.0
cuda9.0
gcc6.3

**Comment by chenjun2hao** [comment]
i have sovled this problem by change the gcc version, i change to gcc5.5

**Comment by Songtingt** [comment]
> i have sovled this problem by change the gcc version, i change to gcc5.5

it solves my error!!!
and aslo solves my another error in pytorch-faster-rcnn!!
thanku!!!!!!

**Comment by bufferXia** [comment]
> i have sovled this problem by change the gcc version, i change to gcc5.5

Think you!!! I solve this problem by change the gcc version 6 to  5 .

**Comment by guotong1988** [comment]
Thank you. I will try to change GCC 6 to 5
