### ISSUE TITLE
Config files for cascade_rcnn_hrnetv2p models

### ISSUE THREAD

**Issue by adampower48** [open-mmlab/mmdetection#1296]
Are there config files for the Cascade R-CNN HRNetV2p-W18 and HRNetV2p-W48 models?
If not, is there an easy way to to change the [HRNetV2p-W32](https://github.com/open-mmlab/mmdetection/blob/master/configs/hrnet/cascade_rcnn_hrnetv2p_w32_20e.py) config files to work with the other 2 models?
Thanks

**Comment by zhouhang95** [comment]
first, diff faster_rcnn_hrnetv2p_w18_1x.py faster_rcnn_hrnetv2p_w32_1x.py
then, modify cascade_rcnn_hrnetv2p
three item: pretrained, backbone and neck

**Comment by adampower48** [comment]
Thank you, that worked perfectly.
Here are the two files if anyone else needs them:
[cascade_rcnn_hrnetv2p_w18_20e](https://github.com/adampower48/AI-City-Anomaly-Detection/blob/master/mmdet_configs/cascade_rcnn_hrnetv2p_w18_20e.py)  
[cascade_rcnn_hrnetv2p_w48_20e](https://github.com/adampower48/AI-City-Anomaly-Detection/blob/master/mmdet_configs/cascade_rcnn_hrnetv2p_w48_20e.py)
