### ISSUE TITLE
KeyError: 'segmentation' 

### ISSUE THREAD

**Issue by vadik6666** [open-mmlab/mmdetection#1297]
For `cascade_rcnn_r50_fpn_1x.py `and custom dataset for detection only I've got 

```
File "/learning/other/mmdetection/mmdet/datasets/coco.py", line 87, in _parse_ann_info
gt_masks_ann.append(ann['segmentation'])
KeyError: 'segmentation' 
```

And after changing train_pipeline options:
`dict(type='LoadAnnotations', with_bbox=True, with_mask=False),`

This error still exist. I assume for COCO it works, because COCO has masks. But for detection dataset it doesn't work.

**Comment by vadik6666** [comment]
Maybe I should change my annotation file which looks like for some bbox:
```
{'area': 702.1057499999998,
 'iscrowd': 0,
 'image_id': 289343,
 'bbox': [473.07, 395.93, 38.65, 28.67],
 'category_id': 18,
 'id': 1768}
```
and add new key-value like `'segmentation': []`

**Comment by Aavesh** [comment]
I know the issue is closed but providing a better solution to this instead of messing with annotation file which can be difficult at times. Just change _C.MODE_MASK = None   in config.py.

**Comment by David-19940718** [comment]
@Aavesh 
Hello，can you tell me where is the config.py?

**Comment by CMobley7** [comment]
@Aavesh or @David-19940718, what config.py file are you referring to?

**Comment by naveenggmu** [comment]
@Aavesh is there a way to train models like retinaNet without providing masks? Also can you please tell where to find "config.py" that you have mentioned above.

**Comment by TonojiKiobya** [comment]
Try to Go to /mmdetection/mmdet/datasets/coco.py" and disable all pieces of code which refer to segmentation. such as
#gt_masks_ann = []
#gt_masks_ann.append(ann['segmentation'])
#masks=gt_masks_ann,

Then see how it will turn out
