### ISSUE TITLE
about background class

### ISSUE THREAD

**Issue by flyfj** [open-mmlab/mmdetection#1298]
In training on a new dataset, we set num_classes to actual class number + 1 (background). how are the bg samples created?

**Comment by ZwwWayne** [comment]
Please refer the [codebase conventions](https://mmdetection.readthedocs.io/en/latest/compatibility.html#codebase-conventions).

**Comment by hubutui** [comment]
@ZwwWayne Hey, I check the link above, and I'm still confused. For eg, I have `person, dog, cat, background` in my custom dataset, then I need to set `num_classes=3`, and set `classes.txt`:
```
person
dog
cat
```
Am I right? However, during evaluation in training
```
+------------+-----+------+--------+-------+
| class      | gts | dets | recall | ap    |
+------------+-----+------+--------+-------+
| person     | 0   | 0    | 0.000  | 0.000 |
| dog        | 149 | 653  | 0.000  | 0.000 |
| cat        | 14  | 0    | 0.000  | 0.000 |
+------------+-----+------+--------+-------+
| mAP        |     |      |        | 0.000 |
+------------+-----+------+--------+-------+
```
But my actual gt: person - 149, dog - 14, cat - 0.
