### ISSUE TITLE
--show(cv2.error)

### ISSUE THREAD

**Issue by Taylor-X76** [open-mmlab/mmdetection#1305]
cv2.error: OpenCV(4.1.0) /io/opencv/modules/highgui/src/window.cpp:627: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

**Comment by HsiaoChungYen** [comment]
> cv2.error：OpenCV（4.1.0）/io/opencv/modules/highgui/src/window.cpp:627：錯誤：（-2：未指定錯誤）該功能未實現。在Windows，GTK + 2.x或Cocoa支持下重建庫。如果您使用的是Ubuntu或Debian，請安裝libgtk2.0-dev和pkg-config，然後重新運行cmake或在功能'cvShowImage'中配置腳本


I also encountered the same problem, not only imshow, Moreover namedWindow noveWindow  resizeWindow all the same mistakes, I feel very troubled......

**Comment by akankshanb** [comment]
I encountered the same issue. Even after uninstalling opencv and writing  conda install -c menpo opencv I get the same error

**Comment by wen0618** [comment]
I met the same problem today,and solved it by:

pip install opencv-contrib-python
python setup.py develop

Hope it will help you.

**Comment by zhaohui-yang** [comment]
> I met the same problem today,and solved it by:
> 
> pip install opencv-contrib-python
> python setup.py develop
> 
> Hope it will help you.

it helps, thanks
