### ISSUE TITLE
HTC memory grows also after closing issue#1185

### ISSUE THREAD

**Issue by michaelyyq** [open-mmlab/mmdetection#1308]
reopen the #1185 

The GPU memory grows anyway. The size of epoch_3 is 561.1MB， after stopping, resumming the checkpoint and training one epoch more, the size of epoch_4 becomes 934.3MB，while epoch_5 is 1.02GB correspondingly. I checkout the checkpoint '*.pth' file， let variable weight be the dict loaded from the file, I find that the length of weight['optimizer']['state'] become bigger and bigger when I resume the checkpoint and save it.  After some trials, I guess that the 'momentum_buffer' in weight['optimizer']['state'] become more and more while training proceeds, because the length of 
weight['optimizer']['state'] changes from 208 of epoch_3 to 862 of epoch and each of the weight['optimizer']['state'] is a large tensor named 'momentum_buffer'.

I don't find the same problem when I train MS RCNN model with the same dataset.
I don't know why the 'momentum_buffer' become more while training and make gpus memory leak even without mstrain.

**Comment by michaelyyq** [comment]
I don't find the same problem when I train MS RCNN model with the same dataset.
I don't know why the 'momentum_buffer' become more while traing and make gpus memory leak.

**Comment by BlakeXiaochu** [comment]
same problem~

**Comment by hhaAndroid** [comment]
Is there still a problem with the latest version now?

**Comment by AronLin** [comment]
According to our latest training log, this problem did not reappear.
