### ISSUE TITLE
Where can I find the site for downloading the pretrained models

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#1310]
Hi, Kai,

A quick question, I'd like to download some pre-trained backbone models for training. This is because our sever cannot access the Internet due to some complicated reasons. May I know the file in MMdetection that stores all downloading site of the pre-trained backbone?

Thank you!

**Comment by andresfp14** [comment]
Hi, 

If you go to a model, and search for the method `init_weights`, you will see that they use the function `load_checkpoint` from mmcv. After some short search, you get to
[mmcv/runner/checkpoint.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py). in it, you have a dict in line  17 containing all the urls of the pretrained models. I hope this is what you are looking for.

**Comment by shanggdlk** [comment]
> Hi,
> 
> If you go to a model, and search for the method `init_weights`, you will see that they use the function `load_checkpoint` from the library mmcv (other project from the same lab). After some short search, you get to
> [mmcv/runner/checkpoint.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py). in it, you have a dict in line 17 containing all the urls of the pretrained models. I hope this is what you are looking for.

Thank you so much, man!
