### ISSUE TITLE
A question about img_norm_cfg

### ISSUE THREAD

**Issue by jzchenriver** [open-mmlab/mmdetection#1311]
In faster_rcnn_r50_fpn_1x.py, there is the img_norm_cfg: dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True).
I want to know the reason why these numbers are chosen. Because my test dataset is infrared images, I think it is necessary to change this cfg.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/issues/796
