### ISSUE TITLE
[HTC] mismatch in semantic loss weght between implementation and paper

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#1315]
The default semantic loss weight in the paper is 1 but in implementation is [0.2](https://github.com/open-mmlab/mmdetection/blob/df1b90430444b19b263082337c2a02ea0369dc1e/configs/htc/htc_r50_fpn_20e.py#L105)

**Comment by hellock** [comment]
Seems that that's the case. I will check some early implementations to see the difference.
