### ISSUE TITLE
About LibraRCNN

### ISSUE THREAD

**Issue by vadik6666** [open-mmlab/mmdetection#1318]
I have read the paper but I have two questions about Libra RCNN.
1) Does it solve class imbalance problem in dataset (e.g. number of gt bboxes for some class is 1000 in trainset, and for other class 10000) ?
2) Does it solve the problem when some gt bboxes are not annotated in trainset (e.g. annotators forgot to annotate some objects, and it makes difficult to train model because it will be punished for finding this false positive objects during training)?

I assume the answer for both will be "No"

**Comment by hellock** [comment]
Yes you are right, the answer for both questions is "No". It only solves the imbalance issues as presented in the paper.

**Comment by vadik6666** [comment]
@hellock Thanks for the answer. 
I have one more question.
Currently I use "coco-pretrained retina" and config `libra+retina`, and results on validation are worse than "coco-pretrained retina" and config `retina`.
If I want to finetune coco-pretrained detector on mine dataset using `libra+retina` config do I have to use "coco-pretrained libra+retina" detector or I can use "coco-pretrained retina"?

**Comment by hellock** [comment]
It's better to use the corresponding pretrained checkpoint to the config.

**Comment by vadik6666** [comment]
@vadik6666 , thank you!
