### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Hi-Alvin** [open-mmlab/mmdetection#1323]
**Describe the bug**
When I used the config file named "cascade_rcnn_x101_64x4d_fpn_1x.py",  there is a checkpoint bug as the title.
the pretrained model was download from 
https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_64x4d-ee2c6f71.pth
and saved under /mmdetection/pretrained_models/

**Reproduction**
1. What command or script did you run?
```
run train.py under the tools dir in the IDE pycharm2019.03
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
transfer the path of config file, work dir and resume in main function  not by the terminal, the codes is as follows
def main(config_file, save_dir, resume):
    args = parse_args()
    args.config = config_file
    args.work_dir = save_dir
    args.resume_from = resume
    ...
if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = '7'
    config_file = '../configs/cascade_rcnn_x101_64x4d_fpn_1x.py'
    save_dir = '../save_dir/cascade_rcnn_x101_64x4d_fpn_1x'
    resume = '../pretrained_models/resnext101_64x4d-ee2c6f71.pth'
    main(config_file, save_dir, resume)

3. What dataset did you use?
my own dataset but was translated to coco format correctly, and it worked well in the maskrcnn-benchmark by facebook 

**Environment**
 - OS: [Ubuntu 16.04.5 LTS]
 - GCC [5.4.0]
 - PyTorch version [1.2.0]
- How you installed PyTorch [pip]
- GPU model [RTX 2080Ti]
- CUDA and CUDNN version [10.1.168  7.5.0]

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "/data/Code/mmdetection/tools/train.py", line 116, in <module>
    main(config_file, save_dir, resume)
  File "/data/Code/mmdetection/tools/train_.py", line 108, in main
    logger=logger)
  File "/data/Code/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/data/Code/mmdetection/mmdet/apis/train.py", line 218, in _non_dist_train
    runner.resume(cfg.resume_from)
  File "/data/Anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 310, in resume
    self._epoch = checkpoint['meta']['epoch']
TypeError: list indices must be integers or slices, not str
```

**Comment by hellock** [comment]
This checkpoint is a pretrained weight on ImageNet, not a checkpoint for detection models, so that you cannot use `load_from`. If you just want to use the ResNeXt-101 as the backbone, there is no need to modify any codes, you can download the pretrained weight and put it in the default checkpoint folder of PyTorch, e.g., ~/.cache/torch/checkpoints.

**Comment by Hi-Alvin** [comment]
> This checkpoint is a pretrained weight on ImageNet, not a checkpoint for detection models, so that you cannot use `load_from`. If you just want to use the ResNeXt-101 as the backbone, there is no need to modify any codes, you can download the pretrained weight and put it in the default checkpoint folder of PyTorch, e.g., ~/.cache/torch/checkpoints.

Got it, thanks a lot.
