### ISSUE TITLE
MAP is 0 and predicted box almost same size as image

### ISSUE THREAD

**Issue by flyfj** [open-mmlab/mmdetection#1325]
I trained a model on a custom dataset, each class has about 300 annotations, the training accuracy starts very high like 95% and reaches at 97% quickly and loss doesn't change too much after. I used voc eval and get all 0 recall and precision for each class. When i visualize the prediction (with threshold of 0 otherwise no box is shown), i found the box is almost as big as the entire image. 

Does anyone know what is the reason and how to fix it? Thank you.

**Comment by bnumaomei** [comment]
I met the same problem, have you solved it?

**Comment by bnumaomei** [comment]
这是来自徐杨的自动回复邮件。
