### ISSUE TITLE
Is it possible to get normalized bbox coordinates from the inference_detector apis

### ISSUE THREAD

**Issue by ChandanVerma** [open-mmlab/mmdetection#1327]
I get the following results from the inference_detector API. Just wanted to enquire whether is it possible to get normalized bbox coordinates using some inbuilt function or do I need to write a custom function for the same.

array([[377.76096  , 254.91911  , 602.107    , 533.1789   ,   0.8144508]],
       dtype=float32),
 array([[2.5211449e+02, 4.9718927e+02, 3.4354926e+02, 6.1962537e+02,
         1.3233066e-01]], dtype=float32),
 array([[5.5296722e+02, 3.0450262e+02, 7.8253992e+02, 5.9926660e+02,
         1.2978064e-01],
        [2.5386581e+02, 4.9311365e+02, 3.3906073e+02, 6.1097095e+02,
         3.2496080e-01]], dtype=float32)

Thanks,
Chandan Verma

**Comment by hellock** [comment]
You mean normalizing the bboxes to [0, 1]? There is currently no builtin options and you need to implement it.

**Comment by mitming** [comment]
Hi, @hellock 

Is there any function like this in mmdet now?
