### ISSUE TITLE
fail to run python setup.py develop 

### ISSUE THREAD

**Issue by CZL-96** [open-mmlab/mmdetection#1328]
When I ran the command "python setup develop" to install mmdetection, the following problem occurred:

**czl@czl:~/mmdetection$ python setup.py develop
/home/czl/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '1.0.rc0+df1b904' to '1.0rc0+df1b904'
  normalized_version,
running develop

running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.nms.nms_cpu' extension
gcc -pthread -B /home/czl/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/czl/anaconda3/lib/python3.6/site-packages/torch/include -I/home/czl/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/czl/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/czl/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/czl/anaconda3/include/python3.6m -c mmdet/ops/nms/src/nms_cpu.cpp -o build/temp.linux-x86_64-3.6/mmdet/ops/nms/src/nms_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/czl/anaconda3/compiler_compat -L/home/czl/anaconda3/lib -Wl,-rpath=/home/czl/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/mmdet/ops/nms/src/nms_cpu.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.6/mmdet/ops/nms/nms_cpu.cpython-36m-x86_64-linux-gnu.so
/home/czl/anaconda3/compiler_compat/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1**

**Comment by CZL-96** [comment]
My environment is
unbuntu 18.04
python：3.7
cuda10.0
pytorch：1.2.0

This problem has been bothering me for a long time Could anyone help me? Thanks~

**Comment by hellock** [comment]
You need to check the CUDA environment and see if the libraries are correctly installed and can be found in system paths.

**Comment by CZL-96** [comment]
Thank you. Problem solved. The reason is that I don't have cuda installed in my conda virtual environment.
