### ISSUE TITLE
data question

### ISSUE THREAD

**Issue by johnlanbor** [open-mmlab/mmdetection#1330]
mmdet/dataset/pipeline/transformer.py  in Resize _resize_bboxes function:
I found result format is like this:
{'img_info': {'height': 1000, 'width': 2446, 'id': 1795, 'file_name': 'a68780d9344d16861208254265.jpg', 'filename': 'a68780d9344d16861208254265.jpg'}, 'ann_info': {'bboxes': array([[  14.53,    6.92, 2443.25,  823.74]], dtype=float32), 'labels': array([14]), 'bboxes_ignore': array([], shape=(0, 4), dtype=float32), 'masks': [[[14.53, 6.92, 2444.25, 6.92, 2444.25, 824.74, 14.53, 824.74]]], 'seg_map': 'a68780d9344d16861208254265.png'}, 'img_prefix': 'a', 'seg_prefix': None, 'proposal_file': None, 'bbox_fields': [], 'mask_fields': [], 'filename': '5.jpg', 'img': array( , dtype=uint8), 'img_shape': (800, 1957, 3), 'ori_shape': (1000, 2446, 3), 'gt_bboxes': array([[  14.53,    6.92, 2443.25,  823.74]], dtype=float32), 'gt_labels': array([14]), 'scale': (2000, 800), 'scale_idx': 0, 'pad_shape': (800, 1957, 3), 'scale_factor': 0.8, 'keep_ratio': True}

but for these lines:
        for key in results.get('bbox_fields', []):
            bboxes = results[key] * results['scale_factor']
            bboxes[:, 0::2] = np.clip(bboxes[:, 0::2], 0, img_shape[1] - 1)
            bboxes[:, 1::2] = np.clip(bboxes[:, 1::2], 0, img_shape[0] - 1)
            results[key] = bboxes
It seems you want to resize bbox  according to scale_factor, but bbox_fields does not in result keys, so I cant resize bbox?

so, I want to know ,when use dataset.__getitem__() function.
the gt bbox is the original box , or the resized bbox(eg , origion box * scale_factor)

**Comment by hellock** [comment]
The returned results are resized bboxes.
