### ISSUE TITLE
How to implement WeightedRandomSampler in Distributed training?

### ISSUE THREAD

**Issue by oljike** [open-mmlab/mmdetection#1331]
Do you have some guideline on how to use own Samplers in dataloaders? As far as i understand, currently only Random and Sequential samplers work.

**Comment by hellock** [comment]
You need to 1) implement your own sampler and 2) modify [`build_dataloader()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/loader/build_loader.py#L17).

**Comment by olzhaskabdolov** [comment]
@hellock  However, I don't understand the difference between DistributedGroupSampler and DistributedSampler, because they both have option to **shuffle** data. In https://github.com/open-mmlab/mmdetection/blob/0d5233a32dac4288760f6d819ddfef9c1e020cf7/mmdet/datasets/loader/build_loader.py#L26

**Comment by hellock** [comment]
For GroupSampler, we divide all samples into several groups (specifically 2 groups by aspect ratio). In each GPU, samples are guaranteed to be from the same group.
