### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_sigmoid_cls'

### ISSUE THREAD

**Issue by ds198799** [open-mmlab/mmdetection#1332]
**Hi, I just installed the latest version of mmdetection.  When I tried to train a customized model. Then I get the following error. Can you please help? Thanks!** Here is my command line: python mmdetection/tools/train.py configs/htc_dconv_c3-c5_mstrain_x101_64x4d_fpn_20e_1200x1900.py
 @hellock

2019-09-04 10:34:30,856 - INFO - Distributed training: False
Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 118, in <module>
    main()
  File "mmdetection/tools/train.py", line 94, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/models/detectors/htc.py", line 23, in __init__
    super(HybridTaskCascade, self).__init__(num_stages, backbone, **kwargs)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 41, in __init__
    self.rpn_head = builder.build_head(rpn_head)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/models/builder.py", line 35, in build_head
    return build(cfg, HEADS)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/home/hao/kaggle-imaterialist/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 16, in __init__
    super(RPNHead, self).__init__(2, in_channels, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_sigmoid_cls'

**Also, when I install the mmdetection, it shows the installation is successful (please see below). However, I did try to install the old version of mmdetection before I installed the latest version of the mmedetecion in the same conda environment. Would this be the reason that causes this issue? Thank you** 

  Running setup.py develop for mmdet
    Running command /home/hao/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/hao/kaggle-imaterialist/mmdetection/setup.py'"'"'; __file__='"'"'/home/hao/kaggle-imaterialist/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    copying build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/nms
    copying build/lib.linux-x86_64-3.7/mmdet/ops/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/nms
    copying build/lib.linux-x86_64-3.7/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/nms
    copying build/lib.linux-x86_64-3.7/mmdet/ops/roi_align/roi_align_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/roi_align
    copying build/lib.linux-x86_64-3.7/mmdet/ops/roi_pool/roi_pool_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/roi_pool
    copying build/lib.linux-x86_64-3.7/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/dcn
    copying build/lib.linux-x86_64-3.7/mmdet/ops/dcn/deform_pool_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/dcn
    copying build/lib.linux-x86_64-3.7/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/sigmoid_focal_loss
    copying build/lib.linux-x86_64-3.7/mmdet/ops/masked_conv/masked_conv2d_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/masked_conv
    Creating /home/hao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet.egg-link (link to .)
    Adding mmdet 1.0rc0+df1b904 to easy-install.pth file

    Installed /home/hao/kaggle-imaterialist/mmdetection
    /home/hao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '1.0.rc0+df1b904' to '1.0rc0+df1b904'
      normalized_version,
Successfully installed mmdet
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-02eax21q'

**Comment by hellock** [comment]
Your config file is outdated. You may refer to the new config files.

**Comment by ds198799** [comment]
@hellock Thank you very much!

**Comment by sisse008** [comment]
This did not solve the problem for me.
