### ISSUE TITLE
Question about the implementation of Double-Head RCNN

### ISSUE THREAD

**Issue by remilstl** [open-mmlab/mmdetection#1334]
First of all, thanks for this amazing project.

I was wondering why the implementation of Double-Head RCNN rescales the ROI before extracting the features for the bbox regression head. I read the paper and I have not noticed this implementation detail, and it appears to me this is the main reason why we can't use DoubleConvFCBBoxHead with other detectors (e.g. Cascade RCNN). While I can imagine giving a bigger ROI to the conv. head improves result, I am curious to hear if any study was done to measure the impact of this change when compared to using the same features for the fc head and the conv. head.

**Comment by hellock** [comment]
We got this implementation detail from the authors. It is not in the paper but used in the original implementation, which will bring 0.4~0.5 mAP improvement.

**Comment by remilstl** [comment]
Perfect! Thanks for the quick answer!

**Comment by yhs95** [comment]
I combine cascade with double and the performance is poor. Do you combine the two? How is the performance? Can you tell me the key details of their combination?

**Comment by yhs95** [comment]
I combine Cascade RCNN with Double-Head RCNN and the performance is poor. Do you combine the two? How is the performance? Can you tell me the key details of their combination?

**Comment by sciencestarstar** [comment]
> I combine Cascade RCNN with Double-Head RCNN and the performance is poor. Do you combine the two? How is the performance? Can you tell me the key details of their combination?

请问如何将Cascade RCNN加入Double-Head RCNN，我尝试失败了。
dear yhs95, can you hepl me how to add cascade RCNN to double head RCNN. My attempt failed.

**Comment by zhaoxin111** [comment]
I have tried to combine the cascade rcnn with double head and trained the model on my own dataset,the result is poor too.

**Comment by CUMTLZ** [comment]
> 我将Cascade RCNN与Double-Head RCNN结合使用，性能很差。您将两者结合起来吗？表现如何？您能告诉我他们组合的关键细节吗？


> I combine Cascade RCNN with Double-Head RCNN and the performance is poor. Do you combine the two? How is the performance? Can you tell me the key details of their combination?

请问怎么在cascadercnn中用doublehead呀？能分享一下吗

**Comment by CUMTLZ** [comment]
> I have tried to combine the cascade rcnn with double head and trained the model on my own dataset,the result is poor too.

dear zhaoxin111, can you hepl me how to add cascade RCNN to double head RCNN. My attempt failed.

**Comment by zhaoxin111** [comment]
> > I have tried to combine the cascade rcnn with double head and trained the model on my own dataset,the result is poor too.
> 
> dear zhaoxin111, can you hepl me how to add cascade RCNN to double head RCNN. My attempt failed.

我记得直接组合配置吧，好像没什么特别设置的

**Comment by Bin-ze** [comment]
> 我尝试将级联 rcnn 与双头结合起来，并在我自己的数据集上训练模型，结果也很差。

Can you tell me how to add double_head to cascadeRcnn, I changed the configuration file, but it failed

**Comment by hellmo718** [comment]
> > > I have tried to combine the cascade rcnn with double head and trained the model on my own dataset,the result is poor too.
> > 
> > 
> > dear zhaoxin111, can you hepl me how to add cascade RCNN to double head RCNN. My attempt failed.
> 
> 我记得直接组合配置吧，好像没什么特别设置的

我配置失败了，其中roi head 的类型是设置为cascaderoihead 还是doubleheadroihead呢，然后在cascade rcnn中添加reg_roi_scale_factor=1.3这个配置不成功呢。请问你是怎么配置的，能分享一下你的配置吗？谢谢

**Comment by wzr0108** [comment]
> > > > I have tried to combine the cascade rcnn with double head and trained the model on my own dataset,the result is poor too.
> > > 
> > > 
> > > dear zhaoxin111, can you hepl me how to add cascade RCNN to double head RCNN. My attempt failed.
> > 
> > 
> > 我记得直接组合配置吧，好像没什么特别设置的
> 
> 我配置失败了，其中roi head 的类型是设置为cascaderoihead 还是doubleheadroihead呢，然后在cascade rcnn中添加reg_roi_scale_factor=1.3这个配置不成功呢。请问你是怎么配置的，能分享一下你的配置吗？谢谢

请问你解决了吗

**Comment by Bin-ze** [comment]
我之前成功了，不仅需要修改配置文件，你需要debug到股东的位置去查看那里的输出，我当时经过少量的代码修改成功实现了，但是，我可以很负责任的告诉你们，这样的效果提升是有限的，而带来的模型的重量确是罕见的，你可以仔细查看双头模型，你会发现他很重，在cacade起来，那么它将是一个巨无霸，喔经过一系列实验放弃了，因为我的认知一直是简约才优美，如果你希望实现这样的效果，就好好查看二阶段的代码吧，少量修改应该就可以达到了

发自我的iPhone
