### ISSUE TITLE
Include Background images while training

### ISSUE THREAD

**Issue by pkhigh** [open-mmlab/mmdetection#1335]
When can we expect to see this feature?

Is there any head start which I can work on to add this feature while training?

**Comment by XGuider** [comment]
@pkhigh Have you successfully implemented it?

**Comment by pkhigh** [comment]
No, But I am willing to collaborate and work on a soution for this.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/pull/1531
