### ISSUE TITLE
The key from the mmdet pre-training model does not match module.state_dict()

### ISSUE THREAD

**Issue by gfjiangly** [open-mmlab/mmdetection#1337]
in mmcv load_checkpoint function:
```python
    # load state_dict
    if hasattr(model, 'module'):
        load_state_dict(model.module, state_dict, strict, logger)
    else:
        load_state_dict(model, state_dict, strict, logger)
```
When using the pre-trained model, for example, in config file pretrained='./work_dirs/mask_rcnn_r50_fpn_2x/epoch_6.pth',  the program enters the else branch, there is no ‘backbone’ in the key string of module.state_dict(), but there is ‘backbone’ in the pretrain model file.

![module state_dict](https://user-images.githubusercontent.com/38396233/64310577-2fe38600-cfd3-11e9-9a57-820533fa2a51.png)

![pretrain model state_dict](https://user-images.githubusercontent.com/38396233/64310593-3e31a200-cfd3-11e9-9eb1-251d6e1ea485.png)

**Comment by biebiewang** [comment]
There is a hacky way. Please try to set pretrained=None  in config file, maybe it will work.
I checked code to figure out why it works but failed. Please let me know if you have any cue.

**Comment by biebiewang** [comment]
btw, you need to set load_from/resume_from in config file.

**Comment by gfjiangly** [comment]
> There is a hacky way. Please try to set pretrained=None in config file, maybe it will work.
> I checked code to figure out why it works but failed. Please let me know if you have any cue.

Probably the ‘pretrained’ parameter in config can only be used in official pre-trained models, which is a bit surprising.  This requirement that loads the backbone weight of the model trained from mmdet can be partially solved by the ‘load_from’ parameter. Thanks for your help.
