### ISSUE TITLE
Resize shape passed twice in Cityscapes config file

### ISSUE THREAD

**Issue by anirudh-chakravarthy** [open-mmlab/mmdetection#1342]
Hi,

I was going through the code, and curiously found that the shape is passed twice to Resize, in the cityscapes config file [here.](https://github.com/open-mmlab/mmdetection/blob/master/configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py#L123).

Is this intentional? If so, what is the reason for this?

Additionally, I am trying to use a Cityscapes-like dataset. So, would I need to pass the shape twice (as in the existing config), or only once?

**Comment by hellock** [comment]
This means multiscale training.

**Comment by lxtGH** [comment]
The second is left for multiscale training

**Comment by anirudh-chakravarthy** [comment]
Thank you for your help.
