### ISSUE TITLE
Questions about Guide Anchoring

### ISSUE THREAD

**Issue by hero-y** [open-mmlab/mmdetection#1343]
Hello,in the ga_loc_target function,the loc_avg_factor =  sum([t.size(0) * t.size(-1) * t.size(-2) for t in all_loc_targets]) / 200,I don't understand what 200 stands for.
And I think the log_avg_factor should be the sum of positive regions and negative regions.
Can you explain it for me? Thanks!

**Comment by hellock** [comment]
It is a hard-coded hyper parameter to balance the loss value.
