### ISSUE TITLE
How do I use a pretrained htc model for prediction?

### ISSUE THREAD

**Issue by shraddhaamohan** [open-mmlab/mmdetection#1344]
I want to use the pretrained htc model for prediction on a set of images. 
When I just download the model and add it to the would be workdirs specified in the config file, it tells me that the model.pth file is not a checkpoint file. 
What is the correct way of going about this? 

Is there a more detailed read me in regards to the config file for htc ?

**Comment by hellock** [comment]
You may refer to the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#inference-with-pretrained-models).

**Comment by shraddhaamohan** [comment]
Thanks I was able to find what I needed.
