### ISSUE TITLE
Maybe retinanet test stage in bbox_nms.py exists bug??

### ISSUE THREAD

**Issue by cxfwdz** [open-mmlab/mmdetection#1346]
the code 
""""
 for i in range(1, num_classes):
        cls_inds = multi_scores[:, i] > score_thr
        if not cls_inds.any():
            continue
""""
 in the "mmdet/core/post_processing/bbox_nms.py";
if I use retinanet model and use sigmoid， the code is
""""
        if self.use_sigmoid_cls:
            self.cls_out_channels = num_classes - 1
        else:
            self.cls_out_channels = num_classes
"""""
suppose I have six classes, now the cls_out_channels should be five, the problem is that in bbox_nms can not obtain the first class score? Looking forward to solution， Thanks。

**Comment by cxfwdz** [comment]
I have validated, the problem would not have effect on the results

**Comment by hellock** [comment]
The first channel corresponds to background.
