### ISSUE TITLE
Format of bboxes in object detection models

### ISSUE THREAD

**Issue by ChandanVerma** [open-mmlab/mmdetection#1347]
Wanted to know the bbox format of object detection models 
Is it xmin, xmax, ymin, ymax OR
xmin, ymin, xmax, ymax?

Thanks

**Comment by hellock** [comment]
xmin, ymin, xmax, ymax

**Comment by d12306** [comment]
@hellock , @ChandanVerma , say if I have a matrix [a,b], so here the xmin and xmax is defined in terms of column b right?
