### ISSUE TITLE
Repeat Dataset parameter in config file

### ISSUE THREAD

**Issue by anirudh-chakravarthy** [open-mmlab/mmdetection#1348]
Hi, 

I was going through the Cityscapes Mask R-CNN [config file.](https://github.com/open-mmlab/mmdetection/blob/master/configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py#L149) I came across the Repeat Dataset parameter, which is also present in the VOC configs but doesn't occur in COCO config files. 

Based on my experimentation, I concluded that the parameter `times` loads the dataset by that multiple for each epoch. My question is, what is the necessity of this parameter? If I say, double this, can I reduce `total_epochs` by half (as it seems like actual epochs will be same for both cases) ?

**Comment by anirudh-chakravarthy** [comment]
From what I've been able to gather, `actual epochs = total_epochs * times`. I believe that increasing the parameter `times` will load the dataset faster than loading during repeating multiple independent epochs. 

Correct me if I'm wrong, but I think this issue is solved.

**Comment by dhananjaisharma10** [comment]
Just to add to your description, this is especially useful for small datasets.
