### ISSUE TITLE
Question about multi scale testing

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#135]
Thank you for sharing an awesome repo. I have a question relating to multi-scale testing. 
If i am not wrong, we can perform multi-scale testing by changing``img_scale=(1333, 800)`` in ``test`` dict.
However when i change ``img_scale`` to ``img_scale=[(400, 1400), (1200, 1400)``. I got worse mAP compare to single scale testing. 

Am i wrong somewhere? Can you show me the correct way to perform multiscale testing in your repo?
The below is the results that i tried:
Model: ``Faster-R-50-FPN-1x``
- Single-scale testing: 36.4 mAP
- Multi-scale testing: 35.5 mAP

Thank you!

**Comment by hellock** [comment]
The choice of multiple scales also matters. The two scales you choose is either two small or two large. If you choose `[(1400, 1000), (1400, 600)]`, the results should be much better. Of course you can add more scales for better performance.

**Comment by thangvubk** [comment]
Thank you for the quick reply. If i choose ``[(1400, 1000), (1400, 600)]``. The test scale will be randomly sampled between (1400, 1000) and (1400, 600) or it just is counted as two fixed scales.

**Comment by hellock** [comment]
During inference, scales are not random sampled, just the fixed values you specified.

**Comment by thangvubk** [comment]
I totally understand now. Thank you!

**Comment by chenxu93** [comment]
@hellock  it  seems this code base only support 2 scales when training and testing? It is right, and what are the differences between range model and value model?
![image](https://user-images.githubusercontent.com/42310082/53021418-214cdb80-3494-11e9-81ef-f95a3d1303b9.png)

**Comment by hellock** [comment]
The `value` mode supports arbitrary scales, and the `range` mode only needs two scales (min and max). The code should be already very clear.

**Comment by 01lin** [comment]
@thangvubk  I have a question about multi-scale testing. how to set multi-scale-testing? 
 when i change **img_scale=[(1000,600),(834,500)]**, i got the wrong code: TypeError: Scale must be a number or tuple of int, but got <class 'list'>. 
Can you help me ?  Thank you~
![image](https://user-images.githubusercontent.com/23114910/53397798-feb24980-39e2-11e9-9c6b-62bf645b1a1f.png)

**Comment by 01lin** [comment]
> @thangvubk I have a question about multi-scale testing. how to set multi-scale-testing?
> when i change **img_scale=[(1000,600),(834,500)]**, i got the wrong code: TypeError: Scale must be a number or tuple of int, but got <class 'list'>.
> Can you help me ? Thank you~
> ![image](https://user-images.githubusercontent.com/23114910/53397798-feb24980-39e2-11e9-9c6b-62bf645b1a1f.png)

I used the official test-image script:
![image](https://user-images.githubusercontent.com/23114910/53399203-77ff6b80-39e6-11e9-9def-d149b1ad3e11.png)

**Comment by chenxu93** [comment]
@01lin if you use the official test-image script: it only support one scale when you perform inference. If you want to perform multi-scale test, you should use test command like:
python tools/test.py <CONFIG_FILE> <CHECKPOINT_FILE> --gpus <GPU_NUM> --out <OUT_FILE>

**Comment by Beitadoge** [comment]
hi,,thanks the awesome code,,i  have a question:Could we train the model with multi-scale? if we can,,How could we do? Looking forward to your reply！Thanks.O(∩_∩)O
