### ISSUE TITLE
The model_urls go wrong 

### ISSUE THREAD

**Issue by hero-y** [open-mmlab/mmdetection#1352]
Hi,for resnet50_caffe,when I use origin url ,the terminal shows that Connection timed out.
So, I replace https://s3.ap-northeast-2.amazonaws.com/open-mmlab in the urls with https://open-mmlab.oss-cn-beijing.aliyuncs.com,the new url should be https://open-mmlab.oss-cn-beijing.aliyuncs.com/pretrain/third_party/resnet50_caffe-788b5fa3.pth,but it shows that This XML file does not appear to have any style information associated with it. The document tree is shown below.
Can you help me? Thanks

**Comment by hellock** [comment]
The aliyun mirror is not complete since it is too slow to upload to aliyun and often fails. Currently AWS hosts all models.
