### ISSUE TITLE
Question about Image Scale

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#1353]
Hi,
I have a data set that contains pictures of various sizes from 5000 X5000 pixels to 584x584 pixels. The format of the data set is PASCAL VOC. Config file for PASCAL VOC contains img_scale = (1000, 600). If I start the train with this config file, how do I use images larger than 1000X600 for training? Are the pictures resized and used for training? When I increase img_scale in config file, I get an out of memory error error. Please,  can someone explain this issue to me? Thanks

**Comment by hellock** [comment]
The scale is the resizing scale. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L11) for details.
