### ISSUE TITLE
No prediction found

### ISSUE THREAD

**Issue by bugbugKiller** [open-mmlab/mmdetection#1357]
I use the cascade_rcnn_hrnetv2p_w32_20e model, in the training stage ,everything is ok:
       Epoch [1][1150/1194]	lr: 0.02000, eta: 6:15:01, time: 0.990, data_time: 0.006, memory: 9773, loss_rpn_cls: 0.9262, loss_rpn_bbox: 0.5313, s0.loss_cls: 0.0464, s0.acc: 99.5059, s0.loss_bbox: 0.0059, s1.loss_cls: 0.0302, s1.acc: 99.6328, s1.loss_bbox: 0.0117, s2.loss_cls: 0.0085, s2.acc: 99.6758, s2.loss_bbox: 0.0003, loss: 1.5603
But in the validation stage, I got the output:
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4774/4774, 6.3 task/s, elapsed: 755s, ETA:     0s
    18	
    19	Loading and preparing results...
    20	No prediction found.
I need help.

**Comment by hellock** [comment]
This usually means the model is not trained well.

**Comment by bugbugKiller** [comment]
Thank you to repeat me

**Comment by bugbugKiller** [comment]
> 
> 
> This usually means the model is not trained well.

Thank you for your reply.

**Comment by lyuweiwang** [comment]
> This usually means the model is not trained well.

What dose it mean? Should I continue the training and wait for a better result.
