### ISSUE TITLE
No module named 'mmdet.datasets.utils'

### ISSUE THREAD

**Issue by andrey-nashi** [open-mmlab/mmdetection#1363]
I have updated the library to the latest version and started getting errors. At first related to CUDA. I rebuild the library with **python3 setup.py install** (also tried python3 setup.py develop). It ran successfully, yet when I try to use API or run training with **python3 tools/train myconfig.py** I get error:

`  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+c5c7ef9-py3.6-linux-x86_64.egg/mmdet/datasets/__init__.py", line 9, in <module>
    from .utils import random_scale, show_ann, to_tensor
ModuleNotFoundError: No module named 'mmdet.datasets.utils'
`

It seems like utils.py was removed and pipelines directory was added (mmdetection/mmdet/datasets/).
It exists in commit [043efc3](https://github.com/open-mmlab/mmdetection/tree/7bb38af46396d3829482a94b4bc5b49a747150cc/mmdet/datasets), removed in commit [0d5233a](https://github.com/open-mmlab/mmdetection/tree/0d5233a32dac4288760f6d819ddfef9c1e020cf7/mmdet/datasets) while pipelines are present.

**Comment by hellock** [comment]
I suppose that the version you are running is not the one you updated. There is no line like `from .utils import random_scale, show_ann, to_tensor` in the latest version.
