### ISSUE TITLE
How does the network know functions like NMS, topk() and IoU-pooling do not need backpropagation? 

### ISSUE THREAD

**Issue by YandanYang** [open-mmlab/mmdetection#1365]
How does the network know functions like NMS, topk() and IoU-pooling do not need backpropagation? 
Or do they also go through backpropagation?
I realize that NMS and IoU pooling are not coded in python. I don't know why? Is this for speeding up or for backpropagation?

**Comment by hellock** [comment]
- NMS does not support back propagation yet.
- What is IoU-pooling?
- CUDA extensions usually run faster than python implementations.

**Comment by YandanYang** [comment]
Thanks for your reply. 
I mean ROI pooling. And your answer helps a lot.

**Comment by hellock** [comment]
RoI Pooling supports bp.
