### ISSUE TITLE
"device-side assert triggered" error when training  ssd512 .

### ISSUE THREAD

**Issue by LifeIsSoSolong** [open-mmlab/mmdetection#1366]
Thanks for your contributions~
When training a "person" detector(only one class) using ssd512 config file,I get the error "Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed" and "device-side assert triggered" . 
However I  trained a "person" detector using faster rcnn config file well in the same way.

my train process:
0.prepare data
1.create my config file
I copy configs/ssd512_coco.py and change it following your project.(change num_classes=2 , change datt root)
2.create MyDataset class
create class MyDataset following your project.

![image](https://user-images.githubusercontent.com/31103865/64515869-fb97fe80-d31f-11e9-86d1-d5f22451ae6c.png)

change __init__.py following your project.
3.train

I have successfully trained a faster-rcnn person detector following your project, then I only changed config file from faster-rcnn to ssd512, the error happened.

![image](https://user-images.githubusercontent.com/31103865/64515496-45ccb000-d31f-11e9-9867-11410cabca15.png)

Who can give me some advice . thanks~

**Comment by LifeIsSoSolong** [comment]
I have tried the advice:
https://github.com/open-mmlab/mmdetection/issues/1300#issuecomment-526581241

It can work at the begin of training, but after a few iterations, the same error came again.

**Comment by LifeIsSoSolong** [comment]
> I have tried the advice:
> [#1300 (comment)](https://github.com/open-mmlab/mmdetection/issues/1300#issuecomment-526581241)
> 
> It can work at the begin of training, but after a few iterations, the same error came again.

it seems that my datasets have bug, but why faster-rcnn-person can be trained normally.

**Comment by LifeIsSoSolong** [comment]
it seems that torch.gather sometimes receiving an invalid index , but how to fix it ?

**Comment by LifeIsSoSolong** [comment]
I change lr from lr_original to lr_origial/8, then the error is solved. lr_original is the lr in original config file.
but I don't know why it works, anyone has some idea? 
I don't think my way solved the error rightly, just no error but maybe have other bugs

**Comment by hellock** [comment]
It seems the network is not converging as expected, and causes some internal errors.

**Comment by LifeIsSoSolong** [comment]
> It seems the network is not converging as expected, and causes some internal errors.

you are right.After changing lr to lr/8, the error is no longer arise, but the model is not converging as expected.After 3day training, the model can not work.
the loss curve as:
figure_1 is first epoch training log, and figure_2 is epoch2~epoch18

![Figure_1](https://user-images.githubusercontent.com/31103865/64931897-17465c00-d86e-11e9-98a6-f320c24e3b0a.png)
![Figure_2](https://user-images.githubusercontent.com/31103865/64931898-17465c00-d86e-11e9-8b85-ef8a36762e51.png)

It seems changing lr do not solve that error rightly, do you have any advice to solve that? thank you .

best wishes~

**Comment by LifeIsSoSolong** [comment]
the original training error:
![image](https://user-images.githubusercontent.com/31103865/64932283-67262280-d870-11e9-8348-1be23bfbcbc5.png)

**Comment by Surflyan** [comment]
I also meet this problem，is there solution？
