### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [open-mmlab/mmdetection#1369]
Hello I work on a Google Cloud Machine, and have problem for installation.
I follow the README file and installed all the dependencies. 
-----------------------------------------------------------------------------------
Description:    Ubuntu 16.04.3 LTS

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

PyTorch 1.2

NCCL 2

g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
---------------------------------------------------------------------------------------
After I run the setup.py, I got:

Best match: addict 2.2.1
Processing addict-2.2.1-py3.7.egg
addict 2.2.1 is already the active version in easy-install.pth

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/addict-2.2.1-py3.7.egg
Searching for PyYAML==5.1.2
Best match: PyYAML 5.1.2
Processing PyYAML-5.1.2-py3.7-linux-x86_64.egg
PyYAML 5.1.2 is already the active version in easy-install.pth

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/PyYAML-5.1.2-py3.7-linux-x86_64.egg
Searching for networkx==2.3
Best match: networkx 2.3
Processing networkx-2.3-py3.7.egg
networkx 2.3 is already the active version in easy-install.pth

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/networkx-2.3-py3.7.egg
Searching for imageio==2.5.0
Best match: imageio 2.5.0
Processing imageio-2.5.0-py3.7.egg
imageio 2.5.0 is already the active version in easy-install.pth
Installing imageio_download_bin script to /root/anaconda3/envs/open-mmlab/bin
Installing imageio_remove_bin script to /root/anaconda3/envs/open-mmlab/bin

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/imageio-2.5.0-py3.7.egg
Searching for PyWavelets==1.0.3
Best match: PyWavelets 1.0.3
Processing PyWavelets-1.0.3-py3.7-linux-x86_64.egg
PyWavelets 1.0.3 is already the active version in easy-install.pth

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/PyWavelets-1.0.3-py3.7-linux-x86_64.egg
Searching for setuptools==41.0.1
Best match: setuptools 41.0.1
Adding setuptools 41.0.1 to easy-install.pth file
Installing easy_install script to /root/anaconda3/envs/open-mmlab/bin

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages
Searching for urllib3==1.25.3
Best match: urllib3 1.25.3
Processing urllib3-1.25.3-py3.7.egg
urllib3 1.25.3 is already the active version in easy-install.pth

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/urllib3-1.25.3-py3.7.egg
Searching for idna==2.8
Best match: idna 2.8
Processing idna-2.8-py3.7.egg
idna 2.8 is already the active version in easy-install.pth

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/idna-2.8-py3.7.egg
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Processing chardet-3.0.4-py3.7.egg
chardet 3.0.4 is already the active version in easy-install.pth
Installing chardetect script to /root/anaconda3/envs/open-mmlab/bin

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg
Searching for certifi==2019.6.16
Best match: certifi 2019.6.16
Adding certifi 2019.6.16 to easy-install.pth file

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages
Searching for decorator==4.4.0
Best match: decorator 4.4.0
Adding decorator 4.4.0 to easy-install.pth file

Using /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages
Finished processing dependencies for mmdet==1.0rc0+unknown

--------------------------------------------------------------------------------------------
But when I run demo got problem:
![Screenshot from 2019-09-09 15-49-42](https://user-images.githubusercontent.com/26878250/64536460-7b6e9a80-d319-11e9-89bc-b0d8e2eda143.png)

**Comment by hellock** [comment]
The CUDA library is not found. You may add the library path to LD_LIBRARY_PATH.

**Comment by sunwencanUp** [comment]
> The CUDA library is not found. You may add the library path to LD_LIBRARY_PATH.

Add the library path to LD_LIBRARY_PATH,
export PATH=$PATH:/usr/local/cuda-9.0/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda-9.0/lib64

but the same problem happen, nothing changed.

Traceback (most recent call last):
  File "tools/test.py", line 18, in <module>
    from mmdet.apis import init_dist
  File "/home/kc/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/kc/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/kc/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/kc/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/kc/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/kc/mmdetection/mmdet/ops/__init__.py", line 7, in <module>
    from .nms import nms, soft_nms
  File "/home/kc/mmdetection/mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "/home/kc/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 4, in <module>
    from . import nms_cpu, nms_cuda
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by sunwencanUp** [comment]
> The CUDA library is not found. You may add the library path to LD_LIBRARY_PATH.

libcudart.so.10.1 is cuda10 file？ My cuda is 9.

And I locate the libcudart.so.10.1 file, then copy the file to /usr/local/cuda-9.0/lib64. The problem is fixed. But,

(open-mmlab) root@kc-PowerEdge-T630:/home/kc/mmdetection# locate libcudart.so
/root/anaconda3/envs/open-mmlab/lib/libcudart.so
/root/anaconda3/envs/open-mmlab/lib/libcudart.so.9.2
/root/anaconda3/envs/open-mmlab/lib/libcudart.so.9.2.148
/root/anaconda3/pkgs/cudatoolkit-10.1.168-0/lib/libcudart.so
/root/anaconda3/pkgs/cudatoolkit-10.1.168-0/lib/libcudart.so.10.1
/root/anaconda3/pkgs/cudatoolkit-10.1.168-0/lib/libcudart.so.10.1.168
/root/anaconda3/pkgs/cudatoolkit-9.2-0/lib/libcudart.so
/root/anaconda3/pkgs/cudatoolkit-9.2-0/lib/libcudart.so.9.2
/root/anaconda3/pkgs/cudatoolkit-9.2-0/lib/libcudart.so.9.2.148
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0.176
