### ISSUE TITLE
assert rois.size(1) == 4 or rois.size(1) == 5

### ISSUE THREAD

**Issue by kaikaizhu** [open-mmlab/mmdetection#1372]
File "/home/123/torch-yolo/mmdetection-master/mmdet/models/bbox_heads/bbox_head.py", line 223, in regress_by_class
    assert rois.size(1) == 4 or rois.size(1) == 5
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by hellock** [comment]
You may check the RoI size.

**Comment by sjiki** [comment]
Same problem.
Do you have any solution?

**Comment by kyrielzy** [comment]
I have the same problem.

**Comment by ciwei123** [comment]
@kaikaizhu @sjiki @kyrielzy The same problem, can you tell me how you solved it？Thank you very much!!

**Comment by abfleishman** [comment]
I am also running into this issue...
