### ISSUE TITLE
TypeError when train Faster r-cnn with OHEM

### ISSUE THREAD

**Issue by zhengjiawen** [open-mmlab/mmdetection#1373]
When I train Faster r-cnn with OHEM on my custom dataset, error " missing 1 required positional argument: 'context'" occured.

config:
```
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(
            type='OHEMSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='soft-nms', iou_thr=0.5, min_score=0.05), max_per_img=100)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)
)
```
Please tell me how to use OHEM correctly, thanks.

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by zhengjiawen** [comment]
@hellock 
Here it is, thanks for any help!

Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I train Faster r-cnn with OHEM on my custom dataset, error " missing 1 required positional argument: 'context'" occured.

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=4,5,6,7 ./tools/dist_train.sh \
    ./configs/faster_rcnn_ohem_r50_fpn_1x.py \
    4 \
    --validate \
    --autoscale-lr  \
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I modified the number of classe, dataset type and paths, and add soft_nms. No changes in code.
3. What dataset did you use?
My own dataset.

**Environment**
 - OS:  Ubuntu 16.04.6
 - GCC 5.4.0
 - PyTorch version 1.1.0
- How you installed PyTorch conda
- GPU model TitanXp
- CUDA  9.0  CUDNN 7.0
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
 missing 1 required positional argument: 'context'
```

**Comment by JosonChan1998** [comment]
@zhengjiawen hi! 
I have the same problem.How can you fix it  ?

**Comment by Sencc** [comment]
I had the same problem.
