### ISSUE TITLE
Segmentation network evaluation error (KeyError: 0)

### ISSUE THREAD

**Issue by RaymondKirk** [open-mmlab/mmdetection#1376]
Running [test.py](https://github.com/open-mmlab/mmdetection/blob/8d010d7de9c2643e715aaf6033ff7fd5c60ebdc2/tools/test.py) with `bbox segm` eval options on instance segmentation networks results in `data['score'] = float(mask_score[i]) (KeyError: 0)` in the [coco_utils.py](https://github.com/open-mmlab/mmdetection/blob/8d010d7de9c2643e715aaf6033ff7fd5c60ebdc2/mmdet/core/evaluation/coco_utils.py#L154) file.

Command executed (independant of dataset used)

```bash
python tools/test.py configs/mask_rcnn_r50_fpn_1x.py work_dirs/mask_rcnn_r50_fpn_1x/latest.pth --out results.pkl --eval bbox segm
```

**Environment**
 -  Ubuntu 16.04.6
 - PyTorch version 1.1.0

**Error traceback**
```
Traceback (most recent call last):
  File "/home/user/mmdetection/tools/test.py", line 224, in <module>
    main()
  File "/home/user/mmdetection/tools/test.py", line 201, in main
    result_files = results2json(dataset, outputs, args.out)
  File "/home/user/mmdetection/mmdet/core/evaluation/coco_utils.py", line 170, in results2json
    json_results = segm2json(dataset, results)
  File "/home/user/mmdetection/mmdet/core/evaluation/coco_utils.py", line 154, in segm2json
    data['score'] = float(mask_score[i])
KeyError: 0
```

Possible clone of malformed issue https://github.com/open-mmlab/mmdetection/issues/1140.

**Comment by yhcao6** [comment]
I download the [`mask R-50-FPN`](https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth) model from modelzoo and execute the same test command with you. However, there is no error.

May I ask if you have modified something? If not, could you replace your `lastest.pth` with the [model](https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth) provided in modelzoo and try again?

**Comment by RaymondKirk** [comment]
Yes, change the number of classes to 2 in the config file (3 including background). Sorry this should have been included in my original message. You can’t have exactly two classes because the check in coco_utils (see the PR) checks if len(seg) == 2.

**Comment by RaymondKirk** [comment]
The code states that some detectors use different score for det and segm, so we need a more reliable way to see if this is the case. Just checking the seg length is insufficient because it’s length can also depend on the number of classes.

**Comment by yhcao6** [comment]
This is really a bug. 
But this pr misses a situation when `len(seg) == 2` and `len(dataset.CLASSES) == 2`

**Comment by RaymondKirk** [comment]
Changed the PR to check the length of the bounding boxes again the segm results instead (not perfect still, but way better than having no check at all)

**Comment by yhcao6** [comment]
If detector uses different score for det and segm, then seg[0] is segm, seg[1] is score.
`seg[0]` is a list of list, `label` is an integer, `label in seg[0]` will always be False.

**Comment by RaymondKirk** [comment]
Added to PR.

**Comment by yhcao6** [comment]
Why condition `label in seg[0]` will always be True when detectors use a different score for det and segm? You may have a check by testing [this config](https://github.com/open-mmlab/mmdetection/blob/master/configs/ms_rcnn/ms_rcnn_r50_caffe_fpn_1x.py).

**Comment by RaymondKirk** [comment]
Sorry I edited my comment (got it the wrong way round) tested to be working.

**Comment by RaymondKirk** [comment]
Pr ready to merge closing issue.
