### ISSUE TITLE
 OSError: ../checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth is not a checkpoint file 

### ISSUE THREAD

**Issue by GabbySuwichaya** [open-mmlab/mmdetection#1378]
I only want to test if it is working after installation by running 'inference_demo.ipnb'.

 **Describe the bug**

>  OSError: ../checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth is not a checkpoint file 

**Reproduction**
1. What command or script did you run?

model = init_detector(config_file, checkpoint_file, device='cuda:0')
 
 2. Did you make any modifications on the code or config? Did you understand what you have modified?

No. 

3. What dataset did you use?

No.

 
**Error traceback**
If applicable, paste the error trackback here.

 ---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-653ecd49b591> in <module>
      1 # build the model from a config file and a checkpoint file
----> 2 model = init_detector(config_file, checkpoint_file, device='cuda:0')

~/mmdetection/mmdet/apis/inference.py in init_detector(config, checkpoint, device)
     34     model = build_detector(config.model, test_cfg=config.test_cfg)
     35     if checkpoint is not None:
---> 36         checkpoint = load_checkpoint(model, checkpoint)
     37         if 'CLASSES' in checkpoint['meta']:
     38             model.CLASSES = checkpoint['meta']['CLASSES']

~/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py in load_checkpoint(model, filename, map_location, strict, logger)
    169     else:
    170         if not osp.isfile(filename):
--> 171             raise IOError('{} is not a checkpoint file'.format(filename))
    172         checkpoint = torch.load(filename, map_location=map_location)
    173     # get state_dict from checkpoint

OSError: ../checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth is not a checkpoint file 
---------------------------------------------------------------------------------------------------

**Comment by hellock** [comment]
Have you downloaded the corresponding checkpoint file?

**Comment by anirudh-chakravarthy** [comment]
Hi,

I faced the same error, and observed that passing the absolute path for the checkpoint worked for me. 

Hope it helps!

**Comment by GabbySuwichaya** [comment]
Thanks to both of you. And I am sorry for my late reply.  
The problem is fixed as it turns out that I forgot to download the checkpoint files.

**Comment by sunwencanUp** [comment]
> Thanks to both of you. And I am sorry for my late reply.
> The problem is fixed as it turns out that I forgot to download the checkpoint file

> Thanks to both of you. And I am sorry for my late reply.
> The problem is fixed as it turns out that I forgot to download the checkpoint files.

Where could I download the checkpoint files?

**Comment by QuaternaryKFC** [comment]
> > Thanks to both of you. And I am sorry for my late reply.
> > The problem is fixed as it turns out that I forgot to download the checkpoint file
> 
> > Thanks to both of you. And I am sorry for my late reply.
> > The problem is fixed as it turns out that I forgot to download the checkpoint files.
> 
> Where could I download the checkpoint files?

You can check the MODEL_ZOO.md to find them.

**Comment by zhangshen12356** [comment]
> > > Thanks to both of you. And I am sorry for my late reply.
> > > The problem is fixed as it turns out that I forgot to download the checkpoint file
> > 
> > 
> > > Thanks to both of you. And I am sorry for my late reply.
> > > The problem is fixed as it turns out that I forgot to download the checkpoint files.
> > 
> > 
> > Where could I download the checkpoint files?
> 
> You can check the MODEL_ZOO.md to find them.

.pth is the checkpoint file?

**Comment by anirudh-chakravarthy** [comment]
Yes, that is correct!

**Comment by NamrataSharma30** [comment]
I downloaded the checkpoint file, and provided an absolute path but still getting this error:

mask_rcnn_r50_caffe_fpn_poly_1x_coco_no_aug_compare_20200518-10127928.pth is not a checkpoint file

I got this error while training the model the first time.

**Comment by JihyeJung-Work** [comment]
@QuaternaryKFC  In what location should I download the .pth file? I know that it should be in /checkpoints folder, but it seems that I have to make this folder and I don't know where to make it....

**Comment by suhassatish** [comment]
@JihyeJung-Work , by running the example "demo/test_fashion_recommender.py", I figured out the paths should be these from the GIT_REPO_ROOT - 
checkpoint/FashionRecommend/TypeAware/disjoint/l2_embed/epoch_16.pth
checkpoint/resnet18.pth

**Comment by Yabing67** [comment]
> @QuaternaryKFC In what location should I download the .pth file? I know that it should be in /checkpoints folder, but it seems that I have to make this folder and I don't know where to make it....

in root folder
