### ISSUE TITLE
mutil-gpu train error about GHM

### ISSUE THREAD

**Issue by cxfwdz** [open-mmlab/mmdetection#1380]
no distribution multi-gpu train exists error in the code:
"inds = (g<= edges[i])&(g<edges[i+1])&vaild"

the error is
"arguments are located on different gpus at /pytorch/aten/THC/generic/THCTensorMathCompareT.cu:31"

**Comment by hellock** [comment]
@libuyu

**Comment by libuyu** [comment]
I never met with this and I don't think this is a bug of GHM. But I think [this discussion](https://discuss.pytorch.org/t/index-select-with-dataparallel-arguments-are-located-on-different-gpus/10229/7) and  https://github.com/pytorch/pytorch/issues/7405 can help you.

**Comment by Markovcom** [comment]
@cxfwdz hello, i also meet this problem, how to solve it?

**Comment by Markovcom** [comment]
@libuyu hello, register_buffer can not sovle this problem. There are other ways?

**Comment by hhaAndroid** [comment]
Is there still a problem with the latest version now?
