### ISSUE TITLE
The issue for the NASFPN module

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#1381]
In your recent NASFPN moule, I found the netwok type is RetinaNet. Have you ever tried the two-stage methods?  Also,the epoch in the configs is set 50. This parametre is solid or can be changed as 1x or 2x?

**Comment by hellock** [comment]
We do not have enough time and resource to try various settings and just reproduce the results in the paper. It can produce the possibility for users to further investigate it.

**Comment by keetsky** [comment]
I have fix it.

**Comment by dereyly** [comment]
@keetsky 
>> I have fix it.
interesting! what do you fix? 
constrain of square resolution?
