### ISSUE TITLE
training HTC out of memory? Any suggestions to save GPU memory during training?

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [open-mmlab/mmdetection#1382]
The GPU memory keeps growing during training，I try to add `del outputs` and call torch.cuda.empty_cache() in [mmcv, runner.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/runner.py#L272), it did work. 

Any other suggestions to save GPU memory during training? Thank you!

**Comment by BlueWings8** [comment]
I only have 2 RTX2080 (8G) ，can make a try ?

**Comment by hellock** [comment]
The best and most straight forward way is to use GPUs with larger memory.
Other methods that may be worth trying is 1) mixed precision (fp16) training, and 2) set `with_cp=True` in the backbone to use checkpointing. Even if 1) and 2) are used, there is still a minimum requirement for GPU memory, although I don't know the exact number.
