### ISSUE TITLE
Inference Speed of Mask R-CNN

### ISSUE THREAD

**Issue by Yuliang-Zou** [open-mmlab/mmdetection#1385]
I wonder why the FPS of ResNet-50-C4 is smaller than ResNet-50-FPN for Faster R-CNN and Mask R-CNN, while the FPS of ResNet-50-C4 is larger than ResNet-50-FPN for RPN.

**Comment by hellock** [comment]
You may take a closer look at the architecture. C4 Faster/Mask R-CNN is heavier than FPN, since there is a large head after RoI Align. For RPN, C4 model is more lightweight than FPN models.

**Comment by Yuliang-Zou** [comment]
Thanks so much! Is there a way to measure the inference time of each component of Faster R-CNN/Mask R-CNN? For example, feature extraction, RPN, box head, mask head, etc.

**Comment by hellock** [comment]
You can add timer in the forward method to measure the time cost of each step.
