### ISSUE TITLE
Using a pretrained model checkpoint for image classification

### ISSUE THREAD

**Issue by philno** [open-mmlab/mmdetection#1389]
I want to use a pretrained model checkpoint for image classification.
The problem I am trying to solve has different classes and bounding boxes don't matter. In particular, I do not have that much training data.
This is why I want to define my own head but use a pretrained backbone and neck. I have a few questions about the model architecture and implementation in mmdet.

I am able to load a given model checkpoint, for example FCOS X-101 from [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/README.md), with the high level api methods. Furthermore, I can get the `features` from the pretrained backbone and neck as follows:

```python
model = init_detector(configFile, checkpointFile, device='cuda:0')
image = torch.randn(1, 3, 256, 256).cuda()
features = model.extract_feat(image)
# how to get from features to n class predictions?
```

Inspection of the feature object reveals that it is a list of five tensors. In a regular neural network, I would expect a single tensor instead of a list.
Is this because FCOS is a feature pyramid network? How is a single class prediction computed from this list?

How can I design my own head that just predicts class probabilities for _n_ classes? Should I just delete the bbox and centerness properties from the [fcos_head](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/fcos_head.py)?
For example, would adding a pooling layer, flattening the results and using some kind of fully connected head be a valid alternative? How would I handle the features in that case, since I can not apply pooling to the list directly?

**Comment by ZwwWayne** [comment]
Please refer to the implementation of classifier in [mmclassification](https://github.com/open-mmlab/mmclassification).
