### ISSUE TITLE
MMDistributedDataParallel

### ISSUE THREAD

**Issue by HardLaugh** [open-mmlab/mmdetection#1393]
hello, Can someone explain ｀MMDistributedDataParallel｀, Compared to the official one, I am confused about the `forward` function is relatively simple: 1) only one  `_sync_params` before training; 2）where is the details of the distributed average_gradients from each devices. i can not find anything about the `dist_op` eg. reduce, all_reduce, gather and so on.
haha, just a newbaby about pytorch.

**Comment by hellock** [comment]
Here: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/utils/dist_utils.py#L54
