### ISSUE TITLE
How to modify the number of times to save checkpoints, or the code file,and latest.pth---- Is it the best checkpoint?

### ISSUE THREAD

**Issue by XGuider** [open-mmlab/mmdetection#1396]
Thks，your best work!! I meet a error!next......................
How to modify the number of times to save checkpoints, or the code file,and latest.pth---- Is it the best checkpoint?

**Comment by valuefish** [comment]
The default CheckpointHook code is in `mmcv/runner/hooks/checkpoint.py`, like this:
```python
class CheckpointHook(Hook):

    def __init__(self,
                 interval=-1,
                 save_optimizer=True,
                 out_dir=None,
                 **kwargs):
        self.interval = interval
        self.save_optimizer = save_optimizer
        self.out_dir = out_dir
        self.args = kwargs

    @master_only
    def after_train_epoch(self, runner):
        if not self.every_n_epochs(runner, self.interval):
            return

        if not self.out_dir:
            self.out_dir = runner.work_dir
        runner.save_checkpoint(
            self.out_dir, save_optimizer=self.save_optimizer, **self.args)
```
You can change `checkpoint_config` in your config file to modify the number of times to save checkpoints (e.g. `checkpoint_config = dict(interval=2)`, every 2 epoch save 1 time). Also you can define your own `CheckpointHook` class by inheriting `Hook` class.

 "latest.pth" is the last checkpoint, not the best.

**Comment by XGuider** [comment]
okay,i get.Thnx you so much!

> The default CheckpointHook code is in `mmcv/runner/hooks/checkpoint.py`, like this:
> 
> ```python
> class CheckpointHook(Hook):
> 
>     def __init__(self,
>                  interval=-1,
>                  save_optimizer=True,
>                  out_dir=None,
>                  **kwargs):
>         self.interval = interval
>         self.save_optimizer = save_optimizer
>         self.out_dir = out_dir
>         self.args = kwargs
> 
>     @master_only
>     def after_train_epoch(self, runner):
>         if not self.every_n_epochs(runner, self.interval):
>             return
> 
>         if not self.out_dir:
>             self.out_dir = runner.work_dir
>         runner.save_checkpoint(
>             self.out_dir, save_optimizer=self.save_optimizer, **self.args)
> ```
> 
> You can change `checkpoint_config` in your config file to modify the number of times to save checkpoints (e.g. `checkpoint_config = dict(interval=2)`, every 2 epoch save 1 time). Also you can define your own `CheckpointHook` class by inheriting `Hook` class.
> 
> "latest.pth" is the last checkpoint, not the best.

**Comment by XGuider** [comment]
@valuefish Thnx you so much!why i not found mmcv/runner/hooks/checkpoint.py in this repositories?

**Comment by valuefish** [comment]
It's in another project called `mmcv`, you can see [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py).

**Comment by XGuider** [comment]
okay,I get.Thnx so much!!!

**Comment by jamessergeant** [comment]
@valuefish Can you please elaborate on creating a custom CheckpointHook? From what I can tell you would need to modify mmcv in order to achieve this. Is there not a way to provide a custom hook class through the config?

**Comment by hellock** [comment]
@jamessergeant You don't need to modify anything MMCV, just to write your own hook and register it.
Specifically, you can replace `cfg.checkpoint_config` [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L249) with your own hook.

**Comment by jamessergeant** [comment]
Ah I see, I dug further into build_hook in mmcv and see now that it returns the custom Hook if passed in as the args. Thanks @hellock.

**Comment by bryanzhou008** [comment]
@valuefish Do you know how to save more often than once every epoch?

**Comment by sparshgarg23** [comment]
just curious if the default interval is set to -1,then does it mean that checkpoint will only be saved at the end of the training?
