### ISSUE TITLE
Multi-GPU training problems?

### ISSUE THREAD

**Issue by Sunnyheye** [open-mmlab/mmdetection#1400]
Hi,Dear authors:
Thanks for your great works!
I want to know about how to train with multi-GPUs which index is not consecutive，such as 0 and 2.

when I using following command :
`CUDA_VISIBLE_DEVICES=0,2 ./tools/dist_train.sh configs/cascade_rcnn_r50_fpn_1x.py 2`

it is still train model with GPUs named 0 and 1. But I want to train model with GPUs 0 and 2.
Could you please help me solve this problems? 
Thanks a lot!

**Comment by valuefish** [comment]
I just tried `CUDA_VISIBLE_DEVICES=0,2 tools/dist_train.sh configs/cascade_rcnn_r50_fpn_1x.py 2` , it can work for me.
