### ISSUE TITLE
mutil-gpu train problem

### ISSUE THREAD

**Issue by qianzhang2018** [open-mmlab/mmdetection#1402]
(open-mmlab) zq@ubuntu-server:/mnt/nfs/code/zq/all_mmdection$ sudo CUDA_VISIBLE_DEVICES=4,5,6 bash ./tools/dist_train.sh ./configs/retinanet_r50_fpn_1x.py 3

but i get this :
/usr/bin/python: No module named torch.distributed

**Comment by qianzhang2018** [comment]
i have solved it.

**Comment by yuyijie1995** [comment]
Can you tell me how did you solve it？

**Comment by ujsyehao** [comment]
@qianzhang2018  Can you say?

**Comment by nmxian** [comment]
CUDA_VISIBLE_DEVICES=0,2,3
python -m torch.distributed.launch --nproc_per_node=3 --master_port=29500 \
    tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py --launcher pytorch  may solve it.

**Comment by nmxian** [comment]
change python to python3 in the .sh file. I solve by it.
