### ISSUE TITLE
How to save the output images?

### ISSUE THREAD

**Issue by sicarioakki** [open-mmlab/mmdetection#1405]
Hey @hellock @tjsongzw @lindahua 
Can anyone guide me as to how to save the output images with detections?
Like i want to save all the output images in a directory once the inference code is run

**Comment by Sunnyheye** [comment]
@sicarioakki  
You can refer to this python file: mmdet/apis/inference.py -> show_result() , which can save the images of detection result to specified folder.

**Comment by DecentMakeover** [comment]
@sicarioakki if your issue is solved, please close the issue.

**Comment by hellock** [comment]
Feel free to reopen it if there is any further questions.

**Comment by scut-salmon** [comment]
Hi I found that the image is reshaped when saved, anyway I can do to save the original size of image

**Comment by YijianLiu** [comment]
have you saved this? thanks！

**Comment by reubencmoyo** [comment]
> have you saved this? thanks！

How do I save a video after visualising it?

**Comment by sisse008** [comment]
This should be reopened. There is no show_result() in version 2.4

**Comment by justinkeke91** [comment]
The code below can show and save image with result. 
--------------------------------------------------------------------------------------------------------------------------------

import mmcv
import os
import cv2
import numpy as np
from mmcv.runner import load_checkpoint
from mmdet.models import build_detector
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import matplotlib.pyplot as plt


config_file = '/home/en_ro/mmdata/mmdetection/configs/balloon/faster_rcnn_r50_fpn_1x_voc_cat0602.py'
checkpoint_file =  '/home/en_ro/mmdetection/work_dirs/faster_rcnn_r50_fpn_1x_voc_cat0602/epoch_100.pth'

model = init_detector(config_file,checkpoint_file)

img_dir = '/home/en_ro/mmdata/valdata_1/'
out_dir = 'results/'

if not os.path.exists(out_dir):
    os.mkdir(out_dir)
test_path = 'jpg0615.txt'
fp = open(test_path, 'r')
test_list = fp.readlines()

count = 0
imgs = [] 
img = '017-01_0034_o_S017-1_0035.JPG'
result = inference_detector(model,img)

show_result_pyplot(model, img, result, score_thr=0.6)# show  the image with result
model.show_result(img, result, out_file='0617.jpg')# save image with  result

**Comment by ahmetnihat** [comment]
# Note : Show_result_pyplot was removed after mmdet version 2.0. OpenCV imshow is used instead.

## import mmdet.apis module
from mmdet.apis import init_detector, inference_detector
from mmdet.registry import VISUALIZERS
import cv2
import mmcv

## path to model file
config_file = 'rtmdet_tiny_8xb32-300e_coco.py'
## path to weight file
checkpoint_file = 'rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth'

## create model and load weights
model = init_detector(config_file, checkpoint_file, device='cpu')

## init visualizer
visualizer = VISUALIZERS.build(model.cfg.visualizer)

## the dataset_meta is loaded from the checkpoint and
## then pass to the model in init_detector
visualizer.dataset_meta = model.dataset_meta

## path to the image you want to test
img = 'demo/demo.jpg'
img = cv2.imread(img)

## apply the model to the image and get the output
result = inference_detector(model, img)

img = mmcv.imconvert(img, 'bgr', 'rgb')
visualizer.add_datasample(
    name='result',
    image=img,
    data_sample=result,
    draw_gt=False,
    pred_score_thr=0.3,
    show=False)

img = visualizer.get_image()
img = mmcv.imconvert(img, 'bgr', 'rgb')

## Solution to your question: Save the image
cv2.imwrite('result', img) 
cv2.imshow('result', img)

cv2.waitKey(0)
