### ISSUE TITLE
AttributeError: 'ConcatDataset' object has no attribute 'img_ids'

### ISSUE THREAD

**Issue by lckdl** [open-mmlab/mmdetection#1406]
I try to use list for val:
```
ann_file=[data_root + 'annotations/instances_valid1.json',
           data_root + 'annotations/instances_valid2.json'],
img_prefix=[data_root + 'images/val1/',data_root + 'images/val2/'],
```
error: line 111, in det2json
AttributeError: 'ConcatDataset' object has no attribute 'img_ids'

How can I solve this problem?

**Comment by heejun8609** [comment]
I have same problem. I think that problems occur during concating dataset.

**Comment by gfjiangly** [comment]
You can evaluate multiple data sets separately or combine multiple test sets into one file, like: https://github.com/gfjiangly/cvtools/blob/master/cvtools/label_convert/coco/merge_coco.py

**Comment by lckdl** [comment]
> You can evaluate multiple data sets separately or combine multiple test sets into one file, like: https://github.com/gfjiangly/cvtools/blob/master/cvtools/label_convert/coco/merge_coco.py

@gfjiangly how to use MergeCOCO in mmdetection training val.
