### ISSUE TITLE
why is map so low in VOCDataset ? 

### ISSUE THREAD

**Issue by sbbug** [open-mmlab/mmdetection#1408]
+-------------+------+------+--------+-----------+-------+
| class       | gts  | dets | recall | precision | ap    |
+-------------+------+------+--------+-----------+-------+
| aeroplane   | 155  | 991  | 0.871  | 0.138     | 0.693 |
| bicycle     | 177  | 1331 | 0.910  | 0.122     | 0.701 |
| bird        | 243  | 1541 | 0.716  | 0.113     | 0.476 |
| boat        | 150  | 1881 | 0.780  | 0.063     | 0.435 |
| bottle      | 252  | 1360 | 0.722  | 0.134     | 0.564 |
| bus         | 114  | 1161 | 0.921  | 0.091     | 0.632 |
| car         | 625  | 2321 | 0.888  | 0.247     | 0.766 |
| cat         | 190  | 1630 | 0.921  | 0.108     | 0.609 |
| chair       | 398  | 3323 | 0.759  | 0.094     | 0.492 |
| cow         | 123  | 914  | 0.894  | 0.122     | 0.410 |
| diningtable | 112  | 1551 | 0.830  | 0.061     | 0.493 |
| dog         | 257  | 1917 | 0.930  | 0.125     | 0.530 |
| horse       | 180  | 1161 | 0.950  | 0.148     | 0.712 |
| motorbike   | 172  | 1105 | 0.930  | 0.147     | 0.730 |
| person      | 2332 | 9625 | 0.911  | 0.224     | 0.772 |
| pottedplant | 266  | 2054 | 0.703  | 0.092     | 0.389 |
| sheep       | 127  | 1023 | 0.787  | 0.098     | 0.467 |
| sofa        | 124  | 1314 | 0.903  | 0.089     | 0.543 |
| train       | 152  | 1702 | 0.967  | 0.087     | 0.680 |
| tvmonitor   | 158  | 1266 | 0.873  | 0.109     | 0.654 |
+-------------+------+------+--------+-----------+-------+
| mAP         |      |      |        |           | 0.587 |
+-------------+------+------+--------+-----------+-------+

my epoch is 12 dataset-version = voc2007

**Comment by miaoshuyu** [comment]
@sbbug which model you used? I used ssd300 and the map is 0.643

**Comment by zihaozhang9** [comment]
How can I output an evaluation log like the mAP above？very thanksa

**Comment by zihaozhang9** [comment]
How can I output an evaluation log like the mAP above?very thanks~
