### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xxliiiii** [open-mmlab/mmdetection#1409]
**Describe the bug**
I train on VOC dataset using deformable pooling function. And I run the tools/test.py without argument --eval to get the results.pkl, then try to run tools/voc_eval.py and raise IndexError: list index out of range.

**Reproduction**
1. What command or script did you run?
```
 python tools/voc_eval.py work_dirs/faster_rcnn_mdpool_r50_fpn_1x_VOC/results.pkl configs/dcn/faster_rcnn_mdpool_r50_fpn_1x_VOC.py
```
3. What dataset did you use?
parsal_VOC

**Environment**
 - OS: Ubuntu 18.04
 - GCC： 5.4.0
 - PyTorch version ：1.1.0
- How you installed PyTorch ：use the dockerfile
- GPU model：2080Ti
- CUDA and CUDNN version：cuda10.0 cudnn 7.5

**Error traceback**
Traceback (most recent call last):
  File "tools/voc_eval.py", line 62, in <module>
    main()
  File "tools/voc_eval.py", line 58, in main
    voc_eval(args.result, test_dataset, args.iou_thr)
  File "tools/voc_eval.py", line 43, in voc_eval
    print_summary=True)
  File "/workspace/mmdetection/mmdet/core/evaluation/mean_ap.py", line 328, in eval_map
    print_map_summary(mean_ap, eval_results, dataset)
  File "/workspace/mmdetection/mmdet/core/evaluation/mean_ap.py", line 371, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: list index out of range

**Comment by chrisjuniorli** [comment]
@xxliiiii  hi, have you solved the problem?

**Comment by lizxchen** [comment]
I met the same problem. And I change the num_classes  when I test. It also has this error. I should train again?Can you give me some advice?

**Comment by xxliiiii** [comment]
按理说应该要重新训练的呀，配置文件改了都要重新训练吧，我是重新训练了就没问题了的



发自我的iPhone


------------------ Original ------------------

**Comment by lizxchen** [comment]
谢谢大佬，我重新训练一下。




------------------ 原始邮件 ------------------
发件人: "xxliiiii"<notifications@github.com>; 
发送时间: 2019年10月1日(星期二) 下午3:20
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com>; 
抄送: "陈修"<1835427598@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [open-mmlab/mmdetection] IndexError: list index out of range(#1409)



按理说应该要重新训练的呀，配置文件改了都要重新训练吧，我是重新训练了就没问题了的 
 
 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------

**Comment by shenhongjuan** [comment]
我在训练只有一个类别的数据集时，测试IndexError: list index out of range错误，我将classesnum都进行了修改，不知道什么原因

**Comment by olaConge** [comment]
> 我在训练只有一个类别的数据集时，测试IndexError: list index out of range错误，我将classesnum都进行了修改，不知道什么原因

你解决这个问题了嘛，我也是训练一个类别

**Comment by Wenting-Xu** [comment]
> 按理说应该要重新训练的呀，配置文件改了都要重新训练吧，我是重新训练了就没问题了的 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: lizxchen <notifications@github.com&gt; Date: Tue,Oct 1,2019 3:16 PM To: open-mmlab/mmdetection <mmdetection@noreply.github.com&gt; Cc: xxliiiii <598903680@qq.com&gt;, Mention <mention@noreply.github.com&gt; Subject: Re: [open-mmlab/mmdetection] IndexError: list index out of range (#1409)

请问num_classes是要加上背景类的嘛？但是我修改了configs的num_classes，并加了背景类，同样出现了上面的错误

**Comment by rhythm-A** [comment]
> > 我在训练只有一个类别的数据集时，测试IndexError: list index out of range错误，我将classesnum都进行了修改，不知道什么原因
> 
> 你解决这个问题了嘛，我也是训练一个类别

can you tell me how to fix this problem?thx

**Comment by rhythm-A** [comment]
> 我在训练只有一个类别的数据集时，测试IndexError: list index out of range错误，我将classesnum都进行了修改，不知道什么原因

请问这个问题怎么解决?

**Comment by olaConge** [comment]
> > 我在训练只有一个类别的数据集时，测试IndexError: list index out of range错误，我将classesnum都进行了修改，不知道什么原因
> 
> 请问这个问题怎么解决?

很久以前的问题了，我也不太记得了，貌似是需要在类别的那个列表里加一个逗号，比如person类就得写成[person, ]
