### ISSUE TITLE
no print process

### ISSUE THREAD

**Issue by dfzsgjshzfj** [open-mmlab/mmdetection#1413]
te@te:/home/yuan/mmdetection$ python tools/train.py "/home/yuan/mmdetection/configs/mask_rcnn_r50_fpn_1x.py"
2019-09-18 12:00:40,278 - INFO - Distributed training: False
2019-09-18 12:00:40,879 - INFO - load model from: torchvision://resnet50
2019-09-18 12:00:41,126 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

2019-09-18 12:00:44,790 - INFO - Start running, host: te@te, work_dir: /home/yuan/mmdetection/work_dirs/mask_rcnn_r50_fpn_1x
2019-09-18 12:00:44,790 - INFO - workflow: [('train', 1)], max: 100 epochs
+++++++++++++++++++++++++++++++++++++++

From the beginning of the training to the end, the log and checkpoint can be generated, but there is no printing process.
How to make it print the train process if I wang to see？

**Comment by dfzsgjshzfj** [comment]
I found the reason, the log generation interval is too large, change the interval in log_config can solve the problem

**Comment by dfzsgjshzfj** [comment]
I found the reason, the log generation interval is too large, change the interval in log_config can solve the problem

**Comment by zhaojw219** [comment]
Hello.I met the similar problem.When I use distributed training,there is no print.And the model is bad,it seems that the model learned nothing.Can you help me?

**Comment by dfzsgjshzfj** [comment]
> Hello.I met the similar problem.When I use distributed training,there is no print.And the model is bad,it seems that the model learned nothing.Can you help me?

Sorry, I only have one gpu and have not tried distributed training. Your model can work in single gpu？If so, maybe I don't know how to solve your problem.

**Comment by KaihuaTang** [comment]
> Hello.I met the similar problem.When I use distributed training,there is no print.And the model is bad,it seems that the model learned nothing.Can you help me?

I also found this weird bug that the logger won't print out anymore.  It takes me a long time to figure out that it's caused by the logger.HasHandlers() function, which always returns the True even the logger.handlers = [], so I change it to len(logger.handlers) > 0, then  the problem is solved.
