### ISSUE TITLE
An error occured when run coco_eval.py?

### ISSUE THREAD

**Issue by jshuzi** [open-mmlab/mmdetection#1415]
When i run the command: python tools/coco.eval.py result.pkl --ann ./data/coco/annotations/instances_val2017.json, an error occured: 
typeerror: string indices must bu integers,
Is my command wrong? How to use the coco_eval.py?

**Comment by jshuzi** [comment]
choices=['proposal_fast', 'proposal', 'bbox', 'segm', 'keypoint'], so the input arguments should be --types bbox, but the code in coco_utils.py,  result_file = result_files[res_type]  requires an integer input.

**Comment by bond9779** [comment]
How to get the classwise mAP of a given dataset?

The below command gives the overall mAP:
python3 tools/test.py --config/<config_name> checkpoint/<checkpoint_file_name> --eval bbox segm --show/--out

But is there a way to get the classwise mAP from this?
@hellock @jshuzi

**Comment by bond9779** [comment]
@yhcao6 Can you help me with this?

**Comment by DoubleCake** [comment]
![image](https://user-images.githubusercontent.com/23249887/67180555-90584680-f40c-11e9-8b18-d659890e2c41.png)
Look at the latest code and you will understand .
So,please update your code.
In the old version of the code, maybe the format like  ''proposal': 'result.path',  of course, this is just my understanding, if it is not correct, please let me know, thank you
