### ISSUE TITLE
map about multi-gpu and single-gpu

### ISSUE THREAD

**Issue by qianzhang2018** [open-mmlab/mmdetection#1419]
i use retinanet_r50.
i use my own dataset.
when i train it on single 1080,map(iou=0.5) is 0.32.(lr=0.00125)
but when i train it on 2*2070,map(iou=0.5) is 0.24.(lr = 0.0025)
is it normal?
can you give me some suggest？
thank you.

**Comment by johnlanbor** [comment]
may be you can check your bn setting

**Comment by hellock** [comment]
Please follow the `Error report` issue template to provide further information.
