### ISSUE TITLE
Fintune Question

### ISSUE THREAD

**Issue by johnlanbor** [open-mmlab/mmdetection#1420]
when i fintune a model from htc_x101_64x4d_fpn_20e_20190408-497f2561.pth

I got these , so why the backbone is mismatch ?

missing keys in source state_dict: layer2.1.conv2_offset.weight, layer2.0.conv2_offset.weight, layer2.3.conv2_offset.bias, layer3.22.conv2_offset.bias, layer4.0.conv2_offset.weight, layer2.3.conv2_offset.weight, layer3.7.conv2_offset.weight, layer3.19.conv2_offset.bias, layer3.21.conv2_offset.bias, layer3.6.conv2_offset.bias, layer4.2.conv2_offset.bias, layer3.12.conv2_offset.bias, layer3.14.conv2_offset.weight, layer2.2.conv2_offset.bias, layer3.8.conv2_offset.bias, layer3.17.conv2_offset.bias, layer2.2.conv2_offset.weight, layer3.10.conv2_offset.bias, layer3.13.conv2_offset.weight, layer3.18.conv2_offset.weight, layer3.18.conv2_offset.bias, layer3.3.conv2_offset.bias, layer3.9.conv2_offset.bias, layer3.2.conv2_offset.weight, layer3.9.conv2_offset.weight, layer3.15.conv2_offset.bias, layer3.1.conv2_offset.weight, layer3.2.conv2_offset.bias, layer3.6.conv2_offset.weight, layer3.16.conv2_offset.bias, layer3.11.conv2_offset.weight, layer3.22.conv2_offset.weight, layer3.5.conv2_offset.bias, layer3.3.conv2_offset.weight, layer2.0.conv2_offset.bias, layer3.0.conv2_offset.weight, layer3.1.conv2_offset.bias, layer3.20.conv2_offset.bias, layer3.13.conv2_offset.bias, layer3.16.conv2_offset.weight, layer2.1.conv2_offset.bias, layer3.4.conv2_offset.bias, layer3.12.conv2_offset.weight, layer3.5.conv2_offset.weight, layer4.1.conv2_offset.bias, layer3.17.conv2_offset.weight, layer3.4.conv2_offset.weight, layer3.14.conv2_offset.bias, layer3.15.conv2_offset.weight, layer3.20.conv2_offset.weight, layer3.7.conv2_offset.bias, layer3.11.conv2_offset.bias, layer3.8.conv2_offset.weight, layer4.0.conv2_offset.bias, layer4.1.conv2_offset.weight, layer3.10.conv2_offset.weight, layer3.19.conv2_offset.weight, layer3.21.conv2_offset.weight, layer4.2.conv2_offset.weight, layer3.0.conv2_offset.bias,backbone.layer3.9.conv2_offset.bias, backbone.layer3.11.conv2_offset.bias, backbone.layer3.8.conv2_offset.bias, backbone.layer3.17.conv2_offset.weight, backbone.layer3.12.conv2_offset.bias, backbone.layer3.5.conv2_offset.weight, backbone.layer3.15.conv2_offset.weight, backbone.layer3.19.conv2_offset.bias, backbone.layer3.10.conv2_offset.weight, backbone.layer3.4.conv2_offset.bias, backbone.layer3.7.conv2_offset.weight, backbone.layer3.19.conv2_offset.weight, backbone.layer4.0.conv2_offset.bias, backbone.layer3.0.conv2_offset.weight, backbone.layer3.5.conv2_offset.bias, backbone.layer3.10.conv2_offset.bias, backbone.layer2.0.conv2_offset.weight, backbone.layer2.1.conv2_offset.bias, backbone.layer3.12.conv2_offset.weight, backbone.layer3.13.conv2_offset.weight, backbone.layer3.20.conv2_offset.weight, backbone.layer3.21.conv2_offset.weight, backbone.layer3.11.conv2_offset.weight, backbone.layer3.21.conv2_offset.bias, backbone.layer2.3.conv2_offset.bias, backbone.layer4.2.conv2_offset.bias, backbone.layer3.16.conv2_offset.weight, backbone.layer3.8.conv2_offset.weight, backbone.layer4.2.conv2_offset.weight, backbone.layer3.15.conv2_offset.bias, backbone.layer2.2.conv2_offset.bias, backbone.layer4.1.conv2_offset.bias, backbone.layer3.14.conv2_offset.bias, backbone.layer3.18.conv2_offset.weight, backbone.layer3.1.conv2_offset.bias, backbone.layer3.7.conv2_offset.bias, backbone.layer3.22.conv2_offset.weight, backbone.layer3.2.conv2_offset.weight, backbone.layer3.14.conv2_offset.weight, backbone.layer3.0.conv2_offset.bias, backbone.layer2.1.conv2_offset.weight, backbone.layer4.1.conv2_offset.weight, backbone.layer3.3.conv2_offset.bias, backbone.layer3.9.conv2_offset.weight, backbone.layer3.16.conv2_offset.bias, backbone.layer3.1.conv2_offset.weight, backbone.layer3.20.conv2_offset.bias, backbone.layer3.2.conv2_offset.bias, backbone.layer3.6.conv2_offset.weight, backbone.layer4.0.conv2_offset.weight, backbone.layer3.22.conv2_offset.bias, backbone.layer2.3.conv2_offset.weight, backbone.layer3.3.conv2_offset.weight, backbone.layer3.6.conv2_offset.bias, backbone.layer3.13.conv2_offset.bias, backbone.layer3.18.conv2_offset.bias, backbone.layer2.2.conv2_offset.weight, backbone.layer3.4.conv2_offset.weight, backbone.layer2.0.conv2_offset.bias, backbone.layer3.17.conv2_offset.bias

and 

these keys have mismatched shape:
+----------------------------------+-----------------------------+------------------------------+
| key                              | expected shape              | loaded shape                 |
+----------------------------------+-----------------------------+------------------------------+
| bbox_head.0.fc_cls.weight        | torch.Size([9, 1024])       | torch.Size([81, 1024])       |
| bbox_head.0.fc_cls.bias          | torch.Size([9])             | torch.Size([81])             |
| bbox_head.1.fc_cls.weight        | torch.Size([9, 1024])       | torch.Size([81, 1024])       |
| bbox_head.1.fc_cls.bias          | torch.Size([9])             | torch.Size([81])             |
| bbox_head.2.fc_cls.weight        | torch.Size([9, 1024])       | torch.Size([81, 1024])       |
| bbox_head.2.fc_cls.bias          | torch.Size([9])             | torch.Size([81])             |
| mask_head.0.conv_logits.weight   | torch.Size([9, 256, 1, 1])  | torch.Size([81, 256, 1, 1])  |
| mask_head.0.conv_logits.bias     | torch.Size([9])             | torch.Size([81])             |
| mask_head.1.conv_logits.weight   | torch.Size([9, 256, 1, 1])  | torch.Size([81, 256, 1, 1])  |
| mask_head.1.conv_logits.bias     | torch.Size([9])             | torch.Size([81])             |
| mask_head.2.conv_logits.weight   | torch.Size([9, 256, 1, 1])  | torch.Size([81, 256, 1, 1])  |
| mask_head.2.conv_logits.bias     | torch.Size([9])             | torch.Size([81])             |
| semantic_head.conv_logits.weight | torch.Size([19, 256, 1, 1]) | torch.Size([183, 256, 1, 1]) |
| semantic_head.conv_logits.bias   | torch.Size([19])            | torch.Size([183])            |
+----------------------------------+-----------------------------+------------------------------+

**Comment by johnlanbor** [comment]
another question:
can I just copy the same classes weight (coco to cityscapes)? that will be better than load from raw checkpoint?

**Comment by michaelisc** [comment]
I don't know about the missing weights but the weights with mismatched shape are caused by the different number of classes in COCO and Cityscapes. I don't know, how mmdetection handles these weights. Optimally they would just be ignored, then your finetuning should work as expected.

**Comment by michaelisc** [comment]
How did you add the semantic segmentation maps though?

**Comment by johnlanbor** [comment]
@michaelisc  I change the mismatched weights, by the following method

if city_classes equals to coco_classes, then copy this channel weight to new network,so the weights are same like cityscapes in the end , but weird this got no AP improvement.
what I wonder is why the backbone weight is missing when I use load from ..

**Comment by johnlanbor** [comment]
@michaelisc I didnt to find a way to copy semantic segmentation maps, if I find a cool way I will tell you.
