### ISSUE TITLE
Expect to update HRnet model on Aliyun

### ISSUE THREAD

**Issue by wxy1234567** [open-mmlab/mmdetection#1421]
I wonder if the model of HRnet has not been uploaded to Aliyun. I download it too slowly with AWS.

**Comment by zhouhang95** [comment]
你可以使用迅雷直接下载 然后mv到正确的位置

**Comment by wxy1234567** [comment]
> 你可以使用迅雷直接下载 然后mv到正确的位置

刚刚试了迅雷下载也很慢啊，兄弟有没有好的办法

**Comment by zhouhang95** [comment]
woc 我很快啊

**Comment by wxy1234567** [comment]
> woc 我很快啊

你是下阿里云的还是亚马逊的？有没有开会员啊？，我下https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/models/hrnet/mask_rcnn_hrnetv2p_w48_2x_20190820-70df51b2.pth
只有几K/s

**Comment by zhouhang95** [comment]
迅雷极速版 200k/s

**Comment by zhouhang95** [comment]
就你这个连接

**Comment by wxy1234567** [comment]
> 就你这个连接

感谢！
