### ISSUE TITLE
Can i use dcn in hrnet?

### ISSUE THREAD

**Issue by Epiphqny** [open-mmlab/mmdetection#1426]

**Comment by zhouhang95** [comment]
they are both backbone,
you need to modify backbone rather than use them directly

**Comment by Epiphqny** [comment]
> they are both backbone,
> you need to modify backbone rather than use them directly

thanks for your reply.

**Comment by kaikaizhu** [comment]
I want to increase dcn into backbone （resnet101）. Which weight should I use as the pre-training weight?
Can you help me? Thanks!
@zhouhang95 @Epiphqny
