### ISSUE TITLE
died with <Signals.SIGSEGV: 11>.

### ISSUE THREAD

**Issue by qpfhuan** [open-mmlab/mmdetection#1428]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I cloned the project in July and used it train a faster-rcnn model and now I wanna transfer this project to another machine which means the enviroment is different. I downloaded the latest project and copy the data and start to train but the error occurs and it didn't show where the problem is. Plz help me with that. 
The enviroment difference is
v100 -> p40
cuda 9.1 -> cuda9.0
torch1.1.0 ->torch1.1.0 no change
python 3.7.3 -> 3.6.6

I run the "python setup.py develop" everytime I installed the new cloned project. but the error remains the same.

**Reproduction**
1. What command or script did you run?
```
tools/dist_train ...
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
 - OS: centos7
 - PyTorch version 1.1.0 installed before
- GPU model p40
- CUDA and CUDNN version 9.0
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
2019-09-21 17:51:55,877 - INFO - workflow: [('train', 1)], max: 15 epochs
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/python3/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/usr/local/python3/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/pascal_voc/faster_rcnn_terrorism_cate13_badcase.py', '--launcher', 'pytorch', '--validate', '--work_dir', 'work_dirs/faster_rcnn_terrorism_cate13_badcase_0920']' died with <Signals.SIGSEGV: 11>.
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Hi @qpfhuan ,
`Signals.SIGSEGV: 11` seems to be a common bug when you are using different libraries/environments for compiling and running the code. I find a similar issue in other projects such as [nvvl](https://github.com/NVIDIA/nvvl/issues/5), this might give you a hint to check the running/compiling libraries to fix the bug.

**Comment by hellock** [comment]
Feel free to reopen it if you have any further questions.

**Comment by dyy0205** [comment]
hi, have you fix this problem? I have no idea how to fix it.

**Comment by ZwwWayne** [comment]
> hi, have you fix this problem? I have no idea how to fix it.

Can you post your environment information through `collect_env.py`?

**Comment by dyy0205** [comment]
> > hi, have you fix this problem? I have no idea how to fix it.
> 
> Can you post your environment information through `collect_env.py`?

when i run collect_env.py,  output "段错误“ ...

**Comment by DeannaJ** [comment]
> hi, have you fix this problem? I have no idea how to fix it.
i have recreate a new virtual environment and that solved the problem.
