### ISSUE TITLE
No config files for GCNET(DCN Cascade Mask)

### ISSUE THREAD

**Issue by ChandanVerma** [open-mmlab/mmdetection#1429]
Can you provide the config file for GCNET or at least the reference for the following model so that I can create the config?

**X-101-FPN | DCN Cascade Mask | GC(c3-c5, r16) | 1x | - | - | - | 47.9 | 40.9 | model**

Thanks,
Chandan Verma

**Comment by remilstl** [comment]
More GCNet configurations are available in the original GCNET repo : https://github.com/xvjiarui/GCNet/tree/master/configs/gcnet
However you might have to change the data config to make it compatible with the most recent changes.

**Comment by ChandanVerma** [comment]
Tried to make changes but is not compatible with latest version of this repository

**Comment by ZwwWayne** [comment]
Already supported in the current [model zoo](https://github.com/open-mmlab/mmdetection/tree/master/configs/gcnet).
