### ISSUE TITLE
How to modify the learning rate decay coefficient?

### ISSUE THREAD

**Issue by ZenFSheng** [open-mmlab/mmdetection#1430]
Hi~ I noticed that the learning rate will decay to 0.1*itself at the specific epoch.And I think it's too fast 😂，which part should be modified to change it? Thank you~

```
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 15])
```

**Comment by amirassov** [comment]
Hi, you should use parameter `gamma`. For example:
```lr_config = dict(
    policy='step',
    gamma=0.2,
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 15])```

**Comment by ZenFSheng** [comment]
> Hi, you should use parameter `gamma`. For example:
> 
> ```
>     policy='step',
>     gamma=0.2,
>     warmup='linear',
>     warmup_iters=500,
>     warmup_ratio=1.0 / 3,
>     step=[8, 15])```
> ```

Thank you very much~👍👍👍
