### ISSUE TITLE
the steps of  'building a model with basic components ' in TECHNICAL_DETAILS are not complete

### ISSUE THREAD

**Issue by minixiguazi** [open-mmlab/mmdetection#1431]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When i want to create a new neck component, i find the guidance in the TECHNICAL_DETAILS.md is not complete.

**Bug fix**
Except for the step 1 create a new file in mmdet/models/necks/pafpn.py and step 2 modify the config file, there is another thing we should do. That is adding your new component to the relatived __init__.py .
From
![wo change](https://user-images.githubusercontent.com/37469483/65398088-d1e2db00-dde7-11e9-8549-5e25127b3b20.png)
to
![changed](https://user-images.githubusercontent.com/37469483/65398093-d7402580-dde7-11e9-9d2e-cf1613c491b5.png)

**Comment by hellock** [comment]
Yes you are right, the step-by-step tutorial in [GETTING_STARTED.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#develop-new-components) is correct. You may open a PR to fix the docs.
