### ISSUE TITLE
How to modify model.classes?

### ISSUE THREAD

**Issue by zihaozhang9** [open-mmlab/mmdetection#1432]
I have modified the category annotation in the [json ](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r50_fpn_1x.py#L149)file.
But when I tested, I used the following statement to construct the model:
`model = init_detector(config_file, checkpoint_file, device='cuda:0')`
Then look at the `model.classes` variable and see the object category that is still coco.
Are there any names changes in the mask_rcnn_r50_fpn_1x.py file.
Or, change [class_names](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L94) when making predictions.

**Comment by zhouhang95** [comment]
mmdetection\mmdet\datasets

**Comment by zihaozhang9** [comment]
> mmdetection\mmdet\datasets

Can only be achieved by modifying [CocoDataset's](https://github.com/open-mmlab/mmdetection/blob/0d5233a32dac4288760f6d819ddfef9c1e020cf7/mmdet/datasets/coco.py#L11) code? Can't it be modified by configuration file

**Comment by zhouhang95** [comment]
need to modify both

**Comment by Hemantr05** [comment]
You'll need to modify the classes in the mmdet/datasets/ in your dataset file. And replace the DatasetType in the config file with the class in your dataset file.

**Comment by Hemantr05** [comment]
Or, you can also replace model.CLASSES with a list of class names (for eg. ["Person", "Dog", "Cat", ...])

**Comment by prajnasb** [comment]
hey can anyone help me out with this issue, I want to train the SSD model with Voc dataset but I am not able to change the class name, I tried editing voc.py but still it is not happening. 
and I even want to know the inference script for the updated mmdet.

**Comment by SR-fr** [comment]
I want to predict only person and dog objects in the model.classes what I want to do??  show me the script? any example code?

**Comment by SR-fr** [comment]
> Or, you can also replace model.CLASSES with a list of class names (for eg. ["Person", "Dog", "Cat", ...])

I want to predict only person and dog objects in the model.classes what I want to do?? show me the script? any example code?

**Comment by SR-fr** [comment]
> mmdetection\mmdet\datasets

I want to predict only person and dog objects in the model.classes what I want to do?? show me the script? any example code?

**Comment by Soodep** [comment]
did anyone have solution to this?

**Comment by Soodep** [comment]
@prajnasb did you solve your issue?
