### ISSUE TITLE
what's the difference if the num_classes(<81) in config file is larger than the length of the classes in mmdet/datasets/coco.py

### ISSUE THREAD

**Issue by github-eliviate** [open-mmlab/mmdetection#1434]
first, I Modify the classes in mmdet/datasets/coco.py ,for example ,class=('A','B','C','D')
second,keep the num_classes=81 in config file(mask_rcnn_hrnetv2p_w32_1x) ,and then train the network after modify the dataset path in config file,there is no error reported,and i use the config file for test,then get a acc Acc_81.
third,keep the first step unchanged,modify the num_class to 5 in config file(mask_rcnn_hrnetv2p_w32_1x), and train the network again, when i use the config file for test,get a acc Acc_5.
I found that Acc_81 is bigger than Acc_5,and I can't find new category except A,B,C,D in result images.
why?????

**Comment by mosheliv** [comment]
I think coco is mAP, so it is also averaging the zero classes. So, suppose
you have perfect score for a, b, c, d, e, the average will be (5+75*0)/81
