### ISSUE TITLE
torch size mismatch when changing the loss type to iou loss

### ISSUE THREAD

**Issue by scut-salmon** [open-mmlab/mmdetection#1436]
**Describe the bug**
when I change the bbox type to IOU loss:
![image](https://user-images.githubusercontent.com/20534039/65409321-0079a980-de1a-11e9-9b22-b6d6c9b2e463.png)
it reports the error:
```
    loss = weight_reduce_loss(loss, weight, reduction, avg_factor)
  File "mmdetection/mmdet/models/losses/utils.py", line 40, in weight_reduce_loss
    loss = loss * weight
RuntimeError: The size of tensor a (45) must match the size of tensor b (4) at non-singleton dimension 1
```

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=2 python tools/train.py configs/dcn/cascade_rcnn_dconv_c3-c5_r50_fpn_1x.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I debug the error and find that it's because the torch size mismatch in this [line](https://github.com/open-mmlab/mmdetection/blob/c64beaf1494ea68562b274a723824d7f52fd31e8/mmdet/models/losses/utils.py#L40), the iou loss return 1-dimension value, which is different from smooth-L1 loss(4-dimension). but the weight loss is still 4-dimension.
I change this [line](https://github.com/open-mmlab/mmdetection/blob/c64beaf1494ea68562b274a723824d7f52fd31e8/mmdet/models/losses/utils.py#L40) to as follows, and the code run correctly.
```        
if loss.shape != weight.shape: loss = loss * weight[:, 0]
else: loss = loss * weight
```
I change to this line because I think the 4-dimension of `weight` is the same. 

I don't sure whether this change is correct, or maybe there are some other good solutions(But I don't find in the issues).

**Comment by hellock** [comment]
The out-of-the-box replacement is not supported yet, since the input of `IoULoss` and `SmoothL1Loss` are also different.

**Comment by scut-salmon** [comment]
But I find this table in the  [ArXiv](https://arxiv.org/abs/1906.07155)
![image](https://user-images.githubusercontent.com/20534039/66492011-460ac780-eae6-11e9-88c1-5b2f9daee819.png)

**Comment by GYxiaOH** [comment]
@scut-salmon i meet the same problem, do you solve the issue?

**Comment by hellock** [comment]
There is no out-of-the-box replacement, so we simply make some simple modifications to the interfaces when using the IoU Loss or GIoU Loss.

**Comment by yhcao6** [comment]
Usually the regression loss is of shape (#pos, 4), and the loss weight is of shape (#pos, 4). 
However, IoU loss is of shape (#pos, ) which leads this mismatch error.
You can change [this line](https://github.com/open-mmlab/mmdetection/blob/618dca0895f5f4ede19f5feebb064648e128e12e/mmdet/models/bbox_heads/bbox_head.py#L127) to `bbox_weights[pos_inds][:, 0],` when using `IoULoss`.

**Comment by ZYN-guy** [comment]
> Usually the regression loss is of shape (#pos, 4), and the loss weight is of shape (#pos, 4).
> However, IoU loss is of shape (#pos, ) which leads this mismatch error.
> You can change [this line](https://github.com/open-mmlab/mmdetection/blob/618dca0895f5f4ede19f5feebb064648e128e12e/mmdet/models/bbox_heads/bbox_head.py#L127) to `bbox_weights[pos_inds][:, 0],` when using `IoULoss`.

Thank you for your comments. But I got a lower map

**Comment by clw5180** [comment]
> > Usually the regression loss is of shape (#pos, 4), and the loss weight is of shape (#pos, 4).
> > However, IoU loss is of shape (#pos, ) which leads this mismatch error.
> > You can change [this line](https://github.com/open-mmlab/mmdetection/blob/618dca0895f5f4ede19f5feebb064648e128e12e/mmdet/models/bbox_heads/bbox_head.py#L127) to `bbox_weights[pos_inds][:, 0],` when using `IoULoss`.
> 
> Thank you for your comments. But I got a lower map

请问mAP现在正常了么

**Comment by xiabc612** [comment]
I meet the same problem when changing to IOU loss. I found that the shape of  bbox_weights(no bbox_weights[pos_inds]) is 1024*4, but I didn't find any relative information of bbox_weights in config file. What's the use of this bbox_weights? Should this weight be changed when using IOU loss?
