### ISSUE TITLE
How to add pictures without bounding box to reduce false postive?

### ISSUE THREAD

**Issue by Nioolek** [open-mmlab/mmdetection#1437]
when I trained a class named Mickey,model often predict some cartoon faces as Mickey.So,I want to add pictures without bounding box.
How to add pictures without bounding box to reduce false postive?

**Comment by abuzn** [comment]
I think acctually only some of algorithms support feeding pictures without bounding box, it depends on the 'sampler', 'assigner' and 'loss'. I tried retinanet  with some modification and it works.

**Comment by Nioolek** [comment]
> I think acctually only some of algorithms support feeding pictures without bounding box, it depends on the 'sampler', 'assigner' and 'loss'. I tried retinanet with some modification and it works.

Thank you. I tried to change the 'sampler','assigner'and'loss' ,and it succeeded.

**Comment by zhaojw219** [comment]
I used retinanet in mmdetection to detect small object like football in football game,but false positive is too much in the result.Do you have any good suggestion?Thanks so much!

**Comment by Nioolek** [comment]
> I used retinanet in mmdetection to detect small object like football in football game,but false positive is too much in the result.Do you have any good suggestion?Thanks so much!

小目标的检测一直是比较困难的。
给你如下几个建议：
1、保证自己的数据集中，所有的足球都是肉眼可以识别出的。
2、增加训练和测试的图片输入尺寸。
3、修改anchor，尽量适配小目标。
4、训练时候增加负样本，告诉模型检测出的fp是fp。
5、我看mmdetection中，只有size是大于10的bounding box才会保留，可能很多你已经打了标的数据，在这一步就已经被过滤掉了。你可以把这个阈值改的更小，不过我猜测这应该不会有用。

**Comment by zhaojw219** [comment]
> > I used retinanet in mmdetection to detect small object like football in football game,but false positive is too much in the result.Do you have any good suggestion?Thanks so much!
> 
> 小目标的检测一直是比较困难的。
> 给你如下几个建议：
> 1、保证自己的数据集中，所有的足球都是肉眼可以识别出的。
> 2、增加训练和测试的图片输入尺寸。
> 3、修改anchor，尽量适配小目标。
> 4、训练时候增加负样本，告诉模型检测出的fp是fp。
> 5、我看mmdetection中，只有size是大于10的bounding box才会保留，可能很多你已经打了标的数据，在这一步就已经被过滤掉了。你可以把这个阈值改的更小，不过我猜测这应该不会有用。

Can you explain in detail the fourth and fifth steps in the code? Maybe I can change them to optimize my model. Thank you very much!

**Comment by Nioolek** [comment]
> > > I used retinanet in mmdetection to detect small object like football in football game,but false positive is too much in the result.Do you have any good suggestion?Thanks so much!
> > 
> > 
> > 小目标的检测一直是比较困难的。
> > 给你如下几个建议：
> > 1、保证自己的数据集中，所有的足球都是肉眼可以识别出的。
> > 2、增加训练和测试的图片输入尺寸。
> > 3、修改anchor，尽量适配小目标。
> > 4、训练时候增加负样本，告诉模型检测出的fp是fp。
> > 5、我看mmdetection中，只有size是大于10的bounding box才会保留，可能很多你已经打了标的数据，在这一步就已经被过滤掉了。你可以把这个阈值改的更小，不过我猜测这应该不会有用。
> 
> Can you explain in detail the fourth and fifth steps in the code? Maybe I can change them to optimize my model. Thank you very much!

第四步：调节配置文件中的正负样本比例，增加负样本比例。
第五步：你查看mmdet/datasets文件夹中的代码，会有fillter函数把小目标直接过滤掉了

**Comment by zhaojw219** [comment]
> > > > I used retinanet in mmdetection to detect small object like football in football game,but false positive is too much in the result.Do you have any good suggestion?Thanks so much!
> > > 
> > > 
> > > 小目标的检测一直是比较困难的。
> > > 给你如下几个建议：
> > > 1、保证自己的数据集中，所有的足球都是肉眼可以识别出的。
> > > 2、增加训练和测试的图片输入尺寸。
> > > 3、修改anchor，尽量适配小目标。
> > > 4、训练时候增加负样本，告诉模型检测出的fp是fp。
> > > 5、我看mmdetection中，只有size是大于10的bounding box才会保留，可能很多你已经打了标的数据，在这一步就已经被过滤掉了。你可以把这个阈值改的更小，不过我猜测这应该不会有用。
> > 
> > 
> > Can you explain in detail the fourth and fifth steps in the code? Maybe I can change them to optimize my model. Thank you very much!
> 
> 第四步：调节配置文件中的正负样本比例，增加负样本比例。
> 第五步：你查看mmdet/datasets文件夹中的代码，会有fillter函数把小目标直接过滤掉了

OK.Thank you very much!

**Comment by clw5180** [comment]
> > > > I used retinanet in mmdetection to detect small object like football in football game,but false positive is too much in the result.Do you have any good suggestion?Thanks so much!
> > > 
> > > 
> > > 小目标的检测一直是比较困难的。
> > > 给你如下几个建议：
> > > 1、保证自己的数据集中，所有的足球都是肉眼可以识别出的。
> > > 2、增加训练和测试的图片输入尺寸。
> > > 3、修改anchor，尽量适配小目标。
> > > 4、训练时候增加负样本，告诉模型检测出的fp是fp。
> > > 5、我看mmdetection中，只有size是大于10的bounding box才会保留，可能很多你已经打了标的数据，在这一步就已经被过滤掉了。你可以把这个阈值改的更小，不过我猜测这应该不会有用。
> > 
> > 
> > Can you explain in detail the fourth and fifth steps in the code? Maybe I can change them to optimize my model. Thank you very much!
> 
> 第四步：调节配置文件中的正负样本比例，增加负样本比例。
> 第五步：你查看mmdet/datasets文件夹中的代码，会有fillter函数把小目标直接过滤掉了

对于第五步我看代码中是过滤掉了img_size<32的图片，还有不包含任何gt的图片，但是没有看到会过滤小目标，可否请教下是在哪里过滤的？

**Comment by zzzjoey** [comment]
> > I think acctually only some of algorithms support feeding pictures without bounding box, it depends on the 'sampler', 'assigner' and 'loss'. I tried retinanet with some modification and it works.
> 
> Thank you. I tried to change the 'sampler','assigner'and'loss' ,and it succeeded.

Hello, how did you solve it? Can you give me some specific instructions for changes? I also encountered the same problem. Thank you very much.
