### ISSUE TITLE
Why ga_shape_target_single() return (None,) *6

### ISSUE THREAD

**Issue by gyfastas** [open-mmlab/mmdetection#1438]
I got ValueError:not enough values to unpack(expected 5)  whe using ga_shape_target_single(), and found that 
`if not inside_flags.any(): return (None,) *6` but I notice that this function returns a 5-tuple in `inside_flags.any()=True` case.

**Comment by hellock** [comment]
Looks like a bug. Feel free to fix that with a PR.
