### ISSUE TITLE
bounded iou loss is  time-consuming

### ISSUE THREAD

**Issue by scut-salmon** [open-mmlab/mmdetection#1442]
Hi, I found that when I change the smooth-L1 loss to bounded iou loss, the code become quite time-consuming and the loss is not stable, which may occur to large value, the same situation as iou loss.

Did anyone meet the same question?

Thanks
Zhang

**Comment by xvjiarui** [comment]
Hi @scut-salmon 
Bounded IoU loss and IoU loss are supported in V2.0. You may refer to [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/faster_rcnn#different-regression-loss) for experiment results. 
The results seem normal and no time-consuming issue is observed. 
You may try our latest code. Feel free to reopen this issue if the problem still exits.
