### ISSUE TITLE
No module named 'terminaltables'

### ISSUE THREAD

**Issue by xcaizewu** [open-mmlab/mmdetection#1443]
![error](https://user-images.githubusercontent.com/48117810/65501648-ef9d6680-def3-11e9-8d1b-990af509d2f5.jpg)

Who can help me? I don't know what's wrong

**Comment by zrl4836** [comment]
pip install

**Comment by KDcx35** [comment]
hi,how you solve this?I have already install the 'terminaltables' module,but i still got this error.

**Comment by xcaizewu** [comment]
> 
> 
> hi,how you solve this?I have already install the 'terminaltables' module,but i still got this error.

Sorry, I forgot how to solve this problem. It seems that pip install has solved it

**Comment by KDcx35** [comment]
> > hi,how you solve this?I have already install the 'terminaltables' module,but i still got this error.
> 
> Sorry, I forgot how to solve this problem. It seems that pip install has solved it

ok，thank you
