### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by l99500** [open-mmlab/mmdetection#1444]
Recently, I try to install the mmcv and mmdetection in a computer. But   due to the special organization, the computer can not connect to Internet.  I have installed the CUDA ,anaconda and pytorch and failed to install the mmcv and mmdetection.  I find both need to download something and don't know how to solve it. Is there some suggestion? thank you very much.

**Comment by hellock** [comment]
You also need to install the requirements, e.g., https://github.com/open-mmlab/mmdetection/blob/master/requirements.txt.

**Comment by l99500** [comment]
thank you. I've solved this problem
