### ISSUE TITLE
About Loss Calculation 

### ISSUE THREAD

**Issue by cancam** [open-mmlab/mmdetection#1446]
Hello everyone,
I am wondering how does classification and regression losses calculated in loss_single function in anchor_head. I tracked anchors, matched ground truths and labels up to the loss_single function. Each variable that I mentioned before contains all levels of FPN, but when I checked those variables inside loss_single function they only contain the first level of the FPN? How does loss calculation mechanism work? I am trying to hook loss values of anchors that place in every level of FPN.

Notes:
I am working on the RetinaNet model with ResNet-50 backbone.

Thank you.
Baris.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L190
