### ISSUE TITLE
Wrong about the code of non_local.py

### ISSUE THREAD

**Issue by xunhen** [open-mmlab/mmdetection#1447]
The wrong  code in non_local.py is below:
    def embedded_gaussian(self, theta_x, phi_x):
        # pairwise_weight: [N, HxW, HxW]
        pairwise_weight = torch.matmul(theta_x, phi_x)
        if self.use_scale:
            # theta_x.shape[-1] is `self.inter_channels`
            pairwise_weight /= theta_x.shape[-1]**-0.5
        pairwise_weight = pairwise_weight.softmax(dim=-1)
        return pairwise_weight
The operate of scale should be the multipy between pairwise_weight and theta_x.shape[-1]**-0.5, not the div opt

**Comment by hellock** [comment]
Thanks! Fixed in #1528.
