### ISSUE TITLE
batch_size should be a positive integer value, but got batch_size=0

### ISSUE THREAD

**Issue by xcaizewu** [open-mmlab/mmdetection#1448]
![error2](https://user-images.githubusercontent.com/48117810/65589953-846b9700-dfbc-11e9-90bb-255e73a8d070.jpg)
I don't understand this error

**Comment by boykac** [comment]
i meet this too

**Comment by xcaizewu** [comment]
> 
> 
> i meet this too

重新克隆mmdetection，安装后再试试
