### ISSUE TITLE
Reppoints Test Error

### ISSUE THREAD

**Issue by leftthomas** [open-mmlab/mmdetection#1453]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
The `test_pipeline` and `data.test` in `configs/reppoints/reppoints_moment_x101_dcn_fpn_2x_mt.py` is wrong.

1.`data.test` field should be 
```python
test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/image_info_test-dev2017.json',
        img_prefix=data_root + 'test2017/',
        pipeline=test_pipeline))
```
2.`img_scale` field in `test_pipeline` is wrong, if we use `img_scale=(1333, 800)`, then it will report **deform conv error: the input shape is less than kernel size**.

**Reproduction**
1. What command or script did you run?
```
./tools/test.sh configs/reppoints_moment_x101_dcn_fpn_2x_mt.py checkpoints/reppoints_moment_x101_dcn_fpn_2x_mt.pth 8 --json_out results
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
yes, look 1.
3. What dataset did you use?
coco2017 test-dev.

**Environment**
 - OS: [Ubuntu 18.04.3]
 - GCC [7.4.0]
 - PyTorch version [ 1.2.0]
- How you installed PyTorch [conda]
- GPU model [V100]
- CUDA and CUDNN version [CUDA10.0, CUDNN 7.6.2.24]

**Comment by hellock** [comment]
Maybe @yangze0930 can help.

**Comment by yangze0930** [comment]
Thanks for your information! In fact, this is a problem relates to DCN operator. In the forward pass, DCN will check whether the input feature map shape is less than the DCN kernel size. See [here](https://github.com/open-mmlab/mmdetection/blob/6ee5e4d614abc81d64eecbf814e195c985b80956/mmdet/ops/dcn/src/deform_conv_cuda.cpp#L127-L128) for details. In the multi scale test mode, when a small scale is selected, the smallest feature map in the reppoints head may have a shorter edge less than 3, while  3 is the kernel size of DCN. The workaround is to either use a larger scale or comment the code in [here](https://github.com/open-mmlab/mmdetection/blob/6ee5e4d614abc81d64eecbf814e195c985b80956/mmdet/ops/dcn/src/deform_conv_cuda.cpp#L127-L128) and recompile.

**Comment by leftthomas** [comment]
@yangze0930 thank you for you help
