### ISSUE TITLE
_non_dist_train validation?

### ISSUE THREAD

**Issue by andresfp14** [open-mmlab/mmdetection#1454]
Hello! I may be missing something, but I'm trying to train a model in non distributed mode, and apparently it does not validate after training.

I went inside of mmdet/apis/train.py and the validation section is implemented for _dist_train but not for _non_dist_train .

When I try to put `workflow = [('train', 1), ('val', 1)]` in the configuration, it just explodes in the validation. The error is something like:

```
File "/home/userXXX/.conda/envs/envXXX/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 43, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 96 and 192 in dimension 2 at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/TH/generic/THTensor.cpp:711
```

Am I missing something? or is this a feature that has not been implemented yet?

**Comment by hellock** [comment]
#407 #1090 #1093
