### ISSUE TITLE
How to use nvidia-dali in mmdet?

### ISSUE THREAD

**Issue by BlueBlueFF** [open-mmlab/mmdetection#1456]
Maybe I should define a new dataloader？

**Comment by hellock** [comment]
Not sure if it is simple to integrate DALI to mmdetection. Feel free to share your experience if you get it.

**Comment by 13952522076** [comment]
> Maybe I should define a new dataloader？

Hi, if u successfully integrate DALI to mmdetection? It would be helpful.

**Comment by 1757525671** [comment]
Similarly. I also want to know how to introduce DALI

**Comment by jshilong** [comment]
We will investigate DALI recently and evaluate its feasibility

**Comment by mitming** [comment]
> We will investigate DALI recently and evaluate its feasibility

Hi, @jshilong @hellock

Is there progress in introducing DALI?

**Comment by austinmw** [comment]
Hi, curious if there's any progress on this or other methods to improve dataloading speed?
