### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by DENGZAIXU** [open-mmlab/mmdetection#1457]
In the config file：
anchor_scales=[8]
anchor_ratios=[0.5, 1.0, 2.0]
anchor_strides=[4, 8, 16, 32, 64]
What do these three parameters represent?

**Comment by AloshkaD** [comment]
These describe the scale ans size of the anchor bboxs that the network use. Typically, you would need smaller anchors for the small objects in your mask and the opposite is true. This paper is helpful for explaining these terms and how to set them up.

http://www.multimedia-computing.de/mediawiki/images/e/ed/ICME2017.pdf

**Comment by Kaeseknacker** [comment]
Can someone explain me anchor_strides (especially for RetinaNet, anchor_strides=[8,16,32,64,128]) in more detail? I understand it like this: Place at every 8th, 16th, ... position of the image a special set of anchor boxes and make a prediction. On the other hand, I can also observe that the last feature map layers (of RetinaNet-Pyramid) are exactly 1/8, 1/16, 1/32, 1/64 and 1/128 of the input image size. Therefore, I ask myself, is the parameter set "anchor_strides" really freely selectable, or is it directly related to the structure of the network and if I choose it wrong, the whole construct collapses?

**Comment by harriv** [comment]
> This paper is helpful for explaining these terms and how to set them up.

> http://www.multimedia-computing.de/mediawiki/images/e/ed/ICME2017.pdf

That link has expired, do you remember the title of that paper or authors?

**Comment by harriv** [comment]
> This paper is helpful for explaining these terms and how to set them up.
> 
> http://www.multimedia-computing.de/mediawiki/images/e/ed/ICME2017.pdf

This link doesn't work anymore, do you remember the title of the paper, or authors?
