### ISSUE TITLE
How to deploy trained model to CPU?

### ISSUE THREAD

**Issue by jayeshsaita** [open-mmlab/mmdetection#1459]
Hi,

Is there any way to publish the model to CPU? I used the publish.py script to convert the model to CPU, but I cannot install the mmdetection library in a CPU only environment. Is it possible to perform inference in a CPU only environment? Is it possible to do so using ONNX? 

Thanks :)

**Comment by Prakashvanapalli** [comment]
Go through the issues [Link1](https://github.com/open-mmlab/mmdetection/issues/1274). It should have mentioned in the README.

**Comment by akarazniewicz** [comment]
I actually created separate project for that. Currently it's only retinanet, but may be helpful: https://github.com/akarazniewicz/smd

**Comment by zhaojw219** [comment]
> Hi,
> 
> Is there any way to publish the model to CPU? I used the publish.py script to convert the model to CPU, but I cannot install the mmdetection library in a CPU only environment. Is it possible to perform inference in a CPU only environment? Is it possible to do so using ONNX?
> 
> Thanks :)

.onnx is ok
