### ISSUE TITLE
when training my dataset ,run voc_eval.py exist  aeroplane bicycle ap

### ISSUE THREAD

**Issue by yangdeqieyingli** [open-mmlab/mmdetection#1461]
finish training my dataset,run voc_eval.py:
+-----------+-----+------+--------+-----------+-------+
| class     | gts | dets | recall | precision | ap    |
+-----------+-----+------+--------+-----------+-------+
| aeroplane | 142 | 171  | 0.993  | 0.825     | 0.909 |
| bicycle   | 137 | 169  | 1.000  | 0.811     | 0.985 |
| bird      | 180 | 198  | 1.000  | 0.909     | 1.000 |
| boat      | 178 | 196  | 1.000  | 0.908     | 1.000 |
+-----------+-----+------+--------+-----------+-------+
| mAP       |     |      |        |           | 0.973 |
+-----------+-----+------+--------+-----------+-------+
the ap is not my dataset,why?

**Comment by lizxchen** [comment]
I met the same question. Can you give me some advise?Thanks.

**Comment by hellock** [comment]
I guess you were using `VOCDataset` instead of writing your own dataset inherited from `VOCDataset`.
