### ISSUE TITLE
Does the "validate" procedure should be executed each epoch?

### ISSUE THREAD

**Issue by ronghaoLee** [open-mmlab/mmdetection#1464]
I have created a new dataset according to the data format of the COCO
But when I try to train the model with the "validate" setted by the 'parser', I found the validate procedure is too long because of the big validation dataset.

How can I validate the training model with a longer interval? (For example, how can I validate the model once per 5 training epochs)

**Comment by shuxp** [comment]
You can write a new hook to do validation as you wanted.

**Comment by ronghaoLee** [comment]
> You can write a new hook to do validation as you wanted.

Thanks, I got it.

**Comment by hellock** [comment]
You can simply add a field `evaluation = dict(interval=5)` in the config file.
