### ISSUE TITLE
How can I change the model download path from AWS to aliyun in the code.

### ISSUE THREAD

**Issue by herrickli** [open-mmlab/mmdetection#1465]
How can I change the model download path from AWS to aliyun in the code.
Thanks~

**Comment by hellock** [comment]
You can replace `https://s3.ap-northeast-2.amazonaws.com/open-mmlab` with `https://open-mmlab.oss-cn-beijing.aliyuncs.com` in model urls.

E.g., if the url of AWS is `https://s3.ap-northeast-2.amazonaws.com/open-mmlab/xxxxxxxxxx`, you can use `https://open-mmlab.oss-cn-beijing.aliyuncs.com/xxxxxxxxxx` instead.
