### ISSUE TITLE
Flip the mask when merging bbox_masks

### ISSUE THREAD

**Issue by wmmxk** [open-mmlab/mmdetection#1466]
**Describe the bug**
In the function merge_aug_masks[() ](https://github.com/open-mmlab/mmdetection/blob/d2483e15fc48b4166815c15a6e12be864bcc521a/mmdet/core/post_processing/merge_augs.py#L87). The aug_masks is flipped if the input image is flipped. I think the aug_masks should not be flipped even if the img_info[0]['flip'] is True. You know the flip is on the whole but the box_mask. When I visualize the predicted masks, I saw the flipping is not needed. If I am wrong, please correct me. This function is called in the simple_test() [function](https://github.com/open-mmlab/mmdetection/blob/69e93f6f25d95edc498e73f0094dce8af742d296/mmdet/models/detectors/cascade_rcnn.py#L378)

**Comment by MendelXu** [comment]
Why this issue is closed without any explanation?
