### ISSUE TITLE
How to convert mmdetection config file to pytorch config file?

### ISSUE THREAD

**Issue by kingwpf** [open-mmlab/mmdetection#1467]
I need to load the model on python2 environment, but model build method doesn't works on python2, so can I convert the mmdetection config file to original pytorch config file?

**Comment by hellock** [comment]
What do you mean by `pytorch config file`? As far as I know, PyTorch does not define any official config file format.

**Comment by hellock** [comment]
Feel free to reopen it if you have any further questions.
