### ISSUE TITLE
onnx exported Resize op has no scales params

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmdetection#1472]
![image](https://user-images.githubusercontent.com/21303438/65852739-acc30f00-e389-11e9-8730-8e9eff8cbe96.png)

As you may notice, the model does not have a scales params in Resize....

Does anyone knows why it does needs scales but onnx opset 10 said, Resize op consume 2 inputs which is input nodes and scales.

Compares to yolov3.onnx, much more standared:

![image](https://user-images.githubusercontent.com/21303438/65852838-00cdf380-e38a-11e9-8002-1d1bc27c5ed7.png)

It have a scales params.

**Comment by RunningLeon** [comment]
Pls. try with the latest mmcv and mmdetection. Reopen it if you still have any issue.
