### ISSUE TITLE
Got poor performance on custom dataset.

### ISSUE THREAD

**Issue by herrickli** [open-mmlab/mmdetection#1473]
I trained custom `pascal_voc dataset` with `cascade_rcnn_hrnetv2p_w32_20e.py`, I used all the data as trainval, and part of it as test, after 20 epochs, the loss decrease to 0.3, and the `log info` like this:
```
INFO - Epoch [16][450/715]    lr: 0.00250, eta: 3:52:14, time: 0.801, data_time: 0.004, memory: 9102, loss_rpn_cls: 0.0239, loss_rpn_bbox: 0.0093, s0.loss_cls: 0.1392, s0.acc: 96.1270, s0.loss_bbox: 0.0731, s1.loss_cls: 0.0549, s1.acc: 97.1621, s1.loss_bbox: 0.0480, s2.loss_cls: 0.0183, s2.acc: 98.4102, s2.loss_bbox: 0.0135, loss: 0.3802
```
And I used the checkpoint to run `test.py` and generate `result.pkl`, but after the I parsed the `.pkl` file, set score threshold 0.5, the result is not good, lots of images have no predictions.
So what can I do to improve the performance or is there somewhere I forgot to modified.
Thanks~

**Comment by herrickli** [comment]
I don't know if it is my dataset is too small, but the total loss is about 0.3 in the second epoch and doesn't decrease in the next 20+ epoches. I'm confused.

**Comment by herrickli** [comment]
@hellock Help, please~

**Comment by herrickli** [comment]
I trained 100 epoches, the loss is still above 0.3, I can't solve it. Any help? Please. @hellock

**Comment by herrickli** [comment]
I still haven't solve the problem.
I use another configure file, `htc_without_semantic_r50_fpn_1x.py`, pretrained_weight is `htc_r50_fpn_1x_20190408-878c1712.pth`, training for 12 epochs, and below is the log info 
```
INFO - Epoch [12][200/228]    lr: 0.00005, eta: 0:00:37, time: 1.510, data_time: 0.011, memory: 4299, loss_rpn_cls: 0.0393, loss_rpn_bbox: 0.0156, s0.loss_cls: 0.1401, s0.acc: 97.0273, s0.loss_bbox: 0.0623, s0.loss_mask: 0.4336, s1.loss_cls: 0.0479, s1.acc: 98.2266, s1.loss_bbox: 0.0306, s1.loss_mask: 0.2064, s2.loss_cls: 0.0133, s2.acc: 99.1855, s2.loss_bbox: 0.0051, s2.loss_mask: 0.1042, loss: 1.0984

```

After I got `epoch_12.pth`, I use it to test my test dataset which is the same with my training dataset, and it is the result. In my dataset, there are 5 classes.
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.022
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.005
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.006
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.034
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.098
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.128
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.083
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.135
```
So, I'm really confused, I don't know where is wrong. Please help me. Many thanks. @hellock

**Comment by herrickli** [comment]
I have not idea about how to make it work.
I use mask_rpn
There are 5 categorises in my custom dataset, and I changed the coco classes to my categories.
And I use 2 gpu, so I reduce lr from `0.02` to `0.02 / 4`
Here is my config file.
```
model = dict(
    type='MaskRCNN',
    #pretrained='torch/checkpoints/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth',
    pretrained=None,
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=dict(
        type='SharedFCBBoxHead',
        num_fcs=2,
        in_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=6,
        target_means=[0., 0., 0., 0.],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        reg_class_agnostic=False,
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
    mask_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=14, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    mask_head=dict(
        type='FCNMaskHead',
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=6,
        loss_mask=dict(
            type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        mask_size=28,
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_thr=0.5),
        max_per_img=100,
        mask_thr_binary=0.5))
# dataset settings
dataset_type = 'CocoDataset'
data_root = '/home/licheng/projects/mmdetection/data/coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline))
# optimizer
optimizer = dict(type='SGD', lr=0.02 / 4, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
evaluation = dict(interval=1)
# runtime settings
total_epochs = 12
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/mask_rcnn_r50_fpn_1x'
load_from = None
resume_from = None
workflow = [('train', 1)]
```

I put 905 images in train dataset, and only 1 image in val dataset.
After 12 epochs, this is the log info.

```
2019-10-11 17:16:07,626 - INFO - Epoch [12][200/227]    lr: 0.00005, eta: 0:00:26, time: 1.067, data_time: 0.013, memory: 3818,
 loss_rpn_cls: 0.0496, loss_rpn_bbox: 0.0131, loss_cls: 0.1310, acc: 97.4199, loss_bbox: 0.0573, loss_mask: 0.4235, loss: 0.6745
```
And I do add validate, here is the result.
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
```
And I use the config file and `epoch_12.pth` to run the `test.py`, output file is 'result.pkl', `--eval bbox`, the output log is the same as below validate info.

Then I use `python tools/coco_eval.py result.pkl`, it says `assert isinstance(coco, COCO)
AssertionError`.

I print the content of result.pkl, here are all the prediction bounding boxes:
```
[3.3848590e+02 1.4069824e+02 5.3549097e+02 2.0575418e+02 5.0295100e-02]
[1.7246944e+02 2.9701807e+02 3.6649576e+02 3.6149133e+02 5.6047469e-02]
[1.7711346e+01 4.1604980e+02 2.0808742e+02 4.8156598e+02 6.0481794e-02]
[5.0730634e+02 5.9567677e+01 9.1988708e+02 2.7949777e+02 7.5444207e-02]
[5.0661667e+02 2.0105237e+02 9.2023450e+02 4.2323883e+02 6.1535407e-02]
[1.7433136e+02 2.9717792e+02 3.6482898e+02 3.6110904e+02 5.0828498e-02]
[1.9520685e+01 4.1627609e+02 2.0668042e+02 4.8118680e+02 5.7543796e-02]
[9.1576378e+01 2.6835748e+02 4.1394058e+02 3.7968976e+02 8.4639400e-02]
[9.2929489e+01 9.9893806e+01 4.1266205e+02 2.1219266e+02 6.6862963e-02]
[2.3507387e+02 9.9953766e+01 5.5520831e+02 2.1230498e+02 6.6346191e-02]
[5.9234485e+02 2.9185373e+02 9.1278314e+02 4.0377466e+02 6.9933698e-02]
[2.6123657e+02 2.9166693e+02 5.7896777e+02 4.0380725e+02 5.5320792e-02]
[5.4653821e+02 9.9814087e+01 8.6509033e+02 2.1305472e+02 8.5708417e-02]
[4.0416705e+02 2.6778049e+02 7.2487976e+02 3.8080344e+02 5.7837050e-02]
[4.7541058e+02 2.9084387e+02 7.9413354e+02 4.0402386e+02 9.4671853e-02]
[3.0887506e+02 1.2337411e+02 6.2653229e+02 2.3610245e+02 5.3929359e-02]
[4.52255859e+02 1.22953285e+02 7.71123596e+02 2.36525085e+02
 8.02869201e-02]
[5.2550073e+02 1.4647357e+02 8.4031226e+02 2.6035840e+02 5.3360116e-02]
[5.2654205e+02 8.1211395e+00 7.6470966e+02 4.2790662e+02 9.3501098e-02]
``` 
No predicted score is bigger than 0.1.

I'm running out of my mind, I do have no idea what is wrong.

**Please reply to me if you see this issue. Please let me know too if you don't know what is wrong. Thanks!!** @eugenelawrence @hellock

**Comment by eugenelawrence** [comment]
You have set the pretrained weight to None. Maybe that's the key.

**Comment by herrickli** [comment]
rm -rf mmdetection/  [thumb down]

**Comment by cszer** [comment]
you should use pretrained true and use load from where you should past sent from pretrained to load from
example:
pretrained=true
load from=mask_rcnn_r50_fpn_1x_20181010-069fa190.pth
and also if you want to fine tune froze more than 1 stage

**Comment by xhqiui** [comment]
Maybe the pretrained in the configs isn't suitable,you can try the default configuration in  the section of the pretrained.

**Comment by wen0618** [comment]
> @eugenelawrence Thanks for your reply, but this is not the reason, below log info is under pretrained weight mask_rcnn_r50_fpn_1x_20181010-069fa190.pth, None is the later setting.
> Is there any other reasons, thanks.
Have you solved your problem?My result is poor too. The loss is less than 0.0015 but the mAP is not good.

**Comment by wen0618** [comment]
> I have not idea about how to make it work.
> I use mask_rpn
> There are 5 categorises in my custom dataset, and I changed the coco classes to my categories.
> And I use 2 gpu, so I reduce lr from `0.02` to `0.02 / 4`
> Here is my config file.
> 
> ```
> model = dict(
>     type='MaskRCNN',
>     pretrained='torch/checkpoints/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth',
>     #pretrained=None,
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         style='pytorch'),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         num_outs=5),
>     rpn_head=dict(
>         type='RPNHead',
>         in_channels=256,
>         feat_channels=256,
>         anchor_scales=[8],
>         anchor_ratios=[0.5, 1.0, 2.0],
>         anchor_strides=[4, 8, 16, 32, 64],
>         target_means=[.0, .0, .0, .0],
>         target_stds=[1.0, 1.0, 1.0, 1.0],
>         loss_cls=dict(
>             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
>         loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
>     bbox_roi_extractor=dict(
>         type='SingleRoIExtractor',
>         roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
>         out_channels=256,
>         featmap_strides=[4, 8, 16, 32]),
>     bbox_head=dict(
>         type='SharedFCBBoxHead',
>         num_fcs=2,
>         in_channels=256,
>         fc_out_channels=1024,
>         roi_feat_size=7,
>         num_classes=6,
>         target_means=[0., 0., 0., 0.],
>         target_stds=[0.1, 0.1, 0.2, 0.2],
>         reg_class_agnostic=False,
>         loss_cls=dict(
>             type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
>         loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
>     mask_roi_extractor=dict(
>         type='SingleRoIExtractor',
>         roi_layer=dict(type='RoIAlign', out_size=14, sample_num=2),
>         out_channels=256,
>         featmap_strides=[4, 8, 16, 32]),
>     mask_head=dict(
>         type='FCNMaskHead',
>         num_convs=4,
>         in_channels=256,
>         conv_out_channels=256,
>         num_classes=6,
>         loss_mask=dict(
>             type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)))
> # model training and testing settings
> train_cfg = dict(
>     rpn=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.7,
>             neg_iou_thr=0.3,
>             min_pos_iou=0.3,
>             ignore_iof_thr=-1),
>         sampler=dict(
>             type='RandomSampler',
>             num=256,
>             pos_fraction=0.5,
>             neg_pos_ub=-1,
>             add_gt_as_proposals=False),
>         allowed_border=0,
>         pos_weight=-1,
>         debug=False),
>     rpn_proposal=dict(
>         nms_across_levels=False,
>         nms_pre=2000,
>         nms_post=2000,
>         max_num=2000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.5,
>             neg_iou_thr=0.5,
>             min_pos_iou=0.5,
>             ignore_iof_thr=-1),
>         sampler=dict(
>             type='RandomSampler',
>             num=512,
>             pos_fraction=0.25,
>             neg_pos_ub=-1,
>             add_gt_as_proposals=True),
>         mask_size=28,
>         pos_weight=-1,
>         debug=False))
> test_cfg = dict(
>     rpn=dict(
>         nms_across_levels=False,
>         nms_pre=1000,
>         nms_post=1000,
>         max_num=1000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=dict(
>         score_thr=0.05,
>         nms=dict(type='nms', iou_thr=0.5),
>         max_per_img=100,
>         mask_thr_binary=0.5))
> # dataset settings
> dataset_type = 'CocoDataset'
> data_root = '/home/licheng/projects/mmdetection/data/coco/'
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
>     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>     dict(type='RandomFlip', flip_ratio=0.5),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(1333, 800),
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(type='Normalize', **img_norm_cfg),
>             dict(type='Pad', size_divisor=32),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img']),
>         ])
> ]
> data = dict(
>     imgs_per_gpu=2,
>     workers_per_gpu=2,
>     train=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/instances_train2017.json',
>         img_prefix=data_root + 'train2017/',
>         pipeline=train_pipeline),
>     val=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/instances_val2017.json',
>         img_prefix=data_root + 'val2017/',
>         pipeline=test_pipeline),
>     test=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/instances_val2017.json',
>         img_prefix=data_root + 'val2017/',
>         pipeline=test_pipeline))
> # optimizer
> optimizer = dict(type='SGD', lr=0.02 / 4, momentum=0.9, weight_decay=0.0001)
> optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
> # learning policy
> lr_config = dict(
>     policy='step',
>     warmup='linear',
>     warmup_iters=500,
>     warmup_ratio=1.0 / 3,
>     step=[8, 11])
> checkpoint_config = dict(interval=1)
> # yapf:disable
> log_config = dict(
>     interval=50,
>     hooks=[
>         dict(type='TextLoggerHook'),
>         # dict(type='TensorboardLoggerHook')
>     ])
> # yapf:enable
> evaluation = dict(interval=1)
> # runtime settings
> total_epochs = 12
> dist_params = dict(backend='nccl')
> log_level = 'INFO'
> work_dir = './work_dirs/mask_rcnn_r50_fpn_1x'
> load_from = None
> resume_from = None
> workflow = [('train', 1)]
> ```
> 
> I put 905 images in train dataset, and only 1 image in val dataset.
> After 12 epochs, this is the log info.
> 
> ```
> 2019-10-11 17:16:07,626 - INFO - Epoch [12][200/227]    lr: 0.00005, eta: 0:00:26, time: 1.067, data_time: 0.013, memory: 3818,
>  loss_rpn_cls: 0.0496, loss_rpn_bbox: 0.0131, loss_cls: 0.1310, acc: 97.4199, loss_bbox: 0.0573, loss_mask: 0.4235, loss: 0.6745
> ```
> 
> And I do add validate, here is the result.
> 
> ```
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
>  Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> ```
> 
> And I use the config file and `epoch_12.pth` to run the `test.py`, output file is 'result.pkl', `--eval bbox`, the output log is the same as below validate info.
> 
> Then I use `python tools/coco_eval.py result.pkl`, it says `assert isinstance(coco, COCO) AssertionError`.
> 
> I print the content of result.pkl, here are all the prediction bounding boxes:
> 
> ```
> [3.3848590e+02 1.4069824e+02 5.3549097e+02 2.0575418e+02 5.0295100e-02]
> [1.7246944e+02 2.9701807e+02 3.6649576e+02 3.6149133e+02 5.6047469e-02]
> [1.7711346e+01 4.1604980e+02 2.0808742e+02 4.8156598e+02 6.0481794e-02]
> [5.0730634e+02 5.9567677e+01 9.1988708e+02 2.7949777e+02 7.5444207e-02]
> [5.0661667e+02 2.0105237e+02 9.2023450e+02 4.2323883e+02 6.1535407e-02]
> [1.7433136e+02 2.9717792e+02 3.6482898e+02 3.6110904e+02 5.0828498e-02]
> [1.9520685e+01 4.1627609e+02 2.0668042e+02 4.8118680e+02 5.7543796e-02]
> [9.1576378e+01 2.6835748e+02 4.1394058e+02 3.7968976e+02 8.4639400e-02]
> [9.2929489e+01 9.9893806e+01 4.1266205e+02 2.1219266e+02 6.6862963e-02]
> [2.3507387e+02 9.9953766e+01 5.5520831e+02 2.1230498e+02 6.6346191e-02]
> [5.9234485e+02 2.9185373e+02 9.1278314e+02 4.0377466e+02 6.9933698e-02]
> [2.6123657e+02 2.9166693e+02 5.7896777e+02 4.0380725e+02 5.5320792e-02]
> [5.4653821e+02 9.9814087e+01 8.6509033e+02 2.1305472e+02 8.5708417e-02]
> [4.0416705e+02 2.6778049e+02 7.2487976e+02 3.8080344e+02 5.7837050e-02]
> [4.7541058e+02 2.9084387e+02 7.9413354e+02 4.0402386e+02 9.4671853e-02]
> [3.0887506e+02 1.2337411e+02 6.2653229e+02 2.3610245e+02 5.3929359e-02]
> [4.52255859e+02 1.22953285e+02 7.71123596e+02 2.36525085e+02
>  8.02869201e-02]
> [5.2550073e+02 1.4647357e+02 8.4031226e+02 2.6035840e+02 5.3360116e-02]
> [5.2654205e+02 8.1211395e+00 7.6470966e+02 4.2790662e+02 9.3501098e-02]
> ```
> 
> No predicted score is bigger than 0.1.
> 
> I'm running out of my mind, I do have no idea what is wrong.
> 
> **Please reply to me if you see this issue. Please let me know too if you don't know what is wrong. Thanks!!** @eugenelawrence @hellock



> I trained custom `pascal_voc dataset` with `cascade_rcnn_hrnetv2p_w32_20e.py`, I used all the data as trainval, and part of it as test, after 20 epochs, the loss decrease to 0.3, and the `log info` like this:
> 
> ```
> INFO - Epoch [16][450/715]    lr: 0.00250, eta: 3:52:14, time: 0.801, data_time: 0.004, memory: 9102, loss_rpn_cls: 0.0239, loss_rpn_bbox: 0.0093, s0.loss_cls: 0.1392, s0.acc: 96.1270, s0.loss_bbox: 0.0731, s1.loss_cls: 0.0549, s1.acc: 97.1621, s1.loss_bbox: 0.0480, s2.loss_cls: 0.0183, s2.acc: 98.4102, s2.loss_bbox: 0.0135, loss: 0.3802
> ```
> 
> And I used the checkpoint to run `test.py` and generate `result.pkl`, but after the I parsed the `.pkl` file, set score threshold 0.5, the result is not good, lots of images have no predictions.
> So what can I do to improve the performance or is there somewhere I forgot to modified.
> Thanks~

Have you solved your problem?My result is poor too. The loss is less than 0.0015 but the mAP is not good.

**Comment by wen0618** [comment]
@herrickli 
Have you solved your problem?My result is poor too. The loss is less than 0.0015 but the mAP is not good.

**Comment by herrickli** [comment]
@wen0618 Nope, but I find if don't load the pre-trained model, performance would be slightly better. So maybe the reason is we used improper model.

**Comment by wen0618** [comment]
> @wen0618 Nope, but I find if don't load the pre-trained model, performance would be slightly better. So maybe the reason is that we used improper model.

Thank you! I will try later.

**Comment by Seema1997** [comment]
Hello,
@herrickli Can you tell me, How you got both train and val accuracy in you result.which is:
 "INFO - Epoch [16][450/715]    lr: 0.00250, eta: 3:52:14, time: 0.801, data_time: 0.004, memory: 9102, loss_rpn_cls: 0.0239, loss_rpn_bbox: 0.0093, s0.loss_cls: 0.1392, s0.acc: 96.1270, s0.loss_bbox: 0.0731, s1.loss_cls: 0.0549, s1.acc: 97.1621, s1.loss_bbox: 0.0480, s2.loss_cls: 0.0183, s2.acc: 98.4102, s2.loss_bbox: 0.0135, loss: 0.3802

Through this command python tool/train,py configs/faster_rcnn_r50_fpn_1x.py I only got one accuracy in my result. Please help me I do have no idea what is wrong.

Thanks in Advance.

**Comment by herrickli** [comment]
@Seema1997 Hi, I didn’t change anything of the code, so the reason of your problem might be that we use different model.

**Comment by YAOYI626** [comment]
I got the same problem. 99% acc but 0% recall, very incrediable. I am helpless.
