### ISSUE TITLE
Close the mask branch in maskrcnn

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#1480]
Hi,

My dataset does not contain the mask field (segmentation). Hence in maskrcnn (mask_rcnn_r50_fpn_1x.py), I'm changing the following code to shut down the mask branch during training:

mask_head=dict(
        type='FCNMaskHead',
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=4,
        loss_mask=dict(
            type='CrossEntropyLoss', use_mask=**False**, loss_weight=1.0)))

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=**False**),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
#dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]

However, when I kick off the training, there is still an error on mask:

  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 215, in forward_train
    self.train_cfg.rcnn)
  File "/mmdetection/mmdet/models/mask_heads/fcn_mask_head.py", line 111, in get_target
    gt_masks, rcnn_train_cfg)
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 11, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable

Any suggestions? Thanks!

**Comment by ishann** [comment]
See [#102](https://github.com/open-mmlab/mmdetection/issues/102#issue-378317977). FPN Faster R-CNN is equivalent to Mask R-CNN without mask. Consider using a detection model for your task.

**Comment by shanggdlk** [comment]
> See [#102](https://github.com/open-mmlab/mmdetection/issues/102#issue-378317977). FPN Faster R-CNN is equivalent to Mask R-CNN without mask. Consider using a detection model for your task.

Thanks for the tips. Maskrcnn introduces some new staff compared to faster-rcnn (e.g., ROI_align). Is there a way to solve this error rather than using faster-rcnn instead?

**Comment by hellock** [comment]
Faster R-CNN is exactly what you want.

**Comment by SunNYNO1** [comment]
> See [#102](https://github.com/open-mmlab/mmdetection/issues/102#issue-378317977). FPN Faster R-CNN is equivalent to Mask R-CNN without mask. Consider using a detection model for your task.

sorry,I have a question, I find the baseline of faster rcnn R-50-FPN pytorch is 37.4 in github, however the baseline of mask  rcnn R-50-FPN pytorch is 38.2  in github,  could you help  me?
