### ISSUE TITLE
Adapting from Matterport's Mask-RCNN to mmdetection Mask-RCNN

### ISSUE THREAD

**Issue by MaddyThakker** [open-mmlab/mmdetection#1481]
Hi, I trained a Mask-RCNN using Matterport's Mask_RCNN [(link),](https://github.com/matterport/Mask_RCNN) unfortunately it does not have an implementation of Mask-Scoring RCNN. 
When training on Matterport's Mask-RCNN, I labeled my dataset using VIA Image annotator as done [here](https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46). Can I somehow use the same annotations and convert them so that I can train the mmdetection's Mask-RCNN. 
I labeled around 100 images and do not want them to annotate them again. 

Any help will be highly appreciated.

**Comment by hellock** [comment]
You can convert the annotations to the coco format and use it with mmdetection.
