### ISSUE TITLE
dist_train.sh hangs frequently when it runs with Python 3.5.2

### ISSUE THREAD

**Issue by priancho** [open-mmlab/mmdetection#1483]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
 Yes
2. The bug has not been fixed in the latest version.
 Yes

**Describe the bug**

When I run mmDetection with dist_train.sh, it frequently hangs.
For example, when I run it with 4 GPUs, it launches 4 Python processes with the command line argument "semaphore" in a successful scenario.
However, most times, only 1-3 such processes come up and the program just hangs.

With many tries&errors, I found that the cause of this problem is Python 3.5.2 which comes with Ubuntu 16.04.
After installing Anaconda with Python 3.7.3, the problem went away.

**Reproduction**
1. What command or script did you run?
```
export CUDA_VISIBLE_DEVICES=4,5,6,7
tools/dist_train.sh configs/test.py 4

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
We modified codes (network and data loading) and it worked w/o any problem if dist_train.sh is not used.

3. What dataset did you use?
MSCOCO for object detection and segmentation

**Environment**
 - OS: 16.04 LTS (Xenial Xerus)
 - GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
 - PyTorch version: 1.1.0
- How you installed PyTorch: pip install torch
- GPU model: V100 * 8
- CUDA and CUDNN version: CUDA-9.0, CUDNN-7
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.): Nothing special

**Error traceback**
If applicable, paste the error trackback here.
```
It hangs and no meaningful error messages come.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

I am not sure the exact reason.
It might be better to exclude Python 3.5.x from a supported version as a reasonable workaround.

**Comment by hellock** [comment]
Thanks for your report! This may not be easy to identify and fix. Usually we use 3.6 or 3.7 so that we did not run across such issues very often.
