### ISSUE TITLE
Kernel restart error in the demo code inference_demo.ipynb

### ISSUE THREAD

**Issue by szrw668** [open-mmlab/mmdetection#1486]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
For the inference_demo at https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb:
In [4]: # test a single image
img = 'demo.jpg'
**result = inference_detector(model, img)**

The inference_detector line will make the kernel restart and the result cannot be obtained.

**Reproduction**
1. What command or script did you run?
```
result = inference_detector(model, img)
```
Jupyter and Spyder give the same error.

2. Did you make any modifications on the code or config? Did you understand what you have modified?
NO
3. What dataset did you use?
COCO

**Environment**
 - OS: [CentOS 7]
 - GCC [4.8.5]
 - PyTorch version [1.2]
- How you installed PyTorch [conda]
- GPU model [1080Ti]
- CUDA and CUDNN version [10.1]
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
the kernel appears to have died. it will restart automatically
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
As stated in the documentation, gcc version >= 4.9 is required.

**Comment by szrw668** [comment]
Now updated gcc to gcc (GCC) 9.2.0, still the same problem in Juypter, Spyder or plain python command line:
**result = inference_detector(model, img)**
Error: Segmentation fault (core dumped)

Any other suggestions, everyone?

**Comment by WankingMachine** [comment]
cuda:10.0
cudnn:7.6.0
pytorch:1.2
gpu:1080ti
gcc:7.3
OS: CenOS 7.5
when I run to the line: inference_detector(model, img)
get the error: Segmentation fault
 I just download the model checkpoint in modelzoo and run the demo code given in GETTING_STARTED.md

**Comment by WankingMachine** [comment]
> Now updated gcc to gcc (GCC) 9.2.0, still the same problem in Juypter, Spyder or plain python command line:
> **result = inference_detector(model, img)**
> Error: Segmentation fault (core dumped)
> 
> Any other suggestions, everyone?

hello ,have you found any solutions

**Comment by szrw668** [comment]
> > Now updated gcc to gcc (GCC) 9.2.0, still the same problem in Juypter, Spyder or plain python command line:
> > **result = inference_detector(model, img)**
> > Error: Segmentation fault (core dumped)
> > Any other suggestions, everyone?
> 
> hello ,have you found any solutions

no luck.

**Comment by szrw668** [comment]
Hope the people who tried  to install and run mmdetection demo using the most recent code base can share their experience. This will give us some clues to see whether this is a common issue or accidental case.

**Comment by szrw668** [comment]
Update: switched gcc version from 9.2 to 7.3 and install again, the problem disappears. 

Although new error happens and I understand I need to recompile opencv from source to replace the opencv in anaconda. 
error: OpenCV(4.1.1) /io/opencv/modules/highgui/src/window.cpp:627: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
