### ISSUE TITLE
How can I get the pre-computed proposals for the Fast R-CNN?

### ISSUE THREAD

**Issue by goolhanrry** [open-mmlab/mmdetection#1487]
How should I generate the pickle file of proposals to feed it into Fast R-CNN?
Thanks!

**Comment by hellock** [comment]
You can just run the testing script to test an RPN model and obtain the proposals.

**Comment by goolhanrry** [comment]
Thank you so much!

**Comment by ElegantLin** [comment]
@hellock Hello, I want to train a Fast RCNN. I have trained a RPN using mmdetection and I have got the `.pth` file of RPN. What should I do next?

Thanks a lot.
