### ISSUE TITLE
Question about training Cityscape.

### ISSUE THREAD

**Issue by chituma110** [open-mmlab/mmdetection#1488]
I want to train cityscape using the config file "mmdetection/configs/cityscapes/faster_rcnn_r50_fpn_1x_cityscapes.py". The data is leftImg8bit_trainvaltest.zip and gtFine_trainvaltest.zip. 
However, the result is not satisfiled:

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.113
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.233
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.102
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.049
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.127
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.139
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.107
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.162
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.170
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.085
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.191
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.215

The official result is:
Backbone | Style | Lr schd | Scale | Mem (GB) | Train time (s/iter) | Inf time (fps) | box AP
R-50-FPN | pytorch | 1x | 800-1024 | 4.9 | 0.345 | 8.8 | 36

Could you show me each step including the preparing of data to help me to check my training process.

**Comment by yhcao6** [comment]
1. Prepare dataset:
https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md#prepare-datasets

2. Train the model as usual (you can download from https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/models/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes_20200227-afe51d5a.pth).

3. Evaluate the trained model, take [Mask R-CNN](https://github.com/open-mmlab/mmdetection/blob/master/configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py) as an example: 
./tools/dist_test.sh configs/test/mask_rcnn_r50_fpn_1x_cityscapes.py models/mask_rcnn_r50_fpn_1x_cityscapes_20200227-afe51d5a.pth 8 --eval cityscapes --out results.pkl
