### ISSUE TITLE
Random corp doesn't include in Semantc seg pipeline therefore not consistent

### ISSUE THREAD

**Issue by joeythegod** [open-mmlab/mmdetection#1489]
In the transform.py, SegResizeFlipPadRescale will do the same thing that training image did, but when we apply random crop, the semantic seg won't change, therefor the shape will meet an error.

**Comment by joeythegod** [comment]
Hi, I also want to check if our semantic class exceed 255, how can I adjust to use it. Currently my problem is I used coco image with different annotation (from 80 classes to 1k+ classes), I would like to add semantic branch but the semantic png image is annotated by its pixel value, will it matter if we don't re-map them? Or Semantic head's classes don't influence mask head classes at all?

**Comment by hellock** [comment]
Fixed in #1880
