### ISSUE TITLE
any plans and results for the SE154

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#1490]
I experiment the HTC model using the senet154 backbone models from cadene. And the result is only 42.3 which is lower than your resnext101 model which is 43.9. In the experiment, I used the DCN and multi-scale training. So if convenient,could you share your SENet154 pretrained model in your HTC paper?

**Comment by hellock** [comment]
You may expect it in a month.

**Comment by runzeer** [comment]
Hi，any plans for the SE154 results?
