### ISSUE TITLE
TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'

### ISSUE THREAD

**Issue by zihaozhang9** [open-mmlab/mmdetection#1493]
When I use [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r50_fpn_1x.py) to train my own data, workflow is set to [('train', 1)] and the training runs normally. When workflow is set to [('train', 1),('val', 1)], val reports the following error：
`  File "/media/nnir712/F264A15264A119FD/zzh/detect/mmcv/mmcv/runner/runner.py", line 265, in train                                                        [0/1828]
    self.model, data_batch, train_mode=True, **kwargs)
  File "/media/nnir712/F264A15264A119FD/zzh/detect/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/nnir712/F264A15264A119FD/zzh/detect/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/media/nnir712/F264A15264A119FD/zzh/detect/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'`

**Comment by LUCKMOONLIGHT** [comment]
I also have this problem. Who can help me?

**Comment by RayTang88** [comment]
I also meet it. did you solve it?

**Comment by hznuhisejeffrey** [comment]
perhaps reduce learn rate will solve your problem

**Comment by RayTang88** [comment]
Got it! i change the pipeline in ‘’val‘ from test_pipeline to train_pipeline, it work!

**Comment by RayTang88** [comment]
@boomLuo yeah！i think that is right, val pipeline miss Annotations when we use train.py, i change the code like you say, but i get another error.
maybe it is only for train?     
when i use dist_train.py,  workflow is set to [('train', 1)], it work!

**Comment by zihaozhang9** [comment]
> error

error logs?

**Comment by dimahwang88** [comment]
Have the same problem. I don't understand why test pipeline has to be used for validation.

**Comment by thaiKari** [comment]
Same problem here

**Comment by dimahwang88** [comment]
If you need to just print loss on validation set (data+GT) you may change to train_pipeline and in base.py change line 88 as follows:          
else:
            #return self.forward_train(img, img_meta, **kwargs)
             return self.forward_test(img, img_meta, **kwargs)

**Comment by yhcao6** [comment]
Thanks for reporting the bug. 

There is no gt in `test_pipeline` which leads this error. Here is a temporary solution:
1. Add a `val_pipiline` in the [config]( https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py):
```
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
```
2. Modify `data.val.pipeline`:
```
pipeline=val_pipeline,
```
https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py#L156

**Comment by korabelnikov** [comment]
@yhcao6 I had to invent exactly the same solution as above.
I also found out that all configs contain test pipeline for validation dataset. What is proper way for validation you used?

tensorflow-detection-api print a table with common metrics and put them into tensorboard to track progress and over-fitting. 

validation here just prints 'loss'. Is it expected output fromat?

**Comment by jemaromaster** [comment]
I'm currently working with [faster_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/faster_rcnn_r50_fpn_1x.py) and I am trying to also print the loss value for the VAL dataset. However I get the following error when I'm setting the workflow to [('train', 1), ('val', 1)]. 

`File "/notebooks/Git/pmi-jesus/mmcv/runner/runner.py", line 407, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/notebooks/Git/pmi-jesus/mmcv/runner/runner.py", line 310, in val
    self.model, data_batch, train_mode=False, **kwargs)
  File "/notebooks/Git/mmdetection/mmdet/apis/train.py", line 41, in batch_processor
    losses = model(**data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/notebooks/Git/pmi-jesus/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/notebooks/Git/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/notebooks/Git/mmdetection/mmdet/models/detectors/base.py", line 100, in forward
    return self.forward_train(img, img_meta, **kwargs)
**TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'**`

In the [config](https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/faster_rcnn_r50_fpn_1x.py) file, I already tried to use a custom pipeline instead of the test_pipeline but still I got the error. Does anyone know what might be happening?

**Comment by YanqingWu** [comment]
> Thanks for reporting the bug.
> 
> There is no gt in `test_pipeline` which leads this error. Here is a temporary solution:
> 
> 1. Add a `val_pipiline` in the [config](https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py):
> 
> ```
> val_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
>     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>     dict(type='RandomFlip', flip_ratio=0.0),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
> ]
> ```
> 
> 1. Modify `data.val.pipeline`:
> 
> ```
> pipeline=val_pipeline,
> ```
> 
> https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py#L156

@yhcao6 why not fix in the source code?

**Comment by huangrichen11** [comment]
> Thanks for reporting the bug.
> 
> There is no gt in `test_pipeline` which leads this error. Here is a temporary solution:
> 
> 1. Add a `val_pipiline` in the [config](https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py):
> 
> ```
> val_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
>     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>     dict(type='RandomFlip', flip_ratio=0.0),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
> ]
> ```
> 
> 1. Modify `data.val.pipeline`:
> 
> ```
> pipeline=val_pipeline,
> ```
> 
> https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py#L156

After add val_pipeline, But got the error as follow:
```
train/../datasets/pipelines/formating.py line178
img_meta[key] = results[key]
KeyError:'flip'
```

**Comment by SarahChane98** [comment]
> Thanks for reporting the bug.
> 
> There is no gt in `test_pipeline` which leads this error. Here is a temporary solution:
> 
>     1. Add a `val_pipiline` in the [config](https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py):
> 
> 
> ```
> val_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
>     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>     dict(type='RandomFlip', flip_ratio=0.0),
>     dict(type='Normalize', **img_norm_cfg),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
> ]
> ```
> 
>     1. Modify `data.val.pipeline`:
> 
> 
> ```
> pipeline=val_pipeline,
> ```
> 
> https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py#L156

Is it alright to just change data.val.pipeline to pipeline=train_pipeline? This worked for me.

**Comment by SuperCrystal** [comment]
> > Thanks for reporting the bug.
> > There is no gt in `test_pipeline` which leads this error. Here is a temporary solution:
> > ```
> > 1. Add a `val_pipiline` in the [config](https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py):
> > ```
> > 
> > 
> > ```
> > val_pipeline = [
> >     dict(type='LoadImageFromFile'),
> >     dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
> >     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
> >     dict(type='RandomFlip', flip_ratio=0.0),
> >     dict(type='Normalize', **img_norm_cfg),
> >     dict(type='Pad', size_divisor=32),
> >     dict(type='DefaultFormatBundle'),
> >     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
> > ]
> > ```
> > 
> > 
> > ```
> > 1. Modify `data.val.pipeline`:
> > ```
> > 
> > 
> > ```
> > pipeline=val_pipeline,
> > ```
> > 
> > 
> > https://github.com/open-mmlab/mmdetection/blob/82c533bee0de1a84f5959e257815eb7df4e69162/configs/mask_rcnn_r50_fpn_1x.py#L156
> 
> Is it alright to just change data.val.pipeline to pipeline=train_pipeline? This worked for me.

I think if you did it in this way, you will use your training dataset to do validation, and that it is what we won't want:) Because we want to see the validation performance on a dataset independent on the training one.

**Comment by hellock** [comment]
Here I explain what the issue is and why it happen. Documentations will be added.

For validation, we can use either losses or other metrics, but the pipelines to compute losses and mAP are different. The former is the same as training, and the latter is the same as testing.

Since the final model is evaluated with mAP, we adopt mAP as the default validation metric in MMDetection, so we need to use `test_pipline` for the val set.

The above validation is implemented with the [evaluation hook](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py), which is not included in the workflow, so we just specify `work_flow=[('train', 1)]` instead of `work_flow=[('train', 1), ('val', 1)]`. This is the recommended and default validation setting.

However, if we just want to observe losses in the val set instead of evaluating mAP, we can specify `work_flow=[('train', 1), ('val', 1)]` and use the `train_pipeline`.

**Comment by ZhenYiRan** [comment]
> Here I explain what the issue is and why it happens. Documentations will be added.
> 
> For validation, we can use either losses or other metrics, but the pipelines to compute losses and mAP are different. The former is the same as training, and the latter is the same as testing.
> 
> Since the final model is evaluated with mAP, we adopt mAP as the default validation metric in MMDetection, so we need to use `test_pipline` for the val set.
> 
> The above validation is implemented with the [evaluation hook](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py), which is not included in the workflow, so we just specify `work_flow=[('train', 1)]` instead of `work_flow=[('train', 1), ('val', 1)]`. This is the recommended and default validation setting.
> 
> However, if we just want to observe losses in the val set instead of evaluating mAP, we can specify `work_flow=[('train', 1), ('val', 1)]` and use the `train_pipeline`.

Thanks a lot!!!

**Comment by LIQiushui2427** [comment]
> > Here I explain what the issue is and why it happens. Documentations will be added.
> > For validation, we can use either losses or other metrics, but the pipelines to compute losses and mAP are different. The former is the same as training, and the latter is the same as testing.
> > Since the final model is evaluated with mAP, we adopt mAP as the default validation metric in MMDetection, so we need to use `test_pipline` for the val set.
> > The above validation is implemented with the [evaluation hook](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py), which is not included in the workflow, so we just specify `work_flow=[('train', 1)]` instead of `work_flow=[('train', 1), ('val', 1)]`. This is the recommended and default validation setting.
> > However, if we just want to observe losses in the val set instead of evaluating mAP, we can specify `work_flow=[('train', 1), ('val', 1)]` and use the `train_pipeline`.
> 
> Thanks a lot!!!

I met the same issues when i trainning Mask2former.. I think we should make a update:)

**Comment by zihaozhang9** [comment]
我已收到您发送的邮件。我会及时查看。

**Comment by lijoe123** [comment]
> > Here I explain what the issue is and why it happens. Documentations will be added.
> > For validation, we can use either losses or other metrics, but the pipelines to compute losses and mAP are different. The former is the same as training, and the latter is the same as testing.
> > Since the final model is evaluated with mAP, we adopt mAP as the default validation metric in MMDetection, so we need to use  for the val set.`test_pipline`
> > The above validation is implemented with the [evaluation hook](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py), which is not included in the workflow, so we just specify  instead of . This is the recommended and default validation setting.`work_flow=[('train', 1)]``work_flow=[('train', 1), ('val', 1)]`
> > However, if we just want to observe losses in the val set instead of evaluating mAP, we can specify  and use the .`work_flow=[('train', 1), ('val', 1)]``train_pipeline`
> 
> Thanks a lot!!!

Hello, i had met the same error. But i don't understand what that mean, and how to set it. Do i need to replace the `pipeline=test_pipeline` with `work_flow=[('train', 1)]`? like this?
![image](https://user-images.githubusercontent.com/86214036/208076774-5b13ec94-bc7d-4ab1-992f-b92c013acf0a.png)
Thank you very much!

**Comment by zihaozhang9** [comment]
我已收到您发送的邮件。我会及时查看。

**Comment by Tensorrrrrr** [comment]
> > > Here I explain what the issue is and why it happens. Documentations will be added.
> > > For validation, we can use either losses or other metrics, but the pipelines to compute losses and mAP are different. The former is the same as training, and the latter is the same as testing.
> > > Since the final model is evaluated with mAP, we adopt mAP as the default validation metric in MMDetection, so we need to use  for the val set.`test_pipline`
> > > The above validation is implemented with the [evaluation hook](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py), which is not included in the workflow, so we just specify  instead of . This is the recommended and default validation setting.`` work_flow=[('train', 1)]``work_flow=[('train', 1), ('val', 1)] ``
> > > However, if we just want to observe losses in the val set instead of evaluating mAP, we can specify  and use the .`` work_flow=[('train', 1), ('val', 1)]``train_pipeline ``
> > 
> > 
> > Thanks a lot!!!
> 
> @ZhenYiRan Hello, i had met the same error. But i don't understand what that mean, and how to set it. Do i need to replace the `pipeline=test_pipeline` with `work_flow=[('train', 1)]`? like this? ![image](https://user-images.githubusercontent.com/86214036/208076774-5b13ec94-bc7d-4ab1-992f-b92c013acf0a.png) Thank you very much!

Do you slove it? I met the same problem.

**Comment by zihaozhang9** [comment]
我已收到您发送的邮件。我会及时查看。
