### ISSUE TITLE
run cascade_rcnn_hrnetv2p_w48 and cascade_mask_rcnn_hrnetv2p_w48 result  is None

### ISSUE THREAD

**Issue by xujin1184104394** [open-mmlab/mmdetection#1496]
code：

from mmdet.apis import init_detector, inference_detector, show_result
import mmcv
from tqdm import tqdm
# config_file = 'configs/hrnet/cascade_mask_rcnn_hrnetv2p_w32_20e.py'
# checkpoint_file = 'checkpoints/cascade_mask_rcnn_hrnetv2p_w48_20e_20190810-d04a1415.pth'

config_file = 'configs/hrnet/cascade_rcnn_hrnetv2p_w32_20e.py'
checkpoint_file = 'checkpoints/cascade_rcnn_hrnetv2p_w48_20e_20190810-f40ed8e1.pth'

# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

if 1:
    # video_path = 'videoplayback.mp4'
    video_path = 'video.mp4'
    video = mmcv.VideoReader(video_path)
    for frame in tqdm(video):
        result = inference_detector(model, frame)
        show_result(frame, result, model.CLASSES, wait_time=1)

**Comment by Edgis** [comment]
i have met the same question, have you resolve this problem?

**Comment by xujin1184104394** [comment]
I have solved it. Obtained by modifying other configuration files.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Edgis"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月13日(星期一) 晚上9:35
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送： &nbsp;“徐缙” <1184104394@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题： &nbsp;回复：[open-mmlab / mmdetection]运行级联_rcnn_hrnetv2p_w48和级联_mask_rcnn_hrnetv2p_w48结果为None（＃1496）




我遇到了同样的问题，您解决了这个问题吗？
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by Edgis** [comment]
> I have solved it. Obtained by modifying other configuration files.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Edgis"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月13日(星期一) 晚上9:35 收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;; 抄送： &nbsp;“徐缙” <1184104394@qq.com&gt;;“作者” <author@noreply.github.com&gt;; 主题： &nbsp;回复：[open-mmlab / mmdetection]运行级联_rcnn_hrnetv2p_w48和级联_mask_rcnn_hrnetv2p_w48结果为None（＃1496） 我遇到了同样的问题，您解决了这个问题吗？ — 您收到此消息是因为您创建了线程。 直接回复此电子邮件，在GitHub上查看，或取消订阅。

can you tell me the detailed modification?

**Comment by amr4i** [comment]
Can you point out the modifications you made to the config file?

**Comment by hhaAndroid** [comment]
Is there still a problem with the latest version now?
