### ISSUE TITLE
Don't know how to get started with a Docker

### ISSUE THREAD

**Issue by prakharg24** [open-mmlab/mmdetection#1499]
Hi,

I am trying to get mmdetection working and I tried various methods of installing the library. However, there seems to be some conflict with the CUDA versions and GCC versions present in my machine. So, instead I decided to install the docker image.

The instruction only have one line of code for Docker installation,
```
docker build -t mmdetection docker/
```

I ran the code above and it downloaded and installed a lot of things. Finally it was finished with what seemed like everything was successfully installed.

Just to check whether the docker was now present in my system, I did this,
```
sudo docker images
```

I got the following output
```
REPOSITORY          TAG                             IMAGE ID            CREATED             SIZE
mmdetection         latest                          67f97b78f88d        22 minutes ago      7.47GB
pytorch/pytorch     1.1.0-cuda10.0-cudnn7.5-devel   1be771bff6d1        5 months ago        6.94GB
```

Now I don't know how to run the docker image.

I tried 
```
docker run mmdetection
```

But it just exited without any output or visible activity of any other kind after 4-5 seconds.

I am new to the idea of using docker images. Can anyone point tell me how to open the docker image, run my code in this image, edit it etc. or maybe point me to a good tutorial that can explain this all?

Thank you

**Comment by mosheliv** [comment]
try something along the lines of :

sudo docker run --shm-size=2048m -it -v `pwd`:/lh -v
/mnt/2t1/oid2019:/oid2019 -v /mnt/m2:/m2 -v /mnt/2t1/coco:/coco mmdetection

the -shm-size will allow some of the larger models to run
the -it will give you prompt
the -v maps the a directory from the host to a directory inside the image

**Comment by prakharg24** [comment]
Thank you. It works!!
