### ISSUE TITLE
did this paper can download "FishNet: A Versatile Network Backbone for Image Region and Pixel Level Prediction“?

### ISSUE THREAD

**Issue by mlinxiang** [open-mmlab/mmdetection#15]

**Comment by kevin-ssy** [comment]
Hi,

FishNet will be included and updated later in mmdet. Both the paper and the code will be released in the late Oct.

Thank you for your interest.

**Comment by sunpeng981712364** [comment]
> Hi,
> 
> FishNet will be included and updated later in mmdet. Both the paper and the code will be released in the late Oct.
> 
> Thank you for your interest.
where is the fishnet?
