### ISSUE TITLE
TypeError: object of type 'DataContainer' has no len()

### ISSUE THREAD

**Issue by prakharg24** [open-mmlab/mmdetection#1501]
I installed the Docker image as mentioned in install.md and then tried testing the Faster RCNN model using the instructions provided in Getting_started.md

I ran the following code
```
python tools/test.py configs/faster_rcnn_r50_fpn_1x.py checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth --show
```

I got the following output
```
loading annotations into memory...
Done (t=0.59s)
creating index...
index created!
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 224, in <module>
    main()
  File "tools/test.py", line 184, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 26, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 140, in forward
    return self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 88, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 79, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 231, in simple_test
    x, img_meta, self.test_cfg.rpn) if proposals is None else proposals
  File "/mmdetection/mmdet/models/detectors/test_mixins.py", line 10, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 216, in get_bboxes
    for img_id in range(len(img_metas)):
TypeError: object of type 'DataContainer' has no len()
```

I have downloaded the checkpoint file and saved it in the checkpoints folder as mentioned above. I have also downloaded the COCO data and placed it in the directory as instructed in install.md

I am not able to understand the exact reason of the error.
What I can say is that this term is causing the error,
```
len(img_metas)
```

So I just printed the object right before where the error is caused
```
print(img_metas)
```
and I got the output
```
DataContainer([[{'filename': 'data/coco/val2017/000000397133.jpg', 'ori_shape': (427, 640, 3), 'img_shape': (800, 1199, 3), 'pad_shape': (800, 1216, 3), 'scale_factor': 1.873536299765808, 'flip': False, 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}}]])
```
if this helps in any way.

Please help me understand the error.
Thank you

**Comment by jetsmith** [comment]
@prakharg24 i got the same problem while i run test.py with grid-rcnn-r50, it is strange that the type of _img_metas_ is <class 'mmcv.parallel.data_container.DataContainer'>,  it has no len(), have you solved it?

**Comment by desmondlzy** [comment]
also got the same problem......... not just on faster rcnn but also on other models

**Comment by ZwwWayne** [comment]
Hi @desmondlzy @jetsmith ,

Could you try to use the option `--out ./debug.pkl` rather than `--show` to see what happen?
I do not have the GPU host now so I cannot use the `--show` option, but I am checking the code to see what happens.

**Comment by desmondlzy** [comment]
@ZwwWayne @jetsmith  I kind of get the problem solved. It could be very likely that this script requires a GPU environment. Once I switched to GPU host, the problem disappeared in no time. 

Hope it helps!

**Comment by sunwencanUp** [comment]
> Hi @desmondlzy @jetsmith ,
> 
> Could you try to use the option `--out ./debug.pkl` rather than `--show` to see what happen?
> I do not have the GPU host now so I cannot use the `--show` option, but I am checking the code to see what happens.

(openmmlab) root@kc-PowerEdge-T630:~/mmdetection# python tools/test.py configs/faster_rcnn_r50_fpn_1x.py checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth --out ./debug.pkl
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[                                                  ] 0/1, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 224, in <module>
    main()
  File "tools/test.py", line 184, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 26, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/root/anaconda3/envs/openmmlab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/openmmlab/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 140, in forward
    return self.module(*inputs, **kwargs)
  File "/root/anaconda3/envs/openmmlab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/root/mmdetection/mmdet/models/detectors/base.py", line 102, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/root/mmdetection/mmdet/models/detectors/base.py", line 93, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/root/mmdetection/mmdet/models/detectors/two_stage.py", line 270, in simple_test
    x, img_meta, self.test_cfg.rpn) if proposals is None else proposals
  File "/root/mmdetection/mmdet/models/detectors/test_mixins.py", line 10, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/root/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/root/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 261, in get_bboxes
    for img_id in range(len(img_metas)):
TypeError: object of type 'DataContainer' has no len()

**Comment by sunwencanUp** [comment]
> @ZwwWayne @jetsmith I kind of get the problem solved. It could be very likely that this script requires a GPU environment. Once I switched to GPU host, the problem disappeared in no time.
> 
> Hope it helps!

how to switched to GPU host?

**Comment by ZwwWayne** [comment]
> > @ZwwWayne @jetsmith I kind of get the problem solved. It could be very likely that this script requires a GPU environment. Once I switched to GPU host, the problem disappeared in no time.
> > Hope it helps!
> 
> how to switched to GPU host?

Do you run the code with at least one GPU card or just with CPU?

**Comment by ZwwWayne** [comment]
> @ZwwWayne @jetsmith I kind of get the problem solved. It could be very likely that this script requires a GPU environment. Once I switched to GPU host, the problem disappeared in no time.
> 
> Hope it helps!

Thanks a lot!

It seems that the current script needs to run with at least one GPU now and we may not test it on CPU before. We will check it further.

**Comment by sunwencanUp** [comment]
my env is GPU.

发至realJacky‘s iPhone

**Comment by ZwwWayne** [comment]
I tried the same command with a GPU as reported in this issue:
`python tools/test.py configs/faster_rcnn_r50_fpn_1x.py checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth --show`,
but I met no bug.

However, when I did not provide GPU and ran the command, I met this bug.

So for now, I am certain that this bug is caused by running scripts without using GPU.

A temporary solution is to do the inference with at least one GPU (please make sure you indeed use the GPU by, e.g., torch.cuda.is_avaliable() first). I will check the bug further in the mmcv.

**Comment by wpc2333** [comment]
I have the same problem, and I solved it.  just update mmcv to the latest version.
`pip uninstall mmcv-full`
`pip install mmcv-full`

modify  `mmdet/__init__.py`    `mmcv_maximum_version = '1.3.6'`

**Comment by Lature-Yang** [comment]
> I have the same problem, and I solved it. just update mmcv to the latest version.
> `pip uninstall mmcv-full`
> `pip install mmcv-full`
> 
> modify `mmdet/__init__.py` `mmcv_maximum_version = '1.3.6'`

Perfect~
