### ISSUE TITLE
What is the best configuration/model to make text detection? 

### ISSUE THREAD

**Issue by ShroukMansour** [open-mmlab/mmdetection#1503]
I found a lot of models in the model zoo but can't determine which one would give the best results in text detection, for scene-text images or/and document-text images. @ramkakarala  @tjsongzw  @lindahua  @ychfan @Erotemic  Any help, please!

**Comment by Erotemic** [comment]
I don't know if anyone has a definitive answer to this problem. Its going to heavily depend on the specifics of your problem. I suggest you try several models and evaluate them to determine which is best for you. If you do this evaluation consider reporting back with your findings!
