### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by gsx0015** [open-mmlab/mmdetection#1508]
when install mmdetection, 
I try to execute "python setup.py develop", it said "error: command 'x86_64-linux-gnu-gcc' failed with exit status 1"
how to fix it?Thanks!

**Comment by Mengman** [comment]
what's you gcc version?

check you /usr/bin directory to see if there has  'x86_64-linux-gnu-gcc'  or 'x86_64-linux-gnu-gcc-6', 'x86_64-linux-gnu-gcc-7'

**Comment by smoolya17** [comment]
I faced the same problem and when I checked 

> ls -l /usr/bin/ 

my gcc was pointing towards gcc-7

> lrwxrwxrwx 1 root root           5 May 20 21:38  x86_64-linux-gnu-gcc -> gcc-7
> lrwxrwxrwx 1 root root           5 Apr 12  2018  x86_64-linux-gnu-gcc-5 -> gcc-5

I am gonna check it by pointing towards gcc-5
