### ISSUE TITLE
CUDA out of memory after training several iterations

### ISSUE THREAD

**Issue by SuckChen** [open-mmlab/mmdetection#1511]
**Describe the bug**
I run the latest version of MMDetetcion, resize image to (1024,512)
My dataset has 3107 images ,
only one GPU so learningrate set to 0.00125
after training several iterations the code automatically terminated itself,
this problem confuses me a lot.
The following log is the point where My code stopped 
```
2019-10-07 07:48:43,181 - INFO - Epoch [1][1950/3107]	lr: 0.00125, eta: 4:56:24, time: 0.564, data_time: 0.117, memory: 4101, loss_rpn_cls: 0.0957, loss_rpn_bbox: 0.0678, s0.loss_cls: 0.1250, s0.acc: 98.1172, s0.loss_bbox: 0.0232, s1.loss_cls: 0.0466, s1.acc: 98.5898, s1.loss_bbox: 0.0101, s2.loss_cls: 0.0185, s2.acc: 98.8906, s2.loss_bbox: 0.0013, loss: 0.3882
```
**My Device**
```
GeForce GTX 1080  8116MiB
 NVIDIA-SMI 415.27    
 Driver Version: 415.27       
 CUDA Version: 10.0 
```

**Comment by Wulingtian** [comment]
这不是天池的布匹疵点智能识别比赛嘛，一张图片包含的目标过多导致oom的

**Comment by LostStars3** [comment]
我在mmcv的runner里面加了 torch.cuda.empty_cache()，就不会出现显存使用越来越多的情况。
貌似mmdet/mmcv更新了几次以后有显存泄露的问题，在老版本用efficientNet当backbone显存占用很少，在新版本总是报oom

**Comment by KooSung** [comment]
@LostStars3 请问mmcv runner的哪部分添加 torch.cuda.empty_cache()？

**Comment by LostStars3** [comment]
你好，这是我的py文件，可以通过搜索这个函数找到添加的位置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ko Sung"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月14日(星期一) 下午4:25
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"。"<290225924@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] CUDA out of memory after training several iterations (#1511)




@LostStars3 请问mmcv runner的哪部分添加 torch.cuda.empty_cache()？

**Comment by hellock** [comment]
#1575
