### ISSUE TITLE
base_anchor Explanation

### ISSUE THREAD

**Issue by BangguWu** [open-mmlab/mmdetection#1515]
tensor([[-83., -37.,  98.,  52.],
        [-56., -56.,  71.,  71.],
        [-37., -83.,  52.,  98.]], device='cuda:0')
I print the base_anchor, but I can not understand the four numbers of each line. Why the first two are negative numbers, the last two are positive numbers and it's meaning. Looking forward to your reply.

**Comment by hellock** [comment]
It is the anchor coordinates represented as [x_min, y_min, x_max, y_max]. You may refer to the Faster R-CNN paper for more details.

**Comment by BangguWu** [comment]
Thank you for your reply, I read the paper carefully and already understood the details, thank you again.
