### ISSUE TITLE
AP and AR = 0.000

### ISSUE THREAD

**Issue by hznuhisejeffrey** [open-mmlab/mmdetection#1518]
hello,everyone.
I used my own dataset to train on Cascade R-CNN Resnet50.After 80 epoch, I run tools/test.py to evalue my model and got results as follows:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001

why AP and AR is so low?
I tried to show the result images, it looks ok and the prediction of every image is very accurate. Now I'm very confused, please help me!

**Comment by hznuhisejeffrey** [comment]
I checked my test annotations and found my category_id is incorrect. Now it's OK.

**Comment by qa8306202** [comment]
I encounter the same problem, too.
Could u please tell me how you deal with it?

**Comment by DoveJay** [comment]
> I checked my test annotations and found my category_id is incorrect. Now it's OK.

could u tell me more details?
how and where to check your annotations

**Comment by DoveJay** [comment]
> I checked my test annotations and found my category_id is incorrect. Now it's OK.

It still doesn't work for me

**Comment by ZhengHeZhe** [comment]
> I checked my test annotations and found my category_id is incorrect. Now it's OK.

Could u please tell me how did you solve the problem? What have you changed?
