### ISSUE TITLE
stuffthingmaps

### ISSUE THREAD

**Issue by Beam-wi** [open-mmlab/mmdetection#1519]

**Comment by Beam-wi** [comment]
我有个问题请问您一下，我在训练时  有些需要 stuffthingmaps 数据，请问这个数据是什么？我怎么得到？

**Comment by LL-Lee** [comment]
> 我有个问题请问您一下，我在训练时 有些需要 stuffthingmaps 数据，请问这个数据是什么？我怎么得到？

https://github.com/nightrome/cocostuff/blob/master/README.md
