### ISSUE TITLE
RetinaNet with Mask head

### ISSUE THREAD

**Issue by fujenchu** [open-mmlab/mmdetection#152]
Thanks for your great works!
I am wondering if the RetinaNet can be added with a mask head? If so, could you kindly provide an example (like how to modify current retinanet_r50_fpn_1x.py)? Thank you very much!

**Comment by hellock** [comment]
You may not be able to add a mask head to RetinaNet by just modifying the config file. You need to refer to [TwoStageDetector](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/two_stage.py) for adding mask heads.
