### ISSUE TITLE
Inconsistency in optimiser initialisation

### ISSUE THREAD

**Issue by hoonkai** [open-mmlab/mmdetection#1521]
Hi

I'm browsing through the training code and noticed these few lines if the model contains parameters with `requires_grad=False`:

``` python
        for name, param in model.named_parameters():
            param_group = {'params': [param]}
            if not param.requires_grad:
                # FP16 training needs to copy gradient/weight between master
                # weight copy and model weight, it is convenient to keep all
                # parameters here to align with model.parameters()
                params.append(param_group)
                continue
```
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L116-L123

Notably, the param with `requires_grad=False` is added to `params` which is later used for initialising the optimiser:

``` python
        return optimizer_cls(params, **optimizer_cfg)
```
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L140

However, the constructor of `Optimizer` has the following:
``` python
        for param_group in param_groups:
            self.add_param_group(param_group)
```
https://github.com/pytorch/pytorch/blob/master/torch/optim/optimizer.py#L50-L51

where each param group without the default keys are initialised with the default values. Now, if a parameter has `requires_grad=False`, shouldn't it be ignored by the optimiser entirely? How come params with `requires_grad=False` are considered by the optimiser and are initialised with default `lr`, `weight_decay`, etc. values?

**Comment by shipeizhen** [comment]
I have the same doubt with you.

**Comment by yhcao6** [comment]
https://github.com/open-mmlab/mmdetection/pull/520#discussion_r333830670
