### ISSUE TITLE
How the parameter 'with_crowd' works?

### ISSUE THREAD

**Issue by hdjsjyl** [open-mmlab/mmdetection#1525]
How the parameter 'with_crowd' works? I did not find the place to cope with 'bbox_ignore', but the program has this parameter. Any advice will be appreciated, thanks

**Comment by hellock** [comment]
Ignored bboxes are used when assigning the targets, see [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/assigners/max_iou_assigner.py#L47).

**Comment by hdjsjyl** [comment]
@hellock  Got it, thanks
