### ISSUE TITLE
Claswise mAP

### ISSUE THREAD

**Issue by bond9779** [open-mmlab/mmdetection#1526]
How to get the classwise mAP of a given dataset?

The below command gives the overall mAP:
`python3 tools/test.py --config/<config_name> checkpoint/<checkpoint_file_name> --eval bbox segm --show/--out`   

But is there a way to get the classwise mAP from this?

**Comment by bond9779** [comment]
@hellock

**Comment by ZwwWayne** [comment]
Hi @bond9779 ,

**Comment by bond9779** [comment]
Thanks for the prompt reply @ZwwWayne :)
I will check the link provided by you

**Comment by ZwwWayne** [comment]
> Thanks for the prompt reply @ZwwWayne :)
> I will check the link provided by you

Hi @bond9779 , I tried to run the script by myself and find that it does not show the class-wise mAP but shows other details that might help you to analyze.

So I added some code in the script and proposed a PR. You can check this link https://github.com/open-mmlab/mmdetection/pull/1549
It can show the class-wise mAP for both segm and bbox now by simply adding `--with_ap` option in the running command.

Hope it could help.

**Comment by ZwwWayne** [comment]
The PR https://github.com/open-mmlab/mmdetection/pull/1549 is approved, so current master branch support to view classwise mAP now.

I am going to close this issue, feel free to reopen it if you have any further questions.

**Comment by Cli98** [comment]
> The PR #1549 is approved, so current master branch support to view classwise mAP.
> 
> I am going to close this issue, feel free to reopen it if you have any further questions.

Why u need to PR this? coco provided this function.
