### ISSUE TITLE
inference_detector with multiple images?

### ISSUE THREAD

**Issue by Kaeseknacker** [open-mmlab/mmdetection#1527]
Is it possible to call inference_detector (mmdet/apis/inference.py) with multiple images (list of image-paths)? The doku says yes, but calling the function with a list of image paths throws an exception. Does anyone have any idea what to change, so that multiple images are possible?
```python
# build the data pipeline
test_pipeline = [LoadImage()] + cfg.data.test.pipeline[1:]
test_pipeline = Compose(test_pipeline)
# prepare data
data = dict(img=img)
data = test_pipeline(data)
data = scatter(collate([data], samples_per_gpu=1), [device])[0]
```
For a Python newbie, these few lines of code are very confusing.

**Comment by hellock** [comment]
Are you seeking for a high-level api or low-level modifications?
For the former, you may simply wrap the `inference_detector()` method. See more details on the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#high-level-apis-for-testing-images). For the latter, you may refer to #939.

**Comment by hellock** [comment]
@Kaeseknacker Actually it won't be "much" faster. We have tried forward the network with multiple images but it is only slightly faster under some circumstance (e.g., input images have the same resolution), and even slower sometimes.

**Comment by hellock** [comment]
#1833

**Comment by minan19605** [comment]
my code for inference multiple images in one directory, just for your reference:

from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv
#import matplotlib.pyplot as plt
import cv2
import glob
import os
import sys
import time
import argparse

'''
python tools/my_inference.py \
    --cfg configs/my_config/htc_without_semantic_r50_fpn_1x_coco_linux.py \
    --output-dir work_dirs/htc/20200608/infer_paper/ \
    --wts work_dirs/htc/20200608/epoch_200.pth \
    ../coco/infer_img_dir
'''

def parse_args():
    parser = argparse.ArgumentParser(description='End-to-end inference')
    parser.add_argument(
        '--cfg',
        dest='cfg',
        help='cfg model file (/path/to/model_config.yaml)',
        default=None,
        type=str
    )
    parser.add_argument(
        '--wts',
        dest='weights',
        help='weights model file (/path/to/model_weights.pkl)',
        default=None,
        type=str
    )
    parser.add_argument(
        '--output-dir',
        dest='output_dir',
        help='directory for visualization pdfs (default: /tmp/infer_simple)',
        default='/tmp/infer_simple',
        type=str
    )
    parser.add_argument(
        '--image-ext',
        dest='image_ext',
        help='image file name extension (default: jpg)',
        default='jpg',
        type=str
    )
    parser.add_argument(
        '--always-out',
        dest='out_when_no_box',
        help='output image even when no object is found',
        action='store_true'
    )
    parser.add_argument(
        '--output-ext',
        dest='output_ext',
        help='output image file format (default: jpg)',
        default='jpg',
        type=str
    )
    parser.add_argument(
        '--thresh',
        dest='thresh',
        help='Threshold for visualizing detections',
        default=0.3,
        type=float
    )
    parser.add_argument(
        'im_or_folder', help='image or folder of images', default=None
    )
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)
    return parser.parse_args()

def main(args):
    
    config_file = args.cfg
    checkpoint_file = args.weights
    thresh=args.thresh
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
    #model = init_detector(config_file, checkpoint_file, device='cpu')

    if os.path.isdir(args.im_or_folder):
        im_list = glob.iglob(args.im_or_folder + '/*.' + args.image_ext)
    else:
        im_list = [args.im_or_folder]
    
    total_t = time.time()
    for i, im_name in enumerate(im_list):
        print('Get img {}'.format(im_name))
        one_t = time.time()
        if(args.image_ext == args.output_ext):
            output_name = os.path.join(
                args.output_dir, '{}'.format(os.path.basename(im_name))
            )
        else:
            output_name = os.path.join(
                args.output_dir, '{}'.format(os.path.basename(im_name) + '.' + args.output_ext)
            )
        
        result = inference_detector(model, im_name)
        if hasattr(model, 'module'):
            model = model.module
        pred_img = model.show_result(im_name, result, score_thr=thresh, show=False)
        cv2.imwrite(output_name,pred_img)
        print('write {}'.format(output_name))
        print('One image time {:.3f}s'.format(time.time()-one_t))
    print("Total inference time is {:.3f}s".format(time.time() - total_t))

if __name__ == '__main__':
    args = parse_args()
    main(args)

**Comment by zsc15** [comment]
I think there are some bugs in in **inference_detector**. When I trained vfnet using my datasets, I used **inference_detector** function to get visualization of single image with pretained model ,i.e.**. latest.pth** file, I got following bugs. So how do I to fix this problem?  Who can help me?, think you!!!


`Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-848253714dd5>", line 1, in <module>
    runfile('/workspace/mmdetection/visual_one_img.py', wdir='/workspace/mmdetection')
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/workspace/mmdetection/visual_one_img.py", line 30, in <module>
    result = inference_detector(model, img)
  File "/workspace/mmdetection/mmdet/apis/inference.py", line 177, in inference_detector
    data = scatter(data, [device])[0]
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 44, in scatter
    return scatter_map(inputs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 34, in scatter_map
    out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 29, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 31, in scatter_map
    out = list(map(list, zip(*map(scatter_map, obj))))
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 27, in scatter_map
    return Scatter.forward(target_gpus, obj.data)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/_functions.py", line 72, in forward
    streams = [_get_stream(device) for device in target_gpus]
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/_functions.py", line 72, in <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 115, in _get_stream
    if _streams[device] is None:
TypeError: list indices must be integers or slices, not torch.device
`

**Comment by leemengwei** [comment]
> @Kaeseknacker Actually it won't be "much" faster. We have tried forward the network with multiple images but it is only slightly faster under some circumstance (e.g., input images have the same resolution), and even slower sometimes.

Why is that batch inference only slightly faster instead of multiple times faster? It's because of: GPU hardware/cuda version/python limitation/pytorch or mmdetection implementation? Could you share more insights? Thanks!
