### ISSUE TITLE
Pretrained RPN in Faster RCNN

### ISSUE THREAD

**Issue by wsnedy** [open-mmlab/mmdetection#153]
Hi, If I only want to load the pretrained RPN in Faster R-CNN, what should I do ? Do I need to modify the code in mmdet? or I can do this just by modify the config files

**Comment by hellock** [comment]
You can simply load Faster R-CNN weights and use RPN configs.

**Comment by wsnedy** [comment]
Thx, I try to load RPN, and it works!

**Comment by Flyooofly** [comment]
> Thx, I try to load RPN, and it works!

How do you do it in detail, please help me, thank you
