### ISSUE TITLE
mmdetection in Jetson tx2 jetpack 4.2

### ISSUE THREAD

**Issue by fadonoso** [open-mmlab/mmdetection#1530]
Hi communnity,

has someone installed mmdetection on jetson tx2?  I´ve been trying with no success. 

Please some light with this. And if is not possible also is good to know.

Regards

**Comment by fadonoso** [comment]
Guys,
this is the error Im getting now:

Installed /home/jetson/Builds/mmdetection
Processing dependencies for mmdet==1.0rc0+ff28413
Searching for opencv-python
Reading https://pypi.python.org/simple/opencv-python/
No local packages or working download links found for opencv-python
error: Could not find suitable distribution for Requirement.parse('opencv-python')

However, opencv python is working. I understand that there is not version of opencv-python trough pip on the repository but it is installed so why look on the repository?

**Comment by notfox** [comment]
default,opencv-python has been installed on tx2
you can comment out the the part of install opencv-python

**Comment by fadonoso** [comment]
I just installed opencv 3.4 in my jetson tx2, however there is an issue with opencv-python-headless. This is the error:

Processing dependencies for mmdet==1.0rc0+ff28413
Searching for opencv-python-headless>=4.1.1
Reading https://pypi.org/simple/opencv-python-headless/
Download error on https://pypi.org/simple/opencv-python-headless/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'opencv-python-headless' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for opencv-python-headless>=4.1.1
error: Could not find suitable distribution for Requirement.parse('opencv-python-headless>=4.1.1')

There is not possible to install that package on jetson tx2. So, what can I do?

**Comment by notfox** [comment]
i installed mmdet(v0.6?) on tx2 a few month ago,just  comment out the the part of install opencv-python，and modify a .cu file because of resource limit
after compile,inference model normally

**Comment by fadonoso** [comment]
@notfox could you please explain the steps to comment out the part of install opencv-python and the modification of the .cu file.

Thanks.

**Comment by notfox** [comment]
i modify the file roi_align_kernel.cu
#define THREADS_PER_BLOCK 1024 to #define THREADS_PER_BLOCK 256
about the opencv-python,i forgot the detail,only remember skipped it,sorry

**Comment by Dwrety** [comment]
Anyone successfully built nccl on Jetson Nano? I am building a Nano cluster for project diversity.

**Comment by fadonoso** [comment]
@notfox I tried with version v0.6.0 but same problem with python-opencv. I dont know why the developers of mmdetection dont solve this issue.

**Comment by zhang1992wen1023** [comment]
@fadonoso  the same question,Have you solved this problem?

**Comment by zhang1992wen1023** [comment]
@notfox  How to stop the opencv-python,would you please share your solutions?

**Comment by fadonoso** [comment]
I could not solve the problem. I'm hoping that the solution came from the
official channel.

**Comment by coldsummerday** [comment]
I had  solve this problem。
I have try to  nstalled mmdetection on jetson tx2。
here are my solution：
first， my tx2 install jetpack 4.3 （which include cuda10，opencv4.1，cudnn7.6)
also  here are some pip wheel for pytorch.(not need to  make the whole pytorch code)
https://devtalk.nvidia.com/default/topic/1049071/pytorch-for-jetson-nano-version-1-3-0-now-available/

And mmdetection  requirements opencv-python，but in the tx2，pip install not have the opencv-python。 （jetpack 4.3 already installed opencv4.1，and in python2.7/3.6，import cv2 is OK）。
so，we have opencv environment，but opencv-python can’t  installed。

albumentations>=0.3.2
imagecorruptions
mmcv>=0.2.15 
require opencv-python 
I download the source code。
imagecorruptions:
modify the setup.py ：
install_requires=[
          'numpy >= 1.16',
          'Pillow >= 5.4.1',
          'scikit-image >= 0.15',
          'opencv-python >= 3.4.5',
          'scipy >= 1.2.1',
      ],
to:
install_requires=[
          'numpy >= 1.16',
          'Pillow >= 5.4.1',
          'scikit-image >= 0.15',
          'scipy >= 1.2.1',
      ],

albumentations-0.4.3,mmcv-0.2.16 ：
change setup.py：
CHOOSE_INSTALL_REQUIRES = [("opencv-python>=4.1.1", "opencv-python-headless>=4.1.1")]
# If first not installed install second package
CHOOSE_INSTALL_REQUIRES = []


after modify the setup.py, run the sudo python setup.py install (to install the python package )

then  run the sudo pip3 install -e .  in the mmdetection source dir。


in my experience，jetpack 4.3 in tx2  install  scipy also a problem。（i also try to make the scipy source 
 to install this package）

**Comment by jzchenriver** [comment]
> install_requires=[
> 'numpy >= 1.16',
> 'Pillow >= 5.4.1',
> 'scikit-image >= 0.15',
> 'opencv-python >= 3.4.5',
> 'scipy >= 1.2.1',
> ]

I cannot find the below in the setup.py of mmcv
install_requires=[
'numpy >= 1.16',
'Pillow >= 5.4.1',
'scikit-image >= 0.15',
'opencv-python >= 3.4.5',
'scipy >= 1.2.1',
]

Could you tell me more details about the modification?

**Comment by JinhaSong** [comment]
> > install_requires=[
> > 'numpy >= 1.16',
> > 'Pillow >= 5.4.1',
> > 'scikit-image >= 0.15',
> > 'opencv-python >= 3.4.5',
> > 'scipy >= 1.2.1',
> > ]
> 
> I cannot find the below in the setup.py of mmcv
> install_requires=[
> 'numpy >= 1.16',
> 'Pillow >= 5.4.1',
> 'scikit-image >= 0.15',
> 'opencv-python >= 3.4.5',
> 'scipy >= 1.2.1',
> ]
> 
> Could you tell me more details about the modification?

install_requires -> setup.py of mmdetection
CHOOSE_INSTALL_REQUIRES -> setup.py of mmcv

**Comment by zhang1992wen1023** [comment]
> > > install_requires=[
> > > 'numpy >= 1.16',
> > > 'Pillow >= 5.4.1',
> > > 'scikit-image >= 0.15',
> > > 'opencv-python >= 3.4.5',
> > > 'scipy >= 1.2.1',
> > > ]
> > 
> > 
> > I cannot find the below in the setup.py of mmcv
> > install_requires=[
> > 'numpy >= 1.16',
> > 'Pillow >= 5.4.1',
> > 'scikit-image >= 0.15',
> > 'opencv-python >= 3.4.5',
> > 'scipy >= 1.2.1',
> > ]
> > Could you tell me more details about the modification?
> 
> install_requires -> setup.py of mmdetection
> CHOOSE_INSTALL_REQUIRES -> setup.py of mmcv

setup.py of mmdetection is install_requires=parse_requirements('requirements/runtime.txt'),
not like  install_requires=[
'numpy >= 1.16',
'Pillow >= 5.4.1',
'scikit-image >= 0.15',
'opencv-python >= 3.4.5',
'scipy >= 1.2.1',
]

**Comment by wscnwps** [comment]
> Anyone successfully built nccl on Jetson Nano? I am building a Nano cluster for project diversity.

Mostly same as : 

> i modify the file roi_align_kernel.cu
> #define THREADS_PER_BLOCK 1024 to #define THREADS_PER_BLOCK 256
> about the opencv-python,i forgot the detail,only remember skipped it,sorry

1. Only change 256 to 128 as Jetson Nano has less GPUs than Jetson TX2.
2. And an opencv dependency is in "imagecorruptions", "imgaug"(Be careful! need version<0.2.7,>=0.2.5, ), "albumentations". All of them are about image augmentation. Build and install them mannully ( use "pip install -e .") by firstly commenting opencv in their 'setup.py' or "requirements.txt" as we do in "mmcv".  
3. "imgaug" needs Sharply, which needs "geos". Run "sudo apt install libgeos-dev" before build "imgaug".
