### ISSUE TITLE
How can I train the fast-rcnn?

### ISSUE THREAD

**Issue by shwoo93** [open-mmlab/mmdetection#1532]
Hello,

For training the fast-rcnn, it requires pre-computed region proposals (.pkl files). 
How can I get those with my own rpn?

Thanks,

**Comment by thangvubk** [comment]
You can do that by using test script for rpn and replace ``ann_file`` and ``img_prefix`` of val set by train set. Check [here](https://github.com/open-mmlab/mmdetection/blob/ff2841333f1e0f63d8bf9c8d430a62a21308db3d/configs/rpn_r50_fpn_1x.py#L100)
