### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'pipeline'?? There is anyone can tell me Why?

### ISSUE THREAD

**Issue by CRmost** [open-mmlab/mmdetection#1533]

**Comment by hellock** [comment]
Maybe you are using an old-style config file?

**Comment by lazerliu** [comment]
same error,config file is  "ssd512_coco.py",how can I use ssd then?thks.

**Comment by gakkifan2020** [comment]
> same error,config file is "ssd512_coco.py",how can I use ssd then?thks.

have you found the solution?
