### ISSUE TITLE
Where's the implementation of CARAFE

### ISSUE THREAD

**Issue by Youngkl0726** [open-mmlab/mmdetection#1535]
I read the paper CARAFE recently and it says that code is available here. However, I don't find the implementation of this module. Can you tell me where it is? Thanks a lot.

**Comment by hellock** [comment]
It will soon be released.

**Comment by myownskyW7** [comment]
@Youngkl0726 You can find it in this pr(https://github.com/open-mmlab/mmdetection/pull/1583).

**Comment by ShihuaiXu** [comment]
@myownskyW7 ,this code cannot run in my environment, when I compile it, it will occur:
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00006868_00000000-6_carafe_cuda_kernel_benchmark.cpp1.ii".
Compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
Please help me
