### ISSUE TITLE
[Feature request] Add Weights & Biases for logging

### ISSUE THREAD

**Issue by ternaus** [open-mmlab/mmdetection#1537]
It would be nice to add an option to use `wandb` library for logging. https://www.wandb.com

During training, logs are uploaded to their website and one can monitor the training process from different machines online.

They have a pretty nice way to compare the results across different experiments.

I would say, it is a Tensorboard on steroids.

I find it very convenient and use it my ML pipelines. 

It would be great to see it as a feature in MMdetection.

**Comment by hellock** [comment]
Interesting idea. We may add it in the future, and you can implement it first if this is an urgent feature request. It should not be hard. There have been some examples like [TensorboardLoggerHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/tensorboard.py) (used for tensorboard logging) and [PaviLoggerHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/pavi.py) (used for an internal web service just like Weights & Biases).

**Comment by ternaus** [comment]
Thanks. I will try to create Pull Request with this functionality.

**Comment by hellock** [comment]
Implemented in https://github.com/open-mmlab/mmcv/pull/143.

**Comment by digantamisra98** [comment]
@hellock can the logger integrated in MMCV be used directly in MMDetection? Is there any docs for the same? Thanks!
