### ISSUE TITLE
I hope to get the version of CUDA for Pytorch.

### ISSUE THREAD

**Issue by chzhan** [open-mmlab/mmdetection#154]
I always encounter compilation errors related to the CUDA version during use. I want to install the corresponding Pytorch version. Can I get the CUDA version in INSTALL.md, thank you!

**Comment by Curry1201** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md
see the software environment.

**Comment by chzhan** [comment]
Thanks! @Curry1201
