### ISSUE TITLE
For loss bbox, eg smooth l1 loss, why avg factor is set num_total_samples insted of num_total_pos?

### ISSUE THREAD

**Issue by cizhenshi** [open-mmlab/mmdetection#1540]
`losses['loss_bbox'] = self.loss_bbox(
                pos_bbox_pred,
                bbox_targets[pos_inds],
                bbox_weights[pos_inds],
                avg_factor=bbox_targets.size(0),
                reduction_override=reduction_override)`
avg_factor why not set to bbox_targes[pos_inds].size（0）？

**Comment by ppwwyyxx** [comment]
```
    # The loss is normalized using the total number of regions (R), not the number
    # of foreground regions even though the box regression loss is only defined on
    # foreground regions. Why? Because doing so gives equal training influence to
    # each foreground example. To see how, consider two different minibatches:
    #  (1) Contains a single foreground region
    #  (2) Contains 100 foreground regions
    # If we normalize by the number of foreground regions, the single example in
    # minibatch (1) will be given 100 times as much influence as each foreground
    # example in minibatch (2). Normalizing by the total number of regions, R,
    # means that the single example in minibatch (1) and each of the 100 examples
    # in minibatch (2) are given equal influence.
```
(copied from https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/fast_rcnn.py#L114-L124)

**Comment by cizhenshi** [comment]
> ```
>     # The loss is normalized using the total number of regions (R), not the number
>     # of foreground regions even though the box regression loss is only defined on
>     # foreground regions. Why? Because doing so gives equal training influence to
>     # each foreground example. To see how, consider two different minibatches:
>     #  (1) Contains a single foreground region
>     #  (2) Contains 100 foreground regions
>     # If we normalize by the number of foreground regions, the single example in
>     # minibatch (1) will be given 100 times as much influence as each foreground
>     # example in minibatch (2). Normalizing by the total number of regions, R,
>     # means that the single example in minibatch (1) and each of the 100 examples
>     # in minibatch (2) are given equal influence.
> ```
> 
> (copied from https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/roi_heads/fast_rcnn.py#L114-L124)

I got it! Thank you for your detailed answer.

**Comment by abcxs** [comment]
Thanks
