### ISSUE TITLE
Any plans for NASNet?

### ISSUE THREAD

**Issue by agroener** [open-mmlab/mmdetection#1541]
NASNet: Neural Architecture Search Net developer by Google Brain, outperforms nearly all others architectures on CIFAR-10.

The proposed feature would be to add NASNet as a potential backbone to mm-detection.

Interesting article about NASNet:
https://medium.com/@sh.tsang/review-nasnet-neural-architecture-search-network-image-classification-23139ea0425d

**Comment by hellock** [comment]
Adding new backbones are relatively easier work, and there are many public implementations. We may add some NAS models in the future but maybe not NASNet, due to the limited resources and time.
