### ISSUE TITLE
If two instances overlap in annotation file, which category the overlap area belongs to according the code?

### ISSUE THREAD

**Issue by herrickli** [open-mmlab/mmdetection#1546]
If two instances overlap in segmentation annotation file, which category the overlap area belongs to according the code?
And how can I specify the overlap area to one of the categories?
Many thanks.

**Comment by hellock** [comment]
There are no "overlapping" in the annotation of masks. Each pixel only belongs to one instance, and if an object is occluded, then the occluded region is not counted as part of the object.

**Comment by herrickli** [comment]
@hellock So, if an object is occluded into two parts, I have to create two polygons to  it, am I right?

**Comment by hhaAndroid** [comment]
> @hellock So, if an object is occluded into two parts, I have to create two polygons to annotate it, am I right?

Yes, you can refer to COCO annotate .
