### ISSUE TITLE
Upgrade to PyTorch 1.0

### ISSUE THREAD

**Issue by hellock** [open-mmlab/mmdetection#155]

**Comment by donglee-afar** [comment]
I hope that the PyTorch 1.0 update will be available faster than the 0.4 version, instead of updating 0.4 faster as it is now :)
After all, the stable version has been around for 2 weeks.
Thanks for your outstanding work！

**Comment by bowenc0221** [comment]
@hellock I'm running this code with PyTorch 1.0 and currently there is no error.
