### ISSUE TITLE
Is there the support the Webcam demo with multiple GPU. 

### ISSUE THREAD

**Issue by phamdat09** [open-mmlab/mmdetection#1553]
Dear, 

I have a question. 
As I understood, with `demo/webcam_demo.py`, you only support with single GPU. 
Is there any way to run it with multiple GPUs?.I want to speed-up the FPS with 2 GPUs. It is possible ?

Thanks

**Comment by hellock** [comment]
Currently this demo only supports a single GPU. You may need to implement it by yourself.
