### ISSUE TITLE
I am training on 2080 images but see Epoch [3][250/1040] - is there max # images?

### ISSUE THREAD

**Issue by skeptomist** [open-mmlab/mmdetection#1555]
I am training on 2080 images (using PKL file) but see the following:

2019-10-16 17:53:29,523 - INFO - Epoch [3][250/1040]    lr: 0.02000, eta: 20:40:46, time: 1.062, data_time: 0.398, memory: 7382, loss_rpn_cls: 0.0449, loss_rpn_bbox: 0.0919, loss_cls: 0.1723, acc: 93.3574, loss_bbox: 0.1623, loss: 0.4713

Particularly 250/1040 does this mean 2 images per GPU or is there some max limit on number of images?  Or is there some parameter I need to provide to train.py?

**Comment by dulvqingyun** [comment]
250/1040 indicate  current iteration/total iterations  in Epoch 3

**Comment by skeptomist** [comment]
thanks for that
so the # of images being trained does not show i.e. 1040 just by coincidence happens to be half of my # images which is 2080?  I read somewhere that each GPU handles 2 images so I thought that may account for the 1040 figure ...
i am paranoid that all the images (in PKL file ) may not be used for training

**Comment by skeptomist** [comment]
> 250/1040 indicate current iteration/total iterations in Epoch 3

thanks for that
so the # of images being trained does not show i.e. 1040 just by coincidence happens to be half of my # images which is 2080? I read somewhere that each GPU handles 2 images so I thought that may account for the 1040 figure ...
i am paranoid that all the images (in PKL file ) may not be used for training

**Comment by Kaeseknacker** [comment]
You can set up the # of images per GPU in your model config file. See for example:
https://github.com/open-mmlab/mmdetection/blob/618dca0895f5f4ede19f5feebb064648e128e12e/configs/retinanet_x101_64x4d_fpn_1x.py#L88

In addition, if you are training on multiple GPUs simultaneously, the displayed maximum number of iterations would continue to decrease. For example:
#images = 2080, 2 imgs per GPU, train on 2 GPUs => 520 iterations in one epoch
