### ISSUE TITLE
Lack of some .py codes in configs folder

### ISSUE THREAD

**Issue by Xlsean** [open-mmlab/mmdetection#1558]
Hi, everyone. I met a problem when I was going to test some pre-train models. I couldn't find some  .py codes though the corresponding .pth weight files were given. For example, in the folder "/configs/fcos/":
![1](https://user-images.githubusercontent.com/45596440/67079651-264e6000-f1c6-11e9-8568-ddae2e17be70.png)
![2](https://user-images.githubusercontent.com/45596440/67079666-2babaa80-f1c6-11e9-9f90-21761c3d3f4d.png)
Under this folder, there are 8 different .pth weight files but only 3 corresponding .py codes are given. Does anyone know what the matter with that? Thank you soooo much for answering me.

**Comment by hellock** [comment]
We are not providing all the config files since they are mostly duplicated. Modifying from existing ones to any settings in the model zoo should be quite simple.

**Comment by Xlsean** [comment]
> We are not providing all the config files since they are mostly duplicated. Modifying from existing ones to any settings in the model zoo should be quite simple.

Thank you for your answer! I have already known how to modify the config files.
