### ISSUE TITLE
Suspected bug in faster_rcnn_r50_fpn_1x.py

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection#1559]
In the file, the default setting of the length of `anchor_strides` `(num_outs)` is not in accordance with `featmap_strides` which is less than `num_outs`, which likely causes extra fpn level being ignored. Because the number of fpn levels sent into RoI extractor is determined by `featmap_strides.`
I am not pretty sure, and hope it helps.

**Comment by ZwwWayne** [comment]
The config implements the standard and state-of-the-art setting, which is also consistent with other codebases.
