### ISSUE TITLE
Bug: wrong keyword in htc.

### ISSUE THREAD

**Issue by WangChuanYuan** [open-mmlab/mmdetection#1566]
There is a slip of pen in the simple_test of htc.
In line 345, the keyword argument 'nms_cfg' should be cfg.
[line 345 in htc](https://github.com/open-mmlab/mmdetection/blob/618dca0895f5f4ede19f5feebb064648e128e12e/mmdet/models/detectors/htc.py#L345)

**Comment by hellock** [comment]
Thanks for your report! Would you like to open a PR to fix it?

**Comment by WangChuanYuan** [comment]
> Thanks for your report! Would you like to open a PR to fix it?

Sure. I have created a PR.
