### ISSUE TITLE
`workflow = [('train', 1)]`

### ISSUE THREAD

**Issue by yyfhaku** [open-mmlab/mmdetection#1568]
What does this `workflow = [('train', 1)]` mean and where is it used?  it's in the last line of each configs/**.py

**Comment by WangChuanYuan** [comment]
It is used in the Runner. You can change it to the '[('train', 2), ('val', 1)]' to train for two epochs and then validate for one epoch.

**Comment by yyfhaku** [comment]
thank you very much. you are right! @WangChuanYuan
