### ISSUE TITLE
run train.py error undefined symbol

### ISSUE THREAD

**Issue by jinlukang1** [open-mmlab/mmdetection#1574]
When I run tools/train.py, I got this:
```ImportError: /data3/home_jinlukang/detection/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration```

Here is the env:
`nvcc -V == 9.0`
`torch.__version__=='1.1.0`
`torch.version.cuda==9.0`

Can somebody help me?

**Comment by ZwwWayne** [comment]
Hi @jinlukang1 ,

Please refer this issue https://github.com/open-mmlab/mmdetection/issues/66

We would appreciate if you could use the “Error report” issue template.
