### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection#1584]
I test the model then there is an error,torch.__version__ is '1.1.0',cuda is '9.0.176',and it's available，run the python setup.py develop normally,should I install cuda10?

**Comment by TWDH** [comment]
I have the same problem, have you solved it?

**Comment by yustaub** [comment]
> I have the same problem, have you solved it?

sorry，I haven't sovle it

**Comment by TiG000** [comment]
> I have the same problem, have you solved it?

> I have the same problem, have you solved it?
Resolved, please refer to #1577

**Comment by yustaub** [comment]
> Resolved, please refer to #1577

my nvidia driver is 384.81,can't install cuda9.2,do you solve it by install cuda9.2?

**Comment by lsh1994** [comment]
I copied so.10.1 directly from another computer to the corresponding location, and it was resolved.

**Comment by Song-xx** [comment]
you can try reinstall pytorch with proper cuda version(10.0).

may be you installed with a uncompatible version pytorch.

nvcc -V and nvidia-smi give different version.

good luck !
