### ISSUE TITLE
undefined symbol: _ZN3c1019ComplexCUDATensorIdEv

### ISSUE THREAD

**Issue by TWDH** [open-mmlab/mmdetection#1587]
I've reviewed all other issues in terms of this problem. it is said that complilation cuda is different from runtime cuda. However, I don't know how to check it. and solution doesn't work for me. Many thanks if anybody can give a tutorial.

After updating to the the current master branch, the compile.sh file doesn't exist and can you tell how to recompile it easily? 

I think my environment matched my pytorch version.
my system run in the following environment:
1.
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

2.
pytorch     1.3.0           py3.6_cuda10.0.130_cudnn7.6.3_0
I tried pytorch 1.1 , 1.2 and 1.3. none of them help.

**Comment by jiangwenj02** [comment]
you can remove all the ops directory and download the diretory  for replacing it. Recompile it.

**Comment by TWDH** [comment]
I actually solved this problem myself. So my "base" environment's python version is 3.7 and "open-mmlab" python version is 3.6.
After I modify the python version to 3.7 in my open-mmlab environment, it works properly. Not sure if it's the problem...
Hope it can help
