### ISSUE TITLE
I want to upload a result to COCO detection server. Does have any tools for generating results of coco test-standard.

### ISSUE THREAD

**Issue by jiangwenj02** [open-mmlab/mmdetection#1589]
I want to upload a result to COCO detection server. Does have any tools for generating results of coco test-standard.
Thank you very much.

**Comment by hellock** [comment]
You can use the test script to get the json results, and follow the [official guide](http://cocodataset.org/#upload) to upload it.

**Comment by jiangwenj02** [comment]
Thank you. I can find the test.
