### ISSUE TITLE
argument --validate of train.py silently disables validation phase

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#1594]
https://github.com/open-mmlab/mmdetection/blob/f83c8638920fd710d12a1d904a2ee957c58adda3/mmdet/apis/train.py#L195

Even if such behavier is not supported yet this should warn about it or raise error.

Am I right?

**Comment by hellock** [comment]
Agree. It should be better to warn about it.

**Comment by hellock** [comment]
Fixed.
