### ISSUE TITLE
Proper way to validate while train?

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#1595]

**Comment by ZwwWayne** [comment]
MMDet always supports evaluation after each epoch in training. I do not get what the question means.

**Comment by korabelnikov** [comment]
@ZwwWayne Really? How? 
If I use non-dist training

**Comment by ZwwWayne** [comment]
You can train a config e.g., faster rcnn, and see. It will evaluate after each epoch.

**Comment by korabelnikov** [comment]
Thanks, I will try master branch.
At least at time of question there wasn't a such functionality.
