### ISSUE TITLE
Unable to install mmdetection with Poetry

### ISSUE THREAD

**Issue by Prakashvanapalli** [open-mmlab/mmdetection#1597]
installing mmdetection with poetry in the following way is throwing an error 

```toml
mmdetection = { git = "https://github.com/open-mmlab/mmdetection.git"}
```

## Error
```
[RuntimeError]                                                       
Unable to retrieve the package version for /tmp/pypoetry-git-mmdetectionlsrsrn2m  
```

**Comment by Prakashvanapalli** [comment]
Apparently calling get_version() from setup.py file is throwing error. There is no version.py file inside mmdet.

**Comment by hellock** [comment]
`version.py` is dynamically generated when compiling.
