### ISSUE TITLE
where is the code for computing 'acc' that shown in log.

### ISSUE THREAD

**Issue by ZucchiniTang** [open-mmlab/mmdetection#1599]
Dear MMlab Members,

When I run 'tools/train.py', the log shows below:

`2019-10-29 16:59:22,925 - INFO - Epoch [12][200/259]	lr: 0.00020, eta: 0:00:43, time: 0.756, data_time: 0.004, memory: 7097, loss_rpn_cls: 0.0007, loss_rpn_bbox: 0.0008, loss_cls: 0.0345, acc: 98.9277, loss_bbox: 0.0047, loss: 0.0406
2019-10-29 17:00:00,836 - INFO - Epoch [12][250/259]	lr: 0.00020, eta: 0:00:06, time: 0.758, data_time: 0.004, memory: 7097, loss_rpn_cls: 0.0005, loss_rpn_bbox: 0.0007, loss_cls: 0.0361, acc: 98.9766, loss_bbox: 0.0053, loss: 0.0425`

I'm wondering **where is the code for computing 'acc:98.9866'.** 

Thanks.

**Comment by ZucchiniTang** [comment]
> Dear MMlab Members,
> 
> When I run 'tools/train.py', the log shows below:
> 
> `2019-10-29 16:59:22,925 - INFO - Epoch [12][200/259] lr: 0.00020, eta: 0:00:43, time: 0.756, data_time: 0.004, memory: 7097, loss_rpn_cls: 0.0007, loss_rpn_bbox: 0.0008, loss_cls: 0.0345, acc: 98.9277, loss_bbox: 0.0047, loss: 0.0406 2019-10-29 17:00:00,836 - INFO - Epoch [12][250/259] lr: 0.00020, eta: 0:00:06, time: 0.758, data_time: 0.004, memory: 7097, loss_rpn_cls: 0.0005, loss_rpn_bbox: 0.0007, loss_cls: 0.0361, acc: 98.9766, loss_bbox: 0.0053, loss: 0.0425`
> 
> I'm wondering **where is the code for computing 'acc:98.9866'.**
> 
> Thanks.

I found 'acc:' code in '/mmdet/models/bbox_heads/bbox_head.py'
the accuracy be calculated in '/mmdet/models/losses/accuracy.py'

**Comment by hellock** [comment]
Yes you got it.
