### ISSUE TITLE
converting mmdetection into caffemodel

### ISSUE THREAD

**Issue by LUCKMOONLIGHT** [open-mmlab/mmdetection#1604]
Hi @yhcao6，
Could you please guide me how to converting mmdetection into caffemodel ?

**Comment by LUCKMOONLIGHT** [comment]
But most pytorch2caffe scripts require torch < 0.4.

**Comment by zhaojw219** [comment]
maybe you can try .onnx?

**Comment by RunningLeon** [comment]
You can first convert PyTorch to ONNX using our [pytorch2onnx.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/pytorch2onnx.py) , then convert ONNX to caffemodel using other open-source tools such as [onnx2caffe](https://github.com/MTlab/onnx2caffe).
