### ISSUE TITLE
General question 

### ISSUE THREAD

**Issue by DecentMakeover** [open-mmlab/mmdetection#1605]
Hey
 
Thanks for sharing this work, it has been very helpful.Now that kai chen has graduated, will he still be involved in this project?

Thanks

**Comment by hellock** [comment]
Thanks for your attention and contributing! I have graduated and got a job in the industry, but I will continue maintaining this open source project as a part time work, with the support of my employer. I am building a small team for open source projects such as mmdetection, and we hope to establish a more formal and active community.

**Comment by DecentMakeover** [comment]
Thanks a lot for your reply and i am very happy that you will still be involved in mmdetection.
