### ISSUE TITLE
[FCOS] It is very easy to get inf when the feature passes exp() in reg branch

### ISSUE THREAD

**Issue by YilanWang** [open-mmlab/mmdetection#1606]
when data go through 

>         bbox_pred = scale(self.fcos_reg(reg_feat)).float().exp()

it is easy to get inf, and the reg_loss is then become nan. 
the config is the same as 1x.
What could be the cause of this? thank!

**Comment by hellock** [comment]
Thanks for your reporting. You may email the authors of FCOS to get help. We only respond to stuffs related to the codebase itself.
However, if you have confirmed this is caused by mmdet, we will further check it.
