### ISSUE TITLE
Execute two training scripts on the same machine but different gpu id

### ISSUE THREAD

**Issue by joeythegod** [open-mmlab/mmdetection#1607]
Hi, 
Is it possible to execute two training scripts on the same machine but different gpu id? 
E.g. 
Session1:
    CUDA_VISIBLE_DEVICES=0,1,2,3 ./tools/dist_train.sh [configs1] 4

Session2:
    CUDA_VISIBLE_DEVICES=4,5,6,7 ./tools/dist_train.sh [configs2] 4

**Comment by hellock** [comment]
Yes, but you need to modify the port number in `dist_train.sh`.
