### ISSUE TITLE
 how can I add new operations, such as rotate_nms.

### ISSUE THREAD

**Issue by kkking24** [open-mmlab/mmdetection#1612]

**Comment by hellock** [comment]
If you refer to a CUDA extension, you can add it to the `ops` directory, and modify the `setup.py` to compile it.

**Comment by kkking24** [comment]
![image](https://user-images.githubusercontent.com/18071139/68120056-53796d00-ff3f-11e9-86ab-59e3753948cf.png)
i have add a cuda extension to th ops directory and modify the setup.py,  and i compiled it successfullly. but when i run dist_train.sh, the error occurs.

**Comment by hellock** [comment]
The most probable reason is that compiling and runtime CUDA versions are not the same. You may update to the latest version, rebuild it and then run `python tools/collect_env.py` to check it.
