### ISSUE TITLE
How can I test the model and see each class mAP?

### ISSUE THREAD

**Issue by buptcwk** [open-mmlab/mmdetection#1613]
I test the model by using `python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] [--eval ${EVAL_METRICS}]` from **Getting Started.md**
But I can only see the whole mAP. How can I see each class mAP?
I'm sorry I'm a newbie. I really need help.

**Comment by buptcwk** [comment]
ok I see in [https://github.com/open-mmlab/mmdetection/blob/master/tools/coco_eval.py](url)

**Comment by yustaub** [comment]
> ok I see in [https://github.com/open-mmlab/mmdetection/blob/master/tools/coco_eval.py](url)

hello bro, could you show the coco_eval.py here, now there is not exist coco_eval.py in mm
