### ISSUE TITLE
How can I get the imformation of “epochs”?

### ISSUE THREAD

**Issue by sherlockedlee** [open-mmlab/mmdetection#1616]
Thank you very much for your brilliant work.For some reasons,I need my detectors to behave differently at different epochs,how can I get the imformation of "epochs",to be specific,how can I import "epochs" into models/anchor_heads?

**Comment by hellock** [comment]
You can register a hook to change/add some variables in the model. Here are some [examples](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/hooks).
