### ISSUE TITLE
google colab problem?

### ISSUE THREAD

**Issue by sjiki** [open-mmlab/mmdetection#1617]
I use the google colab, GPU count is 1
Following issue is occured
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
obj = _ForkingPickler.dumps(obj)
File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
obj = _ForkingPickler.dumps(obj)
File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

**Comment by ZhuoyaYang** [comment]
Same problem.

**Comment by vincentkk6356** [comment]
Make sure you add the "to_float32=True" in your pipeline in your model config file.  I solve this error by doing so.

`dict(type='LoadImageFromFile',to_float32=True)`

**Comment by liu-zg15** [comment]
I got the same error when I tried to train SSD300 on custom data.
Some times it runs well, but most times it will stop the training.
I also add to_float32=True as suggested.
But it doesn't works.
Does anyone has solution for this problem?

**Comment by ZwwWayne** [comment]
Please refer our [colab tutorial](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb) for colab usage.

**Comment by yangshiyu89** [comment]
> I got the same error when I tried to train SSD300 on custom data.
> Some times it runs well, but most times it will stop the training.
> I also add to_float32=True as suggested.
> But it doesn't works.
> Does anyone has solution for this problem?

I have the same issue. I have added the trained pipeline with "to_float32=True", but every time I trained the model, there jumps up this weird issue. Have you solved this issue yet?
