### ISSUE TITLE
Object tracking after detection 

### ISSUE THREAD

**Issue by DecentMakeover** [open-mmlab/mmdetection#1618]
Object tracking(Like MOT) after the detection of bounding box can be helpful for more fine grained information.
Are there plans to integrate this with mmdetection, Would this be feature be relevant for mmdetection?

**Comment by hellock** [comment]
Good point, but currently we do not have enough time and resources to work on that.

**Comment by DecentMakeover** [comment]
okay got it , ill close this issue for now.
