### ISSUE TITLE
How to only test for rpn?  the bbox head must be implemented.

### ISSUE THREAD

**Issue by Markovcom** [open-mmlab/mmdetection#1621]
![image](https://user-images.githubusercontent.com/26458922/68097272-11c1d580-fef1-11e9-9487-751aeee8cd11.png)

**Comment by hellock** [comment]
You can just try the RPN model.

**Comment by Markovcom** [comment]
@hellock thanks, it works.

**Comment by RebornL** [comment]
@Markovcom Hello, can you share your test script for RPN network？^^)
