### ISSUE TITLE
Testing in distributed mode gives different results

### ISSUE THREAD

**Issue by AAnoosheh** [open-mmlab/mmdetection#1622]
I'm running a custom dataset using `tools/test.py` in both distributed and non-distributed modes, and I get slightly different bounding box values with each. The numbers tend to differ by no more than a couple pixels, but the error builds up a lot over a lot of images.

I am not using flipping or rescaling (I set the MultiScaleFlipAug rescale to the original image size) and verified that flipping the `rescale` argument in lines 26 & 47 of `tools/test.py` changes nothing.

Also setting the number of GPUS to 1, 2, and 4 all give the same exact results - all different from when using non-distributed mode. So it really is an issue with the program and not the scattering/collecting.

All non-data parameters are equivalent to [this config file](https://github.com/open-mmlab/mmdetection/blob/master/configs/retinanet_r50_fpn_1x.py).

**Environment**
 - Python 3.6
- Nvidia V100

**Comment by hhaAndroid** [comment]
The collate function may have different image sizes under different batch size settings, so maybe gives different results, but the difference should be small.
