### ISSUE TITLE
Sphinx documentation

### ISSUE THREAD

**Issue by cristianpb** [open-mmlab/mmdetection#1623]
**Sphinx documentation mix docstrings inside the code, plain text, images, static typing in order to build a rich documentation. It can be automatically deployed using github actions**

**Motivation**
This feature will allow to find easily information inside the project.
In addition of good quality code, the explanation will add more details to each part of the code.

**Related resources**
Sphinx resources can be found here: https://www.sphinx-doc.org/en/master/
Sphinx automatic documentation plugin from docstrings can be found here: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

**Additional context**
I ask for this request because we started using this for our project [IA Flash Lab](https://github.com/ia-flash/lab) and the sphinx documentation looks like this: https://ia-flash.github.io/lab/
I can adapt the configuration that I have made to the mmdetection repository. Let me know what you think.

**Comment by hellock** [comment]
Thanks for your advice! Actually we were using sphinx for the documentation of [MMCV](https://github.com/open-mmlab/mmcv). The reason why we did not deploy it for MMDetection is that we though currently the documentation of this project is not satisfying and needs further improvements.

**Comment by cristianpb** [comment]
Ok, thanks for pointing the MMCV documentation. I hope one day mmdetection would have a nice documentation too.
