### ISSUE TITLE
EfficientNet backbone

### ISSUE THREAD

**Issue by dhananjaisharma10** [open-mmlab/mmdetection#1627]
Hi!

I am trying to write a new backbone. Can someone please guide me through the process? I am particularly interested in knowing how to link the feature maps of the backbone with FPN.

Thanks!

**Comment by JegernOUTT** [comment]
It can be something like this implementation (not finished but working)

https://github.com/JegernOUTT/mmdetection/blob/master/mmdet/models/backbones/efficientnet.py
https://github.com/JegernOUTT/mmdetection/blob/master/configs/efficientnet_backbone/retinanet_eb0_fpn_1x.py

**Comment by dhananjaisharma10** [comment]
@JegernOUTT Thanks for the reference. I am currently trying to figure out an alternate way to get the same padding feature as in TF to remove the need for a separate wrapper class for Conv2d.

**Comment by zh99li** [comment]
> It can be something like this implementation (not finished but working)
> 
> https://github.com/JegernOUTT/mmdetection/blob/master/mmdet/models/backbones/efficientnet.py
> https://github.com/JegernOUTT/mmdetection/blob/master/configs/efficientnet_backbone/retinanet_eb0_fpn_1x.py

thank you!
But when I use efficientnet-b7, some error happend.
RuntimeError: Given groups=1, weight of size 256 24 1 1, expected input[1, 48, 160, 160] to have 24 channels, but got 48 channels instead
