### ISSUE TITLE
Bug: Test HTC with proposals

### ISSUE THREAD

**Issue by WangChuanYuan** [open-mmlab/mmdetection#1628]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When test htc with proposal_file, the bug occurs. I supposed that the bug may exist in other detectors.

**Reproduction**
1. What command or script did you run?
```
python -m torch.distributed.launch --nproc_per_node=3
      test.py configs/htc_r50_fpn.py
              {checkpoint}
              --launcher pytorch
              --out {path}             
              --eval bbox segm
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
```
I modified the config of htc and provided it with the proposals generated by ga_rpn.
I am sure that my config was right.
```
3. What dataset did you use?
COCO

**Error traceback**
If applicable, paste the error trackback here.
```
File "/mmdetection/mmdet/core/bbox/transforms.py", line 163, in bbox2roi
    rois = torch.cat([img_inds, bboxes[:, :4]], dim=-1)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 3 and 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:62
```

**Bug fix**
I fix the bug through modifing the base detector.
I insert the code
```
if 'proposals' in kwargs:
            kwargs['proposals'] = kwargs['proposals'][0]
```
before
```
return self.simple_test(imgs[0], img_metas[0], **kwargs)
```
in forward_test.

**Comment by WangChuanYuan** [comment]
By the way, I want to know the details about how to finetuing htc with proposals generated by ga_rpn.
According to the paper:
Should I improve each stage's iou_thr to `0.6, 0.7, 0.8`  vs. `0.5, 0.6, 0.7` before?
and set the lr is `0.02, 0.002, 0002` when finetuning.

I have tried end-to-end training (with higher iou_thr each stage), but the performance was not satisfying.
I simply test a trained htc_r50_fpn_1x with proposals generated by ga_rpn (without finetuing) and the map dropps one point. 

Also, I wonder why the batch size of masked_conv must be one as the assertion in masked_conv.py
https://github.com/open-mmlab/mmdetection/blob/4b101ece44f448cf00faf165e8fc93338d9cf1d9/mmdet/ops/masked_conv/masked_conv.py#L17
I comment that line so that I can train ga_rpn without assert error.

**Comment by ZwwWayne** [comment]
Hi @WangChuanYuan ,
May I know the details about how you generate the proposal with GA_RPN?
For example, the config and performance detail of the GA_RPN model, which command you use to generate the proposals, and the configs for finetuning the HTC with GA_RPN.
The unsatisfactory results might result from some inconsistent settings.

It would be very helpful if you could create a new branch in your own repo thus we could find the problem much easier.

Thanks.

**Comment by WangChuanYuan** [comment]
Hi @ZwwWayne ,
Thanks for your reply, I list some details about my experiments and hope we can find the problems.
[https://github.com/WangChuanYuan/mmdetection/tree/coco-instance-segmentation/coco_instance_segmentation](experiments)

**Comment by ZwwWayne** [comment]
We are able to see the config and your results now.
It might take some time to check and we will response A.S.A.P.

**Comment by yhcao6** [comment]
Thanks for reporting the bug. We would appreciate it if you would like to create a PR to fix this error?

**Comment by WangChuanYuan** [comment]
> Thanks for reporting the bug. We would appreciate it if you would like to create a PR to fix this error?

I have created a PR. I fix the bug through the method mentioned in my issue. It worked at that time but I am sorry I cannot do the test for current version since there are no devices and datasets for me now.

**Comment by ZwwWayne** [comment]
This issue is closed because it has been solved in https://github.com/open-mmlab/mmdetection/pull/2196. Feel free to reopen it if you have any further questions.
