### ISSUE TITLE
Is the implementation of faster-rcnn(TwoStageDetector) is different from the original paper?

### ISSUE THREAD

**Issue by heylfda** [open-mmlab/mmdetection#1630]
The part of loss function of ["forward_train"](https://github.com/open-mmlab/mmdetection/blob/4b101ece44f448cf00faf165e8fc93338d9cf1d9/mmdet/models/detectors/two_stage.py#L218) use get target of the bbox head "ConvFCBBoxHead". But the get_target function use "bbox2delta" to get "delta". I saw the inputs of the bbox2delta were "proposals" sampled from rpn outputs and "gt_bboxes". So in the [bbox2delta](https://github.com/open-mmlab/mmdetection/blob/4b101ece44f448cf00faf165e8fc93338d9cf1d9/mmdet/core/bbox/transforms.py#L23) function the denominator of the formula is ground truth NOT anchors in the paper. 
![The formula in the paper](https://user-images.githubusercontent.com/11287256/68267920-1c19d600-008f-11ea-8028-cf95b9f94838.png)
So is that the loss implementation is different with the paper? I thougt it may get different results between these two implementation.

**Comment by hellock** [comment]
The implementation follows the original paper. `bbox2delta` is used to compute the regression targets from the proposal to the ground truth.

**Comment by heylfda** [comment]
Thank you for your reply.  But is that we should use anchors as the denominator "ha" or "wa" in the formula? But the implement use the pos_boxes's w and h in "bbox_target_single" function bellow.
![图片](https://user-images.githubusercontent.com/11287256/68443516-0a5f3c80-020f-11ea-8572-df47b1364fd4.png)
![图片](https://user-images.githubusercontent.com/11287256/68443632-7b9eef80-020f-11ea-931e-afa101e5991d.png)

I'm really confused about this. I'd appreciate it for the reply. Thank you.

**Comment by hellock** [comment]
`pos_target_single` is used to compute the regression target of the second stage in your screenshot, where "ha" or "wa" are the size of proposals.
