### ISSUE TITLE
Why mmdetection  does not use dropblock？

### ISSUE THREAD

**Issue by HeathHose** [open-mmlab/mmdetection#1632]
**Describe the feature**
Thank you for sharing an awesome repo.
dropblock seems can boost the performance, but there is no dropblock used in mmedetection

**Related resources**
there is an  third-party implementations：https://github.com/miguelvr/dropblock
![image](https://user-images.githubusercontent.com/14328405/68298929-92412b80-00d5-11ea-8829-450cd01285aa.png)

**Comment by hellock** [comment]
Of course you can implement dropblock and it should not be hard. MMDetection provides everything you may need for building new models or blocks, but not everything.

**Comment by HeathHose** [comment]
@hellock  thanks for your kind help
