### ISSUE TITLE
[FCOS]Why can GIOU improve performance?

### ISSUE THREAD

**Issue by YilanWang** [open-mmlab/mmdetection#1639]
Giou mainly renormalizes the scope of regression loss, and its most important contribution is to solve the problem that gt and prediction box do not intersect. For fcos or other anchor-free models, their location points are points inside the gt that satisfy the requirements, and the boxes generated by these points must intersect with gt. So I would like to ask, why is there a significant improvement in giou?

------

giou主要是重新规范化了回归误差的范围，而它最重要的贡献是解决了gt和预测框不相交的问题。然后对于fcos或者类似anchor-free的模型，他们的位置点是满足要求的gt内部的点，而这些点所生成的框必然和gt有交集。所以我想请教一下，为什么giou能够有明显的提升？

**Comment by tim20120526** [comment]
请问你在fcos上用了giou涨点明显?

**Comment by tim20120526** [comment]
you implement GIOU in FCOS method to get better performance?

**Comment by YilanWang** [comment]
> you implement GIOU in FCOS method to get better performance?

about 0.3 map

**Comment by LostStars3** [comment]
你好，我想请问一下，anchor-based的方法，正样本是和gt的IOU大于一定阈值，这样必然anchor和gt也有交集，这是不是意味着使用GIOU的时候应该把负样本也用上？

**Comment by 2448845600** [comment]
Should we implement "MaxGIoUAssigner" for GIoU loss?
