### ISSUE TITLE
IF I want to change the lr_scheduler to 0.5x, what parameters should I adjust ?

### ISSUE THREAD

**Issue by b03505036** [open-mmlab/mmdetection#1640]
IF I want to change the lr_scheduler to 0.5x, what parameters should I adjust ?
Is it having some connections with GPU_number and images_per_GPU?

**Comment by ZwwWayne** [comment]
Hi @b03505036 ,
You only need to change `steps` and `total_epochs` in the config files.
Take https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_fpn_1x.py as an example, change https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_fpn_1x.py#L157 from `[8, 11]` to `[4,5]` and change https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_fpn_1x.py#L168 from `12` to `6`.

**Comment by b03505036** [comment]
ty, so much.
I am training now.
