### ISSUE TITLE
Testing Results confusing when evaluting with proposals and bbox

### ISSUE THREAD

**Issue by tzzcl** [open-mmlab/mmdetection#1641]
When I try to test pretrained faster_rcnn_r50_fpn_1x with my trained weights on MS-COCO, there are two options:
1. evaluate proposals:

> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.412
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.678
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.438
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.272
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.475
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.577
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.552
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.552
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.552
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.401
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.615
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.729

2. evaluate bboxs:

>  Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.363
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.583
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.389
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.212
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.396
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.465
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.303
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.485
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.510
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.316
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.548
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.641

And I have two questions:

1. What's the differences between AP with both evaluation?

2. Why evaluting proposals, the AR becomes same when maxDet changes?

Thanks

**Comment by chenlongsun** [comment]
How many times have you trained? To achieve the above results?Trained on your own data set?

**Comment by hellock** [comment]
`proposal` is used for evaluating the performance of proposals, e.g., recall.
`bbox` is used for evaluating the performance of final bbox results, e.g., mAP.

**Comment by XCRobert** [comment]
> `proposal` is used for evaluating the performance of proposals, e.g., recall.
> `bbox` is used for evaluating the performance of final bbox results, e.g., mAP.

Hello，hellock! For faster-rcnn , during testing if I use "--eval proposal --out proposal.pkl " will get the same content in pkl.json as using "--eval bbox --out bbox.pkl " . The proposals got in the json file are actually the final predicted boxes instead of  the proposals from the rpn stage

**Comment by XCRobert** [comment]
@hellock  
test.py
https://github.com/open-mmlab/mmdetection/blob/b7894cbdcbe114e3e9efdd1a6a229419a552c807/tools/test.py#L240-L269
coco_utils.py
https://github.com/open-mmlab/mmdetection/blob/b7894cbdcbe114e3e9efdd1a6a229419a552c807/mmdet/core/evaluation/coco_utils.py#L43-L50
For twp stage detectors , it seems the codes directly using the second stage outputs as proposals by ignore the category labels  information to evaluate .

**Comment by hellock** [comment]
If you would like to evaluate the proposals, then you need to test the RPN model instead of the Faster R-CNN.
