### ISSUE TITLE
output of test.py is different with and without --show argument

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#1646]
mmdetection/tools/test.py 
config.py latest.pth --out out1.pkl --show

mmdetection/tools/test.py 
config.py latest.pth --out out2.pkl

results in  out1.pkl and out2.pkl are different. If precisely they have different scale. out2.pkl is wrong but you can't visualize it, when you try to visualize you will get out1.pkl that's correct one,

If scale==1 issue doesn't affect results

**Comment by ZwwWayne** [comment]
Hi @korabelnikov ,
Please check the discussion in PR https://github.com/open-mmlab/mmdetection/pull/1645
