### ISSUE TITLE
How to mix different datasets in training

### ISSUE THREAD

**Issue by Kaeseknacker** [open-mmlab/mmdetection#1648]
Hi,

I want to train a detector with two different datasets:

Dataset A: #images = 1000; #objects = 1000 (~1 object per image)
Dataset B: #images = 500; #objects = 2000 (~4 objects per image)

How should I mix up the two different datasets to get a "good" performance on both datasets?

Case 1:
1xDataset A and 2xDataset B 
=> The network sees the same number of images from both datasets.

 Case 2:
2xDataset A and 1xDataset B
=> The network sees the same number of objects from both datasets.

**Comment by ZwwWayne** [comment]
Hi @Kaeseknacker ,

**Comment by zhaojw219** [comment]
I met the same problem with you.Have you solved it?

**Comment by Kaeseknacker** [comment]
Hi @ZwwWayne ,
Yes I know, and I already use this feature. The model config could look something like this:
```python
dataset_A_train_dict = dict(
        type='RepeatDataset',
        times=1,
        dataset=dict(
            type='Dataset_A,
            ...
            pipeline=train_pipeline
        )
    )
dataset_A_val_dict = dict(
        ...
        pipeline=test_pipeline
    )
dataset_A_test_dict = dict(
        ...
        pipeline=test_pipeline
    )
dataset_B_train_dict = dict(
        type='RepeatDataset',
        times=2,
        dataset=dict(
            type='Dataset_B,
            ...
            pipeline=train_pipeline
        )
    )
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train = [
        dataset_A_train_dict,
        dataset_B_train_dict
    ],
    val = dataset_A_val_dict,
    test = dataset_A_test_dict
    )
```

My question is more theoreticaly:
Should I make sure that the model sees the same number of images from both datasets or that the model sees the same number of objects from both datasets?

**Comment by ZwwWayne** [comment]
I am not very certain about the answer, but I think you could try.

**Comment by thomashossler** [comment]
Hey @Kaeseknacker, it depends on many things. How different are the distribution of both datasets? For example, is it both outdoor scenes at different time of the day or is it indoor vs outdoor? What's your classes distribution? How many classes? You could simply weight the classification loss based on the frequency of each class, with a lesser weight to classes that appear often.

**Comment by Kaeseknacker** [comment]
hi @thomashossler , thank you for your clues.
In my case it's about ships (so only 2 classes: ships + background). One dataset contains a lot of small objects (=> many objects/image). The other data set usually contains only one object per image, but the object is much larger. Weather, lighting and camera are different.

For me again for understanding: The network learns per batch (= multiple images). If the batch contains 100 objects, the loss is calculated depending on 100 objects. If the batch contains only 10 objects, then the loss is calculated depending on 10 objects. Right?

**Comment by thomashossler** [comment]
yes you are correct. you have two types of losses in object detection tasks: classification (ship/no ship) and regression (how "tight" the predicted bbox is relatively to the ground truth). 

To be honest, I don't think the approach would matter that much because the sub-class imbalance is relatively small (1/2). Keep in mind that if you use augmentation (which you should definitely do because of the small dataset) like random cropping, you might crop out some of the small boats during training but you will not crop the larger ones, which will bring that ratio down. 

Given the dataset sizes, I would just train with 1:1 ratio of dataset A and B

**Comment by Mabinogiysk** [comment]
Hi, @ZwwWayne , is there any tutorial about training on mutiple datasets? Or the only way that I learn the usage is reading the source code?

**Comment by ZwwWayne** [comment]
Hi @Mabinogiysk ,
For now, we do not have a tutorial for that. We will try to add it in our next release.
