### ISSUE TITLE
Shuffle=True in build data loader

### ISSUE THREAD

**Issue by thomashossler** [open-mmlab/mmdetection#1649]
**Describe the bug**
1) When setting `shuffle=True` inb the non distributed training case, the `build_dataloader` function crashes. Because of `sampler = GroupSampler(dataset, imgs_per_gpu) if shuffle else None`, when `shuffle=True` the sampler is defined and pytorch dataloader cannot have both. 

2) more importantly, because of that logic, in non distributed training, the sampler is None and there is no shuffling which means that the training data is fed to the network in a deterministic fashion (which is really bad if the classes are not uniformly distributed in your dataset for example). 

**Reproduction**
1. What command or script did you run?
```
python train.py ../configs/faster_rcnn_r50_fpn_1x.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
In `mmdet/apis/train.py`, line 203" in the `_non_dist_train` function:
```
    data_loaders = [
        build_dataloader(
            ds,
            cfg.data.imgs_per_gpu,
            cfg.data.workers_per_gpu,
            cfg.gpus,
            dist=False,
            shuffle=True) for ds in dataset
    ]
```

3. What dataset did you use?
`coco2017`

**Environment**
- provided docker image

**Error traceback**
If applicable, paste the error trackback here.
```
ValueError: sampler option is mutually exclusive with shuffle
```

**Bug fix**
I can write the PR asap.

**Comment by thomashossler** [comment]
any update on that @ZwwWayne ?

**Comment by ZwwWayne** [comment]
@thomashossler Thanks for your advice, this is indeed a bug.
Could you write a PR to fix that?

**Comment by thomashossler** [comment]
sure,  I'll submit it tomorrow

**Comment by ZwwWayne** [comment]
Thanks a lot.

**Comment by thomashossler** [comment]
cool you have the PR reference above. This is my first PR in this repo, I followed the guidelines but lemme know if something is wrong. I think this was the easiest / cleanest way to solve the bug.

**Comment by ZwwWayne** [comment]
Thanks for the PR.
This issue is closed, feel free to reopen it if you have further questions.
