### ISSUE TITLE
start with tools/train.py instead of dist_train.sh

### ISSUE THREAD

**Issue by hellohwang** [open-mmlab/mmdetection#1652]
hello, ck. I want to write a .py scriot to train a model, I have trouble that i want to start with "tools/train.py" instead of "dist_train.py", And i have tried to write this, but i failed. Can you give me a example code?Thanks advanced!

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#train-with-a-single-gpu

**Comment by hellohwang** [comment]
Thanks a lot!
