### ISSUE TITLE
How to start validate only in the second half of training? 

### ISSUE THREAD

**Issue by tim20120526** [open-mmlab/mmdetection#1653]
HI! thanks for your  amazing project!
i have a question. i use this code to train some model from scratch recently.It usually take many epoches, i want to run validate process only iin the second half of training to save time.can you give me some advises?

**Comment by tim20120526** [comment]
i have solved this problem by .... in hook.py.

**Comment by ujsyehao** [comment]
@tim20120526  Can you tell me which hook.py?
