### ISSUE TITLE
Error on removing RandomFlip operation

### ISSUE THREAD

**Issue by Cli98** [open-mmlab/mmdetection#1656]
Ask a beginner question: I removed RandomFlip from train pipeline then I find an error below.
I have no idea why this happened. I do not need to flip my data during my training phase.
In the meanwhile I checked pipeline docs. Looks like RandomFlip is the only operation to add "flip" to result. 
So this Framework enforce flip in training period?
_BTW I googled for two hours but find no solution on this issue._

Here is the train pipeline I'm using,
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(600, 1000), keep_ratio=True),
    #dict(type='RandomFlip', flip_ratio = 10e-30),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]

And here is the error message, 

Traceback (most recent call last):
  File "./tools/train.py", line 112, in <module>
    main()
  File "./tools/train.py", line 108, in main
    logger=logger)
  File "/home/sumanta/lcl/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/sumanta/lcl/mmdetection/mmdet/apis/train.py", line 193, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/sumanta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/mmcv-0.2.14-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sumanta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/mmcv-0.2.14-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/sumanta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/sumanta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/sumanta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sumanta/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/sumanta/lcl/mmdetection/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/sumanta/lcl/mmdetection/mmdet/datasets/custom.py", line 141, in prepare_train_img
    return self.pipeline(results)
  File "/home/sumanta/lcl/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/sumanta/lcl/mmdetection/mmdet/datasets/pipelines/formating.py", line 178, in __call__
    img_meta[key] = results[key]
KeyError: 'flip'

**Comment by huangrichen11** [comment]
you cant move flip, if you cat set flip_ration = 0.0  instead of remove RandomFlip

**Comment by Cli98** [comment]
> you cant move flip, if you cat set flip_ration = 0.0 instead of remove RandomFlip

I have not figured out "flip_ration" param, where is it?
Are you referring to "flip_ratio"?. Mmdetection enforce flip_ratio>0.

**Comment by huangrichen11** [comment]
yes, it is `flip_ratio`.  In `formating.py`, you can see the key `flip` is default, so you cant remove it. But you can set `flip_ratio` to 0. See [here](https://github.com/open-mmlab/mmdetection/issues/1493#issuecomment-546781440) for details. But you say Mmdetection enforce `flip_ratio`>0.  I cant find it in source code.  please check the `__init__` of  `RandomFlip` class  of  `transforms.py`  it will be help you

**Comment by Cli98** [comment]
> yes, it is `flip_ratio`. In `formating.py`, you can see the key `flip` is default, so you cant remove it. But you can set `flip_ratio` to 0. See [here](https://github.com/open-mmlab/mmdetection/issues/1493#issuecomment-546781440) for details. But you say Mmdetection enforce `flip_ratio`>0. I cant find it in source code. please check the `__init__` of `RandomFlip` class of `transforms.py` it will be help you

Thank you for let me know the code for val pipeline.
Here is the code from trainsformer.py
Line 170-185

@PIPELINES.register_module
class RandomFlip(object):
    """Flip the image & bbox & mask.

    If the input dict contains the key "flip", then the flag will be used,
    otherwise it will be randomly decided by a ratio specified in the init
    method.

    Args:
        flip_ratio (float, optional): The flipping probability.
    """

    def __init__(self, flip_ratio=None):
        self.flip_ratio = flip_ratio
        if flip_ratio is not None:
            assert flip_ratio >= 0 and flip_ratio <= 1

**Comment by Cli98** [comment]
> yes, it is `flip_ratio`. In `formating.py`, you can see the key `flip` is default, so you cant remove it. But you can set `flip_ratio` to 0. See [here](https://github.com/open-mmlab/mmdetection/issues/1493#issuecomment-546781440) for details. But you say Mmdetection enforce `flip_ratio`>0. I cant find it in source code. please check the `__init__` of `RandomFlip` class of `transforms.py` it will be help you

Hi @huangrichen11 thank you for point it out. The code updates 12 days ago but I have not updated code base yet. Now we are able to set flip_ratio as 0

**Comment by huangrichen11** [comment]
> > yes, it is `flip_ratio`. In `formating.py`, you can see the key `flip` is default, so you cant remove it. But you can set `flip_ratio` to 0. See [here](https://github.com/open-mmlab/mmdetection/issues/1493#issuecomment-546781440) for details. But you say Mmdetection enforce `flip_ratio`>0. I cant find it in source code. please check the `__init__` of `RandomFlip` class of `transforms.py` it will be help you
> 
> Thank you for let me know the code for val pipeline.
> Here is the code from trainsformer.py
> Line 170-185
> 
> @PIPELINES.register_module
> class RandomFlip(object):
> """Flip the image & bbox & mask.
> 
> ```
> If the input dict contains the key "flip", then the flag will be used,
> otherwise it will be randomly decided by a ratio specified in the init
> method.
> 
> Args:
>     flip_ratio (float, optional): The flipping probability.
> """
> 
> def __init__(self, flip_ratio=None):
>     self.flip_ratio = flip_ratio
>     if flip_ratio is not None:
>         assert flip_ratio > 0 and flip_ratio <= 1 
> ```

Actually, you can modify code directly if you meet similar issue in the future.
