### ISSUE TITLE
Other features      DCNv2     Group Normalization     Weight Standardization     OHEM     Soft-NMS     Generalized Attention     GCNet     Mixed Precision (FP16) Training

### ISSUE THREAD

**Issue by henbucuoshanghai** [open-mmlab/mmdetection#1657]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by henbucuoshanghai** [comment]
where is the code of them???? DCNv2 Group Normalization Weight Standardization OHEM Soft-NMS Generalized Attention GCNet Mixed Precision (FP16)

**Comment by ZwwWayne** [comment]
Hi @henbucuoshanghai ,

I do not know why you cannot find them, so I list their implementation and configs as follows:

- **DCN v2**: implementation is in https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops/dcn, configs are in https://github.com/open-mmlab/mmdetection/tree/master/configs/dcn to run the model.

- **GN**: it is implemented by Pytorch, and you can use the configs in https://github.com/open-mmlab/mmdetection/tree/master/configs/gn to run the code.

- **WS**: use configs in https://github.com/open-mmlab/mmdetection/tree/master/configs/gn%2Bws, the implementation is in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/utils/conv_ws.py.

- **OHEM**: configs can be found at https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_ohem_r50_fpn_1x.py, and the implementation is in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/samplers/ohem_sampler.py.

- **SoftNMS**: it is in https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops/nms, you can use it by uncommenting the NMS option in each config such as in https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_fpn_1x.py

- **GCNet**: implementation is in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/context_block.py, you can use the configs in https://github.com/open-mmlab/mmdetection/tree/master/configs/gcnet.

- **FP16**: implementation is in https://github.com/open-mmlab/mmdetection/tree/master/mmdet/core/fp16, configs: https://github.com/open-mmlab/mmdetection/tree/master/configs/fp16.

Wish you good luck.

**Comment by henbucuoshanghai** [comment]
very nice. very kind of you.tks   that is what i wanted.
