### ISSUE TITLE
the training process may get into stuck

### ISSUE THREAD

**Issue by miracle-fmh** [open-mmlab/mmdetection#166]
After training some iterations, the GPU-Util may increased from about 50% to 100%, and then the training get into totally stuck and can not training any iterations, and the code can not throw any error.

**Comment by miracle-fmh** [comment]
![123](https://user-images.githubusercontent.com/33553128/49773320-903ae500-fd2b-11e8-8c28-77626aaadf2a.png)

**Comment by miracle-fmh** [comment]
My System is : CUDA 9 and Python 3.5 and Pytorch 0.4.1

**Comment by hellock** [comment]
#99

**Comment by miracle-fmh** [comment]
thks, i will try build the pytorch from source

**Comment by miracle-fmh** [comment]
@hellock 
I build the pytorch by following steps: 
git clone -b v0.4.1 --recursive https://github.com/pytorch/pytorch
python setup.py install

My system info: python3.5 + cuda9 + cudnn7.0.5
By using the build torch, the training still get into stuck, it cannot train any iterations.
![333](https://user-images.githubusercontent.com/33553128/49802529-15ec7e00-fd88-11e8-8461-67670153576a.png)

can you show me how you build the pytorch, thank you?

**Comment by miracle-fmh** [comment]
By training using below, the code works
python3 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py

But training using below, the code stuck:
python3 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py --gpus 4

By training using  below, the code throw out of memory error:
python3 -m torch.distributed.launch --nproc_per_node=4 ./tools/train.py --launcher pytorch

Could you meet these problems?

**Comment by miracle-fmh** [comment]
By training using below, the code works
python3 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py

But training using below, the code stuck:
python3 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py --gpus 4

By training using below, the code work well (when --gpus = 1 2 or 3):
python3 -m torch.distributed.launch --nproc_per_node=1 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py --gpus 3

By training using below, the code get stuck (when --gpus = 4):
python3 -m torch.distributed.launch --nproc_per_node=1 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py --gpus 4

Could you meet these problems?

**Comment by miracle-fmh** [comment]
I train the model on 4-gpus machine.

By training using below, the code works
python3 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py

But training using below, the code stuck:
python3 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py --gpus 4

By training using below, the code work well (when --gpus = 1 2 or 3):
python3 -m torch.distributed.launch --nproc_per_node=1 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py --gpus 3

By training using below, the code get stuck (when --gpus = 4):
python3 -m torch.distributed.launch --nproc_per_node=1 ./tools/train.py /mnt/cephfs/lab/yudongdong/mmdetection/configs/cascade_mask_rcnn_r50_fpn_1x_gpu4.py --gpus 4

Could you meet these problems?

**Comment by miracle-fmh** [comment]
> In my opinion, it is sometimes related to cuda interations. I have some suggestion for you.
> 
> 1. If you are using cuda9, you should upgrade nvidia driver to 396.51 since many people reported to resolve random hang in multi-GPU training.
> 2. If option 1 doesnot work, i recommend you to install from a clean docker, `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` can be a good point to start. See [#159](https://github.com/open-mmlab/mmdetection/issues/159)

Thanks, I will try it.

**Comment by miracle-fmh** [comment]
@hellock @thangvubk  Thanks, the training process works well after upgrade the nvidia driver to 410.xx.

**Comment by KimSoybean** [comment]
@miracle-fmh I met the same problem. 
For Faster-r50-fpn, it throws "UserWarning: semaphore_tracker: There appear to be 8 leaked semaphores to clean up at shutdown."
For Mask-r50-fpn, it stops without any error.
For Retinanet-r50, it runs properly.
I use 4 Tesla P40, CUDA90, pytorch0.4.1 (installed from "pip install pytorch_0.4.1_xxxx.whl "), driver= 410(I have also tried 390, the same situation )
Can you tell me some methods else?

**Comment by XudongWang12Sigma** [comment]
Hi, I also meet similar problems, have you already solved it? @KimSoybean

**Comment by yhcao6** [comment]
To ensure no stuck, if you are using pytorch 0.4.1, you can 
1. Modify source code as follow:
![16911537936937_ pic_hd](https://user-images.githubusercontent.com/22662425/51649321-f10e3c00-1fbe-11e9-8a08-14102e21cbdd.jpg)

2. Then compile pytorch-0.4.1 from source code

After that, I have not met stuck anymore.

**Comment by ujsyehao** [comment]
Hi, my environment: titan X + 410 Driver + cuda10 + pytorch 1.1
I encounter the problem too.

**Comment by ujsyehao** [comment]
@thangvubk yeah, you are right, I try new docker image(you recommend) and it works!

**Comment by visenzeadam** [comment]
The problem is still there.

After I installed driver and toolkit for cuda10.1,  installed Pytorch 1.2 from the newest source, followed the guid from nvcc and installed nvcc2, apt-get installed gcc with version 7.4.0.
Conda installed some other dependences like mmcv and cython. 
os: ubuntu 18.04

**Comment by yanxp** [comment]
> The problem is still there: the training got stuck, without any progress after loading dataset.
> 
> After I installed driver and toolkit for cuda10.1, installed Pytorch 1.2 from the newest source, followed the guid from nvcc and installed nvcc2, apt-get installed gcc with version 7.4.0.
> Conda installed some other dependences like mmcv and cython.
> os: ubuntu 18.04
> I tried both ./tools/dist-train.sh and single GPUs train like below.
> 
> $ python ./tools/train.py --work_dir work_dirs/ --validate --gpus 4 configs/retinanet_r101_fpn_1x.py
> 2019-07-19 07:50:51,719 - INFO - Distributed training: False
> 2019-07-19 07:50:52,319 - INFO - load model from: modelzoo://resnet101
> 2019-07-19 07:50:53,156 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias
> 
> missing keys in source state_dict: layer3.19.bn2.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.7.bn3.num_batches_tracked, layer3.11.bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.16.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.15.bn2.num_batches_tracked, layer3.14.bn2.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer3.14.bn1.num_batches_tracked, layer3.12.bn2.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer3.6.bn2.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.19.bn1.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.8.bn2.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer3.10.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.13.bn2.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer3.15.bn3.num_batches_tracked, layer3.18.bn1.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer3.16.bn1.num_batches_tracked, layer3.21.bn3.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.7.bn1.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer3.7.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, bn1.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer3.18.bn2.num_batches_tracked, layer3.22.bn2.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer3.22.bn3.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer3.20.bn3.num_batches_tracked, layer3.13.bn1.num_batches_tracked, layer3.22.bn1.num_batches_tracked, layer3.12.bn3.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer3.11.bn3.num_batches_tracked, layer3.12.bn1.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.20.bn2.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer3.6.bn1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer3.9.bn2.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer3.8.bn3.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer3.21.bn1.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.17.bn3.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.17.bn2.num_batches_tracked, layer3.8.bn1.num_batches_tracked, layer3.20.bn1.num_batches_tracked, layer3.17.bn1.num_batches_tracked, layer3.14.bn3.num_batches_tracked, layer3.6.bn3.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.13.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.16.bn3.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.11.bn2.num_batches_tracked, layer3.10.bn2.num_batches_tracked, layer3.21.bn2.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer3.19.bn3.num_batches_tracked, layer3.18.bn3.num_batches_tracked, layer3.9.bn1.num_batches_tracked, layer3.10.bn3.num_batches_tracked, layer3.15.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.9.bn3.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer1.0.bn1.num_batches_tracked
> 
> loading annotations into memory...
> Done (t=0.64s)
> creating index...
> index created!
> 2019-07-19 07:50:56,395 - INFO - Start running, host: adam@adam-train-1, work_dir: /home/adam/code/mmdetection/work_dirs
> 2019-07-19 07:50:56,397 - INFO - workflow: [('train', 1)], max: 60 epochs

Have you solved the problem?

**Comment by ZlodeiBaal** [comment]
Same issue here.
But i found solution for me - pytorch/pytorch#33296
import cv2
At the beginning of the program ( in train.py ), first import cv2, before import torch. Seem like pytorch internal problem.

**Comment by viet98lx** [comment]
> Same issue here. But i found solution for me - [pytorch/pytorch#33296](https://github.com/pytorch/pytorch/issues/33296) import cv2 At the beginning of the program ( in train.py ), first import cv2, before import torch. Seem like pytorch internal problem.

it works for me too.
