### ISSUE TITLE
caculate AR for each class

### ISSUE THREAD

**Issue by zhaojw219** [open-mmlab/mmdetection#1660]
I have got mAP and mAR of all classes and mAP for each class.But how can I get AR for each class?Thanks very much!

**Comment by ZwwWayne** [comment]
Hi @zhaojw219 ,
Currently, we only support the class-wise mAP, but you can implement the class-wise AR following the class-wise mAP implementation in [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/coco_utils.py#L53) and rise a PR, if you are interested.

**Comment by zhaojw219** [comment]
> Hi @zhaojw219 ,
> Currently, we only support the class-wise mAP, but you can implement the class-wise AR following the class-wise mAP implementation in [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/coco_utils.py#L53) and rise a PR, if you are interested.

Thank you very much!But it seems that there are some problems，mAP is 0.96+ on my dataset.But the AP result of each category is about 0.7...Do I need to modify this part of the code?

**Comment by ZwwWayne** [comment]
The evaluation code should have no bugs now because it has been used by many users and no bugs are reported. So this might because the data you send in for evaluation has some problems, you may need to visualize them to check where the bug is.

**Comment by zhaojw219** [comment]
> The evaluation code should have no bugs now because it has been used by many users and no bugs are reported. So this might because the data you send in for evaluation has some problems, you may need to visualize them to check where the bug is.

OK.I will check my data.Thank you very much.

**Comment by ZwwWayne** [comment]
This issue is closed, feel free to reopen it if you have any further questions.

**Comment by biyuruofeng** [comment]
> I have got mAP and mAR of all classes and mAP for each class.But how can I get AR for each class?Thanks very much!

hi，can you tell me how to get mAP for each class?
