### ISSUE TITLE
Using Adam instead if SGD

### ISSUE THREAD

**Issue by IrisLanderer** [open-mmlab/mmdetection#1662]
Hello, I would like to know how to use other optimizers such as Adam instead of SGD. I have already tried to change the configuration, but it doesn't work:

optimizer = dict(type='Adam', lr=0.001, betas=(0.9, 0.999), eps=1e-08)

Could anyone please help me?

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.
What do you mean when you are saying it doesn't work? 
We are not able to find the problem and help you if you do not provide the logs/error messages.
