### ISSUE TITLE
AP AR = -1

### ISSUE THREAD

**Issue by chun2925084** [open-mmlab/mmdetection#1664]
I have used faster_rcnn_r50_fpn_1x.py to trained on my own data
Here is the loss
![image](https://user-images.githubusercontent.com/26199242/68822139-18a7cf80-06cb-11ea-9ef8-537fe2deb2c9.png)
when I test the result by using test.py it shows that all the AP and AR are -1(below is the result). But, before I used --show the prediction of every image is very accurate. 
![image](https://user-images.githubusercontent.com/26199242/68822045-d1b9da00-06ca-11ea-800b-9f5791419de6.png)
I am very confused, please help!!!!!

**Comment by ZwwWayne** [comment]
Hi @chun2925084 ,
Please use the `Error Template`, these two images do no help to locate the problems and more information is needed, e.g., what is your data annotation, what modification you did.
