### ISSUE TITLE
Load model on multiple gpus by default

### ISSUE THREAD

**Issue by jasper2326** [open-mmlab/mmdetection#1669]
typing
```init_detector($config_path, $checkpoint_path, device='cuda:1')```
I am trying to load model on CUDA:1 but the model will be load on **both CUDA:0 and CUDA:1** with the same pid.
Please help me solve this problem, thank you

**enviroment**
1. CUDA 9
2. Pytorch 1.1
3. python 3.6
4. mmdet 1.0.0rc

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
