### ISSUE TITLE
Is keypoint regressor available?

### ISSUE THREAD

**Issue by whikwon** [open-mmlab/mmdetection#167]
Is keypoint regressor available in mmdetection?

**Comment by hellock** [comment]
Keypoint head is currently not supported, and community contribution is welcome.

**Comment by whikwon** [comment]
Thanks. I have a work keypoint head needed so that I have to implement. 
If the implementation is not for the foreseeable future, I will end work and contribute.

**Comment by hellock** [comment]
That would be very nice. Thanks!

**Comment by lzhbrian** [comment]
Hi, any progress on this?

**Comment by nemonameless** [comment]
@hellock  Hi, is there any plan on keypoint ?

**Comment by lxtGH** [comment]
Hi any new plan on keypoint ?

**Comment by mathmanu** [comment]
Looking forward for keypoint support!

**Comment by powerlic** [comment]
I implemented a version of mask_rcnn with keypoint and mask according to the tutorial and the detectron2, but the keypoint branch does not seem work (the loss can not converge as the detectron2),  anybody could give me some advices?  the link is https://github.com/powerlic/mmdetection 
the start command is python train path/to/your/configs/keypoint/mask_keypoint_r50_fpn_1x_coco.py --gpus 1
@hellock

**Comment by powerlic** [comment]
![截屏2020-06-07 下午10 44 06](https://user-images.githubusercontent.com/18439513/83971990-80946080-a910-11ea-8f63-d551990e2dac.png)

**Comment by SebastienLinker** [comment]
@powerlic Thanks for this work. I noticed you do some data augmentation during training (Resize, crops) but don't always adjust the keypoints accordingly. 
I changed the loss and compute the loss between 2 heatmaps instead of a heatmap and some keypoints.
I think we also need to output the keypoints. 

But so far I am still stuck there

**Comment by SebastienLinker** [comment]
Based on @powerlic work, we redesigned the loss functions and implemented a keypoints detector based on HRNet:
https://github.com/open-mmlab/mmdetection/pull/3391

**Comment by jshilong** [comment]
> @powerlic Thanks for this work. I noticed you do some data augmentation during training (Resize, crops) but don't always adjust the keypoints accordingly.
> The losses are producing one heatmap per keypoint, if we have 2 persons we will have 2*17 heatmaps. Shouldn't it be 17 heatmaps? (edit: nevermind, I had another paper in mind)
> 
> I changed the loss and compute the loss between 2 heatmaps instead of a heatmap and some keypoints.
> I think we also need to output the keypoints.
> 
> In addition, we also have to update the drawing functions to display keypoints and the output of mmdetection inference. I suggest to output a dict with fields like `keypoints`, `masks`, `bboxes` ...

Thanks for your contribution and your suggestions about the output of the model, we will support more tasks including the 
keypoints in the near future.
