### ISSUE TITLE
[HTC] Mismatch in AP of object scale between model zoo and htc paper

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#1672]
I found that the mask AP between model zoo and HTC paper is comparable but the AP for different object scales is not consistent. 

|        Model       |  AP  | AP50 | AP75 | APS  | APM  | APL  |
|:------------------:|:----:|:----:|------|------|------|------|
| HTC from model zoo | 38.1 | 59.4 | 41.0 | 17.9 | 40.7 | 56.6 |
| HTC from paper     | 38.0 | 59.4 | 40.7 | 20.3 | 40.9 | 52.3 |

The ``HTC from model zoo`` is tested using latest code (@[4d8416](https://github.com/open-mmlab/mmdetection/commit/4d84161f142b7500089b0db001962bbc07aa869d)). I guess the evaluation code has been changed somehow. I report it here and hope we can figure out what is the problem.

Updated: I also test with Mask R-CNN and it also has the same problem.

**Comment by hellock** [comment]
There can also be other reasons.
1. They are not the same checkpoint, we re-trained HTC models before the code release.
2. Code refactoring happens during that period.

**Comment by hellock** [comment]
It is interesting that the AP on small and large objects are very different. There maybe some refactoring which leads to that.

**Comment by hellock** [comment]
Thanks for the fix!
