### ISSUE TITLE
BBox with shape [n, num_classes*4] resize error when keep_ratio=False 

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmdetection#1673]
**Describe the bug**
I trained libra_faster_rcnn with setting `(type='Resize', img_scale=(512, 512), keep_ratio=False)`. Training is okay but when I run test and inference, it reports RuntimeError. The error is:
```Traceback (most recent call last):
  File "/home/rangilyu/Projects/mmdetection/mmdet/apis/inference.py", line 86, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/rangilyu/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rangilyu/Projects/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/rangilyu/Projects/mmdetection/mmdet/models/detectors/base.py", line 119, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/rangilyu/Projects/mmdetection/mmdet/models/detectors/base.py", line 102, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/rangilyu/Projects/mmdetection/mmdet/models/detectors/two_stage.py", line 273, in simple_test
    x, img_meta, proposal_list, self.test_cfg.rcnn, rescale=rescale)
  File "/home/rangilyu/Projects/mmdetection/mmdet/models/detectors/test_mixins.py", line 60, in simple_test_bboxes
    cfg=rcnn_test_cfg)
  File "/home/rangilyu/Projects/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/rangilyu/Projects/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 158, in get_det_bboxes
    bboxes /= torch.from_numpy(scale_factor).to(bboxes.device)
RuntimeError: The size of tensor a (324) must match the size of tensor b (4) at non-singleton dimension 1
```

**Environment**
 - OS: [Ubuntu 18.04]
 - GCC [5.5.0]
 - PyTorch version [1.3.1]
- How you installed PyTorch [conda]
- GPU model [1080Ti]
- CUDA version 10.1

**Bug fix**
The error is in[ bbox_head.py, line 158](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/bbox_heads/bbox_head.py#L158):
```
bboxes /= torch.from_numpy(scale_factor).to(bboxes.device)
```
bboxes is a tensor which shape is [1000, 324], 324=num_classes * 4, when keep_ratio=True, the scale_factor is a float, so it works fine with bboxes /= scale_factor. But when keep_ratio=False, the scale_factor is a numpy array which size is [1,4], a [1000,324] tensor cannot be devided by a  [1,4] array.
I fixed this bug by changing the code in [bbox_head.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/bbox_heads/bbox_head.py#L154) like this:
```
        if rescale:
            if isinstance(scale_factor, float):
                bboxes /= scale_factor
            else:
                if bboxes.shape[1] == 4:
                    bboxes /= torch.from_numpy(scale_factor).to(bboxes.device)
                else:
                    scale_factor = torch.from_numpy(scale_factor).to(bboxes.device)
                    for i in range(1, cls_score.shape[1]):
                        bboxes[:, i * 4:(i + 1) * 4] /= scale_factor
```

**Comment by xmyqsh** [comment]
```
        if rescale:
            if isinstance(scale_factor, float):
                bboxes /= scale_factor
            else:
                if bboxes.shape[1] == 4:
                    bboxes /= torch.from_numpy(scale_factor).to(bboxes.device)
                else:
                    scale_factor = torch.from_numpy(scale_factor).to(bboxes.device)
                    bboxes = (bboxes.view(bboxes.size()[0], -1, 4) / scale_factor).view(bboxes.size()[0], -1)
```
@RangiLyu How about this instead of for loop?

**Comment by RangiLyu** [comment]
> ```
>         if rescale:
>             if isinstance(scale_factor, float):
>                 bboxes /= scale_factor
>             else:
>                 if bboxes.shape[1] == 4:
>                     bboxes /= torch.from_numpy(scale_factor).to(bboxes.device)
>                 else:
>                     scale_factor = torch.from_numpy(scale_factor).to(bboxes.device)
>                     bboxes = (bboxes.view(bboxes.size()[0], -1, 4) / scale_factor).view(bboxes.size()[0], -1)
> ```
> 
> @RangiLyu How about this instead of for loop?

@xmyqsh Nice! Thanks for your code! In this way, there is no need to judge bbox.shape[1]==4 so that the 'if else' can also be removed like this:
```
        if rescale:
            if isinstance(scale_factor, float):
                bboxes /= scale_factor
            else:
                scale_factor = torch.from_numpy(scale_factor).to(bboxes.device)
                bboxes = (bboxes.view(bboxes.size()[0], -1, 4) / scale_factor).view(bboxes.size()[0], -1)
```

**Comment by ZwwWayne** [comment]
Looks like a bug, feel free to fix it and propose a PR.

**Comment by ZwwWayne** [comment]
Please see the PRhttps://github.com/open-mmlab/mmdetection/pull/1730.
