### ISSUE TITLE
How to exclude mmdet in installation?

### ISSUE THREAD

**Issue by fanq15** [open-mmlab/mmdetection#1675]
I add `mmdet` in the `exclude` packages in the Line140 of `setup.py`, and I use the `python setup.py develop` to install the code. However, when I install the `code1` and copy it to `code2`, and train the model in `code2`, the model uses the `mmdet` in `code1`. It means after installation, the `code1` and `code2` use the `mmdet` in `code1`. I want the `mmdet` like the `configs`, so that I can modify it independently in every code copy. Could you help me fix it? Thank you.

**Comment by ZwwWayne** [comment]
Please check the [installation guide ](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md).
