### ISSUE TITLE
Incongruence between DeformConv and ModulatedDeformConv

### ISSUE THREAD

**Issue by sebamenabar** [open-mmlab/mmdetection#1676]
**Describe the bug**
Hi, in the implementation of regular DeformableConvs, the **stride, padding and dilation** are casted to tuple (by applying `_pair()`) and the output size is calculated with that on consideration.

On the other hand, in the ModulatedDeformableConvs function, there is no casting of those parameters and the output shape is calculated like this:

```python
height_out = (height + 2 * ctx.padding -
                      (ctx.dilation * (kernel_h - 1) + 1)) // ctx.stride + 1
width_out = (width + 2 * ctx.padding -
                      (ctx.dilation * (kernel_w - 1) + 1)) // ctx.stride + 1
```
So it does not support setting **stride, padding and dilation** as tuples.

**Reproduction**

```python
from mmdet.ops import dcn
conv = dcn.ModulatedDeformConvPack(1, 2, 3, padding=(1,2)).cuda()
conv(torch.randn(1, 1, 4,4).cuda())
```

**Environment**
 - OS: Ubuntu 18.04.2
 - GCC Not sure, let me know if required
 - PyTorch version 1.3
- How you installed PyTorch: pip
- GPU model: GTX1080ti
- CUDA: 10.1.243 and CUDNN: not sure how to find it

**Error traceback**
Execution raises:
```python
/mnt-homes/kraken/samenabar/code/mmdetection/mmdet/ops/dcn/deform_conv.py in _infer_shape(ctx, input, weight)
    177         height, width = input.shape[2:4]
    178         kernel_h, kernel_w = weight.shape[2:4]
--> 179         height_out = (height + 2 * ctx.padding -
    180                       (ctx.dilation * (kernel_h - 1) + 1)) // ctx.stride + 1
    181         width_out = (width + 2 * ctx.padding -

TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
```

**Bug fix** (Proposed)
(I think), on ModulatedDeformConvFunction, wrap stride, padding and dilation with `_pair()` and use DeformConvFunction's method to calculate output_size for ModulatedDeformConvFunction

Thanks

**Comment by ZwwWayne** [comment]
Thanks for your advice, since the current implementation of DCN covers most of the needs, we do not have a plan to modify it yet. We might do it in the future if we have time.

**Comment by ZwwWayne** [comment]
The issue is closed, feel free to reopen it if you have any further questions.
