### ISSUE TITLE
AttributeError: install_layout

### ISSUE THREAD

**Issue by yulubin** [open-mmlab/mmdetection#1677]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I follow the step in the INSTALL.md, after I type 'python setup.py develop' in the terminal, the terminal show the error.

**Reproduction**
1. What command or script did you run?
```
python setup.py develop
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
default
**Environment**
 - OS: Ubuntu 16
 - GCC 5.4.0
 - PyTorch version 1.2.0
- How you installed PyTorch conda
- GPU model M5000
- CUDA and CUDNN version CUDA 10 CUDNN 7.6.4

**Error traceback**
If applicable, paste the error trackback here.
```
(ylb) scut@scut-PC:~/mmskeleton$ python setup.py develop
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 353, in fetch_build_egg
cmd = self._egg_fetcher
AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "setup.py", line 174, in
zip_safe=False)
File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/core.py", line 108, in setup
_setup_distribution = dist = klass(attrs)
File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in init
self.fetch_build_eggs(attrs['setup_requires'])
File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
replace_conflicting=True,
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 826, in resolve
dist = best[req.key] = env.best_match(req, ws, installer)
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 1092, in best_match
return self.obtain(req, installer)
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 1104, in obtain
return installer(requirement)
File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 378, in fetch_build_egg
cmd.ensure_finalized()
File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
self.finalize_options()
File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 289, in finalize_options
'install_lib', ('install_dir', 'install_dir')
File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 287, in set_undefined_options
src_cmd_obj.ensure_finalized()
File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
self.finalize_options()
File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
self.set_undefined_options('install',('install_layout','install_layout'))
File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 290, in set_undefined_options
setattr(self, dst_option, getattr(src_cmd_obj, src_option))
File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 103, in getattr
raise AttributeError(attr)
AttributeError: install_layout
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
This seems to be a bug caused by **setuptools**, you can try to reinstall it. https://github.com/pypa/setuptools/issues/1086

**Comment by ZwwWayne** [comment]
Btw, why you report the bug to mmdetection when you seems to be installing mmskeleton?

**Comment by yulubin** [comment]
> This seems to be a bug caused by **setuptools**, you can try to reinstall it. [pypa/setuptools#1086](https://github.com/pypa/setuptools/issues/1086)

OK，I’ll try

**Comment by yulubin** [comment]
> Btw, why you report the bug to mmdetection when you seem to be installing mmskeleton?

The bug appeared when I install mmskeleton, so I try to install mmdetection first, then the bug appeared again.

**Comment by ZwwWayne** [comment]
So this should be the bug of the code environment rather than the codebase.

**Comment by kuangleiniubi** [comment]
> > Btw, why you report the bug to mmdetection when you seem to be installing mmskeleton?
> 
> The bug appeared when I install mmskeleton, so I try to install mmdetection first, then the bug appeared again.

Hi there,
I recently encounter with the exact same error, which is  AttributeError: install_layout when installing mmcv package.
I was just wondering how did you solve it? Looking forward to your early reply.
Thanks a lot!

**Comment by yulubin** [comment]
> > > Btw, why you report the bug to mmdetection when you seem to be installing mmskeleton?
> > 
> > 
> > The bug appeared when I install mmskeleton, so I try to install mmdetection first, then the bug appeared again.
> 
> Hi there,
> I recently encounter with the exact same error, which is AttributeError: install_layout when installing mmcv package.
> I was just wondering how did you solve it? Looking forward to your early reply.
> Thanks a lot!

No，I finally install mmedetection on another computer, and it worked. Maybe just like ZwwWayne said, this was caused by the bug of  **setuptools**. I failed to install on the ubuntu with **setuptools 20.7**, and  install on the ubuntu with **setuptools**with 40.8 successfully.

**Comment by kuangleiniubi** [comment]
> > > > Btw, why you report the bug to mmdetection when you seem to be installing mmskeleton?
> > > 
> > > 
> > > The bug appeared when I install mmskeleton, so I try to install mmdetection first, then the bug appeared again.
> > 
> > 
> > Hi there,
> > I recently encounter with the exact same error, which is AttributeError: install_layout when installing mmcv package.
> > I was just wondering how did you solve it? Looking forward to your early reply.
> > Thanks a lot!
> 
> No，I finally install mmedetection on another computer, and it worked. Maybe just like ZwwWayne said, this was caused by the bug of **setuptools**. I failed to install on the ubuntu with **setuptools 20.7**, and install on the ubuntu with **setuptools**with 40.8 successfully.

Yeah I also worked it out recently on another server. Thanks so much for your reply.

**Comment by lucasfagiolli** [comment]
It happened to me in a script I downloaded, I followed these instructions to solve the problem by installing Setuptools in Python 3 it worked perfectly for me.

Here's a summary of the steps I took:

Downloaded the latest Setuptools source package for Python 3 from the [official website](https://pypi.org/project/setuptools/#files) using the command:

`curl https://files.pythonhosted.org/packages/69/77/aee1ecacea4d0db740046ce1785e81d16c4b1755af50eceac4ca1a1f8bfd/setuptools-60.5.0.tar.gz > setuptools-60.5.0.tar.gz`

Extracted the downloaded package with the command:


`tar -xzvf setuptools-60.5.0.tar.gz`

Navigated to the Setuptools directory:


`cd setuptools-60.5.0`

Installed the package using:
`python3 setup.py install`

After the installation, I verified that Setuptools was installed correctly using:
`python3 -m easy_install --version`

After installation, I verified that Setuptools installed correctly using:
`python3 -m easy_install --version`

Import configuration tools:
```
Python3
> import configuration tools
```

Once this is done, check if you can execute the command again

**Comment by NapatChomchuen** [comment]
try this

sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED

pip uninstall setup tools

pip uninstall ujson

curl https://files.pythonhosted.org/packages/69/77/aee1ecacea4d0db740046ce1785e81d16c4b1755af50eceac4ca1a1f8bfd/setuptools-60.5.0.tar.gz > setuptools-60.5.0.tar.gz

tar -xzvf setuptools-60.5.0.tar.gz

cd setuptools-60.5.0

python3 setup.py install

pip install ujson

Cd OLED_python3

sudo python3 setup.py install

**Comment by bgigous** [comment]
> curl https://files.pythonhosted.org/packages/69/77/aee1ecacea4d0db740046ce1785e81d16c4b1755af50eceac4ca1a1f8bfd/setuptools-60.5.0.tar.gz > setuptools-60.5.0.tar.gz
> 
> tar -xzvf setuptools-60.5.0.tar.gz
> 
> cd setuptools-60.5.0
> 
> python3 setup.py install
> 
> pip install ujson

Holy crap, *THANK YOU.* I found your comment after banging my head against the wall in trying to use `setup.py` for a *completely separate* project which gave me the `AttributeError: install_layout`. I even had the "latest" setuptools v66.1.1-1 for my system. But still, the error occurred.

So, I said "screw it." Uninstalled setuptools, installed the version 60.5.0 through the method you provided, retried `setup.py` on the problem package, and BOOM. It installed without the error. 😑😂😭 

Again, THANK YOU.
