### ISSUE TITLE
Making MS RCNN data

### ISSUE THREAD

**Issue by lijain** [open-mmlab/mmdetection#1678]
Can you tell me how to make MS RCNN data format with label and mask in your own data set

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#use-my-own-datasets

**Comment by lijain** [comment]
I know that. I want to ask, when my data has images, labels, mask, how can I build. Pkl format? Before VOC, I have built scripts





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wenwei Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 晚上8:47
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] Making MS RCNN data (#1678)




https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#use-my-own-datasets

**Comment by ZwwWayne** [comment]
You could follow the [script](https://github.com/open-mmlab/mmdetection/blob/master/tools/convert_datasets/pascal_voc.py) for converting VOC.

**Comment by lijain** [comment]
Well, you didn't understand me. I want to say that I have the code for VOC to. Pkld. What I want to ask is how to convert data like images, labels and mask to. Pkl. Because I want to run MS RCNN





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wenwei Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 中午11:27
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] Making MS RCNN data (#1678)




You could follow the script for converting VOC.

**Comment by ZwwWayne** [comment]
1. You do not need to convert data like images, labels and mask to .pkl file to run MS RCNN, you only need to use the [config](https://github.com/open-mmlab/mmdetection/tree/master/configs/ms_rcnn) following the [guide](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md).
2. You can [google](https://www.google.com/search?q=how+to+convert+image+to+pkl&oq=how+to+convert+image+to+pkl&aqs=chrome..69i57.9238j0j7&sourceid=chrome&ie=UTF-8) how to convert data to .pkl file.

**Comment by ZwwWayne** [comment]
This issue is closed because the question seems to be answered. Feel free to reopen it if you have any further questions.

**Comment by lijain** [comment]
ok,I know how
