### ISSUE TITLE
How to use M2Det mentioned in  the technical report?

### ISSUE THREAD

**Issue by WangChengKai-WCK** [open-mmlab/mmdetection#1680]
**Describe my question**
Hi, in the technical report, it mentioned that mmdetection supports  "General Modules and Methods" including **M2Det**. So I hope to use it in my experiments.

But,  I have browsed the project of mmdetection carefully, **there is no module of M2Det.** 
**So I want to know how to find the module of M2Det, thanks!**

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/pull/820
