### ISSUE TITLE
Deadlock using multiprocessing test.

### ISSUE THREAD

**Issue by t-m-k** [open-mmlab/mmdetection#1684]
when using multiprocessing test the model, the gpu will be deadlock(100%).

```
from mmdet.apis import init_detector, inference_detector, show_result
import os
import argparse
import sys
import torch
import threading

def func(model):
    for i in range(100000):
        img = './t.jpg'
        print(img)
        result = inference_detector(model,img)

def main():
  config_file = 'libra_faster_rcnn_r50_fpn_1x.py'
  checkpoint_file = 'last.pth'
  model = init_detector(config_file, checkpoint_file)
  treadnum = 6
  threads = []
  for i in range(treadnum):
      threads.append(threading.Thread(target=func,args=(model,)))
      threads[i].start()
```

gpu:Tesla V100
pytroch:1.1.0
gcc:4.9
cuda:10.1
python:3.7

**Comment by ZwwWayne** [comment]
First, I think the model is not inference anything, because the variable `img` is a string rather than a picture.
Second, do you meet any problem when using the scripts in the codebase? We have already provided a version for multi-gpu test in the [test.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L38).

**Comment by t-m-k** [comment]
> First, I think the model is not inference anything, because the variable `img` is a string rather than a picture.
> Second, do you meet any problem when using the scripts in the codebase? We have already provided a version for multi-gpu test in the [test.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L38).

1: inference_detector  receive a model and a pic path, the './t.jpg' is a img path in current dir.
2: I found there are also  deadlock only three fc layers in model using multiprocessing forward in Tesla V100.
As:
The Net 
```
import torch
import torch.nn as nn
class FC(nn.Module):
    def __init__(self):
        super(FC, self).__init__()
        self.fc1 = nn.Linear(12544, 1024)
        self.fc2 = nn.Linear(1024, 1024)
        self.fc3 = nn.Linear(1024, 2)

    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        return x
```
The test scipt:
```
import torch
import threading
from fc_layer import FC

def func(model):
    for i in range(100000):
        inp = torch.randn(3,12544).cuda()
        out = model(inp)

def main():
  model = FC().cuda()
  treadnum = 6
  threads = []
  for i in range(treadnum):
      threads.append(threading.Thread(target=func,args=(model,)))
      threads[i].start()

```
Out is deadlock with 100% GPU-Util
![image](https://user-images.githubusercontent.com/20682161/69207956-cd8b3200-0b8c-11ea-9dd1-de8b87e2a7fa.png)

There is the similar problem in pytorch git:
https://github.com/pytorch/pytorch/issues/22259

**Comment by ZwwWayne** [comment]
So why do you want to do that, what is the purpose?

**Comment by hellock** [comment]
@t-m-k Using multiple processes (instead of threads) is not as simple as what you showed. You may refer to https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/parallel_test.py.

**Comment by t-m-k** [comment]
@hellock OK! Its very helpful, thank you very much!!!
