### ISSUE TITLE
multi gpus problem

### ISSUE THREAD

**Issue by PL-96** [open-mmlab/mmdetection#1689]
subprocess.CalledProcessError: Command '['/home/lihonghao/anaconda3/envs/mmdetection/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/mo.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by solauky** [comment]
Same problem. Seek solutions. Thank you ~

**Comment by hellock** [comment]
Please use the `Error report` issue template.

**Comment by PAUPAUPAUL** [comment]
Same problem, did you find the solution?

**Comment by hellock** [comment]
> Same problem, did you find the solution?

Please use the `Error report` issue template to provide useful information.

**Comment by milleniums** [comment]
请问如何解决的呀？

**Comment by andjsmile** [comment]
Same problem. Still don't solve.

**Comment by hongrui16** [comment]
is there any solution for this issue?

**Comment by milleniums** [comment]
可能是因为安装的pytorch是CPU版本

**Comment by henbucuoshanghai** [comment]
same question  ..  help

**Comment by Yinhance** [comment]
Anyone solved it? 
Much thx!
