### ISSUE TITLE
How to use resnet+fpn on SSD detector?

### ISSUE THREAD

**Issue by zhoulukuan** [open-mmlab/mmdetection#1690]
Hi, thanks for this great work. I want to train SSD with resnet+fpn. However, I only find `ssd_vgg.py` in backbones and vgg config file in `ssd512/300_coco.py`. So it doesn't support train SSD with resnet+fpn? What should I do if I want to do, any reference?

**Comment by Kaeseknacker** [comment]
To my knowledge, no backbone other than VGG is supported for the SSD.
But:
resnet + fpn + ssd ~= retina net? :-)
