### ISSUE TITLE
Test Pipeline without Resize

### ISSUE THREAD

**Issue by Kaeseknacker** [open-mmlab/mmdetection#1691]
Is it possible to test (inference) images with it's original image size? 
The test_pipeline in every config file contains the lines: img_scale=(1333, 800) and dict(type='Resize', keep_ratio=True). So if I test a full HD image it will be downscaled and if i test a Pascal VOC image (~500x300) it will be upscaled?!

**Comment by hellock** [comment]
Yes images are resized to the specified size for two reasons:
- Models are trained at the scale of (1333, 800), and perform well on the scale.
- Adopting larger sizes may leads to better performance, but consumes more memory. You can specify a size as you want.
