### ISSUE TITLE
no print loss information

### ISSUE THREAD

**Issue by zhaojw219** [open-mmlab/mmdetection#1692]
When I train,there is no loss information to print.Can anyone help me?

**Comment by Kaeseknacker** [comment]
While training you should get something like this in your terminal:

`2019-11-19 15:11:02,274 - INFO - Epoch [1][305/323]	lr: 0.01000, eta: 16:36:20, time: 2.030, data_time: 0.015, memory: 20804, loss_cls: 0.8663, loss_bbox: 0.5393, loss: 1.4055`

The frequency of how often this line is printed, you can set in the config file:
https://github.com/open-mmlab/mmdetection/blob/e033ef69a8bb58dd5fa0902942f628481c21c666/configs/retinanet_x101_64x4d_fpn_1x.py#L118
Maybe your training did not start properly and therefore you never see this line?

**Comment by zhaojw219** [comment]
> While training you should get something like this in your terminal:
> 
> `2019-11-19 15:11:02,274 - INFO - Epoch [1][305/323] lr: 0.01000, eta: 16:36:20, time: 2.030, data_time: 0.015, memory: 20804, loss_cls: 0.8663, loss_bbox: 0.5393, loss: 1.4055`
> 
> The frequency of how often this line is printed, you can set in the config file:
> https://github.com/open-mmlab/mmdetection/blob/e033ef69a8bb58dd5fa0902942f628481c21c666/configs/retinanet_x101_64x4d_fpn_1x.py#L118
> 
> 
> Maybe your training did not start properly and therefore you never see this line?

Thanks so much!

**Comment by ZwwWayne** [comment]
This issue is closed because the problem seems to be solved, feel free to reopen it if you have further questions.
