### ISSUE TITLE
ERROR QUESTION ON RUNNING IMAGE CAPTIONING CODE (using Deep Learning (CNN and LSTM) in PyTorch)

### ISSUE THREAD

**Issue by saandbad** [open-mmlab/mmdetection#1694]
Thanks for your error report and we appreciate it a lot.
Hi,

Please, help to find the solution to this unknown error  : UnpicklingError: unpickling stack underflow
while I run the train.py file of image captioning (https://www.analyticsvidhya.com/blog/2018/04/solving-an-image-captioning-task-using-deep-learning/ )
![2019-11-20 17_22_09-C__Windows_System32_cmd exe](https://user-images.githubusercontent.com/56487830/69283565-a77c8680-0bba-11ea-8e86-49c08ec7546b.png)

**Comment by hellock** [comment]
It is irrelevant to this repo.
