### ISSUE TITLE
multi-gpu training process got stuck  occasionally

### ISSUE THREAD

**Issue by nyyznyyz1991** [open-mmlab/mmdetection#1696]
I'm running my code on a cloud server with 8*v100, it looks like one process was not working, and it still occupied the gpu memory. Other processes were waiting for this lost process!
Could you give some advice?

![image](https://user-images.githubusercontent.com/15084560/69298822-edccf680-0c49-11ea-9c13-bbd4416b30cc.png)
![image](https://user-images.githubusercontent.com/15084560/69298831-f0c7e700-0c49-11ea-8fe1-3f1646ab30ac.png)

**Comment by nyyznyyz1991** [comment]
I use a docker environment with cuda9 and driver version 410.93

**Comment by ZwwWayne** [comment]
Hi @nyyznyyz1991 ,
Could you also provide logs or use the `Error Template`?
This two pictures cannot help us to locate the problem, and maybe it is just OK if you check the logs.
