### ISSUE TITLE
the difference of map between val and test-dev

### ISSUE THREAD

**Issue by hust-kevin** [open-mmlab/mmdetection#1700]
in mmdet, MAP is reported on coco_2017_val ,usually in most detection paper, MAP is reported on test-dev,  any relationship between the MAP on val and test-dev? what's more, how can we get the performance on test-dev?

**Comment by hellock** [comment]
They are different split of COCO. You can test the model on test-dev and submit the results to the official test server to get the performance.

**Comment by zhangshen12356** [comment]
> They are different split of COCO. You can test the model on test-dev and submit the results to the official test server to get the performance.

how can i find the official test server to get the performance?
