### ISSUE TITLE
could I use iter to control learning process rather than epoch?

### ISSUE THREAD

**Issue by YilanWang** [open-mmlab/mmdetection#1702]
I want to control the learning process more accurately, such as increasing or decreasing the learning rate within an epoch. Is there a parameter that can directly control the iteration instead of epoch? like warmup_iters in warmup processing. Thanks!

**Comment by Etoye** [comment]
Interesting at this question too!

**Comment by hellock** [comment]
There is an argument [`by_epoch`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/lr_updater.py#L10) that determines the learning rate adjustment. If set to False, the learn rate will be updated by iteration.

**Comment by YilanWang** [comment]
wow! Thank you for your answer! I find it in mmcv. Time to read mmcv codes!
