### ISSUE TITLE
Can you provide each model  with a metrics file like detectron2

### ISSUE THREAD

**Issue by XCRobert** [open-mmlab/mmdetection#1706]
**Describe the feature**
 A metrics file like detectron2 have all the training statistics and evaluation curves of a model.
**Motivation**
It will be helpful to check the loss at the same epoch and the same iteration for reference.

**Related resources**
Metric files can be get from: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

**Comment by ZwwWayne** [comment]
Hi @XCRobert ,
We already support this. During training, MMDet not only saves a log.txt but also provides a log.txt.json. You can use the provided [tool](https://github.com/open-mmlab/mmdetection/blob/master/tools/analyze_logs.py) following the [guidance](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md) to use them.

**Comment by XCRobert** [comment]
Thanks for your reply.But I mean can you provide  training log from your group , were the log files generated from your model trainings  backed up. Sometimes I want  to compare my method with correspond model , but in order to compare the loss with mine I had to reproduce your model by training again while having not enough gpu resources .  It will be appreciated if you can  provide metric files just like the below picture(underline in red)
![image](https://user-images.githubusercontent.com/16361120/69477344-160e4e00-0e20-11ea-95bd-04f74948227e.png)

**Comment by ZwwWayne** [comment]
Thanks for your advice.
For now, we might not be able to provide them with current models because it has been a long time since we released them. We will take your advice into consideration next time we re-benchmark the models.

**Comment by ZwwWayne** [comment]
This issue is closed, feel free to reopen it if you have any further questions.
