### ISSUE TITLE
How to achive dense connection on FPN? Can you help me

### ISSUE THREAD

**Issue by 18804601171** [open-mmlab/mmdetection#1712]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hellock** [comment]
You can write a new neck module or modify https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/necks/fpn.py
