### ISSUE TITLE
How to load multiple models such as student model and teacher model？

### ISSUE THREAD

**Issue by UcanSee** [open-mmlab/mmdetection#1713]
recently I want to try some experiments about knowladge distillation, but when I start setting up the networks, I don't know how to set up two models wchich represents teacher model and student model respectively. Did mmdetection support to set up two models simultanously? Or what should I do to achieve this goal?

**Comment by hellock** [comment]
You can jut initialize two models by modifying the [training script](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L83) and load the checkpoints respectively. It should not be hard.

**Comment by chuong98** [comment]
You can write a new Dectector, named Distillation Detector, then specify Teacher and Student NW in one model.

**Comment by zhaojw219** [comment]
Hi,did you implement model distillation?

**Comment by hellock** [comment]
Feel free to reopen it if you have any further questions.
