### ISSUE TITLE
Only 'MaxIoUAssigner' has been used in configs. 

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#1714]
https://github.com/open-mmlab/mmdetection/tree/master/mmdet/core/bbox/assigners

Why other as signers is needed for? There should be examples of usage of them

**Comment by hellock** [comment]
`ApproxMaxIoUAssigner` is used in GuidedAnchoring, see [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/guided_anchoring/ga_faster_r50_caffe_fpn_1x.py#L65) for examples.
`PointAssigner` is used in RepPoints, see [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/reppoints/reppoints_minmax_r50_fpn_1x.py#L46) for examples.

**Comment by korabelnikov** [comment]
my bad, i missed it
