### ISSUE TITLE
Thank you for your work! How do I use multiple GPUs when I infer a batch of images using the high-level API? 

### ISSUE THREAD

**Issue by liugaolian** [open-mmlab/mmdetection#1717]
Thank you for your work!
How do I use multiple GPUs when I infer a batch of images using the high-level API?
I'm trying to deploy mmdetection to the production environment! But I only saw the demo of multi GPU test.

**Comment by hellock** [comment]
We have not implement a high-level api of using multiple gpus for inference. Different deployment schemes usually implement their own apis. This repo provides a multi-gpu testing script on datasets and a high-level api on a single image.
