### ISSUE TITLE
error: torch 1.1.0 is installed but torch==1.3.1 is required by {'torchvision'}

### ISSUE THREAD

**Issue by Weizhen-Fang** [open-mmlab/mmdetection#1718]
When I install, this error appeared.
Must I change torch to 1.3.1?

**Comment by ZwwWayne** [comment]
You can also change the version of torchvision.

**Comment by Weizhen-Fang** [comment]
I have installed torchvision 0.2.2. But when I install mmdet, It will download torchvision 0.4.2 automatically. 
here is the command:
Processing dependencies for mmdet==1.0rc0+b17f88c
Searching for torchvision
Reading https://pypi.org/simple/torchvision/
Downloading https://files.pythonhosted.org/packages/74/ee/d872c12ea508f9cca4cf0d7b91fc5a5e476cec77628a66795ec5a585a67f/torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl#sha256=276a385f2f5fe484bf08467b5d081d9144b97eb458ba5b4a11e4640389e53149
Best match: torchvision 0.4.2
Processing torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl
Installing torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl to /mnt/lustre/fangweizhen/anaconda3/envs/mmlab/lib/python3.7/site-packages
Adding torchvision 0.4.2 to easy-install.pth file
Installed /mnt/lustre/fangweizhen/anaconda3/envs/mmlab/lib/python3.7/site-packages/torchvision-0.4.2-py3.7-linux-x86_64.egg
error: torch 1.1.0 is installed but torch==1.3.1 is required by {'torchvision'}

Is that mean I must use torch 1.3.1?

**Comment by Weizhen-Fang** [comment]
> You can also change the version of torchvision.
> Since this does not relate to the mmdet, this issue is closed, feel free to reopen it if you have questions related to the codebase.

I have installed torchvision 0.2.2. But when I install mmdet, It will download torchvision 0.4.2 automatically.
here is the command:
Processing dependencies for mmdet==1.0rc0+b17f88c
Searching for torchvision
Reading https://pypi.org/simple/torchvision/
Downloading https://files.pythonhosted.org/packages/74/ee/d872c12ea508f9cca4cf0d7b91fc5a5e476cec77628a66795ec5a585a67f/torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl#sha256=276a385f2f5fe484bf08467b5d081d9144b97eb458ba5b4a11e4640389e53149
Best match: torchvision 0.4.2
Processing torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl
Installing torchvision-0.4.2-cp37-cp37m-manylinux1_x86_64.whl to /mnt/lustre/fangweizhen/anaconda3/envs/mmlab/lib/python3.7/site-packages
Adding torchvision 0.4.2 to easy-install.pth file
Installed /mnt/lustre/fangweizhen/anaconda3/envs/mmlab/lib/python3.7/site-packages/torchvision-0.4.2-py3.7-linux-x86_64.egg
error: torch 1.1.0 is installed but torch==1.3.1 is required by {'torchvision'}

Is that mean I must use torch 1.3.1?

**Comment by ZwwWayne** [comment]
No, but how do you installed your pytorch? Usually we use the command `conda install pytorch torchvision -c pytorch` following the [guideline](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md), this already install both pytorch and torchvision, so during compilation it will not install torchvision anymore.

**Comment by hellock** [comment]
PyTorch 1.1 works with torchvision 0.3.0 and PyTorch 1.3.1 works with torchvision 0.4.2. You need to install compatible versions of pytorch and torchvision. If you are not confident about the installation, just follow the official guide mentioned above.
