### ISSUE TITLE
SSD  Conversion to ONNX

### ISSUE THREAD

**Issue by linzhongchen** [open-mmlab/mmdetection#1719]
Finally converted SSD is shown as:
     .......
     ........
     return (%150,%152,%154,%156,%158,%160,%162,%151,%153,%155,%157,%159,%161,%163)

Is this result correct?

Still looking forward to everyone's advice?

**Comment by linzhongchen** [comment]
aadad

**Comment by goodlixu** [comment]
Did you solve this problem? I met the same problem.

**Comment by yy2yy** [comment]
> Finally converted SSD is shown as:
> .......
> ........
> return (%150,%152,%154,%156,%158,%160,%162,%151,%153,%155,%157,%159,%161,%163)
> Is this result correct?
> Still looking forward to everyone's advice?

Did you succeed? What's the situation?
