### ISSUE TITLE
Missing keys in source state_dict issue 

### ISSUE THREAD

**Issue by whikwon** [open-mmlab/mmdetection#172]
Missing keys in source state_dict issue occurs. As i've looked into it, it's from the nn.DataParallel trained weight. 

Could you provide the non-nn.DataParallel trained weight when non_dist_training?
https://discuss.pytorch.org/t/missing-keys-unexpected-keys-in-state-dict-when-loading-self-trained-model/22379/2

**Comment by hellock** [comment]
Could you provide more information? mmdetection is supposed to support both DataParallel weights and non-DataParallel weights.

**Comment by whikwon** [comment]
I got this warning:
```
2018-12-12 11:46:55,588 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias
missing keys in source state_dict: layer3.3.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked,
```
Executed cmd was `python tools/train.py configs/faster_rcnn_r50_fpn_1x.py`

**Comment by hellock** [comment]
You can just ignore the warning and it is related to PyTorch. The pretrained weights in the official model zoo are based on the old BN implementation, which lack some buffers. It has no effects on the training.

**Comment by whikwon** [comment]
Thank you.
