### ISSUE TITLE
the value of  wh_ratio_clip is different with torchvision

### ISSUE THREAD

**Issue by hust-kevin** [open-mmlab/mmdetection#1720]
in [transforms.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/transforms.py#L39), the value of wh_ratio_clip  is `16 / 1000`, however in [torchvision](https://github.com/pytorch/vision/blob/a44d55d87b/torchvision/models/detection/_utils.py#L145) is `1000/16`

**Comment by hellock** [comment]
The implementation is different, see [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/transforms.py#L85-L87) for details. Our implementation is actually `[16/1000, 1000/16]`.

**Comment by hust-kevin** [comment]
thanks for reply, I miss this code

one more quetion about init_weight, I notice in mmdetection use different init ways, for example

in [backbone](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L503) use `kaiming_init`

```python
for m in self.modules():
    if isinstance(m, nn.Conv2d):
        kaiming_init(m)
```

in [fpn](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/necks/fpn.py#L96) use `xavier_init`

```python

for m in self.modules():
    if isinstance(m, nn.Conv2d):
        xavier_init(m, distribution='uniform'

```

in [rpn head](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/rpn_head.py#L25) use `normal_init`

```python
normal_init(self.rpn_conv, std=0.01)
normal_init(self.rpn_cls, std=0.01)
normal_init(self.rpn_reg, std=0.01)
```

in [bbox head](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/bbox_heads/bbox_head.py#L64) , reg and cls fc use` nn.init.normal_`, however in [shared fc](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/bbox_heads/convfc_bbox_head.py#L124) use `nn.init.xavier_uniform_`

so why use the different init in different part, any advice to choose a init when add new layer ?

**Comment by hellock** [comment]
Mostly we just follow the initialization conventions such as the backbone. We do not have a specific rule to initialize new layers and In most cases it does not matter too much.
