### ISSUE TITLE
Add RetinanNet-34-FPN to the model  Zoo

### ISSUE THREAD

**Issue by ternaus** [open-mmlab/mmdetection#1723]
I trained RetinaNet with Resnet 34 backbone on COCO.

I would like to add it to the model Zoo.

It looks like weights for other networks are located at https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/

How can I upload weights there?

**Comment by ternaus** [comment]
@hellock

**Comment by hellock** [comment]
The modelzoo is currently read-only. You may share the link in any other way and we will help to publish the model after validating it.
