### ISSUE TITLE
Training faster-rcnn with IoU Loss

### ISSUE THREAD

**Issue by cancam** [open-mmlab/mmdetection#1733]
Hi,
In technical report IoU-loss variants results are provided as follows;
![Screenshot from 2019-11-29 15-52-11](https://user-images.githubusercontent.com/5897289/69870295-8275cb00-12c0-11ea-8848-5c5d942a842d.png)
In order to reproduce results with IoU-variants, I trained Faster RCNN with SmoothL1 loss and IoULoss for 1 epoch with reduced coco dataset with same configurations except for RCNN localization loss and evaluated in coco-val set. Results are provided below:
**with IoU Loss:**
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.045
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.008
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.013
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.012
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.025
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.066
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.075
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.025
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.070
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.106
**with SmoothL1 Loss:**
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.078
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.190
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.049
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.052
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.098
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.091
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.106
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.214
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.233
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.108
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.263
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.289

From the results it is obvious that directly using IoU-Loss without any change in the faster rcnn architecture it is not possible to reproduce results provided in the technical report. I think the issue original training configuration of Faster-RCNN is based on bounding box deltas, but IoU loss uses normalized box coordinates to generate regression loss. I am planning to replace bboxdeltas with bboxcoordinates to use IoU loss in regression brach. Are you planning to release IoU-loss implementation that is compatible with faster-rcnn architecture. (I guess, current implementation of IoU-Loss and GIoU-Loss is only compatible with FOCS architecture)

Thanks.
Baris.

**Comment by ZwwWayne** [comment]
Hi @cancam ,
1. Since 1) both the mAP are very small (< 10%), 2) the models are trained with only 1 epoch, 3) and you are using am unknown reduced coco dataset split, I doubt the comparison is meaningful and the conclusion that IoU-Loss can not reproduce the results is solid.
2. Using a reduced coco dataset split also cannot guarantee that you can reproduce the results in the technical report, but this does not indicate a bug because you have already modify another thing.

Based on the abovementioned two reasons, I suggest you train the models using the same setting, i.e., same data, config, and scheduler and see the results if you can.

Thie issue is closed, but feel free to reopen it if you have any further questions.

**Comment by yuyijie1995** [comment]
Can you tell me how to add IoU Loss in the Faterrcnn?  Only changed the config.py seems not right.
