### ISSUE TITLE
convert retinanet weight file to .onnx

### ISSUE THREAD

**Issue by zhaojw219** [open-mmlab/mmdetection#1735]
Is there anyone convert retinanet weight file into .onnx? In fact,I have converted successfully,but the output of .xml file generated by .onnx file is wrong,can anyone give me help?Thanks!

**Comment by CRmost** [comment]
How do you convert the modele weight to onnx??@zhaojw219

**Comment by CRmost** [comment]
> 
> 
> Is there anyone convert retinanet weight file into .onnx? In fact,I have converted successfully,but the output of .xml file generated by .onnx file is wrong,can anyone give me help?Thanks!
How do you convert the modele weight to onnx??@zhaojw219

**Comment by Ru-Van** [comment]
@zhaojw219, @CRmost, Do you convert the retinanet weight to onnx?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#convert-to-onnx-experimental
