### ISSUE TITLE
about distributed training

### ISSUE THREAD

**Issue by ZhangYumi** [open-mmlab/mmdetection#1737]
hello,may someone tell me what is the difference between distributed training(gpus=2) and non-distributed-training but I set gpus=2?thank you!

**Comment by ash11sh** [comment]
MMDetection implements distributed training and non-distributed training, which uses MMDistributedDataParallel and MMDataParallel respectively. 

you can know more about DistributedDataParallel and Data-parallel from [ here ](https://pytorch.org/docs/stable/nn.html#dataparallel-layers-multi-gpu-distributed)

**Comment by ZwwWayne** [comment]
This issue is closed because the question seems to be answered. Feel free to reopen it if you have any furtehr questions.
