### ISSUE TITLE
The order of numbers in mena=[123.675, 116.28, 103.53] is BGR or RGB？

### ISSUE THREAD

**Issue by GYee** [open-mmlab/mmdetection#1738]
I am using the cascade_mask_rcnn_r101_fpn_1x.py， there is a defination in this file that:
`img_norm_cfg  = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)`

I wanna using the mean and std calculated from my dataset, so I have know what is the order of numbers in mena=[123.675, 116.28, 103.53] ？ RGB or BGR?

**Comment by ash11sh** [comment]
from the [code ](https://github.com/open-mmlab/mmdetection/blob/f1c793926c269f1f4f4764d23e72e42a3d437935/mmdet/datasets/pipelines/transforms.py#L293) i think they are in the order of BGR

```python
line 299: to_rgb (bool): Whether to convert the image from BGR to RGB,
            default is true.

**Comment by GYee** [comment]
> from the [code ](https://github.com/open-mmlab/mmdetection/blob/f1c793926c269f1f4f4764d23e72e42a3d437935/mmdet/datasets/pipelines/transforms.py#L293) i think they are in the order of BGR
> 
> ```python
> line 299: to_rgb (bool): Whether to convert the image from BGR to RGB,
>             default is true.
> ```

maybe, but it can also be read on the contrary of what you understand

**Comment by hellock** [comment]
If `to_rgb` is set to True, the mean and std is ordered as RGB. You may refer to [`imnormalize`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/transforms/normalize.py#L6).

**Comment by RuoyuChen10** [comment]
> If `to_rgb` is set to True, the mean and std is ordered as RGB. You may refer to [`imnormalize`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/transforms/normalize.py#L6).

The original order is BGR? Right? If `to_rgb` is false.
