### ISSUE TITLE
How to add focal loss to Mask R-CNN?

### ISSUE THREAD

**Issue by jwwangchn** [open-mmlab/mmdetection#174]
I try to replace `weighted_cross_entropy` with `weighted_sigmoid_focal_loss` in the `bbox_head.py` to train Mask R-CNN with the focal loss, but I met some problems. I found the dimension of `labels` and `label_weights` need to be `(N, class_num)` in function `weighted_sigmoid_focal_loss`, but in function `weighted_cross_entropy`, `labels` and `label_weights` need to be `(N, )`. I want to know how to solve this problem.

**Comment by hellock** [comment]
You can use [`expand_binary_labels()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_target.py#L156) to expand the label from `(N, )` to `(N, class_num)`.

**Comment by jwwangchn** [comment]
Will try it, Thanks for your reply.

**Comment by JincanDeng** [comment]
@jwwangchn Have you add focal loss successfully? I want to use focal loss too.

**Comment by xxllp** [comment]
我发现加上focal loss 后损失反而爆炸了~~

**Comment by ZwwWayne** [comment]
This issue is closed because the issue seems to be answered. Feel free to reopen it if you have any further questions.
