### ISSUE TITLE
Why use valid bins in GHM Loss

### ISSUE THREAD

**Issue by Beowulf0731** [open-mmlab/mmdetection#1741]
I am trying to implement the GHM-C loss in my own model.
when calculating the approximate gradient density harmonizing parameter, the valid bins number is used to calculate the weights instead of using `self.bins`.
Is it reasonable to use the valid bins number? In the paper, the gradient density denotes the number of examples lying in the region centered at g with a length of edges. If the edge length is 0.5 (M = 2), and all the labels are 1, and all the gradient norm are centered in 0 to 0.5, then the gradient density should be N / 0.5, and the βi should be 0.5 . But if using the valid bins, the βi is still 1. 
```
        n = 0  # n valid bins
        for i in range(self.bins):
            inds = (g >= edges[i]) & (g < edges[i+1]) & valid
            num_in_bin = inds.sum().item()
            if num_in_bin > 0:
                if mmt > 0:
                    self.acc_sum[i] = mmt * self.acc_sum[i] \
                        + (1 - mmt) * num_in_bin
                    weights[inds] = tot / self.acc_sum[i]
                else:
                    weights[inds] = tot / num_in_bin
                n += 1
        if n > 0:
            weights = weights / n
```

**Comment by hellock** [comment]
Supposed that @libuyu can help.

**Comment by Beowulf0731** [comment]
@hellock Many thanks for your reply. I already find the answer in [https://github.com/libuyu/GHM_Detection/issues/13#issuecomment-472766868](url).
If I have any new question about this loss funtion, I may raise a new issue in that project.
Thanks again!
