### ISSUE TITLE
Settings of LibraRCNN

### ISSUE THREAD

**Issue by littletomatodonkey** [open-mmlab/mmdetection#1743]
想请教一个问题：在librarcnn中，如果使用默认配置，则负样本采样的3个区间分别是[-1,-0.33],[-0.33,0.33],[0.33,1.0]，这样的话，相当于第一个区间永远不会被采样？不知道我的理解是否有问题呢？
![image](https://user-images.githubusercontent.com/14270174/70048476-5d0cf800-1605-11ea-9edb-3ecfd81f909e.png)

**Comment by hellock** [comment]
Please use English or English&Chinese for issues.
