### ISSUE TITLE
Has anybody ever done model compression with mmdetection?

### ISSUE THREAD

**Issue by wen0618** [open-mmlab/mmdetection#1744]
Has anybody ever done model compression with mmdetection?Is it suitable for compression?
I am a complete beginner to model compression,but I like to use  mmdetion for detection study.
Hope for your suggestion,thanks.

**Comment by ZwwWayne** [comment]
Thanks for your attention and for choosing mmdet for the detection study.
Currently, we have not tried to use it with model compression, but we think you could try it.
Model compression is mainly about reducing the computation cost from models and could be related to any topics including detection. 
We welcome your PR.
