### ISSUE TITLE
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643

### ISSUE THREAD

**Issue by yangpc615** [open-mmlab/mmdetection#1745]
`        for jl in range(il, len(pts)):
            polyj = Polygon(pts[jl])
            try:
                inS = poly.intersection(polyj)
            except:
                print(poly, polyj)`

This code throws the following exception, I find that the dimension has been converted to 4x2 before, and why does it become 5x2 here.

`            quad_result = np.array(quad_results[0])
            keep = py_cpu_pnms(quad_result[:, :8].reshape((-1, 4, 2)),
                               quad_result[:, 8],
                               thresh=0.5)`

TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643
POLYGON ((331 31, 495 35, 158 24, 670 9, 331 31)) POLYGON ((497 44, 497 16, 629 16, 629 44, 497 44))
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643
POLYGON ((331 31, 495 35, 158 24, 670 9, 331 31)) POLYGON ((546 43, 546 15, 834 15, 834 43, 546 43))
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643
POLYGON ((331 31, 495 35, 158 24, 670 9, 331 31)) POLYGON ((591 14, 475 27, 226 23, 226 12, 591 14))
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643
POLYGON ((331 31, 495 35, 158 24, 670 9, 331 31)) POLYGON ((282 29, 282 6, 854 6, 854 29, 282 29))
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643
POLYGON ((331 31, 495 35, 158 24, 670 9, 331 31)) POLYGON ((626 34, 181 35, 181 19, 587 21, 626 34))
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643
POLYGON ((331 31, 495 35, 158 24, 670 9, 331 31)) POLYGON ((175 41, 175 9, 292 9, 292 41, 175 41))
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 344.8727452212151 30.099703849950643 at 344.8727452212151 30.099703849950643
POLYGON ((331 31, 495 35, 158 24, 670 9, 331 31)) POLYGON ((601 50, 601 17, 816 17, 816 50, 601 50))

**Comment by hellock** [comment]
Please follow the `Error report` issue template to provide useful information, so that other users or maintainers can help.

**Comment by Amberrferr** [comment]
have you solve this problem? could you please tell me about this?
