### ISSUE TITLE
How Can I Ensemble of Model Outputs?

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#1753]
My goal is to combine the output of more than one model to make a more effective object detection. So, I want to ensemble output more than one model that I have trained according to specific weights. How do I get model outputs such as [box_x, box_y, box_w, box_h, class]? Is that possible? I'm stuck and please help me. Thank you for your attention. Best regards...

**Comment by ZwwWayne** [comment]
You can first use [test.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py) to get the detection results from all the models, following the usage in the [GETTING_STARTED.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md). Then you need to write code by yourself to ensemble the detection results.

**Comment by zerok01** [comment]
Thanks for comments. I know how to train multiple models and get detection results. The point I can't do is draw the bbox according to the detection results ( -- show parameter). I don't know how to get the coordinate and class information used when drawing the bbox. Once I have this information, the ensemble code I will use is ready. I hope I can express myself well. Thank you

**Comment by ZwwWayne** [comment]
There is an `--out` option to get the coordinate and class information, I am not sure whether it helps you.

**Comment by kartikJ-9** [comment]
@zerok01 Any progress with your work? Even I am also looking for something like this.

**Comment by TheDarkKnight300** [comment]
Any updates on the model ensembling? @zerok01 It would be really nice if you could share the code you used for ensembling.
