### ISSUE TITLE
unexpected keyword bn_eval 

### ISSUE THREAD

**Issue by huangrichen11** [open-mmlab/mmdetection#1754]
when set 'bn_eval' and 'bn_frozen' in the 'faster_rcnn_r50_fpn_1x.py', got this error below:
```
xxxx/utils/registry.py Line 76 in build_from_cfg
__init__() got an unexpected keyword argument 'bn_eval'
```

**Comment by ZwwWayne** [comment]
Because there is no such an argument called `bn_eval`,  it is `norm_eval` as you can see from the [`resnet.py`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L349).
