### ISSUE TITLE
Model parallelism 

### ISSUE THREAD

**Issue by reygz** [open-mmlab/mmdetection#1755]
Hi, 

I have input images of 4k size, with batch size 1, GPU memory is not enough. Is there any way I can perform model parallelism over multiple GPUs.

**Comment by ZwwWayne** [comment]
There is no other way for model parallelism over multiple GPUs.
But you can try to use `checkpoint`. You can find its usage [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L352) and set it in the config of backbone.
