### ISSUE TITLE
unable to execute ':/usr/local/cuda-10.0/bin/bin/nvcc': No such file or directory error: command ':/usr/local/cuda-10.0/bin/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by lxlscut** [open-mmlab/mmdetection#1756]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
 - OS: [e.g., Ubuntu 16.04.6]
 - GCC [e.g., 5.4.0]
 - PyTorch version [e.g., 1.1.0]
- How you installed PyTorch [e.g., pip, conda, source]
- GPU model [e.g., 1080Ti, V100]
- CUDA and CUDNN version
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by lxlscut** [comment]
when i run the command "python setup.py develop" then this error occur????

**Comment by ZwwWayne** [comment]
Try `which nvcc` and see what happens.
This indicates that the nvcc is not at the place which is expected and has nothing to do with mmdet but your own CUDA environment.

**Comment by lxlscut** [comment]
![image](https://user-images.githubusercontent.com/44891891/70212929-2d7bfe00-1773-11ea-9c64-dfb4ca277011.png)
the location of nvcc is right

**Comment by ZwwWayne** [comment]
The correct path is `/usr/local/cuda-10.0/bin/nvcc`, but you try to execute `:/usr/local/cuda-10.0/bin:/usr/local/cuda-10.0/bin/nvcc`, is this path still right?

**Comment by lxlscut** [comment]
![image](https://user-images.githubusercontent.com/44891891/70222199-9f107800-1784-11ea-94e6-438f591bab7b.png)
now it looks like this~how could i correct the path

**Comment by lxlscut** [comment]
thanks i have solove the problems successfully~
the mistake is the cudahome in my ~/.bashrc ls 
"export CUDA_HOME="$CUDA_HOME:/usr/local/cuda-10.0""
（多了个冒号）and i change it to:
"export CUDA_HOME='/usr/local/cuda-10.0'"
then success~
