### ISSUE TITLE
about the size of Convolution's and Linear‘s parameters

### ISSUE THREAD

**Issue by ZhangYumi** [open-mmlab/mmdetection#1757]
Hello,everyone. I have an issue about the size of Convolution's and Linear's parameters. I try to use two convolution layers instead of the two linear layers behind RoI Pooling. The convolutions' kernel are 7x7x1024 and 1x1x1024。But both the used memory and the used GPU memory are about 4G more than using two linear layers. I check the number of their parameters, the weights’size of convolution layers are [1024,256,7,7] and [1024,1024,1,1],and the weights's size of linear layers are [1024,12544] and [1024,1024]。But 12544 = 7x7x256 ，which means thay have the same number of parameters. So I don't understand why using conv need much more memory than using linear.Anyone can help me ?

**Comment by ZwwWayne** [comment]
Having the same parameters does not mean their implementation cost the same GPU memory.
We cannot provide you a solid answer but this might because the conv use `im2col` operation for parallelism and thus cost more GPU memory during computation.
