### ISSUE TITLE
training model with single gpu

### ISSUE THREAD

**Issue by yelusaleng** [open-mmlab/mmdetection#1759]
hi, 
thanks for your work!
i met a serious problem.
you said i need to change the learning rate according to my gpu,
```shell
*Important*: The default learning rate in config files is for 8 GPUs and 2 img/gpu (batch size = 8*2 = 16). According to the Linear Scaling Rule, you need to set the learning rate proportional to the batch size if you use different GPUs or images per GPU, e.g., lr=0.01 for 4 GPUs * 2 img/gpu and lr=0.08 for 16 GPUs * 4 img/gpu.
```

according to your advice, i set the lr to 0.00125 since i have single gpu and i use the retinanet model (original lr = 0.01),
however, i get a worse result than the case with lr=0.01.

whether i should increase the number of epoch?

expecting your help!
@hellock

**Comment by ZwwWayne** [comment]
Hi @yelusaleng ,
It is reasonable that the performance drop after the setting is changed, especially when the LR/batch is decreased, so we are not able to do much help here.

**Comment by yelusaleng** [comment]
hi @ZwwWayne,
i get it, many thanks
