### ISSUE TITLE
Could I use label smoothing in mmdetection?

### ISSUE THREAD

**Issue by YilanWang** [open-mmlab/mmdetection#1762]
The question is as above. And does cls branch label smooth is helpful for task?

**Comment by ZwwWayne** [comment]
You could try and are welcomed for PR.

**Comment by milleniums** [comment]
> You could try and are welcomed for PR.
what is PR?i am newer in github. thanks

**Comment by milleniums** [comment]
> The question is as above. And does cls branch label smooth is helpful for task?

hello, have you implemented label smothing in  mmdetection?thanks

**Comment by wzgwy** [comment]
> > You could try and are welcomed for PR.
> > what is PR?i am newer in github. thanks



> > The question is as above. And does cls branch label smooth is helpful for task?
> 
> hello, have you implemented label smothing in mmdetection?thanks

您好，请问一下您，您有将label smooth 应用在mmdetection中吗，我用了mmdetection 的faster rcnn做分类，使用label smooth效果不好，请问您有遇到过这类情况吗？
