### ISSUE TITLE
mmdetection/mmdet/ops/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at11ATenOpTable11reportErrorEN3c1012TensorTypeIdE

### ISSUE THREAD

**Issue by lxlscut** [open-mmlab/mmdetection#1763]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
 - OS: [e.g., Ubuntu 16.04.6]
 - GCC [e.g., 5.4.0]
 - PyTorch version [e.g., 1.1.0]
- How you installed PyTorch [e.g., pip, conda, source]
- GPU model [e.g., 1080Ti, V100]
- CUDA and CUDNN version
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by lxlscut** [comment]
when i try to train,then this occur,my environment is cuda10.0 with pytorch 1.2.0

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/issues/1577

**Comment by ZwwWayne** [comment]
![image](https://user-images.githubusercontent.com/40779233/70286500-5d281600-1806-11ea-9b68-7db75f8639e2.png)
This is a template you need to fill, especially for the environment information related to this problem.

**Comment by lxlscut** [comment]
我把pytorch版本换成1.1.0没有报错了

**Comment by lxlscut** [comment]
多谢！！！

**Comment by luoqingyu** [comment]
How you solve it? i replace 1.10 but not work.

**Comment by lxlscut** [comment]
确定是一样的错误吗？？？我的还是cuda10.0
