### ISSUE TITLE
How to add IoULoss in other model except FCOS

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1764]
I changed the guided anchor faster-rcnn's config file from  loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))) to # loss_bbox=dict(type='IoULoss', loss_weight=1.0))) 
the error happened : RuntimeError: The size of tensor a(8) must match the size of tensor b(4) at nonsingleton dimension 1

**Comment by YilanWang** [comment]
You need to write the code of "targets", like those in FCOS.

**Comment by hellock** [comment]
#1436
