### ISSUE TITLE
Coco data needs to get mIoU,recall,precision of bounding box and mask

### ISSUE THREAD

**Issue by solauky** [open-mmlab/mmdetection#1766]
Coco data want to use voc_eval.py display style to evaluate, how to change the code? thank you

**Comment by solauky** [comment]
**Bounding box** : | AP50 | Precision | Recall | 
**Mask** : |  IoU | Precision | Recall

I need some evaluation indicators in this form.But coco_eval.py only gives  both AP and AR. How should I change it?

**Comment by hellock** [comment]
We adopt the official coco evaluation protocol, and if you want to reformat the output you may need to dive into the implementations.
