### ISSUE TITLE
MemoryError using slurm in mmdet

### ISSUE THREAD

**Issue by YilanWang** [open-mmlab/mmdetection#1767]
I ran my code using slurm. And the erroy is as floow:

`Traceback (most recent call last):  File "<string>", line 1, in <module>  File "/mnt/lustre/share/platform/env/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main    exitcode = _main(fd)  File "/mnt/lustre/share/platform/env/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 115, in _main    self = reduction.pickle.load(from_parent)
MemoryErrorTraceback (most recent call last):
  File "<string>", line 1, in <module>  File "/mnt/lustre/share/platform/env/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)  File "/mnt/lustre/share/platform/env/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)MemoryError`

the dataset is large(about 450G), I have the following guesses:
1. The maximum amount of memory that can be allocated exceeds the limit that slrum can allocate.
2. As shown in the error, 
> mp.set_start_method ('spawn') 

was called during distributed training, which resulted in some errors that I couldn't solve.
What is the possible cause. And how do I troubleshoot them? thanks a lot!

**Comment by ZwwWayne** [comment]
This seems to be the bug/limit of the machine, I think I met this problem before when the annotations or proposals files are large, you could change another machine/cluster or try to reduce the loading overload at the beginning.
