### ISSUE TITLE
Is it possible to extract the feature from any layer of a pre-trained detector?

### ISSUE THREAD

**Issue by goolhanrry** [open-mmlab/mmdetection#1768]
Thanks for your attention. Recently I'd like to use mmdetection to extract the feature for downstream tasks, and I'm confused about the pipeline.

Now I have a list of bbox coordinates (formed in XYXY) with respect to some images, how can I run a pre-trained detector (i.e. Faster-RCNN-R50-FPN) on these images, and crop the feature map (i.e. extract the 7x7 rois in the detector) according to the bbox coordinates? (It would be better to detect the bboxes directly and output their corresponding roi-pooled feature simultaneously)

I've tried to save the roi-pooled feature from RPN, and match them with the final outputs. However, since this is a two-stage detector, the actual bboxes might be refined after bounding box regression, which leads to the slightly mismatch between roi-pooled feature and bbox coordinates. Is there any approach to solve this problem?

**Comment by ZwwWayne** [comment]
A way to do that is to get the final detection results first, then make the box results as a proposal and treat the model as a fast rcnn, to get the RoI features cropped by the box and RoIAlign.

**Comment by goolhanrry** [comment]
Thank you so much for your reply!

**Comment by shridharmishra4** [comment]
@YLiuEric Hi, I am trying to do the same thing, can you please post an example extract the feature from bounding box images? I would be really grateful!
Thanks
