### ISSUE TITLE
How can I use NonLocal2D into the resnet backbone?

### ISSUE THREAD

**Issue by wen0618** [open-mmlab/mmdetection#1770]
I cannot found a config use nonlocal in their backbone?I want to try it with the resnet50.So what should I set in my config file or other file?Hooe for your help,thanks.

**Comment by ZwwWayne** [comment]
Currently, we do not support Non-Local Block, but it is easy to add it. It is quite similar to the global context block, so you can add it following the same way as in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L199.
