### ISSUE TITLE
What is the scale of the bboxes in the output of RPN?

### ISSUE THREAD

**Issue by goolhanrry** [open-mmlab/mmdetection#1774]
Thank you for your attention.

I would like to modify the output file from RPN and manually add some new proposals on my own. But I have no idea what is the scale of the bboxes, since the coordinates of the bboxes might change due to the pre-processing of images (i.e. padding or scaling), should I modify the [2000x5 tensors] in the proposal files manually to meet these transforms?

**Comment by ZwwWayne** [comment]
The model prediction has already been transformed to have the same scale as the original image thus they could be directly evaluated by the COCO API. When loading the bbox as a proposal file, it is modified to be consistent with the image pre-processing thus the model could be properly trained.

**Comment by goolhanrry** [comment]
Thank you so much!
