### ISSUE TITLE
How make my own dataset like coco_2017(with stuffmaps) #2

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1779]
I want to train the HTC,but it need the stuffmaps, how to get the stuffmaps dataset ,I already have the json annotations and images. Can you give me some suggestions.

**Comment by hellock** [comment]
You need to annotate the semantic maps, following [COCO-Stuff: Thing and Stuff Classes in Context](https://arxiv.org/abs/1612.03716).

**Comment by prateek-77** [comment]
Hi @yuyijie1995,

Were you able to create the stuffmaps for your custom dataset? If yes, then could you share how did you do it? Thanks!

**Comment by yuyijie1995** [comment]
https://codeleading.com/article/58021331085/;jsessionid=B3FBF6CD675E582E0998593373F2C949 You can refer to this website



At 2020-02-15 01:33:59, "Prateek Garg" <notifications@github.com> wrote:

Hi @yuyijie1995,

Were you able to create the stuffmaps for your custom dataset? If yes, then could you share how did you do it? Thanks!

**Comment by prateek-77** [comment]
Thanks!

**Comment by IAMShashankk** [comment]
@yuyijie1995 Hi, I used this code to generate the stuffmaps for my own custom dataset.
But when I am training I still face issue mentioned in #5608.
Could you please advise me on how to resolve this?

**Comment by Rock-L21** [comment]
> @yuyijie1995嗨，我使用此代码为我自己的自定义数据集生成了素材图。 但是当我训练时，我仍然面临#5608中提到的问题。 你能告诉我如何解决这个问题吗？

I have the same problem as you, how did you solve it.
