### ISSUE TITLE
coco_error_analysis.py

### ISSUE THREAD

**Issue by Charcy-yang** [open-mmlab/mmdetection#1780]
I would like to ask when running coco_error_analysis.py Each parameter instruction
#
def main():
    parser = ArgumentParser(description='COCO Error Analysis Tool')
    parser.add_argument('result', help='result file (json format) path')
    parser.add_argument('out_dir', help='dir to save analyze result images')
    parser.add_argument(
        '--ann',
        default='data/coco/annotations/instances_val2017.json',
        help='annotation file path')
    parser.add_argument(
        '--types', type=str, nargs='+', default=['bbox'], help='result types')
    args = parser.parse_args()
    analyze_results(args.result, args.ann, args.types, out_dir=args.out_dir)
#

python tools/coco_error_analysis.py  weight/faster_rcnn_r106/result/result_2.
pkl.bbox.json --out_dir /home/njaudata/anaconda3/envs/mmdetection/mmdetection/result --ann /home/njaudata/anaconda3/envs/mmdetection/mmdetection/data/coco/annotations/instances_val2017.json
usage: coco_error_analysis.py [-h] [--ann ANN] [--types TYPES [TYPES ...]]
                              result out_dir
coco_error_analysis.py: error: unrecognized arguments: --out_dir

**Comment by hellock** [comment]
Which argument is unclear to you? There have been instructions for each argument.
