### ISSUE TITLE
Why test only 1 images one gpus? Can I change the size  

### ISSUE THREAD

**Issue by zxyu1995** [open-mmlab/mmdetection#1783]
Why in test stage, only 1 imgs per gpus , how can i change the code to test multiple imgs , at same time

**Comment by ash11sh** [comment]
please look at the [code](https://github.com/open-mmlab/mmdetection/blob/b7894cbdcbe114e3e9efdd1a6a229419a552c807/mmdet/apis/inference.py#L63) here.

you can actually give a list of images or only one loaded image

**Comment by zxyu1995** [comment]
@ash11sh ， what i mean is batch inference

**Comment by hellock** [comment]
It is currently not supported, and will be added later.

**Comment by zxyu1995** [comment]
@hellock Thanks

**Comment by AlexFridman** [comment]
Hi, @hellock ! Any updates here?
