### ISSUE TITLE
How to calculate ap of one category with the cocoapi evaluation ? 

### ISSUE THREAD

**Issue by hitlxm** [open-mmlab/mmdetection#179]

**Comment by jwwangchn** [comment]
My method is using `tools/coco_eval.py` to read eval result file `RESULTS.pkl.json` which generated by `tools/test.py`. 

For looking the AP of each category, you need to set the `catIds` in class `COCOeval` in [coco_eval](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/coco_utils.py#L9) by adding the line `cocoEval.params.catIds = cat_ids` under `cocoEval.params.imgIds = img_ids`. `cat_ids` is a list contains category ids which you care about. 

For loop is necessary to see AP of each category in `tools/coco_eval.py`

**Comment by hitlxm** [comment]
yeah ! i kown that , but i try another way and i only save the result for that category by adding code in mmdet/core/evaluation/coco_utils.py det2json function : 
    for label in range(len(result)): 
            if not label== 2 
                  continue
because i have the json file which only includs that category . So it works .

**Comment by hitlxm** [comment]
Thanks for your reply!   yeah i kown that , But i try another way and only save the result for that category by adding code in mmdet/core/evaluation/coco_utils.py det2json function as follows:
           for label in range(len(result)):
               if not label==2:
                 continue
because i have the json file which only includs that category, So it works .
