### ISSUE TITLE
Training with my own data

### ISSUE THREAD

**Issue by jinho88** [open-mmlab/mmdetection#1792]
I make annotation pickle file for my data according to the /mmdet/datasets/loader/custom.py and I tried to train the retinanet_r101_fpn_1x with my own data(Kitti 2d object).

I trained the network during 150 epochs, but mAp is only 0.007~0.008.
Compared to the start, it is better, but a little bit..

If I set the lr bigger, sometimes loss goes to 'nan' and all APs are zero.

Please help me to train the network efficiently.
Do I just need to train more?

**Comment by ZwwWayne** [comment]
Since the mAP is so small, it might be some other problems rather than the training issue. You might need to check your data conversion process or other modifications you have done to the codebase.

**Comment by jinho88** [comment]
Thank you for answering!

I used CustomDataset  class in custom.py
in that file, 
    Annotation format:
    [
        {
            'filename': 'a.jpg',
            'width': 1280,
            'height': 720,
            'ann': {
                'bboxes': <np.ndarray> (n, 4),
                'labels': <np.ndarray> (n, ),
                'bboxes_ignore': <np.ndarray> (k, 4),
                'labels_ignore': <np.ndarray> (k, 4) (optional field)
            }
        },
        ...
    ]

in the bboxes (n,4),
I write down  x/ width, y/height, x_size/width, y_size/height

Is it right?

**Comment by hellock** [comment]
x1 (left), y1 (top), x2 (right), y2 (bottom)

**Comment by sizhky** [comment]
Please indicate this clearly in the documentation @hellock
