### ISSUE TITLE
loss_bbox is strange

### ISSUE THREAD

**Issue by masonwang96** [open-mmlab/mmdetection#1801]
I wan traing with config faster_rcnn_r101_fpn_1x.py. However, the loss_curve looks very strange and it seems that loss_bbox never drops. Besides, I found that rpn loss is very low as well and never decreases.
the lr is 0.0025 since I was using only one GPU.Other config is as default.

I plot the loss curve,You can see it as follows. Can anyone tell me why?
![Figure_2](https://user-images.githubusercontent.com/14297432/70773838-7e16db00-1db3-11ea-8dab-d6071f048a2a.png)

**Comment by ZwwWayne** [comment]
Hi @masonwang96 ,
What is your final mAP? The curve seems a little bit weird.
