### ISSUE TITLE
How can I train Faster R-CNN with ResnetC4

### ISSUE THREAD

**Issue by CindyHuang23** [open-mmlab/mmdetection#1807]
The  backbone configs of faster R-CNN is all the fpn. But I want to train Faster R-CNN with resent 101 C4 .How to modify the config file of Faster R-CNN？Thank you very much!

**Comment by hellock** [comment]
ResNet C4 is already supported and you can find config files with the `c4` in filenames.

**Comment by PVSemk** [comment]
@hellock 
As far as I'm concerned, you provide configs only for Faster R-CNN with C4 in Caffe style. How can I train it in pytorch?
I followed your tips in [#814](https://github.com/open-mmlab/mmdetection/issues/814) but faced a trouble with huge memory consumption of the model. With your FPN-config it took 3GB on GPU to train with batch size 1 while with modified caffe config with BS 1 it requires 6.3 GB. Is it normal?
I train custom dataset in COCO format, thx in advance

**Comment by hellock** [comment]
C4 models naturally consumes larger memory than FPN models, which is irrelevant to `pytorch` style or `caffe` style.

**Comment by PVSemk** [comment]
Understandable, but two times difference is too large, isn't it?

**Comment by hellock** [comment]
It's normal in my view. You can see the differences of these two models and estimate the params and memory.
