### ISSUE TITLE
Can not add my own data aug method

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1810]
I wrote  a data aug method in the transform like this 
`@PIPELINES.register_module
class RandomAddPatch(object):`
and modify the config file like this:
`train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='RandomAddPatch', nums_patch=2),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]`
but this error happened :
KeyError: 'RandomAddPatch is not in the pipeline registry'
Where else do I need to modify to implement this method?

**Comment by hellock** [comment]
You need to import RandomAddPatch somewhere, e.g., https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/__init__.py

**Comment by yuyijie1995** [comment]
Thanks a lot!
