### ISSUE TITLE
ImportError: cannot import name 'get_dist_info' from 'mmcv.runner.utils' 

### ISSUE THREAD

**Issue by XavierCHEN34** [open-mmlab/mmdetection#1811]
Traceback (most recent call last):
  File "tools/train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/core/evaluation/__init__.py", line 5, in <module>
    from .eval_hooks import (CocoDistEvalmAPHook, CocoDistEvalRecallHook,
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/core/evaluation/eval_hooks.py", line 13, in <module>
    from mmdet import datasets
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/datasets/__init__.py", line 6, in <module>
    from .loader import DistributedGroupSampler, GroupSampler, build_dataloader
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/datasets/loader/build_loader.py", line 8, in <module>
    from .sampler import DistributedGroupSampler, DistributedSampler, GroupSampler
  File "/home/cx/workspace/mmdet/mmdetection-master/mmdet/datasets/loader/sampler.py", line 6, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info' from 'mmcv.runner.utils' (/home/cx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/utils.py)

anyone could help me with this issue?

**Comment by ZwwWayne** [comment]
Hi @XavierCHEN34 ,
You might need to update your mmcv version and try again.

**Comment by hellock** [comment]
This error is caused by mmcv v0.2.15, you need to update mmdet to the latest version to use the latest mmcv.

**Comment by XavierCHEN34** [comment]
> This error is caused by mmcv v0.2.15, you need to update mmdet to the latest version to use the latest mmcv.

Thx, it works

**Comment by XGuider** [comment]
hi,how to get update mmcv ?    i hava a conda env.thnx so much. @XavierCHEN34 @ZwwWayne

**Comment by aimhabo** [comment]
@hellock what git from https://github.com/open-mmlab/mmcv is still 0.2.15
installing it and reinstalling mmdetection cannot avoid the ImportError

**Comment by yuyijie1995** [comment]
@XavierCHEN34 @ZwwWayne  how to update the mmcv to the latest version,I tried to use 'pip install --upgrade mmcv' but it is still the 0.2.15 and the error happened again.

**Comment by hellock** [comment]
@aimhabo @yuyijie1995 Please update **mmdetection**, not mmcv.

**Comment by cristianoKaKa** [comment]
> @aimhabo @yuyijie1995 Please update **mmdetection**, not mmcv.

I've already update mmdetection to the latest version(mmcv too), but still the same error... Any advice then?

**Comment by SystemErrorWang** [comment]
same problem here, i installed newest mmcv and mmdetection, and got the same error

**Comment by yuyijie1995** [comment]
I just updated the new mmdetection and it worked




| |
俞依杰
|
|
邮箱：13588280094@163.com
|

签名由 网易邮箱大师 定制

On 01/06/2020 21:34, SystemErrorWang wrote:

same problem here, i installed newest mmcv and mmdetection, and got the same error

**Comment by cristianoKaKa** [comment]
thx, I am reseting now



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yuyijie1995"; 
发送时间: 2020年1月6日(星期一) 晚上9:55
收件人: "open-mmlab/mmdetection";
抄送: "cristianoKaKa"<920906637@qq.com>;"Comment";
主题: Re: [open-mmlab/mmdetection] ImportError: cannot import name &#39;get_dist_info&#39; from &#39;mmcv.runner.utils&#39;  (#1811)



I just updated the new mmdetection and it worked
 
 
 
 
 | |
 俞依杰
 |
 |
 邮箱：13588280094@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 On 01/06/2020 21:34, SystemErrorWang wrote:
 
 same problem here, i installed newest mmcv and mmdetection, and got the same error
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by pengfeidip** [comment]
@aimhabo @yuyijie1995

How to update **mmdetection**?  Just delete mmdetection folder then git clone?

**Comment by aimhabo** [comment]
> @aimhabo @yuyijie1995
> 
> How to update **mmdetection**? Just delete mmdetection folder then git clone?

or even you can create a new conda environment. 
I have encountered it two times and rebuilt two things. I'm not sure where the problem is.

**Comment by XGuider** [comment]
pytorch 1.1.0+torchvision 0.2.2  is useful.not torchvision 0.3.0

**Comment by starlipernl** [comment]
What version of mmcv will not cause this error? I would prefer to install the older version rather than deal with updating my fork and rebuilding my environments.

**Comment by HViktorTsoi** [comment]
> @aimhabo @yuyijie1995
> 
> How to update **mmdetection**? Just delete mmdetection folder then git clone?

`git pull origin master`

**Comment by yuyijie1995** [comment]
Yes i git clone a new rep




| |
俞依杰
|
|
邮箱：13588280094@163.com
|

签名由 网易邮箱大师 定制

On 01/14/2020 15:26, HViktorTsoi wrote:

@aimhabo@yuyijie1995

How to update mmdetection? Just delete mmdetection folder then git clone?

git pull origin master

**Comment by TangDL** [comment]
mmdet==1.0rc0， torch==1.1.0,  torchvision==0.3.0,  mmcv==0.2.14,  cudn==10.2 is worked for me

**Comment by Dawn-LX** [comment]
I juse copy the original function from https://github.com/open-mmlab/mmcv/blob/600477624181ceea3a57e47e41bc953afa2a8810/mmcv/runner/dist_utils.py#L51

**Comment by liansheng** [comment]
> I just copy the original function from https://github.com/open-mmlab/mmcv/blob/600477624181ceea3a57e47e41bc953afa2a8810/mmcv/runner/dist_utils.py#L51
> 
> and it WORKS!!!!

why are you so excellent？

**Comment by Anirudh257** [comment]
https://github.com/JiangWenPL/multiperson/issues/4#issuecomment-652929895 also helped me.

**Comment by Dawn-LX** [comment]
> > I just copy the original function from https://github.com/open-mmlab/mmcv/blob/600477624181ceea3a57e47e41bc953afa2a8810/mmcv/runner/dist_utils.py#L51
> > and it WORKS!!!!
> 
> why are you so excellent？

Because I am from ZJU

**Comment by pc2005** [comment]
You are trying to import 'get_dist_info' from 'mmcv.runner.utils', which should be 'mmcv.runner.dist_utils'. Change it to:
`from mmcv.runner.dist_utils import get_dist_info`

**Comment by MaarufB** [comment]
Hi guys. What command should I use to update mmvc
