### ISSUE TITLE
RuntimeError: cuda runtime error (98)

### ISSUE THREAD

**Issue by kevinchow1993** [open-mmlab/mmdetection#1813]
RuntimeError: cuda runtime error (98)  unrecognized error code at mmdet/ops/roi_align/src/roi_align_kernel.cu:145 Uncaught exception. Entering post mortem 

Environment:
ubuntu 16.04
cuda 10.1
pytorch 1.2

**Comment by ZwwWayne** [comment]
Hi @kevinchow1993 ,
Please use the `Error Template`. https://github.com/open-mmlab/mmdetection/issues/229,  https://github.com/open-mmlab/mmdetection/issues/24.
