### ISSUE TITLE
How to get the current number of epoch rounds in the forward process

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1814]
I want to save the feature map during a certain round of training, but I don't know how to introduce the current number of epoch in the forward of mmdetection.

**Comment by ZwwWayne** [comment]
There might be two possible ways you could try:
1. As a temporary solution: you could add a counter in the detector, make it +1 after each iteration and use it to indicate the number of epoch or what you want to do after several iterations.
2. You could build a hook and register it for the runner, to implement a hook for mmdetection, you might need to read the doc and implementations in [mmcv](https://github.com/open-mmlab/mmcv/tree/master/mmcv/runner/hooks).

**Comment by yuyijie1995** [comment]
it worked ! thanks a lot.
