### ISSUE TITLE
RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered(Add new data aug method)

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1816]
**Describe the bug**
RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'

After adding my own data aug method, model can be trained normally several epochs,then this error happened.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/faster_rcnn_r50_fpn.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
yes the code added like this.
`@PIPELINES.register_module
class RandomAddPatch(object):
    def __init__(self, nums_patch=2,threshold=0.3,scale_range=(0.9,1.0,1.1,1.2,1.3,1.4,1.5)):
        self.nums_patch = nums_patch
        self.threshold=threshold
        self.scale=scale_range

    def addPatch(self,results):
        if results['gt_bboxes'].size>0:
            gt_bboxes=results['gt_bboxes'].tolist()
            gt_labels=results['gt_labels'].tolist()
            occluded=results['ann_info']['occluded'].tolist()
            img=results['img']
            image = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
            width=results['img_info']['width']
            height=results['img_info']['height']
            new_bboxes=[]
            for inx,bbox in enumerate(gt_bboxes):
                bbox_width,bbox_height=bbox[2]-bbox[0],bbox[3]-bbox[1]
                if bbox_width>30 or bbox_height>30 or bbox_width<5 or bbox_height<5:
                    continue
                for i in range(self.nums_patch):
                    if occluded[inx]>1:
                  
                        new_bbox_left = random.randint(0, width - bbox_width)
                        new_bbox_top = random.randint(0, height - bbox_height)
                        
                        b1 = int(bbox[1]+1)
                        b3 = int(bbox[3])
                        b0 = int(bbox[0]+1)
                        b2 = int(bbox[2])
                        bbox_width=b2-b0
                        bbox_height=b3-b1

                        bbox1 = [new_bbox_left, new_bbox_top, new_bbox_left + bbox_width,
                                 new_bbox_top + bbox_height]
                        ious=[self.bbox_iou(bbox1,bbox2) for bbox2 in gt_bboxes ]
                       
                        if max(ious)<=self.threshold:
                            gt_labels.append(gt_labels[inx])
                       
                        region = image.crop((b0, b1, b2 - 1, b3 - 1))
                        # region = region.resize((scaled_bbox_width, scaled_bbox_height), Image.ANTIALIAS)
                        image.paste(region, (new_bbox_left, new_bbox_top))
                     
                        new_bboxes.append(bbox1)
                    else:
                        new_bbox_left=random.randint(0,width-bbox_width)
                        new_bbox_top=random.randint(0,height-bbox_height)
                        b1 = int(bbox[1]+1)
                        b3 = int(bbox[3])
                        b0 = int(bbox[0]+1)
                        b2 = int(bbox[2])
                        bbox_width = b2 - b0
                        bbox_height = b3 - b1

                        scale_ratio = rd.sample(self.scale,1)[0]
                        scaled_bbox_width=int(bbox_width*scale_ratio)
                        scaled_bbox_height=int(bbox_height*scale_ratio)
                        bbox1 = [new_bbox_left, new_bbox_top, new_bbox_left + scaled_bbox_width ,
                                 new_bbox_top + scaled_bbox_height]
                        ious=[self.bbox_iou(bbox1,bbox2) for bbox2 in gt_bboxes ]

                        if max(ious)<=self.threshold:
                            gt_labels.append(gt_labels[inx])
                            crop = img[b1:b3, b0:b2, :]
                            # crop_float = crop.astype(np.float32)
                            # scaled_crop = mmcv.imresize(crop, (scaled_bbox_width, scaled_bbox_height))
                            # print(scaled_bbox_width,scaled_bbox_height)
                            # if scaled_bbox_height<5 or scaled_bbox_width<5:
                            ###PIL版本
                            region = image.crop((b0, b1, b2 - 1, b3 - 1))
                            region = region.resize((scaled_bbox_width, scaled_bbox_height), Image.ANTIALIAS)
                            image.paste(region, (new_bbox_left, new_bbox_top))
                            
                            new_bboxes.append(bbox1)
            gt_bboxes.extend(new_bboxes)
            img = cv2.cvtColor(np.asarray(image), cv2.COLOR_RGB2BGR)
            results['img']=img
            results['gt_bboxes']=np.array(gt_bboxes,dtype=np.float32)
            results['gt_labels']=np.array(gt_labels)
        return results`
3. What dataset did you use?
My own dataset but build it like coco.

**Error traceback**
If applicable, paste the error trackback here.
```
RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'

```

**Comment by ZwwWayne** [comment]
Hi @yuyijie1995 ,
It sometimes means your labels might have problems. The bug should be triggered by your modification but it does not happen in this part of the code. You might need to first locate the exact place the bug happened, e.g. from your log or the terminal output.

**Comment by SunNYNO1** [comment]
I can train on my data in faster_rcnn_r50_fpn.py，but not ssd300_voc.py, I meet this error:
`RuntimeError: merge_sort: failed to synchronize: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1565287025495/work/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f5083808e37 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x12e14 (0x7f5083a40e14 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x165bf (0x7f5083a445bf in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x74 (0x7f50837f3fa4 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x140fc34 (0x7f50868b8c34 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x31a4bf0 (0x7f508864dbf0 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x3756d12 (0x7f5088bffd12 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x7f5088bffdbf in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x37739b1 (0x7f5088c1c9b1 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #9: c10::TensorImpl::release_resources() + 0x20 (0x7f50837f3f50 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #10: <unknown function> + 0x1bb014 (0x7f50aece0014 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x40142b (0x7f50aef2642b in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x401461 (0x7f50aef26461 in /home/titan-ubuntu/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xf0 (0x7f50bdd19830 in /lib/x86_64-linux-gnu/libc.so.6)

已放弃 (核心已转储)
`
have anybody help me?, thank you very much

**Comment by ZwwWayne** [comment]
Hi @SunNYNO1 
Can you provide the python error traceback? Or at least please find which python code triggered this problem. Otherwise, we cannot help much.

**Comment by CoinCheung** [comment]
I met same error, it seems to be brought by gn+ws in the resnet50 backbone. I let backbone option `conv_cfg=None` leaving only gn, the problem no longer exists in my code. The combination of gn+ws in the neck and head does not have this problem.

**Comment by ZwwWayne** [comment]
Hi @CoinCheung ,
Do you also meet this error when you are training models on your own dataset?
