### ISSUE TITLE
KeyError: 'PAFPN is not in the neck registry'

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1817]
I wrote a new neck  stucture in the mmdetection and I had add it in the __init__.py like this
`from .bfp import BFP
from .fpn import FPN
from .hrfpn import HRFPN
from .PAFPN import PAFPN

__all__ = ['FPN', 'BFP', 'HRFPN','PAFPN']
`
and 
like this
`

@NECKS.register_module
class PAFPN(nn.Module):

`

**Comment by hellock** [comment]
I guess the running version is not the version that you modified.

**Comment by yuyijie1995** [comment]
Thanks ,I solved it .

**Comment by ZYK266139** [comment]
> Thanks ,I solved it .
Hello，I wonder how you solved the problem？
