### ISSUE TITLE
Is there restriction in custom dataset image size?

### ISSUE THREAD

**Issue by whikwon** [open-mmlab/mmdetection#182]
Is there restriction in custom dataset image size?

Can I use any size of image for custom dataset?

**Comment by hellock** [comment]
The only restriction is your GPU memory. Of course you may need to choose hyper parameters according to the image size.

**Comment by sunpeng981712364** [comment]
> The only restriction is your GPU memory. Of course you may need to choose hyper parameters according to the image size.

hi, hellock,  can you give me some ideas about hyper parameteres related to image size?
