### ISSUE TITLE
questions about recall and precision

### ISSUE THREAD

**Issue by wytcsuch** [open-mmlab/mmdetection#1821]
I trained two models. One is libra_faster_rcnn_r50_fpn_1x.py, and got the following training results
+---------------+-------+--------+--------+-----------+-------+
| class                  | gts      | dets      | recall     | precision    | ap       |
+---------------+-------+--------+--------+-----------+-------+
| plane                | 3851   | 7338     | 0.959    | 0.503        | 0.939 |
| ship                  | 20434 | 40789   | 0.964    | 0.483        | 0.943 |
| small-vehicle     | 63783 | 152882 | 0.836    | 0.349        | 0.708 |
| large-vehicle     | 9594   | 35652   | 0.946     | 0.254       | 0.834 |
| storage-tank    | 4254   | 12037   | 0.898     | 0.317        | 0.826 |
+---------------+-------+--------+--------+-----------+-------+
| mAP                 |             |             |              |                  | 0.850 |
+---------------+-------+--------+--------+-----------+-------+

Another model is retinanet_free_anchor_r50_fpn_1x.py,

+---------------+-------+--------+--------+-----------+-------+
| class                 | gts       | dets       | recall    | precision     | ap      |
+---------------+-------+--------+--------+-----------+-------+
| plane                | 3851   | 173739 | 0.973  | 0.022     | 0.899 |
| ship                  | 20434 | 388241 | 0.966  | 0.051     | 0.876 |
| small-vehicle     | 63783 | 891158 | 0.761  | 0.054     | 0.586 |
| large-vehicle     | 9594   | 472861 | 0.949  | 0.019     | 0.693 |
| storage-tank     | 4254   | 208354 | 0.841  | 0.017     | 0.730 |
+---------------+-------+--------+--------+-----------+-------+
| mAP                 |            |               |            |                  | 0.757 |
+---------------+-------+--------+--------+-----------+-------+

I understand that dets represents the number of targets detected by the model. The more dets, the higher recall, but the lower precision. Obviously, the det of model 1 is much less than that of model 2. Why the precision of model 2 is higher？

**Comment by hellock** [comment]
The precision here is not "average precision", it is just the precision of all detected bboxes, which should be rather low and is not useful.

**Comment by hellock** [comment]
#506

**Comment by CRmost** [comment]
> 
> 
> The precision here is not "average precision", it is just the precision of all detected bboxes, which should be rather low and is not useful.

Then you said the precision is not useful, and we use what to judge a good model in the mmdetection??

**Comment by hsp2454** [comment]
Did you solve this problem?
