### ISSUE TITLE
MODEL accelerating .TensorRT

### ISSUE THREAD

**Issue by neil5410** [open-mmlab/mmdetection#1822]
did anyone try to accelerate the mmd models ， transform it into tensorrt fp 32 or 16 or int8 ?
if you've done related work can we discuss some problems about it?

**Comment by loveunk** [comment]
An official FP16 demo:
[https://github.com/open-mmlab/mmdetection/blob/f96e57d6ee57a3c53833c53bcbb34a06d460c07e/configs/fp16/faster_rcnn_r50_fpn_fp16_1x.py#L2](https://github.com/open-mmlab/mmdetection/blob/f96e57d6ee57a3c53833c53bcbb34a06d460c07e/configs/fp16/faster_rcnn_r50_fpn_fp16_1x.py#L2)

**Comment by RunningLeon** [comment]
You can convert your model from PyTorch to ONNX and then convert ONNX to TensorRT engine. There would be some ops that are not supported in TensorRT. You may have to write your custom TensorRT plugin. BTW, welcome to contribute your custom TensorRT plugin to `mmcv`.
