### ISSUE TITLE
when I use multiprocessing the speed drop sharply

### ISSUE THREAD

**Issue by ioir123ju** [open-mmlab/mmdetection#1824]
model: **libra_rcnn, repoint**
**use multiprocessing:** 
```

 import multiprocessing
 gpu_pool = multiprocessing.Pool(2)
 gpu_pool.apply_async(test_speed_proc)
gpu_pool.close()
gpu_pool.join()
```
**FPS:6.649**

**do not use multiprocessing:** 
```
test_speed_proc()
```
**FPS:10.085**

why??

**inference function:**
```
def test_speed_proc():
    os.environ["CUDA_VISIBLE_DEVICES"] = "1"
    cfg = mmcv.Config.fromfile('config/voc_reppoints_moment_r50_fpn_2x_mt.py')
    cfg.model.pretrained = None
    model = init_detector(cfg, 'model/libra_person.pth', device='cuda:0')

    dataset_dir = "data/mask/VOCdevkit/VOC2007/JPEGImages"
    image_ids = next(os.walk(dataset_dir))[2]

    url = os.path.join(dataset_dir, image_ids[0])
    test_image = cv2.imread(url)
    test_image = cv2.resize(test_image, (0, 0), fx=setting.scale, fy=setting.scale)

    start = time.time()
    for i in range(200):
            result = inference_detector(model, test_image)
            print("\r" + "{}".format(i), end="", flush=True)
    elapsed = (time.time() - start)
    print('\nNUM:{}, TIME USE:{}, SPEED: {}'.format(200, elapsed, 200 / elapsed))

```

**Comment by hellock** [comment]
I don't think you correctly used multiprocessing.

**Comment by ioir123ju** [comment]
> I don't think you correctly used multiprocessing.
Sorry, I can't understand. I'm just use multiprocessing.Pool.apply_async().
Nothing else has changed

**Comment by hellock** [comment]
You just repeated the task twice instead of sharing tasks between two processes. You may learn more knowledge about multiprocessing.
BTW, applying multiprocessing to GPU tasks and CPU tasks is somewhat different, which is nontrivial. If you are looking for a solution for speedup, https://github.com/open-mmlab/mmdetection/pull/1647 provides an async interface and may be helpful.

**Comment by ioir123ju** [comment]
> You just repeated the task twice instead of sharing tasks between two processes. You may learn more knowledge about multiprocessing.
> BTW, applying multiprocessing to GPU tasks and CPU tasks is somewhat different, which is nontrivial. If you are looking for a solution for speedup, #1647 provides an async interface and may be helpful.

I don't think you understand me.I don't want to run two programs at once. 
I only use multiprocessing interface to start one test_speed_proc(), not two test_speed_proc().
So there should be no performance loss, but executing one test_speed_proc() with multiprocessing is 4 seconds slower than running it with no more processes. it is unreasonable

**Comment by hellock** [comment]
It's normal that wrapping a method with the multiprocessing interface is slower than simply running the method, since it requires additional costs.
