### ISSUE TITLE
Why use bias_init_with_prob in fcos/foveabox/reppoints？

### ISSUE THREAD

**Issue by zhoulukuan** [open-mmlab/mmdetection#1825]
In fcos/foveabox/reppoints, conv for cls in the final always use `bias_cls = bias_init_with_prob(0.01)` for initialization.  Is it related to their use of Focal loss? If the numbers of positive and negative samples  balanced after sampling, is this not necessary?
```
def bias_init_with_prob(prior_prob):
    """ initialize conv/fc bias value according to giving probablity"""
    bias_init = float(-np.log((1 - prior_prob) / prior_prob))
    return bias_init
```

**Comment by hellock** [comment]
It's a typical convention for initializing weights when adopting the focal loss. You may refer to [Focal Loss for Dense Object Detection](https://arxiv.org/abs/1708.02002) for detailed reasons.
