### ISSUE TITLE
ImportError: /opt/conda/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev

### ISSUE THREAD

**Issue by guobinli** [open-mmlab/mmdetection#1828]
i face this issue during training

running environment:
pytorch1.3.1 cuda10.1  gcc7.*  ubuntu16.04

i wonder that how to solve this issue?

**Comment by hellock** [comment]
Please follow the `Error report` issue template and also run the `collect_env` tool.
