### ISSUE TITLE
Where is the code of paper: Side-Aware Boundary Localization for More Precise Object Detection (SABL)?

### ISSUE THREAD

**Issue by black12357** [open-mmlab/mmdetection#1829]
I already read and understand the paper: Side-Aware Boundary Localization for More Precise Object Detection and your work is very good. So, I need the location of this code to reproduce. I'm looking forward from you. Thank you for your work!

**Comment by hellock** [comment]
To be released.

**Comment by xuanthuyvo** [comment]
Thank you for your response. I'm waiting for publishing your code.

**Comment by brmarkus** [comment]
"need the location of this paper" - do you mean an URL...? A link where to find the paper?
E.g. here:
"https://deepai.org/publication/side-aware-boundary-localization-for-more-precise-object-detection" pointing to "https://arxiv.org/pdf/1912.04260v1.pdf"

**Comment by xuanthuyvo** [comment]
@brmarkus No. I mean the location of SABL's code.
