### ISSUE TITLE
undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_4E

### ISSUE THREAD

**Issue by DominicChai** [open-mmlab/mmdetection#183]
Hi，I have looked into issue #48 but still have the following error while running list_train.sh or test.py

"ImportError: /python3.5/site-packages/mmdet/ops/roi_align/roi_align_cuda.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_4E"

my environment:
python 3.5
pytorch 0.4.1
and I finished all the setup in INSTALL.md

Can you please provide more details on how to check the compiling environment and runtime environment or other suggestions of dealing with this problems? or maybe illustrate the reason why this error occurs?

I used conda to set up a virtual environment and also set up the same local environment in my own computer(Ubuntu), but encountered same issue either way.

Thank you

**Comment by ZwwWayne** [comment]
This issue is closed, feel free to reopen it if you have any further questions.
