### ISSUE TITLE
Poor results after training for 2500 epochs. 

### ISSUE THREAD

**Issue by beversnor** [open-mmlab/mmdetection#1835]
I am currentrly working on a project where I am trying to detect rather small objects in large images using HTC ResNet-101. The original images have a height and width of  2100 x 1500px and the objects that i am trying to detect have sizes ranging from  3x3px to 20x20px. 
I already read the issue regarding problems with detecting small object therefore I split the original image in 12 smaller images (523x518px) and trained using that as a batchsize. 

To check if this showed any results I trained a small dataset (train: 36, val: 12, test: 12) on my laptop (NVIDIA GTX 1060 6gb). After this showed promising results, I trained a bigger dataset(train:1200, val: 300, test: 300) om a VM (NVIDIA Tesla V100 16gb). Both training sessions used the same config file: [htc.txt](https://github.com/open-mmlab/mmdetection/files/3983363/htc.txt)
This however showed poor results compared to the test run. 
Both of the training sessions were trained for the same amount of epochs (2500) and ended at around the same losses.

Testing the results trained using the latest `pth` file from the VM only 5 images of the 300 in my test set showed masks for what I consider the small objects. However running the same test set throught the latest epoch of the training on my laptop a total of 26 images contained masks. The results of the VM are as I mentioned very poor in comparison to what I trained on my laptop. 

What I am currently wondering is why there is a large gap between detection on `pth` files from my laptop and the VM. Also, I am looking for some explanation regarding the trajectory of the loss graphs. 

[losses.pdf (Laptop)](https://github.com/open-mmlab/mmdetection/files/3983256/losses.pdf)
[losses.pdf (VM)](https://github.com/open-mmlab/mmdetection/files/3983257/losses.pdf)

**Comment by hellock** [comment]
We don't help to solve practical problems and tune the results on custom datasets, which is unrelated to this codebase and more about your knowledge of machine learning and computer vision. If you have specific questions related to the usage of mmdetection, you can raise an issue and we can help.
