### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by gaussiangit** [open-mmlab/mmdetection#1837]
So if I used pretrained model from model zoo with my custom dataset in coco format.
Should I just use "load_from" in the config to fine tune and just adjust number of classes in the config ? 
Is there anything else I should take care of ? 
@hellock

**Comment by gaussiangit** [comment]
So if I do what I have mentioned, does it consider as fine tuning. 
I get mismatch error warning obviously because of the coco trained model:
these keys have mismatched shape:
+--------------------------------+----------------------------+-----------------------------+
| key                            | expected shape             | loaded shape                |
+--------------------------------+----------------------------+-----------------------------+
| bbox_head.0.fc_cls.weight      | torch.Size([9, 1024])      | torch.Size([81, 1024])      |
| bbox_head.0.fc_cls.bias        | torch.Size([9])            | torch.Size([81])            |
| bbox_head.1.fc_cls.weight      | torch.Size([9, 1024])      | torch.Size([81, 1024])      |
| bbox_head.1.fc_cls.bias        | torch.Size([9])            | torch.Size([81])            |
| bbox_head.2.fc_cls.weight      | torch.Size([9, 1024])      | torch.Size([81, 1024])      |
| bbox_head.2.fc_cls.bias        | torch.Size([9])            | torch.Size([81])            |
| mask_head.0.conv_logits.weight | torch.Size([9, 256, 1, 1]) | torch.Size([81, 256, 1, 1]) |
| mask_head.0.conv_logits.bias   | torch.Size([9])            | torch.Size([81])            |
| mask_head.1.conv_logits.weight | torch.Size([9, 256, 1, 1]) | torch.Size([81, 256, 1, 1]) |
| mask_head.1.conv_logits.bias   | torch.Size([9])            | torch.Size([81])            |
| mask_head.2.conv_logits.weight | torch.Size([9, 256, 1, 1]) | torch.Size([81, 256, 1, 1]) |
| mask_head.2.conv_logits.bias   | torch.Size([9])            | torch.Size([81])            |
+--------------------------------+----------------------------+-----------------------------+

**Comment by StringBottle** [comment]
I think you can refer to this post. #743
