### ISSUE TITLE
which network can get the highest mAP for vehicle detection on UA_DETRAC/KITTI/BDD?

### ISSUE THREAD

**Issue by sisrfeng** [open-mmlab/mmdetection#1841]
Do I need to try by myself one by one? I want to stand on the shoulders of giants.....

**Comment by hellock** [comment]
There is no answer to this question. It depends on your datasets and using senarios. You may refer to the [MODEL ZOO](https://github.com/open-mmlab/mmdetection/blob/master/docs/MODEL_ZOO.md) on COCO dataset.
