### ISSUE TITLE
mrcnn mask edge loss

### ISSUE THREAD

**Issue by alaayadi** [open-mmlab/mmdetection#1843]
To further improve the segmentation of different objects, can we implement a mrcnn mask edge loss similar to this implementation in Keras:
https://github.com/zimmerrol/mask-rcnn-edge-agreement-loss/blob/f764a8951235f0c9266a412282b60548ac0c90a0/mrcnn/model.py#L1217

**Comment by hellock** [comment]
Yes you can try it.

**Comment by alaayadi** [comment]
@hellock any help with the implementation?

**Comment by hellock** [comment]
We have to say that we cannot help with it.
