### ISSUE TITLE
I think this annotation may be wrong

### ISSUE THREAD

**Issue by CuriousCat-7** [open-mmlab/mmdetection#1858]
"""
         Calls either forward_train or forward_test depending on whether
         return_loss=True. Note this setting will change the expected inputs.
         When `return_loss=False`, img and img_meta are single-nested (i.e.
         Tensor and List[dict]), and when `resturn_loss=True`, img and img_meta
         should be double nested (i.e.  List[Tensor], List[List[dict]]), with
         the outer list indicating test time augmentations.
         """

I think you just write the opposite. It should be:

When return_loss=**True**,  img and img_meta are single-nested .

 when resturn_loss=**False**, img and img_meta should be double nested

Yours

**Comment by hellock** [comment]
Yes you are right, a PR is welcome.
