### ISSUE TITLE
[enhancement] Could you add pointers to your AAAI paper that describes the anchoring scheme ?

### ISSUE THREAD

**Issue by jeandut** [open-mmlab/mmdetection#186]
The sparse anchoring scheme used in place of RPN in your codebase is supposedly described in a AAAI paper. This repository would surely beneficiate from pointers to the papers supporting these results (or their arXiv versions at least). And would allow one to dive in the code more easily. Thank you again.

**Comment by hellock** [comment]
We will release the paper on arxiv soon. Code will also be available later on.
