### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'img_scale'

### ISSUE THREAD

**Issue by wangcn99** [open-mmlab/mmdetection#1860]
### Here is my config file:
# model settings
model = dict(
    type='FasterRCNN',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=dict(
        type='SharedFCBBoxHead',
        num_fcs=2,
        in_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=81,
        target_means=[0., 0., 0., 0.],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        reg_class_agnostic=False,
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)
)
# dataset settings
dataset_type = 'VOCDataset'
data_root = 'data/VOCdevkit/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',  # to avoid reloading datasets frequently
        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                data_root + 'VOC2007/ImageSets/Main/train.txt',#train.txt
            ],
            img_prefix=[data_root + 'VOC2007/'],
            img_scale=(1200, 1120),
            img_norm_cfg=img_norm_cfg,
            size_divisor=32,
            flip_ratio=0.5,
            with_mask=False,
            with_crowd=False,
            with_label=True)),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/trainval.txt',
        img_prefix=data_root + 'VOC2007/',
        img_scale=(1200, 1120),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_crowd=False,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        img_scale=(1200, 1120),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_crowd=False,
        with_label=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 12
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/faster_rcnn_r50_fpn_1x'
load_from = None
resume_from = None
workflow = [('train', 1)]
 
### Here is my error 

Traceback (most recent call last):
  File "tools/train.py", line 110, in <module>
    main()
  File "tools/train.py", line 88, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/fulei/mmdetection/mmdet/datasets/builder.py", line 35, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/home/fulei/mmdetection/mmdet/datasets/builder.py", line 37, in build_dataset
    dataset = _concat_dataset(cfg, default_args)
  File "/home/fulei/mmdetection/mmdet/datasets/builder.py", line 25, in _concat_dataset
    datasets.append(build_dataset(data_cfg, default_args))
  File "/home/fulei/mmdetection/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/fulei/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/home/fulei/mmdetection/mmdet/datasets/voc.py", line 11, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/home/fulei/mmdetection/mmdet/datasets/xml_style.py", line 15, in __init__
    super(XMLDataset, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'img_scale'

**Comment by zzw0225** [comment]
i got the same error.have you solved it?

**Comment by liugl7** [comment]
i got the same error.have you solved it?

**Comment by wangzl2011** [comment]
i got the same error.have you solved it?

**Comment by 422301949** [comment]
i got the same error.have you solved it?

**Comment by m-d-hasan** [comment]
I got the same error. have you solved it?
.

**Comment by RiyazAina-DeepML** [comment]
i got the following error,
got an unexpected keyword argument 'bbox_roi_extractor'

**Comment by elk-april** [comment]
> i got the following error,
> got an unexpected keyword argument 'bbox_roi_extractor'

I have solved this issue. After you clone the latest version, you have to install mmdetection under your mmdetceion directory:
python setup.py develop
right answer from @OPzealot

**Comment by TAOSHss** [comment]
TypeError: __init__() got an unexpected keyword argument 'train_cfg'

**Comment by 15988817140** [comment]
> TypeError: **init**() got an unexpected keyword argument 'train_cfg'

I have a same problem,have you solved it?

**Comment by chentp-1183** [comment]
> 

me too!

**Comment by willnotapostle** [comment]
I got the following error,
got an unexpected keyword argument 'bbox_head'

**Comment by bryanbocao** [comment]
We can trace down the __init__() and check which argument names were changed compared to previous versions.
