### ISSUE TITLE
Changing channel of input data

### ISSUE THREAD

**Issue by yanlongbinluck** [open-mmlab/mmdetection#1861]
Thank you for your time. sorry, I am new to MMdetection. My question is very simple. 
I want to do some experiments of multi-channel input.
Example:
The standard algorithm need 3 channel input, I want to input 6 channel to backbone, such as simply copying the data.
I have changed the input channel of backbone from 3 to 6, and  changed  the `__getitem__` function in mmdet/datasets/custom.py as follow:
```
# TODO
def my_function_from_3channel_to_6channel(input):
    ...
    return out

def __getitem__(self, idx):
    if self.test_mode:
        data = self.prepare_test_img(idx)

        # TODO
        data['img'] = my_function_from_3channel_to_6channel(data['img'].data)
        return data
    while True:
        data = self.prepare_train_img(idx)
        if data is None:
            idx = self._rand_another(idx)
            continue

        # TODO
        data['img'] = my_function_from_3channel_to_6channel(data['img'].data)
        return data
```
Is my method is right?  or where should I add this change? I want to do it with all datasets and algorithms.
There no error in some algorithms, but a error about mismatch size of input data with FCOS, if the batchsize=1, it is ok; when batchsize greater than 1, error.
Thank you very much~

**Comment by hellock** [comment]
You can do it like above for fast prototyping. A more elegant way is to add a new pipeline module. https://mmdetection.readthedocs.io/en/latest/TECHNICAL_DETAILS.html#data-pipeline

**Comment by yanlongbinluck** [comment]
Thanks

**Comment by bnumaomei** [comment]
@yanlongbinluck Hi～ I also want to change the input image channel, could you please tell me how to modify the code to handle this problem?

**Comment by yanlongbinluck** [comment]
The answer above is already clear. Longbin YAN 邮箱：yanlongbinluck@gmail.com 签名由 网易邮箱大师 定制 On 03/26/2020 15:23, bnumaomei wrote: @yanlongbinluck Hi～ I also want to change the input image channel, could you please tell me how to modify the code to handle this problem? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lhgiang149** [comment]
@yanlongbinluck @hellock can you fix the document's link? It's broken
