### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by xiuruisi** [open-mmlab/mmdetection#1868]
Hi, I want to use ROIAlign and do a test, but when I compile the ROIAlign and test, something went wrong.

Traceback (most recent call last):
  File "/home/cs512/jixie/mjw/ROIaligntest/ttest.py", line 2, in <module>
    from roi_align import RoIAlign      # RoIAlign module
  File "/home/cs512/jixie/mjw/ROIaligntest/roi_align.py", line 6, in <module>
    from . import roi_align_cuda
ImportError: attempted relative import with no known parent package

g++ version : 4.9
pytorch version : 1.2

**Comment by hellock** [comment]
It is a package. If you take out the folder and use it in other projects, you may need to place it to a proper location.
