### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable,  in mmdet/models/anchor_heads/rpn_head.py

### ISSUE THREAD

**Issue by Helicopt** [open-mmlab/mmdetection#1871]
Error raised:

  File "~/.local/lib/python3.6/site-packages/mmdet-1.0rc1+cd0d37c-py3.6-linux-x86_64.egg/mmdet/models/anchor_heads/rpn_head.py", line 53, in loss
    loss_rpn_cls=losses['loss_cls'], loss_rpn_bbox=losses['loss_bbox'])
TypeError: 'NoneType' object is not subscriptable

traceback:
- cls_reg_targets is None in mmdet/models/anchor_heads/anchor_head.py#L178
- expression “any([labels is None for labels in all_labels])” is True in mmdet/core/anchor/anchor_target.py#L65
- condition "if not inside_flags.any():" satisfied in mmdet/core/anchor/anchor_target.py#L106
- all valid flags positions exceed boundary in mmdet/core/anchor/anchor_target.py#L168

I guess:  all positions/locations are not valid,  or exceed image boundaries. 
So what happens? Is there something wrong with the input data?  Is the input image too small?

The pipelines are as below:

104 train_pipeline = [
105     dict(type='LoadImageFromFile'),
106     dict(type='LoadAnnotations', with_bbox=True),
107     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
108     dict(type='RandomFlip', flip_ratio=0.5),
109     dict(type='Normalize', **img_norm_cfg),
110     dict(type='Pad', size_divisor=32),
111     dict(type='DefaultFormatBundle'),
112     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
113 ]

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by Helicopt** [comment]
Can you show me a reference link for correct Error report issue template?

**Comment by hellock** [comment]
When you click the "New issue" button to raise an issue, you will see 3 options and the first one is `Error report`.

**Comment by Helicopt** [comment]
> When you click the "New issue" button to raise an issue, you will see 3 options and the first one is `Error report`.

Thanks, I create a new issue and we can turn to that page.
Duplicate of #1882
