### ISSUE TITLE
Some quention for data augment

### ISSUE THREAD

**Issue by CindyHuang23** [open-mmlab/mmdetection#1874]
Does mmdetection implement data augmentation for target detection? If not, how to achieve data enhancement for target detection, such as horizontal flip or vertical flip?Or other data enhancement methods?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L182

**Comment by CindyHuang23** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L182

Thank you! But  how to modify the config file if I want to train with data augment? I use the config file-- "cascade_rcnn_x101_64*4d_fpn_1x.py" .

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/configs/cascade_rcnn_x101_64x4d_fpn_1x.py#L170
