### ISSUE TITLE
a question about random seed

### ISSUE THREAD

**Issue by bxhandhxb** [open-mmlab/mmdetection#1875]
Hi
I have a question about the function set_random_seed() in env.py.
The random.seed(seed) and np.random.seed(seed) only take effect once, don't they??
So how does the function set_random_seed() affect the whole  codebase ?
If I fix the random seed in env.py, does the RandomFlip only have one direction??

**Comment by hellock** [comment]
Yes they are only set once, and only needed to be set once.

https://en.wikipedia.org/wiki/Random_seed

**Comment by bxhandhxb** [comment]
thx very much~
