### ISSUE TITLE
when i use the "python setup.py develop" i met the problems

### ISSUE THREAD

**Issue by demondaimeng** [open-mmlab/mmdetection#1876]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "setup.py", line 171, in <module>
    sources=['src/compiling_info.cpp']),
  File "setup.py", line 101, in make_cuda_ext
    raise EnvironmentError('CUDA is required to compile MMDetection!')
OSError: CUDA is required to compile MMDetection!
how can i solve this problem?

**Comment by hellock** [comment]
You did not install CUDA.

**Comment by abiramipriya** [comment]
> You did not install CUDA.

" i have installed CUDA after also, I got the same issue..

**Comment by cauivy** [comment]
> > You did not install CUDA.
> 
> " i have installed CUDA after also, I got the same issue..
@hellock @demondaimeng I got the same problem, did you guys solve the problem? Thanks in advance!

**Comment by JulianJuaner** [comment]
same problem

**Comment by SystemErrorWang** [comment]
same problem here，i can compile with torch1.2.0, but when i update torch to 1.3.0,  i got this error:
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "setup.py", line 171, in <module>
    sources=['src/compiling_info.cpp']),
  File "setup.py", line 101, in make_cuda_ext
    raise EnvironmentError('CUDA is required to compile MMDetection!')
OSError: CUDA is required to compile MMDetection!
```

**Comment by PanJianning** [comment]
> same problem here，i can compile with torch1.2.0, but when i update torch to 1.3.0, i got this error:
> 
> ```
> No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
> Traceback (most recent call last):
>   File "setup.py", line 171, in <module>
>     sources=['src/compiling_info.cpp']),
>   File "setup.py", line 101, in make_cuda_ext
>     raise EnvironmentError('CUDA is required to compile MMDetection!')
> OSError: CUDA is required to compile MMDetection!
> ```

Maybe you should check whether pytorch is installed correctly.
```python
import torch
print(torch.cuda.is_available())
```

**Comment by SystemErrorWang** [comment]
@PanJianning yes, I found it was pytorch installation problem. I then switched cuda version and successfully install pytorch 1.3.0, but met following problem when compiling mmdetection:
```
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
```
