### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by 1428679766** [open-mmlab/mmdetection#1877]
RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/ATen/native/cuda/Loops.cuh:102)
---------------------------------------------------------------------------------------------------------------------
I got this error when I tried to run demo / inference_demo.ipynb with jupyter
The configuration environment is:
ubuntu: 16.04 lts
gtx 1060
cuda: 10.0.130
Nvidia driver version: 418.56
pytorch 1.3.1
Can someone tell me how to solve this problem?

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
