### ISSUE TITLE
raise EnvironmentError('CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by henbucuoshanghai** [open-mmlab/mmdetection#1878]
it must be cuda9.0  ????cuda 10 is wrong???

**Comment by hellock** [comment]
CUDA 10 should work well and we have used it for a long time.

Please follow the `Error report` issue template.

**Comment by henbucuoshanghai** [comment]
where is the template?    i am not familiar with mmlab?hep  thks

**Comment by henbucuoshanghai** [comment]
where is the template?    i am not familiar with mmlab?hep  thks

**Comment by hellock** [comment]
When you click the "New issue" button to raise an issue, you will see 3 options and the first one is Error report.

**Comment by knowledgePest** [comment]
I am getting the same issue. How did you folks solve it?
