### ISSUE TITLE
How could I do multi-scale 'validation' ?

### ISSUE THREAD

**Issue by CoinCheung** [open-mmlab/mmdetection#1879]
I would like to know the ms-testing performance in each validation during the training process. Does mmdetection suppose that? Could I simply configure the field of `test_pipeline` to do that ?

**Comment by hellock** [comment]
We have not tried that but it may work. It will cost a long time to do multiscale validation and you may do it manually after training.

**Comment by CoinCheung** [comment]
Thanks, please let me be a lazy person for once. Would you tell me if the newer version mmcv is compatible with older mmcv? My partner's code is based on older version mmcv(pulled from github at around Augest 2019), and my code is based on new version mmcv(December, 2019), if we combine our code together, will there be problem of version compatible?

**Comment by hellock** [comment]
Mostly you can just use the newer version. In case that some errors occur, they should be just minor ones and it is trivial to fix them.

**Comment by CoinCheung** [comment]
Thanks for replying, I am closing this.
