### ISSUE TITLE
How to draw bbox map curve for fcos？I use analyze.py have a error that is no metric bbox map.

### ISSUE THREAD

**Issue by 18804601171** [open-mmlab/mmdetection#1883]

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by 18804601171** [comment]
@hellock The error is that"does not contain metric bbox_mAP".

**Comment by hellock** [comment]
Please follow the Error report issue template.

When you click the "New issue" button to raise an issue, you will see 3 options and the first one is `Error report`.
