### ISSUE TITLE
RepPoints: does this model have a way to visualize reppoints on the testing images?

### ISSUE THREAD

**Issue by StarBurstStream0** [open-mmlab/mmdetection#1891]
Hi,
    i want to see the positions of the generated rep points on each image, but didn't find a .py to show it. May i do it myself or there existing one but i just ormit it?

**Comment by hellock** [comment]
There is no existing scripts to do that. You may need to implement by yourself or refer to the authors.

**Comment by StarBurstStream0** [comment]
> There is no existing scripts to do that. You may need to implement by yourself or refer to the authors.

Thanks a lot, i'll do it!
