### ISSUE TITLE
Dockerfile not build as expected

### ISSUE THREAD

**Issue by alphamodel** [open-mmlab/mmdetection#1893]
I ran `docker build` in the latest clone of the repo. End with following error:

```
Step 11/12 : WORKDIR /mmdetection
 ---> Running in fee857c17c7e
Removing intermediate container fee857c17c7e
 ---> 211439ced91e
Step 12/12 : RUN pip install --no-cache-dir -e .
 ---> Running in dfb528eaf869
Obtaining file:///mmdetection
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mmdetection/setup.py'"'"'; __file__='"'"'/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /mmdetection/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mmdetection/setup.py", line 171, in <module>
        sources=['src/compiling_info.cpp']),
      File "/mmdetection/setup.py", line 101, in make_cuda_ext
        raise EnvironmentError('CUDA is required to compile MMDetection!')
    OSError: CUDA is required to compile MMDetection!
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install --no-cache-dir -e .' returned a non-zero code: 1
```
I have checked the `pytorch` image downloaded do have cuda installed under `/usr/local/cuda`.

```
root@b89786ddf1f5:/workspace# ls -l /usr/local/cuda
lrwxrwxrwx 1 root root 9 Aug 26 21:27 /usr/local/cuda -> cuda-10.1
root@b89786ddf1f5:/workspace# ls -l /usr/local/cuda-10.1
total 48
-rw-r--r-- 1 root root  366 Aug  9 19:57 LICENSE
-rw-r--r-- 1 root root  366 Aug  9 19:57 README
drwxr-xr-x 3 root root 4096 Aug 26 21:30 bin
drwxr-xr-x 2 root root 4096 Aug 26 21:27 compat
drwxr-xr-x 2 root root 4096 Aug 26 21:27 doc
drwxr-xr-x 5 root root 4096 Aug 26 21:30 extras
lrwxrwxrwx 1 root root   28 Aug  9 19:58 include -> targets/x86_64-linux/include
lrwxrwxrwx 1 root root   24 Aug  9 19:58 lib64 -> targets/x86_64-linux/lib
drwxr-xr-x 3 root root 4096 Aug 26 21:31 nvml
drwxr-xr-x 7 root root 4096 Aug 26 21:30 nvvm
drwxr-xr-x 3 root root 4096 Aug 26 21:30 share
drwxr-xr-x 2 root root 4096 Aug 26 21:30 src
drwxr-xr-x 1 root root 4096 Aug 26 21:27 targets
-rw-r--r-- 1 root root   22 Aug  9 19:57 version.txt
```
Any idea why the docker file does not build as expect. Thanks.

**Comment by hellock** [comment]
Are you using `nvidia-docker`?

**Comment by alphamodel** [comment]
@hellock I am using official docker. I just upgrade docker to docker-ce 19.03 and installed nvidia-docker following instructions [here](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(Native-GPU-Support)).  The installation seems to be correct:

```
sudo docker run --gpus all nvidia/cuda nvidia-smi
Tue Dec 31 02:49:19 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P5000        Off  | 00000000:03:00.0  On |                  Off |
| 26%   34C    P8     8W / 180W |  16116MiB / 16270MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

```
sudo nvidia-docker run nvidia/cuda nvidia-smi
Tue Dec 31 02:44:10 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P5000        Off  | 00000000:03:00.0  On |                  Off |
| 26%   34C    P8     8W / 180W |  16116MiB / 16270MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

But running `sudo nvidia-docker build .` still has the same error:

```

Step 12/12 : RUN pip install --no-cache-dir -e .
 ---> Running in 675160f01687
Obtaining file:///mmdetection
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mmdetection/setup.py'"'"'; __file__='"'"'/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /mmdetection/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mmdetection/setup.py", line 171, in <module>
        sources=['src/compiling_info.cpp']),
      File "/mmdetection/setup.py", line 101, in make_cuda_ext
        raise EnvironmentError('CUDA is required to compile MMDetection!')
    OSError: CUDA is required to compile MMDetection!
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install --no-cache-dir -e .' returned a non-zero code: 1

```
Thanks for your help!

**Comment by alphamodel** [comment]
@hellock Interestingly, if we hack into the docker image built, and build the repo inside the container, everything is working as expected. 

```
Successfully built albumentations mmcv pycocotools terminaltables imgaug
Installing collected packages: scipy, imageio, cycler, pyparsing, python-dateutil, kiwisolver, matplotlib, PyWavelets, networkx, scikit-image, imgaug, opencv-python-headless, albumentations, opencv-python, imagecorruptions, addict, mmcv, pycocotools, terminaltables,
mmdet
  Running setup.py develop for mmdet
Successfully installed PyWavelets-1.1.1 addict-2.2.1 albumentations-0.4.3 cycler-0.10.0 imagecorruptions-1.1.0 imageio-2.6.1 imgaug-0.2.6 kiwisolver-1.1.0 matplotlib-3.1.2 mmcv-0.2.15 mmdet networkx-2.4 opencv-python-4.1.2.30 opencv-python-headless-4.1.2.30 pycocotools-2.0.0 pyparsing-2.4.6 python-dateutil-2.8.1 scikit-image-0.16.2 scipy-1.4.1 terminaltables-3.1.0
```
No idea what is happening here. Any idea?

**Comment by wfypku** [comment]
> @hellock Interestingly, if we hack into the docker image built, and build the repo inside the container, everything is working as expected.
> 
> ```
> Successfully built albumentations mmcv pycocotools terminaltables imgaug
> Installing collected packages: scipy, imageio, cycler, pyparsing, python-dateutil, kiwisolver, matplotlib, PyWavelets, networkx, scikit-image, imgaug, opencv-python-headless, albumentations, opencv-python, imagecorruptions, addict, mmcv, pycocotools, terminaltables,
> mmdet
>   Running setup.py develop for mmdet
> Successfully installed PyWavelets-1.1.1 addict-2.2.1 albumentations-0.4.3 cycler-0.10.0 imagecorruptions-1.1.0 imageio-2.6.1 imgaug-0.2.6 kiwisolver-1.1.0 matplotlib-3.1.2 mmcv-0.2.15 mmdet networkx-2.4 opencv-python-4.1.2.30 opencv-python-headless-4.1.2.30 pycocotools-2.0.0 pyparsing-2.4.6 python-dateutil-2.8.1 scikit-image-0.16.2 scipy-1.4.1 terminaltables-3.1.0
> ```
> 
> No idea what is happening here. Any idea?

Yes, I met same problem. Did you solve it?

**Comment by alphamodel** [comment]
@wfypku I did not find out what is the actual problem of the Dockerfile. But what you can do is using some docker file like following, and it will let you compile the package inside the container. Solving this issue seems need in-depth knowledge of docker, I have already checked the environment variables and shell seems not relevant to this issue.

```
ARG PYTORCH="1.3"
ARG CUDA="10.1"
ARG CUDNN="7"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxrender-dev libxext6 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install mmdetection
RUN conda install cython -y && conda clean --all
RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
WORKDIR /mmdetection
RUN /bin/bash
```

**Comment by flyfj** [comment]
> @hellock Interestingly, if we hack into the docker image built, and build the repo inside the container, everything is working as expected.
> 
> ```
> Successfully built albumentations mmcv pycocotools terminaltables imgaug
> Installing collected packages: scipy, imageio, cycler, pyparsing, python-dateutil, kiwisolver, matplotlib, PyWavelets, networkx, scikit-image, imgaug, opencv-python-headless, albumentations, opencv-python, imagecorruptions, addict, mmcv, pycocotools, terminaltables,
> mmdet
>   Running setup.py develop for mmdet
> Successfully installed PyWavelets-1.1.1 addict-2.2.1 albumentations-0.4.3 cycler-0.10.0 imagecorruptions-1.1.0 imageio-2.6.1 imgaug-0.2.6 kiwisolver-1.1.0 matplotlib-3.1.2 mmcv-0.2.15 mmdet networkx-2.4 opencv-python-4.1.2.30 opencv-python-headless-4.1.2.30 pycocotools-2.0.0 pyparsing-2.4.6 python-dateutil-2.8.1 scikit-image-0.16.2 scipy-1.4.1 terminaltables-3.1.0
> ```
> 
> No idea what is happening here. Any idea?

Having the same problem, only start to have the issue after updating to the newest version of mmdetection, weird...

**Comment by RayTang88** [comment]
> I ran `docker build` in the latest clone of the repo. End with following error:
> 
> ```
> Step 11/12 : WORKDIR /mmdetection
>  ---> Running in fee857c17c7e
> Removing intermediate container fee857c17c7e
>  ---> 211439ced91e
> Step 12/12 : RUN pip install --no-cache-dir -e .
>  ---> Running in dfb528eaf869
> Obtaining file:///mmdetection
>     ERROR: Command errored out with exit status 1:
>      command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mmdetection/setup.py'"'"'; __file__='"'"'/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
>          cwd: /mmdetection/
>     Complete output (8 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/mmdetection/setup.py", line 171, in <module>
>         sources=['src/compiling_info.cpp']),
>       File "/mmdetection/setup.py", line 101, in make_cuda_ext
>         raise EnvironmentError('CUDA is required to compile MMDetection!')
>     OSError: CUDA is required to compile MMDetection!
>     No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> The command '/bin/sh -c pip install --no-cache-dir -e .' returned a non-zero code: 1
> ```
> 
> I have checked the `pytorch` image downloaded do have cuda installed under `/usr/local/cuda`.
> 
> ```
> root@b89786ddf1f5:/workspace# ls -l /usr/local/cuda
> lrwxrwxrwx 1 root root 9 Aug 26 21:27 /usr/local/cuda -> cuda-10.1
> root@b89786ddf1f5:/workspace# ls -l /usr/local/cuda-10.1
> total 48
> -rw-r--r-- 1 root root  366 Aug  9 19:57 LICENSE
> -rw-r--r-- 1 root root  366 Aug  9 19:57 README
> drwxr-xr-x 3 root root 4096 Aug 26 21:30 bin
> drwxr-xr-x 2 root root 4096 Aug 26 21:27 compat
> drwxr-xr-x 2 root root 4096 Aug 26 21:27 doc
> drwxr-xr-x 5 root root 4096 Aug 26 21:30 extras
> lrwxrwxrwx 1 root root   28 Aug  9 19:58 include -> targets/x86_64-linux/include
> lrwxrwxrwx 1 root root   24 Aug  9 19:58 lib64 -> targets/x86_64-linux/lib
> drwxr-xr-x 3 root root 4096 Aug 26 21:31 nvml
> drwxr-xr-x 7 root root 4096 Aug 26 21:30 nvvm
> drwxr-xr-x 3 root root 4096 Aug 26 21:30 share
> drwxr-xr-x 2 root root 4096 Aug 26 21:30 src
> drwxr-xr-x 1 root root 4096 Aug 26 21:27 targets
> -rw-r--r-- 1 root root   22 Aug  9 19:57 version.txt
> ```
> 
> Any idea why the docker file does not build as expect. Thanks.

**Comment by chenwj19850115** [comment]
> 
> 
> @wfypku I did not find out what is the actual problem of the Dockerfile. But what you can do is using some docker file like following, and it will let you compile the package inside the container. Solving this issue seems need in-depth knowledge of docker, I have already checked the environment variables and shell seems not relevant to this issue.
> 
> ```
> ARG PYTORCH="1.3"
> ARG CUDA="10.1"
> ARG CUDNN="7"
> 
> FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel
> 
> ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
> ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
> ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
> 
> RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxrender-dev libxext6 \
>  && apt-get clean \
>  && rm -rf /var/lib/apt/lists/*
> 
> # Install mmdetection
> RUN conda install cython -y && conda clean --all
> RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
> WORKDIR /mmdetection
> RUN /bin/bash
> ```

hello, i used your dockerfile, trying to compile the package inside the container, but also failed, can you tell me how you compile the package? Is using "pip install --no-cache-dir -e ." inside the container?

**Comment by blessxu** [comment]
I delete 
RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
WORKDIR /mmdetection
RUN pip install --no-cache-dir -e .

Then use volume to mount the /mmdetection
then run pip install --no-cache-dir -e .

It is okay

**Comment by prateek-77** [comment]
I was meeting with the same issue. I used the image **nvcr.io/nvidia/pytorch:xx** from nvcr page. I ran a container using this image, and set the flag **--runtime = nvidia** (For identifying CUDA). Then run and attach with the container and follow the steps given in [install.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md). The model works perfectly fine on docker after this.

**Comment by ldenoyel** [comment]
There is a bug in the recents changes that causes the issue. When I use an older version of mmdetection it works fine.
In the Docker file I use :
...
WORKDIR /mmdetection
**RUN git reset --hard b7894cb**
RUN pip install --no-cache-dir -e . 
...

I am doing a hard reset to [this commit](https://github.com/open-mmlab/mmdetection/commit/b7894cbdcbe114e3e9efdd1a6a229419a552c807), randomly taken, but I did not investigate which commit is responsible for this.

**Comment by ldenoyel** [comment]
Nevermind, it compiles mais I still have an error when I try to use the lib.

**Comment by ckang244** [comment]
Running into the same issue. It seems the GPUs not being available during the build step causes CUDA to not be visible for some reason. For example, if I build the Dockerfile as-is after commenting out the lines following `WORKDIR /mmdetection` and run it interactively without specifying `--gpus all` in the `docker run` command, I get same CUDA missing error when trying to build. But if I `docker run` with GPUs enabled, I can install using `python setup.py develop` just fine.

**Comment by yexing99** [comment]
@blessxu I tried your method but got error when run training script. "cannot import name 'get_dist_info'", Did you have the same issue?

sudo nvidia-docker run -v /home/adminye/notebooks/mmdetection/configs:/mmdetection/configs_ye -it mmdetection python ./tools/train.py configs_ye/retinanet_r50_fpn_1x.py
Traceback (most recent call last):
  File "./tools/train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
  File "/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/mmdetection/mmdet/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/mmdetection/mmdet/core/evaluation/__init__.py", line 5, in <module>
    from .eval_hooks import (CocoDistEvalmAPHook, CocoDistEvalRecallHook,
  File "/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 13, in <module>
    from mmdet import datasets
  File "/mmdetection/mmdet/datasets/__init__.py", line 6, in <module>
    from .loader import DistributedGroupSampler, GroupSampler, build_dataloader
  File "/mmdetection/mmdet/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/mmdetection/mmdet/datasets/loader/build_loader.py", line 8, in <module>
    from .sampler import DistributedGroupSampler, DistributedSampler, GroupSampler
  File "/mmdetection/mmdet/datasets/loader/sampler.py", line 6, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info'

**Comment by heartInsert** [comment]
Actually , I  think  it's  not hard  to  understand ,  because    if   you  want  to  enable  CUDA ,you  must  add  `--gpus` in  run  at first.

**Comment by ckang244** [comment]
> Actually , I think it's not hard to understand , because if you want to enable CUDA ,you must add `--gpus` in run at first.

As far as I can tell, `—gpus` is not an option in the `docker build` command, only `run`. Already tried adding that.
