### ISSUE TITLE
"CalledProcessError" when training data on my workstation

### ISSUE THREAD

**Issue by YuzhouPeng** [open-mmlab/mmdetection#1898]
I use a new machine(CentOs7) and the program return CalledProcessError when running dist_train.sh:
![捕获](https://user-images.githubusercontent.com/13601004/71575872-8009c980-2b29-11ea-8ae5-09aeaff6e0d8.JPG)
this is train.sh file:
![捕获1](https://user-images.githubusercontent.com/13601004/71575929-ae87a480-2b29-11ea-950a-8d6ff478ea3e.JPG)
and dist_train.sh:
![捕获2](https://user-images.githubusercontent.com/13601004/71576008-03c3b600-2b2a-11ea-949e-b4091ee2a2ca.JPG)
All dependencies install succeed. cudnn version 7.6.3

Could you please help me figure out the problem? Thank you!

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.
