### ISSUE TITLE
what does `with_crowd` for?

### ISSUE THREAD

**Issue by whikwon** [open-mmlab/mmdetection#190]
In the config file, I can find the hyperparameter `with_crowd`. 

In two-stage detector, default option `with_crowd=True`. 

I took my dataset and trained `with_crowd=False` and got error `TypeError: forward_train() missing 1 required positional argument: 'gt_bboxes_ignore'` 

What does `with_crowd` do in the code and if i don't need this, how can i remove this option?

**Comment by whikwon** [comment]
I found strange thing, 

[Faster R-CNN] 
![image](https://user-images.githubusercontent.com/30768596/50068287-73f5e700-0208-11e9-90a5-321634b15672.png)

I Added code for custom dataset and ran the faster R-CNN. when I ran faster R-CNN,
 loss quickly goes to zero like the picture i attached. But when I evaluate using the trained weight, wrong predictions come out. 

```
import numpy as np
from .custom import CustomDataset

class MedicalDataset(CustomDataset):

    def __init__(self, **kwargs):
        super(MedicalDataset, self).__init__(**kwargs)

    def _read_csv_to_list(self, ann_file):
        img_path_bbox_coords = []
        with open(ann_file, 'r') as f:
            lines = f.read().split()
            lines = [i.split(',') for i in lines]
        img_path_bbox_coords.extend(lines)
        return img_path_bbox_coords

    def load_annotations(self, ann_file):
        self.img_path_coords = self._read_csv_to_list(ann_file)
        img_infos = []

        for data in self.img_path_coords:
            path, *coords = data
            width = 416
            height = 416
            img_info = dict(filename=path,
                            width=width,
                            height=height)
            img_infos.append(img_info)
        return img_infos

    def get_ann_info(self, idx):
        _, *coords = self.img_path_coords[idx]
        cen_x, cen_y, w, h = [float(i) for i in coords]
        xmin, ymin = cen_x - w/2, cen_y - h/2
        xmax, ymax = cen_x + w/2, cen_y + h/2
        bboxes = np.array([[xmin, ymin, xmax, ymax]]).astype(np.float32)

        labels = np.array([1]).astype(np.int64)
        bboxes_ignore = np.array([[]]).reshape(-1, 4)

        ann = dict(
            bboxes=bboxes,
            labels=labels,
            bboxes_ignore=bboxes_ignore.astype(np.float32))
        return ann
```

As compared to the Faster R-CNN, I've also ran the retinanet with `with_crowd=True` and it's loss doesn't go to zero. 

What do you think is the problem?

**Comment by hellock** [comment]
For the first question, it should be a bug. We will fix it to allow `with_crowd=False`.
For the second questions, it may be related to the dataset. In such a small dataset, hyper parameters may need to be tuned. I cannot debug for your dataset but I think you may first try training a RPN to see if it is normal.

**Comment by whikwon** [comment]
Thanks. hmm.. Is there some recommendable technique suitable for small dataset (10K~20K)? 

I've tried RetinaNet and loss goes down well, but inference still has issue. 

As the size of the data (width, height) may be a problem, I'm testing after setting same size with coco.

**Comment by puphy** [comment]
I encounter the same error.  How do you solve the  problem? I just change with_crowd as False in config, however it don't work.
