### ISSUE TITLE
problem with setup.py win10

### ISSUE THREAD

**Issue by JY614** [open-mmlab/mmdetection#1902]
when run setup.py , such problem occured :

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe -c mmdet\ops\roi_align\src/roi_align_kernel.cu -o build\temp.win-amd64-3.6\Release\mmdet\ops\roi_align\src/roi_align_kernel.obj -ID:\Anaconda3\envs\mmdetection\lib\site-packages\torch\include -ID:\Anaconda3\envs\mmdetection\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\mmdetection\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\mmdetection\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -ID:\Anaconda3\envs\mmdetection\include -ID:\Anaconda3\envs\mmdetection\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build " "-I C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt" -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61
roi_align_kernel.cu

*************************************
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 2
*************************************

My environment: 
win10
cuda10.1 
vs2015
anaconda
addict==2.2.0
albumentations==0.4.3
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cycler==0.10.0
Cython==0.29.14
decorator==4.4.1
idna==2.8
imagecorruptions==1.1.0
imageio==2.6.1
imgaug==0.2.6
kiwisolver==1.1.0
matplotlib==3.1.2
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mmcv==0.2.15
mmdet==0.6rc0+edb0393
networkx==2.4
numpy==1.18.0
olefile==0.46
opencv-python==4.1.2.30
Pillow==6.2.1
pycocotools==2.0
pycparser==2.19
pyparsing==2.4.6
python-dateutil==2.8.1
PyWavelets==1.1.1
PyYAML==5.2
requests==2.22.0
scikit-image==0.16.2
scipy==1.4.1
six==1.13.0
terminaltables==3.1.0
torch==1.3.1
torchvision==0.4.2
urllib3==1.25.7
wincertstore==0.2 

i had tried all different ******.cu , but all failed

**Comment by hznuhisejeffrey** [comment]
Maybe you can change vs2015 to vs2017 and try again

**Comment by JY614** [comment]
> Maybe you can change vs2015 to vs2017 and try again

i 'll try it

**Comment by JY614** [comment]
> Maybe you can change vs2015 to vs2017 and try again
Thank U, I have compiled it successfully  with vs2017 
Maybe Vs 2015 is not supported

My current environment is vs2017 + cuda10.1 +py3.6 +win10
