### ISSUE TITLE
How to show evaluation value of every category?

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1903]
Using the default mode,this evaluation value shows like this:
Average Precision  (AP) @[ IoU=0.50:0.95 \| area=   all \| maxDets=100 ] = 0.500
--
Average Precision  (AP) @[ IoU=0.50      \| area=   all \| maxDets=100 ] = 0.775
Average Precision  (AP) @[ IoU=0.75      \| area=   all \| maxDets=100 ] = 0.503
Average Precision  (AP) @[ IoU=0.50:0.95 \| area= small \| maxDets=100 ] = 0.312
Average Precision  (AP) @[ IoU=0.50:0.95 \| area=medium \| maxDets=100 ] = 0.410
Average Precision  (AP) @[ IoU=0.50:0.95 \| area= large \| maxDets=100 ] = 0.559
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=   all \| maxDets=  1 ] = 0.516
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=   all \| maxDets= 10 ] = 0.611
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=   all \| maxDets=100 ] = 0.617
Average Recall     (AR) @[ IoU=0.50:0.95 \| area= small \| maxDets=100 ] = 0.428
Average Recall     (AR) @[ IoU=0.50:0.95 \| area=medium \| maxDets=100 ] = 0.562
Average Recall     (AR) @[ IoU=0.50:0.95 \| area= large \| maxDets=100 ] = 0.658
I want to get the every category's P and R . Is there a method to get the result except changing the code in coco_util.py ?

**Comment by hellock** [comment]
https://mmdetection.readthedocs.io/en/latest/GETTING_STARTED.html#analyse-class-wise-performance

**Comment by hsp2454** [comment]
Did you solve this problem?
