### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/proposals/rpn_r50_fpn_1x_train2017.pkl'

### ISSUE THREAD

**Issue by David-19940718** [open-mmlab/mmdetection#1905]
When I run the following code, I got the issue.
python tools/train.py configs/fast_rcnn_r50_fpn_1x.py --gpus 4 --validate --work_dir work_dirs

How can I get the "rpn_r50_fpn_1x_train2017.pkl"?

**Comment by hellock** [comment]
#1487

**Comment by David-19940718** [comment]
thank you. And now i got another issue: When i predict the picture by using my trained model, i found that it raise many Bbox in one picture.  I guess it didn't run the nms. How can i solve it. I try to modify the parameter in faster_rcnn_r50_fpn_1x.py. however. it doesn't work.------------------ 原始邮件 ------------------
发件人: "Kai Chen"<notifications@github.com>
发送时间: 2020年1月2日(星期四) 晚上8:34
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com>;
抄送: "Wei Wang"<940565369@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [open-mmlab/mmdetection] FileNotFoundError: [Errno 2] No suchfile or directory: 'data/coco/proposals/rpn_r50_fpn_1x_train2017.pkl' (#1905)



#1487
 
&mdash;

**Comment by hellock** [comment]
Please raise another issue.
