### ISSUE TITLE
error installing imgaug

### ISSUE THREAD

**Issue by Kindpire** [open-mmlab/mmdetection#1908]
ubuntu 16.04 fresh install mmdetection
after python setup.py develop, it showed:
Installed /home/pengfei/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/scikit_image-0.16.2-py3.7-linux-x86_64.egg
Searching for imgaug<0.2.7,>=0.2.5
Reading https://pypi.org/simple/imgaug/
Downloading https://files.pythonhosted.org/packages/ad/2e/748dbb7bb52ec8667098bae9b585f448569ae520031932687761165419a2/imgaug-0.2.6.tar.gz#sha256=82a5052d2daabc1b8de04b5fade44d59f3376c429880dd78e759028c67f3c8f3
Best match: imgaug 0.2.6
Processing imgaug-0.2.6.tar.gz
Writing /tmp/easy_install-akijj0be/imgaug-0.2.6/setup.cfg
Running imgaug-0.2.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-akijj0be/imgaug-0.2.6/egg-dist-tmp-broa2k_h
  File "build/bdist.linux-x86_64/egg/imgaug/bak/affine.py", line 108
    return shear = shear
                 ^
SyntaxError: invalid syntax

Sorry: IndentationError: unexpected indent (parameters-testcode.py, line 2)
zip_safe flag not set; analyzing archive contents...
imgaug.__pycache__.imgaug.cpython-37: module references __file__
creating /home/pengfei/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/imgaug-0.2.6-py3.7.egg
Extracting imgaug-0.2.6-py3.7.egg to /home/pengfei/anaconda3/envs/open-mmlab/lib/python3.7/site-packages
Sorry: IndentationError: unexpected indent (parameters-testcode.py, line 2)
  File "/home/pengfei/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/imgaug-0.2.6-py3.7.egg/imgaug/bak/affine.py", line 108
    return shear = shear
                 ^
SyntaxError: invalid syntax

Adding imgaug 0.2.6 to easy-install.pth file

**Comment by songyuc** [comment]
@yhcao6 , I meet the same kind of message,

**Comment by songyuc** [comment]
@Kindpire , Hi,
Have you ever successfully install the MMDetection?

**Comment by Kindpire** [comment]
> @Kindpire , Hi,
> Have you ever successfully install the MMDetection?

Yes, I think it's the latest version's problem. However, you can fix it by manually install the right version of imgaug or related packages (especially pkg albumentations).

**Comment by cristianoKaKa** [comment]
> > @Kindpire , Hi,
> > Have you ever successfully install the MMDetection?
> 
> Yes, I think it's the latest version's problem. However, you can fix it by manually install the right version of imgaug or related packages (especially pkg albumentations).

Hi, how to install the right version of imgaug?
I tried conda install imgaug=0.26, but report Package Not Found Error
Something wrong with my conda channels?

**Comment by songyuc** [comment]
@Kindpire , in fact, I am not sure about the reason the `.py` script would use `.whl` style installation instead of "pip install".

**Comment by Kindpire** [comment]
> > > @Kindpire , Hi,
> > > Have you ever successfully install the MMDetection?
> > 
> > 
> > Yes, I think it's the latest version's problem. However, you can fix it by manually install the right version of imgaug or related packages (especially pkg albumentations).
> 
> Hi, how to install the right version of imgaug?
> I tried conda install imgaug=0.26, but report Package Not Found Error
> Something wrong with my conda channels?

i haven't tried conda, but pip works

**Comment by Kindpire** [comment]
> @Kindpire , in fact, I am not sure about the reason the `.py` script would use `.whl` style installation instead of "pip install".
Sorry, i'm not sure about this either.

**Comment by songyuc** [comment]
@Kindpire , thank you!

**Comment by hellock** [comment]
The dependency sometimes gets corrupted and is out of our control. albumentations and imagecorruptions have been made optional and will not be installed by default.
