### ISSUE TITLE
can i change the Long type label to Float type of Focal loss? 

### ISSUE THREAD

**Issue by tim20120526** [open-mmlab/mmdetection#1909]
HI~nice work!
i have a work to use float type label of Focal loss, but it only suppert long type. can you tell me how to implement it by myself? thanks you very much!

**Comment by hellock** [comment]
What do you mean by float type label? Shouldn't classification labels be integers?

**Comment by tim20120526** [comment]
> What do you mean by float type label? Shouldn't classification labels be integers?

I want the label to be a probability, and I've solved this problem. Thanks ~
