### ISSUE TITLE
./compile.sh  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by hust-kevin** [open-mmlab/mmdetection#191]

**Comment by hust-kevin** [comment]
![image](https://user-images.githubusercontent.com/23699630/50086049-da91f980-0236-11e9-806b-fd80d0b4647f.png)

**Comment by hust-kevin** [comment]
![image](https://user-images.githubusercontent.com/23699630/50086071-e978ac00-0236-11e9-9b37-4f6557a691e4.png)

![image](https://user-images.githubusercontent.com/23699630/50086080-f1385080-0236-11e9-83b9-412c1997519e.png)

**Comment by hellock** [comment]
What version of PyTorch are you using? It looks like a version mismatch.

**Comment by hust-kevin** [comment]
my pytorch version is 0.4.0 , and i will try 0.4.1 soon

**Comment by hust-kevin** [comment]
thanks very much !! it work for me
