### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by soheer** [open-mmlab/mmdetection#1912]
When I run this command in Installation :
python setup.py develop  # or "pip install -v -e ."
I got this error :
![image](https://user-images.githubusercontent.com/15982135/71721278-26591600-2e2d-11ea-8ed6-42fa954a030d.png)

Or when I run this command : sudo docker build -t mmdetection docker/
I got this error :

![image](https://user-images.githubusercontent.com/15982135/71721300-3a047c80-2e2d-11ea-8f35-a141699f181c.png)

Thank you

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.
