### ISSUE TITLE
Is a PyTroch implementation of SSD

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1916]
Hi guys!
I want to know whether there is a PyTroch implementation of SSD?
Any answer will be appreciated!

**Comment by hellock** [comment]
Yes, please refer to the documentation.

**Comment by songyuc** [comment]
@hellock , it would be my honor to hear from a CV master like you.
And I have checked the documentation, but it seems that there are only caffe implementations of SSD, as shown below,
![图片](https://user-images.githubusercontent.com/27288110/71798357-bf399c80-308c-11ea-8e41-dbb7cc558e48.png)

**Comment by hellock** [comment]
`caffe` here refers to a data preprocessing style, not the caffe implementation.
