### ISSUE TITLE
I want to know how to start learning to modify the model? 

### ISSUE THREAD

**Issue by Noah-CV** [open-mmlab/mmdetection#1918]
For example,SSD+FPN。
Seeing the source code is not explained, some places are confused。 Thanks for your help.

**Comment by ZwwWayne** [comment]
Please be specific, e.g., which part you are not clear with so that we can help you more efficiently.

**Comment by hellock** [comment]
https://mmdetection.readthedocs.io/en/latest/GETTING_STARTED.html#develop-new-components
