### ISSUE TITLE
Does mmdetection have  cascade r-cnn pretrain model based resnext50_32x4d

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1919]

**Comment by ZwwWayne** [comment]
For now, we do not provide such models, but we provide resnext101_32x4d, so it should be easy to modify the config to train one by setting the depth to 50.
PRs are welcomed if you could train one with correct config, trained model, and reasonable results.

**Comment by yuyijie1995** [comment]
OK I will try.
