### ISSUE TITLE
Batch_Size*imgs_per_gpu*mgpus  !=  len(train_data)  ?????

### ISSUE THREAD

**Issue by Liys0558** [open-mmlab/mmdetection#1920]
Excuse me, I have 4 GPUs, imgs_per_gpu is 8, then the batctsize should be 4516/32 = 141, but the training log is 40, what is the reason? ? ?

**Comment by ZwwWayne** [comment]
Firstly, the batch size should be num_gpus*imgs_per_gpu, thus it is 4*8 = 32.
Then I do not understand your question, what is 4516 mean? what is 40 in the training log?
Maybe you can screenshot your log then ask your question more clearly.

**Comment by Liys0558** [comment]
> Firstly, the batch size should be num_gpus_imgs_per_gpu, thus it is 4_8 = 32.
> Then I do not understand your question, what is 4516 mean? what is 40 in the training log?
> Maybe you can screenshot your log then ask your question more clearly.

4516 is the number of training sets，4*8 = 32 is batch_size , 1 epoch should be 4516/32 = 141 batch size, but 1 epoch only has 40 batch size???
2020-01-06 09:21:59,838 - INFO - Epoch [01][5/40]

**Comment by hellock** [comment]
iterations per epoch is expected to be `total_img / (num_gpus * imgs_per_gpu)`. You may provide more information such as your config file, training command, etc.
