### ISSUE TITLE
How to use the coco_eval.py?

### ISSUE THREAD

**Issue by David-19940718** [open-mmlab/mmdetection#1921]
Firstly, I run the code:
`python tools/test.py configs/faster_rcnn_r50_fpn_1x.py work_dirs/faster_rcnn_r50_fpn_1x/latest.pth --out demo/result_12.pkl`
and i get the result.pkl.
However, when I run the next code:
`python tools/coco_eval.py demo/result_12.pkl --ann data/coco/annotations/instances_val2017.json `
I got the issue:
`Traceback (most recent call last):
  File "tools/coco_eval.py", line 30, in <module>
    main()
  File "tools/coco_eval.py", line 26, in main
    coco_eval(args.result, args.types, args.ann, args.max_dets, args.classwise)
  File "/home/xxx/xxx/xxx/mmdetection/mmdet/core/evaluation/coco_utils.py", line 39, in coco_eval
    assert result_file.endswith('.json')
AssertionError
`

**Comment by David-19940718** [comment]
How can I get the .json file? It just gives me a  .pkl file.

**Comment by David-19940718** [comment]
I try to modify the code by follow:
`python tools/test.py configs/faster_rcnn_r50_fpn_1x.py work_dirs/faster_rcnn_r50_fpn_1x/epoch_12.pth --json_out demo/bbox
`
`python tools/coco_eval.py demo/result.json --ann data/coco/annotations/instances_val2017.json`
It can run, and I get the result :

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.127
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.245
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.123
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.080
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.134
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.104
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.191
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.206
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.206
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.146
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.219
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.135


But I don't want this, how can I get the ap per class?

**Comment by David-19940718** [comment]
Sorry, I just found the same issue.

**Comment by chengbaoyan** [comment]
Did you solve the  AssertionError?
I also meet this question

**Comment by hsp2454** [comment]
Did you solve this problem?
