### ISSUE TITLE
Cityscapes test error

### ISSUE THREAD

**Issue by yyfyan** [open-mmlab/mmdetection#1922]
Hi, I use mmdection's trained-model in the Cityscapes to test, but I get the error AP results. 
however,  the vis results is good. 

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.035
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.069
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.034
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.022
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.045
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.043
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.033
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.050
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.050
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.031
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.059
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.069

**Comment by yyfyan** [comment]
@DXist @ramkakarala @tjsongzw @lindahua

**Comment by yyfyan** [comment]
I have solved the issue, by change the results order.

**Comment by yl-precious** [comment]
> order

how did you change the results order? I met the same questioin too.

**Comment by yyfyan** [comment]
The order is same as you created the coco format cityscapes train and val set.

**Comment by YangxintongLyu** [comment]
> The order is same as you created the coco format cityscapes train and val set.

@yyfyan Could you please give more details about how to change the results order? Thanks in advance.
