### ISSUE TITLE
Modify config file when train with custom dataset

### ISSUE THREAD

**Issue by neoyang0620** [open-mmlab/mmdetection#1924]
Hi,

I built a custom dataset based on COCO format. And added a new my_dataset.py under mmdet/datasets and added from .my_dataset import MyDataset in __init__.py. 

Then, I modified the  configuration file:

dataset_type = 'MyDataset'
data_root = 'path/to/my/dataset'
data = dict{}

During the training, the accuracy is almost 100. However, in evaluation, the mAP is almost 0. I don't know what's wrong with my setting. Did i forget to change any details?

Best,
Neo

**Comment by hellock** [comment]
I don't know either. For custom datasets, you need to figure out 1) if your annotation is correct, 2) if hyper-parameters are suitable for your application. You cannot expect getting good results without any prior knowledge of your data and settings.

**Comment by neoyang0620** [comment]
@hellock Hi, thanks for the explanation. I get one more question. For instance, I get a one-class dataset. When I train the model, do I need to modify the num_classes under bbox_head to 1 (Originally, it is 81)?

**Comment by hellock** [comment]
It should be 2 (1 foreground + 1 background).
