### ISSUE TITLE
  I'm confused about whether we need to use test.py to generate result.pkl before evaluate

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#1925]
The official website doesn't give an example of evaluate, only gives an example of test

can we use  python  coco_eval.py without using  test.py?
is result.pkl necessary before evaluate?

    
Test Mask R-CNN with 8 GPUs, and evaluate the bbox and mask AP.

./tools/dist_test.sh configs/mask_rcnn_r50_fpn_1x.py \
    checkpoints/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth \
    8 --out results.pkl --eval bbox segm

**Comment by ZwwWayne** [comment]
When you run the test.py, you are evaluating your model. This command evaluates the bbox mAP and mask mAP of the output `results.pkl`.
