### ISSUE TITLE
Is mmdetection a pure-Python codebase?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1928]
Hi, guys!
When I install the mmdetection, I found it would use the command 'python setup.py develop  # or "pip install -v -e ."', so it seems that mmdetection is not a pure-Python codebase, am I right?

Any answer will be appreciated!

**Comment by ZwwWayne** [comment]
Hi @songyuc ,
Yes you are right, the mmdetection is not a pure-Python codebase, as you can find C++&Cuda code in [here](https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops).

**Comment by songyuc** [comment]
@ZwwWayne thanks for the explanation!

**Comment by songyuc** [comment]
@ZwwWayne , in fact, I still have a little quesition about the usage of C++ & Cuda codes.
So what is the reason of using C++ & Cuda codes, as pure Python code seems more convenient?
What is the consideration of you to mix these different level of codes?

Your answer will be appreciated as a fresh hand like me.

**Comment by hellock** [comment]
Pure python code is slow and inefficient for some operators.
