### ISSUE TITLE
Better way to define work_dir

### ISSUE THREAD

**Issue by destinyzs** [open-mmlab/mmdetection#1929]
The `work_dir` in configs are all defined by the same file names, but I ’m sure there will be omissions in the actual situation. For simplicity, i think the following way is better, just a suggestion.

```
import os
work_dir = './work_dirs/' + os.path.splitext(os.path.basename(__file__))[0]
```

It needs no manual modification.

**Comment by ZwwWayne** [comment]
Hi @destinyzs ,
Thanks for your suggestion. For now, we provide an option in the script to set the word dir manually every time you run a training experiment. You can find it [here](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L21).
We will also consider your suggestion in our future plan.

**Comment by destinyzs** [comment]
Great, thanks for your reply.
