### ISSUE TITLE
What is the difference between the commands python setup.py develop  and pip install -v -e .

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1930]
Today I am installing MMDetection, and I have used the command `python setup.py develop`, but I found my downloading speed from https://pypi.org/simple/*** is very slow, and in fact, I have opened my VPN to prevent the influence of censor firewall as I am in China;
So I want to know the difference between the commands `python setup.py develop` and `pip install -v -e .`

**Comment by hellock** [comment]
You may expect that they are the same.

**Comment by hellock** [comment]
You can switch to a mirror site such as tsinghua or aliyun if the official pypi source is slow.
