### ISSUE TITLE
can not  pip install mmcv

### ISSUE THREAD

**Issue by zhaojingru408** [open-mmlab/mmdetection#1931]
![1](https://user-images.githubusercontent.com/56055695/71825434-d309f080-30d6-11ea-9ac3-1ad3d80d942f.png)

![2](https://user-images.githubusercontent.com/56055695/71825531-09477000-30d7-11ea-8d82-eaa3dd21a5ac.png)

wish for help

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.

**Comment by zhaojingru408** [comment]
sorry I really don't know why. Could you give me your contact information? thank you so much

**Comment by CRmost** [comment]
Maybe you can try the 阿里源.

**Comment by zhaojingru408** [comment]
Could you be more specific

**Comment by CRmost** [comment]
Try the" pip install mmcv -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com flask"

**Comment by iamchinu14** [comment]
It is not working @CRmost
