### ISSUE TITLE
 I have some confusion when using VOC data， are there any problems in the following steps

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#1934]
1、Do we need to recompile as follows after modifying the related configuration of VOC mode

    ./compile.sh
    python setup.py develop

2、Some people say, are they right？

before Calculation  mAP we should modify the VOC Eval function in the VOC eval.py file
Note the following code:
     if hasattr(dataset, 'year') and dataset.year == 2007:
            dataset_name = 'voc07'
        else:
            dataset_name = dataset.CLASSES
On the eval map, add:
dataset_name = dataset.CLASSES
https://blog.csdn.net/weicao1990/article/details/93484603

**Comment by hellock** [comment]
Your steps are wrong and outdated. Please refer to the official documentation.
