### ISSUE TITLE
What will happen increasing cascading in Cascade RCNN

### ISSUE THREAD

**Issue by ravising-h** [open-mmlab/mmdetection#1936]
I was thinking to play with cascaded RCNN Paramerters. What will be the effect of changing the Cascading (from three to let us say 4) in Cascade RCNN?

**Comment by songyuc** [comment]
@ravising-h it is a interesting question, but I am afraid that one of the first consumption is the time cost.
The intuition of "more cascaded RCNN" is something like the intuition of "more anchors" in the RPN, I think.

**Comment by hellock** [comment]
You may refer to the original paper, which solves your question.
