### ISSUE TITLE
Is there a instant test .py script for us to test whether we have installed the mmdetection successfully?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1937]
Hi guys,
I want to know whether there is a instant test `.py` script for us to make sure whether we have installed the MMDetection successfully?

**Comment by ravising-h** [comment]
You can use this script to check whether environment is installed correctly [collect_env](https://github.com/open-mmlab/mmdetection/blob/master/tools/collect_env.py) .  To check whether installation is right you can run a demo on pretrained model.

**Comment by songyuc** [comment]
@ravising-h , thanks sincerely for your help.
And here is my output information,
```bash
sys.platform: linux
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.1.1
MMCV: 0.2.15
MMDetection: 1.0rc1+e907139
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.1
```
So is this mean that I have installed the MMDetection successfully?

**Comment by Chromer163** [comment]
@songyuc 
here is my output：
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/home/hyg/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/PIL/__init__.py)

maybe I need to check the environment

**Comment by songyuc** [comment]
@Chromer163 , hi, it is clear that you haven't installed the PIL successfully.

**Comment by Chromer163** [comment]
@songyuc  May PIL version is not correct.

**Comment by Chromer163** [comment]
@songyuc 
Now here is my output log:
`sys.platform: linux
Python: 3.7.6 | packaged by conda-forge | (default, Dec 27 2019, 00:09:34) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1: GeForce GTX 1080 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.1.2
MMCV: 0.2.15
MMDetection: 1.0rc1+e907139
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0`

**Comment by ravising-h** [comment]
@songyuc Seems right. If still have doubts then compare versions from requirement.txt

**Comment by songyuc** [comment]
@ravising-h in fact, my question is whether there is a .py script for me to get the WYSIWYG result, specifically, that I can use my own picture to see the detection results, instead of needing download the whole bulky dataset like COCO.

**Comment by ravising-h** [comment]
As mentioned above you can use [demo](https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb). Take help from here you need not to download coco dataset rather just a epoch_{}.pth file as mentioned in the demo_inference.ipynb

**Comment by songyuc** [comment]
@ravising-h , appreciate it very much as a beginner like me.
I will try the demo Notebook, thanks!

**Comment by songyuc** [comment]
@ravising-h , do you have a pretrained ".pth" model, which help me test my demo at once?
Appreciate!

**Comment by ravising-h** [comment]
download it from [here](https://modelzoo.co/)

**Comment by songyuc** [comment]
@ravising-h , I am afraid that Model zoo is a website with collection of different kinds of projects instead of pretrained `.pth` file.

**Comment by chenggangdu** [comment]
@ravising-h There was a  error:Segmentation fault (core dumped) when I ran the coolect_env.py script, do you know why?

**Comment by songyuc** [comment]
@chenggangdu , maybe you did not installed the MMDetection successfully.

**Comment by chenggangdu** [comment]
> @chenggangdu , maybe you did not installed the MMDetection successfully.

I re installed the MMDetection, and  did not happen Segmentation fault (core dumped) .but I ran the demo, there are just showing an image like the demo.jpg whitout the bboxes.

**Comment by changwh** [comment]
> 
> 
> @songyuc May PIL version is not correct.

see:https://github.com/open-mmlab/mmdetection/pull/1907#issuecomment-570752358
confirm PIL<7.0

**Comment by fuyuer233** [comment]
@chenggangdu，I have the same problem. Have you solved the problem？
