### ISSUE TITLE
Is there a pretrained ".pth" file for me to test the demo Notebook

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1939]
Hi guys,
I want to know whether there is a pretrained ".pth" file for me to test [the demo Notebook](https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb)

Any answer and suggestion will be appreciated!

**Comment by ravising-h** [comment]
https://modelzoo.co/

**Comment by songyuc** [comment]
@ravising-h , thanks for your kind answer!

We can get the pretrained ".pth" file of MMDetection in its [Model zoo](https://github.com/open-mmlab/mmdetection/blob/master/docs/MODEL_ZOO.md).
