### ISSUE TITLE
What is the application scenarios of "Asynchronous interface"?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1940]
I see the "Asynchronous interface" in [Getting Started](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#asynchronous-interface---supported-for-python-37
), as
> Async interface allows not to block CPU on GPU bound inference code and enables better CPU/GPU utilization for single threaded application. Inference can be done concurrently either between different input data samples or between different models of some inference pipeline.

In fact, I am not quite sure about the explicit application scenarios of this asynchronous interface.

Any idea and answer will be appreciated!

**Comment by hellock** [comment]
For some advanced users, they may want to accelerate the inference with asynchronous interface.

**Comment by songyuc** [comment]
@hellock , could you give me a detailed example you would use this?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/tests/async_benchmark.py
