### ISSUE TITLE
What is the difference between MMDistributedDataParallel and torch.nn.parallel.DistributedDataParallel?

### ISSUE THREAD

**Issue by xmyqsh** [open-mmlab/mmdetection#1941]
What is the difference between MMDistributedDataParallel and torch.nn.parallel.DistributedDataParallel?

Is MMDistributedDataParallel better than torch.nn.parallel.DistributedDataParallel?

I have not dig into the detail.

**Comment by hellock** [comment]
MMDistributedDataParallel adds support for [`DataContainer`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/data_container.py#L18).
