### ISSUE TITLE
Do I need to add the string of my dateset into the all list?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1942]
Today I followed the instruction in the [Getting Started](https://mmdetection.readthedocs.io/en/latest/GETTING_STARTED.html#train-a-model
) to get a model on my own dataset,
And I see this,
![image](https://user-images.githubusercontent.com/27288110/71899009-bbde0800-3195-11ea-9c84-368da1c300b0.png)
When I open the `mmdet/datasets/__init__.py`,
I see this code like,
```python
from .builder import build_dataset
from .cityscapes import CityscapesDataset
from .coco import CocoDataset
from .custom import CustomDataset
from .dataset_wrappers import ConcatDataset, RepeatDataset
from .loader import DistributedGroupSampler, GroupSampler, build_dataloader
from .registry import DATASETS
from .voc import VOCDataset
from .wider_face import WIDERFaceDataset
from .xml_style import XMLDataset

from .my_dataset import MyDataset

__all__ = [
    'CustomDataset', 'XMLDataset', 'CocoDataset', 'VOCDataset',
    'CityscapesDataset', 'GroupSampler', 'DistributedGroupSampler',
    'build_dataloader', 'ConcatDataset', 'RepeatDataset', 'WIDERFaceDataset',
    'DATASETS', 'build_dataset'
]
```
So my question is if I need to add the string `"MyDataset"` of my `MyDataset` class into the `__all__` list variable?

Your answer will be appreciated.

**Comment by hellock** [comment]
It is recommended but not forced.
