### ISSUE TITLE
How to modify config file when train with custom dataset

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1944]
Hi, guys,
If I want to modify the config file so as to train with my custom dataset,
what are the parameters in the config MUST to be modified, temporarily not in the consideration of detection accuracy?

**Comment by hellock** [comment]
All dataset specific variables. To name a few, annotation files, class numbers, etc.

**Comment by songyuc** [comment]
@hellock I found path-related and classes_number are essential to modify.
