### ISSUE TITLE
How to set the bboxhead.num_classes in the config?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1946]
Hi guys,
I am working on my own dataset of plane images in the VOC format, which has 24 classes.
And in the config file, there is a parameter of `bboxhead.num_classes`, as showed below,

```python
    bbox_head=dict(

        type='SharedFCBBoxHead',

        num_fcs=2,

        in_channels=256,

        fc_out_channels=1024,

        roi_feat_size=7,

        num_classes=81,

        target_means=[0., 0., 0., 0.],

        target_stds=[0.1, 0.1, 0.2, 0.2],

        reg_class_agnostic=False,
```
 The original value of  `bboxhead.num_classes` is 81. But in my dataset, there is only 24 classes of planes.
So my question is that whether I should set the `bboxhead.num_classes` as 25 or any other value?

Your answer will be appreciated very much!

**Comment by hellock** [comment]
25

**Comment by songyuc** [comment]
@hellock , thanks very much!
I think it will be more beneficial if you can provide the detailed description of the config parameters in the MMDetection doc.
