### ISSUE TITLE
Why does the num_stages=4 in the fast_rcnn_r50_fpn_1x.py?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1947]
Today I continue to study MMDetection.
When I read the code of `fast_rcnn_r50_fpn_1x.py`, I see a snippet as this,
```python
backbone=dict(

        type='ResNet',

        depth=50,

        num_stages=4,

        out_indices=(0, 1, 2, 3),

        frozen_stages=1,

        style='pytorch'),
```
and the `num_stages=4`, which seems strange.
Because in the original paper of ResNet, all kinds of ResNets have 5 stages, as conv1, conv2_x, conv3_x, conv4_x and conv5_x.
So my question is, what is the meaning of `num_stages=4` here?

**Comment by hellock** [comment]
conv1 is not considered a res stage.
