### ISSUE TITLE
What is the meaning of dataset_type?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1948]
Hi guys,
I am working on modifying the config file for my own dataset,
and I see this as,
```python
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        proposal_file=data_root + 'proposals/rpn_r50_fpn_1x_train2017.pkl',
        img_prefix=data_root + 'train2017/',
        pipeline=train_pipeline),
```
So what is the meaning of dataset_type?
I have set it as `dataset_type = 'MyDataset'`, which I don't whether is correct or not.

Any answer or suggestion will be appreciated!

**Comment by hellock** [comment]
It should be your own dataset class name.
