### ISSUE TITLE
Traceback (most recent call last):   File "tools/train.py", line 12, in <module>     from mmdet import __version__ ModuleNotFoundError: No module named 'mmdet'

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1952]
I used 'python setup.py develop' today and the mmdet module does not work.
Are some things updated and How can I use it again?

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.

**Comment by MarsJunhaoHu** [comment]
Hi, did you solve the problem? I met the exactly same problem. You are the only one who asks the question here.
