### ISSUE TITLE
Is there any way to see results after every rcnn in cascade RCNN

### ISSUE THREAD

**Issue by ravising-h** [open-mmlab/mmdetection#1958]
I want to check results after every rcnn in cascaded is there any way?

**Comment by hellock** [comment]
You can implement it by yourself. #1806 is a reference.

**Comment by ravising-h** [comment]
If anybody interested:
In paper it is mentioned if threshold is 0.5 3 stages are best if increasing thres to 0.75 it is advisable to increase it to 4.
I decreaced the stages to 2 and Map fell by 2.
