### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 359: invalid continuation byte

### ISSUE THREAD

**Issue by ToBread** [open-mmlab/mmdetection#1959]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
You did not provide any information and fill any reserved fields in the template, thus we cannot help.

**Comment by 1127244933** [comment]
![1708787999923](https://github.com/open-mmlab/mmdetection/assets/72912006/f64e148c-4746-42a6-a58b-a4dedf856596)

![1708788032593](https://github.com/open-mmlab/mmdetection/assets/72912006/e73ac6fd-98b3-41f0-87ca-d1f5de7938bb)
类似的错误，不知道如何解决呢
