### ISSUE TITLE
Different image size in one batch

### ISSUE THREAD

**Issue by FeiLyu** [open-mmlab/mmdetection#1966]
In one batch, there are two images of different pad_shapes, for example, size of image 1 is (384, 512, 3), and size of image 2 is (352,512,3), but the 'img' size is [2,3,384,512], so could you please tell me which step changes the size of image 1?

**Comment by FeiLyu** [comment]
'DataContainer' solved the problem.

**Comment by QuentinAI** [comment]
Thanx. How could u solve the problem? I met the same problem, I have two kinds of images of different size.

**Comment by FeiLyu** [comment]
> Thanx. How could u solve the problem? I met the same problem, I have two kinds of images of different size.

I use the formatting function in /mmdet/datasets/pipelines
from mmcv.parallel import DataContainer as DC
results['img'] = DC(to_tensor(img), stack=True)
