### ISSUE TITLE
why usually freeze thr first stage of backbone?

### ISSUE THREAD

**Issue by lingfengyueguang** [open-mmlab/mmdetection#1967]
I want to know why usually freeze the first stage of backbone? Compared with not frozen, how to affect final performance？

**Comment by songyuc** [comment]
I think this might be relevant to my question of #1947, there are usually 4 stages in the config.

**Comment by lingfengyueguang** [comment]
> I think this might be relevant to my question of #1947, there are usually 4 stages in the config.

Sorry, I want to know why we need freeze the first stage？How does this operation affect final performance？

**Comment by songyuc** [comment]
I think only the contributor @hellock can provide the true answer.
And in my opinion, I think this might be due to the fact that the structure first stage is relatively simpler than the other four stages.
In fact, I am also very interested about the answer of this question.

**Comment by hellock** [comment]
This training strategy is not first adopted by us, it has been the standard practice for object detection codebases. Unfortunately I forgot the exact performance of these two cases.

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/issues/1802

**Comment by ZwwWayne** [comment]
Hi @songyuc , you can train and compare the results on your own.
Since this question is duplicated, the issue is closed. Feel free to reopen it if you have any further questions.

**Comment by hiyyg** [comment]
Hi @hellock , I wonder why does mmdet usually freezes the first stage but detectron2 freezes the first 2 stages by default?

**Comment by ZwwWayne** [comment]
Hi @hiyyg ,
You can see this [line](https://github.com/facebookresearch/detectron2/blob/28223a6fccb1c42f421f9b6e7dbbdc29193068ab/detectron2/modeling/backbone/resnet.py#L454). They use `MODEL.BACKBONE.FREEZE_AT = 2` by default, which will freeze the stem layer and the first stage, which is the same as our setting.
