### ISSUE TITLE
NotImplementedError: Built-in validation is not implemented yet in not-distributed training

### ISSUE THREAD

**Issue by gongtian1234** [open-mmlab/mmdetection#1968]
When I executed mmd, I encountered the following error:

    Traceback (most recent call last):
    File "tools/train.py", line 124, in <module>
      main()
    File "tools/train.py", line 120, in main
      timestamp=timestamp)
    File "/content/drive/My Drive/model_train/10_酒瓶检测/mmdetection/mmdet/apis/train.py", line 
    133, in train_detector
      timestamp=timestamp)
    File "/content/drive/My Drive/model_train/10_酒瓶检测/mmdetection/mmdet/apis/train.py", line 
    282, in _non_dist_train
        raise NotImplementedError('Built-in validation is not implemented '
    NotImplementedError: Built-in validation is not implemented yet in not-distributed training. Use 
    distributed training or test.py and *eval.py scripts instead.

I haven't encountered this kind of error before. What is the reason for this and how can I solve it?

**Comment by chenggangdu** [comment]
Have you solved the problem？

**Comment by SISTMrL** [comment]
have you solved the problem? thanks

**Comment by SISTMrL** [comment]
> Have you solved the problem？

have you solved it?

**Comment by chenggangdu** [comment]
> > Have you solved the problem？
> 
> have you solved it?
I changed the validate to False in the line 121 in train.py

**Comment by SISTMrL** [comment]
> > > Have you solved the problem？
> > 
> > 
> > have you solved it?
> > I changed the validate to False in the line 121 in train.py

you means in tools/train.py?

**Comment by chenggangdu** [comment]
> > > > Have you solved the problem？
> > > 
> > > 
> > > have you solved it?
> > > I changed the validate to False in the line 121 in train.py
> 
> you means in tools/train.py?

yes
