### ISSUE TITLE
Visualization is poor

### ISSUE THREAD

**Issue by Curry1201** [open-mmlab/mmdetection#197]
I used the VOC07 dataset to train and test the mask rcnn. Why is the result displayed is completely wrong when I visualize the code? (The visualization code is: python3 tools/test.py configs/mask_rcnn_r50_fpn_1x.py work_dirs/mask_rcnn_r50_fpn_1x/latest.pth --show) 
For example, the image below. Sometimes the model marks people as birds and marks cats as cars.
/home/power/mmdetection/_screenshot_21.12.2018.png

The file mask_rcnn_r50_fpn_1x.py is modified as follows:
# dataset settings
dataset_type = 'CocoDataset'
data_root = 'data/VOCdevkit/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/pascal_train2007.json',
        img_prefix=data_root + 'VOC2007/VOCtrainval_06-Nov-2007/JPEGImages',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=True,
        with_crowd=True,
        with_label=True),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/pascal_val2007.json',
        img_prefix=data_root + 'VOC2007/VOCtrainval_06-Nov-2007/JPEGImages',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=True,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/pascal_test2007.json',
        img_prefix=data_root + 'VOC2007/VOCtest_06-Nov-2007/JPEGImages',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)

There seems to be no problem when the model training is completed.
2018-12-21 14:19:23,665 - INFO - Epoch [12][600/626]	lr: 0.00005, time: 0.599, data_time: 0.015, loss_rpn_cls: 0.0084, loss_rpn_reg: 0.0166, loss_cls: 0.0845, acc: 96.8066, loss_reg: 0.0675, loss_mask: 0.1951, loss: 0.3721
2018-12-21 14:23:17,430 - INFO - Epoch [12][626/626]	lr: 0.00005, bbox_mAP: 0.2823, segm_mAP: 0.2888

**Comment by hedes1992** [comment]
> I used the VOC07 dataset to train and test the mask rcnn. Why is the result displayed is completely wrong when I visualize the code? (The visualization code is: python3 tools/test.py configs/mask_rcnn_r50_fpn_1x.py work_dirs/mask_rcnn_r50_fpn_1x/latest.pth --show)
> For example, the image below. Sometimes the model marks people as birds and marks cats as cars.
> /home/power/mmdetection/_screenshot_21.12.2018.png
> 
> The file mask_rcnn_r50_fpn_1x.py is modified as follows:
> 
> # dataset settings
> dataset_type = 'CocoDataset'
> data_root = 'data/VOCdevkit/'
> img_norm_cfg = dict(
> mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> data = dict(
> imgs_per_gpu=2,
> workers_per_gpu=2,
> train=dict(
> type=dataset_type,
> ann_file=data_root + 'annotations/pascal_train2007.json',
> img_prefix=data_root + 'VOC2007/VOCtrainval_06-Nov-2007/JPEGImages',
> img_scale=(1333, 800),
> img_norm_cfg=img_norm_cfg,
> size_divisor=32,
> flip_ratio=0.5,
> with_mask=True,
> with_crowd=True,
> with_label=True),
> val=dict(
> type=dataset_type,
> ann_file=data_root + 'annotations/pascal_val2007.json',
> img_prefix=data_root + 'VOC2007/VOCtrainval_06-Nov-2007/JPEGImages',
> img_scale=(1333, 800),
> img_norm_cfg=img_norm_cfg,
> size_divisor=32,
> flip_ratio=0,
> with_mask=True,
> with_crowd=True,
> with_label=True),
> test=dict(
> type=dataset_type,
> ann_file=data_root + 'annotations/pascal_test2007.json',
> img_prefix=data_root + 'VOC2007/VOCtest_06-Nov-2007/JPEGImages',
> img_scale=(1333, 800),
> img_norm_cfg=img_norm_cfg,
> size_divisor=32,
> flip_ratio=0,
> with_mask=False,
> with_label=False,
> test_mode=True))
> 
> # optimizer
> optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
> 
> There seems to be no problem when the model training is completed.
> 2018-12-21 14:19:23,665 - INFO - Epoch [12][600/626]	lr: 0.00005, time: 0.599, data_time: 0.015, loss_rpn_cls: 0.0084, loss_rpn_reg: 0.0166, loss_cls: 0.0845, acc: 96.8066, loss_reg: 0.0675, loss_mask: 0.1951, loss: 0.3721
> 2018-12-21 14:23:17,430 - INFO - Epoch [12][626/626]	lr: 0.00005, bbox_mAP: 0.2823, segm_mAP: 0.2888

What's your visualization result and mAP result?
In my practice, it need set show to False when evaluation, 
when setting show to True, there exists no need to do evaluation

**Comment by Curry1201** [comment]
Visualization result is here.
https://github.com/Curry1201/mmdetection/blob/a56e0f4bfbedb53e95cf1d765c76ed32ab4e417e/_screenshot_21.12.2018.png
(Sorry, I don't know how to add an image in the comments section.) 

mAP result is here.
2018-12-21 14:23:17,430 - INFO - Epoch [12][626/626]	lr: 0.00005, bbox_mAP: 0.2823, segm_mAP: 0.2888

Is the set show to False in the config file during the evaluation? I did not find it. I am just performing a visual operation.

**Comment by hedes1992** [comment]
> Visualization result is here.
> https://github.com/Curry1201/mmdetection/blob/a56e0f4bfbedb53e95cf1d765c76ed32ab4e417e/_screenshot_21.12.2018.png
> (Sorry, I don't know how to add an image in the comments section.)
> 
> mAP result is here.
> 2018-12-21 14:23:17,430 - INFO - Epoch [12][626/626]	lr: 0.00005, bbox_mAP: 0.2823, segm_mAP: 0.2888
> 
> Is the set show to False in the config file during the evaluation? I did not find it. I am just performing a visual operation.

You can copy image to this edit box, it will upload to github automatically.

**Comment by Curry1201** [comment]
@hellock I got it. Thanks.
