### ISSUE TITLE
some questions about libra_RetinaNet

### ISSUE THREAD

**Issue by wytcsuch** [open-mmlab/mmdetection#1972]
Hello, I'm studying libra retinanet recently, I found that there seems a focal loss in the train_cfg in the config of libra_retinanet ,however in the config of retinanet,there is nothing, What's the meaning of the focal loss in train_cfgs,  and also smoothl1_beta?
```
train_cfg = dict(
    assigner=dict(
        type='MaxIoUAssigner',
        pos_iou_thr=0.5,
        neg_iou_thr=0.4,
        min_pos_iou=0,
        ignore_iof_thr=-1),
    smoothl1_beta=0.11,  #???
    gamma=1.0,  ##???
    alpha=0.75,  #???
    allowed_border=-1,
    pos_weight=-1,
    debug=False)
```

**Comment by OceanPang** [comment]
Hi, sorry for the confusing. The three factors are originally here but move to the `Balanced L1 Loss` later. This is our negligence during the refactoring. We will move it later. Thanks!
