### ISSUE TITLE
fatal error: cuda_runtime_api.h: No such file or directory

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1973]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Can not use "python setup.py develop" to compile the mmdet

**Reproduction**
1. What command or script did you run?
```
python setup.py develop
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No.
3. What dataset did you use?
coco
**Environment**

1. Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.
Can not use the command,my mmdet is not compiled yet.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
My cuda path in ~/.bashrc 
export PATH="/usr/local/cuda-10.1/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH"
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

and I can use the cuda pytorch normally
"""
>>> import torch
>>> torch.cuda.is_available()
True
"""

**Error traceback**
If applicable, paste the error trackback here.
```
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.utils.compiling_info' extension
gcc -pthread -B /home/wrc/anaconda3/envs/coco/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/wrc/anaconda3/envs/coco/lib/python3.6/site-packages/torch/include -I/home/wrc/anaconda3/envs/coco/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/wrc/anaconda3/envs/coco/lib/python3.6/site-packages/torch/include/TH -I/home/wrc/anaconda3/envs/coco/lib/python3.6/site-packages/torch/include/THC -I:/usr/local/cuda-10.1/include -I/home/wrc/anaconda3/envs/coco/include/python3.6m -c mmdet/ops/utils/src/compiling_info.cpp -o build/temp.linux-x86_64-3.6/mmdet/ops/utils/src/compiling_info.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=compiling_info -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
mmdet/ops/utils/src/compiling_info.cpp:3:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
Is `/usr/local/cuda` a symlink to `/usr/local/cuda-10.1`?
What's the output of `echo $LD_LIBRARY_PATH`?

**Comment by yuyijie1995** [comment]
I checked it ，my path is wrong.. I fixed it .

**Comment by wuyxiquanquan** [comment]
> $LD_LIBRARY_PATH

My `/usr/local/cuda` is a symlink to '/usr/local/cuda-10.1', but when I run this `python setup.py develop` also meet this problem
```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
mmdet/ops/utils/src/compiling_info.cpp:3:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
```
```
echo $LD_LIBRARY_PATH
/usr/local/cuda:/usr/local/cuda:/usr/local/cuda:
```

**Comment by CodeXiaoLingYun** [comment]
> > $LD_LIBRARY_PATH
> 
> My `/usr/local/cuda` is a symlink to '/usr/local/cuda-10.1', but when I run this `python setup.py develop` also meet this problem
> 
> ```
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> mmdet/ops/utils/src/compiling_info.cpp:3:10: fatal error: cuda_runtime_api.h: No such file or directory
>  #include <cuda_runtime_api.h>
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> ```
> 
> ```
> echo $LD_LIBRARY_PATH
> /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:
> ```

i also have the same question, i use conda install torch,the cudatoolkit-10.1.243.
but my env
CUDA_HOME=:/usr/local/cuda-9.0
LD_LIBRARY_PATH=:/usr/local/cuda-9.0/lib64
i have not solve this question.   can you solve it?

**Comment by Huanqing1** [comment]
> > > $LD_LIBRARY_PATH
> > 
> > 
> > My `/usr/local/cuda` is a symlink to '/usr/local/cuda-10.1', but when I run this `python setup.py develop` also meet this problem
> > ```
> > cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> > mmdet/ops/utils/src/compiling_info.cpp:3:10: fatal error: cuda_runtime_api.h: No such file or directory
> >  #include <cuda_runtime_api.h>
> >           ^~~~~~~~~~~~~~~~~~~~
> > compilation terminated.
> > error: command 'gcc' failed with exit status 1
> > ```
> > 
> > 
> > ```
> > echo $LD_LIBRARY_PATH
> > /usr/local/cuda:/usr/local/cuda:/usr/local/cuda:
> > ```
> 
> i also have the same question, i use conda install torch,the cudatoolkit-10.1.243.
> but my env
> CUDA_HOME=:/usr/local/cuda-9.0
> LD_LIBRARY_PATH=:/usr/local/cuda-9.0/lib64
> i have not solve this question. can you solve it?

I have the same question. Have you solved it? Can you help me?

**Comment by dzyjjpy** [comment]
**:**/usr/local/cuda-10.0/bin/nvcc -DWITH_CUDA -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include/TH -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/usr/local/include/python3.6m -c mmdet/ops/nms/src/nms_kernel.cu -o build/temp.linux-x86_64-3.6/mmdet/ops/nms/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-10.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1

报错那条指令那里为啥会多一个冒号:?  -I参数也会

**Comment by Huanqing1** [comment]
> **:**/usr/local/cuda-10.0/bin/nvcc -DWITH_CUDA -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include/TH -I/home/jiapy/virtualEnv/mmdet/lib/python3.6/site-packages/torch/include/THC -I:/usr/local/cuda-10.0/include -I/usr/local/include/python3.6m -c mmdet/ops/nms/src/nms_kernel.cu -o build/temp.linux-x86_64-3.6/mmdet/ops/nms/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
> unable to execute ':/usr/local/cuda-10.0/bin/nvcc': No such file or directory
> error: command ':/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1
> 
> 报错那条指令那里为啥会多一个冒号:? -I参数也会
的确是路径问题  我修改路径后就回复正常了 谢谢！

**Comment by McGradyGao** [comment]
#CUDA 
export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda-9.0

I have added the path to compiling_info.cpp
#include </usr/local/cuda-9.0/cuda_runtime_api.h>

If you have a solution please let me know,thank you very much!

**Comment by bufferXia** [comment]
I meet this problem too.
I solve this problem by modify the CUDA PATH:

export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

**Comment by Yonv1943** [comment]
https://stackoverflow.com/questions/64481487/fatal-error-cuda-runtime-api-h-no-such-file-or-directory-when-trying-to-use-cu

Maybe this ↑  stackoverflow can solve this problem?

> Thanks to @Robert Crovella I solved my problem. Turned out I just needed to use `nvidia/cuda/10.0-devel` as base image instead of `nvidia/cuda/10.0-base`
