### ISSUE TITLE
May I become a contributor of MMDetection?

### ISSUE THREAD

**Issue by songyuc** [open-mmlab/mmdetection#1974]
Hi guys,

I am Yucheng Song from Wuhan, China. 
And I want to know if I am able to become a contributor of MMDetection?

Your answer will be appreciated.

**Comment by hellock** [comment]
Of course. Anyone can be a contributor of MMDetection. You can discuss with others in issues and raise PRs to fix or improve it.

**Comment by songyuc** [comment]
Thank you sincerely for your response!
