### ISSUE TITLE
RuntimeError: shape mismatch

### ISSUE THREAD

**Issue by hzby** [open-mmlab/mmdetection#1977]
Checklist

   1. I have searched related issues but cannot get the expected help.
   2. The bug has not been fixed in the latest version.
Describe the bug
    when using command ''./tools/dist_train.sh /home/a123/mmdetection/configs/mask_rcnn_r50_fpn_1x.py 4 --validate'' train mask_rcnn this bug happened.
    RuntimeError: shape mismatch: value tensor of shape [7, 256, 14, 14] cannot be broadcast to indexing result of shape [1, 256, 14, 14]
Reproduction

1. What command or script did you run?
    ./tools/dist_train.sh /home/a123/mmdetection/configs/mask_rcnn_r50_fpn_1x.py 4 --validate
2.Did you make any modifications on the code or config? Did you understand what you have modified?
    I change the epoch number from 12 to 16 and learning rate .
3.What dataset did you use?
    CoCo dataset.
Environment
4.Please run python tools/collect_env.py to collect necessary environment infomation and paste it here.
 sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3: GeForce RTX 2080 Ti
GCC: gcc (GCC) 5.4.0
PyTorch: 1.1.0
PyTorch compiling details: PyTorch built with:
  - GCC 4.9
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.5.1
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=True, USE_NNPACK=True, USE_OPENMP=ON, 

TorchVision: 0.3.0
OpenCV: 4.1.2
MMCV: 0.2.16
MMDetection: 1.0rc1+e032ebb
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0
2.You may add addition that may be helpful for locating the problem, such as

    How you installed PyTorch [e.g., pip, conda, source]
    Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)
    Conda
Error traceback
   Traceback (most recent call last):
  File "./tools/train.py", line 124, in <module>
    main()
  File "./tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/home/a123/mmdetection/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/home/a123/mmdetection/mmdet/apis/train.py", line 272, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/mmcv/runner/runner.py", line 275, in train
    self.call_hook('after_train_iter')
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/mmcv/runner/runner.py", line 231, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/a123/mmdetection/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: shape mismatch: value tensor of shape [7, 256, 14, 14] cannot be broadcast to indexing result of shape [1, 256, 14, 14]

**Comment by hzby** [comment]
Traceback also like that:
Traceback (most recent call last):
  File "./tools/train.py", line 124, in <module>
    main()
  File "./tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/home/a123/mmdetection/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/home/a123/mmdetection/mmdet/apis/train.py", line 272, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/mmcv/runner/runner.py", line 275, in train
    self.call_hook('after_train_iter')
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/mmcv/runner/runner.py", line 231, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/a123/mmdetection/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/a123/.conda/envs/two/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: shape mismatch: value tensor of shape [58, 256, 7, 7] cannot be broadcast to indexing result of shape [1, 256, 7, 7]

**Comment by deloious** [comment]
I faced the same problem ,how did you fixed it? thanks!

**Comment by hzby** [comment]
When I used 3 GPUS to train the model ,this problem disappears.Maybe it's because that one of your 4 GPUS is broken as mine.

**Comment by hzby** [comment]
You  can firstly use one gpu to trying to see if it can work well.

**Comment by deloious** [comment]
Thanks! I trained with one gpu just now ,it still has the same error . I used the nvidia p100 gpu.

**Comment by hzby** [comment]
Did you add argument CUDA_VISIBLE_DEVICES=0,1,2 or 3 to specify which GPU to use as you started trianing?

**Comment by hzby** [comment]
Maybe your GPU 0 is broken,but the others are good.If you don't add that argument ,it will use GPU 0 to train automatically.

**Comment by deloious** [comment]
Thanks ,I trained with the command : python train.py configs/cascade_rcnn_r50_fpn_1x.py --gpus = 1.
Every time I trained with different single gpu.I think my gpu should be fine.But ,I can't figure out what is wrong with my code.Thank you !

**Comment by hzby** [comment]
Finally，I trained with command ：  CUDA_VISIBLE_DEVICES=0,1,2  PORT=29500  ./tools/dist_train.sh configs/cascade_rcnn_r50_fpn_1x.py  3.Then it  was running correctly.

**Comment by deloious** [comment]
OK. I will give a try,thanks!

**Comment by deloious** [comment]
@hzby  Thank you very much! Your way works very well.Thanks again!

**Comment by hzby** [comment]
@deloious You are welcome！

**Comment by sahertariq07** [comment]
Hi! I'm also facing same problem, but I'm running a light model to eval() and running it on CPU. Any suggestions how to fix?
