### ISSUE TITLE
how to save checkpoint durning N batch instead of save once each epoch? 

### ISSUE THREAD

**Issue by haoran1062** [open-mmlab/mmdetection#198]
Because one epoch save once is too easy to overfit(in my case), so I wanna save checkpoint durning like 200 or 500 batch to save once

**Comment by hedes1992** [comment]
> Because one epoch save once is too easy to overfit(in my case), so I wanna save checkpoint durning like 200 or 500 batch to save once

![image](https://user-images.githubusercontent.com/14728901/50339196-c0675c80-0551-11e9-80cc-a6b5ef169dcd.png)
You may need to after_train_iter function for CheckpointHook class
