### ISSUE TITLE
Errors during training: segment fault(core dump)

### ISSUE THREAD

**Issue by fuyuer233** [open-mmlab/mmdetection#1980]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when run `python tools/train.py configs/**` ,errors occur: **segment fault(core dump)**
**Reproduction**
1. What command or script did you run?
`python tools/train.py configs/**`
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Dataset replaced
3. What dataset did you use?
my own dataset
**Environment**

1. Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.
段错误 (核心已转储)
segment fault(core dump)
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
`conda install pytorch=1.1.0 `
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
**Ubuntu 18.0
gcc 5.5/g++ 5.5
py3.7_cuda9.0.176_cudnn7.0.5
conda install pytorch=1.1.0 torchvision=0.3.0 cudatoolkit=10.0 -c pytorch**


**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by fuyuer233** [comment]
Look here and give me some help @hellock

**Comment by hellock** [comment]
Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.

**Comment by fuyuer233** [comment]
run python tools/collect_env.py
it shows段错误 (核心已转储)
segment fault(core dump)

**Comment by fuyuer233** [comment]
maybe cuda9.0 can't match this project @hellock

**Comment by hellock** [comment]
CUDA 9.0 is compatible, as long as you use the corresponding pytorch version.
You can run `tools/collect_env.py` to diagnose the issue.

**Comment by fuyuer233** [comment]
when i run tools/collect_env.py
```
Traceback (most recent call last):
  File "collect_env.py", line 12, in <module>
    from mmdet.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/user/CHENJIE/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/user/CHENJIE/mmdetection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/user/CHENJIE/mmdetection/mmdet/ops/dcn/deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: /home/user/CHENJIE/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

```
i used cuda9.0 ,and fllowed installation steps on pytroch website 
`conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch`
it also can't work  @hellock

**Comment by hellock** [comment]
Almost all the segmentation fault errors I met are caused by the environment. Maybe your environment is messed up and there may be multiple versions of dependencies.
You need to figure out:
1. Your **compiling** gcc
2. Your **compiling** cuda
2. Your **runtime** cuda

Make sure your compiling gcc is 4.9+ and your compiling cuda matches runtime cuda.

**Comment by Sphinxone** [comment]
Do you slove this problem? i have same problem with you
