### ISSUE TITLE
RuntimeError: input image is smaller than kernel (shape_check at mmdet/ops/dcn/src/deform_conv_cuda.cpp:127)

### ISSUE THREAD

**Issue by chen1234520** [open-mmlab/mmdetection#1981]
RuntimeError: input image is smaller than kernel (shape_check at mmdet/ops/dcn/src/deform_conv_cuda.cpp:127)

Who can tell me what this hint means，Thanks！

**Comment by ZwwWayne** [comment]
It seems to be quite clear that ***the input image is smaller than kernel***.

**Comment by kulkarnivishal** [comment]
@hellock any idea how I can handle this ? I'm getting this error on inference

**Comment by kulkarnivishal** [comment]
Ideally one shouldn't have to resize images for inference,  right?

**Comment by DaveCage** [comment]
> Ideally one shouldn't have to resize images for inference, right?

the config "point_feat_channels" might equal to  or lower than the image size,you can resize your image before you train or change the  point_feat_channels  value ,I`ve change the value from 256 to 128 ,and it gives me no warn, but i dont know the other influence

**Comment by Hshuqin** [comment]
> @hellock any idea how I can handle this ? I'm getting this error on inference

Hello, have you solved this problem? ? ? I also encountered this problem while testing.
