### ISSUE TITLE
Will the yolo be supported in the future??

### ISSUE THREAD

**Issue by CRmost** [open-mmlab/mmdetection#1983]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by ZwwWayne** [comment]
Hi @CRmost ,
Thanks for your suggestion, for now, we do not have such a plan. 
We might consider to add it in the future.
PRs are also welcomed!
