### ISSUE TITLE
why i test images but raise assert bboxes.shape[0] == labels.shape[0]

### ISSUE THREAD

**Issue by Meowooo** [open-mmlab/mmdetection#1984]
### my code:
from mmdet.apis import init_detector, inference_detector, show_result
import mmcv
import numpy as np
import pycocotools.mask as maskUtils

config_file = 'model_config/rpn_r50_fpn_1x.py'
checkpoint_file = 'checkpoint/latest.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')

img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_detector(model, img)
show_result(img, result, model.CLASSES)
show_result(img, result, model.CLASSES, out_file='result.jpg')

### error message :
Traceback (most recent call last):
  File "/home/wangai0/Project/home_board/t.py", line 83, in <module>
    show_result(img, result, model.CLASSES)
  File "/home/wangai0/Downloads/mmdetection/mmdet/apis/inference.py", line 179, in show_result
    out_file=out_file)
  File "/home/wangai0/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/visualization/image.py", line 112, in imshow_det_bboxes
    assert bboxes.shape[0] == labels.shape[0]
AssertionError

**Comment by ZwwWayne** [comment]
It means that the boxes and labels have different shapes, which they should have.
Do you do any modifications to the code base?

**Comment by Jungmo** [comment]
same problem in webcam demo. There is no code change (The only thing I changed is the webcam device number to video file path).
I used this checkpoint, rpn_x101_32x4d_fpn_1x_20181218-7e379d26.pth.
I checked that the shape[0] of both bboxes and labels are 2000 and 10000 respectively.
Is there any ideas?
