### ISSUE TITLE
RuntimeError when training FreeAnchor

### ISSUE THREAD

**Issue by ZQ-zz** [open-mmlab/mmdetection#1989]
Runtime error when training freeanchor，I only change the input image size and the config file is ‘coco_retinanet_free_anchor_r50_fpn_test.txt’
when I resume training process from epoch7，it‘s OK and got good results. It seems training process is unstable. I am also training the original FreeAnchor (https://github.com/zhangxiaosong18/FreeAnchor) and got the similar error.

the error message：
2019-12-30 21:07:26,863 - INFO - Epoch [7][7050/7330]	lr: 0.01000, eta: 11:53:03, time: 0.331, data_time: 0.011, memory: 5807, positive_bag_loss: 1.3131, negative_bag_loss: 0.1438, loss: 1.4569
2019-12-30 21:07:43,478 - INFO - Epoch [7][7100/7330]	lr: 0.01000, eta: 11:52:44, time: 0.332, data_time: 0.011, memory: 5807, positive_bag_loss: 1.3113, negative_bag_loss: 0.1462, loss: 1.4574
2019-12-30 21:07:59,918 - INFO - Epoch [7][7150/7330]	lr: 0.01000, eta: 11:52:25, time: 0.329, data_time: 0.011, memory: 5807, positive_bag_loss: 1.3473, negative_bag_loss: 0.1465, loss: 1.4938
/pytorch/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [40376,0,0], thread: [451,0,0] Assertion `*input >= 0. && *input <= 1.` failed.
Traceback (most recent call last):
  File "./tools/train.py", line 124, in <module>
    main()
  File "./tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/home/zz/work/mmdetection/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/home/zz/work/mmdetection/mmdet/apis/train.py", line 272, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv-0.2.15-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv-0.2.15-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 267, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/zz/work/mmdetection/mmdet/apis/train.py", line 101, in batch_processor
    loss, log_vars = parse_losses(losses)
  File "/home/zz/work/mmdetection/mmdet/apis/train.py", line 79, in parse_losses
    log_vars[loss_name] = loss_value.item()
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fda9b741441 in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fda9b740d7a in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13652 (0x7fda997bf652 in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x50 (0x7fda9b731ce0 in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x30facb (0x7fda9a15bacb in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x1420bb (0x7fdadaa520bb in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3c30f4 (0x7fdadacd30f4 in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x3c3141 (0x7fdadacd3141 in /home/zz/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x19aa5e (0x5599a94a1a5e in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #9: <unknown function> + 0xf1b77 (0x5599a93f8b77 in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #10: <unknown function> + 0xf1a07 (0x5599a93f8a07 in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #11: <unknown function> + 0xf1a1d (0x5599a93f8a1d in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #12: <unknown function> + 0xf1a1d (0x5599a93f8a1d in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #13: <unknown function> + 0xf1a1d (0x5599a93f8a1d in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #14: <unknown function> + 0xf1a1d (0x5599a93f8a1d in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #15: <unknown function> + 0xf1a1d (0x5599a93f8a1d in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #16: <unknown function> + 0xf1a1d (0x5599a93f8a1d in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #17: <unknown function> + 0xf1a1d (0x5599a93f8a1d in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #18: PyDict_SetItem + 0x3da (0x5599a943f63a in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #19: PyDict_SetItemString + 0x4f (0x5599a944665f in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #20: PyImport_Cleanup + 0x99 (0x5599a94abd89 in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #21: Py_FinalizeEx + 0x61 (0x5599a9516231 in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #22: Py_Main + 0x35e (0x5599a952057e in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #23: main + 0xee (0x5599a93ea88e in /home/zz/anaconda3/envs/mmdetection/bin/python)
frame #24: __libc_start_main + 0xe7 (0x7fdaf283ab97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #25: <unknown function> + 0x1c3160 (0x5599a94ca160 in /home/zz/anaconda3/envs/mmdetection/bin/python)

[coco_retinanet_free_anchor_r50_fpn_test.txt](https://github.com/open-mmlab/mmdetection/files/4068937/coco_retinanet_free_anchor_r50_fpn_test.txt)

**Comment by hellock** [comment]
If you also encountered similar problems while using the original maskrcnn-benchmark implementation released by the author, then it is unlikely to be related to the codebase itself. Thus we cannot help and you need to figure it out.

**Comment by YAOYI626** [comment]
Encountered the same problem with FreeAnchor. I trained FreeAnchor model for thousands of times and nothing happens except this time. It's super strange.

`/opt/conda/conda-bld/pytorch_1579040055865/work/aten/src/THCUNN/BCECriterion.cu:57: void bce_updateOutput_no_reduce_functor<Dtype, Acctype>::operator()(const Dtype *, const Dtype *, Dtype *) [with Dtype = float, Acctype = float]: block: [21040,0,0], thread: [115,0,0] Assertion `*input >= 0. && *input <= 1.` failed.`
