### ISSUE TITLE
what's the mean of img_metas

### ISSUE THREAD

**Issue by hust-kevin** [open-mmlab/mmdetection#199]
![image](https://user-images.githubusercontent.com/23699630/50345470-2e1f8280-056a-11e9-844c-d652a1fc6b70.png)

I want's know the mean of img_metas, but I don't know where callback the forward_train() function, can you tell me where is the code of forward propagation

**Comment by hellock** [comment]
1. `img_meta` or `img_metas` are used to keep some information of images, see [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L199) for details.
2. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L78) to see how the forward method is called.

**Comment by hust-kevin** [comment]
thanks, I have another question,
![image](https://user-images.githubusercontent.com/23699630/50375632-91c5b080-063b-11e9-9bf3-583432ceb9b3.png)
train_dataset[i] is a dict,like {'gt_labels': xx, 'gt_bboxes':xx ,...} 

![image](https://user-images.githubusercontent.com/23699630/50375651-ecf7a300-063b-11e9-87fa-93bc356a740b.png)

so the batch is a list of dict,like [{'gt_labels': xx, 'gt_bboxes':xx ,...},{xx},]  batch[0] would be a dict,
why would batch[0] be a DC_type?

**Comment by hust-kevin** [comment]
Hi, I have another question, [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_target.py#L126) the pos_inds  is the positive anchor index to valid anchor, may it should map to origin anchor? like [this?](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_target.py#L153)

**Comment by hellock** [comment]
Thanks! `pos_inds` is only used for computing the number of pos anchors, see [L64](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_target.py#L64), but this may be a potential bug if it is used somewhere else.
