### ISSUE TITLE
Is there a function that maps one point back to the position on the feature map?

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#1990]
I noticed that there is a function get_points_single( ) in fcos_head.py that maps the positions on multi-level feature maps to the points on the image plane. I was wondering if there is an existing 'inverse' function that can map the point on the image plane to the position on the feature map? 
Thanks.

**Comment by ZwwWayne** [comment]
Hi @hyz-xmaster ,
It seems that the MMDetection does not implement this. The implementation should not be so hard since the mapping from the feature map to the image plane is already implemented.
