### ISSUE TITLE
hi, can you make sure code below need to change, or it just my enviorment cause.

### ISSUE THREAD

**Issue by goldlee** [open-mmlab/mmdetection#2000]
In file mmdet/core/bbox/sampler/ohem_sample.py at line 46:

_, topk_loss_inds = loss.topk(num_expected)

when I do not change, just add ohem_sample in config, it error out  like list:
RuntimeError: invalid argument 2: k not in range for dimension
 so i debug in it and search for the func topk
i modify it like this
_, topk_loss_inds = loss.topk(num_expected, dim=0)

it runs well, so i just confuse,and make the issue.

thanks, best wish.

**Comment by ZwwWayne** [comment]
Please use `Error Template` to indicate other modifications to the code base and the environment.

From the doc of [Topk](https://pytorch.org/docs/1.3.0/torch.html#torch.topk), it says `If dim is not given, the last dimension of the input is chosen`. So setting `dim=0` might be a quick fix but the key reason is somewhere else. `k not in range for dimension` seems to mean `num_expected` is not in the range in the last dimension of loss.

**Comment by goldlee** [comment]
> Please use `Error Template` to indicate other modifications to the code base and the environment.
> 
> From the doc of [Topk](https://pytorch.org/docs/1.3.0/torch.html#torch.topk), it says `If dim is not given, the last dimension of the input is chosen`. So setting `dim=0` might be a quick fix but the key reason is somewhere else. `k not in range for dimension` seems to mean `num_expected` is not in the range in the last dimension of loss.

Thanks for you reply, I modify the code this days, so I cannot offer the same scene origin.
Anyway, thank you very much, maybe it's my fault, I'll check it safely!
