### ISSUE TITLE
How to implement SWA（Stochastic Weight Averaging）in mmdetection？

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#2001]
just as above

**Comment by ZwwWayne** [comment]
You can implement it [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L172) by importing the SWA since it is already implemented in `[torchcontrib](https://github.com/pytorch/contrib)` as indicated by the [blog](https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/).

**Comment by zr526799544** [comment]
> You can implement it [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L172) by importing the SWA since it is already implemented in [torchcontrib](https://github.com/pytorch/contrib) as indicated by the [blog](https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/).
follow the blog I find it seems that I need add opt.swap_swa_sgd() at the end of training before save the model. so that it seems I have to motify the Runner in mmcv. But It doesn't work. Could you give me some advise?

**Comment by ZwwWayne** [comment]
By saying **it does not work** you mean? Maybe the SWA could not improve the detection performance or maybe your implementation is not right. I am afraid that I cannot do much help here.

**Comment by zr526799544** [comment]
> By saying **it does not work** you mean what? Maybe the SWA could not improve the detection performance or maybe your implementation is not right. I am afraid that I cannot do much help here.

My implementation is not right, I can not find a exactly right hook time to insert ‘’opt.swap_swa_sgd()‘’. I can not find end_of_train in /mmcv/runner/hooks/hook.py

**Comment by ZwwWayne** [comment]
> > By saying **it does not work** you mean what? Maybe the SWA could not improve the detection performance or maybe your implementation is not right. I am afraid that I cannot do much help here.
> 
> My implementation is not right, I can not find a exactly right hook time to insert ‘’opt.swap_swa_sgd()‘’. I can not find end_of_train in /mmcv/runner/hooks/hook.py

For now, maybe you can use `every_n_epochs`, and set the epochs manually, for example, set the interval to be 12, and train the model for 12 epoch.

**Comment by zr526799544** [comment]
> > > By saying **it does not work** you mean what? Maybe the SWA could not improve the detection performance or maybe your implementation is not right. I am afraid that I cannot do much help here.
> > 
> > 
> > My implementation is not right, I can not find a exactly right hook time to insert ‘’opt.swap_swa_sgd()‘’. I can not find end_of_train in /mmcv/runner/hooks/hook.py
> 
> For now, maybe you can use `every_n_epochs`, and set the epochs manually, for example, set the interval to be 12, and train the model for 12 epoch.

Thanks,but now I add it in the runner.save_checkpoint().I use it like this:
        if self.epoch + 1 == 24:
            self.optimizer.swap_swa_sgd()
        save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
Will it raise any unexpected error？

**Comment by feiyangsuo** [comment]
> You can implement it [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L172) by importing the SWA since it is already implemented in [torchcontrib](https://github.com/pytorch/contrib) as indicated by the [blog](https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/).

Hi, SWA in this blog seems executed during training, while according to the SWA paper, it can be done independently. Wonder how to just SWA several models' weights if they were already trained?

**Comment by ZwwWayne** [comment]
> > You can implement it [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L172) by importing the SWA since it is already implemented in [torchcontrib](https://github.com/pytorch/contrib) as indicated by the [blog](https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/).
> 
> Hi, SWA in this blog seems executed during training, while according to the SWA paper, it can be done independently. Wonder how to just SWA several models' weights if they were already trained?

Then you need to check the implementation and use the checkpoint saved in the training process.

**Comment by sankin97** [comment]
> > > > By saying **it does not work** you mean what? Maybe the SWA could not improve the detection performance or maybe your implementation is not right. I am afraid that I cannot do much help here.
> > > 
> > > 
> > > My implementation is not right, I can not find a exactly right hook time to insert ‘’opt.swap_swa_sgd()‘’. I can not find end_of_train in /mmcv/runner/hooks/hook.py
> > 
> > 
> > For now, maybe you can use `every_n_epochs`, and set the epochs manually, for example, set the interval to be 12, and train the model for 12 epoch.
> 
> Thanks,but now I add it in the runner.save_checkpoint().I use it like this:
> if self.epoch + 1 == 24:
> self.optimizer.swap_swa_sgd()
> save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
> Will it raise any unexpected error？

Have you successfully import SWA in mmdetection? I have the same problem.

**Comment by zhaoxin111** [comment]
> > > > By saying **it does not work** you mean what? Maybe the SWA could not improve the detection performance or maybe your implementation is not right. I am afraid that I cannot do much help here.
> > > 
> > > 
> > > My implementation is not right, I can not find a exactly right hook time to insert ‘’opt.swap_swa_sgd()‘’. I can not find end_of_train in /mmcv/runner/hooks/hook.py
> > 
> > 
> > For now, maybe you can use `every_n_epochs`, and set the epochs manually, for example, set the interval to be 12, and train the model for 12 epoch.
> 
> Thanks,but now I add it in the runner.save_checkpoint().I use it like this:
> if self.epoch + 1 == 24:
> self.optimizer.swap_swa_sgd()
> save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
> Will it raise any unexpected error？

BN also needs to be updated after training.
opt.bn_update(train_loader, model)
