### ISSUE TITLE
Error nvcc fatal   : Unsupported gpu architecture 'compute_61' when running setup.py

### ISSUE THREAD

**Issue by HUNGLiquid** [open-mmlab/mmdetection#2002]
I have searched related issues but cannot get the expected help.

**Reproduction**
When I try to run this script: "python setup.py develop"
Before that requitement.txt has been satisfied.

**Environment**
# packages in environment at /home/sven/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
addict                    2.2.1                    pypi_0    pypi
albumentations            0.4.3                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2019.11.27                    0    anaconda
certifi                   2019.11.28               py37_0    anaconda
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.14          py37he6710b0_0    anaconda
decorator                 4.4.1                    pypi_0    pypi
freetype                  2.9.1                h8a8886c_1  
idna                      2.8                      pypi_0    pypi
imagecorruptions          1.1.0                    pypi_0    pypi
imageio                   2.6.1                    pypi_0    pypi
imgaug                    0.2.6                    pypi_0    pypi
intel-openmp              2019.4                      243  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
matplotlib                3.1.2                    pypi_0    pypi
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
mmcv                      0.2.16                   pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
networkx                  2.4                      pypi_0    pypi
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_0  
olefile                   0.46                     py37_0  
opencv-python             4.1.2.30                 pypi_0    pypi
opencv-python-headless    4.1.2.30                 pypi_0    pypi
openssl                   1.1.1                h7b6447c_0    anaconda
pillow                    7.0.0            py37hb39fc2d_0  
pip                       19.3.1                   py37_0  
pycocotools               2.0.0                    pypi_0    pypi
pyparsing                 2.4.6                    pypi_0    pypi
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3                      pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                44.0.0                   py37_0  
six                       1.13.0                   py37_0  
sqlite                    3.30.1               h7b6447c_0  
terminaltables            3.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
torchvision               0.5.0                py37_cu101    pytorch
urllib3                   1.25.7                   pypi_0    pypi
wheel                     0.33.6                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+

**Error traceback**
I have this error:

    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    error: command '/usr/bin/nvcc' failed with exit status 1

**Comment by yan-roo** [comment]
1. Make sure your have install CUDA and nvidia driver
2. Check your variable PATH
export PATH="/usr/local/cuda-10.2/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH"
export CUDA_HOME="/usr/local/cuda-10.2"
