### ISSUE TITLE
执行python setup.py develop出现如下错误

### ISSUE THREAD

**Issue by Soulempty** [open-mmlab/mmdetection#2009]
Compiling mmdet/ops/nms/src/soft_nms_cpu.pyx because it changed.
[1/1] Cythonizing mmdet/ops/nms/src/soft_nms_cpu.pyx
running develop
running egg_info
creating mmdet.egg-info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
writing manifest file 'mmdet.egg-info/SOURCES.txt'
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.utils.compiling_info' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/mmdet
creating build/temp.linux-x86_64-3.6/mmdet/ops
creating build/temp.linux-x86_64-3.6/mmdet/ops/utils
creating build/temp.linux-x86_64-3.6/mmdet/ops/utils/src
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/chao/anaconda3/lib/python3.6/site-packages/torch/include -I/home/chao/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/chao/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/chao/anaconda3/lib/python3.6/site-packages/torch/include/THC -I:/usr/local/cuda-9.0:/usr/local/cuda:/usr/local/cuda-9.0:/usr/local/cuda-9.0:/usr/local/cuda-9.0/include -I/home/chao/anaconda3/include/python3.6m -c mmdet/ops/utils/src/compiling_info.cpp -o build/temp.linux-x86_64-3.6/mmdet/ops/utils/src/compiling_info.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=compiling_info -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
mmdet/ops/utils/src/compiling_info.cpp:3:30: fatal error: cuda_runtime_api.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
感谢回复此问题

**Comment by heartInsert** [comment]
Why can't you  speak in English ?

**Comment by hellock** [comment]
Please use English or English&Chinese for issues.

You did not install CUDA.

**Comment by CodeXiaoLingYun** [comment]
i hava the same question.can you solve it?

**Comment by hujinda** [comment]
gcc版本过低

**Comment by dzyjjpy** [comment]
@hellock  Hi ,我使用virtualenv创建的虚拟环境，也遇到这个问题，
python3.6.8
cuda 10.0 (nvcc -V也能显示10.0版本)
pytorch 1.2
torchvision0.4.0
请问有可能是cuda路径没有设置对吗？ 试过export添加，没用

**Comment by dzyjjpy** [comment]
我在官网下载的源码，想安装mmdetection1.2;
cuda在其它code base中都是可以使用的，训练测试都没问题。
torch.cuda.is_available() 也是True, @hellock 帮忙看下具体是什么问题。

(mmdet) jiapy@adminroot:~/workspace/mmdetection_1.2$ echo $LD_LIBRARY_PATH
:/usr/local/openssl/lib:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/

**Comment by dzyjjpy** [comment]
> Please use English or English&Chinese for issues.
> 
> You did not install CUDA or the path is incorrect.

最好在readme里面加一下 cuda路径设置
