### ISSUE TITLE
How to train with pure background images?

### ISSUE THREAD

**Issue by PerryL7s** [open-mmlab/mmdetection#2014]
I noticed that #1531 added support for training with images without gt annotations, and I believe that there must be a relative switch like `skip_img_without_anno` or something else in training pipeline so that one could easily determine whether to filter out background images during training, but I didn't find it anywhere. Pure background images have been dropped by default during training. Could anyone help and tell me how to set the configuration, or modify the codes if necessary, in order to let pure background images be counted during training? Many thanks!

**Comment by hellock** [comment]
If you are using COCO dataset, you need to set `filter_empty_gt = False`. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L44) and [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L52) for implementations.

**Comment by PerryL7s** [comment]
It works. Thank you.

**Comment by clw5180** [comment]
> If you are using COCO dataset, you need to set `filter_empty_gt = False`. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L44) and [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L52) for implementations.

Dear @hellock ,  I really want to ask you a question that whether adding pure background images can actually improve the precision ? And I found in practice the mAP often drops, have you ever done similar experiment ? Thanks a lot!
