### ISSUE TITLE
How to add senet to this framework?  I met an error when adding senet, can you tell me how to correctly add senet 50 to this framework? 

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#2016]
I tried to add the code of senet below to the framework, but I encountered the following error
the net is :
https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/senet.py#L18

the err is :
File "/home/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
return obj_cls(**args)
File "/home/mmdetection/mmdet/models/backbones/senet.py", line 292, in init
downsample_padding=0
File "/home/mmdetection/mmdet/models/backbones/senet.py", line 331, in _make_layer
if stride != 1 or self.inplanes != planes * block.expansion:
AttributeError: 'str' object has no attribute 'expansion'
 How to solve it

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
