### ISSUE TITLE
UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead

### ISSUE THREAD

**Issue by Alibhji** [open-mmlab/mmdetection#2017]
Hello,
I have installed:
Pytorch 1.4.0
cuda: 10.1

after running:
python3 tools/train.py   ./configs/ssd300_coco.py

Training will be started but with this warning, Is there any Idea to remove it?

2020-01-24 18:31:56,041 - INFO - Start running, host: ali@ali-ubt, work_dir: /home/ali/00_2020/mmdetection/work_dirs/ssd300_coco
2020-01-24 18:31:56,041 - INFO - workflow: [('train', 1)], max: 24 epochs
**/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.**

**Comment by ZwwWayne** [comment]
A first guess is [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_target.py#L162), for now, you can try to remove the `.type(torch.uint8)` and also set related variables to be bool somewhere.
Thanks for your kind notification, we will also fix this warning in the future.

**Comment by CMobley7** [comment]
I can confirm this issue. I've tried PyTorch versions from 1.4 to 1.2 and still receive the error.

**Comment by CMobley7** [comment]
When this change is implemented, can it be back-ported into 1.0?

**Comment by ZwwWayne** [comment]
This change should be independent, so you can fix it in your environment.

**Comment by prateek-77** [comment]
You can add this in train.py while training (to ignore the warning):
```
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
```

**Comment by EvenStrangest** [comment]
The below task also produces this error.

```
root@1bac3eaaf785:/mmdetection# python tools/train.py configs/htc/htc_x101_64x4d_fpn_20e_16gpu.py
2020-03-10 14:49:23,916 - mmdet - INFO - Environment info:
------------------------------------------------------------
TorchVision: 0.4.1a0+d94043a
OpenCV: 4.2.0
MMCV: 0.3.2
MMDetection: 1.1.0+e08a1ee
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1
```

**Comment by Holylili** [comment]
I have also met the same problem, and I can't solve by using the online solutions. If are there anything new methods to solve this problem, please tell me!

**Comment by mhiyer** [comment]
Change torch.ByteTensor->torch.BoolTensor

**Comment by Holylili** [comment]
> Change torch.ByteTensor->torch.BoolTensor

Thank you!

**Comment by wulala-max** [comment]
> > Change torch.ByteTensor->torch.BoolTensor
> 
> Thank you!

could tell me more clearly?change  torch.ByteTensor->torch.BoolTensor is done in which file?

**Comment by wulala-max** [comment]
> > Change torch.ByteTensor->torch.BoolTensor
> 
> Thank you!

thanks!

**Comment by wulala-max** [comment]
> Change torch.ByteTensor->torch.BoolTensor

could you tell me more clearly? make this change in which file?thank you!

**Comment by wulala-max** [comment]
please help me,when I train,I encounter pdb and stop,erro information is below.How can I continue?

2022-04-01 22:13:34,296 - INFO - workflow: [('train', 1)], max: 12 epochs
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
> /root/desktop/mmdetection_RGBT/mmdet/models/detectors/faster_rcnn_mydata.py(393)forward_train()
-> if self.with_shared_head:
(Pdb)

**Comment by Tracy-git** [comment]
> 

`maybe u could convert tensor type like : xx.bool at the location of the error（warning）
