### ISSUE TITLE
How did you set target_stds for regression?

### ISSUE THREAD

**Issue by kemaloksuz** [open-mmlab/mmdetection#2018]
Hi, thank you for this repo, I think many people are extensively using this. My question is about target_stds for regression. How did you set them? 

For some networks, like RetinaNet they are all 1s, but for some like R-CNN you have [0.1, 0.1,0.2, 0.2]. And for different Cascade levels you have a different target_stds (down to target_stds=[0.033, 0.033, 0.067, 0.067]). 

Thanks in advance

**Comment by ZwwWayne** [comment]
This is a practical convention. We adopt these settings from the authors' implementation in [Cascade R-CNN](https://github.com/zhaoweicai/Detectron-Cascade-RCNN) and [Detectron](https://github.com/facebookresearch/Detectron).

**Comment by kemaloksuz** [comment]
Ok. I just wondered whether you employed some method to derive such statistics by yourself. Thank you.
