### ISSUE TITLE
Cascade mask rcnn visualization error

### ISSUE THREAD

**Issue by Curry1201** [open-mmlab/mmdetection#202]
An error occurred while executing the visualization code.
python3 tools/test.py configs/cascade_mask_rcnn_r50_fpn_1x.py checkpoints/cascade\ mask\ r-cnn/cascade_mask_rcnn_r50_fpn_1x_20181123-88b170c9.pth --show

power@ubuntu:~/mmdetection$ python3 tools/test.py configs/cascade_mask_rcnn_r50_fpn_1x.py checkpoints/cascade\ mask\ r-cnn/cascade_mask_rcnn_r50_fpn_1x_20181123-88b170c9.pth --show
loading annotations into memory...
Done (t=0.46s)
creating index...
index created!
[                              ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 124, in <module>
    main()
  File "tools/test.py", line 86, in main
    outputs = single_test(model, data_loader, args.show)
  File "tools/test.py", line 26, in single_test
    dataset.CLASSES)
TypeError: show_result() takes 4 positional arguments but 5 were given

**Comment by hellock** [comment]
Thanks for reporting the bug! You may need to modify this [line](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L26) to `dataset=dataset.CLASSES`.
