### ISSUE TITLE
Gradient cumulative

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#2021]
Does mmdetection have the function of gradient cumulative?

**Comment by ZwwWayne** [comment]
Do you mean to run forward and calculate losses for several times but only backward once?

**Comment by yuyijie1995** [comment]
Yes




| |
俞依杰
|
|
邮箱：13588280094@163.com
|

签名由 网易邮箱大师 定制

On 01/27/2020 23:33, Wenwei Zhang wrote:

Do you mean to run forward and calculate losses for several times but only backward once?

**Comment by ZwwWayne** [comment]
Currently, MMDetection and MMCV seem to do not implement it. PRs are welcomed.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmcv/issues/190
