### ISSUE TITLE
‘open VIDEOIO ERROR’ when running demo

### ISSUE THREAD

**Issue by ChutianXu0922** [open-mmlab/mmdetection#2022]
Hello! Thanks for your excellent project!

I came across an error when I ran demo/webcam_demo.py. It raises an 'open VIDEOIO ERROR' as I run it with docker.

The order is:

`sudo docker run --rm -it -v $(pwd):/$(pwd) -w $(pwd) --name cascademask cascademask python demo/webcam_demo.py configs/mask_rcnn_r50_fpn_1x.py checkpoint/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth`

And it shows:
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (802) open VIDEOIO ERROR: V4L: can't open camera by index 0
Press "Esc", "q" or "Q" to exit.
Traceback (most recent call last):
  File "demo/webcam_demo.py", line 44, in <module>
    main()
  File "demo/webcam_demo.py", line 33, in main
    result = inference_detector(model, img)
  File "/mmdetection/mmdet/apis/inference.py", line 82, in inference_detector
    data = test_pipeline(data)
  File "/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/mmdetection/mmdet/apis/inference.py", line 56, in __call__
    img = mmcv.imread(results['img'])
  File "/opt/conda/lib/python3.6/site-packages/mmcv/image/io.py", line 45, in imread
    raise TypeError('"img" must be a numpy array or a filename')
TypeError: "img" must be a numpy array or a filename

I did not find anyone with the same problem in this project. However, I found one in the mask-rcnn project [here](https://github.com/facebookresearch/maskrcnn-benchmark/issues/203), yet I did not manage to solve my problem with the solution in that project.

I am very much appreciated with any help. Thank you!

**Comment by hellock** [comment]
https://stackoverflow.com/questions/44852484/access-webcam-using-opencv-python-in-docker

**Comment by ChutianXu0922** [comment]
> https://stackoverflow.com/questions/44852484/access-webcam-using-opencv-python-in-docker

Thank you very much. I am trying to solve it with your hint.

**Comment by ChutianXu0922** [comment]
> https://stackoverflow.com/questions/44852484/access-webcam-using-opencv-python-in-docker

I'm sorry, but although I set `/dev/video0:/dev/video0` or `--device=/dev/video0`, it does not go well.

**Comment by brmarkus** [comment]
Can you check, whether the camera device(s) exist?
Can you check access rights and to which group the video device(s) belong to?

For example:

$> ls -al /dev/video*
crw-rw----+ 1 root video 81, 0 Jan 28 09:10 /dev/video0

Is your user part of the video group?

Can you check (from your HOST system and/or within your Docker container) the driver, formats, resolutions, please?

$> v4l2-ctl --info
$> v4l2-ctl --list-formats
$> v4l2-ctl --all

You might see a special driver being used or required (e.g. the UVC kernel open not set and and missing kernel driver).
Or your camera's default stream (the first entry) is in an "exotic" resolution and color-format and codec, which might not be installed within the Docker or on HOST-side.

Can you maybe try another USB_webcam, e.g. Logitech C920? That is "old enough" and uses "standards".

Can you try to e.g. use a gstreamer command line to simply test, whether the "camera subsystem" and the codecs are in place (e.g. OpenCV uses gstreamer, ffmpeg or v4l2 to process the camera stream), e.g.:

gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw,format=YUY2' ! videoconvert ! autovideosink

**Comment by ChutianXu0922** [comment]
> Can you check, whether the camera device(s) exist?
> Can you check access rights and to which group the video device(s) belong to?
> 
> For example:
> 
> $> ls -al /dev/video*
> crw-rw----+ 1 root video 81, 0 Jan 28 09:10 /dev/video0
> 
> Is your user part of the video group?
> 
> Can you check (from your HOST system and/or within your Docker container) the driver, formats, resolutions, please?
> 
> $> v4l2-ctl --info
> $> v4l2-ctl --list-formats
> $> v4l2-ctl --all
> 
> You might see a special driver being used or required (e.g. the UVC kernel open not set and and missing kernel driver).
> Or your camera's default stream (the first entry) is in an "exotic" resolution and color-format and codec, which might not be installed within the Docker or on HOST-side.
> 
> Can you maybe try another USB_webcam, e.g. Logitech C920? That is "old enough" and uses "standards".
> 
> Can you try to e.g. use a gstreamer command line to simply test, whether the "camera subsystem" and the codecs are in place (e.g. OpenCV uses gstreamer, ffmpeg or v4l2 to process the camera stream), e.g.:
> 
> gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw,format=YUY2' ! videoconvert ! autovideosink

Thank you very much for your detailed reply. I am going to check them.

**Comment by ChutianXu0922** [comment]
> Can you check, whether the camera device(s) exist?
> Can you check access rights and to which group the video device(s) belong to?
> 
> For example:
> 
> $> ls -al /dev/video*
> crw-rw----+ 1 root video 81, 0 Jan 28 09:10 /dev/video0
> 
> Is your user part of the video group?
> 
> Can you check (from your HOST system and/or within your Docker container) the driver, formats, resolutions, please?
> 
> $> v4l2-ctl --info
> $> v4l2-ctl --list-formats
> $> v4l2-ctl --all
> 
> You might see a special driver being used or required (e.g. the UVC kernel open not set and and missing kernel driver).
> Or your camera's default stream (the first entry) is in an "exotic" resolution and color-format and codec, which might not be installed within the Docker or on HOST-side.
> 
> Can you maybe try another USB_webcam, e.g. Logitech C920? That is "old enough" and uses "standards".
> 
> Can you try to e.g. use a gstreamer command line to simply test, whether the "camera subsystem" and the codecs are in place (e.g. OpenCV uses gstreamer, ffmpeg or v4l2 to process the camera stream), e.g.:
> 
> gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw,format=YUY2' ! videoconvert ! autovideosink

Yes, you are right. I made a mistake that my webcam could not work in server. The file works well when I run it in local directory.

Thank you very much for your help!
