### ISSUE TITLE
Duplicated weight initialization 

### ISSUE THREAD

**Issue by whikwon** [open-mmlab/mmdetection#2025]
I can see `init_weights` method in both `ConvModule` and `FPN`. 

Is there any specific reason doing implemented in this way? 

When `Conv2d` modules are initialized twice, do the parameters in module not change?

**Comment by hellock** [comment]
Yes ConvModule has its default initialization, and we need to reinitialize it if we want to adopt a different initialization method, such as in FPN.

**Comment by whikwon** [comment]
Thank you. I asked you because I found initial losses were different between with/without ConvModule's initialization.
