### ISSUE TITLE
Different map result after 'Encapsulate DCN into a ConvModule & Conv_layers'

### ISSUE THREAD

**Issue by TimothyZero** [open-mmlab/mmdetection#2027]
I have trained the same dataset with two version of dcn config:
1. previous version (both config and resnet.py): 
dcn=dict(modulated=False, deformable_groups=1, fallback_on_stride=False)
result is 0.64
2. latest version:
dcn=dict(type='DCN', deformable_groups=1, fallback_on_stride=False)
result is 0.4+

I'm not sure if there has a problem in ConvModule, but have you retrain your model based on latest config?

**Comment by hellock** [comment]
Yes we retrained related models and got the same results before this PR was merged.

**Comment by TimothyZero** [comment]
Thank you!
