### ISSUE TITLE
when use OHEMSampler and FocalLoss，RuntimeError:

### ISSUE THREAD

**Issue by zwenc** [open-mmlab/mmdetection#2036]
raceback (most recent call last):
  File "/home/w/Desktop/TC/mmdetection/mmdet/core/bbox/samplers/ohem_sampler.py", line 46, in hard_mining
    _, topk_loss_inds = loss.topk(num_expected)
RuntimeError: invalid argument 5: k not in range for dimension at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/generic/THCTensorTopK.cu:23

code download at 2020.01.10

**Comment by zwenc** [comment]
but only use FocalLoss or OHEMSampler ,no error

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by Guangjun-A** [comment]
I meet this problem too.
