### ISSUE TITLE
speed up the preprocessing of image during testing

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#2037]
Hi, could you tell me where is the source code for image preprocessing (\eg, resize, normalization) in the testing process? Basically I'd like to speed up the preprocessing by executing it in GPU instead of CPU. I thought it is on **dataLoader**, but I did not find it. thanks!

**Comment by hellock** [comment]
Image preprocessing is done by the [data pipeline](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_fpn_1x.py#L115-L129), and you can find corresponding implementations in `mmdet/datasets/pipelines`.

**Comment by shanggdlk** [comment]
> Image preprocessing is done by the [data pipeline](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_fpn_1x.py#L115-L129), and you can find corresponding implementations in `mmdet/datasets/pipelines`.

Thank you for your reply. A quick question, if I modify mmdet/dataset/transforms.py, e.g., I reimplement the resize function for example, do I need to recompile the code?
