### ISSUE TITLE
How to use the custom optimizer?

### ISSUE THREAD

**Issue by AlanJie** [open-mmlab/mmdetection#2041]
I want to customize the optimizer(RAdam etc.), but I find that the optimizer in mmdetection is imported from `torch.optim`(only a few of optimizer are implemented),  can you provide an official example to do this? Thank you

**Comment by hellock** [comment]
We will introduce an optimizer registry like dataset or model registry to support customizing the optimizer. As a walkaround now, you may just modify [this line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L190) and get your own optimizer class.

**Comment by AlanJie** [comment]
OK, I'll try, thanks

**Comment by hiyyg** [comment]
It seems the custom optimizer documentation is out of date. How to use custom optimizer after the cleaning of optimizer code?

**Comment by hiyyg** [comment]
I figured out using this way:
```
from mmcv.runner.optimizer import build_optimizer, OPTIMIZERS
from my_optimizer import MyOptimizer
OPTIMIZERS.register_module()(MyOptimizer)

optim_cfg = dict(type="MyOptimizer", lr=0.001)
optimizer = build_optimizer(model, optim_cfg)
```
