### ISSUE TITLE
How do I make a Faster RCNN config file, with resnet101 backbone, without fpn feature.

### ISSUE THREAD

**Issue by Siddsouza19** [open-mmlab/mmdetection#2045]
I'm trying to train my model with a Faster RCNN config, using a resnet101 backbone, without using fpn. In the config files, "faster_rcnn_r50_caffe_c4_1x.py" is provided, but this is resnet 50 without fpn. I want it for resnet 101.

**Comment by ZwwWayne** [comment]
By changing the `depth=50` of backbone to `depth=101`.

**Comment by breezelj** [comment]
if I use "faster_rcnn_r50_fpn_1x.py", how can I modify it to train faster rcnn without fpn? thanks
