### ISSUE TITLE
for retinanet config, how I sets network input size?

### ISSUE THREAD

**Issue by zgsxwsdxg** [open-mmlab/mmdetection#205]

**Comment by hellock** [comment]
You can find it [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/retinanet_r50_fpn_1x.py#L63).

**Comment by zgsxwsdxg** [comment]
@hellock Hello, img_scale=(1333, 800) 就是网络训练归一化尺寸么？谢谢
