### ISSUE TITLE
A  question  about  cascadeRcnn  stage_loss_weights 

### ISSUE THREAD

**Issue by heartInsert** [open-mmlab/mmdetection#2050]
Hi ,  everyone   , I  notice that  in  cascadeRcnn  we  set   `stage_loss_weights=[1, 0.5, 0.25]` ,  but  as  we  know ,  in  predict  time ,   the  result   will   generate   by   the  last  stage   at  last   ,   why  should    not   we  enhance  the  ability  in  the  second   stage  and   the  third  stage  ?Set  `stage_loss_weights=[1, 1,1]` .

I  stuck   in  this  issue  for  so  many  days  ,  thanks  for   whoever   reply  for  this .

**Comment by ZwwWayne** [comment]
This is a tuned hyper-parameter, you could try by yourself and compare the performance.
Setting stage_loss_weights=[1, 1,1] might not be a good option because the later stages' input is better the former stages' inputs.
