### ISSUE TITLE
the training process may get into stuck 

### ISSUE THREAD

**Issue by wwetnaroh** [open-mmlab/mmdetection#2053]
after I enter python tools/train.py configs/libra_rcnn/libra_faster_rcnn_x101_64x4d_fpn_1x_copy.py
it shows
INFO - workflow: [('train', 1)], max: 20 epochs
and get stuck

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.
This bug could caused by many reasons, we cannot do much help here without information required in the `Error Template`.
