### ISSUE TITLE
how to  train faster rcnn without fpn

### ISSUE THREAD

**Issue by breezelj** [open-mmlab/mmdetection#2054]
if I use "faster_rcnn_r50_fpn_1x.py", how can I modify it to train faster rcnn without fpn? thanks

**Comment by ZwwWayne** [comment]
You can check this [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_caffe_c4_1x.py).

**Comment by breezelj** [comment]
thanks very much
