### ISSUE TITLE
Imbalanced memory when distributed training on 8 V100

### ISSUE THREAD

**Issue by backseason** [open-mmlab/mmdetection#206]
Hi, when distributed training on an 8 V100 server, it'll occurs an imbalanced memory usage: gpu_id0 allocates about twice the size of other gpu's memory.
Many thanks!
![image](https://user-images.githubusercontent.com/7400760/50421341-0fc2cb00-0879-11e9-921e-289ea847a934.png)

**Comment by hellock** [comment]
Could you show your training script? Maybe you are not using distributed training?

**Comment by backseason** [comment]
It's caused by pretrained models. Thanks a lot!

**Comment by cizhenshi** [comment]
I face to the same problem, how do you solve it?

**Comment by dongsheng18** [comment]
I also face to the same problem, how do you solve it?

**Comment by cizhenshi** [comment]
> I also face to the same problem, how do you solve it?

 I face the problem because my model is too large, so out of memory occour. But the error will not report. So it looks like imblanced memory.

**Comment by dongsheng18** [comment]
I find that my problem is caused by pretrianed model, but I still don't know how to solve this problem

> > I also face to the same problem, how do you solve it?
> 
> I face the problem because my model is too large, so out of memory occour. But the error will not report. So it looks like imblanced memory.
