### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by ltm920716** [open-mmlab/mmdetection#2060]
demo code：

![image](https://user-images.githubusercontent.com/12007227/74020585-dd205700-49d4-11ea-8910-252198727398.png)

env info：
![image](https://user-images.githubusercontent.com/12007227/74020618-ed383680-49d4-11ea-860c-7a75033007ba.png)

err info：

/home/liangtm/home/mmdetection/mmdet/apis/inference.py:40: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Traceback (most recent call last):
  File "inference_demo.py", line 11, in <module>
    result = inference_detector(model, img)
  File "/home/liangtm/home/mmdetection/mmdet/apis/inference.py", line 86, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liangtm/home/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/liangtm/home/mmdetection/mmdet/models/detectors/base.py", line 139, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/liangtm/home/mmdetection/mmdet/models/detectors/base.py", line 122, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/liangtm/home/mmdetection/mmdet/models/detectors/two_stage.py", line 303, in simple_test
    self.test_cfg.rpn)
  File "/home/liangtm/home/mmdetection/mmdet/models/detectors/test_mixins.py", line 34, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/liangtm/home/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/liangtm/home/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 276, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/liangtm/home/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 92, in get_bboxes_single
    proposals, _ = nms(proposals, cfg.nms_thr)
  File "/home/liangtm/home/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 55, in nms
    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/Loops.cuh:103)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f987f681627 in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: void at::native::gpu_index_kernel<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> const&) + 0x78d (0x7f97e8f0168d in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x571bf32 (0x7f97e8efaf32 in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x571c298 (0x7f97e8efb298 in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x16957eb (0x7f97e4e747eb in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: at::native::index(at::Tensor const&, c10::ArrayRef<at::Tensor>) + 0x47e (0x7f97e4e705ae in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x1c0155a (0x7f97e53e055a in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x1c06023 (0x7f97e53e5023 in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x3820d1a (0x7f97e6fffd1a in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #9: <unknown function> + 0x1c06023 (0x7f97e53e5023 in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #10: at::Tensor::index(c10::ArrayRef<at::Tensor>) const + 0x191 (0x7f9880175931 in /home/liangtm/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: nms_cuda(at::Tensor, float) + 0x84d (0x7f986e2787ca in /home/liangtm/home/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #12: nms(at::Tensor const&, float) + 0x459 (0x7f986e2679d9 in /home/liangtm/home/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #13: <unknown function> + 0x3b3c9 (0x7f986e2763c9 in /home/liangtm/home/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x39750 (0x7f986e274750 in /home/liangtm/home/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>

段错误 (核心已转储)

please help！

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/issues/1961

**Comment by ltm920716** [comment]
> #1961

@ZwwWayne Thanks
