### ISSUE TITLE
Random Loss increase between epochs

### ISSUE THREAD

**Issue by fatihcankurnaz** [open-mmlab/mmdetection#2061]
I use default config about `configs/faster_rcnn_r50_fpn_1x.py`, and train.py parameters are `configs/faster_rcnn_r50_fpn_1x.py`

I am using this on my own custom dataset but, I am getting random loss spikes. Sometimes these spikes result in a continuous increase in loss and segmentation fault.

I followed the suggestion in `GETTING_STARTED.md` and set my lr accordingly, but the result did not change. These spikes always occur at the start of a new epoch.

`2020-02-07 08:09:11,774 - INFO - Epoch [85][700/702]	lr: 0.00001, eta: 1:12:12, time: 0.413, data_time: 0.006, memory: 3784, loss_rpn_cls: 0.0169, loss_rpn_bbox: 0.0154, loss_cls: 0.1619, acc: 95.7207, loss_bbox: 0.0654, loss: 0.2586
2020-02-07 08:09:33,983 - INFO - Epoch [86][50/702]	lr: 0.00001, eta: 1:11:51, time: 0.418, data_time: 0.011, memory: 3784, loss_rpn_cls: 146476154799534.0938, loss_rpn_bbox: 17531582713692.1758, loss_cls: 133715883610603.6875, acc: 95.6328, loss_bbox: 19717618161418.3047, loss: 317441248681001.1875
2020-02-07 08:09:54,643 - INFO - Epoch [86][100/702]	lr: 0.00001, eta: 1:11:30, time: 0.413, data_time: 0.006, memory: 3784, loss_rpn_cls: 0.0144, loss_rpn_bbox: 0.0178, loss_cls: 0.1575, acc: 95.8770, loss_bbox: 0.0648, loss: 0.2525
`

**Comment by ZwwWayne** [comment]
You might need to check your dataset; there might be some bug samples since it appears regularly.

**Comment by fatihcankurnaz** [comment]
The thing is that I tried to change the dataset structure, by taking items from different (train)set to another (test)set. However, no matter what I do, this always happens at the start of some new epoch. I am guessing that if it was a dataset problem It would occur regularly during the epoch, but it occurs when an epoch ends and a new one starts.

**Comment by ZwwWayne** [comment]
> The thing is that I tried to change the dataset structure, by taking items from different (train)set to another (test)set. However, no matter what I do, this always happens at the start of some new epoch. I am guessing that if it was a dataset problem It would occur regularly during the epoch, but it occurs randomly when an epoch ends and a new one starts.

You can set a breakpoint when the loss is weird and chek which sample causes this problem.
