### ISSUE TITLE
No weight decay in depthwise convolution

### ISSUE THREAD

**Issue by rydenisbak** [open-mmlab/mmdetection#2063]
**No weight decay in depthwise convolution**

**Motivation**
In the original MobileNet paper they mention that it was important to put very little weight decay on the depthwise layers.

I suggest set to zero weight decay in depthwise convolution if some flag is True in config.
If you will decide this feature is important I can create PR.

**Comment by ZwwWayne** [comment]
Thanks for your kind suggestion.
We do have plans to support MobileNets and depthwise convolutions in the codebase, at that time we will make sure the performance is compatible with their original papers.
