### ISSUE TITLE
rois.shape[0] == 0 in deformable pool

### ISSUE THREAD

**Issue by txytju** [open-mmlab/mmdetection#2072]
In deformable pooling operation, if `rois.shape[0]==0`, there will be error when you view x(a tensor of shape (0, C, pooled_h, pooled_w)) to shape of (0, -1) in [this line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/dcn/deform_pool.py#L165) and the error is as followes. What should I do ?

> RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by ZwwWayne** [comment]
Maybe you should check why the `rois.size(0) =0` first.
You can also add an `if` check at someplace, e.g., `if tensor.size(0) == 0`, you can manually skip the deformable pooling.

**Comment by hellock** [comment]
Thanks for the report. We will fix it to handle the exception.
