### ISSUE TITLE
How to fix parameters of some certain parts of the network and only train other parts easily?

### ISSUE THREAD

**Issue by KaiChen1998** [open-mmlab/mmdetection#2073]
Hi, here is a question about fine tuning. 
Is there an easy way to fix the parameters of parts of the network (e.g. fix the backbone and RPN and only train detection head when fine tuning a Mask RCNN model) in a config file? For example like the parameter `require_grad` in norm_cfg?
Thank you!

**Comment by ZwwWayne** [comment]
Currently, the codebase only supports to freeze the backbone. By setting the fronzen_stage=4, the backbone is frozen.

**Comment by KaiChen1998** [comment]
@ZwwWayne And this parameter `frozen_stage` should be set in the model dictionary or the backbone dictionary?
Since I don't think the `resnet` backbone class has this parameter.

**Comment by hellock** [comment]
Another way that you can fix any parameters of the model is to construct the optimizer according to your demand, and pass it to the runner.
