### ISSUE TITLE
torchscript support for DCVv2

### ISSUE THREAD

**Issue by IgorDavidyuk** [open-mmlab/mmdetection#2078]
Hello!
Allow me to ask for your advice, please.
Situation description: I know that deformable convolution is supported natively in Pytorch since 1.4, but this does not mean DCN may be extracted to a static graph via jit. Moreover, DCN added to Pytorch is version 1, not this one (version two).
Question: Can you confirm I understand the situation correctly and how hard is to add DCNv2 support to torchscript from your point of view?

**Comment by hellock** [comment]
Does PyTorch 1.4 support DCN natively? I cannot find it in the documentation.
The version is used in mmdet only, since we have some code refactoring for DCN.
It may not be quite simple to support torchscript for DCNv2.

**Comment by IgorDavidyuk** [comment]
@hellock  thanks for reply.
torchvision now contains DCN. https://github.com/pytorch/vision/blob/master/torchvision/ops/deform_conv.py
It seems like it is v1 DefCon (not modulated)

**Comment by hellock** [comment]
I see, it is modified from the op in mmdetection. `version` in DCN does not mean DCNv1 or DCNv2 in the paper, it is a flag for pytorch modules.
