### ISSUE TITLE
Custom labels for training

### ISSUE THREAD

**Issue by jimmy15923** [open-mmlab/mmdetection#2079]
Hi!

I want to add another custom labels such as class activation map as supervision to train the model. I have revised the dataset to load the CAM data and return in the `get_ann_info`

```
def get_ann_info(self, idx):
        ....
        ann = dict(
            bboxes=bboxes.astype(np.float32),
            labels=labels.astype(np.int64),
            cams=cams.astype(np.float32)
            bboxes_ignore=bboxes_ignore.astype(np.float32),
            labels_ignore=labels_ignore.astype(np.int64))
    return ann
```
Then I update the trian_pipelin with 'cams'
```
dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'cams'])
```
But got the KeyError. How can I add custom groud truth correctly? Also, how do I update the `Loss` function in the Detector to get all the ground truth data?
```
    @force_fp32(apply_to=('cls_scores', 'cams'))
    def loss(self,
             cls_scores,
             bbox_preds,
             centernesses,
             gt_bboxes,
             gt_labels,
             cams,
             img_metas,
             cfg,
             gt_bboxes_ignore=None):
```
Thank you!

**Comment by hellock** [comment]
1. You need to modify [`LoadAnnotations`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/loading.py#L38) to process your own keys properly. If you need to do some transforms for `cam` you may also need to write or modify other pipelines.
2. You need to modify the loss method of corresponding heads, and then call the loss method in the detector with the new signature.

**Comment by jimmy15923** [comment]
Got it. Thanks!

**Comment by jimmy15923** [comment]
Hi @hellock!

I want to make sure that if I add any custom ground truths, will the augmentation also apply to these new labels, such as rescale or flip? If not, how can I make sure the proper augmentation be applied to my custom labels? Thanks!

**Comment by jimmy15923** [comment]
I Found it! Just update the method in transform.py
