### ISSUE TITLE
where to download the pretrained resnext101_64x4d model?

### ISSUE THREAD

**Issue by qijiezhao** [open-mmlab/mmdetection#208]
Hi, Kai Chen:

Thanks for your contribution to mmdetection, I really appreciate your amazing work!
Recently, I was re-producing the supported RetinaNet-ResNeXt101-64x4d model by the command:
`
CUDA_VISIBLE_DEVICES=xx,xx ./tools/dist_train.sh configs/retinanet_x101_64x4d_fpn_1x.py 2 --validate
`
However, I always get the error:
`
OSError: open-mmlab://resnext101_64x4d is not a checkpoint file, 
`
although I have downloaded the pretrained X-101-64_4d.pkl from Detectron official page to ~/.torch/models/.
So how to prepare the pretrained resnext101_64x4d file?

Thank you!

**Comment by hellock** [comment]
You need to update mmcv to the latest version to enable new pretrained model urls. See [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py#L12) for newly added models.

**Comment by qijiezhao** [comment]
Thanks, solved!
