### ISSUE TITLE
program is stuck using reppoint and instaboost config

### ISSUE THREAD

**Issue by kingman1980** [open-mmlab/mmdetection#2082]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I trained a model with the config: reppoints_moment_r50_fpn_2x.py using my own coco-style dataset. As the program is running, the output is stuck as blow:

loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Done (t=5.28s)
creating index...
Done (t=5.31s)
creating index...
Done (t=5.38s)
creating index...
Done (t=5.58s)
creating index...
index created!
index created!
index created!
2020-02-12 12:41:46,660 - mmdet - INFO - Start running, host: myname@computer, work_dir: /home/myname/GitHub/mmdetection/work_dirs/reppoints_moment_r50_fpn_2x_20200211
2020-02-12 12:41:46,660 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
index created!

and this kept a very long time. If I shut down the program using Ctrl+C, the output is:
^CTraceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/myname/.local/lib/python3.5/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/myname/.local/lib/python3.5/site-packages/torch/distributed/launch.py", line 256, in main
    process.wait()
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

This is also happened using instaboost config.

Using Mask-rcnn config, the model can be trained and get good result.

**Reproduction**
1. What command or script did you run?
./tools/dist_train.sh configs/reppoints_moment_r50_fpn_2x_20200211.py 4

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I modified:
a). my own dataset;
b). imgs_per_gpu=4, workers_per_gpu=4,
3. What dataset did you use?
my own coco-style dataset.
**Environment**

1. Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

MMDetection CUDA Compiler: 10.0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
Python: 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
MMDetection: 1.0.0+1d7b0a7
CUDA available: True
GPU 0,1,2,3: TITAN RTX
MMCV: 0.2.16
TorchVision: 0.5.0
MMDetection Compiler: GCC 5.4
PyTorch: 1.4.0
OpenCV: 3.4.5

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by wzczc** [comment]
Hi, I met the same error. Did you solve it?
