### ISSUE TITLE
pad_val not used in class Pad when pad to a fixed size

### ISSUE THREAD

**Issue by lhcalibur** [open-mmlab/mmdetection#2083]
in mmdet/datasets/pipelines/transforms.py **class Pad**
```python
    def _pad_img(self, results):
        if self.size is not None:
            padded_img = mmcv.impad(results['img'], self.size)
```
self.pad_val is not pass to mmcv.impad

**Comment by hellock** [comment]
Thanks for reporting the potential bug! You may create a PR to fix it if you would like to.
