### ISSUE TITLE
How to determine label_weight in GHM Loss function?

### ISSUE THREAD

**Issue by Alien1007** [open-mmlab/mmdetection#2084]
I want to use GHM-R loss in my task, but I have no idea about the function of the argument 'label_weight' in your implementation. And how to compute 'label_weight' before I use the loss func?

**Comment by hellock** [comment]
`label_weight` is usually used to indicate valid samples. If we would like to ignore some samples, we set the corresponding weight to 0.

**Comment by Alien1007** [comment]
So we can just set all elements as 1 if we want use all samples. Thanks for your reply!
