### ISSUE TITLE
how to support apex in mmdetection?

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#2085]
RT, thanks.

**Comment by hellock** [comment]
MMDetection does not support apex officially, you may need to figure it our and modify the codes.
BTW, what are you going to use apex for? Mixed precision training?

**Comment by clw5180** [comment]
> MMDetection does not support apex officially, you may need to figure it our and modify the codes.
> BTW, what are you going to use apex for? Mixed precision training?

yes, it can save a lot of time, but FP16 in mmdetection can't.

**Comment by hellock** [comment]
According to our test, the mixed precision training implementation of mmdet is no slower than apex.
