### ISSUE TITLE
How to use OHEMSampler in one-stage detector?

### ISSUE THREAD

**Issue by yongtaoge** [open-mmlab/mmdetection#209]
Does mmdetection offer an interface to implentment it?

**Comment by yongtaoge** [comment]
Does mmdetection offer an interace to implentment it?

**Comment by hellock** [comment]
For single-stage detectors, `OHEMSampler` is generally not necessary. SSD has already implemented hard mining which is slightly different from OHEM, and RetinaNet uses focal loss to mine hard samples. If you want to implement it for your own detector, simply add it to the config file and it will be used in [`anchor_target()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/single_stage_heads/retina_head.py#L192) if you set `sampling=True`.

**Comment by yongtaoge** [comment]
Thank you. It helps.!

**Comment by yxchng** [comment]
@hellock Are you referring to `sampling=True` in this line (https://github.com/open-mmlab/mmdetection/blob/57d34592ec9cbeb5416a5528c40f202b34487c4f/mmdet/models/anchor_heads/ssd_head.py#L158)? How do I check if OHEM is indeed used after I change the settings?
