### ISSUE TITLE
Reproduce model zoo checkpoint SSD

### ISSUE THREAD

**Issue by Mxbonn** [open-mmlab/mmdetection#2096]
Hi,

I want to reproduce the SSD network results.
However I noticed that the config `config/ssd300_coco.py` has `total_epochs=24`  while the entry in the modelzoo mentions **lr_sched = 120e**. 
Does that mean that the config file to reproduce the model zoo checkpoint is different than the config file given in the configs directory? And if yes, are there any other settings I have to change besides the number of epochs?

**Comment by ZwwWayne** [comment]
Hi @Mxbonn ,
The dataset is repeated by 5 times as you can find the setting [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/ssd512_coco.py#L91). Therefore, by using the current config you can get comparable results to the model zoo.

**Comment by Mxbonn** [comment]
@ZwwWayne Thanks for pointing that out!
Current training after 10/12 epochs however is only at 17 mAP. So I dont think my model will reach the final mAP of 25.
The reason I ask for the original config file is because I want to add more SSD models such as (Mobilenets)SSDLite, as I feel they are missing in this framework.
However for that I first need to be able to reproduce the SSD Modelzoo models.

**Comment by yhcao6** [comment]
Hi, @Mxbonn, 
I have just tested [ssd300](https://github.com/open-mmlab/mmdetection/blob/master/configs/ssd300_coco.py) a few days ago and the performance seems fine, here is the training log
[20200208_113236.log](https://github.com/open-mmlab/mmdetection/files/4231615/20200208_113236.log).

By the way, can you provide your environment info?

**Comment by Mxbonn** [comment]
Rerunning the provided config file indeed reproduced the results.
Thank you.
