### ISSUE TITLE
mmdet/ops/utils/src/compiling_info.cpp:3:30: fatal error: cuda_runtime_api.h

### ISSUE THREAD

**Issue by CodeXiaoLingYun** [open-mmlab/mmdetection#2106]
when i use conda install python3.6 and torch 1.3.1, i input "git clone https://github.com/open-mmlab/mmdetection.git" and "cd mmdetection"  .
But when i input "python setup.py develop" , it is error.
![image](https://user-images.githubusercontent.com/20829946/74622155-bd2e2780-517a-11ea-83b0-74cdaf4837ee.png)
I chech the cuda and find it is OK.
![image](https://user-images.githubusercontent.com/20829946/74622200-dd5de680-517a-11ea-9ade-128ff4754ebc.png)
please help!!!!!

**Comment by CodeXiaoLingYun** [comment]
i cheak my env and find 
CUDA_HOME=:/usr/local/cuda-9.0
LD_LIBRARY_PATH=:/usr/local/cuda-9.0/lib64
But when i use conda install pytorch
![image](https://user-images.githubusercontent.com/20829946/74640099-0184ec00-51aa-11ea-9b1e-12875f244114.png)
i don't know,whether the difference of the duda is reason?

**Comment by CodeXiaoLingYun** [comment]
The question is solved. i change the #include<absolute path>

**Comment by jefferyZhan** [comment]
I met the same problem. Could you please tell me how to fix it?

**Comment by CodeXiaoLingYun** [comment]
> I met the same problem. Could you please tell me how to fix it?

my question is it can not look for the cuda_runtime.h. This order in mmdet/ops/utils/src/compling_info.cpp.  original order is #<cuda_runtime.h>,you can try change the path to absolute path. Tthis flile(cuda_runtime.h)may be in usr/cuda-9.0... you can try.

**Comment by hellock** [comment]
1. The CUDA version in your local path and the CUDA version built with PyTorch should match.
2. You need to specify correct CUDA_HOME to make your local CUDA visible.

**Comment by CodeXiaoLingYun** [comment]
> 1. The CUDA version in your local path and the CUDA version built with PyTorch should match.
> 2. You need to specify correct CUDA_HOME to make your local CUDA visible.



> 1. The CUDA version in your local path and the CUDA version built with PyTorch should match.
> 2. You need to specify correct CUDA_HOME to make your local CUDA visible.

thank you for you answer.althought my CUDA version(9.0)in my local path is different from the CUDAversion with pytorch(which build by conda ,version=10.0), but i find i can run the test demo. i am trying train a model on my own dataset. I do not know whether it is ok

**Comment by qzz1007055052** [comment]
Can you explain in detail how it was modified?Thank you!!~

**Comment by CodeXiaoLingYun** [comment]
> I met the same problem. Could you please tell me how to fix it?

The first you should look for the file in mmdet/ops/utils/src/compling_info.cpp
You can find a code like # include <cuda_runtime.h> , this cite used relative path not the absolute path， so you can change it to absolute path, and the file cuda_runtime.h maybe in usr/cuda-9.0...

**Comment by CodeXiaoLingYun** [comment]
> Can you explain in detail how it was modified?Thank you!!~

The first you should look for the file in mmdet/ops/utils/src/compling_info.cpp
You can find a code like # include <cuda_runtime.h> , this cite used relative path not the absolute path， so you can change it to absolute path, and the file cuda_runtime.h maybe in usr/cuda-9.0...

**Comment by LoveIsAGame** [comment]
我修改成绝对路径，还是一样的错误，可以给我提供一些其他的思路吗？

**Comment by CodeXiaoLingYun** [comment]
> 我修改成绝对路径，还是一样的错误，可以给我提供一些其他的思路吗？

既然你用中午问了，那我就用中文回一个，是这样的，你可以进入你的环境1. nvcc --version  这里有一个环境运行的cuda版本 2. 进入python3 import torch, torch.cuda.version 查看当前torch对应的cuda版本，1，2的cuda版本尽量保持一样，不然问题很多

**Comment by BIGWangYuDong** [comment]
Find the line in  mmdet/ops/utils/src/compling_info.cpp `# include <cuda_runtime.h>`
Then change `cuda_runtime_api.h` to `/usr/local/cuda/targets/x86_64-linux/include/cuda_runtime_api.h` (need check the path)

Meet the same error and fix it.
