### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by jefferyZhan** [open-mmlab/mmdetection#2108]
hello!
The command I ran is "python3 tools/train.py configs/faster_rcnn_r50_fpn_1x.py --gpus 1 --work_dir work_dirs". And on Telsa P4 whose Compute Capability is 6.1, I didn't meet the error, but on Telsa T4 whose Compute Capability is 7.5, we got this error.
I think the reason is the setting of TORCH_CUDA_ARCH_LIST.In your dockerfile, it is written "ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX", which means it doesn't support 7.5. I think the env built with another method you provide is the same. So how can I change the setting instead of change the setting in the dockerfile and using the dockerfile to build the env?

**Comment by hellock** [comment]
You may override the variable by specifying TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5+PTX" explicitly in your `docker run` command.
