### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'with_last_pool'

### ISSUE THREAD

**Issue by robeson1010** [open-mmlab/mmdetection#211]
Hi, when I try to use SSD model with custom dataset it shows:

TypeError: __init__() got an unexpected keyword argument 'with_last_pool'.

How to fix it?

**Comment by yhcao6** [comment]
You can update mmcv

**Comment by robeson1010** [comment]
> You can update mmcv

Thanks

**Comment by zhaoyang97** [comment]
Have u solved it？I meet the same question now.
Update mmcv does not working.
