### ISSUE TITLE
Question about the progress on #1695

### ISSUE THREAD

**Issue by EletronicElephant** [open-mmlab/mmdetection#2110]
Hi everyone, thank you for the awesome job!

I have some questions on #1695 `Implementing YOLOv3 architecture`, since several months have passed and there seems to be no progress.

I'm wondering if there is any progress on YOLOv3. If not, I have successfully get his code running. May I continue his job? Will the lincense issue be a problem?

Best wishes.

**Comment by EletronicElephant** [comment]
@hellock

**Comment by hellock** [comment]
There is a code refactoring on-going, thus we will not merge it now. We will work on the code reviews after the refactoring in March.

**Comment by EletronicElephant** [comment]
> 
> 
> There is a code refactoring on-going, thus we will not merge it now. We will work on the code reviews after the refactoring in March.

Understand. By the way, I'm happy to help if the original author doesn't respond.
