### ISSUE TITLE
Validation fails if there are no ignored boxes

### ISSUE THREAD

**Issue by melikovk** [open-mmlab/mmdetection#2115]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Training encounters error during validation step if there are no ignored gt bboxes.
On line 179 in mean_ap.py
gt_bboxes = np.vstack((gt_bboxes, gt_bboxes_ignore))

**Bug fix**

This error is due to the bug on Line 261 in function get_cls_results

cls_gts_ignore.append(np.array((0,4),  dtype=np.float32)) 

This line append an array [0,4  ] of shape (2,), when empty array of shape (0,4) is expected.
The following substitution fixes the issue:

cls_gts_ignore.append(np.empty((0, 4), dtype=np.float32))

Thank you.

**Comment by ZwwWayne** [comment]
Hi @melikovk ,
Thanks for your error report, this is indeed a bug, we will fix it ASAP.
