### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 64 3 7 7, expected input[3, 2, 800, 1120] to have 3 channels, but got 2 channels instead

### ISSUE THREAD

**Issue by 584669** [open-mmlab/mmdetection#2119]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

when l train faster-rcnn ,this error is happen,but others model is normal.i think it maybe batch-size and channel is error.

**Comment by hellock** [comment]
Please follow the issue template to fill in the required fields. Without enough information, it would be hard for others to help with this issue.
