### ISSUE TITLE
anchor_generators of faster_rcnn without neck

### ISSUE THREAD

**Issue by moonh1** [open-mmlab/mmdetection#2120]
Hello, I am these days trying to detach fpn from faster_rcnn.

What I am thinking of is, get only last layer of resnet backbone, and insert it to the rpn head.
But I met the issue in **anchor_head.py**, specifically line 172,
assert len(featmap_sizes) == len(self.anchor_generators).

Since my feature map size is 1 and len(self.anchor_generators) is 5 according to default config, I met this error.

Do I need to also change rpn_head part to match dimensions?
Thank you for the help.

**Comment by hellock** [comment]
We have already provided a config for using a single feature map instead of FPN: https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn_r50_caffe_c4_1x.py.
