### ISSUE TITLE
Error in inferencing HTC dconv_c3-c5

### ISSUE THREAD

**Issue by meghanakanapaneni** [open-mmlab/mmdetection#2122]
Facing error in dconv_c3-c5 model. The error is attached below.
I think the problem is with the config file(Config file : configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py). Can you please help me with this?
<img width="666" alt="Screenshot 2020-02-20 at 5 05 23 PM" src="https://user-images.githubusercontent.com/30812554/74930295-43f53580-5403-11ea-96e8-9d58f9a6c517.png">

**Comment by ZwwWayne** [comment]
Hi @meghanakanapaneni ,
The key of `groups` is duplicated. To quick fix the bug, you can either delete this [line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnext.py#L65) or this [line](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py#L19). We will create a PR to fix this later.
