### ISSUE TITLE
Batched inference

### ISSUE THREAD

**Issue by robeson1010** [open-mmlab/mmdetection#213]
I found the model was rewritten. Is any way yo batched inference that inference 4 pictures per GPU per time?

**Comment by hellock** [comment]
The api is currently not available, though it has been implemented.
For single GPU inference, you can modify the argument [`imgs_per_gpu`](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L84) and comment corresponding assert statements.
For multi GPU inference, it needs more modification.

**Comment by robeson1010** [comment]
> The api is currently not available, though it has been implemented.
> For single GPU inference, you can modify the argument [`imgs_per_gpu`](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L84) and comment corresponding assert statements.
> For multi GPU inference, it needs more modification.

Thanks for your reply, I have checked the code and comment the assert line in base.py.  However, the output the following line is always for one img even the data['img'] is [4,3,xxx,xxx]. How to run the right result here?
 `` result = model(return_loss=False, rescale=not show, **data)

For example,
the data['img'] is 1,3,height,wight
the result is a list of length 80
when the data['img] is 4,3,height,weight
the result is always a list of length 80

**Comment by xgmiao** [comment]
yes，I found the same problem.  it do'n surpport batch inference even in single GPU inference，the result is always for the first img even the data['img'] is [4,3,xxx,xxx]  @hellock @robeson1010

**Comment by farleylai** [comment]
I noticed that in `rpn.py`, only the `proposal_list[0]` is returned which is marked as TODO.

What is the current restriction of batch inference/training?
Is it due to the image preprocessing?
It looks like the scaling/padding may not ensure the same image tensor size in a batch because the `img_transformer` is set to pad to a multiple of `cfg.data.size_divisor`.
