### ISSUE TITLE
test script fails on CustomDataset

### ISSUE THREAD

**Issue by melikovk** [open-mmlab/mmdetection#2130]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Test script fails on CustomDataset when attempting to evaluate mAP, even though correct parameters are provided with a message
KeyError: "metric ['mAP'] is not supported"

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
The reason for the problem is evaluate() method in CustomDataset. Currently it treats metric argument as a string (although documentation suggest that both string and list of strings can be used). The test script though passes it a list (even if it is only 1 metric). I have made changes to the evaluate() method to correctly treat list arguments (pull request #2128).
Thank you.

**Comment by melikovk** [comment]
recall part still does not work with my patch, but mAP works.

**Comment by hellock** [comment]
Are you using the latest version? Could you also show your config file?

**Comment by melikovk** [comment]
Hi, I am sorry, I should have closed the issue. The problem with recall was because I was trying to run it on the output of multi-class model and apparently it does not support it
