### ISSUE TITLE
ga_faster_x101 training NaN

### ISSUE THREAD

**Issue by chenzui1113** [open-mmlab/mmdetection#2133]
When I try to train the ga_faster_x101, the loss has become very large, sometimes NaN. I only have one  1080Ti. So I have tried a lot of lr, and also tried to modify the warmup='exp',warmup_iters=1000, warmup_ratio=1.0/10. But the same result happened. (other detection network also like it). 
Can you tell me why please? Thank you very much!
![1](https://user-images.githubusercontent.com/40261000/75049043-7a66a980-5504-11ea-9035-e3f5fca8a106.jpg)

**Comment by ElectronicElephant** [comment]
In my opinion, the small batch size might be the cause.

**Comment by myownskyW7** [comment]
You may first search for a lr (e.g. 0.02/8 = 0.0025) which can be successfully adopted to the original Faster R-CNN with X-101 and FPN backbone. And then tries to train GA-Faster R-CNN with such a lr.

**Comment by shliang0603** [comment]
@chenzui1113  I have sloved the problem，by reducing the learn_rate，such as:
```python
 retinanet_r50_fpn_1x_coco.py
_base_ = [
    '../_base_/models/retinanet_r50_fpn.py',
    '../_base_/datasets/voc0712.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)


# lr default is 0.01, I changed it to 0.001
 retinanet_r50_fpn_1x_coco.py
_base_ = [
    '../_base_/models/retinanet_r50_fpn.py',
    '../_base_/datasets/voc0712.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
# optimizer
optimizer = dict(type='SGD', lr=0.001, momentum=0.9, weight_decay=0.0001)
```
