### ISSUE TITLE
How do we train using htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py but without semantic segmentation information?

### ISSUE THREAD

**Issue by shriramhr** [open-mmlab/mmdetection#2136]
Hi,

I've been going throught the config and want to train my custom dataset which has instance mask information but no semantic mask information and it is in COCO format. 

What do we put in place of: 
seg_prefix=data_root + 'stuffthingmaps/train2017/'

**Comment by hellock** [comment]
Only HTC requires stuff maps. You can also refer to [a variant](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_without_semantic_r50_fpn_1x.py) which does not use semantic segmentation maps.

**Comment by shriramhr** [comment]
> Only HTC requires stuff maps. You can also refer to [a variant](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_without_semantic_r50_fpn_1x.py) which does not use semantic segmentation maps.

I saw that but it's using a resnet50 backbone. Is there a way to make the file work if I swap the backbone to the resnext 101 with fpn backbone? Will I need to change all the dicts in the file too?

**Comment by hellock** [comment]
The config file is modular, and you can make your own modifications as you like.
