### ISSUE TITLE
File "/home/writ/.virtualenvs/mmde/lib/python3.6/site-packages/torchvision/models/inception.py", line 9, in <module>     from torch.jit.annotations import Optional ImportError: cannot import name 'Optional'

### ISSUE THREAD

**Issue by CZYWRIT** [open-mmlab/mmdetection#2138]
File "/home/writ/.virtualenvs/mmde/lib/python3.6/site-packages/torchvision/models/inception.py", line 9, in <module>
    from torch.jit.annotations import Optional
ImportError: cannot import name 'Optional'

when I want to train， this fault would happen，please give me some suggestion，thank you.
my environment is python 3.6, torch1.1, cuda10.0

**Comment by ZwwWayne** [comment]
Please check the version consistency between your Torchvision and the PyTorch. You might need to reinstall a suitable torchvision or upgrade your PyTorch,

**Comment by czy112** [comment]
i meet same error ,torch==1.1.0,torchvision==0.3.0   can you tell me how to solve this ?   
    from torch._jit_internal import Optional
ImportError: cannot import name 'Optional'


thanks
