### ISSUE TITLE
use init_detector() twice to load two models, but met error ‘The model and loaded state dict do not match exactly’

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#2140]
I want to load 2 model to predict different kinds of images, the code like that 
`config_file =  'configs/cascade_rcnn_hrnetv2p_w32_20e_v1.py'
checkpoint_file = 'work_dirs/cascade_rcnn_hrnetv2p_w32_v2/epoch_12.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')

config_file2 =  'configs/cascade_rcnn_hrnetv2p_w32_20e_v2py'
checkpoint_file2 = 'work_dirs/cascade_rcnn_hrnetv2p_w32_v2/epoch_12.pth'
model2 = init_detector(config_file2, checkpoint_file2, device='cuda:0')`

but I got error:
**The model and loaded state dict do not match exactly**

**these keys have mismatched shape:
rpn_head.rpn_cls.weight | torch.Size([7, 256, 1, 1])  | torch.Size([10, 256, 1, 1])**

**Comment by clw5180** [comment]
我发现加载第二个模型时，尽管cfg名字是第二个模型，但用的还是第一个模型的rpn属性，导致rpn在anchor上不匹配，请问这是什么原因？应该如何解决？

**Comment by matthost** [comment]
think im running into the same thing. you fix it?

**Comment by matthost** [comment]
for me I am having different behavior (mmdet module code errors) if i load two models and run inference, while loading and running inference for each on its own works

**Comment by matthost** [comment]
nvm, issue was our fault. one of the modules was modifying static class attributes instead of instance attributes
