### ISSUE TITLE
Doc mistake in GETTING_STARTED.md

### ISSUE THREAD

**Issue by seanremy** [open-mmlab/mmdetection#2142]
Very simple problem, very simple fix:

Under 'Testing a dataset', the 4th option is described as:
"Test Mask R-CNN on COCO test-dev with 8 GPUs, and generate the json file to be submit to the official evaluation server."

However with '--out' (instead of '--eval' or '--format_only') the results json files will not actually be generated. Either fix 'tools/test.py' or change 'docs/GETTING_STARTED.md'

Thanks!

**Comment by ZwwWayne** [comment]
Hi @seanremy ,
Thanks for your kind suggestion, we forget to modify the docs.
Are you willing to create a PR to fix the doc issue in `docs/GETTING_STARTED.md` ?

**Comment by seanremy** [comment]
#2149
