### ISSUE TITLE
different cityscapes result

### ISSUE THREAD

**Issue by liyiwei979621500** [open-mmlab/mmdetection#2146]
The box AP  of Faster R-CNN in the cityscapes page is 36, however, I download the model and run eval then get ap 33.8. 

Can someone take a look at this diffrence? Am I doing something wrong?

![image](https://user-images.githubusercontent.com/16919236/75149523-2bf01f80-573d-11ea-9926-1384e0d7b2ff.png)

# Update
I regenerate the annotation files, test with which, I get  the ap0.5 = 35.7. Is this correct?
![image](https://user-images.githubusercontent.com/16919236/75218645-bf752f00-57d5-11ea-9947-b1b100f7980c.png)

Which AP are you using? the AP0.5 or  AP0.50:0.95?

**Comment by xvjiarui** [comment]
We noticed that some parts of Cityscapes have been deprecated. 
We are working on a new implementation, which would be merged very soon with the newly trained model.

**Comment by liyiwei979621500** [comment]
Thanks! @xvjiarui
