### ISSUE TITLE
ImportError: cannot import name 'CARAFENAIVE' from 'mmdet.ops.carafe'

### ISSUE THREAD

**Issue by isolution911** [open-mmlab/mmdetection#2148]
The module name 'CARAFENAIVE' in file 'mmdet.ops.carafe.grad_check.py' shoud be 'CARAFENaive'. When I run this command 'python mmdet/ops/carafe/grad_check.py', the following error is reported: ImportError: cannot import name 'CARAFENAIVE' from 'mmdet.ops.carafe'.

**Comment by hellock** [comment]
Thanks! Would you like to create a PR to fix it?
