### ISSUE TITLE
./compile.sh error

### ISSUE THREAD

**Issue by Markovcom** [open-mmlab/mmdetection#215]
Building roi align op...
running build_ext
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py:118: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'roi_align_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_align_cuda.o -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/usr/local/cuda/bin/nvcc -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_align_kernel.cu -o build/temp.linux-x86_64-3.6/src/roi_align_kernel.o -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Half-inl.h(17): error: identifier "__half_as_short" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000681d_00000000-7_roi_align_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
Building roi pool op...
running build_ext
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py:118: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
building 'roi_pool_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_pool_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_pool_cuda.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/usr/local/cuda/bin/nvcc -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_pool_kernel.cu -o build/temp.linux-x86_64-3.6/src/roi_pool_kernel.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Half-inl.h(17): error: identifier "__half_as_short" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00006845_00000000-7_roi_pool_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
Building nms op...
rm -f *.so
echo "Compiling nms kernels..."
Compiling nms kernels...
python setup.py build_ext --inplace
Warning: Extension name 'cpu_nms' does not match fully qualified name 'mmdet.ops.nms.cpu_nms' of 'cpu_nms.pyx'
Warning: Extension name 'cpu_soft_nms' does not match fully qualified name 'mmdet.ops.nms.cpu_soft_nms' of 'cpu_soft_nms.pyx'
Warning: Extension name 'gpu_nms' does not match fully qualified name 'mmdet.ops.nms.gpu_nms' of 'gpu_nms.pyx'
running build_ext
building 'cpu_nms' extension
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c cpu_nms.cpp -o build/temp.linux-x86_64-3.6/cpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_nms.cpp:520:
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -B /home/zhoulinmao/anaconda3/compiler_compat -L/home/zhoulinmao/anaconda3/lib -Wl,-rpath=/home/zhoulinmao/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu_nms.o -o /home/code/zhoulinmao/detection/mmdetection/mmdet/ops/nms/cpu_nms.cpython-36m-x86_64-linux-gnu.so
building 'cpu_soft_nms' extension
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c cpu_soft_nms.cpp -o build/temp.linux-x86_64-3.6/cpu_soft_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_soft_nms.cpp:520:
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
cpu_soft_nms.cpp: In function ‘PyObject* __pyx_pf_5mmdet_3ops_3nms_12cpu_soft_nms_cpu_soft_nms(PyObject*, PyArrayObject*, float, unsigned int, float, float)’:
cpu_soft_nms.cpp:2319:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                    ^
cpu_soft_nms.cpp:2830:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                    ^
g++ -pthread -shared -B /home/zhoulinmao/anaconda3/compiler_compat -L/home/zhoulinmao/anaconda3/lib -Wl,-rpath=/home/zhoulinmao/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu_soft_nms.o -o /home/code/zhoulinmao/detection/mmdetection/mmdet/ops/nms/cpu_soft_nms.cpython-36m-x86_64-linux-gnu.so
building 'gpu_nms' extension
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c gpu_nms.cpp -o build/temp.linux-x86_64-3.6/gpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:522:
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
nvcc -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c nms_kernel.cu -o build/temp.linux-x86_64-3.6/nms_kernel.o -c --compiler-options -fPIC
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
g++ -pthread -shared -B /home/zhoulinmao/anaconda3/compiler_compat -L/home/zhoulinmao/anaconda3/lib -Wl,-rpath=/home/zhoulinmao/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/gpu_nms.o build/temp.linux-x86_64-3.6/nms_kernel.o -o /home/code/zhoulinmao/detection/mmdetection/mmdet/ops/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so

**Comment by hellock** [comment]
The warning information has told that the gcc version is not high enough. You need to upgrade gcc.

**Comment by Markovcom** [comment]
@hellock thank you for your reply, I try it.

**Comment by Markovcom** [comment]
@hellock hello, i change gcc4.8 to gcc4.9.4, then run compile.sh,but i meet this error
Building roi align op...
running build_ext
building 'roi_align_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_align_cuda.o -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_align_kernel.cu -o build/temp.linux-x86_64-3.6/src/roi_align_kernel.o -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Half-inl.h(17): error: identifier "__half_as_short" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00003341_00000000-7_roi_align_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
Building roi pool op...
running build_ext
building 'roi_pool_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_pool_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_pool_cuda.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c src/roi_pool_kernel.cu -o build/temp.linux-x86_64-3.6/src/roi_pool_kernel.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Half-inl.h(17): error: identifier "__half_as_short" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00003356_00000000-7_roi_pool_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
Building nms op...
rm -f *.so
echo "Compiling nms kernels..."
Compiling nms kernels...
python setup.py build_ext --inplace
Warning: Extension name 'cpu_nms' does not match fully qualified name 'mmdet.ops.nms.cpu_nms' of 'cpu_nms.pyx'
Warning: Extension name 'cpu_soft_nms' does not match fully qualified name 'mmdet.ops.nms.cpu_soft_nms' of 'cpu_soft_nms.pyx'
Warning: Extension name 'gpu_nms' does not match fully qualified name 'mmdet.ops.nms.gpu_nms' of 'gpu_nms.pyx'
running build_ext
building 'cpu_nms' extension
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c cpu_nms.cpp -o build/temp.linux-x86_64-3.6/cpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_nms.cpp:520:
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -B /home/zhoulinmao/anaconda3/compiler_compat -L/home/zhoulinmao/anaconda3/lib -Wl,-rpath=/home/zhoulinmao/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu_nms.o -o /home/code/zhoulinmao/detection/mmdetection/mmdet/ops/nms/cpu_nms.cpython-36m-x86_64-linux-gnu.so
building 'cpu_soft_nms' extension
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c cpu_soft_nms.cpp -o build/temp.linux-x86_64-3.6/cpu_soft_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_soft_nms.cpp:520:
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
cpu_soft_nms.cpp: In function ‘PyObject* __pyx_pf_5mmdet_3ops_3nms_12cpu_soft_nms_cpu_soft_nms(PyObject*, PyArrayObject*, float, unsigned int, float, float)’:
cpu_soft_nms.cpp:2319:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
cpu_soft_nms.cpp:2830:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
g++ -pthread -shared -B /home/zhoulinmao/anaconda3/compiler_compat -L/home/zhoulinmao/anaconda3/lib -Wl,-rpath=/home/zhoulinmao/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu_soft_nms.o -o /home/code/zhoulinmao/detection/mmdetection/mmdet/ops/nms/cpu_soft_nms.cpython-36m-x86_64-linux-gnu.so
building 'gpu_nms' extension
gcc -pthread -B /home/zhoulinmao/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c gpu_nms.cpp -o build/temp.linux-x86_64-3.6/gpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:522:
/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
nvcc -I/home/zhoulinmao/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/zhoulinmao/anaconda3/include/python3.6m -c nms_kernel.cu -o build/temp.linux-x86_64-3.6/nms_kernel.o -c --compiler-options -fPIC
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
g++ -pthread -shared -B /home/zhoulinmao/anaconda3/compiler_compat -L/home/zhoulinmao/anaconda3/lib -Wl,-rpath=/home/zhoulinmao/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/gpu_nms.o build/temp.linux-x86_64-3.6/nms_kernel.o -o /home/code/zhoulinmao/detection/mmdetection/mmdet/ops/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/issues/22#issuecomment-430671216
