### ISSUE TITLE
How to convert my dataset to coco format

### ISSUE THREAD

**Issue by liquor233** [open-mmlab/mmdetection#2152]
I have a dataset which consists a lot of jpeg images and gt text files, and I wonder how can I convert it to coco format. Thanks .

**Comment by hellock** [comment]
Actually you don't need to convert it to COCO format, you can write a simple dataset to support your own format following the [documentation](https://mmdetection.readthedocs.io/en/latest/GETTING_STARTED.html#use-my-own-datasets). If you indeed want to convert it to COCO format, just write a script.
