### ISSUE TITLE
subprocess.CalledProcessError: Command 'gcc --version | head -n1' returned non-zero exit status 255.

### ISSUE THREAD

**Issue by kknoob** [open-mmlab/mmdetection#2154]
I have successfully run demo.py.
And my environment is cuda10.1,pytorch 1.4.0  python 3.6 and win 10.
But when I want to train.
`python tools/train.py configs/guided_anchoring/ga_retinanet_r50_caffe_fpn_1x.py --gpus 0 --validate --work_dir work_dirs
'tail' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'head' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 94, in main
    env_info_dict = collect_env()
  File "E:\Anaconda\envs\mmdetection\lib\site-packages\mmdet\utils\collect_env.py", line 42, in collect_env
    gcc = subprocess.check_output('gcc --version | head -n1', shell=True)
  File "E:\Anaconda\envs\mmdetection\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "E:\Anaconda\envs\mmdetection\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'gcc --version | head -n1' returned non-zero exit status 255.`

Can someone help me? Thank you very much!

**Comment by hellock** [comment]
Windows is currently not supported.

**Comment by TuanNguyenSKKU** [comment]
I have also encountered this error. But when I saw this tutorial, they can run it more easily on Windows 10. 
https://www.youtube.com/watch?v=z8lGpY4jQfc
@hellock I hope you can give us the solutions to this issue.
Thank you.
