### ISSUE TITLE
Incorrect time estimation for faster rcnn fpn ResNet Xt101 framework

### ISSUE THREAD

**Issue by Cli98** [open-mmlab/mmdetection#2159]
![image](https://user-images.githubusercontent.com/19630616/75286230-2a2e6680-57e6-11ea-9fa0-128e2399ec05.png)
If my understanding is correct, it tells me that I need -2 days to complete training.  @hellock Is this the expected behavior? Why it shows -2?

**Comment by hellock** [comment]
You may have set the `resume_from` field. It is only used for resuming an experiment without modification, otherwise the time estimation might be inaccurate. If you modified the config, you may use `load_from` instead of `resume_from`.

**Comment by Cli98** [comment]
I see that. That's a good catch. Thank you.
