### ISSUE TITLE
Where to make data augmentation? the inference?

### ISSUE THREAD

**Issue by hitlxm** [open-mmlab/mmdetection#216]

**Comment by hellock** [comment]
You can modify `img_scales` to be a list of tuple for multi-scale inference, and `flip_ratio` to be positive for horizontal flipping.

**Comment by hellock** [comment]
#135

**Comment by spytensor** [comment]
only support 2 scale?

**Comment by hellock** [comment]
@spytensor The inference supports any scales.

**Comment by chenxu93** [comment]
@hellock  where to change model type  between "range" and "value"?
