### ISSUE TITLE
How to set img_scale for 4096*3000 images？

### ISSUE THREAD

**Issue by 18804601171** [open-mmlab/mmdetection#2160]

**Comment by clw5180** [comment]
> _No description provided._

tianchi ?

**Comment by 18804601171** [comment]
@clw5180 yes

**Comment by clw5180** [comment]
> @clw5180 yes

have you tried short side = 1500 or 1800 and multi-scale ±20% ? I'm also curious about how to get the best scale

**Comment by 18804601171** [comment]
can you add my wechat number596932608？I have try short side=1500，but performance is not good。
