### ISSUE TITLE
How to freeze more layers outside the backbone networks?

### ISSUE THREAD

**Issue by zhoulukuan** [open-mmlab/mmdetection#2162]
I want to train some branches first and then train the rest branches. So I need to freeze more layers outside the backbone networks, such as those in the classifier. How to do it?

**Comment by ZwwWayne** [comment]
You may refer to the implementation in the [resnet.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L457) and implement a similar function in the module you want to freeze.
