### ISSUE TITLE
Question about the cost of GPU memory increase during inference

### ISSUE THREAD

**Issue by lyc6749** [open-mmlab/mmdetection#2168]
After used the interpolate ，the gpu memory can not be released during inference。I try to use torch.cuda.empty_cache() after, but it can work only in feding the images one by one。when the images is concurrently fedding ，the GPU still increase。Can you tell me how to do？

**Comment by ZwwWayne** [comment]
Hi @lyc6749 ,
I do not quite understand your question or what you expect to obtain. Do you mean you want to reduce the GPU memory usage during inference?

**Comment by kye9216789** [comment]
I recommend you to reduce num_sample in sampler or num_proposals in rcnn layer
torch.cuda.empty_cache() will seriously increase your total train time.
In my experience, applying empty_cache() multiplies total duration maximum 6 times.

**Comment by lyc6749** [comment]
dur

> Hi @lyc6749 ,
> I do not quite understand your question or what you expect to obtain. Do you mean you want to reduce the GPU memory usage during inference?

during inference, the GPU memory will increase too large。The code used for inference as follows:
`      model = init_detector(config_file, checkpoint_file, device='cuda:0')
        img=cv2.imread(im_file)
        result = inference_detector(model, img)`

**Comment by hellock** [comment]
Please follow the `Error report` issue template to provide necessary information.

**Comment by vanpersie32** [comment]
I think I have met the same issue, the gpu usage is increasing during inference
