### ISSUE TITLE
 __init__() missing 1 required positional argument: 'context'

### ISSUE THREAD

**Issue by Fitz-liu** [open-mmlab/mmdetection#217]
![002f066b68783db5093333fd2f7973c](https://user-images.githubusercontent.com/24975745/50538811-ae6c6600-0bb0-11e9-8f87-6a587446dc1d.png)

**Comment by Morde-kaiser** [comment]
@Fitz-liu Hi, I also encountered this problem when I used OHEM in cascade rcnn. Have you solved it?

**Comment by mao-jy** [comment]
> @Fitz-liu Hi, I also encountered this problem when I used OHEM in cascade rcnn. Have you solved it?

I have the same issue when apply OHEM to Cascade RCNN. Have you solved it? Would you please give me some help? Thank you!
