### ISSUE TITLE
picture format question

### ISSUE THREAD

**Issue by DaveCage** [open-mmlab/mmdetection#2172]
Hi!
The pictures in my datasets are '.bmp' format,and it doesn`t work in voc_form .What can i do to train the pictures?
Thx

**Comment by hellock** [comment]
You may train without any modification as long as the images can be opened with `cv2.imread()`.

**Comment by DaveCage** [comment]
thx a lot， i`ll try

**Comment by cvchongci** [comment]
@hellock 
I find the following codes in xml_style.py
```
            filename = 'JPEGImages/{}.jpg'.format(img_id)
            xml_path = osp.join(self.img_prefix, 'Annotations',
                                '{}.xml'.format(img_id))
```
it seems that for VOC format only jpg is supported?
thank you co much.
