### ISSUE TITLE
Can 'modulated=True' in dcn setting improve map?

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#2178]
When should I use 'modulated=True' in dcn? I see most of the configs sets 'modulated=False'. Thanks a lot!

**Comment by hellock** [comment]
`modulated=True` corresponds to `DCNv2` and `modulated=False` corresponds to `DCNv1`.

**Comment by clw5180** [comment]
> `modulated=True` corresponds to `DCNv2` and `modulated=False` corresponds to `DCNv1`.

Does 'modulated=True' often better than 'modulated=False' in most situations?
