### ISSUE TITLE
About resume training

### ISSUE THREAD

**Issue by ztt0821** [open-mmlab/mmdetection#2183]
Hi. I want to ask the resume training. My training process was interrupted by accident. May I ask how to resume training or I need to training from the begin. I am training HTC model now.

**Comment by hellock** [comment]
You can set `resume_from` in the config file to the last checkpoint file.

**Comment by ZwwWayne** [comment]
The issue is closed because the question is answered. Feel free to reopen it if you have any further questions.

**Comment by danial880** [comment]
When the training is resumed from a checkpoint, do all the hyperparameters have the same value when the checkpoint is saved? Or it is just weights that are kept in the checkpoint.
