### ISSUE TITLE
Questions on how GN is used in FCOS

### ISSUE THREAD

**Issue by ElectronicElephant** [open-mmlab/mmdetection#2188]
As is shown in `configs/fcos/README.md`, `GN` can increase mAP by 1 point.

However, I have noticed that only the `head` is using `GN` by default in the config `fcos_r50_caffe_fpn_gn_1x_4gpu.py` [L11](https://github.com/open-mmlab/mmdetection/blob/51df8a9b7ad5f25ebd75cf8e0969c3b728bde08d/configs/fcos/fcos_r50_caffe_fpn_gn_1x_4gpu.py#L11) .

Thus, I'm wondering the details on how `GN` is used in FCOS. Is it only used in head ?

Thank you.

**Comment by ZwwWayne** [comment]
Hi @ElectronicElephant ,
The configs should match the results in the README.
For the details, you can refer to the [paper](https://arxiv.org/pdf/1904.01355.pdf), they indeed only add GN in the head.

**Comment by ElectronicElephant** [comment]
Hi @ZwwWayne ,

Thank you for your reply! 

Just to confirm, you have implemented the **improvement** `“ctr.  on reg.”:  moving the center-ness branch to the regression branch`, but not `center sampling`.

Am I right?

If I'm right, I have implemented the `center sampling` proposed in the original paper and I'm testing it now. Would you welcome a pull request to add `center sampling` ?

**Comment by ElectronicElephant** [comment]
#2206
