### ISSUE TITLE
Question about how to do multi-machine multi-gpu training?

### ISSUE THREAD

**Issue by hanjianhua44** [open-mmlab/mmdetection#2190]
In pytorch way, we just need to add --nodes, --node_rank, --master_addr, --master port, OR should we do something else like to set 
1. model = DistributedDataParallel(model, device_ids=[i], output_device=i) 
2. dist.init_process_group(backend=backend, init_method="env://")
in mmdetection?

**Comment by ZwwWayne** [comment]
You can still add those options in the [dist_train.sh](https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh). 
Modification of the code should be unnecessary.
