### ISSUE TITLE
ModuleNotFoundError: No module named 'cityscapesscripts' 

### ISSUE THREAD

**Issue by BigBaiNUE** [open-mmlab/mmdetection#2194]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
ModuleNotFoundError: No module named 'cityscapesscripts'

After I installed mmdetetetection V 1.1 according to the guide in a totally new environment, I ran train.py and reported the error above. It can't be solved by reinstalling mmdet completely for many times.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/atss/atss_r50_fpn_1x.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I did not make any modifications on the code or config.
3. What dataset did you use?
My own dataset, in coco format, works well in previous versions of mmdet.
**Environment**

1. sys.platform: linux
Python: 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
PyTorch: 1.2.0+cu92
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
- NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,cod[1/1937]
-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.2
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp
-DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno
-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflo
w -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-erro
r=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trap
ping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR
=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.4.0+cu92
OpenCV: 4.1.1
MMCV: 0.3.2
MMDetection: 1.1.0+51df8a9
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "tools/train.py", line 14, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/root/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/root/mmdetection/mmdet/apis/inference.py", line 12, in <module>
    from mmdet.datasets.pipelines import Compose
  File "/root/mmdetection/mmdet/datasets/__init__.py", line 2, in <module>
    from .cityscapes import CityscapesDataset
  File "/root/mmdetection/mmdet/datasets/cityscapes.py", line 9, in <module>
    import cityscapesscripts.evaluation.evalInstanceLevelSemanticLabeling as CSEval
```

**Bug fix**
Hope to get a solution as soon as possible, thanks!

**Comment by CMobley7** [comment]
I can confirm this issue in the master branch. It wasn't an issue as of last Friday, 28FEB20; so, it must have been introduced by changes made over the weekend. I'm testing 1.1 now to see if this bug affects that branch as well.

**Comment by CMobley7** [comment]
@BigBaiNUE, I've checked and this bug appears to only affect the master branch not v1.1. I'm not sure how you installed `mmdetection`; however, I'd suggest using `pip3 install -e git+https://github.com/open-mmlab/mmdetection.git@v1.1.0#egg=mmdet`

**Comment by PanJianning** [comment]
`pip3 install -r requirements.txt`

**Comment by BigBaiNUE** [comment]
> 
> 
> @BigBaiNUE, I've checked and this bug appears to only affect the master branch not v1.1. I'm not sure how you installed `mmdetection`; however, I'd suggest using `pip3 install -e git+https://github.com/open-mmlab/mmdetection.git@v1.1.0#egg=mmdet`

Thank you for prompt reply. I installed it according to INSTALL.md steps. Your guidance is feasible, and now it works. Thx :-D

**Comment by BigBaiNUE** [comment]
> 
> 
> `pip3 install -r requirements.txt`

Thanks for reply.I completed this step and showed that the conditions were satisfied, but the problem still happened. It's solved by  using pip3 install -e git+https://github.com/open-mmlab/mmdetection.git@v1.1.0#egg=mmdet.

**Comment by soldier828** [comment]
> `pip3 install -r requirements.txt`

I solved by this. Thank U!!

**Comment by hellock** [comment]
Please read the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md#prepare-datasets). It is stated in the docs that you need to run `pip install cityscapesscripts` and also convert the dataset format if you are working with cityscapes.
