### ISSUE TITLE
How empty tensor is handled?

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#220]
After box regression step, there might be no positive boxes for mask branch, then the input of mask branch is an empty tensor. Did you consider and handle this case?

**Comment by hellock** [comment]
The input of mask branch is the original proposals plus gt bboxes, as in Detectron.

**Comment by thangvubk** [comment]
But in inference step we dont have gt bboxes.

**Comment by hellock** [comment]
You mean there is no bbox with scores greater than 0.05 (score_thr)?

**Comment by hellock** [comment]
During inference, if no bbox is detected, then mask branch will return empty results, see [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/test_mixins.py#L99) for details.
