### ISSUE TITLE
format_only in test.py doesn't allow users to set a file_prefix

### ISSUE THREAD

**Issue by CMobley7** [open-mmlab/mmdetection#2201]
In a relatively recent commit, `json_out` has been replaced with the argument `--format_only` in `test.py`. Moving to this makes sense from a generalization standpoint. However, there is now no way to specify the `file_prefix` or at least no way that I know of; so, `format_results` saves the file to a tmp directory, instead of where the user wants it using the default `test.py` script. If possible, I'd suggest adding another `arg` to `test.py`, to allow for this functionality, which was lost, to be added back in. This `arg` would allows the user to set a `file_prefix`, which will set `jsonfile_prefix` when using coco; so that, for `results2json` output the file with the correct name and location. Thanks in advance.

**Comment by ZwwWayne** [comment]
Hi @CMobley7 ,
Actually, you can do that. Please check the 4th test example in the [doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md)
