### ISSUE TITLE
where is Mixed Precision Training  set in config

### ISSUE THREAD

**Issue by jy1023408440** [open-mmlab/mmdetection#2204]
how to Mixed Precision Training

**Comment by yhcao6** [comment]
Here are the example configs of Mixed Precision Training:
https://github.com/open-mmlab/mmdetection/tree/master/configs/fp16.

As long as your favorite model support mixed precision training in the current implementation, you only need to add these 2 lines like above examples in the corresponding config to start mix precision training
https://github.com/open-mmlab/mmdetection/blob/51df8a9b7ad5f25ebd75cf8e0969c3b728bde08d/configs/fp16/faster_rcnn_r50_fpn_fp16_1x.py#L1-L2

**Comment by jy1023408440** [comment]
ok,thanks

**Comment by shubhamiit** [comment]
How do I know if a model supports mixed precision training?
