### ISSUE TITLE
How can I get proposal_file from my own dataset?

### ISSUE THREAD

**Issue by Magsun** [open-mmlab/mmdetection#2207]
Hello, thanks so much for providing this fantastic frame to help us train our own instance segmentation model.

Here's my question:
I have my own 3 label dataset and coverted it into coco style, while I'm trying to use mmdetec train model listed below, I don't know how to get proposal_files it needed.

Model: 
Fast R-CNN (with pre-computed proposals) 
R-50-FPN

Files I don't know how to get:
proposal_file=data_root + 'proposals/rpn_r50_fpn_1x_train2017.pkl'
proposal_file=data_root + 'proposals/rpn_r50_fpn_1x_val2017.pkl',
proposal_file=data_root + 'proposals/rpn_r50_fpn_1x_val2017.pkl',

Thanks again, hope someone can help me on this.

**Comment by hellock** [comment]
You need to generate the proposal file with a RPN model first.

**Comment by wtt848** [comment]
Excuse me, are you training rpn alone? I am using guaid anchor. But I don't know what the reasonable process is, whether to use ga-faster rcnn directly or try ga-rpn to generate proposal and then apply it to ga-faster rcnn, but how does proposal apply to ga-faster rcnn? I read resd me without relevant information, and hope to get your reply.

**Comment by wtt848** [comment]
> You need to generate the proposal file with a RPN model first.

Excuse me, are you training rpn alone? I am using guaid anchor. But I don't know what the reasonable process is, whether to use ga-faster rcnn directly or try ga-rpn to generate proposal and then apply it to ga-faster rcnn, but how does proposal apply to ga-faster rcnn? I read resd me without relevant information, and hope to get your reply.
