### ISSUE TITLE
when mutil-gpu training, the training process won't move on

### ISSUE THREAD

**Issue by QuentinAI** [open-mmlab/mmdetection#2208]
when 2-gpu training:
once training till 2nd epoch,  the training process won't move on and stuck for a long time, can't move to 3rd epoch. No matter when I train it from the start or from checkpoint,e.g. epoch_1.path
No error display.
How can I solve it?
Thanx!
Env:py 3.6.9, cuda 10.1, cudnn 7.6.3, nvidia driver version 418.39, pytorch 1.3.0.
Hardware is Titan X Pascal.
@hellock

**Comment by QuentinAI** [comment]
[20200306_124530.log](https://github.com/open-mmlab/mmdetection/files/4298518/20200306_124530.log)
That's my log.
And this is my running commands:
`./tools/dist_train.sh configs/faster_rcnn_r50_fpn_1x.py 2 --validate --work_dir work_dirs --resume_from work_dirs/epoch_1.pth`

**Comment by marcosly** [comment]
> [20200306_124530.log](https://github.com/open-mmlab/mmdetection/files/4298518/20200306_124530.log)
> That's my log.
> And this is my running commands:
> `./tools/dist_train.sh configs/faster_rcnn_r50_fpn_1x.py 2 --validate --work_dir work_dirs --resume_from work_dirs/epoch_1.pth`

I got the same issue, did you fix it

**Comment by xvjiarui** [comment]
Hi @marcosly @QuentinAI 
MMdet v2.0 has been released. You may check it out to see if the problem still exists. 
I will close this issue for now. Please feel free to reopen it.
