### ISSUE TITLE
Tutorial for configs options

### ISSUE THREAD

**Issue by tiberium24** [open-mmlab/mmdetection#2210]
Hello,

I would like to train some of those detectors using your config files. Is there any explanation of those parameters within the code? For example in faster_rcnn_r101_fpn_1x.py:
```
rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1)
```

**Comment by PanJianning** [comment]
For me, I use github search and read the corresponding documentation in the source code. [max_iou_assigner.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/assigners/max_iou_assigner.py#L8)

**Comment by hellock** [comment]
As @PanJianning suggested, you can just read the docstring of corresponding classes. We will improve the documentation.
