### ISSUE TITLE
Deformable depth-wise convolution is time-consuming

### ISSUE THREAD

**Issue by v-qjqs** [open-mmlab/mmdetection#2211]
I do mask-rcnn-fpn experiments. ShuffleNetV2 is used as backbone and ModulatedDeformConvPack is also adopted for backbone at the last three stage.  I scale the size of ShuffleNetV2 backbone so as to have comparable flops with res-50 backbone.  Since depth-wise convolution is used in ShuffleNetV2 block, I notice it's very time-consuming when adopting deformable convolution for depth-wise case, see below: 
![image](https://user-images.githubusercontent.com/34116221/76136578-e18c6e00-606d-11ea-9e9c-104618624aab.png)

But it's fine when no deformable convolution is used in ShuffleNetV2 backbone, see below:
![image](https://user-images.githubusercontent.com/34116221/76136581-e6512200-606d-11ea-8a06-b827e3608687.png)

Meanwhile, the time cost in mask-rcnn-res50_fpn_mdconv_c3-c5 case is reasonable, see below:
![image](https://user-images.githubusercontent.com/34116221/76136692-704dba80-606f-11ea-9893-a98bec90f9d4.png)

So roughly the time cost in the first figure is 4x of that in the second figure.  And computation cost in the first figure is roughly 4x of that in the third figure, even if res-50 and scaled ShuffleNetV2 backbone have comparable flops. I wonder if anyone can help me. Thanks a lot.

Hardware: 8 GeForce RTX 2080 Ti GPU
Software environment: Python 3.5.2, PyTorch 1.3.1, CUDA 10.0.130, CUDNN 7.5.0

**Comment by ZwwWayne** [comment]
Hi @v-qjqs ,
This might because the DCN implementation does not optimize much for the depth-wise setting, usually the group size is at most 64.
Therefore, for now, I am afraid that we cannot do much help here.
