### ISSUE TITLE
Some doubts about the anchor generator.py

### ISSUE THREAD

**Issue by Owen-Fish** [open-mmlab/mmdetection#2222]
hello, awsome contributers. today, when I am reading the source code about anchor generator  in mmdet/core/anchor/anchor_generator.py . 
these lines are make me confused.
`def gen_base_anchors(self):
        ...

        **h_ratios = torch.sqrt(self.ratios)
        w_ratios = 1 / h_ratios**
        if self.scale_major:
            ...

here h_ratios and w_ratios are reverse with my inference. here is my inference:
assume the area of anchor is 1, and anchors with different aspect ratios has same area. so:

w*h = 1
w/h= ratios
so : h =  1 / sqrt(ratios) , w = sqrt(ratios)

this seems like the inverse branch of the original code. I alse find the similiar implements  in faster-rcnn source code. That's confused me a lot. :(

Help me ~

**Comment by ZwwWayne** [comment]
Hi @Owen-Fish ,
The goal is to keep the anchors have the same area.

**Comment by Owen-Fish** [comment]
Thanks&nbsp;for&nbsp;your&nbsp;reply.&nbsp;I&nbsp;know&nbsp;that&nbsp;operation&nbsp;is&nbsp;to&nbsp;keep&nbsp;anchor&nbsp;area&nbsp;the&nbsp;same&nbsp;when&nbsp;apply&nbsp;multiple&nbsp;ratios.&nbsp;But&nbsp;I&nbsp;still&nbsp;wondering&nbsp;that&nbsp;that&nbsp;h_ratio&nbsp;and&nbsp;w_ratio&nbsp;may&nbsp;change&nbsp;there&nbsp;position.


---Original---
