### ISSUE TITLE
Request to bump up Pillow dependency version

### ISSUE THREAD

**Issue by farleylai** [open-mmlab/mmdetection#2224]
With the latest stable release of `torchvision` that has addressed the [PILLOW_VERSION issue](https://github.com/pytorch/vision/issues/1712), the requirements of Pillow <=6.2.2 should be relaxed.

**Comment by ZwwWayne** [comment]
Hi @farleylai ,
Thanks for your suggestion. However, since we still need to support Pytorch 1.1, we cannot relax the requirement yet. And the version of Pillow 6.2.2 or 7.0 does not affect the use.
