### ISSUE TITLE
Problems with cityscapes evaluation

### ISSUE THREAD

**Issue by mirmashel** [open-mmlab/mmdetection#2228]
Hello 
I have a problem with cityscapes evaluation
I have downloaded cityscapes dataset and prepare it with this:
```
pip install cityscapesscripts
python tools/convert_datasets/cityscapes.py ./data/cityscapes --nproc 8 --out_dir ./data/cityscapes/annotations
```

And pretrained model of faster-rcnn from [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/cityscapes)

And when i trying to evaluate with this command:
```./tools/dist_test.sh configs/cityscapes/faster_rcnn_r50_fpn_1x_cityscapes.py checkpoints/faster_rcnn_r50_fpn_1x_cityscapes_20200227-362cfbbf.pth 4 --eval bbox```
I get this results:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
```

What should i do to fix it?

**Comment by xvjiarui** [comment]
Hi @mirmashel ,
To evaluate the performance on `val` split, you need to change configs from test to val here [here](https://github.com/open-mmlab/mmdetection/blob/9b9e4a90356be8ff2a9110b92aba2f2319b21507/configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py#L163-L168) .

**Comment by DoveJay** [comment]
> Hi @mirmashel ,
> To evaluate the performance on `val` split, you need to change configs from test to val here [here](https://github.com/open-mmlab/mmdetection/blob/9b9e4a90356be8ff2a9110b92aba2f2319b21507/configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py#L163-L168) .

it doesn't work
