### ISSUE TITLE
How to use  Albumentations？can you give me an example？

### ISSUE THREAD

**Issue by 18804601171** [open-mmlab/mmdetection#2229]

**Comment by PanJianning** [comment]
[configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)

**Comment by 18804601171** [comment]
@PanJianning How to use some augmentions  in albumentations?

**Comment by PanJianning** [comment]
> @PanJianning How to use some augmentions in albumentations?

Why don't you just look at the examples？

**Comment by yustaub** [comment]
> [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)

@PanJianning  I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply

**Comment by SISTMrL** [comment]
how to add the albumentations into voc0712.py, I know that I need to add albu_train_transforms list before the train_pipeline, But i'm not sure to modify the train_pipeline.
I see the mask_rcnn_r50_fpn_albu_1x_coco.py, there are keymap and meta_keys,should i delete them?

**Comment by lh0515** [comment]
> > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> 
> @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply

Do you have the answer? I have the same problem.

**Comment by yustaub** [comment]
> > > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> > 
> > 
> > @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply
> 
> Do you have the answer? I have the same problem.

this should depends on your dataset

**Comment by lh0515** [comment]
> > > > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> > > 
> > > 
> > > @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply
> > 
> > 
> > Do you have the answer? I have the same problem.
> 
> this should depends on your dataset



> > > > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> > > 
> > > 
> > > @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply
> > 
> > 
> > Do you have the answer? I have the same problem.
> 
> this should depends on your dataset

Thank you for your reply。I use a medical image data set, why would this cause this situation？So should I use data augmentation？

**Comment by yustaub** [comment]
> > > > > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> > > > 
> > > > 
> > > > @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply
> > > 
> > > 
> > > Do you have the answer? I have the same problem.
> > 
> > 
> > this should depends on your dataset
> 
> > > > > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> > > > 
> > > > 
> > > > @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply
> > > 
> > > 
> > > Do you have the answer? I have the same problem.
> > 
> > 
> > this should depends on your dataset
> 
> Thank you for your reply。I use a medical image data set, why would this cause this situation？So should I use data augmentation？

you can analysis your dataset and choose which aug should be effective.

**Comment by lh0515** [comment]
> > > > > > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> > > > > 
> > > > > 
> > > > > @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply
> > > > 
> > > > 
> > > > Do you have the answer? I have the same problem.
> > > 
> > > 
> > > this should depends on your dataset
> > 
> > 
> > > > > > [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_1x.py)
> > > > > 
> > > > > 
> > > > > @PanJianning I want to know why the ap is lower with ablu data aug than without ablu? very appreciate for your reply
> > > > 
> > > > 
> > > > Do you have the answer? I have the same problem.
> > > 
> > > 
> > > this should depends on your dataset
> > 
> > 
> > Thank you for your reply。I use a medical image data set, why would this cause this situation？So should I use data augmentation？
> 
> you can analysis your dataset and choose which aug should be effective.

Ok, thank you very much

**Comment by muyuuuu** [comment]
> Why don't you just look at the examples？

because the link is 404.

**Comment by kbyokin** [comment]
> > Why don't you just look at the examples？
> 
> because the link is 404.

@muyuuuu Try to check on [configs/albu_example/mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py)

**Comment by M-Amrollahi** [comment]
How we can specify different pipeline for train and val set with albumentation?
