### ISSUE TITLE
Meet error at writing custom modules

### ISSUE THREAD

**Issue by qijiezhao** [open-mmlab/mmdetection#223]
Hi, Kai Chen:

Thanks for your amazing contribution to this repo. Recently, I was working to reproduce M2Det(https://qijiezhao.github.io/imgs/m2det.pdf, and then plus focalloss to speedup the training process) based on mmdetection, and I met some problems that unsolved, can you please give me some advice?

I follow the suggestion of TECHNICAL_DETAILS.md:
1, write the mlfpn.py in the path of ./mmdet/models/necks/
2, modify the neck config of RetinaNet config file.

When I run the training command, it says:
`
zhaoqijie@work1:~/mmdetection$ sh run_train_m2det.sh 
2019-01-03 18:03:44,001 - INFO - Distributed training: False
Traceback (most recent call last):
  File "tools/train.py", line 96, in <module>
    main()
  File "tools/train.py", line 79, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/zhaoqijie/anaconda3/lib/python3.6/site-packages/mmdet-0.5.5+unknown-py3.6.egg/mmdet/models/builder.py", line 57, in build_detector
    return build(cfg, detectors, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zhaoqijie/anaconda3/lib/python3.6/site-packages/mmdet-0.5.5+unknown-py3.6.egg/mmdet/models/builder.py", line 24, in build
    return _build_module(cfg, parrent, default_args)
  File "/home/zhaoqijie/anaconda3/lib/python3.6/site-packages/mmdet-0.5.5+unknown-py3.6.egg/mmdet/models/builder.py", line 16, in _build_module
    cfg, parrent, default_args)
  File "/home/zhaoqijie/anaconda3/lib/python3.6/site-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/utils.py", line 72, in obj_from_dict
    return obj_type(**args)
TypeError: 'module' object is not callable
`

I have tested the single mlfpn.py file and it has no bugs any more.

So why "module object is not callable" happened? Thanks for you kind help!

**Comment by hellock** [comment]
Hi @qijiezhao, you need to modify `mmdet/models/necks/__init__.py` to import your own module to a higher level, so that it can be discovered in the config file.
Adding custom modules can be made more convenient and we will improve it later.

**Comment by qijiezhao** [comment]
> Hi @qijiezhao, you need to modify `mmdet/models/necks/__init__.py` to import your own module to a higher level, so that it can be discovered in the config file.
> Adding custom modules can be made more convenient and we will improve it later.

Thanks for your reply!
Yes, I have done this step before I wrote this issue:

`
from .mlfpn import MLFPN
from .fpn import FPN

__all__ = ['FPN', 'MLFPN']
`

**Comment by hellock** [comment]
Did you use `python setup.py install` or `python setup.py develop` to install mmdetection?

**Comment by qijiezhao** [comment]
Yeah, I have tried(the two commands didn't show errors), but the Error Information(module object is not callable) is still unchanged.

**Comment by hellock** [comment]
That's weird, how about the config file?
