### ISSUE TITLE
Cuda error during recognition

### ISSUE THREAD

**Issue by rusanager** [open-mmlab/mmdetection#2230]
Hi!
I use mmdetection for recognition in my django project. I was build mmdetection from docker image and import init_detector and inference_detector. I get error: 
`Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`
My vps does not provide gpu and I want use cpu. My neural network was trained in google colab with gpu. 
How can i fix it? What is the best way to use recognition in a web project?

**Comment by ZwwWayne** [comment]
Hi @rusanager ,
You can change the model weight to CPU tensor and load it in your other project.
