### ISSUE TITLE
 multi-scale test of htc doesn't work

### ISSUE THREAD

**Issue by PKUbahuangliuhe** [open-mmlab/mmdetection#2235]
Hello, I train a htc-config(x101-32*4d+dcn+multi-scale trainning) for my baseline, but multi-scale test only gets 0.1 mAP increment compared to the single-scale test

**Comment by hanjianhua44** [comment]
Can you show me the test pipeline you used in htc ms test config file?

**Comment by PKUbahuangliuhe** [comment]
> 
> 
> Can you show me the test pipeline you used in htc ms test config file?

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(1333, 800), (1333, 400), (1333, 500), (1333, 600), (1333, 700), (1333, 900), (1333, 1000), (1333, 1100), (1333, 1200)],
        #img_scale=[(1333, 800),(2000,400),(2000,500),(2000,600),(2000,700),(2000,900),(2000,1000),(2000,1100),(2000,1200)],
        #img_scale=(1333, 800),
        flip=True,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

**Comment by ZwwWayne** [comment]
Fixed in https://github.com/open-mmlab/mmdetection/pull/2944.
