### ISSUE TITLE
The multi-scale test of HTC only brings 0.1mAP of increment

### ISSUE THREAD

**Issue by PKUbahuangliuhe** [open-mmlab/mmdetection#2236]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
```
The multi-scale test of HTC only brings 0.1mAP of increment compared to the single-scale test. As a result, single-scale test result is 51.6.However,I use the multi-scale test in mmdetection and the result is 51.7.
```

**Reproduction**
1. What command or script did you run?
```
./tools/dist_train.sh configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py 8
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
```
I remove the mask and semantic head in the config,that is to say,I only keep the detection part. And I replace the x101-64-4d with Dual-x101-32-4d (CBNet). 
```

3. What dataset did you use?
```
MS-COCO
```
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
```
The environment is ok.
```
**Error traceback**
If applicable, paste the error trackback here.
```
No error occurs.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
To use multi scale test, for example two scales (1333, 800),(1600,960) and flip, you need to change the `test_pipeline` of the config from
```
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
```
to
```
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(1333, 800), (1600, 960)],
        flip=True,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
```
It can boost box AP of [htc_r50_fpn](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_r50_fpn_1x.py) from 42.1 to 43.6.
