### ISSUE TITLE
Mem (GB) difference between pascal_voc and coco for the same model?

### ISSUE THREAD

**Issue by PCML-WangZhe** [open-mmlab/mmdetection#224]
why Mem (GB) needed of the same model for different datasets(eg: pascal_voc and coco) are so different?

**Comment by yhcao6** [comment]
coco use larger batch size

**Comment by hellock** [comment]
For SSD, the main difference is the batch size and num of gt bboxes. And for two-stage detectors, the default image scale is not the same for two datasets, and the number of gt bboxes also leads to different memory.

**Comment by Stewarttzy** [comment]
the number of category is different also
