### ISSUE TITLE
Testing trained model, no saved images

### ISSUE THREAD

**Issue by tiberium24** [open-mmlab/mmdetection#2240]
Hello,

I am trying to run this:

`./tools/dist_test.sh custom_configs/cascade_rcnn_r50_fpn_1x.py work_dirs/cascade_rcnn_r50_fpn_1x/epoch_25.pth 4 --format_only --options "outfile_prefix=./cascade_rcnn_r50_fpn_1x_results" `

No images with detection results are however saved to any output folder. Do you know why? 
It would be nice to have the detections results on images saved.

**Comment by suntaiwu** [comment]
+1

**Comment by hellock** [comment]
It will not save images by default. The above command saves the detection results in a json file. You can either save it by yourself or visualize the results online by specifying `--show`.

**Comment by Hemantr05** [comment]
You can try using High-level APIs for testing images, it saves the detection as an image.
