### ISSUE TITLE
which style should I use, caffe or pytorch?

### ISSUE THREAD

**Issue by hanjianhua44** [open-mmlab/mmdetection#2249]
I use mmdetection/tools/detectron2pytorch.py to convert resneXt152 from caffe version to pytorch version, after that in my config, I set:
1. add norm_cfg = dict(type="BN", requires_grad=False) in backbone.
2. img_norm_cfg = dict(mean=[102.9801, 115.9465, 122.7717], std=[1.0, 1.0, 1.0], to_rgb=False)
3. norm_eval = True

I wanna know which style should I use, caffe of pytorch?

**Comment by xvjiarui** [comment]
Hi, @hanjianhua44 
The `caffe` style should be used if you converted from caffe ResNet. Just in case, you'd better check the original implementation.
