### ISSUE TITLE
What does "actual epoch = 4 * 3 = 12" mean?

### ISSUE THREAD

**Issue by PCML-WangZhe** [open-mmlab/mmdetection#225]
In configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py 
In line 151 it's "total_epochs = 4  # actual epoch = 4 * 3 = 12"
why the actual epoch is 4*3?

**Comment by hellock** [comment]
See [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py#L98-L99) for details.

**Comment by PCML-WangZhe** [comment]
@hellock OK, I got it, thx

**Comment by ujsyehao** [comment]
@PCML-WangZhe Can you tell me why?

**Comment by ujsyehao** [comment]
@hellock Hi, Why actual epoch = 4 * 3?

**Comment by ujsyehao** [comment]
3 is times?
`    train=dict(
        type='RepeatDataset',  # to avoid reloading datasets frequently
        times=3,`
