### ISSUE TITLE
What would happen if "load_from" and backbone's "pretrained" both not None

### ISSUE THREAD

**Issue by ZTao-z** [open-mmlab/mmdetection#2250]
for example, my backbone uses Resnet 34, but "load_from" model uses Resnet 50.
```
pretrained='modelzoo://resnet34',
backbone=dict(
    type='ResNet',
    depth=34,
)
```
```
load_from = './pretrained/cascade_rcnn_r50_fpn_20e_20181123-db483a09.pth'
```
what would happen? or should I set one of them to None.

**Comment by ZwwWayne** [comment]
It will make the model cannot load the weight correctly and may degrade the performance.
If you need to use ResNet34, than you need to prepare a corresponding backbone or do not use any pre-trained model.

**Comment by ZTao-z** [comment]
thank you
