### ISSUE TITLE
Why using `once_differentiable` at mmdet/ops

### ISSUE THREAD

**Issue by xieshuqin** [open-mmlab/mmdetection#2251]
Hello,

I wonder if there is any specific reason of using `once_differentiable` at several operations (e.g. focal loss, deform_conv, roialign, etc). This requirement raises an exception when computing gradient of gradients at these operations. If there is no particular reason of adding this requirement, is it safe to remove them?

A quick reference to codes that contain this requirement is [sigmoid_focal_loss](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss.py#L23) and [deform_conv](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/dcn/deform_conv.py#L60)

**Comment by hellock** [comment]
Higher-order gradients are not implemented for these operations.
