### ISSUE TITLE
Test_VOC_eval Error: AttributeError: 'list' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by Moderate28** [open-mmlab/mmdetection#2254]

**Comment by Moderate28** [comment]
When i run
python tools/test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py work_dirs/faster_rcnn_r50_fpn_1x_voc0712/latest.pth --out ./evaluation_neudet/faster_rcnn_r50_fpn_1x_voc0712/latest.pkl --eval recall

Error appears:
Traceback (most recent call last):
  File "tools/test.py", line 175, in <module>
    main()
  File "tools/test.py", line 171, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/home/hry/mmdetection/mmdet/datasets/voc.py", line 54, in evaluate
    gt_bboxes, results, proposal_nums, iou_thr, logger=logger)
  File "/home/hry/mmdetection/mmdet/core/evaluation/recall.py", line 91, in eval_recalls
    if proposals[i].ndim == 2 and proposals[i].shape[1] == 5:
AttributeError: 'list' object has no attribute 'ndim'

The proposals in recall.py(line 91) are the input parameter results in voc.py(line 54)

Thanks!

**Comment by yhcao6** [comment]
To evaluate recall of Faster R-CNN, you should use the config of RPN and load the model of Faster R-CNN. 
```
python tools/test.py configs/pascal_voc/rpn_r50_fpn_1x_voc0712.py 
    work_dirs/faster_rcnn_r50_fpn_1x_voc0712/latest.pth --out
```
It should be very easy to adapt `rpn_r50_fpn_1x.py` to `rpn_r50_fpn_1x_voc0712.py`

**Comment by Moderate28** [comment]
> To evaluate recall of Faster R-CNN, you should use the config of RPN and load the model of Faster R-CNN.
> python tools/test.py configs/pascal_voc/rpn_r50_fpn_1x_voc0712.py 
>     work_dirs/faster_rcnn_r50_fpn_1x_voc0712/latest.pth --out
> 
> It should be very easy to adapt rpn_r50_fpn_1x.py to rpn_r50_fpn_1x_voc0712.py

Thanks! Your solution works!
