### ISSUE TITLE
fail to train when reaching roi_align

### ISSUE THREAD

**Issue by Doubiiu** [open-mmlab/mmdetection#2255]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when I train the cascade_mask_rcnn_r101_fpn_1x on my own dataset(COCO format). It reports an error.
THCudaCheck FAIL file=mmdet/ops/roi_align/src/roi_align_kernel.cu line=140 error=48 : unrecognized error code
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    meta=meta)
  File "/content/drive/My Drive/mmdetection/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/content/drive/My Drive/mmdetection/mmdet/apis/train.py", line 231, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 371, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 275, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/content/drive/My Drive/mmdetection/mmdet/apis/train.py", line 75, in batch_processor
    losses = model(**data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/content/drive/My Drive/mmdetection/mmdet/models/detectors/base.py", line 147, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/content/drive/My Drive/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 246, in forward_train
    rois)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/content/drive/My Drive/mmdetection/mmdet/models/roi_extractors/single_level.py", line 105, in forward
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/mmdetection/mmdet/ops/roi_align/roi_align.py", line 83, in forward
    self.sample_num)
  File "/content/drive/My Drive/mmdetection/mmdet/ops/roi_align/roi_align.py", line 28, in forward
    sample_num, output)
RuntimeError: cuda runtime error (48) : unrecognized error code at mmdet/ops/roi_align/src/roi_align_kernel.cu:140
**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/cascade_mask_rcnn_r101_fpn_1x.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I modified:
    #1:initial lr to 0.0025
    #2:dataset to MyDataset
    #3dataset path
3. What dataset did you use?
My own dataset with COCO format and I set dummy "segmentation" in annotations as a rect.
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
------------------------------------------------------------
sys.platform: linux
Python: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: Tesla T4
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.1.2
MMCV: 0.3.2
MMDetection: 1.1.0+58a3f02
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.0
------------------------------------------------------------
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
pip
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
in the above
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
Could you check the inputs of RoIAlign?

**Comment by 36572545** [comment]
features torch.Size([2, 256, 192, 336]):tensor([[[[-0.0050,  0.2370,  0.2255,  ...,  0.1895,  0.1051,  0.1385],
          [ 0.5962,  0.9160,  0.8330,  ...,  0.3827,  0.3032,  0.4318],
          [ 0.6375,  0.9799,  0.9135,  ...,  0.4774,  0.2881,  0.4137],
          ...,
          [ 0.2530,  0.5929,  0.5987,  ...,  0.7763,  0.7447,  0.7125],
          [ 0.3878,  0.6201,  0.6405,  ...,  0.8578,  0.8493,  0.6303],
          [ 0.4015,  0.8213,  0.7153,  ...,  0.7806,  0.6855,  0.6307]],

         [[ 0.0609,  0.3267,  0.3663,  ...,  0.3154,  0.3082, -0.0101],
          [-0.1850,  0.1682,  0.2441,  ...,  0.5096,  0.5171,  0.2380],
          [-0.0743,  0.2516,  0.2625,  ...,  0.5761,  0.6001,  0.2941],
          ...,
          [ 0.1131, -0.2255, -0.1935,  ..., -0.3602, -0.3080, -0.2843],
          [ 0.2702, -0.0799, -0.0869,  ..., -0.2294, -0.2592, -0.3342],
          [ 0.1552,  0.1295,  0.1514,  ..., -0.1555, -0.2017, -0.0423]],

         [[-0.7865, -0.7133, -0.6435,  ..., -1.2243, -1.2783, -0.5991],
          [-1.4214, -1.7059, -1.6424,  ..., -2.0914, -2.0929, -0.9063],
          [-1.3250, -1.5894, -1.5086,  ..., -1.9030, -1.9281, -0.7793],
          ...,
          [-1.3926, -1.6262, -1.5923,  ..., -1.1939, -1.1430, -0.0577],
          [-1.3848, -1.5334, -1.5291,  ..., -1.1286, -1.0788, -0.0224],
          [-0.6787, -0.5295, -0.5262,  ..., -0.8101, -0.7975, -0.2224]],

         ...,

         [[-0.0117,  0.3464,  0.2415,  ...,  0.5629,  0.6269,  0.8780],
          [-0.3608, -0.1705, -0.2100,  ...,  0.0219,  0.1714,  0.5790],
          [-0.4887, -0.3861, -0.3780,  ..., -0.1161,  0.0426,  0.4508],
          ...,
          [ 0.1850,  0.5132,  0.4530,  ..., -0.1513, -0.0869,  0.2579],
          [ 0.0572,  0.2996,  0.2774,  ..., -0.3270, -0.2302,  0.1760],
          [-0.2006,  0.1227,  0.1242,  ..., -0.2585, -0.1907,  0.0169]],

         [[ 0.0502,  0.5712,  0.4515,  ...,  0.1114, -0.0592,  0.2690],
          [-0.5718,  0.0065, -0.0702,  ..., -0.0449, -0.3717,  0.0127],
          [-0.4816, -0.0481, -0.0359,  ...,  0.0176, -0.1751,  0.1733],
          ...,
          [-0.4858, -0.5319, -0.5506,  ..., -0.4938, -0.6163, -0.3136],
          [-0.6205, -0.5656, -0.4975,  ..., -0.3767, -0.5394, -0.1839],
          [-0.4771, -0.5065, -0.4260,  ..., -0.2896, -0.3717, -0.1507]],

         [[ 0.9020,  1.2116,  1.1187,  ...,  0.3261,  0.3602,  0.3727],
          [ 1.5665,  1.8584,  1.7613,  ...,  0.7347,  0.7442,  0.6206],
          [ 1.5017,  1.8667,  1.8270,  ...,  0.8302,  0.7808,  0.6144],
          ...,
          [ 1.0014,  1.1074,  1.0364,  ...,  0.6326,  0.7449,  0.5265],
          [ 0.9724,  0.9792,  0.8916,  ...,  0.5823,  0.6490,  0.3588],
          [ 1.1353,  1.1233,  0.9388,  ...,  0.5954,  0.5461,  0.1506]]],


        [[[-0.0257,  0.1672,  0.1279,  ...,  0.2477,  0.2636,  0.2094],
          [ 0.4950,  0.6568,  0.5870,  ...,  0.4867,  0.5050,  0.6325],
          [ 0.5165,  0.6515,  0.6410,  ...,  0.5952,  0.4860,  0.6312],
          ...,
          [-0.0434,  0.3575,  0.3825,  ...,  0.8312,  0.7304,  0.9454],
          [ 0.1102,  0.4025,  0.4339,  ...,  0.9314,  0.8864,  0.9017],
          [ 0.2628,  0.6309,  0.5253,  ...,  0.6371,  0.5613,  0.5570]],

         [[-0.0049,  0.2038,  0.2638,  ...,  0.2421,  0.2267,  0.1614],
          [-0.2935,  0.0814,  0.1785,  ...,  0.4930,  0.3527,  0.3129],
          [-0.2017,  0.1626,  0.1988,  ...,  0.4646,  0.3928,  0.3687],
          ...,
          [ 0.3690,  0.0032,  0.0228,  ...,  0.1558,  0.1456,  0.2216],
          [ 0.5158,  0.1361,  0.1198,  ...,  0.2799,  0.1985,  0.1588],
          [ 0.2546,  0.1027,  0.1159,  ..., -0.0844, -0.1193,  0.2006]],

         [[-0.9412, -0.8587, -0.7762,  ..., -0.8740, -0.8296, -0.4025],
          [-1.5083, -1.7512, -1.6856,  ..., -1.4240, -1.4214, -0.5634],
          [-1.3935, -1.6080, -1.5242,  ..., -1.2625, -1.2131, -0.4260],
          ...,
          [-1.1023, -1.4854, -1.4449,  ..., -1.8984, -1.8965, -0.5641],
          [-1.1045, -1.4086, -1.3999,  ..., -1.8397, -1.8282, -0.5234],
          [-0.6246, -0.5510, -0.5496,  ..., -0.7943, -0.7882, -0.2069]],

         ...,

         [[ 0.0253,  0.3909,  0.2758,  ...,  0.1204,  0.1664,  0.5334],
          [-0.3375, -0.1175, -0.1719,  ..., -0.5430, -0.4316,  0.1856],
          [-0.4694, -0.3508, -0.3262,  ..., -0.6270, -0.5469,  0.0600],
          ...,
          [ 0.2137,  0.7242,  0.6667,  ..., -0.0082,  0.1112,  0.1400],
          [ 0.0956,  0.5200,  0.5098,  ..., -0.1611, -0.0283,  0.0777],
          [-0.1153,  0.2283,  0.2328,  ..., -0.0701, -0.0377, -0.1027]],

         [[ 0.2020,  0.6861,  0.5780,  ...,  0.1156, -0.0585,  0.2858],
          [-0.3082,  0.2039,  0.0859,  ...,  0.1066, -0.1582,  0.1846],
          [-0.2136,  0.1522,  0.1625,  ...,  0.1933, -0.0107,  0.3131],
          ...,
          [-0.8738, -0.8904, -0.9119,  ..., -0.1286, -0.3310, -0.2173],
          [-1.0142, -0.9413, -0.8752,  ..., -0.0568, -0.2333, -0.0749],
          [-0.6855, -0.8222, -0.7457,  ..., -0.0395, -0.1262, -0.0126]],

         [[ 0.8289,  1.0953,  0.9985,  ...,  0.4713,  0.4514,  0.5613],
          [ 1.3861,  1.5788,  1.4950,  ...,  0.6446,  0.6990,  0.8140],
          [ 1.3215,  1.6146,  1.5610,  ...,  0.7108,  0.7527,  0.7862],
          ...,
          [ 0.7534,  0.7731,  0.6980,  ...,  0.4109,  0.5224,  0.7282],
          [ 0.7342,  0.6556,  0.5652,  ...,  0.4299,  0.4811,  0.5469],
          [ 1.1343,  1.0809,  0.8940,  ...,  0.8276,  0.7859,  0.5047]]]],
       device='cuda:0', grad_fn=<CudnnConvolutionBackward>)
, rois torch.Size([810, 5]):tensor([[  0.0000, 755.4783, 323.9630, 808.6357, 385.2199],
        [  0.0000, 733.4612, 294.2577, 783.4484, 358.3441],
        [  0.0000, 720.8480, 292.6546, 769.4529, 356.5902],
        ...,
        [  1.0000, 522.3984, 583.9924, 583.5753, 651.3859],
        [  1.0000, 390.5507, 234.9045, 417.2459, 269.4191],
        [  1.0000, 901.8758, 411.6084, 956.6341, 477.5273]], device='cuda:0')
, out_h:7
, out_w:7
, spatial_scale:0.25
,sample_num:2
, output torch.Size([810, 256, 7, 7]):tensor: all zero

These are inputs of roi_align_cuda.forward(features, rois, out_h, out_w, spatial_scale,
                                   sample_num, output), thanks!

**Comment by hellock** [comment]
I mean you can debug during training to see if the inputs are invalid when the training crashes.
