### ISSUE TITLE
Why define output and grad of deformable conv in torch.autograd.Function?

### ISSUE THREAD

**Issue by yeoyi519** [open-mmlab/mmdetection#2258]
In deformable conv code, [mmdetection](https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops/dcn/src) and [this](https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/tree/master/src) choose to define and allocate memory for output of forward and grad of backward, but someone else [[1]](https://github.com/BIGKnight/deformable_conv2d_pytorch)[[2]](https://github.com/lbin/DCNv2/tree/master/src/cuda) choose to allocate memory inside cpp file and return the results.
If I move defination and allocation into cpp file, and let cpp function return the results, the forward function is ok, but backward function return None gradient.
I am confused, why their codes is okay?

**Comment by hellock** [comment]
These two implementations are both ok, and we have tried some operators in both ways. You may need to check if your implementation.

**Comment by yeoyi519** [comment]
> These two implementations are both ok, and we have tried some operators in both ways. You may need to check your implementation.

Based on your implementation, I use at::zeros_like to create grads inside cpp file, and let it return grads to backward func, didn't make other changes, and it fails.
So, I want to know, did you test their code directly, or test on modified codes which base on yours?
If you test on modified codes, can you give me some advices or release it officially?
