### ISSUE TITLE
Pascal VOC eval?

### ISSUE THREAD

**Issue by PCML-WangZhe** [open-mmlab/mmdetection#226]
when I finish training on pascal_voc dataset, and test the result by the script:
python tools/test.py <CONFIG_FILE> <CHECKPOINT_FILE> --gpus <GPU_NUM> --out <OUT_FILE>
and I got: AttributeError: 'VOCDataset' object has no attribute 'img_ids'
How to test the result correctly?

**Comment by donglee-afar** [comment]
'img_ids' is one of the attribute of 'cocodataset',
check your training <CONFIG_FILE> or <CHECKPOINT_FILE> and try again?

**Comment by donglee-afar** [comment]
> when I finish training on pascal_voc dataset, and test the result by the script:
> python tools/test.py <CONFIG_FILE> <CHECKPOINT_FILE> --gpus <GPU_NUM> --out <OUT_FILE>
> and I got: AttributeError: 'VOCDataset' object has no attribute 'img_ids'
> How to test the result correctly?

'img_ids' is one of the attribute of 'cocodataset',
check your training <CONFIG_FILE> or <CHECKPOINT_FILE> and try again?

**Comment by PCML-WangZhe** [comment]
I have check it, my setting is right, and I found that the test.py doesn't include voc_eval, I must run the voc evaluation by: 
python tools/voc_eval.py results.pkl ./configs/pascal_voc/cascade_rcnn_r101_fpn_1x_voc2021.py
atfer using test.py script

**Comment by donglee-afar** [comment]
emm，In my understanding， it has three parts:
train, and generate model file
test and generate result file
evaluation the result file and calc map.

**Comment by PCML-WangZhe** [comment]
yeah， the last part can't work by test.py and I should do it in another way.

**Comment by lxtGH** [comment]
@PCML-WangZhe Hi !!! what's results you got? training with default setting? Can you share?

**Comment by Simon-Chen-Wen** [comment]
hi,I make a same error,can you tell me how to solve it? Thanks!

**Comment by xxllp** [comment]
这个项目 文档少 例子少 难道都靠 issue 来维持吗

**Comment by joeythegod** [comment]
> 这个项目 文档少 例子少 难道都靠 issue 来维持吗

I think they have given us enough instructions, or you can write another instruction instead of talking xxx.

**Comment by lxtGH** [comment]
=

> > 这个项目 文档少 例子少 难道都靠 issue 来维持吗
> 
> I think they have given us enough instructions, or you can write another instruction instead of talking xxx.

I agree with you!

**Comment by mathmanu** [comment]
You may be passing the --eval argument while running tools/test.py. Do not do that to evaluate results on voc.
Instead write the results to a pkl file by using --out results.pkl. Then evaluate the results using tools/voc_eval.py

**Comment by b03505036** [comment]
Ty,guys
