### ISSUE TITLE
How can I change the color of the bbox?

### ISSUE THREAD

**Issue by Hemantr05** [open-mmlab/mmdetection#2265]
I am using the ssd_vgg16-caffe config file and would like to know how to change the color of the bounding box and also, convert the class score to percentage.

**Comment by ZwwWayne** [comment]
You might need to set the color [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L193), and use the corresponding arguments indicated by the [doc](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L79)

**Comment by Hemantr05** [comment]
Thanks a ton! Where can I find the class score?

**Comment by ZwwWayne** [comment]
It seems current implementation does not show the score, you might need to add it by yourself.

**Comment by hellock** [comment]
Scores should be already plotted on the bboxes.

**Comment by ZwwWayne** [comment]
Hi @Hemantr05 ,
As reminded by @hellock , I find that I missed this [line](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L134) before, which will plot scores. 
Sorry for misleading before.

**Comment by Hemantr05** [comment]
@hellock, yes it is plotted on the bbox but I wanted to display the same as percentage instead of a probability.
Thanks @ZwwWayne

**Comment by ZwwWayne** [comment]
Maybe you just need to reformat it [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L135) to show what you want.

**Comment by Hemantr05** [comment]
@ZwwWayne yup, making changes there

**Comment by ZwwWayne** [comment]
The issue is closed because the question seems to be answered. Feel free to reopen it if you have any further questions.

**Comment by prajnasb** [comment]
Heya hi
I wanted to change the font_thickness, how can i do that?

**Comment by Ruolingdeng** [comment]
@prajnasb Hey, I also want to change the font_thickness, have you find the solution?

**Comment by wang1528186571** [comment]
> [您可能需要在此处](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L193)设置颜色，并使用[文档指示](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L79)的相应参数[](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L79)

In mmdet 3.0，it is not suitable，please tell me about new version to change color for bbox
