### ISSUE TITLE
How to output result as json format while using python test.py?

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#2267]
test.py used to output json output.
I want to use coco_error_analysis.py, but it seems only accept json format result.
Thanks

**Comment by ZwwWayne** [comment]
Please refer to the 4th example in the section `Test a dataset` of [doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md).

**Comment by thisisi3** [comment]
Thanks!
