### ISSUE TITLE
Bug for class Albu

### ISSUE THREAD

**Issue by hhaAndroid** [open-mmlab/mmdetection#2268]
After albu enhancement, there should be no results ['idx_mapper'] = np.arange (len (results ['bboxes'])) code, otherwise the bbox label every time it is deleted is wrong

![image](https://user-images.githubusercontent.com/17425982/76735024-118aee00-679f-11ea-80e5-32a8bb6e058f.png)
right:
![image](https://user-images.githubusercontent.com/17425982/76735089-27001800-679f-11ea-81ed-693c9a83041e.png)

**Comment by hhaAndroid** [comment]
The correct writing is the following figure

**Comment by xvjiarui** [comment]
Hi @hhaAndroid 
Thanks for your report. Could you please open a PR about it?

**Comment by hhaAndroid** [comment]
ok
