### ISSUE TITLE
how to infer images using mask rcnn

### ISSUE THREAD

**Issue by chenxu93** [open-mmlab/mmdetection#227]
Hi, I have trained my custom dataset (transform to coco format) successfully,which only contain a person class.(person segmentation). But I want to use my trained model to infer a image that it contain a person, I get some errors.I don't how to infer imgae and save the infered image with mask. Would you help me?@hellock . Thank you in advance!

**Comment by OceanPang** [comment]
@chenxu93 The testing process will dump a file called `results.json`. The results (polygons) are saved in this file.

**Comment by chenxu93** [comment]
@OceanPang Thank you, I use 'python tools/test.py configs/mask_rcnn_r50_fpn_1x.py work_dirs/mask_rcnn_r50_fpn_1x/latest.pth --gpus 2 --out result.pkl --eval bbox segm' then get a result.pkl and result.pkl.json file. But I find the 'counts' field in the json file like "_Vib0=bh06G6M3M101N2N2N2F902N5K>PYOSNQf0^20000000000000000000000Til9". What is the meaning of 'counts', and how can I parse it?

**Comment by OceanPang** [comment]
@chenxu93 You can get related codes in [cocoapi](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI) the usage is the same to annotations.

**Comment by SystemErrorWang** [comment]
met the same problem now, i trained mask rcnn in a coco format custom dataset with 2 classes, and came across the following problem:
```
Traceback (most recent call last):
  File "./tools/test.py", line 217, in <module>
    main()
  File "./tools/test.py", line 194, in main
    result_files = results2json_segm(dataset, outputs, args.out)
  File "/mnt/cephfs_new_wj/cv/wangxinrui/code/mmdetection/mmdet/core/evaluation/coco_utils.py", line 200, in results2json_segm
    json_results = segm2json_segm(dataset, results)
  File "/mnt/cephfs_new_wj/cv/wangxinrui/code/mmdetection/mmdet/core/evaluation/coco_utils.py", line 169, in segm2json_segm
    data['score'] = float(mask_score)
TypeError: only size-1 arrays can be converted to Python scalars
```
