### ISSUE TITLE
Is there any plan to implement Double Anchor R-CNN for Human Detection in a Crowd?

### ISSUE THREAD

**Issue by MeepoAII** [open-mmlab/mmdetection#2270]
**Describe the feature**
Is there any plan to implement [Double Anchor R-CNN for Human Detection in a Crowd](https://arxiv.org/pdf/1909.09998.pdf)?

**Motivation**
I am doing some research on pedestrian detection in crowd senariy, and this paper provide a new idea(double anchor) to detect crowd human, I find there is no implementation(or official code) for this paper, So I wonder is there any plan to implement it ? (if not, can i try .....)

**Related resources**
No official code..

**Additional context**
[paper](https://arxiv.org/pdf/1909.09998.pdf)
author's post:
[CrowdHuman+Double Anchor：强强联合，推动密集行人检测技术落地](https://zhuanlan.zhihu.com/p/95253096)

and if there is no plan to implement, can i try? may be take me 1-2months.....

**Comment by ZwwWayne** [comment]
Hi @MeepoAII ,
Recently, we do not have plans for this paper.
Therefore, PRs are welcomed and of course, you can have a try.

**Comment by MeepoAII** [comment]
get it
