### ISSUE TITLE
Missing the json result format output option (--out_json) in test.py

### ISSUE THREAD

**Issue by b03505036** [open-mmlab/mmdetection#2272]
also, lacking of coco_uils.py in mmdet.core, which is existed in previous version.

**Comment by ZwwWayne** [comment]
For JSON output, you may refer the 4th example in the [doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md). The functions in coco_utils.py are refactored into the [coco.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py).
