### ISSUE TITLE
inference_detector is slower then numbers reported by test.py

### ISSUE THREAD

**Issue by i008** [open-mmlab/mmdetection#2273]
So i'm trying to figure this out: when i run the test.py (single gpu) script i get speed number (task/s) close to what i would expect ( and reported in model zoo) but if i use the mmdet.api.inference.inference_detector API im getting far worse results. For instance inferencing one image takes 300ms altough the same models scores 15FPS while running the test.py script.
I thought that maybe the preloading of the data loaders makes this possible, but when i dig deeper i did  not find the data loading to be an bottleneck.

**Comment by i008** [comment]
So it turns out it indeed was related to dataloading, and if i inference using a dataloader with atleast 1 process per gpu i get the same speeds. In that case if ones needs to inference on a huge amount using the api.inference way in a loop will be rather slow.

**Comment by hellock** [comment]
The inference speed is reported with the testing script. If you use high-level inference apis with a for-loop, it will be slower since all operations are sequential.
