### ISSUE TITLE
norm_cfg = dict(type='BN', requires_grad=False) in caffe style

### ISSUE THREAD

**Issue by breezelj** [open-mmlab/mmdetection#2274]
as described in [5.2,](https://arxiv.org/pdf/1906.07155.pdf) eval = True,requires grad = True, why setting requires_grad=False in faster_rcnn_r50_caffe_c4_1x.py, were there other experiments to prove this setting in caffe perform better???

**Comment by ZwwWayne** [comment]
When using the Caffe style backbone, the BN is fixed. 
It has bee a while since our last benchmark, so we are not sure the performance of training BN in the Caffe style backbone.
You can try to train BN in the Caffe style backbone by yourself if you are interested.

**Comment by breezelj** [comment]
Thanks your reply
