### ISSUE TITLE
Bug For test when I use imresize to train and test

### ISSUE THREAD

**Issue by elfpattern** [open-mmlab/mmdetection#2275]
mmdetection version:1.0.rc0+unknown, mmcv:0.2.10
Now , I wanna use imresize to resize my pic to （550*550）, so I  changed those:
1. custom.py, resize_keep_ratio = False
![截图](https://user-images.githubusercontent.com/26590396/76824177-4e172200-6851-11ea-9887-bc95c4533b8f.png)
2. transforms.py, keep_ratio = False
![截图 (1)](https://user-images.githubusercontent.com/26590396/76824204-638c4c00-6851-11ea-98e1-319962fc80d4.png)
I train my model, It is no bug，but,  when I test, there exists a bug:
Command: python3 tools/test.py  mask_rcnn_hrnetv2p_w18_1x.py  epochs/epoch_76.pth --out results.pkl --eval bbox segm 
Results:
![截图 (2)](https://user-images.githubusercontent.com/26590396/76824418-fc22cc00-6851-11ea-9576-09d2e1a14ab6.png)
I try to fix the bug, but failed, when I set above = True, It is right, I don't know what happened?

Question:
Is there a Bug if resize the image ?? or What can I do to resize image online ?

**Comment by ZwwWayne** [comment]
Hi @elfpattern ,
You may need to upgrade your codebase to the newest version. The bug of scale_factors is fixed in the current version.

**Comment by elfpattern** [comment]
@ZwwWayne ok, thx
