### ISSUE TITLE
我使用mmdetection检测类别出错

### ISSUE THREAD

**Issue by YYZ-rose** [open-mmlab/mmdetection#2279]
修改了VOC中的类别信息，但是最终得出的类结果有问题。
我修改的类别信息
CLASSES = ('plane', 'ship', 'storage-tank', 'baseball-diamond','small-vehicle', 'large-vehicle')

这是检测结果

+-----------+-------+--------+--------+-------+
| class     | gts   | dets   | recall | ap    |
+-----------+-------+--------+--------+-------+
| aeroplane | 6215  | 68899  | 0.874  | 0.773 |
| bicycle   | 21153 | 66896  | 0.743  | 0.702 |
| bird      | 5995  | 25085  | 0.742  | 0.670 |
| boat      | 0     | 0      | 0.000  | 0.000 |
| bottle    | 10775 | 114712 | 0.819  | 0.495 |
+-----------+-------+--------+--------+-------+
| mAP       |       |        |        | 0.660 |
+-----------+-------+--------+--------+-------+

结果的五类完全不是我原先设定的五类，这是什么原因导致的

**Comment by ZwwWayne** [comment]
Please use English or English&Chinese for issues.

**Comment by YYZ-rose** [comment]
> Please use English or English&Chinese for issues.

ok，now i sovle it。

**Comment by HankYangg** [comment]
How did you solve this?

> > Please use English or English&Chinese for issues.
> 
> ok，now i sovle it。
how did you solve this?

**Comment by hyd-520** [comment]
兄弟，你怎么解决这个问题的？

**Comment by oreo-lp** [comment]
> How did you solve this?
> 
> > > Please use English or English&Chinese for issues.
> > 
> > 
> > ok，now i sovle it。
> > how did you solve this?

hi, have you solved this problem?

**Comment by oreo-lp** [comment]
> > How did you solve this?
> > > > Please use English or English&Chinese for issues.
> > > 
> > > 
> > > ok，now i sovle it。
> > > how did you solve this?
> 
> hi, have you solved this problem?

i have soloved this problems, i changed my dataset from VOV2007 to VOC2012,
