### ISSUE TITLE
Alternate dataset 

### ISSUE THREAD

**Issue by abhigoku10** [open-mmlab/mmdetection#2282]
@hellock  hi thanks for open sourcing the code  i had few queries 
Q1. have you trained on datasets like cityscape , bdd100k for semantic segmentation
Q2 using which backbone can i get best accuracy on objects like trees , buildings and poles 
Q3 can we use other models to obtain semanttic maps on bdd100k dataset if so which would be the best architecture to choose for 
Thanks in adavance

**Comment by ZwwWayne** [comment]
For Q1, we only train cityscape for instance segmentation and not support BDD100K. PRs are welcomed.
For Q2, we only report the average AP over all the classes on the supported datasets. So we may not be able to give you an exact answer, but usually, the model with higher AP achieves better on all the classes. Therefore, you can directly try the models with the highest AP in the [model zoo](https://github.com/open-mmlab/mmdetection/blob/master/docs/MODEL_ZOO.md) if you want.
For Q3, you might need to use models for semantic segmentation to obtain the semantic maps, e.g., Deeplab V3++ or PSPNet, etc.

**Comment by abhigoku10** [comment]
@ZwwWayne @hellock  thanks for the suggestion on the Q3 , i tried most of  the models and i am getting the following results 
![image](https://user-images.githubusercontent.com/22094053/77228131-38845e00-6bab-11ea-9e43-c1ee0a032540.png)
can you suggest the reason no matter which model i use i get almost like this result

**Comment by ZwwWayne** [comment]
The results seem to be reasonable given that this is a semantic segmentation task.

**Comment by abhigoku10** [comment]
@ZwwWayne  the sky is getting classified or segmented as buildings / trees and this is common in most of the images sometime even the roads are getting segmented as buildings or sky

**Comment by ZwwWayne** [comment]
> @ZwwWayne the sky is getting classified or segmented as buildings / trees and this is common in most of the images sometime even the roads are getting segmented as buildings or sky

You may try the recent technics in semantic segmentation, e.g., using PSPNet, ASPP module, attention modules, etc. Since current MMDetection only focuses on instance segmentation, we may not be able to do much help for semantic segmentation.

**Comment by abhigoku10** [comment]
@ZwwWayne thanks for the support
