### ISSUE TITLE
gcc5.3 but also segment fault

### ISSUE THREAD

**Issue by Sphinxone** [open-mmlab/mmdetection#2284]
gcc 5.3.0
cuda 10.0
torchvision 0.3.0
centos 7

when i use gdb to debug,it report:
Program received signal SIGSEGV, Segmentation fault.
0x00007fff9136da4c in construct<_object*, _object*> (__p=0xb, this=0x555556964618)
    at **/usr/include/c++/4.8.2**/ext/new_allocator.h:120
120             { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
Missing separate debuginfos, use: debuginfo-install glib2-2.56.1-2.el7.x86_64 glibc-2.17-260.el7_6.5.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.5-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXrender-0.9.10-1.el7.x86_64 libuuid-2.23.2-59.el7_6.1.x86_64 libxcb-1.13-1.el7.x86_64 pcre-8.32-17.el7.x86_64

i can not understand why the computer usres  c++/4.8.2 which is old g++,and gcc -v is 5.3.0 now.
i make soft link such as usr/bin/gcc->usr/local/bin/gcc

**Comment by Sphinxone** [comment]
My English is poor,thank you for reading

**Comment by xvjiarui** [comment]
Please provide the environment info generated at the beginning of the log.

**Comment by Sphinxone** [comment]
> Please provide the environment info by run `python mmdet/utils/collect_env.py`.

thank you for your reply and i have tried your suggestion "run python mmdet/utils/collect_env.py"
But it also report segmentation fault(i can not understand) 
when i use 
gdb python3
run collect_env.py
it also reports 
Program received signal SIGSEGV, Segmentation fault.
0x00007fff9136da4c in construct<_object*, _object*> (__p=0xb, this=0x555556964618)
at /usr/include/c++/4.8.2/ext/new_allocator.h:120
120 { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
Missing separate debuginfos, use: debuginfo-install glib2-2.56.1-2.el7.x86_64 glibc-2.17-260.el7_6.5.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.5-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXrender-0.9.10-1.el7.x86_64 libuuid-2.23.2-59.el7_6.1.x86_64 libxcb-1.13-1.el7.x86_64 pcre-8.32-17.el7.x86_64

**Comment by Sphinxone** [comment]
Append:I use pdb find the problem but i do not know how to slove it
compiling_info.cpp will report segmentation fault
Should i delete mmdetection and install all package again?

**Comment by ZwwWayne** [comment]
You might need to clean your compile environment and make sure that GCC-5.3 is used. From your current situation, the bug is very likely caused by the gcc/c++ whose version is below 4.9.

**Comment by dyy0205** [comment]
> get_compiler_version() will report segmentation fault

I also find get_compiler_version() will report segmentation fault, have you fix this problem?
