### ISSUE TITLE
train only person class with COCO2017 and get abnormal result

### ISSUE THREAD

**Issue by alyssa121** [open-mmlab/mmdetection#2288]
**Describe the bug**
I extract person class from COCO2017 train and validation dataset, and get 64115 pics for training and 2693 pics for testing. However, the testing result seems really abnormal:
**************************************************************************************
```
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2693/2693, 12.4 task/s, elapsed: 217s, ETA:     0s
Evaluating bbox...
Loading and preparing results...
DONE (t=1.90s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=41.17s).
Accumulating evaluation results...
DONE (t=4.33s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.009
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.004
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.026
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.059
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.161
```
**************************************************************************************

**Reproduction**
1. What command or script did you run?
training command is:
 `python tools/train.py configs/aaaa/faster_rcnn_r50_fpn_1x_coco.py`

testing command is: 
`python tools/test.py configs/aaaa/faster_rcnn_r50_fpn_1x_coco.py   work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_6.pth --eval bbox`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
 Yes. I use only one gpu. The modifications are: lr = 0.005, num_classes=2, imgs_per_gpu=4, step=[4, 5], total_epochs =6.

3. What dataset did you use?
 COCO2017, the annotation file only contains person label.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

```
sys.platform: linux
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 9.1, V9.1.85
GPU 0,1,2,3,4,5: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.3.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.1a0+d94043a
OpenCV: 3.4.5
MMCV: 0.3.2
MMDetection: 1.1.0+dd88ed6
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.2

```

**Comment by ZwwWayne** [comment]
It seems that you still train an 80-classes detector using the dataset only containing one class. I am not sure whether this will cause the bug you reported, but I suggest you try to train a 1 class detector first.

**Comment by hellock** [comment]
I tried it long ago with the 1x setting and the mAP should be ~53.

**Comment by DoveJay** [comment]
I face the same issue, if you address it, please give me a feedback

**Comment by alyssa121** [comment]
> It seems that you still train an 80-classes detector using the dataset only containing one class. I am not sure whether this will cause the bug you reported, but I suggest you try to train a 1 class detector first.

I've changed some code to fit one class, as "GETTING_STARTED.md" requires. I'm sure I train only one class.

**Comment by alyssa121** [comment]
> I face the same issue, if you address it, please give me a feedback

Not yet. I still confuse about it. Maybe I didn't handle the dataset properly.

**Comment by DoveJay** [comment]
> > I face the same issue, if you address it, please give me a feedback
> 
> Not yet. I still confuse about it. Maybe I didn't handle the dataset properly.

Actually, the visualized detection results are ok, and I have checked the test .json annotation file.
There is no problem, but it still does not work.

**Comment by ZwwWayne** [comment]
Hi  @DoveJay ,
Maybe you can first make sure that the evaluation is conducted on only 1 class rather than 80 classes.

**Comment by ZwwWayne** [comment]
We will release a new version that supports to train on only some categories of coco dataset.

**Comment by alyssa121** [comment]
> ase a new version that supports to train on only some categories of

Thank you very much!

**Comment by alyssa121** [comment]
> We will release a new version that supports to train on only some categories of coco dataset.

Hello, I made some changes as you did in #2340 except that  I set num_classes=2 rather than 81, the AP@0.5 is  almost zero. But when I test single picture with epoch5.pth, the detection result is good:
![result](https://user-images.githubusercontent.com/37036185/78981220-0a62c000-7b52-11ea-8b11-a8ac679ccc3c.jpg)
