### ISSUE TITLE
/ops/roi_align/functions/roi_align.py   An automatic interrupt occurred to the program

### ISSUE THREAD

**Issue by YanHengxu** [open-mmlab/mmdetection#229]
if features.is_cuda:
            print("feature is cuda")
            roi_align_cuda.forward(features, rois, out_h, out_w, spatial_scale,
                                   sample_num, output)
            print("feature is cuda .....")
When I use the 'cascade_mask_rcnn_r50_fpn_1x.py',the program interrupts and exits at  the roi_align_cuda.forward in the first iteration. 
My systhem:
nvidia driver: 410.78, ubuntu:14.04, cuda:8.0.61.cudnn:5.1.1,pytorch:0.4.1,python:3.6.5

**Comment by OceanPang** [comment]
@YanHengxu Please first check your gcc version, we found gcc 4.8 will cause segmentation fault during the forward process. We also recommend the CUDA version > 9.0.

**Comment by YanHengxu** [comment]
My gcc version is 4.8.5, I find that the config ,'rpn_r50_fpn_1x.py', can be used and the problem is that python can't use 'roi_align_cuda.cpp'

**Comment by YanHengxu** [comment]
Thank you,the 4.9.4 version of gcc can be used correctly

**Comment by hellock** [comment]
#24
