### ISSUE TITLE
Finetuning on small dimension images

### ISSUE THREAD

**Issue by tiberium24** [open-mmlab/mmdetection#2292]
Hello,

I am wondering which parameters would you think is best to change in one of the config files when inputing low res images (due to their small size, 480*360). Definitely the resize option needs to be changed but what else would be needed to improve accuracy?

Thank you

**Comment by ZwwWayne** [comment]
You may further try multi-scale training to improve accuracy. A template is [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py#L230).

**Comment by tiberium24** [comment]
Thanks. I observe however that you have this: 

```
dict(
        type='Resize',
        img_scale=[(1600, 400), (1600, 1400)],
        multiscale_mode='range',
        keep_ratio=True)
```
Why is (1600,400) there two times?

Also, later you have: 

```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False
```

Why is it in testing (1333,800)?

**Comment by ZwwWayne** [comment]
This is to make sure the images have the same size in testing to avoid randomness.
For the COCO dataset, a common practice is to make it has a size (1333, 800). You can set a value suitable for your own dataset.

**Comment by tiberium24** [comment]
Thanks for your reply.
1. My mistake, I missed the second element.
2. I had the impression that the size to which you train needs to be the same when testing.

**Comment by ZwwWayne** [comment]
The multi-scale setting works for both only detection or instance segmentation.
