### ISSUE TITLE
Is there anyone who has tested mmdetection with CUDA 10.2 ??

### ISSUE THREAD

**Issue by StringBottle** [open-mmlab/mmdetection#2293]
Is there anyone who has tested mmdetection with CUDA 10.2 ??

I am installing mmdetection in a server currently under development.

I was told by a server manager that I have to install CentOS 7.7 OS which is only compatible with CUDA 10.2. 

As far as I check the CUDA 10.2-related documentation and Pytorch community Q&A, Pytorch can be run with CUDA 10.2. 

Please share with me an experience CUDA 10.2 installation if you have.

**Comment by ZwwWayne** [comment]
Just make sure the Cuda runtime version is compatible with the Pytorch you installed.

**Comment by StringBottle** [comment]
> Just make sure the Cuda runtime version is compatible with the Pytorch you installed.

Thanks for your reply!
