### ISSUE TITLE
Documentation error in GETTING_STARTED.md

### ISSUE THREAD

**Issue by Msirte** [open-mmlab/mmdetection#2295]
In example 4: 

> Test Mask R-CNN on COCO test-dev with 8 GPUs, and generate the json file to be submit to the official evaluation server.
./tools/dist_test.sh configs/mask_rcnn_r50_fpn_1x.py \
    checkpoints/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth \
    8 --format-only --options "jsonfile_prefix=./mask_rcnn_test-dev_results"

where `--format-only` should be `--format_only`

**Comment by ZwwWayne** [comment]
Thanks for your bug report. Would you like to create a PR to fix it?

**Comment by Msirte** [comment]
#2300
