### ISSUE TITLE
Bug of the mmdet.models.losses.mse_loss.mse_loss function

### ISSUE THREAD

**Issue by penghaozhou** [open-mmlab/mmdetection#2297]
**Describe the bug**
The function F.mse_loss set reduction='mean' by default. Therefore, MSELoss Class executes mean operation no matter what is passed to 'reduction'.

**Bug fix**
@weighted_loss
def mse_loss(pred, target):
    return F.mse_loss(pred, target, reduction="none")

**Comment by hellock** [comment]
Thanks for reporting the bug! Would you like to create a PR to fix it?

**Comment by penghaozhou** [comment]
of course, i will submit a PR in few days. By the way, can i ask how to test on original size image?

**Comment by hellock** [comment]
Fixed in #2301
