### ISSUE TITLE
pytorch2onnx failes

### ISSUE THREAD

**Issue by sam-cts** [open-mmlab/mmdetection#2299]
**Describe the bug**
Tried to convert pytorch to onnx, but failed on onnx.check.check_model after conversion.

**Reproduction**
I have trained a model with mask r cnn config.
Then tried to convert it to onnx model with pytorch2onnx.py

Here is the error I got
```
checking onnx model
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 126, in <module>
    main()
  File "tools/pytorch2onnx.py", line 120, in main
    onnx.checker.check_model(onnx_model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "1107" op_type: "Constant" attribute { name: "value" s: "cpu" type: STRING }
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
opset_version=11 option is added in torch.onnx.export() 
`
    # Export the model to ONNX
    with torch.no_grad():
        with io.BytesIO() as f:
            torch.onnx.export(
                model,
                inputs,
                f,
                operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
                verbose=True,  # NOTE: uncomment this for debugging
                # export_params=True,
                opset_version=11
            )
            onnx_model = onnx.load_from_string(f.getvalue())
`
As some of the operations in mask r cnn config only supported in opset 11 in pytorch, that's why I added it.

Also I have added another check right after model build and before saving the onnx model

`
    onnx.helper.printable_graph(onnx_model.graph)
    print('checking onnx model')
    onnx.checker.check_model(onnx_model)
    print('saving model in {}'.format(args.out))
    onnx.save(onnx_model, args.out)
`

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

sys.platform: linux
Python: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce GTX 970
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 0.4.0
MMDetection: 1.1.0+623029c
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.1

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by xvjiarui** [comment]
It may due to the version of protobuf when onnx is installed. Please refer to https://github.com/onnx/onnx/issues/932

**Comment by sam-cts** [comment]
> 
> 
> It may due to the version of protobuf when onnx is installed. Please refer to [onnx/onnx#932](https://github.com/onnx/onnx/issues/932)

I have tried to pip install different version of profobuf, and sadly that did not solve the issue

**Comment by lwyl98** [comment]
I have the same issue when converting cascade_rcnn to onnx model with pytorch2onnx.py.  Build onnx from source also not work for me.

**Comment by goodlixu** [comment]
I met the same problem when convert cascade_rcnn to onnx format. Change protobuf version did not solve this problem.

**Comment by ashnair1** [comment]
I'm facing the same issue as well while exporting Faster RCNN. I'm using `protobuf == 3.9.2`. If it is a protobuf issue as @xvjiarui says, it would be helpful if everyone could state what protobuf version they used so that we can narrow it down. 

My environment:
```
sys.platform: linux
Python: 3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.168
GPU 0: GeForce RTX 2070 with Max-Q Design
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 0.4.2
MMDetection: 1.1.0+749265c
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1
```

**Comment by ashnair1** [comment]
Regarding the specific error that @sam-cts mentioned, this is caused by a Constant node containing the location of the tensor. Refer image below
![1092_cpu](https://user-images.githubusercontent.com/32295036/78639047-5990c280-78be-11ea-84aa-b958d4c69094.png)

In my faster-rcnn model, there were two instances of these nodes. Removing them allowed the `onnx.checker.check_model(onnx_model)` to pass.

**Comment by marload** [comment]
@ashnair1 
How do I delete Constanta?

**Comment by ashnair1** [comment]
To delete Constant, you need to remove two nodes. One is the Constant node itself and the other is the node to which Constant is an input. You need to replace that node as well.

For example,

```
>> onnx_model = onnx.load("model.onnx")
>> node = onnx_model.graph.node

>> node[437]

output: "1092"
op_type: "Constant"
attribute {
  name: "value"
  s: "cpu"
  type: STRING
}

>> node[439]

input: "1081"
input: "1088"
input: "1089"
input: "1090"
input: "1091"
input: "1092"
input: "1093"
output: "1094"
op_type: "ATen"
attribute {
  name: "operator"
  s: "new_full"
  type: STRING
}
domain: "org.pytorch.aten"

# Make new node without 1092 input 
>> kwargs = {"operator": "new_full"}
>> new_node = onnx.helper.make_node(
     op_type="ATen",
     inputs=["1081", "1088", "1089", "1090", "1091", "1093", "1094"],
     outputs=['1097'],
     domain="org.pytorch.aten",
     **kwargs)

>> onnx_model.graph.node.remove(node[439])
>> onnx_model.graph.node.insert(439, new_node)
>> onnx_model.graph.node.remove(node[437])
```

**Comment by lddsjy** [comment]
> Regarding the specific error that @sam-cts mentioned, this is caused by a Constant node containing the location of the tensor. Refer image below
> ![1092_cpu](https://user-images.githubusercontent.com/32295036/78639047-5990c280-78be-11ea-84aa-b958d4c69094.png)
> 
> In my faster-rcnn model, there were two instances of these nodes. Removing them allowed the `onnx.checker.check_model(onnx_model)` to pass.
> 
> Edit: Although the onnx model gets created there are some issues while loading the model:
> 
> 1. If you're using `onnxruntime`, you might hit `Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: ATen is not a registered function/op`
> 2. If you're using caffe2 backend, it will fail since it's been setup with opset 9 while you're using opset 11.

Meet the same problem when using onnxruntime

**Comment by Single430** [comment]
> Regarding the specific error that @sam-cts mentioned, this is caused by a Constant node containing the location of the tensor. Refer image below
> ![1092_cpu](https://user-images.githubusercontent.com/32295036/78639047-5990c280-78be-11ea-84aa-b958d4c69094.png)
> 
> In my faster-rcnn model, there were two instances of these nodes. Removing them allowed the `onnx.checker.check_model(onnx_model)` to pass.
> 
> Edit: Although the onnx model gets created there are some issues while loading the model:
> 
> 1. If you're using `onnxruntime`, you might hit `Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: ATen is not a registered function/op`
> 2. If you're using caffe2 backend, it will fail since it's been setup with opset 9 while you're using opset 11.

I also encountered the problem 1 after deleting the node. Do you have any solutions now? Looking forward to your reply

**Comment by ashnair1** [comment]
I ended up using this [fork](https://github.com/opencv/mmdetection) of mmdetection. It supports conversion to onnx and openvino formats.

**Comment by Single430** [comment]
> @Single430 I ended up using this [fork](https://github.com/opencv/mmdetection) of mmdetection. It supports conversion to onnx and openvino formats.

Yes, I tested it and it works, thank you very much
