### ISSUE TITLE
Negative samples not participate in training for Focal Loss?

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#2302]
I notice focal loss in RetinaNet is using sigmoid, does that mean negative samples(backgrounds) are not involved in training classifier?
Also can I trust py_sigmoid_focal_loss? Does it cause problem or it is simply slower.
Thanks.

**Comment by ZwwWayne** [comment]
Hi @thisisi3 ，
1. It does not use backgrounds, but backgrounds are involved in training by setting the GT score of 80 classes are 0.
2. It should be simply slower.

**Comment by thisisi3** [comment]
I see, thanks.
