### ISSUE TITLE
How AnchorHead calculates loss?

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#2305]
I notice when anchor head calculates loss, it has the following steps:
1, Cat all levels of features in each image
2, Find targets in each image
3, Map back targets to levels
4, Calculate loss on each level
5, Sum losses of all levels
It seems 3, 4 steps are redundent if we eventually sum losses of all levels. I notice it uses the same avg_factor for all levels. 
Thanks.

**Comment by hellock** [comment]
Literally it is redundant. This is because it provides an interface for showing the losses of each level, which is helpful for our early development. For now it is useless.

**Comment by thisisi3** [comment]
I see, thank you for clearing that up.
