### ISSUE TITLE
how to divide things that belong to same class?

### ISSUE THREAD

**Issue by yaodonggggggg** [open-mmlab/mmdetection#2306]
I have get the output image,it looks well.But how to divide things that in same class?
Like this [https://github.com/dbolya/yolact/blob/master/data/yolact_example_2.png](url)
Another question,how to show the class that just i want?
I change
`show_result(img, result, model.CLASSES,show=False, out_file='output_dir/result1.jpg')`
to
`show_result(img, result, ['person'],show=False, out_file='output_dir/result1.jpg')`
but got 

> IndexError: list index out of range.

**Comment by hellock** [comment]
You can parse the prediction of the model by yourself other than use the `show_result()` method to visualize the results. It is originally a list of bounding boxes corresponding to different classes.
