### ISSUE TITLE
MultiScaleFlipAug test seems wrong, TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by heqinglin336** [open-mmlab/mmdetection#2308]
File "tools/test.py", line 162, in <module>
    main()
  File "tools/test.py", line 140, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "/content/mmdetection/mmdet/apis/test.py", line 19, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/content/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/content/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/content/mmdetection/mmdet/models/detectors/base.py", line 149, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/content/mmdetection/mmdet/models/detectors/base.py", line 134, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "/content/mmdetection/mmdet/models/detectors/two_stage.py", line 327, in aug_test
    self.extract_feats(imgs), img_metas, self.test_cfg.rpn)
  File "/content/mmdetection/mmdet/models/detectors/test_mixins.py", line 41, in aug_test_rpn
    proposal_list = self.simple_test_rpn(x, img_metas, rpn_test_cfg)
  File "/content/mmdetection/mmdet/models/detectors/test_mixins.py", line 34, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/content/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/content/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 274, in get_bboxes
    img_shape = img_metas[img_id]['img_shape']
TypeError: list indices must be integers or slices, not str

ps: Single test is right, but it's wrong when use Mutli-Test , I guess this bug that is due to update before 5 hours

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by heqinglin336** [comment]
> Please follow the `Error report` issue template.

I have tested  original code(configs: cascade_rcnn_r50_fpn_1x.py), MultiScaleFlipAug test didn't work, for example, 
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(1333, 800), (2666, 1600)],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
],
before upgrade this code, it worked ver well.

**Comment by heqinglin336** [comment]
thank you very much, this code( yhcao6) works well.

**Comment by Peterchen111** [comment]
i have this problem too ,can you tell me how to solve it

**Comment by Wenbin94** [comment]
how to solve the problem

**Comment by Wenbin94** [comment]
> thank you very much, this code( yhcao6) works well.
how to solve the problem.

**Comment by Wenbin94** [comment]
> thank you very much, this code( yhcao6) works well.


how to solve the problem

**Comment by jvnext1** [comment]
> i have this problem too ,can you tell me how to solve it

Did you solve the problem?I met the same

**Comment by Wenbin94** [comment]
> > i have this problem too ,can you tell me how to solve it
> 
> Did you solve the problem?I met the same

copy mmdet code( yhcao6) to your project.

**Comment by jvnext1** [comment]
> > > i have this problem too ,can you tell me how to solve it
> > 
> > 
> > Did you solve the problem?I met the same
> 
> copy mmdet code( yhcao6) to your project.

老哥，code(yhcao6)是指https://github.com/yhcao6/mmdetection这个库的代码吗？我复制了一下这个库里的mmdet，还是遇到了同样的问题😔

**Comment by NaCl-Ocean** [comment]
I copy the code，but it did not work，any advice?

**Comment by Wenbin94** [comment]
> > > > i have this problem too ,can you tell me how to solve it
> > > 
> > > 
> > > Did you solve the problem?I met the same
> > 
> > 
> > copy mmdet code( yhcao6) to your project.
> 
> 老哥，code(yhcao6)是指[https://github.com/yhcao6/mmdetection这个库的代码吗？我复制了一下这个库里的mmdet，还是遇到了同样的问题😔](https://github.com/yhcao6/mmdetection%E8%BF%99%E4%B8%AA%E5%BA%93%E7%9A%84%E4%BB%A3%E7%A0%81%E5%90%97%EF%BC%9F%E6%88%91%E5%A4%8D%E5%88%B6%E4%BA%86%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA%E5%BA%93%E9%87%8C%E7%9A%84mmdet%EF%BC%8C%E8%BF%98%E6%98%AF%E9%81%87%E5%88%B0%E4%BA%86%E5%90%8C%E6%A0%B7%E7%9A%84%E9%97%AE%E9%A2%98%F0%9F%98%94)
> Does code (yhcao6) mean the link https://github.com/yhcao6/mmdetection ? I copied the mmdet from this repository, and I still met the same problem.

do u run pip install -v -e .or "python setup.py develop"after copy？

**Comment by Wenbin94** [comment]
> I copy the code，but it did not work，any advice?

do u run pip install -v -e .or "python setup.py develop"after copy？

**Comment by NaCl-Ocean** [comment]
yes, i rebuild the project, but still doesn't work

**Comment by NaCl-Ocean** [comment]
> > I copy the code，but it did not work，any advice?
> 
> do u run pip install -v -e .or "python setup.py develop"after copy？

yes, i rebuild the project, but still doesn't work

**Comment by NaCl-Ocean** [comment]
But I used an earlier version and solved the problem

> > > I copy the code，but it did not work，any advice?
> > 
> > 
> > do u run pip install -v -e .or "python setup.py develop"after copy？
> 
> yes, i rebuild the project, but still doesn't work

But I use an earlier version and solved the problem

**Comment by jvnext** [comment]
> > > I copy the code，but it did not work，any advice?
> > 
> > 
> > do u run pip install -v -e .or "python setup.py develop"after copy？
> 
> yes, i rebuild the project, but still doesn't work

I read the code about Mutli-Test. Then I Modified some code and it works. Here's what I've modified.
The code in mmdet/models/detectors/cascade_rcnn.py 
Line 420-424
```python
for x, img_meta in zip(self.extract_feats(imgs), img_metas):
    img_shape = img_meta[0]['img_shape']  
    scale_factor = img_meta[0]['scale_factor']        
    flip = img_meta[0]['flip']
```
Line 480-483
```python
for x, img_meta in zip(self.extract_feats(imgs), img_metas):
    img_shape = img_meta[0]['img_shape']
    scale_factor = img_meta[0]['scale_factor']
    flip = img_meta[0]['flip']
```
The code in mmdet/models/detectors/test_mixins.py
Line 40-41
```python
 for x, img_meta in zip(feats, img_metas):
     proposal_list = self.simple_test_rpn(x, img_meta, rpn_test_cfg)
```
Line 125-128
```python
for x, img_meta in zip(feats, img_metas):
    img_shape = img_meta[0]['img_shape']
    scale_factor = img_meta[0]['scale_factor']
    flip = img_meta[0]['flip']
```
Line 239-242
```python
for x, img_meta in zip(feats, img_metas):
    img_shape = img_meta[0]['img_shape']
    scale_factor = img_meta[0]['scale_factor']
    flip = img_meta[0]['flip']
```

It just change the 'metas' to 'meta' in some forloops. Maybe I change some others similar code, but I can't remember exactly. You can try it.

**Comment by MeUH503** [comment]
Additionally,

The code in mmdet/models/detectors/cascade_rcnn.py
Line 444-447

> ```python
> if i < self.num_stages - 1:
>     bbox_label = cls_score.argmax(dim=1)
>     rois = bbox_head.regress_by_class(rois, bbox_label,
>                              bbox_pred, img_meta[0])
> ```
