### ISSUE TITLE
Questions on method py_sigmoid_focal_loss.

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#2309]
Here is the code I am confused about:
`focal_weight = (alpha * target + (1 - alpha) *
                    (1 - target)) * pt.pow(gamma)`

I think alpha is always the same on both target and non-target places. Is there a reason doing this or this piece of code is simply for debugging and is not used anywhere.

**Comment by hellock** [comment]
This is the standard definition in the Focal Loss paper, you may refer to it.

**Comment by thisisi3** [comment]
Yes you are right, thanks.
