### ISSUE TITLE
How to add images to tensorboard during training?

### ISSUE THREAD

**Issue by wangg12** [open-mmlab/mmdetection#231]

**Comment by OceanPang** [comment]
@wangg12 mmdetection use hooks to control those modules. If you want to show images on tensorboard, you should first add the images into Runner object (See in mmcv), and upload them to tensorboard using [tensorboard hooks](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/tensorboard.py)

**Comment by wangg12** [comment]
@OceanPang Thank you. It works.

**Comment by LUCKMOONLIGHT** [comment]
> @OceanPang Thank you. It works.
How did you do it, can you share with me?

**Comment by UpCoder** [comment]
@LUCKMOONLIGHT I find a way
1. You need to rewrite the Tensorboard Hook, such as TensorboardImageHook
2. You need to pass the image object in batch_processor func in train.py to the outputs
3. You can write the image object to tensorboard in your TensorboardImageHook

**Comment by cxiang26** [comment]
> @LUCKMOONLIGHT I find a way
> 
> 1. You need to rewrite the Tensorboard Hook, such as TensorboardImageHook
> 2. You need to pass the image object in batch_processor func in train.py to the outputs
> 3. You can write the image object to tensorboard in your TensorboardImageHook

It is difficult to understand the second item, could you provide a simple example? Thanks very much.

**Comment by UpCoder** [comment]
@cxiang26 you can add the tensor you want to show into the output(dict) in the train_step func, https://github.com/open-mmlab/mmdetection/blob/405c37766398608f81b8cae657914c0f15830286/mmdet/models/detectors/base.py#L250

then, in your hook, you can get the tensor mentioned above by this way
```python
log_images = runner.outputs.get('log_images')
```
then, you can add the image to tf log
```python
self.writer.add_image(
                    'image/original_image', np.asarray(image, np.uint8), runner.iter
                )
```

**Comment by cxiang26** [comment]
I got it, thanks!

**Comment by cxiang26** [comment]
@UpCoder I got it, thanks!

**Comment by deepakksingh** [comment]
Is there a way to utilize the Tensorboard Hook to pass custom values?
Any suggestions would be helpful

**Comment by parthnatekar** [comment]
> @cxiang26 you can add the tensor you want to show into the output(dict) in the train_step func,
> 
> https://github.com/open-mmlab/mmdetection/blob/405c37766398608f81b8cae657914c0f15830286/mmdet/models/detectors/base.py#L250
> 
> then, in your hook, you can get the tensor mentioned above by this way
> 
> ```python
> log_images = runner.outputs.get('log_images')
> ```
> 
> then, you can add the image to tf log
> 
> ```python
> self.writer.add_image(
>                     'image/original_image', np.asarray(image, np.uint8), runner.iter
>                 )
> ```

Hi, can @UpCoder, where exactly do I get the output tensor of the model so that I can add it to the output(dict)?

In other words, where are the model outputs at each epoch?
