### ISSUE TITLE
how to create a new component?

### ISSUE THREAD

**Issue by NicholasIrving** [open-mmlab/mmdetection#2314]
In MMDetection, model components are basically categorized as 4 types. Backbone, neck, head and roi extractor. If I want to add a new component, what should I do ?

**Comment by ZwwWayne** [comment]
Create a new python file to implement the new component and put them in their corresponding directories.

**Comment by NicholasIrving** [comment]
I have create a new one according to the document, but the error #2377  occurred when i run dist_train.

**Comment by ZwwWayne** [comment]
You can try to set `find_unused_parameters=True` first in your config and see whether the bug still exists.
