### ISSUE TITLE
Pretrained models download.

### ISSUE THREAD

**Issue by lovepan1** [open-mmlab/mmdetection#2317]

**Comment by lovepan1** [comment]
When i use https://open-mmlab.oss-cn-beijing.aliyuncs.com url, 
I got the following error
![捕获](https://user-images.githubusercontent.com/39023964/77499181-5a703000-6e8c-11ea-8ba3-644362dfc30d.JPG)

**Comment by PanJianning** [comment]
What pretraineds model do you want to download? As far as I know, you can get the download url for backbone pretrained on imagenet from [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py#L17) and url for detection model pretrained on coco from [model zoo](https://github.com/open-mmlab/mmdetection/blob/master/docs/MODEL_ZOO.md)

**Comment by lovepan1** [comment]
Thank you for your reply, I want to download  detection model pretrained on coco, but when i use  https://open-mmlab.oss-cn-beijing.aliyuncs.com url to replace https://s3.ap-northeast-2.amazonaws.com/open-mmla url,   just like https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/rpn_r50_caffe_c4_1x-ea7d3428.pth  became  https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection/models/rpn_r50_caffe_c4_1x-ea7d3428.pth
i always meet this error, is there something wrong with my method?
![捕获](https://user-images.githubusercontent.com/39023964/77655504-73bccd80-6fad-11ea-8722-dea9918d9521.JPG)

**Comment by PanJianning** [comment]
My bad. I never notice that we can replace the host url for model downloading. Take a look at [this](https://www.alibabacloud.com/help/zh/doc-detail/31945.html).Their aliyun oss service may have run out of money。

**Comment by lovepan1** [comment]
oh....no, I don't know how to download the model without aliyun,   are you sure it's the official problem and not my method??

**Comment by hellock** [comment]
Thanks for the notice. We recharged the service and it is avaiable again. (It is expensive...)

**Comment by lovepan1** [comment]
Thank you very much, thank you for your support, but ....., i also met this problem, what should i do?
![捕获](https://user-images.githubusercontent.com/39023964/77731098-399b0c80-703d-11ea-897d-dbf6ed574a37.JPG)

**Comment by lovepan1** [comment]
I'm afraid you can't see the pic, the content is as follows:
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>5E7DA6E2F43DB73434569CA7</RequestId>
<HostId>open-mmlab.oss-cn-beijing.aliyuncs.com</HostId>
<Key>
mmdetection/models/rpn_r50_caffe_c4_1x-ea7d3428.pth
</Key>
</Error>

**Comment by mkapry** [comment]
Hi! I guess, I have the same problem with downloading from [open-mmlab://msra/hrnetv2_w32 ](url), would be grateful for any advice/solution
