### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by Chenney0813** [open-mmlab/mmdetection#232]
I have five ann_files and there are  total 83992 images, but When I start training the model, there are only 10628 images showed in the log,   I print the length of the dsets.flag  in the utils.py and it shows 83992 well,I want to know if there are something wrong？
Here is my train dataset in config:
 
 train=dict(
        type=dataset_type,
        ann_file=[
                data_root + 'annotations/airplane_train2014.json',
                data_root + 'annotations/instances_train2018.json',
                data_root + 'annotations/occluded_cococate.json',
                data_root + 'annotations/pascal_train2012_cococate.json',
                data_root + 'annotations/test2.json'
            ],
        img_prefix=[data_root + 'train/airplane_train2014/', 
       		    data_root + 'train/train2018/',
                    data_root + 'train/occluded_cococate/',
                    data_root + 'train/pascal_train2012_cococate/',
                    data_root + 'train/test2Images/'],
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=False,
        with_crowd=True,
        with_label=True),

and here is the log:

`2019-01-05 15:54:55,969 - INFO - Epoch [1][50/10628]	lr: 0.00399, eta: 2 days, 18:31:53, time: 1.127, data_time: 0.123, loss_rpn_cls: 0.1124, loss_rpn_reg: 0.0105, s0.loss_cls: 0.3051, s0.acc: 96.2441, s0.loss_reg: 0.0413, s1.loss_cls: 0.1280, s1.acc: 96.9551, s1.loss_reg: 0.0105, s2.loss_cls: 0.0676, s2.acc: 95.6172, s2.loss_reg: 0.0011, loss: 0.6765`

**Comment by OceanPang** [comment]
@Chenney0813 the '10628' means the iterations needed by 1 epoch. I guess you are using 8 GPUs?

**Comment by Chenney0813** [comment]
but I only have 4 gpus and here is my train script
`./tools/dist_train.sh configs/cascade_rcnn_r101_fpn_1x.py 4 --validate`

**Comment by Chenney0813** [comment]
> @Chenney0813 the '10628' means the iterations needed by 1 epoch. I guess you are using 8 GPUs?
but I only have 4 gpus and here is my train script
./tools/dist_train.sh configs/cascade_rcnn_r101_fpn_1x.py 4 --validate

**Comment by OceanPang** [comment]
@Chenney0813 per GPU contains 2 images? Thus the batch size = 8

**Comment by Chenney0813** [comment]
> @Chenney0813 per GPU contains 2 images? Thus the batch size = 8

thank you

**Comment by OceanPang** [comment]
@Chenney0813 please read the config file
