### ISSUE TITLE
Error is reported when inputting training command

### ISSUE THREAD

**Issue by rouyalxy** [open-mmlab/mmdetection#2321]
python tools/train.py configs/faster_rcnn_r50_fpn_1x.py 
usage: train.py [-h] [--config CONFIG] [--work_dir WORK_DIR]
                [--resume_from RESUME_FROM] [--validate] [--gpus GPUS]
                [--seed SEED] [--deterministic]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK] [--autoscale-lr]
train.py: error: unrecognized arguments: configs/faster_rcnn_r50_fpn_1x.py

**Comment by hellock** [comment]
Please use the `Error report` issue template.
