### ISSUE TITLE
How to get feature map from the middle layer?

### ISSUE THREAD

**Issue by Zachzhang97** [open-mmlab/mmdetection#2326]
Thanks in advance for this excellent project. 
I'm new to mmdetection. I don’t know how to get feature map from the middle layer. 
eg： In faster rcnn，**i need the output of the bbox_roi_extractor**（the input of bbox_head）
I already know how to get the output of the entire model like：
`result = inference_detector(model, img_name)`
But I don't know how to easily get the middle layer features.
Another question is, how to delete the bbox_head of the trained model, and it can still infer the feature map normally?
I really need your help, thank you

**Comment by PanJianning** [comment]
I don't think there is a easy way. You may need to modify the test function of the detector to return the middle feature map.

**Comment by Kaeseknacker** [comment]
You can modify `inference.py` and `two_stage.py` if you want feature maps for FRCNN for example:

in `tow_stage.py` modify `def simple_test(...)`:
```
if not self.with_mask:
    return bbox_results, x
```

in `inference.py` modify `def inference_detector(model, img):`
```
    result, x = model(return_loss=False, rescale=True, **data)
```

`x` contains the feature maps of the FPN.

**Comment by Zachzhang97** [comment]
> You can modify `inference.py` and `two_stage.py` if you want feature maps for FRCNN for example:
> 
> in `tow_stage.py` modify `def simple_test(...)`:
> 
> ```
> if not self.with_mask:
>     return bbox_results, x
> ```
> 
> in `inference.py` modify `def inference_detector(model, img):`
> 
> ```
>     result, x = model(return_loss=False, rescale=True, **data)
> ```
> 
> `x` contains the feature maps of the FPN.

Thanks a lot ! You're right.  I noticed that there are several files under '/ mmdet / models / detectors /' path that I can modify to get the forward propagation process I want.

**Comment by songruoning** [comment]
@Kaeseknacker Thanks a lot! It's a great solution!

**Comment by Liruonn** [comment]
@Zachzhang97 Have you ever achieve what you want?Now,I want to do the same thing as you.Could you please share me what you have modified with inference.py ?Thank you a lot!

**Comment by PushpakBhoge** [comment]
you can use pytorch `register_forward_hook` method check this tutorial https://kozodoi.me/python/deep%20learning/pytorch/tutorial/2021/05/27/extracting-features.html
then you can attach that hook to a layer from mmdet and it will give you the features
