### ISSUE TITLE
New Transforms

### ISSUE THREAD

**Issue by melikovk** [open-mmlab/mmdetection#2328]
**Describe the feature**

I suggest adding following data transforms to the project.

_Rescale_ and _RandomRescale_ - transforms to resample image similar to _RandomScale_ from albumentation project
_RandomGamma_ - similar to _RandomGamma_ from albumentation project
_RandomBlur_ - to randomly blur or sharpen image using _unsharp mask_ method
_RandomChannelPermutation_ - similar to _ChannelShuffle_ from albumentation
_AutoContrast_ - simple intensity normalization transform that performs normalization using properties of each image
_ConvertToMultiChannel_ - a convenience transform to turn grayscale (single channel) image to multichannel image for transfer learning
 
**Motivation**
Although Albu transform provides a good interface to albumentation project, it is somewhat inconvenient that while some transforms are present in the project, others have to be used from another project.
Proposed transform use interface more consistent with other transforms in mmdetection project (i.e. always applied, list of options rather than ranges)
Unlike albumentation _RandomGamma_, _RandomBlur_ and _RandomChannelPermutation_ can be applied to a subset of channels and are designed for images with arbitrary number of channels

**Additional context**
I already have written and used these transforms and will be glad to create pull request so you can get a better idea and decided if you feel that any of them belong to the project. The main drawback is that since some transform operate on a subset of channels they have to directly utilize opencv, rather than use mmcv.

**Comment by PanJianning** [comment]
LOL, I think Albu is quite convenient.

**Comment by PanJianning** [comment]
LOL, But I think Albu is quite convenient.

**Comment by whuhangzhang** [comment]
I quite agree with your idea that the albumentations library will bring many problems, which are not well maintained in mmdet. May I ask if your submission is this: https://github.com/melikovk/mmdetection/commit/47ebdb2291a6f6f7bee27c06fb5477baa2137bbe . Are these transformations tested and able to transform image, mask, and coco_stuff at the same time

**Comment by melikovk** [comment]
Yes, this is submission. I have tested and used them all on the images I work with - those are multi-channel 16 bit images, which are converted into float32 during loading. Only Rescale and RandomRescale  are geometric transforms and I tested that they properly handle bounding boxes. The code for mask transform is taken from mmdet Resize transform but I did not test it. Other transform affect only pixel values and just pass through other fields.

**Comment by whuhangzhang** [comment]
@melikovk Thank you for your great work and look forward to your PR. In the hope of adding sufficient test samples for coordinate transformations, geometric transformations often introduce subtle errors

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/pull/2427

**Comment by rezat96** [comment]
seems like the class RandomRescale(Rescale) is omitted in the latest version(v3.1). Any reason why? is there any recommendation instead? @melikovk @hellock @ZwwWayne
I am actually looking to make a class which is relatively smaller than the other more scale, what is the right approach?
Thanks for your help.
