### ISSUE TITLE
The problem of parameter updates.

### ISSUE THREAD

**Issue by fanglinpu** [open-mmlab/mmdetection#233]
I don't add the rpn_losses to the total losses, but the parameter of rpn_bbox still updated. What is the reason about this problem?

**Comment by OceanPang** [comment]
@fanglinpu Is the changes minor? If so I guess it may owing to the weight decay.

**Comment by fanglinpu** [comment]
@OceanPang Thank you for your reply. It exactly be owing to the weight decay since the values of the parameters are always decreased.
