### ISSUE TITLE
How to freeze model？

### ISSUE THREAD

**Issue by wytcsuch** [open-mmlab/mmdetection#2337]
Hello, I want to freeze the model so that it can still run out of the mmdetection framework. Which file should I run，publish_model.py or pytorch2onnx.py？

**Comment by ZwwWayne** [comment]
Hi @wytcsuch ,
publish_model.py or pytorch2onnx.py only export model weights with a different format or name. You need to set the model to eval mode if you want to freeze the model, i.e. do not train the weights in the model.
