### ISSUE TITLE
which backbone can perform better for video object detection?

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection#2338]
I hava trained the faster_rcnn_r50_fpn_1x_voc0712 on my custom video dataset (I process it to pics frame by frame), may I ask which backbone can perform better for video object detection? Very appreciate for your reply

**Comment by ZwwWayne** [comment]
Usually, the greater backbone could yield better results, e.g., ResNext101_x64x4d.

**Comment by yustaub** [comment]
thk, I will try it @ZwwWayne

**Comment by ShidiDaisy** [comment]
> ResNext101_x64x4d

Does it mean ResNext101_x64x4d can have a higher inference time than faster_rcnn_r50_fpn_1x_voc0712 when processing video frames?

**Comment by yustaub** [comment]
surely @ShidiDaisy
