### ISSUE TITLE
Question about test augmentation: MultiScaleFlipAug

### ISSUE THREAD

**Issue by Zachzhang97** [open-mmlab/mmdetection#2339]
In faster rcnn , I noticed that the model uses the test augmentation :  MultiScaleFlipAug.
`test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]`
So I came up with a somewhat stupid question: whether the boxes predicted by the  model with test augmentation match the original image. When I'm in an image contest, can I submit the results predicted by the model with test augmentation? I worry that the predicted box is not from the original image, but the preprocessed image. Or whether the box results are automatically convert to a format consistent with the original image?
Thanks to your help !

**Comment by ZwwWayne** [comment]
The box is scaled to the original image size, thus the users can use the script to produce results that can be directly used for test submission, as indicated in test example 4 in the [doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md).

**Comment by Zachzhang97** [comment]
> The box is scaled to the original image size, thus the users can use the script to produce results that can be directly used for test submission, as indicated in test example 4 in the [doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md).

Thanks ! This solved my question.
