### ISSUE TITLE
'RuntimeError: CUDA error: misaligned address' and 'RuntimeError: CUDA error: device-side assert triggered'

### ISSUE THREAD

**Issue by GaryZhu1996** [open-mmlab/mmdetection#2342]
**Describe the bug**
This two error messages are shown when I run 'tools/dist_train.py': 'RuntimeError: CUDA error: misaligned address.' and 'RuntimeError: CUDA error: device-side assert triggered'
But these errors does not happened every time. Sometimes I can train the model without any issues. I think that the two errors are related to each other.

**Environment**
sys.platform: linux
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-9.0
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GPU 0,1,2,3: GeForce GTX 1080 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 0.2.16
MMDetection: 1.0.0+923b70a
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 9.0

**Error traceback for error1**
Traceback (most recent call last):
  File "./tools/train.py", line 124, in <module>
    main()
  File "./tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/disk1/zzw/works/mmdetection/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/disk1/zzw/works/mmdetection/mmdet/apis/train.py", line 230, in _dist_train
    model = MMDistributedDataParallel(model.cuda())
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 24, in __init__
    self._sync_params()
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 38, in _sync_params
    self.broadcast_bucket_size)
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 28, in _dist_broadcast_coalesced
    flat_tensors = _flatten_dense_tensors(tensors)
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 228, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
RuntimeError: CUDA error: misaligned address
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: misaligned address (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:764)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7effc6974193 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x17f66 (0x7effc6bb1f66 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x19cbd (0x7effc6bb3cbd in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x4d (0x7effc696463d in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x67bac2 (0x7f00119e3ac2 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x67bb66 (0x7f00119e3b66 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x1a184f (0x5611e62db84f in /disk1/zzw/anaconda3/bin/python)
frame #7: <unknown function> + 0xfd1a8 (0x5611e62371a8 in /disk1/zzw/anaconda3/bin/python)
frame #8: <unknown function> + 0x10e3c7 (0x5611e62483c7 in /disk1/zzw/anaconda3/bin/python)
frame #9: <unknown function> + 0x10e3dd (0x5611e62483dd in /disk1/zzw/anaconda3/bin/python)
frame #10: <unknown function> + 0x10e3dd (0x5611e62483dd in /disk1/zzw/anaconda3/bin/python)
frame #11: <unknown function> + 0x10e3dd (0x5611e62483dd in /disk1/zzw/anaconda3/bin/python)
frame #12: <unknown function> + 0x10e3dd (0x5611e62483dd in /disk1/zzw/anaconda3/bin/python)
frame #13: <unknown function> + 0x10e3dd (0x5611e62483dd in /disk1/zzw/anaconda3/bin/python)
frame #14: <unknown function> + 0x10e3dd (0x5611e62483dd in /disk1/zzw/anaconda3/bin/python)
frame #15: PyDict_SetItem + 0x502 (0x5611e629ced2 in /disk1/zzw/anaconda3/bin/python)
frame #16: PyDict_SetItemString + 0x4f (0x5611e629d70f in /disk1/zzw/anaconda3/bin/python)
frame #17: PyImport_Cleanup + 0x9e (0x5611e62e19ce in /disk1/zzw/anaconda3/bin/python)
frame #18: Py_FinalizeEx + 0x67 (0x5611e635d087 in /disk1/zzw/anaconda3/bin/python)
frame #19: <unknown function> + 0x235f93 (0x5611e636ff93 in /disk1/zzw/anaconda3/bin/python)
frame #20: _Py_UnixMain + 0x3c (0x5611e63702bc in /disk1/zzw/anaconda3/bin/python)
frame #21: __libc_start_main + 0xf0 (0x7f002a2d9830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #22: <unknown function> + 0x1db062 (0x5611e6315062 in /disk1/zzw/anaconda3/bin/python)

**Error traceback for error2**
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [52,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [53,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [54,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "./tools/train.py", line 124, in <module>
    main()
  File "./tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/disk1/zzw/works/mmdetection/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/disk1/zzw/works/mmdetection/mmdet/apis/train.py", line 272, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 268, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/disk1/zzw/works/mmdetection/mmdet/apis/train.py", line 100, in batch_processor
    losses = model(**data)
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 54, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk1/zzw/works/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/disk1/zzw/works/mmdetection/mmdet/models/detectors/base.py", line 138, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/disk1/zzw/works/mmdetection/mmdet/models/detectors/two_stage.py", line 176, in forward_train
    *rpn_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/disk1/zzw/works/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 51, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/disk1/zzw/works/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/disk1/zzw/works/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 189, in loss
    sampling=self.sampling)
  File "/disk1/zzw/works/mmdetection/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/disk1/zzw/works/mmdetection/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/disk1/zzw/works/mmdetection/mmdet/core/anchor/anchor_target.py", line 136, in anchor_target_single
    target_means, target_stds)
  File "/disk1/zzw/works/mmdetection/mmdet/core/bbox/transforms.py", line 22, in bbox2delta
    dy = (gy - py) / ph
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:764)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fdc6b3f7193 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x17f66 (0x7fdc6b634f66 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x19cbd (0x7fdc6b636cbd in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x4d (0x7fdc6b3e763d in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x67bac2 (0x7fdcb6466ac2 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x67bb66 (0x7fdcb6466b66 in /disk1/zzw/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x1a184f (0x55b5422ab84f in /disk1/zzw/anaconda3/bin/python)
frame #7: <unknown function> + 0x10db9b (0x55b542217b9b in /disk1/zzw/anaconda3/bin/python)
frame #8: <unknown function> + 0x10dcf7 (0x55b542217cf7 in /disk1/zzw/anaconda3/bin/python)
frame #9: <unknown function> + 0xfd1a8 (0x55b5422071a8 in /disk1/zzw/anaconda3/bin/python)
frame #10: <unknown function> + 0x10e3c7 (0x55b5422183c7 in /disk1/zzw/anaconda3/bin/python)
frame #11: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #12: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #13: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #14: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #15: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #16: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #17: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #18: <unknown function> + 0x10e3dd (0x55b5422183dd in /disk1/zzw/anaconda3/bin/python)
frame #19: PyDict_SetItem + 0x502 (0x55b54226ced2 in /disk1/zzw/anaconda3/bin/python)
frame #20: PyDict_SetItemString + 0x4f (0x55b54226d70f in /disk1/zzw/anaconda3/bin/python)
frame #21: PyImport_Cleanup + 0x9e (0x55b5422b19ce in /disk1/zzw/anaconda3/bin/python)
frame #22: Py_FinalizeEx + 0x67 (0x55b54232d087 in /disk1/zzw/anaconda3/bin/python)
frame #23: <unknown function> + 0x235f93 (0x55b54233ff93 in /disk1/zzw/anaconda3/bin/python)
frame #24: _Py_UnixMain + 0x3c (0x55b5423402bc in /disk1/zzw/anaconda3/bin/python)
frame #25: __libc_start_main + 0xf0 (0x7fdcced5c830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #26: <unknown function> + 0x1db062 (0x55b5422e5062 in /disk1/zzw/anaconda3/bin/python)

Please help me fix the bug ,THANK YOU!

**Comment by ZwwWayne** [comment]
The CUDA runtime is 9.0, but your PyTorch is compiled by CUDA 10.1. Please make sure that the CUDA version is consistent with the CUDA version that the Pytorch requires.

**Comment by GaryZhu1996** [comment]
> The CUDA runtime is 9.0, but your PyTorch is compiled by CUDA 10.1. Please make sure that the CUDA version is consistent with the CUDA version that the Pytorch requires.

I have tried to change pytorch to the version that matches the CUDA environment, but still got the same error message. Should I do some other compilation?

**Comment by ZwwWayne** [comment]
It seems that there is still some bug in your code. You can try `CUDA_LAUNCH_BLOCKING=1`  to locate which line of code that causes this bug

**Comment by JerryQiang** [comment]
how to make sure that your compilation CUDA version and runtime CUDA version match

**Comment by JerryQiang** [comment]
> The CUDA runtime is 9.0, but your PyTorch is compiled by CUDA 10.1. Please make sure that the CUDA version is consistent with the CUDA version that the Pytorch requires.

how to make sure that your compilation CUDA version and runtime CUDA version match?

**Comment by JerryQiang** [comment]
> It seems that there is still some bug in your code. You can try `CUDA_LAUNCH_BLOCKING=1` to locate which line of code that causes this bug

How to make sure that your compilation CUDA version and runtime CUDA version match?
In `Install.md`, it tells me to see https://pytorch.org/, I just see the version of Pytorch

Need I to check the match of CUDA and cuDNN ?

**Comment by ZwwWayne** [comment]
> > It seems that there is still some bug in your code. You can try `CUDA_LAUNCH_BLOCKING=1` to locate which line of code that causes this bug
> 
> How to make sure that your compilation CUDA version and runtime CUDA version match?
> In `Install.md`, it tells me to see https://pytorch.org/, I just see the version of Pytorch
> 
> Need I to check the match of CUDA and cuDNN ?

Yes, you need to check your cuda version and install the correct PyTorch.

**Comment by JingJingBaoBao** [comment]
I met the same problem. Now I settle it. It seems to my NO.0 GPU doesn't work. When I ignore the 0 GPU with command `CUDA_VISIBLE_DEVICES=1,2 ` , the program runs normally.
