### ISSUE TITLE
Incorrect working testing cityscapes

### ISSUE THREAD

**Issue by BloomBabe** [open-mmlab/mmdetection#2343]
I run command python tools/test.py 'configs/cityscapes/mask_rcnn_r50_fpn_cityscapes.py'   'PATH/to/weights.pth'  --format_only --options "txtfile_prefix=/PATH/to/result" to generate folder with testing cityscapes results, but after execution I have only part of the testing image,more precisely, in the folder, the results of the predictions are saved only for the Munich folder

**Comment by xvjiarui** [comment]
Hi @BloomBabe ,
I could not reproduce this error. Could you check it with our released model? 
Note: Since there are too many files, `ls -n ` will be overwhelmed. Try `ls -n txtfile_prefix | grep berlin`.

**Comment by BloomBabe** [comment]
Hi @xvjiarui, thanks for the responsiveness, i'll try it,  but I’m afraid that the problem may be that I work in google collab and store the data set on google drive, I upload the test data there too, I understand that google drive is not your area of responsibility, so thanks for the help I will think further
