### ISSUE TITLE
Locate the images which shap is not consistent with annotation file

### ISSUE THREAD

**Issue by Bai426** [open-mmlab/mmdetection#2350]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Hi, all. I am facing a problem like this: 
    assert shape[i] >= img.shape[i]
AssertionError

Above all is the error report.  I use my own coco-like dataset to train a Mask-R-CNN model. These datasets can be used in Faseter-R-CNN, but in this model training, it raises the shape of some images in image files are not consistent with annotation file. In Question about pad_shape
#482, @hellock explained that it is due to : 
This is most probable that the image shape in annotations is not the same as the actual shape of the loaded image. Some images may be taken by mobile devices and have different orientation. You may have a check.

I checked the code and ran the data impading, sometimes it can read 255 images while my whole images are 267, sometimes only several images can be loaded. There must be one or few images which has the shap problem, but how can I locate and clean them?
**Reproduction**
1. What command or script did you run?
```I follow "mmdetection_train_custom_coco_data_segmentation.ipynb": https://colab.research.google.com/github/Tony607/mmdetection_instance_segmentation_demo/blob/master/mmdetection_train_custom_coco_data_segmentation.ipynb#scrollTo=ZWpo2UKK8WTD

A placeholder for the command.
```I am running model training:
%cd {project_name}
!python /home/bys2058/mmdetection/tools/train.py {config_fname}

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I didn't modify anything except for the config file.
3. What dataset did you use?
Custom COCO
**Environment**

sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: GeForce RTX 2080 SUPER
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.2.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.2
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.4.0a0+6b959ee
OpenCV: 4.2.0
MMCV: 0.4.0
MMDetection: 1.1.0+e03c96d
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.0


**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "/home/bys2058/mmdetection/tools/train.py", line 142, in <module>
    main()
  File "/home/bys2058/mmdetection/tools/train.py", line 138, in main
worker.py, r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL) (120, [196])
self.prepare_train_img(idx): 196
{'id': 5427, 'dataset_id': 13, 'path': '/datasets/300spalling/spalling and exposed reinforcement17.jpg', 'width': 250, 'height': 167, 'file_name': 'spalling and exposed reinforcement17.jpg', 'filename': 'spalling and exposed reinforcement17.jpg'}
    meta=meta)
  File "/home/bys2058/mmdetection/mmdet/apis/train.py", line 111, in train_detector
ann_info, idx =  196
results['img_prefix'] /home/bys2058/mmdetection/data/coco/300crackspalling-1/
    meta=meta)
  File "/home/bys2058/mmdetection/mmdet/apis/train.py", line 235, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 262, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 829, in __next__
    return self._process_data(data)
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 859, in _process_data
    data.reraise()
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 182, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bys2058/mmdetection/mmdet/datasets/custom.py", line 136, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/bys2058/mmdetection/mmdet/datasets/custom.py", line 153, in prepare_train_img
    return self.pipeline(results)
  File "/home/bys2058/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/bys2058/mmdetection/mmdet/datasets/pipelines/transforms.py", line 326, in __call__
    self._pad_masks(results)
  File "/home/bys2058/mmdetection/mmdet/datasets/pipelines/transforms.py", line 311, in _pad_masks
    for mask in results[key]
  File "/home/bys2058/mmdetection/mmdet/datasets/pipelines/transforms.py", line 311, in <listcomp>
    for mask in results[key]
  File "/home/bys2058/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/image/geometry.py", line 200, in impad
    assert shape[i] >= img.shape[i]
AssertionError

A placeholder for trackback.
```I don't understand this, but I think above all is clear.

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
You can just write a script to load your images and annotations, and compare the actual image shape with the shape in annotations.

**Comment by Bai426** [comment]
Hi, all. I solved the problem.
There are two issues for my own dataset:
1) Some images are png instead of jpg or jpeg, so it is necessary to convert them to jpg by revising the json file.
2) There are few bad images which shape is inconsistent with annotation. Although I compared the original images with the annotation file, it cannot find the bad ones.  

I did the following to locate them:
a) First, set shuffle = False (defaulted as True) in builder_loader.py, make sure batch-size = 1.
b) Then, in Runner.py, I added the following lines to track the index of last filed to be processed:
 def train(self, data_loader, **kwargs):
        for i, data_batch in enumerate(data_loader):    #### for data checking   ####
            print("i", i)
The last i is the index of the image which can be processed, but i+1 is the one that cannot be input. Check its name in your whole dataset which was not shuffled, and then clean it.
c) Follow this step b) you can get the bad images out of my own datasets. Fortunately, I just had one bad image.
