### ISSUE TITLE
visualize the network model

### ISSUE THREAD

**Issue by zuhaoran** [open-mmlab/mmdetection#2354]
I want to visualize the network model.What should I do?
The image made by netron don't have line.
When Use torchviz, it hint me a mistake,miss the img_meta.

**Comment by brmarkus** [comment]
Which model do you want to visualize?
Which version of Netron do you use?
Do the lines appear if you change the zoom-level? Can you add a screenshot, please?

**Comment by zuhaoran** [comment]
@brmarkus The model is cascade_rcnn_x101_64x4d_fpn_1x
The version of Netron is  4.0.1
![image](https://user-images.githubusercontent.com/17699537/77923728-68331480-72d5-11ea-872e-0064a84c9006.png)

**Comment by brmarkus** [comment]
Hmm, I haven't used Netron with *.pth models.
According to "https://github.com/lutzroeder/netron" looks like it is in "experimental" state:

> Netron has experimental support for TorchScript (.pt, .pth), PyTorch (.pt, .pth)

Maybe you want to ask your question in the Netron's repository "https://github.com/lutzroeder/netron".

**Comment by zuhaoran** [comment]
@brmarkus Is there any way you can convert pytorch's model to onnx's model?
Some people say that netron is unfriendly to pytorch, but more friendly to other models

**Comment by hellock** [comment]
We provide preliminary and experimental support to convert our models to onnx, please refer to the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#convert-to-onnx-experimental).

**Comment by zuhaoran** [comment]
Thank you for your answer
