### ISSUE TITLE
c. Clone the mmdetection repository. Not working.

### ISSUE THREAD

**Issue by AdvertiserM** [open-mmlab/mmdetection#2358]
I open up the Anaconda Prompt, everything goes fine until I reach

`c. Clone the mmdetection repository.

git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection`

Then I get this error 

(open-mmlab) C:\user\Scott\c. Clone the mmdetection repository.

git clone https://github.com/open-mmlab/mmdetection.git 
'git' is not recognized as an internal or external command, operable program or batch file.

**Comment by hellock** [comment]
It is irrelevant to the codebase but the environment. 1. git is not installed in your environment. 2. windows is not officially supported.
