### ISSUE TITLE
What's the use of sync-BN?

### ISSUE THREAD

**Issue by hanjianhua44** [open-mmlab/mmdetection#2359]
In my knowledge, Sync-bn can get a better moving meaning and moving variance, but in mostly models, bn-eval is set to true, which means Sync-bn make no use in backbone?

For example, in htc paper, you said add sync bn in backbone and head can get you about 1.2% increasement, would you like to share how to modify the config file with X152?

**Comment by hellock** [comment]
Yes SyncBN is not used by default. If you would like to have a try, you can add SyncBN [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/conv.py#L6) and then modify the config.
Here is an example of using [GN](https://github.com/open-mmlab/mmdetection/blob/master/configs/gn/mask_rcnn_r50_fpn_gn_2x.py#L2) in the backbone, neck and head. You can do similar things with SyncBN.

However, The official implementation of SyncBN by PyTorch may not be stable.
