### ISSUE TITLE
Training Policy Question

### ISSUE THREAD

**Issue by Moderate28** [open-mmlab/mmdetection#2368]
Hi

Some questions about training policy in mmdetection!

For the model "faster_rcnn_r50_fpn_1x", The backbone and neck are shared by rpn_head and bbox_head, and rpn_head outputs rois to bbox_head.

However, both rpn_head and bbox_head, trained independently, will modify their backbone and neck in different ways. The ancient paper "faster r-cnn" address this issue by 4-step alternating training.

So what's the method to address the issue in mmdetection! 

Thanks

**Comment by hellock** [comment]
The alternating training is outdated and the authors and the community adopt end-to-end training nowadays.

**Comment by Moderate28** [comment]
> The alternating training is outdated and the authors and the community adopt end-to-end training nowadays.

end-to-end like this?

"Approximate joint training: 
In this solution, the RPN and Fast R-CNN networks are merged into one network during training as in Figure 2. In each SGD iteration, the forward pass generates region  proposals which are treated just like fixed, pre-computed proposals when training a Fast R-CNN detector. The backward propagation takes place as usual, where for the shared layers the backward propagated signals from both the RPN loss and the Fast R-CNN loss are combined. This solution is easy to implement. But this solution ignores the derivative w.r.t. the proposal boxes’ coordinates that are also network responses, so is approximate.  "

Thanks

**Comment by hellock** [comment]
Yes.
