### ISSUE TITLE
请问，我在训练自己的COCO格式数据时，用Two-stage的几种方式都可以运行成功，但换到SSD时，就报错了，SSD配置文件修改了num_classes

### ISSUE THREAD

**Issue by liuliaocheng** [open-mmlab/mmdetection#2369]
报错

RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1570910687650/work/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fdd16b3e687 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x17044 (0x7fdd16d7a044 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1cccb (0x7fdd16d7fccb in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x4d (0x7fdd16b2be9d in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x14b2169 (0x7fdd19c93169 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x3327275 (0x7fdd1bb08275 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x39d8ab2 (0x7fdd1c1b9ab2 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x7fdd1c1b9b5f in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0x46 (0x7fdd4a893ed6 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x39ff98c (0x7fdd1c1e098c in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #10: c10::TensorImpl::release_resources() + 0x20 (0x7fdd16b2be70 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #11: <unknown function> + 0x1c8439 (0x7fdd4a894439 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x4b19ab (0x7fdd4ab7d9ab in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x4b19e6 (0x7fdd4ab7d9e6 in /home/lsq/anaconda3/envs/torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #29: __libc_start_main + 0xe7 (0x7fdd5a3d6b97 in /lib/x86_64-linux-gnu/libc.so.6)

已放弃 (核心已转储)

我该如何解决，谢谢！

**Comment by jonguo111** [comment]
I had this problem on the maskrcnn-benchmark. They gave two approaches to solve this issue. One is to change the class numbers, and the other one is to use a smaller learning rate. However, these two ways didn't work well on my custom dataset. By the way, can you evaluate the mAP for your custom data?

**Comment by hellock** [comment]
@liuliaocheng  Please use English or English&Chinese.
