### ISSUE TITLE
Models sensitive to grad clipping

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#2370]
I thought grad clipping has little affect on classic models until I tested it on RetinaNet, it shows around 3 mAP drop on voc2007 dataset without grad clipping. I am wondering what else models are sensitive to grad clipping? Or if it is the case on other dataset like CoCo?

train_set: VOC2007_trainval
test_set: VOC2007_test
gpu: 1
imgs_per_gpu: 1

**Comment by hellock** [comment]
Most models are not sensitive but some are indeed. We do not have a detailed list for that and gradient clipping is adopted by default. Adopting a longer warmup schedule also helps.

**Comment by thisisi3** [comment]
Good to know and thank you for sharing the tip.
