### ISSUE TITLE
autoscale-lr ,imgs_per_gpu and lr?

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#2371]
It seems autoscale-lr does not count imgs_per_gpu, does that mean if I changed imgs_per_gpu, I can no longer use a simple autoscale-lr? Instead I need to apply linear scale rule to manually set lr in config?

**Comment by PanJianning** [comment]
Yes.

**Comment by hellock** [comment]
We recommend modifying the learning rate manually.
