### ISSUE TITLE
Is is possible to predict out of image borders boxes?

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection#2382]
In some datasets, ex. CrowdHuman with full body mark up, there are boxes that are partially out of image borders, ex, `x_min < 0` or `x_max > img_width`. Looks like mmdetection always crops its predictions to `0 <= x <= img_width` by calling `distance2bbox(..., max_shape=img_shape)` in `FCOSHead` or `delta2bbox(..., max_shape=img_shape)` in `AnchorHead`.

Is is possible to work with such boxes in current version of mmdetection? One can set `max_shape=None` in this calls, but is it enough? Should one increase `allowed_border` in `train_cfg` or change something else?

Thank you.

**Comment by ZwwWayne** [comment]
Set `allowed_border-1` and `max_shape=None` should be enough.

**Comment by filaPro** [comment]
Thank you for the answer.
