### ISSUE TITLE
initialize the weights of DeformConvPack

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#2384]
Hi there, thanks for making this great toolbox.

I saw there is a new function for DCN, namely, DeformConvPack, which integrates the offset prediction and deformable convolution together, making the usage of DCN easier. 

I have a question about its usage,  that is,  **when using the DeformConvPack, do I still need to manually initialize its weights?** 

Because I am aware that there is a self.reset_parameters() in DeformConv and a self.init_offset() in DeformConvPack respectively, and I think they are doing the initialization work. 

Thank you.

**Comment by xvjiarui** [comment]
Hi @hyz-xmaster 
`self.init_offset()` and `self.reset_parameters()` would initialize them by default. In most cases, it should be fine. 
Note: You should be cautious that they could be overwritten by other initialization. Please refer to the `self.init_weights()` in `ResNet` to see how to init `DCN` in backbone.

**Comment by hyz-xmaster** [comment]
Hi @xvjiarui Thank you for the quick reply and it is really helpful.
