### ISSUE TITLE
anchor optimization

### ISSUE THREAD

**Issue by Maxfashko** [open-mmlab/mmdetection#2386]
Hello. I want to discuss the topic of the optimal hyperparameters selection for anchors.
I performed some experiments with my dataset (coco format). I tried to calculate how the default hyperparameters suit my dataset.
I generated anchors for this configuration file https://github.com/open-mmlab/mmdetection/blob/master/configs/cascade_rcnn_x101_32x4d_fpn_1x.py
I got anchors using the `grid_anchors` function
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_generator.py#L66

for example, the basic anchors based on the above config are provided as follows:
```
tensor([[-21.,  -9.,  24.,  12.],
        [-14., -14.,  17.,  17.],
        [ -9., -21.,  12.,  24.]])
tensor([[-41., -19.,  48.,  26.],
        [-28., -28.,  35.,  35.],
        [-19., -41.,  26.,  48.]])
tensor([[-83., -37.,  98.,  52.],
        [-56., -56.,  71.,  71.],
        [-37., -83.,  52.,  98.]])
tensor([[-165.,  -75.,  196.,  106.],
        [-112., -112.,  143.,  143.],
        [ -75., -165.,  106.,  196.]])
tensor([[-330., -149.,  393.,  212.],
        [-224., -224.,  287.,  287.],
        [-149., -330.,  212.,  393.]])
```

Then I converted bboxes used in my dataset from xywh -> xyxy

Then I used the `bbox_overlaps` function https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/geometry.py#L4 to understand how the bboxes used in my dataset are overlapped with anchors.
I chose the threshold `iou = 0.7`

```
iou_thresh=0.7

overlaps = bbox_overlaps(annotations, all_anchors)
max_overlap = np.amax(overlaps, axis=1)
not_matched = len(np.where(max_overlap < iou_thresh)[0])
```

I got a very unsatisfactory result -> 7046 boxes (out of 10000) with an anchor overlap threshold of less than 0.7

Tell me whether I used the anchors generated by the `grid_anchors` function correctly for such a comparative analysis or not. Maybe these anchors are changed somewhere in the network learning process?

I want to use the optimization algorithm in order to obtain the optimal values for striders and ratios in the future.

**Comment by ZwwWayne** [comment]
The anchors will not change, but the assigner will find a suitable anchor if all the anchors has you less than 0.7 with one GT box. The anchor's setting may not be optimal, you could try to tune those parameters if you are interested.

**Comment by Maxfashko** [comment]
@ZwwWayne I performed some experiments to optimize anchors. For example, it came as a surprise to me that with an increase in the number of scale and ratios parameters to 3, the training time increases significantly. As I understand it, when using the standard hyperparameters `scale = [1], ratios = [1, 2, 3]`, as well as `fpn_out = 5`, we get `15` base anchors at all FPN levels. But when using `scale=[1, 2, 3], ratios=[1, 2, 3]` we already have three times as many basic anchors: `45`.
In my experiments, when choosing the optimal scale and ratios, I was able to increase mAP by 3%, but the training time increased by 3 times. Is there any simple explanation for this?

**Comment by ZwwWayne** [comment]
The number of anchors is increased by 2 times, which may cause the anchor assigning process a bottleneck of efficiency, e.g., the IoU calculation might be very cost.

**Comment by Asaad-Nasrallah** [comment]
> @ZwwWayne I performed some experiments to optimize anchors. For example, it came as a surprise to me that with an increase in the number of scale and ratios parameters to 3 values, the training time increases significantly. As I understand it, when using the standard hyperparameters `scale = [1], ratios = [1, 2, 3]`, as well as `fpn_out = 5`, we get `15` base anchors at all FPN levels. But when using `scale=[1, 2, 3], ratios=[1, 2, 3]` we already have three times as many basic anchors: `45`. In my experiments, when choosing the optimal scale and ratios, I was able to increase mAP by 3%, but the training time increased by 3 times. Is there any simple explanation for this?



> @ZwwWayne I performed some experiments to optimize anchors. For example, it came as a surprise to me that with an increase in the number of scale and ratios parameters to 3 values, the training time increases significantly. As I understand it, when using the standard hyperparameters `scale = [1], ratios = [1, 2, 3]`, as well as `fpn_out = 5`, we get `15` base anchors at all FPN levels. But when using `scale=[1, 2, 3], ratios=[1, 2, 3]` we already have three times as many basic anchors: `45`. In my experiments, when choosing the optimal scale and ratios, I was able to increase mAP by 3%, but the training time increased by 3 times. Is there any simple explanation for this?

How can I find best scales and ratios for my dataset ??
