### ISSUE TITLE
The corelation between anchor_scale and map_roi_levels ?

### ISSUE THREAD

**Issue by Moderate28** [open-mmlab/mmdetection#2387]
Hello
Question about the corelation between anchor_scale and map_roi_levels.
The question may be fundamental but i'm confused!

The most initial configs such as "faster_rcnn_r50_fpn_1x.py" would set anchor_scales=[8] in rpn_head, which means anchors would have scale 32, 64, 128, 256 and 512 for feature map P2, P3, P4, P5 and P6

However, the function map_roi_levels in  \mmdet\models\roi_extractors  would do
`        """Map rois to corresponding feature levels by scales.
        - scale < finest_scale * 2: level 0
        - finest_scale * 2 <= scale < finest_scale * 4: level 1
        - finest_scale * 4 <= scale < finest_scale * 8: level 2
        - scale >= finest_scale * 8: level 3
        """`
the default **finest_scale is 56**

It seems strange as below
P2             anchor_scale set for rpn_head: 32           mapped_roi_scale for roi_extractor: 0-112
P3             anchor_scale set for rpn_head: 64           mapped_roi_scale for roi_extractor: 112-224
P4             anchor_scale set for rpn_head: 128         mapped_roi_scale for roi_extractor: 224-448
P5             anchor_scale set for rpn_head: 256         mapped_roi_scale for roi_extractor: 448-

So why the mapped_roi_scale for roi_extractor don't approximately match the anchor_scale for rpn_head?

Thanks

**Comment by Moderate28** [comment]
It seems strange as below:

P2 anchor_scale set for rpn_head: 32 mapped_roi_scale for roi_extractor: 0~112
P3 anchor_scale set for rpn_head: 64 mapped_roi_scale for roi_extractor: 112~224
P4 anchor_scale set for rpn_head: 128 mapped_roi_scale for roi_extractor: 224~448
P5 anchor_scale set for rpn_head: 256 mapped_roi_scale for roi_extractor: 448~

So why the mapped_roi_scale for roi_extractor don't approximately match the anchor_scale for rpn_head?

**Comment by ZwwWayne** [comment]
Hi @Moderate28 ,
Maybe it is because that the RoIs are predicted based on the anchor, which does not have exactly the same scales as the anchor?

**Comment by Moderate28** [comment]
Thanks for your comments!    @ZwwWayne 

I wonder whether the performance would be improved if we make **default finest_scale** smaller to make two scales approximate.

Please share if anyone has ever done such experiments before! Thanks!

**Comment by Moderate28** [comment]
I will do such experiments in a few days!

**Comment by luuuyi** [comment]
@Moderate28 have you get some result about this?

**Comment by Moderate28** [comment]
@luuuyi   Thanks for your attention!
Not yet, i'm preparing othor work these days.
I'll return to the mentioned experiments next week.

If you wonder the results, you can also do some experiments.

**Comment by Moderate28** [comment]
Smaller default finest_scale doesn't work better.

Maybe the unstable results on my small dataset couldn't reveal the problem.

**Comment by dadada101** [comment]
It seems the implementation doesn't comply with the original FPN paper? as introduced as follows
![捕获](https://user-images.githubusercontent.com/69999981/108449707-dfcbb280-729e-11eb-8ef8-a40921fb66c6.PNG)

**Comment by C-H-Wong** [comment]
Cause 'k' of 'Pk' in paper start from 2, while 'level' in code start from 0, there is no difference.
