### ISSUE TITLE
mask_rcnn_hrnetv2p_w48_2x config file is missing. Please add it

### ISSUE THREAD

**Issue by sarimmehdi** [open-mmlab/mmdetection#2402]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
mask_rcnn_hrnetv2p_w48_2x config file is missing.

**Comment by hellock** [comment]
Adding all configs files are redundant and inconvenient to maintain, and it is easy to adapt one from another. You may can simply modify from existing configs.
