### ISSUE TITLE
How can I save the results of running test.py as an image?

### ISSUE THREAD

**Issue by marload** [open-mmlab/mmdetection#2407]
I am using mmdetection in linux using ssh. test.py --show is not available because it is used by command line. How can I save this result as an image?

**Comment by ZwwWayne** [comment]
You may save the pickle results first and plot them in another script.

**Comment by hellock** [comment]
Or you may use the [high-level APIs](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#high-level-apis-for-testing-images) to do it.

**Comment by marload** [comment]
Thx!
