### ISSUE TITLE
Is it possible to save predictions of a model in COCO format?

### ISSUE THREAD

**Issue by AlexFridman** [open-mmlab/mmdetection#2415]
Hello!

I would like to run `tools/coco_error_analysis.py`, but it requires `result` (json-file). How could I build/save such a result file?
Is there's a way to save predictions for a dataset in COCO format?

Thank you!

**Comment by xvjiarui** [comment]
Hi @AlexFridman 
You may run `tools/test.py` with `--options jsonfile_prefix=./mask_rcnn_test-dev_results` for COCO dataset. 
Please refer to [GETTING_STARTED](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#inference-with-pretrained-models) for details.

**Comment by AlexFridman** [comment]
Hello, @xvjiarui ! Thank you for the quick response!

Getting started guide maybe a bit overloaded :)

**Comment by FirasKedidi** [comment]
> Hi @AlexFridman
> You may run `tools/test.py` with `--options jsonfile_prefix=./mask_rcnn_test-dev_results` for COCO dataset.
> Please refer to [GETTING_STARTED](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#inference-with-pretrained-models) for details.

Can it be done without the annotation file ??

**Comment by GeorgePearse** [comment]
Can't find this implemented anywhere in MMDet 3.0?

**Comment by Alaric423** [comment]
Any update to save the prediction result in COCO form in MMDet 3.0？

**Comment by Ljung323** [comment]
in MMDet 3.0, we can run `tools/test.py` with `--cfg-options test_evaluator.outfile_prefix=/path/to/json/`

or update the config file to specify the option
`test_evaluator = dict(format_only=True, outfile_prefix=/path/to/json/)`

https://mmdetection.readthedocs.io/en/3.x/user_guides/test_results_submission.html#update-them-in-command-line
