### ISSUE TITLE
it seems Aliyun mirror is not work

### ISSUE THREAD

**Issue by wbh604** [open-mmlab/mmdetection#2423]
When I try to dowload the pre-trained model, I met the error like as follows:
The URL:
https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
The error information:
<Error>
<Code>UserDisable</Code>
<Message>UserDisable</Message>
<RequestId>5E8F4BEB3373BA353459D9B0</RequestId>
<HostId>open-mmlab.oss-cn-beijing.aliyuncs.com</HostId>
</Error>

**Comment by hellock** [comment]
It should be available now. The charge was overdue.
