### ISSUE TITLE
Finetuning related documentation missing

### ISSUE THREAD

**Issue by tiberium24** [open-mmlab/mmdetection#2424]
I have been through some previous issues posted about how to finetune. 
Finetune means getting some pretrained weights from COCO for example and doing "resume from" option and then train on your own dataset. That part is easy. 
The question is how can you change the number of model classes at the end which is commonly referred as "changing the last layer  for your dataset".

Could you provide a guide here at first on how to do it for faster_rcnn_x101_32?
That would be helpful for many others.

**Comment by ZwwWayne** [comment]
Hi @tiberium24 ,
A simple way is to change `num_class` in the head of the config and add the model path in `load_from`.
A template is the [configs](mask_rcnn_r50_fpn_1x_cityscapes.py) for training cityscapes.
Thanks for your suggestion, we will do it in the next release.
