### ISSUE TITLE
Just a quick wonder: why resize to 1333, 800

### ISSUE THREAD

**Issue by leemengwei** [open-mmlab/mmdetection#2428]
most configuration file  have
 img_scale=[(1333, 800)]
or 
dict(type='Resize', img_scale=(1333,800), keep_ratio=True)

wonder how's that come from?

**Comment by leemengwei** [comment]
@hellock

**Comment by stevehjc** [comment]
In Fast RCNN, Faster RCNN (without FPN) paper: shorter side s=600

In FPN paper: shorter side s=800
[Feature Pyramid Networks for Object Detection](https://arxiv.org/abs/1612.03144)
