### ISSUE TITLE
ap very low

### ISSUE THREAD

**Issue by Chenney0813** [open-mmlab/mmdetection#243]
I train the model with cascade_rcnn and only get 0.0004AP,I want to know what happened
`2019-01-07 18:47:37,338 - INFO - Epoch [1][8684/8684]	lr: 0.01000, bbox_mAP: 0.0004` 
`2019-01-07 21:15:55,253 - INFO - Epoch [2][8684/8684]	lr: 0.01000, bbox_mAP: 0.0000`
`2019-01-07 23:44:15,963 - INFO - Epoch [3][8684/8684]	lr: 0.01000, bbox_mAP: 0.0001`
`2019-01-07 23:42:07,254 - INFO - Epoch [3][8650/8684]	lr: 0.01000, eta: 1 day, 7:45:51, time: 1.004, data_time: 0.004, loss_rpn_cls: 0.0100, loss_rpn_reg: 0.0053, s0.loss_cls: 0.0503, s0.acc: 98.2285, s0.loss_reg: 0.0377, s1.loss_cls: 0.0222, s1.acc: 98.4700, s1.loss_reg: 0.0576, s2.loss_cls: 0.0117, s2.acc: 98.3085, s2.loss_reg: 0.0489, loss: 0.2438`

**Comment by EtienneDavid** [comment]
@Chenney0813 what was your error ? I face similar issue and don't know if it comes from the model or my annotation (which look good when i check with COCOstuff)
