### ISSUE TITLE
error: command 'g++' failed with exit status 1

### ISSUE THREAD

**Issue by zyuh** [open-mmlab/mmdetection#2430]
i install mmdetection in conda virtual environment with 'python setup.py develop'.
but it tells me, ''ImportError: ***/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/../../../libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /DB/rhome/yuhangzhou/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)'',
####
then i remove original libstdc++.so.6,  and run ''ln -s libstdc++.so.6.0.26 libstdc++.so.6''
after that, i run '''python setup.py develop' again,
#### it prints:
running build_ext
building 'mmdet.ops.utils.compiling_info' extension
gcc -pthread -B /****/miniconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/****/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/****/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/***/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/****/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/****/miniconda3/envs/open-mmlab/include/python3.7m -c mmdet/ops/utils/src/compiling_info.cpp -o build/temp.linux-x86_64-3.7/mmdet/ops/utils/src/compiling_info.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=compiling_info -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/mmdet
creating build/lib.linux-x86_64-3.7/mmdet/ops
creating build/lib.linux-x86_64-3.7/mmdet/ops/utils
g++ -pthread -shared -B ***/miniconda3/envs/open-mmlab/compiler_compat -L/***/miniconda3/envs/open-mmlab/lib -Wl,-rpath=***/miniconda3/envs/open-mmlab/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/mmdet/ops/utils/src/compiling_info.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.7/mmdet/ops/utils/compiling_info.cpython-37m-x86_64-linux-gnu.so
/****/miniconda3/envs/open-mmlab/compiler_compat/ld: cannot find -lm
/*****/miniconda3/envs/open-mmlab/compiler_compat/ld: cannot find -lpthread
/****/miniconda3/envs/open-mmlab/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
###
ps: in my conda virtual environmen, i used ''conda install -c psi4 gcc-5'', after that, when i run 'gcc -v' or 'g++ -v', 
####it prints:
Reading specs from /***/miniconda3/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/***/miniconda3/gcc/libexec/gcc/x86_64-unknown-linux-gnu/5.2.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/***/miniconda3/gcc --with-gxx-include-dir=/***/miniconda3/gcc/include/c++ --bindir=/****/miniconda3/bin --datarootdir=/****/miniconda3/share --libdir=/****/miniconda3/lib --with-gmp=/***/miniconda3 --with-mpfr=/****/miniconda3 --with-mpc=/****/miniconda3 --with-isl=/*****/miniconda3 --with-cloog=/****/miniconda3 --enable-checking=release --with-tune=generic --disable-multilib
Thread model: posix
gcc version 5.2.0 (GCC) 
####
i am not a root member. 
thank you!

**Comment by MrNN233** [comment]
I have the same problem.
/home/computer/anaconda3/compiler_compat/ld: cannot find -lm
/home/computer/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/computer/anaconda3/compiler_compat/ld: cannot find -lc

Have you solved the probelm?

**Comment by zyuh** [comment]
i have not solved it. and did you also run ''conda install -c psi4 gcc-5'' ?&nbsp; i guess it may be produce some problems but i am not sure.
if you solve this problem, please tell me. and so do i.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MrNN233"<notifications@github.com&gt;; 
发送时间: 2020年4月11日(星期六) 下午5:32
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;; 
抄送: "。.=`待ィ+."<834805028@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmdetection] error: command &#39;g++&#39; failed with exit status 1 (#2430)





 
I have the same problem.
 /home/computer/anaconda3/compiler_compat/ld: cannot find -lm
 /home/computer/anaconda3/compiler_compat/ld: cannot find -lpthread
 /home/computer/anaconda3/compiler_compat/ld: cannot find -lc
 
Have you solved the probelm?

**Comment by MrNN233** [comment]
Good news! I sovled it. Try this method:
[https://stackoverflow.com/questions/47512182/cannot-find-lfftw3-omp-error-when-compiling-a-third-party-package-how-to-lin](url)

So first you excute `ld -lpthread --verbose`
And get the path1 which shows 'succeed'
Finally excute `ln -s path1 `path2(/**/miniconda3/envs/open-mmlab/compiler_compat)`
My path2 is `/home/computer/anaconda3/compiler_compat`

Now you can excute `python setup.py develop`
It will take a long time(Maybe 10 mins) and I got lots of warnings.

I hope the method will be helpful to you!
 
I guess you are Chinese. If so, we can communicate in Chinese.

**Comment by MrNN233** [comment]
Good news! I solved the problem! Try this method:
[https://stackoverflow.com/questions/47512182/cannot-find-lfftw3-omp-error-when-compiling-a-third-party-package-how-to-lin](url)

excute `ld -lc --verbose` and get path1 which shows 'scueeded'
and excute `ln -s path1 path2`
My path2 is '/home/computer/anaconda3/compiler_compat'

Now you can excute `python setup.py develop`
It will take a long time(maybe 10 mins) and maybe you will get lots of warnings.

I hope it will be helpful to you!
I guees you are Chinese.If so, we can communicate in Chinese.

**Comment by zyuh** [comment]
thank you! i use the similar methods, and also&nbsp;get lots of warnings. at last, it prints 'Finished processing dependencies for mmdet==1.1.0+365c930'
But can you run the demo?&nbsp;
when i run the demo, it prints 'ImportError: ***/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: atexit', and you?
yes,&nbsp;i am chinese too, can we add qq friend or wechat? my qq number can be seen in my email site.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MrNN233"<notifications@github.com&gt;; 
发送时间: 2020年4月11日(星期六) 晚上6:46
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;; 
抄送: "。.=`待ィ+."<834805028@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmdetection] error: command &#39;g++&#39; failed with exit status 1 (#2430)





 
Good news! I solved the problem! Try this method:
 https://stackoverflow.com/questions/47512182/cannot-find-lfftw3-omp-error-when-compiling-a-third-party-package-how-to-lin
 
excute ld -lc --verbose and get path1 which shows 'scueeded'
 and excute ln -s path1 path2
 My path2 is '/home/computer/anaconda3/compiler_compat'
 
Now you can excute python setup.py develop
 It will take a long time(maybe 10 mins) and maybe you will get lots of warnings.
 
I hope it will be helpful to you!
 I guees you are Chinese.If so, we can communicate in Chinese.
