### ISSUE TITLE
Trained model for HTC ResNet 50 with DCN

### ISSUE THREAD

**Issue by BloomBabe** [open-mmlab/mmdetection#2431]
Hello, I would like to ask if it is possible to ask to train the model HTC ResNet 50 with DCN on the COCO dataset and add a trained model to Model Zoo, since the capabilities of my graphics card do not allow me to do this quickly. I would be very grateful, thanks.

**Comment by hellock** [comment]
We try the best to maintain the codebase but sorry that we cannot help training additional models, which is out of our resources.
