### ISSUE TITLE
how to convert cityscapes to pascal voc format? could you give any instructions?

### ISSUE THREAD

**Issue by Emma0118** [open-mmlab/mmdetection#2439]

**Comment by hellock** [comment]
You can learn the format of cityscapes and voc datasets and then write a script to do so if you indeed want to.
Here is an example how to convert it to coco format: https://github.com/open-mmlab/mmdetection/blob/master/tools/convert_datasets/cityscapes.py.

**Comment by Emma0118** [comment]
ok, many thanks.
