### ISSUE TITLE
img_norm_cfg for pretrained backbone 'open-mmlab://vgg16_caffe'

### ISSUE THREAD

**Issue by liyiwei979621500** [open-mmlab/mmdetection#2441]
What img_norm_cfg should I set if I want to use the pretrained vgg16 backbone?

Should I use the img_norm_cfg_from ssd300?
https://github.com/open-mmlab/mmdetection/blob/25ede58af6072ea8089af7b42cbb418a3b6991e9/configs/ssd300_coco.py#L49

**Comment by ZwwWayne** [comment]
If you are using the same backbone model, then you do not need to change that. If you are using other backbone models, you should check the img_norm accordingly.

**Comment by liyiwei979621500** [comment]
@ZwwWayne thanks
