### ISSUE TITLE
How to only train GA-RPN?

### ISSUE THREAD

**Issue by hanjianhua44** [open-mmlab/mmdetection#2444]
We want to finetune trained detectors with the proposals generated by GA-RPN and we want to know how to only train GA-RPN?

**Comment by hanjianhua44** [comment]
@hellock hi, I trained a ga-rpn on X101, 32*4d, then I use the proposal list to finetune Faster rcnn r50 for 3 epochs（with lr 0.02, 0.002, 0.0002, rpn off）,  after that I got 37.3% mAp on val.

The gudied achor paper shows that when use ga-rpn for fintuning can get 2% increase with ga-rpn res50, but I only get 1% increase(36.4->37.4%)?

It means I should finetune more steps when using stronger ga-rpn backbone or it will get 2% increase when I use matched backbone (ga-rpn-res50)?

By the way, for both train and inference,  I used https://github.com/open-mmlab/mmdetection/blob/master/configs/guided_anchoring/ga_rpn_x101_32x4d_fpn_1x.py test_cfg.rpn for finetuning.

**Comment by hanjianhua44** [comment]
By the way, for finetuning, I didn't increase Iou threshold to 0.6 and the number of ga-rpn proposal I used for (nms_pre, nms_post, max_num) is (2000, 2000, 2000), the score threshold I use is 0.05.

**Comment by hellock** [comment]
You did not follow the hyper-parameters proposed in the paper.

**Comment by myownskyW7** [comment]
To follow the hyper-parameters in the original paper. You should also change max_num to 300.
