### ISSUE TITLE
RuntimeError: cuda runtime error (98) : unrecognized error code at mmdet/ops/roi_align/src/roi_align_kernel.cu:139

### ISSUE THREAD

**Issue by yuguangs** [open-mmlab/mmdetection#2445]
when run the demo ,meet the problem

**environment info：**
ubuntu16.04
gcc5.4.0
cuda10.0.130
cudnn7.6.0
PyTorch.1.0   from source

thanks for your help

import os
from mmdet.apis import init_detector, inference_detector, show_result

if __name__ == '__main__':
	config_file = 'configs/faster_rcnn_r50_fpn_1x.py'
	checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
	# checkpoint_file = 'tools/work_dirs/mask_rcnn_r101_fpn_1x/epoch_1200.pth'
	img_path = 'demo/demo.jpg'
	model = init_detector(config_file, checkpoint_file, device='cuda:0')
	print(model)
	# 输入可以为文件夹或者图片
	if os.path.isdir(img_path):
		imgs= os.listdir(img_path)
		for i in range(len(imgs)):
			imgs[i]=os.path.join(img_path,imgs[i])
		for i, result in enumerate(inference_detector(model, imgs)):	# 支持可迭代输入imgs
			print(i, imgs[i])
			show_result(imgs[i], result, model.CLASSES, out_file='output/result_{}.jpg'.format(i))

	elif os.path.isfile(img_path):
         print(1)

         result = inference_detector(model, img_path)
         show_result(img_path, result, model.CLASSES)

File "/home/re31/mmdetection/mmdet/ops/roi_align/roi_align.py", line 36, in forward
    spatial_scale, sample_num, output)
RuntimeError: cuda runtime error (98) : unrecognized error code at mmdet/ops/roi_align/src/roi_align_kernel.cu:139

**Comment by Zhang-ren** [comment]
I I have the same problem. How to solve it

**Comment by yuguangs** [comment]
Check the pytorch environment to ensure that CUDA Toolkit and torch match

**Comment by yuguangs** [comment]
> 二有同样的问题。如何解决

Check the pytorch environment to ensure that CUDA Toolkit and torch match

**Comment by yuguangs** [comment]
> I I have the same problem. How to solve it

Check the pytorch environment to ensure that CUDA Toolkit and torch match
