### ISSUE TITLE
mmdetection to tensorflow model

### ISSUE THREAD

**Issue by marload** [open-mmlab/mmdetection#2447]
I learned cascade rcnnn with mmdetection. To deploy this model, you need to convert it to a tensorflow model. What should I do?

**Comment by hellock** [comment]
We do not provide support for converting models to tf, but you may refer to common methods for converting pytorch models to tf.

**Comment by marload** [comment]
Thanks You!

**Comment by Mohamed-Hazem-Abdo** [comment]
@marload  
hello,
I am having the same problem did you find a solution?
