### ISSUE TITLE
Save mAP evaluation result

### ISSUE THREAD

**Issue by StringBottle** [open-mmlab/mmdetection#2449]
Hello, mmdetection team. 

Is there any option to save mAP evaluation result? As far as I looked through, there are only options to save bounindg box and segmentation information of detection results. 

Can you let me know if it is currently available option or not? 
If it is not available, I would like to make a pull request of it.

**Comment by hellock** [comment]
What do you mean by "saving mAP evaluation result"? I suppose that we can just copy and paste the numbers printed in the terminal.
BTW, all the evaluation results are saved in the json log file.

**Comment by StringBottle** [comment]
@hellock  

I wanted to save the mAP numbers printed in the terminal while testing multiple configs. In my case, I need to test multiple configuration files at a time.  It was bit inconvenient  to copy and paste the numbers every time runs the test script.

**Comment by ZwwWayne** [comment]
You may add `2>&1 | tee ap_log.txt` in your command.
