### ISSUE TITLE
Cannot install with CUDA9.0

### ISSUE THREAD

**Issue by Mabinogiysk** [open-mmlab/mmdetection#2456]
I found it impossible to install mmdetection with cuda9.0 because there is no compatible version for torchvision with cuda9.0.
I have searched all packages in pip and conda, the minimum cuda version required for torchvision is 9.2 on linux. when I executed command `conda install pytorch torchvision -c pytorch`,  torchvision0.2.1 and torch0.4.1 were installed.
Is there any solusion？

**Comment by hellock** [comment]
Option 1: Install a newer version CUDA
Option 2: Build PyTorch from source to support CUDA 9.0
Option 3: Install PyTorch 1.1. (Since 1.2, no prebuilt pytorch packages with CUDA 9 are provided)
