### ISSUE TITLE
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by LaMeiMitsuda** [open-mmlab/mmdetection#2458]
I install mmdetection in conda. But I failed to install it. And I can't find any similar issues from network.

My env:
pyhton：3.7.0
cuda：10.1
pytorch: 1.2.0
gcc: 5.5.0

 The error print:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h(54): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(98): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(100): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(116): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(120): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(151): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(153): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(157): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(162): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(176): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(178): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(196): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(208): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(52): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(54): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(77): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(98): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(100): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(116): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(120): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(151): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(153): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(157): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(162): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(176): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(178): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(196): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(204): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(52): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(54): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(77): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(98): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(100): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(116): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(120): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(151): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(153): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(157): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(162): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(176): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(178): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(196): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(204): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(52): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(54): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(63): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(65): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(77): error: variable "_Mdouble_END_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(98): error: variable "_Mdouble_BEGIN_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(100): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(109): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(116): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(120): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(151): error: variable "_Mdouble_BEGIN_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(153): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(157): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(162): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(176): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(178): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(196): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(204): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(52): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(54): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(63): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(65): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(77): error: variable "_Mdouble_END_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(98): error: variable "_Mdouble_BEGIN_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(100): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(109): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(116): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(120): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(151): error: variable "_Mdouble_BEGIN_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(153): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(157): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(162): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(176): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(178): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(196): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(204): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(52): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(54): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(63): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(65): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(77): error: variable "_Mdouble_END_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(81): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(98): error: variable "_Mdouble_BEGIN_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(100): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(109): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(116): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(120): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(151): error: variable "_Mdouble_BEGIN_NAMESPACE" is not a type name

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(153): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(157): error: variable "_Mdouble_END_NAMESPACE" has already been defined

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(162): error: expected a ";"

/usr/include/x86_64-linux-gnu/bits/mathcalls.h(176): error: variable "_Mdouble_BEGIN_NAMESPACE" has already been defined

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00000365_00000000-6_nms_kernel.cpp1.ii".
Compilation terminated.

**Comment by LaMeiMitsuda** [comment]
The last bottom error is 'error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1'.

**Comment by hellock** [comment]
Installation errors are mostly related to your environment. We cannot help with the information you provided.

**Comment by LaMeiMitsuda** [comment]
> Installation errors are mostly related to your environment. We cannot help with the information you provided.

Thx for replying. What information do you want?  I try my best to provide.

**Comment by guotong1988** [comment]
Similar Question.

```
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:6681:95:   required from here
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1
```

**Comment by guotong1988** [comment]
I change gcc 7 to 5.3.1 and setup successful.

**Comment by xuyingheng** [comment]
yep u need change gcc version.gcc 7 to 5.5 and setup successful
