### ISSUE TITLE
Qs on multiclass_nms.

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#2462]
The implementation of multiclass_nms is not what I expected, it seems one bbox who has already been participated in one nms can still participate in the next nms, wouldn't it make it possible that one bbox who suvived two nms has two different labels? I know you guys must have a reason doing this, I wonder what it is.

**Comment by hellock** [comment]
The NMS process of each class is independent, which is a standard (and official) practice for R-CNN series.

**Comment by thisisi3** [comment]
Good to know.
