### ISSUE TITLE
How to use the ".pkl" files?

### ISSUE THREAD

**Issue by JKingKong** [open-mmlab/mmdetection#2463]
After Run this code:
**python tools/test.py configs/faster_rcnn_r50_fpn_1x.py 
    checkpoints/epoch_200.pth 
    --out results.pkl --eval bbox**
output a "results.pkl" file.
How to use the "results.pkl" file?

**Comment by hellock** [comment]
All detection results are saved in this pickle file. You can load and use it as you will.

**Comment by octavianplesea** [comment]
Hello @hellock , Can you please tell me how I can visualize the detection results from a pickle file?

**Comment by ODAncona** [comment]
If you want to understand, you can always have a look on the file mmdetection/tools/analysis_tools/eval_metric.py

Or if you only want to use your result you can do it with the command:

```python
command = f"python mmdetection/tools/analysis_tools/eval_metric.py {configPath}\
    {resultPath} \
    --eval bbox \
    "
os.system(command)
```
