### ISSUE TITLE
pip install -v -e .

### ISSUE THREAD

**Issue by njustczr** [open-mmlab/mmdetection#2464]
Created temporary directory: /tmp/pip-ephem-wheel-cache-s6haovgi
Created temporary directory: /tmp/pip-req-tracker-ew2ahqsb
Created requirements tracker '/tmp/pip-req-tracker-ew2ahqsb'
Created temporary directory: /tmp/pip-install-9uz2osh_
Looking in indexes: http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/
Obtaining file:///root/mmdetection
  Added file:///root/mmdetection to build tracker '/tmp/pip-req-tracker-ew2ahqsb'
    Running setup.py (path:/root/mmdetection/setup.py) egg_info for package from file:///root/mmdetection
    Running command python setup.py egg_info
    error in mmdet setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
Cleaning up...
Removed file:///root/mmdetection from build tracker '/tmp/pip-req-tracker-ew2ahqsb'
Removed build tracker '/tmp/pip-req-tracker-ew2ahqsb'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

my environment: python3.6 pytorch1.3 cuda10

**Comment by njustczr** [comment]
my problem...

**Comment by guyii54** [comment]
hello, I have met the same problem. How can I fix this problem? My environment is the same with you. thx a lot

**Comment by njustczr** [comment]
> hello, I have met the same problem. How can I fix this problem? My environment is the same with you. thx a lot

i think you should install coco api and
cd mmdetection
pip install -r requirements/build.txt
pip install Cython
pip install pytest-runner
pip install mmcv
pip install numpy
pip install -v -e .

**Comment by guyii54** [comment]
> > hello, I have met the same problem. How can I fix this problem? My environment is the same with you. thx a lot
> 
> i think you should install coco api and
> cd mmdetection
> pip install -r requirements/build.txt
> pip install Cython
> pip install pytest-runner
> pip install mmcv
> pip install numpy
> pip install -v -e .

Thank you very much. I figure out that my problem lies in nvidia driven software.
