### ISSUE TITLE
SSD300_voc model size is too big

### ISSUE THREAD

**Issue by XeniAlovich** [open-mmlab/mmdetection#2468]
Hi
Tell me please, which parameter need I change in ssd300_voc.py to make the model smaller?
I trained the model on my own dataset with a standard config and the onnx file size was 95 mb. It's too much for my task. How can I fix it?
Thanks!

**Comment by hellock** [comment]
You can design a more lightweight model, e.g., by reducing channels or number of layers, and train it by yourself.
