### ISSUE TITLE
multiclass_nms loses 1 detection result each time

### ISSUE THREAD

**Issue by c1aris** [open-mmlab/mmdetection#2475]
At this line in V2.0,
https://github.com/open-mmlab/mmdetection/blob/127a5d28afe6c90814b18caa07413637752fc54f/mmdet/core/post_processing/bbox_nms.py#L52
the `multiclass_nms` method will lose 1 detection result if `max_num` is not specified and be set to `-1` by default. I was wondering is there any reason to do that?

**Comment by hellock** [comment]
Thanks for reporting and It is a bug. We need to check if max_num > 0 before slicing. PRs are welcome!

**Comment by c1aris** [comment]
Done in #2486.
