### ISSUE TITLE
Is old version eg.mmdet==1.0 support data augmentation??

### ISSUE THREAD

**Issue by RonDen** [open-mmlab/mmdetection#2477]
Hi~ I have noticed that the mmdet==1.1 use albu for data augmentation.
But I have to use mmdet==1.0 for my training.
I have to add data augmentation to my training process because of the lack of training data (already converted to `json` format of course).

When I use the `albu_example/ms_rcnn_r50_fpn_1x.py` there is an error:
```
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 109, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/ldap_shared/home/s_zyt/inseg/PolarMask/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/ldap_shared/home/s_zyt/inseg/PolarMask/mmdet/utils/registry.py", line 74, in build_from_cfg
    return obj_type(**args)
TypeError: __init__() got an unexpected keyword argument 'pipeline'
```

It seems that mmdet==1.0 doesn't support `pipeline` and albu augmentation.

How can I solve this?

**Comment by PanJianning** [comment]
You can refer to some [configs](https://github.com/open-mmlab/mmdetection/blob/v1.0rc0/configs/dcn/cascade_rcnn_dconv_c3-c5_r50_fpn_1x.py#L195) of v1.0

**Comment by RonDen** [comment]
Thank you for your advise.

It seems only `flip` supported after finding a lot of `configs` and reading the docs. More augmentations is needed in my problem.

But I finnaly solve this by using `imgaug` lib and write the image to disk.
Not elegant but work.
