### ISSUE TITLE
ResNeXt-32x8d-101-FPN

### ISSUE THREAD

**Issue by shengshiH** [open-mmlab/mmdetection#2479]
Hello, I notice that some papers used ResNeXt-32x8d-101-FPN as their backbone while ResNeXt-32x4d-101-FPN and ResNeXt-64x4d-101-FPN are used in mmdetection. Do you provide pre-trained model and config for ResNeXt-32x8d-101-FPN?

**Comment by hellock** [comment]
64x4d performs comparable or slightly better than 32x8d, thus we adopt the former. It is unlikely that we benchmark all models on 32x8d, since it requires a large amount of resources.

**Comment by shengshiH** [comment]
> 64x4d performs comparable or slightly better than 32x8d, thus we adopt the former. It is unlikely that we benchmark all models on 32x8d, since it requires a large amount of resources.

Thank you for your reply. I notice that when 64x4d was used as a backbone, 2x is usually worse than 1x. Does 20e work better in Retinanet and Faster RCNN?

**Comment by hellock** [comment]
Yes it is observed in many codebases. 2x is not necessarily higher than 1x, which is related to models, datasets, etc.
We have not tried ResNeXt-101 with the 20e schedule.
