### ISSUE TITLE
Question about CocoDataset

### ISSUE THREAD

**Issue by Viczyf** [open-mmlab/mmdetection#2481]
As defined in coco.py, gt_bboxes'num may be different for images in a batch. Why no errors happen in in collecting step of data_loader?
根据coco.py中的定义，每张图可能有不同数量的gt_bbox, 在data_loader聚合的时候为什么没有错误发生。

**Comment by PanJianning** [comment]
[formating.py#L129](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/formating.py#L129)

**Comment by hellock** [comment]
As @PanJianning replied, we use [DataContainer](https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/data_container.py#L19) to handle such cases. It is flexible to gather tensors and objects.
