### ISSUE TITLE
Mask R-CNN test result in cityscapes 

### ISSUE THREAD

**Issue by BloomBabe** [open-mmlab/mmdetection#2485]
Hello, I trained Mask R-CNN FPN ResNet50 on cityscapes dataset with lr=0.01/3 for 59 000 iterations and lr=0.001/3 for 17 700 iterations for 1 gpu and got AP=33.5826, but with original config, result is AP=32.0, I want to use these results in my student work, but I don’t know how to explain such a large increase in the result
![image](https://user-images.githubusercontent.com/43008190/79700061-e4e55d00-829b-11ea-9452-f83c419d319c.png)

**Comment by xvjiarui** [comment]
Hi @BloomBabe 
The cityscapes dataset is relatively small and we didn't tune every hyperparameter. It is reasonable that your setting may achieve better performance.

**Comment by BloomBabe** [comment]
Are there any principles for setting hyperparameters, or is the final result more a success?

**Comment by xvjiarui** [comment]
We use the same lr for cityscapes and coco. The hyperparameters on cityscapes may not be optimal since cityscapes is relatively small.
