### ISSUE TITLE
About publishing model to cloud

### ISSUE THREAD

**Issue by flyfj** [open-mmlab/mmdetection#2493]
The getting started doc has a section about publish model and how to convert to cpu tensor. But how to actually use it? When I was trying to run inference on the converted model after specifying using cpu as device, it fails. Anyone managed to make it work? Thank you

**Comment by hellock** [comment]
This script is used for sharing your models with others. It will compress your checkpoint size by removing unnecessary fields. It is irrelevant to the inference device.
For CPU inference, please refer to #2385.

**Comment by flyfj** [comment]
> This script is used for sharing your models with others. It will compress your checkpoint size by removing unnecessary fields. It is irrelevant to the inference device.
> For CPU inference, please refer to #2385.

Thank you for your reply.
