### ISSUE TITLE
How to get  loss on validation via tool/test.py?

### ISSUE THREAD

**Issue by tiltgod** [open-mmlab/mmdetection#2496]

**Comment by tiltgod** [comment]
Can I modify mmdetection/mmdet/apis/test.py
by 
result = model(return_loss=False, rescale=not show, **data)
as
result = model(return_loss=True, rescale=not show, **data)

**Comment by tiltgod** [comment]
@hellock because I can't validate in non-distribute mode so I use tool/test.py for validating every epoch. I need to plot loss curve on both training and validation set.

**Comment by hellock** [comment]
The latest version should already supported validating during training for both non-distributed and distributed mode.
