### ISSUE TITLE
DCN offset order

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#2504]
Hi there, thanks for making this great toolbox. 

I have a question about the offset order in the deform_conv.py

Say, the network outputs an offset map of size (N, 2, H, W) and inputs it to the DeformConv(feature_map, offset). The DeformConv thinks the **x offset is offset[:, 0, :, :] or offset[:, 1, :, :]** (here x indicates the horizontal axis)? 

Thank you.

**Comment by hellock** [comment]
The order should be (y, x). @xvjiarui Please confirm that.

**Comment by xvjiarui** [comment]
Hi @hyz-xmaster , offset[:, 0, :, :] corresponds to H, offset[:, 1, :, :] corresponds to W. In other words ,the order is (y, x),

**Comment by hyz-xmaster** [comment]
Got it, thank you.
