### ISSUE TITLE
Getting Error: Probably not able to access host gpu via docker container 

### ISSUE THREAD

**Issue by gurjeetseh** [open-mmlab/mmdetection#2508]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I installed the docker using the given dockerfile and running using command like this:

docker run -ti --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm --rm --ipc=host -it --mount type=bind,source=/home/liberty/Documents/mmdetection/data,target=/mmdetection/data mmdetection:latest /bin/bash

I am getting errors in test scripts. I think issue might be accessing the gpu in docker container. My gpu is working fine on host machine. Please let me know if there are specific way I have to run docker with gpu or if there are instructions I can follow so docker can communicate with host gpu.

**Reproduction**
1. What command or script did you run?
```
python tools/test.py configs/faster_rcnn_r50_fpn_1x.py     checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth     --show

python demo/webcam_demo.py configs/faster_rcnn_r50_fpn_1x.py  checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

No, I didn't make any modification 
3. What dataset did you use?
COCO dataset

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

sys.platform: linux
Python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
CUDA available: False
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.3.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.1a0+d94043a
OpenCV: 4.2.0
MMCV: 0.4.3
MMDetection: 1.1.0+a1c3aa4
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

Used the dockerfile

**Error traceback**
If applicable, paste the error trackback here.
```
root@86bb41c47f9b:/mmdetection# python demo/webcam_demo.py configs/faster_rcnn_r50_fpn_1x.py \
>     checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
/mmdetection/mmdet/apis/inference.py:40: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Traceback (most recent call last):
  File "demo/webcam_demo.py", line 44, in <module>
    main()
  File "demo/webcam_demo.py", line 26, in main
    args.config, args.checkpoint, device=torch.device('cuda', args.device))
  File "/mmdetection/mmdet/apis/inference.py", line 44, in init_detector
    model.to(device)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 426, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 202, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 424, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 102, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx


root@86bb41c47f9b:/mmdetection# python tools/test.py configs/faster_rcnn_r50_fpn_1x.py     checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth     --show
loading annotations into memory...
Done (t=0.39s)
creating index...
index created!
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 170, in <module>
    main()
  File "tools/test.py", line 148, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "/mmdetection/mmdet/apis/test.py", line 19, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 140, in forward
    return self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 149, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 130, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 303, in simple_test
    self.test_cfg.rpn)
  File "/mmdetection/mmdet/models/detectors/test_mixins.py", line 34, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 265, in get_bboxes
    for img_id in range(len(img_metas)):
TypeError: object of type 'DataContainer' has no len()


```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
You may refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/install.html#another-option-docker-image) and installation of [nvidia-docker](https://github.com/NVIDIA/nvidia-docker#quickstart). Docker 19.03 above is required.

**Comment by ika-musuko** [comment]
> You may refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/install.html#another-option-docker-image) and installation of [nvidia-docker](https://github.com/NVIDIA/nvidia-docker#quickstart). Docker 19.03+ is required.

Documentation link should be updated to: https://mmdetection.readthedocs.io/en/latest/get_started.html?highlight=docker#use-mmdetection-with-docker
