### ISSUE TITLE
about class_agnostic parameter in mask rcnn and htc

### ISSUE THREAD

**Issue by Shi-Xiaoyu** [open-mmlab/mmdetection#2510]
Hi. I remember in the Mask R-CNN paper, the author emphasized that they use a class-agnostic mask head to predict masks. But in your implementation of Mask R-CNN, class_agnostic = False. What's more, in your HTC, bbox regression is set to be class-agnostic while mask head remains class-specific. Did I miss any thing or you have a preference regarding this point?

**Comment by hellock** [comment]
Just because the official code of Mask R-CNN adopts class-dependent mask predictions.
