### ISSUE TITLE
nms_cuda.nms mistakenly call nms_cpu during testing with error: RuntimeError: !dets.type().is_cuda() INTERNAL ASSERT FAILED at mmdet/ops/nms/src/nms_cpu.cpp:7

### ISSUE THREAD

**Issue by Liu0329** [open-mmlab/mmdetection#2512]
---
name: Error report
about: Create a report to help us improve
title: nms_cuda.nms mistakenly call nms_cpu during testing 
labels: ''
assignees: xvjiarui

---

Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
nms_cuda.nms mistakenly call nms_cpu.cpython-36m-x86_64-linux-gnu.so during testing.
The error is strange that I have checked the input dets_th is a cuda tensor, but trigger the assertion in nms_cpu.cpp. Training is OK, but testing has this error.

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=0 python3 tools/test.py configs/faster_rcnn_r50_fpn_carafe_1x.py \
./work_dirs/faster_rcnn_r50_fpn_carafe_1x/epoch_55.pth --eval bbox --out output/out.pkl
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes. Only debug code and config changes
3. What dataset did you use?
My own dataset

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3,4,5,6,7: TITAN V
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.5
    - Built with CuDNN 7.6
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/conda-bld/pytorch_1584364664130/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1584364664130/work=/usr/local/src/conda/pytorch-1.4.0 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1584364664130/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.5.0+cu100
OpenCV: 4.1.0
MMCV: 0.4.4
MMDetection: 1.1.0+unknown
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
       conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
       $PATH /usr/local/go/bin:/home/username/miniconda3/bin:/home/username/miniconda3/condabin:/home/username/miniconda3/bin:/usr/local/cuda10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       $LD_LIBRARY_PATH
        /usr/local/cuda10.0/lib64
       $PYTHONPATH
       empty

**Error traceback**
If applicable, paste the error trackback here.
```
File "/home/code/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 56, in nms
    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: !dets.type().is_cuda() INTERNAL ASSERT FAILED at mmdet/ops/nms/src/nms_cpu.cpp:7, please report a bug to PyTorch. dets must be a CPU tensor (nms_cpu_kernel at mmdet/ops/nms/src/nms_cpu.cpp:7)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7fe1086a32ad in /home/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: at::Tensor nms_cpu_kernel<float>(at::Tensor const&, float) + 0x9c7 (0x7fe0f719a847 in /home/code/mmdetection/mmdet/ops/nms/nms_cpu.cpython-36m-x86_64-linux-gnu.so)
frame #2: nms(at::Tensor const&, float) + 0x392 (0x7fe0f7186892 in /home/code/mmdetection/mmdet/ops/nms/nms_cpu.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x4ae91 (0x7fe047455e91 in /home/code/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x48b0b (0x7fe047453b0b in /home/code/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Liu0329** [comment]
@hellock sorry to bother, but someone also encounter it and cannot solve it directly.
https://github.com/pytorch/pytorch/issues/36506

**Comment by xvjiarui** [comment]
@Liu0329 
Hi, have you modified the code? From your stdout L56 calls `nms_cuda` while from here https://github.com/open-mmlab/mmdetection/blob/245276124857c278bdbd6790becc5a008156e33b/mmdet/ops/nms/nms_wrapper.py#L56 `nms_cpu` is called. 
You may use the [error-template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) if the debug still exits.

**Comment by Liu0329** [comment]
> @Liu0329
> Hi, have you modified the code? From your stdout L56 calls `nms_cuda` while from here
> 
> https://github.com/open-mmlab/mmdetection/blob/245276124857c278bdbd6790becc5a008156e33b/mmdet/ops/nms/nms_wrapper.py#L56
> 
> `nms_cpu` is called.
> You may use the [error-template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) if the debug still exits.

No. Line numbers are changed because I only added 'pdb' stuff to debug. 
I wil use the error-template.

**Comment by Liu0329** [comment]
@xvjiarui updated. Pls take a look.

**Comment by xvjiarui** [comment]
Hi @Liu0329 
I just tried with the latest code in the master branch. I could not reproduce your error. Could you please try to merge the latest master to see if the bug still exists?

**Comment by Liu0329** [comment]
@xvjiarui I did use the latest master code.

**Comment by xvjiarui** [comment]
Hi @Liu0329 
I did try the latest master code. It works fine. Did you modify the `setup.py` before? I suggest you to remove the folder and clone again to see if the bug still exists.

**Comment by sxfduter** [comment]
I encountered the same problem as you. Have you solved this problem?

**Comment by TrinhDinhPhuc** [comment]
just use `dets_th.cpu()` to convert from Torch.Tensor to cpu
