### ISSUE TITLE
what are the best suitable hyperparameters such as num_pre, nms_post, max_num, score_thr nms Iou_thr

### ISSUE THREAD

**Issue by jacky99** [open-mmlab/mmdetection#2519]
When trained on other datasets(not coco), the final result seems very sensitive to  these hyper parameters.
Take num_pre, max_num,max_per_img as example, if I change these parameters from 200 to 500,2000, ap and recall changes a lot.
In the dense object prediction, the final results also rely on nms_pre, max_num and max_per_img.
And in faster rcnn, the default score_thr is set to 0.05, but in ga model, the the default score_thr is set to 1e-3,
So how can we fairly compare different models' performance if performance depends a lot on these hyperparameters.
Can we get the best result by tuning these parameters

**Comment by hellock** [comment]
There are no definite answer for that. The best hyper-parameters can be very different for different models, datasets, etc. The tuning relies on your experience and understanding to the task.
Different from other hyper-parameters, lower `score_thr` usually brings higher mAP, which is certain.
