### ISSUE TITLE
Increased memory use in v2.0

### ISSUE THREAD

**Issue by melikovk** [open-mmlab/mmdetection#2522]
I have tried to train a model using v2.0 branch and see a significantly higher memory use. I am training retinanet_r50_fpn model with 1 channel input and 1 class output on my custom dataset. With the version 1.4 training with 4 images per GPU (800x800) consumed upto  6.2 Gb of memory. With v2.0 I run out of 8Gb memory if I attempt 4 images per GPU and 2 images per GPU consume about 5.4 Gb. Is this expected?

**Comment by yhcao6** [comment]
Indeed we found the memory usage of most models increases in v2.0, but the gap is not as large as yours. For Retinanet R50, memory usage increases from 3.6 to 3.8.
I have not tested inputs with 1 channel and output with 1 class, high memory usage may be also related to your change to the code.

**Comment by melikovk** [comment]
Thank you. I did not change the models, only the dataset and image pipeline is different. One feature of my dataset is that it has many objects per image - can this be a reason for relatively large difference I see, since I think you made extensive changes in the anchor heads?

**Comment by yhcao6** [comment]
It may be the reason leads to large memory usage. Optimizing memory usage is in our plan, it is also welcome to help us find where the problem is.

**Comment by melikovk** [comment]
Thank you. I will try to explore it.
