### ISSUE TITLE
How to save the full model(including model structure) rather than only state_dict?

### ISSUE THREAD

**Issue by feiyangsuo** [open-mmlab/mmdetection#2526]
Used `torch.load()` to load the checkpoint file in work_dir, getting a dict with only three keys: `meta`, `state_dict` and `optimizer`. So is the model structure saved? Or should I specify mmdet to save it?

**Comment by xvjiarui** [comment]
Hi @feiyangsuo 
The model weight is saved in `state_dict`. The structure is not saved.

**Comment by feiyangsuo** [comment]
> Hi @feiyangsuo
> The model weight is saved in `state_dict`. The structure is not saved.

Thank you. BTW, Is there any way to save the structured model?

**Comment by hellock** [comment]
You can use pickle to dump the model, although not recommended.
