### ISSUE TITLE
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/**/Download/mmdetection/mmdet/apis/__init__.py)

### ISSUE THREAD

**Issue by laridzhang** [open-mmlab/mmdetection#2527]
**Describe the bug**
After the installation, i import `mmdet` from another Python script and it raise an ImportError like this.
```
ImportError: cannot import name 'init_dist' from 'mmdet.apis' (/home/**/Download/mmdetection/mmdet/apis/__init__.py)
```
**Reproduction**
1. What command or script did you run?
```
from mmdet.apis import init_dist
```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
```
TorchVision: 0.4.0a0
OpenCV: 4.2.0
MMCV: 0.4.4
MMDetection: 1.1.0+unknown
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.0
```

**Comment by mincwin** [comment]
the extra info: 
  I clone the project [https://github.com/hdjang/Feature-Selective-Anchor-Free-Module-for-Single-Shot-Object-Detection](url) witch based on the mmdetection .  
  running  the command: python /tools/test.py  then appear the error.
  Its very important for me. I really need your help

**Comment by hellock** [comment]
The version you were using is quite old. You can change it to `from  mmcv.runner import init_dist`.

**Comment by aliman80** [comment]
ImportError: cannot import name 'init_dist' from 'mmdet.apis' hi i am trying to run zeroshot detection code and from git hub and getting this eror.
The version you were using is quite old. You can change it to from mmcv.runner import init_dist.  Can you tell me where should i change this ?

**Comment by hanquansanren** [comment]
> ImportError: cannot import name 'init_dist' from 'mmdet.apis' hi i am trying to run zeroshot detection code and from git hub and getting this eror. The version you were using is quite old. You can change it to from mmcv.runner import init_dist. Can you tell me where should i change this ?

hello, you can add this code in tools/test.py

**Comment by CoffeeinTeaC** [comment]
I meet a problem such as     from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
ImportError: cannot import name 'get_root_logger' from 'mmdet.apis' (/home/cyg/mmdetection/mmdet/apis/__init__.py).I do not know how to deal with it.who can help me?
