### ISSUE TITLE
HELP！！！ImportError: /home/z。。/。。/PyTorch_Test/src/mmdetection/mmdet/ops/roi_align/roi_align_cuda.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by Wang-zuozheng** [open-mmlab/mmdetection#2528]
Idon't know what is this mean.how to dealwith it?If you can help me ,thank you so much!!!!!!!!!!!!

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by Wang-zuozheng** [comment]
Thank you for replying me.But I still have a question, where is the Error report?Is that a document in the github? thank you so much!

**Comment by hellock** [comment]
When you click `New issue` to open a new issue, please select the `Error report`.
