### ISSUE TITLE
How to use big dataset train mask rcnn without mask and use small dataset train mask rcnn with mask

### ISSUE THREAD

**Issue by JKingKong** [open-mmlab/mmdetection#2533]
**My purpose:**
1. I want to use a big dataset train  Mask R-CNN **without mask**
2. And the **use 1 step get model** to use small dataset train Mask R-CNN **with mask** 

**I have looked those solution:**
[#102](https://github.com/open-mmlab/mmdetection/issues/102)
[#1480](https://github.com/open-mmlab/mmdetection/issues/1480)
I  know that **mask R-CNN without mask is Faster R-CNN.**

Please help me，thank you.

**Comment by xvjiarui** [comment]
Hi @JKingKong 
You could complete step 1 by train the Faster R-CNN directly by using Faster R-CNN config.
After that, you could train a Mask R-CNN by set `load_from=/PATH/TO/CHECK_POINT` in your Mask R-CNN config file. 
You would see the warning that mask head weights are missing after loading. But it should be your use case, right?

**Comment by JKingKong** [comment]
> Hi @JKingKong
> You could complete step 1 by train the Faster R-CNN directly by using Faster R-CNN config.
> After that, you could train a Mask R-CNN by set `load_from=/PATH/TO/CHECK_POINT` in your Mask R-CNN config file.
> You would see the warning that mask head weights are missing after loading. But it should be your use case, right?

Thank you for your help.
**But，it raise a exception:**

missing keys in source state_dict: mask_head.convs.0.conv.weight, mask_head.convs.0.conv.bias, mask_head.convs.1.conv.weight, mask_head.convs.1.conv.bias, mask_head.convs.2.conv.weight, mask_head.convs.2.conv.bias, mask_head.convs.3.conv.weight, mask_head.convs.3.conv.bias, mask_head.upsample.weight, mask_head.upsample.bias, mask_head.conv_logits.weight, mask_head.conv_logits.bias

Traceback (most recent call last):
  File "tools/train.py", line 151, in <module>
    main()
  File "tools/train.py", line 147, in main
    meta=meta)
  File "/content/mmdetection/mmdet/apis/train.py", line 162, in train_detector
    runner.resume(cfg.resume_from)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 329, in resume
    self.optimizer.load_state_dict(checkpoint['optimizer'])
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/optimizer.py", line 116, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by xvjiarui** [comment]
You may use `tools/publish_model` to remove unnecessary fields in the checkpoint.

**Comment by JKingKong** [comment]
> You may use `tools/publish_model` to remove unnecessary fields in the checkpoint.

Thank you，it works successfully.
