### ISSUE TITLE
albumentation: cv2.cvtColor error

### ISSUE THREAD

**Issue by Bai426** [open-mmlab/mmdetection#2535]
Thanks for your error report and we appreciate it a lot.
When I used Albumentation to augment my data, the function cv2.cvtColor is incorrect, so there is problem, I adjusted like this according to official guideline on how to use cv2.cvtColor.
1. The original one in line 39 of normalize.py:
    **cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)   # inplace**
2. The revised one:
    **img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)** 
    Then it can work.
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Hi @Bai426 ,
Thanks for your bug report, would you like to create a PR to fix it?

**Comment by Bai426** [comment]
Oh, I think it's a little bug, so I just want to report, there is no need to create a PR. Thank you!


________________________________

**Comment by ZwwWayne** [comment]
Hi @Bai426 ，
Ok, I see. Then could you create an Issue in Albumentation? Because the bug seems in their codebase.

**Comment by Bai426** [comment]
Yes, I can. Thank you!
________________________________

**Comment by ZwwWayne** [comment]
Thanks very much.
