### ISSUE TITLE
Why not broadcast buffers?

### ISSUE THREAD

**Issue by nnop** [open-mmlab/mmdetection#2539]
https://github.com/open-mmlab/mmdetection/blob/8732ed96a85163fc4fb6d36b52ff3c3d25172611/tools/test.py#L153

`broadcast_buffers=False` makes BN buffers different on each GPU. Why not set to `True`?

**Comment by hellock** [comment]
- The initial buffers are the same for each device if a pretrained checkpoint is provided.
- It is a common practice that `broadcast_buffers` is set to False for distributed training. If you care about it, SyncBN will sync running mean and var among devices.
