### ISSUE TITLE
Is there a way to use a model trained by mmdet in an environment without mmedt?

### ISSUE THREAD

**Issue by feiyangsuo** [open-mmlab/mmdetection#2545]
Just for inference. 
I've tried `torch.save()` the model. But when trying to load the model(In an environment with torch but without mmdet), pickle reported "no module named mmdet" as excuting `torch.load()`.

**Comment by hellock** [comment]
It is impossible to use pickle to do that. You need a deployment runtime which is non-trivial. PyTorch -> Caffe/ONNX -> TensorRT is a common way, but you may need to support it by yourself.
