### ISSUE TITLE
RepPoints page weights link - Access denied

### ISSUE THREAD

**Issue by nikitaverbis** [open-mmlab/mmdetection#2546]
**Problem description**
At [RepPoints page](https://github.com/open-mmlab/mmdetection/tree/master/configs/reppoints) in table row: 
RepPoints | R-50-FPN | N | none | moment | 1x | 36.8 | [Link](https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/models/reppoints/reppoints_moment_r50_no_gn_fpn_1x-66db098e.pth)

Weights "Link" is not correct - "AccessDenied".

Image:
![error](https://user-images.githubusercontent.com/21986402/80314283-3e4c0f80-87f9-11ea-809c-d1f05a211dde.PNG)

**Comment by yhcao6** [comment]
In the latest version, we have update the model zoo of Reppoints. Please recheck that.
