### ISSUE TITLE
My train dataset is not loaded all images when train the model.

### ISSUE THREAD

**Issue by JKingKong** [open-mmlab/mmdetection#2549]
**My dataset details:**
1. images shape： <= (1333,800)
2. total images quantity：146

**Question:**
**The command line show:**
2020-04-27 03:19:12,390 - mmdet - INFO - Epoch [1][50/**73**]	

**It just loads 73 images，but my dataset is 146 images.**

What happens on loading images?
Please help me，Thanks.

**Comment by PanJianning** [comment]
Do you set `imgs_per_gpu=2` ?

**Comment by JKingKong** [comment]
> Do you set `imgs_per_gpu=2` ?

Yes，I set imgs_per_gpu=2.

**Comment by PanJianning** [comment]
Your batch_size is 2. `73 * 2 = 146`. Nothing wrong.

**Comment by JKingKong** [comment]
> Your batch_size is 2. `73 * 2 = 146`. Nothing wrong.

Thank you.
Now，I know the `imgs_per_gpu` is batch_size.

**Comment by Yukinoyuki1** [comment]
> Your batch_size is 2. 73 * 2 = 146. Nothing wrong.

I also set imgs_per_gpu=2. But I have 3001 images, and it only loaded 1157...

**Comment by PanJianning** [comment]
> > Your batch_size is 2. 73 * 2 = 146. Nothing wrong.
> 
> I also set imgs_per_gpu=2. But I have 3001 images, and it only loaded 1157...

Do you have any background images(i.e. images without gt bboxes) in your dataset? Background  images are filtered by default.
