### ISSUE TITLE
Do you have any plan for sync bn?

### ISSUE THREAD

**Issue by shaoqb** [open-mmlab/mmdetection#255]

**Comment by hellock** [comment]
Yes it is in our release plan, but not of high priority.

**Comment by shaoqb** [comment]
thanks for your reply!

**Comment by RainHxj** [comment]
@hellock 

Do you mind describe the detail of using sync BN? I want to implement it . but when  I  use Sync BN instead of all BN( frozen BN) on the backbone, I cannot get better peformance.
