### ISSUE TITLE
weights in model zoo doesn't work in branch v2.0

### ISSUE THREAD

**Issue by charlesyann** [open-mmlab/mmdetection#2551]
When I run code like blow:
python tools/test.py configs/ssd/ssd300_coco.py checkpoints/ssd300_coco_vgg16_caffe_120e_20181221-84d7110b.pth --show

but I got a lot of wrong bboxes on the image

**Comment by ZwwWayne** [comment]
Hi @charlesyann ,
Due to the BC-breaking changes in V2.0,  the models trained in V1.x need to be converted to use V2.0 codebase, and the accuracy will drop a bit. This PR https://github.com/open-mmlab/mmdetection/pull/2529 may help you.

**Comment by charlesyann** [comment]
@ZwwWayne the scripts works with faster rcnn,  but ssd still doesn't work.

**Comment by hellock** [comment]
You may use the checkpoints from v2.0 model zoo which we re-benchmarked.

**Comment by charlesyann** [comment]
> You may use the checkpoints from v2.0 model zoo which we re-benchmarked.

Nice, is that v2.0 model zoo available now or in a few days ?

**Comment by ZwwWayne** [comment]
It will be available in a few days.
