### ISSUE TITLE
Question about the coco_error_analysis.py

### ISSUE THREAD

**Issue by tonysy** [open-mmlab/mmdetection#2554]
Hi, I'm curious about the meaning of Loc, Sim, Oth of types = ['C75', 'C50', 'Loc', 'Sim', 'Oth', 'BG', 'FN'].

Anyone can give some intuitive introduction of the figure generated from the coco_error_analysis.

Thanks in advance.
![image](https://user-images.githubusercontent.com/7881589/80379631-ee407c00-88d0-11ea-9fbf-f82e3aaca8c5.png)

**Comment by hellock** [comment]
You can refer to http://cocodataset.org/#detection-eval.

**Comment by tonysy** [comment]
Thanks, it helps me a lot!
