### ISSUE TITLE
ATSS training with negative samples

### ISSUE THREAD

**Issue by edwardyangxin** [open-mmlab/mmdetection#2555]
When I do atss training with nagetive samples, I get all bbox_loss and centerness_loss as nan. If I remove all negative sample, it seems ok.
![image](https://user-images.githubusercontent.com/13101725/80442382-5b8af600-893f-11ea-91f1-c94c19830c27.png)

Does atss not support negative samples?

**Comment by vinceyzw** [comment]
请问你解决了吗？我也一直nan的问题 @edwardyangxin

**Comment by ZwwWayne** [comment]
ATSS supports negative samples in the newest version of MMDetection. So this issue is closed. Feel free to create a new issue following the `error template` with detailed information if you meet a similar problem in the newest master.
