### ISSUE TITLE
why comparison between BN and GN in ResNext, GN get a great drop in map? 

### ISSUE THREAD

**Issue by TangShengqin** [open-mmlab/mmdetection#2561]
faster rcnn with ResNext, using GN:  
![image](https://user-images.githubusercontent.com/27995341/80514048-8f533380-89b2-11ea-9e98-34a0f973a019.png)

X-50-32x4d-FPN | pytorch | GN | 1x | 36.5
X-101-32x4d-FPN | pytorch | GN | 1x | 33.2

faster rcnn with ResNext, using BN:
![image](https://user-images.githubusercontent.com/27995341/80514210-c88ba380-89b2-11ea-9a11-16b89c980865.png)

X-101-32x4d-FPN | pytorch | 1x | BN| 40.1
X-101-64x4d-FPN | pytorch | 1x | BN| 41.3

**Comment by hellock** [comment]
ResNeXt has groups in its conv, applying the same setting of ResNet to ResNeXt may not be good. This drop is also reported in the official repo of GN.

**Comment by TangShengqin** [comment]
thanks for your reply, i get it！
