### ISSUE TITLE
How to install mmdetection on pp64cle(IBM POWER8)?    

### ISSUE THREAD

**Issue by Bryce1010** [open-mmlab/mmdetection#2573]
**Describe the bug**

I follow the install method, and the error happens: 

```bash
Installed /opt/anaconda/envs/wmlce/lib/python3.7/site-packages/mmcv-0.4.4-py3.7-linux-ppc64le.egg
Searching for opencv-python>=3
Reading https://pypi.org/simple/opencv-python/
No local packages or working download links found for opencv-python>=3
error: Could not find suitable distribution for Requirement.parse('opencv-python>=3')

```

**Environment**
```bash
Linux version 4.15.0-76-generic (buildd@bos02-ppc64el-028) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #86-Ubuntu SMP Fri Jan 17 17:24:13 UTC 2020

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

PyTorch 1.3.1

```
![image](https://user-images.githubusercontent.com/30361513/80776311-af424d00-8b94-11ea-8d2e-32a7ac40e57e.png)

**Comment by hellock** [comment]
The reason is the lack of `opencv-python`, which may not support pp64cle. you may install opencv and the python api in other ways.

**Comment by Bryce1010** [comment]
Thanks for your answer. 
I have searched for some time, but I can't  find a good solution for this problem.  
Can you share one?

**Comment by hellock** [comment]
Sorry that we do not have a power8 server, and cannot provide further help.
