### ISSUE TITLE
Tools like grad cam

### ISSUE THREAD

**Issue by NicholasIrving** [open-mmlab/mmdetection#2574]
Are there any tools similar to grad cam or something to visualize the heat map?

**Comment by hellock** [comment]
Currently not. Community contribution is welcome.

**Comment by cszer** [comment]
Ablation cam , presented at WACV 2020 and gradients don't needed

**Comment by freesunshine** [comment]
@NicholasIrving 
Did anyone implemented grad-cam to mmdetection? It is really useful.I tried with faster-rcnn,but got no clue.Any help?

**Comment by heboyong** [comment]
I have written some codes to visualize the heatmap from all stages from backbone and fpn, it works well .
If you need help, please contact me with email :heboyong@qq.com, because the codes is unofficial  and need change some oofficial codes in order to extract the original data from both backbone and fpn

**Comment by heboyong** [comment]
I write some codes to visualize the heatmap from backbone and fpn, it works well.
 https://github.com/heboyong/grad-cam-for-mmdetection
I refer to some codes online, this code is rough and not rigorous(neng yong jiu xing)

**Comment by fengqian-wei** [comment]
> I write some codes to visualize the heatmap from backbone and fpn, it works well.
> https://github.com/heboyong/grad-cam-for-mmdetection
> I refer to some codes online, this code is rough and not rigorous(neng yong jiu xing)

em..., it  randomly chooes a channel to draw heatmap. It doesn't reweight channels. (yong de bu fang xing)
I don't know how to get gradient in  inference_detector function. It is key to visualize the heat map or cam

**Comment by duzhixing** [comment]
> I write some codes to visualize the heatmap from backbone and fpn, it works well.
> https://github.com/heboyong/grad-cam-for-mmdetection
> I refer to some codes online, this code is rough and not rigorous(neng yong jiu xing)

老哥，你这个只是随机抽取一个通道的特征图打印出来， 并不是grad_cam, grad_cam 重要的不是backwards 吗

**Comment by Frank1o** [comment]
@duzhixing 请问用cam时model应该怎么选择？可以直接选rpn_head里最后一个卷积吗？

**Comment by RuoyuChen10** [comment]
I write an example with YOLO and Grad-CAM, see here: [https://github.com/RuoyuChen10/objectdetection-saliency-maps](https://github.com/RuoyuChen10/objectdetection-saliency-maps)

**Comment by jacob-kang** [comment]
머라는겨 영어로해 걍
니들만 모국어있

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/pull/7987
