### ISSUE TITLE
NasFPN 

### ISSUE THREAD

**Issue by johnlanbor** [open-mmlab/mmdetection#2579]
I found your nasfpn is unstable.
when I use your nasfpn, when stack times is 5 or 7, the performance is droped.
when I use other nasfpn which in my own codebase. the training is stable. but I add my nasfpn to your neck, the training process is unstable when stack times is 5 or 7.

so, if there any chance that your codebase have something wrong in other part, not nasfpn make the training process unstable.

still try to train other fpn, eg bifpn and dlafpn.

**Comment by johnlanbor** [comment]
I believe that the reason of your nasfpn is unstable is not because the nasfpn is unstable.
My experiment shows that your codebase is not friendly to stack fpns. eg nasfpn,bifpn,dlafpn and so on.
By the way, when stack times below 3, the training seems stable, which still got 1 point benifits.

**Comment by johnlanbor** [comment]
Maybe when stack times grows, need bigger batch size.
In my own code base, the batch size is 32(8*4).but I don't have enough V100 to do these experiment with mmdet.

**Comment by hellock** [comment]
If you reduce the batch size, the performance can drop. Stacking 7 times while keeping the batch size unchanged (8 images per gpu) should be better than 3 times on RetinaNet.
