### ISSUE TITLE
how can i get precision in voc dataset?

### ISSUE THREAD

**Issue by KDcx35** [open-mmlab/mmdetection#2580]
the result i get is like this
![image](https://user-images.githubusercontent.com/19550055/80854975-3106a900-8c6f-11ea-8f63-a64bc51e8eb8.png)
this image doesn't contain precision,so how can i get precision?

the command i use is like this:
```
!python tools/test.py configs/faster_rcnn_r50_fpn_1x.py \
    work_dirs/faster_rcnn_r50_fpn_1x/latest.pth \
    --eval mAP
```
i see other people use voc_eval.py,but i can't find it in my mmdetection
so i went online and find one,but it won't work
first,it says gt_ignore has some kind of a mistake
then when i delete gt_ignore,it says this:
```
Traceback (most recent call last):
  File "tools/voc_eval.py", line 62, in <module>
    main()
  File "tools/voc_eval.py", line 58, in main
    voc_eval(args.result, test_dataset, args.iou_thr)
  File "tools/voc_eval.py", line 43, in voc_eval
    print_summary=True)
TypeError: eval_map() got multiple values for argument 'scale_ranges'
```
so,any suggestions?Thank you!

**Comment by hellock** [comment]
The argument [`results`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/mean_ap.py#L391) contains all the information you need, including precision.

**Comment by KDcx35** [comment]
> The argument [`results`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/mean_ap.py#L391) contains all the information you need, including precision.

Could you give me a example?I don't know how to use this argument.
thank you
