### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by qgh1223** [open-mmlab/mmdetection#2582]
Why I met this problem in colaboratory?
mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
In March,there is no problem in program

**Comment by madiltalay** [comment]
What worked for me:
1. `!git clone -b v2.0 https://github.com/open-mmlab/mmdetection.git`
2. Go to mmdetection directory:
a. Open requirements.txt and remove the first line that ends with build.txt
b. Open setup.py and go to line 219 and 225 that also have build.txt and remove them
3. Go to mmdet/utils and open collect_env.py and in line 24, change it to:
`env_info['CUDA_HOME'] = '/usr/local/cuda'`
4. Finally, run:
`!python setup.py develop`

I am assuming you have mmcv and terminaltables installed. If not, then you may find this helpful:
```
import os, sys
from google.colab import drive
drive.mount('/content/gdrive')
packages_path = '/content/packages'
os.symlink('/content/gdrive/My Drive/Developer/Packages', packages_path)
sys.path.insert(0,packages_path)

!pip install --target=$packages_path mmcv
!pip install --target=$packages_path terminaltables
```

**Comment by qgh1223** [comment]
> What worked for me:
> 
> 1. `!git clone -b v2.0 https://github.com/open-mmlab/mmdetection.git`
> 2. Go to mmdetection directory:
>    a. Open requirements.txt and remove the first line that ends with build.txt
>    b. Open setup.py and go to line 219 and 225 that also have build.txt and remove them
> 3. Go to mmdet/utils and open collect_env.py and in line 24, change it to:
>    `env_info['CUDA_HOME'] = '/usr/local/cuda'`
> 4. Finally, run:
>    `!python setup.py develop`
> 
> I am assuming you have mmcv and terminaltables installed. If not, then you may find this helpful:
> 
> ```
> import os, sys
> from google.colab import drive
> drive.mount('/content/gdrive')
> packages_path = '/content/packages'
> os.symlink('/content/gdrive/My Drive/Developer/Packages', packages_path)
> sys.path.insert(0,packages_path)
> 
> !pip install --target=$packages_path mmcv
> !pip install --target=$packages_path terminaltables
> ```

I remember there are other components needed to be compiled after nms.deform_conv.Is this problem?I think it should be happened in compiling ops folder

**Comment by ZwwWayne** [comment]
This seems to be an API-compatibility issue when the old mmdet is used for PyTorch 1.5. This issue should be fixed in the newest MMDet, which supports PyTorch 1.3 - 1.5. For colab usage, you can also refer to our [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb) for installation process.

**Comment by shanudhawale** [comment]
I'm trying to replicate the environment in Google Colab:

-Installation of mmdetection -v1.0rc1 this error comes out with python setup.py develop it gives error as
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

running the high-level API results into this
ImportError: cannot import name 'deform_conv_cuda'

I'm installing my dependencies like this:
!pip install -U torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
!pip install mmcv-full
!rm -rf mmdetection
!git clone --depth 1 --branch v1.0rc1 https://github.com/open-mmlab/mmdetection.git

need help!!!!! @ZwwWayne @anurag1paul @hachreak @qgh1223
