### ISSUE TITLE
Why cannot compile nms_cuda in mmdetection?

### ISSUE THREAD

**Issue by qgh1223** [open-mmlab/mmdetection#2583]
I met thie problem in compiling mmdetection.What happened now?What lost in colaboratory?
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:262:30: note: declared here
DeprecatedTypeProperties & type() const {
^~~~
mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
#define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
^
mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
#define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
^~~~~~~~
mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
#define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
^
mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
#define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
^~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by qgh1223** [comment]
cannot use gcc 7 in mmdetction?The gcc in colaboratory now is gcc 7

**Comment by madiltalay** [comment]
[https://github.com/open-mmlab/mmdetection/issues/2582](url)

**Comment by qgh1223** [comment]
> [https://github.com/open-mmlab/mmdetection/issues/2582](url)

No results matched your search.What happened?

**Comment by qgh1223** [comment]
gcc version in sys.version 8.2.
gcc --version version 7.5.Is it normal？

**Comment by hellock** [comment]
gcc 7 is supported and tested. The cause is the pytorch version. The master branch has not supported PyTorch 1.5 yet and you may switch to the v2.0 branch.
