### ISSUE TITLE
registry.py missing in v2.0 branch

### ISSUE THREAD

**Issue by madiltalay** [open-mmlab/mmdetection#2589]
Please check

**Comment by hellock** [comment]
It is merged into `builder.py`

**Comment by madiltalay** [comment]
Sorry, I forgot mentioning the details.
The folder mmdet.utils in v2.0 has no registry.py
It leads to an error when we run:
`from mmdet.apis import set_random_seed, train_detector`


>

**Comment by hellock** [comment]
You may pull the latest v2.0 branch. `Registry` has been moved to MMCV.

**Comment by madiltalay** [comment]
Ok, got it working.
