### ISSUE TITLE
No/Little Memory Reduction for HTC when training with FP16

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmdetection#2597]
I've tried fp16 on other models and it reduces memory usage a lot but has little impact on HTC model. Should I modify somewhere to support fp16 training on HTC?

**Comment by yhcao6** [comment]
Could you show the exact number of FP32 HTC and FP16 HTC.
I just test htc_r50_fpn_1x_coco.py with 1 GPU, in the first several iterations, the memory usage of
FP32 HTC: 5724 MB
FP16 HTC: 3803 MB (Just adding `fp16 = dict(loss_scale=512.)` at the end of the config)
It seems normal.

**Comment by zehuichen123** [comment]
I rechecked the memory usage of htc on mmdet2.0 and it looks normal. Thx. The memory usage reduced from about 9000MB to 6500MB.
