### ISSUE TITLE
How to extract feature vector from the last layer?

### ISSUE THREAD

**Issue by andreqwert** [open-mmlab/mmdetection#2598]
Hi!
I need to extract feature vectors from the various images with different resolutions. To make it I tried to modify the code so [here](https://github.com/open-mmlab/mmdetection/blob/51df8a9b7ad5f25ebd75cf8e0969c3b728bde08d/mmdet/models/detectors/single_stage.py#L83) I returned not only bboxes but vector `x` also. After that I have got the pytorch tensors with different shapes for different image sizes. How can I encode that to the equal shapes?

**Comment by hellock** [comment]
Feature map shapes of different input resolutions are naturally different, thus this question is not related to the codebase itself, but more a method design and choice by yourself.

**Comment by andreqwert** [comment]
@hellock Thank you for reply! If we disregard taking different resolutions, can I assume that my method of feature vectors extraction is generally correct? If no, how can I get feature vector for any resolution?

**Comment by hellock** [comment]
If you use the same resolution, you can just take the output feature map of backbone as your feature vector, see the [x](https://github.com/open-mmlab/mmdetection/blob/51df8a9b7ad5f25ebd75cf8e0969c3b728bde08d/mmdet/models/detectors/single_stage.py#L75) here.

**Comment by andreqwert** [comment]
@hellock thanks!
