### ISSUE TITLE
bug in ssd_head.py

### ISSUE THREAD

**Issue by bigpo** [open-mmlab/mmdetection#260]
I think this [line](https://github.com/open-mmlab/mmdetection/blob/432c33206465d2526b097c28de57aad48090b1b7/mmdet/models/anchor_heads/ssd_head.py#L147) should be `label_channels` @hellock

**Comment by yhcao6** [comment]
I cannot find variable `label_channels`, do you mean we should rename `cls_out_channels` to `label_channels`?

**Comment by bigpo** [comment]
> I cannot find variable `label_channels`, do you mean we should rename `cls_out_channels` to `label_channels`?

yes, because the function `anchor_target` defined in `mmdet/core/anchor/anchor_target.py` has keyword parameter `label_channels=` , see this [line](https://github.com/open-mmlab/mmdetection/blob/432c33206465d2526b097c28de57aad48090b1b7/mmdet/core/anchor/anchor_target.py#L15)

**Comment by hellock** [comment]
It is a bug. Thanks for reporting!
