### ISSUE TITLE
When i run one task twice by dist_train , the error appears: RuntimeError: Address already in use at /data1/bryanleoliu/pytorch/torch/lib/THD/process_group/General.cpp:17 how to deal with it 

### ISSUE THREAD

**Issue by hitlxm** [open-mmlab/mmdetection#261]

**Comment by hitlxm** [comment]
but i got another error AssertionError: got unexpected keyword arguments: port

**Comment by hellock** [comment]
Emm, you can modify `tools/dist_train.sh` to be `$PYTHON -m torch.distributed.launch --nproc_per_node=$2 --master_port xxxx $(dirname "$0")/train.py $1 --launcher pytorch ${@:3}` instead of updating config files.

**Comment by hitlxm** [comment]
ok  thanks

**Comment by chenxu93** [comment]
@hellock How to assigngpus 2,3 if I have 0,1,2,3 total four gpus?

**Comment by hellock** [comment]
`CUDA_VISIBLE_DEVICES=2,3`
