### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by interestingzhuo** [open-mmlab/mmdetection#2627]
when I run "python tools/test.py configs/faster_rcnn_r50_fpn_1x.py     checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth" there are some errors
Traceback (most recent call last):
  File "tools/test.py", line 8, in <module>
    from tools.fuse_conv_bn import fuse_module
  File "/mnt/WXRG0349/zhuoli/mmdetection/tools/fuse_conv_bn.py", line 7, in <module>
    from mmdet.apis import init_detector
  File "/mnt/WXRG0349/zhuoli/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/mnt/WXRG0349/zhuoli/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/mnt/WXRG0349/zhuoli/mmdetection/mmdet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/mnt/WXRG0349/zhuoli/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/mnt/WXRG0349/zhuoli/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/mnt/WXRG0349/zhuoli/mmdetection/mmdet/ops/__init__.py", line 19, in <module>
    from .utils import get_compiler_version, get_compiling_cuda_version
  File "/mnt/WXRG0349/zhuoli/mmdetection/mmdet/ops/utils/__init__.py", line 2, in <module>
    from .compiling_info import get_compiler_version, get_compiling_cuda_version
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Environment**
pytorch1.4.0+python3.7.0
use "pip" install the pytorch

**Comment by edwardyangxin** [comment]
I meet same error here, how did you solve it?

**Comment by interestingzhuo** [comment]
> I meet same error here, how did you solve it?

I haven't solve this problem.

**Comment by hellock** [comment]
Did you install CUDA correctly?

**Comment by interestingzhuo** [comment]
> Did you install CUDA correctly?

yes. when I run torch.cuda.is_available() it returns True

**Comment by pansiyuan123** [comment]
Traceback (most recent call last):
  File "../mmdetection/tools/test.py", line 9, in <module>
    from tools.fuse_conv_bn import fuse_module
  File "/home/pansiyuan/mmdetection/tools/fuse_conv_bn.py", line 7, in <module>
    from mmdet.apis import init_detector
  File "/home/pansiyuan/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/pansiyuan/mmdetection/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/pansiyuan/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/pansiyuan/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BitmapMasks, PolygonMasks
  File "/home/pansiyuan/mmdetection/mmdet/core/mask/structures.py", line 8, in <module>
    from mmdet.ops.roi_align import roi_align
  File "/home/pansiyuan/mmdetection/mmdet/ops/__init__.py", line 3, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/pansiyuan/mmdetection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/pansiyuan/mmdetection/mmdet/ops/dcn/deform_conv.py", line 12, in <module>
    from . import deform_conv_ext
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by grayson-hilliard** [comment]
also seeing this issue when importing `init_detector` with a valid CUDA environment

**Comment by ZwwWayne** [comment]
Hi @grayson-hilliard, @pansiyuan123 , @interestingzhuo ,
Can you first try to import torch and do some operation to see whether your PyTorch is installed correctly and works well? Meanwhile, you can also try to use conda to install PyTorch and see whether the bug still exists.

**Comment by infinite013** [comment]
> Hi @grayson-hilliard, @pansiyuan123 , @interestingzhuo ,
> Can you first try to import torch and do some operation to see whether your PyTorch is installed correctly and works well? Meanwhile, you can also try to use conda to install PyTorch and see whether the bug still exists.

there's still the same problem

**Comment by ZwwWayne** [comment]
Could you try to run https://github.com/open-mmlab/mmdetection/blob/master/mmdet/utils/collect_env.py and post your results in this issue?

**Comment by dmy1997** [comment]
I also meet the problem. I use pytorch 1.4.0+cuda 10.0

**Comment by infinite013** [comment]
> I also meet the problem. I use pytorch 1.4.0+cuda 10.0

well i've solved this problem by recompile mmdetection。Maybe you could try
pytorch1.4 and cuda 10.0

**Comment by dmy1997** [comment]
> > I also meet the problem. I use pytorch 1.4.0+cuda 10.0
> 
> well i've solved this problem by recompile mmdetection。Maybe you could try。
> i use pytorch1.4 and cuda 10.0

Hi !  What does ''recompile mmdetection'' mean? Do that in install.md again? Thank you! 
(My cuda is  the image: nvidia/cuda         10.0-cudnn7-devel)

**Comment by grayson-hilliard** [comment]
> Could you try to run https://github.com/open-mmlab/mmdetection/blob/master/mmdet/utils/collect_env.py and post your results in this issue?

I'm using mdmet==v1.0rc1 and these are the results of the "backported" `collect_env.py` script:

```
> python ./mmdet/utils/collect_env.py 
Traceback (most recent call last):
  File "./mmdet/utils/collect_env.py", line 62, in <module>
    for name, val in collect_env().items():
  File "./mmdet/utils/collect_env.py", line 55, in collect_env
    from mmdet.ops import get_compiler_version, get_compiling_cuda_version
  File "./mmdet/ops/__init__.py", line 7, in <module>
    from .nms import nms, soft_nms
  File "./mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "./mmdet/ops/nms/nms_wrapper.py", line 4, in <module>
    from . import nms_cpu, nms_cuda
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
```

I commented out the `mmdet` import + subsequent calls and re-ran, here are the results:

```
> python ./mmdet/utils/collect_env.py 
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: GeForce RTX 2080
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.2.0
```

**Comment by ZwwWayne** [comment]
Hi @grayson-hilliard ,
If you use MMDet 1.x and meet the similar problem, then yes, it is very likely the environment problem caused by recent PyTorch, we will further check it.

**Comment by usbhub** [comment]
It seems that they recently refactored their libraries yes: https://github.com/pytorch/pytorch/issues/29235 , so if you build against pytorch 1.5.0 and then try and run on an older pytorch it will have an issue.

**Comment by deepakksingh** [comment]
So should we go through INSTALL.md and redo the steps?

**Comment by interestingzhuo** [comment]
I solve this problem by using pytorch1.5 and the new version. Maybe you can use the new version.

**Comment by deepakksingh** [comment]
> I solve this problem by using pytorch1.5 and the new version. Maybe you can use the new version.

new version of?

**Comment by interestingzhuo** [comment]
> > I solve this problem by using pytorch1.5 and the new version. Maybe you can use the new version.
> 
> new version of?

The latest code.

**Comment by deepakksingh** [comment]
> > > I solve this problem by using pytorch1.5 and the new version. Maybe you can use the new version.
> > 
> > 
> > new version of?
> 
> The latest code.

I  built the environment from scratch, and it started working, thank you. But when i run for multiple GPUs using the following command: 
**./tools/dist_train.sh configs/ms_rcnn/ms_rcnn_x101_32x4d_fpn_1x_coco.py 4**
I'm having 4 GPUs on a single machine. So i have mentioned 4 above.
I'm getting SubProcessError:
subprocess.CalledProcessError: Command '['/home/dksingh/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/ms_rcnn/ms_rcnn_x101_32x4d_fpn_1x_coco.py', '--launcher', 'pytorch', '--work-dir', '/ssd_scratch/cvit/dksingh/msrcnn_logs/']' died with <Signals.SIGKILL: 9>.

**Comment by xvjiarui** [comment]
I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared. 
```
rm -r build
python setup.py develop
```

**Comment by deepakksingh** [comment]
> I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> 
> ```
> rm -r build
> python setup.py develop
> ```

Initially i was running using 1.4+, it was raising other errors, once i built the environment, it started running for single gpu machine, but when i run for multiple gpu as I have mentioned above, it's raising that issue.
I noticed other similar issues regarding it and they have mentioned that it maybe due to batch size or memory, Do you have any idea under which dictionary i should mention batch size?
Also, do we have to mention the CUDA_VISIBLE_DEVICES for multiple_gpu run on a single machine.

Thank you

**Comment by juliusfrost** [comment]
> I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> 
> ```
> rm -r build
> python setup.py develop
> ```

This also fixed it for me. I got another error with PyTorch 1.5 and CUDA 10.1 so I downgraded to PyTorch 1.4. The exact error was #2635
Also better to change to `rm -rf build` to remove the flood of prompts

**Comment by grayson-hilliard** [comment]
> > I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> > ```
> > rm -r build
> > python setup.py develop
> > ```
> 
> This also fixed it for me. I got another error with PyTorch 1.5 and CUDA 10.1 so I downgraded to PyTorch 1.4. The exact error was #2635
> Also better to change to `rm -rf build` to remove the flood of prompts

I can also confirm, this was the solution. I'm successfully running inference w/ mmdet=1.0 and cuda=10.0 :tada: 

I feel silly for not having realized I needed to delete the build folder. Could we update the docs to include this (seemingly obvious but very critical and time-consuming to triage) information?

**Comment by xvjiarui** [comment]
Hi @deepakksingh 
You may set `samples_per_gpu` in `data` dict. 
`CUDA_VISIBLE_DEVICES` may not be necessary. 
You could raise a new issue with [error template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) if you encounter other errors.

**Comment by deepakksingh** [comment]
Thank you. I will do that.

**Comment by FreyWang** [comment]
> I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> 
> ```
> rm -r build
> python setup.py develop
> ```

It not work for me ,I finnaly found the reason is that cuda version of compiling torch and extension is not match.  Adding extentsion cuda in PATH works for me

`export LD_LIBRARY_PATH="usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH"`

**Comment by E0HYL** [comment]
For me, the problem occurred when I use `pip install --upgrade torch-geometric` to update Pytorch Geometric from 1.4 to 1.5.
Then I used `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch` to update torch and the problem got solved.

**Comment by twmht** [comment]
someone may need to delete all generated so files under mmdet

```
find . -name "*.so" -type f -delete
```

**Comment by ShidiDaisy** [comment]
> I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> 
> ```
> rm -r build
> python setup.py develop
> ```

I'm also encountering this issue.. I'm also downgrading pytorch from 1.5 to 1.4.
I'm using CUDA10.0, mmdet==2.3.0rc0+b90441e.
After I ran the first round of 
`rm -r build
python setup.py develop`
the build folder doesn't appear anymore.
Only one round of this command seems couldn't solve this issue.
Could you please give some idea. I also added CUDA library path to LD_LIBRARY_PATH. But still got this issue.

**Comment by twmht** [comment]
@ShidiDaisy 

you should delete all the shared library (*.so) under mmdet, not only the build folder.

**Comment by ShidiDaisy** [comment]
> @ShidiDaisy
> 
> you should delete all the shared libraries (*.so) under mmdet, not only the build folder.

I have run 
`find . -name "*.so" -type f -delete`
`python setup.py develop`
twice, but still got this issue.

**Comment by zhepherd** [comment]
> > I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> > ```
> > rm -r build
> > python setup.py develop
> > ```
> 
> It not work for me ,I finnaly found the reason is that cuda version of compiling torch and extension is not match. Adding extentsion cuda in PATH works for me
> 
> `export LD_LIBRARY_PATH="usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH"`

thx,this work for me~

**Comment by TWDH** [comment]
Hi, I have the same problem. after I uninstall the mmdet and delete build, then when I run ```pip install -v -e .``` again, there 's no build file in mmdetection anymore which means it doesn't build successfully.

**Comment by tableter** [comment]
I met the same problem, and waste days to find the solution. Last I found that I am such a fool, I just copy this 
`pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html` 
to install mmcv, and I did not saw this command include version code, so I change it to 
`pip install mmcv-full==latest+torch1.4.0+cu100 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html`
 with **pytorch=1.4 and cuda=10.0** , finally is worked, now I am struggling in another problem.

**Comment by DanieleFundaro** [comment]
When I run the command ```from mmdet.models import build_detector``` I got the error below:
```python
File "/usr/src/app/mmdetection/mmdet/models/__init__.py", line 3, in <module>
    from .bbox_heads import *  # noqa: F401,F403
  File "/usr/src/app/mmdetection/mmdet/models/bbox_heads/__init__.py", line 3, in <module>
    from .double_bbox_head import DoubleConvFCBBoxHead
  File "/usr/src/app/mmdetection/mmdet/models/bbox_heads/double_bbox_head.py", line 2, in <module>
    from mmcv.cnn.weight_init import normal_init, xavier_init
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'
```

This is what I have from the command ```python mmdetection/mmdet/utils/collect_env.py```:
```python
sys.platform: linux
Python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce RTX 2070 SUPER
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.3.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.4.1a0+d94043a
OpenCV: 4.2.0
MMCV: 1.0.5
MMDetection: 1.2.0+unknown
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1
```
The project is in a docker container with the image
```docker
FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-devel
```
How did you solve it? Please help.

**Comment by light1003** [comment]
> I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> 
> ```
> rm -r build
> python setup.py develop
> ```

It work well，thanks

**Comment by freepoet** [comment]
i have solved this problem by reinstalling mmcv.
`pip uninstall mmcv`
`pip install mmcv-full  -i https://pypi.tuna.tsinghua.edu.cn/simple`  (not `pip install mmcv-full==latest+torch1.5.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html`)
it may be helpful for you

**Comment by exnx** [comment]
> I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> 
> ```
> rm -r build
> python setup.py develop
> ```

In what directory do I run these commands?

**Comment by hyeokhyen** [comment]
> I met the same problem, and waste days to find the solution. Last I found that I am such a fool, I just copy this
> `pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html`
> to install mmcv, and I did not saw this command include version code, so I change it to
> `pip install mmcv-full==latest+torch1.4.0+cu100 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html`
> with **pytorch=1.4 and cuda=10.0** , finally is worked, now I am struggling in another problem.

This solved my problem.

**Comment by nemonameless** [comment]
> > I met the same problem, and waste days to find the solution. Last I found that I am such a fool, I just copy this
> > `pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html`
> > to install mmcv, and I did not saw this command include version code, so I change it to
> > `pip install mmcv-full==latest+torch1.4.0+cu100 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html`
> > with **pytorch=1.4 and cuda=10.0** , finally is worked, now I am struggling in another problem.
> 
> This solved my problem.

Also solved my problem.

**Comment by wxhqw** [comment]
i solve the problem by reinstall the mmcv-full by "pip install mmcv-full==1.1.4 -i https://pypi.tuna.tsinghua.edu.cn/simple"

**Comment by wawaa** [comment]
> i solve the problem by reinstall the mmcv-full by "pip install mmcv-full==1.1.4 -i https://pypi.tuna.tsinghua.edu.cn/simple"

Thanks a lot. It works for me.

**Comment by wangluyabupt** [comment]
> I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> 
> ```
> rm -r build
> python setup.py develop
> ```

could you please tell me which build shuold be remove or while is the build file ? I can not find it.

**Comment by wxhqw** [comment]
> > I encountered this issue when I downgraded from pytorch from 1.5.0 to 1.4.0. I did the following command **twice** then the issue disappeared.
> > ```
> > rm -r build
> > python setup.py develop
> > ```
> 
> could you please tell me which build shuold be remove or while is the build file ? I can not find it.

you can try it  reinstall the mmcv-full by "pip install mmcv-full==1.1.4 -i https://pypi.tuna.tsinghua.edu.cn/simple", i solve the problem by this

**Comment by laisimiao** [comment]
Honestly speaking, I have tried all possible solutions above mentioned, but I still can't import .so shared files in pycharm(like nms_cpu.cpython-37m-x86_64-linux-gnu.so, etc.) and then raise the error like title: `ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory`, 
![image](https://user-images.githubusercontent.com/37405764/121363942-f0955680-c969-11eb-8925-b9dc4bbda439.png)
![image](https://user-images.githubusercontent.com/37405764/121364030-0145cc80-c96a-11eb-8b2f-43c0707e4507.png)

my mmdetection version is `1.0.rc0+6e48d28` that used in another repo so that I can't change version lest incompatible problems
my env is:
```
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.5.2
MMCV: 0.5.3
MMDetection: 1.1.0+unknown
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1
```

**Comment by HappyPeanuts** [comment]
> Honestly speaking, I have tried all possible solutions above mentioned, but I still can't import .so shared files in pycharm(like nms_cpu.cpython-37m-x86_64-linux-gnu.so, etc.) and then raise the error like title: `ImportError:`

I have met the same problems, have you sesolved this problem?

**Comment by Leozyc-waseda** [comment]
```
rm -r build
python setup.py develop
```

works.
