### ISSUE TITLE
how to save one image's json

### ISSUE THREAD

**Issue by Chenney0813** [open-mmlab/mmdetection#263]
`
# 构建网络，载入模型
model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
 
_ = load_checkpoint(model, 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')
 
# 测试一张图片
img = mmcv.imread('test.jpg')
result = inference_detector(model, img, cfg)
show_result(img, result)
`
I want to save the json of this image ,how can I do

**Comment by hellock** [comment]
You may refer to [results2json()](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/coco_utils.py#L140).

**Comment by Kaeseknacker** [comment]
why do I need a "dataset" object for calling results2json()? I'm also looking for a function to save my results as json.
