### ISSUE TITLE
In v2.0 shall we add new Class's name into somewhere like old style's __init__.py?

### ISSUE THREAD

**Issue by aimhabo** [open-mmlab/mmdetection#2631]
Or would it automatic finished?  So that we can just drag our file into fo the folder

**Comment by hellock** [comment]
You may leave mmdetection as a dependency and write all your codes in an isolated folder anywhere. An imperfect example is https://github.com/jshilong/SEPC.

**Comment by hiyyg** [comment]
Would v2.0 be like detectron2, in which we can just import mmdet and implement isolated projects?
