### ISSUE TITLE
Multiscale testing problems，TypeError: Scale must be a number or tuple of int, but got <class 'list'>

### ISSUE THREAD

**Issue by LvNianZu** [open-mmlab/mmdetection#2636]
My test code is：
![1](https://user-images.githubusercontent.com/35162393/81248321-a814b680-904e-11ea-8d6f-0ae395b14df0.png)
![2](https://user-images.githubusercontent.com/35162393/81248331-aba83d80-904e-11ea-8aec-52c1bbf6a133.png)

**Comment by hellock** [comment]
Please use the configs provided under `configs/`. Your version is too old.

**Comment by Pluto1314** [comment]
Hi,I also have the problem. Have you solved it?

**Comment by hellock** [comment]
@Pluto1314 Please refer to the above answer.
