### ISSUE TITLE
version

### ISSUE THREAD

**Issue by ZengminLiu** [open-mmlab/mmdetection#2637]
how can I get v1.1.0

**Comment by hellock** [comment]
`git checkout v1.1.0`. I suggest using 1.2.0 if you prefer 1.x.

**Comment by ZengminLiu** [comment]
thank you ,i have found the version


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kai Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 中午12:42
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"刘增敏"<1542775117@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] version (#2637)





 
git checkout v1.1.0. I suggest using 1.2.0 if you prefer 1.x.
