### ISSUE TITLE
Got the 404 error when i got the pretrained ".pth" file of MMDetection from model zoo

### ISSUE THREAD

**Issue by my-hello-world** [open-mmlab/mmdetection#2638]
When i use https://github.com/open-mmlab/mmdetection/blob/master/docs/MODEL_ZOO.md url,
I got the 404 error，
what should i do?
.

**Comment by hellock** [comment]
The correct URL should be https://github.com/open-mmlab/mmdetection/blob/master/docs/model_zoo.md
We will fix it.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/pull/2641
