### ISSUE TITLE
Unable to load dataset: No such file or directory

### ISSUE THREAD

**Issue by madiltalay** [open-mmlab/mmdetection#2640]
I am using a custom dataset.
In the config file, I set the parameters:

`data_root = 'content/custom_dataset/'`

Further, I also set:
```
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=data_root+'ImageSets/Main/train.txt',
            img_prefix=data_root + 'JPEGImages_trainval',
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        ann_file=data_root+'ImageSets/Main/val.txt',
        img_prefix=data_root + 'JPEGImages_trainval',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root'ImageSets/Main/test.txt',
        img_prefix=data_root + 'JPEGImages_test',
        pipeline=test_pipeline))
```
Now I am in the directory:
`/content/gdrive/My Drive/Developer/Repositories/mmdetection`

From this directory, when I run the train.py, I get the error:
> FileNotFoundError: [Errno 2] No such file or directory: 'content/custom_dataset/ImageSets/Main/train.txt'

Am I missing something?

**Comment by madiltalay** [comment]
Traversing back to the directory `content` solves the problem

**Comment by hongrui16** [comment]
I met the same error due to missing my own classes name.
