### ISSUE TITLE
How to change parameters like img_scale using the options param within tool/train.py

### ISSUE THREAD

**Issue by CMobley7** [open-mmlab/mmdetection#2646]
To Whom It May Concern,

I'm sending in a dictionary of parameters to the `options` command with the `tools/train.py` script. However, I can't figure out how to set params within the train, val, and test pipeline. For example how would I set the `img_scale` parameter within `Resize`? I've tried the following
```
params = {}
params["data.train.img_scale"] = (224, 224)
params["data.val.img_scale"] = (224, 224)
params["data.test.img_scale"] = (224, 224)
```
However, obviously, this sets it within data train, val, test, which isn't what I need.

Also, how would I add an addition dictionary to a config values instead of overwriting it. Such as adding something to `params["log_config.hooks"]`. I suppose I could just reset it entirely, but I was wondering if there was a way to just add an additional dictionary value to it. Thanks in advance.

**Comment by CMobley7** [comment]
I guess a subquestion to this would be how do you output a correctly formatted config to disk. I originally thought
```
with open(filename.py, "w") as f:
    f.write(config.dump())
```
However, this config file cannot be read back in and used, which is what I need to be able to do.

**Comment by xvjiarui** [comment]
Hi @CMobley7 
As stated in [doc](https://mmdetection.readthedocs.io/en/latest/config.html#config-system),
to use `options`, you may add `--options xxx.yyy=zzz` where `xxx` could be an existing field or a new field. 
To see the complete config, `python tools/print_config.py /PATH/TO/CONFIG`.

**Comment by hellock** [comment]
> I guess a subquestion to this would be how do you output a correctly formatted config to disk. I originally thought
> 
> ```
> from mmcv import Config
> config = Config.fromfile('filename_orig.py')
> config.merge_from_dict(additional_args_as_dict)
> with open(filename_modified.py, "w") as f:
>     f.write(config.dump())
> ```
> 
> However, this config file cannot be read back in and used, which is what I need to be able to do. I check the documentation [here](https://mmcv.readthedocs.io/en/latest/utils.html#config). as well as the [source code](https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/config.py), but didn't see an obvious way. I also tried the following, but get this `TypeError: cfg_dict must be a dict, but got <class 'str'>`
> 
> ```
> from mmcv import Config
> config = Config.fromfile('filename_orig.py')
> config.merge_from_dict(additional_args_as_dict)
> with open(filename_modified.json, "w") as f:
>     json.dump(config.dump())
> ```

```python
from mmcv import Config
config = Config.fromfile('filename_orig.py')
config.merge_from_dict(additional_args_as_dict)
with open('filename_modified.py', "w") as f:
    f.write(config.pretty_text)
```

**Comment by CMobley7** [comment]
Thanks @hellock, that exactly what I needed. 
Thanks @xvjiarui, I understand what you're saying; however, that doesn't work with variables like `img_scale`. `img_scale` is included within certain transformation in`train_pipeline`, `test_pipeline`, and `pipeline` typically within `data.train`; however, the `pipelines` are `lists` of different types of transformation. The best it appears I can do is write over that entire pipeline with the `--options` command, which isn't want I want to do. I merely want to img_scale to be different. Is this possibly using the `--options` command?

**Comment by xvjiarui** [comment]
Hi @CMobley7 
Sorry, it is not supported for now. As you said, `pipelines` are `list`. You may create a new config file for it.
