### ISSUE TITLE
TypeError: forward_train() got an unexpected keyword argument 'gt_bboxes_ignore'

### ISSUE THREAD

**Issue by kakaluote** [open-mmlab/mmdetection#265]
i pull latest code at master branch, and try to train pascal voc with retinanet,then got this error 
`TypeError: forward_train() got an unexpected keyword argument 'gt_bboxes_ignore'`

i have try to rollback pytorch from 1.0 to 0.4,also error

**Comment by ZLeopard** [comment]
So what i do now? i got the same error with training the single stage detector ----RetinaNet!!

**Comment by ZLeopard** [comment]
#327 this can solve it !!!
