### ISSUE TITLE
How to use lmdb dataset with dist train?

### ISSUE THREAD

**Issue by cizhenshi** [open-mmlab/mmdetection#2652]
I want to use LMDB to store and read data, so I modified the code of the data read part in the loading.py like this:
`class LoadImageFromFile(object):

    def __init__(self, to_float32=False, color_type='color', lmdb_dir="./data/coco"):
        self.to_float32 = to_float32
        self.color_type = color_type
        self.lmdb_dir = lmdb_dir
        self.cur_lmdb = lmdb.open(self.lmdb_dir, readonly=True)

    def __call__(self, results):
        if results['img_prefix'] is not None:
            filename = osp.join(results['img_prefix'],
                                results['img_info']['filename'])
        else:
            filename = results['img_info']['filename']

        # img = mmcv.imread(filename, self.color_type)
        #xx
        #cur_lmdb = lmdb.open(self.lmdb_dir, readonly=True)
        cur_lmdb = self.cur_lmdb
        handle = cur_lmdb.begin()
        value = handle.get(filename.encode())
        image_buf = np.asarray(bytearray(value), dtype="uint8")
        img = cv2.imdecode(image_buf, cv2.IMREAD_COLOR)

        if self.to_float32:
            img = img.astype(np.float32)
        results['filename'] = filename
        results['img'] = img
        results['img_shape'] = img.shape
        results['ori_shape'] = img.shape
        return results

    def __repr__(self):
        return '{} (to_float32={}, color_type={})'.format(
            self.__class__.__name__, self.to_float32, self.color_type)
`

but i get the error:
Traceback (most recent call last):
  File "./tools/train.py", line 126, in <module>
    main()
  File "./tools/train.py", line 122, in main
    timestamp=timestamp)
  File "xxx/mmdet/apis/train.py", line 103, in train_detector
    timestamp=timestamp)
  File "xxx/mmdet/apis/train.py", line 250, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "xxx/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "xxx/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    for i, data_batch in enumerate(data_loader):
  File "xxx/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "xxxi/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    w.start()
  File "xxx/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "xxxi/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "xxxanaconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "xxx/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/xxx/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "xxx/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "xxx/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle Environment objects

can you give me some advice?

**Comment by xinntao** [comment]
You should put lmdb initialization function `lmdb.open(self.lmdb_dir, readonly=True)`  outside the __init__ function. 

Ref: 
https://github.com/open-mmlab/mmsr/blob/a73b318f0f07feb6505ef5cb1abf0db33e33807a/codes/data/LQGT_dataset.py#L34-L39

**Comment by cizhenshi** [comment]
> You should put lmdb initialization function `lmdb.open(self.lmdb_dir, readonly=True)` outside the **init** function.
> 
> Ref:
> https://github.com/open-mmlab/mmsr/blob/a73b318f0f07feb6505ef5cb1abf0db33e33807a/codes/data/LQGT_dataset.py#L34-L39

Thanks for your reply.  it works.  But we need to create an LMDB environment object each time  we get an item.  I think it will make LMDB data reading less efficient?  This seems inevitable. Is that?

**Comment by xinntao** [comment]
It only creates when the env is None.

Ref:
https://github.com/open-mmlab/mmsr/blob/a73b318f0f07feb6505ef5cb1abf0db33e33807a/codes/data/LQGT_dataset.py#L41-L43

**Comment by cizhenshi** [comment]
I got it! thanks!

**Comment by cizhenshi** [comment]
`def __init__(self, to_float32=False, color_type='color', lmdb_dir="./data/coco"):
        self.to_float32 = to_float32
        self.color_type = color_type
        self.lmdb_dir = lmdb_dir
        self.cur_lmdb = None

    def init_lmdb(self):
        self.cur_lmdb = lmdb.open(self.lmdb_dir, readonly=True)

    def __call__(self, results):
        if results['img_prefix'] is not None:
            filename = osp.join(results['img_prefix'],
                                results['img_info']['filename'])
        else:
            filename = results['img_info']['filename']

         if self.cur_lmdb is None:
            self.init_lmdb()
        handle = self.cur_lmdb.begin()
        value = handle.get(filename.encode())
        image_buf = np.asarray(bytearray(value), dtype="uint8")
        img = cv2.imdecode(image_buf, cv2.IMREAD_COLOR)`

I'm sorry. I thought I got it but not.  I've found that this can cause dataloader deadlock in num_worker>1. I don't understand why? Anybody have any ideas？

**Comment by xinntao** [comment]
try this 
`
lmdb.open(self.lmdb_dir, readonly=True, lock=False, readahead=False,
                                meminit=False)`
instead of `lmdb.open(self.lmdb_dir, readonly=True)`

**Comment by cizhenshi** [comment]
It works! Thank you very much.
