### ISSUE TITLE
How to clip the loss or gradient?

### ISSUE THREAD

**Issue by hanjianhua44** [open-mmlab/mmdetection#2654]
In the process of training the model, we may have a gradient explosion, which will lead to the failure of our model training.
We can adopt a simple strategy to avoid gradient explosion like gradient truncation, and I want to know how to clip the loss or gradient in mmdetection?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/fcos_r50_caffe_fpn_4x4_1x_coco.py#L97
