### ISSUE TITLE
交流群

### ISSUE THREAD

**Issue by interestingzhuo** [open-mmlab/mmdetection#2655]
大佬方便拉一个微信交流群吗？

**Comment by interestingzhuo** [comment]
![群二维码](https://user-images.githubusercontent.com/43921151/81393046-37ef5900-9152-11ea-892a-9c11b08fad6e.jpg)

**Comment by interestingzhuo** [comment]
冒昧的拉了一个群，需要交流的可以加群，等作者入群了我就把群转给作者。

**Comment by lji72** [comment]
这个二维码失效了，有新的二维码么？

**Comment by interestingzhuo** [comment]
![微信图片_20200515232210](https://user-images.githubusercontent.com/43921151/82071769-22a59c00-9709-11ea-80ed-88cbb812360e.png)

**Comment by zhayanli** [comment]
又失效啦，发个新的，多谢。

**Comment by zhayanli** [comment]
已经加入了，多谢。

**Comment by YAOYI626** [comment]
hey @interestingzhuo would it be possible to update QR code? thanks!

**Comment by Paddy-Xu** [comment]
可以再发下二维码吗，多谢！

**Comment by interestingzhuo** [comment]
![微信图片_20200528124902](https://user-images.githubusercontent.com/43921151/83100145-c451c380-a0e1-11ea-8ed7-7a87028569fd.png)

**Comment by linmelon** [comment]
又失效了，求更新
