### ISSUE TITLE
Depth-wise deformable convolutions are slow

### ISSUE THREAD

**Issue by MauroPfister** [open-mmlab/mmdetection#2656]
Hi

I noticed that the implementation of deformable convolutions is really slow when using depth-wise convolutions (`groups = in_channels`). See profiling output below and profiling script [here](https://gist.github.com/MauroPfister/6643169d1b0d9b656277dbaaa8548745).
If there is any chance, the current code could be made faster for these depth-wise convolutions, that would be fantastic.

```
# Output of deform_conv_speed.py

bs: 01, in-channels: 512, groups: 1
Time normal conv:                0.37 ms
Time torchvision deform conv:    0.37 ms
Time mmdet deform conv:          0.36 ms
----------------------------------------
bs: 01, in-channels: 512, groups: 512
Time normal conv:                0.19 ms
Time torchvision deform conv:   15.23 ms
Time mmdet deform conv:         13.67 ms
----------------------------------------
bs: 16, in-channels: 512, groups: 1
Time normal conv:                1.15 ms
Time torchvision deform conv:    2.26 ms
Time mmdet deform conv:          2.19 ms
----------------------------------------
bs: 16, in-channels: 512, groups: 512
Time normal conv:                0.32 ms
Time torchvision deform conv:   15.06 ms
Time mmdet deform conv:         13.76 ms
----------------------------------------
```

**Motivation**
I am using deformable convolutions to shift feature maps in the spatial dimension similar to the approach described in [Spatiotemporal Sampling Networks](https://arxiv.org/abs/1803.05549). Using regular convolutions would introduce more parameters than necessary which is why I opted for depth-wise convolutions which reduce the amount of parameters by a factor of `in_channels`. Unfortunately this makes the network very slow, both in training but even more so during inference.

**Related resources**
I started a [thead](https://discuss.pytorch.org/t/depthwise-deformable-convolutions-are-slow/80030) in the PyTorch forum to ask for advice concerning this issue. In the mean time I found out that I can at use the weights trained with depth-wise convolutions for inference with normal convolutions if I initialize the kernels as in the code snipped below (see [this post](https://discuss.pytorch.org/t/depthwise-deformable-convolutions-are-slow/80030/6?u=mauropfister) for more information). 
```
# model.deform_conv.weight.shape = [512, 512, 3, 3]
# pretrained_kernels.shape = [512, 1, 3, 3]

for i in range(model.deform_conv.weight.shape[0]):
    model.deform_conv.weight[i, i, :, :] = pretrained_kernels[i, 0, :, :]
```
I was wondering if the same approach could not also be used on cuda level to speed up the grouped convolutions for the special case where `groups = in_channels`?

Unfortunately I have zero experience with cuda code but I am happy to help if I get some guidance.

**Comment by xvjiarui** [comment]
Hi @MauroPfister 
Thanks for bringing this up. I will take a look into it.

**Comment by MauroPfister** [comment]
Hi @xvjiarui 
Thanks for considering my suggestion. Did you already have time to look at it?

Cheers

**Comment by xvjiarui** [comment]
Hi @MauroPfister 
Sorry for the late reply. Actually, I didn't find an elegant way to fix it for good. Since DCN is implemented on CUDA without cudnn support, depthwise is slow.

**Comment by MauroPfister** [comment]
Oh that's too bad. I guess I'll have to work with my hack from the first post then.

Thanks anyways for looking into it and please keep us posted if you manage to speed it up.

**Comment by Leonngm** [comment]
Hi, 
I just noticed, that depthwise deformable convolutions are still slow. Is there any update on speeding them up?
Thanks!
