### ISSUE TITLE
warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")

### ISSUE THREAD

**Issue by leoliangyao** [open-mmlab/mmdetection#266]
2019-01-17 13:01:53,625 - INFO - Distributed training: False
2019-01-17 13:01:54,027 - INFO - load model from: modelzoo://resnet50
2019-01-17 13:01:54,190 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer3.5.bn1.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.4.bn2.num_batches_tracked, bn1.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer3.0.bn1.num_batches_tracked

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-01-17 13:01:56,404 - INFO - Start running, host: manning@spider, work_dir: /home/manning/leounet/mmcv/mmdetection/work_dirs/mask_rcnn_r50_fpn_1x
2019-01-17 13:01:56,404 - INFO - workflow: [('train', 1)], max: 12 epochs
/home/manning/leounet/venv/lib/python3.5/site-packages/torch/nn/_reduction.py:16: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  **warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")**

Help me please. I don't know why it show this warning when I try to train my own dataset. Thank you very much!

**Comment by hellock** [comment]
You are using pytorch 1.0, so you need to merge the pytorch-1.0 branch manually.

**Comment by leoliangyao** [comment]
> You are using pytorch 1.0, so you need to merge the pytorch-1.0 branch manually.

Thanks for your reply! I have change the files that you required in #257,but it also shows the warning.Sadding~~

**Comment by leoliangyao** [comment]
> You are using pytorch 1.0, so you need to merge the pytorch-1.0 branch manually.

Could you give me what I can do in detail? Thank you very much!

**Comment by hellock** [comment]
`git merge pytorch-1.0` and reinstall it.
