### ISSUE TITLE
Error pytorch1.5+mmdet need gcc>5

### ISSUE THREAD

**Issue by shipengai** [open-mmlab/mmdetection#2663]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
#error "You're trying to build Pytorch with a too old version of GCC. We need GCC 5 or later"

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by shipengai** [comment]
I update gcc from 4.9.2 to 5.4,Then, the error miss.

**Comment by hellock** [comment]
Would you like to create a PR to fix the requirements in the doc?

**Comment by hellock** [comment]
@yhcao6 Please create a PR to fix it.
