### ISSUE TITLE
dcn ops run too slow

### ISSUE THREAD

**Issue by AprLie** [open-mmlab/mmdetection#2664]
The dcn module is used in my project which aims to predict the time series of N points. The training data is with batch_size ~ 256, N ~ 300, t ~ 100, num_feature ~ 1. The data will be reshaped into [batch_size * N, num_feature, t, 1] to adapt to the dcn. However, when using V100 with 15.5G memory, it takes about 140s for a single batch, and the GPU-Util is almost less than 20%. Therefore, I would like to consult with you whether such a time cost and GPU-Util is reasonable because it is too slow to train a model like that.

**Comment by hellock** [comment]
Conv is highly optimized in CUDNN while DCN is not. You may have a try.

**Comment by AprLie** [comment]
Could you tell me which Conv it is? The traditional Conv in Pytorch or some other ops in mmdetection? The conv I used is Class ModulatedDeformConvPack in deform_conv.py.

**Comment by hellock** [comment]
I mean the traditional convolution layer.
