### ISSUE TITLE
No module named 'tools' 

### ISSUE THREAD

**Issue by LaserLV52** [open-mmlab/mmdetection#2667]
i used the command:
python tools/test.py configs/reppoints/reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py checkpoints/reppoints_moment_r101_dcn_fpn_2x_mt.pth --show
to test the model, but report some error.

Traceback (most recent call last):
  File "tools/test.py", line 10, in <module>
    from tools.fuse_conv_bn import fuse_module
ModuleNotFoundError: No module named 'tools'

how to solve it, thanks

**Comment by yhcao6** [comment]
```
PYTHONPATH=${PWD}:$PYTHONPATH python tools/test.py configs/reppoints/reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py checkpoints/reppoints_moment_r101_dcn_fpn_2x_mt.pth --show
```

**Comment by Key2Love** [comment]
@yhcao6 Can you explain why adding "PYTHONPATH=${PWD}:$PYTHONPATH" before the old code will do ?  I have search for it, but I think it just adds environment variable, but doesn't change the fact that  the fuse_conv_bn.py file has been removed . Thanks !
