### ISSUE TITLE
What does base_size in AnchorGenerator means?

### ISSUE THREAD

**Issue by X-funbean** [open-mmlab/mmdetection#2668]

**Comment by X-funbean** [comment]
Hi! I'm new to object detection and I'm stuck with some basic concepts. What does `base_size` in `AnchorGenerator` means? What's its relationship with the actual size of anchor boxes on the input image?  Please help me out. Thanks!

**Comment by hellock** [comment]
The actual size is `base_size * scale`, you may refer to the [code](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_generator.py#L134-L164).
