### ISSUE TITLE
Question about `output_buffer` and `gradOutputBuffer` in DCN C++ Source Code

### ISSUE THREAD

**Issue by yizhou-wang** [open-mmlab/mmdetection#2679]
Hi, 

Recently, I was reading the C++ source code of Deformable Conv. While I met a question about the shape of `output_buffer` and `gradOutputBuffer` in the DCN C++ source code. Here is the source code. 

https://github.com/open-mmlab/mmdetection/blob/3c021b1167095767c7be32d3007b57ed71753f80/mmdet/ops/dcn/src/cuda/deform_conv_cuda.cpp#L213-L216

https://github.com/open-mmlab/mmdetection/blob/3c021b1167095767c7be32d3007b57ed71753f80/mmdet/ops/dcn/src/cuda/deform_conv_cuda.cpp#L432-L434

Why the shape of `output_buffer` is transformed into `batchSize / im2col_step, nOutputPlane, im2col_step * outputHeight, outputWidth` instead of `batchSize / im2col_step, nOutputPlane, im2col_step, outputHeight, outputWidth`? Similar question for the shape of `gradOutputBuffer`. 

Can anyone leave some ideas about that? Thanks a lot!

**Comment by ZwwWayne** [comment]
It is simple legacy code. I think both should be OK as long as the downstream APIs are consistent with it.
