### ISSUE TITLE
The Faster RCNN training procedure stops at the second epoch without error.

### ISSUE THREAD

**Issue by ZhexuanZhou** [open-mmlab/mmdetection#2685]
I was training a faster rcnn with my own dataset. The training in the first epoch went well. When the second epoch started, the training stopped after 150 iterators. The stop does not mean there is some error, it means that the training procedure does not go any further and the GPUs are fully occupied.

Looking forward to your response.

**Comment by ZhexuanZhou** [comment]
> I was training a faster rcnn with my own dataset. The training in the first epoch went well. When the second epoch started, the training stopped after 150 iterators. The stop does not mean there is some error, it means that the training procedure does not go any further and the GPUs are fully occupied.
> 
> Looking forward to your response.

It worked well when I used one GPU.

**Comment by BIGWangYuDong** [comment]
This maybe due to the PyTorch codes, you can update the PyTorch version and mmdet version.
If you still meet this error, please feel free to create a new issue
