### ISSUE TITLE
CPU(Not cuda)

### ISSUE THREAD

**Issue by stu5** [open-mmlab/mmdetection#2688]
hello,i  do not have cuda,and i can use this tools to run  my medical image?If it's convenient, can you give me a rough idea of the process? How are the steps different from installing the CUDA version?

**Comment by xvjiarui** [comment]
Currently, CPU training is not supported. However, you could use our models to inference without CUDA. You may refer to [here](https://mmdetection.readthedocs.io/en/latest/install.html#install-with-cpu-only) for details.

**Comment by VishalPrasadIITGn** [comment]
Link expired. Kindly post the new link.

**Comment by VpkPrasanna** [comment]
[See here ](https://mmdetection.readthedocs.io/en/latest/get_started.html#install-with-cpu-only)
