### ISSUE TITLE
New params list. Accuracy drop with update.

### ISSUE THREAD

**Issue by dereyly** [open-mmlab/mmdetection#269]
I have update mmdetection to new version. I think previous was 3 month ago 
`commit 3f5df4f061aa0831c5adff670afa4148d405fe54
Merge: 86e25e4 9dd4334
Author: Kai Chen <chenkaidev@gmail.com>
Date:   Thu Nov 1 19:09:46 2018 +0800
`
And my mAP drop dramatically. With standard scale training and testing in my dataset objects higher 512x512 in resized image to 800xN are missed. What changes in training or testing may do this. 
Mayby something like this min_pos_iou=0.3 -- but it may drop object more 1024

**Comment by hellock** [comment]
We kept tracking the performance when we add new features or updates. The performance on COCO dataset is still reproducible. Maybe you can compare the versions?

**Comment by dereyly** [comment]
It was strange bug in my code
