### ISSUE TITLE
Image inference results into json ?

### ISSUE THREAD

**Issue by CamilleMaurice** [open-mmlab/mmdetection#2693]
Dear all,
Thank you for reading this thread. I am using object detection inference on image through the demo, I am using a model pre-trained on COCO. I wonder how could I export the result into json ? I have seen the method "results2json" from the CocoDataset class but I can't use it (I don't have the COCO annotation file and I'm not interested getting it). Do you have a simple way to achieve it ?
Also, I could implement it my myself I guess, but if it is already implemented I would not mind using it.
Thank you all,
Camille

`result = inference_detector(model, image)`

**Comment by Yukinoyuki1** [comment]
I'll give you an example.
python ./tools/test.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py  ./work_dirs/epoch_2.pth --format-only --options "jsonfile_prefix=./results"

**Comment by CMobley7** [comment]
@Yukinoyuki1 , similar question. I used to use the method you are suggesting here; however, it no longer seems to work under 2.0. Can you take a look at https://github.com/open-mmlab/mmdetection/issues/2167 and comment if you have any ideas.

**Comment by Yukinoyuki1** [comment]
Well, the annotation file is **NECESSARY**.

**Comment by hellock** [comment]
Seems that we can make `results2json()` a classmethod so that it can be used without initializing a COCO dataset.

**Comment by sipie800** [comment]
why the annotation is necessary? if I have one ,why do I do inference any way?

**Comment by wwcc1107** [comment]
have you solve this problem?

**Comment by 0ssamaak0** [comment]
Anything new?

**Comment by Jeff001128** [comment]
> lar question. I used to use the method you are suggesting here; however, it

Hi, it seems that ` --format-only `or `--options` is not provided in tools/test.py. Could you help me out? Thx!

**Comment by Jeff001128** [comment]
> > lar question. I used to use the method you are suggesting here; however, it
> 
> Hi, it seems that `--format-only`or `--options` is not provided in tools/test.py. Could you help me out? Thx!

Oh, I figure it out. Here's the solution.

Modify in the config file by replacing` test_evaluator `with 
```
test_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/image_info_test-dev2017.json',
    metric=['bbox'],
    format_only=True,  # 只将模型输出转换为 coco 的 JSON 格式并保存
    outfile_prefix='./work_dirs/coco_detection/test')  # 要保存的 JSON 文件的前缀
```
