### ISSUE TITLE
Extracting mAP for each class when evaluating. 

### ISSUE THREAD

**Issue by kinredon** [open-mmlab/mmdetection#2694]
Is there some way to extract an mAP metric for each individual class/label when evaluating?

I am using a COCO-like custom dataset.

Any help or advice is appreciated, thanks!

**Comment by ZwwWayne** [comment]
Example 5 in [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md) should help.

**Comment by mytk2012** [comment]
> Example 5 in [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md) should help.

Can you provide another option？I run it on the remote server，.sh can't be run.

**Comment by kinredon** [comment]
@mytk2012 you can extract the command from the .sh.

**Comment by mytk2012** [comment]
> @mytk2012 you can extract the command from the .sh.

Can you give me some examples?I have never seen contents in .sh like this.Before that,it mainly consists of several pip commandlines
