### ISSUE TITLE
Could test step support changing config parameters?

### ISSUE THREAD

**Issue by Robert-BoMiao** [open-mmlab/mmdetection#2695]
Hi,

I notice that in the training commands, we can easily using "--options" to change the parameters as shown below. However, in the test commands, it seems that changing data.test.ann_file in --options will bring bugs in "kwargs = {} if args.options is None else args.options". Could test support all the functions that training has?

Thanks.
===============================================
#python tools/train.py configs/dcn/mask_rcnn_r50_fpn_mdconv_c3-c5_1x_coco.py \
#       --gpus 1 \
#       --options data.samples_per_gpu=1 data.workers_per_gpu=1 data.train.ann_file='data/coco/annotations/instances_train2017_11000.json'

**Comment by ZwwWayne** [comment]
The need to change the test time config is not so frequent as that in training time. We may consider adding this feature in the future. PRs are also welcomed.
