### ISSUE TITLE
Bugs when the labels is empty during inference.

### ISSUE THREAD

**Issue by Robert-BoMiao** [open-mmlab/mmdetection#2696]
Hi,

I noticed that if labels is empty during inference, there will have a bug in max(labels) as shown below.

============================
mmdet/models/detectors/base.py
row:204
raw:
            color_masks = [
                np.random.randint(0, 256, (1, 3), dtype=np.uint8)
                for _ in range(max(labels) + 1)
            ]
fixed:
            max_labels = max(labels) if len(labels) > 0 else 0
            color_masks = [
                np.random.randint(0, 256, (1, 3), dtype=np.uint8)
                for _ in range(max_labels + 1)
            ]

**Comment by hellock** [comment]
Fixed in #2763
