### ISSUE TITLE
[HTC] inference with pretrained HTC models gets wrong results.

### ISSUE THREAD

**Issue by mangdian** [open-mmlab/mmdetection#2697]
I just simply tried using the demo code to test the pretained HTC models (all downloaded from model_zoo, the command is as follows:
`python demo/image_demo.py demo/demo.jpg configs/htc/htc_r50_fpn_1x_coco.py     checkpoints/htc_r50_fpn_1x_coco_20200317-7332cf16.pth --device cpu`

The result makes no sense:

![QQ图片20200512201655](https://user-images.githubusercontent.com/18326098/81690486-ec101d00-948d-11ea-81a7-06c0add41252.jpg)

and an error occured:

` File "demo/image_demo.py", line 27, in <module>
    main()
  File "demo/image_demo.py", line 23, in main
    show_result_pyplot(model, args.img, result, score_thr=args.score_thr)
  File "/home/zt/pjob/mmdetection/mmdet/apis/inference.py", line 150, in show_result_pyplot
    plt.imshow(mmcv.bgr2rgb(img))
  File "/home/zt/anaconda3/lib/python3.6/site-packages/mmcv/image/colorspace.py", line 280, in convert_color
    out_img = cv2.cvtColor(img, code)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

When I test with mask rcnn models or faster rcnn models, it works fine.
Is there anything different or anything wrong with HTC models?
Thanks.

**Comment by mangdian** [comment]
Anyone can help me? Please?

**Comment by mangdian** [comment]
I found that when using cascaded mask rcnn or HTC for inference, model.show_result( ) just return a None. I can confirm that inside the show_result the image is not empty, and everything works fine. But when show_result() returns the result image, actually a None is received. This situation doesn't happen when inference with faster rcnn or mask rcnn. 
Hope that you can fix this bug. Thanks. 
And besides, from the picture I give above we can see that the performance of pretrained HTC models is poor. It seems that it can only identify these small instances.

**Comment by rassabin** [comment]
> I found that when using cascaded mask rcnn or HTC for inference, model.show_result( ) just return a None. I can confirm that inside the show_result the image is not empty, and everything works fine. But when show_result() returns the result image, actually a None is received. This situation doesn't happen when inference with faster rcnn or mask rcnn.
> Hope that you can fix this bug. Thanks.
> And besides, from the picture I give above we can see that the performance of pretrained HTC models is poor. It seems that it can only identify these small instances.

Have you solve the problem? Because i faced the similar one also with Cascade model.
