### ISSUE TITLE
FishNet backbone and Guided Anchoring?

### ISSUE THREAD

**Issue by gaussfan** [open-mmlab/mmdetection#27]
Thanks the team very much for sharing the code! 

When I read the code, I cannot find the FisherNet backbone and the Guided Anchoring design.  Will these parts be released in the future, or just they lie in somewhere that I haven't noticed?

**Comment by hellock** [comment]
For FishNet, please contact the author [Shuyang Sun](https://github.com/kevin-ssy) for details. As he [replied](https://github.com/open-mmlab/mmdetection/issues/15#issuecomment-428890562), it will be released (maybe in [mmcv](https://github.com/open-mmlab/mmcv)) at the end of this month.

For the Guided Anchoring, it will be released after the paper being accepted or public on Arxiv.

**Comment by gaussfan** [comment]
Got it.
