### ISSUE TITLE
batch inference

### ISSUE THREAD

**Issue by noumanriazkhan** [open-mmlab/mmdetection#2703]
What are the necessary changes to enable inference model for batch inference?

I know this has been discussed many a times here and I know developers are working on this but what if I want to achieve it myself?

The test_pipeline as ImageToTensor method which can be replaced with DefaultFormatBundle but LoadImage returns dict, should I return list of dicts?

Thanks!

**Comment by noumanriazkhan** [comment]
never mind, I solve it.

**Comment by mitsuix** [comment]
> never mind, I solved it.

How did you solve it?

**Comment by akhalili** [comment]
how did you solve it?
