### ISSUE TITLE
 raise KeyError('metric {} is not supported'.format(metric)) 

### ISSUE THREAD

**Issue by smartparrot** [open-mmlab/mmdetection#2705]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by smartparrot** [comment]
In my config file, there is a line : evaluation = dict(interval=1, metric='bbox').
After the first epoch, I got the error as below:

 File "/data/zhangcong/mmdetection/mmdet/datasets/custom.py", line 186, in evaluate

    raise KeyError('metric {} is not supported'.format(metric))

I use customized COCO dataset.

Who can tell me how to fix this?

**Comment by Ronales** [comment]
I also get this error during test performance.my code:

python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --eval mAP

**Comment by Ronales** [comment]
**I only use one class coco dataset**

(newtorch) pjw@star:~/yccdataset/mmdetection$ python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --eval mAP
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 314/314, 10.0 task/s, elapsed: 32s, ETA:     0sTraceback (most recent call last):
  File "tools/test.py", line 150, in <module>
    main()
  File "tools/test.py", line 146, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/home/pjw/miniconda3/envs/newtorch/lib/python3.6/site-packages/mmdet-2.0.0+ba58dda-py3.6-linux-x86_64.egg/mmdet/datasets/coco.py", line 347, in evaluate
    raise KeyError(f'metric {metric} is not supported')
KeyError: 'metric mAP is not supported'

**Comment by ZwwWayne** [comment]
The metric is not mAP, it is `bbox`, `segm` as shown in the `Inference with pretrained models` section of [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md).

**Comment by BeingGod** [comment]
> In my config file, there is a line : evaluation = dict(interval=1, metric='bbox').
> After the first epoch, I got the error as below:
> 
> File "/data/zhangcong/mmdetection/mmdet/datasets/custom.py", line 186, in evaluate
> 
> ```
> raise KeyError('metric {} is not supported'.format(metric))
> ```
> 
> I use customized COCO dataset. I add --validate in my train command.
> 
> Who can tell me how to fix this?

Hey guys,I also some question. Did you fix your problem? Would you tell me more details?

**Comment by sei-amellinger** [comment]
> The metric is not mAP, it is `bbox`, `segm` as shown in the `Inference with pretrained models` section of [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md).

Too bad the tutorial shows it as "mAP" - https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb

**Comment by hhaAndroid** [comment]
> > The metric is not mAP, it is `bbox`, `segm` as shown in the `Inference with pretrained models` section of [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md).
> 
> Too bad the tutorial shows it as "mAP" - https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb

Hi. This is not an error, as different datasets use different evaluation metrics. The COCO dataset use `bbox` and `segm`，but the custom dataset use` mAP`

**Comment by HHZLL** [comment]
> **I only use one class coco dataset**
> 
> (newtorch) pjw@star:~/yccdataset/mmdetection$ python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --eval mAP
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 314/314, 10.0 task/s, elapsed: 32s, ETA: 0sTraceback (most recent call last):
> File "tools/test.py", line 150, in
> main()
> File "tools/test.py", line 146, in main
> dataset.evaluate(outputs, args.eval, **kwargs)
> File "/home/pjw/miniconda3/envs/newtorch/lib/python3.6/site-packages/mmdet-2.0.0+ba58dda-py3.6-linux-x86_64.egg/mmdet/datasets/coco.py", line 347, in evaluate
> raise KeyError(f'metric {metric} is not supported')
> KeyError: 'metric mAP is not supported'



> **I only use one class coco dataset**
> 
> (newtorch) pjw@star:~/yccdataset/mmdetection$ python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --eval mAP
> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 314/314, 10.0 task/s, elapsed: 32s, ETA: 0sTraceback (most recent call last):
> File "tools/test.py", line 150, in
> main()
> File "tools/test.py", line 146, in main
> dataset.evaluate(outputs, args.eval, **kwargs)
> File "/home/pjw/miniconda3/envs/newtorch/lib/python3.6/site-packages/mmdet-2.0.0+ba58dda-py3.6-linux-x86_64.egg/mmdet/datasets/coco.py", line 347, in evaluate
> raise KeyError(f'metric {metric} is not supported')
> KeyError: 'metric mAP is not supported'
I meet the same problem,do you have done it?

**Comment by LuooChen** [comment]
> > > The metric is not mAP, it is `bbox`, `segm` as shown in the `Inference with pretrained models` section of [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md).
> > 
> > 
> > Too bad the tutorial shows it as "mAP" - https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb
> 
> Hi. This is not an error, as different datasets use different evaluation metrics. The COCO dataset use `bbox` and `segm`，but the custom dataset use` mAP`

So sad, i also got this error, because i use `metric='bbox'` by default config, and my dataset was custom dataset. Is it any tips can find in the document?

**Comment by momobiubiubiu** [comment]
change 'bbox' , use 'mAP' to replay it.
