### ISSUE TITLE
Reading the num_classes from json

### ISSUE THREAD

**Issue by NeelBhowmik** [open-mmlab/mmdetection#2711]
Hi,
It's a nice code with fairly easy to use.
However - while training, I observe the **_num_classes_** (in config files) needs to be passed from the command line or user needs to update the config file manually. Why don't you please, update this parameter automatically from the _training annotation file (json)_? The _num_classes_ information is available in the annotation files.

Thanks,
Neel

**Comment by ZwwWayne** [comment]
Because this entangles the datasets and detectors and will increase the complexity. However, developers should be responsible for this setting and so as to their own dataset.
