### ISSUE TITLE
how to add mask_iou_head(mask scoring rcnn module) onto HTC(or Cascade RCNN)

### ISSUE THREAD

**Issue by tangjiasheng** [open-mmlab/mmdetection#2715]
New to MMDetection. I wanna implement this head. Can anyone share any ideas or code fragment?

**Comment by ZwwWayne** [comment]
You can find code in [mask_iou_head](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/mask_scoring_roi_head.py) and [cascade_head](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/cascade_roi_head.py). Create a new roi_head should work, this [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_modules.md) might do some help.

**Comment by rzgbw** [comment]
同样的需求，请问解决了吗
