### ISSUE TITLE
Error during evaluation in mean_ap.py

### ISSUE THREAD

**Issue by Harish202** [open-mmlab/mmdetection#2716]
Thank you for your code. I have been using it since a year but for this new version of code I am facing below issue during evaluation of mAP.

During evaluation there is a loop through num_classes. 
for i in range(num_classes):
        cls_dets, cls_gts, cls_gts_ignore = get_cls_results(
            det_results, annotations, i)
here when i is 0, there will not be any ground truth for 0 class. I have 1 class so during my annotation class label I appended is as 1 as 0 will be background which has been the case for your old repository. Since there will not be any GTBbox for class 0, evaluation is failing at that step.

May I please know if I am missing something here. Should I need to annotate my one class as 0 during the train.json. Your help is much appreciated.

**Comment by hellock** [comment]
Please refer to the documentation: https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md#codebase-conventions
