### ISSUE TITLE
Issue with keep_ratio=False in resize transform (swapped width and height)

### ISSUE THREAD

**Issue by tiago-gaspar** [open-mmlab/mmdetection#2723]
In structures.py, the width and height are in the wrong order, when calling imresize:

https://github.com/open-mmlab/mmdetection/blob/d0f71b228d2ed5884a94ac0ce1d19af6a5c256ff/mmdet/core/mask/structures.py#L139

resize receives height first, but imresize receives width first.

This leads to weird masks when using Resize transform with keep_ratio=False

**Comment by hellock** [comment]
Thanks for reporting the issue. The api `mmcv.imresize` was designed to behave like this. The input shape is treated as the long edge and short edge, regardless of w and h. We will rethink the design of this API, however.
