### ISSUE TITLE
where to change the class name in updated mmdet?

### ISSUE THREAD

**Issue by prajnasb** [open-mmlab/mmdetection#2728]
hey can anyone help me out with this issue, I want to train the SSD model with Voc dataset but I am not able to change the class name, I tried editing voc.py but still it is not happening.
and I even want to know the inference script for the updated mmdet.

**Comment by tiltgod** [comment]
you need to setup.py develop again after you edit voc.py

**Comment by hellock** [comment]
Please refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html#modify-classes-of-existing-dataset).
