### ISSUE TITLE
when train retina-resnet50_coco, loss_box is 0 with mmdetection 2.0 

### ISSUE THREAD

**Issue by lji72** [open-mmlab/mmdetection#2729]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

When I use mmdetection2.0 to train retinanet-resnet50-coco, but bbox-loss is 0 when started training and loss-cls becomes 0 shortly. 

**Reproduction**
1./tools/dist_train.sh configs/retinanet/retinanet_r50_fpn_1x_coco.py 8
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
use 4/8 GPU and 4 images per gpu

3. What dataset did you use?
coco
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.6.10 | packaged by conda-forge | (default, Mar  5 2020, 10:05:08) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.3.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.4.1+cu100
OpenCV: 4.2.0
MMCV: 0.5.1
MMDetection: 2.0.0+unknown
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0


2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

    Download whl from pytorch website and use pip to install.

**Error traceback**
If applicable, paste the error trackback here.
```
ERROR LOG:
2020-05-15 18:46:42,316 - mmdet - INFO - Epoch [1][50/3665]     lr: 0.00198, eta: 19:31:43, time: 1.600, data_time: 1.096, memory: 6326, loss_cls: 8.3815, lo
ss_bbox: 0.0000, loss: 8.3815
2020-05-15 18:47:02,830 - mmdet - INFO - Epoch [1][100/3665]    lr: 0.00398, eta: 12:15:17, time: 0.410, data_time: 0.009, memory: 6326, loss_cls: 0.0000, lo
ss_bbox: 0.0000, loss: 0.0000
2020-05-15 18:47:23,263 - mmdet - INFO - Epoch [1][150/3665]    lr: 0.00597, eta: 9:49:09, time: 0.409, data_time: 0.008, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
2020-05-15 18:47:43,913 - mmdet - INFO - Epoch [1][200/3665]    lr: 0.00797, eta: 8:36:39, time: 0.413, data_time: 0.009, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
2020-05-15 18:48:04,442 - mmdet - INFO - Epoch [1][250/3665]    lr: 0.00997, eta: 7:52:43, time: 0.411, data_time: 0.009, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
2020-05-15 18:48:25,029 - mmdet - INFO - Epoch [1][300/3665]    lr: 0.01197, eta: 7:23:26, time: 0.412, data_time: 0.008, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
2020-05-15 18:48:45,594 - mmdet - INFO - Epoch [1][350/3665]    lr: 0.01397, eta: 7:02:23, time: 0.411, data_time: 0.009, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
2020-05-15 18:49:06,084 - mmdet - INFO - Epoch [1][400/3665]    lr: 0.01596, eta: 6:46:22, time: 0.410, data_time: 0.008, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
2020-05-15 18:49:26,731 - mmdet - INFO - Epoch [1][450/3665]    lr: 0.01796, eta: 6:34:04, time: 0.413, data_time: 0.009, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
2020-05-15 18:49:47,245 - mmdet - INFO - Epoch [1][500/3665]    lr: 0.01996, eta: 6:23:59, time: 0.410, data_time: 0.009, memory: 6326, loss_cls: 0.0000, los
s_bbox: 0.0000, loss: 0.0000
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Hi @lji72 ,
Could you try the original config that has batch size=2 for each GPU? I run the original config yesterday and meet no bug. I will try your case by only changing `samples_per_gpu=4`

**Comment by lji72** [comment]
@ZwwWayne I would have a try. but bacth-size cannot have such affection on model training.

**Comment by edwardyangxin** [comment]
same error I mentioned in #2653.

**Comment by ZwwWayne** [comment]
These are two different problems with yours @edwardyangxin . Yours is about change num_classes and @lji72 's is simple the error in retinanet. If @lji72 uses the original config or only change the `samples_per_gpu` from 2 to 4, the bug is very wierd because I ran the same config many times and meet no bug.

**Comment by ZwwWayne** [comment]
Hi @lji72 
What is your version of MMDet, I did not find the commit ID from your bug report.

**Comment by lji72** [comment]
I get mmdetection-master.zip by downloading. It's mmdetection2.0. If you don't meet the bug, it's quite strange.

**Comment by ZwwWayne** [comment]
Hi @lji72 ,
Could you use the newest master and try again? You can use git clone and install a new MMDet.
