### ISSUE TITLE
How to export trained model?

### ISSUE THREAD

**Issue by i-m-vivek** [open-mmlab/mmdetection#2731]
Hi, I want to ask to know how we can export a trained model, I have a custom dataset, I want to use the pretrained model on that custom dataset to finetune the model after that I want to export the fin-tuned model.

**Comment by ZwwWayne** [comment]
To finetune the model, this [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/finetune.md) could help you.
To export the model, `publish_model.py` could help you.
