### ISSUE TITLE
guided anchor

### ISSUE THREAD

**Issue by hust-kevin** [open-mmlab/mmdetection#274]
hey! will guided anchor code release in this repository ?

**Comment by hellock** [comment]
Yes it will be released in this repo. Perhaps by the end of March because currently we do not have the time to work on it.

**Comment by hust-kevin** [comment]
thanks!
I have two question abou the paper
1. you always emphasize that anchor should be alignment and consistency,but i don't understand it clearly，Is there any research or experiment about it?
2.the anchor shape (w,h) seems is predifined ,not learned by network?

**Comment by hust-kevin** [comment]
what's more, when I train ssd, I meet the problem,can you tell me how to solve it? thanks

![image](https://user-images.githubusercontent.com/23699630/51439242-5083f780-1cf2-11e9-9011-769043460aa1.png)

**Comment by yhcao6** [comment]
I just test it no problem, have you modified something?

**Comment by hellock** [comment]
@hust-kevin You need to update mmcv to the latest version to use more pretrained models. For the guided anchoring paper, it may not be proper for open discussion currently since it is under review. You can send emails and we will reply to the questions.
