### ISSUE TITLE
Stop mmdetection from "re-import files"

### ISSUE THREAD

**Issue by twangnh** [open-mmlab/mmdetection#2741]
As posted by https://github.com/open-mmlab/mmdetection/issues/2593, The multiprocessing mode is set to spawn, so mmdetection would reimport files after every epoch, but if we modify the code base, for example, remove some functions, then a running code will fail to import the functions when the epoch ended, how to cope with this problem? Thanks!

**Comment by ZwwWayne** [comment]
Actually, if you do not use multiprocessing, high-version python seems still re-import files when the program is running. Cloneing a new MMDetection and developing on that codebase could solve this.

**Comment by hellock** [comment]
There is no way to `Stop mmdetection from "re-import files"`, since it is a designed feature of pytorch's distributed training. When you use other codebases based on distributed training, they also `reimport files` for new epochs. The best practice is to use multiple copies (folders) for different experiments.

**Comment by twangnh** [comment]
@ZwwWayne, @hellock ,thanks, does this only affect data loader? i.e., it would not affect code for model?

**Comment by ZwwWayne** [comment]
Hi @twangnh ,
It affects not only data loader, but also models and core logic.

**Comment by twangnh** [comment]
But I'm really confused, currently, I'm running multiple experiments simultaneously in a single project directory, with git to switch between different experiment branch, git can only stay on one branch, but this problem only happen if I switch to a branch that has not created the model file (eg, xxx.py). If it reloads everything, then currently every previous runs with different model setting (e.g, one more conv) would fail after re-import different model file, but this does not happen

**Comment by ZwwWayne** [comment]
It does not reload the config, because the config is not imported. For detail on a deeper level, I do not know either, you can google.

**Comment by twmht** [comment]
try to remove `spawn`  in mmcv (https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/dist_utils.py#L17) would work.
