### ISSUE TITLE
why mAP score is different with tools/test.py and out file

### ISSUE THREAD

**Issue by HotaekHan** [open-mmlab/mmdetection#2746]
Hello :)

I ran tools/test.py and got the result file using --out option.
I have 0.739 for VOC Pascal 07 test set from tools/test.py.
However convert pickle file to txt and ran my evaluation code for mAP, I got the 0.669.

well..I have double check for my evaluation code. 
And I thought output file from --out option seems to not apply nms. exist very much overlapped boxes.
what is the procedure for test in the tools/test.py? is apply the nms? or exist confidence threshold?

**Comment by ZwwWayne** [comment]
Did you do some quantization when converting pickle file to txt format?
tools/test.py does model inference, so it does NMS, but the dumped pickle file should be the results directly used for evaluation.

So you may also check your evaluation code.

**Comment by HotaekHan** [comment]
@ZwwWayne Thanks for your comment :)

yea, I did some quantization to convert uint8 type. but there is no change for the result when i remove it.

I have tried again with configs/pascal_voc/ssd300_voc0712.py. no change in the config file except for batch size.

after training, using tools/test.py for evaluation.
`python tools/test.py configs/pascal_voc/ssd300_voc0712.py /work_dirs/epoch_24.pth --out /work_dirs/results.pkl --eval mAP`
I got 0.778 for mAP from the terminal.

And convert dumped pickle to txt format.
```
pkl_path = '/work_dirs/results.pkl'

data_list = list()
with open(pkl_path, 'rb') as file:
    while True:
        try:
            data = pickle.load(file)
        except EOFError:
            break
        data_list.append(data)

num_img = len(data_list[0])

for iter_img in tqdm(range(num_img)):
    img_results = data_list[0][iter_img]
    out_file = get_filename(iter_img, test_files)
    boxes = list()
    scores = list()
    labels = list()

    for iter_class in range(num_classes):
        bboxes = img_results[iter_class]

        if len(bboxes) > 0:
            num_bboxes = len(bboxes)
            for iter_box in range(num_bboxes):
                bbox = bboxes[iter_box]
                class_name = CLASSES[iter_class]
                xmin = bbox[0]
                ymin = bbox[1]
                xmax = bbox[2]
                ymax = bbox[3]
                confidence = float(bbox[4])

                boxes.append([xmin, ymin, xmax, ymax])
                scores.append(confidence)
                labels.append(iter_class)
```
And ran my evaluation code, I got the 0.7056.
Also I ran the other evaluation code(https://github.com/Cartucho/mAP), and i got the 0.7071. similar with my result.

As my thought, dumpled pickle file is weird because there is so many overlapped box.
for example, the result of 000013.jpg is
```
cow 0.9528617262840271 298 157 436 248
sheep 0.4322863817214966 296 157 432 249
```
it seems to not apply NMS.

which part goes wrong?


Appendix. results of each evaluation code.

1. tools/test.py
+-------------+------+-------+--------+-------+
| class       | gts  | dets  | recall | ap    |
+-------------+------+-------+--------+-------+
| aeroplane   | 285  | 1234  | 0.912  | 0.823 |
| bicycle     | 337  | 1123  | 0.911  | 0.848 |
| bird        | 459  | 2893  | 0.891  | 0.760 |
| boat        | 263  | 3247  | 0.905  | 0.716 |
| bottle      | 469  | 5156  | 0.765  | 0.509 |
| bus         | 213  | 940   | 0.962  | 0.852 |
| car         | 1201 | 5722  | 0.953  | 0.867 |
| cat         | 358  | 1071  | 0.936  | 0.874 |
| chair       | 756  | 8718  | 0.843  | 0.613 |
| cow         | 244  | 991   | 0.951  | 0.833 |
| diningtable | 206  | 1306  | 0.937  | 0.765 |
| dog         | 489  | 1739  | 0.941  | 0.848 |
| horse       | 348  | 1034  | 0.934  | 0.860 |
| motorbike   | 325  | 959   | 0.932  | 0.857 |
| person      | 4528 | 23384 | 0.911  | 0.797 |
| pottedplant | 480  | 5430  | 0.769  | 0.525 |
| sheep       | 242  | 1277  | 0.905  | 0.787 |
| sofa        | 239  | 1094  | 0.946  | 0.803 |
| train       | 282  | 1006  | 0.929  | 0.863 |
| tvmonitor   | 308  | 2049  | 0.912  | 0.754 |
+-------------+------+-------+--------+-------+
| mAP         |      |       |        | 0.778 |
+-------------+------+-------+--------+-------+

2. my evaluation code
AP for aeroplane: 0.7978565593492883
AP for bicycle: 0.7786832571968133
AP for bird: 0.671222933906605
AP for boat: 0.5555157546377121
AP for bottle: 0.38598040419499263
AP for bus: 0.7841689575968207
AP for car: 0.7725650830676921
AP for cat: 0.8854219761237488
AP for chair: 0.47112418936041545
AP for cow: 0.7398244800874506
AP for diningtable: 0.6593967994988152
AP for dog: 0.8338666389785335
AP for horse: 0.8174617087756869
AP for motorbike: 0.8004815022975823
AP for person: 0.7548689999031093
AP for pottedplant: 0.47090083495391577
AP for sheep: 0.6715405384394445
AP for sofa: 0.6904740897402375
AP for train: 0.8520245617935266
AP for tvmonitor: 0.7193053932106794
mAP: 0.7056342331556535

3. https://github.com/Cartucho/mAP
80.05% = aeroplane AP 
77.84% = bicycle AP 
67.35% = bird AP 
55.39% = boat AP 
38.92% = bottle AP 
78.82% = bus AP 
77.45% = car AP 
88.54% = cat AP 
47.37% = chair AP 
74.18% = cow AP 
65.84% = diningtable AP 
83.54% = dog AP 
81.75% = horse AP 
80.12% = motorbike AP 
76.05% = person AP 
47.25% = pottedplant AP 
67.43% = sheep AP 
69.05% = sofa AP 
85.55% = train AP 
71.81% = tvmonitor AP 
mAP = 70.71%

**Comment by HotaekHan** [comment]
@ZwwWayne Hello,
looking for some code snippet.
is this related to this issue?
as my thought, this code allowing multiple matching for one gt box. is this right?

https://github.com/open-mmlab/mmdetection/blob/f745a64d62ff4b7619e1387453168eaea09e19b9/mmdet/core/evaluation/mean_ap.py#L125-L132

**Comment by hellock** [comment]
The above code can achieve the same results as the official matlab code provided by PASCAL VOC devkit.
