### ISSUE TITLE
CPU performance is worse than GPU performance in current 2.0

### ISSUE THREAD

**Issue by CarryHJR** [open-mmlab/mmdetection#2747]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.
3. mmdetection 2.0

**Describe the bug**
CPU performance  is worse than GPU performance

**Reproduction**
first i use cuda to run https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb

then i change it to 
```
model = init_detector(config_file, checkpoint_file, device='cpu:0')
```
the output is the same

but when i test some other images, the outputs are different and the cpu performance is bad,
I use VOC2012 to test, etc.
/VOC2012/JPEGImages/2009_003810.jpg
gpu:
![](https://tva1.sinaimg.cn/large/007S8ZIlly1gewhjy6phhj30l90g2gou.jpg)

cpu:
![](https://tva1.sinaimg.cn/large/007S8ZIlly1gewhkcn5whj30l90g2wh9.jpg)

for these jpgs, the cpu performance is bad and cannot detect valid objects but the gpu performance is good, the error usually happens in detecting large objects.

could you fix this bug?

**Comment by hellock** [comment]
Not sure if it is related to #2754.

**Comment by CarryHJR** [comment]
yes, now it works

**Comment by BerryRB** [comment]
Hi, @CarryHJR  Can you tell me if you recompile the CPU version of mmdetection？Why in [https://github.com/open-mmlab/mmdetection/blob/v2.0.0/setup.py)  I didn't see the changes described in [#2385](https://github.com/open-mmlab/mmdetection/pull/2385/commits/41465c89d97e949c1cb4d329ced37937e8acfff4)？

**Comment by CarryHJR** [comment]
Yes, i  recompile the CPU version of the latest mmdetection, the bug in this issue is caused by the nms implementation, the author has fixed it.

**Comment by BerryRB** [comment]
> Yes, i recompile the CPU version of the latest mmdetection, the bug in this issue is caused by the nms implementation, the author has fixed it.
Can you tell me how to compile the CPU version? I didn't see the CPU changes in [mmdetection 2.0](https://github.com/open-mmlab/mmdetection/blob/v2.0.0/setup.py)) ?

**Comment by CarryHJR** [comment]
emm, i install the cpu version of torch and torchvision, then compile the mmdet.

**Comment by BerryRB** [comment]
Hi, I compiled mmdet as you said, but when I used CPU to predict, I got this error:
'''
No CUDA runtime is found, using CUDA_ HOME='/usr/local/cuda'
'''

Can you use the CPU version of pytorch for normal prediction after compilation?
