### ISSUE TITLE
我已经在win10部署成功并训练( I have successfully deployed in win10 )

### ISSUE THREAD

**Issue by trustguan** [open-mmlab/mmdetection#2748]
Thanks author for the great work, I have successfully deployed in win10 !
You can watch the video in bilibili： https://www.bilibili.com/video/BV1M5411s784/ or in youtube: https://youtu.be/0Y1h-DEm3k4
But the video language is Chinese.

**Comment by ZwwWayne** [comment]
Hi @trustguan ,
Great work!
Would you like to create a PR to contribute documentation about installing mmdet on Windows10?
We lack win10 machines to install and test mmdet for now.

**Comment by OneWorld-github** [comment]
> Thanks author for the great work, I have successfully deployed in win10 !
> You can watch the video in bilibili： https://www.bilibili.com/video/BV1M5411s784/ or in youtube: https://youtu.be/0Y1h-DEm3k4
> But the video language is Chinese.

I would love an English version of this video :-)

**Comment by guotong1988** [comment]
Thank you.
