### ISSUE TITLE
BUG REPORT for mmdetect/core/anchor/anchor_target.py

### ISSUE THREAD

**Issue by Morde-kaiser** [open-mmlab/mmdetection#275]
**RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument  'other'**

When i change num_class in configs/retinanet_r101_fpn_1x.py from 81 to 2. the above error occurs.  This error seems to be caused by focal loss. In mmdetect/core/anchor/anchor_target.py line 150, if label_channels equal 1, labels will not be converted to support focal loss.

**Comment by hellock** [comment]
Thanks for your reporting, we will look into it.

**Comment by hellock** [comment]
Solved in the PR.
