### ISSUE TITLE
centerness loss drops slowly in fcos

### ISSUE THREAD

**Issue by KKKiven** [open-mmlab/mmdetection#2751]
When I training fcos, I found that centerness_loss drops slowly compared with reg_loss and cls_loss. Though it is indeed droping, it seems really slow. Is it the problem of fcos itself or due to code implementation difference? And dose it have bad influence to the final results?

**Comment by ZwwWayne** [comment]
It seems to be the phenomenon caused by FCOS itself. The performance is compatible with the official implementation.
