### ISSUE TITLE
CBNet Integration

### ISSUE THREAD

**Issue by mdv3101** [open-mmlab/mmdetection#2753]
[CBNet: A Novel Composite Backbone Network Architecture for Object Detection](https://aaai.org/Papers/AAAI/2020GB/AAAI-LiuY.1833.pdf) ([Github](https://github.com/VDIGPKU/CBNet#cbnet-a-novel-composite-backbone-network-architecture-for-object-detection)) provides some promising results. Can we provide an integration with mmdetection?

**Comment by hellock** [comment]
Thanks for your proposal. We are currently quite busy developing other planned features, but glad to accept PRs to support it.

**Comment by mdv3101** [comment]
@hellock I will create a PR based on the default code provided by the authors of CBNet. :)

**Comment by kartikJ-9** [comment]
Any update on this? Even I am excited about CBNet integration.

**Comment by rhiver** [comment]
CBNetV2 has the best performance this year. Try to integrate?

**Comment by Ikwus** [comment]
I don't think that cbnetv2 can be easily integrated into mmdet because it uses something called mmcv-custom...
