### ISSUE TITLE
win10, many demo fail

### ISSUE THREAD

**Issue by GreenTeaHua** [open-mmlab/mmdetection#2756]
win10+vs2019+cuda10.1 +cudnn7+git
mmdetection 2.0.
until now,after 24 hours make,
the only work demo is,
 ------------------------------只有下面这句是OK的----
python demo/webcam_demo.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

**Comment by hellock** [comment]
Currently Windows is not officially supported since we do not have any windows servers for developing. Community support is appreciated.

**Comment by sciencestarstar** [comment]
> win10+vs2019+cuda10.1 +cudnn7+git
> mmdetection 2.0.
> until now,after 24 hours make,
> the only work demo is,
> ------------------------------只有下面这句是OK的----
> python demo/webcam_demo.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
> checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

同学，请问win10下如何安装2.0版本

**Comment by ZwwWayne** [comment]
Too old to track.
