### ISSUE TITLE
Urls for mirror of model zoo on Aliyun

### ISSUE THREAD

**Issue by fly2leoo** [open-mmlab/mmdetection#2757]
The doc of [model zoo](https://mmdetection.readthedocs.io/en/latest/model_zoo.html) said '
We use AWS as the main site to host our model zoo, and maintain a mirror on aliyun. You can replace ```https://s3.ap-northeast-2.amazonaws.com/open-mmlab``` with ```https://open-mmlab.oss-cn-beijing.aliyuncs.com``` in model urls.
'

However, the download url I got from model zoo looks like 'https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'. There is no ```https://s3.ap-northeast-2.amazonaws.com/open-mmlab``` in the url.

So, what is the corresponding aliyun url?

**Comment by ZwwWayne** [comment]
Hi @fly2leoo ,
Thanks for your remind.
We have not finished mirror models from AWS to aliyun. We will let you know once the mirroring process is done.

**Comment by guotong1988** [comment]
Same question.

**Comment by sphcn** [comment]
Same question.
