### ISSUE TITLE
Repeat anchor generation operation

### ISSUE THREAD

**Issue by destinyzs** [open-mmlab/mmdetection#276]
In [anchor_head.py](mmdetection/mmdet/models/anchor_heads/anchor_head.py), the anchor generation operation has been performed twice at [get_bboxes](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L215-L217) and [get_anchors](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L106-L107), i think a cache can be set to temporarily store anchor to reduce repeated operations, like [here](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L2603-L2604)

**Comment by hellock** [comment]
Thanks for the advice. We call `grid_anchors()` independently for training and inference to make the code more simple. In your referred repo, the anchor generation operation is implemented with numpy, while we implement it with GPU ops, so the speed is very fast. Using cache will not bring speedups and will require more GPU memory.

**Comment by destinyzs** [comment]
Thanks a lot!  Life is short, use GPU~
