### ISSUE TITLE
When to add FPG？

### ISSUE THREAD

**Issue by anonymoussss** [open-mmlab/mmdetection#2765]
Hi, chen,
      I have just read your paper _Feature Pyramid Grids_  on arxiv,  do you want to add your work  into mmdetection recently?

**Comment by ZwwWayne** [comment]
The code will be released when it is ready.

**Comment by zehuichen123** [comment]
@hellock. Hello! could you explain the exact differences between `Pyramid` and `pathways`, since this sentence confused me a lot...
> BN statistics are synchronized across GPUs for the
Pyramid, and frozen in the ImageNet pre-trained backbone, pathways.
