### ISSUE TITLE
Is it possible to test custom pipelines?

### ISSUE THREAD

**Issue by RocketFlash** [open-mmlab/mmdetection#2766]
Hi! I created custom pipeline using [this tutorial](https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html) and now I want to test it somehow. Is it possible to visualize images and boxes after passing my pipeline?

**Comment by ZwwWayne** [comment]
It is possible, for example, save the output after finish your pipeline at the end of the `__call__` function. But we do not support this in the code since the use case is rare.
