### ISSUE TITLE
Why is the anchor different from the official code？ with same scale（8，16，32）、base_size(16)

### ISSUE THREAD

**Issue by hitlxm** [open-mmlab/mmdetection#277]
![image](https://user-images.githubusercontent.com/32316210/51468695-8edced80-1daa-11e9-8bc4-6ce2c7ca182b.png)
official: https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/rpn/generate_anchors.py
![image](https://user-images.githubusercontent.com/32316210/51468777-b7fd7e00-1daa-11e9-8be5-565a1e7ef48f.png)
with same scale（8，16，32）、base_size(16) 、ratio（0.5，1.，2）

**Comment by hitlxm** [comment]
Thanks i got it !
 i think your method maybe is better than the source methed.
 another question: any materials can help me understand  below code? i am confused with it ?emmmmmm........
https://github.com/open-mmlab/mmdetection/blob/f3a939fa697ce23d8a6435b59529791002f64fdf/mmdet/core/anchor/anchor_generator.py#L53

**Comment by Eniac-Xie** [comment]
Hi, in anchor_generator.py, I found the center of the base anchor is calculated as:
`        w = self.base_size
        h = self.base_size
        if self.ctr is None:
            x_ctr = 0.5 * (w - 1)
            y_ctr = 0.5 * (h - 1)
        else:
            x_ctr, y_ctr = self.ctr`
why not
`x_ctr, y_ctr = 0, 0`
?

**Comment by hellock** [comment]
@Eniac-Xie The center of anchors is aligned with the center of corresponding feature map pixel.
