### ISSUE TITLE
model training is not reproducible

### ISSUE THREAD

**Issue by aabramovrepo** [open-mmlab/mmdetection#2773]
Hi All,

   first of all many thanks for making this project available! I have a question regarding reproducibility of training results. I'm training Faster-RCNN model on the PASCAL VOC data set. However, despite setting a `seed` and setting `deterministic=True` by:

`python tools/train.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py --seed 100 --deterministic --gpu-ids 0`

I get different results every time. In all my own PyTorch projects setting a random seed always led to deterministic results (exactly the same number after every run).

[#2558](https://github.com/open-mmlab/mmdetection/issues/2558l) does not help further
[#1206](https://github.com/open-mmlab/mmdetection/issues/1206) has the same issue

Many thanks in advance for your help!

Best,
Alexey

**Comment by ZwwWayne** [comment]
Hi @aabramovrepo ,
Could you also report the AP of these runs?

**Comment by aabramovrepo** [comment]
@ZwwWayne sure, here are the 4 mAPs obtained with the command above: `0.6258`, `0.6283`, `0.6226`, `0.6197`.

**Comment by ZwwWayne** [comment]
Hi @aabramovrepo ,
I also try to run the same config for four times, and obtain 0.8086, 0.7974, 0.7985, and 0.8009 AP.  So it seems that the performance on VOC is indeed more unstable than the detectors on COCO dataset.

**Comment by aabramovrepo** [comment]
@ZwwWayne thanks for the response, what are actually the reasons for different outcomes using a fixed seed from your point of view?

**Comment by ZwwWayne** [comment]
I am not sure, maybe because the dataset is small.

**Comment by LMerCy** [comment]
> I am not sure, maybe because the dataset is small.

It's not about dataset, what we want to know is where dese the random come from, which will be good for debugging.
