### ISSUE TITLE
misleading docstring

### ISSUE THREAD

**Issue by qianyizhang** [open-mmlab/mmdetection#278]
In the core/bbox/geometry.py  bbox_overlaps
 Returns:
        ious(Tensor): shape (n, k) if is_aligned == False else shape (n, 1)

**should be** 
 ious(Tensor): shape (m, n) if is_aligned == False else shape (n, 1)

Also in the bbox/assigners/max_iou_assigner.py  assign_wrt_overlaps
 Args:
            overlaps (Tensor): Overlaps between n bboxes and k gt_bboxes,
                shape(n, k).
            gt_labels (Tensor, optional): Labels of k gt_bboxes, shape (k, ).

**should be**
overlaps (Tensor): Overlaps between k gt_bboxes and n bboxes 
                shape(k, n).

**Comment by hellock** [comment]
Fixed in #279
