### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LYKlyk** [open-mmlab/mmdetection#2781]
File "/mmdetection/mmdet/datasets/coco.py", line 182, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

I try to use my own dataset, and it has only one category. What should I do if I follow the example provided to make changes but the above errors occur?

**Comment by ZwwWayne** [comment]
You need to change num_classes in the head. And maybe set the classes of the dataset. See tutorials [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_dataset.md).

**Comment by lingchen1991** [comment]
> You need to change num_classes in the head. And maybe set the classes of the dataset. See tutorials [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_dataset.md).

Same issue here. Note that "MyDataset" class has been customized and "num_classes" has been set correspondingly without counting background.

**Comment by sunnyisabaster** [comment]
> You need to change num_classes in the head. And maybe set the classes of the dataset. See tutorials [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_dataset.md).

I changed them all in the config file, but also occurred this problem.

**Comment by sky-fly97** [comment]
> > You need to change num_classes in the head. And maybe set the classes of the dataset. See tutorials [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_dataset.md).
> 
> I changed them all in the config file, but also occurred this problem.

Have you solved the problem? I meet the problem too!Thanks!

**Comment by OOIIps** [comment]
@sky-fly97  I have same error. How do you fix this problem ?

**Comment by sky-fly97** [comment]
> @sky-fly97 I have same error. How do you fix this problem ?

I think it may be the index problem of class.

**Comment by Loovelj** [comment]
In mmdetection/mmdet/core/evaluation/class_names.py, line 67 ,when I use coco style data, I changed the coco_classes() to my data classes，it sloved

**Comment by markproy** [comment]
I still get this error after changing model.roi_head.bbox_head.num_classes=200 . It's interesting to hear that changing coco_classes() fixes the problem for some, but that's not an acceptable solution. Can anyone point to a working solution for fine-tuning or training with a completely custom dataset that does not change mmdetection code? Note I'm using the Faster R CNN implementation.

**Comment by WWaynee** [comment]
I met the error as well... I have modified the "num_classes" in the configs directory but it is still the same error, I don't know why

**Comment by USTC-wlsong** [comment]
> I met the error as well... I have modified the "num_classes" in the configs directory but it is still the same error, I don't know why

i have solved this problem. you can see https://www.codenong.com/cs107067843/

**Comment by faithfulnguyen** [comment]
I got the same problem and I looked into the code coco_metric.py 

line 419 .
```
 # handle lazy init
        if self.cat_ids is None:
            self.cat_ids = self._coco_api.get_cat_ids(
                cat_names=self.dataset_meta['classes'])
```
this is the way cat_ids  init.
fast way to fix this is to replace the line  
```
#self.cat_ids = None
```
by
```
self.cat_ids = self._coco_api.get_cat_ids()
```
and in your anno.json  file should contain a background class in the field ` categories`.

**Comment by WWaynee** [comment]
收到了惹，啾咪~

**Comment by HosseinSheikhi** [comment]
for me the problem was that the order of categories in classes passed to coco and the cat in annotation file was not matched.

**Comment by WWaynee** [comment]
收到了惹，啾咪~
