### ISSUE TITLE
DataContainer error at training stage

### ISSUE THREAD

**Issue by bailiqun** [open-mmlab/mmdetection#2782]
When I train singlesStageDetector like SSD, dataloader with pipline DefaultFormatBundle.
dataloader output list of DataContainer object., then these DC object go to function forward_train()
in SingleStageDetector. 
forward_train(img) img should be _torch.Tensor_ type but got _DC_ type

TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not DataContainer

any solutions?

![image](https://user-images.githubusercontent.com/7125779/82519071-60fcea00-9b53-11ea-8dd0-32a98fa94b5a.png)
![image](https://user-images.githubusercontent.com/7125779/82519115-7ffb7c00-9b53-11ea-89d0-12af78fa6512.png)
![image](https://user-images.githubusercontent.com/7125779/82519155-96a1d300-9b53-11ea-8577-70c52fae9296.png)

**Comment by ZwwWayne** [comment]
It seems that your model is not encapsulated by either `DistributedDataParallel` or `DataParallel`.

**Comment by bailiqun** [comment]
I use DataParallel in pytorch, when I change to mmcv.parallel.MMDataParallel back to norm~ 
Thanks.

**Comment by guotong1988** [comment]
Thank you!
