### ISSUE TITLE
A problem about how to set "num_class"

### ISSUE THREAD

**Issue by LYKlyk** [open-mmlab/mmdetection#2791]
In the mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py, We can find "num_class". I found that it is set to 80 instead of 81. Do we need to set it to "category quantity + 1" when setting? If I only have class 1 objects, what should I set this property（num_class） to? Is it 1 or 2?

**Comment by duanyuqi987** [comment]
(i think) If you only have class 1 objects, you set this property（num_class）to 1

**Comment by ZwwWayne** [comment]
Please see the [compatibility.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md), if your number of classes is 1, then num_class is 1.
