### ISSUE TITLE
demo time slower than test.py time

### ISSUE THREAD

**Issue by zhang1992wen1023** [open-mmlab/mmdetection#2792]
A difference between image_demo.py and test.py 
On my titan XP,
Faster Rcnn , 
when I run test.py , I get  10 task/s,which means detect a image needs 0.1s,
when I run  image_demo.py , I need 0.26s or more to detect a image,
what is the difference between these two files?
How to solve this question?

**Comment by ZwwWayne** [comment]
If you take a deeper look into the code, you will find that the image demo plot results as default while test.py usually do not plot.
