### ISSUE TITLE
Why were the parameters bias_lr_mult and bias_lr_decay set in FCOS?

### ISSUE THREAD

**Issue by cizhenshi** [open-mmlab/mmdetection#2794]
I noticed that there was a 0.3 point gap if it wasn't set. Is this a general trick, or does it only work for FCOS?

**Comment by ZwwWayne** [comment]
It is an old trick now only adopted in several models, such as in FCOS, though it should be no longer necessary after we change some other hyperparameters. We will also update the performance of FCOS without using these tricks when the ablation study is done in the near future.
