### ISSUE TITLE
"cascade_rcnn_r50_fpn_1x_coco_20200317-0b6a2fbf.pth is not a checkpoint file"

### ISSUE THREAD

**Issue by CarryHJR** [open-mmlab/mmdetection#2795]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

R-50-FPN | pytorch | 1x - checkpoint is still 1.0, when i use mmdet 2.0, i get the error 
"cascade_rcnn_r50_fpn_1x_coco_20200317-0b6a2fbf.pth is not a checkpoint file"
the other model file works, just this didn't work.

and i view the log file https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco/cascade_rcnn_r50_fpn_1x_coco_20200316_214748.log.json

it shows this model file is generated by mmdet 1.0

please upload the latest 2.0 model file, thanks alot

**Comment by yhcao6** [comment]
I can download `cascade rcnn r50 fpn 1x coco` directly by clicking the URL in README.md.
Could you have a try on this link https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco/cascade_rcnn_r50_fpn_1x_coco_20200316-3dc56deb.pth again?

Some models are trained before mmdet v2.0 release. So the version may not be updated.

**Comment by zehuichen123** [comment]
Same problem encountered when I am trying to load model from `res2net101_v1d_26w_4s_mmdetv2-f0a600f9.pth` provided by https://open-mmlab.s3.ap-northeast-2.amazonaws.com/pretrain/third_party/res2net101_v1d_26w_4s_mmdetv2-f0a600f9.pth. Actually, mmcv(version==0.5.5) raised `KeyError: 'res2net101_v1d_26w_4s'` if I directly set `pretrained='open-mmlab://res2net101_v1d_26w_4s',`
