### ISSUE TITLE
 Is there a similar function for mmdetection?

### ISSUE THREAD

**Issue by FuJ1aHu1** [open-mmlab/mmdetection#2799]
After I play the target detection training, I want to get the detected data like this format.May I use a certain API of mmdetection to achieve this function?
![1](https://user-images.githubusercontent.com/55631381/82661097-f4224680-9c5d-11ea-9c40-38e8c5843a3d.png)
Each row represents the Class, ROI and position of the box.
Or generate a similar xml file

**Comment by ZwwWayne** [comment]
See example 4 in the [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md), you can use the dumped pkl and convert the results to txt format.
