### ISSUE TITLE
Order of dcn offsets

### ISSUE THREAD

**Issue by MauroPfister** [open-mmlab/mmdetection#2801]
Hi

Given a deformable convolution with `kernel_size = 3` and `deform_groups = 1` the predicted offsets are a tensor of size `[batches, 18, h, w]`. How are the offsets structured in dimension 1 of this tensor? Is it `[x0, y0, x1, y1, x2, y2, ...., x8, y8]` or `[x0, x1, ..., x8, y0, y1, ..., y8]` or something else? And how do the offsets correspond to the weights in the kernel? Intuitively I would guess the order below, but could you confirm this?
```
(x0, y0) (x1, y1) (x2, y2)
(x3, y3) (x4, y4) (x5, y5)
(x6, y6) (x7, y7) (x8, y8)
```

I'm aware that issue #2504 is very similar. However, it only discussed the case for `kernel_size = 1`. That's why I opened another one.

Thanks for the help!

**Comment by xvjiarui** [comment]
Hi @MauroPfister 
The offset is also column first. Your order should be transposed.

**Comment by MauroPfister** [comment]
Hi @xvjiarui 

Thanks for the reply. I'm still unsure about the offset tensor structure though. Could you tell me explicitly if it is one of the following options or something different?

1. `[y0, x0, y1, x1, y2, x2, ..., y8, x8]`
2. `[y0, y1, ... , y8, x0, x1, ..., x8]`

Also, could you show precisely the spatial arrangement of the offsets with a matrix (like I tried to illustrate in my first post)?

Thanks a lot! I think this will also help other people when analyzing the offsets to see what the dcn is learning.

**Comment by xvjiarui** [comment]
Hi @MauroPfister 
The offset tensor is like `[y0, x0, y1, x1, y2, x2, ..., y8, x8]`.

The spatial arrangement is like:
```
(x0, y0) (x1, y1) (x2, y2)
(x3, y3) (x4, y4) (x5, y5)
(x6, y6) (x7, y7) (x8, y8)
```

**Comment by MauroPfister** [comment]
Perfect, thanks a lot! =)
