### ISSUE TITLE
您好 我们的数据集图片全部是1024*1024的 多尺度测试报错

### ISSUE THREAD

**Issue by kiddliao** [open-mmlab/mmdetection#2803]
我们在mmdet2.0上进行了多尺度训练,然后多尺度测试的时候报错(单尺度测试没有任何问题)
![image](https://user-images.githubusercontent.com/57079702/82749453-eabee880-9ddb-11ea-9e7c-9c0dc8d02f54.png)
我不知道是不是多尺度测试这么写就可以,我们多尺度训练就是这个写法
![image](https://user-images.githubusercontent.com/57079702/82749476-17730000-9ddc-11ea-9d17-9725ac7fe86c.png)

我们在mmdet1里这样训练和多尺度测试没有报错 但是在2中出现了这个问题
还有个问题 
想问问您对于同样尺寸的数据集,多尺度训练和多尺度测试有用吗?
还有如果想最后用多尺度测试,就必须用多尺度训练嘛

**Comment by asdiuzd** [comment]
You can fix it via https://github.com/open-mmlab/mmdetection/issues/2804#issue-623821376

**Comment by kiddliao** [comment]
> You can fix it via [#2804 (comment)](https://github.com/open-mmlab/mmdetection/issues/2804#issue-623821376)

谢谢 已经解决
想问问您对于同样尺寸的数据集,多尺度训练和多尺度测试有用吗?
还有如果想最后用多尺度测试,就必须用多尺度训练嘛

**Comment by hellock** [comment]
- Please use English or English&Chinese for issues.
- Please use `Error template` to report errors.

Multi-scale training is not independent of multi-scale testing.
