### ISSUE TITLE
bbox vertical flip is not handled correctly when aug test

### ISSUE THREAD

**Issue by asdiuzd** [open-mmlab/mmdetection#2805]
The vertical flip process is the same as the horizontal flip.
If I set random vertical flip, bbox transform in mmdet/core/bbox/transforms.py handle the vertical flip via horizontal flip.

def bbox_flip(bboxes, img_shape):
    """Flip bboxes horizontally.

    Args:
        bboxes(Tensor or ndarray): Shape (..., 4*k)
        img_shape(tuple): Image shape.

    Returns:
        Same type as `bboxes`: Flipped bboxes.
    """
    if isinstance(bboxes, torch.Tensor):
        assert bboxes.shape[-1] % 4 == 0
        flipped = bboxes.clone()
        flipped[:, 0::4] = img_shape[1] - bboxes[:, 2::4]
        flipped[:, 2::4] = img_shape[1] - bboxes[:, 0::4]
        return flipped
    elif isinstance(bboxes, np.ndarray):
        return mmcv.bbox_flip(bboxes, img_shape)

def bbox_mapping(bboxes, img_shape, scale_factor, flip):
    """Map bboxes from the original image scale to testing scale"""
    new_bboxes = bboxes * bboxes.new_tensor(scale_factor)
    if flip:
        new_bboxes = bbox_flip(new_bboxes, img_shape)
    return new_bboxes

def bbox_mapping_back(bboxes, img_shape, scale_factor, flip):
    """Map bboxes from testing scale to original image scale"""
    new_bboxes = bbox_flip(bboxes, img_shape) if flip else bboxes
    scale_factor = new_bboxes.new_tensor(scale_factor)
    new_bboxes = (new_bboxes.view(new_bboxes.size(0), -1, 4) / scale_factor).view(
        new_bboxes.size()[0], -1)
    # print(new_bboxes.shape, new_bboxes.new_tensor(scale_factor))
    # new_bboxes = new_bboxes / new_bboxes.new_tensor(scale_factor)
    return new_bboxes

I find another bbox transform in mmdet/datasets/pipelines/transforms.py is correct.

def bbox_flip(self, bboxes, img_shape, direction):
        """Flip bboxes horizontally.

        Args:
            bboxes(ndarray): shape (..., 4*k)
            img_shape(tuple): (height, width)
        """
        assert bboxes.shape[-1] % 4 == 0
        flipped = bboxes.copy()
        if direction == 'horizontal':
            w = img_shape[1]
            flipped[..., 0::4] = w - bboxes[..., 2::4]
            flipped[..., 2::4] = w - bboxes[..., 0::4]
        elif direction == 'vertical':
            h = img_shape[0]
            flipped[..., 1::4] = h - bboxes[..., 3::4]
            flipped[..., 3::4] = h - bboxes[..., 1::4]
        else:
            raise ValueError(f"Invalid flipping direction '{direction}'")
        return flipped

**Comment by yhcao6** [comment]
`bbox_flip` in mmdet/core/transform.py only deals with horizontally flip. Please read the doc carefully. You can implement the vertical flip by yourself. It should be very easy.

**Comment by xvjiarui** [comment]
Hi @asdiuzd 
Thanks for reporting. I will create a PR to fix this bug.
