### ISSUE TITLE
Typeerror:__init__() got an unexpected keyword argument 'bbox_roi_extractor'

### ISSUE THREAD

**Issue by rusanager** [open-mmlab/mmdetection#2807]
Hello!
Thank you for your work!
I installed mmdetection, but when I try to start the prediction I get an error ```__init__() got an unexpected keyword argument 'bbox_roi_extractor```
I tried using a docker file, but I get the same result.

**Reproduction**
1. What command or script did you run?
```init_detector```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
MaskRCNN
**Environment**
```sys.platform: linux
Python: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GRID M60-1Q
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.5.0+cu100
OpenCV: 4.2.0
MMCV: 0.5.5
MMDetection: 2.0.0+9f8c002
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1
```
**Error traceback**
```
  File "/home/docker/web/utils/recognition.py", line 110, in getResult
    model = init_detector(config_fname, checkpoint_file)
  File "/home/docker/mmdetection/mmdet/apis/inference.py", line 33, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/docker/mmdetection/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/docker/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'bbox_roi_extractor'
```

**Comment by kbiyani33** [comment]
Hey, I had faced the same error yesterday. You might have to upgrade mode version. Since the config file is not having the same structure. 
Please try running:
python setup.py develop
It has been suggested in #1860

**Comment by rusanager** [comment]
> Hey, I had faced the same error yesterday. You might have to upgrade mode version. Since the config file is not having the same structure.
> Please try running:
> python setup.py develop
> It has been suggested in #1860

I saw this issue. I cloned a new version of mmdetection and ran `python setup.py develop` in mmdetection directory. I can't get rid of the error.
Also docker file exists cloning last version and installation. I don't get errors when I build docker, but I got this runtime error.
Should I retrain my neural network on a new version mmdetection if the configuration file structure has changed? My network was trained a few months ago.

**Comment by kbiyani33** [comment]
Do you mind giving the training command you used?? 

Earlier the mistake I was doing was that I was giving a config for GCNet from the GCNet repo instead of the modest repo. The versions are different. That's when I got exactly the same error as in w.r.t bb_roi_extractor being an unexpected keyword.

**Comment by hellock** [comment]
You need to modify the config files according to the new structure, and then upgrade your model following the [documentation](https://mmdetection.readthedocs.io/en/latest/compatibility.html#upgrade-models-from-1-x-to-2-0).

**Comment by rusanager** [comment]
Thanks for your help! I used old config file. After updating config file, error disappeared.

**Comment by Sencc** [comment]
I encountered similar problems because the project versions were different and some parameters had different names. The solution was to compare the config file with the old version and modify those new parameters.

**Comment by dtlam26** [comment]
Thank you guys, Editing the config files solves the version migration

**Comment by Tanmaypal** [comment]
> You need to modify the config files according to the new structure, and then upgrade your model following the [documentation](https://mmdetection.readthedocs.io/en/latest/compatibility.html#upgrade-models-from-1-x-to-2-0).

Hi Hellock...when I tried to update the model version using this command "!python /content/mmdetection/tools/model_converters/upgrade_model_version.py --num-classes 1  /content/rpn_r101_fpn_1x_20181129-f50da4bd.pth  /content/work_dirs/faster_rcnn_r101_fpn_1x"

i am getting this error


Traceback (most recent call last):
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 209, in <module>
    main()
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 205, in main
    convert(args.in_file, args.out_file, args.num_classes)
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 126, in convert
    '#' + meta_info['config'])
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 36, in parse_config
    elif isinstance(config.model['bbox_head'], list):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 32, in __missing__
    raise KeyError(name)
KeyError: 'bbox_head'


plz help me resolve this.

**Comment by Tanmaypal** [comment]
> You need to modify the config files according to the new structure, and then upgrade your model following the [documentation](https://mmdetection.readthedocs.io/en/latest/compatibility.html#upgrade-models-from-1-x-to-2-0).

Hi @hellock ...when I tried to update the model version using this command "!python /content/mmdetection/tools/model_converters/upgrade_model_version.py --num-classes 1 /content/rpn_r101_fpn_1x_20181129-f50da4bd.pth /content/work_dirs/faster_rcnn_r101_fpn_1x"

i am getting this error

Traceback (most recent call last):
File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 209, in
main()
File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 205, in main
convert(args.in_file, args.out_file, args.num_classes)
File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 126, in convert
'#' + meta_info['config'])
File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 36, in parse_config
elif isinstance(config.model['bbox_head'], list):
File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 32, in missing
raise KeyError(name)
KeyError: 'bbox_head'

plz help me resolve this.

**Comment by wulala-max** [comment]
Hello!
Thank you for your work!
I installed and modify mmdetection, but when I try to start the train I get an error:TypeError: FasterRCNN: __init__() got an unexpected keyword argument 'bbox_roi_extractor',I want to try to upgrade your model ,but i don't know how to use tools/converters_version.py ,what the parameter,and what can it do 

Traceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 117, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/vipuser/Desktop/mmdetection/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/vipuser/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/vipuser/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/vipuser/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FasterRCNN: __init__() got an unexpected keyword argument 'bbox_roi_extractor'
