### ISSUE TITLE
List has no attribute shape. Cascade Mask RCNN error after training

### ISSUE THREAD

**Issue by kartikJ-9** [open-mmlab/mmdetection#2818]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

Hello. I am implementing this on Colab. Model training is done and the .pth file is generated. But there is some issue in the bounding box creation in the images. This is happening for Cascade Mask RCNN 101 64x64 fpn1x model. 

Following error shows up :

AttributeError: 'list' object has no attribute 'shape'

**Comment by yhcao6** [comment]
Please fill the placeholder in the error template to provide us more detailed information. So that we can better help you.
