### ISSUE TITLE
Could you give a BaiduYun download url ?

### ISSUE THREAD

**Issue by SHU-FLYMAN** [open-mmlab/mmdetection#282]
It really really slow in chinese when download the weights from amazonaws. Could you give a BaiduYun url.

**Comment by hellock** [comment]
We will maintain a mirror of the model zoo on aliyun. Just replace `https://s3.ap-northeast-2.amazonaws.com` in the urls with `https://open-mmlab.oss-cn-beijing.aliyuncs.com`. (currently not available)

**Comment by SHU-FLYMAN** [comment]
Thank you!

**Comment by jianlong-yuan** [comment]
https://open-mmlab.oss-cn-beijing.aliyuncs.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
This XML file does not appear to have any style information associated with it. The document tree is shown below.
 This url is not ready

**Comment by hellock** [comment]
You used the wrong url. The following link is accessible.
https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth

**Comment by heqinglin336** [comment]
hi，this way didn't  work，such as https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth

**Comment by heqinglin336** [comment]
> Sorry that the above info is wrong. You need to replace `https://s3.ap-northeast-2.amazonaws.com/open-mmlab` in the urls with `https://open-mmlab.oss-cn-beijing.aliyuncs.com`. The following link is accessible.
> https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth

hi，this way didn't work，such as https://open-mmlab.oss-cn-beijing.aliyuncs.com/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
