### ISSUE TITLE
soft nms

### ISSUE THREAD

**Issue by abcxs** [open-mmlab/mmdetection#2823]
How much effect soft NMS has improved. I used it on retinaNet and got only 0.1%, is that normal？

**Comment by xvjiarui** [comment]
Hi @abcxs 
I will update a comparison table later. Btw, are you using the default hyper parameter for soft nms?

**Comment by abcxs** [comment]
yes, just like this
![image](https://user-images.githubusercontent.com/13503336/83379434-165e5600-a40e-11ea-9d30-9ee82b6441b0.png)
