### ISSUE TITLE
The evaluation does not work

### ISSUE THREAD

**Issue by hhcahut** [open-mmlab/mmdetection#2829]
I use the pretrained model"mask_rcnn_r50_fpn_1x_cityscapes_20200227-afe51d5a.pth" to test,but it tells me"ERROR: Found no prediction for ground truth /media/wxy/000F8E4B0002F751/SEPC/mmdetection/data/cityscapes/gtFine/test/berlin/berlin_000000_000019_gtFine_instanceIds.png"
the following text are cut from my linux terminal
*****************************************************
python tools/test.py /media/wxy/000F8E4B0002F751/SEPC/mmdetection/configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py /media/wxy/000F8E4B0002F751/SEPC/mmdetection/configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes_20200227-afe51d5a.pth --eval=cityscapes
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1081/1081, 3.3 task/s, elapsed: 328s, ETA: 0s
Evaluating in Cityscapes style
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1081/1081, 3.2 task/s, elapsed: 340s, ETA: 0sEvaluating results under /tmp/tmprpi2chka/results ...
ERROR: Found no prediction for ground truth /media/wxy/000F8E4B0002F751/SEPC/mmdetection/data/cityscapes/gtFine/test/berlin/berlin_000000_000019_gtFine_instanceIds.png

**Comment by xvjiarui** [comment]
Hi @hhcahut 
It seems you are testing on the test set of cityscapes. However, the annotation of test set is not provided. You may change the set to `val` for validation.
