### ISSUE TITLE
I have a question when I train myself vocdata,what's the reason?

### ISSUE THREAD

**Issue by wangduyang** [open-mmlab/mmdetection#283]
2019-01-24 09:56:42,226 - INFO - Start running, host: wang@wang, work_dir: /home/wang/mmcv/mmdetection/tools/work_dirs/faster_rcnn_r50_fpn_1x_voc0712
2019-01-24 09:56:42,226 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "train.py", line 90, in <module>
    main()
  File "train.py", line 86, in main
    logger=logger)
  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmdet-0.5.6+b7aa30c-py3.6.egg/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmdet-0.5.6+b7aa30c-py3.6.egg/mmdet/apis/train.py", line 121, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmcv/runner/runner.py", line 355, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmcv/runner/runner.py", line 257, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmdet-0.5.6+b7aa30c-py3.6.egg/mmdet/datasets/repeat_dataset.py", line 16, in __getitem__\n    return self.dataset[idx % self._ori_len]\n  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmdet-0.5.6+b7aa30c-py3.6.egg/mmdet/datasets/custom.py", line 154, in __getitem__\n    data = self.prepare_train_img(idx)\n  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmdet-0.5.6+b7aa30c-py3.6.egg/mmdet/datasets/custom.py", line 182, in prepare_train_img\n    ann = self.get_ann_info(idx)\n  File "/home/wang/anaconda3/envs/rebar/lib/python3.6/site-packages/mmdet-0.5.6+b7aa30c-py3.6.egg/mmdet/datasets/xml_style.py", line 44, in get_ann_info\n    label = self.cat2label[name]\nKeyError: \'good\'\n'

'good' is my class !
thank you

**Comment by wangduyang** [comment]
Here is my configFile:

# model settings
model = dict(
    type='FasterRCNN',
    pretrained='modelzoo://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        use_sigmoid_cls=True),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=dict(
        type='SharedFCBBoxHead',
        num_fcs=2,
        in_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=2,
        target_means=[0., 0., 0., 0.],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        reg_class_agnostic=False))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        smoothl1_beta=1 / 9.0,
        debug=False),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.2,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.0, nms=dict(type='nms', iou_thr=0.2), max_per_img=250)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)
)
# dataset settings
dataset_type = 'VOCDataset'
data_root = '/home/wang/mmcv/mmdetection/data/VOCdevkit/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',  # to avoid reloading datasets frequently
        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                #data_root + 'VOC2007/ImageSets/Main/trainval.txt',
                data_root + 'VOC2012/ImageSets/Main/trainval.txt'
            ],
            img_prefix=[data_root + 'VOC2012/'],
            img_scale=(1000, 600),
            img_norm_cfg=img_norm_cfg,
            size_divisor=32,
            flip_ratio=0.5,
            with_mask=False,
            with_crowd=True,
            with_label=True)),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2012/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2012/',
        img_scale=(1000, 600),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2012/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2012/',
        img_scale=(1000, 600),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(policy='step', step=[3])  # actual epoch = 3 * 3 = 9
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 12  # actual epoch = 4 * 3 = 12
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/faster_rcnn_r50_fpn_1x_voc0712'
load_from = None
resume_from = None
workflow = [('train', 1)]

**Comment by hellock** [comment]
You need to inherit from VOCDataset and modify the [class names](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/voc.py#L6).

**Comment by wangduyang** [comment]
the class name I have  modified

**Comment by hellock** [comment]
You can print `self.cat2label` to see if it is expected.

**Comment by BboyHanat** [comment]
modify CLASSES = ('good') to CLASSES = ('good',)

**Comment by BboyHanat** [comment]
modify CLASSES = ('.....') to CLASSES = ('good',) in voc.py

**Comment by Yuyang-01** [comment]
i also have this errror: 

File "/home/yuyang/.conda/envs/yuy_py35/lib/python3.5/site-packages/mmdet-0.6rc0+70383d4-py3.5.egg/mmdet/datasets/xml_style.py", line 44, in get_ann_info\n    label = self.cat2label[name]\nKeyError: \'aircraft\'\n'

and i modify CLASSES = ('.....') to CLASSES = ('aircraft',) in voc.py, it still show the same problem??

**Comment by xinetzone** [comment]
i met the same problem,  i have modified the Class names.

**Comment by wizholy** [comment]
i met the same problem, i have modified the Class names.

**Comment by wizholy** [comment]
have you finish it?

**Comment by Yuyang-01** [comment]
I met the same problem and i solved it by the proposals above.

**Comment by revilokeb** [comment]
@xinetzone @wizholy you can set CLASSES=['...'] if you are having only one class, instead of CLASSES=('...')

**Comment by BIGWangYuDong** [comment]
I met the same same question, how can i solve this??

**Comment by GuoxingYan** [comment]
CLASSES = ('word',) i s  true
    CLASSES = ('word') is false
注意逗号

**Comment by LiWentomng** [comment]
I have met the same problem.  I slove it by the  ' CLASSES = ('word',)' .Don't forget the ','  after the  'word'.

**Comment by imerse** [comment]
> i also have this errror:
> 
> File "/home/yuyang/.conda/envs/yuy_py35/lib/python3.5/site-packages/mmdet-0.6rc0+70383d4-py3.5.egg/mmdet/datasets/xml_style.py", line 44, in get_ann_info\n label = self.cat2label[name]\nKeyError: 'aircraft'\n'
> 
> and i modify CLASSES = ('.....') to CLASSES = ('aircraft',) in voc.py, it still show the same problem??

It is necessary to check the other voc.py which is built into `mmdet.egg.xxx`. Check the error info in detail, and find the file like `"/home/yuyang/.conda/envs/yuy_py35/lib/python3.5/site-packages/mmdet-0.6rc0+70383d4-py3.5.egg/mmdet/datasets/voc.py`, then change the classnames in it. It will be done!
