### ISSUE TITLE
RuntimeError: "CARAFELaucherBackward_Mask" not implemented for 'Half' (operator() at mmdet/ops/carafe/src/cuda/carafe_cuda_kernel.cu:456)

### ISSUE THREAD

**Issue by nemonameless** [open-mmlab/mmdetection#2834]
Although it has no effect on other models training and build successfully.  I just want to use CARAFE and meet this error. My env: CUDA-10.0, torch 1.3.1

**Comment by myownskyW7** [comment]
Half is now supported in https://github.com/open-mmlab/mmdetection/pull/2890
