### ISSUE TITLE
mmcv is not support opencv==4.2.0

### ISSUE THREAD

**Issue by ioir123ju** [open-mmlab/mmdetection#2837]
**commond**
./tools/dist_train.sh configs/ms_rcnn/my_ms_rcnn_x101_64x4d_fpn_1x_coco.py 2

**Describe the bug**
run with opencv4.2.0  reports error.
run with opencv4.1.2 is ok.
`  File "/home/juzheng/code/competition/mmdetection/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/home/juzheng/code/competition/mmdetection/mmdet/datasets/pipelines/transforms.py", line 330, in __call__
    results['img'] = mmcv.imnormalize(results['img'], self.mean, self.std,
  File "/home/juzheng/anaconda3/envs/python3.8/lib/python3.8/site-packages/mmcv/image/photometric.py", line 18, in imnormalize
    return imnormalize_(img, mean, std, to_rgb)
  File "/home/juzheng/anaconda3/envs/python3.8/lib/python3.8/site-packages/mmcv/image/photometric.py", line 38, in imnormalize_
    cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)  # inplace
TypeError: Expected Ptr<cv::UMat> for argument 'dst'
`

**Comment by ZwwWayne** [comment]
Thanks for your report, we will test it and update the package requirements after verifying it.

**Comment by ZwwWayne** [comment]
Hi @ioir123ju ,
I just ran mask_rcnn_r50_fpn_1x.py on my machine with `opencv-python-4.2.0.34` and meet no bug, which version of opencv-python-4.2.0 are you using?

**Comment by ioir123ju** [comment]
I am also this version

**Comment by ZwwWayne** [comment]
Did you modify other things in the config?

**Comment by ioir123ju** [comment]
Yes,But I don't think it has anything wrong with config.
coco_instance.py
`_base_ = './IJCAI_detection.py'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(800, 800), keep_ratio=True),
    dict(type='Pad', size_divisor=32),
    dict(
            type='Albu',
            transforms=albu_train_transforms,
            bbox_params=dict(
                type='BboxParams',
                format='pascal_voc',
                label_fields=['gt_labels'],
                min_visibility=0.0,
                filter_lost_elements=True),
            keymap={
                'img': 'image',
                'gt_masks': 'masks',
                'gt_bboxes': 'bboxes'
            },
            update_pad_shape=False,
            skip_img_without_anno=True),
    # dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'],
         meta_keys=('filename', 'ori_shape', 'img_shape', 'img_norm_cfg',
                    'pad_shape', 'scale_factor')),
]

data = dict(train=dict(pipeline=train_pipeline))
evaluation = dict(metric=['bbox', 'segm'])
`
coco_detection.py
`dataset_type = 'CocoDataset'
classes = ('Children Cabinet', 'Nightstand', 'Bookcase / jewelry Armoire', 'Wardrobe', 'Tea Table', 'Corner/Side Table',
           'Sideboard / Side Cabinet / Console', 'Wine Cooler', 'TV Stand', 'Drawer Chest / Corner cabinet', 'Shelf',
           'Round End Table', 'Double Bed', 'Bunk Bed', 'Bed Frame', 'Single bed', 'Kids Bed', 'Dining Chair',
           'Lounge Chair / Book-chair / Computer Chair', 'Dressing Chair', 'Classic Chinese Chair', 'Barstool',
           'Dressing Table', 'Dining Table', 'Desk', 'Three-Seat / Multi-person sofa', 'armchair', 'Two-seat Sofa',
           'L-shaped Sofa', 'Lazy Sofa', 'Chaise Longue Sofa', 'Footstool / Sofastool / Bed End Stool / Stool',
           'Pendant Lamp', 'Ceiling Lamp')
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(800, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(800, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        classes=classes,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'train2017/',
        classes=classes,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'train2017/',
        classes=classes,
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')
`

**Comment by ZwwWayne** [comment]
You might need to set `to_float32=True` during loading.
