### ISSUE TITLE
How should I process labels in v2.0

### ISSUE THREAD

**Issue by MioChiu** [open-mmlab/mmdetection#2838]
I see[ “In MMDetection 2.0, label “K” means background, and labels [0, K-1] correspond to the K = num_categories object categories.”](https://mmdetection.readthedocs.io/en/v2.0.0/compatibility.html)
should I  do like this when I [make cocostyle dataset](https://mmdetection.readthedocs.io/en/v2.0.0/tutorials/new_dataset.html)？
id       0      1     2     3
cls     A      B      C    background

**Comment by hellock** [comment]
No, the annotation file remains the same.
