### ISSUE TITLE
How to convert the pretrained resnext_50_32x4d.t7 model for mmdetection?

### ISSUE THREAD

**Issue by convolutionROC** [open-mmlab/mmdetection#284]

**Comment by OceanPang** [comment]
Hi @convolutionROC resnext_50_32x4d will be added recently. The pretrained model will be added to mmcv.

**Comment by OceanPang** [comment]
Hi @convolutionROC the corresponding pre-trained model is updated to mmcv. You can using `pretrained='open-mmlab://resnext50_32x4d',` to load it.

**Comment by hyliu-deepnorth** [comment]
Hi @OceanPang , How to use local pre-trained model?

**Comment by OceanPang** [comment]
@hyliu-deepnorth Just write the address of pre-trained model in `pretrain='{address}'.`

**Comment by WilliamYi96** [comment]
@OceanPang Could you express how to use a local pre-trained model specifically? If `'model_url = ../model.pth'`, then set `pretrain=model_url`, it says: `OSError: ../premodel/epoch_1.pth is not a checkpoint file`. Could you give me some advice?

**Comment by OceanPang** [comment]
@WilliamYi96 Please try to use the absolute url.

**Comment by WilliamYi96** [comment]
@OceanPang It helps! Thanks a lot.
