### ISSUE TITLE
Why the default value of finest_scale is 56?

### ISSUE THREAD

**Issue by ZucchiniTang** [open-mmlab/mmdetection#2843]
The definition of self.finest_scale locate in "mmdet/models/roi_extractors/single_level.py"
**The default value of self.finest_scale = 56.**
Can someone explain the reason for it? 
Thank you very much.

**Comment by hellock** [comment]
Please refer to the original paper of FPN.

**Comment by ZucchiniTang** [comment]
> Please refer to the original paper of FPN.

Yes, ok. Thank you for your reply.

**Comment by dadada101** [comment]
It seems the implementation doesn't comply with the original FPN paper? as introduced as follows
![捕获](https://user-images.githubusercontent.com/69999981/108449771-025dcb80-729f-11eb-8de7-ad3b1ebd4d53.PNG)

**Comment by ZucchiniTang** [comment]
> It seems the implementation doesn't comply with the original FPN paper? as introduced as follows
> ![捕获](https://user-images.githubusercontent.com/69999981/108449771-025dcb80-729f-11eb-8de7-ad3b1ebd4d53.PNG)
> @hellock @ZucchiniTang
I think mmdetection code is the same as the FPN paper. 

As mentioned in equation (1) in FPN paper, for example: w,h = 58,  k = k_0 + (-1.95) = 4 - 1.95 = 2.05.--> 2

And, finest_scale = \sqrt{w * h}.

Thus, in both of mmdetection code and FPN paper, if 0 < finest_scale < 112, k = 2; else If 112 < finest_scale < 224, k = 3; and if 224 < finest_scale, k = 4.
