### ISSUE TITLE
coco_eval.py and different results with pretrained mmdetection models

### ISSUE THREAD

**Issue by Etoye** [open-mmlab/mmdetection#2844]
During my work under ensembling, I noticed a difference between reported COCO mAP results at a model zoo with results that I receive by coco_eval.py evaluation of output JSON file.
Faster- RNN models

Original results:
R-50-FPN ---> 37.4 mAP
R-101-FPN --> 39.8 mAP
X-101-FPN --> 41.2 mAP (32x4d)

Results of JSON output from the provided models by coco_eval.py:
R-50-FPN ---> 36.4 mAP
R-101-FPN --> 38.5 mAP
X-101-FPN --> 40.1 mAP (32x4d)

What can be a reason for the difference between original results and achieved in the local environment?

**Comment by hellock** [comment]
- There is no `coco_eval.py` under `tools`, we use `tools/test.py` to test and evaluate results.
- What is your checkpoint? Are they from the latest model zoo?

**Comment by Etoye** [comment]
> * There is no `coco_eval.py` under `tools`, we use `tools/test.py` to test and evaluate results.
> * What is your checkpoint? Are they from the latest model zoo?

I use the previous mmdetection version (~1.0) which includes a coco_eval.py script in tools to evaluate output JSON file, received from test.py by --out parameter. 
To be honest, this model is ~3 months old, and I didn't check them with the current one in a model zoo. I will have a look at it.

**Comment by hellock** [comment]
In V1.x, the performance should be 36.4, 38.5, 40.1. In V2.0, we optimized the models and the performance are higher.
