### ISSUE TITLE
only one class, bug

### ISSUE THREAD

**Issue by fengxiuyaun** [open-mmlab/mmdetection#285]
when num_classes=1,     g = torch.abs(input.sigmoid().detach() - target)
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #3 'other'

**Comment by ybai62868** [comment]
num_classes needs to be set to 2 (such as person + bkg ) and reg_class_agnostic in bbox_head should be set to "True". 
I successfully get the person detecter by mmdet. That's a very good work!

**Comment by ybai62868** [comment]
num_classes needs to be set to 2 (such as person + bkg ) and reg_class_agnostic in bbox_head should be set to "True".
I successfully get the person detector by mmdet. That's a very good work!

**Comment by fengxiuyaun** [comment]
thank you very much

**Comment by fengxiuyaun** [comment]
Excuse me!. Do you used retina_head to train only person???
