### ISSUE TITLE
Convert model to v2.0

### ISSUE THREAD

**Issue by rusanager** [open-mmlab/mmdetection#2852]
Hi!
I'm try to convert model weights using `upgrade_model_version`. But I get following error:

`Traceback (most recent call last):
  File "upgrade_model_version.py", line 194, in <module>
    main()
  File "upgrade_model_version.py", line 190, in main
    convert(args.in_file, args.out_file, args.num_classes)
  File "upgrade_model_version.py", line 121, in convert
    checkpoint = torch.load(in_file)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
MemoryError
`

Size of file with my model just about 250mb. 16gb RAM is availble in my server and 15gb is free.

Any ideas why this is so.

**Comment by ZwwWayne** [comment]
Hi @rusanager ,
The script fails at `torch.load()` when loading your checkpoint. You might need to check whether your checkpoint could be loaded by `torch.load()`, e.g., whether the path is correct, whether your checkpoint is valid. It is not the bug of the script itself, so I am afraid that we cannot do much help here.

You can provide the checkpoint, related config, and your command to run the script thus helping us to reproduce the bug.
