### ISSUE TITLE
Regarding scale_factor  and multiscale testing

### ISSUE THREAD

**Issue by mdv3101** [open-mmlab/mmdetection#2853]
1.Can you please clarify the difference between: img_scale, scale_factor, scale and scale_idx?

2. Can we use img_scale and scale_factor simultaneously like: `img_scale = [1333,800]` and `scale_factor =2`. If yes, what would be the effect?

3. Also can we use something for scaling the images multiple times like setting `scale_factor = 1/4,1/2,1,2,4` . What other parameters do we need to set for getting such type of implementation. 

4. I want to test images on 5 scales and select those bounding boxes which are generated in atleast three scales. (Eg. Suppose for a given object, we get the detection bounding box at scale 1/4.2 and 4, so we will going to select this object, but if we are getting bounding box at only two/one scale, then it will going to discard it). Any suggestion on how to achieve this?

**Comment by hellock** [comment]
- There is only one argument `img_scale` for [`Resize`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L25). Could you be more specific?

- You can implement your own logic by overriding the [`aug_test()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/standard_roi_head.py#L256) method.

**Comment by mdv3101** [comment]
In the [data_pipeline](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/data_pipeline.md), you have mentioned ([Preprocessing](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/data_pipeline.md#pre-processing))
```
Resize

    add: scale, scale_idx, pad_shape, scale_factor, keep_ratio
```
I was asking about them.

Also can you please tell how to rescale an image by a factor of 1/2? Do we have to change img_scale from [1333,800] to [666,400], or is their any other method?

**Comment by hellock** [comment]
Only `img_scale` is the argument, others are fields for internal use. Please refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/api.html#mmdet.datasets.pipelines.Resize) and [code](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L25) for details.

**Comment by mdv3101** [comment]
Thanks for your response.
