### ISSUE TITLE
RuntimeError: ROIAlignV2 is not compiled with GPU support

### ISSUE THREAD

**Issue by cpboost** [open-mmlab/mmdetection#2854]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by cpboost** [comment]
![image](https://user-images.githubusercontent.com/58577521/83318165-bb3d2f80-a264-11ea-9706-08176b5289ab.png)

**Comment by hellock** [comment]
You did not provide any useful information. Please **fill in** the template instead of just **copying** it.

**Comment by cpboost** [comment]
I can only use a small part of its mmdetection algorithm, such as ssd, to complete the test. Faster-rcnn and cascade-rcnn are not available, and the error shown below appears.
RuntimeError: ROIAlignV2 is not compiled with GPU support


Individual model can is output
![image](https://user-images.githubusercontent.com/58577521/83346607-81e1ee00-a350-11ea-86c0-6abd5a1aa06d.png)

**Comment by hellock** [comment]
**Please fill in the `Error report` template.**

**Comment by cpboost** [comment]
解决了，谢谢你的好心，整体就是pillow安装的有问题，也没有按照install.md文档安装
