### ISSUE TITLE
Run the demo, no effect

### ISSUE THREAD

**Issue by TimVerion** [open-mmlab/mmdetection#2855]
ubuntu16.4
https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
cuda10 torch=1.4.0 mmdet mmcv Successful installation
But when I run the script in the demo, nothing happens
eg:
_from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv
config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = 'demo.jpg'
result = inference_detector(model, img)
show_result_pyplot(model, img, result)_

The output did not report an error:
The model and loaded state dict do not match exactly
unexpected key in source state_dict: bbox_head.fc_cls.weight, bbox_head.fc_cls.bias, bbox_head.fc_reg.weight, bbox_head.fc_reg.bias, bbox_head.shared_fcs.0.weight, bbox_head.shared_fcs.0.bias, bbox_head.shared_fcs.1.weight, bbox_head.shared_fcs.1.bias
missing keys in source state_dict: roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias, roi_head.bbox_head.fc_reg.weight, roi_head.bbox_head.fc_reg.bias, roi_head.bbox_head.shared_fcs.0.weight, roi_head.bbox_head.shared_fcs.0.bias, roi_head.bbox_head.shared_fcs.1.weight, roi_head.bbox_head.shared_fcs.1.bias

I tried retinanet50 maskrcnn50 fasterrcnn50 and nothing worked

**Comment by EvanAlbee** [comment]
@TimVerion  I meet the same problems ,Have you solved it?

**Comment by hyd-520** [comment]
i meet the same problems

**Comment by cltdevelop** [comment]
I meet the same problems

**Comment by valencebond** [comment]
using  https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb can solve the problem
