### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError

### ISSUE THREAD

**Issue by lyy-fighting** [open-mmlab/mmdetection#2863]
**When I use  configs/ssd512_coco.py to train custom dataset,the error appears during training process even the batch size is 1**..My** config file as follows:( )
**GPU:RTX 2070S  8G
RAM:16G
CPU:i5 and 6 cores**

**configs/ssd512_coco.py:**

train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=img_norm_cfg['mean'],
        to_rgb=img_norm_cfg['to_rgb'],
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(512, 512), keep_ratio=False),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
The error:
.conda/envs/open-mmlab/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
.conda/envs/open-mmlab/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError.

**How can deal with it?Thanks!!!**

**Comment by lyy-fighting** [comment]
I notice my %CPU is very high. It may be the data pre-processing consumes many resources. As a result, I just try to add code annotation in this part : 
'''
dict(
type='PhotoMetricDistortion',
brightness_delta=32,
contrast_range=(0.5, 1.5),
saturation_range=(0.5, 1.5),
hue_delta=18),
dict(
type='Expand',
mean=img_norm_cfg['mean'],
to_rgb=img_norm_cfg['to_rgb'],
ratio_range=(1, 4)), 
'''
Then it works well;
Also, I have a try to  annotate the PhotoMetricDistortion dict only.But it has the same error.I havn't tried to annotate the Expand dict only. I guess it will work if just annotating Expand dict. Because the Expand method may add much calculation and lets cpu can't stand  to run normally. Of course,the result may be have a discount.But I hope the discount is little....hah

**Comment by hhaAndroid** [comment]
Is there still a problem with the latest version now?

**Comment by ZwwWayne** [comment]
This seems to be caused by the limited memory of your device. So we are not able to help here.
