### ISSUE TITLE
report  an error after the project runs

### ISSUE THREAD

**Issue by xjl-le** [open-mmlab/mmdetection#2864]
#
![Firefox_Screenshot_2020-06-01T00-14-52 954Z](https://user-images.githubusercontent.com/55579267/83366407-725eb580-a3e1-11ea-96b5-965985c0699d.png)

hello,i meet a error which the image show 。it show 'Function not implemented :'epoch_1.pth'->'/mnt/newmmdet/mmdetection-master/tools/work/fcos50_gn/latest.pth''
My project environment is cuda10,torch1.3,mmcv==0.5.8 .I need you help .thanks a million

**Comment by hellock** [comment]
`symlink` is not implemented on some OS, you can add `create_symlink=False` in the checkpoint config.
