### ISSUE TITLE
error about demo.py

### ISSUE THREAD

**Issue by cdzhu** [open-mmlab/mmdetection#2868]
Firstly,Thank you for the excellent work,mmdetection helps me a lot.
When run the demo.py to inference just one image,some errors happened,because there is no key named ‘img_fields’ in results,this will make some errors when padding .so i add one line in the call LoadImage in inference.py,results['img_fields']=['img'],it works.
在我运行demo.py去测试单张图像时，发生了一些错误，提示我在对图像进行padding时，缺少 'img_fields'这个关键字，所以我在inference.py文件里加载图像的类里加了一行results['img_fields']=['img']，就可以运行了。

**Comment by ZwwWayne** [comment]
Hi @cdzhu ,
This bug should have been fixed in this [line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L283), could you pull the newest master and try again? Thanks.

**Comment by cdzhu** [comment]
OK，thanks very much!
