### ISSUE TITLE
In the tools\train.py, please import torch firstly for Windows 10

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#2870]
**Describe the feature**

**Motivation**
On my laptop, WIN10, GTX 1060, I installed the latest pytorch, cuda 10.2, mm-detection, mmcv for the demo, and debug purpose.
When I try to run the training code in Visual Studio, there have errors:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\keras\lib\site-packages\numpy\core\__init__.py", line 17, in <module>  
    from . import multiarray
  File "E:\Anaconda3\envs\keras\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "E:\Anaconda3\envs\keras\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

Finally,  I modify the train.py , import torch firstly then import mmcv.  The issue resolved.

So I suggest to modify the tools/train.py as I said.

Thanks a lot in advance.

**Comment by ZwwWayne** [comment]
Hi @minan19605 ,
Thanks for you advice. However, the core issue is not solved, if the code need to use bumpy, it may still meet the problem. You might need to check whether the numpy is correctly installed, and the import orders follow the python code style formated by isort.

**Comment by minan19605** [comment]
Actually,  I think this is maybe VS code's issue. I test in anaconda command line, I can import numpy normally in same conda env.

So,  is possible to add a comment if you don't want to change code?

**Comment by ZwwWayne** [comment]
Since the case is rare and seems to be caused by the bug of environment handling by vs code, adding a comment is unnecessary.
