### ISSUE TITLE
pip install -v-e.

### ISSUE THREAD

**Issue by zdd520** [open-mmlab/mmdetection#2871]
When I used this command “pip install -v-e.” in in V2.0, an error occurred: 
‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.
