### ISSUE TITLE
error on nms

### ISSUE THREAD

**Issue by ckqsars** [open-mmlab/mmdetection#2874]
When I test the nms use  test_nms in test folder.
the error is invalid device function on the code  inds = nms_ext.nms(dets_th, iou_thr) on 54 line.
But there is no error when I use the python setup.py develop or pip install -v -e . 

So anyone meet the same problem.

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by ckqsars** [comment]
> Please follow the `Error report` issue template.

I have solve the problem Thank you
