### ISSUE TITLE
warmup_ratio=0.001

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#2878]
Thanks for your work. 

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

There seems a bug in [warmup_ratio](https://github.com/open-mmlab/mmdetection/blob/fb9efc27dbe4a4d188c94369ef56e553ef2d64e9/configs/_base_/schedules/schedule_1x.py#L9). If you would like to use 0.001 as the warmup learning rate, I think this number should be 0.1 rather than 0.001, at least in the 'constant' policy. I guess this is one reason that leads to training performance degradation, as some guys report.

**Bug fix**
Change warmup_ratio=0.1

By the way, I have to say I do not like the restructuring of config files in v2.0, which results in the config file difficult to have an overview and edit, though this reduces the negligible file  size.

**Comment by hellock** [comment]
We set `warmup_ratio=0.001` to make the initial learning rate 0.001*0.02=0.00002. It makes the training more stable in some cases.

For the config file, you can still use the old-style config files in V2.0, which are also acceptable. Before each training, the complete config file (including configs overwritten by the command line) will be printed in the terminal. Besides, you can show the config file like the following.
```python
config = Config.fromfile('xxx.py')
print(config.pretty_text)
```

**Comment by hyz-xmaster** [comment]
Hi @hellock, 

Thanks for the reply and suggestions.

If the warmup_ratio is set as 0.001 by default, then the initial learning rate for training some one stage detectors, e.g. RepPoints, FCOS, will be 0.001x0.01 = [0.00001](https://github.com/open-mmlab/mmdetection/blob/a59f274ae6bb6c9d9e7d326837724fde7a882013/configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py#L99), but looking at the model training logs, for example the [RepPoint](https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/reppoints/reppoints_moment_r50_fpn_1x_coco/reppoints_moment_r50_fpn_1x_coco_20200330_233609.log.json) and [FCOS](https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/fcos/fcos_r50_caffe_fpn_4x4_1x_coco/20200224_230410.log.json), I found that the initial learning rates start from 0.001 rather than 0.00001 and the results are obtained using mmdetection v1.0 not v2.0. This inconsistency confuses me a bit.

Best,
xmaster

**Comment by hellock** [comment]
Not all models are benchmarked after the developing finished. Some models are benchmarked during the development, when we have not updated the version number. If the log shows initial lr is 0.001, that means `warmup_ratio` is set to 0.1 in that run. Using a smaller warmup_ratio will not bring negative effects.

**Comment by hyz-xmaster** [comment]
Got it, thanks.
