### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by zhangxiaodi** [open-mmlab/mmdetection#288]
when i run inference_detector(model, img, cfg)， the error is follow.

Segmentation fault!

How debug it? Is error from op or other place?

**Comment by hellock** [comment]
#24

**Comment by zhangxiaodi** [comment]
Thanks for your tip！ I shift my gcc version to 5.5 and compile op. Then the code can run well. Is this problem should be closed?

**Comment by Kerrwy** [comment]
> Thanks for your tip！ I shift my gcc version to 5.5 and compile op. Then the code can run well. Is this problem should be closed?

how do you shift you gcc version to 5.5? i am in conda virtual environment. @zhangxiaodi
