### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_75'

### ISSUE THREAD

**Issue by tarunmcom** [open-mmlab/mmdetection#2880]
Got error while installing mmdet.
**nvcc fatal   : Unsupported gpu architecture 'compute_75'**

**Comment by ZwwWayne** [comment]
Please use the `Error Template` and at least report the detail information of your environment.

**Comment by indulgingcode** [comment]
export TORCH_CUDA_ARCH_LIST="7.0"[https://github.com/torch/torch7/issues/1190#issuecomment-544790139](url)

**Comment by indulgingcode** [comment]
https://github.com/torch/torch7/issues/1190#issuecomment-544790139

**Comment by ZwwWayne** [comment]
Hi @tarunmcom 
Did you solve the issue?

**Comment by tarunmcom** [comment]
Not able to solved. Are some nvidia gpus not supported?

**Comment by ZwwWayne** [comment]
> Please use the `Error Template` and at least report the detail information of your environment.

That is why we need you to provide more information of your environment or following the `Error Template`. A single line of bug does not give any useful information for us to help to solve the bug.

**Comment by hyhyni** [comment]
> Got error while installing mmdet.
> **nvcc fatal : Unsupported gpu architecture 'compute_75'**

 I want to know how you solved this problem 'nvcc fatal : Unsupported gpu architecture 'compute_75'
Thank you very much.
