### ISSUE TITLE
Unbalanced GPU memory when using slurm on multi machine and multi gpus

### ISSUE THREAD

**Issue by jwwangchn** [open-mmlab/mmdetection#2886]
When I run MMDetection on 2 nodes with total of 16 GPUs by `slurm_train.sh`, I met a problem of unbalanced GPU memory usage. This figure shows one node GPU memory usage. I wonder if this is normal? And how should I do for reducing the memory usage on GPU0?

![image](https://user-images.githubusercontent.com/18238763/83617503-bf967f00-a5bb-11ea-94d8-5b64b1ecf1d2.png)

**Comment by hellock** [comment]
What pretrained checkpoints were you using? Is it a custom checkpoint?
The checkpoint may contain GPU tensors instead of CPU tensors we use by default.

**Comment by jwwangchn** [comment]
Yes, I used the custom checkpoint. Should I load checkpoint by `torch.load(CHECKPOINT_FILE, map_location='cpu')`?
