### ISSUE TITLE
with_cp

### ISSUE THREAD

**Issue by zyc-ai** [open-mmlab/mmdetection#2887]
Hi, 

I found that in the description of ResNeXt, there is an option of `with_cp` which is claimed to use checkpoint to save some memory. However, I couldn't find the the use of cp in ResNeXt.

Besides, ResNet have supporrt of with_cp for bottleneck structure only, setting with_cp with basiblock would raise an AssertionError, which is not stated in the description.

**Comment by xvjiarui** [comment]
Hi @zyc-ai 
`with_cp` is used in `forward()` [here](https://github.com/open-mmlab/mmdetection/blob/a59f274ae6bb6c9d9e7d326837724fde7a882013/mmdet/models/backbones/resnet.py#L277). 
`Bottleneck` of `ResNeXt` inherits from `Bottleneck` of `ResNet`, so it doesn't need to implement it again. 
`BasicBlock` is used in `ResNet18`, which is relatively small in terms of memory consumption. `with_cp` is usually not necessary. 
Btw, you are very welcomed to create a PR to add `with_cp` option for `BasicBlock`.
