### ISSUE TITLE
Can I read coco data from a zip file?

### ISSUE THREAD

**Issue by hust-nj** [open-mmlab/mmdetection#2888]
Hi, I often have a directory coco like this:
```bash
> ls
annotations  test2017.zip  train2017.zip  val2017.zip
```
When I run the code it raises
```python
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/val2017/000000403385.jpg'
```
It may suggest me to unzip the file.
Can I custom the reader in mmdetection so that I can read images from zip files without unzipping?

**Comment by hellock** [comment]
You may have a try, though not recommended.

**Comment by hust-nj** [comment]
OK, thank you!
I originally thought it was supported by mmdetection.  I have to custom the code myself. Because azure storage only supports large file well.
