### ISSUE TITLE
CPU version compilation

### ISSUE THREAD

**Issue by BerryRB** [open-mmlab/mmdetection#2889]
If I use the CPU to predict a single image, do I need to recompile the CPU version of mmdetection?And why in [mmdetection 2.0](https://github.com/open-mmlab/mmdetection/blob/v2.0.0/setup.py))  I didn't see the changes described in [#2385](https://github.com/open-mmlab/mmdetection/pull/2385/commits/41465c89d97e949c1cb4d329ced37937e8acfff4)？

**Comment by hellock** [comment]
MMDetection now supports both GPU and CPU inference. No changes are needed and you do not need to recompile it.

**Comment by BerryRB** [comment]
@hellock  Thank you for your reply! Using CPU to predict can use roialign and roipool normally？

**Comment by hellock** [comment]
Yes it can be compiled without CUDA. Please refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/install.html#install-with-cpu-only).
