### ISSUE TITLE
我想使用一个faster rcnn的预训练模型来初始化训练而不是主干网络的预训练模型

### ISSUE THREAD

**Issue by kiddliao** [open-mmlab/mmdetection#2892]
但是我的类别数是4类,预训练模型的类别数是81类,我能怎么解决这个问题呢
![image](https://user-images.githubusercontent.com/57079702/83707018-945b7080-a64b-11ea-9fe1-5118cd34e0a4.png)

**Comment by hellock** [comment]
Please use English or English&Chinese.

**Comment by kiddliao** [comment]
> English&Chinese.

sorry , what 'English or English&Chinese' means?
Am I not speaking Chinese?
