### ISSUE TITLE
Refactor the category order in heads. 0 means the first positive class instead of background now.

### ISSUE THREAD

**Issue by qianjinhao** [open-mmlab/mmdetection#2894]
我从v1迁移voc格式的数据集到v2上训练，发现了有些问题：
我训练三个类别，numclasses设置成4，但是输出的全连接层有5个，并且eval发现类别号对不上，都往前移动了一个，不知道什么原因，下面是我前后结果的对比。我在document上查到“Refactor the category order in heads. 0 means the first positive class instead of background now.”，是与这个有关系吗？

+-------+-------+--------+--------+-------+
| class | gts   | dets   | recall | ap    |
+-------+-------+--------+--------+-------+
| truck | 7591  | 42260  | 0.952  | 0.932 |
| car   | 23282 | 133814 | 0.986  | 0.964 |
| van   | 5734  | 38709  | 0.975  | 0.937 |
+-------+-------+--------+--------+-------+
| mAP   |       |        |        | 0.944 |
+-------+-------+--------+--------+-------+

+-------+-------+--------+--------+-------+
| class | gts   | dets   | recall | ap    |
+-------+-------+--------+--------+-------+
| truck | 0     | 436    | 0.000  | 0.000 |
| car   | 7591  | 49674  | 0.951  | 0.907 |
| van   | 23282 | 146452 | 0.979  | 0.944 |
+-------+-------+--------+--------+-------+
| mAP   |       |        |        | 0.926 |
+-------+-------+--------+--------+-------+

**Comment by hellock** [comment]
Please use English or English&Chinese for issues.
