### ISSUE TITLE
V1 to V2, voc format training problem

### ISSUE THREAD

**Issue by qianjinhao** [open-mmlab/mmdetection#2896]
I transferred voc format datasets from V1 to V2 for training, and found some problems:
I trained on three categories, num classes set to 4, but in the log had five outputs in full connection layers, and I eval the model I haved trained and  found that the category Numbers didn't match, and moved one forward. For some reason, here's how I compared the results before and after.
`
+-------+-------+--------+--------+-------+
| class | gts   | dets   | recall | ap    |
+-------+-------+--------+--------+-------+
| truck | 7591  | 42260  | 0.952  | 0.932 |
| car   | 23282 | 133814 | 0.986  | 0.964 |
| van   | 5734  | 38709  | 0.975  | 0.937 |
+-------+-------+--------+--------+-------+
| mAP   |       |        |        | 0.944 |
+-------+-------+--------+--------+-------+

+-------+-------+--------+--------+-------+
| class | gts   | dets   | recall | ap    |
+-------+-------+--------+--------+-------+
| truck | 0     | 436    | 0.000  | 0.000 |
| car   | 7591  | 49674  | 0.951  | 0.907 |
| van   | 23282 | 146452 | 0.979  | 0.944 |
+-------+-------+--------+--------+-------+
| mAP   |       |        |        | 0.926 |
+-------+-------+--------+--------+-------+
`

I found "Refactor the category order in heads. 0 means the first positive class instead of background now" in the document, Is that the reason? Can you explain that.

**Comment by ZwwWayne** [comment]
Hi @qianjinhao ,
If you only have three categories, then the num_classes should be 3 rather than 4.
