### ISSUE TITLE
测试一张图片的时候，出现了warning。

### ISSUE THREAD

**Issue by wangning7149** [open-mmlab/mmdetection#2897]
已经训练好模型了，我在测试一张图片时，用命令： python demo/image_demo.py demo/03001-0002.jpg configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py epoch_32.pth --device cpu
出现了错误：
/home/wn/projects/mmdetection-2.0.0/mmdet/apis/inference.py:95: UserWarning: We set use_torchvision=True in CPU mode.
warnings.warn('We set use_torchvision=True in CPU mode.')
/opt/conda/conda-bld/pytorch_1587428091666/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of addcmul is deprecated:
addcmul(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
addcmul(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out)
/home/wn/projects/mmdetection-2.0.0/mmdet/models/detectors/base.py:233: UserWarning: show==False and out_file is not specified, only result image will be returned
warnings.warn('show==False and out_file is not specified, only '
请问怎么解决啊？

**Comment by hellock** [comment]
Please use English or English&Chinese for issues.
