### ISSUE TITLE
i want to train my custom datasets with  pre-trained models on faster r-cnn

### ISSUE THREAD

**Issue by kiddliao** [open-mmlab/mmdetection#2898]
and i use a pre-trained models of faster-rcnn instead of pre-trained models of backbones,but the pre-traned model is trained on coco and have 81 classes,my custom datasets only have 4 classes,how can i solve it?
![image](https://user-images.githubusercontent.com/57079702/83732702-0600e200-a67f-11ea-8ffe-c4ecd7374c9c.png)

**Comment by kiddliao** [comment]
and i have an another question
![image](https://user-images.githubusercontent.com/57079702/83751653-c1367480-a699-11ea-92c5-875ca3d18ec1.png)
![image](https://user-images.githubusercontent.com/57079702/83751665-c7c4ec00-a699-11ea-913b-8a089ea2202a.png)
which language should i speak

**Comment by hellock** [comment]
> and i have an another question
> ![image](https://user-images.githubusercontent.com/57079702/83751653-c1367480-a699-11ea-92c5-875ca3d18ec1.png)
> ![image](https://user-images.githubusercontent.com/57079702/83751665-c7c4ec00-a699-11ea-913b-8a089ea2202a.png)
> which language should i speak

You may use
1. English only
2. English as the primary and Chinese as the annotation if you think it is necessary.

**Comment by hellock** [comment]
> and i use a pre-trained models of faster-rcnn instead of pre-trained models of backbones,but the pre-traned model is trained on coco and have 81 classes,my custom datasets only have 4 classes,how can i solve it?
> ![image](https://user-images.githubusercontent.com/57079702/83732702-0600e200-a67f-11ea-8ffe-c4ecd7374c9c.png)

Please refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/tutorials/finetune.html).

**Comment by kiddliao** [comment]
> > and i use a pre-trained models of faster-rcnn instead of pre-trained models of backbones,but the pre-traned model is trained on coco and have 81 classes,my custom datasets only have 4 classes,how can i solve it?
> > ![image](https://user-images.githubusercontent.com/57079702/83732702-0600e200-a67f-11ea-8ffe-c4ecd7374c9c.png)
> 
> Please refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/tutorials/finetune.html).

thanks for your reply.
i have read that documents
do you mean 'load_from'?
i have used mmdetection for 2 months and can train models successfully on mmdetection
my question is:
i have a pretrained models(not pretrained backbone models ,like resNext and resnetxxxx.pth),it used faster r-cnn and trained on mscoco and had 81 classes,
i want to use that pretrained models on my small custom datasets,
i can use that pretrained models successfullt bu changing my own categories,
May i have another convenient way to use that pretrained model,like freeze some classifier layers?

**Comment by kiddliao** [comment]
emm

**Comment by CarryHJR** [comment]
just change the num classes in the config and the load_from, then it will work, maybe you will get warning "size mismatch", ignore it.
改一下类别就可以和load_from就可以了，直接运行不会报错的

**Comment by hellock** [comment]
I did not catch your question. Is it not explained in the documentation? Can the suggestion from @CarryHJR work well for you?
