### ISSUE TITLE
Mask-RCNN segmentation head output channel contains background

### ISSUE THREAD

**Issue by kye9216789** [open-mmlab/mmdetection#290]
Hello.
I am using mmdetection giving you guys countless thanks.

In Mask R-CNN official paper, the output segmentation chnnel is 80(coco).
It seems that mmdetection output channel without class agnostic is 81, and I think it contains background.

The cascade R-CNN uses output channel as 80, but Mask R-CNN does not.

Please tell me why it is. Thank you.

**Comment by hellock** [comment]
The first channel indicates background, which is not used. In most implementations (including the official one), the mask head just output 81 channels instead of 80. Cascade R-CNN also outputs 81 channels.

**Comment by kye9216789** [comment]
Thank for your help. Have good day :)
