### ISSUE TITLE
 focal loss won't throw any error when model's num_classes is inconsistent with class number in ann_file

### ISSUE THREAD

**Issue by jshilong** [open-mmlab/mmdetection#2903]
https://github.com/open-mmlab/mmdetection/blob/e05e85834c3162a8981dc5169ffd04b1c44d67d6/mmdet/ops/sigmoid_focal_loss/src/cuda/sigmoid_focal_loss_cuda.cu#L37

When num_classes in bbox_head isn't  consistent with the max class number in ann_file,
this won't throw any error,  add a check like ``t < num_classes``  may avoid some mistakes

**Comment by yhcao6** [comment]
Thanks for your advice. We would appreciate if you would you like to create a PR to add `num_classes` checking to make it more friendly.
