### ISSUE TITLE
PASCAL VOC classes are defined twice

### ISSUE THREAD

**Issue by aabramovrepo** [open-mmlab/mmdetection#2908]
Hi All,

   I have a question regarding PASCAL VOC class names. In the project I found two places where exactly the same classes are defined:

1st: [voc.py](https://github.com/open-mmlab/mmdetection/blob/e05e85834c3162a8981dc5169ffd04b1c44d67d6/mmdet/datasets/voc.py#L9)

2nd: [class_names.py](https://github.com/open-mmlab/mmdetection/blob/e05e85834c3162a8981dc5169ffd04b1c44d67d6/mmdet/core/evaluation/class_names.py#L8)

as I understood, the final category names that appear in the evaluation table, are taken from `class_names.py`. However, removing `CLASSES` from `VOCDataset` in `voc.py` will cause a failure. What is the logic behind two declarations?

Thanks!

Cheers,
Alexey

**Comment by ZwwWayne** [comment]
`self.CLASSES` is used in data loading, classes in `class_names.py` are used for evaluating results. We will try to simplify them in the future.
