### ISSUE TITLE
Any plans for adding support for AmoebaNet?

### ISSUE THREAD

**Issue by liaopeiyuan** [open-mmlab/mmdetection#2910]
**Describe the feature**
Supporting AmoebaNet as one of the backbones for object detection.

**Motivation**
Models like NAS-FPN benefit a lot from AmoebaNet-based backbones, as shown in paper-with-code leaderboards: https://paperswithcode.com/paper/learning-data-augmentation-strategies-for#code
 
**Related resources**
https://cloud.google.com/tpu/docs/tutorials/amoebanet

**Additional context**
According to the official paoper, the # of parameters regarding AmoebaNet-A is close to a ResNeXt-101, so it is feasible for normal research.
https://arxiv.org/pdf/1802.01548.pdf

**Comment by ZwwWayne** [comment]
Hi @liaopeiyuan ,
Thanks for you suggestion, currently we do not have enough time for this feature, we will take it into consideration in our future plan. PRs are also welcomed.
