### ISSUE TITLE
label issues in cross_entropy_loss.py

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#2911]
Hi, 

  As the positive class label starts from 0 now in v2.0, 
> "Refactor the category order in heads. 0 means the first positive class instead of background now. (#2374)"

should these lines related to labels in [cross_entropy_loss.py](https://github.com/open-mmlab/mmdetection/blob/e05e85834c3162a8981dc5169ffd04b1c44d67d6/mmdet/models/losses/cross_entropy_loss.py#L32-L34)  be changed accordingly?

Thank you.

Regards,
xmaster

**Comment by ZwwWayne** [comment]
Hi @hyz-xmaster ,
See comments in [lines 28-30](https://github.com/open-mmlab/mmdetection/blob/e05e85834c3162a8981dc5169ffd04b1c44d67d6/mmdet/models/losses/cross_entropy_loss.py#L28-L30).

**Comment by hyz-xmaster** [comment]
Hi @ZwwWayne, thanks for the explanation.
