### ISSUE TITLE
How to load two dataloader when training?

### ISSUE THREAD

**Issue by mrbulb** [open-mmlab/mmdetection#2912]
Hi, I want to load diff image from two dataset for different processing when training.
But it seems that we can only give one dataloader for runner
https://github.com/open-mmlab/mmdetection/blob/8fc0542439629e5e69cc1f039a833ef84ac5fe51/mmdet/apis/train.py#L179

Is there any convenient way can load two diff dataloader without modify mmcv's source code?

**Comment by ZwwWayne** [comment]
You can concatenate dataset following the [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_dataset.md).
