### ISSUE TITLE
Clearly add expected bbox format in custom dataset

### ISSUE THREAD

**Issue by sizhky** [open-mmlab/mmdetection#2914]
**Describe the feature**
It is described that bboxes should be Nx4 numpy array for a custom dataset [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L27) but it is ambiguious where it is `(x,y,X,Y)` or `(x,y,w,h)` format. Please make sure it is mentioned properly

**Comment by sizhky** [comment]
I saw [here](https://github.com/open-mmlab/mmdetection/issues/1792#issuecomment-565721518) that it shoud be `x,y,X,Y`, but [here] it's prescribed as `x,y,w,h`. Does this mean, format changes according to the model under consideration? If so, where to check which model uses what format?

**Comment by BeingGod** [comment]
I have same question

**Comment by hellock** [comment]
bboxes are represented as (left, top, right, bottom). The representation is irrelevant to models. Some datasets like COCO have annotations like (x, y, w, h) and we convert it to (left, top, right, bottom).

**Comment by sizhky** [comment]
Sorry but i still didn't understand. As a user, should I always use `x,y,X,Y` and can I assume it works fine in every case? Or should I use `x,y,w,h` exclusively for COCO and `x,y,X,Y` for everything else? Can you point to the location in source code where I can find more details?

**Comment by hellock** [comment]
Internally, we adopt the format (x1, y1, x2, y2) everywhere. For the dataset annotation, unfortunately different datasets adopt different formats, which is not decided by us. We just take the official annotation format and convert it to (x1, y1, x2, y2) in our code. Thus if you want to create COCO-compatible datasets, bboxes in the annotations file should be (x,y,w,h). If you want to write your own dataset following the CustomDataset, you can use (x1, y1, x2, y2). Please refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html) and [custom.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py) and [coco.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py).

**Comment by Mabinogiysk** [comment]
@hellock The format of bbox is not written on docs. It would be of great help if it could be added to docs.
