### ISSUE TITLE
How to convert the config file from version1.X to the version2.X?

### ISSUE THREAD

**Issue by lartpang** [open-mmlab/mmdetection#2915]
Now I have a config file from the version1.X. But I want to try the mmdetectionV2.0 and some items in the old config file are invalid.

Could you give me some suggestions?

**Comment by ZwwWayne** [comment]
Hi @lartpang ,
Please refer to the configs in [legacy_1.x](https://github.com/open-mmlab/mmdetection/tree/master/configs/legacy_1.x).
