### ISSUE TITLE
Train with Negative Dataset （voc2007 & faster-rcnn）

### ISSUE THREAD

**Issue by wangning7149** [open-mmlab/mmdetection#2919]
I am trying to train faster RCNN of v2.0 with negative dataset (images which contain only background).
Excuse me, what should I do?

**Comment by mdv3101** [comment]
Hi @wangning7149
 #2399 it might help.

**Comment by wingskh** [comment]
> Hi @wangning7149
> #2399 it might help.

sorry, should the values of bbox be [0,0,0,0] or [] for negative images?

**Comment by hhaAndroid** [comment]
duplicate: #2399
