### ISSUE TITLE
Why setting rcnn=dict('match_low_quality=False') in Faster R-CNN but not in Mask R-CNN?

### ISSUE THREAD

**Issue by c1aris** [open-mmlab/mmdetection#2922]
Is the inconsistency a feature or a bug?

**Comment by ZwwWayne** [comment]
When we do the ablation study before, we sometimes observe about 0.1 AP improvements from `match_low_quality=False` in faster rcnn, but this does not always hold for mask rcnn, so we finally did not modify the mask rcnn. For now, this option does not affect the performance of both Faster R-CNN and Mask R-CNN. We are considering making them consistent in the future.

**Comment by c1aris** [comment]
I see, thank you so much!
