### ISSUE TITLE
performance difference when training with different number of GPUs

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#2927]
Anyone has any insight into the performance difference when training with different number of GPUs, say, training with 2 gpus X 8 images/gpu,  4 gpus X 4 images/gpu and 8 gpus x 2 images/gpu? Are the results always the same? or different considerably? Thanks.

**Comment by hellock** [comment]
Results should be very close, unless BN layers are trained.

**Comment by hyz-xmaster** [comment]
Thanks for the prompt reply.

Would you say 0.3 mAP gap is acceptable? 

If the GN layers are employed and trained, does this has similar effect on the performance to BN layers when training with different batch configurations?

**Comment by hellock** [comment]
I think it acceptable. GN might bring a small performance gap regarding to different batch sizes, but much smaller than BN.

**Comment by hyz-xmaster** [comment]
Thank you. These comments are quite helpful.
