### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by BeingGod** [open-mmlab/mmdetection#2928]
I meet a ERROR when I trained my custom dataset whose format is COCO.
I browsed some **issues** but them couldn't help me solve this problem.

# My config file
```python
_base_ = './faster_rcnn/faster_rcnn_r50_fpn_iou_1x_coco.py'

dataset_type = 'CocoDataset'
data_root = 'data/coco/'
classes= ('sick',)

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations/test.json',
	img_prefix=data_root + 'AI_2020_02/'
),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations/test.json',
	img_prefix=data_root + 'AI_2020_02/'
),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations/test.json',
	img_prefix=data_root + 'AI_2020_02/'
))

model = dict(
    roi_head=dict(
        bbox_head=dict(
            num_classes=1,)))
```
# The content of `test.json`
```json
{"info": {},
 "licenses": [], 
"images": [
{"file_name": "IM_0012.jpg", "height": 512, "width": 512, "id": 0}, 
{"file_name": "IM_0066.jpg", "height": 512, "width": 512, "id": 1},
 {"file_name": "IM_0809.jpg", "height": 512, "width": 512, "id": 2}...], 
"annotations": [
{"segmentation": [[]], "area": 288.0, "iscrowd": 0, "image_id": 0, "bbox": [281.0, 274.0, 16.0, 18.0], "category_id": 0, "id": 0}, 
{"segmentation": [[]], "area": 304.0, "iscrowd": 0, "image_id": 1, "bbox": [280.0, 274.0, 16.0, 19.0], "category_id": 0, "id": 1}, 
{"segmentation": [[]], "area": 272.0, "iscrowd": 0, "image_id": 2, "bbox": [280.0, 276.0, 16.0, 17.0], "category_id": 0, "id": 2},
 {"segmentation": [[]], "area": 288.0, "iscrowd": 0, "image_id": 3, "bbox": [279.0, 276.0, 16.0, 18.0], "category_id": 0, "id": 3}, 
{"segmentation": [[]], "area": 289.0, "iscrowd": 0, "image_id": 4, "bbox": [279.0, 276.0, 17.0, 17.0], "category_id": 0, "id": 4}...], 
"categories": [{"id": 0, "name": "sick"}]}
```
I make sure the type of  `image_id` and `id` is **`int`**

**Besides, I can train coco2017 normally.**

**Comment by BeingGod** [comment]
1. And I also want to know whether the `image_id` and `id` is **only** or not? 
2. Can share id in different json files?
such as the id of `IM_0000.jpg` is **0** in `train.json` and the id of `IM_0001.jpg` is **also 0** in `val.json`.

**Comment by igonro** [comment]
>     1. And I also want to know whether the `image_id` and `id` is **only** or not?
> 
>     2. Can share id in different json files?
>        such as the id of `IM_0000.jpg` is **0** in `train.json` and the id of `IM_0001.jpg` is **also 0** in `val.json`.

@BeingGod did you find out anything? I'm facing the same issue and I would like to know the answer to those questions you ask. Thanks!

**Comment by paklau99988** [comment]
Same here

**Comment by gxCaesar** [comment]
ME TOO.

**Comment by WAMAWAMA** [comment]
maybe you need to modify the `mmdet/datasets/xxx.py`  and `mmdet/core/evaluation/class_names.py`  for matching your own dataset👍

**Comment by tingfengwanxiao** [comment]
> ME TOO.

have you solved it?

**Comment by gxCaesar** [comment]
Yes,you have to know the detail！

发送自 Windows 10 版邮件应用

发件人: tingfengwanxiao
发送时间: 2020年10月26日 20:12
收件人: open-mmlab/mmdetection
抄送: Caesar; Comment
主题: Re: [open-mmlab/mmdetection] ValueError: need at least one array toconcatenate (#2928)

ME TOO.
have you solved it?

**Comment by tingfengwanxiao** [comment]
> he detail！

then,how do you solve the problem,I can check whether I meet the same problem.

**Comment by vpeopleonatank** [comment]
> > he detail！
> 
> then,how do you solve the problem,I can check whether I meet the same problem.

I get same error message. I found a solution on issues and fixed it by change **image_id** from type string to int and value of key 'segmentation' from list to list of list like this 
```json
"segmentation": [1,2] -> "segmentation": [[1,2]]
```
All modification is in my coco json annotation!
