### ISSUE TITLE
from now on,does mmdet only support voc format for 3 method?

### ISSUE THREAD

**Issue by gittigxuy** [open-mmlab/mmdetection#293]
it only support faster rcnn and ssd?if I want to use another method to train voc data ,what should I do?
transfer voc format to coco format?

**Comment by hellock** [comment]
It can support any method except for mask prediction, and you can write new config files like retinanet or cascade rcnn. If you'd like to predict masks, you can convert it to coco format or rewrite `VOCDataset`.

**Comment by beier9739** [comment]
Hello, Please forgive me for my bad English.
may I use the cascade mask rcnn to train the voc dataset, can I rewrite the VOCDataset? How can I rewrite it? Could you update it, please forgive me for being a beginner, I don’t know a lot. @hellock

**Comment by TyroneLi** [comment]
> Hello, Please forgive me for my bad English.
> may I use the cascade mask rcnn to train the voc dataset, can I rewrite the VOCDataset? How can I rewrite it? Could you update it, please forgive me for being a beginner, I don’t know a lot. @hellock

Just follow the xml_style.py and add your customed code to inherit base class and rewrite your own function.
