### ISSUE TITLE
the asynchronous num_pos issue in FCOS

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#2933]
**Describe the feature**
Fix the [num_pos](https://github.com/open-mmlab/mmdetection/blob/63e2d65291ad0957466932ccce60be00cd3289f7/mmdet/models/dense_heads/fcos_head.py#L185) bug in FCOS.

**Motivation**
As [the author of FCOS was aware](https://github.com/tianzhi0549/FCOS#training) that

> Now, training with 8 GPUs and 4 GPUs can have the same performance. Previous performance gap was because we did not synchronize num_pos between GPUs when computing loss.

I have also ran into this problem that there is an obvious performance gap (about 1 mAP) when training the FCOS with 8GPUs and 4 GPUs with mmdetection.  The problem is probably caused by the same asynchronous num_pos issue.

**Related resources**
The author of FCOS has fixed the problem by synchronizing 'num_pos' between GPUs. Please see the bug fix commit: https://github.com/tianzhi0549/FCOS/commit/a62aeca5f31eaeda37cfaf7ab66d2e3d84abba32

Thank you.

**Comment by yhcao6** [comment]
Thank you for the reminder. We would appreciate it if you would like to create a PR to fix this problem. I also notice that ATSS has already adopted reduced num positive across all GPUs. https://github.com/open-mmlab/mmdetection/blob/e574b8a65b5dbf5058dd371843bcb4ae817deed0/mmdet/models/dense_heads/atss_head.py#L205-L206

**Comment by hyz-xmaster** [comment]
well, I'd like to make my first PR, but you have to wait for a moment, because I need to first learn how to create a PR...

**Comment by yhcao6** [comment]
never mind.
