### ISSUE TITLE
The influence of some hyper-parameters on final performance in guided anchor

### ISSUE THREAD

**Issue by TengFeiHan0** [open-mmlab/mmdetection#2934]
In this paper [GA](https://arxiv.org/abs/1901.03278), To train the anchor localization branch, you define three regions of each box. Does the length of the central(ignore) region have any effect on the final performance? In other words, Is the final result sensitive to these hyperparameters? Thank you in advance.

**Comment by hellock** [comment]
It is not sensitive to $\sigma_1$ and $\sigma_2$.

**Comment by TengFeiHan0** [comment]
I'm sorry, I already find the related descriptions in your paper. thank you for your reply.
