### ISSUE TITLE
`cat_img_map` get empty `img_ids`

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [open-mmlab/mmdetection#2940]
after git pull new ci from master branch, the `cat_img_map` func gets empty `img_ids`. it seems that it should be assigned after [createIndex](https://github.com/open-mmlab/cocoapi/blob/master/pycocotools/pycocotools/coco.py#L93) func.

**Comment by xvjiarui** [comment]
Hi @zimenglan-sysu-512 
The original implementation defines `catToImgs` [here](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/coco.py#L80). 
The `cat_img_map` shares the same content with `catToImgs`. 
So the behavior of `cat_img_map` and `catToImgs` should be the same.  

May I know your use case and error you got?

**Comment by VoThanhDanh95** [comment]
I print the these 2 variable, but `catToImgs` return none empty while cat_img_map get empty. Still don't know why..

**Comment by zimenglan-sysu-512** [comment]
@xvjiarui 
i train ssd with subset of coco classes, and find that the `catToImgs` will be empty.

**Comment by zimenglan-sysu-512** [comment]
hi @xvjiarui 
`cat_img_map` still get empty, i think u should place these two lines
```
self.img_ann_map = self.imgToAnns
self.cat_img_map = self.catToImgs
```
after the this [line](https://github.com/open-mmlab/cocoapi/blob/master/pycocotools/pycocotools/coco.py#L93) `self.createIndex()`

**Comment by xvjiarui** [comment]
@zimenglan-sysu-512 
You are right. Could you please open a PR in https://github.com/open-mmlab/cocoapi to fix it?

**Comment by xvjiarui** [comment]
Hi @zimenglan-sysu-512 @VoThanhDanh95 
This issue is fixed by https://github.com/open-mmlab/cocoapi/pull/10.
You may try if the error still exists.
