### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by huzcc** [open-mmlab/mmdetection#2941]
Follow install.md, and following error occurs.
If you know, please help me.
Thanks!
![image](https://user-images.githubusercontent.com/49805871/84022279-92c9d980-a9b8-11ea-9398-dfc2ae69fe98.png)
This is conda env.
![image](https://user-images.githubusercontent.com/49805871/84022684-4206b080-a9b9-11ea-8c95-7a44ef5a45dd.png)

**Comment by xvjiarui** [comment]
Hi @huzcc 
The doc is updated. Please run
```
pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
```

**Comment by huzcc** [comment]
Hi, @xvjiarui 
The answer is effective.
Thank you very much!
