### ISSUE TITLE
mmdet - ERROR - The testing results of the whole dataset is empty

### ISSUE THREAD

**Issue by Prakhar-97** [open-mmlab/mmdetection#2942]
I was trying to train a CascadeMaskRCNN Hrnet model on a custom dataset in my local system with COCO style annotations.

This is the message that I get while training my dataset. On further looking I found that when running the single_gpu_test for validation data, the results are all empty, I am not able to identify the reason for the same. I am new to this library and any help would be appreciated.

**Comment by hellock** [comment]
There can be many reasons for that since you train the model on a custom dataset, and we cannot debug for you. E.g, the model has not converged, it suffers from overfitting, the threshold is high, the train/test set has much differences.

**Comment by Rajat-Mehta** [comment]
I am getting the same error while training on custom dataset in coco format
``` 
Loading and preparing results...
2020-06-14 23:36:16,926 - mmdet - ERROR - The testing results of the whole dataset is empty.
```

what might be the reason?

**Comment by Prakhar-97** [comment]
As you are using a custom dataset in the coco format make sure that you mention about the classes in the config files. This might be one of the reasons 
...
# dataset settings
dataset_type = 'CocoDataset'
classes = ('a', 'b', 'c', 'd', 'e')
...
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file='path/to/your/train/data',
        ...),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file='path/to/your/val/data',
        ...),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file='path/to/your/test/data',
        ...))
...

**Comment by muhammadabdullah34907** [comment]
@Prakhar-97 very well said. thank you

**Comment by anonymoussss** [comment]
> There can be many reasons for that since you train the model on a custom dataset, and we cannot debug for you. E.g, the model has not converged, it suffers from overfitting, the threshold is high, the train/test set has much differences.

Hello, I am using the coco dataset to train a detection model. I want to know why the error "The testing results of the whole dataset is empty" is reported when the model does not converge?

**Comment by tetsu-kikuchi** [comment]
In my case, I got this message in the evaluation at the 5th epoch, but not after the 10th epoch (val is done at every 5 epochs).  I used my custom dataset with 45 train data and 5 val data.  The train/val loss was not nan at the 5th epoch.   
Maybe the meaning of the message "The testing results of the whole dataset is empty" should be more clarified.

**Comment by LLsmile** [comment]
I trained YOLOX with my data and labels and it works well. But I get the same error in mmdet. So how can I check whether my json file meets the need of mmdet?

**Comment by sarmientoj24** [comment]
Also getting the same thing

**Comment by KingofLong** [comment]
I solved this problem while training on retinanet with my custom dataset by cutting half the lr.

**Comment by happy20200** [comment]
> 我用我的数据和标签训练了 YOLOX，它运行良好。但是我在 mmdet 中遇到了同样的错误。那么如何检查我的 json 文件是否满足 mmdet 的需要呢？我的数据集是 coco 格式的，但我不确定 mmdet 是否可以。
您好，请问这个问题你解决了嘛，我也是同样的情况，自己的数据集不确定做的对不对

**Comment by zhaoyuezhy** [comment]
In my case, I got this message in the evaluation at the 5th epoch, but not after the 36th epoch...

**Comment by David-Biggs** [comment]
> In my case, I got this message in the evaluation at the 5th epoch, but not after the 10th epoch (val is done at every 5 epochs). I used my custom dataset with 45 train data and 5 val data. The train/val loss was not nan at the 5th epoch. I used faster_rcnn_r50_fpn_2x_coco.py. Maybe it is better if the message is modified so that its meaning is clearer.

I got the same! Got this message after epoch 5 but then not after epoch 10...

**Comment by 294784045** [comment]
reducing the learning rate solved

**Comment by gicu8ab2** [comment]
Reducing learning rate worked for me also!

**Comment by yoletPig** [comment]
> As you are using a custom dataset in the coco format make sure that you mention about the classes in the config files. This might be one of the reasons ...
> 
> # dataset settings
> dataset_type = 'CocoDataset' classes = ('a', 'b', 'c', 'd', 'e') ... data = dict( samples_per_gpu=2, workers_per_gpu=2, train=dict( type=dataset_type, classes=classes, ann_file='path/to/your/train/data', ...), val=dict( type=dataset_type, classes=classes, ann_file='path/to/your/val/data', ...), test=dict( type=dataset_type, classes=classes, ann_file='path/to/your/test/data', ...)) ...

thank you so much. Reducing learning rate can't solve my problem,but this is work.

**Comment by koshinryuu** [comment]
but it gets` TypeError: __init__() got an unexpected keyword argument 'classes'`, when I add `classes=classes,`

**Comment by hwaseem04** [comment]
> but it gets` TypeError: __init__() got an unexpected keyword argument 'classes'`, when I add `classes=classes,`

I guess in 3.x the classes argument is removed. Try reducing the learning rate by changing it in the config, it worked for me.

**Comment by gitleej** [comment]
It may be caused by METAINFO under coco dataset. Just modify METAINFO under mmseg/dataset/coco.py.

**Comment by klinsc** [comment]
> There can be many reasons for that since you train the model on a custom dataset, and we cannot debug for you. E.g, the model has not converged, it suffers from overfitting, the threshold is high, the train/test set has much differences.

> reducing the learning rate solved

So I found the solution, whoever stump upon the "The testing results of the whole dataset is empty" line. Just add this line into your configuation file. (By the way, I am not sure what the default learning rate is, but my co-pilot told that it is 0.02)
`optimizer = dict(lr=0.02 / 10) # reduce learning rate by 10x.`

**Comment by linnnnnnnda** [comment]
Lowering the learning rate can resolve this error.

**Comment by freedomspiritJohn** [comment]
> > There can be many reasons for that since you train the model on a custom dataset, and we cannot debug for you. E.g, the model has not converged, it suffers from overfitting, the threshold is high, the train/test set has much differences.这可能有很多原因，因为您在自定义数据集上训练模型，我们无法为您调试。例如，模型没有收敛，它遭受过拟合，阈值高，训练/测试集有很大差异。
> 
> > reducing the learning rate solved降低学习率已解决
> 
> So I found the solution, whoever stump upon the "The testing results of the whole dataset is empty" line. Just add this line into your configuation file. (By the way, I am not sure what the default learning rate is, but my co-pilot told that it is 0.02)所以我找到了解决方案，无论谁绊倒了“整个数据集的测试结果是空的”行。只需将此行添加到您的配置文件中即可。（顺便说一句，我不确定默认学习率是多少，但我的副驾驶告诉它是 0.02） `optimizer = dict(lr=0.02 / 10) # reduce learning rate by 10x.`



> > There can be many reasons for that since you train the model on a custom dataset, and we cannot debug for you. E.g, the model has not converged, it suffers from overfitting, the threshold is high, the train/test set has much differences.
> 
> > reducing the learning rate solved
> 
> So I found the solution, whoever stump upon the "The testing results of the whole dataset is empty" line. Just add this line into your configuation file. (By the way, I am not sure what the default learning rate is, but my co-pilot told that it is 0.02) `optimizer = dict(lr=0.02 / 10) # reduce learning rate by 10x.`

Thank you, brother. I lowered it by half at the beginning, and it still didn't work, as you can

**Comment by veizei-K** [comment]
> > There can be many reasons for that since you train the model on a custom dataset, and we cannot debug for you. E.g, the model has not converged, it suffers from overfitting, the threshold is high, the train/test set has much differences.
> 
> > reducing the learning rate solved
> 
> So I found the solution, whoever stump upon the "The testing results of the whole dataset is empty" line. Just add this line into your configuation file. (By the way, I am not sure what the default learning rate is, but my co-pilot told that it is 0.02) `optimizer = dict(lr=0.02 / 10) # reduce learning rate by 10x.`

Thank you, brother. I lowered it by half at the beginning, and it still didn't work, as you can

**Comment by haoyuxingchen** [comment]
![Image](https://github.com/user-attachments/assets/111d278c-a12a-40dd-af05-d67ff0add29c)
我是配置文件class_name中标签跟json中标签不对应，导致loss_cls和loos_box为0导致的
