### ISSUE TITLE
Loading the models(model zoo) in c++.

### ISSUE THREAD

**Issue by mosjoker** [open-mmlab/mmdetection#295]

**Comment by mosjoker** [comment]
such as https://pytorch.org/tutorials/advanced/cpp_export.html#step-1-converting-your-pytorch-model-to-torch-script

**Comment by hellock** [comment]
Deployment and c++ support is not of high priority in our current dev plan. You can follow the official tutorial to have a try.

**Comment by mosjoker** [comment]
Thank you for your reply. I will try it.
