### ISSUE TITLE
How to train with background image with no bbox?

### ISSUE THREAD

**Issue by JosonChan1998** [open-mmlab/mmdetection#2956]
How to train with bg image with no bbox ? Should I use bbox[0,0,0,0] or bbox[] ? And what about the  category_id ? Should I set k as background in mmdetection2.0 ?

**Comment by zimenglan-sysu-512** [comment]
when to support this feature?

**Comment by ZwwWayne** [comment]
Hi @JosonChan1998 ,
I am not sure which step you want to ask about when you say `How to train with bg image with no bbox`. If you want do deal with it in your customized dataset, this [line](https://github.com/open-mmlab/mmdetection/blob/8951a8a70f36d442d8f5a9ecfe6361bbd6dc2adb/mmdet/datasets/coco.py#L133) gives an example about how to deal with BG image in your dataset.

**Comment by JosonChan1998** [comment]
@ZwwWayne Thanks for you reply.
I try to set `filter_gt_empty` as Fasle, and set the bbox [0,0,0,0],finally it works!  But I have a questions. Does training with background images contribute to loss? Or just skip the backgroud image ?

**Comment by hellock** [comment]
It contributes to losses, but not necessarily boost the performance.

**Comment by JosonChan1998** [comment]
@hellock Thanks for your reply.
I use it for cascade_RCNN, it just contributes to loss_rpn_cls, right?

**Comment by JosonChan1998** [comment]
@hellock Thanks for your reply.
I use it for cascade_RCNN, it just contributes to loss_rpn_cls, right?

**Comment by ZwwWayne** [comment]
> @hellock Thanks for your reply.
> I use it for cascade_RCNN, it just contributes to loss_rpn_cls, right?

And maybe classification branch in heads.

**Comment by JosonChan1998** [comment]
@ZwwWayne I got it.Thank you very much.

**Comment by LicharYuan** [comment]
hi, i meet some problems to train pure background images, it will stack in DDP mode ...  
Can anyone give me some suggestions?  Thanks!

**Comment by JosonChan1998** [comment]
> hi, i meet some problems to train pure background images, it will stack in DDP mode ...
> Can anyone give me some suggestions? Thanks!

set filter_gt_empty as Fasle, and set the bbox [0,0,0,0]

**Comment by LicharYuan** [comment]
> > hi, i meet some problems to train pure background images, it will stack in DDP mode ...
> > Can anyone give me some suggestions? Thanks!
> 
> set filter_gt_empty as Fasle, and set the bbox [0,0,0,0]

I try it before,  the training still stacked in some iterations. It seems like the DDP problems.  Thanks anyway!
