### ISSUE TITLE
deformable_group

### ISSUE THREAD

**Issue by hongdayu** [open-mmlab/mmdetection#296]

**Comment by hongdayu** [comment]
the deformed convolution weight when use the deformable_group is not the same as the pytorch group convolution?

**Comment by hongdayu** [comment]
是通过offset的分组来实现分组卷积？
那么我要在resnext加上deformed conv的话, 如何加载预训练权重呢？

**Comment by hellock** [comment]
Currently deformable conv does not support the argument `groups`, we will add it later.
