### ISSUE TITLE
error with installation: pip install -v -e .

### ISSUE THREAD

**Issue by Jingdong-Liu** [open-mmlab/mmdetection#2960]
**Checklist**
 I have searched related issues but cannot get the expected help.

**Bug**
can not install mmdetection

**Reproduction**
1. command or script has runed?
```
conda create -n open-mmlab python=3.7 -y
conda activate open-mmlab
conda install pytorch=1.3.1 cudatoolkit=9.2 torchvision=0.4.2 -c pytorch
cd ~/Desktop
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
pip install "git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI"
pip install -v -e . 
```
2. No modifications

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
**collect_env.py can not run, after debug this file, i get the following output**
```bash
sys.platform: linux
Python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 7.5, V7.5.17
GPU 0: GeForce GTX 965M
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.2.0
MMCV: 0.5.9
MMDetection: 2.0.0+unknown
```
2. Enviroments supplyments:
```
System: Ubuntu 16.04 LTS
Nvidia driver: 430
Cuda: 9.2  
Cuda: 7.6.2  
cudatoolkit: 9.2
PyTorch: 1.3.1
torchvision: 0.4.2
```

3. Install PyTorch way
```
conda install pytorch=1.3.1 cudatoolkit=9.2 torchvision=0.4.2 -c pytorch
```
4.  Other environment variables (`$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.2/lib64
export PATH=$PATH:/usr/local/cuda-9.2/bin
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda-9.2
```

**Error traceback**
If applicable, paste the error trackback here.
```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    :/usr/local/cuda-9.2/bin/nvcc -DWITH_CUDA -I/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include -I/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-9.2/include -I/home/kinst/anaconda3/envs/open-mmlab/include/python3.7m -c mmdet/ops/nms/src/cuda/nms_kernel.cu -o build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=sm_52 -std=c++11
    error: command ':/usr/local/cuda-9.2/bin/nvcc' failed with exit status 1
ERROR: Command errored out with exit status 1: /home/kinst/anaconda3/envs/open-mmlab/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kinst/Desktop/mmdetection-2.0.0/setup.py'"'"'; __file__='"'"'/home/kinst/Desktop/mmdetection-2.0.0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 790, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/kinst/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/kinst/anaconda3/envs/open-mmlab/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kinst/Desktop/mmdetection-2.0.0/setup.py'"'"'; __file__='"'"'/home/kinst/Desktop/mmdetection-2.0.0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-pm1o9_mk'
```

**Comment by Jingdong-Liu** [comment]
I change the enviroments to `conda install pytorch cudatoolkit=10.1 torchvision -c pytorch` , the error happens samely

**Comment by 916968505** [comment]
I met the same problem

**Comment by kaijieshi7** [comment]
![Screenshot from 2020-06-09 20-47-42](https://user-images.githubusercontent.com/19171201/84149104-80bc6980-aa92-11ea-83ec-08014a6186b6.png)
这样的吗？我在弄SOLO的官方实现那里的安装的，SOLO原来是1.0的mmdetection，我按照说明去装就这样了。

**Comment by 916968505** [comment]
把cuda升级成10.2就好了 亲测

**Comment by kaijieshi7** [comment]
我没有升级cuda,我都是10.1，重新安装了10.1cuda对应的1.3torch和0.4torchvision，貌似又有用了

**Comment by Jingdong-Liu** [comment]
我试试，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "916968505"<notifications@github.com&gt;; 
发送时间: 2020年6月10日(星期三) 下午2:55
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;; 
抄送: "984312425"<984312425@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmdetection] error with installation: pip install -v -e . (#2960)





 
把cuda升级成10.2就好了 亲测

**Comment by mmeendez8** [comment]
Same problem here too

**Comment by mmeendez8** [comment]
This worked for me (downgrade pytorch) in Ubuntu 18.04 with CUDA 10.1:
`conda install pytorch=1.4 cudatoolkit=10.1 torchvision -c pytorch
`

**Comment by ElectronicElephant** [comment]
can confirm that there is something to do with pytorch 1.5 and cuda 10.1.

It works with either pytorch 1.4 + cuda 10.1 or pytorch 1.5 + cuda 10.2, but not with pytorch 1.5+cuda 10.1

**Comment by lxm7188** [comment]
I have the same problem,
![Screenshot from 2020-07-01 11-48-09](https://user-images.githubusercontent.com/49085417/86201476-3c545300-bb92-11ea-9d2c-6536dd387c0c.png)

my configuration as follows,
NVRM version: NVIDIA UNIX x86_64 Kernel Module  440.100  Fri May 29 08:45:51 UTC 2020
GCC version:  gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0  On |                  N/A |
| 24%   49C    P8    11W / 200W |    322MiB /  8116MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1294      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1376      G   /usr/bin/gnome-shell                          48MiB |
|    0      1680      G   /usr/lib/xorg/Xorg                           119MiB |
|    0      1819      G   /usr/bin/gnome-shell                         129MiB |
|    0     19304      G   /usr/lib/firefox/firefox                       1MiB |
+-----------------------------------------------------------------------------+

**Comment by ZwwWayne** [comment]
The issue seems to be resolved, though the bug report basically does not capture the real bug/error of C++/NVCC compilation error. So the issue is closed. Please create a new issue following `Error Template` if you meet the similar issue again and cannot solve it.
