### ISSUE TITLE
Is there any method to make DCN run on CPU?

### ISSUE THREAD

**Issue by mao-jy** [open-mmlab/mmdetection#2961]

**Comment by xvjiarui** [comment]
Hi @mao-jy 
Currently, there is no efficient CPU implementation of DCN. But community contribution is always welcomed!

**Comment by mao-jy** [comment]
> Hi @mao-jy
> Currently, there is no efficient CPU implementation of DCN. But community contribution is always welcomed!

Thanks for your answer!
