### ISSUE TITLE
inferencing on cuda device 0 only

### ISSUE THREAD

**Issue by RiyazAina-DeepML** [open-mmlab/mmdetection#2969]
i am trying to do inference by setting cuda device other than 0,but its not using that device at all .
how to do inference on cuda device other than 0.?

**Comment by yhcao6** [comment]
For example, you want to inference on device 1, then
CUDA_VISIBLE_DEVICES=1 ${test_command}

**Comment by RiyazAina-DeepML** [comment]
> For example, you want to inference on device 1, then
> CUDA_VISIBLE_DEVICES=1 ${test_command}
