### ISSUE TITLE
dcn training error

### ISSUE THREAD

**Issue by SHERLOCKLS** [open-mmlab/mmdetection#297]
when I try to train the dcn you just released, the terminal throw out an error:
`
__init__() got an unexpected keyword argument 'dcn'`

Therefore, I wonder where am I doing wrong?

I use the following cmd to train model:

`python tools/train.py cascade_rcnn_dconv_c3-c5_r50_fpn_1x.py --gpus 4 --work_dir workdir/deconv --validate`

**Comment by hellock** [comment]
Are you using the latest code?

**Comment by SHERLOCKLS** [comment]
Yes, I have followed the [INSTALL.md ](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md) and  run the last step python `setup.py install` after I  pull updates from github.
This is the output after I run the last step
`Finished processing dependencies for mmdet==0.5.6+554e20a`
Looks like everything goes fine but when I run the train step, it broke down and throw the error above.
So I wonder if there something else went wrong.

**Comment by SHERLOCKLS** [comment]
Well, I found where the problem is.
**I didn't uninstall the previous version of mmdet.**
which looks like that there are a few different version lying in my virtue environment like this:

> mmcv                                           
> mmcv-0.2.3.dist-info                          
> mmdet                                          
> mmdet-0.5.5+1b9f9b8.dist-info                  
> mmdet-0.5.6+554e20a-py3.6.egg

**So I cover mmdet with mmdet-0.5.6+554e20a-py3.6.egg**
Now, everything goes fine. 
Thanks for your time.

**Comment by SHERLOCKLS** [comment]
the problem is solved. So I close the issue.
