### ISSUE TITLE
Why end-to-end train the GA-RPN with HTC, no improvement compared to the generic HTC

### ISSUE THREAD

**Issue by sunpeng1996** [open-mmlab/mmdetection#2973]
RT, 
Why I end-to-end train the GA-RPN with HTC no improvement compared to the generic HTC?
I change the thresholds from 0.5,0.6,0.7 to 0.6,0.7,0.8, but the improvement is almost nothing.
Thanks for your response.

**Comment by ZwwWayne** [comment]
Please use the `Reimplementation Questions`.
