### ISSUE TITLE
mabe a bug in version 2.1.0

### ISSUE THREAD

**Issue by heboyong** [open-mmlab/mmdetection#2974]
I upgrade mmdetection from 2.0.0 to 2.1.0, but I can't train with this error:ValueError: need at least one array to concatenate.
So I use version 2.0.0 and all work well, so I think maybe there is a bug in version 2.1.0

**Comment by xvjiarui** [comment]
Hi @heboyong 
What command did you run? 
Could you please fill the [error-template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md)?

**Comment by JacksonLiu-ai** [comment]
same problem...T.T

**Comment by CarryHJR** [comment]
same problem

**Comment by xvjiarui** [comment]
It seems that it is related to #2396. 
I will open a PR to fix it.

**Comment by deepakksingh** [comment]
I tried to build the version v1.2.0 by performing a checkout to that tag and then doing a build using ```python setup.py develop``` but in the logs it shows:
```
MMCV: 0.5.9                                                                                                                 │
MMDetection: 2.1.0+bf9638a                                                                                                  │
MMDetection Compiler: GCC 5.5                                                                                               │
MMDetection CUDA Compiler: 10.2  
```
Is there a procedure to build older versions?

**Comment by zxs123boss** [comment]
mmdetection sucks, detectron2 is the best

**Comment by hellock** [comment]
> mmdetection sucks, detectron2 is the best

Please mind your words. Do NOT be offensive.
