### ISSUE TITLE
How can I remove areas in the picture other than mask?

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#2978]
I trained with mask r-cnn. I can detect objects in pictures using `image_demo.py.` The masks on the picture are drawn with the following code snippet in the `base.py` file. 
Based on this code, I want to assign all the pixels except for this mask colorless, ie [0,0,0]. How can I do it? Thanks...

```
        # draw segmentation masks
        if segm_result is not None and len(labels) > 0:  # non empty
            segms = mmcv.concat_list(segm_result)
            inds = np.where(bboxes[:, -1] > score_thr)[0]
            np.random.seed(42)
            color_masks = [
                np.random.randint(0, 256, (1, 3), dtype=np.uint8)
                for _ in range(max(labels) + 1)
            ]
            for i in inds:
                i = int(i)
                color_mask = color_masks[labels[i]]
                mask = segms[i]
                img[mask] = img[mask] * 0.5 + color_mask * 0.5
```

**Comment by ZwwWayne** [comment]
Since you have the mask, you can create a new image with all zeros, e.g. empty_img, and then use
`empty_img[mask] = img[mask] * 0.5 + color_mask * 0.5`. Something like that should work.
