### ISSUE TITLE
SyntaxError: trailing comma not allowed without surrounding parentheses

### ISSUE THREAD

**Issue by deep-practice** [open-mmlab/mmdetection#2982]
>>>from mmdet.apis import inference_detector, init_detector, 
  File "<stdin>", line 1
SyntaxError: trailing comma not allowed without surrounding parentheses

mmdetection master branch
ubuntu18.04 pytorch1.5 cuda10.2 cudnn7.5.6

**Comment by hellock** [comment]
Which file?

**Comment by deep-practice** [comment]
stdin

**Comment by hellock** [comment]
I mean which file does this error originate from? Could you provide the complete stack trace?

**Comment by deep-practice** [comment]
I see what's going on.I type an extra comma.
