### ISSUE TITLE
Consider raising ValueError instead of AssertionError

### ISSUE THREAD

**Issue by zyc-ai** [open-mmlab/mmdetection#2983]
**Describe the feature**

Use
```python
if xxxx:
    raise ValueError/TypeError/KeyError
```
instead of

```python
assert xxx
```

**Motivation**
A clear and concise description of the motivation of the feature.

Most value/type checks use `assert`. However, there are [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError),  [`TypeError`](https://docs.python.org/3/library/exceptions.html#TypeError), etc. specifically designed for these cases. 

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

https://docs.python.org/3/library/exceptions.html

https://www.python.org/dev/peps/pep-3109/

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hellock** [comment]
I agree. We can gradually replace some assertions with ValueError or TypeError if the assertion is clearly for type check or value check. PRs are welcome.
