### ISSUE TITLE
Error with importing Corner Pool

### ISSUE THREAD

**Issue by ShreyasKallingal** [open-mmlab/mmdetection#2991]
I tried to run these two lines to import the necessary modules for inference on Faster_RCNN_r50_FPN. I cloned the latest version of MMDetection for this. I am unable to import certain "ext" modules like corner_pool_ext. I'm new to this platform, so I would greatly appreciate any insight you have. Thank you!
```
from mmcv.runner import load_checkpoint
from mmdet.apis import inference_detector, show_result, init_detector
```

**Environment**

sys.platform: linux
Python: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: Tesla K80
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.1.2
MMCV: 0.5.9
MMDetection: 2.1.0+8951a8a
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1

**Error traceback**

```
ImportError                               Traceback (most recent call last)
<ipython-input-6-24b0dc9ad91b> in <module>()
      1 from mmcv.runner import load_checkpoint
----> 2 from mmdet.apis import inference_detector, show_result, init_detector

8 frames
/content/mmdetection/mmdet/apis/__init__.py in <module>()
----> 1 from .inference import (async_inference_detector, inference_detector,
      2                         init_detector, show_result_pyplot)
      3 from .test import multi_gpu_test, single_gpu_test
      4 from .train import get_root_logger, set_random_seed, train_detector
      5 

/content/mmdetection/mmdet/apis/inference.py in <module>()
      7 from mmcv.runner import load_checkpoint
      8 
----> 9 from mmdet.core import get_classes
     10 from mmdet.datasets.pipelines import Compose
     11 from mmdet.models import build_detector

/content/mmdetection/mmdet/core/__init__.py in <module>()
      1 from .anchor import *  # noqa: F401, F403
----> 2 from .bbox import *  # noqa: F401, F403
      3 from .evaluation import *  # noqa: F401, F403
      4 from .fp16 import *  # noqa: F401, F403
      5 from .mask import *  # noqa: F401, F403

/content/mmdetection/mmdet/core/bbox/__init__.py in <module>()
      5                     TBLRBBoxCoder)
      6 from .iou_calculators import BboxOverlaps2D, bbox_overlaps
----> 7 from .samplers import (BaseSampler, CombinedSampler,
      8                        InstanceBalancedPosSampler, IoUBalancedNegSampler,
      9                        PseudoSampler, RandomSampler, SamplingResult)

/content/mmdetection/mmdet/core/bbox/samplers/__init__.py in <module>()
      7 from .random_sampler import RandomSampler
      8 from .sampling_result import SamplingResult
----> 9 from .score_hlr_sampler import ScoreHLRSampler
     10 
     11 __all__ = [

/content/mmdetection/mmdet/core/bbox/samplers/score_hlr_sampler.py in <module>()
      1 import torch
      2 
----> 3 from mmdet.ops import nms_match
      4 from ..builder import BBOX_SAMPLERS
      5 from ..transforms import bbox2roi

/content/mmdetection/mmdet/ops/__init__.py in <module>()
      1 from .context_block import ContextBlock
      2 from .conv_ws import ConvWS2d, conv_ws_2d
----> 3 from .corner_pool import CornerPool
      4 from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
      5                   DeformRoIPoolingPack, ModulatedDeformConv,

/content/mmdetection/mmdet/ops/corner_pool/__init__.py in <module>()
----> 1 from .corner_pool import CornerPool
      2 
      3 __all__ = ['CornerPool']

/content/mmdetection/mmdet/ops/corner_pool/corner_pool.py in <module>()
      2 from torch.autograd import Function
      3 
----> 4 from . import corner_pool_ext
      5 
      6 

ImportError: cannot import name 'corner_pool_ext'

```

**Comment by hellock** [comment]
Did you compile and install it correctly?

**Comment by guotong1988** [comment]
Same question. I am trying to debug mmdetection on Linux CPU.
I first run `/home/gt/Py36/bin/python3 setup.py install` in the root directory.
Then I run `tools/train.py` in Pychram.

**Comment by hyhyni** [comment]
> ImportError: cannot import name 'corner_pool_ext'
> ```

Hello, I want to know how you solved this problem 'ImportError: cannot import name 'corner_pool_ext'.

**Comment by guotong1988** [comment]
python setup.py develop

**Comment by hyhyni** [comment]
> `python3 setup.py develop`

Thank you.I will try it.
