### ISSUE TITLE
Different performance with syncBN and BN on HTC

### ISSUE THREAD

**Issue by caidandaren** [open-mmlab/mmdetection#2994]
Thanks for your work.
When I was using test script after train on our own dataset with syncBN on HTC, I found the error following:
!Traceback (most recent call last):                                                                                                                                                       
  File "/remote-home/my/Future3d/tools/test.py", line 149, in <module>                                                                                   
    main()                                                                                                                                                                              
  File "/remote-home/my/Future3d/tools/test.py", line 143, in main                                                                                                                      
    dataset.format_results(outputs, **kwargs)                                                                                                                                           
  File "/remote-home/my/Future3d/mmdet/datasets/Future3d.py", line 309, in format_results                                                                                             
    result_files = self.results2json(results, jsonfile_prefix)        
  File "/remote-home/my/Future3d/mmdet/datasets/Future3d.py", line 245, in results2json    
    json_results = self._segm2json(results)    
  File "/remote-home/my/Future3d/mmdet/datasets/Future3d.py", line 205, in _segm2json      
    segms = seg[label]                               
IndexError: list index out of range

Test script is:
./tools/dist_test.sh /remote-home/my/Future3d/configs/htc/htc_without_semantic_x101_64x4d_fpn_syncBN_dconv_c3-c5_mstrain_400_1400_2x_Future3d.py /remote-home/my/Future3d/tools/work_dirs/htc_without_semantic_x101_64x4d_fpn_syncBN_dconv_c3-c5_mstrain_400_1400_2x_Future3d/latest.pth 4 --format-only --options "jsonfile_prefix=./test_result/htc_without_semantic_x101_64x4d_fpn_syncBN_dconv_c3-c5_mstrain_400_1400_2x_Future3d/test_result"

Then I printed out the results output following:
[[array([], shape=(0, 5), dtype=float32)*34],[]*34]

However, I get the right segmentation result when using BN on HTC. The only difference between two configs is 'norm_cfg=dict(type='syncBN', requires_grad=True),norm_eval=False' and  'norm_cfg=dict(type='BN', requires_grad=True),norm_eval=True' 
Could somebody help me with the problem?

**Comment by ZwwWayne** [comment]
Hi @caidandaren ,
You might need to check whether the num_classes is set consistently with your dataset. `num_classes` should equal to the number of foreground classes in your dataset.

**Comment by caidandaren** [comment]
Hi @ZwwWayne ,
num_classes is the same '34' in the config file of BN and syncBN, but I get right segmentation result in the test of BN while the error in syncBN

**Comment by ZwwWayne** [comment]
Is 34 the correct number? Or is your implementation of output conversion is correct? It is possible that BN does not trigger this bug simply because it does not produce empty predictions on the same image.

**Comment by caidandaren** [comment]
@ZwwWayne Thank you, I will check it.
