### ISSUE TITLE
about the mean and std in configs/pascal_voc/ssd*_voc0712.py

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [open-mmlab/mmdetection#2996]
hi i train the `configs/pascal_voc/ssd300_voc0712.py` get low ap. find that the std is [1, 1, 1], is it right?

btw, find the the link to download the trained model in the readme is empty.

**Comment by ZwwWayne** [comment]
Hi @zimenglan-sysu-512 ,
We have not release the model but we will release them in the next week. The `img_norm_cfg` is set according to the pre-trained backbone's training setting.

**Comment by pecanjk** [comment]
@

> Hi @zimenglan-sysu-512 ,
> We have not release the model but we will release them in the next week. The `img_norm_cfg` is set according to the pre-trained backbone's training setting.

Is the pascal_voc/ssd pretrained model realeased?
