### ISSUE TITLE
How to use the toolbox ??

### ISSUE THREAD

**Issue by SuzaKrish** [open-mmlab/mmdetection#2997]
I am trying to build a faster rcnn model to incorporate RoIPooling. How should I use thetoolbox's code to recreate the model?

**Comment by ZwwWayne** [comment]
Since we support RoIPooling, you can do that by only changing the config of faster rcnn.
For example, a config like this should work.
```python
_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
model = dict(
    roi_head=dict(
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIPooling', out_size=7),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32])
        ))

```

**Comment by SuzaKrish** [comment]
Oh okay. Thank you! Also could you let me know where we can find how to build these modules? The tutorials tell certain things but how do we know the structure of building a config? Is there any particular syntax to refer to? And how do we integrate this into our own code? I seem to not be able to understand the structuring of these sub modules.

**Comment by liyiwei979621500** [comment]
https://mmdetection.readthedocs.io/en/latest/config.html
