### ISSUE TITLE
Add backbones

### ISSUE THREAD

**Issue by hellock** [open-mmlab/mmdetection#3]
- [ ] ResNext
- [ ] SE-ResNe(X)t
- [ ] DetNet

**Comment by hellock** [comment]
We consider to migrate backbones to `mmcv.cnn`.

**Comment by EtienneDavid** [comment]
Hello,

Thank you for your work on the mmdetection toolbox. It's truly a great tool to conduct DL research.

Are you still planning to implement new backbone as DetNet or Res2Net ?
