### ISSUE TITLE
Pytorch 1.0 support feature

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmdetection#30]
As pytorch already announced pytorch 1.0, it would be state-of-art if api can running on newest version pytorch

**Comment by hellock** [comment]
Thanks for your comments. Our release plan is to support the latest stable version of PyTorch, and we does have the plan to upgrade to v1.0 after the stable release of PyTorch.

**Comment by jinfagang** [comment]
@hellock That's very nice!

**Comment by hellock** [comment]
#157
