### ISSUE TITLE
Question about pre_nms, post_nms

### ISSUE THREAD

**Issue by whikwon** [open-mmlab/mmdetection#300]
Always thankful for providing a good framework.

I have a question about nms in `rpn_head` code below. https://github.com/open-mmlab/mmdetection/blob/554e20a2e77863a01bb870f528bc835603f4fab4/mmdet/models/anchor_heads/rpn_head.py#L43-L92
As I have never seen `nms_pre` and `nms_post` before, but could you let me know the reference paper of these?

**Comment by ybai62868** [comment]
The setting of nms_pre and nms_post can be found in configs/xxxx.py 
-----------------------------------------------------------------------
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)
)
I think Faster-RCNN can be a classic paper for you to learn this knowledge.

**Comment by whikwon** [comment]
Thanks. I can find the statement and does not contain `nms_pre` and `nms_post` related information. 
``` 
We fix the IoU threshold for NMS at 0.7, which leaves us about 2000 proposal regions per image, As we will show, NMS does not harm the ultimate detection accuracy, but substantially reduces the number of proposals. After NMS, we use the top-N ranked proposal regions for detection.
```

**Comment by kye9216789** [comment]
I have same question.

**Comment by hellock** [comment]
`nms_pre` means bbox num before nms, `nms_post` means bbox num after nms. Please see this [method](https://github.com/open-mmlab/mmdetection/blob/95d44cc119/mmdet/models/anchor_heads/rpn_head.py#L43) for details.

**Comment by whikwon** [comment]
Thanks, I've seen the method you mentioned and if possible, i want to know reference paper of it.

**Comment by hellock** [comment]
Faster R-CNN and FPN are the papers you need, but some details will not be in the paper, you need to look through the official source code.

**Comment by whikwon** [comment]
Ah, OK i'll check them. Thank you so much for help.

**Comment by scut-salmon** [comment]
@hellock Hi, I found that the value of nms_pre and nms_post are both set to 2000 in most train config file. Only some caffe version of config file with value:
![image](https://user-images.githubusercontent.com/20534039/62823786-a608ee80-bbc7-11e9-8660-2c157e93d651.png)
which I think is correct.

Could you please explain why should set the nms_pre=2000 instead of 12000, in this setting I don't think NMS will make some contributions.

Thanks,
Zhang

**Comment by ShihuaiXu** [comment]
@scut-salmon I am also have the same probleam, have you sloved it?

**Comment by xiaojunhao-ccc** [comment]
> @hellock Hi, I found that the value of nms_pre and nms_post are both set to 2000 in most train config file. Only some caffe version of config file with value: ![image](https://user-images.githubusercontent.com/20534039/62823786-a608ee80-bbc7-11e9-8660-2c157e93d651.png) which I think is correct.
> 
> Could you please explain why should set the nms_pre=2000 instead of 12000, in this setting I don't think NMS will make some contributions.
> 
> Thanks, Zhang

这才是正确的解释：
        rpn_proposal=dict(  # 在训练期间生成 proposals 的配置
            nms_across_levels=False,  # 是否对跨层的 box 做 NMS。仅适用于 `GARPNHead` ，naive rpn 不支持 nms cross levels
            nms_pre=2000,  # NMS 前的 box 数
            nms_post=1000,  # NMS 要保留的 box 的数量，只在 GARPNHHead 中起作用
            max_per_img=1000,  # NMS 后要保留的 box 数量
            nms=dict( # NMS 的配置
                type='nms',  # NMS 的类别
                iou_threshold=0.7 # NMS 的阈值
                ),
