### ISSUE TITLE
Is it possible to debug mmdetection in PyCharm in a CPU machine?

### ISSUE THREAD

**Issue by guotong1988** [open-mmlab/mmdetection#3010]
I don't need to debug all the models.
Only debugging one of them is OK.
If there are no full instructions, it is OK.
You can just answer yes or no. Then I will try to do it.
Thank you very much.

**Comment by hellock** [comment]
mmdet can inference with CPU, but not training, and we have no experience with PyCharm.

**Comment by guotong1988** [comment]
May I ask how do you debug mmdetection and What IDE do you use?

**Comment by hellock** [comment]
VSCode/VIM
print/pdb
