### ISSUE TITLE
faster-rcnn cityscapes checkpoint link is not working

### ISSUE THREAD

**Issue by soyebn** [open-mmlab/mmdetection#3012]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
The link provided in the cityscapes/readme for downloading trained checkpoint is not working,  
https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/cityscapes/faster_rcnn_r50_fpn_1x_cityscapes_20200502-829424c0.pth
I get the following error.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D11B90A1CF94F0FC</RequestId>
<HostId>cmeIUf5dWk3husNRcu0OKUDopnk4Tm3SxY4WAcVrvDN5Av285hIxdj6pItfTGe0omIxgSNtaj9o=</HostId>
</Error>

**Environment**
I tried using firefox and chrome and on win10/Ubuntu18.04/Android Mobile. But getting access denied error.

**Comment by xvjiarui** [comment]
Hi @soyebn 
I just make it public. Could you please try again?

**Comment by soyebn** [comment]
@xvjiarui, It worked thanks a lot.

**Comment by Rohit42** [comment]
The same issue exists for the Mask R-CNN link in the readme
