### ISSUE TITLE
How to train the model with the original size of the image

### ISSUE THREAD

**Issue by 422301949** [open-mmlab/mmdetection#3015]
In class Resize(), the training image is adjusted to a fixed size or a certain multiple.  But it changes the scale distribution of the objects in the data set. How to train with the original size of the image in mmdetection.

**Comment by yhcao6** [comment]
The default coco detection training pipeline is as following:
```
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
```
You can simply remove the `Resize` pipeline.
