### ISSUE TITLE
Error with proposal file

### ISSUE THREAD

**Issue by vankhoa21991** [open-mmlab/mmdetection#3017]
Hi, I ran the code 

tools/train.py configs/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py -- out 

to geth the pkl file, but it contain an array of 50K length (validation set of coco)

Then I run 
tools/train.py configs/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py

using that pkl file, but the length the code expected are 117266:

mmdetection/mmdet/datasets/custom.py", line 85, in <listcomp>
    self.proposals = [self.proposals[i] for i in valid_inds]
IndexError: list index out of range

Do you know what mistakes I made? Thanks

**Comment by hellock** [comment]
`tools/train.py configs/fast_rcnn/fast_rcnn_r50_fpn_1x_coco.py -- out`?
