### ISSUE TITLE
Dataset Concatination: Are overlapping labels being merged?

### ISSUE THREAD

**Issue by michaelschleiss** [open-mmlab/mmdetection#3019]
In Tutorial 2: Adding New Dataset it is mentioned that you can concatenate two datasets. 

What happens to overlapping labels, e.g. if I have two datasets that both contain the class pedestrian?

**Comment by hellock** [comment]
For the usage of concatenating two datasets, these two datasets share the same labels (classes).

**Comment by michaelschleiss** [comment]
I should have been more precise. I am a custom dataset alongside COCO. The custom dataset consists of pedestrians, cars, etc. For COCO I use only the subset that overlaps with the classes from my custom dataset, following the example from the tutorial:

> classes = ('person', 'bicycle', 'car')
> data = dict(
>     train=dict(classes=classes),
>     val=dict(classes=classes),
>     test=dict(classes=classes))

I guess there is no way at the moment to merge those labels, since they have different ids, right?

**Comment by hellock** [comment]
Yes, the concatenated datasets are expected to have exactly the same classes. If not, you may need to remap the class ids.
