### ISSUE TITLE
DataLoader seems to ignore samples without objects

### ISSUE THREAD

**Issue by aabramovrepo** [open-mmlab/mmdetection#3023]
Dear All,

   am I right that `DataLoader` ignores samples without objects? I have just noticed that the data set length shown in `INFO` during training is slightly lower than the actual data set length. Just for my understanding, how can I force `DataLoader` to load all images (I'm training `Faster RCNN` on data in `PASCAL VOC` format)? Setting `filter_empty_gt` to False does not make a difference.

Thanks!

Best,
Alexey

**Comment by Shallowte** [comment]
Using MSCOCO dataset, I think `filter_empty_gt` works fine when first loading the data, then the data is filtered by `get_subset_by_classes` found in mmdetection/mmdet/datasets/coco.py. 

Adding a condition `if self.filter_empty_gt` to the function this way

    def get_subset_by_classes(self):

        ids = set()
        if self.filter_empty_gt:
            for i, class_id in enumerate(self.cat_ids):
                ids |= set(self.coco.catToImgs[class_id])
            self.img_ids = list(ids)

        data_infos = []
        for i in self.img_ids:
            info = self.coco.loadImgs([i])[0]
            info['filename'] = info['file_name']
            data_infos.append(info)
        return data_infos

seems to do the trick on my side for MSCOCO, it might give you an idea for your case. 

Cheers!

**Comment by aabramovrepo** [comment]
@hellock thanks for your reply, I will check it out.
