### ISSUE TITLE
Question about assigner and sampler

### ISSUE THREAD

**Issue by kye9216789** [open-mmlab/mmdetection#303]
Hi
I cannot understand why blow two are different.

I think cascade_rcnn has many(3) assigner and samplers, and typical two_stage has only one assigner and sampler. that`s all.

But when getting assign, sampling results, cascade_rcnn uses assign_and sample, and two_stage uses separated functions build_assigner and build_sampler.

I think that is because the parameter in the build_sampler, context=self, but there are no uses in build_sampler function.

Please explain me. I can not understand what is the role of 'context=self'.

[https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/cascade_rcnn.py#L137-L143](url)

[https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/two_stage.py#L107-L109](url)

**Comment by hellock** [comment]
The behavior in two_stage is for supporting more complicated samplers such as OHEMSampler. By passing `context=self`, the sampler can access modules in the detector.

**Comment by kye9216789** [comment]
You must be an angel. You are my teacher. Thank you very much.
