### ISSUE TITLE
List of Index out of range while training

### ISSUE THREAD

**Issue by JackJWWong** [open-mmlab/mmdetection#3034]
Excuse me,
I'm training my VOC type dataset with NAS_FPN, the network will evaluate the mAP after every epoch. However, the error occurs with List of Index out of Range.
While training Faster_R-CNN in the Pascal_VOC folder, this issue doesn't exist.

The issue is shown below.
![1592286207(1)](https://user-images.githubusercontent.com/46587171/84736015-7856b800-afd7-11ea-96ce-fcee8634b01d.png)

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
