### ISSUE TITLE
error during setup mmdetetion

### ISSUE THREAD

**Issue by RiyazAina-DeepML** [open-mmlab/mmdetection#3038]
i am trying to do setup of mmdetection using the install.md 
`conda create -n open-mmlab python=3.7 -y
conda activate open-mmlab

conda install -c pytorch pytorch torchvision -y
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=PythonAPI"
pip install -v -e .`

but after running this command "pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=PythonAPI"
i am getting error 
"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-zBoZNw-build/PythonAPI"

``

**Comment by TengFeiHan0** [comment]
probably, you try a new command line `pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"`
`pip install -v -e . `  written in `install.md`
