### ISSUE TITLE
negative  segm_mAP_s

### ISSUE THREAD

**Issue by RiyazAina-DeepML** [open-mmlab/mmdetection#3039]
why am i getting "segm_mAP_s:-1.0000 " val during model training ?
what does it mean ?

`Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.567
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.920
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.663
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.536`

**Comment by ZwwWayne** [comment]
Please use the `Error Template` or `Reimplementation questions`. We are not able to help you because we do not know why either from your description.
