### ISSUE TITLE
what does proposal_files do?

### ISSUE THREAD

**Issue by whikwon** [open-mmlab/mmdetection#305]
I can't find any config using `proposal_files` what is it for? 
https://github.com/open-mmlab/mmdetection/blob/ab5bca654060e9dee9fa1d02a7c8ece5a48753f7/mmdet/datasets/utils.py#L77

**Comment by hellock** [comment]
It is used to load pre-computed proposals (like Fast R-CNN). If you are training Faster R-CNN end to end, this field is set to None.
