### ISSUE TITLE
ValueError: some parameters appear in more than one parameter group

### ISSUE THREAD

**Issue by BlueBlueFF** [open-mmlab/mmdetection#3051]
when i use this config"configs/fcos/fcos_r50_caffe_fpn_4x4_1x_coco.py",
if i set optimizer = 
optimizer = dict(type='SGD', lr=0.01,paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.,bypass_duplicate=True))

it will raise error:ValueError: some parameters appear in more than one parameter group

if i set optimizer = 
optimizer = dict(type='SGD', lr=0.01)
the loss will be nan after warm up stage, and i try to adjust steps or ratio of warm up, it doesn't work

**Comment by TangShengqin** [comment]
i meet this problem too..

**Comment by xvjiarui** [comment]
Hi @TangShengqin 
May I have your config file?

**Comment by TangShengqin** [comment]
> Hi @TangShengqin
> May I have your config file?

I solve this problem. I found that the reason for this problem is that there are parameters in the model that do not participate in the loss calculation, we can set find_unused_parameters = True in config file to solve this proplem.

**Comment by TangShengqin** [comment]
> Hi @TangShengqin
> May I have your config file?

# -*- coding: utf-8 -*-
# @File    : fcos_center-normbbox-centeronreg-giou_efficientnet-b0-coco.py

from __future__ import absolute_import, division, print_function

multiplier = 1.0
feat_channels = 64

lr = 0.14
total_epochs = 300

INF = 1e8
default_regress_ranges = ((-1, 64), (64, 128), (128, 256), (256, 512),
                          (512, INF))
range_multiplier = 1.0
regress_ranges = tuple(((x * range_multiplier, y * range_multiplier) for x, y
                        in (default_regress_ranges)))

# model settings
model = dict(
    type='FCOS',
    pretrained='efficientnet_b0_no_se_relu.pt',
    backbone=dict(
        type='MBV2_Net',
        strides=(8, 16, 32)),
    neck=dict(
        type='BiFPN',
        in_channels=[40, 112, 320],
        out_channels=feat_channels,
        norm_cfg=dict(type='BN', requires_grad=True),
        act_cfg=dict(type='ReLU'),
        start_level=0,
        num_outs=5),
    bbox_head=dict(
        type='FCOSHead',
        num_classes=80,
        in_channels=feat_channels,
        stacked_convs=4,
        feat_channels=feat_channels,
        strides=[8, 16, 32, 64, 128],
        num_ins=5,
        share_bn=False,
        sep_conv=True,
        regress_ranges=regress_ranges,
        norm_on_bbox=True,
        centerness_on_reg=True,
        dcn_on_last_conv=False,
        center_sampling=True,
        conv_bias=True,
        norm_cfg=dict(type='BN', requires_grad=True),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='GIoULoss', loss_weight=1.0),
        loss_centerness=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)))
# training and testing settings
train_cfg = dict(
    assigner=dict(
        type='MaxIoUAssigner',
        pos_iou_thr=0.5,
        neg_iou_thr=0.4,
        min_pos_iou=0,
        ignore_iof_thr=-1),
    allowed_border=-1,
    pos_weight=-1,
    debug=False)
test_cfg = dict(
    nms_pre=1000,
    min_bbox_size=0,
    score_thr=0.05,
    nms=dict(type='nms', iou_threshold=0.6),
    max_per_img=100)

# dataset settings
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_scale = (512, 512)
size_divisor = 128
img_norm_cfg = dict(
    mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=img_scale, keep_ratio=True,
         ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=img_scale),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=size_divisor),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=size_divisor),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=28,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
)
evaluation = dict(interval=10, metric='bbox')
# optimizer
# optimizer = dict(
#     type='SGD', lr=lr, momentum=0.9, weight_decay=4e-5)
optimizer = dict(
    type='SGD', lr=0.16, momentum=0.9, weight_decay=4e-5,
    paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.))
optimizer_config = dict(grad_clip=None)

lr_config = dict(
    policy='CosineAnnealing',
    by_epoch=False,
    warmup='constant',
    warmup_iters=50,
    warmup_ratio=1.0 / 3,
    min_lr=0.0)

# runtime settings
checkpoint_config = dict(interval=10)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
