### ISSUE TITLE
incorrect unmap invocation parameter in AnchorHead::_get_targets_single

### ISSUE THREAD

**Issue by tianq01** [open-mmlab/mmdetection#3055]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

issue #2560 introduced below code:

  labels = unmap(
                labels, num_total_anchors, inside_flags,
                fill=self.num_classes)  # fill bg label

For faster-rcnn , it fills 1 in our case(fg label),  which makes thousands of positive examples.

perhaps self.background_label should be used here.

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Hi @tianq01 ,
Thanks for your report. However, we change it in https://github.com/open-mmlab/mmdetection/pull/2560 because it will cause another bug. Since `label_weight` serves as a correct mask here, you can use `label_weight` to mask the out-of-image positive labels. This workaround may not be perfect but should work in most of the cases. We will also consider to redesign this place in the future.

**Comment by tianq01** [comment]
Thanks for quick reply.

yeah thanks to lable_weight, it looks no much impact on training. 
In AnchorHead.__init__:
        `self.background_label = (
            num_classes if background_label is None else background_label)
`
further question: is self.background_label not enough for the fix?

**Comment by ZwwWayne** [comment]
> Thanks for quick reply.
> 
> yeah thanks to `label_weight`, it looks no much impact on training.
> In `AnchorHead.__init__`:
> `self.background_label = ( num_classes if background_label is None else background_label) `
> 
> further question: is `self.background_label` not enough for the fix?

It will cause the same problem as `num_classes`.
