### ISSUE TITLE
Will the memory of the model list in the model zoo be memory or GPU memory requirements? Is 8G memory enough?

### ISSUE THREAD

**Issue by hyz0720** [open-mmlab/mmdetection#3057]
Will the memory of the model list in the model zoo be memory or GPU memory requirements? Is 8G memory enough?

**Comment by hellock** [comment]
It is GPU memory. For server memory, 64G or above is recommended and 256G is safe.

**Comment by hyz0720** [comment]
I found that the memory usage will continue to increase during training. Is this normal? Is there a function to release video memory?
