### ISSUE TITLE
understanding model training output 

### ISSUE THREAD

**Issue by RiyazAina-DeepML** [open-mmlab/mmdetection#3058]
can anyone help me understand the output of model training ?

`Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.618
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.917
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.795
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.596
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.690
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.228
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.705
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.722
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.691
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.737`

**Comment by hellock** [comment]
You may learn more about COCO dataset and its metrics. Please refer to http://arxiv.org/abs/1405.0312.
