### ISSUE TITLE
how to build a specific version

### ISSUE THREAD

**Issue by deepakksingh** [open-mmlab/mmdetection#3066]
most of the version are marked with tags.
Could you kindly tell me how to build a specific version.

What all have i done:
1. ``` git checkout v1.2.0```
2. Run ```python setup.py develop```

When i train with the command:
```./tools/dist_train.sh configs/ms_rcnn/ms_rcnn_x101_32x4d_fpn_1x_cityscapes_new.py 4```
I notice that the logs contain:
```
MMCV: 0.5.9                                                                                                                 │
MMDetection: 2.1.0+bf9638a                                                                                                  │
MMDetection Compiler: GCC 5.5                                                                                               │
MMDetection CUDA Compiler: 10.2  
```

Is there any steps missing to build at a specific tag

**Comment by hellock** [comment]
Did you have multiple versions installed in different paths?

**Comment by deepakksingh** [comment]
I had just switched to the specific branch/tag and performed the build

**Comment by hellock** [comment]
Could you run `echo $PYTHONPATH`?

**Comment by deepakksingh** [comment]
it's blank.
maybe it is not set during the installation

**Comment by deepakksingh** [comment]
I performed a new build from scratch with a new environment and still, the PYTHONPATH variable is blank.

**Comment by hellock** [comment]
You may check the file `mmdet/version.py` to see the version after building it.

**Comment by deepakksingh** [comment]
yes, it updates in ```mmdet/version.py```.
i had to remove the previous build files using:
```
pip uninstall mmdet
rm -rf ./build
find . -name "*.so" | xargs rm
```
