### ISSUE TITLE
SSD Configs Hardcode COCO Dataset in Abnormal Way

### ISSUE THREAD

**Issue by CMobley7** [open-mmlab/mmdetection#3067]
The configs for SSDs include the following code, which prevent a custom dataset from being used with `/tools/train.py` when sending in additional args with the `--options` flag. Can the dataset portion of the code be removed and set via `_base_/datasets/coco_detection.py`, like the faster rcnn models; so that, custom datasets can be used more easily?

```
train=dict(
        _delete_=True,
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=dataset_type,
            ann_file=data_root + 'annotations/instances_train2017.json',
            img_prefix=data_root + 'train2017/',
            pipeline=train_pipeline)),
```

**Comment by hellock** [comment]
It is slightly different from the base dataset, and `RepeatDataset` is used. Why additional args can not be specified via `--options`?

**Comment by CMobley7** [comment]
Understood regarding the need for the dataset dict. The options command can still be used but the traditional args I typically used needed to be updated a little. Closing this issue as there is no issue.

**Comment by ryanmaxwell96** [comment]
Hello, I would also like to use a custom dataset with ssd. How can I do this? Also, sorry for the newbie question, but how do I input --options? Like python3 tools/train config_file --options?

**Comment by Asaad-Nasrallah** [comment]
try >>>>>
***********************************************************************
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=3,
    train=dict(pipeline=train_pipeline),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
***********************************************************************
it is work with me
