### ISSUE TITLE
Is it possible to apply custom evaluation metric ? 

### ISSUE THREAD

**Issue by Wei-Mao** [open-mmlab/mmdetection#3069]

**Comment by hellock** [comment]
Yes, please refer to the implementation of `dataset.evaluate()`.

**Comment by soumya997** [comment]
I could not find this `dataset.evaluate()` in any part of the official documentation, but I did find the implementation.
Here: https://github.com/open-mmlab/mmdetection/blob/f08548bfd6d394a82566022709b5ce9e6b0a855e/mmdet/datasets/coco.py#L364
Thank you for this great framework.
