### ISSUE TITLE
How to get anchors of certain fpn levels

### ISSUE THREAD

**Issue by x2ss** [open-mmlab/mmdetection#307]
Hi authors, 

First of all, wonderful work! Here I would like to ask you a question. Thanks for your time on considering it.

Now I would like to get anchors from certain FPN levels, for example, I only want the anchors from P2, P3, and P4, and suppress the anchors from P5 and P6. Would you please give me some suggestions on modifying the mmdetection to make it possible?

Thanks for your help very much!

Best

**Comment by hellock** [comment]
The anchor generation is implemented in `AnchorHead`. You may refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L115) for details.

**Comment by x2ss** [comment]
> The anchor generation is implemented in `AnchorHead`. You may refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L115) for details.

Thanks for your kind relay. After reading [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L115), I think that changing anchor_strides=[4, 8, 16, 32, 64] to anchor_strides=[4,8,16] in config file would  suppress the anchors from P5 and P6. Am I right? 

Also, I found that the total number of anchor_strides is related to featmap_sizes (since num_levels = len(featmap_sizes)), but I can not find where 'featmap_sizes' is valued. Would you please give me some idea?

Thank you very much.

Best
