### ISSUE TITLE
RetinaNet with HRNet Listed but no Configs Exist

### ISSUE THREAD

**Issue by CMobley7** [open-mmlab/mmdetection#3070]
RetinaNet is listed as working with HRNet, but I don't see any config examples for this in `/configs`. Is this on purpose?

**Comment by hellock** [comment]
The models listed in the table are supported, but not necessarily being benchmarked. You can easily create a config following RetinaNet and HRNet.

**Comment by CMobley7** [comment]
Understood, thank you @hellock for always getting back to me quickly! Closing this issue as there is no issue.
