### ISSUE TITLE
during inference index out of range error

### ISSUE THREAD

**Issue by RiyazAina-DeepML** [open-mmlab/mmdetection#3071]
i have used "/configs/ms_rcnn/ms_rcnn_x101_64x4d_fpn_1x.py" this model,
mmdetection v1.1.0

i am runnig  inference_demo.py file under the demo folder.
during this i am getting following error.

`-> 168             mask = maskUtils.decode(segms[i]).astype(np.bool)
    169             img[mask] = img[mask] * 0.5 + color_mask * 0.5
    170     # draw bounding boxes

IndexError: list index out of range

during debuging code  doesn't reach segms[i] line.
`
what is the issue,
result = inference_detector(model, img)
bbox_result, segm_result = result
when i checked the len(bbox_result),len(segm_result) ,they are not equal? why ?
that why segs[i] getting out of bound index

same inference code run properly on other model config file but it throws error mask scoring cnn? is their other way to inference for this model

**Comment by yhcao6** [comment]
Could you try MMDet v2.x (master branch)?
