### ISSUE TITLE
Some simple question about how to develop. Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [open-mmlab/mmdetection#3072]
My goal is to train my own dataset.

Here is my steps:

1, I download the code of `v2.1.0`

2, I run `python setup.py install`

My question is:

The code is installed into `Python's site-packages`. How could I write `my_dataset.py` in my own IDE? How could I let `my_custom_config.py` find `my_dataset.py` ?

Thank you very much.

**Comment by hellock** [comment]
Please follow the installation guide and development guide in the documentation.

**Comment by guotong1988** [comment]
```
pip install -v -e .  # or "python setup.py develop"
```
