### ISSUE TITLE
Cascade RCNN with OHEMSampler

### ISSUE THREAD

**Issue by liaopeiyuan** [open-mmlab/mmdetection#3074]
Is it true that this is supported in v1.x, but not yet for v2.x?

I saw that before the TwoStageDetector abstraction appears, it is possible to create OHEMSampler with Cascade RCNN's extractor as a context, and OHEMSampler in v2.x do check for num_stages (implying that at one time cascade rcnn) works, but now it seems that in init_assigner_sampler, there is no entry point to create new sampler that takes into account for contexts.

My current work-around looks like this:

- initialize a variable, say a = 0
- set current_stage attribute of the roi layer to be a
- whenever it builds a sampler in the for loop, set ['context'] of the confg dict to be self
- increments a by one, and updates the current_stage attribute

Since I'm not familiar with v2.x setup, does this work? (aka does the bbox_roi_extractor in the sampler update with backprop of the original model during training). Also, apparently this breaks the yapf pretty formatting, for some strange reasons as well.

**Comment by hellock** [comment]
We do not think OHEM useful for Cascade R-CNN, thus we remove the support to make the code clean and simple. The workaround sounds doable.
