### ISSUE TITLE
question about area and 11points modes in eval_map

### ISSUE THREAD

**Issue by aabramovrepo** [open-mmlab/mmdetection#3076]
Hi All,

   I'm training `Faster R-CNN` with `FPN` on a custom data set in `PASCAL VOC` format. I see two modes in the `eval_map` function: `area` and `11points`, at the first glance both produce very similar numbers. What is the main difference between them and which one is more preferable to use?

Thanks!

Best,
Alexey

**Comment by hellock** [comment]
`11points` use only 11 points in the precision-recall curve for average while `area` use all points. The former is the default evaluation metric in voc07 and the latter is the default metric in voc12. `area` is more precise and preferable personally.

**Comment by aabramovrepo** [comment]
@hellock thanks for the very clear response!
