### ISSUE TITLE
stuck in runing test.py!!

### ISSUE THREAD

**Issue by zhangyu96** [open-mmlab/mmdetection#3084]
when i test a dataset acoording to the 'getting_started.md' , I  run the command as follows:
_**python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --show**_.
But the processing is stucked in the first row as :
**_loading annotations into memory...
Done (t=0.67s)
creating index...
index created!
[                                                  ] 0/5000, elapsed: 0s, ETA:_**.
And there is no error reported. 
any help is appreciated.
thanks!

**Comment by hellock** [comment]
`--show` means displaying the image in a window. If you are using a server without GUI, then it will get stuck.

**Comment by zhangyu96** [comment]
> `--show` means displaying the image in a window. If you are using a server without GUI, then it will get stuck.

It is same when i use '--show-dir' and '--eval mAP'!

**Comment by hellock** [comment]
Please follow the `Error report` issue template to provide necessary information.

**Comment by zhangyu96** [comment]
> Please follow the `Error report` issue template to provide necessary information.

(mmdet) d1999@1999D-Tower:~/ZY/mmdetection$ python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --show-dir results
In /home/d1999/anaconda3/envs/mmdet/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/d1999/anaconda3/envs/mmdet/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/d1999/anaconda3/envs/mmdet/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
loading annotations into memory...
Done (t=0.50s)
creating index...
index created!
[                                                                 ] 0/5000, elapsed: 0s, ETA:^C

**Comment by hellock** [comment]
Please follow the [Error report](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) issue template to provide necessary information. Just click `Error report` when you create a new issue.

**Comment by Chenyusheng97** [comment]
> > Please follow the `Error report` issue template to provide necessary information.
> 
> (mmdet) d1999@1999D-Tower:~/ZY/mmdetection$ python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --show-dir results
> In /home/d1999/anaconda3/envs/mmdet/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
> The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
> In /home/d1999/anaconda3/envs/mmdet/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
> The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
> In /home/d1999/anaconda3/envs/mmdet/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle:
> The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
> loading annotations into memory...
> Done (t=0.50s)
> creating index...
> index created!
> [ ] 0/5000, elapsed: 0s, ETA:^C

I met the same problems.Have you solve it?
