### ISSUE TITLE
I 0It seems the custom optimizer documentation is out of date. How to use custom optimizer after the cleaning of optimizer code?

### ISSUE THREAD

**Issue by LorenzoQ5** [open-mmlab/mmdetection#3086]
It seems the custom optimizer documentation is out of date. How to use custom optimizer after the cleaning of optimizer code?

_Origin0ally posted by @hiyyg in https://github.com/open-mmlab/mmdetection/issues/2041#issuecomment-647065657_

**Comment by LorenzoQ5** [comment]
babyjesusq5@gmail.com

**Comment by hellock** [comment]
https://mmdetection.readthedocs.io/en/latest/tutorials/new_modules.html#customize-optimizer

**Comment by hiyyg** [comment]
This doc is out of date.

**Comment by hiyyg** [comment]
#3092

**Comment by hellock** [comment]
> Hi, @hellock , this doc is out of date. The custom optimizer code has been removed in mmdet.

Thanks for pointing out the issue. It is moved to mmcv and we will update the doc soon.
