### ISSUE TITLE
Question about img_scale for multi-scale training

### ISSUE THREAD

**Issue by lisosia** [open-mmlab/mmdetection#3095]
I am interested in multi scale training/testing and 
checked some configs for multi scale training/testing (for example [this one](https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/fcos_r50_caffe_fpn_gn-head_mstrain_640-800_4x4_2x_coco.py#L22))

They use fixed width img_scale.
Also, height range is `[test-height / CONST, test-height]` and bigger height (compared to test heigth) is not used. 

Would it be more reasonable to train **around** test-time resolution.
For example, if test scale is (1333, 800), train scale would be  
`img_scale=[(1333 / CONST, 800 / CONST), (1333 * CONST, 800 * CONST)]`

Is there any reason for current img_scale settings for multi-scale training?

**Comment by hellock** [comment]
Both settings are applicable, and it depends on the GPU memory.

**Comment by lisosia** [comment]
Thanks for your responce. I got the reason bigger resolution is not used.

Another question is:  Why is the width fixed?
Is it just a tradition?

**Comment by ZwwWayne** [comment]
Yes, it is a tradition.
