### ISSUE TITLE
Training across nodes on the cluster managed with PBS

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#3096]
Hi, I am aware that there is one script in mmdetection for training on a cluster which is managed by SLURM. But our cluster is managed by portable batch system (PBS). I would like to train my detector across nodes, say, use 8 gpus across 2 nodes. So how can I do it? 

I have tried using the dist_train.py and setting `--nproc_per_node= 4 or 8`, but it didn't work in the way I have thought. When setting `--nproc_per_node=4`, only 4 gpus were actually used, and setting `--nproc_per_node=8`, the training failed. 

Thank you.

**Comment by hellock** [comment]
We have no experience with PBS. You may need to add support to it like [this](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/dist_utils.py#L38).

**Comment by hyz-xmaster** [comment]
Thanks for the help.
