### ISSUE TITLE
How to use synchronous batch normalization?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmdetection#3100]
Hi,

how to use synchronous batch normalization in mmdetection? is it ready for using?

**Comment by PanJianning** [comment]
[Example](https://github.com/open-mmlab/mmdetection/blob/88d042a1e4555cb263d8811b78a157415b93d233/configs/gcnet/mask_rcnn_r101_fpn_syncbn-backbone_1x_coco.py#L4)
