### ISSUE TITLE
Comparing Predicted Instance Segmentation with Ground Truth

### ISSUE THREAD

**Issue by azibit** [open-mmlab/mmdetection#3103]
Hi,
I am testing my instance segmentation model and wanted to compare the results of the model with the ground truth. 

Anyone knows of how to achieve that directly in mmdetection?

**Comment by azibit** [comment]
Figured it out

**Comment by andersonsantos3** [comment]
Hi,

Could you describe what you did, please? Does this work for bbox?

Thank you

**Comment by zachbellay** [comment]
Hey @azibit, would you mind elaborating on how you achieved this?

**Comment by azibit** [comment]
Hi,
@zachbellay What I did was write up a new code that checks the number of ground truth images from my coco labeling and then compares that with the predictions using a certain threshold for the IoU. This is done for each of the images. This is what I had to do. Do let me know if that helps or if we could have other ways to communicate

**Comment by zachbellay** [comment]
Hi @azibit, do you happen to have the code you wrote to perform this? This seems very useful!

**Comment by azibit** [comment]
Hi @zachbellay I hope what I have helps. You can check my code at https://colab.research.google.com/drive/1FzdsbJyMOeZat6Td6ovTv58yVC1vX1F6?usp=sharing

Do let me know if that helps

**Comment by zachbellay** [comment]
Hi @azibit, thank you! I'll be going over your code and adapting it to my needs. Your time and help is much appreciated!

**Comment by azibit** [comment]
You are most welcome. I hope the code helps you as much as it helped me. Feel free to reach out if you have any more questions. Thanks

**Comment by TuanNguyenSKKU** [comment]
hi @azibit , can you tell me how to get the bbox_pred_file (.bbox.json) in mmdetection?
I really hope to receive your support. 
Thank you!
