### ISSUE TITLE
Bugs which Prevent Training Runs from Starting

### ISSUE THREAD

**Issue by CMobley7** [open-mmlab/mmdetection#3105]
So, first off I want to thank you for making such a great platform for the training of object detectors. I used it in the past week and a half to train 100+ object detectors on several different PCs with different sets of GPUs. For the most part it works great; however, there are two common bugs I've run into at the beginning of training that prevent a run from starting. I can't figure out why these errors occur, but I figured I would let you know since I've seen them across different computers using 1.x, 2.0, and 2.1.

The first one occurs when the model finished downloading, showing 100%, but hangs there and training never starts, even after leaving it for a few hours. This happens like 1x for every 4-5 runs. The seconds, which I've included the error report below, happens like 1x for every 2-3 runs.

```
Traceback (most recent call last):
  File "/podc/src/mmdet/tools/train.py", line 161, in <module>
    main()
  File "/podc/src/mmdet/tools/train.py", line 92, in main
    cfg.optimizer['lr'] = cfg.optimizer['lr'] * len(cfg.gpu_ids) / 8
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/config.py", line 324, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/config.py", line 36, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'optimizer'
```

With both of these issues, if I just restart the training job, the issue doesn't occur again, until another few models down the line.

**Comment by hellock** [comment]
For the first issue, it may be because all processes are downloading the checkpoint to the same path. We will fix it. Before that you can try downloading the checkpoint before the first run.
For the second one, it looks weird and we have never met it before.

**Comment by ZwwWayne** [comment]
Hi @CMobley7 ,
Could you post the corresponding config thus we could debug it?

**Comment by ZwwWayne** [comment]
Since there is no response, this issue is closed. Please create a new issue following the `issue template` if the issues occur again.
