### ISSUE TITLE
After_train_epoch test erro when train in 2 gpus.

### ISSUE THREAD

**Issue by JunLeecus** [open-mmlab/mmdetection#3108]
**Describe the bug**
I train my model using "tools/train.py" by setting  "--gpus 2", train successfully but test after per epoch raise erro.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/cascade_rcnn/cascade_rcnn_x101_32x4d_fpn_1x_coco.py --gpus 2
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I change the model config to read VOC style data by change "coco_detection.py" to "voc0712.py". It seems no wrong because I can successfully train.  Then I try to find the answer by set train and test pic to a small num. I found,  if I train in 2 gpus, test raise erro but train narmally. when I train only in 1 gpu, both normally.
I think maybe due to test called class "EvalHook" and use single_gpu_test? It makes conflict? I try to use "--launcher pytorch" in train.py to change it to multi_gpu_test, but it raise another erro. 
3. What dataset did you use?
pasaclVOC dataset.

**Environment**
1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1: Tesla V100-SXM2-32GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.3 Product Build 20190125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.1.1
MMCV: 0.6.1
MMDetection: 2.0.0+unknown
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0

2. You may add addition that may be helpful for locating the problem, such as
    Install pytorch by conda

**Error traceback**
```
run "python tools/train.py configs/cascade_rcnn/cascade_rcnn_x101_32x4d_fpn_1x_coco.py --gpus 2"
2020-06-23 03:21:32,579 - mmdet - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/4, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    meta=meta)
  File "/root/lijun/pedestrian_det/mmdetection-master/mmdet/apis/train.py", line 179, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 46, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 282, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/lijun/pedestrian_det/mmdetection-master/mmdet/core/evaluation/eval_hooks.py", line 27, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/root/lijun/pedestrian_det/mmdetection-master/mmdet/apis/test.py", line 26, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: expected sequence object with len >= 0 or a single integer
---------------------------------------------
add param "--laucher pytorch"
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 99, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 28, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/opt/conda/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```

**Comment by y78h11b09** [comment]
> **Describe the bug**
> I train my model using "tools/train.py" by setting "--gpus 2", train successfully but test after per epoch raise erro.
> 
> **Reproduction**
> 
> 1. What command or script did you run?
> 
> ```
> python tools/train.py configs/cascade_rcnn/cascade_rcnn_x101_32x4d_fpn_1x_coco.py --gpus 2
> ```
> 
> 1. Did you make any modifications on the code or config? Did you understand what you have modified?
>    I change the model config to read VOC style data by change "coco_detection.py" to "voc0712.py". It seems no wrong because I can successfully train.  Then I try to find the answer by set train and test pic to a small num. I found,  if I train in 2 gpus, test raise erro but train narmally. when I train only in 1 gpu, both normally.
>    I think maybe due to test called class "EvalHook" and use single_gpu_test? It makes conflict? I try to use "--launcher pytorch" in train.py to change it to multi_gpu_test, but it raise another erro.
> 2. What dataset did you use?
>    pasaclVOC dataset.
> 
> **Environment**
> 
> 1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
>    sys.platform: linux
>    Python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
>    CUDA available: True
>    CUDA_HOME: /usr/local/cuda
>    NVCC: Cuda compilation tools, release 10.0, V10.0.130
>    GPU 0,1: Tesla V100-SXM2-32GB
>    GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
>    PyTorch: 1.4.0
>    PyTorch compiling details: PyTorch built with:
> 
> * GCC 7.3
> * Intel(R) Math Kernel Library Version 2019.0.3 Product Build 20190125 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * NNPACK is enabled
> * CUDA Runtime 10.0
> * NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
> * CuDNN 7.6.3
> * Magma 2.5.1
> * Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
> 
> TorchVision: 0.5.0
> OpenCV: 4.1.1
> MMCV: 0.6.1
> MMDetection: 2.0.0+unknown
> MMDetection Compiler: GCC 5.4
> MMDetection CUDA Compiler: 10.0
> 
> 1. You may add addition that may be helpful for locating the problem, such as
>    Install pytorch by conda
> 
> **Error traceback**
> 
> ```
> run "python tools/train.py configs/cascade_rcnn/cascade_rcnn_x101_32x4d_fpn_1x_coco.py --gpus 2"
> 2020-06-23 03:21:32,579 - mmdet - INFO - Saving checkpoint at 1 epochs
> [                                                  ] 0/4, elapsed: 0s, ETA:Traceback (most recent call last):
>   File "tools/train.py", line 161, in <module>
>     main()
>   File "tools/train.py", line 157, in main
>     meta=meta)
>   File "/root/lijun/pedestrian_det/mmdetection-master/mmdet/apis/train.py", line 179, in train_detector
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 46, in train
>     self.call_hook('after_train_epoch')
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 282, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/root/lijun/pedestrian_det/mmdetection-master/mmdet/core/evaluation/eval_hooks.py", line 27, in after_train_epoch
>     results = single_gpu_test(runner.model, self.dataloader, show=False)
>   File "/root/lijun/pedestrian_det/mmdetection-master/mmdet/apis/test.py", line 26, in single_gpu_test
>     result = model(return_loss=False, rescale=True, **data)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
>     return self.gather(outputs, self.output_device)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
>     return gather(outputs, output_device, dim=self.dim)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
>     res = gather_map(outputs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
>     return type(out)(map(gather_map, zip(*outputs)))
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
>     return type(out)(map(gather_map, zip(*outputs)))
> TypeError: expected sequence object with len >= 0 or a single integer
> ---------------------------------------------
> add param "--laucher pytorch"
> Traceback (most recent call last):
>   File "tools/train.py", line 161, in <module>
>     main()
>   File "tools/train.py", line 99, in main
>     init_dist(args.launcher, **cfg.dist_params)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 17, in init_dist
>     _init_dist_pytorch(backend, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 28, in _init_dist_pytorch
>     rank = int(os.environ['RANK'])
>   File "/opt/conda/lib/python3.6/os.py", line 669, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'RANK'
> ```

Hi, has  your question been sloved ?

**Comment by xvjiarui** [comment]
When using multi GPU evaluation, you should run in distributed mode.
