### ISSUE TITLE
Does retinanet support PAFPN and how to add it?

### ISSUE THREAD

**Issue by madexin** [open-mmlab/mmdetection#3109]
I follow the method of configuring PAFPN in faster r-cnn to configure retinanet, which can be trained, but the detection rate of training is basically 0.The method I configured is to simply replace FPN with PAFPN, and comment out start_level=1 and add_extra_convs='on_input'.

Does retinanet support PAFPN and how to add it?

**Comment by yhcao6** [comment]
You can create a config that inherits the normal Retinanet and replace `neck_type 'FPN` with `neck_type 'PAFPN'`.
