### ISSUE TITLE
how to train from scratch?

### ISSUE THREAD

**Issue by notfox** [open-mmlab/mmdetection#311]
example, train from scratch with GN,thanks

**Comment by hellock** [comment]
You need to set `pretrained` to None and `norm_eval` to False compared to imagenet pretraining.
Here is an example.
```python
# model settings
normalize = dict(type='GN', num_groups=32)

model = dict(
    type='MaskRCNN',
    pretrained=None,
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch',
        normalize=normalize,
        norm_eval=False),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5,
        normalize=normalize),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        use_sigmoid_cls=True),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=dict(
        type='ConvFCBBoxHead',
        num_shared_convs=4,
        num_shared_fcs=1,
        in_channels=256,
        conv_out_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=81,
        target_means=[0., 0., 0., 0.],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        reg_class_agnostic=False,
        normalize=normalize),
    mask_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=14, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    mask_head=dict(
        type='FCNMaskHead',
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=81,
        normalize=normalize))

# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        smoothl1_beta=1 / 9.0,
        debug=False),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        mask_size=28,
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_thr=0.5),
        max_per_img=100,
        mask_thr_binary=0.5))
# dataset settings
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[102.9801, 115.9465, 122.7717], std=[1.0, 1.0, 1.0], to_rgb=False)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=True,
        with_crowd=True,
        with_label=True),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=True,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[28, 34])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 36
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/mask_rcnn_r50_fpn_gn_2x'
load_from = None
resume_from = None
workflow = [('train', 1)]
```

**Comment by notfox** [comment]
> You need to set `pretrained` to None and `norm_eval` to False compared to imagenet pretraining.
> Here is an example.
> 
> ```python
> # model settings
> normalize = dict(type='GN', num_groups=32)
> 
> model = dict(
>     type='MaskRCNN',
>     pretrained=None,
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         style='pytorch',
>         normalize=normalize,
>         norm_eval=False),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         num_outs=5,
>         normalize=normalize),
>     rpn_head=dict(
>         type='RPNHead',
>         in_channels=256,
>         feat_channels=256,
>         anchor_scales=[8],
>         anchor_ratios=[0.5, 1.0, 2.0],
>         anchor_strides=[4, 8, 16, 32, 64],
>         target_means=[.0, .0, .0, .0],
>         target_stds=[1.0, 1.0, 1.0, 1.0],
>         use_sigmoid_cls=True),
>     bbox_roi_extractor=dict(
>         type='SingleRoIExtractor',
>         roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
>         out_channels=256,
>         featmap_strides=[4, 8, 16, 32]),
>     bbox_head=dict(
>         type='ConvFCBBoxHead',
>         num_shared_convs=4,
>         num_shared_fcs=1,
>         in_channels=256,
>         conv_out_channels=256,
>         fc_out_channels=1024,
>         roi_feat_size=7,
>         num_classes=81,
>         target_means=[0., 0., 0., 0.],
>         target_stds=[0.1, 0.1, 0.2, 0.2],
>         reg_class_agnostic=False,
>         normalize=normalize),
>     mask_roi_extractor=dict(
>         type='SingleRoIExtractor',
>         roi_layer=dict(type='RoIAlign', out_size=14, sample_num=2),
>         out_channels=256,
>         featmap_strides=[4, 8, 16, 32]),
>     mask_head=dict(
>         type='FCNMaskHead',
>         num_convs=4,
>         in_channels=256,
>         conv_out_channels=256,
>         num_classes=81,
>         normalize=normalize))
> 
> # model training and testing settings
> train_cfg = dict(
>     rpn=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.7,
>             neg_iou_thr=0.3,
>             min_pos_iou=0.3,
>             ignore_iof_thr=-1),
>         sampler=dict(
>             type='RandomSampler',
>             num=256,
>             pos_fraction=0.5,
>             neg_pos_ub=-1,
>             add_gt_as_proposals=False),
>         allowed_border=0,
>         pos_weight=-1,
>         smoothl1_beta=1 / 9.0,
>         debug=False),
>     rcnn=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.5,
>             neg_iou_thr=0.5,
>             min_pos_iou=0.5,
>             ignore_iof_thr=-1),
>         sampler=dict(
>             type='RandomSampler',
>             num=512,
>             pos_fraction=0.25,
>             neg_pos_ub=-1,
>             add_gt_as_proposals=True),
>         mask_size=28,
>         pos_weight=-1,
>         debug=False))
> test_cfg = dict(
>     rpn=dict(
>         nms_across_levels=False,
>         nms_pre=2000,
>         nms_post=2000,
>         max_num=2000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=dict(
>         score_thr=0.05,
>         nms=dict(type='nms', iou_thr=0.5),
>         max_per_img=100,
>         mask_thr_binary=0.5))
> # dataset settings
> dataset_type = 'CocoDataset'
> data_root = 'data/coco/'
> img_norm_cfg = dict(
>     mean=[102.9801, 115.9465, 122.7717], std=[1.0, 1.0, 1.0], to_rgb=False)
> data = dict(
>     imgs_per_gpu=2,
>     workers_per_gpu=2,
>     train=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/instances_train2017.json',
>         img_prefix=data_root + 'train2017/',
>         img_scale=(1333, 800),
>         img_norm_cfg=img_norm_cfg,
>         size_divisor=32,
>         flip_ratio=0.5,
>         with_mask=True,
>         with_crowd=True,
>         with_label=True),
>     val=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/instances_val2017.json',
>         img_prefix=data_root + 'val2017/',
>         img_scale=(1333, 800),
>         img_norm_cfg=img_norm_cfg,
>         size_divisor=32,
>         flip_ratio=0,
>         with_mask=True,
>         with_crowd=True,
>         with_label=True),
>     test=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/instances_val2017.json',
>         img_prefix=data_root + 'val2017/',
>         img_scale=(1333, 800),
>         img_norm_cfg=img_norm_cfg,
>         size_divisor=32,
>         flip_ratio=0,
>         with_mask=False,
>         with_label=False,
>         test_mode=True))
> # optimizer
> optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
> optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
> # learning policy
> lr_config = dict(
>     policy='step',
>     warmup='linear',
>     warmup_iters=500,
>     warmup_ratio=1.0 / 3,
>     step=[28, 34])
> checkpoint_config = dict(interval=1)
> # yapf:disable
> log_config = dict(
>     interval=50,
>     hooks=[
>         dict(type='TextLoggerHook'),
>         # dict(type='TensorboardLoggerHook')
>     ])
> # yapf:enable
> # runtime settings
> total_epochs = 36
> dist_params = dict(backend='nccl')
> log_level = 'INFO'
> work_dir = './work_dirs/mask_rcnn_r50_fpn_gn_2x'
> load_from = None
> resume_from = None
> workflow = [('train', 1)]
> ```

thank you，i will try it

**Comment by youngwanLEE** [comment]
I have a question. 

Since oth box and mask head also have GN normalization, these need to be `norm_eval` to False?

**Comment by tim20120526** [comment]
> I have a question.
> 
> Since both box and mask head also have GN normalization, these need to be `norm_eval` to False?
> 
> Anyway,
> 
> Could you share the results about GN from scratch like [this](https://github.com/facebookresearch/Detectron/tree/master/projects/GN#training-mask-r-cnn-from-scratch)?

just for bn.

**Comment by AAA-Fan** [comment]
How about frozen_stages? Why is it 1? if training from scratch, we also need to train stage 1, right?

**Comment by joihn** [comment]
I think @AAA-Fan is right, `frozen-stage `should also be removed

**Comment by lionReichl2357** [comment]
Hey, I am trying to train from scratch. But I think pretrained is not supported anymore. It allways tells me that 'pretrained' is an invalid input

**Comment by Petros626** [comment]
@hellock does this count for `mmrotate` too?

**Comment by Petros626** [comment]
> Hey, I am trying to train from scratch. But I think pretrained is not supported anymore. It allways tells me that 'pretrained' is an invalid input

'Pretrained' instead of `pretrained` I guess.
