### ISSUE TITLE
Failed to compile  sigmoid_focal_loss_cuda.cu   Under   win10

### ISSUE THREAD

**Issue by nothingws** [open-mmlab/mmdetection#3111]
Failed to compile               # make_cuda_ext(
            #     name='sigmoid_focal_loss_ext',
            #     module='mmdet.ops.sigmoid_focal_loss',
            #     sources=['src/sigmoid_focal_loss_ext.cpp'],
            #     sources_cuda=['src/cuda/sigmoid_focal_loss_cuda.cu']),

vs2017 cuda10.1 pytorch1.3

**Comment by ZwwWayne** [comment]
Should have be resolved in MMCV.
