### ISSUE TITLE
How to use pytorch ops instead of ATen ops?

### ISSUE THREAD

**Issue by Syencil** [open-mmlab/mmdetection#3118]
I successfully converted the model into onnx. But it can not converted into tensorRT directly. It seems mmdet override some basic operations in C++. 
For example, in mmdet/core/bbox/transforms.py line 67. img_inds = bboxes.new_full((bboxes.size(0), 1), img_id).
There seem to be two implementations here. One is in (_TensorBase in torch._C._TensorBase), another is in (Tensor in torch).
I m wondering how to use these operations which implemented in native pytorch.

**Comment by hellock** [comment]
We did not override basic operations in C++. The ONNX export totally rely on the official pytorch API.
