### ISSUE TITLE
./complie.sh error (gpu_nms)

### ISSUE THREAD

**Issue by 01lin** [open-mmlab/mmdetection#312]
building 'gpu_nms' extension
gcc -pthread -B /home1/neal/anaconda3/envs/tmm-pt/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home1/neal/anaconda3/envs/tmm-pt/lib/python3.6/site-packages/numpy/core/include -I/home1/neal/anaconda3/envs/tmm-pt/include/python3.6m -c gpu_nms.cpp -o build/temp.linux-x86_64-3.6/gpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ?.Wstrict-prototypes?.is valid for C/ObjC but not for C++
In file included from /home1/neal/anaconda3/envs/tmm-pt/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1818:0,
                 from /home1/neal/anaconda3/envs/tmm-pt/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home1/neal/anaconda3/envs/tmm-pt/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:657:
/home1/neal/anaconda3/envs/tmm-pt/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
nvcc -I/home1/neal/anaconda3/envs/tmm-pt/lib/python3.6/site-packages/numpy/core/include -I/home1/neal/anaconda3/envs/tmm-pt/include/python3.6m -c nms_kernel.cu -o build/temp.linux-x86_64-3.6/nms_kernel.o -c --compiler-options -fPIC
nvcc fatal   : Path to libdevice library not specified
error: command 'nvcc' failed with exit status 1
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by hellock** [comment]
Looks like a cuda installation issue.
You may refer to https://devtalk.nvidia.com/default/topic/804501/libdevice-library-not-found-by-nvcc/ or search google with the keyword "Path to libdevice library not specified".

**Comment by hellock** [comment]
The nms op is rewritten and such error is unlikely to occur. Feel free to reopen it for further problems.
