### ISSUE TITLE
Why aren't annotations loaded in the test pipeline?

### ISSUE THREAD

**Issue by quinquice** [open-mmlab/mmdetection#3121]
I'm trying to train a Faster-RCNN model on the COCO dataset with augmented class labels. I think I can easily change the labels when training by adding a custom data pipeline after LoadAnnotations, but I would also like to test and validate using the same relabeling. However, it doesn't appear that the annotations are ever even loaded into the test pipeline. What is the reason for this, and is there a workaround for my problem? If not, how can I easily modify the entire annotation file to reflect the label changes I want?

**Comment by ceykmc** [comment]
The dataset 'evaluate' method is invoked in test.py.

in evaluate method, with get_ann_info method, it will load annotation.

**Comment by quinquice** [comment]
Thank you. I have decided to create a copy of the labels and augment them manually instead of attempting to do so in the train/test pipeline.
