### ISSUE TITLE
wider face config, ssd300_wider_face.py , why num_classes is 2?

### ISSUE THREAD

**Issue by ceykmc** [open-mmlab/mmdetection#3123]
in mmdet/datasets/wider_face.py, CLASSES only have "face"

using the config to generate wider face dataset, each sample's label is zero

should the num_classes be 1 not 2 ?

**Comment by chuong98** [comment]
num_classes=2 including background class. This is the old config from v1.x

**Comment by hellock** [comment]
This could be a bug.

**Comment by ceykmc** [comment]
I think the num_classes should be 1.
if num class is 2, the background_label is 2, the label 0 is for face, the label 1 has no meaning.

**Comment by ZwwWayne** [comment]
Hi @ceykmc ,
Thanks for your bug report. I checked the [config in v1.0](https://github.com/open-mmlab/mmdetection/blob/v1.0.0/configs/wider_face/ssd300_wider_face.py#L20), the `num_classes` is 2. So it should be a bug where we forget to modify it consistently when we upgrading to V2.0.
