### ISSUE TITLE
Bag of Freebies for Training Object Detection Neural Networks

### ISSUE THREAD

**Issue by mathmanu** [open-mmlab/mmdetection#3124]
**Describe the feature**
Is it possible to support the training improvements described in the following paper:
"Bag of Freebies for Training Object Detection Neural Networks"
Zhi Zhang, Tong He, Hang Zhang, Zhongyue Zhang, Junyuan Xie, Mu Li
https://arxiv.org/pdf/1902.04103.pdf

**Motivation**
It seems the "Bag of Freebies" provide significant accuracy improvement (+5%) in a single shot detector such as YOLOv3. It improves Faster-RCNN by upto 1.7%. It is likely that these features will improve other detectors as well.

**Related resources**
https://medium.com/apache-mxnet/gluoncv-0-3-a-new-horizon-564326364e16
https://gluon-cv.mxnet.io/model_zoo/detection.html

**Additional context**
I think implementing these features would give accuracy lift to several object detectors in mmdetection.

**Comment by hellock** [comment]
Thanks for the suggestion and you may add this feature request to the pinned issue (MMDetection Roadmap).

**Comment by mathmanu** [comment]
Thanks.
