### ISSUE TITLE
RuntimeError: input tensor has to be contiguous with DCNv2 on Res2Net

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmdetection#3129]
Hi, I am trying to add DCNv2 on Res2Net backbone. Interestingly, I got an `RuntimeError: input tensor has to be contiguous` with batch size = 2 but when I set batch size = 1, the error was gone. This bug also didn't appear on DCNv1.

**Comment by PanJianning** [comment]
I met this problem before. Adding [this line](https://github.com/PanJianning/cbnet/blob/master/res2net.py#L179) may help.

**Comment by zehuichen123** [comment]
> I met this problem before. Adding [this line](https://github.com/PanJianning/cbnet/blob/master/res2net.py#L179) may help.

Thanks! I will give it a try~

**Comment by hyz-xmaster** [comment]
Hi, @zehuichen123, I have also run into the exactly same problem and tried the fix given by @PanJianning, but it seems that the fix doesn't work.  Have you solved the problem? Thank you.

**Comment by hyz-xmaster** [comment]
> Hi, @zehuichen123, I have also run into the exactly same problem and tried the fix given by @PanJianning, but it seems that the fix doesn't work. Have you solved the problem? Thank you.

One possible solution would be to change [`sp = self.convs[0](spx[0])`](https://github.com/open-mmlab/mmdetection/blob/d613f216b2d9fa9dab3eaa4747f980cc386fb258/mmdet/models/backbones/res2net.py#L118) into `sp = self.convs[0](spx[0].contiguous())` and change  [`sp = self.convs[i](sp)`](https://github.com/open-mmlab/mmdetection/blob/d613f216b2d9fa9dab3eaa4747f980cc386fb258/mmdet/models/backbones/res2net.py#L126) into `sp = self.convs[i](sp.contiguous())`

**Comment by shinya7y** [comment]
I met this problem also with DCNv1.
@hyz-xmaster's solution fixed both DCN version on my environment, so I sent PR.
