### ISSUE TITLE
U^2-Net (U square net) in mmdetection

### ISSUE THREAD

**Issue by muhammadabdullah34907** [open-mmlab/mmdetection#3131]
Hi @ZwwWayne 
Any plan to add this method in future. I believe it's best feature for smooth masking of objects. 

https://github.com/NathanUA/U-2-Net
U^2-Net: Going Deeper with Nested U-Structure for Salient Object Detection

**Comment by hellock** [comment]
PRs are welcome. You may add the feature request to the pinned issue (MMDetection Roadmap).

**Comment by timiil** [comment]
any update for this ?
