### ISSUE TITLE
Bounding boxes not showing on the result demo image

### ISSUE THREAD

**Issue by OdysseeT** [open-mmlab/mmdetection#3135]
I simply run the _inference_demo_ notebook from the Docker image, and I don't get the bounding boxes on the result image.
The returned result from ```result = inference_detector(model, img)``` is a list of empty arrays.

**Reproduction**
1. What command or script did you run?
```
sudo docker build -t mmdetection docker/
sudo docker run --gpus all  -p 8888:8888  --rm -it mmdetection

# inside the container
wget -P checkpoints https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
```
I get the same result if i run the script
```
python image_demo.py demo.jpg \
'../configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'  \
'../checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, I haven't modified the code of the notebook nor the default script

3. What dataset did you use?
I used the default image from the notebook: 'demo.jpg'

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: TITAN RTX
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 0.6.2
MMDetection: 2.1.0+792273b
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.1

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
x I haven't installed Pytorch as I used the DockerFile.
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
x None

**Error traceback**
If applicable, paste the error trackback here.

There is no error. Just UserWarnings.
I don't consider the **The model and loaded state dict do not match exactly** as an error as mentioned here: #1151

![Screenshot from 2020-06-27 15-40-37](https://user-images.githubusercontent.com/8287111/85923947-791d0300-b88f-11ea-8be1-1aea72645823.png)

**Comment by OdysseeT** [comment]
Seems to be coming from the checkpoint:
https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth

By using the checkpoint from the colab notebook, it works:
**https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth**

**Comment by hellock** [comment]
We rebenchmarked all models in V2.0 and the old ones are deprecated. Please refer to [compatibility.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md) for details.

**Comment by ronit450** [comment]
I am getting this error? I have trained my own model and when using the checkpoint and config file It gives error
