### ISSUE TITLE
ssd voc dataset meet error

### ISSUE THREAD

**Issue by rrjia** [open-mmlab/mmdetection#3141]
python tools/train.py configs/pascal_voc/ssd300_voc0712.py

File /mmdetection-master/mmdet/models/dense_heads/anchor_head.py", line 331, in get_targets
    labels_list = images_to_levels(all_labels, num_level_anchors) 
File "/mmdetection-master/mmdet/core/anchor/utils.py", line 9, in images_to_levels
    target = torch.stack(target, 0)
RuntimeError: stack expects each tensor to be equal size, but got [45690] at entry 0 and [51136] at entry 1

**Comment by v-qjqs** [comment]
Hi @rrjia, there is no error in my experiments. Counld you please use the latest mmdection and mmcv?
