### ISSUE TITLE
why fix 256 training anchors when training RPN?

### ISSUE THREAD

**Issue by bxhandhxb** [open-mmlab/mmdetection#3149]
hi 
I know we sample positive and negative anchors for class balancing. But the ground truth is got before training RPN.
Why not just set negative anchors number equal to the positive anchors?   I mean, if there are 50 positive anchors, we can set the negative num to be 50 instead of 206(256-50==206). Similarly, if there are 250 positive anchors, we can set the negative anchor num to be 250 instead of 128.
I'm confused. Is there any important reason to fix 256 training anchors?

**Comment by Shallowte** [comment]
Hi,
I think 256 is [kind of] an arbitrary number that [kind of] guarantees a good balance between positives and negatives. This balance depends on your data and the results you want to obtain (higher recall vs higher precision), and I don't think there is a good number. 

On the other hand, in case you did not notice, you can play with the parameter `neg_pos_ub` to obtain the balance you desire between positives and negatives: 
`Number of negatives = neg_pos_ub * min(1, Number of positives)` 
For what you described, you can set it to 1.

Cheers,

**Comment by bxhandhxb** [comment]
> Hi,
> I think 256 is [kind of] an arbitrary number that [kind of] guarantees a good balance between positives and negatives. This balance depends on your data and the results you want to obtain (higher recall vs higher precision), and I don't think there is a good number.
> 
> On the other hand, in case you did not notice, you can play with the parameter `neg_pos_ub` to obtain the balance you desire between positives and negatives:
> `Number of negatives = neg_pos_ub * min(1, Number of positives)`
> For what you described, you can set it to 1.
> 
> Cheers,
Thanks.  BTW,  do you think it's necessary to adjust the parameter (256) for training model in different datasets ?

**Comment by bxhandhxb** [comment]
> Hi,
> I think 256 is [kind of] an arbitrary number that [kind of] guarantees a good balance between positives and negatives. This balance depends on your data and the results you want to obtain (higher recall vs higher precision), and I don't think there is a good number.
> 
> On the other hand, in case you did not notice, you can play with the parameter `neg_pos_ub` to obtain the balance you desire between positives and negatives:
> `Number of negatives = neg_pos_ub * min(1, Number of positives)`
> For what you described, you can set it to 1.
> 
> Cheers,



Thanks. BTW, do you think it's necessary to adjust the parameter (256) for training model in different datasets ?

**Comment by ZwwWayne** [comment]
You can have a try. Usually, you need to tune those hyperparameters first if you meet a new dataset.
