### ISSUE TITLE
ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by zhangshen12356** [open-mmlab/mmdetection#3152]
i would like to test the result of training, so i write the next:
(base) zhangshen@zhangshen-X550JX:~/mmdetection$ python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --out./result/result_100/pkl --eval bbox

but i got:
Traceback (most recent call last):
  File "tools/test.py", line 9, in <module>
    from tools.fuse_conv_bn import fuse_module
ModuleNotFoundError: No module named 'tools'

how can i solve this problem?

**Comment by yhcao6** [comment]
#2667.

**Comment by hellock** [comment]
@yhcao6 Either fix the tool script or update the documentation.

**Comment by zhangshen12356** [comment]
> @yhcao6 Either fix the tool script or update the documentation.

how can i fix the tool script  or which doucumentation should i update?

**Comment by yhcao6** [comment]
I have created a pr to fix the error-report template, #3192 . Thanks for reporting the error.
