### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by WHAOOOOO** [open-mmlab/mmdetection#3154]
Compiled successfully。

Error when running training and testing：
RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/Loops.cuh:103)

ubuntu16.04   cuda10.0.130    pytorch1.4.0   python3.7.4

**Comment by ZwwWayne** [comment]
Please use the `Error template`. This might be because the Pytorch version is incompatible with your CUDA version.

**Comment by YachaoDong** [comment]
> Compiled successfully。
> 
> Error when running training and testing：
> RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/Loops.cuh:103)
> 
> ubuntu16.04 cuda10.0.130 pytorch1.4.0 python3.7.4

Hello, I have the same problem, and how did you solve it?

**Comment by ZwwWayne** [comment]
This issue is closed because there is no valid information to debug the issue. Please raise a new issue using the `error template`  if you meet similar problem and cannot solve it.

**Comment by momo666666** [comment]
> > Compiled successfully。
> > Error when running training and testing：
> > RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/cuda/Loops.cuh:103)
> > ubuntu16.04 cuda10.0.130 pytorch1.4.0 python3.7.4
> 
> Hello, I have the same problem, and how did you solve it?

I have the problem too, have you solved that?
