### ISSUE TITLE
During the test, the count got confused

### ISSUE THREAD

**Issue by jiafengshen** [open-mmlab/mmdetection#3156]
{"annotations": [{"image_id": 1, "bbox": [762.374267578125, 695.5563354492188, 59.5633544921875, 89.50347900390625], "score": 0.08252769708633423, "category_id": 6, "segmentation": {"size": [1200, 1200], "counts": "jfmk0`0[S1LilN\\1SS1cNPmN\\1PS1cNRmN]1lR1dNnlNb1QS1_NnlNb1QS1_NPmNa1oR1_NQmNa1nR1aNPmN`1PS1a0N1001nMQmNa1oR1^NRmNb1oR1]NQmNc1oR1^NPmNb1QS1>001O0000O100OoMRmNb1nR1]NYmN]1fR1cN\\mN\\1cR1dN_mN[1_R1gNamNY1^R1hNcmNW1\\R1jNdmNV1\\R1iNemNW1ZR1jNgmNU1YR1kNgmNU1YR1kNhmNT1XR1lNhmNT1YR1jNimNU1WR1kNimNU1WR1kNimNU1WR1jNjmNV1VR1jNkmNU1UR1kNkmNU1UR1kNlmNS1UR1mNlmNR1TR1nNnmNo0SR1QOWnNd0jQ1[OanN;_Q1EjnN0XQ10T20000000000O2O1N101N2Nb^k="}}, {"image_id": 1, "bbox": [760.2423706054688, 694.6834716796875, 62.4852294921875, 90.29620361328125], "score": 0.9504950046539307, "category_id": 7, "segmentation": {"size": [1200, 1200], "counts": "k[kk0>_S1JflN_1VS1?N1N2O2O0OQNSmN^1lR1bNolNc1PS1?O101O000000000001O1O0000000000O1OnMZmN\\1fR1cN]mN[1aR1fN`mNZ1^R1hNbmNX1]R1iNdmNV1[R1jNgmNU1YR1kNgmNU1YR1kNgmNU1YR1kNhmNT1XR1lNhmNT1XR1lNhmNT1XR1lNimNS1WR1lNjmNT1VR1lNjmNT1VR1lNjmNT1VR1lNjmNT1VR1lNkmNS1UR1lNmmNR1TR1nNmmNQ1SR1oNnmNo0SR1POXnNe0iQ1[OanN;_Q1EinN1YQ1OT200000001O0O2O1O0O1O104JQYj="}}, {"image_id": 1, "bbox": [832.6072998046875, 642.3690185546875, 273.5950927734375, 243.00152587890625], "score": 0.07028164714574814, "category_id": 20, "segmentation": {"size": [1200, 1200], "counts": "[m`n0R2[S15L3N2O0O2O001O2M2O1O1O001O000O10000000000000001N101N101N2N2N2O1N2O0O10000000001O0O1000001O001O001O1O1O1O001O0000001O0000000000001O00000000000000001O1O1N2O1O1O1O1O0O10000O2N100O1O100O2O001N2O0O2O1O1N101N100N2M3F:YOg0O1O2N1O1O1O1O2L3A?G:N1O2N1O2N2O0N3M2L5K4O1O2O0O100000O10000O100O010O1O1O100O100O10000O10001O0O10000O100O1O1O100O100O10001O0O10001O001O1O001O001O00001O0000000000001N100O100O1O1O1O1O100O1000000000000000000O10000000000000000000000000000000000O10000O100O100O1O1O100O1000000000001O0O1000001O001O1O1O1O001O0O2O0O1O1VOk0QOn0K5L5M2N3M2M5K8QMXnNe1bg_3"}}, {"image_id": 1, "bbox": [356.2389221191406, 651.9069213867188, 404.5733337402344, 148.678466796875], "score": 0.9934169054031372, "category_id": 27, "segmentation": {"size": [1200, 1200], "counts": "SkQ=\\1RT18G5N1N2O001N101O0O2O0O2O1N2N2O1N2O1O001N10001O0O2O1O1O2M6K4K2O1O1N2O001O001O1O1O2N5QnNhL\\Q1m3I1O1O001N101O0000000000000000000000000000000000000000000000000000000000O1000000000000000000000000000000000000000000000000000001O0000000000000000000000000000000000000000000000000000000000000000000O100000O100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000O1000000000000000000000000001O000000000000000000000000dNinN_NWQ1_1lnN`NTQ1^1onNaNQQ1]1RoNbNnP1]1ToNbNlP1@inNU1<[OkP1_OlnNS1;]OiP1_OnnNR1:_OhP1^OPoNQ19AgP1]OQoNR18AgP1\\OToNP16DfP1\

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.

**Comment by Fengweinlpr** [comment]
Have you solved it?
