### ISSUE TITLE
Would you mind sharing se_resnext101 model weights on BaiduDisk 

### ISSUE THREAD

**Issue by tricoffee** [open-mmlab/mmdetection#3157]
It took me half a day to download _se_resnext101_32x4d-3b2fe3d8.pth_
from http://data.lip6.fr/cadene/pretrainedmodels/se_resnext101_32x4d-3b2fe3d8.pth  , but it failed in the end. I didn't get anything. I hope you can share this file on Baidu disk. Thank you.

**Comment by hellock** [comment]
This model is not maintained by us. Please contact the maintainer.
