### ISSUE TITLE
method _resize_masks() cause mask size large than image size 

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#3165]
**Describe the bug**
When train HTC model with myself dataset, there have assert error in mmcv function impad() assert shape[i] >= img.shape[i]. In my dataset, each image has different width and height.  This assert error occured easily.
Assume one image shape is (800, 1333), scale is (1333, 800). one mask of this image has shape(133, 80).
After resize the mask, the mask shape will be (1330, 800), then 800 < 1330 which cause the assert error.

I checked code, I think there is a issue in the mmdet function _resize_masks() in the class Resize in the datasets\pipelines\transforms.py.
In the def _resize_masks(self, results)
if self.keep_ratio:
      results[key] = results[key].rescale(**_results['scale'])_**

I think here should call the rescale() like:  rescale(results['scale_factor']). Because when you resize masks in one image, masks should keep same scale factor as resized image.

please check.
Thanks in advance!

**Comment by yhcao6** [comment]
https://github.com/open-mmlab/mmdetection/blob/38dfa875c048207fd46b8cd2b7ccafd5239b4a4e/mmdet/datasets/pipelines/loading.py#L275-L298

After loading mask annotation and before `rescale`,  the shape of the mask annotation and the image should be the same. So after rescale their shape should be still the same. I guess there is some other issues? Could you check it again
