### ISSUE TITLE
GN and BN's inference speed with the same backbone?

### ISSUE THREAD

**Issue by yongtaoge** [open-mmlab/mmdetection#317]
I found that Mask RCNN with R-50-FPN's(BN) inference time is 7.7 fps while Mask RCNN with R-50-FPN's(GN) is 5.4 fps. Does group normalization have a slower inference speed than batch normalization, and if so, what's the reason?

**Comment by hellock** [comment]
BN is faster than GN since cudnn has optimized implementation of BN.

**Comment by yongtaoge** [comment]
Thanks!
