### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ahchang2** [open-mmlab/mmdetection#3173]
I tried to install mmdet on colab notebook. I installed anaconda3 (and it showed that anaconda is successfully installed) first and then followed the commands provided on the installation instruction. However, I met the following errors.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/build.txt'
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /content
I got these two errors when I run the following commands(specifically the first and third lines).
pip install -r requirements/build.txt
pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
pip install -v -e .
And after that I tried to import the software and it failed as follow.
      2 import numpy as np
      3 
----> 4 from mmcv._ext import flow_warp_c
      5 from mmcv.arraymisc import dequantize, quantize
      6 from mmcv.image import imread, imwrite
 ModuleNotFoundError: No module named 'mmcv._ext' 
I was wondering whether it was because I installed anaconda3 in a wrong way or something else.
Could anyone help me with this issue?

**Comment by ZwwWayne** [comment]
From `No such file or directory: 'requirements/build.txt'`, it seems that you are in a wrong directory or did not clone mmdetection successfully.
