### ISSUE TITLE
Example transforms given in AutoAugment class do not exist

### ISSUE THREAD

**Issue by AlphonsGwatimba** [open-mmlab/mmdetection#3177]
https://github.com/open-mmlab/mmdetection/blob/8da42a21e79b7cda4b271bc0510cd53033e60efb/mmdet/datasets/pipelines/auto_augment.py#L25-L43

The example augmentation types ` type='Shear'`, `type='Sharpness'` and ` type='Rotate'` in line 27, line 29 and 37 respectively from the above code are not implemented anywhere in this repo as far as I can tell, potentially confusing users.

Also, the policies list given in the line of code highlighted does not follow the argument type 'list[list[dict]]' required by the function Args specification.

**Comment by hellock** [comment]
- The policies have not been implemented yet. You may either implement it by yourself or wait until it is finished.
- The policy list is `list[list[dict]]`, isn't it?

**Comment by AlphonsGwatimba** [comment]
> * The policies have not been implemented yet. You may either implement it by yourself or wait until it is finished.

Alright: #3194 

> * The policy list is `list[list[dict]]`, isn't it?

Yes you are right, my mistake

**Comment by rhythm-A** [comment]
Can you tell me how to use the auto_augment polices from google?Such as augmentation = AutoAugment(policies), policices=v1?

**Comment by AlphonsGwatimba** [comment]
@rhythm-A Hey bro, I'm not sure on that question, try creating a new issue.
