### ISSUE TITLE
Tried to train HTC model in 1 GPU, ERROR arise

### ISSUE THREAD

**Issue by Korolyow** [open-mmlab/mmdetection#3181]
Dear community I have tried train HTC model by 1 GPU 16 gb.

/mmdetection/mmdet/ops/roi_align/roi_align.py", line 30, in forward aligned)
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)

What is the changes in config file I should do for it work?

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
