### ISSUE TITLE
rpn head get 

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#3183]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/rpn_head.py#L125
```
           if self.use_sigmoid_cls:
                rpn_cls_score = rpn_cls_score.reshape(-1)
                scores = rpn_cls_score.sigmoid()
            else:
                rpn_cls_score = rpn_cls_score.reshape(-1, 2)
                # we set FG labels to [0, num_class-1] and BG label to
                # num_class in other heads since mmdet v2.0, However we
                # keep BG label as 0 and FG label as 1 in rpn head
                scores = rpn_cls_score.softmax(dim=1)[:, 1]
```

Whether use `scores = rpn_cls_score.softmax(dim=1)[:, 1]` not  `scores = rpn_cls_score.softmax(dim=1)[:, 0]`? I think rpn_cls_score.softmax(dim=1)[:, 0] mean the socre of foreground, rpn_cls_score.softmax(dim=1)[:, 1] mean the socre of background? or the code can not use in RPN head?

**Comment by thisisi3** [comment]
I am confused, the comment clearly says in RPN case FG label is 1 so the code should be alright.

**Comment by as754770178** [comment]
```
rpn_cls_score = rpn_cls_score.reshape(-1, 2)
scores = rpn_cls_score.softmax(dim=1)[:, 1]
```
I mean that this code use for ` FG label is 0`. 

我感觉这段代码取第一位作为FG label分数，也就是认为FG的label是0

**Comment by hellock** [comment]
The comment has stated that `However we keep BG label as 0 and FG label as 1 in rpn head`.
