### ISSUE TITLE
installation problem again

### ISSUE THREAD

**Issue by ahchang2** [open-mmlab/mmdetection#3193]
So here's the problem.
I'm trying to install the mmdetection on google colab and I followed the instructions on 'mmdet_inference_colab.ipynb'.
First I installed the latest mmdetection and the result is exactly the same as that of the instruction, and I thought I installed successfully. Then I restarted the runtime as said. After that, I started running the demo.
When I ran the code of 'from mmdet.apis import inference_detector, init_detector, show_result_pyplot', I received a statement saying that 'No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda''. Then when I tried to run the following codes about downloading the faster-rcnn model, I met a runtime error saying that 'RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47'. 
Does someone know how to solve this issue?

**Comment by ZwwWayne** [comment]
Hi @ahchang2 , this might be the incompatibility issue between the PyTorch you installed and the colab server. Colab uses CUDA 10.1, you can check whether the Pytorch you installed could use the GPU first.
