### ISSUE TITLE
VOC Style New DataSet Error

### ISSUE THREAD

**Issue by wangcn99** [open-mmlab/mmdetection#3202]
**Describe the bug**

when i use my own voc dataset i get an error

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/pascal_voc/retinanet_r50_fpn_1x_voc0712.py --work-dir RetinaNetVOC07-2020-7-5-0/

A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

i use offical voc.py to creat a voc dataset
here is the configuaretion
# dataset settings
dataset_type = 'VOCDataset'
data_root = 'data/BambooVOCdevkit/'
classes = ('维管束')
img_norm_cfg = dict(
    mean=[177.1758, 177.1758, 177.1758], std=[46.33112, 46.33112, 46.33112], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1000, 600), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1000, 600),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'BambooVOC2007/ImageSets/Main/trainval.txt',
        img_prefix=[data_root + 'BambooVOC2007/'],
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'BambooVOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'BambooVOC2007/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'BambooVOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'BambooVOC2007/',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='mAP')

3. What dataset did you use?
my own dataset using voc style

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0: Quadro RTX 5000
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0
OpenCV: 4.2.0
MMCV: 0.6.2
MMDetection: 2.2.0+588536d
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.2
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 128, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/zjj/mmdetection/mmdet/datasets/builder.py", line 65, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zjj/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.6.2-py3.7-linux-x86_64.egg/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/zjj/mmdetection/mmdet/datasets/voc.py", line 15, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/home/zjj/mmdetection/mmdet/datasets/xml_style.py", line 23, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/home/zjj/mmdetection/mmdet/datasets/custom.py", line 67, in __init__
    self.CLASSES = self.get_classes(classes)
  File "/home/zjj/mmdetection/mmdet/datasets/custom.py", line 248, in get_classes
    class_names = mmcv.list_from_file(classes)
  File "/home/zjj/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.6.2-py3.7-linux-x86_64.egg/mmcv/fileio/parse.py", line 17,in list_from_file
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '维管束'

A placeholder for trackback.
```

**Comment by ZwwWayne** [comment]
Hi @wangcn99 ,
This is because what you passed to the `classes` is actually a string rather than a tuple. `classes = ('维管束')` will be interpreted as `classes = '维管束'` by python, you need to use `classes = ('维管束', )` to avoid this problem.
