### ISSUE TITLE
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ZZH2950228** [open-mmlab/mmdetection#3209]

**Comment by LIUHUACHENG** [comment]
how to solve this problem? I meet the same problems

**Comment by auger1** [comment]
> how to solve this problem? I meet the same problems

Have you solved this problem ? Could you please tell your method? Looking forward your answer!

**Comment by jinzhiyang1** [comment]
Have you solved this problem ? Could you please tell your method? Looking forward your answer!!!

**Comment by auger1** [comment]
Sorry,I didn't solve it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月13日(星期五) 晚上7:34
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"胡杨"<2235733428@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory (#3209)





 
Have you solved this problem ? Could you please tell your method? Looking forward your answer!!!

**Comment by nemonameless** [comment]
@ZwwWayne How to solve this problem?

**Comment by lambdayin** [comment]
rebuild mmcv

**Comment by hjqiu** [comment]
I meet the same problems, my solution is to rebuild  “mmcv”，then try “python setup.py develop” and  "pip install -v -e ." again.

**Comment by danailliu** [comment]
Version mismatch

**Comment by danailliu** [comment]
The version of your torch is not right ,install right version can solve this problem
