### ISSUE TITLE
Why the det_bbox is fp when it correctly detects a gt_bbox covered by a higher det_bbox?

### ISSUE THREAD

**Issue by breAchyz** [open-mmlab/mmdetection#3211]
Hi, I am very thankful for this useful project!
My confused part of  `tpfp_default` code in 'mmdet/core/evaluation/mean_ap.py' is as follow:
 
                   `if not gt_covered[matched_gt]:`
                       `gt_covered[matched_gt] = True`
                        `tp[k, i] = 1`
                   `else:`
                       `fp[k, i] = 1`

I think it will cause a unreasonable decrease of precision.

**Comment by ZwwWayne** [comment]
The meanAP calculation follows the standard protocol of VOC dataset. You may refer to the [doc](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/htmldoc/devkit_doc.html) for details.
