### ISSUE TITLE
Custom Segmentation Map for HTC

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3214]
I was trying to use HTC with a custom dataset, creating my own segmentation map using pycocotools (https://github.com/nightrome/cocostuffapi/blob/master/PythonAPI/pycocotools/cocostuffhelper.py). However, when running the analysis, I get ```RuntimeError: 1only batches of spatial targets supported (3D tensors)``` because the segmentation map is being read as a 4D tensor (1, H, W, 3) rather than a 3D one (1, H, W). Would you know why this is the case, or alternatively, can you please let me know where in the code the seg map png is being converted to a tensor so that I can try do something about the last dimension. 

Many thanks!

**Comment by ZwwWayne** [comment]
You need to check whether your segmentation maps are consistent with those existing annotations of cocostuff.

**Comment by sehyungp92** [comment]
As I only have 1 class, I have assigned black (0,0,0) to it, and white (255,255,255) for the background / unlabelled. Are you suggesting that (0,0,0) is not used for any classes in the cocostuff dataset? Thanks

**Comment by xvjiarui** [comment]
Hi @sehyungp92 
You may try to use `pillow` backend at https://github.com/open-mmlab/mmdetection/blob/cdfc6a1e9a1414994bab78267ac10cd3aff38891/mmdet/datasets/pipelines/loading.py#L316. 
You may change it to 
```
results['gt_semantic_seg'] = mmcv.imfrombytes(img_bytes, flag='unchanged', backend='pillow').squeeze()

```
In this way, the segmentation maps should be 3D tensors.

**Comment by sehyungp92** [comment]
Many thanks!
