### ISSUE TITLE
Unusual memory used

### ISSUE THREAD

**Issue by GingerCohle** [open-mmlab/mmdetection#3216]
When I used nohup to train my model, and I need to kill the pids, but the memory didn't release.
![image](https://user-images.githubusercontent.com/37873318/86546883-6e3a3080-bf69-11ea-9e9b-fd9cfd8d2c62.png)
![image](https://user-images.githubusercontent.com/37873318/86546950-b8bbad00-bf69-11ea-9aa9-6560ce290f23.png)

.

**Comment by xvjiarui** [comment]
Hi @GingerCohle 
Sometimes, workers haven't exit properly. You may check it by `top` or `htop`.

**Comment by GingerCohle** [comment]
> Hi @GingerCohle
> Sometimes, workers haven't exit properly. You may check it by `top` or `htop`.

3Q, by the way. mmdetction is a great project. U guys dong excellent.
