### ISSUE TITLE
Can I keep the input image resulotion to detect? This mean not use Resize()

### ISSUE THREAD

**Issue by fengqian-wei** [open-mmlab/mmdetection#3218]
For example , now I have 400x500 image, I have trained a detector. I want to detector directly to dectect img, instead of first reSize to 1024*1024  and then detector.
I think this can change in dataconfig. How should I do ? img_scale or   dict(type='Resize', keep_ratio=True)?
I have tried delete this code  "dict(type='Resize', keep_ratio=True)", and the program doesn't work.

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2000, 2000),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

**Comment by hellock** [comment]
You can just remove the Resize transform.

**Comment by fengqian-wei** [comment]
When I remove the code dict(type='Resize', keep_ratio=True)  in test config. There are some errors and program doesn't work.
![image](https://user-images.githubusercontent.com/19569529/87007609-20395d00-c1f5-11ea-9414-d3c784d85637.png)

**Comment by fengqian-wei** [comment]
When I debug program,the  scale_factor is NULL, I think Maybe when user not set Resize atrribute，the scale_factor is 1. 
 so ,I change the code and it work 

    def __call__(self, results):
        data = {}
        img_meta = {}
        for key in self.meta_keys:
            #code add
            if key =='scale_factor':
                img_meta[key] =1
                continue

**Comment by fengqian-wei** [comment]
When I debug program,I found the  scale_factor is NULL, I think Maybe when user not set Resize atrribute，the scale_factor is 1. 
 so ,I change the code and it work 

    def __call__(self, results):
        data = {}
        img_meta = {}
        for key in self.meta_keys:
            #code add
            if key =='scale_factor':
                img_meta[key] =1
                continue
