### ISSUE TITLE
No module named 'mmcv.cnn.weight_init'

### ISSUE THREAD

**Issue by kalayan** [open-mmlab/mmdetection#3219]
branches : master
mmcv version : 0.6.2

when I follow the https://github.com/open-mmlab/mmdetection/blob/v2.2.0/docs/getting_started.md#high-level-apis-for-testing-images, error happend 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3de5e6a1b478> in <module>
----> 1 from mmdet.apis import init_detector, inference_detector
      2 import mmcv

/usr/local/lib/python3.6/dist-packages/mmdet/apis/__init__.py in <module>
----> 1 from .inference import (async_inference_detector, inference_detector,
      2                         init_detector, show_result, show_result_pyplot)
      3 from .train import get_root_logger, set_random_seed, train_detector
      4 
      5 __all__ = [

/usr/local/lib/python3.6/dist-packages/mmdet/apis/inference.py in <module>
     11 from mmdet.core import get_classes
     12 from mmdet.datasets.pipelines import Compose
---> 13 from mmdet.models import build_detector
     14 
     15 

/usr/local/lib/python3.6/dist-packages/mmdet/models/__init__.py in <module>
      1 from .anchor_heads import *  # noqa: F401,F403
      2 from .backbones import *  # noqa: F401,F403
----> 3 from .bbox_heads import *  # noqa: F401,F403
      4 from .builder import (build_backbone, build_detector, build_head, build_loss,
      5                       build_neck, build_roi_extractor, build_shared_head)

/usr/local/lib/python3.6/dist-packages/mmdet/models/bbox_heads/__init__.py in <module>
      1 from .bbox_head import BBoxHead
      2 from .convfc_bbox_head import ConvFCBBoxHead, SharedFCBBoxHead
----> 3 from .double_bbox_head import DoubleConvFCBBoxHead
      4 
      5 __all__ = [

/usr/local/lib/python3.6/dist-packages/mmdet/models/bbox_heads/double_bbox_head.py in <module>
      1 import torch.nn as nn
----> 2 from mmcv.cnn.weight_init import normal_init, xavier_init
      3 
      4 from ..backbones.resnet import Bottleneck
      5 from ..registry import HEADS

ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'

**Comment by rsrrohit** [comment]
You need to downgrade your version of mmcv as a work around for this problem:

pip uninstall mmcv
pip install mmcv==0.2.6

**Comment by hellock** [comment]
You need to upgrade mmdetection to the latest version, see https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/bbox_heads/double_bbox_head.py#L2

**Comment by kalayan** [comment]
> You need to upgrade mmdetection to the latest version, see https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/bbox_heads/double_bbox_head.py#L2

Thanks!
