### ISSUE TITLE
Add AMD ROCm support, I have successfully run on Radeon VII with ROCm ! 

### ISSUE THREAD

**Issue by acai66** [open-mmlab/mmdetection#3222]
**Describe the feature**
I have modified some .cu files, so AMD ROCm works fine, but i don't know that's correct or not.
I really hope this feature will become official support.

**Motivation**
I hope to get more extensive support and application through this feature .

**Related resources**
I have forked a copy  of mmdetection in my [repo](https://github.com/AHNU2019/mmdetection_ROCM), and i have successfully run some models on my AMD Radeon VII graphics card, this is a [demo](https://hyacm.com/acai/dl/247/rocm_mmdetection/).

**Additional context**
Here is my [commit](https://github.com/AHNU2019/mmdetection_ROCM/commit/f3a7ee1fcb2a435244d64594e6b478f16ab2a4ec), i know it's not perfect.

Installion:
![rocm_mmdetection_compile](https://user-images.githubusercontent.com/37766207/86571300-c68e2400-bfa3-11ea-81e3-0e120dd10174.png)

Training and testing:
![rocm_mmdetection_test](https://user-images.githubusercontent.com/37766207/86571323-ce4dc880-bfa3-11ea-8844-7e9256a97fa0.png)

Envs:
![rocm_env](https://user-images.githubusercontent.com/37766207/86572403-7912b680-bfa5-11ea-8e5d-8b58597defae.png)

**Comment by hellock** [comment]
Thanks for your efforts! We will migrate to `mmcv.ops` and you may create a PR in mmcv.

**Comment by acai66** [comment]
> Thanks for your efforts! We will migrate to `mmcv.ops` and you may create a PR in mmcv.

我已经尝试发起了PR, https://github.com/open-mmlab/mmdetection/pull/3235, 这个只在我的A卡机器上做了部分测试，由于没有Nvidia显卡，就没能测试CUDA，一般而言，我的提交是不会影响 nvcc 编译的。

**Comment by ZwwWayne** [comment]
Supported in https://github.com/open-mmlab/mmcv/pull/1022. You may have a try and feel free to create a new issue if you meet any unexpected results
