### ISSUE TITLE
fsaf_x101_64x4d_fpn_1x_coco.py: /coco.py", line 230, in _det2json  data['category_id'] = self.cat_ids[label]

### ISSUE THREAD

**Issue by QuantScientist** [open-mmlab/mmdetection#3223]
Hello, 
This only happens at the end of the training loop and stops training after the first epoch:
![image](https://user-images.githubusercontent.com/18743986/86577786-6edfc080-bf83-11ea-80a9-79058eefe661.png)

I tried both these solutions as suggested elsewhere:
```
pip install "git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI"
pip install -U "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"

```

Thanks ,

**Comment by QuantScientist** [comment]
This only happens if I try to validate while training (e.g. --validate)

**Comment by HXH-resonance** [comment]
> This only happens if I try to validate while training (e.g. --validate)

请问您方便留一个联系方式吗？有些问题想向您请教。我的邮箱是Houxiaohan_666@163.com

**Comment by ZwwWayne** [comment]
This means that your results predict more labels and it is out of the range of the dataset's number of classes. This usually happens when you set the `num_classes` in the head greater than the real number of classes in the dataset.
