### ISSUE TITLE
how to apply multi-scale test to inference

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection#3231]
**nice work firstly. I have used multi-scale testing to improve mAP, and I want to apply it to inference stage**
`from mmdet.apis import init_detector, inference_detector
import mmcv

config_file = 'configs/faster_rcnn_r50_fpn_1x_coco.py'
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'

#build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

#test a single image and show the results
img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_detector(model, img)`  
**how can I do this ? very appreciate for your reply!!**

**Comment by xvjiarui** [comment]
You need to modify config file. Please refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/test_time_aug.py) for TTA.
