### ISSUE TITLE
How to train SENet using basic FasterRCNN?

### ISSUE THREAD

**Issue by TWDH** [open-mmlab/mmdetection#3233]
Hello @hellock ,
I'd like to train (ResNet + SENet) as backbone and use FasterRCNN to do object detection task using the ImageNet pretrained model. However, when I simply add SENet in the ResNet residual block(after conv3) and train in Pascal VOC0712 dataset, the performance actually goes down a little bit which is weird. I heard someone said adding a SE-Layer will destroy the pretrain weights of ImageNet so results in a decrease of mAP. Is there any training skill or method I can use to improve the performance?  (besides, GCNet seems added at the same localtion as SENet, but mAP can boost up around 1%, but why SENet won't work?) Many Many Thanks! Hope you can comment on it :)

**Comment by ZwwWayne** [comment]
SENet requires pre-trained backbone. You need to implement SENet first by adding the module in `mmdet.models.backbones` like [resnet.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py). Then you need to prepare a pre-trained SENet. GCNet does not need to pertain GCBlock, it only requires pre-trained ResNet.

**Comment by TWDH** [comment]
Thanks very much!
