### ISSUE TITLE
----autoscale-lr was cancled???

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3240]
Remember args had the parameter autoscale-lr that automatically scale lr with the number of gpus ago.
Now it is cancled.
If I use two gpu or single gpu, "loss nan" or  "scores become infinite or NaN" will appear. Why do cancle autoscale-lr?
Have a more question: the specification of training configuration in config is carried out under several gpus? are all config files?
Thank you!

**Comment by ZwwWayne** [comment]
Hi @zhjw0927 ,
This is because `autoscale-lr` sometimes is easy to be miss-used and we have a similar convenient way to set the LR without modifying the config. For example, if the original LR is 0.02 for 8 GPU, for single-GPU training you only need to add additional arguments '--options optimizer.lr=0.0025'.

**Comment by zhjw0927** [comment]
Thank you! I know a lot.
About scaling lr according batchsize, I have a litte qusetion.
##  2imgs/gpu, 8gpus, batchsize=16, lr = 0.02
##  16imgs/gpu, 1gpu, batchsize=16,  whether the lr should also be 0.02?
Thank you!

**Comment by zhjw0927** [comment]
Thank you! I know a lot.
About scaling lr according batchsize, I have a litte qusetion.
1)  2imgs/gpu, 8gpus, batchsize=16, lr = 0.02
2)  16imgs/gpu, 1gpu, batchsize=16, whether the lr should also be 0.02?
Thank you!

**Comment by ZwwWayne** [comment]
> Thank you! I know a lot.
> About scaling lr according batchsize, I have a litte qusetion.
> 
> 1. 2imgs/gpu, 8gpus, batchsize=16, lr = 0.02
> 2. 16imgs/gpu, 1gpu, batchsize=16, whether the lr should also be 0.02?
>    Thank you!

Yes, it should be 0.02.
