### ISSUE TITLE
ssd voc dataset meet error

### ISSUE THREAD

**Issue by rrjia** [open-mmlab/mmdetection#3241]
python tools/train.py configs/pascal_voc/ssd300_voc0712.py

File /mmdetection-master/mmdet/models/dense_heads/anchor_head.py", line 331, in get_targets
labels_list = images_to_levels(all_labels, num_level_anchors)
File "/mmdetection-master/mmdet/core/anchor/utils.py", line 9, in images_to_levels
target = torch.stack(target, 0)
RuntimeError: stack expects each tensor to be equal size, but got [45690] at entry 0 and [51136] at entry 1

**Comment by deepakksingh** [comment]
@rrjia hey, did you find a fix for this issue?
I'm facing the same issue.

**Comment by BIGWangYuDong** [comment]
If you still meet the problem after you update the mmdet to the latest version, please feel free to let us know.
