### ISSUE TITLE
Why the number of bboxes is different in MaxIoUAssigner.assign() and forward_train()

### ISSUE THREAD

**Issue by wangg12** [open-mmlab/mmdetection#325]
I printed the number of bboxes in these two places:
[https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/two_stage.py#L113](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/two_stage.py#L113)
and 
[https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/assigners/max_iou_assigner.py#L75](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/assigners/max_iou_assigner.py#L75)

However the number is not consistent in these places. In `forward_train()`, it is always 2000, but in `MaxIoUAssigner.assign()` it is 2000 or 70420. 

I wonder why they are different and what does the difference come from?

**Comment by hellock** [comment]
For two-stage detectors, the assign process happens both in the RPN stage and RCNN stage, so it is 2000 (number of proposals) or 70420 (number of anchors).

**Comment by wangg12** [comment]
Thanks.
