### ISSUE TITLE
The old API of register_module(module, force=False) is deprecated

### ISSUE THREAD

**Issue by strongwolf** [open-mmlab/mmdetection#3250]
I think I have updated mmdetection and mmcv to the latest version but the warning bellow still occurs. I don't know which function has triggered this warning.

The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.

**Comment by hellock** [comment]
Old API:
```python
@xxx.register_module
class xxx:
    xxxx
```

New API:
```python
@xxx.register_module()
class xxx:
    xxxx
```

**Comment by hellock** [comment]
This warning will not affect the results.

**Comment by nidhi6553** [comment]
!python tools/train.py configs/cascade_rcnn_x101_32x4d_fpn_1x.py --resume-from work_dirs/cascade_rcnn_x101_32x4d_fpn_1x/epoch_12.pth


/usr/local/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
