### ISSUE TITLE
How to specify the GPU used for training when using dist_train.sh training?

### ISSUE THREAD

**Issue by gjxgjxgjxgjx** [open-mmlab/mmdetection#3253]
How to specify the GPU used for training when using dist_train.sh training? For example, four GPUs, how to use 2,3GPU. I tried to set gpu_ids to 2,3 but the training still uses 0,1 gpu.

**Comment by Soulempty** [comment]
CUDA_VISIBLE_DEVICES=2,3 ./tools/dist_train.sh configs/faster_rcnn/my_faster-rcnn-caffe.py 2

**Comment by SISTMrL** [comment]
CUDA_VISIBLE_DEVICES=4,5 ./tools/dist_train.sh ./configs/faster_rcnn/faster_rcnn_r50_fpn_soft_nms_1x_coco.py 2 

when I run the command above, i encounter this problem:
usage: launch.py [-h] [--nnodes NNODES] [--node_rank NODE_RANK]
                 [--nproc_per_node NPROC_PER_NODE] [--master_addr MASTER_ADDR]
                 [--master_port MASTER_PORT] [--use_env] [-m]
                 training_script ...
launch.py: error: argument --nproc_per_node: invalid int value: ''

How can I fix it ? thanks!

**Comment by Soulempty** [comment]
@SISTMrL you can do like below:
1、CUDA_VISIBLE_DEVICES=4,5 ./tools/dist_train.sh configs/faster_rcnn/faster_rcnn_r50_fpn_soft_nms_1x_coco.py 2
or
2、CUDA_VISIBLE_DEVICES=4,5  python -m torch.distributed.launch --nproc_per_node=2 --master_port=$PORT ./tools/train.py  configs/faster_rcnn/faster_rcnn_r50_fpn_soft_nms_1x_coco.py --launcher pytorch
