### ISSUE TITLE
TypeError: bad operand type for unary -: 'list' , after adding custom dataset

### ISSUE THREAD

**Issue by peeyushpashine** [open-mmlab/mmdetection#3261]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
I have checked the issues but could not find what i am looking for.
2. The bug has not been fixed in the latest version.

**Describe the bug**

after adding custom dataset, tablebank dataset. i changed the config files and i can see results on my test images as well. when i am trying to calculate mAP by

python tools/test.py /home/jovyan/cascadetabnet/CascadeTabNet/Config/cascade_mask_rcnn_hrnetv2p_w32_20e.py /data/epoch_24_GeneralModel.pth  --eval mAP

The output is

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100/100, 8.7 task/s, elapsed: 11s, ETA:     0s

Traceback (most recent call last):
  File "tools/test.py", line 170, in <module>
    main()
  File "tools/test.py", line 166, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/home/jovyan/cascadetabnet/mmdetection/mmdet/datasets/custom.py", line 289, in evaluate
    logger=logger)
  File "/home/jovyan/cascadetabnet/mmdetection/mmdet/core/evaluation/mean_ap.py", line 344, in eval_map
    sort_inds = np.argsort(-cls_dets[:, -1])
TypeError: bad operand type for unary -: 'list'

**Reproduction**
1. What command or script did you run?
```
python tools/test.py /home/jovyan/cascadetabnet/CascadeTabNet/Config/cascade_mask_rcnn_hrnetv2p_w32_20e.py /data/epoch_24_GeneralModel.pth  --eval mAP

A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

Yes changed the dataroot and test file paths for annotations and image_prefix
3. What dataset did you use?

tableebank

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1: Tesla V100-PCIE-16GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0+cu100
OpenCV: 4.3.0
MMCV: 0.6.2
MMDetection: 1.2.0+0f33c08
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.0

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]

through pip

    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "tools/test.py", line 170, in <module>
    main()
  File "tools/test.py", line 166, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/home/jovyan/cascadetabnet/mmdetection/mmdet/datasets/custom.py", line 289, in evaluate
    logger=logger)
  File "/home/jovyan/cascadetabnet/mmdetection/mmdet/core/evaluation/mean_ap.py", line 344, in eval_map
    sort_inds = np.argsort(-cls_dets[:, -1])
TypeError: bad operand type for unary -: 'list'


```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
From the bug trace, it seems that your prediction `cls_dets[:, -1]` is a list rather than np.ndarray. You might need to check your implementation when formating your results.

**Comment by peeyushpashine** [comment]
At present not looking into this so I am closing my issue.

**Comment by peeyushpashine** [comment]
closing
