### ISSUE TITLE
About groupsampler

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3263]
![image](https://user-images.githubusercontent.com/42128459/87035716-4f16f980-c21c-11ea-8106-87ef633ef7de.png)

My question is about this picture, main is num extra samples.
I think above figure is only for single gpu, not consider gpus.

i.e. having 6 imgs, 2 gpus, samplers per gpu is 2.
As shown in the figure above, do not need extra sample.
But actually, batchsize=2*2, take four images at a time, there are two left, but it's not batch enough.
Did I think wrong?
Thank you!

**Comment by xvjiarui** [comment]
Hi @zhjw0927 
Are you using distributed training or non-distributed training?

**Comment by zhjw0927** [comment]
under non-distributed training.
