### ISSUE TITLE
No module named "tools"

### ISSUE THREAD

**Issue by Atul997** [open-mmlab/mmdetection#3264]
I am using mmdetection version 1.2.0 for training cascade maskrcnn model using Google Colab. When I am running the command 
`!python tools/test.py --out /content/drive/My Drive/tabnet/result.pkl configs/hrnet/cascade_mask_rcnn_hrnetv2p_w32_20e.py /content/mmdetection/work_dirs/cascade_mask_rcnn_hrnetv2p_w32_20e/epoch_20.pth --eval bbox --show-dir /content/drive/My Drive/result/`

I am getting error of- 
`Traceback (most recent call last):
  File "tools/test.py", line 8, in <module>
    from tools.fuse_conv_bn import fuse_module
ModuleNotFoundError: No module named 'tools'`

How can I overcome this?

**Comment by starkgate** [comment]
#2667

**Comment by Atul997** [comment]
> #2667

how to do this in google colab?

**Comment by xvjiarui** [comment]
@Atul997 
You may try:
```
!PYTHONPATH=${PWD}:$PYTHONPATH python tools/test.py 
```
