### ISSUE TITLE
Add Transformers  as detailed in DETR

### ISSUE THREAD

**Issue by roya0045** [open-mmlab/mmdetection#3267]
**Describe the feature**

A recent paper by facebook propose the use of transformers as a predictor. They used resnet as the backbone to extract the feature maps and obtained decent results on COCO.

**Motivation**
This approach is quite novel and the new component could be useful for rresearch/experimenting.
The approach may also be lighter as stated in the readme.

**Related resources**
Official repo: https://github.com/facebookresearch/detr
They also propose a simplement implementation as a demo.

**Comment by ZwwWayne** [comment]
Hi @roya0045 ,
Thanks for your suggestion. We do have plans to support DETR but the progress will be slow, e.g., in the following several months. PRs are welcomed.

**Comment by dream-in-night** [comment]
> Hi @roya0045 ,
> Thanks for your suggestion. We do have plans to support DETR but the progress will be slow, e.g., in the following several months. PRs are welcomed.

快一年啦，出来没
