### ISSUE TITLE
Add recent backbones [Xception/AOGNet?]

### ISSUE THREAD

**Issue by roya0045** [open-mmlab/mmdetection#3268]
**Describe the feature**
Some new recent backbones seem to provide good performance but are not as widely used as the implemented ones.

It would be nice to have also some other backbones such as Xception and possibly AOGNet (not sure about the later with the licence)

I wasn't sure if it was worth splitting and making more ticket or keeping them together as AOGNet might be a far shoot due to the current licencing.

**Motivation**
These newer backbones are quite recent and adoption in open modular toolbox would encourage experimentation.

**Related resources**
[Xception]
[Unofficial simple implementation]: https://github.com/hoya012/pytorch-Xception
[Unofficial implementation]: https://github.com/jfzhang95/pytorch-deeplab-xception/blob/master/modeling/backbone/xception.py

[Official AOGNet]: https://github.com/iVMCL/AOGNet-v2

**Comment by ZwwWayne** [comment]
Hi @roya0045 ，
Thanks for your kind suggestion. Due to limited resources, our recent plan does not includes these features. We may consider adding them in the future. PRs are also welcomed.

**Comment by roya0045** [comment]
@ZwwWayne I may be able to help and make some draft PRs for those two requests if someone can provide guidance in some aspect as I'm not too familiar with the internals of mmdetection at the moment. XCeption seems relatively simple to code based on the two examples provided. Though I am unable to provided trained models if those are needed due to hardware restrictions at the moment.

**Comment by ZwwWayne** [comment]
> @ZwwWayne I may be able to help and make some draft PRs for those two requests if someone can provide guidance in some aspect as I'm not too familiar with the internals of mmdetection at the moment. XCeption seems relatively simple to code based on the two examples provided. Though I am unable to provided trained models if those are needed due to hardware restrictions at the moment.

If you want to implement Xception, you need to implement a exception backbone like the [resnet.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py). One concern is that Xception is not commonly used in detection but more used in semantic segmentation tasks. So you might be interested in [MMSegementation](https://github.com/open-mmlab/mmsegmentation).

**Comment by roya0045** [comment]
@ZwwWayne I started something, I'm not sure if I should make it more modular but [here is my current version](https://github.com/roya0045/mmdetection/blob/xception/mmdet/models/backbones/xception.py). Let me know if this is adequate or if you have any suggestions before I make a PR. Thanks!

**Comment by ZwwWayne** [comment]
Hi @roya0045 ,
Sorry, I missed this message before and thanks for your kind contribution. Since Xception backbone is not used in the current detectors and we do not have a very clear performance reference, it is a little bit hard to evaluate the correctness of the implementation. So there are several suggestions that may help:
1. Since Xception has been used in segmentation models, e.g., used by DeepLab, you may be interested to support it in [MMSegmentation](https://github.com/open-mmlab/mmsegmentation/), which is exactly for semantic segmentation and already supports deeplab models.
2. Use registry for separable conv and implement the basic block follows the design styles in mmdet & mmseg, and try to reuse the existing codes in the codebase to reduce the complexity.

**Comment by roya0045** [comment]
@ZwwWayne https://github.com/open-mmlab/mmdetection/pull/3383

**Comment by ZwwWayne** [comment]
> @ZwwWayne #3383

The suggestion is also applicable for #3383

**Comment by roya0045** [comment]
@ZwwWayne My intent was to show that a proposal exist and that if you have any concrete feedback regarding where I can improve things it would be more appreiated and fruitful than a generic suggestion. I beileived I have followed this suggestion but if I am wrong I would be happy to be corrected.
