### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by yangtianyu92** [open-mmlab/mmdetection#3270]
>>> from torchvision import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit__C)

docker image wrong

镜像都打不通。。。头疼，你们那有打好的直接下的嘛？不是dockerfile，我估计都复不出来错误，感觉贼不靠谱。

**Comment by xvjiarui** [comment]
Hi @yangtianyu92 
You may try to follow the latest [install guide](https://mmcv.readthedocs.io/en/latest/#installation) of mmcv.

**Comment by Au3C2** [comment]
头疼，俺也是这个错误

**Comment by yangtianyu92** [comment]
没事，你退镜像然后重新进，一切都好。我也就周末玩玩。




On 07/15/2020 15:52, JoeyLin wrote:

头疼，俺也是这个错误
