### ISSUE TITLE
No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by finnickniu** [open-mmlab/mmdetection#3272]
same as previous two

**Comment by Hwan6316** [comment]
I solved with this command

>pip install mmcv-full

**Comment by finnickniu** [comment]
fixed,thanks

**Comment by KDcx35** [comment]
> I solved with this command
> 
> > pip install mmcv-full

thank you

**Comment by xvjiarui** [comment]
Btw, you may install pre-build mmcv-full as stated [here](https://mmcv.readthedocs.io/en/latest/#install-with-pip).

**Comment by Liu199604** [comment]
> Btw, you may install pre-build mmcv-full as stated [here](https://mmcv.readthedocs.io/en/latest/#install-with-pip).

Hello, I have this problem too, I use cuda 10.2 and torch 1.3, but the mmcv doesn't have the matched version, so what should I do?

**Comment by ZwwWayne** [comment]
> > Btw, you may install pre-build mmcv-full as stated [here](https://mmcv.readthedocs.io/en/latest/#install-with-pip).
> 
> Hello, I have this problem too, I use cuda 10.2 and torch 1.3, but the mmcv doesn't have the matched version, so what should I do?

You need to either `pip install mmcv-full` or build from source manually following the doc [here](https://mmcv.readthedocs.io/en/latest/#install-from-source).
