### ISSUE TITLE
AttributeError: COCO object has no attribute get_cat_ids

### ISSUE THREAD

**Issue by wuhaonanBOB** [open-mmlab/mmdetection#3274]
please help me solve this question,many thanks!

**Comment by xvjiarui** [comment]
Please run `pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"` to install coco tools.

**Comment by Liu199604** [comment]
> please help me solve this question,many thanks!

You could reinstall pycocotools using :
pip install "git+https://github.com/openmmlab/cocoapi.git#subdirectory=pycocotools"

**Comment by wuhaonanBOB** [comment]
> > please help me solve this question,many thanks!
> 
> You could reinstall pycocotools using :
> pip install "git+https://github.com/openmmlab/cocoapi.git#subdirectory=pycocotools"

yes,I do it like you said ;but it occurs:

> > please help me solve this question,many thanks!
> 
> You could reinstall pycocotools using :
> pip install "git+https://github.com/openmmlab/cocoapi.git#subdirectory=pycocotools"

yes, I do ,but it occurs follow question:
![image](https://user-images.githubusercontent.com/57397434/87121975-8934d980-c2b6-11ea-94e6-01dc19ea633b.png)
and i also  follow this step to solve ,but cannot solve :
![image](https://user-images.githubusercontent.com/57397434/87122163-ecbf0700-c2b6-11ea-98e1-64873b69629c.png)

**Comment by wuhaonanBOB** [comment]
I still cannot pip install it,so i was upset

**Comment by xvjiarui** [comment]
@wuhaonanBOB You may try the following
```
git clone https://github.com/open-mmlab/cocoapi.git
cd cocoapi
pip install .
```

**Comment by wuhaonanBOB** [comment]
> pip install .
thank you very much ,follow your step ,I have soved it 谢谢你们三人的帮助！！

**Comment by baibaidedongdong** [comment]
＠wuhaonanBOB 　　When I run "pip install .", it gets such problem like below:  
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

how should I do ?

**Comment by baibaidedongdong** [comment]
@wuhaonanBOB @xvjiarui
When I run "pip install .", it gets such problem like below:
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

how should I do ?

**Comment by baibaidedongdong** [comment]
![image](https://user-images.githubusercontent.com/54987492/87847177-7cdcfc00-c908-11ea-8006-ce90734923e7.png)
just like this

**Comment by yxwhn** [comment]
> ![image](https://user-images.githubusercontent.com/54987492/87847177-7cdcfc00-c908-11ea-8006-ce90734923e7.png)
> just like this

yes,you can  " cd pycocotools" in cocoapi. and then run "pip install ."

**Comment by ZwwWayne** [comment]
`pip uninstall pycocotools` and then `pip install mmpycocotools` should work.
