### ISSUE TITLE
KeyError: 'ConvWS is already registered in conv layer'

### ISSUE THREAD

**Issue by YANG-25** [open-mmlab/mmdetection#3275]
when I train the model mask_rcnn_r50_fpn_2x_coco.py on my own custom dataset, I have some problem: 

File "/.../anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 58, in _register_module
raise KeyError(f'{module_name} is already registered 
KeyError: 'ConvWS is already registered in conv layer'

Has somebody knew about it? :(

**Comment by rozendetr** [comment]
Same issue here (#3249)

**Comment by YANG-25** [comment]
> Same issue here (#3249)

Thanks !!

**Comment by xvjiarui** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/issues/3249#issuecomment-656505982 .

**Comment by YANG-25** [comment]
> Please refer to #3249 (comment) .

Ok, it has been resolved, thanks!
