### ISSUE TITLE
Why does LVIS require more training GPU memory than COCO using the same model?

### ISSUE THREAD

**Issue by sunpeng1996** [open-mmlab/mmdetection#3277]
I think it's because there are more boxes, right? Ask for an answer.

**Comment by sunpeng1996** [comment]
I think it's because there are more boxes, right? Ask for an answer.

**Comment by xvjiarui** [comment]
On the other hand, the classification head is 1203 channels on LVIS. compared with 80 channels on COCO,

**Comment by xvjiarui** [comment]
On the other hand, the classification head is 1203 channels on LVIS. compared with 80 channels on COCO,

**Comment by sunpeng1996** [comment]
Thank you for your reply. Your idea is right. 
I looked at the log in MMdetection, the same model (e.g. ResNet101-FPN-maskrcnn) requires 7G for coco and 10G for LVIS.  That's a big difference for GPU memory.
But I found that training the GA (Guided-Anchor) model alone was much larger than the original. What do you think is the reason, bboxes?
