### ISSUE TITLE
How can I test the AP of each class in the coco dataset? 

### ISSUE THREAD

**Issue by gjxgjxgjxgjx** [open-mmlab/mmdetection#3278]
In addition, what is the difference between the proposal and bbox tested?  
Thanks！

**Comment by ZwwWayne** [comment]
Please refer to the 5th example in the [doc](https://mmdetection.readthedocs.io/en/latest/getting_started.html#test-a-dataset).

**Comment by rsj007** [comment]
> Please refer to the 5th example in the [doc](https://mmdetection.readthedocs.io/en/latest/getting_started.html#test-a-dataset).
What IoU threshold is this AP for each class based on?
