### ISSUE TITLE
only use human class to train detectoRS, but the result is not good 

### ISSUE THREAD

**Issue by wadesunyang** [open-mmlab/mmdetection#3279]
I trained the detectoRS with only use the human class,  and the config file is  detectors_htc_r50_1x_coco.py.

i only remove the model <semantic_roi_extractor> and <semantic_head> ,  because  the custom data don't have the mask.

i trained 20 epoch,  and finally the result is not good.  the score is always low.

so any one can give me some advise?

Should  i need change number of RandomSampler to 256 or 128,  because one human class, the positive anchor don't have so much.

**Comment by ZwwWayne** [comment]
Hi @wadesunyang ,
Please use and follow the issue template of `Reimplementation Questions`.
You can first train a vanilla Faster RCNN or Mask RCNN to obtain a reasonable baseline, and then compare it with DetectoRS and see where the bug lies.

**Comment by wadesunyang** [comment]
ok, thank you.  
And anyone who use the mmdetection to train one class can give me some advice.

**Comment by zachbellay** [comment]
Hey @wadesunyang, I have been able to successfully use DetectoRS with only a single class where my input data is a set of polygons in COCO format from the VGG Image Annotation tool. Here is a gist of the config file that I have used to get the result. I got this config by using the tools/print_config.py so it is probably more verbose than necessary.

https://gist.github.com/zachbellay/4146a9ee38a6d85bc39db23bf4c5b99a

**Comment by wadesunyang** [comment]
@zachbellay Thank you for your replay.  My config is the same as yours except no mask roi head, because my data don't have the mask region.

**Comment by zachbellay** [comment]
Hi @wadesunyang, I have about ~100 instances of a single class in my images.

**Comment by zachbellay** [comment]
@wadesunyang would you mind posting the current configuration file you're using? My guess is that you are not using the load_from parameter to initialize the network with weights trained on COCO.

**Comment by vpeopleonatank** [comment]
> Hey @wadesunyang, I have been able to successfully use DetectoRS with only a single class where my input data is a set of polygons in COCO format from the VGG Image Annotation tool. Here is a gist of the config file that I have used to get the result. I got this config by using the tools/print_config.py so it is probably more verbose than necessary.
> 
> https://gist.github.com/zachbellay/4146a9ee38a6d85bc39db23bf4c5b99a

Hi @zachbellay , i used your config for training 1 class and only change training data path and classes name. But i received error, can you help me debug it
```
Traceback (most recent call last):
  File "tools/train.py", line 179, in <module>
    main()
  File "tools/train.py", line 155, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/content/drive/My Drive/DeepLearning/Code/mmdetection/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/content/drive/My Drive/DeepLearning/Code/mmdetection/mmdet/datasets/custom.py", line 85, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/content/drive/My Drive/DeepLearning/Code/mmdetection/mmdet/datasets/coco.py", line 56, in load_annotations
    self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 206, in get_cat_ids
    return self.getCatIds(cat_names, sup_names, cat_ids)
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 192, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'
```
here is my [https://gist.github.com/vpeopleonatank/381dea90ee29a1ce33258c846fd6d720](config)

**Comment by vpeopleonatank** [comment]
> > Hey @wadesunyang, I have been able to successfully use DetectoRS with only a single class where my input data is a set of polygons in COCO format from the VGG Image Annotation tool. Here is a gist of the config file that I have used to get the result. I got this config by using the tools/print_config.py so it is probably more verbose than necessary.
> > https://gist.github.com/zachbellay/4146a9ee38a6d85bc39db23bf4c5b99a
> 
> Hi @zachbellay , i used your config for training 1 class and only change training data path and classes name. But i received error, can you help me debug it
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 179, in <module>
>     main()
>   File "tools/train.py", line 155, in main
>     datasets = [build_dataset(cfg.data.train)]
>   File "/content/drive/My Drive/DeepLearning/Code/mmdetection/mmdet/datasets/builder.py", line 71, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
>     return obj_cls(**args)
>   File "/content/drive/My Drive/DeepLearning/Code/mmdetection/mmdet/datasets/custom.py", line 85, in __init__
>     self.data_infos = self.load_annotations(self.ann_file)
>   File "/content/drive/My Drive/DeepLearning/Code/mmdetection/mmdet/datasets/coco.py", line 56, in load_annotations
>     self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
>   File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 206, in get_cat_ids
>     return self.getCatIds(cat_names, sup_names, cat_ids)
>   File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 192, in getCatIds
>     cats = self.dataset['categories']
> KeyError: 'categories'
> ```
> 
> here is my [config](https://gist.github.com/vpeopleonatank/381dea90ee29a1ce33258c846fd6d720)

I found problem, because categories in my json annotation file is empty.
