### ISSUE TITLE
How to obtain the number of detected object per image for MAE&RMSE

### ISSUE THREAD

**Issue by xincyu** [open-mmlab/mmdetection#3282]
**Describe the feature**

**Motivation**
It is inconvenient when i try to compute Mean Absolute Error (MAE) and Root Mean Square Error(RMSE).

How to obtain the number of detected object and the  number of ground truth per image in order to compute the MAE & RMSE.

If you already have this function, please advise me, I will be very grateful.

**Comment by ZwwWayne** [comment]
Hi @xincyu ,
For now, we do not support this function. To obtain the number of objects and GTs per image, they are usually available in the head and you can obtain them from the head's loss function, e.g., [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/anchor_head.py#L470)

**Comment by xincyu** [comment]
> Hi @xincyu ,
> For now, we do not support this function. To obtain the number of objects and GTs per image, they are usually available in the head and you can obtain them from the head's loss function, e.g., [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/anchor_head.py#L470)

Thank you very much. I'll do a try
