### ISSUE TITLE
DetectRS loss is nan when use fp16

### ISSUE THREAD

**Issue by Pluto1314** [open-mmlab/mmdetection#3292]
When I use fp16 in detectors_cascade_rcnn_r50_1x_coco.py, loss is Nan。
![nan](https://user-images.githubusercontent.com/47765770/87239127-08a0e500-c43e-11ea-9602-7bc4ebf5f2e4.JPG)

**Comment by shanzg** [comment]
ConvWS op can not use in fp16 traing......

**Comment by ZwwWayne** [comment]
FP16 training with DetectoRS is not tested yet and it needs parameter tuning.

**Comment by Pluto1314** [comment]
@ZwwWayne @shanzg OK，thanks！
