### ISSUE TITLE
Names of the detected items on the image 

### ISSUE THREAD

**Issue by Adarsh1999** [open-mmlab/mmdetection#3294]
I have been folloeing this demo : [demo](https://colab.research.google.com/github/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb#scrollTo=oWyEcikND61n)

Here in the output where the result detection was plotted on the image but I need the  name of the entities which were detected on the image in form of string array or anything else. So by using which functions can I get  those?

**Comment by ZwwWayne** [comment]
You may check how [`mmcv.imshow_det_bboxes`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L79) plot the names of boxes. With `self.CLASSES` and `labels` you can get the list you want.

**Comment by Adarsh1999** [comment]
Hi, 
Thanks for your reply.
Please see the following code example I am following:
```python3
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv
config_file = '/content/mmdetection/configs/retinanet/retinanet_x101_64x4d_fpn_1x_coco.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = '/content/mmdetection/retinanet_x101_64x4d_fpn_1x_coco_20200130-366f5af1.pth'
# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')
# test a single image
img = '/content/image2.jpeg'
result = inference_detector(model, img)
# show the results
show_result_pyplot(model, img, result)

```
I am confused from your reply what function should I call in for this demo?

**Comment by jainal09** [comment]
Hi, @ZwwWayne please help getting the same issue!

**Comment by ZwwWayne** [comment]
After `result = inference_detector(model, img)`, you have obtained the result, which contains bounding box and labels. The mapping from label to the class name can be obtained from `model.CLASSES`. So you could obtain what you need through `result` and `morel.CLASSES`.  `show_result_pyplot` and [this function](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L79) shows you a way to do that.
