### ISSUE TITLE
about registering class of DCN or DCNv2

### ISSUE THREAD

**Issue by fornote** [open-mmlab/mmdetection#3298]
Hello, thanks for your so outstanding works.
I have a problem when I used DCN as a filter to extract feature from input tensor.
The problem is that there is **no DCN class** in register of CONV_LAYERS.
The following is my code in new_tmp.py :
`from mmcv.cnn.bricks.registry import CONV_LAYERS`
`CONV_LAYERS.register_module('DCN', force=True)      #CONV_LAYERS.register_module('DCN')`
Although I haven't registered Conv1d, Conv2d, Conv3d and Conv, there were still these four class in CONV_LAYERS. However, I registered the DCN class, there was no this class in CONV_LAYERS.

**Comment by ZwwWayne** [comment]
Please use the newest mmcv by **uninstalling the original mmcv and install mmcv-full** by the command `pip install mmcv-full`. DCN and DCNv2 has already been registered in CONV_LAYERS.
