### ISSUE TITLE
Training speed of mmdet2.2 is slower than mmdet1.0

### ISSUE THREAD

**Issue by JiHaoqina** [open-mmlab/mmdetection#3299]
Hi, I train & test RetinaNet_r50_fpn_1x.py on both mmdet1.0 and mmdet2.0,  my envs are:
mmdet1.0: python==3.7 | pytorch==1.1 | cuda==9.0   | cudnn==7.0.5 | mmcv==0.2.14
mmdet2.2: python==3.7 | pytorch==1.5 | cuda==10.2 | cudnn==7.6.5 | mmcv-full==1.0.0
 
i found that：

1. Testing speed (v100) and accuracy
    -- mmdet2.2 speed: 17.9 tasks/s  | AP@[0.5:0.95] = 36.3
    -- mmdet1.0 speed: 12.6 tasks/s  | AP@[0.5:0.95] = 35.5
    (both accuracy and efficiency are improved!)

2. training speed (single Tesla v100, 16 imgs/gpu, and use the default settings for the rest)
    -- mmdet2.2 iter_time: 1.779  | total time: 1day + 20h (actual time, not the original estimate)
    -- mmdet1.0 iter_time: 1.543  | total time: 1day + 13h

I don't know why the training speed of mmdet2.2 is slower, what could be the cause?

**Comment by yhcao6** [comment]
Do you compare them on the same machine or not? The speed may be affected by some other factors like IO.
If could, could you provide your training log?
