### ISSUE TITLE
how to set the configurations for 2x?

### ISSUE THREAD

**Issue by Hwang64** [open-mmlab/mmdetection#330]
Very nice job!!
From the Model Zoo, the lr_schd configuration for some results are 2x, the readme have said that:
"We adopt the same training schedules as Detectron. 1x indicates 12 epochs and 2x indicates 24 epochs,"
So the configurations for 1x for faster_rcnn_r101_fpn_1x are:
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=1)
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
    ])
total_epochs = 12

if i want to train 2x(faster_rcnn_r101_fpn_2x), what are configurations? I wonder whether the following configurations are correct (change the total epochs and the lr_steps)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[16, 22])
checkpoint_config = dict(interval=1)
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
    ])
total_epochs = 24

looking forward for your reply~~

**Comment by chenxu93** [comment]
yes, it is correct
