### ISSUE TITLE
Is there a Dockerfile for CPU installation only?

### ISSUE THREAD

**Issue by StanleyGan** [open-mmlab/mmdetection#3301]
I just need a Docker environment for inferencing on CPU. I've tried using the existing Dockerfile but gotten numerous errors which can be seen in multiple issues reported in this repository such as `No module found 'mmcv.ops'` etc.

**Comment by v-qjqs** [comment]
Hi, you might re-install mmcv if you have error message 'No module found 'mmcv.ops' '.
