### ISSUE TITLE
Got OS error for model saving during faster R-CNN training

### ISSUE THREAD

**Issue by anabiasohail** [open-mmlab/mmdetection#3302]
I followed "mmdetection_demo.ipynb" for the training of faster RCNN on colab and assigned my google drive path to  "cfg.work_dir" to save the models, but i got following error after saving of first checkpoint ("epoch_12.pth"). It gives error for "latest.pth" and further training does not proceeds.
---> 36     os.symlink(src, dst, **kwargs)
OSError: [Errno 95] Operation not supported: 'epoch_12.pth' -> '/content/drive/My Drive/mmdetection/latest.pth'

however when I change the path of "cfg.work_dir" to exiting current directory of colab ('./tutorial_exps'), i got no error.

How can I save the models in google drive?

**Comment by xvjiarui** [comment]
You may add following to the config file. 
```
checkpoint_config = dict(create_symlink=False)
```

**Comment by anabiasohail** [comment]
Thank you issue resolved.
