### ISSUE TITLE
How to use coco dataset?

### ISSUE THREAD

**Issue by blackCmd** [open-mmlab/mmdetection#3305]
I've read guide documentation 
> https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html#customize-datasets-by-reorganizing-data

very many times but i don't know how to make it. 
How can i configure?

Plz help me. Thank you.

**Comment by azibit** [comment]
In what format do you have your data? Is it in the coco format?

**Comment by blackCmd** [comment]
> In what format do you have your data? Is it in the coco format?

oh, yes i have own coco dataset already : )

**Comment by azibit** [comment]
Let us assume you are using the mask_rcnn_r50_fpn_2x_coco for Instance Segmentation, then you can edit the class mmdetection/mmdet/datasets/coco.py and change the CLASSES to the classes you have.

Then you also edit the class 'configs/_base_/models/mask_rcnn_r50_fpn.py', and replace the num_classes with the number of classes you have, then you should be fine.

This is basically what I do. Do let me know if that works for you.

**Comment by blackCmd** [comment]
> Let us assume you are using the mask_rcnn_r50_fpn_2x_coco for Instance Segmentation, then you can edit the class mmdetection/mmdet/datasets/coco.py and change the CLASSES to the classes you have.
> 
> Then you also edit the class 'configs/_base_/models/mask_rcnn_r50_fpn.py', and replace the num_classes with the number of classes you have, then you should be fine.
> 
> This is basically what I do. Do let me know if that works for you.

Oh! This is the long-awaited news for me !
OK i'm gonna try it now and i'll reply you if it works or not

**Comment by blackCmd** [comment]
> Let us assume you are using the mask_rcnn_r50_fpn_2x_coco for Instance Segmentation, then you can edit the class mmdetection/mmdet/datasets/coco.py and change the CLASSES to the classes you have.
> 
> Then you also edit the class 'configs/_base_/models/mask_rcnn_r50_fpn.py', and replace the num_classes with the number of classes you have, then you should be fine.
> 
> This is basically what I do. Do let me know if that works for you.

Oh! This is the long-awaited news for me!
OK I'm gonna try it now and I'll reply to you if it works or not

I've edited all that you said.

1. I changed `CLASSES = ('person', 'bycycle', 'car' ... etc)` to `CLASSES = ('person')` in `mmdetection/mmdet/datasets/coco.py`.
2. I changed `num_classes=80` to `num_classes=1' in `mmdetection/configs/_base_/models/mask_rcnn_r50_fpn.py`.

Then I tried `python mmdetection/tools/train.py mmdetection/configs/detectors/mask_rcnn_r50_fpn_2x_coco.py`

But I got an error like this.
![image](https://user-images.githubusercontent.com/13531174/87497159-fd44f800-c68f-11ea-99c7-afda45030147.png)

Are there any things that I edited?

**Comment by azibit** [comment]
For some weird python reasons which I am not sure of, you need to have CLASSES = ('person', ) with the comma at the end rather than just having CLASSES = ('person') without the comma. Try that and let me know how that goes

**Comment by blackCmd** [comment]
> For some weird python reasons which I am not sure of, you need to have CLASSES = ('person', ) with the comma at the end rather than just having CLASSES = ('person') without the comma. Try that and let me know how that goes

Oh, I mistake annotation file plz wait. Thanks @azibit u r angel.

**Comment by blackCmd** [comment]
> For some weird python reasons which I am not sure of, you need to have CLASSES = ('person', ) with the comma at the end rather than just having CLASSES = ('person') without the comma. Try that and let me know how that goes

Oh, I mistake annotation file plz wait. Thanks @azibit u r angel.

Oh, bro, Reason of the error is my mistake.
My annotation file has `"category_id" : "human"` but i edited `CLASSES = ('person')` in mmdetection/mmdet/datasets/coco.py. 
After i edit `CLASSES = ('person')` to `CLASSES = ('human')` training process works well!

Thank you @azibit.
I owe you big time. You're a lifesaver Thanks.

**Comment by azibit** [comment]
You are most welcome @blackCmd I wish you all the very best. Do let me know if you need anything else

**Comment by blackCmd** [comment]
> You are most welcome @blackCmd I wish you all the very best. Do let me know if you need anything else

@azibit I executed `image_demo.py in `mmdetection/demo/` and I get this result.
![image](https://user-images.githubusercontent.com/13531174/87632498-7cabf780-c774-11ea-8d0a-5b039c7cc170.png)

But this is so weird. What are those that I indicate red arrows?

**Comment by hellock** [comment]
https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html#modify-classes-of-existing-dataset

**Comment by echonax07** [comment]
> For some weird python reasons which I am not sure of, you need to have CLASSES = ('person', ) with the comma at the end rather than just having CLASSES = ('person') without the comma. Try that and let me know how that goes

I know right, it's so weird. I spent 2 hours just to fix the missing comma
