### ISSUE TITLE
ValueError: 'mmdet/ops/nms/src/soft_nms_cpu.pyx' doesn't match any files

### ISSUE THREAD

**Issue by Note-Liu** [open-mmlab/mmdetection#3307]
执行python setup.py develop,提示ValueError: 'mmdet/ops/nms/src/soft_nms_cpu.pyx' doesn't match any files

**Comment by kartikJ-9** [comment]
I am facing the same issue. Any workaround that helped?

**Comment by ZwwWayne** [comment]
The ops have been moved into MMCV, please update your MMDetection and use the newest one.

**Comment by lh0515** [comment]
> The ops have been moved into MMCV, please update your MMDetection and install `mmcv-full` following the [doc](https://mmdetection.readthedocs.io/en/latest/install.html#install-mmdetection).

Because ops is already in mmcv, if I want to modify the soft_nms in ops, what should I do？
