### ISSUE TITLE
Distributed training on single machine stuck at the end of training.

### ISSUE THREAD

**Issue by wangg12** [open-mmlab/mmdetection#331]
The training process hangs at the end of training. The last checkpoint has been saved. 

It seems `.lock_map_hook` should be removed after training. However when I look into the work dir, `.lock_map_hook` still exists. What is going wrong?

**Comment by wangg12** [comment]
It seems this is a reproducible bug.

**Comment by hellock** [comment]
I agree that it may be an upstream issue, though we hardly encounter that.
