### ISSUE TITLE
Solution to: mmcv.ops not found

### ISSUE THREAD

**Issue by paklau99988** [open-mmlab/mmdetection#3321]
Super strange error that took me a while to resolve. 

This works 100%.

```
export TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
export  TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
export  CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"


pip uninstall -y mmdet mmcv
conda install -y cython==0.28.5
#pip install mmcv==0.2.15
pip install mmcv==0.6.2 terminaltables Pillow==6.2.2

export FORCE_CUDA="1"

pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
pip install "git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI"
#git clone https://github.com/open-mmlab/mmdetection.git mmdetection
#cd mmdetection
rm -rf build
pip install -r requirements/build.txt
python setup.py develop
pip install --no-cache-dir -e .
pip install mmcv==0.6.2 mmcv-full

```

**Comment by xvjiarui** [comment]
Hi @paklau99988 
mmcv and mmcv-full should not be installed at the same time. 
Please refer to [install guide](https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md).

**Comment by paklau99988** [comment]
> Hi @paklau99988
> mmcv and mmcv-full should not be installed at the same time.
> Please refer to [install guide](https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md).

Nothing else works. Try it yourself.

**Comment by xvjiarui** [comment]
Hi @paklau99988 
I just tried with the latest MMDetection. 
The setup in the [install guide](https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md) is just fine.
```shell
conda create -n open-mmlab python=3.7 -y
conda activate open-mmlab

# install latest pytorch prebuilt with the default prebuilt CUDA version (usually the latest)
conda install -c pytorch pytorch torchvision -y

# install the latest mmcv
pip install mmcv-full

# install mmdetection
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
pip install -v -e .
```

**Comment by paklau99988** [comment]
Did you train anything using this?
I get zero loss on the first epoch on COCO style DB.

**Comment by ZwwWayne** [comment]
> Did you train anything using this?
> I get zero loss on the first epoch on COCO style DB.

This issue will be closed since the installation problem is solved. Please post a new issue if you still meet the training problem and cannot solve it by yourself using the `Reimplementation Questions`.

**Comment by captaindavepdx** [comment]
This doesn't work on Windows - it's in the [installation](https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md) instructions.
```
• Linux or macOS (Windows is not currently officially supported)
```
I tried it on MacOS and it worked.
