### ISSUE TITLE
How to use Albu augmentation in HTC with 'gt_semantic_seg'?

### ISSUE THREAD

**Issue by kunc01** [open-mmlab/mmdetection#3323]
Thanks for your great work!
I'm now trying to train HTC with `gt_semantic_seg` on my own dataset, and I'm wondering how to use Albu aug in HTC with `gt_semantic_seg`.  Someone in [#1726](https://github.com/open-mmlab/mmdetection/issues/1726) also mentioned that. Could you give me some idea? Thanks!

**Comment by vpeopleonatank** [comment]
I have found an example config using Albu in {MMDETECTION}/configs/albu_example
