### ISSUE TITLE
Transforming instance segmentation results into COCO format

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3324]
I was just wondering if mmdetection offered a way of transforming the results of an instance segmentation model back into the COCO annotation format. Alternatively, if anyone knows any other way of doing so, please do let me know.

Thanks!

**Comment by ZwwWayne** [comment]
The [pycocotools](https://github.com/open-mmlab/cocoapi) supports to encode the instance mask into the COCO annotation format. Basically you need to crop that instance mask according to the box and encode it.
