### ISSUE TITLE
When I tried Asynchronous interface, AttributeError: 'RPNHead' object has no attribute 'rpn_head'

### ISSUE THREAD

**Issue by blackCmd** [open-mmlab/mmdetection#3326]
When I tried `Asynchronous interface` in documentation I got an error like this.
> **AttributeError: 'RPNHead' object has no attribute 'rpn_head'**
>
> ![image](https://user-images.githubusercontent.com/13531174/87625336-dc9aa200-c764-11ea-91c9-864f14d0a7a4.png)

And this is the documentation link.
> _https://mmdetection.readthedocs.io/en/latest/getting_started.html#asynchronous-interface-supported-for-python-3-7_

My python version is `3.7.5`. 
How can I use `Asynchronous interface`?
Plz help for solving the error.

**Comment by tjsongzw** [comment]
`RPNHead` shouldn't have `rpn_head` I guess, it points `self`

`sleep_interval = self.rpn_head.test_cfg.pop('async_sleep_interval', 0.025)`
-> 
`sleep_interval = self.test_cfg.pop('async_sleep_interval', 0.025)`
does it work?

**Comment by blackCmd** [comment]
> `RPNHead` shouldn't have `rpn_head` I guess, it points `self`
> 
> `sleep_interval = self.rpn_head.test_cfg.pop('async_sleep_interval', 0.025)`
> ->
> `sleep_interval = self.test_cfg.pop('async_sleep_interval', 0.025)`
> does it work?

Oh plz wait. I'm gonna try that now!

**Comment by blackCmd** [comment]
> `RPNHead` shouldn't have `rpn_head` I guess, it points `self`
> 
> `sleep_interval = self.rpn_head.test_cfg.pop('async_sleep_interval', 0.025)`
> ->
> `sleep_interval = self.test_cfg.pop('async_sleep_interval', 0.025)`
> does it work?

> `RPNHead` shouldn't have `rpn_head` I guess, it points `self`
> 
> `sleep_interval = self.rpn_head.test_cfg.pop('async_sleep_interval', 0.025)`
> ->
> `sleep_interval = self.test_cfg.pop('async_sleep_interval', 0.025)`
> does it work?

Oh, plz wait. I'm gonna try that now!

It makes another error like this.
> ![image](https://user-images.githubusercontent.com/13531174/87650328-71fd5c80-c78c-11ea-8ef2-69160ede8294.png)

Hmm.. Where can I get `rpn_head` module.

**Comment by tjsongzw** [comment]
could you try to modify
https://github.com/open-mmlab/mmdetection/blob/d613f216b2d9fa9dab3eaa4747f980cc386fb258/mmdet/models/roi_heads/base_roi_head.py#L86

as

```python
    async def async_simple_test(self, x, proposal_list , img_meta, **kwargs):
```

**Comment by blackCmd** [comment]
> could you try to modify
> https://github.com/open-mmlab/mmdetection/blob/d613f216b2d9fa9dab3eaa4747f980cc386fb258/mmdet/models/roi_heads/base_roi_head.py#L86
> 
> as
> 
> ```python
>     async def async_simple_test(self, x, proposal_list , img_meta, **kwargs):
> ```

I thank you for your kindness bro. But I don't have a time to try it now... Sorry...ㅠ_ㅠ

I will do that in 24h ! And I'll reply as soon as possible.

**Comment by anthonyshao009** [comment]
same issue in purest tests/test_async.py could be solved in this way
> `RPNHead` shouldn't have `rpn_head` I guess, it points `self`
> 
> `sleep_interval = self.rpn_head.test_cfg.pop('async_sleep_interval', 0.025)`
> ->
> `sleep_interval = self.test_cfg.pop('async_sleep_interval', 0.025)`
> does it work?

**Comment by blackCmd** [comment]
> could you try to modify
> https://github.com/open-mmlab/mmdetection/blob/d613f216b2d9fa9dab3eaa4747f980cc386fb258/mmdet/models/roi_heads/base_roi_head.py#L86
> 
> as
> 
> ```python
>     async def async_simple_test(self, x, proposal_list , img_meta, **kwargs):
> ```

I did that and I got a this error.
> ![image](https://user-images.githubusercontent.com/13531174/87736680-c861ae00-c813-11ea-8684-44e1201d74bf.png)

When I debug that error I found `async_simple_test` function is not implemented....
> https://github.com/open-mmlab/mmdetection/blob/d613f216b2d9fa9dab3eaa4747f980cc386fb258/mmdet/models/roi_heads/base_roi_head.py#L86

**Comment by tjsongzw** [comment]
which specific roi head do you take? CascadeRoIHead? 
https://github.com/open-mmlab/mmdetection/blob/588536de9905feb7f37c2c977d146a64c74ef28e/mmdet/models/roi_heads/standard_roi_head.py#L218
it's implemented in the standard roi head

**Comment by blackCmd** [comment]
> which specific roi head do you take? CascadeRoIHead?
> https://github.com/open-mmlab/mmdetection/blob/588536de9905feb7f37c2c977d146a64c74ef28e/mmdet/models/roi_heads/standard_roi_head.py#L218
> 
> 
> it's implemented in the standard roi head

Oh! How did you know that I took Cascasde model !
I took this model▼
> 
![image](https://user-images.githubusercontent.com/13531174/87744315-24353280-c826-11ea-9414-5e07e5a83e05.png)

**Comment by thuwyh** [comment]
> self.rpn_head.test_cfg.pop('async_sleep_interval', 0.025)

this works

**Comment by blackCmd** [comment]
> > self.rpn_head.test_cfg.pop('async_sleep_interval', 0.025)
> 
> this works

OH! Where is that code bro?!

**Comment by PawelFaron** [comment]
Same here. Lets hope it will be implemented one day :)
