### ISSUE TITLE
When testing the coco test data set, how should I get the test results without the annotation file?

### ISSUE THREAD

**Issue by gjxgjxgjxgjx** [open-mmlab/mmdetection#3327]
train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=What should I write on this line？？？
        img_prefix=data_root + 'test2017/',
        pipeline=test_pipeline))

**Comment by hyz-xmaster** [comment]
image_info_test2017.json or image_info_test-dev2017.json.
Please refer to [coco annotations](https://cocodataset.org/#download) for more details. 
You should use --format-only and --options arguments to save the results for coco test set. See this example [6. Test Mask R-CNN on COCO test-dev with 8 GPUs](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md).

**Comment by gjxgjxgjxgjx** [comment]
@hyz-xmaster  Problem solved. Thanks!
