### ISSUE TITLE
Incomplete config file in gfl configurations

### ISSUE THREAD

**Issue by Atul997** [open-mmlab/mmdetection#3328]
The config fie inside the config folder of gfl are incomplete I am trying to reimplement their models for custom dataset. But I found that config files are incomplete for the given models. Why is it so?

**Comment by ZwwWayne** [comment]
Please refer to the [doc of config system](https://mmdetection.readthedocs.io/en/latest/config.html#config-system). We use inheritance to reduce the duplicate keys in configs.

**Comment by Atul997** [comment]
Thanks
