### ISSUE TITLE
old config file working on 1.x is not detecting tables in images after conversion to 2.x

### ISSUE THREAD

**Issue by peeyushpashine** [open-mmlab/mmdetection#3329]
Hi,

I was using old config file of type CascadeRCNN with backbone as HRnet and was working fine on table detection in images.
I converted my model weights it using guideline mentioned in:

https://github.com/open-mmlab/mmdetection/tree/master/configs/legacy_1.x

I do not see any examples for backbone HRnet, and took the below config as an example:

https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/cascade_mask_rcnn_r50_fpn.py

My old config was:

https://github.com/DevashishPrasad/CascadeTabNet/blob/master/Config/cascade_mask_rcnn_hrnetv2p_w32_20e.py

With latest release 2.2.1 while doing inference I see weird detection bboxes on tables in images.

My changed config file is:

https://gist.github.com/peeyushpashine/5ee3bb4e70a5dda1ae4d9aabfc9d6123

Any suggestions on why this could be happening?

Thanks,
Peeyush

**Comment by ZwwWayne** [comment]
Hi @peeyushpashine ,
We do not present the config using HRNet because the legacy modification is mainly about anchor generators and box coders in heads. Using the original config of HRNet should be fine unless we refactor this backbone.

From your changed config, I did not find any problem. So could you describe more specifically about the ` weird detection boxes`?

**Comment by peeyushpashine** [comment]
<img width="375" alt="Screenshot 2020-07-17 at 6 23 28 PM" src="https://user-images.githubusercontent.com/1849556/87788251-ad665c80-c85a-11ea-9878-5fa05e452a5f.png">

With v1.x it was coming off like this above but now with v2.2.1, it is coming off as below:

<img width="515" alt="Screenshot 2020-07-17 at 6 20 31 PM" src="https://user-images.githubusercontent.com/1849556/87788327-cd961b80-c85a-11ea-95d1-b65b493d6570.png">

@ZwwWayne

**Comment by ZwwWayne** [comment]
It seems that the table is detected but there are many false positives. You might need to change the thresholds of nms or scores.

**Comment by peeyushpashine** [comment]
@ZwwWayne : Thanks for the comment. I figured out it was class related issue. When i gave no of classes +1, it started detecting the tables.
