### ISSUE TITLE
inference_detector for Fast R-CNN or models finetuned with GA RPN

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3332]
It seems that inference_detector for models without RPN does not pick up the pickled proposals, whereas tools/test.py does. 

Thanks.

**Reproduction**
1. What command or script did you run?
```
model = init_detector("/content/mmdetection/configs/project/htc_no_seg_ga_rpn.py", checkpoint_file)
result = inference_detector(model, img)
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Config has link to the proposals.pkl and works for tools/test.py

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "mmdetection/mmdet/apis/inference.py", line 95, in inference_detector(model, img)
    data = test_pipeline(data)
  File "mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__(self, data)
    data = t(data)
  File "mmdetection/mmdet/datasets/pipelines/loading.py", line 387, in __call__(self, results)
    proposals = results['proposals']
KeyError: 'proposals'
```

**Comment by ZwwWayne** [comment]
You need to add  path of `proposals` in your config.

**Comment by sehyungp92** [comment]
@ZwwWayne, many thanks for the response. I definitely have and it works when producing evaluation metrics using tools/test.py but throws an error when using inference_detector, mainly for visualisation purposes.

**Comment by ZwwWayne** [comment]
1. You did not pass the proposals of this image to the detector.
2. Current `inference_detector` function do not support the Fast R-CNN behavior. As you can see, the function only allows input of `(model, img)`.

Therefore, you need the modify the `inference_detector(model, img)` to allow proposals to be passed to the model.
