### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by kartikJ-9** [open-mmlab/mmdetection#3334]
I am implementing Cascade RPN (one of the projects implemented with mmdetection). On running the train.py and test.py script, there is a epoch1.pth file generated along with the tf_logs. But, I am not able to get the mAP value chart for the same. 

I have 4 class IDs for the detection task. 
Following is the error:
File "/home/user/Downloads/mmdetection-master/mmdet/core/evaluation/bbox_overlaps.py", line 33, in bbox_overlaps
    area2 = (bboxes2[:, 2] - bboxes2[:, 0] + 1) * (
IndexError: too many indices for array

I am a beginner in this domain, and any help with this would be appreciated. Thanks.
![image](https://user-images.githubusercontent.com/41812957/87752965-2e076780-c81f-11ea-8e0b-03906c528229.png)
![image](https://user-images.githubusercontent.com/41812957/87753036-542d0780-c81f-11ea-9a07-307f64f48ff6.png)

**Comment by ZwwWayne** [comment]
Hi @kartikJ-9 ,
You might need to check your detection output. It seems that the box result used for evaluation are not a 2D array but a 1D array.
