### ISSUE TITLE
where's the cuda nms ? I have seen it at mmdet\ops\nms\src before, but I can't find the nms code in this version. 

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#3335]
just as above.

**Comment by xuanthuyvo** [comment]
https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py

**Comment by clw5180** [comment]
> https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py

Thanks！
