### ISSUE TITLE
pycocotools._mask.frPyObjects IndexError: list index out of range

### ISSUE THREAD

**Issue by farshid-mi** [open-mmlab/mmdetection#3338]
hi,i'm trying to implement **mask_rcnn** on **colab** for a **custom dataset(GWHD)** provided in coco style(json file) with config below:

> model = dict(
>     type='MaskRCNN',
>     pretrained='torchvision://resnet50',
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=0,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=True,
>         style='pytorch'),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         num_outs=5),
>     rpn_head=dict(
>         type='RPNHead',
>         in_channels=256,
>         feat_channels=256,
>         anchor_generator=dict(
>             type='AnchorGenerator',
>             scales=[8],
>             ratios=[0.5, 1.0, 2.0],
>             strides=[4, 8, 16, 32, 64]),
>         bbox_coder=dict(
>             type='DeltaXYWHBBoxCoder',
>             target_means=[0.0, 0.0, 0.0, 0.0],
>             target_stds=[1.0, 1.0, 1.0, 1.0]),
>         loss_cls=dict(
>             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
>         loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
>     roi_head=dict(
>         type='StandardRoIHead',
>         bbox_roi_extractor=dict(
>             type='SingleRoIExtractor',
>             roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
>             out_channels=256,
>             featmap_strides=[4, 8, 16, 32]),
>         bbox_head=dict(
>             type='Shared2FCBBoxHead',
>             in_channels=256,
>             fc_out_channels=1024,
>             roi_feat_size=7,
>             num_classes=1,
>             bbox_coder=dict(
>                 type='DeltaXYWHBBoxCoder',
>                 target_means=[0.0, 0.0, 0.0, 0.0],
>                 target_stds=[0.1, 0.1, 0.2, 0.2]),
>             reg_class_agnostic=False,
>             loss_cls=dict(
>                 type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
>             loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
>         mask_roi_extractor=dict(
>             type='SingleRoIExtractor',
>             roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
>             out_channels=256,
>             featmap_strides=[4, 8, 16, 32]),
>         mask_head=dict(
>             type='FCNMaskHead',
>             num_convs=4,
>             in_channels=256,
>             conv_out_channels=256,
>             num_classes=1,
>             loss_mask=dict(
>                 type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))))
> train_cfg = dict(
>     rpn=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.7,
>             neg_iou_thr=0.3,
>             min_pos_iou=0.3,
>             match_low_quality=True,
>             ignore_iof_thr=-1),
>         sampler=dict(
>             type='RandomSampler',
>             num=256,
>             pos_fraction=0.5,
>             neg_pos_ub=-1,
>             add_gt_as_proposals=False),
>         allowed_border=-1,
>         pos_weight=-1,
>         debug=False),
>     rpn_proposal=dict(
>         nms_across_levels=False,
>         nms_pre=2000,
>         nms_post=1000,
>         max_num=1000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.5,
>             neg_iou_thr=0.5,
>             min_pos_iou=0.5,
>             match_low_quality=True,
>             ignore_iof_thr=-1),
>         sampler=dict(
>             type='RandomSampler',
>             num=512,
>             pos_fraction=0.25,
>             neg_pos_ub=-1,
>             add_gt_as_proposals=True),
>         mask_size=28,
>         pos_weight=-1,
>         debug=False))
> test_cfg = dict(
>     rpn=dict(
>         nms_across_levels=False,
>         nms_pre=1000,
>         nms_post=1000,
>         max_num=1000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=dict(
>         score_thr=0.05,
>         nms=dict(type='nms', iou_threshold=0.5),
>         max_per_img=100,
>         mask_thr_binary=0.5))
> dataset_type = 'CocoDataset'
> classes = ('wheat', )
> data_root = ''
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
>     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>     dict(type='RandomFlip', flip_ratio=0.5),
>     dict(
>         type='Normalize',
>         mean=[123.675, 116.28, 103.53],
>         std=[58.395, 57.12, 57.375],
>         to_rgb=True),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(1333, 800),
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(
>                 type='Normalize',
>                 mean=[123.675, 116.28, 103.53],
>                 std=[58.395, 57.12, 57.375],
>                 to_rgb=True),
>             dict(type='Pad', size_divisor=32),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img'])
>         ])
> ]
> data = dict(
>     samples_per_gpu=4,
>     workers_per_gpu=0,
>     train=dict(
>         type='CocoDataset',
>         classes=('wheat', ),
>         ann_file='/content/data_xywh_full_bbox_segm/train_ins.json',
>         img_prefix='',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
>             dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>             dict(type='RandomFlip', flip_ratio=0.5),
>             dict(
>                 type='Normalize',
>                 mean=[123.675, 116.28, 103.53],
>                 std=[58.395, 57.12, 57.375],
>                 to_rgb=True),
>             dict(type='Pad', size_divisor=32),
>             dict(type='DefaultFormatBundle'),
>             dict(
>                 type='Collect',
>                 keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
>         ]),
>     val=dict(
>         type='CocoDataset',
>         classes=('wheat', ),
>         ann_file='/content/data_xywh_full_bbox_segm/val_ins.json',
>         img_prefix='',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(
>                 type='MultiScaleFlipAug',
>                 img_scale=(1333, 800),
>                 flip=False,
>                 transforms=[
>                     dict(type='Resize', keep_ratio=True),
>                     dict(type='RandomFlip'),
>                     dict(
>                         type='Normalize',
>                         mean=[123.675, 116.28, 103.53],
>                         std=[58.395, 57.12, 57.375],
>                         to_rgb=True),
>                     dict(type='Pad', size_divisor=32),
>                     dict(type='ImageToTensor', keys=['img']),
>                     dict(type='Collect', keys=['img'])
>                 ])
>         ]),
>     test=dict(
>         type='CocoDataset',
>         classes=('wheat', ),
>         ann_file='/content/data_xywh_full_bbox_segm/test_ins.json',
>         img_prefix='',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(
>                 type='MultiScaleFlipAug',
>                 img_scale=(1333, 800),
>                 flip=False,
>                 transforms=[
>                     dict(type='Resize', keep_ratio=True),
>                     dict(type='RandomFlip'),
>                     dict(
>                         type='Normalize',
>                         mean=[123.675, 116.28, 103.53],
>                         std=[58.395, 57.12, 57.375],
>                         to_rgb=True),
>                     dict(type='Pad', size_divisor=32),
>                     dict(type='ImageToTensor', keys=['img']),
>                     dict(type='Collect', keys=['img'])
>                 ])
>         ]))
> evaluation = dict(metric=['bbox', 'segm'])
> optimizer = dict(type='SGD', lr=0.015, momentum=0.9, weight_decay=0.0001)
> optimizer_config = dict(grad_clip=None)
> lr_config = dict(
>     policy='step',
>     warmup='linear',
>     warmup_iters=500,
>     warmup_ratio=0.001,
>     step=[4])
> total_epochs = 5
> checkpoint_config = dict(interval=1)
> log_config = dict(
>     interval=50,
>     hooks=[dict(type='TextLoggerHook'),
>            dict(type='TensorboardLoggerHook')])
> dist_params = dict(backend='nccl')
> log_level = 'INFO'
> load_from = 'https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/mask_rcnn/mask_rcnn_r50_fpn_1x_coco/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth'
> resume_from = None
> workflow = [('train', 1)]

```
def close_contour(contour):
    if not np.array_equal(contour[0], contour[-1]):
        contour = np.vstack((contour, contour[0]))
    return contour

def binary_mask_to_polygon(binary_mask, tolerance=0):
    """Converts a binary mask to COCO polygon representation
    Args:
        binary_mask: a 2D binary numpy array where '1's represent the object
        tolerance: Maximum distance from original points of polygon to approximated
            polygonal chain. If tolerance is 0, the original coordinate array is returned.
    """
    polygons = []
    # pad mask to close contours of shapes which start and end at an edge
    padded_binary_mask = np.pad(binary_mask, pad_width=1, mode='constant', constant_values=0)
    contours = measure.find_contours(padded_binary_mask, 0.5)
    contours = np.subtract(contours, 1)
    for contour in contours:
        contour = close_contour(contour)
        contour = measure.approximate_polygon(contour, tolerance)
        if len(contour) < 3:
            continue
        contour = np.flip(contour, axis=1)
        segmentation = contour.ravel().tolist()
        # after padding and subtracting 1 we may get -0.5 points in our segmentation 
        segmentation = [0 if i < 0 else i for i in segmentation]
        polygons.append(segmentation)

    return polygons
```

in order to fill segmentation field as needed based on coco style,i used **otsu thresholding algorithm on bboxes** in dataset **+ function above**(found on github) for producing polygons(this version of dataset **worked correctly for a custom implementation of faster_rcnn_r50_fpn_1x_coco** model----> bbox_map_50=76.5) but after using this data **for same custom implementation of mask_rcnn_r50_fpn_1x_coco**,i faced the same **list index out of range error** which after **removing annotations with empty segmentation field** it worked finely only that it seems like it(mask_rcnn) did **not trained as well** as faster_rcnn model(less bbox_map_50) so i decided to reuse those deleted annotations but this time i **filled those segmentation fields with polygons of the bboxes themselves(rectangular shape)**! and now i'm getting **the same error list index out of range**.

> 2020-07-18 05:26:14.673321: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
>   File "/content/mmdetection/tools/train.py", line 153, in <module>
>     main()
>   File "/content/mmdetection/tools/train.py", line 149, in main
>     meta=meta)
>   File "/content/mmdetection/mmdet/apis/train.py", line 128, in train_detector
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
>     for i, data_batch in enumerate(data_loader):
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
>     data = self._next_data()
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 385, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/content/mmdetection/mmdet/datasets/custom.py", line 187, in __getitem__
>     data = self.prepare_train_img(idx)
>   File "/content/mmdetection/mmdet/datasets/custom.py", line 210, in prepare_train_img
>     return self.pipeline(results)
>   File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
>     data = t(data)
>   File "/content/mmdetection/mmdet/datasets/pipelines/loading.py", line 339, in __call__
>     results = self._load_masks(results)
>   File "/content/mmdetection/mmdet/datasets/pipelines/loading.py", line 291, in _load_masks
>     [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
>   File "/content/mmdetection/mmdet/datasets/pipelines/loading.py", line 291, in <listcomp>
>     [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
>   File "/content/mmdetection/mmdet/datasets/pipelines/loading.py", line 247, in _poly2mask
>     rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
>   File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
> IndexError: list index out of range

i've already read some of these segmentation fields and made sure that they are **not empty anymore!**
example of segmentation field out of otsu algorithm:

> [[383.0, 219.5, 334.0, 195.5, 307.0, 219.5, 327.5, 193.0, 290.0, 173.5, 288.5, 165.0, 337.0, 184.5, 373.5, 147.0, 365.5, 135.0, 383.0, 134.5, 383.5, 169.0, 374.0, 156.5, 345.5, 185.0, 383.0, 198.5, 383.0, 219.5]]

and one that takes all the bbox as instance region:

> [[394.0, 224.5, 308.0, 224.5, 307.5, 143.0, 394.0, 142.5, 394.0, 224.5]]

-so what is the problem?!
-are those empty segmentation fields even a problem?! do i really **need to delete** those from dataset?!
-or maybe it worked before because faster_rcnn did not need segmentation field to work?!

*another reason for reusing pruned annotations with [bbox filled]segmentation fields was that the mask_rcnn model which worked with the pruned dataset did **not see any improvement in segm_map_50**([-]stuck at zero during train and test)([+]good accuracy--->82% and loss_mask---->0.097) and that model **produced fine bboxes** in inference but only **a few sparse stains(not all object surface and not even for all the objects)**!

-maybe the dataset problem(resulted in index out of range error) made segm_map_50 zero before and there was no need for making changes to the segmentation fields?!!

**Comment by sunnyisabaster** [comment]
Hi man, please check ur 'mask_ann'. For me, some annotations only have 3 or 2 points, which I called bad segmentations. These bad segmentations occurred because of mistakes during the data annotation or processing. So, please check ur annotation file and make sure that u don't have 3 or 2 segmentation points in ur annotation label. I suppose the pycocotools/_mask.pyx in the mmdetection is similar to  here: https://github.com/cocodataset/cocoapi/blob/ed842bffd41f6ff38707c4f0968d2cfd91088688/PythonAPI/pycocotools/_mask.pyx#L293

**Comment by quocnhat** [comment]
> Hi man, please check ur 'mask_ann'. For me, some annotations only have 3 or 2 points, which I called bad segmentations. These bad segmentations occurred because of mistakes during the data annotation or processing. So, please check ur annotation file and make sure that u don't have 3 or 2 segmentation points in ur annotation label. I suppose the pycocotools/_mask.pyx in the mmdetection is similar to here: https://github.com/cocodataset/cocoapi/blob/ed842bffd41f6ff38707c4f0968d2cfd91088688/PythonAPI/pycocotools/_mask.pyx#L293
This is the answer, Thanks very much

**Comment by paulineml** [comment]
This didn't solve the problem, do you have another solution for this ?
