### ISSUE TITLE
Will mmdetection support a function for registering the custom dataset (in COCO or VOC format) like Detectron2?

### ISSUE THREAD

**Issue by SkeletonOne** [open-mmlab/mmdetection#3341]
**Describe the feature**

**Motivation**
First of all, mmdetection is a great work and it contains rich models for users. I used detectron2 previously, and I am currently trying to do something with mmdetection because of its advantages over detectron2.
However, the first thing to do is to deal with my custom dataset. In detectron2, there is a function 'register_coco_instances' to register COCO format dataset in one line of code. However, it does not support VOC format, as the issue shows: https://github.com/facebookresearch/detectron2/issues/991. 
The official colab tutorial of mmdetection gives a introduction of registering a dataset to middle format, but no COCO format, so I am still a little bit confused.
Therefore, I am hoping that mmdetection can support  something like 'register_coco_instances' or 'register_voc_instances', that will be easy for users to register their own dataset, because it is easy for one to transfer their own labels to coco/voc format via a simple script. Thanks.

**Comment by hellock** [comment]
Option 1: https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html#modify-classes-of-existing-dataset
Option 2: Overwrite COCO dataset and register it.

**Comment by SkeletonOne** [comment]
@hellock Thanks for your kindly reply. It is quite easy to implement :)
