### ISSUE TITLE
The ap of the coco test-dev

### ISSUE THREAD

**Issue by zlx-6** [open-mmlab/mmdetection#3342]
hi, when i down the weights of the faster rcnn with R-50-FPN (pytorch style) and uses the tool/tests to get the json file, and i upload the json file to the coco official website. and i get the finally AP is 37.7, but in the model zoo, the AP is 37.4.

**Comment by hellock** [comment]
We report the AP on COCO 2017val in the model zoo.

**Comment by zlx-6** [comment]
thanks, why the results of the test-dev are  better than the results of the val ?

**Comment by ZwwWayne** [comment]
> thanks, why the results of the test-dev are better than the results of the val ?

The data in test-dev is different from that in val. This is just a common phenomenon in COCO.
