### ISSUE TITLE
About how to solve the problem of "ModuleNotFoundError: No module named 'mmcv.ops'" 

### ISSUE THREAD

**Issue by UESTC-Liuxin** [open-mmlab/mmdetection#3343]
Problem Description:
When I pulled the latest version on 2020/7/18: mmcv was added. I got an error like ModuleNotFoundError: No module named'mmcv.ops'. The guess is that the installation of mmcv is not complete.
Solution:
Force to merge and copy all files of mmcv/mmcv to the following path: ~/.conda/envs/{your conda sub-environment name}/lib/python3.7/site-packages/mmcv

**Comment by ZwwWayne** [comment]
Please refer to the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md#install-mmdetection).
This issue duplicates https://github.com/open-mmlab/mmdetection/issues/3321 so it is closed.
