### ISSUE TITLE
voc recall go wrong

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3344]
Error occurred in evaluate retinanet-voc's recall.
In mmdet.core.eval_recalls,
args:
       proposals(list[array])
but, actuallt proposals is list[list[array]].

**Comment by xgm-web** [comment]
en, voc's mAP  have recall about each class. the voc's recall is used to  rpn ,but retinanet is one-shot,it has no rpn,so it's error,i think.

**Comment by hellock** [comment]
We compute mAP for RetinaNet and recall for RPN.
