### ISSUE TITLE
能否出一个中文版的文档

### ISSUE THREAD

**Issue by langxj** [open-mmlab/mmdetection#3350]
首先，感谢这一个杰出的开源项目！我的问题是，虽然程序员群体对英文文档要求是必备技能，但还是有大量中国开发者群体更希望看到中文文档，这样阅读起来更方便和高效，能否对说明文档提供一份中文版的？

**Comment by hellock** [comment]
Thanks for the suggestion. We have no recent plan for that due to the lack of developers. If there is dedicated commmunity support for that, we are glad to accept and have a collaboration.
