### ISSUE TITLE
Hello, how do I get the code of MMdet V1.x? And how to judge the correspondence between MMdet version and mmcv version? Thank you 

### ISSUE THREAD

**Issue by limengfei3675** [open-mmlab/mmdetection#3351]
Hello, how do I get the code of MMdet V1.x? And how to judge the correspondence between MMdet version and mmcv version? Thank you

**Comment by hellock** [comment]
You can checkout to any tags like v1.2.0, v1.1.0, etc. MMCV 0.6.2 should work with mmdet 1.x.

**Comment by ZwwWayne** [comment]
The version compatibility between mmdet & mmcv can be found [here](https://mmdetection.readthedocs.io/en/latest/install.html#install-mmdetection). The issue is closed because the questions are answered.
