### ISSUE TITLE
Error in init_detector

### ISSUE THREAD

**Issue by Atul997** [open-mmlab/mmdetection#3354]
While initiaising the model in mmdetection I am getting following error 

`model = init_detector(config_file, checkpoint_file, device='cuda:0')`

Error-

`TypeError
Traceback (most recent call last)

<ipython-input-15-fa18f63b83cc> in <module>()
      6 
      7 # build the model from a config file and a checkpoint file
----> 8 model = init_detector(config_file, checkpoint_file, device='cuda:0')
      9 

9 frames

/content/mmdetection/mmdet/models/dense_heads/gfl_head.py in __init__(self, num_classes, in_channels, stacked_convs, conv_cfg, norm_cfg, loss_dfl, reg_max, **kwargs)
    103         self.norm_cfg = norm_cfg
    104         self.reg_max = reg_max
--> 105         super(GFLHead, self).__init__(num_classes, in_channels, **kwargs)
    106 
    107         self.sampling = False

TypeError: __init__() got an unexpected keyword argument 'octave_base_scale'`

**Comment by ZwwWayne** [comment]
What does your config look like? Could you post your full config?

**Comment by Atul997** [comment]
# model settings
    model = dict(
    type='ATSS',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs=True,
        extra_convs_on_inputs=False,
        num_outs=5),
    bbox_head=dict(
        type='GFLHead',
        num_classes=4,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        octave_base_scale=8,
        scales_per_octave=1,
        anchor_ratios=[1.0],
        anchor_strides=[8, 16, 32, 64, 128],
        target_means=[.0, .0, .0, .0],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        loss_qfl=dict(
            type='QualityFocalLoss',
            use_sigmoid=True,
            beta=2.0,
            loss_weight=1.0),
        loss_dfl=dict(
            type='DistributionFocalLoss',
            loss_weight=0.25),
        reg_max=16,
        loss_bbox=dict(type='GIoULoss', loss_weight=2.0)))
# training and testing settings
    train_cfg = dict(
    assigner=dict(type='ATSSAssigner', topk=9),
    allowed_border=-1,
    pos_weight=-1,
    debug=False)
    test_cfg = dict(
    nms_pre=1000,
    min_bbox_size=0,
    score_thr=0.05,
    nms=dict(type='nms', iou_thr=0.6),
    max_per_img=100)
# dataset settings
   dataset_type = 'CocoDataset'
   data_root = '/content/drive/My Drive/tabnet/data/VOC2007/'

   img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
    train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
     ]
    test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
       ]
    data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'coco/train.json',
        img_prefix=data_root + 'JPEGImages/Train/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'coco/val.json',
        img_prefix=data_root + 'JPEGImages/Test/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'coco/val.json',
        img_prefix=data_root + 'JPEGImages/Test/',
        pipeline=test_pipeline))
    evaluation = dict(interval=1, metric='bbox')
# optimizer
    #optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
   #optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))

    optimizer = dict(
    type='SGD',
    lr=0.01,
    momentum=0.9,
    weight_decay=0.0001,
    paramwise_options=dict(bias_lr_mult=2., bias_decay_mult=0.))
    optimizer_config = dict(grad_clip=None)


# learning policy
    lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
    checkpoint_config = dict(interval=1)
# yapf:disable
   log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
   total_epochs = 30 #
   dist_params = dict(backend='nccl')
   log_level = 'INFO'
   work_dir = './work_dirs/gfl_r50_1x'
   load_from = None
   resume_from = None
   workflow = [('train', 1)]               
`

**Comment by Ekct00** [comment]
same issue on Jetson AGX

**Comment by ZwwWayne** [comment]
It seems that the config is for V1.x rather than for V2.x. You can check [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/legacy_1.x) to migrate the config from v1.x to v2.x.
