### ISSUE TITLE
Can I set ignore region(do not return gradient) during training model?

### ISSUE THREAD

**Issue by fengqian-wei** [open-mmlab/mmdetection#3355]
I get a dataset which have many object, but some object is too small to label. So people labels this region as ignore area. 
I want to train a model which not  calculate loss  for the object in ignore region. What should I do ? Thank you very much!

**Comment by hellock** [comment]
Ignored bboxes are already supported, like in COCO/VOC datasets.

**Comment by sisrfeng** [comment]
Hi, would you mind telling me how to handle the ignore region? Some people just mask the region with a black box, which I think may change some information of the original image.
 

> Ignored bboxes are already supported,

Does this mean mmdetection can ignore the  loss for the objects in ignore region? Which file should I change?

Thx!
