### ISSUE TITLE
When using tensorboard, how do I make the horizontal axis of the mAP curve become epoch instead of the number of iterations? 

### ISSUE THREAD

**Issue by gjxgjxgjxgjx** [open-mmlab/mmdetection#3358]
Also, is there any instructions on using tensorboard in mmdetection?

**Comment by ZwwWayne** [comment]
By simply uncomment [this line](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/default_runtime.py#L7) you can use tensorboard. Since the log is recorded based on iterations, so you might need to modify MMCV to record mAP based on epoch rather than iteration.
