### ISSUE TITLE
Evaluation metrics logged with "train" suffix in TensorBoard

### ISSUE THREAD

**Issue by ayushjaiswal** [open-mmlab/mmdetection#3362]
[EvalHook](https://github.com/open-mmlab/mmdetection/blob/ba595cf7d8f904a97f764bf1818bd0d598ec0716/mmdet/core/evaluation/eval_hooks.py) is implemented with `after_train_epoch` function. Therefore, it runs after the training for the epoch is finished but the `runner.mode` is still `train`. Because of this, [TensorboardLoggerHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/tensorboard.py#L49) logs the evaluation metrics as `<metric_name>/train`:

```python
tag = f'{var}/{runner.mode}'
```

Not sure what the best solution to this is.

**Comment by ayushjaiswal** [comment]
I have verified that a possible workaround is to change `after_train_epoch` definitions to `after_val_epoch` definitions for EvalHook and DistEvalHook. However, this requires `('val', <epochs>)` to be in the workflow.

**Comment by ZwwWayne** [comment]
What is it for? The mode indicates when the evaluation is performed.

**Comment by ayushjaiswal** [comment]
Yes, I understand, but the problem is that in the current setup, TensorBoard logs and visualization show evaluation metrics with `train` suffix, e.g., `mAP/train` even though the mAP is actually the val/test mAP.

**Comment by hellock** [comment]
This is a known issue.

**Comment by hellock** [comment]
Already fixed in the latest version.
