### ISSUE TITLE
I want to predict the label from result = inference_detector(model, img), what should I do？ Thanks

### ISSUE THREAD

**Issue by 1159172858** [open-mmlab/mmdetection#3364]
What command or script did you run?
model = init_detector("/content/mmdetection/configs/project/htc_no_seg_ga_rpn.py", checkpoint_file)
result = inference_detector(model, img)

**Comment by hellock** [comment]
What do you mean? `result` is the detection result which contains all detected bboxes.

**Comment by 1159172858** [comment]
> What do you mean? `result` is the detection result which contains all detected bboxes.
I know，I also want to get the 'category' or 'category_id' corresponding to each bbox from the ‘result’

**Comment by hellock** [comment]
`result` is a list, and the index corresponds to the category id.

**Comment by 1159172858** [comment]
ok. Thanks

**Comment by biao321** [comment]
> What command or script did you run?
> model = init_detector("/content/mmdetection/configs/project/htc_no_seg_ga_rpn.py", checkpoint_file)
> result = inference_detector(model, img)

How can I predict with multi gpus? And does "imgs per gpu"  work during predicting? It takes an hour for me to predict.

**Comment by vikas94** [comment]
> `result` is a list, and the index corresponds to the category id.

result is a tuple of two lists, first list contains list(ndarrays), second list contains what?
