### ISSUE TITLE
what about of dataset sampler

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3367]
In non-distribued training, the code only guarantees that the data set can be evenly divided by the number of GPU.
i.e. `num_samples = int(np.ceil(len(dataset) / samples_per_gpu) * samples_per_gpu)`
but, that's going to happen:
len(dataset) = 6, samples_per_gpu = 2, num_gpu = 2
In a iteration, batch_size = samples_per_gpu * num_gpu, 
Then what about the remaining two imgs and less than one batch_size?

**Comment by ZwwWayne** [comment]
The remaining two images will not be used. Since the sampling process is random, the two images thrown are different during each epoch. If the epoch number is large, the effect is negligible.

**Comment by zhjw0927** [comment]
Thank you! I know it.
