### ISSUE TITLE
How do I know which version of mmdetection I downloaded? 

### ISSUE THREAD

**Issue by gjxgjxgjxgjx** [open-mmlab/mmdetection#3368]
The other code I downloaded is not clearly stated.

**Comment by liaopeiyuan** [comment]
```
>>> import mmdet
>>> print(mmdet.__version__)
2.2.0+cb94bd1
```

**Comment by gjxgjxgjxgjx** [comment]
How do I know the version without installing it? I just downloaded this code from github.  

Running your suggestion directly will have the following errors

I cannot find the version.py file in the mmdet directory

>>> import mmdet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "H:\Det\D2Det\mmdet\__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'

**Comment by ZwwWayne** [comment]
mmdet/VERSION.
