### ISSUE TITLE
Can I extract bottom up attention features?

### ISSUE THREAD

**Issue by hairzooc** [open-mmlab/mmdetection#3369]
Thanks for the great work!

I've been finding bottom up attention feature extractor so far.
Even if there're caffe and pytorch version, these modules were hard to install. (especially detectron2 old version these repo used)
https://github.com/peteanderson80/bottom-up-attention (original caffe version)
https://github.com/airsplay/py-bottom-up-attention (pytorch with detectron2)
https://github.com/MILVLG/bottom-up-attention.pytorch (another pytorch with detectron2)

Would it be possible for me to extract bottom up attention features by using mmdetection?
If you guys have some idea on that, Please let me know :)

**Comment by ZwwWayne** [comment]
Yes. To do that, you might need to first implement the bottom-up-attention module in MMDetection. Then you need to implement a detector or write a script that could load the trained models and dump the features of the attention you need.

**Comment by hairzooc** [comment]
Thanks for your feedback!
