### ISSUE TITLE
imgs_per_gpu=2 causes no log recorded when i run "python tools/train.py"

### ISSUE THREAD

**Issue by whyguu** [open-mmlab/mmdetection#337]
when i use imgs_per_gpu=2, workers_per_gpu=2, in config file.
the program keeps running, but there is no log info recorded.

i do not use the dist_train.sh script, instand i just use "python tools.train.py" and relevant arguments are properly  configured in train.py.

this happens in both the latest version and the older version.

**Comment by hellock** [comment]
I cannot reproduce the issue, the logs are normally printed as the training goes on. The command is `python tools/train.py configs/faster_rcnn_r50_fpn_1x.py`.

**Comment by hellock** [comment]
Feel free to reopen it if there is any further updates.
