### ISSUE TITLE
batch_processor disappeared? and MMDataParallel not support multi gpu?

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3370]
I remember there used to be batch_processor, and MMDataParallel could support multi-gpu training.
Its all gone now.
mmdetection or mmcv, which is nightly compiled?
Why does MMDataParallel cancel multi-gpu training?
Thank you!

**Comment by hellock** [comment]
`batch_processor is deprecated and now we define the logic in` model.train_step()`. MMDataParallel only supports single GPU training and we encourage using MMDistributedDataParallel which is much more faster.
