### ISSUE TITLE
How do I change the thickness of the bounding box when I wanna test an image?

### ISSUE THREAD

**Issue by Ruolingdeng** [open-mmlab/mmdetection#3371]
How do I change the thickness of the bounding box when I wanna test an image?

**Comment by ZwwWayne** [comment]
The API `model.show_results()` allows you to set thickness [here](https://github.com/open-mmlab/mmdetection/blob/b05c17e3f6c6a1d8947cd39f7c5c576c8698e655/mmdet/models/detectors/base.py#L266). Therefore, you can set thickness through the [high level API](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L160).

**Comment by ZeeRizvee** [comment]
@ZwwWayne it seems like the code has been updated after recent releases. I am facing a similar problem. Can you please guide how I can modify the thickness of the bounding box during testing?
