### ISSUE TITLE
Question: The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by HymEric** [open-mmlab/mmdetection#3373]
![image](https://user-images.githubusercontent.com/26487821/88139815-0fd8a780-cc23-11ea-96de-a69f9e05647d.png)
Is there anything wrong?

**Comment by ZwwWayne** [comment]
Yes, it seems that the channels in the loaded model are more than the model of your current model. You need to set the `base_channels` and `stem_channels` in the backbone.

**Comment by HymEric** [comment]
OK，I will try. Thanks a lot.
