### ISSUE TITLE
It seems in the configs of fcos, those with GN still use BN

### ISSUE THREAD

**Issue by SkeletonOne** [open-mmlab/mmdetection#3375]
For example, mmdetection/configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py has: "norm_cfg=dict(type='BN', requires_grad=False),", which seems like it is still using BN.

**Comment by ZwwWayne** [comment]
The config file name `fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py` means the FCOS uses resnet50 Caffe-style backbone with FPN and uses GN in the head. So it is right that the backbone still uses BN. Please refer to the [doc](https://mmdetection.readthedocs.io/en/latest/config.html#config-name-style) for more detailed meanings of each config names.

**Comment by zhangh-dev** [comment]
> The config file name `fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py` means the FCOS uses resnet50 Caffe-style backbone with FPN and uses GN in the head. So it is right that the backbone still uses BN. Please refer to the [doc](https://mmdetection.readthedocs.io/en/latest/config.html#config-name-style) for more detailed meanings of each config names.

For auto_assign, change GN into BN in bbox_head, mAP will drop 3% for coco dataset. Can you encountered this problem?
