### ISSUE TITLE
KeyError: 'ConvWS is already registered in conv layer'

### ISSUE THREAD

**Issue by LYKlyk** [open-mmlab/mmdetection#3378]
File "mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 58, in _register_module
    raise KeyError(f'{module_name} is already registered '
KeyError: 'ConvWS is already registered in conv layer'

How to solve this problem? Thank you.

**Comment by ZwwWayne** [comment]
Duplicate https://github.com/open-mmlab/mmdetection/issues/3249
