### ISSUE TITLE
DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple")

### ISSUE THREAD

**Issue by LYKlyk** [open-mmlab/mmdetection#3379]
File "mmlab/lib/python3.7/distutils/command/build_ext.py", line 363, in check_extensions_list
    "each element of 'ext_modules' option must be an "
setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple")

How to solve this problem? Thank you.

**Comment by ZwwWayne** [comment]
Please use the `Error Template` to provide mode information.

**Comment by ZihuaTan** [comment]
I face the same situation here.
could somebody help?

**Comment by 1LOVESJohnny** [comment]
Hi, I met the same problem. Did you find a solution?

**Comment by KevinQian97** [comment]
I also encounter such a problem. And I found out it's because I build the environment from miniconda instead of anaconda. So manually install Cython and pip install -r requirements.txt help me solve the problem.

**Comment by blackCmd** [comment]
> I also encounter such a problem. And I found out it's because I build the environment from miniconda instead of anaconda. So manually install Cython and pip install -r requirements.txt help me solve the problem.

Yes! you save me

**Comment by ZwwWayne** [comment]
> I also encounter such a problem. And I found out it's because I build the environment from miniconda instead of anaconda. So manually install Cython and pip install -r requirements.txt help me solve the problem.

Thanks for your kind solution, would you like to update your experience to the [trouble shooting documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/trouble_shooting.md) thus it could benefit more people? PRs are welcomed.

**Comment by Fly-dream12** [comment]
Have you fixed it ? I have met the same problem as you.

**Comment by Fly-dream12** [comment]
@KevinQian97
