### ISSUE TITLE
Scale must be a number or tuple of int, but got <class 'list'>

### ISSUE THREAD

**Issue by spytensor** [open-mmlab/mmdetection#338]
When I set train scale to `[(800,900),(800,1000)]` ,it works well.But if I change the same scale type for inference,I get the error as the title.If anywhere I set wrong,or I must merge to scale results by myself...

**Comment by hellock** [comment]
It runs smoothly with multiple scales during inference. Maybe you need to provide more information to reproduce it.

**Comment by spytensor** [comment]
Thanks ,I will try it

**Comment by zytx121** [comment]
I meet the same problem with you,  have you fix  it?
