### ISSUE TITLE
Demo error: Distutils was imported before Setuptools. 

### ISSUE THREAD

**Issue by wangzhengshuai** [open-mmlab/mmdetection#3385]
I install the mmdetection. When I run the demo 'image_demo.py', the error 'Distutils was imported before Setuptools. ' occors. Did I install mmdetection successfully? How can I solve this issuce? Thanks!

python demo/image_demo.py demo/demo.jpg configs/guided_anchoring/ga_faster_x101_32x4d_fpn_1x_coco.py checkpoints/ga_faster_x101_32x4d_fpn_1x_coco_20200215-1ded9da3.pth 

error:
/home/wangzs/miniconda2/envs/mmdetection/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
/opt/conda/conda-bld/pytorch_1591914880026/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of addmm is deprecated:
	addmm(Number beta, Tensor input, Number alpha, Tensor mat1, Tensor mat2, *, Tensor out)
Consider using one of the following signatures instead:
	addmm(Tensor input, Tensor mat1, Tensor mat2, *, Number beta, Number alpha, Tensor out)

**Comment by ZwwWayne** [comment]
I only see warnings but no errors. Could your post the full error trace following the `Error Template`?

**Comment by wangzhengshuai** [comment]
> I only see warnings but no errors. Could your post the full error trace following the `Error Template`?

Yes, I check again, it can run successfully. The warning is still existing but the  warnings do not affect the use of the demo. Thanks!
