### ISSUE TITLE
training error on custom dataset based ssd

### ISSUE THREAD

**Issue by At1a8** [open-mmlab/mmdetection#339]
hi，i have trained my dataset on ssd with config<ssd512_coco.py>, but encountered some issues under the following images. Could you please give me some advice to solve this problem?
![image](https://user-images.githubusercontent.com/39615225/53229033-0958a000-36be-11e9-9446-f467806737ab.png)

**Comment by yhcao6** [comment]
How many classes in your dataset?

**Comment by At1a8** [comment]
> How many classes in your dataset?

single class

**Comment by yhcao6** [comment]
Then you need to change the `num_classes` from 81 to 2 in 'ssd512_coco.py'

**Comment by At1a8** [comment]
i have changed num_classes in the config file, but still suffer from this problem.

**Comment by yhcao6** [comment]
Could you run the program again with `CUDA_LAUNCH_BLOCKING=1 python tools/train.py configs/ssd512_coco.py --gpus 1`

**Comment by At1a8** [comment]
> Could you run the program again with `CUDA_LAUNCH_BLOCKING=1 python tools/train.py configs/ssd512_coco.py --gpus 1`

Thank you for your advice, but this issue has not been solved.

**Comment by yhcao6** [comment]
This command is just used to help with debug, is there new error information?

**Comment by At1a8** [comment]
![image](https://user-images.githubusercontent.com/39615225/53231711-930b6c00-36c4-11e9-99bb-0242c47b72c5.png)
![image](https://user-images.githubusercontent.com/39615225/53231740-a0285b00-36c4-11e9-9498-0d90fced20b3.png)
The error message in log is shown in the figure. By the way, i have trained resnet as well as vgg on my dataset and obtained good results. This problem is only encountered when training SSD.

**Comment by yhcao6** [comment]
I just remember there is a similar issue, please refer to #313

**Comment by At1a8** [comment]
> I just remember there is a similar issue, please refer to #313

Thank you so much
