### ISSUE TITLE
Pure ONNX export for MaskRCNN+PointRend

### ISSUE THREAD

**Issue by bpfliegel** [open-mmlab/mmdetection#3393]
Hello,

I'm trying to create a pure ONNX model from the pretrained MaskRCNN+PointRend model that I can CPU infer with onnxruntime, however I did not have luck currently (I tried with the onnx export script explicitly specifying opset 11, but I got some error on constants as ATEN fallback should be specified and that overrides something on the constants)..
As I see ROIAlign and ROIPool are getting moved to MMCV and there is also a large commit in MMCV with ONNX related ops.
Is this something I could do with 2.3 or is it already doable, just I was not able to do?

Thanks for your kind feedback and hints,
Balint

**Comment by xvjiarui** [comment]
Hi @bpfliegel 
Sorry, it is not supported yet.

**Comment by bpfliegel** [comment]
> Hi @bpfliegel
> Sorry, it is not supported yet.

Thanks for your reply Jerry!

**Comment by jhagege** [comment]
> > Hi @bpfliegel
> > Sorry, it is not supported yet.
> 
> Thanks for your reply Jerry!

Hi, did you find any solution / workaround ? 
Thanks !

**Comment by bpfliegel** [comment]
> > > Hi @bpfliegel
> > > Sorry, it is not supported yet.
> > 
> > 
> > Thanks for your reply Jerry!
> 
> Hi, did you find any solution / workaround ?
> Thanks !

Sorry, did not put more effort into it.
