### ISSUE TITLE
How to write recall in json log file

### ISSUE THREAD

**Issue by r376533** [open-mmlab/mmdetection#3396]
Hello everyone

when i train my own dataset 
every epoch will verification onse
i use command like this

python tools/train.py {MyConfig} --work-dir {MyWorkDir}

and program will train and show some info like this( this example is first epoch so mAP is bad)
-------------------
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
---------------------------
when train finish , it will show train log json     yyyymmdd_hhMMss.log.json
and every verification  info like this 
{"mode": "val", "epoch": 1, "iter": 36, "lr": 0.00142, "bbox_mAP": 0.0, "bbox_mAP_50": 0.0, "bbox_mAP_75": 0.0, "bbox_mAP_s": -1.0, "bbox_mAP_m": 0.0, "bbox_mAP_l": 0.0, "bbox_mAP_copypaste": "0.000 0.000 0.000 -1.000 0.000 0.000"}
-----------------------------

I want to add Average Recall  info into json 

how should i do?

THNAK!!!

**Comment by hellock** [comment]
Add what you want to [`eval_results`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L501).

**Comment by hellock** [comment]
#3497
