### ISSUE TITLE
somtimes 'loss_bbox: nan' appear for small object detection

### ISSUE THREAD

**Issue by Soulempty** [open-mmlab/mmdetection#3397]
I want to know some reasons about this phenomenon,thanks for your empirical suggestions.some important details about the train process as followings:
1、use faster_rcnn_r50_caffe_c4.py as baseline;
2、the object sizes of all images are around 32 pixels;
3、the object nums of each image are around 1 or more;
4、other parameters are default.

**Comment by cpboost** [comment]
json file maybe error，

**Comment by Soulempty** [comment]
yes,some xml file exists negative value
