### ISSUE TITLE
About how to make ssd print the value of  "acc"

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmdetection#3405]
Hello! First of all ,thank you for giving us a such perfect project! Second,I want to ask some questions about ssd。I have just used your project for a few days ,when I use  ssd to train my data,I want to make it print the value of "acc", where should I change about this code?Thank you very much!

**Comment by sunnyisabaster** [comment]
Could you post ur configs, pls?

**Comment by baibaidedongdong** [comment]
emmm, sorry, what is ur configs?

**Comment by baibaidedongdong** [comment]
@sunnyisabaster emmm, sorry, what is ur configs?

**Comment by baibaidedongdong** [comment]
`input_size = 300
model = dict(
    type='SingleStageDetector',
    pretrained='open-mmlab://vgg16_caffe',
    backbone=dict(
        type='SSDVGG',
        input_size=300,
        depth=16,
        with_last_pool=False,
        ceil_mode=True,
        out_indices=(3, 4),
        out_feature_indices=(22, 34),
        l2_norm_scale=20),
    neck=None,
    bbox_head=dict(
        type='SSDHead',
        in_channels=(512, 1024, 512, 256, 256, 256),
        num_classes=80,
        anchor_generator=dict(
            type='SSDAnchorGenerator',
            scale_major=False,
            input_size=300,
            basesize_ratio_range=(0.15, 0.9),
            strides=[8, 16, 32, 64, 100, 300],
            ratios=[[2], [2, 3], [2, 3], [2, 3], [2], [2]]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[0.1, 0.1, 0.2, 0.2])))
cudnn_benchmark = True
train_cfg = dict(
    assigner=dict(
        type='MaxIoUAssigner',
        pos_iou_thr=0.5,
        neg_iou_thr=0.5,
        min_pos_iou=0.0,
        ignore_iof_thr=-1,
        gt_max_assign_all=False),
    smoothl1_beta=1.0,
    allowed_border=-1,
    pos_weight=-1,
    neg_pos_ratio=3,
    debug=False)
test_cfg = dict(
    nms=dict(type='nms', iou_threshold=0.45),
    min_bbox_size=0,
    score_thr=0.02,
    max_per_img=200)
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[1, 1, 1], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=[123.675, 116.28, 103.53],
        to_rgb=True,
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(300, 300), keep_ratio=False),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[1, 1, 1],
        to_rgb=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(300, 300),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[1, 1, 1],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=3,
    train=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type='CocoDataset',
            ann_file='data/coco/annotations/instances_train2017.json',
            img_prefix='data/coco/train2017/',
            pipeline=[
                dict(type='LoadImageFromFile', to_float32=True),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(
                    type='PhotoMetricDistortion',
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                dict(
                    type='Expand',
                    mean=[123.675, 116.28, 103.53],
                    to_rgb=True,
                    ratio_range=(1, 4)),
                dict(
                    type='MinIoURandomCrop',
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
                    min_crop_size=0.3),
                dict(type='Resize', img_scale=(300, 300), keep_ratio=False),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[1, 1, 1],
                    to_rgb=True),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(type='DefaultFormatBundle'),
                dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
            ])),
    val=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=1, metric='bbox')
optimizer = dict(type='SGD', lr=0.002, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[16, 22, 30, 42])
total_epochs = 70
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = 'work_dirs/ssd300_coco/epoch_50.pth'
workflow = [('train', 1)]
work_dir = './work_dirs/ssd300_coco'
gpu_ids = range(0, 1)
`

**Comment by baibaidedongdong** [comment]
input_size = 300
model = dict(
    type='SingleStageDetector',
    pretrained='open-mmlab://vgg16_caffe',
    backbone=dict(
        type='SSDVGG',
        input_size=300,
        depth=16,
        with_last_pool=False,
        ceil_mode=True,
        out_indices=(3, 4),
        out_feature_indices=(22, 34),
        l2_norm_scale=20),
    neck=None,
    bbox_head=dict(
        type='SSDHead',
        in_channels=(512, 1024, 512, 256, 256, 256),
        num_classes=80,
        anchor_generator=dict(
            type='SSDAnchorGenerator',
            scale_major=False,
            input_size=300,
            basesize_ratio_range=(0.15, 0.9),
            strides=[8, 16, 32, 64, 100, 300],
            ratios=[[2], [2, 3], [2, 3], [2, 3], [2], [2]]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[0.1, 0.1, 0.2, 0.2])))
cudnn_benchmark = True
train_cfg = dict(
    assigner=dict(
        type='MaxIoUAssigner',
        pos_iou_thr=0.5,
        neg_iou_thr=0.5,
        min_pos_iou=0.0,
        ignore_iof_thr=-1,
        gt_max_assign_all=False),
    smoothl1_beta=1.0,
    allowed_border=-1,
    pos_weight=-1,
    neg_pos_ratio=3,
    debug=False)
test_cfg = dict(
    nms=dict(type='nms', iou_threshold=0.45),
    min_bbox_size=0,
    score_thr=0.02,
    max_per_img=200)
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[1, 1, 1], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=[123.675, 116.28, 103.53],
        to_rgb=True,
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(300, 300), keep_ratio=False),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[1, 1, 1],
        to_rgb=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(300, 300),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[1, 1, 1],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=3,
    train=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type='CocoDataset',
            ann_file='data/coco/annotations/instances_train2017.json',
            img_prefix='data/coco/train2017/',
            pipeline=[
                dict(type='LoadImageFromFile', to_float32=True),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(
                    type='PhotoMetricDistortion',
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                dict(
                    type='Expand',
                    mean=[123.675, 116.28, 103.53],
                    to_rgb=True,
                    ratio_range=(1, 4)),
                dict(
                    type='MinIoURandomCrop',
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
                    min_crop_size=0.3),
                dict(type='Resize', img_scale=(300, 300), keep_ratio=False),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[1, 1, 1],
                    to_rgb=True),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(type='DefaultFormatBundle'),
                dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
            ])),
    val=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=1, metric='bbox')
optimizer = dict(type='SGD', lr=0.002, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[16, 22, 30, 42])
total_epochs = 70
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = 'work_dirs/ssd300_coco/epoch_50.pth'
workflow = [('train', 1)]
work_dir = './work_dirs/ssd300_coco'
gpu_ids = range(0, 1)

**Comment by sunnyisabaster** [comment]
就是发一下你的配置信息------------------&nbsp;Original&nbsp;------------------

**Comment by baibaidedongdong** [comment]
@sunnyisabaster 
已经发了，不好意思，发的有点晚

**Comment by sunnyisabaster** [comment]
> @sunnyisabaster
> 已经发了，不好意思，发的有点晚

你现在的log文件长得是啥样的？

**Comment by baibaidedongdong** [comment]
2020-07-28 19:48:57,163 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce GTX 1660 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+35d732a
OpenCV: 3.4.3
MMCV: 1.0.2
MMDetection: 2.3.0rc0+unknown
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1
------------------------------------------------------------

2020-07-28 19:48:57,163 - mmdet - INFO - Distributed training: False
2020-07-28 19:48:57,449 - mmdet - INFO - Config:
input_size = 300
model = dict(
    type='SingleStageDetector',
    pretrained='open-mmlab://vgg16_caffe',
    backbone=dict(
        type='SSDVGG',
        input_size=300,
        depth=16,
        with_last_pool=False,
        ceil_mode=True,
        out_indices=(3, 4),
        out_feature_indices=(22, 34),
        l2_norm_scale=20),
    neck=None,
    bbox_head=dict(
        type='SSDHead',
        in_channels=(512, 1024, 512, 256, 256, 256),
        num_classes=80,
        anchor_generator=dict(
            type='SSDAnchorGenerator',
            scale_major=False,
            input_size=300,
            basesize_ratio_range=(0.15, 0.9),
            strides=[8, 16, 32, 64, 100, 300],
            ratios=[[2], [2, 3], [2, 3], [2, 3], [2], [2]]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[0.1, 0.1, 0.2, 0.2])))
cudnn_benchmark = True
train_cfg = dict(
    assigner=dict(
        type='MaxIoUAssigner',
        pos_iou_thr=0.5,
        neg_iou_thr=0.5,
        min_pos_iou=0.0,
        ignore_iof_thr=-1,
        gt_max_assign_all=False),
    smoothl1_beta=1.0,
    allowed_border=-1,
    pos_weight=-1,
    neg_pos_ratio=3,
    debug=False)
test_cfg = dict(
    nms=dict(type='nms', iou_threshold=0.45),
    min_bbox_size=0,
    score_thr=0.02,
    max_per_img=200)
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[1, 1, 1], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=[123.675, 116.28, 103.53],
        to_rgb=True,
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(300, 300), keep_ratio=False),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[1, 1, 1],
        to_rgb=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(300, 300),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[1, 1, 1],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=3,
    train=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type='CocoDataset',
            ann_file='data/coco/annotations/instances_train2017.json',
            img_prefix='data/coco/train2017/',
            pipeline=[
                dict(type='LoadImageFromFile', to_float32=True),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(
                    type='PhotoMetricDistortion',
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                dict(
                    type='Expand',
                    mean=[123.675, 116.28, 103.53],
                    to_rgb=True,
                    ratio_range=(1, 4)),
                dict(
                    type='MinIoURandomCrop',
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
                    min_crop_size=0.3),
                dict(type='Resize', img_scale=(300, 300), keep_ratio=False),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[1, 1, 1],
                    to_rgb=True),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(type='DefaultFormatBundle'),
                dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
            ])),
    val=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(300, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=1, metric='bbox')
optimizer = dict(type='SGD', lr=0.002, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[16, 22, 30, 42])
total_epochs = 50
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/ssd300_coco'
gpu_ids = range(0, 1)

2020-07-28 19:48:57,679 - mmdet - INFO - load model from: open-mmlab://vgg16_caffe
2020-07-28 19:48:58,525 - mmdet - WARNING - The model and loaded state dict do not match exactly

missing keys in source state_dict: extra.0.weight, extra.0.bias, extra.1.weight, extra.1.bias, extra.2.weight, extra.2.bias, extra.3.weight, extra.3.bias, extra.4.weight, extra.4.bias, extra.5.weight, extra.5.bias, extra.6.weight, extra.6.bias, extra.7.weight, extra.7.bias, l2_norm.weight

2020-07-28 19:49:01,320 - mmdet - INFO - Start running, host: zhaotongdong@zhaotongdong-MS-7B89, work_dir: /home/zhaotongdong/goole_download/mmdetection/work_dirs/ssd300_coco
2020-07-28 19:49:01,320 - mmdet - INFO - workflow: [('train', 1)], max: 50 epochs
2020-07-28 19:49:25,800 - mmdet - INFO - Epoch [1][50/154]	lr: 1.978e-04, eta: 1:01:56, time: 0.486, data_time: 0.064, memory: 2384, loss_cls: 19.4103, loss_bbox: 3.0249, loss: 22.4351
2020-07-28 19:49:43,161 - mmdet - INFO - Epoch [1][100/154]	lr: 3.976e-04, eta: 0:52:45, time: 0.347, data_time: 0.009, memory: 2384, loss_cls: 10.3150, loss_bbox: 2.9190, loss: 13.2340
2020-07-28 19:50:00,487 - mmdet - INFO - Epoch [1][150/154]	lr: 5.974e-04, eta: 0:49:28, time: 0.346, data_time: 0.010, memory: 2384, loss_cls: 4.7862, loss_bbox: 2.8319, loss: 7.6180
2020-07-28 19:50:01,694 - mmdet - INFO - Saving checkpoint at 1 epochs
2020-07-28 19:50:03,660 - mmdet - INFO - Evaluating bbox...
2020-07-28 19:50:04,168 - mmdet - INFO - Epoch [1][154/154]	lr: 6.134e-04, bbox_mAP: 0.0020, bbox_mAP_50: 0.0100, bbox_mAP_75: 0.0000, bbox_mAP_s: 0.0880, bbox_mAP_m: -1.0000, bbox_mAP_l: -1.0000, bbox_mAP_copypaste: 0.002 0.010 0.000 0.088 -1.000 -1.000
2020-07-28 19:50:25,514 - mmdet - INFO - Epoch [2][50/154]	lr: 8.132e-04, eta: 0:49:04, time: 0.423, data_time: 0.066, memory: 2384, loss_cls: 3.9779, loss_bbox: 2.6387, loss: 6.6166
2020-07-28 19:50:43,396 - mmdet - INFO - Epoch [2][100/154]	lr: 1.013e-03, eta: 0:47:53, time: 0.357, data_time: 0.010, memory: 2384, loss_cls: 3.9955, loss_bbox: 2.7201, loss: 6.7156
2020-07-28 19:51:01,394 - mmdet - INFO - Epoch [2][150/154]	lr: 1.213e-03, eta: 0:47:02, time: 0.360, data_time: 0.010, memory: 2384, loss_cls: 3.7918, loss_bbox: 2.4860, loss: 6.2778
2020-07-28 19:51:02,612 - mmdet - INFO - Saving checkpoint at 2 epochs
2020-07-28 19:51:04,134 - mmdet - INFO - Evaluating bbox...
2020-07-28 19:51:04,678 - mmdet - INFO - Epoch [2][154/154]	lr: 1.229e-03, bbox_mAP: 0.0330, bbox_mAP_50: 0.1270, bbox_mAP_75: 0.0050, bbox_mAP_s: 0.2720, bbox_mAP_m: -1.0000, bbox_mAP_l: -1.0000, bbox_mAP_copypaste: 0.033 0.127 0.005 0.272 -1.000 -1.000
2020-07-28 19:51:25,046 - mmdet - INFO - Epoch [3][50/154]	lr: 1.429e-03, eta: 0:46:33, time: 0.404, data_time: 0.059, memory: 2384, loss_cls: 3.7906, loss_bbox: 2.5624, loss: 6.3531
2020-07-28 19:51:42,709 - mmdet - INFO - Epoch [3][100/154]	lr: 1.628e-03, eta: 0:45:49, time: 0.353, data_time: 0.009, memory: 2384, loss_cls: 3.5147, loss_bbox: 2.3628, loss: 5.8775
2020-07-28 19:52:00,625 - mmdet - INFO - Epoch [3][150/154]	lr: 1.828e-03, eta: 0:45:16, time: 0.358, data_time: 0.010, memory: 2384, loss_cls: 3.2510, loss_bbox: 2.2587, loss: 5.5097
2020-07-28 19:52:01,930 - mmdet - INFO - Saving checkpoint at 3 epochs
2020-07-28 19:52:03,445 - mmdet - INFO - Evaluating bbox...
2020-07-28 19:52:03,961 - mmdet - INFO - Epoch [3][154/154]	lr: 1.844e-03, bbox_mAP: 0.0810, bbox_mAP_50: 0.3110, bbox_mAP_75: 0.0160, bbox_mAP_s: 0.2740, bbox_mAP_m: -1.0000, bbox_mAP_l: -1.0000, bbox_mAP_copypaste: 0.081 0.311 0.016 0.274 -1.000 -1.000
2020-07-28 19:52:24,388 - mmdet - INFO - Epoch [4][50/154]	lr: 2.000e-03, eta: 0:44:55, time: 0.405, data_time: 0.062, memory: 2384, loss_cls: 3.2941, loss_bbox: 2.3337, loss: 5.6278
2020-07-28 19:52:41,837 - mmdet - INFO - Epoch [4][100/154]	lr: 2.000e-03, eta: 0:44:20, time: 0.349, data_time: 0.010, memory: 2384, loss_cls: 3.0518, loss_bbox: 2.1137, loss: 5.1655
2020-07-28 19:52:59,311 - mmdet - INFO - Epoch [4][150/154]	lr: 2.000e-03, eta: 0:43:48, time: 0.349, data_time: 0.010, memory: 2384, loss_cls: 2.9942, loss_bbox: 1.9992, loss: 4.9934
2020-07-28 19:53:00,578 - mmdet - INFO - Saving checkpoint at 4 epochs
2020-07-28 19:53:02,236 - mmdet - INFO - Evaluating bbox...
2020-07-28 19:53:02,749 - mmdet - INFO - Epoch [4][154/154]	lr: 2.000e-03, bbox_mAP: 0.0720, bbox_mAP_50: 0.3000, bbox_mAP_75: 0.0090, bbox_mAP_s: 0.2910, bbox_mAP_m: -1.0000, bbox_mAP_l: -1.0000, bbox_mAP_copypaste: 0.072 0.300 0.009 0.291 -1.000 -1.000
2020-07-28 19:53:23,404 - mmdet - INFO - Epoch [5][50/154]	lr: 2.000e-03, eta: 0:43:32, time: 0.409, data_time: 0.059, memory: 2384, loss_cls: 2.8654, loss_bbox: 2.0248, loss: 4.8902
2020-07-28 19:53:41,186 - mmdet - INFO - Epoch [5][100/154]	lr: 2.000e-03, eta: 0:43:06, time: 0.356, data_time: 0.010, memory: 2384, loss_cls: 2.8412, loss_bbox: 1.8640, loss: 4.7052
2020-07-28 19:53:58,881 - mmdet - INFO - Epoch [5][150/154]	lr: 2.000e-03, eta: 0:42:40, time: 0.354, data_time: 0.010, memory: 2384, loss_cls: 2.6943, loss_bbox: 1.9460, loss: 4.6403
2020-07-28 19:54:00,167 - mmdet - INFO - Saving checkpoint at 5 epochs
2020-07-28 19:54:01,737 - mmdet - INFO - Evaluating bbox...
2020-07-28 19:54:02,258 - mmdet - INFO - Epoch [5][154/154]	lr: 2.000e-03, bbox_mAP: 0.1650, bbox_mAP_50: 0.4970, bbox_mAP_75: 0.0660, bbox_mAP_s: 0.3650, bbox_mAP_m: -1.0000, bbox_mAP_l: -1.0000, bbox_mAP_copypaste: 0.165 0.497 0.066 0.365 -1.000 -1.000
2020-07-28 19:54:22,976 - mmdet - INFO - Epoch [6][50/154]	lr: 2.000e-03, eta: 0:42:25, time: 0.410, data_time: 0.063, memory: 2384, loss_cls: 2.6351, loss_bbox: 1.6389, loss: 4.2739
2020-07-28 19:54:40,725 - mmdet - INFO - Epoch [6][100/154]	lr: 2.000e-03, eta: 0:42:01, time: 0.355, data_time: 0.010, memory: 2384, loss_cls: 2.4775, loss_bbox: 1.6010, loss: 4.0786
2020-07-28 19:54:58,414 - mmdet - INFO - Epoch [6][150/154]	lr: 2.000e-03, eta: 0:41:37, time: 0.354, data_time: 0.010, memory: 2384, loss_cls: 2.6442, loss_bbox: 1.6475, loss: 4.2917

**Comment by baibaidedongdong** [comment]
@sunnyisabaster 大概就这样，没有acc这个结果

**Comment by sunnyisabaster** [comment]
加个checkpoint文件试试。在你的config文件中添加。

**Comment by sunnyisabaster** [comment]
> @sunnyisabaster 大概就这样，没有acc这个结果

我刚刚看了看，到节点的时候好像会给一个mAP，其实你用这个做标准其实也可以。
像下面这样：
![image](https://user-images.githubusercontent.com/20209604/89127620-c754a000-d4e6-11ea-8d63-45280633271a.png)

**Comment by yhcao6** [comment]
https://github.com/open-mmlab/mmdetection/blob/11b1ef830aa7c8c054d8b5346fe0966e643d473c/mmdet/models/dense_heads/ssd_head.py#L255-L266

You can computer accuracy there and add it into the loss dictionary like follows,
```
return dict(loss_cls=losses_cls, loss_bbox=losses_bbox, accu=your_computed_accuracy)
```

**Comment by baibaidedongdong** [comment]
ok,thank you



---Original---
