### ISSUE TITLE
How can I see the fps when I  use a model to test pictures?

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmdetection#3409]

**Comment by baibaidedongdong** [comment]
Does it need to write by myself?

**Comment by ZwwWayne** [comment]
Use [benchmark.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/benchmark.py).

**Comment by WangTianYuan** [comment]
@ZwwWayne Hello, I have a problem when I run the benchmark.py, I first test the fps of faster RCNN model, I get 21.9 img/s, then I add some conv layers for the fpn module and train it, for this time, I still get 21.9 img/s, I am pretty sure that I add some conv layers, so why the fps is still the same?

**Comment by WangTianYuan** [comment]
@ZwwWayne I look through the log and I find that the benchmark failed to load these conv_layers that I've added, but the load code is the same as it in test.py. I am confused, can you help me?
