### ISSUE TITLE
Cascade R-CNN with OHEM

### ISSUE THREAD

**Issue by ZengyuanYu** [open-mmlab/mmdetection#341]
@hellock  Thanks your work! I use mmdetection for my finally thesis. Now I meet some question:
- 1. I want to compare OHEM and Random use Cascade R-CNN, But got error. I don't debug it, So will you give me some advice?
**my config**
# model settings
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained='modelzoo://resnet101',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        use_sigmoid_cls=True),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=[
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.1, 0.1, 0.2, 0.2],
            reg_class_agnostic=True),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.05, 0.05, 0.1, 0.1],
            reg_class_agnostic=True),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.033, 0.033, 0.067, 0.067],
            reg_class_agnostic=True)
    ])
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        smoothl1_beta=1 / 9.0,
        debug=False),
    rcnn=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                ignore_iof_thr=-1),
            sampler=dict(
                type='OHEMSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                ignore_iof_thr=-1),
            sampler=dict(
                type='OHEMSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.7,
                min_pos_iou=0.7,
                ignore_iof_thr=-1),
            sampler=dict(
                type='OHEMSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)
    ],
    stage_loss_weights=[1, 0.5, 0.25])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100),
    keep_all_stages=False)
# dataset settings
dataset_type = 'CocoDataset'
data_root = '/home/yu/mmdetection/data/coco-wheat/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/trainval.json',
        img_prefix=data_root + 'trainval',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/val.json',
        img_prefix=data_root + 'val/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/test.json',
        img_prefix=data_root + 'test/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=10)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 200
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/cascade_rcnn_r101_fpn_1x'
load_from = None
resume_from = None
workflow = [('train', 1)]

**error msg**
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
2019-02-24 20:31:17,671 - INFO - Start running, host: yu@xc-pc, work_dir: /home/yu/mmdetection/data/result/cascade_rcnn_r101_OHEM_wheat
2019-02-24 20:31:17,671 - INFO - workflow: [('train', 1)], max: 200 epochs
Traceback (most recent call last):
  File "tools/train.py", line 90, in <module>
    main()
  File "tools/train.py", line 86, in main
    logger=logger)
  File "/home/yu/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/yu/mmdetection/mmdet/apis/train.py", line 121, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/yu/.virtualenvs/mmdetetion/lib/python3.6/site-packages/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yu/.virtualenvs/mmdetetion/lib/python3.6/site-packages/mmcv/runner/runner.py", line 255, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/yu/mmdetection/mmdet/apis/train.py", line 37, in batch_processor
    losses = model(**data)
  File "/home/yu/.virtualenvs/mmdetetion/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yu/.virtualenvs/mmdetetion/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yu/.virtualenvs/mmdetetion/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yu/mmdetection/mmdet/models/detectors/base.py", line 80, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/yu/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 141, in forward_train
    cfg=rcnn_train_cfg)
  File "/home/yu/mmdetection/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/yu/mmdetection/mmdet/core/bbox/assign_sampling.py", line 30, in assign_and_sample
    bbox_sampler = build_sampler(cfg.sampler)
  File "/home/yu/mmdetection/mmdet/core/bbox/assign_sampling.py", line 22, in build_sampler
    cfg, samplers, default_args=kwargs)
  File "/home/yu/.virtualenvs/mmdetetion/lib/python3.6/site-packages/mmcv/runner/utils.py", line 72, in obj_from_dict
    return obj_type(**args)
TypeError: __init__() missing 1 required positional argument: 'context'

**Comment by ZengyuanYu** [comment]
I use Faster R-CNN with OHEM is OK.

**Comment by hellock** [comment]
We have not tried OHEM in Cascade R-CNN and it is currently not supported. You can refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/cascade_rcnn.py#L137-L143) and [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/two_stage.py#L107-L122) if you want to add OHEM in Cascade R-CNN.

**Comment by ZengyuanYu** [comment]
> We have not tried OHEM in Cascade R-CNN and it is currently not supported. You can refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/cascade_rcnn.py#L137-L143) and [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/two_stage.py#L107-L122) if you want to add OHEM in Cascade R-CNN.

OK, I will do it for refer code.Thank you!

**Comment by 1224wxwx** [comment]
> I use Faster R-CNN with OHEM is OK.

Could you please tell me whether OHEM helped you?
After I used OHEM, it became very difficult for loss to decrease(both on train dataset and test dataset) and the result was worse than before.

**Comment by zvadaszi** [comment]
Did OHEM helped with Cascade R-CNN?
