### ISSUE TITLE
When Training with Multi GPU, assertion 'GDK_IS_DISPLAY (display)' failed

### ISSUE THREAD

**Issue by ZenFSheng** [open-mmlab/mmdetection#3415]
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(train.py:20197): Gdk-CRITICAL **: 03:47:39.745: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(train.py:20198): Gdk-CRITICAL **: 03:47:39.800: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(train.py:20594): Gdk-CRITICAL **: 03:47:53.229: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3374/3373, 18.9 task/s, elapsed: 178s, ETA:     0s
```

when I run the multi gpu training, I got many message just as above. It seems that training got some error and has been passed, then suddenly do evaluation...  I cannot find out where is the problem. Can you guys tell me why? 

I just run command
`./tools/dist_train.sh configs/reppoints/reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck+head_2x_coco.py 2
`
 I just modified config of dataset, and I use my own dataset, its format is just same as coco.

My Environment:
Python 3.6.9
pytorch 1.5
torch vision 0.6.0
CUDA 10.0

**Comment by yhcao6** [comment]
I guess you are using matplotlib but there is no available display GUI in your server. Can you check again if you call matplotlib to show something during the evaluation?
