### ISSUE TITLE
How to use Mask R-CNN  to calculate Mask areas?

### ISSUE THREAD

**Issue by jonguo111** [open-mmlab/mmdetection#3418]
i am trying to use Mask R-CNN to calculate defects' mask area. which code can be used for the calculation? Thank you very much!

**Comment by yhcao6** [comment]
Do you mean how to compute the area of a mask? For example if the mask is in bitmap format, then the area equals to its sum.
https://github.com/open-mmlab/mmdetection/blob/ae453fa92ffebcbd224b72f6d48e0b8699424450/mmdet/core/mask/structures.py#L301-L303
