### ISSUE TITLE
NMS on each fpn level or not?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmdetection#3421]
Hi,

I found out in early version of rpn head did nms at each level (https://github.com/hasanirtiza/Pedestron/blob/master/mmdet/models/anchor_heads/rpn_head.py#L92).

But in the current version of rpn head use nms across all the levels (https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/rpn_head.py#L167).

I tried to train the same network config on both versions of rpn head, and found out early version has much better  accuracy.

Any reason why you use nms across all the levels?

**Comment by hellock** [comment]
NMS is performs at each level in the new version. You may refer to the implementation of `batch_nms`.
