### ISSUE TITLE
How do I debug coco.py in linux platform?

### ISSUE THREAD

**Issue by sunnyisabaster** [open-mmlab/mmdetection#3422]
Maybe my question is stupid, but I really need ur help.

When I trained a model, there was an error: List index out of range occurred in the 
File "/mmdetection/mmdet/datasets/coco.py", line 230, in _det2json 
data['category_id'] = self.cat_ids[label]

So, I tried to add some prints in the coco.py, even delete 'data['category_id'] = self.cat_ids[label]', but it still says  List index out of range in the 
File "/mmdetection/mmdet/datasets/coco.py", line 230, in _det2json 
data['category_id'] = self.cat_ids[label]

So, do you have any ideas to solve it?

**Comment by sunnyisabaster** [comment]
If not, how do I check the param of _det2json in coco.py?

    def _det2json(self, results):
        """Convert detection results to COCO json style."""
        json_results = []
        for idx in range(len(self)):
            img_id = self.img_ids[idx]
            result = results[idx]
            for label in range(len(result)):
                bboxes = result[label]
                for i in range(bboxes.shape[0]):
                    data = dict()
                    data['image_id'] = img_id
                    data['bbox'] = self.xyxy2xywh(bboxes[i])
                    data['score'] = float(bboxes[i][4])
                    data['category_id'] = self.cat_ids[label]
                    json_results.append(data)
        return json_results

**Comment by sunnyisabaster** [comment]
I think I can just debug the train file now (tools/train.py).

**Comment by sky-fly97** [comment]
> 我想我现在可以调试列车文件(Tools/Tra.py)了。

Hello, I meet the problem too! Can you tell me how to solve it?  Thanks!
