### ISSUE TITLE
subprocess.CalledProcessError: Command '['................--launcher', 'pytorch']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by hongrui16** [open-mmlab/mmdetection#3423]
I got the error and I found it was due to the master port used repeatedly.
remember to modify the master port number in dist_train.sh every time, especially when there exists a training job runing.

**Comment by henbucuoshanghai** [comment]
how to change it?

**Comment by hongrui16** [comment]
> how to change it?

--master_port=xxx
renew the port num and avoid repeating the one used by the running thread
