### ISSUE TITLE
Train on cpu

### ISSUE THREAD

**Issue by saicomagic** [open-mmlab/mmdetection#3425]
Does mmdetection support train models on CPU (my computer does not have GPU and cuda)? How shouild I config if it support, thx a lot!!!

**Comment by sunnyisabaster** [comment]
I think this is what you want:

https://mmdetection.readthedocs.io/en/latest/install.html#install-with-cpu-only

**Comment by hellock** [comment]
Training with CPU is currently not supported. Inference with CPU is okay.

**Comment by rusmux** [comment]
Are there any updates on this? When I try to do training on the CPU, I get the error `batch_size should be a positive integeral value, but got batch_size=0`. Is it still not supported?
