### ISSUE TITLE
pytorch2onnx

### ISSUE THREAD

**Issue by manhongnie** [open-mmlab/mmdetection#3427]
@drcut 
I successfully converted to onnx and used pytorch 1.5 and 1.3, but I combed through the results and found that it was incorrect. For example, at the node ReduceMax, I found that its input was [0, 4], which may be an error in the Gather node Later, I checked the model and onnx to compare their input and output, and found that it was completely wrong. I don't know why you used onnxruntime to test successfully and the result is correct.

**Comment by manhongnie** [comment]
@drcut
Can I add you to WeChat? There are too many problems with this onnx

**Comment by manhongnie** [comment]
@xvjiarui 
卷积后面接了个Gather，这明显是不对的，我看了这个节点效果只是一个去维度的操作，使用Gather得到了错误的结果．

**Comment by manhongnie** [comment]
give up

**Comment by INNOCENT-BOY** [comment]
I also meet the same problems, have you find the solution? @manhongnie
