### ISSUE TITLE
ATSS assigner error when training in small image size:

### ISSUE THREAD

**Issue by chuong98** [open-mmlab/mmdetection#3428]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I change the image size to smaller size (320,320) for mobile application:
```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(320, 320), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
```
3. What dataset did you use?
coco
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

For small size, some time the image does not have enough positive sample at high stage. Thus. topk=9 sometime fails. 
In your code, line 122,123 of file: `mmdet/core/bbox/assigners/atss_assigner.py`, replace:
```python
_, topk_idxs_per_level = distances_per_level.topk(
                self.topk, dim=0, largest=False)
``` 
to
```python
_, topk_idxs_per_level = distances_per_level.topk(
    min(self.topk, distances_per_level.shape[0]), dim=0, largest=False)
```
It will pass the error.

**Comment by shinya7y** [comment]
This issue should have been fixed in the latest version. https://github.com/open-mmlab/mmdetection/pull/3361
