### ISSUE TITLE
Will support BorderDet？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#3430]
**The original single-point feature can be directly optimized by using the border features, and the SOTA target detection algorithm BorderDet is proposed based on BorderAlign**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. Many sliding-window object detectors(such as FCOS,SSD,RetinaNet) adopte the feature maps on the point of the grid to generate the bounding box predictions, but lack the explicit border information for accurate localization.
Ex2.If those detectors use the border information, the performance of the detector will be improved.
Ex3. There is a recent paper《BorderDet: Border Feature for Dense Object Detection》.This paper gives a detailed explanation of the method of using border information to improve the performance of FCOS(mAP: 38.6 v.s. 41.4) and has achieved good results.

**Related resources**
official code：https://github.com/Megvii-BaseDetection/BorderDet

**Comment by hellock** [comment]
You may request new features in #2931.
