### ISSUE TITLE
How to generate the results for VOC data without annotations

### ISSUE THREAD

**Issue by FreedoomG** [open-mmlab/mmdetection#3432]
Hi there,
I want to get the test results to submit( the real test but not the val), and there are no XML annotation documents for the test.
However, in mmdet, there must exist these file which I think is useless.
Can you fix it by ignoring the annotation loading when we choose '--format-only'?
And are there any ways to fulfil the requirement by mmdet except creating XML files the same number as the test images?
THX!

**Comment by NicholasIrving** [comment]
Is there any solutions?

**Comment by cqwly** [comment]
Just to generate some fake annotations, it works for me
import os
import shutil

img_path = '0/' # path saves images to be tested
img_list = os.listdir(img_path)
file_len = len(img_list)
for i in range(file_len):
    dst_name = 'xml/' + img_list[:-4] + 'xml'
    shutil.copyfile('1.xml', dst_name)  # 1.xml is the annotation of a training sample/picture

**Comment by FreedoomG** [comment]
> Just to generate some fake annotations, it works for me
> import os
> import shutil
> 
> img_path = '0/' # path saves images to be tested
> img_list = os.listdir(img_path)
> file_len = len(img_list)
> for i in range(file_len):
> dst_name = 'xml/' + img_list[i][:-4] + 'xml'
> shutil.copyfile('1.xml', dst_name) # 1.xml is the annotation of a training sample/picture

**Comment by FreedoomG** [comment]
the upper shows a great template to generate the annotation, but I think the official group should do something to deal with this kind question which is my purpose to put this issue.
