### ISSUE TITLE
How to save the prediction labels (class name, bounding box information) during test/model inference?

### ISSUE THREAD

**Issue by Sudhakar17** [open-mmlab/mmdetection#3433]
For Pseudo-labeling purpose,  We load the images from the folder and predictions will be saved inside the folder in XML/txt/Json file (label format like VOC/YOLO). It reduces the time to annotate the images.

**Comment by ZwwWayne** [comment]
Please see the example 6,7 in the [documentation](https://mmdetection.readthedocs.io/en/latest/getting_started.html#test-a-dataset).

**Comment by Sudhakar17** [comment]
@ZwwWayne @hellock : I don't have annotation files for the images(like a test set). Do I need the annotations to run the test script? Because, config file -> data file -> train_dict, val_dict, test_dict is used in the code.
