### ISSUE TITLE
Is there any way to evaluate mAP with COCO style dataset on non-distributed gpu options?

### ISSUE THREAD

**Issue by kye9216789** [open-mmlab/mmdetection#345]
Hi.
I always thanks for your help.

I have only single gpu machine, and I want to evaluate mAP with my own (coco style) dataset.

I searched your code, but I could not find  the way I want.

Is evaluating mAP supported on distributed gpu?

**Comment by hellock** [comment]
Evaluation during training currently only supports distributed training, if you are interested in doing so for non-distributed training, you need to write an [evaluation hook](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py).

If you mean the evaluation after training, then just use the test script.

**Comment by kye9216789** [comment]
I owe you.
Thank you very much.
