### ISSUE TITLE
No result when I run the demo

### ISSUE THREAD

**Issue by freehome1** [open-mmlab/mmdetection#3450]
I have download the faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth and run the demo.py like this: 
python demo/image_demo.py demo/demo.jpg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  
and return a image without any bboxes on it. 
Then I try another pth: faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth and meet the same problem.

**Comment by freehome1** [comment]
The result in the inference.py is array[]

**Comment by freehome1** [comment]
The result[0] in the inference.py is {ndarray:(0,5)}

**Comment by freehome1** [comment]
the result[0] in the inference.py is {ndarray:(0, 5)} []

**Comment by ZwwWayne** [comment]
Hi @freehome1 ,
I just tried your command, with the same checkpoint and the same config, I got the expected image with box results on it.
Do you modify anything in the code? Or could you use the newest mmdet and try again?

**Comment by ZwwWayne** [comment]
Since the newest code does not have this problem. This issue is closed. Feel free to reopen it if you have any further questions.
