### ISSUE TITLE
关于 x1,y1,x2,y2,x3,y3,x4,y4,annotation 格式

### ISSUE THREAD

**Issue by Decalogue** [open-mmlab/mmdetection#3452]
您好！
请问支持 x1,y1,x2,y2,x3,y3,x4,y4,annotation 这种任意四边形的格式吗？比如检测斜的文本行
如果不支持那么怎样修改比较好呢？
多谢了！

**Comment by ZwwWayne** [comment]
MMDet does not support this. To support this, you need to enable the data pipeline, data loader, and bbox head to support this annotation.
