### ISSUE TITLE
question on caffe pretrained model

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3455]
Hi, there,

I saw on your GN config template (https://github.com/open-mmlab/mmdetection/blob/eb66e0d01ecded59160ab8d5c0e8e302eb1836a1/configs/gn/mask_rcnn_r50_fpn_gn-all_2x_coco.py#L4) that you are using Caffe pre-trained backbone (open-mmlab://detectron/resnet50_gn). However, you are not freezing the GN on the backbone as I highlighted on the code below. Also, the style on the backbone is not changed from pytorch to caffe. Could you help to confirm this?

Thanks!

_base_ = '../mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
**norm_cfg = dict(type='GN', num_groups=32, requires_grad=True)**
model = dict(
    pretrained='open-mmlab://detectron/resnet50_gn',
    **backbone=dict(norm_cfg=norm_cfg),**
    neck=dict(norm_cfg=norm_cfg),
    roi_head=dict(
        bbox_head=dict(
            type='Shared4Conv1FCBBoxHead',
            conv_out_channels=256,
            norm_cfg=norm_cfg),
        mask_head=dict(norm_cfg=norm_cfg)))
img_norm_cfg = dict(
    mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)

**Comment by ZwwWayne** [comment]
`open-mmlab://detectron/resnet50_gn` does not mean the backbone is in caffe style. GN is not freezed since it does not running_mean and running_var like BN.

**Comment by shanggdlk** [comment]
> `open-mmlab://detectron/resnet50_gn` does not mean the backbone is in caffe style. GN is not freezed since it does not running_mean and running_var like BN.

Thank you for the reply. But I saw it uses **img_norm_cfg = dict(
mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)** which is applied when switching to caffe-based pretrained models (if I understand correctly). So is this pretrained model based on pytorch or caffe? 

Thanks!

**Comment by ZwwWayne** [comment]
The `img_norm_cfg` has nothing to do with the backbone type. It only depends on how the model is pre-trained. It should be the same as the `img_norm` used to train the model in ImageNet. The backbone style is pytorch means the downsample is performed by the 3x3 conv in each stage, caffe-style means the downsample is performed by the 1x1 conv.

**Comment by shanggdlk** [comment]
> The `img_norm_cfg` has nothing to do with the backbone type. It only depends on how the model is pre-trained. It should be the same as the `img_norm` used to train the model in ImageNet. The backbone style is pytorch means the downsample is performed by the 3x3 conv in each stage, Caffe-style means the downsample is performed by the 1x1 conv.

Great! Thanks for the explanation. I got confused when I read the previous issues posted in the channel, where the user is asked to change std/mean to [103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0] when switching to use Caffe pretrained backbone. (https://github.com/open-mmlab/mmdetection/issues/23). So I thought using [103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0] means you are using Caffe pretrained backbone. 

Never mind, thanks for the explanation. It is no crystal clear to me.
