### ISSUE TITLE
How to install the previous verision of mmdet just list mmdet1.0+

### ISSUE THREAD

**Issue by aakunkun** [open-mmlab/mmdetection#3459]
Thanks for your answer

**Comment by aakunkun** [comment]
the verision of mine is "short_version = '1.0.rc0" ，I have did some experiments in this envirment. But the computer is broken, I have  to continue my experiments in the same envirment. So, is there any way I can install the previous verision?  Thanks for your answer

**Comment by ZwwWayne** [comment]
You can use the 1.x version by git commands, e.g., `git checkout v1.0.0`.
