### ISSUE TITLE
Frozen BN

### ISSUE THREAD

**Issue by AresGao** [open-mmlab/mmdetection#346]
Training with your config, you use ```norm_eval=True``` to freeze bn, why not setting```normalize=dict(type='BN', frozen=True)```? Is there any difference？

**Comment by thangvubk** [comment]
``frozen``: stop gradient update in norm layers
``norm_eval``: stop moving average statistics update in norm layers

**Comment by blateyang** [comment]
Why need to stop moving average statistics update in norm layers when training model? As far as I know，BN layers usually need to record moving average statistics which is to be used when testing model.
