### ISSUE TITLE
While training the  Fashion Segmentation model, is there  a way to train only bbox detection and turn off segmentation

### ISSUE THREAD

**Issue by kartikwar** [open-mmlab/mmdetection#3462]
Hi I have a fashion dataset that I want to train. The issue is I have only bbox coordinates with me. I dont want to train segmentation . I am using the configuration deepfashion/mask_rcnn_r50_fpn_15e_deepfashion.py. I am able to train by providing random segmentation points. But the issue is this would impact loss and hence the model (since model is also taking loss for segmentation predictions) so this would affect my detection results as well for the trained model. Is there any way in ehich I can turn off the segmentation mask pipeline in this model. Also if not are there any other alternatives to achieve this ?

Thanks

**Comment by ZwwWayne** [comment]
You could try Faster RCNN by deleting the mask head in the config. An example of faster rcnn is [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/faster_rcnn_r50_fpn.py)

**Comment by kartikwar** [comment]
I tried using the faster_rcnn_r50_fpn.py model in my configuration. I got the error **KeyError: 'the cfg dict must contain the key "type", but got {\'num_classes\': 15}'**
and when I tried editing the configuration of mask_rcnn_r50_fpn_15e_deepfashion.py (making it same as the example you shared). I got the same error again. This is while training the deep fashion dataset (In-Shop) dataset. It does have the segmentation coordinates. I just dont want to use them . Any help on this error would be appreciated. Thanks :-)

**Comment by kvboe** [comment]
> You could try Faster RCNN by deleting the mask head in the config. An example of faster rcnn is [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/faster_rcnn_r50_fpn.py)

How i can delete mask in faster_rcnn?

**Comment by kvboe** [comment]
> You could try Faster RCNN by deleting the mask head in the config. An example of faster rcnn is [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/faster_rcnn_r50_fpn.py)

How i can delete mask head in this config? I don't see anything...

**Comment by ZwwWayne** [comment]
```python
_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py',
    '../_base_/datasets/deepfashion.py', '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py'
]
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=15)))
# runtime settings
total_epochs = 15


```

**Comment by ZwwWayne** [comment]
The above codes should work as a Faster RCNN detector. The [documentation of the config system](https://mmdetection.readthedocs.io/en/latest/config.html) might do help to you.
