### ISSUE TITLE
Why the learn rate does not match during the training period? 

### ISSUE THREAD

**Issue by sunnyisabaster** [open-mmlab/mmdetection#3464]
Fist of all, thanks for your help!

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

**Describe the issue**

A clear and concise description of what the problem you meet and what have you done.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py ./configs/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_20e_coco.py
```
2. What config dir you run?
# you can see here the learn rate is 0.00125
```
optimizer = dict(type='SGD', lr=0.00125, momentum=0.9, weight_decay=0.0001) 
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[16, 19])
total_epochs = 20
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = 'checkpoints/cascade_rcnn_x101_64x4d_fpn_20e_coco_20200509_224357-051557b1.pth'
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/cascade_rcnn_x101_64x4d_fpn_20e_coco'
gpu_ids = range(0, 1)
```
3. Did you make any modifications on the code or config? Did you understand what you have modified?
4. What dataset did you use?
```
something like that :
'images': [
    {
        'file_name': 'COCO_val2014_000000001268.jpg',
        'height': 427,
        'width': 640,
        'id': 1268
    },
    ...
],

'annotations': [
    {
        'segmentation': [[192.81,
            247.09,
            ...
            219.03,
            249.06]],  # if you have mask labels
        'area': 1035.749,
        'iscrowd': 0,
        'image_id': 1268,
        'bbox': [192.81, 224.8, 74.73, 33.43],
        'category_id': 16,
        'id': 42986
    },{
        'segmentation': [[88,
            33.09,
            ...
            444.03,
            555.06]],  # if you have mask labels
        'area': 1035.749,
        'iscrowd': 0,
        'image_id': 1268,
        'bbox': [192.81, 224.8, 74.73, 33.43],
        'category_id': 0,
        'id': 42986
    }
    ...
],

'categories': [
    {'id': 0, 'name': 'fish'},
 ]
 ```

**Environment**

the environment is fine.

**Results**
before 500:
![image](https://user-images.githubusercontent.com/20209604/89122775-16d4a500-d4c2-11ea-9c95-2c7b53da17e1.png)
after 500, it's keeping lr: 1.250e-03:
![image](https://user-images.githubusercontent.com/20209604/89122783-2bb13880-d4c2-11ea-8859-c18748dcfe7f.png)

So, why it happened? 
what should I do for this problem?  My evaluation result is not good, so I suppose the learn rate is not correct.
![image](https://user-images.githubusercontent.com/20209604/89122824-70d56a80-d4c2-11ea-9bad-d523228206c4.png)

**Issue fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Because the config uses warmup and the number of warmup iterations is 500. You can see that after 500 iters the LR is 1.250e-3

**Comment by sunnyisabaster** [comment]
> Because the config uses warmup and the number of warmup iterations is 500. You can see that after 500 iters the LR is 1.250e-3

Thanks for your reply. So, do u think the learn rate is the cause of the low ap result?

**Comment by ZwwWayne** [comment]
0.00125 = 1.250e-3. If the model is trained using single GPU, the LR should be fine. The low AP might be caused by other issues, I do not know.

**Comment by sunnyisabaster** [comment]
> 0.00125 = 1.250e-3. If the model is trained using single GPU, the LR should be fine. The low AP might be caused by other issues, I do not know.

Ok, thanks man! it was a stupid Qs...
