### ISSUE TITLE
UserWarning: This overload of nonzero is deprecated

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3467]
I've been getting the UserWarning message below which I have not seen before today and I was wondering if it may have any impact on the performance, as I'm finding it difficult to replicate my own previous results and just wanted to quickly check if this may have something to do with it. Thanks

```
mmdetection/mmdet/core/post_processing/bbox_nms.py:44: UserWarning: This overload of nonzero is deprecated
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  labels = valid_mask.nonzero()[:, 1]
```

**Comment by ZwwWayne** [comment]
Hi @sehyungp92 ,
Thanks for your report, what is the version of PyTorch in your environment?

**Comment by sehyungp92** [comment]
@ZwwWayne, thanks for your response. 

PyTorch: 1.6.0+cu101
TorchVision: 0.7.0+cu101

**Comment by sleep3r** [comment]
@sehyungp92
Just downgrade PyTorch to 1.5.0 and rebuild all dependencies. It helped me.

**Comment by hellock** [comment]
The latest version supports PyTorch 1.6 now.

**Comment by shinya7y** [comment]
Probably `Tensor.nonzero()` can be fixed to `Tensor.nonzero(as_tuple=False)` safely.
`labels = valid_mask.nonzero(as_tuple=False)[:, 1]`

Most `torch.nonzero` calls have already been fixed in May. https://github.com/open-mmlab/mmdetection/pull/2602
But newer files and `Tensor.nonzero` have not been fixed.
