### ISSUE TITLE
FP16 training with Apex ?

### ISSUE THREAD

**Issue by LightToYang** [open-mmlab/mmdetection#347]
I want to train model with FP16 by Apex, but it's hard to change the code, may someone give me some suggestions?

**Comment by hellock** [comment]
We will release fp16 training (no apex dependency) and not too much code is needed.

**Comment by runzeer** [comment]
So when will you release the fp16 trainning ?

**Comment by runzeer** [comment]
If necessary,could you tell me when the fp16 training will be released?

**Comment by hellock** [comment]
This is an outdated issue and mixed precision has been supported.
