### ISSUE TITLE
How to submit test-dev rusults to coco？

### ISSUE THREAD

**Issue by XieXing018** [open-mmlab/mmdetection#3471]
I have tested my method on test-dev2017 and generated the results.json. But I can not find test-dev2017 server in CodaLab. I only find test-dev 2019(bbox).  Did you use test-dev2019(bbox) replace test-dev2017 to test?
![image](https://user-images.githubusercontent.com/18532996/89143658-ec482200-d57d-11ea-92c3-b7de6b0fdd61.png)
@hellock

**Comment by xuanthuyvo** [comment]
Right!

**Comment by XieXing018** [comment]
> Right!

I signed up the codalab and registed two competition, yesterday, as shown in foloowing Figures. I sumbmited my results on participate page. But no response and not apperaing any errors after submiting my results.  Have you been in this situation recently?
![image](https://user-images.githubusercontent.com/18532996/89151686-14db1680-d594-11ea-8991-3a7d3827c03f.png)

**Comment by hellock** [comment]
This is not an issue related to mmdetection. You may seek help from the coco challenge organizers.
