### ISSUE TITLE
How to get polygon vertices of all mask segmentation?

### ISSUE THREAD

**Issue by TuanNguyenSKKU** [open-mmlab/mmdetection#3472]
Hi everyone,
I really want to get polygon vertices of all mask segmentation in the image after inference. So how can I modify to get this parameter?

I hope to receive your supports. Thank you so much.

**Comment by xuanthuyvo** [comment]
I think you can convert mask prediction to contour (using cv2.findContours function). After that, you can get the vertices.

**Comment by TuanNguyenSKKU** [comment]
@xuanthuyvo thank you, I think the mask region is actually created based on polygons. Therefore, the polygon vertice must be identified first. The problem is that I don't know where the related codes are.
I think if we use cv2.findContours function, the accuracy of mask region may be reduced compared to the original one.

**Comment by xuanthuyvo** [comment]
You can try to read the paper PolarMask. The method also converts ground truth masks to ground truth polygons (36 vertices).
https://github.com/xieenze/PolarMask

**Comment by xuanthuyvo** [comment]
https://gitlab.com/irafm-ai/poly-yolo

**Comment by TuanNguyenSKKU** [comment]
Yes, they also assembly the whole contours to create masks but I see that those accuracies seem to be lower than Mask R-CNN :((. 
Thank you for your suggestions.
Hope to receive more solutions for this issue.
