### ISSUE TITLE
After completed object detection, how to get the feature vectors of different targets on different levels ?

### ISSUE THREAD

**Issue by y78h11b09** [open-mmlab/mmdetection#3473]
How to extract the feature of object on single-stage model in mmdection??? anyone do it ?

**Comment by hellock** [comment]
You need to implement it by yourself.

**Comment by y78h11b09** [comment]
I have solved it try my best, and now got some progress!, thank you



y78h11b09@163.com
 
From: Kai Chen
Date: 2020-08-14 01:36
To: open-mmlab/mmdetection
CC: y78h11b09; State change
Subject: Re: [open-mmlab/mmdetection] After completed object detection, how to get the feature vectors of different targets on different levels ? (#3473)
You need to implement it by yourself.
