### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3474]
Hi, I just had 2 very quick questions on data augmentation. As I have data that does not have default orientation, I wanted to implement both horizontal and vertical random flips in the data augmentation pipeline, and just wanted to check if the best way to do this was to add both these lines in the ```train_pipeline```:
```
dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
dict(type='RandomFlip', flip_ratio=0.5, direction='vertical'),
```
Also, just wanted to ask, when implementing random cropping, whether it is standard practice to perform cropping first followed by resizing. Thanks!

**Comment by hellock** [comment]
Q1: It will result in unexpected behavior if you use two consecutive `RandomFlip`. We will fix it soon.
Q2: No standard practice for that, and you may decide to perform which one first.

**Comment by sehyungp92** [comment]
@xvjiarui Many thanks for looking into this!

So if I set ``flip_ratio=0.75``, ``direction=['horizontal',  'vertical',  'diagonal']``, does this mean it will be horizontally flipped with probability 0.25, vertically with probability 0.25 and horizontally & vertically with probability 0.25?

**Comment by xvjiarui** [comment]
@sehyungp92 
Yes!
