### ISSUE TITLE
loss.backward() error when trying to calculate grad of input

### ISSUE THREAD

**Issue by THUrssq** [open-mmlab/mmdetection#3476]
I want to change the input image using gradient, but error happens 
error information

RuntimeError: range.second - range.first == t.size() INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579040055865/work/torch/csrc/autograd/generated/Functions.cpp:55, please report a bug to PyTorch. inconsistent range for TensorList output

**Comment by SunSwallow** [comment]
I hacve the same problem. Have you solved the problem?
