### ISSUE TITLE
"ClassBalance": hows to instantiate function self.get_cat_ids(idx)

### ISSUE THREAD

**Issue by leopardyao** [open-mmlab/mmdetection#3478]
Hello, 
mmdet 2.3.0, torch 1.4.0, mmcv 1.0.4:
in online documentation, there is sth about classbalance, but it does not tell full story.
so if i only change config.py for my dataset voc_0712.py
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='ClassBalancedDataset',
        oversample_thr=1e-3,
        dataset=dict(
            type=dataset_type, ...

 I will run into below error for training:
 File "/home/usr/mmdetection/mmdet/datasets/dataset_wrappers.py", line 187, in _get_repeat_factors
    for cat_id in cat_ids})
ValueError: max() arg is an empty sequence

what should I exactly do to make classbalance work? thanks

**Comment by ZwwWayne** [comment]
It seems that the list is empty [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L185), which means that some images in your dataset may not have gt bboxes, which is not supported by `ClassBalancedDataset` by now.  The code below may be a workaround.
```python
            repeat_factor = max(
                {category_repeat[cat_id]
                 for cat_id in cat_ids}) if len(cat_ids) > 0 else 1
```
I have not tested it, you can try.

**Comment by will6309** [comment]
Hi there, I am not sure if you have solved your problem. In your case, try the following changes:
data = dict(
samples_per_gpu=2,
workers_per_gpu=2,
type='ClassBalancedDataset',
oversample_thr=1e-3,
train=dict(
type=dataset_type, ...
