### ISSUE TITLE
Weighted Box Fusion as 

### ISSUE THREAD

**Issue by kartikJ-9** [open-mmlab/mmdetection#3479]
I am trying to implement Weighted Box Fusion in this framework. As mentioned [here ](https://github.com/ZFTurbo/Weighted-Boxes-Fusion), it has proved to give a better accuracy. Please help me implement this in the framework. Thanks.

**Comment by ZwwWayne** [comment]
We usually do not provide specific suggestions about feature implementation. The [tutorials](https://github.com/open-mmlab/mmdetection/tree/master/docs/tutorials) might help.

**Comment by kingoo123** [comment]
> I am trying to implement Weighted Box Fusion in this framework. As mentioned [here ](https://github.com/ZFTurbo/Weighted-Boxes-Fusion), it has proved to give a better accuracy. Please help me implement this in the framework. Thanks.

Hello, have you integrated WBF into mmdetection? Do you have any suggestions for me? Thanks
