### ISSUE TITLE
cl.exe failed

### ISSUE THREAD

**Issue by LukaPM** [open-mmlab/mmdetection#348]
I encountered the following problem when compiling compile.sh
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
The environment is:win10, python3.6, pytorch1.0, visio studio2015
I tried many methods but could not solve them. Is it possible that compile. sh cannot run in pytorch1.0.Even now, support for pytorch1.0 has been updated

**Comment by LukaPM** [comment]
在编译compile.sh时，我遇到了以下问题
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
环境是:win10, python3.6, pytorch1.0, visio studio2015
我试过许多方法，但都解决不了。会不会是 compile.sh不能在pytorch1.0中运行。即使更新支持了pytorch1.0

**Comment by LukaPM** [comment]
我发现mmdet/ops/roi.align的更新时间是一个月前，会不会是这里没有更新
I found that the update time of mmdet/ops/roi.align was one month ago, may it be that there is no update here

**Comment by LukaPM** [comment]
@hellock

**Comment by LukaPM** [comment]
Sorry, I didn't know this doesn't support Windows

**Comment by hellock** [comment]
We are not familiar with pytorch on windows and don't have windows servers to test on, so no official support for windows is provided.

**Comment by lbq779660843** [comment]
> 在编译compile.sh时，我遇到了以下问题
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
> 环境是:win10, python3.6, pytorch1.0, visio studio2015
> 我试过许多方法，但都解决不了。会不会是 compile.sh不能在pytorch1.0中运行。即使更新支持了pytorch1.0

我是没配置环境变量，出现了这问题，下面是方法:
https://jingyan.baidu.com/article/a501d80c267390ec630f5ee4.html
但又出了新问题，我佛啦...

**Comment by hellock** [comment]
mmdetection does not provide official support for windows currently.

**Comment by Timmmmmms** [comment]
> 在编译compile.sh时，我遇到了以下问题
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
> 环境是:win10, python3.6, pytorch1.0, visio studio2015
> 我试过许多方法，但都解决不了。会不会是 compile.sh不能在pytorch1.0中运行。即使更新支持了pytorch1.0

你好，请问解决了吗？我也遇到这样的问题

**Comment by LaserLV52** [comment]
> mmdetection does not provide official support for windows currently.

did the mmdetection support for windows now？
