### ISSUE TITLE
Example config file with Autoaugment

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3480]
Is there an example config py which implements Autoaugment just so that we can see how it fits into the train_pipeline.

Thanks!

**Comment by sky-fly97** [comment]
> Is there an example config py which implements Autoaugment just so that we can see how it fits into the train_pipeline.
> 
> Thanks!

I need it too!

**Comment by rhythm-A** [comment]
Can you give me some advice to use auto_augment.py?
