### ISSUE TITLE
关于现场部署问题

### ISSUE THREAD

**Issue by ayicherry** [open-mmlab/mmdetection#3481]
Hello：
       想请教一个问题，就是用mmdetection平台训练出来的模型，怎么样部署方便。比如使用c++，libtorch来部署。这个首先要把pth模型转换成ScriptModule模型下的pt模型，然后libtorch调用这个转换后的模型。但是用官方转换代码把mmdeteion训练出来的pth模型转换成ScriptModule模型下的pt模型一致不成功，不知道问题出在哪里。
      不知道大神们有没有部署上的经验传授一下，谢谢！

**Comment by liaopeiyuan** [comment]
As far as I know, there are multiple efforts in trying to deploy mmdetection-based models in production, such as https://github.com/grimoire/mmdetection-to-tensorrt and https://github.com/randxie/mmdetection-tvm . You can try them out. As for mmdetection-tvm, it is under active deployment, and we will post new progresses from time to time.

**Comment by nistarlwc** [comment]
@ayicherry 找到好的部署方法了吗？
我是希望能在windows下用python调用pytorch，转化为torchscript了，还能用python调用吗
