### ISSUE TITLE
Multi-label object detection

### ISSUE THREAD

**Issue by ngalym** [open-mmlab/mmdetection#3485]
Hello guys! Great work. Is there a way to use mmdetection for training a dataset for detection of objects that have multiple labels?

**Comment by ZwwWayne** [comment]
Current MMDetection does not support multi-label object detection. To do that, you need a dataset for your multi-label dataset, then you might need to implement a box head with the specially designed loss for that.

**Comment by yusiyoh** [comment]
Hello,
I have same issue and want to use mmdetect for a dataset with multi-labels (traffic lights with direction + aspect information, thus there are 4+3 classes, 4 directions, and 3 bulb numbers). @ngalym could you find any solution for your task? 
Thanks

**Comment by Windson9** [comment]
Hello @yusiyoh. Were you able to implement this ? I am trying to do something similar.
