### ISSUE TITLE
Pretrained Models for HTC with DCN

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3489]
Hi, just wanted to quickly check, are there pretrained models for HTC with DCN other than the one that uses ResNeXt-101-64x4d-FPN as the backbone (e.g. ResNet-50 or ResNet-101)? If so, is there any chance that they could be made available. Thanks!

**Comment by hellock** [comment]
Currently not, and there is no plan for that. We provide frameworks and users can train any models they want.
