### ISSUE TITLE
Install error due to release of pytorch 1.6.0

### ISSUE THREAD

**Issue by asuith** [open-mmlab/mmdetection#3490]
**Describe the bug**

Follow the install instruction step by step will not install properly. 

When running `python -c "from mmdet.apis import init_detector, inference_detector"` will cause `OSError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory`. (The error message may not be accurate because I didn't keep track, but there sure is one)

I suspect that the problem is related to **step c** when running the command

```
pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
```
and notice that the version specifies `torch1.5.0`, while the default version now for pytorch is `1.6.0`.

**Reproduction**

1. What command or script did you run?
Exact commands from the current `install.md`

**Bug fix**

I'm not sure if changing mmcv-full version from `torch1.5.0` to `torch1.6.0` would be a fix. But I installed pytorch **1.5.0** and everything works like a charm now. Specifically, using command
```
pip install pytorch==1.5.0 torchvision==0.6.0 cudatoolkit=10.1
```
(cudatoolkit version may vary, you can look up the command at [Previous PyTorch Versions | PyTorch](https://pytorch.org/get-started/previous-versions/)) instead of something like this
```
conda install pytorch torchvision cudatoolkit=10.1
```

**Comment by hellock** [comment]
We will soon release the prebuilt mmcv-full package for pytorch 1.6. For now, you can build mmcv from source by `pip install mmcv-full`.

**Comment by asuith** [comment]
> We will soon release the prebuilt mmcv-full package for pytorch 1.6. For now, you can build mmcv from source by `pip install mmcv-full`.

Thank you for responding! I'm looking forward to the prebuilt package. 

Looking back at the `install.md`, I noticed that there's a line in step c

> See here for different versions of MMCV compatible to different PyTorch and CUDA versions.

But the word "here" has no link to it. Maybe something is missing there?

**Comment by hellock** [comment]
Oh yes, it should link to https://github.com/open-mmlab/mmcv#install-with-pip. You may create a PR to fix it if you would like to.

**Comment by asuith** [comment]
Thank you. I'm happy to fix the typo.

**Comment by hellock** [comment]
Prebuilt packages for PyTorch 1.6 have been released.
