### ISSUE TITLE
How to use Autoaugment  in my config.py

### ISSUE THREAD

**Issue by sky-fly97** [open-mmlab/mmdetection#3503]
Hello, I want to use autoaugment of mmdet, but how to use autoaugment  in my config.py? Anyone can help me? Thanks!

**Comment by hellock** [comment]
It has not been implemented yet. You may need to implement some transforms first.

**Comment by sky-fly97** [comment]
> It has not been implemented yet. You may need to implement some transforms first.

Thanks, another question is about **dataset balance** of mmdet,   how to use this?

**Comment by hellock** [comment]
Please refer to the LVIS dataset and config files.

**Comment by sky-fly97** [comment]
> Please refer to the LVIS dataset and config files.

Thanks, but I my dataset is **object detection**.
 As shown in some **lvis config files**, can I only change the **dataset type to 'LVISV1Dataset'** and change  the **train type to 'ClassBalancedDataset'**?

**Comment by xvjiarui** [comment]
Hi @sky-fly97 
You may specify your own dataset type with `ClassBalancedDataset` wrapping.

**Comment by rhythm-A** [comment]
Can you give me some advice to use auto_augment.py?such as polices：v1?
