### ISSUE TITLE
2.0以上版本和1.x版本中添加senet骨干网络

### ISSUE THREAD

**Issue by cpboost** [open-mmlab/mmdetection#3505]
在1.2版本中我能够添加senet网络，但是在2.0以上缺不能修改成功。在注册构建网络的时候总是缺少参数，是mmcv新的版本中固定一些参数了吗？，比如depth，和num_stages，我想通过官方的分类网络添加到mmdet中，总会报错，我想知道mmcv是不是固定必须要传的参数了？

**Comment by hellock** [comment]
Please use English or English&Chinese for issues.
Please use the `Error report` issue template.
