### ISSUE TITLE
Multi-scale testing get worst results on HTC

### ISSUE THREAD

**Issue by r03943158** [open-mmlab/mmdetection#3506]
Hi, thanks your efficient code.

I have some questions when using the mutli-scale testing on HTC. When I use the 5 scales(img_scale=[(1400,1400), (1400,1200),(1400,1000),(1400,800),(1400,600) flip=True]), the mAP decreases 6% from baseline (using img_scale=(1333.800)Flip=false) on HTC.

However, the results will improve 1.0mAP when using two image scales(img_scale=[(1400,1200),(1400,600)]). Is the MultiScaleFlipAug can only using two image scales for resize?

Thank you.

**Comment by ZwwWayne** [comment]
Please use the `Reimplementation questions` to describe you problem in detail. We are not able to diagnose the issue for now due to limited information.
