### ISSUE TITLE
resize image to (1333,800)

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3509]
I want to know why the resize scale used in the paper is (1333, 800).
Every one of in coco images, the scale and aspect ratio are different.
Is the resize method of keeping keep_ratio in mmdet equivalent to multi-scale training?
Thank you!

**Comment by hellock** [comment]
- Aspect ratios are not changed. 
- This is a typical convention.
- `keep_ratio` has nothing to do with multi-scale training.

**Comment by zhjw0927** [comment]
`dict(type='Resize', img_scale=(1333, 800), keep_ratio=True)`
I would like to ask whether the above approach is equivalent to multi-scale training?
For instance:
img1: original shape: (400, 200, 3)  resize shape: (1333,666,3)eee
img2: original shape: (573,462, 3)   resize shape: (992, 800, 3)
Because the size of each image in coco is different, the network will learn the object of different scales after this resize method.e
So, is equivalent to multi-scale training?
Thank you!
