### ISSUE TITLE
About uniform sampling

### ISSUE THREAD

**Issue by backkon** [open-mmlab/mmdetection#3512]
During the training process, most of our datasets are category unbalanced, presenting long tail distribution. I wonder if uniform sampling is implemented in mmdetection, and if so, how to use it ?

Look fowward to your reply！

**Comment by hellock** [comment]
You can implement your own samplers or datasets. [Here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L99) is an example.
