### ISSUE TITLE
How to eval already exists json

### ISSUE THREAD

**Issue by linyangsdu** [open-mmlab/mmdetection#3515]
I want to eval a json file with mmdetection, how can I do?

**Comment by ZwwWayne** [comment]
Currently, we do not support to evaluate the produced JSON file. We are considering to support evaluation on saved inference results in the future.

**Comment by ZwwWayne** [comment]
As a workaround, you may refer to the implementation [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L272) and write a script for that.

**Comment by linyangsdu** [comment]
Okay, I have solved it, thank you!
