### ISSUE TITLE
Should I split the my own dataset as Train-Val?

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#3518]
I am using a own data set and data part of the my config file is below.
```
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
	classes=classes,
        ann_file=data_root + 'annotations/train.json',
        img_prefix=data_root + 'images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
	classes=classes,
        ann_file=data_root + 'annotations/train.json',
        img_prefix=data_root + 'images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
	classes=classes,
        ann_file=data_root + 'annotations/test.json',
        img_prefix=data_root + 'images/',
        pipeline=test_pipeline))
```
I don't want to divide my datasets as train-val. I am thinking of training directly in this way. Do I train like this or do I divide the data set by 80-20 ratio as train-val?

If I write the entire data set in both train and val sections as above, I think the toolkit divides the data set as train-val by making a rating in itself. I wonder if I'm thinking wrong? Can you guide me in this matter.

Note: There are about 25000 images(1024x1024 size) in my data set. I would be glad if you comment accordingly

**Comment by ZwwWayne** [comment]
The codebase does not support to split the train/val set automatically because this is usually the responsibility of users. For common practice, it might be better to split a small val set from training data to avoid overfitting the test data.

**Comment by zerok01** [comment]
Thank you for the answer. I think I understand what you mean. Accordingly, I separated 20% of the data set as val. I guess it will be better this way

**Comment by ZwwWayne** [comment]
Good luck.
