### ISSUE TITLE
Syntax error for dist_train.sh

### ISSUE THREAD

**Issue by CathayPacific358** [open-mmlab/mmdetection#3520]
**Describe the bug**
When running dist_train.sh an syntax error for CONFIG=$1 occurred for no reason.

**Reproduction**
1. Error traceback
```
  File "./tools/dist_train.sh", line 3
    CONFIG=$1
           ^
SyntaxError: invalid syntax
```
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.1.2
MMCV: 0.6.2
MMDetection: 2.1.0+e7537a4
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1

**Comment by ZwwWayne** [comment]
What is your running command when you use `dist_train.sh`?

**Comment by SISTMrL** [comment]
sh ./tools/dist_train.sh ./configs/faster_rcnn/faster_rcnn_r50_fpn_soft_nms_1x_coco.py --gpu-ids 4 5 6 7


hello，when i run this command, it encounters this problem:
./tools/dist_train.sh: 7: ./tools/dist_train.sh: Bad substitution

the question is I don't know to train my model with multiple gpus, could you tell the command to train model with multiple GPUS? thanks!!

**Comment by trikim** [comment]
> sh ./tools/dist_train.sh ./configs/faster_rcnn/faster_rcnn_r50_fpn_soft_nms_1x_coco.py --gpu-ids 4 5 6 7
> 
> hello，when i run this command, it encounters this problem:
> ./tools/dist_train.sh: 7: ./tools/dist_train.sh: Bad substitution
> 
> the question is I don't know to train my model with multiple gpus, could you tell the command to train model with multiple GPUS? thanks!!

you could try to change "sh" to "bash".
