### ISSUE TITLE
fp16+dist_train is about four times slow than without mix precision training?

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [open-mmlab/mmdetection#3526]
without fp16 config, the training speed is 1sec/iter,
with fp16, I get 4sec/iter

has anyone run into the same problem?

**Comment by hellock** [comment]
You need volta GPUs, e.g., V100, for speedup.

**Comment by Jiangfeng-Xiong** [comment]
> You need volta GPUs, e.g., V100, for speedup.

ok, thanks, I use P40, and I have just found that it does not support float16

**Comment by blackCmd** [comment]
> without fp16 config, the training speed is 1sec/iter,
> with fp16, I get 4sec/iter
> 
> has anyone run into the same problem?

How to change datatype fp16 to fp32?
Where can I change that in source code?
