### ISSUE TITLE
lr seting doesn't match actual lr,so confusing

### ISSUE THREAD

**Issue by GingerCohle** [open-mmlab/mmdetection#3527]
![image](https://user-images.githubusercontent.com/37873318/89858070-437a7200-dbd0-11ea-8454-81bfb68f3b78.png)

**Comment by GingerCohle** [comment]
U can see 0.0001 mismatch 2e-2

**Comment by ZwwWayne** [comment]
This is because the LR saved in the checkpoint is 2e-2. This seems to be a bug and we will fix it in the future.

**Comment by yhcao6** [comment]
Could you try the latest mmcv and mmdet, I can't reproduce this error.
When I resume the model of faster rcnn from epoch 5, the default learning rate is 2e-2 and I change the learning rate in config to be 8e-2, then the learning rate of learning rate is 8e-2, it is expected.

**Comment by GingerCohle** [comment]
> Could you try the latest mmcv and mmdet, I can't reproduce this error.
> When I resume the model of faster rcnn from epoch 5, the default learning rate is 2e-2 and I change the learning rate in config to be 8e-2, then the learning rate of learning rate is 8e-2, it is expected.

I will try my model, thanks for ur attention.

**Comment by GingerCohle** [comment]
> Could you try the latest mmcv and mmdet, I can't reproduce this error.
> When I resume the model of faster rcnn from epoch 5, the default learning rate is 2e-2 and I change the learning rate in config to be 8e-2, then the learning rate of learning rate is 8e-2, it is expected.

I change lr by set config/cascadefolder/casxxx.py,and still
![image](https://user-images.githubusercontent.com/37873318/91722906-87f49e80-ebcd-11ea-9d37-d78769333e30.png)

**Comment by GingerCohle** [comment]
> Could you try the latest mmcv and mmdet, I can't reproduce this error.
> When I resume the model of faster rcnn from epoch 5, the default learning rate is 2e-2 and I change the learning rate in config to be 8e-2, then the learning rate of learning rate is 8e-2, it is expected.

![image](https://user-images.githubusercontent.com/37873318/91723714-ca6aab00-ebce-11ea-885f-6ce1df08a20c.png)
I think i installed the latest

**Comment by GingerCohle** [comment]
> This is because the LR saved in the checkpoint is 2e-2. This seems to be a bug and we will fix it in the future.



> Could you try the latest mmcv and mmdet, I can't reproduce this error.
> When I resume the model of faster rcnn from epoch 5, the default learning rate is 2e-2 and I change the learning rate in config to be 8e-2, then the learning rate of learning rate is 8e-2, it is expected.

So I sovle the problem by seting this 
![image](https://user-images.githubusercontent.com/37873318/91724983-a1e3b080-ebd0-11ea-899d-c07f0ffaa63e.png)
I resume from epoch_12 and set  lr_config = dict(policy='step', step=[12, 22])
lr = 0.002
