### ISSUE TITLE
How to set workers_per_gpu?

### ISSUE THREAD

**Issue by AresGao** [open-mmlab/mmdetection#353]
I set ssd ``imgs_per_gpu=32```, So need I change the ``workers_per_gpu``` to match the images? I set ``workers_per_gpu=20``` and I the speed come slower...

**Comment by hellock** [comment]
`workers_per_gpu` needs to match you cpu cores, `workers_per_gpu=20` requires 20*8=160 cpu cores. If it is set larger than cpu cores, the speed will be slow.

**Comment by Fmin-Zou** [comment]
> `workers_per_gpu` needs to match you cpu cores, `workers_per_gpu=20` requires 20*8=160 cpu cores. If it is set larger than cpu cores, the speed will be slow.

Hello! If my cpu cores=12, and I use 2 gpus, should I set the `workers_per_gpu=6'? or less than it? which will be better for training?
