### ISSUE TITLE
You have worked so hard on this. Improve documentation.

### ISSUE THREAD

**Issue by bluesky314** [open-mmlab/mmdetection#3535]
You guys have worked so hard on this great library. It has so many features. It would be great if you provided more examples in documentations that would make new users get a quicker handle on it. Many kagglers and researchers are not expert software engineers so it would really help. Your library would be used much much more if you did so. Some ideas: 

Creating Hooks
Using Hooks(like tensorboard,wandb, etc)
Adding losses
Modifying the train loop

**Comment by hellock** [comment]
Thanks for your suggestions. We have been working on improving the documentation since V2.0, and will go on for it with your nice advices.
