### ISSUE TITLE
How to download   pre-trained  model   with  aliyun

### ISSUE THREAD

**Issue by CZMHHH** [open-mmlab/mmdetection#3540]
Recently,I want  to  compare   mmdetection  with  detection2.  When  I  replace https://s3.ap-northeast-2.amazonaws.com/open-mmlab with https://open-mmlab.oss-cn-beijing.aliyuncs.com ,  it does  not  down  auto  Automatically.  
![ILOF5ZBF)L$TD OC4SG`FET](https://user-images.githubusercontent.com/46748561/89997066-36d44780-dcbe-11ea-984a-e2e3e03da3c3.png)

**Comment by ZwwWayne** [comment]
We have not synchronized models from aws to aliyun yet.

**Comment by CZMHHH** [comment]
Thank you for your reply. I  want  to know  when  can  I download  from  the  aliyuncs?  Where  can  I  download?   Thank  you.
