### ISSUE TITLE
Filtering out the empty images by default

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3545]
I notice that on the customized dataset, the data loader by default will filter out empty images (image without annotations) on the testing set during testing. Is there a particular reason for doing so? Thanks!

```
    CLASSES = None

    def __init__(self,
                 ann_file,
                 pipeline,
                 classes=None,
                 data_root=None,
                 img_prefix='',
                 seg_prefix=None,
                 proposal_file=None,
                 test_mode=False,
                 **filter_empty_gt=True):**
```

**Comment by ZwwWayne** [comment]
It is just a common practice because images usually have GT in COCO/VOC datasets.

**Comment by shanggdlk** [comment]
> It is just a common practice because images usually have GT in COCO/VOC datasets.

Thank you for your reply! I tried to set filter_empty_gt=False, but it still not work when testing on the customized dataset (meaning it will filter empty images as well during testing). I find related questions on this issue and it requires us to modify coco.py code. Any plan to address this bug (forgive me if "bug" is not a proper word here)?

Thanks!

**Comment by skylake-L** [comment]
If there are no defect in my image, do I need to write bbox [0,0,0,0] into my annotation
