### ISSUE TITLE
`benchmark.py`.  ModuleNotFoundError: No module named 'tools.fuse_conv_bn'.

### ISSUE THREAD

**Issue by sr-frost** [open-mmlab/mmdetection#3552]
Recently the `tools/fuse_conv_bn.py`  was removed in #3529 . But the `benchmark.py`  is still trying to use the old script. 

[https://github.com/open-mmlab/mmdetection/blob/master/tools/benchmark.py#L8](https://github.com/open-mmlab/mmdetection/blob/master/tools/benchmark.py#L8)

I think this might be causing the error.

**Reproduction**
1. What command or script did you run?
```
tools/benchmark.py
```

**Comment by hellock** [comment]
`fuse_conv_bn` has been moved to mmcv.
@yhcao6 Please fix this bug.
