### ISSUE TITLE
Supporting Decimal weight decaying settings

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3554]
Hi, there,

My customized dataset is relatively large (20X more than COCO), so I will use a relatively small number of epochs for training. e.g. 2. I'm wondering if I can use decimal weight decaying settings, e.g.:  step=[1.6, 1.9]). If not, how can we change to # of iterations instead? Thank you!

```
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[1.6, 1.9])
total_epochs = 2
```

**Comment by hellock** [comment]
It is currently not supported. @xvjiarui may add documentation on how to use `IterBasedRunner`.
