### ISSUE TITLE
why imgs/gpu is 2?

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3555]
For Fatser RCNN, why use 8 Gpus and only 2 images per GPU?
In this case, don't use synchronous BN, don't  worry about the performance impact?
If I have 8 gpus, also do follow this example to do research?

**Comment by hellock** [comment]
8 GPUs with 2 images per GPU is a typical setting. You can also try other settings.
BN stats are fixed in this setting.

**Comment by zhjw0927** [comment]
Thank you. I got it.
