### ISSUE TITLE
Error in modulated_deformable_col2im_cuda: invalid argument

### ISSUE THREAD

**Issue by gasvn** [open-mmlab/mmdetection#356]
I met an error of when using the  deformable conv with a large image size.
When the input image is larger than 1024x1024 (1, 512, 128, 128 for that layer), the ` invalid argument` error occurs. I think the reason for this error is that the pre-allocated memory space is not enough. But I not familiar with the Cuda program in pytorch, so I can't find a solution yet.

**Comment by gasvn** [comment]
@hellock  @yhcao6

**Comment by ybai62868** [comment]
@gasvn I got the same questions with you... but the training process is running. Do you know this error will effect the experiment results?

**Comment by ybai62868** [comment]
@gasvn I got the same questions with you... but the training process is running. Do you know this error will affect the experiment results?

**Comment by gasvn** [comment]
@ybai62868 Not so sure, I resized images with large size to avoid this error. But I guess it will affect the results if there are lots of large images.

**Comment by hellock** [comment]
I guess this may be a bug and any reports are welcome. Does it has any influence on the performance?

**Comment by hellock** [comment]
https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/issues/13
