### ISSUE TITLE
What does “32x4d” mean?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#3562]
A littile question , What does “32x4d” mean?(faster_rcnn_x101_32x4d_fpn_1x_coco)
I know the meaning of the other parts of the name but I don’t know the meaning of this part(32x4d)
I will be very grateful if you can reply

**Comment by shinya7y** [comment]
"x101_32x4d": [ResNeXt-101 (32x4d)](https://arxiv.org/abs/1611.05431)
