### ISSUE TITLE
How can I add new nms in mmdetection?

### ISSUE THREAD

**Issue by Mabinogiysk** [open-mmlab/mmdetection#3565]
Hi,
I am using mmdetection 1.1.0 and I want to add some new nms algorithm. I modified file `mmdet/ops/nms/nms_wrapper`, however I got this error:
```
AttributeError: module 'mmdet.ops.nms.nms_wrapper' has no attribute 'nms_xxx'
```
What should I do?
Thanks.

**Comment by sky-fly97** [comment]
> 嗨,
> 我使用mmtection1.1.0，我想添加一些新的nms算法。我修改了文件`mmdet/ops/nms/nms_wrapper`，但是我得到了这个错误：
> 
> ```
> AttributeError: module 'mmdet.ops.nms.nms_wrapper' has no attribute 'nms_xxx'
> ```
> 
> 我该怎么办？
> 谢谢。



> Hi,
> I am using mmdetection 1.1.0 and I want to add some new nms algorithm. I modified file `mmdet/ops/nms/nms_wrapper`, however I got this error:
> 
> ```
> AttributeError: module 'mmdet.ops.nms.nms_wrapper' has no attribute 'nms_xxx'
> ```
> 
> What should I do?
> Thanks.

Hello, have you solved this problem? Can you share your work？Thanks
