### ISSUE TITLE
Deformable groups - support and explanation

### ISSUE THREAD

**Issue by jsaric** [open-mmlab/mmdetection#357]
Hi, thank you for your work!
Is deformable_groups parameter now supported in deformable convolutions?
Could you please precisely explain what happens If I set it do !=1?
I wonder if each group has different kernel weights and different offsets or kernel weights across groups are shared and offsets are not?

**Comment by hellock** [comment]
`deformable_groups` refers to the offset groups (as described in the DCN paper), and `groups` refers to the convolution groups (just the same as group convolution, which is not implemented in the original DCN paper). You may refer to the paper for more details.

**Comment by alexwq100** [comment]
@hellock ，so deformable_groups must be equal to the groups ?
