### ISSUE TITLE
Why doese the mAP increase so much in v2 than in v1 when I use the same configs file to train same custom dataset?

### ISSUE THREAD

**Issue by hq804903203** [open-mmlab/mmdetection#3572]
First, thanks for your work!  But I'm confused about the great improvement of mAP in v2 than v1 when I use the same configs file to train same custom dataset. 

I used MMdetectionV1 to train my custom dataset, the mAPs of faster-rcnn and cascade-rcnn-dconv with albu are 53.7(overfitting) and 81.9 respectively. Recently, I installed v2 without uninstalling v1, then v1 can't be used. So I used v2 to reproduce the experiments in v1, the mAPs of faster-rcnn with albu and cascade-rcnn-dconv are 88.5 and 89. The results are shocking, especially the mAP of the faster rcnn with albu in v2 is much better than cascade rcnn dconv with albu in v1. 

I'm confused about the results and hope you can give me some advice.

**Comment by ZwwWayne** [comment]
A note can be found [here](https://mmdetection.readthedocs.io/en/latest/compatibility.html). For legacy models, you can still use them following the [doc](https://mmdetection.readthedocs.io/en/latest/compatibility.html#upgrade-models-from-1-x-to-2-0).

**Comment by hq804903203** [comment]
Thanks for your reply. I find the old configure file, and I'll try doing some ablation experiments to find the reason.

**Comment by hq804903203** [comment]
Excuse me, I have a new problem. I found that the icon of the checkpoint file saved after training is compressed file. And when i try to load from my own checkpoint file, an error occur as follows.

![image](https://user-images.githubusercontent.com/28336096/90591243-35060900-e215-11ea-88ed-82085ad6ae08.png)
```
2020-08-19 11:00:05,366 - mmdet - INFO - load checkpoint from ./work_dirs/0819_50_dcn_0001/epoch_12.pth
Traceback (most recent call last):
  File "tools/train.py", line 154, in <module>
    main()
  File "tools/train.py", line 150, in main
    meta=meta)
  File "/home/hq/mmdetection/mmdet/apis/train.py", line 142, in train_detector
    runner.load_checkpoint(cfg.load_from)
  File "/home/hq/anaconda3/envs/mmlab2/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 303, in load_checkpoint
    self.logger)
  File "/home/hq/anaconda3/envs/mmlab2/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 224, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/hq/anaconda3/envs/mmlab2/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 199, in _load_checkpoint
    raise IOError(f'{filename} is not a checkpoint file')
OSError: ./work_dirs/0819_50_dcn_0001/epoch_12.pth is not a checkpoint file
```
I open my own ckpt file and find its keys are `meta, state_dict, optimizer` instead of `meta, state_dict`. I guess the reason of this design is for resuming training. So I create a new ckpt file by removing the part of `optimizer` in original ckpt file, but the new ckpt file still can't be loaded in model, the error is as same as before. 

 Then I find the `checkpoint.py` in `mmcv/runner` and comment out the code between line 348 and line 357 and train the model again. The ckpt file generated by training can be loaded correctly. Maybe it is a bug or it results from other reasons. Hope you can check this out in your spare time. Thanks!

The code commented out by me is as follows. It's in the bottom of `mmcv/runner/checkpoint.py`.
```
    # save optimizer state dict in the checkpoint
#    if isinstance(optimizer, Optimizer):
#        checkpoint['optimizer'] = optimizer.state_dict()
#    elif isinstance(optimizer, dict):
#        checkpoint['optimizer'] = {}
#        for name, optim in optimizer.items():
#            checkpoint['optimizer'][name] = optim.state_dict()
```

**Comment by ZwwWayne** [comment]
It raises an error because `osp.isfile(filename)=False`， which means you might give a wrong path to load. Comment out the resume of optimizer does not help anything actually. Without commenting it out, you can still re-train a model successfully.

**Comment by hq804903203** [comment]
Sorry, I reviewed the config file and found the error resulted from spelling mistake.  It‘s a bit embarrassing, haha

**Comment by BigYsmallx** [comment]
hello，I found the same mistake,./work_dir/faster_rcnn_r50_fpn_1x_coco/epoch_12.pth is not a checkpoint file. could you tell me how  to solve it? Thank you
