### ISSUE TITLE
Results mismatch of evaluation in train.py and test.py

### ISSUE THREAD

**Issue by b02202050** [open-mmlab/mmdetection#3573]
## Description
I validate after each epoch and pick a best bbox_mAP_50 model.
But when evaluating the validation set with the `tools/test.py` on the saved model, I found slightly difference from the validation score I recorded when running with `tools/train.py`.
* validation dataset re-test score (bbox_mAP_50): 0.642
* validation score recorded (bbox_mAP_50): 0.640

How can this happen?

## details
1. I use only single GPU for both training and testing.
1. All the configs are the same for train.py and test.py, especially the `val` and `test` dataset are the same.
1. `fp16` in used for training and testing.
1. I extract the validation score through `eval_res['bbox_mAP_50']` after [this line](https://github.com/open-mmlab/mmdetection/blob/6acf6be921429343f885c0fab7fa75ba01c46d16/mmdet/core/evaluation/eval_hooks.py#L31), which gives 0.640
1. I run the `tools/test.py` and get `Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.642`

Thanks for help.

**Comment by ZwwWayne** [comment]
We do not know either. Usually, for this problem, you can set breakpoints in the code and compare the difference.

**Comment by b02202050** [comment]
> We do not know either. Usually, for this problem, you can set breakpoints in the code and compare the difference.

Do you either face this problem? Or this is only my case?
Thanks!

**Comment by ZwwWayne** [comment]
We recently find out the reasons, it is because that the BN's means and stds are different in different GPU cards, during training evaluation, different GPU thus inference with different BN's means and stds. In test.py, all GPU uses the loaded checkpoint thus uses a similar BN. These could cause a slight difference in the model's evaluation AP.
