### ISSUE TITLE
 Is there any good way to reduce GPU mempry?

### ISSUE THREAD

**Issue by gjxgjxgjxgjx** [open-mmlab/mmdetection#3574]
I added some modules to FPN, and running get_flop found that the number of parameters is not much, but the video memory occupied during training is so much that I changed the epoch from 10 to 1.The new module is written in the normal pytorch way.

 Is there any good way to reduce GPU mempry?

**Comment by ZwwWayne** [comment]
You can reduce the batch size from 2 to 1. Changing the epoch will not reduce the GPU memory cost.
You can also set `gpu_assign_thr=N` to reduce the GPU memory according to [here](https://mmdetection.readthedocs.io/en/latest/api.html#mmdet.core.bbox.MaxIoUAssigner) for calculating box IoU, but this will slow down the speed.

**Comment by gjxgjxgjxgjx** [comment]
@ZwwWayne I made a mistake before, and I was talking about batch. Where is gpu_assign_thr set?

**Comment by gjxgjxgjxgjx** [comment]
@ZwwWayne The default value of gpu_assign_thr is -1, how do I know how much this value should be set to?

**Comment by ZwwWayne** [comment]
You need to tune this hyperparameter. We do not know either since different kinds of GPUs have different memories. We just provide an option/feature for the users.

**Comment by ZwwWayne** [comment]
> @ZwwWayne After I set gpu_assign_thr, the memory occupied by training is still very high and it doesn’t work. Even setting gpu_assign_thr=1 is the same
> 
> train_cfg = dict(
> assigner=dict(
> type='MaxIoUAssigner',
> pos_iou_thr=0.5,
> neg_iou_thr=0.4,
> min_pos_iou=0,
> ignore_iof_thr=-1,
> gpu_assign_thr=1), #
> allowed_border=-1,
> pos_weight=-1,
> debug=False)

If so, you can further try to resize the images to a smaller size. This will reduce the performance but will reduce the memory.
