### ISSUE TITLE
Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by zlx-6** [open-mmlab/mmdetection#3579]
hello. When i run the ''python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'', it will get an error :
File "/home/xxx/anaconda3/envs/mmdet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution.

And the environment is
    sys.platform: linux
   Python: 3.8.5 (default, Aug  5 2020, 08:36:46) [GCC 7.3.0]
   CUDA available: True
   CUDA_HOME: None
   GPU 0: Quadro K2000
   GCC: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
   PyTorch: 1.5.0
   PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;- 
  gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;- 
  gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  

Besides, it also get an warning:
  userWarning: 
       Found GPU0 Quadro K2000 which is of cuda capability 3.0.
       PyTorch no longer supports this GPU because it is too old.
      The minimum cuda capability that we support is 3.5.
       warnings.warn(old_gpu_warn % (d, name, major, capability[1]))

i also run it with pytorch 1.6.and it also has the same problems.

i want to konw the problems come from the gpu is too old, or maybe my enviroment has some problems? thanks.

**Comment by ZwwWayne** [comment]
This is just because the GPU is too old. The minimum arch supported by Pytorch-1.6 is 3.5 but your GPU only supports CUDA 3.0.

**Comment by zlx-6** [comment]
@ZwwWayne thank you very much, can i solve it by build pytorch from source?

**Comment by zlx-6** [comment]
I solve it by build pytorch from source and modify some  files. thanks

**Comment by besmaGuesmi** [comment]
How did you solve it?

**Comment by besmaGuesmi** [comment]
I tried to decrease the image size and the batch size to consume less VRAM and it works fine!

**Comment by ZivNice** [comment]
It's probably due to insufficient GPU memory. You can try adjusting the batch size.
