### ISSUE TITLE
--validate error

### ISSUE THREAD

**Issue by jiesonZheng** [open-mmlab/mmdetection#358]
When I train the maskrcnn model with --validate parameter：
./tools/dist_train.sh ./configs/mask_rcnn_r50_fpn_1x.py 4 --workdir ./MaskFpn50 --validate
The first epoch can be trained and the validate result displayed, and then it is stuck there, without any hints.

If I train the maskrcnn model without --validate :
./tools/dist_train.sh ./configs/mask_rcnn_r50_fpn_1x.py 4 --workdir ./MaskFpn50
The training process is ok.

I installed mmdection as described in INSTALL.md. 
I have not changed any code or config value, Where is wrong? Has anyone encountered this problem?
thanks.

**Comment by neolovepineapple** [comment]
I have the same problem and don't know how to solve it!

**Comment by Luodian** [comment]
hi~I use --validate without errors, but where the validation outputs saved? I didn't find them.

**Comment by tycallen** [comment]
I have the one epoch validation hang problem too.

**Comment by jeasinema** [comment]
The same issue here when training RetinaNet.

**Comment by milleniums** [comment]
求解啊，烦死人了

**Comment by ZwwWayne** [comment]
It should be the bug  of early version of Pytorch. Please upgrade the codebase and environments.
