### ISSUE TITLE
mmcv install error

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3583]
This is my envs.
ubuntu16.04
CUDA 10.0
python 3.7
![image](https://user-images.githubusercontent.com/42128459/90633974-96e86200-e259-11ea-9baa-50294f786cb3.png)

The following error occurred while using "MMCV_WITH_OPS=1 pip install -e ." or "pip install mmcv-full"

What is the reason?
What other information do you， please tell me.

**Comment by zhjw0927** [comment]
Unable to upload screenshots due to network restrictions

**Comment by tianwen0110** [comment]
Did you solve this problom? I meet the same one
