### ISSUE TITLE
can't install mmcv

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3584]
The following error occurred using MMCV_WITH_OPS=1 pip install -e .
![image](https://user-images.githubusercontent.com/42128459/90635798-41fa1b00-e25c-11ea-8bf3-0e37e4383a5e.png)
Please let me know if you need any other environmental information.
Thank you!

**Comment by zhjw0927** [comment]
python 3.7
pytorch 1.3.1
CUDA 10.0
Ubuntu 16.04

**Comment by hellock** [comment]
You may try `pip install -v -e .` to print more logs.

**Comment by zhjw0927** [comment]
I solved it.
![image](https://user-images.githubusercontent.com/42128459/91512709-33bf9500-e915-11ea-930e-63a6715a1086.png)
extra add CUDA_TOOLKIT_ROOT_DIR CFLAGS, etc.
