### ISSUE TITLE
relax mmcv version requirement

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmdetection#3588]
mmdetection 2.3.0 requires mmcv==1.0.5? Could you consider relax this requirment? see also:
https://github.com/open-mmlab/mmdetection/blob/c31df74ee16345485245809dca47c716f04a103d/mmdet/__init__.py#L23

**Comment by ZwwWayne** [comment]
MMCV has BC-breaking changes from 1.0.5 to 1.1.0, to we add this assertion thus the users know that they should install mmcv-full==1.0.5 instead.
