### ISSUE TITLE
The parameter 'validate' is not work.

### ISSUE THREAD

**Issue by Flawless1202** [open-mmlab/mmdetection#36]
I find the `_non_dist_train()` function in `mmdet/apis/train.py` does not use the parameter 'validate', so  I could not see the validate result even though I use the parameter '--validate'.

**Comment by hellock** [comment]
We haven't implemented the evaluation hook for non-distributed training and will add it later. Currently you can use distributed training, which is strongly recommended.

**Comment by Flawless1202** [comment]
Is there any tutorials to use distributed training? My lab has two machines, both of them have 4 GPUs. 
Thank you! @hellock

**Comment by hellock** [comment]
Distributed training does not require multiple machines. If your two machines are not connected with an InfiniBand, it will be slow. In fact, we run all the experiments with 8 GPUs on a single machine.

To run on a single machine with distributed training, please refer to the [readme](https://github.com/open-mmlab/mmdetection#distributed-training).

If you do want to run on multiple machines, you can modify the commands in `tools/dist_train.sh` according to the [guide](https://pytorch.org/docs/stable/distributed.html#launch-utility).

**Comment by Flawless1202** [comment]
OK I will try this. Thanks a lot @hellock .
