### ISSUE TITLE
I used faster rcnn r50 to train the crowdhuman data set, and found that the memory is increasing continuously during training, and finally out of memory, my gpu is 11GB

### ISSUE THREAD

**Issue by hyz0720** [open-mmlab/mmdetection#3601]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
It might because Crowdhuman has many bounding boxes in a single image. You can change to use `samples_per_gpu=1` , or set `gpu_assign_thr=N` where N is a reasonable number to avoid OOM as below
```python
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            match_low_quality=True,
            gpu_assign_th=10,
            ignore_iof_thr=-1)),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            gpu_assign_th=10,
            match_low_quality=False,
            ignore_iof_thr=-1)))

```

**Comment by zimenglan-sysu-512** [comment]
how big gpu_assign_thr is reasonable?
