### ISSUE TITLE
len() of a numpy.ndarray causes "len() of unsized object" error.

### ISSUE THREAD

**Issue by zeakey** [open-mmlab/mmdetection#3602]
The `process_polygons()` function <https://github.com/open-mmlab/mmdetection/blob/9596b9a4c916ae601f9a8a641c3a0ea47265abec/mmdet/datasets/pipelines/loading.py#L268-L271>
uses the buitin function `len()` to a `numpy.ndarray` object, leading to a `
TypeError: len() of unsized object` error.

This issue is related to #3599 where I tried to output polygon-style annotations to the `FCNMaskHead`.

**Comment by ZwwWayne** [comment]
This is because the `polygon` is a scalar, you need to check the format of your annotations, especially the type of polygon.

**Comment by zeakey** [comment]
> This is because the `polygon` is a scalar or something that does not have `__len__`, you need to check the format of your annotations, especially the type of polygon.
`polygon` seems to be RLE format annotation encoded as a np.ndarray:

![QQ图片20200824170932](https://user-images.githubusercontent.com/6763078/91026070-daade380-e62c-11ea-93fe-06de274fad9c.png)

As mentioned in #3599 ,  I simply add `poly2mask=False` to `dict(type='LoadAnnotations', with_bbox=True, with_mask=True, poly2mask=False)` <https://github.com/open-mmlab/mmdetection/blob/9596b9a4c916ae601f9a8a641c3a0ea47265abec/configs/_base_/datasets/cityscapes_instance.py#L7>,
and then start training by `python tools/train.py configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py`.

I intend to get polygon-style targets (instead of masks) in the `roi head`, this is useful in many contour-based instance segmentation methods like  **deep-snake**, **polarmask**.

**Comment by ZwwWayne** [comment]
It seems that there is some incompatibility between the polygon mask and cityscapes. Please @yhcao6 have a check on that.
