### ISSUE TITLE
mAP@small and @medium is -1.00

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3610]
![image](https://user-images.githubusercontent.com/42128459/90993033-d01c2b80-e5e5-11ea-9cad-ea92161eacb0.png)
I'm running custom dataset, tt100k. Json format converted to Coco Style.
Why is this happening?
Any Suggestions?
Thank you!

**Comment by ZwwWayne** [comment]
What is your mmdet version?
This issue duplicates https://github.com/open-mmlab/mmdetection/issues/3468 and should already be fixed in https://github.com/open-mmlab/mmdetection/pull/3497.
