### ISSUE TITLE
Low speed of training widerface by ssd300 using dist_train.sh

### ISSUE THREAD

**Issue by XiaXuehai** [open-mmlab/mmdetection#3612]
Before training the model, it takes long long time, as well as validation. It is longer than single GPU. The utilization rate of cpu and gpu is low. I do not know what's the problem.
mmcv=0.6.2 installed by pip; 
and mmdetection=2.21；
pytorch=1.4.0 + cu100

**Comment by xvjiarui** [comment]
It takes longer when `samples_per_gpu` or `workers_per_gpu` is large. For SSD, it is `8*3`.

**Comment by XiaXuehai** [comment]
@xvjiarui ,but if I set 8*3, the gpu-util is low.

**Comment by xvjiarui** [comment]
Waiting for fork process.

**Comment by XiaXuehai** [comment]
16cores + 2* titanxp，samples=32, workers=8,  waiting 5 min, and training 6 min, does it normal？

**Comment by xvjiarui** [comment]
I am not sure if your hard drive will slow it down. 
More workers will load more images, and each worker has its own coco annotation copy. 
I suggest you validate less frequently and use fewer workers. You may try how many workers will be the best trade-off between GPU utilization and waiting time.
