### ISSUE TITLE
How to calculate AP30 for coco data set in MMdetection?

### ISSUE THREAD

**Issue by Wenting-Xu** [open-mmlab/mmdetection#3614]
Because my data set features are not obvious.The accuracy of the results after training is low, so I want to use AP10 and AP30 as the evaluation indicators.I have some problems after I modified the evaluation document.Can someone give me some advice?

**Comment by fengyouliang** [comment]
modify pycocotools/cocoeval.py 
```python
class Params:
    '''
    Params for coco evaluation api
    '''
    def setDetParams(self):
        self.imgIds = []
        self.catIds = []
        # np.arange causes trouble.  the data point on arange is slightly larger than the true value
        self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)
        self.recThrs = np.linspace(.0, 1.00, int(np.round((1.00 - .0) / .01)) + 1, endpoint=True)
        self.maxDets = [1, 10, 100]
        self.areaRng = [[0 ** 2, 1e5 ** 2], [0 ** 2, 32 ** 2], [32 ** 2, 96 ** 2], [96 ** 2, 1e5 ** 2]]
        self.areaRngLbl = ['all', 'small', 'medium', 'large']
        self.useCats = 1
```

**Comment by xvjiarui** [comment]
Hi @Wenting-Xu 
@fengyouliang 's answer is correct. You need to modify `pycocotools/cocoeval.py` to add 0.1 and 0.3 into `iouThrs`.
However, `mAP_10` and `mAP_30` may not reflect the accuracy of your detector since the iou threshold is too low...

**Comment by Wenting-Xu** [comment]
> modify pycocotools/cocoeval.py
> 
> ```python
> class Params:
>     '''
>     Params for coco evaluation api
>     '''
>     def setDetParams(self):
>         self.imgIds = []
>         self.catIds = []
>         # np.arange causes trouble.  the data point on arange is slightly larger than the true value
>         self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)
>         self.recThrs = np.linspace(.0, 1.00, int(np.round((1.00 - .0) / .01)) + 1, endpoint=True)
>         self.maxDets = [1, 10, 100]
>         self.areaRng = [[0 ** 2, 1e5 ** 2], [0 ** 2, 32 ** 2], [32 ** 2, 96 ** 2], [96 ** 2, 1e5 ** 2]]
>         self.areaRngLbl = ['all', 'small', 'medium', 'large']
>         self.useCats = 1
> ```

**Comment by Wenting-Xu** [comment]
> modify pycocotools/cocoeval.py
> 
> ```python
> class Params:
>     '''
>     Params for coco evaluation api
>     '''
>     def setDetParams(self):
>         self.imgIds = []
>         self.catIds = []
>         # np.arange causes trouble.  the data point on arange is slightly larger than the true value
>         self.iouThrs = np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)
>         self.recThrs = np.linspace(.0, 1.00, int(np.round((1.00 - .0) / .01)) + 1, endpoint=True)
>         self.maxDets = [1, 10, 100]
>         self.areaRng = [[0 ** 2, 1e5 ** 2], [0 ** 2, 32 ** 2], [32 ** 2, 96 ** 2], [96 ** 2, 1e5 ** 2]]
>         self.areaRngLbl = ['all', 'small', 'medium', 'large']
>         self.useCats = 1
> ```

thankes for you replay.i changed like this:
self.iouThrs = np.linspace(.1, 0.95, int(np.round((0.95 - .1) / .05)) + 1, endpoint=True)
but i got an error  like this:
Average Precision  (AP) @[ IoU=0.30      | area=   all | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
why i will got -1.00?

**Comment by MichaelXin** [comment]
You have to modify mmdet/dataset/coco.py as well.
