### ISSUE TITLE
Cannot run inference on GPU:1 in a two GPU setup

### ISSUE THREAD

**Issue by skeptomist** [open-mmlab/mmdetection#3615]
Following code:

`import convertCSV
import mmdet
from mmdet.apis import init_detector, inference_detector, show_result

if __name__ == '__main__':    
    model = init_detector('configMultiGPU.py', "model0.pth" , device='cuda:1')
    result = inference_detector(model, 'test.JPG')
    print(result[0])
(base) root@tensorflow-1-vm:/home/skeptomist/mmdetection/ALS/webAPI#`

Run with: CUDA_VISIBLE_DEVICES=0,1 python multiGPU-v5.py

Results in:

`Traceback (most recent call last):
  File "multiGPU-v5.py", line 7, in <module>
    result = inference_detector(model, 'test.JPG')
  File "/home/skeptomist/mmdetection/mmdet/apis/inference.py", line 66, in inference_detector
    return _inference_single(model, imgs, img_transform, device)
  File "/home/skeptomist/mmdetection/mmdet/apis/inference.py", line 93, in _inference_single
    result = model(return_loss=False, rescale=True, **data)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/base.py", line 78, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/two_stage.py", line 199, in simple_test
    x, img_meta, self.test_cfg.rpn) if proposals is None else proposals
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/test_mixins.py", line 10, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/skeptomist/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 218, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/skeptomist/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 83, in get_bboxes_single
    self.target_stds, img_shape)
  File "/home/skeptomist/mmdetection/mmdet/core/bbox/transforms.py", line 54, in delta2bbox
    gw = pw * dw.exp()
RuntimeError: binary_op(): expected both inputs to be on same device, but input a is on cuda:0 and input b is on cuda:1
`
Changing to device='cuda:0' works fine, without error.

GPU Setup is:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    60W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:00:05.0 Off |                    0 |
| N/A   73C    P0    77W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by fengyouliang** [comment]
```python
model = init_detector('configMultiGPU.py', "model0.pth" , device='cuda:0')
```
mmcv default use cuda:0, set model in cuda:0
or before `import mmdet` / `import mmcv`add 
```python
os.environ['CUDA_VISIBLE_DEVICES'] = 'x'  # x = 0, 1
```

**Comment by xvjiarui** [comment]
Hi @skeptomist 
Have you modified the code? 
Could you provide the snippets so that we could reproduce this bug?

**Comment by skeptomist** [comment]
> ```python
> model = init_detector('configMultiGPU.py', "model0.pth" , device='cuda:0')
> ```
> 
> mmcv default use cuda:0, set model in cuda:0
> or before `import mmdet` / `import mmcv`add
> 
> ```python
> os.environ['CUDA_VISIBLE_DEVICES'] = 'x'  # x = 0, 1
> ```

@xvjiarui Thanks for your quick reply.
I was running the program with: CUDA_VISIBLE_DEVICES=0,1 python multiGPU-v5.py
Does not achieve the same effect?
 Also what do you mean by "set model in cuda:0" - do I have to modify source code of mmcv to use different GPU?

**Comment by skeptomist** [comment]
@xvjiarui & @fengyouliang I have setup a new virtual machine :

sys.platform: linux
Python: 3.8.5 | packaged by conda-forge | (default, Aug 21 2020, 18:21:27) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0: Tesla K80
GCC: gcc (Debian 8.3.0-6) 8.3.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.1.1
MMDetection: 2.3.0+
MMDetection Compiler: GCC 8.3
MMDetection CUDA Compiler: 10.2

But when I run: python -c "from mmdet.apis import init_detector, inference_detector, show_result"

I get: ImportError: cannot import name 'show_result' from 'mmdet.apis' (/home/skeptomist/mmdetection/mmdet/apis/__init__.py)
(
