### ISSUE TITLE
Qusetion about new loss function

### ISSUE THREAD

**Issue by sky-fly97** [open-mmlab/mmdetection#3622]
Can someone tell me how to change smooth L1 loss to a new loss function? Like ciou loss....I always have problems that I can't solve.

**Comment by xvjiarui** [comment]
Hi @sky-fly97 
You may set `type=L1Loss` in your loss config.

**Comment by sky-fly97** [comment]
> Hi @sky-fly97
> You may set `type='L1Loss'` in your loss config.

Thanks, but will L1 loss perform better than smooth L1 loss? I use cascade cnn.
