### ISSUE TITLE
Passing image to detector gives "File name too long"

### ISSUE THREAD

**Issue by manybodycpa** [open-mmlab/mmdetection#3623]
I cloned the latest version yesterday. Looking at the webcam demo, I would expect to be able to pass an image grabbed from a video to the detector:

```
capture = cv2.VideoCapture(file_video_in)
rc = capture.grab()
if not rc: 
   continue

_, image = capture.retrieve()
res = inference_detector(model, image)
```

However, the image (array) is interpreted as a filename, leading to

`OSError: [Errno 36] File name too long '[[[ ...`

**Comment by xvjiarui** [comment]
Hi @manybodycpa 
It is a bug introduced by #3611 
We will fix it soon.

**Comment by Seiano** [comment]
I also have this problem and i try  List(), array, but no can work.
