### ISSUE TITLE
More stable results

### ISSUE THREAD

**Issue by rumusan** [open-mmlab/mmdetection#3624]
I found the mAP is unstable with several trials (~2mAP), even if under same seed. 

Some similar issues have been raised, however, I still cannot find a solution.

Many thanks!

**Comment by xvjiarui** [comment]
Hi @rumusan 
Which config are you using? 
The experiments on COCO is actually quite stable, the gap is usually less than 0.2 mAP.

**Comment by rumusan** [comment]
Yes, the standard COCO dataset is stable. I am working with some special datasets now. I just want to know if there are some solutions to get stable results with the same seed? As the seed seems to have no effect now.

**Comment by xvjiarui** [comment]
If the dataset is not balanced, the results will be unstable.
