### ISSUE TITLE
image_scale doesn't work in init_detector

### ISSUE THREAD

**Issue by nipeone** [open-mmlab/mmdetection#3626]
in config file,i set image_scale=(512,512) like below
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
```
when i use demo/image_demo.py to infer my image,i dynamically set image_scale to (1920,1200) like below 
```
    config='./configs/cascade_mask_rcnn_r101_fpn_1x_exp1.py'
    config = mmcv.Config.fromfile(config)
    # here image_scale is (512,512)
    config.test_pipeline[1].img_scale=(1920,1200)
    print(config.test_pipeline)
    # here image_scale is (1920,1200), i have checked it
    # build the model from a config file and a checkpoint file
    model = init_detector(config, checkpoint, device='cuda:0')
```

but the actual detection effect seems to be calculated by 512x512 resolution.

v1.1.0 has not the problem.
my current mmdetection release  is v2.3.0,

**Comment by xvjiarui** [comment]
Hi @nipeone 
You need to modify `config.test.test_pipeline[1]` since `config. test_pipeline` is just a intermediate variable. 
Please refer to [docs](https://mmdetection.readthedocs.io/en/latest/config.html#use-intermediate-variables-in-configs) for details.

**Comment by nipeone** [comment]
> Hi @nipeone
> You need to modify `config.test.test_pipeline[1]` since `config. test_pipeline` is just a intermediate variable.
> Please refer to [docs](https://mmdetection.readthedocs.io/en/latest/config.html#use-intermediate-variables-in-configs) for details.

thanks, it works, but should modify like this:    
```
config = mmcv.Config.fromfile(config)
config.data.test.pipeline[1].img_scale=[(1920,1200)]
```

**Comment by xvjiarui** [comment]
Hi @nipeone 
Yes. That's correct.
