### ISSUE TITLE
mmdetection stop in runner

### ISSUE THREAD

**Issue by zhmengyu01** [open-mmlab/mmdetection#3642]
i use 1 gpu to train coco dataset,if set workers_per_gpu=0, it can run normally, but if set workers_per_gpu > 0,it can not run normally and stoped like blow

![image](https://user-images.githubusercontent.com/60053055/91546644-5e314280-e955-11ea-8821-62f9b7668281.png)

my environment:
PyTorch: 1.5.1
TorchVision: 0.6.0a0+35d732a
OpenCV: 4.4.0
MMCV: 1.1.1
MMDetection: 2.3.0+
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1

**Comment by AllenPeng0209** [comment]
I got the same problem in mmdetection3d, how do you solve it? thanks
