### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3645]
Hi there, I install the latest mmDetectionv2.3 from the docker. Everything goes well in the docker building. However, the training cannot be successfully launched due to the following error:

**Traceback (most recent call last):
  File "./tools/train.py", line 8, in <module>
    import mmcv
  File "/opt/conda/lib/python3.7/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/__init__.py", line 29, in <module>
    from .env import collect_env
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/env.py", line 8, in <module>
    import cv2
  File "/opt/conda/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory**

I use the standard docker file provided by mmDetection (only add vim and tmux when building the docker):

**ARG PYTORCH="1.5"
ARG CUDA="10.1"
ARG CUDNN="7"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 tmux vim\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install MMCV
RUN pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html

# Install MMDetection
RUN conda clean --all
RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
WORKDIR /mmdetection
ENV FORCE_CUDA="1"
RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e .**

**Comment by HimariO** [comment]
I just encounter the same issue after building the docker image with the lastest Dockerfile. And I find out it can be solved by simply install the missing dependency with the following command:
`RUN apt-get install ffmpeg libsm6 libxext6 -y`

**Comment by shanggdlk** [comment]
> I just encounter the same issue after building the docker image with the lastest Dockerfile. And I find out it can be solved by simply install the missing dependency with the following command:
> `RUN apt-get install ffmpeg libsm6 libxext6 -y`

Great, it works. Thank you!

**Comment by RyanXLi** [comment]
This issue is stale and closed.
