### ISSUE TITLE
Question about learning rate config

### ISSUE THREAD

**Issue by sky-fly97** [open-mmlab/mmdetection#3647]
I used the cascade rcnn config, and my lr config is 
`lr_config = dict(policy='CosineAnealing', min_lr_ratio=0.01, by_epoch=False,warmup='linear', warmup_iters=500, warmup_ratio=1.0 / 3,)`
But I got this problem!
`Traceback (most recent call last):
  File "tools/train.py", line 174, in <module>
    main()
  File "tools/train.py", line 170, in main
    meta=meta)
  File "/data-output/mmdetection-master/mmdet/apis/train.py", line 108, in train_detector
    cfg.get('momentum_config', None))
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 412, in register_training_hooks
    self.register_lr_hook(lr_config)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 342, in register_lr_hook
    hook = mmcv.build_from_cfg(lr_config, HOOKS)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CosineAnealingLrUpdaterHook is not in the hook registry'`

**Comment by sky-fly97** [comment]
So can I use the CosineAnealing lr config? How can I use it correctly？

**Comment by shinya7y** [comment]
`CosineAnealing` -> `CosineAnnealing`
The typo is fixed in mmcv. https://github.com/open-mmlab/mmcv/pull/433

Please keep this issue open until the [config.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/config.md) is fixed.

**Comment by sky-fly97** [comment]
> `CosineAnealing` -> `CosineAnnealing`
> The typo is fixed in mmcv. [open-mmlab/mmcv#433](https://github.com/open-mmlab/mmcv/pull/433)
> 
> Please keep this issue open until the [config.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/config.md) is fixed.

Thanks! It works!!!

**Comment by sky-fly97** [comment]
> `CosineAnealing` -> `CosineAnnealing`
> The typo is fixed in mmcv. [open-mmlab/mmcv#433](https://github.com/open-mmlab/mmcv/pull/433)
> 
> Please keep this issue open until the [config.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/config.md) is fixed.

Hello, under the same configuration, I ran 18 epochs with the step [12,16] strategy, and then ran 18 epochs with the cos LR strategy, but the difference between the final results was 1.5 map@0.5. Can I ask whether cos  lr needs more epochs than step？

**Comment by shinya7y** [comment]
If we improved results easily, cos lr would be more popular in object detection.

The effects of epochs, lr, and min_lr (or min_lr_ratio) need to be verified experimentally.
Tuning the lr and step of stepLr is also needed for fair comparison.

**Comment by sky-fly97** [comment]
> If we improved results easily, cos lr would be more popular in object detection.
> 
> The effects of epochs, lr, and min_lr (or min_lr_ratio) need to be verified experimentally.
> Tuning the lr and step of stepLr is also needed for fair comparison.

Yes, it makes a lot of sense！
