### ISSUE TITLE
Can I pass a parameter without creating new config.py?

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#365]
For example, I have two types of gpu servers, one is 4gpus and another is 8. So I need to set two kinds of learning rate to fit one certain GPU, which doubles the number of config files.
Can I just pass the parameter using existing API? just like the way using `--set` in detectron?

**Comment by hellock** [comment]
This feature was considered before but not adopted. We will have new discussions about the config system.

**Comment by xiaoxiongli** [comment]
the config system is good now,  you can create two config file

**Comment by ZwwWayne** [comment]
Already supported by setting [`--options`](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L46)
