### ISSUE TITLE
unexpted error for `--format-only` when there is no ground truth in test json.

### ISSUE THREAD

**Issue by sr-frost** [open-mmlab/mmdetection#3651]
**Describe the bug**
I have a folder of images. First, I created a  json file that has all the fields including the ground truth `annotatoions`. At this stage, if I use the `--format-only`  option in `test.py` and I get expected results. 

Next, I created another json file that doesn't include the ground truth `annotations` field.  Again, I am trying to generate the model predictions using the `--format-only` command line option. But, this time I am getting list out of range error.

I think this is unexpected because `--format-only` shouldn't behave differently based on whether or not I have ground truth annotations.

**Reproduction**
1. What command or script did you run?
```
python tools/test.py 'my_config.py' \
'checkpoints/epoch_2.pth' \
--format-only \
--eval-options 'jsonfile_prefix=./test_results'
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I modified the config for my custom 1 class dataset.

3. What dataset did you use?
A custom 1 class dataset.

**Error traceback**
If applicable, paste the error trackback here.
```
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/test.py", line 197, in <module>
    main()
  File "tools/test.py", line 186, in main
    dataset.format_results(outputs, **kwargs)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 361, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 292, in results2json
    if isinstance(results[0], list):
IndexError: list index out of range
```

**Comment by xvjiarui** [comment]
Hi @sr-frost 
Sorry for the late reply. 
You may follow COCO style [here](https://cocodataset.org/#download) to create a test json.

**Comment by wong1998** [comment]
i don't know how to test the images without GT by mmdetection.the config in the mmdetection all use the val.json to test!!
so how can i test the images without the json file(because it does't have the GT!!!!!!)

**Comment by aixiaodewugege** [comment]
Does is solved?
