### ISSUE TITLE
How to set update-frequency > 1

### ISSUE THREAD

**Issue by kkissmart** [open-mmlab/mmdetection#3652]
Due to number of GPU and GPU, I can't have large batch size. Is there an arg that I can set that I run multiple forward and then update the parameters with an average gradient from these multiple forward steps?

I am new here. any help is appreciate!

Thanks

**Comment by ZwwWayne** [comment]
Hi @kkissmart ,
Currently MMDetection do not support this feature. We may support that in the future. For now, you can set with_cp=True in the backbone or adjust your learning rates with small batch sizes.
