### ISSUE TITLE
How to get gt_bboxes and gt_labels annotations during testing?

### ISSUE THREAD

**Issue by naimple** [open-mmlab/mmdetection#3653]
This is useful in some ablation studies. For example, to verify the upper bound performance of bbox regression branch, we can replace the anchors with `gt_bboxes`.

Since in testing mode the detector doesn't receive `gt_bboxes` and `gt_labels`, I tried to add `return_loss=True` in <https://github.com/open-mmlab/mmdetection/blob/f93c00fd05b50cd3903c964599efb7eb9fd354ea/mmdet/apis/test.py#L26> and input the annotations in the same line, but the detector with `training mode` only returns losses and doesn't return detection results as I expected. I have to modify the detector to output detection results in `training mode`.

Is there cheaper way of feeding annotations to the detector during testing?

**Comment by ZwwWayne** [comment]
You need to modify the config of pipeline, e.g., add `gt_labels` and `gt_bboxes` in [this line](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/datasets/coco_detection.py#L27) as [the line for training](https://github.com/open-mmlab/mmdetection/blob/f93c00fd05b50cd3903c964599efb7eb9fd354ea/configs/_base_/datasets/coco_detection.py#L13).

**Comment by abcxs** [comment]
Where do you plan to change to get a good result

**Comment by mathshangw** [comment]
excuse me i tried this solution and got the result with this form 
`[array([[3.43202576e+02, 2.43713760e+01, 4.96343414e+02, 3.32774170e+02, 8.81948233e-01],`
`[4.71771484e+02, 1.72076767e+02, 4.93474548e+02, 2.18293701e+02,5.77966988e-01],`
`[4.71194794e+02, 1.73165421e+02, 5.15258850e+02, 2.17751862e+02, 4.02466476e-01], ....`

i need to get
x1, y1, x2, y2, class_id, bbox_score
