### ISSUE TITLE
Training error on CornerNet

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3654]
Hi, I kick off CornerNet to train my local dataset. However, it reports an error below:

  **File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/models/backbones/hourglass.py", line 77, in forward
    return up1 + up2
RuntimeError: The size of tensor a (13) must match the size of tensor b (14) at non-singleton dimension 3

  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/models/backbones/hourglass.py", line 77, in forward
    return up1 + up2
RuntimeError: The size of tensor a (95) must match the size of tensor b (96) at non-singleton dimension 3**

Could you give me some suggestions?

Thanks!

**Comment by ZwwWayne** [comment]
Hi @shanggdlk ,
What is the input size of your model? Could you follow the `reimplementation issues` to provide more details?
