### ISSUE TITLE
multi-machine multi-gpu training won't start using slurm_train.sh script on CNGrid

### ISSUE THREAD

**Issue by HawkRong** [open-mmlab/mmdetection#3655]
**Describe the bug**
I tried to launch multi-node multi-gpu training on a cluster (CNGRID) managed by slurm, using the script 'slurm_train.sh'; however, the training stuck at the early step of loading pretrained backbone network weights. When I look into the nodes that slurm allocated to me, I found all gpus' util rates are 0% and only gpu0's memory usage reached about 1gb while others' barely used; using 'top', I found a python process was created on each node and it gave 100% cpu usage.
What was possibly happening?

**Reproduction**
1. What command or script did you run?
slurm_train.sh
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No.
3. What dataset did you use?
coco2017

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
I use mmdetection 1.0, so the information collection script is not there.
The information collected with pytorch's script is as below:
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 440.64.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.0
[pip] torch==1.4.0
[pip] torchvision==0.4.0a0
[conda] _pytorch_select 0.2 gpu_0 defaults
[conda] blas 1.0 mkl defaults
[conda] mkl 2019.4 243 defaults
[conda] mkl-service 2.3.0 py37he904b0f_0 defaults
[conda] mkl_fft 1.0.15 py37ha843d7b_0 defaults
[conda] mkl_random 1.1.0 py37hd6b4f25_0 defaults
[conda] pytorch 1.2.0 cuda100py37h938c94c_0 defaults
[conda] torch 1.4.0 pypi_0 pypi
[conda] torchvision 0.4.0 cuda100py37hecfc37a_0 defaults

**Error traceback**
No.

**Bug fix**
No.

**Comment by ZwwWayne** [comment]
Hi @HawkRong ，
If the training stuck at downloading pre-trained models, you can download the model first through single gpu training, or download the weights manually through links in [this file](https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json).

**Comment by HawkRong** [comment]
@ZwwWayne Hello. I have the weight file in the correct folder and single-machine multi-gpu training went well, so I think the issue is specific to multi-node training. Any insight?

**Comment by hellock** [comment]
We can hardly help with this. It's difficult to diagnose the errors on some specific environment that we cannot access or not familiar. For reference, we tried on our own cluster with 2 nodes or 4 nodes, and it just works fine.
