### ISSUE TITLE
mmcv.ops.nms.batched_nms

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3657]
![image](https://user-images.githubusercontent.com/42128459/91676403-4a165c80-eb72-11ea-95be-c87d9172982b.png)
Don't understand the use of  `eval('nms')`
What does eval mean?
Thank you!

**Comment by xvjiarui** [comment]
Hi @zhjw0927 
[Here](https://docs.python.org/3/library/functions.html#eval) is the doc of `eval`. 
It makes the string into an op.
