### ISSUE TITLE
running test fcos, error occurred

### ISSUE THREAD

**Issue by zhjw0927** [open-mmlab/mmdetection#3659]
running test fcos using pretrained model, eval metric is zero.
![image](https://user-images.githubusercontent.com/42128459/91680580-42f54b80-eb7e-11ea-9b31-a7cf8b24584a.png)
have suggestions?

**Comment by RyanXLi** [comment]
Hi! I verified with the same command and there is no problem. The mAP is 36.2 as reported in the model zoo. Please try again and also check your dataset. Meanwhile, make sure you have not accidentally edited the config and checkpoint file. Thanks.
