### ISSUE TITLE
what's the test results pickle format?

### ISSUE THREAD

**Issue by kinredon** [open-mmlab/mmdetection#366]
I have trained a model, and then I use test my test data with command:

`python tools/test.py <CONFIG_FILE> <CHECKPOINT_FILE> --gpus <GPU_NUM> --out <OUT_FILE>`

in the `<OUT_FILE>`, how to figure out the bounding box corresponding to its image file?

**Comment by anirudh-chakravarthy** [comment]
Hi,

Were you able to figure this out?
