### ISSUE TITLE
add iamges to tensorboard

### ISSUE THREAD

**Issue by FancyRay** [open-mmlab/mmdetection#3664]
i wonder how to add images to tensorboard while training and where to find image tensor.

**Comment by RyanXLi** [comment]
Hi! You need to pass the image object to output and edit the Tensorboard hook. For details please reference [this issue](https://github.com/open-mmlab/mmdetection/issues/231).

**Comment by FancyRay** [comment]
> Hi! You need to pass the image object to output and edit the Tensorboard hook. For details please reference [this issue](https://github.com/open-mmlab/mmdetection/issues/231).

Thanks. But i do not know where to get the image object while training.

**Comment by RyanXLi** [comment]
Check this [comment](https://github.com/open-mmlab/mmdetection/issues/231#issuecomment-633072220) please.
