### ISSUE TITLE
Question on RepeatDataset

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3668]
Hi, I just have 2 very basic questions on ```RepeatDataset```:

1. Is it possible to have 2 different ```train_pipeline``` for the different datasets, so that the datasets have different augmentation strategies applied to them. So, something like:
```
dataset_A_train = dict(
    type='RepeatDataset',
    times=1,
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/annotations.json',
        img_prefix=data_root + 'train2019/',
        pipeline=train_pipeline_A
    )
dataset_B_train = dict(
    type='RepeatDataset',
    times=2,
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/annotations.json',
        img_prefix=data_root + 'train2019/',
        pipeline=train_pipeline_B
    )
```
2. When we use ```RepeatDataset```, do the images from one dataset get fed to the model first followed by the second dataset or does the order of the images get mixed?

Thanks!

**Comment by ZwwWayne** [comment]
1. Yes, you can use `ConcatDataset` to concat these two repeat dataset following [here](https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html#concatenate-dataset).
2. The order of the images get mixed because we use RandomSampler.
