### ISSUE TITLE
Small dense object detection using Mask R-CNN - hyperparameter suggestions

### ISSUE THREAD

**Issue by ecm200** [open-mmlab/mmdetection#3669]
I was wondering if there were suggestions people could make to with regards to hyperparameter settings of the RPN and ROI align parts of the network that might improve many small object detection performance?

My ideas on how to achieve this include:

1. Reduce RPN anchor sizes.
2. Increase number of anchors to be used since the objects are small and can be found anywhere on an image.
3. Increase maximum number of predicted objects since an image can contain 300 or more objects.
4. Increase the number of region proposals during training.
5. Reduce mask threshold probability from 0.5 setting it lower to say 0.35 to help in the detection of small object boundaries.

From my understanding of the implementation, these are the places to achieve the above suggestions.

I would be really grateful if people could point out issues with my ideas and suggestions of how to achieve the stated objective, amend or suggest new ones etc.

### 1. Reduce RPN anchor sizes:

One suggestion I have seen that the **scales** parameter of the **RPN network** being changed from the default 8, to a range, say [4,8,16,32,64], perhaps as high as 256.

_**Q. Would this have the desired outcome of reducing the size of the anchors of the RPN network?**_

```python
rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[4,8,16,32,64], # default is [8]
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0))
```

### 2. Increase the number of RPN anchors used:

Under the **training_cfg** object in the cfg file, the following settings control the number of anchors.

**_Q. What are the differences between **nms_post** and **max_num**?_**

**_Q. Would increasing these result in more anchors?_**

```python
rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0)
```

### 3. Increasing number of objects detected:

This achieved by changing the **max_per_image** in the **test_cfg** section of the configuration file.
Default is 100, so I thought raising to 300 or even 500 as a good start.

``` python
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_thr=0.5),
        max_per_img=100,
        mask_thr_binary=0.5))
```

### 4. Increase the number of region proposals during training:

How is the number of region proposals during training modified?
Have I got these confused above with the anchors proposal?

```python

```

### 5. Reduce object detection probability:

This is set by parameter **mask_thr_binary** in the **test_cfg** section.
Default is 0.5, so thinking of dropping to 0.35 to improve small object detection.

```python
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_thr=0.5),
        max_per_img=100,
        mask_thr_binary=0.5))
```

**Comment by ZwwWayne** [comment]
All the ideas make sense.
For point 4, you can modify `nms_pre`, `nms_post`, and `max_num`  in the train_cfg.rpn to greater numbers.
