### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.ops.nms.gpu_nms'

### ISSUE THREAD

**Issue by DemonProfessor** [open-mmlab/mmdetection#367]
when i run the test.py, i got this error:
(pc-test) dh@dh:~/mmdetection$ python test_img.py 
Traceback (most recent call last):
  File "test_img.py", line 3, in <module>
    from mmdet.models import build_detector
  File "/home/dh/mmdetection/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/dh/mmdetection/mmdet/models/backbones/__init__.py", line 1, in <module>
    from .resnet import ResNet
  File "/home/dh/mmdetection/mmdet/models/backbones/resnet.py", line 9, in <module>
    from mmdet.ops import DeformConv, ModulatedDeformConv
  File "/home/dh/mmdetection/mmdet/ops/__init__.py", line 5, in <module>
    from .nms import nms, soft_nms
  File "/home/dh/mmdetection/mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "/home/dh/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 4, in <module>
    from .gpu_nms import gpu_nms
ModuleNotFoundError: No module named 'mmdet.ops.nms.gpu_nms'

The envs:
python 3.6
cuda 10.1
pytorch 1.0
no problems in ./compile.sh and setup.py install

**Comment by Yuyang-01** [comment]
i also have the error :No module named 'mmdet.ops.nms.gpu_nms'

**Comment by hellock** [comment]
Under the `mmdet/ops/nms` folder, there should be some .so files, is there any?

**Comment by Yuyang-01** [comment]
yes,there is 3 files named gpu_nms.cpython-35m-x86_64-linux-gnu.so,   cpu_nms.cpython-35m-x86_64-linux-gnu.so,   cpu_soft_nms.cpython-35m-x86_64-linux-gnu.so

**Comment by hellock** [comment]
When compiling the nms op, your python version is 3.5, but when running, it is 3.6.

**Comment by Yuyang-01** [comment]
In the mmdetection project, the file INSTALL.md says, the requirement is Python 3.4+  and   PyTorch 1.0.  My environment is  Python 3.5  and   PyTorch 1.0

**Comment by hellock** [comment]
So it's just a typo in your first comment?

**Comment by hellock** [comment]
You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.

**Comment by DemonProfessor** [comment]
thanks for ur reply, it's because there is a error when i run the compile.sh. An error about nvcc causes  this problem. I solved it by add cuda-path to my envs and then the script works. thks for your wonderful work~

> You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.

**Comment by Markovcom** [comment]
@hellock Building nms op...
rm -f *.so
echo "Compiling nms kernels..."
Compiling nms kernels...
python setup.py build_ext --inplace
running build_ext
building 'cpu_nms' extension
gcc -pthread -B /home/wangxijun/anaconda2/envs/mmdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include -I/home/wangxijun/anaconda2/envs/mmdet/include/python3.7m -c cpu_nms.cpp -o build/temp.linux-x86_64-3.7/cpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:0,
                 from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_nms.cpp:638:
/home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
g++ -pthread -shared -B /home/wangxijun/anaconda2/envs/mmdet/compiler_compat -L/home/wangxijun/anaconda2/envs/mmdet/lib -Wl,-rpath=/home/wangxijun/anaconda2/envs/mmdet/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/cpu_nms.o -o /home/wangxijun/zhoulm/code/mmdetection/mmdet/ops/nms/cpu_nms.cpython-37m-x86_64-linux-gnu.so
building 'cpu_soft_nms' extension
gcc -pthread -B /home/wangxijun/anaconda2/envs/mmdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include -I/home/wangxijun/anaconda2/envs/mmdet/include/python3.7m -c cpu_soft_nms.cpp -o build/temp.linux-x86_64-3.7/cpu_soft_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:0,
                 from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_soft_nms.cpp:638:
/home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
cpu_soft_nms.cpp: In function ‘PyObject* __pyx_pf_12cpu_soft_nms_cpu_soft_nms(PyObject*, PyArrayObject*, float, unsigned int, float, float)’:
cpu_soft_nms.cpp:2493:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
cpu_soft_nms.cpp:3004:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
g++ -pthread -shared -B /home/wangxijun/anaconda2/envs/mmdet/compiler_compat -L/home/wangxijun/anaconda2/envs/mmdet/lib -Wl,-rpath=/home/wangxijun/anaconda2/envs/mmdet/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/cpu_soft_nms.o -o /home/wangxijun/zhoulm/code/mmdetection/mmdet/ops/nms/cpu_soft_nms.cpython-37m-x86_64-linux-gnu.so
building 'gpu_nms' extension
gcc -pthread -B /home/wangxijun/anaconda2/envs/mmdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include -I/home/wangxijun/anaconda2/envs/mmdet/include/python3.7m -c gpu_nms.cpp -o build/temp.linux-x86_64-3.7/gpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:0,
                 from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:640:
/home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
nvcc -I/home/wangxijun/anaconda2/envs/mmdet/lib/python3.7/site-packages/numpy/core/include -I/home/wangxijun/anaconda2/envs/mmdet/include/python3.7m -c nms_kernel.cu -o build/temp.linux-x86_64-3.7/nms_kernel.o -c --compiler-options -fPIC
unable to execute 'nvcc': No such file or directory
error: command 'nvcc' failed with exit status 1
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
I meet the same problem,

**Comment by hellock** [comment]
@Markovcom `unable to execute 'nvcc': No such file or directory` This is a cuda path error.

**Comment by XiaYuanxiang** [comment]
> You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.

when import gpu_nms，it report 
gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaFree
how to solve it

**Comment by Smoothing97** [comment]
> > You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.
> 
> when import gpu_nms，it report
> gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaFree
> how to solve it

Maybe cuz error in your compile stage,I mean when you compile gpu_nms.cpython-36m-x86_64-linux-gnu.so,there is some cuda error.：）

**Comment by Smoothing97** [comment]
> > You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.
> 
> when import gpu_nms，it report
> gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaFree
> how to solve it

sorry but I have this problem now,could you please share some experiences?Really need some help!

**Comment by XiaYuanxiang** [comment]
> > > You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.
> > 
> > 
> > when import gpu_nms，it report
> > gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaFree
> > how to solve it
> 
> sorry but I have this problem now,could you please share some experiences?Really need some help!

change CUDA from 9.2 to 9.0 solve my problem

**Comment by kevin-ssy** [comment]
Met the same issue. A quick solution to this problem is to include cuda into your PATH:

`export PATH=/usr/local/cuda/bin/$PATH`

**Comment by harryhan618** [comment]
> > > You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.
> > 
> > 
> > when import gpu_nms，it report
> > gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaFree
> > how to solve it
> 
> sorry but I have this problem now,could you please share some experiences?Really need some help!

Did you solve the problem? 
I successfully compile the nms module, but `undefined symbol: cudaFree` occurs when I want to import it.
My cuda version is 9.0 and in python environment, cudatoolkit version is 9.0 as well.

**Comment by harryhan618** [comment]
> > > > You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.
> > > 
> > > 
> > > when import gpu_nms，it report
> > > gpu_nms.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaFree
> > > how to solve it
> > 
> > 
> > sorry but I have this problem now,could you please share some experiences?Really need some help!
> 
> Did you solve the problem?
> I successfully compile the nms module, but `undefined symbol: cudaFree` occurs when I want to import it.
> My cuda version is 9.0 and in python environment, cudatoolkit version is 9.0 as well.

I got it. `gpu_nms` cannot be imported standalone. `torch` should get imported first.

**Comment by memeda2232** [comment]
i got the same problem. i see mmdet/ops/nms ,there only two .so .lost gpu_nms.cpython-37m-x86_64-linux-gnu.so

**Comment by hellock** [comment]
@harryhan618 @memeda2232  Have you updated to the latest version? The NMS op have been replaced and there should be no `gpu_nms.xxx.so`. The compiling issue should have been fixed.

**Comment by Superfly12138** [comment]
I fixed by add this
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib
export PATH=$PATH:/usr/local/cuda/bin
```
to .bashrc file.

**Comment by HappyPeanuts** [comment]
> You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.

The paskage 'mmdet.ops'  not in my project, what should I do, could you please send me your package? Looking forward to your reply! My Email is 2197951460@qq.com

**Comment by HappyPeanuts** [comment]
> You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.

I have resoluved nms problems, but i found a new error, this is no .so files im my dcn package, so, can you send me your .so file about deform_conv_cuda and so on... 

![image](https://user-images.githubusercontent.com/57491808/127265136-5900ab75-434e-4bc2-a949-171315a94c2a.png)

**Comment by J5DSM** [comment]
> > You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.
> 
> The paskage 'mmdet.ops' not in my project, what should I do, could you please send me your package? Looking forward to your reply! My Email is [2197951460@qq.com](mailto:2197951460@qq.com)

i have met the same problem,thers is no mmet/ops file. Did you sovle it?i would be appreciated if you could tell me how to sovel it.

**Comment by HappyPeanuts** [comment]
&nbsp;I have try it, but it's no use. i found it is because of the lost of *.so file,so i will try other methods, thank you for you help.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月31日(星期六) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] ModuleNotFoundError: No module named 'mmdet.ops.nms.gpu_nms' (#367)





   
You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the mmdet/ops/nms directory and import gpu_nms.
  
The paskage 'mmdet.ops' not in my project, what should I do, could you please send me your package? Looking forward to your reply! My Email is ***@***.***
  
i have met the same problem,thers is no mmet/ops file. Did you sovle it?i would be appreciated if you could tell me how to sovel it.

**Comment by lukestruggle** [comment]
> You can try opening a python interpreter in the root directory (the directory in which compile.sh is) and import mmdet to see what's the error message. Then you can enter the `mmdet/ops/nms` directory and import gpu_nms.
ImportError:  AugFPN-master/mmdet/ops/nms/gpu_nms.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaLaunchKernel

**Comment by yuy01** [comment]
你好，邮件已收到。这是来自QQ邮箱的自动回复邮件。
