### ISSUE TITLE
UserWarning: The old API of register_module(module, force=False) is deprecated

### ISSUE THREAD

**Issue by liyiwei979621500** [open-mmlab/mmdetection#3671]
I clone and install the lastest mmdet today.
When I start training, this warning keeps showing up which is quite annoying.
How to disable this warning?
Thanks！

![image](https://user-images.githubusercontent.com/16919236/91931176-4cfd8280-ed15-11ea-9697-865c2156ecdb.png)

**Comment by ZwwWayne** [comment]
Hi @liyiwei979621500 ，
Which config or model are you using? This is because some old-style usage of registry like `xxx@register_module`, use `xxx@register_module()` could fix this.

**Comment by liyiwei979621500** [comment]
thanks, @ZwwWayne I'm using retinanet

```
_base_ = [
    '../../_base_/models/retinanet_r50_fpn.py',
]

model = dict(bbox_head=dict(num_classes=1))
```
Are these warnings caused by sabl？I'm not using them. 

![image](https://user-images.githubusercontent.com/16919236/92066963-b644ca80-edd5-11ea-97be-1cd3ef2bbbbe.png)
