### ISSUE TITLE
TypeError: getCatIds() got an unexpected keyword argument 'cat_names' AND subprocess.CalledProcessError:

### ISSUE THREAD

**Issue by nianjiuhuiyi** [open-mmlab/mmdetection#3673]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I ran the command "python tools/train.py  configs/retinanet/retinanet_x101_32x4d_fpn_1x_coco.py" on a single GPU, it worked fine.
But when I trained with two Gpus running the command  
"./tools/dist_train.sh  configs/retinanet/retinanet_x101_64x4d_fpn_1x_coco.py  2", it made the following error.
I have looked for these problems and made some attempts, but failed to solve them. Please help me, thank you

**Reproduction**
1. What command or script did you run?
```
./tools/dist_train.sh  configs/retinanet/retinanet_x101_64x4d_fpn_1x_coco.py  2
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?
COCO2014
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1: GeForce RTX 2080 Ti
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0
OpenCV: 3.4.2
MMCV: 1.0.5
MMDetection: 2.3.0+unknown
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.2

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    pip
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
total_epochs = 12
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/retinanet_x101_64x4d_fpn_1x_coco'
gpu_ids = range(0, 1)

2020-09-02 22:20:08,346 - mmdet - INFO - load model from: open-mmlab://resnext101_64x4d
loading annotations into memory...
loading annotations into memory...
Done (t=10.19s)
creating index...
index created!
Traceback (most recent call last):
  File "./tools/train.py", line 154, in <module>
    main()
  File "./tools/train.py", line 129, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/songhui/projects/mmdetection-master/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/root/root/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/songhui/projects/mmdetection-master/mmdet/datasets/custom.py", line 82, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/songhui/projects/mmdetection-master/mmdet/datasets/coco.py", line 47, in load_annotations
    self.cat_ids = self.coco.getCatIds(cat_names=self.CLASSES)
TypeError: getCatIds() got an unexpected keyword argument 'cat_names'
Done (t=12.23s)
creating index...
index created!
Traceback (most recent call last):
  File "./tools/train.py", line 154, in <module>
    main()
  File "./tools/train.py", line 129, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/songhui/projects/mmdetection-master/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/root/root/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/songhui/projects/mmdetection-master/mmdet/datasets/custom.py", line 82, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/songhui/projects/mmdetection-master/mmdet/datasets/coco.py", line 47, in load_annotations
    self.cat_ids = self.coco.getCatIds(cat_names=self.CLASSES)
TypeError: getCatIds() got an unexpected keyword argument 'cat_names'
Traceback (most recent call last):
  File "/root/root/anaconda3/envs/mmdetection/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/root/anaconda3/envs/mmdetection/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/root/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/root/root/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/root/anaconda3/envs/mmdetection/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/retinanet/retinanet_x101_64x4d_fpn_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Which `pycocotools` are you using? You may try uninstall the `pycocotools` in the environment and make sure there is no `pycocotools` in the environment first and then install through `pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"`

**Comment by nianjiuhuiyi** [comment]
Thank you for your reply. 
But in the beginning, I used # single-GPU testing in "getting_started.md", and I had this "getCatIds()" error.  Then I searched for the problem, and It was solved by  uninstall the pycocotools in the environment and then install through pip install "git+https://github.com/open-mmlab/cocoapi.git#subdirectory=pycocotools"
When I execute # single-GPU testing in "getting_started.md" again,My problem is solved,everything is OK.

But when I use  # multi-gpu testing  in "getting_started.md", The above error occurs, and  another error named 'subprocess.CalledProcessError' has also been occured.

**Comment by ZwwWayne** [comment]
Which multi-gpu testing command are you using? Could you provide a one for us to reproduce this error?

**Comment by nianjiuhuiyi** [comment]
`./tools/dist_train.sh configs/retinanet/retinanet_x101_64x4d_fpn_1x_coco.py 2`
I tried this command again today, and it was still the same error.
In "Describe the bug", I wrote down the commands I used in detail

**Comment by ZwwWayne** [comment]
Do you have multiple version of MMDetection in your environment? In the error report you show that your mmdetection version is v2.3.0+known. However, from the error message, the real mmdet you are using is not because the line of code that throws error
```
  File "/home/songhui/projects/mmdetection-master/mmdet/datasets/coco.py", line 47, in load_annotations
    self.cat_ids = self.coco.getCatIds(cat_names=self.CLASSES)
```
is different from the v2.3.0 code [here](https://github.com/open-mmlab/mmdetection/blob/v2.3.0/mmdet/datasets/coco.py#L47).
It should be 
```python
        self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
```

**Comment by nianjiuhuiyi** [comment]
Thank you for your patient reply. There may be some problems with my version.Now I can use a single GPU for training, but the problem of multiple Gpus still exists. After there is enough time, I will try to deal with it thoroughly and see if it is the version problem.

**Comment by nianjiuhuiyi** [comment]
I deleted everything from my MMdetection, including the environment it relies on.And I downloaded mmdetection-2.4.0, and reinstalled its environment dependencies.Then all the problems will be solved.
