### ISSUE TITLE
Anchor box calculation and configuratoin

### ISSUE THREAD

**Issue by PawelFaron** [open-mmlab/mmdetection#3675]
Is there some way in mmdetection to calculate anchor boxes  for my COCO like dataset (k-means or something similar)?
Probably too much to ask but also some example of how to configure anchor boxes would be very helpful?

**Comment by ZwwWayne** [comment]
Currently, MMDetection does not provide such tools. We may support this feature in the future. PRs are welcomed.

**Comment by PawelFaron** [comment]
@ZwwWayne thanks for the info. I will start working on tools for my project. If I come up with something useful I will create PR.
