### ISSUE TITLE
Pretrain model cannot get results

### ISSUE THREAD

**Issue by zhangzishuo123** [open-mmlab/mmdetection#3678]
I want to test faster rcnn with pretrain model. It can't detect anything, but only show the original image.
I tried as follow:
python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py models/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --show

**Comment by v-qjqs** [comment]
Hi @zhangzishuo123 , does this [page](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md) help? Make sure you load pretrained model from the correct path, or will decrease the arguments 'show-score-thr' help?

**Comment by zhangzishuo123** [comment]
@v-qjqs Thanks for reply! I download pretrained model from configs/faster_rcnn/README.md. I also tried to change 'score_thr' to 0.05 in show_result, but it still can't detect anything. If there are other ways that I can do?

**Comment by v-qjqs** [comment]
Hi, is there any mismatch (e.g. unexpected or missing keys) between your model and loaded state dict.
