### ISSUE TITLE
Able to see proposals

### ISSUE THREAD

**Issue by tiberium24** [open-mmlab/mmdetection#3683]
Hello,

Is it possible to see RPN proposals in mmdetection? I am referring to this: https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb. We can see the final detection results only for now.

**Comment by yhcao6** [comment]
Sorry, there is no direct API to visualize the intermediate RPN proposal of faster rcnn. But you can make minor change to do that.
1. add `return proposals_list` in line 197
https://github.com/open-mmlab/mmdetection/blob/73ebc5223a2bb7ee358961ed235b82fcf3b8b316/mmdet/models/detectors/two_stage.py#L193-L197
2. modify demo/image_demo.py  as follows:
change 
https://github.com/open-mmlab/mmdetection/blob/73ebc5223a2bb7ee358961ed235b82fcf3b8b316/demo/image_demo.py#L20-L22
to
```
    result = inference_detector(model, args.img).cpu().numpy()
    from mmcv import imshow_bboxes
    imshow_bboxes(args.img, result, out_file='test.jpg', show=False)
```

**Comment by tiberium24** [comment]
Thank you very much. May I also ask you what exactly the dimensions of proposals in proposal list refer to? Is it for the original image?

**Comment by yhcao6** [comment]
Proposals list is a list of proposals of each image, i.e., proposals_list[0] is the proposal of imgs[0].
The coordinate refers to the image after pre-processing (the processing includes rescale, pad) instead of the original image.

**Comment by yarkable** [comment]
Thanks！

**Comment by Soodep** [comment]
> Sorry, there is no direct API to visualize the intermediate RPN proposal of faster rcnn. But you can make minor change to do that.
> 
> 1. add `return proposals_list` in line 197
>    https://github.com/open-mmlab/mmdetection/blob/73ebc5223a2bb7ee358961ed235b82fcf3b8b316/mmdet/models/detectors/two_stage.py#L193-L197
> 2. modify demo/image_demo.py  as follows:
>    change
>    https://github.com/open-mmlab/mmdetection/blob/73ebc5223a2bb7ee358961ed235b82fcf3b8b316/demo/image_demo.py#L20-L22
>    
>    to
> 
> ```
>     result = inference_detector(model, args.img).cpu().numpy()
>     from mmcv import imshow_bboxes
>     imshow_bboxes(args.img, result, out_file='test.jpg', show=False)
> ```
I tried this with "python demo/image_demo.py demo/car.jpg     configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py     checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth" and it gives me error AttributeError: 'Tensor' object has no attribute 'gpu'. 
how to run this with gpu

**Comment by TuanNguyenSKKU** [comment]
> the processing includes rescale, pad
hello @yhcao6 
How to show proposals in the original image? 
Thank you very much.

**Comment by TuanNguyenSKKU** [comment]
hello @yhcao6 
How to show proposals in the original image?
Thank you very much.
