### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError

### ISSUE THREAD

**Issue by luoyixin2019** [open-mmlab/mmdetection#3689]
Hi, I encountered a error about 'PicklingError' when I run my deepsnake model train code written by mmdet.
`_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError`
![K0GI$GEZ_T$K6ZOU{{B7VQ9](https://user-images.githubusercontent.com/49396177/92213457-2894d800-eec6-11ea-9126-a9686aab10c4.png)

The dataset I used is iSAID, and I have run some instance segment baseline on iSAID dataset with mask rcnn in mmdetection.

I checked the related issues, which suggested me to add "to_float32=True" in config file. I did, but it not work.

As deepsnake is a counter-based instance segment model, I add 'poly2mask=False' in train_pipeline-LoadAnnotations, to get the polygon annotation instead of bitmap of mask. It can successfully run on COCO dataset(without add "to_float32=True"), but failed when changed to iSAID dataset(even add "to_float32=True").

Thanks a lot!

the env I used is:

sys.platform: linux
Python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1,2,3: GeForce RTX 2080 Ti
GPU 4,5,6,7: TITAN Xp
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.0.5
MMDetection: 2.3.0+c31df74
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.2

**Comment by yhcao6** [comment]
Can you run again with 1GPU and set `worker_per_gpu = 0` in the config?

**Comment by luoyixin2019** [comment]
> Can you run again with 1GPU and set `worker_per_gpu = 0` in the config?

Thanks for your attention. I change the config as you said, the error change to be
`numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'`

![I21% Q(X_H5C0R@8 VXYT}C](https://user-images.githubusercontent.com/49396177/92217461-4bc18680-eeca-11ea-8075-773ec9869680.png)

It seems that such bug come from resize precess?

**Comment by luoyixin2019** [comment]
As I have spilt my isaid dataset to size of 800*800, resize process should be unnecessary. So I notes the resize config code.
`#dict(type='Resize', img_scale=(800, 800), keep_ratio=True),   ### `
Then the model can run successfully.
