### ISSUE TITLE
Finished processing dependencies for mmdet==0.6rc0+unknown

### ISSUE THREAD

**Issue by Hesene** [open-mmlab/mmdetection#369]
Thank you for your sharing.
I meet some problem,Why is my mmdet version is =0.6rc0+unknown，what is the ''unknow''means?
and when I run the test.py, it will appear
 ‘’ImportError: /home/vvv/jh/mmdetectionV1/mmdet/ops/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration ‘’ 
My environment is 
ubuntu18.04, cuda10, cudnn7.4.1, torch1.0 
Thank you for your answer！！！

**Comment by hellock** [comment]
The "unknown" means the git commit id cannot be retrieved, normally it will be the git id and it is convenient to know the exact version. Are you using `git clone` to clone the repo to your local disk?

The cuda error looks like a version mismatch. You may have multiple cuda versions installed or the pytorch version does not match with your cuda version.
(#66, #48)
