### ISSUE TITLE
Dynamic loss scale support for fp16 traing.

### ISSUE THREAD

**Issue by halostorm** [open-mmlab/mmdetection#3690]
**Description**
Loss scale is set as 512 default for fp16 training, which can sometimes cause gradient overflow. So I think dynamic loss scale is necessary. 
Then  I migrated this feature from Apex and add to hook.py. Maybe you can merge it.
https://github.com/halostorm/mmdetection/blob/ab8b273e2fb9273e5659d0fce36afb476fe87638/mmdet/core/fp16/hooks.py#L38

**Comment by xvjiarui** [comment]
Hi @halostorm 
Thanks for your suggestion. You may open create a PR for it.
