### ISSUE TITLE
Batch inference during training

### ISSUE THREAD

**Issue by sandylaker** [open-mmlab/mmdetection#3691]
Single-stage detectors also support batch inference now, so is it possible (or better) to evaluate multiple images in a batch in `EvalHook` during training? More specifically, should we change the `samples_per_gpu` in [train.py](https://github.com/open-mmlab/mmdetection/blob/73ebc5223a2bb7ee358961ed235b82fcf3b8b316/mmdet/apis/train.py#L117) to other values bigger than 1?

**Comment by yhcao6** [comment]
Currently, the batch size is hardcoded as 1 during evaluation.
https://github.com/open-mmlab/mmdetection/blob/a1e0e28c1f4602389528b5baf15312b646f8eb42/mmdet/apis/train.py#L115-L120
But to enable evaluation with multi images, you can change 1 to 2 and replace 
` dict(type='ImageToTensor', keys=['img'])` in val pipeline to `DefaultFormatBundle`.
I will create a Pr to support that once #3686 is merged.
