### ISSUE TITLE
About the tags that are still VOC after modification

### ISSUE THREAD

**Issue by zhang5957** [open-mmlab/mmdetection#3696]
Why use my
![微信图片_20200905223252](https://user-images.githubusercontent.com/60083899/92307281-d63be000-efc7-11ea-83fc-bc115f43aeb0.png)
own tag training, after modifying the category, the test is still VOC tag

**Comment by xvjiarui** [comment]
Hi @zhang5957 
You may provide more details about what behavior you would like to achieve, and what you have done towards it.

**Comment by zhang5957** [comment]
我在使用自己的数据集进行训练，按照步骤将voc标签换成自己的二分类标签，但是在进行训练时仍然是voc的两个类别标签。mmdet/datasets/VOC.py，mmdet/core/evaluation/class_names.py，这两个我都改了

**Comment by zhang5957** [comment]
@xvjiarui 我在使用自己的数据集进行训练，按照步骤将voc标签换成自己的二分类标签，但是在进行训练时仍然是voc的两个类别标签。mmdet/ datasets / VOC.py，mmdet / core / evaluation /class_names.py，这两个我都改了

**Comment by yuzhj** [comment]
I think rewriting the dataset is a good way to address your problem
like this:
```python
@DATASETS.register_module()
class DatasetName(XMLDataset):

    CLASSES = ('label1', 'label2', '...')

    def __init__(self, **kwargs):
        ...
    
    def evaluate():
        ...
```
you can refer to voc.py

**Comment by hyd-520** [comment]
我也遇到了这样的问题，请问你解决了吗？

**Comment by xvjiarui** [comment]
Please use English or Chinese/English for issue.
