### ISSUE TITLE
Proposal coordinates error when get target mask 

### ISSUE THREAD

**Issue by animebing** [open-mmlab/mmdetection#370]
when I train mask rcnn with text detection dataset, sometimes the process crashes with the error 
`cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
` when resize mask to get the target mask in [this line](https://github.com/open-mmlab/mmdetection/blob/70383d4633fc8b30c5286f6833a267bcaf71808c/mmdet/core/mask/mask_target.py#L29). 

When I debug, the coordinates of positive proposal with an error is `[800 745 800 783 ]` in which the `x` coordinate ` 800` is out of the image, so the ROI mask is empty, that's why the error occurs, I am confused about why this proposal is choosed.

At the same time, I find some ground truth bounding boxes I generate is on the border, when I clip the coordinates to `[0, w-1]` and `[0, h-1]`, there is no error. And I find when do preprossing, there is one line code `gt_bboxes[:, 0::2] = np.clip(gt_bboxes[:, 0::2], 0, img_shape[1])` in [BboxTransform](https://github.com/open-mmlab/mmdetection/blob/70383d4633fc8b30c5286f6833a267bcaf71808c/mmdet/datasets/transforms.py#L79), I think there should be `img_shape[1] - 1`

**Comment by hellock** [comment]
I guess you are right! A PR to fix that is welcome.
btw, are you training with other datasets than COCO?

**Comment by animebing** [comment]
@hellock Yes, I am training with text detection dataset.

**Comment by hellock** [comment]
#390
