### ISSUE TITLE
How to download res2net 50 pre-trained model

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#3700]
How to download res2net 50 pre-trained model? There only have res2net 101 model.

Thanks a lot!

**Comment by xvjiarui** [comment]
Hi @minan19605 
You may refer to the official implementation [here](https://github.com/Res2Net/Res2Net-PretrainedModels). 
Note that you may need to convert some miss matching keys.

**Comment by shinya7y** [comment]
Please try the below.
[model](https://github.com/shinya7y/UniverseNet/releases/download/20.06/res2net50_v1b_26w_4s-3cf99910_mmdetv2.pth)
[key conversion script](https://github.com/shinya7y/UniverseNet/blob/master/tools/convert_res2net_checkpoint.py)

**Comment by minan19605** [comment]
@shinya7y Thank you so much. the model works very well

**Comment by minan19605** [comment]
I download the pth file into my PC and scp to the /home/xxxx/.cache/torch/checkpoints. Then modify the config py file as below:

model = dict(
    pretrained= '/home/xxx/.cache/torch/checkpoints/res2net50_v1b_26w_4s-3cf99910_mmdetv2pth', 
    backbone=dict(type='Res2Net', depth=50, scales=4, base_width=26))
