### ISSUE TITLE
How to view the map of a certain class in coco dataset

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmdetection#3706]
When I have trained my custom datasets,I just want to see a certain class's map  so that I can change my algorithm to improve this class's map, so what shuold I do to get the map of a certain class?Thanks for your help,I just a newer for this project.

**Comment by xvjiarui** [comment]
Hi @baibaidedongdong 
Are you using `CustomDataset`?

**Comment by baibaidedongdong** [comment]
yes，but it is coco data type.&nbsp;



---Original---

**Comment by xvjiarui** [comment]
If so, you may try to use COCO dataset. When evaluating, set `classwise=True`.

**Comment by baibaidedongdong** [comment]
ok，thanks，I will try it tomorrow!



---Original---
