### ISSUE TITLE
bbox mAP stays very low at end of each epoch when training on custom COCO-format dataset

### ISSUE THREAD

**Issue by mcdy143** [open-mmlab/mmdetection#3707]
I am training an object detection model using the `cascade_rcnn_x101_64x4d_fpn_20e_coco.py` config file on a custom COCO formatted dataset. I have 20 classes and have changed the corresponding config file lines. Outputs from the log files are as follows and there seem to be a mismatch between the loss during training and the evaluation on bbox mAP at end of each epoch:

`2020-09-05 08:56:35,767 - mmdet - INFO - Epoch [20][4300/4395]	lr: 0.00003, eta: 0:01:04, time: 0.685, data_time: 0.005, memory: 6717, loss_rpn_cls: 0.0007, loss_rpn_bbox: 0.0008, s0.loss_cls: 0.0152, s0.acc: 99.4355, s0.loss_bbox: 0.0039, s1.loss_cls: 0.0073, s1.acc: 99.4718, s1.loss_bbox: 0.0057, s2.loss_cls: 0.0046, s2.acc: 99.3902, s2.loss_bbox: 0.0064, loss: 0.0444
2020-09-05 08:57:09,980 - mmdet - INFO - Epoch [20][4350/4395]	lr: 0.00003, eta: 0:00:30, time: 0.684, data_time: 0.005, memory: 6717, loss_rpn_cls: 0.0006, loss_rpn_bbox: 0.0008, s0.loss_cls: 0.0140, s0.acc: 99.4707, s0.loss_bbox: 0.0040, s1.loss_cls: 0.0056, s1.acc: 99.5386, s1.loss_bbox: 0.0052, s2.loss_cls: 0.0028, s2.acc: 99.5430, s2.loss_bbox: 0.0058, loss: 0.0389
[>>>>>>>>>>>>>>>>>>>>>>>>>>] 1549/1549, 10.8 task/s, elapsed: 143s, ETA:     0s2020-09-05 09:00:05,316 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.31s).
Accumulating evaluation results...
DONE (t=0.34s).
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.090
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.100
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.099
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.090
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.093
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.095
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.095
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.095
2020-09-05 09:00:07,039 - mmdet - INFO - Epoch [20][4395/4395]	lr: 0.00003, bbox_mAP: 0.0900, bbox_mAP_50: 0.1000, bbox_mAP_75: 0.0990, bbox_mAP_s: 0.0000, bbox_mAP_m: 0.0000, bbox_mAP_l: 0.0900, bbox_mAP_copypaste: 0.090 0.100 0.099 0.000 0.000 0.090`

My dataset annotations have the following format: 
`[{'id': 652, 'image_id': 2348213731, 'category_id': 10, 'segmentation': [], 'iscrowd': 0, 'area': 662606, 'bbox': [60, 198, 893, 742]}]`

Is it possible that the bbox evaluation is done using the segmentation field that is empty (Referring to #3434) or could it be some other reasons?

**Comment by xvjiarui** [comment]
Hi @mcdy143 
You may check if your annotation file is correct. [Here](https://github.com/open-mmlab/cocoapi/blob/master/pycocotools/pycocoEvalDemo.ipynb) is an example.

**Comment by mcdy143** [comment]
Thanks for the quick response @xvjiarui . What should `resFile` be in this case? I was able to visualize the annotations correctly using `pycocotools`.

**Comment by lliuz** [comment]
I have meet a similar issue in evaluation of distributed training models and dist_test.sh as well.
I guess there is a bug in collecting results which leads keys and results misaligned, since when I use a single GPU everything is fine.

**Comment by mcdy143** [comment]
Thanks for the insights @lliuz . I am using a single-gpu machine so it might be a different issue. Upon running inference using the trained model, I got very accurate bounding boxes, but the class labels are all wrong, so that explains the low numbers. However, I have done everything listed in [here](https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html), so I am really confused as to why the class labels mismatch.
