### ISSUE TITLE
Question about Dataloader

### ISSUE THREAD

**Issue by kye9216789** [open-mmlab/mmdetection#371]
https://github.com/open-mmlab/mmdetection/blob/70383d4633fc8b30c5286f6833a267bcaf71808c/mmdet/datasets/loader/build_loader.py#L15-L44

When non-dist, why num_workers = num_gpus * workers_per_gpu ? 
How is it possible?
I think non-dist train is done with only single gpu.

**Comment by i008** [comment]
This has likely to do with multiprocessed loading of the data (happening on CPU's anyway) so it its not directly so thats perfectly fine even if you have 1 GPU.

**Comment by wangg12** [comment]
@kye9216789 You can run non-dist training with multiple gpus on a single machine.

**Comment by CaMi1le** [comment]
> This has likely to do with multiprocessed loading of the data (happening on CPU's anyway) so it its not directly so thats perfectly fine even if you have 1 GPU.

Then how can I put this manually on GPU?
