### ISSUE TITLE
key value mismatch when evaluation of distributed training models and distributed test

### ISSUE THREAD

**Issue by lliuz** [open-mmlab/mmdetection#3718]
I have meet a similar issue in evaluation of distributed training models and dist_test.sh as well.
I guess there is a bug in collecting results which leads keys and results misaligned, since when I use a single GPU everything is fine.

_Originally posted by @lliuz in https://github.com/open-mmlab/mmdetection/issues/3707#issuecomment-688743063_

**Comment by lliuz** [comment]
I wonder if anyone has tested the COCO dataset with `dist_test.sh` in the current version. That will be helpful for me to figure out what is wrong with my code.

**Comment by yhcao6** [comment]
Are you using your own dataset? It is fine for testing coco dataset with multi GPUs.
Can you give us more information about your error like the error traceback?

**Comment by lliuz** [comment]
Thanks for your reply, I will double check my dataset and recompile mmdet.
