### ISSUE TITLE
请问一下，我看你已经添加了ignore的gt，如果我想要用mmdet来训练citypersons这个数据集，那我如何转化数据集格式呢？

### ISSUE THREAD

**Issue by gittigxuy** [open-mmlab/mmdetection#372]
citypersons的输入是比coco数据集多了一个ignore区域

**Comment by gittigxuy** [comment]
请问一下，最新的版本的代码不支持pytorch1.0以下的版本了吗？

**Comment by hellock** [comment]
1. COCO dataset already ships with the ignored bboxes.
2. You can checkout to the 0.4.1 branch if you want to use pytorch 0.4.1, but it will not receive further updates.
