### ISSUE TITLE
Questions about cut out parameters?

### ISSUE THREAD

**Issue by sky-fly97** [open-mmlab/mmdetection#3724]
Hello, I want to use **cut out** in mmdet, and I notice that this method has been implemented in **transform.py.**  But there is no default **parameters**, so I would like to ask **how to set the default parameters** of cut out **better**? For example, **n_ holes** and **cutout_ Ratio**, I want to know whether the official has done any experiments when adding these parameters, or has anyone else set them? Thank you

**Comment by Johnson-Wang** [comment]
These hyper-parameters may vary from task to task, and users may refer to the [original paper](
https://arxiv.org/abs/1708.04552) for details. As to the default setting, there is no universal recommendations but the following setting has been test on coco dataset with around 0.5 AP increase. 

```python
dict(type='CutOut', 
    n_holes=7,
    cutout_shape=[(4, 4), (4, 8), (8, 4),
                       (8, 8), (16, 8), (8, 16),
                       (16, 16), (16, 32), (32, 16) ]
)
```
