### ISSUE TITLE
Too similar bounding boxes with different classes

### ISSUE THREAD

**Issue by melih1996** [open-mmlab/mmdetection#3725]
Hi, I do object detection on medical images. I have 2 similar classes. No matter which model I try, I always get too similar bounding boxes for different classes. The models are capable of finding superclass but for all objects, it gives too similar bounding box coordinates. How to handle it? Should I change the loss function then how to do it? Thank you.

**Comment by hellock** [comment]
It is expected. If the detector predicts two classes with scores higher than a threshold, then we leave both.

**Comment by melih1996** [comment]
How to resolve it. I want to change the loss function. Is there any easy way to do it otherwise I need to train a Siamese network after trainining detection model on the superclass.

**Comment by hellock** [comment]
You can do a NMS across different classes or just keep the bbox with highest scores among all classes.
