### ISSUE TITLE
High mAP but low recall and precision while training my dataset

### ISSUE THREAD

**Issue by MinYounZhang** [open-mmlab/mmdetection#3730]
Thanks for mmlab and thanks for your time to help a vegetable chicken :)

I just fine-turn RetinaNet using my dataset( VOC format). I change num_class = 4 and ResNet + Retina weights fit to number of detection class. Finally,the mAP is more than 95% while recall and precision are both less than 5%. Output detection pictures and training loss suggest that the model works well. Can you give me some advice？Becuse of anchor box?

**Comment by v-qjqs** [comment]
Hi @MinYounZhang , did you show the correct value of mAP, recall and percision? I guess it's not possible to have such high a performance and such low a recall or precision.
