### ISSUE TITLE
GPU Memory Usage Is Continously Increasing During Training

### ISSUE THREAD

**Issue by kesisci** [open-mmlab/mmdetection#3733]
I switched different models and saw that the issue is continuing. GPU memory usage is increasing and causing CUDA memory error.

Python: 3.8.5
GPU : GTX 2080 8GB
Cuda:10.2

**Comment by v-qjqs** [comment]
Hi @kesisci , did you release the GPU memory before your next training? Does reduce the batch size help?

**Comment by kesisci** [comment]
I am checking with "nvidia-smi" and seeing that the memory is released. I already reduce "samples_for_gpu = 1" and the problem is still occurring. The problem is that after some iteration, the gpu become full, especially for the models that are using cascade r cnn backbone.

**Comment by v-qjqs** [comment]
Hi @kesisci, I guess it's common for the GPU memory to become larger and larger in the first few iterations. You might reduce the input resolution for training large detectors like CascadeRCNN since your limited GPU memory.
