### ISSUE TITLE
About lable assigning method in grid_assigner.py

### ISSUE THREAD

**Issue by YufanLuo** [open-mmlab/mmdetection#3735]
Hi, sorry to bother you. But I have questions in reading _grid_assigner.py_.  In my opinion, the method of assigning ground truth to anchors depends on such description in _YOLOv3: An Incremental Improvement:_

> YOLOv3 predicts an objectness score for each bounding box using logistic regression. This should be 1 if the bounding box prior overlaps a ground truth object by more than any other bounding box prior. If the bounding box prior is not the best but does overlap a ground truth object by more than some threshold we ignore the prediction, following [17]. We use the threshold of .5. Unlike [17] our system only assigns one bounding box prior for each ground truth object. If a bounding box prior is not assigned to a ground truth object it incurs no loss for coordinate or class predictions, only objectness.

However, method in _grid_assigner.py_ adopts the method similar with Faster R-CNN, which positive anchors are defined as having IOU values higher than 0.5 with any ground truth. Thus the ignored anchors are defined as in cells that are not responsible for this object and have IOU value higher than 0.5.  But maybe the quote above means that if the anchor has IOU value higher than 0.5 but not the highest IOU value should be defined as ignored?

So does the method of assigning lables in _grid_assigner.py_ bring extra performance increasing? Or I have wrong understanding about the method of assigning lables in YOLOv3?

**Comment by hhaAndroid** [comment]
I think it can be simply considered as a combination of max iou assigner and yolov3 grid assigner.

**Comment by xvjiarui** [comment]
Hi @YufanLuo 
As @hhaAndroid said, `grid_assigner` is the combination of the two. And the max iou assigner part could also assign by IoU threshold. You may check the [doc](https://mmdetection.readthedocs.io/en/latest/api.html#mmdet.core.bbox.MaxIoUAssigner) for details.
