### ISSUE TITLE
GCNet pre-trained model download failed

### ISSUE THREAD

**Issue by jianjiandandande** [open-mmlab/mmdetection#3737]
I encountered this problem ' You have no right to access this object because of bucket acl.' when I downloaded the following pre-trained model.
![image](https://user-images.githubusercontent.com/15951818/92844751-c7ff2100-f418-11ea-9d93-65c3d9dbf454.png)

**Comment by xvjiarui** [comment]
Hi @jianjiandandande 
I just uploaded them. You may check it.
