### ISSUE TITLE
It raises warnings about matplotlib, how can I avoid them?

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#374]
![image](https://user-images.githubusercontent.com/15847405/54018576-04b6e000-41c4-11e9-9369-57814ac264c5.png)

**Comment by hellock** [comment]
It is a matplotlib backend dependency issue, mostly related to your GUI environment. You can easily search for some solutions for that, or just comment the `import matplotlib.pyplot as plt` line, which is not required if you don't want to plot official annotations for debugging.
