### ISSUE TITLE
Have the CIoULoss and DIoULoss been tested?

### ISSUE THREAD

**Issue by hiyyg** [open-mmlab/mmdetection#3743]
Hi, I found that there are implementations of CIoULoss and DIoULoss, but I can not find any examples or models using these two losses. I wonder whether they have been tested with any algorithms?

**Comment by RyanXLi** [comment]
Hi! For the usage of these loss, you can refer to models using IoULoss, e.g. this [Faster RCNN](https://github.com/open-mmlab/mmdetection/blob/bce9682339284e736038c461663d338303f19b9c/configs/faster_rcnn/faster_rcnn_r50_fpn_iou_1x_coco.py) or FSAF or FCOS, as they have the same conventions in input and output and they can be substituted by editing the config.

**Comment by ZwwWayne** [comment]
Their usage are the same as GIoULoss and IoULoss.

**Comment by henbucuoshanghai** [comment]
so i can use  the follow  to train frcnn with giou??????????????
python tools/train.py ./configs/faster_rcnn_r50_fpn_giou_1x_coco.py


 loss_bbox=dict(type='GIoULoss', loss_weight=10.0))))
