### ISSUE TITLE
mask prediction does not not work when keep_ratio=False in data

### ISSUE THREAD

**Issue by PawelFaron** [open-mmlab/mmdetection#3747]
I'm training my own data in COCO like format using https://github.com/open-mmlab/mmdetection/blob/master/configs/res2net/htc_r2_101_fpn_20e_coco.py
It words good when I have keep_ratio=False set in train_pipeline, test_pipeline, val, test dict but I got all zeros for "segm" when I have this set for data.

**Comment by ZwwWayne** [comment]
Hi @PawelFaron ,
Could you provide a reproducible config with the command you use?
