### ISSUE TITLE
How to register multiple eval hooks

### ISSUE THREAD

**Issue by LMerCy** [open-mmlab/mmdetection#3749]
I need to register multiple eval hooks to reuse dataset.evaluate(), but i found here will call Pool init https://github.com/open-mmlab/mmdetection/blob/11b1ef830aa7c8c054d8b5346fe0966e643d473c/mmdet/core/evaluation/mean_ap.py#L312 , if i call multiple eval hooks, which may be so slow due to the large overhead, is there any solution?

**Comment by ZwwWayne** [comment]
The two hooks execute sequentially. Therefore, there will be only `nproc` number of thread to calculate the AP all the time. After the first evaluation is done, the next evalhook will execute the evaluation. So this should not be a problem.

**Comment by ZwwWayne** [comment]
The question seems to be answered thus the issue is closed. Feel free to reopen it if you have any further questions.
