### ISSUE TITLE
KeyError: 'xxxDataset is not in the dataset registry' when test

### ISSUE THREAD

**Issue by guiyuliu** [open-mmlab/mmdetection#3751]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I create a new dataset which inherits from coco， the only difference is the CLASS names
I can train it ， but when I test it， it will report the not registry error。
I registry it already in mmdet/dataset/init

**Reproduction**
1. What command or script did you run?
```
 python tools/test.py configs/retinanet/retinanet_r50_fpn_2x_coco.py work_dirs/retinanet_r50_fpn_2x_coco_obstacle/epoch_1.pth --eval proposal

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I think I registry my new dataset to  datasest module, I add it to __init__.py
```

diff --git a/mmdet/datasets/__init__.py b/mmdet/datasets/__init__.py
index 95a38ba..e4eccd6 100644
--- a/mmdet/datasets/__init__.py
+++ b/mmdet/datasets/__init__.py
@@ -10,6 +10,7 @@ from .samplers import DistributedGroupSampler, DistributedSampler, GroupSampler
 from .voc import VOCDataset
 from .wider_face import WIDERFaceDataset
 from .xml_style import XMLDataset
+from .nuscenes_dataset import NusDataset

 __all__ = [
     'CustomDataset', 'XMLDataset', 'CocoDataset', 'DeepFashionDataset',
@@ -17,5 +18,5 @@ __all__ = [
     'LVISV1Dataset', 'GroupSampler', 'DistributedGroupSampler',
     'DistributedSampler', 'build_dataloader', 'ConcatDataset', 'RepeatDataset',
     'ClassBalancedDataset', 'WIDERFaceDataset', 'DATASETS', 'PIPELINES',
-    'build_dataset'
+    'build_dataset', 'NusDataset'
 ]

```

3. What dataset did you use?
this is my new dataset
```
from .coco import CocoDataset
from .builder import DATASETS

@DATASETS.register_module()
class NusDataset(CocoDataset):
    CLASSES = ("obstacle")
```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
  File "tools/test.py", line 197, in <module>
    main()
  File "tools/test.py", line 144, in main
    dataset = build_dataset(cfg.data.test)
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/site-packages/mmdet-2.3.0-py3.7.egg/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'NusDataset is not in the dataset registry'

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
Hi @guiyuliu ,
I guess the running version is not the version that you modified. You may check whether your environment has another mmdet.

**Comment by Guangjun-A** [comment]
Maybe you don't write 'from .NusDataset import NusDataset' in __init__.py.

**Comment by DaniloAlves1995** [comment]
> Maybe you don't write 'from .NusDataset import NusDataset' in **init**.py.

Thank you, this fixed for me!

**Comment by heethesh** [comment]
had the same issue mmdetection3d, you might to document this in the tutorial

**Comment by daigz1224** [comment]
see this: https://github.com/open-mmlab/mmdetection/issues/1324#issuecomment-958694654

**Comment by ake020675** [comment]
> Maybe you don't write 'from .NusDataset import NusDataset' in **init**.py.

thank u so much. you saved me

**Comment by Jxy04250** [comment]
> Maybe you don't write 'from .NusDataset import NusDataset' in **init**.py.

This fixed for me, thanks!
