### ISSUE TITLE
robustness_eval.py:'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmdetection#3753]
**commandline**:python tools/robustness_eval.py /work/pycharmprojects/mmdetection-master/robust.pkl --dataset coco --task bbox 
**environment**:python3.7
**error**:UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Traceback (most recent call last):
  File "/work/mmdetection/tools/robustness_eval.py", line 256, in <module>
    main()
  File "/work/mmdetection/tools/robustness_eval.py", line 252, in main
    aggregate=args.aggregate)
  File "/work/mmdetection/tools/robustness_eval.py", line 175, in get_results
    aggregate=aggregate)
  File "/work/mmdetection/tools/robustness_eval.py", line 68, in get_coco_style_results
    num_distortions = len(list(eval_output.keys()))
AttributeError: 'list' object has no attribute 'keys'
**how can i get AP of each class？**:I have seen the primary coco_eval.py has been removd，and now the only way is to use robustness_eval.py?

**Comment by mytk2012** [comment]
AP for each class，I have referred to history about each class,and you mean we should take 5th example.But the question is that we don't have access to run .sh because it's on the remote server.Can you provide another solution？

**Comment by ZwwWayne** [comment]
Please refer to the 5th example in [doc](https://github.com/open-mmlab/mmdetection/blob/e5072a3f75be4bc02da21ac6401e4f97d462c205/docs/getting_started.md).
