### ISSUE TITLE
How to get class probabilities for each detection 

### ISSUE THREAD

**Issue by Seiano** [open-mmlab/mmdetection#3755]
These detections already pick the highest probability class for each detection.

Is there an easy way to get the predictions for each class for each detection?

**Comment by yuzhj** [comment]
like this
```python
from mmdet.apis import init_detector, inference_detector
import mmcv

config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_detector(model, img)
```
 the predictions for each class are in "result"

**Comment by mytk2012** [comment]
> like this
> 
> ```python
> from mmdet.apis import init_detector, inference_detector
> import mmcv
> 
> config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
> checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
> model = init_detector(config_file, checkpoint_file, device='cuda:0')
> img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
> result = inference_detector(model, img)
> ```
> 
> the predictions for each class are in "result"

But this is the implement for ipny.In fact，when you run test.py or robustness_eval.py，this don't output each class

**Comment by Seiano** [comment]
> like this
> 
> ```python
> from mmdet.apis import init_detector, inference_detector
> import mmcv
> 
> config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
> checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth'
> model = init_detector(config_file, checkpoint_file, device='cuda:0')
> img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
> result = inference_detector(model, img)
> ```
> 
> the predictions for each class are in "result"

That "result" is not my mean.   I want  Multiple calsses- probabilities corresponding to one box. But the result give me one-classes-probability corresponding to one box.  I have try it.

**Comment by ZwwWayne** [comment]
You may hack the test code [here](https://github.com/open-mmlab/mmdetection/blob/11b1ef830aa7c8c054d8b5346fe0966e643d473c/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L198).

**Comment by Seiano** [comment]
thank you for your  help! I got it in the bbox_nms/multiclass_nms()  so hard!  but  now  I am so  happy!

**Comment by Cavaradossi** [comment]
> thank you for your help! I got it in the bbox_nms/multiclass_nms() so hard! but now I am so happy!

how to do with bbox_nms /multiclass_nms on result and output the most probable class?

**Comment by LiUzHiAn** [comment]
@Seiano  
Hi, there. I check the inference code in detail and modify it accordingly.  I wrote a function that can return the class probabilities for each detection. Check it [>>here<<](https://gist.github.com/LiUzHiAn/13f8f13b354e848a3b166fde3cc3335a). Hope it helps!

**Comment by muyuuuu** [comment]
`inference_detector` only output boxes and probabilities, why not output class of each box?

**Comment by RangiLyu** [comment]
> `inference_detector` only output boxes and probabilities, why not output class of each box?

The `results` returned by `inference_detector` is a list and its length is num_classes. So the index of each numpy array of boxes and probabilities in this list is class id.

**Comment by muyuuuu** [comment]
> The `results` returned by `inference_detector` is a list and its length is num_classes. So the index of each numpy array of boxes and probabilities in this list is class id.

thank you !!! I didn't find that on [offical document](https://mmdetection.readthedocs.io/en/latest/api.html#module-mmdet.apis) thus the question arose.

**Comment by neel04** [comment]
@RangiLyu That's complicating inference very much :\ Isn't there an easier method to store bboxes with predicted class in a simple 5-elements long list?

**Comment by neel04** [comment]
If anyone else has an easy resource whereby I can do the above mentioned task easily, it would be greatly appreciated!

**Comment by mykeysid10** [comment]
How can I get predicted mask coordinates or mask area in inference detector? Inference Detector only gives boxes and probability. I need the mask area.

**Comment by KostadinovShalon** [comment]
> The `results` returned by `inference_detector` is a list and its length is num_classes. So the index of each numpy array of boxes and probabilities in this list is class id.

It seems this is not the case anymore for mmdetection 3.0.0. I cannot find a way of doing this in the latest version

**Comment by Y-T-G** [comment]
@KostadinovShalon Yes. In 3.0.0, I only get the best score associated with each bbox. I want to get the probabilities for all of the classes, not just the best class for each bbox. Can anyone explain how to do that in 3.0.0?

**Comment by Y-T-G** [comment]
I found a way to do this in MMDetection 3.1.0. I did it for RetinaNet, but the steps should be similar for other detectors.

https://y-t-g.github.io/tutorials/mmdetection-patching-probabilities/
