### ISSUE TITLE
Error in inference.py

### ISSUE THREAD

**Issue by payalmittal6792** [open-mmlab/mmdetection#3759]
I am not able to fully clone MMDetection github repository. There are few functions in APIs which are missing that hinders testing pipeline implementation. Can anyone have similar issue?

**Comment by ZwwWayne** [comment]
This is wierd, which module are you missing? Could you git clone a new repo and try again?

**Comment by payalmittal6792** [comment]
ImportError: cannot import name 'show_result' While running inference.py

**Comment by ZwwWayne** [comment]
There is no module named ` show_result` now in mmdet, the `show_result` methods are the method the models. Did you try to clone a new repo and try again? It should fix your issues.
