### ISSUE TITLE
Can I use inference to Multi-scale test?

### ISSUE THREAD

**Issue by zytx121** [open-mmlab/mmdetection#376]
Thank you for sharing an awesome repo. I have a question relating to multi-scale testing.
If i am not wrong, we can perform multi-scale testing by changingimg_scale=(1333, 800) in test dict.
However when i change img_scale to img_scale=[(400, 1400), (1200, 1400)].
I got bug`TypeError: Scale must be a number or tuple of int, but got <class 'list'>`

I just use the inference_detector in the README to test images, is that right? 
```
for i, result in enumerate(inference_detector(model, imgs, cfg, device='cuda:0')):
    file_name = imgs[i]
    file_out_name = imgs_out[i]
    bboxes = np.vstack(result)
    img = imread(file_name)
    if score_th > 0:
        assert bboxes.shape[1] == 5
        scores = bboxes[:, -1]
        inds = scores > score_th
        bboxes = bboxes[inds, :]
    for bbox in bboxes:
        bbox_int = bbox.astype(np.int64)
        left_top = (bbox_int[0], bbox_int[1])
        right_bottom = (bbox_int[2], bbox_int[3])
        results_file.write(file_name.split("/")[-1] + "," + str(int(bbox_int[0])) + " " + str(int(bbox_int[1])) + " " + str(
            int(bbox_int[2])) + " " + str(int(bbox_int[3])) + "\n")
        cv2.rectangle(
            img, left_top, right_bottom, color=(0,0,255), thickness=2)
    imwrite(img, file_out_name)
```

Do I need to use tools/test.py ?

**Comment by hellock** [comment]
The `inference_detector` has not implemented multi-scale inference yet. You can refer to `tools/test.py`.

**Comment by zytx121** [comment]
Ok! Thank you for your reply!
