### ISSUE TITLE
AttributeError: module 'pycocotools' has no attribute '__version__'

### ISSUE THREAD

**Issue by jialeli1** [open-mmlab/mmdetection#3761]
Hi,  I installed mmdet according to the instructions, but I still encountered this problem. 

File "/home/lijiale/mmdet_install/mmdetection/mmdet/datasets/coco.py", line 19, in <module>
    assert pycocotools.__version__ >= '12.0.2'
AttributeError: module 'pycocotools' has no attribute '__version__'

I also tried to install pycocotools from open-mmlab/cocoapi, but I found that it installed mmpycocotools.  When I run _pip list | grep pycocotools_, I found that there are two pycocotools. 

(open-mmlab) lijiale@ImageLab:~/mmdet_install/mmdetection3d$ pip list | grep pycocotools
mmpycocotools          12.0.2
pycocotools            2.0.2

Maybe this is the problem, but I don't know the specific reason. Could someone help me?

**Comment by yuzhj** [comment]
pip uninstall pycocotools

**Comment by ZwwWayne** [comment]
Please use the mmlab maintained pycocotools. To do that, you should first `pip uninstall pycocotools` and `pip install mmpycocotools`.

**Comment by alistarhu** [comment]
import pycocotools   pycocotools.__file__, to locate the pycocotools path which is used in current python environment. Then uninstall it.

**Comment by naveenggmu** [comment]
Hey @ZwwWayne, when I install mmpycocotools, I get back the error `ModuleNotFoundError: No module named 'pycocotools'`
Would be great if you can help me out.

**Comment by demerzel1** [comment]
> Hey @ZwwWayne, when I install mmpycocotools, I get back the error `ModuleNotFoundError: No module named 'pycocotools'`
> Would be great if you can help me out.

Hey, I got this problem too. I solved it by uninstall mmpycocotools, and install it again.
Hope can help you!

**Comment by dlutzhouyue** [comment]
> > Hey @ZwwWayne, when I install mmpycocotools, I get back the error `ModuleNotFoundError: No module named 'pycocotools'`
> > Would be great if you can help me out.
> 
> Hey, I got this problem too. I solved it by uninstall mmpycocotools, and install it again.
> Hope can help you!

it works for me! thx

**Comment by AhmadIbtehaj** [comment]
> > Hey @ZwwWayne, when I install mmpycocotools, I get back the error `ModuleNotFoundError: No module named 'pycocotools'`
> > Would be great if you can help me out.
> 
> Hey, I got this problem too. I solved it by uninstall mmpycocotools, and install it again. Hope can help you!

it worked for me

**Comment by thelandord** [comment]
> > Hey @ZwwWayne, when I install mmpycocotools, I get back the error `ModuleNotFoundError: No module named 'pycocotools'`
> > Would be great if you can help me out.
> 
> Hey, I got this problem too. I solved it by uninstall mmpycocotools, and install it again. Hope can help you!

it works for me .  But I have a new bug. 
FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: 'data/nuimages/annotations/nuimages_v1.0-train.json'
I can't find this josn file.  Could someone help me ?

**Comment by goToHelloWorld** [comment]
> 请使用 mmlab 维护的 pycocotools。为此，您应该首先 和 。`pip uninstall pycocotools``pip install mmpycocotools`
Thank you ！
