### ISSUE TITLE
supporting models running in parallel

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3762]
Hi, there,

I'm planning to ensemble the results of multiple models. Since the inference usually takes less computation and storage resources, is it possible to run multiple (different) models on the same GPU in parallel (for FPS) with mmDetection? If yes, could you give me some high-level suggestions on how to do this?

Thanks!

**Comment by yuzhj** [comment]
multi-threading
different models run in different threads

**Comment by ZwwWayne** [comment]
Currently, mmdet does not support this. If you want to perform ensemble, usually we run inference with models sequentially and finally ensemble the results.
