### ISSUE TITLE
dist_test.sh how to change to 1

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmdetection#3763]
![image](https://user-images.githubusercontent.com/57787557/93158442-b1b9d380-f73e-11ea-9e3e-999d7dcf4687.png)

**Comment by yuzhj** [comment]
no "sh"
like this
```python
./tools/dist_test.sh config checkpoint  1 ...
```

**Comment by mytk2012** [comment]
> no "sh"
> like this
> 
> ```python
> ./tools/dist_test.sh config checkpoint  1 ...
> ```

same error

**Comment by mytk2012** [comment]
> no "sh"
> like this
> 
> ```python
> ./tools/dist_test.sh config checkpoint  1 ...
> ```

I have succeeded by add bash，because it points to specially about bash and no sh.
