### ISSUE TITLE
how to use or add data augmentation while training?

### ISSUE THREAD

**Issue by 492235584** [open-mmlab/mmdetection#377]
thank you for your framework.
I would like do some data augmentation such as random rotate, random flip, random crop while train the model, how can I do this.

**Comment by hellock** [comment]
You can just modify [`ImageTransform`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/transforms.py#L8) or add some extra transforms like what SSD does.

**Comment by 492235584** [comment]
thanks for your response, I get it. 



> You can just modify [`ImageTransform`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/transforms.py#L8) or add some extra transforms like what SSD does.
