### ISSUE TITLE
ImportError: cannot import name 'show_result'

### ISSUE THREAD

**Issue by vishaldhull09** [open-mmlab/mmdetection#3771]
How to resolve this?
I am trying to run mmdetection repo on colab
Link : 
https://colab.research.google.com/github/Tony607/mmdetection_object_detection_demo/blob/master/mmdetection_train_custom_data.ipynb?authuser=1#scrollTo=FNTFhKuVVhMr

**Comment by TiG000** [comment]
now show_result has changed to class BaseDetector , if you want to use it, firstly you need import it from mmdet.models.detectors.

**Comment by vishaldhull09** [comment]
> now show_result has changed to class BaseDetector , if you want to use it, firstly you need import it from mmdet.models.detectors.

i tried using   from mmdet.models.detectors import show_result  but it is saying "ImportError: cannot import name 'show_result'
" 
may be i am doing something wrong i am new to this

**Comment by TiG000** [comment]
> > now show_result has changed to class BaseDetector , if you want to use it, firstly you need import it from mmdet.models.detectors.
> 
> i tried using from mmdet.models.detectors import show_result but it is saying "ImportError: cannot import name 'show_result'
> "
> may be i am doing something wrong i am new to this

BaseDetector.show_result instead of show_result

**Comment by payalmittal6792** [comment]
when i call show_result as directed by you, following error occurred:

---------------------------------------------------------------------------KeyError Traceback (most recent call last)<ipython-input-19-b47390b94d84> in <module> 
8 # test a single image and show the results 
9 img = 'data/VOCdevkit/VOC2007/JPEGImages/0000001_05499_d_0000010.jpg'---> 10 result = inference_detector(model, img) 
11 BaseDetector.show_result(img, result, model.CLASSES, 
12 score_thr=score_thr, out_file="result.jpg")
~/Desktop/mmlab/mmdetection_object_detection_demo/mmdetection/mmdet/apis/inference.py in inference_detector(model, img) 
80 # prepare data 
81 data = dict(img=img)
---> 82 data = test_pipeline(data) 
83 data = scatter(collate([data], samples_per_gpu=1), [device])[0] 
84 # forward the model
~/Desktop/mmlab/mmdetection_object_detection_demo/mmdetection/mmdet/datasets/pipelines/compose.py in __call__(self, data) 
38
 39 for t in self.transforms
:---> 40 data = t(data) 
41 if data is None: 
42 return None
~/Desktop/mmlab/mmdetection_object_detection_demo/mmdetection/mmdet/datasets/pipelines/test_time_aug.py in __call__(self, results) 103 _results['flip'] = flip 
104 _results['flip_direction'] = direction
--> 105 data = self.transforms(_results) 
106 aug_data.append(data) 
107 # list of dict to dict of list
~/Desktop/mmlab/mmdetection_object_detection_demo/mmdetection/mmdet/datasets/pipelines/compose.py in __call__(self, data) 
38 
39 for t in self.transforms
:---> 40 data = t(data) 
41 if data is None: 
42 return None
~/Desktop/mmlab/mmdetection_object_detection_demo/mmdetection/mmdet/datasets/pipelines/formating.py in __call__(self, results) 
313 img_meta = {} 
314 for key in self.meta_keys:--> 
315 img_meta[key] = results[key]
 316 data['img_metas'] = DC(img_meta, cpu_only=True) 
317 for key in self.keys:

KeyError: 'ori_filename'

**Comment by TiG000** [comment]
in demo.py,I have mainly changed the following config:
result = inference_detector(model, img)
~~import ipdb; ipdb.set_trace()~~
res = BaseDetector.show_result(img, result, model.CLASSES, score_thr=0.3, wait_time=1)
cv.imwrite(result_path, res)

**Comment by vishaldhull09** [comment]
%cd {mmdetection_dir}

score_thr = 0.8

# build the model from a config file and a checkpoint file
model = init_detector(config_fname, checkpoint_file)

# test a single image and show the results
img = 'data/VOCdevkit/VOC2007/JPEGImages/0000001_05499_d_0000010.jpg'
result = inference_detector(model, img)
BaseDetector.show_result(img, result, model.CLASSES,
            score_thr=score_thr, out_file="result.jpg")


This shows error 
TypeError: "img" must be a numpy array or a str or a pathlib.Path object

**Comment by TiG000** [comment]
img = mmcv.imread(img_path)

**Comment by vishaldhull09** [comment]
error is the same after changing what you suggested

**Comment by vishaldhull09** [comment]
Is there any problem in code i am running or image

**Comment by binjiaqm** [comment]
Same issue here. Even doesn't have a good demo start!

**Comment by SayanSahu99** [comment]
BaseDetector.show_result(img=img, result=result, self=model, show=True,
            score_thr=score_thr)

This should work

**Comment by yassinesefrioui** [comment]
@vishaldhull09  i have the same problem, did you find any solution for that ?

**Comment by Albert337** [comment]
> @vishaldhull09 @yassinesefrioui Try this instead of BaseDetector.show_result
> 
> from mmdet.apis import show_result_pyplot show_result_pyplot(model, img, result, score_thr=0.3)

Thanks, but i use "show_result_pyplot" to instead "show_result_meshlab", the error is still occured. and my mmdet3d version
![image](https://github.com/open-mmlab/mmdetection/assets/33714840/029d7a9d-16bf-43e9-b22a-a21512d1ef86)
