### ISSUE TITLE
KeyError(f'invalid depth {depth} for resnet') when import build_detector

### ISSUE THREAD

**Issue by yanty123** [open-mmlab/mmdetection#3772]
Traceback (most recent call last):
  File "demo_prune.py", line 15, in <module>
    from mmdet.models import build_detector
  File "/home/yantianyi/mmdet-3.5/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/yantianyi/mmdet-3.5/mmdet/models/backbones/__init__.py", line 3, in <module>
    from .resnext import ResNeXt
  File "/home/yantianyi/mmdet-3.5/mmdet/models/backbones/resnext.py", line 7, in <module>
    from .resnet_2 import Bottleneck as _Bottleneck
  File "/home/yantianyi/mmdet-3.5/mmdet/models/backbones/resnet_2.py", line 386
    raise KeyError(f'invalid depth {depth} for resnet')
                                                     ^
SyntaxError: invalid syntax

I have installed the mmnet, but cant import the modules.

**Comment by yanty123** [comment]
Here is my packges:
python=3.5.6
pytorch=1.1.0 cuda9.0
mmdet=1.1.0
mmcv=0.3.2

so how can i fix it? 

thank u very much!

**Comment by v-qjqs** [comment]
Hi @yanty123 , a invalid depth for resnet backbone will raise the above KeyError. The valid depth value for resnet is only in [18,34,50,101,152]

**Comment by yanty123** [comment]
> Hi @yanty123 , a invalid depth for resnet backbone will raise the above KeyError. The valid depth value for resnet is only in [18,34,50,101,152]

Thank you sir, I know what you mean. However I haven't define the model yet, it's just the import line causes the error.
Just  'from mmdet.models import build_detector' this import line trigger the error.

So where is the problem?
Thank you!

**Comment by v-qjqs** [comment]
Hi, I guess the import error might be caused by your incorrectly installation? Did you install mmdetection following the official guideline?

**Comment by yanty123** [comment]
> Hi, I guess the import error might be caused by your incorrectly installation? Did you install mmdetection following the official guideline?

I guess so.I did follow the ReadMe and there isn't any problem, so i dont know where is the problem.
I run it well in the py3.6 env, so it's quiet strange. .

**Comment by v-qjqs** [comment]
Hi, does manually adding your mmdetection absolute path to PYTHONPATH help?

**Comment by yanty123** [comment]
> Hi, does manually adding your mmdetection absolute path to PYTHONPATH help?

oh it really helps! Thank you!
However, there is a new similiar problem when using the code 
' from mmdet.apis import inference_detector, init_detector_pruned, init_detector, show_result_pyplot '

File "/home/yantianyi/video/tools/mmdetection/demo_prune.py", line 20, in <module>
    from mmdet.apis import inference_detector, init_detector_pruned, init_detector, show_result_pyplot
  File "/home/yantianyi/mmdet-3.5/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/yantianyi/mmdet-3.5/mmdet/apis/inference.py", line 21
    f'but got {type(config)}')
    ^
SyntaxError: invalid syntax

So how can I fix this one?

**Comment by yanty123** [comment]
It seems like the imported init-module runs, but i just import it.
