### ISSUE TITLE
Error installing mmdetection on CPU

### ISSUE THREAD

**Issue by JuliuszZiomek** [open-mmlab/mmdetection#3774]
**Describe the bug**
Hello,
I would like to install mmdetection framework in CPU-only mode as it is described in docs https://mmdetection.readthedocs.io/en/latest/install.html#install-with-cpu-only, but I can't find clear instruction on how to do it.
I followed the guidelines from the mmcv repo front-page on installing the mmcv cpu version and then installed the dependencies and ran setup.py install and setup.py develop which both worked fine. However, when I try running any script (e.g. webcam demo) I get the following error:
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/mainfs/home/jkz1n20/cpu/mmdetection/mmdet/ops/dcn/__init__.py)

**Environment**
Installed with conda on Linux
1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
output: ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/mainfs/home/jkz1n20/cpu/mmdetection/mmdet/ops/dcn/__init__.py)

**Comment by ZwwWayne** [comment]
Hi @JuliuszZiomek ,
Could you report the version of your MMDet and MMCV?

**Comment by JuliuszZiomek** [comment]
MMCV version is: 0.4.3
MMDet version is: 1.2.0+0f33c08

**Comment by ZwwWayne** [comment]
The documentation is for the newest mmcv and mmdet. But the version of mmcv and mmdet you are using is too old.

**Comment by SourabhRanade** [comment]
@ZwwWayne @JuliuszZiomek could you please point out to the exact steps to be followed? I was refering to the following section, [](https://mmdetection.readthedocs.io/en/latest/get_started.html#install-without-gpu-support) however, there are no explicit steps mentioned. It just says that it can be used on an environment with no CUDA. I want to setup the mmdetection environemnt on a raspberry pi machine.
