### ISSUE TITLE
AP = -1.0

### ISSUE THREAD

**Issue by sakurasakura1996** [open-mmlab/mmdetection#3775]
I use mmdetection to train my custom dataset, the console output is:
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.438
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.735
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.476
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.399
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.372
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.639
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.639
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.639
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.633
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.583
why the fourth AP is -1.000,What are the possible reasons？

**Comment by shinya7y** [comment]
No small bbox (area <= 32*32) in your test dataset.
