### ISSUE TITLE
How to load only the weight parameters of RPN from the pre-trained model?

### ISSUE THREAD

**Issue by jwwangchn** [open-mmlab/mmdetection#3776]
I already know that I should use `load_from` in the config file to load the pre-trained model. But I just want to use the weight parameters of RPN and drop the weight parameters of RCNN branch (such as Faster R-CNN). What should I do?

Thanks for your time and help.

**Comment by ZwwWayne** [comment]
You can first write a script to drop the weights of roi_heads, which has key name starting from `roi_head.`
