### ISSUE TITLE
The data is ready. Report errors during training

### ISSUE THREAD

**Issue by zoui520** [open-mmlab/mmdetection#3780]
The data is ready. Report errors during training
![QQ图片20200916140005](https://user-images.githubusercontent.com/26056504/93297977-f0c25480-f824-11ea-9d34-43a45a158661.png)

version：
![image](https://user-images.githubusercontent.com/26056504/93298014-046dbb00-f825-11ea-8735-e20f7e9b3a48.png)

env 
 win10

**Comment by yhcao6** [comment]
Please follow the error template.
