### ISSUE TITLE
running error on async inference

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3782]
Hi there,

Following your example, I'm using async API to run multiple models on a single GPU. However, I find the following error. Could you give me some feedback? I'm using mmDetection v2.3.

`
  File "model_run_async.py", line 72, in <module>
    asyncio.run(main())
  File "/opt/conda/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "model_run_async.py", line 60, in main
    async_results = await asyncio.gather(*tasks)
  File "model_run_async.py", line 53, in detect
    return await async_inference_detector(model, img)
  File "/mmdetection/mmdet/apis/inference.py", line 150, in async_inference_detector
    result = await model.aforward_test(rescale=True, **data)
  File "/mmdetection/mmdet/models/detectors/base.py", line 116, in aforward_test
    return await self.async_simple_test(img[0], img_metas[0], **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 80, in async_simple_test
    raise NotImplementedError
NotImplementedError
`

Here's the code sample I'm using:

import asyncio
import torch
from mmdet.apis import init_detector, async_inference_detector
from mmdet.utils.contextmanagers import concurrent
import mmcv
from mmdet.utils.profiling import profile_time

```
async def main():
    config_file_one = 'xxx'
    checkpoint_file_one = 'xxx'

    config_file_two = 'xxx'
    checkpoint_file_two = 'xxx'

    config_file_three = 'xxx'
    checkpoint_file_three = 'xxx'

    config_file_four = 'xxx‘
    checkpoint_file_four = 'xxx'

    device = 'cuda:0'
    model_one = init_detector(config_file_one, checkpoint=checkpoint_file_one, device=device)
    model_two = init_detector(config_file_two, checkpoint=checkpoint_file_two, device=device)
    model_three = init_detector(config_file_three, checkpoint=checkpoint_file_three, device=device)
    model_four = init_detector(config_file_four, checkpoint=checkpoint_file_four, device=device)

    # queue is used for concurrent inference of multiple images
    streamqueue = asyncio.Queue()
    # queue size defines concurrency level
    streamqueue_size = 4

    for _ in range(streamqueue_size):
        streamqueue.put_nowait(torch.cuda.Stream(device=device))

    # test a single image and show the results
    img = 'xxx.jpeg' 
    img = mmcv.imread(img)

    async def detect(img, model):
        async with concurrent(streamqueue):
            return await async_inference_detector(model, img)

    models = [model_one, model_two, model_three, model_four]
    with profile_time('benchmark', 'async'):
        tasks = [
            asyncio.create_task(detect(img,model)) for model in models

```

Thanks!

**Comment by RyanXLi** [comment]
Hi! Please follow the error template when raising an issue so I can better understand the problem.

**Comment by shanggdlk** [comment]
> Hi! Please follow the error template when raising an issue so I can better understand the problem.

Thanks! I have resubmitted a question accordingly.
