### ISSUE TITLE
How to cal the infer time of model?

### ISSUE THREAD

**Issue by LicharYuan** [open-mmlab/mmdetection#3783]
Hi, thanks for this awesome open-source work.

I notice that the model zoo public the model infer time. How to get this value?  Any Codes provided (maybe I missed)?

Thanks for any answers!

**Comment by RyanXLi** [comment]
> We report the inference time as the total time of network forwarding and post-processing, excluding the data loading time. Results are obtained with the script [benchmark.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/benchmark.py) which computes the average time on 2000 images.

([source](https://github.com/open-mmlab/mmdetection/blob/f240bf9d4999854c4eb5cccbfae5053443db4a84/docs/model_zoo.md#common-settings))

**Comment by LicharYuan** [comment]
Thank you. 

Got it !

**Comment by wsy-yjys** [comment]
how to get infer time just use one gpu without distributed
