### ISSUE TITLE
mmdet/core/evaluation/mean_ap.py Line 256 might cause error

### ISSUE THREAD

**Issue by emergencyd** [open-mmlab/mmdetection#3784]
`cls_gts.append(ann['bboxes'][gt_inds, :])`
when the gt_inds is False, this will turn the (1, 4) array to (0, 1, 4), thus causing error in future concatenation.

**Comment by RyanXLi** [comment]
This piece of code does seem to be problematic. Thanks for pointing it out.

**Comment by hhaAndroid** [comment]
Hi, @emergencyd I think this is correct, when the gt_inds is False, this will return the (0, 4) array, not (0, 1, 4)!
