### ISSUE TITLE
The problem of loss does not converge in the training of SSD

### ISSUE THREAD

**Issue by zhang5957** [open-mmlab/mmdetection#3786]
During the training of SSD, errors were reported：AssertionError: classification scores become infinite or NaN!
![微信图片_20200917162727](https://user-images.githubusercontent.com/60083899/93442947-bcbd6100-f902-11ea-9f46-9bd86af107e3.png)
For the same data, there is no problem in faster- RCNN

**Comment by RyanXLi** [comment]
Hi! As the error message suggests, your cls score is infinite or NaN, probably meaning your gradient has exploded. Please check your hyperparameters among other things. And please supply more information following the template of reporting an error if the problem is not resolved.

**Comment by zhang5957** [comment]
> Hi! As the error message suggests, your cls score is infinite or NaN, probably meaning your gradient has exploded. Please check your hyperparameters among other things. And please supply more information following the template of reporting an error if the problem is not resolved.

I use the default configuration, nothing has been changed，i dont know where to change T_T

**Comment by RyanXLi** [comment]
Did you use 8 GPUs as our config did? The number of GPU used will affect the batch size and the learning rate will need to be changed correspondingly following the linear scaling principle.

**Comment by chenjiabo5197** [comment]
hello，i also have the same problem,how do you slove it?

**Comment by luxdong** [comment]
emm.. i meet this problem too. i train my custom dataset in yolov3 is good ,but train  with ssd300  it got the NaN problem.

**Comment by chenjiabo5197** [comment]
> 
> 
> emm.. i meet this problem too. i train my custom dataset in yolov3 is good ,but train with ssd300 it got the NaN problem.

reduce the lr can solve this problem

**Comment by luxdong** [comment]
> > emm.. i meet this problem too. i train my custom dataset in yolov3 is good ,but train with ssd300 it got the NaN problem.
> 
> reduce the lr can solve this problem

thanks .it work.
