### ISSUE TITLE
Asking about HTC with custom dataset

### ISSUE THREAD

**Issue by moonh1** [open-mmlab/mmdetection#3790]
Hi, I am trying to train HTC with own custom data.
When I looked through the document, it seemed like that I need semantic segmentation map such as thingandstuff for COCO.
Also I saw there is without_semantic_seg script for HTC.

Can anyone tell me how to train HTC without semantic map of own custom dataset?
Thank you!

**Comment by v-qjqs** [comment]
Hi, there exists official [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_without_semantic_r50_fpn_1x_coco.py) for training HTC without semantic segmentation maps.
