### ISSUE TITLE
mmdetection2.0：Failed when I tried to specify multiple GPU during training my dataset

### ISSUE THREAD

**Issue by Ann331** [open-mmlab/mmdetection#3793]
My instructions： python ./tools/train.py ./configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py --gpus 2

Error reporting information：
('MMDataParallel only supports single GPU training, if you need to'
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

Looking forward to your help...

**Comment by BQT11** [comment]
How to solve this problem?
