### ISSUE TITLE
running error on async inference

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3797]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.

**Describe the bug**
Hi there,

Following the async example, I'm using async API to run multiple object detection models on a single GPU (one is faster-rcnn, and another is reppoints). However, I find the following error. Could you give me some feedback? I'm using mmDetection v2.3.

`File "model_run_async.py", line 72, in <module> asyncio.run(main()) File "/opt/conda/lib/python3.7/asyncio/runners.py", line 43, in run return loop.run_until_complete(main) File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete return future.result() File "model_run_async.py", line 60, in main async_results = await asyncio.gather(*tasks) File "model_run_async.py", line 53, in detect return await async_inference_detector(model, img) File "/mmdetection/mmdet/apis/inference.py", line 150, in async_inference_detector result = await model.aforward_test(rescale=True, **data) File "/mmdetection/mmdet/models/detectors/base.py", line 116, in aforward_test return await self.async_simple_test(img[0], img_metas[0], **kwargs) File "/mmdetection/mmdet/models/detectors/base.py", line 80, in async_simple_test raise NotImplementedError NotImplementedError`

**Reproduction**
1. What command or script did you run?

```
async def main():
    config_file_one = 'xxx'
    checkpoint_file_one = 'xxx'

    config_file_two = 'xxx'
    checkpoint_file_two = 'xxx'

    config_file_three = 'xxx'
    checkpoint_file_three = 'xxx'

    config_file_four = 'xxx‘
    checkpoint_file_four = 'xxx'

    device = 'cuda:0'
    model_one = init_detector(config_file_one, checkpoint=checkpoint_file_one, device=device)
    model_two = init_detector(config_file_two, checkpoint=checkpoint_file_two, device=device)
    model_three = init_detector(config_file_three, checkpoint=checkpoint_file_three, device=device)
    model_four = init_detector(config_file_four, checkpoint=checkpoint_file_four, device=device)

    # queue is used for concurrent inference of multiple images
    streamqueue = asyncio.Queue()
    # queue size defines concurrency level
    streamqueue_size = 4

    for _ in range(streamqueue_size):
        streamqueue.put_nowait(torch.cuda.Stream(device=device))

    # test a single image and show the results
    img = 'xxx.jpeg' 
    img = mmcv.imread(img)

    async def detect(img, model):
        async with concurrent(streamqueue):
            return await async_inference_detector(model, img)

    models = [model_one, model_two, model_three, model_four]
    with profile_time('benchmark', 'async'):
        tasks = [
            asyncio.create_task(detect(img,model)) for model in models
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

Yes, I write my own code shown above.

3. What dataset did you use?

My own private dataset.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3: Tesla V100-PCIE-16GB
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.3.0
MMCV: 0.6.2
MMDetection: 2.2.0+d632ccc
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.1

2. You may add addition that may be helpful for locating the problem, such as
    mmDetection was installed on the docker.

**Error traceback**

```
`File "model_run_async.py", line 72, in <module> asyncio.run(main()) File "/opt/conda/lib/python3.7/asyncio/runners.py", line 43, in run return loop.run_until_complete(main) File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete return future.result() File "model_run_async.py", line 60, in main async_results = await asyncio.gather(*tasks) File "model_run_async.py", line 53, in detect return await async_inference_detector(model, img) File "/mmdetection/mmdet/apis/inference.py", line 150, in async_inference_detector result = await model.aforward_test(rescale=True, **data) File "/mmdetection/mmdet/models/detectors/base.py", line 116, in aforward_test return await self.async_simple_test(img[0], img_metas[0], **kwargs) File "/mmdetection/mmdet/models/detectors/base.py", line 80, in async_simple_test raise NotImplementedError NotImplementedError````

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by v-qjqs** [comment]
Hi, as the error traceback suggests, async_simple_test is not supported currently.

**Comment by shanggdlk** [comment]
> Hi, as the error traceback suggests, async_simple_test is not supported currently.

Thank you! Does that mean mmDetection for now only support some specific models? If so, which model does it support for now? Thanks!

**Comment by blackCmd** [comment]
> Hi, as the error traceback suggests, async_simple_test is not supported currently.

Oh I see...... ㅠ_ㅠ
Thank you
