### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by colt18** [open-mmlab/mmdetection#3799]
Hi,

Any efforts for Windows support for the foreseeable future? If not can you guide me with a link?

Thanks.

**Comment by v-qjqs** [comment]
Hi @colt18, sorry that there might be little efforts for Windows support in the foreseeable future.

**Comment by hellock** [comment]
@colt18 Windows support is ongoing. The main dependency `mmcv-full` has been tested, see [here](https://github.com/open-mmlab/mmcv/issues/587#issuecomment-699667619) for details.

**Comment by colt18** [comment]
@hellock  thanks for the link. In the meanwhile the latest is not supported for Windows but the `mmcv-full=1.1.3` with `pytorch=1.6.0` and `cuda=10.1` could be installed via this:

`pip install mmcv-full==1.1.3+torch1.6.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html`

**Comment by hellock** [comment]
@colt18 The latest version 1.1.6 has been supported.
