### ISSUE TITLE
When I set nproc_per_node >= 2, It raises ValueError: signal number 32 out of range

### ISSUE THREAD

**Issue by Lucklady** [open-mmlab/mmdetection#380]
I trained with default configs in pascal_vol/faster_rcnn*.py
My  CPU has 16 cores, if I want to use distributed training, what should I do? Thanks in advance.

**Comment by Lucklady** [comment]
Upgrade python to 3.6.6, problems disappeared, before that my python version is 3.6.5

**Comment by Lucklady** [comment]
Upgrade python to 3.6.6, problems disappeared, before that my python version is 3.6.5

**Comment by Single430** [comment]
thanks!!!
