### ISSUE TITLE
why shared head is not supported in HTC?

### ISSUE THREAD

**Issue by zhangshen12356** [open-mmlab/mmdetection#3804]
can i add shared head in htc_roi_head.py?

**Comment by v-qjqs** [comment]
Hi @zhangshen12356, We have not try to use IoULoss for retinanet yet, so we do not know the reasion either. 
Could you provide a reproducible config or command for us to debug?

**Comment by v-qjqs** [comment]
Hi @zhangshen12356, the shared head in HTC is not supported currently.

**Comment by zhangshen12356** [comment]
if i add shared head  will it occur error?

**Comment by ZwwWayne** [comment]
> if i add shared head will it occur error?

It will not if you implement it in a correct way. However, the performance should be lower than the current HTC (as Faster R-CNN C4 is lower than Faster R-CNN FPN). And the GPU memory will cost more than before.
