### ISSUE TITLE
cannot install mmcv by 'pip install mmcv-full==latest+torch1.5.0+cu101 -f http://download.openmmlab.com/mmcv/dist/index.html'

### ISSUE THREAD

**Issue by aimhabo** [open-mmlab/mmdetection#3806]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
(mmlab) wit@wit:~/mmdetection-20200921$ pip install mmcv-full==latest+torch1.5.0+cu101 -f http://download.openmmlab.com/mmcv/dist/index.html
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: http://download.openmmlab.com/mmcv/dist/index.html
WARNING: The repository located at download.openmmlab.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host download.openmmlab.com'.
ERROR: Could not find a version that satisfies the requirement mmcv-full==latest+torch1.5.0+cu101 (from versions: 1.0rc0, 1.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3)
ERROR: No matching distribution found for mmcv-full==latest+torch1.5.0+cu101

**Reproduction**
1. What command or script did you run?
```
conda create -n mmlab python=3.7
conda activate mmlab
conda install pytorch cudatoolkit=10.1 torchvision -c pytorch
pip install mmcv-full==latest+torch1.5.0+cu101 -f http://download.openmmlab.com/mmcv/dist/index.html
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
 -
3. What dataset did you use?
 -
**Environment**
channels:
  - defaults
show_channel_urls: true
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
remote_connect_timeout_secs: 60.0
remote_read_timeout_secs: 60.0

**Bug fix**
 -

**Comment by v-qjqs** [comment]
Hi @aimhabo, is your pytorch version compatible with mmcv version?

**Comment by sxlyiyiyi** [comment]
I also have this problem in windows.
ERROR: No matching distribution found for mmcv-full==latest+torch1.5.0+cu101
 Could not build wheels for mmcv-full which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

**Comment by ZwwWayne** [comment]
MMCV indeed does not provide a pre-built windows wheel.

**Comment by huangh12** [comment]
> 
> 
> MMCV indeed does not provide a pre-built windows wheel.

Does this mean there is no way install MMCV on win10?

**Comment by aimhabo** [comment]
You can use the old version 1.1.5, such as [mmcv_full-1.1.5+torch1.6.0+mmdet2.7](https://www.cnblogs.com/aimhabo/p/14119411.html)
