### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'

### ISSUE THREAD

**Issue by BlackHandguy** [open-mmlab/mmdetection#3807]
I have installed mmcv certainly, but .......version matching problem?
mmcv                      1.1.2                    pypi_0    pypi
mmdet                     0.6.0+a717a85             dev_0    <develop>

**Comment by zoucg** [comment]
> I have installed mmcv certainly, but .......version matching problem?
> mmcv 1.1.2 pypi_0 pypi
> mmdet 0.6.0+a717a85 dev_0

Can you tell me how you can solve this problem?

**Comment by BlackHandguy** [comment]
> > I have installed mmcv certainly, but .......version matching problem?
> > mmcv 1.1.2 pypi_0 pypi
> > mmdet 0.6.0+a717a85 dev_0
> 
> Can you tell me how you can solve this problem?

I uninstalled the mmcv 1.1.2, and installed the mmcv 0.4.3,
