### ISSUE TITLE
Any attempt for some new algorithms?

### ISSUE THREAD

**Issue by ming71** [open-mmlab/mmdetection#381]
Will you keep it maintained for some new algorithms such  as YOLOv3 and so on ?
Or just stop updating it ?==

**Comment by hellock** [comment]
Yes it will be maintained. Bug fixes and minor updates are always going on and we are also planing some major updates after ICCV. However, we have no recent plan for YOLO-series and contributions are welcome.

**Comment by ming71** [comment]
Thanks for your reply !! It really helps.
