### ISSUE TITLE
I want know how can I get the mmdetectionV0.6？

### ISSUE THREAD

**Issue by sandy-0326** [open-mmlab/mmdetection#3811]
If  I want to get other  version of mmdetection, how can i get them?
Thank you for answering!

**Comment by yuzhj** [comment]
[https://github.com/open-mmlab/mmdetection/releases/tag/v0.6.0](url)

**Comment by yuzhj** [comment]
https://github.com/open-mmlab/mmdetection/releases/tag/v0.6.0

**Comment by sandy-0326** [comment]
> https://github.com/open-mmlab/mmdetection/releases/tag/v0.6.0

OK! Thank you very much!
