### ISSUE TITLE
May I use the iterative method based on faster rcnn to change to cascade rcnn, but the following error was reported during the test

### ISSUE THREAD

**Issue by hyz0720** [open-mmlab/mmdetection#3812]
(iterdet) hyz@hyz-MS-7B89:~/下载/iterdet-master$ bash tools/dist_test.sh configs/iterdet/1.py work_dirs/iterdet/wider_cascade/epoch_1.pth 1 --show
[ ] 0/1000, elapsed: 0s, ETA:Traceback (most recent call last):
File "tools/test.py", line 149, in
main()
File "tools/test.py", line 134, in main
args.gpu_collect)
File "/home/hyz/下载/iterdet-master/mmdet/apis/test.py", line 86, in multi_gpu_test
result = model(return_loss=False, rescale=True, **data)
File "/home/hyz/anaconda3/envs/iterdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in call
result = self.forward(*input, **kwargs)
File "/home/hyz/anaconda3/envs/iterdet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 445, in forward
output = self.module(*inputs[0], **kwargs[0])
File "/home/hyz/anaconda3/envs/iterdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in call
result = self.forward(*input, **kwargs)
File "/home/hyz/下载/iterdet-master/mmdet/core/fp16/decorators.py", line 49, in new_func
return old_func(*args, **kwargs)
File "/home/hyz/下载/iterdet-master/mmdet/models/detectors/base.py", line 150, in forward
return self.forward_test(img, img_metas, **kwargs)
File "/home/hyz/下载/iterdet-master/mmdet/models/detectors/base.py", line 131, in forward_test
return self.simple_test(imgs[0], img_metas[0], **kwargs)
File "/home/hyz/下载/iterdet-master/mmdet/models/detectors/iterdet_faster_rcnn.py", line 95, in simple_test
x, img_metas, proposal_list, self.roi_head.test_cfg, rescale=rescale)
File "/home/hyz/下载/iterdet-master/mmdet/models/roi_heads/test_mixins.py", line 60, in simple_test_bboxes
bbox_results = self._bbox_forward(x, rois)
TypeError: _bbox_forward() missing 1 required positional argument: 'rois'
Traceback (most recent call last):
File "/home/hyz/anaconda3/envs/iterdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/hyz/anaconda3/envs/iterdet/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/hyz/anaconda3/envs/iterdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in
main()
File "/home/hyz/anaconda3/envs/iterdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hyz/anaconda3/envs/iterdet/bin/python', '-u', 'tools/test.py', '--local_rank=0', 'configs/iterdet/1.py', 'work_dirs/iterdet/wider_cascade/epoch_1.pth', '--launcher', 'pytorch', '--show']' returned non-zero exit status 1.

**Comment by hyz0720** [comment]
# model settings
model = dict(
    type='IterDetFasterRCNN',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,#-1,+1
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5,
        norm_cfg=dict(type='BN')),#
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),#beta
    roi_head=dict(
        type='CascadeRoIHead',
        num_stages=3,
        stage_loss_weights=[1, 0.5, 0.25],
        #type='StandardRoIHead',#
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', out_size=7, sample_num=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
         bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ]))
        #bbox_head=dict(
        #    type='Shared2FCBBoxHead',
        #    in_channels=256,
        #    fc_out_channels=1024,
        #    roi_feat_size=7,
        #    num_classes=1,#
        #    bbox_coder=dict(
        #        type='DeltaXYWHBBoxCoder',
        #        target_means=[0., 0., 0., 0.],
        #        target_stds=[0.1, 0.1, 0.2, 0.2]),
        #    reg_class_agnostic=True,#不確定
        #    loss_cls=dict(
        #        type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        #    loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))))#

# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            match_low_quality=True,
            ignore_iof_thr=-1),#0.5,-1
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,#-1,0
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    #rcnn=dict(
     #   assigner=dict(
      #      type='MaxIoUAssigner',
       #     pos_iou_thr=0.5,
        #    neg_iou_thr=0.5,
         #   min_pos_iou=0.5,
          #  match_low_quality=False,
           # ignore_iof_thr=-1),
        #sampler=dict(
         #   type='RandomSampler',
          #  num=512,
           # pos_fraction=0.25,
            #neg_pos_ub=-1,
            #add_gt_as_proposals=True),
        #pos_weight=-1,
        #debug=False))#three times
      rcnn=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.7,
                min_pos_iou=0.7,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)
    ])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.01, nms=dict(type='nms', iou_thr=0.5), max_per_img=1000),#0.01,0.05
    n_iterations=2#
)
# dataset settings
dataset_type = 'CrowdHumanDataset'
data_root = 'data/wider_person/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=[(1000, 600), (1666, 1000)], keep_ratio=True),#
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='AddHistory'),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'history', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore']),#
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'train.json',
        img_prefix=data_root + 'Images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'val.json',
        img_prefix=data_root + 'Images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'val.json',
        img_prefix=data_root + 'Images/',
        pipeline=test_pipeline))
# optimizer
optimizer = dict(
    type='Adam',
    lr=.0001
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    step=[16, 22])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 24
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/iterdet/wider_cascade'
load_from = None
resume_from = None
workflow = [('train', 1)]

**Comment by ZwwWayne** [comment]
It seems to be an issue with your code, as the input `rois` for bbox_forward is missing.
