### ISSUE TITLE
AttributeError: 'str' object has no attribute 'show_result'

### ISSUE THREAD

**Issue by vishaldhull09** [open-mmlab/mmdetection#3813]
when i ran
show_result_pyplot(img, result, model.CLASSES, score_thr=score_thr)

AttributeError    Traceback (most recent call last)
<ipython-input-23-b795e544cc29> in <module>
      1 show_result_pyplot(img, result, model.CLASSES,
----> 2             score_thr=score_thr)

~/Desktop/mmlab/mmdetection_object_detection_demo/mmdetection/mmdet/apis/inference.py in show_result_pyplot(model, img, result, score_thr, fig_size)
    165     if hasattr(model, 'module'):
    166         model = model.module
--> 167     img = model.show_result(img, result, score_thr=score_thr, show=False)
    168     plt.figure(figsize=fig_size)
    169     plt.imshow(mmcv.bgr2rgb(img))

AttributeError: 'str' object has no attribute 'show_result'

**Comment by yhcao6** [comment]
Wut's your running command? 
If you are playing with `demo/image_demo.py', I tried this command which can lead expected result without error.
```
python demo/image_demo.py demo/demo.jpg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py models/faster_rcnn/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
```

**Comment by vishaldhull09** [comment]
I m running this code
from mmdet.models.api import show_result_pyplot
i
mg = 'data/VOCdevkit/VOC2007/JPEGImages/0000001_05499_d_0000010.jpg'
result = inference_detector(model, img)

show_result_pyplot(img, result, model.CLASSES, score_thr=score_thr)

**Comment by Shubham-Saket** [comment]
Hello @vishaldhull09, 
call of the function should be like:
show_result_pyplot(model, result, img, score_thr=score_thr)
