### ISSUE TITLE
--Eval options parsing sequence

### ISSUE THREAD

**Issue by biyuruofeng** [open-mmlab/mmdetection#3815]
When I use -- Eval options to parse a sequence, I find that it is not possible to parse a sequence in a key value pair, but a string directly
```
    parser.add_argument(
        '--eval-options',
        nargs='+',
        action=DictAction,
        help='custom options for evaluation, the key-value pair in xxx=yyy '
        'format will be kwargs for dataset.evaluate() function')
```
`--eval-options "iou_thrs=[0.1]"`
In this case, I found that only "[0.1]" could be parsed as a string, not a list

**Comment by yhcao6** [comment]
It seems a bug, we will fix it soon.
