### ISSUE TITLE
Single class training

### ISSUE THREAD

**Issue by larspars** [open-mmlab/mmdetection#3816]
How should you set the num_classes parameter on the models, when training a detector with a single class?

This thread says you should set num_classes=2 (adding a class for background):

https://github.com/open-mmlab/mmdetection/issues/344

Is this still valid? I ask because training seems to work well enough with num_classes=1, and the defaults for coco are 80 (not 81).

**Comment by yhcao6** [comment]
In mmdetv2.0 you should `num_classes=1` (exclude background class), but if you use mmdetv1.0 you should set `num_classes=2`.

**Comment by larspars** [comment]
Aha, I see. Thanks!
