### ISSUE TITLE
Add scripts in tools/ to the pypi release

### ISSUE THREAD

**Issue by mprzewie** [open-mmlab/mmdetection#3819]
Hi! First, thanks for releasing MMDet to PyPI, it improved it's convenience greatly. Could you add the scripts provided in the `tools` directory to the released package, so that they can be used after installing mmdet that way? 

I believe it would be a nice simplification, because now, when one wants to use e.g. `tools/train.py` script, they must clone the repo instead of simply getting mmdet through `pip install`.

Thanks!

**Comment by RyanXLi** [comment]
Thanks. We do plan to add support for this in the future.
