### ISSUE TITLE
Multi-scale testing

### ISSUE THREAD

**Issue by yldrmBtn** [open-mmlab/mmdetection#3826]
I want to ask details related to multi-scale tarining. If we choose 3 scales for multi scale testing, does network runs over a image for 3 different scale and thane fuse results of these runs? I mean when we choose 3 scale for testing, does network runs 3 times for single image? As I understood, network choose a random scale and runs for that scale and network just runs once for a image. If I understood correctly, then what is the logic of multi scale testing?

**Comment by ZwwWayne** [comment]
The network will run on three scales of one image and then fuse the results.
