### ISSUE TITLE
Same color of instances(the color should be different for each instance) while visualizing instance masks on test data for the model trained on cascade mask rcnn

### ISSUE THREAD

**Issue by abubakar2141731** [open-mmlab/mmdetection#3827]
HOw to visualize different color for each instance mask, using mmdetection, please explain? right now i am getting the same color for each instance belonging to the same class in an image while testing the images.

**Comment by ZwwWayne** [comment]
Currently, mmdetection does not support to draw color based on instances. You may draw it by yourself.
