### ISSUE TITLE
A wechat  group for discussion about mmdetection

### ISSUE THREAD

**Issue by ming71** [open-mmlab/mmdetection#383]
![431188098](https://user-images.githubusercontent.com/43720092/54082562-e03d3e00-4352-11e9-9c1b-d2d75239cce9.jpg)

Shame to bother author with stupid questions , the established  wechat group is for discussion and sharing .Common questions supposed to be put on github instead of the group to benifit more people .

**Comment by runzeer** [comment]
could you update two-dimension code please？ The two-dimension code above has been out of date.

**Comment by ming71** [comment]
update the QR code:
![image](https://user-images.githubusercontent.com/43720092/55373071-8fc29600-5536-11e9-8f1d-df14490c442b.png)

**Comment by Wulingtian** [comment]
二维码失效了

**Comment by ming71** [comment]
No more updating here , if you wanna join the group , you can contact me by qq :1343545543 , and invite you through QR code。
If you just want some assistance on code , this repo annotate mmdetection and may help you:
https://github.com/ming71/mmdetection-annotated
