### ISSUE TITLE
Different number of images during training

### ISSUE THREAD

**Issue by efedoganay** [open-mmlab/mmdetection#3834]
Hi,

I created a custom coco dataset for Mask R-CNN training. It consists of 366 training images and 100 validation images and each of them is grayscale. However, during the training (with batch size 1) it shows that there are 309 images for training and 85 for validation. Is it because some of my annotations are wrongly formatted?

**Comment by yuzhj** [comment]
refer to this [function](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L96-L105)
