### ISSUE TITLE
question about config file：train img_scale

### ISSUE THREAD

**Issue by donglee-afar** [open-mmlab/mmdetection#384]
https://github.com/open-mmlab/mmdetection/blob/70383d4633fc8b30c5286f6833a267bcaf71808c/configs/cascade_mask_rcnn_r101_fpn_1x.py#L172
what's the meaning of it?
if the input image(w,h) w<h ,e.g. (500,1000) when training,
does it will zoom directly to （1333,800）
or it will automatically select long and short sides to (1000,500) and then transfer to (1333,800)

**Comment by ming71** [comment]
It also confuses me....It seems different from the implementions in certain papers?

**Comment by hellock** [comment]
See [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/transforms/resize.py#L94-L97) for details.
