### ISSUE TITLE
AttributeError：On testing with SABL head

### ISSUE THREAD

**Issue by longyueying** [open-mmlab/mmdetection#3845]
Hi
I used SABL in faster RCNN. the training process is normal, but some wrong occured when testing. The Traceback is as below:
```
File "/workspace/mmdetection/mmdet/models/roi_heads/test_mixins.py", line 73, in simple_test_bboxes                                                                        
    0) if bbox_pred is not None else [None, None]                                                   
0) if bbox_pred is not None else [None, None]                                                                                                                                
AttributeError: 'tuple' object has no attribute 'split'AttributeError                               
: 'tuple' object has no attribute 'split'  
```
I compared the output of **bbox_head** and **sabl_head** and found the tuple which return by the **reg_forward()** function of **mmdet/models/roi_heads/bbox_heads/sabl_head.py** may account for this wrong. the simple_test_bboxes() function in **mmdet/models/roi_heads/test_mixins.py** expects the bbox_pred to be a tensor whose format is ```tensor([[…, …, …],[…, …, …],[…, …, …]])```,but the bbox_pred  return by sabl_head has a format of 
```
(
tensor([[…, …, …],[…, …, …],[…, …, …]]), 
tensor([[…, …, …],[…, …, …],[…, …, …]])
) 
```
rather a format of 
```
tensor([
([…, …, …],[…, …, …]),
([…, …, …],[…, …, …]),
([…, …, …],[…, …, …])
])
```

**Comment by yuzhj** [comment]
@longyueying #3849 I have tested it in VOCDataset

**Comment by yuzhj** [comment]
@longyueying #3849 I have tested it with VOCDataset

**Comment by longyueying** [comment]
> @longyueying #3849 I have tested it with VOCDataset

thanks a lot.  the solution in your PR
```
 bbox_pred = (
                bbox_pred, ) if bbox_pred is not None else [None, None]```
doesn't split bbox_pred according to the batchsize. 
Do you set batchsize as 1 or 2?

**Comment by yuzhj** [comment]
No, my batch size is 4, and tested it with 2 gpus

**Comment by longyueying** [comment]
> No, my batch size is 4, and tested it with 2 gpus
**samples_per_gpu**  =  4?

**Comment by yuzhj** [comment]
> > No, my batch size is 4, and tested it with 2 gpus
> > **samples_per_gpu**  =  4?

yes

**Comment by longyueying** [comment]
Ok，I will try this. thanks

**Comment by yuzhj** [comment]
> > @longyueying #3849 I have tested it with VOCDataset
> 
> thanks a lot. the solution in your PR
> 
> ```
>  bbox_pred = (
>                 bbox_pred, ) if bbox_pred is not None else [None, None]
> ```
> 
> doesn't split bbox_pred according to the proposals number of each image.
> Do you set batchsize as 1 or 2?

an easy example:
```python
a = torch.rand(5,5)
a.split(5,0) == (a,)
```
the number of proposal == bbox_pred[0].shape[0]
so bbox_pred.split() == (bbox_pred, )

**Comment by yuzhj** [comment]
@longyueying hello, here is the latest code #3853

**Comment by longyueying** [comment]
@yuzhj ok，this modification seems to be right. thanks a lot!
