### ISSUE TITLE
tutorial updates about adding new modules

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmdetection#3846]
In `https://github.com/open-mmlab/mmdetection/edit/master/docs/tutorials/new_modules.md` (v2.4.0), now `https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_models.md` (v2.5.0)
I believe you mean
```python
from ..builder import NECKS
```
not
```python
from ..registry import NECKS
```

**Comment by ZwwWayne** [comment]
Hi @hubutui ,
I missed this issue before. Thanks for your report, would you like to create a PR to fix that?

**Comment by hubutui** [comment]
@ZwwWayne I believe you could fix it in a minute. I'm now more interested in https://github.com/open-mmlab/mmdetection/issues/3852
