### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'log_level'

### ISSUE THREAD

**Issue by vishaldhull09** [open-mmlab/mmdetection#3847]
i am trying to run train.py with cascade rcnn model with tensorboard  on and i am  getting this error

log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])

**Comment by ZwwWayne** [comment]
Please use the `error template`, or at least provide a config and command to reproduce your errors.
