### ISSUE TITLE
new loss when test(2 ways):error

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmdetection#3851]
![image](https://user-images.githubusercontent.com/57787557/94399171-7933e400-0199-11eb-9e6a-63484dae5968.png)
![image](https://user-images.githubusercontent.com/57787557/94398748-b77cd380-0198-11eb-9e6a-8c30942eeeb5.png)
my config of cls_loss:
![image](https://user-images.githubusercontent.com/57787557/94399003-32de8500-0199-11eb-946e-8bb8bac7b608.png)
![image](https://user-images.githubusercontent.com/57787557/94399044-40940a80-0199-11eb-837e-a6da45edea3f.png)

**Comment by mytk2012** [comment]
i test the code in 2 ways:test.py and dist_test.sh

**Comment by mytk2012** [comment]
class_name=None，but why?

**Comment by mytk2012** [comment]
I have debuged it:labels are  all 8,it it normal?isn't it from range 0 to len(class)?

**Comment by mytk2012** [comment]
I have debuged for times.It seemed that my loss for train has failed causing labels to be all 8,but why the loss has a value rather than report an error?

**Comment by hhaAndroid** [comment]
Does the problem still exist?
