### ISSUE TITLE
support for validate with batch size > 1

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmdetection#3852]
Hi, glad to know we could run the inference with batch size > 1, any plan to support validation during training with batch size > 1? According to 
https://github.com/open-mmlab/mmdetection/blob/c8511649550834ea168f610411a47a39cf194767/mmdet/apis/train.py#L113-L120
batch size is set to 1 for validation.

**Comment by ZwwWayne** [comment]
Hi @hubutui ,
Thanks for your suggestion. We may add this feature in the future.

**Comment by hubutui** [comment]
@ZwwWayne Could you give me some sugesstions if I'd like to implement similar feature?
