### ISSUE TITLE
About old version of mmdetection

### ISSUE THREAD

**Issue by AnnabelChen51** [open-mmlab/mmdetection#3855]
Dear Author,
Thank you very much for your great work! I wanna ask is there any place to download the old version package of mmdetection and the old version of pretrained model zoos? Your reply is greatly appreciated.

**Comment by RyanXLi** [comment]
You can download old version of MMDetection in the [release page](https://github.com/open-mmlab/mmdetection/releases). You can also try to checkout the old version of the repo to find the old model zoos but they are not guaranteed to all be present if it is too distant.
