### ISSUE TITLE
Something about AutoAugment 

### ISSUE THREAD

**Issue by Qianshaowei** [open-mmlab/mmdetection#3856]
Hello, I found that there are AutoAugment modules in our code. So how to use AutoAugment module to search effective data Augment solutions? I will be grateful for your answer.

**Comment by v-qjqs** [comment]
Hi @Qianshaowei, the AutoAugment modules are implemented in process and not completely finished yet. Meanwhile, now we only implement AutoAugment based on the searched policies from google's official paper . Effectively searching method of AutoAugment for your dataset is not supported.

**Comment by rhythm-A** [comment]
Can you give me some advice to use auto_augment.py?such as polices：v1?

**Comment by Qianshaowei** [comment]
> Can you give me some advice to use auto_augment.py?such as polices：v1?

I suggest you refer to the official documentation to rewrite the auto_augment.py, and you have to pay attention to the changes of the bounding box.
