### ISSUE TITLE
In rpn.py (mmdet->models->detectors) is the function show_result used to display ground truth bounding box?

### ISSUE THREAD

**Issue by bharath-07** [open-mmlab/mmdetection#3860]

**Comment by bharath-07** [comment]
Also when is the function called? Because when i use --show I am only able to display the prediction bounding box and not the ground truth.

**Comment by RyanXLi** [comment]
Hi! This funtion only shows the result (output) of the network instead of the groundtruth.

**Comment by bharath-07** [comment]
How to view the ground truth bounding box in the image?

**Comment by yuzhj** [comment]
@bharath-07 a lightweight GUI for visualizing the detection results, you can refer [DetVisGUI](https://github.com/Chien-Hung/DetVisGUI/tree/mmdetection) project.

**Comment by bharath-07** [comment]
Thanks! That is helpful
