### ISSUE TITLE
Solution for editing configuration file via scripts

### ISSUE THREAD

**Issue by MARMOTatZJU** [open-mmlab/mmdetection#3861]
**Describe the feature**

**Motivation**

The current configuration system of MMDetection use *.py*. However, the editing of a set of configs in *.py* files is not as easy as other config system such as YAML/YACS (used by Detectron2). 

The editing means. for example, adding an extra training dataset or changing a certain hyper-paramter, etc. This is easy to achieve under YAMLYACS by loading the YAML, modifying the desired item, and reserializing the config again into YAML.

Thus, could you please provide some solution for editing MMDetection's configuration file via scripts? Thanks in advance.

**Related resources**

[configuration system of Detectron2](https://github.com/facebookresearch/detectron2/tree/master/configs)

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hellock** [comment]
Thanks for your feedback!
1. We support py/yaml/json for config files with unified apis, not only py files.
2. Could you be more specific on `not easy to edit`? We should have supported the same way as yacs.

**Comment by MARMOTatZJU** [comment]
Thanks for your quick answer!

1. I didn't find information about yaml/json configuration files (e.g. [Official Description for Configuration System](https://mmdetection.readthedocs.io/en/latest/config.html) ). Could you please provide the description for yaml/json?

2. By "not easy to edit", I mean not easy for some high-level script to automatically change config & run training. For example, in my case I'd like to routinely launch a training/benchmarking task, but automatically edit the config every time.

**Comment by MARMOTatZJU** [comment]
I found the documentation in mmcv.utils.Config
https://mmcv.readthedocs.io/en/latest/utils.html

**Comment by MARMOTatZJU** [comment]
No further question. Thanks again!
