### ISSUE TITLE
I can't test in video

### ISSUE THREAD

**Issue by Tsu-t** [open-mmlab/mmdetection#3864]
I tried to test my dataset in video from code of official page.
It didn't exist error message, it was only thinking and didn't work correctly. could you help me?

from mmdet.apis import init_detector, inference_detector
import mmcv

config_file = 'config.py'
checkpoint_file = './work_dir/latest.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')

video = mmcv.VideoReader('video.mp4')
for frame in video:
      result = inference_detector(model, frame)
      model.show_result(frame, result, wait_time=1)

**Comment by ZwwWayne** [comment]
Hi @Tsu-t ,
What model do you use? Could you follow the `error template` to provide more information with command and code for use to reproduce your issue?

**Comment by Tsu-t** [comment]
> Hi @Tsu-t ,
> What model do you use? Could you follow the `error template` to provide more information with command and code for use to reproduce your issue?

Hi @ZwwWayne ,
My using model is "cascade_mask_rcnn", and I was able to train and test in image by Coco dataset. That config file is changed only coco format and some Parameters from original.

**Comment by neomukul** [comment]
@Tsu-t Are you able to resolve this issue because I am also getting the same issue, the model is just working and not displaying anything?

**Comment by neomukul** [comment]
@ZwwWayne in my case i am using faster_rcnn_x101_64x4d_fpn_2x_coco.py

**Comment by Tsu-t** [comment]
@neomukul I haven't solved yet. I want someone to help because I'm giving up.

**Comment by neomukul** [comment]
@Tsu-t i was advised to use "kodec" to resolve this issue, but I don't know what is kodec????
