### ISSUE TITLE
mmdet bbox_nms nonzero warning

### ISSUE THREAD

**Issue by pecanjk** [open-mmlab/mmdetection#3865]
/opt/model_factory/mmdetection/mmdet/core/post_processing/bbox_nms.py:54: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /tmp/pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  labels = valid_mask.nonzero()[:, 1]

**Comment by shinya7y** [comment]
Duplicate https://github.com/open-mmlab/mmdetection/issues/3467
`labels = valid_mask.nonzero(as_tuple=False)[:, 1]`
