### ISSUE TITLE
Cannot modify 'num_classes' in 'FusedSemanticHead' in htc config file

### ISSUE THREAD

**Issue by mcdy143** [open-mmlab/mmdetection#3868]
I am training an htc model on a custom dataset. When I try to modify 'num_classes' in 'FusedSemanticHead' in the htc_r50_fpn_1x_coco.py config file, I get an error before training starts:

`File "/home/yxw4wp8/14-mmdet_2.0/mmdetection/mmdet/models/roi_heads/htc_roi_head.py", line 278, in forward_train
    gt_labels[j])
  File "/home/yxw4wp8/14-mmdet_2.0/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py", line 105, in assign
    overlaps = self.iou_calculator(gt_bboxes, bboxes)
  File "/home/yxw4wp8/14-mmdet_2.0/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py", line 31, in __call__
    return bbox_overlaps(bboxes1, bboxes2, mode, is_aligned)
  File "/home/yxw4wp8/14-mmdet_2.0/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py", line 126, in bbox_overlaps
    eps = union.new_tensor([eps])
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1573049310284/work/c10/cuda/CUDACachingAllocator.cpp:569)`

When I leave that field as is, the training starts fine. Could anyone explain why I need to leave 183 (number of coco stuff classes) as it is?

**Comment by ZwwWayne** [comment]
The error message shown here has nothing to do with the `FusedSemanticHead`. 
You can set `CUDA_LAUNCH_BLOCKING=1` when you run your code thus the error will be reported from the real place.

Please use the `reimplementation questions` to report your reimplementation issue.
