### ISSUE TITLE
undefined symbol: _ZN3c1010Dispatcher11reportErrorERKNS_13DispatchTableENS_8optionalINS_11DispatchKeyEEE

### ISSUE THREAD

**Issue by neomukul** [open-mmlab/mmdetection#3871]
Hello All,

I am trying to follow the mmdet tutorial and while running the third cell I am facing this issue can anyone help me to resolve this??

I've installed mmcv-full.

ImportError                               Traceback (most recent call last)
<ipython-input-37-996fc3bbb871> in <module>
     10 
     11 #import mmcv
---> 12 from mmcv.ops import get_compiling_cuda_version, get_compiler_version
     13 print(get_compiling_cuda_version())
     14 print(get_compiler_version())

/usr/local/lib/python3.6/dist-packages/mmcv/ops/__init__.py in <module>
----> 1 from .bbox import bbox_overlaps
      2 from .carafe import CARAFE, CARAFENaive, CARAFEPack, carafe, carafe_naive
      3 from .cc_attention import CrissCrossAttention
      4 from .corner_pool import CornerPool
      5 from .deform_conv import DeformConv2d, DeformConv2dPack, deform_conv2d

/usr/local/lib/python3.6/dist-packages/mmcv/ops/bbox.py in <module>
      1 from ..utils import ext_loader
      2 
----> 3 ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
      4 
      5 

/usr/local/lib/python3.6/dist-packages/mmcv/utils/ext_loader.py in load_ext(name, funcs)
      9 
     10     def load_ext(name, funcs):
---> 11         ext = importlib.import_module('mmcv.' + name)
     12         for fun in funcs:
     13             assert hasattr(ext, fun), f'{fun} miss in module {name}'

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ImportError: /usr/local/lib/python3.6/dist-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1010Dispatcher11reportErrorERKNS_13DispatchTableENS_8optionalINS_11DispatchKeyEEE

**Comment by ZwwWayne** [comment]
Please follow the [trouble shooting page](https://mmdetection.readthedocs.io/en/latest/trouble_shooting.html#trouble-shooting) here. It is very likely that your MMCV is compiled in an environment but ran in another environment.
