### ISSUE TITLE
Log is missing for faster rcnn with different losses

### ISSUE THREAD

**Issue by roywei** [open-mmlab/mmdetection#3872]
Hi,

The logs from these experiments are missing:

https://github.com/open-mmlab/mmdetection/tree/master/configs/faster_rcnn

R-50-FPN | IoULoss |   |   | 37.9 | model \| log
-- | -- | -- | -- | -- | --
R-50-FPN | GIoULoss |   |   | 37.6 | model \| log
R-50-FPN | BoundedIoULoss |   |   | 37.4 | model \| log

Could you share this if available? I'm interested in reproducing the AP results on GIOU.

Thanks!

**Comment by ZwwWayne** [comment]
Thanks for your report, we will update the links.

**Comment by roywei** [comment]
I was able to reproduce the result. GIoU has better result than IoU which different than the table above.
You can use my logs:
[logs.zip](https://github.com/open-mmlab/mmdetection/files/5352368/logs.zip)

**Comment by xvjiarui** [comment]
This issue is fixed.
