### ISSUE TITLE
import error in async_benchmark.py

### ISSUE THREAD

**Issue by frnhfr** [open-mmlab/mmdetection#3874]
hi,
the async_benchmark.py script isnt working anymore. im thinking its because the function name show_result() changed to show_result_pyplot() in mmdet.apis.inference.

**Comment by ZwwWayne** [comment]
Hi @frnhfr ,
Thanks for your report, would you like to create a PR to fix that?

**Comment by ZwwWayne** [comment]
Fixed in https://github.com/open-mmlab/mmdetection/pull/4367
