### ISSUE TITLE
Any idea about implementation of multiple heads?

### ISSUE THREAD

**Issue by MakeCent** [open-mmlab/mmdetection#3877]
I want to build a model with multiple heads, e.g. multiple fully-connected classification heads, and train them according to the input. I will assign an auxiliary value into the label of each input sample and train the head corresponding to that auxiliary value. Does anyone ever tried to do this? Any suggestions will be very helpful. Thanks!

**Comment by ZwwWayne** [comment]
The [doc](https://mmdetection.readthedocs.io/en/latest/tutorials/new_modules.html#add-new-heads) could help. The implementation of [TSD based on mmdet](https://github.com/Sense-X/TSD) does a similar thing, which might also do some help.

**Comment by Qiqi-0810** [comment]
> The [doc](https://mmdetection.readthedocs.io/en/latest/tutorials/new_modules.html#add-new-heads) could help. The implementation of [TSD based on mmdet](https://github.com/Sense-X/TSD) does a similar thing, which might also do some help.

Hi, @ZwwWayne  I met the same problem now, however I find the doc you provided didn't exist anymore, whould you mind share it again? Thanks a lot
