### ISSUE TITLE
a question of GenericRoIExtractor

### ISSUE THREAD

**Issue by DingShengLin** [open-mmlab/mmdetection#3878]
In mmdet/models/roi_heads/roi_extractors/generic_roi_extractor.py, the process of extract RoI is :
roi_feats = feats[0].new_zeros(
      rois.size(0), self.out_channels, *out_size)
for i in range(num_levels):
      roi_feats_t = self.roi_layers[i](feats[i], rois)
            ... ....
      if self.aggregation == 'sum':
                # and sum them all
                roi_feats += roi_feats_t  
I have a question:
     fpn's output feature maps have different size,   since roi remain unchanged,  does this direct addition lead to an out of bounds?

**Comment by ZwwWayne** [comment]
The ROI layers already rescaled the size of ROI before using them to crop the features, using the argument `spatial_scale` as described in the [documentation](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_align.py#L102).
