### ISSUE TITLE
为什么不能复现cascade-rcnn和cascade_rcnn_dconv_c3-c5_r50结果呢

### ISSUE THREAD

**Issue by timcredy** [open-mmlab/mmdetection#388]
我尝试了提供的基线配置来复现cascade-rcnn和cascade_rcnn_dconv_c3-c5_r50的结果，采用提供的配置文件，使用8GPU，发现前1代loss下降非常快，但到0.4几和0.3几就再也不下降了，评估效果也很差，map 0.07的值，为什么不能复现cascade-rcnn和cascade_rcnn_dconv_c3-c5_r50结果呢
问题出在哪里了呢？

**Comment by hellock** [comment]
Could you provide a more precise description? I cannot understand your problem clearly.
