### ISSUE TITLE
C++ Library containing cuda_ops(nms, RoIAlign) on Windows 10.

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#3881]
Dear Authors,
I am looking for a cuda implementation of ops (nms, roi_align etc) that can be used as C++ library on Windows. I first turn to torchvision, they claim to have C++ API but the build process on Windows is painful and bugs everywhere. I see mmcv-full supports compilation on Windows, I am wondering if there is any way to turn the complied objects(cuda impl of nms, roi_align etc) into a C/C++ library or they are already C/C++ libraries.

**Comment by ZwwWayne** [comment]
This issue should be raised in MMCV.

Some of the operators, e.g., NMS, roi_align has C++ implementation while some not. You can find their implementation [here](https://github.com/open-mmlab/mmcv/tree/master/mmcv/ops/csrc/pytorch).
