### ISSUE TITLE
How can I set the checkpoint saving interval?

### ISSUE THREAD

**Issue by lmomoy** [open-mmlab/mmdetection#3884]
Before I can set it through checkpoint_config in config files, but it seems that it have been removed from config file.

**Comment by ZwwWayne** [comment]
The config still contain this key, we only move it to the `[default_runtime.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/default_runtime.py)` for config inheritance. You can still modify it in your own config. The documentation for the new config system is [here](https://mmdetection.readthedocs.io/en/latest/config.html#config-system).
