### ISSUE TITLE
Any potential issue with RTX 30XX series? 

### ISSUE THREAD

**Issue by StringBottle** [open-mmlab/mmdetection#3888]
Before purchasing RTX 30XX series, I would like to check if any potential issue can occur while using RTX 30XX series.

As far as I looked through Pytorch community, I think CUDA version compatibility could cause an error.

I think A CUDA version issue can be resolved with further updates but I wanted to ask maintainers' opinion on this.

Thank you.

**Comment by StringBottle** [comment]
It seems that RTX 30XX series only support CUDA 11.X series.

pytorch/pytorch#45028

**Comment by ZwwWayne** [comment]
If Pytorch supports the new GPUs well, then there should be no big issues in MMDetection.

**Comment by gpogorzelski** [comment]
I tried to run mmdet training on a few RTX 3090 and the training crashes at random times. With a single 3090 gpu it only crashed during evaluation after the first epoch. I used pytorch nightly 1.7 and cuda 11

**Comment by StringBottle** [comment]
@gpogorzelski 

Can CUDA 11.x series only run with Pytorch nightly version? Or have you tried to build pytorch under 1.6.x version from the source?

**Comment by gpogorzelski** [comment]
@StringBottle 
I haven tried it so I cant tell you. Basically only CUDA 11+ supports ampere architecture gpus, so this is your only limitation.
