### ISSUE TITLE
How to change datatype fp16 to fp32?

### ISSUE THREAD

**Issue by blackCmd** [open-mmlab/mmdetection#3893]
When I train and inference, I want to change datatype fp16 to fp32 or fp32 to fp16.

Where can I change that in source code?

Thank you.

**Comment by yhcao6** [comment]
You can refer to the config of [fp16 faster rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/fp16/faster_rcnn_r50_fpn_fp16_1x_coco.py).
You only need to append
```
# fp16 settings
fp16 = dict(loss_scale=512.)
```
in the config file.

**Comment by blackCmd** [comment]
> You can refer to the config of [fp16 faster rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/fp16/faster_rcnn_r50_fpn_fp16_1x_coco.py).
> You only need to append
> 
> ```
> # fp16 settings
> fp16 = dict(loss_scale=512.)
> ```
> 
> in the config file.

Wow! You saved me. 
Thanks 🙂!
