### ISSUE TITLE
How can I do batch inference?

### ISSUE THREAD

**Issue by hairzooc** [open-mmlab/mmdetection#3894]
Hi, Thank you for the great repo. :)

I want to do batch inference with pretrained models but I couldn't find simple and easy way to do that.
I've seen some issues regarding batch inference but couldn't understand exactly what to do.
Can anyone help me out?

**Comment by hubutui** [comment]
check the [tutorial](https://mmdetection.readthedocs.io/en/latest/getting_started.html#test-a-dataset), and simply change the batch size.

**Comment by yhcao6** [comment]
You can add `--cfg-options data.test.samples_per_gpu=n` in your bash command, `n` means the batch size
For example if you want to test faster rcnn with batch size 2, the following is the command:
```
python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py [checkpoint] --eval bbox --cfg-options data.test.samples_per_gpu=2
```
