### ISSUE TITLE
Getting coordinates of bounding boxes

### ISSUE THREAD

**Issue by malizia88** [open-mmlab/mmdetection#3897]
First of all I would like to thank the creators for providing such a useful package, my kudos.

I'm using a pretrained Cascade mask R-CNN HRNet based model (From CascadeTabNet) to detect tables and cells inside the table in an image (Using CPU only on ubuntu 18.04). The results seem to be very promising. I now want to get the coordinates of the cells so I can compare them with the results of google OCR to get the actual text inside the identified cells. I understand I can get the bounding boxes from:

`result = inference_detector(model, img)`

However I do not understand the contents of `result `due to my limited knowledge of python and being new to object detection in general. Upon printing `result ` I get to see a bunch of True and False values which I can't make sense of. Can someone explain me the steps to get the bounding boxes? I would really appreciate your help. Thankyou

**Comment by ZwwWayne** [comment]
The results contain both bounding boxes and masks because you are using Cascade Mask RCNN. It is a tuple of (bbox, segm).

**Comment by malizia88** [comment]
Thank you, I figured that out after a bit of pain. Here's my code, adapted from CascadeTabNet if someone else is trying to do the same and Cant figure it out.

```
res_borderTable = []
res_borderlessTable = []
res_cell = []

## for tables with borders
for r in result[0][0]:
    if r[4]>.85:
        res_borderTable.append(r[:4].astype(int))
    ## for cells
for r in result[0][1]:
    if r[4]>.85:
        r[4] = r[4]*100
        res_cell.append(r.astype(int))
    ## for borderless tables
for r in result[0][2]:
    if r[4]>.85:
        res_borderlessTable.append(r[:4].astype(int))
```

**Comment by earlng** [comment]
Hi @malizia88! I just wanted to say *thank you*! I've been bashing my head against the wall for the last 2 hours trying to figure out why `result`'s structure looked so weird. I didn't realize it placed it in different positions in `results[0]` based on what type of "object" it was.

I was wondering, do you happen to remember where you came across this information? Possibly documentation? I wanna study up on how it behaves.

Thank you!

**Comment by vaishalisingh-ds** [comment]
> Thank you, I figured that out after a bit of pain. Here's my code, adapted from CascadeTabNet if someone else is trying to do the same and Cant figure it out.
> 
> ```
> res_borderTable = []
> res_borderlessTable = []
> res_cell = []
> 
> ## for tables with borders
> for r in result[0][0]:
>     if r[4]>.85:
>         res_borderTable.append(r[:4].astype(int))
>     ## for cells
> for r in result[0][1]:
>     if r[4]>.85:
>         r[4] = r[4]*100
>         res_cell.append(r.astype(int))
>     ## for borderless tables
> for r in result[0][2]:
>     if r[4]>.85:
>         res_borderlessTable.append(r[:4].astype(int))
> ```

Thankyou so much! It worked perfectly.
