### ISSUE TITLE
RuntimeError: expected dtype Float but got dtype Half

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#3898]
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
**python tools/train.py configs/fp16/yolov3_d53_fp16_mstrain_273e_voc0712.py --work-dir experiments/fp16_test**
![image](https://user-images.githubusercontent.com/24897773/95441452-bc0d6d00-098c-11eb-9c12-e154c2ef86f4.png)

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

**I add a new config file at file configs/pascal_voc/yolov3_d53_mstrain-416_273e_voc0712.py** 

3. What dataset did you use?
**Pascal_VOC**
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
![image](https://user-images.githubusercontent.com/24897773/95440670-caa75480-098b-11eb-9114-36615aef14c2.png)

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
Does the problem still exist?
