### ISSUE TITLE
The model of YOLO v3 is larger than downloaded model

### ISSUE THREAD

**Issue by lmomoy** [open-mmlab/mmdetection#3899]
My trained YOLO v3 model is 492.7MB, but the model you offered is 236.6MB. I want to know whether I have something wrong?

**Comment by yuzhj** [comment]
Your model records the optimizer information

**Comment by yuzhj** [comment]
Your model contains the optimizer information

**Comment by lmomoy** [comment]
> Your model contains the optimizer information

How can I remove these information?

**Comment by yuzhj** [comment]
it won't affect your use, if you really want to reduce the size of model, you can re-save the model like the following
```python
a = torch.load('your-model-path')
b = dict(state_dict=a['state_dict'])
torch.save(b,'new-path')
```

**Comment by hellock** [comment]
> it won't affect your use, if you really want to reduce the size of model, you can re-save the model like the following
> 
> ```python
> a = torch.load('your-model-path')
> b = dict(state_dict=a['state_dict'])
> torch.save(b,'new-path')
> ```

Better to keep the meta info in the checkpoints. There is a tool for removing optimizer (and append the hash to the filename): https://github.com/open-mmlab/mmdetection/blob/master/tools/publish_model.py.
