### ISSUE TITLE
Bounding Box format Question In Customize Datasets/An example of customized dataset

### ISSUE THREAD

**Issue by PofeiShit** [open-mmlab/mmdetection#3901]
#
000001.jpg
1280 720
2
10 20 40 60 1
20 40 50 60 2
#
000002.jpg
1280 720
3
50 20 40 60 2 # this line may be error. It seems x, y, w, h format. 
20 40 30 45 2
30 40 50 60 3
I use faster_rcnn_r50_fpn to train one of my own datasets gets loss_bbox=nan problem with x, y, w, h format. But in x_min, x_max, y_min, y_max format, there is no nan problem and inference result is good

**Comment by hellock** [comment]
xmin, ymin, xmax, ymax
