### ISSUE TITLE
ga-retinanet-r50-caffe

### ISSUE THREAD

**Issue by Markovcom** [open-mmlab/mmdetection#3902]
http://download.openmmlab.com/mmdetection/v2.0/guided_anchoring/ga_retinanet_r50_caffe_fpn_1x_coco/ga_retinanet_r50_caffe_fpn_1x_coco_20200531-902ffd79.pth 
This model is not the final model but it is the epoch_9.pth.
![image](https://user-images.githubusercontent.com/26458922/95650130-15ec6f00-0b14-11eb-98b8-8a089c8d8f22.png)

**Comment by myownskyW7** [comment]
Thanks for your report. We will update the checkpoint asap.

**Comment by myownskyW7** [comment]
https://github.com/open-mmlab/mmdetection/pull/3983
