### ISSUE TITLE
how to train my imageset with .bmp format

### ISSUE THREAD

**Issue by tingfengwanxiao** [open-mmlab/mmdetection#3904]
I wan't to train my dataset in faster-rcnn,but I meet the error like that
----------------------------------------
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOCdevkit/VOC2007/JPEGImages/001.jpg'
-------------------------------------
it‘s because that my JPEGImages have the picture 001.bmp
I change the demo in mmdetection/tools/convert_datasets/pascalvoc.py in line 84 and another place from the .jpg to .bmp
---------------------------------------------
img_paths = [
            f'VOC{year}/JPEGImages/{img_name}.bmp' for img_name in img_names
        ]
-----------------------------------------------
filename = f'JPEGImages/{img_id}.bmp'
-------------------------------------------------------------
while it doesn't work,how can I do,thank you!

**Comment by yuzhj** [comment]
modify this [function](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/xml_style.py#L27-L59)

**Comment by tingfengwanxiao** [comment]
> modify this [function](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/xml_style.py#L27-L59)

it doesn't work

**Comment by yuzhj** [comment]
@tingfengwanxiao it's a little strange, i tested several images which format is bitmap, i could train the model normally

**Comment by tingfengwanxiao** [comment]
> @tingfengwanxiao it's a little strange, i tested several images which format is bitmap, i could train the model normally

Have you only modify the demo there?is there any cache file I must clear to make a new load?

**Comment by yuzhj** [comment]
Yes, I only modified the load_annotations function of xml_style.py
