### ISSUE TITLE
died with <Signals.SIGKILL: 9>

### ISSUE THREAD

**Issue by 619774263** [open-mmlab/mmdetection#3907]
Environment:
    sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3: TITAN RTX
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.4.0
MMCV: 0.4.4
MMDetection: 1.1.0+612916b
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0

/home/ps/anaconda3/envs/road_dyr/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/ps/anaconda3/envs/road_dyr/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/ps/anaconda3/envs/road_dyr/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/ps/anaconda3/envs/road_dyr/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/road_dyr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ps/anaconda3/envs/road_dyr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ps/anaconda3/envs/road_dyr/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/ps/anaconda3/envs/road_dyr/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ps/anaconda3/envs/road_dyr/bin/python', '-u', './tools_1.0/train.py', '--local_rank=3', './configs_1.0/9_25_road/10_9_hr32_double_mask_rcnn_gdice_bfp_roi14.py', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>.

**Comment by Complicateddd** [comment]
This problem may cause by that u use command kill -9 xxx many times.
You could set num_works=0 or reboot your machine

**Comment by 619774263** [comment]
> This problem may cause by that u use command kill -9 xxx many times.
> You could set num_works=0 or reboot your machine

**Comment by 619774263** [comment]
> This problem may cause by that u use command kill -9 xxx many times.
> You could set num_works=0 or reboot your machine

Thank ,you! I'll try it later.Somtimes the method you said can work.The application ran well , but died suddenly! When I ran it again, the above problem came to me!!!

**Comment by Complicateddd** [comment]
> > This problem may cause by that u use command kill -9 xxx many times.
> > You could set num_works=0 or reboot your machine
> 
> Thank ,you! I'll try it later.Somtimes the method you said can work.The application ran well , but died suddenly! When I ran it again, the above problem came to me!!!

It’s best to avoid frequent use of the command ‘kill -9 xxx’, you can try to use ‘kill xxx’. In my environment, after I restarted the machine, this problem basically did not occur.

**Comment by 619774263** [comment]
> > > This problem may cause by that u use command kill -9 xxx many times.
> > > You could set num_works=0 or reboot your machine
> > 
> > 
> > Thank ,you! I'll try it later.Somtimes the method you said can work.The application ran well , but died suddenly! When I ran it again, the above problem came to me!!!
> 
> It’s best to avoid frequent use of the command ‘kill -9 xxx’, you can try to use ‘kill xxx’. In my environment, after I restarted the machine, this problem basically did not occur.



> > > This problem may cause by that u use command kill -9 xxx many times.
> > > You could set num_works=0 or reboot your machine
> > 
> > 
> > Thank ,you! I'll try it later.Somtimes the method you said can work.The application ran well , but died suddenly! When I ran it again, the above problem came to me!!!
> 
> It’s best to avoid frequent use of the command ‘kill -9 xxx’, you can try to use ‘kill xxx’. In my environment, after I restarted the machine, this problem basically did not occur.

How to set  num_works=0，in config files setting workers_per_gpu=0? I reboot my machine,but the error still exist.

**Comment by xvjiarui** [comment]
Hi @619774263 
Yes. You need to set it in config file.
