### ISSUE TITLE
Assigning class names to checkpoint's meta data

### ISSUE THREAD

**Issue by colt18** [open-mmlab/mmdetection#3908]
I'm getting following after initializing a detector. 

```
UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
```
Here is the code snippet:
```
config_file = './configs/my_conf/myconf.py'
checkpoint_file = 'logs/latest.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
```

However I do have `cfg.classes=('class1','class2','class3')`. I could add a dict key after loading checkpoint file for a workaround but I do not wanna do that. Am I missing something out?

**Comment by ZwwWayne** [comment]
For now, this seems to be the only workaround, we will enhance this part in the future.
