### ISSUE TITLE
how to generate bbox embedding giving a pretrained model along with bbox

### ISSUE THREAD

**Issue by xwuShirley** [open-mmlab/mmdetection#3909]
Hi there,

Thank you very much for the open-source code and the models. I have a question regarding to **extracting features given a bbox and pre-trained fast-rcnn model**. It might be very straightforward. But I am new to mmdetection.  I went through the tutorials but didn't find what I need.   It would be great if you could give some hint. In fact, my question is similar to the following issue which has been closed.
https://github.com/open-mmlab/mmdetection/issues/1046 

Thank you very much.
Best,

**Comment by yhcao6** [comment]
For example, you want to extract the feature of two given boxes on the feature map from FPN by **RoIAligh**, here is an example code:

```
from argparse import ArgumentParser

import torch
from mmcv.parallel import collate, scatter

from mmdet.apis import init_detector
from mmdet.datasets.pipelines import Compose


def main():
    parser = ArgumentParser()
    parser.add_argument('img', help='Image file')
    parser.add_argument('config', help='Config file')
    parser.add_argument('checkpoint', help='Checkpoint file')
    args = parser.parse_args()

    # build the model from a config file and a checkpoint file
    model = init_detector(args.config, args.checkpoint, device='cuda:0')

    cfg = model.cfg
    device = next(model.parameters()).device  # model device
    # prepare data
    data = dict(img_info=dict(filename=args.img), img_prefix=None)
    # build the data pipeline
    test_pipeline = Compose(cfg.data.test.pipeline)
    data = test_pipeline(data)
    data = collate([data], samples_per_gpu=1)
    data = scatter(data, [device])[0]

    img = data['img'][0]
    x = model.extract_feat(img)

    # hack your favorite box here, first 0 represents batch indices
    # you can just set it as 0
    rois = torch.tensor([
        [0., 0., 10., 5., 20.],
        [0., 10., 20., 15., 24.3],
    ]).to(device)
    bbox_feats = model.roi_head.bbox_roi_extractor(
        x[:model.roi_head.bbox_roi_extractor.num_inputs], rois)
    print(bbox_feats.shape)


if __name__ == '__main__':
    main()
```

The command:
```
python extract_feat.py demo/demo.jpg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
```

**Comment by lolongcovas** [comment]
> For example, you want to extract the feature of two given boxes on the feature map from FPN by **RoIAligh**, here is an example code:
> 
> ```
> from argparse import ArgumentParser
> 
> import torch
> from mmcv.parallel import collate, scatter
> 
> from mmdet.apis import init_detector
> from mmdet.datasets.pipelines import Compose
> 
> 
> def main():
>     parser = ArgumentParser()
>     parser.add_argument('img', help='Image file')
>     parser.add_argument('config', help='Config file')
>     parser.add_argument('checkpoint', help='Checkpoint file')
>     args = parser.parse_args()
> 
>     # build the model from a config file and a checkpoint file
>     model = init_detector(args.config, args.checkpoint, device='cuda:0')
> 
>     cfg = model.cfg
>     device = next(model.parameters()).device  # model device
>     # prepare data
>     data = dict(img_info=dict(filename=args.img), img_prefix=None)
>     # build the data pipeline
>     test_pipeline = Compose(cfg.data.test.pipeline)
>     data = test_pipeline(data)
>     data = collate([data], samples_per_gpu=1)
>     data = scatter(data, [device])[0]
> 
>     img = data['img'][0]
>     x = model.extract_feat(img)
> 
>     # hack your favorite box here, first 0 represents batch indices
>     # you can just set it as 0
>     rois = torch.tensor([
>         [0., 0., 10., 5., 20.],
>         [0., 10., 20., 15., 24.3],
>     ]).to(device)
>     bbox_feats = model.roi_head.bbox_roi_extractor(
>         x[:model.roi_head.bbox_roi_extractor.num_inputs], rois)
>     print(bbox_feats.shape)
> 
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> The command:
> 
> ```
> python extract_feat.py demo/demo.jpg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
> ```

Hi, I am facing the similar use case. However, the example of above requires 2 forward passes: 1) for the object detection and 2) for the feature extraction. Is mmdetection allowed to return not only the boxes but also the feature maps (features before the neck and/or after neck)?

Best

**Comment by Spritea** [comment]
> For example, you want to extract the feature of two given boxes on the feature map from FPN by **RoIAligh**, here is an example code:
> 
> ```
> from argparse import ArgumentParser
> 
> import torch
> from mmcv.parallel import collate, scatter
> 
> from mmdet.apis import init_detector
> from mmdet.datasets.pipelines import Compose
> 
> 
> def main():
>     parser = ArgumentParser()
>     parser.add_argument('img', help='Image file')
>     parser.add_argument('config', help='Config file')
>     parser.add_argument('checkpoint', help='Checkpoint file')
>     args = parser.parse_args()
> 
>     # build the model from a config file and a checkpoint file
>     model = init_detector(args.config, args.checkpoint, device='cuda:0')
> 
>     cfg = model.cfg
>     device = next(model.parameters()).device  # model device
>     # prepare data
>     data = dict(img_info=dict(filename=args.img), img_prefix=None)
>     # build the data pipeline
>     test_pipeline = Compose(cfg.data.test.pipeline)
>     data = test_pipeline(data)
>     data = collate([data], samples_per_gpu=1)
>     data = scatter(data, [device])[0]
> 
>     img = data['img'][0]
>     x = model.extract_feat(img)
> 
>     # hack your favorite box here, first 0 represents batch indices
>     # you can just set it as 0
>     rois = torch.tensor([
>         [0., 0., 10., 5., 20.],
>         [0., 10., 20., 15., 24.3],
>     ]).to(device)
>     bbox_feats = model.roi_head.bbox_roi_extractor(
>         x[:model.roi_head.bbox_roi_extractor.num_inputs], rois)
>     print(bbox_feats.shape)
> 
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> The command:
> 
> ```
> python extract_feat.py demo/demo.jpg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
> ```

Just a reminder that the rois **are not** the final predicted boxes given by model inference. You still need to resize the final predicted boxes with the same way inputs images are resized, then take that as the rois in the code. 

Eg, your original image is 1920x1080, and the model resizes it to 1300x800, you would get a scale_factor(in x, and in y) from the test pipeline. Your predicted box given by model inference is [1500, 850, 1600, 950], and then you need to multiply it with scale_factor, and get the final rois. Then take that as the rois in the code above.

**Comment by XinyueZ** [comment]
How to get it for the model like "rtmdet" ? @lolongcovas @Spritea

**Comment by prafful-kumar** [comment]
This code works for mmdet 2.x. I want to know how can the same functionality be achieved using mmdet 3.x. I mean, how can I extract the detector embedding (before the head) of the predicted bbox.
