### ISSUE TITLE
Can this work be integrated into yolov4?

### ISSUE THREAD

**Issue by xiaozhangya** [open-mmlab/mmdetection#3910]
Can this work be integrated into yolov4? 

Thank you

**Comment by RyanXLi** [comment]
Hi! Yolo v4 is currently in progress. You can find a preliminary version of YOLO v4 [here](https://github.com/open-mmlab/mmdetection/pull/3781), note that it does not completely work as it is a work-in-progress. Pull requests are also welcomed!
