### ISSUE TITLE
sabl test problem  'tuple' object has no attribute 'split'

### ISSUE THREAD

**Issue by monkeyMirandar** [open-mmlab/mmdetection#3911]
File "/home/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py", line 315, in simple_test
    bbox_pred = bbox_pred.split(num_proposals_per_img, 0)
AttributeError: 'tuple' object has no attribute 'split'

**Please tell me how to solve it**

**Comment by yuzhj** [comment]
refer to #3853

**Comment by yuzhj** [comment]
replace
```python
bbox_pred = bbox_pred.split(num_proposals_per_img, 0)
```
with
```python
bbox_pred = self.bbox_head.bbox_pred_split(
                    bbox_pred, num_proposals_per_img)
```
