### ISSUE TITLE
The training process exit without any Traceback

### ISSUE THREAD

**Issue by neolovepineapple** [open-mmlab/mmdetection#392]
I am using the default config file to run the model on coco2014 datasets.
The path in config file are change to the right one
However, the training process stop without any Traceback, just like this:

loading annotations into memory...
loading annotations into memory...
Done (t=10.67s)
creating index...
Done (t=10.68s)
creating index...
index created!
index created!
2019-03-11 17:06:01,201 - INFO - Start running, host: alenni@nodeip-dev115, work_dir: /data2/alenni/seven_job/mmdetection/work_dirs/faster_rcnn_r101_fpn_1x
2019-03-11 17:06:01,201 - INFO - workflow: [('train', 1)], max: 12 epochs

I found that the process stop at the forward pass of model, line 38 in mmdetection/mmdet/apis/train.py

Anyone can help me? Thanks!

I`m using CUDA 9, pytorch 1.0.1.post2, python 3.6

**Comment by animebing** [comment]
@neolovepineapple I met the same issue that the training process just stopped here without any information, maybe you can try to use Ctrl+c to stop it, there will be error message if the stop is caused by any error, it works in my case, but I am still confused about why it just stopped without any output.

**Comment by qq237942920** [comment]
@neolovepineapple @animebing hi，I guess you choose your new dataset to train?

**Comment by Alawaka** [comment]
@neolovepineapple @animebing @qq237942920 Yes, I use my own dataset to train and have the save problem above, but I have no idea to solve this problem, anyone can help me?

**Comment by chenyipeng1** [comment]
me too...

**Comment by hellock** [comment]
Did you take a look at the documentation [here](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#train-with-multiple-gpus)?

**Comment by ZlodeiBaal** [comment]
Same issue here.
But i found solution - https://github.com/pytorch/pytorch/issues/33296
`import cv2`
At the beginning of the program ( in train.py ), first import cv2, before import torch.

**Comment by mdcaio** [comment]
I'm having the same issue. Any solutions yet? (cv2 import does not solve it.)
