### ISSUE TITLE
The "expand" transform costs too much time when meets large image

### ISSUE THREAD

**Issue by noprohuangqi** [open-mmlab/mmdetection#3922]
When I train my own dataset , I found sometime GPU-util became 0 , and expand transform costed too much time. 
 
This is my test, you can find `np.full`  function in "expand"  is slow.
![image](https://user-images.githubusercontent.com/35948614/95881671-67625b80-0dab-11eb-9e86-15194963b15f.png)
So , is there any way to solve this?

**Comment by Sundrops** [comment]
use `np.full((int(h * ratio), int(w * ratio), 3), 1.2, dtype=np.float32)`
