### ISSUE TITLE
Adding SpineNet as backbone of faster RCNN, following error arised:

### ISSUE THREAD

**Issue by payal6792** [open-mmlab/mmdetection#3928]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-63f0da5758a7> in <module>
      9 # Build the detector
     10 model = build_detector(
---> 11     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
     12 # Add an attribute for visualization convenience
     13 model.CLASSES = datasets[0].CLASSES

~/Downloads/mmdetection/mmdet/models/builder.py in build_detector(cfg, train_cfg, test_cfg)
     65 def build_detector(cfg, train_cfg=None, test_cfg=None):
     66     """Build detector."""
---> 67     return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))

~/Downloads/mmdetection/mmdet/models/builder.py in build(cfg, registry, default_args)
     30         return nn.Sequential(*modules)
     31     else:
---> 32         return build_from_cfg(cfg, registry, default_args)
     33 
     34 

~/anaconda3/envs/edge/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
    169             f'type must be a str or valid type, but got {type(obj_type)}')
    170 
--> 171     return obj_cls(**args)

~/Downloads/mmdetection/mmdet/models/detectors/retinanet.py in __init__(self, backbone, neck, bbox_head, train_cfg, test_cfg, pretrained)
     15                  pretrained=None):
     16         super(RetinaNet, self).__init__(backbone, neck, bbox_head, train_cfg,
---> 17                                         test_cfg, pretrained)

~/Downloads/mmdetection/mmdet/models/detectors/single_stage.py in __init__(self, backbone, neck, bbox_head, train_cfg, test_cfg, pretrained)
     28         bbox_head.update(train_cfg=train_cfg)
     29         bbox_head.update(test_cfg=test_cfg)
---> 30         self.bbox_head = build_head(bbox_head)
     31         self.train_cfg = train_cfg
     32         self.test_cfg = test_cfg

~/Downloads/mmdetection/mmdet/models/builder.py in build_head(cfg)
     55 def build_head(cfg):
     56     """Build head."""
---> 57     return build(cfg, HEADS)
     58 
     59 

~/Downloads/mmdetection/mmdet/models/builder.py in build(cfg, registry, default_args)
     30         return nn.Sequential(*modules)
     31     else:
---> 32         return build_from_cfg(cfg, registry, default_args)
     33 
     34 

~/anaconda3/envs/edge/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
    169             f'type must be a str or valid type, but got {type(obj_type)}')
    170 
--> 171     return obj_cls(**args)

~/Downloads/mmdetection/mmdet/models/dense_heads/retina_sepbn_head.py in __init__(self, num_classes, num_ins, in_channels, stacked_convs, conv_cfg, norm_cfg, **kwargs)
     28         self.num_ins = num_ins
     29         super(RetinaSepBNHead, self).__init__(num_classes, in_channels,
---> 30                                               **kwargs)
     31 
     32     def _init_layers(self):

**Comment by ZwwWayne** [comment]
Please use the `Error template` when creating the issue.
