### ISSUE TITLE
What does "iof" mean?

### ISSUE THREAD

**Issue by Flawless1202** [open-mmlab/mmdetection#393]
In the file `max_iou_assigner`,
this line:
```
class MaxIoUAssigner(BaseAssigner):
    """Assign a corresponding gt bbox or background to each bbox.

    Each proposals will be assigned with `-1`, `0`, or a positive integer
    indicating the ground truth index.

    - -1: don't care
    - 0: negative sample, no assigned gt
    - positive integer: positive sample, index (1-based) of assigned gt

    Args:
        pos_iou_thr (float): IoU threshold for positive bboxes.
        neg_iou_thr (float or tuple): IoU threshold for negative bboxes.
        min_pos_iou (float): Minimum iou for a bbox to be considered as a
            positive bbox. Positive samples can have smaller IoU than
            pos_iou_thr due to the 4th step (assign max IoU sample to each gt).
        gt_max_assign_all (bool): Whether to assign all bboxes with the same
            highest overlap with some gt to that gt.
        ignore_iof_thr (float): IoF threshold for ignoring bboxes (if
            `gt_bboxes_ignore` is specified). Negative values mean not
            ignoring any bboxes.
        ignore_wrt_candidates (bool): Whether to compute the iof between
            `bboxes` and `gt_bboxes_ignore`, or the contrary.
    """
```

what does 'IoF' mean?

**Comment by hajlyx** [comment]
the ratio of intersection over foreground, which means intersection/(areas of bboxes1)

**Comment by cassie101** [comment]
Hi, just wondering, what is the significance of iof over iou? Say a situation below (blue box = anchor; green box = GT). Since the iof = 1, this anchor box will assigned as positive. But in this case, doesn't the anchor box contains too much unneeded information? e.g. the white region. If iou is used instead, this anchor box could be regarded as negative sample.
![Screenshot from 2019-03-13 12-44-54](https://user-images.githubusercontent.com/42600012/54254241-026ed000-458e-11e9-8314-e5d0ae440fa5.png)

**Comment by hajlyx** [comment]
IoU is used most of the time. I think that IoF may be used in NMS processing, for example, you've got two detection bboxes of 'person' class, one bbox surrounded person completely and another surrounded only upper part of the same person, in this situation the IoU may be less than 0.5 but IoF is 1.0, choosing IoU>0.5 as the threshold may not suppress duplicate bbox and IoF>0.5 works well.

**Comment by hellock** [comment]
@Flawless1202 It is intersection over foreground, just as @hajlyx replied. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/geometry.py#L4) for more details.
We use iof instead of iou for ignored regions, you can just refer to the implementation of assigner.

**Comment by Flawless1202** [comment]
@hellock  @hajlyx Thanks a lot!

**Comment by leemengwei** [comment]
> the ratio of intersection over foreground, which means intersection/(areas of bboxes1)

@hajlyx @hellock , Hi, I have two questions:
1, iof = intersection/(areas of bboxes1)-------- so what about bboxes2? 
2, iof is in MaxIoUAssigner (train phase), how should I use it in test phase?
THANKS!
