### ISSUE TITLE
pytorch2onnx bug report

### ISSUE THREAD

**Issue by tangyanf** [open-mmlab/mmdetection#3934]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when i try to convert mask-rcnn model to onnx i got this output:

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

**Reproduction**
1. What command or script did you run?
```shell
python3.8 tools/pytorch2onnx.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py checkpoint/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

no,i do not make any modifications on the code,but when i got the error, itried to modifiy code use .cpu().detach().numpy() to replace .cpu().numpy(),Unfortunately，i got another error，could you try to fix it?

**Comment by RyanXLi** [comment]
Hi! The `pytorch2onnx` is currently an experimental feature. It currently only supports RetinaNet. Support for converting mask-rcnn model to onnx will be coming in the future.
