### ISSUE TITLE
Caluculating mAP from pickle file

### ISSUE THREAD

**Issue by uttaransinha** [open-mmlab/mmdetection#3935]
Hi,
Is there a way to calculate classwise mAP on a custom COCO dataset when I have the output as a pickle file? Please let me know if there are any inbuild functions that can input a pickle file and generate the evaluation metrics.
P.S The model I am working on is in an old version on mmdetection (0.6.5) and has a lot of custom files which cannot be convereted to the latest format easily. However, I want to use the pickle file on the latest code to get the results.

**Comment by yhcao6** [comment]
Yes, you can refer [tools/eval_metric](https://github.com/open-mmlab/mmdetection/blob/master/tools/eval_metric.py).

**Comment by uttaransinha** [comment]
Thanks!
