### ISSUE TITLE
Can we test the model trained on HTC with mask without the configs of mask?

### ISSUE THREAD

**Issue by zhangshen12356** [open-mmlab/mmdetection#3943]
If i trained my dataset on HTC with mask, i found the speed of inference  not particularly good. So can i remove the configs of mask when i test the model trained with mask?

**Comment by xvjiarui** [comment]
Hi @zhangshen12356 
You may try this [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_without_semantic_r50_fpn_1x_coco.py)
