### ISSUE TITLE
'numpy.ndarray' object has no attribute 'show_result'

### ISSUE THREAD

**Issue by SubMarineas** [open-mmlab/mmdetection#3944]
I used the docker installation environment. The demo program just ran, and I found that the entire function of **show result** cannot be used. Is this a bug? I'll look at the source code later

![image](https://user-images.githubusercontent.com/33534492/96241710-251c6280-0fd5-11eb-9cb4-10de57612145.png)

and 

![image](https://user-images.githubusercontent.com/33534492/96241781-36656f00-0fd5-11eb-9358-992220b12eca.png)

**Comment by DorothysDad** [comment]
i have same problems, do you solve them?

**Comment by xvjiarui** [comment]
Hi @SubMarineas 
The first argument of `show_result_pyplot` should be model not image.

**Comment by SubMarineas** [comment]
@xvjiarui Okay, I built it under windows and looked at the source code and it was resolved
