### ISSUE TITLE
Hi~I encountered one problem when using show_result function to do visualization.

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#395]
I am running the demo test code, I want to inference some of my pictures.
![image](https://user-images.githubusercontent.com/15847405/54249770-69838900-457c-11e9-8f60-d441fdc46812.png)
the wrong codes are:
![image](https://user-images.githubusercontent.com/15847405/54249785-7acc9580-457c-11e9-929d-36baae4a9ebb.png)
It looks like we should transform bbox into ndarray format or use `len(bbox)` to get its length.
I modified codes in mmdet.apis.inference, so it seems that I should reinstall mmdet by running again `python3 setup.py install`?

And another question, it takes too long when running `setup.py`? And there isn't any output during the first few minutes...I'm not sure whether it's a problem of my env or this script itself? Maybe it can be more verbose.

Sorry to interrupt so many times, but a lot of thanks to author and mmlab for creating such a milestone codebase for object detection.
> 我怕我英文说不清楚，但是现在我改了mmdet.apis里的文件，那么通过重新运行setup.py就可以更新到python库里面对吗？另外运行setup.py每次会在一开始卡好几分钟？maybe十多分钟，我不明白是因为我的原因还是代码的问题，它可以正确执行但是看起来就像是卡住了。我似乎问了很多问题，很感谢作者能够解答和创造出如此重要的目标检测的codebase.

**Comment by Luodian** [comment]
I am running the demo test code, I want to inference some of my pictures.
![image](https://user-images.githubusercontent.com/15847405/54249770-69838900-457c-11e9-8f60-d441fdc46812.png)
the wrong codes are:
![image](https://user-images.githubusercontent.com/15847405/54249785-7acc9580-457c-11e9-929d-36baae4a9ebb.png)
It looks like we should transform bbox into ndarray format or use `len(bbox)` to get its length.
I modified codes in mmdet.apis.inference, so it seems that I should reinstall mmdet by running again `python3 setup.py install`?
And another question, it takes too long to run `setup.py`? And there isn't any output during the first few minutes...I'm not sure whether it's a problem of my env or this script itself? Maybe it can be more verbose.
Sorry to interrupt so many times, but a lot of thanks to author and mmlab for creating such a milestone codebase for object detection.
> 我怕我英文说不清楚，但是现在我改了mmdet.apis里的文件，那么通过重新运行setup.py就可以更新到python库里面对吗？另外运行setup.py每次会在一开始卡好几分钟？maybe十多分钟，我不明白是因为我的原因还是代码的问题，它可以正确执行但是看起来就像是卡住了。我似乎问了很多问题，很感谢作者能够解答和创造出如此重要的目标检测的codebase.

**Comment by hellock** [comment]
`result` should be a list of numpy array.

You can just use `python setup.py develop` or `pip install -e .` to avoid reinstalling it after making modifications each time. Running `setup.py` usually takes seconds, since it will just copy files to the directory of python packages or create symbol links.
