### ISSUE TITLE
Beta update assert error in dynamic rcnn

### ISSUE THREAD

**Issue by formorebeat** [open-mmlab/mmdetection#3950]
When the beta updates, new beta will be the median of the beta_history. It might be 0.0 but the beta used in loss function should be greater than 0.
The assert error occurred.
[https://github.com/open-mmlab/mmdetection/blob/5d07dda8719b0c67c11ad015410bc111e9f90200/mmdet/models/roi_heads/dynamic_roi_head.py#L144](url)
The code to fix it could be as follows:
`if np.abs(np.median(self.beta_history)) < 1e-15:
            new_beta = self.bbox_head.loss_bbox.beta
  else:
            new_beta = min(self.train_cfg.dynamic_rcnn.initial_beta,
                       np.median(self.beta_history))`
I am willing to create a PR to fix it as well.

**Comment by v-qjqs** [comment]
Hi @formorebeat, you are welcome to create a PR to fix it.
