### ISSUE TITLE
How I can save detection results in coco format?

### ISSUE THREAD

**Issue by peyman-sabouri** [open-mmlab/mmdetection#3952]
Hi, 
I am using python tools/test.py with the following argument
     --eval-options "jsonfile_prefix=./mask_rcnn_test-dev_results" 
It saves two json files, however I want to save segmentation results like coco segmentation (polygons). 

Is it possible to save detection results in coco format to be used for re-training?

Thanks

**Comment by v-qjqs** [comment]
Hi @peyman-sabouri, the inferenced result file is in COCO submission format, not for re-training.
