### ISSUE TITLE
How can i use torchsata in mmdetection

### ISSUE THREAD

**Issue by DingShengLin** [open-mmlab/mmdetection#3954]
i want to see parameters in my trained model with torchsata, however, when i add codes as below, it occurs TypeError， can anyone help me ?
def _inference_single(model, img, img_transform, device):
    img = mmcv.imread(img)
    #print(img.shape)
    data = _prepare_data(img, img_transform, model.cfg, device)
    with torch.no_grad():
        result = model(return_loss=False, rescale=True, **data)
        stat(model, img.shape)
    return result
TypeError: forward() missing 1 required positional argument: 'img_meta'

**Comment by v-qjqs** [comment]
Hi @DingShengLin, as the error message suggests, you are missing the required 'img_meta' argument for the forward function.
