### ISSUE TITLE
Similar errors when inferring pictures using test.py --show mode

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#396]
I am using a remote server to run inference procedure. So it can't show result images via GUI. How can I avoid this error, just want to save all results. I didn't find the appropriate lines to revise.
![image](https://user-images.githubusercontent.com/15847405/54252619-7a38fc80-4586-11e9-9268-1be6edf5abd0.png)

**Comment by hellock** [comment]
[test.py#L25](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L25) and [base.py#L129](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L129).

**Comment by hellock** [comment]
#403
