### ISSUE TITLE
Anyway to visualize masks and classes on a single image in the dataset?

### ISSUE THREAD

**Issue by colt18** [open-mmlab/mmdetection#3960]
Detectron2 have [this ](https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/visualizer.py)`def draw_dataset_dict:` in order to visualize the masks and classes on a single selected image in the registered database. This ensures that .json file and its contents are working as intended and solid. Is there a way we can accomplish this in `mmcv.visualization`? A quick tutorial would be nice.

**Comment by ZwwWayne** [comment]
Please use the demo in demo/image_demo.py
