### ISSUE TITLE
train_detector(...) gives error while training on MaskRCNN

### ISSUE THREAD

**Issue by m-mohsin-zafar** [open-mmlab/mmdetection#3961]
**Problem while execution of train_detector**

I tried training Mask RCNN and whenever I execute it gives the following error.

> AttributeError                            Traceback (most recent call last)
> 
> <ipython-input-10-5f50d9102797> in <module>()
>      15 # Create work_dir
>      16 mmcv.mkdir_or_exist(os.path.abspath(cfg.work_dir))
> ---> 17 train_detector(model, datasets, cfg, distributed=False, validate=True)
> 
> /home/mohsin/github_clones/mmdetection/mmdet/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
>     141     elif cfg.load_from:
>     142         runner.load_checkpoint(cfg.load_from)
> --> 143     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
> 
> /home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
>     123                     if mode == 'train' and self.epoch >= self._max_epochs:
>     124                         break
> --> 125                     epoch_runner(data_loaders[i], **kwargs)
>     126 
>     127         time.sleep(1)  # wait for some hooks like loggers to finish
> 
> /home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
>      45         self.call_hook('before_train_epoch')
>      46         time.sleep(2)  # Prevent possible deadlock during epoch transition
> ---> 47         for i, data_batch in enumerate(self.data_loader):
>      48             self._inner_iter = i
>      49             self.call_hook('before_train_iter')
> 
> /home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
>     361 
>     362     def __next__(self):
> --> 363         data = self._next_data()
>     364         self._num_yielded += 1
>     365         if self._dataset_kind == _DatasetKind.Iterable and \
> 
> /home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
>     987             else:
>     988                 del self._task_info[idx]
> --> 989                 return self._process_data(data)
>     990 
>     991     def _try_put_index(self):
> 
> /home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
>    1012         self._try_put_index()
>    1013         if isinstance(data, ExceptionWrapper):
> -> 1014             data.reraise()
>    1015         return data
>    1016 
> 
> /home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
>     393             # (https://bugs.python.org/issue2651), so we work around it.
>     394             msg = KeyErrorMessage(msg)
> --> 395         raise self.exc_type(msg)
> 
> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in collate
>     for key in batch[0]
>   File "/home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp>
>     for key in batch[0]
>   File "/home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 31, in collate
>     [sample.data for sample in batch[i:i + samples_per_gpu]])
>   File "/home/mohsin/anaconda3/envs/deep_latest/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 31, in <listcomp>
>     [sample.data for sample in batch[i:i + samples_per_gpu]])
> AttributeError: 'list' object has no attribute 'data'

**Reproduction**
Below is my script used for training
```
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())

# Check MMDetection installation
import mmdet

print(mmdet.__version__)
import copy
import os

import mmcv
import numpy as np

from mmdet.datasets.builder import DATASETS
from mmdet.datasets.custom import CustomDataset

root = '/home/mohsin/Projects/jack_data_prep/processed_data/coco_annotations_modified/'

from mmcv import Config
cfg = Config.fromfile('/home/mohsin/github_clones/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_2x_coco.py')


address = 'http://download.openmmlab.com/mmdetection/v2.0/mask_rcnn/mask_rcnn_r50_fpn_2x_coco/mask_rcnn_r50_fpn_2x_coco_bbox_mAP-0.392__segm_mAP-0.354_20200505_003907-3e542a40.pth'

!mkdir checkpoints
!wget -c {address} \
      -O checkpoints/mask_rcnn_r50_fpn_2x_coco_bbox_mAP-0.392__segm_mAP-0.354_20200505_003907-3e542a40.pth


import os
base_dir='outputs'
folder_name='mm_detection_results_01/'
model_save_dir=os.path.join(base_dir,folder_name)
if not os.path.exists(model_save_dir):
    os.mkdir(model_save_dir)
print ('dir created')


train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(256, 256), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    # dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(256, 256),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            # dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]

from mmdet.apis import set_random_seed

cfg.load_from = 'checkpoints/mask_rcnn_r50_fpn_2x_coco_bbox_mAP-0.392__segm_mAP-0.354_20200505_003907-3e542a40.pth'
# dataset settings

# Modify dataset type and path
cfg.dataset_type = 'CocoDataset'
cfg.classes = ['xx']

# cfg.train_pipeline = train_pipeline
# cfg.test_pipeline = test_pipeline
cfg.data_root ='/home/mohsin/Projects/jack_data_prep/processed_data/coco_annotations_modified/' 

cfg.data.test.data_root = '/home/mohsin/Projects/jack_data_prep/processed_data/coco_annotations_modified/' 
cfg.data.test.ann_file = 'coco_test_mixed.json' 
cfg.data.test.img_prefix = 'images_org' 
cfg.data.test.classes = ['xx']

cfg.data.train.data_root = '/home/mohsin/Projects/jack_data_prep/processed_data/coco_annotations_modified/'  
cfg.data.train.ann_file = 'coco_train_mixed.json' 
cfg.data.train.img_prefix = 'images_org' 
cfg.data.train.classes = ['xx']

cfg.data.val.data_root = '/home/mohsin/Projects/jack_data_prep/processed_data/coco_annotations_modified/' 
cfg.data.val.ann_file = 'coco_val_mixed.json' 
cfg.data.val.img_prefix = 'images_org' 
cfg.data.val.classes = ['xx']

cfg.data.train.pipeline = train_pipeline
cfg.data.val.pipeline = test_pipeline
cfg.data.test.pipeline = test_pipeline
# Set up working dir to save files and logs.
cfg.work_dir = model_save_dir 

cfg.lr_config.policy='step' #'Cyclic/step'
cfg.optimizer.lr = 0.02 / 8
cfg.lr_config.warmup = 'linear' #'None'
cfg.log_config.interval = 2

cfg.evaluation.metric = ['bbox', 'segm']

cfg.evaluation.interval =  2

cfg.checkpoint_config = dict(create_symlink=False)
cfg.checkpoint_config.interval = 5
cfg.total_epochs = 8

cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = [0]

# cfg.model.roi_head.mask_head.num_classes = 1
cfg.model.roi_head.bbox_head.num_classes = 1
cfg.data.samples_per_gpu = 8
# cfg.data.workers_per_gpu = 2

print(f'Config:\n{cfg.pretty_text}')

from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import train_detector


# Build dataset
datasets = [build_dataset([cfg.data.train, cfg.data.val])]

# Build the detector
model = build_detector(cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
# Add an attribute for visualization convenience
model.CLASSES = ('xx') 

# Create work_dir
mmcv.mkdir_or_exist(os.path.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
    Yes, some modifications I made are available for reference in the code above. 2 Major changes I made in the configuration file are; (1) I change the resize scale to (256, 256) as my input Images are of 256 x 256 and I don't wan't to train them on other scales. (2) I remove Pad  from the train and test pipeline.
3. What dataset did you use?
    I used a custom dataset however the dataset is in Coco Format and runs accurately with Detectron2 

**Environment**

1. sys.platform: linux
Python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce GTX 1070
CUDA_HOME: None
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.1.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.4.0+ced1c57

**Error traceback**
Already provided

I shall be thankful for your help,

Regards,

Mohsin

**Comment by hhaAndroid** [comment]
Does the problem still exist?

**Comment by rocketsfallonrocketfalls** [comment]
I have the same issue. Any solutions yet?
