### ISSUE TITLE
Error using Albumentation and validation workflow

### ISSUE THREAD

**Issue by tbootboston** [open-mmlab/mmdetection#3962]
**Describe the bug**
Using albumentation pipeline for data augmentation and workflow set as workflow = [('train', 1), ('val', 1)] yields an after evaluation step (mAP computation):
ValueError: Your 'label_fields' are not valid - them must have same names as params in dict

**Reproduction**
albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        p=0.3),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RandomBrightnessContrast',
                p=1.0),
            dict(
                type='CLAHE',
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=50,
                val_shift_limit=50,
                p=1.0)
        ],
        p=0.3),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=7, p=0.5),
            dict(type='GaussNoise', var_limit=(10.0, 50.0), p=0.5)
        ],
        p=0.3),
]

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1024, 1024), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Pad', size_divisor=32),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=('filename', 'ori_shape', 'img_shape', 'img_norm_cfg',
                   'pad_shape', 'scale_factor'))
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_label=True),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 1024),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Pad', size_divisor=32),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
        ])
]

workflow = [('train', 1), ('val', 1)]

**Environment**

Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3: GeForce GTX 1080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 1.1.4
MMDetection: 2.4.0+8c81ca5
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
After evaluation step, validation loss is computed while runner mode is Train to return loss values on validation dataset. Is there a way to prevent this behavior without applying albumentation pipeline on test dataset ?

**Comment by hhaAndroid** [comment]
In test/val mode,albumentation pipeline will not run，it is only for the train. about the issue，please provide more information. Thank you! @tbootboston

**Comment by jigsawcoder** [comment]
I am using custom dataset and coco annotations for object detection, and I want to apply Albumentation to the dataset. I am facing a similar error :
ValueError: Your 'label_fields' are not valid - them must have same names as params in dict

coco_detection.py file:

dataset_type = 'CocoDataset'
data_root = '/content/drive/MyDrive/SIGNATURE_DETECION_FINAL/'
labels = ['signature', 'hand_written_date', 'stamp', 'barcode']
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]


train_pipeline = [
    dict(type='LoadImageFromFile'),
       dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='coco',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        classes = labels,
        ann_file=data_root + 'Atul_sir_new_data/train.json',
        img_prefix=data_root + 'Atul_sir_new_data/train/',
        #ann_file=data_root + 'final_data/train/voc2coco_train.json',
        #img_prefix=data_root + 'final_data/train/images',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes = labels,
        #ann_file=data_root + 'final_data/val/voc2coco_val.json',
        #img_prefix=data_root + 'final_data/val/images/',
        ann_file=data_root + 'Atul_sir_new_data/valid.json',
        img_prefix=data_root + 'Atul_sir_new_data/val/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes = labels,
        ann_file=data_root + 'Atul_sir_new_data/val.json',
        img_prefix=data_root + 'Atul_sir_new_data/val/',
        #ann_file=data_root + 'final_data/test/voc2coco_test.json',
        #img_prefix=data_root + 'final_data/test/images',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')


I am not sure what to change to fix this error.
Please help!!

**Comment by hhaAndroid** [comment]
@jigsawcoder Thank you for your feedback，error in training or evaluation mode ？

**Comment by jigsawcoder** [comment]
> @jigsawcoder Thank you for your feedback，error in training or evaluation mode ？

In the training mode

**Comment by hhaAndroid** [comment]
@jigsawcoder There is an error in your configuration file

1. LoadAnnotations pipeline must be before Albu
2. In Albu,bbox_params.format should be pascal_voc' not 'coco'

You'd better refer to [mask_rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py) for design

**Comment by jigsawcoder** [comment]
> @jigsawcoder There is an error in your configuration file
> 
> 1. LoadAnnotations pipeline must be before Albu
> 2. In Albu,bbox_params.format should be pascal_voc' not 'coco'
> 
> You'd better refer to [mask_rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py) for design

For your 2nd comment, I am using coco format for bounding box, do I have to change it to 'pascal_voc'?

Also, how do I apply albumentation in faster_rcnn ???

**Comment by hhaAndroid** [comment]
@jigsawcoder  Using coco format also use 'pascal_voc'，Because coco.py has been converted to xyxy(pascal_voc) format. If you use it for faster rcnn, just remove the mask related settings. example

`train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='Pad', size_divisor=32),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=('filename', 'ori_shape', 'img_shape', 'img_norm_cfg',
                   'pad_shape', 'scale_factor'))
]`

**Comment by jigsawcoder** [comment]
> @jigsawcoder Using coco format also use 'pascal_voc'，Because coco.py has been converted to xyxy(pascal_voc) format. If you use it for faster rcnn, just remove the mask related settings. example
> 
> train_pipeline = [
> dict(type='LoadImageFromFile'),
> dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
> dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
> dict(type='Pad', size_divisor=32),
> dict(
> type='Albu',
> transforms=albu_train_transforms,
> bbox_params=dict(
> type='BboxParams',
> format='pascal_voc',
> label_fields=['gt_labels'],
> min_visibility=0.0,
> filter_lost_elements=True),
> keymap={
> 'img': 'image',
> 'gt_bboxes': 'bboxes'
> },
> update_pad_shape=False,
> skip_img_without_anno=True),
> dict(type='Normalize', **img_norm_cfg),
> dict(type='DefaultFormatBundle'),
> dict(
> type='Collect',
> keys=['img', 'gt_bboxes', 'gt_labels'],
> meta_keys=('filename', 'ori_shape', 'img_shape', 'img_norm_cfg',
> 'pad_shape', 'scale_factor'))
> ]



That actually worked but I am facing another issue...

RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 0

coco_detection.py :

dataset_type = 'CocoDataset'
data_root = '/content/drive/MyDrive/SIGNATURE_DETECION_FINAL/'
labels = ['signature', 'hand_written_date', 'stamp', 'barcode']
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]


train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
      type='Albu',
      transforms=albu_train_transforms,
      bbox_params=dict(
      type='BboxParams',
      format='pascal_voc',
      label_fields=['gt_labels'],
      min_visibility=0.0,
      filter_lost_elements=True),
      keymap={
      'img': 'image',
      'gt_bboxes': 'bboxes'
      },
      update_pad_shape=False,
      skip_img_without_anno=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        classes = labels,
        ann_file=data_root + 'Atul_sir_new_data/train.json',
        img_prefix=data_root + 'Atul_sir_new_data/train/',
        #ann_file=data_root + 'final_data/train/voc2coco_train.json',
        #img_prefix=data_root + 'final_data/train/images',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes = labels,
        #ann_file=data_root + 'final_data/val/voc2coco_val.json',
        #img_prefix=data_root + 'final_data/val/images/',
        ann_file=data_root + 'Atul_sir_new_data/valid.json',
        img_prefix=data_root + 'Atul_sir_new_data/val/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes = labels,
        ann_file=data_root + 'Atul_sir_new_data/val.json',
        img_prefix=data_root + 'Atul_sir_new_data/val/',
        #ann_file=data_root + 'final_data/test/voc2coco_test.json',
        #img_prefix=data_root + 'final_data/test/images',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')

**Comment by hhaAndroid** [comment]
@jigsawcoder I suggest you to open a new issue. If you can't solve it, you can refer to  [faster rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person-bicycle-car.py) with add the Albu for you

**Comment by jigsawcoder** [comment]
> @jigsawcoder I suggest you to open a new issue. If you can't solve it, you can refer to [faster rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person-bicycle-car.py) with add the Albu for you

@hhaAndroid Thank you so much for you help!!

**Comment by JXQI** [comment]
> @jigsawcoder There is an error in your configuration file
> 
> 1. LoadAnnotations pipeline must be before Albu
> 2. In Albu,bbox_params.format should be pascal_voc' not 'coco'
> 
> You'd better refer to [mask_rcnn](https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py) for design

why this is not work for me? I use albu to  mask rcnn.

**Comment by waddington** [comment]
> In test/val mode,albumentation pipeline will not run，it is only for the train. about the issue，please provide more information. Thank you! @tbootboston

Why is this? Can I change this?
