### ISSUE TITLE
How to train only use one label ’person‘  in coco2017？and other classes treat as bg. Thanks

### ISSUE THREAD

**Issue by nemonameless** [open-mmlab/mmdetection#397]
I want to train coco using only one class 'person' ，and other classes should be treat as background without bbox gt or instanse seg gt. How to change the code ? Thanks.

**Comment by hellock** [comment]
You can modify the `CocoDataset` to set other classes as background labels.

**Comment by nemonameless** [comment]
@hellock  thank you very much. You are so responsible. I simply  modified the  'mmdet/datasets/coco.py '，I have finished training, using cascade_mask_rcnn_r50 ,the loss seems normally decline , but the mAP of the val is only 0.007, and the mask AP is only 0.006. Is it normal?   

It seems that evaluating  still needs to change the code in other places?

**Comment by Curry1201** [comment]
@nemonameless I have the same purpose as you. How do you change the code when you do? Looking forward to your reply.

**Comment by hitlxm** [comment]
Maybe you can change the label of cats_ids except 'person' to 0,  like that:
https://github.com/open-mmlab/mmdetection/blob/a054aef422d650a644459bdc232248eefa8ae8b7/mmdet/datasets/coco.py#L27   
 self.cat2label = {
            cat_id: i + 1
            if cat_id ==0 else  0  for i, cat_id in enumerate(self.cat_ids)
        }

@hellock is that right?

**Comment by sokunmin** [comment]
This is what I modified for using one-stage detector..

1. Set classes to `2` (background, person) in config file.
```bbox_head=dict(
        type='RetinaHead',
        num_classes=2,
        ...
```

2. Modify these lines in `coco.py`.
```def load_annotations(self, ann_file):
        ...
        # set person class only.
        self.cat_ids = self.coco.getCatIds(catNms=['person'])
        ...
        # pass the Ids of person class to coco.getImgIds()
        self.img_ids = self.coco.getImgIds(catIds=self.cat_ids)```

```def get_ann_info(self, idx):
        ...
        ann_ids = self.coco.getAnnIds(imgIds=[img_id], catIds=self.cat_ids)
```
3. Set `person` class.
```
class CocoDataset(CustomDataset):
    CLASSES = ('person')
```

**It works good for detecting person only.** 
I tried to evaluate the test set by running `tools/test.py` and got the following result.

**Results on `instances_val2017.json.json`.**
```Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.007
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.010
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.007
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.004
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.007
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.009
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.002
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.007
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.008
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.006
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.010
```
Seems a little bit weird here. Maybe there is something I'm missing?

**Results on `person_keypoints_val2017.json`.**
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.530
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.825
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.549
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.353
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.593
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.719
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.193
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.543
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.639
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.493
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.688
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.803
```
On this one, it works great. 
If there's something I did it wrong, please let me know. Thanks.

**Comment by guancheng817** [comment]
> This is what I modified for using one-stage detector..
> 
> 1. Set classes to `2` (background, person) in config file.
> 
> ```
> bbox_head=dict(
>         type='RetinaHead',
>         num_classes=2,
>         ...
> ```
> 
> 1. Modify these lines in `coco.py`.
> 
> ```
> def load_annotations(self, ann_file):
>         ...
>         # set person class only.
>         self.cat_ids = self.coco.getCatIds(catNms=['person'])
>         ...
>         # pass the Ids of person class to coco.getImgIds()
>         self.img_ids = self.coco.getImgIds(catIds=self.cat_ids)
> ```
> 
> ```
> def get_ann_info(self, idx):
>         ...
>         ann_ids = self.coco.getAnnIds(imgIds=[img_id], catIds=self.cat_ids)
> ```
> 
> 1. Set `person` class.
> 
> ```
> class CocoDataset(CustomDataset):
>     CLASSES = ('person')
> ```
> 
> **It works good for detecting person only.**
> I tried to evaluate the test set by running `tools/test.py` and got the following result.
> 
> **Results on `instances_val2017.json`.**
> 
> ```
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.007
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.010
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.007
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.004
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.007
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.009
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.002
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.007
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.008
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.006
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.009
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.010
> ```
> 
> **Seems a little bit weird here. Maybe there is something I'm missing to evaluate specific classes?**
> 
> **Results on `person_keypoints_val2017.json`.**
> 
> ```
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.530
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.825
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.549
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.353
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.593
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.719
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.193
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.543
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.639
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.493
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.688
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.803
> ```
> 
> On this one, it works great.
> If there's something I did it wrong, please let me know. Thanks.

hello, do you know why get weird results on person_keypoints_val2017.json?thanks.
