### ISSUE TITLE
val_pipeline and keyError 'ann_info'

### ISSUE THREAD

**Issue by selecta81** [open-mmlab/mmdetection#3971]
Please forgive me, but i haven't found a similar problem: I need to show validation loss in Tensorboard, but during training I get an error: **KeyError: 'ann_info'** 

My configfile:

data_root = 'data/xxx/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=1,
    workers_per_gpu=2,
    train = dict(
        type='myDataset',
        ann_file=data_root + 'annotations/coco_mydataset_annotations_train.json',
        img_prefix=data_root + 'mydataset/',
        pipeline=train_pipeline),
    val = dict(
        type='myDataset',
        ann_file= data_root + 'annotations/coco_mydataset_annotations_val.json',
        img_prefix=data_root + 'mydataset/',
        pipeline=val_pipeline),
    test = dict(
        type='myDataset',
        ann_file= data_root + 'annotations/coco_mydataset_annotations_train.json',
        img_prefix=data_root + 'mydataset/',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')

------------------------------------------------
workflow = [('train', 1),('val',1)]

Please for help and thank you.

**Comment by yhcao6** [comment]
Since you write a new dataset `MyDataset`, I guess there are some problems with this Class.
In `CustomDataset`, key of `ann_info` is registered here.
```
    def prepare_train_img(self, idx):
        """Get training data and annotations after pipeline.
        Args:
            idx (int): Index of data.
        Returns:
            dict: Training data and annotation after pipeline with new keys \
                introduced by pipeline.
        """

        img_info = self.data_infos[idx]
        ann_info = self.get_ann_info(idx)
        results = dict(img_info=img_info, ann_info=ann_info)
        if self.proposals is not None:
            results['proposals'] = self.proposals[idx]
        self.pre_pipeline(results)
        return self.pipeline(results)
```

**Comment by selecta81** [comment]
I adjusted my dataset to a coco dataset. So I had no need for a val pipeline, I actually use a train pipeline : 

`if len(cfg.workflow) == 2:
        val_dataset = copy.deepcopy(cfg.data.val)
        val_dataset.pipeline = cfg.data.train.pipeline
        datasets.append(build_dataset(val_dataset))`
and now it works.

Thank you!
