### ISSUE TITLE
How to calculate the mAP with ignore annotations

### ISSUE THREAD

**Issue by xzxedu** [open-mmlab/mmdetection#3972]
Hi,  in my custom dataset, I have some targets whose annotation is iscrowd=1, which means they need to be ignored from calculating the mAP. I wonder how to express it in the test pipeline. In the train pipeline, I can add 'gt_bboxes_ignore' key in the Collect dict.

**Comment by yhcao6** [comment]
Do you mean you want to ignore these crowded objects when evaluating mAP? If you are using cocoapi for evaluation, you can just add the `crowded` flag to your json annotations, then it will be ignored during evaluation.

https://github.com/open-mmlab/cocoapi/blob/01f805cd54d7bd7af64c0fbd5fd96d8ca0b9ddc9/pycocotools/pycocotools/cocoeval.py#L112-L115

**Comment by xzxedu** [comment]
Hi, many thanks for your reply! Does that mean if one object annotated with "iscrowd=1" in my test annotation json file, this object will be ignored during evaluating mAP?

**Comment by yhcao6** [comment]
If you are using PycocoAPI to evaluate your model, then the answer is yes. To confirm if it works, you can test with or without the `iscrowd` flag.
