### ISSUE TITLE
undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by yy18dlz** [open-mmlab/mmdetection#3974]
Hi:
I have a problem:
ImportError: /home/yy18dlz/opt/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

**Comment by RyanXLi** [comment]
Hi! Please follow the template for reporting errors so that we can know your situation better. First, you might want to make sure the Cuda runtime version you are using is the same as the Cuda version you are compiling with. You may check the version using `nvcc -V` and `echo $CUDA_HOME`.

**Comment by yy18dlz** [comment]
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

when echo $CUDA_HOME  there is nothing...

**Comment by RyanXLi** [comment]
Then you probably need to install Cuda toolkit from Nvidia which contains the Cuda runtime. Note that the cuda you install from your conda environment is only a subset of the cuda toolkit containing the nvcc but not the runtime required.

**Comment by Shawn0Hsu** [comment]
Hello, I have also encountered the same problem, have you solved it, can you tell me the way, thank you! @yy18dlz

**Comment by yy18dlz** [comment]
> Hello, I have also encountered the same problem, have you solved it, can you tell me the way, thank you! @yy18dlz

时间有点久，我已经忘记了怎么解决了，，，大概率是cuda版本不对吧
