### ISSUE TITLE
 cannot import name 'coco_eval' from 'mmdet.core' 

### ISSUE THREAD

**Issue by ulanbator** [open-mmlab/mmdetection#3975]
版本mmdetection2.5
错误：
Traceback (most recent call last):
  File "tools/rects_test.py", line 16, in <module>
    from mmdet.core import coco_eval, results2json, wrap_fp16_model
ImportError: cannot import name 'coco_eval' from 'mmdet.core' (/home/fangzheng/anaconda3/envs/AET/lib/python3.8/site-packages/mmdet-2.5.0-py3.8.egg/mmdet/core/__init__.py)
最新版本去掉这个coco_eval了吗？

**Comment by RyanXLi** [comment]
Yes. It has been removed in [this pr](https://github.com/open-mmlab/mmdetection/pull/2042).

**Comment by Tamuade** [comment]
Then how to deal with this problem now?
