### ISSUE TITLE
Difference FPN config between mmdet and Retinanet paper

### ISSUE THREAD

**Issue by xzxedu** [open-mmlab/mmdetection#3978]
Hi, when I see the config/_base_/models/retinanet_r50_fpn.py, I notice it uses 'L1 loss' in loss_bbox and its FPN is as follows:
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5), 

But when I read the original Retinanet Paper 'Focal loss for Dense Object Detection', I notice the network uses FPN from level P3 to P7 and also it uses 'smoothL1 loss' in loss_bbox. If I want to use pyramid level P3 to P7, I wonder  i can just replace the start_level in the above FPN config to 3 and nothing else change?

Thanks.

**Comment by RyanXLi** [comment]
I believe the original RetinaNet uses 5 feature maps from P2 to P6, which is consistent with our 4 `in_channels` plus the `add_extra_convs`. Please read [this issue](https://github.com/open-mmlab/mmdetection/issues/298) if you still have questions.
