### ISSUE TITLE
How to add new loss to the whole network

### ISSUE THREAD

**Issue by Andrew-Zhu** [open-mmlab/mmdetection#3979]
Hi, I have read https://mmdetection.readthedocs.io/en/latest/tutorials/customize_losses.html.
I know how to modify a predefined loss like FocalLoss.
But I still do not know how to add a totally new loss for faster-rcnn. Could you give me some suggestions? Thanks!

**Comment by RyanXLi** [comment]
You can refer to the FocalLoss implementation. Implement a loss, add it to the registry with the decorator, add it to the corresponding `__init__.py` of the directory, then edit the config to use it.
