### ISSUE TITLE
./compile.sh   error   No such file or directory: 'which': 'which'

### ISSUE THREAD

**Issue by ltm920716** [open-mmlab/mmdetection#398]
./compile.sh
Building roi align op...
running build_ext
error: [Errno 2] No such file or directory: 'which': 'which'
Building roi pool op...
running build_ext
error: [Errno 2] No such file or directory: 'which': 'which'
.....
Building dcn...
running build_ext
error: [Errno 2] No such file or directory: 'which': 'which'

why get this error，please，thanks

**Comment by ltm920716** [comment]
this is my dockerfile：

FROM nvidia/cuda:9.0-cudnn7-devel-centos7

# 设置网络
ARG https_proxy=https://192.168.71.33:8080
ARG http_proxy=http://192.168.71.33:8080

RUN yum -y install wget && \
    yum -y install bzip2 && \
    yum -y install git && \
    yum -y install make && \
    
    # 安装anaconda==>python3.4+
    cd /home && \
    wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh && \
    bash Anaconda3-5.0.1-Linux-x86_64.sh -b && \
    echo "PATH=~/anaconda3/bin:$PATH" >> ~/.bashrc && \
    source ~/.bashrc && \
    # pip install protobuf && \
    
    # 安装pytorch 1.0
    pip install torchvision && \
    # rm -rf /home/* && \
    # rm -rf /root/.cache/* \
    
    # 安装mmdetection
    git clone https://github.com/open-mmlab/mmdetection.git && \
    cd mmdetection && \
    # pip install cython && \
    pip install mmcv && \
    ./compile.sh && \
    python setup.py install

**Comment by ltm920716** [comment]
this is my dockerfile：

FROM nvidia/cuda:9.0-cudnn7-devel-centos7

RUN yum -y install wget && \
    yum -y install bzip2 && \
    yum -y install git && \
    yum -y install make && \
    
    cd /home && \
    wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh && \
    bash Anaconda3-5.0.1-Linux-x86_64.sh -b && \
    echo "PATH=~/anaconda3/bin:$PATH" >> ~/.bashrc && \
    source ~/.bashrc && \
    
    pip install torchvision && \
    
    git clone https://github.com/open-mmlab/mmdetection.git && \
    cd mmdetection && \
    pip install mmcv && \
    ./compile.sh && \
    python setup.py install

**Comment by hellock** [comment]
That looks weird. How about your system information?

**Comment by ltm920716** [comment]
@hellock 
Thank you for your reply.

The system is nvidia/cuda:9.0-cudnn7-devel-centos7, and the python version is 3.6 by anaconda, below is my dockerfile：

FROM nvidia/cuda:9.0-cudnn7-devel-centos7

RUN yum -y install wget &&
yum -y install bzip2 &&
yum -y install git &&
yum -y install make && \

cd /home && 
wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh && 
bash Anaconda3-5.0.1-Linux-x86_64.sh -b && 
echo "PATH=~/anaconda3/bin:$PATH" >> ~/.bashrc && 
source ~/.bashrc && \

pip install torchvision && \

git clone https://github.com/open-mmlab/mmdetection.git && 
cd mmdetection && 
pip install mmcv && 
./compile.sh && 
python setup.py install

thanks again！

**Comment by ltm920716** [comment]
@hellock ？

**Comment by svmsunny** [comment]
install which： yum install which

**Comment by ltm920716** [comment]
> install which： yum install which

Thanks
