### ISSUE TITLE
FoveaBox Box Prediction

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#3981]
In article, FoveaBox directly computes the normalized offset between (x,y) and four boundaries: `tx_1 = log((s_l*(x+0.5)-x_1) / r_l)`.

But in mmdet code, 
```
bbox_targets[py1:py2 + 1, px1:px2 + 1, 0] = \
          (stride * x[py1:py2 + 1, px1:px2 + 1] - gt_x1) / base_len
```
, I can not find where exec log.

**Comment by xvjiarui** [comment]
Hi @as754770178 
You may find it [here](https://github.com/open-mmlab/mmdetection/blob/95c05decbe3f9b40de7d312840d7bff261a5f890/mmdet/models/dense_heads/fovea_head.py#L257).
