### ISSUE TITLE
'torch module not found' when deploying in gcp app engine

### ISSUE THREAD

**Issue by Rana-Banerjee** [open-mmlab/mmdetection#3982]
I am trying to deploy a mmdetection app in gcp app engine and it takes the dependencies from requirements.txt file. The installation is failing at the mmdetection installation step with the error that 'torch module not found'. Moving the package name up/down in the requirements.txt file is having no effect, as I believe a dependency tree is created when building the environment via requirements.txt. 
Is there any way to enforce an order of installation or any other work around or am I doing something wrong?

**Error snippet as below:**
Collecting git+https://github.com/open-mmlab/mmdetection.git (from -r requirements.txt (line 43))
  Cloning https://github.com/open-mmlab/mmdetection.git to /tmp/pip-req-build-2pqo7f0m

INFO     `pip_download_wheels` had stderr output:
/env/lib/python3.7/site-packages/pip/_internal/req/req_file.py:200: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options, line.opts)
  Running command git clone -q https://github.com/open-mmlab/mmdetection.git /tmp/pip-req-build-2pqo7f0m
    ERROR: Command errored out with exit status 1:
     command: /env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2pqo7f0m/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2pqo7f0m/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l9p4d96_
         cwd: /tmp/pip-req-build-2pqo7f0m/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-2pqo7f0m/setup.py", line 5, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Requirements.txt as below**:
pycocotools 
torch==1.6.0
absl-py==0.10.0           # via tensorboard
addict==2.3.0             # via mmcv-full
albumentations==0.5.0     # via -r requirements.in
backcall==0.2.0           # via ipython
cachetools==4.1.1         # via google-auth
catalyst==20.10.1         # via -r requirements.in
certifi==2020.6.20        # via matplotlib, requests
chardet==3.0.4            # via requests
click==7.1.2              # via uvicorn
cycler==0.10.0            # via matplotlib
cython==0.29.21           # via -r requirements.in, mmpycocotools
decorator==4.4.2          # via ipython, networkx
deprecation==2.1.0        # via catalyst
fastapi==0.61.1           # via -r requirements.in
future==0.18.2            # via torch
gitdb==4.0.5              # via gitpython
gitpython==3.1.9          # via catalyst
google-auth-oauthlib==0.4.1  # via tensorboard
google-auth==1.22.1       # via google-auth-oauthlib, tensorboard
grpcio==1.32.0            # via tensorboard
h11==0.11.0               # via uvicorn
idna==2.10                # via requests
imageio==2.9.0            # via imgaug, scikit-image
imgaug==0.4.0             # via albumentations
importlib-metadata==2.0.0  # via markdown
ipython-genutils==0.2.0   # via traitlets
ipython==7.18.1           # via catalyst
jedi==0.17.2              # via ipython
joblib==0.17.0            # via scikit-learn
kiwisolver==1.2.0         # via matplotlib
markdown==3.3.2           # via tensorboard
matplotlib==3.3.2         # via catalyst, imgaug, mmdet, mmpycocotools, scikit-image
mmcv-full==1.1.5          # via -r requirements.in
git+https://github.com/open-mmlab/mmdetection.git --install-option="develop" 
#mmdet
mmpycocotools==12.0.3     #  
networkx==2.5             # via scikit-image
numpy==1.19.2             # via -r requirements.in, albumentations, catalyst, imageio, imgaug, matplotlib, mmcv-full, mmdet, opencv-python, opencv-python-headless, pandas, pywavelets, scikit-image, scikit-learn, scipy, tensorboard, tensorboard$
oauthlib==3.1.0           # via requests-oauthlib
opencv-python-headless==4.4.0.44  # via albumentations, mmcv-full
opencv-python==4.4.0.44   # via -r requirements.in, imgaug
packaging==20.4           # via catalyst, deprecation
pandas==1.1.3             # via catalyst
parso==0.7.1              # via jedi
pexpect==4.8.0            # via ipython
pickleshare==0.7.5        # via ipython
pycocotools 
torchvision==0.7.0        # via -r requirements.in
tqdm==4.50.2              # via catalyst
traitlets==5.0.5          # via ipython
typing-extensions==3.7.4.3  # via uvicorn
urllib3==1.25.11          # via -r requirements.in, requests
uvicorn==0.12.2           # via -r requirements.in
wcwidth==0.2.5            # via prompt-toolkit
werkzeug==1.0.1           # via tensorboard
wheel==0.35.1             # via tensorboard
yapf==0.30.0              # via mmcv-full
zipp==3.3.1               # via importlib-metadata

**Comment by Rana-Banerjee** [comment]
If I use mmdet in my requirements.txt file then I get 'numpy not found' error

**Comment by xvjiarui** [comment]
Hi @Rana-Banerjee 
You may need to install PyTorch manually first.
