### ISSUE TITLE
Which  means background-class rois in roi classification? 0 or 80?

### ISSUE THREAD

**Issue by Wyman-yang** [open-mmlab/mmdetection#3987]
When using CE loss for classification, is class 0 means background? THANKS!

**Comment by ZwwWayne** [comment]
No, 0 means the first foreground, 80 means background. See [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md#codebase-conventions) for clarification.

**Comment by Wyman-yang** [comment]
> No, 0 means the first foreground, 80 means background. See [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md#codebase-conventions) for clarification.

Thank you so much!
