### ISSUE TITLE
Is there some method to keep each RPN has at least one roi?

### ISSUE THREAD

**Issue by Wyman-yang** [open-mmlab/mmdetection#3988]
I am working on a project which needs to keep at least one rois in each FPN (4 layers), and there always no rois in some layer. Is there some method to achieve that? THANK YOU！

**Comment by ZwwWayne** [comment]
This cannot be guaranteed so we do not do anything to ensure that. Sometimes it will cause deadlock and we use code [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py#L72) to avoid that.
