### ISSUE TITLE
Alternative to torch distributed launch for multi-gpu -- Incompatability

### ISSUE THREAD

**Issue by sbb-gh** [open-mmlab/mmdetection#3989]
Thank you very much for the excellent codebase.

Is there an option for running jobs on multiple gpus that does not use torch distributed launch?

Unfortunately I need to use the pytorch function scatter_add, which is not supported with distributed launch, please see first table of:
https://pytorch.org/docs/stable/distributed.html

**Comment by sbb-gh** [comment]
When I use the --gpus option, I get the error:
('MMDataParallel only supports single GPU training, if you need to'
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

**Comment by yhcao6** [comment]
Can you provide your launching command?

**Comment by sbb-gh** [comment]
This works fine when I am not using the scatter_add function:
(distributed) PORT=29500 ./tools/dist_train.sh configs/carafe/faster_rcnn_r50_fpn_carafe_1x_coco.py 8

This works fine on a single gpu:
(multi-gpu)  PYTHONPATH="$(dirname $0)/..":$PYTHONPATH python tools/train.py configs/carafe/faster_rcnn_r50_fpn_carafe_1x_coco.py --gpus 8

**Comment by yhcao6** [comment]
It seems that `scatter_add` is not related to distributed training. https://pytorch.org/docs/stable/tensors.html#torch.Tensor.scatter_add_

**Comment by sbb-gh** [comment]
Thank you for the reply.

If you look at the table:  https://pytorch.org/docs/stable/distributed.html  it says the scatter operation is not supported with distributed training.  The scatter_add operation has a similar implementation, so I assume it is also not supported.

The code runs when I am not using distributed training, i.e. with python tools/train.py ....
With distributed training the code runs if I remove the scatter_add operation, but produces cuda errors if I keep it in.

Is there another approach to do multi-gpu training ?

**Comment by yhcao6** [comment]
`python tools/train.py ... --gpus 2`. You will meet an assertion here, you can just delete that assertion and the program can run successfully. But I can't guarantee whether the final results will be correct since it is not officially supported anymore.

**Comment by sbb-gh** [comment]
Thank you for your time.

Can I make a feature request for this?

**Comment by yhcao6** [comment]
Probably we won't support it later. If you want to run jobs with multi-GPUs, please use DDP.

https://github.com/open-mmlab/mmcv/blob/bb06f354d5ecace242096dbc01e113f6deb695ca/mmcv/parallel/data_parallel.py#L54-L57
