### ISSUE TITLE
/home/ubuntu/miniconda3/envs/py37-cuda101/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so:undefined symbol: _ZN3c106Symbol14fromQualStringERKSs,how can I solve the problem?

### ISSUE THREAD

**Issue by reallysmelly** [open-mmlab/mmdetection#3991]
The environment infomation is
    Ubuntu=18.04
    python=3.7
    pytorch=1.4.0
    cuda 10.1
    mmcv=1.1.5
     
Every time I run the code
`import mmcv`

It will be shown in such errors.
So how can I slove the problem?Thank you!

**Comment by yhcao6** [comment]
You can 
1. Refer to the [`trouble shooting`](https://github.com/open-mmlab/mmdetection/blob/eb7bfbc62658b60e5be8bb00a40d5e3018971f78/docs/trouble_shooting.md)
1. search some related issues like this

<img width="567" alt="Screen Shot 2020-10-27 at 8 28 02 PM" src="https://user-images.githubusercontent.com/22662425/97301644-f898fe00-1892-11eb-85f1-7914e20a9544.png">

I believe you can find wut you want.

**Comment by reallysmelly** [comment]
Ok,I have solved the problem.You should recompile the mmcv on your computer.
Thank you!
