### ISSUE TITLE
DetectoRS + Res2net

### ISSUE THREAD

**Issue by hachreak** [open-mmlab/mmdetection#3995]
Hi all,
could somebody help me to use DetectoRS with a Res2net backbone?
Both extend the ResNet classes but up to now it's not clear to me the best way to fuse both together.

**Motivation**
To check advantages to use a better backbone.

**Comment by yhcao6** [comment]
To integrate detectoRS with Res2net, you have to modify [`res2net.py`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/res2net.py) and implement `detectors_res2net` yourself, which should be similar to what ['detectors_resnet.py'](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/detectors_resnet.py) does.
