### ISSUE TITLE
In mmdet/datasets/coco.py,  np.linspace() may not create exact values

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#3997]
Ubuntu 18.04, AMD Ryzen 3700x

MMCV: 1.0.5
MMDetection: 2.3.0+68d860d
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1

In mmdet/datasets/coco.py, the function evaluate(),  code:
        if iou_thrs is None:
            iou_thrs = np.linspace(
                .5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)
I found iou_thrs = [0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, **_0.8999999_** , 0.95]

**Bug fix**
I changed code as below and tested ok.
        if iou_thrs is None:
            iou_thrs = np.linspace(
                .5, 0.95, int(np.round((0.95 - .5) / .05)) + 1, endpoint=True)
            **_iou_thrs = np.round(iou_thrs, decimals=2)_**

**Comment by yhcao6** [comment]
I think it is an expected behavior instead of a bug. If you like you can print it as two decimal float number but it won't harm the correctness.

**Comment by minan19605** [comment]
I try to get AP and AR value for each IOU threshold value, not only 0.5, 0.75,  I found I can't get AP/AR value for 0.9. Because 0.89999 not equal to 0.9. 

So I don't get why it is expected behavior?

**Comment by yhcao6** [comment]
That's a problem related to floating-point arithmetic.
