### ISSUE TITLE
Add single-stage detectors

### ISSUE THREAD

**Issue by hellock** [open-mmlab/mmdetection#4]
- [x] Single-stage heads
- [x] RetinaNet
- [x] SSD

**Comment by takecareofbigboss** [comment]
waiting for ur release

**Comment by s5plus1** [comment]
Nice work! Will you plan to add yolov3?

**Comment by hellock** [comment]
> Nice work! Will you plan to add yolov3?

YOLO series are not in our dev plan currently, but PRs are alway welcome.

**Comment by s5plus1** [comment]
@hellock Thanks for your reply!

**Comment by odb920** [comment]
Can you send me the link for the new year
