### ISSUE TITLE
RuntimeError: arguments are located on different GPUs when test

### ISSUE THREAD

**Issue by whyguu** [open-mmlab/mmdetection#40]
# after training a faster rcnn model, the runtime error occurs when using the provided test.py or the code. following is the trace back。

# i trained the model on gpu1. the error always occurs whether i use gpu1 or others.

Traceback (most recent call last):
  File "tools/test.py", line 121, in <module>
    main(arguments)
  File "tools/test.py", line 86, in main
    outputs = single_test(model, data_loader, args.show)
  File "tools/test.py", line 20, in single_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mmdet/models/detectors/base.py", line 81, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mmdet/models/detectors/base.py", line 73, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mmdet/models/detectors/two_stage.py", line 149, in simple_test
    self.test_cfg.rpn) if proposals is None else proposals
  File "/usr/local/lib/python3.5/dist-packages/mmdet/models/detectors/test_mixins.py", line 10, in simple_test_rpn
    proposal_list = self.rpn_head.get_proposals(*proposal_inputs)
  File "/usr/local/lib/python3.5/dist-packages/mmdet/models/rpn_heads/rpn_head.py", line 197, in get_proposals
    img_meta[img_id]['img_shape'], cfg)
  File "/usr/local/lib/python3.5/dist-packages/mmdet/models/rpn_heads/rpn_head.py", line 229, in _get_proposals_single
    self.target_stds, img_shape)
  File "/usr/local/lib/python3.5/dist-packages/mmdet/core/bbox/transforms.py", line 54, in delta2bbox
    gw = pw * dw.exp()
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:314

# code in test.py
```python
def parse_args(args):
    parser = argparse.ArgumentParser(description='MMDet test detector')
    parser.add_argument('config', help='test config file path')
    parser.add_argument('checkpoint', help='checkpoint file')
    parser.add_argument(
        '--gpus', default=1, type=int, help='GPU number used for testing')
    parser.add_argument(
        '--proc_per_gpu',
        default=1,
        type=int,
        help='Number of processes per GPU')
    parser.add_argument('--out', help='output result file')
    parser.add_argument(
        '--eval',
        type=str,
        nargs='+',
        choices=['proposal', 'proposal_fast', 'bbox', 'segm', 'keypoints'],
        help='eval types')
    parser.add_argument('--show', action='store_true', help='show results')
    args = parser.parse_args(args)
    return args


def main(args):
    args = parse_args(args)

    if args.out is not None and not args.out.endswith(('.pkl', '.pickle')):
        raise ValueError('The output file must be a pkl file.')

    cfg = mmcv.Config.fromfile(args.config)
    cfg.model.pretrained = None
    cfg.data.test.test_mode = True

    dataset = obj_from_dict(cfg.data.test, datasets, dict(test_mode=True))
    if args.gpus == 1:
        model = build_detector(
            cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
        load_checkpoint(model, args.checkpoint)
        model = MMDataParallel(model, device_ids=[1])
        print('using cuda 1')

        data_loader = build_dataloader(
            dataset,
            imgs_per_gpu=1,
            workers_per_gpu=cfg.data.workers_per_gpu,
            num_gpus=1,
            dist=False,
            shuffle=False)
        outputs = single_test(model, data_loader, args.show)
    else:
        model_args = cfg.model.copy()
        model_args.update(train_cfg=None, test_cfg=cfg.test_cfg)
        model_type = getattr(detectors, model_args.pop('type'))
        outputs = parallel_test(
            model_type,
            model_args,
            args.checkpoint,
            dataset,
            _data_func,
            range(args.gpus),
            workers_per_gpu=args.proc_per_gpu)

    if args.out:
        print('writing results to {}'.format(args.out))
        mmcv.dump(outputs, args.out)
        eval_types = args.eval
        if eval_types:
            print('Starting evaluate {}'.format(' and '.join(eval_types)))
            if eval_types == ['proposal_fast']:
                result_file = args.out
            else:
                result_file = args.out + '.json'
                results2json(dataset, outputs, result_file)
            coco_eval(result_file, eval_types, dataset.coco)


if __name__ == '__main__':
    arguments = [
        'configs/faster_rcnn_r50_fpn_1x.py',
        'data/faster_rcnn_r50_fpn_1x/epoch_12.pth',
        '--gpus=1',
        '--out=test.pkl'
    ]
    main(arguments)
```

# code in readme
```python
def infer():
    import mmcv
    from mmcv.runner import load_checkpoint
    from mmdet.models import build_detector
    from mmdet.apis import inference_detector, show_result
    from mmcv.parallel import scatter, collate, MMDataParallel

    cfg = mmcv.Config.fromfile('configs/faster_rcnn_r50_fpn_1x.py')
    cfg.model.pretrained = None

    # construct the model and load checkpoint
    model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
    print(model)
    checkpoint_path = 'data/faster_rcnn_r50_fpn_1x/epoch_12.pth'
    _ = load_checkpoint(model, checkpoint_path, map_location='cuda:1')
    model = MMDataParallel(model, device_ids=[1])
    # test a single image
    img_path = '/workspace/nas/test/'
    img = mmcv.imread(img_path+'0.jpg')
    result = inference_detector(model, img, cfg, device='cuda:1')
    show_result(img, result)

    # test a list of images
    # img_path = '/workspace/nas/test/'
    # imgs = ['0.jpg', '1.jpg']
    # imgs = [img_path+img for img in imgs]
    # for i, result in enumerate(inference_detector(model, imgs, cfg, device='cuda:2')):
    #     print(i, imgs[i])
    #     show_result(imgs[i], result)
```

**Comment by hellock** [comment]
Can you post the scripts that you ran?

**Comment by whyguu** [comment]
> Can you post the scripts that you ran?

code has been posted.

**Comment by whyguu** [comment]
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

seems to solve this problem.
