### ISSUE TITLE
How to visualize model?

### ISSUE THREAD

**Issue by ming71** [open-mmlab/mmdetection#400]
Visualization is much helpful for study, but I have try various methods and failed to visualize the model , any plan for that?

**Comment by ming71** [comment]
Maybe I am not familiar with that....

**Comment by Luodian** [comment]
你可以用README.md里面的Test images的方法来可视化模型，但是目前还没有可以可视化mask的方法，只支持可视化bbox

**Comment by Luodian** [comment]
#401 你可以看这个，instructions里面还是有点问题的

**Comment by ming71** [comment]
> 你可以用README.md里面的Test images的方法来可视化模型，但是目前还没有可以可视化mask的方法，只支持可视化bbox
> UPDATE: 其实mmdet有mask可视化，但是没写在inference引用的那部分代码里。
Nope， 我指的不是这种文本形式可视化，而是生成png形式，像keras和tensorboard那样，但是尝试了各种方法都没有成功，所以弃坑了

**Comment by Luodian** [comment]
@ming71 oh ye
