### ISSUE TITLE
Error when visualizing loss

### ISSUE THREAD

**Issue by YRDTSS** [open-mmlab/mmdetection#4001]
I've learned a lot from your code, thanks for your great job！

When I run analyze_logs.py, error: KeyError: './work_dirs/20201026_154039.log.json does not contain metric loss_'.

Welcome to discuss with anyone who has the same problem

**Comment by yhcao6** [comment]
Can you provide your running command and log?

**Comment by YRDTSS** [comment]
When I run："python tools/analyze_logs.py plot_curve ./work_dirs/faster_rcnn/20201102_194729.log.json --keys loss_cls --out ./plot_result/a   ",I can get a loss_cls graph.  When I add  ''loss_dfl'' to the "--keys" parameter, it displays an error:"KeyError: './work_dirs/faster_rcnn/20201102_194729.log.json does not contain metric loss_dfl'

**Comment by YRDTSS** [comment]
Welcome to discuss with anyone who has the same problem
