### ISSUE TITLE
Training Process Not Responding

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#4002]
**Describe the bug**
No logging and progress during training:
After starting the training process, there is no progress or logging after the following step. The training process does not give an error either. Although it has been approximately 1 hour after starting the training, there is no change in the following situation. Meanwhile, the Cursor is constantly flashing. I have to terminate the process with the Ctlr + C keys. However, there is no .pth file in work directory. The training process seems to be in an endless loop.

```
loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
2020-10-26 21:29:50,713 - mmdet - INFO - Start running, host: atakan@atakan-MS-7A15, work_dir: /home/atakan/mmdetection/work_dirs/htc_without_semantic_r50_fpn_1x_coco'
2020-10-26 21:29:50,713 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
```

**Reproduction**
1. What command or script did you run?
`python tools/train.py configs/htc/htc_without_semantic_r50_fpn_1x_coco.py `

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I changed the my own data set into COCO data format and than modified my data path(data root) in config file (/config/base/model, /config/base/data) then run the train.py file

3. What dataset did you use?
my own dataset with labeled

**Environment**
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.1.5
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.5.0+5d07dda

**Error traceback**
It does not give any error

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
Could you try the default COCO dataset to see if the training process is normal?
If the COCO dataset is normal, then the problem comes from the implementation of your own dataset class.
Otherwise, it may be related to your environment setup.

**Comment by liushuai839** [comment]
Have you solved it ?? I met the same problem

**Comment by MengAaron** [comment]
I run mmdetection3d, and meet the same problem

**Comment by zerok01** [comment]
> Have you solved it ?? I met the same problem

No, but I am not getting this error on AerialDetection(https://github.com/dingjiansw101/AerialDetection) using the lower version of mmdetection. I will format my computer in 1-2 days. After formatting, I will re-install mmdetection and this time I will try it on the COCO dataset. I'll report the result. But I think there's a problem

**Comment by zerok01** [comment]
I formatted my computer. Then I installed mmdetection with a clean install. Problem solved. I think there was a conflict issue with older versions of mmdetection. As a solution, you can try this.
