### ISSUE TITLE
When I use the ATSS model of this code base, AP small is always -1.000, but it doesn’t work if I change the base_size. Any suggestions?

### ISSUE THREAD

**Issue by 1428679766** [open-mmlab/mmdetection#4004]
On my own data set, but adjusting anchor_size on Faster rcnn can improve mAPs(small)

**Comment by RyanXLi** [comment]
It is a COCO convention to return -1 for AP or AR when there is no groundtruth ([see here](https://github.com/cocodataset/cocoapi/blob/e140a084d678eacd18e85a9d8cfa45d1d5911db9/PythonAPI/pycocotools/cocoeval.py#L52)), so maybe check whether the dataset you test on has small objects.
