### ISSUE TITLE
Where's the benchmark list for all models?

### ISSUE THREAD

**Issue by ArchNew** [open-mmlab/mmdetection#4008]
If I remembered correctly, there was a benchmark list for all models. It recorded scores of all models on the major datasets. I can't find it anymore. Did you guys delete it? Or I looked at the wrong places.

**Comment by RyanXLi** [comment]
I believe you are referring to the table 10 in the [MMDetection tech report](https://arxiv.org/pdf/1906.07155.pdf). The most updated benchmarks are in the [model zoo page](https://github.com/open-mmlab/mmdetection/blob/master/docs/model_zoo.md) which contains more new models.

**Comment by ArchNew** [comment]
Thanks!
