### ISSUE TITLE
Some problems during inference images.

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#401]
```
import mmcv
from mmcv.runner import load_checkpoint
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result

cfg = mmcv.Config.fromfile('configs/faster_rcnn_r50_fpn_1x.py')
cfg.model.pretrained = None

model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
_ = load_checkpoint(model, 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')

img = mmcv.imread('test.jpg')
result = inference_detector(model, img, cfg)
show_result(img, result)

imgs = ['test1.jpg', 'test2.jpg']
for i, result in enumerate(inference_detector(model, imgs, cfg, device='cuda:0')):
    print(i, imgs[i])
    show_result(imgs[i], result)
```
At README.md, we are instructed to do this and result returns both `bbox` and `segms`, but `show_result` method only support visualization of bbox
so it should be revised to `show_result(imgs[i], result[0]` if you are using a model contains mask branch.

**Comment by Luodian** [comment]
Also, we need to revise lines in `apis/inference.py`
```
	labels = [
		np.full(bbox.shape[0], i, dtype = np.int32)
		for i, bbox in enumerate(result)
	]
```
That should be...
```
	labels = [
		np.full(len(bbox), i, dtype = np.int32)
		for i, bbox in enumerate(result)
	]
```

**Comment by Luodian** [comment]
I am not sure modifying `bbox.shape[0]` into `len(bbox)` will affect other lines to call this function. I can to pull a request maybe to help you out this problem.
I am now pasting codes in detectron to help with mask visualization, I don't think there's a lot of difference. 
It's an easy migration, but didn't support getting dataset, so my visualization didn't contain label's name, maybe a quick fix to create a new `show_det_mask` function to help with mask visualization is needed.

**Comment by Luodian** [comment]
Ok, I found mask segmentations drawing part in `mmdet/model/detectors/base.py`

**Comment by runzeer** [comment]
Thanks for your sharing. But when I run the inference test as below,I came across the 
段错误(吐核) problem. So How can I solve the problem? It happens in the "inference_detector" module
 
import mmcv
from mmcv.runner import load_checkpoint
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result

cfg = mmcv.Config.fromfile('configs/faster_rcnn_r50_fpn_1x.py')
cfg.model.pretrained = None

model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
_ = load_checkpoint(model, 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')

img = mmcv.imread('test.jpg')
result = inference_detector(model, img, cfg)
show_result(img, result)

imgs = ['test1.jpg', 'test2.jpg']
for i, result in enumerate(inference_detector(model, imgs, cfg, device='cuda:0')):
    print(i, imgs[i])
    show_result(imgs[i], result)

**Comment by hellock** [comment]
@runzeer mostly because of the gcc version, see #24 #229 for details.

**Comment by runzeer** [comment]
So when will you share the source codes of the 2018 COCO Champion version?

**Comment by runzeer** [comment]
> Also, we need to revise lines in `apis/inference.py`
> 
> ```
> 	labels = [
> 		np.full(bbox.shape[0], i, dtype = np.int32)
> 		for i, bbox in enumerate(result)
> 	]
> ```
> That should be...
> 
> ```
> 	labels = [
> 		np.full(len(bbox), i, dtype = np.int32)
> 		for i, bbox in enumerate(result)
> 	]
> ```
> But I found that if we only visualize bbox, using original code is right.

I changed the code according to what you said. But there still exists the problem. It is wrong in the mmcv/visualize/image.py 102 line 
assert bboxes.shape[0] == label.shape[0].
So could you tell me why?

**Comment by yangcong955** [comment]
test

**Comment by Stephenfang51** [comment]
> Thanks for your sharing. But when I run the inference test as below,I came across the
> 段错误(吐核) problem. So How can I solve the problem? It happens in the "inference_detector" module
> 
> import mmcv
> from mmcv.runner import load_checkpoint
> from mmdet.models import build_detector
> from mmdet.apis import inference_detector, show_result
> 
> cfg = mmcv.Config.fromfile('configs/faster_rcnn_r50_fpn_1x.py')
> cfg.model.pretrained = None
> 
> model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
> _ = load_checkpoint(model, 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')
> 
> img = mmcv.imread('test.jpg')
> result = inference_detector(model, img, cfg)
> show_result(img, result)
> 
> imgs = ['test1.jpg', 'test2.jpg']
> for i, result in enumerate(inference_detector(model, imgs, cfg, device='cuda:0')):
> print(i, imgs[i])
> show_result(imgs[i], result)

Dear Sir

Did you solve the problem yet ? I met the same issue here 

hope you can provided the solution.

Thanks in advanced !
