### ISSUE TITLE
cannot use DeformRoIPoolingPack

### ISSUE THREAD

**Issue by wyman123** [open-mmlab/mmdetection#4013]
I changed the config file of faster rcnn to perform deformable roi pooling but got stuck:

    assert hasattr(ops, layer_type)
AssertionError

Thank you so much!

**Comment by RyanXLi** [comment]
It seems that the ROI `layer_cfg` does not have key `layer_type`. Could you provide your config so we could better understand the problem?

**Comment by Wyman-yang** [comment]
![image](https://user-images.githubusercontent.com/61415784/97662640-8d2d7700-1ab2-11eb-9446-c516d4a86899.png)

I changed the cfg of roi layer from ROI ALigh to DeformRoIPoolingPack

> It seems that the ROI `layer_cfg` does not have key `layer_type`. Could you provide your config so we could better understand the problem?

**Comment by RyanXLi** [comment]
Maybe try `DeformRoIPoolPack` as in [this config](https://github.com/open-mmlab/mmdetection/blob/5f2cdeddf990d695c55aa8982dc29abb1f9be9cb/configs/dcn/faster_rcnn_r50_fpn_dpool_1x_coco.py#L8).

**Comment by nmll** [comment]
Could I ask about the DeformRoIPoolPack forward input(self, feats, rois, roi_scale_factor=None), the feas shape is (B, C, H, W), the rois is(idx, x1,y1,x2,y2), is the idx batch index?
