### ISSUE TITLE
SOS: KeyError: 'HighFPN is not in the neck registry'

### ISSUE THREAD

**Issue by jonguo111** [open-mmlab/mmdetection#4014]
**Checklist**
I want to add a new neck to my code but the new neck cannot be registered.

**Describe the bug**

**KeyError: 'HighFPN is not in the neck registry'**

**Reproduction**
1. What command or script did you run?
```
python tools/train.py [configs/retinanet/retinanet_r50_fpn_1x_coco.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I have followed the instructions in (https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#define-a-neck-e-g-pafpn)

-  2.1

I have added a new fpn file named ```high_fpn.py``` into ```../mmdet/models/necks/```

To be condense, following shows part of ```high_fpn.py```

```
import torch.nn as nn
import torch.nn.functional as F
from mmcv.cnn import ConvModule, xavier_init
from mmcv.runner import auto_fp16

from ..builder import NECKS

@NECKS.register_module()

class HighFPN(nn.Module):

    def __init__(self,
                 in_channels,
                 out_channels,
                 num_outs,
                 pool_ratios=[0.1,0.2,0.3],
                 start_level=0,
                 end_level=-1,
                 add_extra_convs=False,
                 normalize=None,
                 activation=None):
        super(HighFPN, self).__init__()
        assert isinstance(in_channels, list)
        self.in_channels = in_channels
...
     
```
    

- 2.2 I have added HighFPN into  ```__init__.py``` into ``` .. /mmdet/models/necks/```

The following shows the change:

```
...
from .pafpn import PAFPN
from .rfp import RFP
from .yolo_neck import YOLOV3Neck
from .high_fpn import HighFPN

__all__ = [
    'FPN','BFP', 'HRFPN', 'NASFPN', 'FPN_CARAFE', 'PAFPN', 'NASFCOS_FPN',
    'RFP', 'YOLOV3Neck', 'HighFPN'
]

```

- 2.3 I have replaced ```type = FPN``` to ```type = HighFPN``` in 

```../mmdetection_train_crossing/configs/_base_/models/retinanet_r50_fpn.py```

- I have referred to this question (https://github.com/open-mmlab/mmdetection/issues/1817), and I have double checked my mmdet file, finding nothing wrong on my file path. 

- Thank you in advance!

**Comment by RyanXLi** [comment]
The most common cause of this problem is that you are in a different virtual environment. Please verify the mmdet you are running is the same as the mmdet you are editing by running these in the python REPL.

```python
import mmdet
mmdet.__path__
```
