### ISSUE TITLE
Get model checkpoints for `mmdetection/v2.0/` models not available on model zoo

### ISSUE THREAD

**Issue by CMobley7** [open-mmlab/mmdetection#4016]
What is the easiest way to download or make checkpoints for models not on the server at https://s3.ap-northeast-2.amazonaws.com/open-mmlab? It looks like there are very few `mmdetection/v2.0/` models available at that url. Is the only way to download the ones available for `mmdetection` and use `tools/upgrade_model_version.py` to convert them to v2.0? Or is there any easier way? I'm assuming for the remaining models not available under `mmdetection/` or `mmdetection/v2.0/` at the url, such as https://github.com/open-mmlab/mmdetection/blob/master/configs/regnet/faster_rcnn_regnetx-3.2GF_fpn_1x_coco.py, checkpoints are not actually available. Consequently, the model would have to be trained from scratch on COCO. Am I correct?

**Comment by CMobley7** [comment]
Actually, I see that you link them here, https://github.com/open-mmlab/mmdetection/tree/master/configs/regnet, but the underlying url isn't your model zoo. Is there a reason for this?

**Comment by xvjiarui** [comment]
Hi @CMobley7 
We switched to download.openmmlab.com. You may find the model there.
