### ISSUE TITLE
What's the best way to use the validation dataset 

### ISSUE THREAD

**Issue by JonathanAndradeSilva** [open-mmlab/mmdetection#4018]
Hi every one,

I would like to know whats the difference between use the validation dataset with two workflow [('train',1),('val',1)] or with one workflow but set true the validate flag on train.py?

My main concern are:
 - Which one only test the validation dataset without update the network
 - How to evaluate with mAP when the val pipeline is the same of the train pipeline.

**Comment by xvjiarui** [comment]
Hi @JonathanAndradeSilva 
You need to use `EvalHook` for mAP results. `workflow` won't get you there.
