### ISSUE TITLE
Encountering Problem while adding SpineNet as backbone with 2 GPUs

### ISSUE THREAD

**Issue by payal6792** [open-mmlab/mmdetection#4020]
subprocess.CalledProcessError: Command '['/home/payal/anaconda3/envs/spn/bin/python', '-u', 'tools/train.py', '--local_rank=1', './configs/sp.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by xvjiarui** [comment]
Hi @payal6792 
You may use [error report template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) to provide more details.
