### ISSUE TITLE
a bug in mmdet/models/dense_heads/paa_head.py

### ISSUE THREAD

**Issue by meijiangyuan** [open-mmlab/mmdetection#4021]
**Bug fix**

File "/path/to/mmdetection/mmdet/models/dense_heads/paa_head.py", line 626, in score_voting
det_bboxes_voted = torch.cat(det_bboxes_voted, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPUTensorId, CUDATensorId, QuantizedCPUTensorId, VariableTensorId]

when det_bboxes_voted is empty, it will report this error.

My advise is that 
if self.with_score_voting:
            det_bboxes, det_labels = self.score_voting(det_bboxes, det_labels,
                                                       mlvl_bboxes,
                                                       mlvl_nms_scores,
                                                       cfg.score_thr)
＝＝>
if self.with_score_voting and len(det_bboxes)>0:
            det_bboxes, det_labels = self.score_voting(det_bboxes, det_labels,
                                                       mlvl_bboxes,
                                                       mlvl_nms_scores,
                                                       cfg.score_thr)

**Comment by xvjiarui** [comment]
Hi @meijiangyuan 
Thanks for pointing out. Would you like to create a PR to fix it?

**Comment by hellock** [comment]
@jshilong
