### ISSUE TITLE
It seems to be an implementation error in "centripetalNet"

### ISSUE THREAD

**Issue by ymzis69** [open-mmlab/mmdetection#4022]
**Describe the bug**
Thank you for your open source code!
In "centripetalNet", it does not seem to implement this part of the paper:
![bug](https://user-images.githubusercontent.com/67489888/97413738-1a02f400-193e-11eb-9a31-139a750e51a4.jpg)

**Comment by xvjiarui** [comment]
@tianyuandu

**Comment by tianyuandu** [comment]
The corresponding code is here: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/corner_head.py#L1009

Seems we forgot to compute the exponent to `dists`. This part only affects inference, so you can modify this line and compare it to the released result.

**Comment by ymzis69** [comment]
Thank you. I will try to add this part after the training to compare the results.
