### ISSUE TITLE
How to add "eta:" info. into log.json when training model via mmdet ?

### ISSUE THREAD

**Issue by cefengxu** [open-mmlab/mmdetection#4026]
**_the log.json I got via mmdet was shown below:_**
{"mode": "train", "epoch": 2, "iter": 8, "lr": 0.0025, "memory": 2224, "data_time": 0.05936, "loss_rpn_cls": 0.07717, "loss_rpn_bbox": 0.02901, "loss_cls": 0.20496, "acc": 97.85156, "loss_bbox": 0.07756, "loss": 0.3887, "time": 0.23003}

**_how to set the log that just shown some info. or add more info. ( eta ) which I want, for example:_**
{"mode": "train", "epoch": 2, "iter": 8, **"eta": 1.0325**, "memory": 2224, "data_time": 0.05936,"loss_cls": 0.20496, "acc": 97.85156, "loss_bbox": 0.07756, "loss": 0.3887, "time": 0.23003}

**Comment by cefengxu** [comment]
i have  rewrite the code in mmcv ( mmcv/runner/hooks/logger/text.py:: _dump_log( self, log_dict , runner ) )  and rebuild mmcv from source, and then I can add  "eta" into the None.log.json.

however,  can I just set the params from mmdetection code for adding "eta" into None.log.json, instead of mmcv?

**Comment by ZwwWayne** [comment]
For now, mmdet does not support that. We may make it as an argument to enable this feature in the future.
