### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lwdoubles** [open-mmlab/mmdetection#4029]
When I run the train.py，I met the error Segmentation fault.
I get the information below when I run “python mmdet/utils/collect_env.py”

Python: 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /cm/shared/apps/cuda10.1/toolkit/10.1.243
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3,4,5,6,7: Tesla V100-PCIE-16GB
GCC: gcc (GCC) 5.5.0
PyTorch: 1.5.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
TorchVision: 0.6.1+cu101
OpenCV: 4.1.1
MMCV: 1.1.1
MMDetection: 2.3.0+HEAD
MMDetection Compiler: GCC 5.5
MMDetection CUDA Compiler: 10.1
Segmentation fault

**Comment by ZwwWayne** [comment]
Hi @lwdoubles ,
Can you try gcc 5.4? GCC 5.5 seems to has incompatibility issues and the bug is unknown. You can try to install gcc 5.4 in your environment and the problem should be solved.

**Comment by lwdoubles** [comment]
> Hi @lwdoubles ,
> Can you try gcc 5.4? GCC 5.5 seems to has incompatibility issues and the bug is unknown. You can try to install gcc 5.4 in your environment and the problem should be solved.
I try gcc 5.4,but get the same error.i also try distributed training,and get the error info like this:

subprocess.CalledProcessError: Command '['/home/user/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=7', './configs/pisa/pisa_retinanet_r50_fpn_1x_coco.py', '--launcher', 'pytorch', '--work-dir', 'nms_test/']' died with <Signals.SIGSEGV: 11>.

**Comment by lwdoubles** [comment]
> Hi @lwdoubles ,
> Can you try gcc 5.4? GCC 5.5 seems to has incompatibility issues and the bug is unknown. You can try to install gcc 5.4 in your environment and the problem should be solved.

I get more error info:
Fatal Python error: Segmentation fault

Current thread 0x00002aaaaaae8380 (most recent call first):
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 307 in <lambda>
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 225 in _apply
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203 in _apply
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203 in _apply
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 307 in cuda
  File "/home/user/idea_achieve/mmdetection/mmdet/apis/train.py", line 82 in train_detector
  File "tools/train.py", line 175 in main
  File "tools/train.py", line 179 in <module>
Segmentation fault

I don't know why it appear

**Comment by ZwwWayne** [comment]
Hi @lwdoubles ,
If so,  can you check the following things in order and report their results?

1. Check whether PyTorch is correctly installed and could use CUDA op, e.g. run python and type the following
```python
import torch
a = torch.tensor(1)
b = a.cuda()
c = b * b
```
And see whether they could correctly output results.

2. If Pytorch is correctly installed, check whether MMCV is correctly installed.
```python
import mmcv
import mmcv.ops
```
If MMCV is correctly installed, then there will be no issue of the above two commands.

3. If MMCV and Pytorch is correctly installed, you may add `print` in the mmdetection code, and see which part leads the segmentation fault.

**Comment by lwdoubles** [comment]
> ```python
> import torch
> a = torch.tensor(1)
> b = a.cuda()
> c = b * b
> ```

when I run
"""
import torch
a = torch.tensor(1)
b = a.cuda()
c = b * b
"""
there is no problem

but if I import mmcv.ops,
"""
b = a.cuda() 
"""
will get the error
Segmentation fault

**Comment by lwdoubles** [comment]
> Hi @lwdoubles ,
> If so, can you check the following things in order and report their results?
> 
> 1. Check whether PyTorch is correctly installed and could use CUDA op, e.g. run python and type the following
> 
> ```python
> import torch
> a = torch.tensor(1)
> b = a.cuda()
> c = b * b
> ```
> 
> And see whether they could correctly output results.
> 
> 1. If Pytorch is correctly installed, check whether MMCV is correctly installed.
> 
> ```python
> import mmcv
> import mmcv.ops
> ```
> 
> If MMCV is correctly installed, then there will be no issue of the above two commands.
> 
> 1. If MMCV and Pytorch is correctly installed, you may add `print` in the mmdetection code, and see which part leads the segmentation fault.

I follow that way and solve it, thank you!

**Comment by WHW-S** [comment]
could tell me what caused it? I also met it and i have verity that MMCV and Pytorch is correctly installed.
