### ISSUE TITLE
Config files and pretrained weights for Path Aggregation Network (PANet/PAFPN)

### ISSUE THREAD

**Issue by bpmsilva** [open-mmlab/mmdetection#4030]
**Describe the feature**
I would like to suggest the incorporation of config files and pre-trained weights for the Path Aggregation Network (PANet/PAFPN).

**Motivation**
The YOLO v4 explores the same concepts of PANet. Also, I had good results with the PANet architecture in a recent benchmark. However, I had to use [this repo](https://github.com/ShuLiu1993/PANet), which is based on [detectron.pytorch](https://github.com/roytseng-tw/Detectron.pytorch). The [detectron](https://github.com/facebookresearch/Detectron) and the [detectron.pytorch](https://github.com/roytseng-tw/Detectron.pytorch) are deprecated, and I had a lot of trouble to use PANet due to compatibility issues. The mmdetection repo includes config files and pre-trained weights for the PANet, but only for detection (no instance segmentation). Also, the backbone is only the ResNet-50 (is there a limitation to use deeper backbones?).

**Related resources**
I link [ShuLiu1993/PANet](https://github.com/ShuLiu1993/PANet), but I think the repo comes from someone from the Multimedia Laboratory, CUHK. So, I don't think it is something new to you guys.

Thanks for your attention.

**Comment by ZwwWayne** [comment]
PAFPN is implemented in the codebase with configs and pre-trained checkpoints [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/pafpn).
