### ISSUE TITLE
in the demo.py, can it be saved as a picture with bounding box?

### ISSUE THREAD

**Issue by Yuyang-01** [open-mmlab/mmdetection#404]
in the demo.py，in the end : show_result(img, result), can it be saved as a picture with bounding box?

**Comment by hellock** [comment]
You can modify the `show_result` method to specify an output path for [`imshow_det_bboxes`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L62).

**Comment by Yuyang-01** [comment]
Thank you. Does the result support to output the number of bounding boxes?
