### ISSUE TITLE
Only update the parameters of my own structure？

### ISSUE THREAD

**Issue by heboyong** [open-mmlab/mmdetection#4040]
I add some new layers in FPN layer, and want to continue training but only update new layers 
I change the codes in detectors:
```python
        for v in self.backbone.parameters():
            v.requires_grad = False
        for v in self.roi_head.parameters():
            v.requires_grad = False
        for v in self.rpn_head.parameters():
            v.requires_grad = False
        for v in self.neck.named_parameters():
            name,para = v
            if 'ATS' not in name:
                para.requires_grad = False
```
where the 'ATS' is my new layers, but I get this error while training:
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
How to solve this problem ?Thanks

**Comment by yuzhj** [comment]
#3667

**Comment by ZwwWayne** [comment]
If the head is frozen, there will be no gradient be passed to the neck. So you should not freeze the roi_head and rpn_head.
Since this issue duplicates #3667, this issue will be closed.
