### ISSUE TITLE
AssertionError: MMCV==1.1.4 is used but incompatible. Please install mmcv>=1.1.5, <=1.3.

### ISSUE THREAD

**Issue by handsomefengfeng** [open-mmlab/mmdetection#4058]
AssertionError: MMCV==1.1.4 is used but incompatible. Please install mmcv>=1.1.5, <=1.3.

How to upgrade ? 

Thanks!~

**Comment by v-qjqs** [comment]
Hi @handsomefengfeng, you might uninstall the installed mmcv and reinstall a newer version.
