### ISSUE TITLE
question about workflow in config file

### ISSUE THREAD

**Issue by alexwq100** [open-mmlab/mmdetection#406]
hi ,@hellock,
in this issue [https://github.com/open-mmlab/mmdetection/issues/271](url)
you say " In detection tasks we implement mAP evaluation during training to serve as validation, so the val phase is unnecessary." where is it,in the tools/train.py I haven't found.

**Comment by hellock** [comment]
You mean [evaluation hooks](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py)?
