### ISSUE TITLE
image size on multi-scale testing

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#4061]
Hi, there, a quick question on multi-scale testing.

Suppose I'm setting two-scale (a,b), (c,d) for multi-scale testing. Then during testing, for a given image I, I assume the preprocessing part will transform I to I_1 with a size of (a,b), and I_2 with a size of (c,d). However, when sending them as a batch to the model, I thought you should make the input images the same size. My question is will the preprocessing part patch these two images I_1 and I_2 to the same size before sending them to the model for inference?

Thanks!

**Comment by xvjiarui** [comment]
Hi @shanggdlk 
Two images are processed separately.
