### ISSUE TITLE
Suggestions for adding new task training function modules

### ISSUE THREAD

**Issue by mzk665** [open-mmlab/mmdetection#4062]
Hello!

For example, when I want to use faster-rcnn to train an end-to-end model to complete the task of human detection and the task of human gender classification at the same time, I need to add a branch to roi-head, and read the truth value and loss. A lot of changes are needed. Therefore, I suggest adding a new function module to help me complete these tasks quickly?
thank!

**Comment by xvjiarui** [comment]
Hi @mzk665 
You could try 3 classes directly. Or could you explain the feature request in more detail? Are you saying classify human detection result once more?
