### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#4066]
when I want to make fp16 for YOLO_V3 based on PACAL VOC,
 
_base_ = '../pascal_voc/yolov3_d53_mstrain-416_273e_voc0712.py'
# fp16 settings
fp16 = dict(loss_scale=512.)

It will report the type is not same.

**Comment by xvjiarui** [comment]
Hi @puhan123 
FP16 is not supported for YOLOv3 yet.

**Comment by puhan123** [comment]
Thank you for your reply!
