### ISSUE TITLE
RuntimeError: Found dtype Float but expected Half

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#4067]
When I want to do fp16  for yolov3 based on Pascal_voc

like this:

_base_ = '../pascal_voc/yolov3_d53_mstrain-416_273e_voc0712.py'
# fp16 settings
fp16 = dict(loss_scale=512.)

It reported error:
RuntimeError: Found dtype Float but expected Half

**Comment by xvjiarui** [comment]
Duplicate with #4066
