### ISSUE TITLE
No eval in case of non distributed training

### ISSUE THREAD

**Issue by sovrasov** [open-mmlab/mmdetection#407]
The function `_non_dist_train` doesn't register eval hook even if `validate` is True.
Is it possible to enable validation in this function?

**Comment by hellock** [comment]
Since non-distributed training is deprecated and only used for debugging, evaluation after each epoch is not supported. You need to implement a hook for that if you want to do so.

**Comment by sovrasov** [comment]
Ok, I see your point. For me distributed run on local machine is not convenient: when I need to stop an experiment, I can't do that by just pressing ctrl+c. I need to kill all the remained processes by myself. For some reason the main process doesn't send to the spawned ones information about exceptions.

**Comment by ridasalam** [comment]
@sovrasov, do you have a solution for this?

**Comment by sovrasov** [comment]
No. I suppose a new eval hook is needed here, but I didn't try to implement it.

**Comment by yhcao6** [comment]
> Ok, I see your point. For me distributed run on local machine is not convenient: when I need to stop an experiment, I can't do that by just pressing ctrl+c. I need to kill all the remained processes by myself. For some reason the main process doesn't send to the spawned ones information about exceptions.

You can simply use the command `pkill -f python` to kill the program when use distributed training, thought the command is somewhat dangerous
