### ISSUE TITLE
Is there a confidence threshold on proposals?

### ISSUE THREAD

**Issue by tiberium24** [open-mmlab/mmdetection#4071]
Hello,

I know there is a confidence threshold on the final detections. Is there a similar one for object proposals to separate background from objects?

**Comment by yhcao6** [comment]
If I understand correctly, the threshold you refer to is `test_cfg.rcnn.score_thr`
https://github.com/open-mmlab/mmdetection/blob/d3cf38d91c454b1a6881e8c36c1e4a66dc5521b8/configs/_base_/models/faster_rcnn_r50_fpn.py#L97-L108
which is used here to filter boxes with low scores https://github.com/open-mmlab/mmdetection/blob/d3cf38d91c454b1a6881e8c36c1e4a66dc5521b8/mmdet/core/post_processing/bbox_nms.py#L41
There is no similar step during proposal generation for RPN.

**Comment by tiberium24** [comment]
@yhcao6 I am referring to objects that are output of RPN and before they go to RCNN. So basically the object proposals, which are classified as objects or background from the RPN. These should have a confidence of belonging being an object (no specific class) or background. I believe you mean the same thing and it looks like the threshold of 0.05 is applied to them before they go into the RCNN. Please correct me if I am wrong.

**Comment by yhcao6** [comment]
No, they are different. `test_cfg.rcnn.score_thr` is exactly the confidence you mentioned `I know there is a confidence threshold on the final detections`. There is no such filtering step for object proposals that you mentioned `objects that are output of RPN and before they go to RCNN. So basically the object proposals, which are classified as objects or background from the RPN`. You can find the detail in this method:
https://github.com/open-mmlab/mmdetection/blob/d3cf38d91c454b1a6881e8c36c1e4a66dc5521b8/mmdet/models/dense_heads/rpn_head.py#L78-L86

**Comment by tianxianhao** [comment]
Maybe the object detection API of Tensorflow can help you solve your problem.
I remember there is a nms_score threshold parameter of faster rcnn second stage in its config file.
