### ISSUE TITLE
How to train the generating anchor method?Actually I can't find such kind of files.

### ISSUE THREAD

**Issue by vstracksj** [open-mmlab/mmdetection#4074]

**Comment by vstracksj** [comment]
> Does `generating anchor method` means methods like `RPN`? Here is an example config of `RPN`
> https://github.com/open-mmlab/mmdetection/blob/master/configs/rpn/rpn_r50_fpn_1x_coco.py

Thanks for your reply! Actually, I want to find the method of Guided Anchoring, but it seems to provide the related configuraton

**Comment by yhcao6** [comment]
Guided anchoring is there:
https://github.com/open-mmlab/mmdetection/blob/master/configs/guided_anchoring/ga_faster_r50_fpn_1x_coco.py
