### ISSUE TITLE
Add a new bbox regression loss

### ISSUE THREAD

**Issue by sovrasov** [open-mmlab/mmdetection#408]
Recently the Generalized IoU loss has been proposed to replace the regression loss in detectors (https://arxiv.org/abs/1902.09630). Any plans to add it?

**Comment by hellock** [comment]
Yes we plan to add it by the beginning of next month, but it is quite simple so you may also try it first.

**Comment by sovrasov** [comment]
I've already implemented that, but my code rather looks like a hack, so I'm waiting for the clean implementation.

**Comment by yuEzar** [comment]
where did you add your regression loss into the project?I can not find the place.

**Comment by zytx121** [comment]
Does it make sense? can you show me some experiments? Thx

**Comment by hellock** [comment]
For R-50 Faster R-CNN, GIoU loss is 1 points higher than the baseline, and IoU loss is 0.9 points higher. These implementations will be released after our refactoring.

**Comment by zytx121** [comment]
Amazing! I am much expecting!

**Comment by jihuaxu** [comment]
where should i add your regression loss into the project? Is it in bbox_head.py?

**Comment by jihuaxu** [comment]
There are always something wrong when I implemented GIoU loss. So I'm waiting for the implementation or can you show me some experiments? Thx

**Comment by JulienSiems** [comment]
Any updates on when it will be added?

**Comment by DRosemei** [comment]
> For R-50 Faster R-CNN, GIoU loss is 1 points higher than the baseline, and IoU loss is 0.9 points higher. These implementations will be released after our refactoring.

Hello @hellock I have implemented GIoU loss for libra faster rcnn. For VOC2007 test, I got 0.7points higher, while for COCO 2017val, I got 10points lower. I found that the acc increased slower than the baseline. Could you give me some advice? Waiting for your reply:)

**Comment by ZYN-guy** [comment]
> For R-50 Faster R-CNN, GIoU loss is 1 points higher than the baseline, and IoU loss is 0.9 points higher. These implementations will be released after our refactoring.

Have you tried cascade RCNN? I got a bad result.

**Comment by ZYN-guy** [comment]
> I've already implemented that, but my code rather looks like a hack, so I'm waiting for the clean implementation.
> upd: you can check out my implementation here https://github.com/grib0ed0v/mmdetection/tree/vs/focal

too many values to unpack ? How to solve it? Than you
