### ISSUE TITLE
question about faster_rcnn_r50_fpn_1x_coco-person.py config

### ISSUE THREAD

**Issue by mrbulb** [open-mmlab/mmdetection#4080]
in this config, the number of dataset class is set to one classs, but `num_classes` still is 80 in config
https://github.com/open-mmlab/mmdetection/blob/d3cf38d91c454b1a6881e8c36c1e4a66dc5521b8/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco-person.py#L2

may be the following code should be add to this config?
```python
model = dict(roi_head=dict(bbox_head=dict(num_classes=1)))
```

**Comment by ZwwWayne** [comment]
Yes I forget to update `num_classes` accordingly. Would you like to create a PR for that?

**Comment by mrbulb** [comment]
> Yes I forget to update `num_classes` accordingly. Would you like to create a PR for that?

@ZwwWayne  I have created a PR https://github.com/open-mmlab/mmdetection/pull/4088 to fix this problem 😄

**Comment by ZwwWayne** [comment]
Great! Thanks!
