### ISSUE TITLE
img_scale (height, width) or (width, height)?

### ISSUE THREAD

**Issue by tuanphan09** [open-mmlab/mmdetection#4085]
Can anyone clarify this setup config for me? And also the Input format (h, w, c) or (c, h, w)?
Thanks

**Comment by v-qjqs** [comment]
Hi @tuanphan09, generally it's (height, width) order.

**Comment by tuanphan09** [comment]
I read the code and it seems like the image was processed in (h, w) order. But the setting `img_scale` really confuses me, it was set reversed in training config. For example in DeepFashion dataset, the height is  larger than the width but the `img_scale' is (750, 1101):
https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/datasets/deepfashion.py#L9
