### ISSUE TITLE
is mmdetection memory management inefficient?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmdetection#4086]
I tried to port retinaface (https://github.com/biubug6/Pytorch_Retinaface) to mmdetection.

with GTX-1080 Ti * 4,  I can only set `samples_per_gpu` to 6 when training with mmdetection.

However, in the same network, I can set `samples_per_gpu` to 32 when training with the original retinaface.

is the memory management in mmdetection inefficient?

**Comment by v-qjqs** [comment]
Hi @twmht, I'm not familiar with retinaface and I'm sorry I cann't give you useful suggestions yet.
