### ISSUE TITLE
future version request

### ISSUE THREAD

**Issue by G-Naughty** [open-mmlab/mmdetection#4094]
Recently a new GPU has published(3090), and it only support cuda 11.0 or higher vision, so only pytorch1.7 supports it. However, the latest mmdetection vision can only supports pytorch1.3-1.6. so when will the mmdetection can publish the version to support pytorch1.7(GPU 3090)

**Comment by xvjiarui** [comment]
Hi @G-Naughty 
It will be supported next month.

**Comment by G-Naughty** [comment]
thank you very much
