### ISSUE TITLE
The question about mmdet & mmcls

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#4095]
Hi, thank you for your amazing job!
I have a little question about mmdet and mmcls
I want to use the backbone of mmcls in mmdet, can I directly transplant the *.py of mmcls/backbone to mmdet/backbone (without any modification except the modify in '__int__.py', only transplant directly)?If can't, how can I use the backbone of mmcls in mmdet in the easiest way？
Thx!

**Comment by xvjiarui** [comment]
Hi @zhongqiu1245 
For ResNet, they are compatible. But there is no guarantee for others. 
We plan to bridge the gap by the end of next month.

**Comment by zhongqiu1245** [comment]
Thank you! @xvjiarui
