### ISSUE TITLE
how can i get dataset precision and accuracy

### ISSUE THREAD

**Issue by chenjiabo5197** [open-mmlab/mmdetection#4096]
i want to know the precision and accuracy about every epoch result about my datasets.but every epoch only output the recall and ap about my dataset,how can i get the precision and accuracy?

**Comment by yhcao6** [comment]
To get accuracy, you can refer https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_runtime.md#customize-workflow.

AP means average precision, what precision you want?

**Comment by chenjiabo5197** [comment]
hello,when i use your addvise,change workflow = [('train', 1)] to workflow = [('train', 1),('val', 1)],the program show attributeerror:'ConfigDict' object has no attribute 'pipeline'

> 
> 
> To get accuracy, you can refer https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_runtime.md#customize-workflow.
> 
> AP means average precision, what precision you want?

hello,when i use your addvise,change workflow = [('train', 1)] to workflow = [('train', 1),('val', 1)],the program show attributeerror:'ConfigDict' object has no attribute 'pipeline'

**Comment by chenjiabo5197** [comment]
> 
> 
> To get accuracy, you can refer https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_runtime.md#customize-workflow.
> 
> AP means average precision, what precision you want?

OK，thanks
