### ISSUE TITLE
run '.\datasets\loader\build_loader.py', ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by xingkong5hao** [open-mmlab/mmdetection#41]
"\Python\Python36\lib\site-packages\mmdet\datasets\loader\build_loader.py", line 10, in <module>
import resource
ModuleNotFoundError: No module named 'resource'

Q: Nowhere to find the module resource and I can ensure that it is not another package of Python. Would any one tell me where the module is? Disappear? or uncompleted?

**Comment by hellock** [comment]
Are you using Windows? You can just delete the related lines and try again, but mmdetection has been tested only on Ubuntu and CentOS and I guess it is hard to run it on Windows.

**Comment by yavana** [comment]
> Are you using Windows? You can just delete the related lines and try again, but mmdetection has been tested only on Ubuntu and CentOS and I guess it is hard to run it on Windows.

I got "No module named 'mmdet.ops.nms.gpu_nms'"

**Comment by dxggithub** [comment]
I got "No module named 'mmdet.ops.nms.gpu_nms'" too.

**Comment by softmicro929** [comment]
> > Are you using Windows? You can just delete the related lines and try again, but mmdetection has been tested only on Ubuntu and CentOS and I guess it is hard to run it on Windows.
> 
> I got "No module named 'mmdet.ops.nms.gpu_nms'"

maybe make fail. try make again.

**Comment by liveway6** [comment]
> > Are you using Windows? You can just delete the related lines and try again, but mmdetection has been tested only on Ubuntu and CentOS and I guess it is hard to run it on Windows.
> 
> I got "No module named 'mmdet.ops.nms.gpu_nms'"

Hi, I meet the same problem.   "No module named 'mmdet.ops.nms.gpu_nms'" Are you solved?  codes running in Linux's virtual environment:
python：3.6
gcc：5.5.0
pytorch：0.4.1
CUDA Version 9.0.176

**Comment by liveway6** [comment]
> > > Are you using Windows? You can just delete the related lines and try again, but mmdetection has been tested only on Ubuntu and CentOS and I guess it is hard to run it on Windows.
> > 
> > 
> > I got "No module named 'mmdet.ops.nms.gpu_nms'"
> 
> maybe make fail. try make again.

It works. Thanks!

**Comment by ChenConnie** [comment]
@softmicro929  hello,I met the problem that No module named 'mmdet.ops.nms.gpu_nms',could please tell me how to solve it specificly?

**Comment by XiaYuanxiang** [comment]
also meet  ModuleNotFoundError: No module named 'mmdet.ops.nms.gpu_nms'
