### ISSUE TITLE
MMDetection Remote server install problem

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#4101]
Hi, 
MMDetection is installed on my home computer and works fine. The institution I work for has a service that provides remote server support. In this service, you have a directory with your own username under the server's home directory. The Server’s operating system is Centos7.3 .In this service, there is no GPU support directly. I run GPU-requiring jobs (eg mmdetection training) on GPU-equipped servers by sending them to the job queue via the SLURM workload manager.

I prepare the relevant batch file to perform `pip install -v -e .  `command, which is the last step of mmdetection installation, with the GPU and send the work to the queue. The job I sent is working and the messages that mmdetection has been installed without any problems are written to the output file. When I start the train after this process is finished, I get the error that the nms was not compiled with the GPU.

Although I installed the previous versions of mmdetection as I explained above, I did not get this error and I did the train and test process many times without any problems. If you ask what the difference is, I think it is the absence of the build folder in the latest version.

1) How can I solve this problem? Anyone have any ideas?

2) Another solution that comes to my mind is to copy the mmdetection files installed on the home computer with GPU support to the home directory on the server. Do you think it works? If it works, is it enough to just copy the mmdetection folder? Do I have to copy files under "conda / envs / open-mmlab" as well?

Thanks...

**Comment by yhcao6** [comment]
When you installing mmcv, have you add `MMCV_WITH_OPS=1`?

**Comment by zerok01** [comment]
> When you installing mmcv, have you add `MMCV_WITH_OPS=1`?

Thank you very much. It worked...
