### ISSUE TITLE
Pytorch2onnx 

### ISSUE THREAD

**Issue by xiaohuaibaoguigui** [open-mmlab/mmdetection#4102]
i want convert .pth model to .onnx model by tools/pytorch2onnx.py,but there is something wrong.what can i do?
`(open-mmlab) zxh@ubuntu:~/zxh_code/mmdetection$ python tools/pytorch2onnx.py configs/yolo/yolov3_d53_320_273e_coco.py  work_dirs/yolov3_d53_320_273e_coco-421362b6.pth --out work_dirs/epoch_24.onnx --verify
/home/zxh/zxh_code/mmdetection/mmdet/core/anchor/anchor_generator.py:255: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  feat_h = int(feat_h)
/home/zxh/zxh_code/mmdetection/mmdet/core/anchor/anchor_generator.py:256: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  feat_w = int(feat_w)
/home/zxh/zxh_code/mmdetection/mmdet/core/anchor/anchor_generator.py:199: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  xx = x.repeat(len(y))
/home/zxh/zxh_code/mmdetection/mmdet/core/anchor/anchor_generator.py:200: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  yy = y.view(-1, 1).repeat(1, len(x)).view(-1)
/home/zxh/zxh_code/mmdetection/mmdet/models/dense_heads/yolo_head.py:260: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  pred_map[..., :2] = torch.sigmoid(pred_map[..., :2])
/home/zxh/zxh_code/mmdetection/mmdet/core/bbox/coder/yolo_bbox_coder.py:69: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/home/zxh/zxh_code/mmdetection/mmdet/core/bbox/coder/yolo_bbox_coder.py:70: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(-1) == bboxes.size(-1) == 4
/home/zxh/zxh_code/mmdetection/mmdet/models/dense_heads/yolo_head.py:277: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if 0 < nms_pre < conf_pred.size(0):
/home/zxh/zxh_code/mmdetection/mmdet/models/dense_heads/yolo_head.py:293: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if with_nms and (multi_lvl_conf_scores.size(0) == 0):
/home/zxh/zxh_code/mmdetection/mmdet/core/post_processing/bbox_nms.py:33: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] > 4:
/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py:255: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if len(boxes_for_nms) < split_thr:
/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py:82: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py:83: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py:112: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator sub_. This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  boxes[:, -2:] -= 1
/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py:112: TracerWarning: There are 4 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  boxes[:, -2:] -= 1
/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py:655: UserWarning: ONNX export failed on ATen operator new_zeros because torch.onnx.symbolic_opset11.new_zeros does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 142, in <module>
    normalize_cfg=normalize_cfg)
  File "tools/pytorch2onnx.py", line 43, in pytorch2onnx
    opset_version=opset_version)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 656, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/home/zxh/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'new_zeros'
`

**Comment by xiaohuaibaoguigui** [comment]
mmcv-full                 1.1.5                    pypi_0    pypi
mmdet                     2.6.0                     dev_0    <develop>

**Comment by fadonoso** [comment]
Hi, is it possible to convert a mmdetection .pth to .onnx to be used with jetson-inference (detectnet) on a jetson nano?

**Comment by wxhqw** [comment]
@xiaohuaibaoguigui @fadonoso I also meet this problem, do you have solved it ???

**Comment by RunningLeon** [comment]
Pls. try with latest mmcv and mmdetection.
