### ISSUE TITLE
the mmdet has the ciou giou loss,but how can i use it??

### ISSUE THREAD

**Issue by henbucuoshanghai** [open-mmlab/mmdetection#4106]
how to set  the kind of bbox loss to the ciou or giou loss?
where?

**Comment by yhcao6** [comment]
Config of giou: https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_giou_1x_coco.py

**Comment by henbucuoshanghai** [comment]
how&nbsp; to use it?

**Comment by henbucuoshanghai** [comment]
已解决  请问frcnn在voc上训练多少epoch呢？默认的20？   map能到多少？78？

**Comment by yhcao6** [comment]
12 epoch, 79.5, please refer to the detail in there, https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/README.md

**Comment by henbucuoshanghai** [comment]
多谢回复 能最后问一句 为何mmdet训练voc或coco只需要12 epoches   ？太少了吧   有很多论文是一百多二百才收敛结束，mmdet为何很快结束？

**Comment by yhcao6** [comment]
The learning rate is different.

**Comment by henbucuoshanghai** [comment]
I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.
but when i use the frcnn r50 diou train the COCO2017,the map as follow...          
very bad..
why?

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.219
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.381
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.225
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.381
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.381
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.381
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482
2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py
2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317]	bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281

**Comment by henbucuoshanghai** [comment]
only 21.9  ,but the model mmdet given is 37.4.....how to get it?

R-50-FPN | pytorch | 1x | 4.0 | 21.4 | 37.4
https://github.com/open-mmlab/mmdetection/tree/master/configs/faster_rcnn

**Comment by henbucuoshanghai** [comment]
frcnn_r50_fpn with diou，the final map is 35.1，but the mmdet given is 37.4.............why?


Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py
2020-11-17 23:49:31,990 - mmdet - INFO - Epoch(val) [12][29317]	bbox_mAP: 0.3510, bbox_mAP_50: 0.5450, bbox_mAP_75: 0.3790, bbox_mAP_s: 0.2010, bbox_mAP_m: 0.3800, bbox_mAP_l: 0.4500, bbox_mAP_copypaste: 0.351 0.545 0.379 0.201 0.380 0.450

**Comment by yhcao6** [comment]
Do you train the model with 1 GPU? Then you need to scale the learning rate accordingly.

**Comment by henbucuoshanghai** [comment]
tks for your help.
I have two 2080ti GPUS, and change nothing about the faster_rcnn_r50_fpn_diou_1x_coco.py   and other cfg parameters。
trainset is COCO2017 with 118k images,   test set is COCO2017 val.
with 2 GPUs,I train 12 epoch,  use 30 hours

anything wrong?

**Comment by henbucuoshanghai** [comment]
the schedule_1x.py is used.

**Comment by yhcao6** [comment]
The config supposes you train with 8GPUs. Now you train with 2 GPUs now, you need to divide the original learning rate by 4. since the ratio of total batch size is 8 * 2 / (2 * 2) = 4.

**Comment by henbucuoshanghai** [comment]
in schedule_1x.py ,set  lr=0.02  to lr=0.005????   no need to chnage others?

optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)

**Comment by henbucuoshanghai** [comment]
by the way ,in my coco_detection.py   i only chnage the coco path.

this means?   and no need to change ???
 samples_per_gpu=2,
  workers_per_gpu=2,

**Comment by yhcao6** [comment]
A better way is to override it in the target config.

**Comment by henbucuoshanghai** [comment]
in schedule_1x.py ,set the lr=0.005?             override means?

**Comment by yhcao6** [comment]
Please refer to the documentation: https://github.com/open-mmlab/mmdetection/tree/master/docs

**Comment by richstella** [comment]
> 我使用frcnn_r50_diou训练VOC2007，结果很好，技术水平很高。
> 但是当我使用frcnn_r50 diou火车COCO2017时，地图如下...
> 非常糟糕..
> 为什么？
> 
> 平均精度（AP）@ [IoU = 0.50：0.95 |面积=全部| maxDets = 100] = 0.219
> 平均精度（AP）@ [IoU = 0.50 |面积=全部| maxDets = 1000] = 0.381
> 平均精度（AP）@ [IoU = 0.75 |面积=全部| maxDets = 1000] = 0.225
> 平均精度（AP）@ [IoU = 0.50：0.95 |面积=小| maxDets = 1000] = 0.119
> 平均精度（AP）@ [IoU = 0.50：0.95 | 面积=中| maxDets = 1000] = 0.237
> 平均精度（AP）@ [IoU = 0.50：0.95 |面积=大| maxDets = 1000] = 0.281
> 平均召回率（AR）@ [IoU = 0.50：0.95 |面积=全部| maxDets = 100] =
> 0.381平均召回率（AR）@ [IoU = 0.50：0.95 |面积=全部| maxDets = 300] =
> 0.381平均召回率（AR）@ [IoU = 0.50：0.95 |面积=全部|maxDets = 1000] =
> 0.381平均召回率（AR）@ [IoU = 0.50：0.95 |面积=小| maxDets = 1000] = 0.207
> 平均召回率（AR）@ [IoU = 0.50：0.95 | 面积=中| maxDets = 1000] = 0.402
> 平均召回率（AR）@ [IoU = 0.50：0.95 |面积=大| maxDets = 1000] = 0.482
> 2020-11-17 10：57：04,171-mmdet-INFO-Exp名称：faster_rcnn_r50_fpn_diou_1x_coco.py
> 2020-11-17 10：57：04,171-mmdet-INFO-Epoch（val）[7] [ 29317] bbox_mAP：0.2190，bbox_mAP_50：0.3810，bbox_mAP_75：0.2250，bbox_mAP_s：0.1190，bbox_mAP_m：0.2370，bbox_mAP_1：0.2810，bbox_mAP_copy_paste：0.219 0.381 0.225 0.119 0.237 0.281

**Comment by richstella** [comment]
请问用什么指令能获得上面的结果？我是coco格式的数据集

**Comment by Duanjiayu** [comment]
> I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.
> but when i use the frcnn r50 diou train the COCO2017,the map as follow...
> very bad..
> why?
> 
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482
> 2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py
> 2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281

When I use DIoU or CIoU in faster-rcnn's bbox loss function,the result is always 'nan',could you tell me how to use it correctly，thanks.
Is it the reason for the input?how to transform it correctly？

**Comment by richstella** [comment]
maybe the lr is too big.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106)





  
I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.
 but when i use the frcnn r50 diou train the COCO2017,the map as follow...
 very bad..
 why?
 
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219
 Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381
 Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225
 Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119
 Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237
 Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281
 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381
 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381
 Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381
 Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207
 Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402
 Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482
 2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py
 2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281
  
When I use DIoU or CIoU in faster-rcnn's bbox loss function,the result is always 'nan',could you tell me how to use it correctly，thanks.
 Is it the reason for the input?how to transform it correctly？

**Comment by Duanjiayu** [comment]
I set batchsize 4，lr0.005.what's you setting？I just replace 'L1loss' to 'DIoUloss',is it more than that?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月14日(星期天) 晚上9:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106)





 maybe the lr is too big. 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年3月14日(星期天) 晚上9:10 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106) 
 
 
 
 
 
    
 I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art. 
  but when i use the frcnn r50 diou train the COCO2017,the map as follow... 
  very bad.. 
  why? 
   
 Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219 
  Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381 
  Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225 
  Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119 
  Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237 
  Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281 
  Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381 
  Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381 
  Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381 
  Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207 
  Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402 
  Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482 
  2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py 
  2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281 
    
 When I use DIoU or CIoU in faster-rcnn's bbox loss function,the result is always 'nan',could you tell me how to use it correctly，thanks. 
  Is it the reason for the input?how to transform it correctly？

**Comment by richstella** [comment]
lr=(gpu_num*sample_per_gpu)/16*0.02


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106)





 I set batchsize 4，lr0.005.what's you setting？I just replace 'L1loss' to 'DIoUloss',is it more than that? 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年3月14日(星期天) 晚上9:15 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106) 
 
 
 
 
 
  maybe the lr is too big.  
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年3月14日(星期天) 晚上9:10  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106)  
   
   
   
   
   
      
  I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.  
   but when i use the frcnn r50 diou train the COCO2017,the map as follow...  
   very bad..  
   why?  
     
  Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219  
   Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381  
   Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225  
   Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119  
   Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237  
   Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281  
   Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381  
   Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381  
   Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381  
   Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207  
   Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402  
   Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482  
   2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py  
   2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281  
      
  When I use DIoU or CIoU in faster-rcnn's bbox loss function,the result is always 'nan',could you tell me how to use it correctly，thanks.  
   Is it the reason for the input?how to transform it correctly？

**Comment by Duanjiayu** [comment]
yeah，my lr=(1*4)/16*0.02=0.005.Do you just replace bbox loss function simply?Thank you for your reply,thanks






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月14日(星期天) 晚上9:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106)





 lr=(gpu_num*sample_per_gpu)/16*0.02 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年3月14日(星期天) 晚上9:23 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106) 
 
 
 
 
 
  I set batchsize 4，lr0.005.what's you setting？I just replace 'L1loss' to 'DIoUloss',is it more than that?  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年3月14日(星期天) 晚上9:15  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106)  
   
   
   
   
   
   maybe the lr is too big.   
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年3月14日(星期天) 晚上9:10   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [open-mmlab/mmdetection] the mmdet has the ciou giou loss,but how can i use it?? (#4106)   
     
     
     
     
     
        
   I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.   
    but when i use the frcnn r50 diou train the COCO2017,the map as follow...   
    very bad..   
    why?   
       
   Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219   
    Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381   
    Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225   
    Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119   
    Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237   
    Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281   
    Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381   
    Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381   
    Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381   
    Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207   
    Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402   
    Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482   
    2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py   
    2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281   
        
   When I use DIoU or CIoU in faster-rcnn's bbox loss function,the result is always 'nan',could you tell me how to use it correctly，thanks.   
    Is it the reason for the input?how to transform it correctly？

**Comment by Duanjiayu** [comment]
> I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.
> but when i use the frcnn r50 diou train the COCO2017,the map as follow...
> very bad..
> why?
> 
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482
> 2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py
> 2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281

您好，请问你是怎么使用的diou loss，除了在faster_rcnn_r50_fpn.py里bbox替换成diou，还需要哪些操作？

**Comment by Duanjiayu** [comment]
> I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.
> but when i use the frcnn r50 diou train the COCO2017,the map as follow...
> very bad..
> why?
> 
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482
> 2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py
> 2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281

您好，请问你是怎么使用的diou loss，除了在faster_rcnn_r50_fpn.py里bbox替换成diou，还需要哪些操作？

**Comment by Duanjiayu** [comment]
> I use the frcnn_r50_diou train the VOC2007,the resout is good ,state of the art.
> but when i use the frcnn r50 diou train the COCO2017,the map as follow...
> very bad..
> why?
> 
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.219
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = 0.381
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = 0.225
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.119
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.237
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.281
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = 0.381
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.207
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.402
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.482
> 2020-11-17 10:57:04,171 - mmdet - INFO - Exp name: faster_rcnn_r50_fpn_diou_1x_coco.py
> 2020-11-17 10:57:04,171 - mmdet - INFO - Epoch(val) [7][29317] bbox_mAP: 0.2190, bbox_mAP_50: 0.3810, bbox_mAP_75: 0.2250, bbox_mAP_s: 0.1190, bbox_mAP_m: 0.2370, bbox_mAP_l: 0.2810, bbox_mAP_copypaste: 0.219 0.381 0.225 0.119 0.237 0.281

您好，请问您是怎么使用的diou loss，除了在faster_rcnn_r50_fpn.py里bbox替换成diou，还需要哪些操作？
