### ISSUE TITLE
two problems of about ATSS and TTA 

### ISSUE THREAD

**Issue by SnailForce** [open-mmlab/mmdetection#4107]
First,
ATSS (model)

0.394 0.576 0.428 0.236 0.429 0.503  # img_scale=(1333, 800),
0.391 0.575 0.424 0.258 0.426 0.471  # img_scale=(1600, 960),
0.404 0.583 0.440 0.260 0.438 0.499  # img_scale=[(1333, 800), (1600, 960)],
0.398 0.580 0.433 0.247 0.435 0.510  # img_scale=(1333, 800), flip=True,

ATSS支持TTA的issue中，请问第三行和第四行是指什么意思？
我的理解是第三行是多尺度测试，第四行是指TTA后的结果吗?为什么比第三行看起来在某些指标上效果要差？

Second 
how to use TTA?
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(1333, 400), (1333, 800)],
        flip=True,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
请问这样使用正确吗，就是
type='MultiScaleFlipAug',
        img_scale=[(1333, 400), (1333, 800)],
        flip=True,
这样写是对的吗？
小白求解

**Comment by yhcao6** [comment]
Third line: `0.404 0.583 0.440 0.260 0.438 0.499 # img_scale=[(1333, 800), (1600, 960)]` means test with two image scale
Forth line: `0.398 0.580 0.433 0.247 0.435 0.510 # img_scale=(1333, 800), flip=True` means test with the image and its flipped version.
They are both TTA and the AP is higher than the baseline of single-scale test (first line and second line).

**Comment by SnailForce** [comment]
Thank you for your answer, then my writing below uses two scales at the same time and uses the flipped version, right?

type='MultiScaleFlipAug',
img_scale=[(1333, 400), (1333, 800)],
flip=True,

**Comment by ZwwWayne** [comment]
Yes.
