### ISSUE TITLE
DetectorRS with one class

### ISSUE THREAD

**Issue by cuong12ly1** [open-mmlab/mmdetection#4108]
I want to use DetectorRS HTC r50 with my dataset have one class follow coco dataset.  I try to follow the tutorial on website when set, (I try faster RCNN follow tutorial and it worked for me)
model = dict(
    roi_head=dict(
        bbox_head=[dict(num_classes=1),
                              dict(num_classes=1),
                              dict(num_classes=1)],)
and don't use mask head
I try list dict num_class because of Cascade RCNN but got an error:
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'num_classes\': 1}\nNone
How can i fix it? And how can i modify config file without mask head?

**Comment by cuong12ly1** [comment]
if I don't want to use semantic segmentation, can I delete mask roi-extractor and mask head from config file? (in htc_without_semantic_r50_fpn_1x_coco.py and htc_r50_1x_coco.py)

**Comment by ryanmaxwell96** [comment]
Did you ever figure this out?
