### ISSUE TITLE
Using a mmdetection model on jetson-nano?

### ISSUE THREAD

**Issue by fadonoso** [open-mmlab/mmdetection#4109]
Hi, is it possible to convert a mmdetection .pth to .onnx to be used with jetson-inference (detectnet) on a jetson nano?

So if not, how is the best way to optimise (improve fps) the model on jetson-nano?

Thanks

**Comment by yuzhj** [comment]
tensorrt is a good choice, [here](https://github.com/grimoire/mmdetection-to-tensorrt) is a repository which could transform the model from mmdetection to tensorrt directly

**Comment by fadonoso** [comment]
Thanks!! I will check it out.
