### ISSUE TITLE
Error: 'VOCDataset' object has no attribute 'img_ids'

### ISSUE THREAD

**Issue by Yuyang-01** [open-mmlab/mmdetection#411]
When i test voc-style data, it report an error that  File coco_utils.py, line 106, in det2json,    
img_id = dataset.img_ids[idx], AttributeError: 'VOCDataset' object has no attribute 'img_ids'.
How can i solve this problem?

**Comment by hellock** [comment]
You need to use voc_eval instead of coco_eval for voc-style datasets. #226 #145

**Comment by Yuyang-01** [comment]
Thank you for your explanation, i have solved the prolem.

**Comment by lizxchen** [comment]
@Yuyang-01 I met the same question,but i can not solve it ,can you help me ?

**Comment by TyroneLi** [comment]
> @Yuyang-01 I met the same question,but i can not solve it ,can you help me ?
take a look at tools/voc_eval.py,you need two steps to evalutate voc-format dataset.

**Comment by mathmanu** [comment]
You may be passing the --eval argument while running tools/test.py. Do not do that to evaluate results on voc. 
Instead write the results to a pkl file by using --out results.pkl. Then evaluate the results using tools/voc_eval.py

**Comment by TonojiKiobya** [comment]
Solution.
1. First find the result.pkl  via tools/test.py script
For example:  python tools/test.py configs/cascade_rcnn_r50_caffe_c4_1x.py work_dirs/xyz/epoch_18.pth --out results1.pkl

2: Second use voc_eval.py to obyain results
For example python tools/voc_eval.py ./results1.pkl configs/cascade_rcnn_r50_caffe_c4_1x.py
