### ISSUE TITLE
How can I view other metrics?

### ISSUE THREAD

**Issue by secondwhao** [open-mmlab/mmdetection#4110]
How can I view other metrics?

For example, How can I view the recall value when IoU is 0.5 or 0.75.
How can I view the mMR in human detection.

**Comment by yhcao6** [comment]
You can modify COCOAPI to evaluate the recall of thr 0.5 or 0.75,
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L502-L511

We don't support mMR in human detection.

**Comment by hsp2454** [comment]
Did you solve this problem?
