### ISSUE TITLE
Setting Score Threshold Per Class

### ISSUE THREAD

**Issue by masotrix** [open-mmlab/mmdetection#4114]
I have modified COCOeval.summary to return the score threshold that maximizes F1 score per class Now I would like to use the returned scores with my models at inference

How could I set these 'optimal' score threshold per class in mmdetection?

**Comment by yhcao6** [comment]
Currently, we don't support setting score threshold for each class individually. But you can implement it yourself. The filter step is in there:
https://github.com/open-mmlab/mmdetection/blob/048c41a8d00f57ed33affd0ea73c8bc6de76e98a/mmdet/core/post_processing/bbox_nms.py#L31-L42

**Comment by masotrix** [comment]
Thanks, I am going to check it

**Comment by masotrix** [comment]
Thanks, I am going to leave my solution here in case someone needs it

If your code specifies a list as the class-wise score thresholds before init_detector(), e.g in case of 3 classes
```
cfg.test_cfg.rcnn.score_thr=[0.82, 0.6, 0.74]
model = init_detector(cfg, cfg.load_from, device='cuda:0')
```
it is only required to transform list to torch.Tensor appropriately before score thresholding at multiclass_nms(), i.e.:
```
 if type(score_thr) == type([]):
   if multi_scores.is_cuda:
     score_thr = torch.cuda.FloatTensor(score_thr);
   else:
     score_thr = torch.FloatTensor(score_thr);

 # filter out boxes with low scores 
 valid_mask = scores > score_thr 
```
