### ISSUE TITLE
Could you provide a code example of adding VGG-16 into backbone and using it in faster rcnn?

### ISSUE THREAD

**Issue by tianxianhao** [open-mmlab/mmdetection#4115]
I need to implement the Faster-rcnn + VGG16. But I dont find the VGG backbone of faster rcnn. There is only a file about VGG under mmdet/models/backbones, that is ssd_vgg,py. It can be used directly in fasterrcnn config file? I hope the tutorial can be more detailed. Could you provide a more detailed tutorial about add a VGG backbone into Faster rcnn? A colab example is more appreciated. Thanks.

**Comment by tianxianhao** [comment]
what should i pay attention to when implementing my task based on the config file of mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py. For example, the input channel of FPN or else.

**Comment by yhcao6** [comment]
We don't support Faster R-CNN with backbone VGG16. But you can implement it by yourself. The logic should be similar to ResNet which receives an image and output a sequence of features. You can refer to other public implementations of VGG16 Faster R-Cnn and try to migrate it to MMDetection.

**Comment by freepoet** [comment]
Hi,bro!~</br>
Have you implemented Faster R-CNN with backbone VGG16 successfully?

**Comment by tianxianhao** [comment]
> Hi,bro!~ Have you implemented Faster R-CNN with backbone VGG16 successfully?

I build the backbone based on mmcv.cnn.VGG

**Comment by tianxianhao** [comment]
> Hi,bro!~ Have you implemented Faster R-CNN with backbone VGG16 successfully?



> > Hi,bro!~ Have you implemented Faster R-CNN with backbone VGG16 successfully?
> 
> Hi, could you provide a code of VGG16 for reference?

https://github.com/tianxianhao/FasterRCNN_VGG16_DC5.git

**Comment by PineYY** [comment]
> > Hi,bro!~ Have you implemented Faster R-CNN with backbone VGG16 successfully?
> 
> > > Hi,bro!~ Have you implemented Faster R-CNN with backbone VGG16 successfully?
> > 
> > 
> > Hi, could you provide a code of VGG16 for reference?
> 
> https://github.com/tianxianhao/FasterRCNN_VGG16_DC5.git


> > Hi,bro!~ Have you implemented Faster R-CNN with backbone VGG16 successfully?
> 
> > > Hi,bro!~ Have you implemented Faster R-CNN with backbone VGG16 successfully?
> > 
> > 
> > Hi, could you provide a code of VGG16 for reference?
> 
> https://github.com/tianxianhao/FasterRCNN_VGG16_DC5.git

Thanks for your help.
