### ISSUE TITLE
Save best mAP model

### ISSUE THREAD

**Issue by CuongNN218** [open-mmlab/mmdetection#4117]
I want to save the best accuracy model along with epochs model. How can I do it?

**Comment by cuong12ly1** [comment]
@ZwwWayne can you help me ?

**Comment by yhcao6** [comment]
#3773

**Comment by cuong12ly1** [comment]
@yhcao6 did it merge to master branch?

**Comment by yhcao6** [comment]
Not yet, but it will be merged soon.

**Comment by ZwwWayne** [comment]
Since the PR is merged, this issue is closed. Feel free if you have any further questions.

**Comment by winner-4** [comment]
I have the same problem as you, don't want to save the model for each round, just want the model that performs best on the validation set. Where did you change it?
