### ISSUE TITLE
How to use OHEMSampler in RetinaNet?

### ISSUE THREAD

**Issue by Ssugar10** [open-mmlab/mmdetection#4120]
I use c2 in resnet so I really need OHEM to reduce the negative samples in training. Does mmdetection offer an interface for RetinaNet to use OHEM in v2.x. Thanks!

**Comment by yhcao6** [comment]
Retinanet use Focal Loss to balance the training samples.
We have only tested OHEMSampler to two-stage models. So I am afraid it can't be directly applied it to RetinaNet.
