### ISSUE TITLE
help install mvcc in windows 10

### ISSUE THREAD

**Issue by a527533557** [open-mmlab/mmdetection#4121]
I fllow the guide to install the pytorch、MMCV，but can't success even if i use  all method,please help me！
there are error message below,thanks!(when i install MMCV pip install mmcv-full)
too long to submit all of message,i put some of it

    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/autograd/autograd.h
    注意: 包含文件:    F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch\csrc\api\include\torch/python.h
    注意: 包含文件:     F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/Device.h
    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/python_headers.h    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\include\Python.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\patchlevel.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyconfig.h
    注意: 包含文件:         F:\Windows Kits\10\include\10.0.18362.0\ucrt\io.h
    注意: 包含文件:          F:\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h
    注意: 包含文件:         F:\Windows Kits\10\include\10.0.18362.0\shared\basetsd.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pymacconfig.h
    注意: 包含文件:        F:\Windows Kits\10\include\10.0.18362.0\ucrt\assert.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyport.h
    注意: 包含文件:         F:\Windows Kits\10\include\10.0.18362.0\ucrt\math.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pymacro.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyatomic.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pymath.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pytime.h
    注意: 包含文件:         F:\ProgramData\Anaconda3\envs\paper\include\object.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pymem.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\objimpl.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\typeslots.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyhash.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pydebug.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\bytearrayobject.h
    注意: 包含文件:         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\stdarg.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\bytesobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\unicodeobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\longobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\longintrepr.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\boolobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\floatobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\complexobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\rangeobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\memoryobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\tupleobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\listobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\dictobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/utils/tensor_numpy.h
    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/Generator.h
    [11/34] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DMMCV_WITH_CUDA -IF:\mmcv\mmcv-master\mmcv-master\mmcv\ops\csrc -IF:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include -IF:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch\csrc\api\include -IF:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\TH -IF:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IF:\ProgramData\Anaconda3\envs\paper\include -IF:\ProgramData\Anaconda3\envs\paper\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IF:\Windows Kits\10\include\10.0.18362.0\ucrt" "-IF:\Windows Kits\10\include\10.0.18362.0\shared" "-IF:\Windows Kits\10\include\10.0.18362.0\um" "-IF:\Windows Kits\10\include\10.0.18362.0\winrt" "-IF:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c F:\mmcv\mmcv-master\mmcv-master\mmcv\ops\csrc\pytorch\focal_loss.cpp /FoF:\mmcv\mmcv-master\mmcv-master\build\temp.win-amd64-3.7\Release\mmcv/ops/csrc/pytorch\focal_loss.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
    注意: 包含文件:  F:\mmcv\mmcv-master\mmcv-master\mmcv\ops\csrc\pytorch_cpp_helper.hpp
    注意: 包含文件:   F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/extension.h

    注意: 包含文件:                 F:\Windows Kits\10\include\10.0.18362.0\ucrt\float.h
    注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\climits
    注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\intrin0.h
    注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual 
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\objimpl.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\typeslots.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyhash.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pydebug.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\bytearrayobject.h
    注意: 包含文件:         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\stdarg.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\bytesobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\unicodeobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\longobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\longintrepr.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\boolobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\floatobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\complexobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\rangeobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\memoryobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\tupleobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\listobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\dictobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\odictobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\enumobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\setobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\methodobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\moduleobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\funcobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\classobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\fileobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pycapsule.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\traceback.h
    注意: 包含文件:         F:\ProgramData\Anaconda3\envs\paper\include\pystate.h
    注意: 包含文件:          F:\ProgramData\Anaconda3\envs\paper\include\pythread.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\sliceobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\cellobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\iterobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\genobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\descrobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\warnings.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\weakrefobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\structseq.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\namespaceobject.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\codecs.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyerrors.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\context.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyarena.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\modsupport.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\compile.h
    注意: 包含文件:         F:\ProgramData\Anaconda3\envs\paper\include\code.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pythonrun.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pylifecycle.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\ceval.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\sysmodule.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\osmodule.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\intrcheck.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\import.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\abstract.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\bltinmodule.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\eval.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyctype.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pystrtod.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pystrcmp.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\dtoa.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\fileutils.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\include\pyfpe.h
    注意: 包含文件:     F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/Dtype.h
    注意: 包含文件:     F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/DynamicTypes.h
    注意: 包含文件:     F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/utils/pybind.h
    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11/pybind11.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\attr.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\cast.h
    注意: 包含文件:         F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\pytypes.h
    注意: 包含文件:          F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\detail/common.h
    注意: 包含文件:           F:\ProgramData\Anaconda3\envs\paper\include\frameobject.h
    注意: 包含文件:          F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\buffer_info.h
    注意: 包含文件:         F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\detail/typeid.h    注意: 包含文件:         F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\detail/descr.h
    注意: 包含文件:         F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\detail/internals.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\options.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\detail/class.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11\detail/init.h
    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\pybind11/stl.h
    注意: 包含文件:       C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\valarray
    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/autograd/python_variable.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/THP_export.h
    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/utils/python_tuples.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/Exceptions.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/utils/auto_gil.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/jit/runtime/jit_exception.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\ATen/detail/FunctionTraits.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/utils/object_ptr.h
    注意: 包含文件:       F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/utils/python_numbers.h
    注意: 包含文件:        F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/utils/tensor_numpy.h
    注意: 包含文件:      F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\include\torch/csrc/Generator.h
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\utils\cpp_extension.py", line 1522, in _run_ninja_build
        env=env)
      File "F:\ProgramData\Anaconda3\envs\paper\lib\subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "F:\mmcv\mmcv-master\mmcv-master\setup.py", line 228, in <module>
        zip_safe=False)
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\utils\cpp_extension.py", line 653, in build_extensions
        build_ext.build_extensions(self)
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "F:\ProgramData\Anaconda3\envs\paper\lib\distutils\command\build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\utils\cpp_extension.py", line 635, in win_wrap_ninja_compile
        with_cuda=with_cuda)
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\utils\cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "F:\ProgramData\Anaconda3\envs\paper\Lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'F:\ProgramData\Anaconda3\envs\paper\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'F:\\mmcv\\mmcv-master\\mmcv-master\\setup.py'"'"'; __file__='"'"'F:\\mmcv\\mmcv-master\\mmcv-master\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by a527533557** [comment]
my pytorch==1.7 but cuda==10.2,when i update the cuda to 11.0,success!

**Comment by forallsunday** [comment]
> my pytorch==1.7 but cuda==10.2,when i update the cuda to 11.0,success!

老哥， 修改文件了吗， 还是直接装上的， 我也是win10 torch1.7 cuda11.0， 装不上啊

**Comment by gzchenjiajun** [comment]
@forallsunday 
这个问题你解决了吗

**Comment by a527533557** [comment]
> > my pytorch==1.7 but cuda==10.2,when i update the cuda to 11.0,success!
> 
> 老哥， 修改文件了吗， 还是直接装上的， 我也是win10 torch1.7 cuda11.0， 装不上啊


You'd better check your version of mmcv

**Comment by a527533557** [comment]
> @forallsunday
> 这个问题你解决了吗
> 我也遇到了
> 请问如何解决

The versions of mmcv, python, and CUDA should match
