### ISSUE TITLE
Tensorboard visualization

### ISSUE THREAD

**Issue by ricardborras** [open-mmlab/mmdetection#4123]
Hi, 

iteration number in tensorboard visualization is not correct, it shows values of 1.4k when we are training a custom object detector for 50 iterations

Also, when multiple trains are run without clearing {WORK_DIR}/outputs/tf_logs contents, it shows garbaged curves (see atachment with 2 runs)

Any help on this?

Thanks,

Ricard

![tensorboard_capture](https://user-images.githubusercontent.com/10165293/99272183-ca6e6480-2827-11eb-95ca-303d2da52b79.png)

**Comment by nguyen14ck** [comment]
This is an issue of Tensorboard.  
Just restart Tensorboard, and wait for a moment. It will auto refresh.

**Comment by ricardborras** [comment]
Thanks! Solved
