### ISSUE TITLE
ssd转onnx

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection#4127]
你好，我用了tools/pytorch2onnx.py将ssd转成onnx。结果显示，转换是没有问题的。
![success](https://user-images.githubusercontent.com/39186017/99328980-2c76aa80-28b8-11eb-83c8-cf2b9db46796.png)

但是我用netron看网络结构，发现和ssd的网络结构出入很大。
![ssd_onnx](https://user-images.githubusercontent.com/39186017/99329054-5760fe80-28b8-11eb-9b76-e11103eb6f4e.png)

我想问一下这样子正常不？会不会影响到我后续转ncnn/paddleLite/tflite这样的操作？

**Comment by ZwwWayne** [comment]
Converting SSD to ONNX is not supported in the current version. You can try YOLO v3 instead. We might support SSD in the future.

**Comment by CheungBH** [comment]
> Converting SSD to ONNX is not supported in the current version. You can try YOLO v3 instead. We might support SSD in the future.

Thank you. I also wonder which kind of model is supported for onnx conversion? Only retinanet and Yolov3?

**Comment by RunningLeon** [comment]
Pls. try lastest mmcv and mmdetection for ssd and yolov3 conversion.
