### ISSUE TITLE
cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:750: error: (-215:Assertion failed) !buf.empty() && buf.isContinuous() in function 'cv::imdecode_'

### ISSUE THREAD

**Issue by LoveIsAGame** [open-mmlab/mmdetection#4128]
Yesterday's training was good, the code has not been changed, this problem appeared today.

Who can tell me the possible reason, thank you very much!

**Comment by ZwwWayne** [comment]
You might need to check your data, it seems that the image decoding failed due to some reason. The error is not related to the code but is about the data or IO.

**Comment by happybear1015** [comment]
import cv2
import os

image_folder = 'path_to_your_image_folder'  # 替换为你的图像文件夹路径

for filename in os.listdir(image_folder):
	if filename.endwith("jpg"):
	    image_path = os.path.join(image_folder, filename)
	    image = cv2.imread(image_path)
	
	    if image is None:
	        print(f"Failed to load the image: {filename}")
	    else:
	        pass
