### ISSUE TITLE
multi gpu for yolov4

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#4133]
I run yolo_v4 on 8 GPU, but the code stuck at first batch, don't  continue running.
```
loading with a hack.
2020-11-18 09:45:37,366 - mmdet - INFO - Epoch [1][1/3665]      lr: 1.000e-04, eta: 240 days, 2:40:43, time: 89.849, data_time: 84.795, memory: 4758, loss_cls: 1755.3647, loss_conf: 35100.9453, loss_xy: 88.2475, loss_wh: 21.6808, loss: 36966.2422, grad_norm: 61357.0859
```
my env:
torch1.6 mmcv:1.6

**Comment by RyanXLi** [comment]
Hi! Yolo v4 is currently still a work in progress and we will release a complete version in the near future.

**Comment by meanmee** [comment]
Still not the time of releasing yolov4？

**Comment by ModestYjx** [comment]
> Hi! Yolo v4 is currently still a work in progress and we will release a complete version in the near future.

hello! I am a enthusiastic developer for mmdetection! I want to know when the yolov4 is released because I want to bring these tricks on my project.
Sincerely looking forward to your reply.

**Comment by hongyanghu** [comment]
> 你好！Yolo v4 目前仍在开发中，我们将在不久的将来发布完整版本。
I used the v4 configuration in your resp. After setting ```loss_bbox=dict(type='CIoULoss', loss_weight=2.0, reduction="mean")```, the loss_bbox and ap values are very low and it is difficult to train. What is the reason?
