### ISSUE TITLE
Model is not taking complete data for training

### ISSUE THREAD

**Issue by Atul997** [open-mmlab/mmdetection#4135]
I am training a custom detection model for tables and cells and using the `cascade_maskrcnn_hrnet_w32_20e.py ` config file for model training. I have 875 annotations of images while training it is taking only 438 images. Why is it happening?
Any help or suggestions would be helpful!

**Comment by v-qjqs** [comment]
Hi @Atul997, I guess it's normal since you set your batch_size=2?
