### ISSUE TITLE
About DCN in resnet backbone

### ISSUE THREAD

**Issue by tianxinhang** [open-mmlab/mmdetection#4136]
Does resnet backbone support DCN ?
![image](https://user-images.githubusercontent.com/54171139/99497743-4d6ef680-29b1-11eb-84c6-f5bb2450b03c.png)

**Comment by v-qjqs** [comment]
Hi @tianxinhang, mmdet supports DCN in resnet backbone and there exists official config example, like [this](https://github.com/open-mmlab/mmdetection/blob/master/configs/dcn/faster_rcnn_r50_fpn_dconv_c3-c5_1x_coco.py#L4).
