### ISSUE TITLE
ResNet frozen problem?

### ISSUE THREAD

**Issue by SnailForce** [open-mmlab/mmdetection#4137]
model = dict(
	type='FasterRCNN',                         # model类型
    pretrained='modelzoo://resnet50',          # 预训练模型：imagenet-resnet50
    backbone=dict(
        type='ResNet',                         # backbone类型
        depth=50,                              # 网络层数
        num_stages=4,                          # resnet的stage数量
        out_indices=(0, 1, 2, 3),              # 输出的stage的序号
        frozen_stages=1,                       # 冻结的stage数量，即该stage不更新参数，-1表示所有的stage都更新参数
        style='pytorch'))

请问为什么要冻结stage，看到了好几个config中都选择了冻结

**Comment by v-qjqs** [comment]
Hi @SnailForce, it's a common setting to freeze some stages (e.g. the stem and the first stage) of resnet backbone for COCO training.
