### ISSUE TITLE
pycharm debug error

### ISSUE THREAD

**Issue by Majiawei** [open-mmlab/mmdetection#4138]
How do I use pycharm  to debug when training?
When I debugged, pycharm had no data to display
![image](https://user-images.githubusercontent.com/20382521/99516229-e52c0f00-29c8-11eb-8d44-0c3db23f4e39.png)

**Comment by v-qjqs** [comment]
Hi @Majiawei, I'm sorry I can't give you some useful suggestions, but will you directly print the data information?
