### ISSUE TITLE
compile.sh error

### ISSUE THREAD

**Issue by abing222** [open-mmlab/mmdetection#414]
Building roi align op...
running build_ext
building 'roi_align_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/abing/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_align_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/roi_align_kernel.cu -o build/temp.linux-x86_64-3.6/src/roi_align_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /home/abing/anaconda3/compiler_compat -L/home/abing/anaconda3/lib -Wl,-rpath=/home/abing/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/src/roi_align_cuda.o build/temp.linux-x86_64-3.6/src/roi_align_kernel.o -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.6/roi_align_cuda.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/roi_align_cuda.cpython-36m-x86_64-linux-gnu.so -> 
Building roi pool op...
running build_ext
building 'roi_pool_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/abing/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/roi_pool_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_pool_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/roi_pool_kernel.cu -o build/temp.linux-x86_64-3.6/src/roi_pool_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /home/abing/anaconda3/compiler_compat -L/home/abing/anaconda3/lib -Wl,-rpath=/home/abing/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/src/roi_pool_cuda.o build/temp.linux-x86_64-3.6/src/roi_pool_kernel.o -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.6/roi_pool_cuda.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/roi_pool_cuda.cpython-36m-x86_64-linux-gnu.so -> 
Building nms op...
rm -f *.so
echo "Compiling nms kernels..."
Compiling nms kernels...
python setup.py build_ext --inplace
running build_ext
building 'cpu_nms' extension
gcc -pthread -B /home/abing/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/abing/anaconda3/include/python3.6m -c cpu_nms.cpp -o build/temp.linux-x86_64-3.6/cpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_nms.cpp:611:
/home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -B /home/abing/anaconda3/compiler_compat -L/home/abing/anaconda3/lib -Wl,-rpath=/home/abing/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu_nms.o -o /home/abing/project/mmdetection/mmdet/ops/nms/cpu_nms.cpython-36m-x86_64-linux-gnu.so
building 'cpu_soft_nms' extension
gcc -pthread -B /home/abing/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/abing/anaconda3/include/python3.6m -c cpu_soft_nms.cpp -o build/temp.linux-x86_64-3.6/cpu_soft_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cpu_soft_nms.cpp:611:
/home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
cpu_soft_nms.cpp: In function ‘PyObject* __pyx_pf_12cpu_soft_nms_cpu_soft_nms(PyObject*, PyArrayObject*, float, unsigned int, float, float)’:
cpu_soft_nms.cpp:2435:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
cpu_soft_nms.cpp:2946:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_11 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
g++ -pthread -shared -B /home/abing/anaconda3/compiler_compat -L/home/abing/anaconda3/lib -Wl,-rpath=/home/abing/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu_soft_nms.o -o /home/abing/project/mmdetection/mmdet/ops/nms/cpu_soft_nms.cpython-36m-x86_64-linux-gnu.so
building 'gpu_nms' extension
gcc -pthread -B /home/abing/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/abing/anaconda3/include/python3.6m -c gpu_nms.cpp -o build/temp.linux-x86_64-3.6/gpu_nms.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_nms.cpp:613:
/home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
nvcc -I/home/abing/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/abing/anaconda3/include/python3.6m -c nms_kernel.cu -o build/temp.linux-x86_64-3.6/nms_kernel.o -c --compiler-options -fPIC
g++ -pthread -shared -B /home/abing/anaconda3/compiler_compat -L/home/abing/anaconda3/lib -Wl,-rpath=/home/abing/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/gpu_nms.o build/temp.linux-x86_64-3.6/nms_kernel.o -o /home/abing/project/mmdetection/mmdet/ops/nms/gpu_nms.cpython-36m-x86_64-linux-gnu.so
Building dcn...
running build_ext
building 'deform_conv_cuda' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
gcc -pthread -B /home/abing/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/deform_conv_cuda.cpp -o build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/deform_conv_cuda_kernel.cu -o build/temp.linux-x86_64-3.6/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /home/abing/anaconda3/compiler_compat -L/home/abing/anaconda3/lib -Wl,-rpath=/home/abing/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o build/temp.linux-x86_64-3.6/src/deform_conv_cuda_kernel.o -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.6/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so
building 'deform_pool_cuda' extension
gcc -pthread -B /home/abing/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/deform_pool_cuda.cpp -o build/temp.linux-x86_64-3.6/src/deform_pool_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/abing/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/home/abing/anaconda3/include/python3.6m -c src/deform_pool_cuda_kernel.cu -o build/temp.linux-x86_64-3.6/src/deform_pool_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
g++ -pthread -shared -B /home/abing/anaconda3/compiler_compat -L/home/abing/anaconda3/lib -Wl,-rpath=/home/abing/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/src/deform_pool_cuda.o build/temp.linux-x86_64-3.6/src/deform_pool_cuda_kernel.o -L/usr/local/cuda-9.0/lib64 -lcudart -o build/lib.linux-x86_64-3.6/deform_pool_cuda.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so -> 
copying build/lib.linux-x86_64-3.6/deform_pool_cuda.cpython-36m-x86_64-linux-gnu.so ->

**Comment by abing222** [comment]
ubuntu16.04,cuda9.0,numpy1.13.3,torch1.0.1,

**Comment by abing222** [comment]
when I print "python tools/train.py configs/faster_rcnn_r50_fpn_1x_voc0712.py"
Traceback (most recent call last):
  File "tools/train.py", line 7, in <module>
    from mmdet.datasets import get_dataset
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformRoIPooling, DeformRoIPoolingPack,
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+85c30cc-py3.6.egg/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'

**Comment by hellock** [comment]
There is no compiling error according to your log. Possible reasons:
- There are multiple python or pytorch versions and different ones are used for compiling and running.
- You did not run the install command after compiling.

**Comment by abing222** [comment]
But when I test the program, it's normal.

import mmcv
from mmcv.runner import load_checkpoint
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result

cfg = mmcv.Config.fromfile('configs/faster_rcnn_r50_fpn_1x.py')
cfg.model.pretrained = None
model = build_detector(cfg.model, test_cfg=cfg.test_cfg)

_ = load_checkpoint(model, 'faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')

img = mmcv.imread('test.jpg')
result = inference_detector(model, img, cfg)
show_result(img, result)

**Comment by hellock** [comment]
That's most possible if you have multiple python versions.

**Comment by abing222** [comment]
Thank you for your help,but I find Non-distributed training could not print val-loss and val-acc. Is there any way to export it? And when using tensorboard output format, the terminal does not output information.
