### ISSUE TITLE
I got import errors when using mmdetection

### ISSUE THREAD

**Issue by Li-Yun** [open-mmlab/mmdetection#4141]
Hello,

I tried to use the mmdetection package (mmdet 2.6.0) to run pedestrian detection, but I got multiple import errors:
1. ImportError: cannot import name 'init_dist' from 'mmdet.apis'
2. ImportError: cannot import name 'results2json' from 'mmdet.core'
3. ImportError: cannot import name 'coco_eval' from 'mmdet.core'

How can I solve these errors? Thanks.

**Comment by xvjiarui** [comment]
Hi @Li-Yun 
Have you installed mmdet? 
I suggest following the installation guide step by step.

**Comment by Li-Yun** [comment]
@xvjiarui Thank you for replying to my message. I installed the newest version of mmdetection, and it seems everything is fine. Thank you for your help.
