### ISSUE TITLE
strange lr and loss curve

### ISSUE THREAD

**Issue by Chen823** [open-mmlab/mmdetection#4142]
<img width="279" alt="loss" src="https://user-images.githubusercontent.com/44660655/99617358-2c161500-2a5a-11eb-8fdf-c634d07e03f7.png">
<img width="261" alt="lr" src="https://user-images.githubusercontent.com/44660655/99617364-30423280-2a5a-11eb-82ec-19af08ce030e.png">

**Comment by xvjiarui** [comment]
Hi @Chen823 
You may install the latest MMCV to see if the bug still exists.
