### ISSUE TITLE
 two errors

### ISSUE THREAD

**Issue by Lixia1221** [open-mmlab/mmdetection#4150]
(open-mmlab) fsr@serverA2:~/FoveaBox$ python tools/test.py "/home/fsr/FoveaBox/configs/foveabox/fovea_r50_fpn_4gpu_2x.py" "/home/fsr/FoveaBox/checkpoints/fovea_r50_fpn_4x4_2x_coco_20200203-2df792b1.pth" --out "/home/fsr/FoveaBox/results.pkl/"
Traceback (most recent call last):
  File "tools/test.py", line 224, in <module>
    main()
  File "tools/test.py", line 140, in main
    raise ValueError('The output file must be a pkl file.')
ValueError: The output file must be a pkl file.

(open-mmlab) fsr@serverA2:~/FoveaBox$ python tools/analyze_logs.py plot_curve log.json --keys loss_cls loss_reg --out losses.pdf
Traceback (most recent call last):
  File "tools/analyze_logs.py", line 178, in <module>
    main()
  File "tools/analyze_logs.py", line 172, in main
    log_dicts = load_json_logs(json_logs)
  File "tools/analyze_logs.py", line 154, in load_json_logs
    with open(json_log, 'r') as log_file:
FileNotFoundError: [Errno 2] No such file or directory: 'log.json'

i meet those errors. what should i do ?

**Comment by LMerCy** [comment]
@Lixia1221 
1. out file should be "/home/fsr/FoveaBox/results.pkl", not "/home/fsr/FoveaBox/results.pkl/".
2. it seems there is no log.json file, you may provide the right path.
