### ISSUE TITLE
Batch Inference

### ISSUE THREAD

**Issue by yldrmBtn** [open-mmlab/mmdetection#4151]
Is there support for batch inference ? I look old issues but did not find any satisfactory answer.

**Comment by dongyangcai** [comment]
hi, i meet same question? did you solve it?

**Comment by yldrmBtn** [comment]
I was using a very old mmdetection version and problem is solved for me when I pull latest version. When you change samples_per_gpu in test data loader, there should not be any problem and you will do batch inference.

**Comment by SeaRealE** [comment]
> I was using a very old mmdetection version and problem is solved for me when I pull latest version. When you change samples_per_gpu in test data loader, there should not be any problem and you will do batch inference.

hi @yldrmBtn, I have a question. you mean if I only modify `samples_per_gpu` in test data loader of a config file, it works?
Is there any additional option when running `test.py`?
