### ISSUE TITLE
PAA reassign bug

### ISSUE THREAD

**Issue by HAOCHENYE** [open-mmlab/mmdetection#4152]
ValueError: Fitting the mixture model failed because some components have ill-defined empirical covariance (for instance caused by singleton or collapsed samples). Try to decrease the number of components, or increase reg_covar.

This error occured in PAA reassign, gmm.fit(). I only changed the shared head to detect head to private head.

It seems that it could happen very  occasionally。

**Comment by Johnson-Wang** [comment]
This could be due to the unstable behavior of `covariance_type='diag'` . You may try to use `covariance_type='full'` in `PAAHead` instead.
