### ISSUE TITLE
Are COCO RLE Encoded datasets supported for training?

### ISSUE THREAD

**Issue by zachbellay** [open-mmlab/mmdetection#4154]
I have a dataset that is encoded using COCO mask RLE as opposed to polygons. 

In my `coco.json` my RLE encoded label looks like this:

```json
        {
            "id": 1726,
            "image_id": 12,
            "segmentation": {
                "size": [
                    1944,
                    2592
                ],
                "counts": "ei^Z26[l18K8J4N2M3L4M3M1O1N200dTNhNYk1[10N3O0010O101N100O01O001O0:F3M0000000O1000O100O1O100N2N200N2N110N2N2N2N2O1O001O001N200O1000N11O1O1O010O0100O2O003L2O2N1O1N2O2N0O3N1O1O1N101N100O101N100O1O10000O2O1N100O2N1O2O0N200O2N2O0O100N2O1O1O1O100O1000O0100N110002hMQVNb1dj1O0O2N1O1O1N2O101N1O2N2N101N1O10000O010O10000O2O1N2N101N2N1O2N3M3L3O1M4L4L_SlU2"
            },
            "category_id": 1,
            "iscrowd": 0
        }
```

whereas a polygon would look like this: 

```json
{
            "segmentation": [
                [
                    2084,
                    1221,
                    2084,
                    1198,
                    2086,
                    1189,
                    2084,
                    1165,
                    2093,
                    1149,
                    2100,
                    1140,
                    2071,
                    1135,
                    2059,
                    1126,
                    2035,
                    1110,
                    2012,
                    1112,
                    1991,
                    1112,
                    1969,
                    1122,
                    1949,
                    1145,
                    1945,
                    1189,
                    1949,
                    1218,
                    1969,
                    1234,
                    2000,
                    1236,
                    2035,
                    1230,
                    2063,
                    1263,
                    2076,
                    1228
                ]
            ],
            "area": 23715,
            "bbox": [
                1945,
                1110,
                155,
                153
            ],
            "iscrowd": 0,
            "id": 2814,
            "image_id": 31,
            "category_id": 1
        }
```

I have been having difficulty getting the RLE play nice with mmdetection so I am wondering whether mmdetection currently supports this style of COCO formatted data. If so I will continue to debug my app, otherwise I will probably revert to polygons.

**Comment by zachbellay** [comment]
I was able to get my training to work by converting my masks into a list of multiple polygons, however, it would be nice to know if this functionality is not supported just for the future. Thank you.

**Comment by xvjiarui** [comment]
Hi @zachbellay 
If your format is the same as COCO, it should be fine.

**Comment by marek-mottmac** [comment]
use poly2mask=True
`dict(type='LoadAnnotations', with_bbox=True, with_mask=True, poly2mask=True),`

**Comment by kaixin-bai** [comment]
> Hi @zachbellay If your format is the same as COCO, it should be fine.

Although coco format support rle, mmdetection still has problem with training for COCO dataset with rle annotation, from 2022.11.02.

**Comment by jerpint** [comment]
I am also having issues, I opened a discussion here: https://github.com/open-mmlab/mmdetection/discussions/9290

**Comment by Victtttttt** [comment]
> 嗨，如果您的格式与 COCO 相同，应该没问题。

Please explain the details to solve the problem  when I use RLE(ps:setting with_bbox=True, with_mask=True, and poly2mask=True 
iscrowd=1 doesn't work,Loss_box Loss_mask is still equal to 0).

**Comment by ruinianxu** [comment]
@Victtttttt Hi, did you figure it out? Really appreciate if you could tell me know if you made it work.
