### ISSUE TITLE
Can mmdet load 3D files?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#4156]
Can mmdet load 3D images and label(or mask) files such as *.nii or *.pickle?
 If can't,   how can I make it to load those files?
 (I will use the 3D_conv backbone)
 Thank you very much!

**Comment by zhongqiu1245** [comment]
I am looking forward to your reply

**Comment by xvjiarui** [comment]
Hi @zhongqiu1245 
You may check [MMDet3D](https://github.com/open-mmlab/mmdet3d).
