### ISSUE TITLE
rebuilt parameter indices size is not same as original model parameters size.177 versus 169389

### ISSUE THREAD

**Issue by GreysonPhoenix** [open-mmlab/mmdetection#4157]
This message popped up, during my training ATSS. The case never happened to me when I use version 1.0, so I guess it's a bug?
RuntimeError: replicas_[0].size() == rebuilt_param_indices_.size() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1603729138878/work/torch/csrc/distributed/c10d/reducer.cpp":1326, please report a bug to PyTorch. rebuilt parameter indices size is not same as original model parameters size.177 versus 169389

**Comment by Kyuuki93** [comment]
@GreysonPhoenix Did you solved this problem? I meet the same issue
