### ISSUE TITLE
error when calculate AP

### ISSUE THREAD

**Issue by Asperger12345** [open-mmlab/mmdetection#4158]
Hi,when I use tools/robustness_eval.py calculate AP ,there is an error.

I use it in this way:
`python tools/robustness_eval.py ./result10.pkl --dataset voc --metric AP`

and the error message:
```
Traceback (most recent call last):
  File "tools/robustness_eval.py", line 250, in <module>
    main()
  File "tools/robustness_eval.py", line 246, in main
    aggregate=args.aggregate)
  File "tools/robustness_eval.py", line 178, in get_results
    filename, prints=prints, aggregate=aggregate)
  File "tools/robustness_eval.py", line 124, in get_voc_style_results
    num_distortions = len(list(eval_output.keys()))
AttributeError: 'list' object has no attribute 'keys'
```

Thank you very much!

@anurag1paul @hachreak @DXist @ramkakarala @tjsongzw @

**Comment by Epiphqny** [comment]
same question

**Comment by TuanNguyenSKKU** [comment]
I have encountered the same issue.

**Comment by xuhuasheng** [comment]
same issue. how to fix it?

**Comment by calvin886** [comment]
> Hi,when I use tools/robustness_eval.py calculate AP ,there is an error.
> 
> I use it in this way:
> `python tools/robustness_eval.py ./result10.pkl --dataset voc --metric AP`
> 
> and the error message:
> 
> ```
> Traceback (most recent call last):
>   File "tools/robustness_eval.py", line 250, in <module>
>     main()
>   File "tools/robustness_eval.py", line 246, in main
>     aggregate=args.aggregate)
>   File "tools/robustness_eval.py", line 178, in get_results
>     filename, prints=prints, aggregate=aggregate)
>   File "tools/robustness_eval.py", line 124, in get_voc_style_results
>     num_distortions = len(list(eval_output.keys()))
> AttributeError: 'list' object has no attribute 'keys'
> ```
> 
> Thank you very much!
> 
> @anurag1paul @hachreak @DXist @ramkakarala @tjsongzw @

same question! how to solve it ?
