### ISSUE TITLE
Why did the acc reach 96% at the beginning of training

### ISSUE THREAD

**Issue by wangning7149** [open-mmlab/mmdetection#4159]
When I train fasterrcnn，Why did the acc reach 96% at the beginning of training？

**Comment by xvjiarui** [comment]
Hi @wangning7149 
Which config are you running?

**Comment by wangning7149** [comment]
> Hi @wangning7149
> Which config are you running?

configs/faster-rcnn/faster_rcnn_r50_fpn_1x_coco.py

**Comment by hellock** [comment]
acc is only a reference number. Even if you have a prediction of all zeros, acc will be high since most samples are negative ones.
