### ISSUE TITLE
测试时对单张图片处理的函数

### ISSUE THREAD

**Issue by FibonacciZ** [open-mmlab/mmdetection#4162]
如何将一张图片按照config里的pipelines对图像进行预处理，应该调用什么函数。

**Comment by xvjiarui** [comment]
Hi @FibonacciZ 
Please use English or English/Chinese for issue.

You may create a dataset with config and get the processed images by iterating the dataset.

**Comment by FibonacciZ** [comment]
Can it be implemented only through function calls?
Because I want to get the feature map of a certain layer when an image is input.
