### ISSUE TITLE
RuntimeError: nms is not compiled with GPU support (cuda11)

### ISSUE THREAD

**Issue by codefabulous** [open-mmlab/mmdetection#4165]
Hi, I installed python3.7, torch 1.7.0+cu110 and mmcv-full 1.2.0 on cuda11 with Gpu(RTX 6000). However, when I ran the verification code after installation, the error occurred.

The verification code is:
from mmdet.apis import init_detector, inference_detector
config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
device = 'cuda:0'
model = init_detector(config_file, device=device)
inference_detector(model, 'demo/demo.jpg')

The error log is:
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    inference_detector(model, 'demo/demo.jpg')
  File "/home/user11/fireDetection/mmdetection/mmdet/apis/inference.py", line 119, in inference_detector
    result = model(return_loss=False, rescale=True, **data)[0]
  File "/home/user11/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user11/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/user11/fireDetection/mmdetection/mmdet/models/detectors/base.py", line 170, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/user11/fireDetection/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/user11/fireDetection/mmdetection/mmdet/models/detectors/two_stage.py", line 194, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/home/user11/fireDetection/mmdetection/mmdet/models/dense_heads/rpn_test_mixin.py", line 36, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/user11/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/user11/fireDetection/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 571, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/user11/fireDetection/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 167, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/home/user11/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 259, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/user11/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/user11/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 113, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home/user11/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 18, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: nms is not compiled with GPU support

Thank you for your help.

**Comment by yuliwu** [comment]
Reinstalling pytorch 1.6 and cuda 10.2 solved my errors.

**Comment by Hitec-at** [comment]
Hi guys, I also met a similar problem yesterday when I finished installation procedures and tried the verification code in get_started.md and got this

> RuntimeError: nms is not compiled with GPU support

So it seems like mmdet has not yet support cuda11? That wiil be so sad for me, since GPU server in my lab just switched from 1080ti to RTX 3080 and from [here](https://forums.developer.nvidia.com/t/can-rtx-3080-support-cuda-10-1/155849/4) I learned that RTX 3080 cannot rollback to cuda10 or early version. I guess we have to wait for the new release with cuda11 support :(

**Comment by Hitec-at** [comment]
> Hi guys, I also met a similar problem yesterday when I finished installation procedures and tried the verification code in get_started.md and got this
> 
> > RuntimeError: nms is not compiled with GPU support
> 
> So it seems like mmdet has not yet support cuda11? That wiil be so sad for me, since GPU server in my lab just switched from 1080ti to RTX 3080 and from [here](https://forums.developer.nvidia.com/t/can-rtx-3080-support-cuda-10-1/155849/4) I learned that RTX 3080 cannot rollback to cuda10 or early version. I guess we have to wait for the new release with cuda11 support :(

Hi I'm here to say I've just solved this problem by following [this link](https://github.com/open-mmlab/mmdetection/pull/4176). Make it short just reinstall mmcv&mmdet after successfully installing pytorch1.7 and torchvision0.8.1 with cuda11 support. Namely, change following steps:

> git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
MMCV_WITH_OPS=1 pip install -e .  # package mmcv-full will be installed after this step
cd ..

> git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"

into:

> git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e .  # package mmcv-full will be installed after this step
cd ..

> git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e .  # or "python setup.py develop"
After redoing these steps I test verification code and the error info doesn't show up

**Comment by xiaowanzizz** [comment]
oh my god
thank you!!!!!merry christmas!!!!!!@ Hitec-at

**Comment by ZwwWayne** [comment]
FAQ about this issue is updated [here](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment).

**Comment by yuquant** [comment]
> > Hi guys, I also met a similar problem yesterday when I finished installation procedures and tried the verification code in get_started.md and got this
> > > RuntimeError: nms is not compiled with GPU support
> > 
> > 
> > So it seems like mmdet has not yet support cuda11? That wiil be so sad for me, since GPU server in my lab just switched from 1080ti to RTX 3080 and from [here](https://forums.developer.nvidia.com/t/can-rtx-3080-support-cuda-10-1/155849/4) I learned that RTX 3080 cannot rollback to cuda10 or early version. I guess we have to wait for the new release with cuda11 support :(
> 
> Hi I'm here to say I've just solved this problem by following [this link](https://github.com/open-mmlab/mmdetection/pull/4176). Make it short just reinstall mmcv&mmdet after successfully installing pytorch1.7 and torchvision0.8.1 with cuda11 support. Namely, change following steps:
> 
> > git clone https://github.com/open-mmlab/mmcv.git
> > cd mmcv
> > MMCV_WITH_OPS=1 pip install -e .  # package mmcv-full will be installed after this step
> > cd ..
> 
> > git clone https://github.com/open-mmlab/mmdetection.git
> > cd mmdetection
> > pip install -r requirements/build.txt
> > pip install -v -e .  # or "python setup.py develop"
> 
> into:
> 
> > git clone https://github.com/open-mmlab/mmcv.git
> > cd mmcv
> > MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e .  # package mmcv-full will be installed after this step
> > cd ..
> 
> > git clone https://github.com/open-mmlab/mmdetection.git
> > cd mmdetection
> > pip install -r requirements/build.txt
> > MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e .  # or "python setup.py develop"
> 
> After redoing these steps I test verification code and the error info doesn't show up

cuda11.2，pytorch1.7.1，python3.9，But it doesn't work

**Comment by adlane98** [comment]
@yuquant I think pytorch 1.7.1 does not support CUDA 11.2 following thin [link](https://pytorch.org/get-started/previous-versions/).

**Comment by superchenyan** [comment]
cuda11.1, pytorch1.8.0, python3.7, it doesnot work
