### ISSUE TITLE
error when modify are_Rng for evaluation

### ISSUE THREAD

**Issue by casiahnu** [open-mmlab/mmdetection#4166]
Hello!
I train my own dataset using mmdetection, The resolution of all the dataset is 512*512.
When I test the model, I meet something weird.

When I  set the areaRng in the cocoeval.py as follows:
   self.areaRng = [[0 ** 2, 511 ** 2], [512 ** 2, 512 ** 2], [513 ** 2, 513 ** 2], [513 ** 2, 1e5 ** 2]]
     self.areaRngLbl = ['all', 'small', 'medium', 'large']

Then I run 
CUDA_VISIBLE_DEVICES=6 python3 ./tools/test.py ./configs/fsaf/fsaf_r101_fpn_1x_coco.py  ./work_dirs/fsaf_r101_fpn_1x_coco/epoch_200.pth --out ./result/result.pkl --eval bbox

 I will get 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.374
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.375
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

It can be seen that only [512^2,512^2] will get a result when running test.py,

However, Judging from the test results of the images, the bbox of various resolutions can be detected. 
Could you please give me some guidance？ Thank you!

**Comment by ZwwWayne** [comment]
This might because those other areas do not have related ground truth boxes?
