### ISSUE TITLE
strange in datasets/coco.py

### ISSUE THREAD

**Issue by bladesaber** [open-mmlab/mmdetection#4167]
hello, I am not sure the what I meet is a bug or an unsafe operation.

the situation reproduce:
`from pycocotools.coco import COCO`
`co4 = COCO('test.json')  # coco sample dataset from here:`[test.zip](https://github.com/open-mmlab/mmdetection/files/5588163/test.zip)

`print(co4.cats)` 
`# output: {1: {'id': 1, 'name': 'pallet1', 'supercategory': ''}, 0: {'id': 0, 'name': 'pallet1_support', 'supercategory': ''}}`

`print(co4.get_cat_ids(('pallet1_support', 'pallet1')))`
` # output:[1, 0]`

the second output is wrong and should be [0, 1]. I meet this problem when I use mmdet/datasets/coco.py in function load_annotations(), `self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)` . And it cause the structure of network result not correct.

So I check source code of get_cat_ids in mmpycocotools and find the source code below:
`def get_cat_ids(self, cat_names=[], sup_names=[], cat_ids=[]):` 
      `return self.getCatIds(cat_names, sup_names, cat_ids)`

`def getCatIds(self, catNms=[], supNms=[], catIds=[]):`
`...`
`cats = self.dataset['categories']`
`cats = cats if len(catNms) == 0 else [cat for cat in cats if cat['name'] in catNms]`
`ids = [cat['id'] for cat in cats]`
`return ids`

it seem that the sequence depended by the cats not by catNums.
at last, I change the code in my mmdet/datasets/coco.py
`self.cat_ids = []`
`for class_name in self.CLASSES:`
`class_id = self.coco.getCatIds([class_name])[0]`
`self.cat_ids.append(class_id)`

**Comment by ZwwWayne** [comment]
Please @xvjiarui have a check on the mmpycocotools.

**Comment by xvjiarui** [comment]
Hi @bladesaber 
It is the desired behavior of the original pycocotools.
