### ISSUE TITLE
你好，训了很多模型   如果一共12epoch，则会在第8/9/10个epcoh的时候,val

### ISSUE THREAD

**Issue by henbucuoshanghai** [open-mmlab/mmdetection#4168]

**Comment by henbucuoshanghai** [comment]
如果一共12epoch，则会在第8/9/10个epcoh的时候,val上的map最好   后面会降低1个点 左右
 请问怎么回事呢？
那此时可以用最好的结果 当做最终结果？

**Comment by ZwwWayne** [comment]
You should use the model with the best mAP. This sometimes means that the dataset is a little bit small and the model starts overfitting.

**Comment by henbucuoshanghai** [comment]
确定吗？直接第9个epoch的时候  直接当最终结果?


overfit?   那frcnn训练pascal voc。。。过拟合，。。  不解决一下？
