### ISSUE TITLE
How to add plugins in some ResBlock, but not all the blocks in one stage

### ISSUE THREAD

**Issue by Wyman-yang** [open-mmlab/mmdetection#4169]
I want to add some plugins (GCBlock, Non-local ) in the third block of stage two, but the cfg only provide  stage apis.                    stages=(False, True, False, False)

**Comment by ZwwWayne** [comment]
Hi @Wyman-yang ,
MMDetection does not provide such a fine-grained control of those blocks but follows the implementation/recommendation in the original papers. If you want to tune those hyper-parameters, you may need to modify the code.

**Comment by Wyman-yang** [comment]
> Hi @Wyman-yang ,
> MMDetection does not provide such a fine-grained control of those blocks but follows the implementation/recommendation in the original papers. If you want to tune those hyper-parameters, you may need to modify the code.

Thank you so much for your reply~
