### ISSUE TITLE
Training stagnates at the beginning? It happens randomly

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#417]
At the start of training, it gets stuck. I don't know whether it's because of data loader or other situations.
![image](https://user-images.githubusercontent.com/15847405/54579358-15761a00-4a3e-11e9-9a2c-439e185086e6.png)
GPU mem didn't rise. It just gets stuck here.
![image](https://user-images.githubusercontent.com/15847405/54579694-9f72b280-4a3f-11e9-88cc-b12f0f69edd8.png)

**Comment by xieqingxing** [comment]
I also encounter this problem,Have you solved it?

**Comment by Luodian** [comment]
use `python3 tools/train.py [config]` will help.

> I also encounter this problem,Have you solved it?

Are u using coco or other datasets?

**Comment by zhubinQAQ** [comment]
> use `python3 tools/train.py [config]` will help.
> 
> > I also encounter this problem,Have you solved it?
> 
> Are u using coco or other datasets?

it occurs only when I use multi GPUs, do you have the same problem?

**Comment by roger1993** [comment]
meet the same problem

**Comment by Kaeseknacker** [comment]
I have the same problem. Usually one data loader gets stuck so that the training process cannot start.

**Comment by hhaAndroid** [comment]
Has it been resolved?
