### ISSUE TITLE
How to update model  from 1.x to 2.x

### ISSUE THREAD

**Issue by G-Naughty** [open-mmlab/mmdetection#4171]
Recently, I am running a model based on mmdetection1.x,  However, now my new computer only support mmdetection2.x ,how can I update the code to fit mmdetection2.x

**Comment by v-qjqs** [comment]
Hi @G-Naughty, we have guidelines for updating model from 1.x to 2.x, see [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md).
