### ISSUE TITLE
Why the tensorboard scalars figure like that?

### ISSUE THREAD

**Issue by ziippy** [open-mmlab/mmdetection#4177]
I want to using the tensorboard for check the model's training status.

so, I edited the log_config in config file like that.
`log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])`

and using the tensorboard command like that
"tensorboard --port=6007 --logdir=tf_logs"

but, the tensorboard scalars figure something wrong...
![image](https://user-images.githubusercontent.com/19854237/100183133-8e22be80-2f21-11eb-8b4f-2adbde260643.png)
![image](https://user-images.githubusercontent.com/19854237/100183191-a98dc980-2f21-11eb-83d5-969a2a95250a.png)

but the bbox_mAP is ok.
![image](https://user-images.githubusercontent.com/19854237/100183224-bb6f6c80-2f21-11eb-8d6f-a187d36c349f.png)

I think, maybe the acc and loss using the looped step value.
0 ~ 28.35 steps
0 ~ 28.35 steps
...

But, I want to see the log with the increased step
How can I fix that?

Appendix
my config file is like that
[default_runtime_1.txt](https://github.com/open-mmlab/mmdetection/files/5594490/default_runtime_1.txt)

**Comment by v-qjqs** [comment]
Hi @ziippy, I guess the saved log for tensorboard has multiple experiments records.

**Comment by ziippy** [comment]
> Hi @ziippy, I guess the saved log for tensorboard has multiple experiment records.

No. It was first experiment. not multiple.

**Comment by ZwwWayne** [comment]
This might because that the tf_logs directory contains multiple logs.

**Comment by deepakksingh** [comment]
In the tensorboard dashboard, you can click on RELATIVE/WALL-TIME to change the x-axis
