### ISSUE TITLE
How can I set the number of GPU when the configs have default requirement on it?

### ISSUE THREAD

**Issue by lmomoy** [open-mmlab/mmdetection#4179]
Such as cornernet and FCOS, they have default number of GPU. But when I want to use single GPU to train them, I don't know how I can set it.

**Comment by v-qjqs** [comment]
Hi, [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py#L88) is an example of FCOS. You may set 'samples_per_gpu'=1 for single GPU training.
