### ISSUE TITLE
Resnest BN batchsize =1 error

### ISSUE THREAD

**Issue by XcodeHw** [open-mmlab/mmdetection#4180]
when i use backbone resnest,i set BN and Batchsize =1 ,error,ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64, 1, 1])
,when i set bachsize =2 it can train

**Comment by zehuichen123** [comment]
@XcodeHw, since there is GAP in ResNeSt and BN doesn't allow 1 size value input when training. You may refer the code to torch.nn.functional.batch_norm(maybe this structure).
