### ISSUE TITLE
Invalid link in readme of cityscape

### ISSUE THREAD

**Issue by luzai** [open-mmlab/mmdetection#4181]
Hi, Thank you very much for the amazing project! 

I would like to report that the [model](http://download.openmmlab.com/mmdetection/v2.0/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes_20200502-6ea77f0e.pth) in the [readme](https://github.com/open-mmlab/mmdetection/blob/master/configs/cityscapes/README.md) in the cityscape is invalid. 

Meanwhile, may I ask whether there are more pre-trained models on Cityscape? I would like to evaluate the models elaborately. 

Thank you!

**Comment by v-qjqs** [comment]
Hi @luzai, thanks for your comments, and we will fix it soon.
