### ISSUE TITLE
Modify input channels of model

### ISSUE THREAD

**Issue by GiangHLe** [open-mmlab/mmdetection#4182]
Hi, 

I want to train a model with 6 channels input, I success in create a custom pipeline as issue #1861. But I have no idea how to modify the first layer. I want to modify input channel of model same as #3820 

My config: htc_r50_rfp_1x_coco.py

I tried to modify: 

- In `mmdet/core/models/backbones/detectors_resnet.py` line 223, change all Bottleneck in channel is 6.

- In `mmdet/apis/train.py` line 150, I add this code:

```python
from mmcv.cnn import ConvAWS2d
from torch import nn as nn
add_layer = ConvAWS2d(6, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
nn.init.xavier_uniform(add_layer.weight)
runner.model.module.backbone.conv1 = add_layer
runner.model.cuda()   
# print(model)
```
When I printed the model to check it, the first layer input channel was changed from 3 to 6.
However, it still returned the bug `RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 6, 224, 1344] to have 3 channels, but got 6 channels instead`. Can you help me solve this problem?

**Comment by GiangHLe** [comment]
I tried to solve by add `input_channels` in configs backbone, but it returns `RuntimeError: Given groups=1, weight of size [64, 6, 7, 7], expected input[1, 3, 224, 1344] to have 6 channels, but got 3 channels instead` even I didn't touch dataset or pipeline.

So I decided to clone the newest version mmdetection, install all things again. This time, it still doesn't work with add `input_channels` in configs file, so I change the model construct inside the backbbone `detectors_resnet.py` and modify the `loading.py`, then it worked.

**Comment by Jossome** [comment]
> by add `input_channels` in configs backbone,

I think it's `in_channels`. I just tested and it worked without having to modify the backbone codes.

**Comment by GiangHLe** [comment]
@Jossome Thank you, maybe you are correct, in my case, I just want to know why the input channels change effect the dataloader as you can see I have 2 different bugs when I added input_channels

> RuntimeError: Given groups=1, weight of size [64, 6, 7, 7], expected input[1, 3, 224, 1344] to have 6 channels, but got 3 channels instead

And comment out it 

> RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 6, 224, 1344] to have 3 channels, but got 6 channels instead

**Comment by MoonDiana17** [comment]
> I tried to solve by add `input_channels` in configs backbone, but it returns `RuntimeError: Given groups=1, weight of size [64, 6, 7, 7], expected input[1, 3, 224, 1344] to have 6 channels, but got 3 channels instead` even I didn't touch dataset or pipeline.
> 
> So I decided to clone the newest version mmdetection, install all things again. This time, it still doesn't work with add `input_channels` in configs file, so I change the model construct inside the backbbone `detectors_resnet.py` and modify the `loading.py`, then it worked.

Hello, may I know how you modified those two files

**Comment by JDPalla** [comment]
I am trying to do same. Please kindly share code or repo if you have any
