### ISSUE TITLE
About forward_plugin in backbone

### ISSUE THREAD

**Issue by zsef123** [open-mmlab/mmdetection#4184]
* on the master branch 

Codes
```
def forward_plugin(self, x, plugin_names):
        out = x
        for name in plugin_names:
            out = getattr(self, name)(x) # this line
        return out
```

In the `out = getattr(self, name)(x)`, is this correct that the parameter of getattr contains the `x` instead of the `out`?

My expected
```
def forward_plugin(self, x, plugin_names):
        out = x
        for name in plugin_names:
            out = getattr(self, name)(out) # this line
        return out
```

As my understading (https://github.com/open-mmlab/mmdetection/pull/2345#discussion_r399821238) , the plugins can be multiple items and these items will be passing on sequential.

Am I misunderstanding ?

<hr>

And about JIT, TorchScript. (https://github.com/open-mmlab/mmdetection/pull/1504)

Raised Error on `torch.jit.script` (torch==1.7.0)
```
RuntimeError: 
getattr's second argument must be a string literal:

out = getattr(self, name)(x)
                  ~~~~~~~~~~~~~~~~~~ <--- HERE
```

Because torchscript aren't support runtime module name checking. 

So current plugins names can't converting to JIT ( same issue on the normalization layers )
 
So how about changing your naming rules to fixed name (like plugins wrap into nn.ModuleList)

**Comment by xvjiarui** [comment]
Hi @zsef123 
Sorry for the late reply. 
You are correct, it is potential a bug. Would you like to create a PR to fix it? 

If we are using fixed name, it won't be compatible with different plugins.
