### ISSUE TITLE
NVIDIA driver too old

### ISSUE THREAD

**Issue by meanmee** [open-mmlab/mmdetection#4187]
![image](https://user-images.githubusercontent.com/8026086/100326249-ad464c80-3004-11eb-91cf-8b24eaa7c80a.png)

torch 1.5.0, Cuda 10.1
Working fine with other projects but this one

**Comment by xvjiarui** [comment]
Hi @meanmee 
You should follow what PyTorch suggested. Your CUDA may not compatible with your driver.

**Comment by meanmee** [comment]
@xvjiarui I see, thanks

**Comment by meanmee** [comment]
![image](https://user-images.githubusercontent.com/8026086/100327640-838e2500-3006-11eb-9217-7ef4ecc3c36c.png)

@xvjiarui Everything is okay with my nvidia driver

**Comment by xvjiarui** [comment]
Have you changed your driver or pytorch before? I suggest you re-installing pytorch to see if it works.

**Comment by meanmee** [comment]
![image](https://user-images.githubusercontent.com/8026086/100328852-f0ee8580-3007-11eb-8cfe-478c84bcd2f2.png)
I dont see why but dame torch 1.4.0 works ...
