### ISSUE TITLE
CUDA Runtime and MMDetection CUDA Compiler are different

### ISSUE THREAD

**Issue by jaebbb** [open-mmlab/mmdetection#4188]
hi
I use CUDA : 10.2 / torch 1.5.0 / torchvision : 0.6.0 / mmcv : 1.1.6 and mmdetection v2.4.0
![image](https://user-images.githubusercontent.com/52495256/100344447-2bfeb200-3024-11eb-8a65-33fa875a3b0f.png)  
I trained well  and CUDA Runtime and MMDetection CUDA Compiler are same before today
![image](https://user-images.githubusercontent.com/52495256/100344088-a1b64e00-3023-11eb-88f7-1dd1c84494dd.png)  
![image](https://user-images.githubusercontent.com/52495256/100344170-bf83b300-3023-11eb-94db-bbdc1810b792.png)  

when I run train today, I meet this error message(RuntimeError: CUDA error: invalid device function) and see CUDA Runtime and MMDetection CUDA Compiler are different

**Comment by xvjiarui** [comment]
Hi @jaebbb 
Sorry for the late reply. 
You may try to switch the CUDA runtime to resolve this.
