### ISSUE TITLE
Explanation of Anchors

### ISSUE THREAD

**Issue by JC-13** [open-mmlab/mmdetection#419]
Is there an explanation for what these parameters represent?
```
octave_base_scale
scales_per_octave
anchor_ratios
anchor_strides
featmap_strides
```
And how can I calculate the best ones for my data? (Which contains lots of very small objects)

**Comment by wangg12** [comment]
Hi @hellock , are there any docs about anchors?

**Comment by bnumaomei** [comment]
@JC-13 @wangg12  hi have you known the representation of the featmap_strides?

**Comment by ZwwWayne** [comment]
Current [doc](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_generator.py#L11) should have explained these.
