### ISSUE TITLE
Could model defined in mmdetection be used in pure pytorch framework?

### ISSUE THREAD

**Issue by LZDSJTU** [open-mmlab/mmdetection#4191]
Hi, recently I want to combine a mmdetection model and a pure pytorch model. I do not want to modify too much code. So I want to ask if I can define the mmdetection model using the config and import the model to the pure pytorch model project. Then use the pytorch style train and eval function to run the combined model.

Thank you very much.

**Comment by yhcao6** [comment]
Can you be more specific, for example, what difficulty you meet?
Almost all models need some c++, cuda operators, so if you want pure PyTorch implementation, maybe you need to implement these op yourself.
