### ISSUE TITLE
How to run batch inference correctly?

### ISSUE THREAD

**Issue by sdtblck** [open-mmlab/mmdetection#4195]
I see that batch inference has been included in a recent release of mmdet, but i can't find any details in the documentation about how to use it?

does inference_detector() support batch inference, or would I have to build my own data pipeline?

**Comment by akhalili** [comment]
The same question, seems the code doesn't support array of images

**Comment by akhalili** [comment]
Anny update on this?

**Comment by ZwwWayne** [comment]
We will update the documentation soon.

**Comment by ZwwWayne** [comment]
Resolved in https://github.com/open-mmlab/mmdetection/pull/4296
