### ISSUE TITLE
Why not add DenseNet into mmdetection model zoo?

### ISSUE THREAD

**Issue by tianxianhao** [open-mmlab/mmdetection#4196]
**Describe the feature**
DenseNet is a very popular CNN, which has been cited in more than 12,000 papers.
**Motivation**
Could you please add DenseNet into backbone models in next version of mmdet?
**Related resources**
Huang G, Liu Z, Van Der Maaten L, et al. Densely connected convolutional networks[C]//Proceedings of the IEEE conference on computer vision and pattern recognition. 2017: 4700-4708.
https://github.com/liuzhuang13/DenseNet

**Comment by ZwwWayne** [comment]
Hi @tianxianhao ,
As DenseNet is not a commonly used backbone in the field of object detection, we may not support DenseNet in near releases. PRs are welcomed.
