### ISSUE TITLE
randomly meet dataloader problem?

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#420]
I can safely train models on COCO or CityScapes, but I will meet dataloader problem when training on Mapillary(another dataset which can be safely trained using detectron).
```
RuntimeError: DataLoader worker (pid 34569) is killed by signal
```

**Comment by OceanPang** [comment]
@Luodian Is your `num_workers` set as 1? You can try to set `num_workers = 0` in first and see what happen. If the problem still exists, please give us more information, and we will explore why this is the case.

**Comment by Luodian** [comment]
> @Luodian Is your `num_workers` set as 1? You can try to set `num_workers = 0` in first and see what happen. If the problem still exists, please give us more information, and we will explore why this is the case.

@OceanPang Ok, I will try it.

**Comment by zishanahmed08** [comment]
@Luodian Where you able to get mapillary running?If so, could you please share the scripts

**Comment by Luodian** [comment]
@zishanahmed08 Sorry it has been really long time, I forgot the details. But you can search my repos, there's the one used to transfer Mapillary style images to COCO.

**Comment by d12306** [comment]
@OceanPang , any ideas on why this happens? thanks
