### ISSUE TITLE
How to load the local pretrained (backbone) file as the pretrained of the backbone in mmdet?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#4202]
Thank you for your amazing job！
I have a small question about mmdet.
I transplanted a backbone of mmcls to mmdet. I want to load the weight file generated by mmcls (without the final fully-connected layer) into the backbone of mmdet as pretrained, and the neck and subsequent structures of mmdet all use default initialization values , How can I load it?
Thank you!

**Comment by zhongqiu1245** [comment]
Could you tell me how to do that? 
Thank you!

**Comment by ZwwWayne** [comment]
You can modify the key `pretrain`, e.g., `pretrain='xxxxxxx.pth'`.

**Comment by zhongqiu1245** [comment]
Thank you! @ZwwWayne

**Comment by koriavinash1** [comment]
Should we still use the prefix=mmcls://+<path2ckpt>

as mmcls weights key starts with 'backbone.'
