### ISSUE TITLE
Error when converting RetinaNet to ONNX

### ISSUE THREAD

**Issue by Hussni-V** [open-mmlab/mmdetection#4203]
Hello, 
I am trying to convert RetinaNet to ONNX. 

I am using the RetinaNet with resnet50 config as provided from the config folder. 
The only change I made was, the annotation json, class_names and image directory as I am using a custom coco dataset.

Once trained, I tried to convert it with my checkpoint and is given this error
```
RuntimeError: Exporting the operator argsort to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

The confusing thing is, if I try to export it with the checkpoint you provided, it will succeed with the same config file 
```
this will not work - latest.pth is the checkpoint saved after training is done
 
python ./mmdetection/tools/pytorch2onnx.py ./work_dirs/my_config.py  ./work_dirs/latest.pth
------------------------------------------------------------------------------------------------------------------------------------------
this works - this checkpoint is downloaded from mmdet/configs/retinanet

python ./mmdetection/tools/pytorch2onnx.py ./work_dirs/my_config.py  ./work_dirs/retinanet_r50_fpn_2x_coco_20200131-fdb43119.pth
```

I don't understand this part, since both have the same configs meaning the model structure should be the same, however, one is failing to export while the other isn't. The only difference is the checkpoints

I am stuck here, any help is appreciated.

**Comment by ZwwWayne** [comment]
Please @RunningLeon have a look.

**Comment by Hussni-V** [comment]
I am still having this error, If you would like I could send the checkpoints and config for you to test

**Comment by RunningLeon** [comment]
@Hussni-V Hi, as the error suggested, the op `argsort` is not supported to be exported to ONNX. Pls. provide your custom config file if possible. Take a look at [here](https://github.com/open-mmlab/mmcv/blob/eaf25af6c4ca18d7f3c74c3849989e517168d9a8/mmcv/ops/nms.py#L258) while exporting. 
For now you could set a large `split_thr` to make sure it only goes to `if` branch while tracing.

**Comment by Hussni-V** [comment]
https://drive.google.com/drive/folders/19y9HHl_0BJ-BCo4kBPZS_gKNtSA4_QkZ?usp=sharing

the checkpoints are here in this link, I provided a sample image to run with my checkpoint.

**Comment by Hussni-V** [comment]
Setting the split_thr higher as a workaround works for now

**Comment by aleksei-kashapov** [comment]
I have the same problem with retinanet. @ZwwWayne Could you provide the changes in the config file to utilizes the workaround for nms?

**Comment by Hussni-V** [comment]
```
test_cfg = dict(nms=dict(type='nms', split_thr=10000000000))
```
increase split_thr

**Comment by aleksei-kashapov** [comment]
Thanks, it helps
