### ISSUE TITLE
How to solve the IndexError: list index out of range?

### ISSUE THREAD

**Issue by Lanxin1011** [open-mmlab/mmdetection#4208]
I have actually encountered this kind of problem before, but after I change the variable ' num_classes' to be the actual number of classes instead of the number of classes plus one, the problem solved! But this time,  I switch to another server, and just stick to the rules as usual, when I run tools/train.py, the problems happen again. And I sincerely hope someone of u could help me out !! : )
Best regards~
**P.S. the error information is shown below.**
`2020-12-01 09:36:22,745 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 160/160, 22.6 task/s, elapsed: 7s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta)
  File "/home/zlx/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zlx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zlx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/zlx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zlx/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 143, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/home/zlx/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 162, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/zlx/mmdetection/mmdet/datasets/coco.py", line 403, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/zlx/mmdetection/mmdet/datasets/coco.py", line 348, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/zlx/mmdetection/mmdet/datasets/coco.py", line 280, in results2json
    json_results = self._det2json(results)
  File "/home/zlx/mmdetection/mmdet/datasets/coco.py", line 217, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range`

**Comment by Lanxin1011** [comment]
I have solved this problem~ The place went wrong seems a little stupid. And with the support of my senior fellow, I found out it is `val.json` that went wrong. So actually we should be very very careful to deal with our datasets and the config files since the error-tolerant rate is soooo high that it is very hard to figure out where the true problem is.
Thanks to mmdetection and the team behind : )
Best regards!~

**Comment by xvjiarui** [comment]
Cheers.

**Comment by junnnxie** [comment]
hello, I met the same problem. can you point out the problem about val.json?

**Comment by Lanxin1011** [comment]
> hello, I met the same problem. can you point out the problem about val.json?

Sorry for being late~ The problem I met was as follows:
the key "categories" should be:

> "categories": [{"supercategory": "none", "id": 1, "name": "Boeing737"}, {"supercategory": "none", "id": 2, "name": "Boeing747"}, {"supercategory": "none", "id": 3, "name": "Boeing777"}, {"supercategory": "none", "id": 4, "name": "Boeing787"}, {"supercategory": "none", "id": 5, "name": "A220"}, {"supercategory": "none", "id": 6, "name": "A321"}, {"supercategory": "none", "id": 7, "name": "A330"}, {"supercategory": "none", "id": 8, "name": "A350"}, {"supercategory": "none", "id": 9, "name": "ARJ21"}, {"supercategory": "none", "id": 10, "name": "other"}]

However I mistakenly made it to be:

> "categories": [{"supercategory": "none", "id": 1, "name": "Boeing737"}]

Hope u  can solve it smoothly : )

**Comment by junnnxie** [comment]
thanks a lot，I have solved my problem.




| |
junnnxie
|
|
junnnxie@163.com
|
签名由网易邮箱大师定制
On 1/12/2021 16:22，Lanxin1011<notifications@github.com> wrote：

hello, I met the same problem. can you point out the problem about val.json?

Sorry for being late~ The problem I met was as follows:
the key "categories" should be:

"categories": [{"supercategory": "none", "id": 1, "name": "Boeing737"}, {"supercategory": "none", "id": 2, "name": "Boeing747"}, {"supercategory": "none", "id": 3, "name": "Boeing777"}, {"supercategory": "none", "id": 4, "name": "Boeing787"}, {"supercategory": "none", "id": 5, "name": "A220"}, {"supercategory": "none", "id": 6, "name": "A321"}, {"supercategory": "none", "id": 7, "name": "A330"}, {"supercategory": "none", "id": 8, "name": "A350"}, {"supercategory": "none", "id": 9, "name": "ARJ21"}, {"supercategory": "none", "id": 10, "name": "other"}]

However I mistakenly made it to be:

"categories": [{"supercategory": "none", "id": 1, "name": "Boeing737"}]

Hope u can solve it smoothly : )
