### ISSUE TITLE
How to convert RGB  to HSV

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#4209]
Hello,

I want to convert RGB to HSV before the train and test process. 
Would you please show me how to do it. 

In my configuration py file, I use 
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
But I can't find which step to convert  BGR to RGB. My idea is to modify code and  convert BGR to HSV directly.

Thanks a lot!

**Comment by GiangHLe** [comment]
If you just want to make it quick. In `./mmdetection/mmdet/datasets/pipelines/loading.py`. Line 60, in `__call__` function, the variable img is the rgb array (you can check in `io.py` in [mmcv repo](https://github.com/open-mmlab/mmcv)), so add another line `img = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)` and it's done.

For a long term project, you should generate new pipelines to load image as [this turtorial](https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html), then use it in your config.

**Comment by minan19605** [comment]
@GiangHLe Thank you so much for your information. But I found that:
1.  in the mmcv io.py, the function imfrombytes()
        img = cv2.imdecode(img_np, flag)
        if flag == IMREAD_COLOR and channel_order == 'rgb':
            cv2.cvtColor(img, cv2.COLOR_BGR2RGB, img)
 that return BGR format, not RGB format. 
So I add one line code to convert to  HSV.

**Comment by minan19605** [comment]
I have another question about Normalize configuration:
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
that is in the pipeline configuration:
dict(type='Normalize', **img_norm_cfg),

**I don't know how to normalize the HSV images,  could you advise?**
Currently, I comment on the normalize line and modify one place in train and test pipeline:
dict(type='LoadImageFromFile', **_to_float32=True_**),

**Comment by GiangHLe** [comment]
@minan19605 yes, I miss their default variable, but if you use BGR or HSV, make sure your normalization variable in the configs file is matched with color space and order. Besides that, if you install follow mmdetection instruction, mmcv will be in your site-package, so I recommend you should modify the code in `loading.py`  in mmdet.

**Comment by GiangHLe** [comment]
@minan19605 glob all your dataset, change them to HSV then compute mean and std as normal

**Comment by GiangHLe** [comment]
@minan19605 glob all your dataset, change them to HSV then compute mean and std as normal. As I remember, Hue channel of opencv only reach 180, so I think you need to modify the Normalize function too

**Comment by minan19605** [comment]
Got it! Thank you so much!
