### ISSUE TITLE
Loading data from s3 

### ISSUE THREAD

**Issue by Adblu** [open-mmlab/mmdetection#4212]
Lets say I am not allowed to store train/test images on ec2 instance due to company rules. 
Would it be possible to feed images to training process from s3 directly to the memory ? Probably it would seriously affect loading time ?
During training, when evaluation is performed, batch inference happens which also could complicate the process.

**Comment by ZwwWayne** [comment]
Yes, you could load images from s3. We support different file client to load images through disk, ceph, and IMDB. You can also customize your file client to load image through network. It will not be an issue if the network is fast. See details of [fileclient in mmcv](https://mmcv.readthedocs.io/en/latest/api.html?highlight=fileclient#mmcv.fileio.FileClient)

**Comment by Adblu** [comment]
Perfect. One more question @ZwwWayne . 
I am wondering in which place implement/register new backend and where to call it. 
In the train config file we are specifying:

```
dict(type="LoadImageFromFile"),
dict(type="LoadAnnotations", with_bbox=True, with_mask=True),
```

Do we have to change it somehow accordingly

**Comment by ZwwWayne** [comment]
You can specify it in `LoadImageFromFile` and `LoadAnnotations`, see [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/loading.py#L34). You do not need to implement a loading module, rather, you just need to implement a new file client. Here is an [example of using the Ceph backend in MMDetection3D](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/nus-3d.py#L19).

**Comment by Adblu** [comment]
Perfect, thanks !
