### ISSUE TITLE
Add option to disable non-max supression.

### ISSUE THREAD

**Issue by Erotemic** [open-mmlab/mmdetection#4214]
**Describe the feature**

It would be nice if there was a simple configuration to disable non-max suppression. This should be fairly simple to add to `multiclass_nms`. In the `nms_cfg` simply accept a key called `"enabled"`, which defaults to `True` and if `False`  then just modify the format so it agrees with the normal output of that function: 

```python
    enabled = nms_cfg.get('enabled', True)
    if enabled:
        dets, keep = batched_nms(bboxes, scores, labels, nms_cfg)
    else:
        # Keep the output format the same as if nms was called
        keep = torch.arange(scores.shape[0])
        dets = torch.cat((bboxes[keep], scores[keep].reshape(-1, 1)), dim=1)
```

This will not break existing models, but it will allow for new models to have this feature.

**Motivation**

It is inconvenient when I want to use mmdet to build larger models, but I'm forced to execute its nms step. I find myself monkey patching it out frequently. I'd like to avoid this and simply set a flag that disables it.

**Comment by Erotemic** [comment]
@hellock if you and the other mmdet guys think this is a good idea, I'll make the PR.

**Comment by hellock** [comment]
Thanks! This proposal LGTM. How about just using `nms_cfg=None` to disable it?

**Comment by Erotemic** [comment]
Using `nms_cfg=None` makes sense, I'll make a PR with that change.
