### ISSUE TITLE
How to install multi version of mmdetection?

### ISSUE THREAD

**Issue by jajajajaja121** [open-mmlab/mmdetection#4217]
I want to install 2.7 and 1.2 in my computer, but after I install 1.2 when I run 2.7 there is a error said segmentation fault, and When I install 2.7 the module has not compile, I have read your documents about how to install multiple mmdetection version, but I can't understand how to deal.

**Comment by ZwwWayne** [comment]
Segmentation fault has no relation with the code version. It is about the in-compatibility between GCC/CUDA/Pytorch. See the   [FAQ here](https://mmdetection.readthedocs.io/en/latest/faq.html#).
