### ISSUE TITLE
error in segementation 

### ISSUE THREAD

**Issue by AhmedNageh08** [open-mmlab/mmdetection#4218]
i tried python train.py on google colab gpu that's the train.py
https://github.com/open-mmlab/mmfashion/blob/master/configs/fashion_parsing_segmentation/demo.py
but i have this error
/usr/local/lib/python3.6/dist-packages/torch/cuda/init.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
File "/content/mmfashion/mmdetection/tools/demo.py", line 3, in
from mmdet.apis import inference_detector, init_detector, show_result
File "/usr/local/lib/python3.6/dist-packages/mmdet/apis/init.py", line 1, in
from .inference import (async_inference_detector, inference_detector,
File "/usr/local/lib/python3.6/dist-packages/mmdet/apis/inference.py", line 7, in
from mmcv.ops import RoIPool
File "/usr/local/lib/python3.6/dist-packages/mmcv/ops/init.py", line 1, in
from .bbox import bbox_overlaps
File "/usr/local/lib/python3.6/dist-packages/mmcv/ops/bbox.py", line 3, in
ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
ext = importlib.import_module('mmcv.' + name)
File "/usr/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.6/dist-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

torch-1.7.0
mmcv-1.2.1
and thanks in advance

**Comment by ZwwWayne** [comment]
This is because the MMCV you installed is not build in torch1.7.  You might need to re-compile your MMCV for torch 1.7, or downgrade torch to be 1.6. See the documentation [here](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment) for more details.
