### ISSUE TITLE
Error when converting yolo to onnx

### ISSUE THREAD

**Issue by KyoukaMinaduki** [open-mmlab/mmdetection#4221]
Hello. When I am converting yolo to onnx. An error occurs:
The version is:
mmcv --> 1.2.0
mmdet --> 2.6.0
python --> 3.7.9
numpy -->1.19.2
onnx --> 1.8.0

python tools/pytorch2onnx.py work_dirs/yolov3_d53_mstrain-608_273e_rgb/yolov3_d53_mstrain-608_273e_rgb.py work_dirs/yolov3_d53_mstrain-608_273e_rgb/latest.pth --verify
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/core/anchor/anchor_generator.py:255: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  feat_h = int(feat_h)
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/core/anchor/anchor_generator.py:256: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  feat_w = int(feat_w)
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/core/anchor/anchor_generator.py:199: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  xx = x.repeat(len(y))
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/core/anchor/anchor_generator.py:200: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  yy = y.view(-1, 1).repeat(1, len(x)).view(-1)
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/core/bbox/coder/yolo_bbox_coder.py:69: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/core/bbox/coder/yolo_bbox_coder.py:70: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(-1) == bboxes.size(-1) == 4
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/models/dense_heads/yolo_head.py:270: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729006826/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  conf_inds = conf_pred.ge(conf_thr).nonzero().flatten()
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/models/dense_heads/yolo_head.py:277: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if 0 < nms_pre < conf_pred.size(0):
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/models/dense_heads/yolo_head.py:293: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if with_nms and (multi_lvl_conf_scores.size(0) == 0):
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.6.0-py3.7.egg/mmdet/core/post_processing/bbox_nms.py:33: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] > 4:
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/ops/nms.py:258: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if len(boxes_for_nms) < split_thr:
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/ops/nms.py:82: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/ops/nms.py:83: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 142, in <module>
    normalize_cfg=normalize_cfg)
  File "tools/pytorch2onnx.py", line 43, in pytorch2onnx
    opset_version=opset_version)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/torch/onnx/utils.py", line 934, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/onnx/symbolic.py", line 17, in symbolic_fn
    g, interpolate_mode, args)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 254, in _get_interpolate_attributes
    scales = _interpolate_get_scales_if_available(g, scales)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 229, in _interpolate_get_scales_if_available
    available_scales = _maybe_get_const(scales[0], 'f') != -1 and not _is_none(
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 64, in _maybe_get_const
    return _parse_arg(value, desc)
  File "/home/hkuit155/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 33, in _parse_arg
    return float(tval)
ValueError: only one element tensors can be converted to Python scalars

**Comment by ShaneYS** [comment]
same error

**Comment by ZwwWayne** [comment]
Please @RunningLeon  to have look.

**Comment by RunningLeon** [comment]
@ShaneYS @KyoukaMinaduki 

Have you used a custom config file or a different checkpoint file? Pls. provide runtime info by running `python mmdet/utils/collect_env.py` and other relevant info to reproduce it.
BTW, I had tested again with pytorch=1.6.0, mmcv=1.2.0, mmdet=2.6.0, onnx=1.7.0, python=3.7.0 and the conversion has gone successfully.

**Comment by ShaneYS** [comment]
@RunningLeon Thanks for your reply.

1. 
I download the `MMDetection V2.5.0 Release`, and modify some code to use mmcv==1.2.0:
```
(mmlab) /home/user/mmdetection-2.5.0$ git diff
diff --git a/mmdet/__init__.py b/mmdet/__init__.py
index fdd1d34..6701325 100644
--- a/mmdet/__init__.py
+++ b/mmdet/__init__.py
@@ -16,7 +16,7 @@ def digit_version(version_str):
 
 mmcv_minimum_version = '1.1.5'
-mmcv_maximum_version = '1.2'
+mmcv_maximum_version = '1.2.0'
 mmcv_version = digit_version(mmcv.__version__)
```

2. 
My result of `python mmdet/utils/collect_env.py`:
```
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1060 6GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1+cu110
OpenCV: 4.4.0
MMCV: 1.2.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
```

3. 
I use tools/pytorch2onnx.py, and use official config and checkpoint without modify:
```
    parser.add_argument('--config',
                        default='../configs/yolo/yolov3_d53_mstrain-608_273e_coco.py',
                        help='test config file path')
    parser.add_argument('--checkpoint',
                        default='../checkpoints/yolov3_d53_mstrain-608_273e_coco-139f5633.pth',
                        help='checkpoint file')
    parser.add_argument('--input-img',
                        default='../demo/demo.jpg',
                        type=str, help='Images for input')
```

**Comment by ShaneYS** [comment]
Before I use `MMDetection V2.5.0 Release`, I also try the latest code with commit id: 
`commit 3e902c3afc62693a71d672edab9b22e35f7d4776 (HEAD -> master, tag: v2.7.0, origin/master, origin/HEAD)`, but got the same error.

**Comment by RunningLeon** [comment]
Pls. try with latest mmcv.

**Comment by KyoukaMinaduki** [comment]
> Pls. try with latest mmcv.

Thanks for your reply. My environment is shown below

sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.2.0
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.6.0+d3cf38d

**Comment by ShaneYS** [comment]
> Pls. try with latest mmcv.

I use latest mmcv and mmdet, but get the same error.
```
    import torch
    import torchvision
    import mmcv
    import mmdet
    print(f'torch version: {torch.__version__}')
    print(f'torchvision version: {torchvision.__version__}')
    print(f'mmcv version: {mmcv.__version__}')
    print(f'mmdet version: {mmdet.__version__}')

torch version: 1.7.0+cu110
torchvision version: 0.8.1+cu110
mmcv version: 1.2.1
mmdet version: 2.7.0
```

I install mmcv-full and mmdetection by:
```
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
MMCV_WITH_OPS=1 pip install -e .

git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -v -e .
```

**Comment by RunningLeon** [comment]
Pls. change this [line ](https://github.com/open-mmlab/mmdetection/blob/bec3fc1a862cb9caebb40710bc2e52e586f741b4/mmdet/models/dense_heads/yolo_head.py#L273) to ` conf_inds = conf_pred.ge(conf_thr).nonzero( as_tuple=False).squeeze(1)` and it works.

Weird ...
`flatten ` create a constant shape, as below:
![normal](https://user-images.githubusercontent.com/28671653/101468921-ff7d5b00-397e-11eb-8ad8-737d3d7296f9.jpg)

**Comment by KyoukaMinaduki** [comment]
> Pls. use pytorch=1.6.0 and for now, change this [line ](https://github.com/open-mmlab/mmdetection/blob/bec3fc1a862cb9caebb40710bc2e52e586f741b4/mmdet/models/dense_heads/yolo_head.py#L273) to ` conf_inds = conf_pred.ge(conf_thr).nonzero( as_tuple=False).squeeze(1)` and it works.
> 
> Weird ...
> `flatten ` create a constant shape, as below:
> ![normal](https://user-images.githubusercontent.com/28671653/101468921-ff7d5b00-397e-11eb-8ad8-737d3d7296f9.jpg)

Thank you for your reply.
So the conversion to yolo will be failed when using torch 1.6, right？

**Comment by RunningLeon** [comment]
@KyoukaMinaduki No, with pytorch=1.6.0, you would successfully convert Yolo to ONNX format.

**Comment by KyoukaMinaduki** [comment]
> @KyoukaMinaduki No, with pytorch=1.6.0, you would successfully convert Yolo to ONNX format.

Oh, sorry. I want to ask whether the conversion will be failed using pytorch 1.7.0...

**Comment by RunningLeon** [comment]
@KyoukaMinaduki yes, there would be some issue with pytorch=1.7.0 and may fail in converting.

**Comment by KyoukaMinaduki** [comment]
Hello. Sorry for my late reply.
I tried converting yolov3 with pytorch2onnx.py using pytorch1.6, it succeeded. But the output is different after verification.

**Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 202, in <module>
    test_img=args.test_img)
  File "tools/pytorch2onnx.py", line 125, in pytorch2onnx
    atol=1e-05,
  File "/home/hkuit155/anaconda3/envs/mm16/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/hkuit155/anaconda3/envs/mm16/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 5 / 65 (7.69%)
Max absolute difference: 38.792847
Max relative difference: 4.391222
 x: array([[ 5.839589e+02,  3.215527e+02,  9.358926e+02,  6.484977e+02,
         9.999986e-01],
       [ 7.153469e+02,  1.144297e+02,  1.105215e+03,  5.427672e+02,...
 y: array([[ 5.839589e+02,  3.215527e+02,  9.358926e+02,  6.484977e+02,
         9.999986e-01],
       [ 7.153470e+02,  1.144297e+02,  1.105215e+03,  5.427672e+02,...**

Are there any details I missed? My environment is:
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.2.4
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.7.0+d27e5de
