### ISSUE TITLE
How to perform evaluation of a specific class? 

### ISSUE THREAD

**Issue by tkeval** [open-mmlab/mmdetection#4222]
Hi! 
I am working with a dataset that has a lot of categories. I am trying to run tools/test.py --eval bbox with for a single class, i.e., car. I changed the following: 
class CocoDataset(CustomDataset):

    CLASSES = ('car') 

However, I am still getting below error. I have also tried a number of other things by searching this forum, but I wasn't able to resolve it. For reference, I am usnig yolo cfg. I have only changed test annotations and test dir in the config file. 
Thanks a lot! 

loading annotations into memory...
Done (t=0.62s)
creating index...
index created!
[>>] 300/300, 27.3 task/s, elapsed: 11s, ETA:     0sTraceback (most recent call last):
  File "/content/mmdetection/tools/test.py", line 208, in <module>
    main()
  File "/content/mmdetection/tools/test.py", line 204, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/content/mmdetection/mmdet/datasets/coco.py", line 385, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 332, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 266, in results2json
    json_results = self._det2json(results)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 206, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

**Comment by ZwwWayne** [comment]
1. You should set ('car', )
2. We suggest you simply test the model for all the categories and use the `classwise` option to see the detailed mAP for each class, e.g., use the `evaluation=dict(classwise=True, metric='bbox') in your config if you are using COCO dataset.

**Comment by Soodep** [comment]
what if I am using the Voc dataset? How to perform evaluation of a specific class?
