### ISSUE TITLE
Cannot find pretrained weight for DETR

### ISSUE THREAD

**Issue by TheDarkKnight300** [open-mmlab/mmdetection#4227]
Under mmdetection/configs/detr, if I click on the 'model' inside results and models, it redirects me back to the same page and does not start downloading the weight file. Usually, when I have done this for other models, the weights start being downloaded. 

Could you provide me the link to the DETR pretrained weights? Thanks in advance.

**Comment by TheDarkKnight300** [comment]
@ZwwWayne @hellock

**Comment by Ngoc-Nguyen-NIS** [comment]
Hi @TheDarkKnight300 ,
I have converted DETR pretrained weights (R50) from https://github.com/facebookresearch/detr to mmdet format(configs/detr/detr_r50_8x4_150e_coco.py). Please check it out.
https://drive.google.com/file/d/1qQwVqF_SkncL663ig7GpGauFYSYeQErU/view?usp=sharing

**Comment by TheDarkKnight300** [comment]
It works perfectly, thank you. @Ngoc-Nguyen-NIS

**Comment by ZwwWayne** [comment]
DETR checkpoints will be released soon in the next week.
