### ISSUE TITLE
classwise map@50 calculation

### ISSUE THREAD

**Issue by yldrmBtn** [open-mmlab/mmdetection#4230]
As I know mmdetection support classwise mAP calculation. Can we specify any metric for classwise evaluation s.t. mAP@50 ?

**Comment by ZwwWayne** [comment]
1. If you are using COCO mAP, classwise mAP only support for COCO mAP, i.e., average AP of IoU from 0.5 to 0.95.
2. If you are using the VOC mAP, classwise AP@0.5 will be shown by a table with the mAP@0.5.

**Comment by lalagood** [comment]
if only the COCO mAP could do this——specify any metric for classwise evaluation s.t. mAP@50.
 look forwards to this, thx.

**Comment by deepakksingh** [comment]
I notice that in many research papers the mAP@50 is commonly reported and the dataset in coco json format helps in easier training. So i would request for this feature too.

**Comment by deepakksingh** [comment]
@ZwwWayne Could you suggest any way to configure COCO evaluation to display classwise mAP@50 instead of mAP with iou 50 to 95?
Because currently when I set classwise=True in evaluation, it displays the classwise AP for thresholds ranging from 50 to 95
