### ISSUE TITLE
Question about testing the test2017.

### ISSUE THREAD

**Issue by reedwiththought** [open-mmlab/mmdetection#4231]
Hi, thanks for your great work. I try to test the test2017 and want to get the test_dev_results, but failed. Could you give me some advice? Thank you.

**Comment by ZwwWayne** [comment]
Please use the `Error Template`. We do not know which failure you met so we are not able to give any advice here.

**Comment by reedwiththought** [comment]
Thans for your reply. I forget changing the annotations. And it's ok now.
