### ISSUE TITLE
how to use debug mode properly?

### ISSUE THREAD

**Issue by wyman123** [open-mmlab/mmdetection#4234]
How to use debug if I set "debug" in cfg True for rcnn?

r`rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            match_low_quality=False,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))`

**Comment by ZwwWayne** [comment]
There is no debug mode now actually.
