### ISSUE TITLE
'person' single class training and testing by using resnet50-based retinanet

### ISSUE THREAD

**Issue by WilliamYi96** [open-mmlab/mmdetection#424]
I wonder if I just need to use 'person' label to train and test by setting resnet50-based retinanet as backbone, what do I need to modify?

I've attempted to modifiy the following:

- retinanet_r50_fpn_1x.py: convert num_classes=81 =>> number_classes=2; 
- mmdet/datasets/coco.py: self.cat_ids = self.coco.getCatIds() =>> self.cat_ids = self.coco.getCatIds(catNms=['person']) and self.img_ids = self.coco.getImgIds() =>> self.img_ids = self.coco.getImgIds(CatIds=self.CatIds).

However, it still can not work.
Has anyone faced the same problem and solved it?

**Comment by wizholy** [comment]
when install the mmdetection, you shold use 
python setup.py develop

**Comment by WilliamYi96** [comment]
@wizholy Thanks for your reminder. However, I'm using `python setup.py develop` indeed. Currently, I've solved the problem by just kicking out irrelevant categories and annotations in COCO17 dataset.
