### ISSUE TITLE
configdict' object has no attribute 'pipeline'

### ISSUE THREAD

**Issue by Nabyssache** [open-mmlab/mmdetection#4240]
when I use the tools/browse_dataset.py, the above event occur.

line 47 cfg = retrieve_data_cfg

line 39 x for x in train_data_cfg.pipeline if x['type'] not in skip_tpye

I run code: python tools/browse_dataset.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py --output-dir ./example --not-show

**Comment by ZwwWayne** [comment]
Please @v-qjqs have a check and fix the bug.

**Comment by Nabyssache** [comment]
@v-qjqs

**Comment by v-qjqs** [comment]
Hi @Nabyssache, I checked and there is no such error in my experiments. Which version of mmcv and mmdet did you use?

**Comment by WinnieLaugh** [comment]
Hi, I have met the same error when analyzing the results with the config file "ssd512_coco.py", could you advise on it?

**Comment by Nabyssache** [comment]
@WinnieLaugh @v-qjqs 
sorry，I have found a solution but I forgot to reply this question.
You have to change something in your dataset.py such as voc0712.py when you use browse_dataset.py:
```
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=0,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                data_root + 'VOC2007/ImageSets/Main/trainval.txt',
                # data_root + 'VOC2012/ImageSets/Main/trainval.txt'
            ],
            img_prefix=[data_root + 'VOC2007/'],
            pipeline=train_pipeline)),

```

after change :
```
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=0,
    train=dict(
#        type='RepeatDataset',
#        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                data_root + 'VOC2007/ImageSets/Main/trainval.txt',
                # data_root + 'VOC2012/ImageSets/Main/trainval.txt'
            ],
            img_prefix=[data_root + 'VOC2007/'],
#            pipeline=train_pipeline)),
             pipeline=train_pipeline),
```
python tools/browse_dataset.py configs/.. --output-dir ./SHOW 
then you can see whether your xml is right.

**Comment by WinnieLaugh** [comment]
Thanks for your advice! @Nabyssache 

So I guess it's the problem of "RepeatDataset"?

**Comment by milleniums** [comment]
> [@WinnieLaugh](https://github.com/WinnieLaugh) [@v-qjqs](https://github.com/v-qjqs) sorry，I have found a solution but I forgot to reply this question. You have to change something in your dataset.py such as voc0712.py when you use browse_dataset.py:
> 
> ```
> data = dict(
>     samples_per_gpu=2,
>     workers_per_gpu=0,
>     train=dict(
>         type='RepeatDataset',
>         times=3,
>         dataset=dict(
>             type=dataset_type,
>             ann_file=[
>                 data_root + 'VOC2007/ImageSets/Main/trainval.txt',
>                 # data_root + 'VOC2012/ImageSets/Main/trainval.txt'
>             ],
>             img_prefix=[data_root + 'VOC2007/'],
>             pipeline=train_pipeline)),
> ```
> 
> after change :
> 
> ```
> data = dict(
>     samples_per_gpu=2,
>     workers_per_gpu=0,
>     train=dict(
> #        type='RepeatDataset',
> #        times=3,
>         dataset=dict(
>             type=dataset_type,
>             ann_file=[
>                 data_root + 'VOC2007/ImageSets/Main/trainval.txt',
>                 # data_root + 'VOC2012/ImageSets/Main/trainval.txt'
>             ],
>             img_prefix=[data_root + 'VOC2007/'],
> #            pipeline=train_pipeline)),
>              pipeline=train_pipeline),
> ```
> 
> python tools/browse_dataset.py configs/.. --output-dir ./SHOW then you can see whether your xml is right.

This method works, and I originally used ConcatDataset.
