### ISSUE TITLE
typo in WrapFieldsToLists docstring

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmdetection#4242]
https://github.com/open-mmlab/mmdetection/blob/fb287b144eee70134cd6369f70deb43fdb8d499a/mmdet/datasets/pipelines/formating.py#L327-L345

I think you mean `WrapFieldsToLists` instead of `WrapIntoLists` in line 343.

**Comment by v-qjqs** [comment]
@hubutui, thanks for your comments. I will fix the docstring.

**Comment by ZwwWayne** [comment]
Hi @hubutui ，
Thanks for pointing it out. Would you like to create a PR to fix that?
