### ISSUE TITLE
How to train multi datasets jointly?

### ISSUE THREAD

**Issue by xingjici** [open-mmlab/mmdetection#4248]
Suppose that I have two dataset COCO and VOC . How to modify the config file and training scripts to work on them jointly.

**Comment by ZwwWayne** [comment]
MMDetection now does not support to concatenate different types of dataset, as they have different classes. If you really want to do that, we suggest you convert VOC data to the format of COCO first, then concatenate two COCO dataset with different annotation files to achieve your goal. Examples of concatenating datasets can be find [in the doc](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html#customize-datasets-by-dataset-wrappers).
