### ISSUE TITLE
the result of training 2x is much lower than training 1x

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection#4249]
Hi, sir. I use the cascade_rcnn_r101_fpn to train the same training set (4000 images) and train it with 1x and 2x respectively. when I train it with 2x, I change the `step=[8, 11]` to `step=[16, 22]` in config file, and get the result, `1x` get ap 55.67 and `2x` get ap 52.37, 
why 2x is much lower than 1x? Very appreciate for your reply!

**Comment by ZwwWayne** [comment]
This might because your dataset is too small, and the model overfits the dataset. To avoid that, you could use stronger augmentation strategies or use shorter schedules, e.g., 20 epoch.

**Comment by yustaub** [comment]
when I add some albu augmentation to the config cascade_rcnn_r101_fpn_1x.py , should I add the epoches to train or keep the epoch 1x ? @ZwwWayne

**Comment by ZwwWayne** [comment]
You can keep them first and see whether the results changes.

**Comment by yustaub** [comment]
ok, thanks!!
