### ISSUE TITLE
how to use pure background images,which has no gt bbox?

### ISSUE THREAD

**Issue by 15605190982** [open-mmlab/mmdetection#425]
I get a dataset, some images are pure background, how to use them (no gt bbox)to train a model?

**Comment by HaoxuZhang** [comment]
Same question here.

**Comment by hellock** [comment]
Images without gt bboxes are filtered in the dataset currently. We may consider adding support for that.

**Comment by SUYEgit** [comment]
Have you add support for training with background images? It'd be important for reducing over detection. If not, could you please tell me the place or method to modify your codes to support training with background images?

**Comment by hbhflw2000** [comment]
Could I know if you have already added support for that? As far as I know, the model performance will be better if the number of positive samples vs that of negative ones is 1:1, it will help reduce false positives. (Frankly I'm not sure if this is reasonable.)

Thanks in advance for your help.

**Comment by pkhigh** [comment]
@hellock can you suggest the files which we can update so that images with background only can also be used in training ?

**Comment by BlakeXiaochu** [comment]
I face the same problem~ Could anybody tell me how far has the future plan been achieved, or give some suggestions about modify the code by myself ?

**Comment by zvadaszi** [comment]
I'm also interested in this feature or some guidance on what to change in the code. Thanks!

**Comment by hellock** [comment]
Solved in #1531
