### ISSUE TITLE
ResneSt related weights and logs cannot be downloaded

### ISSUE THREAD

**Issue by zhaoxin111** [open-mmlab/mmdetection#4256]
ResneSt related weights and logs cannot be downloaded

<Error>
<Code>AccessDenied</Code>
<Message>You have no right to access this object because of bucket acl.</Message>
<RequestId>5FD02A884EBCCF02308D2C80</RequestId>
<HostId>download.openmmlab.com</HostId>
</Error>

**Comment by liuyanzhi1214** [comment]
When can it be repaired?

**Comment by v-qjqs** [comment]
Hi, did you mean you have no right to access the ImageNet pretrained resnest backbone?

**Comment by liuyanzhi1214** [comment]
> Hi, did you mean you have no right to access the ImageNet pretrained resnest backbone?

yes

**Comment by v-qjqs** [comment]
Hi, which kind of resnest, resnest50?

**Comment by liuyanzhi1214** [comment]
> Hi, which kind of resnest, resnest50?

emmm...all models of resnest cannot download

**Comment by v-qjqs** [comment]
Hi, it's normal in my experiments. I wonder which config do you use, I will check it.

**Comment by liuyanzhi1214** [comment]
> Hi, it's normal in my experiments. I wonder which config do you use, I will check it.
configs/resnest/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco.py and /configs/resnest/faster_rcnn_s101_fpn_syncbn-backbone+head_mstrain-range_1x_coco.py
thanks~ :>

**Comment by v-qjqs** [comment]
Hi, it's normal in my experiments for your above two configs. Did you have network connection problems?
Or you may manually download pretrained [resnest101](https://download.openmmlab.com/pretrain/third_party/resnest101_d2-f3b931b2.pth) and [resnest50](https://download.openmmlab.com/pretrain/third_party/resnest50_d2-7497a55b.pth).

**Comment by liuyanzhi1214** [comment]
> Hi, it's normal in my experiments for your above two configs. Did you have network connection problems?
> Or you may manually download pretrained [resnest101](https://download.openmmlab.com/pretrain/third_party/resnest101_d2-f3b931b2.pth) and [resnest50](https://download.openmmlab.com/pretrain/third_party/resnest50_d2-7497a55b.pth) here.

Thank you very much, I have successfully downloaded them. :>

**Comment by carranza96** [comment]
I am facing the same issue, the full pre-trained ResNeSt models are not available, it says that access is forbidden. For instance, these two:

http://download.openmmlab.com/mmdetection/v2.0/resnest/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco/faster_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco_20200926_125502-20289c16.pth

http://download.openmmlab.com/mmdetection/v2.0/resnest/faster_rcnn_s101_fpn_syncbn-backbone+head_mstrain-range_1x_coco/faster_rcnn_s101_fpn_syncbn-backbone+head_mstrain-range_1x_coco_20201006_021058-421517f1.pth

Could it be fixed? Thanks

**Comment by zhaoxin111** [comment]
> Hi, it's normal in my experiments for your above two configs. Did you have network connection problems?
> Or you may manually download pretrained [resnest101](https://download.openmmlab.com/pretrain/third_party/resnest101_d2-f3b931b2.pth) and [resnest50](https://download.openmmlab.com/pretrain/third_party/resnest50_d2-7497a55b.pth) here.

Hi, the (https://download.openmmlab.com/pretrain/third_party/resnest101_d2-f3b931b2.pth) and [resnest50](https://download.openmmlab.com/pretrain/third_party/resnest50_d2-7497a55b.pth)  can be downloaded successfully, but the resnest based detectors still can not. Could you fix it? Thanks.
