### ISSUE TITLE
Mean and variance of data sets

### ISSUE THREAD

**Issue by LoveIsAGame** [open-mmlab/mmdetection#4261]
hello，
I have a new dataset, and I organize it into coco. But I don't know if I need to modify mean and STD in configs。
![图片](https://user-images.githubusercontent.com/49852180/101572085-e7efb200-3a12-11eb-846b-2848150f0bd7.png)

As shown in the figure above, I calculated the mean and STD of the dataset myself, and the result is quite different from the original mean and STD. I don't know if this is correct

Looking forward to your reply！

**Comment by LoveIsAGame** [comment]
I tried to modify and train, and all the losses became Nan. I don't know where the problem is. Does this data need to be modified?

**Comment by hhaAndroid** [comment]
I don't know what data you are，please confirm that the mean and variance are correct，the pix range is 0-255，not 0-1，so mean should not be so low

**Comment by LoveIsAGame** [comment]
@hhaAndroid 

Excuse me, do you have Python code to calculate the mean and variance of data sets?
If so, would you like to share it with me？
