### ISSUE TITLE
The log of ssd is got by mmdetv1.0 in mmdetv2.x tag

### ISSUE THREAD

**Issue by Sundrops** [open-mmlab/mmdetection#4268]
http://download.openmmlab.com/mmdetection/v2.0/ssd/ssd300_coco/ssd300_coco_20200307_174216.log.json

```json
{"CUDA_HOME": "/mnt/lustre/share/platform/dep/cuda-9.0-cudnn7.6", "GPU 0,1,2,3,4,5,6,7": "TITAN Xp", "PyTorch": "1.1.0", "TorchVision": "0.2.2", "MMCV": "0.2.16", "MMDetection": "1.0rc1+5f9f470", "seed": 0}
```
http://download.openmmlab.com/mmdetection/v2.0/ssd/ssd512_coco/ssd512_coco_20200308_134447.log.json
```json
{"CUDA_HOME": "/mnt/lustre/share/platform/dep/cuda-9.0-cudnn7.6", "GPU 0,1,2,3,4,5,6,7": "TITAN Xp", "PyTorch": "1.1.0", "TorchVision": "0.2.2", "MMCV": "0.2.16", "MMDetection": "1.0rc1+5f9f470", "seed": 0}
```

**Comment by ZwwWayne** [comment]
This is because, during our benchmark, the tag of v2.0 is not updated. But the model is trained by the code and implementation of v2.0.
