### ISSUE TITLE
ERROR - The testing results of the whole dataset is empty

### ISSUE THREAD

**Issue by NaeemKhan333** [open-mmlab/mmdetection#4273]
I am training "cascade_mask_rcnn_hrnetv2p_w32_20e_coco" network using mm-detection. During training,I get the following error

2020-12-09 15:19:29,784 - mmdet - ERROR - The testing results of the whole dateset is empty.

Can anybody guide what could be the reason for it . Thank you

**Comment by ZwwWayne** [comment]
duplicate #4274
