### ISSUE TITLE
downsampling  in CARAFE++

### ISSUE THREAD

**Issue by laocan** [open-mmlab/mmdetection#4277]
Can I replace the downscaling operator by  setting `scale_factor=0.5`  in cfg of CARAFE,  to get the result in the paper "CARAFE++: Unified Content-AwareReAssembly of FEatures"?
thx~

**Comment by ZwwWayne** [comment]
For now, CARAFE only supports upsampling. We will support CARAFE++ for both upsampling and downsampling in the future.

**Comment by laocan** [comment]
Got it, I have just read the CUDA version of CARAFE. the parameter is int-type, it seems that there are still  some details to be modified...

**Comment by ZwwWayne** [comment]
CARAFE++ will be supported in MMCV in the future. So we will not track the progress in mmdet and this issue will be closed.
