### ISSUE TITLE
batch_intput_shape

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection#4279]
Typo in [batch_intput_shape](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/transformer_head.py#L237) should probably be fixed here and in other places.

**Comment by v-qjqs** [comment]
Hi, could you give me a detailed suggestions or comments?

**Comment by filaPro** [comment]
Hi @v-qjqs , I think `batch_intput_shape` should be renamed to `batch_input_shape`.

**Comment by v-qjqs** [comment]
Hi @filaPro, thanks for your comments very much. Could you please create a PR to fix the type error?

**Comment by filaPro** [comment]
Sure.
