### ISSUE TITLE
Can we use densenet as backbone?

### ISSUE THREAD

**Issue by JincanDeng** [open-mmlab/mmdetection#428]

**Comment by hellock** [comment]
It is convenient if you want to add new backbones to mmdetection. You can just do what [resnet](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py) do.

**Comment by JincanDeng** [comment]
> It is convenient if you want to add new backbones to mmdetection. You can just do what [resnet](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py) do.

Thank you. I will try it.

**Comment by casstio** [comment]
hello,i'm a newer in this area，i'm very interested in this topic，but i don't know if it is easy to change the backbone like from resnet to densenet ,and how to get it，can you give me some advice? thank you very much
