### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by yy18dlz** [open-mmlab/mmdetection#4280]
Hi, There are some errors when evaluation
2020-12-10 14:38:14,837 - mmdet - INFO - Saving checkpoint at 20 epochs
[                                                  ] 0/60000, elapsed: 0s, ETA:Traceback (most recent call last):

RuntimeError: CUDA error: no kernel image is available for execution on the device (NMSCUDAKernelLauncher at ./mmcv/ops/csrc/pytorch/nms_cuda.cu:50)

mv env:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN V             On   | 00000000:3D:00.0 Off |                  N/A |
| 28%   27C    P8    24W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN V             On   | 00000000:3F:00.0 Off |                  N/A |
| 28%   26C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN V             On   | 00000000:40:00.0 Off |                  N/A |
| 28%   25C    P8    24W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN V             On   | 00000000:43:00.0 Off |                  N/A |
| 28%   24C    P8    22W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  TITAN V             On   | 00000000:44:00.0 Off |                  N/A |
| 28%   25C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  TITAN V             On   | 00000000:45:00.0 Off |                  N/A |
| 28%   25C    P8    23W / 250W |      0MiB / 12066MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

 torch.__version__
'1.4.0+cu92

mmcv-full                          1.2.1

**Comment by yhcao6** [comment]
`cuda arch` are not consistent during comping and run time. Make sure your cuda env are the same during compiling and run time.

**Comment by ZwwWayne** [comment]
See the [FAQ](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment).
