### ISSUE TITLE
Where is bbox coordinates

### ISSUE THREAD

**Issue by vlvk5946** [open-mmlab/mmdetection#4281]
I want to find the coordinates of where the object was found on the webcam.
I want to know the distance from the camera to the object through the depth camera.
But, I couldn't find where to find the coordinates or how to fix it.

**Comment by yhcao6** [comment]
You can print the `results` here for coordinates of objects
https://github.com/open-mmlab/mmdetection/blob/e02aa233c479ab55b97736e929236c4bc128806e/demo/webcam_demo.py#L35
