### ISSUE TITLE
Hyperparameter tuning with Ray Tune

### ISSUE THREAD

**Issue by borgarpa** [open-mmlab/mmdetection#4285]
Hi!

I am very interested in using Ray Tune to optimize the hyperparameters of a model with state-of-the-art algorithms like ASHA or Hyperband.

The thing is, Ray Tune needs to get access to each epoch's target metric and log it to the tuner function in order to be able to select the best model after the search.

Is there a way to apply a function on epoch's end to the mmdet training function while extracting certain metrics?

For more information check the official [Ray Tune](https://docs.ray.io/en/latest/tune/) docs and this [blog post](https://towardsdatascience.com/fast-hyperparameter-tuning-at-scale-d428223b081c).

**Comment by yhcao6** [comment]
Yes, you can find them in the evaluation function of the corresponding dataset. Take COCO as an example, the value of different metrics is stored in `eval_results`:
https://github.com/open-mmlab/mmdetection/blob/43b1909221179395ebd36edd24540940274ab9c9/mmdet/datasets/coco.py#L527-L541

**Comment by borgarpa** [comment]
Thank you for your response! 

Ray Tune requires the train function to be modified in order to include a logger, which will extract `eval_results` each epoch. Can I modify train function in order to do that? Maybe through a custom hook?

**Comment by yhcao6** [comment]
Yes, you can access the `eval_results` via some hooks, you can refer to details here: 
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py

**Comment by ipa-foj** [comment]
@borgarpa Did you ever implement this functionality? I am looking for the same, would be cool to get some insights into that

**Comment by christianhi123** [comment]
Are there some updates here? @ipa-foj @borgarpa Would appreciate some waypointers 👍
