### ISSUE TITLE
mAP is TOO bad

### ISSUE THREAD

**Issue by OneBella** [open-mmlab/mmdetection#4286]
On my own data set, the mAP of classic models such as Faster is very poor, but the result of looking at the picture is okay, why is it so?I think most of the detections are correct. Why is mAP only 60+ and the other only 30+

**Comment by yhcao6** [comment]
Lol, mAP 60+ is not too bad right. When you see very poor, which baseline you compare to?

**Comment by OneBella** [comment]
Thank you for your reply~
I see the mAP of Faster （ResNet-101）or ssd e.g. of other papers can reach 80~90 in the RSOD or UCAS-AOD datasets.&nbsp;I tried many network models of mmdetection:RSOD, 60+, UCAS-AOD 30+.&nbsp;
It might be because I only made fine-tunings.&nbsp;I also read the code of the relevant part of mmdetection,but I don’t know why....


Maybe you can give me some suggestions.


Best Reargs






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 中午11:04
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"青青陌上桑"<1060627557@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] mAP is TOO bad (#4286)





 
Lol, mAP 60+ is not too bad right. When you see very poor, which baseline you compare to?

**Comment by yhcao6** [comment]
I have never tried on RSOD or UCAS-AOD dataset. But I guess you need to change some hyper-parameters or setting to reach the same performance in the paper.
