### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Chasing987** [open-mmlab/mmdetection#4289]
hello!when i use the code of v2.3,traing voc2007,it just only train 1 epoch and then appear this error.like this:
`2020-12-11 23:05:43,999 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4952/4952, 20.8 task/s, elapsed: 238s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 154, in <module>
    main()
  File "tools/train.py", line 150, in main
    meta=meta)
  File "/home/csu/Yehaizi/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/csu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/csu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 46, in train
    self.call_hook('after_train_epoch')
  File "/home/csu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 298, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/csu/Yehaizi/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 28, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/csu/Yehaizi/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 32, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/csu/Yehaizi/mmdetection/mmdet/datasets/voc.py", line 72, in evaluate
    logger=logger)
  File "/home/csu/Yehaizi/mmdetection/mmdet/core/evaluation/mean_ap.py", line 388, in eval_map
    mean_ap, eval_results, dataset, area_ranges, logger=logger)
  File "/home/csu/Yehaizi/mmdetection/mmdet/core/evaluation/mean_ap.py", line 451, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: list index out of range
`could you tell me what happen and how to solve this problem?TKS! @anurag1paul @hachreak @DXist @ramkakarala @tjsongzw @hellock @v-qjqs @ALL

**Comment by natures66** [comment]
I met the same problem, did you solve it? I trained the model a few weeks ago it's okay but today appear this error

**Comment by natures66** [comment]
> I met the same problem, did you solve it? I trained the model a few weeks ago it's okay but today appear this error

I found what's wrong. I modified the config for my dataset, in config.py I rewrite the model and place it at the end of the file and then I met this error. Move the model = [...] to the top this error disappeared

**Comment by Atom-Jinny** [comment]
> > I met the same problem, did you solve it? I trained the model a few weeks ago it's okay but today appear this error
> 
> I found what's wrong. I modified the config for my dataset, in config.py I rewrite the model and place it at the end of the file and then I met this error. Move the model = [...] to the top this error disappeared

maybe it doesn't work for me .
I meet the same error ,here is my error report
```
021-01-06 08:34:53,667 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 30/30, 24.0 task/s, elapsed: 1s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 181, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 143, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 162, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/mmdetection/mmdet/datasets/voc.py", line 76, in evaluate
    logger=logger)
  File "/mmdetection/mmdet/core/evaluation/mean_ap.py", line 399, in eval_map
    mean_ap, eval_results, dataset, area_ranges, logger=logger)
  File "/mmdetection/mmdet/core/evaluation/mean_ap.py", line 462, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: list index out of range
```
my config is faster_rcnn_r50_fpn_1x,and I modified some setting, 
```
_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py', '../_base_/datasets/voc0712.py',
    '../_base_/default_runtime.py'
]
model = dict(roi_head=dict(bbox_head=dict(num_classes=2)))

data_root = 'data/VOCdevkit/'
dataset_type = 'VOCDataset'

train_pipeline = [dict(type='Resize', img_scale=(1024, 1024), keep_ratio=True)]
test_pipeline = [dict(img_scale=(1024, 1024))]
data = dict(
    train=dict(
        dataset=dict(
            ann_file= data_root + 'VOC2007/ImageSets/Main/train.txt',
            img_prefix=data_root + 'VOC2007/'
        )),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/val.txt',
        img_prefix=data_root + 'VOC2007/'))
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
# actual epoch = 3 * 3 = 9
lr_config = dict(policy='step', step=[3])
# runtime settings
total_epochs = 40  # actual epoch = 4 * 3 = 12

```
the progamme show that it finishes the training and begin to value.The error happens about mean_ap.py.I guess maybe the dataloaders making the error . Hope a perfect ways to solve it

**Comment by Atom-Jinny** [comment]
> > > I met the same problem, did you solve it? I trained the model a few weeks ago it's okay but today appear this error
> > 
> > 
> > I found what's wrong. I modified the config for my dataset, in config.py I rewrite the model and place it at the end of the file and then I met this error. Move the model = [...] to the top this error disappeared
> 
> maybe it doesn't work for me .
> I meet the same error ,here is my error report
> 
> ```
> 021-01-06 08:34:53,667 - mmdet - INFO - Saving checkpoint at 1 epochs
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 30/30, 24.0 task/s, elapsed: 1s, ETA:     0sTraceback (most recent call last):
>   File "tools/train.py", line 185, in <module>
>     main()
>   File "tools/train.py", line 181, in main
>     meta=meta)
>   File "/mmdetection/mmdet/apis/train.py", line 150, in train_detector
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
>     self.call_hook('after_train_epoch')
>   File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 143, in after_train_epoch
>     key_score = self.evaluate(runner, results)
>   File "/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 162, in evaluate
>     results, logger=runner.logger, **self.eval_kwargs)
>   File "/mmdetection/mmdet/datasets/voc.py", line 76, in evaluate
>     logger=logger)
>   File "/mmdetection/mmdet/core/evaluation/mean_ap.py", line 399, in eval_map
>     mean_ap, eval_results, dataset, area_ranges, logger=logger)
>   File "/mmdetection/mmdet/core/evaluation/mean_ap.py", line 462, in print_map_summary
>     label_names[j], num_gts[i, j], results[j]['num_dets'],
> IndexError: list index out of range
> ```
> 
> my config is faster_rcnn_r50_fpn_1x,and I modified some setting,
> 
> ```
> _base_ = [
>     '../_base_/models/faster_rcnn_r50_fpn.py', '../_base_/datasets/voc0712.py',
>     '../_base_/default_runtime.py'
> ]
> model = dict(roi_head=dict(bbox_head=dict(num_classes=2)))
> 
> data_root = 'data/VOCdevkit/'
> dataset_type = 'VOCDataset'
> 
> train_pipeline = [dict(type='Resize', img_scale=(1024, 1024), keep_ratio=True)]
> test_pipeline = [dict(img_scale=(1024, 1024))]
> data = dict(
>     train=dict(
>         dataset=dict(
>             ann_file= data_root + 'VOC2007/ImageSets/Main/train.txt',
>             img_prefix=data_root + 'VOC2007/'
>         )),
>     val=dict(
>         type=dataset_type,
>         ann_file=data_root + 'VOC2007/ImageSets/Main/val.txt',
>         img_prefix=data_root + 'VOC2007/'))
> # optimizer
> optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
> optimizer_config = dict(grad_clip=None)
> # learning policy
> # actual epoch = 3 * 3 = 9
> lr_config = dict(policy='step', step=[3])
> # runtime settings
> total_epochs = 40  # actual epoch = 4 * 3 = 12
> ```
> 
> the progamme show that it finishes the training and begin to value.The error happens about mean_ap.py.I guess maybe the dataloaders making the error . Hope a perfect ways to solve it

[](https://shliang.blog.csdn.net/article/details/106258366?utm_medium=distribute.pc_relevant.none-task-blog-searchFromBaidu-2.not_use_machine_learn_pai&depth_1-utm_source=distribute.pc_relevant.none-task-blog-searchFromBaidu-2.not_use_machine_learn_pai)

I solve this problem

**Comment by Atom-Jinny** [comment]
[](https://shliang.blog.csdn.net/article/details/106258366?utm_medium=distribute.pc_relevant.none-task-blog-searchFromBaidu-2.not_use_machine_learn_pai&depth_1-utm_source=distribute.pc_relevant.none-task-blog-searchFromBaidu-2.not_use_machine_learn_pai)
I solve the problem and work now

**Comment by cupcakefromchina** [comment]
> I solve the problem and work now

How can you solve this problem? Can you share your methods.

**Comment by Atom-Jinny** [comment]
> > I solve the problem and work now
> 
> How can you solve this problem? Can you share your methods.

最新版本的mmdetection2.0 （v2.0.0版本）环境搭建、训练自己的数据集、测试以及常见错误集合
[]((https://shliang.blog.csdn.net/article/details/106258366))
maybe，this blog can help you.
First, you should know ,in version2.0,you don't need to num+1 in the net structure(.py).
then ,you should know that ,you need to run `python3 setup.py install` every times when you upgrade the other python file.(eg, /mmdection/mmdet/datasets/voc.py)

then ,when I only have one classes,I sign the script end of the ',',like  the voc.py----    CLASSES = ('tree',)

Hope can help you .Good luck to you.

**Comment by Atom-Jinny** [comment]
> > I solve the problem and work now
> 
> How can you solve this problem? Can you share your methods.


最新版本的mmdetection2.0 （v2.0.0版本）环境搭建、训练自己的数据集、测试以及常见错误集合https://shliang.blog.csdn.net/article/details/106258366
[]((https://shliang.blog.csdn.net/article/details/106258366))
maybe，this blog can help you.
First, you should know ,in version2.0,you don't need to num+1 in the net structure(.py).
then ,you should know that ,you need to run `python3 setup.py install` every times when you upgrade the other python file.(eg, /mmdection/mmdet/datasets/voc.py)

then ,when I only have one classes,I sign the script end of the ',',like  the voc.py----    CLASSES = ('tree',)

Hope can help you .Good luck to you.
