### ISSUE TITLE
I write a CSVDataset class inherited from CustomDataset, then add it to file (__init__.py ）in the folder（datasets） ,  but still don't work（AttributeError: module 'mmdet.datasets' has no attribute 'CSVDataset'）, please help.

### ISSUE THREAD

**Issue by hustzwen** [open-mmlab/mmdetection#429]

**Comment by hustzwen** [comment]
The running environment was wrong yesterday, and now it works and achieves a good result.  useful and impressive project. thanks a lot.

**Comment by Joker316701882** [comment]
@hustzwen 
Hi, could you provide more information about "running environment wrong"?
Because I'm facing the same problem with you.

Thanks~

**Comment by 237014845** [comment]
@Joker316701882  I'm facing the same problem with you.

**Comment by Joker316701882** [comment]
@237014845 
```
python(3) setup.py install
```
or
```
export PYTHONPATH=`pwd`:$PYTHONPATH
```
will work.

**Comment by hellock** [comment]
If you use `python(3) setup.py develop` instead of `python(3) setup.py install`, then you don't need to run the setup command each time you make some modifications.
