### ISSUE TITLE
The qusetion of  /mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

### ISSUE THREAD

**Issue by liuyanzhi1214** [open-mmlab/mmdetection#4291]
ImportError: /home/e706/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE
my environment：
ubuntu18.04
python 3.7
cuda10.1
pytorch1.7.1
mmdet2.7.0
How to solve this error？ORZ

**Comment by ZwwWayne** [comment]
Please check the [documentation about CUDA/Pytorch environment](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment).

**Comment by ray-401** [comment]
Did u solve this problem?

**Comment by ranch-hands** [comment]
> Did u solve this problem?

no did you?
pls help us @liuyanzhi1214 @ZwwWayne @yhcao6 @ray401

**Comment by diptanshu-singh** [comment]
Facing the same error.. Any ideas/ workaround for this ?

**Comment by CharlesNJohn** [comment]
> Please check the [documentation about CUDA/Pytorch environment](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment).

I couldn't run this
python mmdet/utils/collect_env.py

**Comment by Wunaiq** [comment]
> mmcv is heavily relying on the versions of the PyTorch and Cuda installed. I had the same issue and noticed the installed mmcv is not for my current PyTorch version. You should reinstall it using: `pip install --upgrade mmcv-full==${MMCV} -f https://download.openmmlab.com/mmcv/dist/cu${CUDA}/torch${PYTORCH}/index.html` where you should replace or set ${MMCV}, ${CUDA}, and ${PYTORCH} with their versions. Pytorch and CUDA should be based on the installed versions. Also, ${CUDA} is in 101 for CUDA 10.1 and so on.

This worked! Thank you very much！

**Comment by IamSVP94** [comment]
if yo use conda:
`conda install -c conda-forge mmcv-full`

**Comment by noreenanwar** [comment]
I am facing the same error after doing that

> if yo use conda:
> `conda install -c conda-forge mmcv-full`

**Comment by haosong001** [comment]
i SOLVED it!
my current: mmcv==1.3.15
it solved by: mim install mmcv-full == 1.3.15
so mmcv change to mmcv-full. yay!

**Comment by Nadia-Chen** [comment]
Same here, refer to the document: https://mmcv.readthedocs.io/zh-cn/latest/get_started/installation.html
reinstall mmcv with proper version according to your torch and cuda version, and the problem solved.
Note: In MMCV-v2.x, mmcv-full is rename to mmcv.
![image](https://github.com/open-mmlab/mmdetection/assets/67884201/a415c7dc-4022-4cc2-84eb-06fb2bb35109)

**Comment by mohamedsaeed8223** [comment]
i faced a similar error but it was originating from python3.8 which the installation guide had in the conda env creation line

this also caused no other mmcv<2.2.0 to be able to finish wheel building during installation

trying once more using python 3.7 and pytorch==1.13.1 fixed both issues

**Comment by Ftoy99** [comment]
I had the same issue . I fixed this by 
Running my scripts with LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6  or your path.
This is because i had an old libstdc++.so.6 in my conda environment and it had priority over my new system one.

I built mmcv 1.6.5 with gcc11 from scratch from their github

**Comment by danielgf0824** [comment]
I had the same problem, and the reason is that after installing the mmcv, I uninstall and re-install torch of another version.
So I uninstalled mmcv, clean the cache by `pip cache purge`， and re-install mmcv
Problem fixed
