### ISSUE TITLE
ImportError: cannot import name 'init_dist' from 'mmdet.apis' 

### ISSUE THREAD

**Issue by VIROBO-15** [open-mmlab/mmdetection#4293]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?
bash ./tools/dist_train.sh configs/point_set_anchor_pose/8GPUs_points_set_anchor_pose_HRNetw32_115E.py 8 ${YOUR_WORK_DIR}
```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
Please update your mmdetection and mmcv

**Comment by VIROBO-15** [comment]
i already have updated version
Torchvision-0.8.2
open-CV-  4.4.0
MMCV- 1.2.1
MMCV COMPILER: GCC: 9.3

**Comment by yhcao6** [comment]
`init_dist` is moved to MMCV now, please check here.
https://github.com/open-mmlab/mmcv/blob/02920db2ccfea1fc2e789da485b6d5607af23ec2/mmcv/runner/dist_utils.py#L16-L26

**Comment by VIROBO-15** [comment]
How can i solve this problem?

**Comment by yhcao6** [comment]
import `init_dist` from`mmcv.runner` instead of `mmdet.apis`
