### ISSUE TITLE
Does the project support Fast RCNN

### ISSUE THREAD

**Issue by tengerye** [open-mmlab/mmdetection#43]
Hi, does the repository support fast rcnn?

**Comment by OceanPang** [comment]
Hi @tengerye , please find attach `configs/fast_rcnn_r50_fpn_1x.py` and `configs/fast_mask_rcnn_r50_fpn_1x.py`, which support fast rcnn and fast mask rcnn. You can extract rpn proposals with `configs/rpn_r50_fpn_1x.py`, and the proposal file will be released later.

**Comment by tengerye** [comment]
Hi @OceanPang , thank you for your kind reply. 

How would I feed my own proposals (e.g. from selective search) to the code please?

**Comment by hellock** [comment]
@tengerye Sorry for the late reply. You can specify the proposal file in the config file, see https://github.com/open-mmlab/mmdetection/blob/HEAD/configs/fast_rcnn_r50_fpn_1x.py#L65.
The content of the proposal file should be a list of nx4 or nx5 numpy arrays.

**Comment by ZengyuanYu** [comment]
> Hi @tengerye , please refer to `configs/fast_rcnn_r50_fpn_1x.py` and `configs/fast_mask_rcnn_r50_fpn_1x.py`, which support fast rcnn and fast mask rcnn. You can extract rpn proposals with `configs/rpn_r50_fpn_1x.py`, and the proposal files will be released later.

@hellock @OceanPang Hi, Dalaoes! So I use `config/rpn_r50_fpn_1x.py` to train images data but also get `*.pth`weights file，the `proposals pkl file` should make for use selective search?  Do you have some scripts to generate this in mmdetection?

**Comment by hellock** [comment]
@ZengyuanYu You can use the trained RPN model to get proposals. Just run scripts like `python tools/test.py config/rpn_r50_fpn_1x.py <CHECKPOINT_FILE> --gpus 8 --out val_proposals.pkl` to obtain proposal file.

**Comment by ElegantLin** [comment]
@hellock Thanks, Kai. I have solved the problem according to this page. Please ignore my previous issue about fast rcnn :).
