### ISSUE TITLE
question about extra_aug(orign used in ssd) in faster rcnn?

### ISSUE THREAD

**Issue by donglee-afar** [open-mmlab/mmdetection#430]
When i add the random crop in extra_aug into faster rcnn,
the final map has dropped，
has someone meet the problem?  
here in the config file

data = dict(
    imgs_per_gpu=1,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        img_scale=[(800,1600),(1200,1600)],
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=False,
        with_crowd=True,
        with_label=True,
        extra_aug=dict(random_crop=dict(
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9), min_crop_size=0.3))),

**Comment by donglee-afar** [comment]
@hellock  , is there any problem in my config file? thank you!

**Comment by donglee-afar** [comment]
i do some experiments about extra augment,
when i  change the shape of the image(rotate 90), the result will drop,
if the augment don't change the shape(rotate 90 twice->flip) , it will not affect the result

**Comment by hellock** [comment]
It is normal if the same extra_aug does not help. Faster R-CNN and SSD are very different and not all augmentations works. The hyper-parameters also matter.
