### ISSUE TITLE
How to add rules to detect two exclusive classes

### ISSUE THREAD

**Issue by hali6779** [open-mmlab/mmdetection#4301]
Hi,
I am doing a object detection project for two exclusive classes A and B. For some ground truth image both two classes will be detected.
May I know is there any way to add some rules on evaluation process, like once class B is detected, all the class A proposals will be eliminated to increase the mAP. I have checked the documentation but didn't find any relevant resource, any suggestions would be appreciated. Thanks in advance.

**Comment by yhcao6** [comment]
Yes, you can modify the post process so that upon an instance of a certain class is detected for an image then you discard the other artificially. The other way is to add a loss to constrain the model to predict only one class.
