### ISSUE TITLE
DERT device error when run inference_detector in mmdetecion

### ISSUE THREAD

**Issue by pedrozamboni** [open-mmlab/mmdetection#4302]
Hi everyone,

When a run the inference_detector to DERT algorithm, I got this error message:

AssertionError  Traceback (most recent call last)

<ipython-input-7-e6cf47609faf> in <module>()
      6 cfg.data.test.test_mode = True
      7 
----> 8 modelx = init_detector(cfg, '/content/drive/MyDrive/Doutorado/tree detction/dert0/epoch_24.pth', device='cuda')
      9 
     10 # test a single image

9 frames

/content/mmdetection/mmdet/models/dense_heads/transformer_head.py in __init__(self, num_classes, in_channels, num_fcs, transformer, positional_encoding, loss_cls, loss_bbox, loss_iou, train_cfg, test_cfg, **kwargs)
    104         class_weight = loss_cls.get('class_weight', None)
    105         if class_weight is not None:
--> 106             assert isinstance(class_weight, float), 'Expected ' \
    107                 'class_weight to have type float. Found ' \
    108                 f'{type(class_weight)}.'

AssertionError: Expected class_weight to have type float. Found <class 'torch.Tensor'>.

The device paramenter of init_detector is default ('cuda:0') and distributed=False. Can you help me?

**Comment by ZwwWayne** [comment]
Please @v-qjqs have a check and fix the issue.

**Comment by v-qjqs** [comment]
Hi, as the error message suggests, 'class_weight' in the config file should be type float, not Tensor. What's your detr config?

**Comment by saadyousuf45** [comment]
Anyone found the solution
?

**Comment by saadyousuf45** [comment]
just add this before infering:
cfg.model.bbox_head.loss_cls.class_weight = float(1.0)
should be good IA.
