### ISSUE TITLE
SSD train_cfg Example

### ISSUE THREAD

**Issue by bjanfeshan** [open-mmlab/mmdetection#4305]
Hi, I am trying to run ssd300_coco on my dataset and it seems I need to provide `train_cfg` and `test_cfg`. Can you please provide an example of that.

Thanks!

**Comment by ZwwWayne** [comment]
The example is in the [config of SSD](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/ssd300.py#L32).

**Comment by bjanfeshan** [comment]
thanks!
