### ISSUE TITLE
Out of Disk Space

### ISSUE THREAD

**Issue by KochPJ** [open-mmlab/mmdetection#4308]
Hey,
I am training on my small Custom dataset. Therefore, I train for >100 epochs. The training makes a checkpoint every epoch, which leads to a disk usage of 330mb * 100 epochs for faster-rcnn. Thereby I ran out of space on my hard disk since I have a small SSD and not much space left. I would like to only save the best model checkpoint or save only every x epoch. Are there any settings I can use for that?

Best,
Paul

**Comment by ZwwWayne** [comment]
You can set the saving interval of checkpoint hook as indicated [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py#L32). An example of config is as below
```python
checkpoint_config = dict(interval=10)
```
