### ISSUE TITLE
error when backward

### ISSUE THREAD

**Issue by zhaoxin111** [open-mmlab/mmdetection#4310]
In ROI extractor layer, I want to add same extra feamaps to the original roi feature.
I encountered a strange problem. When I use torch.cat to splice two tensors, I will encounter the following error, but adding the two tensors directly will not report an error. Why?
`class SingleRoIExtractor_expandROI(SingleRoIExtractor):
    """Extract RoI features from a single level feature map.

    If there are multiple input feature levels, each RoI is mapped to a level
    according to its scale. The mapping rule is proposed in
    `FPN <https://arxiv.org/abs/1612.03144>`_.

    Args:
        roi_layer (dict): Specify RoI layer type and arguments.
        out_channels (int): Output channels of RoI layers.
        featmap_strides (int): Strides of input feature maps.
        finest_scale (int): Scale threshold of mapping to level 0. Default: 56.
    """

    def __init__(self,
                 roi_layer,
                 out_channels,
                 featmap_strides,
                 finest_scale=56,
                 use_expand_roi=False):
        super(SingleRoIExtractor_expandROI, self).__init__(roi_layer, out_channels,
                                                 featmap_strides)
        self.finest_scale = finest_scale
        self.use_expand_roi = use_expand_roi
        self.pool = torch.nn.AdaptiveAvgPool2d(7)
        self.conv = ConvModule(out_channels*2,out_channels,3,1,1)

    @force_fp32(apply_to=('feats', ), out_fp16=True)
    def forward(self, feats, rois, roi_scale_factor=None):
        """Forward function."""
        out_size = self.roi_layers[0].output_size
        num_levels = len(feats)
        if not self.use_expand_roi:
            roi_feats = feats[0].new_zeros(
                rois.size(0), self.out_channels, *out_size)
        else:
            roi_feats = feats[0].new_zeros(
                rois.size(0), self.out_channels*2, *out_size)
        # TODO: remove this when parrots supports
        if torch.__version__ == 'parrots':
            roi_feats.requires_grad = True

        if self.use_expand_roi:
            context = []
            for feat in feats:
                context.append(self.pool(feat))

        if num_levels == 1:
            if len(rois) == 0:
                return roi_feats
            return self.roi_layers[0](feats[0], rois)
        batch_size = feats[0].shape[0]
        target_lvls = self.map_roi_levels(rois, num_levels)
        if self.use_expand_roi:
            rois_expand = self.roi_rescale(rois,2)
        if roi_scale_factor is not None:
            rois = self.roi_rescale(rois, roi_scale_factor)
        
        for i in range(num_levels):
            inds = target_lvls == i
            if inds.any():
                rois_ = rois[inds, :]
                roi_feats_t = self.roi_layers[i](feats[i], rois_)
                if self.use_expand_roi:
                    # expand rois
                    rois_expand_ = rois_expand[inds, :]
                    roi_feats_expand_t = self.roi_layers[i](feats[i], rois_expand_)
                    roi_feats[inds] = torch.cat([roi_feats_t,roi_feats_expand_t],1)
                    # roi_feats[inds] =  roi_feats_t + roi_feats_expand_t
                else:
                    roi_feats[inds] = roi_feats_t
            else:
                roi_feats += sum(
                    x.view(-1)[0]
                    for x in self.parameters()) * 0. + feats[i].sum() * 0.
        if self.use_expand_roi:
            roi_feats = self.conv(roi_feats)
        
        return roi_feats`

Traceback (most recent call last):
  File "./tools/train.py", line 178, in <module>
    main()
  File "./tools/train.py", line 174, in main
    meta=meta)
  File "/home/zhaoxin/workspace/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zhaoxin/workspace/mmcv/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhaoxin/workspace/mmcv/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/home/zhaoxin/workspace/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhaoxin/workspace/mmcv/mmcv/runner/hooks/optimizer.py", line 27, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/zhaoxin/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhaoxin/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: grad_output must be contiguous

**Comment by EwardJohn** [comment]
@zhaoxin111 Hi, have you solved it? When i chenge the single_level_roi_extractor.py,i encounter the same error. How do you solved it? Thanks.

**Comment by zhaoxin111** [comment]
> @zhaoxin111 Hi, have you solved it? When i chenge the single_level_roi_extractor.py,i encounter the same error. How do you solved it? Thanks.

Not yet. :(

**Comment by ZwwWayne** [comment]
The addition will not make the tensor incontiguous, but concatenation and split will. You need to add x.contiguous() in your code.

**Comment by zhaoxin111** [comment]
> The addition will not make the tensor incontiguous, but concatenation and split will. You need to add x.contiguous() in your code.

emmm. The addition didn't make any error, but the cat operation crash the code.
Besides, I have tried add x.contiguous() in my code, but it didn't handle the problem.

**Comment by billqxg** [comment]
> > The addition will not make the tensor incontiguous, but concatenation and split will. You need to add x.contiguous() in your code.
> 
> emmm. The addition didn't make any error, but the cat operation crash the code.
> Besides, I have tried add x.contiguous() in my code, but it didn't handle the problem.

I also met this kind of problem. Perhaps this results from the roialign operation in MMCV.

**Comment by zhaoxin111** [comment]
> > > The addition will not make the tensor incontiguous, but concatenation and split will. You need to add x.contiguous() in your code.
> > 
> > 
> > emmm. The addition didn't make any error, but the cat operation crash the code.
> > Besides, I have tried add x.contiguous() in my code, but it didn't handle the problem.
> 
> I also met this kind of problem. Perhaps this results from the roialign operation in MMCV.

Have you solve the problem？
