### ISSUE TITLE
Please, add information about CPU-only compatibility for all methonds and models

### ISSUE THREAD

**Issue by ioctl-user** [open-mmlab/mmdetection#4311]
I have tried some models and methods in conjunction with mmpose.

As for now, DCN, Resnet + Cascade Mask RCN, DetectoRS and GFL+dcnv are not working on CPU.
Is it possible to add information about CPU-only-compatibility to these and others README.md?

**Comment by v-qjqs** [comment]
Hi @ioctl-user, did you mean these models do not be supported for inference mode on CPU?

**Comment by ioctl-user** [comment]
Sorry for bad description.

I mean these models cannot be used without CUDA GPU, i.e. on systems with only CPU as computing unit.

**Comment by ZwwWayne** [comment]
Thanks for your kind suggestion. We will update this information in the future release.
