### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Chan-Sun** [open-mmlab/mmdetection#4312]
I was trying to run /demo/image_demo.py to valid installation. but got errors as follow:

>Traceback (most recent call last):
>File "image_demo.py", line 3, in <module>
>from mmdet.apis import inference_detector, init_detector, show_result_pyplot
>File "/home/hustwen/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
>from .inference import (async_inference_detector, inference_detector,
>File "/home/hustwen/mmdetection/mmdet/apis/inference.py", line 7, in <module>
>from mmcv.ops import RoIPool
>File "/home/hustwen/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
>from .bbox import bbox_overlaps
>File "/home/hustwen/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
>ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
>File "/home/hustwen/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
>ext = importlib.import_module('mmcv.' + name)
>File "/home/hustwen/anaconda3/envs/mmdet/lib/python3.7/importlib/__init__.py", line 127, in import_module
>return _bootstrap._gcd_import(name[level:], package, level)
>ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

I have upgrade CUDA from 9.0 to 10.1, and rewrite the environment PATH.

Pytorch(pip install from pytorch.org)、CUDA、mmcv、mmdet and gcc version (on Ubuntu 16.04): 

> pytorch                   1.7.1            py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
> torchaudio              0.7.2           py37                                                         pytorch
> torchvision              0.8.2           py37_cu101                                            pytorch

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Sun_Jul_28_19:07:16_PDT_2019
> Cuda compilation tools, release 10.1, V10.1.243

> mmcv-full                 1.2.1                     <pip>

> mmdet __version__ = '2.7.0'

> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Comment by Chan-Sun** [comment]
also cudnn.is_available() works fine
>import torch
>a = torch.tensor(1.)
>a.cuda
><built-in method cuda of Tensor object at 0x7f70c0139320>
>a.cuda()
>tensor(1., device='cuda:0')
>from torch.backends import cudnn
>cudnn.is_available()
>True
>cudnn.is_acceptable(a.cuda())
>True

**Comment by Chan-Sun** [comment]
I checked libcudart, but only got libchudart.so.10.1
```
(mmdet) hustwen@TitanXP:~$ function lib_installed() { /sbin/ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep $1; }
(mmdet) hustwen@TitanXP:~$ function check() { lib_installed $1 && echo "$1 is installed" || echo "ERROR: $1 is NOT installed"; }
(mmdet) hustwen@TitanXP:~$ check libcuda
        libcudart.so.10.1 -> libcudart.so.10.1.243
        libcuda.so.1 -> libcuda.so.430.64
libcuda is installed
(mmdet) hustwen@TitanXP:~$ check libcudart
        libcudart.so.10.1 -> libcudart.so.10.1.243
libcudart is installed
```

**Comment by ma3252788** [comment]
> I checked libcudart, but only got libchudart.so.10.1
> 
> ```
> (mmdet) hustwen@TitanXP:~$ function lib_installed() { /sbin/ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep $1; }
> (mmdet) hustwen@TitanXP:~$ function check() { lib_installed $1 && echo "$1 is installed" || echo "ERROR: $1 is NOT installed"; }
> (mmdet) hustwen@TitanXP:~$ check libcuda
>         libcudart.so.10.1 -> libcudart.so.10.1.243
>         libcuda.so.1 -> libcuda.so.430.64
> libcuda is installed
> (mmdet) hustwen@TitanXP:~$ check libcudart
>         libcudart.so.10.1 -> libcudart.so.10.1.243
> libcudart is installed
> ```

I think you should install pytorch with cuda10.x

**Comment by Chan-Sun** [comment]
> > I checked libcudart, but only got libchudart.so.10.1
> > ```
> > (mmdet) hustwen@TitanXP:~$ function lib_installed() { /sbin/ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep $1; }
> > (mmdet) hustwen@TitanXP:~$ function check() { lib_installed $1 && echo "$1 is installed" || echo "ERROR: $1 is NOT installed"; }
> > (mmdet) hustwen@TitanXP:~$ check libcuda
> >         libcudart.so.10.1 -> libcudart.so.10.1.243
> >         libcuda.so.1 -> libcuda.so.430.64
> > libcuda is installed
> > (mmdet) hustwen@TitanXP:~$ check libcudart
> >         libcudart.so.10.1 -> libcudart.so.10.1.243
> > libcudart is installed
> > ```
> 
> I think you should install pytorch with cuda10.x

**Comment by Chan-Sun** [comment]
> > > I checked libcudart, but only got libchudart.so.10.1
> > > ```
> > > (mmdet) hustwen@TitanXP:~$ function lib_installed() { /sbin/ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep $1; }
> > > (mmdet) hustwen@TitanXP:~$ function check() { lib_installed $1 && echo "$1 is installed" || echo "ERROR: $1 is NOT installed"; }
> > > (mmdet) hustwen@TitanXP:~$ check libcuda
> > >         libcudart.so.10.1 -> libcudart.so.10.1.243
> > >         libcuda.so.1 -> libcuda.so.430.64
> > > libcuda is installed
> > > (mmdet) hustwen@TitanXP:~$ check libcudart
> > >         libcudart.so.10.1 -> libcudart.so.10.1.243
> > > libcudart is installed
> > > ```
> > 
> > 
> > I think you should install pytorch with cuda10.x

yeah, i just follow the instructions in the pytorch.org, choose pytorch version with cuda 10.1. 
but the error seems to have connection with cuda9.0(?), and i can't find where the problem is

**Comment by ZwwWayne** [comment]
It seems that the MMCV you installed is incompatible with the torch and CUDA environment. Please uninstall MMCV and install the correct version for your environment. The commands of MMCV for different torch/cuda environment is in the [doc](https://mmcv.readthedocs.io/en/latest/#installation).
