### ISSUE TITLE
How to use CPU to train temporarily?

### ISSUE THREAD

**Issue by ma3252788** [open-mmlab/mmdetection#4313]
I have an error when I use GPU for training, but I can't accurately locate the error location. So I want to use the CPU temporarily for training. How can I achieve this if I don't recompile the CPU version of mmdetection?

**Comment by xvjiarui** [comment]
Hi @ma3252788 
You may use single GPU to debug.

**Comment by hellock** [comment]
CPU training is not supported for now, only CPU inference is supported.
