### ISSUE TITLE
SOLOv2 implementation

### ISSUE THREAD

**Issue by Tiberius131** [open-mmlab/mmdetection#4315]
**Describe the feature**

**Motivation**
There is a recent paper https://arxiv.org/abs/2003.10152, which is very helpful for instance segmentation.

**Related resources**
There is an official implementation: https://github.com/WXinlong/SOLO but many people have issues getting it running. Since mmdetection is easy to install, it would be a great addition to this project.

**Comment by ZwwWayne** [comment]
SOLOv1 is in PR https://github.com/open-mmlab/mmdetection/pull/3447. For SOLOv2, we may support it in the future. PRs are also welcomed.
