### ISSUE TITLE
More information about datasets used in training

### ISSUE THREAD

**Issue by Angel-Jia** [open-mmlab/mmdetection#4318]
In detectron2, the images number of each category in datasets were printed before traning. Balancing classes is easy with those information.However it is inconvenient to get those information in mmdetection, especically when 'ConcatDataset' and 'RepeatDataset' were used.
Adding a module to give the information of dataset used in training would help training process.

**Comment by ZwwWayne** [comment]
Thanks for your suggestion. We will add this part in the future.

**Comment by ZwwWayne** [comment]
Resolved in https://github.com/open-mmlab/mmdetection/issues/4318
