### ISSUE TITLE
How to use show_result() function in detectors/rpn.py?

### ISSUE THREAD

**Issue by DarkstartsUp** [open-mmlab/mmdetection#432]
I want to only use RPN and show RPN proposals on a image. Could somebody please teach me how to use this api? I want some codes just like example about testing image in readme.md. 
thx!

**Comment by hellock** [comment]
You may refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/rpn.py#L79

**Comment by DarkstartsUp** [comment]
> You may refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/rpn.py#L79

@hellock Thanks for your reply! Yes, I saw this function. But I don't know how to use it: How to construct a pure RPN model and load checkpoint? And how to prepare data and result this show_result() function need?

So I am wondering if you could provide some example code for using this function? Just like example about testing faster r-cnn detector on an image in readme.md.

Thank you very much!

**Comment by DarkstartsUp** [comment]
I guess this api can be used in tools/test.py. Command input 'python3 tools/test.py configs/any_rpn_config_path.py any_rpn_checkpoint.pth' and program will call show_result() function of rpn automatically.
