### ISSUE TITLE
How to draw correlation curve of IoU score and classification score in paper: Prime Sample Attention in Object Detection? 

### ISSUE THREAD

**Issue by black12357** [open-mmlab/mmdetection#4320]
Thank you for your great open source!
I wonder whether you can share the idea about how to make statistics of IoU score and classification score to draw the correlation curve in figure 4 of your paper: Prime sample attention in object detection?
![Selection_031](https://user-images.githubusercontent.com/51944439/102482847-30f4d580-40a7-11eb-95d4-e2c7c1111a15.png)

If it's possible, could you share the code?
Thank you so much!

**Comment by ZwwWayne** [comment]
Please @yhcao6  have a look on that.
