### ISSUE TITLE
Version download problem

### ISSUE THREAD

**Issue by ZYK266139** [open-mmlab/mmdetection#4323]
Hello, how do I download the 2.1 version now? Where is the download address?

**Comment by yhcao6** [comment]
https://github.com/open-mmlab/mmdetection/tree/v2.1.0

**Comment by kellenf** [comment]
![image](https://user-images.githubusercontent.com/19380638/102577507-23852d00-4133-11eb-8444-6c5e442330fa.png)
choose tag 2.1
