### ISSUE TITLE
Categories number mismatch in traning

### ISSUE THREAD

**Issue by Mabinogiysk** [open-mmlab/mmdetection#4327]
Given a dataset A which contains `num` categories，the model can be trained with `num_classes=num-1`. On v2.2.1, background label will be set to `num-1`:
mmdet/models/roi_heads/bbox_heads/bbox_head.py(line 93)
```
labels = pos_bboxes.new_full((num_samples, ), self.num_classes, dtype=torch.long)
```
The problem can be reproduced on v2.7.0. In my opinion, we should check categories number before training.

**Comment by ZwwWayne** [comment]
We will check num_classes before training. The convention of `num_classes` is in the [doc](https://mmdetection.readthedocs.io/en/latest/compatibility.html#codebase-conventions)
