### ISSUE TITLE
Why not use torch.round()?

### ISSUE THREAD

**Issue by lfydegithub** [open-mmlab/mmdetection#4328]
https://github.com/open-mmlab/mmdetection/blob/231387cd3f85a310f899cb5b4c948cd79787118d/mmdet/core/anchor/anchor_generator.py#L716
why not use torch.round() to replace torch.floor()?
because in `mmdet/core/bbox/coder/yolo_bbox_coder.py` line75~77:
```python
# Get outputs x, y
x_center_pred = (pred_bboxes[..., 0] - 0.5) * stride + x_center
y_center_pred = (pred_bboxes[..., 1] - 0.5) * stride + y_center
```
that means you use grid point (not cell) as the anchor center(x_center).
so if a gt_box center was (4.9, 5.1):
in torch.round: grid point (5, 5) should be responsibled;
in torch.floor: grid point (4, 5) should be responsibled, but it can't, because pred_bboxes[..., 0] - 0.5 ∈(-0.5, +0.5)
This confused me.
thx.

**Comment by ZwwWayne** [comment]
The implementation of YOLOv3 follows the original implementation. So maybe you are correct that there are some tweaks in the assignments.
