### ISSUE TITLE
How do I implement my own NMS into mmdetection?

### ISSUE THREAD

**Issue by talkingheadd** [open-mmlab/mmdetection#4329]
Hello everyone,

I am trying to implement a rescoring algorithm before NMS for video object detection. I am considering to run this algorithm and after that apply NMS. How do I get the bboxes before NMS during inference?

**Comment by talkingheadd** [comment]
Or is there a better way ?

**Comment by ZwwWayne** [comment]
You should modify the head of the model that you are using. The inference API is not for development.

**Comment by talkingheadd** [comment]
> You should modify the head of the model that you are using. The inference API is not for development.

Yeah, I see, thanks.  Actually, I figured out how to implement my nms and use it for models, I just need to give an additional input while testing, how should I do that?

**Comment by kellenf** [comment]
multiclass_nms

**Comment by JillianWangm** [comment]
Has anyone solved it? I wanna output bboxes before NMS, how should I do it?

**Comment by talkingheadd** [comment]
I did it. Just customize bbox_nms.py . Create your own dummy nms and use it
instead.

JillianWang <notifications@github.com>, 2 Mar 2021 Sal, 09:46 tarihinde
şunu yazdı:

**Comment by yangguang-v** [comment]
你好，请问一下，您的NWD/mmde/core/post_processing/wasserstein_nms.py中def wasserstein_nms_op这个函数为什么什么内容也没有就pass了，另外def wasserstein_nms和def batched_wasserstein_nms在哪里调用的，调用的时候是不是只选一个调用即可，我的代码是在测试的用的，我划分了train，val, test。
