### ISSUE TITLE
I modify CLASSES = ('aircraft',) in voc.py, but demo and eval result shows 'seroplane'?

### ISSUE THREAD

**Issue by Yuyang-01** [open-mmlab/mmdetection#433]
I modified CLASSES = ('.....') to CLASSES = ('aircraft',) in voc.py. I trained my own dataset.
But when i ran demo.py,test.py and voc_eval.py, the result label is named aeroplane? Why does this happen?

**Comment by wizholy** [comment]
i meat the same question. have you finish it?

**Comment by wizholy** [comment]
I resolved it. 
change the voc_classes() in mmdet/core/evaluation/classesnames.py

**Comment by wizholy** [comment]
when install the mmdetection, you shold use python setup.py develop

**Comment by Yuyang-01** [comment]
@wizholy i use python setup.py, the problem still exists. It seems that the project only supports the coco dataset class, but not the voc class.

**Comment by yx868868** [comment]
Have you solved this problem?

**Comment by lizxchen** [comment]
I met the same question , can you give some advise?

**Comment by hyd-520** [comment]
你解决这个问题了吗？

**Comment by hyd-520** [comment]
> Have you solved this problem?
兄弟你解决了吗？
