### ISSUE TITLE
3D tensors error while training DetectoRS on a custom dataset

### ISSUE THREAD

**Issue by TuanNguyenSKKU** [open-mmlab/mmdetection#4330]
Hello everyone,

After changing the path to a custom dataset, modify the num_classes and some necessary files, I used the command below for training a DetectoRS model:
python tools/train.py configs/detectors/detectors_htc_r50_1x_coco.py

But I have encountered an error like this.
![image](https://user-images.githubusercontent.com/55343855/102684848-6cb2ab00-421f-11eb-84de-359863af24f9.png)
The setup is mmdetection2.6.0, and everything is fine when I run the demo.py file.
I do not know how to deal with this. Please help me with more detail.
Thank you so much.

**Comment by xvjiarui** [comment]
Hi @TuanNguyenSKKU 
The error is not related to DeteroRS. 
Please check the shape of your annotation. 
It seems that your annotation shape is not correct.

**Comment by TuanNguyenSKKU** [comment]
hi @xvjiarui 
The problem is that I was successful with mmdetection2.0.0 for using the same dataset (annotated instances).
I have to switch to mmdetection2.6.0 because of without detectors function in mmdetection2.0.0.
So I think my annotation is fine.

**Comment by TuanNguyenSKKU** [comment]
I got it. The solution is removing all semantic parts in the config file.
