### ISSUE TITLE
About training speed

### ISSUE THREAD

**Issue by yy18dlz** [open-mmlab/mmdetection#4342]
Hi, This is awesome work！I love lt！
But, I have some problem....
I found the taining speed may not as faster as i expected

here is my use analyze_logs.py:
slowest epoch 49, average time is 1.1886
fastest epoch 11, average time is 0.9775
time std over epochs is 0.0323
average iter time: 1.0163 s/iter

this means for one epoch it's need about 4 hours....
the same net on darknet only need about 1 hours for one epoch
Is there any good suggestion here?

**Comment by hhaAndroid** [comment]
Please provide more training details, such as cfg, log, envs, etc.
