### ISSUE TITLE
Provide different pretrained backbones in DetectoRS

### ISSUE THREAD

**Issue by TuanNguyenSKKU** [open-mmlab/mmdetection#4345]
hi everyone,

Currently, I only see DetectoRS with ResNet-50 in this repo. Can you provide us the model and config files for ResNet-101, ResNeXt-101 like in the related paper?
Because the code of joe-siyuan-qiao Github is different from this repo with regards to DetectoRS.
Thank you.

**Comment by v-qjqs** [comment]
Hi, we are providing pretrained r101 and x101 checkpoints in process.

**Comment by TuanNguyenSKKU** [comment]
I hope to see that. Thank you and your team.

**Comment by borgarpa** [comment]
> 
> 
> Hi, we are providing pretrained r101 and x101 checkpoints in process.

Hi,
Is there an estimated release date? I will be doing some research on industrial automation soon, so it would be great to know when ResNeXt 101 64x4d backbone will be ready, since it is the one that performed best.
Thanks for your effort!
