### ISSUE TITLE
when i use mmdetectionn2.7 multiple GPU training cannot be used

### ISSUE THREAD

**Issue by 781458112** [open-mmlab/mmdetection#4346]
when i use mmdetectionn2.3 i can use ./tools/dist_train.sh ./configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py 4 to run multiple GPU.but in mmdetectionn2.7,when i use ./tools/dist_train.sh An error occurred in the program.Details of the error are shown below：
subprocess.CalledProcessError: Command '['/home/z/anaconda3/envs/mmde2.7/bin/python', '-u', './tools/train.py', '--local_rank=3', './configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 2.
I don't know if there is a BUG in the program or if There is something wrong with my operation，How can I use multi-GPU training in mmdetection2.7？

**Comment by v-qjqs** [comment]
Hi @781458112, you may find the multi-GPU training guidelines [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md)
