### ISSUE TITLE
A little question, why "+1" here?

### ISSUE THREAD

**Issue by lfydegithub** [open-mmlab/mmdetection#4351]
https://github.com/open-mmlab/mmdetection/blob/482f60fe55c364e50e4fc4b50893a25d8cc261b0/mmdet/core/bbox/assigners/grid_assigner.py#L130

just a question from a fan.

**Comment by kellenf** [comment]
1.notic in line149 is `assigned_gt_inds[pos_inds] - 1`

**Comment by lfydegithub** [comment]
> 1.notice in line149 is `assigned_gt_inds[pos_inds] - 1`
> 2.notice in class `AssignResult`:
> 
> ```python
> class AssignResult(util_mixins.NiceRepr):
>     """Stores assignments between predicted and truth boxes.
> 
>     Attributes:
>         num_gts (int): the number of truth boxes considered when computing this
>             assignment
> 
>         gt_inds (LongTensor): for each predicted box indicates the 1-based
>             index of the assigned truth box. 0 means unassigned and -1 means
>             ignore.
> 
>         max_overlaps (FloatTensor): the iou between the predicted box and its
>             assigned truth box.
> 
>         labels (None | LongTensor): If specified, for each predicted box
>             indicates the category label of the assigned truth box.
> 
> 
> gt_inds: 0 means unassigned and -1 means ignore. This setting make this code make you confused, help this can help you!
> ```

very useful !!!, thank you very much. I should known that...
