### ISSUE TITLE
replace FPN with RFP

### ISSUE THREAD

**Issue by yzk-lab** [open-mmlab/mmdetection#4352]
I have a model which use FPN,but your Recusion Feature Pyramid is better than FPN ,so i transform the RFP code into my code mmdet/neck /rfp.py,however,there are something wrong.if I just change the type in the config,when i train the model ,it occurs that register_module() missing 1 required positional argument: 'cls',I don‘t know why.i hope you can kindly tell me the solution.

**Comment by yhcao6** [comment]
If you write a new neck and you want to enable customing it in the config, you should:
1.
```
@NECKS.register_module()
class NewNeck:
    ...
```

2. In the [__init__.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/necks/__init__.py), export your new_neck.
