### ISSUE TITLE
The mAP of GFL in min-val is 36.3, not 42.8 in paper.

### ISSUE THREAD

**Issue by mrsempress** [open-mmlab/mmdetection#4353]
I copy the gfl_head.py gfl_loss.py in latest mmdetection, and use the mmdetection v0.6.0 code to train the gfl_r50_fpn_ms2x. But I get the mAP 36.3 in min-val which it is 42.8 in paper. And gfl_r50_fpn_1x is 32.6 in min-val, but 40.2 in paper. I don't what is wrong.
I add the pipeline part to test augment, and even copy the latest ResNet, FPN, anchor_generator, but get the same results. It seems that no other part may influence the results. Can you give me some advice that don't need change the version of mmdetection?

**Comment by ZwwWayne** [comment]
This is because the latest model has different class order and coordinate system as those models trained in mmdetection v0.6.0. See the documentation [here](https://mmdetection.readthedocs.io/en/latest/compatibility.html).
