### ISSUE TITLE
ValueError: base_wd should not be None

### ISSUE THREAD

**Issue by Serenagirl** [open-mmlab/mmdetection#4354]
My config file :

# model settings
num_classes = 4
model = dict(
    type='VFNet',
    pretrained='open-mmlab://resnext101_64x4d',
    backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=64,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs=True,
        extra_convs_on_inputs=False,  # use P5
        num_outs=5,
        relu_before_extra_convs=True),
    bbox_head=dict(
        type='VFNetHead',
        num_classes=num_classes,
        in_channels=256,
        stacked_convs=3,
        feat_channels=256,
        strides=[8, 16, 32, 64, 128],
        center_sampling=False,
        dcn_on_last_conv=False,
        use_atss=True,
        use_vfl=True,
        loss_cls=dict(
            type='VarifocalLoss',
            use_sigmoid=True,
            alpha=0.75,
            gamma=2.0,
            iou_weighted=True,
            loss_weight=1.0),
        loss_bbox=dict(type='GIoULoss', loss_weight=1.5),
        loss_bbox_refine=dict(type='GIoULoss', loss_weight=2.0)))

# training and testing settings
train_cfg = dict(
    assigner=dict(type='ATSSAssigner', topk=9),
    allowed_border=-1,
    pos_weight=-1,
    debug=False)
test_cfg = dict(
    nms_pre=1000,
    min_bbox_size=0,
    score_thr=0.05,
    nms=dict(type='nms', iou_threshold=0.6),
    max_per_img=100)

dataset_type = 'CocoDataset'
data_root = 'data/underwater/'
classes = ['holothurian', 'echinus', 'scallop', 'starfish']
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='Resize',
        img_scale=[(1333, 480), (1333, 960)],
        multiscale_mode='range',
        keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'images',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'images',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'images',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')
# optimizer
optimizer = dict(
    lr=0.01, paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.))
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.1,
    step=[16, 22])
total_epochs = 24

checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]

it's referring to the file here：[link](https://github.com/open-mmlab/mmdetection/blob/master/configs/vfnet/vfnet_x101_64x4d_fpn_mstrain_2x_coco.py)

Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 181, in main
    meta=meta)
  File "/dat01/zhangzhuoer/lilu/mmdetection/mmdet/apis/train.py", line 86, in train_detector
    optimizer = build_optimizer(model, cfg.optimizer)
  File "/home/zhangzhuoer/project/.conda/envs/lilu/lib/python3.6/site-packages/mmcv/runner/optimizer/builder.py", line 41, in build_optimizer
    paramwise_cfg=paramwise_cfg))

  File "/home/zhangzhuoer/project/.conda/envs/lilu/lib/python3.6/site-packages/mmcv/runner/optimizer/builder.py", line 29, in build_optimizer_constructor
    return build_from_cfg(cfg, OPTIMIZER_BUILDERS)

  File "/home/zhangzhuoer/project/.conda/envs/lilu/lib/python3.6/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/home/zhangzhuoer/project/.conda/envs/lilu/lib/python3.6/site-packages/mmcv/runne    val=dict(
r/optimizer/default_constructor.py", line 102, in __init__
    self._validate_cfg()
            pos_weight=-1,
  File "/home/zhangzhuoer/project/.conda/envs/lilu/lib/python3.6/site-packages/mmcv/runner/optimizer/default_constructor.py", line 125, in _validate_cfg
    raise ValueError('base_wd should not be None')
ValueError: base_wd should not be None

I think it should be about optimizer. Change 
```
optimizer = dict(
    lr=0.01, paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.))

```
to 
```
optimizer = dict(
    type='SGD', lr=0.01, paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.))
```
but report the same error

**Comment by ZwwWayne** [comment]
Please use the `error template`.

**Comment by greathope** [comment]
same problem

**Comment by fenght96** [comment]
Maybe you are missing ```weight_decay```

```python
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001,
    paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.))
```

**Comment by jaderxnet** [comment]
> Maybe you are missing `weight_decay`
> 
> ```python
> optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001,
>     paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.))
> ```

This worked for me. But I was use Adan type optimizer and I needed change, is possible continue using Adan without erros?
