### ISSUE TITLE
ImportError: /home/ray/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE

### ISSUE THREAD

**Issue by ray-401** [open-mmlab/mmdetection#4357]
addict             2.4.0
attrs              20.3.0
certifi            2020.12.5
cycler             0.10.0
Cython             0.29.21
future             0.18.2
importlib-metadata 3.3.0
iniconfig          1.1.1
kiwisolver         1.3.1
matplotlib         3.3.3
mkl-fft            1.2.0
mkl-random         1.1.1
mkl-service        2.3.0
mmcv-full          1.2.3
mmdet              2.7.0               /home/ray/mmdetection
mmpycocotools      12.0.3
numpy              1.19.2
olefile            0.46
opencv-python      4.4.0.46
packaging          20.8
Pillow             8.0.1
pip                20.3.3
pluggy             0.13.1
py                 1.10.0
pyparsing          3.0.0b1
pytest             6.2.1
python-dateutil    2.8.1
PyYAML             5.3.1
setuptools         51.0.0.post20201207
six                1.15.0
terminaltables     3.1.0
toml               0.10.2
torch              1.5.1
torchvision        0.6.1
typing-extensions  3.7.4.3
wheel              0.36.2
yapf               0.30.0
zipp               3.4.0

ubuntu18.04,python3.7,

**Comment by ray-401** [comment]
mmcv-full          1.2.3
mmdet              2.7.0               /home/ray/mmdetection
mmpycocotools      12.0.3
torch              1.5.1
torchvision        0.6.0a0+35d732a

**Comment by ray-401** [comment]
compile mmcv from source can solve this problem.

**Comment by Moore-K2** [comment]
> compile mmcv from source can solve this problem.

can you tell me how to compile mmcv? thanks
