### ISSUE TITLE
Visualization classification confidence too low

### ISSUE THREAD

**Issue by GYE19970220** [open-mmlab/mmdetection#4358]
**Describe the bug**
To train kitti, I follow the MMDet_Tutorial.ipynb, and turn it into official structure organization, as the following say. But when I visualize the prediction result, the classification confidence is very low, as the picture show. The only problem I want to solve is  the classification confidence in the visualization result, I think it's too low, but don' know why, please help me. Any ideas would be much appreciated!
![image](https://user-images.githubusercontent.com/42958175/103165267-891e9b00-4850-11eb-89ff-d948b437bfc7.png)
![image](https://user-images.githubusercontent.com/42958175/103165359-9ee09000-4851-11eb-8462-111ef220261c.png)

**Reproduction**

1.What command or script did you run?
**train**
`CUDA_VISIBLE_DEVICES=6 nohup python tools/train.py configs/fcos/fcos_r50_caffe_fpn_4x4_1x_coco.py --gpus=1 --work-dir=fcos_output/test`
**test**
`CUDA_VISIBLE_DEVICES=6 python tools/test.py configs/fcos/fcos_r50_caffe_fpn_4x4_1x_coco.py  fcos_output/test/epoch_12.pth --show`

2.Did you make any modifications on the code or config? Did you understand what you have modified?
All files I modified are recoreded [here](https://blog.csdn.net/Left_control_right/article/details/110881893) ，
①add mmdet/datasets/kitti.py (from MMDet_Tutorial.ipynb)
![image](https://user-images.githubusercontent.com/42958175/103163648-9aa97800-483b-11eb-9d8d-1962d880a238.png)
![image](https://user-images.githubusercontent.com/42958175/103163652-a7c66700-483b-11eb-9e74-70599fbb6c13.png)
②modify mmdet/datasets/__init__.py
![image](https://user-images.githubusercontent.com/42958175/103163657-ccbada00-483b-11eb-8785-16d7cca2f235.png)
③add configs/_base_/datasets/kitti_detection.py(similar to coco_detection.py)
![image](https://user-images.githubusercontent.com/42958175/103163668-f7a52e00-483b-11eb-9313-7cd8892d00b3.png)
![image](https://user-images.githubusercontent.com/42958175/103163670-fd027880-483b-11eb-9ee5-9a26bfc26df5.png)
④modify mmdet\core\evaluation/class_names.py
![image](https://user-images.githubusercontent.com/42958175/103163673-1a374700-483c-11eb-9e23-49ae8f19be61.png)
⑤modify mmdet/core/evaluation/__init__.py
![image](https://user-images.githubusercontent.com/42958175/103163690-40f57d80-483c-11eb-893f-c1e4620ea22f.png)
⑥modify configs/fcos/fcos_r50_caffe_fpn_4x4_1x_coco.py
![image](https://user-images.githubusercontent.com/42958175/103163694-5ff40f80-483c-11eb-977b-4a11571a6736.png)
![image](https://user-images.githubusercontent.com/42958175/103163701-7306df80-483c-11eb-931a-2879231b6039.png)
⑦modify mmdet/apis/inference.py, change 'coco' in line 48 into 'kitti' 
![image](https://user-images.githubusercontent.com/42958175/103163719-b9f4d500-483c-11eb-828d-d7317c1a1998.png)

3.What dataset did you use?
kitti data set

**Environment**

sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: TITAN V
CUDA_HOME: /home/gye/cuda100
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:

GCC 7.3
Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
OpenMP 201511 (a.k.a. OpenMP 4.5)
NNPACK is enabled
CUDA Runtime 10.0
NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
CuDNN 7.6.5
Built with CuDNN 7.6.4
Magma 2.5.0
Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/opt/conda/conda-bld/pytorch_1574381331675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574381331675/work=/usr/local/src/conda/pytorch-1.3.1 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1574381331675/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
TorchVision: 0.4.2
OpenCV: 4.1.0
MMCV: 1.2.1
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMDetection: 2.7.0+fb287b1

**Comment by ZwwWayne** [comment]
The confidence score and the prediction results seems to be normal. It is not a bug actually.
