### ISSUE TITLE
where to get "nms_wrapper" in version 2.7.0

### ISSUE THREAD

**Issue by Chan-Sun** [open-mmlab/mmdetection#4361]
I was trying to reimplement a object detection project found on github. However the project was built on mmdetection 1.1.0 and my mmdetection version is 2.7.0. 

And i couldn't find **nms_wrapper** in mmdetection/mmdet/ops/nms, so i wonder where to find this api?

**Comment by ZwwWayne** [comment]
It has been moved to mmcv.ops
