### ISSUE TITLE
Backend TkAgg is interactive backend. Turning interactive mode on.

### ISSUE THREAD

**Issue by volareneo** [open-mmlab/mmdetection#4365]
I set the breakpoint in the resnet.py. But when I debug the train.py(with appropriate configuration), the Console post'Backend TkAgg is interactive backend. Turning interactive mode on.'

any suggesstion would be appreciated!

**Comment by hhaAndroid** [comment]
Outputting this information will not affect debugging，But if you get stuck, you can recheck the matplotlib . Hope it helps you

**Comment by volareneo** [comment]
> Outputting this information will not affect debugging，But if you get stuck, you can recheck the matplotlib . Hope it helps you

感谢回复！我正在学习您的知乎博客^_   
按照网上说明修改import matplotlib之后不再显示Backend TkAgg is interactive backend. Turning interactive mode on.
我发现我的问题与此也无关，事实上问题是debug过程中，在Debugger的variables中一直是“Collecting data”，推测是因为mmdetection的并行引起的阻塞，导致无法调试.
最后换了搜索关键字，发现需要勾选pycharm中的gevent compatible，就可以在各种子文件中看到Variables了。

**Comment by hhaAndroid** [comment]
Thanks for your attention！  In debug mode, I suggest you set `num_worker=0`

**Comment by medgitt** [comment]
i get a message on running a file as 
"Backend TkAgg is interactive backend. Turning interactive mode on" in pycharm.

what could be the issue

**Comment by sajjadkarimi91** [comment]
![image](https://user-images.githubusercontent.com/50092872/143410683-135b283b-8ac0-4a29-bee1-78ee918a28e8.png)
In debug mode click on "Show Debug Console"
