### ISSUE TITLE
What is the unit of time in log files?

### ISSUE THREAD

**Issue by MSTK2014** [open-mmlab/mmdetection#4369]
For example, one line in  the log file of YOLOv3:

{"mode": "train", "epoch": 1, "iter": 100, "lr": 0.00014, "time": 0.3997, "data_time": 0.01581, "memory": 7445, "loss_cls": 3113.00698, "loss_conf": 2096.8282, "loss_xy": 161.2406, "loss_wh": 41.87329, "loss": 5412.94908, "grad_norm": 9307.87263}

Is the unit of time seconds? If the unit of time is seconds, then the whole training process was completed in more than one hour, wasn't it so fast?

**Comment by ZwwWayne** [comment]
The unit is second. About the training process, it depends on the dataset and many other issues, we are not sure.
