### ISSUE TITLE
About precise RoI pooling

### ISSUE THREAD

**Issue by UT-Mao** [open-mmlab/mmdetection#4371]
Hello, it seems mmdetection does not support Precise RoI pooling yet. Do you have a plan for that?
If I have to implement the Precise RoI pooling myself, is there any suggestion or guidance? 
Thank you.

**Comment by hellock** [comment]
You can migrate it from https://github.com/vacancy/PreciseRoIPooling.

Some researchers tried it before but the op itself does not boost the performance over RoI Align. Other components in IoU-Net are required to work with it.

**Comment by ppwwyyxx** [comment]
The concept of "Precise ROI Pooling" is equivalent to ROIAlign with sampling_ratio=0, which is in fact already supported by the ROIAlign op.
