### ISSUE TITLE
Is it possible to set the mask branches to be class agnostics?

### ISSUE THREAD

**Issue by bpmsilva** [open-mmlab/mmdetection#4373]
I am working on a problem that requires segmenting different but similar objects. For instance, one may need to segment hands labeled as "right hand" and "left hand." Therefore, I would like the mask branches to be class agnostics while keeping the original labels' in the classification branch. Is this type of configuration possible? A snippet of a configuration file that implements this is very welcome!

Thanks in advance

**Comment by bpmsilva** [comment]
Hi!

Right now I'm changing the configuration to add `cfg.model.roi_head.mask_head.class_agnostic = True`. Is that enough? If yes, will this work with the HTC and the Cascade architectures. I am asking because I know, for instance, that HTC interweaves the bounding box and mask predictions.

Thanks!

**Comment by ZwwWayne** [comment]
Yes, it is enough.
