### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by harbmarc** [open-mmlab/mmdetection#4374]
Hello,
I tried to simply run the program in the [colab file](https://colab.research.google.com/github/Tony607/mmdetection_object_detection_demo/blob/master/mmdetection_train_custom_data.ipynb#scrollTo=7AcgLepsKFX-) as it is and it gave the following error  
**IndexError: list index out of range**
This error was due to the following line : **work_dir = re.findall(r"work_dir = \'(.*?)\'", s)[0]**  (It's in the second cell in the modify config file section). Can somebody help me, please?

**Comment by xvjiarui** [comment]
Hi @harbmarc 
You may add `work_dir` in your config file. You may also refer to our [colab tutorial](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb).
