### ISSUE TITLE
Can I replace the backbone of yolov3 with resnet?

### ISSUE THREAD

**Issue by ghm666** [open-mmlab/mmdetection#4375]
@wuhy08 

When I replace the backbone of yolov3 with resnet18, the following error occurs.

`RuntimeError: Given groups=1, weight of size 256 256 1 1, expected input[2, 512, 19, 19] to have 256 channels, but got 512 channels instead`

configs  resnet18-yolov3

_base_ = '../_base_/default_runtime.py'
model settings
model = dict(
    type='YOLOV3',
    pretrained='torchvision://resnet18',
    backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(3, 2, 1),
        frozen_stages=0,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='YOLOV3Neck',
        num_scales=3,
        in_channels=[512, 256, 128],
        out_channels=[512, 256, 128]),
    bbox_head=dict(
        type='YOLOV3Head',
        num_classes=4,
        in_channels=[512, 256, 128],
        out_channels=[1024, 512, 256],
        anchor_generator=dict(
            type='YOLOAnchorGenerator',
            base_sizes=[[(101, 253), (245, 161), (298, 311)],
                        [(38, 142), (92, 112), (217, 69)],
                        [(18, 27), (24, 65), (67, 47)]],
            strides=[32, 16, 8]),
        bbox_coder=dict(type='YOLOBBoxCoder'),
        featmap_strides=[32, 16, 8],
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_conf=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_xy=dict(
            type='CrossEntropyLoss',

**Comment by ZwwWayne** [comment]
Yes you can, but you also need to update your neck accordingly since the channels might not match.

**Comment by ritaiask** [comment]
i replaced backbone with resnet50, neck with fpn , base_lr = 0.0001, train 136 eposhs, the evaluation map is only 0.18

**Comment by xvjiarui** [comment]
Hi @ritaiask 
What is your config? You may try setting `norm_eval=False` and `frozen_stage=-1`.

**Comment by ritaiask** [comment]
Hi @xvjiarui ,my setting is just like the default setting, frozen_stages=1,norm_eval=True;;
i'll try norm_eval=False and frozen_stage=-1 now

**Comment by LisaBernhardt** [comment]
Hi All, I am also trying to substitute the backbone with resnet18. 
I get the following error:
RuntimeError: Given groups=1, weight of size [256, 256, 1, 1], expected input[2, 64, 184, 320] to have 256 channels, but got 64 channels instead

Can someone please share his/her config file here to see how you have changed the neck accordingly?

Thanks!
