### ISSUE TITLE
CUDA11

### ISSUE THREAD

**Issue by SnailForce** [open-mmlab/mmdetection#4376]
实验室服务器是CUDA11.0版本的，然后只能安装pytorch1.7，运行程序报错。
Traceback (most recent call last):
  File "./tools/train.py", line 181, in <module>
    main()
  File "./tools/train.py", line 177, in main
    meta=meta)
  File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 246, in train_step
    losses = self(**data)
  File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 180, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/single_stage.py", line 95, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/atss_head.py", line 272, in loss
    torch.tensor(num_total_pos).cuda()).item()
  File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/core/utils/dist_utils.py", line 68, in reduce_mean
    dist.all_reduce(tensor.div_(dist.get_world_size()), op=dist.ReduceOp.SUM)
RuntimeError: result type Float can't be cast to the desired output type Long

请问该如何解决
之前在pytorch1.5+cuda10.1+mmdetection2.5版本下并未出错

**Comment by SnailForce** [comment]
> 实验室服务器是CUDA11.0版本的，然后只能安装pytorch1.7，运行程序报错。
> Traceback (most recent call last):
> File "./tools/train.py", line 181, in
> main()
> File "./tools/train.py", line 177, in main
> meta=meta)
> File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/apis/train.py", line 150, in train_detector
> runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
> epoch_runner(data_loaders[i], **kwargs)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
> self.run_iter(data_batch, train_mode=True)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
> **kwargs)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
> output = self.module.train_step(*inputs[0], **kwargs[0])
> File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 246, in train_step
> losses = self(**data)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func return old_func(*args, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 180, in forward return self.forward_train(img, img_metas, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/single_stage.py", line 95, in forward_train gt_labels, gt_bboxes_ignore) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func return old_func(*args, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/atss_head.py", line 272, in loss torch.tensor(num_total_pos).cuda()).item() File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/core/utils/dist_utils.py", line 68, in reduce_mean dist.all_reduce(tensor.div_(dist.get_world_size()), op=dist.ReduceOp.SUM)
> RuntimeError: result type Float can't be cast to the desired output type Long
> 
> 请问该如何解决

之前在pytorch1.5+cuda10.1+mmdetection2.5版本下并未出错

**Comment by shinya7y** [comment]
The latest code (after https://github.com/open-mmlab/mmdetection/pull/4359) will work.

**Comment by HzZHoO** [comment]
> 实验室服务器是CUDA11.0版本的，然后只能安装pytorch1.7，运行程序报错。
> Traceback (most recent call last):
> File "./tools/train.py", line 181, in
> main()
> File "./tools/train.py", line 177, in main
> meta=meta)
> File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/apis/train.py", line 150, in train_detector
> runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
> epoch_runner(data_loaders[i], **kwargs)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
> self.run_iter(data_batch, train_mode=True)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
> **kwargs)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
> output = self.module.train_step(*inputs[0], **kwargs[0])
> File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 246, in train_step
> losses = self(**data)
> File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func return old_func(*args, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 180, in forward return self.forward_train(img, img_metas, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/single_stage.py", line 95, in forward_train gt_labels, gt_bboxes_ignore) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func return old_func(*args, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/atss_head.py", line 272, in loss torch.tensor(num_total_pos).cuda()).item() File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/core/utils/dist_utils.py", line 68, in reduce_mean dist.all_reduce(tensor.div_(dist.get_world_size()), op=dist.ReduceOp.SUM)
> RuntimeError: result type Float can't be cast to the desired output type Long
> 
> 请问该如何解决
> 之前在pytorch1.5+cuda10.1+mmdetection2.5版本下并未出错

你好请问你现在能够成功运行程序了吗？能否问一下编译使用的gcc是什么版本？我编译总会g++报错，好像无法生成.o文件
非常感谢

**Comment by Yuxiang1995** [comment]
> 实验室服务器是CUDA11.0版本的，然后只能安装pytorch1.7，运行程序报错。 Traceback (most recent call last): File "./tools/train.py", line 181, in main() File "./tools/train.py", line 177, in main meta=meta) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/apis/train.py", line 150, in train_detector runner.run(data_loaders, cfg.workflow, cfg.total_epochs) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run epoch_runner(data_loaders[i], **kwargs) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train self.run_iter(data_batch, train_mode=True) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter **kwargs) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step output = self.module.train_step(*inputs[0], **kwargs[0]) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 246, in train_step losses = self(**data) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func return old_func(*args, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/base.py", line 180, in forward return self.forward_train(img, img_metas, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/detectors/single_stage.py", line 95, in forward_train gt_labels, gt_bboxes_ignore) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore) File "/data1/home/gw7/miniconda3/envs/om/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func return old_func(*args, **kwargs) File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/models/dense_heads/atss_head.py", line 272, in loss torch.tensor(num_total_pos).cuda()).item() File "/data1/home/gw7/Code/mmdetection-2.7.0/mmdet/core/utils/dist_utils.py", line 68, in reduce_mean dist.all_reduce(tensor.div_(dist.get_world_size()), op=dist.ReduceOp.SUM) RuntimeError: result type Float can't be cast to the desired output type Long
> 
> 请问该如何解决 之前在pytorch1.5+cuda10.1+mmdetection2.5版本下并未出错

@SnailForce @HzZHoO 
在atss_head.py里面
torch.tensor(num_total_pos).cuda()).item()
改成
torch.tensor(num_total_pos, dtype=torch.float32).cuda()).item()
实测解决，对训练效果也不会有影响
