### ISSUE TITLE
How to train the model on other gpu_id?

### ISSUE THREAD

**Issue by Markovcom** [open-mmlab/mmdetection#438]
model = MMDataParallel(model, device_ids=range(cfg.gpus)).cuda()
When i try to train the model on gpu_id=3,it  is still on the gpu_id=0

**Comment by hellock** [comment]
You can specify `CUDA_VISIBLE_DEVICES` like `CUDA_VISIBLE_DEVICES=2,3 ./tools/dist_train.sh xxxx`.

**Comment by BlueBlueFF** [comment]
> You can specify `CUDA_VISIBLE_DEVICES` like `CUDA_VISIBLE_DEVICES=2,3 ./tools/dist_train.sh xxxx`.



> You can specify `CUDA_VISIBLE_DEVICES` like `CUDA_VISIBLE_DEVICES=2,3 ./tools/dist_train.sh xxxx`.

Only need to modify dist_train.sh?
