### ISSUE TITLE
about ga_faster_r50_fpn_1x_coco.py train

### ISSUE THREAD

**Issue by ningqing123** [open-mmlab/mmdetection#4380]
**when I train ga_faster_r50_fpn_1x_coco.py on BDD dataset，I have a problem"flat_anchors.size() torch.Size([0, 4]", why.
flat_anchors tensor([], device='cuda:0', size=(0, 4))**
`2021-01-01 21:27:37,893 - qdtrack - INFO - Epoch [1][150/171305]	lr: 5.994e-03, eta: 21 days, 21:02:58, time: 0.897, data_time: 0.013, memory: 6532, loss_rpn_cls: 0.2027, loss_rpn_bbox: 0.2332, loss_anchor_shape: 0.1536, loss_anchor_loc: 0.7959, loss_cls: 0.3808, acc: 92.2832, loss_bbox: 0.1233, loss_track: 0.6193, loss_track_aux: 0.2689, loss: 2.7777
  File "mmdetection/mmdet/models/dense_heads/anchor_head.py", line 227, in _get_targets_single
    anchors = flat_anchors[inside_flags, :]
IndexError: The shape of the mask [78440] at index 0 does not match the shape of the indexed tensor [0, 4] at index 0`

**Comment by ZwwWayne** [comment]
This wierd, did you modify anything about the model's config? Please use the `reimplementation question` to report your issue. We are not able to do any help here for now.

**Comment by ningqing123** [comment]
oh,thank you ,I got it.
