### ISSUE TITLE
about GARPN's train

### ISSUE THREAD

**Issue by ningqing123** [open-mmlab/mmdetection#4383]
I download the mmdetection, and use 1 GPU,python tools/train.py,modify confige as follow:
`    parser.add_argument('--config',default='configs/guided_anchoring/ga_faster_r50_fpn_1x_coco.py', help='train config file path')`
the result as follow:
`2021-01-03 10:02:15,629 - mmdet - INFO - Epoch [1][500/58633]   lr: 1.996e-02, eta: 3 days, 18:12:13, time: 0.434, data_time: 0.005, memory: 4851, loss_rpn_cls: 2.5725, loss_rpn_bbox: 0.0047, loss_anchor_shape: 0.3861, loss_anchor_loc: 55.1215, loss_cls: 2326544033.5461, acc: 84.1525, loss_bbox: 135189261.4936, loss: 2461733416.8998, grad_norm: 1170372919273.4768
`

**Comment by ZwwWayne** [comment]
The LR is too large. You need to divide the original LR by 8.
