### ISSUE TITLE
How to do test-augmentation?

### ISSUE THREAD

**Issue by sacalo** [open-mmlab/mmdetection#439]
I don't find any function to do bbox and mask test time augmentation with different image scales in the code. Should I do it myself like for example borrowing this functions https://github.com/roytseng-tw/Detectron.pytorch/blob/master/lib/core/test.py#L192?

**Comment by OceanPang** [comment]
@sacalo The multi-scale training and testing methods are not implemented in this codebase yet. You can do it by yourself first.

**Comment by hellock** [comment]
You can just specify multiple scales in the config file, like `img_scale=[(1333, 800), (1000, 600)]`.
