### ISSUE TITLE
the length of the loaded train dataloader is 1

### ISSUE THREAD

**Issue by Eleanor456** [open-mmlab/mmdetection#4390]
When I retrain the model-zoo with my own dataset which is made the form as coco, the  length of the loaded train dataloader is always 1. 
I print the cfg and DATASET before dataset = build_from_cfg(cfg, DATASETS, default_args) in the file of mmdet/datasets/builder.py.

The cfg output  of train loader is:
 "{'type': 'CocoDataset', 'ann_file': 'data/coco/annotations/instances_train2017.json', 'img_prefix': 'data/coco/train2017/', 'pipeline': [{'type': 'LoadImageFromFile'}, {'type': 'LoadAnnotations', 'with_bbox': True}, {'type': 'Resize', 'img_scale': (1333, 800), 'keep_ratio': True}, {'type': 'RandomFlip', 'flip_ratio': 0.5}, {'type': 'Normalize', 'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375], 'to_rgb': True}, {'type': 'Pad', 'size_divisor': 32}, {'type': 'DefaultFormatBundle'}, {'type': 'Collect', 'keys': ['img', 'gt_bboxes', 'gt_labels']}]}"

And the cfg output  of val loader is:
{'type': 'CocoDataset', 'ann_file': 'data/coco/annotations/instances_val2017.json', 'img_prefix': 'data/coco/val2017/', 'pipeline': [{'type': 'LoadImageFromFile'}, {'type': 'MultiScaleFlipAug', 'img_scale': (1333, 800), 'flip': False, 'transforms': [{'type': 'Resize', 'keep_ratio': True}, {'type': 'RandomFlip'}, {'type': 'Normalize', 'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375], 'to_rgb': True}, {'type': 'Pad', 'size_divisor': 32}, {'type': 'ImageToTensor', 'keys': ['img']}, {'type': 'Collect', 'keys': ['img']}]}]}

Could you tell me what is the reason about the problem, and how can I fix it. Thx.

**Comment by ZwwWayne** [comment]
Could you describe more following the `reimplementation questions` or `error template`, e.g., the code you write, at which place, that makes you get the length to be 1?

**Comment by ZwwWayne** [comment]
The cfg dict seems to be normal.

**Comment by hhaAndroid** [comment]
I suggest you run the `tools/browse_dataset.py` file first, if it is right then dataloader cfg problem
