### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'num_stages'

### ISSUE THREAD

**Issue by DWCTOD** [open-mmlab/mmdetection#4397]
你好，一直报这个错，换了很多个pytorch版本（1.7.1,1.7.0,1.6.0,1.51），一直报错
我这里使用的版本
mmdet:2.8.0
mmcv-full:1.2.4

给的demo能跑通，但是改了就报错了，希望大佬有空可以帮忙看一下，不知道具体是为啥，感谢

**Comment by v-qjqs** [comment]
Hi @DWCTOD, could you please provide a completed error log?

**Comment by ZwwWayne** [comment]
Please use `Error Template`.

**Comment by DWCTOD** [comment]
> Hi @DWCTOD, could you please provide a completed error log?

Sorry to bother you, but it's probably my fault

**Comment by ashj9** [comment]
@DWCTOD I am also facing the same error. Could you please share how did you resolve it?

Thanks!!!

**Comment by jabolcni** [comment]
I am also having the same problem. Did you solved the problem and how?

**Comment by ashj9** [comment]
@jabolcni 
In my case, there was a problem with the config.py file. Updating it correctly solved my problem. You can try once.
