### ISSUE TITLE
How can i call mmdetection by c++ in ubuntu?

### ISSUE THREAD

**Issue by lixz123007** [open-mmlab/mmdetection#4399]
I have i c++ project, and success run the mmdetection in python ,How can i call mmdetection by c++ in ubuntu16.04 ?

**Comment by ZwwWayne** [comment]
Currently we do not support that. You may use the models trained by mmdet after export the models to ONNX, see [doc here](https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html)
