### ISSUE TITLE
complile.sh error

### ISSUE THREAD

**Issue by zxhr2793** [open-mmlab/mmdetection#440]
my environment is here.
Ubuntu 16.04
pytorch 1.0.1
cuda 9.0
I can compile my own .cu files using pytorch 0.4.1. but fail for this.
this error links to the line (AT_DISPATCH_FLOATING_TYPES_AND_HALF). how to solver these?

Building roi align op...
running build_ext
building 'roi_align_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/username/miniconda3/envs/mmdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/TH -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/username/miniconda3/envs/mmdet/include/python3.7m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.7/src/roi_align_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/TH -I/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/username/miniconda3/envs/mmdet/include/python3.7m -c src/roi_align_kernel.cu -o build/temp.linux-x86_64-3.7/src/roi_align_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(83): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lowest") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(84): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("max") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(85): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("lower_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/home/username/miniconda3/envs/detectron/lib/python3.7/site-packages/torch/include/ATen/cuda/NumericLimits.cuh(86): warning: calling a constexpr __host__ function("from_bits") from a __host__ __device__ function("upper_bound") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

src/roi_align_kernel.cu(133): error: expression must have integral or enum type

src/roi_align_kernel.cu(133): error: identifier "toString" is undefined

src/roi_align_kernel.cu(276): error: expression must have integral or enum type

src/roi_align_kernel.cu(276): error: identifier "toString" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_000041e3_00000000-6_roi_align_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by zxhr2793** [comment]
compile sucessfully when change to the branch of pytorch-0.4.1. But still fail at the master branch with pytorch 1.0.1

**Comment by ovgeorge** [comment]
Have you've been able to solve the problem?

**Comment by hellock** [comment]
This is an outdated issue.
