### ISSUE TITLE
Could I train mmdet model with sample-wise weight?

### ISSUE THREAD

**Issue by tnhgiang** [open-mmlab/mmdetection#4403]
Hi all, I'm using Mask-RCNN model and wondering if mmdet could support training with sample-wise weight or even class-wise weight? I've searched a lot, but can't find any useful information.

Thanks

**Comment by v-qjqs** [comment]
Hi @tnhgiang, actually mmdet supports both sample-wise weight and class-wise wieght.
For example, [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/losses/cross_entropy_loss.py#L9) `weight` and `class_weight` are used for sample-wise and class-wise respectively.
