### ISSUE TITLE
What parameters should be modified when setting a smaller resolution of image.

### ISSUE THREAD

**Issue by tianxianhao** [open-mmlab/mmdetection#4404]
Hi, i am using the mmdetection for object detection.
i select faster-rcnn + resnet_101  as the experiment model.
The input images are all with size of 320x180.
It is too slow when using the input size of 1333x800 in original config file.
So i try to modify the parameter of "Resize" in train_pipeline and test_pipeline from 1333x800 to 320x180. 
But finally i got a terrible performance on object detection.
And if i use the original config file for training my own dataset, it can provide me a nice result.
What should i do if i want a fasterrcnn model with smaller size input image?
What parameter should be modified  if the "Resize" parameter is changed?
The config file i used for testing is faster_rcnn_r100_caffe_fpn_1x_coco.py

**Comment by kellenf** [comment]
em.....It's normal that bad performance with smaller  input_size, if inference is slow you can transfer to YOLO or other tiny detectors

**Comment by tianxianhao** [comment]
> em.....It's normal that bad performance with smaller input_size, if inference is slow you can transfer to YOLO or other tiny detectors

Not like that, as the original input of Faster-Rcnn is only 224x224, why it also got a nice performance?
So the conclusion that model with small input size has bad performance may be not right.
I input  the 320x180 images into model with process resizing img from 320x180 to 1333x800. And it got a 0.38 mAP.
But if i remove the resize process in model data pipeline, i got mAP< 0.1
I m sure that there are some setting i should change in the config file, and now i ask help here.

**Comment by alexeybozhchenko** [comment]
@tianxianhao maybe you figured it out?

**Comment by tianxianhao** [comment]
> @tianxianhao maybe you figured it out?

yep, the scale of generative achors should be rescale to a reasonable value.
