### ISSUE TITLE
How can I only use the first few layers of pyramids in atss

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmdetection#4413]
I just want use the first few layers of pyramids in atss, how should I change the code?Thank you very much!!!!

**Comment by yhcao6** [comment]
https://github.com/open-mmlab/mmdetection/blob/4824dc0c0c0b3cb701376314db9c2672973c140f/mmdet/models/detectors/single_stage.py#L93
Add one line behind it:
```
x = [x[0]]
```
But you also need to change other codes in `atss_head.py`.

**Comment by baibaidedongdong** [comment]
ok,thank yoy ,I will try it!



---Original---
