### ISSUE TITLE
Error when I test with a trained model

### ISSUE THREAD

**Issue by cccccccccy** [open-mmlab/mmdetection#4417]
Hello. I code a new model with mmdetection. But when I test this model, I have meeted some error. With a same picture as input ,  the train branch and the test branch give me different outputs. The train output looks well, but another don't.
the train branch and the test branch run the same bbox_head.forward(), but they give me different outputs.
Can you tell me what could be the reason？
Thanks a lot!

**Comment by yhcao6** [comment]
What do you mean train branch and test branch?
During training, there are some augmentations like resize and flip and the input to the network may be different from it in the test
