### ISSUE TITLE
How to generate tf_logs folder in work_dirs for tensorboard

### ISSUE THREAD

**Issue by DongDem** [open-mmlab/mmdetection#4418]
hi @openmmlab-bot ,
When I training the model, the `tf_logs` will be created in `work_dirs` folder automatically with (mmdetection ver1.0) but with ver2, I haven't see the `tf_logs` in `work_dirs`. Can you guilde me how to config to get `tf_logs`?
Thanks!

**Comment by yhcao6** [comment]
add the following code in the config
```
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
```
