### ISSUE TITLE
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 0

### ISSUE THREAD

**Issue by jigsawcoder** [open-mmlab/mmdetection#4419]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

I am trying to apply Albumentation on faster_rcnn but I am facing this error: 

RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 0

**Reproduction**

coco_detection.py :

dataset_type = 'CocoDataset'
data_root = '/content/drive/MyDrive/SIGNATURE_DETECION_FINAL/'
labels = ['signature', 'hand_written_date', 'stamp', 'barcode']
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
      type='Albu',
      transforms=albu_train_transforms,
      bbox_params=dict(
      type='BboxParams',
      format='pascal_voc',
      label_fields=['gt_labels'],
      min_visibility=0.0,
      filter_lost_elements=True),
      keymap={
      'img': 'image',
      'gt_bboxes': 'bboxes'
      },
      update_pad_shape=False,
      skip_img_without_anno=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        classes = labels,
        ann_file=data_root + 'Atul_sir_new_data/train.json',
        img_prefix=data_root + 'Atul_sir_new_data/train/',
        #ann_file=data_root + 'final_data/train/voc2coco_train.json',
        #img_prefix=data_root + 'final_data/train/images',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes = labels,
        #ann_file=data_root + 'final_data/val/voc2coco_val.json',
        #img_prefix=data_root + 'final_data/val/images/',
        ann_file=data_root + 'Atul_sir_new_data/valid.json',
        img_prefix=data_root + 'Atul_sir_new_data/val/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes = labels,
        ann_file=data_root + 'Atul_sir_new_data/val.json',
        img_prefix=data_root + 'Atul_sir_new_data/val/',
        #ann_file=data_root + 'final_data/test/voc2coco_test.json',
        #img_prefix=data_root + 'final_data/test/images',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')

```none
A placeholder for the command.
```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```
I am trying to implement faster_rcnn for object detection using a custom dataset with coco annotations. 

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
Can you provide the detailed error trace_back? For example, which line report this error

**Comment by jigsawcoder** [comment]
> Can you provide the detailed error trace_back? For example, which line report this error

Error discription:

Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 181, in main
    meta=meta)
  File "/content/drive/My Drive/SIGNATURE_DETECION_FINAL/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/hooks/optimizer.py", line 34, in after_train_iter
    runner.optimizer.step()
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 0


Also, I am getting a lot of size mismatch warnings, for example :
 

2021-01-10 11:34:57,242 - mmdet - WARNING - The model and loaded state dict do not match exactly

size mismatch for backbone.layer1.0.conv1.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 64, 1, 1]).
size mismatch for backbone.layer1.0.bn1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
size mismatch for backbone.layer1.0.bn1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
size mismatch for backbone.layer1.0.bn1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
size mismatch for backbone.layer1.0.bn1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
size mismatch for backbone.layer1.0.conv2.weight: copying a param with shape torch.Size([256, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 4, 3, 3]).
.
.
.
.

**Comment by arunavsegregore** [comment]
Hey @yhcao6  and @jigsawcoder, Have you solved this bug? If yes, can you pls tell me how you solved this issue?

**Comment by saad-abdullah62** [comment]
Is there any solution for this? 

When i try to remove padding from test dataset , I get this problem.I see problem is coming from this line 
```
mmdetection/mmdet/models/dense_heads/solov2_head.py
  
feature_add_all_level = feature_add_all_level + \
                self.convs_all_levels[i](input_p)
```
