### ISSUE TITLE
Align anchors with features in RPN

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#442]
It seems the anchors are flattened in row-first ([link](https://github.com/open-mmlab/mmdetection/blob/edb03937964b583a59dd1bddf76eaba82df9e8c0/mmdet/core/anchor/anchor_generator.py#L67)), but features are flattened in column-first ([link](https://github.com/open-mmlab/mmdetection/blob/edb03937964b583a59dd1bddf76eaba82df9e8c0/mmdet/models/anchor_heads/anchor_head.py#L163)). Can you verify it?

**Comment by yhcao6** [comment]
Could you explain why https://github.com/open-mmlab/mmdetection/blob/edb03937964b583a59dd1bddf76eaba82df9e8c0/mmdet/models/anchor_heads/anchor_head.py#L163 is column-first

**Comment by thangvubk** [comment]
The default tensor for torch fop conv layers is in ``[N, C, H, W]`` format. So the permuted ``bbox_pred`` having shape of ``[N, H, W, C]``. Then the ``reshape()`` will consider ``H`` before ``W``.

**Comment by yhcao6** [comment]
assume `N=1, H=2, W=3`, then flat should be
`[0, 0, 0]`, 
`[0, 0, 1]`, 
`[0, 0, 2]`
`[0, 1, 0]`, 
`[0, 1, 1]`,
`[0, 1, 2]`
It is row-first.

**Comment by thangvubk** [comment]
Ah. My misunderstanding in indexing and dimension. Thank you!
