### ISSUE TITLE
Batch inference when calling model() with list of ndarrays?

### ISSUE THREAD

**Issue by dave-andersen** [open-mmlab/mmdetection#4421]
**Describe the feature**
At the moment, the inference API assumes that if you pass in an ndarray, it represents a single image.

Passing in a list of ndarrays causes the code to incorrectly treat them as if they were filenames;
passing in a 4D tensor (i.e., img with a batch dimension) doesn't get split before being passed
to non-batch functions in the pipeline.

This is in conflict with the API comments, which indicates that imgs can be a list[str/ndarray].

Relevant code is mmdet/apis/inference.py 
in `inference_detector()`

Is fixing this desirable, e.g., would a patch be accepted (or is there already a fix in the pipeline)?

**Comment by ZwwWayne** [comment]
Hi @dave-andersen ,
Thanks for your kind suggestion. The fix is desirable as the current models support the batched inference thus this feature should also be available for `inference_detector`.  Would you like to create a PR for that?

**Comment by dave-andersen** [comment]
Yep. I've sent PR #4462 for this.
