### ISSUE TITLE
The AP turn to -1 when I test the test set.

### ISSUE THREAD

**Issue by rsj007** [open-mmlab/mmdetection#4427]
I use the pth file to test the test set, however it appears like this.
How does this happen?
![image](https://user-images.githubusercontent.com/29651895/104182465-78bf1080-544b-11eb-840c-cef689d43c6d.png)

**Comment by xuanthuyvo** [comment]
Because the ground truth annotation of the test set is not provided. You can submit the results to CodaLab system to get accuracy.

**Comment by ZwwWayne** [comment]
Please use the `reimplementation questions template` to describe your issue in detail. With the current information, we are not able to do any help.

**Comment by rsj007** [comment]
Thanks for your help. I have submitted a new issue as you said.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 晚上7:30
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"任烁健"<736720216@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] The AP turn to -1 when I test the test set. (#4427)





 
Please use the reimplementation questions template to describe your issue in detail. With the current information, we are not able to do any help.
