### ISSUE TITLE
 how can i get the same result when i training on the same config for two times?

### ISSUE THREAD

**Issue by github-eliviate** [open-mmlab/mmdetection#4428]
I set the seed to 0 and the determinstic to True in train.py , and training on the same config for two times ,I found the bbox mAP is also different ,why ? how can i get the same result?

**Comment by github-eliviate** [comment]
#1206 said the model training is not reproduce, why?

**Comment by ZwwWayne** [comment]
This is because there is still randomness during training. But the gap should be very small between performance of run.
