### ISSUE TITLE
How to view number of samples for each class from my custom dataset in VOC format before training? 

### ISSUE THREAD

**Issue by sindhura234** [open-mmlab/mmdetection#4431]
I have made my own dataset and able to train the network successfully. 
But I see the total samples that my data set is different from the number of samples used for training. 
**I want to see the number of samples it is taking for each class before training** and also I do not want to perform any data augmentation like a flip. **How do I disable this augmentation**?

**Comment by ZwwWayne** [comment]
1. For now, we do not support to see the number of samples before training.
2. By deleting `RandomFlip` in train_pipeline.
