### ISSUE TITLE
The AP value of the coco testing set is -1.000.

### ISSUE THREAD

**Issue by rsj007** [open-mmlab/mmdetection#4435]
#I am reimplementing cascade_rcnn_fpn_1x_coco.py in the coco dataset using the provided configs. After training, I want to test the model in the coco test dataset. I change the ann file and test dataset path in the test dict of the config. However the APs are all -1.000. I don't know what's the problem.
The result is below.
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
{'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}

The command I used for test is "`CUDA_VISIBLE_DEVICES=5,6,7,8 bash mmdetection/tools/dist_test.sh mmdetection/work_dirs/cascade_rcnn_r50_fpn_1x_coco/cascade_rcnn_r50_fpn_1x_coco.py mmdetection/work_dirs/cascade_rcnn_r50_fpn_1x_coco/epoch_1.pth 4 --eval bbox`".

My config is below.
```
model = dict(
    type='CascadeRCNN',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='CascadeRoIHead',
        num_stages=3,
        stage_loss_weights=[1, 0.5, 0.25],
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=80,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=80,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=80,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ]))
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            match_low_quality=True,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.7,
                min_pos_iou=0.7,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)
    ])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.5),
        max_per_img=100))
dataset_type = 'CocoDataset'
data_root = '/data/sj_data/data/coco'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='CocoDataset',
        ann_file='/data/sj_data/data/coco/annotations/instances_train2017.json',
        img_prefix='/data/sj_data/data/coco/train2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ]),
    val=dict(
        type='CocoDataset',
        ann_file='/data/sj_data/data/coco/annotations/instances_val2017.json',
        img_prefix='/data/sj_data/data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='/data/sj_data/data/coco/annotations/image_info_test-dev2017.json',
        img_prefix='/data/sj_data/data/coco/test2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=1, metric='bbox')
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11])
total_epochs = 12
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/cascade_rcnn_r50_fpn_1x_coco'
gpu_ids = range(0, 1)

```

My environment is below.
`Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7,8,9: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.2.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.6.0+`

**Comment by xuanthuyvo** [comment]
https://cocodataset.org/#upload

**Comment by rsj007** [comment]
> https://cocodataset.org/#upload

Sorry, I just want to get the result in the test set offline. Because I also meet the same problem in custom dataset.

**Comment by xuanthuyvo** [comment]
_test=dict(
        type='CocoDataset',
        ann_file='/data/sj_data/data/coco/annotations/image_info_test-dev2017.json',
        img_prefix='/data/sj_data/data/coco/test2017/',)_
I think you should change ann_file to validation file and also for image directory.

**Comment by hhaAndroid** [comment]
> #I am reimplementing cascade_rcnn_fpn_1x_coco.py in the coco dataset using the provided configs. After training, I want to test the model in the coco test dataset. I change the ann file and test dataset path in the test dict of the config. However the APs are all -1.000. I don't know what's the problem.
> The result is below.
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = -1.000
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=1000 ] = -1.000
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=1000 ] = -1.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=300 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=1000 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> {'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}
> 
> The command I used for test is "`CUDA_VISIBLE_DEVICES=5,6,7,8 bash mmdetection/tools/dist_test.sh mmdetection/work_dirs/cascade_rcnn_r50_fpn_1x_coco/cascade_rcnn_r50_fpn_1x_coco.py mmdetection/work_dirs/cascade_rcnn_r50_fpn_1x_coco/epoch_1.pth 4 --eval bbox`".
> 
> My config is below.
> 
> ```
> model = dict(
>     type='CascadeRCNN',
>     pretrained='torchvision://resnet50',
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=True,
>         style='pytorch'),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         num_outs=5),
>     rpn_head=dict(
>         type='RPNHead',
>         in_channels=256,
>         feat_channels=256,
>         anchor_generator=dict(
>             type='AnchorGenerator',
>             scales=[8],
>             ratios=[0.5, 1.0, 2.0],
>             strides=[4, 8, 16, 32, 64]),
>         bbox_coder=dict(
>             type='DeltaXYWHBBoxCoder',
>             target_means=[0.0, 0.0, 0.0, 0.0],
>             target_stds=[1.0, 1.0, 1.0, 1.0]),
>         loss_cls=dict(
>             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
>         loss_bbox=dict(
>             type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
>     roi_head=dict(
>         type='CascadeRoIHead',
>         num_stages=3,
>         stage_loss_weights=[1, 0.5, 0.25],
>         bbox_roi_extractor=dict(
>             type='SingleRoIExtractor',
>             roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
>             out_channels=256,
>             featmap_strides=[4, 8, 16, 32]),
>         bbox_head=[
>             dict(
>                 type='Shared2FCBBoxHead',
>                 in_channels=256,
>                 fc_out_channels=1024,
>                 roi_feat_size=7,
>                 num_classes=80,
>                 bbox_coder=dict(
>                     type='DeltaXYWHBBoxCoder',
>                     target_means=[0.0, 0.0, 0.0, 0.0],
>                     target_stds=[0.1, 0.1, 0.2, 0.2]),
>                 reg_class_agnostic=True,
>                 loss_cls=dict(
>                     type='CrossEntropyLoss',
>                     use_sigmoid=False,
>                     loss_weight=1.0),
>                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
>                                loss_weight=1.0)),
>             dict(
>                 type='Shared2FCBBoxHead',
>                 in_channels=256,
>                 fc_out_channels=1024,
>                 roi_feat_size=7,
>                 num_classes=80,
>                 bbox_coder=dict(
>                     type='DeltaXYWHBBoxCoder',
>                     target_means=[0.0, 0.0, 0.0, 0.0],
>                     target_stds=[0.05, 0.05, 0.1, 0.1]),
>                 reg_class_agnostic=True,
>                 loss_cls=dict(
>                     type='CrossEntropyLoss',
>                     use_sigmoid=False,
>                     loss_weight=1.0),
>                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
>                                loss_weight=1.0)),
>             dict(
>                 type='Shared2FCBBoxHead',
>                 in_channels=256,
>                 fc_out_channels=1024,
>                 roi_feat_size=7,
>                 num_classes=80,
>                 bbox_coder=dict(
>                     type='DeltaXYWHBBoxCoder',
>                     target_means=[0.0, 0.0, 0.0, 0.0],
>                     target_stds=[0.033, 0.033, 0.067, 0.067]),
>                 reg_class_agnostic=True,
>                 loss_cls=dict(
>                     type='CrossEntropyLoss',
>                     use_sigmoid=False,
>                     loss_weight=1.0),
>                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
>         ]))
> train_cfg = dict(
>     rpn=dict(
>         assigner=dict(
>             type='MaxIoUAssigner',
>             pos_iou_thr=0.7,
>             neg_iou_thr=0.3,
>             min_pos_iou=0.3,
>             match_low_quality=True,
>             ignore_iof_thr=-1),
>         sampler=dict(
>             type='RandomSampler',
>             num=256,
>             pos_fraction=0.5,
>             neg_pos_ub=-1,
>             add_gt_as_proposals=False),
>         allowed_border=0,
>         pos_weight=-1,
>         debug=False),
>     rpn_proposal=dict(
>         nms_across_levels=False,
>         nms_pre=2000,
>         nms_post=2000,
>         max_num=2000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=[
>         dict(
>             assigner=dict(
>                 type='MaxIoUAssigner',
>                 pos_iou_thr=0.5,
>                 neg_iou_thr=0.5,
>                 min_pos_iou=0.5,
>                 match_low_quality=False,
>                 ignore_iof_thr=-1),
>             sampler=dict(
>                 type='RandomSampler',
>                 num=512,
>                 pos_fraction=0.25,
>                 neg_pos_ub=-1,
>                 add_gt_as_proposals=True),
>             pos_weight=-1,
>             debug=False),
>         dict(
>             assigner=dict(
>                 type='MaxIoUAssigner',
>                 pos_iou_thr=0.6,
>                 neg_iou_thr=0.6,
>                 min_pos_iou=0.6,
>                 match_low_quality=False,
>                 ignore_iof_thr=-1),
>             sampler=dict(
>                 type='RandomSampler',
>                 num=512,
>                 pos_fraction=0.25,
>                 neg_pos_ub=-1,
>                 add_gt_as_proposals=True),
>             pos_weight=-1,
>             debug=False),
>         dict(
>             assigner=dict(
>                 type='MaxIoUAssigner',
>                 pos_iou_thr=0.7,
>                 neg_iou_thr=0.7,
>                 min_pos_iou=0.7,
>                 match_low_quality=False,
>                 ignore_iof_thr=-1),
>             sampler=dict(
>                 type='RandomSampler',
>                 num=512,
>                 pos_fraction=0.25,
>                 neg_pos_ub=-1,
>                 add_gt_as_proposals=True),
>             pos_weight=-1,
>             debug=False)
>     ])
> test_cfg = dict(
>     rpn=dict(
>         nms_across_levels=False,
>         nms_pre=1000,
>         nms_post=1000,
>         max_num=1000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=dict(
>         score_thr=0.05,
>         nms=dict(type='nms', iou_threshold=0.5),
>         max_per_img=100))
> dataset_type = 'CocoDataset'
> data_root = '/data/sj_data/data/coco'
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> train_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='LoadAnnotations', with_bbox=True),
>     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>     dict(type='RandomFlip', flip_ratio=0.5),
>     dict(
>         type='Normalize',
>         mean=[123.675, 116.28, 103.53],
>         std=[58.395, 57.12, 57.375],
>         to_rgb=True),
>     dict(type='Pad', size_divisor=32),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
> ]
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=(1333, 800),
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(
>                 type='Normalize',
>                 mean=[123.675, 116.28, 103.53],
>                 std=[58.395, 57.12, 57.375],
>                 to_rgb=True),
>             dict(type='Pad', size_divisor=32),
>             dict(type='ImageToTensor', keys=['img']),
>             dict(type='Collect', keys=['img'])
>         ])
> ]
> data = dict(
>     samples_per_gpu=2,
>     workers_per_gpu=2,
>     train=dict(
>         type='CocoDataset',
>         ann_file='/data/sj_data/data/coco/annotations/instances_train2017.json',
>         img_prefix='/data/sj_data/data/coco/train2017/',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(type='LoadAnnotations', with_bbox=True),
>             dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
>             dict(type='RandomFlip', flip_ratio=0.5),
>             dict(
>                 type='Normalize',
>                 mean=[123.675, 116.28, 103.53],
>                 std=[58.395, 57.12, 57.375],
>                 to_rgb=True),
>             dict(type='Pad', size_divisor=32),
>             dict(type='DefaultFormatBundle'),
>             dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
>         ]),
>     val=dict(
>         type='CocoDataset',
>         ann_file='/data/sj_data/data/coco/annotations/instances_val2017.json',
>         img_prefix='/data/sj_data/data/coco/val2017/',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(
>                 type='MultiScaleFlipAug',
>                 img_scale=(1333, 800),
>                 flip=False,
>                 transforms=[
>                     dict(type='Resize', keep_ratio=True),
>                     dict(type='RandomFlip'),
>                     dict(
>                         type='Normalize',
>                         mean=[123.675, 116.28, 103.53],
>                         std=[58.395, 57.12, 57.375],
>                         to_rgb=True),
>                     dict(type='Pad', size_divisor=32),
>                     dict(type='ImageToTensor', keys=['img']),
>                     dict(type='Collect', keys=['img'])
>                 ])
>         ]),
>     test=dict(
>         type='CocoDataset',
>         ann_file='/data/sj_data/data/coco/annotations/image_info_test-dev2017.json',
>         img_prefix='/data/sj_data/data/coco/test2017/',
>         pipeline=[
>             dict(type='LoadImageFromFile'),
>             dict(
>                 type='MultiScaleFlipAug',
>                 img_scale=(1333, 800),
>                 flip=False,
>                 transforms=[
>                     dict(type='Resize', keep_ratio=True),
>                     dict(type='RandomFlip'),
>                     dict(
>                         type='Normalize',
>                         mean=[123.675, 116.28, 103.53],
>                         std=[58.395, 57.12, 57.375],
>                         to_rgb=True),
>                     dict(type='Pad', size_divisor=32),
>                     dict(type='ImageToTensor', keys=['img']),
>                     dict(type='Collect', keys=['img'])
>                 ])
>         ]))
> evaluation = dict(interval=1, metric='bbox')
> optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
> optimizer_config = dict(grad_clip=None)
> lr_config = dict(
>     policy='step',
>     warmup='linear',
>     warmup_iters=500,
>     warmup_ratio=0.001,
>     step=[8, 11])
> total_epochs = 12
> checkpoint_config = dict(interval=1)
> log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
> dist_params = dict(backend='nccl')
> log_level = 'INFO'
> load_from = None
> resume_from = None
> workflow = [('train', 1)]
> work_dir = './work_dirs/cascade_rcnn_r50_fpn_1x_coco'
> gpu_ids = range(0, 1)
> ```
> 
> My environment is below.
> `Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
> CUDA available: True
> GPU 0,1,2,3,4,5,6,7,8,9: GeForce RTX 2080 Ti
> CUDA_HOME: /usr/local/cuda-10.0
> NVCC: Cuda compilation tools, release 10.0, V10.0.130
> GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
> PyTorch: 1.6.0
> PyTorch compiling details: PyTorch built with:
> 
> * GCC 7.3
> * C++ Version: 201402
> * Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * NNPACK is enabled
> * CPU capability usage: AVX2
> * CUDA Runtime 10.2
> * NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
> * CuDNN 7.6.5
> * Magma 2.5.2
> * Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
> 
> TorchVision: 0.7.0
> OpenCV: 4.4.0
> MMCV: 1.2.0
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 10.2
> MMDetection: 2.6.0+`

I suggest you use the validation data for testing，if mAP is -1 that may not have any prediction results，please confirm the output result and cfg

**Comment by suigong1** [comment]
same question
