### ISSUE TITLE
the training process don't go on my own dataset

### ISSUE THREAD

**Issue by leaving-voider** [open-mmlab/mmdetection#4438]
When I trained the Faster R-CNN model on my own dataset GWHD, I modify the Dataset Register Class:

And I modify the configuration, then I run it:
![image](https://user-images.githubusercontent.com/68451409/104426902-88f6fd00-55bd-11eb-8794-f5f48351675d.png)

It seems that it was running, but actually, I have waited for a long time. It didn't have any progression and there is no any error message showed, the cell is still running. How could that be? What would cause this to happen and can anyone help me?

**Comment by wataxiwaxiaokeai** [comment]
@leaving-voider Hi, I met the same problem. Did you solve that?

**Comment by leaving-voider** [comment]
@wataxiwaxiaokeai I tried it today with nothing changed, it just goes very well...
The problem of yesterday didn't show again

**Comment by v-qjqs** [comment]
Hi, [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_dataset.md) we provide guidelines for training your own dataset with COCO format.
Please refer to the `Reorganize new data formats to existing format` part for more suggestions.
