### ISSUE TITLE
 How to save  inferenced video

### ISSUE THREAD

**Issue by xincyu** [open-mmlab/mmdetection#4440]
When running video_ demo.py,  we can only see the video with detection results. How can you save the video with the detection results(menas with bbox).

I sincerely look forward to your reply.

Ming.

# Code :vidieo_demo.py

from argparse import ArgumentParser

from mmdet.apis import inference_detector, init_detector, show_result_pyplot
from mmdet.models.detectors import BaseDetector
import mmcv
import os

config_file = 'config_file'
checkpoint_file = 'latest.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')
video = mmcv.VideoReader('video.mp4')

print(len(video))
print(video.width, video.height, video.resolution, video.fps)

for frame in video:
    result = inference_detector(model, frame)
    model.show_result(frame, result, wait_time=1, show=True, out_file='results')

**Comment by xincyu** [comment]
I've solved it 🗼

video_writer = cv2.VideoWriter('output.mp4', fourcc, target_fps, (frame_width, frame_height))
video_writer.write(result_img)

**Comment by DorothysDad** [comment]
can you give the all of the code, i can not run the video detection thanks!
