### ISSUE TITLE
Need understanding regarding coalesce vs all-reduce

### ISSUE THREAD

**Issue by anuj-sharma-19** [open-mmlab/mmdetection#4446]
Hi,

First of all, thanks a lot for the codebase.

I am actually using `CenterPoint` codebase, which uses multi-gpu training blocks from here. I am however, using pytorch-lightning instead for the multi-gpu setup, but am having some issues in replicating the numbers. So, am going through the training process, and can see that their code uses `coalesce` method, similar to as in your code https://github.com/open-mmlab/mmdetection/blob/5853fa4aa4e0a3769763eb213070d86a7d40210d/mmdet/core/utils/dist_utils.py#L23.

I was curious about how is it different than `all_reduce_grads` which first divides the tensor by world size and then sums up? Could you please let me know your thoughts on this, or how does your multi-gpu training setup compare against `pytorch-lightning`? It would be really great to get your guidance on this.

Thank You, looking forward to your reply.

Best Regards,
Anuj

**Comment by ZwwWayne** [comment]
We just follow the practices in Pytorch DDP.
