### ISSUE TITLE
Display and output fault - Need Solution

### ISSUE THREAD

**Issue by nuggetchr** [open-mmlab/mmdetection#4447]
Hi, I am new to the mmdetection community.

After installation I have been able to verify the collect_env.py script returns the right result, I am facing an error when I attempt to run mmdetection with the following output:

`UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(`

from the utils.py file.

This is an attempt with the demo.jpg image.

I am running 18.04 Ubuntu Linux with CUDA rt 11.0

Please help!

**Comment by xvjiarui** [comment]
Hi @nuggetchr 
This is a warning or error. Did you encounter any unexpected behaviors?

**Comment by nuggetchr** [comment]
> Hi @nuggetchr
> This is a warning or error. Did you encounter any unexpected behaviors?

It appears to be a warning. However, I do not see the program executing through

**Comment by pedrozamboni** [comment]
I'm having the same problem for the last few days when running inferences. Apparently it even calculates the metrics (evaluete) but when I am going to display the images with the inferences he prints the images without them.

**Comment by guillaumefrd** [comment]
I have the same warning when using the inference_demo.ipynb

**Comment by YClemontree** [comment]
you can alter your pipline just like this
`test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 1024),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            # dict(type='ImageToTensor', keys=['img']),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img']),
        ])
]`

**Comment by xvjiarui** [comment]
Hi @guillaumefrd 
I just tried latest master branch (git has `3620bb7`), the `inference_demo.ipynb` works fine. You may have a try. 

Feel free to reopen this issue if there is still error.

**Comment by HusterRC** [comment]
> > Hi @nuggetchr
> > This is a warning or error. Did you encounter any unexpected behaviors?
> 
> It appears to be a warning.
> 
> UPDATE: I was able to successfully 'save' the image and it was computed correctly. The issue appears to be in 'displaying' the result, which it will not seem to do. I am however not able to do the same with a video file. Attached is my code:
> 
> ```
> from mmdet.apis import init_detector, inference_detector
> import mmcv
> 
> config_file = 'configs/hrnet/cascade_mask_rcnn_hrnetv2p_w32_20e_coco.py'
> checkpoint_file = 'checkpoints/cascade_mask_rcnn_hrnetv2p_w32_20e_coco_20200512_154043-39d9cf7b.pth'
> 
> model = init_detector(config_file, checkpoint_file, device='cuda:0')
> 
> video = mmcv.VideoReader('demo/dl13.mp4')
> for frame in video:
>     result = inference_detector(model, frame)
>     model.show_result(frame, result, wait_time=1)
> 
> model.show_result(video, result, out_file='result4.mp4')
> 
> model.show_result(video, result)
> ```
> 
> This spends time computing, then returns the TypeError with no file created:
> 
> `File "/home/comp1/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/image/io.py", line 174, in imread raise TypeError('"img" must be a numpy array or a str or ' TypeError: "img" must be a numpy array or a str or a pathlib.Path object`

I am new to the mmdetection community, can u tell me how to solve thiss issue, thanks!

**Comment by aiyadehaijiao** [comment]
> you can alter your pipline just like this
> `test_pipeline = [ dict(type='LoadImageFromFile'), dict( type='MultiScaleFlipAug', img_scale=(1024, 1024), flip=False, transforms=[ dict(type='Resize', keep_ratio=True), dict(type='RandomFlip'), dict(type='Normalize', **img_norm_cfg), dict(type='Pad', size_divisor=32), # dict(type='ImageToTensor', keys=['img']), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img']), ]) ]`

Could you tell more about it? For example, in which file is it modified?

**Comment by sunjeet95** [comment]
> you can alter your pipline just like this
> `test_pipeline = [ dict(type='LoadImageFromFile'), dict( type='MultiScaleFlipAug', img_scale=(1024, 1024), flip=False, transforms=[ dict(type='Resize', keep_ratio=True), dict(type='RandomFlip'), dict(type='Normalize', **img_norm_cfg), dict(type='Pad', size_divisor=32), # dict(type='ImageToTensor', keys=['img']), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img']), ]) ]`

Can please tell me how it works? I need the output data in the format of the keys. I cannot really follow the tutorial given in the documentation. I have tried everything regarding this.

**Comment by ZahraAnam** [comment]
Hi! I am new to mmdetection and facing the same problem.
After I changed it as suggested then the following warning appears:
/mmdetection/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
  
  Any guidance please?
