### ISSUE TITLE
Unrecognized dataset

### ISSUE THREAD

**Issue by leaving-voider** [open-mmlab/mmdetection#4448]
When I trained the tikki_tiny dataset, it just went well.

But when I trained the same model on my own dataset GWHD, the training process went well but the evaluation gave me an error:
![image](https://user-images.githubusercontent.com/68451409/104531078-50503580-5648-11eb-9c8f-486610b88936.png)

And I tried to debug this, I found it's because the label 'ear' in my GWHD dataset does not appear in the dict showed below:
![image](https://user-images.githubusercontent.com/68451409/104531158-84c3f180-5648-11eb-8086-4638cb21637d.png)

But the evaluation process of kitti_tiny dataset didn't go into this function, why would my GWHD dataset get into it? Does anyone have the same question?

**Comment by xvjiarui** [comment]
It is depended on which dataset class you inherited from. 
You may add your class names into the dict.

**Comment by leaving-voider** [comment]
@xvjiarui thanks for your reply. I have solved this problem~
