### ISSUE TITLE
After training several epochs, CUDA out of memory

### ISSUE THREAD

**Issue by Hanswufe** [open-mmlab/mmdetection#4450]
I train cascade RCNN on custom dataset and the max number of gt bboxes in each image is 45. At the first time, out of memory is reported at the second epoch. At the second time, out of memory is reported at the fifth epoch.

**Reproduction**

1. What command or script did you run?
./tools/train.sh

2. samples_per_gpu = 4,num_workers=2, 2 gpus

**Environment**
1. pytorch 1.3+cuda10
2. TITAN XP 12G
![image](https://user-images.githubusercontent.com/43342643/104587945-ac47a800-56a2-11eb-968e-9d0823131ffc.png)

**Comment by xvjiarui** [comment]
Hi @Hanswufe 
You may try to use 2 images per gpu.

**Comment by ZwwWayne** [comment]
There are some way that may help https://mmdetection.readthedocs.io/en/latest/faq.html#training
