### ISSUE TITLE
Import Error: import mmcv

### ISSUE THREAD

**Issue by Fuhan1994** [open-mmlab/mmdetection#4451]
when i have a try to run test.py, there is an import error as below:

_from .cv2 import *
ImportError: /lib64/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates_

After i checked the information, I found that this is a problem that the _cairo_ version is too low.  but I have no idea how to install the right _cairo_ version under non-root permissions on linux. So does any one have the same problem?

**Comment by ZwwWayne** [comment]
You may try to install it through conda. Anaconda maintains this package [here](https://anaconda.org/anaconda/cairo).

**Comment by Fuhan1994** [comment]
> You may try to install it through conda. Anaconda maintains this package [here](https://anaconda.org/anaconda/cairo).

it does work, thank you very much!
