### ISSUE TITLE
SSD300 inferencing performance on CPU

### ISSUE THREAD

**Issue by devloper13** [open-mmlab/mmdetection#4457]
What should be the performance of SSD300 on CPU while inferencing? By performance I mean it's speed mainly. What I could achieve is about 1.6 FPS on CPU while iferencing. Whereas, I could get about 9 FPS of the same architecture on Tensorflow Object Detection API. Is this expected? 

Note: On inferencing only 2 of my 4 cores were being used on MMDetection. Is there a way to increase this?

**Comment by ZwwWayne** [comment]
We have not benchmarked the CPU inference speed of models for now. So it might be reasonable as we did no optimization for that. This should also be related to the implementation of PyTorch.
