### ISSUE TITLE
fpn中，通过对特征金字塔的最后一层使用max_pooling产生第五个特征图，为什么代码中的max_pooling使用kernel_size=1,而不是等于2.

### ISSUE THREAD

**Issue by ifreewolf** [open-mmlab/mmdetection#4458]
文件：mmdetection/mmdet/models/necks/fpn.py 
line 204：outs.append(F.max_pool2d(outs[-1], 1, stride=2))
这个代码的目的是从特征金字塔的最后一层经过一个下采样获得第五个特征层，为什么kernel_size等于1？？？

**Comment by shinya7y** [comment]
FPN paper: https://arxiv.org/pdf/1612.03144.pdf
> P6 is simply a stride two subsampling of P5.

Detectron:
https://github.com/facebookresearch/Detectron/blob/b02a680bf358d3c8bab526a10c8271630c0930cb/detectron/modeling/FPN.py#L225-L229
``` python
# Use max pooling to simulate stride 2 subsampling
P6_blob = model.MaxPool(P6_blob_in, P6_name, kernel=1, pad=0, stride=2)
```

**Comment by ZwwWayne** [comment]
Just following the convention of the official release.
