### ISSUE TITLE
How should I train faster rcnn from scratch

### ISSUE THREAD

**Issue by sakurasakura1996** [open-mmlab/mmdetection#4460]
I want to train my custom dataset with faster rcnn from scratch, but it defaultly download resnet50 pretrained weights .What do I need to change to solve this problem

**Comment by yuzhj** [comment]
set ```pretrained=None```

**Comment by ZwwWayne** [comment]
Examples are in [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/scratch).
