### ISSUE TITLE
How to change a module name of a pretrained model

### ISSUE THREAD

**Issue by Andrew-Zhu** [open-mmlab/mmdetection#4461]
I want to change the stored neck name in a trained model. For example, I train a model with the neck name as ABC, and I store the model. Then I want to rename the neck part in the .pth file as DEF and load the checkpoint file with a new model (with new neck name DEF).

 I have tried to replace the neck name in the state_dict['meta']['config'] and store the state_dict as new .pth, but when I load the model, it still shows "unexpected key in source state_dict: neck." "missing key in source state_dict: neck."

**Comment by ZwwWayne** [comment]
You need to modify the key of model weights in state_dict rather than changing the config of meta.
