### ISSUE TITLE
mmdetetction v2.8.0 needmmcv-full >=v1.2.4 on windows 10 

### ISSUE THREAD

**Issue by leewi9** [open-mmlab/mmdetection#4463]
https://download.openmmlab.com/mmcv/dist/index.html

There is no mmcv-full >=v1.2.4 on windows 10

could you please add for us, thanks.

**Comment by ZwwWayne** [comment]
We have not officially release the regular build of MMCV on windows due to limited resources. For now, users should build it on their own machines. We may support it in the future.
