### ISSUE TITLE
Why center offset in anchor-base models(Faster RCNN, RetinaNet) is 0, but in anchor-free models(FoveaBox, FCOS) is 0.5

### ISSUE THREAD

**Issue by jbwang1997** [open-mmlab/mmdetection#4464]
Hello,
I recently read the code of FCOS and FoveaBox. And I find the center offset of FCOS and FoveaBox points is 0.5, but the center offset of Faster RCNN and RetinaNet anchors is 0.

I don't know why it's different between anchor-base and anchor-free models.

Have a nice day!

**Comment by ZwwWayne** [comment]
This is because for Anchor-based methods, we adopt the new convention as discussed [here](https://mmdetection.readthedocs.io/en/latest/compatibility.html#coordinate-system). But for the anchor-free methods, we keep their convention as they were released and described in their original paper.
