### ISSUE TITLE
Question about changing image size and other general questions

### ISSUE THREAD

**Issue by waddington-ou-phd-1** [open-mmlab/mmdetection#4465]
Hi,

I really like the MMDetection toolbox, it is a great time saver and very useful! I have a few questions:

1. Nearly all of the models use images of size 1333x800, now this is relatively large for object detection. If I want to train a model on my own dataset with smaller images, e.g. 500x500, then I change the img_scale in the pipeline configs. But if I want to use a model pre-trained on ImageNet, what happens here? Do I still get the pre-trained weights and do they fit the architecture as expected? I have tried this and see that MMDetection does indeed still download a checkpoint, but I'm not certain that it works as expected?

My goal is to use transfer learning from ImageNet weights, as everybody does these days, onto my own dataset, but with smaller images for training on my dataset.

I have seen a reason that 1333x800 is a standard MS COCO size for testing, but I don't see this size in literature, even when using MS COCO.

2. An additional question, what does num_workers_per_gpu do? Does it load as many batches onto the GPU as number of workers?

3. Another question: how does distributed training work? I assume the model must be on each GPU, and the batch size is per GPU, but how are the results combined and weight updates calculated and actioned?

4. What are "caffe" models? Is there something I can read about them

Thanks

**Comment by ZwwWayne** [comment]
1. It will be fine, you only need to change the image size and can directly use the pre-trained model. For COCO dataset we simply adopt the conventions of the communities' papers.
2. num_workers_per_gpu decide how many workers will be used to pre-fetch data for each single GPU. It will not change the batch size, but will accelerate data loading process.
3. For this question you can refer to [PyTorch tutorial](https://pytorch.org/tutorials/beginner/dist_overview.html).
4. caffe models are ResNet trained in the original caffe style, where the downsampling operation is done in `1x1` convs.

**Comment by waddington-ou-phd-1** [comment]
Thank you for the answers. \#1 is exactly what I'm after so thanks for that.

**Comment by GeorgePearse** [comment]
With the RTMDet large model, I hit an error if I try to train on (1920 * 1080), while (960 * 540) works fine. 

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/24a38f51-0895-4cc6-968c-568f6649b369/Untitled.png)

Do I need to adapt the definition of the PA FPN in the config (which seems to be where the error is hit)? 

```
    neck=dict(
        type='CSPNeXtPAFPN',
        # in_channels=[256, 512, 1024],
        in_channels=[512, 1024, 2048],
        out_channels=256,
        num_csp_blocks=3,
        expand_ratio=0.5,
        norm_cfg=dict(type='SyncBN'),
        act_cfg=dict(type='SiLU', inplace=True)),
```

**Comment by Byte247** [comment]
> With the RTMDet large model, I hit an error if I try to train on (1920 * 1080), while (960 * 540) works fine.
> 
> ```
>   File "train.py", line 176, in <module>
>     main()
>   File "train.py", line 172, in main
>     runner.train()
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1701, in train
>     model = self.train_loop.run()  # type: ignore
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
>     self.run_epoch()
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
>     self.run_iter(idx, data_batch)
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
>     outputs = self.runner.model.train_step(
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
>     losses = self._run_forward(data, mode='loss')  # type: ignore
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
>     results = self(**data, mode=mode)
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward
>     return self.loss(inputs, data_samples)
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 77, in loss
>     x = self.extract_feat(batch_inputs)
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 148, in extract_feat
>     x = self.neck(x)
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ubuntu/environments/vision-research/lib/python3.8/site-packages/mmdet/models/necks/cspnext_pafpn.py", line 153, in forward
>     torch.cat([upsample_feat, feat_low], 1))
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 136 but got size 135 for tensor number 1 in the list.
> ```
> 
> Do I need to adapt the definition of the PA FPN in the config (which seems to be where the error is hit)?
> 
> ```
>     neck=dict(
>         type='CSPNeXtPAFPN',
>         in_channels=[512, 1024, 2048],
>         out_channels=256,
>         num_csp_blocks=3,
>         expand_ratio=0.5,
>         norm_cfg=dict(type='SyncBN'),
>         act_cfg=dict(type='SiLU', inplace=True)),
> ```

Did you find a solution for this?

**Comment by GeorgePearse** [comment]
@igaffney215 will add this as an issue in our repo, but would be handy if we could get this to work.
