### ISSUE TITLE
MMCV CUDA Compiler : not available

### ISSUE THREAD

**Issue by sakurasakura1996** [open-mmlab/mmdetection#4471]
Thanks for your work! When I run "python mmdet/utils/collect_env.py",the output is:
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (GCC) 5.4.0
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.5.1
MMCV: 1.2.5
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: not available
MMDetection: 2.8.0+2d2e5c6

Why MMCV CUDA Compiler is not available. I use slurm server, When I at gpu node, I can't install mmcv-full with pip install mmcv-full == 1.2.5.

**Comment by ZwwWayne** [comment]
This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.

**Comment by sakurasakura1996** [comment]
> This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.

Thank you for your reply, My question is: I use slurm gpu server, when i at local node, I can install packages, but when i at gpu node, i can't install mmcv-full in conda env. so when I try MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full in local node's env, then when I go to gpu node, it also shows that MMCV CUDA Complier : not available.

**Comment by ZwwWayne** [comment]
Does your local node have GPU? And what is the output of `python -c 'import mmcv; import mmcv.ops'` when you run this command at local node or slurm gpu server? 
Usually, the local node should have a similar environment as slurm server if the local node is the management node?

**Comment by zhengly123** [comment]
> This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.

I meet the same problem with the following installation commands
```
MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
# install mmdet
pip install -v -e .
```
The output of `mmdet/utils/collect_env.py` is
```
sys.platform: linux
Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
CUDA available: True
GPU 0: Tesla P100-PCIE-16GB
GPU 1: GeForce GTX 1080
CUDA_HOME: /home/spack/opt/spack/linux-debian10-skylake_avx512/gcc-8.3.0/cuda-10.2.89-v5oqq5nht4riunm3zxxfmkmt5yhr22ts
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Spack GCC) 7.4.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.5.1
MMCV: 1.3.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: not available
MMDetection: 2.11.0+5ebba9a
```
I thought `MMCV CUDA Compiler` is determined at compilation time. So does this mean `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
` fetches a wheel package without CUDA support?

**Comment by karthiksharma98** [comment]
> > This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.
> 
> I meet the same problem with the following installation commands
> 
> ```
> MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
> # install mmdet
> pip install -v -e .
> ```
> 
> The output of `mmdet/utils/collect_env.py` is
> 
> ```
> sys.platform: linux
> Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
> CUDA available: True
> GPU 0: Tesla P100-PCIE-16GB
> GPU 1: GeForce GTX 1080
> CUDA_HOME: /home/spack/opt/spack/linux-debian10-skylake_avx512/gcc-8.3.0/cuda-10.2.89-v5oqq5nht4riunm3zxxfmkmt5yhr22ts
> NVCC: Cuda compilation tools, release 10.2, V10.2.89
> GCC: gcc (Spack GCC) 7.4.0
> PyTorch: 1.8.0
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 10.2
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
>   - CuDNN 7.6.5
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> 
> TorchVision: 0.9.0
> OpenCV: 4.5.1
> MMCV: 1.3.0
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: not available
> MMDetection: 2.11.0+5ebba9a
> ```
> 
> I thought `MMCV CUDA Compiler` is determined at compilation time. So does this mean `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html ` fetches a wheel package without CUDA support?

I have the same problem. It goes away when I downgrade to pytorch 1.7.0 and re-install the compatible mmcv. I think the binary for cuda 10.2 and pytorch 1.8.0 is incorrect.

**Comment by zhengly123** [comment]
> > > This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.
> > 
> > 
> > I meet the same problem with the following installation commands
> > ```
> > MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
> > # install mmdet
> > pip install -v -e .
> > ```
> > 
> > 
> > The output of `mmdet/utils/collect_env.py` is
> > ```
> > sys.platform: linux
> > Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
> > CUDA available: True
> > GPU 0: Tesla P100-PCIE-16GB
> > GPU 1: GeForce GTX 1080
> > CUDA_HOME: /home/spack/opt/spack/linux-debian10-skylake_avx512/gcc-8.3.0/cuda-10.2.89-v5oqq5nht4riunm3zxxfmkmt5yhr22ts
> > NVCC: Cuda compilation tools, release 10.2, V10.2.89
> > GCC: gcc (Spack GCC) 7.4.0
> > PyTorch: 1.8.0
> > PyTorch compiling details: PyTorch built with:
> >   - GCC 7.3
> >   - C++ Version: 201402
> >   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
> >   - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
> >   - OpenMP 201511 (a.k.a. OpenMP 4.5)
> >   - NNPACK is enabled
> >   - CPU capability usage: AVX2
> >   - CUDA Runtime 10.2
> >   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
> >   - CuDNN 7.6.5
> >   - Magma 2.5.2
> >   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> > 
> > TorchVision: 0.9.0
> > OpenCV: 4.5.1
> > MMCV: 1.3.0
> > MMCV Compiler: GCC 7.3
> > MMCV CUDA Compiler: not available
> > MMDetection: 2.11.0+5ebba9a
> > ```
> > 
> > 
> > I thought `MMCV CUDA Compiler` is determined at compilation time. So does this mean `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html ` fetches a wheel package without CUDA support?
> 
> I have the same problem. It goes away when I downgrade to pytorch 1.7.0 and re-install the compatible mmcv. I think the binary for cuda 10.2 and pytorch 1.8.0 is incorrect.

Finally, I built it from source and it works well with cu10.2 and torch1.8.0.

**Comment by freshn** [comment]
> > > This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.
> > 
> > 
> > I meet the same problem with the following installation commands
> > ```
> > MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
> > # install mmdet
> > pip install -v -e .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The output of `mmdet/utils/collect_env.py` is
> > ```
> > sys.platform: linux
> > Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
> > CUDA available: True
> > GPU 0: Tesla P100-PCIE-16GB
> > GPU 1: GeForce GTX 1080
> > CUDA_HOME: /home/spack/opt/spack/linux-debian10-skylake_avx512/gcc-8.3.0/cuda-10.2.89-v5oqq5nht4riunm3zxxfmkmt5yhr22ts
> > NVCC: Cuda compilation tools, release 10.2, V10.2.89
> > GCC: gcc (Spack GCC) 7.4.0
> > PyTorch: 1.8.0
> > PyTorch compiling details: PyTorch built with:
> >   - GCC 7.3
> >   - C++ Version: 201402
> >   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
> >   - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
> >   - OpenMP 201511 (a.k.a. OpenMP 4.5)
> >   - NNPACK is enabled
> >   - CPU capability usage: AVX2
> >   - CUDA Runtime 10.2
> >   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
> >   - CuDNN 7.6.5
> >   - Magma 2.5.2
> >   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> > 
> > TorchVision: 0.9.0
> > OpenCV: 4.5.1
> > MMCV: 1.3.0
> > MMCV Compiler: GCC 7.3
> > MMCV CUDA Compiler: not available
> > MMDetection: 2.11.0+5ebba9a
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I thought `MMCV CUDA Compiler` is determined at compilation time. So does this mean `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html ` fetches a wheel package without CUDA support?
> 
> I have the same problem. It goes away when I downgrade to pytorch 1.7.0 and re-install the compatible mmcv. I think the binary for cuda 10.2 and pytorch 1.8.0 is incorrect.

Yes, it works. Thank you for saving my afternoon.

**Comment by evu** [comment]
> This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.

It seems like this option `MMCV_WITH_OPS` could be better-documented... I see it mentioned in a few of the Chinese-language docs but it seems like it is important to set this when you are installing mmcv in a situation like, say, a docker image build.

**Comment by shimmerjordan** [comment]
The similar issue occur when I first build the environment then connect the GPU to the machine. When I first apply the GPU resource then run setup.py to build, it is solved. This was not mmcv-full issue on my machine.

**Comment by hzm8341** [comment]
I use follow shell to solve it:

pip install setuptools==59.5.0
pip uninstall -y shapely
pip install shapely==1.8.0
pip uninstall -y  mmcv
pip uninstall -y  mmcv-full
pip install mmcv==1.4.0 mmdet==2.20.0
pip install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html 
pip install mmcv==1.4.0 mmdet==2.20.0
cd /rtx/huzhengming/3d_mot/
python setup.py develop
python /opt/conda/lib/python3.8/site-packages/mmdet/utils/collect_env.py

**Comment by vetsasai** [comment]
> > This is because the MMCV is not installed with CUDA. Please try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full`.
> 
> I meet the same problem with the following installation commands
> 
> ```
> MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html
> # install mmdet
> pip install -v -e .
> ```
> 
> The output of `mmdet/utils/collect_env.py` is
> 
> ```
> sys.platform: linux
> Python: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
> CUDA available: True
> GPU 0: Tesla P100-PCIE-16GB
> GPU 1: GeForce GTX 1080
> CUDA_HOME: /home/spack/opt/spack/linux-debian10-skylake_avx512/gcc-8.3.0/cuda-10.2.89-v5oqq5nht4riunm3zxxfmkmt5yhr22ts
> NVCC: Cuda compilation tools, release 10.2, V10.2.89
> GCC: gcc (Spack GCC) 7.4.0
> PyTorch: 1.8.0
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 10.2
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
>   - CuDNN 7.6.5
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> 
> TorchVision: 0.9.0
> OpenCV: 4.5.1
> MMCV: 1.3.0
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: not available
> MMDetection: 2.11.0+5ebba9a
> ```
> 
> I thought `MMCV CUDA Compiler` is determined at compilation time. So does this mean `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html ` fetches a wheel package without CUDA support?

Thanks for giving this... I lost lot of time finding different options, but found the right one now.
