### ISSUE TITLE
FP16 training is slower than FP32 traing

### ISSUE THREAD

**Issue by wynterr** [open-mmlab/mmdetection#4476]
I'm trying to use fp16 to train a SSD on COCO. But I found that after using fp16, the memory usage decrease and speed is about 10% slower then fp32. After analyzing with nsight, I found that when using fp16, the step that copy the input data from cpu to gpu can not be paralleled with the main cuda stream(optimizer). And fp16 didn't decrease the inference time or the backward time. 
I'm training on a single 2080TI. My mmdetection version is 2.7.0 and mmcv version is mmcv-full 1.2.2.

Below is the FP32 training, the step that copy the input data from cpu to gpu is paralleled with the main cuda stream(optimizer).
![图片](https://user-images.githubusercontent.com/29707174/105003276-6a857b80-5a6d-11eb-9657-5a2b51f42a69.png)
And the fp16 training, not paralleled
![图片](https://user-images.githubusercontent.com/29707174/105003392-8f79ee80-5a6d-11eb-921a-c500bc414981.png)
Do you have any idea about why this is happening? Thanks

**Comment by wynterr** [comment]
Also, when I use apex for amp training, the copying step still can not be paralleled with the main cuda stream, but the backward time is decreased by about 20%.

**Comment by ZwwWayne** [comment]
FP16 training has not been fully benchmarked, we only try it on V100 actually. So we are not very sure what the reason is.

**Comment by jshilong** [comment]
Half-precision is not faster than full-precision on all devices.
Feel free to reopen the issue if there is any question.
