### ISSUE TITLE
The test video can be displayed in real time, but cannot be saved

### ISSUE THREAD

**Issue by youzi260** [open-mmlab/mmdetection#4477]
I created a video.py code as follows：
import argparse
import os
import cv2
import torch

from mmdet.apis import inference_detector, init_detector

file_path = __file__

dir_path = os.path.dirname(file_path)

# default_video_path=os.path.join(dir_path,'result.mp4') #定义的输出，默认是和video.py同目录的文件
default_video_path = 'demo/result.mp4'

def parse_args():
    parser = argparse.ArgumentParser(description='MMDetection webcam demo')
    parser.add_argument('config', help='test config file path')
    parser.add_argument('checkpoint', help='checkpoint file')
    parser.add_argument(
        '--device', type=str, default='cuda:0', help='CPU/CUDA device option')
    parser.add_argument(
        '--file', type=str, help='test video path')  # 输入视频从哪输入
    parser.add_argument(
        '--out', type=str, default=default_video_path, help='bbox score threshold')  # 输出视频从哪输出
    parser.add_argument(
        '--camera-id', type=int, default=0, help='camera device id')
    parser.add_argument(
        '--score-thr', type=float, default=0.5, help='bbox score threshold')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    device = torch.device(args.device)

    model = init_detector(args.config, args.checkpoint, device=device)

    camera = cv2.VideoCapture(args.file)  # 把这个地方换成视频位置，就不会调用摄像头了

    capture = cv2.VideoCapture(args.file)  # 希望输入视频和输出视频宽高一致
    width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))  # 获得源视频宽高
    height = int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))

    fps = capture.get(cv2.CAP_PROP_FPS)  # 获得帧数
    fourcc = cv2.VideoWriter_fourcc('M', 'P', '4', '2')

    video_writer = cv2.VideoWriter(args.out, fourcc, fps, (width, height))
    # out是保存视频的位置；保存的格式，MP4v；帧数；宽、高；

    print('Press "Esc", "q" or "Q" to exit.')
    while True:  # 无限循环，一帧一帧的读取，一秒24帧
        ret_val, img = camera.read()  # 返回bool值，读取成功就是ture
        print(img)
        result = inference_detector(model, img)

        ch = cv2.waitKey(1)
        if ch == 27 or ch == ord('q') or ch == ord('Q'):  # 27对应键盘上Esc这个键，ord()对应chr()这个函数，在里面传入Q，就会输出对应的ASCIK码
            break

        model.show_result(
            img, result, score_thr=args.score_thr, wait_time=1, show=True)

if __name__ == '__main__':
    main()

——————————————————————————————————
I put the video.py file and the video 1.mp4 to be detected in the demo folder
Then I enter the command on the terminal：
python demo/video.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py WORK_DIR/latest.pth --file /demo/1.mp4
——————————————————————————————————
The environment is as follows, Ubuntu, cuda10.1, python3.6, and then you can display the detection effect in real time, but you can't save it. The error report is as follows. I hope you can help me！！The error is as follows：
key Error : 'img'

**Comment by hhaAndroid** [comment]
Please provide more detailed error information, thank you

**Comment by hhaAndroid** [comment]
@youzi260  I run your script, but no errors were found.  I found the `video_writer` is not used, so it's can't save the file. Please provide more detailed error information about `video_writer`.

**Comment by youzi260** [comment]
import argparse
import os
import cv2
import torch

from mmdet.apis import inference_detector, init_detector

file_path=__file__

dir_path=os.path.dirname(file_path)

#default_video_path=os.path.join(dir_path,'result.mp4') #定义的输出，默认是和video.py同目录的文件
default_video_path='demo/result.mp4'

def parse_args():
    parser = argparse.ArgumentParser(description='MMDetection webcam demo')
    parser.add_argument('config', help='test config file path')
    parser.add_argument('checkpoint', help='checkpoint file')
    parser.add_argument(
        '--device', type=str, default='cuda:0', help='CPU/CUDA device option')
    parser.add_argument(
        '--file', type=str, help='test video path')#输入视频从哪输入
    parser.add_argument(
        '--out', type=str, default=default_video_path, help='bbox score threshold')#输出视频从哪输出
    parser.add_argument(
        '--camera-id', type=int, default=0, help='camera device id')
    parser.add_argument(
        '--score-thr', type=float, default=0.5, help='bbox score threshold')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    device = torch.device(args.device)

    model = init_detector(args.config, args.checkpoint, device=device)

    camera = cv2.VideoCapture(args.file)#把这个地方换成视频位置，就不会调用摄像头了
    
    capture=cv2.VideoCapture(args.file)#希望输入视频和输出视频宽高一致
    width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))#获得源视频宽高
    height=int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))

    fps =capture.get(cv2.CAP_PROP_FPS)#获得帧数
    fourcc=cv2.VideoWriter_fourcc('M','P','4','2')

    video_writer=cv2.VideoWriter(args.out,fourcc,fps,(width,height))
    #out是保存视频的位置；保存的格式，MP4v；帧数；宽、高；

    print('Press "Esc", "q" or "Q" to exit.')
    while True:#无限循环，一帧一帧的读取，一秒24帧
        ret_val, img = camera.read()#返回bool值，读取成功就是ture
        print (img)
        result = inference_detector(model, img)

        ch = cv2.waitKey(1)
        if ch == 27 or ch == ord('q') or ch == ord('Q'): #27对应键盘上Esc这个键，ord()对应chr()这个函数，在里面传入Q，就会输出对应的ASCIK码
            break

        model.show_result(
            img, result, score_thr=args.score_thr, wait_time=1, show=True)


if __name__ == '__main__':
    main()

def main():
    args = parse_args()

    if not args.file:
        print("No target file!")
        exit(0)

    if not torch.cuda.is_available():
        args.device='cpu'

    device = torch.device(args.device)
    print('device',args.device)

    model = init_detector(args.config, args.checkpoint, device=device)

    camera = cv2.VideoCapture(args.file)#把这个地方换成视频位置，就不会调用摄像头了

    capture=cv2.VideoCapture(args.file)#希望输入视频和输出视频宽高一致
    width = int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))#获得源视频宽高
    height=int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))

    fps =capture.get(cv2.CAP_PROP_FPS)#获得帧数

    video_writer=cv2.VideoWriter(args.out,cv2.VideoWriter_fourcc(*'mp4v')),fps,(width,height)
    #out是保存视频的位置；保存的格式，MP4v；帧数；宽、高；

    count=0 #计数，看看成功保存了多少帧
    print('Press "Esc", "q" or "Q" to exit.')
    while True:#无限循环，一帧一帧的读取，一秒24帧
        torch.cuda.empty_cache() #清一下不必要的缓存解除GPU的占用
        ret_val, img = camera.read()#返回bool值，读取成功就是ture
        if ret_val:
            if count<0:#检测一半停了，可以改一下这，960，下次就会从960接着检测
                count += 1
                print('Write {} in result Successfully!'.format(count))
                continue
            result = inference_detector(model, img)

            #中途不想检测了，按这三个键可以停止
            ch = cv2.waitKey(1)
            if ch == 27 or ch == ord('q') or ch == ord('Q'): #27对应键盘上Esc这个键，ord()对应chr()这个函数，在里面传入Q，就会输出对应的ASCIK码
                break
            frame=model.show_result(img,result,score_thr=args.score_thr,thickness=1,font_scale=1,show=False,wait_time=1)
            #用frame把前边的img接收掉
            cv2.imshow('frame',frame)

            if len(frame)>=1 or frame: #检测图片时，可能会有一张黑幕，把错误的图片过滤掉
                video_writer.write(frame)
                count+=1
                print('Write {} in result Successfully!'.format(count))
        else:
             print('Try to read video fail at {}'.format(args.file))
             break

    capture.release()
    video_writer.release()
    cv2.destroyAllWindows()

if __name__=='__main__':
    main()'''

**Comment by hhaAndroid** [comment]
@youzi260 Video result save is temporarily not supported, We will add this feature these days, if it is added, it will notify you immediately
