### ISSUE TITLE
Move model and dataset config files to mmdet folder

### ISSUE THREAD

**Issue by KamalM9** [open-mmlab/mmdetection#4481]
Thanks for gathering all these models and datasets in one place. We'd like to reference the configs from our code (changing datasets often, without needing to create new config files). Would it be possible for you to move all model and dataset configuration files into the mmdet folder, so that they can be referenced from python? 

Example:
```from mmdet.configs.fcos import fcos_r50_caffe_fpn_4x4_1x_coco```

**Comment by hhaAndroid** [comment]
I don't recommend this，because it has an inheritance relationship in the configuration file that needs to be initialized correctly through the `Config.fromfile()`

**Comment by alexander-soare** [comment]
@hhaAndroid is the correct way then to copy the configs from github into ones project directory?
