### ISSUE TITLE
Missing documentation: Create datasets

### ISSUE THREAD

**Issue by dreamflasher** [open-mmlab/mmdetection#4482]
There is this documentation: https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md#prepare-datasets

But it's missing crucial steps so the documentation is barely useable.

Please extend the documentation by 

1) Providing URLs to the datasets. They are hard to find (unecessary step for users) and in a few cases unclear which version/which format is being used.

2) Something seems off with the Pascal VOC dataset. From the folder structure you expect both the 2012 and 2007 dataset to exist, also `https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/datasets/voc0712.py` looks like that. Aren't previous content datasets included in the newer ones? (EDIT: Just figured it out by reading the history table on the dataset page → would be great to document this tribal knowledge)

**Comment by ZwwWayne** [comment]
Thanks for your kind suggestion, we will fix it in the next release.
