### ISSUE TITLE
What is _delete_=True meaning in optimizer_config?

### ISSUE THREAD

**Issue by hust-nj** [open-mmlab/mmdetection#4485]
https://github.com/open-mmlab/mmdetection/blob/e1dd6e28af69a1fd6477494111b0f73ad5b24298/configs/fcos/fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_4x4_1x_coco.py#L49

**Comment by v-qjqs** [comment]
Hi @hust-nj, `_delete_True` means removing the inherited properties and overwriting based on your customized settings .

**Comment by hust-nj** [comment]
> Hi @hust-nj, `_delete_True` means removing the inherited properties and overwriting based on your customized settings .

So it means removing the whole optimizer_config setting defined in base config, and re-defined it by `optimizer_config=dict(grad_clip=None)`. Right?

**Comment by v-qjqs** [comment]
> > Hi @hust-nj, `_delete_True` means removing the inherited properties and overwriting based on your customized settings .
> 
> So it means removing the whole optimizer_config setting defined in base config, and re-defining it by `optimizer_config=dict(grad_clip=None)`. Right?

yes.

**Comment by hust-nj** [comment]
> > > Hi @hust-nj, `_delete_True` means removing the inherited properties and overwriting based on your customized settings .
> > 
> > 
> > So it means removing the whole optimizer_config setting defined in base config, and re-defining it by `optimizer_config=dict(grad_clip=None)`. Right?
> 
> yes.

Thank you!
