### ISSUE TITLE
./compile.sh error in Building nms op...

### ISSUE THREAD

**Issue by Smoothing97** [open-mmlab/mmdetection#449]
**This error really confused me,and I check the version of gcc.I run `./compile.sh` before and got my gcc4.8.5 should be updated to gcc4.9 or more,so I update gcc5.3.0 according to an issue before.However,there is new error:**

`Building nms op...

rm -f *.so
echo "Compiling nms kernels..."                                                  
Compiling nms kernels...                                                         
python setup.py build_ext --inplace                                              
running build_ext                                                                
building 'cpu_nms' extension                                                     
gcc -pthread -B /home/liuran/anaconda3/envs/mmdetection/compiler_compat -Wl,--sy sroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC - I/home/liuran/anaconda3/envs/mmdetection/lib/python3.6/site-packages/numpy/core/ include -I/home/liuran/anaconda3/envs/mmdetection/include/python3.6m -c cpu_nms. cpp -o build/temp.linux-x86_64-3.6/cpu_nms.o -Wno-unused-function -Wno-write-str ings                                                                             cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC  but not for C++                                                                  cpu_nms.cpp: In function ‘PyObject* __pyx_pf_7cpu_nms_cpu_nms(PyObject*, PyArray Object*, PyObject*)’:                                                            
cpu_nms.cpp:2385:34: error: ‘PyArrayObject {aka struct tagPyArrayObject}’ has no  member named ‘dimensions’                                                          
__pyx_v_ndets = (__pyx_v_dets->dimensions[0]);                                        
                                                    ^                                              
error: command 'gcc' failed with exit status 1                                   
make: *** [all] Error 1`

**my envs:
conda python=3.6.7
pytorch1.0.1
cuda9.0.176
cudnn7.2.1
gcc5.3.0**

**I'm searching for solve this compile problem and hoping some replys QAQ**

**Comment by hellock** [comment]
The nms compiling should have been fixed.

**Comment by Smoothing97** [comment]
yeap!I have solve this problem by compling the source code in another computer and copy the compling result to my GPU,it works!So make sure a clear compling env is important.: )
