### ISSUE TITLE
Average Recall or precision at a specific IoU threshold

### ISSUE THREAD

**Issue by bjanfeshan** [open-mmlab/mmdetection#4493]
how I can get Average Recall (or AP) at a specific IoU threshold? or class_wise AR at a specific IoU threshold.

**Comment by superuser992002** [comment]
Your customdataset class has evaluate method, please change iou_thr argument in that method to get your result.

**Comment by bjanfeshan** [comment]
@superuser992002 I am using coco format for my annotation. is that still possible? it seems for bbox option the threshold for IoU is a list.

**Comment by superuser992002** [comment]
I have tested with COCO format and it works as usual.

**Comment by SuyashManiyar** [comment]
@huyphan168 I tried your solution but the output still shows 0.5 to 0.95 thresh which is default, is there any other solution?

**Comment by hsp2454** [comment]
Did you solve this problem?
