### ISSUE TITLE
Support backbone RepVGG

### ISSUE THREAD

**Issue by TuanTNG** [open-mmlab/mmdetection#4496]
**Motivation**

There is a recent paper [RepVGG](https://arxiv.org/pdf/2101.03697.pdf) about backbone, which is very helpful for both training and testing. 

**Related resources**
There is an official code release [here](https://github.com/DingXiaoH/RepVGG), which would be very helpful.

Are you have any plan for reimplement this backbone? If not, I am willing to do it.

**Comment by ZwwWayne** [comment]
Hi @TuanTNG ,
Thanks for your kind suggestion. We do not have any plan to reimplement it in the near future. So your PR is welcomed.

**Comment by ZwwWayne** [comment]
Since mmclassification already support it, you can use it by modifying the config as described in https://mmdetection.readthedocs.io/en/latest/tutorials/how_to.html#use-backbone-network-through-mmclassification
