### ISSUE TITLE
How to train/eval simultaneously on multiple COCO-style datasets?

### ISSUE THREAD

**Issue by wangg12** [open-mmlab/mmdetection#45]
For example, I have multiple annotation files (in json format) for different datasets. I want to train/eval simultaneously on those datasets by providing the paths of the annotation files like what Detectron.pytorch does. 
What is the easy way to achieve this with mmdetection? 
My idea is to make use of `torch.utils.data.ConcatDataset` and modify the `ann_file` to support multiple ann_files in  config.

**Comment by hongdayu** [comment]
For example, I have multiple annotation files (in json format) for different datasets. I want to train/eval simultaneously on those datasets by providing the paths of the annotation files like what Detectron.pytorch does.
What is the easy way to achieve this with mmdetection?
My idea is to make use of torch.utils.data.ConcatDataset and modify the ann_file to support multiple ann_files in config.

**Comment by wangg12** [comment]
I am using `torch.utils.data.dataset.ConcatDataset` to concat a dataset with multiple ann_files. 
```
def get_train_dataset(cfg):
    if isinstance(cfg.data.train['ann_file'], list) or isinstance(cfg.data.train['ann_file'], tuple):
        ann_files = cfg.data.train['ann_file']
        train_datasets = []
        for ann_file in ann_files:
            data_info = copy.deepcopy(cfg.data.train)
            data_info['ann_file'] = ann_file
            train_dset = obj_from_dict(data_info, datasets)
            train_datasets.append(train_dset)
        if len(train_datasets) > 1:
            train_dataset = ConcatDataset(train_datasets)
        else:
            train_dataset = train_datasets[0]
    else:
        train_dataset = obj_from_dict(cfg.data.train, datasets)
    return train_dataset
```
I got this error when I run the training script:
```
Traceback (most recent call last):
  File "tools/train.py", line 104, in <module>
    main()
  File "tools/train.py", line 100, in main
    logger=logger)
  File "/data/wanggu/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/data/wanggu/mmdetection/mmdet/apis/train.py", line 103, in _non_dist_train
    dist=False)
  File "/data/wanggu/mmdetection/mmdet/datasets/loader/build_loader.py", line 31, in build_dataloader
    sampler = GroupSampler(dataset, imgs_per_gpu)
  File "/data/wanggu/mmdetection/mmdet/datasets/loader/sampler.py", line 14, in __init__
    assert hasattr(dataset, 'flag')
AssertionError
```
@hellock Do you have any idea about this?

**Comment by hellock** [comment]
We use a field `flag` to identify different groups for the GroupSampler, but the `ConcatDataset ` only implements `__len__` and `__getitem__`. You may need to inherit the official `ConcatDataset` and add the `flag` filed, which simply concatenates flags of all datasets.

**Comment by wangg12** [comment]
@hellock Yeah. I've noticed that. Now it works.
