### ISSUE TITLE
Why the width and height of coco bbox need minus 1

### ISSUE THREAD

**Issue by stevehjc** [open-mmlab/mmdetection#450]
https://github.com/open-mmlab/mmdetection/blob/edb03937964b583a59dd1bddf76eaba82df9e8c0/mmdet/datasets/coco.py#L84
I can't understand Why the width and height of coco bbox need minus 1.
When I use smaller picture (512x640) trainning, the predicted bboxes have big error.

**Comment by abing222** [comment]
Do you understand this problem? I haven't understood it yet. I hope you can tell me
