### ISSUE TITLE
How to change the train_pipeline after train_iter?

### ISSUE THREAD

**Issue by hwx10** [open-mmlab/mmdetection#4500]
In order to augment my data with different operation，I wanna  change train_pipeline(dataset.pipeline) after train_iter. 
Now I design a method to sample operation, all of the operations are callable. And then I wanna add the sampled operation into train_pipeline. But it seems just support changing dataset's pipeline after epoch?

**Comment by xvjiarui** [comment]
Hi @hwx10 
We don't support changing pipeline during training yet. You may directly implement it as an augmentation.
