### ISSUE TITLE
Why the ResNeSt config file only have 'syncBN' version, such as 'cascade_rcnn_s50_fpn_syncbn-backbone+head_mstrain-range_1x_coco.py'

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#4503]
I try to modify the config to BN and use only 1 card to train, and the result is not good.

**Comment by waddington-ou-phd-1** [comment]
I don't know if it has a negative effect but you can use `./tools/distr_train.py <config/file.py> 1` and train on only 1 card this way.

**Comment by xvjiarui** [comment]
Hi @clw5180 
The official ResNeSt implementation used SyncBN. We followed the same setting.
