### ISSUE TITLE
My custom model did not update weight and bias

### ISSUE THREAD

**Issue by NicholasIrving** [open-mmlab/mmdetection#4506]
I write a model and add it before neck and roi in Faster-RCNN, but after training, the weight and bias did not update.

**Comment by NicholasIrving** [comment]
My model has written in neck as a plugin, if i write it directly in neck network, the weight and bias can be updated. The problem is the modular

**Comment by NicholasIrving** [comment]
#4523

**Comment by xvjiarui** [comment]
Hi @NicholasIrving 
Could you please provide more info? E.g. what did you add?
