### ISSUE TITLE
How to implement EMA in model

### ISSUE THREAD

**Issue by dqawami** [open-mmlab/mmdetection#4509]
Hi, 

I'm trying to implement EMA into one of my model configs, but I'm not entirely sure how to do so. I saw that [mmcv has an EMA hook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/ema.py), but I'm not sure where the hook should be used in an mmdetection config file, or if the hook is supported in mmdetection. Any suggestions would be appreciated!

**Comment by jshilong** [comment]
You can refer to our documentation, here [Modify the config](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_runtime.html#modify-the-config)
