### ISSUE TITLE
Implementation detail about detectoRS

### ISSUE THREAD

**Issue by dadada101** [open-mmlab/mmdetection#4519]
hi,
   in the implementation of detectors_resnet.py, https://github.com/open-mmlab/mmdetection/blob/3a9f5eff39735871c55643927f5506ab5af2127a/mmdet/models/backbones/detectors_resnet.py#L300,the rfp feature seems not to be added to the first stage of the resnet, can explain the reason? and the paper seems not to mention it ?@joe-siyuan-qiao

**Comment by ZwwWayne** [comment]
We follow the official implementation from [here](https://github.com/joe-siyuan-qiao/DetectoRS).
