### ISSUE TITLE
 'ConfigDict' object has no attribute 'test_cfg'

### ISSUE THREAD

**Issue by sungatetop** [open-mmlab/mmdetection#4521]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. I just run the demo https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#inference-with-existing-models

**Comment by ZwwWayne** [comment]
This is because your config is old. After the recent PR https://github.com/open-mmlab/mmdetection/pull/4347, train_cfg/test_cfg becomes an attribute of model, please see the [migration doc](https://mmdetection.readthedocs.io/en/latest/tutorials/config.html#deprecated-train-cfg-test-cfg).
