### ISSUE TITLE
File not found error in demo

### ISSUE THREAD

**Issue by InukKang** [open-mmlab/mmdetection#4524]
I followed your instruction in the demo on
<img width="615" alt="캡처" src="https://user-images.githubusercontent.com/69806620/105640570-72199b80-5e44-11eb-85bf-1354ed14711f.PNG">
 google colab. However, got some error that I don't know.

**Comment by InukKang** [comment]
similar case in cfg
<img width="659" alt="캡처" src="https://user-images.githubusercontent.com/69806620/105640773-667aa480-5e45-11eb-8edb-6dec9dceb2a3.PNG">

**Comment by jshilong** [comment]
@ZwwWayne

**Comment by ZwwWayne** [comment]
This is because you are not in the directory of mmdetection. You should get in the directory of mmdetection first.
