### ISSUE TITLE
Questions about TridentNet

### ISSUE THREAD

**Issue by HAOCHENYE** [open-mmlab/mmdetection#4527]
In section 4.2 of the paper:
**Similar to SNIP [38], we define a valid range [li; ui] for each branch i. During training, we only select the proposals and ground truth boxes whose scales fall in the corresponding valid range of each branch.**
However, I have not found any relevant implemention in TridentRoIHead about that TridentNet's branches can seperately regress different scale bboxes. Have I missed any details?

**Comment by jshilong** [comment]
Actuall, we implement TridentNet-Fast as it in [Detectron2](https://github.com/facebookresearch/detectron2/tree/master/projects/TridentNet),
@Chrisfsj2051, please add a comment to readme of `TridentNet`.

**Comment by Chrisfsj2051** [comment]
Hi @jshilong, please refer to https://github.com/open-mmlab/mmdetection/pull/4533
