### ISSUE TITLE
I want to predict the only car and train using MMdetection What filter do I have to filter for this?What need to change in colab file ?

### ISSUE THREAD

**Issue by SR-fr** [open-mmlab/mmdetection#4529]

**Comment by jshilong** [comment]
You can find a pickle file named  `out.pkl` in you workdir which contains results of all categories after you test your model,  you can pick up results of the corresponding category from this pkl.

**Comment by SR-fr** [comment]
there is no out.pkl file in the directory

**Comment by SR-fr** [comment]
How to add rules to predict only two objects (car and train) classes Out of 80 objects

**Comment by SR-fr** [comment]
> You can find a pickle file named `out.pkl` in you workdir which contains results of all categories after you test your model, you can pick up results of the corresponding category from this pkl.

there is no out.pkl file in the directory

**Comment by SR-fr** [comment]
> You can find a pickle file named `out.pkl` in you workdir which contains results of all categories after you test your model, you can pick up results of the corresponding category from this pkl.

there is no out.pkl file in the directory.How to add rules to predict only two objects (car and train) classes Out of 80 objects

**Comment by jshilong** [comment]
Please inference your model first with this command `python -u tools/test.py ${CONFIG} ${CHECKPOINT} --eval bbox    --out out.pkl`, then you can find `out.pkl`, We have not yet supported only inference partial categories, you need to filter out corresponding results by yourself.
