### ISSUE TITLE
a general question on image scaling

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#4532]
Hi, there, 

I have a question about multi-scale training. The image size in my training set varies from 500x500 to 4000x6000. I'm wondering if I can randomly sample small patches from each image and then scale each patch further by 2X. For example, if the original image size is 4000x6000. I'd like to sample it into multiple 200x300 patches, and then rescale each patch further to 400x600. Is it possible to do so in the current mmDetection pipeline? If so, could you give me some configuration samples?

Thank you!

**Comment by hhaAndroid** [comment]
@shanggdlk  Sorry, it's not supported for now, but you can customize the pipeline for your datasets, you can refer to [data_pipeline](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/data_pipeline.md)
