### ISSUE TITLE
VarifocalNet dist_train keep waiting

### ISSUE THREAD

**Issue by whoNamedCody** [open-mmlab/mmdetection#4535]
My env：
cuda10.2
torch==1.6.0
mmdetection==2.8.0
mmcv==1.2.4
After some iters the GPU-Util 100% but the process is always waiting
Any advice? Thanks

**Comment by v-qjqs** [comment]
Hi @whoNamedCody, would using smaller batch_size helps? I guess it might be caused by out of CUDA memory?

**Comment by whoNamedCody** [comment]
I'm sure Memory-Usage not full, and training on single gpu is normal

**Comment by ZwwWayne** [comment]
The stuck sometimes is caused by the different computation graphs in different GPUS and this usually happens when you are training empty GT images. You may check that first.

**Comment by xnnxax** [comment]
> The stuck sometimes is caused by the different computation graphs in different GPUS and this usually happens when you are training empty GT images. You may check that first.

Hi, @ZwwWayne, I meet the same problem. 

when I set filter_empty_gt=False (because many empty GT images in my custom dataset), dist_train for FCOS also keep waiting, so is there any way and plan to solve it?

Thanks.

**Comment by chenzyhust** [comment]
> The stuck sometimes is caused by the different computation graphs in different GPUS and this usually happens when you are training empty GT images. You may check that first.

I meet the same problem in training resnest.Could you help us solve the problem

**Comment by chenzyhust** [comment]
@ZwwWayne

**Comment by ZwwWayne** [comment]
The implementation might not be so robust, we will check it out.
