### ISSUE TITLE
There is an error occurring when calculating the flops of HRNET.

### ISSUE THREAD

**Issue by CanQixiaoLan** [open-mmlab/mmdetection#4536]
RuntimeError: The size of tensor a (150) must match the size of tensor b (152) at non-singleton dimension 3

**Comment by Dantju** [comment]
@v-qjqs ,I also meet the same problem when test hrnet_w32_crowdpose_256x192,the size of tensor a(47) must match the size of tensor b(48) at non-singleton dimension

**Comment by ZwwWayne** [comment]
This is because the input shape cannot be divided by 32, see the fix in #6076
