### ISSUE TITLE
imagewise eval?

### ISSUE THREAD

**Issue by waddington-ou-phd-1** [open-mmlab/mmdetection#4541]
We can do classwise evaluation for bbox task which gives us the mAP for each class. Is it also possible to produce the same results for each image in the test set?

Ideally I'd like mAP scores for each image, and if this is also classwise that would be even better.

If this isn't already implemented could you point me to a good starting point to modify the code to do it?

Another question: where is the documentation for all of the properties that one can use after the `--eval-options` such as `"classwise=True"`?

Thanks

**Comment by hhaAndroid** [comment]
1. Yes, you can `--eval-options classwise=True`  to  classwise evaluation 
2. you can refer to [mAp for each image](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/analyze_results.py)

**Comment by waddington-ou-phd-1** [comment]
Thanks. Have you got an example somwhere of how to use that file/function? So I run the normal test script on my model/config combo with `--out results.pkl` then use `python tools/analysis_tools/analyze_results.py path/to/config.py path/to/results.pkl path/to/save/images bbox`. Is this a correct/valid usage of that script?

**Comment by hhaAndroid** [comment]
> Thanks. Have you got an example somwhere of how to use that file/function? So I run the normal test script on my model/config combo with `--out results.pkl` then use `python tools/analysis_tools/analyze_results.py path/to/config.py path/to/results.pkl path/to/save/images bbox`. Is this a correct/valid usage of that script?

this usage is correct 

`python tools/analysis_tools/analyze_results.py path/to/config.py path/to/results.pkl path/to/save/images`

**Comment by waddington-ou-phd-1** [comment]
Hi, please reopen.

I have just tried this script by running `python tools/analysis_tools/analyze_results.py /results/resnest-cascade-rcnn-s101-CCT-SGDLR01M0-BS8-e30/resnest-cascade-rcnn-s101-CCT-SGDLR01M0-BS8-e30.py /results/results.pkl /results/save-out` which has the config file and the pkl file.

Inside the `save-out` directory I have two directories: "bad" and "good", each with 22 images in showing the predicted and ground truth boxes. 

1) why are there 22 images when the validation set contained 25k images? When the script was running it showed that it was processing all 25k images.

2) I would like to produce a text file (csv, json, I don't mind) listing the predictions for each image, and mAP for each image. This is what I wanted with my initial question, is there a builtin way to generate this?

Thanks
