### ISSUE TITLE
how to add background bbox labels to annotation json?

### ISSUE THREAD

**Issue by lzcomeon** [open-mmlab/mmdetection#4543]
I'm working on detecting small objects with cascade rcnn. There are many False Positive results when testing on the images. So the recall is ok, but precision is bad relatively. I'd like to add some False Positive bboxes to annotation jsons, cause I want to tell the model these areas are background.

Here is the question, in mmdet 2.0, the last class num refers to the background. If I have 2 classes to be detected, looks like this:
`objA: 1
objB: 2`

Can I add the False Positive bbox in jsons:
`{bbox:[x1, y1, x2,y2]   category_id:3}`
and leave the num_classes=2 in config files.

And in the RPN network, id=0 refers to the background, will the code dealing with these False Positive bboxes as foreground or background? Thanks.

**Comment by lzcomeon** [comment]
any help is welcome, thank you~

**Comment by xvjiarui** [comment]
Hi @lzcomeon 
Why add false positive boxes in the annotation? I don't think it would help. You may add more hard images in the dataset. 
Btw, the annotation should only contain ground truth boxes.
