### ISSUE TITLE
load_annotations() in mmdet.datasets.CustomDataset returning empty list

### ISSUE THREAD

**Issue by madiltalay** [open-mmlab/mmdetection#4544]
I build the dataset using:
`dataset = [build_dataset(cfg.data.train)]`

Then when I run print:
`print(dataset[0].data_infos)`

I get an empty list:

> []

The function called for data_infos is:
`self.data_infos = self.load_annotations(ann_file)`

I check the function, it is:
`def load_annotations(self, ann_file):`
`        return mmcv.load(ann_file)`

When I copy the return part of this function to directly call mmcv.load like:
`self.data_infos = mmcv.load((ann_file)`

I get an error.

Moving to the jupyter notebook where I have built the dataset object by:
`dataset = [build_dataset(cfg.data.train)]`

When I run this:
`data_infos = mmcv.load(dataset[0].ann_file)`
`len(data_infos)`

I get a list with three elements, namely the annotations, categories and images of the COCO type dataset:

> 3

Please guide why the function is not returning the loaded annotations, or maybe it is not even running, and how to resolve it.

**Comment by ZwwWayne** [comment]
If you are using COCO format, please use `CocoDataset` rather than `CustomDataset`. See [docs](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html#tutorial-2-customize-datasets).

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
