### ISSUE TITLE
How can mmdetectionmodel predict the selected object outoff 80 objects? any script ?any example?

### ISSUE THREAD

**Issue by SR-fr** [open-mmlab/mmdetection#4547]

**Comment by yhcao6** [comment]
Do you mean you want predictions of some specific categories?
https://github.com/open-mmlab/mmdetection/blob/f07de13b82b746dde558202f720ec2225f276d73/mmdet/apis/test.py#L27
The predicted results of the model is a list and the length equals the number of categories, you can select the result of your favorite categories here.
