### ISSUE TITLE
pytorch2onnx.py based singgle input picture export faster_rcnn_r50_fpn_1x_coco_x.pth to onnx success, but it‘s not infer on coco val dataset

### ISSUE THREAD

**Issue by pengyeqing** [open-mmlab/mmdetection#4548]
**For off-line infer of faster_rcnn_r50_fpn_1x_coco, I use pytorch2onnx.py to export onnx based singgle input picture，but it‘s failure for onnx infer other picture.**

for example, run comand as follows:
**python3.7 tools/deployment/pytorch2onnx.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ./faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --output-file faster_rcnn_r50_fpn_1x_coco.onnx --input-img demo/demo.jpg --test-img tests/data/color.jpg --shape 800 1216  --verify --show**
it will generate err as follow:
**Non-zero status code returned while running Reshape node. Name:'Reshape_1103'
The input tensor cannot be reshaped to the requested shape. Input shape:{20,2}, requested shape:{641,2}**

**through vimdiff compare difference of export onnx generated based --input-img demo/demo.jpg and --input-img tests/data/color.jpg, I find that modify two reshape operator to (-1, 2) of onnx, modified onnx can infer other pictures.**

but other err occur on 000000308391.jpg 000000560371.jpg 000000374727.jpg of  coco test dataset，then I export onnx based these pictures, err mesage:
**File "/home/pengyq/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 65, in multiclass_nms
    raise RuntimeError('[ONNX Error] Can not record NMS '
RuntimeError: [ONNX Error] Can not record NMS as it has not been executed this time**
relate code as follow:
valid_mask = scores > score_thr
inds = valid_mask.nonzero(as_tuple=False).squeeze(1)
if inds.numel() == 0:
    if torch.onnx.is_in_onnx_export():
        raise RuntimeError(

**Comment by RunningLeon** [comment]
@pengyeqing 
Hi, 
1. faster_rcnn should be exported to ONNX with torch==1.6.0. Verification may fail due to the implementation difference between ONNX Runtime and PyTorch.
2. `RuntimeError('[ONNX Error] Can not record NMS` means you have to input an image with objects, otherwise `nms` cannot be exported to ONNX successfully.

**Comment by pengyeqing** [comment]
thanks, but we don't restrict user input an image with objects.

**Comment by RunningLeon** [comment]
Then you may have to set `score_thr` very small to make sure the input of NMS is not an empty tensor.

**Comment by pengyeqing** [comment]
e...

**Comment by RunningLeon** [comment]
@pengyeqing When export a model from PyTorch to ONNX, we have to make sure NMS ops are included in the ONNX file. Then, when doing inference with ONNX file and ONNXRuntime, there's no restriction with regard to input images.
