### ISSUE TITLE
Strange bug when training Sparse RCNN (every config)

### ISSUE THREAD

**Issue by superuser992002** [open-mmlab/mmdetection#4549]
I have tested my dataset with another detectors and it works well however when I switched to Sparse RCNN,
I have encountered this error, it seems that there is a nan value in some matrices.
![image](https://user-images.githubusercontent.com/51882888/106349162-560f7180-62fe-11eb-99f1-9861ee343877.png)

**Comment by jshilong** [comment]
The training of Sparse-RCNN is unstable in the early stage. If it is your own dataset instead of coco, it is recommended to modify ` load_from` to load the weight trained on coco(we provide the download link), or change `grad
clip` to a smaller value.

**Comment by ZwwWayne** [comment]
This sometimes because there are some Nan or INF values in the cost. You may check that.
