### ISSUE TITLE
modification to mmdet

### ISSUE THREAD

**Issue by hero-y** [open-mmlab/mmdetection#455]
I add new files into mmdet.models.detectors,but this shows the new class is not in the detector registry. so i use pip uninstall mmdet, and then python3 setup.py develop. But this can not also work. Can you help me?

**Comment by liveway6** [comment]
Hi, I add new files into mmdet.models.detectors and I also add this detector in the mmdet/models/__init__.py. but I meet the same problem, can you help me?

**Comment by hellock** [comment]
@liveway6 Please read the [installation guide](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md).

**Comment by liveway6** [comment]
> @liveway6 Please read the [installation guide](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md).

Thank you for your reply, I know how to do it now!
