### ISSUE TITLE
EfficientDet Model Help

### ISSUE THREAD

**Issue by dqawami** [open-mmlab/mmdetection#4550]
Hi, 

I'm currently developing a version of [EfficientDet-D0](https://github.com/dqawami/mmdetection/blob/feature/ik/efficientdet/configs/efficientdet/retinanet_effd0_bifpn_1x_coco.py) with an added [BiFPN neck](https://github.com/dqawami/mmdetection/blob/feature/ik/efficientdet/mmdet/models/necks/bifpn.py). Current AP[50:95] for this model is 31.5%, which is lower from the [paper's reported value of 34.6%](https://arxiv.org/pdf/1911.09070.pdf). 

Are there any further improvements that can be made to this model, specifically when it comes to finetuning the config? Most of the parameters used are based off of the [EfficientNet PR](https://github.com/open-mmlab/mmdetection/pull/3061), so should any of these be changed that could better fit EfficientDet? Are there any tools that can be used for finetuning in mmdetection, or is it mostly guess and check? Any and all feedback would be greatly appreciated.

**Comment by jshilong** [comment]
It is very difficult to reproduce the performance of `EfficientDet`. There are many important details or training tricks. The generalization ability of the model in other datasets is not very good (purely personal experience). I do not recommend trying this series of models.
