### ISSUE TITLE
how can updated new_beta transfer to SmoothL1loss in dynamic_rcnn?

### ISSUE THREAD

**Issue by ywx-hub** [open-mmlab/mmdetection#4551]
hi, thanks for mmdetection.
i am reading dynamic_roi_head.py recently and have a question about the code:

if len(self.iou_history) % update_iter_interval == 0:
new_iou_thr, new_beta = self.update_hyperparameters()

After updated beta,how can new_beta transfer to SmoothL1loss？i can't find which code call this new_beta.
Thank you very much!

**Comment by torchmyheart** [comment]
@ywx-hub Hello, I have the same problem, do you understand how the new beta is updated?
