### ISSUE TITLE
Any plan to add DSSD detection model please?

### ISSUE THREAD

**Issue by leewi9** [open-mmlab/mmdetection#4556]
https://arxiv.org/abs/1701.06659

Fu C Y, Liu W, Ranga A, et al. Dssd: Deconvolutional single shot detector[J]. arXiv preprint arXiv:1701.06659, 2017.

**Comment by jshilong** [comment]
We have no plans for this model, and it seems that the performance of this model has no obvious advantages at the moment. You can find many more powerful models in our model zoo.
