### ISSUE TITLE
the error of TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not list

### ISSUE THREAD

**Issue by destiny311** [open-mmlab/mmdetection#4561]
when i add amodule in the fpn，there is a problem."TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not list",do you have the error?can you tell me how to solve it ? thank you !

**Comment by jshilong** [comment]
Please use the template of issues and describe detailed changes to facilitate us to reproduce your problem.
