### ISSUE TITLE
transfer learning the backbone

### ISSUE THREAD

**Issue by minooei** [open-mmlab/mmdetection#4564]
Hi,
I have trained a model with mmdet and now I want to use its backbone for transfer learning on a different dataset. so I tried to set the pretrained attribute pointing to my last checkpoint ie:
``` model = dict(
    type='FasterRCNN',
    pretrained= '../../epoch_12.pth',
    backbone=dict(
        type='ResNeSt', ...
```
which results in unexpected key in source state_dict error because in saved model there is a prefix in names ie: ```backbone.stem.0.weight``` and the model expect ```stem.0.weight```.
so I wrote a script to rename the keys in the saved model:
```
from collections import OrderedDict
import torch

source='epoch_12.pth'
model = torch.load(source)
state_dict = model.pop('state_dict')
new_state_dict = OrderedDict()

for key, value in state_dict.items():
    if 'backbone' in key:
        new_key = key.replace('backbone.','')
        new_state_dict[new_key] = value

model['state_dict'] = new_state_dict
torch.save(model, 'pre-trained.pth')
```
now it's working fine but I'm not sure if this is the best way.
so I opened this issue as if might be helpful.

**Comment by hhaAndroid** [comment]
Hi @minooei  You should use the `load_from` parameter to load the weight, then the unexpected key error will not appear.
