### ISSUE TITLE
Resolve conflicts between pycocotools and mmpycocotools

### ISSUE THREAD

**Issue by ppwwyyxx** [open-mmlab/mmdetection#4565]
**Describe the feature**

`mmpycocotools` is installed under the package name "pycocotools" - causing a conflict with the official pycocotools. This causes the following potential issues:
1. Users that have installed official pycocotools may fail to use mmdet out of the box. There have been a number of issue reports about this
2. Users cannot use mmdet together with other libraries (e.g. detectron2) that depends on official pycocotools

I ran a structured diff using [psydiff](https://github.com/yinwang0/psydiff) of the two versions. Results are at [here](https://gistcdn.githack.com/ppwwyyxx/82270a1c6ff7024d2fb4ceb3964494d5/raw/9decf2ac4a9def0b66186ac78f2e90a1856f1007/coco-coco.html) and [here](https://gistcdn.githack.com/ppwwyyxx/82270a1c6ff7024d2fb4ceb3964494d5/raw/9decf2ac4a9def0b66186ac78f2e90a1856f1007/cocoeval-cocoeval.html).  It turns out that the only changes in `mmpycocotools` are additions of a few aliases.

Solution 1: Let `mmpycocotools` install the package with the name `mmpycocotools` to avoid conflicts
Solution 2: In mmdet, implement a subclass of `COCO` and `COCOeval`  with new aliases, so there is no need to fork the entire pycocotools

**Comment by ZwwWayne** [comment]
Hi @ppwwyyxx ,

Thanks for the suggestion.

We decide to maintain `mmpycocotools` when `pycocotools` was not officially maintained last year. Since the official team maintains `pycocotools` now, we consider implementing new `COCO` and `COCOEval` that inherits from `COCO` and `COCOEval` implemented in `pycocotools`. We will also deal with the dependency on LVIS at the same time.

**Comment by igonro** [comment]
Hi @ZwwWayne, you mentioned that the official team is maintaining now `pycocotools`, can I ask where are they maintaining the repository? The `cocodataset/cocoapi` repo last commit is from February 2020. Thanks!

**Comment by ZwwWayne** [comment]
> Hi @ZwwWayne, you mentioned that the official team is maintaining now `pycocotools`, can I ask where are they maintaining the repository? The `cocodataset/cocoapi` repo last commit is from February 2020. Thanks!

https://pypi.org/project/pycocotools/

**Comment by hiyyg** [comment]
@ZwwWayne @ppwwyyxx Does `pycocotools` have opensource code, or it is just maintained inside facebook?
