### ISSUE TITLE
How to add an attribute to config?

### ISSUE THREAD

**Issue by UT-Mao** [open-mmlab/mmdetection#4566]
For example, I am using a config file of faster R-CNN and I want to add another `bbox_assigner` with different IoU threshold for a special task (means I need 2 assigner, maintain the old one and add a new one). 
I tried to add 
`train_cfg = dict( ...., NEW_assigner=dict( 
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.2,
            min_pos_iou=0.2,
            match_low_quality=True,
            ignore_iof_thr=-1),....)`
Into config file, and use
 `self.bbox_assigner_NEW = build_assigner(self.train_cfg.NEW_assigner)`
In `standard_roi_dead.py`.
But I got a 
`AttributeError: 'ConfigDict' object has no attribute 'NEW_assigner'.`
I guess there is a default config which indicates the names of the attributions?
So my question is how to add an attribution? Here is an example, I am trying to understand how mmdetection works, and the answer of this question will be really helpful. Thank you a lot.

**Comment by hhaAndroid** [comment]
Hi, @UT-Mao  Can you provide a complete config？ and I suggest you use the Error report issue template.

**Comment by UT-Mao** [comment]
Sorry for bothering.. I think I add the content of config into wrong place..
I will close this, thank you for answering.
