### ISSUE TITLE
What are pre_pipeline for?

### ISSUE THREAD

**Issue by alexa19lab** [open-mmlab/mmdetection#4568]
I noticed that in the data pipeline you designed a dict of lists including 'img_fields', 'bbox3d_fields', etc. But from what I can see, you only use them to record the kinds of data in the input. When you load img, you add 'img' to the 'img_fields'. So why  didn't you just use keys in the input_dict to achieve this? Because the kinds of data are actually fixed, so the keys should also be fixed. We actually don't need extra lists to record them. Do I miss anything?

**Comment by hhaAndroid** [comment]
Hi @alexa19lab   'img_fields' is used to handle multiple images during image transform. you can refer to [changelog](https://github.com/open-mmlab/mmdetection/blob/master/docs/changelog.md#v210-862020)  or PR #2800

**Comment by alexa19lab** [comment]
Hi @hhaAndroid thanks so much for your quick response! May I ask will and when will there be an example of how we can use multiple views?

**Comment by alexa19lab** [comment]
> Hi @alexa19lab 'img_fields' is used to handle multiple images during image transform. you can refer to [changelog](https://github.com/open-mmlab/mmdetection/blob/master/docs/changelog.md#v210-862020) or PR #2800

Hi @hhaAndroid , thanks so much for your quick responds. Do you consider those multi-view imgs have their own bbox or mask labels? If yes, how are you gonna correspond them with their labels in 'bbox_fields' and 'mask_fields'? Thanks!

**Comment by hhaAndroid** [comment]
@alexa19lab  This means that multiple images corresponding to the one annotation.  We currently do not support multiple images corresponding to multiple labeled pipelines.
