### ISSUE TITLE
How to train the model with multi-nodes and multi gpus?

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#457]

**Comment by hellock** [comment]
If you are running on a cluster, you need to implement the env initialization like [`_init_dist_slurm`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/env.py#L37). If you just have multiple machines connected with the ethernet, you can refer to the official [launch utility](https://pytorch.org/docs/stable/distributed.html#launch-utility), which is used in our [script](https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh).

**Comment by alexwq100** [comment]
@hellock ，I am fresh to cluster, which one is better  between the official launch method and slurm?
