### ISSUE TITLE
How to use wandb on train_detector?

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#4575]
Is there a way to incorporate wandb on this?

**Comment by xvjiarui** [comment]
Hi @sarmientoj24 
You may add wandb hooks in `log_config` like this.
```
log_config = dict(
    interval=10,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(
            type='WandbLoggerHook',
            init_kwargs=dict(
                project='mmdetection',
                name='YOUR_EXP'
    ])

```

**Comment by sarmientoj24** [comment]
I will try to test that. @xvjiarui

**Comment by DekuLiuTesla** [comment]
> Hi @sarmientoj24 You may add wandb hooks in `log_config` like this.
> 
> ```
> log_config = dict(
>     interval=10,
>     hooks=[
>         dict(type='TextLoggerHook'),
>         dict(
>             type='WandbLoggerHook',
>             init_kwargs=dict(
>                 project='mmdetection',
>                 name='YOUR_EXP'
>     ])
> ```

Yeah it really works!
