### ISSUE TITLE
RPN model evaluation Bug

### ISSUE THREAD

**Issue by sleepfin** [open-mmlab/mmdetection#4580]
https://github.com/open-mmlab/mmdetection/blob/3620bb74893ef688b3243652042660e1b5866d5e/mmdet/datasets/custom.py#L318

I think here should be `iou_thrs` instead of `iou_thr`

**Comment by xvjiarui** [comment]
Hi @sleepfin 
Thanks for pointing out. Would you like to create a PR to fix it?
