### ISSUE TITLE
VOCDataset that has object but with no difficult attribute returns an Error

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#4585]
**Describe the bug**
When using a VOCDataset, those with annotations that do not have difficult attribute inside the object yields an error.

**Reproduction**

1. What command or script did you run?

```
python tools/train.py {config}
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? Edited configuration
3. What dataset did you use? Custom dataset

**Environment**
MMDet Colab Environment

**Error traceback**
If applicable, paste the error trackback here.

```
  File "/content/mmdetection/mmdet/datasets/custom.py", line 211, in prepare_train_img
    ann_info = self.get_ann_info(idx)
  File "/content/mmdetection/mmdet/datasets/xml_style.py", line 105, in get_ann_info
    difficult = int(obj.find('difficult').text)
AttributeError: 'NoneType' object has no attribute 'text
```

**Bug fix**
This yields the error.
mmdet/datasets/xml_style.py
```
            difficult = int(obj.find('difficult').text)
```

I was able to do a workaround by adding a try-catch 
```
try:
     difficult = int(obj.find('difficult').text) 
catch:
     difficult = 0

**Comment by ZwwWayne** [comment]
Fixed
