### ISSUE TITLE
Difference of semantic_seg and mask

### ISSUE THREAD

**Issue by dimimal** [open-mmlab/mmdetection#4587]
Hello, 

Silly question, what is the difference between the mask and the semantic segmentation map? 
When I try to train detectoRS it needs the segmentation masks a-priori. I thought that these can be retrieved from my coco dataset. Is my conception wrong?

Thanks

**Comment by yhcao6** [comment]
You can refer to this [answer](https://datascience.stackexchange.com/questions/52015/what-is-the-difference-between-semantic-segmentation-object-detection-and-insta)

**Comment by dimimal** [comment]
@yhcao6 Ok I understand that. But, the maskRCNN can be trained without the gt_semantig_seg keyword and computes the masks from the polys. 
Why the detectoRS is different in this regard? 
Both networks are designed for instance segmentation.

**Comment by yhcao6** [comment]
DetectoRS itself doesn't need semantic_seg, but HTC does. For the detail, you can refer to the paper of [HTC](https://arxiv.org/abs/1901.07518).

**Comment by dimimal** [comment]
Ok, Its because of the segmentation branch. Thank you!
