### ISSUE TITLE
Do you have plan to integrate the "Region Proposal by Guided Anchoring" into this framework?

### ISSUE THREAD

**Issue by alexwq100** [open-mmlab/mmdetection#459]
Do you have plan to integrate the "Region Proposal by Guided Anchoring" into this framework?

**Comment by jamesguoxin** [comment]
Same question here lol

**Comment by hellock** [comment]
We are preparing for it.

**Comment by alexwq100** [comment]
ho,fabulously , do you have the milestone?

**Comment by myownskyW7** [comment]
We are now working on it. The code of GA-RPN will probably be released next week.

**Comment by jamesguoxin** [comment]
Has GA-RPN already been integrated into mmdetection? :)

**Comment by myownskyW7** [comment]
The code of GA-RPN is now in pr https://github.com/open-mmlab/mmdetection/pull/594. The performance is ready and I will refactor the code in the following days.
