### ISSUE TITLE
weight_decay for BN

### ISSUE THREAD

**Issue by Soulempty** [open-mmlab/mmdetection#4591]
Hello，in faster rcnn model，I find the weight_decay in optimizer is operated on all the model parameters，it means the BN parameters are also be penalized,but it is generally known that BN parameters need not be  penalized.

**Comment by jshilong** [comment]
We try to follow the original implementation. Generally,  we do not perform this operation on faster-RCNN (considered as tricks).  
If you want to do this operation, you can refer to the `FCOS`'s configs.
