### ISSUE TITLE
 AttributeError: 'ConfigDict' object has no attribute 'train_cfg' during custom dataset training

### ISSUE THREAD

**Issue by surbhi1986** [open-mmlab/mmdetection#4603]
Hi i want to train mmdet on my custom dataset. so for the same i am trying this tutorial.(https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb) But getting the error
/content/mmdetection/mmdet/datasets/custom.py:155: UserWarning: CustomDataset does not support filtering empty gt images.
  'CustomDataset does not support filtering empty gt images.')

Please provide the solution.  Thanks
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-47-9db4fd99782d> in <module>()
      8 
      9 # Build the detector
---> 10 model = build_detector(cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
     11 # Add an attribute for visualization convenience
     12 model.CLASSES = datasets[0].CLASSES

1 frames

/usr/local/lib/python3.6/dist-packages/mmcv/utils/config.py in __getattr__(self, name)
     41         else:
     42             return value
---> 43         raise ex
     44 
     45 

AttributeError: 'ConfigDict' object has no attribute 'train_cfg'

**Comment by hhaAndroid** [comment]
Hi @surbhi1986, thank you for your feedback. This is because `train_cfg` has been moved to the `model`, we will fix this bug.  So far, you can replace

`
model = build_detector(
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
`

with

`
model = build_detector(
    cfg.model,
    train_cfg=cfg.get('train_cfg'),
    test_cfg=cfg.get('test_cfg'))
`

**Comment by surbhi1986** [comment]
Thanks, the above has been solved.
But facing a new issue:

/content/mmdetection/mmdet/datasets/custom.py:155: UserWarning: CustomDataset does not support filtering empty gt images.
  'CustomDataset does not support filtering empty gt images.')
2021-02-09 07:22:02,898 - mmdet - INFO - load model from: open-mmlab://detectron2/resnet50_caffe
2021-02-09 07:22:02,962 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-49-d7db62f8014b> in <module>()
     15 # Create work_dir
     16 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 17 train_detector(model, datasets, cfg, distributed=False, validate=True)

2 frames

/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py in register_lr_hook(self, lr_config)
    348             return
    349         elif isinstance(lr_config, dict):
--> 350             assert 'policy' in lr_config
    351             policy_type = lr_config.pop('policy')
    352             # If the type of policy is all in lower case, e.g., 'cyclic',

AssertionError:

**Comment by ZwwWayne** [comment]
This is because the original config is modified. You might need to rerun the cell that loads the config.

**Comment by surbhi1986** [comment]
Thanks,

**Comment by surbhi1986** [comment]
Now getting issue in saving the checkpoints in last epoch. Please resolve it. Thanks in advance


2021-02-10 10:33:09,276 - mmdet - INFO - Saving checkpoint at 12 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 12/12, 7.5 task/s, elapsed: 2s, ETA:     0s
---------------iou_thr: 0.5---------------
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-32-d7db62f8014b> in <module>()
     15 # Create work_dir
     16 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 17 train_detector(model, datasets, cfg, distributed=False, validate=True)

8 frames
/content/drive/My Drive/images_object/mmdetection/mmdet/core/evaluation/mean_ap.py in get_cls_results(det_results, annotations, class_id)
    258         if ann.get('labels_ignore', None) is not None:
    259             ignore_inds = ann['labels_ignore'] == class_id
--> 260             cls_gts_ignore.append(ann['bboxes_ignore'][ignore_inds, :])
    261         else:
    262             cls_gts_ignore.append(np.empty((0, 4), dtype=np.float32))

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 26

**Comment by ZwwWayne** [comment]
This might because the number of classes in your head does not match those in the dataset, you may check that.

**Comment by GotG** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb

i am running the tutorial and getting the following error:

```
2021-02-17 18:30:24,890 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias

checkpoints/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth is not a checkpoint file
```

**Comment by ZwwWayne** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb
> 
> i am running the tutorial and getting the following error:
> 
> ```
> 2021-02-17 18:30:24,890 - mmdet - WARNING - The model and loaded state dict do not match exactly
> 
> unexpected key in source state_dict: conv1.bias
> ```
> 
> Please advise. Thank you

This is not an error. It is normal when using the resnet pre-trained model as the conv1.bais has been absorbed in the conv1.weight.

**Comment by gledsonmelotti** [comment]
Hello everyone, how are you? I still have a question about the old error 'ConfigDict' object has no attribute 'train_cfg'. I modified my model = build_detector( cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg) to
model = build_detector( cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg')), but I got a new error:
AttributeError: 'ConfigDict' object has no attribute 'log_level'
Could anyone provide a solution please?
