### ISSUE TITLE
Question about BitmapMasks, are they always in absolute image coordinates?

### ISSUE THREAD

**Issue by Erotemic** [open-mmlab/mmdetection#4607]
It seems like its the case that `BitmapMasks` expects the segmentation masks to be specified in the image space? In other words, if I input a 224x224 image to the network, but my object is only 54x48 pixels, I have to allocate the entire 224x224 zeros tensor and then set each pixel to 1 where the object exists in the image?

This seems inefficient. 

Consider the case where I have a 224x224 image, and three objects, located at (in tl_x, tl_y, br_x, br_y coordinates):  

```
gt_bboxes = [
    [0, 0, 54, 48],
    [60, 20, 32, 32],
    [100, 200, 12, 16],
]
```

Instead of allocating `3 * 224 * 224 = 150528` cells, and painting in the segmentations in the absolute image space. I would have expected is that `BitmapMasks` could hold a list of variably sized arrays of size (48, 54), (32, 32), and (16, 12). (Note: `16 * 12 + 48 * 54  + 32 * 32 = 3808`, which is 39x smaller than the baseline). And also an offset indicating a translation factor for each mask. 

Is my interpretation correct? If so, I assume the `PolygonMasks` are designed to attempt to more efficiently handle these cases? Although in that case non-binary masks become an issue (see #4606).

**Comment by ZwwWayne** [comment]
Yes, your interpretation is correct. This might hurt some efficiency, however, this might be more simple and straightforward. You can use PolygonMasks for efficiency.
