### ISSUE TITLE
question on RandomCrop

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#4608]
Hi, there,

I have a question about RandomCrop. I saw on the implementation that by default the cropped area should contain at least one GT box (as shown below where allow_negative_crop=False). 

```
def __init__(self,
                 crop_size,
                 crop_type='absolute',
                 allow_negative_crop=False,
                 bbox_clip_border=True):
```

Now if my training set has certain numbers of negative images (with zero GT boxes), and I have set filter_empty_gt=False in the training pipeline, as shown below.

```
img_prefix='XXXXXX',
        filter_empty_gt=False,
```

My question is: how does RandomCrop perform in such a case? Does it simply ignore negative images or crop an area without GT? I trained in such settings and did not see any errors. However, I'm curious how the code works in such case?

I use randomcrop like this:

```
dict(
                type='Resize',
                img_scale=(1280, 720),
                ratio_range=(1.8, 2.2),
                keep_ratio=True),
            dict(type='RandomCrop', crop_size=(1000, 1000)),
            dict(type='RandomFlip', flip_ratio=0.5),
```

Thanks!

**Comment by jshilong** [comment]
The `RandomCrop`  would skip this image, return None, and process the next image.
