### ISSUE TITLE
bbox format and augmentation

### ISSUE THREAD

**Issue by ProBuro** [open-mmlab/mmdetection#4609]
Sorry for the newbie question. My question is: I'm trying to train different models and it seems like training is going well, but testing is failing - very low detection on the data packet.
I suspect I am misunderstanding what format the bbox is output in, my guess is that:
b [0] = x_min
b [1] = y_min
b [2] = x_max
b [3] = y_max
the training is carried out on its own dataset (custom)
Am I understanding correctly how bbox is output?
2 question:
can I use all kinds of pytorch augmentation or just those in the mmcv documentation?

**Comment by jshilong** [comment]
for q1 
yes
for q2
you can refer to [Datapipeline](https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html#) to design a new augmentation, and I believe you can insert a PyTorch augmentation to a pipeline with very little modification.

**Comment by ProBuro** [comment]
Thanks!
