### ISSUE TITLE
 IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 26

### ISSUE THREAD

**Issue by surbhi1986** [open-mmlab/mmdetection#4612]
Hi I am training a mmdet model on my custom data as according to this [link.](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb). But after training the checkpoints are not saving. I am using annotation data in Pascol .xml format.  Please resolve the issue . TIA. The error is given below: 

2021-02-10 10:33:07,284 - mmdet - INFO - Epoch [12][60/65]	lr: 2.500e-05, eta: 0:00:02, time: 0.414, data_time: 0.026, memory: 3024, loss_rpn_cls: 0.0000, loss_rpn_bbox: 0.0000, loss_cls: 0.0032, acc: 100.0000, loss_bbox: 0.0000, loss: 0.0032
2021-02-10 10:33:09,276 - mmdet - INFO - Saving checkpoint at 12 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 12/12, 7.5 task/s, elapsed: 2s, ETA:     0s
---------------iou_thr: 0.5---------------
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-32-d7db62f8014b> in <module>()
     15 # Create work_dir
     16 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 17 train_detector(model, datasets, cfg, distributed=False, validate=True)

8 frames
/content/drive/My Drive/images_object/mmdetection/mmdet/core/evaluation/mean_ap.py in get_cls_results(det_results, annotations, class_id)
    258         if ann.get('labels_ignore', None) is not None:
    259             ignore_inds = ann['labels_ignore'] == class_id
--> 260             cls_gts_ignore.append(ann['bboxes_ignore'][ignore_inds, :])
    261         else:
    262             cls_gts_ignore.append(np.empty((0, 4), dtype=np.float32))

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 26

**Comment by felipe-parodi** [comment]
Hello, how do you resolve this issue? Thanks!

**Comment by Chenli235** [comment]
I have a similar issue , how you solve it?
Thanks
