### ISSUE TITLE
Why different norm cfg in caffe style pretrained resnet50?

### ISSUE THREAD

**Issue by YongtaoGe** [open-mmlab/mmdetection#4613]
for example:

https://github.com/open-mmlab/mmdetection/blob/d40e19b09b19dd3dd55627ecf0f8d2f0796a1a03/configs/legacy_1.x/retinanet_r50_caffe_fpn_1x_coco_v1.py#L8

https://github.com/open-mmlab/mmdetection/blob/d40e19b09b19dd3dd55627ecf0f8d2f0796a1a03/configs/cascade_rcnn/cascade_rcnn_r50_caffe_fpn_1x_coco.py#L9

**Comment by xvjiarui** [comment]
Hi @YongtaoGe 

In caffe model, the std is absorbed by the backbone.

**Comment by YongtaoGe** [comment]
@xvjiarui The mean value [102.9801, 115.9465, 122.7717] and [103.530, 116.280, 123.675] is different while using the same ImageNet pre-trained model.

**Comment by xvjiarui** [comment]
Ah, I see. My bad. 
It is due to the minor difference in the pertained backbone. The legacy one is from detectron, the other one is from detectron2.

**Comment by YongtaoGe** [comment]
Got it! Thank you!
