### ISSUE TITLE
Question about tensor manipulation in ATSS assigner

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#4617]
I have a question related to tensor manipulation in ATSS assigner.  Lines 138 to 154 below are to limit the positive sample's center in gt.  At line 141 the ``ep_boxes_cx`` is in ``[num_gt, num_bboxes]`` format; however, at line 149, ``ep_boxes_cx`` is reshape to ``[-1, num_gt]``. Here ``num_gt`` is used at column index that confuses me. 

I expect a manipulation at line 149 as follows: ``l_ = ep_bboxes_cx[candidate_idxs].reshape(num_gt, -1).transpose(1, 0) - gt_bboxes[:, 0] ``

It may have a stricky reason for the original code, such as fast computation. If so, feel free to correct me.

https://github.com/open-mmlab/mmdetection/blob/46801227847e0212181af03b1cdcf99d0fba8f80/mmdet/core/bbox/assigners/atss_assigner.py#L138-L154

**Comment by jshilong** [comment]
This is not for fast computation, and I believe 
```l_ = ep_bboxes_cx[candidate_idxs].reshape(num_gt, -1).transpose(1, 0) - gt_bboxes[:, 0]```
 is wrong.

before line 145  `candidate_idxs = candidate_idxs.view(-1) ` the shape of `candidate_idxs`  is 45 * num_gt, so when do the `view` operation the last dimension must be `num_gt`, I think you may misunderstand the meaning of `candidate_idxs`.

**Comment by thangvubk** [comment]
@jshilong, The tricky part is: shape order depend on ``candidate_idxs`` not ``ep_bboxes_cx``. Thanks for correct me.
