### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin

### ISSUE THREAD

**Issue by surbhi1986** [open-mmlab/mmdetection#4622]
Hi Team, I have successfully trained my custom detector. But during testing using tools/test.py i am getting the following error
:

QObject::moveToThread: Current thread (0x3d9b720) is not the object's thread (0x5af24f0).
Cannot move to target thread (0x3d9b720)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/surbhi/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Aborted (core dumped)

**Comment by surbhi1986** [comment]
I have QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu on my local machine.

Is that compatible or should i change the version?

**Comment by surbhi1986** [comment]
resolved

**Comment by noobying** [comment]
resovled what？

**Comment by arthurJHM** [comment]
> resolved

how to resolve?

**Comment by YH721** [comment]
？
