### ISSUE TITLE
GFL head crashes if crop is empty

### ISSUE THREAD

**Issue by dave-andersen** [open-mmlab/mmdetection#4623]
When applying RandomCrop in the training pipeline, it's possible to generate crops that contain no detections. Together with a batch size of 1 (very large images), this means that occasionally the avg_factor in the GFL head will be zero. When this happens, the tensor gets converted to an integer Tensor, instead of a float, which causes a later crash from pytorch refusing to do integer division.

The fix is simple: Always force avg_factor to be a float by changing line 365 of mmdet/models/dense_heads/gfl_head.py:

```
avg_factor = reduce_mean(avg_factor.float()).item()
```

**Comment by ZwwWayne** [comment]
Hi @dave-andersen ,
Thanks for your kind suggestion. Would you like to create a PR to fix that?

**Comment by ZwwWayne** [comment]
I just created a PR #4631  for that as this is a simple and quick fix. Thanks again for your kind suggestion.
