### ISSUE TITLE
hourglass-RuntimeError: The size of tensor a (13) must match the size of tensor b (14) at non-singleton dimension 3

### ISSUE THREAD

**Issue by plantematthieu** [open-mmlab/mmdetection#4624]
Hi, 
I got the same issue than  [#3654](https://github.com/open-mmlab/mmdetection/issues/3654) when i use hourglass backbone for cornetnet and centripetalnet:

`RuntimeError: The size of tensor a (13) must match the size of tensor b (14) at non-singleton dimension 3`

I tried different input sizes without succes.

Thanks!

**Comment by ZwwWayne** [comment]
This might because the image is not correctly padded, e.g., padded to be divisible by 16 but the image is downsampled by stride 32 in the backbone. You may check that.

**Comment by plantematthieu** [comment]
I tried 1024x1024 and 512x512 images but it still doesn't work

**Comment by Dantju** [comment]
I alse meet the same issure at HRNet   the size of tensor a(47) must match the size of tensor b(48) at non-singleton dimension @ZwwWayne  use your model to test

**Comment by ZwwWayne** [comment]
Please use the `error template` to report the issue in detail. The current information does not provide much useful information to reproduce or debug the bug.
