### ISSUE TITLE
How to check the samples from the dataset created using build_dataset function in mmdet?

### ISSUE THREAD

**Issue by gaurav-singh1** [open-mmlab/mmdetection#4625]
I am trying to convert to build a dataset to pass into train_detector function like this:

## Build dataset
datasets = [build_dataset(cfg.data.train)]

train_detector(model, datasets, cfg, distributed=False)

But I keep getting this error :
ValueError: need at least one array to concatenate

I think this might be that the datasets is not able to return image array, probably due to some path mismatch. So I need to ensure that the dataset built is working fine.
MMDET version: 2.7.0

Entire Stacktracke:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-46-c9165eae30fe> in <module>
      1 # Create work_dir
      2 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
----> 3 train_detector(model, datasets, cfg, distributed=False)
      4 

/kaggle/working/mmdetection/mmdet/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
    148     elif cfg.load_from:
    149         runner.load_checkpoint(cfg.load_from)
--> 150     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)

/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
    123                     if mode == 'train' and self.epoch >= self._max_epochs:
    124                         break
--> 125                     epoch_runner(data_loaders[i], **kwargs)
    126 
    127         time.sleep(1)  # wait for some hooks like loggers to finish

/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
     45         self.call_hook('before_train_epoch')
     46         time.sleep(2)  # Prevent possible deadlock during epoch transition
---> 47         for i, data_batch in enumerate(self.data_loader):
     48             self._inner_iter = i
     49             self.call_hook('before_train_iter')

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __iter__(self)
    350             return self._iterator
    351         else:
--> 352             return self._get_iterator()
    353 
    354     @property

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _get_iterator(self)
    292             return _SingleProcessDataLoaderIter(self)
    293         else:
--> 294             return _MultiProcessingDataLoaderIter(self)
    295 
    296     @property

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __init__(self, loader)
    825         _utils.signal_handling._set_SIGCHLD_handler()
    826         self._worker_pids_set = True
--> 827         self._reset(loader, first_iter=True)
    828 
    829     def _reset(self, loader, first_iter=False):

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _reset(self, loader, first_iter)
    855         # prime the prefetch loop
    856         for _ in range(self._prefetch_factor * self._num_workers):
--> 857             self._try_put_index()
    858 
    859     def _try_get_data(self, timeout=_utils.MP_STATUS_CHECK_INTERVAL):

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _try_put_index(self)
   1089 
   1090         try:
-> 1091             index = self._next_index()
   1092         except StopIteration:
   1093             return

/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_index(self)
    425 
    426     def _next_index(self):
--> 427         return next(self._sampler_iter)  # may raise StopIteration
    428 
    429     def _next_data(self):

/opt/conda/lib/python3.7/site-packages/torch/utils/data/sampler.py in __iter__(self)
    225     def __iter__(self):
    226         batch = []
--> 227         for idx in self.sampler:
    228             batch.append(idx)
    229             if len(batch) == self.batch_size:

/kaggle/working/mmdetection/mmdet/datasets/samplers/group_sampler.py in __iter__(self)
     34                 [indice, np.random.choice(indice, num_extra)])
     35             indices.append(indice)
---> 36         indices = np.concatenate(indices)
     37         indices = [
     38             indices[i * self.samples_per_gpu:(i + 1) * self.samples_per_gpu]

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate

**Comment by jshilong** [comment]
`pdb.set_trace()` in corresponding  dataset's `get_item`

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.

**Comment by paihuai0** [comment]
> Feel free to reopen the issue if there is any question.

I write hook for show datasets I can share it with you if you need
