### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'resume_from' 

### ISSUE THREAD

**Issue by prateekg** [open-mmlab/mmdetection#4632]
While training the model for custom dataset (4 classes), how do I use the pretrained model. (number of classes differ)

**Comment by prateekg** [comment]
<img width="576" alt="Screenshot 2021-02-16 at 4 47 07 PM" src="https://user-images.githubusercontent.com/17765345/108055939-a6b0f980-7076-11eb-9182-301deddd7c9e.png">

Here, if I use resume_dir, the number of classes doesn't match and hence the state dict.

**Comment by prateekg** [comment]
Issue is resolved, please

**Comment by wwcc1107** [comment]
maybe you should add " resume_from = ' ', load_from =' ' " in default_runtime.py
