### ISSUE TITLE
tinaface

### ISSUE THREAD

**Issue by MHlighting** [open-mmlab/mmdetection#4633]
**Describe the feature**
Implement tinaface based on mmdetection.
**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. Tinaface references the code of mmdetection, which is easily implemented on mmdetection.
Ex2. There is a recent paper TinaFace: Strong but Simple Baseline for Face Detection,under the widerface evaluation criteria, tinaface is SOTA.

**Related resources**
This is the implementation details of tinaface, https://github.com/Media-Smart/vedadet/

**Additional context**
I am trying to implement modules such as data, model, hook, etc.

**Comment by ZwwWayne** [comment]
Hi @MHlighting ,
Thanks for your suggestion and interests. PRs are welcomed and @hhaAndroid will follow up when the PR is created.
