### ISSUE TITLE
Is there any example or method of applying fcos_head as RPN?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#4634]
Hi, dear authors
Is there any example or method of applying fcos_head as RPN? (FCOS' paper mentioned that FCOS can be used as RPN)
Which parameters of fcos_head need to be modified? Or how to apply fcos_head as RPN?
Any help is greatly appreciated！

**Comment by zhongqiu1245** [comment]
The method for judging positive and negative samples like the FCOS network is indeed simple and effective, so if it is to be used in rpn, it can form a two-stage anchor free network
I am looking for your reply
Any help is greatly appreciated!

**Comment by ZwwWayne** [comment]
Will be supported here https://github.com/open-mmlab/mmdetection/pull/5061
