### ISSUE TITLE
No loss shown in Tensorboard

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#4638]
I'm using mmdetection 2.7.0 with mmcv-full

I've set up 
```
log_config = dict(
    interval=25,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook'),

```
but get only 3 time series without any loss.
Where to dig in? Is it a bug or my issue?

![image](https://user-images.githubusercontent.com/3808833/108498846-807d9a80-72be-11eb-9628-2f7e36d124c5.png)

text logging works well
![image](https://user-images.githubusercontent.com/3808833/108499242-0f8ab280-72bf-11eb-82e7-5b61a74a353b.png)

**Comment by yhcao6** [comment]
It should be your issue. I test it and everything looks fine:
<img width="943" alt="Screen Shot 2021-02-20 at 4 06 57 PM" src="https://user-images.githubusercontent.com/22662425/108588734-aaee5700-7395-11eb-9ca7-dd59f44ce5e3.png">

**Comment by korabelnikov** [comment]
@yhcao6 thank you,

what version are you using? master?

**Comment by yhcao6** [comment]
latest mmcv and mmdetection

**Comment by korabelnikov** [comment]
I'll check up last version
