### ISSUE TITLE
During validation be able to save predicted bbox coordinates to txt/csv/json file?

### ISSUE THREAD

**Issue by waddington-ou-phd-1** [open-mmlab/mmdetection#4641]
Is it possible to save the prediction data during validation to some kind of file? In coco type dataset there are dts and gts object, dts is the prediction data in json format, is there an easy way to save this? Thanks

**Comment by ZwwWayne** [comment]
See 6th example [here](https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#examples).

**Comment by waddington-ou-phd-1** [comment]
That's exactly what I want, thank you.

There are some mistakes in the documentation: 

1. `-format-only` should be `--format-only` - note the double leading hyphens
2. `--options` should be `--eval-options` as per the deprecation warning

Thanks

**Comment by puhan123** [comment]
Does this surport the VOC type dataset?
I use the command line as below:
 python tools/test.py configs/pascal_voc/ssd300_voc0712.py experiments/ssd/epoch_24.pth --format-only --options "jsonfile_prefix=./results"

But I found it did't save the json file.
What should I do ? Thank you very much!

**Comment by tikitong** [comment]
Hi @puhan123, I noticed the same thing did you find out why? Thanks
