### ISSUE TITLE
Sampler for classes

### ISSUE THREAD

**Issue by ivanpanshin** [open-mmlab/mmdetection#4647]
Hey! 

I tried pretty much every sampler and checked the sample configs, but I still haven't found a solution to my issue. I want to use a sampler for classes. So that the amount of bboxes for each class that goes to training is more of less the same for each class. 

Is there any way I can do that? I initially thought that instance_balanced_pos_sampler will do the job, but that's not it.

**Comment by ZwwWayne** [comment]
You need to implement a new sampler to do that.
