### ISSUE TITLE
The relationship between keep_ratio and image_scale

### ISSUE THREAD

**Issue by ingbeeedd** [open-mmlab/mmdetection#4652]
Hello. I have a question about data config. I read the document below link, but I don't know if I understood it well. I'm curious about the relationship between keep_ratio and image_scale. In other words, if keep_ratio is true, the horizontal is fixed, so the vertical value can change to fluid? Or does it have a different meaning?

https://mmdetection.readthedocs.io/en/latest/tutorials/config.html#
![image](https://user-images.githubusercontent.com/57895472/108665041-5541b800-7517-11eb-867a-43df85fda401.png)

**Comment by ingbeeedd** [comment]
And if it's composed of two things, like img_scale= [2000, 800), (2000, 1200), how does it work?

**Comment by jshilong** [comment]
When you specify multi value of scale in `resize`, it would change to multiscale training mode.      
  ```
   dict(
                type='Resize',
                img_scale=[(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                           (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                           (736, 1333), (768, 1333), (800, 1333)],
                multiscale_mode='value',
                keep_ratio=True)
```
About the relationship between keep_ratio and image_scale, For example, the image scale (1333,800) indicate that after `resize `, the resize_w <= 1333 and resize_h <= 800, keep_ratio is a flag to control whether to keep the radio between the w and h in the resize process, if set it as Ture, the image would be rescaled as large as possible within the scale. When setting it as false, we simply resize it to (1333,800)

**Comment by ingbeeedd** [comment]
Thank you. if I have (2400,800) image, `keep_ratio=false` produces (1333,800). `keep_ratio=true` produces (1333, 480) it's approximately 3:1? Thank you.

You write the order of img_scale is (h, w), is this the right definition? Thank you

**Comment by jshilong** [comment]
Sorry, I check the code, What I say about the case of setting `keep_radio=True`  before is Wrong, I have corrected it. 
you can refer to these lines to get more details when setting `keep_radio=True`.
```
# scale  (1333,800) or (800., 1333) would get same results
        max_long_edge = max(scale)
        max_short_edge = min(scale)
        scale_factor = min(max_long_edge / max(h, w),
                           max_short_edge / min(h, w))
```

**Comment by ingbeeedd** [comment]
I'm sorry because I haven't solved my curiosity yet. e.g If the list length of img_scale is 8, will 8 resized images come out regardless of the value of keep_ratio?

**Comment by ingbeeedd** [comment]
@jshilong  Do you think answered?

**Comment by jshilong** [comment]
> I'm sorry because I haven't solved my curiosity yet. e.g If the list length of img_scale is 8, will 8 resized images come out regardless of the value of keep_ratio?

When `image_scale`  is a list, it is in multi-scale training mode, it would randomly resize to a scale in the list.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
