### ISSUE TITLE
Could you provide the results of each detector with multi-scale training?

### ISSUE THREAD

**Issue by tangjiuqi097** [open-mmlab/mmdetection#4653]
**Describe the feature**
Each model (at least the model using Resnet50 backbone) of detectors adds the results with multi-scale training.

**Motivation**
Many detectors trained with multi-scale training as the default setting, e.g. DETR, Deform-DETR, etc.
Of course, it is unfair to compare with the detector trained with a single scale.
So, could you provide the results of each detector with multi-scale training as a benchmark?

**Comment by jshilong** [comment]
Thanks for your suggestion
We may add these results shortly, but for some algorithms, a single scale of 1x is not enough to converge, especially the recent sparse method(sparse-rcnn, detr, deform-detr), in other words, The performance of these methods can be improved more significantly via 3x_multiscale training when compared to the traditional algorithm(faster retinanet), how to compare fairly is a difficult problem
