### ISSUE TITLE
GCNet some checkpoint maybe wrong

### ISSUE THREAD

**Issue by funnyday16** [open-mmlab/mmdetection#4654]
I found that some weights of GCNET are wrong and do not match the corresponding config. 

For example, the last row of the table.

Config: https://github.com/open-mmlab/mmdetection/blob/master/configs/gcnet/cascade_mask_rcnn_x101_32x4d_fpn_syncbn-backbone_dconv_c3-c5_r4_gcb_c3-c5_1x_coco.py
Model: http://download.openmmlab.com/mmdetection/v2.0/gcnet/cascade_mask_rcnn_x101_32x4d_fpn_syncbn-backbone_dconv_c3-c5_r4_gcb_c3-c5_1x_coco/cascade_mask_rcnn_x101_32x4d_fpn_syncbn-backbone_dconv_c3-c5_r4_gcb_c3-c5_1x_coco_20200518_041145-24cabcfd.pth

I guess the backbone corresponding to this weight is resnet50. Other x101 weights may also have problems and look forward to fixing them.

**Comment by jshilong** [comment]
Thanks。
We would fix it asap.
@xvjiarui @ZwwWayne

**Comment by xvjiarui** [comment]
Hi @funnyday16 
I just checked. The provided config and checkpoint are correct. Could you please provide your error message?
