### ISSUE TITLE
Purpose of "+ 1" in width/height JSON output of xyxy2xywh

### ISSUE THREAD

**Issue by giulio-zhou** [open-mmlab/mmdetection#466]
Just as #450 described how COCO's width/height were subtracted by 1, I wanted to know what is the purpose of adding 1 to the width and height of the output JSON. Is this COCO-specific? It was noted in the 2018 COCO competition slides that "A single pixel shift can lead to 1 point drop." How did this manifest during production and how do these -1/+1 adjustments fix that?

Edit: Naive hypothesis is that the +1 simply "unsubtracts" the -1 applied to the COCO dataset. But how would this affect other datasets?

**Comment by hellock** [comment]
It depends on your annotation. Specifically, whether (x1, x2, y1, y2) contain the pixel of x2 and y2 or not.
