### ISSUE TITLE
Model mAP drops when exported to onnx

### ISSUE THREAD

**Issue by ArarakiRen** [open-mmlab/mmdetection#4660]
Hello, I've converted Cascade-RCNN-R50-FPN-coco to ONNX format but when I perform inference with it by onnx-runtime, the final mAP drops from 40.3 to 39.7. Same thing happens with Retinanet. So may I ask if you have tested the accuracy of your ONNX models on coco dataset? Thanks.

**Comment by hhaAndroid** [comment]
Hi, @ArarakiRen Thank you for your feedback. We have not tested the accuracy of ONNX models on the coco dataset yet, but it is in progress. Once completed, the docs will be updated, please continue to pay attention. Thank you!
