### ISSUE TITLE
Add ability to serve models

### ISSUE THREAD

**Issue by waddington-ou-phd-1** [open-mmlab/mmdetection#4661]
**Describe the feature**

There are libaries such as Tensorflow Serve and Pytorch Serve. It would be useful is MMDetection had the ability to serve models, maybe inside a container, through an API endpoint.

**Motivation**
It would allow us to easily use models trained using MMDetection in other applications for inference.

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
At the moment I have a script which calls an MMDetection script that I use as the entrypoint for a Docker container; it starts up whenever I need it, it's pretty slow. It would be nice if there was an easier way.

**Comment by ZwwWayne** [comment]
Thanks for your kind suggestion. Due to limited resources, this may not be supported soon. But we will consider this valuable feature in the future.
