### ISSUE TITLE
TypeError: "img" must be a numpy array or a str or a pathlib.Path object

### ISSUE THREAD

**Issue by SherlockHua1995** [open-mmlab/mmdetection#4664]
hello,thanks for this nice work.
when i test my trained model, the following error occured.
Traceback (most recent call last):
  File "test_save_1.py", line 22, in <module>
    BaseDetector.show_result(img, result, model.CLASSES, out_file='testOut.jpg')
  File "pathto/mmdet/models/detectors/base.py", line 316, in show_result
    img = mmcv.imread(img)
  File "pathto/python3.6/site-packages/mmcv/image/io.py", line 174, in imread
    raise TypeError('"img" must be a numpy array or a str or '
**TypeError: "img" must be a numpy array or a str or a pathlib.Path object**
I have checked the img variable, and it's a abosulte path to an image.
Any advice would be grateful.
And when I use the test.py to test: python tools/test.py configs/vfnet/vfnet_x101_64x4d_fpn_mdconv_c3-c5_mstrain_2x_coco.py work_dirs/vfnet/latest.pth --show-dir result, the saved image is all blank.

**Comment by ZwwWayne** [comment]
Hi @SherlockHua1995 ,
For the test_save_1.py, this is weird, could you check again that the variable `img` is correct? From the error message, it is neither string or numpy array.  For the test script but, it is a different thing, please create a new issue following the `error template` for that.
