### ISSUE TITLE
占用显存疑问

### ISSUE THREAD

**Issue by XiaYuanxiang** [open-mmlab/mmdetection#467]
我看Model zoo里，faster rcnn 50 fpn占用显存是5.1g，但我用test.py测试时，11个多g的显存都不够用，所以这个5.1指的是训练时所用的？

R-50-FPN | pytorch | 1x | 5.1 | 0.554 | 9.9 | 36.4

**Comment by hellock** [comment]
We report the training GPU memory as the maximum value of `torch.cuda.max_memory_cached()` for all 8 GPUs. Note that this value is usually less than what nvidia-smi shows, but closer to the actual requirements.
