### ISSUE TITLE
Building mmcv-full wheel is time consuming

### ISSUE THREAD

**Issue by KamalM9** [open-mmlab/mmdetection#4671]
Upon looking into [FAQS](https://github.com/open-mmlab/mmdetection/blob/84a4570f290a6e6f943fe48956528a189c2abd04/docs/faq.md) and this [issue](https://github.com/open-mmlab/mmdetection/issues/3271), it seems the only resolution to missing `mmcv._ext` module is just uninstalling `mmcv` and installing the full package `mmcv-full`. Meanwhile this solves the problem, library installation becomes very time consuming since building the `mmcv-full` wheel takes 8-10 mins. 

Is there any way around just installing `mmcv-full` which would reduce installation time? Do we need everything in the `mmcv-full` package?

**Comment by xvjiarui** [comment]
You may use pre-build package by `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`.

**Comment by KamalM9** [comment]
Thanks. That is much better.
