### ISSUE TITLE
TTA with inference_detector function

### ISSUE THREAD

**Issue by CuongNN218** [open-mmlab/mmdetection#4672]
I had wrote a custom inference file for inference with inference_detector func. How Can I perform TTA?
here is my config for testing. Did it include TTA when use it with inference_detector func?
`test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            # dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img']),
        ])
]`

**Comment by xvjiarui** [comment]
HI @CuongNN218 
To use TTA, you need to change `imp_scale` to a list of augmented scales.

**Comment by CuongNN218** [comment]
@xvjiarui Thanks for your quick reply. I got it.
