### ISSUE TITLE
How to access the tensors using hooks?

### ISSUE THREAD

**Issue by deepakksingh** [open-mmlab/mmdetection#4675]
Hello
I wanted to access the ground truth tensors and the output tensors using hooks.
I am able to create a custom hook and invoke it at various points like `before_iter` and `after_iter`.
The hook object has the `runner` object. But how can i access the input and output data?
Thanks in advance.

**Comment by ZwwWayne** [comment]
You cannot access the input and output data because the MMCV hooks does not support that. To do what you want, you should use PyTorch hooks.

**Comment by deepakksingh** [comment]
Thank you @ZwwWayne. I will check that out.
