### ISSUE TITLE
Using frozen model of the previous epoch in current epoch

### ISSUE THREAD

**Issue by deepakksingh** [open-mmlab/mmdetection#4676]
Thank you for this amazing framework.
I was trying to build an incremental object detector using mmdetection framework.
I need to access a frozen model of the previous epoch in the current model's epoch.
I was planning to use hooks to trigger during `after_epoch` in current training. But I don't
know how to pass the old frozen model into the current training epoch. 
Any suggestions/feedback could be very helpful.

Thanks in advance.

**Comment by deepakksingh** [comment]
@xvjiarui Could you please help me with this?

**Comment by xvjiarui** [comment]
Hi @deepakksingh 
Sorry for the late reply. 
I don't think there is an easy way to regressively load previous epoch weight. You may need to customize the runner.

**Comment by deepakksingh** [comment]
Thanks @xvjiarui
