### ISSUE TITLE
How to save best epoch？

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#4677]
Hi, dear authors！
I want to save the best epoch during the entire training period(that is, only the best model is left after the training is completed), how can I do it?
Thank you！

**Comment by deepakksingh** [comment]
Hello,
You can use 
```
evaluation = dict(
    ..
    metric='bbox',
    save_best = 'bbox_mAP',
    ...
)
```
in your config file.

**Comment by zhongqiu1245** [comment]
@deepakksingh Thank you, are there any other options besides this option?  Could you tell me where can I see these options?

**Comment by deepakksingh** [comment]
I actually found out after going through the code of EvalHook. You can find it here:
https://mmdetection.readthedocs.io/en/latest/_modules/mmdet/core/evaluation/eval_hooks.html?highlight=save%20best

**Comment by zhongqiu1245** [comment]
@deepakksingh Thank you

**Comment by freepoet** [comment]
i

> Hello,
> You can use
> 
> ```
> evaluation = dict(
>     ..
>     metric='bbox',
>     save_best = 'bbox_mAP',
>     ...
> )
> ```
> 
> in your config file.

it seems not only  save the best model, but also save the every model after training. The best model is the soft link of the model with best bbox_mAP among all the models.

**Comment by fangxu622** [comment]
I have the same question, and I set the config as 
```
evaluation = dict(
    ..
    metric='bbox',
    save_best = 'bbox_mAP',
    ...
)
```
errors still happened.

```
Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 181, in main
    meta=meta)
  File "mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "mmdetection/mmdet/core/evaluation/eval_hooks.py", line 116, in before_train_epoch
    self.after_train_epoch(runner)
  File "mmdetection/mmdet/core/evaluation/eval_hooks.py", line 150, in after_train_epoch
    last_ckpt = runner.meta['hook_msgs']['last_ckpt']
KeyError: 'last_ckpt'
```

**Comment by tomatowithpotato** [comment]
> i
> 
> > Hello,
> > You can use
> > ```
> > evaluation = dict(
> >     ..
> >     metric='bbox',
> >     save_best = 'bbox_mAP',
> >     ...
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in your config file.
> 
> it seems not only save the best model, but also save the every model after training. The best model is the soft link of the model with best bbox_mAP among all the models.

add
'''
checkpoint_config = dict(interval=-1)
'''
in your config
-1 means never save checkpoint

**Comment by freepoet** [comment]
> > i
> > > Hello,
> > > You can use
> > > ```
> > > evaluation = dict(
> > >     ..
> > >     metric='bbox',
> > >     save_best = 'bbox_mAP',
> > >     ...
> > > )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > in your config file.
> > 
> > 
> > it seems not only save the best model, but also save the every model after training. The best model is the soft link of the model with best bbox_mAP among all the models.
> 
> add
> '''
> checkpoint_config = dict(interval=-1)
> '''
> in your config
> -1 means never save checkpoint

Thank you, but how to test your model without checkpoint?

**Comment by tomatowithpotato** [comment]
> > > i
> > > > Hello,
> > > > You can use
> > > > ```
> > > > evaluation = dict(
> > > >     ..
> > > >     metric='bbox',
> > > >     save_best = 'bbox_mAP',
> > > >     ...
> > > > )
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > in your config file.
> > > 
> > > 
> > > it seems not only save the best model, but also save the every model after training. The best model is the soft link of the model with best bbox_mAP among all the models.
> > 
> > 
> > add
> > '''
> > checkpoint_config = dict(interval=-1)
> > '''
> > in your config
> > -1 means never save checkpoint
> 
> Thank you, but how to test your model without checkpoint?
'''
evaluation = dict(
    ..
    metric='bbox',
    save_best = 'bbox_mAP',
    ...
)
'''
will save best checkpoint
