### ISSUE TITLE
Issue with checkpoint

### ISSUE THREAD

**Issue by JeHeeHan0403** [open-mmlab/mmdetection#4678]
![image](https://user-images.githubusercontent.com/70060517/109132965-c8f1f800-7797-11eb-8fde-a1b55b0edb8f.png)

I am trying to access this site for checkpoint and it kept returning this message,

Is there any other way that I can see the checkpoint? 

Thank you in advance

**Comment by ZwwWayne** [comment]
The cite is unreachable. Which checkpoint you cannot download? Please specify it in a new issue. This issue will be closed.
