### ISSUE TITLE
Initializing RPN module

### ISSUE THREAD

**Issue by deepakksingh** [open-mmlab/mmdetection#4679]
Hello,
Is there a way to set pretrained=False for the RPN head.
I'm trying to train Faster-RCNN and I wanted to know if there is way to access/modify the initialization of RPN.
I tried setting the following:
```
model = dict(
    type='FasterRCNN',
    rpn_head = dict(
    type = 'RPNHead',
    pretrained=None
    )
)
```
But it throws:
```
TypeError: FasterRCNN: RPNHead: __init__() got an unexpected keyword argument 'pretrained'
```

Any workaround to access the RPN module before the training run?
Thanks in advance.

**Comment by jshilong** [comment]
There are no pre-train parameters in RPN by defaults.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
