### ISSUE TITLE
Pascal自定义数据集上测试时 class 总是显示的是coco的80个类别

### ISSUE THREAD

**Issue by HelloMX** [open-mmlab/mmdetection#468]

**Comment by hellock** [comment]
You are using the coco_eval scripts?

**Comment by HelloMX** [comment]
我的具体操作步骤如下：
1）MyVOCdataset 继承VOCDataset  仅修改classes 为自己的类别
2）参照configs/pascal中的修改dcn中的数据相关的数据相关的配置 myfrcnnconfig.py
       dataset_type = 'MYVOCDataset'
        data_root = 'mypath'
3）通过第二步的配置文件训练
4）通过tools/test.py  基于训练的模型生成result.pkl
5)  通过tools/voc_eval.py  result.pkl  myfrcnnconfig.py

第五步的时候就会报错  具体定位问题时发现 
voc_eval.py line11   det_results = mmcv.load(result_file)
这一步中 在det_results 中包含的 num_classes ==80   而  MyVOCdataset.CLASSES==4 
所以是在 test.py 中 生成outputs 的时候就出问题了 

进一步就不知道问题出在哪里，应该和底层逻辑有关
所以想问下最后模型预测的类别数量不是根据MyVOCdataset.CLASSES来判断的吗？
@hellock  谢谢！

**Comment by HelloMX** [comment]
还有一个奇怪的现象就是 如果我直接按照上述步骤操作但是直接把configs/pascal中几个配置文件的配置修改成dataset_type = 'MYVOCDataset'
data_root = 'mypath'
而不是把dcn中的配置文件修改成
dataset_type = 'MYVOCDataset'
data_root = 'mypath'
上述流程走下来 det_results 中包含的还是vocdataset中的类 而不是 myvocdataset的类
所以还是很疑惑 最后模型预测的类别是根据什么来判断的？
