### ISSUE TITLE
about epoch

### ISSUE THREAD

**Issue by Jnyle** [open-mmlab/mmdetection#4682]
Hi ,if I want to get the current epoch time in the anchor_head.py file, what should I do? 
Thank you!

**Comment by yhcao6** [comment]
The easiest way is to add a line here:

https://github.com/open-mmlab/mmdetection/blob/8824417be9218e9c300c13dcd2ade46958002f3c/mmdet/apis/train.py#L102-L110

```
# if the anchor_head is RPNHead
model.module.rpn_head.runner = runner
```

Then you can access the current epoch by:
```
self.runner.epoch
```
