### ISSUE TITLE
Can I train with a CPU-only installation?

### ISSUE THREAD

**Issue by qAp** [open-mmlab/mmdetection#4686]
I tried executing `tools/train.py` but got 
```
AssertionError: Torch not compiled with CUDA enabled
```

Am I right to assume that this means it's not possible to do any training without a GPU, and that the CPU-only installation is only for carrying out some inference?

**Comment by ZwwWayne** [comment]
For now, MMDetection does not support CPU training but only supports CPU inference. See [doc](https://mmdetection.readthedocs.io/en/latest/get_started.html#install-with-cpu-only).
