### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by NatalinoMantoan** [open-mmlab/mmdetection#4687]
Hi everyone it's my first time writing here, so I start to tell you sorry if something is wrong and I say sorry for the second time cause of my english.
I m using my own dataset in COCO format, and I m trying to training a model. I followed the tutorial on https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html but it seems it doesn't work well.
I m working on Google Colab so i followed the other tutorial too https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb.

1. 

**I report my error:** 
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-02-26 17:53:18,680 - mmdet - INFO - Start running, host: root@dfc1d08735e9, work_dir: /content/mmdetection/work_dirs/my_custom_config
2021-02-26 17:53:18,681 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/content/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 746, in __init__
    self._try_put_index()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/content/mmdetection/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

2.

**Here i put my config that i m using:** 
model = dict(
    type='CascadeRCNN',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='CascadeRoIHead',
        num_stages=3,
        stage_loss_weights=[1, 0.5, 0.25],
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=[
            dict(type='Shared2FCBBoxHead', num_classes=2),
            dict(type='Shared2FCBBoxHead', num_classes=2),
            dict(type='Shared2FCBBoxHead', num_classes=2)
        ],
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=2,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.6,
                    neg_iou_thr=0.6,
                    min_pos_iou=0.6,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.7,
                    neg_iou_thr=0.7,
                    min_pos_iou=0.7,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)))
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type='CocoDataset',
        ann_file='/content/mmdetection/TestCoorsa/annotations/train2020.json',
        img_prefix='/content/mmdetection/TestCoorsa/train/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
        ],
        classes=('0', '1')),
    val=dict(
        type='CocoDataset',
        ann_file='/content/mmdetection/TestCoorsa/annotations/valid.json',
        img_prefix='/content/mmdetection/TestCoorsa/valid/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('0', '1')),
    test=dict(
        type='CocoDataset',
        ann_file='/content/mmdetection/TestCoorsa/annotations/valid.json',
        img_prefix='/content/mmdetection/TestCoorsa/valid/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('0', '1')))
evaluation = dict(metric=['bbox', 'segm'])
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
classes = ('0', '1')
work_dir = './work_dirs/my_custom_config'
gpu_ids = range(0, 1)

3.
I converted my dataset from a Pascal VOC type to a COCO dataset type on roboflow, so i think it worked well. I have the annotations files write in the right way and everything it's correct i think. I just did a resize to 416x416 when i converted the dataset.

4.
**My environment is the same of the colab tutorial of https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb ** but in case i try to  say something more here.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Python 3.7
torchversion 1.5.1
mmdet 2.9.0
GCC 7.5

Thank you for any answer, and i m sorry again if i did something wrong posting this error.

**Comment by ZwwWayne** [comment]
Hi @NatalinoMantoan ,
May I ask more information about your dataset, e.g., how many data is contained in your dataset, are they all in the similar aspect ratio?

**Comment by ZwwWayne** [comment]
There are similar bugs mentioned in https://github.com/open-mmlab/mmdetection/issues/4199. Could you check this issue and see whether it could solve your problem?

**Comment by NatalinoMantoan** [comment]
> 
> 
> Hi @NatalinoMantoan ,
> May I ask more information about your dataset, e.g., how many data is contained in your dataset, are they all in the similar aspect ratio?

TestCoorsa-COCO - v5 CocoDat
==============================

**My dataset is this one:**
This dataset was exported via roboflow.ai on February 25, 2021 at 4:59 PM GMT

It includes 508 images.
Valvola-rossa--valvola-gialla are annotated in COCO format.

The following pre-processing was applied to each image:
* Auto-orientation of pixel data (with EXIF-orientation stripping)
* Resize to 416x416 (Stretch)

The following augmentation was applied to create 2 versions of each source image:
* Random brigthness adjustment of between -20 and +20 percent

**Other information about dataset**:
My dataset has 2 classes "valvola rossa" and "valvola gialla". It's divided in Train, Validation and Test.
An example of a name of my image is this one: "image1_0010_png.rf.fc1fa3f73a534d95a421776dc16b9b67.jpg"
I add a little part of my annotation file:

    "info": {
        "year": "2021",
        "version": "5",
        "description": "Exported from roboflow.ai",
        "contributor": "",
        "url": "https://app.roboflow.ai/datasets/testcoorsa-coco/5",
        "date_created": "2021-02-25T16:59:01+00:00"
    },
    "licenses": [
        {
            "id": 1,
            "url": "",
            "name": "Unknown"
        }
    ],
    "categories": [
        {
            "id": 0,
            "name": "valvola-rossa--valvola-gialla",
            "supercategory": "none"
        },
        {
            "id": 1,
            "name": "Valvola gialla",
            "supercategory": "valvola-rossa--valvola-gialla"
        },
        {
            "id": 2,
            "name": "Valvola rossa",
            "supercategory": "valvola-rossa--valvola-gialla"
        }
    ],
    "images": [
        {
            "id": 0,
            "license": 1,
            "file_name": "image1_0251_png.rf.fae9059a27170f6c236d95a3985c2167.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 1,
            "license": 1,
            "file_name": "image1_0010_png.rf.fc1fa3f73a534d95a421776dc16b9b67.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 2,
            "license": 1,
            "file_name": "image1_0208_png.rf.fa0c16bfba6bdb55aea67f0c8cf7e212.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 3,
            "license": 1,
            "file_name": "image1_0229_png.rf.fd02a94f99ab73e5df17b19e0005d31d.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 4,
            "license": 1,
            "file_name": "image1_0183_png.rf.f651213ce813368381db2f1e3335b060.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 5,
            "license": 1,
            "file_name": "image1_0311_png.rf.e1e998c2e6a021550a5d9bb12587726c.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 6,
            "license": 1,
            "file_name": "image1_0268_png.rf.dde341335dd2f8731ecc81017c54d4f9.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 7,
            "license": 1,
            "file_name": "image1_0020_png.rf.e8d2d5171c6110fceb62f3858b2fd511.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 8,
            "license": 1,
            "file_name": "image1_0284_png.rf.02bb34b30ba2d178f337aca7e0111f38.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 9,
            "license": 1,
            "file_name": "image1_0084_png.rf.06558a2b670c3d7a242680a047b85e9f.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
        },
        {
            "id": 10,
            "license": 1,
            "file_name": "image1_0301_png.rf.06ff6c59ba8831245f64332e963e3b85.jpg",
            "height": 416,
            "width": 416,
            "date_captured": "2021-02-25T16:59:01+00:00"
},.... and it continues
 
that's the a part of the continue:
{
            "id": 728,
            "image_id": 39,
            "category_id": 2,
            "bbox": [
                169,
                128,
                19.5,
                52.5
            ],
            "area": 1023.75,
            "segmentation": [],
            "iscrowd": 0
        },
        {
            "id": 729,
            "image_id": 40,
            "category_id": 2,
            "bbox": [
                149,
                129,
                29.5,
                38.5
            ],
            "area": 1135.75,
            "segmentation": [],
            "iscrowd": 0
        },
        {
            "id": 730,
            "image_id": 40,
            "category_id": 2,
            "bbox": [
                189,
                218,
                15,
                61
            ],
            "area": 915,
            "segmentation": [],
            "iscrowd": 0
        },
        {
            "id": 731,
            "image_id": 40,
            "category_id": 2,
            "bbox": [
                124,
                188,
                23.5,
                49
            ],
            "area": 1151.5,
            "segmentation": [],
            "iscrowd": 0
        },
        {
            "id": 732,
            "image_id": 40,
            "category_id": 2,
            "bbox": [
                125,
                233,
                24,
                51
            ],


I will try to see if i can resolve the bug with the suggestions on #4199 like you said. If you have any more things to request about my config and dataset, i m here. Thank you very very much.

**Comment by hhaAndroid** [comment]
Hi @NatalinoMantoan,  I think you can first use the [browse_dataset](https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py) script to visualize whether the data is correct.

**Comment by NatalinoMantoan** [comment]
Hello,
I will try to use the script too and i will update if the problem will be resolved. Thank you very much

**Comment by uniartisan** [comment]
To be honest, I have met the same problem when I upgrade mmdet from 2.4.0 to 2.9.0.
I tried some solutions but it seemed to be useless, so I reinstall mmdet==2.4.0

**Comment by hhaAndroid** [comment]
#210

**Comment by qgh1223** [comment]
The bug I met in this problem is from the different class number.
Something wrong happened in the filter_imgs function in coco.py.
You can change self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES) to self.cat_ids = self.coco.get_cat_ids() in load_annotations

**Comment by JustVietNH** [comment]
> The bug I met in this problem is from the different class number.
> Something wrong happened in the filter_imgs function in coco.py.
> You can change self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES) to self.cat_ids = self.coco.get_cat_ids() in load_annotations

Thank you, this solved the given error for me!

**Comment by alaa-shubbak** [comment]
> To be honest, I have met the same problem when I upgrade mmdet from 2.4.0 to 2.9.0.
> I tried some solutions but it seemed to be useless, so I reinstall mmdet==2.4.0

I am working with mmdet version 2.13 , the test of images and pretrained models are working but the training is not . 

i try to down grade it to version 2.4.0 by having mmcv-full= to be 1.1.1 , 1.1.2 and 1.1.3 and 1.1.4 , the only one that being  able to download was 1.1.1 , but unfortunately it gives  the following error massage
![error](https://user-images.githubusercontent.com/10245810/123806589-5f255e80-d8ef-11eb-9833-ab8476d26568.JPG)

it asks me to upgrade it to higher version (mmdet 2.12.0 or higher) . 

so what shall i do?

**Comment by alaa-shubbak** [comment]
can any one till me how to use the command  `browse_dataset`
so will be able to check my dataset . 
what should i see after running this command? 

actually ,  i am afraid that my problem is in `data/dataloader.py` or in `data/sampler.py`.

**Comment by github-eliviate** [comment]
> The bug I met in this problem is from the different class number. Something wrong happened in the filter_imgs function in coco.py. You can change self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES) to self.cat_ids = self.coco.get_cat_ids() in load_annotations

yes,I have 3 category in coco['categories'],but only have 2 category in data

**Comment by TheSeriousProgrammer** [comment]
> The bug I met in this problem is from the different class number. Something wrong happened in the filter_imgs function in coco.py. You can change self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES) to self.cat_ids = self.coco.get_cat_ids() in load_annotations

I dont see this patch in the main repo, does this change affect other models?
