### ISSUE TITLE
Training Tutorial error: AttributeError: 'ConfigDict' object has no attribute 'train_cfg'

### ISSUE THREAD

**Issue by craine** [open-mmlab/mmdetection#4688]
I was going through the Colab tutorial:
https://colab.research.google.com/github/ZwwWayne/mmdetection/blob/update-colab/demo/MMDet_Tutorial.ipynb#scrollTo=7WBWHu010PN3

And ran into the following error at Train a New Detector:
AttributeError: 'ConfigDict' object has no attribute 'train_cfg'

When I run: print(f'Config:\n{cfg.pretty_text}')
There does appear to be:

train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),

Thought it might be helpful to note this for others who might use it and to learn how to fix the issue for my own use.

**Comment by craine** [comment]
I ended up finding this in another issue. But still, might want to update tutorial colab. 

Solution is change:
model = build_detector( cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)

with

model = build_detector( cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))

**Comment by ZwwWayne** [comment]
Duplicates #4603 and this issue have been fixed in https://github.com/open-mmlab/mmdetection/pull/4643

**Comment by gledsonmelotti** [comment]
Hello everyone, how are you? I still have a question about the old error 'ConfigDict' object has no attribute 'train_cfg'. I modified my model = build_detector( cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg) to
model = build_detector( cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg')), but I got a new error:
AttributeError: 'ConfigDict' object has no attribute 'log_level'
Could anyone provide a solution please?
