### ISSUE TITLE
About get_flpos.py

### ISSUE THREAD

**Issue by pengzhiliang** [open-mmlab/mmdetection#4689]
Hello, 
I'd like to know if there is a self-attention module in backbone, is it accurate to use get_flops.py to calculate flops?

**Comment by ZwwWayne** [comment]
The flop counter relies on the implementation is MMCV [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/utils/flops_counter.py). It seems that multihead attention or customized attention module's FLOP is not included.

**Comment by pengzhiliang** [comment]
Ok, I find that, thank u~

In fact, if the torch.bmm operator is included, the flops will be accurate.
And, the LayerNorm is also ignored in  get_model_complexity_info function.

**Comment by ZwwWayne** [comment]
Thanks for your suggestion. Would you like to create a PR to MMCV? If not, we may add this feature in MMCV in the next month.

**Comment by pengzhiliang** [comment]
ooooh!  I'm sorry that I don't know how to implement it in fact. 

Therefore,  looking forward to the update of mmcv ! 

Thank u~
