### ISSUE TITLE
How to assign different loss weights to concatenated datasets?

### ISSUE THREAD

**Issue by fzfs** [open-mmlab/mmdetection#4697]
Hi，thanks for your code！
I want to assign different loss weights to concatenated datasets in the training phase.
Can you give me some advice?

**Comment by jshilong** [comment]
You can set an attribute `id` for all images in a dataset and pass it to `image_metas` and use different loss weights in the head according to this `id`.

**Comment by fzfs** [comment]
Thanks for your help!

**Comment by fzfs** [comment]
Hi, another question, how to pass the attribute id to image_metas?

**Comment by fzfs** [comment]
I knew it, thanks!
file path: 'mmdet/datasets/pipelines/formatting.py:Collect'
