### ISSUE TITLE
Error with new optimizer docs tutorial 5

### ISSUE THREAD

**Issue by waddington-ou-phd-1** [open-mmlab/mmdetection#4698]
When following the instructions at https://mmdetection.readthedocs.io/en/latest/tutorials/customize_runtime.html?highlight=optimizer#customize-self-implemented-optimizer to implement a new optimizer a step is missing.

As it stands you will get an error saying that the optimizer is not in the registry. The fix is to edit `mmdet/core/__init__.py` to add an import for the new optimizer directory. The line to add is `from .optimizer import *`.

**Comment by waddington-ou-phd-1** [comment]
Having seen this https://github.com/open-mmlab/mmdetection/issues/2041

you must also change the registry import line to `from mmcv.runner.optimizer import build_optimizer, OPTIMIZERS` to be able to add the optimizer to the registry.

**Comment by jshilong** [comment]
Thanks for your suggestion, we would fix it asap.

**Comment by waddington-ou-phd-1** [comment]
I will be happy to submit a PR with the proviso that you can answer a few more questions on this thread in the coming days about custom optimizers. As it stands the custom optimizer documentation is next-to-none and doesn't actually provide anywhere near enough information to implement one. Once I get a working example (hence more questions from me in the coming days) I will submit a PR withe details.

Thanks

**Comment by waddington-ou-phd-1** [comment]
How can I use the closure as per PyTorch custom optimizer guide? https://pytorch.org/docs/stable/optim.html#optimizer-step-closure.

I need to able to re-calculate a models output multiple times on the same batch within a single call to the optimizers `.step()` function.

**Comment by jshilong** [comment]
Sorry for the late response, what you can modify is in MMCV
https://github.com/open-mmlab/mmcv/blob/1790e9f26563e2772db2479db267c7b2b9df8068/mmcv/runner/hooks/optimizer.py#L35

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
