### ISSUE TITLE
how to create results.pkl?

### ISSUE THREAD

**Issue by chelixuan** [open-mmlab/mmdetection#47]
when I train the model, I run:
python tools/train.py /home1/clx/mmdetection/configs/mask_rcnn_r50_fpn_1x.py --gpus 2 --work_dir /home1/clx/mmdetection/logs/logs_mask/ --validat

but after the training process, in the work_dir, there exists a file named "20181019_155702.log"

**Comment by hellock** [comment]
You can run the testing scripts to get the results. There is no result file (temp files will be deleted) created during training.
