### ISSUE TITLE
I use DETR with VOCDatesets, and get mAP=0. With the same VOCDatasets, more than 95% of mAP can be obtained by Faster-rcnn or SSD300.

### ISSUE THREAD

**Issue by dingdingzuo** [open-mmlab/mmdetection#4702]
**Notice**

There are several common situations in the reimplementation issues as below

1. Reimplement a model in the model zoo using the provided configs
2. Reimplement a model in the model zoo on other dataset (e.g., custom datasets)
3. Reimplement a custom model but all the components are implemented in MMDetection
4. Reimplement a custom model with new modules implemented by yourself

There are several things to do for different cases as below.

- For case 1 & 3, please follow the steps in the following sections thus we could help to quick identify the issue.
- For case 2 & 4, please understand that we are not able to do much help here because we usually do not know the full code and the users should be responsible to the code they write.
- One suggestion for case 2 & 4 is that the users should first check whether the bug lies in the self-implemented code or the original code. For example, users can first make sure that the same model runs well on supported datasets. If you still need help, please describe what you have done and what you obtain in the issue, and follow the steps in the following sections and try as clear as possible so that we can better help you.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The issue has not been fixed in the latest version.

**Describe the issue**

A clear and concise description of what the problem you meet and what have you done.

**Reproduction**

1. What command or script did you run?

DETR

2. What config dir you run?

------------------------------------------------------------

2021-02-27 09:01:47,808 - mmdet - INFO - Distributed training: False
2021-02-27 09:01:51,999 - mmdet - INFO - Config:
dataset_type = 'VOCDataset'
data_root = '/media/ices/327E75477E7504BF/lgj/mmdetection/data/Drink_100/VOCdevkit/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='AutoAugment',
        policies=[[{
            'type':
            'Resize',
            'img_scale': [(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                          (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                          (736, 1333), (768, 1333), (800, 1333)],
            'multiscale_mode':
            'value',
            'keep_ratio':
            True
        }],
                  [{
                      'type': 'Resize',
                      'img_scale': [(400, 1333), (500, 1333), (600, 1333)],
                      'multiscale_mode': 'value',
                      'keep_ratio': True
                  }, {
                      'type': 'RandomCrop',
                      'crop_type': 'absolute_range',
                      'crop_size': (384, 600),
                      'allow_negative_crop': True
                  }, {
                      'type':
                      'Resize',
                      'img_scale': [(480, 1333), (512, 1333), (544, 1333),
                                    (576, 1333), (608, 1333), (640, 1333),
                                    (672, 1333), (704, 1333), (736, 1333),
                                    (768, 1333), (800, 1333)],
                      'multiscale_mode':
                      'value',
                      'override':
                      True,
                      'keep_ratio':
                      True
                  }]]),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=1),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=1),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type='VOCDataset',
            ann_file=[
                '/media/ices/327E75477E7504BF/lgj/mmdetection/data/Drink_100/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt'
            ],
            img_prefix=[
                '/media/ices/327E75477E7504BF/lgj/mmdetection/data/Drink_100/VOCdevkit/VOC2007/'
            ],
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='Pad', size_divisor=32),
                dict(type='DefaultFormatBundle'),
                dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
            ]),
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='AutoAugment',
                policies=[[{
                    'type':
                    'Resize',
                    'img_scale': [(480, 1333), (512, 1333), (544, 1333),
                                  (576, 1333), (608, 1333), (640, 1333),
                                  (672, 1333), (704, 1333), (736, 1333),
                                  (768, 1333), (800, 1333)],
                    'multiscale_mode':
                    'value',
                    'keep_ratio':
                    True
                }],
                          [{
                              'type': 'Resize',
                              'img_scale': [(400, 1333), (500, 1333),
                                            (600, 1333)],
                              'multiscale_mode': 'value',
                              'keep_ratio': True
                          }, {
                              'type': 'RandomCrop',
                              'crop_type': 'absolute_range',
                              'crop_size': (384, 600),
                              'allow_negative_crop': True
                          }, {
                              'type':
                              'Resize',
                              'img_scale': [(480, 1333), (512, 1333),
                                            (544, 1333), (576, 1333),
                                            (608, 1333), (640, 1333),
                                            (672, 1333), (704, 1333),
                                            (736, 1333), (768, 1333),
                                            (800, 1333)],
                              'multiscale_mode':
                              'value',
                              'override':
                              True,
                              'keep_ratio':
                              True
                          }]]),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=1),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ]),
    val=dict(
        type='VOCDataset',
        ann_file=
        '/media/ices/327E75477E7504BF/lgj/mmdetection/data/Drink_100/VOCdevkit/VOC2007/ImageSets/Main/test.txt',
        img_prefix=
        '/media/ices/327E75477E7504BF/lgj/mmdetection/data/Drink_100/VOCdevkit/VOC2007/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=1),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='VOCDataset',
        ann_file=
        '/media/ices/327E75477E7504BF/lgj/mmdetection/data/Drink_100/VOCdevkit/VOC2007/ImageSets/Main/test.txt',
        img_prefix=
        '/media/ices/327E75477E7504BF/lgj/mmdetection/data/Drink_100/VOCdevkit/VOC2007/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=1),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=1, metric='mAP')
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
model = dict(
    type='DETR',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(3, ),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=False),
        norm_eval=True,
        style='pytorch'),
    bbox_head=dict(
        type='TransformerHead',
        num_classes=50,
        in_channels=2048,
        num_fcs=2,
        transformer=dict(
            type='Transformer',
            embed_dims=256,
            num_heads=8,
            num_encoder_layers=6,
            num_decoder_layers=6,
            feedforward_channels=2048,
            dropout=0.1,
            act_cfg=dict(type='ReLU', inplace=True),
            norm_cfg=dict(type='LN'),
            num_fcs=2,
            pre_norm=False,
            return_intermediate_dec=True),
        positional_encoding=dict(
            type='SinePositionalEncoding', num_feats=128, normalize=True),
        loss_cls=dict(
            type='CrossEntropyLoss',
            bg_cls_weight=0.1,
            use_sigmoid=False,
            loss_weight=1.0,
            class_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=5.0),
        loss_iou=dict(type='GIoULoss', loss_weight=2.0)),
    train_cfg=dict(
        assigner=dict(
            type='HungarianAssigner',
            cls_cost=dict(type='ClassificationCost', weight=1.0),
            reg_cost=dict(type='BBoxL1Cost', weight=5.0),
            iou_cost=dict(type='IoUCost', iou_mode='giou', weight=2.0))),
    test_cfg=dict(max_per_img=100))
optimizer = dict(
    type='AdamW',
    lr=0.0001,
    weight_decay=0.0001,
    paramwise_cfg=dict(
        custom_keys=dict(backbone=dict(lr_mult=0.1, decay_mult=1.0))))
optimizer_config = dict(grad_clip=dict(max_norm=0.1, norm_type=2))
lr_config = dict(policy='step', step=[100])
total_epochs = 150
work_dir = './work_dirs/detr_r50_8x2_150e_coco'
gpu_ids = range(0, 1)

3. Did you make any modifications on the code or config? Did you understand what you have modified?
4. What dataset did you use?

VOC

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
nohup: ignoring input
2021-02-27 09:01:43,473 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GCC: gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
PyTorch: 1.7.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cu101
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 5.5
MMCV CUDA Compiler: 9.0
MMDetection: 2.8.0+4310fed
2. You may add addition that may be helpful for locating the problem, such as
   1. How you installed PyTorch [e.g., pip, conda, source]
   2. Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Results**

If applicable, paste the related results here, e.g., what you expect and what you get.

---------------iou_thr: 0.5---------------
2021-02-27 13:49:26,118 - mmdet - INFO - 
+----------+-----+--------+--------+-------+
| class    | gts | dets   | recall | ap    |
+----------+-----+--------+--------+-------+
| BSS      | 405 | 0      | 0.000  | 0.000 |
| FANTA    | 354 | 0      | 0.000  | 0.000 |
| JDB      | 798 | 512000 | 0.158  | 0.013 |
| KSFBHC   | 522 | 0      | 0.000  | 0.000 |
| VTMSSL   | 409 | 0      | 0.000  | 0.000 |
| MD       | 611 | 0      | 0.000  | 0.000 |
| MZYGLC   | 528 | 0      | 0.000  | 0.000 |
| TYNL     | 464 | 0      | 0.000  | 0.000 |
| TYASM    | 483 | 0      | 0.000  | 0.000 |
| YYKX     | 715 | 0      | 0.000  | 0.000 |
| VITANM   | 364 | 0      | 0.000  | 0.000 |
| YLHSNN   | 462 | 0      | 0.000  | 0.000 |
| KSFXL    | 404 | 0      | 0.000  | 0.000 |
| KSFSMT   | 581 | 0      | 0.000  | 0.000 |
| KSFT     | 507 | 0      | 0.000  | 0.000 |
| KSFLC    | 477 | 0      | 0.000  | 0.000 |
| KSFFY    | 649 | 0      | 0.000  | 0.000 |
| KSFMM    | 556 | 0      | 0.000  | 0.000 |
| KSFJN    | 637 | 0      | 0.000  | 0.000 |
| XMTTLL   | 390 | 0      | 0.000  | 0.000 |
| XMLLQN   | 526 | 0      | 0.000  | 0.000 |
| YLJH     | 660 | 0      | 0.000  | 0.000 |
| MZYRG    | 152 | 0      | 0.000  | 0.000 |
| MZYSH    | 307 | 0      | 0.000  | 0.000 |
| BYLMZ    | 442 | 0      | 0.000  | 0.000 |
| BYBXG    | 479 | 0      | 0.000  | 0.000 |
| COCACOLA | 293 | 0      | 0.000  | 0.000 |
| SPIRITNM | 430 | 0      | 0.000  | 0.000 |
| YQSLBS   | 615 | 0      | 0.000  | 0.000 |
| YQSLRT   | 490 | 0      | 0.000  | 0.000 |
| YQSLRC   | 520 | 0      | 0.000  | 0.000 |
| MNDPT    | 689 | 0      | 0.000  | 0.000 |
| MNDXG    | 638 | 0      | 0.000  | 0.000 |
| NSPEPSI  | 579 | 0      | 0.000  | 0.000 |
| JTPEPSI  | 649 | 0      | 0.000  | 0.000 |
| DPCP     | 366 | 0      | 0.000  | 0.000 |
| HKGN     | 431 | 0      | 0.000  | 0.000 |
| KSFWH    | 415 | 0      | 0.000  | 0.000 |
| YYMM     | 544 | 0      | 0.000  | 0.000 |
| YYLP     | 557 | 0      | 0.000  | 0.000 |
| YYHM     | 504 | 0      | 0.000  | 0.000 |
| VTMSRS   | 536 | 0      | 0.000  | 0.000 |
| CPMW     | 392 | 0      | 0.000  | 0.000 |
| BGZMHT   | 620 | 0      | 0.000  | 0.000 |
| YYDTGY   | 571 | 0      | 0.000  | 0.000 |
| BJKZW    | 746 | 0      | 0.000  | 0.000 |
| WHHGWS   | 766 | 0      | 0.000  | 0.000 |
| JDLLM    | 564 | 0      | 0.000  | 0.000 |
| JDLNM    | 540 | 0      | 0.000  | 0.000 |
| DSHC     | 294 | 0      | 0.000  | 0.000 |
+----------+-----+--------+--------+-------+
| mAP      |     |        |        | 0.000 |
+----------+-----+--------+--------+-------+
2021-02-27 13:49:26,202 - mmdet - INFO - Exp name: detr_r50_8x2_150e_coco.py
2021-02-27 13:49:26,223 - mmdet - INFO - Epoch(val) [1][30720]	AP50: 0.0000, mAP: 0.0003

**Issue fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
For VOC you may need more hyper-parameter tuning. Currently, we have no clues for that. It may simply because the dataset is too small and the model cannot learn from that. You may try to load a pre-trained DETR on COCO dataset and use this pre-trained model to train on VOC to see the results.

**Comment by rhythm-A** [comment]
Can you give me some advice to use auto_augment.py?such as polices：v1?

**Comment by mstarget** [comment]
I have the same problem, how to deal with it?
