### ISSUE TITLE
What does the level argument in the Rotate transformation correspond to? 

### ISSUE THREAD

**Issue by vblua** [open-mmlab/mmdetection#4706]
In `mmdectection/mmdet/datasets/pipelines/auto_augment.py`
the Rotate class is used to apply a transformation to the image. What exactly does the `level` argument correspond to? In my case a high value of `level` quickly leads the model to a very low accuracy. Thank you very much.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.

**Comment by hhaAndroid** [comment]
Hi, @vblua  level represents the discrete rounding level of the augment operation, the larger the value, the stronger the augment.
