### ISSUE TITLE
The return value's dimention is inconsistent in multiclass_nms() 

### ISSUE THREAD

**Issue by daleydeng** [open-mmlab/mmdetection#4708]
mdetection/mmdet/core/post_processing/bbox_nms.py

line 80~82: bboxes.numel() ==0 case, return the bboxes's last dim is 4
but in line 90-93, return the dets's last dim is 5(concated with extra score)
the two return value is not consistent, which will cause ERROR when empty case returned. e.g. passing an zero image

![bug_mmdet](https://user-images.githubusercontent.com/770506/109898713-a730cd80-7ccf-11eb-8be2-87754ed19ab8.png)

**Comment by ZwwWayne** [comment]
This issue will be fixed in https://github.com/open-mmlab/mmdetection/pull/4980
