### ISSUE TITLE
last_ckpt not define in save best model option 

### ISSUE THREAD

**Issue by DatDoc** [open-mmlab/mmdetection#4709]
https://github.com/open-mmlab/mmdetection/blob/9946e121e7807e5927b3797bee360392761dbea0/mmdet/core/evaluation/eval_hooks.py#L160-L173

The runner.meta create an empty dictionary and line 166 shows the last_ckpt is new and hasn't store anything in it, so it throw an error when running the first evaluation. Do I need to initialize the last_ckpt?

**Comment by xvjiarui** [comment]
Hi @DatDoc 
It is created [here](https://github.com/open-mmlab/mmcv/blob/27e9ede5b9ba46097a7f5e8bd652b5794ab07769/mmcv/runner/hooks/checkpoint.py#L84).
