### ISSUE TITLE
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core'

### ISSUE THREAD

**Issue by FujieLuo** [open-mmlab/mmdetection#4711]
when I test the module using "python tools/test.py configs/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py work_dirs/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/epoch_4.pth --eval mAP"

`python tools/test.py configs/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py work_dirs/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/epoch_4.pth --eval mAP`

I met this error:

Traceback (most recent call last):
  File "tools/test.py", line 13, in <module>
    from mmdet.core import wrap_fp16_model
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (/home/fujie/MyCode/mycode_2021_1/mmdetection/mmdet/core/__init__.py)

**Comment by navalchand** [comment]
Hi, did you manage to find a fix for this issue. Thanks

**Comment by ningqing123** [comment]
I also had this problem.
