### ISSUE TITLE
How to get mask output 

### ISSUE THREAD

**Issue by MiladGhorbaniG** [open-mmlab/mmdetection#4713]
Hi
I want to use the output mask for the mask-rcnn algorithm. The pickle output is not easy to extract the mask. Is there any tool to export polygon from mask? 
Here is the picke output of the tools/test.py

> ([array([[1.5769882e+03, 6.3306250e+02, 1.7778210e+03, 7.1044873e+02,
>           9.2739618e-01],
>          [3.2007248e+02, 5.0255215e+02, 4.1308646e+02, 5.3752441e+02,
>           8.8351351e-01],
>          [1.2747670e+03, 5.6046014e+02, 1.3662086e+03, 6.1406750e+02,
>           6.5471631e-01],
>          [1.8191138e+03, 2.3844353e+02, 1.8953635e+03, 2.7563647e+02,
>           2.8026125e-01],
>          [1.9200000e+03, 2.1914424e+02, 1.9200000e+03, 2.8582327e+02,
>           2.3006660e-01],
>          [1.8766643e+03, 1.0880000e+03, 1.9200000e+03, 1.0880000e+03,
>           2.3006660e-01]], dtype=float32),
>   array([[1.8183140e+03, 2.3660251e+02, 1.8939658e+03, 2.7566266e+02,
>           8.9468551e-01],
>          [1.2773165e+03, 5.5959711e+02, 1.3640281e+03, 6.1268561e+02,
>           7.5558299e-01],
>          [1.9200000e+03, 2.1894131e+02, 1.9200000e+03, 2.8620560e+02,
>           1.9019245e-01],
>          [1.8764729e+03, 1.0880000e+03, 1.9200000e+03, 1.0880000e+03,
>           1.9019245e-01],
>          [1.5797314e+03, 6.3386627e+02, 1.7754969e+03, 7.1128400e+02,
>           1.5191171e-01],
>          [3.2042102e+02, 5.0163623e+02, 4.1242587e+02, 5.3903339e+02,
>           6.1897986e-02]], dtype=float32)],
>  [[{'counts': b'gbbd16fQ15M3L3O2N101N1N3N1O2N1O101O0O101O00000O100O2N1O100O1000001O00001O001O1O00001O00001N3N3M1O2N1O10O01O1O001O1O0010O000001O00000010O0001O000000000010O000000001O01O0001O000001O01O0000001O000001O000001O00010O1O00001O00001O001N10001O001O001N101O00001O1O001N101O000O2O1O001N10001N10001N101O0O101O001O0O101O000O101O00001O000O1000001O000O1000000000000O10000000001O00000O2O0000001O000O2O000O2O1N2IoXg4',
>     'size': [1088, 1920]},
>    {'counts': b'Qnk:3lQ12O2N>B2ON10001N10001OO1000O10001OO10001O0O1000001N10000O10000O10000O10000O10000O1000000O10000O10O10O1000O100000000O01000000000O100000001N10001O001O0O2N2O0O2O2M1O2O2M6HlgQb1',
>     'size': [1088, 1920]},
>    {'counts': b'fZ\\Z17hQ14L3M3N0O2N100O2N1O1O001O010N2O001O01O01O100O1O001O100O010O1O010O100O10O0100O1O01000O100O01000O1000000O10O1000O0100000O10O1O100O001O1O1O1O1O1N200O1O1O100O1O1O1O2O0O3L2N3M3L4JXnN1RX_b0',
>     'size': [1088, 1920]},
>    {'counts': b'no]l18cQ15M3M3O10O1O101O2M2O2M10001O01O0O2O1O1N3N1O1N2O1O1N2O001O00001N101O001O00001O000000000000001O0001O000000000000001O000O2O001O00001N101O1N2O1N2N101N2NQZj0',
>     'size': [1088, 1920]},
>    {'counts': b'PPho1', 'size': [1088, 1920]},
>    {'counts': b'PPho1', 'size': [1088, 1920]}],
>   [{'counts': b'PP^l15cQ19N1L4M30O10002M4L2N2O1O000010O0O2O1O2M2O1O1N2O1O1N2O001O0O2O001O001O00001O0O100000001O000001O0000000000001O00001O00001O00001N2O001O1O1N101N2N2N2NQ\\k0',
>     'size': [1088, 1920]},
>    {'counts': b'f^^Z1<bQ13N2N100O1O1O1O1O1O100O1O001O001O1O010O1O1O010O1O10O01O1O010O10O01O100O10000O1O10O10O10O01000000O1000O010000000O01000O010O1O1O1O001O1O1O1O1O1O1O100O1O1O1O2N1O2M3N1O2L4N\\X_b0',
>     'size': [1088, 1920]},
>    {'counts': b'PPho1', 'size': [1088, 1920]},
>    {'counts': b'PPho1', 'size': [1088, 1920]},
>    {'counts': b'_fdd1`0^Q13N1O2N100O2N1O1O1O2O0O101O001O00001N1O100O1O100000001N1000001O1O1O001O00001N101O5K1O1O1O1N1010O01O100O001O00001O0000001O01O0001O00001O0001O0000001O0000010O0000010O0000001O000001O01O00000000001O010O00001O001O001O001O0O2O00001O001O001O00001O1N101O001N101O0O2O1O000O2O001N10001N101O0O101O0O10001O00000O2O000000001N100000001O0O100000000000000O101O0000000000000000001N101O000O2O1N3In\\i4',
>     'size': [1088, 1920]},
>    {'counts': b'Rnk:1mQ15M0dnNKmP1:gnNNXQ1>O01N10001O001N1000000O1000O10001O0O1000000O101O0O10000O10000O100O10000O1000000O1000O010000O1000O10O10000000O1000000000000O100000001O0O2O001N101N2O0O3N1N2O1N3M4KlgQb1',
>     'size': [1088, 1920]}]])
>

**Comment by PeterVennerstrom** [comment]
Your output is a list of bounding boxes and corresponding masks 'counts' in RLE format.  The COCO dataset includes an [API](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py) for encoding and decoding binary masks to RLE.

If latency isn't an issue the COCO API is a good option, otherwise you may want to skip converting to RLE and use the masks in their original tensor form directly.

**Comment by MiladGhorbaniG** [comment]
Thank you

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.

**Comment by quliang93** [comment]
@PeterVennerstrom @MiladGhorbaniG 
Thank you.
If I don't want to encode segmentation mask in RLE format,  can I modify test.py in tools/test.py directly?
According your answer, if I want to get mask instead of RLE codes, I have to write a another script with coco API to decode RLE?
I'm new to mmdetection~~

**Comment by PeterVennerstrom** [comment]
RLE format is used to comply with the COCO api to compute accuracy metrics.  Test.py runs the images through the model and prepares the results in the proper format for the COCO api.  For masks, it uses the encode_mask_results() function to convert the numpy masks to RLE.  Test.py could be modified directly to skip the encoding function.  

You may want to look at inference.py if you do not need to compute accuracy metrics and simply want the predicted boxes and masks in numpy format with low latency.

**Comment by vj697** [comment]
@PeterVennerstrom 
I am using demo code and want to make the area of mask 255 and remaining 0 , how i can do??

**Comment by PeterVennerstrom** [comment]
For models which output a mask the second position in result holds the masks.
    result = inference_detector(model, img)

The masks are probably a list of numpy arrays [0,1].  You could loop through them and set the ones to 255.  
    masks = [np.where(m == 1, 255, m) for m in result[1]]

**Comment by vj697** [comment]
@PeterVennerstrom Thank you!!

**Comment by vj697** [comment]
@PeterVennerstrom want to create binary masks for output image and save those binary images , i tried with your line of code ,but it is not working ?

**Comment by vj697** [comment]
@PeterVennerstrom
 want to extract masks value  of the result and  to create binary image of the result , 
The output of  above line of code 



[array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]]), array([], dtype=float64), array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

**Comment by vj697** [comment]
@PeterVennerstrom 
 I want to extract masks value of the result  to create binary image of the result ,
But the  output of above line of your  code is :

[array([[[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
...,
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0],
[0, 0, 0, ..., 0, 0, 0]],

   [[0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    ...,
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0]],

   [[0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    ...,
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0]]]), array([], dtype=float64), array([[[0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    ...,
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0]],

   [[0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    ...,
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0]],

   [[0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    ...,
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0],
    [0, 0, 0, ..., 0, 0, 0]],

   ...,



The output of result[1]:
[[array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],

How shd i extract the mask values??

**Comment by PeterVennerstrom** [comment]
Those are the mask values.    

Result[1] is numpy bool type not int type as I expected.  The numpy where() function will automatically change the type to int [0,1] when doing the comparison and setting the True values to 255.

a = np.array([False, True, False])
a = np.where(a == 1, 255, a)
print(a)

**Comment by vj697** [comment]
@PeterVennerstrom 
Yes!! understood this ,  how to create binary image of the result ?
i mean , masks in the result  image should be white and background  black and i want to save  this binary image...
Please help with code

**Comment by PeterVennerstrom** [comment]
There are quite a few ways to do this.

Pillow should work on the original binary format using mode 1.  

mask_imgs = [Image.fromarray(m, mode='1') for m in result[1]]
[m.save(f'{I}.png') for i, m in enumerate(mask_imgs)]

**Comment by vj697** [comment]
@PeterVennerstrom Thank you!!
