### ISSUE TITLE
Some questions about containers in backbone ?

### ISSUE THREAD

**Issue by ming71** [open-mmlab/mmdetection#472]
https://github.com/open-mmlab/mmdetection/blob/e421e832883241bd7831bf77dc31d5fb31d7da58/mmdet/models/backbones/resnet.py#L253-L254
Is it  better to use nn.Modulelist rather than python list to store the layers ?
Cause as described here:
https://discuss.pytorch.org/t/the-difference-in-usage-between-nn-modulelist-and-python-list/7744/3
the modules put in python list will not update parameters  while training , is it right???

**Comment by thangvubk** [comment]
``make_res_layer()`` is a helper function, not a class method. Here, it returns an ``nn.Module`` and you can see how this module is attached to the backbone as below. 
https://github.com/open-mmlab/mmdetection/blob/e421e832883241bd7831bf77dc31d5fb31d7da58/mmdet/models/backbones/resnet.py#L374

**Comment by ming71** [comment]
> `make_res_layer()` is a helper function, not a class method. Here, it returns an `nn.Module` and you can see how this module is attached to the backbone as below.

I  have just figured out how the backbone part works , but the difference between python list and modulelis still confuse me .  Emm....Then is it OK to use Modulelist Container for storage of layers rahter than python list??
If so ,I would rather take Modulelist as my first consideration  to avoid mistakes  : p

**Comment by hellock** [comment]
`layers` is just a temporal variable, not a container of the module. layerX in the backbone is of `nn.Sequential` type.
