### ISSUE TITLE
How to check if weights are frozen during training process

### ISSUE THREAD

**Issue by Chan-Sun** [open-mmlab/mmdetection#4722]
I want to train a model and freeze the whole network except the final FC layer.

As to freeze model ,I have done some search, put some code in ./mmdet/apis/train.py

```
from mmcv.runner import build_optimizer_constructor
import copy
def Freeze_Model(model):
    for v in model.module.backbone.parameters():
        v.requires_grad = False
    for v in model.module.roi_head.parameters():
        v.requires_grad = False
    for v in model.module.rpn_head.parameters():
        v.requires_grad = False
    return model

def build_optimizer_freeze(model,cfg):
    optimizer_cfg = copy.deepcopy(cfg)
    constructor_type = optimizer_cfg.pop('constructor', 'DefaultOptimizerConstructor')
    paramwise_cfg = optimizer_cfg.pop('paramwise_cfg',None)
    model = Freeze_Model(model)
    optim_constructor = build_optimizer_constructor(
        dict(
            type=constructor_type,
            optimizer_cfg=optimizer_cfg,
            paramwise_cfg=paramwise_cfg))
    optimizer = optim_constructor(model)
    return optimizer
```
the function **build_optimizer_freeze()** above was designed to replace function **build_optimizer()** here https://github.com/open-mmlab/mmdetection/blob/9e3a997417ca3ff3dee7ef06027b59316d886280/mmdet/apis/train.py#L88

I wonder if these code really works and how to check if they make the change.
thanks a lot

**Comment by DuckJ** [comment]
> I want to train a model and freeze the whole network except the final FC layer.
> 
> As to freeze model ,I have done some search, put some code in ./mmdet/apis/train.py
> 
> ```
> from mmcv.runner import build_optimizer_constructor
> import copy
> def Freeze_Model(model):
>     for v in model.module.backbone.parameters():
>         v.requires_grad = False
>     for v in model.module.roi_head.parameters():
>         v.requires_grad = False
>     for v in model.module.rpn_head.parameters():
>         v.requires_grad = False
>     return model
> 
> def build_optimizer_freeze(model,cfg):
>     optimizer_cfg = copy.deepcopy(cfg)
>     constructor_type = optimizer_cfg.pop('constructor', 'DefaultOptimizerConstructor')
>     paramwise_cfg = optimizer_cfg.pop('paramwise_cfg',None)
>     model = Freeze_Model(model)
>     optim_constructor = build_optimizer_constructor(
>         dict(
>             type=constructor_type,
>             optimizer_cfg=optimizer_cfg,
>             paramwise_cfg=paramwise_cfg))
>     optimizer = optim_constructor(model)
>     return optimizer
> ```
> 
> the function **build_optimizer_freeze()** above was designed to replace function **build_optimizer()** here
> 
> https://github.com/open-mmlab/mmdetection/blob/9e3a997417ca3ff3dee7ef06027b59316d886280/mmdet/apis/train.py#L88
> 
> I wonder if these code really works and how to check if they make the change.
> thanks a lot

Hi, Is this way work
