### ISSUE TITLE
Possible dead lock in reduce_mean for FCOS

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection#4724]
I'm not enough familiar with `torch.distributed.all_reduce`, but look like `reduce_mean` [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/fcos_head.py#L239) introduced in #4370 is dangerous. This blocking call is under [if](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/fcos_head.py#L230) statement. If in some processes this condition is `True` and in others it is `False` they are going to wait indefinitely.

I didn't try to catch it while running `FCOS` in latest `mmdetection`. However I got this deadlock while researching custom `FCOS3D` in the latest `mmdetection3d` built with their `Dockerfile`.

**Comment by ZwwWayne** [comment]
Hi @filaPro ,
Thanks for your kind suggestion. Agree with that, if different GPUS are in different condition branch, it will cause deadlock. We will fix that in our next version.

**Comment by zlin3000** [comment]
VFNet(**vfnet_head.py**) also has the same problem. Please fix it as well.
