### ISSUE TITLE
How to use a larger output_size of roi_layer in maskrcnn

### ISSUE THREAD

**Issue by Allen-lz** [open-mmlab/mmdetection#4728]
Hi~ , if I want to use a larger roi_layer in the bbox head and mask head, how can I modify the configuration parameters and network so that it can be successfully trained.

**Comment by jshilong** [comment]
In `roihead` in config，
```       
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),

        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
```
`output_size` maybe what you want。

**Comment by Allen-lz** [comment]
Thanks Reply. 
I have tried to modify the output_size in the config before, but the following error will appear when I run it,

`File "/home/dm/luzeng/maskrcnn_version/siamese_sal_maskrcnn/mmdet/models/losses/cross_entropy_loss.py", line 125, in mask_cross_entropy
    pred_slice, target, weight=class_weight, reduction='mean')[None]
  File "/home/dm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 2538, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([77, 28, 28])) must be the same as input size (torch.Size([77, 56, 56]))
`

**Comment by jshilong** [comment]
You should modify corresponding args(related to the output of roi_extractor) in the head.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
