### ISSUE TITLE
A bug of mmcv when using pytorch 1.7.0

### ISSUE THREAD

**Issue by tianxianhao** [open-mmlab/mmdetection#4730]
At first, I have run the code successfully when the setting of model backbone with **frozen_stages=-1**. 
When i set **frozen_stages=1**, a bug appear. I list it as follow.
=======================================================
(mmdet2.8) tianxianhao@ubuntu:~/Project/mmdet/mmdet2.8/mmdetection/configs/nolo$ CUDA_VISIBLE_DEVICES=4,5,6,7 PORT=29502 ../../tools/dist_train.sh nolo_faster_rcnn_r50_fpn_1x_virat_frozen.py 4
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2021-03-08 20:47:36,007 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.5.1
MMCV: 1.2.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.9.0+9d47a8a
------------------------------------------------------------

2021-03-08 20:47:36,556 - mmdet - INFO - Distributed training: True
2021-03-08 20:47:37,020 - mmdet - INFO - Config:
model = dict(
    type='FasterRCNN3D',
    pretrained=None,
    backbone=dict(
        type='ResNet3d',
        depth=50,
        pretrained='torchvision://resnet50',
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        kernel_depth=5,
        plugin_use_conv=False,
        style='pytorch',
        norm_eval=True,
        frozen_stages=1),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[2],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=1,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.5),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.5),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100)))
dataset_type = 'MyCocoVideoDataset'
data_root = None
img_norm_cfg = dict(
    mean=[0.423, 2.051, 3.02], std=[3.3, 9.462, 11.638], to_rgb=True)
train_pipeline = [
    dict(type='LoadImagesWithRefImgFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(320, 180), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='VideoNormalize',
        mean=[0.423, 2.051, 3.02],
        std=[3.3, 9.462, 11.638],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImagesWithRefImgFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(320, 180),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='VideoNormalize',
                mean=[0.423, 2.051, 3.02],
                std=[3.3, 9.462, 11.638],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type='MyCocoVideoDataset',
        ann_file='/home/tianxianhao/Project/dataset/virat250/COCO_v_train.json',
        img_prefix=None,
        pipeline=[
            dict(type='LoadImagesWithRefImgFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='Resize', img_scale=(320, 180), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='VideoNormalize',
                mean=[0.423, 2.051, 3.02],
                std=[3.3, 9.462, 11.638],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ]),
    val=dict(
        type='MyCocoVideoDataset',
        ann_file='/home/tianxianhao/Project/dataset/virat250/COCO_v_val.json',
        img_prefix=None,
        pipeline=[
            dict(type='LoadImagesWithRefImgFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(320, 180),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='VideoNormalize',
                        mean=[0.423, 2.051, 3.02],
                        std=[3.3, 9.462, 11.638],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='MyCocoVideoDataset',
        ann_file='/home/tianxianhao/Project/dataset/virat250/COCO_v_test.json',
        img_prefix=None,
        pipeline=[
            dict(type='LoadImagesWithRefImgFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(320, 180),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='VideoNormalize',
                        mean=[0.423, 2.051, 3.02],
                        std=[3.3, 9.462, 11.638],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=1, metric='bbox')
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[5, 7])
runner = dict(type='EpochBasedRunner', max_epochs=8)
checkpoint_config = dict(interval=1)
log_config = dict(
    interval=500,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
seed = 1
work_dir = '../../work_dirs/nolo/faster_rcnn/frozen/'
gpu_ids = range(0, 4)

Use load_from_torchvision loader
Use load_from_torchvision loader
2021-03-08 20:47:38,305 - mmdet - INFO - load model from: torchvision://resnet50
Use load_from_torchvision loader
Use load_from_torchvision loader
2021-03-08 20:47:38,981 - mmdet - INFO - These parameters in the 2d checkpoint are not loaded: {'fc.weight', 'fc.bias'}
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Done (t=5.08s)
creating index...
Done (t=4.91s)
creating index...
Done (t=4.98s)
creating index...
Done (t=5.39s)
creating index...
index created!
index created!
index created!
index created!
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Done (t=0.54s)
creating index...
Done (t=0.57s)
creating index...
Done (t=0.56s)
creating index...
Done (t=0.63s)
creating index...
index created!
index created!
index created!
index created!
2021-03-08 20:47:51,757 - mmdet - INFO - Start running, host: tianxianhao@ubuntu, work_dir: /home/tianxianhao/Project/mmdet/mmdet2.8/mmdetection/work_dirs/nolo/faster_rcnn/frozen
2021-03-08 20:47:51,757 - mmdet - INFO - workflow: [('train', 1)], max: 8 epochs
Traceback (most recent call last):
  File "../../tools/train.py", line 187, in <module>
    main()
  File "../../tools/train.py", line 183, in main
    meta=meta)
  File "/home/tianxianhao/Project/mmdet/mmdet2.8/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    not in TORCH_VERSION) and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "../../tools/train.py", line 187, in <module>
    main()
  File "../../tools/train.py", line 183, in main
    meta=meta)
  File "/home/tianxianhao/Project/mmdet/mmdet2.8/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    not in TORCH_VERSION) and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "../../tools/train.py", line 187, in <module>
    main()
  File "../../tools/train.py", line 183, in main
    meta=meta)
  File "/home/tianxianhao/Project/mmdet/mmdet2.8/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    not in TORCH_VERSION) and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "../../tools/train.py", line 187, in <module>
    main()
  File "../../tools/train.py", line 183, in main
    meta=meta)
  File "/home/tianxianhao/Project/mmdet/mmdet2.8/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    not in TORCH_VERSION) and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/tianxianhao/anaconda3/envs/mmdet2.8/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/tianxianhao/anaconda3/envs/mmdet2.8/bin/python', '-u', '../../tools/train.py', '--local_rank=3', 'nolo_faster_rcnn_r50_fpn_1x_virat_frozen.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by hhaAndroid** [comment]
Hi, @tianxianhao Maybe you can try setting find_unused_parameters=True in the config. It will affect the following code in mmdet/apis/train.py：
![image](https://user-images.githubusercontent.com/17425982/110400905-78da3600-80b3-11eb-94f8-6b2dfa1383ea.png)

**Comment by tianxianhao** [comment]
> Hi, @tianxianhao Maybe you can try setting find_unused_parameters=True in the config. It will affect the following code in mmdet/apis/train.py：
> ![image](https://user-images.githubusercontent.com/17425982/110400905-78da3600-80b3-11eb-94f8-6b2dfa1383ea.png)

Could you help me explain the reason why the bug appear when I set frezen_stages=1. How it affect the process? There is no problem in original config. Thanks.

**Comment by tianxianhao** [comment]
You solution works. Thanks a lot. But i am confused of this setting.
