### ISSUE TITLE
eval coco with voc metrics

### ISSUE THREAD

**Issue by CuongNN218** [open-mmlab/mmdetection#4733]
As in title, Can I evaluate a dataset have coco style with voc metrics?

**Comment by hhaAndroid** [comment]
Hi @CuongNN218

1. You can convert the coco format to VOC, and then use VOC metrics
2. You manually call the `eval_map` function. Maybe you can refer to [analyze_results](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/analyze_results.py)

**Comment by CuongNN218** [comment]
@hhaAndroid I want to evaluate when training with voc metrics? whích part of code should I modified

**Comment by hhaAndroid** [comment]
> @hhaAndroid I want to evaluate when training with voc metrics? whích part of code should I modified

There will be more code changes, so you'd better rewrite the coco evaluate method and you manually call the eval_map function.
