### ISSUE TITLE
TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by jshilong** [open-mmlab/mmdetection#4737]
This error only appeared in   **Pytorch 1.8**

When test a model with DDP，for example ATSS 
```
Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 197, in main
    args.gpu_collect)
  File "/home/SENSETIME/zhangshilong/Desktop/openmmlab_prs/debug_ddp/mmdetection/mmdet/apis/test.py", line 98, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/SENSETIME/zhangshilong/Desktop/openmmlab_prs/debug_ddp/mmdetection/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/SENSETIME/zhangshilong/Desktop/openmmlab_prs/debug_ddp/mmdetection/torch/nn/parallel/distributed.py", line 706, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/SENSETIME/zhangshilong/Desktop/openmmlab_prs/debug_ddp/mmdetection/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/SENSETIME/zhangshilong/Desktop/openmmlab_prs/debug_ddp/mmdetection/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/SENSETIME/zhangshilong/Desktop/openmmlab_prs/debug_ddp/mmdetection/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/SENSETIME/zhangshilong/Desktop/openmmlab_prs/debug_ddp/mmdetection/mmdet/models/detectors/base.py", line 150, in forward_test
    img_meta[img_id]['batch_input_shape'] = tuple(img.size()[-2:])
TypeError: 'DataContainer' object is not subscriptable
```

**Comment by zhaogev5** [comment]
I have the same question plz tell how to solve it

**Comment by Wolfwjs** [comment]
I have the same question too, what i should do to solve it ?

**Comment by shiyongde** [comment]
same problem !!

**Comment by RShevcheCape** [comment]
same issue here. What is the solution?

**Comment by jshilong** [comment]
@shiyongde @RShevcheCape  https://github.com/open-mmlab/mmcv/pull/882 have fixed it please update your mmcv at least after that commit.

**Comment by RShevcheCape** [comment]
Thanks @jshilong , however I have a clean installation of the latest release `1.7.0` from yesterday:
`root@0ed046e27087:/workspaces/pj_rosty_mmdetection# pip show mmcv-full
Name: mmcv-full
Version: 1.7.0
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Contributors
Author-email: openmmlab@gmail.com
License: 
Location: /opt/conda/lib/python3.8/site-packages
Requires: addict, numpy, yapf, Pillow, pyyaml, opencv-python, packaging
Required-by:`

**Comment by AdorableJiang** [comment]
Same here. I installed `MMCV: 1.5.3` by compiling from source.

```bash
2022-11-12 00:55:49,170 - mmdet - INFO - Environment info:
------------------------------------------------------------                                                                                                                                                                                                                  sys.platform: linux
Python: 3.9.13 (main, Oct 13 2022, 21:15:33) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: ${my_home}/miniconda3/envs/mmdet
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1
PyTorch compiling details: PyTorch built with:
- GCC 9.3
- C++ Version: 201402
- Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
- OpenMP 201511 (a.k.a. OpenMP 4.5)
- LAPACK is enabled (usually provided by MKL)
- NNPACK is enabled
- CPU capability usage: AVX2
- CUDA Runtime 11.6
- NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
- CuDNN 8.3.2  (built against CUDA 11.5)
- Magma 2.6.1
- Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
- TorchVision: 0.13.1
- OpenCV: 4.6.0
- MMCV: 1.5.3
- MMCV Compiler: GCC 9.4
- MMCV CUDA Compiler: 11.6
- MMDetection: 2.25.3+6e99234
------------------------------------------------------------
```

**Comment by 2474137474** [comment]
> Same here. I installed `MMCV: 1.5.3` by compiling from source. The error occurs in the evaluation stage.
> 
> ```shell
> 2022-11-12 00:55:49,170 - mmdet - INFO - Environment info:
> ------------------------------------------------------------                                                                                                                                                                                                                  sys.platform: linux
> Python: 3.9.13 (main, Oct 13 2022, 21:15:33) [GCC 11.2.0]
> CUDA available: True
> GPU 0,1: NVIDIA GeForce RTX 3090
> CUDA_HOME: ${my_home}/miniconda3/envs/mmdet
> NVCC: Cuda compilation tools, release 11.6, V11.6.124
> GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> PyTorch: 1.12.1
> PyTorch compiling details: PyTorch built with:
> - GCC 9.3
> - C++ Version: 201402
> - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
> - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
> - OpenMP 201511 (a.k.a. OpenMP 4.5)
> - LAPACK is enabled (usually provided by MKL)
> - NNPACK is enabled
> - CPU capability usage: AVX2
> - CUDA Runtime 11.6
> - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
> - CuDNN 8.3.2  (built against CUDA 11.5)
> - Magma 2.6.1
> - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,
> - TorchVision: 0.13.1
> - OpenCV: 4.6.0
> - MMCV: 1.5.3
> - MMCV Compiler: GCC 9.4
> - MMCV CUDA Compiler: 11.6
> - MMDetection: 2.25.3+6e99234
> ------------------------------------------------------------
> ```

Have you solved it yet? Same question occurs in the evaluation stage
