### ISSUE TITLE
How do I change the coco iou thr in tools/test.py?

### ISSUE THREAD

**Issue by ingbeeedd** [open-mmlab/mmdetection#4740]
Hello, I train with a custom dataset and run test.py.
```bash
python test.py ... --eval mAP
```
This is the existing coco test standard, so the results are very strict. Which part should I modify to control this? Thank you

**Comment by hhaAndroid** [comment]
you can setting `evaluation = dict(...,iou_thrs=[...])` in config file. Example  `evaluation = dict(iou_thrs=[0.8])`  or  `evaluation = dict(iou_thrs=[0.5, 0.8])`

**Comment by ingbeeedd** [comment]
Is the default 0.5? Which file should I refer to?
I wonder if the mAP test is based on the base coco test that (0.5:0.95:0.05).

**Comment by hhaAndroid** [comment]
> Is the default 0.5? Which file should I refer to?
> I wonder if the mAP test is based on the base coco test that (0.5:0.95:0.05).

default is 0.5:0.95, you can refer to [coco.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L408).
