### ISSUE TITLE
why two GPUs  memory allocate differently?

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection#4743]
Hello, sir. I use cascade rcnn to train my dataset and use dist_train.sh with two gpu, but I found that the memory used in two gpus is different, 
![image](https://user-images.githubusercontent.com/40256410/110565617-b8735180-8189-11eb-861f-3327b5d0955f.png)
how can I solve this? Very appreciate for your reply!!!

**Comment by ZwwWayne** [comment]
Different GPU contains different images during training, and those images have different sizes. So this is normal.

**Comment by yustaub** [comment]
thanks for your reply!!
