### ISSUE TITLE
mAP0.5 per class and different colors for different class box

### ISSUE THREAD

**Issue by feiyuhuahuo** [open-mmlab/mmdetection#4744]
**Motivation**
A clear and concise description of the motivation of the feature.
Ex1.When testing with `--options "classwise=True"`, it can only show mAP0.5-0.95, it's better to show mAP0.5 per class either. In industry environment, mAP0.5 is enough to measure a model.
Ex2. It's better to use different color for different class box when visualizing detection result. And currently, the text maybe two large for small objects. It's better to adjust the font scale automatically according to the object scale.

The small objects are covered.
![图片](https://user-images.githubusercontent.com/32631344/110587561-d1dac480-81ae-11eb-8643-05089c911394.png)

**Comment by ZwwWayne** [comment]
Hi @feiyuhuahuo ,
Thanks for your kind suggestion. The suggestion 2 is implemented through https://github.com/open-mmlab/mmdetection/pull/8988. Feel free to try in MMDet 3.x.
For suggestion 1, you can set the iou_threshoulds to 0.5 through the config.
