### ISSUE TITLE
Does image normalization consist with pretrained model on ImageNet?

### ISSUE THREAD

**Issue by Solomon1588** [open-mmlab/mmdetection#475]
I download resnext101 backbone with hyperlink from mmcv. And I find that the image normalization in cascade rcnn config is as follow:
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
I wonder whether  the mean and std  is consistent with the values for training pretrained model on ImageNet?

**Comment by OceanPang** [comment]
@Solomon1588 Yes. Please refer to [imnormalize](https://github.com/open-mmlab/mmdetection/blob/e421e832883241bd7831bf77dc31d5fb31d7da58/mmdet/datasets/transforms.py#L37)
