### ISSUE TITLE
Docstring of SingleRoIExtractor is wrong in single_level_roi_extractor.py

### ISSUE THREAD

**Issue by SeongjaeHong** [open-mmlab/mmdetection#4753]
https://github.com/open-mmlab/mmdetection/blob/dbc6b67446d3898461d0a5d5cef7d112e710db0a/mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py#L9-L20

On L19, I think the type of featmap_strides should be list.

Because on L27 of BaseRoIExtractor, they get length of featmap_strides
https://github.com/open-mmlab/mmdetection/blob/dbc6b67446d3898461d0a5d5cef7d112e710db0a/mmdet/models/roi_heads/roi_extractors/base_roi_extractor.py#L25-L27

And we can see that on L43 in configure file also. It define featmap_strides as a list.
https://github.com/open-mmlab/mmdetection/blob/dbc6b67446d3898461d0a5d5cef7d112e710db0a/configs/_base_/models/cascade_rcnn_r50_fpn.py#L35-L43

**Comment by jshilong** [comment]
Thanks
Would you mind giving a PR to fix it?
