### ISSUE TITLE
Having multiple validation sets

### ISSUE THREAD

**Issue by koriavinash1** [open-mmlab/mmdetection#4757]
Is it possible to define two validation sets (val1, val2), and perform validation on val1 every epoch and on val2 every 10th epoch?

**Comment by jshilong** [comment]
You can refer to the `separate_val` in `ConcateDataset` 
https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html#concatenate-dataset

**Comment by jshilong** [comment]
Feel free to reopen it if there is any question.
