### ISSUE TITLE
TypeError: build_model_from_cfg() got an unexpected keyword argument 'cfg_options'

### ISSUE THREAD

**Issue by Wulingtian** [open-mmlab/mmdetection#4759]
python pytorch2onnx.py  config  model.pth
运行如上命令，报了如下错误：

Traceback (most recent call last):
  File "pytorch2onnx.py", line 231, in <module>
    pytorch2onnx(
  File "pytorch2onnx.py", line 36, in pytorch2onnx
    orig_model = build_model_from_cfg(
TypeError: build_model_from_cfg() got an unexpected keyword argument 'cfg_options'

**Comment by RunningLeon** [comment]
@Wulingtian Please try with the latest mmdet.
