### ISSUE TITLE
The problem of the third stage

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#476]
Hi ,Great work ! When I want to reincomplement the HTC codes. I went to the third stage. And I found something wrong. The Mth stage mask feature depends on the Mth bbox and the (M-1)th mask feature，right? Also the (M-1)th mask feature depends on the (M-1)th bbox , right? But the batchsize of (M-1)th bbox is different from the batchsize of Mth bbox? So how can you add these two items by means of element-wise?  Could you tell me ?Thanks a lot!

**Comment by hellock** [comment]
#478
