### ISSUE TITLE
Could you support the *Mixup* & *Duck_inject* in tran?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#4761]
*Mixup* & *Duck_inject*

**Motivation**
Enhance the recognition of rare small targets

**Related resources**
Duck_inject：https://github.com/chuliuT/Tianchi_Fabric_defects_detection/blob/master/final_commit/Duck_inject2.0.py

Thank you

**Comment by ZwwWayne** [comment]
Thanks for your suggestion. For now, we have limited resources and may not have effort for that. PRs are welcomed.
