### ISSUE TITLE
Cannot use dist_train.sh for multiple GPUs

### ISSUE THREAD

**Issue by MeatballCat** [open-mmlab/mmdetection#4762]
When I want to use multiple GPUs for training, the .sh file is always unresponsive, as shown in the figure below

![1615643902(1)](https://user-images.githubusercontent.com/58537183/111032448-42037780-8447-11eb-83bf-8e5e574a5004.jpg)

The following is my instruction：
bash ./tools/dist_train.sh "/data_nvme1t/tianchi/mmdetection/configs/cascade_rcnn/cascade_rcnn_r101_fpn_1x_coco.py" 4 --work-dir "/data_nvme1t/tianchi/mmdetection/result/"

Can someone tell me why？Thank you.

**Comment by ZwwWayne** [comment]
Cannot find python. This is a problem in your environment and has nothing to do with mmdet.

**Comment by MeatballCat** [comment]
> Cannot find python. This is a problem in your environment and has nothing to do with mmdet.

But I activated the Python environment, do I need to change the configuration of the .sh file?Thank you.
