### ISSUE TITLE
i get a message on running a file as

### ISSUE THREAD

**Issue by medgitt** [open-mmlab/mmdetection#4766]
i get a message on running a file as 
"Backend TkAgg is interactive backend. Turning interactive mode on" in pycharm.

what could be the issue

_Originally posted by @medgitt in https://github.com/open-mmlab/mmdetection/issues/4365#issuecomment-798903700_

**Comment by jshilong** [comment]
Please give more details.

**Comment by ZwwWayne** [comment]
This is not related to mmdetection. You may google/baidu it to solve the issue of pycharm.
