### ISSUE TITLE
urgent problem

### ISSUE THREAD

**Issue by yzk-lab** [open-mmlab/mmdetection#4767]
hi,i have a prolem with the loss. in the smooth-L1 loss function ,the parameter are the pred and target,which represent the predict offset(x,y,w,h) ,it seems that they have no relation with IOU.so  if i want to use IOU loss,i must to know the IOU between the anchor and gt_bbox ,but the parameter in loss function are not the anchor and gt_bbox,so how should i do to utilize the IOU?hope for your reply.thanks!

**Comment by jshilong** [comment]
There is an `iou loss` in mmdet. 
You can refer to [mmdet.models.losses.BoundedIoULoss][https://mmdetection.readthedocs.io/en/latest/api.html?highlight=iouloss#mmdet.models.losses.BoundedIoULoss.forward]

**Comment by jshilong** [comment]
Feel free to reopen it if there is any question.
