### ISSUE TITLE
How to use mmdetection to predict.

### ISSUE THREAD

**Issue by yc0619** [open-mmlab/mmdetection#4768]
Hi,

i have trained mask rcnn. And i want the trained model to label the data for me.

Does someone knows how can i run the test with just loading the picture without label in? And no evaluation will be processed in test.

thx!

**Comment by yc0619** [comment]
我还对一个地方有疑问，如何把mmdetection的test跑出来的result直接存到coco格式下的json文件里？而不是只有一个pkl文件。谢谢。

**Comment by jshilong** [comment]
An example:
```
./tools/dist_test.sh \
    configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py \
    checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth \
    8 \
    -format-only \
    --options "jsonfile_prefix=./mask_rcnn_test-dev_results"
```
 -format-only maybe what you want.

**Comment by jshilong** [comment]
Feel free to reopen it if there is any question.

**Comment by yc0619** [comment]
Hi,

Sorry for asking help again.

i have tried your command, it can run without an error. And the results are also perfectly saved in the root directory of mmdetection. But in these 2 json files, there is just "[]", ok nothing. I think i might have done something wrong. So i have written down my workflow and what i want to achieve below.

What i made:
1. label the predict file (if not labeled, no ann.json, comes an error, so i have just labeled one GT on the pic)
2. convert it to coco format
3. run the cmd you've mentioned before
4. the saved result is empty

I would like to ask, if i can use test.py to predict the no labeled images. And how can i do it?

what i want to do is:
1. predict with not labeled pic
2. get segm as results
3. convert the saved segm result to coco format
4. convert coco format to labelme format, so that i can fix the wrong predicted label

Thanks for your help again!
