### ISSUE TITLE
Predicting on Windows platforms

### ISSUE THREAD

**Issue by Chqbelief** [open-mmlab/mmdetection#4772]
I want to predicting on Windows platforms use mask-rcnn model, but I find many problems, such as encoding of mmcv, torch version ,mmcv-full version. I don't know what should I do ?

**Comment by yc0619** [comment]
hey, wanna ask, how could you install mmcv on windows? do you have a tutorial? thx.

**Comment by jshilong** [comment]
Windows is in experimental support.

**Comment by cl886699** [comment]
> hey, wanna ask, how could you install mmcv on windows? do you have a tutorial? thx.

you can follow this tutorial
https://mmcv.readthedocs.io/en/latest/build.html

**Comment by Chqbelief** [comment]
> Windows is in experimental support.
I have successfully predicted on Windows, using the CPU, not training.
In fact, you only need to change the relevant encoding of MMCV,and needs to pip install mmcv-full,torch and so on ,
version needs to correspond

**Comment by Chqbelief** [comment]
> hey, wanna ask, how could you install mmcv on windows? do you have a tutorial? thx.

Download the source code installation

**Comment by Chqbelief** [comment]
> Windows is in experimental support.

I have successfully predicted on Windows, using the CPU, not training.
In fact, you only need to change the relevant encoding of MMCV,and needs to pip install mmcv-full,torch and so on ,
version needs to correspond

**Comment by yc0619** [comment]
> > Windows is in experimental support.
> 
> I have successfully predicted on Windows, using the CPU, not training.
> In fact, you only need to change the relevant encoding of MMCV,and needs to pip install mmcv-full,torch and so on ,
> version needs to correspond

Hi, which network are you using for prediction. Last days i have also raised an issue about prediction with mask rcnn (#4773). But officially is the prediction not supported now. I would really appreciate that, if you could tell me how you made it. :)
Thx!
