### ISSUE TITLE
Do you have the plan to update the version to 3.0?

### ISSUE THREAD

**Issue by icedream2** [open-mmlab/mmdetection#4775]
I am a user of mmdetection 1.2.0 and have developed some works based on it. I'd like to adopt the new features of version 2.x, but the version update is quickly. It means frequent modification shoulded be conducted. So I want to know when will the mmdetection 3.x be published, and then I can directly transfer my current works into the newest version and reduce the cost of migration.

**Comment by hhaAndroid** [comment]
Thank you for your attention. We have no plans to release 3.x for now, so you can develop it in version 2.x. Looking forward to your contribution.
