### ISSUE TITLE
Bad prediction results with converted .onnx model 

### ISSUE THREAD

**Issue by mdatres** [open-mmlab/mmdetection#4777]
[onnx_inference.txt](https://github.com/open-mmlab/mmdetection/files/6148235/onnx_inference.txt)

Dear all, 
I have trained retinanet_r50_fpn_2x_coco.py on my costum dataset in COCO format. The model works good using: 

> model = init_detector(config_file, checkpoint_file, device=device)
> result = inference_detector(model, img)

So I have decided to export the model in the .onnx format running the following command:
 

> python tools/deployment/pytorch2onnx.py configs/retinanet/retinanet_r50_fpn_2x_coco.py /data0/work_dirs/retinanet_mmdet_120321/epoch_50.pth --output-file /home/datres/Catchme/mmdetection/ONNX_models/retinanet/retinanet2x.onnx  --input-img /data0/Catchme/dataset/12_03_2021/images/20201221_rosina_federico_isera_16_7__3_.jpg --shape 3456 4608 --test-img /data0/Catchme/dataset/12_03_2021/images/20201212_catchme-pietram__4_.jpg --verify

This command produces an output. I have loaded the produced output in an onnx runtime and I have run inference using the code available in the .txt file in attached. Unfortunately, the predictions this time are really bad, but I can't understand why. I just want to remark that the pictures used for onnx inference are different to those used in pytorch2onnx.py command. Can you help me? Thanks in advance, 

Best regards, 
mdatres

**Comment by hhaAndroid** [comment]
Hi, You lost the to_rgb operation, you can refer to mmcv.imnormalize

**Comment by mdatres** [comment]
thanks for the quick answer. My images are RGB and I have just checked that in the config file there is to_rgb=True:

> img_norm_cfg = dict(

    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

Maybe I didn't get what you meant. Thank you in advance, 

Best regards, 
mdatres

**Comment by hhaAndroid** [comment]
The image inputted in your txt is in bgr format, but it actually needs to be in rgb.

**Comment by mdatres** [comment]
Thanks for the answer. I have converted the image to RGB, but the prediction are still not good. This is my new onnx_inference file. It does not predict the correct bounded boxes. In this dropbox folder there is my converted .onnx model: 
https://www.dropbox.com/s/mixq0k3xjiat17r/retinanet1.onnx?dl=0
I attach also the image that I have used for the test: 
![20201205_catchme-ischiaisera-dx2](https://user-images.githubusercontent.com/80750571/111308770-646dde80-865b-11eb-8fd4-683e15f520da.jpg)
if you need also the config file let me know. It should predict the yellow insect in the middle. 
Thanks in advanced, 
[onnx_inference.txt](https://github.com/open-mmlab/mmdetection/files/6148838/onnx_inference.txt)

**Comment by mdatres** [comment]
I solved my problem. The mistake was in the way I used to preprocess the image. 
Thanks a lot, 

Best regards, 
mdatres
