### ISSUE TITLE
The model zoo of RetinaNet doesn't work.

### ISSUE THREAD

**Issue by hero-y** [open-mmlab/mmdetection#4780]
The model zoo of RetinaNet doesn't work, where can we find the checkpoints?

**Comment by hhaAndroid** [comment]
Which checkpoints, can you post the URL?

**Comment by hero-y** [comment]
RetinaNet:
1. http://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_fpn_1x_coco/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth
2. http://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r101_fpn_1x_coco/retinanet_r101_fpn_1x_coco_20200130-7a93545f.pth
Faster RCNN:
1.
http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
2.
http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r101_fpn_1x_coco/faster_rcnn_r101_fpn_1x_coco_20200130-f513f705.pth

**Comment by hhaAndroid** [comment]
Hi, I have tried it and the link is valid. You may need to check the network.
