### ISSUE TITLE
Save interferance data

### ISSUE THREAD

**Issue by FredrikG94** [open-mmlab/mmdetection#4786]
Hi, I want to take my inference data and save it to a file. Is this possible and how? 
I want to save the label, bbox, and score of each object detected in a picture.
Thanks!

**Comment by ZwwWayne** [comment]
You can convert your data to the COCO format (tutorial is [here](https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html#prepare-the-customized-dataset)), and then use `jsonfile_prefix` or `--out` to save the prediction results, see [examples](https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#examples).
