### ISSUE TITLE
There was an error when I was executing the demo code

### ISSUE THREAD

**Issue by Healer-EugeneLi** [open-mmlab/mmdetection#4788]
MyMMdet/mmdet/datasets/utils.py:68: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
  
  How i can solve it?

**Comment by hhaAndroid** [comment]
Hi, This is just a warning, it doesn't matter.

**Comment by shilinlun** [comment]
do you solve it?,i also get the question,and it quit directively and not give me the result

**Comment by shilinlun** [comment]
i knowed it

**Comment by TimGor1997** [comment]
> i knowed it

could you tell me how to solve it？

**Comment by shilinlun** [comment]
> > 我知道
> 
> 你能告诉我如何解决吗？

我的在vscode上面运行不会显示图片，你加一个show_result_pyplot这个函数，就会显示检测结果
