### ISSUE TITLE
UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.

### ISSUE THREAD

**Issue by shilinlun** [open-mmlab/mmdetection#4790]
when i use the demo.py

from mmdet.apis import init_detector, inference_detector

config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
# url: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
device = 'cuda:0'
# init a detector
model = init_detector(config_file, checkpoint_file, device=device)
# inference the demo image
inference_detector(model, 'demo/demo.jpg')

i get the follow warning:
UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.

and it quit and not show any calculate result 

how can i solve it 

thanks

**Comment by hhaAndroid** [comment]
Hi, This is just a warning, it doesn't matter.

**Comment by WHW-S** [comment]
i also met this problem,but it was abort automatically with tips---(Segment error, core has been dumped)

**Comment by WHW-S** [comment]
could you tell me how you deal with it,thanks

**Comment by YuYue26** [comment]
have you get over this problem, I meet the same!!!

**Comment by cena001plus** [comment]
> Hi, This is just a warning, it doesn't matter.

same question ,it's indeed  warning  ,but no inference result .

**Comment by Alan-D-Chen** [comment]
sad. I just get the same problem. What can I do for this?Please~.

**Comment by Tianyu100** [comment]
I also experience this issue, in a hurry, can you help me？

**Comment by monkeycc** [comment]
`model.show_result(img, result)`
replace
`model.show_result(img, result, score_thr=0.2, show=True)`

**Comment by monkeycc** [comment]
`model.show_result(img, result)`
replace
`model.show_result(img, result, score_thr=0.2, show=True)`

**Comment by wzgliang** [comment]
> `model.show_result(img, result)` # jupyter ！！！！ replace `model.show_result(img, result, score_thr=0.2, show=True)`

which file need？
