### ISSUE TITLE
Qusetions about learning rate

### ISSUE THREAD

**Issue by Hwang64** [open-mmlab/mmdetection#4791]
In current configuration, each gpu runs two images. If four images are deployed on each gpu, how to adjust the learning rate?
For example:
1). Four gpus and each gpu runs two images;
2). Two gpus and each gpu runs four images.
Do these two configurations have the same learning rate?

**Comment by ZwwWayne** [comment]
Yes they are same as the overall batch size is 8.
The learning rate if for batch size=16 for the total number of images in all the GPUS. If the overall batch size is modified, you should follow the linear scale rules. For example, if the batch size =32, the LR should be scaled by 2.

**Comment by clw5180** [comment]
> Yes they are same as the overall batch size is 8. The learning rate if for batch size=16 for the total number of images in all the GPUS. If the overall batch size is modified, you should follow the linear scale rules. For example, if the batch size =32, the LR should be scaled by 2.

请问如果是在自己的小数据集上finetune的话，lr是否需要设置的更小
