### ISSUE TITLE
How to add more branches/losses to AnchorHead ?

### ISSUE THREAD

**Issue by yossibiton** [open-mmlab/mmdetection#4794]
I would like to consult with you guys about extending AnchorHead class to support more branches/losses.
For face detection task it's common to add more branches other than the classification & regression :
1. Tinaface - they add IOU estimation branch (with new relevant loss). Their [implementation](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface) is actually based on mmdetection.
I didn't like their implementation because it's not general enough and actually assumes that every model has this IOU estimation branch
2. Retinaface - they add landmarks detection branch (with new relevant loss)

Two approaches i consider :
1. Implement a new class inheriting from AnchorHead, but I'm worried it would result in a lot of duplicated code.
2. Implement a new class, which holds AnchorHead as a member and only add the new logic on top of it.

What do you think about these suggestions? Am I missing something?
Is there a relevant example I can look at?

**Comment by hhaAndroid** [comment]
Based on the current algorithm implementation, I suggest option 1. Maybe you can refer to [ATSS implement](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/atss_head.py)
