### ISSUE TITLE
logging when run multiple GPUs

### ISSUE THREAD

**Issue by ChuanyangZheng** [open-mmlab/mmdetection#4797]
Hi, I am testing logging when running tools/train.py on one machine with 2 GPUs. 
```python
   logger = get_root_logger(log_file=log_file, log_level=cfg.log_level)
   logger.error('test: {}'.format(args.local_rank))            #add by myself
```
In the terminal, it outputs:
```shell
2021-03-19 14:46:15,725 - mmdet -  ERROR - test: 1
2021-03-19 14:46:15,726 - mmdet -  ERROR - test: 0
```
However, in the log file, I only find:
```file
2021-03-19 14:46:15,726 - mmdet -  ERROR - test: 0
```
How can I log information from multiple process into one single log file?

**Comment by ZwwWayne** [comment]
This is because the current logger only supports logging information of rank 0. If you want to log all the ranks, you may need to update your logger.

**Comment by ChuanyangZheng** [comment]
Thank you for your reply. 
I have changed the logger.py in mmcv as following:
```
# if rank == 0 and log_file is not None:
# Here, the default behaviour of the official logger is 'a'. Thus, we
# provide an interface to change the file mode to the default
# behaviour.
# file_handler = logging.FileHandler(log_file, file_mode)
# handlers.append(file_handler)
file_handler = logging.FileHandler(log_file, file_mode)
handlers.append(file_handler)
```
      I remove the rank 0 condition because I want to logging information from all processes into one single log_file. The result is in my question. It seems that the log file is bound into rank 0 and can not be changed by other processes. 
And I have tested creating log_file for every process, that workes. But how can I log all data into one single log file?
