### ISSUE TITLE
undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

### ISSUE THREAD

**Issue by softmicro929** [open-mmlab/mmdetection#48]
I need your help  : )
ImportError: /home/wangshuainan/mmdetection/mmdet/ops/roi_align/roi_align_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

**Comment by hellock** [comment]
It is possible that the compiling environment and runtime environment are not the same. You can have a check.

**Comment by hcx1231** [comment]
i also have this problem

**Comment by qpanpony** [comment]
@softmicro929 
Would you please give more details on how to check the compiling environment and runtime environment? I met the same issue when running tools/test.py in a pytorch conda env. Thanks!

**Comment by aimhabo** [comment]
@mynameiziji it works for me

**Comment by qpanpony** [comment]
@mynameiziji 
I wiped the slate clean and it works, though still be puzzled. Thank you!

**Comment by ximitiejiang** [comment]
sorry to re-open the thread. 
what is the script @mynameiziji ? is that mentioned on bottom of INSTALL.md?
i can not open that address(https://gist.github.com/hellock/bf23cd7348c727d69d48682cb6909047)
anybody can suggest what content for the script. I met similar import issue when run the test.py.

from mmdet.models import build_detector
Traceback (most recent call last):

  File "<ipython-input-15-a53ade34e156>", line 1, in <module>
    from mmdet.models import build_detector

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/models/__init__.py", line 1, in <module>
    from .detectors import (BaseDetector, TwoStageDetector, RPN, FastRCNN,

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/models/detectors/__init__.py", line 1, in <module>
    from .base import BaseDetector

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/models/detectors/base.py", line 9, in <module>
    from mmdet.core import tensor2imgs, get_classes

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/ops/__init__.py", line 1, in <module>
    from .nms import nms, soft_nms

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/ops/nms/nms_wrapper.py", line 4, in <module>
    from .gpu_nms import gpu_nms

ImportError: /home/ubuntu/anaconda3/lib/python3.7/site-packages/mmdet-0.5.4+cd35200-py3.7.egg/mmdet/ops/nms/gpu_nms.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

thank you!

**Comment by mynameiziji** [comment]
@ximitiejiang 
it's the script:

conda create -n open-mmlab python=3.6 -y
source activate open-mmlab

conda install -c pytorch pytorch torchvision -y
conda install cython -y
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
./compile.sh
pip install .  # "pip install -e ." for develop mode

mkdir data
ln -s $COCO_ROOT data

**Comment by ximitiejiang** [comment]
@mynameiziji
 @open-mmlab/mmdetection


thank you for the reply!
i have solved the issue.



At 2018-12-20 14:21:35, "mynameiziji" <notifications@github.com> wrote:


@ximitiejiang
it's the script:

conda create -n open-mmlab python=3.6 -y
source activate open-mmlab

conda install -c pytorch pytorch torchvision -y
conda install cython -y
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
./compile.sh
pip install . # "pip install -e ." for develop mode

mkdir data
ln -s $COCO_ROOT data

**Comment by earhian** [comment]
**pytorch 1.0 works for me.**

**Comment by HearyShen** [comment]
I encountered this issue and tried quite a few times. 
I find everything is fine when installing without `cudatoolkit`, but if I use the PyTorch official conda install command(with `cudatoolkit=*.0`), this issue just happens again and again.
So, I think it has nothing to do with 3-rd party mirrors like tsinghua, I doubt it is the `cudatoolkit` installed by conda causing the problem.

Wish to be helpful!

**Comment by lawpdas** [comment]
We should install pytorch from official source.
`conda install -c pytorch pytorch torchvision -y`

**Comment by andeyeluguo** [comment]
> @mynameiziji @open-mmlab/mmdetection thank you for the reply! i have solved the issue. At 2018-12-20 14:21:35, "mynameiziji" <notifications@github.com> wrote: @ximitiejiang it's the script: conda create -n open-mmlab python=3.6 -y source activate open-mmlab conda install -c pytorch pytorch torchvision -y conda install cython -y git clone https://github.com/open-mmlab/mmdetection.git cd mmdetection ./compile.sh pip install . # "pip install -e ." for develop mode mkdir data ln -s $COCO_ROOT data — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
that works for me.  My cuda is 9.1 ,when I use cudatoolkit=9.0, it corrupped, but when I use conda install -c pytorch pytorch torchvision -y. It will install cudatoolkit=10.0, and it worked.

**Comment by joshua23333** [comment]
i can not install pytorch and torchvision from conda in Sep 16th, so it is there any other solutions for this problem?

**Comment by tricoffee** [comment]
couldn’t find any code matching 'compile.sh' in open-mmlab/mmdetection
@mynameiziji
