### ISSUE TITLE
pytorch2onnx，and Error occurred when I use .onnx Model with C++ API.

### ISSUE THREAD

**Issue by ChenCVer** [open-mmlab/mmdetection#4802]
情况大概是这样的，我用的pytorch1.7版本，onnxruntime 1.6.0，当yolov3.pth转onnx模型的时候，verify模式下载python接口是不会报错的，但是当我放在onnxruntime的C++接口下，就会报错，b报错信息是：
[E:onnxruntime:, sequential_executor.cc:281 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running If node. Name:'If_809' Status Message: Subgraph must have the shape set for all outputs but 1381 did not.
通过查找对应的python代码是在yolo_head.py如下部分:
  # Filtering out all predictions with conf < conf_thr,
  conf_thr = cfg.get('conf_thr', -1)
  if conf_thr > 0:
      # add as_tuple=False for compatibility in Pytorch 1.6
      # flatten would create a Reshape op with constant values,
      # and raise RuntimeError when doing inference in ONNX Runtime
      # with a different input image (#4221).
      conf_inds = conf_pred.ge(conf_thr).nonzero(as_tuple=False).squeeze(1)
      bbox_pred = bbox_pred[conf_inds, :]
      cls_pred = cls_pred[conf_inds, :]
      conf_pred = conf_pred[conf_inds]

上面代码中的：conf_inds = conf_pred.ge(conf_thr).nonzero(as_tuple=False).squeeze(1)引起。
恳请mmdet官方可否出个解决方案！谢谢！

**Comment by QingChuanWS** [comment]
At present, you can temporarily try to remove the parameter in the sqeeuze() function to avoid this problem. This error is a new problem in the pytorch 1.7 version.

**Comment by RunningLeon** [comment]
Please try with PyTorch==1.6.0 to see if this issue still happens.
