### ISSUE TITLE
smooth-l1 and iou loss different parameters

### ISSUE THREAD

**Issue by yzk-lab** [open-mmlab/mmdetection#4808]
hi,if i want to combine the iou loss and smooth-l1 loss in my loss ,but the input parameter of these two loss function are different.i can not touch the information about anchor and gt_box,so how can i get the iou?

**Comment by jshilong** [comment]
I can't get what u want to do.

**Comment by ZwwWayne** [comment]
See the example [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L245). You should use the box_coder to decode the box first for IoU loss.

**Comment by yzk-lab** [comment]
> I can't get what u want to do.

my fault.my expression exists problem.i want to konw if  i can use two type loss,such as smooth-l1 loss and iou loss,i set my loss 0.8*smooth-l1 loss and 0.2*iou loss. but their parameters are different.smotth-l1 loss utilize the offset as target ,while the iou loss use the absolute offset ,how can i balance them in a loss with different  weights?

**Comment by yzk-lab** [comment]
> See the example [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L245). You should use the box_coder to decode the box first for IoU loss.

i want to konw if i can use two type loss,such as smooth-l1 loss and iou loss,i set my loss 0.8 multiplys smooth-l1 loss and 0.2 multiply iou loss. but their function parameters are different.smotth-l1 loss utilize the offset as target ,while the iou loss use the absolute offset ,how can i balance them in a loss with different weights?

**Comment by jshilong** [comment]
> > See the example [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L245). You should use the box_coder to decode the box first for IoU loss.
> 
> i want to konw if i can use two type loss,such as smooth-l1 loss and iou loss,i set my loss 0.8 multiplys smooth-l1 loss and 0.2 multiply iou loss. but their function parameters are different.smotth-l1 loss utilize the offset as target ,while the iou loss use the absolute offset ,how can i balance them in a loss with different weights?

You may refer to DETR which use l1 loss and iou loss at the same time. You can find it in https://github.com/open-mmlab/mmdetection/blob/0d2b39b195031b3b7ede73ebaa0a04150d1f332b/mmdet/models/dense_heads/detr_head.py#L410

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
