### ISSUE TITLE
Problems when run the video_demo.py

### ISSUE THREAD

**Issue by DorothysDad** [open-mmlab/mmdetection#4809]
error:
**python demo/vide_demo.py demo-real/test2.mp4 configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/my_fasterrcnn/latest.pth --out demo-real/result2.mp4
段错误 (核心已转储)**

but it can works if i use the image_demo.py when use my_fasterrcnn/latest.pth
so how can i solve this problem in video_demo.py

**Comment by hhaAndroid** [comment]
Can you try
 `python demo/video_demo.py demo/demo.mp4 \
    configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    --out result.mp4` ?

This should be correct.

**Comment by DorothysDad** [comment]
> Can you try
> `python demo/video_demo.py demo/demo.mp4 \ configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \ checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \ --out result.mp4` ?
> 
> This should be correct.

i try your command and i reinstall the mmdetection and mmcv in order to keep them as newest version but i still can not run the video_demo.py
python demo/video_demo.py demo/demo.mp4 configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --out result.mp4
段错误 (核心已转储)

**Comment by hhaAndroid** [comment]
This type of error is more difficult for us to reproduce.

**Comment by DorothysDad** [comment]
> This type of error is more difficult for us to reproduce.

fine thanks~

**Comment by ZwwWayne** [comment]
This is usually related to incorrect environment. We are not able to help without detailed information. Please use `error template`.
