### ISSUE TITLE
Is there a way to load model without loading the config? 

### ISSUE THREAD

**Issue by rhiver** [open-mmlab/mmdetection#4811]
Too many dependencies on mmcv and mmdetection itself. 
It is really hard to get the most lightweight code for just inference.
I don't wanna keep such a big project for a simple inference.
Is there a way to do that?

**Comment by jshilong** [comment]
We have no related solution for the time being.

**Comment by ZwwWayne** [comment]
> Too many dependencies on mmcv and mmdetection itself.
> It is really hard to get the most lightweight code for just inference.
> I don't wanna keep such a big project for a simple inference.
> Is there a way to do that?

You can simply install MMDetection and MMCV in your environment, and keep the scripts for inference, like those in the [colab tutorial](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb).
