### ISSUE TITLE
Faster Rcnn Inconsistent model size

### ISSUE THREAD

**Issue by cygerts** [open-mmlab/mmdetection#4812]
Hi,
If I train my own Faster Rcnn on COCO or Cityscapes the checkpoint size is of around 330 MB.  However if I download pretrained models their size is only around 158 MB. This makes the models inconsistent with the configs. 

What is the cause of such incompatibility? Maybe there were some adjustment made to the backbone (reduce number of base channels), Faster Rcnn Heads (num features) or half precision was used, and are not currently reflected in the provided configs?

No modifications made to the original configs.
PyTorch 1.7.1, CUDA = 10.1, TorchVIsion = 0.8.2, MMCV = 1.2.6, Python=3.7.9, mmdetection = 2.9.0

**Comment by hhaAndroid** [comment]
Hi, This is because irrelevant content is deleted from the pre-trained model, such as config, optimizer parameters, etc.

**Comment by formorebeat** [comment]
Hi, you can load the model dict and find out the gap between them.
