### ISSUE TITLE
Request: highlight OpenMMLab on Interrogate's documentation

### ISSUE THREAD

**Issue by econchick** [open-mmlab/mmdetection#4814]
Hey there! - I really appreciate that many of the OpenMMLab repos use [interrogate](https://github.com/econchick/interrogate)! It's super flattering!

I'm wondering, may I mention that OpenMMLab uses interrogate on our [docs site](https://interrogate.readthedocs.io)? Something just as simple as a section of "Projects that use Interrogate" with the name and link under it. If you'd like, I can include the OpenMMLab logo, and/or even a quote from y'all about why it's used 😅

I totally understand if you'd prefer not to! I won't put anything up until I hear from you.

Thanks!

**Comment by ZwwWayne** [comment]
Hi @econchick ，
Glad to hear from you. Yes, you can mention that.
