### ISSUE TITLE
How to add copy-paste augmentation to train_pipeline?

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#4815]
Hello! I am currently doing object detection using MMDetection and VOC-format dataset. I want to implement a customized data pipeline by adding copy-paste (a data augmentation method) to existing train_pipeline in file voc0712.py, following instructions: https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html. Codes for copy-paste is here: https://github.com/conradry/copy-paste-aug. But this one seems to be for coco format. For now I have no idea how to implement it correctly.

**Comment by hhaAndroid** [comment]
In MMDetection, the dataset output format is `xyxy`, which is the same as the input required by the `copy-paste-aug` library. And you can use [scripts](https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py) to visualize the augmented data.

**Comment by hhaAndroid** [comment]
If you are interested, feel free to submit a PR！

**Comment by ZwwWayne** [comment]
You may have a look at [instaboost](https://github.com/GothicAi/Instaboost).

**Comment by dyabel** [comment]
> Hello! I am currently doing object detection using MMDetection and VOC-format dataset. I want to implement a customized data pipeline by adding copy-paste (a data augmentation method) to existing train_pipeline in file voc0712.py, following instructions: https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html. Codes for copy-paste is here: https://github.com/conradry/copy-paste-aug. But this one seems to be for coco format. For now I have no idea how to implement it correctly.

Hi, have you successfully implementing copy-paste in mmdetection? If so, can you provide the code or some advices? Thanks!
