### ISSUE TITLE
Why the YOLO-v5 not be released to the project?

### ISSUE THREAD

**Issue by formorebeat** [open-mmlab/mmdetection#4816]
The one stage detector YOLO v5 is now released by the author, why didn't you convert it to this project?
There is an official code https://github.com/ultralytics/yolov5

**Comment by hhaAndroid** [comment]
There may be copyright issues and the corresponding paper has not been published yet.

**Comment by formorebeat** [comment]
> There may be copyright issues and the corresponding paper has not been published yet.

OK～thx
