### ISSUE TITLE
there have 300 epoth.pth after train my data and   how i know the best.pth.  

### ISSUE THREAD

**Issue by Alex-afka** [open-mmlab/mmdetection#4819]

**Comment by hhaAndroid** [comment]
Hi, you can refer to #4677

**Comment by Alex-afka** [comment]
i set the save_best but it is wrong .i use mmdetection 2.6 .it has problem of the different version mmdection

**Comment by hhaAndroid** [comment]
> i set the save_best but it is wrong .i use mmdetection 2.6 .it has problem of the different version mmdection

Maybe you need to use the latest version.

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/5e246d5e3bc3310b5c625fb57bc03d2338ca39bc/docs/en/faq.md#training


It can be turned on by configuring evaluation = dict(save_best=‘auto’). In the case of the auto parameter, the first key in the returned evaluation result will be used as the basis for selecting the best model. You can also directly set the key in the evaluation result to manually set it, for example, evaluation = dict(save_best='mAP' ).
