### ISSUE TITLE
How to upgrade the MMDetection from v2.0 to v2.9

### ISSUE THREAD

**Issue by calvin886** [open-mmlab/mmdetection#4820]
Q1: Is the virtual environment of V2.0 compatible with the V2.9?
      Do I need to set up the virtual environment again if i upgrade it to V2.9?

Q2: Do we have any guidance about version upgrade?

Thanks!

**Comment by hhaAndroid** [comment]
Q1: Yes，compatible.
Q2: you can read [changelog](https://github.com/open-mmlab/mmdetection/blob/master/docs/changelog.md)

**Comment by calvin886** [comment]
Thanks for your reply,
I think i need to update the version of mmcv and Pytorch in my virtual environment right?

**Comment by hhaAndroid** [comment]
> Thanks for your reply,
> I think i need to update the version of mmcv and Pytorch in my virtual environment right?

YES
