### ISSUE TITLE
error happened when run onnx2tensorrt

### ISSUE THREAD

**Issue by DJ543** [open-mmlab/mmdetection#4822]
**Describe the bug**
error happened when run onnx2tensorrt

**Reproduction**
I have run tools/deployment/pytorch2onnx.py successfully with configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py. And I  installed mmcv-full with ONNXRuntime custom ops and TensorRT plugins as the markdown introduct. I set up ONNX_BACKEND=MMCVTensorRT followed by issuse #4731, finished the unit test with tests/test_ops/test_tensorrt.py.
I didn't make any modifications on the code or  config. But I have problems when run tools/deployment/onnx2tensorrt.py
```
python tools/deployment/onnx2tensorrt.py \
    checkpoints/faster_rcnn/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.onnx \
    --trt-file checkpoints/faster_rcnn/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.trt \
    --input-img img/1_dj_0.jpg \
    --shape 480 720 \
    --mean 123.675 116.28 103.53 \
    --std 58.395 57.12 57.375\
    --show \
    --verify
```

**RuntimeError: parse onnx failed:
In node -1 (importTopK): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()**

**Environment**
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.5.1
MMCV: 1.2.7
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.2
MMDetection: 2.10.0+

[pip3] numpy==1.20.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] cudatoolkit               10.2.89              hfd86e86_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2020.2                      256    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.0.12           py37ha843d7b_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.1.1            py37h0573a6f_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.16.4           py37h7e9f1db_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.20.1                    <pip>
[conda] numpy-base                1.16.4           py37hde5b4d6_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py37_cu102    pytorch
onnx                      1.8.1                     <pip>
onnxruntime               1.5.1                     <pip>
tensorrt                  7.1.3.4

$PATH: /home/dujie/anaconda3/envs/open-mmlab/bin:/home/dujie/anaconda3/bin:/usr/local/cuda-10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

$LD_LIBRARY_PATH: /home/dujie/project/mmcv/onnxruntime-linux-x64-1.5.1/lib::/usr/local/cuda-10.2/lib64:/cv_data/dujie/TensorRT-7.1.3.4/lib

$ONNX_BACKEND: MMCVTensorRT

**Error traceback**
```
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 179, in <module>
    workspace_size=args.workspace_size)
  File "tools/deployment/onnx2tensorrt.py", line 38, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/home/dujie/project/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 148, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (importTopK): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()
```

**Bug fix**
I have investigated the related problems. A tensor can not be used as the index of another tensor. I have located my problem with mmdet==2.9.0. In mmdet/models/dense_heads/ ssssrpn_head.py 
`dets, keep = batched_nms(proposals, scores, ids, nms_cfg)`

this will lead the problem to mmcv nms. And I didn't solve my issue by update mmdet. Did I make some mistakes when I installed mmcv-full with ONNXRuntime custom ops and TensorRT plugins? But I executed the unit test successfully. 
Thank you very much for your help

**Comment by geekplusaa** [comment]
(open-mmlab) wwh@wwh:/opt/ai/projects/github/mmdetection/mmdetection$ python tools/deployment/onnx2tensorrt.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_10.onnx --trt-file work_dirs/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_epoch_10.trt --show --verify
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 148, in <module>
    assert is_tensorrt_plugin_loaded(), 'TensorRT plugin should be compiled.'
AssertionError: TensorRT plugin should be compiled.

**Comment by DJ543** [comment]
@geekplusaa hi, I got the same question earily. If you obey the introduction of installation ,you will succeed. If you succeed and don't have my problem, please let me know

**Comment by DJ543** [comment]
@ZwwWayne @hhaAndroid  Hi, I have tried to update my Tensorrt version to 7.2.1.6, maybe the only difference is the Ubuntu version, but I failed again, and I donn't think the Ubuntu version failed the program. As the onnx2tensorrt.md said, "If you meet any problem with the listed models above, please create an issue and it would be taken care of soon", can you give me some advice asap.

**Comment by RunningLeon** [comment]
@DJ543 Because we are supporting deployment with batch, there may be some issue with the current master branch. If it is not so urgent, strongly suggest you try again after PR #4796 is merged. 

BTW, the following error is due to K in TopK should be int in TensorRT, not a Tensor, but it could be a Tensor in ONNXRuntime. You could comment out those codes of creating dynamic K for TopK to workaround.

```
In node -1 (importTopK): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()
```

**Comment by DJ543** [comment]
@RunningLeon Hi, thanks for your help and your work. I did some work to solve the problem with mmdet previous version but I failed with nms in mmcv. And I didn't run the onnx2tensorrt.py successfully with verision2.10.0.Now, I will  solve the TopK problem with verison2.10.0. And I'm Looking forward to your work.

**Comment by geekplusaa** [comment]
@DJ543 I always have this problem
---
Traceback (most recent call last):
File "tools/deployment/onnx2tensorrt.py", line 148, in
assert is_tensorrt_plugin_loaded(), 'TensorRT plugin should be compiled.'
AssertionError: TensorRT plugin should be compiled.
---
Install tensorrt7.2.2.3
1: pip install tensorrt-7.2.2.3-cp38-none-linux_x86_64.whl
2:pip install uff-0.6.9-py2.py3-none-any.whl

I don't know what went wrong?

**Comment by DJ543** [comment]
@geekplusaa Did you follow the doc https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/onnx2tensorrt.md#prerequisite   ?

**Comment by RunningLeon** [comment]
@DJ543 Thanks for the reply.
@geekplusaa You have to install mmcv-full with custom ops for ONNXRuntime and TensorRT.
```
MMCV_WITH_OPS=1 MMCV_WITH_ORT=1 MMCV_WITH_TRT=1 pip install -e .
```

**Comment by jiejie1993** [comment]
I found the same error when I convert Yolov3 onnx model to tensorrt.

 RuntimeError: parse onnx failed:
In node -1 (importTopK): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()

my env is:
mmdetection:2.12.0
mmcv:1.3.5 
I install according to official handbook from source：MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 MMCV_WITH_ORT=1 pip install -e .

**Comment by RunningLeon** [comment]
@jiejie1993 Hi, you may need to export an env variable when using pytorch2onnx if your destination backend is TensorRT.


> If the deployed backend platform is TensorRT, please add environment variables before running the file:
```
export ONNX_BACKEND=MMCVTensorRT
```
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md#list-of-supported-models-exportable-to-onnx

**Comment by jiejie1993** [comment]
> @jiejie1993 Hi, you may need to export an env variable when using pytorch2onnx if your destination backend is TensorRT.
> 
> > If the deployed backend platform is TensorRT, please add environment variables before running the file:
> 
> ```
> export ONNX_BACKEND=MMCVTensorRT
> ```
> 
> https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md#list-of-supported-models-exportable-to-onnx

It worked! thanks for your reply.
