### ISSUE TITLE
Help with Sparse RCNN Default Evaluation Parameters & Post-processing

### ISSUE THREAD

**Issue by sreevishnu-damodaran** [open-mmlab/mmdetection#4826]
Could I please get some help with the Sparse RCNN evaluation parameters and post-processing (score threshold or nms or others) methods that are used by default in MMDetection?

I'm using the following model and config:
`sparse_rcnn_r101_fpn_300_proposals_crop_mstrain_480-800_3x_coco.py`

I'm getting a high CV score during validation but, as this model produces 300 proposal boxes and doesn't perform any post-processing by default during TEST Inference. So, I'm not able to figure out the exact settings I need to use for test predictions.

The original paper says the following about the 100 proposals model and the way they did evaluation.
"For evaluation, we directly use these 100 boxes without any post-processing."

Any help would be really appreciated. Thanks in advance

**Comment by hhaAndroid** [comment]
I may not understand the meaning, but you can set `num_proposals`  to specified in cfg.

**Comment by sreevishnu-damodaran** [comment]
Thanks @hhaAndroid
Sorry if my initial comment was a little vague.

The issue I'm facing is after I complete the model training. During the training, I'm performing evaluation after each epoch and after sufficient epochs and lr scheduling, I'm getting a good CV mAP in the default evaluation that happens as a part of the training as I also provide a validation dataset. Then, when I have to perform inference on test images, the model predicts either 100 or 300 proposals as per the specified `num_proposals` and the mAP doesn't seem to be at par with other models trained to the same CV score.

I just wanted to know if some post-processing or confidence score threshold filtering is applied during the default evaluation that happens during the training so that I can replicate the same performance for the test inference. I scanned through the config file for this model and I couldn't find a setting for nms threshold or other techniques like the ones in the config files of other models.

**Comment by hhaAndroid** [comment]
Hi 
1. If you are testing with tools/test.py, then the performance must be the same as when val
2. If you are testing with image_demo.py, then the only difference is `--score-thr`

Sparse RCNN post-processing only has the `num_proposals` parameter.

**Comment by sreevishnu-damodaran** [comment]
Thank you 🙂

Could you please help in providing the exact ` --score-thr` value used with the MMDET API?

I'm referring to the default ` --score-thr` for validation (during the training) with the `mmdet.apis.train_detector` method and inference with the mmdet.apis.inference_detector` method.

I can see the `max_per_img` but, I couldn't find the ` --score-thr` key for validation and test pipelines in the sparse rcnn config.

**Comment by hhaAndroid** [comment]
1. It is `--show-score-thr` in tool/test.py https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L45
2. It is `--score-thr` in demo/image_demo.py https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py#L14
