### ISSUE TITLE
Run-Time Optimization

### ISSUE THREAD

**Issue by yuvalg1987** [open-mmlab/mmdetection#4829]
Hi,

Is it possible to perform model run-time optimizations such as pruning, quantization etc. under mmdetection? 
In addition, has anybody tried using distiller (https://github.com/IntelLabs/distiller) for that task under mmdetection?

Thanks
Yuval

**Comment by xvjiarui** [comment]
It is not supported officially for now.

**Comment by yuvalg1987** [comment]
Ok, thanks for the quick answer!

**Comment by ZwwWayne** [comment]
Localization distillation in PR https://github.com/open-mmlab/mmdetection/pull/4758 will be supported in the next release.
