### ISSUE TITLE
ImportError:cannot import name 'get_git_hash' from 'mmcv.utils' 

### ISSUE THREAD

**Issue by calvin886** [open-mmlab/mmdetection#4831]
<img width="453" alt="截屏2021-03-25 上午11 10 43" src="https://user-images.githubusercontent.com/46655164/112413193-bf3dbf00-8d5a-11eb-859c-1cd57ce60326.png">
<img width="525" alt="截屏2021-03-25 上午11 12 59" src="https://user-images.githubusercontent.com/46655164/112413394-15126700-8d5b-11eb-9fb6-d579c73ae1c6.png">

I am using 
Pytorch 1.7
torchvision 0.8.0
python 3.7
CUDA 10.2
MMCV-full:1.2.7
MMDetection 2.10.0

After i down everything above here, i just follow the get_started.md to build requirements and install MMdetection.

Then, i try to run commend 'python tools/train.py -h' to see if it worked. it showed the error above.

Did i down the wrong mmcv version or something to cause the error? please help.

**Comment by xvjiarui** [comment]
Hi @calvin886 
I am not quite sure. Could you please check `which python` first?

**Comment by calvin886** [comment]
> Hi @calvin886
> I am not quite sure. Could you please check `which python` first?

<img width="453" alt="截屏2021-03-25 下午2 39 01" src="https://user-images.githubusercontent.com/46655164/112429611-d939ca80-8d77-11eb-9203-2c982b77ef61.png">
Are there something wrong with python?

**Comment by xvjiarui** [comment]
Hi @calvin886 
I couldn't reproduce this issue. Do you add something into the mmdetection directory?

**Comment by calvin886** [comment]
> Hi @calvin886
> I couldn't reproduce this issue. Have you added something into the mmdetection directory?

<img width="430" alt="截屏2021-03-26 下午2 10 29" src="https://user-images.githubusercontent.com/46655164/112589976-069c7c00-8e3d-11eb-9ba4-8c6f98cfeafa.png">

This ‘mmcv’ directory is the only thing i added into the mmdetection directory

**Comment by ZwwWayne** [comment]
You may delete the mmcv in your directory and try again. It is highly possible that the python first look into the MMCV directory and cannot import `get_git_hash`.

**Comment by calvin886** [comment]
> You may delete the mmcv in your directory and try again. It is highly possible that the python first look into the MMCV directory and cannot import `get_git_hash`.

Thanks for your reply,
I deleted the 'mmcv' directory first, and run 
pip install -r requirements/build.txt
pip install -v -e .
python tools/train.py -h
then, I got the same error 
<img width="462" alt="截屏2021-03-26 下午10 47 10" src="https://user-images.githubusercontent.com/46655164/112649244-37080880-8e85-11eb-8b24-01d9bb3da6cc.png">
my virtual environment is below here
<img width="462" alt="截屏2021-03-26 下午10 47 55" src="https://user-images.githubusercontent.com/46655164/112649346-5141e680-8e85-11eb-9555-4f103d36a2d5.png">

<img width="434" alt="截屏2021-03-26 下午10 49 58" src="https://user-images.githubusercontent.com/46655164/112649670-99610900-8e85-11eb-8be9-58217c27fea6.png">

**Comment by SamMohel** [comment]
did you solve it ?

**Comment by CansuNurDemirkiran** [comment]
I get the same error. The mmcv library is installed under the "../python3.7/site-packages/mmcv" directory. If you get in the directory and go the "../mmcv/utils/__init__.py" file and search for "get_git_hash" function, you won't find it, that's why you get this error. So you have to delete the mmcv and mmcv related folders like "mmcv_full-1.7.0.dist-info" or any other version info folders. And reinstall the mmcv-full using commands bellow. 

pip install -U openmim
mim install mmcv-full

After installation you can check, if the "get_git_hash" is there. It worked for me, hope it works for you too.

For more information about the mmcv library, you can check this document: "https://mmcv.readthedocs.io/_/downloads/en/latest/pdf/"

**Comment by Ancuy** [comment]
You can try changing 'from mmcv. untils' to' from mmengine. until '
I am using mmcv2.2.0
