### ISSUE TITLE
why many fram have not the yolo？

### ISSUE THREAD

**Issue by qiangruoyu** [open-mmlab/mmdetection#484]
I looked for a couple of similar frameworks, but why didn't any of them have the yolo algorithm?

**Comment by hellock** [comment]
Maybe some historical reasons. YOLO is firstly implemented with neither mainstream backbones or mainstream DL frameworks, and the pipeline is different from other methods, so it is not as popular as SSD or Faster R-CNN and their variants.

You may refer to https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet for YOLO on PyTorch.
