### ISSUE TITLE
Fine-tuning problem

### ISSUE THREAD

**Issue by calvin886** [open-mmlab/mmdetection#4846]
I have a pre-trained model of SSD(vgg16) which have already trained on a large dataset, and then I try to use this model as my pre-model to fine-tuning on another small dataset.
 
How to freeze the parameters of some layers and train the remaining layers in SSD300-vgg16 ?

Thanks!

**Comment by xvjiarui** [comment]
Hi @calvin886 
You may implement something like this https://github.com/open-mmlab/mmdetection/blob/5af50631d92bcf2a7841e997c48bd515d2980b5b/mmdet/models/backbones/resnet.py#L572

**Comment by xvjiarui** [comment]
If you would like to use your own pretrained weight, you may directly set `pretrained` to your checkpoint path.

**Comment by calvin886** [comment]
> If you would like to use your own pretrained weight, you may directly set `pretrained` to your checkpoint path.

Thanks a lot Jerry! It helps me a lot!

**Comment by calvin886** [comment]
> Hi @calvin886
> You may implement something like this
> 
> https://github.com/open-mmlab/mmdetection/blob/5af50631d92bcf2a7841e997c48bd515d2980b5b/mmdet/models/backbones/resnet.py#L572

OK, I got it. Thank you so much. btw, why you guys were not implement the `_freeze_stages` in `mmdetection/mmdet/models/backbones/ssd_vgg.py `?  It is a very useful feature.

**Comment by calvin886** [comment]
Dear Jerry，

我一直有一个疑问，关于上次使用训练模型时只需要在  pretrained这里设置成我的checkpoint path。
我局的这样做是不对的
因为在你们的code中 pretrained
后面跟的都是vgg16,resnet50,darknet这种backbone，但是你要是让我把整个训练好的ssd.pth，retinanet。pth或者yolo.pth去等于
pretrained这样显然是不对的。 请问你能告诉我你之前说“you may directly set pretrained to your
checkpoint path ” 是什么原理吗。

best wishes！
Jiacheng

**Comment by xvjiarui** [comment]
Hi @calvin886 
Please use English or English+Chinese for issues. 
If the entire detector is pertained, you need to use `--load-from`. If just backbone, you need to use `pretrained`.
