### ISSUE TITLE
CUDA out of memory which should not be

### ISSUE THREAD

**Issue by CathayPacific358** [open-mmlab/mmdetection#4847]
I was implementing a custom backbone with two sets of data. 
All these datasets are implemented under batch size of 1. The first set of it contains larger images that most of which are about 350x350 with some even larger in 700x1500 that approximately 120kb. CUDA never raise a OOM for this dataset. However, for another dataset which contains smaller images that resized into 300x300 in approximately 35kb, CUDA keep raising OOM no matter how I resize the image into smaller resolution, which does not make sense.
Please help me to figure it out. Thx.

Error message:
RuntimeError: CUDA out of memory. Tried to allocate 20.00MiB (GPU 0; 10.76 GiB total capacity; 9.41 GiB already allocated; 11.38MiB free; 9.86 GiB reserved in total by PyTorch)

**Comment by jshilong** [comment]
It doesn't matter what is the original resolution， The cuda memory is only related to the size of `Resize` in the `train_pipeline` or `test_pipeline`.
