### ISSUE TITLE
rpn_r50_fpn_1x_val2017.pkl? Use Fast R-cnn to train my own dataset

### ISSUE THREAD

**Issue by Zhangyannn1030** [open-mmlab/mmdetection#4848]
After converting my voc2007 data set to coco, I tried to train my own data set with Fast R-CNN, but encountered the following error, how can I get this pkl file? Or that this is not the key to the problem? ?

Traceback (most recent call last) :
File "toolsltrain. py", line 187, in <module>main()
File "tools/train.py", line 163, in main
datasets =[build_dataset(cfg.data.train)]
File"/usT/local/lib/python3.7/dist-packages /mmdet/datasets/builder.py", line 71，in build_datasetdataset = build_from_cfglcfg,DATASETs,default_args)
File"/usx/local/lib/python3.7/dist-packages /mncv/utils/registry.py"， line 182,in build_from_ofgraise type(e)(f’Tobj_cls._name_ : {e}')
FilelotFoudError : CocoDataset: Errno 2] Mo such file or directory : 'data/coco/proposals/rpn r50_fpn_1x_train2017.pkl'

**Comment by jshilong** [comment]
You should do the inference on the dataset then get the `pkl` with your own `rpn` head

**Comment by oreo-lp** [comment]
excuse me, how do inference to get the pkl?

**Comment by Zhangyannn1030** [comment]
sorry，i did not solve this problem ，exactly &nbsp;i could not get the reason why it comes to this situation。QAQ

发自我的iPhone


------------------ Original ------------------
From: oreo-lp ***@***.***&gt;
Date: Sun,Apr 18,2021 0:19 PM
To: open-mmlab/mmdetection ***@***.***&gt;
Cc: Zhangyannn1030 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [open-mmlab/mmdetection] rpn_r50_fpn_1x_val2017.pkl? Use Fast R-cnn to train my own dataset (#4848)

**Comment by oreo-lp** [comment]
Thank you!

**Comment by oreo-lp** [comment]
> sorry，i did not solve this problem ，exactly &nbsp;i could not get the reason why it comes to this situation。QAQ 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: oreo-lp ***@***.***&gt; Date: Sun,Apr 18,2021 0:19 PM To: open-mmlab/mmdetection ***@***.***&gt; Cc: Zhangyannn1030 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [open-mmlab/mmdetection] rpn_r50_fpn_1x_val2017.pkl? Use Fast R-cnn to train my own dataset (#4848)

Will you share me you configs?

**Comment by Zhangyannn1030** [comment]
you means Fast rcnn？i used the official configs



发自我的iPhone


------------------ Original ------------------
From: oreo-lp ***@***.***&gt;
Date: Sun,Apr 18,2021 1:01 PM
To: open-mmlab/mmdetection ***@***.***&gt;
Cc: Zhangyannn1030 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [open-mmlab/mmdetection] rpn_r50_fpn_1x_val2017.pkl? Use Fast R-cnn to train my own dataset (#4848)

**Comment by oreo-lp** [comment]
> you means Fast rcnn？i used the official configs 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: oreo-lp ***@***.***&gt; Date: Sun,Apr 18,2021 1:01 PM To: open-mmlab/mmdetection ***@***.***&gt; Cc: Zhangyannn1030 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [open-mmlab/mmdetection] rpn_r50_fpn_1x_val2017.pkl? Use Fast R-cnn to train my own dataset (#4848)

Thank you!
