### ISSUE TITLE
could you add the code for the multi-cpus with multi-gpus?

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#485]

**Comment by runzeer** [comment]
I just have multiple machines connected with the ethernet.  I just added the cfg.dist_params with init_method ='env://'.  But the speed is slower than the single node with multi-gpus. So is there something wrong with my change?

**Comment by hellock** [comment]
What do you mean by multi-cpu?
Multi-node training is already supported. It is normal to be slower if you do not have an optimized cluster.

**Comment by runzeer** [comment]
sorry for the error writing. I mean the multi-nodes with multi-gpus. when I tried to use single mode and the mode has two gpus, and the config file is htc_r50_fpn_1x.py ,the whole time would cost about 4 days. But when I tried to use the two modes and every mode has two gpus, the same config file would cost 8 days. It is normal for slower for two modes because I do not have the optimized cluster. But the cost time  is more than the single mode,is it normal? Or is there something wrong with the code?

**Comment by thangvubk** [comment]
If you wish to train with multiple machines, you probably need a high-speed network (e.g. Infiniband). Otherwise, it would be slower than a single machine.

**Comment by RaymondByc** [comment]
> If you wish to train with multiple machines, you probably need a high-speed network (e.g. Infiniband). Otherwise, it would be slower than a single machine.

Are there extra steps to using Infiniband?  I update the connection method from Ethernet to Infiniband, but the iter time improved just limited (1%). 

Did you test your code with an Infiniband connection? how its performance is?
