### ISSUE TITLE
Using OHEMSampler for negative mining in Two stage Detectors

### ISSUE THREAD

**Issue by tiberium24** [open-mmlab/mmdetection#4853]
**Using OHEM in Two stage Detectors**

**Motivation**
I have seen that OHEM can provide better results and would like to use it for an application. Is this feature supported?
I believe it was in an earlier version but no longer? Can we still use it somehow? I am using the Cascade DCONV detector.

**Comment by jshilong** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_ohem_1x_coco.py
