### ISSUE TITLE
'ConfigDict' object has no attribute 'train_cfg' in colab tutorial

### ISSUE THREAD

**Issue by JaumePrats** [open-mmlab/mmdetection#4854]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I am getting started using mmdetection using de colab tutorial on github: *mmdetection/demo/MMDet_Tutorial.ipynb*
Without making any modifications to the code I get the following error in *Train a new detector section*:

AttributeError: 'ConfigDict' object has no attribute 'train_cfg'

**Reproduction**

1. What command or script did you run?

```none
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import train_detector


# Build dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_detector(
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I did not make any modifications to the code.
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
AttributeError                            Traceback (most recent call last)
<ipython-input-38-63f0da5758a7> in <module>()
      9 # Build the detector
     10 model = build_detector(
---> 11     cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
     12 # Add an attribute for visualization convenience
     13 model.CLASSES = datasets[0].CLASSES

1 frames
/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py in __getattr__(self, name)
     41         else:
     42             return value
---> 43         raise ex
     44 
     45 

AttributeError: 'ConfigDict' object has no attribute 'train_cfg'
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
Please refer to #4688
