### ISSUE TITLE
After I trained my model with coco datasets, I test this model with cityscapes dataset. All ap is -1!!

### ISSUE THREAD

**Issue by ModestYjx** [open-mmlab/mmdetection#4861]
I ran this command:
```
./tools/dist_test.sh     configs/experiment_fpn/cityscapes/experiment_BFP.py     work_dirs/experiment_fpn/experiment_BFP/latest.pth     4     --eval bbox
```

logger is 
```
root@40c6f06c3798:/mmdetection# PORT=31111 ./tools/dist_test.sh     configs/experiment_fpn/cityscapes/experiment_BFP.py     work_dirs/experiment_fpn/experiment_BFP/latest.pth     4     --eval bbox
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
loading annotations into memory...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Done (t=0.00s)
creating index...
index created!
Use load_from_local loader
Use load_from_local loader
loading annotations into memory...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Done (t=0.00s)
creating index...
index created!
Use load_from_local loader
Use load_from_local loader
The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([9, 1024]).
size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([9]).
size mismatch for roi_head.bbox_head.fc_reg.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([32, 1024]).
size mismatch for roi_head.bbox_head.fc_reg.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([32]).
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1528/1525, 13.6 task/s, elapsed: 113s, ETA:     0sloading annotations into memory...
Done (t=0.04s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

Evaluating bbox...
Loading and preparing results...
DONE (t=1.31s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=3.20s).
Accumulating evaluation results...
DONE (t=1.08s).
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
{'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}
```

I hope to get a normal metric result.

But I got 
```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
{'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}
```

**Comment by ModestYjx** [comment]
- If you need more information, please let me know it. I can will supply more information.
- I want to know why this problem will happed.

**Comment by donxy** [comment]
> I ran this command:
> 
> ```
> ./tools/dist_test.sh     configs/experiment_fpn/cityscapes/experiment_BFP.py     work_dirs/experiment_fpn/experiment_BFP/latest.pth     4     --eval bbox
> ```
> 
> logger is
> 
> ```
> root@40c6f06c3798:/mmdetection# PORT=31111 ./tools/dist_test.sh     configs/experiment_fpn/cityscapes/experiment_BFP.py     work_dirs/experiment_fpn/experiment_BFP/latest.pth     4     --eval bbox
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> loading annotations into memory...
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> Done (t=0.00s)
> creating index...
> index created!
> Use load_from_local loader
> Use load_from_local loader
> loading annotations into memory...
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> Done (t=0.00s)
> creating index...
> index created!
> Use load_from_local loader
> Use load_from_local loader
> The model and loaded state dict do not match exactly
> 
> size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([9, 1024]).
> size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([9]).
> size mismatch for roi_head.bbox_head.fc_reg.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([32, 1024]).
> size mismatch for roi_head.bbox_head.fc_reg.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([32]).
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1528/1525, 13.6 task/s, elapsed: 113s, ETA:     0sloading annotations into memory...
> Done (t=0.04s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> 
> Evaluating bbox...
> Loading and preparing results...
> DONE (t=1.31s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=3.20s).
> Accumulating evaluation results...
> DONE (t=1.08s).
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> {'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}
> ```
> 
> I hope to get a normal metric result.
> 
> But I got
> 
> ```
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> {'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}
> ```



> I ran this command:
> 
> ```
> ./tools/dist_test.sh     configs/experiment_fpn/cityscapes/experiment_BFP.py     work_dirs/experiment_fpn/experiment_BFP/latest.pth     4     --eval bbox
> ```
> 
> logger is
> 
> ```
> root@40c6f06c3798:/mmdetection# PORT=31111 ./tools/dist_test.sh     configs/experiment_fpn/cityscapes/experiment_BFP.py     work_dirs/experiment_fpn/experiment_BFP/latest.pth     4     --eval bbox
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> loading annotations into memory...
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> Done (t=0.00s)
> creating index...
> index created!
> Use load_from_local loader
> Use load_from_local loader
> loading annotations into memory...
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> Done (t=0.00s)
> creating index...
> index created!
> Use load_from_local loader
> Use load_from_local loader
> The model and loaded state dict do not match exactly
> 
> size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([9, 1024]).
> size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([9]).
> size mismatch for roi_head.bbox_head.fc_reg.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([32, 1024]).
> size mismatch for roi_head.bbox_head.fc_reg.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([32]).
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1528/1525, 13.6 task/s, elapsed: 113s, ETA:     0sloading annotations into memory...
> Done (t=0.04s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> 
> Evaluating bbox...
> Loading and preparing results...
> DONE (t=1.31s)
> creating index...
> index created!
> Running per image evaluation...
> Evaluate annotation type *bbox*
> DONE (t=3.20s).
> Accumulating evaluation results...
> DONE (t=1.08s).
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> {'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}
> ```
> 
> I hope to get a normal metric result.
> 
> But I got
> 
> ```
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = -1.000
> Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = -1.000
> {'bbox_mAP': -1.0, 'bbox_mAP_50': -1.0, 'bbox_mAP_75': -1.0, 'bbox_mAP_s': -1.0, 'bbox_mAP_m': -1.0, 'bbox_mAP_l': -1.0, 'bbox_mAP_copypaste': '-1.000 -1.000 -1.000 -1.000 -1.000 -1.000'}
> ```
you could change  `**gtFine_test.json` and `leftImg8bit/test/`  into  `**gtFine_val.json` and `leftImg8bit/val/` in test dict of configs/_base_/cityscapes_instance.py , because cityscapes  test dataset you doenload have no full annotation
