### ISSUE TITLE
About train custom dataset

### ISSUE THREAD

**Issue by joey1616** [open-mmlab/mmdetection#4862]
Hello, I want to use mmdetection to train custom dataset. I transfer my dataset to voc. But my dataset only have one class. So I changed `model = dict(roi_head=dict(bbox_head=dict(num_classes=1)))
` in configs. And I changed `CLASSES = ('ship')` in mmdet/datasets/voc.py.
The program not worked with `AssertionError: The [num_classes] (1) in Shared2FCBBoxHead of MMDataParallel does not matches the length of [CLASSES]20) in RepeatDataset
`
How can I solve it? Thank you.

**Comment by fengyouliang** [comment]
add `classes=('ship', )` in 
```python
dataset=dict(
    type=dataset_type,
    classes=('ship', ),
    ann_file=[
        data_root + 'VOC2007/ImageSets/Main/trainval.txt',
        data_root + 'VOC2012/ImageSets/Main/trainval.txt'
    ],
    img_prefix=[data_root + 'VOC2007/', data_root + 'VOC2012/'],
    pipeline=train_pipeline
)
```
it work in `CocoDataset`

**Comment by fengyouliang** [comment]
no need, just add `classes=('ship', )` in your dataset config

**Comment by fengyouliang** [comment]
> > add `classes=('ship', )` in
> > ```python
> > dataset=dict(
> >     type=dataset_type,
> >     classes=('ship', ),
> >     ann_file=[
> >         data_root + 'VOC2007/ImageSets/Main/trainval.txt',
> >         data_root + 'VOC2012/ImageSets/Main/trainval.txt'
> >     ],
> >     img_prefix=[data_root + 'VOC2007/', data_root + 'VOC2012/'],
> >     pipeline=train_pipeline
> > )
> > ```
> > 
> > 
> > it work in `CocoDataset`
> 
> Hi, do I need to convert my dataset to coco format? Thank you.

no need, just add `classes=('ship', )` in your dataset config

**Comment by joey1616** [comment]
> config

It works. Thank you.
