### ISSUE TITLE
How to change the paint color  for bbox and category name during inference?

### ISSUE THREAD

**Issue by Hwang64** [open-mmlab/mmdetection#4865]
Hi, for visualization the detection results and save the painted images during inference, I want to change the color for painting the bbox and category name, where is the corrsponding codes and how can I do? Thank you.

**Comment by daavoo** [comment]
For changing the color of the painted bbox, you can use the `bbox_color` argument of `model.show_result`:

https://github.com/open-mmlab/mmdetection/blob/ff38f207826859e7a89255b31978809717d4f096/mmdet/models/detectors/base.py#L291

For changing the category names, you can update the `model.CLASSES` property, as that is the list used inside `model.show_result`:

https://github.com/open-mmlab/mmdetection/blob/ff38f207826859e7a89255b31978809717d4f096/mmdet/models/detectors/base.py#L342

Example:

```python
model = init_detector(config, checkpoint, device=device)
result = inference_detector(model, img)
model.CLASSES = ("new_category_name_0", "new_category_name_1")
custom_color = (255, 0, 0)
model.show_result(
    img,
    result,
    score_thr=score_thr,
    show=True,
    wait_time=0,
    win_name="result",
    bbox_color=custom_color)
```

**Comment by Hwang64** [comment]
@daavoo Thanks very much!
