### ISSUE TITLE
GHM  & SSD Head 

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#4868]
Hello! I want to add GHM Loss to SSD Head, but I found a strange question.

The one of input parameters of GHMC Loss is pred (float tensor of size [batch_num, class_num]), I think the input  pred size is  wrong, because one image have many anchors. How do you explain this?

Thank you very much!

**Comment by ZwwWayne** [comment]
GHM for SSD is not tried, so there might be some incompatibility between their APIs. You may check how GHM is used for RetinaNet and modify the interface.
