### ISSUE TITLE
RPN performance

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection#487]
The performance of RPN in model zoo (AR1000 = 57.1) is lower than reported value in Guided anchoring paper (AR1000 = 59.4). Is there any settings that are different from the paper. Thank you.

**Comment by hellock** [comment]
The Guided Anchoring paper is implemented with a very early version codebase. There are two differences. 1) caffe-style backbones are used for all experiments 2) smooth_l1 beta is not used, while target_stds = [0.11, 0.11, 0.33, 0.33].

**Comment by thangvubk** [comment]
Thank you for clarification. Just for curiosity, how did you find ``target_stds``. Is that: train the network with ``target_stds = [1, 1, 1, 1]``, then after the network converged you evaluate the output boxes of training set again to get ``target_stds``.

**Comment by hellock** [comment]
Such hyper-parameters have been adopted long ago and we just follow that. It is computed as the std of regression targets.

**Comment by tonysy** [comment]
Hi, I wonder how evaluate the RPN recall of a pretrained faster-rcnn model? Any suggestions?

**Comment by thangvubk** [comment]
@tonysy ./tools/dist_test.sh ${RPN_CONFIG_FILE} ${CHECKPOINT_FILE} ${GPU_NUM} [--out ${RESULT_FILE}] --eval proposal_fast
