### ISSUE TITLE
Why IOU balanced sampling in libra-rcnn reduces accuracy instead？

### ISSUE THREAD

**Issue by ModestYjx** [open-mmlab/mmdetection#4872]
- I add  IOU balanced sampling  module on BFP_BLL strategy, but m-ap is reduced. 
- I want to know why this result happend.
Here are my experiment results:
### experiment_BFP_BLL
([('bbox_mAP', 0.37), 
('bbox_mAP_50', 0.578), 
('bbox_mAP_75', 0.402), 
('bbox_mAP_s', 0.221), 
('bbox_mAP_m', 0.405), 
('bbox_mAP_l', 0.465), 
('bbox_mAP_copypaste', '0.370 0.578 0.402 0.221 0.405 0.465'), 
('mAP', 0.425), 
('mAP_50', 0.682), 
('mAP_75', 0.455), 
('mAP_s', 0.281), 
('mAP_m', 0.484), 
('mAP_l', 0.595)])

### experiment_BFP_BLL_IOUBS
([('bbox_mAP', 0.364),
 ('bbox_mAP_50', 0.567),
 ('bbox_mAP_75', 0.395),
 ('bbox_mAP_s', 0.209),
 ('bbox_mAP_m', 0.399),
 ('bbox_mAP_l', 0.462),
 ('bbox_mAP_copypaste', '0.364 0.567 0.395 0.209 0.399 0.462'),
 ('mAP', 0.422),
 ('mAP_50', 0.673),
 ('mAP_75', 0.451),
 ('mAP_s', 0.271),
 ('mAP_m', 0.477),
 ('mAP_l', 0.596)])

- If you need my code, I could send it to you to check this problem .

**Comment by ZwwWayne** [comment]
For these modules, you need to specifically tune the hyper-parameters as the original hyper-parameters are tuned for the COCO dataset.
