### ISSUE TITLE
Is there an error in calculating average precision by 11 points method?

### ISSUE THREAD

**Issue by ZephyrusKylin** [open-mmlab/mmdetection#4873]
https://github.com/open-mmlab/mmdetection/blob/ff38f207826859e7a89255b31978809717d4f096/mmdet/core/evaluation/mean_ap.py#L50

I think the div function should be used out of the num_scales circulation.

**Comment by hhaAndroid** [comment]
Hi. Thank you very much, this is indeed wrong,  can you create a PR?

**Comment by ZephyrusKylin** [comment]
> Hi. Thank you very much, this is indeed wrong, can you create a PR?

OK~
