### ISSUE TITLE
HELP!!  KeyError: 'ann_info' Only during evaluation process

### ISSUE THREAD

**Issue by tcexeexe** [open-mmlab/mmdetection#4881]
**Describe the bug**

I converted my dataset to Coco format and trained it. The training set validation set is the same. When the program starts validation, the following error is reported.If my data set is formatted incorrectly, then why did it not report errors during training? I used the same pipline to read the training and validation sets
![image](https://user-images.githubusercontent.com/28287196/113368300-f92d4780-9390-11eb-818b-7b3ffd1a14e6.png)

Traceback (most recent call last):
File "tools/train.py", line 187, in lt;module&gt;
The main ()
File "tools/train.py", line 183, in main
Meta meta =)
The File "/ home/tcexeexe/dataDisk1 / mmdetection/mmdet/apis/train. Py", line 170, in train_detector
Runner. The run (data_loaders, CFG. Workflow)
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/MMCV/runner/epoch_based_runner py", line 125, in the run
Epoch_runner (data_loaders [I], * * kwargs)
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/MMCV/runner/epoch_based_runner py", line 54, in train
Self. Call_hook (' after_train_epoch ')
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/MMCV/runner/base_runner py", line 308, in call_hook
Getattr (hook, fn_name) (self)
The File "/ home/tcexeexe dataDisk1 / mmdetection/mmdet/core/evaluation/eval_hooks py", line 146, in after_train_epoch
Results = single_gpu_test(runner.model, self.dataLoader, show=False)
The File "/ home/tcexeexe dataDisk1 / mmdetection mmdet/apis/test. Py", line 25, in single_gpu_test
For I, data in enumerate(data_loader):
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/torch/utils/data/dataloader py", line 517, in __next__
Data = self. _next_data ()
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/torch/utils/data/dataloader py", line 1199, in _next_data
Return the self. _process_data (data)
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/torch/utils/data/dataloader py", line 1225, in _process_data
Data. Reraise ()
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/torch / _utils. Py", line 429, in reraise
Raise the self. Exc_type (MSG)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/torch/utils/data / _utils/worker. Py", line 202, in _worker_loop
Data = fetcher. The fetch (index)
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/torch/utils/data / _utils/fetch. Py", line 44, in the fetch
Data = [self.dataset[IDX] For IDX In Possibly_Batched_Index]
The File "/ home/tcexeexe anaconda3 / envs/open - mmlab/lib/python3.7 / site - packages/torch/utils/data / _utils/fetch. Py", line 44, in & lt;listcomp&gt;
Data = [self.dataset[IDX] For IDX In Possibly_Batched_Index]
The File "/ home/tcexeexe/dataDisk1 / mmdetection/mmdet/datasets/custom. Py", line 191, in the __getitem__
Return the self. Prepare_test_img (independence idx)
The File "/ home/tcexeexe/dataDisk1 / mmdetection/mmdet/datasets/custom. Py", line 234, in prepare_test_img
Return the self. The pipeline (results)
File "/ home/tcexeexe/dataDisk1 / mmdetection/mmdet/datasets/pipelines/compose. Py", line 40, in __call__
Data = t (data)
File "/ home/tcexeexe/dataDisk1 / mmdetection/mmdet/datasets/pipelines/loading. Py", line 367, in __call__
Results = self. _load_bboxes (results)
File "/ home/tcexeexe/dataDisk1 / mmdetection/mmdet/datasets/pipelines/loading. Py", line 241, in _load_bboxes
Print (results [' ann_info '])
KeyError: 'ann_info'

**Reproduction**

1. What command or script did you run?

```none
CUDA_VISIBLE_DEVICES=1  python tools/train.py configs/panda/cascade_rcnn_r50_fpn_1x_coco_round1_panda.py
```

**Environment**

Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1660 Ti
GPU 1: Tesla M40 24GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.5.1
MMCV: 1.2.7
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMDetection: 2.10.0+

**Bug fix**

**Comment by tojimahammatov** [comment]
hi @tcexeexe , I think you have a small mistake in the code (line 238), where you should have written ```pipeline=test_pipeline```, then dataloader will not come to this line. Because this is a test mode now. I hope that you did not include ```LoadAnnotations``` in ```test_pipeline```, but if there is, make sure to remove it.
