### ISSUE TITLE
When I run docker to generate images opencv raised error. I open VPN also raised.

### ISSUE THREAD

**Issue by ZengyuanYu** [open-mmlab/mmdetection#4886]
When I run docker to generate images opencv raised error. I open VPN also raised.
1. ‘git clone https://github.com/open-mmlab/mmdetection.git’
2. 'cd mmdetection'
3. 'docker build -t mmdetection docker/'
4. docker verision is 20.45

**Comment by ZwwWayne** [comment]
What error did you meet? Could you follow the `error template` to provide more detailed information? We are not able to help here with limited information.
