### ISSUE TITLE
Can I modify the IoU threshold of the test mode?

### ISSUE THREAD

**Issue by abdoelsayed2016** [open-mmlab/mmdetection#4888]
Hello, 
I want help with modifying the IoU threshold of the test mode
I am  trying to train the model but I can understand how can I modify the IoU while test the dataset 
my config file  
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_thr=0.5),
        max_per_img=100,
        mask_thr_binary=0.5))

should I change score_thr or iou_thr i want to test the model with .5 , .6 , .7 , .8 , .9 and  .95?

I am using mmdetection v2

**Comment by hhaAndroid** [comment]
duplicate #4740

**Comment by abdoelsayed2016** [comment]
i don't want to use the test.py 
I am writing my code to calculate f1-score, so test.py does not help me.
how can I change iou threshold in my configuration file ?

**Comment by abdoelsayed2016** [comment]
test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)))
