### ISSUE TITLE
Print the det_bboxes and proposal_list

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#4890]
I successfully ran the demo and now I want to just print out the proposal_list and det_bboxes in the demo image. For proposal_list I just need to print("proposal_list) in the mmdet/detectors/two_stage.py. But how do I print the det_bboxes, just to see the values of the boxes.

**Comment by ZwwWayne** [comment]
You may need to print in the roi head [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/standard_roi_head.py#L238).

**Comment by Soodep** [comment]
Thank you! It works
