### ISSUE TITLE
mAP (medium) and mAP (large) =-1

### ISSUE THREAD

**Issue by zjmlovlin** [open-mmlab/mmdetection#4891]
In the results of my experiment, both mAP (medium) and mAP (large) are -1，but in the dataset I used, there are objects with size greater than 32*32，why？
![image](https://user-images.githubusercontent.com/46813859/113481862-8d50f900-94ce-11eb-847c-b768feafa2df.png)

**Comment by hhaAndroid** [comment]
Hi, @zjmlovlin Maybe you can visualize the results first? If there is no predicted result about a medium object, then mAP are -1.
