### ISSUE TITLE
loss_rpn_bbox is inf

### ISSUE THREAD

**Issue by NuaaWill** [open-mmlab/mmdetection#4893]
In the configuration file, the loss of rpn_head uses 'L1Loss'. The training log shows 'loss_rpn_bbox: inf', but the training process can still be completed, how can I remove this 'inf'?

**Comment by manhph2211** [comment]
Hi @1428679766, your issue is not very clear. However, I think it's about your lr. Try to decrease it.

**Comment by Fan-shujuan** [comment]
> Hi @1428679766, your issue is not very clear. However, I think it's about your lr. Try to decrease it.

I also encountered the same problem, and I can train normally in the faster rcnn in mmdet. When using the same data to train the RPN, the loss will become nan in the warmup stage (have tried to lower the lr)。
Looking forward to your reply，thanks！

**Comment by ZwwWayne** [comment]
It usually happens when there are abnormal boxes in the GT.
