### ISSUE TITLE
Generate the .json file for the prediction of VOC type dataset

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#4895]
I want to generate the .json file for the prediction of VOC type dataset
I use the command line as below:
python tools/test.py configs/pascal_voc/ssd300_voc0712.py experiments/ssd/epoch_24.pth --format-only --options "jsonfile_prefix=./results"

But I found it did't save the json file. This does not support the VOC format data?

What should I do ? Thank you very much!

**Comment by hhaAndroid** [comment]
Yes, Currently not supported, but you can convert VOC data into COCO.
