### ISSUE TITLE
About CascadeMaskRCNN class

### ISSUE THREAD

**Issue by BaeSukkyoung** [open-mmlab/mmdetection#4896]
Hi ~
I just have some question while doing my research.
I use CascadeMaskRCNN of mmdetection well and one of my detected class is crack.
I guess they're veryyyy thinner than any other object so the test result is really not good.
Is the Instance Segmentation model structure that is hard to detect tiny object ?
Usual crack size is 1~5pixel in 1024*1024 image.

Thanks :)

**Comment by ZwwWayne** [comment]
Yes, such small objects usually need specific hyper-parameter tuning or special architecture design.
