### ISSUE TITLE
AssertionError: CocoDataset: Annotation ids are not unique!

### ISSUE THREAD

**Issue by manhph2211** [open-mmlab/mmdetection#4897]
I have met this error and it is weird, I think! Can anyone help me with this :( Thanks in advance!

**Comment by daavoo** [comment]
You have to review the `annotations` list inside the `.json` in [COCO format](https://cocodataset.org/#format-data) that you are referencing in the configuration file. Each annotation inside the `annotations` list should have an **unique** `id` property; the AssertionError you have met indicates that there is at least 1 duplicated `id` in that `annotations` list.

**Comment by manhph2211** [comment]
Hi @daavoo, thanks for your reply. Actually, I had checked the JSON files before I set the issue. I found them totally normal@ Believe this or not, I did train the model successfully several days ago. But today, I have met this issue (I didn't change anything ). That's tough LOL

**Comment by ZwwWayne** [comment]
> Hi @daavoo, thanks for your reply. Actually, I had checked the JSON files before I set the issue. I found them totally normal@ Believe this or not, I did train the model successfully several days ago. But today, I have met this issue (I didn't change anything ). That's tough LOL

Successful training does not mean that the annotation is not correct. This check is added several days ago to prevent the potential error in your annotation file.

**Comment by manhph2211** [comment]
Hi @ZwwWayne, many thanks for your help! I'll carefully check the annotation again :+1:

**Comment by daavoo** [comment]
Maybe we could improve the error message to show the `id`(s) that caused the intersection

**Comment by sweetboxwwy** [comment]
How is this problem solved！please

**Comment by CharlesNJ** [comment]
Is there any update on that checking which are repeating? I am facing the same issue after converting the YOLO format files to COCO. I have more than 11k `id`s and it doesn't make sense to check it manually. @daavoo @hhaAndroid hhAndroid

**Comment by CharlesNJ** [comment]
> Is there any update on that, checking which are repeating? I am facing the same issue after converting the YOLO format files to COCO. I have more than 11k `id`s and it doesn't make sense to check it manually. @daavoo @hhaAndroid

Also, is there a library that you recommend using for converting YOLO to COCO? I am assuming it has to do something with it even though I did not find any.

**Comment by GenMoat** [comment]
mine was due to the image names aren't match the 'image_name' in the json file.
