### ISSUE TITLE
About fine-tuning problem

### ISSUE THREAD

**Issue by calvin886** [open-mmlab/mmdetection#4899]
Now, I have a ssd300.pth file which have already train on a large dataset, but I want to fine-tune it on a small dataset. These two dataset had different class number.

Is that right if I just changed the code: `pretrained='open-mmlab://vgg16_caffe', to  pretrained='./ssd300.pth,` in the file `open-mmlab/mmdetection/blob/master/configs/_base_/models/ssd300.py`

Or,  what is the right way to fine-tune it ?

Thanks

**Comment by hhaAndroid** [comment]
you should use `load_from`
