### ISSUE TITLE
Maybe one bug in DETR's implementation?

### ISSUE THREAD

**Issue by LanceZPF** [open-mmlab/mmdetection#4902]
ValueError: matrix contains invalid numeric entries (the 132th line in hungarian_assigner)

I have met this error in two different scenarios, the first occured when I tried to train a DETR from the scratch on a large-scale custom dataset,. This occured after random iterations. (By the way, if I trained the DETR from the COCO's checkpoint, then the training was OK without the error.)

As for the second, it is after when I made some changes on the original DETR Head, (the incremental refinement with no changing to the original code), then I train the model, the weights of the most part are loaded from the detr_r50_coco.pth, and the incremental part trained from scratch, and I met this ValueError after random iterations.

I might think there are some bugs in hungarian_assigner. Need for some help.

**Comment by hhaAndroid** [comment]
Hi, @LanceZPF  This error seems to be a loss of nan. Can you confirm it? Thank you

**Comment by LanceZPF** [comment]
> Hi, @LanceZPF This error seems to be a loss of nan. Can you confirm it? Thank you

Yes, I have confirmed this is the loss (or called cost_matrix in assigner) of nan. So, is it related to the setting of hyperparameters?

**Comment by hhaAndroid** [comment]
Yes, I suggest you use pretrained weights instead of scratch, and check hyperparameters.

**Comment by LanceZPF** [comment]
> Yes, I suggest you use pretrained weights instead of scratch, and check hyperparameters.

OK, thank you for your notification.

**Comment by ZwwWayne** [comment]
This usually means some cost contain `nan` of `inf` values, which is usually caused by the training failure of model of unclean annotations.
