### ISSUE TITLE
arch error , how can I fix it?

### ISSUE THREAD

**Issue by user-never-lose** [open-mmlab/mmdetection#4903]
RuntimeError: CUDA error: no kernel image is available for execution on the device (NMSCUDAKernelLauncher at ./mmcv/ops/csrc/pytorch/nms_cuda.cu:50)

**Comment by hhaAndroid** [comment]
Hi, you can refer to #4335

**Comment by hhaAndroid** [comment]
Hi, you can refer to #4335
