### ISSUE TITLE
Can we freeze parameters in HRNet backbone, HRFPN neck and RPNHead while fine-tuning?

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#4908]
As far as I am concerned, in ResNet backbone we have 'frozen_stages' that helps us freeze stages in the backbone while training. However, in the definition of HRNet, HRFPN and RPNHead we don't have argument 'frozen_stages'. I am wondering if it is feasible to freeze parameters in HRNet backbone, HRFPN neck and RPNHead, since I am trying to fine-tune the model while freezing all the parameters except for those in the last few FC layers.

**Comment by hhaAndroid** [comment]
Sorry. If you want to fix the part except for the backbone, you may need to modify the code.
