### ISSUE TITLE
Image preprocessing dimension　[64, 3, 7, 7]　 [3, 800, 1216]

### ISSUE THREAD

**Issue by liguoyu666** [open-mmlab/mmdetection#4909]
When I run demo/image_demo.py
` python demo/image_demo.py 'demo/demo.jpg' 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py' 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
`
it reported
` RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 3-dimensional input of size [3, 800, 1216] instead`

**Comment by LeThuHien22** [comment]
I got the same issue. How did you solve it??

**Comment by liguoyu666** [comment]
> I got the same issue. How did you solve it??

Run according to the readme, it will report a warning. in fact, it generate a image named 'result.jpg'. if you modify the code according to the warning, it will report this error.

**Comment by liguoyu666** [comment]
> Hi @liguoyu666 ,
> So which part did you modify that causes this error?

sorry, I forgot it.
