### ISSUE TITLE
How to add branch or module in the mmdet?

### ISSUE THREAD

**Issue by qq237942920** [open-mmlab/mmdetection#491]
Recently, I want to add some module and branch into the maskrcnn, but I don't know how to add it when I build the Class module or branch like Class FPN? How to add branch or module in the mmdet?

**Comment by thangvubk** [comment]
The[ technical detail](https://github.com/open-mmlab/mmdetection/blob/master/TECHNICAL_DETAILS.md) may give you some ideas.

**Comment by ZwwWayne** [comment]
This [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/new_modules.md) could help.
