### ISSUE TITLE
Add Loss Module: TypeError: forward() got an unexpected keyword argument 'avg_factor'

### ISSUE THREAD

**Issue by EchoWang99** [open-mmlab/mmdetection#4910]
I implement a new loss module based on Cross Entropy Loss. I only add extra branches and don’t change the calculation method.
Then I encountered this error:
TypeError: forward() got an unexpected keyword argument 'avg_factor'
I cant seem to figure out why 'avg_factor' become an unexpected argument.

**Error**
![image](https://user-images.githubusercontent.com/54389141/113820478-55d39c80-97ad-11eb-912a-b06b61d661c3.png)

**mycode**
![image](https://user-images.githubusercontent.com/54389141/113820793-c8447c80-97ad-11eb-812e-d2dfcfb7c76c.png)

**Comment by hhaAndroid** [comment]
Hi @EchoWang99 In addition to adding loss, what code have you modified？

**Comment by EchoWang99** [comment]
I add some code in bbox_head for some extra calculation. I doubt  it  affects subsequent loss calculations.

**Comment by hhaAndroid** [comment]
Can you provide more detailed information？
