### ISSUE TITLE
Fine tune only the classifier with my own data in ResNet50 +FPN ？

### ISSUE THREAD

**Issue by phleungae** [open-mmlab/mmdetection#4911]
Hello, 

I want to fine tune a pre trained ResNet model with my own data. However, I do not want the feature extraction part of the model got affected by my new data. Basically, I want to see the generalization power of my model when applying to different data. I did a short search online and saw that you can set “ frozen_stages = ” in the config file. May I know if I am correct if I set frozen_stages = 4. Will that serve my purpose that will only use my data to train the classifier（the fully connected layers) without changing the feature extraction part?  Thanks a lot !

**Comment by hhaAndroid** [comment]
frozen_stages can only freeze the backbone. If you want to freeze FPN, you may need to modify the FPN code.

**Comment by phleungae** [comment]
(Forget about the FPN for this moment ） Right ! if I now set frozen stage =4， does it mean I am training a new classifier only to fit my different in classes?
But if I now also want to implement FPN, which part of the code I should change/look into? Sorry I am quite new to these. Thanks again !

**Comment by hhaAndroid** [comment]
1 Yes,  frozen stage =4.
2  I check it.  If you want to freeze FPN and Head, you can achieve it by setting `optimizer.paramwise_cfg`.  For example Retianet:

```python
paramwise_cfg=dict(
        custom_keys={'neck': dict(lr_mult=0.0),'bbox_head.cls_convs' :dict(lr_mult=0.0}....)))
```

**Comment by hhhhhhx** [comment]
> 1 Yes, frozen stage =4.
> 2 I check it. If you want to freeze FPN and Head, you can achieve it by setting `optimizer.paramwise_cfg`. For example Retianet:
> 
> ```python
> paramwise_cfg=dict(
>         custom_keys={'neck': dict(lr_mult=0.0),'bbox_head.cls_convs' :dict(lr_mult=0.0}....)))
> ```

@hhaAndroid  Could you introduce the details of the implementation of freezing other structures in Faster RCNN(like freeze RPN and Head), I want to freeze all the parameters except the box classifier and the box regressor while training Faster RCNN(to implement the method of this paper https://arxiv.org/abs/2003.06957 ), how could I do？Look forward to your kind advice, thanks.

**Comment by DuckJ** [comment]
> 1 Yes, frozen stage =4.
> 2 I check it. If you want to freeze FPN and Head, you can achieve it by setting `optimizer.paramwise_cfg`. For example Retianet:
> 
> ```python
> paramwise_cfg=dict(
>         custom_keys={'neck': dict(lr_mult=0.0),'bbox_head.cls_convs' :dict(lr_mult=0.0}....)))
> ```
@hhhhhhx @hhaAndroid 
Is it work? anyone can tell me. thanks

**Comment by fengxijia** [comment]
> 1 Yes, frozen stage =4. 2 I check it. If you want to freeze FPN and Head, you can achieve it by setting `optimizer.paramwise_cfg`. For example Retianet:
> 
> ```python
> paramwise_cfg=dict(
>         custom_keys={'neck': dict(lr_mult=0.0),'bbox_head.cls_convs' :dict(lr_mult=0.0}....)))
> ```

Hi, thanks for your resolution! I encountered this problem when I set the frozen_stage to 4: 'ResNet' object has no attribute 'layer4'. My part of the modification in my config file is:

```
model = dict(
    pretrained=None,
    backbone=dict(
        frozen_stages=4 ## freeze 4 layers in ResNet
    ),
    roi_head=dict(
        bbox_head=dict(num_classes=20),
        mask_head=dict(num_classes=20))
    )
load_from = '... .pth'
```
the config file I inherited is mask_rcnn_r50_caffe_c4_1x_coco.py

Could you pls help me with this? I am new to this too. Thank you in advance! :)
