### ISSUE TITLE
When I trained my coco dataset, the console's logs showed the number of pictures that were not equal to the number of pictures in my json file

### ISSUE THREAD

**Issue by qiuxiaoming** [open-mmlab/mmdetection#4914]
When I trained my coco dataset, the console's logs showed the number of pictures that were not equal to the number of pictures in my json file.Curiously, when I use this training set for testing, the output of the console is equal to the number in the json file. I would like to ask what may be the cause of this situation. Did I train 6819 pictures?
json: id bteween 1-6819
![image](https://user-images.githubusercontent.com/55471067/113868376-3145e780-97e2-11eb-817e-5e3442f22364.png)
console:6777 samples_per_gpu=1 only use 1 gpu
![image](https://user-images.githubusercontent.com/55471067/113868543-5f2b2c00-97e2-11eb-8244-af159b1bdeb0.png)
use rcnn detection 
Thanks a lot.

**Comment by hhaAndroid** [comment]
Hi, @qiuxiaoming  In train mode, empty gt images will be filtered.

**Comment by qiuxiaoming** [comment]
I get it.Thank you very much.
