### ISSUE TITLE
How to train MaskRCNN for only detection task? 

### ISSUE THREAD

**Issue by krishvishal** [open-mmlab/mmdetection#4915]
Is it possible to train the MaskRCNN model for only the object detection task? The dataset I'm using contains only bounding boxes. When the training is started it results in the error: 
```
TypeError: 'NoneType' object is not iterable
```
Which is expected since no masks are provided as input.

**Comment by xvjiarui** [comment]
Hi @krishvishal 
In this case, you need to use FasterRCNN.
