### ISSUE TITLE
Gray Image trainning

### ISSUE THREAD

**Issue by VincentZhao1992** [open-mmlab/mmdetection#4919]
I want to train the model with the y channel.
It means using gray image to train model.
so, how should I do?
I have already to convert my dataset into gray image,but when I trained the model, it has so many problom.
Is there a simple way to solve it?

**Comment by xvjiarui** [comment]
Hi @VincentZhao1992 
What error are you getting? Typically, most of the models are pretrained with RGB images, after you load your gray image, you may need to change it to 3-channel images.
