### ISSUE TITLE
detector models cannot download 

### ISSUE THREAD

**Issue by qingweihk** [open-mmlab/mmdetection#4920]
I have try to download models in configures/detectors, but no response.

Any help? Thanks

**Comment by ZwwWayne** [comment]
Could you tell us which model ink is not available?

**Comment by xvjiarui** [comment]
Hi @qingweihk 
Could you please provide the command you use?

**Comment by qingweihk** [comment]
> Could you tell us which model ink is not available?

Thanks, Models in configs/detectors/README.md :Results and Models part: 
the following part in the table:
DetectoRS line: Download model

**Comment by qingweihk** [comment]
> Hi @qingweihk
> Could you please provide the command you use?


Thanks, Models in configs/detectors/README.md :Results and Models part: 
the following part in the table:
DetectoRS line: Download model

**Comment by shinya7y** [comment]
Chrome blocks pth download, though it may not be related to this issue.
Left click: no response.
Right click and "Save link as...": warning, but downloadable.

**Comment by qingweihk** [comment]
> Chrome blocks pth download, though it may not be related to this issue.
> Left click: no response.
> Right click and "Save link as...": warning, but downloadable.

Thanks a lot! It works.
