### ISSUE TITLE
How to get the output of each layer?

### ISSUE THREAD

**Issue by qiuxiaoming** [open-mmlab/mmdetection#4922]
In inference stage,I want to get the output of certain layer(for example the output of rpn). Could you tell me how to do?

**Comment by xvjiarui** [comment]
Hi @qiuxiaoming 
Let's say you like to get the proposal, you need to return them in the detector https://github.com/open-mmlab/mmdetection/blob/5ebba9a9221c3f6f8754d4efe293cdcd12be8dd4/mmdet/models/detectors/two_stage.py#L198

**Comment by qiuxiaoming** [comment]
Thank you very much.I want to know if I want to compare the output of the proposal with the final output of the bbox in the inference stage, can it be achieved by registering a hook? I saw in related tutorials that hook seems to be only used in train and val stages.Or is there any other way?

**Comment by SourabhRanade** [comment]
@hhaAndroid @qiuxiaoming  was this resolved or was any workaround found?

**Comment by ZwwWayne** [comment]
In mmdet 2.x, it is hard to solve. We can try to set the proposal in the model predictions in MMDet 3.x
