### ISSUE TITLE
tensorrt in docker

### ISSUE THREAD

**Issue by hihijimin** [open-mmlab/mmdetection#4924]
Don't have tensorrt installed in docker.

Please tell me how to install tesnorrt on docker
Also please tell me the tensorrt version for install
Reference: Docker File

    ARG PYTORCH="1.6.0"
    ARG CUDA="10.1"
    ARG CUDNN="7"
    
    FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel
    
    ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
    ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
    ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
    
    RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
    
    # Install MMCV
    RUN pip install mmcv-full==latest+torch1.6.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
    
    # Install MMDetection
    RUN conda clean --all
    RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
    WORKDIR /mmdetection
    ENV FORCE_CUDA="1"
    RUN pip install -r requirements/build.txt
    RUN pip install --no-cache-dir -e .

**Comment by RunningLeon** [comment]
@hihijimin Please refer to the [doc](https://github.com/open-mmlab/mmcv/blob/master/docs/tensorrt_plugin.md) in mmcv for TensorRT version and installation
