### ISSUE TITLE
Why does not the training set size match my settings?

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#4930]
Previously I tried to train a detector on trainingSetA and validate it on validateSetA, it worked just as expected. To be specific, I set 640 training images and 160 valitating images (training: validating = 8: 2), set 'samples_per_gpu' to 2, set 'times' in 'RepeatDataset' to 1. During training I got information like 'Epoch [N][n/320]'. It was right because I had 640 training images and batch size was 2, right?

Now I am trying to train another detector on trainingSetB and validate it on validateSetB, this time I set 311 training images and 78 valitating images (same training/validating ratio as before). Again, I set 'samples_per_gpu' to 2, set 'times' in 'RepeatDataset' to 1. I am not sure what will happen if the batch size is 2 while the number of training images is an odd number. I expect to receive information like 'Epoch [N][n/155]' or 'Epoch [N][n/156]'. But what I receive is 'Epoch [N][n/147]'. Is there anything wrong with my settings?

**Comment by hhaAndroid** [comment]
The data with empty GT may be filtered, you may check it.
