### ISSUE TITLE
How calculate mAP for custom range instead of default? 

### ISSUE THREAD

**Issue by krishvishal** [open-mmlab/mmdetection#4931]
My dataset is cocodetection dataset. Right now to get a summary of model detection performance I'm using the following code.

```python
evaluation = dict(metric='bbox', interval=5, classwise=True)
```
I want to know if there is a way to change the reported mAP for each class for custom range of AP eg 0.15 to 0.5 instead of the default range.

**Comment by hhaAndroid** [comment]
Please refer to #4740
