### ISSUE TITLE
是否考虑增加脚本

### ISSUE THREAD

**Issue by lmk123568** [open-mmlab/mmdetection#4932]
提供一个自动下载数据集的脚本吧，这样不用额外找办法下载数据集并划分

**Comment by ZwwWayne** [comment]
Thanks for your suggestion, we are considering it and may decide it at the end of this month (April 30th). PRs are welcomed.

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/pull/7015
