### ISSUE TITLE
您好，关于setup.py

### ISSUE THREAD

**Issue by lmk123568** [open-mmlab/mmdetection#4933]
针对`python setup.py develop`这个代码，每次改动源代码都要运行一次吗，如果我写好新的模型分享给别人，别人新电脑也要重新运行上述代码吗，还是要删除某些文件，文档让人有点绕

**Comment by lmk123568** [comment]
如果能回复我问题，将不胜感激

**Comment by ZwwWayne** [comment]
If you did not add CUDA op, you do not need to rebuild it every modification. If you share it with others, they should rebuild it.

**Comment by ZwwWayne** [comment]
BTW, could you tell us which line in the documentation that confuses you?

**Comment by lmk123568** [comment]
> If you did not add CUDA op, you do not need to rebuild it every modification. If you share it with others, they should rebuild it.

cuda op不是很懂，电脑就安装了cuda10.2就没动cuda相关的东西也不更新升级，是不是只要编译一次setup.py就可以了，只要不改cuda相关的东西就不用重新编译是吗。如果我把东西要分享给别人，我怎么才能删掉（删干净）本机编译的文件好让代码架构整洁一点

**Comment by lmk123568** [comment]
> BTW, could you tell us which line in the documentation confuses you?

主要是如果要做一个小型验证，比如复现某个论文，显卡资源不够就要用VOC快速看效果，但是官方教程前面部分对voc讲的比较少，基本都是以coco为主，这一点解决办法只能是看别人的博客，期待voc教程能上到官方教程，同时也希望能出一个中文版文档，对国内英语不好的开发者是一个福利

**Comment by ZwwWayne** [comment]
> > If you did not add CUDA op, you do not need to rebuild it every modification. If you share it with others, they should rebuild it.
> 
> cuda op不是很懂，电脑就安装了cuda10.2就没动cuda相关的东西也不更新升级，是不是只要编译一次setup.py就可以了，只要不改cuda相关的东西就不用重新编译是吗。如果我把东西要分享给别人，我怎么才能删掉（删干净）本机编译的文件好让代码架构整洁一点

yes. Just delete build/*

**Comment by ZwwWayne** [comment]
> > BTW, could you tell us which line in the documentation confuses you?
> 
> 主要是如果要做一个小型验证，比如复现某个论文，显卡资源不够就要用VOC快速看效果，但是官方教程前面部分对voc讲的比较少，基本都是以coco为主，这一点解决办法只能是看别人的博客，期待voc教程能上到官方教程，同时也希望能出一个中文版文档，对国内英语不好的开发者是一个福利

We will release Chinese documentation in the future.

**Comment by lmk123568** [comment]
> 
> 
> > > BTW, could you tell us which line in the documentation confuses you?
> > 
> > 
> > 主要是如果要做一个小型验证，比如复现某个论文，显卡资源不够就要用VOC快速看效果，但是官方教程前面部分对voc讲的比较少，基本都是以coco为主，这一点解决办法只能是看别人的博客，期待voc教程能上到官方教程，同时也希望能出一个中文版文档，对国内英语不好的开发者是一个福利
> 
> We will release Chinese documentation in the future.

十分感谢回复，对于新手刚接触mmdet时候，因为大概不可能一上来就下载coco，太大了，更多会考虑下载voc，但是根据官方教程走的时候，改动代码比如改动`--eval mAP`（官方教程说这个会用到voc数据集），实际上新手可能不知道还要改config文件，毕竟对于新手来说不会一上来就啃各种配置文件，只想跑一次模型试验一下增强信心

**Comment by hhaAndroid** [comment]
> > > > BTW, could you tell us which line in the documentation confuses you?
> > > 
> > > 
> > > 主要是如果要做一个小型验证，比如复现某个论文，显卡资源不够就要用VOC快速看效果，但是官方教程前面部分对voc讲的比较少，基本都是以coco为主，这一点解决办法只能是看别人的博客，期待voc教程能上到官方教程，同时也希望能出一个中文版文档，对国内英语不好的开发者是一个福利
> > 
> > 
> > We will release Chinese documentation in the future.
> 
> 十分感谢回复，对于新手刚接触mmdet时候，因为大概不可能一上来就下载coco，太大了，更多会考虑下载voc，但是根据官方教程走的时候，改动代码比如改动`--eval mAP`（官方教程说这个会用到voc数据集），实际上新手可能不知道还要改config文件，毕竟对于新手来说不会一上来就啃各种配置文件，只想跑一次模型试验一下增强信心

Perhaps we could provide a very small subset of coco for people to use directly. 
.

**Comment by AronLin** [comment]
At the bottom of https://mmdetection.readthedocs.io/en/latest/get_started.html#installation, there is a note.

Note:
a. Following the above instructions, MMDetection is installed on dev mode, any local modifications made to the code will take effect without the need to reinstall it.
