### ISSUE TITLE
No such file or directory '/content/mmdetection_object_detection_demo/data/VOCdevkit/VOC2007/Annotations/mapper.xml'

### ISSUE THREAD

**Issue by Tanmaypal** [open-mmlab/mmdetection#4935]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Tanmaypal** [comment]
Traceback (most recent call last):
  File "/content/mmdetection_object_detection_demo/mmdetection/tools/train.py", line 187, in <module>
    main()
  File "/content/mmdetection_object_detection_demo/mmdetection/tools/train.py", line 183, in main
    meta=meta)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/apis/train.py", line 140, in train_detector
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: VOCDataset: [Errno 2] No such file or directory: '/content/mmdetection_object_detection_demo/data/VOCdevkit/VOC2007/Annotations/mapper.xml'

**Comment by jshilong** [comment]
Please check whether you run the command in a correct work directory

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
