### ISSUE TITLE
Using image_demo.py on the colab encountered a problem that the image of the detection result could not be found

### ISSUE THREAD

**Issue by Cloudyunn** [open-mmlab/mmdetection#4938]
1、After training my voc data set, I tried to use image_demo.py to detect images and output the results. :

!python demo/image_demo.py demo/inclusion_94.jpg configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py Faster/latest.pth 

Use load_from_local loader
/usr/local/lib/python3.7/dist-packages/mmdet/datasets/utils.py:68: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
<Figure size 200.01x200.01 with 1 Axes>

The execution process did not seem to encounter problems, but the detection result images were not found.
I checked mmdet.api again and found that the api used by image_demo.py is show_result_pyplot.:

**from mmdet.apis import inference_detector, init_detector, show_result_pyplot**

It seems that matplotlib can only support local. In this case, how can I modify the api to save the picture of my test results on the colab?

2、In the process of image detection using image_demo.py, I didn't  see the FPS parameter. How can I display the detection speed of the model in mmdet?

**Comment by jshilong** [comment]
Sorry for the late respondence, you can save the visualized images with arguments `--show-dir`, you can refer to https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#examples
