### ISSUE TITLE
FASTERRCNN: __init__() got an unexpected keyword argument 'bbox_roi_extractor'..

### ISSUE THREAD

**Issue by Tanmaypal** [open-mmlab/mmdetection#4944]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Tanmaypal** [comment]
for this i have tried converting the model version from 1 to 2 but for that also I am facing this following issue..

Traceback (most recent call last):
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 209, in <module>
    main()
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 205, in main
    convert(args.in_file, args.out_file, args.num_classes)
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 126, in convert
    '#' + meta_info['config'])
  File "/content/mmdetection/tools/model_converters/upgrade_model_version.py", line 36, in parse_config
    elif isinstance(config.model['bbox_head'], list):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 32, in __missing__
    raise KeyError(name)
KeyError: 'bbox_head'

**Comment by Tanmaypal** [comment]
plz help reslove this

**Comment by jshilong** [comment]
Is there any modification about the config?

**Comment by jshilong** [comment]
Seems the reason is the unreasonable modifications of config. Feel free to reopen the issue if there is any question
