### ISSUE TITLE
单机多卡训练时多个数据实例导致内存爆满问题

### ISSUE THREAD

**Issue by houjun0322** [open-mmlab/mmdetection#4946]
【背景】
我使用tools/dist_train.sh进行多卡训练（比如4卡），启动训练后会创建4个数据实例，即每一张卡对应一个数据实例。这对于相对比较小的数据集是没有什么问题。当我训练比较大的数据集，如Objects365，创建四个数据实例会导致内存爆满。

【问题】
为什么单机上的多卡不能共享一个数据实例？或者如何设置以防止内存爆炸

**Comment by jshilong** [comment]
Sorry for the late reply,
When you do the distributed training and set more than one works in a data loader, there are round `num_rank` * `num_works` dataset copies, because the JSON of object365 is quite big,  so many copies of the dataset would cause oom. 
A temporary solution is to set a smaller number of `num_works` of data loader, but this may slow down the training speed.

**Comment by jshilong** [comment]
We would support large dataset training in the near future.
Maybe  2.14 or 2.15

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by chenxu93** [comment]
我也遇到了这个问题，比较疑惑是为什么多个gpu 不能共享一个dataloader？detectron2 看起来是多个gpu 共享一个dataloader，内存消耗差了很多倍。

**Comment by chenxu93** [comment]
@jshilong

**Comment by houjun0322** [comment]
> Sorry for the late reply, When you do the distributed training and set more than one works in a data loader, there are round `num_rank` * `num_works` dataset copies, because the JSON of object365 is quite big, so many copies of the dataset would cause oom. A temporary solution is to set a smaller number of `num_works` of data loader, but this may slow down the training speed.

thanks you for your reply

**Comment by chenxu93** [comment]
> We would support large dataset training in the near future. Maybe version2.14 or version2.15

hi， does mmdet support big dataset training now?

**Comment by wywywy01** [comment]
> We would support large dataset training in the near future. Maybe version2.14 or version2.15

Hi, is these any plan to do this?

**Comment by feiyutalk** [comment]
> We would support large dataset training in the near future. Maybe version2.14 or version2.15

Hi, is these any plan to do this?

**Comment by Napier7** [comment]
除了可以尝试降低num_workers外（当然也会降低训练速度），还可以在训练配置文件中删除验证集配置以防止加载，这会节省一点内存
