### ISSUE TITLE
yolov3 pytorch2onnx failed, mmdet=2.11.0, MMCV: 1.3.0,PyTorch: 1.8.1

### ISSUE THREAD

**Issue by qinxianglinya** [open-mmlab/mmdetection#4948]
collect_env
sys.platform: win32
Python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: TITAN X (Pascal)
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
NVCC: Not Available
GCC: n/a
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.4, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.9.1
OpenCV: 4.5.1
MMCV: 1.3.0
MMCV Compiler: MSVC 191627042
MMCV CUDA Compiler: 10.0
MMDetection: 2.11.0+5ebba9a

**Comment by qinxianglinya** [comment]
D:\miniconda\envs\mmlab\python.exe C:/Users/dc/Desktop/mmdetection/tools/deployment/pytorch2onnx.py ../../configs/yolo/yolov3_d53_mstrain-608_273e_coco.py ../../checkpoints/yolov3_608.pth --input-img ../../demo/demo.jpg --verify --test-img ../../demo/demo.jpg
Use load_from_local loader
Use load_from_local loader
C:\Users\dc\Desktop\mmdetection\mmdet\models\dense_heads\yolo_head.py:251: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cfg.get('nms_pre', -1), device=device, dtype=torch.long)
C:\Users\dc\Desktop\mmdetection\mmdet\core\bbox\coder\yolo_bbox_coder.py:72: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
C:\Users\dc\Desktop\mmdetection\mmdet\core\bbox\coder\yolo_bbox_coder.py:73: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(-1) == bboxes.size(-1) == 4
C:\Users\dc\Desktop\mmdetection\mmdet\models\dense_heads\yolo_head.py:283: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nms_pre_tensor > 0 and (torch.onnx.is_in_onnx_export()
C:\Users\dc\Desktop\mmdetection\mmdet\models\dense_heads\yolo_head.py:290: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  _, topk_inds = conf_pred.topk(nms_pre)
C:\Users\dc\Desktop\mmdetection\mmdet\models\dense_heads\yolo_head.py:318: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if with_nms and (batch_mlvl_conf_scores.size(0) == 0):
D:\miniconda\envs\mmlab\lib\site-packages\torch\tensor.py:590: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
C:\Users\dc\Desktop\mmdetection\mmdet\core\post_processing\bbox_nms.py:36: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] > 4:
D:\miniconda\envs\mmlab\lib\site-packages\mmcv\ops\nms.py:269: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
D:\miniconda\envs\mmlab\lib\site-packages\mmcv\ops\nms.py:277: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if boxes_for_nms.shape[0] < split_thr or torch.onnx.is_in_onnx_export():
D:\miniconda\envs\mmlab\lib\site-packages\mmcv\ops\nms.py:132: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
D:\miniconda\envs\mmlab\lib\site-packages\mmcv\ops\nms.py:133: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
Traceback (most recent call last):
  File "C:/Users/dc/Desktop/mmdetection/tools/deployment/pytorch2onnx.py", line 245, in <module>
    cfg_options=args.cfg_options)
  File "C:/Users/dc/Desktop/mmdetection/tools/deployment/pytorch2onnx.py", line 57, in pytorch2onnx
    opset_version=opset_version)
  File "D:\miniconda\envs\mmlab\lib\site-packages\torch\onnx\__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "D:\miniconda\envs\mmlab\lib\site-packages\torch\onnx\utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "D:\miniconda\envs\mmlab\lib\site-packages\torch\onnx\utils.py", line 701, in _export
    dynamic_axes=dynamic_axes)
  File "D:\miniconda\envs\mmlab\lib\site-packages\torch\onnx\utils.py", line 468, in _model_to_graph
    module=module)
  File "D:\miniconda\envs\mmlab\lib\site-packages\torch\onnx\utils.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "D:\miniconda\envs\mmlab\lib\site-packages\torch\onnx\__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\miniconda\envs\mmlab\lib\site-packages\torch\onnx\utils.py", line 997, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "D:\miniconda\envs\mmlab\lib\site-packages\mmcv\onnx\symbolic.py", line 17, in symbolic_fn
    g, interpolate_mode, args)
  File "D:\miniconda\envs\mmlab\lib\site-packages\mmcv\onnx\onnx_utils\symbolic_helper.py", line 267, in _get_interpolate_attributes
    scales = _interpolate_get_scales_if_available(g, scales)
  File "D:\miniconda\envs\mmlab\lib\site-packages\mmcv\onnx\onnx_utils\symbolic_helper.py", line 234, in _interpolate_get_scales_if_available
    scales[0], scale_desc) != -1 and not _is_none(scales[0])
  File "D:\miniconda\envs\mmlab\lib\site-packages\mmcv\onnx\onnx_utils\symbolic_helper.py", line 66, in _maybe_get_const
    return _parse_arg(value, desc)
  File "D:\miniconda\envs\mmlab\lib\site-packages\mmcv\onnx\onnx_utils\symbolic_helper.py", line 33, in _parse_arg
    return float(tval)
ValueError: only one element tensors can be converted to Python scalars

**Comment by qinxianglinya** [comment]
it works when i try to transform retinanet and faster rcnn to onnx. but yolov3 failed.

**Comment by RunningLeon** [comment]
@qinxianglinya Please refer to our [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md). Currently, we only tested the listed model with PyTorch==1.6.0.

**Comment by qinxianglinya** [comment]
> @qinxianglinya请参阅我们的[教程](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md)。目前，我们仅在PyTorch == 1.6.0的情况下测试了列出的模型。

ok, thank you for your reply.
