### ISSUE TITLE
yolo class number issue 

### ISSUE THREAD

**Issue by calvin886** [open-mmlab/mmdetection#4955]
@xvjiarui please help
The class number of my dataset is 21. 

Do I need to add one more class `'0'`as my background during the training time like this?
<img width="525" alt="截屏2021-04-13 下午3 52 51" src="https://user-images.githubusercontent.com/46655164/114516790-5027fc00-9c70-11eb-939f-71d2cd8f7fd2.png">

**Comment by hhaAndroid** [comment]
no need!
