### ISSUE TITLE
how can I get the probability of the categories in each bbox?

### ISSUE THREAD

**Issue by qiuxiaoming** [open-mmlab/mmdetection#4957]
When I use cascade rcnn inference, how do I get the probability of the categories in each bbox.`in image_demo.py results = inference_detector (model, args.img)`. But this result contains only the probability values for the category with the highest probability in the final bbox. I interrupted the code that entered the inference process and did not find the returned interface

**Comment by hhaAndroid** [comment]
Sorry, Not supported for now.

**Comment by qiuxiaoming** [comment]
thanks for your reply.
