### ISSUE TITLE
How can I change the number of proposals for each graph output during the test?

### ISSUE THREAD

**Issue by Snowstorm0** [open-mmlab/mmdetection#496]
How can I change the number of proposals for each graph output during the test?
How is the output effect in the paper achieved?
![1234](https://user-images.githubusercontent.com/37918479/56117484-bc48ca00-5f9a-11e9-9e71-3a816cd56327.png)

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/configs/rpn_r50_fpn_1x.py#L51

**Comment by Snowstorm0** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/configs/rpn_r50_fpn_1x.py#L51

Thank you for helping me solve this problem.

**Comment by yojayc** [comment]
How to change the number of proposals in the latest version?
I found rpn_r50_fpn_1x.py in https://github.com/open-mmlab/mmdetection/blob/master/configs/rpn/rpn_r50_fpn_1x_coco.py, but it doesn't have line 51
