### ISSUE TITLE
Bug with VOC training dataset?

### ISSUE THREAD

**Issue by wongsinglam** [open-mmlab/mmdetection#4962]
Hi, I got one interesting thing. 

When I use dataset = build_dataset(cfg.data.train) to build my voc 2007 training dataset and print one sample, 'gt_labels' sometimes have different values. I am not sure if it is bug or not. 

here I print dataset[0]:
{'img_metas': DataContainer({'filename': 'data/VOCdevkit/VOC2007/JPEGImages/000005.jpg', 'ori_filename': 'JPEGImages/000005.jpg', 'ori_shape': (375, 500, 3), 'img_shape': (600, 800, 3), 'pad_shape': (608, 800, 3), 'scale_factor': array([1.6, 1.6, 1.6, 1.6], dtype=float32), 'flip': False, 'flip_direction': None, 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}}),
 'img': DataContainer(tensor([[[-1.9467, -1.9295, -1.8953,  ...,  0.6563,  0.6392,  0.6392],
          [-1.9980, -1.9809, -1.9467,  ...,  0.6563,  0.6563,  0.6563],
          [-2.0152, -2.0152, -1.9809,  ...,  0.6734,  0.6734,  0.6734],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[-1.8606, -1.8431, -1.8081,  ...,  1.2381,  1.2206,  1.2206],
          [-1.9132, -1.8782, -1.8431,  ...,  1.2381,  1.2381,  1.2381],
          [-1.9132, -1.8957, -1.8606,  ...,  1.2556,  1.2556,  1.2556],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[-1.6302, -1.6127, -1.5779,  ...,  1.5768,  1.5594,  1.5594],
          [-1.6650, -1.6476, -1.6127,  ...,  1.5768,  1.5768,  1.5768],
          [-1.6476, -1.6476, -1.6302,  ...,  1.5942,  1.5942,  1.5942],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]])),
 **'gt_bboxes': DataContainer(tensor([[419.2000, 336.0000, 516.8000, 540.8000],
         [262.4000, 420.8000, 403.2000, 593.6000],
         [384.0000, 308.8000, 470.4000, 476.8000]])),**
 'gt_labels': DataContainer(tensor([8, 8, 8]))}

But sometimes it become:

{'img_metas': DataContainer({'filename': 'data/VOCdevkit/VOC2007/JPEGImages/000005.jpg', 'ori_filename': 'JPEGImages/000005.jpg', 'ori_shape': (375, 500, 3), 'img_shape': (600, 800, 3), 'pad_shape': (608, 800, 3), 'scale_factor': array([1.6, 1.6, 1.6, 1.6], dtype=float32), 'flip': True, 'flip_direction': 'horizontal', 'img_norm_cfg': {'mean': array([123.675, 116.28 , 103.53 ], dtype=float32), 'std': array([58.395, 57.12 , 57.375], dtype=float32), 'to_rgb': True}}),
 'img': DataContainer(tensor([[[ 0.6392,  0.6392,  0.6563,  ..., -1.8953, -1.9295, -1.9467],
          [ 0.6563,  0.6563,  0.6563,  ..., -1.9467, -1.9809, -1.9980],
          [ 0.6734,  0.6734,  0.6734,  ..., -1.9809, -2.0152, -2.0152],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 1.2206,  1.2206,  1.2381,  ..., -1.8081, -1.8431, -1.8606],
          [ 1.2381,  1.2381,  1.2381,  ..., -1.8431, -1.8782, -1.9132],
          [ 1.2556,  1.2556,  1.2556,  ..., -1.8606, -1.8957, -1.9132],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 1.5594,  1.5594,  1.5768,  ..., -1.5779, -1.6127, -1.6302],
          [ 1.5768,  1.5768,  1.5768,  ..., -1.6127, -1.6476, -1.6650],
          [ 1.5942,  1.5942,  1.5942,  ..., -1.6302, -1.6476, -1.6476],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]])),
 **'gt_bboxes': DataContainer(tensor([[283.2000, 336.0000, 380.8000, 540.8000],
         [396.8000, 420.8000, 537.6000, 593.6000],
         [329.6000, 308.8000, 416.0000, 476.8000]])),**
 'gt_labels': DataContainer(tensor([8, 8, 8]))}

Anyone can explain this change? Thanks

**Comment by wongsinglam** [comment]
Hi, anyone meets the same problems as me?

**Comment by BIGWangYuDong** [comment]
Maybe due to `'flip': True.` only and xmin and xmax change.

 'gt_bboxes': DataContainer(tensor([[419.2000, 336.0000, 516.8000, 540.8000],
[262.4000, 420.8000, 403.2000, 593.6000],
[384.0000, 308.8000, 470.4000, 476.8000]])),
&
'gt_bboxes': DataContainer(tensor([[283.2000, 336.0000, 380.8000, 540.8000],
[396.8000, 420.8000, 537.6000, 593.6000],
[329.6000, 308.8000, 416.0000, 476.8000]])),

**Comment by BIGWangYuDong** [comment]
Feel free to reopen thiif you still meet this problem
