### ISSUE TITLE
I am confused about func “_get_targets_single” in anchor_head when i use SSD;

### ISSUE THREAD

**Issue by zj19921221** [open-mmlab/mmdetection#4963]
hi 
I am confused about func “_get_targets_single” in anchor_head when i use SSD;
when i run this func, i found the shape of created label is not match the predict featuremap size;
the wrong tips show as below:
"Expected input batch_size (21896) to match target batch_size (21856)"
the reason of ”21856“ is the code 
"
        inside_flags = anchor_inside_flags(flat_anchors, valid_flags, img_meta['img_shape'][:2], self.train_cfg.allowed_border)
        anchors = flat_anchors[inside_flags, :]
"
the inside_flag is not all true;

could you please give me some help！

**Comment by ZwwWayne** [comment]
It is normal that the `inside_flag` is not all true because some anchors is out of the real image sizes and should be ignored.
