### ISSUE TITLE
about the way of initializing weight in FPN

### ISSUE THREAD

**Issue by HulioZhao** [open-mmlab/mmdetection#4965]
I wonder why using different initializing function in FPN and in BBOX_HEAD.
I intend to train a normal faster_rcnn model.
In FPN(mmdet/necks/fpn.py), the way of initializing weight is using mmcv.cnn.xavier_init. 
![image](https://user-images.githubusercontent.com/40555727/114810560-f09c2e80-9dde-11eb-8641-014415e86a84.png)

However in BBOX_HEAD, the way of initializing weight is using torch.nn.init.xavier_uniform_.
![image](https://user-images.githubusercontent.com/40555727/114810582-f7c33c80-9dde-11eb-8f06-1e2c4d8f316f.png)

this difference in initializing weight confuse me a lot because when I do baseline faster-rcnn experiments, it seems that choosing which initializing method in FPN can influence results a lot.

**Comment by HulioZhao** [comment]
I did two experiments to see how initilizing method can influence the results. One is using torch.nn.init.xavier_uniform_, other one is using mmcv.cnn.xavier.
![image](https://user-images.githubusercontent.com/40555727/114810949-b67f5c80-9ddf-11eb-944f-16238a2bc5c3.png)
For each initializing method I run experiments 5 times and report its highest, lowets and mean results.
For mmcv.cnn.xavier 
![image](https://user-images.githubusercontent.com/40555727/114811023-e62e6480-9ddf-11eb-9327-20d906a019c5.png)
For torch.nn.xavier_init
![Uploading image.png…]()

**Comment by hhaAndroid** [comment]
There is a problem with your writing, `xavier_init('uniform') `should be the same as `nn.init.xavier_uniform_`  not `nn.init.xavier_normal_`

**Comment by HulioZhao** [comment]
> There is a problem with your writing, `xavier_init('uniform') `should be the same as `nn.init.xavier_uniform_` not `nn.init.xavier_normal_`

sorry my bad, according to my experiments, In my problem setting, using xavier_normal init can lead to a higher result of ~5-10% compared to xavier_uniform, both in baseline and my method.
This problem may only occurs in mmdetection=2.6.0 and mmcv==1.1.5
![image](https://user-images.githubusercontent.com/40555727/115165900-d1edae80-a0e2-11eb-8a41-4269e4ff612f.png)
