### ISSUE TITLE
new mmdet dependency does not support windows

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmdetection#4970]
The official [pycocotools does not provide windows support](https://github.com/cocodataset/cocoapi/issues/9#issuecomment-217339740) because of this line in [setup.py](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/setup.py#L12), how to use mmdetection on windows after [this pr](https://github.com/open-mmlab/mmdetection/pull/4939)?

**Comment by hhaAndroid** [comment]
If mmpycocotools can be installed successfully, I think pycocotools can also be used, because mmpycocotools simply wraps pycocotools.

**Comment by fcakyon** [comment]
@hhaAndroid it is not true. Please compare this line in [pycocotools](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/setup.py#L12) and [mmpycocotools](https://github.com/open-mmlab/cocoapi/blob/01f805cd54d7bd7af64c0fbd5fd96d8ca0b9ddc9/pycocotools/setup.py#L16).

mmpycocotools fixes windows installation bug of original pycocotools by commenting out that line in setup.py.

**Comment by fcakyon** [comment]
[With this commit](https://github.com/open-mmlab/cocoapi/commit/d234b096b49a578c490ff5ff6dcec46072bdf68a#diff-95916459f8bea3fdc60020ed4aac945b84aee8f0a957e865604e112161cc4cde), @xvjiarui fixed windows installation bug of the original pycocotools repo.

**Comment by hhaAndroid** [comment]
> [With this commit](https://github.com/open-mmlab/cocoapi/commit/d234b096b49a578c490ff5ff6dcec46072bdf68a#diff-95916459f8bea3fdc60020ed4aac945b84aee8f0a957e865604e112161cc4cde), @xvjiarui added windows installation support to mmpycocotools, before that it was not possible to install mmdet on windows.

OK, Thank you. I will confirm it.
