### ISSUE TITLE
mmdet cannot train with single class dataset

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmdetection#4971]
Since PR https://github.com/open-mmlab/mmdetection/pull/4508, single class training has been broken.

I create a new dataset class as:

```python
from .builder import DATASETS
from .coco import CocoDataset


@DATASETS.register_module()
class NewCocoDataset(CocoDataset):

    CLASSES = ('uav')
```

Then when i start training with ssd512 config, i get this error:

```bash
The `num_classes` (1) in SSDHead of MMDataParallel does not matches the length of `CLASSES` 3) in NewCocoDataset
  File "mmdetection\mmdet\datasets\utils.py", line 136, in _check_head
    assert module.num_classes == len(dataset.CLASSES), \
```

**Comment by shinya7y** [comment]
Does `CLASSES = ('uav', )` work?
https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/mmdet/datasets/wider_face.py#L17

**Comment by fcakyon** [comment]
@shinya7y yes that works, maybe we can add a warning that tells to add a semicolon at the end, for the single class case.

**Comment by ZwwWayne** [comment]
> @shinya7y yes that works, maybe we can add a warning that tells to add a semicolon at the end, for the single class case.

I agree with this warning. We may do that in PR #4973.

**Comment by fcakyon** [comment]
@ZwwWayne i updated #4973
