### ISSUE TITLE
TypeError: HybridTaskCascade: __init__() got an unexpected keyword argument 'num_stages'

### ISSUE THREAD

**Issue by hanlanqian** [open-mmlab/mmdetection#4976]
why "num_stages" is an unexpected keyword argument in builid function?

I'm trying to make research on vehicle re-id program, but the error vanished in the following code:
```
    if isinstance(cfg, list):
        modules = [
            build_from_cfg(cfg_, registry, default_args) for cfg_ in cfg
        ]
        return nn.Sequential(*modules)
    else:
        return build_from_cfg(cfg, registry, default_args)
```
and the model setting is:
```
model = dict(
    type='HybridTaskCascade',
    num_stages=3,
    pretrained='open-mmlab://resnext101_64x4d',
    interleaved=True,
    mask_info_flow=True,
    backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=64,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch',
        dcn=dict(
            type='DCN',
            groups=64,
            deformable_groups=1,
            fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True)),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
......
```

**Comment by chienkan** [comment]
Think i've met the same situation, and I found that "num_stages" had been moved to be a keyword of roi_heads in the 2.x version. 
For example, you can find "num_stages" as a key of "CascadeRoIHead" in [this config](https://github.com/open-mmlab/mmdetection/blob/v2.11.0/configs/_base_/models/cascade_rcnn_r50_fpn.py), and the corresponding implementation of passing the value of "num_stages" can be exactly found in [this file](https://github.com/open-mmlab/mmdetection/blob/v2.11.0/mmdet/models/roi_heads/cascade_roi_head.py), which is copied from [the implementation](https://github.com/open-mmlab/mmdetection/blob/v1.2.0/mmdet/models/detectors/cascade_rcnn.py) of the 1.x version. 
Hope this will help.
