### ISSUE TITLE
pip install mmdet failed (cause of failed install mmpycocotools)

### ISSUE THREAD

**Issue by haoran1062** [open-mmlab/mmdetection#4987]
https://github.com/open-mmlab/mmocr/issues/79
detail here

**Comment by hhaAndroid** [comment]
You can consider using the latest version of mmdet, no need to install mmpycocotools.

**Comment by lsm140** [comment]
But with the latest version of mmdet installed, wouldn't an old project based on mmcv==1.0.5 not run?

**Comment by lsm140** [comment]
> > But with the latest version of mmdet installed, wouldn't an old project based on mmcv==1.0.5 not run?
> 
> have you solve the problem with failing to build mmpycocotools, when you pip install mmdet

My installation of mmpycocotools was unsuccessful, so I later installed pycocotools and manually changed the in-file mmpycocotools api to the pycocotools api. e.g., get_cat_ids ---> getCatIds.
get_img_ids ---> getImgIds.
cat_names ---> catNms.
load_imgs ---> loadImgs.
load_anns ---> loadAnns.
get_anno_ids(img_ids=) ----> getAnnIds(imgIds=). It worked.
