### ISSUE TITLE
how to preprocess image using pytorch only but mmcv ？

### ISSUE THREAD

**Issue by Bruno-bai** [open-mmlab/mmdetection#4988]
i have converted the mmdet trained model into onnx, how to  preprocess image to feed to the onnx model using pytorch transform or using onnx c++ preprocessing?

**Comment by RunningLeon** [comment]
@Bruno-bai You could take the model config file as the reference to preprocess an input image, which may include: resize, padding, minus mean values and multiply mean scales.
