### ISSUE TITLE
`ModuleNotFoundError: No module named 'mmcv._ext'` 

### ISSUE THREAD

**Issue by SamMohel** [open-mmlab/mmdetection#4991]
i got this error while i install mmcv 
    
`f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.1 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.`

i used 
`git clone https://github.com/open-mmlab/mmcv.git`
`cd mmcv` 
`MMCV_WITH_OPS=1`
`python3 -m pip install -e .`

then i re-install then mmcv and used `pip install mmcv==1.2.7`
and got 
`ModuleNotFoundError: No module named 'mmcv._ext'` 

I have cuda 11.0

**Comment by PCRKTY** [comment]
same problem.
did you solve it? @SamMohel

**Comment by ZwwWayne** [comment]
You need to checkout to a tag and then compile MMCV, e.g., v1.2.9.
Or you can install mmcv following the instruction [here](https://github.com/open-mmlab/mmcv#installation).

**Comment by lijain** [comment]
I am a cuda11.1.  PIP install mmcv-full does not work.  Using the compiled source code, download MMCV after compiling, also reported this error. Here's my environment, Please guide me
![image](https://user-images.githubusercontent.com/18046568/128437242-1dd808d9-1d11-4edd-a0ef-61ff267ba8c2.png)
