### ISSUE TITLE
weight size error，help！

### ISSUE THREAD

**Issue by zhxngjxnhxx** [open-mmlab/mmdetection#4997]
When I was training another model, there was a problem that the pre-trained mmdet weight size did not match the model size.
like this：RuntimeError: The expanded size of the tensor (16) must match the existing size (81) at non-singleton dimension 0.  Target sizes: [16, 1024].  Tensor sizes: [81, 1024]
 I asked the original author of the code. He pointed out that the model configuration does not match the weight. How can I get  the pre-training weights of the specified size,  I am a noob, or there is only one size for the pre-training weights of the specified name?

**Comment by ZwwWayne** [comment]
You might need to modify the num_classes in the head to be 16.
