### ISSUE TITLE
How can I eval myself dataset

### ISSUE THREAD

**Issue by shuoshuoa** [open-mmlab/mmdetection#500]
I have added Kitti Dataset to mmdetection. But how can i eval pretrained model. I found the code only reference coco_eval. What should i modify? Thank you for reply.
![image](https://user-images.githubusercontent.com/15209384/56196396-52e3bc80-6069-11e9-9675-532cb86fc673.png)

**Comment by OceanPang** [comment]
@shuoshuoa We recommend you to convert the KITTI annotation to COCO style. In that case, you can train and evaluate the model in this codebase conveniently. And then revert the results to the format KITTI needed and upload it to the official website. 
You can also add your evaluation tools into the code directly. Just add another eval choice, such as 'kitti'.

**Comment by shuoshuoa** [comment]
Thanks very much. i got it!
