### ISSUE TITLE
When I execute publish_model.py , it prompts "model"_ pickle.UnpicklingError : invalid load key, '_ '. "

### ISSUE THREAD

**Issue by ModestYjx** [open-mmlab/mmdetection#5004]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
python tools/model_converters/publish_model.py configs/experiment_fpn/experiment_BFP_BLL.py \
data/epoch_12.pth
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
yes，I deleted the IOU balanced sampling module of Libra r-cnn and got the experiment_BFP_BLL.py  .Nothing else has been changed.
3. What dataset did you use?
COCO

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
TorchVision: 0.7.0
OpenCV: 4.5.1
MMCV: 1.2.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.10.0+1253742
```

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```none
(base) root@b08d3225ea6e:/mmdetection# python tools/model_converters/publish_model.py configs/experiment_fpn/experiment_BFP_BLL.py data/epoch_12.pth
Traceback (most recent call last):
  File "tools/model_converters/publish_model.py", line 39, in <module>
    main()
  File "tools/model_converters/publish_model.py", line 35, in main
    process_checkpoint(args.in_file, args.out_file)
  File "tools/model_converters/publish_model.py", line 17, in process_checkpoint
    checkpoint = torch.load(in_file, map_location='cpu')
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '_'.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by JiaxYau** [comment]
I come across the same problem when I train FCOS. No problem when I train Faster RCNN.

**Comment by ZwwWayne** [comment]
This might because the model is saved and loaded by different version of pickle or pytorch.

**Comment by Jaykob** [comment]
I have the same problem using YoloX...
Pickle and pytorch versions are the exact same.
Any ideas?

**Comment by saadyousuf45** [comment]
> I have the same problem using YoloX... Pickle and pytorch versions are the exact same. Any ideas?

DId you fix it Jaykob?

**Comment by Jaykob** [comment]
Nope :(
