### ISSUE TITLE
Dead lock still exists in vfnet_head.py

### ISSUE THREAD

**Issue by zlin3000** [open-mmlab/mmdetection#5009]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
 Whiling training vfnet with multiple-GPU and  filter_empty_gt=False, it still possible to meet deadlock.

**Reproduction**

1. What command or script did you run?

bash dist_train.sh vfnet_config.py 8

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Yes

3. What dataset did you use?

voc+custom

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
https://github.com/open-mmlab/mmdetection/blob/a2d9047e9a3d70430011895e62764372b3780bc5/mmdet/models/dense_heads/vfnet_head.py#L428

guess should modify this line.

**Comment by hhaAndroid** [comment]
Hi @zlin3000 Thank you for your advice. I will fix it.
