### ISSUE TITLE
a problem with stand-alone multi-gpus training in dist_train.sh

### ISSUE THREAD

**Issue by qiuxiaoming** [open-mmlab/mmdetection#5010]
When I train with two gpus, the main program's print statement (my own print statement) is printed twice on the console and two processes are created, but the log is normal during training. (Log only print once and the number of pictures on a single gpu is 1137 and the number of pictures on two gpus is 619.) Could you tell me what's wrong with my setup? Will this affect my training?

**Comment by tojimahammatov** [comment]
When we train model in multi-gpu, separate model instances are created for each gpu and do forward/backward independently. It means that your code runs in each gpu independently, so whatever you print or do something all gpu do it. This will never affect your training, feel free to ignore it, unless you are okay to seem them n times. See [here](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html).

And about the log, of course it is possible to print only one time, and look through DistributedDataParallel of pytorch or MMDetectionDataParallel to see how they use for logs. Quick workaround can be something like this:
```
if gpu_index == 0:
    print("One time print") 
```

**Comment by qiuxiaoming** [comment]
I get it. Thanks a lot.
