### ISSUE TITLE
How to visualize the whole network using TensorBoardX?

### ISSUE THREAD

**Issue by wwk-png** [open-mmlab/mmdetection#5018]
How to visualize the whole network using TensorBoardX?I made a mistake by adding "add_graph" to train.py. The "img_meta" position parameter is missing.

**Comment by jshilong** [comment]
You can change the `default_runtime.py` in the _base_ config.
```
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
```

**Comment by jshilong** [comment]
Feel free to reopen it if there are any problems

**Comment by fangxu622** [comment]
#5140

**Comment by fangxu622** [comment]
Have you resolved ?

**Comment by wwk-png** [comment]
Now I can only visualize the network structure of Backbone.I think Tensorboard can only visualize structures with tensors as input and output, but a network built by MMDetection has more information than just tensors.

**Comment by fangxu622** [comment]
#5140 
update PyTorch version will resolve this problem.
when I am ready to propose changes, I found it has been changed on the master branch.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
