### ISSUE TITLE
AssertionError: RandomCenterCropPad needs the input image of dtype np.float32, please set "to_float32=True" in "LoadImageFromFile" pipeline

### ISSUE THREAD

**Issue by ElliotQi** [open-mmlab/mmdetection#5019]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```shell
./tools/dist_train.sh configs/universenet/myconfig.py 4
```
2.dataset
https://www.heywhale.com/home/competition/605ab78821e3f6003b56a7d8/submit

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /public/software/cuda10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3: Tesla V100
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.5.1
MMCV: 1.2.4
MMDetection: 2.4.0+5966cdd
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1
------------------------------------------------------------
**Error traceback**
If applicable, paste the error trackback here.
```none
ssertionError: RandomCenterCropPad needs the input image of dtype np.float32, please set "to_float32=True" in "LoadImageFromFile" pipeline
```

**my config **
```none
train_pipeline = [
    dict(type='LoadImageFromFile',to_float32=True),
    dict(
        type='LoadAnnotations', with_bbox=True, with_mask=False, with_seg=False),
    dict(type='Resize',
         img_scale = [(1333,640),(1333,672),(1333,704),(1333,736),(1333,768),(1333,800)],
         multiscale_mode='value',
         keep_ratio=True),
    # dict(
    #   type="Albu",
    #   transforms=albu_train_transforms,
    #   keymap=dict(img="image", gt_bboxes="bboxes"),
    #   update_pad_shape=False,
    #   skip_img_without_anno=True,
    #   bbox_params=dict(type="BboxParams", format="pascal_voc", label_fields=["gt_labels"], min_visibility=0.0,filter_lost_elements=True),
    #),
    # dict(type='BBoxJitter'),
    dict(type='RandomFlip', flip_ratio=0.5, direction='horizontal'),
    #dict(type='RandomFlip', flip_ratio=0.5, direction='vertical'),
    # dict(type='BBoxJitter', min=0.95, max=1.05),
    dict(type='Mosaic',img_scale=(1333, 800), min_buffer_size=4, p=0.5),
    # dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    # dict(type='Grid', use_w=True, use_h=True),
    #dict(type='FenceMask', prob=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
```

**Comment by hhaAndroid** [comment]
As the prompt says, you only need to set set "to_float32=True" in "LoadImageFromFile".

**Comment by ElliotQi** [comment]
@hhaAndroid As you see in my config file, I set "to_float32=True"

**Comment by hhaAndroid** [comment]
I did not see that you used RandomCenterCropPad from the configuration you provided.
