### ISSUE TITLE
How to train with negative samples

### ISSUE THREAD

**Issue by PauloFavero** [open-mmlab/mmdetection#5020]
Hi,

I am using mmdetection to train mask-rcnn model and point rend models, My dataset has 13 classes plus the background.
My objects are somehow similar to trees and for this reason, I am getting a lot of false positives. I would like to know if it's possible to add negative samples to the training dataset.  Negative samples are images without labels. Adding a bunch of images of trees with empty labels would help my model to understand that is not an object. Does mmdetection have support for images with empty labels in the dataset? How is it handled?

I use COCO-style annotations for the images, saved in JSON format.

The Yolo_Darknet has support for this feature as can be seen [here](https://github.com/AlexeyAB/darknet#how-to-improve-object-detection).

**Comment by hhaAndroid** [comment]
Hi, Currently supports empty gt scene and you can set `filter_empty_gt=False` in `CustomDataset`.
