### ISSUE TITLE
Out of memory during training

### ISSUE THREAD

**Issue by rusanager** [open-mmlab/mmdetection#5021]
Hello!
I'm try start training after relocate to v2 and I get error:
`2021-04-19 19:32:31,036 - mmdet - INFO - workflow: [('train', 1)], max: 50 epochs
Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 187, in <module>
    main()
  File "mmdetection/tools/train.py", line 183, in main
    meta=meta)
  File "/home/docker/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/hooks/optimizer.py", line 27, in after_train_iter
    runner.outputs['loss'].backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 4.00 GiB total capacity; 2.66 GiB already allocated; 26.86 MiB free; 2.90 GiB reserved in total by PyTorch)
`
I used to train the network with the same images and annotations. I only try to use mmdet v2 for training.  
And early I have only 2gb memory in gpu. I used pytorch 1.4.0, cu100 and  mmcv 1.2.1.  Now I use pytorch 1.6.0, cu101, mmcv 1.3.1, and the latest version of mmdetection.
I don't understand why I get out of memory. I need help!

**Comment by hhaAndroid** [comment]
Your GPU memory is not enough, you can consider reducing the image size.

**Comment by rusanager** [comment]
> Your GPU memory is not enough, you can consider reducing the image size.

But I trained with the same images and annotations using mmdet V1 and 2gb memory of GPU and all was ok.

I can reduce image size together annotation automatically? I have many annotated images and it was big work.

**Comment by hhaAndroid** [comment]
> > Your GPU memory is not enough, you can consider reducing the image size.
> 
> But I trained with the same images and annotations using mmdet V1 and 2gb memory of GPU and all was ok.
> 
> I can reduce image size together annotation automatically? I have many annotated images and it was big work.

Yes, You only need to modify the image size and annotation will automatically change.

**Comment by rusanager** [comment]
I'm sorry but I don't understand how my annotation will automatically change. I annotated images using coco annotator and I have annotation with the size of images and polygons with coordinates relative to image size. If I only change image size I will get the error that annotation out of range image size, right?

And I also don't understand why it works with V1, but doesn't work with V2, then I change only libraries versions.

**Comment by rusanager** [comment]
> Yes, You only need to modify the image size and annotation will automatically change.

I'm sorry but I don't understand how my annotation will automatically change. I annotated images using coco annotator and I have annotation with the size of images and polygons with coordinates relative to image size. If I only change image size I will get the error that annotation out of range image size, right?

And I also don't understand why it works with V1, but doesn't work with V2, then I change only libraries versions.

**Comment by hhaAndroid** [comment]
You don’t need to do other things, except to modify the image size in the config. Images and annotations will be processed together in the data processing pipeline.

**Comment by rusanager** [comment]
> You don’t need to do other things, except to modify the image size in the config. Images and annotations will be processed together in the data processing pipeline.

Now I understand. Thank you very much! I was able to start training.
