### ISSUE TITLE
How to add dilation and change num_queries in DETR config

### ISSUE THREAD

**Issue by duongnv0499** [open-mmlab/mmdetection#5022]
Thank you for your great work!
I want to add --dilation and change --num_queries from 100 to 300 in DETR model, but I cannot add it to DETR config. Were you implement it yet? Is there any suggestion to modify them?
Thank you !

**Comment by hhaAndroid** [comment]
Hi
1. you can modify `test_cfg=dict(max_per_img=100))` to `test_cfg=dict(max_per_img=300))`
2. where do you want to add dilation?
