### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by xinzhichao** [open-mmlab/mmdetection#5024]
./tools/dist_test.sh \
    configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py \
    checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth \
    8 \
    --format-only \
    --options "jsonfile_prefix=./mask_rcnn_test-dev_results"

When I run this line of code, there is no error, but no .json file is generated in the directory. My version is mmdet 2.1

**Comment by hhaAndroid** [comment]
Hi, @xinzhichao  I am running normally, maybe you can try the single-machine mode.

**Comment by xinzhichao** [comment]
Hello, thank you for your reply. The commands I tried all work normally, but there is no .json or png and txt. What could be the possible reason for this?

./tools/dist_test.sh
configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py
checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
1
--format-only
--options "jsonfile_prefix=./mask_rcnn_test-dev_results"


./tools/dist_test.sh
configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py
checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
1
--format-only
--options "txtfile_prefix=./mask_rcnn_test-dev_results"


python  configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py
checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
--format-only
--options "jsonfile_prefix=./mask_rcnn_test-dev_results"

**Comment by xinzhichao** [comment]
> Hi, @xinzhichao I am running normally, maybe you can try the single-machine mode.

Hello, thank you for your reply. The commands I tried all work normally, but there is no .json or png and txt. What could be the possible reason for this?

./tools/dist_test.sh
configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py
checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
1
--format-only
--options "jsonfile_prefix=./mask_rcnn_test-dev_results"

./tools/dist_test.sh
configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py
checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
1
--format-only
--options "txtfile_prefix=./mask_rcnn_test-dev_results"

python configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py
checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
--format-only
--options "jsonfile_prefix=./mask_rcnn_test-dev_results"
