### ISSUE TITLE
Clarification on installation instructions documentation

### ISSUE THREAD

**Issue by Lauler** [open-mmlab/mmdetection#5029]
I'm wondering whether you can clarify certain aspects of the installation instructions documentation found here:  https://mmdetection.readthedocs.io/en/latest/get_started.html .

I find them rather confusing but maybe this is because I am unfamiliar with mmcv as a whole and for the past 6 months have relied on conda environments to manage CUDA with Pytorch rather than have it installed on my system. 

1. Why is step 1 of the instructions to `pip install mmdet`, whereas step 2 proceeds to instruct the user to create a conda environment? Does this mean `mmdet` should be installed in the base environment? Is creating a conda environment entirely optional?  Is `pip install mmdet` before creating conda environment optional? Is step2-step6 an entirely separate installation guide that is not related to step1? Many questions. Few answers. 
2. In step 3 you give the following example: "E.g.1 If you have CUDA 10.1 installed under /usr/local/cuda and would like to install PyTorch 1.5, you need to install the prebuilt PyTorch with CUDA 10.1.".  I have trouble parsing the meaning of this. My guess, however, is that the implication of these instructions is that I need to both: i) have CUDA installed my system, AND ii) install the cudatoolkit matching my system's CUDA version in the conda environment when building Pytorch. Maybe the confusion stems from me being too stupid to understand what "Note: Make sure that your compilation CUDA version and runtime CUDA version match" means. I feel like this is a rather critical installation instruction and should be phrased in a more friendly way for more unexperienced people such as myself for whom the phrasing "compilation CUDA version and runtime CUDA version" is unhelpful. 
3. Step 5 and 6: Here you clone and build `mmdetection` again which makes me strongly suspect that step 1 was an entirely separate way of installing the library that is not at all related to step 2-6. In fact I am sure of it -- but since I managed to misinterpret so many of the previous installation instructions I harbor some residual doubt that I may still be an idiot. 

I would appreciate if you could clarify these things in the documentation for people like me for whom it is very easy to misinterpret instructions. In short I think you should break up Step1 from Steps 2-6 and organize them under separate subheadings:

**Installation option 1 with pip**
1. pip install mmdet

**Installation option 2 with conda**
1. Create a conda env and activate it...
2. You need to have CUDA installed on your system following these instructions: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html . 
3. Assuming you have CUDA 10.1 already installed, you can install Pytorch in your conda environment by... 
4. ...

In my opinion the heading ["A from-scratch setup script" ](https://mmdetection.readthedocs.io/en/latest/get_started.html#a-from-scratch-setup-script) conveyed the instructions more clearly and unambiguously than the current steps in your guide.

**Comment by hhaAndroid** [comment]
Hi @Lauler Thanks for your kind comments. Can you submit a PR？

**Comment by tojimahammatov** [comment]
Hi @Lauler , some opinions about your words:
1. Did you notice that ```pip install mmdet``` is given with red color without gray box like other commands (e.g conda ...) ? I am sure that you did not run ```pip uninstall mmcv``` as well which is given above with the red color since it is a kind of note. 
2. There is prerequisites section at the beginning, so you can assume that steps are given to install all of those prerequisites before running simple ```pip install mmdet```. 
3. However, I still agree with you to make some changes into instructions. My simple addition would be remove step 1, and add it to step 6 as an option to install mmdet. Then after step 6, note "a" section makes sense to separate two different installation modes.
