### ISSUE TITLE
Why there need to be three RoIExtractor?

### ISSUE THREAD

**Issue by jichilen** [open-mmlab/mmdetection#503]
Here are the configs
https://github.com/open-mmlab/mmdetection/blob/53c647eac839aac788d719ba2c5f8215214cbdd8/configs/cascade_mask_rcnn_r50_fpn_1x.py#L28-L32
And in cascade_rcnn.py
https://github.com/open-mmlab/mmdetection/blob/53c647eac839aac788d719ba2c5f8215214cbdd8/mmdet/models/detectors/cascade_rcnn.py#L47-L50
https://github.com/open-mmlab/mmdetection/blob/53c647eac839aac788d719ba2c5f8215214cbdd8/mmdet/models/detectors/cascade_rcnn.py#L62-L65
There seems to be no params in RoIExtractor, can i use one RoIExtractor to do RoIAlign for box heads and mask heads?

**Comment by hellock** [comment]
Of course you can. We just want to make it more flexible.

**Comment by jichilen** [comment]
Thank you
