### ISSUE TITLE
How to convert  models from V1.x to MMDetection V2.0?

### ISSUE THREAD

**Issue by hanlanqian** [open-mmlab/mmdetection#5030]

**Comment by hhaAndroid** [comment]
please refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md

**Comment by hanlanqian** [comment]
@hhaAndroid  Many thanks to your reply~ Accordingly, how to convert configs files`config.py` from V1.x to MMDetection V2.0?
