### ISSUE TITLE
MaskRCNN - IndexError: list index out of range after training 1 epoch

### ISSUE THREAD

**Issue by manhph2211** [open-mmlab/mmdetection#5032]
Hello, I'm having trouble  with this kinda weird error:
```
  File "./mmdetection/mmdet/datasets/coco.py", line 259, in _segm2json
    if isinstance(segms[i]['counts'], bytes):
IndexError: list index out of range
```
Showing up right after I trained 1 epoch :cry: 

Could anyone help me to handle it :love_letter:  Thanks in advance!

**Comment by hhaAndroid** [comment]
I suspect that your data may be incorrectly labeled, you need to check

**Comment by manhph2211** [comment]
Sir, thanks for your reply. I did check the data(only 1 class) but everything seems good :confused:

**Comment by hhaAndroid** [comment]
You can also use [visual scripts](https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py) to find problems easily

**Comment by leemengwei** [comment]
+1 here when resume-from model,  at epoch 23

**Comment by hhaAndroid** [comment]
> +1 here when resume-from model, at epoch 23 using dist train

I think this error has nothing to do with the train, it may just be a dataset problem.

**Comment by manhph2211** [comment]
@hhaAndroid I followed the solution in `fix supple_mask` above but the error is still there :sob: :sob:

**Comment by hhaAndroid** [comment]
> @hhaAndroid I followed the solution in `fix supple_mask` above but the error is still there

This problem is more difficult to eliminate, can you debug to see the cause? Thank you.

**Comment by YiXinChenChen** [comment]
+1

**Comment by hhaAndroid** [comment]
> +1

Are you using the coco data set? Can you provide more details？

**Comment by YiXinChenChen** [comment]
> > +1
> 
> Are you using the coco data set? Can you provide more details？

I use the custom dataset but covert it to coco format,  the error appear when evaluation：

2021-04-28 14:33:52,806 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 50/50, 6.9 task/s, elapsed: 7s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 186, in main
    meta=meta)
  File "/home/chenyixin03/mmdetection/mmdet/apis/train.py", line 171, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 147, in after_train_epoch
    key_score = self.evaluate(runner, results)
  File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 177, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 417, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 362, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 299, in results2json
    json_results = self._segm2json(results)
  File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 267, in _segm2json
    if isinstance(segms[i]['counts'], bytes):
    IndexError: list index out of range

**Comment by hhaAndroid** [comment]
> > > +1
> > 
> > 
> > Are you using the coco data set? Can you provide more details？
> 
> I use the custom dataset but covert it to coco format, the error appear when evaluation：
> 
> 2021-04-28 14:33:52,806 - mmdet - INFO - Saving checkpoint at 1 epochs
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 50/50, 6.9 task/s, elapsed: 7s, ETA: 0sTraceback (most recent call last):
> File "tools/train.py", line 190, in
> main()
> File "tools/train.py", line 186, in main
> meta=meta)
> File "/home/chenyixin03/mmdetection/mmdet/apis/train.py", line 171, in train_detector
> runner.run(data_loaders, cfg.workflow)
> File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
> epoch_runner(data_loaders[i], **kwargs)
> File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
> self.call_hook('after_train_epoch')
> File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> getattr(hook, fn_name)(self)
> File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 147, in after_train_epoch
> key_score = self.evaluate(runner, results)
> File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 177, in evaluate
> results, logger=runner.logger, **self.eval_kwargs)
> File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 417, in evaluate
> result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
> File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 362, in format_results
> result_files = self.results2json(results, jsonfile_prefix)
> File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 299, in results2json
> json_results = self._segm2json(results)
> File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 267, in _segm2json
> if isinstance(segms[i]['counts'], bytes):
> IndexError: list index out of range

Have you tried #5065 solution?

**Comment by YiXinChenChen** [comment]
> > > > +1
> > > 
> > > 
> > > Are you using the coco data set? Can you provide more details？
> > 
> > 
> > I use the custom dataset but covert it to coco format, the error appear when evaluation：
> > 2021-04-28 14:33:52,806 - mmdet - INFO - Saving checkpoint at 1 epochs
> > [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 50/50, 6.9 task/s, elapsed: 7s, ETA: 0sTraceback (most recent call last):
> > File "tools/train.py", line 190, in
> > main()
> > File "tools/train.py", line 186, in main
> > meta=meta)
> > File "/home/chenyixin03/mmdetection/mmdet/apis/train.py", line 171, in train_detector
> > runner.run(data_loaders, cfg.workflow)
> > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
> > epoch_runner(data_loaders[i], **kwargs)
> > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
> > self.call_hook('after_train_epoch')
> > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> > getattr(hook, fn_name)(self)
> > File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 147, in after_train_epoch
> > key_score = self.evaluate(runner, results)
> > File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 177, in evaluate
> > results, logger=runner.logger, **self.eval_kwargs)
> > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 417, in evaluate
> > result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
> > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 362, in format_results
> > result_files = self.results2json(results, jsonfile_prefix)
> > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 299, in results2json
> > json_results = self._segm2json(results)
> > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 267, in _segm2json
> > if isinstance(segms[i]['counts'], bytes):
> > IndexError: list index out of range
> 
> Have you tried #5065 solution?

yes，but not work.

**Comment by hhaAndroid** [comment]
> > > > > +1
> > > > 
> > > > 
> > > > Are you using the coco data set? Can you provide more details？
> > > 
> > > 
> > > I use the custom dataset but covert it to coco format, the error appear when evaluation：
> > > 2021-04-28 14:33:52,806 - mmdet - INFO - Saving checkpoint at 1 epochs
> > > [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 50/50, 6.9 task/s, elapsed: 7s, ETA: 0sTraceback (most recent call last):
> > > File "tools/train.py", line 190, in
> > > main()
> > > File "tools/train.py", line 186, in main
> > > meta=meta)
> > > File "/home/chenyixin03/mmdetection/mmdet/apis/train.py", line 171, in train_detector
> > > runner.run(data_loaders, cfg.workflow)
> > > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
> > > epoch_runner(data_loaders[i], **kwargs)
> > > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
> > > self.call_hook('after_train_epoch')
> > > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> > > getattr(hook, fn_name)(self)
> > > File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 147, in after_train_epoch
> > > key_score = self.evaluate(runner, results)
> > > File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 177, in evaluate
> > > results, logger=runner.logger, **self.eval_kwargs)
> > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 417, in evaluate
> > > result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
> > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 362, in format_results
> > > result_files = self.results2json(results, jsonfile_prefix)
> > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 299, in results2json
> > > json_results = self._segm2json(results)
> > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 267, in _segm2json
> > > if isinstance(segms[i]['counts'], bytes):
> > > IndexError: list index out of range
> > 
> > 
> > Have you tried #5065 solution?
> 
> yes，but not work.

It is difficult for me to reproduce. Could you please debug to see the approximate reason？Thank you.

**Comment by YiXinChenChen** [comment]
> > > > > > +1
> > > > > 
> > > > > 
> > > > > Are you using the coco data set? Can you provide more details？
> > > > 
> > > > 
> > > > I use the custom dataset but covert it to coco format, the error appear when evaluation：
> > > > 2021-04-28 14:33:52,806 - mmdet - INFO - Saving checkpoint at 1 epochs
> > > > [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 50/50, 6.9 task/s, elapsed: 7s, ETA: 0sTraceback (most recent call last):
> > > > File "tools/train.py", line 190, in
> > > > main()
> > > > File "tools/train.py", line 186, in main
> > > > meta=meta)
> > > > File "/home/chenyixin03/mmdetection/mmdet/apis/train.py", line 171, in train_detector
> > > > runner.run(data_loaders, cfg.workflow)
> > > > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
> > > > epoch_runner(data_loaders[i], **kwargs)
> > > > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
> > > > self.call_hook('after_train_epoch')
> > > > File "/home/chenyixin03/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> > > > getattr(hook, fn_name)(self)
> > > > File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 147, in after_train_epoch
> > > > key_score = self.evaluate(runner, results)
> > > > File "/home/chenyixin03/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 177, in evaluate
> > > > results, logger=runner.logger, **self.eval_kwargs)
> > > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 417, in evaluate
> > > > result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
> > > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 362, in format_results
> > > > result_files = self.results2json(results, jsonfile_prefix)
> > > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 299, in results2json
> > > > json_results = self._segm2json(results)
> > > > File "/home/chenyixin03/mmdetection/mmdet/datasets/coco.py", line 267, in _segm2json
> > > > if isinstance(segms[i]['counts'], bytes):
> > > > IndexError: list index out of range
> > > 
> > > 
> > > Have you tried #5065 solution?
> > 
> > 
> > yes，but not work.
> 
> It is difficult for me to reproduce. Could you please debug to see the approximate reason？Thank you.

The reason for this error is that the num of the bboxs and the num of of the segms is not euqal when evaluation in _segm2json function. I don't know why.

**Comment by hhaAndroid** [comment]
@YiXinChenChen #5065 is to solve this situation, but I don't know why it has not been solved? Are there other situations that have not been considered? You can take a closer look at #5065. thank you!

**Comment by YiXinChenChen** [comment]
> @YiXinChenChen #5065 is to solve this situation, but I don't know why it has not been solved? Are there other situations that have not been considered? You can take a closer look at #5065. thank you!

OK, I found that the current MMD version is 2.11.0，when I update to master，it work！ Thanks！

**Comment by whitecyl** [comment]
> > @YiXinChenChen #5065 is to solve this situation, but I don't know why it has not been solved? Are there other situations that have not been considered? You can take a closer look at #5065. thank you!
> 
> OK, I found that the current MMD version is 2.11.0，when I update to master，it work！ Thanks！

May I ask you how to fix this error? I got the same error!!!

**Comment by Epiee** [comment]
I modified something in mmdet（2.28.2）/datasets/coco.py ,which added it after 'for I in range(bboxes.shape[0]):' in the segm section:
‘if i >= len(segms):
continue’
After this change, the code ran successfully. As I iterate through the bboxes, I make sure the segms are long enough to prevent the index from crossing over. Therefore, a condition check is added while traversing the bboxes
I hope it was helpful for you.
