### ISSUE TITLE
TensorRT conversion error for faster_rcnn_r50

### ISSUE THREAD

**Issue by christian-holland** [open-mmlab/mmdetection#5033]
Pretty much duplicate of this [issue](https://github.com/open-mmlab/mmdetection/issues/4822), but the offered solutions do not work I think (and the problem still persists). 

I installed mmcv with plugins as described in docs. `assert is_tensorrt_plugin_loaded()` returns True. I am trying to convert `faster_rcnn_r50_fpn_1x_coco` which should be supported according to docs. I the other thread it is suggested that this may be due to recent changes but I tried all older commits that have the conversion and the same issue still persists.

Can somebody offer a setting where this error does not occur for `faster_rcnn_r50_fpn_1x_coco`?

Traceback:
```
root@a:/my_mmdetection# python tools/deployment/onnx2tensorrt.py tmp.onnx
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 179, in <module>
    workspace_size=args.workspace_size)
  File "tools/deployment/onnx2tensorrt.py", line 38, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/my_mmdetection/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 148, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node 497 (importTopK): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()
```

ran in docker:
Cuda version 11.0
TensorRT version 7.2.3.4 
mmcv-full 1.3.1
Installed as described in the docs.

**Comment by RunningLeon** [comment]
The following error is due to K in TopK should be int in TensorRT, not a Tensor, but it could be a Tensor in ONNXRuntime. You could comment out those codes of creating dynamic K for TopK to workaround.

```
In node -1 (importTopK): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()
```

If it is urgent, you could try with [ONNX branch](https://github.com/open-mmlab/mmdetection/tree/onnx) and refer to the [pytorch2onnx](https://github.com/open-mmlab/mmdetection/blob/onnx/docs/tutorials/pytorch2onnx.md) and [onnx2tensorrt](https://github.com/open-mmlab/mmdetection/blob/onnx/docs/tutorials/onnx2tensorrt.md)

**Comment by christian-holland** [comment]
Hi thanks for your help. Which occuring of top_k do you mean exactly? The top_k proposals of rpn? Where in the code would I find this?

Also do you maybe have an environment where this conversion works?

**Comment by christian-holland** [comment]
@RunningLeon I understand that this is a beta feature. Do you know what commit of mmdet and mmcv you used for working conversion of fasterrcnn? I am trying to reproduce this setting.

**Comment by RunningLeon** [comment]
onnx branch certainly could export fasterrcnn. Did you follow the instructions? Can you provide detailed error message?

**Comment by RunningLeon** [comment]
@christian-holland Do you still have the issue?

**Comment by christian-holland** [comment]
yes, I am trying to find the difference at the moment if it works for you. Are you still using torch version 1.6 cuda 10.2 and mmcv built from source at current master?

**Comment by RunningLeon** [comment]
### You can refer to the doc.

> The following error is due to K in TopK should be int in TensorRT, not a Tensor, but it could be a Tensor in ONNXRuntime. You could comment out those codes of creating dynamic K for TopK to workaround.
> 
> ```
> In node -1 (importTopK): UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()
> ```
> 
> If it is urgent, you could try with [ONNX branch](https://github.com/open-mmlab/mmdetection/tree/onnx) and refer to the [pytorch2onnx](https://github.com/open-mmlab/mmdetection/blob/onnx/docs/tutorials/pytorch2onnx.md) and [onnx2tensorrt](https://github.com/open-mmlab/mmdetection/blob/onnx/docs/tutorials/onnx2tensorrt.md)

### Important info from the doc for pytorch->onnx->tensorrt:

- All models above are tested with Pytorch==1.6.0 and onnxruntime==1.5.1

- If the deployed backend platform is TensorRT, please add environment variables before running the file:

```export ONNX_BACKEND=MMCVTensorRT```
- If you want to use the --dynamic-export parameter in the TensorRT backend to export ONNX, please remove the --simplify parameter, and vice versa.
```

**Comment by RunningLeon** [comment]
Feel free to reopen it if you still have the issue.

**Comment by ximitiejiang** [comment]
@RunningLeon, 
Hi, i met similiar issue for exporting trt model. i tried the the onnx branch as you mentioned and export the onnx model sucessfully but still failed to export trt model. 
1. below are my software versions:
pytorch1.6.0
cuda10.1
cudnn7.6
onnxruntime1.5.1
tensorRT7.2.1.6

2. I compiled the mmcv with onnxruntime1.5.1 with MMCV_WITH_OPS=1,MMCV_WITH_ORT=1,MMCV_WITH_TRT=1, and generated 3 so files in mmcv root path.

3. pth file export to onnx file succeed with pytorch2onnx().

4. onnx file export to trt file failed with below traceback:
......(leaved out some trt verbose logs here)
[TensorRT] VERBOSE: ModelImporter.cpp:125: Where_492 [Where] inputs: [896 -> ()], [874 -> ()], [894 -> ()], 
[TensorRT] VERBOSE: ImporterContext.hpp:150: Registering constant layer: 874 for ONNX initializer: 874
[TensorRT] VERBOSE: ImporterContext.hpp:154: Registering layer: Where_492 for ONNX node: Where_492
[TensorRT] VERBOSE: ImporterContext.hpp:120: Registering tensor: 897 for ONNX tensor: 897
[TensorRT] VERBOSE: ModelImporter.cpp:179: Where_492 [Where] outputs: [897 -> ()], 
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: Constant_493 [Constant]
[TensorRT] VERBOSE: ModelImporter.cpp:125: Constant_493 [Constant] inputs: 
[TensorRT] VERBOSE: ModelImporter.cpp:179: Constant_493 [Constant] outputs: [898 -> (1)], 
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: Reshape_494 [Reshape]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 897
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 898
[TensorRT] VERBOSE: ModelImporter.cpp:125: Reshape_494 [Reshape] inputs: [897 -> ()], [898 -> (1)], 
[TensorRT] VERBOSE: ImporterContext.hpp:154: Registering layer: Reshape_494 for ONNX node: Reshape_494
[TensorRT] VERBOSE: ImporterContext.hpp:120: Registering tensor: 899 for ONNX tensor: 899
[TensorRT] VERBOSE: ModelImporter.cpp:179: Reshape_494 [Reshape] outputs: [899 -> (1)], 
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: TopK_495 [TopK]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 881
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 899
[TensorRT] VERBOSE: ModelImporter.cpp:125: TopK_495 [TopK] inputs: [881 -> (-1, -1)], [899 -> (1)], 
Traceback (most recent call last):
  File "/home/suliang/suliang_git/mmdetection-onnx/sl_BIG/onnx2tensorrt.py", line 239, in <module>
    verbose=args.verbose)
  File "/home/suliang/suliang_git/mmdetection-onnx/sl_BIG/onnx2tensorrt.py", line 42, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/home/suliang/suliang_git/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 52, in onnx2trt
    onnx_model.SerializeToString()), 'parse onnx failed.'
AssertionError: parse onnx failed.

Process finished with exit code 1

i am not very sure anything i missing or if you can give any more suggestion? 
You mentioned we can comment the topK  code area to workaround, can you give more detail on how to to do that or on which position i can do?

thanks in advance.

**Comment by RunningLeon** [comment]
Currently, we do not have this plan.
If you set `export ONNX_BACKEND=MMCVTensorRT` before run `pytorch2onnx.py`, then the K of TopK would be set to constant in the ONNX model and there would be no error of `Assertion failed: inputs.at(1).is_weights()`.
> @RunningLeon If you say that the conversion works for you, can you maybe provide an installation script that works from your provided docker container? Then I can investigate the difference to my build.
