### ISSUE TITLE
Questions about `pretain` and `load_from` loading

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#5036]
Hi, dear authors
Sorry to bother you.
I have a small question.
If I load `pretrain='open-mmlab://detectron/resnet50_gn'` and `load_from = 'faster-rcnn_r50_fpn_xxxxxx.pth'` in the config file at the same time, then is the `resnet50_gn` from `pretrain` or the `resnet50` from `load_from` loaded on the backbone?
Thank you

**Comment by hhaAndroid** [comment]
Run `pretrain`first, then `load_from `.

**Comment by zhongqiu1245** [comment]
> Run `pretrain`first, then `load_from `.

@hhaAndroid Hi
Thank you for your reply.
According to what you mean, `load_from` will replace `pretrain` in the end, right? (If both are loaded at the same time)

**Comment by tojimahammatov** [comment]
```pretrained``` weights are loaded when a model is built, you can see constructors of all detectors, e.g [this one](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/single_stage.py).

```load_from``` weights are loaded just before starting the training, thus they will override. You can see the END of [this file](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py).

**Comment by zhongqiu1245** [comment]
Thank you！
