### ISSUE TITLE
Why do I use dist_train.sh slower than non_dist_train

### ISSUE THREAD

**Issue by liuhe2017** [open-mmlab/mmdetection#504]
Are there any difference between running "python ./tools/train.py ./configs/retinanet_r50_fpn_1x.py --gpu 4 --validate" and "./tools/dist_train.sh ./configs/retinanet_r50_fpn_1x.py 4 --validate". ps. I modify "workers_per_gpu" in "retinanet_r50_fpn_1x.py" from 2 to 4.
The question is: when I run dist_train.sh at the beginning, the log says the training may cost about 3 days and  "python ./tools/train.py ./configs/retinanet_r50_fpn_1x.py --gpu 4 --validate" just cost 1 day.  However, after finishing training 1400 pictures, the dist_train.sh is faster than "python ./tools/train.py ./configs/retinanet_r50_fpn_1x.py --gpu 4 --validate" about 1 minutes. Why was that happening? Is dist_train.sh will faster than non_dist_train.sh even in the same GPU numbers?

**Comment by hellock** [comment]
The ETA at the beginning is not accurate since the first few iterations are slow.

**Comment by liuhe2017** [comment]
So, calculating the total time, using dist_train.sh will be faster than train.py?




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            刘鹤
                            
                            
                                
                                    邮箱：liuhe.coder@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


On 04/17/2019 09:40, Kai Chen wrote: The ETA at the beginning is not accurate since the first few iterations are slow.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/open-mmlab/mmdetection","title":"open-mmlab/mmdetection","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/open-mmlab/mmdetection"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hellock in #504: The ETA at the beginning is not accurate since the first few iterations are slow."}],"action":{"name":"View Issue","url":"https://github.com/open-mmlab/mmdetection/issues/504#issuecomment-483904386"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/open-mmlab/mmdetection/issues/504#issuecomment-483904386",
"url": "https://github.com/open-mmlab/mmdetection/issues/504#issuecomment-483904386",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hellock** [comment]
yes, except that your dataset has very few images.

**Comment by liuhe2017** [comment]
Got it, thanks a lot!




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            刘鹤
                            
                            
                                
                                    邮箱：liuhe.coder@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


On 04/17/2019 09:47, Kai Chen wrote: yes, except that your dataset has very few images.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/open-mmlab/mmdetection","title":"open-mmlab/mmdetection","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/open-mmlab/mmdetection"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hellock in #504: yes, except that your dataset has very few images."}],"action":{"name":"View Issue","url":"https://github.com/open-mmlab/mmdetection/issues/504#issuecomment-483905531"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/open-mmlab/mmdetection/issues/504#issuecomment-483905531",
"url": "https://github.com/open-mmlab/mmdetection/issues/504#issuecomment-483905531",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Shen001** [comment]
> yes, except that your dataset has very few images.

so 200 images for train,100 images for validate is a very few dataset?
