### ISSUE TITLE
Different versions of mmdet yields different results

### ISSUE THREAD

**Issue by yarkable** [open-mmlab/mmdetection#5045]
I have a mmdet V2.3.0 in my server and another mmdet V2.11.0. However, all with bs=32 per GPU (I use two Nvidia V100s), size 640*640, their results are different, and gap nearly 1.5AP. Is there any problem with different versions? Below are my results of retinanet.

`2021-04-19 07:48:19,950 - mmdet - INFO - Exp name: retinanet_r50_fpn_1x_coco.py
2021-04-19 07:48:19,951 - mmdet - INFO - Epoch(val) [12][1833]  bbox_mAP: 0.3290, bbox_mAP_50: 0.5110, bbox_mAP_75: 0.3450, bbox_mAP_s: 0.1400, bbox_mAP_m: 0.3720, bbox_mAP_l: 0.4760, bbox_mAP_copypaste: 0.329 0.511 0.345 0.140 0.372 0.476
(mmdet)
`
`2021-04-21 10:33:21,727 - mmdet - INFO - Epoch(val) [12][1833]  bbox_mAP: 0.3140, bbox_mAP_50: 0.4920, bbox_mAP_75: 0.3310, bbox_mAP_s: 0.1320, bbox_mAP_m: 0.3590, bbox_mAP_l: 0.4490, bbox_mAP_copypaste: 0.314 0.492 0.331 0.132 0.359 0.449
`

**Comment by hhaAndroid** [comment]
@yarkable Do you have any questions now?
