### ISSUE TITLE
How can I visualize the groundtruth mask on the input image?

### ISSUE THREAD

**Issue by noobying** [open-mmlab/mmdetection#5048]
Hi, I want to know if there exists a api to visualize the groundtruth mask on the input image. I want to compare my predicted masks with the groundtruth one. Thanks a lot.

**Comment by hhaAndroid** [comment]
you can use this script https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py

**Comment by noobying** [comment]
> you can use this script https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py

Thanks a lot!
