### ISSUE TITLE
How to convert FCOS model to ONNX or caffe?

### ISSUE THREAD

**Issue by taofuyu** [open-mmlab/mmdetection#5049]

**Comment by RunningLeon** [comment]
You could refer to the doc: https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md

**Comment by taofuyu** [comment]
> You could refer to the doc: https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md

Thanks for reply. I read this tutorial before, but supported models only include ssd, yolo3, retina and faster-rcnn

**Comment by RunningLeon** [comment]
@taofuyu 
Should be working for FCOS on master branch. If not, could try with onnx branch.

**Comment by taofuyu** [comment]
> @taofuyu
> Should be working for FCOS on master branch. If not, could try with onnx branch.

master branch always raise error:
RuntimeError: Unsupported: ONNX export of type_as for tensor of unknown dtype.

Onnx branch can generate an .onnx file. But its structure is always very strange even with --simplify, and it HAS NOT correct model output.

**Comment by QingChuanWS** [comment]
What version of pytorch are you using?

**Comment by taofuyu** [comment]
> What version of pytorch are you using? @taofuyu

Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.0a0+1606899
GCC 9.3
CUDA Runtime 11.1
TorchVision: 0.9.0a0
OpenCV: 4.4.0
MMCV: 1.3.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.11.0+6b185f0

**Comment by QingChuanWS** [comment]
Hello, @taofuyu . After our verification, FCOS can be successfully exported to the onnx model. At the same time, if you specify the `dynamic-export` when using `pytorch2onnx.py`, and use `tests/data/color.jpg` as the verification image, the visualization results indeed will appear mismatch, but this does not mean that the export process failed. On the contrary, this picture is just an example. You can change to another picture for testing, such as `demo/demo.jpg`. You can find that the onnx file exported by visualization can run normally and the output is correct.

**Comment by QingChuanWS** [comment]
And on my machine, after FCOS exports onnx model without specifying `--dynamic-export`, the visualization result is correct.

**Comment by taofuyu** [comment]
> And on my machine, after FCOS exports onnx model without specifying `--dynamic-export`, the visualization result is correct.

what does your onnx's head look like? 
When I use detectron2, the onnx's head:

![det](https://user-images.githubusercontent.com/13781923/116528937-f92c5300-a90e-11eb-8e69-cb9800bcee32.png)
The prediction head is clear.

But when using mmdetection, the onnx's head:
![mm](https://user-images.githubusercontent.com/13781923/116529240-50322800-a90f-11eb-9b48-3babcb420732.png)

Obviously it can not be deployed to any platform.

**Comment by RunningLeon** [comment]
@taofuyu Hi, welcome PR from you to improve the deployment.
