### ISSUE TITLE
How to get the loss on validation set after each epoch?

### ISSUE THREAD

**Issue by forestriveral** [open-mmlab/mmdetection#505]
Is there any ways to get the loss on validation set after each epoch when training? 
Not just making COCO-style evaluation on validation set.
Thanks for any ideas!

**Comment by yhcao6** [comment]
Take 'Faster-R50' as example, you can modify the `workflow` in this line as
` worflow = [('train', 1), ('val', 1)]`
https://github.com/open-mmlab/mmdetection/blob/900968046507c57d25d0d965474937ed4a16775e/configs/faster_rcnn_r50_fpn_1x.py#L156
Also you need to modify the `data_loader` in this line, your need to append your `valset_loader` at the end of `data_loader`
https://github.com/open-mmlab/mmdetection/blob/900968046507c57d25d0d965474937ed4a16775e/mmdet/apis/train.py#L64

**Comment by forestriveral** [comment]
@yhcao6 Thanks! That solved the problem. Another question is whether I can get this loss after a given iteration interval(such as every 200 iterations, not one epoch like 1000 iterations)? Because I need more points to plot loss curve on both training and validation set.

**Comment by yhcao6** [comment]
You need to modify mmcv, to log every n iter in `val epoch`, you need to add a method `after_val_iter` just similar to `after_train_iter` to log every n iters
https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/base.py

**Comment by forestriveral** [comment]
I have tried to do some modification in `base.py`, but it didn't work successfully. The 'val epoch' is always after 'train epoch' like the following log output and I can't make them work alternately in the same epoch.
 
`2019-04-17 18:50:43,930 - INFO - Epoch [1][600/772]	lr: 0.00500, eta: 0:01:34, time: 0.569, data_time: 0.004, memory: 5116, loss_rpn_cls: 0.0190, loss_rpn_reg: 0.0082, s0.loss_cls: 0.0461, s0.acc: 98.0684, s0.loss_reg: 0.0441, s0.loss_mask: 0.2014, s1.loss_cls: 0.0256, s1.acc: 97.9508, s1.loss_reg: 0.0803, s1.loss_mask: 0.1152, s2.loss_cls: 0.0169, s2.acc: 97.0288, s2.loss_reg: 0.0633, s2.loss_mask: 0.0582, loss: 0.6783`
`2019-04-17 18:51:41,695 - INFO - Epoch [1][700/772]	lr: 0.00500, eta: 0:00:39, time: 0.578, data_time: 0.004, memory: 5116, loss_rpn_cls: 0.0165, loss_rpn_reg: 0.0075, s0.loss_cls: 0.0470, s0.acc: 98.0078, s0.loss_reg: 0.0465, s0.loss_mask: 0.1982, s1.loss_cls: 0.0268, s1.acc: 97.7954, s1.loss_reg: 0.0817, s1.loss_mask: 0.1110, s2.loss_cls: 0.0168, s2.acc: 97.2259, s2.loss_reg: 0.0688, s2.loss_mask: 0.0556, loss: 0.6763`
`2019-04-17 18:52:53,718 - INFO - Epoch(val) [1][100]	eta: 0:00:00, time: 0.204, data_time: 0.005, memory: 5217, loss_rpn_cls: 0.0201, loss_rpn_reg: 0.0082, s0.loss_cls: 0.0562, s0.acc: 97.6641, s0.loss_reg: 0.0473, s0.loss_mask: 0.2076, s1.loss_cls: 0.0334, s1.acc: 97.2258, s1.loss_reg: 0.0849, s1.loss_mask: 0.1132, s2.loss_cls: 0.0187, s2.acc: 96.7638, s2.loss_reg: 0.0774, s2.loss_mask: 0.0572, loss: 0.7242`
`2019-04-17 18:53:13,847 - INFO - Epoch(val) [1][200]	eta: 0:00:00, time: 0.201, data_time: 0.004, memory: 5217, loss_rpn_cls: 0.0164, loss_rpn_reg: 0.0073, s0.loss_cls: 0.0591, s0.acc: 97.5947, s0.loss_reg: 0.0493, s0.loss_mask: 0.2116, s1.loss_cls: 0.0347, s1.acc: 97.3185, s1.loss_reg: 0.0888, s1.loss_mask: 0.1161, s2.loss_cls: 0.0195, s2.acc: 96.7061, s2.loss_reg: 0.0779, s2.loss_mask: 0.0584, loss: 0.7390`
`2019-04-17 18:53:17,392 - INFO - Epoch(val) [1][218]	eta: 0:00:00, time: 0.202, data_time: 0.004, memory: 5217, loss_rpn_cls: 0.0179, loss_rpn_reg: 0.0076, s0.loss_cls: 0.0568, s0.acc: 97.6536, s0.loss_reg: 0.0475, s0.loss_mask: 0.2110, s1.loss_cls: 0.0337, s1.acc: 97.3061, s1.loss_reg: 0.0856, s1.loss_mask: 0.1156, s2.loss_cls: 0.0190, s2.acc: 96.7671, s2.loss_reg: 0.0766, s2.loss_mask: 0.0583, loss: 0.7294`

Then I found method `run` in [https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/runner.py](url). It seems like `train epoch` and `val epoch` must be done at least in one epoch by following the order of `cfg.workflow`. Am I missing any important details?

**Comment by yhcao6** [comment]
Sorry that I misunderstand your point. You may need to insert some code in `train` method at this line in "runner.py": 

https://github.com/open-mmlab/mmcv/blob/506455af0bb4edf6b13cec5c7d171f26c9531d52/mmcv/runner/runner.py#L269 

may be like this:
```
save_train_epoch_state
if (i + 1) % interval == 0:
    self.eval()
restore_train_epoch_state
```

**Comment by forestriveral** [comment]
Thank you for helping! Now the modification is working properly.

**Comment by DuCheng2018** [comment]
> Take 'Faster-R50' as example, you can modify the `workflow` in this line as
> ` worflow = [('train', 1), ('val', 1)]`
> [mmdetection/configs/faster_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/900968046507c57d25d0d965474937ed4a16775e/configs/faster_rcnn_r50_fpn_1x.py#L156)
> 
> Line 156 in [9009680](/open-mmlab/mmdetection/commit/900968046507c57d25d0d965474937ed4a16775e)
> 
>  workflow = [('train', 1)] 
> 
> Also you need to modify the `data_loaders` in this line, your need to append your `valset_loader` at the end of `data_loaders`
> [mmdetection/mmdet/apis/train.py](https://github.com/open-mmlab/mmdetection/blob/900968046507c57d25d0d965474937ed4a16775e/mmdet/apis/train.py#L64)
> 
> Line 64 in [9009680](/open-mmlab/mmdetection/commit/900968046507c57d25d0d965474937ed4a16775e)
> 
>  data_loaders = [

Will it make valset contribute to the model weights ?
Because It works just look like trainset.

**Comment by leemengwei** [comment]
@forestriveral , Hi by "Also you need to modify the data_loaders in this line, your need to append your valset_loader at the end of data_loaders", could you be more specific about how to make a valset_loader?

**Comment by canorbal** [comment]
@yhcao6 You mentioned here https://github.com/open-mmlab/mmdetection/issues/505#issuecomment-483954471 I have to add val_dataset in _non_dist_train but I do not understand how I can get it from this function

Could you please clarify it?

**Comment by canorbal** [comment]
It works if you add this lines:

```
from mmdet.datasets import get_dataset

...
    data_loaders = [
        build_dataloader(
            dataset,
            cfg.data.imgs_per_gpu,
            cfg.data.workers_per_gpu,
            cfg.gpus,
            dist=False),
        build_dataloader(
            get_dataset(cfg.data.val),
            cfg.data.imgs_per_gpu,
            cfg.data.workers_per_gpu,
            cfg.gpus,
            dist=False
        )
    ]
```

**Comment by psh9002** [comment]
> Take 'Faster-R50' as example, you can modify the `workflow` in this line as
> ` worflow = [('train', 1), ('val', 1)]`
> https://github.com/open-mmlab/mmdetection/blob/900968046507c57d25d0d965474937ed4a16775e/configs/faster_rcnn_r50_fpn_1x.py#L156
> 
> 
> Also you need to modify the `data_loaders` in this line, your need to append your `valset_loader` at the end of `data_loaders`
> https://github.com/open-mmlab/mmdetection/blob/900968046507c57d25d0d965474937ed4a16775e/mmdet/apis/train.py#L64

I cannot understand exactly what you mean.
You mean I have to create and import a new python file on 'mmdet/datasets/loader' or add method in 'mmdet/datasets/loader/build_loader.py'?

**Comment by leemengwei** [comment]
Run tools/dist_train.sh with —validate will get you on the way～

Yet I dont know what is the relation between ‘work_flow’ in config file and —validate in command line。

发自我的iPhone

**Comment by CarolinRue** [comment]
Hii, is this way also the same to get the validiation loss for mmdetection version 2.28.2? I am also not sure how to set this "_Also you need to modify the data_loaders in this line, your need to append your valset_loader at the end of data_loaders_", because in version 2.28.2 the data_loaders looks different. In version 2.28.2 there is no _dist_train function, here it looks like this: 

```
`def train_detector(model,
                   dataset,
                   cfg,
                   distributed=False,
                   validate=False,
                   timestamp=None,
                   meta=None):

    cfg = compat_cfg(cfg)
    logger = get_root_logger(log_level=cfg.log_level)

    # prepare data loaders
    dataset = dataset if isinstance(dataset, (list, tuple)) else [dataset]

    runner_type = 'EpochBasedRunner' if 'runner' not in cfg else cfg.runner[
        'type']

    train_dataloader_default_args = dict(
        samples_per_gpu=2,
        workers_per_gpu=2,
        # `num_gpus` will be ignored if distributed
        num_gpus=len(cfg.gpu_ids),
        dist=distributed,
        seed=cfg.seed,
        runner_type=runner_type,
        persistent_workers=False)

    train_loader_cfg = {
        **train_dataloader_default_args,
        **cfg.data.get('train_dataloader', {})
    }

    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]`
```

I am new to this. Can somebody help me to get the validation loss in mmdetection version 2.28.2?

```When I just add workflow = [('train', 1), ('val', 1)] then I get this error: 
File "tools/train.py", line 247, in <module>
    main()
  File "tools/train.py", line 226, in main
    'pipeline', cfg.data.train.dataset.get('pipeline'))
  File "/home/mm/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 52, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dataset'```
