### ISSUE TITLE
How to save validation results in pkl for each epoch during training?

### ISSUE THREAD

**Issue by cskarthik7** [open-mmlab/mmdetection#5067]
I have been training detectoRS with custom config and trying to implement a feature where I am able to save predictions in pkl during validation for each epoch in training phase. So wanted to know how can I tackle this problem.

**Comment by ZwwWayne** [comment]
You can modify the `EvalHook` [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py#L272) to save the prediction results.
