### ISSUE TITLE
where is the code about Guided Anchoring?

### ISSUE THREAD

**Issue by shipengai** [open-mmlab/mmdetection#507]
I am reading paper"Region Proposal by Guided Anchoring",In Abstact, it says code is in this reposity.But I can't find it. Can anyone help me find it, Thanks

**Comment by myownskyW7** [comment]
We are still working on it. The code will probably be public next week.

**Comment by SunskyF** [comment]
any progress?

**Comment by shipengai** [comment]
@myownskyW7 Any progress? I'm looking forward your coding.

**Comment by wangyuxin87** [comment]
> We are still working on it. The code will probably be public next week.

Does it finished? I'm looking forward too! Waiting for your response!

**Comment by myownskyW7** [comment]
https://github.com/open-mmlab/mmdetection/pull/594 The code is in this pr, the performance is ready.

**Comment by shipengai** [comment]
Good work! I have found it in pull request
