### ISSUE TITLE
RuntimeError: number of dims don't match in permute

### ISSUE THREAD

**Issue by dujinhuaGithub** [open-mmlab/mmdetection#5074]
when running pytorch2onnx

**Comment by johnson-magic** [comment]
mmdetction Only support the models of list to convert onnx.
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md#list-of-supported-models-exportable-to-onnx

**Comment by changzhonghan** [comment]
The case is the [F.linear] expected the weight has the shape of [channel-out X channel-in]; But , the [project] has the shape of [channel-out]. so U can fix this bug : x = F.linear(x, self.project.type_as(x).reshape(-1, 1)).reshape(x.shape[0],-1, 4)
