### ISSUE TITLE
AssertionError: MMCV==1.3.1 is used but incompatible. Please install mmcv>=1.3.2, <=1.4.0.

### ISSUE THREAD

**Issue by MrDavinci** [open-mmlab/mmdetection#5078]
But, where could I find such a mmcv? The lastest intalling command is mmcv1.3.1.

**Comment by hhaAndroid** [comment]
Hi, @MrDavinci  please refer to https://github.com/open-mmlab/mmcv.

**Comment by MrDavinci** [comment]
Hi, Kai ge, I download mmcv 132 source code.zip, and run the setup.py, but I only get mmcv132 rather than mmcv-full 132. It this OK?

**Comment by hhaAndroid** [comment]
> Hi, Kai ge, I download mmcv 132 source code.zip, and run the setup.py, but I only get mmcv132 rather than mmcv-full 132. It this OK?

You can use this command pip install mmcv-full==1.3.2 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html

**Comment by MrDavinci** [comment]
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Looking in links: https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full==1.3.2
ERROR: No matching distribution found for mmcv-full==1.3.2

I did, but

**Comment by hhaAndroid** [comment]
![image](https://user-images.githubusercontent.com/17425982/116383461-7097af00-a849-11eb-914e-6d501416ec78.png)

**Comment by MrDavinci** [comment]
Oh no, I am using win10.

**Comment by hhaAndroid** [comment]
> Oh no, I am using win10.

win10 is not officially supported. You need to compile it yourself.

**Comment by MrDavinci** [comment]
Oh well, .mmcv1.3.1 full is worked normally on win10.
I am going to compile it, thank you!

**Comment by MrDavinci** [comment]
After setting the environment variables,

CUDA_HOME = CUDA_PATH_V11_1
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
CUDA_PATH_V11_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
TORCH_CUDA_ARCH_LIST="8.6"
MMCV_WITH_OPS = 1
MAX_JOBS = 8

 I ran the following 
(MMcv) C:\Users\53771\mmcv132\mmcv-1.3.2\mmcv-1.3.2>python setup.py build_ext
running build_ext

nothing else happened
