### ISSUE TITLE
Add all-in-one graphic with all methods

### ISSUE THREAD

**Issue by ioctl-user** [open-mmlab/mmdetection#5085]
There are a lot of methods that is difficult to compare, so I have the following suggestion:

Add graphical picture with all methods with two axis: FPS and box AP.
Something like this: https://paperswithcode.com/sota/pose-estimation-on-coco-test-dev

**Comment by ZwwWayne** [comment]
Hi @ioctl-user ,
Thanks for your suggestion. Actually paper with code has already done that for us [here](https://paperswithcode.com/lib/mmdetection). We will do that in our own repo in future releases.
