### ISSUE TITLE
Unable to install mmcv version 1.3.2 or higher

### ISSUE THREAD

**Issue by darshan2412** [open-mmlab/mmdetection#5095]
mmdet __init__ file has a requirement of mmcv version higher than 1.3.2. But I'm unable to install that version of mmcv. The latest available version is 1.3.1

**Comment by tojimahammatov** [comment]
How and what method did you try to install? What errors did you get?

How about using lower version of mmdet?

**Comment by darshan2412** [comment]
I tried installing with the following commands:
```
!pip install mmcv-full
!git clone https://github.com/open-mmlab/mmdetection.git
%cd mmdetection
!pip install -e .
```
However, currently, I'm not facing any problem as mmcv-full version 1.3.3 is getting installed with this command. So this issue can be closed
