### ISSUE TITLE
About pretrain

### ISSUE THREAD

**Issue by joey1616** [open-mmlab/mmdetection#5103]
Hello, how to use pretrain weights? I can't find the modification in the config file. Thanks.

**Comment by EdyQiu** [comment]
> Hello, how to use pretrain weights? I can't find the modification in the config file. Thanks.

May I ask how did you solve the problem? 
I modified the config file and train.py as the official document mentioned, but the msg 'i**nit_cfg without layer key, if you do not define override' still appears.**

_model = dict(
type='FasterRCNN',
#pretrained='torchvision://resnet50',
backbone=dict(
type='ResNet',
depth=50,
num_stages=4,
out_indices=(0, 1, 2, 3),
frozen_stages=1,
norm_cfg=dict(type='BN', requires_grad=True),
norm_eval=True,
style='pytorch',
**init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'),),_

Thanks lot!

**Comment by joey1616** [comment]
> I modified the config file and train.py as the official document mentioned, but the msg 'i**nit_cfg without layer key, if you do not define override' still appears.**

Hi, I change '''load_from''' at __base__/default_runtime.py.

**Comment by EdyQiu** [comment]
> > I modified the config file and train.py as the official document mentioned, but the msg 'i**nit_cfg without layer key, if you do not define override' still appears.**
> 
> Hi, I change '''load_from''' at **base**/default_runtime.py.

Thanks!
Yesterday I also used the "load from", but the error msg still appeared, and the fine-tuning result was almost 0 mAP.
I will have other trys!
