### ISSUE TITLE
onnx - assertion error - The numerical values are different between Pytorch and ONNX,

### ISSUE THREAD

**Issue by suchig** [open-mmlab/mmdetection#5107]
I created a model using Faster-RCNN and created checkpoints for the same. I ran the below to create onnx file

python tools/deployment/pytorch2onnx.py /
        configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py 
        my_epoch_10.pth     
        --output-file my_onnx.onnx --verify --test-img my.jpg --input-img my.jpg 
        --cfg-options model.roi_head.bbox_head.num_classes=32

I got the error The numerical values are different between Pytorch and ONNX
(shapes (0, 5), (1, 5) mismatch)
 x: array([], shape=(0, 5), dtype=float32)
 y: array([[4.318965e+02, 2.368963e+02, 1.020632e+03, 3.657931e+02,
        9.941006e-01]], dtype=float32)

I checked pytorch return values as well as onnx return values. They were different.
I checked the visual results. Onnx did not detect any bboxes. Visual results are not matching.

Can someone help resolve this? I am suspecting that this is because I am using my own checkpoint file and the classes are different from Coco dataset.

**Comment by suchig** [comment]
I figured out the reason. Interestingly the code to pull out dets and labels were as below in pytorch2onnx.py was as below

onnx_outputs = [_[-1] for _ in onnx_outputs]
ort_dets, ort_labels = onnx_outputs[:2]

I changed it as below since onnx_outputs was of the format [[],[]]
#onnx_outputs = [_[-1] for _ in onnx_outputs]
#ort_dets, ort_labels = onnx_outputs[:2]
ort_dets = onnx_outputs[0]
ort_labels = onnx_outputs[1]

Any reason why the original code did not work?

**Comment by RunningLeon** [comment]
@suchig Hi, thanks for the feedback. This may due to the compatibility of outputs with and without batch dim. This could be improved in the next iteration.

**Comment by suchig** [comment]
> @suchig Hi, thanks for the feedback. This may due to the compatibility of outputs with and without batch dim. This could be improved in the next iteration.

Could this be the reason of error in #5108? How do I pass batch dimension?

**Comment by RunningLeon** [comment]
You could try with the latest mmdetection and mmcv and follow the instruction in the doc https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html

**Comment by suchig** [comment]
> You could try with the latest mmdetection and mmcv and follow the instruction in the doc https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html

Yes. I followed this. Then I faced multiple errors. I changed some code in pytirch2onnx as mentioned above to fit my needs. I reinstalled mmcv per instructions here - https://github.com/open-mmlab/mmcv/blob/db6b0542c7ca13edcbad0bb90687bf680a685844/docs/onnxruntime_op.md

There are a lot version restrictions. mmcv throws error if I use anything other than onnxruntime 1.5.1.

**Comment by RunningLeon** [comment]
> There are a lot version restrictions. mmcv throws error if I use anything other than onnxruntime 1.5.1.
You could post the full error message here.

**Comment by RunningLeon** [comment]
Closed due to age. Feel free to reopen if you still have the issue.

**Comment by sarmientoj24** [comment]
Still have the issue @RunningLeon

**Comment by RunningLeon** [comment]
@sarmientoj24 Hi, first of all, please try with the standard config and ckpt provided by mmdetection.  If it works, then maybe something wrong with your model. Maybe you need to debug a little bit. BTW, you could try the deployment tool [mmdeploy](https://github.com/open-mmlab/mmdeploy). Any problem could be post there as well.

**Comment by sarmientoj24** [comment]
@RunningLeon I was able to make it successfully work with mmdeploy.

Quick question, does the deployed ONNX model has the preprocessing normalization built in? Or do we normalize manually? Is normalization still needed?

**Comment by RunningLeon** [comment]
@sarmientoj24 Hi, for mmdeploy, the normalization is excluded in the exported onnx. That means you have to normalize the input before feeding into onnx model.
