### ISSUE TITLE
onnx2trt parse onnx failed

### ISSUE THREAD

**Issue by suchig** [open-mmlab/mmdetection#5108]
Hi,

While converting onnx to tensorrt using onnx2tensorrt, I faced the below error. Any help?

RuntimeError: parse onnx failed:
In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims

**Comment by suchig** [comment]
Some additional information.
 
I was able to capture the node details of the onnx model. And I traversed the last few Verbose outputs from TensorRT.
 
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: Unsqueeze_278 [Unsqueeze]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 672
[TensorRT] VERBOSE: ModelImporter.cpp:125: Unsqueeze_278 [Unsqueeze] inputs: [672 -> ()], 
Traceback (most recent call last):
  File "test_tensorrt.py", line 149, in <module>
    verbose=True)
  File "test_tensorrt.py", line 42, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/mmcv/tensorrt/tensorrt_utils.py", line 148, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
 
I looked for Unsqueeze in the node details. I observed that this was the first node which had axis -1. The rest of them had axis 0. Now I have no clue how to map this back to the model
 
name: "Unsqueeze_278"
op_type: "Unsqueeze"
attribute {
  name: "axes"
  ints: -1
  type: INTS
}

Any help?

**Comment by RunningLeon** [comment]
@suchig Hi, could you provide more detailed info such as model type, version of TensorRT, PyTorch?

**Comment by suchig** [comment]
> @suchig Hi, could you provide more detailed info such as model type, version of TensorRT, PyTorch?

Sure
Model - Faster RCNN
TensorRT (I tried 7.2.2.1, 7.2.3.4, 8.0.0.3)
Pytorch - I tried 1.6 and 1.7

With TensorRT 7.2.x  I get Assertion Failed: axis >= 0 && axis < nbDims error
With TensorRT 8.x, I get Assertion failed: (inputs.at(1).is_weights()) && "This version of TensorRT only supports input K as an initializer."

**Comment by RunningLeon** [comment]
@suchig Hi, did you try with the latest mmdetection and mmcv?

**Comment by suchig** [comment]
> @suchig Hi, did you try with the latest mmdetection and mmcv?

Yes. I followed this to install mmcv - https://github.com/open-mmlab/mmcv/blob/db6b0542c7ca13edcbad0bb90687bf680a685844/docs/onnxruntime_op.md

**Comment by suchig** [comment]
> @suchig Hi, for `(inputs.at(1).is_weights()) && "This version of TensorRT only supports input K as an initializer."`, do you set the env variable `export ONNX_BACKEND=MMCVTensorRT` before run the tools of `pytorch2onnx.py`? You could refer to the doc : https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md

Yes. ONNX_BACKEND export is done per instructions

**Comment by RunningLeon** [comment]
@suchig Then, there should be no assertation error of TopK in TensorRT.

**Comment by foreverYoungGitHub** [comment]
Hi, @suchig @RunningLeon,

I meet same issue here. Which is `In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims`.

To be more specific:
- pytorch: 1.8.1
- mmcv: self-built pulled from master
- onnx: 1.9.0
- TensorRT: 7.2.1.6/7.2.3.4
- model: yolov3_d53_mstrain-608_273e_coco
- command to reproduce: 
```bash
python tools/deployment/pytorch2onnx.py     configs/yolo/yolov3_d53_mstrain-608_273e_coco.py     checkpoints/yolo/yolov3_d53_mstrain-608_273e_coco.pth     --output-file checkpoints/yolo/yolov3_d53_mstrain-608_273e_coco.onnx     --input-img demo/demo.jpg     --test-img tests/data/color.jpg     --shape 608 608     --mean 0 0 0     --std 255 255 255     --show     --verify       --cfg-options       model.test_cfg.nms_pre=200        model.test_cfg.max_per_img=200        model.test_cfg.deploy_nms_pre=300

python tools/deployment/onnx2tensorrt.py    checkpoints/yolo/yolov3_d53_mstrain-608_273e_coco.onnx     --trt-file  checkpoints/yolo/yolov3_d53_mstrain-608_273e_coco.trt    --input-img demo/demo.jpg     --shape 608 608     --mean 0 0 0     --std 255 255 255     --show     --verify
```

**Comment by RunningLeon** [comment]
@foreverYoungGitHub Hi, could you try with pytorch==1.6.0 and onnx==1.7.0? Currently, we did not test this feature with pytorch==1.8.1.
For more info, you could refer to the docs : 
- https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md
- https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/onnx2tensorrt.md
- https://mmcv.readthedocs.io/en/latest/tensorrt_plugin.html#how-to-build-tensorrt-plugins-in-mmcv

**Comment by RunningLeon** [comment]
Closed due to age. Feel free to reopen if you still have the issue.

**Comment by smile-care** [comment]
Is cuda11 supported?

**Comment by smile-care** [comment]
@RunningLeon

**Comment by RunningLeon** [comment]
@smile-care We did not test with cuda11. You could try with it.

**Comment by chuong98** [comment]
I have the same error, and the problem is due to Pytorch version.
- Using either `pytorch 1.6` or `pytorch 1.9` can convert pytorch model to onnx. Let say `model_pt16.onnx` and `model_pt19.onnx` , respectively.
- Only `model_pt16.onnx` can be converted to TensorRT successfully.
- The `model_pt19.onnx` will enconter error:
  > UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims

**Comment by RunningLeon** [comment]
@chuong98 Yes, we only tested with PyTorch==1.6.0.

**Comment by jiejie1993** [comment]
I met the same error with PyTorch==1.7.0. Any solution to it ?
`Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 254, in <module>
    verbose=args.verbose)
  File "tools/deployment/onnx2tensorrt.py", line 45, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/workspace/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims`

**Comment by Seraph1990** [comment]
@chuong98 Thank you! I tried successfully with CUDA 10.2, Torch 1.6,cuDNN 8.0.1,TensorRT 7.2.1.6.
