### ISSUE TITLE
How to set the norm_eval if the model is trained from scratch (small sample dataset, 1000 images)

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#5109]
Hi, dear author
Sorry to bother you
If I want to train the model from scratch (a small data set, about 1000 images, much smaller than the COCO dataset), is the effect of `norm_eval=True` or `norm_eval=False` good in the backbone? How does this value affect the final result? (norm_cfg=GN)
Thank you！

**Comment by hhaAndroid** [comment]
Eval mode does not affect GN. If you are using BN, it is best to set it to `norm_eval=False`.

**Comment by zhongqiu1245** [comment]
@hhaAndroid Hi
Thank you for your reply!
May I ask why setting `norm_eval=False` will achieve better results, and what is the reason behind it?
Thank you!

**Comment by hhaAndroid** [comment]
> norm_eval=False

Because you do not have pre-training weights, it is most appropriate to train all parameters.

**Comment by zhongqiu1245** [comment]
Thank you!
