### ISSUE TITLE
The weight of GN is 1 when resnet50 is initialized, but the weight of GN is 0 when forward

### ISSUE THREAD

**Issue by wedlight** [open-mmlab/mmdetection#5113]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
A clear and concise description of what the bug is The weight of GN is 1 when resnet50 is initialized, but the weight of GN is 0 when forward
![1](https://user-images.githubusercontent.com/79439187/117112797-2fa91880-adbc-11eb-97ef-8737bed37549.png)
![2](https://user-images.githubusercontent.com/79439187/117112824-3768bd00-adbc-11eb-9c5d-b7b39b59e715.png)

**Reproduction**

3. What dataset did you use?
widerface

**Comment by shinya7y** [comment]
[model.init_weights()](https://github.com/open-mmlab/mmdetection/blob/931d96e5441b99227dce101ebace5d60c2853830/tools/train.py#L162) resets the weight of gn3 to 0 if zero_init_residual == True (default).
https://github.com/open-mmlab/mmdetection/blob/931d96e5441b99227dce101ebace5d60c2853830/mmdet/models/backbones/resnet.py#L413-L423
