### ISSUE TITLE
The prediction does not match the number of categories output

### ISSUE THREAD

**Issue by noobying** [open-mmlab/mmdetection#5120]
In the cls branch of DETR, the CE loss is be used and the every slot's cls vector's length is 81(80+1).but in the Deformable DETR,the length is 80, and the loss is focal loss ,but the gt labels is 81 category same as DETR, how did the focal loss to solve the dismatch of 80 and 81.

**Comment by hhaAndroid** [comment]
@noobying The focal loss uses a sigmoid operation, which is calculated channel by channel, so only 80 is required.

**Comment by noobying** [comment]
thanks

**Comment by Chop1** [comment]
In the codebase

```python
    def forward(self, mlvl_feats, img_metas):
        """Forward function.
        Args:
            mlvl_feats (tuple[Tensor]): Features from the upstream
                network, each is a 4D-tensor with shape
                (N, C, H, W).
            img_metas (list[dict]): List of image information.
        Returns:
            all_cls_scores (Tensor): Outputs from the classification head, \
                shape [nb_dec, bs, num_query, cls_out_channels]. Note \
                cls_out_channels should includes background.
```

the comment state that  ```cls_out_channels should includes background.```
But this is only done using non-sigmoid function. See the code:

```python
        if self.loss_cls.use_sigmoid:
            self.cls_out_channels = num_classes
        else:
            self.cls_out_channels = num_classes + 1
```

I think that the comment is missleading ?
