### ISSUE TITLE
Incompability between rtx3060 and mmdet in win10

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdetection#5123]
My environment contains windows 10, python 3.7, pytorch 1.3.1 and display card rtx3060. Due to the display card, I can only install cuda 11.1 or above. So I installed cuda 11.1. 

Then I compiled mmcv-full 1.1.5 and mmdetection 2.7.0 successfully. When I tried to train a model, say mask_rcnn, it took a long time for it to finish loading data and start training, like 30 minutes. This did not happen before when I used a rtx2080ti display card with cuda 10.1 or 11.1. 

Does anyone encounter this issue? I think this issue is due to the Incompability between the rtx3060 card and mmdet. Is there a way we can solve this?

**Comment by ZwwWayne** [comment]
PyTorch 1.3.1 might not be compatible with 3060. You may try the newest PyTorch and mmdet.

**Comment by yeungkong** [comment]
> PyTorch 1.3.1 might not be compatible with 3060. You may try the newest PyTorch and mmdet.

I tried pytorch 1.8.1 and 1.7.0, but mmdet cannot be compiled successfully. I tried pytorch 1.6.0 and it works the same in terms of taking a long time to finish loading data and start training.

**Comment by Kaeseknacker** [comment]
I have a similar problem with RTX3060 and Ubuntu18.04:

Environment:
```bash
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 3060
CUDA_HOME: /home/user/lib/cuda_11.1.1_455.32.00
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0
OpenCV: 4.5.2
MMCV: 1.3.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.12.0+7971bbd
```

Error:
```bash
python verify_installation.py
/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/utils/registry.py:250: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
Use load_from_local loader
/home/user/Programme/DroneDetection/mmdetection/mmdet/datasets/utils.py:68: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
Traceback (most recent call last):
  File "verify_installation.py", line 11, in <module>
    inference_detector(model, 'mmdetection/demo/demo.jpg')
  File "/home/user/Programme/DroneDetection/mmdetection/mmdet/apis/inference.py", line 147, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/detectors/base.py", line 169, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/detectors/base.py", line 146, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/detectors/two_stage.py", line 196, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/dense_heads/rpn_test_mixin.py", line 36, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 182, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 582, in get_bboxes
    scale_factors, cfg, rescale)
  File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 248, in _get_bboxes
    cfg.nms)
  File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/ops/nms.py", line 278, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/ops/nms.py", line 144, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/ops/nms.py", line 20, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

Test pytorch:
```python
import torch
import sys
print('A', sys.version)
print('B', torch.__version__)
print('C', torch.cuda.is_available())
print('D', torch.backends.cudnn.enabled)
device = torch.device('cuda')
print('E', torch.cuda.get_device_properties(device))
print('F', torch.tensor([1.0, 2.0]).cuda())
print('G', torch.cuda.get_arch_list())
x = torch.rand(5,3)
print(x)

A 3.7.10 (default, Feb 26 2021, 18:47:35)
[GCC 7.3.0]
B 1.8.0
C True
D True
E _CudaDeviceProperties(name='GeForce RTX 3060', major=8, minor=6, total_memory=12051MB, multi_processor_count=28)
F tensor([1., 2.], device='cuda:0')
G ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
tensor([[0.2695, 0.8339, 0.2414],
        [0.4402, 0.3113, 0.0689],
        [0.2836, 0.4589, 0.9722],
        [0.9486, 0.1660, 0.3713],
        [0.6882, 0.8315, 0.5367]])
```

Is my GPU really too new for mmdetection?

**Comment by JunyuSu** [comment]
> I have a similar problem with RTX3060 and Ubuntu18.04:
> 
> Environment:
> 
> ```shell
> sys.platform: linux
> Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
> CUDA available: True
> GPU 0: GeForce RTX 3060
> CUDA_HOME: /home/user/lib/cuda_11.1.1_455.32.00
> NVCC: Build cuda_11.1.TC455_06.29190527_0
> GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> PyTorch: 1.8.0
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.1
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
>   - CuDNN 8.0.5
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> 
> TorchVision: 0.9.0
> OpenCV: 4.5.2
> MMCV: 1.3.3
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 11.1
> MMDetection: 2.12.0+7971bbd
> ```
> 
> Error:
> 
> ```shell
> python verify_installation.py
> /home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/utils/registry.py:250: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
>   'The old API of register_module(module, force=False) '
> Use load_from_local loader
> /home/user/Programme/DroneDetection/mmdetection/mmdet/datasets/utils.py:68: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
>   'data pipeline in your config file.', UserWarning)
> Traceback (most recent call last):
>   File "verify_installation.py", line 11, in <module>
>     inference_detector(model, 'mmdetection/demo/demo.jpg')
>   File "/home/user/Programme/DroneDetection/mmdetection/mmdet/apis/inference.py", line 147, in inference_detector
>     results = model(return_loss=False, rescale=True, **data)
>   File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/detectors/base.py", line 169, in forward
>     return self.forward_test(img, img_metas, **kwargs)
>   File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/detectors/base.py", line 146, in forward_test
>     return self.simple_test(imgs[0], img_metas[0], **kwargs)
>   File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/detectors/two_stage.py", line 196, in simple_test
>     proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
>   File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/dense_heads/rpn_test_mixin.py", line 36, in simple_test_rpn
>     proposal_list = self.get_bboxes(*rpn_outs, img_metas)
>   File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 182, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 582, in get_bboxes
>     scale_factors, cfg, rescale)
>   File "/home/user/Programme/DroneDetection/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 248, in _get_bboxes
>     cfg.nms)
>   File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/ops/nms.py", line 278, in batched_nms
>     dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
>   File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
>     output = old_func(*args, **kwargs)
>   File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/ops/nms.py", line 144, in nms
>     inds = NMSop.apply(boxes, scores, iou_threshold, offset)
>   File "/home/user/miniconda3/envs/mmdet-2.12_v2/lib/python3.7/site-packages/mmcv/ops/nms.py", line 20, in forward
>     bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
> RuntimeError: CUDA error: no kernel image is available for execution on the device
> ```
> 
> Test pytorch:
> 
> ```python
> import torch
> import sys
> print('A', sys.version)
> print('B', torch.__version__)
> print('C', torch.cuda.is_available())
> print('D', torch.backends.cudnn.enabled)
> device = torch.device('cuda')
> print('E', torch.cuda.get_device_properties(device))
> print('F', torch.tensor([1.0, 2.0]).cuda())
> print('G', torch.cuda.get_arch_list())
> x = torch.rand(5,3)
> print(x)
> 
> A 3.7.10 (default, Feb 26 2021, 18:47:35)
> [GCC 7.3.0]
> B 1.8.0
> C True
> D True
> E _CudaDeviceProperties(name='GeForce RTX 3060', major=8, minor=6, total_memory=12051MB, multi_processor_count=28)
> F tensor([1., 2.], device='cuda:0')
> G ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
> tensor([[0.2695, 0.8339, 0.2414],
>         [0.4402, 0.3113, 0.0689],
>         [0.2836, 0.4589, 0.9722],
>         [0.9486, 0.1660, 0.3713],
>         [0.6882, 0.8315, 0.5367]])
> ```
> 
> Is my GPU really too new for mmdetection?

Have you solve the problem? I meet the exactly same problem with RTX 3090!

**Comment by Kaeseknacker** [comment]
Yes, I solved it with the following configuration:
```
pytorch: 1.7.0
CUDA 11.0.3
cudatoolkit (in conda env): 11.0.221
mmcv-full: 1.2.4 / cu110 / torch1.7.0
mmdetection: 2.10 (older version, but I think not necessary)
```
