### ISSUE TITLE
pytorch2onnx.py:  AssertionError: `max_shape` should be tensor of (h,w) for onnx

### ISSUE THREAD

**Issue by hbchen-hf** [open-mmlab/mmdetection#5125]
AssertionError: `max_shape` should be tensor of (h,w) for onnx

**Comment by RunningLeon** [comment]
@hbchen-hf Hi, could you provide detailed info about this issue?

**Comment by hbchen-hf** [comment]
mmd:2.12.0
mmcv:1.3.3
CUDA:10.1


python tools/deployment/pytorch2onnx.py cascade_rcnn_s101_fpn-backbone+head_mstrain-range_1x.py epoch_12.pth --input-img 00168116.jpg --output-file tmp.onnx --verify&nbsp;




/data/hbchen/mmdetection/mmdet/models/builder.py:52: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
&nbsp; 'please specify them in model', UserWarning)
Use load_from_local loader
Use load_from_local loader
/data/hbchen/mmdetection/mmdet/models/dense_heads/anchor_head.py:573: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; img_metas[i]['scale_factor'] for i in range(cls_scores[0].shape[0])
/data/hbchen/mmdetection/mmdet/models/dense_heads/rpn_head.py:123: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
&nbsp; cfg.nms_pre, device=cls_scores[0].device, dtype=torch.long)
/data/hbchen/mmdetection/mmdet/models/dense_heads/rpn_head.py:127: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; assert rpn_cls_score.size()[-2:] == rpn_bbox_pred.size()[-2:]
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:62: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; if k <= 0 or size <= 0:
/data/hbchen/mmdetection/mmdet/models/dense_heads/rpn_head.py:146: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; if nms_pre &gt; 0:
/data/hbchen/mmdetection/mmdet/models/dense_heads/rpn_head.py:147: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; _, topk_inds = scores.topk(nms_pre)
/data/hbchen/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:87: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; assert pred_bboxes.size(0) == bboxes.size(0)
/data/hbchen/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:89: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; assert pred_bboxes.size(1) == bboxes.size(1)
/data/hbchen/mmdetection/mmdet/models/dense_heads/rpn_head.py:192: UserWarning: In rpn_proposal or test_cfg, nms_thr has been moved to a dict named nms as iou_threshold, max_num has been renamed as max_per_img, name of original arguments and the way to specify iou_threshold of NMS will be deprecated.
&nbsp; 'In rpn_proposal or test_cfg, '
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:118: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
&nbsp; iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:119: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
&nbsp; score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:123: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
&nbsp; nms_pre = torch.tensor(pre_top_k, device=scores.device, dtype=torch.long)
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:126: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; if nms_pre &gt; 0:
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:128: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; _, topk_inds = max_scores.topk(nms_pre)
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:147: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; batch_inds = torch.randint(batch_size, (num_fake_det, 1))
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:148: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; cls_inds = torch.randint(num_class, (num_fake_det, 1))
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:149: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; box_inds = torch.randint(num_box, (num_fake_det, 1))
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:171: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator index_put_. This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
&nbsp; mask[pos_inds, :] += 1
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:180: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
&nbsp; after_top_k, device=scores.device, dtype=torch.long)
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:183: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; if nms_after &gt; 0:
/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py:184: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; _, topk_inds = scores.topk(nms_after)
/data/hbchen/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py:281: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; num_imgs = len(proposal_list)
/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/tensor.py:426: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
&nbsp; 'incorrect results).', category=RuntimeWarning)
/data/hbchen/mmdetection/mmdet/core/bbox/transforms.py:70: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; if bboxes.size(0) &gt; 0:
/data/hbchen/mmcv/mmcv/ops/roi_align.py:79: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; assert rois.size(1) == 5, 'RoI must be (idx, x1, y1, x2, y2)!'
/data/hbchen/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py:300: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; len(proposals) for proposals in proposal_list)
/data/hbchen/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py:511: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; assert rois.size(1) == 4 or rois.size(1) == 5, repr(rois.shape)
/data/hbchen/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py:517: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; assert bbox_pred.size(1) == 4
/data/hbchen/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py:519: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
&nbsp; if rois.size(1) == 4:
Traceback (most recent call last):
&nbsp; File "tools/deployment/pytorch2onnx.py", line 275, in <module&gt;
&nbsp; &nbsp; dynamic_export=args.dynamic_export)
&nbsp; File "tools/deployment/pytorch2onnx.py", line 77, in pytorch2onnx
&nbsp; &nbsp; dynamic_axes=dynamic_axes)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
&nbsp; &nbsp; strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
&nbsp; &nbsp; dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
&nbsp; &nbsp; fixed_batch_size=fixed_batch_size)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/onnx/utils.py", line 249, in _model_to_graph
&nbsp; &nbsp; graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/onnx/utils.py", line 206, in _trace_and_get_graph_from_model
&nbsp; &nbsp; trace, torch_out, inputs_states = torch.jit.get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/jit/__init__.py", line 275, in get_trace_graph
&nbsp; &nbsp; return LegacyTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/jit/__init__.py", line 352, in forward
&nbsp; &nbsp; out = self.inner(*trace_inputs)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
&nbsp; &nbsp; result = self._slow_forward(*input, **kwargs)
&nbsp; File "/home/omnisky/anaconda3/envs/hbchen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "/data/hbchen/mmcv/mmcv/runner/fp16_utils.py", line 95, in new_func
&nbsp; &nbsp; return old_func(*args, **kwargs)
&nbsp; File "/data/hbchen/mmdetection/mmdet/models/detectors/base.py", line 169, in forward
&nbsp; &nbsp; return self.forward_test(img, img_metas, **kwargs)
&nbsp; File "/data/hbchen/mmdetection/mmdet/models/detectors/base.py", line 146, in forward_test
&nbsp; &nbsp; return self.simple_test(imgs[0], img_metas[0], **kwargs)
&nbsp; File "/data/hbchen/mmdetection/mmdet/models/detectors/two_stage.py", line 183, in simple_test
&nbsp; &nbsp; x, proposal_list, img_metas, rescale=rescale)
&nbsp; File "/data/hbchen/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py", line 316, in simple_test
&nbsp; &nbsp; for j in range(num_imgs)
&nbsp; File "/data/hbchen/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py", line 316, in <listcomp&gt;
&nbsp; &nbsp; for j in range(num_imgs)
&nbsp; File "/data/hbchen/mmcv/mmcv/runner/fp16_utils.py", line 182, in new_func
&nbsp; &nbsp; return old_func(*args, **kwargs)
&nbsp; File "/data/hbchen/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 524, in regress_by_class
&nbsp; &nbsp; rois[:, 1:], bbox_pred, max_shape=img_meta['img_shape'])
&nbsp; File "/data/hbchen/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py", line 92, in decode
&nbsp; &nbsp; self.add_ctr_clamp, self.ctr_clamp)
&nbsp; File "/data/hbchen/mmcv/mmcv/utils/parrots_jit.py", line 21, in wrapper_inner
&nbsp; &nbsp; return func(*args, **kargs)
&nbsp; File "/data/hbchen/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py", line 254, in delta2bbox
&nbsp; &nbsp; x1, y1, x2, y2 = dynamic_clip_for_onnx(x1, y1, x2, y2, max_shape)
&nbsp; File "/data/hbchen/mmdetection/mmdet/core/export/onnx_helper.py", line 23, in dynamic_clip_for_onnx
&nbsp; &nbsp; torch.Tensor), '`max_shape` should be tensor of (h,w) for onnx'
AssertionError: `max_shape` should be tensor of (h,w) for onnx





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月8日(星期六) 下午2:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection] pytorch2onnx.py:  AssertionError: `max_shape` should be tensor of (h,w) for onnx (#5125)





 
@hbchen-hf Hi, could you provide detailed info about this issue?

**Comment by RunningLeon** [comment]
@hbchen-hf Hi, we do not support **cascade_rcnn** model for exporting to ONNX by far. You could refer to the doc.
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md#list-of-supported-models-exportable-to-onnx
