### ISSUE TITLE
yolof error

### ISSUE THREAD

**Issue by chaos1992** [open-mmlab/mmdetection#5126]
I train the model use configs/yolof/yolof_r50_c5_8x8_1x_coco.py, and got this error:

-----------------------------
/workspace/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [16,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "train.py", line 157, in <module>
    main()
  File "train.py", line 153, in main
    meta=meta)
  File "/workspace/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/workspace/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/workspace/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/workspace/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/workspace/mmcv/parallel/distributed.py", line 51, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/workspace/mmdet/models/detectors/base.py", line 233, in train_step
    losses = self(**data)
  File "/opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/mmdet/models/detectors/base.py", line 167, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/workspace/mmdet/models/detectors/single_stage.py", line 78, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/workspace/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/workspace/mmcv/runner/fp16_utils.py", line 182, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/mmdet/models/dense_heads/yolof_head.py", line 186, in loss
    label_channels=label_channels)
  File "/workspace/mmdet/models/dense_heads/yolof_head.py", line 290, in get_targets
    unmap_outputs=unmap_outputs)
  File "/workspace/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "workspace/mmdet/models/dense_heads/yolof_head.py", line 381, in _get_targets_single
    gt_bboxes)
  File "/workspace/mmdet/core/bbox/samplers/pseudo_sampler.py", line 35, in sample
    assign_result.gt_inds > 0, as_tuple=False).squeeze(-1).unique()
RuntimeError: copy_if failed to synchronize: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /workspace/c10/cuda/CUDACachingAllocator.cpp:856)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x57 (0x7fa4dd144137 in /opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1a760 (0x7fa4e64a6760 in /opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1d21f (0x7fa4e64a921f in /opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x4d (0x7fa4dd12c90d in /opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x476239 (0x7fa4e3cfc239 in /opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x4762f1 (0x7fa4e3cfc2f1 in /opt/conda/envs/python3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x19aaae (0x557d58053aae in ./python_bin)
frame #7: <unknown function> + 0xf2868 (0x557d57fab868 in ./python_bin)
frame #8: <unknown function> + 0xf2987 (0x557d57fab987 in ./python_bin)
frame #9: <unknown function> + 0xf2987 (0x557d57fab987 in ./python_bin)
frame #10: <unknown function> + 0xf2247 (0x557d57fab247 in ./python_bin)
frame #11: <unknown function> + 0xf20d7 (0x557d57fab0d7 in ./python_bin)
frame #12: <unknown function> + 0xf20ed (0x557d57fab0ed in ./python_bin)
frame #13: <unknown function> + 0xf20ed (0x557d57fab0ed in ./python_bin)
frame #14: <unknown function> + 0xf20ed (0x557d57fab0ed in ./python_bin)
frame #15: <unknown function> + 0xf20ed (0x557d57fab0ed in ./python_bin)
frame #16: <unknown function> + 0xf20ed (0x557d57fab0ed in ./python_bin)
frame #17: <unknown function> + 0xf20ed (0x557d57fab0ed in ./python_bin)
frame #18: PyDict_SetItem + 0x3da (0x557d57ff1d7a in ./python_bin)
frame #19: PyDict_SetItemString + 0x4f (0x557d57ff8c5f in ./python_bin)
frame #20: PyImport_Cleanup + 0x99 (0x557d5805ddc9 in ./python_bin)
frame #21: Py_FinalizeEx + 0x61 (0x557d580c8961 in ./python_bin)
frame #22: Py_Main + 0x35e (0x557d580d2cae in ./python_bin)
frame #23: main + 0xee (0x557d57f9cf2e in ./python_bin)
frame #24: __libc_start_main + 0xf5 (0x7fa4f0a60445 in /lib64/libc.so.6)
frame #25: <unknown function> + 0x1c327f (0x557d5807c27f in ./python_bin)
-----------------------------

I think this error is caused by UniformAssigner, but I don't know how to fix it.

**Comment by hhaAndroid** [comment]
@chaos1992  Hi, Please use cuda10 and above drivers for training. Errors will be reported on lower versions.

**Comment by chaos1992** [comment]
@hhaAndroid hi, I have used cuda10.0 to train it.

This is my environment:
cuda10.0
python3.6
pytorch1.3.1

I guess that pos_ignore_thr and neg_ignore_thr in uniform_assigner may be cause this bug

**Comment by hhaAndroid** [comment]
> @hhaAndroid hi, I have used cuda10.0 to train it.
> 
> This is my environment:
> cuda10.0
> python3.6
> pytorch1.3.1
> 
> I guess that pos_ignore_thr and neg_ignore_thr in uniform_assigner may be cause this bug

I have also encountered this error in the lower version, but it will not be changed to 10.1 and above.

**Comment by hhaAndroid** [comment]
> @hhaAndroid hi, I have used cuda10.0 to train it.
> 
> This is my environment:
> cuda10.0
> python3.6
> pytorch1.3.1
> 
> I guess that pos_ignore_thr and neg_ignore_thr in uniform_assigner may be cause this bug

I have an illegal memory out-of-bounds error on CUDA9.0, but CUDA10.1 is normal.

**Comment by ZwwWayne** [comment]
@hhaAndroid Shall we update the pages like FAQ about this issue? Or update the readme.md of YOLOF.
