### ISSUE TITLE
when the fp16 training can be updated?

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#513]
The ms training according to your paper really cost lots of memory,so when the fp16 training can be updated?

**Comment by hellock** [comment]
It is ongoing, may be released in next few weeks.

**Comment by hellock** [comment]
#520

**Comment by runzeer** [comment]
Thanks for your reply! But when I use the fp16 training,it did not save the memory .When I use the mask_r50_fpn_fp16.py, it cost the same as fp32. So is anything wrong with the usage of the fp16 training?
Should the mmdetection be setup again?

**Comment by runzeer** [comment]
Could you provide the memory usage for more models like HTC ?  The memory usage monitored by nvidia-smi is larger than the memory used for the mask-r50-fpn-fp16-1x.py. The usage in your report said 3.3GB, but the memory usage monitored by nvidia-smi is about 5.5GB. Is it normal?

**Comment by yhcao6** [comment]
You should use the latest mmcv, which will show memory usage automatically.

**Comment by yhcao6** [comment]
> Thanks for your reply! But when I use the fp16 training,it did not save the memory .When I use the mask_r50_fpn_fp16.py, it cost the same as fp32. So is anything wrong with the usage of the fp16 training?
> Should the mmdetection be setup again?

you should setup again

**Comment by runzeer** [comment]
Thanks for your answer.But the memory cost shown from mmcv is much smaller than the nvidia-smi ,is it noamal?

**Comment by yhcao6** [comment]
It is normal. The nvidia-smi number includes space the allocated by the CUDA driver when it loads PyTorch and other things, this can be large. So currently mmcv use 
 ```
torch.cuda.max_memory_allocated()
```
to measure memory usage (reduce max memory over all GPUs).

By the way, could you show the memory usage under FP32 and FP16 when looking at nvidia-smi?

**Comment by runzeer** [comment]
The fp16 and fp32 memory usage shown by mmcv is 2.8G and 3.8G while the memory usage shown by nvidia-smi is 6.6G and 8.6G, which is different from the result you provided. So is there anything wrong with my settings?
