### ISSUE TITLE
About bad performance using VfNet  

### ISSUE THREAD

**Issue by Yangr116** [open-mmlab/mmdetection#5131]
I use the vfnet in my own dataset. when I change the 'score_thr' from 0.05 to 0.001 in test_cfg，Sometimes the mAP will drop by 10%. That looks random.

**Comment by cl886699** [comment]
why you change score_thr to 0.001

**Comment by Yangr116** [comment]
> why you change score_thr to 0.001

 I would like to decrease the min_score of soft-nms so that obtaining high mAP, but I  accidentally set "score_thr" to 0.001. That gave me bad results. So far I still don’t know what lead to the case.

**Comment by jshilong** [comment]
Maybe because `softnms` would reweight the score, too many boxes with low scores may disturb the results
You can change to NMS and try again

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
