### ISSUE TITLE
TypeError: FasterRCNN: init() got an unexpected keyword argument 'bbox_roi_extractor'

### ISSUE THREAD

**Issue by timf34** [open-mmlab/mmdetection#5138]
Hi, I seem to have the exact same issue as in #3148 however, I should note that I am only trying to run the model for inference on a custom dataset, and that I have tried updating my config file to be compatible with 2.x and I have also upgraded my model using 'tools/upgrade_model_version.py', however when I try to run. Also note that I commented over there at #3148 before realising it was closed, and so I have opened a new issue - hope that's ok

model = init_detector(config, checkpoint, device='cuda:0')

I get the following error

Exception ignored in: <function _TemporaryFileCloser.del at 0x7f71a099b680>
Traceback (most recent call last):
File "/usr/lib/python3.7/tempfile.py", line 587, in del
self.close()
File "/usr/lib/python3.7/tempfile.py", line 583, in close
unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpjgs19fhc/tmplgmb4rko.py'
Exception ignored in: <function _TemporaryFileCloser.del at 0x7f71a099b680>
Traceback (most recent call last):
File "/usr/lib/python3.7/tempfile.py", line 587, in del
self.close()
File "/usr/lib/python3.7/tempfile.py", line 583, in close
unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpf2fshekp/tmp6ohgok6v.py'

TypeError Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
50 try:
---> 51 return obj_cls(**args)
52 except Exception as e:

TypeError: init() got an unexpected keyword argument 'bbox_roi_extractor'

During handling of the above exception, another exception occurred:

TypeError Traceback (most recent call last)
5 frames
/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
52 except Exception as e:
53 # Normal TypeError does not print class name.
---> 54 raise type(e)(f'{obj_cls.name}: {e}')
55
56

TypeError: FasterRCNN: init() got an unexpected keyword argument 'bbox_roi_extractor'

My config file is as follows:

`# model settings
model = dict(
type='FasterRCNN',
#pretrained='open-mmlab://resnext101_64x4d',
backbone=dict(
type='ResNeXt',
depth=101,
groups=64,
base_width=4,
num_stages=4,
out_indices=(0, 1, 2, 3),
frozen_stages=1,
style='pytorch'),
neck=dict(
type='FPN',
in_channels=[256, 512, 1024, 2048],
out_channels=256,
num_outs=5),
rpn_head=dict(
type='RPNHead',
in_channels=256, # The input channels of each input feature map, this is consistent with the output channels of neck
feat_channels=256, # Feature channels of convolutional layers in the head.
anchor_generator=dict( # The config of anchor generator
type='AnchorGenerator',
scales=[8],
ratios=[0.5, 1.0, 2.0],
strides=[4, 8, 16, 32, 64]),
bbox_coder=dict( # Config of box coder to encode and decode the boxes during training and testing
type='DeltaXYWHBBoxCoder',
target_means=[0.0, 0.0, 0.0, 0.0],
target_stds=[1.0, 1.0, 1.0, 1.0]),
loss_cls=dict( # Config of loss function for the classification branch
type='CrossEntropyLoss', # Type of loss for classification branch, we also support FocalLoss etc.
use_sigmoid=True, # RPN usually perform two-class classification, so it usually uses sigmoid function.
loss_weight=1.0), # Loss weight of the classification branch.
loss_bbox=dict( # Config of loss function for the regression branch.
type='L1Loss',
loss_weight=1.0)), # Loss weight of the regression branch.
bbox_roi_extractor=dict(
type='SingleRoIExtractor',
roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
out_channels=256,
featmap_strides=[4, 8, 16, 32]),
bbox_head=dict(
type='SharedFCBBoxHead',
num_fcs=2,
in_channels=256,
fc_out_channels=1024,
roi_feat_size=7,
num_classes=4,
target_means=[0., 0., 0., 0.],
target_stds=[0.1, 0.1, 0.2, 0.2],
reg_class_agnostic=False,
loss_cls=dict(
type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
roi_head=dict(
type='StandardRoIHead',
bbox_roi_extractor=dict(
type='SingleRoIExtractor',
roi_layer=dict(
type='RoIAlign',
output_size=7,
sampling_ratio=0),
out_channels=256,
featmap_strides=[4, 8, 16, 32]),
bbox_head=dict( # Config of box head in the RoIHead.
type='Shared2FCBBoxHead',
in_channels=256,
fc_out_channels=1024, # Output feature channels of FC layers.
roi_feat_size=7, # Size of RoI features
num_classes=4,
bbox_coder=dict( # Box coder used in the second stage.
type='DeltaXYWHBBoxCoder',
target_means=[0.0, 0.0, 0.0, 0.0],
target_stds=[0.1, 0.1, 0.2, 0.2]),
reg_class_agnostic=False,
loss_cls=dict(
type='CrossEntropyLoss',
use_sigmoid=False, # Whether to use sigmoid.
loss_weight=1.0), # Loss weight of the classification branch.
loss_bbox=dict(
type='L1Loss',
loss_weight=1.0))))
test_cfg=dict(
rpn=dict(
nms_pre=1000,
max_per_img=1000,
nms=dict(type='nms', iou_threshold=0.7),
min_bbox_size=0),
rcnn=dict(
score_thr=0.05,
nms=dict(type='nms', iou_threshold=0.5),
max_per_img=100)
# soft-nms is also supported for rcnn testing
# e.g., nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05)
)

`

Do you see where I am going wrong - it would be greatly appreciated!
Thanks

**Comment by shinya7y** [comment]
`bbox_roi_extractor` appears twice.

```python
# unexpected
bbox_roi_extractor=dict(
    type='SingleRoIExtractor',

roi_head=dict(
    # expected
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
```

**Comment by wulala-max** [comment]
I have not  upgrade my model using 'tools/upgrade_model_version.py',because Idon't know how to use,I just stay at training stage using my own data and modified model base on faster rcnn,and when try to train encounter the issue TypeError: FasterRCNN: __init__() got an unexpected keyword argument 'bbox_roi_extractor';maybe because my code is based on older code ,but I don't know how to solve

envs:
cuda10.1,pytorch1.5.0,mmcv-full =1.3.17
mmdet  __version__ = '1.0.rc0+c64beaf' 
Traceback (most recent call last):
  File "tools/train.py", line 146, in <module>
    main()
  File "tools/train.py", line 117, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/vipuser/Desktop/mmdetection/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/vipuser/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/vipuser/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/vipuser/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FasterRCNN: __init__() got an unexpected keyword argument 'bbox_roi_extractor'




model:
model = dict(
    type='FasterRCNNMydata',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHeadMY',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[1., 1/2., 2., 1/3., 3., 1/5., 5.],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    bbox_roi_extractor=dict(
        type='MultiRoIExtractor',
        #type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=dict(
        type='SharedFCMultiLvlsBBoxHeadDOTA',
        # type='SharedFCBBoxHeadMY',
        num_fcs=2,
        in_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=5,
        # target_means=[0., 0., 0., 0.],
        # target_stds=[0.1, 0.1, 0.2, 0.2],
        hor_target_means=[0., 0., 0., 0.], ## [x, y, w, h]
        hor_target_stds=[0.1, 0.1, 0.2, 0.2], ## [x, y, w, h]
        target_means=[0., 0., 0., 0., 0.], ## [x, y, w, h, theta]
        target_stds=[0.1, 0.1, 0.2, 0.2, 0.2], ## [x, y, w, h, theta]
        reg_class_agnostic=False,
        #交叉熵
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        smoothl1_beta=1 / 9.0,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))

diff_r_threshold = {'car':0.4, 'bus':0.3, 'freight car':0.01, 'truck':0.4}
diff_h_threshold = {'car':0.4, 'bus':0.3, 'freight car':0.01, 'truck':0.01}

diff_r_max_num = {'car':100, 'bus':200, 'freight car':100, 'truck':300}
diff_h_max_num = {'car':100, 'bus':200, 'freight car':100, 'truck':300}

test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        #score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100,
        score_thr_h = 0.05, nms_h = dict(type = 'nms', iou_thr = 0.4), max_per_cls_h = 100, 
        score_thr_r = 0.05, nms_r = dict(type = 'nms_rotate', iou_thr = 0.4), max_per_cls_r = 100)
        # score_thr_h = 0.05, nms_h = dict(type = 'nms', iou_thr = diff_h_threshold), max_per_cls_h = diff_h_max_num, 
        # score_thr_r = 0.05, nms_r = dict(type = 'nms_rotate', iou_thr = diff_r_threshold), max_per_cls_r = diff_r_max_num)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)
)
# dataset settings，数据集设置
## 定义RGB通道的均值和标注差，这个最好是自己数据集的所有数据进行求解，包含训练和测试集，训练测试比例为9:1
# 输入图像初始化，减去均值mean并处以方差std，to_rgb表示将bgr转为rgb
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),   #在mmdet/datasets/pipeline/loading
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(640, 512), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    # meta_keys=('filename', 'ori_shape', 'img_shape', 'pad_shape','scale_factor', 'flip', 'img_norm_cfg')):

    dict(type='Collect', keys=['img', 'img2', 'gt_bboxes', 'gt_labels', 'hor_gt_boxes', 'gt_bboxes_ignore']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(640, 512),
        flip=False,
        # flip_v=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img', 'img2']),
            dict(type='Collect', keys=['img', 'img2']),
        ])
]
# 选择实验的数据集格式
dataset_type = 'MyDataset'
data_root = '/test/datasets/RGB-Infrared/path/'


data = dict(
    imgs_per_gpu=1,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'train_rgb.txt', 
        img_prefix=None,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_minival2017.json',
        img_prefix=None,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'test_rgb.txt', 
        img_prefix=None,
        pipeline=test_pipeline))
# optimizer# 优化参数，lr为学习率，momentum为动量因子，weight_decay为权重衰减因子
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 5,
    step=[8, 11])
    # step=[15, 22])

#保存训练所得权重文件的间隔为1，即一次迭代保存一次，log间隔为50个batch
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings

#一共12个epoch
total_epochs = 12
# total_epochs = 24
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/faster_rcnn_r50_fpn_1x_mydata'
load_from = None
resume_from = None
workflow = [('train', 1)]
