### ISSUE TITLE
你好，新手有一些关于mmdet问题

### ISSUE THREAD

**Issue by lmk123568** [open-mmlab/mmdetection#5146]
1. 怎么得到模型的推理速度，比如得到fps，以及poset process时间
2. 请教一下怎么在中断点继续训练，而不是加载预训练模型
3. 多卡训练有两个写法
```
# 写法1
CUDA_VISIBLE_DEVICES=0,1,2,3 PORT=29500 ./tools/dist_train.sh configs/retinanet_r50_fpn_1x_voc.py 4
#写法2
python tools/train.py configs/retinanet_r50_fpn_1x_voc.py --gpus 4
```
这两个之间有没有区别

如果能回复我的问题，将不胜感激

**Comment by xvjiarui** [comment]
Hi @lmk123568 
Please use English or English+Chinese for issue. 

1. You may checkpoint https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/benchmark.py
2. You may use `--resume`.
3. The first one is distributed training, the second one is non-distributed training.
