### ISSUE TITLE
where can be download :open-mmlab://resnext101_64x4d

### ISSUE THREAD

**Issue by aishangmaxiaoming** [open-mmlab/mmdetection#5149]

**Comment by RangiLyu** [comment]
You can download from here: https://download.openmmlab.com/pretrain/third_party/resnext101_64x4d-ee2c6f71.pth

And you can find download links of all pretrained backbone weights in the JSON files from here: https://github.com/open-mmlab/mmcv/tree/master/mmcv/model_zoo
