### ISSUE TITLE
mmcv/utils/registry.py", line 171, in build_from_cfg     return obj_cls(**args) TypeError: __init__() got an unexpected keyword argument '_delete_'

### ISSUE THREAD

**Issue by aishangmaxiaoming** [open-mmlab/mmdetection#5151]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/67897601/118095575-d6b43280-b402-11eb-9b55-30b03c29e9aa.png">

**Comment by ZwwWayne** [comment]
This means that you add unnecessary `_delete_` in your config. You can avoid this issue by simply remove that.
