### ISSUE TITLE
 data['category_id'] = self.cat_ids[label]  IndexError: list index out of range

### ISSUE THREAD

**Issue by aishangmaxiaoming** [open-mmlab/mmdetection#5152]
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/67897601/118099628-10d40300-b408-11eb-9770-2e5f773ddcdf.png">

**Comment by zhangkuncsdn** [comment]
请问这个问题，你解决了吗？

**Comment by aishangmaxiaoming** [comment]
> 请问这个问题，你解决了吗？

没解决，你呢

**Comment by jshilong** [comment]
Maybe because  the `num_classes` of the head is larger than the 80

**Comment by jshilong** [comment]
You can refer to #4952

**Comment by DiDisama317** [comment]
> > 请问这个问题，你解决了吗？
> 
> 没解决，你呢

Hi, I've met the same problem in training Swin-transformer-Object-Detection, where I used my custom coco dataset and it failed right after one epoch with the same error traceback to yours. Please do let me know if you have solved that, THANKS!
