### ISSUE TITLE
how to get current iteration inside model.

### ISSUE THREAD

**Issue by namihagi** [open-mmlab/mmdetection#5153]
I'm implementing my custom model.
I try to implement weighted loss based on iteration.
Could you tell me how to get current iteration inside model (loss function).

Thank you.

**Comment by shinya7y** [comment]
`HeadHook` of TOOD will be helpful as a related example.
https://github.com/fcjian/TOOD/blob/master/mmdet/core/utils/head_hook.py
https://github.com/fcjian/TOOD/blob/876db1f29046ab307636e221fed416e80d9a8f56/configs/tood/tood_r50_fpn_1x_coco.py#L73-L76
