### ISSUE TITLE
I can't understand why ratio is sqrt

### ISSUE THREAD

**Issue by Hyerin-oh** [open-mmlab/mmdetection#5157]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/anchor_generator.py#L168
line  168 ~ 169      

```
h_ratios = torch.sqrt(ratios)
w_ratios = 1 / h_ratios
```

why h_ratios is sqrt(ratios)?

I think if ratio = 2  ,  h_ratio = 1 , w_ratio = 2  so w/h = 2 
Please let me know ASAP

**Comment by shinya7y** [comment]
To keep area.
https://twitter.com/Mxbonn/status/1252933371682066432
