### ISSUE TITLE
LVIS testing

### ISSUE THREAD

**Issue by shwoo93** [open-mmlab/mmdetection#5158]
Hello, 

Due to the class imbalanced nature of LVIS, the confidence of rare categories at test time is low.
Given this fact, we low down the standard confidence threshold at test time from 0.05 to 0.0001 and increase the maximum bounding box per image from 100 to 300. This heuristic provides better mAP overall in LVIS, especially for rare categories. 

However, the visual results at test time seem to look like this (many redundant boxes even after the nms). 

![image](https://user-images.githubusercontent.com/13035722/118217496-8a273080-b4b0-11eb-82dc-4ed66f8798c4.png)

Is this natural?

**Comment by shinya7y** [comment]
With the default setting `class_agnostic=False`, NMS cannot suppress boxes across classes.
https://github.com/open-mmlab/mmcv/blob/b8c09f3b8449f2771e92a6a671027359d2c2707e/mmcv/ops/nms.py#L232

`class_agnostic=True` or `Limit detections-per-class` https://arxiv.org/abs/2102.01066 may improve visualization results.

**Comment by ZwwWayne** [comment]
Yes, this is normal because we allow 300 boxes for LVIS following previous practices.
