### ISSUE TITLE
Why has solo v1/v2 reimplementation been removed?

### ISSUE THREAD

**Issue by TyroneLi** [open-mmlab/mmdetection#5159]
As mentioned above.

**Comment by TyroneLi** [comment]
By the way, could u release dense reppoints or reppoints v2?

**Comment by lt1103725556** [comment]
I have the same question

**Comment by AronLin** [comment]
We are redesigning the base class for one-stage instance segmentation, including SOLO, SOLOv2, and CondInst.  They will be released soon.

ReppointsV2 is not planned in the near future, but we welcome the PR for this method.
