### ISSUE TITLE
Multiscaling training, but there was no performance improvement.

### ISSUE THREAD

**Issue by cowoopark** [open-mmlab/mmdetection#516]
hi,
For multi-scale train,
the image_scale in cascade_mask_rcnn config file was set to [(1333, 640), (1333, 672), (1333, 704), (1333, 736), (1333, 768), (1333, 800)], but there was no performance improvement.
>> coco MAP results : (single scale) 45.8  (multi scale) 45.9
i also checked that mmdet image scale strategy is same with detectron.

I think it is a very ironic phenomenon...
i have also read the HTC paper, could you share the image scale value for multi-scale? or share multi-scale trained models?

**Comment by hellock** [comment]
The training scales are already described in the paper. In the PR we also released a model trained with multiple scales.

**Comment by cowoopark** [comment]
thanks :)
i just checked it!
