### ISSUE TITLE
pretrained=None,but the map is so low

### ISSUE THREAD

**Issue by hero-y** [open-mmlab/mmdetection#517]
I set pretrained=None and norm_eval=False in Faster_rcnn_r50_fpn_1x_voc0712, but after i train about 4 epoch, the 0.5 voc map is 0.08. I don't know why this is. Can you help me? Thanks!

**Comment by hellock** [comment]
Did you read the paper "Rethinking ImageNet Pre-training"?
https://arxiv.org/abs/1811.08883

**Comment by KimSoybean** [comment]
@hero-y  Set 5x lr & 8x epoch and replace BN to GN.

**Comment by zzzzzzc** [comment]
> @hero-y Set 5x lr & 8x epoch and replace BN to GN.
sorry，can you help me？
How to replace BN to GN?
i do not find the corresponding profile about BN and GN.
thank  @KimSoybean
