### ISSUE TITLE
module 'torch.nn' has no attribute 'SyncBatchNorm'

### ISSUE THREAD

**Issue by wzz513878041** [open-mmlab/mmdetection#5170]
I installed cuda11.0 and pytorch1.7.0，but when I run python tools/train.py   ,I met this problem

  File "/home/wzz/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/utils/parrots_wrapper.py", line 71, in _get_norm
    SyncBatchNorm_ = torch.nn.SyncBatchNorm
AttributeError: module 'torch.nn' has no attribute 'SyncBatchNorm'

does anybody know how to solve it,thanks!

**Comment by wzz513878041** [comment]
torch.cuda.is_available()  is true!

**Comment by ZwwWayne** [comment]
This is weird because PyTorch 1.7.0 has this module. Can you check whether your environment is correct?

**Comment by liushuai839** [comment]
Hello, I met the same problem. Have you solved it ?
