### ISSUE TITLE
Issue when building mmcv together with latest onnxruntime >=1.7.0

### ISSUE THREAD

**Issue by tehkillerbee** [open-mmlab/mmdetection#5174]
Hi, 

Does mmdetection/mmcv support any onnxruntime versions more recent than 1.5.1? I would like to take advantage of better OpenVINO and one DNN support, but it seems that the latest onnxruntime packages (eg. 1.7.1) is not compatible with mmcv 1.3.1 at all.

So far, I have attempted to follow https://github.com/open-mmlab/mmcv/blob/master/docs/onnxruntime_op.md
But more recent versions of onnxruntime does not appear to work, I get errors similar to #5051 
`RuntimeError: Error compiling objects for extension`

It would be nice to know which version of onnxruntime that is supported currently.

**Comment by RunningLeon** [comment]
@tehkillerbee We have not fully tested ONNX feature with different versions of onnxruntime yet. However, it should be OK for onnxruntime between 1.5.1 and 1.6.0.

**Comment by RunningLeon** [comment]
closed due to age.
