### ISSUE TITLE
跑GFL 报错 ，RuntimeError: The size of tensor a (4) must match the size of tensor b (24) at non-singleton dimension 1

### ISSUE THREAD

**Issue by aishangmaxiaoming** [open-mmlab/mmdetection#5175]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/67897601/118490717-d1335100-b750-11eb-9aa6-9740246a7284.png">

**Comment by shinya7y** [comment]
Please use the latest code after https://github.com/open-mmlab/mmdetection/pull/4982
