### ISSUE TITLE
How should I setup the settings when I need finetune from an existing model without the need of warmup?

### ISSUE THREAD

**Issue by ArchNew** [open-mmlab/mmdetection#5183]
Since I finetune from an existing model, I have no need for warm-up. But from What I can learn from the page https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/finetune.md , it seems the author doesn't touch the warm-up settings. Doesn't it cause the whole 64 epochs in the example are all running in the warm-up sessions?

**Comment by hhaAndroid** [comment]
If you don't need a warmup, you can set `warmup_ratio=1`.

**Comment by ArchNew** [comment]
> If you don't need a warmup, you can set `warmup_ratio=1`.

Thanks, I find I just need set `warmup=None`
