### ISSUE TITLE
Backbone weight is really loaded for the latest version of the code?

### ISSUE THREAD

**Issue by ErenTuring** [open-mmlab/mmdetection#5184]
I updated the code to the latest version a few days ago. Then, a model with exact same configs as before, the performance drops dramatically. During the debugging process, I didn't see the weight of the pre-trained backbone being loaded.

**Comment by hhaAndroid** [comment]
Hi, Maybe it is because of parameter initialization. Can you describe it in detail? e.g config command...

**Comment by K0mp0t** [comment]
In the last update pre-trained model weights initialization was changed a bit, now you have to add init_cfg to your config and initialize pre-trained model weights manually. Here's what you should do:

1. Add init_cfg to your config
```
model = dict(
    type='FasterRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=False),
        norm_eval=True,
        style='caffe',
        init_cfg=dict(type='Pretrained', checkpoint='open-mmlab://detectron2/resnet50_caffe'),), # <- you shuold add this
    ....))
```
2. In your training script after model initialization add call of model.init_weights function:
```
from mmdet.apis import train_detector
from mmdet.models import build_detector
import os.path as osp


model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'), train_cfg=cfg.get('train_cfg'))
model.init_weights() # <- this is what you should add

model.CLASSES = datasets[0].CLASSES

mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```

**Comment by ErenTuring** [comment]
> 
>     1. In your training script after model initialization add call of model.init_weights function:
> 
> 
> ```
> from mmdet.apis import train_detector
> from mmdet.models import build_detector
> import os.path as osp
> 
> 
> model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'), train_cfg=cfg.get('train_cfg'))
> model.init_weights() # <- this is what you should add
> 
> model.CLASSES = datasets[0].CLASSES
> 
> mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
> train_detector(model, datasets, cfg, distributed=False, validate=True)
> ```

Really appreciate!
The updated version I used did not add `model.init_weights()`.
