### ISSUE TITLE
[Doc] External links ending with `.md` do not link to the correct page in read-the-docs

### ISSUE THREAD

**Issue by THU17cyz** [open-mmlab/mmdetection#5185]
Hi, I am a developer of MMDet3D. Recently I found a bug in the read-the-docs page of MMDet3D (please refer to [this](https://github.com/open-mmlab/mmdetection3d/pull/548)). In a word, the underlying parsing machanism of `sphinx` will view an external link (which is not a relative path) ending with `.md` as something other than a external link. Therefore, when a user clicks the link in a generated read-the-docs webpage, the link will jump to a 404 page because `.md` is stripped in the target webpage.

Example: 
https://mmdetection.readthedocs.io/en/latest/model_zoo.html#training-speed-benchmark
Click _detectron2_ in the sentence "_We compare the training speed of Mask R-CNN with some other popular frameworks (The data is copied from detectron2)_". The webpage jumps to https://github.com/facebookresearch/detectron2/blob/master/docs/notes/benchmarks, which is stripped of `.md` and shows a 404 error.

I have searched for solutions in Google and among the issues of `sphinx` and `recommonmark` but found nothing useful. Therefore I provide a workaround, which is to add a `/` after `.md`. Do you have a better solution, such as modifying the building script of read-the-docs? If not, the workaround is easy and solves this tiny bug.

**Comment by AronLin** [comment]
Thank you, we will fix this bug.
If we find a better solution, we will record it in this issue.

**Comment by THU17cyz** [comment]
> Thank you, we will fix this bug.
> If we find a better solution, we will record it in this issue.

I can also open a pull request.

**Comment by AronLin** [comment]
> > Thank you, we will fix this bug.
> > If we find a better solution, we will record it in this issue.
> 
> I can also open a pull request.

PRs are welcomed! Thanks for your contribution.
