### ISSUE TITLE
Training object detection on COCO dataset with FP16+with_cp error

### ISSUE THREAD

**Issue by Line290** [open-mmlab/mmdetection#5188]
**Describe the bug**
When training COCO in the config: `faster_rcnn_r101_fpn_2x_coco.py` with FP16 and with_cp, an error causes as below: 

`Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/users/$HOME/Codes/mmdetection-master/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/users/$HOME/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/users/$HOME/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/users/$HOME/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/users/$HOME/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 133, in after_train_iter
    self.loss_scaler.scale(runner.outputs['loss']).backward()
  File "/users/$HOME/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/users/$HOME/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same`

**Reproduction**

1. What command or script did you run?

        1). enable `with_cp=True` in config: `configs/_base_/models/faster_rcnn_r50_fpn.py#L5:backbone` 
        2). enable `fp16 = dict(loss_scale=512.0)` in config: `configs/_base_/default_runtime.py` 
Run command as below:
```
bash tools/dist_train.sh configs/faster_rcnn/faster_rcnn_r101_fpn_2x_coco.py 4
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Please see above

3. What dataset did you use?
COCO

**Error traceback**
If applicable, paste the error trackback here.
Pls see above

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.  
```fatal: Not a git repository (or any parent up to mount point /users)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-PCIE-16GB
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.168
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0+cu101
OpenCV: 4.5.1
MMCV: 1.3.3
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.12.0+ ```

**Comment by hhaAndroid** [comment]
Hi, Can you try `with_cp=False` to see if the same error occurs?

**Comment by Line290** [comment]
Hi @hhaAndroid, it's definitely ok.

**Comment by hhaAndroid** [comment]
> Hi @hhaAndroid, it's definitely ok.

So, when `with_cp=True and fp16=True`, there will be an error?

**Comment by Line290** [comment]
> > Hi @hhaAndroid, it's definitely ok.
> 
> So, when `with_cp=True and fp16=True`, there will be an error?

Yes, but in the old version, says mmdet==2.5.0, when with_cp=True and fp16=True, it's fine.

**Comment by ZwwWayne** [comment]
Because you are using PyTorch 1.6，originally we use self-implemented FP16 training. But in the new version, we use PyTorch AMP for when PyTorch version >=1.6. We may try to fix that.

**Comment by Line290** [comment]
Cool, thanks.
