### ISSUE TITLE
"false" in file qasciikey.cpp, line 501

### ISSUE THREAD

**Issue by Snowstorm0** [open-mmlab/mmdetection#519]
Why do I always encounter this problem when I test：

loading annotations into memory...
Done (t=0.43s)
creating index...
index created!
unexpected key in source state_dict: bbox_head.fc_cls.weight, bbox_head.fc_cls.bias, bbox_head.fc_reg.weight, bbox_head.fc_reg.bias, bbox_head.shared_fcs.0.weight, bbox_head.shared_fcs.0.bias, bbox_head.shared_fcs.1.weight, bbox_head.shared_fcs.1.bias

[                                                  ] 0/5000, elapsed: 0s, ETA:ASSERT: "false" in file qasciikey.cpp, line 501
Aborted

**Comment by hellock** [comment]
https://www.google.com/search?client=safari&rls=en&q=%22false%22+in+file+qasciikey&ie=UTF-8&oe=UTF-8
