### ISSUE TITLE
ccnet do not work?

### ISSUE THREAD

**Issue by chenxu93** [open-mmlab/mmdetection#5190]
I doubt the implement of criss-cross attention do not useful?  all feature elements are zeros.
![image](https://user-images.githubusercontent.com/42310082/118997679-6c2f6380-b9bb-11eb-94eb-f10dec40e28d.png)
![image](https://user-images.githubusercontent.com/42310082/118997831-88330500-b9bb-11eb-96a9-467a2295565f.png)

**Comment by hhaAndroid** [comment]
Hi @chenxu93 `gamma` is a learnable parameter, initialized to 0, which is correct.

**Comment by chenxu93** [comment]
> Hi @chenxu93 `gamma` is a learnable parameter, initialized to 0, which is correct.

i see, thx.
