### ISSUE TITLE
AssertionError: CocoDataset: Incompatible version of pycocotools is installed. Run pip uninstall pycocotools first. Then run pip install mmpycocotools to install open-mmlab forked pycocotools.

### ISSUE THREAD

**Issue by Wakinguup** [open-mmlab/mmdetection#5207]
AssertionError: CocoDataset: Incompatible version of pycocotools is installed. Run pip uninstall pycocotools first. Then run pip install mmpycocotools to install open-mmlab forked pycocotools.

i did that follow the tips, but didn't work for me

**Comment by RangiLyu** [comment]
What's the version of pycocotools you installed? Try to run `pip install pycocotools==2.0.2` to install the newer version.

**Comment by ZwwWayne** [comment]
You are using the old mmdetection version, which relies on mmpycocotools. Therefore, you need to `pip uninstall pycocotools` first and make sure it is cleaned (sometimes `pip uninstall` does not fully cleaned the environment when these two package are already installed).
