### ISSUE TITLE
Error while train default Faster R-CNN model

### ISSUE THREAD

**Issue by moxie-chen** [open-mmlab/mmdetection#5211]
RuntimeError: operation does not have an identity.
It can work sometimes
![2021-05-24 15-06-54屏幕截图](https://user-images.githubusercontent.com/53067819/119310122-caf31800-bc1b-11eb-9748-2622cf5be0cf.png)

**Comment by EdyQiu** [comment]
I met the same issue!

**Comment by moxie-chen** [comment]
> I met the same issue!

turn down the iou_threshold and it works

**Comment by tehkillerbee** [comment]
I have the same issue when training with custom dataset. Can you elaborate how you turned down this threshold?

**Comment by moxie-chen** [comment]
> I have the same issue when training with custom dataset. Can you elaborate how you turned down this threshold?

i turned down the iou_threshold in faster_rcnn_r50_fpn.py
![1](https://user-images.githubusercontent.com/53067819/119501748-a11e1c00-bd15-11eb-8b61-90e7d2a48e4f.png)

**Comment by tehkillerbee** [comment]
@moxie-chen Thank you, that did the trick!

**Comment by hhaAndroid** [comment]
Thank you for your feedback, the reason is that the bbox is an empty tensor, which is an exception. I will fix it.

**Comment by SamihaSara** [comment]
@hhaAndroid please let me know how to fix this. I am also facing the same problem with configs/faster_rcnn/faster_rcnn_r101_fpn_2x_coco.py to train on the COCO dataset from scratch.

**Comment by hero-y** [comment]
I also get the same issue

**Comment by ZwwWayne** [comment]
Which version of MMDetection did you run?

**Comment by EdyQiu** [comment]
> Which version of MMDetection did you run?

The latest one, or the one just before the update in May, sorry  I can not really remember. 
The issue occurred when training data is few, and when I rerun the code it worked somehow.

**Comment by SamihaSara** [comment]
> Which version of MMDetection did you run?

Tried again with the current version. it worked this time.

**Comment by hero-y** [comment]
I use the version in Jun 7 and met the same issue.

**Comment by jshilong** [comment]
@hero-y @SamihaSara @EdyQiu 
Seems this is a bug when `rpn_head` can't give any proposals for  `batch_nms`, PR#5249 would fix it.
