### ISSUE TITLE
losses in retinaNet become nan

### ISSUE THREAD

**Issue by rerester** [open-mmlab/mmdetection#5213]
This is my retinanet.py, training with VOC dataset:

```
_base_ = [
    '../_base_/models/retinanet_r50_fpn.py',
    '../_base_/datasets/voc0712.py',
    '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py'
]
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
model = dict(
    bbox_head=dict(
    num_classes=20))

dataset_type = 'VOCDataset'
data_root = 'data/VOC/VOCdevkit/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1000, 600), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1000, 600),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

the log in training:
![image](https://user-images.githubusercontent.com/52994675/119315649-a85b1080-bca8-11eb-9978-33ec21ee79fb.png)

Can anyone help me?

**Comment by hhaAndroid** [comment]
Hi @rerester You can compare the https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/retinanet_r50_fpn_1x_voc0712.py configuration, the parameters may need to be adjusted.

**Comment by rerester** [comment]
> Hi @rerester You can compare the https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/retinanet_r50_fpn_1x_voc0712.py configuration, the parameters may need to be adjusted.

OK, thank!

**Comment by tojimahammatov** [comment]
Hi @rerester , try adding `grad_clip` in the config. Something like `grad_clip=dict(max_norm=35, norm_type=2)` rather than `grad_clip=None`.

**Comment by rerester** [comment]
> Hi @rerester , try adding `grad_clip` in the config. Something like `grad_clip=dict(max_norm=35, norm_type=2)` rather than `grad_clip=None`.

OK, it works!

**Comment by ZwwWayne** [comment]
Please refer to the documentation https://mmdetection.readthedocs.io/en/latest/faq.html#training.
