### ISSUE TITLE
Query about support for 3090

### ISSUE THREAD

**Issue by momo1986** [open-mmlab/mmdetection#5219]
Cannot run mmdetection with multiple-gpu on 3090.
**mmcv-version:1.2.4
mmdet-version:2.11.0
CUDA:11.1
RTX 3090**

My script is 
`CUDA_VISIBLE_DEVICES=0,1 tools/dist_train.sh configs/retinanet/retinanet_r50_fpn_1x_mm21.py 2`

Traceback (most recent call last):
  File "tools/train.py", line 14, in <module>
    from mmdet import __version__
  File "/root/junyan/adv_training/mmdetection_yolov4/mmdetection/mmdet/__init__.py", line 23, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.2.4 is used but incompatible. Please install mmcv>=1.1.5, <=1.2.

> Traceback (most recent call last):
>   File "tools/train.py", line 14, in <module>
>     from mmdet import __version__
>   File "/root/junyan/adv_training/mmdetection_yolov4/mmdetection/mmdet/__init__.py", line 23, in <module>
>     assert (mmcv_version >= digit_version(mmcv_minimum_version)
> AssertionError: MMCV==1.2.4 is used but incompatible. Please install mmcv>=1.1.5, <=1.2.
> Traceback (most recent call last):
>   File "/root/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
>     main()
>   File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
>     raise subprocess.CalledProcessError(returncode=process.returncode,
> subprocess.CalledProcessError: Command '['/root/anaconda3/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/retinanet/retinanet_r50_fpn_1x_mm21.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

Since there is no clear road-map for the support on 3090.

Just ask for questions.

Thanks & regards!
Momo

**Comment by RangiLyu** [comment]
Try to update MMDetection to V2.12.0.

**Comment by momo1986** [comment]
@RangiLyu Thanks for your advise. Is mmcv-1.2.4 OK or should I choose other version?

**Comment by RangiLyu** [comment]
You can refer to docs/get_started.md

**Comment by ZwwWayne** [comment]
See the first question in [FAQ](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment).
