### ISSUE TITLE
use mobilenet backbones ,train 60 epoch ,get 3% accuracy

### ISSUE THREAD

**Issue by jerrynije** [open-mmlab/mmdetection#522]
When i attempt to change the resnet backbone to mobilenet .However,the accuracy is pretty low.What might be the reason to get this 3% low accuracy,since the resnet backbone is over 90%.

**Comment by hellock** [comment]
You may provide the config file and command you used.

**Comment by jerrynije** [comment]
config:faster_rcnn_r50_fpn_1x.py

model = dict(
  3     type='FasterRCNN',
  4    # pretrained='modelzoo://resnet18',
  5     pretrained=None,
  6   #  backbone=dict(
  7      #   type='ResNet',
  8         #block=BasicBlock,
  9         #layers=[2,2,2,2],
 10         #sample_size=64),
 11         #sample_duration=2),
 12     #    depth=18,
 13    #     num_stages=4,
 14   #      out_indices=(0, 1, 2, 3),
 15        # frozen_stages=1,
 16       #  norm_eval=False,
 17      #   style='pytorch'),
 18     backbone=dict(
 19         type='MobileNet',
 20         width_multiplier=1,
 21         class_num=1),
 22     neck=dict(
 23         type='FPN',
 24         in_channels=[128, 256, 512,1024],
 25         out_channels=64,
 26         num_outs=5),
Nothing else changed .

Backbone: mobileNet
1          import torch
  2 import torch.nn as nn
  3 import logging
  4 import torch.utils.checkpoint as cp
  5 
  6 from mmcv.cnn import constant_init, kaiming_init
  7 from mmcv.runner import load_checkpoint
  8 from ..registry import BACKBONES
  9 
 10 class DepthSeperabelConv2d(nn.Module):
 11 
 12     def __init__(self, input_channels, output_channels, kernel_size, **kwargs):
 13         super().__init__()
 14         self.depthwise = nn.Sequential(
 15             nn.Conv2d(
 16                 input_channels,
 17                 input_channels,
 18                 kernel_size,
 19                 groups=input_channels,
 20                 **kwargs),
 21             nn.BatchNorm2d(input_channels),
 22             nn.ReLU(inplace=True)
 23         )
 24 
 25         self.pointwise = nn.Sequential(
 26             nn.Conv2d(input_channels, output_channels, 1),
 27             nn.BatchNorm2d(output_channels),
 28             nn.ReLU(inplace=True)
 29         )
 30 
 31     def forward(self, x):
 32         x = self.depthwise(x)
 33         x = self.pointwise(x)
 34 
 35         return x
36 
 37 
 38 class BasicConv2d(nn.Module):
 39 
 40     def __init__(self, input_channels, output_channels, kernel_size, **kwargs):
 41 
 42         super().__init__()
 43         self.conv = nn.Conv2d(
 44             input_channels, output_channels, kernel_size, **kwargs)
 45         self.bn = nn.BatchNorm2d(output_channels)
 46         self.relu = nn.ReLU(inplace=True)
 47 
 48     def forward(self, x):
 49         x = self.conv(x)
 50         x = self.bn(x)
 51         x = self.relu(x)
 52 
 53         return x
 54 
 55 @BACKBONES.register_module
 56 class MobileNet(nn.Module):
 57 
 58     """
 59     Args:
 60         width multipler: The role of the width multiplier α is to thin 
 61                          a network uniformly at each layer. For a given 
 62                          layer and width multiplier α, the number of 
 63                          input channels M becomes αM and the number of 
 64                          output channels N becomes αN.
 65     """
 66 
 67     def __init__(self, width_multiplier=1, class_num=1):
 68        super().__init__()
69 
 70        alpha = width_multiplier
 71        self.stem = nn.Sequential(
 72            BasicConv2d(3, int(32 * alpha), 3, padding=1, bias=False),
 73            DepthSeperabelConv2d(
 74                int(32 * alpha),
 75                int(64 * alpha),
 76                3,
 77                padding=1,
 78                bias=False
 79            )
 80        )
 81 
 82        #downsample
 83        self.conv1 = nn.Sequential(
 84            DepthSeperabelConv2d(
 85                int(64 * alpha),
 86                int(128 * alpha),
 87                3,
 88                stride=2,
 89                padding=1,
 90                bias=False
 91            ),
 92            DepthSeperabelConv2d(
 93                int(128 * alpha),
 94                int(128 * alpha),
 95                3,
 96                padding=1,
 97                bias=False
 98            )
 99        )
100 
101        #downsample
102        self.conv2 = nn.Sequential(
103            DepthSeperabelConv2d(
104                int(128 * alpha),
105                int(256 * alpha),
106                3,
107                stride=2,
108                padding=1,
109                bias=False
110            ),
111            DepthSeperabelConv2d(
112                int(256 * alpha),
113                int(256 * alpha),
114                3,
115                padding=1,
116                bias=False
117            )
118        )
119 
120        #downsample
121        self.conv3 = nn.Sequential(
122            DepthSeperabelConv2d(
123                int(256 * alpha),
124                int(512 * alpha),
125                3,
126                stride=2,
127                padding=1,
128                bias=False
129            ),
130 
131            DepthSeperabelConv2d(
132                int(512 * alpha),
133                int(512 * alpha),
134                3,
135                padding=1,
136                bias=False
137            ),
138            DepthSeperabelConv2d(
139                int(512 * alpha),
140                int(512 * alpha),
141                3,
142                padding=1,
143                bias=False
144            ),
145            DepthSeperabelConv2d(
146                int(512 * alpha),
147                int(512 * alpha),
148                3,
149                padding=1,
150                bias=False
151            ),
152            DepthSeperabelConv2d(
153                int(512 * alpha),
154                int(512 * alpha),
155                3,
156                padding=1,
157                bias=False
158            ),
159            DepthSeperabelConv2d(
160                int(512 * alpha),
161                int(512 * alpha),
162                3,
163                padding=1,
164                bias=False
165            )
166        )
167 
168        #downsample
169        self.conv4 = nn.Sequential(
170            DepthSeperabelConv2d(
171                int(512 * alpha),
172                int(1024 * alpha),
173                3,
174                stride=2,
175                padding=1,
176                bias=False
177            ),
178            DepthSeperabelConv2d(
179                int(1024 * alpha),
180                int(1024 * alpha),
181                3,
182                padding=1,
183                bias=False
184            )
185        )
186 
187       # self.fc = nn.Linear(int(1024 * alpha), class_num)
188       # self.avg = nn.AdaptiveAvgPool2d(7)
189 
190     def init_weights(self, pretrained=None):
191         if isinstance(pretrained, str):
192             logger = logging.getLogger()
193             load_checkpoint(self, pretrained, strict=False, logger=logger)
194         elif pretrained is None:
195             for m in self.modules():
196                 if isinstance(m, nn.Conv2d):
197                     kaiming_init(m)
198                 elif isinstance(m, (nn.BatchNorm2d, nn.GroupNorm)):
199                     constant_init(m, 1)
200 
201     def forward(self, x):
202         outs=[]
203         x = self.stem(x)
204         x=self.conv1(x)
205         outs.append(x)
206         x = self.conv2(x)
207         outs.append(x)
208         x = self.conv3(x)
209         outs.append(x)
210         x = self.conv4(x)
211 
212        # x = self.avg(x)
213         outs.append(x)
214        # x = x.view(x.size(0), -1)
215         #x = self.fc(x)
216         return tuple(outs)
217     def train(self, mode=True):
218         super(MobileNet, self).train(mode)
219         if mode:
220             for m in self.modules():
221                 # trick: eval have effect on BatchNorm only
222                 if isinstance(m, nn.BatchNorm2d):
223                     m.train()
   

command :                  CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 python tools/train.py configs/faster_rcnn_r50_fpn_1x.py --gpus 5 --validate
task:        Recognise and locate the  license plate number
                                                                                                                                              Thanks

**Comment by hellock** [comment]
The result is expected since `pretrained=None`.

**Comment by jerrynije** [comment]
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2000/2000, 152.4 task/s, elapsed: 13s, ETA:     0s

writing results to result.pkl
Starting evaluate bbox
Loading and preparing results...
DONE (t=0.16s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.40s).
Accumulating evaluation results...
DONE (t=0.35s).

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.011
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.038
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.015
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.021
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.090
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.096
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.106
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.056

Thanks

**Comment by hellock** [comment]
I mean your result is as expected, since you randomly initialized backbone weights.

**Comment by jerrynije** [comment]
how to improve the accuracy

**Comment by jerrynije** [comment]
However,things turn out to be different on resnet backbone.when i use the resnet backbone,and turn off the BN,set the pretrained=None, the accuracy is still over 90% on the same dataset.A slightly down compares to set pretrained=True.

**Comment by xscjun** [comment]
@jerrynije  
Hi, When i attempt to change the resnet backbone to mobilenet as you said , I got the error :
" TypeError: __init__() got an unexpected keyword argument 'width_multiplier' " , in "mmdet/utils/registry.py"
could you tell me how to fix it , please ?

**Comment by catchy666** [comment]
Hi, @jerrynije !
Your MobileNet version is v1/v2, please?
