### ISSUE TITLE
about seesaw loss useage

### ISSUE THREAD

**Issue by dmuqlzhang** [open-mmlab/mmdetection#5220]
can i use seesaw loss only in object detection task without  Instance Segmentation？

**Comment by dmuqlzhang** [comment]
> can i use seesaw loss only in object detection task without Instance Segmentation？

can i direct use seesaw loss in FasterRcnn？

**Comment by ZwwWayne** [comment]
Yes, you can. It is used in the box head so of course, it can be used for object detection.
