### ISSUE TITLE
How to add new content in the log file?

### ISSUE THREAD

**Issue by rsj007** [open-mmlab/mmdetection#5224]
I am training a network on the Nightowls dataset, which has a index called "miss rate", as shown in the picture below.
![image](https://user-images.githubusercontent.com/29651895/119619453-97d8a080-be36-11eb-8a29-e5fad19e97ab.png)
However it just appears in the terminal every epoch finished and doesn't show in the log file. I wonder how to change the log config to add it in the log file?
![image](https://user-images.githubusercontent.com/29651895/119619861-ff8eeb80-be36-11eb-9cc7-edc56fb4cee2.png)

**Comment by AronLin** [comment]
You can output your results to the log file with the function 'mmcv.utils.print_log' in your 'evaluate' function of your dataset.
For example:

        msg = 'Average Miss Rate (MR) ... IoU = {}, ...'.format(iou, ...)   # your results
        print_log(msg, logger=logger)
