### ISSUE TITLE
Where to add custom_pipeline

### ISSUE THREAD

**Issue by marijnl** [open-mmlab/mmdetection#5225]
I try to add a pipeline that does some custom augmentation following this tutorial
https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html#extend-and-use-custom-pipelines

I wonder where and how i should import MyTransform? When i run my training code it removes my MyTransform from the train_pipeline.

Adding `from .my_pipeline import MyTransform` in `tools/train.py` didnt do the trick
Does my_pipeline.py need to be placed in some specific directory?
Also, i did install mmdetection using pip. Is it at all possible to run a custom pipeline when installing via pip?

**Comment by marijnl** [comment]
I tried setting it in my cfg
Now i does import the module, but it still doesnt allow me to add it as part of my train pipeline
```
custom_imports = dict(imports=['my_pipeline'], allow_failed_imports=False)
train_pipeline = [
    dict(type='MyTransform', p=.2)
]
```

**Comment by marijnl** [comment]
I think i found the problem. For future reference:
```
data = dict(
    train=dict(
        pipeline=train_pipeline
     )
 )
```
In my cfg i needed to add the `train_pipeline` explicitly as part of data.train.pipeline
Now it runs my `MyTransform` as part of the training pipeline

**Comment by qinsimon** [comment]
Hi, I got same issue. Could you plz tell me how to solve it in detail? where i should import My_transform, and how to use it in cfg. it would be great if you can share an example.

**Comment by marijnl** [comment]
I tried to rephrase the docs to make it a bit more clear. Have you seen the associated PR?

**Comment by qinsimon** [comment]
COOL. It's very kind of you!XD
