### ISSUE TITLE
when run fist_train.sh ,return non-zero exit status 2

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#5228]
error:
(open-mmlab) liuguangcan@ubuntu:~/mmdetection$ ./tools/dist_train.sh configs/htc/htc_r50_fpn_1x_coco.py  2
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
usage: train.py [-h] [--config CONFIG] [--work-dir WORK_DIR]
                [--resume-from RESUME_FROM] [--no-validate]
                [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]] [--seed SEED]
                [--deterministic] [--options OPTIONS [OPTIONS ...]]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK]
train.py: error: unrecognized arguments: configs/htc/htc_r50_fpn_1x_coco.py
usage: train.py [-h] [--config CONFIG] [--work-dir WORK_DIR]
                [--resume-from RESUME_FROM] [--no-validate]
                [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]] [--seed SEED]
                [--deterministic] [--options OPTIONS [OPTIONS ...]]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK]
train.py: error: unrecognized arguments: configs/htc/htc_r50_fpn_1x_coco.py
Traceback (most recent call last):
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liuguangcan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/liuguangcan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/liuguangcan/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/htc/htc_r50_fpn_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 2.
please tall me where i with wrong?
think you vary much

**Comment by RangiLyu** [comment]
Did you modify tools/train.py? The original train.py has no '--' before 'config' in L23:`parser.add_argument('config', help='train config file path')`

**Comment by AronLin** [comment]
Have you solved your problem?
You can reopen this issue if the problem still exists, we can discuss it.

**Comment by Bin-ze** [comment]
This problem occurred because I modified the config，I have solved this problem，think you

**Comment by isomatical** [comment]
How did you solve it in the end？I met the same problem, please help!

**Comment by Bin-ze** [comment]
Generally, such errors are caused by the wrong modification of the config file or the arg parameter. My problem is that I modified the arg parameter in train.py. If you do not have the same error as mine, can you change Send me your error information in detail so that it is easier to determine where the error is.

**Comment by Bin-ze** [comment]
Generally, such errors are caused by the wrong modification of the config file or the arg parameter. My problem is that I modified the arg parameter in train.py. If you do not have the same error as mine, can you change Send me your error information in detail so that it is easier to determine where the error is.

**Comment by Bin-ze** [comment]
> 请问最后是怎么解决的？我也遇到了同样的问题，请帮忙！

Generally, such errors are caused by the wrong modification of the config file or the arg parameter. My problem is that I modified the arg parameter in train.py. If you do not have the same error as mine, can you change Send me your error information in detail so that it is easier to determine where the error is.
