### ISSUE TITLE
Any way to run mmdetection without python setup.py install ?

### ISSUE THREAD

**Issue by Liu0329** [open-mmlab/mmdetection#523]
Hi mmdet team,

   Thanks for the great work !
   Every time when I make some changes to mmdet, I have to python setup.py install. It is not friendly to debug like pdb.settrace().
   Is there any way to get rid of it ?  And make the code run on where it was.

Thanks !

**Comment by JrPeng** [comment]
Agree

**Comment by hellock** [comment]
#146 
#76

**Comment by Liu0329** [comment]
@hellock Thanks ! Maybe you can add it in the readme to avoid repeated asking :)

**Comment by hellock** [comment]
It's already there. https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md#notice
