### ISSUE TITLE
FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: 'data/coco/annotations/instances_train2017.json'

### ISSUE THREAD

**Issue by wujiaors** [open-mmlab/mmdetection#5230]
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_train2017.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 164, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/XXXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/XXXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: 'data/coco/annotations/instances_train2017.json'

**Comment by RangiLyu** [comment]
Make sure you symlink the coco dataset root to `$MMDETECTION/data`. Like this:
```
mmdetection
├── mmdet
├── tools
├── configs
├── data
│   ├── coco
│   │   ├── annotations
│   │   ├── train2017
│   │   ├── val2017
│   │   ├── test2017
```

**Comment by wujiaors** [comment]
> Make sure you symlink the coco dataset root to `$MMDETECTION/data`. Like this:
> 
> ```
> mmdetection
> ├── mmdet
> ├── tools
> ├── configs
> ├── data
> │   ├── coco
> │   │   ├── annotations
> │   │   ├── train2017
> │   │   ├── val2017
> │   │   ├── test2017
> ```
But I'm using the VOC dataset, and the coco dataset is a bit hard to understand here, what should I do?

**Comment by RangiLyu** [comment]
Here are some example config files of VOC dataset: https://github.com/open-mmlab/mmdetection/tree/master/configs/pascal_voc. You can refer to these files to change your configuration. Also, you can find more details in https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md

**Comment by wujiaors** [comment]
> Here are some example config files of VOC dataset: https://github.com/open-mmlab/mmdetection/tree/master/configs/pascal_voc. You can refer to these files to change your configuration. Also, you can find more details in https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md

My VOC dataset root like this:
mmdetection
├── mmdet
├── tools
├── configs
├── data #手动创建data、VOCdevkit、VOC2007、Annotations、JPEGImages、ImageSets、Main这些文件夹
│   ├── VOCdevkit
│   │   ├── VOC2007
│   │   │   ├── Annotations #把test.txt、trainval.txt对应的xml文件放在这
│   │   │   ├── JPEGImages #把test.txt、trainval.txt对应的图片放在这
│   │   │   ├── ImageSets
│   │   │   │   ├── Main
│   │   │   │   │   ├── test.txt 
│   │   │   │   │   ├── val.txt
│   │   │   │   │   ├── train.txt 
│   │   │   │   │   ├── trainval.txt

**Comment by ZwwWayne** [comment]
Which config are you using? @wujiaors

**Comment by MohammadKhan81** [comment]
![Screenshot 2024-09-05 070457](https://github.com/user-attachments/assets/50c18a84-d621-4aa3-be67-4cd49964ba8c)

**Comment by MohammadKhan81** [comment]
I am getting this problem - what do u think is the problem?
