### ISSUE TITLE
Calculate mAP more than once per epoch during training

### ISSUE THREAD

**Issue by alexeyhorkin** [open-mmlab/mmdetection#5238]
Is there a good way to calculate and logging MAP more than once per epoch during training?

**Comment by RangiLyu** [comment]
You can use IterBasedRunner and change evaluation interval steps. Refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_90k_coco.py and https://github.com/open-mmlab/mmdetection/blob/master/configs/yolof/yolof_r50_c5_8x8_iter-1x_coco.py

**Comment by www516717402** [comment]
@alexeyhorkin https://github.com/open-mmlab/mmcv/blob/b36c4de157259a5188d1e7a5aca683b02060ae1b/mmcv/runner/hooks/evaluation.py#L64
