### ISSUE TITLE
How to remove TTA to speed up pre-process in inference mode?

### ISSUE THREAD

**Issue by elepherai** [open-mmlab/mmdetection#5239]
Hi, to speed up pre-process in inference mode, I would like to remove TTA in test_pipeline.

Since my image data is rescaled before test_pipeline, I want to keep Normalize and ImageToTensor transforms and remove the others.

How could I change bellow codes for my purpose?

```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 256),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

**Comment by ZwwWayne** [comment]
Other modules do not actually work here. Because `flip=False`, the `RandomFlip` does not really work, the resize is still necessary to resize the image to the corresponding `img_scale`, so as the padding.

**Comment by elepherai** [comment]
Hi @ZwwWayne , thanks for your reply.

I have simplified the test pipeline like this:

```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]
```
