### ISSUE TITLE
Is there any way to only update the parameters of several specific layers?

### ISSUE THREAD

**Issue by Flawless1202** [open-mmlab/mmdetection#524]
Thanks for your excellent project. I have use this framework to realize my own model. But I could not find the way to freeze the parameters of several specific layers when I training the parameters of another layers. Is there any way to do this?
Looking forward to your reply soon. @hellock @OceanPang

**Comment by hellock** [comment]
When initializing the runner, you can just use a `torch.optim.Optimizer` object instead of a [dict](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L74). So you can construct the optimizer as you wish, to only update the parameters of some specific layers, which is the same as in other pytorch programmes.

**Comment by Flawless1202** [comment]
Thanks for your reply! I would try it. @hellock

**Comment by leemengwei** [comment]
@Flawless1202 Hi, have you solve the issue? Could you offer some specific instructions?

**Comment by ashj9** [comment]
@Flawless1202 , @hellock , were you able to achieve that?

**Comment by naimple** [comment]
@hellock Could you please give a specific example of finetuning parts of model parameters based on the [tools/train.py](https://github.com/open-mmlab/mmdetection/blob/8bca5b70ea7552d848424f2c076ad6469902e7fc/tools/train.py) script?

I tried to initiate a `torch.optim.SGD` object by myself  to replace <https://github.com/open-mmlab/mmdetection/blob/8bca5b70ea7552d848424f2c076ad6469902e7fc/mmdet/apis/train.py#L85>.

But this gives me the error:

> Traceback (most recent call last):
>   File "mytrain.py", line 298, in <module>
>     main()
>   File "mytrain.py", line 294, in main
>     meta=meta)
>   File "mytrain.py", line 123, in train_detector
>     eval_hook = DistEvalHook if distributed else EvalHook
> NameError: name 'EvalHook' is not defined

It seems that the `build_optimizer` function registers a hook into the optimizer.

**Comment by zeakey** [comment]
@ashj9 You filter out unnecessary parameters by constructing the optimizer manually.

For example, if you only want to update FPN parameters,
just replace <https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L85>
with
```
parameters = []
    for name, p in model.named_parameters():
        if "fpn" in name:
            parameters.append(p)

    optimizer = torch.optim.SGD(
        parameters, lr=cfg.optimizer['lr'], momentum=cfg.optimizer['momentum'],
        weight_decay=cfg.optimizer['weight_decay']
    )
```
