### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by xiexu0210** [open-mmlab/mmdetection#5240]
hi, my code need nms and dcn module. so i need from your code to obtian this module. then , i take out the modules from your code , then compile it. but the following error occurred .

![Uploading 2021-05-28 12-16-21屏幕截图.png…]()

By the way， Is there a tutorial for compiling individual components。
Thank you for your reply

**Comment by xiexu0210** [comment]
![Uploading 2021-05-28 12-16-21屏幕截图.png…]()

**Comment by xiexu0210** [comment]
![2021-05-28 12-16-21屏幕截图](https://user-images.githubusercontent.com/72843739/119929082-69320580-bfaf-11eb-8cf5-867b2fb5722d.png)

**Comment by ZwwWayne** [comment]
The current message does not show the error traceback, so we do not know why it fails.

**Comment by ZwwWayne** [comment]
Please use the `error template`.
