### ISSUE TITLE
yolov3 关于中心坐标x\y的损失为什么使用BCE损失?不应该使用L2损失么?

### ISSUE THREAD

**Issue by jiejie1993** [open-mmlab/mmdetection#5241]
loss_xy=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=2.0,
            reduction='sum'),

**Comment by RangiLyu** [comment]
Please refer to 2.1. in yolov3 paper. https://arxiv.org/pdf/1804.02767.pdf

**Comment by clw5180** [comment]
> Please refer to 2.1. in yolov3 paper. https://arxiv.org/pdf/1804.02767.pdf

请教一下，xywh不是都使用平方差损失么
