### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by ChessQian** [open-mmlab/mmdetection#525]
I have already set CUDA_HOME in ~/.bashrc, but when I compile, it still has "OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root."
HELP!

**Comment by ChessQian** [comment]
I set export CUDA_HOME=/usr/local/cuda-9.0 in ~/.bashrc, and alias gcc='/usr/bin/gcc-6 -std=c++11'
alias g++='/usr/bin/g++-6 -std=c++11' for compile

**Comment by hellock** [comment]
Did you source your bashrc after making modifications?

**Comment by ChessQian** [comment]
> Did you source your bashrc after making modifications?

Yes，I did. Now I retry the compile.sh, it has these errors:
envs/fastai/lib/python3.7/site-packages/torch/lib/include/c10/util/string_utils.h:57:12: error: ‘std::to_string’ has not been declared  using std::to_string;
I compile it with g++-5 and gcc-5, and I tried with g++ -std=c++11 gcc -std=c11, but it still has these errors.

**Comment by ChessQian** [comment]
Here is what I set in bashrc
export PATH=/usr/local/cuda-9.0/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda-9.0
alias gcc='gcc -std=c11'
alias g++='g++ -std=c++11'

**Comment by tzhang2014** [comment]
you shoude do ln -s cuda-9.0 cuda in cuda root path

**Comment by tzhang2014** [comment]
you should do ln -s cuda9-0 cuda

**Comment by henbucuoshanghai** [comment]
cuda10 is not useful????it must be cuda9.0?

**Comment by leiqing110** [comment]
i met the same error. have u solved it?

**Comment by MaarufB** [comment]
Hi guys, have you solve this problem?
