### ISSUE TITLE
Can mmdetection generate result images from the trained log test results? 

### ISSUE THREAD

**Issue by JoJoliking** [open-mmlab/mmdetection#5250]
For example, the VOC test results after each epoch will be output into image format

**Comment by ZwwWayne** [comment]
For now, MMDet does not officially support that. You can add a hook to implement that.

**Comment by JoJoliking** [comment]
@ZwwWayne Thank you. By the way. I have tow questions in traing by mmdet
1. I use mmdet default configs of yolov3 and I only modify datasets and numclass in yolov3 configs. When I train yolov3 with 4*4 batch, the loss is nan or can't be convergent. 
2. When I train GFLV1 （Modified also the same as yolov3 ）, it raises a fatal error : RuntimeError: result type Float can’t be cast to the desired output type Long
Can you Give me advice ? Thank you

**Comment by JoJoliking** [comment]
yolov3 testing result of VOC in each epoch is 0.001~0.002. This is abnormal
