### ISSUE TITLE
How to import DeformConv?

### ISSUE THREAD

**Issue by luowy1001** [open-mmlab/mmdetection#526]
I follow: `mmdetection_env.sh` to install this lib
there is no problem when run `compile.py` and `python setup.py install`
Then, run` import mmdet` , it works well
But, when I enter /mmdet/ops/dcn/, and run `import import DeformConv` or` import deform_conv`,
It displays:
`ModuleNotFoundError: No module named 'DeformConv'`
or 
`ModuleNotFoundError: No module named 'deform_conv'`
In the file /mmdet/ops/dcn/, there are two `.so` files: 
`deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so`
`deform_pool_cuda.cpython-36m-x86_64-linux-gnu.so`
The evns:
pytorch: 1.0.1.post2
python: Python 3.6.2

**Comment by hellock** [comment]
You cannot run a python interpreter or python script inside a package. You can just go outside the package and use `from mmdet.ops import DeformConv`.
