### ISSUE TITLE
What does it mean when set total_epochs=8, the acutal number of epochs is 64?

### ISSUE THREAD

**Issue by ArchNew** [open-mmlab/mmdetection#5270]
From the finetune guide https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/finetune.md, "total_epochs" is 8 times of actual epochs. Where the '8' comes from? The number of GPUs? What can I do if I want to set actual epochs to 3?

**Comment by AronLin** [comment]
Sorry, this comment is a bug, we will fix it.
The total epochs is 8 when you set total_epochs=8 whatever the batch size is, unless the dataset is RepeatDataset.
When the dataset type is RepeatDataset, the total epochs is total_epochs * repeat_times.

**Comment by ArchNew** [comment]
Thanks for your answer.
