### ISSUE TITLE
RuntimeError: nms is not compiled with GPU support

### ISSUE THREAD

**Issue by SamMohel** [open-mmlab/mmdetection#5278]
i got this error 
`RuntimeError: nms is not compiled with GPU support`
 when running this command 
`python3 test.py  retinanet.py /path/epoch_3.pth  --show-dir results.pkl`
although i had a cuda and checked it by `nvidia-smi` and got this 

`|NVIDIA-SMI 450.80.02    Driver Version: 450.80.02           CUDA Version: 11.0     |`

i checked 
`python3 -c "import torch; print(torch.__version__); print(torch.version.cuda)"` and got 
`1.8.1+cu102`
`10.2`

**Comment by hhaAndroid** [comment]
Hi @SamMohel Your mmcv version needs to follow the full version, you can consider the following command `pip install mmcv-full==1.3.5 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html`
