### ISSUE TITLE
How can I get the "Inf time (fps)" like in the baselines of model zoo?

### ISSUE THREAD

**Issue by forestriveral** [open-mmlab/mmdetection#528]
Does it just mean that, doing the evaluation on test set first then calculating the average inference time of each image or other accurate way?

**Comment by hellock** [comment]
You just need to run the testing script, which will do it.

**Comment by forestriveral** [comment]
Thank you for your reply!

**Comment by ujsyehao** [comment]
@forestriveral Hi, Do you know how to get fps? When I use tools/test.py, I just can get mAP of the detection method.

**Comment by ujsyehao** [comment]
@hellock Hi, When I run tools/test.py, I just can get mAP, no fps.

**Comment by ujsyehao** [comment]
@hellock 
![23](https://user-images.githubusercontent.com/17454232/60570095-5b63ad80-9da3-11e9-8e6e-f41a0dc6b10b.jpg)
Dose

**Comment by KDcx35** [comment]
@ujsyehao @forestriveral hi,have you guys figure out how to get inference speed(fps)?Can you show me how to do it?Thank you!

**Comment by dinhthihuyen** [comment]
> @hellock ![23](https://user-images.githubusercontent.com/17454232/60570095-5b63ad80-9da3-11e9-8e6e-f41a0dc6b10b.jpg) 51.6 is fps?

@hellock is 51.6 the fps?
