### ISSUE TITLE
How to use “Add simple_test to dense heads“?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#5285]
Hi, dear authors
Sorry to borher you.
mmdet has updated the new feature of Add simple_test to dense heads. Could you tell me how can I use this new feature? 
Thank you！

**Comment by hhaAndroid** [comment]
Hi @zhongqiu1245 This PR just unifies the function entry and has no effect on the logic. The usage does not require special attention.

**Comment by zhongqiu1245** [comment]
Thank you@hhaAndroid
