### ISSUE TITLE
Config errors for configs/detectors/detectors_htc_r101_20e_coco.py

### ISSUE THREAD

**Issue by joe-siyuan-qiao** [open-mmlab/mmdetection#5287]
I came across [configs/detectors/detectors_htc_r101_20e_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/detectors/detectors_htc_r101_20e_coco.py) and found that only the backbone in the _neck_ is changed to r101, but the backbone in _backbone_ is still r50. So this config actually implements r50 + r101. Just wanted to point out this error and hope to see it updated soon.

Thank you!

**Comment by hhaAndroid** [comment]
Hi @joe-siyuan-qiao  The base config is `_base_ = '../htc/htc_r101_fpn_20e_coco.py'`, so the backbone is r101 not r50.

**Comment by joe-siyuan-qiao** [comment]
Ah, that's right. Thanks for the prompt reply! Will close this.
