### ISSUE TITLE
debug error

### ISSUE THREAD

**Issue by mytk2012** [open-mmlab/mmdetection#5288]
When I debug the code refers to **mmcv.inshow_det_bboxes line 330** in mmdet/models/detectors/base.py,
**the error** was,**self:ATSS** with_box:('Traceback (most recent call last):\n  File "/root/.vscode-server/extensions/ms-python.python-2021.5.842923320/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py", line 193, in _get_py_dictionary\n    attr = getattr(var, name)\n  File "/root/anaconda3/envs/mmdetection/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in __getattr__\n    raise AttributeError("\'{}\' object has no attribute \'{}\'".format(\nAttributeError: \'ATSS\' object has no attribute \'with_bbox\'\n')
But bboxes and bbox_result has values.

**Comment by hhaAndroid** [comment]
Hi @mytk2012  You can try the following script to see if it is correct？ `python demo/image_demp.py  configs/atss/atss_r101_fpn_1x_coco.py  http://download.openmmlab.com/mmdetection/v2.0/atss/atss_r50_fpn_1x_coco/atss_r50_fpn_1x_coco_20200209-985f7bd0.pth `
