### ISSUE TITLE
Any plans for mask scoring rcnn ?

### ISSUE THREAD

**Issue by nemonameless** [open-mmlab/mmdetection#529]
Any plans for mask scorng rcnn ? It is an improvement for all instance segmentation models.

https://github.com/zjhuang22/maskscoring_rcnn

**Comment by hellock** [comment]
Our team is working on that.

**Comment by runzeer** [comment]
when will the scoring rcnn be released?

**Comment by runzeer** [comment]
> Any plans for mask scorng rcnn ? It is an improvement for all instance segmentation models.
> 
> https://github.com/zjhuang22/maskscoring_rcnn

Have you tried to reincomplement with the mask scoring rcnn?

**Comment by runzeer** [comment]
> > Any plans for mask scorng rcnn ? It is an improvement for all instance segmentation models.
> > https://github.com/zjhuang22/maskscoring_rcnn
> 
> Have you tried to reincomplement with the mask scoring rcnn? There is something wrong with the codes.

**Comment by runzeer** [comment]
> > > Any plans for mask scorng rcnn ? It is an improvement for all instance segmentation models.
> > > https://github.com/zjhuang22/maskscoring_rcnn
> > 
> > 
> > Have you tried to reincomplement with the mask scoring rcnn?

**Comment by hellock** [comment]
#621
