### ISSUE TITLE
question about self.cls_out_channels

### ISSUE THREAD

**Issue by johnson-magic** [open-mmlab/mmdetection#5297]
In the file 'mmdet/models/dense_heads/anchor_head.py', line 69~72. I am confused by these code, below. I want to know why use_sigmoid will affect the channel number? 

I am viewing general focal loss source code. I find for gfocal v2. It is a small "bug", to some extent. See the gfocal v2 author's answer snapshot, below, please. But , I think it's ok, maybe. Because, More channels is  compatible with the less in cnn. 
And these codes belongs to a base class AnchorHead. Maybe you want to be compatible with other child class head.

So, any algorithms else use the "+1" branch truly. If so, I think it is ok. Otherwise,  It is a bug, truely? And I new a pr, [#5298](https://github.com/open-mmlab/mmdetection/pull/5298).

sanpshot one:
![image](https://user-images.githubusercontent.com/19408186/120895046-d992f380-c64d-11eb-91cc-65948203e15c.png)

snapshot two:
![image](https://user-images.githubusercontent.com/19408186/120895688-b9b0ff00-c650-11eb-8428-ae4fcc010613.png)

**Comment by shinya7y** [comment]
Please refer to the discussion in https://github.com/implus/GFocalV2/issues/12

**Comment by ZwwWayne** [comment]
It is mainly used to distinguish whether the activation includes background (for softmax) or not (for sigmoid).

**Comment by johnson-magic** [comment]
OK, I got it. Thank you.
