### ISSUE TITLE
Has this code been tested with cuda 10.0?

### ISSUE THREAD

**Issue by yaoliUoA** [open-mmlab/mmdetection#53]
Hi 
I have problems when running the 'compile.sh'. I got the following error: 

`/home/yao/.local/lib/python2.7/site-packages/torch/lib/include/THC/THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone

/home/yao/.local/lib/python2.7/site-packages/torch/lib/include/THC/THCAtomics.cuh(123): error: return value type does not match the function type

2 errors detected in the compilation of "/tmp/tmpxft_0000150c_00000000-4_roi_align_kernel.cpp4.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
`
It seems that the problems is with the cuda version. What cuda version has been used testing this package? I am using cuda 10.0 and pytorch 0.4.1.

**Comment by hellock** [comment]
We have not tested the codebase with CUDA 10. CUDA 9.x + PyTorch 0.4.1 works well. We will try CUDA 10 and update the results here. (Only Python 3 is supported)

**Comment by hellock** [comment]
According to https://github.com/pytorch/pytorch/issues/12075, CUDA 10 is not compatible with PyTorch 0.4.1, we will support CUDA 10 after migrating to the stable release of 1.0.
