### ISSUE TITLE
./compile.sh error

### ISSUE THREAD

**Issue by Songluchuan** [open-mmlab/mmdetection#531]
my environment:

blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.2           py36h2e261b9_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
cloog                     0.18.0                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
cudatoolkit               8.0                           3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Cython                    0.29.7                    <pip>
freetype                  2.9.1                h8a8886c_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
gcc-5                     5.2.0                         1    psi4
gmp                       6.1.2                h6c8ec71_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
intel-openmp              2019.3                      199    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
isl                       0.12.2                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
jpeg                      9b                   h024ee3a_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libedit                   3.1.20181209         hc058e9b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgcc-ng                 8.2.0                hdf63c60_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgfortran-ng            7.3.0                hdf63c60_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libpng                    1.6.36               hbc83047_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libstdcxx-ng              8.2.0                hdf63c60_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libtiff                   4.0.10               h2733197_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl                       2019.3                      199    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_fft                   1.0.10           py36ha843d7b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_random                1.0.2            py36hd81dba3_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mpc                       1.1.0                h10f8cd9_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mpfr                      4.0.1                hdf1c602_3    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
ncurses                   6.1                  he6710b0_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
ninja                     1.9.0            py36hfd86e86_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
numpy                     1.16.2           py36h7e9f1db_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
numpy-base                1.16.2           py36hde5b4d6_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
olefile                   0.46                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
openssl                   1.1.1b               h14c3975_1    conda-forge
pillow                    5.4.1            py36h34e0f95_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
pip                       19.0.3                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
pycparser                 2.19                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
python                    3.6.8                h0371630_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
pytorch                   1.0.1           py3.6_cuda8.0.61_cudnn7.1.2_2    pytorch
readline                  7.0                  h7b6447c_5    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
setuptools                41.0.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
six                       1.12.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
sqlite                    3.27.2               h7b6447c_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tk                        8.6.8                hbc83047_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
torchvision               0.2.2                      py_3    pytorch
wheel                     0.33.1                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
xz                        5.2.4                h14c3975_4    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
zlib                      1.2.11               h7b6447c_3    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
zstd                      1.3.7                h0b5b093_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main

when I run compile.sh,an unexpected error occurred,this error links to the line:

gcc -pthread -B /home/slc/anaconda3/envs/mmdetection/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include/TH -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/slc/anaconda3/envs/mmdetection/include/python3.6m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.6/src/roi_align_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include/TH -I/home/slc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/slc/anaconda3/envs/mmdetection/include/python3.6m -c src/roi_align_kernel.cu -o build/temp.linux-x86_64-3.6/src/roi_align_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /home/slc/anaconda3/envs/mmdetection/compiler_compat -L/home/slc/anaconda3/envs/mmdetection/lib -Wl,-rpath=/home/slc/anaconda3/envs/mmdetection/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/src/roi_align_cuda.o build/temp.linux-x86_64-3.6/src/roi_align_kernel.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.6/roi_align_cuda.cpython-36m-x86_64-linux-gnu.so
/home/slc/anaconda3/envs/mmdetection/compiler_compat/ld: cannot find -lm
/home/slc/anaconda3/envs/mmdetection/compiler_compat/ld: cannot find -lpthread
/home/slc/anaconda3/envs/mmdetection/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1

and plenty of these
ps: I meet this problem when I run maskrcnn-benchmark,solve it by add extra_link_args=['-L/usr/lib/x86_64-linux-gnu/'] in setup.py,but hoe to solve this problem in mmdetection?

look forward to ur rely

**Comment by hellock** [comment]
If you already have gcc 4.9+ on your system, you may just uninstall the one in your conda environment,
otherwise you can also add the extra linking args to setup.py of all ops (eg, [RoIAlign](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/roi_align/setup.py#L10)).

**Comment by Songluchuan** [comment]
thanks for u rely.**But after I add the extra link args,It have some error like this:**

Building roi align op...
  File "setup.py", line 11
    extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']
                   ^
SyntaxError: invalid syntax

**My RoIAlign setup.py here:**

setup(
    name='roi_align_cuda',
    ext_modules=[
        CUDAExtension('roi_align_cuda', [
            'src/roi_align_cuda.cpp',
            'src/roi_align_kernel.cu',
        ]),
    extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']
    ],
    cmdclass={'build_ext': BuildExtension})

**Can u give me an exmple about where to put  extra link?**
look forward to ur rely

**Comment by hellock** [comment]
`extra_link_args` is the argument of `CUDAExtension`.

**Comment by Songluchuan** [comment]
Thanks for you reply !  I have already finish this problem by your guidance
