### ISSUE TITLE
is there any function or something to save cropped detected result?

### ISSUE THREAD

**Issue by gihunsong** [open-mmlab/mmdetection#5310]
so for now, i understood that i can get result image which is on the inferenced image with bounding box, 

but

i wanna know there is any function or something to save cropped detected results.

Thanks in advance!

**Comment by orbitlink** [comment]
One way to do this is to use the result directly returned by :
```python
from mmdet.apis import inference_detector
    result = inference_detector(model, image)
```
You can use the good script given by @tommyjiang in the post [#248](https://github.com/open-mmlab/mmdetection/issues/248) to write your own function to extract bounding boxes or pixel masks from the detected objects and simply cropped them to the image.

**Comment by gihunsong** [comment]
@orbitlink thank you for your answer!
