### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'data'

### ISSUE THREAD

**Issue by justinkeke91** [open-mmlab/mmdetection#5314]
Hello everyone. I want to use the trained mmdetetion model to predict .But I got the Error 'AttributeError: 'ConfigDict' object has no attribute 'data'' .Here is my code. How shoud I do?

----------------------------------------------------------------------------------------------------------------------------------------------
from argparse import ArgumentParser
import os
from mmdet.apis import inference_detector, init_detector  #, show_result_pyplot
import cv2
 
def show_result_pyplot(model, img, result, score_thr=0.3, fig_size=(15, 10)):
    """Visualize the detection results on the image.
    Args:
        model (nn.Module): The loaded detector.
        img (str or np.ndarray): Image filename or loaded image.
        result (tuple[list] or list): The detection result, can be either
            (bbox, segm) or just bbox.
        score_thr (float): The threshold to visualize the bboxes and masks.
        fig_size (tuple): Figure size of the pyplot figure.
    """
    if hasattr(model, 'module'):
        model = model.module
    img = model.show_result(img, result, score_thr=score_thr, show=False)
    return img
    # plt.figure(figsize=fig_size)
    # plt.imshow(mmcv.bgr2rgb(img))
    # plt.show()
 
 
def main():
    # config file 
    config_file = '/home/enro/mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py'
    #train model
    checkpoint_file = '/home/enro/mmdetection/work_dirs/faster_rcnn_r50_fpn_1x_voc_cat0602/epoch_100.pth'
 
    # model = init_detector(config_file, checkpoint_file)
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
 
    # input dir
    img_dir = '/home/enro/ダウンロード/Test_017-01/'
    # output dir
    out_dir = '/home/enro/ダウンロード/test0607/'
 
    if not os.path.exists(out_dir):
        os.mkdir(out_dir)
    
    # jpg list
    test_path = '/home/enro/mmtest/jpg.txt'
    fp = open(test_path, 'r')
    test_list = fp.readlines()
 
    count = 0
    imgs = []
    for test in test_list:
        #test = test.replace('\n', '')
        #name = img_dir + test + '.JPG'
        name = img_dir + '.JPG'
        
        count += 1
        print('model is processing the {}/{} images.'.format(count, len(test_list)))
        # result = inference_detector(model, name)
        # model = init_detector(config_file, checkpoint_file, device='cuda:0')
        result = inference_detector(model, name)
        img = show_result_pyplot(model, name, result, score_thr=0.8)
        cv2.imwrite("{}/{}.JPG".format(out_dir, test), img)
 
 
if __name__ == '__main__':
    main()
----------------------------------------------------------------------------------------------------------------------------------------------my GPU 's environment is here.

NVIDIA-SMI 460.73.01 Driver Version: 460.73.01 CUDA Version: 11.0

torch 1.7.1+cu110
torchaudio 0.7.2
torchvision 0.8.2+cu110
tornado 6.1
mmcv-full 1.3.3
mmdet 2.12.0

**Comment by hhaAndroid** [comment]
The information you provided is a bit messy, I suggest you use the https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.pyscript to predict

**Comment by justinkeke91** [comment]
> The information you provided is a bit messy, I suggest you use the https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.pyscript to predict

Thank you very much. I tried but got the same Error.

**Comment by hhaAndroid** [comment]
> > The information you provided is a bit messy, I suggest you use the https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.pyscript to predict
> 
> Thank you very much. I tried but got the same Error.

Please do not modify the code, and then directly use the official weight to try if it is correct.

**Comment by justinkeke91** [comment]
> > > The information you provided is a bit messy, I suggest you use the https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.pyscript to predict
> > 
> > 
> > Thank you very much. I tried but got the same Error.
> 
> Please do not modify the code, and then directly use the official weight to try if it is correct.

I don't know why but when I changed the code to this, it worked. Thank you. New code is here.

----------------------------------------------------------------------------------------------------------------------------------------------

import mmcv
import os
import numpy as np
from mmcv.runner import load_checkpoint
from mmdet.models import build_detector
from mmdet.apis import init_detector, inference_detector, show_result_pyplot


config_file = '/home/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
# url: http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
checkpoint_file =  '/home/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'

model = init_detector(config_file,checkpoint_file)

img_dir = '/home/en_ro/ダウンロード/Test_017_01/'
out_dir = 'results/'

if not os.path.exists(out_dir):
    os.mkdir(out_dir)

img = '017-01_0034_o_S017-1_0035.JPG'
result = inference_detector(model,img)
show_result_pyplot(model, img, result, score_thr=0.7)
print(result)

**Comment by shaoshuaidu** [comment]
> 

it works，thank you
