### ISSUE TITLE
[Refactor] Rewrite config files use init_cfg instead of model.pretrained

### ISSUE THREAD

**Issue by BIGWangYuDong** [open-mmlab/mmdetection#5318]
Using `model.pretrained` to Initialize the backbone will get a warning: *UserWarning: init_cfg without layer key if you do not define override key either, this init_cfg will do nothing*.
It is necessary to rewrite config files, using `init_cfg` to initialize the backbone.

**Comment by hhaAndroid** [comment]
> Using `model.pretrained` to Initialize the backbone will get a warning: _UserWarning: init_cfg without layer key if you do not define override key either, this init_cfg will do nothing_.
> It is necessary to rewrite config files, using `init_cfg` to initialize the backbone.

Yes, you can.

**Comment by alexeyhorkin** [comment]
@BIGWangYuDong , @hhaAndroid , 
Does this mean that when I define load_from="/path/to/my/.pth" weights for the model are not loaded?

**Comment by BIGWangYuDong** [comment]
@alexeyhorkin ,
Hi, in mmdet, we first init model weights, then, if we want to load the whole model, we use the key `load_from` to load the `.pth` file. `load from` or `resume from` does not conflict with init weights.
