### ISSUE TITLE
cur_target >= 0 && cur_target < n_classes`

### ISSUE THREAD

**Issue by hankangying** [open-mmlab/mmdetection#5319]
/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THCUNN/ClassNLLCriterion.cu:57: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=61 error=59 : device-side assert triggered

我的类别有39个 num_classes设置为了39   标签标号是从0开始的

使用python ./tools/train.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py进行训练时提示上述的错误

**Comment by hhaAndroid** [comment]
The num_classes setting is correct. Have you modified the code logic?  It is recommended that you use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.pyscript visualization label to confirm whether it is correct

**Comment by hankangying** [comment]
> The num_classes setting is correct. Have you modified the code logic? It is recommended that you use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.pyscript visualization label to confirm whether it is correct

CUDA_LAUNCH_BLOCKING=1 python ./tools/misc/browse_dataset.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[                                                  ] 0/26, elapsed: 0s, ETA:[46 46]
Traceback (most recent call last):
  File "./tools/misc/browse_dataset.py", line 97, in <module>
    main()
  File "./tools/misc/browse_dataset.py", line 91, in main
    text_color=(255, 102, 61))
  File "/userdata/hyk/mmdetection/mmdet/core/visualization/image.py", line 139, in imshow_det_bboxes
    label] if class_names is not None else f'class {label}'
IndexError: tuple index out of range

当我运行这个可视化文件时 提示下标越界  想要访问下标为46的类别 可是我的下标是0-38

**Comment by hankangying** [comment]
> The num_classes setting is correct. Have you modified the code logic? It is recommended that you use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.pyscript visualization label to confirm whether it is correct

[46]
Traceback (most recent call last):
  File "./tools/misc/browse_dataset.py", line 97, in <module>
    main()
  File "./tools/misc/browse_dataset.py", line 68, in main
    print(dataset)
  File "/userdata/hyk/mmdetection/mmdet/datasets/custom.py", line 343, in __repr__
    instance_count[unique] += counts
IndexError: index 46 is out of bounds for axis 0 with size 40
当我尝试输出browse_dataset.py  文件中的dataset时  同样想要访问index 46  可是超出了40

**Comment by hhaAndroid** [comment]
If you did not modify the code, it means that your json file is incorrect.

**Comment by hankangying** [comment]
> 如果你没有修改代码，说明你的json文件不正确。

我的json中的  images annotatios  categories 如下图所示
![image](https://user-images.githubusercontent.com/51064113/121310757-4819cf00-c936-11eb-939f-64f8aeee8c54.png)
![image](https://user-images.githubusercontent.com/51064113/121310781-4f40dd00-c936-11eb-974b-3f2eda6a5184.png)
![image](https://user-images.githubusercontent.com/51064113/121310831-5cf66280-c936-11eb-8a87-9bf4802cea7b.png)

**Comment by hankangying** [comment]
> If you did not modify the code, it means that your json file is incorrect.

我的json在他人那边可以运行  在我这边不可以  尽管我们使用相同的环境
CUDA_LAUNCH_BLOCKING=1 python ./tools/misc/browse_dataset.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[                                                  ] 0/47, elapsed: 0s, ETA:46
Traceback (most recent call last):
  File "./tools/misc/browse_dataset.py", line 96, in <module>
    main()
  File "./tools/misc/browse_dataset.py", line 90, in main
    text_color=(255, 102, 61))
  File "/userdata/anaconda3/envs/hyk37/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/core/visualization/image.py", line 137, in imshow_det_bboxes
    label] if class_names is not None else f'class {label}'
IndexError: tuple index out of range

当我使用您提出的方法查看时 提示下标越界  它总是试图访问下标为46的位置

**Comment by hhaAndroid** [comment]
Your image number are relatively small, I suggest you check the json carefully。
