### ISSUE TITLE
Any plans for TridentNet ?

### ISSUE THREAD

**Issue by qixuxiang** [open-mmlab/mmdetection#532]
Thanks for amazing work!
Maybe [TridentNet](https://arxiv.org/abs/1901.01892) is the most accurate two-stage object detection algorithm so far, it is implemented in [simpledet](https://github.com/TuSimple/simpledet/), which is a mxnet based framework and only supports coco dataset.
A student is trying to translate TridentNet into Pytorch, which is in [a-new-scale-aware-loss-](https://github.com/wei-yuma/a-new-scale-aware-loss-).

**Comment by hellock** [comment]
No recent plan for that, and community contribution is welcome.
If you are just looking for a high-performance method, you may also have a try for [Hybrid Task Cascade](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/README.md#results-and-models).

**Comment by qixuxiang** [comment]
Thanks for your reply^_^
