### ISSUE TITLE
A question in iou_balanced_neg_sampler

### ISSUE THREAD

**Issue by LaoYang1994** [open-mmlab/mmdetection#5323]
https://github.com/open-mmlab/mmdetection/blob/47d468ef08235e1ab4d11c96a0fd70a9b542ca71/mmdet/core/bbox/samplers/iou_balanced_neg_sampler.py#L58

In this place, we want to sample negative samples in a balanced way. I think the max iou of negative samples or the high_thresh for the negative is the better choice. Suppose the number of iou bins is 2, the max_iou of all samples is 1 and the positive thresh is 0.5, there is only one valid iou interval([0, 0.5)), which degenerates to random sampling.

**Comment by LaoYang1994** [comment]
@AronLin @ZwwWayne Is there any answer ?

**Comment by AronLin** [comment]
Maybe you can discuss this issue with the authors of the paper.
