### ISSUE TITLE
"init_detector()" and "inference_detector()” API BUG

### ISSUE THREAD

**Issue by Hr-Song** [open-mmlab/mmdetection#5326]
When I tried using "init_detector()" and "inference_detector()" API to inference **deformable_detr_refine_r50_16x2_50e_coco**  network, I set the argument'--device' to 'cuda:1'. However,  nvidia-smi shows that the program is running on both GPU0 and GPU1 instead of just GPU1 as I set.

**Comment by RangiLyu** [comment]
You can print(next(model.parameters()).device) to check which GPU the model is using. The gpu usage in nvidia-smi is about all processes on your pc. Also, you can set CUDA_VISIBLE_DEVICES to make sure you only use which device.

**Comment by Hr-Song** [comment]
I have already checked carefully. **deformable_detr_refine_r50_16x2_50e_coco** is indeed running on both GPU0 and GPU1 despite I set device to GPU0. It happened even if I used torch.cuda.set_device to switch the GPUs. But when I use  DETR model to inference instead of Deformable_DETR then, the GPU was set correctly. Therefore, I think such problems only happen when using Deformable_DETR.

**Comment by RangiLyu** [comment]
Thanks for your reply! There may be some problems in Deformable_DETR, we will check it asap.

**Comment by RangiLyu** [comment]
Solved in open-mmlab/mmcv#1402. Please install the latest mmcv.
