### ISSUE TITLE
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]

### ISSUE THREAD

**Issue by jiejie1993** [open-mmlab/mmdetection#5331]
**Describe the bug**
I convert YoloV3 pytorch -> onnx -> tensorrt, when I run onnx2tensorrt.py and pytorch2onnx.py, the result from pytorch/onnx/tensorrt is same. The command is as following:
`python tools/deployment/pytorch2onnx.py configs/yolo/yolov3_d53_mstrain-608_273e_voc_haiyangshengwu.py yolov3_work_dir/epoch_101.pth --output-file checkpoints/epoch_101_backend.onnx --input-img tests/data/Angelas_1.jpg --test-img tests/data/Angelas_1.jpg --shape 608 608 --mean 0 0 0 --std 255 255 255  --show --verify --dynamic-export`
`
python tools/deployment/onnx2tensorrt.py checkpoints/epoch_101_backend.onnx --trt-file checkpoints/epoch_101_backend.trt --input-img tests/data/Angelas_1.jpg --shape 608 608 --mean 0 0 0 --std 255 255 255 --show --verify
`
But when I run **test.py** to verificate the tensorrt model, the command is:
`python tools/deployment/test.py configs/yolo/yolov3_d53_mstrain-608_273e_voc_haiyangshengwu.py checkpoints/epoch_101_backend.trt --out log_model_dir/haiyangshengwu_YoloV3/out_result.pkl --backend tensorrt --eval mAP --show-dir log_model_dir/haiyangshengwu_YoloV3/`
 I found the error:
`[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]`

Besides, the output of the tensorrt's test running in test.py is much poorer than onnx model.
`
**tensorrt:**
---------------iou_thr: 0.5---------------

+--------------------+-----+-------+--------+-------+
| class              | gts | dets  | recall | ap    |
+--------------------+-----+-------+--------+-------+
| angelas            | 230 | 1217  | 0.000  | 0.000 |
| angel_fish         | 305 | 2379  | 0.567  | 0.156 |
| Apple_Mermaid      | 122 | 20149 | 0.623  | 0.017 |
| Ball_photoelectric | 127 | 255   | 0.008  | 0.000 |
+--------------------+-----+-------+--------+-------+
| mAP                |     |       |        | 0.043 |
+--------------------+-----+-------+--------+-------+
OrderedDict([('AP50', 0.043), ('mAP', 0.043374571949243546)])`

`
**onnx**:
---------------iou_thr: 0.5---------------

+--------------------+-----+------+--------+-------+
| class              | gts | dets | recall | ap    |
+--------------------+-----+------+--------+-------+
| angelas            | 230 | 8411 | 0.922  | 0.791 |
| angel_fish         | 305 | 5570 | 0.951  | 0.925 |
| Apple_Mermaid      | 122 | 5012 | 0.975  | 0.929 |
| Ball_photoelectric | 127 | 5007 | 0.953  | 0.921 |
+--------------------+-----+------+--------+-------+
| mAP                |     |      |        | 0.892 |
+--------------------+-----+------+--------+-------+
OrderedDict([('AP50', 0.892), ('mAP', 0.8916489481925964)])

`

**Environment**
sys.platform: linux
Python: 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) [GCC 7.2.0]
CUDA available: True
GPU 0: GeForce RTX 2060
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.1
MMCV: 1.3.5
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.2
MMDetection: 2.12.0+2ae25e0

**Comment by RunningLeon** [comment]
@jiejie1993 Hi, you may need to set `--shape` for min input shape  and `--max-shape` for max input shape  for onnx2tensorrt.py
https://github.com/open-mmlab/mmdetection/blob/238d3f6edcca4188bf65172d2dfebd0f2790997e/tools/deployment/onnx2tensorrt.py#L36

**Comment by jiejie1993** [comment]
> @jiejie1993 Hi, you may need to set `--shape` for min input shape and `--max-shape` for max input shape for onnx2tensorrt.py
> https://github.com/open-mmlab/mmdetection/blob/238d3f6edcca4188bf65172d2dfebd0f2790997e/tools/deployment/onnx2tensorrt.py#L36

Thanks,it helps a lot! I found I set the wrong shape [608, 608], but when I debug in tensorrt_utils.py, 
`self.context.set_binding_shape(idx, tuple(input_tensor.shape))`, I found the input_tensor.shape is [352, 608]. when I change `--shape 352 608`, it worked.

**Comment by RunningLeon** [comment]
@jiejie1993 Glad to hear it worked.

**Comment by RunningLeon** [comment]
Closed due to age. Feel free to reopen if still have the issue.
