### ISSUE TITLE
About the reduce ratio of step learning rate

### ISSUE THREAD

**Issue by JulioZhao97** [open-mmlab/mmdetection#5333]
I wonder how to set the reduce ratio of learning rate in step learning style? It seems default config is reducing learning rate with 0.1. What should I do if I want to reduce learning rate by 0.5 or other values?
optimizer = dict(type='SGD', lr=0.01, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[150])

**Comment by RangiLyu** [comment]
Add gamma=0.5 to lr_config. You can refer to https://mmcv.readthedocs.io/en/latest/_modules/mmcv/runner/hooks/lr_updater.html?highlight=StepLrUpdaterHook# to find more details.

**Comment by JulioZhao97** [comment]
> Add gamma=0.5 to lr_config. You can refer to https://mmcv.readthedocs.io/en/latest/_modules/mmcv/runner/hooks/lr_updater.html?highlight=StepLrUpdaterHook# to find more details.

thanks!!!!!!!!!
