### ISSUE TITLE
Do the Resnet in the backbone of DectorRS and the two ResNet in the RFP share parameters? 

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#5334]
Hi, dear authors!
Sorry to bother you.
Do the Resnet in the backbone of DectorRS and the two ResNet in the RFP share parameters? Or are the three ResNet parameters independent of each other?
Thank you!

**Comment by zhongqiu1245** [comment]
Any news？

**Comment by 54wb** [comment]
hi, I think the backbone in DetectoRS  and resnet in neck is not sharing parameters, so the size of .pth is larger than general network.
