### ISSUE TITLE
hi, about bbox size and feat map (roialign)

### ISSUE THREAD

**Issue by jun0wanan** [open-mmlab/mmdetection#5335]
hi,

I have a question  about bbox size and feat map .  The feat map from resnext is 4*4 . Will it be effect the bbox feat ? (Too too small.....)  How can I save this problem ? Can you give us a example ?~~~~ Thanks!

Best,
jun

**Comment by jun0wanan** [comment]
@RangiLyu~

**Comment by jshilong** [comment]
Can give me more details? I am confused about your problems.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
