### ISSUE TITLE
Adding a regression head to regress a new feature

### ISSUE THREAD

**Issue by SamihaSara** [open-mmlab/mmdetection#5337]
I am using **mmdetection project** for disease detection. I have converted my dataset in COCO Format and added a new field in the annotation file, called "severity_score"(value ranges from 0 to 1). This I want to feed along with bounding box coordinates and class labels. I have run the following command to run **mmdetection's** FasterRCNN and FCOS models:

python tools/train.py configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py
and
python tools/train.py configs/faster_rcnn/faster_rcnn_r101_fpn_2x_coco.py

Now I am trying to feed my dataset to regress a new feature in the annotation file. I understand I need to modify 
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/bbox_heads/bbox_head.py.
But **mmdetection** seems a big project I am not quite getting to feed a new field from ground truth and add a new regression head which files should I look into. Any suggestion regarding this would be greatly appreciated.
Also, for a beginner, what kind of model would be convenient i.e. anchor free or anchor models? I would like this feature in the existing code, without registering new heads/modules if possible.

@hellock please if you have some time, I would be thankful for your help.

**Comment by jshilong** [comment]
Sorry for the late response,
firstly, you should modify the config
```
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
```
add the `severity_score` to `Collect`
Then you need to change the forward-related function to pass this new field.

**Comment by SamihaSara** [comment]
@jshilong I have already done this( forward-related functions pass this new field). I can see this severity score passed to models/roi_heads/bbox_heads/bbox_head.py /
and mmdet/models/detectors/two_stage.py /
However, I am not understanding how to change training functions' logics/codes so that the algorithm learns to regress this new field alongside the bounding box. And how in Test time, I can have severity scores alongside bousing box coordinates?
My severity score ranges from 0 to 1.
Could you please advise about this? I would be very grateful.

**Comment by jshilong** [comment]
I am confused about what you want to do.
If you need an additional classification score named `severity_score`, you just need to add a binary classification head for the proposal feature in `bbox_head.py`

**Comment by SamihaSara** [comment]
I want to regress the level of occlusion, if fully occluded then the score is 0,  partial occlusion can be 0.3, 0.5, etc, if 
fully visible then the score is 1.0.

Can you please tell me how to add an extra regression head alongside the current bounding box regression head? 
I want to have occlusion results during inference with bounding box coordinates.
