### ISSUE TITLE
how to remove mask results on inference_demo.py with mask_RCNN

### ISSUE THREAD

**Issue by hyuan1991** [open-mmlab/mmdetection#5339]
hello, 
I want to remove my mask result when making inference with mask-RCNN, with only bounding box been shown.

is it possible to do this?

Thank you!

**Comment by jshilong** [comment]
remove segmentation results from `result`
 https://github.com/open-mmlab/mmdetection/blob/a1cecf63c713c53941b8dcf8a9d762baf8511f2c/mmdet/models/detectors/base.py#L303

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by CharlesNJ** [comment]
this is a similar question @jshilong, how do I return the bounding boxes parameters so I can save them in a txt file for each image?
