### ISSUE TITLE
the val metric  AP is always 0.0  when crop image by fix size

### ISSUE THREAD

**Issue by fangxu622** [open-mmlab/mmdetection#5340]
I implement a FixCrop Class according to RandomCrop Class.
I found something weird.

the validation metric ap is always 0.0  when crop image by fix size on train phase.
I bet that the implementation of FixCrop Class is correct. it's easily modified from RandomCrop Class. and the validation metric ap is also approximate 0.0 when replacing FixCrop with RandomCrop
the config file

![image](https://user-images.githubusercontent.com/16681534/121730307-15ccc500-cb22-11eb-95ef-1d445460d6fe.png)

I bet that the implementation of FixCrop Class is correct. it's easily modified from RandomCrop Class. and  the validation metric ap is  also approximate 0.0 when replacing FixCrop with RandomCrop

**Comment by ZwwWayne** [comment]
It should not be used in val and test pipelines.
