### ISSUE TITLE
how to evaluate mmdetection model?

### ISSUE THREAD

**Issue by shabbbb** [open-mmlab/mmdetection#5342]
Hey,
    Can anyone plz tell me how to evaluate the mmdetection model. I tried it by executing the mean_ap.py file. But, it does not return any output values. Do I need to write any extra comment to get the average precision of mmdetection?  Looking forward for suggestions. 
Thank you

**Comment by RangiLyu** [comment]
You can follow the steps in wiki https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#test-existing-models-on-standard-datasets

**Comment by shabbbb** [comment]
Thank you ....

**Comment by JNaranjo-Alcazar** [comment]
The link has expired... does anyone know where is the new one?
