### ISSUE TITLE
With default setting in mmdet, priority of EvalHook  is higher than CheckpointHook

### ISSUE THREAD

**Issue by Jason-cpp** [open-mmlab/mmdetection#5343]
The EvalHook is registered in `apis/train.py` by `runner.register_hook(eval_hook(val_dataloader, **eval_cfg))`

Then mmcv will give EvalHook a default  "NORMAL" priority, (NORMAL=50), But the CheckpointHook's default priority is 70.

This means the runner will eval firstly and then save the checkpoint. If there is a bug in the eval-code, and the program crashes, this checkpoint will not be saved.  This will cause waste, especially for the time-consuming epoch.

**Comment by hhaAndroid** [comment]
Has been fixed by https://github.com/open-mmlab/mmcv/pull/1120
