### ISSUE TITLE
 UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead   warnings.warn('DeprecationWarning: pretrained is a deprecated, 

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#5345]
when i run train.py 
UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead   warnings.warn('DeprecationWarning: pretrained is a deprecated, 
should i change not warning?

**Comment by ZwwWayne** [comment]
If you are using mmdetection, we will update our configs in the future and the warning will be fixed. If you are working with your own config, you need to modify the `pretrained`,  see docs in #5273

**Comment by Bin-ze** [comment]
我怎样才可以变得跟你一样强



---Original---
From: "Wenwei ***@***.***&gt;
Date: Tue, Jun 15, 2021 15:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection]  UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead   warnings.warn('DeprecationWarning: pretrained is a deprecated,  (#5345)




 
If you are using mmdetection, we will update our configs in the future and the warning will be fixed. If you are working with your own config, you need to modify the pretrained,  see docs in #5273
