### ISSUE TITLE
Get 'gt_bboxes' and 'gt_labels'  in the pkl file during test step

### ISSUE THREAD

**Issue by orbitlink** [open-mmlab/mmdetection#5346]
Is there a way to get the `gt_bboxes` and `gt_labels` in the pkl file at the same time that `det_bboxes` during the test step ?
#3653 does not change the pkl file.  

I would like to use the `map_roc_pr` function in mmdet/core/evaluation/mean_ap_visualize.py. Thanks.

**Comment by mathshangw** [comment]
Did you solve it ?

**Comment by orbitlink** [comment]
@mathshangw for the `gt_bboxes` and `gt_labels`  in the pkl file, no directlty. A solution is to get them directly from your `load_annotations` method in your `mmdetection/mmdet/datasets/yourclass.py` file.
