### ISSUE TITLE
Logging the recall metric values

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#5348]
Hello,

I noticed that the recall metrics are not logged by default in the log.json files. Is there a way to activate logging of these metrics that I am not seeing? Or do I need to edit the code?

**Comment by BIGWangYuDong** [comment]
Hi, I think you can find the metrics in the log.json, by findind the keyword: `evaluation`. For example,  `evaluation= dict(metric=['bbox', 'segm'])`, more EVAL_METRICS details you can find in the [docs](https://github.com/BIGWangYuDong/mmdetection/blob/master/docs/1_exist_data_model.md)

**Comment by pcicales** [comment]
Hi @BIGWangYuDong , it seems that mAP are logged by default while mAR are not. I can try to change the code, but I was wondering if there was an option parameter that I was missing.

**Comment by BIGWangYuDong** [comment]
> Hi @BIGWangYuDong , it seems that mAP are logged by default while mAR are not. I can try to change the code, but I was wondering if there was an option parameter that I was missing.
@pcicales 
`proposal_fast, proposal` are support for AR, you can see code details in `mmdet.datasets.coco.py`
