### ISSUE TITLE
How to match the results.pkl to original image data?

### ISSUE THREAD

**Issue by ShangYingHe** [open-mmlab/mmdetection#535]
I have train a model and created results.pkl on test data, but I don't know how to match results.pkl to my original image data.

**Comment by ShangYingHe** [comment]
> I have train a model and created results.pkl on test data, but I don't know how to match results.pkl to my original image data.

**Comment by ShangYingHe** [comment]
I've solved it.

**Comment by riciche** [comment]
> I've solved it.
Hello, i have met the similar problem, do you convert the results.pkl file into some txt files corresponding to each  image of test set

**Comment by ShangYingHe** [comment]
> > I've solved it.
> > Hello, i have met the similar problem, do you convert the results.pkl file into some txt files corresponding to each  image of test set

it's a list corresponding to the images when you are testing
testing order : 001.jpg->002.jpg->...->xxx.jpg
results.pkl : [001.jpg's prediction, 002.jpg's prediction, ..., xxx.jpg's prediction]
and xxx.jpg's prediction is also a list corresponding to each category
xxx.jpg's prediction : [bboxes for category 0, bboxes for category 1, ...]

**Comment by riciche** [comment]
> > > I've solved it.
> > > Hello, i have met the similar problem, do you convert the results.pkl file into some txt files corresponding to each  image of test set
> 
> it's a list corresponding to the images when you are testing
> if testing order like this : 001.jpg->002.jpg->...->xxx.jpg
> results.pkl will be : [001.jpg's prediction, 002.jpg's prediction, ..., xxx.jpg's prediction]
> and xxx.jpg's prediction is also a list corresponding to each category
> xxx.jpg's prediction : [bboxes for category 0, bboxes for category 1, ...]

yeah, I know , i have transformed the pkl file to txt file and gotten the big array.
What i mean is how to transform the array to a lot of txt  corresponding to each image ,like that:
![image](https://user-images.githubusercontent.com/28674267/62015705-7974d000-b1e0-11e9-8627-0e3278b2e6e1.png)
this is a example of test, i am a beginner, not familiar with python
anyway, thank you for your reply.
