### ISSUE TITLE
Caught error in DataLoader worker process 0

### ISSUE THREAD

**Issue by FirasKedidi** [open-mmlab/mmdetection#5350]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
cv2.error: OpenCV(4.1.2) /io/opencv/modules/core/src/copy.cpp:1170: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder
Error happened when training the model 
**Reproduction**

1. What command or script did you run?

```
train_detector(model, datasets[0], cfg, distributed=False, validate=False)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
2No i didn't do any modification i am just following the colab tutorial
3. What dataset did you use?
Custom dataset every image have it's own shape
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. sys.platform: linux
Python: 3.7.10 (default, May  3 2021, 02:48:31) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla K80
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.1+cu101
OpenCV: 4.1.2
MMCV: 1.3.6
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMDetection: 2.13.0+

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
  Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 624, in __call__
    self._pad_masks(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 605, in _pad_masks
    results[key] = results[key].pad(pad_shape, pad_val=self.pad_val)
  File "/content/mmdetection/mmdet/core/mask/structures.py", line 309, in pad
    for mask in self.masks
  File "/content/mmdetection/mmdet/core/mask/structures.py", line 309, in <listcomp>
    for mask in self.masks
  File "/usr/local/lib/python3.7/dist-packages/mmcv/image/geometric.py", line 450, in impad
    value=pad_val)
  cv2.error: OpenCV(4.1.2) /io/opencv/modules/core/src/copy.cpp:1170: error: (-215:Assertion failed) top >= 0 && bottom >= 0 
  && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by BIGWangYuDong** [comment]
Hi, maybe you should check out your config file and your datasets. This seems like you got a negative number. If you still got this problem, please show more information about your config file and dataset.

**Comment by FirasKedidi** [comment]
> Hi, maybe you should check out your config file and your datasets. This seems like you got a negative number. If you still got this problem, please show more information about your config file and dataset.

Conf file is the same i used the same model with the same configuration but with another dataset and it worked.
I believe that the problem is on the dataset level.
The images don't have the same sizes but i don't know what's causing the error

**Comment by FirasKedidi** [comment]
The dataset seems good tho i tried to read them with cv2 and it's good. The error is on the CopyMakeBorder.

**Comment by BIGWangYuDong** [comment]
I think this question is due to your original image size is larger than the padding size. Maybe you can create a breakpoint in `mmcv.image.geometric` line 443, and debug your code. Checking your img shape and the padding shape. You can set `workers_per_gpu=0` while debugging the code.

**Comment by FirasKedidi** [comment]
> I think this question is due to your original image size is larger than the padding size. Maybe you can create a breakpoint in `mmcv.image.geometric` line 443, and debug your code. Checking your img shape and the padding shape. You can set `workers_per_gpu=0` while debugging the code.

I don't understand why i am getting the error because i tried on a similar dataset smaller size and it worked just fine.

**Comment by BIGWangYuDong** [comment]
Due to the padding size= expect_padding_size(which is image padding size in mmdet) -  segm_original_size, and your error is padding size < 0 

You should check out your image size and segmentation image size. Maybe your segm image size is smaller than the image size, then it may get this error.

Please debug your code and check the img_shape, ori_shape, gt_semantic_seg.shape , gt_masks.shape, etc.
All the keys can get from `mmdet.datastes.pipelines.transforms.Pad` 

Give us more information and let's solve this error together.

**Comment by FirasKedidi** [comment]
> Due to the padding size= expect_padding_size(which is image padding size in mmdet) - segm_original_size, and your error might be padding size < 0
> 
> You should check out your image size and segmentation image size. Maybe your segm image size is smaller than the image size, then it may get this error.
> 
> Please debug your code and check the img_shape, ori_shape, gt_semantic_seg.shape , gt_masks.shape, etc.
> All the keys can get from `mmdet.datastes.pipelines.transforms.Pad`
> 
> Give us more information and let's solve this error together.
Update: The problem was from the data somehow google drive changed the names in the data folder. I am using google drive to store my data and it somehow changed the names of the files, therefore, they were getting each other's annotation.
Thank you for your time.
I apologize for the disturb.

**Comment by jack-luoluo** [comment]
> > Update: The problem was from the data somehow google drive changed the names in the data folder. I am using google drive to store my data and it somehow changed the names of the files, therefore, they were getting each other's annotation.
> > Thank you for your time.
> > I apologize for the disturb.

@FirasKedidi Hi, I also came across the same problem as you by using google colab for training. Could you tell me how to fix this error in google drive? Thank you!

**Comment by FirasKedidi** [comment]
> > > Update: The problem was from the data somehow google drive changed the names in the data folder. I am using google drive to store my data and it somehow changed the names of the files, therefore, they were getting each other's annotation.
> > > Thank you for your time.
> > > I apologize for the disturb.
> 
> @FirasKedidi Hi, I also came across the same problem as you by using google colab for training. Could you tell me how to fix this error in google drive? Thank you!

Hello,
Sorry for this late reply.
I just zipped the data and uploaded to google colab and it worked.
The problem was that google drive was messing up with my files names.

**Comment by SirRacha** [comment]
> > > > Update: The problem was from the data somehow google drive changed the names in the data folder. I am using google drive to store my data and it somehow changed the names of the files, therefore, they were getting each other's annotation.
> > > > Thank you for your time.
> > > > I apologize for the disturb.
> > 
> > 
> > @FirasKedidi Hi, I also came across the same problem as you by using google colab for training. Could you tell me how to fix this error in google drive? Thank you!
> 
> Hello, Sorry for this late reply. I just zipped the data and uploaded to google colab and it worked. The problem was that google drive was messing up with my files names.

Thank you!  How were you able to find out if google drive changed the names?
