### ISSUE TITLE
Annotation a custom dataset

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5353]
Hello , I would like to ask regards using my custom dataset in training a model from mmdetection. 

1. which is the better solution to ensure that the training will work correctly , is it to have the annotation on one html or text file ? or make them separately in txt file for each image? 
2. should i annotate my dataset according to coco format which has 5 items ( info, license , images ,annotation and categories ) , is it fine if i only used three of them ( images , annotation and categories )  
3. in case i have only one class to focus on , what exactly shall i change in the config files ,and other import setup files. 

please, in case there is any other document that helps in doing such training , could you please provide me with ? i try the colab tutorial included in the repository , unfortunately it did not work. 
your dataset was only labelled in way different than coco form , that made me little bit confused. 

could you please also explain to me , what do you meant by 0.00 and 0 in the annotation file as bellow: 

**Pedestrian 0.00 0 1.94 330.06 178.74 360.77 238.64 1.87 0.96 0.65 -8.50 2.07 23.02 1.59**

I can understand that the last 12 elements are the polygon represent the segmentation , is that true? 

looking forward to hear from your side.

**Comment by hhaAndroid** [comment]
Hi @alaa-shubbak Thanks for your attention.

1. Regardless of the format, it is best to convert to coco format, because it has a complete analysis tool.
2. As long as you don't report an error.
3. You can refer to face detection https://github.com/open-mmlab/mmdetection/blob/master/configs/wider_face/ssd300_wider_face.py configuration
