### ISSUE TITLE
analyze_results uses the wrong loading pipeline on test data

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#5355]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

A train pipeline is being used when get_loading_pipeline is used for a test dataset.

**Reproduction**

1. What command or script did you run?

tools/analysis_tools/analyze_results.py

```
def main():
args = parse_args()

mmcv.check_file_exist(args.prediction_path)

cfg = Config.fromfile(args.config)
if args.cfg_options is not None:
cfg.merge_from_dict(args.cfg_options)
cfg.data.test.test_mode = True
# import modules from string list.
if cfg.get('custom_imports', None):
from mmcv.utils import import_modules_from_strings
import_modules_from_strings(**cfg['custom_imports'])

cfg.data.test.pop('samples_per_gpu', 0)
cfg.data.test.pipeline = get_loading_pipeline(cfg.data.train.pipeline)
dataset = build_dataset(cfg.data.test)
outputs = mmcv.load(args.prediction_path)

result_visualizer = ResultVisualizer(args.show, args.wait_time,
args.show_score_thr)
result_visualizer.evaluate_and_show(
dataset, outputs, topk=args.topk, show_dir=args.show_dir)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Yes, in my version I changed it to the test pipeline as needed. This caused the following:

```
Traceback (most recent call last):
 File "/red/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
   exec(exp, global_vars, local_vars)
 File "<string>", line 7, in <module>
 File "/red/workspace/pycharm_projects/mmdetection/tools/analysis_tools/analyze_results_AMB.py", line 173, in analyze_results_AMB
   cfg.data.val.pipeline = get_loading_pipeline(cfg.data.test.pipeline)
 File "/red/workspace/pycharm_projects/mmdetection/mmdet/datasets/utils.py", line 109, in get_loading_pipeline
   'The data pipeline in your config file must include ' \
AssertionError: The data pipeline in your config file must include loading image and annotations related pipeline.
```

The code appears to run normally when using the train pipeline; however, I do not want to perform qualitative analysis with test time augmentation. 

3. What dataset did you use?

BDD100k

**Comment by hhaAndroid** [comment]
Hi @pcicales  Can you post your train pipeline config?

**Comment by pcicales** [comment]
Here it is @hhaAndroid

```
train_pipeline = [
   dict(type='LoadImageFromFile'),
   dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
   dict(type='RandomFlip', flip_ratio=0.0),
   dict(
       type='AutoAugment',
       policies=[[{
           'type':
               'Resize',
           'img_scale': [(400, 1280), (432, 1280), (464, 1280),
                         (496, 1280), (528, 1280), (560, 1280), (592, 1280),
                         (624, 1280), (656, 1280), (688, 1280), (720, 1280)
                         # (1024, 3840), (1088, 3840), (1152, 3840),
                         # (1216, 3840), (1280, 3840), (1344, 3840), (1408, 3840),
                         # (1472, 3840), (1536, 3840), (1600, 3840), (1664, 3840),
                         # (1728, 3840), (1792, 3840), (1856, 3840), (1920, 3840)
                         ],
           'multiscale_mode':
               'value',
           'keep_ratio':
               True
       }],
           [{
               'type': 'Resize',
               # 'img_scale': [(1700, 3840), (1800, 3840), (1900, 3840)],
               # 'img_scale': [(1408, 3840)],
               'img_scale': [(464, 1280)],
               'multiscale_mode': 'value',
               'keep_ratio': True
           }, {
               'type': 'RandomCrop',
               'crop_type': 'absolute_range',
               # 'crop_size': (1408, 2816),
               'crop_size': (464, 938),
               'allow_negative_crop': True
           }, {
               'type':
                   'Resize',
               'img_scale': [(400, 1280), (432, 1280), (464, 1280),
                             (496, 1280), (528, 1280), (560, 1280), (592, 1280),
                             (624, 1280), (656, 1280), (688, 1280), (720, 1280)
                             # (1216, 3840), (1280, 3840), (1344, 3840), (1408, 3840),
                             # (1472, 3840), (1536, 3840), (1600, 3840), (1664, 3840),
                             # (1728, 3840), (1792, 3840), (1856, 3840), (1920, 3840)
                             ],
               'multiscale_mode':
                   'value',
               'override':
                   True,
               'keep_ratio':
                   True
           }]]),
   dict(
       type='Normalize',
       mean=[123.675, 116.28, 103.53],
       std=[58.395, 57.12, 57.375],
       to_rgb=True),
   dict(type='Pad', size_divisor=32),
   dict(type='DefaultFormatBundle'),
   dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
```

**Comment by hhaAndroid** [comment]
> Here it is @hhaAndroid
> 
> ```
> train_pipeline = [
>    dict(type='LoadImageFromFile'),
>    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
>    dict(type='RandomFlip', flip_ratio=0.0),
>    dict(
>        type='AutoAugment',
>        policies=[[{
>            'type':
>                'Resize',
>            'img_scale': [(400, 1280), (432, 1280), (464, 1280),
>                          (496, 1280), (528, 1280), (560, 1280), (592, 1280),
>                          (624, 1280), (656, 1280), (688, 1280), (720, 1280)
>                          # (1024, 3840), (1088, 3840), (1152, 3840),
>                          # (1216, 3840), (1280, 3840), (1344, 3840), (1408, 3840),
>                          # (1472, 3840), (1536, 3840), (1600, 3840), (1664, 3840),
>                          # (1728, 3840), (1792, 3840), (1856, 3840), (1920, 3840)
>                          ],
>            'multiscale_mode':
>                'value',
>            'keep_ratio':
>                True
>        }],
>            [{
>                'type': 'Resize',
>                # 'img_scale': [(1700, 3840), (1800, 3840), (1900, 3840)],
>                # 'img_scale': [(1408, 3840)],
>                'img_scale': [(464, 1280)],
>                'multiscale_mode': 'value',
>                'keep_ratio': True
>            }, {
>                'type': 'RandomCrop',
>                'crop_type': 'absolute_range',
>                # 'crop_size': (1408, 2816),
>                'crop_size': (464, 938),
>                'allow_negative_crop': True
>            }, {
>                'type':
>                    'Resize',
>                'img_scale': [(400, 1280), (432, 1280), (464, 1280),
>                              (496, 1280), (528, 1280), (560, 1280), (592, 1280),
>                              (624, 1280), (656, 1280), (688, 1280), (720, 1280)
>                              # (1216, 3840), (1280, 3840), (1344, 3840), (1408, 3840),
>                              # (1472, 3840), (1536, 3840), (1600, 3840), (1664, 3840),
>                              # (1728, 3840), (1792, 3840), (1856, 3840), (1920, 3840)
>                              ],
>                'multiscale_mode':
>                    'value',
>                'override':
>                    True,
>                'keep_ratio':
>                    True
>            }]]),
>    dict(
>        type='Normalize',
>        mean=[123.675, 116.28, 103.53],
>        std=[58.395, 57.12, 57.375],
>        to_rgb=True),
>    dict(type='Pad', size_divisor=32),
>    dict(type='DefaultFormatBundle'),
>    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
> ]
> ```

Are you going to test DETR?

**Comment by pcicales** [comment]
@hhaAndroid no this is for a 3 stage cascade R-CNN

**Comment by hhaAndroid** [comment]
Hi，I found that you modified the code, in fact you don’t need to modify it.  Please refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/useful_tools.md#result-analysis.

**Comment by pcicales** [comment]
Hi @hhaAndroid , the lines I posted are straight from the repo, they are not modified.

**Comment by hhaAndroid** [comment]
Can you run it directly with the original code, I think it should be normal.

**Comment by pcicales** [comment]
The outputs do not appear to be augmented. Is it because of how the train pipeline is being used?

**Comment by hhaAndroid** [comment]
> The outputs do not appear to be augmented, even when I run it with my script. Is it because of how the train pipeline is being used?

It is only used to load annotations.

**Comment by pcicales** [comment]
Ok I understand now, sorry for the confusion

**Comment by hhaAndroid** [comment]
> Ok I understand now, sorry for the confusion

ok
