### ISSUE TITLE
gcnet x101-32x4d checkpoint is wrong

### ISSUE THREAD

**Issue by greathope** [open-mmlab/mmdetection#5356]
Please see https://github.com/open-mmlab/mmdetection/issues/4654#issue-813190257.
The backbone corresponding to this weight is resnet50. When I changed it, I can load it, but the ap is very poor in coco validation, below 0.1.
please check it, thanks.

**Comment by hhaAndroid** [comment]
Hi @greathope You are right, there is indeed a problem with this config.
