### ISSUE TITLE
Difference in results between the test and the display of the precision-recall curve 

### ISSUE THREAD

**Issue by ghost** [open-mmlab/mmdetection#5364]
I don't understand the difference between my results on my test set where I get :

```
---------------iou_thr: 0.5---------------

+----------+-----+------+--------+-------+
| class    | gts | dets | recall | ap    |
+----------+-----+------+--------+-------+
| book     | 23  | 908  | 0.957  | 0.753 |
| chair    | 68  | 1113 | 0.971  | 0.882 |
+----------+-----+------+--------+-------+
| mAP      |     |      |        | 0.818 |
+----------+-----+------+--------+-------+
OrderedDict([('AP50', 0.818), ('mAP', 0.8178441524505615)])

```
and when I use the method `map_roc_pr` in `mmdet/core/evaluation/mean_ap_visualize.py`. With `map_roc_pr` AP scrores returned are 0.01 for the first class and 0 for the second. The pr curve displays is wrong.  

I get directly my `gt_bboxes`, `gt_labels` from my `load_annotations` method for my `test.txt` file, and I extract from my _results.pkl_ file the `det_results` by classes. After verifications all argument formats are good, `assert len(det_results) == len(gt_bboxes) == len(gt_labels)` is good. 

Where is the error ? Thanks a lot.

**Comment by AronLin** [comment]
I will check it.

**Comment by AronLin** [comment]
Maybe you can use the latest version of `mmdet` to see if there is this problem? 
It is difficult for us to find problems because we do not have your dataset.
