### ISSUE TITLE
ImportError: cannot import name 'get_dataset'

### ISSUE THREAD

**Issue by SamMohel** [open-mmlab/mmdetection#5365]
i tried to use 

`from mmdet.datasets import get_dataset`

but got 

`ImportError: cannot import name 'get_dataset'`

**Comment by AronLin** [comment]
This function has been deprecated since our datasets were managed by registry.
Maybe you can check your mmdet version.

**Comment by SamMohel** [comment]
excuse me how can i check the version ?

**Comment by SamMohel** [comment]
i checked version.py and found 2.13.0

**Comment by SamMohel** [comment]
mmdet==0.6.0+0b9addf

**Comment by ZwwWayne** [comment]
Its too old, could you try the latest mmdet?

**Comment by mathshangw** [comment]
> It is too old, could you try the latest mmdet?

thanks for replying , how can i get the latest version, please ?

**Comment by SamMohel** [comment]
> It is too old, could you try the latest mmdet?

thanks for replying , how can i get the latest version please

**Comment by mathshangw** [comment]
does this the latest version mmdet 2.13.0   ?

**Comment by SamMohel** [comment]
does this the latest version `mmdet 2.13.0` ?

**Comment by AronLin** [comment]
Yes, the latest version is quite different from the version you used.

**Comment by SamMohel** [comment]
thanks but the version i have now is `mmdet  2.13.0` and still got 

`from mmdet.datasets import get_dataset
ImportError: cannot import name 'get_dataset' from 'mmdet.datasets' (/path/mmdetection/mmdet/datasets/__init__.py)`

**Comment by AronLin** [comment]
In mmdet 2.13.0, the function 'get_dataset' is already deprecated.
Please try to use build_dataset instead.

**Comment by ReyZedden** [comment]
> In mmdet 2.13.0, the function 'get_dataset' is already deprecated. Please try to use build_dataset instead.

But I still saw get_dataset in init.py of mmdet
