### ISSUE TITLE
ImportError: cannot import name 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by ws15145177388** [open-mmlab/mmdetection#5367]
When I run the verification code, I met a problem like this.

Traceback (most recent call last):
  File "mmdet/ceshi.py", line 4, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "/usr/local/lib/python3.6/dist-packages/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/usr/local/lib/python3.6/dist-packages/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/usr/local/lib/python3.6/dist-packages/mmdet/datasets/__init__.py", line 10, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/usr/local/lib/python3.6/dist-packages/mmdet/datasets/utils.py", line 9, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "/usr/local/lib/python3.6/dist-packages/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/usr/local/lib/python3.6/dist-packages/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .detectors_resnet import DetectoRS_ResNet
  File "/usr/local/lib/python3.6/dist-packages/mmdet/models/backbones/detectors_resnet.py", line 10, in <module>
    from .resnet import BasicBlock
  File "/usr/local/lib/python3.6/dist-packages/mmdet/models/backbones/resnet.py", line 10, in <module>
    from ..utils import ResLayer
  File "/usr/local/lib/python3.6/dist-packages/mmdet/models/utils/__init__.py", line 10, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/usr/local/lib/python3.6/dist-packages/mmdet/models/utils/transformer.py", line 8, in <module>
    from mmcv.cnn.bricks.transformer import (BaseTransformerLayer,
ImportError: cannot import name 'MultiScaleDeformableAttention'

My environment is:

sys.platform: linux
Python: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
CUDA available: True
GPU 0,1: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cu110
OpenCV: 4.5.2
MMCV: 1.3.6
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.13.0+a4e04e8

How will I solve the problem?

**Comment by jshilong** [comment]
@ws15145177388 @ly015 
``MultiScaleDeformableAttention`` has been moved to ``mmcv.ops.multi_scale_deform_attn`` from ``mmcv.cnn.bricks.transformer``, you should use ``from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention`` now.

I am sorry for this BC-breaking, I would fix it in `mmcv` today.

**Comment by ZwwWayne** [comment]
For now, you can also use the newest MMDet.

**Comment by askeySnip** [comment]
Using mim install is the easist way, I found it still the old version, so, do you have a plan to update the mmdet to mim? Or how can I fix the same bug with mmdet installed by mim

**Comment by AronLin** [comment]
This bug is fixed in  open-mmlab/mmcv#1100.
You can download the latest codes from [mmcv](https://github.com/open-mmlab/mmcv) and install it with mim:

    mim install -e .
