### ISSUE TITLE
wnen i use tools/analyze_results.py to storage the results of test-dev, the command line give the below error.

### ISSUE THREAD

**Issue by zw1422145571** [open-mmlab/mmdetection#5368]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**

root@559662f2e8f9:/home/ZW/ZW/mmdetection# CUDA_VISIBLE_DEVICES=3 python ./tools/analyze_results.py ./configs/dafpn/faster_rcnn_r101_dafpn_1x_coco.py ./results.pkl ./faster_rcnn_r101_results
usage: analyze_results.py [-h] {plot_curve,cal_train_time} ...
analyze_results.py: error: argument task: invalid choice: './configs/dafpn/faster_rcnn_r101_dafpn_1x_coco.py' (choose from 'plot_curve', 'cal_train_time')

**Reproduction**

1. What command or script did you run?

python ./tools/analyze_results.py ./configs/dafpn/faster_rcnn_r101_dafpn_1x_coco.py ./results.pkl ./faster_rcnn_r101_results

2. Did you make any modifications on the code or config? Did you understand what you have modified?
yes,I use my model's config,which is correct when testing on val2017.
3. What dataset did you use?
coco test-dev
**Environment**

my mmdetection version is 2.4 with a relative mmcv.

**Error traceback**
root@559662f2e8f9:/home/ZW/ZW/mmdetection# CUDA_VISIBLE_DEVICES=3 python ./tools/analyze_results.py ./configs/dafpn/faster_rcnn_r101_dafpn_1x_coco.py ./results.pkl ./faster_rcnn_r101_results
usage: analyze_results.py [-h] {plot_curve,cal_train_time} ...
analyze_results.py: error: argument task: invalid choice: './configs/dafpn/faster_rcnn_r101_dafpn_1x_coco.py' (choose from 'plot_curve', 'cal_train_time')

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by AronLin** [comment]
The error looks like because you input the wrong arguments.
With the latest version of mmdet, I ran the command, and it works.

I check the released code of mmdet 2.4, but I can not find analyze_results.py. Have you just copied the file in high version mmdet to your codebase?
