### ISSUE TITLE
how to download the ade cityscapes and coco-stuff dataset 

### ISSUE THREAD

**Issue by peterlv666** [open-mmlab/mmdetection#5372]
I  read your get_started.md carefully and didn't find how to prepare the dataset. Can you kindly tell me how to download the ade20k, cityscapes and coco-stuff dataset.  Thanks for your time and kindness.

**Comment by AronLin** [comment]
Ade：http://groups.csail.mit.edu/vision/datasets/ADE20K/
citys：https://www.cityscapes-dataset.com/
coco: https://cocodataset.org/

**Comment by peterlv666** [comment]
Thanks for your reply.
