### ISSUE TITLE
 No such file or directory: 'mmdet/version.py'

### ISSUE THREAD

**Issue by mathshangw** [open-mmlab/mmdetection#5373]
`Building roi align op... compile.sh: line 6: cd: mmdet/ops/roi_align: No such file or directory Traceback (most recent call last): File "setup.py", line 83, in <module> write_version_py() File "setup.py", line 72, in write_version_py with open(version_file, 'w') as f: IOError: [Errno 2] No such file or directory: 'mmdet/version.py' Building roi pool op... compile.sh: line 13: cd: ../roi_pool: No such file or directory Traceback (most recent call last): File "setup.py", line 83, in <module> write_version_py() File "setup.py", line 72, in write_version_py with open(version_file, 'w') as f: IOError: [Errno 2] No such file or directory: 'mmdet/version.py'`

i have 

timm                          0.4.9
torch                         1.8.0+cu111
torchaudio                    0.8.0
torchsummary                  1.5.1
torchvision                   0.9.0+cu111
mmcv-full                     1.3.6
mmdet                         2.13.0

**Comment by AronLin** [comment]
The ops have been migrated to MMCV.
So, why you can compile the ops in mmdet 2.13.0?
