### ISSUE TITLE
training of maskrcnn not work at all.

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5377]
**Describe the issue**

I try to use my own dataset which has the coco format, and use them for training a mask Rcnn model. I followed the step in the Tutorial. I modify the config files, and have my new configuration in a path (configs/human). 

**Reproduction**

1. What command or script did you run?
 i do the same as this tutorial (https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html) 
 i used the training command ''!python tools/train.py configs/human/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_person.py'' 
and i have only one class.

2. What config dir you run?
i used a new director contains all three main config needs in maskRcnn detector; 

![config file](https://user-images.githubusercontent.com/10245810/122283226-9dcd1900-ceec-11eb-8879-37e0f3a1f485.JPG)

3. Did you make any modifications on the code or config? Did you understand what you have modified?
4. What dataset did you use? my own small sample of my dataset in coco form.  

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
 i did it in colab 

![error massage in maskrcnn data builder](https://user-images.githubusercontent.com/10245810/122279795-bfc49c80-cee8-11eb-8e48-031332830e20.JPG)

could it be a problem in mmcv installation? how can i be sure it is like that.

**Comment by RangiLyu** [comment]
The first error shows your annotation file cannot be decoded. Try to make sure you converted your dataset to coco format correctly.

**Comment by alaa-shubbak** [comment]
thank you . i checked my dataset format , and i think it is similar to COCO dataset form. attached an image of my dataset. 
 i did not use any script to convert my dataset, i produced it as json file from AVI annotator , and do some checkup and changing by hand . then used it for training. 
is there any software that can check my dataset format automatically? if so , could you please give me the link of such. 

your help will be highly appreciated. 
![my dataset1](https://user-images.githubusercontent.com/10245810/122607831-78bae080-d07b-11eb-9cf1-217b5d2ac76d.JPG)
![my dataset2](https://user-images.githubusercontent.com/10245810/122608003-c0416c80-d07b-11eb-88da-4ddb6a77f957.JPG)

**Comment by alaa-shubbak** [comment]
i checked the dataset , and correct the config file , but i still get the same error of 

TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

attached an image, i did not understand what is 'doc' and 'pos' related to ?
![error again](https://user-images.githubusercontent.com/10245810/122615289-95a9e080-d088-11eb-99c0-ab1c295fbd0a.JPG)

**Comment by RangiLyu** [comment]
`TypeError: init() missing 2 required positional arguments: 'doc' and 'pos' ` means that your JSON file is still incorrect. Refer to https://docs.python.org/3/library/json.html#json.JSONDecodeError
I'm not sure what caused this, but I found that there is ` (1)` in your json filename. Try to rename it.

**Comment by alaa-shubbak** [comment]
thank you very much , i changed the json file and checked it through some online json file checker, now it is working. 
but unfortunately , i face another problem. 
attached the image of it 
![error new](https://user-images.githubusercontent.com/10245810/122672466-e8d87c00-d1cb-11eb-9d69-9dfe948a65f3.JPG)

i changed the batch_size to 16 and the num_workers to 0 , as some repository said, but i did not understand and it dose not work either. 

i did not find such error in any issue here in mmdetection.  any help . thanks

**Comment by RangiLyu** [comment]
You can use this script to check whether the dataset can be loaded correctly. https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py

And here is a similar issue: #4687

**Comment by alaa-shubbak** [comment]
here is the result of check the loading status of my dataset. 

![test my config in browser](https://user-images.githubusercontent.com/10245810/122796054-451bc880-d2be-11eb-8e50-0f3b077e4413.JPG)

is it loaded completely ? it dose not give me any error , but like complete :0 ? what dose that means? 

here also my system versions and installation: 
![my system](https://user-images.githubusercontent.com/10245810/122796079-4a791300-d2be-11eb-811b-3e5848f91d3e.JPG)

**Comment by alaa-shubbak** [comment]
I am sorry , i am so new here , so i still need some guides , 

here my configuration file , which i am running as training (with command python tools/train.py configs/'this file as py".) 

is there any mistake , something missing here ?  
![my config to train](https://user-images.githubusercontent.com/10245810/122796559-d2f7b380-d2be-11eb-861e-f140954d2b22.JPG)

**Comment by RangiLyu** [comment]
> here is the result of check the loading status of my dataset.
> 
> ![test my config in browser](https://user-images.githubusercontent.com/10245810/122796054-451bc880-d2be-11eb-8e50-0f3b077e4413.JPG)
> 
> is it loaded completely ? it dose not give me any error , but like complete :0 ? what dose that means?
> 
> here also my system versions and installation:
> ![my system](https://user-images.githubusercontent.com/10245810/122796079-4a791300-d2be-11eb-811b-3e5848f91d3e.JPG)

Normally, browse_dataset.py will visualize the images and annotations. I think your dataset format is incorrect. No data is loaded.

**Comment by alaa-shubbak** [comment]
thank you , i am still wondering . is my way of using  (browse_dataset.py ) correct ? 
I put after it the script that contains the configuration of my dataset. (as config.py) 
my config.py script contains 


# Modify dataset related settings
dataset_type = 'CocoDataset'  # Dataset type, this will be used to define the dataset
data_root = 'image0/'  # Root path of data
img_norm_cfg = dict(  # Image normalization config to normalize the input images
    mean=[123.675, 116.28, 103.53],  # Mean values used to pre-training the pre-trained backbone models
    std=[58.395, 57.12, 57.375],  # Standard variance used to pre-training the pre-trained backbone models
    to_rgb=True
)  # The channel orders of image used to pre-training the pre-trained backbone models
train_pipeline = [  # Training pipeline
    dict(type='LoadImageFromFile'),  # First pipeline to load images from file path
    dict(
        type='LoadAnnotations',  # Second pipeline to load annotations for current image
        with_bbox=True,  # Whether to use bounding box, True for detection
        with_mask=True,  # Whether to use instance mask, True for instance segmentation
        poly2mask=False),  # Whether to convert the polygon mask to instance mask, set False for acceleration and to save memory
    dict(
        type='Resize',  # Augmentation pipeline that resize the images and their annotations
        img_scale=(1333, 800),  # The largest scale of image
        keep_ratio=True
    ),  # whether to keep the ratio between height and width.
    dict(
        type='RandomFlip',  # Augmentation pipeline that flip the images and their annotations
        flip_ratio=0.5),  # The ratio or probability to flip
    dict(
        type='Normalize',  # Augmentation pipeline that normalize the input images
        mean=[123.675, 116.28, 103.53],  # These keys are the same of img_norm_cfg since the
        std=[58.395, 57.12, 57.375],  # keys of img_norm_cfg are used here as arguments
        to_rgb=True),
    dict(
        type='Pad',  # Padding config
        size_divisor=32),  # The number the padded images should be divisible
    dict(type='DefaultFormatBundle'),  # Default format bundle to gather data in the pipeline
    dict(
        type='Collect',  # Pipeline that decides which keys in the data should be passed to the detector
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),  # First pipeline to load images from file path
    dict(
        type='MultiScaleFlipAug',  # An encapsulation that encapsulates the testing augmentations
        img_scale=(1333, 800),  # Decides the largest scale for testing, used for the Resize pipeline
        flip=False,  # Whether to flip images during testing
        transforms=[
            dict(type='Resize',  # Use resize augmentation
                 keep_ratio=True),  # Whether to keep the ratio between height and width, the img_scale set here will be suppressed by the img_scale set above.
            dict(type='RandomFlip'),  # Thought RandomFlip is added in pipeline, it is not used because flip=False
            dict(
                type='Normalize',  # Normalization config, the values are from img_norm_cfg
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(
                type='Pad',  # Padding config to pad images divisable by 32.
                size_divisor=32),
            dict(
                type='ImageToTensor',  # convert image to tensor
                keys=['img']),
            dict(
                type='Collect',  # Collect pipeline that collect necessary keys for testing.
                keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,  # Batch size of a single GPU
    workers_per_gpu=2,  # Worker to pre-fetch data for each single GPU
    train=dict(  # Train dataset config
        type='CocoDataset',  # Type of dataset, refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L19 for details.
        ann_file='image0/train/train_coco.json',  # Path of annotation file
        img_prefix='image0/train/',  # Prefix of image path
        pipeline=[  # pipeline, this is passed by the train_pipeline created before.
            dict(type='LoadImageFromFile'),
            dict(
                type='LoadAnnotations',
                with_bbox=True,
                with_mask=True,
                poly2mask=False),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
        ]),
    val=dict(  # Validation dataset config
        type='CocoDataset',
        ann_file='image0/val/val_coco_klein.json',
        img_prefix='image0/val/',
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(  # Test dataset config, modify the ann_file for test-dev/test submission
        type='CocoDataset',
        ann_file='image0/val/val_coco_klein.json',
        img_prefix='image0/val/',
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        samples_per_gpu=2  # Batch size of a single GPU used in testing
        ))

i change the path of the data in this script , 
was it correct?

**Comment by Jadynjin** [comment]
I have met the same promble,finally I figure out it is caused by the dataset config in the configs. The dataset_type should be set as 'mmdet.CocoDatasets'

**Comment by alaa-shubbak** [comment]
I changed the dataset_type from 'CocoDataset' to 'mmdet.CocoDatasets' in my config file, unfortunately it dose not work. 

here is my dataset config: 

![my config new](https://user-images.githubusercontent.com/10245810/123258961-446c7780-d4f4-11eb-8a13-0ca3dc713869.JPG)


it gives me this error;
KeyError: 'mmdet.CocoDatasets is not in the dataset registry'

could you please share with me your configuration ?

**Comment by alaa-shubbak** [comment]
> I have met the same problem,finally I figure out it is caused by the dataset config in the configs. The dataset_type should be set as 'mmdet.CocoDatasets'

i think you are right , although i still have an error message pop out. here it is 

![error massege](https://user-images.githubusercontent.com/10245810/123336647-71e21100-d546-11eb-9f57-775e2804f37b.JPG)

it seems that something in python is missing, I did the downloading and matching between versions (torch, cuda and mmcv) many times , and sure that the match is correct. as the testing of any existing model is working correctly.

**Comment by alaa-shubbak** [comment]
> I changed the dataset_type from 'CocoDataset' to 'mmdet.CocoDatasets' in my config file, unfortunately it dose not work.
> 
> here is my dataset config:
> 
> ![my config new](https://user-images.githubusercontent.com/10245810/123258961-446c7780-d4f4-11eb-8a13-0ca3dc713869.JPG)
> 
> it gives me this error;
> KeyError: 'mmdet.CocoDatasets is not in the dataset registry'
> 
> could you please share with me your configuration ?

again the same error , 

`` KeyError: 'mmdet.CocoDatasets is not in the dataset registry'

how can i add a dataset to the registry? taken into consideration that my dataset is in the coco format.

**Comment by RangiLyu** [comment]
The dataset_type should be your dataset class name. Are you creating a new dataset class? If not, there is no need to change the dataset_type. I still think the problem is about the JSON file.

**Comment by alaa-shubbak** [comment]
> The dataset_type should be your dataset class name. Are you creating a new dataset class? If not, there is no need to change the dataset_type. I still think the problem is about the JSON file.

you are right , I did not create a new dataset, so i should keep working with coco dataset, without changing. 
my problem was the path of my data, i fixed now exactly as what they wrote in the coco dataset type. 
then i run the test code bellow , 

```
python tools/test.py \
    configs/faster_rcnn/faster_rcnn_r50_fpn_1x.py \
    checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    --show-dir faster_rcnn_r50_fpn_1x_results
```
this code in the doc : https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md


it is working correctly with my test annotation , it reads them  and i got a quit good results, which means my json is correct. as i think. 

when trying to run the training , i noticed that the cuda is not available , i check the installation again and find on that error : 

![couda problem_ne](https://user-images.githubusercontent.com/10245810/123435423-dac09c00-d5cd-11eb-9955-64e1f2e4a03e.JPG)

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.2'

this means that my problem in cuda installation ... 

now i don't know where should i put this instruction.  
`export CUDA_HOME='/usr/local/cuda-10.2'`  , and export FORCE_CUDA="1" which are  mentioned in another issue as a solution for this problem. 

any ideas? 
thank you so much

**Comment by alaa-shubbak** [comment]
the system is not working at all with me . can any one tell me the requirement that i should have in my ubuntu Linux system , so i can run this module. I  can not understand why nothing working well.. even i read all other issues that are similar to mine and follow there suggestions. I have cuda 10.2 in my toolkit , but cuda 11.0 when running nvidia-smi. 

i download pytorch 1.7 for toolkit cuda 10.2 , and have a version of mmcv =1.3.7 

the error still give me message of 

`ValueError: need at least one array to concatenate `

i can not continue with such things , no clue to solve it..
when download mmcv ,sometimes give me this: 

![mmcv wrong in install](https://user-images.githubusercontent.com/10245810/123553406-45fba100-d77b-11eb-8107-d5392e5863c8.JPG)

**Comment by alaa-shubbak** [comment]
Thank you all , I figure out my problem and solved it finally , one was related to the dataset , the other one is related to the config  file.

**Comment by willhunger** [comment]
@alaa-shubbak 
Hey, Could you share your solution to this problem ?
I caught the same problem as yous.

**Comment by alaa-shubbak** [comment]
> @alaa-shubbak
> Hey, Could you share your solution to this problem ?
> I caught the same problem as yous.

yes , sure with my pleasure. 

as you did the download of mmdetection correctly as mentioned in the main page, only you need to be sure that you have a correct from of dataset, and you have correct config file. 

i used coco dataset format, that means i made my annotation of my dataset to be fit with coco format. 
the main problems i faced that segmentation polygon data should be written inside [[ ]] not  only single []. 

for the configuration ,
1.   be sure that your configuration file is as same as the one in the configs folder here in this repository. cope it from the configs folder is the best way, and change the name to be fit with your work 
2. then  change the dictionary of the place of your dataset and the annotation , you can do this in your config file or in the file name (coco_detection.py) on the folder base in configs folder (configs/_base_/datasets/coco_detection.py)
3. finally , change the number of class that you want to detect . it is easy to done through your new config file ,but you should be sure that you change it in all head of your backbone model, for example for faster rcnn you change it once , while for mask rcnn you need to change it twice. 
4. you also need to change the name of classes to be fit with this new number of classes in the (coco_detection.py) file. 


i hope this will help you. good luck

**Comment by willhunger** [comment]
> > @alaa-shubbak
> > Hey, Could you share your solution to this problem ?
> > I caught the same problem as yous.
> 
> yes , sure with my pleasure.
> 
> as you did the download of mmdetection correctly as mentioned in the main page, only you need to be sure that you have a correct from of dataset, and you have correct config file.
> 
> i used coco dataset format, that means i made my annotation of my dataset to be fit with coco format.
> the main problems i faced that segmentation polygon data should be written inside [[ ]] not only single [].
> 
> for the configuration ,
> 
> 1. be sure that your configuration file is as same as the one in the configs folder here in this repository. cope it from the configs folder is the best way, and change the name to be fit with your work
> 2. then  change the dictionary of the place of your dataset and the annotation , you can do this in your config file or in the file name (coco_detection.py) on the folder base in configs folder (configs/_base_/datasets/coco_detection.py)
> 3. finally , change the number of class that you want to detect . it is easy to done through your new config file ,but you should be sure that you change it in all head of your backbone model, for example for faster rcnn you change it once , while for mask rcnn you need to change it twice.
> 4. you also need to change the name of classes to be fit with this new number of classes in the (coco_detection.py) file.
> 
> i hope this will help you. good luck

Thank you very much.
I checked the coco dataset format and retried agian according to your detailed steps, but I failed again.
I used the coco api to load dataset and found my annotation works well.  I created the coco annotation by this [helper functions](https://github.com/waspinator/pycococreator). 
Would you mind sharing your way to annotate your dataset?

I really appreciate your detailed reply.
