### ISSUE TITLE
python3: can't open file 'setup_linux.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mathshangw** [open-mmlab/mmdetection#5378]
there is no folder ops in mmdetection when i setup and found this error 
`Building roi align op...
compile.sh: 6: cd: can't cd to mmdet/ops/roi_align
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building roi pool op...
compile.sh: 13: cd: can't cd to ../roi_pool
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building roi align rotated op...
compile.sh: 20: cd: can't cd to ../roi_align_rotated
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building riroi align op...
compile.sh: 27: cd: can't cd to ../riroi_align
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building ps roi align rotated op...
compile.sh: 34: cd: can't cd to ../psroi_align_rotated
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building nms op...
compile.sh: 41: cd: can't cd to ../nms
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building dcn...
compile.sh: 48: cd: can't cd to ../dcn
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building sigmoid focal loss op...
compile.sh: 55: cd: can't cd to ../sigmoid_focal_loss
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building masked conv op...
compile.sh: 62: cd: can't cd to ../masked_conv
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building poly_nms op...
compile.sh: 69: cd: can't cd to ../poly_nms
  File "setup.py", line 111
    zip_safe=False)import os
                        ^
SyntaxError: invalid syntax
Building cpu_nms...
compile.sh: 76: cd: can't cd to ../../core/bbox
python3: can't open file 'setup_linux.py': [Errno 2] No such file or directory`

**Comment by RangiLyu** [comment]
What's the version of mmdet you using? Now, these ops have moved to mmcv.
