### ISSUE TITLE
Running test/val with a batch size larger than one

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#5379]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.

This will speed up eval times dramatically, I think its a really necessary feature to have and easy to implement.

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by RangiLyu** [comment]
You can set `samples_per_gpu` larger than 1 in config.

**Comment by pcicales** [comment]
Hello @RangiLyu , during test I cannot set batch size to be greater than one.

**Comment by RangiLyu** [comment]
https://github.com/open-mmlab/mmdetection/blob/2028b0c189d676ce0c7ad31f24f8a68107220855/mmdet/apis/train.py#L135
https://github.com/open-mmlab/mmdetection/blob/2028b0c189d676ce0c7ad31f24f8a68107220855/tools/test.py#L147

You can set samples_per_gpu in config->data->test->samples_per_gpu.
