### ISSUE TITLE
how can I use htc train only object detection? and how to modify it?

### ISSUE THREAD

**Issue by moyans** [open-mmlab/mmdetection#538]
up!

**Comment by hellock** [comment]
Please stop posting meaningless comments like "up" in issues.

For your question, we have already provided a config file without semantic segmentation, which requires the same annotation as Mask R-CNN.

**Comment by moyans** [comment]
Get it, thank you。

**Comment by naveenggmu** [comment]
@hellock Can you please tell on how to train models like retinaNet (or whatever model) without passing masks?
