### ISSUE TITLE
[Nvidia Jetson] Different NMS in ONNX and MMCV plugins

### ISSUE THREAD

**Issue by Dorozhko-Anton** [open-mmlab/mmdetection#5383]
My goal is to use YoloV3 in TensorRT on Nvidia Jetson 

I use YoloV3 https://github.com/open-mmlab/mmdetection/blob/master/configs/yolo/yolov3_d53_mstrain-608_273e_coco.py

```bash
python tools/deployment/pytorch2onnx.py \
    configs/yolo/yolov3_d53_mstrain-608_273e_coco.py \
    checkpoints/yolo/yolov3_d53_mstrain-608_273e_coco.pth \
    --output-file checkpoints/yolo/yolov3.onnx \
    --input-img demo/demo.jpg \
    --test-img tests/data/color.jpg \
    --shape 608 608 \
    --mean 0 0 0 \
    --std 255 255 255 \
    --opset-version 11 \
    --show \
    --verify \
    --dynamic-export \
    --cfg-options \
      model.test_cfg.deploy_nms_pre=-1 \
```

I compile mmcv-full with trt plugins and use trtexec to generate an engine. 

```bash
trtexec --onnx=yolov3.onnx --saveEngine=yolov3.trt --verbose --plugins=/home/nvidia/mmdetection/mmcv/mmcv/_ext_trt.cpython-36m-aarch64-linux-gnu.so
```

And I get the following error
```
[06/16/2021-17:02:39] [I] [TRT] builtin_op_importers.cpp:3659: Searching for plugin: NonMaxSuppression, plugin_version: 1, plugin_namespace: 
terminate called after throwing an instance of 'std::out_of_range'
  what():  Attribute not found: center_point_box
```
This parameter is described in https://mmcv.readthedocs.io/en/latest/tensorrt_custom_ops.html#nonmaxsuppression

I check onnx with netron and there is no `center_point_box` parameter 

![image](https://user-images.githubusercontent.com/6677779/122359307-bc1b2f00-cf55-11eb-862b-52d85a8004cc.png)

How I can get `center_point_box` in my onnx? What should I modify to convert my onnx file to trt on nvidia jetson?

**Comment by Dorozhko-Anton** [comment]
Seems like I shoul preprocess my onnx with  `mmcv/mmcv/tensorrt/preprocess.py`

**Comment by Dorozhko-Anton** [comment]
I still have some problemes with generation of trt engine.
When I use mmdetection script onnx2tensorrt with a freshly generated onnx I receive that error

```
UNSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()
```
Which can be easily fixed with onnx-simplify tool. But after simplification I receive an error that a node does not exist. This is a node for one of the parameters of NMS that was simplified to a constant to avoid a previous error.
```
  File "./tools/deployment/onnx2tensorrt.py", line 227, in <module>
    verbose=args.verbose)
  File "./tools/deployment/onnx2tensorrt.py", line 43, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/home/nvidia/mmdetection/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 56, in onnx2trt
    onnx_model = preprocess_onnx(onnx_model)
  File "/home/nvidia/mmdetection/mmcv/mmcv/tensorrt/preprocess.py", line 86, in preprocess_onnx
    mark_nodes_to_remove(node_inputs[2])
  File "/home/nvidia/mmdetection/mmcv/mmcv/tensorrt/preprocess.py", line 43, in mark_nodes_to_remove
    node = node_dict[name]
KeyError: '1359'
```

I use Nvidia jetpack 4.4 with Tensorrt 7.1.3

**Comment by Dorozhko-Anton** [comment]
I commented `mark_to_remove_node` lines
https://github.com/open-mmlab/mmcv/blob/004c00675f912b9ac59ba07655295c86a39e29d1/mmcv/tensorrt/preprocess.py#L86
and now I have another error 
```
[TensorRT] ERROR: (Unnamed Layer* 534) [Constant]: constant weights has count 0 but 1 was expected
[TensorRT] ERROR: (Unnamed Layer* 534) [Constant]: constant weights has count 0 but 1 was expected
[TensorRT] ERROR: (Unnamed Layer* 534) [Constant]: constant weights has count 0 but 1 was expected
Traceback (most recent call last):
  File "./tools/deployment/onnx2tensorrt.py", line 227, in <module>
    verbose=args.verbose)
  File "./tools/deployment/onnx2tensorrt.py", line 43, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/home/nvidia/mmdetection/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (elementwiseHelper): UNSUPPORTED_NODE: Assertion failed: tensor_ptr->getDimensions().nbDims == maxNbDims && "Failed to broadcast tensors elementwise!"

```

**Comment by RunningLeon** [comment]
> I commented `mark_to_remove_node` lines
> https://github.com/open-mmlab/mmcv/blob/004c00675f912b9ac59ba07655295c86a39e29d1/mmcv/tensorrt/preprocess.py#L86
> and now I have another error
> 
> ```
> [TensorRT] ERROR: (Unnamed Layer* 534) [Constant]: constant weights has count 0 but 1 was expected
> [TensorRT] ERROR: (Unnamed Layer* 534) [Constant]: constant weights has count 0 but 1 was expected
> [TensorRT] ERROR: (Unnamed Layer* 534) [Constant]: constant weights has count 0 but 1 was expected
> Traceback (most recent call last):
>   File "./tools/deployment/onnx2tensorrt.py", line 227, in <module>
>     verbose=args.verbose)
>   File "./tools/deployment/onnx2tensorrt.py", line 43, in onnx2tensorrt
>     max_workspace_size=max_workspace_size)
>   File "/home/nvidia/mmdetection/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
>     raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
> RuntimeError: parse onnx failed:
> In node -1 (elementwiseHelper): UNSUPPORTED_NODE: Assertion failed: tensor_ptr->getDimensions().nbDims == maxNbDims && "Failed to broadcast tensors elementwise!"
> ```

@Dorozhko-Anton Hi, just for the record, we only tested with PyTorch==1.6.0, onnx==1.7.0, TensorRT=7.2.1
And is there any reason that you commented that line?

>>> NSUPPORTED_NODE: Assertion failed: inputs.at(1).is_weights()


If the deployed backend platform is TensorRT, please add environment variables before running pytorch2onnx.py:
```
export ONNX_BACKEND=MMCVTensorRT
```
You could refer to the doc for more help.
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md

**Comment by RunningLeon** [comment]
Closed due to age. Feel free to reopen if still have the issue.

**Comment by eliabruni** [comment]
> My goal is to use YoloV3 in TensorRT on Nvidia Jetson
> 
> I use YoloV3 https://github.com/open-mmlab/mmdetection/blob/master/configs/yolo/yolov3_d53_mstrain-608_273e_coco.py
> 
> ```shell
> python tools/deployment/pytorch2onnx.py \
>     configs/yolo/yolov3_d53_mstrain-608_273e_coco.py \
>     checkpoints/yolo/yolov3_d53_mstrain-608_273e_coco.pth \
>     --output-file checkpoints/yolo/yolov3.onnx \
>     --input-img demo/demo.jpg \
>     --test-img tests/data/color.jpg \
>     --shape 608 608 \
>     --mean 0 0 0 \
>     --std 255 255 255 \
>     --opset-version 11 \
>     --show \
>     --verify \
>     --dynamic-export \
>     --cfg-options \
>       model.test_cfg.deploy_nms_pre=-1 \
> ```
> 
> I compile mmcv-full with trt plugins and use trtexec to generate an engine.

Hello @Dorozhko-Anton , how did you manage to compile mmcv-full on Jetson? How did you set `TENSORRT_DIR`, following up [here](https://mmcv.readthedocs.io/en/latest/deployment/tensorrt_plugin.html#how-to-build-tensorrt-plugins-in-mmcv)?

Cheers!

> 
> ```shell
> trtexec --onnx=yolov3.onnx --saveEngine=yolov3.trt --verbose --plugins=/home/nvidia/mmdetection/mmcv/mmcv/_ext_trt.cpython-36m-aarch64-linux-gnu.so
> ```
> 
> And I get the following error
> 
> ```
> [06/16/2021-17:02:39] [I] [TRT] builtin_op_importers.cpp:3659: Searching for plugin: NonMaxSuppression, plugin_version: 1, plugin_namespace: 
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  Attribute not found: center_point_box
> ```
> 
> This parameter is described in https://mmcv.readthedocs.io/en/latest/tensorrt_custom_ops.html#nonmaxsuppression
> 
> I check onnx with netron and there is no `center_point_box` parameter
> 
> ![image](https://user-images.githubusercontent.com/6677779/122359307-bc1b2f00-cf55-11eb-862b-52d85a8004cc.png)
> 
> How I can get `center_point_box` in my onnx? What should I modify to convert my onnx file to trt on nvidia jetson?
