### ISSUE TITLE
Bbox contains negative values

### ISSUE THREAD

**Issue by phungo1506** [open-mmlab/mmdetection#5385]
Hi, if in my annotation set there are boxes with negative coordinates, will it affect the training and testing process or does it default to understand these negative numbers as 0, thank you.
![json](https://user-images.githubusercontent.com/67255026/122370183-11246880-cf89-11eb-9aa8-92096c45bd7e.png)

**Comment by RangiLyu** [comment]
You can set `clip_object_border=True` in "Resize" pipeline to avoid this problem.
