### ISSUE TITLE
Why do test sets have ann files?

### ISSUE THREAD

**Issue by abing222** [open-mmlab/mmdetection#539]
test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))

When I set ann_file = None, the program also reads ann_file, And then report wrong.Why do test sets have ann files?

**Comment by thangvubk** [comment]
Testset doesnt have labels. You can use ``image_info_test2017.json`` instead.

**Comment by abing222** [comment]
Thank you, in the instances_info_test2017.json, I only set 'images',such as:
 {
    "images": [
        {
            "height": 2000,
            "width": 2666,
            "id": 1,
            "file_name": "B632B25A.jpg"
        },
        {
            "height": 2000,
            "width": 2666,
            "id": 2,
            "file_name": "16D3DBEB.jpg"
        },
        {
            "height": 2000,
            "width": 2666,
            "id": 3,
            "file_name": "ACA80058.jpg"
        },
        {
            "height": 2000,
            "width": 2666,
            "id": 4,
            "file_name": "CDA0B1AD.jpg"
        },
        {
            "height": 2000,
            "width": 2666,
            "id": 5,
            "file_name": "08B8C2A8.jpg"
        }]
}

but report wrong:
Traceback (most recent call last):
  File "tools/test.py", line 128, in <module>
    main()
  File "tools/test.py", line 75, in main
    dataset = obj_from_dict(cfg.data.test, datasets, dict(test_mode=True))
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmcv/runner/utils.py", line 77, in obj_from_dict
    return obj_type(**args)
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+a3c8ddf-py3.6.egg/mmdet/datasets/custom.py", line 58, in __init__
    self.img_infos = self.load_annotations(ann_file)
  File "/home/abing/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+a3c8ddf-py3.6.egg/mmdet/datasets/coco.py", line 26, in load_annotations
    self.cat_ids = self.coco.getCatIds()
  File "/home/abing/anaconda3/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 170, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'

**Comment by abing222** [comment]
I know,I didn't pay attention to the test set format of the coco dataset. Thank you.

**Comment by thangvubk** [comment]
Are you using ``image_info_test2017.json`` from coco2017 dataset. Your filename and image filename (08B8C2A8.jpg) seem different.

**Comment by abing222** [comment]
can you show me your image_info_test2017.json format. Thank you very much
