### ISSUE TITLE
how to get  class_id, bbox_score ?

### ISSUE THREAD

**Issue by mathshangw** [open-mmlab/mmdetection#5395]
i need to get 
`x1, y1, x2, y2, class_id, bbox_score`
and my result as this form with 80 array for each image 
`[array([[3.43202576e+02, 2.43713760e+01, 4.96343414e+02, 3.32774170e+02, 8.81948233e-01],`
             ` [4.71771484e+02, 1.72076767e+02, 4.93474548e+02, 2.18293701e+02,5.77966988e-01],`
           `  [4.71194794e+02, 1.73165421e+02, 5.15258850e+02, 2.17751862e+02, 4.02466476e-01], ....`

should i edit in `aips/test.py`  or `config` file for the model ?

**Comment by jevenail** [comment]
I met the same problem.
By use :
     result = inference_detector(model, img)
I got the result,but it seemly only included boxes and score.
How to get the class labels?

**Comment by lihwa123** [comment]
I met the same problem.

**Comment by lihwa123** [comment]
how to save labels to checkpoint? I met this problem
UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '

**Comment by AronLin** [comment]
The format of the results:

    [
        { img_id_1:   # the id of the first image
            [   array: (n1, 5),  # the bounding boxes and scores of the first class
                array: (n2, 5),  # the bounding boxes and scores of the second class
                ...
                array: (nk, 5)  # the bounding boxes and scores of the last class, in coco dataset, k is 80
            ]
        },
        ...
        { img_id_m:  # the id of the mth image
            [ array: (n1, 5),
               ...
            ]
        },
    ]

In the results of an image, the class_id of the ith array is i.

if you want to get only one array (100, 6) for an image with the below format:

    x1, y1, x2, y2, class_id, bbox_score

You can modify the test function in api/test.py like:

    with torch.no_grad():
        result = model(return_loss=False, rescale=True, **data)
        # encode mask results
        if isinstance(result[0], tuple):
            result = [(bbox_results, encode_mask_results(mask_results))
                for bbox_results, mask_results in result]
    img_id = int(data['img_metas'][0].data[0][0]['ori_filename'].split('.')[0])
    tmp = []
    for i, arrays in enumerate(result[0]):
        if arrays is None:
            continue
        labels = np.zeros((arrays.shape[0], 1), dtype=arrays.dtype) + I
        new_arrays = [arrays[:, :4], labels, arrays[:, -1:]]
        new_arrays = np.concatenate(new_arrays, axis=1)
        tmp.append(new_arrays)

    new_arrays = np.concatenate(tmp, axis=0)
    result = [{img_id: new_arrays}]
    results.extend(result)

**Comment by jevenail** [comment]
> The format of the results:
> 
> ```
> [
>     { img_id_1:   # the id of the first image
>         [   array: (n1, 5),  # the bounding boxes and scores of the first class
>             array: (n2, 5),  # the bounding boxes and scores of the second class
>             ...
>             array: (nk, 5)  # the bounding boxes and scores of the last class, in coco dataset, k is 80
>         ]
>     },
>     ...
>     { img_id_m:  # the id of the mth image
>         [ array: (n1, 5),
>            ...
>         ]
>     },
> ]
> ```
> 
> In the results of an image, the class_id of the ith array is i.
> 
> if you want to get only one array (100, 6) for an image with the below format:
> 
> ```
> x1, y1, x2, y2, class_id, bbox_score
> ```
> 
> You can modify the test function in api/test.py like:
> 
> ```
> with torch.no_grad():
>     result = model(return_loss=False, rescale=True, **data)
>     # encode mask results
>     if isinstance(result[0], tuple):
>         result = [(bbox_results, encode_mask_results(mask_results))
>             for bbox_results, mask_results in result]
> img_id = int(data['img_metas'][0].data[0][0]['ori_filename'].split('.')[0])
> tmp = []
> for i, arrays in enumerate(result[0]):
>     if arrays is None:
>         continue
>     labels = np.zeros((arrays.shape[0], 1), dtype=arrays.dtype) + I
>     new_arrays = [arrays[:, :4], labels, arrays[:, -1:]]
>     new_arrays = np.concatenate(new_arrays, axis=1)
>     tmp.append(new_arrays)
> 
> new_arrays = np.concatenate(tmp, axis=0)
> result = [{img_id: new_arrays}]
> results.extend(result)
> ```

I have tried your method.
However,there is no change for the result...

**Comment by AronLin** [comment]
> I have tried your method.
> However, there is no change in the result...
Did you modify the codes in the right position?
You changed the code, but the results did not change. That implies the program did not run the changed codes.

**Comment by jevenail** [comment]
> > I have tried your method.
> > However, there is no change in the result...
> 
> Did you modify the codes in the right position?
> You changed the code, but the results did not change. That implies the program did not run the changed codes.

I change your code in the function 'single_gpu_test' from  mmdet/apis/test.py 
And it's the code:

def single_gpu_test(model,
                    data_loader,
                    show=False,
                    out_dir=None,
                    show_score_thr=0.3):
    model.eval()
    results = []
    dataset = data_loader.dataset
    prog_bar = mmcv.ProgressBar(len(dataset))
    for i, data in enumerate(data_loader):
        with torch.no_grad():
            result = model(return_loss=False, rescale=True, **data)

        batch_size = len(result)
        if show or out_dir:
            if batch_size == 1 and isinstance(data['img'][0], torch.Tensor):
                img_tensor = data['img'][0]
            else:
                img_tensor = data['img'][0].data[0]
            img_metas = data['img_metas'][0].data[0]
            imgs = tensor2imgs(img_tensor, **img_metas[0]['img_norm_cfg'])
            assert len(imgs) == len(img_metas)

            for i, (img, img_meta) in enumerate(zip(imgs, img_metas)):
                h, w, _ = img_meta['img_shape']
                img_show = img[:h, :w, :]

                ori_h, ori_w = img_meta['ori_shape'][:-1]
                img_show = mmcv.imresize(img_show, (ori_w, ori_h))

                if out_dir:
                    out_file = osp.join(out_dir, img_meta['ori_filename'])
                else:
                    out_file = None

                model.module.show_result(
                    img_show,
                    result[i],
                    show=show,
                    out_file=out_file,
                    score_thr=show_score_thr)

        # encode mask results
        if isinstance(result[0], tuple):
            result = [(bbox_results, encode_mask_results(mask_results))
                      for bbox_results, mask_results in result]
        img_id = int(data['img_metas'][0].data[0][0]['ori_filename'].split('.')[0])
        tmp = []
        for i, arrays in enumerate(result[0]):
            if arrays is None:
                continue
            labels = np.zeros((arrays.shape[0], 1), dtype=arrays.dtype) + I
            new_arrays = [arrays[:, :4], labels, arrays[:, -1:]]
            new_arrays = np.concatenate(new_arrays, axis=1)
            tmp.append(new_arrays)

        new_arrays = np.concatenate(tmp, axis=0)
        result = [{img_id: new_arrays}]
        results.extend(result)

        for _ in range(batch_size):
            prog_bar.update()
    return results

**Comment by AronLin** [comment]
What command do you run? If you run dist_test.sh, multi_gpu_test will be used to inference.

**Comment by jevenail** [comment]
> What command do you run? If you run dist_test.sh, multi_gpu_test will be used to inference.
This is my test code.


from mmdet.apis import init_detector, inference_detector
import mmcv
import numpy as np
import pandas as pd
import os

config_file = '../configs/mydata_faster_rcnn_config.py'
checkpoint_file = '../work_dirs/mydata_faster_rcnn_config/epoch_3.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')


img_dir = '../../test_data/'
out_dir = 'results/'
csv_file = pd.read_csv('../../test_data/3_testa_user.csv', header=None)
imgs = []
for im in csv_file[0]:
    if len(im) < 20: continue
    imgs.append(im)
print(imgs[0])
results = []

count = 0
for img in imgs:
    img=img_dir+img
    count += 1
    print('model is processing the {}/{} images.'.format(count, len(imgs)))
    result = inference_detector(model, img)
    print(result)
    results.append(result)
# transform to json

**Comment by SamMohel** [comment]
i tried to use the code for maskrcnn but got 

  `labels = np.zeros((arrays.shape[0], 1), dtype=arrays.dtype) + i`
`AttributeError: 'list' object has no attribute 'shape'`
