### ISSUE TITLE
A small bug about  plot_curve fucntion in tools/analysis_tools/analyze_logs.py

### ISSUE THREAD

**Issue by Y-M-Y** [open-mmlab/mmdetection#5396]
_Thank you very much_ for bringing great help to my research. I encountered a small problem in the process of using it, and I also proposed my own solution for your reference.

**Describe the bug**
When using the `plot_curve` function `tools/analysis_tools/analyze_logs.py` to plot the curve of loss-iteration, loss values with a large number of iterations will be misplaced in front of the loss with a small number of iterations. Therefore, some details of the loss-iteration curve are disorderly.
![Figure_1](https://user-images.githubusercontent.com/44496446/122661946-ef61f600-d1c1-11eb-938a-d7e6b10b3ef3.png)

There could be some problems with the setting of abscissa(iters). I checked the `plot_curve` fucntion in `tools/analysis_tools/analyze_logs.py` and found that `num_iters_per_epoch` could not return the right value. It returns the iter of `mode:val` instead of the last/biggest number of `mode:train` in log.json file.

**Reproduction**
Using `python tools/analysis_tools/analyze_logs.py plot_curve log.json --keys loss_cls --legend loss_cls` to plot curve.
Here's my log and log.json file.
[logandlogjason20210619_165226.zip](https://github.com/open-mmlab/mmdetection/files/6681733/logandlogjason20210619_165226.zip)

**Environment**
mmdet 2.13

**Bug fix**
I tried a method that can solve my problem, but it may not work for all related problems.

ln `line 68` of `tools/analysis_tools/analyze_logs.py`, I changed `num_iters_per_epoch = log_dict[epochs[0]]['iter'][-1]` to `num_iters_per_epoch = log_dict[epochs[0]]['iter'][-2]`. After the change, `num_iters_per_epoch` could return the last value of `mode:train` instead of the value of `mode:val`.
![Figure_2](https://user-images.githubusercontent.com/44496446/122661955-fee13f00-d1c1-11eb-988c-eaa5e49903cf.png)

The solution only works when there is only one value of `mode:val`.

Thanks again.

**PS**
I am totally a freshman on this. If there is any problem, please don't hesitate to correct me.

**Comment by ZwwWayne** [comment]
Thanks for your report, would you like to create a PR to fix that?

**Comment by Y-M-Y** [comment]
> Thanks for your report, would you like to create a PR to fix that?
I have already done that, thanks for your hint. It's my first time being a contributor, hope it works well.

**Comment by Y-M-Y** [comment]
> Thanks for your report, would you like to create a PR to fix 

I have already done that, thanks for your hint. It's my first time to create a PR and I do not have the ability to do it perfectly. Hope it works well, thank you for your tolerance.

**Comment by liuyuan000** [comment]
if log_dict[epochs[0]]['mode'][-1]=='val':
                    num_iters_per_epoch = log_dict[epochs[0]]['iter'][-2]
                else:
                    num_iters_per_epoch = log_dict[epochs[0]]['iter'][-1]

**Comment by ZwwWayne** [comment]
Solved in https://github.com/open-mmlab/mmdetection/pull/5479
