### ISSUE TITLE
怎么加入负样本图片

### ISSUE THREAD

**Issue by nmxnql** [open-mmlab/mmdetection#540]
怎么加入没有目标的背景图片以减少误检？是自己写入proposal文件吗

**Comment by vintagew** [comment]
请问你解决了这个问题吗？

**Comment by wl654655902** [comment]
> 怎么加入没有目标的背景图片以减少误检？是自己写入proposal文件吗

我在配置文件中data的train和val中设置filter_empty_gt=False，就可以加入没目标的背景图片训练了

**Comment by corkiyao** [comment]
> > 怎么加入没有目标的背景图片以减少误检？是自己写入proposal文件吗
> 
> 我在配置文件中data的train和val中设置filter_empty_gt=False，就可以加入没目标的背景图片训练了

效果请问怎么样呢？我也想尝试加入无目标的负样本
