### ISSUE TITLE
data aug is too slow. Why don't use albumentations?

### ISSUE THREAD

**Issue by ailias** [open-mmlab/mmdetection#5405]
When I trained a small detection model(50m flops while input size is 256 * 256),  the utilization of gpus ranging from 0 to 100%, while all of cpu threads are almost 100%, the wasted time of data augmentation is too much. So why don't we use a public favorite library such as albumentations?

**Comment by RangiLyu** [comment]
You can set albumentations augmentation in your config. Refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py

**Comment by leemengwei** [comment]
For I know
poly2mask = True     <-------- convert your annotation from polygon form to Bitmap mask form when running.
or else raised: albumentation only suppport bitmap mask
