### ISSUE TITLE
Class_num changing issue

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [open-mmlab/mmdetection#5411]
Excuse me, I meet a problem that when I use my own dataset (in COCO form) and rewrite the number of classes both in Shard2FCBBox layer and the class info in config file, such Error will occur:
   **_TypeError: tuple indices must be integers or slices, not str**

I change the class info according to the tutorial: Adding the class info  in file 'configs/_base_/dataset/coco_detection.py' by typing  
_' class = ('a', 'b', 'c', ...) '_  
and then I add such info into data dict, nothing else changed.

Also I tried to directly change the class info of COCO dataset in 'mmdet/dataset/coco.py', but that didn't work either.

**Comment by BIGWangYuDong** [comment]
Pleas refer to [Document](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_dataset.md)
