### ISSUE TITLE
SOLOV2 Reimplementation: Too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by cyrilzakka** [open-mmlab/mmdetection#5412]
**Checklist**

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The issue has not been fixed in the latest version.

**Describe the issue**

I was able to successfully port SOLOv2 from the original [repo](https://github.com/WXinlong/SOLO)  which was implemented with `mmdetection v1.0.0`. The model trains well and the loss decreases as expected. Unfortunately during the evaluation script after the first epoch, I get the following error in `mmdet/apis/test.py `:
```
 # encode mask results
        if isinstance(result[0], tuple):
            result = [(bbox_results, encode_mask_results(mask_results))
                      for bbox_results, mask_results in result]
```

```
 File "/content/mmdetection/mmdet/apis/test.py", line 61, in <listcomp>
    for bbox_results, mask_results in result]
ValueError: too many values to unpack (expected 2)
```
I suspect the problem might be caused by the fact that the evaluation script is expecting a `BitmapMask ` and I'm giving it an `ndarray`. Any ideas? Should my network head return a `BitmapMask` for the segmentation masks instead of an array? I could modify the eval script to fit my needs but I'm trying to keep things as clean as possible to submit a PR for SOLOV2 later on.

**Comment by hhaAndroid** [comment]
There is a big gap between v1 code and v2. If you want to use v2 of SOLOv2, please refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md

**Comment by cyrilzakka** [comment]
Thanks for the documentation, but there doesn't seem to be anything in there addressing my specific issue. I guess I'll just modify the evaluation script as needed and post a link here.

**Comment by iAhmedMaher** [comment]
@cyrilzakka any luck?
