### ISSUE TITLE
Dilated Residual Networks

### ISSUE THREAD

**Issue by htyj123** [open-mmlab/mmdetection#5413]
how to apply Dilated Residual Networks as the backbone in the project, I use DRN, but the perofrmance is not well, the loss are always show 'NAN', I use the drn_c_58 and 'out_indices=(2,3,4,5,6,7)'
could you help me? Thank you. 
And I want to know how to remove the "neck" part in the mmdetection

**Comment by htyj123** [comment]
I use the drn_c_58 and 'out_indices=(2,3,4,5,6,7)'

**Comment by hhaAndroid** [comment]
you can setting neck=None.
