### ISSUE TITLE
https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html#modify-classes-of-existing-dataset

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5414]
https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html#modify-classes-of-existing-dataset

_Originally posted by @hellock in https://github.com/open-mmlab/mmdetection/issues/3305#issuecomment-660585311_

this document is not lunched, is there any document similar to it that i can read it?

**Comment by jshilong** [comment]
https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html#modify-dataset-classes
