### ISSUE TITLE
Can't download pretrained model

### ISSUE THREAD

**Issue by MarcusNerva** [open-mmlab/mmdetection#5416]
![image](https://user-images.githubusercontent.com/37070207/122923340-33f2ba80-d397-11eb-8327-b31ebf3201d2.png)
I can't download [faster_rcnn_x101_32x4d_fpn_mstrain_3x_coco](https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_32x4d_fpn_mstrain_3x_coco/faster_rcnn_x101_32x4d_fpn_mstrain_3x_coco_20210524_124151-e8595dde.pth)

Can anyone help me?

**Comment by hhaAndroid** [comment]
Thank you for your feedback, we will deal with it as soon as possible.
