### ISSUE TITLE
Multiple mmdetection project compatiable?

### ISSUE THREAD

**Issue by huangh12** [open-mmlab/mmdetection#5422]
Hello guys, I have encountered a problem and look for some help here.

In my python env, I have two project both based on mmdetection, e.g., project A and project B.  They both depend on the same pytorch&mmcv libs.  However, the two project differs in the mmdet directory. Therefore, If I wanna run project A, I need to execute `pip install -v -e .` to install mmdet for A. But when I want to run project B, I have to execute `pip uninstall mmdet` to uninstall A's mmdet, and reinstall B's.  

This will trouble a lot if there are many project on mmdetection.  Is there any elegant method to cope with this scenario?
Thank you!

**Comment by jshilong** [comment]
You can move the corresponding version of `mmdet` into your projects. The `mmdet` in the current path has priority over the `mmdet` in conda environment.

**Comment by huangh12** [comment]
Thank you.   Exporting the mmdet to PYTHONPATH before running each project solves my prolem.
