### ISSUE TITLE
Adding extra anchors to RetinaNet

### ISSUE THREAD

**Issue by benihime91** [open-mmlab/mmdetection#5430]
I am working on detecting very small objects for which I would like to have some small anchors in `RetianaNet` other that the standard coco anchors. How can I achieve this ? Thanks..

**Comment by RangiLyu** [comment]
There are two ways: 1. manually set `scales` and `base_sizes` or 2. set `octave_base_scale` and `scales_per_octave` in AnchorGenerator. You can refer to the docstring of AnchorGenerator https://mmdetection.readthedocs.io/en/latest/api.html?highlight=AnchorGenerator#mmdet.core.anchor.AnchorGenerator

**Comment by benihime91** [comment]
Thanks

**Comment by mmeendez8** [comment]
We have developed [pyodi](https://github.com/Gradiant/pyodi) a tool that follow mmdetection format and helps to understand anchors, their parameters and to optimize them with respect to your data distribution. You can create a new set of anchors for you RetinaNet model!

![image](https://user-images.githubusercontent.com/15969667/126467442-299f7d57-d5f0-4784-9c43-bbda5ddeab76.png)
