### ISSUE TITLE
I have the same problem with you,have you solved this question?

### ISSUE THREAD

**Issue by oceanleftsea** [open-mmlab/mmdetection#544]
I have the same question with you.Have you solved this problem?

Here is what I set in bashrc
export PATH=/usr/local/cuda-9.0/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda-9.0
alias gcc='gcc -std=c11'
alias g++='g++ -std=c++11'

_Originally posted by @ChessQian in https://github.com/open-mmlab/mmdetection/issues/525#issuecomment-485235644_

**Comment by hellock** [comment]
You should post comments in the original issue instead of opening a new one.

**Comment by oceanleftsea** [comment]
I'm sorry,it's not my intention.And will you tell me about your solution for this problem? 18120356 邮箱18120356@bjtu.edu.cn 签名由 网易邮箱大师 定制 On 04/26/2019 07:45, Kai Chen wrote: You should post comments in the original issue instead of opening a new one. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
