### ISSUE TITLE
How can I use backbone--ResNet50 or another when I train Centernet?

### ISSUE THREAD

**Issue by 15988817140** [open-mmlab/mmdetection#5441]
How can I use backbone--ResNet50 or another when I train Centernet?Is there an official pre-trained model available? I didn't find one.

**Comment by jshilong** [comment]
You can refer to [Tutorial 1: Learn about Configs](https://mmdetection.readthedocs.io/en/latest/tutorials/config.html#tutorial-1-learn-about-configs)
