### ISSUE TITLE
I want to know whether the label information used by mask rcnn is the same as the regular segmentation information

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#5445]
I want to know whether the label information used by mask rcnn is the same as the regular segmentation information. Mask rcnn is based on roi, so I am thinking that its information should be cropped in the proposal area as a GT. I don’t know if my understanding is correct. , Because I just read his paper instead of carefully watching the source code, and I observed that the FCN you implemented does not have a coco segmentation configuration. Is it because it is difficult to have a good effect on the coco data set? The label of coco is not compatible with the design of FCN, and a new design may be needed. I really want to reproduce FCN on the coco data set. I need your help. I may be a novice, so I hope you can give me detailed Comments to facilitate my work, thank you very much

**Comment by AronLin** [comment]
1. What is the meaning of regular segmentation information? Semantic segmentation?
2. For semantic segmentation task, coco is not easy to handle. So general semantic segmentation methods do not experiment on the coco. And mmdet is not a repo to support Semantic segmentation, we only support instance segmentation.
3. FCN has reproduced by mmseg, you can try to support coco dataset on mmseg and it will be easier if you want to follow semantic segmentation task.
