### ISSUE TITLE
how can i show the accuracy of classification after training Cascade Mask R-CNN

### ISSUE THREAD

**Issue by abdoelsayed2016** [open-mmlab/mmdetection#5446]
Hello 
how can I show the accuracy of classification after training the models 
I know how can I show the recall and precision of object detection 
```
!python 'tools/test.py' '/Cascade Mask R-CNN/X-101-64x4d-FPN/cascade_mask_rcnn_x101_64x4d_fpn_1x_coco.py' 'model.pth' --eval bbox
```
but also I want to know the accuracy of classification 
thanks

**Comment by jshilong** [comment]
We do not support this feature
