### ISSUE TITLE
Use Lidar 3D proposals instead of proposal_list

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#5447]
I am trying to use my own lidar 3D proposals instead of the original proposal in two_stage.py file. How can I replace the original proposal_list with my own 3D proposal from lidar. P.S: I already have the .txt file of the lidar 3D proposals.

**Comment by ZwwWayne** [comment]
You may refer to MMDetection3D. Basically, you need to implement a new dataset with corresponding data pipelines to allow that. And you need to modify your head.
