### ISSUE TITLE
> > > Hi, how do I replace Darknet53 in Yolov3 with MobileNetV2?

### ISSUE THREAD

**Issue by GalSang17** [open-mmlab/mmdetection#5450]
> > > Hi, how do I replace Darknet53 in Yolov3 with MobileNetV2?
> > 
> > 
> > IMHO, just changing the config file is OK. It should be working in the `mm-detection`-way. There is nothing special.
> 
> ![image](https://user-images.githubusercontent.com/49866330/123363402-011e1180-d5a5-11eb-816d-3c37c40d97a6.png)
> Is it just like this? The neck section will throw an exception

emmm, there are several points:

For the backbone part, you should check the strides for each `out_indices`. The length of `out_indices` should be **3**, if you do like minimal change of neck or head.

For the neck part, you need to at least make sure that `in_channels` work with the backbone.

BTW, you can open a new issue and we can track the problem there.

_Originally posted by @ElectronicElephant in https://github.com/open-mmlab/mmdetection/issues/3083#issuecomment-868178106_

**Comment by GalSang17** [comment]
Yes, I just want to modify the backbone part minimally, but I don't know how to start

**Comment by ElectronicElephant** [comment]
Hi,

I think the out_indices in backbone should be set to [4, 6, 7]

in_channels in neck should be [64, 160, 320]

Reference: 
https://github.com/open-mmlab/mmdetection/blob/102f37978930e0a8de6cb7e555a198c420816486/mmdet/models/backbones/mobilenet_v2.py#L41

![image](https://user-images.githubusercontent.com/20351686/123373553-2405f100-d5b8-11eb-93b2-009b02784157.png)
![image](https://user-images.githubusercontent.com/20351686/123373573-2a946880-d5b8-11eb-8e90-4a7aab452612.png)

**Comment by GalSang17** [comment]
> Hi,
> 
> I think the out_indices in backbone should be set to [4, 6, 7]
> 
> in_channels in neck should be [64, 160, 320]
> 
> Reference:
> https://github.com/open-mmlab/mmdetection/blob/102f37978930e0a8de6cb7e555a198c420816486/mmdet/models/backbones/mobilenet_v2.py#L41
> 
> ![image](https://user-images.githubusercontent.com/20351686/123373553-2405f100-d5b8-11eb-93b2-009b02784157.png)
> ![image](https://user-images.githubusercontent.com/20351686/123373573-2a946880-d5b8-11eb-8e90-4a7aab452612.png)

I tried the modification method you mentioned, but it doesn't seem to work, like this screenshot
![image](https://user-images.githubusercontent.com/49866330/123377514-cf19a900-d5be-11eb-8063-641f858b65ca.png)
![image](https://user-images.githubusercontent.com/49866330/123378178-f83a3980-d5be-11eb-9aa1-94d324e0401e.png)

Then I tried out_indices=(2,4,6) and the output was consistent with the same size data tested with Darknet53, like this screenshot
![image](https://user-images.githubusercontent.com/49866330/123377275-6b8f7b80-d5be-11eb-8650-5241f69750fa.png)
![image](https://user-images.githubusercontent.com/49866330/123377898-e6f12d00-d5be-11eb-89bd-f53371f49557.png)

**Comment by ElectronicElephant** [comment]
Hi @GalSang17 ,

Sorry that I have made some mistakes. Then, `2,4,6` is Okay for backbone.

You may try `in_channels=[320, 96, 32]` in neck, and make sure the `out_channels` in neck is consistent with the `in_channels` in head. It's more flexible thanks to #5218 compared with the one I originally wrote.

BRW, I think you should reduce the channels in head, because you are using a lightweight model.

**Comment by GalSang17** [comment]
> Hi @GalSang17 ,
> 
> Sorry that I have made some mistakes. Then, `2,4,6` is Okay for backbone.
> 
> You may try `in_channels=[320, 96, 32]` in neck, and make sure the `out_channels` in neck is consistent with the `in_channels` in head. It's more flexible thanks to #5218 compared with the one I originally wrote.
> 
> BRW, I think you should reduce the channels in head, because you are using a lightweight model.

Thanks for your answer, it is now working properly. By the way, does Open-MMLab have pre-training weights for MobileNetV2, like this
![image](https://user-images.githubusercontent.com/49866330/123394518-cf6f6f80-d5d1-11eb-9a7f-d9a6f1bab312.png)

**Comment by ElectronicElephant** [comment]
> > Hi @GalSang17 ,
> > Sorry that I have made some mistakes. Then, `2,4,6` is Okay for backbone.
> > You may try `in_channels=[320, 96, 32]` in neck, and make sure the `out_channels` in neck is consistent with the `in_channels` in head. It's more flexible thanks to #5218 compared with the one I originally wrote.
> > BRW, I think you should reduce the channels in head, because you are using a lightweight model.
> 
> Thanks for your answer, it is now working properly. By the way, does Open-MMLab have pre-training weights for MobileNetV2, like this
> ![image](https://user-images.githubusercontent.com/49866330/123394518-cf6f6f80-d5d1-11eb-9a7f-d9a6f1bab312.png)

Hi, I'm not sure about it. But, since MobileNet is a quite small backbone, it should be Okay to start from scratch~

**Comment by ElectronicElephant** [comment]
@GalSang17  Hi, you can try  https://github.com/open-mmlab/mmcv/blob/db097bd1e97fc446a7551c715970611d2fcc848d/mmcv/model_zoo/open_mmlab.json#L42

**Comment by tikitong** [comment]
> > Hi @GalSang17 ,
> > Sorry that I have made some mistakes. Then, `2,4,6` is Okay for backbone.
> > You may try `in_channels=[320, 96, 32]` in neck, and make sure the `out_channels` in neck is consistent with the `in_channels` in head. It's more flexible thanks to #5218 compared with the one I originally wrote.
> > BRW, I think you should reduce the channels in head, because you are using a lightweight model.
> 
> Thanks for your answer, it is now working properly. By the way, does Open-MMLab have pre-training weights for MobileNetV2, like this
> ![image](https://user-images.githubusercontent.com/49866330/123394518-cf6f6f80-d5d1-11eb-9a7f-d9a6f1bab312.png)

Hi @GalSang17  it's works correctly for you ? Can you tell me which `out_channels` you put in the neck? Thanks a lot.

**Comment by ElectronicElephant** [comment]
> > > Hi @GalSang17 ,
> > > Sorry that I have made some mistakes. Then, `2,4,6` is Okay for backbone.
> > > You may try `in_channels=[320, 96, 32]` in neck, and make sure the `out_channels` in neck is consistent with the `in_channels` in head. It's more flexible thanks to #5218 compared with the one I originally wrote.
> > > BRW, I think you should reduce the channels in head, because you are using a lightweight model.
> > 
> > 
> > Thanks for your answer, it is now working properly. By the way, does Open-MMLab have pre-training weights for MobileNetV2, like this
> > ![image](https://user-images.githubusercontent.com/49866330/123394518-cf6f6f80-d5d1-11eb-9a7f-d9a6f1bab312.png)
> 
> Hi @GalSang17 it's works correctly for you ? Can you tell me which `out_channels` you put in the neck? Thanks a lot.

Since https://github.com/open-mmlab/mmdetection/pull/5218 is merged, you can use any out_channels.(btw, you may want to pull and checkout the latest code) IMHO, `[160, 48, 16]` would be a good value to start.

**Comment by tikitong** [comment]
@ElectronicElephant Thank you very much, I would like to use MobileNetV2/V3_small (I have a small dataset) with YoloV3, it is also necessary to adapt the `in_channels` and `out_channels` of the `bbox_head` true? 

With this configuration I get this error: `RuntimeError: Given groups=1, weight of size [48, 96, 1, 1], expected input[8, 160, 32, 32] to have 96 channels, but got 160 channels instead`
```python
cfg.model = dict(
    type='YOLOV3',
    pretrained='open-mmlab://MobileNetV2',
    backbone=dict(type='MobileNetV2', widen_factor=1.0, out_indices=(2, 4, 6)),
    neck=dict(
        type='YOLOV3Neck',
        num_scales=3,
        in_channels=[320, 96, 32],
        out_channels=[160, 48, 16]),
    bbox_head=dict(
        type='YOLOV3Head',
        num_classes=3,
        in_channels=[160, 48, 16],
        out_channels=[320, 96, 32],
        anchor_generator=dict(
            type='YOLOAnchorGenerator',
            base_sizes=[[(116, 90), (156, 198), (373, 326)],
                        [(30, 61), (62, 45), (59, 119)],
                        [(10, 13), (16, 30), (33, 23)]],
            strides=[32, 16, 8]),
        bbox_coder=dict(type='YOLOBBoxCoder'),
        featmap_strides=[32, 16, 8],
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_conf=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_xy=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=2.0,
            reduction='sum'),
        loss_wh=dict(type='MSELoss', loss_weight=2.0, reduction='sum')),
    train_cfg=dict(
        assigner=dict(
            type='GridAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0)),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        conf_thr=0.005,
        nms=dict(type='nms', iou_threshold=0.45),
        max_per_img=100))
```

**Comment by ElectronicElephant** [comment]
Hi @tikitong , are you using the latest code?

**Comment by tikitong** [comment]
Hi @ElectronicElephant yes I think I use the last one I did a `git pull` a week ago..

**Comment by ElectronicElephant** [comment]
> Hi @ElectronicElephant yes I think I use the last one I did a `git pull` a week ago..

Just wait for a minute. I'll create a pr to add such config.

**Comment by ElectronicElephant** [comment]
Hi @tikitong , you can check #5510

**Comment by tikitong** [comment]
Thank you very much for the example #5510 ! Indeed my case should also work... I don't understand. With the basic DarkNet backbone it works fine. Here is my entire configuration file. Do you notice anything that could cause the error ?
```python
from mmcv import Config
from mmdet.apis import set_random_seed
from pathlib import Path

import os.path as osp
from mmcv import mkdir_or_exist
from mmdet.datasets import build_dataset
from mmdet.models import backbones, build_detector, necks
from mmdet.apis import train_detector

base = 'configs/yolo/yolov3_d53_320_273e_coco.py'
cfg = Config.fromfile(base)
          
cfg.model = dict(
    type='YOLOV3',
    pretrained='open-mmlab://MobileNetV2',
    backbone=dict(type='MobileNetV2', widen_factor=1.0, out_indices=(2, 4, 6)),
    neck=dict(
        type='YOLOV3Neck',
        num_scales=3,
        in_channels=[320, 96, 32],
        out_channels=[160, 48, 16]),
    bbox_head=dict(
        type='YOLOV3Head',
        num_classes=3,
        in_channels=[160, 48, 16],
        out_channels=[320, 96, 32],
        anchor_generator=dict(
            type='YOLOAnchorGenerator',
            base_sizes=[[(116, 90), (156, 198), (373, 326)],
                        [(30, 61), (62, 45), (59, 119)],
                        [(10, 13), (16, 30), (33, 23)]],
            strides=[32, 16, 8]),
        bbox_coder=dict(type='YOLOBBoxCoder'),
        featmap_strides=[32, 16, 8],
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_conf=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_xy=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=2.0,
            reduction='sum'),
        loss_wh=dict(type='MSELoss', loss_weight=2.0, reduction='sum')),
    train_cfg=dict(
        assigner=dict(
            type='GridAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0)),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        conf_thr=0.005,
        nms=dict(type='nms', iou_threshold=0.45),
        max_per_img=100))

cfg.load_from = 'checkpoints/mobilenet_v2.pth'

cfg.dataset_type = 'MyDataset'
cfg.data_root = 'set'
cfg.classes = ('triangle', 'circle', 'square')

cfg.data.train.type = cfg.dataset_type
cfg.data.train.data_root = cfg.data_root
cfg.data.train.ann_file = 'train.txt'
cfg.data.train.img_prefix = 'image'
cfg.data.train.pipeline = cfg.train_pipeline

cfg.data.val.type = cfg.dataset_type
cfg.data.val.data_root = cfg.data_root
cfg.data.val.ann_file = 'val.txt'
cfg.data.val.img_prefix = 'image'

cfg.data.test.type = cfg.dataset_type
cfg.data.test.data_root = cfg.data_root
cfg.data.test.ann_file = 'test.txt'
cfg.data.test.img_prefix = 'image'

cfg.optimizer = dict(type='SGD', lr=6e-4, momentum=0.9, weight_decay=0.0001)

cfg.optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))


cfg.runner = dict(type='EpochBasedRunner', max_epochs=40)
cfg.total_epochs = 40
cfg.evaluation = dict(interval=20, metric=['mAP'])

cfg.log_config = dict(
    interval=172,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])

cfg.checkpoint_config = dict(interval=50)

cfg.work_dir = f'work_dirs/{Path(base).stem}_'

cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)

print(f'Config: {cfg.total_epochs} epochs\n{cfg.pretty_text}')

datasets = [build_dataset(cfg.data.train)]
model = build_detector(cfg.model)
mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```

**Comment by ElectronicElephant** [comment]
Hi @tikitong , can you just double check if your local code contains the modification in  https://github.com/open-mmlab/mmdetection/pull/5218 ? I found nothing unusual. Hmm, wired.

**Comment by tikitong** [comment]
@ElectronicElephant Thanks a lot, that was it ! Both files [mmdet/models/necks/yolo_neck.py](https://github.com/open-mmlab/mmdetection/pull/5218/files/79996c8e9d914290cb0cb2838f9f830ddab6c037#diff-fee0dd45f483d1e3659acff8ee688ffdc94b9af90ca734c3b1eaf954b822ab83) and [tests/test_models/test_necks.py](https://github.com/open-mmlab/mmdetection/pull/5218/files/79996c8e9d914290cb0cb2838f9f830ddab6c037#diff-44fbd79261f587660008eab9b955dc24450bd590caa40c6620b77d4fbcad2754) were not up to date. Despite the `git pull` it's normal ? I report it as a `bug`?  Now it works fine but mAP scores have dropped to 0.00.. with the DarkNet and MobileNetV2 backbone.

**Comment by jshilong** [comment]
> @ElectronicElephant Thanks a lot, that was it ! Both files [mmdet/models/necks/yolo_neck.py](https://github.com/open-mmlab/mmdetection/pull/5218/files/79996c8e9d914290cb0cb2838f9f830ddab6c037#diff-fee0dd45f483d1e3659acff8ee688ffdc94b9af90ca734c3b1eaf954b822ab83) and [tests/test_models/test_necks.py](https://github.com/open-mmlab/mmdetection/pull/5218/files/79996c8e9d914290cb0cb2838f9f830ddab6c037#diff-44fbd79261f587660008eab9b955dc24450bd590caa40c6620b77d4fbcad2754) were not up to date. Despite the `git pull` it's normal ? I report it as a `bug`? Now it works fine but mAP scores have dropped to 0.00.. with the DarkNet and MobileNetV2 backbone.

Any update?

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any problem
