### ISSUE TITLE
INVALID_ARGUMENT: getPluginCreator could not find plugin NonMaxSuppression version 1

### ISSUE THREAD

**Issue by BChunlei** [open-mmlab/mmdetection#5452]
I have successfully converted yolov3 pytorch model to onnx and then tensorrt by the tools：pytorch2onnx.py and onnx2tensorrt.py, but when i use tensorrt do inference, it gives me the errors:

[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin NonMaxSuppression version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (322) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 106, in <module>
    main()
  File "onnx_to_tensorrt.py", line 73, in main
    with get_engine(engine_file_path) as engine, engine.create_execution_context() as context:
AttributeError: __enter__

The onnx_to_tensorrt.py file as below:

def get_engine(engine_file_path=""):

    if os.path.exists(engine_file_path):
        # If a serialized engine exists, use it instead of building an engine.
        print("Reading engine from file {}".format(engine_file_path))
        with open(engine_file_path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
            return runtime.deserialize_cuda_engine(f.read())
    return None`

def main():

    engine_file_path = "yolov3.trt"
    input_image_path = 'images/00076.jpg'
    image = Image.open(input_image_path)
    image = np.transpose(image, [2, 0, 1])
    trt_outputs = []
    with get_engine(engine_file_path) as engine, engine.create_execution_context() as context:
        inputs, outputs, bindings, stream = common.allocate_buffers(engine)
        # Do inference
        print('Running inference on image {}...'.format(input_image_path))
        # Set host input to the image. The common.do_inference function will copy the input to the GPU before executing.
        inputs[0].host = image
        trt_outputs = common.do_inference_v2(context, bindings=bindings, inputs=inputs, outputs=outputs, stream=stream)
        print(trt_outputs)

I'm not sure it is the correct way to use the ‘.trt’ file. Could you give me some suggestions?
Ubuntu-16.04 pytorch 1.6 cuda 10.2 tensorrt 7.2.1.6 mmcv 1.3.7 mmdet 2.13 onnx 1.7

**Comment by RunningLeon** [comment]
Hi, @BChunlei For TensorRT inference with Python, you could check `mmdet.core.export.model_wrappers.TensorRTDetector` for reference.

**Comment by BChunlei** [comment]
Hi, @RunningLeon ,i have changed my code as :
`from mmdet.core.export.model_wrappers import TensorRTDetector`
`engine_file=‘my_trt/yolov3.trt’`
`my_detector = TensorRTDetector(engine_file,class_names,device_id)`

but it shows me that:
`Traceback (most recent call last):
  File "my_infer.py", line 21, in <module>
    my_detector = TensorRTDetector(engine_file,class_names,device_id)
  File "/root/bcl/projects/mmdetection/mmdet/core/export/model_wrappers.py", line 166, in __init__
    model = TRTWraper(engine_file, ['input'], output_names)
  File "/root/bcl/downloads/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 232, in __init__
    super().__init__(*args, **kwargs)
  File "/root/bcl/downloads/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 162, in __init__
    raise TypeError('engine should be str or trt.ICudaEngine')
TypeError: engine should be str or trt.ICudaEngine`

The 'yolov3.trt' file is exported by pytorch2onnx.py and onnx2tensorrt.py with ubuntu 16.04. For some reasons, i run 'TensorRTDetector(engine_file,class_names,device_id)' with ubuntu 18.04.

**Comment by RunningLeon** [comment]
@BChunlei Hi, for TensorRT, you have to create and run the engine on the same device(same Nvidia Graphics Card).

**Comment by BChunlei** [comment]
Hi @RunningLeon , I have created and run the engine on the same device. Got the same error:
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "my_infer.py", line 22, in <module>
    my_detector = TensorRTDetector(engine_file,class_names,device_id)
  File "/root/bcl/projects/mmdetection/mmdet/core/export/model_wrappers.py", line 166, in __init__
    model = TRTWraper(engine_file, ['input'], output_names)
  File "/root/bcl/downloads/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 232, in __init__
    super().__init__(*args, **kwargs)
  File "/root/bcl/downloads/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 162, in __init__
    raise TypeError('engine should be str or trt.ICudaEngine')
TypeError: engine should be str or trt.ICudaEngine

**Comment by BChunlei** [comment]
@RunningLeon, I got the following errors when I do inference with trt model:

[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1128, condition: engineDims.nbDims == dimensions.nbDims
[TensorRT] ERROR: Parameter check failed at: engine.cpp::resolveSlots::1318, condition: allInputDimensionsSpecified(routine)
Traceback (most recent call last):
  File "../my_trt_infer/my_infer.py", line 35, in <module>
    outputs = my_detector.forward_test(one_img,one_meta)
  File "/root/bcl/projects/mmdetection-2.14.0/mmdet/core/export/model_wrappers.py", line 179, in forward_test
    outputs = self.model({'input': input_data})
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/bcl/downloads/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 216, in forward
    shape = tuple(self.context.get_binding_shape(idx))
ValueError: __len__() should return >= 0


I use the following code and commands:
torch->onnx:
`python tools/deployment/pytorch2onnx.py configs/yolo/yolov3_d53_mstrain-416_273e_coco.py checkpoints/yolov3_d53_mstrain-416_273e_coco-2b60fcd9.pth --shape 416 416 --output-file my_onnx/yolov3.onnx --dynamic-export --verify`
onnx->trt:
`python tools/deployment/onnx2tensorrt.py configs/yolo/yolov3_d53_mstrain-416_273e_coco.py my_onnx/yolov3.onnx --trt-file my_trt/yolov3.trt --shape 416 416 --min-shape 416 224 --max-shape 416 640 --input-img demo/demo.jpg --verify`
inference:
from mmdet.core.export.model_wrappers import TensorRTDetector
from mmdet.core.export import preprocess_example_input

class_names = ('person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
               'train', 'truck', 'boat', 'traffic light', 'fire hydrant',
               'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog',
               'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
               'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
               'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat',
               'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
               'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl',
               'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
               'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
               'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop',
               'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
               'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock',
               'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush')
engine_file = '/root/bcl/projects/mmdetection-2.14.0/my_trt/yolov3.trt'
device_id = 'cuda:0'

my_detector = TensorRTDetector(engine_file,class_names,device_id)
input_config = {
    'input_shape': (1,3,416,416),
    'input_path': '/root/bcl/projects/my_trt_infer/my_images/00063.jpg',
    'normalize_cfg': {
        'mean': (123.675, 116.28, 103.53),
        'std': (58.395, 57.12, 57.375)
        }
}
one_img, one_meta = preprocess_example_input(input_config)
print(one_img.shape)
outputs = my_detector.forward_test(one_img,one_meta)
print(outputs)

**Comment by RunningLeon** [comment]
@BChunlei Hi, yes. Have successfully created a TensorRT engine and ran an inference with `onnx2tensorrt` tool ?

**Comment by BChunlei** [comment]
I use the following command to generate onnx model:
`python tools/deployment/pytorch2onnx.py configs/_my_config/my_yolov3_config_608.py work_dirs/my_yolov3_config_608/epoch_1.pth --output-file my_onnx/yolov3.onnx --shape 608 608 --dynamic-export`

When I use onnx model gennerated by above command to do test:'python tools/deployment/test.py configs/_my_config/my_yolov3_config_608.py my_onnx/yolov3.onnx --backend onnxruntime --eval bbox', error occurs:

339 Execute] Non-zero status code returned while running TopK node. Name:'TopK_472' Status Message: k argument [1000] should not be greater than specified axis dim value [855]
Traceback (most recent call last):
  File "tools/deployment/test.py", line 142, in <module>
    main()
  File "tools/deployment/test.py", line 121, in main
    args.show_score_thr)
  File "/root/bcl/projects/mmdetection-2.14.0/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/bcl/downloads/mmcv/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/bcl/projects/mmdetection-2.14.0/mmdet/core/export/model_wrappers.py", line 44, in forward
    outputs = self.forward_test(img, img_metas, **kwargs)
  File "/root/bcl/projects/mmdetection-2.14.0/mmdet/core/export/model_wrappers.py", line 146, in forward_test
    self.sess.run_with_iobinding(self.io_binding)
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 229, in run_with_iobinding
    self._sess.run_with_iobinding(iobinding._iobinding, run_options)
RuntimeError: Error in execution: Non-zero status code returned while running TopK node. Name:'TopK_472' Status Message: k argument [1000] should not be greater than specified axis dim value [855]

**Comment by BChunlei** [comment]
I see, I set nms_pre=1000. it's greater than 855.

**Comment by BChunlei** [comment]
@RunningLeon, Hi, I use the following command to generate trt model:
`python tools/deployment/onnx2tensorrt.py configs/_my_config/my_yolov3_config_608.py my_onnx/yolov3.onnx --trt-file my_trt/yolov3.trt --shape 608 608 --min-shape 608 384 --max-shape 608 768 --input-img demo/demo.jpg --verify`

I can get the trt model, but when l do reference, the same error:

[                                                  ] 0/3955, elapsed: 0s, ETA:[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::resolveSlots::1318, condition: allInputDimensionsSpecified(routine)
Traceback (most recent call last):
  File "tools/deployment/test.py", line 142, in <module>
    main()
  File "tools/deployment/test.py", line 121, in main
    args.show_score_thr)
  File "/root/bcl/projects/mmdetection-2.14.0/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/bcl/downloads/mmcv/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/bcl/projects/mmdetection-2.14.0/mmdet/core/export/model_wrappers.py", line 44, in forward
    outputs = self.forward_test(img, img_metas, **kwargs)
  File "/root/bcl/projects/mmdetection-2.14.0/mmdet/core/export/model_wrappers.py", line 179, in forward_test
    outputs = self.model({'input': input_data})
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/bcl/downloads/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 216, in forward
    shape = tuple(self.context.get_binding_shape(idx))
ValueError: __len__() should return >= 0

**Comment by BChunlei** [comment]
@RunningLeon ,Hi, I solve the problem by this method:https://github.com/open-mmlab/mmdetection/issues/5331.
Now, I can do inference with trt model and get the results. But the accuracy is significantly lower than onnx model. onnx model mAP is 0.516 and trt model mAP is 0.3. I use the following command to test the model:
trt test:
`python tools/deployment/test.py configs/_my_config/my_yolov3_config_608.py my_trt/yolov3_608.trt --backend tensorrt --eval bbox`
onnx test:
`python tools/deployment/test.py configs/_my_config/my_yolov3_config_608.py my_trt/yolov3_608.trt --backend onnxruntime --eval bbox`

Moreover, when doing inference with trt model, I can get some error messages like:
[>>>>>>>>>>>>>>>>>                                 ] 1394/3955, 42.1 task/s, elapsed: 33s, ETA:    61s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[>>>>>>>>>>>>>>>>>                                 ] 1395/3955, 42.1 task/s, elapsed: 33s, ETA:    61s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                    ] 2381/3955, 42.9 task/s, elapsed: 56s, ETA:    37s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                    ] 2386/3955, 42.9 task/s, elapsed: 56s, ETA:    37s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 2622/3955, 43.0 task/s, elapsed: 61s, ETA:    31s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 2667/3955, 43.0 task/s, elapsed: 62s, ETA:    30s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                 ] 2686/3955, 43.0 task/s, elapsed: 62s, ETA:    30s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>            ] 3051/3955, 43.1 task/s, elapsed: 71s, ETA:    21s[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]

**Comment by RunningLeon** [comment]
> >

@BChunlei When you convert model to ONNX for TensorRT backend and hope its input shape be dynamic, you have to consider the min and max input shape.
Based on the preprocessing pipeline in the config, images from coco dataset may be processed to the shape such as `192 608` or `608 192`.
Thus, when you create onnx using `pytorch2onnx.py`, the argument `--shape` should be `min_size min_size`. Then when using `onnx2tensorrt.py`, argument `--min-shape` should be `min_size min_size`, `--max-shape` should be `max_size max_size`.

**Comment by BChunlei** [comment]
Thanks a lot, I have solve the problem. BTW, does mmdet have the api for .trt inference lile .pth inference  'inference_detector(model, img)' in mmdet.apis?

**Comment by RunningLeon** [comment]
@BChunlei Hi, there's no inference api for TensorRT and ONNX Runtime backend for now.

**Comment by BChunlei** [comment]
Hi @RunningLeon ,I use the following script to do inference with trt model. But it's much slower than the project mmdetection-to-tensorrt,13 fps vs 45 fps. Could you give me some tips about the following code？

from mmdet.core.export.model_wrappers import TensorRTDetector
from mmcv.parallel import MMDataParallel
from mmdet.datasets.pipelines import Compose
import mmcv
import torch
from mmcv.parallel.data_container import DataContainer
import time

def trt_infer(model,test_pipeline,img,device='cuda:0'):
    data = dict(img_info=dict(filename=img), img_prefix=None)
    
    # prepare data
    data = test_pipeline(data)
    
    #img增加一维，格式与test方法是输入一致
    tensor = data['img'][0]
    if isinstance(tensor, mmcv.parallel.DataContainer):
        tensor = tensor.data
    tensor = tensor.unsqueeze(0)
    data['img'][0] = tensor
    
    #强行将输入数据格式保持与test方法的输入一致
    data['img_metas'][0] = DataContainer([[data['img_metas'][0].data]],cpu_only=True)
    
    with torch.no_grad():
        result = model(return_loss=False, rescale=True, **data)
    
    return result

def main():
    cfg_path = '/root/bcl/projects/mmdetection-2.14.0/configs/_my_config/my_yolov3_config_608.py'
    engine_file = '/root/bcl/projects/mmdetection-2.14.0/my_trt/yolov3_608.trt'
    class_names = ('bulldozer','cement_pump_truck','da_zhuang_ji','excavator','tower_crane_arm','truck_crane','truck_crane_working_arm')
    device_id = 0
    img = '/root/bcl/projects/my_trt_infer/my_images/00063.jpg'
    
    model = TensorRTDetector(engine_file, class_names=class_names, device_id=device_id)
    model = MMDataParallel(model, device_ids=[device_id])
    
    cfg = mmcv.Config.fromfile(cfg_path)
    
    test_pipeline = Compose(cfg.data.test.pipeline)
    
    s_t = time.time()
    for i in range(100):
        result = trt_infer(model,test_pipeline,img)
    e_t = time.time()
    print(100/(e_t - s_t))
    
if __name__=='__main__':
    main()

**Comment by RunningLeon** [comment]
@BChunlei Hi, we did not do the speed benchmark with backend such as TensorRT, ONNX Runtime up to now.

**Comment by chuong98** [comment]
> When you convert model to ONNX for TensorRT backend and hope its input shape be dynamic, you have to consider the min and max input shape.
> Based on the preprocessing pipeline in the config, images from coco dataset may be processed to the shape such as `192 608` or `608 192`.
> Thus, when you create onnx using `pytorch2onnx.py`, the argument `--shape` should be `min_size min_size`. Then when using `onnx2tensorrt.py`, argument `--min-shape` should be `min_size min_size`, `--max-shape` should be `max_size max_size`.

This is very important. Please have it mention in the tutorial !!!
For COCO, I found the parameters:

```
    --shape 800 1333 \
    --min-shape 320 320 \
    --max-shape 1600 1600 \
```
yield correct mAP. However, the speed of TensorRT and Pytorch model is almost the same. My test with `Cascade-R50-fpn` on V100 gives: 
+ Pytorch: 5000/5000, 15.6 task/s, elapsed: 320s. mAP 40.3 
+ TensorRT : 5000/5000, 15.8 task/s, elapsed: 316s. mAP: 40.1

**Comment by ZwwWayne** [comment]
As MMDeploy is released https://github.com/open-mmlab/mmdeploy. MMDet will no longer maintain the feature of  model export. Please use MMDeploy and create an issue if you still have questions about that.
