### ISSUE TITLE
请问下，deformable DETR里面的参数配置是按照几个GPU的配置的？

### ISSUE THREAD

**Issue by cjt222** [open-mmlab/mmdetection#5454]

**Comment by cjt222** [comment]
请问下，按照deformable DETR里面的参数配置如学习率，batch size等，训练时需要几个gpu？

**Comment by ElectronicElephant** [comment]
In config name,

16x2 = 16 GPUs, with 2 imgs on each GPU

**Comment by jshilong** [comment]
We follow the original implementation with a total batch size of 32 on 16 gpus
