### ISSUE TITLE
unexpected error!

### ISSUE THREAD

**Issue by lixiuyu-cumt** [open-mmlab/mmdetection#5455]
When I set up all the configurations,an error occured:
ValueError: need at least one array to concatenate.
It may happened in the process of Dataloader.
The version of MMdetection is 2.13.0,but when i change the version to 2.12.0,there is no such mistake.
However,it happened again this afternoon,when I installed  the MMdetection 2.10.0.

**Comment by alaa-shubbak** [comment]
i have the same problem , even if i change mmcv from version 1.3.7 to 1.3.3 , it is still appear. i can not do training for  even a small dataset of 47 training images, 12 test images and 12 val images.

**Comment by jshilong** [comment]
Would you mind give a detailed error message with the issue template?

**Comment by jshilong** [comment]
Is the error the same as issue #4625 ?
https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/mmdet/datasets/samplers/group_sampler.py#L25
Seem you use `GroupSampler`, you may debug what value the `self.group_sizes` is in your code.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
