### ISSUE TITLE
When I run the NASFPN, I met AssertionError.

### ISSUE THREAD

**Issue by shuowang666** [open-mmlab/mmdetection#5457]
File "/usr/local/lib/python3.6/dist-packages/mmcv/ops/merge_cells.py", line 97, in _resize
    assert x.shape[-2] % size[-2] == 0 and x.shape[-1] % size[-1] == 0
AssertionError

I met the above problem all the time， could you tell me what I can do to deal with it？

**Comment by ZwwWayne** [comment]
The shapes of features are differernt. You need to modify the hyper-parameters of the module.
