### ISSUE TITLE
Runtime error on Jetson TX2

### ISSUE THREAD

**Issue by superying** [open-mmlab/mmdetection#546]
I tried to run the test codes(https://github.com/open-mmlab/mmdetection#test-images) from READ.ME on my Jetson TX2. 
But I meet this error:
THCudaCheck FAIL file=/home/nvidia/pytorch/aten/src/THC/THCTensorSort.cu line=62 error=7 : too many resources requested for launch
mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py line=266
_, topk_inds = max_scores.topk(nms_pre)

PyTorch : branch topk_launch_bounds
(https://github.com/t-vi/pytorch/tree/topk_launch_bounds)
install PyTorch : from source
Python version: 3.5
CUDA/cuDNN version: cuda8.0 and cudnn6.0.4

I checked the pytorch github repo, there is similar error in Jetson before, and pytorch has fix this bug:
https://github.com/pytorch/pytorch/issues/17144
The pytorch I used just fixed this bug.

Any idea is welcome. Thanks.

**Comment by fadonoso** [comment]
Hi mate,

Did you resolve the problem? Could you give guidelenes for installing mmdetection on jetson tx2 please.

**Comment by hhaAndroid** [comment]
Sorry. We have no plan to support Jetson at the moment, but community contributions are welcome.
