### ISSUE TITLE
我注意到你们给的配置文件test部分都是用的coco的val部分啊，真正的test文件是没有Ground Truth的，那么怎么在配置文件中写test.json呢？

### ISSUE THREAD

**Issue by wong1998** [open-mmlab/mmdetection#5460]
我是用的自己的数据集格式都转化成coco了，但是测试集没有标签怎么写json文件呢？？？

**Comment by cyZhu-upup** [comment]
我是自己写了一个生成json的脚本，按照coco格式，写个只有'categories'和'images'两个key的字典

**Comment by wong1998** [comment]
> 我是自己写了一个生成json的脚本，按照coco格式，写个只有'categories'和'images'两个key的字典

谢谢哈，我进你的主页看到了你写的脚本~~~~
