### ISSUE TITLE
How to get runner state in the detector class?

### ISSUE THREAD

**Issue by LuckyDC** [open-mmlab/mmdetection#5462]
Thanks for your great framework! I encounter a  case where I have to change the contribution of a branch to the final output according to the training process. But I do not know how to access runner.epoch in the `forward_train` function of the detector or head class. Would you like to provide a solution? Thanks

**Comment by ZwwWayne** [comment]
For now, you may need to customize a runner following this PR https://github.com/open-mmlab/mmcv/pull/1115.
We are still working on it to provide safe and stable usage. This feature will be officially supported in the future.
