### ISSUE TITLE
Some error in dataset visualization code

### ISSUE THREAD

**Issue by xychen9459** [open-mmlab/mmdetection#5463]
I found that `tools/misc/browse_dataset.py` has some error when loading config dict in the line 55-58
```
train_data_cfg = cfg.data.train
train_data_cfg['pipeline'] = [
    x for x in train_data_cfg.pipeline if x['type'] not in skip_type
]
```
If the training data is wrapped with 'RepeatDataset', the above codes can report the following error:
```
......
File "tools/misc/browse_dataset.py", line 57, in retrieve_data_cfg
    x for x in train_data_cfg.pipeline if x['type'] not in skip_type
......
AttributeError: 'ConfigDict' object has no attribute 'pipeline'
```
In fact, the real dataset config is contained in the key 'dataset' of 'RepeatDataset' (see `mmdet/datasets/dataset_wrappers.py`). I tried to fix the error with the following codes:
```
train_data_cfg = cfg.data.train
if isinstance(train_data_cfg, ConfigDict):           # unwrap the real dataset config from RepeatDataset
    train_data_cfg = train_data_cfg['dataset']
train_data_cfg['pipeline'] = [
    x for x in train_data_cfg.pipeline if x['type'] not in skip_type
]
```
Now I can visualize the dataset properly.

**Comment by ZwwWayne** [comment]
Thanks for your bug report. Would you like to create a PR for that?

**Comment by xychen9459** [comment]
Ok, I'll try to create a PR in the next few days. But I need some time to
learn how to use PR on github.

Wenwei Zhang ***@***.***> 于2021年6月28日周一 下午10:44写道：
