### ISSUE TITLE
Should we use `int32_t` or `int64_t` instead of  both `int` and `long` in C++11 to make it clear?

### ISSUE THREAD

**Issue by ausk** [open-mmlab/mmdetection#547]
Hi, thanks for your great works.

But failed to compile the mmdetection on Windows using `VS2017` +  `Cuda10` + `Python 3.7` + `Pytorch1.0.1` + `Git for Windows`.

Take `mmdetection/mmdet/ops/sigmoid_focal_loss` for example:

1. One of the issue is `more than one operator "==" matches these operands"` ( not only for "==", but also for "<", "<=", ">", ">="). It can be fixed by add flag `-D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__`. Or we can pass `extra_compile_args` parameter when calling `CUDAExtension` in `setup.py`.

2. And there is another the frequency issue is`no instance of function template "THCCeilDiv" matches` of line `std::min(THCCeilDiv(output_size, 512L) ...`. It can be fixed by add explicit type `std::min(THCCeilDiv((long)output_size, 512L) ...`.

3. Then when rebuild again, an issue `unresolved symbols: "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)` occurs. Replace the `long` to `int` in `sigmoid_focal_loss_cuda.cu` will fix the issue.

Now, I compile the sigmoid_focal_loss successfully, but still fail to compile others.

-----

And I have a question:

Considing the `mordern C++ compiler` should have supported `C++11` already, what's the exact attention to use both `int` and `long` in C++(11) program, should use `int32_t` or `int64_t` instead of  both `int` and `long` to make it clear?

**Comment by hellock** [comment]
Sorry that we do not have windows servers so that no official support for windows is provided. If you struggle out, a PR will be much appreciated.

For the usage of `int` and `long`, we just follow pytorch source codes, where `int` and `long` are also widely used. However, I don't mind changing them to `int32_t` and `int64_t`.
