### ISSUE TITLE
Tensorrt error

### ISSUE THREAD

**Issue by AverinaMasha** [open-mmlab/mmdetection#5472]
**TensorRT Version-8.0.0.3:
pythorch 1.7.0
CUDA Version-11.0:
Operating System + Version- Ubuntu 20.04:
Python Version-3.7.**

I am trying to install tensorrt, but when compiling it writes an error and removes mmcv. With onnx, everything was fine.

![image](https://user-images.githubusercontent.com/43960358/123652491-042f3100-d835-11eb-923e-53fac4b20b90.png)

**Comment by RunningLeon** [comment]
@AverinaMasha Hi, we only tested the supported models with the below config:
> 
All models above are tested with Pytorch==1.6.0, onnx==1.7.0 and TensorRT-7.2.1.6.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.0
