### ISSUE TITLE
Should use get_root_logger() in mmdet.utils

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection#5473]
Should use get_root_logger() in mmdet.utils

_Originally posted by @ZwwWayne in https://github.com/open-mmlab/mmdetection/pull/5440#r658693800_

**Comment by AronLin** [comment]
#5540 is for solving this problem.

**Comment by AronLin** [comment]
We should not use get_root_logger() now.
get_root_logger() will be declared during initialization. So every process will output warnings.
