### ISSUE TITLE
error during training of a small dataset /faster rcnn training 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5474]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. yes
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help. yes
3. The bug has not been fixed in the latest version. yes 

**Describe the bug**
the error message is : 
ValueError: need at least one array to concatenate

**Reproduction**

1. What command or script did you run?
`python tools/train.py  configs/human/my_custom_config.py`

2. Did you make any modifications on the code or config? Did you understand what you have modified?

yes, for dataset , and for the model.  i am working only with one class, 
a- so i change the classes_num in the config that i used which was 
/_base_/models/faster_rcnn_r50_fpn.py  
b- changing the name of classes in dataset 
'../_base_/datasets/coco_detection.py'   ...classes = ('person',)
and changing 
samples_per_gpu=1,
workers_per_gpu=1, 

even with keep the sample_per_gpu and the workers as it is (2 ) , i still get the same error message. 
c. my config script contains : 
![config script last](https://user-images.githubusercontent.com/10245810/123669788-c33b1a80-d83c-11eb-9076-2889b3c843f1.JPG)

3. What dataset did you use?
a new dataset , but with same coco format , and i put its file in the same path of coco dataset, by the way , my dataset is so small . it is 47 images for training , 12 images for test, and same 12 images for validation. 
my dataset is in the coco format (the annotation data are  not normalized for bbox and segmentation) , here are a sample: 
![dataset 1](https://user-images.githubusercontent.com/10245810/123669215-25475000-d83c-11eb-8a86-dfad1a2c8714.JPG)
![dataset 2](https://user-images.githubusercontent.com/10245810/123669237-2a0c0400-d83c-11eb-9f22-cb3f9d7e38db.JPG)
![dataset 3](https://user-images.githubusercontent.com/10245810/123669257-2d9f8b00-d83c-11eb-9f94-ecaaa56cb9fd.JPG)

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

python mmdet/utils/collect_env.py
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce RTX 2070
GPU 1: GeForce GTX 1650
CUDA_HOME: /usr/local/cuda
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0
OpenCV: 4.5.2
MMCV: 1.3.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.13.0+0e09f00

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] 
    conda 
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
add my dataset in the same path of mmdetection folder.
the tree of my dataset is: 
![dataset tree 1](https://user-images.githubusercontent.com/10245810/123668036-fe3c4e80-d83a-11eb-8dff-18fd26c4213a.JPG)
![dataset tree 2](https://user-images.githubusercontent.com/10245810/123668066-05fbf300-d83b-11eb-82e5-0e614b33c19b.JPG)

**Error traceback**
If applicable, paste the error trackback here.

```
/home/alshubbak/mmdetection/mmdet/models/detectors/two_stage.py:28: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
/home/alshubbak/mmdetection/mmdet/models/backbones/resnet.py:400: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
2021-06-28 17:35:11,821 - mmcv - INFO - load model from: torchvision://resnet50
2021-06-28 17:35:11,821 - mmcv - INFO - Use load_from_torchvision loader
2021-06-28 17:35:11,933 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py:100: UserWarning: init_cfg without layer key, if you do not define override key either, this init_cfg will do nothing
  'init_cfg without layer key, if you do not define override'
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-06-28 17:35:13,563 - mmdet - INFO - load checkpoint from checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
2021-06-28 17:35:13,563 - mmdet - INFO - Use load_from_local loader
2021-06-28 17:35:13,673 - mmdet - WARNING - The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).
size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([2]).
size mismatch for roi_head.bbox_head.fc_reg.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([4, 1024]).
size mismatch for roi_head.bbox_head.fc_reg.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([4]).
2021-06-28 17:35:13,677 - mmdet - INFO - Start running, host: alshubbak@pc-2170, work_dir: /home/alshubbak/mmdetection/work_dirs/my_custom_config
2021-06-28 17:35:13,677 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/home/alshubbak/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/alshubbak/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/alshubbak/mmdetection/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

```
**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
Hi @alaa-shubbak  you can refer to https://github.com/open-mmlab/mmdetection/issues/4687.

**Comment by alaa-shubbak** [comment]
I read the previous issue #4687 , and try every steps there . 
unfortunately , the problem has not been solved. please , any other suggestion?

**Comment by alaa-shubbak** [comment]
is my problem related to the memory used through the training or because of model? 
if it is related to the memory, 
is there a way to training my model using slurm and only two GPU systems , if so could you please support me with the instruction to do so? 

attached the size need for training the model after running the code
 `python tools/analysis_tools/get_flops.py configs/human/my_custom_config.py`

![memory and flops](https://user-images.githubusercontent.com/10245810/124350708-82edea80-dbf6-11eb-8e6f-8e806a7db05d.JPG)

my input image size is totally different than those in this picture , 
my image size is (3, 2208, 1242)

i am still confused , what is exactly my problem? please help me.

**Comment by alaa-shubbak** [comment]
i try to  use this command , with 2 gpus to train my small dataset 
` python tools/train.py configs/human/my_custom_config.py --gpus 2 --work-dir training_data/faster_rcnn`

unfortunately, it is also not working. 

I got again the same error which is : 
ValueError: need at least one array to concatenate

any help please?

**Comment by hhaAndroid** [comment]
If you are training with multiple GPUs, you need to use the dist script
