### ISSUE TITLE
ModulatedDeformConv is not implemented on CPU on colab

### ISSUE THREAD

**Issue by mahsant** [open-mmlab/mmdetection#5475]
Hi I wanna use modulated_deform_conv on colab.
I use GPU , but I get this error.
I have searched related issues but cannot get the expected help and I can't solve it.
can u please help me?
 thank u

**RuntimeError: ModulatedDeformConv is not implemented on CPU**

**Comment by hhaAndroid** [comment]
Hi @mahsant It means you are using cpu instead of gpu, please check your environment.
