### ISSUE TITLE
请问NMS在哪里可以修改

### ISSUE THREAD

**Issue by cyZhu-upup** [open-mmlab/mmdetection#5477]
只知道还有个soft_nms可以替换，找了好久没找到在哪个文件里定义的nms

**Comment by RangiLyu** [comment]
https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py

**Comment by cyZhu-upup** [comment]
谢谢大佬， 原来是在mmcv里，难怪找不到
