### ISSUE TITLE
Where can I download mmcv_full and mmdet wheel of each version?

### ISSUE THREAD

**Issue by Keiku** [open-mmlab/mmdetection#5480]
`addict-2.4.0-py3-none-any.whl`, `mmcv_full-1.2.6-cp37-cp37m-manylinux1_x86_64.whl`, and `mmdet-2.10.0-py3-none-any.whl` wheels were distributed on kaggle. Where can I download these original wheels? I want to download another version of wheel, but I can't find the link.

It was distributed at the link below.

https://www.kaggle.com/frankx7/mmdet2100

**Comment by RangiLyu** [comment]
You can find them in pypi. https://pypi.org/project/mmdet/#history https://pypi.org/project/mmcv-full/#history

**Comment by Keiku** [comment]
Thank you. Is it okay that the wheel is not distributed? For now, use "pip install".
