### ISSUE TITLE
AttributeError: 'CascadeRoIHead' object has no attribute 'onnx_export'

### ISSUE THREAD

**Issue by pengaoao** [open-mmlab/mmdetection#5481]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
cascade_rcnn 使用python3.7.5 tools/deployment/pytorch2onnx.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py ./cascade_rcnn_r50_fpn_1x_coco_20200316-3dc56deb.pth --shape=1216 --output-file=cascadedRCNN.onnx 导出onnx报错，错误：AttributeError: 'CascadeRoIHead' object has no attribute 'onnx_export'
**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
ubuntu18.04 x86
1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RangiLyu** [comment]
According to the [pytorch2onnx doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md), MMDet currently not support exporting Cascade RCNN to ONNX.

**Comment by pengaoao** [comment]
> According to the [pytorch2onnx doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md), MMDet currently not support exporting Cascade RCNN to ONNX.

不是吧  我在mmdet2.8是可以导出这个onnx的，只不过只支持单batch，现在都2.13了 怎么就不支持了呢

**Comment by pengaoao** [comment]
> According to the [pytorch2onnx doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md), MMDet currently not support exporting Cascade RCNN to ONNX.

不是吧  我在mmdet2.8是可以导出这个onnx的，只不过只支持单batch，现在都2.13了 怎么就不支持了呢

**Comment by RangiLyu** [comment]
@jshilong

**Comment by jshilong** [comment]
The ONNX export of Cascade maybe just an accidental product when we support Faster-RCNN, Only the models in the documents would be tested when we change the related code.

**Comment by jshilong** [comment]
@pengaoao 
I did it in PR #5486,  the Cascade-RCNN can be exported to ONNX with batch dimension. The visualization result seems reasonable, You can try it.
PR #5486  would be merged soon

**Comment by ChicoQ** [comment]
I've done a same model recently but using v2.10 since the latest version has an error as described in this PR. 
In my experiment, if only the boxes with its score greater than 0.4 for example, the onnx model could be acceptable. I'm glad to see this PR will be implemented in the short future. Thanks @jshilong

**Comment by jshilong** [comment]
> I've done a same model recently but using v2.10 since the latest version has an error as described in this PR.
> In my experiment, if only the boxes with its score greater than 0.4 for example, the onnx model could be acceptable. I'm glad to see this PR will be implemented in the short future. Thanks @jshilong

you need to pay attention to the code segment related to the `nms` that I changed in `bbox_head.py`.
`add_dummy_nms_for_onnx` has two sets of parameter forms, it is easy to make mistakes.

**Comment by pengaoao** [comment]
> @pengaoao
> I did it in PR #5486, the Cascade-RCNN can be exported to ONNX with batch dimension. The visualization result seems reasonable, You can try it.
> PR #5486 would be merged soon

你好，感觉不太对，onnx_helper里面的num_class  导出fasterRCNN 的时候应该是80类吧 用内置脚本转onnx，输出为什么总是1呢

**Comment by pengaoao** [comment]
> > @pengaoao
> > I did it in PR #5486, the Cascade-RCNN can be exported to ONNX with batch dimension. The visualization result seems reasonable, You can try it.
> > PR #5486 would be merged soon
> 
> 你好，感觉不太对，onnx_helper里面的num_class 导出fasterRCNN 的时候应该是80类吧 用内置脚本转onnx，输出为什么总是1呢
感觉bbonx_head.py里面540行左右 scores = scores.reshape(batch_size, -1)是多余的

**Comment by ChicoQ** [comment]
@jshilong I've tried branch onnx-cascade but got this exception,

  %3315 : Long(1:100, 100:1, 1:1, requires_grad=0, device=cpu) = onnx::Gather[axis=0](%3313, %3314) # mmdetection/mmdet/core/export/onnx_helper.py:192:0
  %3317 : Tensor = onnx::Unsqueeze[axes=[0]](%3143)
  %3319 : Tensor = onnx::Concat[axis=0](%3317, %3668)
  %labels : Long(1:100, 100:1, requires_grad=0, device=cpu) = onnx::Reshape(%3315, %3319) # mmdetection/mmdet/core/export/onnx_helper.py:193:0
  %3321 : Float(1:100, 100:1, 1:1, requires_grad=1, device=cpu) = onnx::Unsqueeze[axes=[2]](%3300) # mmdetection/mmdet/core/export/onnx_helper.py:195:0
  %dets : Float(1:500, 100:5, 5:1, requires_grad=1, device=cpu) = onnx::Concat[axis=2](%3311, %3321) # mmdetection/mmdet/core/export/onnx_helper.py:196:0
  return (%dets, %labels)


No such file ''

with this command line python tools/deployment/pytorch2onnx.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_voc0712.py work_dirs/cascade_rcnn_r50_fpn_1x_voc0712/epoch_12.pth  --output-file cascade_rcnn_r50_fpn_1x_voc0712_8July.onnx  --input-img temp.jpg  --shape 1000 600 --mean 123.675 116.28 103.53 --std 58.395 57.12 57.375  --simplify --verify --show --dataset voc --dynamic-export

**Comment by pengaoao** [comment]
CLOSE

**Comment by jshilong** [comment]
> @jshilong I've tried branch onnx-cascade but got this exception,
> 
> %3315 : Long(1:100, 100:1, 1:1, requires_grad=0, device=cpu) = onnx::Gather[axis=0](%3313, %3314) # mmdetection/mmdet/core/export/onnx_helper.py:192:0
> %3317 : Tensor = onnx::Unsqueeze[axes=[0]](%3143)
> %3319 : Tensor = onnx::Concat[axis=0](%3317, %3668)
> %labels : Long(1:100, 100:1, requires_grad=0, device=cpu) = onnx::Reshape(%3315, %3319) # mmdetection/mmdet/core/export/onnx_helper.py:193:0
> %3321 : Float(1:100, 100:1, 1:1, requires_grad=1, device=cpu) = onnx::Unsqueeze[axes=[2]](%3300) # mmdetection/mmdet/core/export/onnx_helper.py:195:0
> %dets : Float(1:500, 100:5, 5:1, requires_grad=1, device=cpu) = onnx::Concat[axis=2](%3311, %3321) # mmdetection/mmdet/core/export/onnx_helper.py:196:0
> return (%dets, %labels)
> 
> No such file ''
> 
> with this command line python tools/deployment/pytorch2onnx.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_voc0712.py work_dirs/cascade_rcnn_r50_fpn_1x_voc0712/epoch_12.pth --output-file cascade_rcnn_r50_fpn_1x_voc0712_8July.onnx --input-img temp.jpg --shape 1000 600 --mean 123.675 116.28 103.53 --std 58.395 57.12 57.375 --simplify --verify --show --dataset voc --dynamic-export

I test the `tools/deployment/pytorch2onnx.py` and all seems well.

**Comment by DuckJ** [comment]
@jshilong I noticed that you  implemented the process of cascade onnx export, I did some change in my project that the mmdet version is 2.13.0,  I used the DetectoRS_Resnet18 as backbone, but the error is 
`Exporting the operator var to onnx  opset version 11 is not supported.`
I guess AWS caused it , so I tried resnet18, then the backbone can be exported.
Did you try the DetectoRS_Resnet in your project, can you help me ?

**Comment by DuckJ** [comment]
@jshilong Even if I use resnet18 as backbone, when I export the onnx model, the final error is 
`Only tuples,lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended, but got unsupported  type numpy`
Can you give some advice

**Comment by DuckJ** [comment]
My pytorch version is 1.6.0, mmdetection 2.13.0, mmcv 1.3.5
