### ISSUE TITLE
so what should the test dataset config be like without ground-truth annotations

### ISSUE THREAD

**Issue by s1mpleee** [open-mmlab/mmdetection#5482]
![Screenshot from 2021-06-29 19-54-38](https://user-images.githubusercontent.com/68166466/123793050-e258ab80-d913-11eb-85d4-0922b16eb8e5.png)
 
you see if I create a empty json file,I would get an eroor below...

![Screenshot from 2021-06-29 19-56-30](https://user-images.githubusercontent.com/68166466/123793304-23e95680-d914-11eb-9db0-ca19f9339a6a.png)

I‘m confused right now, should I make the json file not empty and hold some essential information in coco format,or its wrong in other ways

**Comment by HaoGuo98** [comment]
Same to my question. https://github.com/open-mmlab/mmdetection/issues/5442

**Comment by s1mpleee** [comment]
> 和我的问题一样。#5442

so I should write a json file without annotations but contain other essential information of the testset?

**Comment by HaoGuo98** [comment]
yes, you need use a script to get the json file.

**Comment by s1mpleee** [comment]
> yes, you need use a script to get the json file.

I get you. and what would the test result be like, I get a pkl file for it. Is there a way to automatically generate the json file with annotations result, or should I generate it manually?

**Comment by HaoGuo98** [comment]
Manually

**Comment by hhaAndroid** [comment]
Thank you all for your feedback. Considering that this demand is more common, we will provide a conversion script as soon as possible.
