### ISSUE TITLE
Is there K-Net implementation already released?

### ISSUE THREAD

**Issue by p890040** [open-mmlab/mmdetection#5487]
**Describe the feature**

I found that [K-Net: Towards Unified Image Segmentation](https://arxiv.org/abs/2106.14855) published yesterday,and official code is here.
However, I haven't seen the progress on the repo. Is it already done or in the future?
Hope it will be coming soon. thanks!

**Comment by AronLin** [comment]
We are supporting Panoptic Segmentation, the basic methods of panoptic segmentation will be released in a month.
K-Net will be released after we support Panoptic Segmentation.

**Comment by TyroneLi** [comment]
> We are supporting Panoptic Segmentation, the basic methods of panoptic segmentation will be released in a month.
> K-Net will be released after we support Panoptic Segmentation.

It's been a month now, could you release the basic implementation of k-net kernels, in cuda or pytorch?? Thanks
