### ISSUE TITLE
How to train HybridTaskCascade?

### ISSUE THREAD

**Issue by yyangmei** [open-mmlab/mmdetection#549]
I want to train HybridTaskCascade, if there anywhere should I change in train.py?
I found that  `train_dataset = get_dataset(cfg.data.train)` ,but does the function ` get_dataset(cfg.data.train)` handle coco_stuff semantic map?

**Comment by hellock** [comment]
You don't need to make any modifications on the code, just download the dataset following the [readme](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/README.md#dataset).
