### ISSUE TITLE
How to use ATSS at two-stage detectors

### ISSUE THREAD

**Issue by ginobilinie** [open-mmlab/mmdetection#5497]
Hi, I'd like to ask how to use ATSS in two-stage detectors. Since the example configs are all about using ATSS in one-stage detectors. Can you please give me an example?

**Comment by RangiLyu** [comment]
Sorry, the inputs between ATSSAssigner and MaxIOUAssigner are different. So it is unable to use ATSS in two-stage detectors by only modifying the config. You still need to change the code. I think this is a good feature request to make the assigners more general.

**Comment by ginobilinie** [comment]
Thanks. I'll try to modify the code myself.

**Comment by zhaoxin111** [comment]
Have you realized it? I have encountered a similar idea.
