### ISSUE TITLE
Memory sharing

### ISSUE THREAD

**Issue by XiongZhongxia** [open-mmlab/mmdetection#5499]
Hi there. During training, I found memory cost often increases which may break the training procedure. In addition, I only have a PC of 4×12GB GPUs, I cannot train large models such as swinT even using samples_per_gpu=1. So can I use these 4 GPUs to share just 1 image when training? In other words, I assume using samples_per_gpu=1 on 4 GPUs leads to batch_size=4, but can I training on these GPUs using total batchsize=1? Thanks in advance.

**Comment by RangiLyu** [comment]
Sorry, mmdetection does not support model parallelism yet.

**Comment by XiongZhongxia** [comment]
> 
> 
> Sorry, mmdetection does not support model parallelism yet.

OK, thanks.
