### ISSUE TITLE
Can I use mmdetection to train CornerNet?

### ISSUE THREAD

**Issue by Flawless1202** [open-mmlab/mmdetection#55]
The [CornerNet](https://github.com/princeton-vl/CornerNet) is a new model for object detection, and it's code has already been opensourced on github. Is it easy to  add this model to mmdetection? @hellock @OceanPang

**Comment by hellock** [comment]
We do have plan to add CornerNet but maybe after CVPR since we do not have much time now. You can have a try and it will not be difficult.

**Comment by Flawless1202** [comment]
@hellock OK, thanks a lot. Maybe I will try to do that and I really hope to get your help. So if I have any questions can I ask you here?

**Comment by Flawless1202** [comment]
@hellock Hi, these days I'm always reading your code and I think it's an excellent work. but at present I still have problems to understand the code about dataset and dataloader, expecially refer to distribution.
The CornerNet need the top-left and bottom-right coordinates of the bbox instead of (x, y, w, h), so what should I do to adapt to this change? In other words, I should add code to which part of mmdet?

**Comment by hellock** [comment]
The bboxes are represented as (x1, y1, x2, y2), which are naturally top-left and bottom-right corners, so I think there is no need to modify the dataset.

**Comment by ming71** [comment]
> I find the comment in `rpn_head.py` says that "since feature map sizes of all images are the same, we only compute anchors for one time", but the input image shapes are different, so how to make the feature map the same size? @hellock @OceanPang

All inputs are resized to a fixed size for latter process , it's a basic operation , you can read the relative paper or codabase here carefully.

**Comment by lizhe960118** [comment]
when will we get the code about cornetnet or centernet?

**Comment by bhack** [comment]
Here a good overview of recent anchor free solutions https://www.slideshare.net/yuhuang/anchor-free-object-detection-by-deep-learning

**Comment by Ridhwanluthra** [comment]
I am currently working on integrating Centernet: objects as points. you can follow the progress at [my fork](I am currently working on integrating that. you can follow the progress at my fork for now I will be submitting a pull request soon) for now I will be submitting a pull request soon

**Comment by lizhe960118** [comment]
@Ridhwanluthra it's really a great work, thank you very much. What if we add more backbone used for  keypoints detection for centernet in configs, it will be more wonderful!

**Comment by lizhe960118** [comment]
@Ridhwanluthra any plan for  centernet : Keypoint Triplets for Object Detection? it reaches 47.0 mAP in coco, will you do some jobs for it?

**Comment by Ridhwanluthra** [comment]
@lizhe960118 I have would love to be able to include more backbones and thanks to mmdetection's modularity it is very easy to add more. I would be running tests and can test other backbones if we get contributions for that, At the moment I don't have any plans to add more backbones. but feel free to contribute those.
as far as the other centernet is considered, i have no plans so far to include that but once centernet in included adding the other one should not be a very big challenge.

**Comment by lizhe960118** [comment]
@Ridhwanluthra the cpool module in the other centernet (we can call it centernet_key) is compiled by gcc4.9, and the pytorch version is 0.4.1, i am afraid that there would be some problems happen when we install the cpool module. 
By the way, I find that the heads used in hourglass are not added as the independent module in box_heads in your code. If the centernet is a two stage detector, should we separate the heads from the backbone?

**Comment by hellock** [comment]
Already implemented in V2.3.
