### ISSUE TITLE
Dockerfile outdated (1.3.5)?

### ISSUE THREAD

**Issue by jungseokhong** [open-mmlab/mmdetection#5501]
Hello,

I instaleed mmdetection with docker image based on the instruction (https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md). However, the docker image provides 1.3.5 but the verification code in the instruction gives an error since it requires at least 1.3.8. Should I use newer pytorch and cuda version for the dockerfile?

**Comment by hhaAndroid** [comment]
Hi @jungseokhong Can you explain where 1.3.5 is written? I did not find it.

**Comment by hhaAndroid** [comment]
Hi @jungseokhong Maybe you forgot to upload the latest version to Alibaba Cloud, we will fix it as soon as possible.

**Comment by jungseokhong** [comment]
@hhaAndroid Hello,

I am not sure what you meant by Alibaba Cloud?
I just used local docker to run this.

When I ran the verification code, I got this error.

    from mmdet.apis import init_detector, inference_detector
  File "/mmdetection/mmdet/__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.5 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.

**Comment by jshilong** [comment]
PR #5502 has fixed it. Feel free to reopen the issue if there is any question
