### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by xdnjust** [open-mmlab/mmdetection#5503]
hello, I have a question when I used new data to train faster_rcnn，
I converted my data to coco style, based on the website (https://blog.csdn.net/qq_41690533/article/details/115868856)

But a error occurs:
_AssertionError: The `num_classes` (3) in RetinaHead of MMDataParallel does not matches the length of `CLASSES` 80) in CocoDataset_

I need a help!

**Comment by jshilong** [comment]
Please change this tuple 
https://github.com/open-mmlab/mmdetection/blob/e283e2435f11856382df156fb4fe437c375bd56f/mmdet/datasets/coco.py#L22
