### ISSUE TITLE
Problem about test

### ISSUE THREAD

**Issue by munian-ustc** [open-mmlab/mmdetection#551]
I test on coco with command  python tools/test.py configs/mask_rcnn_r101_fpn_gn_2x.py weights/mask_rcnn_r101_fpn_gn_2x_20180113-9598649c.pth --gpus 2 --out result1.pkl --eval bbox segm . No error , but the program just get stuck after create index . 
![2019-04-27 05-50-59屏幕截图](https://user-images.githubusercontent.com/49483370/56838759-df844b00-68b1-11e9-873e-2642be24f034.png)
Thanks!

**Comment by munian-ustc** [comment]
After I kill the progress , it seems got stuck  in here , what should I do ?
![2019-04-27 06-07-12屏幕截图](https://user-images.githubusercontent.com/49483370/56838937-b9ab7600-68b2-11e9-9703-2c6c745e970f.png)

**Comment by hellock** [comment]
Can single gpu testing work in your environment?

**Comment by munian-ustc** [comment]
@hellock Thanks for your reply! I try to test  on single gpu ,and it comes that Segmentation fault (core dumped). I run it under pdb mode , there seems some problem with my pytorch.
![IC)KWDJ{1T1%GOB LIYE XP](https://user-images.githubusercontent.com/49483370/56843302-757b9e00-68d1-11e9-8012-42ec349d525e.png)
Because I have to run my program on server , I have no root right and the gcc version is 4.8.5 ,at first,I could not setup mmdetection . But my friend tells me to modify setup.py in /dcn /nms  /roi_align /roi_pool /sigmoid_focal_loss , according to his advice , I successfully run inference demo. My modification is as following

**Comment by munian-ustc** [comment]
@hellock my modification:
![Uploading TIM图片20190427100202.png…]()

**Comment by munian-ustc** [comment]
@hellock my modification:
![TIM图片20190427100202](https://user-images.githubusercontent.com/49483370/56843474-f2a81280-68d3-11e9-8f4d-ebf7f69dc6b8.png)

**Comment by hellock** [comment]
Segmentation fault usually happens when you use gcc 4.8 and precompiled pytorch to compile extensions.

**Comment by munian-ustc** [comment]
I have solved this problem by install gcc4.9 without root rights.Thank your help! @hellock
