### ISSUE TITLE
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1128, condition: engineDims.nbDims == dimensions.nbDims

### ISSUE THREAD

**Issue by BChunlei** [open-mmlab/mmdetection#5512]
my_detector = TensorRTDetector(engine_file,class_names,device_id)
input_config = {
    'input_shape': (1,3,416,416),
    'input_path': 'my_images/00063.jpg',
    'normalize_cfg': {
        'mean': (123.675, 116.28, 103.53),
        'std': (58.395, 57.12, 57.375)
        }
}
one_img, one_meta = preprocess_example_input(input_config)
outputs = my_detector.forward_test(one_img,one_meta)

I use the above code to do inference with trt file, but it shows me the error:
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1128, condition: engineDims.nbDims == dimensions.nbDims
terminate called without an active exception
Aborted (core dumped)

I use the bellow command to convert pth model to onnx model:
`python tools/deployment/pytorch2onnx.py configs/yolo/yolov3_d53_mstrain-416_273e_coco.py checkpoints/yolov3_d53_mstrain-416_273e_coco-2b60fcd9.pth --output-file my_onnx/yolov3.onnx --shape 416 416`
and use the below command to convert onnx model to trt model:
`python tools/deployment/onnx2tensorrt.py configs/yolo/yolov3_d53_mstrain-416_273e_coco.py my_onnx/yolov3.onnx --trt-file my_trt/yolov3.trt --shape 416 416`

I didn't change the config file.

**Comment by RunningLeon** [comment]
@BChunlei You could add `--verify` to `onnx2tensorrt.py` and check if it breaks while doing inference with TensorRT.

**Comment by BChunlei** [comment]
Hi, @RunningLeon , when I add --verify to onnx2tensorrt.py, it shows me:

Successfully created TensorRT engine: my_trt/yolov3.trt
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 254, in <module>
    verbose=args.verbose)
  File "tools/deployment/onnx2tensorrt.py", line 58, in onnx2tensorrt
    onnx_model = ONNXRuntimeDetector(onnx_file, CLASSES, device_id=0)
  File "/root/bcl/projects/mmdetection/mmdet/core/export/model_wrappers.py", line 113, in __init__
    session_options.register_custom_ops_library(ort_custom_op_path)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Failed to load library /root/bcl/downloads/mmcv/mmcv/_ext_ort.cpython-37m-x86_64-linux-gnu.so with error: libonnxruntime.so.1.5.1: cannot open shared object file: No such file or directory

what's the problem?thanks.

**Comment by RunningLeon** [comment]
@BChunlei You could install mmcv-full with onnxruntime custom ops according to the doc:
https://github.com/open-mmlab/mmcv/blob/master/docs/deployment/onnxruntime_op.md#how-to-build-custom-operators-for-onnx-runtime

```
MMCV_WITH_OPS=1 MMCV_WITH_ORT=1 MMCV_WITH_TRT=1 pip install -e .
```

**Comment by BChunlei** [comment]
@RunningLeon, I solve that problem. Anothor problem occurs when I add --verify to onnx2tensorrt.py:

/root/bcl/projects/mmdetection/mmdet/core/export/model_wrappers.py:156: UserWarning: `output_names` is deprecated and will be removed in future releases.
  warnings.warn('`output_names` is deprecated and will be removed in '
/root/bcl/downloads/mmcv/mmcv/tensorrt/tensorrt_utils.py:233: UserWarning: TRTWraper will be deprecated in future. Please use TRTWrapper instead
  warnings.warn('TRTWraper will be deprecated in'
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 254, in <module>
    verbose=args.verbose)
  File "tools/deployment/onnx2tensorrt.py", line 101, in onnx2tensorrt
    o_res, p_res, rtol=1e-03, atol=1e-05, err_msg=err_msg)
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1529, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/root/anaconda3/envs/torch160trt7216/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 842, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05
The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the exported ONNX model is problematic.
Mismatched elements: 36 / 140 (25.7%)
Max absolute difference: 318.2661
Max relative difference: 1.
 x: array([[ 1.350758e+02,  9.312284e+01,  1.420624e+02,  1.062235e+02,
         1.245209e-01],
       [ 2.959424e+01,  1.121212e+02,  3.878238e+01,  1.400185e+02,...
 y: array([[ 1.350758e+02,  9.312284e+01,  1.420624e+02,  1.062235e+02,
         1.245213e-01],
       [ 2.959424e+01,  1.121212e+02,  3.878238e+01,  1.400185e+02,...

What's the meaning of this? The .trt file is generated, but when I do reference, it still shows me the error:

[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1128, condition: engineDims.nbDims == dimensions.nbDims.

**Comment by RunningLeon** [comment]
@BChunlei You create a TensorRT engine that feeds images of shape 416x416. So check your input image shape and make sure it is 416x416. If you want to create TensorRT engine with dynamic shapes, you have to feed `--min-shape` and `--max-shape` to `onnx2tensorrt.py`.

**Comment by BChunlei** [comment]
Hi @RunningLeon, I use the command 'python tools/deployment/onnx2tensorrt.py configs/yolo/yolov3_d53_mstrain-416_273e_coco.py my_onnx/yolov3.onnx --trt-file my_trt/yolov3.trt --shape 416 416 --input-img demo/demo-416.jpg --verify'. The input-img is 416*416

**Comment by RunningLeon** [comment]
@BChunlei Not sure based on the trace message, and maybe you could use gdb to debug a little bit.

**Comment by RunningLeon** [comment]
Hi, has this problem been solved by far?

**Comment by chuong98** [comment]
@RunningLeon 
I have the same error while convert `cascade_rcnn_r50_fpn_1x_coco.py`. The onnx and tensorrt models are created successfully, despite having error when verifying. 

> AssertionError: 
> Not equal to tolerance rtol=0.001, atol=1e-05
> The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the exported ONNX model is problematic.
> (shapes (45, 5), (3, 5) mismatch)
>  x: array([[7.509468e+02, 2.020876e+02, 7.657206e+02, 2.362118e+02,
>         1.999978e-01],
>        [5.291816e+02, 1.873770e+02, 5.444387e+02, 2.101632e+02,...
>  y: array([[7.509468e+02, 2.020876e+02, 7.657206e+02, 2.362118e+02,
>         1.999966e-01],
>        [5.291816e+02, 1.873770e+02, 5.444387e+02, 2.101632e+02,...

- The `show-pt.png` is scaled into a square image, while the images `show-ort.pg` and `show-trt.png` are keep at the original ratio.  But the inference results are correct. 

However, when I try to evaluate the results on Coco Validate, I get the error, and the `mAP=0.01`. Here are my command to  convert `pytorch2onnx` and `onnx2trt` respectively. 
```
mim run mmdet pytorch2onnx $CFG $CKPT \
    --output-file ${OUTPUT_FILE} \
    --input-img ${INPUT_IMAGE_PATH} \
    --test-img ${TEST_IMAGE_PATH} \
    --opset-version 11 \
    --shape 800 1216 \
    --verify 
```
```
mim run mmdet onnx2tensorrt $CFG $MODEL \
    --trt-file ${TRT_FILE} \
    --input-img ${INPUT_IMAGE_PATH} \
    --workspace-size ${WORKSPACE_SIZE} \
    --shape 800 1216 \
    --verify 
```
My question is: how should I set the parameters for `shape`, `min-shape` and `max-shape` if I want to do evaluate on COCO ?

**Comment by chuong98** [comment]
I found that setting this setting gives me 40.1mAP, matching with the report.
```
mim run mmdet onnx2tensorrt $CFG $MODEL \
    --trt-file ${TRT_FILE} \
    --input-img ${INPUT_IMAGE_PATH} \
    --workspace-size ${WORKSPACE_SIZE} \
    --shape 800 1333 \
    --min-shape 400 400 \
    --max-shape 1600 1600 \
```

**Comment by RunningLeon** [comment]
@chuong98 Works for coco:
--shape 800 1333
--min-shape 352 352
--max-shape 1344 1344

> I found that setting this setting gives me 40.1mAP, matching with the report.
> 
> ```
> mim run mmdet onnx2tensorrt $CFG $MODEL \
>     --trt-file ${TRT_FILE} \
>     --input-img ${INPUT_IMAGE_PATH} \
>     --workspace-size ${WORKSPACE_SIZE} \
>     --shape 800 1333 \
>     --min-shape 400 400 \
>     --max-shape 1600 1600 \
> ```

**Comment by amdslgl** [comment]
hello, I have solved it,this is because trt‘s input dim is not suit for trt’s dim。so, we should check the trt from 
dim= engine.get_profile_shape(profile_id, input_name)[0], we must input the same dim.

**Comment by zhangyps** [comment]
> 你好，我已经解决了，这是因为trt的输入dim不符合trt的dim。所以，我们应该从 dim=engine.get_profile_shape(profile_id, input_name)[0]检查trt，必须输入相同的dim。

您好，我想问下，我在onnx转trt的时候已经设置了动态形状了，profile.set_shape(network.get_input(0).name, (1,3,160,160),(1,3,1280,1280), (1,3,48004800))，为什么会出现   engineDims.nbDims == Dimensions.nbDims。这个问题呢
