### ISSUE TITLE
voc to coco

### ISSUE THREAD

**Issue by ywj509** [open-mmlab/mmdetection#5516]
$ python tools/dataset_converters/pascal_voc.py ${/home/ligongdx/anaconda3/envs/open-mmlab/bin/python /home/ligongdx/YWJ/coco/mmdetection-master/data/VOCdevkit} [-h] [-o ${/home/ligongdx/anaconda3/envs/open-mmlab/bin/python /home/ligongdx/YWJ/coco/mmdetection-master/tuxiang}]
bash: ${/home/ligongdx/anaconda3/envs/open-mmlab/bin/python /home/ligongdx/YWJ/coco/mmdetection-master/data/VOCdevkit}: 错误的替换

I used the pascal_voc.py to change my dataset from voc to coco.But i failed.Can you tell me how can i do this?

**Comment by ywj509** [comment]
python tools/dataset_converters/pascal_voc.py ${data/VOCdevkit} [-h] [-o ${tuxiang}]
usage: pascal_voc.py [-h] [-o OUT_DIR] [--out-format {pkl,coco}] devkit_path
pascal_voc.py: error: unrecognized arguments: [-o ]
 
i have changed the path,

**Comment by BIGWangYuDong** [comment]
Hi, what command did you use?

**Comment by ywj509** [comment]
i have solved this problem

**Comment by JieZzzoo** [comment]
> 

you should add the ‘-o’
