### ISSUE TITLE
How to use backbone's pre-training weights to initialize the model during training? How to use the trained model of the network as a whole to initialize the weights?

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#5518]

**Comment by BIGWangYuDong** [comment]
How to use backbone's pre-training weights to initialize the model during training: [Follow this PR](https://github.com/open-mmlab/mmdetection/pull/5273)

How to use the trained model of the network as a whole to initialize the weights?  Use load_from key
