### ISSUE TITLE
Could you tell me how do I convert the iteration to the epoch?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#5520]
Hello dear author
Sorry to bother you
Could you tell me how do I convert `iterations` into `epochs`?
For example, the training_dataset has 12345 images, and the val_dataset has 1234 images
total_batch_sizes=12, repeat_dataset=5
If iteration_max=160000, how to calculate its corresponding epoch_max? 
Which formula does the conversion relationship between them follow?
Thank you!

**Comment by hhaAndroid** [comment]
max_epoch= (160000*total_batch_sizes)/(len(training_dataset)*repeat_num)

**Comment by zhongqiu1245** [comment]
Thank you！
