### ISSUE TITLE
How to do inference without mmcv?

### ISSUE THREAD

**Issue by likyoo** [open-mmlab/mmdetection#5522]
On a restricted platform, if I use mmcv, it takes me 20 minutes to compile it each time. So, is there any way to do inference without mmcv?I am testing on a restricted platform. If I use mmcv, it takes me 20 minutes to compile it each time. So, is there any way to do inference without mmcv?

**Comment by hhaAndroid** [comment]
Hi @likyoo This may be troublesome, because mmcv is the base dependent library. But if you export to onnx format, mmcv is not required.

**Comment by likyoo** [comment]
thanks
