### ISSUE TITLE
How can I get Mask Areas from Mask R-CNN results?

### ISSUE THREAD

**Issue by yoonj1n** [open-mmlab/mmdetection#5532]
Hi! I'm trying to get Mask R-CNN Model's Area of Results
I found some code about Areas at mmdet/core/mask/structures.py
but I don't know how to use it. please let me know how to get the area of the test result's mask area!!!!

**Comment by BIGWangYuDong** [comment]
Do you mean you want to show the mask area without BBox? Or you just want to use mask area to do something?

**Comment by vj697** [comment]
I wznt to use the mask area to make binary image , how can i get the  mask area?

**Comment by vj697** [comment]
How to get the mask area??

**Comment by BIGWangYuDong** [comment]
You can refer to here you can follow the example, 
https://github.com/open-mmlab/mmdetection/blob/595b51713d14288119412c6831f8cd50230adba2/mmdet/core/mask/structures.py#L201 

Also, you can refer to this,  to make a binary image:
https://github.com/open-mmlab/mmdetection/blob/595b51713d14288119412c6831f8cd50230adba2/mmdet/datasets/pipelines/loading.py#L307

**Comment by yoonj1n** [comment]
I just want to know the number of pixels or something that is a number in the mask area.
I want to know the size of the mask area compared to the original thing's size with the width of mask. For Example, if I designate a person's hand as a mask, i want to use the total size of the person to figure out the size of the hand.
Sorry to strange explanation because i'm not good at English.

**Comment by vj697** [comment]
@BIGWangYuDong  I am using demo code , i want to make binary image of the segmentation results , i mean i want predicted masks area to be 255 and remaining 0 , after getting the output.

**Comment by BIGWangYuDong** [comment]
@yoonj1n  
You can get the mask area first and then use some code to do what you want to do. 
What I understand is you need first get masks and then analyze the masks. For example, first, you get the hand mask and person mask, and then you can write a code to analyze these masks. Such as counting the number of pixels


Here is an example copy from pycocotools
```python
 elif 'segmentation' in anns[0]:
            res.dataset['categories'] = copy.deepcopy(self.dataset['categories'])
            for id, ann in enumerate(anns):
                # now only support compressed RLE format as segmentation results
                ann['area'] = maskUtils.area(ann['segmentation'])
                if not 'bbox' in ann:
                    ann['bbox'] = maskUtils.toBbox(ann['segmentation'])
                ann['id'] = id+1
                ann['iscrowd'] = 0
```

> I just want to know the number of pixels or something that is a number in the mask area.
> I want to know the size of the mask area compared to the original thing's size with the width of mask. For Example, if I designate a person's hand as a mask, i want to use the total size of the person to figure out the size of the hand.
> Sorry to strange explanation because i'm not good at English.

**Comment by BIGWangYuDong** [comment]
> @BIGWangYuDong I am using demo code , i want to make binary image of the segmentation results , i mean i want predicted masks area to be 255 and remaining 0 , after getting the output.

You can debug the code, I seem to remember the binary image only get `true` or `false` these two types.

**Comment by vj697** [comment]
@BIGWangYuDong , Where is the segmented mask output stored ??

**Comment by BIGWangYuDong** [comment]
Hmmm, here is an example, mask pred is the mask output
https://github.com/open-mmlab/mmdetection/blob/595b51713d14288119412c6831f8cd50230adba2/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py#L178

**Comment by BIGWangYuDong** [comment]
You can debug your code, and remember to set workers_per_gpu=0 while debugging.

**Comment by BIGWangYuDong** [comment]
For getting area in mmdet, you can use 
https://github.com/open-mmlab/mmdetection/blob/595b51713d14288119412c6831f8cd50230adba2/mmdet/core/mask/structures.py#L498-L500

**Comment by yoonj1n** [comment]
Thanks, but i'm already know structures.py code but still i don't know how to use areas code in structures.py 
i want to use my results that getting by test.py to get area.

**Comment by BIGWangYuDong** [comment]
Please follow the examples in structures.py and you can debug your code to have a try

**Comment by vj697** [comment]
Thanks you, Can you tell me how to use mask predicted in demo code ??

**Comment by vj697** [comment]
@BIGWangYuDong  please , can you tell me how should i use mask predicted in demo code?

**Comment by BIGWangYuDong** [comment]
I do suggest you run the train or test code in tools

**Comment by BIGWangYuDong** [comment]
It's hard to tell you the details, if you do want to use demo.py, more details you need to read and debug the code, the main codes of demo are in mmdet/apis/inference.py. Meanwhile, you need to have a look at mmdet/models/detectors etc.

**Comment by yoonj1n** [comment]
i have one more question, can i use the result mask predicted in test.py?
