### ISSUE TITLE
AP drops heavily when upgrade model from v1.x to v2.x

### ISSUE THREAD

**Issue by Furyboyy** [open-mmlab/mmdetection#5533]
I tried to test the model I trained in v1.x in v2.x. Then I found all models drop heavily. Some AP drop 10%, Some even drops more than 30%.

visualizing the detect image, I found the cls probability are the same. but the bounding box locates worse in v2.x

![92-mm](https://user-images.githubusercontent.com/52880658/124458041-1b36cb80-ddbf-11eb-860b-3434c6199cad.jpg)

![92-ys](https://user-images.githubusercontent.com/52880658/124458061-238f0680-ddbf-11eb-976e-a53df9e89db0.jpg)

Converting the pth file using script in `tools/model_converters/upgrade_model_version.py` makes it even worse.
![moto_demo_out](https://user-images.githubusercontent.com/52880658/124458129-36094000-ddbf-11eb-998d-b87a7f034cfb.jpg)

Here is my config file
```
model = dict(
    type='RetinaNet',
    pretrained='mnasnet1_0',
    backbone=dict(type='MNASNetBackbone', alpha=1.0),
    neck=dict(
        type='BiFPN',
        in_channels=[40, 96, 320],  
        target_size_list=[52, 26, 13],  
        out_channels=64,
        stack=2,
        start_level=0,
        norm_cfg=norm_cfg,
        num_outs=3),
    bbox_head=dict(
        type='RetinaHead',
        num_classes=2,  
        in_channels=64,  ,
        stacked_convs=2, 
        feat_channels=64,  
        anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[0.5, 1.0, 2.0],
            strides=[8, 16, 32] 
        ),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[0.1, 0.1, 0.2,
                         0.2]  
        ),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=0.75)),
      train_cfg=dict(
          assigner=dict(
              type='MaxIoUAssigner',
              pos_iou_thr=0.5,
              neg_iou_thr=0.4,
              min_pos_iou=0,
              ignore_iof_thr=-1),
          allowed_border=-1,
          pos_weight=-1,
          debug=False),
      test_cfg=dict(
          nms_pre=1000,
          min_bbox_size=0,
          score_thr=0.05,
          nms=dict(type='nms', iou_thr=0.5),
          max_per_img=100))
```

**Comment by BIGWangYuDong** [comment]
Did you use the same checkpoint file and same config file?

**Comment by Furyboyy** [comment]
> Did you use the same checkpoint file and same config file?

yes, I also change 'AnchorGenerator' to 'LegacyAnchorGenerator', but get the same results.

When I change 'DeltaXYWHBBoxCoder' to 'DeltaXYWHBBoxCoder', it raise `RuntimeError: The size of tensor a (4) must match the size of tensor b (1000) at non-singleton dimension 2`

**Comment by ZwwWayne** [comment]
Please check the steps here https://github.com/open-mmlab/mmdetection/tree/master/configs/legacy_1.x and check the documentation https://mmdetection.readthedocs.io/en/latest/compatibility.html#compatibility-with-mmdetection-1-x
Some keys need to by modified more than change the type of anchor generator.

**Comment by Furyboyy** [comment]
> Please check the steps here https://github.com/open-mmlab/mmdetection/tree/master/configs/legacy_1.x and check the documentation https://mmdetection.readthedocs.io/en/latest/compatibility.html#compatibility-with-mmdetection-1-x
> Some keys need to by modified more than change the type of anchor generator.

I notice that all the bbox_box are a bit left-top compared to the old version, so I think the change of coordinates system may cause my problem. The coordinates calculation code is in the mmdetection, How can I apply the old coordinate system in v2.x？
