### ISSUE TITLE
norm_cfg  and conv_cfg

### ISSUE THREAD

**Issue by HaoGuo98** [open-mmlab/mmdetection#5534]
Can i use these dict to set 3d conv and 3d bn? Such as conv_cfg=dict(type='Conv3d'), norm_cfg=dict(type='BN3d')?

**Comment by BIGWangYuDong** [comment]
Yes you can, more details can refer to
https://github.com/open-mmlab/mmcv/blob/4a9f83467ce677b59c2c8abfa968c4925623374e/mmcv/cnn/bricks/conv.py#L11 
and
https://github.com/open-mmlab/mmcv/blob/4a9f83467ce677b59c2c8abfa968c4925623374e/mmcv/cnn/bricks/norm.py#L71
