### ISSUE TITLE
Saving mmdetection model

### ISSUE THREAD

**Issue by FirasKedidi** [open-mmlab/mmdetection#5535]
Hello,
I've trained a model using mmdetection and exported using pytorch static dict method but i couldn't use it for inference because i don't have a class model to create an instance from 

![image](https://user-images.githubusercontent.com/58661767/124480992-bae46180-dd9f-11eb-83fb-9824e581917a.png)

what can i do ??

**Comment by hhaAndroid** [comment]
Hi @FirasKedidi If you don’t want to build a pytorch model, you can choose to export it as onnx, otherwise you can directly use demo/image_demo.py to inference.

**Comment by FirasKedidi** [comment]
> Hi @FirasKedidi If you don’t want to build a pytorch model, you can choose to export it as onnx, otherwise you can directly use demo/image_demo.py to inference.
I didn't know about image_demo.py .
I tried it but for some reason the image is not showing on 

![image](https://user-images.githubusercontent.com/58661767/124571449-b2436800-de3f-11eb-84e6-2cb5e8ba1598.png)
