### ISSUE TITLE
different results between inference_detector and generate_inputs_and_wrap_model

### ISSUE THREAD

**Issue by ChicoQ** [open-mmlab/mmdetection#5539]
I've tried a few models so far. The inference_detector result looks good but the result from (model, _) = generate_inputs_and_wrap_model() not that much. Have anyone met same issue before? Please direct me if there's something wrong. Many thanks.

**Comment by hhaAndroid** [comment]
Hi @ChicoQ This is because the pre-processing strategy is different, which has no effect on the export result.

**Comment by ChicoQ** [comment]
Thanks @hhaAndroid for your explanation. That's really helpful.
