### ISSUE TITLE
ImportError: undefined symbol and AssertionError: border_align_forward miss in moudle _ext

### ISSUE THREAD

**Issue by ludabai** [open-mmlab/mmdetection#5541]
(1) When I try to collect envs using the command: python mmdet/utils/collect_env.py, I got an ImportError: 
/home/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE.

Details:
Traceback (most recent call last):
  File "mmdet/utils/collect_env.py", line 15, in <module>
    for name, val in collect_env().items():
  File "mmdet/utils/collect_env.py", line 9, in collect_env
    env_info = collect_base_env()
  File "/home/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/env.py", line 85, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/.conda/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

(2)When I want to run a demo under the latest mmdetection version, I got an AssertionError: border_align_forward miss in moudle _ext.

Details:
![mmcv-error](https://user-images.githubusercontent.com/30382349/124544305-74533d80-de59-11eb-8f5e-24e124fd792c.png)

My failed fix method: Check and upgrade mmdet and mmcv to the latest version, upgrade cuda and gcc, however the gcc installing process failed. I think the problem may caused by the  incompatibility, maybe it's realted to gnu, gcc etc. But I still cannot figure out the exact incompatible part and the correct method to fix it.

**Comment by RangiLyu** [comment]
The `undefined symbol` error may be because your c++ runtime is different from the c++ version which compiling mmcv. One solution is adding the correct version of libstdc++.so into LD_PRELOAD environment variables.

**Comment by ludabai** [comment]
Thank you. I see, maybe it's because that my gcc version is too low to compile the mmcv. Using the command "gcc --version", I got my gcc version of 4.7.4, which is lower than the needed GCC 5+. I will try to install a satisfied version of gcc and see what happens next.

**Comment by Cavaradossi** [comment]
Did u fixed the problem by updating GCC, my GCC version is 7.5.0 and I have the same error
