### ISSUE TITLE
inference result in json format 

### ISSUE THREAD

**Issue by FirasKedidi** [open-mmlab/mmdetection#5548]
Hello,
I want to get the inference result in a json file or coco format.
Is that possible ??

**Comment by AronLin** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md#test-without-ground-truth-annotations

**Comment by FirasKedidi** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md#test-without-ground-truth-annotations

I tried this one but he kept asking for the annotation for the test dataset.

**Comment by AronLin** [comment]
The annotation file is necessary, but the 'annotations' in the json file can be empty.
We need the other two keys 'images" and 'categories' to format the results.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Firas ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 中午1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmdetection] inference result in json format  (#5548)





  
https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md#test-without-ground-truth-annotations
  
I tried this one but he kept asking for the annotation for the test dataset.

**Comment by FirasKedidi** [comment]
> The annotation file is necessary, but the 'annotations' in the json file can be empty. We need the other two keys 'images" and 'categories' to format the results.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Firas ***@***.***&gt;; 发送时间: 2021年7月8日(星期四) 中午1:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [open-mmlab/mmdetection] inference result in json format (#5548) https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md#test-without-ground-truth-annotations I tried this one but he kept asking for the annotation for the test dataset. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

ah okay i get it thanks

**Comment by Kangzf1996** [comment]
> The annotation file is necessary, but the 'annotations' in the json file can be empty. We need the other two keys 'images" and 'categories' to format the results.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Firas ***@***.***&gt;; 发送时间: 2021年7月8日(星期四) 中午1:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [open-mmlab/mmdetection] inference result in json format (#5548) https://github.com/open-mmlab/mmdetection/blob/master/docs/1_exist_data_model.md#test-without-ground-truth-annotations I tried this one but he kept asking for the annotation for the test dataset. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

Well, I'm not clear about your idea. The json file is empty, how will the other two keys 'images" and 'categories' be used in inference? It's ok if I just mkdir an annotations file? Thank you!
