### ISSUE TITLE
About parameters in DCN API?

### ISSUE THREAD

**Issue by shivin9** [open-mmlab/mmdetection#555]
Hi,

I wanted to know about the `deformable_groups` parameter in the DCN api and the `offset`parameter in the forward function.

Thanks,
Shivin

**Comment by hellock** [comment]
You may refer to the DCN [paper](https://arxiv.org/abs/1703.06211). `offset` is the same as the offset denoted in the paper, and `deformable_groups` means splitting all channels to several groups and different offsets are learned for each group.
