### ISSUE TITLE
training is slow!!!

### ISSUE THREAD

**Issue by HaoGuo98** [open-mmlab/mmdetection#5553]
I try to use my backbone to replace resnet in faster rcnn. The model with replaced backbone can run but it is **quite slow**(about 3 times slower than expectation.) **If it is because i write my backbone without mm libs?** it is noticed than then resnet in mm use  build_from_conv these things to replace nn.conv. If it is necessary for me to rewrite my backbone using mmcv???

**Comment by AronLin** [comment]
It is not necessary to write your backbone with MMCV.
Is your backbone a large network?
Can you show your config file to me?

**Comment by HaoGuo98** [comment]
![image](https://user-images.githubusercontent.com/42510628/124726604-7b08b000-df40-11eb-8fd8-0822e28bfe2b.png)
I have add my backbone in the init.py in the dir mmdet/backbone.

**Comment by HaoGuo98** [comment]
The speed of my backbone is similar to resnet without mm toolkit.

**Comment by HaoGuo98** [comment]
![image](https://user-images.githubusercontent.com/42510628/124727795-9d4efd80-df41-11eb-9a77-6759cbc69e18.png)
this is part of my backbone, it is similar to regular resnet without mm toolkit.

**Comment by xiaoshuomin** [comment]
@HaoGuo98 can you tell me how to add new backbone?I have some problems that I can't solve for a long time.

**Comment by xiaoshuomin** [comment]
@HaoGuo98 can you tell me how to add new backbone?I have some problems that I can't solve for a long time.

**Comment by HaoGuo98** [comment]
I just follow the tutorial.
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_models.md

> @HaoGuo98 can you tell me how to add new backbone?I have some problems that I can't solve for a long time.

**Comment by AronLin** [comment]
You use the 3D convolutions, right? It is an operation taking a lot of time. I guess that your kernel size on time dimension is 3 so that the backbone takes 3 times as long.

**Comment by HaoGuo98** [comment]
But , the **extra time** cost by 3d conv is  0.5~1 times  of regular resnet **without mm**.  And now with mm, we take 4 times training time.

**Comment by HaoGuo98** [comment]
Now i even rewrite my code in the format of resnet in MM and use build_conv_layer these classes. I meet this error.i can run my code if i set find_unused_parameter = True in the train.py, but it is still slow as the same.
![image](https://user-images.githubusercontent.com/42510628/124872366-c336d980-dff7-11eb-9bd5-455f59d8be59.png)

**Comment by AronLin** [comment]
In theory, whether to use MMCV or not does not affect the speed. You can send us the source code and provide information to reproduce this problem.  Or it is difficult for us to know what happened.

**Comment by HaoGuo98** [comment]
So if the find_unused_parameter = True will affect the training time?

**Comment by HaoGuo98** [comment]
I solve it by do not use for loop and if statement... Any explanation?
![image](https://user-images.githubusercontent.com/42510628/125582067-9b77f6f6-1461-46e1-a1fd-8739f71653c1.png)

**Comment by AronLin** [comment]
New codes avoid a lot of jump instructions.
But it should not affect so much time if this code segment is in the initialization progress.

**Comment by HaoGuo98** [comment]
I guess since these operations belong to Python's build-in operation, and in the for loop, it will speed up memory consumption,  then Python will periodically use GC to do memory collection?
