### ISSUE TITLE
How can I change the anchor ratio in atss

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#5563]
does atss support the more anchor ratio?

**Comment by AronLin** [comment]
You can try to set the `ratios` in the anchor generator in the config files.
We support setting different ratios， but we are not sure whether the results will be better.
You can discuss this issue with the authors of the paper, or do an ablation study by yourself with our code base.

**Comment by mmeendez8** [comment]
You can also try pyodi for this :hammer: 

Check discussions [here](https://github.com/open-mmlab/mmdetection/discussions/5666)
