### ISSUE TITLE
no such file when exporting cascade model

### ISSUE THREAD

**Issue by ChicoQ** [open-mmlab/mmdetection#5570]
@jshilong I've tried branch onnx-cascade but got this exception,

%3315 : Long(1:100, 100:1, 1:1, requires_grad=0, device=cpu) = onnx::Gather[axis=0](%3313, %3314) # mmdetection/mmdet/core/export/onnx_helper.py:192:0
%3317 : Tensor = onnx::Unsqueezeaxes=[0]
%3319 : Tensor = onnx::Concat[axis=0](%3317, %3668)
%labels : Long(1:100, 100:1, requires_grad=0, device=cpu) = onnx::Reshape(%3315, %3319) # mmdetection/mmdet/core/export/onnx_helper.py:193:0
%3321 : Float(1:100, 100:1, 1:1, requires_grad=1, device=cpu) = onnx::Unsqueezeaxes=[2] # mmdetection/mmdet/core/export/onnx_helper.py:195:0
%dets : Float(1:500, 100:5, 5:1, requires_grad=1, device=cpu) = onnx::Concat[axis=2](%3311, %3321) # mmdetection/mmdet/core/export/onnx_helper.py:196:0
return (%dets, %labels)

No such file ''

with this command line python tools/deployment/pytorch2onnx.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_voc0712.py work_dirs/cascade_rcnn_r50_fpn_1x_voc0712/epoch_12.pth --output-file cascade_rcnn_r50_fpn_1x_voc0712_8July.onnx --input-img temp.jpg --shape 1000 600 --mean 123.675 116.28 103.53 --std 58.395 57.12 57.375 --simplify --verify --show --dataset voc --dynamic-export

**Comment by jshilong** [comment]
Sorry, I can not reproduce your problem.
Is there any modification to the code?

**Comment by ChicoQ** [comment]
It's running as expected if without 'simplify'.

Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 308, in <module>
    dynamic_export=args.dynamic_export)
  File "tools/deployment/pytorch2onnx.py", line 176, in pytorch2onnx
    o_res, p_res, rtol=1e-03, atol=1e-05, err_msg=err_msg)
  File "/home/chico/.local/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/chico/.local/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 759, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05
The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the exported ONNX model is problematic.
(shapes (96, 5), (13, 5) mismatch)
 x: array([[6.217845e+01, 8.446675e+02, 2.583917e+02, 8.877766e+02,
        9.886150e-01],
       [6.285159e+01, 7.821144e+02, 2.019757e+02, 8.179300e+02,...
 y: array([[6.217845e+01, 8.446675e+02, 2.583917e+02, 8.877766e+02,
        9.886150e-01],
       [6.285159e+01, 7.821144e+02, 2.019757e+02, 8.179300e+02,...

**Comment by RunningLeon** [comment]
@ChicoQ Hi, `--simplify` and `--dynamic-export` cannot work at the same time for `pytorch2onnx.py`
