### ISSUE TITLE
在进行可视化的时候，num_iters_per_epoch经常出错，得到的结果图是错误的

### ISSUE THREAD

**Issue by liuyuan000** [open-mmlab/mmdetection#5571]
默认训练一次，测试一次，但是在可视化绘图的时候，默认第一次没有训练。
修改建议：
将anglyze_logs.py的第68行附近的num_iters_per_epoch的初始化赋值修改为：
```
                if log_dict[epochs[0]]['mode'][-1]=='val':
                    num_iters_per_epoch = log_dict[epochs[0]]['iter'][-2]
                else:
                    num_iters_per_epoch = log_dict[epochs[0]]['iter'][-1]
```

**Comment by HappyPeanuts** [comment]
你好，请教一下，我现在想在我的模型中使用TTFNet的TTFHead，我应该择那么操作，我现在的虚拟环境中已经安装好了mmdet，我是否需要在自己的项目中将mmdet文件夹放在我自己的项目里边，具体放在什么位置，应该如何调用，希望你能给一点点建议，非常感谢

**Comment by liuyuan000** [comment]
> 你好，请教一下，我现在想在我的模型中使用TTFNet的TTFHead，我应该择那么操作，我现在的虚拟环境中已经安装好了mmdet，我是否需要在自己的项目中将mmdet文件夹放在我自己的项目里边，具体放在什么位置，应该如何调用，希望你能给一点点建议，非常感谢

不好意思 我也是只会一些基础操作

**Comment by HappyPeanuts** [comment]
好吧，不过还是非常感谢你能回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月25日(星期天) 晚上11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] 在进行可视化的时候，num_iters_per_epoch经常出错，得到的结果图是错误的 (#5571)





  
你好，请教一下，我现在想在我的模型中使用TTFNet的TTFHead，我应该择那么操作，我现在的虚拟环境中已经安装好了mmdet，我是否需要在自己的项目中将mmdet文件夹放在我自己的项目里边，具体放在什么位置，应该如何调用，希望你能给一点点建议，非常感谢
  
不好意思 我也是只会一些基础操作

**Comment by jshilong** [comment]
Thanks for your bug reporting, please @hhaAndroid take a look at this issue, Seems we have fixed this bug before.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
