### ISSUE TITLE
Hrnet feature stride is not align with focs head

### ISSUE THREAD

**Issue by wywywy01** [open-mmlab/mmdetection#5574]
I saw hrnet-fcos, the default head stride is (8,16,32,64,128) [link](https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py#L34) , while the output feature of hrfpn is stride (4，8, 16, 32, 64)[link](https://github.com/open-mmlab/mmdetection/blob/master/configs/hrnet/fcos_hrnetv2p_w32_gn-head_4x4_1x_coco.py).

**Comment by jshilong** [comment]
The start level of `FPN` is 1 in FCOS and other one-stage detector

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
