### ISSUE TITLE
Error in running demo in Windows

### ISSUE THREAD

**Issue by scar-on** [open-mmlab/mmdetection#5580]
The following error occurred when running demo on Windows：
“    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。”
（pytorch1.9+cuda10.2）
email（1597763078@qqcom）

**Comment by AronLin** [comment]
If you met a Pytorch installation problem, you should go to Pytorch to raise an issue.
I found this issue in Pytorch, here is the link:
https://github.com/pytorch/pytorch/issues/17203

**Comment by zeqianl** [comment]
我也遇到了同样的问题，然后发现是我装错了mmcv
I have the same problem as you. I found that I had installed the mmcv for cu111 and torch=1.8. 
So, I uninstalled mmcv, ran that: 
`pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.8.0/index.html`
