### ISSUE TITLE
Why is the grad_fn "AddBackward0" instead of "CudnnConvolutionBackward"

### ISSUE THREAD

**Issue by johnson-magic** [open-mmlab/mmdetection#5584]
Hi, Can you help me ? 
I am debuging the mmdetection source code with pdb. When i viewed the fpn code, I found a strange debug info. See the snapshot picture below, please. As the picture showing, self.lateral_convs[0] is a Conv2d, I think a tensor inputs[1] inputs into the module, the result self.lateral_convs[0](inputs[1]).grad_fn should be CudnnConvolutionBackward. Why it is AddBackward0 ? 
the code is in file fpn.py, line 151~159
    

         # build laterals
        laterals = [
            lateral_conv(inputs[i + self.start_level])
            for i, lateral_conv in enumerate(self.lateral_convs)
        ]
![image](https://user-images.githubusercontent.com/19408186/125168191-c20fd300-e1d6-11eb-9cde-cd686960b6ea.png)

**Comment by jshilong** [comment]
+ bias

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
