### ISSUE TITLE
Urgent Help please!!!!

### ISSUE THREAD

**Issue by adnanenasser** [open-mmlab/mmdetection#5586]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?
I try to train my model VfNet, i have all the configuration done, except the GPU that i cannot get. when i execute my **sbatch**, i get an error that says **RuntimeError : No CUDA GPUs are available.**

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I have modified the config file of vfnet model, but it doesn't create a problem for me.
3. What dataset did you use?
I train on a custom dataset, that under the coco dataset format.
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
That are my Environment Information
Collecting environment information... PyTorch version: 1.9.0+cu102 Is debug build: False CUDA used to build PyTorch: 10.2 ROCM used to build PyTorch: N/A  OS: Gentoo Base System release 2.6 (x86_64) GCC version: (GCC) 9.3.0 Clang version: Could not collect CMake version: version 3.16.5 Libc version: glibc-2.30  Python version: 3.8 (64-bit runtime) Python platform: Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-glibc2.2.5 Is CUDA available: False CUDA runtime version: No CUDA GPU models and configuration: No CUDA Nvidia driver version: No CUDA cuDNN version: No CUDA HIP runtime version: N/A MIOpen runtime version: N/A  Versions of relevant libraries: [pip3] numpy==1.20.2 [pip3] torch==1.9.0 [pip3] torchaudio==0.8.1 [pip3] torchtext==0.9.1 [pip3] torchvision==0.9.1 [conda] Could not collect
2. You may add addition that may be helpful for locating the problem, such as
    - I am using the MMdetection Toolbox and training on compute canada ressources
    - I am new to Deep Learning, and i don't have a very good background on linux, i am used to work on kaggle.
    

**Error traceback**
If applicable, paste the error trackback here.

```/lustre03/project/6019320/adnen/project_dnd/mmdetection/mmdet/core/anchor/builder.py:15: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator``
  warnings.warn(
loading annotations into memory...
Done (t=0.18s)
creating index...
index created!
Traceback (most recent call last):
  File "VfNet_training.py", line 54, in <module>
    train_detector(model, datasets[0], cfg, distributed=False, validate=True)
  File "/lustre03/project/6019320/adnen/project_dnd/mmdetection/mmdet/apis/train.py", line 85, in train_detector
    model.cuda(cfg.gpu_ids[0]), device_ids=cfg.gpu_ids)
  File "/home/adnen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/adnen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/adnen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/adnen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/adnen/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 637, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/adnen/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
It seems that it cannot find GPU. Do you have GPU on your machine?
