### ISSUE TITLE
The output of Darknet is inf

### ISSUE THREAD

**Issue by MSTK2014** [open-mmlab/mmdetection#5588]
When I trained YOLO v3, I found that the output of Darknet started with e-2 or e-1, then it quickly became e0, e1, e2,..., e35,..., finally, it became inf. 
This happened during the output from Darknet of the first image. That's to say, it happened before the first backward procedure.
I found this in the forward function of the class ResBlock in darknet.py.

    def forward(self, x):
        residual = x
        out = self.conv1(x)
        out = self.conv2(out)
        out = out + residual

        return out

I re-downloaded the file darknet53-a628ea1b.pth, but this still exists.

**Comment by ZwwWayne** [comment]
Hi @MSTK2014 ,
Could you use the reimplementation template to describe your issue in detail? For example, what config/command you use, what is your data?
