### ISSUE TITLE
What is the form and meaning of 'counts'?

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#5589]
python tools/test.py model.py checkpoint.pth --format-only --options "jsonfile_prefix=./results"

What is the '"segmnetation" : {"counts" : "_____" }' in the segm.json file obtained by executing the above command?
And what is the form of it?

**Comment by PeterVennerstrom** [comment]
"Counts" is an encoding of the mask in RLE format.
