### ISSUE TITLE
The regression loss in centerNet(object as points) doesnt choose positive sample 

### ISSUE THREAD

**Issue by igo312** [open-mmlab/mmdetection#5590]
In the centerNet(object as keypoints). I find the regression loss is directly calculated instead of selecting the positive sample. It confuses me, I think there should be a index mask to choose positive sample. Or any detail I have missed?
```
loss_wh = self.loss_wh(
            wh_pred,
            wh_target,
            wh_offset_target_weight,
            avg_factor=avg_factor * 2)
```

**Comment by PeterVennerstrom** [comment]
The wh_offset_target_weight serves the purpose of an index mask to choose positive samples.  The loss function multiplies the calculated loss by the target_weight before reducing it.  In Centernet's case, the target_weight is either 0 or 1.

Other detectors use continuous values to weight the loss, e.g. TTFNet uses the gaussian heat map values to weight the loss.

**Comment by igo312** [comment]
@PeterVennerstrom you are right. thank you!
