### ISSUE TITLE
添加模块，mAP下降

### ISSUE THREAD

**Issue by dailonggang** [open-mmlab/mmdetection#5596]
在Faster R-CNN中添加了OHEM后，在VOC数据集得到的mAP反而下降了，请问一下这是什么原因造成的？

**Comment by hhaAndroid** [comment]
Hi @dailonggang The reason is not easy to say, it may be the parameters or the need for longer training time, etc.

**Comment by HappyPeanuts** [comment]
你好，请教一下，我现在想在我的模型中使用TTFNet的TTFHead，我应该择那么操作，我现在的虚拟环境中已经安装好了mmdet，我是否需要在自己的项目中将mmdet文件夹放在我自己的项目里边，具体放在什么位置，应该如何调用，希望你能给一点点建议，非常感谢

**Comment by hhaAndroid** [comment]
@HappyPeanuts You only need `import mmdet`   and register the head module in your project. You can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs_zh-CN/3_exist_data_new_model.md
