### ISSUE TITLE
训练后评估报错

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#5598]
你好！我用mmdet2.12版本训练自己的数据集，使用的YOLOv3，设置训练10轮后保存模型并进行评估，但是一到评估环节就报错：RuntimeError: CUDA error: no kernel image is available for execution on the device。然后训练终止，我的环境配置是CUDA11.2, pytorch=1.8.1，显卡是3090，请问有什么办法解决吗？谢谢！

**Comment by hhaAndroid** [comment]
Hi @chensen668 This is really weird, there is no problem with training.

**Comment by CangHaiQingYue** [comment]
@chensen668    我也遇到相同的问题了，大佬解决了吗

**Comment by chensen668** [comment]
> @chensen668 我也遇到相同的问题了，大佬解决了吗

你的环境跟我一样吗？我是把mmcv-full版本提高到1.3.8，就正常了

**Comment by chensen668** [comment]
> @chensen668 我也遇到相同的问题了，大佬解决了吗

你的环境跟我一样吗？我是把mmcv-full版本提高到1.3.8，就正常了

**Comment by CangHaiQingYue** [comment]
@chensen668 我是用了两张不同型号的卡训练。  换回来后问题解决了。
谢谢大佬回复。

**Comment by HUBUwg96** [comment]
> 你好！我用mmdet2.12版本训练自己的数据集，使用的YOLOv3，设置训练10轮后保存模型并进行评价，但是一到评价环节:CUDA就报error error no image available is image execution is在设备上。然后培训最终停止，我的环境配置是CUDA11.2，pytorch=1.8.1，显卡是3090，请问有什么办法解决吗？谢谢！

你好 大佬 我是3090的显卡 cuda11.2，但是我死活配不出环境 可以把你的环境详细的发一份给我吗 万分感谢

**Comment by sanmulab** [comment]
好久远了，你可以尝试稍微升级一下mmcv-full的版本。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月10日(周二) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmdetection] 训练后评估报错 (#5598)




  
你好！我用mmdet2.12版本训练自己的数据集，使用的YOLOv3，设置训练10轮后保存模型并进行评价，但是一到评价环节:CUDA就报error error no image available is image execution is在设备上。然后培训最终停止，我的环境配置是CUDA11.2，pytorch=1.8.1，显卡是3090，请问有什么办法解决吗？谢谢！
  
你好 大佬 我是3090的显卡 cuda11.2，但是我死活配不出环境 可以把你的环境详细的发一份给我吗 万分感谢
