### ISSUE TITLE
How to merge local modified mmdetection with recent released mmdetection？

### ISSUE THREAD

**Issue by noobying** [open-mmlab/mmdetection#5599]
mentioned above.

**Comment by hhaAndroid** [comment]
If you use it directly, then `git pull origin master`.
If you are the fork version, then 
```shell
git remote add upstream https://github.com/open-mmlab/mmdetection
git fetch upstream
git pull upstream master

**Comment by noobying** [comment]
> If you use it directly, then `git pull origin master`.
> If you are the fork version, then
> 
> ```shell
> git remote add upstream https://github.com/open-mmlab/mmdetection
> git fetch upstream
> git pull upstream master 
> ```

Thanks
