### ISSUE TITLE
KeyError: 'ZeroShotMaskRCNN is not in the models registry'

### ISSUE THREAD

**Issue by harrytrinh96** [open-mmlab/mmdetection#5601]
I got an error which was `KeyError: 'ZeroShotMaskRCNN is not in the models registry'`, how do i register ZeroShotMaskRCNN in the models registry?
```

2021-07-13 07:16:07,787 - mmdet - INFO - Distributed training: True
INFO:mmdet:Distributed training: True
/home/merge/Harry/instance_seg/mmdetection_zsi/mmdet/models/builder.py:52: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "./tools/train.py", line 188, in <module>
    main()
  File "./tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/merge/Harry/instance_seg/mmdetection_zsi/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/merge/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/merge/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/merge/anaconda3/envs/open-mmlab1/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ZeroShotMaskRCNN is not in the models registry'

```

**Comment by Aaa-ChEn** [comment]
That depends on the way you installed mmdetection. To be short, if you installed it with pip install -e . or python setup.py develop, then you do not need to reinstall it, otherwise you need to reinstall it after any modifications.

**Comment by harrytrinh96** [comment]
@Aaa-ChEn  I know. I installed it using `python setup.py develop` and still got the above error.

**Comment by noobying** [comment]
I also follow this work ZSI recently.  Whether you reimplement this work with mmdetection2, or just using the offical version with mmdetection1

**Comment by harrytrinh96** [comment]
Okay, Now i really know how the `mmdet` works on any versions

**Comment by wulala-max** [comment]
please help me how to solve,I encounter this error too

**Comment by wulala-max** [comment]
> That depends on the way you installed mmdetection. To be short, if you installed it with pip install -e . or python setup.py develop, then you do not need to reinstall it, otherwise you need to reinstall it after any modifications.

I dont understand the meaning of  otherwise you need to reinstall it after any modifications.please help me,first,I modified base the mmdetection and add some my own python files including some new models,then I still need to reinstall with 
pip install -e? but I have done this step at the beginning ,still encounter the error

**Comment by aeeeeeep** [comment]
> > That depends on the way you installed mmdetection. To be short, if you installed it with pip install -e . or python setup.py develop, then you do not need to reinstall it, otherwise you need to reinstall it after any modifications.
> 
> I dont understand the meaning of otherwise you need to reinstall it after any modifications.please help me,first,I modified base the mmdetection and add some my own python files including some new models,then I still need to reinstall with pip install -e? but I have done this step at the beginning ,still encounter the error

I also encounter this error too, do you solved it?

**Comment by kimlia545** [comment]
In my case the version of mmdet didn't matter.
The cause was a corrupted model file.
Test with another model file.
