### ISSUE TITLE
train/test_cfg will be re-update in build.

### ISSUE THREAD

**Issue by www516717402** [open-mmlab/mmdetection#5602]
It hope set train_cfg or test_cfg in specific module. 
https://github.com/open-mmlab/mmdetection/blob/5f6134796ed07f443d1bf389f57d3cee40bbd044/mmdet/models/builder.py#L47-L58
However it will overlap in follow code. 
https://github.com/open-mmlab/mmdetection/blob/5f6134796ed07f443d1bf389f57d3cee40bbd044/mmdet/models/detectors/single_stage.py#L34-L38

**Comment by hhaAndroid** [comment]
Hi @www516717402 Can you describe in detail？ Thank you
