### ISSUE TITLE
How to visualize proposal results?

### ISSUE THREAD

**Issue by wangjx123** [open-mmlab/mmdetection#5607]
How to visualize proposal results?  I try to visualize it based on the official code:
```
def simple_test(self, img, img_metas, proposals=None, rescale=False):
        assert self.with_bbox, 'Bbox head must be implemented.'
        x = self.extract_feat(img)
        if proposals is None:
            proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
        else:
            proposal_list = proposals

        return self.roi_head.simple_test(
            x, proposal_list, img_metas, rescale=rescale)
```
When I visualize the 'proposal_list', I get this result:
![image](https://user-images.githubusercontent.com/37363660/125444659-1b7cc37d-a792-419c-a809-c5078ef82992.png)
However, the final regression results are correct like this:
![image](https://user-images.githubusercontent.com/37363660/125444754-667666e3-e490-4ab4-a518-61b511e59f37.png)
The pretrained model is downloaded from official website, and the model is faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth. The test image is 000000367329.jpg from coco2017.
So, I think the proposal result may have a shift to the final result. How to get the correct proposal visualization?

**Comment by hhaAndroid** [comment]
Hi, @wangjx123 You can refer to the rpn visualization method using `demo/image_demo.py`.
