### ISSUE TITLE
why does dataset/custom.py get called? 

### ISSUE THREAD

**Issue by mtarun02** [open-mmlab/mmdetection#5613]
Hi all. When I run browse_dataset to test my dataset, I see in my error log that custom.py gets called (Where the __getitem__) method is not working. However, I do not see any explicit calls to this py file. Does it get called whenever I call something like dataset[0], and also should this be calling custom.py, not coco.py (my dataset is in coco format?)

Thank you for the clarification.

![Screen Shot 2021-07-14 at 1 56 50 PM](https://user-images.githubusercontent.com/24819296/125669835-1c6c6edc-f38e-4d09-b202-1e47df8d390a.png)

This happens if I call dataset[0] or let this code run (as part of browse_dataset, see below).

Am I missing something here? Is there a bug? Thank you!

![Screen Shot 2021-07-14 at 1 57 57 PM](https://user-images.githubusercontent.com/24819296/125669997-967821c1-2ee1-4d5b-a041-9b95da51cbe7.png)

**Comment by mtarun02** [comment]
![Screen Shot 2021-07-14 at 3 25 48 PM](https://user-images.githubusercontent.com/24819296/125681007-1e1a58e4-40e1-4954-a940-422def3d0026.png)

This is what happens when i run browse_dataset, BTW. It is having issue recalling the information from the dataset. I am confused as to why it uses custom.py, instead of coco, etc. When  I trace the whole thing, it is calling ['id'] from the dataset that is not in the correct method according to coco dataset guidelines.

**Comment by noobying** [comment]
Why use custom iinstead of coco? Because class COCODataset is inherit from CustonDataset. There is no __getitem__ in coco.py.

**Comment by mtarun02** [comment]
I am generally confused - getitem does not seem to work properly for a coco dataset. It calls things such as dataset['id'], which would not work. Something like dataset.get("img_info")['id'] would pull that information - it just seems as though custom.py is not made for coco datasets.

What is the purpose of custom.py and coco.py? Thank you.

**Comment by noobying** [comment]
In my opinion, the customdataset is designed to futher custom new dataset. For data that is not in coco format, you can easyily define through inherit from customdataset. Doc [custom dataset](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html) may help.

**Comment by mtarun02** [comment]
Okay. My question is, when I am running browse_dataset, why is it calling custom.py? I have a coco dataset and have specified the dataset type in my config file. Should it not go through coco.py? Thank you.

**Comment by RangiLyu** [comment]
Because the class `CocoDataset` is a subclass of `CustomDataset`. If you are not familiar with Inheritance, you can refer to this https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)

**Comment by noobying** [comment]
> Because the class `CocoDataset` is a subclass of `CustomDataset`. If you are not familiar with Inheritance, you can refer to this https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)

That what I am talking about!

**Comment by mtarun02** [comment]
Makes sense. Do you guys have any insight into why this error is occurring? I traced it to here:

<img width="684" alt="Screen Shot 2021-07-14 at 10 06 04 PM" src="https://user-images.githubusercontent.com/24819296/125716665-7bdbf913-ac55-42a8-aa3b-3f8551facb8f.png">


Where the commented lines (212 & 226) seem to work (my own code), where as the actual code (213 & 225) does not. This seems to not follow the guidelines of coco dataset. Do I need to go in and edit all of this? Thank you.

**Comment by noobying** [comment]
Could you show us your config file?thanks

**Comment by mtarun02** [comment]
<img width="598" alt="Screen Shot 2021-07-14 at 10 14 08 PM" src="https://user-images.githubusercontent.com/24819296/125717326-097b3fb5-0e89-411d-9136-1f64f609991c.png">

**Comment by noobying** [comment]
I reproduce the bug you by set the train_pipeline same as you (with only a Resize).
![image](https://user-images.githubusercontent.com/42159793/125717810-255cfc96-0d98-4d33-bab4-f05ff805e511.png)
You can merely replace the pipeline in train like follow.
`train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(512, 512), keep_ratio=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]`

**Comment by mtarun02** [comment]
Thank you so much! Unfortunately, I still get the same error, even when I put that in. Any other suggestions?

**Comment by noobying** [comment]
show me the log please.😊

**Comment by mtarun02** [comment]
<img width="698" alt="Screen Shot 2021-07-14 at 10 32 00 PM" src="https://user-images.githubusercontent.com/24819296/125718795-af28a9a1-142a-417c-9dd8-cea373304e6e.png">

**Comment by noobying** [comment]
You can try to use the actual code(213 & 225) you mentioned before!

**Comment by mtarun02** [comment]
Still not working (log below). I have been having issues running a basic train script for about 2 weeks now. I might switch and try detectron2? I am not sure what I am doing wrong.  Thank you so so much for your help.

<img width="735" alt="Screen Shot 2021-07-14 at 10 48 22 PM" src="https://user-images.githubusercontent.com/24819296/125720081-9cebf3f7-fae1-4dc5-bcde-fcc9fafc96f5.png">

**Comment by noobying** [comment]
It's my pleasure, dude.  Everything will be fine, don't give up your good expectations for MMDetection!

**Comment by RangiLyu** [comment]
Did you modified the code in `mmdet/datasets/pipelines`? You may need to revert those to origin and try again. Usually, it is no need to modify the code unless you need to implement new features.

**Comment by mtarun02** [comment]
> Did you modified the code in `mmdet/datasets/pipelines`? You may need to revert those to origin and try again. Usually, it is no need to modify the code unless you need to implement new features.

This worked somehow thanks! I thought I had tried this before but somehow I guess I did not. @noobying Thanks again!
