### ISSUE TITLE
How to be a developer in openmmlab community?

### ISSUE THREAD

**Issue by noobying** [open-mmlab/mmdetection#5615]
I found the inform in Zhihu said that make contributations in community can be a **Developer** from **User**. What is detal of contributaion computation? BTW, how openmmlab record everyone contributation?

**Comment by RangiLyu** [comment]
Great thanks for your interest and contribution! Did you enter the contributors' QQ group(161709383)? Welcome to discuss in there!

**Comment by noobying** [comment]
I will apply.
