### ISSUE TITLE
I find a FP16 problem

### ISSUE THREAD

**Issue by muzishen** [open-mmlab/mmdetection#5616]
About torch1.3, i can use the 'fp16 = dict(loss_scale=512.)' to save the model of fp16.
About torch 1.6, the 'fp16 = dict(loss_scale=512.)' does not work.

Can you tell me how to solve it！

**Comment by RangiLyu** [comment]
When PyTorch >= 1.6, torch.cuda.amp is used as the FP16 backend in MMCV. You may raise an issue in MMCV.

**Comment by muzishen** [comment]
> 
> 
> When PyTorch >= 1.6, torch.cuda.amp is used as the FP16 backend in MMCV. You may raise an issue in MMCV.

Thank you.
When Pytorch >= 1.6, how to use fp16 correctly!

**Comment by AronLin** [comment]
Can you tell us what command you ran and which config you used?
