### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Kangzf1996** [open-mmlab/mmdetection#5617]
Hello, I met this error when I verify the code.
I cannot import the module.
The env of my computer is cuda11.4 pytorch1.8.0 mmcv-full1.3.9 mmdet2.14.0
ImportError: /home/zhkan/anaconda3/envs/solo/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

**Comment by RangiLyu** [comment]
It seems the c++ version which complies mmcv is different from your c++ runtime. Try to add the correct version of libstdc++.so to LD_PRELOAD or LD_LIBRARY_PATH.

**Comment by Kangzf1996** [comment]
> It seems the c++ version which complies mmcv is different from your c++ runtime. Try to add the correct version of libstdc++.so to LD_PRELOAD or LD_LIBRARY_PATH.

Thank you for your reply. The c++ version I use is libstdc.so.6. How to check the c++ version which complies mmcv. Thank you!

**Comment by jshilong** [comment]
> > It seems the c++ version which complies mmcv is different from your c++ runtime. Try to add the correct version of libstdc++.so to LD_PRELOAD or LD_LIBRARY_PATH.
> 
> Thank you for your reply. The c++ version I use is libstdc.so.6. How to check the c++ version which complies mmcv. Thank you!

you can find it in your log file
