### ISSUE TITLE
Questions about anchor_generator

### ISSUE THREAD

**Issue by wangzyon** [open-mmlab/mmdetection#5619]
mmdet/core/anchor/anchor_generator.py/line189

```
base_anchors = [x_center-0.5*ws, y_center-0.5*hs, x_center+0.5*ws, y_center+0.5*hs]
default : center_off=0
```
thus
```
base_anchors = [-0.5*ws, -0.5*hs, 0.5*ws, 0.5*hs]
shift_x = torch.arange(0, feat_w, device=device) * stride[0]
shift_y = torch.arange(0, feat_h, device=device) * stride[1]
A(base_anchors) format:   [-0.5*ws, 0.5*hs, 0.5*ws, 0.5*hs]
K(shift) format: [left,top,left,top]
A plus K is not [xmin,ymin,xmax,ymax] format
```

Why not like this?
```
shift_x = (torch.arange(0, feat_w, device=device)+0.5) * stride[0]
shift_y = (torch.arange(0, feat_h, device=device)+0.5) * stride[1]
A(base_anchors) format:   [-0.5*ws, 0.5*hs, 0.5*ws, 0.5*hs]
K(shift) format: [center_x,center_y,center_x,center_y]
A plus K is [xmin,ymin,xmax,ymax] format
```
or
```
base_anchors =  [0, 0, ws, hs]
shift_x = torch.arange(0, feat_w, device=device) * stride[0]
shift_y = torch.arange(0, feat_h, device=device) * stride[1]
A(base_anchors) format:   [0, 0, ws, hs]
K(shift) format: [left,top,left,top]
A plus K is [xmin,ymin,xmax,ymax] format
```

What's wrong with me? thanks

**Comment by RangiLyu** [comment]
Do you mean why choosing mesh corners as centers of grid anchors instead of pixel centers?

**Comment by wangzyon** [comment]
> 
> 
> Do you mean why choosing mesh corners as centers of grid anchors instead of pixel centers?

yes, do you mean that the selection of anchor center does not affect the result?

**Comment by RangiLyu** [comment]
This is according to the new coordinate system in MMDetection2.x. The new coordinate system treats the center of the most left-top pixel as (0, 0). So the codes
```
shift_x = torch.arange(0, feat_w, device=device) * stride[0]
shift_y = torch.arange(0, feat_h, device=device) * stride[1]
```
actually generate all pixel centers of a feature map. So the K(shift)'s format is [center_x,center_y,center_x,center_y] here. My previous response was wrong.

You can refer to here https://github.com/open-mmlab/mmdetection/blob/master/docs/compatibility.md
