### ISSUE TITLE
The different results between the GN-WS version and the version before

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#562]
Hi,
    Thanks for your GN-WS work. But I found something wrong with the results before. The  GN results in the GN-WS version is much lower than the GN results before. The mask rcnn result for the  x101-32-4d-FPN result with GN is 38.7 and 33.1 .So could you please tell me the difference ?

**Comment by hellock** [comment]
There are no GN results for ResNeXt before. The GN+WS pretrained models for ResNeXt are shared by the authors.
