### ISSUE TITLE
Not a checkpoint file

### ISSUE THREAD

**Issue by shabbbb** [open-mmlab/mmdetection#5623]
Hey...
        I tried mmdetection with coco dataset. And during training, I am getting the error : 'the corresponding file is not a checkpoint file'.
       I tried by changing the config files; still getting the same error. Can you please suggest the config file that I need to use and the corresponding link to download it?

**Comment by jshilong** [comment]
Would you mind uploading your config so I can help to check it

**Comment by shabbbb** [comment]
Thank you sir for your time. My error got fixed, when I provided the right path.
