### ISSUE TITLE
data augment order question

### ISSUE THREAD

**Issue by ayanhui** [open-mmlab/mmdetection#5624]
hi, when I use Expand before RandomFlip  as mmdetection/configs/ssd/ssd300_coco.py in my code, something goes wrong.
the bbox flip will not right because it use results['img_shape'] to do the flip while results['img'].shape != results['img_shape']  after expand opt.
I don't know if I have something misunderstand or its a bug.
![图片1](https://user-images.githubusercontent.com/34311862/125893223-3c66104b-bf49-4390-ae51-c7895df2fde3.png)

**Comment by jshilong** [comment]
I will check it asap.
Many thanks
