### ISSUE TITLE
test.py error: unexpected keyword argument 'ype'

### ISSUE THREAD

**Issue by mtarun02** [open-mmlab/mmdetection#5629]
Hello! when I run the test.py, I get this error:

![Screen Shot 2021-07-16 at 10 17 44 AM](https://user-images.githubusercontent.com/24819296/125962127-dac7ef47-3f20-4b90-977b-d2a2358f1784.png)

I am not sure why it says 'ype', is this some typo in a file? Should this say type? Thank you.

Also, Can someone please point me to a resource that can help me evaluate the output of the training, such as Precision and recall, and what that means? Thank you!

**Comment by noobying** [comment]
Hello, dude, see you again .  I wanted remind you in #5613. Look the pic and red circlebellow .
![image](https://user-images.githubusercontent.com/42159793/126019252-db697944-dcc2-4757-8e5d-5a9b4fde54e9.png)
You can just modify the typo !
For the resource of learning the evaluation metric, you can reach to [here](https://tarangshah.com/blog/2018-01-27/what-is-map-understanding-the-statistic-of-choice-for-comparing-object-detection-models/). BTW, you can also check with the code of mmdetection to find out how the realize this process in code level. Good luck!

**Comment by mtarun02** [comment]
Ah! did not notice that. Thank you so much.
