### ISSUE TITLE
torch version error

### ISSUE THREAD

**Issue by liaopeiyuan** [open-mmlab/mmdetection#563]
When i tired to train a model using dist-train.sh, an error occurs:
ImportError: .../mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
And this is solved from downgrading torch 1.0.1 to 1.0.0. Anyone knows why this is the case?

**Comment by hellock** [comment]
This codebase should be compatible with both pytorch 1.0.0 and 1.0.1. When you installed a new version pytorch, did you recompile the ops?
