### ISSUE TITLE
What does anchor scale and base anchor mean? 

### ISSUE THREAD

**Issue by kyuheejo** [open-mmlab/mmdetection#5630]
How are these hyperparamters used to generate the size of anchor?

**Comment by mmeendez8** [comment]
We have developed [pyodi](https://github.com/Gradiant/pyodi) a tool that follow mmdetection format and helps to understand anchors, their parameters and to optimize them with respect to your data distribution. You should check it out :tada: 

![image](https://user-images.githubusercontent.com/15969667/126467442-299f7d57-d5f0-4784-9c43-bbda5ddeab76.png)
