### ISSUE TITLE
How to change img_scale in pipeline?

### ISSUE THREAD

**Issue by kyuheejo** [open-mmlab/mmdetection#5632]
Hi, in order to modify img_scale in pipline, do I need to chnage it for both train_pipeline and pipeline under train under data or just either one of them?

**Comment by AronLin** [comment]
This [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/config.md#use-intermediate-variables-in-configs) may help you.
You need to change it in train_pipeline and pass it to data.train.
