### ISSUE TITLE
Add a second classification head

### ISSUE THREAD

**Issue by Mehal001** [open-mmlab/mmdetection#5633]
I am trying to add a second classification head, i.e, in total the model has three heads. Is there any relevant documentation that could help describe how to achieve the same?

**Comment by lolongcovas** [comment]
I also need this feature. I have started to implement it, but i dont know how to pass the dynamic parameters in kwargs from config.py file

![image](https://user-images.githubusercontent.com/3662732/126133291-e2805566-e2be-4a00-b132-cda198b5ca6a.png)

**Comment by ZwwWayne** [comment]
You need to implement a new head or model and extend the init arguments of the modules. The key and values in the config are the same as those in the __init__ function.
