### ISSUE TITLE
Images don't show during inference with tools/test.py

### ISSUE THREAD

**Issue by g0lemXIV** [open-mmlab/mmdetection#5634]
**Describe the bug**
First of all, thank you for the amazing library! I find the bug which occurs during inference with tools/test.py (but it exists inside apis/test.py). The problem is as follows - when I use a model with a coco dataset where `file_name` includes the full path to the images for example `home/user/mmdetection/test/test.jpg`, images don't show at all inside specified `--work-dir`. I think this is a problem with the line
https://github.com/open-mmlab/mmdetection/blob/475c6bec197e6b495d48146636301590165d8f66/mmdet/apis/test.py#L47

**Reproduction**
COCO json file where images have full path as `file_name`
```bash
python tools/test.py model.py model.pth
```

**Bug fix**

The only way to prevent this error is to use `os.path.basename` inside apis/test.py to be sure that we are using right path
```python
if out_dir:
    out_file = osp.join(out_dir, osp.basename(img_meta['ori_filename']))
```

**Comment by AronLin** [comment]
Thanks for your feedback. We will check and fix this bug ASAP.

**Comment by AronLin** [comment]
I check the `img_meta` and `img_meta['ori_filename']` contains the original file name such as 'test.jpg', not the absolute path.
So this is not a bug.

If you want to show the images during inference, you can specify `--show` and not specify `--show-dir`; If you want to save the images with boxes, you should specify `--show-dir`.

**Comment by g0lemXIV** [comment]
@AronLin this means that I had had the wrong preprocessing script transformed to COCO format, thanks a lot, sorry about the mistake
