### ISSUE TITLE
reproducibility problem

### ISSUE THREAD

**Issue by ananzeng** [open-mmlab/mmdetection#5637]
hi thanks for research,first I want apologize my poor english,when I run mmdetection, I encountered a situation,I get different result in same config.
if can't get the same result,How did the numbers(some like mAP,AP0.5) on the paper or config page come from?Is it training multiple times to get the average?or train only once?
thank you

**Comment by noobying** [comment]
Hi, this [blog](https://www.zhihu.com/question/453511684/answer/1839683634) may help you. I think mmdet will not average evaluation many times. For you can download the log file in the config page, so the result comes from the single training though the hyper-paramater is not optimal all the time !

**Comment by ananzeng** [comment]
Thank you. I have read this bolg, but is the result with a slight gap acceptable in the paper? Because I see that the paper on CVPR is also implemented with mmdetection!
thank you again for your reply

**Comment by noobying** [comment]
> Thank you. I have read this bolg, but is the result with a slight gap acceptable in the paper? Because I see that the paper on CVPR is also implemented with mmdetection!
> thank you again for your reply

I don't know which model you mentioned above. But I also meet similar situation that I get a slight or large gap between paper with a same official config. Maybe the config in project is not the publish version, I think you can accpet the slight gap. But for the big gap, you can reach to author. Hope it helps you！
