### ISSUE TITLE
How to change batch-size in a training part of any network

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5638]
Hello , 

I want to ask about changing the batch size in any network config? 
should I change the number in ?

```
 samples_per_gpu=16,
 workers_per_gpu=4,
```

In case of changing in training part ,where should I write this instruction?

another question , i am trying to train a cornerNet with dataset have a form of coco dataset. 
the training gives me a massage of "out of memory" while when i training the centerNet on the same GPU system , it is working correctly .. what should i do to make the training on CornerNet works correctly? i am thinking to change the batch size , is that correct ?will this work?

looking for any answer. Thanks

**Comment by Arimitsu06** [comment]
#695
