### ISSUE TITLE
UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims

### ISSUE THREAD

**Issue by chuong98** [open-mmlab/mmdetection#5639]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

- Using either `pytorch 1.6` or `pytorch 1.9` can convert pytorch model to onnx. Let say `model_pt16.onnx` and `model_pt19.onnx` , respectively.
- Only `model_pt16.onnx` can be converted to TensorRT successfully.
- The `model_pt19.onnx` will enconter error:
  > UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims

**Reproduction**

1. What command or script did you run?
 
Convert Pytorch to Onnx
```bash
CFG="configs/mmdet/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py"
CKPT="checkpoints/coco/cascade_rcnn_r50_fpn_1x_coco_20200316-3dc56deb.pth"
OUTPUT_FILE=cache/cascade_rcnn_r50.onnx
INPUT_IMAGE_PATH=cache/demo.jpg
TEST_IMAGE_PATH=cache/color.jpeg
IMAGE_SHAPE="720 1280"
mim run mmdet pytorch2onnx $CFG $CKPT \
    --output-file ${OUTPUT_FILE} \
    --input-img ${INPUT_IMAGE_PATH} \
    --test-img ${TEST_IMAGE_PATH} \
    --shape ${IMAGE_SHAPE} \
    --verify 
```

Convert Onnx 2 TensorRT

```bash
export ONNX_BACKEND=MMCVTensorRT
CFG="configs/mmdet/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py"
MODEL=cache/cascade_rcnn_r50_dynamic.onnx
TRT_FILE=cache/cascade_rcnn_r50_dynamic.trt

INPUT_IMAGE_PATH=cache/demo.jpg
IMAGE_SHAPE="720 1280"
WORKSPACE_SIZE=1

mim run mmdet onnx2tensorrt $CFG $MODEL \
    --trt-file ${TRT_FILE} \
    --input-img ${INPUT_IMAGE_PATH} \
    --shape ${IMAGE_SHAPE} \
    --workspace-size ${WORKSPACE_SIZE} \
    --verify 
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
NO
3. What dataset did you use?
COCO 

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

> Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
> CUDA available: True
> GPU 0,1: GeForce RTX 2080 Ti
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 10.2, V10.2.89
> GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> PyTorch: 1.9.0
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 10.2
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
>   - CuDNN 7.6.5
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
> 
> TorchVision: 0.10.0
> OpenCV: 4.5.3
> MMCV: 1.3.9
> MMCV Compiler: n/a
> MMCV CUDA Compiler: n/a
> MMDetection: 2.14.0+366c628

my `~/.bashrc` setup
```bash
export TENSORRT_DIR=~/TensorRT-7.2.1.6
export ONNXRUNTIME_DIR=~/onnxruntime-linux-x64-1.5.1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TENSORRT_DIR/lib:$ONNXRUNTIME_DIR/lib
```
**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by lushaoan** [comment]
hello, i encounter this problem, here is my detail info  

system: ubuntu16.04  
python: 3.6.4  
cuda: 10.2  
cudnn: 8.2.2  
gpu: RTX2080 Ti  
pytorch: 1.7.0  via pip,  using virtualenv  
onnx: 1.7.0  
onnxruntime-gpu: 1.6.0  
tensorrt: 7.2.1.6  
mmcv-full: 1.3.11  via MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 pip install .  which in your mmcv doc  
mmdet: 2.14.0  

my ~/.bashrc setup  
```
export TENSORRT_DIR=/home/rr/Downloads/TensorRT-7.2.1.6
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TENSORRT_DIR/lib
```

here is my command:

```
python tools/deployment/pytorch2onnx.py configs/yolo/yolov3_d53_mstrain-608_273e_coco.py mmdetection_model/yolov3/yolov3_d53_mstrain-608_273e_coco-139f5633.pth --output-file checkpoints/yolo/yolov3.onnx --input-img demo/demo.jpg --shape 608 608 --cfg-options model.test_cfg.deploy_nms_pre=-1  
python tools/deployment/onnx2tensorrt.py configs/yolo/yolov3_d53_mstrain-608_273e_coco.py checkpoints/yolo/yolov3.onnx --trt-file checkpoints/yolo/yolo.trt --input-img demo/demo.jpg --shape 608 608

```  
the onnx file can be used correctly, however, the onnx2tensorrt.py fail with the traceback  
```
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 255, in <module>
    verbose=args.verbose)
  File "tools/deployment/onnx2tensorrt.py", line 46, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/home/rr/.virtualenvs/mmdet/lib/python3.6/site-packages/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
```  

expect your reply, thanks

**Comment by lushaoan** [comment]
i can run TensorRT-7.2.1.6/samples/python/yolov3_to_onnx.py and onnx_to_tensorrt.py correctly

**Comment by colceagus** [comment]
I have also tried it with the onnx model downloaded by the Tensorrt sample script and used the https://github.com/open-mmlab/mmcv/blob/master/docs/deployment/tensorrt_plugin.md/ example to convert it to trt. 

[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
Traceback (most recent call last):
  File "trt.py", line 30, in <module>
    save_trt_engine(trt_engine, trt_file)
  File "/home/model-server/mmdet/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 98, in save_trt_engine
    f.write(bytearray(engine.serialize()))
AttributeError: 'NoneType' object has no attribute 'serialize'


`import torch
import onnx

from mmcv.tensorrt import (TRTWrapper, onnx2trt, save_trt_engine,
                                           is_tensorrt_plugin_loaded)

assert is_tensorrt_plugin_loaded(), 'Requires to complie TensorRT plugins in mmcv'

onnx_file = 'yolov3.onnx'
trt_file = 'yolo.trt'
onnx_model = onnx.load(onnx_file)

# Model input
inputs = torch.rand(1, 3, 224, 224).cuda()
# Model input shape info
opt_shape_dict = {
            'input': [list(inputs.shape),
                              list(inputs.shape),
                                            list(inputs.shape)]
            }

# Create TensorRT engine
max_workspace_size = 1 << 60
trt_engine = onnx2trt(
            onnx_model,
                opt_shape_dict,
                    max_workspace_size=max_workspace_size)

# Save TensorRT engine
save_trt_engine(trt_engine, trt_file)

# Run inference with TensorRT
trt_model = TRTWrapper(trt_file, ['input'], ['output'])

with torch.no_grad():
    trt_outputs = trt_model({'input': inputs})
    output = trt_outputs['output']
    print(f"{output}")`

**Comment by colceagus** [comment]
I've come back with another experiment. I've tried using the onnx_to_tensorrt.py from the TensorRT-7.2.1.6 python samples for yolo and I got the following errors: 
```
model-server@c595176fea51:~/mmdet/TensorRT-7.2.1.6/samples/python/yolov3_onnx$ python onnx_to_tensorrt.py 
Loading ONNX file from path yolo.onnx...
Beginning ONNX file parsing
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
ERROR: Failed to parse the ONNX file.
In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 185, in <module>
    main()
  File "onnx_to_tensorrt.py", line 156, in main
    with get_engine(onnx_file_path, engine_file_path) as engine, engine.create_execution_context() as context:
AttributeError: __enter__
```

**Comment by ZwwWayne** [comment]
As MMDeploy is released https://github.com/open-mmlab/mmdeploy. MMDet will no longer maintain the feature of  model export. Please use MMDeploy and create an issue if you still have questions about that.

**Comment by Deepcong2019** [comment]
> hello, i encounter this problem, here is my detail info
> 
> system: ubuntu16.04 python: 3.6.4 cuda: 10.2 cudnn: 8.2.2 gpu: RTX2080 Ti pytorch: 1.7.0 via pip, using virtualenv onnx: 1.7.0 onnxruntime-gpu: 1.6.0 tensorrt: 7.2.1.6 mmcv-full: 1.3.11 via MMCV_WITH_OPS=1 MMCV_WITH_TRT=1 pip install . which in your mmcv doc mmdet: 2.14.0
> 
> my ~/.bashrc setup
> 
> ```
> export TENSORRT_DIR=/home/rr/Downloads/TensorRT-7.2.1.6
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TENSORRT_DIR/lib
> ```
> 
> here is my command:
> 
> ```
> python tools/deployment/pytorch2onnx.py configs/yolo/yolov3_d53_mstrain-608_273e_coco.py mmdetection_model/yolov3/yolov3_d53_mstrain-608_273e_coco-139f5633.pth --output-file checkpoints/yolo/yolov3.onnx --input-img demo/demo.jpg --shape 608 608 --cfg-options model.test_cfg.deploy_nms_pre=-1  
> python tools/deployment/onnx2tensorrt.py configs/yolo/yolov3_d53_mstrain-608_273e_coco.py checkpoints/yolo/yolov3.onnx --trt-file checkpoints/yolo/yolo.trt --input-img demo/demo.jpg --shape 608 608
> ```
> 
> the onnx file can be used correctly, however, the onnx2tensorrt.py fail with the traceback
> 
> ```
> Traceback (most recent call last):
>   File "tools/deployment/onnx2tensorrt.py", line 255, in <module>
>     verbose=args.verbose)
>   File "tools/deployment/onnx2tensorrt.py", line 46, in onnx2tensorrt
>     max_workspace_size=max_workspace_size)
>   File "/home/rr/.virtualenvs/mmdet/lib/python3.6/site-packages/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
>     raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
> RuntimeError: parse onnx failed:
> In node -1 (convertAxis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
> ```
> 
> expect your reply, thanks

Have you solved it? I met the same thing
