### ISSUE TITLE
Runtime error when calculate segmatic loss(HTC)

### ISSUE THREAD

**Issue by parkys7175** [open-mmlab/mmdetection#564]
An error occurs in calculating the semantic loss of the HTC model's forward train.
The error is due to the difference in the prediction of semantic head and  gt_seg.
Is there a way to solve this?

**Comment by hellock** [comment]
What error? What's your config?

**Comment by parkys7175** [comment]
The error is shown below.
![image](https://user-images.githubusercontent.com/26953930/57048741-37ef8a00-6cb0-11e9-81c1-d2468e95dc91.png)

and, config file is "configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py"
