### ISSUE TITLE
Resize images to fit the predefined size in configuration file

### ISSUE THREAD

**Issue by ALIYoussef** [open-mmlab/mmdetection#5647]
What is the used method (function) for image/mask resizing inside the framework? 
And in case that one image is rotated (i.e., the width <height), do the resize function rotate it in a proper way to make the dimension with width > height, and then the resize is achieved on the correct dimension?

As an example in faster RCNN configure [file](https://github.com/open-mmlab/mmdetection/blob/11f3ca2ba61b01e84e425bca2b8c6109e525ae67/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_1x_coco.py): 
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        **img_scale=(1333, 800),**
        flip=False,
        transforms=[
            **dict(type='Resize', keep_ratio=True),**
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])

How the rescale of the images is performed? Can any one indicate the function/s that performs this operation.

**Comment by hhaAndroid** [comment]
@ALIYoussef You can refer to https://github.com/open-mmlab/mmdetection/issues/4652
