### ISSUE TITLE
Evaluation failing: KeyError: 'segm is not in results'

### ISSUE THREAD

**Issue by mtarun02** [open-mmlab/mmdetection#5650]
Hi all. I get this error when evaluating a model. I have tried to add a evaluate within my config file, as well as if i test a model, this happens. Below is the method where it is happening. Do I need to add this somewhere else? bbox works fine. Thank you!

code called: 

#evaluation = dict(interval=1, metric='bbox') [this works!]
evaluation = dict(interval=1, metric='segm') [this fails!]

error:

<img width="708" alt="Screen Shot 2021-07-19 at 8 47 29 PM" src="https://user-images.githubusercontent.com/24819296/126245521-a01d7160-642f-43fd-a004-dabee975d16a.png">

Occurs (line 424:)

<img width="592" alt="Screen Shot 2021-07-19 at 8 47 53 PM" src="https://user-images.githubusercontent.com/24819296/126245562-9739b3f6-9bee-4459-aa2c-a66d7f2d4bae.png">

**Comment by mtarun02** [comment]
Could this be an issue with my dataset? Could someone direct me to a resource where I can learn more about bbox and mAP/segm eval metrics? Maybe my dataset does not support mAP/segm? Thank you!

**Comment by RangiLyu** [comment]
What model are you testing?

**Comment by mtarun02** [comment]
VFnet

**Comment by PeterVennerstrom** [comment]
VFnet only detects bbox.  Segm evaluation requires instance segmentation predictions.

**Comment by mtarun02** [comment]
OK Thank you! Where could I go to find this information for other models, like Faster RCNN, etc. ? Also, could you please point me to a resource where I could learn more about bbox and segm  (what they mean and measure?) thank you!

**Comment by PeterVennerstrom** [comment]
The COCO dataset supplies the metrics used for bounding box and instance segmentation tasks, among a few other tasks not addressed by this repository.  

Each individual method has a paper which covers the task(s) it targets.  You could also check the config train pipeline for: with_mask=True to determine which methods produce instance masks.
