### ISSUE TITLE
Just use selected Pi (P5 and P6) of RetinaNet

### ISSUE THREAD

**Issue by WilliamYi96** [open-mmlab/mmdetection#566]
FPN of RetinaNet-ResNet50 is:
``` 
in_channels=[256, 512, 1024, 2048],
out_channels=256,
start_level=1,
add_extra_convs=True,
num_outs=5),
```

I know 256, 512, 1024, 2048 correspond to P2, P3, P4, P5 repectively and we get P6 if we set 'add_extra_convs = True'.

The question is if I just need P5 and P6 to detect objects, how can I modify the least code of mmdetection?

**Comment by hellock** [comment]
If you only want a single feature map, you do not need FPN. If for some reason you want to refine the features on your own, you can just write a new neck module.

**Comment by WilliamYi96** [comment]
@hellock I've trained the model with all Pi (i from 2 to 6). I wonder if I can just use p5 and p6 for testing?
