### ISSUE TITLE
Is it possible to show the ground truth annotations when showing inference results?

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#5667]
As per title, I would like to overlay both MMDetection results and the ground truth annotations. Is this possible? It doesn't seem to be possible. My current code only shows MMDetection predictions:

```python
from mmdet.apis import init_detector, inference_detector
import mmcv

# Specify the path to model config and checkpoint file
config_file = '/workspace/my_config_file.py '
checkpoint_file = '/workspace/latest.pth'

# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

path = "/data/images/*"
jsonPath ="/data/annotation.json"
import glob
imgfiles =  glob.glob(path)
for i in imgfiles:
    save = i.split("/data/images/")[1]
    # test a single image and show the results
    img = i  # or img = mmcv.imread(img), which will only load it once
    result = inference_detector(model, img)
    # visualize the results in a new window
    model.show_result(img, result)
    # or save the visualization results to image files
    model.show_result(img, result, out_file='/workspace/results/'+save)
```

I had a look at the code for the `show_result` method, but it doesn't seem to support ground truth visualization:

https://github.com/open-mmlab/mmdetection/blob/c0506e28c97561ce45122c93ecfc1c791d094e09/mmdet/models/detectors/base.py#L260

How do you folks compare MMDetection and actual labels on an image, when you e.g. run the model on a validation set?

**Comment by noobying** [comment]
Hi, [here](https://github.com/Chien-Hung/DetVisGUI/tree/mmdetection) may help you.

**Comment by AndreaPi** [comment]
Thanks @noobying , I'll test it this week and if it satisfies my requirements, I'll close the issue.
