### ISSUE TITLE
Details about the base_anchor design

### ISSUE THREAD

**Issue by 237014845** [open-mmlab/mmdetection#567]
Hello, I would like to know how anchor is designed in the anchor-base network. For example, your RetinaNet first sets the CTR of base_anchor through the corresponding anchor-stride of each output feature map to generate 9 base-anchors. What is the setting of base_anchor based on? The size of the receptive field? I have calculated the size of the receptive field of each feature map, but I still don't understand what the base_anchor is based on.  if you could take the time to answer my questions I would be grateful

**Comment by thangvubk** [comment]
The anchor is defined by a 4-tuple vector ``(x, y, w, h)``.
Intuitively, the base anchor size equals the size of a feature map pixel in the image space. The base anchor is a square with ``w = h = stride`` (``stride`` is based on the level of feature map, e.g. level = 2 then ``stride = 2^2 = 4``). Then, the center is located ``(stride - 1)/2`` on the feature map. 
Then the base anchor will be transformed to actual anchors using ``scales`` and ``ratios`` see [here](https://github.com/open-mmlab/mmdetection/blob/921e433e23fbb6920e6c67ac5bfac1bf4179a140/configs/faster_rcnn_r50_fpn_1x.py#L21).

**Comment by 237014845** [comment]
@thangvubk Thank you very much for your reply

**Comment by 237014845** [comment]
@thangvubk Hello! Could you please explain again in detail that the base anchor size equals the size of a feature map pixel in the image space? Because the calculated base anchor size does not correspond to the corresponding feature map size. For example, the input picture size is 640x640, and the output feature map of Retinanet is [80x80, 40x40, 20x20, 10x10, 5x5], base_size:[8, 16, 32, 64, 128]. The calculated size of the corresponding base anchor does not correspond to the size of the output feature map. I hope you can help me explain in detail what the base anchor is set on.

**Comment by thangvubk** [comment]
RetinaNet uses features from level 3 to level 7. Let take level 3 as an example, the feature map size is 80x80. If you project 1 pixel of this feature map to the image of 640x640, it will correspond to 8x8 (8*80 = 640).

**Comment by 237014845** [comment]
@thangvubk Thank you very much for your reply. I know what you said, but what I want to ask is what principle the base anchor is set according to and is the center of the base anchor the pixel corresponding to the original input picture? For example, Retinanet input picture is 640x640, feature map is 80x80, base_size: 8. The corresponding 9 base anchor sizes are [45x21, 57x27, 71x35, 31x31, 39x39, 49x49, 21x45, 27x57, 35x71]. However, I still don't understand why the center of base anchor should be set like this.

**Comment by thangvubk** [comment]
If you have a base anchor of 8x8, then the center will be **naturally** (8 - 1)/2 = 3.5.

**Comment by 237014845** [comment]
@thangvubk I know that the center (8-1)/2 = 3.5, 3.5 is the pixel corresponding to the original picture, what I want to know is why to set the center = (stride-1)/2, The corresponding base anchor center of all feature diagrams :[(3.5, 3.5), (7.5, 7.5), (15.5, 15.5), (31.5, 31.5), (63.5, 63.5)] but it has no rule for the original input image

**Comment by thangvubk** [comment]
> but it has no rule for the original input image

What do you mean by ``rule``

**Comment by 237014845** [comment]
@thangvubk I'm sorry that my English is not very good. I just want to know the reason of setting the base anchor centor and the real meaning of it

**Comment by thangvubk** [comment]
The reason is you need good alignment between the feature map pixels and anchor centers. For example, the top-left pixel on the feature map should predict (class and regr) for top-left anchor box.

**Comment by 237014845** [comment]
@thangvubk Thank you very much for your reply
