### ISSUE TITLE
What's the difference between style='caffe' and style="pytorch" in pretrain model?

### ISSUE THREAD

**Issue by johnson-magic** [open-mmlab/mmdetection#5670]
Why auto-assign use style='caffe', however atss use stype='pytorch' in pretrain model?

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/8e942aed8527fabb4995a3c46918056a5308604b/mmdet/models/backbones/resnet.py#L318-L320
