### ISSUE TITLE
Training Instance Segmentation with 4-band (RGBA) images

### ISSUE THREAD

**Issue by abfleishman** [open-mmlab/mmdetection#5671]
I am trying to train `Cascade Mask RCNN` using a custom dataset in `COCO` format with 4 channel `.tif` files.  There is only a single class in the dataset.  I am looking for advice on what changes I need to make to the config (and other places?) to accommodate the 4 band imagery?  Also are there any pre-trained models that I can start with that have 4 bands or will I need to start from scratch?  Thank you for your help!

**Comment by PeterVennerstrom** [comment]
Generally a 3 channel input will be hard coded in each backbone, e.g. darknet.py line 121.  

Then the data loader might also need to be adjusted to load the .tif files and preserve their RGBA format.  The data loader may already handle .tif images, but will convert them to 3 channel numpy arrays by default.   

I don't think there is any additional performance to be gained from using RGBA images, it's another way to represent an image that has some convenience benefits for photo editing, but it doesn't contain additional information over RGB.

**Comment by abfleishman** [comment]
@PeterVennerstrom Thanks for your reply!  This is helpful info and confirms what I have gleaned from other Issues on the repo.  The images I am working with are 4-channel tiffs. They have RGB + Thermal as a fourth band.  

So if I understand, I should be able to train a model from scratch is I 1) modify the data loader to retain the 4th channel and 2) modify the backbone to receive input with 4 channels?

I am hoping to train an instance segmentation model and was going to start with the config for [Cascade Mask-RCNN.](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/cascade_mask_rcnn_r50_fpn.py).  Any chance you (or anyone) could point me toward the correct modifications to the backbone to use 4-channel images?

**Comment by PeterVennerstrom** [comment]
Resnet has an in_channels argument which is set to 3 by default.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
