### ISSUE TITLE
Inference speed is very slow

### ISSUE THREAD

**Issue by ncduy0303** [open-mmlab/mmdetection#5677]
I'm trying to follow the testing scripts for evaluating an existing model on the COCO dataset using `faster_rcnn` on Google Colab. However, the inference speed was only about `8.2 tasks/s`, which is much slower than the reported speed of `21.4fps`

This is my testing scripts:

```
CONFIG = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py' 
CHECKPOINT = 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'

!python tools/test.py $CONFIG $CHECKPOINT --out results.pkl
```

And this if the final time taken to run the testing script:
`[>>] 5000/5000, 8.2 task/s, elapsed: 610s, ETA:     0s`

Any help would be much appreciated!

**Comment by AronLin** [comment]
21.4fps is the inference speed of the network. The testing time contains data time, network inference and post process for evaluation.
