### ISSUE TITLE
error in creating  the pkl result file using tools/test.py function

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5682]
hello , 
I did the training over SSD model with tools/train.py
and i got files with extension (.pth ) 

I am trying to use such file (latest.pth),for testing and inferencing this weights over a test dataset. 
I used the following command;   

`python tools/test.py configs/human/ssd512_coco_my.py training_data/ssd300_epoch24/latest.pth --show-dir test_results/ssd_new --out ssd_pkl --eval bbox`

they mentioned in help that i should use (--out) , and i try use it , but i don't know exactly what should i write after it. 

when running the above command , it gave me the following error
![error in pkl](https://user-images.githubusercontent.com/10245810/126881482-49da7a35-b174-4674-8051-7cfcb2a37aff.JPG)

I need to create the pkl file , so i can use them in the analyse part of results with function 
-python tools/analysis_tools/analyze_results.py- 

what shall i do? please help.

**Comment by BIGWangYuDong** [comment]
Your output file must end with .pkl. 
Try
`python tools/test.py configs/human/ssd512_coco_my.py training_data/ssd300_epoch24/latest.pth --show-dir test_results/ssd_new --out ssd.pkl --eval bbox`
