### ISSUE TITLE
如何在我自己的项目中使用mmdet工具包内TTFNet模型的TTFHead

### ISSUE THREAD

**Issue by HappyPeanuts** [open-mmlab/mmdetection#5684]
我最近有一个任务，需要在自己的项目中使用TTFNet模型的TTFHead，请问我具体应该怎么操作，是需要吧mmdet这个文件复制到我的项目中吗，我已经在虚拟环境中安装了mmdet，但是在我的model中导入TTFHead的时候报错了，请问具体该如何操作。希望有人能给我一些建议和帮助，非常感谢

**Comment by ZwwWayne** [comment]
Could you follow the `issue template` to post your error log? We are not able to debug for now.
For examples, you can refer to https://github.com/open-mmlab/mim-example/tree/master/swin_transformer
