### ISSUE TITLE
How to modify the params of init_cfg if I do not want to use the pretrained model

### ISSUE THREAD

**Issue by wxr5899** [open-mmlab/mmdetection#5687]

**Comment by wxr5899** [comment]
the default of the init_cfg is below:
init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'))

**Comment by wxr5899** [comment]
The new doc of mmdetection  is used the deprecated code sample:

model = dict(
    type='MaskRCNN',  # The name of detector
    pretrained=
    'torchvision://resnet50',  # The ImageNet pretrained backbone to be loaded

**Comment by BIGWangYuDong** [comment]
Hi, You can follow [init_cfg doc](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/init_cfg.md).
In the feature, we will delete `Pretined` in `model` and use `init_cfg` in `backbone`.
