### ISSUE TITLE
In 'MMDETECTION : Open MMLab Detection Toolbox and Benchmark' paper,

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#5690]
I have a question in paper 'MMDETECTION : Open MMLab Detection Toolbox and Benchmark'.
In this paper, What epoch did you use to produce Table 10?
Is it correct that the total epoch has been changed according to the lr schedule?
If the lr schedule is 1x, is it 12 epoch , if lr schedule is 2x, 24 epoch , if lr schedule is 20e, is it 20 epoch ?
(What I understood while reading the paper)
If what I understand is wrong, please let me know how much total epoch is.
And I have one more question.
What optimizer did Table 10 use?
Is it SGD or Adam?

**Comment by BIGWangYuDong** [comment]
Hi, you can refer to the config docs in [`/docs/tutorials/config.md`](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/config.md)
```
{schedule}: training schedule, options are 1x, 2x, 20e, etc. 1x and 2x means 12 epochs and 24 epochs respectively. 
20e is adopted in cascade models, which denotes 20 epochs.
For 1x/2x, initial learning rate decays by a factor of 10 at the 8/16th and 11/22th epochs. 
For 20e, initial learning rate decays by a factor of 10 at the 16th and 19th epochs.
 ```

Also, SGD is the default optimizer in mmdet, for more details please refer to the config files (e.g. [schedult_1x](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/schedules/schedule_1x.py)).
