### ISSUE TITLE
Multiscale testing question

### ISSUE THREAD

**Issue by oblivious137** [open-mmlab/mmdetection#5704]
When I use multiscale testing, I got a worse mAP. It seems that the proposal boxes are used incorrectly.

The proposals are mapped to different scales in the augmentation process (/mmdet/datasets/pipelines/test_time_aug.py:105 -> /mmdet/datasets/pipelines/transforms.py:303) because we add "proposals" to "bbox_fields" when load them, and the scale factors are saved. But in "/mmdet/models/roi_heads/test_mixins.py:179", it doesn't use these mapped proposals. 
The proposals corresponding to the i-th scale are calculated from the first scale's proposals through scale_factor_{i}, while the correct scale factor should be scale_factor_{i}/scale_factor_{0}. Or use the proposals which are already mapped.

I use an older version and modified some codes, so the configs are not suitable for the latest version and I didn't list them. But I see the same codes in the latest version, it may cause the same error.

**Comment by AronLin** [comment]
You can test whether multiscale testing works or not with the existing model in our latest codes. If there is also a worse mAP, we will check it.
