### ISSUE TITLE
test models without ground-truth annotations

### ISSUE THREAD

**Issue by Kangzf1996** [open-mmlab/mmdetection#5706]
Hi,
I'm wondering how to test the model without ground truth.
I don't have the annotations for the image set, the format only cannot work if I don't have the annotations.

**Comment by noobying** [comment]
Hi, you refer to [here](https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#test-without-ground-truth-annotations) for help.

**Comment by Kangzf1996** [comment]
> Hi, you refer to [here](https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#test-without-ground-truth-annotations) for help.

Actually, I've tried it. But it still requires the annotations file.

**Comment by noobying** [comment]
Does GT exist on the network or evaluation server like coco (test-dev) ? Or you just want to inference the images.

**Comment by Kangzf1996** [comment]
> Does GT exist on the network or evaluation server like coco (test-dev) ? Or you just want to inference the images.

Well, I just want to inference the images. 
Thank you.

**Comment by noobying** [comment]
No worries. I  didn't inference a directory of images before. Maybe you can modify the `demo/image_demo.py`.

**Comment by Kangzf1996** [comment]
Ok, thank you. I'll try it.

**Comment by AronLin** [comment]
#5548 may help you.
