### ISSUE TITLE
How to use resnet-101 for Faster R-CNN on PASCAL VOC?

### ISSUE THREAD

**Issue by Balazizo** [open-mmlab/mmdetection#5707]
Hello, I've downloaded a faster r-cnn resnet-101 backbone for PASCAL VOC from https://modelzoo.co/model/faster-rcnnpytorch. I've tried using it as a checkpoint and modifying the pre-trained and backbone depth arguments. I've gotten APs of 0 only, though. Is there any way I can use resnet-101 as a backbone for Faster R-CNN when testing on PASCAL VOC?

**Comment by noobying** [comment]
Maybe you can download https://github.com/open-mmlab/mmdetection/tree/master/configs/faster_rcnn/faster_rcnn_r101_fpn_mstrain_3x_coco.py.

**Comment by Balazizo** [comment]
Isn't this for the coco dataset? Is there a way to use it for PASCAL or another way possible?

**Comment by AronLin** [comment]
The pretrained model for PASCAL and COCO is the same.

**Comment by ZwwWayne** [comment]
1. MMDetection does not support load checkpoints trained by other frameworks, you need to add a script to convert them.
2. If you want to use the model in mmdet, you can see the configs in the [pascal_voc directory](https://github.com/open-mmlab/mmdetection/tree/master/configs/pascal_voc) and modify the configs for ResNet-101. You need to train a model before testing it if it is a new config that do not have a pretrain.
3.  You can use COCO pretrain to train model on Pascal VOC.
