### ISSUE TITLE
Using pointpillars pre-trained model on 32 layer point cloud input 

### ISSUE THREAD

**Issue by mohamed11981198** [open-mmlab/mmdetection#5713]
Hello,

I am trying to use the model trained on Lyft dataset. The trained model was based on a LIDAR that has different number of layers of VLP-32. What do I need to the model to match VLP-32? should I upsample the input point cloud or modify the feature maps?

I tried the model on VLP-32 data as it is but it outputs a lot of false positives in the scene so I am not sure what i need to do in input point cloud loading to the model ?

**Comment by RangiLyu** [comment]
I'm afraid that you need to open this issue in https://github.com/open-mmlab/mmdetection3d
