### ISSUE TITLE
Can't get evaluation result json file

### ISSUE THREAD

**Issue by genres17** [open-mmlab/mmdetection#5723]
### My issue
 I want to save my object detection evaluation results in a json file, including classification results and position results for all bbox.However, it can work normally for evaluation but fail to save as a json file which means I can't find the file in the folder.
 ### Configuration
- Pytorch 1.7.0
- mmcv-full 1.3.9
- mmdet 2.13.0
### Other detail
- dataset: a dataset use pascal VOC format
- model: fasterRCNN+guidedanchor+doublehead
### Issue command
I tried this command by your doucument.
```python tools/test.py configs/m2cai16-tool-locations/faster_rcnn_r50_caffe_fpn_guidedanchor_doublehead_softnms_1x_tools.py work_dirs/faster_rcnn_r50_caffe_fpn_guidedanchor_doublehead_softnms_1x_tools/epoch_12.pth --format-only --options="jsonfile_prefix=./guidedanchor_doublehead"```

### Issue screenshot
1. This is the command running screenshot.
![图片](https://user-images.githubusercontent.com/60060093/127482543-ceeaf05d-e15d-4374-ab45-b8bc5aaaf67e.png)
2. After running can't find the result file.
![图片](https://user-images.githubusercontent.com/60060093/127482480-e3870a21-eca4-4e5c-b38a-0219c85820d7.png)

**Comment by RangiLyu** [comment]
The result file is `guidedanchor_doublehead.bbox.json` not `guidedanchor_doublehead.json`
