### ISSUE TITLE
How to get process group

### ISSUE THREAD

**Issue by FRAOTIAC** [open-mmlab/mmdetection#5727]
I have trouble find the process group during distributed training, at first I located the api/train.py, where distributed the model, but seems like the process group is hidden. I also tried to get the default process group with pytroch _get_default_group API, but then a error occured. How can I get process group correctly?

**Comment by jshilong** [comment]
The entrance is here
https://github.com/open-mmlab/mmdetection/blob/a1cecf63c713c53941b8dcf8a9d762baf8511f2c/tools/train.py#L120
