### ISSUE TITLE
get all mAP results 0.0000

### ISSUE THREAD

**Issue by hxm1150310617** [open-mmlab/mmdetection#5730]
Hi, I trained a faster-rcnn model for an object detection task, and during the training progress, when validating the model on every epoch I got the result of all mAPs equal to 0.0000 or extremely small float such as 0.01. Even worse, for several occasions i got the message: ERROR-The testing results of the whole dataset is empty. However, i visualized the testing results and all objects are perfectly detected, which means the model was working perfectly. Also my val data and annotation seems normal. So i wonder why would this happen? How can i fix this? Also, i tried to reduce the learning rate once and it worked! I have no idea what are the connections between validation progress and learning rate. Looking forward to ur replies, ty.

**Comment by jshilong** [comment]
Your situation is really puzzling, Sorry I can’t solve this problem unless I can reproduce it

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by Guhanxue** [comment]
I met the same error, and found all map is 0.00, but the number of detected objects are right....
