### ISSUE TITLE
有关Mask-rcnn的结果

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#5733]
我使用自己的数据集训练了mmdection包中的mask-rcnn.但是在图片上显示的结果不佳。显示的结果会有边界框的部分。但是经常出现显示边界框（正确结果但是得分较低）套着边界框（得分较高）的结果。或者两个边界框有很大重叠（实际上两者合并的结果正确）。这种结果如何应对？有没有可以修改的参数使得这些边界框的结果进行合并？

**Comment by kankanzheli** [comment]
附上几个图片结果
![IMG_20210423_102255(1)](https://user-images.githubusercontent.com/58200245/127639583-e283a3f7-2f3a-484f-bcce-3e158d597cee.jpg)
![IMG_20210423_101918(2)](https://user-images.githubusercontent.com/58200245/127639610-cb31a41a-be75-4fd4-a302-e6a04cedbf38.jpg)

**Comment by noobying** [comment]
看上去你的数据集有很多遮挡，比如西红柿被被茎分为了好几个部分，你的GT是什么样子的呢

**Comment by jshilong** [comment]
What is your ground truth? If the gt bbox is total tomato, It seems that your detector is not well trained, because all the predicted results are low quality

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by wangzehui20** [comment]
> 附上几个图片结果
> ![IMG_20210423_102255(1)](https://user-images.githubusercontent.com/58200245/127639583-e283a3f7-2f3a-484f-bcce-3e158d597cee.jpg)
> ![IMG_20210423_101918(2)](https://user-images.githubusercontent.com/58200245/127639610-cb31a41a-be75-4fd4-a302-e6a04cedbf38.jpg)

I meet the same problem, have you solved? my gt no occlusion
