### ISSUE TITLE
Model weights for v1.0 not found

### ISSUE THREAD

**Issue by zycheiheihei** [open-mmlab/mmdetection#5741]
I am using mmdetection v1.0 now, but I found that the links of pretrained models have become invalid. 404 Error is reported when I use 'wget' command. Is there any place I can find the pretrained weights for mmdetection v1.0, especially those for Retinanet. The aliyun mirror also doesn't work.

**Comment by ZwwWayne** [comment]
Hi @zycheiheihei ,
Sorry that v1.x models have been no longer supported. You can directly use the RetinaNet in v2.0. The checkpoints can be correctly loaded in v1.0.
