### ISSUE TITLE
关于“遮挡目标”的训练参数优化

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmdetection#5742]
mmdet 效果很好，能成功运行。但是在【**多个目标之间相互遮挡**】的场景下，检测效果一直不好。请问有什么参数可以调节，可以参考什么文档？？

我看有个 `iscrowd` 参数，但没有找到文档。

**Comment by noobying** [comment]
`iscrowd`参数表示是不是群体对象，主要是用于目标比较难以标注所设立的一个属性，可以看到下图中的原图以及它的可视化标注图片。
![image](https://user-images.githubusercontent.com/42159793/127755071-d6494421-c276-457b-b1cb-3f7ca40fb6ae.png)，
![image](https://user-images.githubusercontent.com/42159793/127755081-15463313-cedd-4900-8cd7-ed08489faff5.png)
这一图片来自于COCO，COCO在标注的时候，一般对于人群这种比较多的目标是不会全部进行标注的，只是会选择一部分（10~15个）进行标注，剩余都用一个对象（`iscorwd=1`）进行标注，当你预测出属于`iscorwd=1`的对象时，是不会进行打分的，而且这个`iscrowd`这个对象也是不会作为GT进行训练的，因此这个参数与遮挡没有什么关系。
最后，遮挡问题是检测对象面临的一个共同问题，应该有专用的模型来解决吧，希望能帮助到你 : )

**Comment by chenxinfeng4** [comment]
多谢解答
