### ISSUE TITLE
If Seesaw loss can be only used in image classification?

### ISSUE THREAD

**Issue by Lucy0601** [open-mmlab/mmdetection#5749]
1. If Seesaw loss can be only used in image classification?
2. Do you try it on classification? how does it perform?

**Comment by BIGWangYuDong** [comment]
I haven't tried it, maybe you can create an issue in mmcls

**Comment by zimenglan-sysu-512** [comment]
hi @BIGWangYuDong 
in the paper, the loss has been used for image classification, so do u have a plan to release it?
