### ISSUE TITLE
about docker image 

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#5754]
Hello, I am running the docker command to create an environment, and I will be stuck in this step：
`docker build -t mmdetection docker/`
![image](https://user-images.githubusercontent.com/43515926/127821057-21829b15-5227-4638-878a-0c0d3fe0b30d.png)
![image](https://user-images.githubusercontent.com/43515926/127829020-f1d0ef2a-a4a9-4e9e-af9e-f26b82ba476c.png)
![image](https://user-images.githubusercontent.com/43515926/127829042-3faef693-13ee-4e5c-bdcd-430a7cb897fa.png)

**Comment by zcswdt** [comment]
> Hello, I am running the docker command to create an environment, and I will be stuck in this step：
> `docker build -t mmdetection docker/`
> ![image](https://user-images.githubusercontent.com/43515926/127821057-21829b15-5227-4638-878a-0c0d3fe0b30d.png)


![image](https://user-images.githubusercontent.com/43515926/127828554-faaa74f8-1c16-4b31-9278-7afc60cb625a.png)

**Comment by BIGWangYuDong** [comment]
Hi, maybe you can change a source and rebuild the environment again.
