### ISSUE TITLE
demp.py

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#5757]
![image](https://user-images.githubusercontent.com/43515926/127845402-4080df75-2bb1-4974-862f-231feeb809cd.png)

**Comment by noobying** [comment]
what happen ? Can you specify your question ?

**Comment by zcswdt** [comment]
> what happen ? Can you specify your question ?

Sorry, I didn't describe it clearly. I installed the environment, and then ran demo.py, and then an error was reported. I don't know what caused it, so I would like to ask. The screenshot of the error is above.

**Comment by noobying** [comment]
It's just some warnings. No error occurs.

**Comment by zcswdt** [comment]
> It's just some warnings. No error occurs.

I ran demo.py but no results were generated. There should be a detected image generated. If it is a warning, where is the generated image?
