### ISSUE TITLE
如何实现倾斜目标检测 (How to try Rotation RPN in mmdet)

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmdetection#5763]
MMdetection is less satisfactory in bird view. A general question, but critical in my case, is how to use Rotation RPN in mmdetection?

MMdetection 矩形识别框在 topview 中效果不佳。我的问题是，如何实现如下图的倾斜矩形框识别？
<img width="238" alt="图片" src="https://user-images.githubusercontent.com/17546446/127900358-83e2b56f-a047-4e3c-b18e-72c203a72148.png">

**Comment by ElectronicElephant** [comment]
Hmm, I don't think mmdet support rotated bbox by design.

**Comment by chenxinfeng4** [comment]
The mmdet supports CenterNet, so, it may also be adapted for Roation RPN.

**Comment by hhaAndroid** [comment]
@chenxinfeng4 Or you can try mmocr.
