### ISSUE TITLE
question about MMDetection GPU power consumption

### ISSUE THREAD

**Issue by ingbeeedd** [open-mmlab/mmdetection#5768]
Hello, I'm practicing oxford pet detection with MMdeteciton, but the power I have is small, so I made the batch size small as below code to reduce gpu memory usage. 
but when I run it, gpu power consumption shows maximum.... how the MMdetection package is set? Can I reduce gpu power consumption? my os system is `Ubuntu 18` Thank you!

`cfg.data.samples_per_gpu = 2`

[code Link]
https://drive.google.com/file/d/1tYI0TiML_Z89ayH6dA5VOvcyLefz0Jzd/view?usp=sharing

**Comment by noobying** [comment]
Hi, @ingbeeedd , if your GPU has `tensor core` uints, you can try to use the mixed precision training strategy. This method will theoretically reduce GPU memory comsumption by half.  
You can easily add this line on your config.
```python
fp16 = dict(loss_scale=dict(init_scale=512.))
```

**Comment by ingbeeedd** [comment]
@noobying 
Hello, I have 24GB of GPU memory, and I use about 12GB to perform my current code. So I think the memory usage is okay. But it use the 390W to the maximum power.W). I wonder how to reduce the amount of Power W usage. Thank you

**Comment by ElectronicElephant** [comment]
Hi, you can use `nvidia-smi` command to limit the power of GPU.

https://www.google.com.hk/search?channel=fs&client=ubuntu&q=nvidia-smi+limit+power

**Comment by ingbeeedd** [comment]
@ElectronicElephant I've used the command below, but it seems like the mmdet code has to use that more power at all. As a result, the PC was turned off.

**Comment by ElectronicElephant** [comment]
> @ElectronicElephant I've used the command below, but it seems like the mmdet code has to use that more power at all. As a result, the PC was turned off.

Hmm, it's not only your GPU, but CPU, motherboard, hard disks, etc, also use power. IMHO, you should replace your current power supply with a better one, or, your hardware may be damaged.
