### ISSUE TITLE
测试阶段计算accuracy

### ISSUE THREAD

**Issue by lixiuyu-cumt** [open-mmlab/mmdetection#5772]
我发现在训练阶段会有计算ACC的过程，怎么在测试阶段计算ACC呢？具体的代码修改应该是怎样的呢？

**Comment by hhaAndroid** [comment]
@lixiuyu-cumt It is enough to have mAP in the testing phase. Why do you need to know acc?

**Comment by hhaAndroid** [comment]
The evaluation result does not support acc calculation for the time being, but you can rewrite the `dataset.evaluate` method.
