### ISSUE TITLE
RefineDet implementation

### ISSUE THREAD

**Issue by Charlyo** [open-mmlab/mmdetection#5782]
Searching the implemented models I found that there's no version of RefineDet. Is there any reason / better model that would make this implementation not worth?

Thank you for your amazing work!

**Comment by jshilong** [comment]
This method has no advantage now

**Comment by Charlyo** [comment]
@jshilong which one would you suggest as a better model?

**Comment by Charlyo** [comment]
@jshilong @AronLin Sorry to bother you again. Could you provide some feedback?

**Comment by AronLin** [comment]
It is based on SSD, which has no advantage now. You can try the two-stage methods such as Mask R-CNN series, or Cascade R-CNN.
Some one-stage methods such as FCOS, ATSS have good performance, too.

**Comment by Charlyo** [comment]
I see, eventhough it had anchor refinement? RefineDet++ had align convolutions at the end.

Nonetheless I would try the ones you suggested! I have tried DetectorRS, but it seems to be quite big.

Any recomendation on a improved version of cascade-rcnn / mask-rcnn? They seem to older than newer implementations.

**Comment by AronLin** [comment]
In general, the better the effect, the bigger the model. 
You can choose the largest model you can accept.
You can refer to the Readme file of each algorithm in the configs folder. The size and performance of the models can be the basis of your choice.

**Comment by Charlyo** [comment]
Perfect! Thank you @AronLin !
