### ISSUE TITLE
train error：AttributeError: 'tuple' object has no attribute 'get'

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#5783]
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 158, in main
    model = build_detector(
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.8/site-packages/mmdet-2.12.0-py3.8.egg/mmdet/models/builder.py", line 53, in build_detector
    assert cfg.get('train_cfg') is None or train_cfg is None, \
AttributeError: 'tuple' object has no attribute 'get'

**Comment by AronLin** [comment]
cfg should be a `dict`, not `tuple`, please check the codes you changed.

**Comment by chensen668** [comment]
Thank you for your reply, but I haven't changed train_cfg in the code,train_cfg is still dict.

**Comment by AronLin** [comment]
I know you did not changed the train_cfg, but the `cfg` at line 53 in `builder.py` is a tuple, maybe you changed the codes in `builer.py` , leading to the change of the type of `cfg`. Please check it, it is not a bug in our latest codes.

**Comment by chensen668** [comment]
if train_cfg is not None or test_cfg is not None:
        warnings.warn(
            'train_cfg and test_cfg is deprecated, '
            'please specify them in model', UserWarning)
    assert cfg.get('train_cfg') is None or train_cfg is None, \
        'train_cfg specified in both outer field and model field '
    assert cfg.get('test_cfg') is None or test_cfg is None, \
        'test_cfg specified in both outer field and model field '
    return DETECTORS.build(
        cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))

I don't need to change the code here.  May be not recognize train_cfg due to some other setting problems. I'll take a look tomorrow.Thanks!

**Comment by Spritea** [comment]
I met the same problem, and the reason in my case is that I added a comma after the model dict declaration, like
`model = dict(...), data=dict(...)`
Just deleting the comma can solve the problem.
