### ISSUE TITLE
I want to use vgg19 as backbone

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#5784]
What should I modify to use vgg19 as a backbone?

**Comment by AronLin** [comment]
We do not support VGG in our repo now.
You can refer to this [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_models.md#add-a-new-backbone) to build this new backbone.
As for the pretrained model, you can use the VGG19 pretrained model in torchvision.
