### ISSUE TITLE
Please suggest,. i am running deep_sort_mgn.py on MOT20 dataset. how the folders should be named according to the code snippet

### ISSUE THREAD

**Issue by ssbilakeri** [open-mmlab/mmdetection#5786]
` track_numbers = [1, 4, 5, 9, 10]     
 for track_number in track_numbers:      
      rootdir = '/root/data/A-data/Track{0}'.format(track_number)        
      # rootdir = '/root/data/5'

**Comment by AronLin** [comment]
I even do not know what are you doing according to such a short description.
'/root/data/A-data/Track{0}'.format(track_number) stands for '/root/data/A-data/Track1' or '/root/data/A-data/Track4' ...
