### ISSUE TITLE
VOC data set evaluation index

### ISSUE THREAD

**Issue by ywj509** [open-mmlab/mmdetection#5791]
How to calculate the precision index when using VOC data set for training? At present, only these GTS | dets | recall | AP are given

**Comment by AronLin** [comment]
AP is average precision. Does your `precision` mean that?

**Comment by ywj509** [comment]
No, it's TP / (TP + FP)

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/5c7c74d77dfba3663431fe00b6872dfff8bcce1d/mmdet/core/evaluation/mean_ap.py#L364
