### ISSUE TITLE
Find an error when evaluating recall in VOC Dataset

### ISSUE THREAD

**Issue by BIGWangYuDong** [open-mmlab/mmdetection#5792]
In `VOC.evaluate`:
https://github.com/open-mmlab/mmdetection/blob/604bfe9618533949c74002a4e54f972e57ad0a7a/mmdet/datasets/voc.py#L27-L38

the result is `list[list]`, and it feeds into `eval_recalls`:

https://github.com/open-mmlab/mmdetection/blob/604bfe9618533949c74002a4e54f972e57ad0a7a/mmdet/datasets/voc.py#L82-L85

But in `eval_recalls`, the `proposals` need be (list[ndarray]):

https://github.com/open-mmlab/mmdetection/blob/604bfe9618533949c74002a4e54f972e57ad0a7a/mmdet/core/evaluation/recall.py#L64-L75

This will get an error when evaluating the recall at:
https://github.com/open-mmlab/mmdetection/blob/604bfe9618533949c74002a4e54f972e57ad0a7a/mmdet/core/evaluation/recall.py#L89-L90

The Error is:

```shell
 File "mmdetection/mmdet/core/evaluation/recall.py", line 90, in eval_recalls
    if proposals[i].ndim == 2 and proposals[i].shape[1] == 5:
AttributeError: 'list' object has no attribute 'ndim'
```

**Comment by ZhuangTingT** [comment]
I also met this error, Did you solve it?
