### ISSUE TITLE
Suggest adding darknet-19 backbone to Yolov3

### ISSUE THREAD

**Issue by ghm666** [open-mmlab/mmdetection#5797]
**Suggest adding darknet-19 backbone to Yolov3**

**Comment by RangiLyu** [comment]
Hi, sorry to inform: Since [MMYOLO](https://github.com/open-mmlab/mmyolo) already supports different sizes of the models of YOLOv5&v6&v7, we will not provide more resources for yolov3. But PRs of YOLOv3 are still welcome.
