### ISSUE TITLE
pytorch2caffe ERROR

### ISSUE THREAD

**Issue by SunshineJZJ** [open-mmlab/mmdetection#5798]
pytorch2caffe脚本：https://github.com/woodsgao/pytorch2caffe
您好：我使用上面的转换脚本，将openmmlab下的yolov3模型https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/yolo/yolov3_d53_mstrain-416_273e_coco.py
转换为 caffemodel，但是中间遇到很多问题，目前还有一个问题解决不了，应该是view算子的问题，报错如下：
![image](https://user-images.githubusercontent.com/38787542/128324952-3c394729-49eb-4945-83fa-cd01c8be4253.png)
请帮忙看下是否可以解决？

**Comment by RunningLeon** [comment]
@SunshineJZJ We do not provide `pytorch2caffe` feature in the repo, maybe you could try with pytorch2onnx and onnx2caffe.

**Comment by SunshineJZJ** [comment]
好的 谢谢

**Comment by SunshineJZJ** [comment]
> @SunshineJZJ We do not provide `pytorch2caffe` feature in the repo, maybe you could try with pytorch2onnx and onnx2caffe.

您好 这个方法有实现方案吗 
https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_mstrain-416_273e_coco/yolov3_d53_mstrain-416_273e_coco-2b60fcd9.pth
torch版本1.9.0  可以转onnx模型，但是转caffe的时候提示opset_version版本需要是9，pyotrch2onnx.py中的opset_version=11改为9运行报错，不支持9；

您有上面的yolov3转caffe的解决方案和可执行的代码吗？

**Comment by RunningLeon** [comment]
@SunshineJZJ Hi, yes, only opset_version==11 is supported in the repo. For yolov3 you should export to onnx without post-processing ops like `nms`. And maybe you could try [the opset version conversion tool](https://github.com/onnx/tutorials/blob/master/tutorials/VersionConversion.md) in ONNX repo, however please be noted that we have not used the tool yet.
