### ISSUE TITLE
epoch and batch-size

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#5799]
Where to modify the training epoch and batch-size?

**Comment by zlx-6** [comment]
you should set  the  ```max_epochs``` and ```samples_per_gpu``` in your config file to modify the training epoch and batch size respectively, like this:
```
runner = dict(type='EpochBasedRunner', max_epochs=12),
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,)
```
