### ISSUE TITLE
AttributeError: module 'mmcv' has no attribute '__version__'

### ISSUE THREAD

**Issue by CharlesNJohn** [open-mmlab/mmdetection#5802]
I am running Swin Transformer and I get this error. Installed from this rep.

**Comment by SunshineJZJ** [comment]
先把pip安装的卸载了  然后用mim install mmdet

**Comment by CharlesNJohn** [comment]
> 先把pip安装的卸载了 然后用mim install mmdet

getting the same error for CBNetV2 even after doing that

**Comment by jshilong** [comment]
Please clear  the mmcv  in the environment then install it with the guidance in  https://github.com/open-mmlab/mmcv

**Comment by CharlesNJohn** [comment]
Thank you, that worked! I face an issue again, I wonder if this has to do with mmcv installation.

KeyError: 'CBSwinTransformer is not in the models registry'

During handling of the above exception, another exception occurred:.....
MaskRCNN: 'CBSwinTransformer is not in the models registry'

I got this error while running CBNetV2 for object detection, tried different methods it didn't work. I encountered a similar problem with another model but it was solved when I installed the right package made for that model. I don't understand the cause for this model.


KeyError Traceback (most recent call last)
/tmp/ipykernel_5864/1081140356.py in
8 device = 'cuda:0'
9 # init a detector
---> 10 model = init_detector(config_file, checkpoint_file, device)
11 # inference the demo image
12 img = './demo/1.jpg'

~/cbn/lib/python3.8/site-packages/mmdet/apis/inference.py in init_detector(config, checkpoint, device, cfg_options)
37 config.model.pretrained = None
38 config.model.train_cfg = None
---> 39 model = build_detector(config.model, test_cfg=config.get('test_cfg'))
40 if checkpoint is not None:
41 map_loc = 'cpu' if device == 'cpu' else None

~/cbn/lib/python3.8/site-packages/mmdet/models/builder.py in build_detector(cfg, train_cfg, test_cfg)
55 assert cfg.get('test_cfg') is None or test_cfg is None,
56 'test_cfg specified in both outer field and model field '
---> 57 return DETECTORS.build(
58 cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))

~/cbn/lib/python3.8/site-packages/mmcv/utils/registry.py in build(self, *args, **kwargs)
208
209 def build(self, *args, **kwargs):
--> 210 return self.build_func(*args, **kwargs, registry=self)
211
212 def _add_children(self, registry):

~/cbn/lib/python3.8/site-packages/mmcv/cnn/builder.py in build_model_from_cfg(cfg, registry, default_args)
24 return Sequential(*modules)
25 else:
---> 26 return build_from_cfg(cfg, registry, default_args)
27
28

~/cbn/lib/python3.8/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
52 except Exception as e:
53 # Normal TypeError does not print class name.
---> 54 raise type(e)(f'{obj_cls.name}: {e}')
55

Environment:
sys.platform: linux
Python: 3.8.10 (default, Jun 2 2021, 10:49:15) [GCC 9.4.0]
CUDA available: True
GPU 0,1: RTX A4000
CUDA_HOME: /usr
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:

    GCC 7.3
    C++ Version: 201402
    Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
    Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
    OpenMP 201511 (a.k.a. OpenMP 4.5)
    NNPACK is enabled
    CPU capability usage: AVX2
    CUDA Runtime 11.1
    NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
    CuDNN 8.0.5
    Magma 2.5.2
    Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.5.3
MMCV: 1.3.10
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.15.0+900f7bd
