### ISSUE TITLE
Inconsistent inference results between tensorrt 7 and tensorrt 8

### ISSUE THREAD

**Issue by mesenlol** [open-mmlab/mmdetection#5807]
When I use the same onnx converted to trt file, the inference results in tensorrt7 and tensorrt8 are not consistent, where tensorrt 8 has the correct result and tensorrt 7 appears to have more bbox, some of which have some position shift.
The model I am using is retinanet,what is the problem and why tensorrt7 and tensorrt8 behave differently on this model?
When I use the ssd model, the results of tensorrt7 and tensorrt8 are basically the same and correct.

Environment
TensorRT Version: 8.0.1.6
NVIDIA GPU: GTX1650TI
NVIDIA Driver Version: 470
CUDA Version: 10.2
CUDNN Version: 8.2.0

**Comment by jshilong** [comment]
Please take a look at this issue @RunningLeon

**Comment by RunningLeon** [comment]
@mesenlol Hi, thanks for the feedback. We were meant to support TensorRT7 and TensorRT8 was not in the plan. Currently, we do not have the resources to fully compare these two versions of TensorRT.

**Comment by mesenlol** [comment]
@RunningLeon Thank you for your reply. After I tried, I found that only in TensorRT7.1.3.4 the retinanet results show a certain bbox position offset, while TensorRT7.2.3.4 and TensorRT8.0.1.6 results are basically consistent and correct.

**Comment by RunningLeon** [comment]
Hi, thanks for your info. We only tested on TensorRT-7.2.1.6. You could refer to the note in the doc:
https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/onnx2tensorrt.md#list-of-supported-models-convertable-to-tensorrt
> All models above are tested with Pytorch==1.6.0, onnx==1.7.0 and TensorRT-7.2.1.6.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.0

**Comment by ban1080** [comment]
@mesenlol Did you test TensorRT-7.2.1.6? If so, are the results between TensorRT-7.2.1.6 and TensorRT7.2.3.4/TensorRT8.0.1.6 the same?
