### ISSUE TITLE
metric items coco dataset

### ISSUE THREAD

**Issue by firsakov** [open-mmlab/mmdetection#5810]
Hi, 

is there a way to see f1 score and precision/recall on evaluation of coco dataset? 
in dataset.evaluate() metric items are taken from cocoEval.stats[coco_metric_names[metric_item]], but i can't find any info if there are f1\precision\recall or how to add it.

Thank you in advance.

**Comment by WassimBouatay** [comment]
Same question, what are the available metrics ? I need precision&recall at a fixed confidence score

**Comment by PeterVennerstrom** [comment]
Coco metrics include average precision and average recall across a list of iou thresholds.  For these metrics the confidence scores are used to get the 100 topk detections.  

F1 is not provided, but could be calculated separately.  

To get these metrics at a fixed confidence score, adjust the config before running the evaluation tool.  

There should be a score_thr argument in the test_cfg.  

E.g. FCOS config:

test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.5),
        max_per_img=100))
