### ISSUE TITLE
mean_ap output

### ISSUE THREAD

**Issue by firsakov** [open-mmlab/mmdetection#5811]
Hi,

please help me with output of mean_ap.py.
How to call this scirpt if i want to get output metric tables?

**Comment by PeterVennerstrom** [comment]
The functions in this script are used in a few places, two examples: mmdet/datasets/custom.py, tools/analysis_tools/analyze_results.py

To get the output metrics, one approach would be to create a custom dataset and run /tools/test.py against it.  The custom dataset can call the functions in mean_ap in its evaluate method when the dataset is run with /tools/test.py

[There is some documentation on this topic.](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html)
