### ISSUE TITLE
How to evaluate on a pretrained model on a dataset

### ISSUE THREAD

**Issue by WassimBouatay** [open-mmlab/mmdetection#5812]
I want to evaluate the performance of a provided model (for instance DeeformableDETR) on my dataset. Following the tutorial, I am able to make the prediction for a single image. But, I want to feed a whole dataset to my model and calculate the precision  and recall (for a fixed confidence score i.e. not AP and AR). 

So what I wanted to know is: Is there 
1/ A function that accepts an annotation file and returns its performance ?
2/ Is there an implementation of the Precisoin and Recall or do I have to do it myself ?

PS: I am using the CocoDataset type

Thank you!

**Comment by AronLin** [comment]
1. If your dataset is in COCO format. Using the `evaluate` function of COCO is enough.
What you need to do is to change the path of annotation files and images in your config.
2. AP is `average precision`, they are the same. If you need AP but mAP, you can set `classwise=True` in `evaluate`.

**Comment by WassimBouatay** [comment]
@AronLin  Thank you for your answer. 

1. Yes that is the function that I need (I used CustomDataset evaluation function). I don't know if you can further help me. I get an mAP=0 even though the mode makes good predictions after visualizing with ```show_result_pyplot```.

This is how I used the evaluation function:

```
cfg = Config.fromfile(config)
cfg.data.val.type = 'Custom_Dataset'
cfg.data.val.data_root = ''
cfg.data.val.ann_file = 'mypath'
cfg.data.val.img_prefix = 'validation/'

results = []
with open(cfg.data.val.ann_file, 'r') as jsonFile:
    data = jsonFile.read()
image_list = json.loads(data)
for image in image_list:
    res = inference_detector(model, image['filename'])
    results.append(res)
build_dataset(cfg.data.val)
dataset.evaluate(results=results, metric='mAP', proposal_nums=(100), iou_thr=0.5)

img = 'path_img'
result = inference_detector(model, img)
show_result_pyplot(model, img, result, score_thr=0.5)
```

2. I don't want average Precision or average Recall, I want the Precision and recall for a confidence threshold=0.5 for example.

**Comment by WassimBouatay** [comment]
I ended up calculating Precision and Recall on my own. Maybe, it isn't optimal but easier to do.
