### ISSUE TITLE
How I can visualize the model graph?

### ISSUE THREAD

**Issue by stanislavkuskov** [open-mmlab/mmdetection#5813]
Hello! 
How I can visualize the model graph? In tensorboardX for example.
When i try to use model(x) its get me error _"forward() missing 1 required positional argument: 'img_metas'"_
`
> config = '/home/kuskov/sat/mmdetection/configs/res2net/faster_rcnn_r2_101_fpn_2x_coco.py'
> checkpoint = 'checkpoints/faster_rcnn_r2_101_fpn_2x_coco-175f1da6.pth'
> model = init_detector(config, checkpoint, device='cuda:0')
> 
> img = torch.zeros([1, 3, 224, 224])
> with SummaryWriter(comment='MultipleOutput_shared') as w:
> 
>     w.add_graph(model,` img, True)

`

**Comment by RangiLyu** [comment]
You need to set `model.forward = model.forward_dummy` because the detector's forward function is not the same as the default forward function of pytorch module.

**Comment by stanislavkuskov** [comment]
@RangiLyu Thank You, that works!
