### ISSUE TITLE
issues about cascade networks

### ISSUE THREAD

**Issue by Curry1201** [open-mmlab/mmdetection#582]
Hello, Dr. Chen Kai. In your model, the three parts are cascaded  with IoU thresholds of 0.5, 0.6, and 0.7 for better detection. Why not two or four? What is the innovation point compared to the previous IoU threshold of 0.5? In addition, what are the meanings of different APs? For example: 
![image](https://user-images.githubusercontent.com/43410903/57177462-31226c00-6e96-11e9-9e35-897363fe0363.png)
, 
![image](https://user-images.githubusercontent.com/43410903/57177465-41d2e200-6e96-11e9-8edf-a2b1e8d1dbef.png)
, 
![image](https://user-images.githubusercontent.com/43410903/57177468-4b5c4a00-6e96-11e9-98ee-ce35e6238ec1.png)
, 
![image](https://user-images.githubusercontent.com/43410903/57177474-59aa6600-6e96-11e9-8d10-c428a17ff639.png)
, 
![image](https://user-images.githubusercontent.com/43410903/57177478-66c75500-6e96-11e9-9880-9b05ab1ecee7.png)
, 
![image](https://user-images.githubusercontent.com/43410903/57177483-7050bd00-6e96-11e9-8ba5-3328b353cbd2.png)
.
I look forward to your reply, thank you.

**Comment by hellock** [comment]
You may need to read [Cascade R-CNN: Delving into High Quality Object Detection
](https://arxiv.org/abs/1712.00726).
