### ISSUE TITLE
loss() got multiple values for argument 'gt_bboxes_ignore'

### ISSUE THREAD

**Issue by FibonacciZ** [open-mmlab/mmdetection#5821]
I added extra loss in fcos_head. When I runned the code, it reported errors：
loss() got multiple values for argument 'gt_bboxes_ignore'.

I checked the code, then find that there's no code to change the 'gt_bboxes_ignore'

environment:
mmcv-full                 1.1.6   
mmdet                     2.4.0

**Comment by PeterVennerstrom** [comment]
Sounds like your loss() function is receiving additional inputs, but these are not accounted for in the definition of the function arguments or the extra positional argument is defined after the optional keyword argument gt_bboxes_ignore when it should be defined before.

**Comment by Inori-dn** [comment]
@FibonacciZ Hello, may I ask if you have resolved this issue?
