### ISSUE TITLE
What is the input data structure of MMDetection?

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmdetection#5822]
What is the input data structure of MMDetection? 

Is it 

- "_batchsize, channel ,width, height_" , 
- "_batchsize ,width, height, channel_" or 
- "_width, height, channel, batchsize_" ?

Also, how can I show/view it in the code? where can I use **_x.size()_**?

**Comment by PeterVennerstrom** [comment]
The Pytorch convention is [batch, channel, height, width]

The extract_feat() method in either two_stage.py or single_stage.py takes the image tensor as input.

**Comment by chandlerbing65nm** [comment]
@PeterVennerstrom Thank you. Just a follow-up question, is the batchsize "**_samples_per_gpu_**"?
