### ISSUE TITLE
assert len(inputs) == len(self.in_channels)

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmdetection#5830]
In "_**mmdetection/mmdet/models/necks/fpn.py**_" under "_**def forward(self, inputs):**_" we see the code line:

-  "_**assert len(inputs) == len(self.in_channels)**_"

What does the "_**inputs**_"  represent? 
Why is it the same with "_**self.in_channels**_"?

Can I use this with the "_**inputs**_"?

- **batch, channels, height, width = inputs.size()**

**Comment by PeterVennerstrom** [comment]
In a neck class, input channels is a list of the input channels at each scale.  It corresponds to the output channels at each scale in the backbone.  

The config defines which backbone stages are passed from the backbone to the neck and the corresponding number of channels for each in the neck.  

model = dict(
    type='FastRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3)),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5)

Inputs to the fpn is a tuple of tensors output from the backbone.  They could be looped through to get their shapes.

**Comment by chandlerbing65nm** [comment]
> Inputs to the fpn is a tuple of tensors output from the backbone. They could be looped through to get their shapes.

This tuple contains "**_batch, channels, height, width_**" from the 4 levels of Resnet right? 

So, if I use batch, "**_inputs.size()_**" I should get the items:

- "**_batch, channels, height, width_**"

Is this correct?

**Comment by BIGWangYuDong** [comment]
> > Inputs to the fpn is a tuple of tensors output from the backbone. They could be looped through to get their shapes.
> 
> This tuple contains "**_batch, channels, height, width_**" from the 4 levels of Resnet right?
> 
> So, if I use this on the first level of FPN, "**_inputs[0].size()_**" I should get the items:
> 
> * "**_batch, channels, height, width_**"
> 
> Is this correct?

Yes I think so
