### ISSUE TITLE
Training of HTC model

### ISSUE THREAD

**Issue by Jamestrump** [open-mmlab/mmdetection#5831]
I successfully implemented instance segmentation task with msk-rcnn models but when i tried to use HTC model its shows an error -  .data/coco/stuffthingsmap/mytrainingimage.png file not found.
I have my data and annotations in coco format.
I read the documentation about HTC its shows that you need to have stuffthingsmap. I am really confused about it like what i need to put in stuffthingsmap folder.
Any kind of help will be really appreciated.
Thansk in advance.

**Comment by AronLin** [comment]
Stuffthingsmap is a kind of semantic map which HTC will use. With it, HTC will get better performance.
If you do not want to use it, please refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_without_semantic_r50_fpn_1x_coco.py

**Comment by Jamestrump** [comment]
@AronLin Thankyousomuch can you tell about semantic map , how can we use it?

**Comment by AronLin** [comment]
> @AronLin Thankyousomuch can you tell about semantic map , how can we use it?
> Like do i need to put training / testing data in stuffthingsmap folder?

It is an annotation map about semantic segmentation. Does your dataset have semantic annotations? If not, you can not use it.

**Comment by Jamestrump** [comment]
@AronLin Thankyou once again, my dataset does not have semantic annotations so it means i cannot use SCNet and HTC models, but i can only use htc without semantic models.

**Comment by AronLin** [comment]
> @AronLin Thankyou once again, my dataset does not have semantic annotations so it means i cannot use SCNet and HTC models, but i can only use htc without semantic models.

yes

**Comment by AKMourato** [comment]
@AronLin what kind of maps are those?
Normal binary masks in png or jpeg format?
Thanks
