### ISSUE TITLE
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HappyPeanuts** [open-mmlab/mmdetection#5833]
我搭建好环境后调用测试nms时报错：
ImportError while importing test module '/home/user/yzw/ttfnet-master/mmdet/test_nms.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.conda/envs/ttfnet/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_nms.py:8: in <module>
    from .ops.nms.nms_wrapper import nms
ops/__init__.py:7: in <module>
    from .nms import nms, soft_nms
ops/nms/__init__.py:1: in <module>
    from .nms_wrapper import nms, soft_nms, simple_nms
ops/nms/nms_wrapper.py:5: in <module>
    from .src import nms_cpu, nms_cuda
E   ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
我已经重新安装mmcv-full和mmdet了，仍然报错，请问有人遇到类似的情况吗

**Comment by BIGWangYuDong** [comment]
You should check your environment, especially your CUDA version, please give us more details.
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Comment by HappyPeanuts** [comment]
This is the result:
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1


OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.20.5


Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080 Ti
Nvidia driver version: 470.57.02
cuDNN version: /usr/local/lib/libcudnn.so.7


Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;mkl&nbsp; &nbsp; https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2021.3.0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;h06a4308_520&nbsp; &nbsp; https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2.4.0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; py37h7f8727e_0&nbsp; &nbsp; https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.3.0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; py37h42c9631_2&nbsp; &nbsp; https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.2.2&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; py37h51133e4_0&nbsp; &nbsp; https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.4.0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;py3.7_cuda10.1.243_cudnn7.6.3_0&nbsp; &nbsp; pytorch
[conda] torchvision&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0.5.0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; py37_cu101&nbsp; &nbsp; pytorch



As for&nbsp;&nbsp;$PATH,&nbsp;$LD_LIBRARY_PATH,&nbsp;$PYTHONPATH, I donot know how to operate.Can you tell me more detailly.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory (#5833)





 
You should check your environment, especially your CUDA version, please give us more details.
 Environment
  
Please run python mmdet/utils/collect_env.py to collect necessary environment information and paste it here.
 
You may add addition that may be helpful for locating the problem, such as  
How you installed PyTorch [e.g., pip, conda, source]
 
Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)
  
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HappyPeanuts** [comment]
Sorry, I send you the wrong result ,this is the result of run&nbsp;python mmdet/utils/collect_env.py
(ttfnet2) ***@***.***:/home/user/yzw/ttfnet-master/mmdet/utils# python collect_env.py&nbsp;
Traceback (most recent call last):
&nbsp; File "collect_env.py", line 1, in <module&gt;
&nbsp; &nbsp; from mmcv.utils import collect_env as collect_base_env
ModuleNotFoundError: No module named 'mmcv.utils'
But I found that, there is MMCV-FULL in my enviroments, what happened?
kgs/main
mmcv-full&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.3.9&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pypi_0&nbsp; &nbsp; pypi
mmdet&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1.0rc0+unknown&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dev_0&nbsp; &nbsp; <develop&gt;








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory (#5833)





 
You should check your environment, especially your CUDA version, please give us more details.
 Environment
  
Please run python mmdet/utils/collect_env.py to collect necessary environment information and paste it here.
 
You may add addition that may be helpful for locating the problem, such as  
How you installed PyTorch [e.g., pip, conda, source]
 
Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)
  
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HappyPeanuts** [comment]
This is the latest result:
(ttfnet) ***@***.***:~/yzw/ttfnet-master/mmdet/utils$ python collect_env.py&nbsp;
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.10 (default, Jun&nbsp; 4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0+cu110
PyTorch compiling details: PyTorch built with:
&nbsp; - GCC 7.3
&nbsp; - C++ Version: 201402
&nbsp; - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
&nbsp; - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
&nbsp; - OpenMP 201511 (a.k.a. OpenMP 4.5)
&nbsp; - NNPACK is enabled
&nbsp; - CPU capability usage: AVX2
&nbsp; - CUDA Runtime 11.0
&nbsp; - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
&nbsp; - CuDNN 8.0.4
&nbsp; - Magma 2.5.2
&nbsp; - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,&nbsp;


TorchVision: 0.8.1+cu110
OpenCV: 4.5.3
MMCV: 1.3.9
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.15.0+

But it still have the same problem


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory (#5833)





 
You should check your environment, especially your CUDA version, please give us more details.
 Environment
  
Please run python mmdet/utils/collect_env.py to collect necessary environment information and paste it here.
 
You may add addition that may be helpful for locating the problem, such as  
How you installed PyTorch [e.g., pip, conda, source]
 
Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)
  
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BIGWangYuDong** [comment]
This might because the cuda version you are using is different during compilation and running time.
You can refer this issue #592

Further, we would appreciate it if you could use the “Error report” issue template.

**Comment by HappyPeanuts** [comment]
> This might because the cuda version you are using is different during compilation and running time.
> You can refer this issue #592
> 
> Further, we would appreciate it if you could use the “Error report” issue template.

ok, thank you for your help, i will try it again.
