### ISSUE TITLE
How means about broatcast key to all gpu ?

### ISSUE THREAD

**Issue by www516717402** [open-mmlab/mmdetection#5834]
https://github.com/open-mmlab/mmdetection/blob/8bd1af86292e75458905115cce67e766c69a69da/mmdet/core/hook/yolox_process_hook.py#L98-L102

**Comment by www516717402** [comment]
@hhaAndroid Need help.

**Comment by hhaAndroid** [comment]
This is because the dictionary keys are out of order.

**Comment by www516717402** [comment]
@hhaAndroid  However both of `async_norm_states` and `module.named_modules()` are order dict. No need translate again?
https://github.com/open-mmlab/mmdetection/blob/8bd1af86292e75458905115cce67e766c69a69da/mmdet/core/hook/yolox_process_hook.py#L41-L47

**Comment by hhaAndroid** [comment]
> @hhaAndroid However both of `async_norm_states` and `module.named_modules()` are order dict. No need translate again?
> https://github.com/open-mmlab/mmdetection/blob/8bd1af86292e75458905115cce67e766c69a69da/mmdet/core/hook/yolox_process_hook.py#L41-L47

This synchronous dictionary operation is a general function and also considers disordered scenarios.

**Comment by www516717402** [comment]
@hhaAndroid This operate does not work here since sync-dict already ordered and only work for unorder scenarios. Thank you for explain carefully.
