### ISSUE TITLE
I want to print 'eval_results' to get precision and recall.

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#5836]
I want to get precision and recall to plot ROC curve.

I know there is no way to draw a ROC curve, (but if you know how to draw ROC curve please let me know)
so I try to draw it using precision and recall. 
So I looked it up and the 'mmdetection/mmdet/core/evaluation/mean_ap.py' file seems to be related to it.

I want to use the 'function : eval_map' in 'mmdetection/mmdet/core/evaluation/mean_ap.py'.
I want to print 'eval_results'.
Can you teach me how to print eval_results with my model file and checkpoint file?
OR 
Is there any way to utilize 'eval_map'?

**Comment by BIGWangYuDong** [comment]
Hi, you can use eval_map to get precision and recall. You can get `tp, fp` in this function and 

https://github.com/open-mmlab/mmdetection/blob/a637a552b0a43285cbcaf4d92eecad36326c8ca0/mmdet/core/evaluation/mean_ap.py#L363-L364

you can get precisions and recalls from this two line
