### ISSUE TITLE
model reports errors when it val after first epoch

### ISSUE THREAD

**Issue by FibonacciZ** [open-mmlab/mmdetection#5846]
I added extra loss in fcos_head.  everything is fine when the model is training. But it reports errors when it val after first epoch.

ERROR:
>  File "/mmdetection/mmdet/models/detectors/base.py", line 170, in forward
>    return self.forward_test(img, img_metas, **kwargs)
 > File "/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
 >   return self.simple_test(imgs[0], img_metas[0], **kwargs)
>  File "/mmdetection/mmdet/models/detectors/single_stage.py", line 114, in simple_test
>    *outs, img_metas, rescale=rescale)
>  File "/mmdetection/mmdet/core/fp16/decorators.py", line 131, in new_func
>    return old_func(*args, **kwargs)
>  File "/mmdetection/mmdet/models/dense_heads/fcos_head.py", line 309, in get_bboxes
>    img_shape = img_metas[img_id]['img_shape']
>IndexError: too many indices for tensor of dimension 4

ERROR CODE:
```python
for img_id in range(len(img_metas)):
      cls_score_list = [cls_scores[i][img_id].detach() for i in range(num_levels)]
      bbox_pred_list = [bbox_preds[i][img_id].detach() for i in range(num_levels)]
      centerness_pred_list = [centernesses[i][img_id].detach() for i in range(num_levels)]
 ->   img_shape = img_metas[img_id]['img_shape']
      scale_factor = img_metas[img_id]['scale_factor']
```

**Comment by hhaAndroid** [comment]
@FibonacciZ This is not easy to judge, you can debug to see what img_shape is.

**Comment by FibonacciZ** [comment]
when i print 'img_metas' it just like below. But when i print img_metas[0]['img_shape'] it reports the same errors.
![S_(ID1VX%_9J1TB04WF{2MC](https://user-images.githubusercontent.com/27908488/128862574-c6861f83-58e0-42ba-9118-b5ee0154a9fe.png)

**Comment by PeterVennerstrom** [comment]
'''class BBoxTestMixin(object):
    """Mixin class for testing det bboxes via DenseHead."""

    def simple_test_bboxes(self, feats, img_metas, rescale=False):
        """Test det bboxes without test-time augmentation, can be applied in
        DenseHead except for ``RPNHead`` and its variants, e.g., ``GARPNHead``,
        etc.
        Args:
            feats (tuple[torch.Tensor]): Multi-level features from the
                upstream network, each is a 4D-tensor.
            img_metas (list[dict]): List of image information.
            rescale (bool, optional): Whether to rescale the results.
                Defaults to False.
        Returns:
            list[tuple[Tensor, Tensor]]: Each item in result_list is 2-tuple.
                The first item is ``bboxes`` with shape (n, 5),
                where 5 represent (tl_x, tl_y, br_x, br_y, score).
                The shape of the second tensor in the tuple is ``labels``
                with shape (n,)
        """
        outs = self.forward(feats)
        results_list = self.get_bboxes(*outs, img_metas, rescale=rescale)
        return results_list'''

Is your forward pass returning extra items in outs?  If so, it maybe interfering with the img_metas argument if a corresponding positional argument isn't defined in get_bboxes().  

''' @force_fp32(apply_to=('cls_scores', 'bbox_preds', 'centernesses'))
    def get_bboxes(self,
                   cls_scores,
                   bbox_preds,
                   centernesses,
                   img_metas,
                   cfg=None,
                   rescale=False,
                   with_nms=True):'''
