### ISSUE TITLE
How can I straighten the segmentation boundary?

### ISSUE THREAD

**Issue by haspberry** [open-mmlab/mmdetection#5847]
I am doing image segmentation with mask rcnn.
But image segmentation boundary is vaguely expressed.
I want straighten boundary.
What should I do?
Simply Increase data learning?

**Comment by hhaAndroid** [comment]
@haspberry If you are only image segmentation, you can try `mmseg`, if it is instance segmentation and the boundary is emphasized, you can consider increasing the roialign output size or the pointrend algorithm.
