### ISSUE TITLE
About Loading ResNet50 Pretrained Weights

### ISSUE THREAD

**Issue by SJLeo** [open-mmlab/mmdetection#5849]
I trained a ResNet50 weight with Top1 acc of 78.86%. However, when I loaded it into the backbone in Faster RCNN. I achieved worse performance than the weight of torchvsion://resnet50.pth (Top1 acc 76.1%). I only modified the backbone pretrained path of faster_rcnn_r50_fpn_1x_coco.py

**Comment by hhaAndroid** [comment]
@SJLeo You must first confirm whether the weights are imported correctly.

**Comment by SJLeo** [comment]
We have checked the log, and the log only indicates that the FC layer has not been loaded successfully

**Comment by hhaAndroid** [comment]
> ded successfu

This is normal.
