### ISSUE TITLE
FasterRCNN: 'xxx is not in the models registry'

### ISSUE THREAD

**Issue by lehaifeng000** [open-mmlab/mmdetection#5856]
when I try to create a custom model to replace the backbone of faster rcnn, the error happened. 
I follow the tutorial step by step and it's wrong.
![image](https://user-images.githubusercontent.com/29175644/128962031-a7848439-a3aa-407d-971c-3de7d6d308ac.png)
![image](https://user-images.githubusercontent.com/29175644/128962279-a624c494-e993-4ce7-ac0c-393abc5a9ee9.png)

**Comment by lehaifeng000** [comment]
I get the reason，when i install the mmdet, i use the 
```
pip install openmim
mim install mmdet
```
if i need to use custom model, i should install by git files
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"

**Comment by CharlesNJohn** [comment]
I face the same problem, followed the custom installation, it still persists!  
"MaskRCNN: 'CBSwinTransformer is not in the models registry'"
