### ISSUE TITLE
Cascade Mask rcnn model not produce any mAP values for test dataset or val dataset

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5865]
I am trying to run a cascade_mask_rcnn using my own dataset with same format of coco ones 
my problem is that when finishing from training , i used to plot a curve of mAP for bbox and segm with respect to epoch iteration , it is working good with almost all anchor based detector 
unfortunately , it does not work at all with this cascade_mask_rcnn. 

when checking what going on, i found that some of the losses become nan , and also see this information on val dataset: 
![cascade mask rcnn](https://user-images.githubusercontent.com/10245810/129076544-b8b8121b-bb98-4d75-b0f3-c792d9b236d9.JPG)

i don't know what shall i do to save on the mAP for each validate set at the end of each epoch , eventhough i used the same config file mentioned in config folder 

https://github.com/open-mmlab/mmdetection/blob/master/configs/cascade_rcnn/cascade_mask_rcnn_r101_fpn_1x_coco.py

i did the training for only one class , and did it on cascade rcnn , faster rcnn , mask rcnn and yolo v3 .. all those models are working fine ,with results as mAP ,and the ability to plot curve only this model not work. 

i used this function to plot the performance curve; 

`python tools/analysis_tools/analyze_logs.py plot_curve  path for my json file  --legend mAP`

any help or suggestion will be highly appreciated.

**Comment by RangiLyu** [comment]
Your loss became NAN. You need to refer to "Loss goes Nan" part in this doc https://github.com/open-mmlab/mmdetection/blob/master/docs/faq.md to solve this problem first.

**Comment by Jamestrump** [comment]
@alaa-shubbak Did you solved this loss became "NAN" part? I am also facing this same issue. Any kind of help will be appreciated.

**Comment by alaa-shubbak** [comment]
@Jamestrump 

now training is working correctly with me , i got values for mAP_bbox and mAP_segm .

@RangiLyu many thanks for your help and support.
