### ISSUE TITLE
No gt_bboxes_ignore in YOLOv3

### ISSUE THREAD

**Issue by ZephyrusKylin** [open-mmlab/mmdetection#5867]
I found that there is no 'gt_bboxes_ignore' parameter in the class YOLOV3Head， why？

**Comment by RangiLyu** [comment]
Not all heads use `gt_bboxes_ignore`. Only some heads with some assigners such as `MaxIoUAssigner` use this parameter.

**Comment by www516717402** [comment]
It will use IOF filter ignore bbox, however YOLOV3 use gt center assign. If you set inner anchor as filter by ignore_bbox will cause reduce precise. @ZephyrusKylin

**Comment by ZephyrusKylin** [comment]
> Not all heads use `gt_bboxes_ignore`. Only some heads with some assigners such as `MaxIoUAssigner` use this parameter.

There is no gt_bboxes_ignore in GridAssigner, so what should I do if I want to ignore some gt bboxes instead of considering them as negativte samples when computing loss?

**Comment by ZephyrusKylin** [comment]
> It will use IOF filter ignore bbox, however YOLOV3 use gt center assign. If you set inner anchor as filter by ignore_bbox will cause reduce precise. @ZephyrusKylin

Can you show more details? How is this operation reducing precise? 
@www516717402

**Comment by RangiLyu** [comment]
> > Not all heads use `gt_bboxes_ignore`. Only some heads with some assigners such as `MaxIoUAssigner` use this parameter.
> 
> There is no gt_bboxes_ignore in GridAssigner, so what should I do if I want to ignore some gt bboxes instead of considering them as negativte samples when computing loss? @RangiLyu

I'm afraid that you need to modify the GridAssigner and set the assigned label to -1 for anchors which have overlap with the gt_bboxes_ignore. You can refer to the code in other assigners.
