### ISSUE TITLE
Different anchor setting on different stages

### ISSUE THREAD

**Issue by taofuyu** [open-mmlab/mmdetection#5874]
**Describe the feature**
As an example, RetinaNet, for each feature map(stride=4,8,16, ...), we can set different anchor on it. For example:
anchor_generator=dict(
            type='AnchorGenerator',
            scales=[[2,4], [2,4,6], [2]],
            ratios=[[0.5], [0.5, 1.0], [0.5,1.0,2.0]],
            strides=[16, 32, 64],
            scale_major=False)

**Motivation**
In real practice, it is necessary to set different anchors on different stage.

**Comment by RangiLyu** [comment]
`AnchorGenerator` does not support setting different anchors on different levels. You can use `YOLOAnchorGenerator` or `SSDAnchorGenerator` to replace `AnchorGenerator`. These two anchor generator support this feature.

**Comment by taofuyu** [comment]
> `AnchorGenerator` does not support setting different anchors on different levels. You can use `YOLOAnchorGenerator` or `SSDAnchorGenerator` to replace `AnchorGenerator`. These two anchor generator support this feature.

But，the code is coupled. For example, using `SSDAnchorGenerator` means I can not use `RetinaHead`  `FocalLoss` at the same time, otherwise there will occur some errors during training.
