### ISSUE TITLE
Using optimizer Adam, why remove 'momentum=' for training?

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#5875]
In order to use the adam optimizer, SGD was changed to ADAM in the base model file and training was attempted. 
But there was an error telling me to remove the momentum. So I removed the momentum and the training was successful.
But why should I  remove Momentum to use Adam when it seems like Adaptive Momentum Estimation combines RMSProp and Momentum? 
Does Adam use momentum in MMDETECTION?

**Comment by PeterVennerstrom** [comment]
From the paper:

```Adam updates are directly estimated using a running average of first and second moment of the gradient.```

There isn't a fixed momentum setting for Adam.  The [underlying optimizer](https://pytorch.org/docs/stable/generated/torch.optim.Adam.html#torch.optim.Adam) is from Pytorch and doesn't a momentum argument.

**Comment by jshilong** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/682f03db0c0516324ec4e1e5d97e1d93c0a2485a/configs/detr/detr_r50_8x2_150e_coco.py#L141

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
