### ISSUE TITLE
How to get AP75 and AP[.5::.05::.95] when testing in VOC?

### ISSUE THREAD

**Issue by yanjk3** [open-mmlab/mmdetection#5876]
Just like the title, when testing(training) in COCO, I can get "bbox_mAP: 0.3760, bbox_mAP_50: 0.5870, bbox_mAP_75: 0.4080 ......".
But when testing(training) in VOC, only get "AP50: 0.8000, mAP: 0.8004", is there some ways can get the same result format like COCO?

**Comment by PeterVennerstrom** [comment]
The COCO results are calculated slightly differently than VOC using the COCO API.  

```iou_thr``` in voc.py could be set to a list of ious to yield results at more iou thresholds like COCO.  

To get the full COCO metrics on VOC, the VOC dataset could be converted to coco format and a new dataset could be created using coco.py as a template.

**Comment by yanjk3** [comment]
OK, thanks a lot!
I will try it .
