### ISSUE TITLE
How to retrieve img size when doing test detections?

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#5877]
My input images vary in image size. I am getting the area (in pixel units) based on the xmin, ymin, xmax, ymax detections. But I need to know the image size of the processed image upon going through the test_cfg.

This is what I am using to build the detector
```
model = build_detector(cfg.model, test_cfg=cfg.get("test_cfg"))
```

And it seems like (on the COCO dataset configuration), it resizes but keeps the image ratio.
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

So it means that **not all images are of 1333 x 800** because they may have different ratio.
What's an efficient way to retrieve the image sizes upon detections?

**Comment by jshilong** [comment]
There are `img_shape` in the `img_meta`

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
