### ISSUE TITLE
IS the bounding box detection coordinates relative to the original image?

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#5878]
When it goes through the mmdetection test_pipeline, it gets resized with or without keeping the ratio. But before that, there is an original image size. Are the detected bounding boxes coordinates (xmin, ymin, xmax, ymax) dependent on the original image size? 

There are ori_shape,  'img_shape',  and 'pad_shape on the Dataloader's outputs. Are the bounding boxes dependent on ori_shape?

**Comment by jshilong** [comment]
The `gt bboxes` would be resized from `ori_shape` to `img_shape` in `test_pipeline`

**Comment by jshilong** [comment]
Feel free to reopen the issue if  there is any question
