### ISSUE TITLE
problem about tools/convert_datasets/pascal_voc.py?

### ISSUE THREAD

**Issue by Peterisfar** [open-mmlab/mmdetection#589]
![QQ截图20190506131359](https://user-images.githubusercontent.com/31852119/57207519-de18f800-7000-11e9-8b8b-abcd108382ba.png)

annotations is list, part_annotations is dist...why annotations.expend() not annotations.append().

**Comment by hellock** [comment]
`part_annotations` should be a list.

**Comment by Peterisfar** [comment]
yes,you are right . 
mmcv.track_progress() return list.

thanks for your help!
