### ISSUE TITLE
Class mismatch during evaluation

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#5898]
Hello,

I seem to have found a bug in the evaluation scripts. When I save my formatted predictions, everything is correct (classes are assigned correctly). However, when I use the classwise evaluation and visualization scripts (following the instructions you provided precisely) some of the classes are incorrectly assigned. I noticed that only classes with similar characters are incorrectly assigned. For example, I have a class called 'personal_mobility' and 'person' of which all predictions get grouped as 'personal_mobility' in both the classwise and visualization results. This also happened in 'bicycle_rack' and 'bicycle' for which all predictions were assigned 'bicycle_rack'. All other classes are correct. Again, my formatted json outputs do not have this problem.

I did not use the bug template because I currently dont have time to produce the proper documentation of the issue, but wanted to bring this to your attention. I can add the error info later when I have more time (although it may not be necessary).

Is this something mmdetection is aware of?

**Comment by hhaAndroid** [comment]
Hi @pcicales Thanks for the feedback, I will check it immediately.

**Comment by hhaAndroid** [comment]
> Hello,
> 
> I seem to have found a bug in the evaluation scripts. When I save my formatted predictions, everything is correct (classes are assigned correctly). However, when I use the classwise evaluation and visualization scripts (following the instructions you provided precisely) some of the classes are incorrectly assigned. I noticed that only classes with similar characters are incorrectly assigned. For example, I have a class called 'personal_mobility' and 'person' of which all predictions get grouped as 'personal_mobility' in both the classwise and visualization results. This also happened in 'bicycle_rack' and 'bicycle' for which all predictions were assigned 'bicycle_rack'. All other classes are correct. Again, my formatted json outputs do not have this problem.
> 
> I did not use the bug template because I currently dont have time to produce the proper documentation of the issue, but wanted to bring this to your attention. I can add the error info later when I have more time (although it may not be necessary).
> 
> Is this something mmdetection is aware of?

@pcicales In order to facilitate the reproduction, can you use the issue template?

**Comment by jshilong** [comment]
@pcicales Sorry for the late response,  PR #5227 involves a serious bug that can make class mismatches during evaluation and the training performance seems better. And you can find the reason is that PR #5243, you can pull the master and fix it. 

I am really sorry for such a serious bug.
