### ISSUE TITLE
error while running fovea model , the error mentioned '[Errno 2] No such file or directory: '/tmp/tmpld7jkr8f/tmp72nstzu7.py'

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5901]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. yes 
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help. yes 
3. The bug has not been fixed in the latest version. yes

**Describe the bug**
I try to run a training model of fovea on my dataset with same format of COCO dataset (those dataset has been worked correctly using other models such as faster_RCNN and so on ) 
But i got such error during the running: 

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpld7jkr8f/tmp72nstzu7.py'
![error in running foveabox](https://user-images.githubusercontent.com/10245810/129673407-c820898c-6df9-4a05-a73b-87eb1325c24b.JPG)

**Reproduction**

1. What command or script did you run?

`python tools/train.py configs/human/fovea_align_r50_fpn_gn-head_mstrain_640-800_4x4_2x_coco.py --gpus 0 --work-dir training_data/fovea_r101`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
yes , i add the evaluation matrix , the running max epoch and change the number of categories to be one ('person') 
3. What dataset did you use?
my own dataset , which has same format to COCO dataset , i am pretty sure that the problem not form my dataset as i used it to train another model and it worked correctly, such as FCOS and faster_RCNN

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
![config file](https://user-images.githubusercontent.com/10245810/129674124-1652ec7e-4126-4f75-8aae-6a2f35b6a62a.JPG)

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
i installed it correctly ,as it worked with another models.

**Comment by hhaAndroid** [comment]
@alaa-shubbak It seems that the configuration file is wrong.

**Comment by LEE-SEON-WOO** [comment]
pip install -v -e .

**Comment by alaa-shubbak** [comment]
Thank you so much , now it works... it was the config file . On the other models existing  config files have most of dict needs , while on this types it just contains the head ,Nick and backbones detials..
