### ISSUE TITLE
Would mmdet support OTA (CVPR2021 paper)?

### ISSUE THREAD

**Issue by 4-0-4-notfound** [open-mmlab/mmdetection#5903]
**Describe the feature**
Add the code support for OTA (CVPR2021 paper)

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].
The idea behind the paper “OTA: Optimal Transport Assignment for Object Detection” is very interested in object detection. 
It can be expected that there will be many methods based on this paper in the future.
So I think mmdet should support this algorithm, so that it can be more convenient for comparison in the future.

**Related resources**
https://github.com/Megvii-BaseDetection/OTA

**Additional context**

**Comment by hhaAndroid** [comment]
@4-0-4-notfound There is no plan for the time being, but community PR is welcome.

**Comment by ZwwWayne** [comment]
For now, we support SimOTA used in YOLOX, a simpler and faster version of OTA, you might want to try that.
