### ISSUE TITLE
How to multi gpu training in single machine with jupyter notebook?

### ISSUE THREAD

**Issue by mybirth0407** [open-mmlab/mmdetection#5913]
Hi.

I want to multi GPU training with jupyter notebook.
My machine has 2 GPUs (Quadro RTX 6000), but I can't this machine efficiently.

In my code, training parts are bellow

```
model = build_detector(cfg.model)
datasets = [build_dataset(cfg.data.train)]
train_detector(model, datasets, cfg, distributed=False, validate=False)
```

In my thought, changing from `distributed = False` to `distributed =True` is enough to multi GPU training.
But the solution cannot the problem.

What can I do?

**Comment by RangiLyu** [comment]
I'm afraid that jupyter is not a good choice to start a distributed training process. Please use `dist_train.sh` script in `tools` folder.
