### ISSUE TITLE
Where can I edit bounding boxes and it's outputs? Can I even change for a pre-trained model?

### ISSUE THREAD

**Issue by CharlesNJ** [open-mmlab/mmdetection#5918]
Thinking of printing the output of the location of the object. Thank you for helping out in advance!

**Comment by jshilong** [comment]
- All predictions can be dumped to a pkl and then you can edit it.
You can refer to https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#test-existing-models
- If your pre-trained model means backbone, you can modify the checkpoint  `init_cfg` such as 
https://github.com/open-mmlab/mmdetection/blob/3280d43b813eb1cc7f77f270114a33de5a92fba9/configs/atss/atss_r50_fpn_1x_coco.py#L16.
- If you means whole model, you can use `load_from` to load the pre-trained model.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
