### ISSUE TITLE
The processing time of data sets with the same image and different formats is different

### ISSUE THREAD

**Issue by ywj509** [open-mmlab/mmdetection#5919]
After converting the data set in VOC format to the data set in coco format, the FPS decreases. Why?

**Comment by jshilong** [comment]
This is unreasonable, please check whether you use the same img_scale in the config

**Comment by ywj509** [comment]
I use the same image without changing the configuration. Is the image preprocessing different in different formats?

**Comment by jshilong** [comment]
> I use the same image without changing the configuration. Is the image preprocessing different in different formats?

As far as I know it will not

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
