### ISSUE TITLE
How did you calculate the training accuracy?

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#5920]
The accuracy value appears in the training log file, but I want to know how this is calculated.
How is the accuracy calculated?
May I know the formula?
It's on the train, but why isn't it on the test?

Please let me know how accurate it is.

**Comment by jshilong** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/3280d43b813eb1cc7f77f270114a33de5a92fba9/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L277.
Usually, we calculate the classification accuracy of positive samples.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by hyunjung0208** [comment]
Thank you,  but I had more questions, so I asked again.
SO, acc in training log file is only for classification, not segmentation?
If it also includes segmentation, please let me know the calculation formula such as 'precision=TP/(TP+FP)'.

**Comment by jshilong** [comment]
> SO, acc in training log file is only for classification, not segmentation?
yes
> If it also includes segmentation, please let me know the calculation formula such as 'precision=TP/(TP+FP)'.
Would you mind giving more details, I can not get what you mean

**Comment by hyunjung0208** [comment]
> > SO, acc in training log file is only for classification, not segmentation?
> > yes
> > If it also includes segmentation, please let me know the calculation formula such as 'precision=TP/(TP+FP)'.
> 
> Would you mind giving more details, I can not get what you mean

I am sorry that my English is not good.
First, is the training accuracy only for classification, not for DETECTION or SEGMENTATION?

**Comment by jshilong** [comment]
> > > SO, acc in training log file is only for classification, not segmentation?
> > > yes
> > > If it also includes segmentation, please let me know the calculation formula such as 'precision=TP/(TP+FP)'.
> > 
> > 
> > Would you mind giving more details, I can not get what you mean
> 
> I am sorry that my English is not good.
> First, is the training accuracy only for classification, not for DETECTION and SEGMENTATION?

Sorry for the late response, sure, it is a little difficult to define the accuracy of the training phase in Detection and Segmentation

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
