### ISSUE TITLE
Potiential bug when thers is multiple elements in `results['seg_fields']`

### ISSUE THREAD

**Issue by jshilong** [open-mmlab/mmdetection#5921]
https://github.com/open-mmlab/mmdetection/blob/3280d43b813eb1cc7f77f270114a33de5a92fba9/mmdet/datasets/pipelines/transforms.py#L271
We overwrite the same key `gt_semantic_seg` in a loop, which may cause potential bugs when 
there are multiple elements in the length of results["seg_fileds"].

#5747 gives a temporary solution, we need to remove `gt_semantic_seg` in the future.

**Comment by HarborYuan** [comment]
maybe it would be better to re-consider whether supporting multiple inputs in some other pipelines.

For example, 
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L207
The current version seems to have problems when entering multiple contents.

**Comment by ZwwWayne** [comment]
Solved in https://github.com/open-mmlab/mmdetection/pull/5747
