### ISSUE TITLE
Loading time for coco dataset is faster than torchvision coco dataset?

### ISSUE THREAD

**Issue by codesubmissionforpaper** [open-mmlab/mmdetection#5922]
Hi!
I have found that loading coco using the torchvision coco dataset leads to a very slow loading time, almost 6 seconds per batch. This leads to data loading being a cause for slower training.

Does mmdetection use a custom means for loading coco? Is it faster?

**Comment by jshilong** [comment]
Sorry, we did not compare the speed of loading coco before

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
