### ISSUE TITLE
请问库里的不同算法的功能是不是一样的

### ISSUE THREAD

**Issue by z905762202** [open-mmlab/mmdetection#5923]
每个算法的功能是不是都不是一样的 有的是目标检测 有的是语义分割。 我看到有yolo的 在这个里面就是目标检测是吧。 这里面的算法功能是根据它本来是干什么的 是吧？

**Comment by jshilong** [comment]
Most algorithms in this repo are related to object detection and instance segmentation, and you can find Semantic segmentation related algorithms in [mmsegmentation](https://github.com/open-mmlab/mmsegmentation)

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
