### ISSUE TITLE
Trying out HTC

### ISSUE THREAD

**Issue by ash1995** [open-mmlab/mmdetection#593]
I keep getting this error when I try to train the HTC model (python tools/train.py ./configs/htc/htc_r50_fpn_20e.py): "AttributeError: module 'torchvision.models.resnext' has no attribute 'model_urls'. Not sure why its loading resnext when I'm asking it to load resnet.

**Comment by hellock** [comment]
This is a compatibility bug of latest mmcv and torchvision. You can add a try-except to [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py#L110) to fix it.

**Comment by ash1995** [comment]
What's supposed to be the exception then? To use the open mmlab model? Currently, it loads the checkpoint based on the source of the model. In my case it was from torchvision, if I can't do that, how should I load the model checkpoint?

**Comment by hellock** [comment]
Should already been fixed in the latest mmcv.
