### ISSUE TITLE
KeyError: 'COCODataset is not in the dataset registry

### ISSUE THREAD

**Issue by Idolized22** [open-mmlab/mmdetection#5933]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
described in the title: "KeyError: 'COCODataset is not in the dataset registry" 
it didn't work either when i tried to add it as a custom dataset that inherits coco according to the [tutorial](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_dataset.md) 
yet i was able to train following the [colab tutorial](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb)

**Reproduction**

1. What command or script did you run?

```python tools/test.py \
    ${CONFIG_FILE} \
    ${CHECKPOINT_FILE} \
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?
a custom coco like dataset 
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
NVCC: Build cuda_11.4.r11.4/compiler.30188945_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.0

TorchVision: 0.9.0
OpenCV: 4.5.3
MMCV: 1.3.11
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.4
MMDetection: 2.15.1+4d965c8

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```  File "tools/test.py", line 237, in <module>
    main()
  File "tools/test.py", line 176, in main
    dataset = build_dataset(cfg.data.test)
  File "mmdet/datasets/builder.py", line 77, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "~/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'COCODataset is not in the dataset registry'

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@Idolized22 Hi, COCODataset -> CocoDataset

**Comment by Robotatron** [comment]
> @Idolized22 Hi, COCODataset -> CocoDataset

The tutorial here still uses "COCODataset" name
https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html
