### ISSUE TITLE
YOLOX pretrained models for m, l and x backbones

### ISSUE THREAD

**Issue by tikitong** [open-mmlab/mmdetection#5934]
Thank you very much for adding the brand new YOLOX model which has been doing very well recently on COCO.  
Would it be possible to have the pre-trained models (.pth) for the YOLOX-M, YOLOX-L and YOLOX-X backbones?  It could be very useful.

**Comment by hhaAndroid** [comment]
@tikitong We are already training, thank you for your attention.

**Comment by tikitong** [comment]
@hhaAndroid Do you have any idea when they will be available?

**Comment by bogdan-evtushenko** [comment]
> @tikitong We are already training, thank you for your attention.

Hi, are there any updates about it, may be it's possible to use the weights from the original repo of YOLOX?

**Comment by hhaAndroid** [comment]
> @hhaAndroid Do you have any idea when they will be available?

Will be released after National Day.

**Comment by hhaAndroid** [comment]
> > @tikitong We are already training, thank you for your attention.
> 
> Hi, are there any updates about it, may be it's possible to use the weights from the original repo of YOLOX?

I don’t know if there is a need for this. If you think it’s necessary, we can provide a conversion script.

**Comment by AndyYuan96** [comment]
> > > @tikitong We are already training, thank you for your attention.
> > 
> > 
> > Hi, are there any updates about it, may be it's possible to use the weights from the original repo of YOLOX?
> 
> I don’t know if there is a need for this. If you think it’s necessary, we can provide a conversion script.

hi,  I want to use the conversion script, can you share with me, thank you very much.

**Comment by AndyYuan96** [comment]
> > > > @tikitong We are already training, thank you for your attention.
> > > 
> > > 
> > > Hi, are there any updates about it, may be it's possible to use the weights from the original repo of YOLOX?
> > 
> > 
> > I don’t know if there is a need for this. If you think it’s necessary, we can provide a conversion script.
> 
> hi, I want to use the conversion script, can you share with me, thank you very much.

already write one by myself

**Comment by ALPAHz** [comment]
I want to use YOLOX-m training weight ,could you share your script with me?Thanks! @hhaAndroid
