### ISSUE TITLE
Why the num of outputs is not equal to length of dataset? 

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#5938]
I try to train the retinanet with val dataset for testing. The length of dataset is 4952. And I set the batch_size  to 18. After training 1 epoch, the total iterations are 276. The length of dataset cannot divide the batch_size, so the size of the last batch should be 2. Therefore length of the total outputs of an epoch should be the same as the length of dataset. But I get 4968(=276*18). I get the outputs of each batch through anchor_head.get_bboxes and bbox_results = [bbox2result(....).....]. Then concat them to get the total outpus. Why does this happen?

**Comment by hhaAndroid** [comment]
@Icecream-blue-sky This is because drop_last is true by default.

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky This is because drop_last is true by default.

I have checked the code and find that drop_last is False by default. Even if the drop_last is true, since the length of dataset is 4952, the length of outputs should be 4950 not 4968.

**Comment by hhaAndroid** [comment]
This is because GroupSampler will perform additional operations.

```python
class GroupSampler(Sampler):

    def __init__(self, dataset, samples_per_gpu=1):
        assert hasattr(dataset, 'flag')
        self.dataset = dataset

        for i, size in enumerate(self.group_sizes):
            self.num_samples += int(np.ceil(
                size / self.samples_per_gpu)) * self.samples_per_gpu
```

**Comment by hhaAndroid** [comment]
@Icecream-blue-sky Training process or testing process?

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky Training process or testing process?

At training process

**Comment by hhaAndroid** [comment]
> > @Icecream-blue-sky Training process or testing process?
> 
> At training process

It seems unnecessary.
