### ISSUE TITLE
数据增强支持Cutmix、Grid Mask吗？

### ISSUE THREAD

**Issue by kingbirdWc** [open-mmlab/mmdetection#5942]
您好，请问数据增强支持Cutmix、Grid Mask吗？

**Comment by hhaAndroid** [comment]
@kingbirdWc mmdet is temporarily not supported, but mmcv should already be supported.

**Comment by kingbirdWc** [comment]
mmcv上也没有哦
![image](https://user-images.githubusercontent.com/23066646/130587333-c70f850c-45cf-482b-9814-a4687c5e2886.png)

**Comment by hhaAndroid** [comment]
@kingbirdWc Sorry. Indeed.

**Comment by kingbirdWc** [comment]
No problem， Thank you anyway
