### ISSUE TITLE
centerness gt in ATSS

### ISSUE THREAD

**Issue by baibaidj** [open-mmlab/mmdetection#5948]
Hi. When I looked at the ATSS-related config and code, I cannot pinpoint where the centerness gt is initially generated. 

The ATSS training config uses [coco_detection.py](https://github.com/open-mmlab/mmdetection/blob/05181ba532437583f1cf66a8b3e04bb6bbf9de39/configs/_base_/datasets/coco_detection.py#L14) as its dataset, but there is not 'centerness' included in the Collect function. 

The ATSS model is a subclass of single stage detector and uses the inherited [forward_train](https://github.com/open-mmlab/mmdetection/blob/05181ba532437583f1cf66a8b3e04bb6bbf9de39/mmdet/models/detectors/single_stage.py#L83) method that does not contain a 'centerness' argument, which also does not appear when the self.bbox_head.forward_train() is called. 

And yet, the actual [atss_head](https://github.com/open-mmlab/mmdetection/blob/05181ba532437583f1cf66a8b3e04bb6bbf9de39/mmdet/models/dense_heads/atss_head.py#L219) has a loss method that expects 'centerness' argument. 

I'm quite confused here, so could please provide some suggestions?

**Comment by PeterVennerstrom** [comment]
The atss_head's loss_single() method calls the centerness_target() method to generate the centerness targets from the anchors and bbox_targets.  

The centerness argument the loss_single() method takes as input is the model output returned by the forward_single() method to be compared with the centerness_target.

**Comment by baibaidj** [comment]
> The atss_head's loss_single() method calls the centerness_target() method to generate the centerness targets from the anchors and bbox_targets.
> 
> The centerness argument the loss_single() method takes as input is the model output returned by the forward_single() method to be compared with the centerness_target.

Got you. Thanks.
