### ISSUE TITLE
MMDetection scripts does not work in Kaggle envs/notebooks

### ISSUE THREAD

**Issue by neel04** [open-mmlab/mmdetection#5949]
**Checklist**

- [x] I have searched related issues but cannot get the expected help.
- [x] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the latest version.

**Describe the bug**
Cannot run `MMdetection` script on Kaggle due to ImportError - problem is in the `train.py` script where the imports fail, but not in a normal kaggle notebook. Thankfully, the bug is easy to reproduce on any kaggle notebook.

**Reproduction**

1. What command or script did you run?

Kaggle Notebook
```py
# Installation ----------------------------------------
!pip install mmcv-full

!git clone https://github.com/open-mmlab/mmdetection.git
%cd mmdetection
!pip install -r requirements.txt

# trying to see whether the command works
%cd mmdetection
!python3 tools/train.py -h
%cd ..
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? `NO`
3. What dataset did you use? `Custom dataset converted to COCO`

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```py
Traceback (most recent call last):
  File "collect_env.py", line 4, in <module>
    import mmdet
ModuleNotFoundError: No module named 'mmdet'
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] `Preinstalled`
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

So all in all, we cannot seem to be using any packages in the kaggle env
```none
Traceback (most recent call last):
  File "tools/train.py", line 14, in <module>
    from mmdet import __version__
ModuleNotFoundError: No module named 'mmdet'
```

**Bug fix**
I can't triangulate the reason - the commands that error out in script form run in normal kaggle notebooks.

This seem to be a crucial problem with the package and its lack of operability in kaggle.
## Note: This problem is only present with `mmcv` and `mmdet` - all other packages can be imported and work as expected

**Comment by neel04** [comment]
@AronLin Should I open a new issue for this, or just leave it here?

**Comment by AronLin** [comment]
It seems that you have not set the config file path in this command.

    !python3 tools/train.py -h

**Comment by neel04** [comment]
I am?
```py
!python ./mmdetection/tools/train.py  "./mmdetection/new_config.py" --work-dir='./' --no-validate --gpus=1 --seed=42 --deterministic --launcher="pytorch"
```

**Comment by AronLin** [comment]
_base_ = './........._coco.py'

1. you can check whether `args.config` is correct.
2. Does _base_ here have cyclic inheritance problems?

**Comment by neel04** [comment]
the new config, which inherits from the `base` config resides in `./mmdetection/` while the `base` config resides in `./`, for the checkpoints' arg `load_from` = `./checkpoints/...`

Do you think that the files paths are correct, or should I just use absolute paths?

I can't check `args.config` since I can't load the config file due the above error :(

> Does base here have cyclic inheritance problems?
It kinda does actually...

```py

_base_ = 'htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_adamw_20e_coco.py'

model = dict(
    roi_head=dict(
        bbox_head=[
            dict(
                type='ConvFCBBoxHead',
                num_shared_convs=4,
                num_shared_fcs=1,
                in_channels=256,
                conv_out_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=80,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                reg_decoded_bbox=True,
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                loss_cls=dict(
                    type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
                loss_bbox=dict(type='GIoULoss', loss_weight=10.0)),
            dict(
                type='ConvFCBBoxHead',
                num_shared_convs=4,
                num_shared_fcs=1,
                in_channels=256,
                conv_out_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=80,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                reg_decoded_bbox=True,
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                loss_cls=dict(
                    type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
                loss_bbox=dict(type='GIoULoss', loss_weight=10.0)),
            dict(
                type='ConvFCBBoxHead',
                num_shared_convs=4,
                num_shared_fcs=1,
                in_channels=256,
                conv_out_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=80,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                reg_decoded_bbox=True,
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                loss_cls=dict(
                    type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
                loss_bbox=dict(type='GIoULoss', loss_weight=10.0))
        ]
    )
)
```
I just inherited it again since I wanted to add my own dataset and other params.

I am using [this model](https://github.com/VDIGPKU/CBNetV2/blob/main/configs/cbnet/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.py) 
can you confirm you can load the config file correctly without any errors?

**Comment by AronLin** [comment]
> I can't check `args.config` since I can't load the config file due the above error :(

just print its value before `Config.fromfile(args.config)`.

I can not reimplement this bug in our codebase.

**Comment by AronLin** [comment]
>Do you think that the files paths are correct, or should I just use absolute paths?

You can try this, I can not find any other bugs, it is confusing that it can not find a _temp_ file.

>FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpq_gazn52/tmp__0w_odj.py'

**Comment by neel04** [comment]
no cigar, it's just the same tmp error. :cry: 

Kaggle Reproducer (CPU):-
```py
!mkdir checkpoints
!wget -c https://github.com/CBNetwork/storage/releases/download/v1.0.0/htc_cbv2_swin_base22k_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.pth.zip -O ./chkp.zip
!unzip ./chkp.zip -d -o ./checkpoints/
!wget "https://raw.githubusercontent.com/VDIGPKU/CBNetV2/main/configs/cbnet/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.py" -O ./mmdetection/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_adamw_20e_coco.py

!cd ./mmdetection; pip install -v -e .

# ---------------------------- [NEW CELL SHOULD BE USED] -----------------------------------
%%writefile ./mmdetection/new_config.py
# The new config inherits a base config to highlight the necessary modification
_base_ = '/kaggle/working/mmdetection/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_adamw_20e_coco.py'

# We also need to change the num_classes in head to match the dataset's annotation
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=3)))

# Modify dataset related settings
dataset_type = 'COCODataset'
classes = ('a','b', 'c')
data = dict(
    train=dict(
        img_prefix='/kaggle/working/asd.txt',
        classes=classes,
        ann_file='/kaggle/working/train_coco/jsa.json'),
    val=dict(
        img_prefix='/kaggle/working/v_coco/',
        classes=classes,
        ann_file='/kaggle/working/val_coco/labels.json'),
    test=dict(
        img_prefix='/kaggle/working/v_coco/',
        classes=classes,
        ann_file='/kaggle/working/v_coco/labels.json'))

load_from = '/kaggle/working/checkpoints/htc_cbv2_swin_base22k_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.pth'

# optimizer
# lr is set for a batch size of 8
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)

# the max_epochs and step in lr_config need specifically tuned for the customized dataset
runner = dict(max_epochs=8)
log_config = dict(interval=100)
# ---------------------------- [NEW CELL SHOULD BE USED] -----------------------------------

# the max_epochs and step in lr_config need specifically tuned for the customized dataset
runner = dict(max_epochs=8)
log_config = dict(interval=100)

!python3 ./mmdetection/tools/train.py  "/kaggle/working/mmdetection/new_config.py" --work-dir='/kaggle/working' --launcher="pytorch"
```
Let's get this bug to reproduce first. It doesn't even get to processing the args, and it seems reproducible by me - ping if this can't.

I tried using absolute paths but its obviously a bug now :shrug:

**Comment by neel04** [comment]
Made a new issue above for a cleaner thread ^^^
