### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'ReduceOp'

### ISSUE THREAD

**Issue by nuanyang123** [open-mmlab/mmdetection#595]
pytorch0.4.1. Got above error when training custom dataset. What's wrong with it?

**Comment by hellock** [comment]
PyTorch 0.4.1 is not longer supported by the master branch. You need either checkout to the old pytorch-0.4.1 branch or upgrade to the latest pytorch.

**Comment by nuanyang123** [comment]
@hellock  The version I used was just pytorch 0.4.1branch, not the master branch.

**Comment by hellock** [comment]
You can modify [`dist.ReduceOp`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/text.py#L30) to `dist.reduce_op`. However, I recommend to upgrade to new versions since the pytorch-0.4.1 branch will receive no new features and bug fixes.
