### ISSUE TITLE
gts, dets, recall, ap?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#5955]
What does gts, dets, recall, and ap mean in voc dataset evaluation?
<img width="244" alt="dffdd" src="https://user-images.githubusercontent.com/9031472/131041965-a6a4a7ec-8404-4cd9-aca2-a277395a42cf.PNG">

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.

**Comment by cena001plus** [comment]
> * gts: number of bboxes of this class in your dataset
> * dets: the detect bboxes used to evaluate
> * recall: recall，a common metric used in the detection
> * ap: average precision, a common metric used in the detection

There is too much difference between the number of dets and the number of gts, is it not filtered by the box, such as the confidence threshold, nms? Is the prediction box for calculating recall and precision dets?

@jshilong

**Comment by cena001plus** [comment]
> * gts: number of bboxes of this class in your dataset
> * dets: the detect bboxes used to evaluate
> * recall: recall，a common metric used in the detection
> * ap: average precision, a common metric used in the detection

There is too much difference between the number of dets and the number of gts, is it not filtered by the box, such as the confidence threshold, nms? Is the prediction box for calculating recall and precision dets?

@jshilong
