### ISSUE TITLE
How to display eval mAP result for only two classes( dataset type VOC) while testing?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#5956]
Running the code: python tools/test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py checkpoints/faster_rcnn_r50_fpn_1x_voc0712_20200624-c9895d40.pth --eval mAP

Currently my result is shown for all 20 classes. How to display the result for only two classes? What changes should me made in what files? Can anyone please help me. I would really appreciate it.
<img width="244" alt="dffdd" src="https://user-images.githubusercontent.com/9031472/131042455-71497fea-c980-4752-a902-05c05daec050.PNG">

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.

**Comment by Soodep** [comment]
Even after changing the number of classes and class names to only person and car, I get the same results, in fact i get this unusual result when i run the --show command
![image](https://user-images.githubusercontent.com/9031472/131400148-b7ae1493-2570-4065-8bce-e0a56bd93d99.png)
I am only getting classes aeroplane and bicycle results. But I have changed the name of classes to CLASSES = ('car', 'person')
