### ISSUE TITLE
XCB Plugin Issue

### ISSUE THREAD

**Issue by tan-june** [open-mmlab/mmdetection#5957]
Hi!

I was using test.py on Google Collab (GC) and am receiving an XCB plugin issue. I understand I don't have access to a display on GC.

For the "--show" function in test.py, could you point me to the direction where it sends it to display? I would like to edit this and save it as an image instead so I can view these images.

I appreciate any help you can provide.

-TS

**Comment by jshilong** [comment]
You can save the image to a directory by specifying `--show-dir`
You can refer to https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#test-existing-models

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
