### ISSUE TITLE
用VOC数据集测试faster_rcnn性能，--eval recall时报错，--eval mAP不报错

### ISSUE THREAD

**Issue by XFFwin** [open-mmlab/mmdetection#5959]

**Comment by jshilong** [comment]
Seems we need to assert the results format when using `recall` metric.

**Comment by XFFwin** [comment]
Excuse me , how to assert the results format?

**Comment by jshilong** [comment]
> Excuse me , how to assert the results format?

The metric recall can only be applied to RPN

`Seems we need to assert the results format when using recall metric.` means we will assert `recall`  can only be applied to the outputs of `RPN`

**Comment by XFFwin** [comment]
Ok, get it! Thank you!

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any quesition
