### ISSUE TITLE
Can mmdetection run with cuda 8?

### ISSUE THREAD

**Issue by djiajunustc** [open-mmlab/mmdetection#596]
Hi,
Since the nvidia driver vision of my machine is 381.22, cuda >9 will cause insufficient driver version error.
Could mmdetection run with cuda 8?

**Comment by hellock** [comment]
CUDA 8 is no longer supported in the latest PyTorch. CUDA 9 or CUDA 10 is required for running mmdetection. You may need to upgrade the driver.

**Comment by djiajunustc** [comment]
Thanks a lot
