### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'mmdet.ops.dcn' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ty199931** [open-mmlab/mmdetection#5961]
when I run the process, I found the issue.And I try a lot of ways, But it is not useful. What can I do to deal with it?
when it run here:    from . import deform_conv_cuda
the error appear:
File "/home/ty/model/polar mask/demo/demo_visualize.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result_pyplot
  File "/home/ty/model/polar mask/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/ty/model/polar mask/mmdet/apis/inference.py", line 10, in <module>
    from mmdet.core import get_classes
  File "/home/ty/model/polar mask/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/ty/model/polar mask/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms, multiclass_nms_with_mask
  File "/home/ty/model/polar mask/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/ty/model/polar mask/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/ty/model/polar mask/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/ty/model/polar mask/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'mmdet.ops.dcn' (most likely due to a circular import) (/home/ty/model/polar mask/mmdet/ops/dcn/__init__.py)

**Comment by jshilong** [comment]
@Frank1o @ty199931 Sorry for late response, Could give more detail about the version of MMCV and MMDet? 
BTW, is there any modification of the code?

**Comment by Frank1o** [comment]
> @Frank1o @ty199931 Sorry for late response, Could give more detail about the version of MMCV and MMDet?
> BTW, is there any modification of the code?

Sorry for the late reply！
my version of MMCV and MMDet:
mmcv 0.4.3
mmdet 1.1
After analyzing it, I found that the torch version was automatically upgraded to1.9.0,and I reinstalled version 1.4.0，It works but the error still exist.
Fortunately，it no longer affects training and testing！
I think there may be a problem with C++ compilation, but I don't know how to fix it.

**Comment by ty199931** [comment]
OK，I will try it again by changing the version，and then,I will reply to you.Thanks very much.------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月29日(星期天) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] ImportError: cannot import name &#39;deform_conv_cuda&#39; from partially initialized module &#39;mmdet.ops.dcn&#39; (most likely due to a circular import) (#5961)

**Comment by ty199931** [comment]
> @Frank1o @ty199931 Sorry for late response, Could give more detail about the version of MMCV and MMDet?
> BTW, is there any modification of the code?
Sorry for the reply, I will try it again,then to reply to you.

**Comment by ty199931** [comment]
> @Frank1o @ty199931 Sorry for late response, Could give more detail about the version of MMCV and MMDet?
> BTW, is there any modification of the code?

Hello, I want to learn the Polar Mask，but it is based on mmdetection. And when I run the line:
from mmdet.apis import init_detector, inference_detector, show_result_pyplot, show_result 
it appears error:
Traceback (most recent call last):
  File "/home/ty/下载/PolarMask-master/demo/demo.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result_pyplot, show_result
  File "/home/ty/下载/PolarMask-master/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'

And I have compiled the mmdetection,but it doesn't work.  I don't know why. Please help me.

**Comment by jshilong** [comment]
Rm the `build` directory and rebuild it with `python setup.py build_ext --inplace`, then the package will be built locally.

**Comment by Frank1o** [comment]
> Rm the `build` directory and rebuild it with `python setup.py build_ext --inplace`, then the package will be built locally.

请问这样操作可以解决form.import deform_conv_cuda吗？重新编译会不会覆盖原始环境？
我之前环境是没有问题的，可以正常训练和测试，在一次可视化过程中，我安装了torchcam，然后我的torchvison就出了问题，卸载重装了torchviosn，发现torch版本随着重装更新了，然后出现了一系列错误（ImportError），在对torch版本降级后可以正常训练和测试，但是在ATO/mmdet/ops/_init_.py中，'get_compiler_version','get_compiling_cuda_version'报错,mmdet/ops/dcn/中依然存在form.import deform_conv_cuda问题，猜测可能是cpp编译出了错，不知道该如何解决

**Comment by jshilong** [comment]
For mmdet 1.1, you can use ~Pytorch 1.3 and rebuild it

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is ant question

**Comment by ty199931** [comment]
OK，thanks，I will try it as soon as possible ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月3日(星期五) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] ImportError: cannot import name &#39;deform_conv_cuda&#39; from partially initialized module &#39;mmdet.ops.dcn&#39; (most likely due to a circular import) (#5961)

**Comment by Frank1o** [comment]
how to get per-classes AP?

**Comment by cskate1997** [comment]
> OK，I will try it again by changing the version，and then,I will reply to you.Thanks very much.------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年8月29日(星期天) 下午5:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [open-mmlab/mmdetection] ImportError: cannot import name &#39;deform_conv_cuda&#39; from partially initialized module &#39;mmdet.ops.dcn&#39; (most likely due to a circular import) (#5961)

HI How did you solve this issue? 
I tried to change the version but the problem still exist? Can you help me out?

**Comment by Qianmengs** [comment]
I meet this issue too，I tried to change the version but the problem still exist，it just stopped while loading the model
