### ISSUE TITLE
Kitti camera calibration script for custom dataset

### ISSUE THREAD

**Issue by LawrenceXu13467** [open-mmlab/mmdetection#5962]
Is there a script so we can get similar camera calibration files for a custom dataset? Thank you.

**Comment by ZwwWayne** [comment]
It is about the camera intrinsic data, which is not provided in many datasets and is not used in mmdet.

**Comment by LawrenceXu13467** [comment]
Thank you, ZwwWayne. Sorry, I forgot to mention it's the Kitti dataset. 
In our case, we have a simulated dataset so we can generate all the camera info necessary. But we are unable to locate good documentation or a script to correctly generate the camera intrinsic labels based on the raw camera data. It would be much appreciated if you know a good resource or a link on how to do that in the right way. Thank you so much.

**Comment by ZwwWayne** [comment]
> Thank you, ZwwWayne. Sorry, I forgot to mention it's the Kitti dataset.
> In our case, we have a simulated dataset so we can generate all the camera info necessary. But we are unable to locate good documentation or a script to correctly generate the camera intrinsic labels based on the raw camera data. It would be much appreciated if you know a good resource or a link on how to do that in the right way. Thank you so much.

You can use camera calibration operations in opencv to generate that, e.g., https://docs.opencv.org/master/dc/dbb/tutorial_py_calibration.html. Hope it helps.

**Comment by LawrenceXu13467** [comment]
Thank you
