### ISSUE TITLE
When I trian FCOS on VOC, loss always is Nan.

### ISSUE THREAD

**Issue by FibonacciZ** [open-mmlab/mmdetection#5963]
When I use 'retinanet_r50_fpn_1x_voc0712.py'  to train retinanet, everything is ok. But I change the fcos config to  num_classes=20 and optimizer is the same as 'retinanet_r50_fpn_1x_voc0712.py'. the loss loss always is Nan. How can I solve this problem.

**Comment by jshilong** [comment]
- You can use `grad_clip` like https://github.com/open-mmlab/mmdetection/blob/3545915bf14f2acbb5def6355873f7a773149e62/configs/fsaf/fsaf_r50_fpn_1x_coco.py#L47
- Using a longer warmup iteration maybe helpful

**Comment by FibonacciZ** [comment]
> * You can use `grad_clip` like https://github.com/open-mmlab/mmdetection/blob/3545915bf14f2acbb5def6355873f7a773149e62/configs/fsaf/fsaf_r50_fpn_1x_coco.py#L47
> * Using a longer warmup iteration may be helpful

I success to train fcos on VOC, but mAP is 34.8.  The mAP of Retinanet on VOC is 77.3, 34.8 is so lower than 77.3. I dont know why. The config, based on 'fcos_r50_caffe_fpn_4x4_1x_coco.py', is as follows.
```
model = dict(bbox_head=dict(num_classes=20))
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict( _delete_=True, grad_clip=dict(max_norm=10, norm_type=2))
# learning policy
# actual epoch = 3 * 3 = 9
lr_config = dict(
    warmup='constant',
    warmup_iters=1000,
    warmup_ratio=1.0 / 3,
policy='step', step=[3])
# runtime settings
total_epochs = 4  # actual epoch = 4 * 3 = 12
```

**Comment by jshilong** [comment]
The result is unreasonable, but I have not done VOC-related experiments before, sorry I can’t give useful suggestions.

**Comment by BIGWangYuDong** [comment]
It may be related to the number of your GPUS, you need to adjust lr according to the number of your GPUS.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
