### ISSUE TITLE
meet an import Error problem when I try to import mmdet

### ISSUE THREAD

**Issue by JiayuZou-home** [open-mmlab/mmdetection#5964]
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by JiayuZou-home** [comment]
I found out that the problem is I install pytorch of cpu version. In fact, I should install pytorch of gpu version using the command below. With cuda 10.1, I follow the install directions in pytorch official websites and decide to install pytorch1.5.1.
pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
If we need to install other versions of pytorch, we can find the command in the following websites.
https://pytorch.org/get-started/previous-versions/

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
