### ISSUE TITLE
How can I resize the images using mmdet/datasets/transforms.py? 

### ISSUE THREAD

**Issue by amaanda** [open-mmlab/mmdetection#597]
I have tried to change the config file provided on the example, as in

```
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(640, 360),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=True,
        with_label=False,
        test_mode=True))
```

So that my input image which is 1280x720 would be rescaled to 640x360. My output looks the same so I am missing out something, can you tell me how to do this?

**Comment by hellock** [comment]
The config you provide should work fine. You just need to modify `img_scale` to test with different scales.

**Comment by amaanda** [comment]
I did, but still got the same output.

**Comment by hellock** [comment]
Have you printed the predicted bounding boxes w/ scores?
