### ISSUE TITLE
KeyError: 'LoadImageFromNdarray is not in the pipeline registry'

### ISSUE THREAD

**Issue by Ying-Kang** [open-mmlab/mmdetection#5970]
I completed the training of maskrcnn using mmocr
and I wanna infer one img with the training model
Through the given code in ipynb, I finished inferring with img path like:
```python
img = 'data/valid_imgs/292.jpg'
out_file = './result.jpg'
cfg = Config.fromfile('configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2015_mine.py')
checkpoint = "work_dirs/mask_rcnn_r50_fpn_160e_icdar2015_mine/latest.pth"
model = init_detector(cfg, checkpoint, device="cuda:0")
result = model_inference(model, img)
print(result)
```
but, when i change the img type into **ndarray** like i used to change in mmdet, error occured:
```python
KeyError: 'LoadImageFromNdarray is not in the pipeline registry'
```
my modified codes are as follow:
```python
img = cv2.imread('data/valid_imgs/292.jpg')
out_file = './result.jpg'
cfg = Config.fromfile('configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2015_mine.py')
checkpoint = "work_dirs/mask_rcnn_r50_fpn_160e_icdar2015_mine/latest.pth"
model = init_detector(cfg, checkpoint, device="cuda:0")
result = model_inference(model, img)
print(result)
```
i have checked the __init__.py in pipelines:
![image](https://user-images.githubusercontent.com/32356801/131281518-8d5ab530-b376-4b1e-9b4a-dbe28832afa8.png)
 and the loading.py
![image](https://user-images.githubusercontent.com/32356801/131282238-92d69bcf-f7f3-4ed9-a1ce-6b15202f03da.png)

 it seems that LoadImageFromNdarray is registered in mmocr but not found
i re-compiled the repo, and such error still occured
i'd appreciate it if you would offer help

**Comment by Ying-Kang** [comment]
this kind of error raised in mmcv:
![image](https://user-images.githubusercontent.com/32356801/131281907-fe5560cd-8bd6-4ae9-86b8-e81e20f7ba3b.png)
is there any version of mmcv i should change?
```
mmcv-full                 1.3.12
mmdet                     2.15.1
mmocr                     0.3.0 
```
so strange it is

**Comment by BIGWangYuDong** [comment]
Hi, did you install the environment by mim?

**Comment by BIGWangYuDong** [comment]
Did you change the code in minder? This seems that you change the code in mmocr but not change the code in minder?

**Comment by Ying-Kang** [comment]
> Did you change the code in mmdet? This seems that you change the code in mmocr but did not change the code in mmdet. Your pipeline is registry from mmdet.

i install mmdet via `pip install mmcv-full && pip install mmdet` as mentioned in mmocr's 'install.md'
so, it may not be the reason why it failed as i can infer with 'LoadImageFromFile'

**Comment by BIGWangYuDong** [comment]
You can try change the code in mmdet

**Comment by Ying-Kang** [comment]
> You can try change the code in mmdet

maybe that is the reason cause i didn't find LoadImageFromNdarray registered in mmdet
but why it traces back to mmdet's pipeline instead of mmocr's?
it would be puzzle if i care not only about mmocr but mmdet even mmcv blablabla...

**Comment by Ying-Kang** [comment]
> > You can try change the code in mmdet
> 
> maybe that is the reason cause i didn't find LoadImageFromNdarray registered in mmdet
> but why it traces back to mmdet's pipeline instead of mmocr's?
> it would be puzzle if i care not only about mmocr but mmdet even mmcv blablabla...

yes , i confirm that it registered in mmocr, but didn't registered in mmdet
mmocr just utlizes the 'Compose' in mmdet
![image](https://user-images.githubusercontent.com/32356801/131293966-8c31acef-94e3-4f05-b4ab-3fa4ec26550a.png)
and maybe mmocr should build its own "Compose" 
or update mmdet to fit such un-match method problem in other relevent repo
maybe this issue should be moved into mmocr's repo, : D
thx for your help

**Comment by gaotongxiao** [comment]
A hotfix is to add `import mmocr.datasets.pipelines.LoadImageFromNdarray` at the very beginning of your script so that `LoadImageFromNdarray` will be registered in mmdet's registry.

BTW, MMOCR has been using mmdet's registry and it's now being refactored to overcome such a flaw of design. After this PR (https://github.com/open-mmlab/mmocr/pull/458) has been merged, every reference to mmdet's method will be explicitly declared with a prefix `mmdet.` to avoid confusion.
