### ISSUE TITLE
train lvis05 dataset with scnet,but meet a error when evalution

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#5972]
Use load_from_local loader
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5000/5000, 4.2 task/s, elapsed: 1200s, ETA:     0s

Evaluating bbox...
Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 216, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/ubuntu/.conda/envs/scmask/lib/python3.8/site-packages/mmdet-2.12.0-py3.8.egg/mmdet/datasets/lvis.py", line 426, in evaluate
    nm = self.coco.load_cats(catId)[0]
  File "/home/ubuntu/.conda/envs/scmask/lib/python3.8/site-packages/lvis/lvis.py", line 140, in load_cats
    return self._load_helper(self.cats, ids)
  File "/home/ubuntu/.conda/envs/scmask/lib/python3.8/site-packages/lvis/lvis.py", line 117, in _load_helper
    return [_dict[id] for id in ids]
TypeError: 'int' object is not iterable

env:mmdet=2.12 cuda=11.1 pytorch=1.8.1

**Comment by BIGWangYuDong** [comment]
Hi, please use the “Error report” issue template.
Also, please check have you installed `LVIS dataset` successfully. (using `pip install git+https://github.com/lvis-dataset/lvis-api.git`)

**Comment by chensen668** [comment]
I'm sure the LVIS-API is installed, otherwise I can't train. In addition, I just replaced the coco dataset used by scnet network with lvis05 dataset, and other configurations have not been changed. After the training is successful, but the evaluation reported an error. Is it because scnet is invalid for LVIS dataset?

**Comment by BIGWangYuDong** [comment]
You can update your mmdet and mmcv version and try to evaluate again. If it still can't work, try to re-install a new environment again.

**Comment by BIGWangYuDong** [comment]
@chensen668 How did you fix this error?

**Comment by chensen668** [comment]
No, I think there is something wrong with the LVIS model trained by scnet. It's normal for me to download the official model and test it.
