### ISSUE TITLE
KeyError: "MaskRCNN: 'RefineRoIHead is not in the models registry'"

### ISSUE THREAD

**Issue by apanand14** [open-mmlab/mmdetection#5974]
Hello,

I'm new to mmdetection. I installed mmcv and mmdetection successfully on my windows. But When I train refine mask I'm getting this particular key error (which is mentioned in title). Please help me to solve this error and run successfully refine mask. 
https://github.com/zhanggang001/RefineMask

Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 126, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "C:\AI\RefineMask\venv\lib\site-packages\mmdet\models\builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "C:\AI\RefineMask\venv\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\AI\RefineMask\venv\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\AI\RefineMask\venv\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
****KeyError: "MaskRCNN: 'RefineRoIHead is not in the models registry'"****

**Comment by BIGWangYuDong** [comment]
Hi, maybe you should check your environment.
Maybe you have installed the mmdet in another folder. You can try to install mmdet under your folder,( use `pip install -v -e .` to install mmdet in your folder)

**Comment by apanand14** [comment]
Hey, I have installed properly in the same folder.  Basically I'm adding custom refine_mask_head.py in models/maskheads and also refine_roi_head.py in roi_heads. I made changes accordingly. Also using '@HEADS.register_module()' as discussed in mmdet documentation under customized models.  Still do not know what is the issue of registry I'm facing. Can you tell me if you know more about this? Thank you in advance.

**Comment by ZwwWayne** [comment]
Because the file is not imported. You need to update the corresponding __init__.py or use custom_imports in your config. See examples in https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module

**Comment by apanand14** [comment]
Thank you for your response. I have sucessfully resolved the issue.

**Comment by akaRainbowShine** [comment]
> Thank you for your response. I have sucessfully resolved the issue.

i have the same issue, could you show me the solution?

**Comment by Kerwin0621** [comment]
run: “pip install -v -e . " in your terminal, then solved

**Comment by xjq1042523740** [comment]
> 因为文件没有导入。您需要更新相应的`__init__.py`或在配置中使用 custom_imports 。[请参阅https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module)中的示例[](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module)



> Because the file is not imported. You need to update the corresponding `__init__.py` or use custom_imports in your config. See examples in https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module

Hello, this link is invalid, can you send it again?

**Comment by nskostas** [comment]
> 
> > 因为文件没有导入。您需要更新相应的__init__.py或在配置中使用 custom_imports 。[请参阅https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module)中的示例
> 
>  > Because the file is not imported. You need to update the corresponding __init__.py or use custom_imports in your config. See examples in https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module
> 
> Hello, this link is invalid, can you send it again?


Hi, I think this is the update link, but someone from the team could confirm. Thanks https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module
