### ISSUE TITLE
TypeError: CocoDataset: __init__() got an unexpected keyword argument 'times'

### ISSUE THREAD

**Issue by tuttelikz** [open-mmlab/mmdetection#5980]
Hi! Thanks for solid work. 👍

I have the following bug:

**Description**

I am receiving `TypeError: CocoDataset: __init__() got an unexpected keyword argument 'times'` while training from scratch _CocoDataset_ like custom dataset. The same bug occurs when I also run SSD, DETR, YoloV3. But there is no issue with models, such as VFNet, Cascade, RetinaNet. So I cannot see clear reason for now.

Look forward to your help,
Thank you! 🙏

**Reproduction**

I am running:

```bash
python centernet.py
```
where my `centernet.py` file is defined as below:

```bash
import torch
from mmcv import Config
from mmdet.apis import set_random_seed, train_detector
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from IPython.display import clear_output

cfg = Config.fromfile('./mmdetection/configs/centernet/centernet_resnet18_dcnv2_140e_coco.py')
DATASET_TYPE = 'CocoDataset'
PREFIX = '$path-to-my-images'
cfg.dataset_type = DATASET_TYPE
cfg.classes = ("CIN-1", "CIN-2", "CIN-3")

cfg.model.bbox_head.num_classes = 3

cfg.data.train.img_prefix = PREFIX
cfg.data.train.classes = cfg.classes
cfg.data.train.ann_file = '$path-to-train.json'
cfg.data.train.type = DATASET_TYPE

cfg.data.val.img_prefix = PREFIX
cfg.data.val.classes = cfg.classes
cfg.data.val.ann_file = '$path-to-val.json'
cfg.data.val.type = DATASET_TYPE

cfg.data.test.img_prefix = PREFIX
cfg.data.test.classes = cfg.classes
cfg.data.test.ann_file = '$path-to-test.json'
cfg.data.test.type = DATASET_TYPE

cfg.optimizer.lr = 0.01 / 8
cfg.optimizer_config.grad_clip = dict(max_norm=35, norm_type=2)
cfg.lr_config.policy = 'step'
cfg.lr_config.step = 7
#cfg.lr_config.warmup = None
#cfg.log_config.interval = 100

# Change the evaluation metric since we use customized dataset.
cfg.evaluation.metric = 'bbox'
# We can set the evaluation interval to reduce the evaluation
cfg.evaluation.interval = 4
# We can set the checkpoint saving interval to reduce the storage cost
cfg.checkpoint_config.interval = 4

# Set seed thus the results are more reproducible
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)

# we can use here mask_rcnn.
cfg.load_from = ''$path-to-pretrained-model.pth"
cfg.work_dir = ''$path-to-working-dir"

cfg.runner.max_epochs = 30
cfg.total_epochs = 30

clear_output()
model = build_detector(cfg.model)
datasets = [build_dataset(cfg.data.train)]

train_detector(model, datasets[0], cfg, distributed=False, validate=True)
```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```bash
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: True
GPU 0,1,2,3,4,5: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.2
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.5.3
MMCV: 1.3.12
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.15.1+3545915
```

2. I installed `mmdet ` with as follows:
- A.
```bash
conda create -n openmmlab python=3.7 -y
conda activate
```
- B.
```bash
pip install openmim
mim install mmdet
```

**Comment by hhaAndroid** [comment]
@tuttelikz  You have to check if you use RepeatDataset？Please refer to CenterNet cfg:

```python
dataset_type = 'CocoDataset'
data_root = 'data/coco/'

# Use RepeatDataset to speed up training
data = dict(
    samples_per_gpu=16,
    workers_per_gpu=4,
    train=dict(
        _delete_=True,
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=dataset_type,
            ann_file=data_root + 'annotations/instances_train2017.json',
            img_prefix=data_root + 'train2017/',
            pipeline=train_pipeline)),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
```

**Comment by tuttelikz** [comment]
Thanks for quick response, @hhaAndroid. Yes, it seems `RepeatDataset ` was causing that error. Commenting out that piece from config file resolved the issue!

**Comment by Dogeeeeeee** [comment]
hi，i met the same error and i would like to know to commenting which part of the code can make the code work.

**Comment by khalidcawl** [comment]
@tuttelikz which config file did you comment that out from?

**Comment by saadyousuf45** [comment]
any progress

**Comment by tuttelikz** [comment]
Hi guys, sorry for late reply. I am busyish with my disseration in near time. I experimented with this code long time ago and I don't remember clearly for now. Could you please try to comment out this one: https://github.com/open-mmlab/mmdetection/blob/e283bae020bcae5dab8298be2abe176b71f979f6/configs/centernet/centernet_resnet18_dcnv2_140e_coco.py#L97

**Comment by asd123pwj** [comment]
I also met this problem and the code in my_model.py as follows:
```python
data = dict(
    train=dict(dataset=dict(pipeline=train_pipeline)),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
```
I checked the code in my_dataset.py, there is no key 'dataset' in data['train'].keys, so I modified it as follows, and it works:
```python
data = dict(
    train=dict(pipeline=train_pipeline),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
```

**Comment by Lisuqiang228** [comment]
# dataset settings
dataset_type = 'VOCDataset'
data_root = 'C:\\Users\\Desktop\\mmdetection-main\\data\\'

# Example to use different file client
# Method 1: simply set the data root and let the file I/O module
# automatically Infer from prefix (not support LMDB and Memcache yet)

# data_root = 's3://openmmlab/datasets/detection/segmentation/VOCdevkit/'

# Method 2: Use `backend_args`, `file_client_args` in versions before 3.0.0rc6
# backend_args = dict(
#     backend='petrel',
#     path_mapping=dict({
#         './data/': 's3://openmmlab/datasets/segmentation/',
#         'data/': 's3://openmmlab/datasets/segmentation/'
#     }))
backend_args = None

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', scale=(640, 640), keep_ratio=True),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='Resize', scale=(640, 640), keep_ratio=True),
    # avoid bboxes being resized
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor'))
]
train_dataloader = dict(
    batch_size=8,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        # VOCdataset报错注释掉
        # type='RepeatDataset',
        # times=3,
        # 改成：
        type=dataset_type,
        data_root=data_root,
        ann_file='VOCdevkit\\VOC2007\\ImageSets\\Main\\train.txt',
        data_prefix=dict(sub_data_root='VOCdevkit\\VOC2007\\'),
        filter_cfg=dict(
            filter_empty_gt=True, min_size=32, bbox_min_size=32),
        pipeline=train_pipeline,
        backend_args=backend_args),
         )
    
        #VOC不报错使用RepeatDataset.
        # type='RepeatDataset',
        # times=3,
        # dataset=dict(
        #     type='ConcatDataset',
        #     # VOCDataset will add different `dataset_type` in dataset.metainfo,
        #     # which will get error if using ConcatDataset. Adding
        #     # `ignore_keys` can avoid this error.
        #     ignore_keys=['dataset_type'],
        #     datasets=[
        #         dict(
        #             type=dataset_type,
        #             data_root=data_root,
        #             ann_file='VOCdevkit\\VOC2007\\ImageSets\\Main\\train.txt',
        #             data_prefix=dict(sub_data_root='VOCdevkit\\VOC2007\\'),
        #             filter_cfg=dict(
        #                 filter_empty_gt=True, min_size=32, bbox_min_size=32),
        #             pipeline=train_pipeline,
        #             backend_args=backend_args),
        #     ])))

val_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='VOCdevkit\\VOC2007\\ImageSets\\Main\\val.txt',
        data_prefix=dict(sub_data_root='VOCdevkit\\VOC2007\\'),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args
    ))
test_dataloader = val_dataloader

# Pascal VOC2007 uses `11points` as default evaluate mode, while PASCAL
# VOC2012 defaults to use 'area'.
val_evaluator = dict(type='VOCMetric', metric='mAP', eval_mode='11points')
test_evaluator = val_evaluator

run：

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 788.00 MiB. GPU 0 has a total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 19.08 GiB is allocated by PyTorch, and 2.71 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables

**Comment by TheQYQ** [comment]
Thank you very much, the new version will need to be commented and rewritten. Comment the original train_dataloader and paste in what I wrote below：（mmdet3.3.0 mmcv2.1.0）

```
train_dataloader = dict(
batch_size=8,
num_workers=8,
persistent_workers=True,
sampler=dict(type='DefaultSampler', shuffle=True),
batch_sampler=dict(type='AspectRatioBatchSampler'),
dataset=dict(
type=dataset_type,
data_root=data_root,
ann_file='VOC2007/ImageSets/Main/trainval.txt',
data_prefix=dict(sub_data_root='VOC2007/'),
filter_cfg=dict(
filter_empty_gt=True, min_size=32, bbox_min_size=32),
pipeline=train_pipeline,
backend_args=backend_args))
```
