### ISSUE TITLE
YOLOX support FP16

### ISSUE THREAD

**Issue by RaymondByc** [open-mmlab/mmdetection#5981]
**Describe the feature**

when I add the line

> " fp16 = dict(loss_scale=512.) " 

to the config yolox, I encounter a problem, which is shown as follows:

![截图](https://user-images.githubusercontent.com/11907000/131435152-b08f4298-3380-49c7-9fcb-95e4c6408c26.PNG)

Does the YOLOX support FP16?

**Comment by hhaAndroid** [comment]
@RaymondByc Thank you for your feedback, we will fix it as soon as possible.
