### ISSUE TITLE
Why add reduce_mean(num_pos) for FCOS？

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#5988]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/fcos_head.py#L230
Is it necessary? Can I replace it to num_pos = max( len(num_pos), 1.0) ,  set different num_pos for different gpu ?

**Comment by hhaAndroid** [comment]
@clw5180 We implemented it according to the official code.

**Comment by clw5180** [comment]
Thanks
