### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#5999]
I did 'pip install mmcv-full=1.3.6'
![image](https://user-images.githubusercontent.com/78021183/131614949-60c7c0d1-caa6-4dbc-a975-9dad8d9be40f.png)

I checked the 'conda list' that mmcv-full was installed as shown in the picture. Afterwards, the demo file was run, and the error "no moule named 'mmcv_ext'" appeared as follows. How do we solve this?

![image](https://user-images.githubusercontent.com/78021183/131615092-ca38f9b5-cfca-4fe6-9192-a4b7a78d9225.png)

**Comment by AronLin** [comment]
Did you try to reinstall the `mmcv`?

**Comment by hyunjung0208** [comment]
yes, I tried it many time

**Comment by AronLin** [comment]
You can try to install a higher version of MMCV, and then test whether the runtime version is the version just installed. 
I guess there is a problem with path coverage.

**Comment by hyunjung0208** [comment]
sorry I don't understand "and then test whether the runtime version is the version just installed.
I guess there is a problem with path coverage."

I tried install mmcv=1.3.8 but it also failed

Do you have any recommendations about versions? Cudatoolkit, pytorch, torchvision, mmcv, all of them.

**Comment by AronLin** [comment]
1. I mean, you can use `mmdet.utils.collect_env` to check if the version of `mmcv-full` is correct.
2. maybe you can download the source code and build it by yourself.

    cd mmcv
    MMCV_WITH_OPS=1 python setup.py develop

**Comment by hyunjung0208** [comment]
'tail' is not recognized as an internal or external command,
operable program or batch file.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
sys.platform: win32
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: GeForce GTX 980
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
NVCC: Not Available
GCC: n/a
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192729112
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 2019
  - CPU capability usage: AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.3
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.8.0
OpenCV: 4.5.3
MMCV: 1.3.12
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a
MMDetection: 2.13.0+a8c681d
(mmcv_cpu3) PS C:\Users\kim\Desktop\mmcv_cpu2\mmdetection> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89


**use mmdet.utils.collet_env.py, I got that output.

I don't think I told you that I'm going to install it on Windows 10. I'm sorry.
I know mmdetection supports experiments on Windows. Still, I've seen a lot of people succeeding in running demo.py files on Windows 10. 
I think the mmcv._ext installation is not working well on Windows 10. The first error relates to that.
And I've also tried to build mmcv as a source, but there's an error in _ext.

Please recommend the versions available in Windows 10.**

**Comment by AronLin** [comment]
Ok, I suggest you create an issue in MMCV and Quote this issue.

**Comment by hyunjung0208** [comment]
I already opened ISSUE in MMCV.
However, I succeeded in running the DEMO file by installing the latest version.
Thank you.
