### ISSUE TITLE
Reduce the False Negative

### ISSUE THREAD

**Issue by Kindpire** [open-mmlab/mmdetection#600]
Hi,

Just wondering if I want to reduce the number of False Negatives, which hyperparameter in config files I can adjust? For example, I reduced the score_thr in test_cfg's rcnn setting and increased the max_per_img, however, there's no difference of the result. Any suggestion? Many thanks!

Cheers!

**Comment by hellock** [comment]
`score_thr` and `max_per_img` control the number of output bboxes. Increasing `score_thr` or decreasing `max_per_img` will reduce the number of outputs. If you refer to the training, there is no certrain answer and you need some expertise to figure it out.
