### ISSUE TITLE
Use Focal loss in YOLOv3

### ISSUE THREAD

**Issue by JJQQJJQQ** [open-mmlab/mmdetection#6001]
How can I use Focal loss ins yolov3 head?

**Comment by AronLin** [comment]
You need to modify the config file and yolo_head.py.
Pay attention to the difference between the target of BCE Loss and Focal loss.

**Comment by JJQQJJQQ** [comment]
@AronLin Thanks for your reply， its work now.

**Comment by guydaydayup** [comment]
> @AronLin Thanks for your reply， its work now.

can you tell me how to use focal loss in yolov3?
