### ISSUE TITLE
Pure Pytorch Implementation Model Export for Quantization

### ISSUE THREAD

**Issue by colceagus** [open-mmlab/mmdetection#6007]
Hi all, 

Is there a way to generate a pure PyTorch Python Model Implementation out of the model configuration ?
I'm looking something like tools/deployment/mmdet2torchserve.py to export a Python file with the PyTorch model. 

I want to be able to tweak the pure model to be able to quantize it (optimization using quantization). 

If not, is there a way to quantize a mmdetection model ? 

Thank you, 
Daniel.

**Comment by AronLin** [comment]
We don’t have such a feature for the time being.

**Comment by colceagus** [comment]
Is there a way to quantize a mmdetection model? 

Is there a way to quantize a mmdetection model, after it has been trained? 

Thank you!

**Comment by AronLin** [comment]
We have not considered model quantification.
If you can support it in MMDetection, we welcome your PR.
