### ISSUE TITLE
ImportError: cannot import name 'wrap_fp16_model'

### ISSUE THREAD

**Issue by SamMohel** [open-mmlab/mmdetection#6008]
i got this error 

```
  File "test.py", line 10, in <module>
    from mmcv.runner import (get_dist_info, init_dist, load_checkpoint,
ImportError: cannot import name 'wrap_fp16_model'
```

when tried to run test.py

**Comment by RangiLyu** [comment]
Did you install mmcv-full correctly? And please following the [issue template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) to provide more detailed information.

**Comment by SamMohel** [comment]
i have cuda 10 i used this command `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html`

**Comment by RangiLyu** [comment]
`mmcv/dist/cu110/torch1.7.0` means that you installed mmcv cuda11 version. Please install a correct version of mmcv-full that meets your cuda env.
