### ISSUE TITLE
NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmdetection#6013]
An error was reported during training: NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.
But the model can be trained and is converging. 
The training speed is very slow, data_time is greater than 2.

**Comment by RangiLyu** [comment]
Thank you for your feedback. Please open an issue in MMCV https://github.com/open-mmlab/mmcv
