### ISSUE TITLE
how to adjust model to detect densely occluded targets

### ISSUE THREAD

**Issue by dzz416** [open-mmlab/mmdetection#6018]
I would like to ask if there are other methods of NMS in mmdetection besides traditional NMS and SoftNMS? In addition, I am currently using mmdetection to do a detection, the occlusion overlap of the target is serious, how should I adjust the training and test parameters to make the effect better?

Now I use softnms and the score threshold is 0.1. The targets are all detected, but many targets will be marked with several boxes at the same time. How should I adjust?

**Comment by RangiLyu** [comment]
This is a crowd detection problem and currently, there is no such algorithm in mmdet yet. We planned to implement CrowdDet in the future but we do not have the manpower to do this recently.
