### ISSUE TITLE
NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmdetection#6021]
An error was reported during training: NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.
But the model can be trained and is converging.
The training speed is very slow, data_time is greater than 2.
Who can help me ?Thanks.

**Comment by jshilong** [comment]
@zhouzaida please take a look at this issue

**Comment by jshilong** [comment]
@qq1628qq Please give more detailed information in this issue

**Comment by jshilong** [comment]
duplicate issue  https://github.com/open-mmlab/mmcv/issues/1314
