### ISSUE TITLE
why is my mAP very low?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#6022]
Why is the mAP score very low even though the dets and gts number is very high? How is gts and dets related to the calculation of recall and ap? In general how is recall and ap calculated? 
I am using pascal voc dataset format.

![image](https://user-images.githubusercontent.com/9031472/131868869-467231ec-7359-4baa-b7af-0e72d35bfb6c.png)

**Comment by jshilong** [comment]
There is so much related material and you can easily find it via google.
Just an example,
https://datascience.stackexchange.com/questions/25119/how-to-calculate-map-for-detection-task-for-the-pascal-voc-challenge

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
