### ISSUE TITLE
analyze_results categories

### ISSUE THREAD

**Issue by firsakov** [open-mmlab/mmdetection#6023]
I have trained yolov3 on my own dataset in coco format.
Then i ran tools/test.py and analyze_results.py, and last one prints native coco categories instead of mine (i have them in json file and i put them to datasets/coco.py. but it still tries to find train, truck, person etc. 
Please help me, how to run analyze_results with my own categories?

**Comment by jshilong** [comment]
you need to modify the `CLASSES` in `coco.py` https://github.com/open-mmlab/mmdetection/blob/e876171cdf6cf09cb45fb7e62051365e35fca167/mmdet/datasets/coco.py#L23

**Comment by firsakov** [comment]
@jshilong  I did it and also added classes to my config file. i think problem is in analyze_results.py

https://github.com/open-mmlab/mmdetection/blob/e876171cdf6cf09cb45fb7e62051365e35fca167/tools/analysis_tools/analyze_results.py#L193

if I print dataset.CLASSES after this line it shows native coco classes but it's weird.
 I hardcoded dataset.CLASSES = (<my own classes>) in analyze_results, now it prints my categories on visualisation images, but gts are still zero and detections are awful... maybe you have any ideas?

**Comment by firsakov** [comment]
problem is it somehow doesn't go into build_dataset

**Comment by jshilong** [comment]
> problem is it somehow doesn't go into build_dataset

You may not use the modified version of mmdet in your local directory.
you can check it by executing the following command in your work directory and check whether the path is consistent with your modified mmdet.
command: `python -c "import mmdet; print(mmdet.__path__)"`

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
