### ISSUE TITLE
 iter_time: 4.304s, data_time: 3.125s

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmdetection#6026]
When I use yolox, the speed is very slow and it takes a long time. I noticed a problem with time and data_time. How to deal with it? thanks。iter_time: 0.404s, data_time: 0.025s

**Comment by qq1628qq** [comment]
I just took a look. It is now time=2.927 and data_time=2.720 .but other people is iter_time: 0.404s, data_time: 0.025s

**Comment by qq1628qq** [comment]
An error was reported during training: NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.
But the model can be trained and is converging.
The training speed is very slow, data_time is greater than 2.
Who can help me ?Thanks.

**Comment by jshilong** [comment]
Duplicate issue, please refer to #6021
