### ISSUE TITLE
 time=2.927 and data_time=2.720,

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmdetection#6027]
When i train vocdataset in yolox.I just took a look. It is  time=2.927 and data_time=2.720 .sometimes time>4or3. So slow. 
but other people is iter_time: 0.404s, data_time: 0.025s

**Comment by qq1628qq** [comment]
An error was reported during training: NO ROCm runtime is found,using ROCM_HOME='/opt/rocm'.
But the model can be trained and is converging.
The training speed is very slow, data_time is greater than 2.
Who can help me ?Thanks.

**Comment by jshilong** [comment]
Duplicate issue, please refer to #6021
