### ISSUE TITLE
MAKE mmdetection.exe by pyinstaller

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#6029]
from mmdetection.mmdet.apis import (async_inference_detector, inference_detector, init_detector, show_result_pyplot)

I am going to create an execution program with a model trained with mmdetection using pyinstaller.
Is there anything you need to pyinstaller mmdetection?
For example, Google API is .dist-info or pkg_resources.Py2_warn, etc. should be used additionally.

**Comment by hyunjung0208** [comment]
Please let me know please..
Or is there a tool to make Python application for mmdetection instead of pyinstall?

**Comment by hhaAndroid** [comment]
@hyunjung0208 We haven't done anything like this yet, sorry!
