### ISSUE TITLE
Plot Curve, x and y must have the same first dimension but have different shapes.

### ISSUE THREAD

**Issue by aliceinland** [open-mmlab/mmdetection#6031]
**Describe the bug**

When plotting the data with the analysis tool, an error on the mismatch of the array is generated.
**Reproduction**

1. What command or script did you run?

```python 
python3 tools/analysis_tools/analyze_logs.py plot_curve work_dirs/currect_classes/20210826_141250.log.json --keys loss_cls
```

Error: 
```python 
plot curve of work_dirs/currect_classes/20210826_141250.log.json, metric is loss_cls
Traceback (most recent call last):
  File "tools/analysis_tools/analyze_logs.py", line 179, in <module>
    main()
  File "tools/analysis_tools/analyze_logs.py", line 175, in main
    eval(args.task)(log_dicts, args)
  File "tools/analysis_tools/analyze_logs.py", line 79, in plot_curve
    plt.plot(
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2840, in plot
    return gca().plot(
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1743, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 273, in __call__
    yield from self._plot_args(this, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 399, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (6050,) and (50,)
```

**Environment**

sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.0a0+52ea372
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.2
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.1
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.2, CUDNN_VERSION=8.1.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0a0
OpenCV: 4.5.3
MMCV: 1.3.12
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.2
MMDetection: 2.16.0+1a39e5e

**Comment by zhixuanli** [comment]
Hi, has this bug been solved? I have encountered this bug today too. @hhaAndroid

**Comment by zytx121** [comment]
Hi @Williamlizl @zhixuanli 
Could you upload your `xxx.log.json` ?

**Comment by zhixuanli** [comment]
@zytx121 Thanks!
I finally used the `tensorboard` to visualize the log.

**Comment by wxmchgithub** [comment]
因为xs和ys中元素个数不匹配，xs中把val对应的iter算进去了，但是ys中只算了train，因此要自己把xs中的val去掉才行
