### ISSUE TITLE
version libcudart.so.10.1 not found 

### ISSUE THREAD

**Issue by mathshangw** [open-mmlab/mmdetection#6032]
i got when i run test.py 
`from mmcv.ops import RoIPool
ImportError: /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.10.1: version  libcudart.so.10.1 not found (required by /home/user/.local/lib/python3.6/site-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so)`

i have 

```
mmcv                          0.2.13              /usr/local/lib/python3.6/dist-packages/mmcv-0.2.13-py3.6-linux-x86_64.egg
```

**Comment by jshilong** [comment]
Please check whether the version of CUDA runtime in your environment is consistent with the version of CUDA to compile the MMCV

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
