### ISSUE TITLE
Missing '**kwargs' parameters passing to imshow_bboxes() in show_result() of rpn.py

### ISSUE THREAD

**Issue by MartaYang** [open-mmlab/mmdetection#6033]
https://github.com/open-mmlab/mmdetection/blob/bde7b4b7eea9dd6ee91a486c6996b2d68662366d/mmdet/models/detectors/rpn.py#L155

'**kwargs' parameters haven't passed to mmcv.imshow_bboxes() in show_result() of mmdetection/mmdet/models/detectors/rpn.py

**Comment by jshilong** [comment]
Thanks for your reporting. Would you mind creating a PR to fix it?

**Comment by MartaYang** [comment]
sure thing:)
