### ISSUE TITLE
Is Inf time (fps) measued on 8 GPUs?

### ISSUE THREAD

**Issue by MSTK2014** [open-mmlab/mmdetection#6035]
Is Inf time (fps) measued on 8 GPUs?

**Comment by jshilong** [comment]
The fps that is benchmarked at the end of the training epoch is with multiple GPUs, but it normally contains complex post-processes for the results, you can use `benchmark.py` to get a more accurate inference speed.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
