### ISSUE TITLE
Running benchmark.py reports an error

### ISSUE THREAD

**Issue by ilem777** [open-mmlab/mmdetection#6038]
Dear developer, I want to calculate the inference time of Faster R-CNN on my computer, so I am going to use the benchmark.py file. The command entered is as follows.
`python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_100.pth --launcher pytorch --fuse-conv-bn`
However, I encountered the following error report, how can I solve it? My computer system is Win10, GPU is Quadro P5000 single card, CUDA is 10.2. Thank you.
```
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 143, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 136, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\distributed_c10d.py", line 433, in init_process_group
    rendezvous_iterator = rendezvous(
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "D:\Anaconda3\envs\mmdetection_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\mmdetection_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
    main()
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['D:\\Anaconda3\\envs\\mmdetection_env\\python.exe', '-u', 'tools/analysis_tools/benchmark.py', '--local_rank=0', 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py', 'work_dirs/faster_rcnn_r50_
fpn_1x_coco/epoch_100.pth', '--launcher', 'pytorch', '--fuse-conv-bn']' returned non-zero exit status 1.
```

**Comment by jshilong** [comment]
The support for windows still is experimental, sorry can not check it  due to shorthanded for the time being

**Comment by jshilong** [comment]
@zhouzaida, Do you have any experience on launch multiprocess of torch on windows

**Comment by jshilong** [comment]
> Dear developer, I want to calculate the inference time of Faster R-CNN on my computer, so I am going to use the benchmark.py file. The command entered is as follows.
> `python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_100.pth --launcher pytorch --fuse-conv-bn`
> However, I encountered the following error report, how can I solve it? My computer system is Win10, GPU is Quadro P5000 single card, CUDA is 10.2. Thank you.
> 
> ```
> Traceback (most recent call last):
>   File "tools/analysis_tools/benchmark.py", line 143, in <module>
>     main()
>   File "tools/analysis_tools/benchmark.py", line 136, in main
>     init_dist(args.launcher, **cfg.dist_params)
>   File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 20, in init_dist
>     _init_dist_pytorch(backend, **kwargs)
>   File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 34, in _init_dist_pytorch
>     dist.init_process_group(backend=backend, **kwargs)
>   File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\distributed_c10d.py", line 433, in init_process_group
>     rendezvous_iterator = rendezvous(
>   File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
>     raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
> RuntimeError: No rendezvous handler for env://
> Traceback (most recent call last):
>   File "D:\Anaconda3\envs\mmdetection_env\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "D:\Anaconda3\envs\mmdetection_env\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
>     main()
>   File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\launch.py", line 255, in main
>     raise subprocess.CalledProcessError(returncode=process.returncode,
> subprocess.CalledProcessError: Command '['D:\\Anaconda3\\envs\\mmdetection_env\\python.exe', '-u', 'tools/analysis_tools/benchmark.py', '--local_rank=0', 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py', 'work_dirs/faster_rcnn_r50_
> fpn_1x_coco/epoch_100.pth', '--launcher', 'pytorch', '--fuse-conv-bn']' returned non-zero exit status 1.
> ```

if you just want to benchmark the speed, how about just using the command `python tools/analysis_tools/benchmark.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_100.pth --launcher pytorch --fuse-conv-bn`?

**Comment by ilem777** [comment]
@jshilong I tried your method but encountered a different error. I'm really sorry.
```
(mmdetection_env) F:\PycharmProjects\mmdetection_env\mmdetection>python tools/analysis_tools/benchmark.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_100.pth --launcher pytorch --fuse-
conv-bn
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 143, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 136, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 31, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "D:\Anaconda3\envs\mmdetection_env\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```
Also I want to know, will the fps calculated with test.py be more different than benchmark.py? If not, I'll just use the value calculated by test.py.
I would like to use this command line to run test.py, which will neither generate results and display, nor generate pkl files, nor export images. In this case, will the inference time be close to the benchmark.py result?
`python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_100.pth --fuse-conv-bn --format-only`

**Comment by shinya7y** [comment]
Does old code with `MMDataParallel` before https://github.com/open-mmlab/mmdetection/pull/5265 work?
https://github.com/open-mmlab/mmdetection/blob/2ca1323cf2754c88a57fe645163c0bf2cd79a3e0/tools/analysis_tools/benchmark.py

**Comment by ilem777** [comment]
@shinya7y Thanks for your prompt advice, I tested it and it ran successfully!!! My computer (Quadro P5000) ran Faster RCNN Resnet50 with a result of 15.8 FPS. I believe this result should be quite reasonable.
```
(mmdetection_env) F:\PycharmProjects\mmdetection_env\mmdetection>python tools/analysis_tools/benchmark.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_100.pth --fuse-conv-bn
D:\Anaconda3\envs\mmdetection_env\lib\site-packages\mmdet-2.15.1-py3.8.egg\mmdet\core\anchor\builder.py:16: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator``
  warnings.warn(
Use load_from_local loader
D:\Anaconda3\envs\mmdetection_env\lib\site-packages\mmdet-2.15.1-py3.8.egg\mmdet\core\anchor\anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors``
  warnings.warn('``grid_anchors`` would be deprecated soon. '
D:\Anaconda3\envs\mmdetection_env\lib\site-packages\mmdet-2.15.1-py3.8.egg\mmdet\core\anchor\anchor_generator.py:360: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  warnings.warn(
Done image [50 / 2000], fps: 15.7 img / s
Done image [100/ 2000], fps: 15.7 img / s
Done image [150/ 2000], fps: 15.7 img / s
Done image [200/ 2000], fps: 15.8 img / s
```

**Comment by TonojiKiobya** [comment]
Try to replace your benchmark.py file in your tools/analysis_tools/benchmark.py with the one given here
https://github.com/open-mmlab/mmdetection/blob/2ca1323cf2754c88a57fe645163c0bf2cd79a3e0/tools/analysis_tools/benchmark.py

Then issue the following command on the terminal you are using
python tools/analysis_tools/benchmark.py [path to your config file] [path to your epoch file]
