### ISSUE TITLE
When I use Cascade RCNN with OHEMSampler errored

### ISSUE THREAD

**Issue by Muke6** [open-mmlab/mmdetection#6039]
AttributeError: CascadeRCNN: RPNHead: OHEMSampler: 'RPNHead' object has no attribute 'bbox_head'.
mmdetection:2.16.0

**Comment by jshilong** [comment]
OHEM sampler only can be used in the second stage for the time being

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by Muke6** [comment]
I have solved it, thanks.

**Comment by xlinsist** [comment]
I have solved this problem. When you try to use "OHEMsampler" to replace "RandomSampler" in second stage( i.e. rcnn), you have to set the args "match_low_quality" to false. 
For example, you have to edit from this:

`
dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
`
to this(mind the difference in match_low_quality, it is set to True in dafault)
`
dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                match_low_quality=False, # here is the difference
                ignore_iof_thr=-1),
            sampler=dict(
                type='OHEMSampler',
                num=256,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
`

See [this](https://zhuanlan.zhihu.com/p/184618997) for reference(Chinese).

**Comment by gkgo** [comment]
> I have solved it, thanks.
Hello, I want to ask you how to solve AttributeError: 'RPNHead' object has no attribute 'bbox_head'.
When you try to use "OHEMsampler" to replace "RandomSampler" in second stage(cascade rcnn），I set the args "match_low_quality" to false.But the same error will be reported.
