### ISSUE TITLE
softmax focal loss

### ISSUE THREAD

**Issue by Taotaoxu** [open-mmlab/mmdetection#6040]
Hi, I encountered a problem when traing the RetinaNet with the **softmax_focal_loss**.
Here are my step:

1. Create a new script in the folder of  'mmdetection/models/losses/', named 'softmax_focal_loss.py'.
2. Create a new class '**SoftmaxFocalLoss**', just following the style of mmdetection/models/losses/focal_loss.py'. The main difference is the focal loss, I use the **mmcv.ops.softmax_focal_loss** instead of the  **mmcv.ops.sigmoid_focal_loss** anymore.
3. Parameter are set correctly, such as 'use_sigmoid=False', gamma=2, alpha=0.25.
4. I create tensor x, y to test this code. Then I can confirm that:   **py_softmax_focal_loss(x, y) == SoftmaxFocalLoss.Forward(x, y) == mmcv.ops.softmax_focal_loss**.
5. I change the config.py file at the bbox_head.loss_cls as:  **type=SoftmaxFocalLoss, use_sigmoid=False', gamma=2, alpha=0.25**.
6. I start to train the RetinaNet with this config.py. 
7. A problem is reported: '**variable is unreachable**'.
8. I replace the **mmcv.ops.softmax_focal_loss** with **py_softmax_focal_loss**. And train this model, it turns out a pretty good results with a high mAP.

**Comment by BIGWangYuDong** [comment]
Hi, need to use the issue template to give us more details, such as mmcv version. Also you need to check whether you installed mmcv or mmcv-full. It is suggest to install mmcv-full lastest version to run the code.

**Comment by ZwwWayne** [comment]
Hi @Taotaoxu ,
Thanks for the detail about your reimplementation. But we still not quite understand the error as it might be caused by many reasons. Could you post the full error log to give us more hints? You may also try to test the forward/backward of `py_softmax_focal_loss` and `mmcv.ops.softmax_focal_loss`.

**Comment by Uncolor-Duck** [comment]
> Hi, I encountered a problem when traing the RetinaNet with the **softmax_focal_loss**.
> Here are my step:
> 
> 1. Create a new script in the folder of  'mmdetection/models/losses/', named 'softmax_focal_loss.py'.
> 2. Create a new class '**SoftmaxFocalLoss**', just following the style of mmdetection/models/losses/focal_loss.py'. The main difference is the focal loss, I use the **mmcv.ops.softmax_focal_loss** instead of the  **mmcv.ops.sigmoid_focal_loss** anymore.
> 3. Parameter are set correctly, such as 'use_sigmoid=False', gamma=2, alpha=0.25.
> 4. I create tensor x, y to test this code. Then I can confirm that:   **py_softmax_focal_loss(x, y) == SoftmaxFocalLoss.Forward(x, y) == mmcv.ops.softmax_focal_loss**.
> 5. I change the config.py file at the bbox_head.loss_cls as:  **type=SoftmaxFocalLoss, use_sigmoid=False', gamma=2, alpha=0.25**.
> 6. I start to train the RetinaNet with this config.py.
> 7. A problem is reported: '**variable is unreachable**'.
> 8. I replace the **mmcv.ops.softmax_focal_loss** with **py_softmax_focal_loss**. And train this model, it turns out a pretty good results with a high mAP.
> 
> ### I wander why does this happen? Is the back-forward function of **mmcv.ops.softmax_focal_loss** crorrect ?

Could you share something about "py_softmax_focal_loss" with me? I can not find it anywhere. Thank you so much!

**Comment by jiangming0chen** [comment]
> Hi, I encountered a problem when traing the RetinaNet with the **softmax_focal_loss**. Here are my step:
> 
> 1. Create a new script in the folder of  'mmdetection/models/losses/', named 'softmax_focal_loss.py'.
> 2. Create a new class '**SoftmaxFocalLoss**', just following the style of mmdetection/models/losses/focal_loss.py'. The main difference is the focal loss, I use the **mmcv.ops.softmax_focal_loss** instead of the  **mmcv.ops.sigmoid_focal_loss** anymore.
> 3. Parameter are set correctly, such as 'use_sigmoid=False', gamma=2, alpha=0.25.
> 4. I create tensor x, y to test this code. Then I can confirm that:   **py_softmax_focal_loss(x, y) == SoftmaxFocalLoss.Forward(x, y) == mmcv.ops.softmax_focal_loss**.
> 5. I change the config.py file at the bbox_head.loss_cls as:  **type=SoftmaxFocalLoss, use_sigmoid=False', gamma=2, alpha=0.25**.
> 6. I start to train the RetinaNet with this config.py.
> 7. A problem is reported: '**variable is unreachable**'.
> 8. I replace the **mmcv.ops.softmax_focal_loss** with **py_softmax_focal_loss**. And train this model, it turns out a pretty good results with a high mAP.
> 
> ### I wander why does this happen? Is the back-forward function of **mmcv.ops.softmax_focal_loss** crorrect ?

May I ask you some questions about the softmax focal loss? jiangming_chen@126.com
