### ISSUE TITLE
Has anyone used Grad-CAM++?

### ISSUE THREAD

**Issue by Frank1o** [open-mmlab/mmdetection#6041]
I want to use Grad-CAM++ in the project.Has anyone tried and succeeded?

**Comment by AronLin** [comment]
We do not support this feature.

**Comment by RuoyuChen10** [comment]
> I want to use Grad-CAM++ in the project.Has anyone tried and succeeded?

I implement an example on yolo with grad-cam

Project: [https://github.com/RuoyuChen10/objectdetection-saliency-maps](https://github.com/RuoyuChen10/objectdetection-saliency-maps)
