### ISSUE TITLE
How to extract features of image?

### ISSUE THREAD

**Issue by YHDASHEN** [open-mmlab/mmdetection#6044]
Hi,

thank you for your great work. I have a question regarding how to only extract features of image. In my project, I don't need bounding box for each category. Just like multi-label classification, my output is several labels. How to load your pretrained model without bounding box then train with my dataset? By only loading the backbone pretrained model?

Best regards,
Hui

**Comment by BIGWangYuDong** [comment]
Hi, it seems that you can inherit the One-Stage Detector to create a new detector, then set the head to None and change several codes in the forward train or some other place. Also maybe you can use [mmcls](https://github.com/open-mmlab/mmclassification) to support your work.

**Comment by YHDASHEN** [comment]
Hi Mr. Wang,

thank you so much for your reply. 

Best,
Hui
