### ISSUE TITLE
Print mAP for only 2 classes while testing?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#6045]
I am using command : python tools/test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py checkpoints/faster_rcnn_r50_fpn_1x_voc0712_20200624-c9895d40.pth --eval mAP
to test images from KITTI dataset. I just want to use two classes: person and car. So I modified voc.py ( classes = person, car) and num_classes=2 in my config file . But I am getting this error. I am newbie and I would really appreciate anyone's help. Thank you.

File "/home/UNT/sd0570/mmdetection/mmdet/core/evaluation/mean_ap.py", line 463, in print_map_summary
label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: tuple index out of range

**Comment by BIGWangYuDong** [comment]
Firstly, it seems that your code is not the latest version, maybe you can update your mmdet code. 
Second, if you use the pre-trained checkpoint (the result of pre-trained ckpt is more than your classes), it might get an error. Also, it may get wrong if your set a new classes and use the pre-trained ckpt, such as the original ckpt classes are car, person, but you set your classes to person, car, it may make your inference wrong.

**Comment by Soodep** [comment]
Thank you so much! I will train my own model with only 2 classes, hopefully that works.

**Comment by Soodep** [comment]
@BIGWangYuDong I used the pre trained model along with the latest version and  these is the test result:
![image](https://user-images.githubusercontent.com/9031472/133493804-54891db0-33a5-488c-afdc-8db83f9a4da5.png)
Is there any way to evaluate results for only 2 classes?
