### ISSUE TITLE
Questions about submit a new PR

### ISSUE THREAD

**Issue by vealocia** [open-mmlab/mmdetection#6046]
Thanks for your great contribution to facilate the progress of computer vision!
Here is my question:
1. I want to create a new pull request for ```mmdetection``` to involve our new instance segmentation method ```QueryInst```. We prepare almost everything include source codes and pretrained weights. But I noticed that all pretrained weights provided by ```mmdetection``` are downloaded under ```https://download.openmmlab.com/``` domain. How can I put my pretrained weights to this domain?

**Comment by BIGWangYuDong** [comment]
Hi,
Firstly, thanks for using mmdet. To create a new PR, you should follow [contributing](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to prepare some pre-commit hook.
Then, you can first push your model and other important codes in this PR, and we will review them. After the review, we will contact you to get the pre-trained ckpt and log file.

**Comment by vealocia** [comment]
Thanks for your swift reply. I will close this issue and follow the instructions to create a new pull request.
