### ISSUE TITLE
fcos for MaxIoUAssigner

### ISSUE THREAD

**Issue by zgsxwsdxg** [open-mmlab/mmdetection#6048]
MaxIoUAssigner for fcos_head 中没找到相关调用，MaxIoUAssigner 在fcos中用到了没？，谢谢

**Comment by AronLin** [comment]
FCOS is an anchor free method, which uses the central positive sample assign strategy.

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/003f520cad88be52bd5fd44cdcab2d7ec45dd551/configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py#L45-L51

The config is confuse

**Comment by BIGWangYuDong** [comment]
It seems that if we delete train_cfg, it may get some error while training FCOS

**Comment by zgsxwsdxg** [comment]
> It seems that if we delete train_cfg, it may get some error while training FCOS

既然没有用到，就不应该配置文件中有该配置，这让人困惑

**Comment by BIGWangYuDong** [comment]
> > It seems that if we delete train_cfg, it may get some error while training FCOS
> 
> 
> 
> 既然没有用到，就不应该配置文件中有该配置，这让人困惑

🤷‍♂️🤷‍♂️🤷‍♂️ヽ(￣д￣;)ノ

**Comment by zgsxwsdxg** [comment]
> FCOS is an anchor free method, which uses the central positive sample assign strategy.

但是，mmdetection配置文件fcos算法中配置了MaxIoUAssigner，不知道为啥？

**Comment by AronLin** [comment]
> > FCOS is an anchor free method, which uses the central positive sample assign strategy.
> 
> 但是，mmdetection配置文件fcos算法中配置了MaxIoUAssigner，不知道为啥？

This is a legacy issue of the 2.0 version, which will be corrected in the next major version.
