### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.0'

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#6049]
AssertionError:
The NVIDIA driver on your system is too old (found version 10000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

env：
TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.5.3
MMCV: 1.0.5
MMDetection: ('2.3.0',)
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1
Python: 3.8.11 (default, Aug  3 2021, 15:09:35) [GCC 7.5.0]
CUDA available: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0

Finally, I want to know if CUDA 10.0 can no longer run on mmdet2. X？

**Comment by AronLin** [comment]
> CUDA available: False

This is a mismatch between your torch version and cuda version.

**Comment by chensen668** [comment]
OK，I know
