### ISSUE TITLE
test.py ERROR

### ISSUE THREAD

**Issue by hyunjung0208** [open-mmlab/mmdetection#6051]
I made and trained models in the Linux environment.
I created the same environment for Windows.
And I copied the CONFIG file and WORK_DIRS of the model I trained on Linux to Windows.
I only changed TEST, PRETRAINED, LOAD_FROM PATH in the model file I copied.
They copied images that were tested in the Linux environment and changed them to COCODATASET in the Windows environment.
Then I ran test.py('python tools/test.py configs/scar_c/original_step/resnet101_orgs.py work_dirs/resnet101_orgs/latest.pth --show-dir result/'), and the output was shown below.
And it keeps popping up that there is a file in the image folder but there is no specific file. May I know why this is so?

size mismatch for roi_head.bbox_head.0.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([81, 1024]).
size mismatch for roi_head.bbox_head.0.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([81]).
size mismatch for roi_head.bbox_head.1.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([81, 1024]).
size mismatch for roi_head.bbox_head.1.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([81]).
size mismatch for roi_head.bbox_head.2.fc_cls.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([81, 1024]).
size mismatch for roi_head.bbox_head.2.fc_cls.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([81]).
size mismatch for roi_head.mask_head.0.conv_logits.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
size mismatch for roi_head.mask_head.0.conv_logits.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
size mismatch for roi_head.mask_head.1.conv_logits.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
size mismatch for roi_head.mask_head.1.conv_logits.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
size mismatch for roi_head.mask_head.2.conv_logits.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
size mismatch for roi_head.mask_head.2.conv_logits.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).

**Comment by hhaAndroid** [comment]
@hyunjung0208 Please use the issue template, thank you.

**Comment by hyunjung0208** [comment]
sorry I don't know there is the issue template
