### ISSUE TITLE
Is it possible to save/load different weights for backbone/neck/rpn?

### ISSUE THREAD

**Issue by waddington** [open-mmlab/mmdetection#6053]
Using MMDetection we can train a model and then use this model as a base to fine-tune further down the line. We can also load ImageNet trained weights in the backbone.

I'd like to train some models but save the weights for the different parts of the model separately, and also be able to load these weights individually into their respective parts when training a new model.

I.e. I'd like to be able to train a cascade rcnn model and then use the weights from the backbone, neck, rpn_head as a starting point for training a new model.

Alternatively is it possible to load a pre-trained model of cascade rcnn and then reset/re-initialize the weights in a single section?

**Comment by hhaAndroid** [comment]
@waddington 

1. Currently does not support loading multiple weights
2. If you want to load the weights of certain parts, you can directly use the` load_from` parameter. Unmatched keys will be automatically excluded
3. Load a pre-trained model of cascade rcnn can be realized by using `load_from` parameter
