### ISSUE TITLE
demo报错

### ISSUE THREAD

**Issue by bingo789** [open-mmlab/mmdetection#6057]
### 运行命令

`python demo/image_demo.py demo/demo.jpg  configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py  checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --device=cpu`

### 报错
```
Traceback (most recent call last):
  File "demo/image_demo.py", line 50, in <module>
    main(args)
  File "demo/image_demo.py", line 32, in main
    show_result_pyplot(model, args.img, result, score_thr=args.score_thr)
  File "/Users/bingo/opt/anaconda3/envs/ai/lib/python3.7/site-packages/mmdet/apis/inference.py", line 241, in show_result_pyplot
    text_color=(72, 101, 241))
  File "/Users/bingo/opt/anaconda3/envs/ai/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 343, in show_result
    out_file=out_file)
  File "/Users/bingo/opt/anaconda3/envs/ai/lib/python3.7/site-packages/mmdet/core/visualization/image.py", line 172, in imshow_det_bboxes
    img_rgba = buffer.reshape(height, width, 4)
ValueError: cannot reshape array of size 1090560 into shape (427,640,4)
```
### 版本信息
`mmdet: 2.16.0`

**Comment by AronLin** [comment]
We will check it.

**Comment by BIGWangYuDong** [comment]
![Uploading WXWorkCapture_16315219198763.png…]()

Seems do not get this bug in  `mmdet 2.16.0`
Did you change any code in mmdetection? @bingo789

**Comment by BIGWangYuDong** [comment]
You can update the mmdet to the latest version, and try it again.
Also, you can try to re-install the environment.
If you still meet this bug, please leave a message to us.

**Comment by YuYue26** [comment]
/home/yuyue/下载/mmdetection-master/mmdet/core/anchor/builder.py:17: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Use load_from_local loader
/home/yuyue/下载/mmdetection-master/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
/home/yuyue/下载/mmdetection-master/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/home/yuyue/下载/mmdetection-master/mmdet/core/anchor/anchor_generator.py:361: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '

mmcv-full 1.3.13
mmdet 2.16.0
torch 1.8
cuda 10.2

What is the cause of this problem？？
