### ISSUE TITLE
visualization result shows person at the top of each image 

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#6059]
I am testing some images based on my own trained model. Executing: python tools/test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py .work_dir/latest.pth --show promising result but at the top of  each images there is confidence score of "0.31 person" as shown in the figure:
![image](https://user-images.githubusercontent.com/9031472/132412993-b05499dd-6622-4bad-ab69-0bfbc145888f.png)
![image](https://user-images.githubusercontent.com/9031472/132413046-788956d6-f47b-41e8-80c2-264d41d813b9.png)

![image](https://user-images.githubusercontent.com/9031472/132412735-2cd63f83-6376-44c4-a605-2ed47325aaa8.png)
It is same for all the test images. I am not sure what I did wrong. Any help is really appreciated.

**Comment by Soodep** [comment]
The official model is trained on 20 classes so when I use it to 2 test for only 2 classes I get:  https://github.com/open-mmlab/mmdetection/issues/5956#issue-980683055: this visualization error even after making all the required changes. Your help is appreciated a lot.

**Comment by AronLin** [comment]
Can you tell us which code you changed, it is difficult for us to reproduce this error.

**Comment by Soodep** [comment]
> Can you tell us which code you changed, it is difficult for us to reproduce this error.

I first used the official model to evaluate mAP result for only 2 classes ( VOC format ). For this, I made the following changes:
First: mmdetection/mmdet/core/evaluation/class_names.py
![image](https://user-images.githubusercontent.com/9031472/133114470-76cb6fee-48a8-42d9-bdc0-1cf0e5226f24.png)

Second: mmdetection/mmdet/datasets/voc.py
![image](https://user-images.githubusercontent.com/9031472/133114677-ee384e28-d31b-4c9d-ab55-85d492716f75.png)

Third: mmdetection/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py
![image](https://user-images.githubusercontent.com/9031472/133114929-d01185ca-3866-438c-8d0e-fa3c0fe9e708.png)

After making these changes I try to test some images from KITTI dataset using: python tools/test.py \
    configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc.py \
    checkpoints/faster_rcnn_r50_fpn_1x_voc0712_20200624-c9895d40.pth \
    --show
I get this visualization result: 
![image](https://user-images.githubusercontent.com/9031472/133115544-efa4dbac-f417-4dc8-baf8-750d233d99d7.png)

This might be due to the official model that I used ( trained on 20 classes ) but I am only using 2 classes while testing and the first two classes are aeroplane and bicycle ( alphabetical order) in VOC dataset classes. So, I thought maybe I could use the same configuration as described above to train. I trained using KITTI dataset and above configuration ( made all the changes similar to described above in First, Second and Third ) and when I test some images I get this error: person with confidence score of 0.31 in each images. 
I have been trying to solve this for a while now. I would really appreciate your help.

**Comment by Soodep** [comment]
Can anyone help me please?

**Comment by AronLin** [comment]
1. Suggest to set the CLASSES like [faster_rcnn_r50_fpn_1x_voc0712_cocofmt.py](https://github.com/openmmlab/mmdetection/blob/master/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712_cocofmt.py).
You only need to set it in your config file.
2. Can you output the `model.CLASSES` before [mmdet/tools/test.py/#L203](https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L203) and check whether it is right?

**Comment by Soodep** [comment]
@AronLin Like you suggested I set the classes in  my config file only( i didn't change any other files):
![image](https://user-images.githubusercontent.com/9031472/133445906-76010432-95b1-491a-98fa-02c1db7d54d1.png)

And when I output the model.Classes before mmdet/tools/test.py/#L203 I still get all the classes (20 classes ):
![image](https://user-images.githubusercontent.com/9031472/133446228-7b099204-bd19-42f0-aa64-47073a0454f1.png)

And as for the output I am still getting the same result as above:
![image](https://user-images.githubusercontent.com/9031472/133446386-41353fa4-fb29-4e76-8038-aff89a9305af.png)
I really appreciate your help. At this point I am using the official model and just want to output the mAP for only 2 classes ( car, person) but I am still not able to do that.

**Comment by Soodep** [comment]
I also tried changing the number of classes ( num_classes = 2 ), but when I do the same unexpected visualization result I have explained before ( large no. of aeroplane and bicycle bounding boxes). I am really lost and not sure how I can solve this simple problem.

**Comment by AronLin** [comment]
> when I output the model.Classes before mmdet/tools/test.py/#L203 I still get all the classes (20 classes

That is the problem. If model.CLASSES is correct, the visualization result should also be correct.

1. In the config file, you have not passed the CLASSES to the data.train/val/test.classes. In tools/test.py, we passed the dataset.CLASSES to model.CLASSES. So the number of model.CLASSES should be 2.
2. If the number of model.CLASSES is correct, you can get the right class number in evalution.

**Comment by Soodep** [comment]
How to pass Classes to the data.train/val/test.classes from config file?

**Comment by AronLin** [comment]
![image](https://user-images.githubusercontent.com/29054582/133722182-eb903003-b827-40c3-94f9-f7340a8c876b.png)

**Comment by deepsea12** [comment]
I actually already did that. And even after doing that model.classes outputs all 20 classes.

**Comment by AronLin** [comment]
https://github.com/open-mmlab/mmdetection/blob/fa10539397af557853cc5f72f4cd1aba8a174d44/tools/test.py#L199

Here we set the model.CLASSES, you can go to check what happened.

**Comment by Soodep** [comment]
@AronLin Like you suggested I made changes to my dataset setting in voc0712.py as follows:
![image](https://user-images.githubusercontent.com/9031472/133872073-7d3d4069-f516-485c-be72-ee625457683f.png)
![image](https://user-images.githubusercontent.com/9031472/133872079-e713a930-edde-4db8-9411-e456262cd5cf.png)

And in test.py, I checked the output of model.CLASSES:
![image](https://user-images.githubusercontent.com/9031472/133872116-5d61e5c1-c27e-4b06-90a2-ab397530398c.png)
This is the output of model.CLASSES:
![image](https://user-images.githubusercontent.com/9031472/133872531-29ca7166-c65a-4023-b5c7-605bcd19e124.png)

and at the end of test I get this error:
![image](https://user-images.githubusercontent.com/9031472/133872497-51c03747-b64b-4ecf-bdaf-1b3c3a3ea84f.png)
Am I missing something?

**Comment by deepsea12** [comment]
@Soodep did you solve this?

**Comment by AronLin** [comment]
It is strange. You set the dataset.CLASSES but it is still 20 classes.
I guess the checkpoint you loaded has `CLASSES` in `meta`, and it is 20 classes.

**Comment by hongyanghu** [comment]
![image](https://user-images.githubusercontent.com/29887717/134467631-5652f54d-369c-4c86-b3be-8fba1e28f25e.png)
The problem may be solved by this way，if your dateset is ```voc``` 。Comment the following statement，makes ```ds_name = self.CLASSES``` ,and ```self.CLASSES`` is what you need

**Comment by deepsea12** [comment]
> ![image](https://user-images.githubusercontent.com/29887717/134467631-5652f54d-369c-4c86-b3be-8fba1e28f25e.png)
> The problem may be solved by this way，if your dateset is `voc` 。Comment the following statement，makes `ds_name = self.CLASSES` ,and ```self.CLASSES`` is what you need

Do I have to change the number of classes in config file and pass Classes to the data.train/val/test.classes from config file? Because even after doing that I am not getting good result. 
Dear @hhaAndroid could you please be more specific about the changes I need to make to evaluate the result for only 2 classes using the official model ( which is based on 20 classes )? I appreciate your help.

**Comment by Soodep** [comment]
did you solve it?
