### ISSUE TITLE
: cannot connect to X server

### ISSUE THREAD

**Issue by fengzifrank** [open-mmlab/mmdetection#606]
当我运行demo时，发生了这个报错   模型我都有离线下载完毕   对这个报错  不明白是哪里出问题了

**Comment by zz10001** [comment]
你解决了吗

**Comment by XiaoSX** [comment]
我是运行test.py的时候遇到，去掉--show就好了，运行demo的时候可以指定out_file,把标记过的图片保存下在打开

**Comment by beier9739** [comment]
您好，请问在test.py的时候是怎么把标记的图片保存到文件夹的呢？指定out_file保存的不是pkl文件么？

**Comment by markliu2013** [comment]
show_result(img, result, model.CLASSES, show=False, out_file='result.jpg')
加上show=False
out_file='result.jpg' 你保存的地方。
