### ISSUE TITLE
ATSSAssigner: 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by victoryc** [open-mmlab/mmdetection#6060]
When I use the ATSSAssigner in the config file, I am getting the error: 'NoneType' object has no attribute 'size'
The error occurs on the following line of atss_assigner.py:
`    num_gt, num_bboxes = gt_bboxes.size(0), bboxes.size(0)`
gt_bboxes happens to be None causing the error.

But, when I replace the ATSSAssigner by MaxIOUAssigner, the config file works fine.
Any idea why the error occurs when ATSSAssigner is used?
Thanks.

**Comment by RangiLyu** [comment]
The input of ATSSAssigner is different from MaxIOUAssigner. It requires `num_level_bboxes`. You need to change the code.

**Comment by victoryc** [comment]
@RangiLyu Would you mind providing a sketch of the code changes that need to be made? Thanks!

**Comment by qsc-1999** [comment]
I have the same problem. But I try to solve it and failed...

**Comment by RangiLyu** [comment]
Currently, if you want to change the target assign method, the best way is to inherit the original head and overwrite the `get_targets` function.
