### ISSUE TITLE
How to add  Attention Blocks   for my network ？for example Senet or CBAM.

### ISSUE THREAD

**Issue by myGithubSiki** [open-mmlab/mmdetection#6062]
now, i want  to add Attention Blocks   for my network
but i can't get usefull information from  Internet.
Can you give me some advise? 
It maybe help me 
I hope your reply. Thanks!

**Comment by PeterVennerstrom** [comment]
Here is MMDetection's [SE layer](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/utils/se_layer.py).

Other attention layers could be added in a similar way and then used in the backbone, neck and head as appropriate.  

Alternatively, to use a pretrained backbone with attention blocks which doesn't exist in MMDetection, a new backbone could be added.

**Comment by myGithubSiki** [comment]
Ok, thanks 
I will try .
Tanks for your reply and help  again
