### ISSUE TITLE
wrong classes custom coco dataset

### ISSUE THREAD

**Issue by firsakov** [open-mmlab/mmdetection#6063]
I've trained yolov3 on custom coco dataset.
when i run test.py and then analyze_results.py, it tries to detect native coco classes like truck, person, train etc.
i put my classes to coco.py and also added classes to my config file.
Most amazing for me thing is when i run analyze_results from jupyter notebook it loads dataset and classes correctly, but when i run from terminal in loads native classes.
Anyone has ideas what the problem can be?

**Comment by firsakov** [comment]
@AronLin i double checked everything..

**Comment by AronLin** [comment]
Can you give more information, such as which files you have modified, screenshots of all running commands and results, etc., to help us locate the problem.
