### ISSUE TITLE
关于mmdetection的模型部署

### ISSUE THREAD

**Issue by piaomiao920** [open-mmlab/mmdetection#6064]
您好，经使用mmdetection，各种各样的模型体验感很好，但很遗憾没办法部署下来，只能暂时放弃使用了。。。如果能像YOLOv5那样的一个Python文件部署成torchscript、onnx之类就好了（mmd的onnx用不了GPU）。
mm系列给我一种只比较不重视模型部署的问题，如果部署也完善的话，你们的框架直接无敌了，可惜了。
求转成torchscript教程，只有几个基础的网络也好啊，至少能模仿着自己部署。

**Comment by kingbirdWc** [comment]
我是个游客。部署的话paddle-detection、paddle-lite做的不错，用户支持也比较快。mmdetection没看到有部署的东西，如果能完善一下就更好了。

**Comment by wojiazaiyugang** [comment]
同求教程。
感觉差不多，就是各种模型各种配置用起来很爽很方便，但是一到部署的时候就有很多问题，又爱又恨。
