### ISSUE TITLE
请问如何才能保存bbox信息到json,xml或者txt文件

### ISSUE THREAD

**Issue by 7xjerry1** [open-mmlab/mmdetection#6066]
我需要把检测出的bbox文件生成一个voc格式的文件，如何才能获取到bbox的信息呢，谢谢大家

**Comment by BIGWangYuDong** [comment]
Hi, you can save your result by using XXXXXX --out result.pkl and then write a script to write it to .XML file. 

In my impression, the result.pkl is saved as 
```python
list[
    image_1[
        class_1[
            ... , [xmin, ymin, xmax, ymax] ,...,],
        class_2[
            ... , [xmin, ymin, xmax, ymax] , ...],
         ...],
    image_2[...],
    ....
]
```
