### ISSUE TITLE
在win10系统map值一直都是零点零零几，在ubuntu却可以达到0.9以上

### ISSUE THREAD

**Issue by sweetboxwwy** [open-mmlab/mmdetection#6071]
2021-09-10 09:04:04,415 - mmdet - INFO - Exp name: cascade_rcnn_r50_fpn_1x_coco.py
2021-09-10 09:04:04,415 - mmdet - INFO - Epoch(val) [12][100]	bbox_mAP: 0.0030, bbox_mAP_50: 0.0120, bbox_mAP_75: 0.0000, bbox_mAP_s: -1.0000, bbox_mAP_m: 0.0010, bbox_mAP_l: 0.0030, bbox_mAP_copypaste: 0.003 0.012 0.000 -1.000 0.001 0.003
DONE (t=0.09s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.003
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.012
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.003
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.011
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.011
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.011
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.011

Process finished with exit code 0

**Comment by jshilong** [comment]
The support for windows is temporally experimental

**Comment by ZwwWayne** [comment]
For now, we do not have enough information to help with debugging. So this PR is closed.
