### ISSUE TITLE
数据集的配置文件和模型的配置文件混合在一起，如果解耦配置就更好了

### ISSUE THREAD

**Issue by kingbirdWc** [open-mmlab/mmdetection#6073]
数据集的配置文件和模型的配置文件混合在一起，如果解耦配置就更好了。现在改一改配置文件改数据集路径需要改动挺多地方，很容易出问题，需要反复改才能成功运行。这一点看起来不如paddledetection的配置方便，例如https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/datasets/coco_detection.yml 。一点个人建议。

**Comment by jshilong** [comment]
Thanks for your suggestion and we will seriously consider it.
