### ISSUE TITLE
question about gen_base_anchors in SSDAnchorGenerator 

### ISSUE THREAD

**Issue by Paseam** [open-mmlab/mmdetection#6074]
![image](https://user-images.githubusercontent.com/8642716/132808536-22f52ce9-6ec8-41ae-89f8-ec2978e204d2.png)
i don't understand this code,why does i need to index_select these indexes?

**Comment by jshilong** [comment]
Please take a look at this issue, you add it in PR #2474 @ZwwWayne

**Comment by jshilong** [comment]
These indexes may follow the original implementation of SSD which has no confluence to the performance

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
