### ISSUE TITLE
训练时长

### ISSUE THREAD

**Issue by qq1628qq** [open-mmlab/mmdetection#6075]
为什么YOLOX的训练时长比原版代码慢很多

**Comment by CarryHJR** [comment]
mosaic太耗时了，最后的15e 关闭mosaic速度 一个iteration 0.3s 不关闭 就是0.55s，官方yolox的解决方法是cache全部训练集

**Comment by hhaAndroid** [comment]
> mosaic太耗时了，最后的15e 关闭mosaic速度 一个iteration 0.3s 不关闭 就是0.55s，官方yolox的解决方法是cache全部训练集

great
