### ISSUE TITLE
How can I get the Faster R-CNN region feature and region position?

### ISSUE THREAD

**Issue by greeksharifa** [open-mmlab/mmdetection#6077]
I want to get the region feature(maybe 2048 dim per region proposal or object) and region position(6 dim per region proposal), so that I use these features in Oscar captioning model.

However, the output of the faster rcnn model is fixed to only results(maybe,  I guess bbox and confidence score--the shape of [1, num_classes=80, num_object per class, 5]), and I cannot edit the model output because that is in mmcv.utils library.

How  can I get the region features&positions in faster-rcnn?

Thanks.

**Comment by jshilong** [comment]
You can modify the https://github.com/open-mmlab/mmdetection/blob/b1f97c1b6d2b3c735d8c5690952264c598c2f206/mmdet/models/roi_heads/test_mixins.py#L89
to add `feature` to the returns

**Comment by greeksharifa** [comment]
> You can modify the
> 
> https://github.com/open-mmlab/mmdetection/blob/b1f97c1b6d2b3c735d8c5690952264c598c2f206/mmdet/models/roi_heads/test_mixins.py#L89
> 
> 
> to add `feature` to the returns

Thanks, but, the shape of bbox_results is [1000, 5], and I want to the features for not all of the regions, but region features for only *actual* objects, (so, I expect the shape of region features will be [num_of_objects, 2048]

And, the bbox_feats is [1000, 256, 7, 7] is not I want . how can I get the 2048-dim features? bbox_results contains the cls_score[1000, 81], bbox_pred[1000, 320], bbox_feats[100, 256, 7, 7].

**Comment by greeksharifa** [comment]
hmm, I can get the answer at btup paper. thanks.

**Comment by Dorothylyly** [comment]
Hi, I wonder what's the answer. Thanks for sharing :)

**Comment by freedom6927** [comment]
> btup paper

Hi, how do you get the features (2048) of valid region proposal. If I want to get the feature of assigned bounding box. How to modify the code? thanks
