### ISSUE TITLE
train_detector Assertion Error

### ISSUE THREAD

**Issue by Oz-art** [open-mmlab/mmdetection#6080]
I got this error when trying to use the train_detector. Is anyone also got this following error?
thank you in advance.

AssertionError                            Traceback (most recent call last)
<ipython-input-12-7889370c464f> in <module>()
     18 # Create work_dir
     19 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 20 train_detector(model, datasets, cfg, distributed=False, validate=True)

/content/mmdetection/mmdet/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
     99     else:
    100         if 'total_epochs' in cfg:
--> 101             assert cfg.total_epochs == cfg.runner.max_epochs
    102 
    103     runner = build_runner(

AssertionError:

**Comment by shinya7y** [comment]
`total_epochs` is deprecated.
Please set `runner = dict(type='EpochBasedRunner', max_epochs=12)` instead of `total_epochs = 12`

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by Oz-art** [comment]
Sorry for the late replay. I've been out for several days. The solution is working. Thank you very much for your response.
