### ISSUE TITLE
请问应在何处自定义wandb的log

### ISSUE THREAD

**Issue by Stephenzza** [open-mmlab/mmdetection#6084]
我想在训练阶段记录验证的图片和预测结果到wandb，请问我应该在哪里下手？

**Comment by RangiLyu** [comment]
https://zhuanlan.zhihu.com/p/387078211
And you can add the eval results to wandb in mmdet/core/evaluation/eval_hooks.py

**Comment by Stephenzza** [comment]
Thank u!
