### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple when doing multi-scale test on test-dev

### ISSUE THREAD

**Issue by iFighting** [open-mmlab/mmdetection#6085]
``![image](https://user-images.githubusercontent.com/6366788/132973437-ec24cb1b-fb32-4a47-a7de-21a2139879e3.png)

When doing multi-scale test on test-dev,  i meet this error,  it only occurs on test-dev, when it comes to val, the results is ok

The config is as follows:

data = dict(samples_per_gpu=samples_per_gpu,
            train=dict(
                seg_prefix=data_root + 'stuffthingmaps/train2017/',
                pipeline=train_pipeline),
            val=dict(
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        ann_file=data_root + 'annotations/image_info_test-dev2017.json',
        img_prefix=data_root + 'test2017/',
        pipeline=test_pipeline))

**Comment by shinya7y** [comment]
If your detector is HTC Swin, please try the fix of the PR.
The bug can be reproduced also on val by setting `--cfg-options "model.test_cfg.rcnn.score_thr=1.0"` for `test.py`.

**Comment by iFighting** [comment]
> If your detector is HTC Swin, please try the fix of the PR.
> The bug can be reproduced also on val by setting `--cfg-options "model.test_cfg.rcnn.score_thr=1.0"` for `test.py`.

thanks, it works

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
