### ISSUE TITLE
arguments mismatch

### ISSUE THREAD

**Issue by SkyErnest** [open-mmlab/mmdetection#6087]
I found in `mmdet/models/roi_heads/test_mixins.py` the method `BBoxTestMixin.simple_test_bboxes` made a call `bbox_results = self._bbox_forward(x, rois)` (line 89). 
However the definition of the child class method `CascadeRoIHead._bbox_forward` is `def _bbox_forward(self, stage, x, rois)`

**Comment by jshilong** [comment]
Thanks for your bug reporting. Would you mind create a PR to fix it?
