### ISSUE TITLE
question about val workflow

### ISSUE THREAD

**Issue by tomatowithpotato** [open-mmlab/mmdetection#6090]
in train.py
```python
if len(cfg.workflow) == 2:
        val_dataset = copy.deepcopy(cfg.data.val)
        val_dataset.pipeline = cfg.data.train.pipeline
        datasets.append(build_dataset(val_dataset))
```
why 
```python
val_dataset.pipeline = cfg.data.train.pipeline
```
?????????????????????

it will cause error when I use mosaic

**Comment by jshilong** [comment]
Please take a look at this issue about mosaic augmentation @RangiLyu @hhaAndroid

**Comment by hhaAndroid** [comment]
@tomatowithpotato Why do you need to turn on val workflow?

**Comment by tomatowithpotato** [comment]
> @tomatowithpotato Why do you need to turn on val workflow?

I want to see the validation loss

**Comment by hhaAndroid** [comment]
```shell
val_dataset.pipeline = cfg.data.train.pipeline
```
This is because the val workflow does not load the annotations, so the train pipeline can only be used.

**Comment by tomatowithpotato** [comment]
> ```shell
> val_dataset.pipeline = cfg.data.train.pipeline
> ```
> 
> This is because the val workflow does not load the annotations, so the train pipeline can only be used.

The official seems to strongly discourage the use of val workflow
But I think that since the design has its meaning, I hope to improve it in the future

Thank you very much for your reply！！！！！！
