### ISSUE TITLE
How to train RetineNet from scratch?

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmdetection#6092]
Hi,
I want to train retinanet without any pretrained backbone, what should I do?
I think let `pretrained=None` is not a correct solution.

**Comment by hhaAndroid** [comment]
```shell
# init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'))
init_cfg=None```

**Comment by Senwang98** [comment]
@hhaAndroid 
Okay, I use mmdet version=2.3, so maybe pretrained=None is useful.
