### ISSUE TITLE
why the time varies between different epoches in YOLOX

### ISSUE THREAD

**Issue by RaymondByc** [open-mmlab/mmdetection#6093]
![Figure_1](https://user-images.githubusercontent.com/11907000/133039393-31f7c096-13ff-4136-aaa8-0c0936ec4650.png)

As the figure of time shown, the time between epochs varies a lot.

I have checked the features which just are used in YOLOX, like hooks and transforms, and no clue is found. Only "SyncRandomSizeHook" would change the size of the input, but it happens in different iterations.
 
Do you know any idea?

**Comment by hhaAndroid** [comment]
@RaymondByc Between each epoch, there will be closing dataloader multi-process and opening multi-process operation, which is very time-consuming. You can refer to the log we provide:

```shell
{"mode": "train", "epoch": 1, "iter": 1800, "lr": 0.00038, "memory": 3446, "data_time": 0.04779, "loss_cls": 2.66138, "loss_bbox": 3.53173, "loss_obj": 5.41322, "loss": 11.60633, "time": 0.53712}
{"mode": "train", "epoch": 2, "iter": 50, "lr": 0.00042, "memory": 3446, "data_time": 1.94365, "loss_cls": 2.60153, "loss_bbox": 3.59438, "loss_obj": 4.99105, "loss": 11.18696, "time": 2.48093}
{"mode": "train", "epoch": 2, "iter": 100, "lr": 0.00044, "memory": 3446, "data_time": 0.02042, "loss_cls": 2.60903, "loss_bbox": 3.56643, "loss_obj": 4.95299, "loss": 11.12845, "time": 0.55071}

```

**Comment by RaymondByc** [comment]
You misunderstand what I mean. What I concern about is the changes between epochs instead of iterations.  

[https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_tiny_8x8_300e_coco/yolox_tiny_8x8_300e_coco_20210806_234250.log.json](The log you post) do not have the changes because the tiny config does not have "Mixup".

You can check the changes between epochs in yolox_s_8x8_300e_coco.py.

**Comment by RaymondByc** [comment]
The bug I found is that "update_dynamic_scale" in MultiImageMixDataset Class cannot really change the self._dynamic_scale. 

You can found that when you print the self._dynamic_scale in __get_item__.

**Comment by RaymondByc** [comment]
Change the dataset in dataloader can be done by "runner.data_loader.dataset.update_dynamic_scale()"? I think it would not works.

**Comment by hhaAndroid** [comment]
> Change the dataset in dataloader can be done by "runner.data_loader.dataset.update_dynamic_scale()"? I think it would not works.

This is indeed a bug, you can refer to https://github.com/open-mmlab/mmdetection/pull/6144

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by xubiao-ui** [comment]
Hello, why do I use yolox model very slowly?
