### ISSUE TITLE
repeated dataset

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmdetection#6094]
Hello,
When I use the code, I noticed that there is a parameter:
type='RepeatDataset',
times=N,

What is the function of the repeated dataset? Increase the size of the dataset?

**Comment by hhaAndroid** [comment]
The main purpose of repeating the data set n times is to apply to a small data set scenario, which can reduce the frequent start and end of multiple processes of the dataloader to speed up training.

**Comment by wwjwy** [comment]
Thanks a lot
