### ISSUE TITLE
Shape of ONNX export dynamic batch

### ISSUE THREAD

**Issue by aravind-anantha** [open-mmlab/mmdetection#6096]
Thanks for your error report and we appreciate it a lot.

https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/pytorch2onnx.py#L71

This line should be 
```
    if dynamic_export:
        dynamic_axes = {
            input_name: {
                0: 'batch',
                2: 'height',
                3: 'width'
            },
            'dets': {
                0: 'batch',
                1: 'num_dets',
            },
            'labels': {
                0: 'batch',
                1: 'num_dets',
            },
        }
```

Based on the way the line below is implemented the dynamic axis should be `bs x c x h x w`. 
https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/pytorch2onnx.py#L139

I can create a quick PR for this if needed.

**Comment by hhaAndroid** [comment]
@aravind-anantha Thanks for creating a PR to fix it.
