### ISSUE TITLE
Test none output?

### ISSUE THREAD

**Issue by HuangQinJian** [open-mmlab/mmdetection#611]
![image](https://user-images.githubusercontent.com/20330704/57350717-bdcc7300-7191-11e9-9081-5b854905b082.png)

**Comment by Peterisfar** [comment]
you should add arg  --out ***.pkl

**Comment by HuangQinJian** [comment]
> you should add arg --out ***.pkl

Is there has the  mAP  ?

**Comment by Peterisfar** [comment]
if the dataset type is coco, when you add --out ,it will calculate mAP by coco eval APIs, you can just try

**Comment by HuangQinJian** [comment]
> if the dataset type is coco, when you add --out ,it will calculate mAP by coco eval APIs, you can just try

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3038/3038, 1.4 task/s, elapsed: 2250s, ETA:     0s(mm) hqj@ubuntu-PR4908P:~/ccf-traffic-sign-identification/mmdetectionpn_1x.py' 'work_dirs/faster_rcnn_dconv_c3-c5_x101_32x4d_fpn_1x/epoch_6.pth' --out 'eval.pkl' --eval 'bbox'5_x101_32x4d_fp
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3038/3038, 1.3 task/s, elapsed: 2284s, ETA:     0swriting results to eval.pkl
Starting evaluate bbox
Loading and preparing results...
Traceback (most recent call last):
  File "tools/test.py", line 127, in <module>
    main()
  File "tools/test.py", line 116, in main
    coco_eval(result_file, eval_types, dataset.coco)
  File "/home/ubuntu/ccf-traffic-sign-identification/mmdetection-v2/mmdet/core/evaluation/coco_utils.py", line 26, in coco_eval
    coco_dets = coco.loadRes(result_file)
  File "/opt/anaconda3/envs/mm/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 318, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by HuangQinJian** [comment]
> if the dataset type is coco, when you add --out ,it will calculate mAP by coco eval APIs, you can just try

Also,when I test the image like this :
```
import os

import pandas as pd
import numpy as np

import mmcv
from mmcv.runner import load_checkpoint
from mmdet.apis import inference_detector
from mmdet.models import build_detector
from tqdm import tqdm

cfg = mmcv.Config.fromfile(
    'configs/dcn/faster_rcnn_dconv_c3-c5_x101_32x4d_fpn_1x.py')
cfg.model.pretrained = None

# construct the model and load checkpoint
model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
_ = load_checkpoint(
    model, 'work_dirs/faster_rcnn_dconv_c3-c5_x101_32x4d_fpn_1x/epoch_6.pth')

imgs_dir = '/data1/hqj/traffic-sign-identification/test'
img_names = os.listdir(imgs_dir)

submit_v4 = pd.DataFrame()
empty_v4 = pd.DataFrame()

filenameList = []

X1List = []
X2List = []
X3List = []
X4List = []

Y1List = []
Y2List = []
Y3List = []
Y4List = []

TypeList = []

empty_img_name = []

# for img_name in img_names:
for i, img_name in enumerate(tqdm(img_names)):
    path = os.path.join(imgs_dir, img_name)
    # test a single image
    img = mmcv.imread(path)
    print(path)
    predictions = inference_detector(model, img, cfg)
    print(predictions)
    for j, bbox in enumerate(predictions):
        print(j, bbox)
    break
```

It just output none:
![image](https://user-images.githubusercontent.com/20330704/57353251-75fe1980-719a-11e9-8a41-5a1aa2be6450.png)

**Comment by LiDaiY** [comment]
> if the dataset type is coco, when you add --out ,it will calculate mAP by coco eval APIs, you can just try

Thank you for your answer. Do you konw if dataset type is voc, how to calculate the mAP?
