### ISSUE TITLE
Request to host the models for scnet on openmmlab.com

### ISSUE THREAD

**Issue by ganesh3** [open-mmlab/mmdetection#6110]
Hi,

We would request if all the backbones for SCNET (https://github.com/open-mmlab/mmdetection/tree/master/configs/scnet) are hosted on openmmlab.com similar to VFNET (for e.g.: https://download.openmmlab.com/mmdetection/v2.0/vfnet/vfnet_r50_fpn_1x_coco/vfnet_r50_fpn_1x_coco_20201027-38db6f58.pth). It becomes easier to download the models directly and also integrate them into any open-source software.

Request you to please confirm if this can be done. We are working on integrating different models of mmdetection into icevision and having the models hosted on openmmlab will be very helpful.

Regards
Ganesh

**Comment by hhaAndroid** [comment]
@ganesh3 It has been modified.

**Comment by ganesh3** [comment]
Thanks.
