### ISSUE TITLE
How to use albumentations during test pipeline?

### ISSUE THREAD

**Issue by waddington** [open-mmlab/mmdetection#6111]
This response mentions that it is not possible - https://github.com/open-mmlab/mmdetection/issues/3962#issuecomment-750026724

However I would very much like to be able to do this. Can someone point me to what I need to change to enable it to run?

**Comment by hhaAndroid** [comment]
@waddington Why is there such a demand?

**Comment by waddington** [comment]
So that I can more easily analyse the effect of different input image manipulations on trained models.

**Comment by julled** [comment]
I am would be also very interested in having albumentations run in test pipeline!
Is there a reason why this cant work?

**Comment by waddington** [comment]
@RangiLyu why did you close this?
