### ISSUE TITLE
about dataset val

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#6113]
I want to use the evaluation standard of the coco data set: bbox indicator to evaluate the training results of the voc data set, how can I modify the code to complete

**Comment by RangiLyu** [comment]
There are two different ways:
1. Convert the voc format dataset to coco format and run training and validation with CocoDataset.
2. Copy the evaluate function in CocoDataset (mmdet/datasets/coco.py), and replace the evaluate function in voc dataset (mmdet/datasets/voc.py) with it.
