### ISSUE TITLE
One concern about init_cfg.

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#6114]
https://github.com/open-mmlab/mmdetection/blob/fe396572839f30351aa862d2b2702f57698cefea/mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py#L99

According this this line, if init_cfg was provided by user, all the current default init_cfgs and parents' default init_cfgs would be lost. In order to use the default init_cfgs user has to list them all in the provided init_cfg. I think it might be easier for users to only provide the initialization they want to add/change.

**Comment by RangiLyu** [comment]
Thanks for your feedback! If you have a better idea of weight initialization, welcome to create a pull request.
