### ISSUE TITLE
验证安装的时候报错，Userwarning

### ISSUE THREAD

**Issue by YuYue26** [open-mmlab/mmdetection#6120]
/home/yuyue/下载/mmdetection-master/mmdet/core/anchor/builder.py:17: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Use load_from_local loader
/home/yuyue/下载/mmdetection-master/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
/home/yuyue/下载/mmdetection-master/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/home/yuyue/下载/mmdetection-master/mmdet/core/anchor/anchor_generator.py:361: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '

mmcv-full         1.3.13
mmdet             2.16.0 
torch                1.8
cuda                 10.2

what cause this, please help me!

**Comment by BIGWangYuDong** [comment]
This is only a warning, there is no error report.
