### ISSUE TITLE
Error when convert model to torchserve format

### ISSUE THREAD

**Issue by huyhoang17** [open-mmlab/mmdetection#6124]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I want to convert a model to torchserve's mar format. I run the mmdet2torchserve.py script in tool/deployment folder but got the following error. How can I fix this issue or can you provide more information related to it? Thanks in advance!

![mmdet_torchserve_error](https://user-images.githubusercontent.com/15128654/133772402-f417182c-2c4d-4b25-84ad-22e8c4856178.png)

Lib version
```bash
model-archiver==1.0.3
multi-model-server==1.1.4
torch-model-archiver==0.1.1
```

**Comment by BIGWangYuDong** [comment]
It looks like you are missing some installation packages, you can try to use `pip install -v -e .[all] ` to install fully mmdet 
https://github.com/open-mmlab/mmdetection/blob/master/docs/useful_tools.md#1-convert-model-from-mmdetection-to-torchserve

**Comment by huyhoang17** [comment]
Closed. I got a conflict between torch-model-archiver and model-archiver package. Uninstall model-archiver and it works well
Thanks for your support!
