### ISSUE TITLE
How  set `_delete_=True` to ignore the base config 

### ISSUE THREAD

**Issue by azade-a** [open-mmlab/mmdetection#6128]
Hello everyone.
I used [Solo ](https://github.com/WXinlong/mmdetection/tree/SOLO)branch and ran test.py on my custom dataset and got this error:

/mmdetection-SOLO/mmdetection-SOLO$ python "/home/mmdetection-SOLO/mmdetection-SOLO/tools/test.py"  "/home/mmdetection-SOLO/mmdetection-SOLO/configs/solo/solo_r50_fpn_1x_card.py" "/home/mmdetection-SOLO/mmdetection-SOLO/checkpoints/epoch_12.pth" --show-dir="/home/mmdetection-SOLO/mmdetection-SOLO/show_dir/"
Traceback (most recent call last):
  File "/home/mmdetection-SOLO/mmdetection-SOLO/tools/test.py", line 153, in <module>
    main()
  File "/home/mmdetection-SOLO/mmdetection-SOLO/tools/test.py", line 85, in main
    cfg = Config.fromfile(args.config)
  File "/.myenvs/solo2/lib/python3.7/site-packages/mmcv/utils/config.py", line 212, in fromfile
    use_predefined_variables)
  File "/.myenvs/solo2/lib/python3.7/site-packages/mmcv/utils/config.py", line 181, in _file2dict
    base_cfg_dict = Config._merge_a_into_b(cfg_dict, base_cfg_dict)
  File "/.myenvs/solo2/lib/python3.7/site-packages/mmcv/utils/config.py", line 204, in _merge_a_into_b
    b[k] = Config._merge_a_into_b(v, b[k])
  File "/.myenvs/solo2/lib/python3.7/site-packages/mmcv/utils/config.py", line 200, in _merge_a_into_b
    f'{k}={v} in child config cannot inherit from base '
TypeError: grad_clip={'max_norm': 35, 'norm_type': 2} in child config cannot inherit from base because grad_clip is a dict in the child config but is of type <class 'NoneType'> in base config. You may set `_delete_=True` to ignore the base config

Please help me.
Many thanks in advance.

**Comment by azade-a** [comment]
Hi again .
that's the solution [Link](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_runtime.md#additional-settings)

**Comment by ZwwWayne** [comment]
> Hi again .
> that's the solution [Link](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_runtime.md#additional-settings)

Yes, this is the correct solution.

**Comment by hmtrii** [comment]
The link is died now. Could anyone update it?

**Comment by Ravikshdikola** [comment]
page not found please send the link i am facing the same issue

**Comment by mertkoc** [comment]
Hi, @vincentblot28, just clicked the link you provided and the one above, all of them returns 404 :/
