### ISSUE TITLE
Include model details in the model zoo page

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6134]
**Describe the feature**
For each model included in the [model zoo](https://mmdetection.readthedocs.io/en/latest/model_zoo.html), include the model details (learning schedule, train time, inference time, box AP,  mask AP (for segmentation tasks), etc.) in the model zoo page, rather than in linked pages.
**Motivation**
One of the main reasons for having a model zoo page is to be able to quickly compare different models in terms of performance, such as train time, inference time, box AP, etc. This is easy to do with, e.g., the [Detectron 2 model zoo](https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md) since the model zoo page collects these quantities for each model in a series of tables. Instead, [MMDetection model zoo](https://mmdetection.readthedocs.io/en/latest/model_zoo.html)  is really inconvenient in this respect, because you have to navigate to each model's page in order to see these details, and thus model comparison becomes needlessly complicated.

**Related resources**
None.

**Additional context**
None.

**Comment by ZwwWayne** [comment]
Thanks for your kind suggestion. Actually, we are working on providing a way to compare different models but it might take some time. For now, this page may help you https://paperswithcode.com/lib/mmdetection

**Comment by AndreaPi** [comment]
@ZwwWayne good to know! I'd be glad to help, but I only have experience to write `md` files. If you just need to create Markdown tables, similar to what the Detectron2 folks did, I can contribute, but if you plan to do something more advanced (e.g., a webpage which updates automatically when new models are added to MMDetection), I cannot help much.

**Comment by AndreaPi** [comment]
@ZwwWayne @jshilong hi! So, would you find useful if I created a PR with a `MODEL_ZOO.md`, similar to what is done in Detectron2?

**Comment by AndreaPi** [comment]
Perfect 😁  just forked the current master, will let you know once I'm done!

**Comment by AndreaPi** [comment]
Hi all, I have a small problem: I checked the [`CONTRIBUTING` guidelines](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) and I'm not really onboard with installing stuff outside of Python (such as e.g. Ruby), since that would most likely require using `brew` and for a variety of reasons I don't use it. Also, I'm not too familiar with pre-commit hooks...in the end, I'm only contributing a plain `.md` file. Would it be ok if I just submitted the PR, and then if you find that formatting is not kosher, I modify it accordingly? I do have a markdown linter in VS Code, but I'm not sure is the same as yours.

**Comment by jshilong** [comment]
> Hi all, I have a small problem: I checked the [`CONTRIBUTING` guidelines](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) and I'm not really onboard with installing stuff outside of Python (such as e.g. Ruby), since that would most likely require using `brew` and for a variety of reasons I don't use it. Also, I'm not too familiar with pre-commit hooks...in the end, I'm only contributing a plain `.md` file. Would it be ok if I just submitted the PR, and then if you find that formatting is not kosher, I modify it accordingly? I do have a markdown linter in VS Code, but I'm not sure is the same as yours.

Thanks for your contribution. We can help you to format the markdown after you create the PR
