### ISSUE TITLE
Data-Aug

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [open-mmlab/mmdetection#6137]
Dear all,

I would like to know which data-aug is used and how to change it!

Thank you

Cheers,

Francesco

**Comment by jshilong** [comment]
You can find all data augmentation in the `train_pipline` in all configs, such as https://github.com/open-mmlab/mmdetection/blob/5ef56c174b3b93c6f320d6312ed6c1764e0e4f29/configs/_base_/datasets/coco_detection.py#L6

**Comment by FrancescoSaverioZuppichini** [comment]
Perfect, thank you :)
