### ISSUE TITLE
Overlapping bounding boxes from the same class 

### ISSUE THREAD

**Issue by dimimal** [open-mmlab/mmdetection#6139]
Hi, I have built a mask-RCNN model on my custom dataset using COCO and when I do inference using the `model.show_result()` function, i noticed that I get an enclosed bbox inside another bbox which is of the same class. 

Do you have any ideas why this might happen? 
Is this because the NMS is not applied correctly?
Im using the predefined test_cfg in the mask-RCNN with IoU overlap of 0.7

**Comment by PeterVennerstrom** [comment]
IoU based nms will allow a box completely enclosed inside another box of the same class provided the IoU is below the threshold.  

The threshold could be lowered to filter more boxes.

An nms could be created to filter any boxes completely enclosed by other boxes.
