### ISSUE TITLE
What is the difference between conf_thr and score_thr in the yolo model parameters?

### ISSUE THREAD

**Issue by tikitong** [open-mmlab/mmdetection#6142]
In yolo model setting can you explain the exact difference between **conf_thr** and **score_thr** ? 
https://github.com/open-mmlab/mmdetection/blob/fa10539397af557853cc5f72f4cd1aba8a174d44/configs/yolo/yolov3_d53_mstrain-608_273e_coco.py#L55

```python
...
test_cfg=dict(
    nms_pre=1000, 
    min_bbox_size=0,
    score_thr=0.05,
    conf_thr=0.005,
    nms=dict(type='nms', iou_threshold=0.45),
    max_per_img=100))
...
```
In other model setting such as vfnet, only score_thr is set. 

https://github.com/open-mmlab/mmdetection/blob/fa10539397af557853cc5f72f4cd1aba8a174d44/configs/vfnet/vfnet_r50_fpn_1x_coco.py#L55

Thanks !

**Comment by PeterVennerstrom** [comment]
conf_thr is used to first filter the results by their objectness score before applying nms.  score_thr is used in the nms function to filter results by their class scores.  

From the get_bboxes() method:

'''
conf_thr = cfg.get('conf_thr', -1)
            if conf_thr > 0:
                conf_inds = objectness >= conf_thr
                bboxes = bboxes[conf_inds, :]
                scores = scores[conf_inds, :]
                objectness = objectness[conf_inds]
'''

**Comment by tikitong** [comment]
@PeterVennerstrom Thanks , I'm not sure what **their objectness** means, can you be more specific?

**Comment by PeterVennerstrom** [comment]
Anchor based methods often predict an objectness score for each anchor.  In YOLO's case, the class scores are predicted separately per grid and there are multiple anchors per grid.  

Objectness is described in the original YOLO paper as "... how confident the model is that the box contains an object and also how accurate it think the box is that it predicts".
