### ISSUE TITLE
filter_empty_gt=False

### ISSUE THREAD

**Issue by lsjAI** [open-mmlab/mmdetection#6143]
When I set filter_empty_gt=False, how are images without GT involved in the training? The coco.py. dataset 's function 
 'load_annotation' will set the image's label without GT as None, how does it compute loss and the downstream operations?

**Comment by hhaAndroid** [comment]
For detection tasks, the classification loss will be calculated, but the bbox loss will be skipped.

**Comment by liliwannian** [comment]
Has it been solved?

**Comment by lsjAI** [comment]
> Has it been solved?

May be. You can set the filter_empty_gt=False to load the image without object. For detection tasks, the classification loss will be calculated, but the bbox loss will be skipped.

**Comment by lsjAI** [comment]
> For detection tasks, the classification loss will be calculated, but the bbox loss will be skipped.
Thanks, but I didn't assign a category like '0' for the image without object in the annotation files. In the annotation file these images' annotation is empty. So how dose the classification loss compute, the code will make these images belong to '0' category?
