### ISSUE TITLE
Metrics Insights

### ISSUE THREAD

**Issue by junhuplim** [open-mmlab/mmdetection#6148]
Hi I am currently training a faster rcnn model for an obj detection task and am looking at the metrics provided in `test.py`. 

1) Are there any ways for my model to output the number of TPs, FPs, TNs and FNs instead of just the mAP@IoU values?
2) What is the difference between COCO bbox eval and PASCAL_VOC mAP eval for an object detection task
3) For an object detection task, does the metric consider any predicted bounding box predicted by the model even with a low confidence score? it seems like the `evaluate` function of the datasets do not take into account of any model confidence score

**Comment by hhaAndroid** [comment]
@junhuplim Hi

1. You need to rewrite the `dataset.evaluate` function
2. The difference between them can be found through the official website introduction of COCO and VOC
3. In fact, bbox confidence score is considered when calculating TP and FP

My answer is relatively concise, if you have any questions, you can communicate.

**Comment by junhuplim** [comment]
@hhaAndroid Hello, thanks for the response!

1. Got it, am dabbling around there now
2. Are you able to direct me with the link? Have been looking around the docs but can't find the required information
3. I see, again are you able to point me to the relevant code blocks? I am currently looking at `mean_ap.eval_map` and `mean_ap.average_precision` functions now, (I am evaluating on a Custom dataset) but am unable to see how bbox confidence score is considered there. Am I looking at the wrong place? 

Thanks again, really appreciate the help!

**Comment by junhuplim** [comment]
Okay, for (3), I think i have to look around the `mean_ap.tpfp_default` function instead - since you said it was how TP and FP is calculated. I realise that the det_bboxes has shape of (m, 5) while gt_bboxes has shape of (n, 4). Am i write to say that `det_bboxes[:, -1]` is then the bbox confidence score? If I am right, I still don't see how the confidence score is being considered

**Comment by AronLin** [comment]
`det_bboxes[:, -1]` is the scores.
The confidence score is often used to sort the `TP bboxes` to calculate P-R curve. 
When evaluating `mAP`, scores may be used to find top-k `bboxes` to calculate `mAP`. The most common is to take top-100, but there may also be a need to take top-10 or top-50.

**Comment by junhuplim** [comment]
Got it, thanks for your help!

**Comment by julianzille** [comment]
Hi @hhaAndroid. How is the bbox confidence score on coco datasets actually calculated? Can you please refer me to any code/papers? 

Thanks in advance.
