### ISSUE TITLE
mask_rcnn_x101_32x4d_fpn_gn_ws_2x.py？

### ISSUE THREAD

**Issue by HuangQinJian** [open-mmlab/mmdetection#615]
RuntimeError: invalid hash value (expected "6adc888e", got "414e04feac04cb88d56b1444e63af0a21fecf7585f407bfe72f5015505b7847c")

![image](https://user-images.githubusercontent.com/20330704/57458646-4affec80-72a4-11e9-866e-fbdd2cccfdef.png)

**Comment by hellock** [comment]
Thanks for your report and we will check it.

**Comment by hellock** [comment]
#629

**Comment by HuangQinJian** [comment]
> #629
It  still wrong!

![image](https://user-images.githubusercontent.com/20330704/57578886-b0cbbe80-74c6-11e9-86ae-c153ea11c7f7.png)

**Comment by yhcao6** [comment]
https://github.com/open-mmlab/mmcv/pull/67

**Comment by HuangQinJian** [comment]
> [open-mmlab/mmcv#67](https://github.com/open-mmlab/mmcv/pull/67)

It is still wrong!

**Comment by yhcao6** [comment]
> > [open-mmlab/mmcv#67](https://github.com/open-mmlab/mmcv/pull/67)
> 
> It is still wrong!

How do you modify your mmcv? I just successfully run it.

**Comment by HuangQinJian** [comment]
> > > [open-mmlab/mmcv#67](https://github.com/open-mmlab/mmcv/pull/67)
> > 
> > 
> > It is still wrong!
> 
> How do you modify your mmcv? I just successfully run it.

I use `faster_rcnn_r50_fpn_gn_ws_1x.py` now

**Comment by yhcao6** [comment]
> > > > [open-mmlab/mmcv#67](https://github.com/open-mmlab/mmcv/pull/67)
> > > 
> > > 
> > > It is still wrong!
> > 
> > 
> > How do you modify your mmcv? I just successfully run it.
> 
> I use `faster_rcnn_r50_fpn_gn_ws_1x.py` now

How do you modified your mmcv? Why do you say it is still wrong? Could you tell me so that I can fix it.

**Comment by HuangQinJian** [comment]
> > > > > [open-mmlab/mmcv#67](https://github.com/open-mmlab/mmcv/pull/67)
> > > > 
> > > > 
> > > > It is still wrong!
> > > 
> > > 
> > > How do you modify your mmcv? I just successfully run it.
> > 
> > 
> > I use `faster_rcnn_r50_fpn_gn_ws_1x.py` now
> 
> How do you modified your mmcv? Why do you say it is still wrong? Could you tell me so that I can fix it.

You mennt I must modify mmcv?

**Comment by HuangQinJian** [comment]
> > > > > > [open-mmlab/mmcv#67](https://github.com/open-mmlab/mmcv/pull/67)
> > > > > 
> > > > > 
> > > > > It is still wrong!
> > > > 
> > > > 
> > > > How do you modify your mmcv? I just successfully run it.
> > > 
> > > 
> > > I use `faster_rcnn_r50_fpn_gn_ws_1x.py` now
> > 
> > 
> > How do you modified your mmcv? Why do you say it is still wrong? Could you tell me so that I can fix it.
> 
> You meant I must modify mmcv? How and where?



> > 
> 
> I use `faster_rcnn_r50_fpn_gn_ws_1x.py` now

Also ,you only modify resnetx101,no  resnet 50.

![image](https://user-images.githubusercontent.com/20330704/57580214-81727d00-74d9-11e9-8270-17e518d134b2.png)

**Comment by yhcao6** [comment]
You can follow the modification in https://github.com/open-mmlab/mmcv/pull/67.

Just replace `6adc888e` to `34ac1a9e` at this line.
https://github.com/open-mmlab/mmcv/blob/c728193f8d1dc62537c54b29748d9ba595184d40/mmcv/runner/checkpoint.py#L25

**Comment by yhcao6** [comment]
> > #629
> > It  still wrong!
> 
> ![image](https://user-images.githubusercontent.com/20330704/57578886-b0cbbe80-74c6-11e9-86ae-c153ea11c7f7.png)

You just mentioned `resnetx101` error earlier. Now I have fix them. Please have a check https://github.com/open-mmlab/mmcv/pull/67
