### ISSUE TITLE
dets very high?

### ISSUE THREAD

**Issue by deepsea12** [open-mmlab/mmdetection#6150]
![image](https://user-images.githubusercontent.com/90724607/134354614-d79e2a2d-e06f-4f93-b84e-bf0987409993.png)
 Any ideas why the no of dets is very high? I am testing 200 images ( KITTI dataset ) with pascal voc config and the original model.

**Comment by deepsea12** [comment]
Model setting: 
# model settings
model = dict(
    type='FasterRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0))),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='soft_nms', iou_threshold=0.5),
            max_per_img=100)
        # soft-nms is also supported for rcnn testing
        # e.g., nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05)
    ))
faster_rcnn_r50_fpn_1x_voc0712.py:
_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py', '../_base_/datasets/voc0712.py',
    '../_base_/default_runtime.py'
]
model = dict(roi_head=dict(bbox_head=dict(num_classes=2)))
CLASSES = ('car','person')
# optimizer
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
# actual epoch = 3 * 3 = 9
lr_config = dict(policy='step', step=[3])
# runtime settings
runner = dict(
    type='EpochBasedRunner', max_epochs=4)  # actual epoch = 4 * 3 = 12

voc.py:
![image](https://user-images.githubusercontent.com/90724607/134359888-8f738280-f945-4796-8624-707bbfe909f9.png)

class_names.py:
![image](https://user-images.githubusercontent.com/90724607/134360036-768b17a1-e0e3-40d9-9a92-257182be13aa.png)

**Comment by RangiLyu** [comment]
It is normal because the score threshold of the detection results which pass to the eval function is 0.05. The num of `dets` includes a lot of low score boxes.

**Comment by junhuplim** [comment]
Hi @RangiLyu , do you know where can I find the score threshold that you mention to be 0.05? I am looking to alter that parameter.

**Comment by RangiLyu** [comment]
> Hi @RangiLyu , do you know where can I find the score threshold that you mention to be 0.05? I am looking to alter that parameter.

It's in config
```
rcnn=dict(
score_thr=0.05,
nms=dict(type='soft_nms', iou_threshold=0.5),
max_per_img=100)
```

**Comment by junhuplim** [comment]
ahh i see, actually missed that.. thanks alot! :D

**Comment by RangiLyu** [comment]
> ahh i see, actually missed that.. thanks alot! :D
> 
> Edit: Is there any particular reason it was set at a low value of 0.05? I assume that this low value actually contribute to a high number of FP in relative to a higher number of TP, resulting in a drop of mAP.
> 
> Or is my calculating of mAP wrong? since I have tried increasing the threshold to say (0.2 instead of 0.05) --> my decrease in FP is much higher than the decrease in TP, but my mAP still decreased overall.

This is due to the mAP calculation mechanism. Boxes with all ranges of scores are used during the mAP calculation.

**Comment by junhuplim** [comment]
> 
> This is due to the mAP calculation mechanism. Boxes with all ranges of scores are used during the mAP calculation.

when you say boxes with all ranges of scores are used during the mAP calculation, do you mean only the boxes of scores above the set threshold? Am not really understanding here.

**Comment by RangiLyu** [comment]
Yes. 0.05 score threshold is to filter too many negative samples to speed up evaluation. All boxes with score above the threshold are used during the mAP calculation.

**Comment by deepsea12** [comment]
I set the score_thr  to 0.15, does that mean all the boxes with sore above 0.15 only are used during the mAP calculation. If so is this result justified?
![image](https://user-images.githubusercontent.com/9031472/135482529-b48f3a7b-6c31-4411-9b1c-58d76abb97ef.png)

**Comment by RangiLyu** [comment]
> I set the score_thr to 0.15, does that mean all the boxes with sore above 0.15 only are used during the mAP calculation. 

Yes, you are right.
