### ISSUE TITLE
ONNX export - MaskRCNN and skip-postprocessing

### ISSUE THREAD

**Issue by bpfliegel** [open-mmlab/mmdetection#6151]
Dear developers,

I have a custom (in terms of data, otherwise standard one included in mmdetection) MaskRCNN model, with which I was able to do a lot of things, export to onnx, build the corresponding onnx plugin for roialign and related ops and also got it working under Nvidia's Triton server.

What I'm struggling with is that the output for the masks is (Nx1xHxW), where N is 100, H,W is the original image size(!), and as I infer remotely I get a huge latency over the network, one call is 6-8 seconds as around 200-300MB is transferred.

I want to infer by only getting the non-postprocessed 28x28 float pred masks on the output, but if I export to onnx with 'skip-postprocessing', I get:
'RuntimeError: roi_width >= 0 && roi_height >= 0INTERNAL ASSERT FAILED at "../ops/csrc/pytorch/roi_align_cpu.cpp":137, please report a bug to PyTorch. ROIs in ROIAlign cannot have non-negative size!'
Without supplying 'skip-postprocessing' everything works as expected. Tried multiple PyTorch versions here, no luck,
I am also uncertain what RoiAlign has to do with mask postprocessing...

I'm also uncertain that skip-postprocessing matches my expectations, (to emit raw 28x28 preds) as:
'UserWarning: Not all models support export onnx without post process, especially two stage detectors!'

Please kindly guide.
Thanks, Balint

**Comment by bpfliegel** [comment]
This PR might be related: https://github.com/open-mmlab/mmdetection/pull/5282/commits

**Comment by bpfliegel** [comment]
In any case, please explain what post-processing means generally in mmdetection, how should we interpret it, Thanks!

**Comment by PeterVennerstrom** [comment]
_do_paste_masks() in export_onnx() in fcn_mask_head.py is responsible for resizing the model output size masks to the original image size.  

mask_onnx_export() in standard_roi_head.py has a reshaping operation that needs to be adjusted.  

The PR you linked shows the reshaping adjustment in standard_roi_head.py and _do_paste_masks() could just be commented out in fcn_mask_head.py

**Comment by bpfliegel** [comment]
@PeterVennerstrom very kind of you, thanks Peter. Will do as you suggested! Any comments on what generally post-processing means? I am totally new to mmdet, but like it much, very modular and lovely. Thanks again.

**Comment by PeterVennerstrom** [comment]
I think post-processing generally means the steps performed on the output of trained layers to yield the final results.  Filtering out low score detections, NMS, resizing to the original image size and thresholding of masks are a few examples of post processing steps.  The necessary post processing operations vary between methods.

**Comment by RangiLyu** [comment]
Postprocessing means decoding the output features from the CNN model into the final results such as boxes and masks. The specific process is the same as Peter said above.

**Comment by bpfliegel** [comment]
Very kind of you, thanks a lot for your clarification. It was very easy to do. Lovely framework, great job!

**Comment by guisolsan** [comment]
Dear developers,

I am trying to move MaskRCNN from pytorch to onnx but I am getting the same error, I have tried using the information you propose but I still can't get it to work. any help?

Thanks
