### ISSUE TITLE
Variables in config

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [open-mmlab/mmdetection#6153]
**Describe the feature**
I would like to have variable in the config.py file. One use case is a custom dataset path that may be known only ad runtime. Currently, there is no way to inject a variable in the config file.

Thank you!

Cheers,

Francesco

**Comment by RangiLyu** [comment]
The config is modifiable. How did you inject the variable? Any use case?

**Comment by FrancescoSaverioZuppichini** [comment]
Yes, it is :) Imagine for example that I don't want to call `train.py` from the `cl`.

**Comment by hhaAndroid** [comment]
@FrancescoSaverioZuppichini Very good, but you can also directly add variables in the configuration and read them in the program yourself, which would be better.

**Comment by FrancescoSaverioZuppichini** [comment]
@hhaAndroid No I can, what if I need to add an instance of a class? or anything that is not a literal
