### ISSUE TITLE
Testing with negative images

### ISSUE THREAD

**Issue by junhuplim** [open-mmlab/mmdetection#6159]
I am training a FRCNN with custom dataset, and want to test my model with negative images (images with no annotations). Currently, my json contains no bbox annotations for these negative images. 

In the documentation, it says that model will not filter any images in test mode. However, my negative images are not being considered when i run `test.py config model --eval mAP`. 

Do I need to include any bbox annotations (like 0,0,0,0) for images with no annotations to test?

**Comment by BIGWangYuDong** [comment]
Hi, it seems that if you only inference these images, it does not need annotations. it is suggested to use `test.py config model --out result.pkl`, if you use eval, it will need annotations

**Comment by junhuplim** [comment]
Okay, it was my mistake. I forgot to update my json to include those negative images. I was able to run eval without annotations. I will try using `--out result.pkl` too
