### ISSUE TITLE
Calculating model size/parameters for models under mmdet?

### ISSUE THREAD

**Issue by neel04** [open-mmlab/mmdetection#6163]
This is a pretty critical and crucial QoL feature, yet since #264 we haven't got a way to do it?

If someone does know a quick way to calculate the same, or some feature I missed it would be more than welcome! 🤗

**Comment by hhaAndroid** [comment]
@neel04 Please refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/useful_tools.md#model-complexity

**Comment by neel04** [comment]
That's grand! Thanx a lot @hhaAndroid ! 🤗

**Comment by neel04** [comment]
However, using this:-
```py
RuntimeError: roi_width >= 0 && roi_height >= 0 INTERNAL ASSERT FAILED at "/tmp/pip-install-47obb_qv/mmcv-full_22ae3c0003964445b7382159353a006e/mmcv/ops/csrc/pytorch/roi_align_cpu.cpp":138, please report a bug to PyTorch. ROIs in ROIAlign cannot have non-negative size!
```
seems like a bug, but I guess I can do away with this. Please investigate if you are able to reproduce!

**Comment by hhaAndroid** [comment]
@neel04 Sorry for the late reply, I will check it.

**Comment by hhaAndroid** [comment]
@neel04 I have confirmed that there is no problem, may I ask if you still have any questions？
