### ISSUE TITLE
When convert model from ONNX to TensorRT, ERROR: TopK_1080: length of reduction axis (950) is smaller than K (1000)

### ISSUE THREAD

**Issue by AIZOOTech** [open-mmlab/mmdetection#6166]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I download the model from mmdetection model zoo, and I try to convert the model to TensorRT, I can convert to ONNX model with the command `python tools/deployment/pytorch2onnx.py configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py checkpoints/fcos_r50_caffe_fpn_gn-head_1x_coco-821213aa.pth --output-file model_conversion/fcos_r50_caffe_fpn_gn-head_1x_coco.onnx  --shape 1280 1280      --dynamic-export`.
But when I run `python tools/deployment/onnx2tensorrt.py configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py model_conversion/fcos_r50_caffe_fpn_gn-head_1x_coco.onnx --trt-file model_conversion/fcos_r50_caffe_fpn_gn-head_1x_coco.trt --verbose`,  ERROR occurs:
```
[TensorRT] ERROR: TopK_1080: length of reduction axis (950) is smaller than K (1000)
[TensorRT] ERROR: Builder failed while analyzing shapes.
```

**Reproduction**

1. What command or script did you run?

```
# convert model to onnx
python tools/deployment/pytorch2onnx.py configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py checkpoints/fcos_r50_caffe_fpn_gn-head_1x_coco-821213aa.pth --output-file model_conversion/fcos_r50_caffe_fpn_gn-head_1x_coco.onnx  --shape 1280 1280      --dynamic-export

# convert model to tensorRT
python tools/deployment/onnx2tensorrt.py configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py model_conversion/fcos_r50_caffe_fpn_gn-head_1x_coco.onnx --trt-file model_conversion/fcos_r50_caffe_fpn_gn-head_1x_coco.trt --verbose
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
 No.
3. What dataset did you use?
COCO dataset

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (GCC) 5.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.5.3
MMCV: 1.3.14
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.2
MMDetection: 2.16.0+5ef56c1
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
     pip install 
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Comment by ZwwWayne** [comment]
Hi @AIZOOTech ,
Could you also give more details about the version of onnx, onnxruntime, and TensorRT?

Also, include @RunningLeon to take a look.

**Comment by RunningLeon** [comment]
@AIZOOTech Hi, you get the error because the K of `TopK` layer in TensorRT is static. You may need to set a min-shape and export environment variable to dynamically determine the K with `export ONNX_BACKEND=MMCVTensorRT` while running `pytorch2onnx.py`.
