### ISSUE TITLE
multi-scale testing with HTC

### ISSUE THREAD

**Issue by hyz-xmaster** [open-mmlab/mmdetection#617]
It seems that mmdet hasn't implemented the multi-scale testing function with HTC detector. Could you please add this function to HTC detector?  Thank you.

 File "~/mmdet/mmdet/models/detectors/htc.py", line 392, in aug_test
    raise NotImplementedError
NotImplementedError

**Comment by hellock** [comment]
We have no recent plan to implement that, you can try it by yourself.
