### ISSUE TITLE
ATSS applied to RetinaNet causes Bug

### ISSUE THREAD

**Issue by lji72** [open-mmlab/mmdetection#6170]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
 I want to improve the retinanet model performance by applying ATSS method as positive sample definition method, then causes this issue.

**Reproduction**

1. What command or script did you run?

```
CUDA_VISIBLE_DEVICES=0,1,2,3 ./tools/dist_train.sh configs/retinanet/retinanet_r50_fpn_1x_coco_atss.py  4
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes,  I modify the positive sample definition from IoU threshold rule to ATSS.
    train_cfg=dict(
        #assigner=dict(
        #    type='MaxIoUAssigner',
        #    pos_iou_thr=0.5,
        #    neg_iou_thr=0.4,
        #    min_pos_iou=0,
        #    ignore_iof_thr=-1),
        assigner=dict(type='ATSSAssigner', topk=9),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),

3. What dataset did you use?
    COCO2017

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
fatal: Not a git repository (or any parent up to mount point /var/lib/docker)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: True
GPU 0,1,2,3: Tesla P100-PCIE-16GB
CUDA_HOME: /usr/local/cuda-11
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.0
OpenCV: 4.5.3
MMCV: 1.3.9
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.16.0+

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/scratch/workspace/xxx/anaconda3/envs/mm2_mlperf/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/var/lib/docker/scratch/workspace/xxx/mlperf_retinanet/mmdetection-master/mmdet/models/dense_heads/anchor_head.py", line 464, in loss
    label_channels=label_channels)
  File "/var/lib/docker/scratch/workspace/xxx/mlperf_retinanet/mmdetection-master/mmdet/models/dense_heads/anchor_head.py", line 346, in get_targets
    unmap_outputs=unmap_outputs)
  File "/var/lib/docker/scratch/workspace/xxx/mlperf_retinanet/mmdetection-master/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/var/lib/docker/scratch/workspace/xxx/mlperf_retinanet/mmdetection-master/mmdet/models/dense_heads/anchor_head.py", line 220, in _get_targets_single
    None if self.sampling else gt_labels)
  File "/var/lib/docker/scratch/workspace/xxx/mlperf_retinanet/mmdetection-master/mmdet/core/bbox/assigners/atss_assigner.py", line 69, in assign
    num_gt, num_bboxes = gt_bboxes.size(0), bboxes.size(0)
AttributeError: 'NoneType' object has no attribute 'size'
Traceback (most recent call last):
  File "/scratch/workspace/xxx/anaconda3/envs/mm2_mlperf/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/scratch/workspace/xxx/anaconda3/envs/mm2_mlperf/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/workspace/xxx/anaconda3/envs/mm2_mlperf/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/scratch/workspace/xxx/anaconda3/envs/mm2_mlperf/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/scratch/workspace/xxx/anaconda3/envs/mm2_mlperf/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/retinanet/retinanet_r50_fpn_1x_coco_atss.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by jshilong** [comment]
The interface of `ATSSAssigner ` is different from `MaxIoUAssigner`, we will try to improve it. 
We try to design a more general interface of assigner but we find it is quite an algorithm related component, which makes it very difficult

**Comment by lji72** [comment]
ok，thanks, wait for your modification.
