### ISSUE TITLE
I want to know "Is MASK R-CNN used Sigmoid or Softmax and about mAP"

### ISSUE THREAD

**Issue by yoonj1n** [open-mmlab/mmdetection#6178]
Hi, I used mmdetection to make mask r-cnn model

question 1)
i just want to know Mask R-CNN use or not Sigmoid or Softmax and if we use, where is the code or something that i can know that?

question 2)
where is the code that calculate validation mAP?

Thanks

**Comment by hhaAndroid** [comment]
@yoonj1n 

1. use sigmoid in RPN box head, use softmax in RoI box head. All in https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/mask_rcnn_r50_fpn.py
2. https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L362
