### ISSUE TITLE
[docs] Verifiable demo after installing with pip

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmdetection#6182]
**Describe the feature**

**Motivation**
I found the verifiable script here:  https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md#verification, but it can not work if the code base is installed with pip, so another verifiable script is needed

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by del-zhenwu** [comment]
Also, there are some warnings displayed, this script may need to be updated.
```
/mnt/lustre/lizhenxiang.vendor/mmdetection/mmdet/core/anchor/builder.py:17: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Use load_from_local loader
/mnt/lustre/lizhenxiang.vendor/mmdetection/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
/mnt/lustre/lizhenxiang.vendor/mmdetection/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/mnt/lustre/lizhenxiang.vendor/mmdetection/mmdet/core/anchor/anchor_generator.py:361: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '

```

**Comment by hhaAndroid** [comment]
@del-zhenwu What error does the verification script report?

**Comment by del-zhenwu** [comment]
> @del-zhenwu You need to confirm whether the file exists on your machine

That means the user can run the demo script only when the source code downloaded before, right? If so, I suggest some more description need to added in the doc, especially the verification doc with the `pip` installation.
