### ISSUE TITLE
potential bug of swin init_weights 

### ISSUE THREAD

**Issue by HarborYuan** [open-mmlab/mmdetection#6186]
Hi,

Thanks for your work on mmdet.

It seems that swin init_weights function may have unexpected behavior when the checkpoint is with old version.

https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/swin.py#L697

If in the checkpoint, the states are with backbone. prefix, the swin_converter will not do the right thing. At the same time, the swin_converter will add "backbone." prefix at last, which seems redundant.

**Comment by hhaAndroid** [comment]
@HarborYuan Thank you for your attention, the currently loaded third-party pre-training weights are the specified version. The problem you mentioned is really not robust enough. It can be improved, and community PR is very welcome.
