### ISSUE TITLE
Impossible to correctly retrieve metrics and to extend the codebase

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [open-mmlab/mmdetection#6188]
Dear all,

I hope to find you well. The current codebase is totally closed and it is impossible to retrieve all the metrics computed. Allow *all* metrics to be returned inside `dataset.evaluate`. For instance, currently, we cannot get the `map` per class that is printed inside [`eval_map`](https://github.com/open-mmlab/mmdetection/blob/414c62cb12d1b0ebf6151a697a32b84adc269ca4/mmdet/core/evaluation/mean_ap.py#L297). This makes it impossible to correctly create different experiments and to track all the metrics to later evaluate the model. Moreover, the codebase is so coupled that is virtually impossible to add anything to the metrics making using this framework not ideal in anything that is not a sandbox example.

I am looking forward to hearing your thoughts about this. I bet you have already thought about it and maybe a solution is in the pipeline. From my side I won't be using mmdetection in the future, the library is not ready yet for real-life production scenarios but I hope I will be able to help somewhere. 

Thank you!

Francesco

**Comment by hhaAndroid** [comment]
@FrancescoSaverioZuppichini Thank you for your sincere suggestions. We have recently noticed this problem and are  redesigning the evaluation process.  If you have good suggestions, welcome to discuss together.

**Comment by FrancescoSaverioZuppichini** [comment]
@hhaAndroid thank you for you reply. Sure! What about moving this issue to the discussion tab?
