### ISSUE TITLE
question about --validate on non-distribute train?

### ISSUE THREAD

**Issue by Peterisfar** [open-mmlab/mmdetection#619]
![image](https://user-images.githubusercontent.com/31852119/57506045-3b78b600-732d-11e9-9913-dd5a93955455.png)

there is no validate's funs  but distribute has , so how i can use validate in non-distribute?

**Comment by hellock** [comment]
Non-distributed training is kept in the repo only for debugging purpose, not for training. We have no plan to support validation for non-distributed mode.

**Comment by Peterisfar** [comment]
thanks!

**Comment by yxchng** [comment]
@hellock Can I know why do you not want to support validation for non-distributed mode?

**Comment by thangvubk** [comment]
I agree that non-distributed is also helpful for training. To my experience, when training with pre-computed proposals (e.g., Fast RCNN), RAM usage of non-distributed training is much less than distributed training. Distributed training even can't run on 128G RAM server.

**Comment by OceanPang** [comment]
@thangvubk Please try to set the workers_per_gpu of Fast R-CNN as 0 when you adopt distributed training. The RAM usage would be large lower.

**Comment by thangvubk** [comment]
@OceanPang thanks for your info
