### ISSUE TITLE
Increasing Memory usage during demo

### ISSUE THREAD

**Issue by sunwell1994** [open-mmlab/mmdetection#6193]
I test the basic inference on the video using faster-rcnn model. I try to store the generated frames. However, I find the memory of system keeps increasing and finally it causes the program to be killed due to OOM. Does the inference cache up a lot of unnecessary data? How to avoid caching?

**Comment by AronLin** [comment]
That means you put them into the memory during storing the frames.
You can store them on the disk directly to avoid this problem.
