### ISSUE TITLE
mmdet 支持没有label的图片输入吗，如果支持如何操作

### ISSUE THREAD

**Issue by zhanghang-cv** [open-mmlab/mmdetection#6196]

**Comment by hhaAndroid** [comment]
Only set filter_empty_gt=False:

```shell
train_dataset = dict(
    dataset=dict(
        filter_empty_gt=False,
    )

```

**Comment by zhanghang-cv** [comment]
> Only set filter_empty_gt=False:
> 
> ```shell
> train_dataset = dict(
>     dataset=dict(
>         filter_empty_gt=False,
>     )
> ```

那设置了filter_empty_gt=False后coco标注文件的"annotations"如何设置呢

**Comment by zhanghang-cv** [comment]
> Only set filter_empty_gt=False:
> 
> ```shell
> train_dataset = dict(
>     dataset=dict(
>         filter_empty_gt=False,
>     )
> ```

如果设置成
![image](https://user-images.githubusercontent.com/68639705/135402137-c42639f7-b25a-40f4-b88b-2fdd5ec72167.png)
会报错
![image](https://user-images.githubusercontent.com/68639705/135402193-ef8d0e7c-1f9b-409f-afc1-82cf74e6249b.png)

**Comment by zhanghang-cv** [comment]
> 只设置 filter_empty_gt=False：
> 
> ```shell
> train_dataset = 字典（
>     数据集=字典（
>         filter_empty_gt=假，
>     )
> ```

想加入的是没有任何目标的图片进行训练（没有bbox也没有cat）

**Comment by AronLin** [comment]
You need to write your own dataset to support this function.
Our CocoDataset supports inference without annotations, but does not support training without annotations.

**Comment by hhaAndroid** [comment]
@zhanghang-cv You can set `'bbox': [0,0,0,0]`.

**Comment by zhanghang-cv** [comment]
> @zhanghang-cv You can set `'bbox': [0,0,0,0]`.

那类别设置成什么呢，'bbox': [0,0,0,0]会不会影响loss计算
