### ISSUE TITLE
redundant code in mmdet/models/builder.py

### ISSUE THREAD

**Issue by aa1234241** [open-mmlab/mmdetection#6198]
Hi,
When I read the source code, I found in  mmdet/models/builder.py
`MODELS = Registry('models', parent=MMCV_MODELS)

BACKBONES = MODELS
NECKS = MODELS
ROI_EXTRACTORS = MODELS
SHARED_HEADS = MODELS
HEADS = MODELS
LOSSES = MODELS
DETECTORS = MODELS`

I'm a little confused since all these names map to the same MODELS, why do you need to map the same thing with different names. Many thanks.

**Comment by hhaAndroid** [comment]
@aa1234241 Because we have to distinguish between different model components.

**Comment by aa1234241** [comment]
> @aa1234241 Because we have to distinguish between different model components.

yeah, I know that, but this code means that all components are registered to the same Registry. So the BACKBONES, NECKS, etc. All components will be registered to the MODELS, not separate Registry.

**Comment by hhaAndroid** [comment]
@aa1234241 Yes. This is set from the uniform rules of all open source libraries of OpenMMLab. This is reasonable.
