### ISSUE TITLE
关于超分辨率图片比如大型的遥感图，怎么采用滑窗分割训练滑窗预测呀？

### ISSUE THREAD

**Issue by universea** [open-mmlab/mmdetection#620]
现有遥感图16000*16000像素，目标大概200x200，iou要求0.8+，请问这种我们的框架有什么方案吗

**Comment by hellock** [comment]
This is up to you.

**Comment by Smoothing97** [comment]
为什么要求iou，iou不是自己设定的吗，可以参考下yolt，它的图像尺寸很大。
我接触的都是5000大小，目标最大不超过图像的1/10,用rcnn就可以检测了，切片800大小。

**Comment by Baby47** [comment]
@ Smoothing97, i wonder what dataset do you use to train and how the final result in high resolution image is achieved (detect image chips and combine them to the large one?)

**Comment by gtwell** [comment]
> @ Smoothing97, i wonder what dataset do you use to train and how the final result in high resolution image is achieved (detect image chips and combine them to the large one?)

既然能看懂中文咋不直接中文回复，23333333333
