### ISSUE TITLE
Cannot find the eval results in runner.log_buffer.output 

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [open-mmlab/mmdetection#6203]
Hi guys, 

I hope you are doing great. I am trying to get the `eval_results` from my custom hook but even if they are set (https://github.com/open-mmlab/mmcv/blob/8cac7c25ee5bc199d6e4059297ef2fa92d9c069c/mmcv/runner/hooks/evaluation.py#L327) in `runner.log_buffer.output` I am not able to find them. I have tried with any time of callbacks in the hooks APIs (after_iter, after_epoch, after_val_epoch, etc) but the `log_buffer` is always empty

```
@HOOKS.register_module()
class EarlyStopping(Hook):
    def after_val_epoch(self, runner):
        print(runner.log_buffer.output)

```

Output:

```
OrderedDict()
```

What is the correct way to properly fetch the eval results?

Thank you

**Comment by RangiLyu** [comment]
MMCV will support EarlyStopping. Welcome to discussion at that PR https://github.com/open-mmlab/mmcv/pull/1602
