### ISSUE TITLE
undefined symbol: _ZN5torch3jit6tracer9addInputsEPNS0_4NodeEPKcRKN3c1013TensorOptionsE

### ISSUE THREAD

**Issue by tianrking** [open-mmlab/mmdetection#6207]
Ubuntu20

I only have GTX1050Ti onmy old computer ,however I setup Nvidia driver 460 which CUDA version is 11.2
So, I conda install pytorch torchvision torchaudio cudatoolkit=11.2 -c pytorch -c conda-forge  BUT it cannot work well. 
PLZ help me.

    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/w0x7ce/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5torch3jit6tracer9addInputsEPNS0_4NodeEPKcRKN3c1013TensorOptionsE

# packages in environment at /home/w0x7ce/anaconda3/envs/mmcv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py37h89c1867_0    conda-forge
cffi                      1.14.6           py37hc58025e_0    conda-forge
cudatoolkit               11.2.2               he111cf0_8    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
dotty-dict                1.3.0                    pypi_0    pypi
flake8                    3.9.2                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py37h89c1867_3    conda-forge
importlib-metadata        4.8.1                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2021.3.0          h06a4308_3350  
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0            11_linux64_mkl    conda-forge
libcblas                  3.9.0            11_linux64_mkl    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
liblapack                 3.9.0            11_linux64_mkl    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.16.0               h780b84a_0    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.0.10            hc3755c2_1005    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib                3.4.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mkl                       2021.3.0           h06a4308_520  
mmcls                     0.16.0                   pypi_0    pypi
mmcv-full                 1.3.14                   pypi_0    pypi
mmdet                     2.17.0                   pypi_0    pypi
mmtrack                   0.7.0                    pypi_0    pypi
motmetrics                1.2.0                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2               h4bd325d_0    conda-forge
numpy                     1.21.2                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.5.3.56                 pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0                     pypi_0    pypi
pandas                    1.3.3                    pypi_0    pypi
pillow                    6.2.1            py37h6b7be26_0    conda-forge
pip                       21.2.2           py37h06a4308_0  
pluggy                    1.0.0                    pypi_0    pypi
py                        1.10.0                   pypi_0    pypi
py-cpuinfo                8.0.0                    pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pycodestyle               2.7.0                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyflakes                  2.3.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pytest                    6.2.5                    pypi_0    pypi
pytest-benchmark          3.4.1                    pypi_0    pypi
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
scipy                     1.7.1                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
setuptools                58.0.4           py37h06a4308_0  
setuptools-scm            6.3.2                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h7f98852_1    conda-forge
sqlite                    3.36.0               hc218d9a_0  
terminaltables            3.1.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
toml                      0.10.2                   pypi_0    pypi
tomli                     1.2.1                    pypi_0    pypi
torch                     1.9.1                    pypi_0    pypi
torchaudio                0.9.0                      py37    pytorch
torchvision               0.10.1                   pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
wheel                     0.37.0             pyhd3eb1b0_1  
xmltodict                 0.12.0                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                ha95c52a_0    conda-forge

**Comment by BIGWangYuDong** [comment]
Hi, 
I remember that `mmcv` does not support CUDA11.2 yet? 
It's seems that your PyTorch, CUDA and mmcv is not matched. it is suggested to re-build an environment under CUDA 11.1, torch 1.9 and you can install mmcv-full by `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`

**Comment by BIGWangYuDong** [comment]
Please feel free to create a new issue if you still meet this error

**Comment by HyunjiEllenPak** [comment]
@BIGWangYuDong it worked for me, thanks.
