### ISSUE TITLE
Why ATSS need different GPU memory according to dataset?

### ISSUE THREAD

**Issue by dev-sungman** [open-mmlab/mmdetection#6209]
Hi, 

I found a strange point that ATSS needs different GPU memory according to the dataset. 
i.e. if I trained with the A dataset, the consumption of GPU is 17GB. 
However, if I trained with the B dataset, the consumption of GPU is changed to 13GB. 
Is it a normal case? is this caused by the ATSS head assigner?

![image](https://user-images.githubusercontent.com/36710497/135566530-3a349f60-2ef9-453c-8b11-b2b2eaff32c9.png)

**Comment by PeterVennerstrom** [comment]
Single stage methods like ATSS that densely predict classes will require noticeably more GPU memory as the number of classes increase.

**Comment by dev-sungman** [comment]
@PeterVennerstrom . Thanks for the kind information. 
But, the different GPU usage even occurred when datasets have the same number of classes.

**Comment by thisisi3** [comment]
> Single stage methods like ATSS that densely predict classes will require noticeably more GPU memory as the number of classes increase.

I have some doubts about this observation, increase of class number won't change feature maps, won't change ATSSHead(RetinaHead). It only changes the final output of classification branch. So I don't know if mem will noticeably increase as we increase number of classes. Am I missing something?
