### ISSUE TITLE
Question on the dataset concatenation

### ISSUE THREAD

**Issue by shwoo93** [open-mmlab/mmdetection#6213]
Hello,

I have several questions on the features of ConcatDataset.
It seems that the ConcatDataset basically enables to use different datasets as a whole. 

1. If I want to construct a batch with images always come from different datasets, is it proper to use ConcatDataset? 
2. Also, can we modulate the frequency of each dataset being selected in ConcatDataset? (Maybe setting different repeat time for each datasets and concatenate them)? 

Look forward to your reply. Thanks

**Comment by AronLin** [comment]
We do not support these settings, you may need to implement them yourself.
