### ISSUE TITLE
AssertionError in 2nd training epoch, when using Mosaic augmentation

### ISSUE THREAD

**Issue by Kaze-wind** [open-mmlab/mmdetection#6214]
After succeed in the yolox-s training, which is killed after 2 epochs. 
I tried the Mosaic augmentation with MultiImageMixDataset like this:
```python
train_pipeline = [
    dict(type='Mosaic', img_scale=(780,128), pad_val=114.0),
    dict(
        type='MixUp',
        img_scale=(780,128),
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Resize', keep_ratio=True),
    dict(type='Pad', pad_to_square=True, pad_val=114.0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/train_annotations.json',
        img_prefix=data_root + 'train/',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True)
        ],
        filter_empty_gt=True,
    ),
    pipeline=train_pipeline,
    dynamic_scale=(780,128))
```
The first epoch goes well, the loss drops, it works ! 
But sadly, at the beginning of 2nd epoch, I encountered one AssertionError. 
```python traceback
Original Traceback (most recent call last):
  File "/root/.miniconda/envs/env_torch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.miniconda/envs/env_torch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.miniconda/envs/env_torch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/mmdetection/mmdet/datasets/custom.py", line 195, in __getitem__
    data = self.prepare_train_img(idx)
  File "/root/mmdetection/mmdet/datasets/custom.py", line 221, in prepare_train_img
    return self.pipeline(results)
  File "/root/mmdetection/mmdet/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/root/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2013, in __call__
    results = self._mosaic_transform(results)
  File "/root/mmdetection/mmdet/datasets/pipelines/transforms.py", line 2039, in _mosaic_transform
    assert 'mix_results' in results
AssertionError
```
I found #6155  with the same problem, but I found no solutions.
Are there anyone know how to fix this problem ? Is it a matter of mmcv/mmdet version ?

**Comment by Kaze-wind** [comment]
I found that the `MultiImageMixDataset` use the `CocoDataset` to load datasets for Mosaic / Mixup, which finally trace back to `CustomDataset`. 
In the first epoch, the pipeline within the CustomDataset is `[dict(type='LoadImageFromFile', to_float32=True), dict(type='LoadAnnotations', with_bbox=True, with_mask=True)]` , it matches the config.
However in the second epoch, the pipeline becomes the train_pipeline, that is `[dict(type='Mosaic', ..., ,dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])]`.

I tried to froze the pipeline, rather than from the interfaces, but the pipeline still changes in the 2nd epoch.
Then, I try to modify the `prepare_train_img` function like this. Epoch1 runs quite well. Then still the 2nd epoch, comes a new bug, surprise~~~
```python
  def prepare_train_img(self, idx):
      img_info = self.data_infos[idx]
      ann_info = self.get_ann_info(idx)
      results = dict(img_info=img_info, ann_info=ann_info)
      if self.proposals is not None:
          results['proposals'] = self.proposals[idx]
      self.pre_pipeline(results)
      fix_pipeline = Compose([dict(type='LoadImageFromFile', to_float32=True),
                              dict(type='LoadAnnotations', with_bbox=True, with_mask=True)])
      return fix_pipeline(results)
```
```python traceback
  File "/root/.miniconda/envs/env_torch/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/root/.miniconda/envs/env_torch/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 23, in collate
    if not isinstance(batch, Sequence):
  File "/root/.miniconda/envs/env_torch/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/root/.miniconda/envs/env_torch/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded

```
It is really weird...

As for modifying the `Compose` class, so as to support Mosaic/Mixup, I found it is hard to achieve. 
1. The pipeline in the 2nd epoch lacks 'LoadImageFromFile' & 'LoadAnnotations'
2. The interface can only access 1 data, not suitable for Mosaic & Mixup

Can anyone help me ?

**Comment by justpi** [comment]
I got the same problem, did you solve it?

**Comment by Kaze-wind** [comment]
> I got the same problem, did you solve it?

I tried to **EXACTLY** follow the configs of yolox, that is, all modifications are based on the original `yolox_s_8x8_300e_coco.py` and all configs are within the same top `.py` file.
Only the model and `_base_/schedule_1x.py` and `_base_/default_runtime.py` are imported from the `_base_ = [ ... ]` syntax.

This helps me to avoid the aforementioned problem, hope this can also solve your problem.

By the way, I added the Mosaic and Mixup in the `_base_/datasets/coco_instance.py` before, and I think the pipelines are replaced somewhere when mmdet starts the 2nd epoch. But deeper logic is still unknown for me.

**Comment by justpi** [comment]
> > I got the same problem, did you solve it?
> 
> I tried to **EXACTLY** follow the configs of yolox, that is, all modifications are based on the original `yolox_s_8x8_300e_coco.py` and all configs are within the same top `.py` file. Only the model and `_base_/schedule_1x.py` and `_base_/default_runtime.py` are imported from the `_base_ = [ ... ]` syntax.
> 
> This helps me to avoid the aforementioned problem, hope this can also solve your problem.
> 
> By the way, I added the Mosaic and Mixup in the `_base_/datasets/coco_instance.py` before, and I think the pipelines are replaced somewhere when mmdet starts the 2nd epoch. But deeper logic is still unknown for me.

It works, thank you!
