### ISSUE TITLE
Using pretrained weight for custom model

### ISSUE THREAD

**Issue by Jack-Hu-2001** [open-mmlab/mmdetection#6222]
I need to use the pretrained.pth for my next stage training. I wonna use not only the weight in backbone but also the neck and head. what can I do?
Thanks a lot for your help!!!

**Comment by Jack-Hu-2001** [comment]
It's very late, please reply when you're available. No need to hurry.

**Comment by neel04** [comment]
yea, also is there a way to use pre-trained checkpoints of detector as well? I don't think I am getting **both** loaded, though the logs clearly show that one's being loaded atleast

**Comment by Jack-Hu-2001** [comment]
If I ue resume from, mmdetection will simply use the config file stored in the pth file, not the one I need for the next stage, which confused me.

**Comment by Jack-Hu-2001** [comment]
It's actually another question.
