### ISSUE TITLE
Is any other code to calculate mask’s mAP and mAR?

### ISSUE THREAD

**Issue by yoonj1n** [open-mmlab/mmdetection#6224]
hi, i saw some code about calculating mAP and mAR in mmdet.evaluate but, i dont know that we use the same code to calculate mask and bbox mAP and mAR or not using MASK R CNN
is used same code ? or we have any other code for mask? thanks

**Comment by ZwwWayne** [comment]
We use pycocotools to calculate mask AP and mAR following common practices. See related code here: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L440
