### ISSUE TITLE
How to change the color of segmentation results of different instances

### ISSUE THREAD

**Issue by AGanPoi** [open-mmlab/mmdetection#6228]
I find the mmdet/models/detectors/base.py that can change the color of bbox and text, but the segm results of the same category with different instances draw with the same color. I wonder how to change this color settings.
![QQ图片20211004170706](https://user-images.githubusercontent.com/35792267/135824231-b5f29209-bdd4-4c7a-8c6c-ba3da0e56562.png)

**Comment by jshilong** [comment]
You can refer to
https://github.com/open-mmlab/mmdetection/blob/c88509cb9a73d6bd1edcba64eb924d3cf3cfe85d/mmdet/core/visualization/image.py#L160
you need random select a color for each instance

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
