### ISSUE TITLE
[BUG]bug in ConvFCBBoxHead's init cfg.

### ISSUE THREAD

**Issue by thisisi3** [open-mmlab/mmdetection#6238]
https://github.com/open-mmlab/mmdetection/blob/c88509cb9a73d6bd1edcba64eb924d3cf3cfe85d/mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py#L103

This line will override initializers for fc_cls and fc_reg because they are also nn.Linear. 
Or is it what's intended? But I see the old way to initialize fc_cls and fc_reg is using Normal.

**Comment by jshilong** [comment]
> Can anyone tell me if it is an error or it is supposed to be like this? I really want to know, as tests on small dataset (voc07) shows a big difference.

I will check it

**Comment by jshilong** [comment]
> https://github.com/open-mmlab/mmdetection/blob/c88509cb9a73d6bd1edcba64eb924d3cf3cfe85d/mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py#L103
> 
> This line will override initializers for fc_cls and fc_reg because they are also nn.Linear. Or is it what's intended? But I see the old way to initialize fc_cls and fc_reg is using Normal.

Sorry for the late respondence, 
you are right, we will fix asap
