### ISSUE TITLE
KeyError: 'supercategory' while using coco_error_analysis.py

### ISSUE THREAD

**Issue by apanand14** [open-mmlab/mmdetection#6240]
I'm doing the coco_error_anaylsis after successfully training and testing on custom dataset. And I do not have any supercategory in my coco json files. I'm facing this error. 
I use, 
**mmcv-full (1.1.5)
mmdet 2.7.0**

Here is the complete error message which I get:

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.10s).
Accumulating evaluation results...
DONE (t=0.01s).
--------------analyzing 1 Dog----------------
--------------analyzing 2 Cat----------------
creating index...
index created!
creating index...
index created!
multiprocessing.pool.RemoteTraceback:
"""
**Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\temp_mask\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\anaconda3\envs\temp_mask\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\anand\temp_mask\RefineMask\tools\coco_error_analysis.py", line 68, in analyze_individual_category
    child_catIds = gt.getCatIds(supNms=[nm['supercategory']])
KeyError: 'supercategory'**
"""

The above exception was the direct cause of the following exception:

**Traceback (most recent call last):
  File "tools/coco_error_analysis.py", line 170, in <module>
    main()
  File "tools/coco_error_analysis.py", line 166, in main
    analyze_results(args.result, args.ann, args.types, out_dir=args.out_dir)
  File "tools/coco_error_analysis.py", line 135, in analyze_results
    analyze_results = pool.starmap(analyze_individual_category, args)
  File "C:\Users\anaconda3\envs\temp_mask\lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\anaconda3\envs\temp_mask\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
KeyError: 'supercategory'**

Your help will be appreciated. thank you in advance.

**Comment by BIGWangYuDong** [comment]
Hi, it is suggested to update mmdet version, and maybe you can re-build your environment and try it again. This error seems to occur in `multiprocessing.Pool`, so try to rebuild your environment again. If you also meet this error, please let us know

**Comment by Rov77777** [comment]
i got same error, i don't use supercategories in my coco style custom dataset.
My environment comes from a custom made docker image with the latest versions of MMCV and MMDetection (i.e.: MMCV: 1.4.0, MMCV Compiler: GCC 7.3, MMCV CUDA Compiler: 11.3, MMDetection: 2.19.0+f08548b).
Any suggestion?

**Comment by JackMa-coder** [comment]
> just delete the codes that cause errors as follows, # child_catIds = gt.getCatIds(supNms=[nm['name']]) # for idx, ann in enumerate(gt.dataset['annotations']): # if ann['category_id'] in child_catIds and ann['category_id'] != catId: # gt.dataset['annotations'][idx]['ignore'] = 1 # gt.dataset['annotations'][idx]['iscrowd'] = 1 # gt.dataset['annotations'][idx]['category_id'] = catId problems solved!
Thanks for your answer. It's useful for me.

**Comment by Tender-hjd** [comment]
@SleepyFanz Thanks! It works!
