### ISSUE TITLE
Potential bug in function "forward_train" in "mmdet/models/detectors/two_stage.py"

### ISSUE THREAD

**Issue by pingguokiller** [open-mmlab/mmdetection#6242]
**Describe the bug**
If I embedded some data through a customized pipeline, i.e. the input parameter "kwargs" is not None, an error would occur at line "roi_losses = self.roi_head.forward_train(x, img_metas, proposal_list".

**Bug fix**

In function "forward_train" in "mmdet/models/roi_heads/standard_roi_head.py",  ", **kwargs" should be added at the end of the definition of the function.

**Comment by BIGWangYuDong** [comment]
Hi, you are right, you can create a Pull Request(PR).
