### ISSUE TITLE
Specific model code problems

### ISSUE THREAD

**Issue by sxy1122** [open-mmlab/mmdetection#6246]
![image](https://user-images.githubusercontent.com/77336413/136568841-35cf83ed-3bd0-49db-9d3b-174b21aec7fe.png)

I would like to ask, the specific DCN is like a Resnet file. Where can I see the specific code. Or how to import the existing DCN modules into other frameworks? Because I didn't find the code related to DCN, I only found some files related to DCN in the configurations file

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
