### ISSUE TITLE
convert onnx to trt, the tqdm show speed is too slow

### ISSUE THREAD

**Issue by luuuyi** [open-mmlab/mmdetection#6255]
Hi, everyone. Have anybody found that when we follow the official guide to convert model as pytorch->onnx->tensorrt, and test the mAP with `tool/deployment/test.py` script, the tqdm package show maskrcnn_r50_fpn's speed is only 1.3task/s. 
I wonder know is this a normal phenomenon or i make somewhere mistake.

THX for your guys looking!

**Comment by RunningLeon** [comment]
@luuuyi Hi, maskrcnn is known slow and we did not test the inference speed with TensorRT.

**Comment by jshilong** [comment]
ping@RunningLeon
