### ISSUE TITLE
Basic concepts about generating labels with FPN

### ISSUE THREAD

**Issue by NoLookDefense** [open-mmlab/mmdetection#6262]
I want to consult some basic concepts about FPN.
In network using FPN structure, "different boxes are detected by different scales based on their sizes". However, I either couldn't find the criterion which assign different boxes to different scales, nor know that whether the criterion is different in different models (like FasterRCNN, Yolo and SSD).
Could you tell me the criterion and its corresponding codes?

**Comment by hhaAndroid** [comment]
@NoLookDefense You can refer to [paper of RetinaNet](https://arxiv.org/abs/1708.02002)
