### ISSUE TITLE
retinanet_r50_fpn_1x  problem.

### ISSUE THREAD

**Issue by feixiangdekaka** [open-mmlab/mmdetection#627]
retinanet_r50_fpn_1x_20181125-3d3c2142.pth    whtn  loading the  weights   ,raise following  warning,  the  model  of   retinanet_r50_fpn_1x is not  the  same with  the  model  build  throgh  
model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)  funxtion.

unexpected key in source state_dict: bbox_head.cls_convs.0.weight, bbox_head.cls_convs.0.bias, bbox_head.cls_convs.1.weight, bbox_head.cls_convs.1.bias, bbox_head.cls_convs.2.weight, bbox_head.cls_convs.2.bias, bbox_head.cls_convs.3.weight, bbox_head.cls_convs.3.bias, bbox_head.reg_convs.0.weight, bbox_head.reg_convs.0.bias, bbox_head.reg_convs.1.weight, bbox_head.reg_convs.1.bias, bbox_head.reg_convs.2.weight, bbox_head.reg_convs.2.bias, bbox_head.reg_convs.3.weight, bbox_head.reg_convs.3.bias

missing keys in source state_dict: bbox_head.cls_convs.3.conv.weight, bbox_head.cls_convs.2.conv.weight, bbox_head.reg_convs.3.conv.bias, bbox_head.reg_convs.2.conv.weight, bbox_head.reg_convs.1.conv.bias, bbox_head.reg_convs.3.conv.weight, bbox_head.cls_convs.0.conv.bias, bbox_head.cls_convs.0.conv.weight, bbox_head.cls_convs.1.conv.weight, bbox_head.reg_convs.0.conv.weight, bbox_head.cls_convs.1.conv.bias, bbox_head.reg_convs.1.conv.weight, bbox_head.reg_convs.2.conv.bias, bbox_head.cls_convs.3.conv.bias, bbox_head.reg_convs.0.conv.bias, bbox_head.cls_convs.2.conv.bias

**Comment by yhcao6** [comment]
#629
