### ISSUE TITLE
CUDA out of memory during training YOLOX

### ISSUE THREAD

**Issue by Riser6** [open-mmlab/mmdetection#6270]
Dear open-mmlab:
     Thanks  for your wanderful work and great contribution to the computer vision community! Recently, when I used mmDetection framework to train YOLOX, the  cuda memory occupation kept rising. I feel that there may be cuda memory leakage in your code, and I hope you can solve it!

**Comment by AronLin** [comment]
We have not encountered this problem, please refer to the issue template to show the commands you run, the environment, and the error information to us.
