### ISSUE TITLE
Mosaic can't  be used without RandomAffine?

### ISSUE THREAD

**Issue by rainylt** [open-mmlab/mmdetection#6272]
I have applied Mosaic on ATSS and get a pretty score, but when I commented out the RandomAffine in train_pipeline, it decreased to half of the score before. Does it seem that RandomAffine is important for Mosaic?

Have any others performed experiments like this?

**Comment by clw5180** [comment]
> Yes, RandomAffine must be applied when using Mosaic.

Why RandomAffine must be applied when using Mosaic? I visualized the result after Resize is normal, but definitely without Random Affine the result is really bad...
