### ISSUE TITLE
Problem about my dataset in train and test?

### ISSUE THREAD

**Issue by Peterisfar** [open-mmlab/mmdetection#628]
1、train 
when i make MyDataset follow GETTING_STARTED， when run train.py , has a error about"mmdet.dataset don‘t have MyDataset", i don't know why?
2、test
then i replace the coco Classes by my data Classes  in coco.py and core/evaluation/class_names , but the result show the coco's class name not my data?

**Comment by Peterisfar** [comment]
when i pip install -e . , the problem is solved,,,,,,so ,when i change something in mmdet , just pip install -e . to upset ?

**Comment by hellock** [comment]
If the changes only apply to python codes, you do not need to run the setup each time after your modification.
