### ISSUE TITLE
Pycocotools version in workflows/build.yaml need to be clarified 

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmdetection#6287]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I got error while running the step script in `workflows/build.yaml`, and I found the version of `pycocotools` installed needs to be updated, So I suggest to clarify  `pycocotools>=2.0.2` in `workflows/build.yaml`

**Reproduction**

1. What command or script did you run?

```
python -V
          python -m pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/${{matrix.mmcv_link}}/index.html
          python -m pip install pycocotools
          python -m pip install -r requirements/tests.txt -r requirements/optional.txt
          python -m pip install albumentations>=0.3.2 --no-binary imgaug,albumentations
          python -m pip install git+https://github.com/cocodataset/panopticapi.git
          python -c 'import mmcv; print(mmcv.__version__)'
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@del-zhenwu Thank you for your feedback, can you create a PR to fix it?
