### ISSUE TITLE
export onnx with '--simplify', No such file '' 

### ISSUE THREAD

**Issue by BChunlei** [open-mmlab/mmdetection#6303]
When I export faster-rcnn model by the following command:

python tools/deployment/pytorch2onnx.py configs/_my_config/my_faster_rcnn_r50_config_dianlan.py work_dirs/my_faster_rcnn_r50_config_dianlan/best_bbox_mAP_epoch_16.pth --output-file faster_dianlan.onnx --shape 800 800 --simplify

it shows me the error:
No such file ''

When the '--simplify' is removed, it's ok.

**Comment by BChunlei** [comment]
no more messages. Actually, it can export onnx model, but it print 'No such file ''' message, instead of successful message.
![image](https://user-images.githubusercontent.com/44046955/138022626-7e032296-d464-4f49-9b27-c5bbaf77d357.png)

**Comment by RunningLeon** [comment]
@BChunlei Could debug and locate which line of code is printing this message?
