### ISSUE TITLE
Print bounding boxes during visualization

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#6309]
I am trying to print out the visualized bounding boxes. I am testing some images and below is the test result for a single image:
![image](https://user-images.githubusercontent.com/9031472/137759644-e08c718d-0508-4ff8-b71a-d80a524cb57f.png)
As shown in the result there are 8 bounding boxes ( 7 person and 1 car ), how do I print these boxes manually. I tried to print them at: 
https://github.com/open-mmlab/mmdetection/blob/a32d7d40bfe2277f255bf71911a27a76ff871eb2/mmdet/models/roi_heads/standard_roi_head.py#L254
But I get large number of bounding boxes ( 40 for car and 46 for person) as shown from eval mAP:
![image](https://user-images.githubusercontent.com/9031472/137760661-33fc848c-9c37-464c-aa6b-780caf643b49.png)
And these are the result when I print them out:
![image](https://user-images.githubusercontent.com/9031472/137760801-fc5b8b4c-b0dc-434c-bbe1-2bc7d7c43025.png)
What could be the issue? Why is the no of bounding boxes different in visulaization and evaluation? Is it possible to pass only the bounding boxes that are being visualized to the evaluation. Because during evaluation large no of bounding boxes are considered and hence the mAP is also very low.

**Comment by hhaAndroid** [comment]
@Soodep https://github.com/open-mmlab/mmdetection/issues/6185

**Comment by Soodep** [comment]
@hhaAndroid I printed the bounding box during visualization and during evaluation:
For evaluation: as shown above
For visualization:  https://github.com/open-mmlab/mmdetection/blob/a32d7d40bfe2277f255bf71911a27a76ff871eb2/mmdet/core/visualization/image.py#L135
I printed the bbox from the above line and got this result:
![Screenshot from 2021-10-19 09-41-21](https://user-images.githubusercontent.com/9031472/137933601-45a41d4f-f1d2-40c7-989b-bf1d717abc27.png)
The Det_bbox_result is from the print statement at line : https://github.com/open-mmlab/mmdetection/blob/a32d7d40bfe2277f255bf71911a27a76ff871eb2/mmdet/models/roi_heads/standard_roi_head.py#L256


and Bounding Boxes Image.py is from the print statement at line: https://github.com/open-mmlab/mmdetection/blob/a32d7d40bfe2277f255bf71911a27a76ff871eb2/mmdet/core/visualization/image.py#L135

The problem I am having is as you can see in the det_bbox_result there are random bounding boxes of a same value ( inside the array)  [0.        , 0.        , 0.        , 0.        , 0.14193098], is repeated multiple time although during visulization this bounding box is not shown and another array [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.13929905e-01] is also repeated multiple time as you can see in the picture. What could be the issue behind this?

**Comment by hhaAndroid** [comment]
@Soodep It can be removed by score_thr.
