### ISSUE TITLE
How to use MultiScaleFlipAug on TorchServe 

### ISSUE THREAD

**Issue by oggreo** [open-mmlab/mmdetection#6310]
Hello! 

I wanted to use MultiScaleFlipAug on model served using TorchServe. What is the best way to do this ?

I looked at the code for MultiScaleFlipAug, but it wasn't clear how this could be used in the context of torchserve...

Thanks!

**Comment by hhaAndroid** [comment]
@reo911gt3 I’m not very familiar with it, but I think you can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/useful_tools.md#1-convert-model-from-mmdetection-to-torchserve, and then change CONFIG_FILE to a Multi-scale version. I guess I don’t need to do anything except modify the configuration file.
