### ISSUE TITLE
哪里可以看见基于AMD显卡的安装支持文档

### ISSUE THREAD

**Issue by JayFu** [open-mmlab/mmdetection#6311]
我搜到 [mmcv的issue](https://github.com/open-mmlab/mmcv/issues/1394)和一个PR，看见有人完成了基于AMD显卡的编译安装，想请问现在基于AMD的mmdetection是否可用以及官方有提供针对AMD的安装文件和文档吗？

**Comment by hhaAndroid** [comment]
@JayFu MMDET should not need to be modified but I suggest you go to MMCV to create an issue.
