### ISSUE TITLE
Whats the 'time' and 'data_time' mean?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6312]
![pic](https://user-images.githubusercontent.com/86214036/137838315-2069384b-da54-4b17-9ee7-1a24bd0f1d3d.jpg)
Helllo! I want to know about whats the **'time'**  and **'data_time'** mean  in  the picture? 
By the way, I want to know  how to get the **'fps '**?
Thanks!

**Comment by HarborYuan** [comment]
Sorry for the ambiguity in the previous description.

L51 means the 51st line in the link.

**Comment by HarborYuan** [comment]
Sorry, I am not familiar with that.

**Comment by AronLin** [comment]
#6323 answered this question.
