### ISSUE TITLE
error in tools/test.py

### ISSUE THREAD

**Issue by Chop1** [open-mmlab/mmdetection#6318]
In tools/test.py, when using the --show-dir option, their is an error in mmdet/apis/test.py.

line 49, img_meta['ori_filename'] is an invalide key.

A workaround:

```python
                if out_dir:
                    #out_file = osp.join(out_dir, img_meta['ori_filename'])
                    out_file = osp.join(out_dir, img_metas[0]["filename"].split("/")[-1])
```

**Comment by hhaAndroid** [comment]
@Chop1 I have confirmed that this key exists.
