### ISSUE TITLE
help! anyone could tell me where is the data-train-flip func in mmdet?thanks!

### ISSUE THREAD

**Issue by Peterisfar** [open-mmlab/mmdetection#632]

**Comment by Peterisfar** [comment]
![image](https://user-images.githubusercontent.com/31852119/57583579-42a5ec80-7504-11e9-98a4-b9f5c1fd56ab.png)
filp_ration 0. and 1. ,which is to support filp_ration

**Comment by hellock** [comment]
During training, `flip_ratio` means the ratio of flipping, and 0.5 is used by default.

**Comment by Peterisfar** [comment]
> During training, `flip_ratio` means the ratio of flipping, and 0.5 is used by default.

thank you very much! could you tell me where  is the code about it in mmdet/?
