### ISSUE TITLE
How to set random seed and deterministic=True in the config file?

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6322]
Hi, 

I would like to make the training of a model reproducible. Looking at

https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py

the relevant arguments seem to be  `--seed` and  `--deterministic`. Do I need to set both of them to make the training reproducible? How do I set them in the config file?

**Comment by AronLin** [comment]
In the latest version of mmdet, you can only set them through args, we no longer support setting them in config file. 
https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L155 shows that the `seed` will be covered by args.seed.
