### ISSUE TITLE
Is mmdetection prediction on CPU possible??

### ISSUE THREAD

**Issue by apanand14** [open-mmlab/mmdetection#6328]
Hello,

In mmdetection, tools/test.py uses single_gpu_test and multi_gpu_test for the prediction. I would like to do it on CPU only. Is it possibe to use CPU for test.py for mmdetection prediction? 

Thank you in advance for your answer!

**Comment by AronLin** [comment]
Yes, you can use PyTorch-CPU and re-build mmcv with CPU if you want to use the ops in mmcv.
We did not deliberately go to be compatible with the CPU, but theoretically, it can be tested with the CPU.
