### ISSUE TITLE
labels_ignore error

### ISSUE THREAD

**Issue by Noone65536** [open-mmlab/mmdetection#633]
I train on my own dataset with 11 classes. The training process goes well but when it comes to test it shows 
Traceback (most recent call last):
  File "./tools/train.py", line 97, in <module>
    main()
  File "./tools/train.py", line 93, in main
    logger=logger)
  File "/home/z/object_detection/HRNet-Object-Detection/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/z/object_detection/HRNet-Object-Detection/mmdet/apis/train.py", line 96, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/z/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 355, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/z/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_epoch')
  File "/home/z/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 228, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/z/object_detection/HRNet-Object-Detection/mmdet/core/evaluation/eval_hooks.py", line 94, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/z/object_detection/HRNet-Object-Detection/mmdet/core/evaluation/eval_hooks.py", line 123, in evaluate
    labels = np.concatenate([labels, ann['labels_ignore']])
KeyError: 'labels_ignore'
I changed my dataset into Coco format.

**Comment by Noone65536** [comment]
Is it the problem of my dataset? There seems no term named label_ignore in my dataset's ann. Could you help me with this error? Thx

**Comment by hellock** [comment]
If you want to use COCO-style evaluation, you need to inherit from `CocoDataset` as illustrated in [GETTING_STARTED](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#use-my-own-datasets).

**Comment by Noone65536** [comment]
> If you want to use COCO-style evaluation, you need to inherit from `CocoDataset` as illustrated in [GETTING_STARTED](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#use-my-own-datasets).

I have inherited from CocoDataset and modified my config file as illustrated in GETTING_STARTED in mmdet/datasets/. Do you mean that I need to do the same thing in mmdet/core/evaluation ?

**Comment by lucaskingjade** [comment]
> > If you want to use COCO-style evaluation, you need to inherit from `CocoDataset` as illustrated in [GETTING_STARTED](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#use-my-own-datasets).
> 
> I have inherited from CocoDataset and modified my config file as illustrated in GETTING_STARTED in mmdet/datasets/. Do you mean that I need to do the same thing in mmdet/core/evaluation ?
It seems that your program is using DistEvalmAPHook rather than  CocoDistEvalmAPHook as an evaluation hook.
I guess your own dataset class doesn't inherit from 'CocoDataset', so "DistEvalmAPHook' is used in your program. 
Your own dataset class should be like as follows:
class YourownDataset(CocoDataset):
.....

**Comment by lucaskingjade** [comment]
> > If you want to use COCO-style evaluation, you need to inherit from `CocoDataset` as illustrated in [GETTING_STARTED](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#use-my-own-datasets).
> 
> I have inherited from CocoDataset and modified my config file as illustrated in GETTING_STARTED in mmdet/datasets/. Do you mean that I need to do the same thing in mmdet/core/evaluation ?

I guess your own dataset class doesn't inherit from 'CocoDataset', so "DistEvalmAPHook' is used in your program.
Your own dataset class should be like as follows:
class YourownDataset(CocoDataset):
.....

**Comment by xiaozhuka** [comment]
I modified three places to fit my data set with coco format.
1. Create a new DataSet in mmdet/datasets/widerped.py

from .coco import CocoDataset
class WiderpedDataset(CocoDataset):

    CLASSES = ('person')

2. add `WiderpedDataset` in mmdet/datasets/__init__.py
from .widerped import WiderpedDataset
__all__ = [
    'CustomDataset', 'XMLDataset', 'CocoDataset', 'VOCDataset', 'GroupSampler',
    'DistributedGroupSampler', 'build_dataloader', 'to_tensor', 'random_scale',
    'show_ann', 'get_dataset', 'ConcatDataset', 'RepeatDataset', 'ZipDataset',
    'ExtraAugmentation', 'CocoZipDataset', 'WiderpedDataset'
]

3. add jugement in mmdet/apis/train.py
if cfg.data.val.type == 'CocoDataset' or \
               cfg.data.val.type == 'CocoZipDataset' or \
               cfg.data.val.type == 'WiderpedDataset':
                print('register hook CocoDist Eval mAP Hook for {}'.format(cfg.data.val.type))
                runner.register_hook(CocoDistEvalmAPHook(cfg.data.val))

**Comment by changqinyao** [comment]
I have the same problem, Did you solve it？

**Comment by hellock** [comment]
Seems outdated.
