### ISSUE TITLE
What is MemcachedBackend config Look like?

### ISSUE THREAD

**Issue by tuochi** [open-mmlab/mmdetection#6332]
Hi! I'd like to ask the problem about using memcached as backend . I install memcached by using its office document, but i can't find the files named 'server_list_cfg' or 'client_cfg'. What tool memcached client you used? Could you give me an example about "server_list_cfg","client_cfg" and "sys_path"in your spare time?Thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by RangiLyu** [comment]
This problem is related to MMCV. Please open another issue in MMCV.
