### ISSUE TITLE
The flops and parameters of NASFPN is not matched

### ISSUE THREAD

**Issue by lucienne999** [open-mmlab/mmdetection#6336]
Hi, table.1  in [1] show that  NAS-FPN R-50 (7 @ 256)  FLops and parameters is  **281.3B , 60.3 M**.  However, I use `get_flops.py` to get **140.42 GF** and **68.02M** when using NasFPN config.
 

Refer:
[1] https://arxiv.org/pdf/1904.07392.pdf

**Comment by LicharYuan** [comment]
@RangiLyu  Thanks for your reply. But how to explain the difference in parameters?
