### ISSUE TITLE
About train subclass

### ISSUE THREAD

**Issue by vickyyd** [open-mmlab/mmdetection#6348]
Hi, if i want to train subclass. Except change ./config, should i change ./mmdet/core/evalution/class_name.py and ./mmdet/datassets/voc.py?
For example, my dataset have changed to voc format and it have 'apple' 'orange' two classes. I want to train 'apple' one class. In voc.py, it should be CLASSES = ('apple', 'banana') or CLASSES = ('apple')? And in class_name.py, it should be return ['apple', 'banana'] or return ['apple']. 
Thank you.

**Comment by BIGWangYuDong** [comment]
Maybe due to the VOC hardcode in mmdet. Then you can try to change the CLASSES in the VOC dataset
