### ISSUE TITLE
CVPR code release

### ISSUE THREAD

**Issue by zxpeter** [open-mmlab/mmdetection#635]
Hi,
When will the code of 'Libra R-CNN' and 'Region Proposal by Guided Anchoring' be released?

**Comment by hellock** [comment]
They are already in the PRs.

**Comment by nemonameless** [comment]
@hellock Will you release the results of cascade-libra or cascade-garpn ? 
Just follow the common cascade_rcnn_r50_fpn_1x.py? I mean if it is needed to change the hyper-parameter or parameter? Thanks

**Comment by runzeer** [comment]
Thanks for your excellent work! But when I try to add the GA-RPN into cascade RCNN network, the performance is even worse. So,if convenient,could you share the results about the Cascade RCNN with GA-RPN?
