### ISSUE TITLE
Deformable ROI and Deformable Attention TensorRT plugin

### ISSUE THREAD

**Issue by fduxvtech** [open-mmlab/mmdetection#6350]
Hello, 

Thanks for the incredible work; 
I'm interested in using deformable Roi and deformable Attention in tensorrt; I have interest in porting everything in c++, do your framework support it? 
Where should I start to implement the plugins? any resources will be extremely beneficial since I can't find much online

**Comment by BIGWangYuDong** [comment]
Hi maybe you can find these in [`MMCV`](https://github.com/open-mmlab/mmcv/tree/master/mmcv/ops)

**Comment by fduxvtech** [comment]
Hello again, I wrote the plugin but I'm stuck in the `enqueue` function, cause I don't know how to handle the batch size, in fact it seems that all tensorrt input needs the batch dimensions but some input in deformable attention doesn't have it. Is it possible to have an exchange with the person that is writing the TensorRT plugins?

**Comment by BIGWangYuDong** [comment]
Please @RunningLeon take a look at this issue.

**Comment by RunningLeon** [comment]
@grimoire Hi, since you have replied in another issue, could you connect the two issues together?
