### ISSUE TITLE
Customized backbone model

### ISSUE THREAD

**Issue by AmanGoyal99** [open-mmlab/mmdetection#6355]
Greetings, 

I want to use a customized backbone model. Now, I had already viewed the instructions mentioned in your GitHub repo about it. I had a couple of queries 

1) If I want to add such a customized backbone model, would I need to then clone your github repo and build it or can I do pip installation as well?
2) In the config, is it necessary to mention parameters such as depth, style etc other than 'type' or just this is also sufficient ?

**Comment by ZwwWayne** [comment]
Yes, you should.
