### ISSUE TITLE
How to test with the original image scale?

### ISSUE THREAD

**Issue by bruceyang2012** [open-mmlab/mmdetection#636]
I used random cropping in the training, so I wanted to test with the original scale of the image. Where should I change the code?

**Comment by hellock** [comment]
You can modify any behavior [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L266).

**Comment by bruceyang2012** [comment]
@hellock Thank you. I solve the problem.
