### ISSUE TITLE
自定义数据集

### ISSUE THREAD

**Issue by fhf526** [open-mmlab/mmdetection#6364]
自定义数据集，按照教程中自定义数据集的例子，在mmdet/datasets/my_dataset.py中创建一个新的 dataset 用以加载数据。然后在mmdet/datasets/__init__.py进行添加自己的数据集，然后运行的时候报错 KeyError: 'MyDataset is not in the dataset registry'
想问一下这是什么问题，谢谢！

**Comment by jshilong** [comment]
It should be the path of mmdet that you modified. You can check it.

**Comment by fdhyhtt** [comment]
> Please make sure you use the modified mmdet instead of the mmdet in your environment

how to use the modified mmdet
