### ISSUE TITLE
Upsample error

### ISSUE THREAD

**Issue by Boyden** [open-mmlab/mmdetection#6371]
https://github.com/open-mmlab/mmdetection/blob/d145b0eab083eb6f2004ca37d704536cec882d16/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py#L124
The upsample cfg in the FCNMaskHead supports the bilinear and nearest upsample type. However, in the L124, using bilinear or nearest upsample methods will cause the error `AttributeError: 'Upsample' object has no attribute 'weight'` due to no weight in the torch.nn.Upsample object.

**Comment by RangiLyu** [comment]
Fixed in #6378
