### ISSUE TITLE
About testing YOLOX model's FPS

### ISSUE THREAD

**Issue by sanmulab** [open-mmlab/mmdetection#6373]
作者你好！就是我用yolox训练模型，还没训练完，我用benchmark.py脚本测试模型的速度，发现只有35-40FPS左右，论文里不是有90FPS吗？还是说这个benchmark.py测试的FPS包括前向和后向推理，我应该乘以2吗？最后一个问题是，因为一些原因训练中断了，我用resume-from指令恢复训练，这样做有没有可能会影响模型AP指标。

**Comment by wywywy01** [comment]
去除get box，我在这个函数直接返回，类似于去掉后处理步骤，在yolox tiny上，减少2.5ms的时间；
![image](https://user-images.githubusercontent.com/22450352/147041298-5002029e-4218-489a-b512-bdab6bd7577f.png)

mmdet/models/dense_heads/yolox_head.py

另外，我自己测试速度 yolox tiny的速度，在3090上，速度如下，感觉很慢。去掉后处理，和不去掉后处理分别是  60fps和52fps
![image](https://user-images.githubusercontent.com/22450352/147041386-447e7281-659e-4d8e-b6f5-9ab92c077f50.png)

**Comment by sanmulab** [comment]
> 去除get box，我在这个函数直接返回，类似于去掉后处理步骤，在yolox tiny上，减少2.5ms的时间； ![image](https://user-images.githubusercontent.com/22450352/147041298-5002029e-4218-489a-b512-bdab6bd7577f.png)
> 
> mmdet/models/dense_heads/yolox_head.py
> 
> 另外，我自己测试速度 yolox tiny的速度，在3090上，速度如下，感觉很慢。去掉后处理，和不去掉后处理分别是 60fps和52fps ![image](https://user-images.githubusercontent.com/22450352/147041386-447e7281-659e-4d8e-b6f5-9ab92c077f50.png)

操作就是把参数下面的代码注释掉，然后返回一个空数组是吗

**Comment by sanmulab** [comment]
> 去除get box，我在这个函数直接返回，类似于去掉后处理步骤，在yolox tiny上，减少2.5ms的时间； ![image](https://user-images.githubusercontent.com/22450352/147041298-5002029e-4218-489a-b512-bdab6bd7577f.png)
> 
> mmdet/models/dense_heads/yolox_head.py
> 
> 另外，我自己测试速度 yolox tiny的速度，在3090上，速度如下，感觉很慢。去掉后处理，和不去掉后处理分别是 60fps和52fps ![image](https://user-images.githubusercontent.com/22450352/147041386-447e7281-659e-4d8e-b6f5-9ab92c077f50.png)

操作就是把参数下面的代码注释掉，然后返回一个空数组是吗，还是直接在那一行加入retrun []

**Comment by wywywy01** [comment]
我是这么做的，后处理部分基本就是减少2~3ms左右；
在论文原来的repo里面，也验证了这一点；

**Comment by sanmulab** [comment]
明白了，谢谢

> 我是这么做的，后处理部分基本就是减少2~3ms左右； 在论文原来的repo里面，也验证了这一点；

**Comment by y72428026** [comment]
In the YOLOX paper, models are tested on V100 GPU. Different gpus may effect the testing fps?
