### ISSUE TITLE
IndexError :list index out of range

### ISSUE THREAD

**Issue by Super-chen-big** [open-mmlab/mmdetection#6377]
![QQ图片20211026181433](https://user-images.githubusercontent.com/65719285/138859957-b87388c3-d584-4d1a-8e63-c244fd0083b5.png)
The data model I use is mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
He may report this error before starting the second training after saving the first epoch, or before starting the fourth training or before the eighth training.

**Comment by cfllsbb** [comment]
When I used the VOC format data set for training, this problem also occurred. The data set has 16,000 images. The model reported this error after completing an epoch.
![image](https://user-images.githubusercontent.com/48855043/139532417-caa7ce61-0987-42d7-9a8f-c52fc21580bf.png)

**Comment by hhaAndroid** [comment]
@cfllsbb Please update to the latest version, it may have been fixed.
