### ISSUE TITLE
when i add a specific layer, some error happed!

### ISSUE THREAD

**Issue by searchliu333** [open-mmlab/mmdetection#638]
when i add a block in mmdetection/mmdet/models/necks/fpn.py, i got an error:
        RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
       i know something about this. when data flow enter my block , the data flow is gpu_data, but my block parameters is cpu_data. i try adding my block into original network. i failed,  anyone can help me? thank you very much

**Comment by hellock** [comment]
It seems you have already figured it out. You just need to use cuda tensors.

**Comment by searchliu333** [comment]
> It seems you have already figured it out. You just need to use cuda tensors.
Thank you for your reply,  it  worked.

**Comment by ujsyehao** [comment]
@searchliu333 Can you tell me how to solve the problem?

**Comment by ujsyehao** [comment]
I forget to add `self.extra_convs = nn.Sequential(*self.extra_convs)`

**Comment by GingerCohle** [comment]
> I forget to add `self.extra_convs = nn.Sequential(*self.extra_convs)`

![image](https://user-images.githubusercontent.com/37873318/89288586-7a103400-d688-11ea-8fe0-ecb0c992972d.png)
add your layer here and us it in forward
