### ISSUE TITLE
YOLO v3 loss

### ISSUE THREAD

**Issue by jewelc92** [open-mmlab/mmdetection#6400]
I found that in all the configs of yolov3，the parameter 'reduction' of loss is set to 'sum'，and this only exits in yolov3's config files. The final box AP of yolo v3 model that you provide are normal, but in the log, the final losses are so big that larger than 200. I want to know why this paramter 'reduction' is set to 'sum' only in yolov3?  Does this paramter make any difference to the training result?

**Comment by AbdelazizHamadi** [comment]
Hey @jewelc92, I'm currently doing a comparative study between models with my own dataset with this framework SSD and Faster RCNN worked fine except for yolov3, where loss_cls, oss_conf,  loss_xy are so freaking high, tried too see where is the problem but nothing worked for me, have u found the solution for this problem ?
