### ISSUE TITLE
change LR and use resume-from checkpoint

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6402]
Is there a trick/workaround in order to change the LR and then use `--resume`-checkpoint  ?

at the moment, the old LR from the checkpoint overwrites the new LR :(

(I know I could use `load_from` but this would imply loosing the number of epoch info which I want to avoid )

**Comment by BIGWangYuDong** [comment]
You can pre-process your ckpt, which means you can use a script to process your ckpt, and then use **resume** to run the code.

**Comment by joihn** [comment]
Will try this, thanks
