### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

### ISSUE THREAD

**Issue by tan-june** [open-mmlab/mmdetection#6404]
Hi, 

I'm receiving the following error while running my code:

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

Not sure what occurred as it was working fine a few days ago. Please let me know a fix for this.

-TS

**Comment by LeungWaiHo** [comment]
Do you solve this problem? Once upon a time, I shut down my computer before incompletely killing all processes, and this problem occurred.
