### ISSUE TITLE
Self-pretrained backbone

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6407]
I'm pretraining my own backbone via MMclassification, then using it in  MMdetection.

After the training in MMclassification, I export via 2 methods :

**a)** I save both the whole net (backbone + classifier ) via the nomal checkpoint hook (which will output `epoch_x.pth`)
**b)**or I manually save the naked backbone via 
`torch.save(model.module.backbone.state_dict(), "output/naked_backbone.pth")`

And then I can use it in MMdetection via:
`init_cfg=dict(type='Pretrained', checkpoint='output/naked_backbone.pth')`

Both these methods a) b)  seems to work, which seems weird to me. Am I doing things correctly ?

**Comment by BIGWangYuDong** [comment]
This seems OK, you can check your log file, which can find whether your ckpt load successfully, and what parameters do not use.
