### ISSUE TITLE
How to adopt Guided Anchoring in Fast R-CNN?

### ISSUE THREAD

**Issue by randf102** [open-mmlab/mmdetection#641]
Thank you for sharing such an amazing model. I successfully trained Faster R-CNN with own dataset in less training time. And I got good results.

I am confused about how to adopt Guided Anchoring in Fast R-CNN. I mean, in Faster R-CNN we will set a lot of fixed anchor boxes. But in Fast R-CNN we use selective search to get our proposals. And we did not use anchor boxes in Fast R-CNN. So, I don't know how to use Guided Anchoring in Fast R-CNN to improve mAP.

Could anyone help me, please? Not sure if it is suitable for asking here. If not, please let me know. I will close this issue.

Thanks!

**Comment by myownskyW7** [comment]
1) You may train a GA-RPN model on your own dataset and extract the proposals. 
2) You need to change the proposal_file parameter in the GA-FastRCNN config to your proposal file. 
3) Train this GA-FastRCNN config.
The performance gain comes from high-quality proposals provided by GA-RPN

**Comment by randf102** [comment]
I see. Thank you for your kind reply.
I will try to train GA-FastRCNN followed by your instructions.
