### ISSUE TITLE
Change MMSyncBN to BN when inference images?

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmdetection#6410]
Hi,
After I trained my own model, I use demo/image_demo.py to show result. 
When I use MMSyncBN, I got the following error:
`AssertionError: Default process group is not initialized`
So, I change MMSyncBN  to BN in my config. Then I can get inference result.
But, I have a question about performance. If the output result is different when I change MMSyncBN  to BN when inference.
Thanks for your reply!

**Comment by hhaAndroid** [comment]
@Senwang98 Please use the issue template. Synchronous BN can be directly used for GPU inference.
