### ISSUE TITLE
labelImg VOC Conversion tool

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#6412]
├── annotations
│ ├── xxx1.xml
│ ├── xxx2.xml
│ ├── xxx3.xml
│ | ...
├── images
│ ├── xxx1.jpg
│ ├── xxx2.jpg
│ ├── xxx3.jpg

我是用labelImg标注的
数据集是这种格式
OpenMMLab并没有提供这样的 转换工具  
希望官方能提供转换脚本
感谢

I marked it with labelimg
Data sets are in this format
Openmmlab does not provide such a conversion tool
I hope the official can provide the conversion script
thank

**Comment by RangiLyu** [comment]
You can directly use `XMLDataset`. Just set
```
img_subdir='images',
ann_subdir='annotations',
```
