### ISSUE TITLE
The detr model trains own dataset, ap is all 0

### ISSUE THREAD

**Issue by cfllsbb** [open-mmlab/mmdetection#6413]
![image](https://user-images.githubusercontent.com/48855043/139533168-0453c57d-d507-4266-989c-557fdc186697.png)

**Comment by OneBella** [comment]
I have the same problem as you, is config not set correctly？

**Comment by RangiLyu** [comment]
What did you modify in the config? How many GPUs did you use for training? Please follow the issue template to provide more details.

**Comment by OneBella** [comment]
> What did you modify in the config? How many GPUs did you use for training? Please follow the issue template to provide more details.

File coco_detection and the data settings have been used before. There should be no problem. DERT's config only modifies num_classes, which can be run but mAP is always 0.

**Comment by RangiLyu** [comment]
DERT is hard to train. The hyperparams in the config are based on 8GPUs. If your batch size is different, please modify them to a suitable setting.

**Comment by THEBEST-cloud** [comment]
Has this problem been solved for AP?

**Comment by sfx6635** [comment]
Has the problem been solved？
