### ISSUE TITLE
[TIPS/ADVICE] How to combat overfitting in mmdetection framework?

### ISSUE THREAD

**Issue by neel04** [open-mmlab/mmdetection#6414]
Hey, authors - really really grateful for such a flexible framework!

in #6359 I had a doubt whether my model might be overfitting due to low confidence scores 🤔 

Can you guys provide an exhaustive list of all the fixes one can take to combat overfitting in this framework, the tips and tricks to build a better detection model? I believe this can be very helpful to beginners 👍 

Thanks again! 🤗

**Comment by AndreaPi** [comment]
A tip which I found _essential_, so much that I never train a model without including it in the config file, is to include Albumentations transforms in the training pipeline. This requires a bit of work:

1.  install `albumentations` with
```python
pip install albumentations>=0.3.2 --no-binary imgaug,albumentations
``` 
see also https://mmdetection.readthedocs.io/en/latest/get_started.html#install-mmdetection.
2. learn about pipelines https://mmdetection.readthedocs.io/en/latest/get_started.html#install-mmdetection
3. define a list of albumentations transforms in your config file, e.g.
```python
albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]
```
4. call `albu_train_transform` in your training pipeline (**not** in the test pipeline), e.g.
```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=image_scale, keep_ratio=True),
    dict(type='Pad', size_divisor=32),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_masks': 'masks',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'],
        meta_keys=('filename', 'ori_shape', 'img_shape', 'img_norm_cfg',
                   'pad_shape', 'scale_factor'))
]
```

**Note** that even if you're training on a dataset of type `COCODataset`, for some reasons you still have to specify             `format='pascal_voc'` in the training pipeline, see https://github.com/open-mmlab/mmdetection/issues/6126#issuecomment-922228046

Hope this helps!

**Comment by GeorgePearse** [comment]
HI @AndreaPi would you still recommend this at MMDet 3.0 ? Or have the augmentations you used to use from albumentations now been implemented?

**Comment by pedrozamboni** [comment]
Hey, I got this error while using Alblumentation - 
ValueError: Key img_info is not in available keys.

**Comment by GeorgePearse** [comment]
Hey @pedrozamboni might be an albumentations version error, I've hit that before, think the one you need is 1.13.8 if I remember rightly, but it's in another issue
