### ISSUE TITLE
test_robustness.py:310 osp.makedirs error

### ISSUE THREAD

**Issue by gracciechou** [open-mmlab/mmdetection#6415]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
In line 310 of the test_robustness.py file, osp.makedirs(show_dir) is used incorrectly.
**Reproduction**

1. What command or script did you run?

```
python tools/analysis_tools/test_robustness.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --show-dir results/ --eval bbox --summaries True
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
COCO

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
![image](https://user-images.githubusercontent.com/37568145/139569769-61730d73-428f-4b2c-860c-a87ee48cc78f.png)

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
Traceback (most recent call last):
  File "tools/analysis_tools/test_robustness.py", line 391, in <module>
    main()
  File "tools/analysis_tools/test_robustness.py", line 310, in main
    osp.makedirs(show_dir)
AttributeError: module 'posixpath' has no attribute 'makedirs'

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

change osp.makedirs to os.makedirs(show_dir)

**Comment by hhaAndroid** [comment]
@gracciechou It seems that there is a problem with the os.path library, you can go to confirm.
