### ISSUE TITLE
About the metrics

### ISSUE THREAD

**Issue by Banhkun** [open-mmlab/mmdetection#6417]
Hi, thanks for your work!!!
As I know the **voc07** and **voc12** donate different metrics. 
Do you support both of them?
If so how can I evaluate in voc07 and voc12 metrics separately?.
Cause the test script only have 2 options **mAP** and **recall**.
![image](https://user-images.githubusercontent.com/83081141/139592502-2a54962b-3a75-44f3-aa2d-a72a9b4d8681.png)

**Comment by hhaAndroid** [comment]
@Banhkun 

![image](https://user-images.githubusercontent.com/17425982/140720532-69f7d227-69a8-4aa8-830c-5cb53e9b45c2.png)

The code will be automatically distinguished according to the img_prefix, you can achieve your needs through this field
