### ISSUE TITLE
How to update only certain modules every n iterations?

### ISSUE THREAD

**Issue by vombategeht** [open-mmlab/mmdetection#6418]
Massive gratitude for you guys' hard work maintaining the quality project!

I'm trying to implement class-agnostic object detector[WACV, 2021] with mmdetection. I'm working on setting the model training schedule by **iterating between five discriminator updates for each update to the other modules.** (The discriminator here is simply a fc head that performs class-specific classification)
 
![스크린샷, 2021-11-01 10-59-38](https://user-images.githubusercontent.com/57431963/139611313-24f9bd3b-ed69-4bf2-b0a4-16f2798c7a06.png)

I've changed the codes in mmdet>models>detecotrs>base.py>_parse_losses to subtract the discriminator loss from the other ones. However, I'm kinda lost where I should change to set model to take different losses to get updated every n iterations.

Do you guys have any ideas with this?

**Comment by jshilong** [comment]
There may be much modification
you need set iteration numbers to model in runner
https://github.com/open-mmlab/mmcv/blob/f9be3bc3336f00138b876de002477864810c5b29/mmcv/runner/epoch_based_runner.py#L50
then adopt corresponding loss every k iters

**Comment by vombategeht** [comment]
Thanks a lot!
