### ISSUE TITLE
mim install mmdet,   where the project is installed

### ISSUE THREAD

**Issue by cena001plus** [open-mmlab/mmdetection#6420]
Thank you for your contributions. The way I install mmdetection is the way you recommend, which is "mim install mmdet", but I don't know where the project is installed?

**Comment by RangiLyu** [comment]
mim installs mmdetection as a python package. Just run `pip show mmdet`, and you'll get:
```
Name: mmdet
Version: 2.17.0
Summary: OpenMMLab Detection Toolbox and Benchmark
Home-page: https://github.com/open-mmlab/mmdetection
Author: MMDetection Contributors
Author-email: openmmlab@gmail.com
License: Apache License 2.0
Location: /home/USER/anaconda3/envs/openmmlab/lib/python3.8/site-packages
Requires: numpy, matplotlib, six, pycocotools, terminaltables
Required-by: 
```
And you'll find its path in `Location`

**Comment by cena001plus** [comment]
> mim installs mmdetection as a python package. Just run `pip show mmdet`, and you'll get:
> 
> ```
> Name: mmdet
> Version: 2.17.0
> Summary: OpenMMLab Detection Toolbox and Benchmark
> Home-page: https://github.com/open-mmlab/mmdetection
> Author: MMDetection Contributors
> Author-email: openmmlab@gmail.com
> License: Apache License 2.0
> Location: /home/USER/anaconda3/envs/openmmlab/lib/python3.8/site-packages
> Requires: numpy, matplotlib, six, pycocotools, terminaltables
> Required-by: 
> ```
> 
> And you'll find its path in `Location`

ok

**Comment by cena001plus** [comment]
> > mim installs mmdetection as a python package. Just run `pip show mmdet`, and you'll get:
> > ```
> > Name: mmdet
> > Version: 2.17.0
> > Summary: OpenMMLab Detection Toolbox and Benchmark
> > Home-page: https://github.com/open-mmlab/mmdetection
> > Author: MMDetection Contributors
> > Author-email: openmmlab@gmail.com
> > License: Apache License 2.0
> > Location: /home/USER/anaconda3/envs/openmmlab/lib/python3.8/site-packages
> > Requires: numpy, matplotlib, six, pycocotools, terminaltables
> > Required-by: 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And you'll find its path in `Location`
> 
> ok
