### ISSUE TITLE
gcc error

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#6423]
When I execute the training file, the result is an error: modulenotfounderror: no module named 'mmcv', but I have been able to run normally before, and mmcv full exists in my environment. Then I recompile mmdet, and the result is the following error

**gcc: error: pycocotools/_mask.c: 没有那个文件或目录
gcc: fatal error: no input files
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1**

Because I am not the only one using the server, I don't know if someone else has changed the system settings, resulting in problems in my mmdet environment

**Comment by jshilong** [comment]
What is your mmdet version

**Comment by chensen668** [comment]
I don't think it's the version problems. I have an environment with mmdet = 2.3.0 and mmdet = 2.16. I can still use it normally yesterday, but not today. In addition, when I train with a single card, I report an error:modulenotfounderror: no module named 'mmcv', but when I train with multiple GPUs, I have no problem and can train normally.Why?

**Comment by XYX1998** [comment]
你好，请问你是怎么解决的
