### ISSUE TITLE
A question about plugins ?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6428]
Hello! I want to insert "context_block" into the backbone Resnet, and the position ="after_conv2". Is the structure like that :
![image](https://user-images.githubusercontent.com/86214036/139813955-9891f66c-ec5c-4fa7-a59a-8d07ef3b55ab.png)

**Comment by hhaAndroid** [comment]
@lijoe123  It is like this:
```python
plugins=[
            dict(
                cfg=dict(
                    type='GeneralizedAttention',
                    spatial_range=-1,
                    num_heads=8,
                    attention_type='1111',
                    kv_stride=2),
                stages=(False, False, True, True),
                position='after_conv2')
        ]
```
You can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/empirical_attention/faster_rcnn_r50_fpn_attention_0010_1x_coco.py

**Comment by lijoe123** [comment]
Thank you for your answer. I know how to use the code.  But i just want to know the struture about "context_block" plug in the postion: "after_conv2" of the resnet. Is it like the image ?
![image](https://user-images.githubusercontent.com/86214036/139845627-fe25c50a-cd18-4e7a-b6f2-b757b39b87af.png)
