### ISSUE TITLE
QueryInst model link is invalid > > > > Hi @vealocia ,

### ISSUE THREAD

**Issue by ljpadam** [open-mmlab/mmdetection#6433]
> > > > Hi @vealocia ,
> > > > Thanks for the efforts. It is highly possible that we can make it in this month! Would you also like to add the configs/queryinst/README.md to add the bibetex and the performance of QueryInst just like the other methods? You may also update QueryInst in the model zoo and README.md pages.
> > > 
> > > 
> > > Thanks for the cooperations from all your maintainers too. All pretrained models and logs are prepared and I will update the performance and models asap. But I don't know how to upload these models and logs to your custom server (download.openmmlab.com), can you help me?
> > 
> > 
> > Hi @vealocia , Would you like to put them to google drive or BaiduYUN for us to download and test the model?
> 
> The share link to queryinst checkpoints is https://pan.baidu.com/s/1TVuusygUX1M6YXEIwWR9tQ passwork: hbk0

QueryInst pretrained checkpoints can be downloaded here ⬆️

_Originally posted by @vealocia in https://github.com/open-mmlab/mmdetection/issues/6050#issuecomment-949358824_

Hi, @vealocia
Thank you for the great work.
The baidu link is invalid now. Could you provide a new link, either google drive or baidu drive is OK.

**Comment by vealocia** [comment]
BaiduDrive: https://pan.baidu.com/s/1BPYGM15u4ieuVu156hwTWg KeyCode: kka8
GoogleDrive: https://drive.google.com/drive/folders/1DMelfiwQ1pEc8pJRW096-BML6w3o2IFU?usp=sharing

**Comment by vealocia** [comment]
@ZwwWayne Could you please update the download link of queryinst pretrained model in ```READM.md``` and ```metafile```? Many thanks~

**Comment by ljpadam** [comment]
> BaiduDrive: https://pan.baidu.com/s/1BPYGM15u4ieuVu156hwTWg KeyCode: kka8 GoogleDrive: https://drive.google.com/drive/folders/1DMelfiwQ1pEc8pJRW096-BML6w3o2IFU?usp=sharing

Thanks for your help.

**Comment by AronLin** [comment]
> @ZwwWayne Could you please update the download link of queryinst pretrained model in `READM.md` and `metafile`? Many thanks~

I will push this process.

**Comment by AronLin** [comment]
@ljpadam Hi, I have a question, could you tell me that this checkpoint is trained based on our latest codebase?

**Comment by vealocia** [comment]
> @ljpadam Hi, I have a question, could you tell me that this checkpoint is trained based on our latest codebase?

No, this checkpoint is trained on mmdetection 2.15 and 2.17

**Comment by AronLin** [comment]
The link is updated by #6460.
