### ISSUE TITLE
Plug_in question

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6434]
Hello! I want to insert "context_block" into the backbone **Resnet**, and the position =**"after_conv2**". Is the **structure** like that :
![image](https://user-images.githubusercontent.com/86214036/140016483-414e5d95-4cf4-466e-9232-d3e6673034c2.png)

**Comment by AronLin** [comment]
Do you want to insert codes into our codebase? Or just ask where to insert these codes?

**Comment by lijoe123** [comment]
where .and i just want to know the meaning of "after_conv2"发自坚果 R2
* body { background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }Guangchen Lin ***@***.***>
于 2021年11月3日 下午7:07写道：
Do you want to insert codes into our codebase? Or just ask where to insert these codes?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/open-mmlab/mmdetection/issues/6434#issuecomment-958927584",
"url": "https://github.com/open-mmlab/mmdetection/issues/6434#issuecomment-958927584",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by PeterVennerstrom** [comment]
I think your diagram references stem/stages.  after_conv2 refers to the position of the plugin within the forward pass of each Bottleneck block.  

If your intention is to run the plugin between stages rather within each Bottleneck (or within the Bottlenecks of a subset of the stages) the forward pass of the ResNet class should be edited to include your plugin.  Currently this behavior cannot be set by config.

**Comment by lijoe123** [comment]
Thank you! I had read the paper "An Empirical Study of Spatial Attention Mechanisms in Deep Networks" . And i had read the word : **"in the last two stages"**
![image](https://user-images.githubusercontent.com/86214036/140273480-bee841c6-40f2-4b14-b114-96ec0bdbf712.png)
Is **"the last two stages"** the same as **"after_conv2"** ?
![image](https://user-images.githubusercontent.com/86214036/140274062-58d1d1fc-31b3-4942-95aa-1e00a2d0ec39.png)

**Comment by PeterVennerstrom** [comment]
The Resnet backbone stage naming convention in this codebase is stem > stage_idx 0 > stage_idx 1 > stage_idx 2 > stage_idx 3.  This corresponds to c1 through c5 in your diagram.

Each Resnet stage is a sequence containing multiple Basic blocks or Bottleneck blocks.

The plugins are applied within Bottleneck blocks.  There are three convolution layers in each Bottleneck block and the plugin may be applied after any of them.      

The plugins have two settings to determine where they are added to the network.

Stages determines which stages contain Bottleneck blocks with the plugin.  In your case it would be stages = (False, False, True, True).

Position sets the location of the plugin within each Bottleneck block.

**Comment by lijoe123** [comment]
Wow!!!!Thank you Peter! I Got IT!!!
