### ISSUE TITLE
Unexpected and missing keys

### ISSUE THREAD

**Issue by ridasalam** [open-mmlab/mmdetection#644]
Hi, what is the reason for the following?

unexpected key in source state_dict
missing keys in source state_dict

I want to load one of the pretrained models and fine tune it on my dataset. I have not modified the model at all.

I am running on a single GPU.

**Comment by hellock** [comment]
What is the full output information?

**Comment by ridasalam** [comment]
unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer3.5.bn3.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer3.1.bn3.num_batches_tracked, bn1.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer3.5.bn1.num_batches_tracked

**Comment by hellock** [comment]
You can just ignore these warnings. It's expected.

**Comment by yxchng** [comment]
@hellock Just curious, if it is expected, why print out these messages as if they are errors?

**Comment by hellock** [comment]
@yxchng Not all unexpected keys and missing keys are expected, such info can help users to identify if the loaded model are mismatched.

**Comment by SONG-WONHO** [comment]
@hellock Thanks! I have a question here. Is there any method to ignore these warnings? Like set logging level upper ** . Thanks.
