### ISSUE TITLE
how to get final precision when test model? 

### ISSUE THREAD

**Issue by cena001plus** [open-mmlab/mmdetection#6440]
Hello, thank you for your contributions. I am using your project and encountered a problem. I have checked all the issues and did not solve my problem. My problem is: When I tested the model, I did not get the precision data. Only gts, dets, recall, ap, my data is in voc format, I have used --eval mAP, it still has no precision, in addition, using --eval mAP recall, the following problems occur

`    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/ailab/anaconda3/envs/mm/lib/python3.7/site-packages/mmdet-2.18.0-py3.7.egg/mmdet/datasets/voc.py", line 60, in evaluate
    assert len(metric) == 1
AssertionError
`
1.How can we get precision through the model inference in voc data.
2.If not, how can I get it through training and verifying the model.
3.dets is all the boxes predicted by the model, how to get the final number of predicted boxes

**Comment by RangiLyu** [comment]
What command did you run?

**Comment by cena001plus** [comment]
> What command did you run?

`os.system(f"python {test} {config} {checkpoint} --eval mAP")
os.system(f"python {test} {config} {checkpoint} --eval mAP recall")`

**Comment by RangiLyu** [comment]
> 1.How can we get precision through the model inference in voc data.

`python {test} {config} {checkpoint} --eval mAP` command is correct. And the `mAP` is the precision. Do not add `recall` after that. The evaluation currently only support one eval type. 

> 3.dets is all the boxes predicted by the model, how to get the final number of predicted boxes

What do you mean `final number of predicted boxes`? If you want to get the number of boxes with a higher score threshold, just modify the `score_thr` in the config file.

**Comment by cena001plus** [comment]
> > 1.How can we get precision through the model inference in voc data.
> 
> `python {test} {config} {checkpoint} --eval mAP` command is correct. And the `mAP` is the precision. Do not add `recall` after that. The evaluation currently only support one eval type.
> 
> > 3.dets is all the boxes predicted by the model, how to get the final number of predicted boxes
> 
> What do you mean `final number of predicted boxes`? If you want to get the number of boxes with a higher score threshold, just modify the `score_thr` in the config file.

Thanks for the answer, in fact, what I mean is that the number of dets is significantly higher than the number of gts. The detection frame needs to be filtered, nms, so that many invalid frames can be eliminated, and then we can calculate the recall and precision based on the remaining detection frames. I want to know The recall value obtained here, whether the prediction box used has been processed。

**Comment by cena001plus** [comment]
Because of the large number of dets, the recall calculated based on it should be very high, and the corresponding precision should be very low.

**Comment by RangiLyu** [comment]
These boxes are already filtered by the `test_cfg` set in your config. If you want to filter more boxes, just modify your config such as changing score threshold or nms iou threshold.

**Comment by cena001plus** [comment]
> > 1.How can we get precision through the model inference in voc data.
> 
> `python {test} {config} {checkpoint} --eval mAP` command is correct. And the `mAP` is the precision. Do not add `recall` after that. The evaluation currently only support one eval type.
> 
> > 3.dets is all the boxes predicted by the model, how to get the final number of predicted boxes
> 
> What do you mean `final number of predicted boxes`? If you want to get the number of boxes with a higher score threshold, just modify the `score_thr` in the config file.

I modified mean_ ap.py  ,  i can  get the precision data. The result is the same as expected, that is, 
1. you use all the detection boxes to calculate the recall and precision, so the recall is very high and the precision is very low. 
2. According to the intuitive feeling, the AP should also be very low, but the result is just the opposite.
3.  In addition, when evaluating the model, i also saved the pictures and found that there are not many prediction boxes, It means that you eliminate the invalid prediction bounding box after calculating the evaluation index(recall , recision), which is also my question. Why not calculate the evaluation after that.
4. How can I get the coordinate information and label information of the last prediction box？

#1231
#506

+-------+-------+-------+--------+-----------+-------+
| class | gts   | dets  | recall | precision | ap    |
+-------+-------+-------+--------+-----------+-------+
| class1  | 1108 | 3585 | 0.998  | 0.308     | 0.951 |
| class2  | 95   | 935  | 0.981  | 0.100     | 0.807 |

**Comment by cena001plus** [comment]
> These boxes are already filtered by the `test_cfg` set in your config. If you want to filter more boxes, just modify your config such as changing score threshold or nms iou threshold.

ok， Modified score_thr, changed 0.05 to 0.25, the number of prediction boxes obtained was reduced a lot, and the result looked normal. It is recommended to increase the default value.
