### ISSUE TITLE
can you give the reason about why yolox use SyncNormHook ?  many thanks for you.

### ISSUE THREAD

**Issue by yulinhuyang** [open-mmlab/mmdetection#6444]
dict(
        type='SyncNormHook',
        num_last_epochs=15,
        interval=interval,
        priority=48),

**Comment by BIGWangYuDong** [comment]
Please @hhaAndroid have a look

**Comment by hhaAndroid** [comment]
@yulinhuyang Because this can ensure that the BN parameters between multiple cards are completely consistent, especially after using EMA.
