### ISSUE TITLE
An editing error in the Tutorial Documentation

### ISSUE THREAD

**Issue by pandamax** [open-mmlab/mmdetection#6446]
Thank you for ur contribution, I am a newbie to this project, maybe I found an editing error in the latest [Tutorial Documentation](https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html). The detailed description is shown in the figure.

![图片](https://user-images.githubusercontent.com/23495527/140485815-7beba29e-b8f8-4309-96b8-300b74ee6d41.png)

it should be `python tools/test.py configs/balloon/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_balloon.py work_dirs/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_balloon/latest.pth --eval bbox segm`

**Comment by BIGWangYuDong** [comment]
Seems you are right, you can create a Pull Request to fix this error
