### ISSUE TITLE
Why RPN keep more RoIs with higher iou_threshold in mmdetection implementation?

### ISSUE THREAD

**Issue by vombategeht** [open-mmlab/mmdetection#6447]
Hey there. Thanks a lot for you guys' hard work!!!

I'm trying to see **how many RoIs are left with different RPN IoU thresholds**.
I added the code below in mmcv>ops>nms.py> class NMSop - forward function

```
iou_thresholds = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
        indss = []
        for iou_threshold in iou_thresholds:
            indss.append((ext_module.nms(bboxes, scores, iou_threshold=float(iou_threshold), offset=offset), iou_threshold))
```

And the result showed that **fewer RoIs are left with the smaller iou_threshold, and more RoIs are left with the big iou_threshold**.
Shouldn't it be the other way around? 

As far as I know, if the IoU threshold is set to 0.9, it means that the network only keeps RoIs whose IoU with GT is bigger or equal than 0.9. 
But I could only got 951 RoIs with `iou_threshold=0.5`, and 7958 RoIs with  `iou_threshold=0.95`

Is there something I'm missing?
If anyone knows the answer, please please reach out for me.

**Comment by hhaAndroid** [comment]
@vombategeht 

There is no need to modify the MMCV, you just need to modify the iou threshold through the config, and then print the number of det.

![image](https://user-images.githubusercontent.com/17425982/140719904-7e91b4cf-df5f-4ca6-95c7-64640b328c99.png)


https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/rpn_head.py#L232

**Comment by vombategeht** [comment]
@hhaAndroid Thank you for your answer but this is not what I'm asking. 
I've done what you told me to do, but the result seems the same as what I've got from my own codes. 

I'm still getting **fewer RoIs with the smaller iou_threshold, and more RoIs with the big iou_threshold**, and I think this is problematic according to the definition of NMS. 

Why smaller iou_threshold keeps fewer RoIs? Smaller iou_threshold should keep bigger number of RoIs, isn' it?
@hhaAndroid Is there something I'm missing? :pray:

**Comment by hhaAndroid** [comment]
@vombategeht This is normal. Only IOU greater than the threshold will be deleted. The greater the IOU threshold, the more ROI will be retained.

**Comment by vombategeht** [comment]
@hhaAndroid Oh, I confused with the confidence thresholds. Sorry for being so stuffy. Thank you so much.
