### ISSUE TITLE
Installation encountered a problem with add_mim_extension

### ISSUE THREAD

**Issue by mengmeng0320** [open-mmlab/mmdetection#6449]
when I run pip install -v -e. there was some error like these:

    warning: no files found matching 'mmdet/VERSION'
    warning: no files found matching 'mmdet/.mim/model-index.yml'
    warning: no files found matching 'mmdet/.mim/demo/*/*'
    warning: no files found matching '*.py' under directory 'mmdet/.mim/configs'
    warning: no files found matching '*.yml' under directory 'mmdet/.mim/configs'
    warning: no files found matching '*.sh' under directory 'mmdet/.mim/tools'
    warning: no files found matching '*.py' under directory 'mmdet/.mim/tools'
    writing manifest file '/tmp/pip-pip-egg-info-93hf6e37/mmdet.egg-info/SOURCES.txt'
    File "./mmdetection/setup.py", line 169, in add_mim_extension
        os.symlink(src_relpath, tar_path)
    OSError: [Errno 95] Operation not supported: '../../tools' -> './mmdetection/mmdet/.mim/tools'

    It looks like soft link path failed，I'd like to ask how to solve this problem

**Comment by hhaAndroid** [comment]
@mengmeng0320 Please use the issue template.

**Comment by Nothingtolose9979** [comment]
how to solve this problem. I met the same problem QAQ

**Comment by ttt0666** [comment]
how to solve this problem. I met the same problem QAQ
