### ISSUE TITLE
How to pass my custom configuration to the source code?

### ISSUE THREAD

**Issue by jinzcdev** [open-mmlab/mmdetection#6450]
I think the mmdetection is almost the best framework for object detection at the moment. However, I don't know how to pass my custom configuration to the source code when I need to modify a module, for example if I want to replace the 3x3 conv with a module written by ourselves.

**Comment by hhaAndroid** [comment]
@jinzcdev You can create a new module to achieve. Please refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/3_exist_data_new_model.md#prepare-your-own-customized-model
