### ISSUE TITLE
some questions about test_cfg's max_per_img

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#6454]
I want to re evaluate my model. I replace the maximum detection quantity(max_per_img) of 300 with 500, but the final evaluation result is the same. Wouldn't increasing the number of tests increase the accuracy?

**Comment by hhaAndroid** [comment]
@chensen668 This is related to the model. If the quality of the additional 200 boxes is not high, mAP will not be increased. You can consider reducing `score_thr` at the same time.

**Comment by chensen668** [comment]
OK, I understand. Thank you for your reply
