### ISSUE TITLE
A question about Cascade R-CNN code details

### ISSUE THREAD

**Issue by vombategeht** [open-mmlab/mmdetection#6455]
According to the code below, and as far as I comprehended, `roi_labels` states the GT labels that are assigned to the proposals. 
https://github.com/open-mmlab/mmdetection/blob/374d4c0bed3e3c01e2988213b54310500479e3df/mmdet/models/roi_heads/cascade_roi_head.py#L268
However, these codes below give some changes to the `roi_labels`. If the GT label is bg, it is substituted with the most probable class label that is not bg. 
https://github.com/open-mmlab/mmdetection/blob/374d4c0bed3e3c01e2988213b54310500479e3df/mmdet/models/roi_heads/cascade_roi_head.py#L279-L281
What is the point of doing this? Shouldn't Groundtruth labels be given any changes?

**Comment by hhaAndroid** [comment]
@vombategeht This is because the training process is dynamic. For the background proposal, it may become a positive sample after training. At this time, it needs to be dynamically adjusted to a positive sample.

**Comment by vombategeht** [comment]
Thanks for your response! 

But unfortunately I still don't get why Faster R-CNN does not apply the same technique. **Isn't it same for Faster R-CNN that bg proposals might become positive samples after training?**

I also wonder `bbox_results['bbox_targets'][0]` are GT labels or not. I thought they are, but now I'm confused. Are they predicted labels for bounding boxes or unchangeable GT labels?

**Comment by hhaAndroid** [comment]
@vombategeht This is the refining process.
