### ISSUE TITLE
Are anchors applied on the Image or on the feature map ? 

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6462]
I'm training detectors with a resnet50 backbone
here are my anchors:
![image](https://user-images.githubusercontent.com/11663917/140767423-61f22cc3-3586-4f4f-a325-667d2091612c.png)
here is my feature map:
![image](https://user-images.githubusercontent.com/11663917/140767179-d29613f1-60e0-4eaa-8574-18e4d796163c.png)

I thought the anchor value applied to coordinate of the feature map, but apparently they are out of dimension (anchors is bigger than the feature map max dim). 

Or maybe anchors apply to the raw image and some scaled down version of the raw image ? I'm confused.

**Comment by hhaAndroid** [comment]
@joihn This is normal, and the ones out of bounds will be deleted.

**Comment by joihn** [comment]
Thanks,
Soo the base achor are applied using a sliding windows mechanism **over the feature map**, right ?

**Comment by hhaAndroid** [comment]
The anchor is in the image dimension.

**Comment by joihn** [comment]
okay thanks
