### ISSUE TITLE
loss problem

### ISSUE THREAD

**Issue by HuangQinJian** [open-mmlab/mmdetection#647]
I want to konw if I want to use focal_loss in `cascade_mask_rcnn_r50_fpn_1x.py`,what should I do?

**Comment by hellock** [comment]
Which part do you want to use focal loss on?

**Comment by HuangQinJian** [comment]
> Which part do you want to use focal loss on?

regression loss

**Comment by hellock** [comment]
Focal Loss is not applicable to regression, you may need to read [Focal Loss for Dense Object Detection](https://arxiv.org/abs/1708.02002).

**Comment by gittigxuy** [comment]
@hellock ,but why could you use Focal loss in guide anchor faster rcnn,in regression loss?
