### ISSUE TITLE
File client for reading from S3 Object Storage

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#6470]
Hi, sorry for asking a question similar to #4212, but just wanted to clarify more stuff regarding this: 

- Is `petrel_client` something internal to your lab? 
- If we want to read our data directly from a S3 bucket into memory, we can implement a file client that makes use of [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) (for example), and various credentials/bucket name/path can be passed through `file_client_args`? 
- Under this implementation, is a new S3 client instantiated for every single image read?

**Comment by AronLin** [comment]
Yes, it is supported for internal usage. This function is temporarily not open to the community, and it is supported by mmcv. If you want to discuss, you can open an issue in mmcv.

**Comment by levan92** [comment]
Alright, thanks!
