### ISSUE TITLE
How to adjust schedule using swin transformer for multi-scale crop

### ISSUE THREAD

**Issue by sunny-sjj** [open-mmlab/mmdetection#6471]
Hi! when I use swin transformer as backbone in faster-rcnn,if  I use not use multi-scale crop, the result is well( Lr schd=1x), but when I use  Offline multi-scale crop ,the result is not the same as expected( Lr schd=1x).
Is my training time too short?sholud I adjust  Lr schd=3x?

**Comment by AronLin** [comment]
If you use data augmentation, it will be better to increase the schedule.
