### ISSUE TITLE
Can't reproduce map score even if seed and deterministic has set.

### ISSUE THREAD

**Issue by sjytker** [open-mmlab/mmdetection#6472]
I has set seed=100 and deterministic=True. 

But I can't get the same map0.5 score every time I train(nothing changed). It's not small fluctuations, but a big one!! Sometimes I got 0.55 map0.5 score after converging. The other times I could get 0.60 map0.5 score.

I notice that same problem has been raised in 2019 and it's now 2021. It's a huge problem isn't it? Don't you guys going to fix it?

**Comment by AronLin** [comment]
Are you Chinese? If you are, please read this article.
https://www.zhihu.com/question/453511684/answer/1839683634

**Comment by sjytker** [comment]
Forgive my rudeness, this is the first time I saw such a huge fluctuations. Perhaps the small size of dataset is to be blamed.

**Comment by GingerCohle** [comment]
coco also happen this

**Comment by Anm-pinellia** [comment]
here is 2022, this problem still has not been fixed.....

**Comment by AronLin** [comment]
Atomic operations in CUDA are unordered and random when parallelized.

So, even if the seed and deterministic are fixed, the result can also be different among trainings.
