### ISSUE TITLE
mmdet/datasets/coco.py:454: UserWarning: The key "bbox" is deleted for more accurate mask AP 

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6473]
I'm training instance segmentation models on datasets of type `COCODataset`. I want to compute the bbox mAP and the mask mAP at the end of each epoch on the validation set. To do this, I've always included these two lines in all my config files:

```python
evaluation = dict(metric=['bbox', 'segm'], save_best='bbox_mAP')
workflow = [('train', 1), ('val', 1)]

```
However, today I noticed for the first time that MMDetection raise a warning at train time:

```
2021-11-09 18:03:30,159 - mmdet - INFO - Evaluating segm...                                                                                    
/mmdetection/mmdet/datasets/coco.py:454: UserWarning: The key "bbox" is deleted for more accurate mask AP of small/medium/large instances since
 v2.12.0. This does not change the overall mAP calculation. 
```

What does this mean? Should I change something in my config file, or is it fine the way it is?

**Comment by AronLin** [comment]
You can refer to the comments in [coco.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L441)
