### ISSUE TITLE
GA-RPN

### ISSUE THREAD

**Issue by fanxiaochen-123** [open-mmlab/mmdetection#6475]
Where is the code of GA-RPN?

**Comment by RangiLyu** [comment]
https://github.com/open-mmlab/mmdetection/blob/bde7b4b7eea9dd6ee91a486c6996b2d68662366d/mmdet/models/dense_heads/ga_rpn_head.py

**Comment by fanxiaochen-123** [comment]
@RangiLyu Thank you
