### ISSUE TITLE
[Result analysis problem] Pure background image have a 0 score

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6479]
I'm training detectoRS on a custom dataset, which have some pure background image.
I order to benefit from those  image, I've set `filter_empty_gt=False` in the data cfg.

I then use `tools/analysis_tools/analyze_results.py` to analyse my results.
suprisingly, some pure background image (where the net correctly recognise as pure background, he doesn't output any BBox) are given a score of 0 (I think it should be 1, since the net did everything correct).

_(By score, I mean the score presented at the end of the filename)._
![image](https://user-images.githubusercontent.com/11663917/141100415-54cf429c-a577-4f92-b168-cb5936ee0b88.png)

Is it a bug or am I doing something wrong ?

**Comment by hhaAndroid** [comment]
@joihn The network output score represents the foreground score, if there are no objects, the score should be 0.

**Comment by joihn** [comment]
But that means during evaluation of my network, correctly detected pure background image will actually penalize my global mAP, right ?

**Comment by joihn** [comment]
After playing a while with `test_dataset_evaluation()` `tests/test_data/test_datasets/test_common.py` and `mmdet/datasets/coco.py`, I can confirm that `pycocotool` (using during training) gives a score of 1 for a perfect pure background predicition where the annotation also say pure background, and this score gradually decrease with the number of wrong predictions made.

feature suggestion: modify` tools/test.py` to follow the same behavior.
