### ISSUE TITLE
 How  to use AutoAugment

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#6481]
Hello, I want to use autoaugment in Mask RCNN, but I don't know how to use it, because there are several enhancement strategies. My mmdet = 2.16

**Comment by hhaAndroid** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/detr/detr_r50_8x2_150e_coco.py#L80

**Comment by chensen668** [comment]
Well, thank you. Another question is, the current mosaic enhancements and mixup enhancements don't support instance segmentation?

**Comment by hhaAndroid** [comment]
> Well, thank you. Another question is, the current mosaic enhancements and mixup enhancements don't support instance segmentation?

Yes

**Comment by chensen668** [comment]
OK, thanks. Maybe I should try to realize this function by myself.
