### ISSUE TITLE
default epoch in centernet

### ISSUE THREAD

**Issue by yanlongbinluck** [open-mmlab/mmdetection#6484]
Hi, why the default max epoch in Centernet is 28? [config file](https://github.com/open-mmlab/mmdetection/blob/6cf9aa1866b745fce8f1da6717fdb833d7c66fab/configs/centernet/centernet_resnet18_dcnv2_140e_coco.py#L122)
and not 140 in original code?

**Comment by hhaAndroid** [comment]
@yanlongbinluck Because RepeatDataset is used, the data set will be repeated 5 times

**Comment by yanlongbinluck** [comment]
Thanks
