### ISSUE TITLE
cascade_rcnn_r101_fpn_1x  invalid hash value

### ISSUE THREAD

**Issue by banxia1994** [open-mmlab/mmdetection#649]
hi, I get error:

RuntimeError: invalid hash value (expected "19c8e357", got"ef60faf7386481555dabe702298afe50ac8f40935185")

for config 'cascade_rcnn_r101_fpn_1x'

**Comment by yhcao6** [comment]
Hi, I just successfully run the cfg `cascade_rcnn_r101_fpn_1x.py`, could you provide more information about how to reproduce this error?

**Comment by banxia1994** [comment]
sorry, my mistakes.  I run it again and no problem.
