### ISSUE TITLE
ImportError: cannot import name 'init_random_seed'

### ISSUE THREAD

**Issue by yeyujujishou19** [open-mmlab/mmdetection#6491]
CUDA 10.1
GCC 7.5

**Install steps:**
1,
conda create -n openmmlab python=3.6
conda activate openmmlab

2,
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1

3,
pip install openmim

4,
mim install mmdet

**Next**
Then the installation was successful

Then git clone https://github.com/open-mmlab/mmdetection.git 

and run:
python demo/image_demo.py demo/demo.jpg configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth

Equally successful

**error**
when run：
python ./tools/train.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py

The following error occurred：

Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmdet.apis import init_random_seed, set_random_seed, train_detector
ImportError: cannot import name 'init_random_seed'

**Can someone help me solve this problem？**

**Comment by Jyunta** [comment]
I met the same problem. Could you tell me how you solved it? Thanks in advance.

**Comment by yeyujujishou19** [comment]
Move tools/main.py to the mmdetection main folder, and that’s it


| |
宋晓利
|
|
***@***.***
|
签名由网易邮箱大师定制
On 11/14/2021 ***@***.***> wrote：

I met the same problem. Could you tell me how you solved it? Thanks in advance.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by juAo12** [comment]
Hello, I can't find the file that tools/main.py, and what is mmdetection main folder? Is the mmdetection/ ? Please tell me, thanks!

**Comment by qiumeng6** [comment]
> 
I update my mmdet version from 2.14 to 2.18 and it works !

**Comment by Ancuy** [comment]
> > 
> 
> 我将我的 mmdet 版本从 2.14 更新到 2.18，并且可以正常工作！

I have updated the version, but the issue still hasn't been resolved
