### ISSUE TITLE
norm_cfg = dict(type='BN', requires_grad=False) Can we close the 'BN' in training by ignoring setting norm_cfg?

### ISSUE THREAD

**Issue by addicter2017** [open-mmlab/mmdetection#6494]
I don't want to train with BN because my GPU resourse can not take large batch size in training.
Is there any way to close the 'BN' from config files?

**Comment by PeterVennerstrom** [comment]
Most of the backbones/necks/heads build layers containing BN with the [ConvModule class in the MMCV library](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/bricks/conv_module.py)

If no norm config is passed these layers will not include BN which will save memory, but might be difficult to train.

Another possibility is freezing BN by setting requires_grad = False in the norm config for any pre-trained layers.
