### ISSUE TITLE
Distributed training will hang if log_vars has different length among GPUs

### ISSUE THREAD

**Issue by fingertap** [open-mmlab/mmdetection#6495]
Similar to the [issue in mmseg](https://github.com/open-mmlab/mmsegmentation/issues/1030). Here I just quote:

> In the `_parse_log` function of the `mmseg.segmentors.base.BaseSegmentor`, it attempts to synchronize the loss values among all GPUs. What happened is that in this loop ([line 194](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/base.py#L194)):
>
> ```python
> for loss_name, loss_value in log_vars.items():
>    # reduce loss when distributed training
>    if dist.is_available() and dist.is_initialized():
>        loss_value = loss_value.data.clone()
>        dist.all_reduce(loss_value.div_(dist.get_world_size()))
>    log_vars[loss_name] = loss_value.item()
>```
>
>One GPU A does not have a `"roi_acc"` as `loss_name` (suppose it is the last key in `log_vars`). Then this GPU A thinks it has done all its work, and jump out of the loop. Other GPUs with the last `"roi_acc"` will try to call `torch.distributed.all_reduce`, which infinitely waits for the reply from GPU A.

This bug is hard to debug, as it just gets blocked without error messages.

**Comment by RangiLyu** [comment]
Thanks for finding this bug! Would you like to open a PR for MMDetection just like the one in mmseg https://github.com/open-mmlab/mmsegmentation/pull/1035 ?

**Comment by fingertap** [comment]
Of course. Also, do you think I should add support for skipping such loss terms by setting them to `None`? An example can be found [here](https://github.com/open-mmlab/mmsegmentation/pull/1035#:~:text=%40staticmethod%0Adef%20_parse_losses,return%20loss%2C%20log_vars).

**Comment by RangiLyu** [comment]
> Of course. Also, do you think I should add support for skipping such loss terms by setting them to `None`? An example can be found [here](https://github.com/open-mmlab/mmsegmentation/pull/1035#:~:text=%40staticmethod%0Adef%20_parse_losses,return%20loss%2C%20log_vars).

This feature is worth discussing. @hhaAndroid @ZwwWayne Please take a lot.

**Comment by hhaAndroid** [comment]
> Of course. Also, do you think I should add support for skipping such loss terms by setting them to `None`? An example can be found [here](https://github.com/open-mmlab/mmsegmentation/pull/1035#:~:text=%40staticmethod%0Adef%20_parse_losses,return%20loss%2C%20log_vars).

This is indeed a potential bug. I think assert is the most appropriate, and we can print the keys of different processes at the same time.

**Comment by ZwwWayne** [comment]
Agree, set it to None might be risky. Furthermore, usually each rank should have similar loss names, their values can be 0 if there is not positive samples.
