### ISSUE TITLE
plugin question

### ISSUE THREAD

**Issue by The-Yu** [open-mmlab/mmdetection#6496]
I want to use the context_block ,but under the dir:mmdet/model/plugins only dropblock,should I use it directly or register it first？

**Comment by hhaAndroid** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/3_exist_data_new_model.md#prepare-your-own-customized-model

**Comment by The-Yu** [comment]
thanks for your reply

**Comment by The-Yu** [comment]
> You can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/3_exist_data_new_model.md#prepare-your-own-customized-model
thanks for your reply
