### ISSUE TITLE
different results for same dataset under VOC style and COCO style

### ISSUE THREAD

**Issue by Chan-Sun** [open-mmlab/mmdetection#6499]
Hi! very appreciate for your excellent work on this open-source package!

I was trying to apply some experiments on surface defect detection dataset.

My baseline model is faster rcnn fpn with resnet-50 as backbone, and softnms for test cfg. 

A typical benchmark dataset on this field is NEU-DET dataset [[links](http://faculty.neu.edu.cn/songkechen/zh_CN/zhym/263269/list/index.htm)], and the annotations provided are in voc style.  I wrote some code to convert the voc style to coco style which i'm more familiar with. 

However, same model setting and train-test split got different results under VOC style and COCO style

```shell
 ############  COCO ################
 Average Precision  (AP) @[ IoU=0.50:0.50 | area=   all | maxDets=100 ] = 0.724
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.50 | area= small | maxDets=1000 ] = 0.367
 Average Precision  (AP) @[ IoU=0.50:0.50 | area=medium | maxDets=1000 ] = 0.617
 Average Precision  (AP) @[ IoU=0.50:0.50 | area= large | maxDets=1000 ] = 0.777
 Average Recall     (AR) @[ IoU=0.50:0.50 | area=   all | maxDets=100 ] = 0.943
 Average Recall     (AR) @[ IoU=0.50:0.50 | area=   all | maxDets=300 ] = 0.943
 Average Recall     (AR) @[ IoU=0.50:0.50 | area=   all | maxDets=1000 ] = 0.943
 Average Recall     (AR) @[ IoU=0.50:0.50 | area= small | maxDets=1000 ] = 0.419
 Average Recall     (AR) @[ IoU=0.50:0.50 | area=medium | maxDets=1000 ] = 0.863
 Average Recall     (AR) @[ IoU=0.50:0.50 | area= large | maxDets=1000 ] = 1.000
+----------------+-------+-----------------+-------+-----------+-------+
| category       | AP    | category        | AP    | category  | AP    |
+----------------+-------+-----------------+-------+-----------+-------+
| crazing        | 0.451 | inclusion       | 0.875 | patches   | 0.872 |
| pitted_surface | 0.627 | rolled-in_scale | 0.655 | scratches | 0.865 |
+----------------+-------+-----------------+-------+-----------+-------+

############  VOC  ################
---------------iou_thr: 0.5---------------

+-----------------+-----+------+--------+-------+
| class           | gts | dets | recall | ap    |
+-----------------+-----+------+--------+-------+
| crazing         | 64  | 835  | 0.969  | 0.457 |
| inclusion       | 110 | 587  | 0.973  | 0.897 |
| patches         | 84  | 370  | 0.964  | 0.893 |
| pitted_surface  | 38  | 269  | 0.868  | 0.628 |
| rolled-in_scale | 73  | 606  | 0.973  | 0.681 |
| scratches       | 54  | 242  | 0.963  | 0.887 |
+-----------------+-----+------+--------+-------+
| mAP             |     |      |        | 0.741 |
+-----------------+-----+------+--------+-------+
```

I haven't read much  evaluation code in mmdet, i wonder if this situation is possible? If not, how can i find the bug and fix that?

Many thanks again!

**Comment by RangiLyu** [comment]
This is due to different coordinate definitions between VOC and COCO. We follow the original VOC-devkit implementation. In VOC, w, h should be computed as 'x2 - x1 + 1' and 'y2 - y1 + 1'.  Try to set `use_legacy_coordinate=False` in mmdet/datasets/voc.py

**Comment by Young0111** [comment]
> Hi! very appreciate for your excellent work on this open-source package!
> 
> I was trying to apply some experiments on surface defect detection dataset.
> 
> My baseline model is faster rcnn fpn with resnet-50 as backbone, and softnms for test cfg.
> 
> A typical benchmark dataset on this field is NEU-DET dataset [[links](http://faculty.neu.edu.cn/songkechen/zh_CN/zhym/263269/list/index.htm)], and the annotations provided are in voc style. I wrote some code to convert the voc style to coco style which i'm more familiar with.
> 
> However, same model setting and train-test split got different results under VOC style and COCO style
> 
> ```shell
>  ############  COCO ################
>  Average Precision  (AP) @[ IoU=0.50:0.50 | area=   all | maxDets=100 ] = 0.724
>  Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
>  Average Precision  (AP) @[ IoU=0.50:0.50 | area= small | maxDets=1000 ] = 0.367
>  Average Precision  (AP) @[ IoU=0.50:0.50 | area=medium | maxDets=1000 ] = 0.617
>  Average Precision  (AP) @[ IoU=0.50:0.50 | area= large | maxDets=1000 ] = 0.777
>  Average Recall     (AR) @[ IoU=0.50:0.50 | area=   all | maxDets=100 ] = 0.943
>  Average Recall     (AR) @[ IoU=0.50:0.50 | area=   all | maxDets=300 ] = 0.943
>  Average Recall     (AR) @[ IoU=0.50:0.50 | area=   all | maxDets=1000 ] = 0.943
>  Average Recall     (AR) @[ IoU=0.50:0.50 | area= small | maxDets=1000 ] = 0.419
>  Average Recall     (AR) @[ IoU=0.50:0.50 | area=medium | maxDets=1000 ] = 0.863
>  Average Recall     (AR) @[ IoU=0.50:0.50 | area= large | maxDets=1000 ] = 1.000
> +----------------+-------+-----------------+-------+-----------+-------+
> | category       | AP    | category        | AP    | category  | AP    |
> +----------------+-------+-----------------+-------+-----------+-------+
> | crazing        | 0.451 | inclusion       | 0.875 | patches   | 0.872 |
> | pitted_surface | 0.627 | rolled-in_scale | 0.655 | scratches | 0.865 |
> +----------------+-------+-----------------+-------+-----------+-------+
> 
> ############  VOC  ################
> ---------------iou_thr: 0.5---------------
> 
> +-----------------+-----+------+--------+-------+
> | class           | gts | dets | recall | ap    |
> +-----------------+-----+------+--------+-------+
> | crazing         | 64  | 835  | 0.969  | 0.457 |
> | inclusion       | 110 | 587  | 0.973  | 0.897 |
> | patches         | 84  | 370  | 0.964  | 0.893 |
> | pitted_surface  | 38  | 269  | 0.868  | 0.628 |
> | rolled-in_scale | 73  | 606  | 0.973  | 0.681 |
> | scratches       | 54  | 242  | 0.963  | 0.887 |
> +-----------------+-----+------+--------+-------+
> | mAP             |     |      |        | 0.741 |
> +-----------------+-----+------+--------+-------+
> ```
> 
> I haven't read much evaluation code in mmdet, i wonder if this situation is possible? If not, how can i find the bug and fix that?
> 
> Many thanks again!

你好，我将voc转换为coco格式之后，验证精度很低，请问可以分享一下您转换格式之后操作的步骤么？
