### ISSUE TITLE
2.16版本的swin_transformer预训练模型替换为2.18版本的swin_tiny_patch4_window7_224.pth加载出错，麻烦看看是什么问题

### ISSUE THREAD

**Issue by zhanghang-cv** [open-mmlab/mmdetection#6502]
![image](https://user-images.githubusercontent.com/68639705/141719812-7c109c1a-57f8-4d88-a24e-44bcb9a52d5e.png)

**Comment by hhaAndroid** [comment]
@zhanghang-cv Please use the issue template.

**Comment by shinya7y** [comment]
Does this PR work? https://github.com/open-mmlab/mmdetection/pull/6205
