### ISSUE TITLE
How to speed up inference time

### ISSUE THREAD

**Issue by tienha-Brains** [open-mmlab/mmdetection#6503]
As the title described, how can I speed up the inference time for `mmdet` model for production stage?

I have tried to convert it to **TorchScript** but as this [issue](https://github.com/open-mmlab/mmdetection/issues/5329#issuecomment-858450163) address, this feature seem not to be supported yet.

I also tried to convert model to ONNX format and optimize (graph-optimize, quantization) but still no speed up at all.

**Comment by RangiLyu** [comment]
What is the model you used? Usually, convert to TensorRT and inference with FP16 or INT8 can speed up the inference time. Try to use this script `tools/deployment/onnx2tensorrt.py` and refer to this doc `docs/tutorials/onnx2tensorrt.md`

**Comment by tienha-Brains** [comment]
I will try TensorRT to see if there are any improvements. I'm using YOLOv3 btw. I will reopen if I have any problems. Thank you.

**Comment by tienha-Brains** [comment]
I will try TensorRT to see if there are any improvements. I'm using YOLOv3 btw. I will reopen if I have any problems. Thank you.

**Comment by dinhthihuyen** [comment]
How to calculate inference speed in mmdet?
