### ISSUE TITLE
Python  setup develop failed on Windows.

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmdetection#6504]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Mmcv-full has been installed successfully, but I got error when running `python setup develop`
```
13:51:48  Using c:\users\user\miniconda3\lib\site-packages\tomli-1.2.2-py3.8.egg
13:51:48  Finished processing dependencies for mmdet==2.18.0
13:51:48  C:\Users\user\miniconda3\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to usi
13:51:48  ng the slow distutils backend.
13:51:48    warnings.warn(msg.format('we could not find ninja.'))
13:51:48  Error in atexit._run_exitfuncs:
13:51:48  Traceback (most recent call last):
13:51:48    File "C:\Users\user\miniconda3\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
13:51:48      return stream.closed
13:51:48  ValueError: underlying buffer has been detached
```

https://github.com/open-mmlab/mmdetection/issues/5429
**Reproduction**

1. What command or script did you run?

```none
python setup develop```

After `pip install requirements/built.txt`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

Packages list after the failure:
```
13:51:51  Package                Version             Location
13:51:51  ---------------------- ------------------- ------------------------------------------------------------------------------
13:51:51  addict                 2.4.0
13:51:51  atomicwrites           1.4.0
13:51:51  attrs                  21.2.0
13:51:51  brotlipy               0.7.0
13:51:51  certifi                2021.10.8
13:51:51  cffi                   1.14.6
13:51:51  chardet                4.0.0
13:51:51  colorama               0.4.4
13:51:51  conda                  4.10.3
13:51:51  conda-package-handling 1.7.3
13:51:51  coverage               6.1.1
13:51:51  cryptography           3.4.7
13:51:51  cycler                 0.11.0
13:51:51  Cython                 0.29.24
13:51:51  flatbuffers            2.0
13:51:51  fonttools              4.28.1
13:51:51  idna                   2.10
13:51:51  iniconfig              1.1.1
13:51:51  kiwisolver             1.3.2
13:51:51  lmdb                   1.2.1
13:51:51  matplotlib             3.5.0rc1
13:51:51  menuinst               1.4.16
13:51:51  mkl-fft                1.3.1
13:51:51  mkl-random             1.2.2
13:51:51  mkl-service            2.4.0
13:51:51  mmcv-full              1.3.16              c:\workspace\mmcv
13:51:51  mmdet                  2.18.0              c:\workspace\jenkins\workspace\mmdetection\build-on-windows-zhenwu\mmdetection
13:51:51  numpy                  1.21.2
13:51:51  olefile                0.46
13:51:51  onnx                   1.7.0
13:51:51  onnxoptimizer          0.2.6
13:51:51  onnxruntime            1.9.0
13:51:51  opencv-python          4.5.4.58
13:51:51  packaging              21.2
13:51:51  Pillow                 8.4.0
13:51:51  pip                    21.1.3
13:51:51  pluggy                 1.0.0
13:51:51  protobuf               3.19.1
13:51:51  py                     1.11.0
13:51:51  pycocotools-windows    2.0.0.2
13:51:51  pycosat                0.6.3
13:51:51  pycparser              2.20
13:51:51  pyOpenSSL              20.0.1
13:51:51  pyparsing              2.4.7
13:51:51  PySocks                1.7.1
13:51:51  pytest                 6.2.5
13:51:51  python-dateutil        2.8.2
13:51:51  PyTurboJPEG            1.6.3
13:51:51  pywin32                227
13:51:51  PyYAML                 6.0
13:51:51  regex                  2021.11.2
13:51:51  requests               2.25.1
13:51:51  ruamel-yaml-conda      0.15.100
13:51:51  scipy                  1.7.2
13:51:51  setuptools             52.0.0.post20210125
13:51:51  setuptools-scm         6.3.2
13:51:51  six                    1.16.0
13:51:51  terminaltables         3.1.0
13:51:51  tifffile               2021.11.2
13:51:51  tiffile                2018.10.18
13:51:51  toml                   0.10.2
13:51:51  tomli                  1.2.2
13:51:51  torch                  1.10.0
13:51:51  torchvision            0.11.1
13:51:51  tqdm                   4.61.2
13:51:51  typing-extensions      3.10.0.2
13:51:51  urllib3                1.26.6
13:51:51  wheel                  0.36.2
13:51:51  win-inet-pton          1.1.0
13:51:51  wincertstore           0.2
13:51:51  yapf                   0.31.0
```

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by del-zhenwu** [comment]
Got the same error after `ninja                  1.10.2.2
` installed

**Comment by hhaAndroid** [comment]
@del-zhenwu Can the #5429 solution be used directly to solve it?

**Comment by del-zhenwu** [comment]
> @del-zhenwu Can the #5429 solution be used directly to solve it?

Maybe not the same issue I think, cause the mmcv package has been installed before
