### ISSUE TITLE
CascadeRCNN网络结构和caffe版本差异

### ISSUE THREAD

**Issue by SunshineJZJ** [open-mmlab/mmdetection#6507]
请问mmdet中的CascadeRCNN网络结构和https://github.com/zhaoweicai/cascade-rcnn/blob/master/examples/coco/res50-15s-800-fpn-cascade/deploy.prototxt 作者原版结构为什么不同呢？
![image](https://user-images.githubusercontent.com/38787542/141758404-d150877e-391c-439e-8b3c-2b71fd4ed99f.png)
这是Caffe的网络结构；
mmdet中该部分的网络结构如下：
roi_head.bbox_head.0.shared_fcs.0.weight
roi_head.bbox_head.0.shared_fcs.0.bias
roi_head.bbox_head.0.shared_fcs.1.weight
roi_head.bbox_head.0.shared_fcs.1.bias
roi_head.bbox_head.0.fc_cls.weight
roi_head.bbox_head.0.fc_cls.bias
roi_head.bbox_head.0.fc_reg.weight
roi_head.bbox_head.0.fc_reg.bias
roi_head.bbox_head.1.shared_fcs.0.weight
roi_head.bbox_head.1.shared_fcs.0.bias
roi_head.bbox_head.1.shared_fcs.1.weight
roi_head.bbox_head.1.shared_fcs.1.bias
roi_head.bbox_head.1.fc_cls.weight
roi_head.bbox_head.1.fc_cls.bias
roi_head.bbox_head.1.fc_reg.weight
roi_head.bbox_head.1.fc_reg.bias
roi_head.bbox_head.2.shared_fcs.0.weight
roi_head.bbox_head.2.shared_fcs.0.bias
roi_head.bbox_head.2.shared_fcs.1.weight
roi_head.bbox_head.2.shared_fcs.1.bias
roi_head.bbox_head.2.fc_cls.weight
roi_head.bbox_head.2.fc_cls.bias
roi_head.bbox_head.2.fc_reg.weight
roi_head.bbox_head.2.fc_reg.bias

卷积或者全连接层对应不上，我想把mmdet训练的CascadeRcnn权重转换为Caffe model，请问mmdet有转换工具吗？

**Comment by hhaAndroid** [comment]
@SunshineJZJ This is normal. We do not provide this special conversion script, you may have to convert it yourself.
