### ISSUE TITLE
Question about model prune   剪枝 问题

### ISSUE THREAD

**Issue by syswyl** [open-mmlab/mmdetection#6513]
To get a small model, I try to use some model pruning schemes（Like network slim） to cut the basic model.

1. In order to facilitate pruning, I use[ build_detector](https://github.com/open-mmlab/mmdetection/blob/6cf9aa1866b745fce8f1da6717fdb833d7c66fab/tools/train.py#L159) to get the model first.
and simply use torch.save to save the whole model, the checkpoint is also saved as torch.save(model.state_dict(), checkpoint_path), and add 'meta' and 'optimizer' in the checkpoint.
2. Then, i use HFP to changes the number of channels and corresponding parameters of the network like
```
if name == 'layer1.0.conv1':
        module.weight.data = module.weight.data[keep_index_feature['backbone.layer1.0.bn1'], :, :, :]
        module.weight.data = module.weight.data[:, keep_index_feature['backbone.bn1'] , :, :]
```
and do the same operations in checkopint. **e.g. with this operations, the backbone.layer.0.conv1's channel can be pruned from 64 to 49**
3. after pruning, i want to test or retrain the model. And i modify the [test.py](https://github.com/open-mmlab/mmdetection/blob/6cf9aa1866b745fce8f1da6717fdb833d7c66fab/tools/test.py#L187), just use torch.load to get the model, 
```
    # build the model and load checkpoint
    # model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
      model = torch.load('./after_pruned_model.pth')
      fp16_cfg = cfg.get('fp16', None)
```
and modify config/__base__/default_runtime.py to [load_from](https://github.com/open-mmlab/mmdetection/blob/6cf9aa1866b745fce8f1da6717fdb833d7c66fab/configs/_base_/default_runtime.py#L14) the pruned checkpoint 
```
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = './after_pruned_checkpoint.pth'
resume_from = None
workflow = [('train', 1)]
```

> python ./tools/test.py configs/xxxx.py ./after_pruned_checkpoint.pth --eval bbox --out result.pkl

**But always get dimension error messages** Like 
> lib/python3.7/site-packages/mmcv/cnn/bricks/conv_ws.py", line 106, in _get_weight.py", line 106, in _get_weight
    weight = self.weight_gamma * weight + self.weight_beta
RuntimeError: The size of tensor a (64) must match the size of tensor b (49) at non-singleton dimension 0

The original number of channels is 64, and 49 is my modified number of channels. I can be sure that the model and checkpoint have been modified correctly. 
I wonder whether my processing flow is correct, or I can only **manually define the network in config**  rather modifying the trained **model.pth**.
Sincerely hope to get a reply  @jshilong @RangiLyu

**Comment by hhaAndroid** [comment]
@syswyl It seems that you did not prune the `weight_gamma` and `weight_beta` channel causing an error.

**Comment by syswyl** [comment]
``> @syswyl It seems that you did not prune the `weight_gamma` and `weight_beta` channel causing an error.

well, i've done that.  
```
def prune_bn(bn_layer, index):
    bn_layer.weight.data = bn_layer.weight.data[index]
    bn_layer.running_mean = bn_layer.running_mean[index]
    bn_layer.running_var = bn_layer.running_var[index]
    bn_layer.bias.data = bn_layer.bias.data[index]
    bn_layer.num_features = len(index)
```
and after prune, The backbone network structure of my model is as follows(show the prime layers)

> conv1 torch.Size([49, 3, 7, 7])
> bn1 torch.Size([49])
> layer1.0.conv1 torch.Size([51, 49, 1, 1])
> layer1.0.bn1 torch.Size([51])
> layer1.0.conv2 torch.Size([62, 51, 3, 3])
> layer1.0.bn2 torch.Size([62])
> layer1.0.conv3 torch.Size([224, 62, 1, 1])
> layer1.0.bn3 torch.Size([224])
> layer1.0.downsample.0 torch.Size([224, 49, 1, 1])
> layer1.0.downsample.1 torch.Size([224])

> DetectoRS_ResNet(
  (conv1): ConvAWS2d(3, 49, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(49, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): ResLayer(
    (0): Bottleneck(
      (conv1): ConvAWS2d(49, 51, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(51, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): ConvAWS2d(51, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(62, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): ConvAWS2d(62, 224, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(224, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): ConvAWS2d(49, 224, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(224, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )

Are there any other problems with the handling method？ @hhaAndroid

**Comment by syswyl** [comment]
> @syswyl It seems that you did not prune the `weight_gamma` and `weight_beta` channel causing an error.

oooh , i got it, thanks when i print the checkpoint's weights, those parameters are indeed not modified
 **thanks ~**

**Comment by xuhao-anhe** [comment]
> > @syswyl It seems that you did not prune the `weight_gamma` and `weight_beta` channel causing an error.
> 
> oooh , i got it, thanks when i print the checkpoint's weights, those parameters are indeed not modified **thanks ~**

你好，可以分享一下剪枝的经验吗，代码可以分享一下吗

**Comment by syswyl** [comment]
@xuhao-anhe 您好，其实基于mmdet这一套剪枝的话不是很方便，我的实现是首先用内置的模型加载方式，然后再直接torch.save之后，套用一些开源的剪枝算法，没有特别的操作。如果是这个框架可以用mmlab自己的[mmrazor](https://github.com/open-mmlab/mmrazor/blob/master/README_zh-CN.md)试试。其他通用的torch模型的话建议试试微软的[nni](https://github.com/microsoft/nni)支持的model还是比较多的，使用也方便。如果是yolo系列的话可以看看[yolov3-channel-and-layer-pruning](https://github.com/tanluren/yolov3-channel-and-layer-pruning)，以及相关的repo

**Comment by Audrey528** [comment]
@syswyl Do you meet the question when you use nni pruning model of training by mmdetection?
![1655359468(1)](https://user-images.githubusercontent.com/68552295/174002480-8aeea50b-01ce-4bea-ba71-5688296a1ee9.png)

**Comment by syswyl** [comment]
@Audrey528 hi, That's because mmlab's model requires ****data** to be constructed during input, so directly used `dummy_input = torch.ones (1,3,224,224)` will cause errors. 
You can consider modifying its forward function by referring to the onnx export requirements
[link](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/tools/deployment/pytorch2onnx.py#L79)
`model.forward = partial(model.forward, img_metas={}, return_loss=False)`
[torchtoonnx](https://github.com/open-mmlab/mmclassification/blob/master/tools/deployment/pytorch2onnx.py#L79)
In essence, it is a forward problem.I forgot how to solve it accurately, but the solution is like this
