### ISSUE TITLE
change gn to bn and increase batch size but got worse result?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmdetection#6515]
Hi,

I change GN to BN in `bbox_head` (https://github.com/open-mmlab/mmdetection/blob/master/configs/atss/atss_r50_fpn_1x_coco.py#L24), and increase the batch size per gpu to 16. But got much worse result than GN.

in theory it should be better than GN (https://arxiv.org/abs/1803.08494).

any idea?

**Comment by RangiLyu** [comment]
ATSS using shared heads between multi-level feature maps. It is not suitable for BN because each BN runs `num_level` times in each forward. So the moving average mean and std may be inaccurate during inference.

**Comment by RangiLyu** [comment]
You can refer to mmdet/models/dense_heads/retina_sepbn_head.py to use SepBN to solve this problem.

**Comment by twmht** [comment]
@RangiLyu 

make sense.

but what is `num_ins` in that head (https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/retina_sepbn_head.py#L41) ?

**Comment by twmht** [comment]
ok. make sense.

I would try that and report the result here.

**Comment by twmht** [comment]
sep bn head works. now it's comparable with GN.
