### ISSUE TITLE
mmdet/datasets/custom.py error？？？？

### ISSUE THREAD

**Issue by jiangxinufo** [open-mmlab/mmdetection#6517]
![image](https://user-images.githubusercontent.com/53360080/141938891-dd1478a0-13cd-4ff8-9b02-86e9abaf6729.png)

**Comment by jiangxinufo** [comment]
Img_info there can be no [' width '] and [' height '],what???

**Comment by jiangxinufo** [comment]
![image](https://user-images.githubusercontent.com/53360080/141939508-f60ccae5-c5e1-46b4-bfdb-61ae8c28605d.png)

**Comment by hhaAndroid** [comment]
Please use the issue template to facilitate our investigation

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 15 days.
