### ISSUE TITLE
Question about DCNv1 v2 on resnet

### ISSUE THREAD

**Issue by Fyzjym** [open-mmlab/mmdetection#6519]
hi, I want to add DCNv1 and DCNv2 to resnet50, but an error occurred during the training process.
Are there any examples of successfully joining dcn (for example, image classification network).
Thank you for reading and look forward to your reply.

> /opt/conda/conda-bld/pytorch_1591914895884/work/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**Comment by AronLin** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/tree/master/configs/dcn and modify the configs of the backbone like it.

**Comment by Fyzjym** [comment]
Ok, thanks. sir :D
