### ISSUE TITLE
loss在训练过程中变为nan

### ISSUE THREAD

**Issue by zhanghang-cv** [open-mmlab/mmdetection#6520]
不加数据增强可以正常训练，但是加入了数据增强后，第一个epoch训练过程中loss会变为nan，是什么情况呢，感谢帮忙答疑

**Comment by zhanghang-cv** [comment]
> 不加数据增强可以正常训练，但是加入了数据增强后，第一个epoch训练过程中loss会变为nan，是什么情况呢，感谢帮忙答疑

数据集使用的是 我们自己的数据集

**Comment by AronLin** [comment]
You can check whether the gt after data enhancement is normal and whether there is a division by zero error during training.

**Comment by bluebabylan** [comment]
我猜测可能有这么几点原因：
1. loss的问题，换别的loss
2. 学习率的问题，把学习率调小一点
3. numpy版本的问题，升级numpy

按照你目前的策略来训练，也许你不加数据增强，也会出现nan，只是出现的早与晚的问题，或者你换个随机种子，就可能提前出现了，我猜测应该不是数据增强的问题
