### ISSUE TITLE
Enable same class nested BBox

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6522]
I have a custom dataset where is common to have nested/overlapped bounding box of the same class.

Example of my custom dataset ground truth BBox:
![image](https://user-images.githubusercontent.com/11663917/142013238-1f62b538-5f40-4f31-8387-dfc0a764351d.png)

I guess for most net, the per class non maxima suppresion will get rid of those heavily overlapped boxes, right ? 
(in coco for example it's rare to have a cat within a cat, I read somewhere is some a non maxima suppression for this issue)

Is there a settting or a file I could modify to enable same class nested Bounding box prediciton ?

**Comment by AronLin** [comment]
No, but maybe you can change the `iou_threshould` of `nms` to increase the boxes left.

**Comment by PeterVennerstrom** [comment]
In the example shown no boxes would be filtered by nms at typical iou thresholds.  While the top right box is completely inside the large box, the denominator for iou includes the rest of the large box so the iou for the pair of boxes is still relatively small.
