### ISSUE TITLE
Is it possible to use mmdet with cuda on Windows?

### ISSUE THREAD

**Issue by andrearosasco** [open-mmlab/mmdetection#6524]
I've tried to install everything again and again but it keeps saying that some stuff is not compiled with GPU support.

**Comment by AronLin** [comment]
Do you have any specific error messages? Most errors may occur when compiling MMCV. If it is an MMCV error, you can create an issue in MMCV.

**Comment by andrearosasco** [comment]
Nope, no error during the compilation. I install pytorch with cuda support and install the rest with mim. I can run eveything without error if I set device='cpu', but if I set it to cuda I get the error above or `No CUDA runtime is found, using CUDA_HOME=`.
I have CUDA 11.1 installed and CUDA_HOME correctly points to its location.

**Comment by AronLin** [comment]
You can use `torch.is_cuda_available()` to check whether your Torch matches your CUDA.

**Comment by andrearosasco** [comment]
Yes, `torch.cuda.is_available() ` returns True and the torch package I've installed ('torch 1.8.0+cu111') matches with my system cuda (CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1).

I just tried to follow the installation procedure described in the Colab example [here](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb).

I had to change these lines in `setup.py`
```
    # parse installment mode
    if 'develop' in sys.argv:
        # installed by `pip install -e .`
        mode = 'symlink'
    elif 'sdist' in sys.argv or 'bdist_wheel' in sys.argv:
        # installed by `pip install .`
        # or create source distribution by `python setup.py sdist`
        mode = 'copy'
    else:
        return
```

to 
`mode = 'copy'`
since symlink isn't supported on windows and the installation was successful.

The error I get when I try executing the demo now is:
```
Traceback (most recent call last):
  File "C:/Users/arosasco/PycharmProjects/mmdetection/demo/webcam_demo.py", line 7, in <module>
    from mmdet.apis import inference_detector, init_detector
  File "C:\Users\arosasco\PycharmProjects\mmdetection\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\Users\arosasco\PycharmProjects\mmdetection\mmdet\apis\inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "C:\Users\arosasco\.conda\envs\openmmlab\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "C:\Users\arosasco\.conda\envs\openmmlab\lib\site-packages\mmcv\ops\assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "C:\Users\arosasco\.conda\envs\openmmlab\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\arosasco\.conda\envs\openmmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.
```

This time it doesn't work neither with CUDA nor with the CPU.

**Comment by AronLin** [comment]
It seems that there is still a problem when MMCV compiles `ops`.
You can try to install the pre-compiled version of MMCV.

**Comment by andrearosasco** [comment]
Ok thanks, I'll try that. This is the pre-compiled one, right?
`pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html`

**Comment by AronLin** [comment]
Maybe you can create an issue in MMCV, rhey may have dealt with this kind of problem

**Comment by andrearosasco** [comment]
Yes I've looked up the link https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html and it contains just wheels for linux. I guess I'll have to build it somehow. I opened an issue there too, thanks.

**Comment by andrearosasco** [comment]
Ok I'm compiling mmcv from source as, from my understanding, it's the only way to have it on Windows. I think we can close the issue, I'll open a more specific one would I run into some other problem.
I think it might be useful to add to the mmdet installation guide a Windows section that points [here](https://mmcv.readthedocs.io/en/latest/get_started/build.html#build-on-windows) for compiling mmcv. Thanks for your help :)
