### ISSUE TITLE
AttributeError: 'ClassBalancedDataset' object has no attribute 'evaluate'

### ISSUE THREAD

**Issue by besawe** [open-mmlab/mmdetection#6535]
Model training break after finishing first epoch for not being able to evaluate since 'ClassBalancedDataset' has no 'evaluate' method defined. How are we supposed to train model and do evaluation after each epoch with 'ClassBalancedDataset' enabled?

**Comment by RangiLyu** [comment]
Sorry, the val dataset does not support dataset wrappers.
