### ISSUE TITLE
TypeError: _bbox_forward() missing 1 required positional argument: 'rois'

### ISSUE THREAD

**Issue by zhanghang-cv** [open-mmlab/mmdetection#6538]
Detector设置为cascade时，调用test_mixins.py中的simple_test_bboxes，发现bbox_results = self._bbox_forward(x, rois)，缺少satge参数。而cascade_roi_head.py中函数定义如下def _bbox_forward(self, stage, x, rois)。这个该怎么办呢，感谢答疑。

**Comment by RangiLyu** [comment]
`CascadeRoIHead` overwrites the `simple_test`, it should not use the `simple_test_bboxes` in `test_mixins`. How did you use the CascadeRoIHead?
