### ISSUE TITLE
why the relu is not inplace in fused_semantic_head?

### ISSUE THREAD

**Issue by destinyzs** [open-mmlab/mmdetection#654]
RT. This [line](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/mask_heads/fused_semantic_head.py#L56). In my opinion,  'F.interpolate' function will build a new tensor, and this tensor is not used in other places, so i think there is no need to set 'inplace = False' (which will create a new tensor).

**Comment by hellock** [comment]
If you have tried `inplace=True`, you should see an exception raised. There are other inplace [operations](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/mask_heads/fused_semantic_head.py#L92) in the forward method.

**Comment by destinyzs** [comment]
I haven't tried it yet, thanks for your reply.
BTW, i employed a similar method in my another work, and i implement as follows, it seems to be no errors, but maybe a little rough...
```
mask_x = self.convs[0](feats[0]) + \
	self.convs[1](F.interpolate(feats[1], scale_factor=2, mode='bilinear', align_corners = True)) + \
	self.convs[2](F.interpolate(feats[2], scale_factor=4, mode='bilinear', align_corners = True)) + \
	self.convs[3](F.interpolate(feats[3], scale_factor=8, mode='bilinear', align_corners = True)) + \
	self.convs[4](F.interpolate(feats[4], scale_factor=16, mode='bilinear', align_corners = True))
```
`relu` in `self.convs` is inplace.
