### ISSUE TITLE
About the application of pipeline

### ISSUE THREAD

**Issue by k2580** [open-mmlab/mmdetection#6541]
Hello.
I am planning to apply a pipeline including albumentation during training.
Will this pipeline be applied only once before training?
Or is it applied every epoch?

**Comment by RangiLyu** [comment]
The pipeline is applied every time when loading an image from the dataset.

**Comment by k2580** [comment]
Thank you for your answer.
Am I correct in understanding that the dataset is loaded for each epoch?

**Comment by k2580** [comment]
> The pipeline is applied every time when loading an image from the dataset.

Thank you for your answer.
Am I correct in understanding that the dataset is loaded for each epoch?

**Comment by CharlesNJ** [comment]
@k2580 Thanks for asking, I have the same question. What do you think about creating the augmented images once and then feeding that for training?

**Comment by k2580** [comment]
> The pipeline is applied every time when loading an image from the dataset.

@RangiLyu 
Thank you for your answer.
Am I correct in understanding that the dataset is loaded for each epoch?

**Comment by RangiLyu** [comment]
> > The pipeline is applied every time when loading an image from the dataset.
> 
> @RangiLyu Thank you for your answer. Am I correct in understanding that the dataset is loaded for each epoch?

yes
