### ISSUE TITLE
Clean unnecessary custom_imports in entrypoints

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection#6543]
As MMCV already supports `custom_imports` since PR https://github.com/open-mmlab/mmcv/pull/606. The entrypoints in MMDet no longer need to handle the custom_imports manually. The codes like below should be cleaned.
https://github.com/open-mmlab/mmdetection/blob/c76ab0eb3c637b86c343d8454e07e00cfecc1b78/tools/train.py#L94-L96

**Comment by FloydHsiu** [comment]
Hi, @RangiLyu can I work on this issue?

**Comment by RangiLyu** [comment]
> Hi, @RangiLyu can I work on this issue?
Sure! Welcome to open a PR!
