### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection#6544]
**Describe the feature**
Include new openmmlab projects in readme

**Motivation**
As MMFlow has been released, we should include it in our READMEs of both English & Chinese versions.

**Related resources**
See example in https://github.com/open-mmlab/mmflow#projects-in-openmmlab

**Additional context**
N/A

**Comment by AndreaPi** [comment]
I could lend a hand with the English version!

**Comment by ZwwWayne** [comment]
Thank you @AndreaPi . Sorry, we missed your message and it has been added. Will let you know if we need help in the future.
