### ISSUE TITLE
How to implement multi-detection heads in config file?

### ISSUE THREAD

**Issue by DerekRay** [open-mmlab/mmdetection#6548]
**Describe the issue**
I want to design different detection heads to locate different kind objects. But one detection head only locate only one kind object.
For example, in FCOS, default COCO dataset provided, I want to design two detection heads. One head is gonna to locate Person, the other is gonna to locate car. And final evaluation is computed together. How should I do in FCOS config file?

**Comment by BIGWangYuDong** [comment]
Hi, It seems that we do not support your requirement. Because only one bbox head can build in FCOS. If you want to build two head in one detector, maybe you can change the code in single_stage.py. 
https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/models/detectors/single_stage.py#L35-L37

**Comment by DerekRay** [comment]
> Hi, It seems that we do not support your requirement. Because only one bbox head can build in FCOS. If you want to build two head in one detector, maybe you can change the code in single_stage.py.
> 
> https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/models/detectors/single_stage.py#L35-L37

Thanks! I'm trying to do that.

**Comment by alaa-shubbak** [comment]
Hello , I am still little bit confused , what shall i do between those three lines (35 till 37)?

can you please explain it to me. 

in case i want two heads , not one .. shall i do it like this ? 

```

bbox_head.update(train_cfg=train_cfg) 
bbox_head.update(train_cfg=train_cfg) 
 bbox_head.update(test_cfg=test_cfg) 
 bbox_head.update(test_cfg=test_cfg) 
 self.bbox_head = build_head(bbox_head) 

```

should i update another parts in the code? can you please share with me so codes?

**Comment by alaa-shubbak** [comment]
hello , I am also interested in that 



> 

is his config correct?

**Comment by GeorgePearse** [comment]
I'm also interested in this.
