### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by BEAR787** [open-mmlab/mmdetection#6549]
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

How to solve it?

**Comment by BIGWangYuDong** [comment]
1. This sounds as if the JIT would kick in and compile the CUDA kernels for your architecture, which seem to be missing from the used binary.
2. How did you install/build PyTorch and which GPU are you using?

Once 1. is solved, this might also be fixed.

Similar error in [PyTorch Discuss](https://discuss.pytorch.org/t/cublas-status-execution-failed-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/116740)

**Comment by rootYan** [comment]
I guess maybe your gpu  memory is not enough 
you can try run your code on one bigger gpu device or small you mode
