### ISSUE TITLE
SGD优化器的定义在哪个文件里呀？如何把它改成Adam呢？

### ISSUE THREAD

**Issue by 19970326liu** [open-mmlab/mmdetection#6551]
optimizer = dict(type='SGD', lr=0.001, momentum=0.9, weight_decay=0.0001)
这个SGD的定义在哪个文件里呀？想换成Adam怎么换呀

**Comment by hhaAndroid** [comment]
@19970326liu  `optimizer = dict(type='Adam', lr=0.001, weight_decay=0.0001)`

**Comment by 19970326liu** [comment]
> 我换了之后报了如下图片里的错误，这个怎么解决呀？

![图片](https://user-images.githubusercontent.com/46146061/142954575-02dde1e2-adc1-4164-a00f-7cbd46d9a1f7.png)

**Comment by 19970326liu** [comment]
@hhaAndroid 辛苦帮忙看看

**Comment by hhaAndroid** [comment]
@19970326liu It has nothing to do with adam.
