### ISSUE TITLE
Exporting model to ONNX  throws error "object has no attribute 'onnx_export'"

### ISSUE THREAD

**Issue by CanyonWind** [open-mmlab/mmdetection#6552]
Hi, I am trying to export K-net panoptic segmentation model to onnx. And it shows an error for 
```
'ConvKernelHead' object has no attribute 'onnx_export'
```
This `ConvKernelHead` module is implemented [here](https://github.com/ZwwWayne/K-Net/blob/6aa30b870902d8904af41a14f68d8e9ace4ffb58/knet/det/kernel_head.py#L12), and has been registered into `HEADS` registry. Could anyone please guide me on what I should do to make it exportable? Thanks a lot!

**Comment by hhaAndroid** [comment]
@CanyonWind In order to export the model, you need to implement your own onnx_export method in the head, you can refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/base_dense_head.py#L354

**Comment by CanyonWind** [comment]
Got it. Thanks for the example, I will take a look at it.
