### ISSUE TITLE
Enable again setting random seed and Deterministic=True from the config file

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6553]
**Describe the feature**

**Motivation**
Currently, it's not possible to set the random seed and the option Deterministic=True from the config file, but only from args (see https://github.com/open-mmlab/mmdetection/issues/6322). This is extremely inconvenient: in order to reproduce the training run at a later time, one has to store the CLI launch command _together_ with the config file! It would easier to reproduce experiments if we could set these parameters in the config file.

**Related resources**
Code [here](https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/tools/train.py#L146-L152) shows that in the current implementation, a seed specified in the config file will be overwritten by `args.seed`, which is set to `None` if no seed is passed as an argument. This makes effectively impossible to set the seed through the config file.

**Comment by hhaAndroid** [comment]
@AndreaPi Thank you for your feedback. If you feel there is a need to configure settings, please create a PR to improve it.

**Comment by AndreaPi** [comment]
@hhaAndroid I cannot install all the MMDetection testing harness on my system. I could write a PR, but you would have to support me with the CI/CD pipeline on your side.

**Comment by AndreaPi** [comment]
@hhaAndroid as you see, I wrote a PR, but there seems to be some issue with integrating it. Could you please have a look and help me fix it?

**Comment by hhaAndroid** [comment]
> @hhaAndroid as you see, I wrote a PR, but there seems to be some issue with integrating it. Could you please have a look and help me fix it?

ＯＫ

**Comment by rusmux** [comment]
@hhaAndroid Are there any updates on this?
