### ISSUE TITLE
mmdetection-master$ ./tools/dist_train.sh configs/deformable_detr/deformable_detr_twostage_refine_r50_16x2_50e_coco.py 1

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmdetection#6554]
`mmdetection-master$ ./tools/dist_train.sh configs/deformable_detr/deformable_detr_twostage_refine_r50_16x2_50e_coco.py 1`
 I set GPU:1, but it still runs on GPU:2, and how to set argument with multiple GPUs of distributed train?

**Comment by hhaAndroid** [comment]
@Williamlizl  You can set `CUDA_VISIBLE_DEVICES`.

**Comment by Williamlizl** [comment]
> @Williamlizl You can set `CUDA_VISIBLE_DEVICES`.

I solve other problems and then install mmdet again, all works well. thanks
