### ISSUE TITLE
Bug crash when "sampler" is not in `train_cfg`

### ISSUE THREAD

**Issue by qingswu** [open-mmlab/mmdetection#6555]
https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/models/dense_heads/anchor_head.py#L84

After recent commits, even `'sampler'` is not in `train_cfg`, the first `hasattr` condition will always be met for an `addict.Dict` (and `train_cfg.sampler` will be an empty dict `{}`, and it will crash on calling `self.train_cfg.sampler.type`.

**Comment by RangiLyu** [comment]
What config did you use? The line `hasattr(self.train_cfg, 'sampler')` should be False when 'sampler' is not set in the cfg.

**Comment by qingswu** [comment]
```
>>> import addict; a = addict.Dict(); print(hasattr(a, 'b'), addict.__version__)
True 2.3.0
```
I also tried `addict==2.4.0`

**Comment by qingswu** [comment]
> What config did you use? The line `hasattr(self.train_cfg, 'sampler')` should be False when 'sampler' is not set in the cfg.

```
>>> import addict; a = addict.Dict(); print(hasattr(a, 'b'), addict.__version__)
True 2.3.0
```
I also tried `addict==2.4.0`

**Comment by RangiLyu** [comment]
When the train_cfg is a ConfigDict object, it is correct.
```python
>>> print(type(self.train_cfg))
<class 'mmcv.utils.config.ConfigDict'>

>>> print(hasattr(self.train_cfg, 'sampler'))
False

>>> print(self.train_cfg)
{'assigner': {'type': 'mmdet.MaxIoUAssigner', 'pos_iou_thr': 0.7, 'neg_iou_thr': 0.3, 'min_pos_iou': 0.3, 'match_low_quality': True, 'ignore_iof_thr': -1}, 'allowed_border': -1, 'pos_weight': -1, 'debug': False}

```

When it is an `addict.Dict` object, `hasattr` will always return true:
```python
>>> import addict; a = addict.Dict()
>>> print(hasattr(a, 'sampler'))
True

```

**Comment by RangiLyu** [comment]
When will the `train_cfg` become an `addict.Dict()` object instead of a `mmcv.utils.config.ConfigDict` object? Any use case?

**Comment by qingswu** [comment]
> When will the `train_cfg` become an `addict.Dict()` object instead of a `mmcv.utils.config.ConfigDict` object? Any use case?

found the issue due to my own modifications, closing the issue. Thanks!
