### ISSUE TITLE
how to ensemble instance segmentation models

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6559]
Hi,

I would like to ensemble the results of multiple instance segmentation models. Ensembling results is trivial for **semantic** segmentation models, but I don't know how to do it for instance segmentation models. Could you point me to some relevant repository (better) or to some paper? I know this repository

https://github.com/ZFTurbo/Weighted-Boxes-Fusion

but this allows the ensembling of **object detection** models, instead of instance segmentation models.

**Comment by jshilong** [comment]
Hi, sorry for the late respondence, I was involved in another project last week.
About the ensemble of instance segmentation, you may refer to the ensemble of multistage masks in cascade_mask_rcnn, the code is here
https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/models/roi_heads/cascade_roi_head.py#L439

**Comment by AndreaPi** [comment]
Thanks, I'll look into it.
