### ISSUE TITLE
Why when I train with multiple GPUs get almost same ETA  as with one GPU?

### ISSUE THREAD

**Issue by 137996047** [open-mmlab/mmdetection#656]
one GUP 
`python tools/train.py ./configs/sign_mask_rcnn_r101_fpn_1x_anchor_lr.py`

four GUPs   
`CONFIG=./configs/sign_mask_rcnn_r101_fpn_1x_anchor_lr.py ` 
`GPUS=4 `
`python -m torch.distributed.launch --nproc_per_node=$GPUS ./tools/train.py $CONFIG`

I get the ETA almost same : 4 days, but I don't know what caused it.

` # dataset settings`
![image](https://user-images.githubusercontent.com/30762967/57863324-75b1ee00-782c-11e9-82c2-8e30aa344cda.png)

**Comment by Epiphqny** [comment]
> one GUP
> `python tools/train.py ./configs/sign_mask_rcnn_r101_fpn_1x_anchor_lr.py`
> 
> four GUPs
> `CONFIG=./configs/sign_mask_rcnn_r101_fpn_1x_anchor_lr.py `
> `GPUS=4 `
> `python -m torch.distributed.launch --nproc_per_node=$GPUS ./tools/train.py $CONFIG`
> 
> I get the ETA almost same : 4 days, but I don't know what caused it.
> 
> ` # dataset settings`
> ![image](https://user-images.githubusercontent.com/30762967/57863324-75b1ee00-782c-11e9-82c2-8e30aa344cda.png)

hello, i have the same problem, have you solved it?

**Comment by freshn** [comment]
Same problem occurs here. Anyone know the reason?
