### ISSUE TITLE
Waiting time is too long between two epochs.

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmdetection#6561]
Hi, 
I am reproducting one detection model using mmdet v2.3.  
My config is modified to `evaluation = dict(interval=10, metric='bbox')`, so I just eval coco result every 10 epochs.
However, I found the waiting time between each two epoch is too long (looks like it is still evaluating valset!).
Is this common?
The log is shown as following:
![image](https://user-images.githubusercontent.com/23122139/142806959-baef8bcf-bc29-4301-8574-636fb3d2d63b.png)

**Comment by jshilong** [comment]
It is a known problem ，you can change to IterBasedRunner or set persistent work for data loader if your Pytorch version > 1.9

**Comment by Senwang98** [comment]
Thanks for your reply.
