### ISSUE TITLE
Result wrong when Fcos model convert to tensorrt in fp16 mode.

### ISSUE THREAD

**Issue by jiejie1993** [open-mmlab/mmdetection#6564]
TorchVision: 0.7.0
OpenCV: 4.5.3
MMCV: 1.3.17
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.2
MMDetection: 2.18.1+c76ab0e

When Fcos model convert tensorrt not in fp16 mode, the result is right:
`Not equal to tolerance rtol=0.001, atol=1e-05
The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the exported ONNX model is problematic.
(shapes (96, 5), (95, 5) mismatch)
 x: array([[8.482639e+01, 3.473854e+02, 1.173454e+02, 3.846374e+02,
        6.540170e-01],
       [1.858925e+02, 1.993301e+02, 2.043786e+02, 2.202240e+02,...
 y: array([[8.482641e+01, 3.473855e+02, 1.173454e+02, 3.846374e+02,
        6.540173e-01],
       [1.858925e+02, 1.993301e+02, 2.043786e+02, 2.202240e+02,...`

When Fcos model convert tensorrt in fp16 mode,the result is different from onnx model.
`The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the exported ONNX model is problematic.
(shapes (96, 5), (97, 5) mismatch)
 x: array([[8.482639e+01, 3.473854e+02, 1.173454e+02, 3.846374e+02,
        6.540170e-01],
       [1.858925e+02, 1.993301e+02, 2.043786e+02, 2.202240e+02,...
 y: array([[5.502793e+01, 2.728699e+02, 1.446555e+02, 3.893784e+02,
        9.597778e-03],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,...
`

**Comment by jshilong** [comment]
Would you mind taking a look at this issue? 
@RunningLeon

**Comment by RunningLeon** [comment]
@jiejie1993 Hi, as is shown: `The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the exported ONNX model is problematic.`
 You could compare drawn predictions and evaluate models with `https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/test.py`

**Comment by jiejie1993** [comment]
I have tested using the python script. The model converted in fp32 mode can detect object right, but the model converted in fp16 mode can not detect even one object. As is shown above, the max confidence in detecting result is  9.597778e-03, which is much lower than the default threadhold 0.3

**Comment by RunningLeon** [comment]
@jiejie1993 Maybe the values are out of range for FP16 in some layers. Better to check it.
