### ISSUE TITLE
ImportError: cannot import name 'init_random_seed' from 'mmdet.apis' (/mmdetection/mmdet/apis/__init__.py)

### ISSUE THREAD

**Issue by kirkzZ** [open-mmlab/mmdetection#6565]
ImportError: cannot import name 'init_random_seed' from 'mmdet.apis' (/mmdetection/mmdet/apis/__init__.py)

**Comment by hhaAndroid** [comment]
@kirkzZ Please re-install mmdet, it may be that the code is modified but not re-installed.

**Comment by hoseinCode** [comment]
hi when i write command: from mmflow.apis import init_random_seed, set_random_seed, train_model google colab shows error message as:
ImportError: cannot import name 'init_random_seed' from 'mmflow.apis' (/usr/local/lib/python3.10/dist-packages/mmflow/apis/__init__.py)

**Comment by ealerbaby** [comment]
Do you solve the problem?

**Comment by dotlla** [comment]
I have the same problem, anyone solve it?

**Comment by Ancuy** [comment]
I also encountered the same problem

**Comment by deepalchemist** [comment]
`from mmengine.runner import set_random_seed`
