### ISSUE TITLE
训练YOLOX的时候报错

### ISSUE THREAD

**Issue by shenwenxiao** [open-mmlab/mmdetection#6566]
![QQ图片20211123103312](https://user-images.githubusercontent.com/48246620/142963402-62434274-b5e2-4c09-8e40-dffd652a5a5f.jpg)
使用mmdet训练YOLOX的时候报错，数据集为visdrone，重新启动训练后再过几个epoch依然报错。平均10个epoch报错一次。请问这个怎么解决呢？
yolox要300个epoch，datatime时间也很长，GPU利用率很低，这些因素加起来训练一次YOLOX要四天，但是往往10几个epoch就会断掉，每天也就能训练20几个epoch，这个问题不解决的话训练一次要半个月。。。。。

**Comment by hhaAndroid** [comment]
@shenwenxiao It seems to be out of bounds. It is recommended that you use small data to reproduce first to facilitate troubleshooting.
