### ISSUE TITLE
Some questions about recovery training

### ISSUE THREAD

**Issue by sanmulab** [open-mmlab/mmdetection#6568]
For example, I used two cards to train to 9epoch, and then interrupted myself. Then I used three cards to resume the training, and the training was interrupted to 19epoch. At this time, the network was disconnected, and finally I continued to resume the training. As a result, he started from 9epoch. Shouldn't he start to recover from 19epoch? Anyway, the info message printed says that the parameters change because of the number of GPUs.
I found that as long as the number of GPUs trained is changed halfway, the resume-from instruction cannot take effect. It cannot be recovered from the latest model, but from the first interruption
翻译：举个例子：我用两张卡训练到9epoch，然后自己中断，接着我用三张卡恢复训练，训练到19epoch，此时因为断网又中断了，最后我继续恢复训练，结果他从第9epoch开始，正常不是应该19epoch开始恢复吗？反正打印的info信息说参数变化，因为GPU数量。
我发现，只要中途改变了训练的GPU数量，resume-from指令就不能生效了，不能从最近的模型开始恢复，而是从第一次中断那里开始

**Comment by hhaAndroid** [comment]
@chensen668 This issue needs further confirmation, please use the issue template.

**Comment by chensen668** [comment]
I just don't quite understand why changing the number of GPUs will make it impossible for me to resume training from the recent model. epoch1_ 8. pth (2 GPUs training), epoch9_ 18. pth(3 GPUs training). Finally, I resumed training and started with epoch9. Have I ever had this problem?
