### ISSUE TITLE
yolox_s的模型比较小，m太大，是否有中间大小建议参数？

### ISSUE THREAD

**Issue by yulinhuyang** [open-mmlab/mmdetection#6569]
**Describe the feature**

yolox_s

    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),

yolox_m

backbone=dict(deepen_factor=0.67, widen_factor=0.75),

是否可以提供一组建议参数，模型大小在s-m之间。当前m太大，使用s,训练ap略有点低，想增大一下模型，但是比m要小一些。

**Comment by hhaAndroid** [comment]
@yulinhuyang Sorry, we didn’t study this part either.

**Comment by xubiao-ui** [comment]
Hello, why do I use yolox model very slowly?

**Comment by hhaAndroid** [comment]
@xubiao-ui Please post the training log and explain the modification.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 8 days.
