### ISSUE TITLE
Why training starts with extremely high accuracy?

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmdetection#657]
```
2019-05-17 13:18:50,651 - INFO - Epoch [1][50/32058]	lr: 0.00199, eta: 13 days, 10:51:24, time: 0.755, data_time: 0.018, memory: 5706, loss_rpn_cls: 0.4750, loss_rpn_reg: 0.0318, loss_cls: 0.1646, acc: 96.1250, loss_reg: 0.0419, loss_mask: 0.8765, loss: 1.5897
2019-05-17 13:19:29,251 - INFO - Epoch [1][100/32058]	lr: 0.00233, eta: 13 days, 14:24:12, time: 0.772, data_time: 0.015, memory: 5706, loss_rpn_cls: 0.1524, loss_rpn_reg: 0.0362, loss_cls: 0.1496, acc: 96.0703, loss_reg: 0.0888, loss_mask: 0.6807, loss: 1.1078
```
As you can see, the accuracy is almost 100% at the start. Why?

**Comment by hellock** [comment]
Most are negative samples.

**Comment by yxchng** [comment]
@hellock So this is normal?

**Comment by hellock** [comment]
Yes

**Comment by lingchen1991** [comment]
> Most are negative samples.

Maybe I have a misunderstanding.

But I think the ratio of positive and negative samples should be 50:50？

**Comment by PanJianning** [comment]
> > Most are negative samples.
> 
> Maybe I have a misunderstanding.
> 
> But I think the ratio of positive and negative samples should be 50:50？

![image](https://user-images.githubusercontent.com/15498988/78850003-a30d1900-7a48-11ea-83c9-90cad7b82c65.png)

The `MaxIoUAssigner` will  assigned bboxes as postive, negitive or ignored samples according to the iou setting. Then,  the `RandomSampler` will sample some bboxes for training according to the assign result. 

`Num=256` means it will sample 256 samples, `pos_fracion=0.5` means it will `TRY` to make pos:neg=`1:1`. But more often than not, there are not enough positive bboxes. (here, we need 128), so the actual ratio MAY BE something like `2:256`.

**Comment by lingchen1991** [comment]
> > > Most are negative samples.
> > 
> > 
> > Maybe I have a misunderstanding.
> > But I think the ratio of positive and negative samples should be 50:50？
> 
> ![image](https://user-images.githubusercontent.com/15498988/78850003-a30d1900-7a48-11ea-83c9-90cad7b82c65.png)
> 
> The `MaxIoUAssigner` will assigned bboxes as postive, negitive or ignored samples according to the iou setting. Then, the `RandomSampler` will sample some bboxes for training according to the assign result.
> 
> `Num=256` means it will sample 256 samples, `pos_fracion=0.5` means it will `TRY` to make pos:neg=`1:1`. But more often than not, there are not enough positive bboxes. (here, we need 128), so the actual ratio MAY BE something like `2:254`.

Well noted! Thanks for your kindly explanation!
