### ISSUE TITLE
How to train HTC semantic head with only specific classes?

### ISSUE THREAD

**Issue by douxwombat** [open-mmlab/mmdetection#6571]
Hey there. Thanks a lot for the great work.

I'm trying to train `HTC fused semantic head` with specific 163 classes only amongst 183 cocostuff classes.
I've already changed the `num_classes` in the config. (In my case, I'm trying to train 71/91 things and and all the rest stuffs classes so the total `num_classes` is set to `163`.)
https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/configs/htc/htc_r50_fpn_1x_coco.py#L16
I've found that the line below generates the conv network for the mask prediction. **But how would I set specific classes?** -which classes to train or not- (e.g. in COCO, CLASSES to be trained can be set in mmdet/datasets/coco.py)
https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/models/roi_heads/mask_heads/fused_semantic_head.py#L85
I don't want to change the dataset itself(e.g. removing annotations of specific classes or sth). Is there a possible way?

**Comment by douxwombat** [comment]
@hhaAndroid Hope I can get any tips or answers from you :D

**Comment by mitming** [comment]
> Hey there. Thanks a lot for the great work.
> 
> I'm trying to train `HTC fused semantic head` with specific 163 classes only amongst 183 cocostuff classes. I've already changed the `num_classes` in the config. (In my case, I'm trying to train 71/91 things and and all the rest stuffs classes so the total `num_classes` is set to `163`.)
> 
> https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/configs/htc/htc_r50_fpn_1x_coco.py#L16
> 
> 
> I've found that the line below generates the conv network for the mask prediction. **But how would I set specific classes?** -which classes to train or not- (e.g. in COCO, CLASSES to be trained can be set in mmdet/datasets/coco.py)
> https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/models/roi_heads/mask_heads/fused_semantic_head.py#L85
> 
> 
> I don't want to change the dataset itself(e.g. removing annotations of specific classes or sth). Is there a possible way?

Have you solved it?
