### ISSUE TITLE
I am a researcher of Microsoft Research Institute. When I was in train and loading data, the following error occurred. I sincerely look forward to your reply

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#6575]
the  error  is 
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

**Comment by hhaAndroid** [comment]
@xianglei3 Can you use the issue template? We can troubleshoot it easily？
