### ISSUE TITLE
Images of each classes

### ISSUE THREAD

**Issue by ccedar** [open-mmlab/mmdetection#6579]
I trained faster rcnn with 3 classes, upper, lower, and total. I can see the result image with these 3 boxes together in one image. I wanna see the result image with one class. I mean, the result image just have one class. For example, I have result images with 3 boxes upper, lower, and total. But, I want the result image with only upper class. Could it be possible?

**Comment by AronLin** [comment]
Yes, you can modify the results returned by our detector.
The result returned by the detector is a list, the length of the list is `num_classes`. Each element contains the bboxes and labels of this class, so what you need to do is to extract the results of the class you need and wrapper them to a new list.
