### ISSUE TITLE
Scaling with num of gpus

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#6581]
When training with multiple gpus, the effective batch-size scales accordingly, aka when `samples_per_gpu = 2`, using 2 gpus means the batch size becomes 4. To get similar training performance, people usually follow the linear scaling rule, may I know if `mmdetection` will automatically scale the learning rates accordingly or we will have adjust it ourselves?

**Comment by AronLin** [comment]
You need to modify it by yourself in the config files.
