### ISSUE TITLE
Add face detection model

### ISSUE THREAD

**Issue by dreamflasher** [open-mmlab/mmdetection#6590]
**Describe the feature**
I'd love to do face detection with mmdet.

**Motivation**
Currently we use https://github.com/deepinsight/insightface/, but we already use mmdet, so it would be quite awesome if you add face detection to your toolset. 

**Additional context**
We will train a RetinaNet with mmdet and are happy to provide the trained model. What's needed on your side for integration?

**Comment by RangiLyu** [comment]
Thanks for your interest! It would be great if you can open a PR to provide the model. 
There are some notices: 
- 1. The model should be reproducible. It means that the model should be trained with an open dataset such as WIDER Face. 
- 2. Configs and training logs are also required. 
Once the PR is approved by reviewers, we will upload the pre-trained model to our host.
