### ISSUE TITLE
直接检测图像

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#6591]
很抱歉询问这个问题。
我阅读了使用mmdetection的教程。但是有提到如何使得mmdetection直接检测没有标注结果的图像吗？例如我在使用mask rcnn训练后如何使用模型直接在图像上或者视频上进行检测呢？（不是test数据集）

**Comment by RangiLyu** [comment]
https://github.com/open-mmlab/mmdetection/tree/master/demo

**Comment by kankanzheli** [comment]
尝试video demo发生以下错误：
  File "/home/zhaowentao/Visual/mmdetection/demo/video_demo.py", line 50, in main
    cv2.namedWindow('video', 0)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-f51eratu/opencv/modules/highgui/src/window.cpp:1257: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

**Comment by BIGWangYuDong** [comment]
Seems that you are not installed the environment successfully.

**Comment by kankanzheli** [comment]
还想要询问一下，控制输出的文件是哪一个呢？比如我使用mask-rcnn。但是输出结果包含了实力分割结果和一个边界框。
我想要对其中的边界框数据进行处理。

**Comment by BIGWangYuDong** [comment]
I cannot get your point, more informations are needed

**Comment by kankanzheli** [comment]
就是我想要实现这样一个检测目标。就是在运行mask-rcnn后会得到实例分割和对应物体的边界框的结果。我想要通过判断两者的边界框是否存在重合来判断两者是否相连。

**Comment by kankanzheli** [comment]
大致应该怎么做呢？
