### ISSUE TITLE
norm_eval = True, from scratch

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6593]
the file in `/config/scratch/*.py` (https://github.com/open-mmlab/mmdetection/blob/master/configs/scratch/faster_rcnn_r50_fpn_gn-all_scratch_6x_coco.py) inherit `norm_eval=True` for the backbone. I think it should be set to `norm_eval=False` when training from scratch, in order to correctly train the BN, right ?

**Comment by RangiLyu** [comment]
This model uses GN instead of BN. GN does not have running_mean or running_var.
