### ISSUE TITLE
请问FP16训练速度的问题解决了吗

### ISSUE THREAD

**Issue by nmszt55** [open-mmlab/mmdetection#6594]
https://github.com/open-mmlab/mmdetection/issues/4476
这边FasterRCNN训练FP32和FP16的速度基本是一样的。A100显卡

**Comment by BIGWangYuDong** [comment]
Hi, in mmdet, it is set fp32 during calculating losses, and only models will set to fp16. So it will not speed up the training speed. If you want to speed up during training your models, it is suggested make batch-size larger.
