### ISSUE TITLE
ImportError: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by guanbin1994** [open-mmlab/mmdetection#66]
ImportError: /home/l547/anaconda3/lib/python3.7/site-packages/mmdet-0.5.1+810b711-py3.7.egg/mmdet/ops/nms/gpu_nms.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

**Comment by softmicro929** [comment]
i guess your make op is not success.

**Comment by guanbin1994** [comment]
> i guess your make op is not success.

please describe it more clearly,thanks!

**Comment by qiangruoyu** [comment]
Can you solve this error?How?

**Comment by guanbin1994** [comment]
I have solved this issue.
my pyTorch version is not suit for my CUDA version.
We should use correct pyTorch version with CUDA.
do not directly use: conda install pytorch
we should look at https://pytorch.org/

**Comment by karthiksn** [comment]
Posting this here, since no clear solution was outlined. Without further looking into details of why this is the case, I've found that certain combinations of pytorch and CUDA versions cause this to occur. E.g., I've found that pytorch 0.4.1 + cuda 9.0 works. Steps:

(1) Install cuda 9.0 with the runfile; update your path if needed
(2) Confirm that nvcc --version reads cuda 9.0.
(3) Install pytorch 0.4.1 - I used "conda install pytorch=0.4.1 cuda90 -c pytorch"
(4) Go to mmdetection/ and do ./compile.sh.
(5) Re-run things to see whether this works.

**Comment by ujsyehao** [comment]
Hi, my environment:
- cuda9.0
- pytorch 1.1
- mmdetection 0.6
However, I still encountered the problem.

**Comment by ivder** [comment]
I got the same error 
```
(open-mmlab) ivan@geolux:~/mmdetection$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Sun_Nov_19_03:10:15_CST_2017
Cuda compilation tools, release 9.0, V9.0.252
(open-mmlab) ivan@geolux:~/mmdetection$ conda list |grep cuda
cudatoolkit               9.0                  h13b8566_0
pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
```
I guess my CUDA and pytorch version are matched

**Comment by ivder** [comment]
Successfully removed the error by reinstalling pytorch following these commands 
```
conda uninstall pytorch
conda uninstall pytorch-nightly
conda uninstall torch
codna uninstall torchvision
because torchvision 0.3.0 has problem,
then:
conda install -c pytorch pytorch-nightly torchvision cudatoolkit=9.0
pip install torchvision==0.2.2
```

**Comment by dragen1860** [comment]
I encountered this problem when using `cuda 9.0, pytorch 1.1, mmcv=0.4.3`. When i change to `pytorch 1.2 with cuda 10.0, python 3.7`, it disappeared!
I guess the problem may due to python version. Remember to  `rm build ` folder before install again.
