### ISSUE TITLE
what will happen if a gtbox's size is exceeding the image's size 

### ISSUE THREAD

**Issue by zhb654069015** [open-mmlab/mmdetection#660]
I wonder if there is a gtbox like this[-1,-1,100000,100000] (It has a negative Xmin or Ymin)
What will the model do to handle it.
Do nothing or ignore it or other ways?

**Comment by hellock** [comment]
It will be clipped to fit the image shape.

**Comment by zhb654069015** [comment]
Thanks a lot.
But in my dataset,the RoIs are not clipped into the limitation of the image boundaries,as there are many full body bouding boxes extented out of images.Where should I go to change the code in order to let it not clip my gtbox.
I try to find it myself but I cant't do it.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/transforms.py#L82

**Comment by zhb654069015** [comment]
Thanks for your patient reply~
