### ISSUE TITLE
How to resize gt-bbox when using RandomAffine for evaluating COCO val-set

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmdetection#6603]
Hi, @RangiLyu 
I meet the following question:

**[Background]**
I am reproducting `NanoDet-m-0.5x` based on `mmdet2`. In official NanoDet code, you get resize_warpAffine_matrix first to resize the image when evaluating COCO val-set. To align the inference results with provided checkpoint weights, I must done the same thing as you do.

**[My solution]**
I using the following config to try to reproduct:
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(320, 320),
        flip=False,
        transforms=[
            # dict(type='Resize', keep_ratio=False),
            dict(type='RandomAffine', max_rotate_degree=0, max_translate_ratio=0, scaling_ratio_range=(1, 1), max_shear_degree=0, \
                border_val=(0, 0, 0),min_bbox_size=0,min_area_ratio=0,max_aspect_ratio=20000),
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            # dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```
However, I found that alough I have get the image I wanted, the corresponding gt bboxs are not resized.
If I don't use your checkpoint, and I train from scratch. the final COCO mAP is 13.0.
In `RandomAffine` when test period, the `bbox_fields` is not exist, so what should I do.

**Comment by jshilong** [comment]
Ping @RangiLyu

**Comment by Senwang98** [comment]
@jshilong 
I am not sure if mmdet can use `dict(type='LoadAnnotations', with_bbox=True),` in `test_pipeline`?
I have tested this class, mmdet can't use LoadAnnotations in test_pipeline.
I feel so strange that `Resize` function resize image but do not resize gt-bbox at the same time(because we can't get gt-bbox when test), how to keep inference accuracy?

The following config is my test_pipeline:
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    # dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(320, 320),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

**Comment by RangiLyu** [comment]
There is no need to use RandomAffine during test. Just use Resize

**Comment by Senwang98** [comment]
@RangiLyu 
Sorry for disturb, my param and gflops are the same as your nanodet, but the final mAP is 13.0 with data aug when training.
If I use `RandomAffine ` and `PhotoMetricDistortion` when training, the final mAP is lower than 12.5.
I have no idea about how to reproduct your nanodet based on mmdet2.

**Comment by RangiLyu** [comment]
As I know, the resize method will not influence the performance so much.
