### ISSUE TITLE
TP, FP, FN

### ISSUE THREAD

**Issue by shaodong-ai** [open-mmlab/mmdetection#6606]
hi, I'm using mask rcnn. How can I get the total TP, FP, FN in every epoch's validate when I training it. thanks

**Comment by jshilong** [comment]
You need to read the source code of `evaluate` function of CocoDataset.  https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/datasets/coco.py#L513

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
