### ISSUE TITLE
yolox的权重什么时候出来

### ISSUE THREAD

**Issue by Bigtuo** [open-mmlab/mmdetection#6609]

**Comment by Jack-Hu-2001** [comment]
yolox论文中好像说是从头开始训练效果更好吧...不过如果你要先大数据集预训练之后finetune减少开销的话你也可以让官方帮你在COCO上面训练一下或者提供一下之前代码团队的训练结果checkpoint？

**Comment by Bigtuo** [comment]
从头训练是加载类似darknet53这种权重吗，还是从0开始，那没有预训练权重的话，会不会很难收敛（训练自己的小数据集）



---原始邮件---
发件人: "Jack ***@***.***&gt;
发送时间: 2021年11月29日(周一) 上午8:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmdetection] yolox的权重什么时候出来 (Issue #6609)




 
yolox论文中好像说是从头开始训练效果更好吧...不过如果你要先大数据集预训练之后finetune减少开销的话你也可以让官方帮你在COCO上面训练一下或者提供一下之前代码团队的训练结果checkpoint？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jack-Hu-2001** [comment]
我印象中读论文是大数据集上从0开始，不过小数据集我觉得最好还是你去弄个预训练权重吧。如果你算力足够自己去下个COCO训练好了再在小数据集上面用，不行的话就只能考虑让mmlab官方提供（按道理来说应该有的，之前社区看到过yolox自己实现对接精度啥的过程）或者求助别人了，我算力也不太行。

**Comment by Bigtuo** [comment]
谢谢你的回复，我电脑只是2070，重新训练的话时间太久了，而且在mmdet里batchsize只能开4。



---原始邮件---
发件人: "Jack ***@***.***&gt;
发送时间: 2021年11月29日(周一) 上午9:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmdetection] yolox的权重什么时候出来 (Issue #6609)




 
我印象中读论文是大数据集上从0开始，不过小数据集我觉得最好还是你去弄个预训练权重吧。如果你算力足够自己去下个COCO训练好了再在小数据集上面用，不行的话就只能考虑让mmlab官方提供（按道理来说应该有的，之前社区看到过yolox自己实现对接精度啥的过程）或者求助别人了，我算力也不太行。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhaAndroid** [comment]
@Bigtuo Weights will be released soon

**Comment by clw5180** [comment]
> @Bigtuo Weights will be released soon

请问我可以把YOLOX官方的pth权重直接转成mmdetection的pth格式来用么？

**Comment by Bigtuo** [comment]
yoloxs已经有了，在config中下载



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月2日(周四) 中午1:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmdetection] yolox的权重什么时候出来 (Issue #6609)




  
@Bigtuo Weights will be released soon
  
请问我可以把YOLOX官方的pth权重直接转成mmdetection的pth格式来用么？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by clw5180** [comment]
> eights will be released soon

主要是想用l和x版本

**Comment by Bigtuo** [comment]
我看到官方有个回复是能给出转换代码，你可能需要找官方人员要



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月2日(周四) 晚上7:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmdetection] yolox的权重什么时候出来 (Issue #6609)




  
eights will be released soon
  
主要是想用l和x版本
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by clw5180** [comment]
> 你

可以问下链接在哪里么

**Comment by Bigtuo** [comment]
mmdetection/configs/yolox的下面，他们将tiny换成了yoloxs预训练权重



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月2日(周四) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [open-mmlab/mmdetection] yolox的权重什么时候出来 (Issue #6609)




  
你
  
可以问下链接在哪里么
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
