### ISSUE TITLE
How to modify the training pipeline such that it can optionally train mask head only when mask annotation is available?

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmdetection#661]
How to modify the training pipeline such that it can optionally train mask head only when mask annotation is available, i.e. if mask annotation is present, train bounding box and mask heads. If it is absent, train only bounding box.

Is that possible?

**Comment by hellock** [comment]
Of course that is possible, you need to modify the dataset and two stage detector. Before that you may need to have a basic understanding of the code.
