### ISSUE TITLE
MMDetection Installation in clear steps for CPU only

### ISSUE THREAD

**Issue by Kanhaiya042** [open-mmlab/mmdetection#6612]
Hi, 

I could not install MMDetection for only CPU as steps are not mentioned very clearly.

![image](https://user-images.githubusercontent.com/94110163/143799249-7aa48fcb-cbd8-4588-b93b-83dd591cd476.png)
<img width="577" alt="InstallWith" src="https://user-images.githubusercontent.com/94110163/143799250-72faa409-578e-460b-bf9b-2c9a6fadb869.PNG">

**Comment by hhaAndroid** [comment]
@Kanhaiya042 In fact, we do not recommend using mmdet only with cpu. Currently only part of the model inference supports CPU only.
