### ISSUE TITLE
swin_transformer的backbone预训练权重版本问题

### ISSUE THREAD

**Issue by sunny-sjj** [open-mmlab/mmdetection#6613]
请问有没有swin_transformer的backbone版本为torch1.5以下的权重，我使用的是torch1.4的版本，发现在加载预训练权重的时候，会报torch的版本太低的问题，导致无法加载权重，

**Comment by jshilong** [comment]
Sorry, we do not prepare the checkpoint of that version, why not update your Pytorch?

**Comment by sunny-sjj** [comment]
enn, I'm using an older version of MMDetection(1.)， version mismatches can occur if i use a higher version of PyTorch, but I am solving these problems, Thanks

**Comment by 2324773711** [comment]
请问您是怎么解决的，有低版本的预训练权重吗？
