### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by coder-ww** [open-mmlab/mmdetection#6617]
thanks for your great open source work:)
when i train yolox based on mmdet on my own custom dataset with my exp file which just modify the dataset setting(classes, data_root, and batchsize), i meet this issue:
![Screenshot from 2021-11-29 12-18-55](https://user-images.githubusercontent.com/34940871/143808497-1653957d-a12e-415c-b24f-bf5422b322df.png)
I thought there was something wrong with my dataset format, so i trained the yolox offical version on this dataset with the same parameters(batchsize = 16, lr = 0.01), it worked and archieve great mAP. my gpu is a single 3090, i can't understand why it will OOM when batchsize is 1*16. However, i set the batchsize = 1*8, the same problem happened again...
but, when i start to train, nvidiasmi shows that the cost of GPU memory is just about 2G...
![Screenshot from 2021-11-29 12-34-10](https://user-images.githubusercontent.com/34940871/143809469-c9ff678d-cef3-4231-8824-0c2b74473491.png)
besides, there is the other error happened at the same time, it seems that something wrong in label assignment, but i can't know how to debug, could you help me, SOS = =. 
![bug](https://user-images.githubusercontent.com/34940871/143811156-539222ee-c12f-45eb-bac2-8527d26280b7.jpg)

Any help will be appreciated!

**Comment by coder-ww** [comment]
i have check the label, just two classes,the value is only 0 and 1

**Comment by Sharpiless** [comment]
这个通常是产生了nan导致数组越界，可以通过如下方式定位nan出现的位置：

```python
with torch.autograd.detect_anomaly():
    loss.backward()
```

一般来说是分母为0或者exp的值过大导致的
