### ISSUE TITLE
How can I concatenate couple of datasets?

### ISSUE THREAD

**Issue by hyq12358** [open-mmlab/mmdetection#6618]
There're a couple of datasets, however each dataset only contains a few of classs, how can I concatenate them together?
For example:
dataset1: ["apple", "banana"]
dataset2: ["bottle"]
dataset3: ["tv", "laptop"]

I want to build a detector to detect things all the above but I can't modify the annotation file. 
Dataset is coco-format, category id may be the same among these datasets.
. What should I do?

**Comment by jshilong** [comment]
You can use https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html?highlight=dataset#concatenate-dataset
Please make sure the category index of each annotation file is consistent.
For example apple 1, banana 2, bottle 3, tv 4
