### ISSUE TITLE
can you give me a sample train&test with syncbn?

### ISSUE THREAD

**Issue by notfox** [open-mmlab/mmdetection#662]
thank you

**Comment by hellock** [comment]
You can just refer to the GN configs and replace GN with SyncBN. It is not very stable now and we are studying that.

**Comment by gasvn** [comment]
> You can just refer to the GN configs and replace GN with SyncBN. It is not very stable now and we are studying that.

I followed the GN configs to use SyncBN. But the loss suddenly became nan during the last 1000 iters in epoch 12. Have you encountered this problem?

**Comment by hellock** [comment]
We have not come across the nan loss issue when adopting syncbn.
