### ISSUE TITLE
YOLO series

### ISSUE THREAD

**Issue by jaideep11061982** [open-mmlab/mmdetection#6626]
Hi,
Why each Yolo version refer to Yolo S file  and also 
```
_base_ = './yolox_s_8x8_300e_coco.py'

# model settings
model = dict(
    backbone=dict(deepen_factor=0.67, widen_factor=0.75),
    neck=dict(in_channels=[192, 384, 768], out_channels=192, num_csp_blocks=2),
    bbox_head=dict(in_channels=192, feat_channels=192),
```
)

2) Inside Yolo S file , model type is YoloX.. 
instead of YoloS

```
model = dict(
    type='YOLOX',
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=80, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    # In order to align the source code, the threshold of the val phase is
    # 0.01, and the threshold of the test phase is 0.001.
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))
```

**Comment by RangiLyu** [comment]
The folder `configs/yolox` contains the algorithm YOLOX with different sizes. YOLOX is the algorithm name, the `s` in `YOLOX-s` is size.

**Comment by jaideep11061982** [comment]
can you help in how to use Yolo here. 

secondly , is it possible to use the Yolo with mask_Rcnn.That is usin Yolo instead of faster rcnn

**Comment by jshilong** [comment]
> can you help in how to use Yolo here.
> 
> secondly , is it possible to use the Yolo with mask_Rcnn.That is usin Yolo instead of faster rcnn

You can refer to the method named [Yolact](https://github.com/open-mmlab/mmdetection/tree/master/configs/yolact)

**Comment by jaideep11061982** [comment]
@jshilong is it for images or videos. My requirement is to instance seg for Images

**Comment by jshilong** [comment]
1. For images
2. You can not combine them by only modifying configs, you need to spend some time coding by referring to yolact
