### ISSUE TITLE
How to customize faster-rcnn model?

### ISSUE THREAD

**Issue by sjytker** [open-mmlab/mmdetection#6627]
I want to accelerate my faster-rcnn model in certain application, by modifying its way of generating anchor. Specifically, I don't generate anchor for every pixel, instead, I just need to generate at a few certain pixels.

Since mmdetection is highly modular, it's very hard for me to find out function such as "anchor_target_layer" or "region_proposal". Where can I find these, or what should I do?

**Comment by jshilong** [comment]
We test this 
` by modifying its way of generating anchor. Specifically, I don't generate anchor for every pixel, instead, I just need to generate at a few certain pixels.`
before, but it does not obviously improve the inference speed, you can try it with `sparse_priors` of prior_generator

**Comment by sjytker** [comment]
> We test this ` by modifying its way of generating anchor. Specifically, I don't generate anchor for every pixel, instead, I just need to generate at a few certain pixels.` before, but it does not obviously improve the inference speed, you can try it with `sparse_priors` of prior_generator

Would you please specify how to localize the code of region proposal, or how to use this function?
