### ISSUE TITLE
about overfitting

### ISSUE THREAD

**Issue by NEUdeep** [open-mmlab/mmdetection#6628]
I am doing an experiment on surface defect detection. The average image input size is about 224. How much should the input size of the model be set at this time?
I found that with (1333,800) training, 800-1000 multi-scale testing, the mAP has decreased, dcn,mixup,albu,swa same too, I'm very confused. and do you find that if the mmdetection framework exceeds the default epoch, it is very easy to have over-fitting?

**Comment by hhaAndroid** [comment]
@NEUdeep First of all, you have to confirm whether it is overfitting. If you use too much enhancement, then you may need more epochs.
