### ISSUE TITLE
dynamic head 

### ISSUE THREAD

**Issue by zkloveai** [open-mmlab/mmdetection#6634]
《Dynamic Head: Unifying Object Detection Heads with Attentions》
a novel detection head, called dynamic head, to unify scale-awareness, spatial-awareness, and task-awareness all together.
I can't reimplement it. I hope someone can do this. thanks a lot!!!!

**Comment by hhaAndroid** [comment]
@zkloveai The source code is open, are you interested in reproducing it in mmdet ?

**Comment by zkloveai** [comment]
yes.I only use mmdet ~ hope
