### ISSUE TITLE
How to build multiple necks and dense_heads?

### ISSUE THREAD

**Issue by hyq12358** [open-mmlab/mmdetection#6637]
I noticed that mmdetection seems not support build multiple necks and dense_heads.(Please correct me if I'm wrong)
How can I do that?
For example, I want to build one neck and head to detect person, and another neck and head to detect car.

**Comment by hhaAndroid** [comment]
@hyq12358 This is supported. Please refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/libra_rcnn/libra_faster_rcnn_r50_fpn_1x_coco.py#L4

**Comment by alexarsenault** [comment]
Any updates on this issue? Also interested in a multi-headed network

**Comment by hhaAndroid** [comment]
We have plans to provide a demo, but are still thinking about which task to choose? do you have any suggestion？ @alexarsenault @hyq12358

**Comment by hanchangdong** [comment]
> 

hi, do you have the demo now. 
I want to merge my three different models (label all three datasets is quite time-consuming) with a multi-headed network (one head only calculate the loss when image is belong to its task).
thks

**Comment by hanchangdong** [comment]
> We have plans to provide a demo, but are still thinking about which task to choose? do you have any suggestion？ @alexarsenault @hyq12358

hi, do you have the demo now.
I want to merge my three different models (label all three datasets is quite time-consuming) with a multi-headed network (one head only calculate the loss when image is belong to its task).
thks

**Comment by alexarsenault** [comment]
@hhaAndroid I'd like to see a demo where you have multiple heads with unique anchor box characteristics designated for different classes and how the loss function would need to be updated to support that.

**Comment by apollo910** [comment]
I have same request. Looking forward the related multi-task feature to be supported by mmdetection.
