### ISSUE TITLE
Any plans for support NAS-FPN?

### ISSUE THREAD

**Issue by Wulingtian** [open-mmlab/mmdetection#664]

**Comment by hellock** [comment]
**Please use English for raising issues, or at least use both.**

As for your question, we have not successfully reproduced the results in the paper. We may support NAS-FPN in the future, but it is not urgent.

**Comment by yangJirui** [comment]
I also tried to reproduce Nas-FPN with mmdetection (based on RetinaNet)....but failed.
But we succeed in Faster-RCNN (with tensorflow...)

**Comment by hellock** [comment]
Updates on 30/6: We will support NAS-FPN soon.

**Comment by hellock** [comment]
#1246
