### ISSUE TITLE
MMDet Tutorial not working on Colab

### ISSUE THREAD

**Issue by rogargon** [open-mmlab/mmdetection#6641]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
MMDet Tutorial no working on Colab.

**Reproduction**

1. What command or script did you run?

Followed the link to open the tutorial on Colab. Then tried to run the cells starting from the top. However, the cell that is checking mmcv installation fails with error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-fad1b02c85b9> in <module>()
      8 
      9 # Check mmcv installation
---> 10 from mmcv.ops import get_compiling_cuda_version
     11 print(get_compiling_cuda_version())
     12 print(get_compiler_version())

3 frames
/usr/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ImportError: /usr/local/lib/python3.7/dist-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z27points_in_boxes_cpu_forwardN2at6TensorES0_S0_
---------------------------------------------------------------------------
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
 
The issue might be related with Colab using now CUDA 11.1. Tried to use:
```
!pip install -U torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
 ``` 
However, this didn't solve the issue.

3. What dataset did you use?

None

**Environment**

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by hhaAndroid** [comment]
@rogargon Thank you very much for your feedback, we will fix it as soon as possible.

**Comment by Hihien** [comment]
I've met the same issue, did u resolve it?

**Comment by InukKang** [comment]
Same here with mmdet.datasets..

**Comment by annie2008hi** [comment]
I met the issue:
ImportError: /home/anaconda3/envs/mmseg/lib/python3.6/site-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z27points_in_boxes_cpu_forwardN2at6TensorES0_S0_

I change the version of mmcv-full to 1.3.13, by following command
`pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/{CUDA_VERSION}/{PYTORCH_VERSION}/index.html
`
It solves my problem.

**Comment by wyh196646** [comment]
I've met the same issue！

**Comment by wyh196646** [comment]
I just slove the problem by using   ` pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/{cu110}/{torch1.7.1}/index.html`

**Comment by InukKang** [comment]
> I met the issue: ImportError: /home/anaconda3/envs/mmseg/lib/python3.6/site-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z27points_in_boxes_cpu_forwardN2at6TensorES0_S0_
> 
> I change the version of mmcv-full to 1.3.13, by following command `pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/{CUDA_VERSION}/{PYTORCH_VERSION}/index.html ` It solves my problem.

Solved. Thanks!

**Comment by Hihien** [comment]
> I just slove the problem by using ` pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/{cu110}/{torch1.7.1}/index.html`

i've installed as you suggested, but soon i got the error ''AttributeError: CocoDataset: 'FileClient' object has no attribute 'get_local_path'.'' when I trained my data with faster-rcnn model 
That maybe the old version doesnt have this function. what can I do? Appreciate for all suggestion!!

**Comment by wyh196646** [comment]
> 

I met the same problem ,maybe I just want to abandon this project,I did't found this fuction too.

**Comment by withbrightmoon** [comment]
@Hihien Have you solve this problem? I also meet it when training faster rcnn / mask rcnn models on coco / cityscapes datasets.

**Comment by Hihien** [comment]
> @Hihien Have you solve this problem? I also meet it when training faster rcnn / mask rcnn models on coco / cityscapes datasets.

You should install the lastest version of mmcv, I tried and get an another error: TypeError: CocoDataset: '>=' not supported between instances of 'str' and 'int'.

**Comment by gvalvano** [comment]
Any news on this problem?
