### ISSUE TITLE
How can I do data augmentation to special classes?

### ISSUE THREAD

**Issue by StephenZhao1** [open-mmlab/mmdetection#6642]
My datasets is just like 100 dogs, 10 cats and 20 pigs.But I only want to do do augmentation on cat class and pig class.How can I change the config file.I used mask rcnn for training instance segmentation.Thx a lot.

**Comment by StephenZhao1** [comment]
或者直接对少的类别过采样就可以？请问是先采样再做数据增强还是先做数据增强再采样？

**Comment by hhaAndroid** [comment]
If you consider balancing by sampling, you can use [ClassBalancedDataset](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L211)
