### ISSUE TITLE
[Looking for advice] Overlapped Plant detection problem

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6643]
Thanks for this awesome framework !
I'm currently working on a plant detection problem, with a FasterRCNN architecture.
My dataset annotations are not not perfectly consistent when plants are close to eachother.
![image](https://user-images.githubusercontent.com/11663917/144047462-1f5d8e9b-9990-4e21-8886-dc523fe13e55.png)
(of course, I don't have automatic knowledge whether annotations is type A or type B).
Problematic predictions:
![image](https://user-images.githubusercontent.com/11663917/144051113-26b6c5be-ac7b-485f-89cd-bf2a5683f2c1.png)This inconsistency hurts my model training:
**In prediction type A**, the model get no reward, because it's maximum per object IoU is very low, even though it's prediction is visually okayish. 
**In prediction type B,** the model get no reward, because it's maximum per object IoU is very low, even though it's prediction is visually okayish.

**Non ideal solution 1)**
I could manually re-annotate my groud truth to annotation A all the time, but this is too laborious.
**Non ideal solution 2)**
I could preprocess my dataset to merge al the touching BBox, effectively converting everything to annotation B . 
This is a bad solution because ideally I would like to detect each plant individually.

Do you have another idea how to deal with this problem ? Maybe playing with the **MaxIoUAssigner**, or writing a new loss or using a different architecture ?

**Comment by hhaAndroid** [comment]
@joihn Hi, We have supported crowd detection, you can try it.
