### ISSUE TITLE
./tools/analysis_tools/analyze_logs.py plot_curve  IndexError: list index out of range

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmdetection#6644]
`(openmmlab) lbc@prust-System-3:~/mmdetection-master$ python3.8 ./tools/analysis_tools/analyze_logs.py plot_curve ./work_dirs/deformable_detr_twostage_refine_r50_16x2_50e_coco/20211119_170702.log.json --keys bbox_mAP 
plot curve of ./work_dirs/deformable_detr_twostage_refine_r50_16x2_50e_coco/20211119_170702.log.json, metric is bbox_mAP
Traceback (most recent call last):
  File "./tools/analysis_tools/analyze_logs.py", line 180, in <module>
    main()
  File "./tools/analysis_tools/analyze_logs.py", line 176, in main
    eval(args.task)(log_dicts, args)
  File "./tools/analysis_tools/analyze_logs.py", line 53, in plot_curve
    if metric not in log_dict[epochs[0]]:
IndexError: list index out of range
`

**Comment by zytx121** [comment]
Could you upload your `./work_dirs/deformable_detr_twostage_refine_r50_16x2_50e_coco/20211119_170702.log.json` ?
