### ISSUE TITLE
mAP is nan (loss is normal)

### ISSUE THREAD

**Issue by Runner-2019** [open-mmlab/mmdetection#6658]
Hi, I  want to ask a question , I'm glad if there is one who would help me.

Problem: 
When I used **python tools.test.py configs/xxx.py checkpoints/xxx.pth --eval bbox**, I get the following problem.

![image](https://user-images.githubusercontent.com/59395781/144279380-d864911d-5767-42e8-9ec2-0f284fb646b4.png)
**The AP value of category 8 and 17 are nan**. I don't know how to solve this problem. I'm appreciate if you can help me.

**Comment by RangiLyu** [comment]
Could you check whether the number of objects of those categories is not zero in your dataset?

**Comment by Runner-2019** [comment]
> Could you check whether the number of objects of those categories is not zero in your dataset?

Thank you. I followed your advise and found  the number of 8 and 17 is  zero。 My validation dataset has wrong number。
