### ISSUE TITLE
How to use persistent_workers

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6659]
Hi! 

I'm glad to see that MMDetection now supports `persistent_workers` with PyTorch >=1.7:

https://github.com/open-mmlab/mmdetection/releases/tag/v2.19.0

how do I activate this option? What should I write in the config file? I had a look at the new documentation, but there are no examples using `persistent_workers`, so I'm a bit lost. Any help would be greatly appreciated!

**Comment by hhaAndroid** [comment]
@AndreaPi just follow https://github.com/open-mmlab/mmdetection/blob/master/configs/yolox/yolox_s_8x8_300e_coco.py#L91

**Comment by AndreaPi** [comment]
Wow, that was easy! Thanks a lot, closing the issue now
