### ISSUE TITLE
ImportError: /opt/conda/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z27points_in_boxes_cpu_forwardN2at6TensorES0_S0_

### ISSUE THREAD

**Issue by zhenglongjiepheonix** [open-mmlab/mmdetection#6662]
Thanks for your error report and we appreciate it a lot.

```shell
!pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.9.1/index.html
!pip install mmdet
```

```python
import mmcv
import mmdet
from mmdet.apis import init_detector, inference_detector
```
and then got this error, is this may related with the notebook env

**Comment by bhadreshpsavani** [comment]
I was running the colab notebook provided in the demo directory and got the same error!

**Comment by bhadreshpsavani** [comment]
I checked with `pip install mmcv-full==1.3.17` its seems to be working fine

**Comment by RangiLyu** [comment]
Did you check the python env used in the notebook is correct?

**Comment by zhenglongjiepheonix** [comment]
@bhadreshpsavani solved my problem, seems like a version problem
