### ISSUE TITLE
launch.py: error: argument --nproc_per_node: invalid int value: ''

### ISSUE THREAD

**Issue by yeyujujishou19** [open-mmlab/mmdetection#6664]
**command:**
./tools/dist_train.sh configs/yolox/yolox_x_8x8_300e_coco.py 2

**error:**
launch.py: error: argument --nproc_per_node: invalid int value: ''

Can someone tell me how to solve this problem?

**Comment by ZwwWayne** [comment]
The input arguments are wrong and you should check the doc. https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#test-existing-models
