### ISSUE TITLE
The default value of gt_semantic_seg padding has potential problems

### ISSUE THREAD

**Issue by hhaAndroid** [open-mmlab/mmdetection#6665]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

Since 255 in gt_semantic_seg means ignoring pixels and 0 means effective area, the default value of 0 will be used for padding when to stack a batch which will bring potential bugs.

**Bug fix**
DefaultFormatBundle supports custom padding values.

**Comment by AronLin** [comment]
#6837

**Comment by AronLin** [comment]
The result of panoptic_fpn_r50 is 40.1PQ，it is normal.

**Comment by AronLin** [comment]
The bug was fixed by #6837, it was merged.
