### ISSUE TITLE
Why I can not find mmdetection, configs, or checkpoints folder?

### ISSUE THREAD

**Issue by abcxubu** [open-mmlab/mmdetection#6670]
I have used 'pip install openmim' and 'mim install mmdet' for installation. However, when I wanted to use the Faster RCNN, I cannot find mmdetection, configs, or checkpoints folder. But I found the folder of mmdet, mmdet-2.18.1.dist-info, etc. (as Fig. shows). I don't know how to solve the problem. Could you give me some advice? Thanks.
![捕获](https://user-images.githubusercontent.com/25636252/144429665-6b7cfe1b-22d6-445c-8c5e-83182d7883fc.PNG)

**Comment by TolgaOzdmir** [comment]
It's normal. Openmim just provides the python libraries to run mmdetection. You should download the mmdetection repo on github based on your mmdet version if you want to use configs, etc. Then, you can run the model you want with that repo.

**Comment by abcxubu** [comment]
Thanks so much for your answer. @TolgaOzdmir I will have a try according to your advice.
