### ISSUE TITLE
How to Use MixUp Augmentation?

### ISSUE THREAD

**Issue by WandernForte** [open-mmlab/mmdetection#6673]
I added default dict(type='MixUp') in my train_pipeline but "Assertion Error" occurred.
![image](https://user-images.githubusercontent.com/81891513/144535708-a8fc2d95-c220-46dc-8a20-a6aa18334687.png)
Shall I add other parameters?

**Comment by BIGWangYuDong** [comment]
This is an example using in [YOLOX](https://github.com/open-mmlab/mmdetection/blob/master/configs/yolox/yolox_s_8x8_300e_coco.py):
 ```python
dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
```

**Comment by WandernForte** [comment]
> This is an example using in [YOLOX](https://github.com/open-mmlab/mmdetection/blob/master/configs/yolox/yolox_s_8x8_300e_coco.py):
> 
> ```python
> dict(
>        type='MixUp',
>        img_scale=img_scale,
>        ratio_range=(0.8, 1.6),
>        pad_val=114.0),
> ```

emmm. But I need to use it in cascade......

**Comment by BIGWangYuDong** [comment]
You can change the train pipeline in cascade

**Comment by WandernForte** [comment]
> You can change the train pipeline in cascade

Here's my code:
`from mmcv import Config

cfg = Config.fromfile('/home/working/mmdetection/configs/htc/htc_x101_32x4d_fpn_16x1_20e_coco.py')
albu_train_transforms = [
    dict(type='ShiftScaleRotate', shift_limit=0.0625,
         scale_limit=0.15, rotate_limit=15, p=0.4),
    dict(type='RandomBrightnessContrast', brightness_limit=0.2,
         contrast_limit=0.2, p=0.5),
    dict(
        type="OneOf",
        transforms=[
            dict(type="GaussianBlur", p=1.0, blur_limit=7),
            dict(type="MedianBlur", p=1.0, blur_limit=7),
        ],
        p=0.4,
    ),
]

cfg.train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
       type='MixUp',
       img_scale=(800,1333),
       ratio_range=(0.8, 1.6),
       pad_val=114.0),
    dict(type='Resize', img_scale=[(440, 596), (480, 650), (520, 704), (580, 785), (620, 839)], multiscale_mode='value',
         keep_ratio=True),

    dict(type='RandomFlip', flip_ratio=0.5),
    dict(p=0.5, max_h_size=64, type='Cutout'),

    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='coco',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap=dict(img='image', gt_bboxes='bboxes', gt_masks='masks'),
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(
        type='Normalize',
        mean=[128, 128, 128],
        std=[11.58, 11.58, 11.58],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_masks', 'gt_labels'])
]
cfg.data.train.pipeline = cfg.train_pipeline`


Is there anything Wrong?

**Comment by WandernForte** [comment]
> You can change the train pipeline in cascade

Here's my code:
`from mmcv import Config

cfg = Config.fromfile('/home/working/mmdetection/configs/cascade_rcnn/cascade_mask_rcnn_x101_64x4d_fpn_20e_coco.py')
albu_train_transforms = [
    dict(type='ShiftScaleRotate', shift_limit=0.0625,
         scale_limit=0.15, rotate_limit=15, p=0.4),
    dict(type='RandomBrightnessContrast', brightness_limit=0.2,
         contrast_limit=0.2, p=0.5),
    dict(
        type="OneOf",
        transforms=[
            dict(type="GaussianBlur", p=1.0, blur_limit=7),
            dict(type="MedianBlur", p=1.0, blur_limit=7),
        ],
        p=0.4,
    ),
]

cfg.train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
       type='MixUp',
       img_scale=(800,1333),
       ratio_range=(0.8, 1.6),
       pad_val=114.0),
    dict(type='Resize', img_scale=[(440, 596), (480, 650), (520, 704), (580, 785), (620, 839)], multiscale_mode='value',
         keep_ratio=True),

    dict(type='RandomFlip', flip_ratio=0.5),
    dict(p=0.5, max_h_size=64, type='Cutout'),

    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='coco',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap=dict(img='image', gt_bboxes='bboxes', gt_masks='masks'),
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(
        type='Normalize',
        mean=[128, 128, 128],
        std=[11.58, 11.58, 11.58],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_masks', 'gt_labels'])
]
cfg.data.train.pipeline = cfg.train_pipeline
`


Is there anything Wrong?

**Comment by BIGWangYuDong** [comment]
you can change it in config file, this seems OK
