### ISSUE TITLE
the performance about yoloxs

### ISSUE THREAD

**Issue by miracle-fmh** [open-mmlab/mmdetection#6674]
@hhaAndroid  Thanks for your work.   I find that in your "https://github.com/hhaAndroid/mmdetection/commit/5edbf07518a199b94cd241e5473f8f02b38c3972#diff-dad5a108a20ef343a7ed9e66f16acaafbb1fec47d4955970969042636b9fcc3c" version YOLOXS performance is 40.2. However, I find the laetest version YOLOXS performance is  40.5. What causes the difference?

**Comment by ZwwWayne** [comment]
See notes [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/yolox).
