### ISSUE TITLE
'FileClient' object has no attribute 'get_local_path'

### ISSUE THREAD

**Issue by THEBEST-cloud** [open-mmlab/mmdetection#6675]
‘’‘
my_custom_config.py
’‘’
_base_ = 'mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_coco.py'
dataset_type = 'CocoDataset'
classes = ('pedestrian','people','bicycle','car','van',
    'truck','tricycle','awning-tricycle','bus','motor')
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file='Datasets/VisDrone2019-DET-train/train.json',
        img_prefix='Datasets/VisDrone2019-DET-train/images/'),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file='Datasets/VisDrone2019-DET-val/val.json',
        img_prefix='Datasets/VisDrone2019-DET-val/images/'),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file='Datasets/VisDrone2019-DET-test-dev/test.json',
        img_prefix='Datasets/VisDrone2019-DET-test-dev/images/'))

model = dict(
    roi_head=dict(
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                num_classes=10),
            dict(
                type='Shared2FCBBoxHead',
                num_classes=10),
            dict(
                type='Shared2FCBBoxHead',
                num_classes=10)],
    mask_head=dict(num_classes=10)))

when I  python tools/train.py configs/my_custom_config.py，got this error “CocoDataset:'FileClient' object has no attribute'get_local_path'”

**Comment by BIGWangYuDong** [comment]
Hi, please make sure you have installed the environment successfully. You need to check your mmcv, mmdet, pycocotools version first

**Comment by wyh196646** [comment]
I just installed the environment，i have successfully run the test code on the mmdetection home page,but I meet the same problem.

**Comment by withbrightmoon** [comment]
I also meet the same problem with the environment cuda10.2+python1.7.0. The test code works well.

**Comment by BIGWangYuDong** [comment]
> I also meet the same problem with the environment cuda10.2+python1.7.0. The test code works well.

I'll have a check

**Comment by BIGWangYuDong** [comment]
Please check your mmcv version, and update mmcv to the latest version @withbrightmoon @wyh196646

**Comment by withbrightmoon** [comment]
It looks like the problem is solved with the latest mmcv vesion. Thanks. @BIGWangYuDong @wyh196646 @THEBEST-cloud

**Comment by wyh196646** [comment]
> Please check your mmcv version, and update mmcv to the latest version @withbrightmoon @wyh196646

I installed the latest version ， but annother error shows that  `(open-mmlab) wangyh21@d01:~/assignment/mmtest/mmdetection$ python tools/train.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_voc.py
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmdet.apis import init_random_seed, set_random_seed, train_detector
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: assign_score_withk_forward miss in module _ext`


my cuda version is 11.0，and torch  version is 1.7.1 ,i just try all method to slove the run,but not works. How do  i slove it?

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/pull/6719 avoid get_local_path bc-breaking

**Comment by BIGWangYuDong** [comment]
> > Please check your mmcv version, and update mmcv to the latest version @withbrightmoon @wyh196646
> 
> I installed the latest version ， but annother error shows that `(open-mmlab) wangyh21@d01:~/assignment/mmtest/mmdetection$ python tools/train.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_voc.py Traceback (most recent call last): File "tools/train.py", line 16, in <module> from mmdet.apis import init_random_seed, set_random_seed, train_detector File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 2, in <module> from .inference import (async_inference_detector, inference_detector, File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 7, in <module> from mmcv.ops import RoIPool File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module> from .assign_score_withk import assign_score_withk File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module> '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward']) File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext assert hasattr(ext, fun), f'{fun} miss in module {name}' AssertionError: assign_score_withk_forward miss in module _ext`
> 
> my cuda version is 11.0，and torch version is 1.7.1 ,i just try all method to slove the run,but not works. How do i slove it?

Seems you are not successfully installed mmcv, please check your mmcv version. Also, make sure that you should install `mmcv-full`.
