### ISSUE TITLE
an install error

### ISSUE THREAD

**Issue by fsted** [open-mmlab/mmdetection#6678]
I install mmdet by:
`./home/anaconda3/envs/mm/bin/pip install openmim
mim install mmdet`
but when i import it by:
`from mmdet.apis import init_detector, inference_detector`
It tells me:
AssertionError: MMCV==1.3.18 is used but incompatible. Please install mmcv>=1.1.5, <=1.3.
but my mmdet  version==2.19.0 and MMCV==1.3.18，From the table, there is no conflict  (ㄒoㄒ)
please help me , how i should do?

it is my environment:

_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py37h06a4308_0  
charset-normalizer        2.0.8                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
fonttools                 4.28.2                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0  
giflib                    5.2.1                h7b6447c_0  
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.8.2                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9d                   h7f8727e_0  
kiwisolver                1.3.2                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.6                    pypi_0    pypi
matplotlib                3.5.0                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
mmcv-full                 1.3.18                   pypi_0    pypi
mmdet                     2.19.0                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
ninja                     1.10.2           py37hd09550d_3  
numpy                     1.21.2           py37h20f2e39_0  
numpy-base                1.21.2           py37h79a1101_0  
olefile                   0.46                     py37_0  
opencv-python             4.5.4.60                 pypi_0    pypi
openmim                   0.1.5                    pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
ordered-set               4.0.2                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.4                    pypi_0    pypi
pillow                    8.4.0            py37h5aabda8_0  
pip                       21.2.2           py37h06a4308_0  
pycocotools               2.0.3                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2021.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.26.0                   pypi_0    pypi
setuptools                58.0.4           py37h06a4308_0  
setuptools-scm            6.3.2                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
tabulate                  0.8.9                    pypi_0    pypi
terminaltables            3.1.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
tomli                     1.2.2                    pypi_0    pypi
torchvision               0.6.0                py37_cu101    pytorch
typing-extensions         4.0.1                    pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0

**Comment by BIGWangYuDong** [comment]
I'll build the environment and check it later, I'll reply you later

**Comment by BIGWangYuDong** [comment]
Please check your mmcv version, and update mmcv to the latest version

**Comment by fsted** [comment]
I found the Solution,intsall mmcv-full by conda can used.
