### ISSUE TITLE
Question on Resize

### ISSUE THREAD

**Issue by jaideep11061982** [open-mmlab/mmdetection#6679]
When i see the resize parameters
1)
`    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),` 
If i understand correctly it will resize given image to above shape ?

2)
```python
  type='MultiScaleFlipAug',  # An encapsulation that encapsulates the testing augmentations
        img_scale=(1333, 800),  # Decides the largest scale for testing, used for the Resize pipeline
        flip=False,  # Whether to flip images during testing
        transforms=[
            dict(type='Resize',  # Use resize augmentation
                 keep_ratio=True),
```
what is difference between  simple resize and resize with scale parameter basically here and above

3) My image max size is 520 and 704 . what should i pass for scale in resize  parameter..
4) Can i skip resize if want to train with raw image size ?

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/f08548bfd6d394a82566022709b5ce9e6b0a855e/mmdet/datasets/pipelines/transforms.py#L31-L39
1. The image width and height will match to the given size and keep the original ratio, and then resize the image
2. MultiScaleAugFlip is a Test-time augmentation with multiple scales and flipping.
3. the parameters need to be changed according to your needs. More details can refer to the code. 
4. Yes you can
