### ISSUE TITLE
I want to set the depth of resnet to 18

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6682]
I want to set the depth of resnet to 18.
But it occur the problem: **AssertionError: FasterRCNN: ResNet: Not implemented yet.**
And could you tell me how to reset the **depth** of resnet?

**Comment by RangiLyu** [comment]
Refer to this https://github.com/open-mmlab/mmdetection/blob/f08548bfd6d394a82566022709b5ce9e6b0a855e/configs/ld/ld_r18_gflv1_r101_fpn_coco_1x.py#L11-L19

**Comment by lijoe123** [comment]
And, need i change the **FPN in_channel** just like this?
       
 **type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet18')),
    neck=dict(
        type='FPN',
        in_channels=[64, 128, 256, 512],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5),**

**Comment by lijoe123** [comment]
https://github.com/open-mmlab/mmdetection/blob/f08548bfd6d394a82566022709b5ce9e6b0a855e/configs/ld/ld_r18_gflv1_r101_fpn_coco_1x.py
[https://github.com/open-mmlab/mmdetection/blob/f08548bfd6d394a82566022709b5ce9e6b0a855e/configs/ld/ld_r18_gflv1_r101_fpn_coco_1x.py](url)
`type='ResNet',
depth=18,
num_stages=4,
out_indices=(0, 1, 2, 3),
frozen_stages=1,
norm_cfg=dict(type='BN', requires_grad=True),
norm_eval=True,
style='pytorch',
init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet18')),
neck=dict(
type='FPN',
in_channels=[64, 128, 256, 512],
out_channels=256,
start_level=1,
add_extra_convs='on_output',
num_outs=5),`

**Comment by lijoe123** [comment]
And, need i change the **FPN in_channel** just like this?
https://github.com/open-mmlab/mmdetection/blob/f08548bfd6d394a82566022709b5ce9e6b0a855e/configs/ld/ld_r18_gflv1_r101_fpn_coco_1x.py#L10-L26

**Comment by RangiLyu** [comment]
Yes, the input channels of FPN should also be changed.
