### ISSUE TITLE
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' 

### ISSUE THREAD

**Issue by ningqing123** [open-mmlab/mmdetection#6691]
env:
    pytorch 1.7.0
    cuda10.2.89
    cudnn7.6.5
    mmdet2.19.0
    mmcv-full1.4.0 install use pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.7.0/index.html
    cudtoolkit10.2.89

python tools/test.py
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core'

**Comment by ningqing123** [comment]
So this is because MMDetection V2.10.0 Clean deprecated FP16 API.

**Comment by Lyhour-Chhay** [comment]
I meet the same issue. How to solve this problem ?

**Comment by xiaomi576** [comment]
I meet the same issue. How to solve this problem ?

**Comment by Jazzy0302** [comment]
I meet the same issue. How to solve this problem ?
