### ISSUE TITLE
用自己设定的test_pipeline出现以下报错

### ISSUE THREAD

**Issue by WandernForte** [open-mmlab/mmdetection#6692]
`cfg.test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=False, with_mask=True),
    dict(type='Resize', img_scale=[(440, 596), (480, 650), (520, 704), (580, 785), (620, 839)], multiscale_mode='value', keep_ratio=True),
    dict(
        type='Normalize',
        mean=[128, 128, 128],
        std=[11.58, 11.58, 11.58],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img'])
]`
报错如下
----> 6     result = inference_detector(model, img)
      7     show_result_pyplot(model, img, result)
      8     msk = []

/kaggle/working/mmdetection/mmdet/apis/inference.py in inference_detector(model, imgs)
    113         cfg = cfg.copy()
    114         # set loading pipeline type
--> 115         cfg.data.test.pipeline[0].type = 'LoadImageFromWebcam'
    116 
    117     cfg.data.test.pipeline = replace_ImageToTensor(cfg.data.test.pipeline)

AttributeError: 'dict' object has no attribute 'type'

请问应该如何解决？

**Comment by WandernForte** [comment]
我选择直接改底层代码（

**Comment by YangSN0719** [comment]
@WandernForte 请问您是如何修改的

**Comment by YangSN0719** [comment]
![image](https://user-images.githubusercontent.com/44280931/174000334-8310daab-249b-4d2b-8905-d412197ad376.png)
