### ISSUE TITLE
Occur an error when building mmcv-full 1.4.0

### ISSUE THREAD

**Issue by cppfred** [open-mmlab/mmdetection#6700]
An error occured when openmim is building mmcv 1.4.0 when I use the command below, I'm sure about that openmim was correctly installed before I run this command.
```
mim install mmdet
```
The installation info seems really fine when started:

```
installing mmcv-full from wheel.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://download.openmmlab.com/mmcv/dist/cpu/torch1.1.0/index.html
Collecting mmcv-full==1.4.0
```

And occur error traceback (only a part of) below:
```
  Complete output (1044 lines):
  INFO: Could not find files for the given pattern(s).
  Compiling mmcv._ext without CUDA
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\mmcv
... ...
  creating build\temp.win-amd64-3.6\Release\mmcv\ops\csrc\pytorch
  creating build\temp.win-amd64-3.6\Release\mmcv\ops\csrc\pytorch\cpu
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\fred\AppData\Local\Temp\pip-install-l17amdkj\mmcv-full_c10e03e449b24f0ebaabb9b02acd9b52\mmcv\ops\csrc\common -IC:\Users\fred\anaconda3\envs\pedestron\lib\site-packages\torch\include -IC:\Users\fred\anaconda3\envs\pedestron\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\fred\anaconda3\envs\pedestron\lib\site-packages\torch\include\TH -IC:\Users\fred\anaconda3\envs\pedestron\lib\site-packages\torch\include\THC -IC:\Users\fred\anaconda3\envs\pedestron\include -IC:\Users\fred\anaconda3\envs\pedestron\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tp./mmcv/ops/csrc/pytorch\assign_score_withk.cpp /Fobuild\temp.win-amd64-3.6\Release\./mmcv/ops/csrc/pytorch\assign_score_withk.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /MD
  assign_score_withk.cpp
  C:\Users\fred\anaconda3\envs\pedestron\lib\site-packages\torch\include\c10/util/Exception.h(27): warning C4275: non dll-interface class 'std::exception' used as base for dll-interface class 'c10::Error'
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\vcruntime_exception.h(48): note: see declaration of 'std::exception'
  C:\Users\fred\anaconda3\envs\pedestron\lib\site-packages\torch\include\c10/util/Exception.h(27): note: see declaration of 'c10::Error'
  C:\Users\fred\anaconda3\envs\pedestron\lib\site-packages\torch\include\c10/util/Exception.h(28): warning C4251: 'c10::Error::msg_stack_': class 'std::vector<std::string,std::allocator<std::string>>' needs to have dll-interface to be used by clients of class 'c10::Error'
... ...
  C:\Users\fred\AppData\Local\Temp\pip-install-l17amdkj\mmcv-full_c10e03e449b24f0ebaabb9b02acd9b52\mmcv\ops\csrc\common\pytorch_device_registry.hpp(120): error C2144: syntax error: 'auto' should be preceded by ';'
  C:\Users\fred\AppData\Local\Temp\pip-install-l17amdkj\mmcv-full_c10e03e449b24f0ebaabb9b02acd9b52\mmcv\ops\csrc\common\pytorch_device_registry.hpp(121): error C3861: 'TORCH_CHECK': identifier not found
  C:\Users\fred\AppData\Local\Temp\pip-install-l17amdkj\mmcv-full_c10e03e449b24f0ebaabb9b02acd9b52\mmcv\ops\csrc\common\pytorch_device_registry.hpp(123): error C2143: syntax error: missing ';' before 'return'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
```

**System :**
Windows 10 x64

**Env :**
absl-py==1.0.0
addict==2.4.0
aniso8601==9.0.1
astor==0.8.1
bleach==1.5.0
certifi==2021.5.30
cffi @ file:///C:/ci/cffi_1625831763871/work
chardet==3.0.4
click==7.1.2
colorama==0.4.4
cycler==0.11.0
Cython==0.29.21
dataclasses==0.8
decorator==4.4.2
dill==0.3.4
dominate==2.6.0
Flask==1.1.2
Flask-Bootstrap==3.3.7.1
Flask-RESTful==0.3.8
gast==0.5.3
grpcio==1.42.0
html5lib==0.9999999
idna==2.6
imageio==2.9.0
importlib-metadata==4.8.2
itsdangerous==2.0.1
Jinja2==3.0.3
kiwisolver==1.3.1
Markdown==3.3.6
MarkupSafe==2.0.1
matplotlib==3.2.2
mkl-fft==1.3.0
mkl-random==1.1.1
mkl-service==2.3.0
model-index==0.1.11
multiprocess==0.70.12.2
networkx==2.5.1
numpy==1.18.5
olefile==0.46
opencv-python==4.3.0.36
openmim==0.1.5
ordered-set==4.0.2
packaging==21.3
pandas==1.1.5
pathos==0.2.6
Pillow==7.2.0
pox==0.3.0
ppft==1.6.6.4
protobuf==3.19.1
pycocotools==2.0.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyparsing==3.0.6
python-dateutil==2.8.2
pytz==2021.3
PyWavelets==1.1.1
PyYAML==6.0
redis==3.5.3
regex==2021.11.10
requests==2.18.4
scikit-image==0.17.2
scipy==1.4.1
seaborn==0.10.1
six==1.15.0
tabulate==0.8.9
tensorboard==1.6.0
tensorflow==1.6.0
termcolor==1.1.0
terminaltables==3.1.0
tifffile==2020.9.3
**torch==1.1.0**
**torchvision==0.3.0**
typing_extensions==4.0.1
urllib3==1.22
visitor==0.1.3
Werkzeug==2.0.2
wincertstore==0.2
yapf==0.31.0
zipp==3.6.0

- Pytorch is installed with command: `conda install pytorch-cpu==1.1.0 torchvision-cpu==0.3.0 cpuonly -c pytorch`

**Its my pleasure to get me more info or how to deal with this error from anyone, thx.**

**Comment by cppfred** [comment]
Other wise, when I follow the instruction on [https://mmcv.readthedocs.io/en/latest/get_started/build.html](url) to build a cpu version, the same error I occured.

**Comment by jshilong** [comment]
@zhouzaida Would you mind taking a look at this pr？

**Comment by zhouzaida** [comment]
> Looking in links: https://download.openmmlab.com/mmcv/dist/cpu/torch1.1.0/index.html

It should be https://download.openmmlab.com/mmcv/dist/cpu/torch1.10.0/index.html
