### ISSUE TITLE
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

### ISSUE THREAD

**Issue by kirkzZ** [open-mmlab/mmdetection#6701]
When I want to train with 4 GPUS, I meet this AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

**Comment by jshilong** [comment]
Please use https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh to lunch your program when you want to use multiple gpus
