### ISSUE TITLE
RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.

### ISSUE THREAD

**Issue by godnuan** [open-mmlab/mmdetection#6706]
how to address this error?

D:\tools\anaconda\conda_install\envs\chd\lib\site-packages\mmdet\core\bbox\assigners\max_iou_assigner.py in assign_wrt_overlaps(self, overlaps, gt_labels)
    206             if pos_inds.numel() > 0:
    207                 assigned_labels[pos_inds] = gt_labels[
--> 208                     assigned_gt_inds[pos_inds] - 1]
    209         else:
    210             assigned_labels = None

RuntimeError: Index put requires the source and destination dtypes match, got Long for the destination and Int for the source.

that is so painful..

**Comment by hhaAndroid** [comment]
@godnuan Please use the issue template.

**Comment by godnuan** [comment]
> @godnuan Please use the issue template.

Thank you.The problem has been solved.
Solution: gt_labels[ assigned_gt_inds[pos_inds] - 1].long()

**Comment by levan92** [comment]
Has this been fixed in the latest commits yet?

**Comment by levan92** [comment]
I faced the same error as OP, as well as the following error

```
File "/opt/anaconda3/lib/python3.8/site-packages/mmdet/models/losses/cross_entropy_loss.py", line 162, in mask_cross_entropy
    pred_slice = pred[inds, label].squeeze(1)
IndexError: tensors used as indices must be long, byte or bool tensors
```

This was fixed by the above solution, as well as modifying line 162 of `mmdet/models/losses/cross_entropy_loss.py` from `pred_slice = pred[inds, label].squeeze(1)` to `pred_slice = pred[inds, label.long()].squeeze(1)`

A bit hackish, any long term solution planned? Thank you! 

@hhaAndroid

**Comment by Sere1nz** [comment]
@godnuan Hi, I wonder which file I should modify "gt_labels[ assigned_gt_inds[pos_inds] - 1].long()" on, I dont see it in the runner.py
