### ISSUE TITLE
how to use the plugins in the resnet_34?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6708]
When i use the **plugins** in the **resnet_34** of **mask_rcnn_r34_fpn_2x_coco.py**, but it occur the problem:
**AssertionError: MaskRCNN: ResNet: Not implemented yet.**

**Comment by hhaAndroid** [comment]
@lijoe123 Please make sure `resnet34` has been registered.

**Comment by lijoe123** [comment]
What's that mean? I have trained the resnet34  by my dataset. @hhaAndroid

**Comment by hhaAndroid** [comment]
@lijoe123 Confirm whether resnet34 has been registered in mmdet.
