### ISSUE TITLE
Build mmdet failed on Windows with python3.6

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmdetection#6709]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
```
14:46:57  Installed c:\users\user\miniconda3\envs\mmdetv2.19.0_mmcvv1.4.0_cuda111_py36_torch1.9.0\lib\site-packages\terminaltables-3.1.7-py3.6.egg
14:46:57  Searching for matplotlib
14:46:57  Reading https://pypi.org/simple/matplotlib/
14:46:58  Downloading https://files.pythonhosted.org/packages/78/cf/96af81ef2c15682a020a992cb0f1291bb8ee0b3c296f5cd7978348a72993/matplotlib-3.5.0.tar.gz#sha256=38892a254420d95594285077276162a5e9e9c30b6da08bdc2a4d53331ad9a6fa
14:47:00  Best match: matplotlib 3.5.0
14:47:00  Processing matplotlib-3.5.0.tar.gz
14:47:11  Writing C:\Users\user\AppData\Local\Temp\easy_install-7yj4dwx8\matplotlib-3.5.0\setup.cfg
14:47:11  Running matplotlib-3.5.0\setup.py -q bdist_egg --dist-dir C:\Users\user\AppData\Local\Temp\easy_install-7yj4dwx8\matplotlib-3.5.0\egg-dist-tmp-d6n875vc
14:47:13  error: Setup script exited with 
14:47:13  Beginning with Matplotlib 3.4, Python 3.7 or above is required.
14:47:13  You are using Python 3.6.13.
14:47:13  
```
**Reproduction**

1. What command or script did you run?

```
    CheckMMCV $mmcv
    # Start installation
    pip install -r .\requirements\/build.txt
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Install package failed"
        throw;
    }
    Write-Host "Install build.txt successfully."
    # python setup.py develop
    python setup.py install
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Python setup.py install failed."
        return $LASTEXITCODE
    }
    Write-Host "Install setup.py install successfully."
    pip list
    python setup.py bdist_wheel
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Python setup.py bdist_wheel failed."
        return $LASTEXITCODE
    }
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@del-zhenwu Has this issue been resolved？

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 15 days.
