### ISSUE TITLE
result of coco eval was queer

### ISSUE THREAD

**Issue by banxia1994** [open-mmlab/mmdetection#671]
hi, 
   I train the model with coco dataset. config as original cascade_rcnn_r50_fpn_1x.py
```python
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained='modelzoo://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        use_sigmoid_cls=True),
    bbox_roi_extractor=dict(
....
```
but i use one gpu with lr = 0.002 

log show as follow:

![image](https://user-images.githubusercontent.com/22139336/58016218-a301e300-7b2f-11e9-9161-483391d36e87.png)

  and test:
  **python tools/test.py --config --model --eval bbox --out**
  result:
  
![image](https://user-images.githubusercontent.com/22139336/58016399-19064a00-7b30-11e9-8ed5-7e127b715e2f.png)

 help..  what's wrong ?

**Comment by hellock** [comment]
According to the log, you used lr=0.02.
