### ISSUE TITLE
How to choose nms type, such as nms, soft-nms, etc.

### ISSUE THREAD

**Issue by ts19970816** [open-mmlab/mmdetection#6710]
How to choose nms type, such as nms, soft-nms, etc.

**Comment by hhaAndroid** [comment]
@ts19970816 Softnms is more suitable for dense scenes, generally the performance will be better, but not absolute.

**Comment by ts19970816** [comment]
Select softnms in that configuration file

**Comment by shenyi0220** [comment]
BTW, a cluster better than soft-nms is provided here(https://github.com/shenyi0220/CP-Cluster)

**Comment by ts19970816** [comment]
thanks
