### ISSUE TITLE
The influnce of different sampling ratio in roi align

### ISSUE THREAD

**Issue by blowing-wind** [open-mmlab/mmdetection#6712]
Hi, I wonder how the mAP changes when modifying the default sampling ratio from 0 to 2 in faster-rcnn-fpn roi align，i.e. from an adaptive value to a fixed value，thanks.

**Comment by hhaAndroid** [comment]
@blowing-wind There is no clear answer to this, maybe you can use part of the coco data set to study.

**Comment by blowing-wind** [comment]
Thanks, I'll try it.

**Comment by blowing-wind** [comment]
I change the sampling ratio to 2 in faster_rcnn_r50_fpn_1x_coco, and the result keeps unchanged.
