### ISSUE TITLE
请问近期有公开YOLOX-l和x版本权重的计划么？

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#6713]
或者能否提供下将YOLOX官方的pth权重转成mmdetection格式pth的脚本？是否直接按照对应的key把权重拷贝过来然后就能用了，想请教一下

**Comment by hhaAndroid** [comment]
@clw5180 Yes. You can refer to https://github.com/open-mmlab/mmdetection/pull/6698

**Comment by clw5180** [comment]
> @clw5180 Yes. You can refer to #6698

Thanks, 眸big old
