### ISSUE TITLE
I trained yolox-s on my own dataset of only 1 class, but loss_cls and loss_bbox is always 0

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#6721]
And loss_obj seems normal, what the problem might be? Thanks a lot!
I use 'CocoDataset' in config.py

**Comment by alvinti** [comment]
hi！I encountered the same error. How did you fix it?

**Comment by qiangruoyu** [comment]
hi！I encountered the same error. How did you fix it?
