### ISSUE TITLE
When i use the empirical_attention in the mask_rcnn_r34 , it occur a problem.

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6723]
Why i can train the mask_rcnn_r34, but when i use the plugin in the resnet_34 in the mask_rcnn_r34, i occur the problem:
![2021-12-08 14-42-56屏幕截图](https://user-images.githubusercontent.com/86214036/145161604-a10ebcb3-f0d4-4d66-9d63-1f5181a70d22.png)

**Comment by AronLin** [comment]
Because r34 uses `BasicBlock` but `BottleNeck`, `plugins`(empirical_attention) not supported in `BasicBlock`.
