### ISSUE TITLE
how to use interpolation 'bilinear' while resizing the image for inference

### ISSUE THREAD

**Issue by apanand14** [open-mmlab/mmdetection#6726]
For the inference, I'm using the below config and when I resize the image then it takes interploation nearest by default (I'm not able to find where this process is taken place in code). But I would like to change image resizing with bilinear interploation. Please help me if you already know about it. Thank you in advance.

A part of config for inference:
    **test=dict(
        type='CocoDataset',
        ann_file='annotations/instances_val2017.json',
        img_prefix='train2017',
        classes=classes,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        data_root=data_root))**

**Comment by AronLin** [comment]
We don't support changing the interpolation mode now. But the images are resized with bilinear interpolation by default.
The code is in the `mmdet/datasets/pipelines/transform.py : Resize`.
