### ISSUE TITLE
Different sample_nums on different gpus

### ISSUE THREAD

**Issue by Jack-Hu-2001** [open-mmlab/mmdetection#6728]
**Describe the feature**
I want to utilize several gpus but some of them are partly used by other students. So I would like to 
put different numbers of samples on different gpus for training.
For example, gpu 1 is available and I'd like to set samples_per_gpu on this one at 4.
gpu 2 and 3 is partly used and I'd like to set it to 2 or 1.
However, it's not allowed to do so.

**Motivation**
A clear and concise description of the motivation of the feature.
1. Limited computation resources.
2. different utilization percentage on different gpus.

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.
1. I'm not sure whether this is easy to be implemented in distributed training process.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.
1. need help.

**Comment by AronLin** [comment]
PyTorch has not supported it, so it is hard to support it in our codebase, too.
