### ISSUE TITLE
Training is getting interrupted without any traceback or error

### ISSUE THREAD

**Issue by Rajesh-mandal** [open-mmlab/mmdetection#6729]
unable to train a mmdetection instance segmentation model

**i am not getting any error ..i am getting bellow things**

![image](https://user-images.githubusercontent.com/47553660/145205796-4ffb5e89-67fd-4e3d-8a19-a19a95d7aeea.png)

**Comment by AronLin** [comment]
I have no idea. It seems like there are some problems with your environment or hardware.
If you find the problem, can you give some feedback?
