### ISSUE TITLE
RGB or BGR

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#6735]
Hi, can I confirm that mmcv/mmdet loads images in BGR by default? In the case of the pretrained [model zoo](https://mmdetection.readthedocs.io/en/v2.14.0/model_zoo.html#imagenet-pretrained-models), if `to_rgb` is True then the pretrained model was trained on RGB image, else BGR?

**Comment by RangiLyu** [comment]
BGR is the default. Some models use `to_rgb=True` because the pre-trained weights were converted from the third part.

**Comment by levan92** [comment]
Alright, thank you
