### ISSUE TITLE
Is K-fold training supported??

### ISSUE THREAD

**Issue by bhyun-kim** [open-mmlab/mmdetection#6736]
Is K-fold training supported?? 

As far as I looked through dataset wrappers, it is not supported yet. 

Looking into mmcv runner, it seems the runner go through a whole dataset once it is loaded. 

Is there any way to dynamically change dataset every epoch?? 

If so your help for it would be appreciated. 
If not, could you give me some brief guideline to implement it?

**Comment by RangiLyu** [comment]
Sorry, the K-fold training is not supported yet. 

> Is there any way to dynamically change dataset every epoch??

One way is to implement a Hook to change the data_loader every epoch. Or just implement a runner that supports this function.

**Comment by bhyun-kim** [comment]
Is K fold validation in MMDet roadmap? It seems not so now,  but it will be valuable for many competition usages.

**Comment by bhyun-kim** [comment]
I would make a pr if my implementation looks good enough! Thanks for your reply!!
