### ISSUE TITLE
How can I add my new head in code of RetinaNet? How to registry?

### ISSUE THREAD

**Issue by wei-yuma** [open-mmlab/mmdetection#674]
I have made a new head, that is a child of class AnchorHead. But how to make it work in training phase and test phase of RetinaNet? It seems should be registed, eh, how to do that? Thank you!

**Comment by wei-yuma** [comment]
I have known how to do that. Just like adding FcosHead, thank you!

**Comment by DecentMakeover** [comment]
@wei-yuma  Can you please share in which file you have made these changes,  i want to add a regression head as well to faster rcnn.Thanks
