### ISSUE TITLE
Dataloader

### ISSUE THREAD

**Issue by qdd1234** [open-mmlab/mmdetection#6741]
您好，就是有个代码书写方面的问题想请教你们一下，Dataloader里面现在是每次随机抽取一个batch数据进行训练，如果我想要指定每个batch里面图片的id来进行训练，这种代码怎么来写？ 谢谢~

**Comment by RangiLyu** [comment]
You may need to implement a BatchSampler.

**Comment by XiongweiWu** [comment]
@RangiLyu Hi I find a small typo in your Readme.md, where the swin is published in ICCV-21 instead of CVPR-21. It's a minor issue so I just inform you here without creating an issue.

**Comment by RangiLyu** [comment]
> @RangiLyu Hi I find a small typo in your Readme.md, where the swin is published in ICCV-21 instead of CVPR-21. It's a minor issue so I just inform you here without creating an issue.

Thanks! Welcome to create a PR to fix it.
