### ISSUE TITLE
How to perform two independent augmentations for each image in a mini-batch?

### ISSUE THREAD

**Issue by Sharpiless** [open-mmlab/mmdetection#6742]
Just like “Augment your batch: Improving generalization through instance repetition”

**Comment by RangiLyu** [comment]
You may need to add two pipelines to the dataset. https://github.com/open-mmlab/mmdetection/blob/f08548bfd6d394a82566022709b5ce9e6b0a855e/mmdet/datasets/custom.py#L241

**Comment by Sharpiless** [comment]
Thanks.
