### ISSUE TITLE
 Can't see the progress bar

### ISSUE THREAD

**Issue by gtq0801** [open-mmlab/mmdetection#6745]
您好 我在使用YOLOX模型进行训练自己的数据集的时候 我发现在常规的batchsize下，只有在save checkpoint at 10 epoch的时候才会显示训练进度条；然而只有我把batchsize设置成1的时候，才能看到正常的训练进度条与loss情况，请问这是什么原因呢？

**Comment by RangiLyu** [comment]
Please follow the issue template to provide more details.
