### ISSUE TITLE
add 'Masked-attention Mask Transformer for Universal Image Segmentation' to mmdet

### ISSUE THREAD

**Issue by chhluo** [open-mmlab/mmdetection#6748]
**add 'Masked-attention Mask Transformer for Universal Image Segmentation' to mmdet**

**Motivation**
This algorithm called mask2former is an improved version of maskformer, and the results in the paper are still very good.

**Related resources**
http://arxiv.org/abs/2112.01527

**Additional context**
I want to reimplement it, add it to mmdet.

**Comment by BIGWangYuDong** [comment]
PRs are welcomed.
