### ISSUE TITLE
How to calculate mAP in coco style on pascal voc dataset?

### ISSUE THREAD

**Issue by buncybunny** [open-mmlab/mmdetection#6750]
Pascal VOC dataset and COCO have different evaluation metrics. 
How can I calculate mAP in coco style on pascal voc dataset on current mmdetection?

**Comment by BIGWangYuDong** [comment]
you can convert voc to coco style and calculate mAP in coco style.

**Comment by douxwombat** [comment]
@BIGWangYuDong Do you think replacing this line of the code to ```iou_thrs = [0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]```will do the same job? https://github.com/open-mmlab/mmdetection/blob/f3817df55709e4b13098ebaa9cf72a77b68ce994/mmdet/datasets/voc.py#L63 
I've got results from the replaced code like below.
```
OrderedDict([('AP50', 0.794), ('AP55', 0.774), ('AP60', 0.75), ('AP65', 0.719), ('AP70', 0.666), ('AP75', 0.59), ('AP80', 0.487), ('AP85', 0.35), ('AP90', 0.176), ('AP95', 0.031), ('mAP', 0.533679335564375)])

```

**Comment by BIGWangYuDong** [comment]
I remember that COCO metric and VOC metric are not same, it is suggested to use coco style to check whether they are same.
