### ISSUE TITLE
Change the GPU index to be used for `inference_detector`

### ISSUE THREAD

**Issue by zunction** [open-mmlab/mmdetection#6751]
Is there a way to change the GPU to be used for the `inference_detector` function?

It seems to me that the GPU index is default to 0.

The model I'm using is `mmdet.models.detectors.retinanet.RetinaNet`

Thanks in advance!

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/f3817df55709e4b13098ebaa9cf72a77b68ce994/tools/test.py#L198
Maybe you can change your gpu index here.

**Comment by zunction** [comment]
Thanks a lot!
