### ISSUE TITLE
how to train faster rcnn without fpn

### ISSUE THREAD

**Issue by douxwombat** [open-mmlab/mmdetection#6753]
There was a issue about this before(#2054) but the link of the config there is expired.
How can I train faster rcnn without fpn?

Thanks

**Comment by BIGWangYuDong** [comment]
the config link is https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_c4_1x_coco.py

**Comment by douxwombat** [comment]
@BIGWangYuDong Thanks!
