### ISSUE TITLE
mmdetection/mmdet/core/evaluation/mean_ap.py",   num_classes = len(det_results[0])  # positive class num IndexError: list index out of range

### ISSUE THREAD

**Issue by wyh196646** [open-mmlab/mmdetection#6754]
**Describe the bug**

**Reproduction**

the command I use was: `python ./tools/train.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py`

I meet this bug when the first epoch training over,in eval,the terminal shows
`  File "/home/wangyh21/assignment/mmtest/mmdetection/mmdet/core/evaluation/mean_ap.py", line 354, in eval_map
    num_classes = len(det_results[0])  # positive class num
IndexError: list index out of range`

 I want to train a model to detect the vichle,so, that was only one class 'vehicle' in my dataset ,and my dataset is voc format.
I changed  four file under:
`
mmdetection/mmdet/datasets/voc.py

mmdetection/mmdet/core/evaluation/class_names.py

mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py

mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py
`

**Environment**
sys.platform: linux
Python: 3.7.0 (default, Jun 28 2018, 13:15:42) [GCC 7.2.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.0 Product Build 20180829 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu102
OpenCV: 4.5.4-dev
MMCV: 1.4.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.19.0+f08548b

**Error traceback**
2021-12-10 15:06:03,589 - mmdet - INFO - Epoch [1][3050/3053]   lr: 2.000e-02, eta: 1:26:38, time: 0.154, data_time: 0.007, memory: 2304, loss_rpn_cls: 0.0066, loss_rpn_bbox: 0.0287, loss_cls: 0.1110, acc: 95.3926, loss_bbox: 0.1749, loss: 0.3212
2021-12-10 15:06:04,083 - mmdet - INFO - Saving checkpoint at 1 epochs
completed: 0, elapsed: 0s
---------------iou_thr: 0.5---------------
Traceback (most recent call last):
  File "./tools/train.py", line 185, in <module>
    main()
  File "./tools/train.py", line 181, in main
    meta=meta)
  File "/home/wangyh21/assignment/mmtest/mmdetection/mmdet/apis/train.py", line 203, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/wangyh21/anaconda3/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wangyh21/anaconda3/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/wangyh21/anaconda3/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/wangyh21/anaconda3/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/wangyh21/assignment/mmtest/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 58, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/wangyh21/anaconda3/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 362, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/wangyh21/assignment/mmtest/mmdetection/mmdet/datasets/voc.py", line 89, in evaluate
    use_legacy_coordinate=True)
  File "/home/wangyh21/assignment/mmtest/mmdetection/mmdet/core/evaluation/mean_ap.py", line 354, in eval_map
    num_classes = len(det_results[0])  # positive class num
IndexError: list index out of range

**Comment by BIGWangYuDong** [comment]
maybe you should check your num_classes in your config file

**Comment by wyh196646** [comment]
> 

really thanks，but which file  you mean? I have modify four file under 

`mmdetection/mmdet/datasets/voc.py

mmdetection/mmdet/core/evaluation/class_names.py

mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py

mmdetection/configs/base/models/faster_rcnn_r50_fpn.py`

**Comment by wyh196646** [comment]
@BIGWangYuDong 
I'm really appreciate your  reply，but which file you mean(config file)? I have modify four file under

mmdetection/mmdet/datasets/voc.py

mmdetection/mmdet/core/evaluation/class_names.py

mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py

mmdetection/configs/base/models/faster_rcnn_r50_fpn.py

**Comment by BIGWangYuDong** [comment]
It is suggested to give us your code details, seems that your config file num_classes in bbox head is not equal to your labels:

https://github.com/open-mmlab/mmdetection/blob/83eea4bec684708171f0b6433636df0873e50dac/configs/_base_/models/faster_rcnn_r50_fpn.py#L47

**Comment by luyunfighting** [comment]
Have you solved the problem yet？Thank you~
