### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#6755]
环境为：

Anconda python3.8
                   Cuda 13
                  Pytorch 1.10.1
                  Opencv 4.5.4
                  MMCV 1.4.0
                  mmdetection 2.19.0
                  libgtk2.0-dev 已经是最新版 (2.24.32-1ubuntu1)
                  pkg-config 已经是最新版 (0.29.1-0ubuntu2)。

运行video_demo.py时总会报错
运行命令为python /home/1/Visual/mmdetection-2.19.0/demo/video_demo.py /home/1/Visual/mmdetection/demo/demo.mp4 /home/1/Visual/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py /home/1/Visual/mmdetection/work_dirs/mask_rcnn_r50_fpn_1x_coco1/latest.pth --out /home/1/coco

运行结果为：
load checkpoint from local path: /home/zhaowentao/Visual/mmdetection/work_dirs/mask_rcnn_r50_fpn_1x_coco1/latest.pth
[ERROR:0] global /tmp/pip-req-build-khv2fx3p/opencv/modules/videoio/src/cap.cpp (595) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.4) /tmp/pip-req-build-khv2fx3p/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /home/zhaowentao/coco in function 'icvExtractPattern'

[                                                  ] 0/67, elapsed: 0s, ETA:/home/zhaowentao/Visual/mmdetection-2.19.0/mmdet/datasets/utils.py:65: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 67/67, 5.0 task/s, elapsed: 13s, ETA:     0s
Traceback (most recent call last):
  File "/home/zhaowentao/Visual/mmdetection-2.19.0/demo/video_demo.py", line 61, in <module>
    main()
  File "/home/zhaowentao/Visual/mmdetection-2.19.0/demo/video_demo.py", line 57, in main
    cv2.destroyAllWindows()
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-khv2fx3p/opencv/modules/highgui/src/window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

问题出在了哪里？

**Comment by BIGWangYuDong** [comment]
1. please check your image path.
2. maybe you can reinstall a lower version of opencv-python
