### ISSUE TITLE
How to get the current number of epochs？

### ISSUE THREAD

**Issue by Ahappyprogrammer** [open-mmlab/mmdetection#6761]
By learning the relevant code of mmcv，I know that the relevant information of epoch is in the EpochBasedRunnerclass，but i want to get the current epoch information in the components of the network model. For example, I want to get epoch in ResNet.
I want to know how I can get this information.Thanks.

**Comment by shinya7y** [comment]
Related to https://github.com/open-mmlab/mmdetection/issues/5153 and `SetEpochHook` in https://github.com/open-mmlab/mmdetection/pull/6746

**Comment by Ahappyprogrammer** [comment]
> Related to #5153 and `SetEpochHook` in #6746

Thanks, I have successfully obtained the epoch number information.
