### ISSUE TITLE
Eval yolox-tiny, but ap is 0

### ISSUE THREAD

**Issue by jiesonshan** [open-mmlab/mmdetection#6769]
download demo of yolox-tiny,  model and confis is mmdet config/yolox/readme.md;
test model using mmdet; 
```
./tools/dist_test.sh configs/yolox/yolox_tiny_8x8_300e_coco.py /data/temp/torch_models/yolox_tiny_8x8_300e_coco_20210806_234250-4ff3b67e.pth 1 --out /data/temp/temp.pkl --eval bbox
``` 
but result is 0

**Comment by hhaAndroid** [comment]
@jiesonshan We will release the latest version weights and configurations today, you can try again.

**Comment by jiesonshan** [comment]
thank you！
