### ISSUE TITLE
building a custom config file for latest object detection.

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmdetection#6771]
First Thanks for this awesome work. I am using this framework for my final year project. I need much speed up on object detection. I planned to use YOLOv4 with Mobilenet_v2 backend. How can I 

- develop config file for that?
- do the training ?
using mmdetection..
or 
If you have any plan to release YOLOv4?

your assistance is much appreciated in my FYP
Thank you.

**Comment by jshilong** [comment]
Would you mind taking a look at this PR?

**Comment by jshilong** [comment]
You can use our YOLOX which is better than yolov4, you can easily combine `yolox` with `Mobilenet_v2`
You can refer to [Yolox](https://github.com/open-mmlab/mmdetection/tree/master/configs/yolox) and [Mobilenet_v2](https://github.com/open-mmlab/mmdetection/blob/master/configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py)

**Comment by Thevakumar-Luheerathan** [comment]
Thanks I will check on it
