### ISSUE TITLE
mmdetection在摄像头上使用

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#6776]
mmdetection作为一个图像检测工具的大合集大大方便了图像检测方面的研究。这其中综合大量不同的图像检测工具。那么如何时这个工具在摄像头上成功运行呢？
当前我在使用的摄像头为Zed mini摄像头。这样的专业双目摄像头都会自带它的软件与sdk.那么如何让mmdetection能够在这些摄像头上成功运行呢？我有找到让maskrcnn-benchmark在这个工具上成功运行的相关代码：https://github.com/stereolabs/zed-pytorch
但是mmdetection与maskrcnn-benchmark的代码有巨大的差别。所以我也很难从上面网页中的代码找到值得参考的部分。请问您有什么建议吗？

**Comment by hhaAndroid** [comment]
@kankanzheli You can refer to [webcam_demo](https://github.com/open-mmlab/mmdetection/blob/master/demo/webcam_demo.py)
