### ISSUE TITLE
Why does the workflow always validate my dataset?

### ISSUE THREAD

**Issue by zhiweil20** [open-mmlab/mmdetection#6778]
According to the document
`the only difference between [('train', 1), ('val', 1)] and [('train', 1)] is that the runner will calculate losses on validation set after each training epoch`
I only config the workflow as [('train,1)]，why does the mmdetection validate after every epoch？

**Comment by hhaAndroid** [comment]
@zhiweil20 Because EvalHooK is inserted by default
```python
        eval_cfg = cfg.get('evaluation', {})
        eval_cfg['by_epoch'] = cfg.runner['type'] != 'IterBasedRunner'
        eval_hook = DistEvalHook if distributed else EvalHook
        # In this PR (https://github.com/open-mmlab/mmcv/pull/1193), the
        # priority of IterTimerHook has been modified from 'NORMAL' to 'LOW'.
        runner.register_hook(
            eval_hook(val_dataloader, **eval_cfg), priority='LOW')
```
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L191
