### ISSUE TITLE
A question about mask_rcnn_r34?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6782]
When i use the empirical_attention in the mask_rcnn_r34 , it occur a problem.
Why i can train the mask_rcnn_r34 only, but when i use the plugin in the resnet_34 in the mask_rcnn_r34, i occur the problem:
![image](https://user-images.githubusercontent.com/86214036/145928054-98e7defa-5c3a-4bee-b8e8-4ddf21233afa.png)

**Comment by hhaAndroid** [comment]
@lijoe123 Please use the issue template and provide configuration and other information.

**Comment by lijoe123** [comment]
i am sorry!!! what is the  issue template?

**Comment by ZwwWayne** [comment]
When you create an issue, you need choose one of this button 
![image](https://user-images.githubusercontent.com/40779233/146387478-420efe29-69b9-4813-a49f-ecfad7b4c222.png)
Then these is a markdown template for you to fill in. You should not delete them all.
![image](https://user-images.githubusercontent.com/40779233/146387576-cdcf388f-b7ee-42c5-b2d3-250fba1b0c91.png)
