### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Shorlaks** [open-mmlab/mmdetection#6787]
Hi
**Describe the bug**
I'm running the example from the 'colab tutorial' and this is the result I get.

```
from mmdet.apis import inference_detector, init_detector, show_result_pyplot

# Specify the path to model config and checkpoint file
config_file = r'/home/mb2/Dan/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_mstrain-poly_3x_coco.py'
checkpoint_file = r'/home/mb2/Dan/mmdetection/checkpoints/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth'

# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

img = r'/home/mb2/Dan/mmdetection/demo/demo.jpg'
result = inference_detector(model, img)
show_result_pyplot(model, img, result, score_thr=0.3)
```
No bounding box's 

![Screenshot at 2021-12-14 11-01-55](https://user-images.githubusercontent.com/31376676/145967352-d5e78683-d2e0-48a2-ac22-2b5f8ac0c22a.png)

**Comment by ZwwWayne** [comment]
Does this script have any log printed out?

**Comment by Shorlaks** [comment]
That's the only thing in printed:
```
load checkpoint from local path: /home/mb2/Dan/mmdetection_old/checkpoints/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth
/home/mb2/Dan/mmdetection_old/mmdet/datasets/utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
```

**Comment by wswsadmin** [comment]
**I have the same problem ,but in windows sys**
When I run this: result = inference_detector(model,img)
then,get errors:
C:\Anaconda\envs\mmdet\lib\site-packages\mmdet\datasets\utils.py:69: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
C:\Anaconda\envs\mmdet\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
