### ISSUE TITLE
How to select the best  fine-tuned checkpoints on my val datasets? tools packages?

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmdetection#6791]

**Comment by AronLin** [comment]
You can set `save_best=True` in the `checkpoint_config` when you fine-tune your model.

**Comment by Williamlizl** [comment]
> You can set `save_best=True` in the `checkpoint_config` when you fine-tune your model.

`/mmdetection-master/configs/_base_/datasets/coco_detection.py
evaluation = dict(interval=1, metric='bbox',save_best='bbox_mAP')
`

**Comment by AronLin** [comment]
> > You can set `save_best=True` in the `checkpoint_config` when you fine-tune your model.
> 
> `/mmdetection-master/configs/_base_/datasets/coco_detection.py evaluation = dict(interval=1, metric='bbox',save_best='bbox_mAP') `

Oh, thank you, that‘s the right version.
