### ISSUE TITLE
How to use large-scale jittor while keeping w&h ratio?

### ISSUE THREAD

**Issue by Sharpiless** [open-mmlab/mmdetection#6797]
[这里](https://github.com/open-mmlab/mmdetection/blob/d64e719172335fa3d7a757a2a3636bd19e9efb62/configs/strong_baselines/mask_rcnn_r50_caffe_fpn_syncbn-all_rpn-2conv_lsj_100e_coco.py) 的配置文件使用resize+crop+pad实现了large-scale jittor，实际上large-scale jittor好像pad的时候需要保持长宽比，请问目标mmdet是否支持？

**Comment by ZwwWayne** [comment]
set keep_ratio=True always keeps the ratio of images. Then setting the img_size of padding module will make sure the images are padded to the expected size like 1024. This is already supported in mmdet.
