### ISSUE TITLE
The English version of the docs are not displayed

### ISSUE THREAD

**Issue by JackRio** [open-mmlab/mmdetection#6799]
When I try to change the language of the docs to the English version it still shows me the Chinese version of the docs. This was not the case yesterday.

**Comment by Kevin-Delnoije** [comment]
I am having the same problem, using a older version solved it for me.

https://mmdetection.readthedocs.io/en/v2.18.1/tutorials/config.html

**Comment by JackRio** [comment]
Ohh thanks for the link. I just saw they rolled an update a few hours ago, which caused this change. I am using the older one now as well.

**Comment by RangiLyu** [comment]
Sorry for that. After refactoring the doc folder in #6774. The docs pages were generated incorrectly. We will fix it as soon as possible.

**Comment by RangiLyu** [comment]
The docs have been recompiled. Try to refresh the page.
