### ISSUE TITLE
How to choose the soft_nms method 'Linear' or 'Gaussian'

### ISSUE THREAD

**Issue by nuanyang123** [open-mmlab/mmdetection#680]
How to choose the soft_nms method 'Linear' or 'Gaussian'?

**Comment by hellock** [comment]
Add `method='gaussian'` in the config. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/nms/nms_wrapper.py#L52) for supported arguments.

**Comment by James606240** [comment]
SO if do not add method='gaussian' , is using linear？
