### ISSUE TITLE
对输出结果添加筛选条件

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#6803]
我想要对输出结果添加筛选条件。例如mmdetection的mask-rcnn结果中只输出面积最大的结果。或者边界框内包含某个图像像素点的结果。要做这样的处理应该在哪里进行修改呢？

**Comment by RangiLyu** [comment]
You can overwrite the `simple_test` function of `TwoStageDetector` in `MaskRCNN`.

**Comment by kankanzheli** [comment]
Sorry. I can not find the file of TwoStageDetector in MaskRCNN.

**Comment by kankanzheli** [comment]
我需要确认一下，你要我修改的代码是在mmdetection上吗？

**Comment by RangiLyu** [comment]
`MaskRCNN` inherits `TwoStageDetector`, just overwrite the `simple_test` function.

**Comment by kankanzheli** [comment]
你可以把那个包含simple_test function的文件给一个链接吗？

**Comment by kankanzheli** [comment]
因为我查找了大部分和webcam_demo.py相关的代码，没有能够找到函数simple_test 。所以期待你的帮助。
或者说这个代码存在于mmcv,或只在最新版的mmdetection中呢？

**Comment by RangiLyu** [comment]
https://github.com/open-mmlab/mmdetection/blob/83eea4bec684708171f0b6433636df0873e50dac/mmdet/models/detectors/two_stage.py#L173
