### ISSUE TITLE
Modify source code and recompile

### ISSUE THREAD

**Issue by EkAugust** [open-mmlab/mmdetection#6805]
I want to modify the source code i.e., bbox_overlaps_cuda_kernel.cuh in /mmcv/ops/csrc. Do I need to recompile mmcv every time I make a change to take effect?

**Comment by RangiLyu** [comment]
Yes. The cuda code needs to be compiled every time if you modified. It is a compiled language, not interpreted language.

**Comment by EkAugust** [comment]
Thanks for your reply.
Can I execute compilation command directly in the mmcv/mmdetection directory without uninstall mmcv/mmdetection? The original version will be covered and I can run my code?

**Comment by EkAugust** [comment]
@RangiLyu 
Thanks for your reply.
Can I execute compilation command directly in the mmcv/mmdetection directory without uninstall mmcv/mmdetection? The original version will be covered and I can run my code?

**Comment by ZwwWayne** [comment]
Yes you can do that.
