### ISSUE TITLE
Mosaic transform 

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6807]
Is there a way to add a probability to the mosaic transform in my train pipeline?

For example : p=0.5 would mean leave the image as it is half the time, and modify it to a mosaic half the time

**Comment by RangiLyu** [comment]
Currently, mosaic probability can not be set in config. 
Try to add `if random.uniform(0, 1) > p:` in `__call__` of the mosaic transform.

We are considering adding this feature in the future.
