### ISSUE TITLE
修改输出的结果

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#6811]
很抱歉再次询问这个问题。
现在我在使用mmdetection的mask-rcnn部分
我想要实现的目标为两个。一个是在对行人的图像实例分割后再提取出面积最大的结果并展示。另外一个是在获得面积最大的实例分割结果后寻找和这个行人的边界框结果存在相交的手提袋的实例分割结果。我应该修改哪部分的代码呢？
除此之外，修改的这些代码是对所有的实例分割工具都起效呢还是只对mask-rcnn起效呢？
总的来说，现在运行mmdetection的mask-rcnn可以获得物体的实例分割和边界框结果。我想通过对这两个结果的处理来对mask-rcnn不同标签的分割结果进行筛选。

**Comment by kankanzheli** [comment]
这些问题可以在已经获得实例分割结果后通过对已有结果的筛选来解决吗？能的话在哪里解决呢？（哪个文件及其函数）

**Comment by BIGWangYuDong** [comment]
Seems that we do not support your requirement, we get mask r-cnn results at here:
https://github.com/open-mmlab/mmdetection/blob/83eea4bec684708171f0b6433636df0873e50dac/mmdet/models/detectors/two_stage.py#L173-L185

maybe you can add post-processing, for example, you can add your process in this function,
https://github.com/open-mmlab/mmdetection/blob/83eea4bec684708171f0b6433636df0873e50dac/mmdet/models/roi_heads/test_mixins.py#L224-L229

**Comment by kankanzheli** [comment]
谢谢了。除此之外，我还想询问一下mmdetection能够在ros上使用吗？将ros运行的摄像头获取的数据使用mmdetection来进行处理？
