### ISSUE TITLE
When i use the empirical_attention plug_in in  the resnet_34 of mask_rcnn, it occur a problem.

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6813]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
         When i use the emirical_attention plug_in in  the resnet_34 of mask_rcnn, it occur a problem. But i had run the resnet_34 of mask_rcnn successfully.
![image](https://user-images.githubusercontent.com/86214036/146479507-cbffdb60-89e2-489f-ab7f-cab68c183743.png)

**Reproduction**

1. What command or script did you run?
    python tools/train.py configs/empiricxal_attention/mask_rcnn_r34_fpn_2x.py --work-dir work_dirs/attention_r34
```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
        I change the empirical_attention  first line :  _base_ = '../mask_rcnn/mask_rcnn_r34_fpn_2x_coco.py'

3. What dataset did you use?
         The dataset is mine. And the dataset is coco dataset.
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
![75e3ff63c13e52a2ea608655b0530a16](https://user-images.githubusercontent.com/86214036/146479457-c78282e5-126a-40b0-a62f-d89b186f9513.jpg)

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]      conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by BIGWangYuDong** [comment]
Hi, what code did you change? For example, what code did you change in config file?

**Comment by lijoe123** [comment]
Hi. Your teammate had told me that the Resnet_34 is BasicBottle, But empirical_attention plug_in is BottleNeck ,not support in BasicBlock.
Do you have any solution?

**Comment by BIGWangYuDong** [comment]
You can write a Model to support using bottleneck in Resnet-34. However, I don't think this is a good way to fix this error, because using bottleneck in Resnet-34 may get lower performance. Maybe you can use Resnet-50?
