### ISSUE TITLE
A question about iou_threshold?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6815]
When i use the iou_threshold=0.85 0f dynamic_rcnn to improve the mask_rcnn, the effect is same as before,
but when i use the iou_threshold=0.9,the effect is better.
So  i want to know about the influence of iou_threshold.

**Comment by BIGWangYuDong** [comment]
I haven't met this problem before. I guess that IoU_thr will affect tp and fp, also it will potentially affect the sequence of the pred score. So this may cause your problem

**Comment by BIGWangYuDong** [comment]
feel free to reopen this issue if you still meet this problem
