### ISSUE TITLE
The training speed with InfiniBand 

### ISSUE THREAD

**Issue by RaymondByc** [open-mmlab/mmdetection#6817]
I updated our device from ethernet to InfiniBand, and expected there would be a huge boost in training speed. Unfortunately, it did not happen. 

Have you tested your training with InfiniBand? How the training speed is? 

Are there any extra steps for using InfiniBand? In my case, I just test the connection speed with "ping", and used it the same way as using ethernet.

**Comment by BIGWangYuDong** [comment]
Haven't tried this before. Maybe you can create a discussion to discuss this
