### ISSUE TITLE
problem about  the SyncBN

### ISSUE THREAD

**Issue by runzeer** [open-mmlab/mmdetection#682]
I  changed the config file according to the GN. But when I use multi-test mode, the detected results are empty lists. Could you tell me how to train and test the model with SyncBN? Or could you share your config file for training and testing?

**Comment by hellock** [comment]
We just change `norm_cfg = dict(type='GN', num_groups=32, requires_grad=True)` to `norm_cfg = dict(type='SyncBN', requires_grad=True)`. The official SyncBN implementation seems not very stable.
