### ISSUE TITLE
Multi GPU Cluster Training with ray

### ISSUE THREAD

**Issue by sainivedh19pt** [open-mmlab/mmdetection#6822]
Hi,
There's not much resources available on mmdet docs, Any tips/blogs on getting started with distributed training with ray will be very helpful.

Thanks

**Comment by BIGWangYuDong** [comment]
You can refer to [Docs](https://github.com/open-mmlab/mmdetection/blob/5e246d5e3bc3310b5c625fb57bc03d2338ca39bc/docs/en/1_exist_data_model.md#manage-jobs-with-slurm)

**Comment by amogkam** [comment]
Hey @sainivedh19pt, I'd recommend checking out [Ray Train](https://docs.ray.io/en/latest/train/train.html) for this! 

Ray Train is a library built on Ray for distributed deep learning training- it can take any training function and run it in a distributed fashion. And it will take care of things like creating the torch process group for you.

I think you should be able to take the main functions in `tools/train.py` in this repo, and then run it with Ray Train for distributed training.

Let me know if you have any questions!

**Comment by sivaguru-pat** [comment]
@amogkam hey having this issue while setting mmdetection with ray https://discuss.ray.io/t/model-training-remain-idle-for-12hrs/7296
