### ISSUE TITLE
希望能增加一个很优秀算法-D2Det

### ISSUE THREAD

**Issue by GgShine** [open-mmlab/mmdetection#6825]
在cvpr了解到D2Det是个很优秀的二阶段算法，想请问您一下后续有没有支持此算法的计划

**Comment by jshilong** [comment]
There is a quite heavy head (8 convs with 576 channels) in the second stage in this paper, there are already many excellent algorithms in mmdet when the model size is comparable， so this algorithm is not in our plan， but any pr is appreciated.

**Comment by GgShine** [comment]
很感谢解惑
