### ISSUE TITLE
can't start new thread

### ISSUE THREAD

**Issue by Cathy1900** [open-mmlab/mmdetection#6831]
运行panoptic_fpn时，提示上述错误
OpenBLAS blas_thread_init: pthread_create failed for thread 27 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 2063176 current, 2063176 max

**Comment by AronLin** [comment]
You are currently running too many processes.
During the evaluation, `panopticapi` will create many processes to parallel evaluate the results. You can clean up the useless processes of the system.

**Comment by Cathy1900** [comment]
> You are currently running too many processes. During the evaluation, `panopticapi` will create many processes to parallel evaluate the results. You can clean up the useless processes of the system.

您好，抱歉再次打扰您，本人太小白，请问无效的进程在哪里查看并清楚呢？谢谢

**Comment by AronLin** [comment]
> 您好，抱歉再次打扰您，本人太小白，请问无效的进程在哪里查看并清楚呢？谢谢

This problem can be solved with a search engine.

**Comment by Cathy1900** [comment]
Thanks for your answer！
