### ISSUE TITLE
Question about yolox training time

### ISSUE THREAD

**Issue by wywywy01** [open-mmlab/mmdetection#6832]
According to  the training log of yolox - S model., [log](https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_s_8x8_300e_coco/yolox_s_8x8_300e_coco_20211121_095711.log.json)
whether is the unit of time field is minutes? If so, 300 epoch training usually about 2.7d (0.37min x 37 x 300)?
"time": 0.36955

(
我看到yolox -s模型的训练log，请问 time 字段的单位是分钟吗
如果是的话，300个epoch训练时常大概是2.7d吗 （0.37min x 37 x 300）,
其中37表示一个epoch的data size 1839除以50
)

**Comment by hhaAndroid** [comment]
@wywywy01  The unit of time is seconds.

**Comment by hhaAndroid** [comment]
@wywywy01 Yes.
