### ISSUE TITLE
About get_flpos.py on yolox model

### ISSUE THREAD

**Issue by wywywy01** [open-mmlab/mmdetection#6834]
hi， when i run scripts：

`python tools/analysis_tools/get_flops.py configs/yolox/yolox_tiny_8x8_300e_coco.py --shape 416`

i get 
![image](https://user-images.githubusercontent.com/22450352/146724276-f9a757df-8c8d-4018-bf7f-a6698a7b3b17.png)

and  run

`python tools/analysis_tools/get_flops.py configs/yolox/yolox_s_8x8_300e_coco.py --shape 640`

i get

![image](https://user-images.githubusercontent.com/22450352/146724194-0aeee530-68a4-460d-9b9b-1f5db1fa2a7a.png)

while in yolox paper， the gflops is as below：

![image](https://user-images.githubusercontent.com/22450352/146724030-8dfa0a81-df01-4e7b-a7cf-982783ec4b64.png)

**Comment by jahongir7174** [comment]
@wywywy01, as I know, mmcv [flops counter](https://github.com/open-mmlab/mmcv/blob/fb486b96fd9932637a16f23a5dc60904c12bea7d/mmcv/cnn/utils/flops_counter.py#L553) does not support swish that is used in YOLOX.

**Comment by wywywy01** [comment]
thanks a lot

**Comment by Monkey-D-Luffy-star** [comment]
@wywywy01 mmdetection计算的FLOPs是基于[flops-counter.pytorch](https://github.com/sovrasov/flops-counter.pytorch)工具来计算的，严格来说不是FLOPs，而是MACs，二者区别如下：MACs(Multiply–Accumulate Operations):乘加累积操作数，常常被人们与FLOPs概念混淆实际上1MACs包含一个乘法操作与一个加法操作，大约包含2FLOPs。通常MACs与FLOPs存在一个2倍的关系。
因此，mmdetection的get_flops中得到的结果×2才是真正的FLOPs（官方的YOLOX和YOLOV5的实现中都这样做了）。一些论文中有时会不加提醒的使用MACs和GFLOPs，容易给读者造成混淆。
我也是查了不少信息，如有错误，请指出！

**Comment by wenjunx** [comment]
> @wywywy01 mmdetection计算的FLOPs是基于[flops-counter.pytorch](https://github.com/sovrasov/flops-counter.pytorch)工具来计算的，严格来说不是FLOPs，而是MACs，二者区别如下：MACs(Multiply–Accumulate Operations):乘加累积操作数，常常被人们与FLOPs概念混淆实际上1MACs包含一个乘法操作与一个加法操作，大约包含2FLOPs。通常MACs与FLOPs存在一个2倍的关系。 因此，mmdetection的get_flops中得到的结果×2才是真正的FLOPs（官方的YOLOX和YOLOV5的实现中都这样做了）。一些论文中有时会不加提醒的使用MACs和GFLOPs，容易给读者造成混淆。 我也是查了不少信息，如有错误，请指出！

大佬，请问下yolo系列计算FLOPs都是默认输入尺寸为640计算的吗？因为我训练时的尺寸为1024，yolov5s输出的FLOPs也是15.9G这样
