### ISSUE TITLE
AttributeError: module 'torch.nn' has no attribute 'SyncBatchNorm'

### ISSUE THREAD

**Issue by chchenhui** [open-mmlab/mmdetection#684]
When I import build_detector from mmdet.models, I encounter an error as shown in this screen shot:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/13835142/58102082-4f68c580-7c13-11e9-95e8-af3d318bd08a.png">
Guess it works with _DistributedDataParallel_, but I'm not sure.
Don't know what updates I ignored.

**Comment by liaopeiyuan** [comment]
Have you updated to torch 1.1?

**Comment by chchenhui** [comment]
> Have you updated to torch 1.1?

Thank you. Solved this problem.

**Comment by wangxihuiok** [comment]
> > Have you updated to torch 1.1?
> 
> Thank you. Solved this problem.

Can you tell me how to solve the problem?

**Comment by chchenhui** [comment]
> > > Have you updated to torch 1.1?
> > 
> > 
> > Thank you. Solved this problem.
> 
> @chchenhui Can you tell me how to solve the problem?

Update torch to version 1.1.
