### ISSUE TITLE
Train on RGBD data

### ISSUE THREAD

**Issue by IvDmNe** [open-mmlab/mmdetection#6841]
I want to train Mask R-CNN on RGB and Depth data. Can i do it with MMdetection? I have found, that there is a function LoadMultiChannelImageFromFiles, which expects a list of filenames. Do i need to change something in my annotations format, except of replacing filenames by lists of filenames? And how the transformations will handle this 4-channel image?

**Comment by hhaAndroid** [comment]
@IvDmNe We have not experimented specifically, the pipeline basically calls `opencv` directly, so if `opencv` is supported, then the pipeline is supported.

**Comment by IvDmNe** [comment]
Thank you, I will try. If anyone had experience in training on 4-channels data, please, let me know.

**Comment by wuyiranhit** [comment]
may i ask what to changes to make it work for rgbd inputs? thanks!

**Comment by IvDmNe** [comment]
> may i ask what to changes to make it work for rgbd inputs? thanks!

For my task a model on RGB data showed decent performance, so I did't try to add RGBD support. Anyway, I saw some projects built on detectron2, that use RGBD inputs, such as https://github.com/gist-ailab/uoais

**Comment by wuyiranhit** [comment]
> 

Many thanks!
