### ISSUE TITLE
Wrong labels and not training well, using cascade-rcnn

### ISSUE THREAD

**Issue by CharlesNJ** [open-mmlab/mmdetection#6843]
I have trained using cascade-rcnn with three classes using the pre-trained model to `load_from` but it could not train well, the issue is it is training with wrong labels, trucks are being detected as cars with relatively good accuracy and the cars are not detecting at all. Seems to me like a dataset issue, but I have checked using voxel51, labels are right from the coco model `json` file on the images. I would appreciate any insight on this. Thank you again!

**Describe the bug**
No error report

**Reproduction**

1. What command or script did you run?

```!bash ./tools/dist_train.sh 'configs/tanker/cascade_rcnn_x101_64x4d_fpn_20e_coco.py' 2
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, changed the `lr` to 0.0001 and `warmup_iters` to 2000, `grad_clip=dict(max_norm=35, norm_type=2)` and `step=10`

```
albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]
        
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            #'gt_masks': 'masks',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
    #dict(type='
]
```

3. What dataset did you use?
custom dataset of one class merging with coco dataset of two classes (coco format)

Wondering if this is a data imbalance problem because it was able to detect people really well, not detecting cars at all and detecting trucks as cars (with relatively okay accuracy). During the training, the loss did not change much after 3 or 5 epochs. Class imbalance (person - 20k, cars -8k, tankers -4k) (model is able to detect person really well, detects tankers with okay accuracy but with a wrong label, car. Does not detect car at all)

**Comment by hhaAndroid** [comment]
@CharlesNJ I suggest you use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py script to check

**Comment by CharlesNJ** [comment]
@hhaAndroid Hello there, I could not quite figure out what is going on here, would you mind helping me, please?

Is it something related to classes? I have four classes 1,2,3 and 8. Where class 2 is my own class, others are taken from COCO.

```
Traceback (most recent call last):
  File "/home/wellchecked/cbn/CBNetV2/tools/misc/browse_dataset.py", line 96, in <module>
    main()
  File "/home/wellchecked/cbn/CBNetV2/tools/misc/browse_dataset.py", line 80, in main
    imshow_det_bboxes(
  File "/home/wellchecked/cbn/CBNetV2/mmdet/core/visualization/image.py", line 160, in imshow_det_bboxes
    pass_labels_bbox=create_label_text(label_text,bbox[:-1]) 
  File "/home/wellchecked/cbn/CBNetV2/mmdet/core/visualization/image.py", line 421, in create_label_text
    labels_to_save[4]=labels_to_save[4]-labels_to_save[2]
IndexError: list index out of range
```

**Comment by hhaAndroid** [comment]
@CharlesNJ This shows that the data set is not handled properly. CocoDataset will map 1/2/8 to 1/2/3, you can go to confirm.

**Comment by CharlesNJ** [comment]
Thanks! I have not made proper edits to the config file! The model is training well now.
