### ISSUE TITLE
有没有办法直接使用内存中的数据而不是先读取图像文件呢？

### ISSUE THREAD

**Issue by vincent507cpu** [open-mmlab/mmdetection#6844]
我的图片非常大，需要先切成几千个小块再预测。硬盘的 IO 非常慢，以至于模型在现实中不可用。有没有办法直接对内存里的图片进行预测呢？

**Comment by hhaAndroid** [comment]
@vincent507cpu You can customize your pipeline. For example rewrite `loadimagefromfile`
