### ISSUE TITLE
Where is the readme for useful_tools in the latest version? I could't find it,

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmdetection#6846]

**Comment by hhaAndroid** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/useful_tools.md

**Comment by Williamlizl** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/docs/en/useful_tools.md

I thought it was still on the front page, thank u
