### ISSUE TITLE
gn_ws pretrained resnext model download failure

### ISSUE THREAD

**Issue by HarveyGuo960817** [open-mmlab/mmdetection#685]
Hello, when i tried to download pretrained gn_ws resnext models, it raised error like this:

_Connecting to s3.ap-northeast-2.amazonaws.com (s3.ap-northeast-2.amazonaws.com)|52.219.56.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-21 23:49:50 ERROR 404: Not Found._

but download pretrained gn models successfully meantime.

Is there anyone else meeting the same question? Or the file name provided is false?

_'jhu/resnext50_32x4d_gn_ws': 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext50_32x4d_gn_ws-ad7a50a4.pth',  # noqa: E501
'jhu/resnext101_32x4d_gn_ws': 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_32x4d_gn_ws-6adc888e.pth',  # noqa: E501_

Thank you for replying!

**Comment by yhcao6** [comment]
Could you update your mmcv and then have a try again?

**Comment by liugl7** [comment]
you could try thess urls:
    'jhu/resnext50_32x4d_gn_ws': 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext50_32x4d_gn_ws-0d87ac85.pth',  # noqa: E501
    'jhu/resnext101_32x4d_gn_ws': 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_32x4d_gn_ws-34ac1a9e.pth',  # noqa: E501

**Comment by HarveyGuo960817** [comment]
> Could you update your mmcv and then have a try again?

Thank u very much, solved! ^-^

**Comment by HarveyGuo960817** [comment]
> you could try these urls:
> 'jhu/resnext50_32x4d_gn_ws': 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext50_32x4d_gn_ws-0d87ac85.pth',  # noqa: E501
> 'jhu/resnext101_32x4d_gn_ws': 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_32x4d_gn_ws-34ac1a9e.pth',  # noqa: E501

Thank u very much, solved! ^-^

**Comment by HarveyGuo960817** [comment]
What's more, did you ever add GN to ResNext50-FPN/ResNext101-FPN? 
I found the mAP decreased a lot?

**Comment by hellock** [comment]
@HarveyGuo960817  You can find related results [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/gn%2Bws/README.md#results-and-models).

**Comment by HarveyGuo960817** [comment]
> @HarveyGuo960817  You can find related results here.
Thank you,  but we cannot find the comparison between BN and GN, especially in ResNext. It seems that GN will decrease the mAP when it comes to more complicated network?
(As the paper of Weight Standardization reported)

**Comment by hellock** [comment]
Models in the [model zoo](https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md#mask-r-cnn) are with BN.

**Comment by HarveyGuo960817** [comment]
Ok, thank you!

**Comment by TangShengqin** [comment]
why comparison between BN and GN in ResNext, GN get a great drop in map?  Can someone analyze the reason?

**Comment by lijain** [comment]
Same question.I improved on RESnet101 by about 1% with GN_WS, but decreased by 0.4% on resnext101_32x4D.Please explain?Look at the results of the experiment. It should be improved a little bit.
