### ISSUE TITLE
Changing CutOut to RandomCutOut

### ISSUE THREAD

**Issue by lkm2835** [open-mmlab/mmdetection#6850]
**Describe the feature**

`class Cutout` -> `class RandomCutout`

**Related resources**
[RandomCutout PR](https://github.com/open-mmlab/mmsegmentation/pull/1022) in mmseg

`mmsegmentation/mmseg/datasets/pipelines/transforms.py`
-> [class RandomCutout](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/transforms.py#L954)

In mmseg, I changed Cutout to RandomCutout and added it.
Is this necessary for mmdet as well?
If necessary, I will do PR.

**Comment by ZwwWayne** [comment]
Hi @lkm2835,
Sorry for the late reply. We noticed this issue and will fix it in the future release. This issue is thus closed.
