### ISSUE TITLE
30系列的显卡如何配置mmdetection环境？

### ISSUE THREAD

**Issue by henryccl** [open-mmlab/mmdetection#6869]
我第一次使用mmdetection，但是我的显卡的3080，因为30系列的显卡需要cuda11，但是似乎mmcv只支持cuda10。有人说可以通过编译源代码来配置，我在尝试之后还是报出了mmcv有问题的错误
`ModuleNotFoundError: No module named 'mmcv._ext'
`我该怎么做才能正常使用呢？

**Comment by 17862983805** [comment]
我是RTX3060，用的cuda11.1，能够正常配置和使用mmdetection

**Comment by henryccl** [comment]
请问您是怎么配置的呢？

**Comment by henryccl** [comment]
是否需要从源码重新编译mmcv？  或者只需要pip安装就好？
我按照官网给出的流程直接pip install mmcv出错了

**Comment by henryccl** [comment]
> 我是RTX3060，用的cuda11.1，能够正常配置和使用mmdetection

请问您是怎么配置的呢？
是否需要从源码重新编译mmcv？ 或者只需要pip安装就好？
我按照官网给出的流程直接pip install mmcv出错了

**Comment by henryccl** [comment]
使用
```
pip install openmim
mim install mmdet
```
报错
`(open-mmdet) user301@301comptuer3080:~/usr/Henry/mmdetection
$ mim install mmdet
  Traceback (most recent call last):
  File "/home/user301/anaconda3/envs/open-mmdet/lib/python3.7/sit
e-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/user301/anaconda3/envs/open-mmdet/lib/python3.7/sit
e-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/user301/anaconda3/envs/open-mmdet/lib/python3.7/sit
e-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user301/anaconda3/envs/open-mmdet/lib/python3.7/sit
e-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/user301/anaconda3/envs/open-mmdet/lib/python3.7/sit
e-packages/urllib3/connectionpool.py", line 382, in _make_req
`

**Comment by henryccl** [comment]
这是要梯子吗？  是否有镜像源呢？

**Comment by ElectronicElephant** [comment]
> 但是似乎mmcv只支持cuda10

https://github.com/open-mmlab/mmcv 可以直接下载预编译好的 mmcv 呀

**Comment by henryccl** [comment]
好的 谢谢
