### ISSUE TITLE
swin transformer加载预训练模型

### ISSUE THREAD

**Issue by andreasHan** [open-mmlab/mmdetection#6871]
**Describe the issue**

mmdetection中定义的swin transformer 的模块与源码中swin transform 的模块名称不同，导致到加载预训练模型时，出现参数名称不匹配，无法加载问题.

比如 源码中的参数： 'layers.0.blocks.0.attn.qkv.weight'  对应mmdetection中实现似乎是：'stages.0.blocks.0.attn.w_msa.qkv.weight'
名称不一致。

**Reproduction**

1. What command or script did you run?

```
python tools/train.py configs/swin/retinanet_swin-t-p4-w7_fpn_1x_coco.py
```

2. What config dir you run?

```
at mmdetection home
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
    在swin.py 中，700 - 704 行修改了如下代码，新增else分支：
```
    for k, v in _state_dict.items():
                if k.startswith('backbone.'):
                    state_dict[k[9:]] = v
                else:
                    state_dict[k] = v
```
   如果不新增else分支，则会出现如下错误：
```
  File "/home/edge/dev/sdh/mmdetection/mmdet/models/backbones/swin.py", line 705, in init_weights
    if list(state_dict.keys())[0].startswith('module.'):
IndexError: list index out of range
````
4. What dataset did you use?
coco

**Environment**

sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda-11.4
NVCC: Build cuda_11.4.r11.4/compiler.30300941_0
GCC: gcc (GCC) 7.3.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.2
OpenCV: 4.5.3
MMCV: 1.3.9
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.4
MMDetection: 2.19.1+

**Results**

```  
File "/home/edge/dev/sdh/mmdetection/mmdet/models/backbones/swin.py", line 728, in init_weights
    table_current = self.state_dict()[table_key]
KeyError: 'layers.0.blocks.0.attn.relative_position_bias_table'
```

**Comment by liuxinyuk** [comment]
set 
`model = dict(backbone=dict(convert_weights=True))`
in your config

**Comment by andreasHan** [comment]
> set `model = dict(backbone=dict(convert_weights=True))` in your config

**Comment by andreasHan** [comment]
thanks, work for me
