### ISSUE TITLE
Is the Faster-RCNN model pretrained on PRW dataset?

### ISSUE THREAD

**Issue by TonyWu199** [open-mmlab/mmdetection#6880]
I have tried Faster-RCNN checkpoint `faster_rcnn_r50_fpn_2x_coco_bbox_mAP-0.384_20200504_210434-a5d8aa15.pth` in **test split** of PRW dataset, and I found the results are totally the ground-truths. I wonder if I have ignored some documentations? Thanks for answering!

**Comment by BIGWangYuDong** [comment]
Hi, did you finetune your PRW dataset?
