### ISSUE TITLE
Questions about the result json file in coco format

### ISSUE THREAD

**Issue by missyoudaisy** [open-mmlab/mmdetection#6890]
Hello! Recently, I run the faster rcnn on customized dataset, and I use

python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py /home/desc/mmdetection/work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_12.pth --format-only --options "jsonfile_prefix=./daisyresult"

to generate the jsonfile. However, the json file only contains 'image_id', 'bbox', 'score', category_id', which is different from coco dataset. Because coco has 'images', 'annotations' and 'categories'. It seems that the result json file only contains 'annotations' part, thus I can't correspond the image_id with its original image name(for example, 0001.jpg).
How can I solve this problem?
Thanks!

**Comment by ZwwWayne** [comment]
jsonfile_prefix is to produce predictions ready for submission. The image_id should be contained in the json file of your annotation and you can use that to link the predictions and images.
