### ISSUE TITLE
error when resume from checkpoing

### ISSUE THREAD

**Issue by ray342659093** [open-mmlab/mmdetection#69]
I try to train a model resume from checkpoint epoch_5.pth, but got the following message:

`Traceback (most recent call last):
  File "tools/train.py", line 84, in <module>
    main()
  File "tools/train.py", line 80, in main
    logger=logger)
  File "/home/rusu5516/anaconda3/envs/pytorch4/lib/python3.5/site-packages/mmdet-0.5.0+c21ff08-py3.5.egg/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/rusu5516/anaconda3/envs/pytorch4/lib/python3.5/site-packages/mmdet-0.5.0+c21ff08-py3.5.egg/mmdet/apis/train.py", line 117, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/rusu5516/anaconda3/envs/pytorch4/lib/python3.5/site-packages/mmcv-0.2.0-py3.5.egg/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/rusu5516/anaconda3/envs/pytorch4/lib/python3.5/site-packages/mmcv-0.2.0-py3.5.egg/mmcv/runner/runner.py", line 262, in train
    self.call_hook('after_train_iter')
  File "/home/rusu5516/anaconda3/envs/pytorch4/lib/python3.5/site-packages/mmcv-0.2.0-py3.5.egg/mmcv/runner/runner.py", line 222, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/rusu5516/anaconda3/envs/pytorch4/lib/python3.5/site-packages/mmcv-0.2.0-py3.5.egg/mmcv/runner/hooks/optimizer.py", line 20, in after_train_iter
    runner.optimizer.step()
  File "/home/rusu5516/anaconda3/envs/pytorch4/lib/python3.5/site-packages/torch/optim/sgd.py", line 101, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: The expanded size of the tensor (480) must match the existing size (64) at non-singleton dimension 1
`

**Comment by hellock** [comment]
How does your config file look like?

**Comment by ray342659093** [comment]
`# model settings
model = dict(
    type='FasterRCNN',
    pretrained='modelzoo://resnet50',
    backbone=dict(
        type='I3D'),
    neck=dict(
        type='FPN',
        in_channels=[192, 480, 832, 1024],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        use_sigmoid_cls=True),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=dict(
        type='SharedFCRoIHead',
        num_fcs=2,
        in_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=25,
        target_means=[0., 0., 0., 0.],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        reg_class_agnostic=False))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        pos_fraction=0.5,
        pos_balance_sampling=False,
        neg_pos_ub=256,
        allowed_border=0,
        crowd_thr=1.1,
        anchor_batch_size=256,
        pos_iou_thr=0.7,
        neg_iou_thr=0.3,
        neg_balance_thr=0,
        min_pos_iou=0.3,
        pos_weight=-1,
        smoothl1_beta=1 / 9.0,
        debug=False),
    rcnn=dict(
        pos_iou_thr=0.5,
        neg_iou_thr=0.5,
        crowd_thr=1.1,
        roi_batch_size=512,
        add_gt_as_proposals=True,
        pos_fraction=0.25,
        pos_balance_sampling=False,
        neg_pos_ub=512,
        neg_balance_thr=0,
        min_pos_iou=0.5,
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(score_thr=0.05, max_per_img=100, nms_thr=0.5))
# dataset settings
dataset_type = 'UCF24Dataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        img_scale=(400,320),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(400,320),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(400,320),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[1, 4])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 5
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/faster_rcnn_r50_fpn_1x'
load_from = None
resume_from = './work_dirs/faster_rcnn_r50_fpn_1x/epoch_4.pth'
workflow = [('train', 1)]
`

here is my config file

I changes some codes in the two_statge_detector file and add a file in the backbone folder. It works fine when I start training from the beginning but got those errors when I tried to resume training from a checkpoint. I also tried to save the epoch4['state_dict'] to a separate file and use the load from to make the checkpoint weights as a pretrained model. It will work.

**Comment by wangduyang** [comment]
have you sloved the problem？
你解决这个问题了吗

**Comment by ray342659093** [comment]
@wangduyang 
No, but I can use the load from function to load a checkpoint weight and continue training, which I think would be similar to the resume from function.

**Comment by wangduyang** [comment]
> @wangduyang
> No, but I can use the load from function to load a checkpoint weight and continue training, which I think would be similar to the resume from function.

how to use the load from function to load a checkpoint weight and continue training?
thank you

**Comment by ray342659093** [comment]
@wangduyang 
save your model weights from your checkpoint. specify your model weights path for load from in the config file, e.g. load_from=/path/to/your/model/weights/. comment the warm up setting and set up the proper epoch and learning rate. Then you can use then trained weights as the pretrained model and continue training.

**Comment by wangduyang** [comment]
> @wangduyang
> save your model weights from your checkpoint. specify your model weights path for load from in the config file, e.g. load_from=/path/to/your/model/weights/. comment the warm up setting and set up the proper epoch and learning rate. Then you can use then trained weights as the pretrained model and continue training.

thank you

**Comment by oceanleftsea** [comment]
@wangduyang
Could you please tell me how should I modify the learning rate and epoch parameters? Thank you very much.

**Comment by nex532** [comment]
You can use arguments --resume_from ${CHECKPOINT_FILE}
