### ISSUE TITLE
TypeError: show_result() missing 1 required positional argument: 'class_names'

### ISSUE THREAD

**Issue by chchenhui** [open-mmlab/mmdetection#690]
In the current version of mmdet.apis, when I invoke _show_result()_,  I encounter a problem that needs an argument of _class_names_. But in a former version, it can run without this argument. How should I do?
<img width="728" alt="image" src="https://user-images.githubusercontent.com/13835142/58161723-5fd07d00-7cb3-11e9-951e-0120a6251390.png">

**Comment by hellock** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#high-level-apis-for-testing-images

**Comment by chchenhui** [comment]
OK, thanks for your update.

**Comment by J0KERCHANCE** [comment]
> Please refer to https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#high-level-apis-for-testing-images

Hi there, the link doesn't work anymore, could you please update it? Thank you.
