### ISSUE TITLE
如何在框架下实现半监督训练？

### ISSUE THREAD

**Issue by WandernForte** [open-mmlab/mmdetection#6904]
如题，是否需要额外的包？

**Comment by hhaAndroid** [comment]
@WandernForte I think you can refer to https://github.com/microsoft/SoftTeacher first

**Comment by WandernForte** [comment]
> @WandernForte I think you can refer to https://github.com/microsoft/SoftTeacher first
谢谢，还有一个问题，我可以在没有标注文件的情况下训练半监督数据吗？（刚接触的小白确实不太懂）
thx, one more question, can i train semi-supervised data without ann_file? (Tt may be a stupid question).
