### ISSUE TITLE
how do I train a large dataset that out of memory?

### ISSUE THREAD

**Issue by hyq12358** [open-mmlab/mmdetection#6912]
I want to train a detector based on object365 dataset, but object365 is pretty large, and caused out of memory error in my computer.
I want to split the annotation file to 10, such as ann1,ann2,...ann10, then build 10 datasets and concatenate them, but I'm not sure whether it's
gonna work or not.
Any better suggestion?

**Comment by BIGWangYuDong** [comment]
Hi, Firstly, you can try to set workers_per_gpu = 0 to avoid OOM. Seems that your idea might work, but we haven't verified yet. Your idea is in the plans of MMDet for the next few months.

**Comment by sparshgarg23** [comment]
@BIGWangYuDong  has there been any updates on this issue.I noticed that ZwwWayne marked it as completed.
