### ISSUE TITLE
how to convert solo to onnx?

### ISSUE THREAD

**Issue by dfgan** [open-mmlab/mmdetection#6916]
i am try to convert solo to onnx, but always error. there is some one can help?

**Comment by BIGWangYuDong** [comment]
Here is a PR that has not finished yet,https://github.com/open-mmlab/mmdetection/pull/5967, you can have a look

**Comment by abdulazizm** [comment]
@dfgan Any luck on converting solo to onnx?

**Comment by ZwwWayne** [comment]
As [MMDeploy](https://github.com/open-mmlab/mmdeploy) supported YOLOX export. MMDet will no longer maintain the feature of model export. Please use MMDeploy and create a feature request if you have questions about that.
