### ISSUE TITLE
 How to get the value of precision

### ISSUE THREAD

**Issue by Vegetabhl** [open-mmlab/mmdetection#6923]
I run    python tools/test.py bhl_work/mask_rcnn_r50_fpn_1x_coco.py bhl_work/epoch_12.pth --eval bbox
Got the result of the evaluation

But I have a few points of confusion. The ap value in the result corresponds to the map value. How to get the value of precision and recall?

In addition, how do I change the --eval parameter to proposal and get a new evaluation result, but I don't understand the difference with bbox? If I want to get the precision and recall needed in the object detection paper, which one should I refer to? Thanks

**Comment by ZwwWayne** [comment]
You can use https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/coco_error_analysis.py to do that. bbox and segm means use bbox or segmentation mask when calculating the iou between boxes and masks. Usually, in the published paper like mask r-cnn, they will report both APbbox and APmask, which is obtained by `--eval bbox segm`
