### ISSUE TITLE
instance segmentation

### ISSUE THREAD

**Issue by Cathy1900** [open-mmlab/mmdetection#6929]
I use mask rcnn to complete the instance segmentation, but in the test results the same sample is still uniform color, why their colors are not distinguished? What part of the code do I need to change to make them different colors? Thanks

**Comment by AGanPoi** [comment]
#6228  Maybe you can check this issue that I raise before. In _mmdetection/mmdet/core/visualization/image.py_ Line 160 that you can random select a color for each instance

**Comment by Cathy1900** [comment]
> #6228 Maybe you can check this issue that I raise before. In _mmdetection/mmdet/core/visualization/image.py_ Line 160 that you can random select a color for each instance

thank you

**Comment by AGanPoi** [comment]
已收到 甘伟泽
