### ISSUE TITLE
DCN Deformable Group Parameter Set

### ISSUE THREAD

**Issue by HarveyGuo960817** [open-mmlab/mmdetection#693]
Hello, when the parameter of DCN deformable group parameter is set to >1,  the code raise errors.

I use ResNext101 + DCNv2, my config is like this:

_backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=64,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch',
        dcn=dict(
            modulated=True,
            groups=64,
            deformable_groups=1,
            fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True))_

how to solve the problem?

**Comment by muyuuuu** [comment]
you can find DCN config files here: https://github.com/open-mmlab/mmdetection/tree/master/configs/dcn
