### ISSUE TITLE
Panoptic Segmentation Error

### ISSUE THREAD

**Issue by Cathy1900** [open-mmlab/mmdetection#6930]
I would like to complete the Panoptic Segmentation (mmdetection 2.19) using the following code (i.e., tools/single_inference.py)：
- from mmdet.apis import init_detector, inference_detector
- config_file = './configs/panoptic_fpn/panoptic_fpn_r50_fpn_1x_coco.py'
- checkpoint_file = 'checkpoints/panoptic_fpn_r50_fpn_1x_coco_20210821_101153-9668fd13.pth'
- 
- model = init_detector(config_file, checkpoint_file, device='cuda:0')
- img = './data/coco/val2017/000000146831.jpg'
- result = inference_detector(model, img)
- model.show_result(img, result, out_file='result.jpg', score_thr=0.5)

But I get the following error：
- Traceback (most recent call last):
-   File "tools/single_inference.py", line 8, in <module>
-     model.show_result(img, result, out_file='result.jpg', score_thr=0.5)
-   File "/raid/xxx/mmdetection-master/mmdet/models/detectors/base.py", line 323, in show_result
-     for i, bbox in enumerate(bbox_result)
-   File "/raid/xxx/mmdetection-master/mmdet/models/detectors/base.py", line 323, in <listcomp>
-     for i, bbox in enumerate(bbox_result)
- AttributeError: 'str' object has no attribute 'shape'

How should I solve this problem? Thanks

**Comment by nikky4D** [comment]
I'm running into something similar as well. Were you able to solve the problem?

**Comment by RangiLyu** [comment]
Panoptic segmentation visualization is working in progress. We will create a PR recently and support this feature in the next version.

**Comment by AronLin** [comment]
The visualization for panoptic segmentation is implemented. So this PR will be closed.
