### ISSUE TITLE
cpu memory leaking when train on my own dataset  with yolof内存泄漏

### ISSUE THREAD

**Issue by pumpkin33498** [open-mmlab/mmdetection#6931]
I find that the buff/cache continue to increase when training my own dataset. 
I use "top" command in the terminal to check my memory.

训练过程中经常死机，检查的时候buff/cache一直在增加，一度到了55GB....(总共64GB运行内存)，目前跑的是yolof，是哪里出现内存泄露了嘛

**Comment by RangiLyu** [comment]
Please provide more information like your config and training command and running environment etc.

**Comment by Syencil** [comment]
实际上不光是mmdet存在内存泄漏 是使用了pytorch的dataloader并且worker > 0就会出现
可参考https://github.com/pytorch/pytorch/issues/13246
建议mmdet或者mmcv将这部分考虑进去

**Comment by mitming** [comment]
> 实际上不光是mmdet存在内存泄漏 是使用了pytorch的dataloader并且worker > 0就会出现 可参考[pytorch/pytorch#13246](https://github.com/pytorch/pytorch/issues/13246) 建议mmdet或者mmcv将这部分考虑进去

@RangiLyu Have you solved this issue?

**Comment by xrrain** [comment]
any update for this problem?
