### ISSUE TITLE
运行tools/analysis_tools/analyze_logs.py绘制接着checkpoint训练产生的日志文件会报错

### ISSUE THREAD

**Issue by jt-z** [open-mmlab/mmdetection#6933]
会在迭代到checkpoint对应的第一个epoch时找不到对应的metric键，把epochs中的checkpoint对应的值去掉后正常了。
因为自己的log文件时从epoch4对应的checkpoint文件继续训练的，而epoch4的log内容没有记录下来，所以导致了该报错。于是删除checkpoint4的那个epoch后正常,在`tools/analysis_tools/analyze_logs.py`文件中49行下添加下面的代码后正常：` epochs = epochs[1:]`，可能需要添加一个checkpoint的参数？

**Comment by zytx121** [comment]
Should be a problem of incomplete log.
