### ISSUE TITLE
swin infer speed too slowly

### ISSUE THREAD

**Issue by congjianting** [open-mmlab/mmdetection#6937]
hi,

thanks for good work, recently i have trained a swin mask rcnn pth.
then i use it for inference, i found the speed is too slowly, and gpu memeroy only occupys 2GB, 
but my gpu memory should have 11GB.

someone knowns why?

**Comment by wywywy01** [comment]
try batch mode，just set batch size to 8，16 or  more [code line；](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/benchmark.py#L67)

**Comment by HelloSZS** [comment]
i modified the codes, set batch size to 16

https://github.com/HelloSZS/mmdetection_modified_tools
