### ISSUE TITLE
How to optimize inference time?

### ISSUE THREAD

**Issue by kimnamu** [open-mmlab/mmdetection#6939]
### Discussed in https://github.com/open-mmlab/mmdetection/discussions/6919

<div type='discussions-op-text'>

<sup>Originally posted by **kimnamu** December 29, 2021</sup>
As you know, inference time depends on the hardware performance.
But in the inference time(fps) table, there is no hardware specification.

For example, the fps of retinanet fp16 model is 31.6 fps, but it is not easy to achieve a similar speed.
Can I guess the same hardware on the same table?  So could you tell me which GPU is your standard?</div>

First of all, thank you for great open source.
The above question is different from the speed I measure, so I asked to know the reason.

I am comparing various models for inference time optimization. 
From what I've found, there seems to be a conversion to tensorRT (https://github.com/grimoire/mmdetection-to-tensorrt) or batch inference. 
Is there any other way? For example, freeze variables on keras.

**Comment by RangiLyu** [comment]
The inference speed is tested on Nvidia Tesla V100.

To speed up inference, you can try to fuse BN and turn on FP16 inference.
