### ISSUE TITLE
ImportError: cannot import name 'init_detector'

### ISSUE THREAD

**Issue by hasiftwistcode** [open-mmlab/mmdetection#694]
Been trying this for a few times by changing `pip3 install cython` , `pip3 install Cython`, `python3 setup.py develop`, `pip3 install -e .` and `pip3 install .` but still couldn't work as expected when trying to run inference script at this [link](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#high-level-apis-for-testing-images)

Thanks for your help!

**Comment by blateyang** [comment]
Hello, I met with the same problem. Have you solved this problem?  If so, can you tell me how to solve it. Thanks in advance!@hasiftwistcode

**Comment by estimoelmo** [comment]
Give details about your OS, pytorch version etc @blateyang
