### ISSUE TITLE
Whether the pre-trained backbone is loaded correctly?

### ISSUE THREAD

**Issue by qsunyuan** [open-mmlab/mmdetection#6943]
I just used the faster-rcnn detector with backbone res50.

When I set the config as:
init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')
The logger file output: 
PretrainedInit: load from torchvision://resnet50

However, when I set the config as: 
init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet101')
The logger file output: 
PretrainedInit: load from torchvision://resnet101 

I wanna check whether the pre-trained model is loaded correctly?

For example, I use the mobilenetv2 as my backbone,  but I load the the PVT pretrained backbone, the looger output:
The value is the same before and after calling `init_weights` of FasterRCNN  
It seems right, they don't match.

But when I use PVT as my backbone, the pretrained model is not downlaod from openmmlab or torchvision, so Whether the pre-trained backbone is loaded correctly?

Hope to get ur reply early. 

Thx.

**Comment by qsunyuan** [comment]
I got the logger output:
Initialized by user-defined `init_weights` xxx

**Comment by qsunyuan** [comment]
I used some pretrained backbone from mmclassification?
Is that right?

https://mmclassification.readthedocs.io/en/latest/model_zoo.html

For example, Swin-Transformer tiny for the faster-rcnn backbone.

**Comment by qsunyuan** [comment]
Or update https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json?

**Comment by ZwwWayne** [comment]
They are indeed downloaded from torchvision because they are hosted by other groups. If you do not see an error and the results are normal, then it is fine.
