### ISSUE TITLE
Question about the strides in rpn_head and roi_head

### ISSUE THREAD

**Issue by AGanPoi** [open-mmlab/mmdetection#6944]
In the config file that:
_rpn_head=dict(anchor_generator=dict(strides=[4, 8, 16, 32, 64]))_
but the _roi_head=dict(bbox_roi_extractor=dict(featmap_strides=[4, 8, 16, 32]))_
I wonder why in _bbox_roi_extractor_ or _mask_roi_extractor_, it only use four feature map strides, but in _anchor_generator_, it use five feature map strides as the same of fpn outputs?
If I can use five strides that is [4, 8, 16, 32, 64] in _bbox_roi_extractor_ or _mask_roi_extractor_?

**Comment by AronLin** [comment]
> in bbox_roi_extractor or mask_roi_extractor, it only use four feature map strides

Because only first four feature maps are fed to `roi_exactor`

> If I can use five strides that is [4, 8, 16, 32, 64] in bbox_roi_extractor or mask_roi_extractor?

Yes.

**Comment by AGanPoi** [comment]
已收到 甘伟泽
