### ISSUE TITLE
help! Anyone could tell me where should I set the batch size in mmdet?tks

### ISSUE THREAD

**Issue by gtwell** [open-mmlab/mmdetection#695]

**Comment by OceanPang** [comment]
Batch_size = [imgs_per_gpu](https://github.com/open-mmlab/mmdetection/blob/2b8ad3e0d9d60f70a6cb1d0952c41ad0d1beb1fb/configs/fast_mask_rcnn_r50_fpn_1x.py#L78) * num of gpu you used

**Comment by alaa-shubbak** [comment]
but i still don't know where to write this instruction 
i have two GPUs and set the imgs_per_gpu =6 
the batch size will be 12

but where shall i but this instruction  
`batch_size=12 `
