### ISSUE TITLE
Crop operation for PolygonMasks

### ISSUE THREAD

**Issue by chufengt** [open-mmlab/mmdetection#6950]
For the `Crop` operation designed for the PolygonMasks structure (lines 687~714 in structures.py), some points of the polygon might be outside the box (i.e., the coordinates are negative) after cropping.

Conceptually, the intersection points between polygon and box should be added (and removed the outside points), but such a process was not implemented in the following code.

I noticed the comment “pycocotools will clip the boundary”, but I didn't find how to deal with such a problem in pycocotools.

Could you give me some suggestions?

```python
def crop(self, bbox):
    """see :func:`BaseInstanceMasks.crop`"""
    assert isinstance(bbox, np.ndarray)
    assert bbox.ndim == 1

    # clip the boundary
    bbox = bbox.copy()
    bbox[0::2] = np.clip(bbox[0::2], 0, self.width)
    bbox[1::2] = np.clip(bbox[1::2], 0, self.height)
    x1, y1, x2, y2 = bbox
    w = np.maximum(x2 - x1, 1)
    h = np.maximum(y2 - y1, 1)

    if len(self.masks) == 0:
        cropped_masks = PolygonMasks([], h, w)
    else:
        cropped_masks = []
        for poly_per_obj in self.masks:
            cropped_poly_per_obj = []
            for p in poly_per_obj:
                # pycocotools will clip the boundary
                p = p.copy()
                p[0::2] = p[0::2] - bbox[0]
                p[1::2] = p[1::2] - bbox[1]
                cropped_poly_per_obj.append(p)
            cropped_masks.append(cropped_poly_per_obj)
        cropped_masks = PolygonMasks(cropped_masks, h, w)
    return cropped_masks
```

**Comment by hhaAndroid** [comment]
@chufengt I'm guessing that means the `polygon_to_bitmap` function. When training with PolygonMasks, pycocotools will be called to convert it to a mask.  `PolygonMasks.to_ndarray() -> polygon_to_bitmap`
