### ISSUE TITLE
model inference same class object bbox overlap 

### ISSUE THREAD

**Issue by dimimal** [open-mmlab/mmdetection#6953]
I face a very weird behavior during model inference. I noticed that my instance segmentation model produces predictions of the same class where the bbox of one object is entirely encircled by the second one. 

My issue is not similar to this #6254 where my colleague presents an issue with different bbox overlaps.

Has anyone faced a similar issue before?

**Comment by RangiLyu** [comment]
Could you provide more information? Such as what config did you run and how do the inference results look like?
