### ISSUE TITLE
What's the 'Memory' of the result mean?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6954]
![image](https://user-images.githubusercontent.com/86214036/148322634-e22e22aa-1dbe-4aa5-9031-22ef74199346.png)
I want to know the Memory mean. And the Memory is GB or M?

**Comment by MaxVanDijck** [comment]
Memory is the GPU VRAM used in MB

**Comment by lijoe123** [comment]
Well, Thank you! 
By the way, i want to know how to get the model size?

**Comment by MaxVanDijck** [comment]
run `get_flops.py` with the path to a config file eg:
```
python tools/analysis_tools/get_flops.py configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_1x_coco.py
```
https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/get_flops.py

This will give you the number of parameters,  multiply this by 4 (32 bit float) to get the number of bytes of the model.

**Comment by lijoe123** [comment]
Thank you ! So nice of you!
