### ISSUE TITLE
where is the code to copy training input img to gpu in mmdetection? 

### ISSUE THREAD

**Issue by achao2013** [open-mmlab/mmdetection#6957]
I want to find the code where the input img for trainning is copyed to gpu. In  function to_tensor of formatting.py, i can see the code which convert numpy array to torch tensor, but where is the .cuda() or to(device) operator for the input img?

**Comment by achao2013** [comment]
@hellock  @ZwwWayne

**Comment by achao2013** [comment]
@hhaAndroid @jshilong  can anyone help me?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmcv/blob/86ed509a8bc783cdd0617efeba257375d5aa6658/mmcv/parallel/distributed.py#L50

**Comment by achao2013** [comment]
> https://github.com/open-mmlab/mmcv/blob/86ed509a8bc783cdd0617efeba257375d5aa6658/mmcv/parallel/distributed.py#L50

So that is what it is， thank you very much @hellock
