### ISSUE TITLE
Error for loading pretrained backbone of swin

### ISSUE THREAD

**Issue by JarvisKevin** [open-mmlab/mmdetection#6960]
when loading the pretrained backbone of swin downloading from https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth, there is no 'backbone' in the state_dict's key. Therefore, the state_dict from [https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/swin.py](url) will be an empty dict.
` state_dict = OrderedDict()
            for k, v in _state_dict.items():
                if k.startswith('backbone.'):
                    state_dict[k[9:]] = v`

**Comment by shinya7y** [comment]
`convert_weights=True` adds 'backbone.' prefix.
https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/utils/ckpt_convert.py#L135

**Comment by ShengliLiu** [comment]
In the `configs/swin/retinanet_swin-t-p4-w7_fpn_1x_coco.py`, add `convert_weights=True` to the dict `backbone` in the dict `model`.
