### ISSUE TITLE
How to add an image with WandbLoggerHook?

### ISSUE THREAD

**Issue by ytzhao** [open-mmlab/mmdetection#6962]
Hi everyone, 

I'm trying to plot a image tensor(a heatmap/reference result of the model) with WandbLoggerHook, is there any tutorial document or anyone has some ideas? I could not find anyone. 

To plot a scalar value with WandbLoggerHook in mmdetection is easy, but it is kinda difficult and different to plot an image or a 3D point cloud. 

If anyone has an idea, could you share the solution? Thanks very much.

**Comment by morganmcg1** [comment]
@ytzhao, I'm from W&B, we might have capacity to upgrade this hook in a couple of months, but you could modify the WandbLoggerHook yourself, see the [W&B docs here](https://docs.wandb.ai/guides/track/log/media) to log different media types for example

**Comment by ytzhao** [comment]
@morganmcg1 Thanks morgan, i found a way to work around. As you said, I reimplement the WandbLoggerHook to make images to show. ;-)
