### ISSUE TITLE
What's the formatting standard used in python code formatter?

### ISSUE THREAD

**Issue by DianCh** [open-mmlab/mmdetection#6964]
Hi! I've been using yapf formatter in vscode but it looks like the formatting in mm-series is not yapf. May I ask what format standard does mm-series use? Thanks!

**Comment by shinya7y** [comment]
The formatter is yapf (https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md#code-style)
with the settings below:
https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/setup.cfg#L10-L13

**Comment by DianCh** [comment]
Thank you! I was missing these settings.
