### ISSUE TITLE
多光谱检测 multispectral object detection

### ISSUE THREAD

**Issue by DocF** [open-mmlab/mmdetection#6977]
与之前的Issue#1287类似。
请问如何构建多模态的数据集的dataloader，满足网络双流的输入，比如配对的可见光和红外图片。
期待您的回答，十分感谢。 @open-mmlab

Similar to the previous Issue#1287.
How to build a dataloader of multi-modal data sets to meet the input of network dual-stream, such as paired visible and infrared images.
Looking forward to your answer, thank you very much！

**Comment by DocF** [comment]
@openmmlab-bot

**Comment by RangiLyu** [comment]
You can implement a new `LoadImageFromFile` pipeline to load multiple images.

**Comment by DocF** [comment]
Thanks for your quick reply, I will try to do it.

**Comment by DocF** [comment]
> You can implement a new `LoadImageFromFile` pipeline to load multiple images.

Hi @RangiLyu，how can I debug and test the  `LoadImageFromFile` pipeline.
Can I just test the pipeline，not the model training？

**Comment by RangiLyu** [comment]
> how can I debug and test the LoadImageFromFile pipeline.
> Can I just test the pipeline，not the model training？

You can write a simple unit test to test this module.
You can refer to tests/test_data/test_pipelines/test_loading.py
