### ISSUE TITLE
Errors about evaluation metric

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#6978]
In dataset config I set
`evaluation = dict(interval=1, metric='mAP', save_best='mAP')`
watched the model be trained for an epoch before the first evaluation, where I got an error
`KeyError: 'metric mAP is not supported'`.

I am not using original mmdetection but a modified mmdetection folder. I would like to know how to solve this error. Thank you.

**Comment by RangiLyu** [comment]
Which dataset did you use? If you used CocoDataset, the metric should be 'bbox'.

**Comment by DrX2020** [comment]
Customized dataset annotated in COCO format and my dataset type is CocoDataset. Now I get the reason. CocoDataset type is  supposed to be evaluated in 'bbox' metric, right?

**Comment by RangiLyu** [comment]
You are right.

**Comment by DrX2020** [comment]
Thank you for solving the previous question. Is it possible to customize a dataset type that is annotated in COCO format but can be evaluated in 'mAP' metric?

**Comment by RangiLyu** [comment]
You may need to combine the `evaluate` function in mmdet/datasets/voc.py with your dataset with the coco format annotation file.

**Comment by DrX2020** [comment]
I will try and do this. Thank you so much!
