### ISSUE TITLE
Get the bbox coordinates for predications

### ISSUE THREAD

**Issue by Ferial-stuck** [open-mmlab/mmdetection#6979]
Hey, I want thank all **mmdetection** team for this wonderful work. And I am working on project where I need to do some modifications on mmdet/apis/test.py file  to get bbox coordinates for the predications and write them into txt files for each image.Since I am new to pytorch and mmdetection I was tracing the code and trying to figure out the value that results list have but I facing problem to find the definition for the method at line number 57 since I need o know what is the value show_result() will return. 

`model.module.show_result(
                    img_show,
                    result,
                    show=show,
                    out_file=out_file,
                    score_thr=show_score_thr)`

**Comment by RangiLyu** [comment]
You can refer to:
https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/detectors/base.py#L271
