### ISSUE TITLE
Color setting for bounding box

### ISSUE THREAD

**Issue by wliebtzy** [open-mmlab/mmdetection#6980]
Hello maintainers,
I have successfully reimplemented the Faster RCNN under mmdet. After inference, the bboxs in the result images show only the color orange. Since my custom dataset has 7 categories, I wanna ask if  I can offer a set of colors(7) to render the bboxs according to the categories? I have checked the function "show_result_pyplot", but the color set is fixed.

Best regards!

**Comment by RangiLyu** [comment]
This feature is working in progress.
Refer to #6716

**Comment by wliebtzy** [comment]
> This feature is working in progress. Refer to #6716
Got it! Thank you for your work and rapid response!

**Comment by wliebtzy** [comment]
> This feature is working in progress. Refer to #6716

Hello, I have tried following the suggestion you provided. All changed code has been modified. I don't use the demo but customizing a test.py which follows "/tools/test.py" in[ swin-transformer object detection](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/tools/test.py). But now the result remains still only one color. Do you have some advice?

**Comment by wliebtzy** [comment]
Should I reinstall or recompile the mmdetection after modifying?

**Comment by wliebtzy** [comment]
Solved! Thanks!

**Comment by TonojiKiobya** [comment]
Can you share, how did you do it?

**Comment by wang1528186571** [comment]
> 解决了！谢谢！

can share for us .
