### ISSUE TITLE
Anchor sizes in mmdetection

### ISSUE THREAD

**Issue by VikasRajashekar** [open-mmlab/mmdetection#6981]
Hello,

I was going through the documentation at https://mmdetection.readthedocs.io/en/latest/tutorials/config.html. 

`anchor_generator=dict(  # The config of anchor generator
            type='AnchorGenerator',  # Most of methods use AnchorGenerator, SSD Detectors uses `SSDAnchorGenerator`.
            scales=[8],  # Basic scale of the anchor, the area of the anchor in one position of a feature map will be scale *base_sizes
            ratios=[0.5, 1.0, 2.0],  # The ratio between height and width.
            strides=[4, 8, 16, 32, 64]),  # The strides of the anchor generator. This is consistent with the FPN feature strides. The strides will be taken as base_sizes if base_sizes is not set.`
            
            **Here you say that the Area of Anchor is   scaleXbase_sizes**

So in the given example: 
Is the generated anchor of size **32X32, 64X64, 128X128,256X256,520X520**???? 

Or os it just that the area of each Anchor is **lengthXwidth=32,64,128,256,520**????

The main question is **scale*base size** the **area of the anchor box**, or **the length of the side of the anchor box**?

**Comment by hhaAndroid** [comment]
it means that base anchor size is 32X32, 64X64, 128X128,256X256,520X520.
