### ISSUE TITLE
Size of Inference segmentation image

### ISSUE THREAD

**Issue by SSZ1** [open-mmlab/mmdetection#6982]
I used PolarMask to train the small size image and infer the same size images.   The result image's size is not the same as the original image.  So how shall I do to inference on the origin-size image?   I wanna know how to change the inference size.
Somebody help? Thx.

**Comment by jshilong** [comment]
We do not support PolarMask officially, you can create an issue in the original repo

**Comment by SSZ1** [comment]
Thanks
