### ISSUE TITLE
'init_cfg and pretrained cannot be specified at the same time'

### ISSUE THREAD

**Issue by crazysboy** [open-mmlab/mmdetection#6983]
'init_cfg and pretrained cannot be specified at the same time' 想请问一下这个错误怎么解决，不太清楚怎么造成的

**Comment by RangiLyu** [comment]
`pretrained` and `init_cfg` can not be set at the same time in your config.

**Comment by saadyousuf45** [comment]
I am getting the same error, how do I resolve this?
