### ISSUE TITLE
尝试输出cascade_rcnn到pickle时出现【'ConfigDict' object has no attribute 'eval'】

### ISSUE THREAD

**Issue by WandernForte** [open-mmlab/mmdetection#6984]
这个模型可以添加eval关键字吗？如果可以我需要怎么更改配置文件呢？

**Comment by jshilong** [comment]
Would you mind giving more details

**Comment by WandernForte** [comment]
> Would you mind giving more details

我只是普通地调用了multi_gpu_test, single_gpu_test这两个函数。。。
I just used two functions: multi_ gpu_test, single_ gpu_ test

**Comment by WandernForte** [comment]
> > Would you mind giving more details
> 
> 我只是普通地调用了multi_gpu_test, single_gpu_test这两个函数。。。 I just used two functions: multi_ gpu_test, single_ gpu_ test

yolo seems ok, but cascade_rcnn dosen't work.
