### ISSUE TITLE
The reference of schedule_1X and schedule_2X 

### ISSUE THREAD

**Issue by MSTK2014** [open-mmlab/mmdetection#6987]
Are schedule_1X and schedule_2X referenced or proposed by you? Could you please tell me the reference of schedule_1X and schedule_2X?

**Comment by MSTK2014** [comment]
I mean the set of step in lr_config

**Comment by shinya7y** [comment]
As written in https://arxiv.org/abs/1906.07155 , "The training schedule is the same as Detectron [10]."

Details: https://github.com/open-mmlab/mmdetection/issues/5296
