### ISSUE TITLE
why remove the relu after P6 in  FPN of the retinanet?

### ISSUE THREAD

**Issue by Bilibilee** [open-mmlab/mmdetection#6988]
hi , I read in code of FPN , and the [relu_before_extra_convs](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/necks/fpn.py#L69) constructor  parameter catches my eye , but in the [config of retinanet](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/retinanet_r50_fpn.py#L14),  relu_before_extra_convs is False.
In the original RetinaNet paper, there is a relu before the conv after P6 of FPN, while in this repo the relu is removed. Is this an intended behavior?

The question is also mentioned in [issue](https://github.com/open-mmlab/mmdetection/issues/945)

**Comment by jshilong** [comment]
There is no difference of performance, this argument is added to align some third party implementations of one-stage detectors
