### ISSUE TITLE
网络摄像头的fps

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#6989]
尝试使用webcam_demo.py（使用mask_rcnn）.为什么显示的结果的fps很低呢？该如何提升获取摄像头结果的fps呢？

**Comment by RangiLyu** [comment]
Please follow the issue template to provide more information. E.g. which config did you use and what device are you using.

**Comment by kankanzheli** [comment]
我是用的是mask_rcnn.只把处理过程中的分辨率从（1333，800）修改为（1280,720）
设备的话我是在gazebo内设置的kinect摄像机。从ros话题将图像信息接受直接获得img这一信息。然后直接在webcam_demo.py的model函数对img信息进行处理获取结果。
