### ISSUE TITLE
Need help for compatible old and new version mmcv

### ISSUE THREAD

**Issue by wliebtzy** [open-mmlab/mmdetection#6992]

**Comment by wliebtzy** [comment]
Hello maintainers,

I'm trying to implement the Reppoints V2 on mmdetection 2.X. There exists an error " KeyError: ConvWS is already registered in conv layer".  The old version mmdetection has a folder named"/mmdet/ops" which is the dependency on Reppoints V2 code. Now I install only the new version and can't find the folder. How should I modify my code to adapt to the new mmdet?

**Comment by RangiLyu** [comment]
The ops in mmdetection has been moved into mmcv-full.

**Comment by RangiLyu** [comment]
compatibility between 2.x and 1.x can refer to https://mmdetection.readthedocs.io/en/latest/compatibility.html#compatibility-with-mmdetection-1-x
