### ISSUE TITLE
I train models "without" using docker but I meet "unexpected bus error encountered in worker, This might be caused by insufficient shared memory (shm)"

### ISSUE THREAD

**Issue by LeungWaiHo** [open-mmlab/mmdetection#6993]
I train models "without" using docker but I meet "unexpected bus error encountered in worker, This might be caused by insufficient shared memory (shm)"
I search for solutions to solve it but all of them tell to enlarge the shm on docker, but I do not use docker to train the models? How I can solve it? Thanks!

**Comment by RangiLyu** [comment]
Maybe you need to enlarge the shm of your system.
