### ISSUE TITLE
AssertionError: CascadeRCNN: ResNet: init_cfg and pretrained cannot be specified at the same time

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#6996]
I am currently training models on customized dataset annotated in COCO format. At first I trained a Faster R-CNN r50 and no error occured. However, when changing the model to Cascade R-CNN r101, I got:
> AssertionError: CascadeRCNN: ResNet: init_cfg and pretrained cannot be specified at the same time
at the beginning of the training. Now I am wondering how to solve the error.

**Comment by RangiLyu** [comment]
Do not set `init_cfg` and `pretrained` at the same time in your config.

**Comment by eilenelxc** [comment]
Do not set init_cfg and pretrained at the same time in your config.

**Comment by eilenelxc** [comment]
How do I set it so that it doesn't exist at the same time?
