### ISSUE TITLE
FCOS Model Zoo wights

### ISSUE THREAD

**Issue by RaymondKirk** [open-mmlab/mmdetection#700]
With the introduction of FCOS DNN, is their a plan to host the respective weights also on model zoo?

**Comment by hellock** [comment]
It's already in the model zoo.

**Comment by RaymondKirk** [comment]
> It's already in the model zoo.

In the COCO model zoo? Could you provide a link? I checked here: https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/README.md

**Comment by RaymondKirk** [comment]
Cheers!
