### ISSUE TITLE
Changing Confidence threshold during Testing

### ISSUE THREAD

**Issue by pfuerste** [open-mmlab/mmdetection#7002]
I am trying to change the threshold with which my model discards detections when calling test.py.
I use DDETR and would like to see how much better my model performs if I allow less confident detections for evaluation.
Is there a parameter for this which I just cant find? I tried to follow CoCoEval, but cant wrap my head around it.

**Comment by jshilong** [comment]
We do not support it for the time being, but you can implement it by minor modification in detrhead
