### ISSUE TITLE
Training a customised model

### ISSUE THREAD

**Issue by SourabhRanade** [open-mmlab/mmdetection#7007]
I am trying to make some changes to an existing model. I have then saved the model using the `toch.save(model.state_dict(),path_to_save)` method of PyTorch. Now, in order to train this particular model.I have made use of the load_from parameter in the train_config file. I can see the following command in the logs generated of the train.py file --> 
`load_from = '/home/sourabh/Project/mmdetection/checkpoints/model_lrt.pth'`

I wanted to make sure that this is the right way of doing this. If not, what is the correct way of doing this?

**Comment by jshilong** [comment]
yes, there is no problem following your description

**Comment by SourabhRanade** [comment]
@jshilong Thank you. However, I have a follow-up question to this. When I train this model see that the model size increases.
So, initially, I am using the following model : 
```
!wget -c https://download.openmmlab.com/mmdetection/v2.0/swin/mask_rcnn_swin-t-p4-w7_fpn_1x_coco/mask_rcnn_swin-t-p4-w7_fpn_1x_coco_20210902_120937-9d6b7cfa.pth \
    -O checkpoints/mask_rcnn_swin-t-p4-w7_fpn_1x_coco_20210902_120937-9d6b7cfa.pth

from mmdet.apis import init_detector, inference_detector

config='/home/sourabh/Project/mmdetection/configs/swin/mask_rcnn_swin-t-p4-w7_fpn_1x_coco.py'
# Setup a checkpoint file to load
checkpoint = '/home/sourabh/Project/mmdetection/checkpoints/mask_rcnn_swin-t-p4-w7_fpn_1x_coco_20210902_120937-9d6b7cfa.pth'

# initialize the detector
model = init_detector(config,checkpoint)
```
The checkpoint file for this is around 180 MB .

And then I make some changes to the model and use this model in the way I mentioned in the question. The training is still going on and after each epoch, the checkpoint file is saved under `work_dirs`. 
The size of these .pth files now goes to around 500MB. I wanted to know if I have done something wrong or is this the normal expected behavior?

**Comment by SourabhRanade** [comment]
Okay thank you @jshilong
