### ISSUE TITLE
add support for facebookresearch/detic

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmdetection#7008]
Its a high performing zero shot object detector with changeable vocabulary: https://github.com/facebookresearch/Detic

**Comment by RangiLyu** [comment]
Thanks for your suggestion! We will take it into our feature backlog. And welcome to create a PR if anyone wants to implement it.

**Comment by hhaAndroid** [comment]
@fcakyon This should be implemented in mmfewshot.

**Comment by fcakyon** [comment]
@hhaAndroid but that repo is not active as mmdet

**Comment by Edwardmark** [comment]
+1
