### ISSUE TITLE
discreapancy in yolo-tiny config

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmdetection#7009]
in yolox readme, its says 416 as the input size for yolo-tiny: https://github.com/open-mmlab/mmdetection/tree/master/configs/yolox#results-and-models

but in yolo-tiny config file, training input size is 640: https://github.com/open-mmlab/mmdetection/blob/master/configs/yolox/yolox_tiny_8x8_300e_coco.py#L10

is this normal or should it 416 in the config file?

**Comment by shinya7y** [comment]
It looks abnormal but it may be suitable to reproduce the setting of YOLOX 0.1.1pre.

The official YOLOX repo added `input_scale = (416, 416)` to the `yolox_tiny` config on 23 Aug 2021.
https://github.com/Megvii-BaseDetection/YOLOX/commit/15e87259399a0f6900d0c065a9aaae18fe83a771#diff-a2d14f9117d036411b1995d2a94aac3b8befd62b41bd8368c6d101d781491bed

The latest official weights (0.1.1pre) on 19 Aug 2021 probably were trained before the fix.
https://github.com/Megvii-BaseDetection/YOLOX/blob/main/docs/model_zoo.md
https://github.com/Megvii-BaseDetection/YOLOX/releases

It is worth adding another config and checking the results.

**Comment by hhaAndroid** [comment]
@fcakyon This is Normal.

**Comment by fcakyon** [comment]
@hhaAndroid which one is the correct input size for yolo-tiny then? 416 or 640?

**Comment by hhaAndroid** [comment]
640 for training and 416 for testing

**Comment by wep21** [comment]
Currently 416 for training and 416 for testing in original repo. (https://github.com/Megvii-BaseDetection/YOLOX/blob/de064993d9c105f0eecce405f1e13a45947a8e00/exps/default/yolox_tiny.py#L15-L18)
Does the difference have any effect on accuracy or training cost?

**Comment by hhaAndroid** [comment]
> Currently 416 for training and 416 for testing in original repo. (https://github.com/Megvii-BaseDetection/YOLOX/blob/de064993d9c105f0eecce405f1e13a45947a8e00/exps/default/yolox_tiny.py#L15-L18) Does the difference have any effect on accuracy or training cost?

Oh, maybe they updated again recently
