### ISSUE TITLE
upload experiment artifacts to aws

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmdetection#7012]
Is it possible to use aws s3 uri as `work_dir`?

I see `PetrelBackend` in https://mmcv.readthedocs.io/en/latest/_modules/mmcv/fileio/file_client.html supports s3. Does mmdet support that?

**Comment by hhaAndroid** [comment]
@zhouzaida

**Comment by zhouzaida** [comment]
> Is it possible to use aws s3 uri as `work_dir`?
> 
> I see `PetrelBackend` in https://mmcv.readthedocs.io/en/latest/_modules/mmcv/fileio/file_client.html supports s3. Does mmdet support that?

Hi @fcakyon , we will support `AWS` next month.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 12 days.

**Comment by fcakyon** [comment]
@zhouzaida @hhaAndroid i am waiting for this feature but you can close the issue :+1:

**Comment by zhouzaida** [comment]
Hi @fcakyon , there is a PR to support this feature. https://github.com/open-mmlab/mmcv/pull/1545
