### ISSUE TITLE
train deformable detr on colab gives: RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by prosperopapaleo** [open-mmlab/mmdetection#7017]
Hi guys, I'm getting "cuDNN error: CUDNN_STATUS_NOT_INITIALIZED" when train deformable detr, running again gives "RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1." 

The config is the same, I've just changed the number of classes and I use a standard dataset in coco-format.

It's quite strange beacuse I've trained ddetr for 3 weeks without any problems. 

The only difference that I noted is the version of mmdet came up to 2.20, I downgraded it to 2.19.1 but still have the problem, I tryed also to upgrade pytorch and cuda to 1.13 but it didn't work.

I'm using colab, some settings are:

torch: 1.10.0+cu111
torchvision: 0.11.1+cu111
mmdet: 2.19.1
cuda-compiler: 11.1
GCC 7.3

!nvcc --version:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

!nvidia-smi:

![Immagine 2022-01-17 114423](https://user-images.githubusercontent.com/50454998/149755458-881932f5-e23f-4ffa-ace4-662f3eb7fedf.png)

thanks.

**Comment by RangiLyu** [comment]
What's your mmcv version? 

> The only difference that I noted is the version of mmdet came up to 2.20

Did you upgrade mmcv when you upgrade mmdet?

**Comment by prosperopapaleo** [comment]
The problem is with mmcv 1.4.3, downgrading mmcv from 1.4.3 to 1.4.2 now works again, thank you.

**Comment by preminstrel** [comment]
@prosperopapaleo Today I uninstalled the mmcv 1.4.3 and installed mmcv 1.4.2. However, the error occurred again. How can I fix it? Thank yo for your time!

```bash
2022-01-23 09:34:39,343 - mmdet - INFO - workflow: [('train', 1)], max: 50 epochs
2022-01-23 09:34:39,344 - mmdet - INFO - Checkpoints will be saved to /content/gdrive/MyDrive/mmdetection/work_dirs/deformable_detr_r50_16x2_50e by HardDiskBackend.
/usr/local/lib/python3.7/dist-packages/mmdet/models/utils/positional_encoding.py:81: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_feats)
/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "tools/train.py", line 196, in <module>
    main()
  File "tools/train.py", line 192, in main
    meta=meta)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```
![image](https://user-images.githubusercontent.com/60024807/150672648-4e76743c-7d1a-42f5-9362-1c88ebcc921e.png)

**Comment by RangiLyu** [comment]
> @prosperopapaleo Today I uninstalled the mmcv 1.4.3 and installed mmcv 1.4.2. However, the error occurred again. How can I fix it? Thank yo for your time!
> 
> ```shell
> 2022-01-23 09:34:39,343 - mmdet - INFO - workflow: [('train', 1)], max: 50 epochs
> 2022-01-23 09:34:39,344 - mmdet - INFO - Checkpoints will be saved to /content/gdrive/MyDrive/mmdetection/work_dirs/deformable_detr_r50_16x2_50e by HardDiskBackend.
> /usr/local/lib/python3.7/dist-packages/mmdet/models/utils/positional_encoding.py:81: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
>   dim_t = self.temperature**(2 * (dim_t // 2) / self.num_feats)
> /usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> Traceback (most recent call last):
>   File "tools/train.py", line 196, in <module>
>     main()
>   File "tools/train.py", line 192, in main
>     meta=meta)
>   File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/train.py", line 209, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
>     self.call_hook('after_train_iter')
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
>     runner.outputs['loss'].backward()
>   File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 307, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 156, in backward
>     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
> ```
> 
> ![image](https://user-images.githubusercontent.com/60024807/150672648-4e76743c-7d1a-42f5-9362-1c88ebcc921e.png)

How did you install mmcv-full? Try to make sure the pytorch version and cuda version is compatible with mmcv.

**Comment by preminstrel** [comment]
Thanks for your time！ Actually， I installed `mmcv`, not `full-mmcv`. When I installed the `full-mmcv`, the problems were solved!

**Comment by panpanhaha** [comment]
> The problem is with mmcv 1.4.3, downgrading mmcv from 1.4.3 to 1.4.2 now works again, thank you.

thank you！！！！！！！！！！
