### ISSUE TITLE
Problem about change the code.

### ISSUE THREAD

**Issue by zhb654069015** [open-mmlab/mmdetection#703]
1：Is there anything extra I should do after I change the mmdetection code to make it works?
2：Is there anything extra I should do after I change the mmcv code to make it works? To install mmcv I use the commad：pip install . (without -e)，should I  install it again or do something else to update it？

**Comment by OceanPang** [comment]
Refer to the end of [INSTALL.md](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md)
