### ISSUE TITLE
Error: 'eval_res' is empty

### ISSUE THREAD

**Issue by terrancraft** [open-mmlab/mmdetection#7034]
The training proceed normally but fail to evaluate.
I think the eval path is correct but I don't what the problem is.
Here is the screenshot. Thank you !

![Screenshot from 2022-01-19 12-04-38](https://user-images.githubusercontent.com/51820927/150062156-305b5486-ce9f-4bdb-8a97-1e5138aac7cb.png)

**Comment by hhaAndroid** [comment]
This should have been fixed, please tell me your mmcv and mmdet versions.

**Comment by LuooChen** [comment]
We may got [the same problem](https://github.com/open-mmlab/mmdetection/issues/7096)

**Comment by hhaAndroid** [comment]
Resolved by https://github.com/open-mmlab/mmdetection/pull/7101
