### ISSUE TITLE
Support the README for a simple object detection without mask detection

### ISSUE THREAD

**Issue by rose-jinyang** [open-mmlab/mmdetection#7038]
**Describe the feature**
I want the README for simple object detection without mask detection
**Motivation**
I am going to train a simple object detection model with SwinTransformer based RetinaNet.
I can NOT find an exact README for training a model detecting ONLY bounding box without a mask.

**Comment by jbwang1997** [comment]
The Swin is a general backbone in mmdetection. You can replace the backbone of other detectors with the Swin backbone.

**Comment by hhaAndroid** [comment]
@rose-jinyang You can refer to https://github.com/open-mmlab/mmdetection/blob/98949809b7/configs/swin/retinanet_swin-t-p4-w7_fpn_1x_coco.py
