### ISSUE TITLE
Guided Anchor performs worse compared to baseline.

### ISSUE THREAD

**Issue by Joker316701882** [open-mmlab/mmdetection#704]
I tried the Guided Anchor ResNet50 on custom dataset, but got 4 points worse than baseline resnet50, any ideas? All settings follow the default values in GA config file.

**Comment by nemonameless** [comment]
Do you try on coco first and reproduce the mAP？

**Comment by myownskyW7** [comment]
@Joker316701882 You may try on COCO first to check if everything is okay. And more information about your custom dataset is needed. Otherwise, I will have no idea about your problem.

**Comment by nemonameless** [comment]
@myownskyW7  Thanks for your excellent work!  
Could you share the results and configs about the Cascade GA-RPN? 
I have test on coco with  Cascade-r50-GA but the performance is only 40.4%,  just 0.5% gain compared with faster r50 GA-RPN

**Comment by lpd2csx** [comment]
My result of GA on retinanet with coco dataset is worse than that of baseline. I don't know if i have changed any important code, but i don't change the config for sure.

**Comment by gfjiangly** [comment]
Using GA in Mask R-CNN, there is no performance improvement compared to baseline on my data set.

**Comment by ZhouJiaHuan** [comment]
using GA in cascade R-CNN with default configure parameters on my dataset, but got 2 point worse than the baseline.

**Comment by ZwwWayne** [comment]
This issue is closed since there is no way to debug the problem. Please create a new issue using the `implementation questions` template and describe your issue precisely.
