### ISSUE TITLE
TypeError: YOLOX: init() got an unexpected keyword argument 'input_size'

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmdetection#7044]
I got following error while I was trying to use yolox_tiny.. What would be the issue?
> Traceback (most recent call last):
>   File "keypoint_extractor.py", line 351, in <module>
>     main()
>   File "keypoint_extractor.py", line 167, in main
>     det_config, det_checkpoint, device=device.lower())
>   File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/mmdet/apis/inference.py", line 40, in init_detector
>     model = build_detector(config.model, test_cfg=config.get('test_cfg'))
>   File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
>     cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> TypeError: YOLOX: __init__() got an unexpected keyword argument 'input_size'
> 

I am using following versions
```
> mmcv-full                 1.3.9                    
> mmdet                     2.16.0 
```
Is it a version issue or what?

**Comment by RangiLyu** [comment]
Did you use the new yolox config in the previous version of mmdet? Try to upgrade your mmdetection.

**Comment by Thevakumar-Luheerathan** [comment]
Is it issue with mmdet or mmcv ? error points to a file within ../mmcv/utils/registry.py.. So, I thought the error is with mmcv


> File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
> raise type(e)(f'{obj_cls.name}: {e}')
> TypeError: YOLOX: init() got an unexpected keyword argument 'input_size'


Can I expect any hidden issues when I upgrade? will it damage my environment(The environment is used for more critical tasks. I am using mmpose also)? How can I upgrade?

**Comment by dnth** [comment]
Updating mmdet solved this issue for me. Thank you!

**Comment by RangiLyu** [comment]
> Is it issue with mmdet or mmcv ? error points to a file within ../mmcv/utils/registry.py.. So, I thought the error is with mmcv
> 
> > File "/home/luhee/anaconda3/envs/fyp2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
> > raise type(e)(f'{obj_cls.name}: {e}')
> > TypeError: YOLOX: init() got an unexpected keyword argument 'input_size'
> 
> Can I expect any hidden issues when I upgrade? will it damage my environment(The environment is used for more critical tasks. I am using mmpose also)? How can I upgrade?

It's nothing about the mmcv. YOLOX was refactored in MMDet a few versions ago. Just update your mmdetection. Just pull the latest mmdet from the git and install it.

**Comment by Thevakumar-Luheerathan** [comment]
Thank you. I will check on that.
