### ISSUE TITLE
mim install mmdet

### ISSUE THREAD

**Issue by LLsmile** [open-mmlab/mmdetection#7045]
I install mmdet with suggested command **_mim install mmdet_**, but there are still compatibility issues as

AssertionError: MMCV==1.4.3 is used but incompatible. Please install mmcv>=1.2.4, <=1.4.0.

mmdet version in my computer is mmdet-2.20.0

**Comment by RangiLyu** [comment]
Can you post your `mmdet/__init__.py`?
