### ISSUE TITLE
mmcv installation

### ISSUE THREAD

**Issue by fiveriddle** [open-mmlab/mmdetection#7046]
my mmcv&mmcv version has already been upgraded to 1.3.17, which can be observed in the pip list, however, it still reports like:
AssertionError: MMCV==1.2.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.5.0.
and the mmcv.__version__ command also shows the result in 1.2.0
I don't know which part leads the error.

**Comment by RangiLyu** [comment]
run 
```
pip uninstall mmcv
pip uninstall mmcv-full
```
and then try to install mmcv-full again.
