### ISSUE TITLE
Dose dist_train.py support multi node training ?

### ISSUE THREAD

**Issue by jiejie1993** [open-mmlab/mmdetection#7047]
在k8s的集群管理系统中，可能会分配多个物理机上的GPU，如何在多机多卡的环境下训练？如何修改dist_train可以使之支持多机多卡训练？

**Comment by RangiLyu** [comment]
```
python -m torch.distributed.launch \
    --nnodes= ${NUM_NODES} \
    --node_rank=${NODE_RANK} \
    --master_addr ${MASTER_IP} \
    --nproc_per_node=${GPUS} \
    --master_port=29500 \
    train.py \
    ${py_args}
```

**Comment by jiejie1993** [comment]
我使用docker镜像在多机多卡环境下启动训练报错，环境如下：
`sys.platform: linux
Python: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) [GCC 7.3.0]
CUDA available: True
GPU 0,1: Tesla P4
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.0a0+17f8c32
PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.1 Product Build 20180928 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0a0
OpenCV: 3.4.1
MMCV: 1.3.17
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.18.1+`
报错如下：
`*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'log_model_dir/haiyangshengwu_Yolox_small_416/haiyangshengwu_Yolox_small_416.py', '--launcher=pytorch', '--work-dir=log_model_dir']' died with <Signals.SIGSEGV: 11>.`

**Comment by ZwwWayne** [comment]
For multi-node training with Docker, you may refer to the usage of K8s. Simply running two dockers in two machines respectively might not work.

**Comment by jiejie1993** [comment]
`CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="172.16.30.2" --master_port 8880 tools/train.py log_model_dir/haiyangshengwu_Yolox_small_416/haiyangshengwu_Yolox_small_416.py --launcher=pytorch --work-dir=log_model_dir --deterministic`
我使用上面的指令在两个物理机docker中运行起来了，在evaluation过程中出现了错误，如下：
```
Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 185, in main
    meta=meta)
  File "/Auto_CV/mmdet/apis/train.py", line 211, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/Auto_CV/mmdet/core/evaluation/eval_hooks.py", line 54, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/Auto_CV/mmdet/apis/test.py", line 113, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/Auto_CV/mmdet/apis/test.py", line 148, in collect_results_cpu
    part_list.append(mmcv.load(part_file))
  File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/io.py", line 60, in load
    with BytesIO(file_client.get(file)) as f:
  File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 992, in get
    return self.client.get(filepath)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 517, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Auto_CV/log_model_dir/.eval_hook/part_1.pkl'
```

**Comment by jiejie1993** [comment]
什么时候能够官方支持多机多卡训练哇

**Comment by jiejie1993** [comment]
在ctrl+C杀掉训练进程以后，重新启动时会报如下的错误，更改了端口号也不行
```
CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="172.16.30.2" --master_port 8880 tools/train.py log_model_dir/haiyangshengwu_Yolox_small_416/haiyangshengwu_Yolox_small_416.py --launcher=pytorch --work-dir=log_model_dir --deterministic
gpu2:1653:1653 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
gpu2:1653:1653 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en,eth,em,bond
gpu2:1653:1653 [0] NCCL INFO Bootstrap : Using eno2:172.16.30.2<0>
gpu2:1653:1653 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
gpu2:1653:1653 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
gpu2:1653:1653 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en,eth,em,bond
gpu2:1653:1653 [0] NCCL INFO NET/IB : No device found.
gpu2:1653:1653 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to en,eth,em,bond
gpu2:1653:1653 [0] NCCL INFO NCCL_SOCKET_IFNAME set to en,eth,em,bond
gpu2:1653:1653 [0] NCCL INFO NET/Socket : Using [0]eno2:172.16.30.2<0>
gpu2:1653:1653 [0] NCCL INFO Using network Socket
NCCL version 2.8.2+cuda11.1

gpu2:1653:1695 [0] include/socket.h:347 NCCL WARN Call to bind failed : Address already in use
gpu2:1653:1695 [0] NCCL INFO bootstrap.cc:339 -> 2
gpu2:1653:1695 [0] NCCL INFO init.cc:564 -> 2
gpu2:1653:1695 [0] NCCL INFO init.cc:871 -> 2
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'log_model_dir/haiyangshengwu_Yolox_small_416/haiyangshengwu_Yolox_small_416.py', '--launcher=pytorch', '--work-dir=log_model_dir', '--deterministic']' died with <Signals.SIGSEGV: 11>.
```

**Comment by xgyyao** [comment]
> `CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="172.16.30.2" --master_port 8880 tools/train.py log_model_dir/haiyangshengwu_Yolox_small_416/haiyangshengwu_Yolox_small_416.py --launcher=pytorch --work-dir=log_model_dir --deterministic` 我使用上面的指令在两个物理机docker中运行起来了，在evaluation过程中出现了错误，如下：
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 189, in <module>
>     main()
>   File "tools/train.py", line 185, in main
>     meta=meta)
>   File "/Auto_CV/mmdet/apis/train.py", line 211, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
>     self.call_hook('after_train_epoch')
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
>     self._do_evaluate(runner)
>   File "/Auto_CV/mmdet/core/evaluation/eval_hooks.py", line 54, in _do_evaluate
>     gpu_collect=self.gpu_collect)
>   File "/Auto_CV/mmdet/apis/test.py", line 113, in multi_gpu_test
>     results = collect_results_cpu(results, len(dataset), tmpdir)
>   File "/Auto_CV/mmdet/apis/test.py", line 148, in collect_results_cpu
>     part_list.append(mmcv.load(part_file))
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/io.py", line 60, in load
>     with BytesIO(file_client.get(file)) as f:
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 992, in get
>     return self.client.get(filepath)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 517, in get
>     with open(filepath, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/Auto_CV/log_model_dir/.eval_hook/part_1.pkl'
> ```
> 
> 我看了下缺失的这个文件在物理机2上，eval_hooks.py中的DistEvalHook方法是不是不支持多机多卡训练？如何修改可以支持多机多卡呢

兄弟，我也遇到了你这个问题，请问你怎么解决的呢？

**Comment by ZwwWayne** [comment]
The repo supports multi-machine distributed training since its release. We updated the script for distributed training without slurm https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh.
Doc: https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#train-with-multiple-machines

**Comment by WenkaiYe** [comment]
> > `CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="172.16.30.2" --master_port 8880 tools/train.py log_model_dir/haiyangshengwu_Yolox_small_416/haiyangshengwu_Yolox_small_416.py --launcher=pytorch --work-dir=log_model_dir --deterministic` 我使用上面的指令在两个物理机docker中运行起来了，在evaluation过程中出现了错误，如下：
> > ```
> > Traceback (most recent call last):
> >   File "tools/train.py", line 189, in <module>
> >     main()
> >   File "tools/train.py", line 185, in main
> >     meta=meta)
> >   File "/Auto_CV/mmdet/apis/train.py", line 211, in train_detector
> >     runner.run(data_loaders, cfg.workflow)
> >   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> >     epoch_runner(data_loaders[i], **kwargs)
> >   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
> >     self.call_hook('after_train_epoch')
> >   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> >     getattr(hook, fn_name)(self)
> >   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
> >     self._do_evaluate(runner)
> >   File "/Auto_CV/mmdet/core/evaluation/eval_hooks.py", line 54, in _do_evaluate
> >     gpu_collect=self.gpu_collect)
> >   File "/Auto_CV/mmdet/apis/test.py", line 113, in multi_gpu_test
> >     results = collect_results_cpu(results, len(dataset), tmpdir)
> >   File "/Auto_CV/mmdet/apis/test.py", line 148, in collect_results_cpu
> >     part_list.append(mmcv.load(part_file))
> >   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/io.py", line 60, in load
> >     with BytesIO(file_client.get(file)) as f:
> >   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 992, in get
> >     return self.client.get(filepath)
> >   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 517, in get
> >     with open(filepath, 'rb') as f:
> > FileNotFoundError: [Errno 2] No such file or directory: '/Auto_CV/log_model_dir/.eval_hook/part_1.pkl'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我看了下缺失的这个文件在物理机2上，eval_hooks.py中的DistEvalHook方法是不是不支持多机多卡训练？如何修改可以支持多机多卡呢
> 
> 兄弟，我也遇到了你这个问题，请问你怎么解决的呢？

any updates? Thx in advance.

**Comment by WenkaiYe** [comment]
> `CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="172.16.30.2" --master_port 8880 tools/train.py log_model_dir/haiyangshengwu_Yolox_small_416/haiyangshengwu_Yolox_small_416.py --launcher=pytorch --work-dir=log_model_dir --deterministic` 我使用上面的指令在两个物理机docker中运行起来了，在evaluation过程中出现了错误，如下：
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 189, in <module>
>     main()
>   File "tools/train.py", line 185, in main
>     meta=meta)
>   File "/Auto_CV/mmdet/apis/train.py", line 211, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
>     self.call_hook('after_train_epoch')
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
>     self._do_evaluate(runner)
>   File "/Auto_CV/mmdet/core/evaluation/eval_hooks.py", line 54, in _do_evaluate
>     gpu_collect=self.gpu_collect)
>   File "/Auto_CV/mmdet/apis/test.py", line 113, in multi_gpu_test
>     results = collect_results_cpu(results, len(dataset), tmpdir)
>   File "/Auto_CV/mmdet/apis/test.py", line 148, in collect_results_cpu
>     part_list.append(mmcv.load(part_file))
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/io.py", line 60, in load
>     with BytesIO(file_client.get(file)) as f:
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 992, in get
>     return self.client.get(filepath)
>   File "/opt/conda/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 517, in get
>     with open(filepath, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/Auto_CV/log_model_dir/.eval_hook/part_1.pkl'
> ```
> 
> 我看了下缺失的这个文件在物理机2上，eval_hooks.py中的DistEvalHook方法是不是不支持多机多卡训练？如何修改可以支持多机多卡呢

set evalution.gpu_collect=True in the dataset config, as recommended in [issue](https://github.com/open-mmlab/mmdetection/issues/3424#issuecomment-667236603). Set work_dir to a shared folder between nodes is another choice.
