### ISSUE TITLE
Result in json file

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#7049]
When I output the test result in json file, the result in results.segm.json will looks like it:

{"image_id": 202, "bbox": [723.2297973632812, 126.57115936279297, 82.4393310546875, 31.844032287597656], "score": 0.1710083931684494, "category_id": 4, "segmentation": {"size": [720, 1280], "counts": "fWT`02\\f03L4N1O2O0O1O1N2O1O1O100O00100O10000O1O10000000O10000000000O1000001N10000O2O000O100O2N101M3L300KgYO4Xf0LhYO4Zf0OWmk:"}}

So what is the mean of segmentation" part? How can I calculate the measure（Number of pixels occupied by the result） by this result?

**Comment by RangiLyu** [comment]
It is a RLE encoded mask. You can use cocoapi to decode it.

**Comment by ZwwWayne** [comment]
See example here https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/loading.py#L329

**Comment by wzr0108** [comment]
i met the same problem , have you sovled it?
