### ISSUE TITLE
How to cancel "Mosic“&"MixUp" at some epoch?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#7053]
Hi, dear authors!
Thank you for your amazing job!
Could you tell me how to cancel "Mosic“&"MixUp" at some epoch?
For example, I want to keep "Mosic"&"MixUp" in 1--100 epoch and cancel them in 101--200 epoch.
Thank you!

**Comment by RangiLyu** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/core/hook/yolox_mode_switch_hook.py#L23

**Comment by zhongqiu1245** [comment]
Thank you!
