### ISSUE TITLE
获取result

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#7055]
我正在探索如何获得mask_rcnn的result然后进行处理（例如只输出某个class的结果或者只输出面积最大的结果）
所以浏览的相关的代码。并且产生了一些问题首先是现在代码可以将result转换为json文件，主要采用的代码为mmdet/dataset/coco.py
对于函数_segm2json
if isinstance(seg, tuple):中的seg是从哪里来的呢?

还有就是mmdet/apis/text.py文档内single_gpu_test函数具体将检测结果标注到图像上是哪一句代码呢？（有点看不明白）

而且不论是转换为json文件还是图像结果，都要接收来自于同一个上一级的results。这个results是由哪一个函数计算得到的呢？

**Comment by chhluo** [comment]
1. seg result from here https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/roi_heads/standard_roi_head.py#L265
simple_test_mask defined in https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/roi_heads/test_mixins.py#L224
2. plot annotations on image using show_result function defined here https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/detectors/base.py#L271
3.results returned are from here https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/roi_heads/standard_roi_head.py#L267

**Comment by kankanzheli** [comment]
除此之外，show_score_thr是如何工作的呢？

**Comment by chhluo** [comment]
filter out the results which score is lower than show_score_thr, then show the rest.

**Comment by kankanzheli** [comment]
我的意思是show_score_thr是通过哪些代码工作的呢？

**Comment by chhluo** [comment]
place where show_score_thr pass to. It's not hard, try to find it by yourself.

**Comment by kankanzheli** [comment]
是这样的。我在mmdetection/mmdet/apis/test.py的single_gpu_test函数内找到有提及show_score_thr的部分。最终展示在 52-57行
             model.module.show_result(
                    img_show,
                    result[i],
                    show=show,
                    out_file=out_file,
                    score_thr=show_score_thr)

但这部分看起来不像对数据结果筛选的部分。这也就导致了我向你询问这个问题

**Comment by kankanzheli** [comment]
看起来像是通过这部分代码进行筛选：
model.module.show_result（）
但与此同时，在tools/test.py中，
mmcv.parallel import MMDataParallel
model = MMDataParallel(model, device_ids=cfg.gpu_ids)，所以通过分数筛选的代码存在于mmcv中吗

**Comment by chhluo** [comment]
Please look further in MMDataParallel.You will understand soon.

**Comment by kankanzheli** [comment]
查阅MMDataParallel。文件位于mmcv/mmcv/parallel/data_paralled.py
文件中找不到和score_thr相关的部分
上文中展示的model.module.show_result（）函数的具体解释位置也找不到

**Comment by kankanzheli** [comment]
我找到了score_thr工作的部分。确实不在MMDataParallel。
它的位置在/home/zhaowentao/Visual/mmdetection/mmdet/core/visualization/image.py的imshow_det_bboxes函数

**Comment by kankanzheli** [comment]
还有就是mask iou的计算的代码在哪里呢？

**Comment by chhluo** [comment]
The evalutation is done by package pycocotools.
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L163

**Comment by kankanzheli** [comment]
在mmdetection中是通过--eval segm进行mask iou的计算的。如你所说是使用cocoapi中的computeIoU函数计算mask iou.那么在mmdetection中使用这个函数，把数据导入然后使用这个函数计算的部分在哪里呢？

**Comment by chhluo** [comment]
This line 
https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/datasets/coco.py#L513
