### ISSUE TITLE
about fpg

### ISSUE THREAD

**Issue by ningqing123** [open-mmlab/mmdetection#7060]
```
  File "/lib/python3.7/site-packages/mmdet/models/necks/fpg.py", line 330, in fuse
    out = out + item
RuntimeError: The size of tensor a (23) must match the size of tensor b (24) at non-singleton dimension 2

```
When I replace FPN with FPG, I train fasterrcnn and report the error as above. What is the possible reason？

**Comment by jbwang1997** [comment]
Please follow the issue template to provide more info such as the config and the full error report.
