### ISSUE TITLE
Is it possible to get mask‘s (x,y) coordinates? 是否能够获取识别目标的mask坐标呢？

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmdetection#7062]
I've trained a model and i wanna get the coordinates of the mask,how should i do?thx!
请教一下如果我想获得掩膜的坐标 这是否可行呢？应当如何做呢？感谢大神！

**Comment by chhluo** [comment]
I don't get it, please describe in more detail and specificity.

**Comment by ShaneCan** [comment]
hello chhluo,I want to get the coordinates of each point of the contour on the mask，is that possible?thx again!!!

**Comment by chhluo** [comment]
There is a function in opencv called findContours.

**Comment by ShaneCan** [comment]
thx chhluo,one more question,which .py should i modify to add cv.findcontours funtion? thx a lot ~~~

**Comment by chhluo** [comment]
write a extra py file, then handle the mask results which saved in a json file or pkl file in test process.

**Comment by ShaneCan** [comment]
thats true but i wanna show the  coordinates on the test pic, is that possible?

**Comment by chhluo** [comment]
The number of coordinates of a contour in mask is big, maybe unreasonable be show on test pic. Showing the  coordinates of bbox is more reasonable. The code here 
 https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/core/visualization/image.py#L29 may inspire you。

**Comment by ShaneCan** [comment]
really appreciate chhluo~~~

**Comment by wwcc1107** [comment]
Did you solve this problem please?
