### ISSUE TITLE
Any way to save / load models in native pytorch?

### ISSUE THREAD

**Issue by pfuerste** [open-mmlab/mmdetection#7070]
I am looking for a way to call torch.save(model, path) with a trained model and afterwards be able to just call torch.load(model) without knowing the model class. 
I can save the state_dict this way, but without the model class, I can't make it into a PyTorch-model via load_state_dict().
All that gets saved is a dict with the keys "meta", "state_dict" and "optimizer". Is there a way to load this as a model in a new file without any mmdet-dependencies?

**Comment by ZwwWayne** [comment]
You can use https://github.com/open-mmlab/mmdetection/blob/master/tools/model_converters/publish_model.py

**Comment by pfuerste** [comment]
I did that, but when calling torch.load() on the saved file, it returns a Dict which does not have any relevant function, e.g.:
`  File "/home/fuerste/thesis_root/utils/eval/inference.py", line 11, in load_model
    model.eval()
AttributeError: 'dict' object has no attribute 'eval'`
