### ISSUE TITLE
torch.load(path) returns no model

### ISSUE THREAD

**Issue by pfuerste** [open-mmlab/mmdetection#7071]
I am trying to load my serialized model via torch.load() after serializing it with https://github.com/open-mmlab/mmdetection/blob/master/tools/model_converters/publish_model.py.
See https://github.com/open-mmlab/mmdetection/issues/7070.

But when I use torch.load() on the file generated by this I only get a dictionary. How can I get a model from this with which I can call model.eval() without having the model class?

**Comment by ZwwWayne** [comment]
The dictionary should contain a key named 'state_dict'. Then you should build a model and use model.load_state_dict(). See example here https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/inference.py#L42

**Comment by pfuerste** [comment]
Okay, I should have specified: I am looking for a way to save and load all information about the model.
Calling build_detector() needs my initial config, which I would like to omit.

**Comment by ZwwWayne** [comment]
> Okay, I should have specified: I am looking for a way to save and load all information about the model. Calling build_detector() needs my initial config, which I would like to omit.

We have not tried it yet. You may try pickle.dump().

**Comment by pfuerste** [comment]
That works fine for loading a model, but I can't seem to find a way to just use it without image_metas. Is there any way to just use the model without more image information than the actual image file?

**Comment by ZwwWayne** [comment]
You may construct a fake img_meta. If you do not want that, the solution is to allow default values when img_meta is None. You can have a try if it is necessary for you.

**Comment by Muxindawang** [comment]
> I am trying to load my serialized model via torch.load() after serializing it with https://github.com/open-mmlab/mmdetection/blob/master/tools/model_converters/publish_model.py.我尝试通过 torch.load() 加载我使用 https://github.com/open-mmlab/mmdetection/blob/master/tools/model_converters/publish_model.py 序列化的模型。 See [#7070](https://github.com/open-mmlab/mmdetection/issues/7070).  参见 [#7070](https://github.com/open-mmlab/mmdetection/issues/7070) 。
> 
> But when I use torch.load() on the file generated by this I only get a dictionary. How can I get a model from this with which I can call model.eval() without having the model class?但是，当我使用 torch.load() 加载这个工具生成的文件时，我只得到一个字典。如何从这个字典中获取一个模型，以便我可以调用 model.eval() 而不需要模型类？

Did you manage to solve it in the end? I encountered the same problem. I cut some channels from the original model, and at this point, using the original config directly causes issues. Did you end up creating a new config yourself, or did you use some other solution, like loading with torch.load? I would really appreciate your guidance.
