### ISSUE TITLE
dataset Problem. Is my dataset wrong？

### ISSUE THREAD

**Issue by mitsuha97** [open-mmlab/mmdetection#7072]
run:python tools/misc/browse_dataset.py configs/a_thz_mini/yolox_s_8x8_300e_thzmini.py 
error :    return self.dataset[idx % self._ori_len]
ZeroDivisionError: integer division or modulo by zero

run:python tools/train.py configs/a_thz_mini/yolox_s_8x8_300e_thzmini.py
error:    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

配置文件中的dataset改为官方VOC2007的数据集就可以正常加载，改为自己的数据集就是不行。
数据集已经制作成VOC2007格式的了，可是就是加载不了，真不知道我的数据集问题到底错哪了，请帮忙下载看一下这个数据集的问题到底在哪里？

只有一个类别

https://drive.google.com/file/d/1aTjYT1mMuijC6QErAxWsAMk0YGGjfyn9/view?usp=sharing
please help me QAQ

**Comment by jbwang1997** [comment]
I don't get it. Do you mean using `VOCDataset` to load your data or creating a `new dataset class`?

**Comment by mitsuha97** [comment]
> 

Office VOC2007 dataset can be load.But my custom VOC2007 data can’t be load,I don’t know why… there’s a 50pics demo.Can you help me?

**Comment by mitsuha97** [comment]
> I don't get it. Do you mean using `VOCDataset` to load your data or creating a `new dataset class`?

I upload demo on google drive

**Comment by jbwang1997** [comment]
Have you changed the `CLASSES` in `VOCDataset`.

**Comment by mitsuha97** [comment]
> Have you changed the `CLASSES` in `VOCDataset`.

Yes I did this.You can download my dataset demo to try. Thank you for helping me.

**Comment by ZwwWayne** [comment]
Hi @mitsuha97 ,
This is not a recommended operation. You'd better to create a new dataset class inheriting from VOCDataset, then modify its CLASSES. After that, you should modify the num_classes in your head. The instruction is here https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html.

For your bug, could you post the full error log? We do not know this error comes from which file according to your description, so our hands are tightened and cannot help.

**Comment by lijinrun** [comment]
你好，我刚刚也遇到这个问题了，发现是annotation标注数据里的标签名称和我在代码修改的CLASSES标签名不一致。不知道你的是不是这种情况，可以参考一下我的。

**Comment by jiachen0212** [comment]
> 你好，我刚刚也遇到这个问题了，发现是annotation标注数据里的标签名称和我在代码修改的CLASSES标签名不一致。不知道你的是不是这种情况，可以参考一下我的。

解决了我的问题, 在coco_detection.py中加上自己任务的classes即可！ thx！！！
