### ISSUE TITLE
multi-GPU/processing for inference

### ISSUE THREAD

**Issue by vincent507cpu** [open-mmlab/mmdetection#7073]
My task requires to generate about 5500 patches (1333 x 800) from a large image and infer them in a short period of time (< 5 min). I suppose `inference_detector` using single process with a single GPU and it takes 572 s for 5500 patches. I have 4 GPUs, so I was wondering if there is a way to use this function efficiently. Thanks in advance.

**Comment by cmaurice-qc** [comment]
Have you found a solution?
