### ISSUE TITLE
pos_assigned_gt_inds_list, gt_masks_list, cfg_list) TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hoyeoung** [open-mmlab/mmdetection#7075]
When learning using my dataset, train.py can recognize bbox annotation(ex. training through faster r-cnn) but  when learning using segmentation annotation(ex. mask rcnn, casacade mask rcnn), the following error appears.
I checked that the segmentation annotation format in my dataset is the same as the segmentation annotation required in the coco dataset. How do I resolve this error?

ERROR:
pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable

**Comment by hhaAndroid** [comment]
Too little information was provided, please use the issue template.

**Comment by flashwwf** [comment]
同样的问题，题主解决了吗？
