### ISSUE TITLE
Registry inner workings

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection#7076]
Hi. I do not understand how the registry works underneath. When are the decorated modules instantiated? Why isn't there a problem when the Registry object (let's say DETECTORS) is called to build a model that was not yet "seen", throwing a message like "KeyError: '{} is not in the {} registry'.

**Comment by jbwang1997** [comment]
Here are the [introduction](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/registry.md) and the [code](https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/registry.py) of the registry. Hope those docs can inspire you.

**Comment by AfonsoSalgadoSousa** [comment]
Thank you for the help. I understand it now. For future reference, all modules are instantiated on a cascade of __init__.py, hence why this architecture works.
