### ISSUE TITLE
swin-transformer

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#7077]
您好，请问这个仓库有木有使用swin-transformer作为backbone搭建的FPN网络呢？

**Comment by jbwang1997** [comment]
You can refer to [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/swin) for models with Swin as the backbone.

**Comment by zcswdt** [comment]
> You can refer to [here](https://github.com/open-mmlab/mmdetection/tree/master/configs/swin) for models with Swin as the backbone.

Hi, what does  out_indices=(0, 1, 2, 3) mean?

**Comment by jbwang1997** [comment]
This argument indicates outputting which stages.

**Comment by zcswdt** [comment]
> This argument indicates outputting which stages.

Thank you for your reply. I have another question to ask. I think the default size of the input image is 224. Can I use a 640 image as input for training?
![image](https://user-images.githubusercontent.com/43515926/151330879-dd3b86f2-4875-498e-90cc-0ee7634ef4b5.png)

**Comment by jbwang1997** [comment]
Yes. The `pretain_img_size` is for classification pretrain. You can change the `img_scales` in training pipline to change the training image size.
