### ISSUE TITLE
analyze_results.py 

### ISSUE THREAD

**Issue by crepuscularlight** [open-mmlab/mmdetection#7079]
AttributeError: 'ConcatDataset' object has no attribute 'prepare_train_img'

**Reproduction**

_base_='../swin/mask_rcnn_swin-t-p4-w7_fpn_1x_coco.py'
dataset_type='CocoDataset'

prefix='./data/taco/'

classes=('Can', 'Carton', 'Cup', 'GlassBottle',
         'Other', 'Paper','PlasticBottle', 'PlasticContainer', 'Wrapper')

test_prefix='data/test105'

model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=9),
        mask_head=dict(num_classes=9)))
data=dict(
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file=[
            'data/week17/fixed_annotations.json'
        ],
        img_prefix=prefix
    ),

    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=[
            'data/week17/fixed_annotations.json'
        ],
        img_prefix=prefix
    ),

    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=[
                    "data/test105/fixed_annotations.json"
                  ],
        img_prefix=test_prefix
    )
)

**Environment**

TorchVision: 0.2.1
OpenCV: 4.5.3
MMCV: 1.3.15
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.4
MMDetection: 2.17.0+78e3ec8

**Comment by RangiLyu** [comment]
ConcatDataset currently does not have `prepare_train_img` function.

It seems that you only have one annotation file. So just change to
```
ann_file='data/week17/fixed_annotations.json',
```
to avoid using ConcatDataset.

**Comment by crepuscularlight** [comment]
Thanks a lot
