### ISSUE TITLE
CascadeRCNN model convertion to MXnet

### ISSUE THREAD

**Issue by vedrusss** [open-mmlab/mmdetection#708]
Hi all,

I'm trying to convert **cascade_rcnn_dconv_c3-c5_r50_fpn_1x** model from pytorch to mxnet.
I tried onnx and mmdnn convertors (pytorch->onnx/mmdnn->mxnet); pytorch2caffe (hoping to convert then from caffe to mxnet) as well.

But in all cases I obtain the same error at early beginning:
`TypeError: forward() missing 1 required positional argument: 'img_meta'`

This is because of the model is an instance of class `CascadeRCNN` which I guess re-implements `forward()` method of a base class used within the convertors.

Is there any way to omit the problem while convertion? Converted models? Convertor suitable for the CascadeRCNN model?

My env: ubuntu 16.04, cuda 9.0, pytorch 1.1, python 3.6.

Thanks

**Comment by hellock** [comment]
I guess that those convert tools assume that `forward()` accepts only one argument but detection models takes more inputs. You may need to hack into them for a fix.

**Comment by SnowRipple** [comment]
Hi @vedrusss , I have the same problem. It seems that neither of these conversion tools support dict/multiple input. Did you manage to work around it?
