### ISSUE TITLE
I am confuse about the config file of mstrain_3x_coco.py, the max epoch is 12, not 36, while others use epoch of 36

### ISSUE THREAD

**Issue by 1104662797** [open-mmlab/mmdetection#7082]
Thanks for your answer for this question.  I am trying to reproduction the result of PVT on RetinaNet, the author not provide the config file for mstrain_3x, so i have to write it by myself. I find your[mstrain_3x](https://github.com/open-mmlab/mmdetection/blob/master/configs/common/mstrain_3x_coco.py) file use epoch 0f 12 not 36, but others use 36, this made me so confuse. Thanks for your help.

**Comment by jbwang1997** [comment]
This config uses `RepeatDataset` and duplicates the original coco dataset 3 times. Thus, it only uses 12 epochs.

**Comment by 1104662797** [comment]
Thanks very much, I just notice it.
