### ISSUE TITLE
How to display different mAP for different IOU values?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#7088]
When I run the tools/test.py I can see the mAP table for a certain IOU value (in my case IOU-0.5). Is there a way to display different table at once for different(multiple) IOU values lets say:0.5,0.6,0.7,0.8 etc. Where should I change the IOU value in particular to get the result for a given IOU value? ( I am using VOC dataset format)

**Comment by RangiLyu** [comment]
You can change the value of iou_thr to a list.
https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/datasets/voc.py#L46
