### ISSUE TITLE
About custom_imports

### ISSUE THREAD

**Issue by BuxianChen** [open-mmlab/mmdetection#7089]
I noticed the custom_imports is removed in tools/train.py in the latest version, the same things is also happened to MMOCR:
https://github.com/open-mmlab/mmocr/pull/603
But here is the documents about custom_imports:
https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module

Is custom_imports not recommend later?

**Comment by RangiLyu** [comment]
No, custom_imports is still supported. This feature is handled by MMCV now.
