### ISSUE TITLE
Question about the inference for HTC

### ISSUE THREAD

**Issue by JoyHuYY1412** [open-mmlab/mmdetection#710]
since you set `keep_all_stages` as false, the mask_feat here:
https://github.com/open-mmlab/mmdetection/blob/6050186056dcf8f50cc8115a22bfeb1fa5b56063/mmdet/models/detectors/htc.py#L356
is the mask feature of the bbox after 3 stages, right?

Then the mask head here
https://github.com/open-mmlab/mmdetection/blob/6050186056dcf8f50cc8115a22bfeb1fa5b56063/mmdet/models/detectors/htc.py#L366
also has three stages, but does the bbox in these stages stay not changed?

**Comment by hellock** [comment]
For the mask feature connection across different stages, we use the same bbox.
