### ISSUE TITLE
Some question about tood

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#7113]
How to set more than 1 anchors in Tood detector? And when I use FP16 for Tood, the mAP is always 0, does it support FP16? THanks

**Comment by RangiLyu** [comment]
> How to set more than 1 anchors in Tood detector? 

Try to modify the AnchorGenerator in the config. You can refer to configs of other anchor base models.

> And when I use FP16 for Tood, the mAP is always 0, does it support FP16? THanks

TOOD does not support fp16 yet.

**Comment by dongbx3379** [comment]
What should I do if I need to use fp16 on TOOD?
