### ISSUE TITLE
Error while running MMDet tutorial.ipynb

### ISSUE THREAD

**Issue by sparshgarg23** [open-mmlab/mmdetection#7117]
I was able to install mmdet and mmcv on colab
the respective versions are as follows
Torch 1.10.0+cu111 
MMDet version 2.20.0
Cuda compiler and GCC compiler version
11.1
GCC 7.3
This output was printed after the following import was executed
```
from mmcv.ops import get_compiling_cuda_version, get_compiler_version
```
But when I run the next cell in MMDet tutorial.ipynb I get the following error
```
--2022-02-04 10:48:23--  https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth
Resolving open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)... 52.219.146.15
Connecting to open-mmlab.s3.ap-northeast-2.amazonaws.com (open-mmlab.s3.ap-northeast-2.amazonaws.com)|52.219.146.15|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-02-04 10:48:24 ERROR 403: Forbidden
```
I went to the website posted in the link and ended up recieving the following message
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>WCMZK4QT3VT6V8MJ</RequestId>
<HostId>UgU/LjWh9rJiXNnczSxX45kEqjZgFjynSJf5hjFnzf5ZL+6tT7gmv96YZd963TqigjH8uUtZoqc=</HostId>
</Error>
```

Any suggestions on what can be done to resolve this issue?

**Comment by shinya7y** [comment]
Please use the latest `MMDet_Tutorial.ipynb`.
https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb

The URL has been updated.
https://download.openmmlab.com/mmdetection/v2.0/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth

**Comment by sparshgarg23** [comment]
Thanks I am currently using the following command to install mmcv
```
pip install mmcv-ful -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
```
Is there any signifcant difference between this version of mmcv and the one being used in the .ipynb  file.(Apart from the difference in torch and cuda versions)

**Comment by shinya7y** [comment]
> it seems that the configuration file for mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco does not exist in the configuration directory.

What is the actual MMDet version?

**Comment by sparshgarg23** [comment]
The MMDet Version is 2.9.0 ,but the one in your link is pointing to 2.20

**Comment by shinya7y** [comment]
I referred to the first comment.
> MMDet version 2.20.0

Please use the latest mmdet.

**Comment by ZwwWayne** [comment]
The config still exists, see https://github.com/open-mmlab/mmdetection/blob/v2.9.0/configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco.py

**Comment by sparshgarg23** [comment]
Thanks
