### ISSUE TITLE
bboxes in middle format dataset ?

### ISSUE THREAD

**Issue by longnq969** [open-mmlab/mmdetection#7121]
Hi, I 'm following this guide 
https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html#reorganize-new-data-format-to-middle-format

Pls let me know what is format of bboxes ? 
Is it "top left bottom right" or "top left width height" or something else ?
Thanks,

**Comment by chhluo** [comment]
The expected format is described here https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/datasets/custom.py#L32
