### ISSUE TITLE
onnx export for YOLOX?

### ISSUE THREAD

**Issue by jinfagang** [open-mmlab/mmdetection#7132]
Since YOLOX doesn't have any normalize_cfg needed, but pytorch2onnx.py still checks norm, caused yolox can not export to onnx

**Comment by hhaAndroid** [comment]
@jinfagang Please use mmdeploy directly. It now supports yolox export.

**Comment by RangiLyu** [comment]
Welcome to try mmdeploy! https://github.com/open-mmlab/mmdeploy

**Comment by ZwwWayne** [comment]
Yes it can.
