### ISSUE TITLE
swin FPN

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#7134]
Hello, I want to build a swin-fpn network, why should I use out_indices=(1, 2, 3) instead of out_indices=(0, 1, 2, 3)

![image](https://user-images.githubusercontent.com/43515926/153329578-1997f2d3-d3c4-4104-a112-0e87363c5996.png)

**Comment by RangiLyu** [comment]
As the Notice above said, you need to make sure the `start_level=0` in FPN. And it is determined by how many feature levels you use.
