### ISSUE TITLE
model.init_weights() show each layer's information, cannot erase?

### ISSUE THREAD

**Issue by yoyoyo-yo** [open-mmlab/mmdetection#7136]
Thank you for nice library.

I use model.init_weights() and got each layer's information like below. 
This looks long for me , so how can I use init_weights() without these display?

```
backbone.conv1.weight - torch.Size([64, 3, 7, 7]): 
PretrainedInit: load from open-mmlab://resnext101_64x4d 
 
2022-02-10 16:32:48,488 - mmcv - INFO - 
backbone.bn1.weight - torch.Size([64]): 
PretrainedInit: load from open-mmlab://resnext101_64x4d 
 
2022-02-10 16:32:48,489 - mmcv - INFO - 
backbone.bn1.bias - torch.Size([64]): 
PretrainedInit: load from open-mmlab://resnext101_64x4d 
```

**Comment by BIGWangYuDong** [comment]
I did not get your point, did you want to close these logs? The codes are in [MMCV](https://github.com/open-mmlab/mmcv/blob/dd82ab14972a17cdf4570bee20ad15c10167bd6f/mmcv/runner/base_module.py#L136-L163)
https://github.com/open-mmlab/mmcv/blob/dd82ab14972a17cdf4570bee20ad15c10167bd6f/mmcv/runner/base_module.py#L136-L163

**Comment by BIGWangYuDong** [comment]
the `BaseModule` is in MMCV, which has `init_weights`, and seems that we cannot close the logs right now. If you want to close the log, you need change the code in MMCV

**Comment by yoyoyo-yo** [comment]
Thank you. I will close this thread.
