### ISSUE TITLE
Add tracking URI to MlflowLoggerHook

### ISSUE THREAD

**Issue by jraquelcs** [open-mmlab/mmdetection#7138]
**Describe the feature**
If you are using MLFlow to log runs remotely, it would be nice to set the tracking server’s URI by calling mlflow.set_tracking_uri() in the MlflowLoggerHook method _before_run()_. This way, it would be needed to pass the tracking_uri as an argument to the init function.

**Motivation**
It is convenient when someone wants to log runs remotely, especially when working on a shared instance of MLFlow.

**Related resources**
https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tracking_uri

**Additional context**
I will not be able to implement the feature nor create a PR, please be so kind and add it yourself.

**Comment by hhaAndroid** [comment]
@jraquelcs Great. you can go to `mmcv` to create a pr.
