### ISSUE TITLE
How to save the inference result of the test file

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmdetection#7139]

**Comment by chhluo** [comment]
`--work-dir`
https://github.com/open-mmlab/mmdetection/blob/98949809b7179fab9391663ee5a4ab5978425f90/tools/test.py#L28 ，
`--out`https://github.com/open-mmlab/mmdetection/blob/98949809b7179fab9391663ee5a4ab5978425f90/tools/test.py#L31, 
`--show-dir` https://github.com/open-mmlab/mmdetection/blob/98949809b7179fab9391663ee5a4ab5978425f90/tools/test.py#L62 are related with inference result saving. Please read the descriptions.
