### ISSUE TITLE
Test time augmentation: DETR

### ISSUE THREAD

**Issue by JosianeUwineza** [open-mmlab/mmdetection#7142]
While I was applying the test time augmentation on DETR, I get this:   File "/media/josi/5CEAB0FEEAB0D58C/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 69, in aug_test_bboxes
    f'{self.__class__.__name__}' \
AssertionError: DETRHead does not support test-time augmentation
I there a way I can use to solve this issue? Thanks

**Comment by hhaAndroid** [comment]
@JosianeUwineza DETR does not support TTA now.

**Comment by wwcc1107** [comment]
I also have this problem:AssertionError: DeformableDETRHead does not support test-time augmentation
