### ISSUE TITLE
Frozen Stages Explanation

### ISSUE THREAD

**Issue by TolgaOzdmir** [open-mmlab/mmdetection#7144]
Can anyone explain me how the parameter, frozen stages works? 

I want to change hyperparameters of faster r-cnn with resnext101 and I know this parameter freeze layers of backbone. However, what is the meaning of the integer value? For example, if I assing this parameter to 2 or 3, what will happen? which layer or layers will be frozen? 

Thank you for your help

**Comment by chhluo** [comment]
Please read this https://github.com/open-mmlab/mmdetection/blob/98949809b7179fab9391663ee5a4ab5978425f90/mmdet/models/backbones/resnet.py#L613
If `freeze_stages = 0`, it will freeze the stem in resnet, if `freeze_stages = n, (n >= 1)`, it will freeze the stem and first n stages in resnet.
