### ISSUE TITLE
Why gt_bboxes_ignore is not loaded by default  in Faster RCNN?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#7146]
I found that in old version of mmdetection, the with_crowd=True by default (https://github.com/open-mmlab/mmdetection/issues/190#issuecomment-447833090):
```python
data = dict(
    imgs_per_gpu=1,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        # TODO: train时使用了multi-scale
        img_scale=[(1333, 600),(1333, 1000)],
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=False,
        # TODO: with_crowd=True，加入了coco中的iscrowd标注，暂时不加
        with_crowd=True,
        with_label=True),
```
It means the iscrowd annotations will be loaded, which is the same as gt_bboxes_ignore.  But in the latest version of mmdetection, gt_bboxes_ignore is not loaded by default. Why?

**Comment by chhluo** [comment]
We found it brings marginal gains during implementation and thus do not do that
