### ISSUE TITLE
how to use iou loss on RetinaNet?

### ISSUE THREAD

**Issue by wei-yuma** [open-mmlab/mmdetection#715]

**Comment by wei-yuma** [comment]
I have done.
I reimplement a Iou loss function in my own method, it seems working good.

**Comment by sherlockedlee** [comment]
Can you share your method?Thank u very much.

**Comment by zytx121** [comment]
Can you share your method?Thank u very much.

**Comment by wei-yuma** [comment]
@zytx121 @sherlockedlee 
hi, I just compute iou for every predicted positive bbox and then compute iou loss like this: L=-log(iou)
