### ISSUE TITLE
Is mmdet 2.21.0 compatible with mmcv-full 1.4.5 

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [open-mmlab/mmdetection#7152]
I built mmcv-full from the source. The mmcv version is 1.4.5. Then I used mim to install mmdet. I got following warning.
mmcv-full==1.4.5 has been installed, but want to install mmcv-full==1.4.4, do you want to uninstall mmcv-full==1.4.5 and install mmcv-full==1.4.4?  [y/N]: 

Are both of these packages compatible with each other??

**Comment by Czm369** [comment]
These packages are compatible with each other. Because you built mmcv-full from the source and used mim to install mmdet, some version checks failed.

**Comment by Thevakumar-Luheerathan** [comment]
ok Thank you.
