### ISSUE TITLE
During verifing the trained model, I got TypeError

### ISSUE THREAD

**Issue by BaeSukkyoung** [open-mmlab/mmdetection#7153]
I use same code given by mmdetection like under.

config = 'cascade_mask_rcnn_x101_64x4d_fpn_1x_for_crack_road_crack_210517.py'
checkpoint = 'cascade_mask_rcnn_x101_64x4d_fpn_1x_for_crack_road_crack_210517/epoch_30.pth'

device = 'cuda:0'
model = init_detector(config, checkpoint, device=device)

And I run the code, I get the error like underline.

TypeError: __init__() got an unexpected keyword argument 'num_stages'

What's the problem ?

**Comment by hhaAndroid** [comment]
@BaeSukkyoung Incorrect configuration file.
