### ISSUE TITLE
RuntimeError: binary_op(): expected both inputs to be on same device, but input a is on cuda:0 and input b is on cuda:1

### ISSUE THREAD

**Issue by chchenhui** [open-mmlab/mmdetection#716]
I want to do a single-GPU test and want to use Cuda:1 (Cuda:0 is our of memory), so I change the parameter of device. My codes are as shown in this screenshot.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/13835142/58370250-f52f7380-7f36-11e9-9f65-eb65515a16f1.png">
But the result tells I still have some functions running on Cuda:0. Don't know how to solve it.
<img width="946" alt="image" src="https://user-images.githubusercontent.com/13835142/58370270-290a9900-7f37-11e9-8138-d1020dbab806.png">

**Comment by thangvubk** [comment]
Rather you can specify visible devices by ``CUDA_VISIBLE_DEVICES=1 python test.py ....``

**Comment by chchenhui** [comment]
> Rather you can specify visible devices by `CUDA_VISIBLE_DEVICES=1 python test.py ....`

thanks, I'll try.
