### ISSUE TITLE
请问这里为啥training和非training返回值不同？

### ISSUE THREAD

**Issue by loveisp** [open-mmlab/mmdetection#7167]
https://github.com/open-mmlab/mmdetection/blob/98949809b7179fab9391663ee5a4ab5978425f90/mmdet/models/dense_heads/vfnet_head.py#L307

这样写的话，在base_dense_head.py里会出问题：
https://github.com/open-mmlab/mmdetection/blob/98949809b7179fab9391663ee5a4ab5978425f90/mmdet/models/dense_heads/base_dense_head.py#L330-L335

self.loss调用参数时个数就不一致了，会导致出错。

这里对该问题有一些讨论：https://github.com/airctic/icevision/issues/1006

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/pull/7173#issuecomment-1042517156
