### ISSUE TITLE
请问混淆矩阵里 比例之和不为1的原因是什么？

### ISSUE THREAD

**Issue by MrWcy** [open-mmlab/mmdetection#7169]
![UQ)HY%9NN ($LW`C{WI1M44](https://user-images.githubusercontent.com/30768980/154066576-13390068-752c-4d0a-8d44-803339a7ea48.png)

如图第一行，比例之和为98%

**Comment by RangiLyu** [comment]
https://github.com/open-mmlab/mmdetection/blob/a64303186aa79811a050942f1bdab430a6a7f7af/tools/analysis_tools/confusion_matrix.py#L210

because the float is converted to int here
