### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found. [Windows10, python3.7, cuda10.2, mmdet2.21,mmcv-fulll1.4.5]

### ISSUE THREAD

**Issue by jankrans** [open-mmlab/mmdetection#7170]
Hi, 

I've been trying to get mmdetection to work on windows10 in a miniconda3 env. when trying the following I get the next error:

>`(test2) C:\Users\jkranzen\mmdetection>python`
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
 `from mmdet.apis import init_detector, inference_detector`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jkranzen\mmdetection\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\Users\jkranzen\mmdetection\mmdet\apis\inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "C:\Users\jkranzen\Miniconda3\envs\test2\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\jkranzen\Miniconda3\envs\test2\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "C:\Users\jkranzen\Miniconda3\envs\test2\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\jkranzen\Miniconda3\envs\test2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.`

**Reproduction**
conda create -n mmlab python=3.7
conda activate mmlab
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.10/index.html
pip install openmim
mim install mmdet
pip install opencv-python 

Thanks in regards, please ask if additional information is needed.

**Comment by jbwang1997** [comment]
It seems an error of mmcv referring to https://github.com/open-mmlab/mmcv/issues/1619.
You can try to change the version of mmcv to 1.4.0 and see if the error is still existing.
It would be appreciated if you could also report this issue in mmcv.

**Comment by jankrans** [comment]
> It seems an error of mmcv referring to [open-mmlab/mmcv#1619](https://github.com/open-mmlab/mmcv/issues/1619). You can try to change the version of mmcv to 1.4.0 and see if the error is still existing. It would be appreciated if you could also report this issue in mmcv.

Thanks for the quick respons, @jbwang1997.
I tried installing 1.4.0 am now getting next result: (I also tried using just mmcv instead of mmcv-full)

> (test2) C:\Users\jkranzen>python
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information. 
`from mmdet.apis import init_detector, inference_detector` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jkranzen\Miniconda3\envs\test2\lib\site-packages\mmdet\__init__.py", line 26, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.1.5 is used but incompatible. Please install mmcv>=1.3.17, <=1.5.0.

**Comment by jankrans** [comment]
Solved above by reinstalling mmdet. But now I'm getting the previous error....

**Comment by jbwang1997** [comment]
Kindly ping @zhouzaida to have a look.

**Comment by ZwwWayne** [comment]
You can try to install the newest MMCV. If you still meet a but, please create an issue in https://github.com/open-mmlab/mmcv
