### ISSUE TITLE
Inference with a customized model having structural changes.

### ISSUE THREAD

**Issue by SourabhRanade** [open-mmlab/mmdetection#7172]
Hello, I am using a MaksRCNN model with the model. Thereafter I make a decomposition to the linear layers of the backbone using low-rank transformations. Thus I would now have some structural changes to the model and I save the model using `torch.save(model.state_dict(),path_to_save)`. I have not made any changes to the config file as yet.  I now want to load this saved model to do inference. So my question is first, what do I need to do to get the meta_tags(that mmdetection otherwise creates like when I train a model) in the checkpoints file that I save, and secondly, do I need to make any changes to the config file in order for my changes to be reflected when I initialize the model?

**Comment by jbwang1997** [comment]
As far as I know, you can prepare two detectors, one has one linear layer and the other has two layers. After decomposition, you can change the config's model type and use the new model to load the decomposed checkpoint.

**Comment by SourabhRanade** [comment]
@jbwang1997  okay, I will try this approach

**Comment by SourabhRanade** [comment]
@jbwang1997 I tried a couple of things but had no luck. Could you confirm my understanding : 
As far as I could understand, we have to load the model with single layers (the original model), then run the decomposition to create the new/updated model and save it in a checkpoint. Lastly, update the value for the "checkpoint" tag in the config file to load the new checkpoint in the following initializations.

If I get it right, this approach won't  work as when initializing this model it would load the model structure from something like : 
/content/mmdetection/mmdet/models/backbones/swin.py.  Maybe I am wrong but I haven't managed to solve it.  Could you guide me a bit more?

**Comment by jbwang1997** [comment]
Sorry for not being clear. In my consideration, you can create a new backbone including two linear layers. After getting the decomposed checkpoint, you can update the value of `type` to your new backbone and the value of `checkpoint` to the decomposed checkpoint.
