### ISSUE TITLE
Sparse RCNN: proposal bboxes initialization error

### ISSUE THREAD

**Issue by yixuanli98** [open-mmlab/mmdetection#7174]
Original SparseRCNN initializes the proposal bboxes to the size of  the entire image [https://github.com/PeizeSun/SparseR-CNN/blob/0d2909895fecca7051f0820328345fc61ff0a6e6/projects/SparseRCNN/sparsercnn/detector.py#L58](https://github.com/PeizeSun/SparseR-CNN/blob/0d2909895fecca7051f0820328345fc61ff0a6e6/projects/SparseRCNN/sparsercnn/detector.py#L58). But the function init_weights in [embedding_rpn_head.py](https://github.com/open-mmlab/mmdetection/blob/7a9bc498d5cc972171ec4f7332afcd70bb50e60e/mmdet/models/dense_heads/embedding_rpn_head.py#L44) is not called and the proposal bboxes are initialized randomly.

**Comment by jbwang1997** [comment]
All submodules' init_weights function is called when we call model.init_weights in [train.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L183). You can refer to [BaseModule](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_module.py) for details about initialization.
There is also a tutorial about [init_cfg](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/init_cfg.md).

**Comment by yixuanli98** [comment]
I get it! I have adapted a module of mmdetection to mmaction2. But model.init_weights is not called in train.py of mmaction2. I will module.init_weight manually. Thanks a lot for your quick reply.
