### ISSUE TITLE
A puzzling question.

### ISSUE THREAD

**Issue by zqyJason** [open-mmlab/mmdetection#7177]
When I try to modify a file (e.g. `rfp.py `in `neck`) in the downloaded mmdetection2.21 project (e.g. simply perform printing parameter operations), it is found that the modification is invalid after running. I can only modify the source files in the corresponding environment of the project to take effect, which is confusing and incomprehensible. After checking a lot of posts and official documentation, I don't know what to do with the problem, and I can't accept the operation of modifying the source files. Can you guys help me?

**Comment by dnth** [comment]
How did you install the mmdet package?

**Comment by zqyJason** [comment]
Yes, as you said, I followed the documentation guide for project installation
> ```
> pip install openmim
> mim install mmdet
> ```
But it doesn't seem to work, and other projects have also encountered strange problems. My computer system environment perhaps has some problems, I guess reinstalling the system will improve the situation. Thanks for your generous answer!

**Comment by BIGWangYuDong** [comment]
I'll close this issue. Please feel free to re-open or create a new issue if you meet problems.
