### ISSUE TITLE
How to use test.py to evaluate the accuracy of existing models and display them in the terminal (pytorch1.1.0)

### ISSUE THREAD

**Issue by GuoxingYan** [open-mmlab/mmdetection#718]
I am using a single gpu, voc format, the command is as follows
Python ./tools/test.py configs/dcn/cascade_rcnn_dconv_c3-c5_r50_fpn_1x.py work_dirs/cascade_rcnn_dconv_c3-c5_r50_fpn_1x/epoch_12.pth --eval bbox --show
In the displayed picture, there is no detected box, and finally the result of the accuracy evaluation is not displayed in the terminal.

**Comment by LiDaiY** [comment]
I have the same problem. Have you solved it now? Could you tell me how to do

**Comment by marsggbo** [comment]
SOS, have you solved it?
