### ISSUE TITLE
self.neg_pos_ub 's meaning is confused

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#7184]
In RandomSampler.py, the arg neg_pos_up is supposed to be the upper bound number of negative and positive samples. But in the code, it's actually the upper bound of  (the number of the negative samples)/(the number of the pos samples). Why?
```python
BaseSampler.py line 91
if self.neg_pos_ub >= 0:
            _pos = max(1, num_sampled_pos)
            neg_upper_bound = int(self.neg_pos_ub * _pos)
            if num_expected_neg > neg_upper_bound:
                num_expected_neg = neg_upper_bound
```

**Comment by hhaAndroid** [comment]
@Icecream-blue-sky There may be ambiguity in naming. If you are interested, you can create a PR to modify it.
