### ISSUE TITLE
How to Draw Precision vs Recall Curve? Is there any files/tools within mmdetection library that facilitates this?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#7193]

**Comment by Chop1** [comment]
look at this script, it is part of mmdetection

https://github.com/open-mmlab/mmdetection/blob/7a9bc498d5cc972171ec4f7332afcd70bb50e60e/tools/analysis_tools/coco_error_analysis.py#L43

It can generate precision recall curve and other usefull insights.

**Comment by Soodep** [comment]
Does this work for pascal voc?
