### ISSUE TITLE
为什么mmdetection复现的算法速度相较于论文中相差甚远？

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#7195]
我使用mmdetection训练算法并进行部署，但是发现推理速度与原论文相差很大。
当我使用YOLOX-s时，推理速度大概只能达到25fps,但是原论文中大概可以到80fps
当我使用FCOS是，推理速度大概不到10fps,原论文中大概20-30fps
当我使用cascade-rcnn时，推理速度5fps,论文中10fps
当我使用centernet-resnet18时，推理速度50fps,论文中144fps,
请问我该怎样优化，使用mmdeply大概可以提升多少？

**Comment by twmht** [comment]
it depends on your hardware and software backend.

**Comment by Bin-ze** [comment]
即使不使用v100，而是使用2080ti，这样的性能差距似乎也是非常巨大的，如果使用加速的话，将会有多少提升？


发自我的iPhone

**Comment by ZwwWayne** [comment]
There are many differences in the previous benchmark. For example: whether the post-processing time is calculated in, whether the pre-processing time is calculated in. 
The time also depends on the hardware and software, e.g., CUDA/PyTorch/MMDet version and which GPU card is used (V100/ 1080Ti/2080Ti/3090Ti/T4 are very different). 
Furthermore, it also depends on the acceleration trick or deployment backend, like whether FP16/INT8 is used, or which of TensorRT/ONNXRuntime is used for deployment.

**Comment by ZwwWayne** [comment]
MMDeploy has provided a page for some of the methods, see https://mmdeploy.readthedocs.io/en/latest/benchmark.html
