### ISSUE TITLE
How to set different loss for different layers of FPN like yolov5?

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#7197]
Thanks a lot!

**Comment by chhluo** [comment]
It's can't be realized by simply changing the config file. Take `RetinaNet` as an example, to use different loss for different level outputs, we need to pass a list of different loss config to `anchor_head` and use these loss according to different level here https://github.com/open-mmlab/mmdetection/blob/7a9bc498d5cc972171ec4f7332afcd70bb50e60e/mmdet/models/dense_heads/anchor_head.py#L445

**Comment by clw5180** [comment]
> It's can't be realized by simply changing the config file. Take `RetinaNet` as an example, to use different loss for different level outputs, we need to pass a list of different loss config to `anchor_head` and use these loss according to different level here
> 
> https://github.com/open-mmlab/mmdetection/blob/7a9bc498d5cc972171ec4f7332afcd70bb50e60e/mmdet/models/dense_heads/anchor_head.py#L445

Thanks bro
