### ISSUE TITLE
PyTorch, CUDA and CUDNN version in Docker

### ISSUE THREAD

**Issue by valvgab-bh** [open-mmlab/mmdetection#7199]
In the Dockerfile shared within this library (at [this](https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile) link), there is a dependency on older versions for PyTorch, CUDA and CUDNN:
```bash
ARG PYTORCH="1.6.0"
ARG CUDA="10.1"
ARG CUDNN="7"
```
However, from the compatibility table of MMCV ([here](https://github.com/open-mmlab/mmcv)) it seems that it is possible to use newer torch and cuda versions. 

Is there a reason why MMDetection Dockerfile uses older versions? Are there compatibility issues I should be aware of?

**Comment by chhluo** [comment]
The setting in docker file is one of common choices. Actually you can use newer torch and cuda. We use multiple combinations in CI https://github.com/open-mmlab/mmdetection/blob/78b1e71fbf714c21155f7cbbe99e3894de3d9f41/.github/workflows/build.yml#L92 
https://github.com/open-mmlab/mmdetection/blob/78b1e71fbf714c21155f7cbbe99e3894de3d9f41/.github/workflows/build.yml#L166
