### ISSUE TITLE
Error when I run the test command in model faster_rcnn

### ISSUE THREAD

**Issue by GYee** [open-mmlab/mmdetection#720]
I had changed my own database to the coco type ,but maybe the way I changed have some problems, when I  ran the demo code with the checkpoint from my train,

it warns"/media/yee/Files/deeplearning_models/mmdetection/mmdetection/mmdet/apis/inference.py:39:
UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
warnings.warn('Class names are not saved in the checkpoint's ' "

but it worked out, it showed the classes of my data in the result.

when I run the test command with"**python tools/test.py configs/faster_rcnn_r50_fpn_1x.py work_dirs/epoch_12.pth --out ./result/result_12.pkl --eval bbox --show**"

It reported that ：

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[                              ] 0/72, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 189, in <module>
    main()
  File "tools/test.py", line 159, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 29, in single_gpu_test
    model.module.show_result(data, result, dataset.img_norm_cfg)
  File "/media/yee/Files/deeplearning_models/mmdetection/mmdetection/mmdet/models/detectors/base.py", line 105, in show_result
    class_names = self.CLASSES
  File "/home/yee/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'FasterRCNN' object has no attribute 'CLASSES'

**Comment by GYee** [comment]
if I remove the parameter "--show" from test command, that is just run the command "python tools/test.py configs/faster_rcnn_r50_fpn_1x.py work_dirs/epoch_12.pth --out ./result/result_12.pkl --eval bbox"

it works.

so what is wrong?

**Comment by GYee** [comment]
I have already solved, see the blog for details: https://blog.csdn.net/gaoyi135/article/details/90613895

**Comment by hellock** [comment]
Thanks for reporting the bug, it should have been fixed in the referenced PR.
