### ISSUE TITLE
Additional Norm layers before feeding features into FPN

### ISSUE THREAD

**Issue by CanyonWind** [open-mmlab/mmdetection#7202]
Hi, I just noticed that when applying the backbone model to downstream tasks, it usually adds additional norm layers for each stage's output, like [here in swin transformer](https://github.com/open-mmlab/mmdetection/blob/7a9bc498d5cc972171ec4f7332afcd70bb50e60e/mmdet/models/backbones/swin.py#L638-L641). 

Are there any particular reasons for this? If so, any insights/paper references would be appreciated. Thanks!

**Comment by chhluo** [comment]
The layer norm after ffn is called pre-layer norm, There is a [survey ](http://arxiv.org/abs/2106.04554) that mentions this. 
![image](https://user-images.githubusercontent.com/26483343/154807978-6d92fb50-81c0-4b96-8d41-89bc57e90c11.png)
