### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'log_level'

### ISSUE THREAD

**Issue by gledsonmelotti** [open-mmlab/mmdetection#7203]
Hello everyone, how are you? I'm trying to train a model as per the tutorial https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb, but directly using spyder instead of Colab. 

I use model = build_detector( cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg')), but I got a error:
AttributeError: 'ConfigDict' object has no attribute 'log_level'

Could anyone provide a solution please?

**Comment by BIGWangYuDong** [comment]
Please use the `error template`, or at least provide a config and command to reproduce your errors.
