### ISSUE TITLE
how to use DCN in other backbones？

### ISSUE THREAD

**Issue by henryccl** [open-mmlab/mmdetection#7205]
I'm looking for the code that implements Deformable Conv (DCN or DCNv2), where is it? I have researched the backbone code in mmdet and it seems that DCN is only used in the resnet series. How can I apply DCN to other backbone networks? (like CSPDarkNet)

**Comment by BIGWangYuDong** [comment]
the configs are at here:
https://github.com/open-mmlab/mmdetection/tree/master/configs/dcn
https://github.com/open-mmlab/mmdetection/tree/master/configs/dcnv2

The using example can refer to 
https://github.com/open-mmlab/mmdetection/blob/7a9bc498d5cc972171ec4f7332afcd70bb50e60e/mmdet/models/backbones/resnet.py#L189-L197

which is in mmcv

**Comment by henryccl** [comment]
oh， thank you for your answer！

**Comment by WangLibo1995** [comment]
from mmcv.cnn import build_conv_layer

sk1 = build_conv_layer(dict(type='DCNv2', deform_groups=1), 3, 6, kernel_size=3, 
                                     stride=1, padding=1, dilation=1, bias=False)
feats = torch.randn((1, 3, 16, 16))
out = sk1(feats)
print(out.shape)

I test the DCNv2, a error raised:
![image](https://user-images.githubusercontent.com/38718224/158126984-cdc44c5d-b165-4fa3-836c-6993e155c8a6.png)
Any error in my code? How to correct it?

**Comment by WangLibo1995** [comment]
I checked the mmcv
![image](https://user-images.githubusercontent.com/38718224/158127676-94e03208-bb74-4dbc-9320-a663d829ffc8.png)
It seems not support for DCNv2
