### ISSUE TITLE
"matrix contains invalid numeric entries"在训练SparseNet网络时,训练几轮就报错.

### ISSUE THREAD

**Issue by zhaoyanjoin** [open-mmlab/mmdetection#7208]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1.我看到说这个是loss为nan的情况.所以我降低了学习率,但是仍然报错. 而且数据集在YOLOX上可以训练.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

**Comment by BIGWangYuDong** [comment]
more details are needed. Please use the issue template.
