### ISSUE TITLE
Adding new layers to FPN

### ISSUE THREAD

**Issue by Hwang64** [open-mmlab/mmdetection#721]
I add some new layers to FPN ( mmdetectoin/mmdet/models/necks/fpn.py) using the config file: faster_rcnn_r101_fpn_1x.py, when running the new model, I find there is no change, the new added layers do not work, so I wonder how to add new layers to the FPN? Thank you for your help.

**Comment by thangvubk** [comment]
At least, the performance did not decrease :D. Improving a model is not just simply adding new layers. You may figure out all your own.
