### ISSUE TITLE
Json format of results on demo image

### ISSUE THREAD

**Issue by iliasprc** [open-mmlab/mmdetection#7211]
Hello, I am trying to run a detection predictor on demo images and I woul like to get the results in a json format ( bbox coordinates, class ...)
Could anyone help? Is there a specific function for that ?

**Comment by BIGWangYuDong** [comment]
Seems that we did not give a script to convert results to json format, 
You can use `python tools/test.py CONFIG_PATH CKPT_PATH --out xxx.pkl` to save the result.
the result is list[list[ndarry]] which means
[
     [ [class-1 bboxes], [class-2 bboxes]...  ],
     [ [class-1 bboxes], [class-2 bboxes]...  ],
