### ISSUE TITLE
Your latest version may not work.

### ISSUE THREAD

**Issue by sjytker** [open-mmlab/mmdetection#7214]
I install your latest version, which is mmdet==2.21.0, causing error `ValueError: need at least one array to concatenate `.
However, I used to work well in mmdet==2.18.0 with totally the same dataset.
But now I couldn't run the programme even if I install the version back to 2.18.0.
What should I do?

**Comment by jiachen0212** [comment]
ValueError: need at least one array to concatenate .   i got the same bug....
