### ISSUE TITLE
How can get the bounding box with largest score?

### ISSUE THREAD

**Issue by wuyuuu** [open-mmlab/mmdetection#7222]
Dear developers,

I'm a beginner to object detection and mmdet.

Now I'm using your work for my own project and my aim is to detect only one object in a given image. (The image is assumed to contain only one meaningful object). So basically I want to use your detection model and select the bounding box with largest score.

I use the model you mentioned in [get_started](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md):

```
from mmdet.apis import init_detector, inference_detector

config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
# url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
device = 'cuda:0'
# init a detector
model = init_detector(config_file, checkpoint_file, device=device)
# inference the demo image
inference_detector(model, 'demo/demo.jpg')
```

and I can get a list of 80 ndarrays from inference_detector. 

So I'm wondering what is the meaning of the detection result. Does the index of the list represent the category and each ndarray is a series of bounding boxes that contains a specific object (I guess the format is (lx,ly,rx,ry,score)? ). And if so, do you provide APIs to transfer an index to its related category name?

Thanks for your work!
Best wishes,
Yu

**Comment by jbwang1997** [comment]
Yes, the index of the list represents the category in `mmdet/datasets/coco.py` CLASSES. You can directly find the corresponding category name by indexing CocoDataset.CLASSES.

**Comment by wuyuuu** [comment]
> Yes, the index of the list represents the category in `mmdet/datasets/coco.py` CLASSES. You can directly find the corresponding category name by indexing CocoDataset.CLASSES.

Thanks, your reply helps a lot!
