### ISSUE TITLE
attribute error raised when training on KITTI dataset using MMDetection3D

### ISSUE THREAD

**Issue by sparshgarg23** [open-mmlab/mmdetection#7224]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help. Yes,I was able to trace the bug,and figure out the cause,and would like your opinion on how to resolve it on my end.

**Describe the bug**
The following error was raised when working with MMDetection3D.However,since the trace pointed to a specific line in MMDetection.apis.,I thought of bringing it to your notice also.
While training SECOND/Point Pillar on KITTI3D when single_gpu_test.py is executed,an attribute error is raised.Inside the single_gpu_test.py there is a line 
```
 PALETTE = dataset.PALETTE

```
which is raising the error.

I looked at MMDetection version 2.19 and the specific line which is causing the error is not mentioned .As such ,I would like some help in figuring out which version of MMDet,MMSeg and MMDetection3d should I install,so that the above issue doesn't happen.

I tried training HRNet using MMSeg on ADE and there was no issues,same for SOLO.In both scenarios I used the master branch.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py /content/mmdetection3d/configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? No modifications were made in the code,I am just testing it to get an idea of how the training process looks like.Once that's done,then I will customize the configurations.
3. What dataset did you use? KITTI 3D

**Environment**
Using colab
Enviroment/system config
```
sys.platform: linux
Python: 3.7.12 (default, Jan 15 2022, 18:48:18) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla P100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
 
  - CuDNN 8.0.5
  - Magma 2.5.2
  -

TorchVision: 0.11.1+cu111
OpenCV: 4.1.2
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.21.0
MMSegmentation: 0.21.1
MMDetection3D: 0.18.1+86cc487
```
1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] No I am using colab 
  

**Error traceback**
If applicable, paste the error trackback here.
```
File "tools/train.py", line 235, in <module>
    main()
  File "tools/train.py", line 231, in main
    meta=meta)
  File "/content/mmdetection3d/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/test.py", line 25, in single_gpu_test
    PALETTE = dataset.PALETTE
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError
```
```


**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
I think that I am not installing the correct version of MMDetection,because the master branch includes a term called PALETTE with the dataset but the branch 2.19 doesn't include the pallete term.
The problem is that when I install MMDetection via pip,it seems that pip ends up installing the master branch which causes an error when I run the training script on KITTI 3D.

**Comment by shinya7y** [comment]
Related bug: https://github.com/open-mmlab/mmdetection/pull/7085
Issue in MMDetection3D: https://github.com/open-mmlab/mmdetection3d/issues/1259

**Comment by sparshgarg23** [comment]
Yes I was the one who raised,I was able to resolve it using a different version of MMdet 2.19

**Comment by shinya7y** [comment]
Please keep this issue open while the latest version has the bug.
