### ISSUE TITLE
Handling ignore flag in annotation during training

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#7225]
Hi, I understand that when there is an annotation with ignore flagged, detections associated to it [will be ignored during COCO mAP evaluation](https://github.com/open-mmlab/mmdetection/issues/3972). However, during training, will the loss associated to the annotation be ignored as well? 

Thanks!

**Comment by jbwang1997** [comment]
All annotations with ignore flagged will be removed in [_parse_ann_info](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L160-L163).

**Comment by jbwang1997** [comment]
Feel free to reopen the issue if there is any question.
