### ISSUE TITLE
Accessing other data points in pipeline

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#7229]
Hi, I'm implementing a new pipeline/augmentation that requires read access to the other data points (image & annotations) within the batch (or the entire dataset). From what I understand, the __call__ method takes in results, which only contains information of the input data point. Do you have any suggestions on how I can access the other data points? Thank you!

**Comment by shinya7y** [comment]
Is the following code what you are looking for?
* `MultiImageMixDataset` https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py
* `get_indexes` in `Mosaic` and `MixUp` https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py

**Comment by levan92** [comment]
Looks good, will start looking from these. Thank you so much!
