### ISSUE TITLE
为什么MMDetection中的YOLOX-s比原文的代码实现在推理时间上要慢两到三倍？

### ISSUE THREAD

**Issue by volcanolee4** [open-mmlab/mmdetection#7234]
输入都是640，640，3的tensor，不算后处理，测试发现MMDetection中的推理速度为20-30毫秒/张，而原文的代码为9-14毫秒/张。

**Comment by hhaAndroid** [comment]
@volcanolee4 Because we have some extra operations like `bbox2result` and `float.cuda` etc. If you put these aside, the speed is the same.

**Comment by volcanolee4** [comment]
@hhaAndroid Thaks for you reply! But actually the way I get the inference speed of  YOLOX in mmdetection is as follows:
with torch.no_grad:
        startt=time.time()
        results=model(return_loss=True,rescale=True,**data)
        endt=time.time()
        print('Total time is:',endt-startt)
These code without any preprocess or postprocess still  consume 30 ms for a single 640*640*3 input.I wonder is there any process you mentioned above which consumes so much time?And the inference time in YOLOX's original code just consume 11ms/per image even with post-processing like nms.

**Comment by www516717402** [comment]
@volcanolee4 you can translate .pth to onnx for compare cost time avoid pre and post precess.

**Comment by RangiLyu** [comment]
> @hhaAndroid Thaks for you reply! But actually the way I get the inference speed of YOLOX in mmdetection is as follows: with torch.no_grad: startt=time.time() results=model(return_loss=True,rescale=True,**data) endt=time.time() print('Total time is:',endt-startt) These code without any preprocess or postprocess still consume 30 ms for a single 640x640x3 input.I wonder is there any process you mentioned above which consumes so much time?And the inference in YOLOX's original code just consume 11ms/per image even with post-processing like nms.

The way you get inference speed is incorrect. Please follow the tools/analysis_tools/benchmark.py.

**Comment by lzvvva** [comment]
我遇到的刚好相反，当我使用FCOS和Faster RCNN时都超过了两百FPS，这显然是不正常的，速度均在2080Ti上测试的，命令是python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py \
       configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py \
       checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
       --launcher pytorch
请问这是什么原因？
