### ISSUE TITLE
Try to modify the NMS code

### ISSUE THREAD

**Issue by Ahappyprogrammer** [open-mmlab/mmdetection#7238]
I'm trying to change the threshold of soft-NMS and the way of reduction score, but I find that it involves nms.py in mmcv, I want to know how to modify it.

**Comment by taofuyu** [comment]
just modify the source file directly

**Comment by Ahappyprogrammer** [comment]
> 直接修改源文件即可

I tried to modify the nms.py in mmcv,  but I found that it used the ext_module. It seems to encapsulate the method, and I don't know how to continue to find its code.
inds = ext_module.softnms(
            boxes.cpu(),
            scores.cpu(),
            dets.cpu(),
            iou_threshold=float(iou_threshold),
            sigma=float(sigma),
            min_score=float(min_score),
            method=int(method),
            offset=int(offset))

**Comment by taofuyu** [comment]
it's c++ code, in mmcv/ops/csrc/pytorch

**Comment by Ahappyprogrammer** [comment]
> it's c++ code, in mmcv/ops/csrc/pytorch

Thanks for your answer
