### ISSUE TITLE
ImportError: No module named 'mmdet.ops.masked_conv.modules'

### ISSUE THREAD

**Issue by hust-kevin** [open-mmlab/mmdetection#724]
actually I have done
```shell
sudo sh compile.sh
sudo python3.5 setup.py install
```

**Comment by lzy00codeforfun** [comment]
@hust-kevin @hellock hello. I 've met this too.  I found that the __init__.py in
` /mmdet/ops/masked_conv/modules `  is written as __Init__.py in the source code. Fixing this could help.

**Comment by hellock** [comment]
@lzy00codeforfun Thanks for reporting!
