### ISSUE TITLE
Why setting up 'cudnn_benchmark = True' when training SSD? 

### ISSUE THREAD

**Issue by ZhihuaGao** [open-mmlab/mmdetection#725]
The other detection algorithm not...why?
@yhcao6

**Comment by yhcao6** [comment]
When the input size is fixed (in SSD the input size is either 300 or 512), setting up `cudnn_benchmark = True` can speed up training and inference; In other algorithms the input size is usually variable, which will slow down if enable `cudnn_benchmark`.

**Comment by ZhihuaGao** [comment]
Thank you...
