### ISSUE TITLE
Will add KeyPoint-RCNN

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmdetection#7256]

**Comment by chhluo** [comment]
MMdetection + MMpose can realize the object detection and keypoint detection, see demo in MMPose 
 https://github.com/open-mmlab/mmpose/tree/master/demo, and script https://github.com/open-mmlab/mmpose/blob/master/demo/top_down_img_demo_with_mmdet.py for detail. If you want to add this algorithm，prs are welcomed.
