### ISSUE TITLE
How about the AP of models with sync bn?

### ISSUE THREAD

**Issue by Z-Zheng** [open-mmlab/mmdetection#726]
I trained faster rcnn with fpn50 with 1x lr schedule using sync bn, but the performance is worse，even AP ~= 0 after several epochs.

**Comment by hellock** [comment]
This is a known issue for the official syncbn implementation. For some models, it can decrease to 0 after some epochs, but may return to normal at last.
We have not figured out the reason.

**Comment by Z-Zheng** [comment]
OK, thank you.

**Comment by amsword** [comment]
@hellock do you know if there is any sync-BN implementation (non-official sync-bn), which works as expected?
