### ISSUE TITLE
Where is the path to the downloaded pretrain models?

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#7260]
Like the question, I cannot find the pretrain models in my computer, or if there are any infos about the pretrain models? e.g., training epochs, etc.

**Comment by chhluo** [comment]
The directory for pretrained model is `/home/xxx/.cache/torch/hub/checkpoints/` on linux or ` C:\Users\xxx\.cache\torch\hub\checkpoints\` on windows.
