### ISSUE TITLE
我在使用coco训练集训练出来的网络比如Faster r-cnn在推理时只显示某一类比如人或者某几类的结果，这个可以设置吗

### ISSUE THREAD

**Issue by liuzhihengg** [open-mmlab/mmdetection#7265]
如标题

**Comment by chhluo** [comment]
Not supprted yet.If you use this script https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py to do inference, you can add a few line code to choose the classes you want. https://github.com/open-mmlab/mmdetection/blob/52a32763bef402a5eb684625d974eebe29755351/mmdet/models/detectors/base.py#L338 
And classes order of coco is here https://github.com/open-mmlab/mmdetection/blob/52a32763bef402a5eb684625d974eebe29755351/mmdet/datasets/coco.py#L25

**Comment by liuzhihengg** [comment]
谢谢，我已经解决了这一问题。通过将person之外的结果全部置为空，结果只会有person。谢谢您给的链接给了我提示，这才使得我能通过debug调试出来解决方案
`model = init_detector(args.config, args.checkpoint, device=args.device)
    # test a single image
    result = inference_detector(model, args.img)
    for i in range(1,80):
        result[i] = np.zeros((0, 5), dtype=np.float32)
    # show the results
    show_result_pyplot(
        model,
        args.img,
        result,
        palette=args.palette,
        score_thr=args.score_thr)`
