### ISSUE TITLE
some error in test.py

### ISSUE THREAD

**Issue by zhuofalin** [open-mmlab/mmdetection#7267]
Traceback (most recent call last):
  File ".\tools\test.py", line 5, in <module>
    from mmcv.runner import load_checkpoint, parallel_test, obj_from_dict
ImportError: cannot import name 'parallel_test' from 'mmcv.runner' (f:\mmcv\mmcv\runner\__init__.py)

I need to help

**Comment by RangiLyu** [comment]
Please follow the issue template to provide more detailed information such as the mmdetection version and mmcv version you are using.
