### ISSUE TITLE
How to use pre-trained models for backbone that is not supported by mmdet?

### ISSUE THREAD

**Issue by henryccl** [open-mmlab/mmdetection#7268]
Hi！I'm using ConvNeXt ( mmdet does not implement this method) as backbone for yolo v3.  I can train normally without pre-train model. Now I want to load the pretrain weights. How do I load a pre-trained model for a model that only has network structure logic? Is there a sample implementation?

**Comment by henryccl** [comment]
https://github.com/facebookresearch/ConvNeXt

**Comment by Williamlizl** [comment]
> https://github.com/facebookresearch/ConvNeXt

I met the same issue,,,,, maybe we need to change some config file and code

**Comment by shinya7y** [comment]
This PR will support ConvNeXt. https://github.com/open-mmlab/mmdetection/pull/7281

**Comment by henryccl** [comment]
> This PR will support ConvNeXt. #7281

Thank you！

**Comment by wzr0108** [comment]
I have the same problem. Have you solved it?
