### ISSUE TITLE
What does the number beside the label mean?

### ISSUE THREAD

**Issue by chchenhui** [open-mmlab/mmdetection#727]
I ran the code to test the image. And the outputs not only point out labels but also a number. What does it mean? Is it a probability?
<img width="755" alt="image" src="https://user-images.githubusercontent.com/13835142/58460435-39ea2300-8160-11e9-94a6-cf134f3cb2fc.png">
And the following is the testing codes:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/13835142/58460510-643be080-8160-11e9-890d-23486af5d6fc.png">

**Comment by hellock** [comment]
Yes it is the probability.

**Comment by chchenhui** [comment]
> Yes it is the probability.

And what does this probability represent?

**Comment by hellock** [comment]
The probability of being an object of that category.

**Comment by chchenhui** [comment]
> The probability of being an object of that category.

Got it! Thanks a lot.
