### ISSUE TITLE
how to unfreeze backbone

### ISSUE THREAD

**Issue by Bulbbbb** [open-mmlab/mmdetection#7273]
hi，I want to know  how to unfreeze backbone after I freeze the backbone in resnet. I noticed that you didn't provide this feature. Do I need to implement this feature myself ? Do you have a better solution?

**Comment by hhaAndroid** [comment]
@Bulbbbb 
```python
 backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1, ###############
        ...,
```

**Comment by Bulbbbb** [comment]
> @Bulbbbb
> 
> ```python
>  backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=-1, ###############
>         ...,
> ```

@hhaAndroid  Thanks for replying. Do I need to re-instantiate an object.
