### ISSUE TITLE
How does Registry work?

### ISSUE THREAD

**Issue by dr-GitHub-account** [open-mmlab/mmdetection#7278]
I am currently reading train.py and trying to dive into the modules in train.py. Now I wonder how Registry works. I have read [https://mmcv.readthedocs.io/en/latest/understand_mmcv/registry.html](url) and gain a little knowledge about what Register is. I might still need a single example that illustrates how Registry is defined and used. I believe taking BACKBONE as an example would be enough since every other usage of Register is supposed to be similar with BACKBONE.

**Comment by hhaAndroid** [comment]
@DrX2020 Thanks for your feedback, we recently had a major update.

**Comment by DrX2020** [comment]
I did not notice that an update had been made. Could you please tell me what the update is about?

**Comment by hhaAndroid** [comment]
Registry is a decorator function, and its essence can be represented by the following code:

```python

# define 
_module_dict={}

def register_module(name):
    def _register(cls):
        _module_dict[name] = cls
        return cls

    return _register

# use
@register_module('one_class')
class OneTest(object):
    pass

@register_module('two_class')
class TwoTest(object):
    pass

if __name__ == '__main__':
    # Instantiation by registering the class name
    one_test = _module_dict['one_class']()
    print(one_test)

# output
<__main__.OneTest object at 0x7f1d7c5acee0>

```

**Comment by myxik** [comment]
In the new update, registry works withing the config, where you specify `custom_imports` field, more can be read following this [documentation](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_runtime.md#2-add-the-optimizer-to-registry)

**Comment by DrX2020** [comment]
Thank you!
