### ISSUE TITLE
Using DynamicHead with Faster-RCNN

### ISSUE THREAD

**Issue by smcs88** [open-mmlab/mmdetection#7287]
Hello, how should the DynamicHead config be modified for two-stage object detection using Faster-RCNN?

**Comment by shinya7y** [comment]
Example to modify [`faster_rcnn_r50_fpn_1x_coco.py`](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py) to `faster_rcnn_r50_fpn_dyhead_1x_coco.py`:

```python
_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

model = dict(
    # add DyHead after FPN
    neck=[
        dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            num_outs=5),
        dict(type='DyHead', in_channels=256, out_channels=256, num_blocks=6)
    ])
```

Note:
- I have not trained the model and reproduced AP.
- To reproduce the Faster R-CNN result of the official implementation, other efforts are needed. It will be helpful to see diff between the two configs of ATSS+DyHead.
- The code is based on the official implementation, which is different from Figure 2 (c) of the DyHead paper.

**Comment by smcs88** [comment]
>     * The code is based on the official implementation, which is different from Figure 2 (c) of the DyHead paper.
This answers my question, thank you for the clarification!
