### ISSUE TITLE
Slurm_train.sh doesn't work, the code get stuck

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#7289]
I try to train my model on multiple nodes(two node) with the slurm_train.sh. My script is as below:
```bash
#!/bin/bash
#SBATCH -J sgrn
#SBATCH -o sgrn-%j.log
#SABTCH -e sgrn-%j.err
#SBATCH -N 2
#SBATCH -n 8 
#SBATCH -p GPU-V100 
#SBATCH --gres=gpu:v100:2
echo This job runs on the following nodes:
echo $SLURM_JOB_NODELIST
echo loaded module: ################################
module list
cd HTD
GPUS=4 ./tools/slurm_train.sh GPU-V100 sgrn configs/htd/htd_resnet50_1x.py
```
The training process get stucked after "index created" even if I set the works_per_gpu=0.  The GPU-Util gets stucked at 100%. Besides, I can successfully run the code on single node.
![image](https://user-images.githubusercontent.com/26771037/156093315-91406c1c-a12a-47e5-8dc9-ccd9c94ead60.png)
![image](https://user-images.githubusercontent.com/26771037/156093366-f320eb77-6512-43a6-90b7-c6fbea16eb23.png)
Is this a bug?

**Comment by Icecream-blue-sky** [comment]
> How many resources do you want to use for your job? It might be caused by wrong command. It smees that you are using sbatch commands to run a slurm scripts. The GPU number seems to be conflicted.
Two nodes. And there are two v100 on each node. So the number of gpu I need is 4. The fig2 is the screenshot of one of the nodes. Same result for another node.

**Comment by ZwwWayne** [comment]
You should able to do that by simply run
```
GPUS=4 GPUS_PER_NODE=2 sh ./tools/slurm_train.sh GPU-V100 sgrn xxxx
```
