### ISSUE TITLE
Can there be clearer separation between official codes and external codes? 

### ISSUE THREAD

**Issue by yxchng** [open-mmlab/mmdetection#729]
Right now, there are many pull requests being merged into the codebase but there is no clear indication of which are official and which are not. Having clear separation will allow people to know which code can be used with confidence and which should be used with caution, which is a good thing.

Maybe have a folder called `official` and `external` in `configs`?

**Comment by hellock** [comment]
Recent PRs are usually created by the authors of corresponding papers, which should be reliable. Before a PR is merged into the master branch, there is a code review to make sure the code works well and can be integrated into existing codebase smoothly.
