### ISSUE TITLE
Changing number of classes

### ISSUE THREAD

**Issue by semeka13** [open-mmlab/mmdetection#7294]
What is the right way of changing num_classes? I'm trying to use queryinst for one class instance segmentation. The approach of writing configure file in mmdetection tutorial is not suitable here.

**Comment by RangiLyu** [comment]
What problem are you having? Please follow the issue template to provide more detailed information.

**Comment by ZwwWayne** [comment]
This issue is closed as there is no response. You can create a new issue following the issue template.
