### ISSUE TITLE
colab tutorial does not work by error installing mmcv-full

### ISSUE THREAD

**Issue by gabrielalexandre** [open-mmlab/mmdetection#7299]
First of all, sorry for the bad english, i'm not fluent.
I'm traveling and I went to use colab to continue my project, I saw the tutorial available, but in the installation cell (!pip install mmcv-full) the following error occurs
  Building wheel for mmcv-full (setup.py) ... error
  ERROR: Failed building wheel for mmcv-full
Not completing the installation
is this a problem with colab or with mmcv?

**Comment by gabrielalexandre** [comment]
I managed to get around the problem using an earlier version of mmcv(1.4.1)

**Comment by mathur01** [comment]
This work for me 
`!pip install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/11.1/torch1.10.0/index.html`
but took 32 mins to get load on google colab
