### ISSUE TITLE
How to extract the region proposals of the dataset using trained RPN?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#7300]
I want to extract region proposals of the dataset ( pascal voc format ). I will use these region proposals to train fast_rcnn later. I have trained RPN model based on my dataset but how can I use this model to extract region proposals ( in the form of .pkl file )?

**Comment by jbwang1997** [comment]
If you use the [RPN](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/rpn.py) model in mmdetection. you can directly save the proposals by adding --out [PKL_ROOT] after test.py

**Comment by jbwang1997** [comment]
Fast R-CNN is not an end-to-end model. It needs external proposals to finish the detection task. In the original Fast R-CNN paper, they directly use selective search to generate proposals from images. If you want to train a pure Fast R-CNN, you need to use selective search to generate proposals. RPN is proposed by Faster R-CNN, which is later than Fast R-CNN.

**Comment by Soodep** [comment]
Thank you very much for the explanation. Would you please suggest me if there is support for generating proposals via selective search in mmdetection. ( or in any other library)?

**Comment by jbwang1997** [comment]
We didn't implement selective search in mmdetection. You can refer to https://github.com/AlpacaDB/selectivesearch.
