### ISSUE TITLE
Is there a baseline,when use mobilenet as the backbone for faster-rcnn or mask-rcnn?

### ISSUE THREAD

**Issue by kirkzZ** [open-mmlab/mmdetection#7303]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by jbwang1997** [comment]
For now, we only provide yolov3 with mobilenet backbone. For Faster R-CNN and Mask R-CNN, you can change their backbones to mobilenet by adapting their configs.
