### ISSUE TITLE
我想要自定义NMS，请问如何实现

### ISSUE THREAD

**Issue by liuzhihengg** [open-mmlab/mmdetection#7305]
如题

**Comment by liuzhihengg** [comment]
Sorry，I understand.Next time, I will write by english.

**Comment by jbwang1997** [comment]
We don't have a unified format for NMS. you can code your logic directly.
Here are the source codes of NMS for reference:
https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cuda/nms_cuda.cu
https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cpu/nms.cpp
https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/nms.py

**Comment by jbwang1997** [comment]
Hello. We will first close this issue. Feel free to reopen it if you have any questions.
