### ISSUE TITLE
Fasterrcnn FPS difference between torchvision and mmdetection implementation

### ISSUE THREAD

**Issue by Jaisme** [open-mmlab/mmdetection#7306]
**Backgound**
I trained my custom dataset using both the Faster R-CNN model with a ResNet-50-FPN backbone from [torchvision](https://github.com/pytorch/vision/blob/main/torchvision/models/detection/faster_rcnn.py#L317) and from mmdetection using the configuration [faster_rcnn_r50_fpn_1x_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py).

For both implementations, I only changed the number of classes to 2 and they both run on the same GPU and environment. To measure the inference time (fps) i measure the runtime of simple_test function.

**Hardware**
GPU: NVIDIA GeForce RTX 3090
11th Gen Intel(R) Core(TM) i9-11900 @ 2.50GHz   2.50 GHz

**Question**
As result i get from torchvision model fps 23.96 but from mmdetection implementation only 10.47, where the benchmark from your side is 21.4. Since i want to use mmdetection instead of torchvision, i want to find out what can cause this big fps difference. Could the difference come from the different implementation? Is there anything else i can do to improve the fps?
Any help would be really appreciated!!

**Comment by jbwang1997** [comment]
The `simple_test` function includes inference and post-processing, and the reported time should only include the time of inference. you can use tools/analysis_tools/benchmark.py to get fps.

**Comment by Jaisme** [comment]
Thanks for your reply! I tried to understand the implementation in benchmark.py. Since i only have one GPU, is it still necessary to use MMDistributedDataParallel?

**Comment by jbwang1997** [comment]
Hello. We will close this issue first. Feel free to reopen it if you have any questions.
