### ISSUE TITLE
Official Colab not working

### ISSUE THREAD

**Issue by ayulockin** [open-mmlab/mmdetection#7307]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
The [official colab for mmdetection](https://colab.research.google.com/github/ZwwWayne/mmdetection/blob/update-colab/demo/MMDet_Tutorial.ipynb#scrollTo=gi9zw03oM4CH) seems to not be working. 

It's not able to install mmcv-full. 

<img width="473" alt="image" src="https://user-images.githubusercontent.com/31141479/156438732-1407a516-fc48-4348-b5f1-4299534813a6.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/31141479/156438966-3264919e-a012-4d9c-bc90-f1e5159ed7a3.png">

Upon going through the mmcv repository, I found this [issue](https://github.com/open-mmlab/mmcv/issues/1752) that seems relevant.

**Comment by jbwang1997** [comment]
Thank you for your report, I will check this error as soon as possible.
