### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by TIMAX-159** [open-mmlab/mmdetection#7308]
I encountered two installation errors:
![image](https://user-images.githubusercontent.com/62273225/156444948-6110545d-5a54-434e-88df-7b4c6a381688.png)
![image](https://user-images.githubusercontent.com/62273225/156445074-43edc7f8-64a4-4191-a8a8-e247250216f0.png)
could anyone help me with it?
----------------------------------------------------------------------------------------------------------------------------------------
my environment:

torch              1.9.0+cu102
torchaudio         0.9.0
torchvision        0.10.0+cu102

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

A100-SXM4-40GB

NVIDIA-SMI 450.156.00   Driver Version: 450.156.00   CUDA Version: 11.0

**Comment by jbwang1997** [comment]
Seems the installation failed when building pycocotools. you can try to install pycocotools directly by pip.

**Comment by jbwang1997** [comment]
Hello. We will close this issue first. Feel free to reopen it if you have any questions.
