### ISSUE TITLE
Problems with custom dataset

### ISSUE THREAD

**Issue by hungtran122** [open-mmlab/mmdetection#731]
Hello,

Thanks a lot for such an amazing source code.
I am trying to use this on my custom dataset.
train=dict(
        type=dataset_type,
        ann_file=data_root + '/mydata_train.pickle',
        ...
        proposal_file=None,
        ),
I'm ok with generating pickle file for mydata_train.pickle.
However I don't know how to generate proposal_file.
May I know what proposal_file is? And how can I generate from my own data?

**Comment by thangvubk** [comment]
Proposal_file is output of a region proposal method, and it is supposed to be the output of RPN (or GARPN) here. You can get the ``proposal_file.pkl`` by testing a pretrained RPN, then see Fast RCNN configs for how to use the proposal.

**Comment by hungtran122** [comment]
Thank you.
"You can get the proposal_file.pkl by testing a pretrained RPN"
Can you tell me what pretrained RPN I can use as an example?
