### ISSUE TITLE
KeyError: "RetinaNet: 'PyramidVisionTransformerV2 is not in the models registry

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmdetection#7318]
`import random
import warnings

import numpy as np
import torch
from mmcv import Config
from mmdet.apis import inference_detector, init_detector
import os
import glob
import cv2
import json
import time

#f_path = '/home/zlw/Github/mac_detection/mmdetection/work_dirs/'
config = "/home/lbc/mmdetection-master/configs/pvt/retinanet_pvtv2-b5_fpn_1x_coco.py"
checkpoint = "/home/lbc/mmdetection-master/work_dirs/retinanet_pvtv2-b5_fpn_1x_coco/best_bbox_mAP_epoch_12.pth"
save_path_all = "/home/lbc/mmdetection-master/work_dirs/retinanet_pvtv2-b5_fpn_1x_coco"

# 默认参数
#cfg = Config.fromfile(config_file)
save_path = save_path_all + '/detec_result_compare/'
#if not os.path.exists(save_path):
    #os.mkdir(save_path)
test_image_path = '/home/lbc/Fundus_COCO_20210918/test_for_gpu_test/'
#test_label = '/home/lbc/Fundus_COCO_20210918/annotations/test_2_bbox_label/'
image_list = os.listdir(test_image_path)
model = init_detector(config, checkpoint, device='cuda:3')
s_t = time.time()
for img_i in image_list:
    print(img_i)
    img_path = os.path.join(test_image_path, img_i)
    img = cv2.imread(img_path)
    result = inference_detector(model, img)
    if len(result) == 2:  
        result = result[0]
        print(result)`

**Comment by BIGWangYuDong** [comment]
Hi, please use issue template to ask the issue, cannot get your question right now
