### ISSUE TITLE
show_score_thr not used when multi-gpu test

### ISSUE THREAD

**Issue by zyc573823770** [open-mmlab/mmdetection#7319]
https://github.com/open-mmlab/mmdetection/blob/1872bc44d04601045110186ad566c7117f9a0b2a/tools/test.py#L236

**Comment by zyc573823770** [comment]
I wonder how to set score threshold use multi-gpu mode, however the show_score_thr argument sames not used in multi_gpu_test function.

**Comment by RangiLyu** [comment]
`show_score_thr` is used for visualization. But visualization is only supported during single-gpu test. If you want to filter bboxes with low scores, please set score_thr in test_cfg.

**Comment by zyc573823770** [comment]
i see, thx.
