### ISSUE TITLE
What does bbox_mAP_s means?

### ISSUE THREAD

**Issue by sjytker** [open-mmlab/mmdetection#7325]
Including [bbox_mAP_s, bbox_mAP_m, bbox_mAP_l] when running a fasterRCNN network.
It seems not commonly seen elsewhere, and I couldn't google anything related to them.
I guess if they are three scale of boxes?

**Comment by chhluo** [comment]
These are metrics for small, medium and large objects, refer to https://cocodataset.org/#detection-eval for detail.
