### ISSUE TITLE
How can I understand the graph given by coco_error_analysis.py?

### ISSUE THREAD

**Issue by volcanolee4** [open-mmlab/mmdetection#7326]
Thanks for your contribution.I use the file 'coco_error_analysis.py'  to  analysis my result.I know the meaning of precision，recall ,and mAP，however,I am confused by the symbol in the lower left corner, therefore,I can't understand the curve of this symbols.Can anybody tell me what they mean or what should I learn to understand the graph?
![bbox-allclass-medium](https://user-images.githubusercontent.com/93360352/156877493-6c7057a3-60f0-4967-9032-9a5c1504890f.png)

**Comment by chhluo** [comment]
Please refer to https://cocodataset.org/#detection-eval .
