### ISSUE TITLE
I Want custom faster r-cnn. make rpn head to output full bbox, visible bbox and class. moreover, custom nms to use visible bbox score

### ISSUE THREAD

**Issue by liuzhihengg** [open-mmlab/mmdetection#7329]
I don't understand source code meaning.So, I can't custom model. I hope get help from more detail tutorial for custom model instead of
roughly tutorial on mmdetection official documentation.
If you have free time, Can you hava a meeting or wechat with me for the problem to clearly state the problem.

**Comment by ZwwWayne** [comment]
Have you read the tutorial here? https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html
Could you be more specific about which part you do not know how to do it?

**Comment by liuzhihengg** [comment]
I have read.Can I specific to describe by Chinese?

**Comment by ZwwWayne** [comment]
Sure.

**Comment by liuzhihengg** [comment]
我想要用mmdecttion做行人检测任务，需要把rpn-head原来的cls，bbox分支增加一个可见区域分支，需要多输出4个坐标，然后修改nms算法。针对bbox，vis框和cls三项进行nms。但是，我看不懂源码，一是不明白源码内部的执行逻辑，二是不明白各个变量的含义，所以无从下手。

**Comment by liuzhihengg** [comment]
最后，还需要修改评价指标，将mAP切换为MR，这个在哪里修改也不知道。。

**Comment by chhluo** [comment]
You can wirte a new rpn head, refer to https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html, or modify the original one https://github.com/open-mmlab/mmdetection/blob/1872bc44d04601045110186ad566c7117f9a0b2a/mmdet/models/dense_heads/rpn_head.py#L59

For  `针对bbox，vis框和cls三项进行nms`, you can write a new nms function to replace the original one which is called in rpn head https://github.com/open-mmlab/mmdetection/blob/1872bc44d04601045110186ad566c7117f9a0b2a/mmdet/models/dense_heads/rpn_head.py#L231

For MR, you can overwrite the evaluate method in dataset you use https://github.com/open-mmlab/mmdetection/blob/1872bc44d04601045110186ad566c7117f9a0b2a/mmdet/datasets/custom.py#L291

**Comment by liuzhihengg** [comment]
通过提示，我阅读源码理解了部分问题。但是新的问题出现了，因为我这里需要对数据集进行处理，相比于一般的coco数据集多了一个vis_bbox（4个位置的坐标），并且在训练测试的每一个阶段，vis_bbox的处理都类似于原有的bbox，但是原来的处理流程只针对bbox_label。从数据处理流程引入vis_bbox标签，到后续训练中引入，如何处理

**Comment by liuzhihengg** [comment]
总地来说，数据集中引入了vis_bbox标签，不像我自己用pytorch写的代码可以知道每个模块含义，而且数据从哪到哪，配置文件把数据集加载到了哪里，从哪里调用给了谁，这对我来说像一个黑盒，因此无从下手。

**Comment by chhluo** [comment]
There are lots of article in zhihu https://zhuanlan.zhihu.com/p/341954021, which can help you to understand our design concept.

**Comment by chhluo** [comment]
To load vis_bbox, you can read https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html first

**Comment by liuzhihengg** [comment]
Thank you. I have read the material that you recommand. I have a idea to solve my problem.If I have other problem.I will put a new issue.
