### ISSUE TITLE
How to add new evaluation indicators to the coco dataset?

### ISSUE THREAD

**Issue by lyk595** [open-mmlab/mmdetection#7335]
The evaluation indicators of the coco dataset are only mAP and AR. 
How can I add new indicators?
Such as accuracy and specificity.

**Comment by Czm369** [comment]
You can code a hook function in `mmdet/core/evaluation` and register in `mmdet/apis/train.py`.

**Comment by ZwwWayne** [comment]
If you want to implement a new metric, you should update dataset.evaluate in the coco dataset to support your metric.
