### ISSUE TITLE
maskformer export to onnx got " __init__() got an unexpected keyword argument 'pretrained' "

### ISSUE THREAD

**Issue by Kenneth-X** [open-mmlab/mmdetection#7339]
Thanks for your error report and we appreciate it a lot.
1. What command or script did you run?

```python
python tools/deployment/pytorch2onnx.py \
    configs/maskformer/maskformer_r50_mstrain_16x1_75e_coco.py \
    weights/maskformer_r50_mstrain_16x1_75e_coco_20220221_141956-bc2699cb.pth 
    --output-file maskformer.onnx \
    --input-img demo/test.jpg \
    --test-img demo/test.jpg \
    --dynamic-export
```

**Environment**
sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA A100-SXM4-40GB MIG 3g.20gb
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.2+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.3+cu111
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.22.0+1872bc4

**Error traceback**

Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 324, in <module>
    model = build_model_from_cfg(args.config, args.checkpoint,
  File "/home/xt.xie/.conda/envs/mm/lib/python3.8/site-packages/mmdet/core/export/pytorch2onnx.py", line 89, in build_model_from_cfg
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xt.xie/.conda/envs/mm/lib/python3.8/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/xt.xie/.conda/envs/mm/lib/python3.8/site-packages/mmcv/utils/registry.py", line 213, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xt.xie/.conda/envs/mm/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xt.xie/.conda/envs/mm/lib/python3.8/site-packages/mmcv/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
TypeError: MaskFormer: __init__() got an unexpected keyword argument 'pretrained'

**Comment by Czm369** [comment]
https://github.com/open-mmlab/mmdetection/blob/6ddbff8406aec8b414462badbd57c4013b594afe/tools/deployment/pytorch2onnx.py#L355
This tool has been deprecated. You could try MMDeploy: https://github.com/open-mmlab/mmdeploy

**Comment by Kenneth-X** [comment]
> 
thanks，is the latest mmdeploy already suport maskformer now ?

**Comment by Czm369** [comment]
MMdeploy does not support maskformer now.
