### ISSUE TITLE
How to debug a Faster RCNN step by step？

### ISSUE THREAD

**Issue by rolsheng** [open-mmlab/mmdetection#7344]
I want to know the process of model forward and compute the loss,how can I get it by debugging?Which script should I debug?

**Comment by RangiLyu** [comment]
You can try to use pdb https://docs.python.org/3/library/pdb.html or use an IDE to debug.

**Comment by rolsheng** [comment]
> You can try to use pdb https://docs.python.org/3/library/pdb.html or use an IDE to debug.

so which script should I debug ?
