### ISSUE TITLE
Question about Batch Size Calculation in Distributed and Non-distributed training

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#7345]
In mmdet/dataset/builder.py we have 
    if dist:
        batch_size = samples_per_gpu
        num_workers = workers_per_gpu
    else:
        batch_size = num_gpus * samples_per_gpu
        num_workers = num_gpus * workers_per_gpu

Let's say my original training strategy is 1-gpu, samples_per_gpu=4, lr=0.0025. Now multi-gpu training is supposed to be used (distributed or non-distributed. As far as I am concerned, for multi-gpu we choose distributed or non-distributed training). 

If I want the batch size to be the same as 1-gpu setting (thus lr is also the same, I suppose, since number of iterations remains the same), how do I set multi-gpu distributed and non-distributed training correctly? Thank you!

**Comment by hhaAndroid** [comment]
I understand you mean that you want the total batch to remain the same in the case of single GPU and multi-GPU. If a single GPU bs=4, now you want to use 4 GPU, and the total batch is still 4, and the batch of your single GPU can be set to 1.  But when the batch of a single GPU is relatively small, the performance may be degraded due to the existence of BN.

**Comment by DrX2020** [comment]
Thank you! 

I remember when I tried to use 2 gpus by running dist_train.sh without changing samples_per_gpu in cfg,  the number of iterations per epoch was halved. In my view, when running dist_train.sh, the REAL batch size (different from samples_per_gpu when more than 1 gpus are used) during training will be num_gpus * samples_per_gpu. So when num_gpus is doubled while samples_per_gpu remains the same, the REAL batch size is actually doubled so the number of iterations per epoch is halved. Since the parameters are updated once every iteration, the number of updates is also halved, resulting in slower training. Doubling lr might be a way to alleviate the deceleration.

Is this correct?

**Comment by hhaAndroid** [comment]
Yes

**Comment by DrX2020** [comment]
Thanks a lot!
