### ISSUE TITLE
could not build wheels for pycocotools

### ISSUE THREAD

**Issue by 54wb** [open-mmlab/mmdetection#7348]
1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
when i install mmdetection,using connand pip install -v -e ..The error is Building wheel for pycocotools (pyproject.toml) did not run successfully and Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

my env is cu101 and torch 1.7.0 while my cuda and torch is running ok

i use windows10

**Reproduction**

1. What command or script did you run?
git clone https://github.com/open-mmlab/mmdetection.git (ok)   
cd mmdetection   (ok)
pip install -r requirements/build.txt (ok)  
pip install -v -e . (error)

**A placeholder for the command.**
  (mmdetection) E:\Anaconda\envs\mmdetection\Lib\site-packages\mmdetection>pip install -v -e .
Using pip 22.0.4 from E:\Anaconda\envs\mmdetection\lib\site-packages\pip (python 3.8)

2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?
this stage needn't use dataset,i just want install it well
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: win32
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: GeForce GTX 1050
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
PyTorch: 1.7.1+cu101
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192729112
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_VULKAN_WRAPPER, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.8.2+cu101
OpenCV: 4.5.2
MMCV: 1.4.0
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.1
MMDetection: 2.22.0+6ddbff8
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]   :pip
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
  warning: no files found matching 'mmdet\VERSION'
  warning: no files found matching 'mmdet\.mim\model-index.yml'
  warning: no files found matching 'mmdet\.mim\demo\*\*'
  warning: no files found matching '*.py' under directory 'mmdet\.mim\configs'
  warning: no files found matching '*.yml' under directory 'mmdet\.mim\configs'
  warning: no files found matching '*.sh' under directory 'mmdet\.mim\tools'
  warning: no files found matching '*.py' under directory 'mmdet\.mim\tools'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\ASUS-PC\AppData\Local\Temp\pip-pip-egg-info-0lfm6539\mmdet.egg-info\SOURCES.txt'
done
 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'E:\Anaconda\envs\mmdetection\python.exe' 'E:\Anaconda\envs\mmdetection\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ASUS-PC\AppData\Local\Temp\tmpl3p1g0jb'
  cwd: C:\Users\ASUS-PC\AppData\Local\Temp\pip-install-nsai7zl7\pycocotools_ad6054d7e050485ab52f31f62aca901d
error
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@54wb `error: Microsoft Visual C++ 14.0 or greater is required.` You need to update Microsoft Visual C++ version.

**Comment by 54wb** [comment]
Thank you very much for your help..while I updata MicroSoft Visual C++ version，this error is solved perfectly.If someone else has the same problem, please read this blog for solutions

**Comment by Robotatron** [comment]
On Windows this worked for me:

`conda install -c esri pycocotools`

**Comment by mvsg2** [comment]
> Thank you very much for your help..while I updata MicroSoft Visual C++ version，this error is solved perfectly.If someone else has the same problem, please read this blog for solutions

Hey, I installed Microsoft Visual Studio with C++ Buildtools, etc in the latest version, but it still keeps showing me that I need a C++ version greater than 14.0. How do I solve this issue? 
Thanks

**Comment by Linkcy97** [comment]
> On Windows this worked for me:
> 
> `conda install -c esri pycocotools`

It is works for me

**Comment by TheMegistone4Ever** [comment]
> On Windows this worked for me:
> 
> `conda install -c esri pycocotools`

Thanks a lot, only it's working for me, I've tried a many different options before I saw it...
