### ISSUE TITLE
distributed training

### ISSUE THREAD

**Issue by isJunCheng** [open-mmlab/mmdetection#7354]
When I use the parameters of -- GPUs 2 -- launcher pytorch for training, an error is reported.
![image](https://user-images.githubusercontent.com/44466856/157430008-899c4393-7580-4e79-b0b7-1b6605db284d.png)
I found that the ‘RANK’ parameter is not set in the code. How can I get the support of distributed training？please

**Comment by isJunCheng** [comment]
> 你会提供你运行的命令吗？

sure,I execute the train.py file in the tools directory, and set the config default parameter to 'retinanet_r50_fpn_1x_coco.py'.
![image](https://user-images.githubusercontent.com/44466856/157565896-b03d749c-f048-4dae-9485-bc8fdae38c16.png)

**Comment by jbwang1997** [comment]
We provide a dist_train.sh in tools to set up a distributed training task. You can try this script.

**Comment by isJunCheng** [comment]
> 

thank you for your reply. i found, executing dist_train.sh file can indeed use distributed training, but using the commands in it to directly execute Python compilation will report an error.
![image](https://user-images.githubusercontent.com/44466856/157579722-7e227ce9-0556-4a2d-99ac-b55a11dbd8e0.png)

can't we directly conduct distribute training through train.py?Also, can we use a custom GPU number?

**Comment by isJunCheng** [comment]
> We provide a dist_train.sh in tools to set up a distributed training task. You can try this script.

the command is shown in the fig.
![image](https://user-images.githubusercontent.com/44466856/157580425-31cb794c-28f8-4301-a002-565e7fea56ed.png)

**Comment by jbwang1997** [comment]
Seems you haven't set PYTHONPATH in your command. And you can set custom GPU number according to [GPUS] in dist_train.sh.

**Comment by isJunCheng** [comment]
> Seems you haven't set PYTHONPATH in your command. And you can set custom GPU number according to [GPUS] in dist_train.sh.

ok, thank you for your reply. it's hoped that the distribute training can be directly recommended on the train.py file in the future. hh
thank you
