### ISSUE TITLE
Need advice: Extract Local Attention Positions

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmdetection#7355]
I am working on a project, I want to extract the local attention positions present in the feature maps of every level in the FPN. Below is the visualization:
![Screenshot 2022-03-09 143246](https://user-images.githubusercontent.com/62779617/157432707-ff88ac8b-56f3-4516-8de5-c9fd768a01b0.jpg)

For example, a level in the FPN outputs the feature map that can be visualized below:
![Screenshot 2022-03-09 143703](https://user-images.githubusercontent.com/62779617/157432772-8168a40b-5360-4bed-a550-1470231c6113.jpg)

I want am to know how to locate those weights and how to extract their location with respect to the (H x W x 256) tensor size output of FPN.

**Comment by isJunCheng** [comment]
there are many visualization methods, such as grad-cam.......

**Comment by chandlerbing65nm** [comment]
> there are many visualization methods, such as grad-cam.......

I mean, how to get the locations of the blobs of attention in the feature map

**Comment by chandlerbing65nm** [comment]
> > there are many visualization methods, such as grad-cam.......
> 
> I mean, how to get the locations of the blobs of attention in the feature map. In theoretical explaination.

**Comment by jbwang1997** [comment]
I understand you want to extract the high attention region of the feature map. In this case, you can first localize this region by calculating the coordinates of pixels with high attention. Then you can use `roi align` to extract the region features.

**Comment by chandlerbing65nm** [comment]
> I understand you want to extract the high attention region of the feature map. In this case, you can first localize this region by calculating the coordinates of pixels with high attention. Then you can use `roi align` to extract the region features.

@jbwang1997 I was thinking to combine the 256-channels into 1-channel, then use torch.where() to calculate the x-y locations of high attention values.

**Comment by jbwang1997** [comment]
Yes, it's feasible.
