### ISSUE TITLE
Copying standard pretrained weights of first layer from ResNet50 to a 5 channel 

### ISSUE THREAD

**Issue by Jaisme** [open-mmlab/mmdetection#7357]
I want to replace the first convolutional layer in backbone resnet50 with a new layer with 5 input channels due to 5 channel images. What i want to do is to transfer the first layer pretrained weights to a 5-channel input by copying RGB weights and the rest 2 channels weights by copying R channel weight. 

I know it is possible for torchvision model by doing somthing like this:

```
model = models.resnet50(pretrained=True)
weight = model.conv1.weight.clone()
model.conv1 = nn.Conv2d(5, 64, kernel_size=7, stride=2, padding=3, bias=False)
with torch.no_grad():
    model.conv1.weight[:, :3] = weight
    model.conv1.weight[:, 3] = model.conv1.weight[:, 0]
    model.conv1.weight[:, 4] = model.conv1.weight[:, 0]
    
x = torch.randn(10, 5, 224, 224)
output = model(x)
```

Is this reimplementation also possible with mmdetection? If so, how can i solve it? Any help would be really appreciated!

**Comment by jbwang1997** [comment]
I recommend you code the initialization logic in the `init_weights` function. For example, you can create `init_weights` function in ResNet and write the above codes in it. To avoid potential bugs, [This document](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/init_cfg.md) may help you.

**Comment by Jaisme** [comment]
Thank you for this nice suggestion! Do you mean that i can instead import` from mmcv.runner import BaseModule `directly inherit mmdet ResNet model? I'll try it!

**Comment by jbwang1997** [comment]
Hello. I am going to close this issue. Feel free to reopen it if you have any questions.
