### ISSUE TITLE
Can I conduct error analysis for each individual sample?

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection#7359]
Are there any documents about error analysis?

**Comment by RangiLyu** [comment]
Try to use tools/analysis_tools/analyze_results.py. And the tutorial is in https://mmdetection.readthedocs.io/en/latest/useful_tools.html#result-analysis

**Comment by CheungBH** [comment]
> Try to use tools/analysis_tools/analyze_results.py. And the tutorial is in https://mmdetection.readthedocs.io/en/latest/useful_tools.html#result-analysis

Thank you. I tried to use it, but I didn't find a file containing the mAP for a single image. I can only find the folder containing the top-k good and bad image. 
Are there anything I should assign?

**Comment by CheungBH** [comment]
I think the parameters here means the mAP of each sample. 
https://github.com/open-mmlab/mmdetection/blob/70f6d9cfade4a2f0b198e4f64776521d181b28be/tools/analysis_tools/analyze_results.py#L134
I wonder what's the sequence of this parameter? It is a dictionary, but its keys are the index number(0,1,2,3,...) instead of image index, and I cannot find their corresponding relationships
