### ISSUE TITLE
Difference between coco and VOC?

### ISSUE THREAD

**Issue by PumayHui** [open-mmlab/mmdetection#736]
I have made my dataset to VOC format and coco format.
The details is:
classes: 5, train num: 515762, batch_size: 4
But when I ran this command:
`python tools/train.py ./configs/faster_rcnn_r101_fpn_1x_coco.py`
It shows
![image](https://user-images.githubusercontent.com/28421690/58550458-578eb980-8240-11e9-95cb-a79598e18ff6.png)

`python tools/train.py ./configs/faster_rcnn_r101_fpn_1x_voc.py`
It shows 
![image](https://user-images.githubusercontent.com/28421690/58550477-62494e80-8240-11e9-85d7-72a36cf9769e.png)

Why the num of coco is "92427" and the num of VOC is "128941"?
Can anybody help me?
Thanks so much!

**Comment by PumayHui** [comment]
I guess maybe coco dataset will filter non-object images. The reason is as follows:
In my config,
gpus_num = 1,
imgs_per_gpu = 4,
total_training_num = 515762.
So,
batch_size = gpus_num x imgs_per_gpu = 4
batch_num = total_training_num / batch_size = 515762/4 = 128940.5 (approximate 128941).
This "129841" euqals to VOC batch_num in above screenshot. 
So I think the reason of COCO batch_num 92427 is COCO delete  the non-object images, which causes the numbers of images decrease.

**Comment by hellock** [comment]
Thanks for figuring out it and this should be the difference. Ideally XML style dataset should also filter out images without annotations, but all images of VOC has gt bboxes so we just ignored the step.
Feel free to create a PR to fix that if you would like to.
