### ISSUE TITLE
Failed to download the FPG model

### ISSUE THREAD

**Issue by namelzya** [open-mmlab/mmdetection#7362]
<Error>
           <Code>NoSuchKey</Code>
           <Message>The specified key does not exist.</Message>
           <RequestId>6229711BC25A1C98AB14C89B</RequestId>
           <HostId>download.openmmlab.com</HostId>
           <Key>mmdetection/v2.0/fpg/faster_rcnn_r50_fpg_crop640_50e_coco/faster_rcnn_r50_fpg_crop640_50e_coco-76220505.pth</Key>
</Error>

Can you help me？

**Comment by namelzya** [comment]
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>62297633A33E78AA3133E298</RequestId>
<HostId>download.openmmlab.com</HostId>
<Key>
mmdetection/v2.0/fpg/faster_rcnn_r50_fpg_crop640_50e_coco/faster_rcnn_r50_fpg_crop640_50e_coco-76220505.pth
</Key>
</Error>

**Comment by BIGWangYuDong** [comment]
Hi, seems the download link is invaild. We'll fix this soon.

**Comment by namelzya** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
