### ISSUE TITLE
How to eliminate the small target detection result in the Faster-RCNN detection

### ISSUE THREAD

**Issue by southeastboss** [open-mmlab/mmdetection#7363]
I used the faster_rcnn_x101_32x4d_fpn_2x model to detection, but there have some small targets in my picture. I want to eliminate the small target detection result. Like 30 * 40 targets, but I need to detect the 20 * 100 targets. How can I eliminate the 30 * 40 targets and hold the 20 * 100 targets.

**Comment by BIGWangYuDong** [comment]
Seems the code cannot support your requirement. Maybe you can try to change some code here:
https://github.com/open-mmlab/mmdetection/blob/70f6d9cfade4a2f0b198e4f64776521d181b28be/mmdet/datasets/coco.py#L167-L174

**Comment by southeastboss** [comment]
oh, I mean in test not in train.

**Comment by southeastboss** [comment]
oh, I mean in test not in train.

**Comment by BIGWangYuDong** [comment]
Similar to the above answer, you can add a filter function in your code

**Comment by southeastboss** [comment]
Ok，I get the idea.  Thanks for your reply.
