### ISSUE TITLE
For the detection of general quadrilateral objects, can we directly detect the four vertices of the object? Is there any relevant code link?

### ISSUE THREAD

**Issue by daigang896** [open-mmlab/mmdetection#7365]
Hello.
For the detection of general quadrilateral objects, can we directly detect the four vertices of the object? Is there any relevant code link?

**Comment by RangiLyu** [comment]
MMDetection currently only supports rectangle detection. For general quadrilateral objects detection, you can refer to some text detection methods in MMOCR https://github.com/open-mmlab/mmocr/tree/main/configs/textdet. Some methods can detect beyond rectangles.
