### ISSUE TITLE
running training on terminal is very slow, what's going on??

### ISSUE THREAD

**Issue by alleniver** [open-mmlab/mmdetection#7366]
Hello,when I use the terminal to train, it takes more than 10 minutes for the prompt information (such as configuration information and training-related information) to appear, but if I use the juypter notepad, the information can be displayed very quickly; using other frameworks does not have this problem .

check my attached picture, the result will appear in 3.5 seconds for figure1, and it will take 10 minutes for figure2 to appear.
figure1:
![image](https://user-images.githubusercontent.com/6006650/157616110-eb40c7d1-e6f3-40d4-b5e2-a8da5989da6b.png)

figure2:
![image](https://user-images.githubusercontent.com/6006650/157619715-e372e358-1371-47a8-bc8a-526bcf6a16c2.png)

figure3(slow):
![image](https://user-images.githubusercontent.com/6006650/157620528-c3c248cf-09ef-4141-a6ca-b8f58b18a61c.png)

figure4:(fast):
![image](https://user-images.githubusercontent.com/6006650/157621201-183fb1aa-6694-410f-b5a9-54f1f7519518.png)

Here is my environment info:
sys.platform: windows 11 with wsl2:ubuntu 20.04
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3080 Ti
CUDA_HOME: /usr/local/cuda-11
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
PyTorch: 1.9.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1+cu111
OpenCV: 4.5.5
MMCV: 1.4.6
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.22.0+f5bdc9a

this issue happened in 2.21.0 and 2.22.0, I reinstalled the environment many times, including pytorch 1.8.2 + python 3.7 and pytorch 1.9.1 + python 3.7.

my dev system is windows 11(21H2 22000.556),wsl2 with ubuntu 20.04

**Comment by RangiLyu** [comment]
One possible reason may be the notebook already loaded the python environment but when you are using the terminal, all things should start from scratch.

**Comment by alleniver** [comment]
> One possible reason may be the notebook already loaded the python environment but when you are using the terminal, all things should start from scratch.

maybe not for this reason. because I restarted all terminals and notepad, the execution of the command is still the same,
execute the comand:wsl --shutdown,and reboot the win system,the same problem!

**Comment by alleniver** [comment]
i have used mmselfsup and don't have this problem.

**Comment by RangiLyu** [comment]
> i have used mmselfsup and don't have this problem.

That's weird. I tried to run the same command in the terminal and it started very fast. Maybe because of the wsl? I'm not sure.

**Comment by alleniver** [comment]
> > i have used mmselfsup and don't have this problem.
> 
> That's weird. I tried to run the same command in the terminal and it started very fast. Maybe because of the wsl? I'm not sure.

oh,I'll take look for myself.thx.
