### ISSUE TITLE
calculate the Flops after training a model. 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#7369]
Hello all , 

I am trying to use this isntruction to find out the FLOPS for different types of Object detection models. 
`python tools/analysis_tools/get_flops.py configs/human/fsaf_r101_fpn_1x_coco.py`
all of them express this note: 

`!!!Please be cautious if you use the results in papers. You may need to check if all ops are supported and verify that the flops computation is correct.`

I don't know how to be sure about the values , which are the input shape , FLOPS and the parameters .

even more, while using same instruction on those models (FCOS,FSAF, cascade  RCNN, Cascade mask RCNN  ), there was an error and no results was expressed.  could you please help me. 

the following error is presented: 
`AssertionError: CascadeRCNN: ResNet: init_cfg and pretrained cannot be specified at the same time`

**Comment by RangiLyu** [comment]
> I don't know how to be sure about the values , which are the input shape , FLOPS and the parameters .
You can look the messages printed by this script and make sure all modules in the model have the correct Params and FLOPs.

> the following error is presented:
> AssertionError: CascadeRCNN: ResNet: init_cfg and pretrained cannot be specified at the same time

as the error message said, `init_cfg` and `pretrained` should not be set at the same time. Make sure your config and get_flops script do not set these two params at the same time.

**Comment by alaa-shubbak** [comment]
Thanks for replay, Unfortunately i did not get well what did you mean by pretrained and init_cfg. 

I try the command again, and remove the instruction from the config file: 
`load_from='checkpoints/fcos_x101_64x4d_fpn_gn-head_mstrain_640-800_2x_coco-ede514a8.pth'`

but it is also not working. I see that there is another pretrained part, which is related to the backbone . I am not sure if i should remove it , even though , it was mentioned in the config files with other models that have been worked correctly with me. 

any other clue or idea? please

**Comment by alaa-shubbak** [comment]
here is the another type of  error which presented with another model,such as FCOS
TypeError: FCOS: FPN: __init__() got an unexpected keyword argument 'extra_convs_on_inputs'

**Comment by alaa-shubbak** [comment]
thanks , it seems that i got the point. 
this instruction ,which calculate the parameters number, and the FLOPS is only working on the basic backbone of the model. 
for example in FSAF model , it used the ResNet50 as basic backbone, the instruction will work with it , but  if we integrate the ResNext 101 or ResNet 101 it dose not work. am i right on that?

 in such case how i can make it work with the whole new model? i suppose that using another backbone , like ResNext should increase the number of parameters and the FLOPS; is that correct? 

for the another error which is
` TypeError: FCOS: FPN: __init__() got an unexpected keyword argument 'extra_convs_on_inputs'`
I am still investigating , I don't  know it yet.

**Comment by RangiLyu** [comment]
> thanks , it seems that i got the point. this instruction ,which calculate the parameters number, and the FLOPS is only working on the basic backbone of the model. for example in FSAF model , it used the ResNet50 as basic backbone, the instruction will work with it , but if we integrate the ResNext 101 or ResNet 101 it dose not work. am i right on that?

No, the error message shows that your config file is incorrect. Can you upload your config and the command you run?

**Comment by alaa-shubbak** [comment]
i run FCOS model, 
![fcos model1](https://user-images.githubusercontent.com/10245810/158079367-ef703397-9840-4e97-b20e-01deb7b26f4c.jpg)
![fcos model2](https://user-images.githubusercontent.com/10245810/158079404-6a750996-4005-4db3-b0bc-a2c475fb1b67.jpg)

and this > model = dict(bbox_head=dict(center_sampling=True, center_sample_radius=1.5))
I run this code, it is working.

**Comment by alaa-shubbak** [comment]
i run this instruction in cluster system using the flowing (.sh) file. 

![config oh flop](https://user-images.githubusercontent.com/10245810/158079729-c65698bb-2f8e-424b-b32e-a34fc89a40e2.jpg)

`python tools/analysis_tools/get_flops.py configs/human/fcos_center_r50_caffe_fpn_gn-head_1x_coco.py`

**Comment by hhaAndroid** [comment]
> thanks , it seems that i got the point. this instruction ,which calculate the parameters number, and the FLOPS is only working on the basic backbone of the model. for example in FSAF model , it used the ResNet50 as basic backbone, the instruction will work with it , but if we integrate the ResNext 101 or ResNet 101 it dose not work. am i right on that?
> 
> in such case how i can make it work with the whole new model? i suppose that using another backbone , like ResNext should increase the number of parameters and the FLOPS; is that correct?
> 
> for the another error which is ` TypeError: FCOS: FPN: __init__() got an unexpected keyword argument 'extra_convs_on_inputs'` I am still investigating , I don't know it yet.

@alaa-shubbak I'm guessing the reason is that the code and config don't match, your config file is an old version, but the code is new. The solution is to update the configuration and code at the same time. You can fer to [this PR](https://github.com/open-mmlab/mmdetection/pull/5311)
