### ISSUE TITLE
What does 'evaluation' and 'workflow' do in cfg?

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#7370]
By default, we have `evaluation = dict(interval=1, metric='bbox')` and `workflow = [('train', 1)]` in cfg. I am a little confused about these. By setting evaluation.interval=N, mAP or other metrics are calculated after every N training epochs. It seems that 'workflow' is doing the same thing, according to [https://zhuanlan.zhihu.com/p/341954021](url). Maybe I am not understanding 'evaluation' and 'val' correctly. As far as I am concerned now, they are basically the same, indicating the calculation of metrics on validate set. I might need some help here. Thank you!

**Comment by BIGWangYuDong** [comment]
`evaluation` is using `EvalHook` or `DistEvalHook` to calculate the result. However, `workflow` is going to use `val_step` to process some code.
Here is the code that processes `workflow` in mmcv:
https://github.com/open-mmlab/mmcv/blob/c4b02566cfeb42185041c34ec36f09ad7a5b8589/mmcv/runner/epoch_based_runner.py#L110-L118
For more details, you may need to have a look at mmcv/runner/epoch_based_runner.py

**Comment by DrX2020** [comment]
Thank you!
