### ISSUE TITLE
Setting up mmdetection on a cpu only device

### ISSUE THREAD

**Issue by SourabhRanade** [open-mmlab/mmdetection#7375]
The documentation at [CPU setup](https://mmdetection.readthedocs.io/en/v2.2.0/install.html#install-with-cpu-only) says that the setup can be made on CPU with no CUDA. However, it does not describe any steps. Can someone guide me as to how can I set the same up on a CPU machine? My aim is to set it up on a Raspberry pi 4 and run some inferences on it. Is it possible to do so? 

Also are all the mmdetection pretrained models trained on Imagenet? Is there somewhere I can find this information?

**Comment by BIGWangYuDong** [comment]
>The documentation at [CPU setup](https://mmdetection.readthedocs.io/en/v2.2.0/install.html#install-with-cpu-only) says that the setup can be made on CPU with no CUDA. However, it does not describe any steps. Can someone guide me as to how can I set the same up on a CPU machine?

To install on CPU, you can install pytorch-cpu first. Then, install mmcv or mmcv-full on cpu, which can follow [mmcv](https://github.com/open-mmlab/mmcv). Then you can install the mmdet. [Here](https://mmdetection.readthedocs.io/en/v2.21.0/get_started.html#install-without-gpu-support) is the latest version of the document.

> My aim is to set it up on a Raspberry pi 4 and run some inferences on it. Is it possible to do so?
Haven't tried this before. you can have a try.

> Also are all the mmdetection pretrained models trained on Imagenet? Is there somewhere I can find this information?

https://mmdetection.readthedocs.io/en/v2.21.0/model_zoo.html#imagenet-pretrained-models

**Comment by EasonQYS** [comment]
run on cpu need mmcv>=1.4.5 and mmdet>=2.21.0, you can try this version.
I use this :
```
pip install torch==1.8.1 torchvision==0.9.1 
pip install opencv-python
pip install mmcv-full==1.4.5 -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.8.0/index.html
pip install mmdet==2.22.0
```

I am interested at running it on Raspberry pi 4, if anyone succeed, I would like to learn from the experience.

**Comment by SourabhRanade** [comment]
@BIGWangYuDong Thank you. I will give it a try. 
@EasonQYS I am trying the same. In case I succeed I will share my steps here. Please do the same if you manage to run it on rasberry pi 4  :)

**Comment by SourabhRanade** [comment]
@BIGWangYuDong  , I followed the steps that @EasonQYS mentioned  above and just built the mmdetection from source instead of  `pip install mmdet==2.22.0`. 
The installation seems to go through properly and does not throw any errors. 

However, as I am trying to wrok with SWIN-T transformer I download and run checkpoints file.
The below model intialization code fails with the error message : `AssertionError : Torch not compiled with CUDA enabled`

```
config='/content/mmdetection/configs/swin/mask_rcnn_swin-t-p4-w7_fpn_1x_coco.py'
checkpoint = 'checkpoints/mask_rcnn_swin-t-p4-w7_fpn_1x_coco_20210902_120937-9d6b7cfa.pth'
model = init_detector(config,checkpoint)
```

Is there a way to circumvent this problem or maybe any other way?

**Comment by BIGWangYuDong** [comment]
You need to specify the device as the CPU, and some algorithms do not support cpu inference, you can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md#install-without-gpu-support

**Comment by EasonQYS** [comment]
```
model = init_detector(config,checkpoint)
```
this line should be change to 
```
model = init_detector(config,checkpoint, device='cpu')
```

**Comment by SourabhRanade** [comment]
@EasonQYS  @BIGWangYuDong  Thank you for your answer ! With the steps that I mentioned above and the the change that you suggested the models can be loaded and worked on a rasberry pi 4. Hence I am closing the issue now.

**Comment by SourabhRanade** [comment]
@BIGWangYuDong  could you please confirm if the SWIN-T transformer model has been trianed on the Imagenet dataset. On the link you mentioned above, I just see a general statement that `generally all the backbones are trained on the Imagenet` . I just wanted to confirm the same.

**Comment by parthplc** [comment]
> run on cpu need mmcv>=1.4.5 and mmdet>=2.21.0, you can try this version. I use this :
> 
> ```
> pip install torch==1.8.1 torchvision==0.9.1 
> pip install opencv-python
> pip install mmcv-full==1.4.5 -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.8.0/index.html
> pip install mmdet==2.22.0
> ```
> 
> I am interested at running it on Raspberry pi 4, if anyone succeed, I would like to learn from the experience.

I had to change the third command to 
```
pip3 install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.8.0/index.html
```
for it to work for me.

**Comment by meysamsadeghi** [comment]
I did as suggested by @EasonQYS but with a newer version and have the following error. any suggestion?

` pip install mmcv-full==1.5.2 -f https://download.openmmlab.com/mmcv/dist/cpu/torch1.11.0/index.html`

`Could not fetch URL https://download.openmmlab.com/mmcv/dist/cpu/torch1.11.0/index.html: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='download.openmmlab.com', port=443): Max retries exceeded with url: /mmcv/dist/cpu/torch1.11.0/index.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))) - skipping`

**Comment by meysamsadeghi** [comment]
Used the same command in ubuntu and it worked out.
