### ISSUE TITLE
How to use 3D-dcn in ConvModule?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#7378]
Hi, dear authors!
Thank you for your amazing job!
Could you tell me how to use 3D-dcn in ConvModule?
Thank you!

**Comment by chhluo** [comment]
3D-dcn is not supported in mmcv yet. And by the way, why do you need to use 3D-dcn?

**Comment by zhongqiu1245** [comment]
@chhluo Thank you for your reply.
'cause I'm trying to use mmdet in medical images(CT & MRI).

**Comment by chhluo** [comment]
There are lots of work to apply mmdet to 3D images, because mmdet is design for 2D images.

**Comment by zhongqiu1245** [comment]
@chhluo Could you please give some examples? (URL or paper)

**Comment by chhluo** [comment]
All data processing in mmdet are designed for 2D images, and all models in mmdet are designed for 2D images. Applying mmdet to 3D images detectly is impossible. Object detection on 2D medical image by mmdet is reasonable.
For example, you can do object detection on every slice of a 3D MRI, and summary results to 3D bboxes at last.

**Comment by zhongqiu1245** [comment]
Thank you!

**Comment by WangLibo1995** [comment]
> Thank you!

I test the DCNv2, a error raised:
![image](https://user-images.githubusercontent.com/38718224/158126984-cdc44c5d-b165-4fa3-836c-6993e155c8a6.png)
Any error in my code? How to correct it?

**Comment by WangLibo1995** [comment]
> 3D-dcn is not supported in mmcv and torchvision yet. And by the way, why do you need to use 3D-dcn?

I test the DCNv2, a error raised:
![image](https://user-images.githubusercontent.com/38718224/158126984-cdc44c5d-b165-4fa3-836c-6993e155c8a6.png)
Any error in my code? How to correct it?
