### ISSUE TITLE
Are ''max_epochs'' and ''step'' written wrong in ''mmdetection/configs/common/mstrain_3x_coco.py'' and ''mmdetection/configs/retinanet/retinanet_r101_fpn_mstrain_640-800_3x_coco.py''?

### ISSUE THREAD

**Issue by STAR-ALG** [open-mmlab/mmdetection#7379]
Thanks for your error report and we appreciate it a lot.

**Checklist**
The bug has not been fixed in the latest version.

**Describe the bug**
In 'mmdetection/configs/common/mstrain_3x_coco.py'', there should be ''step=[28, 34]'' and ''max_epoches=36'' in Line 75 and 76, instead of ''step=[9, 11]'' and ''max_epoches=12''. When I use the config ''mmdetection/configs/retinanet/retinanet_r101_fpn_mstrain_640-800_3x_coco.py'', it is plausibly running with only 12 epoches now?

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/70f6d9cfade4a2f0b198e4f64776521d181b28be/configs/common/mstrain_3x_coco.py#L45-L47
because it used a repeat dataset wrapper.

**Comment by STAR-ALG** [comment]
Thank you for your answer! I still have a question: if the dataset is repeated three times, then "step=[9, 11]" is equivalent to "step=[27, 33]", instead of "step=[28, 34]". Will this result in decreased accuracy?

**Comment by BIGWangYuDong** [comment]
I don't think there will be much difference

**Comment by hhaAndroid** [comment]
@STAR-ALG `step=[27, 33]` is the optimized value in the coco dataset, if it is replaced by `[28, 34]`, the accuracy may decrease.
