### ISSUE TITLE
htc model download failed with 403 error 

### ISSUE THREAD

**Issue by wptoux** [open-mmlab/mmdetection#7383]
**Describe the bug**
I can not download the htc model checkpoint

https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmdetection/v2.0/htc/htc_x101_64x4d_fpn_dconv_c3-c5_mstrain_400_1400_16x1_20e_coco/htc_x101_64x4d_fpn_dconv_c3-c5_mstrain_400_1400_16x1_20e_coco_20200312-946fd751.pth

HTTP result is the following.
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>YMYMWQDNNXBGPA8S</RequestId>
<HostId>JgX0VVhe3NvdnUda6q5g47gs3hqoWAIttLEUQTP9aQbWpvUPJMPsXUdzX8ADYyQhIZxKq2oW/gk=</HostId>
</Error>
```

**Comment by ZwwWayne** [comment]
AWS s3 has been deprecated. Please use https://download.openmmlab.com/mmdetection/v2.0/htc/htc_x101_64x4d_fpn_dconv_c3-c5_mstrain_400_1400_16x1_20e_coco/htc_x101_64x4d_fpn_dconv_c3-c5_mstrain_400_1400_16x1_20e_coco_20200312-946fd751.pth
