### ISSUE TITLE
关于数据增强

### ISSUE THREAD

**Issue by FL77N** [open-mmlab/mmdetection#7384]
你好，请问 mmdet 支持旋转数据增强吗？另外，我可以在什么地方查看 mmdet 支持的所有数据增强方式呢？（Hello, does mmdet support rotation data augmentation? In addition, where can I view all the data augmentation supported by mmdet?）

**Comment by ZwwWayne** [comment]
Please refer to [MMRotate](https://github.com/open-mmlab/mmrotate). You can see all the data augmentation in mmdet.datasets.pipelines or mmrotate.datasets.pipelines

**Comment by EasonQYS** [comment]
You can change the title with English by click the edit at the top-right of this page. And using fanyi.baidu.com to help.

**Comment by FL77N** [comment]
> Please refer to [MMRotate](https://github.com/open-mmlab/mmrotate). You can see all the data augmentation in mmdet.datasets.pipelines or mmrotate.datasets.pipelines

Thank for your detail answer！
