### ISSUE TITLE
Why the AP of FCOS is lower than in the paper?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#7385]
I notice that the FCOS's (resnet-50-fpn-1x) AP (which is 36.6) is lower than the paper (37.1 AP). Why?
![image](https://user-images.githubusercontent.com/26771037/158095064-0c3cc5d0-bc19-461b-b8b5-a8f4c9c4e376.png)
![image](https://user-images.githubusercontent.com/26771037/158095227-6b34df4c-3e21-4765-aca9-86c4820f9102.png)
The second picture is come from original code(https://github.com/tianzhi0549/FCOS).

**Comment by Czm369** [comment]
Maybe you can refer to https://github.com/tianzhi0549/FCOS/issues/102

**Comment by Icecream-blue-sky** [comment]
> Maybe you can refer to [tianzhi0549/FCOS#102](https://github.com/tianzhi0549/FCOS/issues/102)

Thanks!
