### ISSUE TITLE
How to use a trained model for validation to get metrics such as mAP

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#7390]
I only saw methods to get the predictions but not to get the metrics after the training is done.
Is there a way to do that?

**Comment by Czm369** [comment]
May you can refer to 
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/1_exist_data_model.md

**Comment by sarmientoj24** [comment]
saw it. but how do you visualize the ground truth from validation?
