### ISSUE TITLE
Custom dataset wrapper

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#7392]
Hi, I'm making a custom dataset wrapper that works similar to `MultiImageMixDataset` but mixing across datasets. After some digging, it seems like the few default dataset wrappers are all "hard-coded" in `mmdet.datasets.builder.build_dataset`. Is the recommended way to include my custom dataset wrapper to write my own `build_dataset`? Thank you!

**Comment by Czm369** [comment]
Maybe you can rewrite `build_dataset`, at least the basic dataset api as same as  CocoDataset

**Comment by levan92** [comment]
alright, thank you
