### ISSUE TITLE
Custom classes in LVIS

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#7393]
Hi, can I confirm that setting the `classes` argument has no effect on the `LVISV05Dataset` and `LVISV1Dataset`? Meaning, it does not filter the images & anns to the classes given in the argument, unlike what happens in `CocoDataset`?

**Comment by Czm369** [comment]
Maybe you can read the code `mmdet/datasets/lvis.py`

**Comment by levan92** [comment]
Yup, that's what I gathered after looking through the code, just wanted to confirm my understanding. Maybe this can be better documented, so that people using the default LVIS dataset class will not expect the `classes` argument to work similar to `CocoDataset`
