### ISSUE TITLE
Mistakes in the merged LD code？

### ISSUE THREAD

**Issue by huangh12** [open-mmlab/mmdetection#7394]
Hello @HikariTJU , it seems like the KD loss is missing in the ld_head.py of mmdetection, however it exists in your official LD code.

mmdetection：
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/ld_head.py#L122

official LD repo:
https://github.com/HikariTJU/LD/blob/main/mmdet/models/dense_heads/ld_head.py#L240

So,  is there any mistakes in the mmdetection implemention？

**Comment by Czm369** [comment]
The implemention is from the author, referring to
https://github.com/open-mmlab/mmdetection/pull/4758
and you can ask the author for more details.

**Comment by HikariTJU** [comment]
No mistakes, just too lazy to merge the latest code.
