### ISSUE TITLE
Which one does val dataset follow? 'train_cfg' or 'test_cfg'?

### ISSUE THREAD

**Issue by DrX2020** [open-mmlab/mmdetection#7396]
In cfg of model, we have dicts train_cfg and test_cfg. By default, after every epoch the val dateset should be used once to do the validation, i.e., to calculate metrics on val data and print. I am wondering whether validation follows train_cfg or test_cfg. For example, if I use nms in train_cfg and use soft-nms in test_cfg, validation is calculated using nms or soft-nms? I have not found the related codes yet.

**Comment by hhaAndroid** [comment]
@DrX2020  validation follows ` test_cfg`

**Comment by DrX2020** [comment]
Thank you!
