### ISSUE TITLE
请问测试速度时，不打印FPS？

### ISSUE THREAD

**Issue by MrWcy** [open-mmlab/mmdetection#7400]
![image](https://user-images.githubusercontent.com/30768980/158336263-279103c7-c3ba-4b43-9112-03263f77ab8b.png)
如图所示，加载checkpoint 后没有后续结果，配置文件和模型文件路径均没有错误（以前好像还可以，这次不行了）
`!cd mmdetection&& python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 \
  tools/analysis_tools/benchmark.py \
  configs/1mask/atss_r101_fpn.py  \
  ../best_bbox_mAP_50_epoch_24.pth \
  --launcher pytorch `

**Comment by hhaAndroid** [comment]
@MrWcy The program doesn't seem to finish. Please confirm again.
