### ISSUE TITLE
The font tag does not render properly on pypi.org

### ISSUE THREAD

**Issue by osbm** [open-mmlab/mmdetection#7408]
The font tag in README.md file on [pypi](https://pypi.org/project/mmdet/) doesn't render right.
![image](https://user-images.githubusercontent.com/74963545/158362720-37070d68-4ef1-4f8b-8609-f271beb0a603.png)

**Comment by hhaAndroid** [comment]
@osbm Thank you for your feedback. I will to check it.

**Comment by osbm** [comment]
This looks ok now. im closing this issue. Stay safe everyone
