### ISSUE TITLE
how to get the training speed and compare with maskrcnn-benchmark

### ISSUE THREAD

**Issue by guanfuchen** [open-mmlab/mmdetection#741]
![image](https://user-images.githubusercontent.com/22321977/58696945-373f3600-83cb-11e9-9731-525160d552a0.png)

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md#comparison-with-detectron-and-maskrcnn-benchmark

**Comment by guanfuchen** [comment]
Thanks for your reply, I want to test how the model performs when gpu grows in single machine, so I simply use the code python mmdetection/tools/train.py mmdetection/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py --gpus=X, X is valued in [1, 2, 4, 8], get time from log like 
```
XXX - INFO - Epoch [4][24450/24827]	lr: 0.00100, eta: 0:01:14, time: 0.200, data_time: 0.004, memory: 2238, loss_rpn_cls: 0.0050, loss_rpn_reg: 0.0060, loss_cls: 0.0587, acc: 97.7441, loss_reg: 0.0473, loss: 0.1169
```
then use 50/time(0.2)=250fps(X=1), 650fps(X=8) the speed up rate is low depending the gpu num. Am I wrong with the calculation?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#train-with-multiple-gpus

**Comment by feixiangdekaka** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#train-with-multiple-gpus

How to get 24827 on pascal voc! the number of trainval0712  is 16651.
