### ISSUE TITLE
model link of open image is invalid in https://github.com/open-mmlab/mmdetection/blob/master/configs/openimages/README.md

### ISSUE THREAD

**Issue by biubug6** [open-mmlab/mmdetection#7412]
model link of open image is invalid in [https://github.com/open-mmlab/mmdetection/blob/master/configs/openimages/README.md](url)

**Comment by hhaAndroid** [comment]
@biubug6  Thanks for your feedback

**Comment by BIGWangYuDong** [comment]
Will fix ASAP

**Comment by BIGWangYuDong** [comment]
Have already re-upload open images ckpt.
