### ISSUE TITLE
NotImplementedError: `forward_dummy` is not implemented in SOLO

### ISSUE THREAD

**Issue by solauky** [open-mmlab/mmdetection#7414]
I made an error trying to test SOLO's Flops. How should I debug? thank you

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/6b87ac22b8d9dea8cc28b9ce84909e6c311e6268/mmdet/models/detectors/single_stage_instance_seg.py#L63-L69
We are not Implemented now. 

You can follow

https://github.com/open-mmlab/mmdetection/blob/6b87ac22b8d9dea8cc28b9ce84909e6c311e6268/mmdet/models/detectors/single_stage.py#L48-L55

to have a try.

**Comment by solauky** [comment]
来信收到，谢谢！

**Comment by solauky** [comment]
thank you ~
