### ISSUE TITLE
How to define a new plugin for my backbone?

### ISSUE THREAD

**Issue by ludabai** [open-mmlab/mmdetection#7419]
I have noticed that a plugin such as 'GeneralizedAttention' can be added into a backbone, similarly I want to add some different plugins into my backbone. 
I want to know some detailed information about plugins, such as where plugins can be used and how to define them. 
I have failed to find related guidedlines in user docs thus I hope for some help.

**Comment by jbwang1997** [comment]
You can register your custom plugin in `PLUGIN_LAYERS` at mmcv https://github.com/open-mmlab/mmcv/blob/e319369068c8fe813086ecddf1070ac510860592/mmcv/cnn/bricks/registry.py#L9. Then, you can call your plugin by config.

The logic of building and applying plugins can be referred to https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/backbones/resnet.py#L97.

**Comment by alaa-shubbak** [comment]
thank you very much. 
If i got it will , for adding some new layers such as CBAM layer , I shall registry it in `PLUGIN_LAYERS`, then write my code inside the backbone Resnet , am i right?

to do so i shall add the info of layer in this part of ResNet code. 
![plugin1](https://user-images.githubusercontent.com/10245810/169350065-fe2f694f-c8a7-4c4e-ab27-945e632c6063.jpg)

is that correct? or i am doing something wrong? 

as i am still little bit confused , if i want my block to be added at the end of the ResNet network, just before the Linear predictor.  what shall i update?

**Comment by zhaoyuezhy** [comment]
> 

Hello, i see the code of mmdet/models/backbones/resnet.py had "plugins", but code gives the examples: Examples:
            ```
>>> plugins=[
            ...     dict(cfg=dict(type='xxx', arg1='xxx'),
            ...          stages=(False, True, True, True),
            ...          position='after_conv2'),
            ...     dict(cfg=dict(type='yyy'),
            ...          stages=(True, True, True, True),
            ...          position='after_conv3'),
            ...     dict(cfg=dict(type='zzz', postfix='1'),
            ...          stages=(True, True, True, True),
            ...          position='after_conv3'),
            ...     dict(cfg=dict(type='zzz', postfix='2'),
            ...          stages=(True, True, True, True),
            ...          position='after_conv3')
            ... ]
            >>> self = ResNet(depth=18)
            >>> stage_plugins = self.make_stage_plugins(plugins, 0)
            >>> assert len(stage_plugins) == 3
```
cannot work. 
Has your problem been solved?
