### ISSUE TITLE
cython is installed by conda but when failed to use pip install . for mmdetection

### ISSUE THREAD

**Issue by sybil12** [open-mmlab/mmdetection#742]
![image](https://user-images.githubusercontent.com/15073782/58715077-bac34c00-83f8-11e9-9b0b-fa28d77d8f05.png)

![image](https://user-images.githubusercontent.com/15073782/58715173-e3e3dc80-83f8-11e9-9cf6-1ffc78985528.png)

I found the same problem when use pip install . for mmcv， then I tried pip install mmcv instead,
as in picture 2 it worked.

but how to get mmdetection work?

**Comment by sybil12** [comment]
actually when I use pip install cython ， the problem is solved.
 but I want to know why pip can not found my conda package?

similar situations happens when i use pip to install a package, but failed to import in conda env, though I use pip in the conda env. 
the reason is pip install the package not in my env site-packages path , the way to solve this is to copy the package folder to my env site-packages path.

so is this time the same problem? could you please help me to figure out how to deal with this situation propely? and why?


> ![image](https://user-images.githubusercontent.com/15073782/58715077-bac34c00-83f8-11e9-9b0b-fa28d77d8f05.png)
> 
> ![image](https://user-images.githubusercontent.com/15073782/58715173-e3e3dc80-83f8-11e9-9cf6-1ffc78985528.png)
> 
> I found the same problem when use pip install . for mmcv， then I tried pip install mmcv instead,
> as in picture 2 it worked.
> 
> but how to get mmdetection work?

**Comment by hellock** [comment]
You have two conda envs `edge` and `py36` and your pip is not in the same conda env with cython.

**Comment by sybil12** [comment]
> You have two conda envs `edge` and `py36` and your pip is not in the same conda env with cython.

you are right, and the reason may be I just copy the py36 folder and rename to edge.

it works when I uninstall pip in edge env and install again. 
thanks a lot.
