### ISSUE TITLE
I trained a model with 28 classes. How to detect only one class (such as face) in actual use

### ISSUE THREAD

**Issue by Masterzhuior** [open-mmlab/mmdetection#7421]
I trained a model with 28 classes. How to detect only one class (such as face) in actual use

**Comment by jbwang1997** [comment]
The output of mmdetection model is a list of np.ndarray. The index of this list indicates the category. You can directly filter out the other class results in the result list.

**Comment by Masterzhuior** [comment]
> 
那怎么抠出人脸然后保存呢？我看了一下结果，好像是归一化之后的bbox

**Comment by Masterzhuior** [comment]
> The output of mmdetection model is a list of np.ndarray. The index of this list indicates the category. You can directly filter out the other class results in the result list.

那怎么抠出人脸然后保存呢？我看了一下结果，好像是归一化之后的bbox

**Comment by jbwang1997** [comment]
The results are based on the coordinate system of the original image. You can directly crop the face region from the image ndarry by slice operation.
