### ISSUE TITLE
Can you provide an example of deploying YOLOV3 trained by mmdetection in C++?

### ISSUE THREAD

**Issue by TTgogogo** [open-mmlab/mmdetection#7423]
I got the YOLOv3 model trained by mmdetection, but didn't know how to deploy it in C++. Can you provide an example?

**Comment by jbwang1997** [comment]
For deployment, you can convert your model to tensorrt or onnx. You can refer to [mmdeploy](https://github.com/open-mmlab/mmdeploy) for details.
