### ISSUE TITLE
How can I obtain current epoch in the detector forwarding?

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection#7425]
I am going to conduct some epoch-related operations when conducting detector forwarding. But I cannot find the parameter like "curr_epoch" to obtain the current training epoch

**Comment by jbwang1997** [comment]
You can use https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/hook/set_epoch_info_hook.py.

**Comment by CheungBH** [comment]
> You can use https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/hook/set_epoch_info_hook.py.

Thank you. Actually, I am not very clear about how to use it. Are there any demo or documents about it?

**Comment by jbwang1997** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/tood/tood_r50_fpn_1x_coco.py#L68-L74 to add `SetEpochInfoHook`. 

Then, in your `detector` you can implement `set_epoch` function like https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/detectors/tood.py#L22-L23.

**Comment by CheungBH** [comment]
Thank you. I succeeded in obtaining the current epoch. 
Are there any api to obtain the total epochs?

**Comment by jbwang1997** [comment]
You can get the max epoch by `max_epoch = runner.max_epochs` in `set_epoch_info_hook`.

**Comment by CheungBH** [comment]
Thank  you. SLoved

**Comment by supergsg** [comment]
> You can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/tood/tood_r50_fpn_1x_coco.py#L68-L74 to add `SetEpochInfoHook`.
> 
> Then, in your `detector` you can implement `set_epoch` function like
> 
> https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/detectors/tood.py#L22-L23
> 
> .I used your method, but self. epoch has not been updated. Can you provide me with a solution?
