### ISSUE TITLE
Question about anchor_generator, original image and feature maps in FPN

### ISSUE THREAD

**Issue by dr-GitHub-account** [open-mmlab/mmdetection#7426]
In 
[https://github.com/open-mmlab/mmdetection/issues/6981](url)
I see "base anchor size is 32X32, 64X64, ...". I am going to try and tell how I understand the relationship between anchor_generator, original image and feature maps in FPN. Please point out my mistake in the following paragraphs, if there is any.

"base anchor size" is the anchor size related to the ORIGINAL image. For instance, if we have input images resized to (800, 800), those anchors of sizes (32X32), (64X64), (128X128), (256X256), (512X512) are all calculated in this (800, 800) scale, but (32X32), (64X64), ... are not real anchor sizes in feature maps in FPN. Given strides = [4, 8, 16, 32, 64], we have feature maps of (800/4, 800/4), (800/8, 800/8), (800/16, 800/16), (800/32, 800/32), (800/64, 800/64), sorted from the largest to the smallest. Let's only talk about ratio = 1 for simplification. The parameter 'ratios' basically causes no confusion. 

The generated anchors in feature map of (800/4, 800/4) will be (32/4, 32/4), the generated anchors in feature map of (800/8, 800/8) will be (64/8, 64/8), ..., the generated anchors in feature map of (800/64, 800/64) will be (512/64, 512/64). That is to say, the anchors will always be (8, 8) in feature maps of different scales in FPN. In large feature map, like (800/4, 800/4), (8, 8) anchors tend to detect small object. In small feature map, like (800/64, 800/64), (8, 8) anchors tend to detect large object. In this way, objects of different scales can all be detected.

Is this the right relationship between anchor_generator, original image and feature maps in FPN?

Thank you!

**Comment by jbwang1997** [comment]
Your understanding is correct. In `anchor_generator`, we set a basic scale and expand it according to the features map strides. Thus, the sizes of each level anchor are always the basic scale when we map anchors into their feature map.

**Comment by DrX2020** [comment]
Thanks a lot!
