### ISSUE TITLE
how to apply the model trained by mmdetection to environment that don't install mmdetection.

### ISSUE THREAD

**Issue by Joll123** [open-mmlab/mmdetection#7442]
first，I use 'torch.save(model, 'path.pth')' to save model at enviroment that install mmdetection. then, I use 'torch.load('path.pth') to load model at environment that don't install mmdetection. Get error. I want to use model at mobile device.

model = torch.load(pth_path)
  File "/Users/jinhonglong/opt/anaconda3/envs/rknn/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/jinhonglong/opt/anaconda3/envs/rknn/lib/python3.7/site-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'mmdet'

**Comment by RangiLyu** [comment]
One way is to deploy the model. Try to use https://github.com/open-mmlab/mmdeploy.
