### ISSUE TITLE
AssertionError caused by loading a pretrained model to the reimplementation of OCRNet

### ISSUE THREAD

**Issue by NeverlandCookies** [open-mmlab/mmdetection#7451]
I tried to reimplement ocrnet_hr48_512x512_160k_ade20k.py on my custom dataset. This config would load a pretrained HRNet as its backbone. But it seems that there will be a conflict between 'pretrained='open-mmlab://msra/hrnetv2_w48'' and cascade_encoder_decoder.py. The cascade_encoder_decoder.py would raise an Assertionerror: cascadeencoderdecoder: both backbone and segmentor set pretrained weight because `pretrained is not None.` and `assert backbone.get('pretrained') is None`. When the code trying to deal with this exception, another Assertionerror rises, which causes an entire failure.

**Comment by RangiLyu** [comment]
OCRNet is in MMSegmentation. Please transfer this issue to MMSegmentation.

**Comment by NeverlandCookies** [comment]
Oh, sorry for making mistake.
