### ISSUE TITLE
Is the GHM equivalent to that of libuyu's project?

### ISSUE THREAD

**Issue by WandernForte** [open-mmlab/mmdetection#7452]
另一个项目的地址在这里->[https://github.com/libuyu/GHM_Detection](url)【确实有点老了】
因为似乎这个项目用的是旧版本的mmdet框架，所以现在有两个问题，一个如题，另一个就是如何将其转化为适配新版本的mmdet的代码呢？
希望各位不吝赐教~

**Comment by WandernForte** [comment]
<English Ver>
The site of another is here - > [https://github.com/libuyu/GHM_Detection](url) [it's really a bit old]
Because it seems that this project uses the old version of mmdet,. Then I have two Questions. One is like the title, and the other is how to convert it into code suitable for the new version of mmdet?

**Comment by BIGWangYuDong** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/tree/master/configs/legacy_1.x
