### ISSUE TITLE
what does every parameter  in the name of the .pth file mean in the MODEL_ZOO.md?

### ISSUE THREAD

**Issue by GYee** [open-mmlab/mmdetection#746]

**Comment by GYee** [comment]
Such as "R-50-C4" and "X-101-64x4d-FPN", what does 'R', 'C4', 'X', '64x4d' mean?

**Comment by randf102** [comment]
I'm curious, too!
Maybe you can reference this [model_zoo.md](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#imagenet-pretrained-models)
Not all, but has some explanation to the model name.

**Comment by hellock** [comment]
These are common abbreviations in papers. `R` means ResNet, `X` means ResNeXt, `64x4d` is a setting of ResNeXt, please refer to the ResNeXt paper for details. `C4` means using 3 stages (C2, C3, C4) of ResNet as backbones and C5 as head.
