### ISSUE TITLE
TypeError: CocoDataset: MultiScaleFlipAug: DefaultFormatBundle: __init__() got an unexpected keyword argument 'keys'

### ISSUE THREAD

**Issue by Zhengym-hub** [open-mmlab/mmdetection#7462]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
Hello everyone, 
I used faster_rcnn to train myself data, I met a problem and found the wrong file, but I did not find a solution, can you help me?
The error is: 
Traceback (most recent call last):
  File "tools/train.py", line 210, in <module>
    main()
  File "tools/train.py", line 199, in main
    train_detector(
  File "/home/zhengym/.local/lib/python3.8/site-packages/mmdet/apis/train.py", line 183, in train_detector
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/home/zhengym/.local/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 81, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zhengym/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CocoDataset: MultiScaleFlipAug: DefaultFormatBundle: __init__() got an unexpected keyword argument 'keys'
Thanks!

**Comment by chhluo** [comment]
Could you please provide the config file you used?

**Comment by Zhengym-hub** [comment]
_base_ = 'faster_rcnn_r50_fpn_1x_coco.py'

model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=3),
        mask_head=dict(num_classes=1, type='FCNMaskHead')))

dataset_type = 'CoCoDataset'
classes = ('Fibroid', 'Fibroma', 'Tumor')
data = dict(
train = dict(
    img_prefix='ovrain/train/',
    classes=classes,
    ann_file='ovarian/annotations/train.json',),
val = dict(
    img_prefix='ovrain/val/',
    classes=classes,
    ann_file='ovarian/annotations/val.json'),
test = dict(
    img_prefix='ovrain/test/',
    classes=classes,
    ann_file='ovarian/annotations/test.json'))

load_from = 'checkpoints/faster_rcnn_r50_fpn_1x_coco.pth'


thank you!

**Comment by Zhengym-hub** [comment]
> Could you please provide the config file you used?

_base_ = 'faster_rcnn_r50_fpn_1x_coco.py'

model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=3),
        mask_head=dict(num_classes=1, type='FCNMaskHead')))

dataset_type = 'CoCoDataset'
classes = ('Fibroid', 'Fibroma', 'Tumor')
data = dict(
train = dict(
    img_prefix='ovrain/train/',
    classes=classes,
    ann_file='ovarian/annotations/train.json',),
val = dict(
    img_prefix='ovrain/val/',
    classes=classes,
    ann_file='ovarian/annotations/val.json'),
test = dict(
    img_prefix='ovrain/test/',
    classes=classes,
    ann_file='ovarian/annotations/test.json'))
load_from = 'checkpoints/faster_rcnn_r50_fpn_1x_coco.pth'

thank you !

**Comment by chhluo** [comment]
What's in ‘base = 'faster_rcnn_r50_fpn_1x_coco.py'’ ？

**Comment by Zhengym-hub** [comment]
> What's in ‘base = 'faster_rcnn_r50_fpn_1x_coco.py'’ ？

it is the same as mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py.

_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

**Comment by chhluo** [comment]
Did you modify the config of `test_pipeline`? There is no `DefaultFormatBundle` in `test_pipeline` by default.

**Comment by Zhengym-hub** [comment]
Yes, I have changed dict(type='ImageToTensor', keys=['img'])  to dict(type='DefaultFormatBundle', keys=['img']),

**Comment by Zhengym-hub** [comment]
> Did you modify the config of `test_pipeline`? There is no `DefaultFormatBundle` in `test_pipeline` by default.

Yes, I have changed  dict(type='ImageToTensor', keys=['img']) to   dict(type='DefaultFormatBundle', keys=['img']),

**Comment by chhluo** [comment]
Why did you change this?

**Comment by Zhengym-hub** [comment]
> Why did you change this?
I saw a document said 'ImageToTensor' has been replaced by 'DefaultFormatBundle', so, i tried it.

**Comment by Zhengym-hub** [comment]
> > Why did you change this?
> > I saw a document said 'ImageToTensor' has been replaced by 'DefaultFormatBundle', so, i tried it.

And now, I changed 'DefaultFormatBundle' to  'ImageToTensor'， it works! Thank you very much!

**Comment by crowmagnumb** [comment]
Yup, I got here for the same reason. This link says to replace it which I did and it doesn't work.
https://mmdetection.readthedocs.io/en/v2.19.0/1_exist_data_model.html?highlight=ImageToTensor#deprecated-imagetotensor
...does that mean I'm using deprecated code, or no?
