### ISSUE TITLE
how to calculate the flops & params of 'DCNs'

### ISSUE THREAD

**Issue by Lausen-Ng** [open-mmlab/mmdetection#7463]
Here, I want to know how to calculate the flops & params of 'DCNs'?
There is an official file 'get_flops.py' to help calculate the flops of the model. However, it does not support the *deformable convolution*.
Does anyone know the solution? Thanks very much!!!!

**Comment by chhluo** [comment]
![image](https://user-images.githubusercontent.com/26483343/159147339-2324ddf9-aaa9-47fa-8e86-b36c1e4fc7eb.png)

For params, dcn have an additional conv to learn `offset`, compared to ordinary conv. For flops, dcn has an additional operation of bilinear interpolation to get feature and a convolution for learning `offset`,  compared to ordinary conv.

**Comment by Lausen-Ng** [comment]
> ![image](https://user-images.githubusercontent.com/26483343/159147339-2324ddf9-aaa9-47fa-8e86-b36c1e4fc7eb.png)
> 
> For params, dcn have an additional conv to learn `offset`, compared to ordinary conv. For flops, dcn has an additional operation of bilinear interpolation to get feature and a convolution for learning `offset`, compared to ordinary conv.

I got it, thanks very much!!
