### ISSUE TITLE
mvcc-full安装问题

### ISSUE THREAD

**Issue by Astroooh** [open-mmlab/mmdetection#7468]
我的python3.9，pytorch是1.11.0，cuda11.3.0,在安装mvcc-full时始终有错误，请问和pytorch的版本有没有关系，是否需要选一个低一点的pytorch重新安装，感谢回复的朋友，谢谢！

**Comment by ZwwWayne** [comment]
Could you post your installation command? PyTorch 1.11.0 + python 3.9 + cuda 11.3 has not been tested for now. We will erify it in the future releases.

**Comment by Tomcccc** [comment]
我成功安装的版本是 pytorch="1.9.0" CUDA="10.2" CUDNN="7"

**Comment by Astroooh** [comment]
> Could you post your installation command? PyTorch 1.11.0 + python 3.9 + cuda 11.3 has not been tested for now. We will erify it in the future releases.
mim install mmdet
or 
pip install mmcv-full==1.4.6 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
谢谢！

**Comment by Astroooh** [comment]
> Could you post your installation command? PyTorch 1.11.0 + python 3.9 + cuda 11.3 has not been tested for now. We will erify it in the future releases.

mim install mmdet
or
pip install mmcv-full==1.4.6 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
谢谢！
