### ISSUE TITLE
How to add predicted images from model in Tensorboardlogger in validation and testing phase

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection#7473]
I have looked the val_step in 
```
[mmdetection/mmdet/models/detectors/base.py]
Line 255 
```
I think I have to call the show_result() method to get the image with bounding boxes in the val_step and also have to extend the implementation of Tensorboardlogger for images but don't know how to get it.
Any help with example will be much appreciated !

**Comment by ZwwWayne** [comment]
You need to write a hook to do that.

**Comment by hhaAndroid** [comment]
@ammaryasirnaich Now there is a [wandb ](https://github.com/open-mmlab/mmdetection/pull/7459)PR that implements this feature, you can refer to it

**Comment by ammaryasirnaich** [comment]
> @ammaryasirnaich Now there is a [wandb ](https://github.com/open-mmlab/mmdetection/pull/7459)PR that implements this feature, you can refer to it

Thanks @hhaAndroid :+1:
