### ISSUE TITLE
What resolution is the pretrained ResNet50?

### ISSUE THREAD

**Issue by flystarhe** [open-mmlab/mmdetection#7475]
你好，我想咨询一下提供的ResNet50预训练权重是在什么分辨率下完成的？比如224x224？或者448x488？

**Comment by Czm369** [comment]
224X224
We use the pretrained Resnet50 from torchvision, referring to https://github.com/open-mmlab/mmdetection/blob/6b87ac22b8d9dea8cc28b9ce84909e6c311e6268/configs/_base_/models/faster_rcnn_r50_fpn.py#L13
