### ISSUE TITLE
Error when I set hooks=dict(type='TensorboardLoggerHook') in the configs file

### ISSUE THREAD

**Issue by GYee** [open-mmlab/mmdetection#748]
I want to use the log style of tensorboard, and I set 

`log_config = dict(
    interval=100,                           
    hooks=[
        #dict(type='TextLoggerHook'),      
        dict(type='TensorboardLoggerHook')  
    ])`

but when I run the train command
it doesn't work and even no error reported, the log just stop that after output the following log:

`loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2019-05-30 04:19:21,238 - INFO - Start running, host: yee@Yee, work_dir: /media/yee/Files/deeplearning_models/mmdetection/mmdetection/work_dirs
2019-05-30 04:19:21,239 - INFO - workflow: [('train', 1)], max: 100 epochs`

After that, nothing was exported.
How can I fix this???

**Comment by hellock** [comment]
You commented `TextLoggerHook`, so no text log will be printed.

**Comment by GYee** [comment]
I try :

`log_config = dict( interval=100, hooks=[ dict(type='TextLoggerHook'), dict(type='TensorboardLoggerHook') ])`

It also does not work

**Comment by GYee** [comment]
> You commented `TextLoggerHook`, so no text log will be printed.

I try :

`log_config = dict( interval=100, hooks=[ dict(type='TextLoggerHook'), dict(type='TensorboardLoggerHook') ])`

It also does not work!

**Comment by GYee** [comment]
It works! Thx!!!

**Comment by GYee** [comment]
> You commented `TextLoggerHook`, so no text log will be printed.

It works. Thx!
