### ISSUE TITLE
How can I find results of faster_rcnn_r50_caffe_c4_1x?

### ISSUE THREAD

**Issue by williamking5** [open-mmlab/mmdetection#7483]
Hi, thank you for great codes! Currently I want to use faster rcnn r50 c4 model to inference, but I cannot find where the checkpoint file is. It seems that exists in mmdet V1.2, however disappear in V2+. The [old link https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_caffe_c4_1x-75ecfdfa.pth](https://s3.ap-northeast-2.amazonaws.com/open-mmlab/mmdetection/models/faster_rcnn_r50_caffe_c4_1x-75ecfdfa.pth) seems unavailable.

![image](https://user-images.githubusercontent.com/16954932/159286943-de6eb628-3e41-43ef-b849-c2d10206a78c.png)

Do you have any ideas?

**Comment by Czm369** [comment]
Maybe you can follow https://github.com/open-mmlab/mmdetection/pull/7435, we will upload the checkpoint as soon as possible.

**Comment by williamking5** [comment]
Thank you
