### ISSUE TITLE
NaN on bbox_loss

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#7485]
Hi! I've implemented a custom copy paste augmentation, and it does train successfully. However, I do notice that bbox_loss goes to NaN at certain iterations pretty frequently. It does not throw an error or throw the training off, but it is concerning to me why certain iterations bbox_loss goes to Nan? 

Do you all have any idea why? I am not using Large Scale Jittering yet, just normal range resize between `[(1333, 640), (1333, 800)]`. 

Does it have to do with the pasted instances going beyond the image bounds? Will that cause any error?

**Comment by Czm369** [comment]
You can check whether the gt after data enhancement is normal and whether there is a division by zero error during training.

**Comment by levan92** [comment]
Thanks! I've solved it. Turns out my augmentation was producing some empty masks/bboxes.
