### ISSUE TITLE
Global Context

### ISSUE THREAD

**Issue by NightShiningStar** [open-mmlab/mmdetection#7491]
请问mmdetection 目前集成了Global Context吗

**Comment by hhaAndroid** [comment]
which paper are you referring to？

**Comment by NightShiningStar** [comment]
https://zhuanlan.zhihu.com/p/50548998,主要看到这个冠军方案增加了context上下文信息，所以想问下mmdetection有没有集成相关模块




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] Global Context (Issue #7491)





 
which paper are you referring to？
