### ISSUE TITLE
Reading from the cfg.evaluation.gpu_collect field during testing

### ISSUE THREAD

**Issue by LutingWang** [open-mmlab/mmdetection#7495]
**Describe the feature**

During testing, use `gpu_collect = args.gpu_collect or cfg.evaluation.gpu_collect`.

**Motivation**
During testing, the `cfg.evaluation.gpu_collect` does not take effect. Rather, users need to specify `gpu_collect` from the command line.

This behavior is inconsistent with the evaluation during training, where `cfg.evaluation.gpu_collect` decides whether to use `gpu_collect`.

**Additional context**
In `tools/test.py`, line 71-74

```python
    parser.add_argument(
        '--gpu-collect',
        action='store_true',
        help='whether to use gpu to collect results.')
```

In `mmdet/apis/train.py`, line 190-196

```python
        eval_cfg = cfg.get('evaluation', {})
        eval_cfg['by_epoch'] = cfg.runner['type'] != 'IterBasedRunner'
        eval_hook = DistEvalHook if distributed else EvalHook
        # In this PR (https://github.com/open-mmlab/mmcv/pull/1193), the
        # priority of IterTimerHook has been modified from 'NORMAL' to 'LOW'.
        runner.register_hook(
            eval_hook(val_dataloader, **eval_cfg), priority='LOW')
```

For backward compatibility, I think it may be reasonable to use `gpu_collect = args.gpu_collect or cfg.evaluation.gpu_collect` in `tools/test.py` line 238-239

```python
        outputs = multi_gpu_test(model, data_loader, args.tmpdir,
                                 args.gpu_collect)
```

If this seems OK, I can create a PR.

**Comment by hhaAndroid** [comment]
@LutingWang Thanks for your feedback, we'll discuss if changes are needed.

**Comment by hhaAndroid** [comment]
@LutingWang Yes. Your idea is right, Can you create a PR?
