### ISSUE TITLE
When I train in CPU env, should I reinstall pytorch-cpu ? and which model support CPU train?

### ISSUE THREAD

**Issue by jiejie1993** [open-mmlab/mmdetection#7496]

**Comment by jiejie1993** [comment]
问题1：使用CPU训练时，是不是需要重新安装cpu版本的pytorch？还是直接使用gpu版本的pytorch，同时设置export CUDA_VISIBLE_DEVICES=-1
问题2 ：mmcv-full是否需要重新安装cpu版本的？
问题3：由于一些cuda的op不可用，哪些模型可以使用CPU进行训练呢？Yolox是否可以？

**Comment by jiejie1993** [comment]
填坑，使用CPU训练时使用CPU版本镜像，安装cpu版本pytorch；mmcv源码编译安装，在没有显卡的情况下默认安装cpu版本，不会编译cuda的op；测试CPU环境下可训练的模型：yolov3,fcos,retinanet,yolox

**Comment by zeqianl** [comment]
你好，请问你是怎么使用cpu训练的呢？我在train.py设置了os.[CUDA_VISIBLE_DEVICES]='-1'但依旧无法跑起来。想知道你是怎么设置的呢，或者说具体是怎么在cpu上跑起来的呢？？
![image](https://user-images.githubusercontent.com/87052414/193178047-bd08ea21-2dbc-46e4-a752-c3cc86a9ce6a.png)

**Comment by jiejie1993** [comment]
> 你好，请问你是怎么使用cpu训练的呢？我在train.py设置了os.[CUDA_VISIBLE_DEVICES]='-1'但依旧无法跑起来。想知道你是怎么设置的呢，或者说具体是怎么在cpu上跑起来的呢？？ ![image](https://user-images.githubusercontent.com/87052414/193178047-bd08ea21-2dbc-46e4-a752-c3cc86a9ce6a.png)

找一个CPU镜像，起容器在容器里面训练
