### ISSUE TITLE
Mask-RCNN Benchmark

### ISSUE THREAD

**Issue by fmassa** [open-mmlab/mmdetection#75]
Hi,

We've just open-sourced our PyTorch 1.0 implementation of Faster R-CNN and Mask R-CNN in https://github.com/facebookresearch/maskrcnn-benchmark.
It contains code for training and testing most of the detection and segmentation models from Detectron.

Compared to the current implementation in `mmdetection`, it seems to bring some significant speed-ups during training, with less memory usage as well.

Please feel free to try it out, and even plug in some of our components to potentially get some speedups.

**Comment by lindahua** [comment]
@fmassa Congratulations to the release of the new implementation of mask rcnn! It is indeed a great piece of work. The team is now working intensely toward CVPR submission, and will learn from your efforts afterwards.

**Comment by sybil12** [comment]
how about speed when infer?

**Comment by hellock** [comment]
We released our [technical report](https://arxiv.org/abs/1906.07155) for the latest benchmark.
