### ISSUE TITLE
How to extract the features from backbone and fpn? 

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmdetection#7500]
Let's say I built the model as shown below:

```
model = build_detector(cfg_model, test_cfg=cfg.get('test_cfg'))
checkpoint = load_checkpoint(model, './workdirs/epoch_12.pth', map_location='cpu')
model.to('cuda:0')
model.eval();
```

If I want to extract the features from the backbone and FPN, how should I do it the same way it can be done in torchvision?

Just like this:
```
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval().to(device)
fpn_layers = [model.backbone]
```

**Comment by hhaAndroid** [comment]
@chandlerbing65nm The mmdet model is also divided into backbone and fpn. Can you also refer to the usage of torchvision?
