### ISSUE TITLE
Seed initialization when resuming the training

### ISSUE THREAD

**Issue by burak43** [open-mmlab/mmdetection#7508]
Hi folks,

Does mmdetection support seed saving and loading from checkpoint files? To my understanding, currently what happens when we stop the training and resume it afterwards is that it [either set random seed or use the one passed in the arguments ](https://github.com/open-mmlab/mmdetection/issues/6339) regardless of resuming or starting the training. This must be restraining the reproducibility. What's worse is that if the same seed is used over and over again via passing as argument (assume that the training is stopped and resumed due to some reasons), it may even cause to the repetition of batch samples or data augmentation (I'm not sure for augmentation tho) when resuming compared to the first epochs of the training. Please correct me if I'm wrong in any way.

I've looked around the codes and dived deep into it, checkpoint saving and loading occurs in `mmcv` [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py) and couldn't find anything regarding the seed. 

1. Is seed saving/resuming being considered to be implemented?
2. Is there a workaround that you may suggest? 

Thanks.

**Comment by jbwang1997** [comment]
The seed of one training will save in checkpoints' meta for convenience of debugging, but this seed will not be set in the new run. When training and resuming, the program will random a seed if one doesn't set it. The case you proposed will happen when users set the same seed in resuming. This should be avoided by users.

**Comment by burak43** [comment]
Thank you for your quick reply and clarifications. In that case, when a run is interrupted/stopped, the reproducibility is broken for sure, right? Will you consider saving current state of RNGs that could be used for resuming in the future, if not is there a particular reason that one should be aware of? Also, could you please pinpoint where does saving in checkpoints' meta occur in codebase @jbwang1997 ?

**Comment by jbwang1997** [comment]
It's hard to restore the state of RNGs because there are different seeds setting in each process and data sampler. So, we don't have a plan to support this feature.

**Comment by jbwang1997** [comment]
The meta of seed is added in tools/train.py.

**Comment by iacopo97** [comment]
I have this issue
