### ISSUE TITLE
What kinds of out file does mmdetection provide?

### ISSUE THREAD

**Issue by jacob-kang** [open-mmlab/mmdetection#7509]
I just read robustness_benchmarking.md
And I want to test my model robustness.

But I wonder what kinds of **[--out ${RESULT_FILE}]** can be used?
I saw It allows to use pickle.
But How can I see my model's mRC, mPC with pickle?

**Comment by jbwang1997** [comment]
You can add `----final-prints mRC rPC` after your command. You can directly refer to the [`parse_args function`](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/test_robustness.py#L151-L165) to find the optional arguments.
