### ISSUE TITLE
ImportError: cannot import name 'Registry' from 'mmdet.utils' (mmdet/utils/__init__.py)

### ISSUE THREAD

**Issue by BaeSukkyoung** [open-mmlab/mmdetection#7512]
I use my own dataset.
Then I use cascade_rcnn_x101_64x4d_fpn_1x.py configuration file to change for my dataset.
And then training,

I got ImportError: cannot import name 'Registry' from 'mmdet.utils' (mmdet/utils/__init__.py)

I don't know why this error occurs even though I haven't changed the existing environment.

**Comment by jbwang1997** [comment]
Could you provide more information, such as the config and the version of mmdet and mmcv?

**Comment by iitm96** [comment]
I have the same issue. What is the fix?

**Comment by kvnptl** [comment]
Same issue with `mmcv 2.1.0`

**Comment by mahilaMoghadami** [comment]
same issue, did you solved that? or any solution?

**Comment by kvnptl** [comment]
As per the [Changelog](https://mmcv.readthedocs.io/en/latest/compatibility.html#:~:text=All%20classes%20in%20mmcv.utils%20(eg%20Config%20and%20Registry)%20and%20many%20functions%2C%20removed%20in%20PR%20%232217.%20Only%20a%20few%20functions%20related%20to%20mmcv%20are%20reserved.) for v2.x.x, it is mentioned that they removed Config and Registry.

**Comment by captain-36** [comment]
I solved this problem by changing the version of mmdet.
mim uninstall mmdet
mim install mmdet ==3.1.0

**Comment by 15738281321** [comment]
> I solved this problem by changing the version of mmdet. mim uninstall mmdet mim install mmdet ==3.1.0

装完这个之后就出现了新的问题ModuleNotFoundError: No module named 'mmdet.core'

**Comment by Cesiumhydroxide** [comment]
go to the file and change 'from mmcv.utils import Registry' to 'from mmcv.utils.registry import Registry'

**Comment by 895318** [comment]
change 'from mmcv.utils import Registry' to 'from mmenging.registry import Registry' with mmcv 2.1.0

**Comment by hlnull** [comment]
change 
```
from mmcv.utils import Registry
```

to 

```
from mmengine.registry import Registry
```
