### ISSUE TITLE
Can i modify code for multi-gpu training in single machine?

### ISSUE THREAD

**Issue by hoya-cho** [open-mmlab/mmdetection#7515]
Is it possible to operate multi-gpu training by directly supplying the necessary parameters without using the provided dist_train.sh ?
For example, is it possible by giving values to setup_multi_processes(cfg), args.gpus, and args.launcher? 
And what else do I need?

**Comment by RangiLyu** [comment]
If you want to start the distributed training processes with python code instead of the script,  you can refer to https://pytorch.org/tutorials/intermediate/dist_tuto.html
