### ISSUE TITLE
Can we merge the output .pkl files of several models on the same test set by taking their intersections?

### ISSUE THREAD

**Issue by dr-GitHub-account** [open-mmlab/mmdetection#7522]
I am wondering if it is possible to merge the predict results (.pkl) of several models, for example, by taking their intersections, so as to promote detection. If there is not such a tool, I might need to look into .pkl structure and see how to customize one.

**Comment by RangiLyu** [comment]
Currently, there is no such tool in mmdetection.

**Comment by dr-GitHub-account** [comment]
Thank you!
