### ISSUE TITLE
Where to find the code of .cfg, .to(device) and .eval()

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmdetection#7527]
When a certain detector is being trained or tested, we set one of these lines of code:

```
model.cfg = cfg
model.to(device)
model.eval();
```

But where exactly in the `mmdet `or `mmcv` folders we can find the code definition of `.cfg, .to(device) and .eval()`? Where are the functions defined?

**Comment by RangiLyu** [comment]
All of these methods are not defined by mmdetection or mmcv.

> model.cfg = cfg

This is a use case of Python's magic method `__setattr__`
Please refer to https://docs.python.org/3.8/reference/datamodel.html?highlight=__setattr__#object.__setattr__

> model.to(device)
> model.eval()

These are PyTorch Module's `to` method. Please refer to 
https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=module#torch.nn.Module.to
https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=module#torch.nn.Module.eval

**Comment by chandlerbing65nm** [comment]
> All of these methods are not defined by mmdetection or mmcv.
> 
> > model.cfg = cfg
> 
> This is a use case of Python's magic method `__setattr__` Please refer to https://docs.python.org/3.8/reference/datamodel.html?highlight=__setattr__#object.__setattr__
> 
> > model.to(device)
> > model.eval()
> 
> These are PyTorch Module's `to` method. Please refer to https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=module#torch.nn.Module.to https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=module#torch.nn.Module.eval

@RangiLyu Thanks for these. Do you have any idea how to extract the features from the different modules of `mmdetection`?

Say for example I want to extract the `backbone `and `neck `features in different levels, can I use `model.backbone` or `model.neck`?

**Comment by RangiLyu** [comment]
You can use `extract_feat` method in the detector to extract features. Please refer to mmdet/models/detectors/base.py
