### ISSUE TITLE
What is the return of inference_detector(model, img) when a class doesn't have any detections?

### ISSUE THREAD

**Issue by AlphonsG** [open-mmlab/mmdetection#7529]
For example, if I have 3 classes `['dog', 'cow', 'cat']`, with dog and cat having one detection and cow having none, does it look like:

`result = [[x1, y1, x2, y2, score], [], [x1, y1, x2, y2, score]]`?

**Comment by BIGWangYuDong** [comment]
yep, I think so. and if you have more than one image, the result may like 
[
[[x1, y1, x2, y2, score], [ ], [x1, y1, x2, y2, score]],
[[xxxx], [xxxx], [xxxxx]],
xxxx
]

**Comment by AlphonsG** [comment]
Thanks a lot for the quick reply and answer.
