### ISSUE TITLE
About the loss in the official log

### ISSUE THREAD

**Issue by zengwz** [open-mmlab/mmdetection#7531]
In the official YOLOV3 train log, the loss is very large and is close to hundreds. 
![image](https://user-images.githubusercontent.com/57857883/160094378-f598f2dd-5262-4688-85be-d91354056f62.png)

And when I train YOLOV3 connected a track model(no change on YOLOV3 model, just connect a track model behind it) in BDD100K dataset, its loss that belongs to YOLOV3 is smaller than the loss in official log. 
![Screenshot from 2022-03-25 17-28-52](https://user-images.githubusercontent.com/57857883/160094231-6d1e4bda-c578-407f-9370-a169b18b02cb.png)

However, its evaluation is zero.
![Screenshot from 2022-03-25 17-29-17](https://user-images.githubusercontent.com/57857883/160096108-e4b2f5e5-be40-4ec2-a649-835221e08fea.png)

And visualization  of detection bboxes is as below:
![b1c66a42-6f7d68ca-0000013 jpg](https://user-images.githubusercontent.com/57857883/160097005-96662efe-a3b4-403f-b2c3-b245f02aab45.png)

So, what is the suitable loss?  Or it is caused by others?

**Comment by BIGWangYuDong** [comment]
Probably a simple cascade is not very efficient. Maybe your tracking loss affects detection loss.

**Comment by David-Biggs** [comment]
> Probably a simple cascade is not very efficient. Maybe your tracking loss affects detection loss. Also, please check whether you have load the GTs sucessfully.

How can one check if the GTs are loaded sucessfully?
