### ISSUE TITLE
AssertionError: fused_bias_leakyrelu miss in module _ext

### ISSUE THREAD

**Issue by lpkoh** [open-mmlab/mmdetection#7536]
I am running Ubuntu 18.04. I have installed mmcv==1.3.3, mmdet==2.7.0, using openmim.

I face the following issue when importing from mmdet.core
```
Traceback (most recent call last):
  File "tools/scrfd2onnx.py", line 10, in <module>
    from mmdet.core import (build_model_from_cfg, generate_inputs_and_wrap_model,
  File "/home/va/Desktop/scrfd/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/va/Desktop/scrfd/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/va/Desktop/scrfd/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/va/Desktop/scrfd/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/home/va/Desktop/scrfd/venv/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 15, in <module>
    from .fused_bias_leakyrelu import FusedBiasLeakyReLU, fused_bias_leakyrelu
  File "/home/va/Desktop/scrfd/venv/lib/python3.6/site-packages/mmcv/ops/fused_bias_leakyrelu.py", line 10, in <module>
    ext_module = ext_loader.load_ext('_ext', ['fused_bias_leakyrelu'])
  File "/home/va/Desktop/scrfd/venv/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: fused_bias_leakyrelu miss in module _ext
```

Could someone advise?

**Comment by chhluo** [comment]
Please run `python mmdet/utils/collect_env.py`, and paste all information here.

**Comment by lpkoh** [comment]
Hi, I have run it and this is my result:

![image](https://user-images.githubusercontent.com/48631399/160249137-9bb2ba61-99d3-4213-877c-03424bbcc7ac.png)

**Comment by chhluo** [comment]
It seems that mmcv-full was installed impropey. which command did you use to installed mmcv?

**Comment by lpkoh** [comment]
I might have used mmcv==1.3.3 instead of mmcv-full==1.3.3.

I am retrying installation with mmcv-full right now. Could this be the reason?

**Comment by lpkoh** [comment]
Hi, I have reinstalled my mmcv-full.

I ran python3 mmdet/utils/collect_env.py, and this is what I got:
![image](https://user-images.githubusercontent.com/48631399/160268680-023a048a-b395-41cb-b064-5bb7561c9070.png)

I ran the command `python3 tools/scrfd2onnx.py config configs/scrfd/scrfd_2.5g.py checkpoint pytorch\ weights/scfrd_2-5g.pth --input-img 0.jpg --shape 640` from https://github.com/deepinsight/insightface/tree/master/detection/scrfd and had the following issue when importing from mmdet.core:
![image](https://user-images.githubusercontent.com/48631399/160268700-9cf2c8a8-8ac3-4522-ac4e-e1af114da7ef.png)

**Comment by chhluo** [comment]
Refer to this https://mmdetection.readthedocs.io/en/latest/faq.html#mmcv-installation

**Comment by ZwwWayne** [comment]
MMCV should update the  FAQ documentation.

**Comment by ZwwWayne** [comment]
Resolved in MMCV's documentation.
