### ISSUE TITLE
Does MMDetection contain a script that draws GT boxes in COCO-format json annotation?

### ISSUE THREAD

**Issue by dr-GitHub-account** [open-mmlab/mmdetection#7545]
I am currently writing a script that draws GT boxes on images according to COCO-format annotation (.json). I am wondering if there is a script in MMDetection that does the same thing. Maybe there are some useful apis or brief methods I can learn from.

**Comment by ZwwWayne** [comment]
See https://subgithub.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py.

**Comment by dr-GitHub-account** [comment]
Thank you!
