### ISSUE TITLE
GIoULoss in GFL

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmdetection#7548]
Why GIoULoss still used in GFL? 
To my understanding, GFL contains QFL and DFL. QFL for joint classification and IoU score while DFL for bbox regression 
![image](https://user-images.githubusercontent.com/69593462/160317213-a035eab7-a063-463a-9106-46c68d069b4f.png)
So DFL is supposed to replace GIoULoss no?

**Comment by Czm369** [comment]
We implemented it following the official code, maybe you can compare the code further.

**Comment by iumyx2612** [comment]
> We implemented it following the official code, maybe you can compare the code further.

I understand that you implemented it following the official code. I just want to ask why does GIoULoss still needed, is it used in training? If yes, then why DFL still needed? Isn't DFL and GIoULoss both bbox loss? I don't want to raise an issues on the official github repo because it seems no one is getting a response there

**Comment by RangiLyu** [comment]
> > We implemented it following the official code, maybe you can compare the code further.
> 
> I understand that you implemented it following the official code. I just want to ask why does GIoULoss still needed, is it used in training? If yes, then why DFL still needed? Isn't DFL and GIoULoss both bbox loss? I don't want to raise an issues on the official github repo because it seems no one is getting a response there

Both GIOU and DFL are used. The optimization targets of these two losses are not the same. Using two regression losses at the same time does not conflict.

**Comment by iumyx2612** [comment]
> > > We implemented it following the official code, maybe you can compare the code further.
> > 
> > 
> > I understand that you implemented it following the official code. I just want to ask why does GIoULoss still needed, is it used in training? If yes, then why DFL still needed? Isn't DFL and GIoULoss both bbox loss? I don't want to raise an issues on the official github repo because it seems no one is getting a response there
> 
> Both GIOU and DFL are used. The optimization targets of these two losses are not the same. Using two regression losses at the same time does not conflict.

Thank you! I thought they would conflict
