### ISSUE TITLE
No such file or directory: ' data/coco/proposals/rpn r50_ fpn 1x train2017. pkl“ 

### ISSUE THREAD

**Issue by mukaiNO1** [open-mmlab/mmdetection#7553]
FiLeNotFoundError: CocoDataset: [Errno 2] No such file or directory: ' data/coco/proposals/rpn r50_ fpn 1x train2017. pkl“ 
How can i download this file？ Please

**Comment by Czm369** [comment]
May you can refer to https://github.com/open-mmlab/mmdetection/pull/7549

**Comment by mukaiNO1** [comment]
> Thank you, I got it.
