### ISSUE TITLE
Is there any plugin to simplify the preview of configuration?

### ISSUE THREAD

**Issue by williamking5** [open-mmlab/mmdetection#7557]
Hi, thank you for great codes! I find the configuration files have really deep hierarchical structures, which is defined by `_base_`. This kind of design can promote reusing codes but make difficult to change and preview the configurations. For example, if I want to change some arguments, I have to search all `_base_` configurations, and it is time-consuming.

For  `python`, plugins such as `Pylance` have been developed for IDEs to help dive into the codes but mmdet-style configurations are not supported by these plugins. I wonder if there is some plugins that can help preview configurations? Thank you very much!

**Comment by Czm369** [comment]
Sorry, I do not konw whether there exits some plugins that can help preview configurations.
But we are supporting replacing `${key}` with the value of `cfg.key`
https://github.com/open-mmlab/mmdetection/pull/7492

**Comment by shinya7y** [comment]
VSCode extension `Open file` is useful, although it is not for preview.
https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-openfile

> This extension enables the user to open a file under the current cursor position. Just right-click on a pathname within a open document and select the open file under cursor option (or just press Alt + P without right-click). If the file is found by vscode then it will open a new tab with this file.

**Comment by williamking5** [comment]
Thank you! I've tried these tools, and they are useful for me:)
