### ISSUE TITLE
evaluate models under different epoch

### ISSUE THREAD

**Issue by Baby47** [open-mmlab/mmdetection#756]
When evaluating the trained model under different epoch,  I meet some errors.
I have tried to replace the checkpoint file by the checkpoint dir in which i saved many weights under different epoch. However, when i test these models, I find the checkpoint encounters mistake from the third epoch.
I test the model in this way:
    for each_checkpoint in checkpoint_list:
        each_checkpoint = load_checkpoint(model, each_checkpoint, map_location='cpu')
However, In the original code in test.py:
        checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
and the checkpoint is not fully used. 
Maybe the different checkpoint is not loaded correctly and I need some help.Thanks

**Comment by hellock** [comment]
I did not catch your point. Could you explain it more clearly?

**Comment by Baby47** [comment]
put it more clearly, the test.py script can only test model under one specific model under specific epoch, what should i change to evaluate model under different epoches by one .py file.

At 2019-06-09 16:13:46, "Kai Chen" <notifications@github.com> wrote:


I did not catch your point. Could you explain it more clearly?

**Comment by hellock** [comment]
What if you use a for-loop to wrap the testing?

**Comment by Baby47** [comment]
I have tried for-loop as i commented at the beginning , but it seems the checkpoints are interwined. So i get the same result from the third epoch.
