### ISSUE TITLE
SWIN instance segmentation with FCOS - how to construct config file?

### ISSUE THREAD

**Issue by ChristofferEdlund** [open-mmlab/mmdetection#7566]
Hi!

I would like to build a one-stage instance segmentation model using a SWIN backbone and FCOS object detection.
My own tries to get this to work has fallen flat and any input on how to construct a config file for this task would be very helpful.

Kindly,
Christoffer

**Comment by PeterVennerstrom** [comment]
My mistake on YOLACT.  It does use anchor boxes.  [SipMask](https://arxiv.org/abs/2007.14772) is an extension of YOLACT built on FCOS.  [BlendMask](https://arxiv.org/abs/2001.00309), [EmbedMask](https://www.ijcai.org/proceedings/2021/0175.pdf) and [SOLO/SOLOv2](https://sites.cs.ucsb.edu/~lilei/pubs/wang2020solov2.pdf) are one stage anchor free instance segmentation methods. 

[CenterNetV2](https://arxiv.org/abs/2103.07461) is a two stage method with a one stage style anchor free RPN.  It could be extended like CenterMask or MaskRCNN.    

SWIN can be added to any method by replacing the backbone and adjusting the neck config.  Adding instance segmentation to bbox detectors is more complex and may require new code.

**Comment by ChristofferEdlund** [comment]
@PeterVennerstrom Was not aware of SipMask, there is just to many architectures to keep track of these days.. I will give it a go with exchanging the backbones of proposed networks with SWIN and see if it works. 

Thank you Peter, much appreciated =)

**Comment by ZwwWayne** [comment]
See this example of Swin Transformer for RetinaNet https://github.com/open-mmlab/mmdetection/blob/master/configs/swin/retinanet_swin-t-p4-w7_fpn_1x_coco.py. You can use it for FCOS since the only difference between retinanet and FCOS is the backbone.
