### ISSUE TITLE
mosaic and mixup error

### ISSUE THREAD

**Issue by zwhua006** [open-mmlab/mmdetection#7569]
when I use mosaic and mixup in cascade_rcnn_r50_fpn:
the error appears,like this:
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 185, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/media/iiaulab/iiau/mmdetection/mmdet/datasets/builder.py", line 77, in build_dataset
    dataset = MultiImageMixDataset(**cp_cfg)
TypeError: __init__() got an unexpected keyword argument 'ann_file'

my config file like this:
base_ = [
    '../_base_/models/cascade_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_20e.py', '../_base_/default_runtime.py'
]
img_scale = (512, 512)
model = dict(
    backbone=dict(
        dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True)),
    neck=[
        dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            num_outs=5),
        dict(
            type='BFP',
            in_channels=256,
            num_levels=5,
            refine_level=2,
            refine_type='non_local')
    ])
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[19.47772,19.47772,19.47772], std=[37.64707, 37.64707,37.64707], to_rgb=True)
train_pipeline = [
        dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
	dict(type='MixUp', img_scale=img_scale,ratio_range=(0.8, 1.6),pad_val=114.0),
     	dict(type='RandomFlip', flip_ratio=0.5),
        dict(type='Normalize', **img_norm_cfg),
        dict(type='Pad', size_divisor=32),
        dict(type='DefaultFormatBundle'),
        dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
    ]
train_dataset = dict(
	type='MultiImageMixDataset',
	dataset=dict(
		type=dataset_type,
		ann_file=data_root + 'annotations/instances_train2017.json',
		img_prefix=data_root + 'train2017/',
		pipeline=[
		dict(type='LoadImageFromFile'),
		dict(type='LoadAnnotations', with_bbox=True)
		],
		filter_empty_gt=False,
	),
	pipeline=train_pipeline)
data = dict(
        train=train_dataset
        )
how to solve this problems.thanks

**Comment by hhaAndroid** [comment]
@zwhua006 Are you referring to the [mosaic](https://github.com/open-mmlab/mmdetection/blob/master/docs/zh_cn/tutorials/how_to.md#%E4%BD%BF%E7%94%A8%E9%A9%AC%E8%B5%9B%E5%85%8B%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%BC%BA) configuration?
