### ISSUE TITLE
Training with my own dataset, I got an error...

### ISSUE THREAD

**Issue by BaeSukkyoung** [open-mmlab/mmdetection#7576]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

./tools/dist_train.sh configs/cascade_mask_rcnn_x101_64x4d_fpn_20e_concrete_crack_220328.py 4

```none
A placeholder for the command.
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
4. What dataset did you use?

My own dataset which is composed of crack.
Is it right that mmdetection doesn't detect background ?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
I run the modified 'cascade_mask_rcnn_x101_64×4d_fpn_20e'.

3. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

Traceback (most recent call last):
  File "./tools/train.py", line 189, in <module>
    main()
  File "./tools/train.py", line 185, in main
    meta=meta)
  File "/home/user/kec-detection/mmdetection/mmdet/apis/train.py", line 211, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/user/kec-detection/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user/kec-detection/mmcv/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/user/kec-detection/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/user/kec-detection/mmcv/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/user/kec-detection/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 58, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/user/kec-detection/mmcv/mmcv/runner/hooks/evaluation.py", line 360, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/user/kec-detection/mmdetection/mmdet/datasets/coco.py", line 414, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/user/kec-detection/mmdetection/mmdet/datasets/coco.py", line 359, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/user/kec-detection/mmdetection/mmdet/datasets/coco.py", line 296, in results2json
    json_results = self._segm2json(results)
  File "/home/user/kec-detection/mmdetection/mmdet/datasets/coco.py", line 247, in _segm2json
    data['category_id'] = self.cat_ids[label]
**_IndexError: list index out of range_**
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/python-envs/kec-detect/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/user/python-envs/kec-detect/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/python-envs/kec-detect/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/cascade_mask_rcnn_x101_64x4d_fpn_20e_concrete_crack_220328.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by jbwang1997** [comment]
Have you changed the `num_classes` in the model config? It seems the results label out of range of dataset cat_ids list.

**Comment by BaeSukkyoung** [comment]
I also changed the num_classes in the configs/_base_/models cascade_mask_rcnn_r50_fpn.py .
80 to 1
Is it right that mmdetection doesn't detect background ?

**Comment by BaeSukkyoung** [comment]
Change the config file like this.

# model settings
model = dict(
    type='CascadeRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    roi_head=dict(
        type='CascadeRoIHead',
        num_stages=3,
        stage_loss_weights=[1, 0.5, 0.25],
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ],
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=1,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.6,
                    neg_iou_thr=0.6,
                    min_pos_iou=0.6,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.7,
                    neg_iou_thr=0.7,
                    min_pos_iou=0.7,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)))

**Comment by BaeSukkyoung** [comment]
And I also add cityscapes_concrete_crack.py in the mmdet/datasets.

# dataset settings
dataset_type = 'ConcreteCrack'
data_root = '/home/user/UOS-SSaS Dropbox/05. Data/02. Training&Test/sukkyoung_thesis/1,767 crack/Cascade Mask R-CNN/dilation=0/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=[(2048, 1024), (2048, 1024)], keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 1024),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=8,
        dataset=dict(
            type=dataset_type,
            ann_file=data_root +
            'annotations/instances_train2018.json',
            img_prefix=data_root + 'train2018/',
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        ann_file=data_root +
        'annotations/instances_val2018.json',
        img_prefix=data_root + 'val2018/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root +
        'annotations/instances_test2018.json',
        img_prefix=data_root + 'test2018/',
        pipeline=test_pipeline))
evaluation = dict(metric=['bbox', 'segm'])

**Comment by BaeSukkyoung** [comment]
> Change the config file like this.
> 
> # model settings
> ```
> model = dict(
>     type='CascadeRCNN',
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=True,
>         style='pytorch',
>         init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         num_outs=5),
>     rpn_head=dict(
>         type='RPNHead',
>         in_channels=256,
>         feat_channels=256,
>         anchor_generator=dict(
>             type='AnchorGenerator',
>             scales=[8],
>             ratios=[0.5, 1.0, 2.0],
>             strides=[4, 8, 16, 32, 64]),
>         bbox_coder=dict(
>             type='DeltaXYWHBBoxCoder',
>             target_means=[.0, .0, .0, .0],
>             target_stds=[1.0, 1.0, 1.0, 1.0]),
>         loss_cls=dict(
>             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
>         loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
>     roi_head=dict(
>         type='CascadeRoIHead',
>         num_stages=3,
>         stage_loss_weights=[1, 0.5, 0.25],
>         bbox_roi_extractor=dict(
>             type='SingleRoIExtractor',
>             roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
>             out_channels=256,
>             featmap_strides=[4, 8, 16, 32]),
>         bbox_head=[
>             dict(
>                 type='Shared2FCBBoxHead',
>                 in_channels=256,
>                 fc_out_channels=1024,
>                 roi_feat_size=7,
>                 num_classes=1,
>                 bbox_coder=dict(
>                     type='DeltaXYWHBBoxCoder',
>                     target_means=[0., 0., 0., 0.],
>                     target_stds=[0.1, 0.1, 0.2, 0.2]),
>                 reg_class_agnostic=True,
>                 loss_cls=dict(
>                     type='CrossEntropyLoss',
>                     use_sigmoid=False,
>                     loss_weight=1.0),
>                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
>                                loss_weight=1.0)),
>             dict(
>                 type='Shared2FCBBoxHead',
>                 in_channels=256,
>                 fc_out_channels=1024,
>                 roi_feat_size=7,
>                 num_classes=1,
>                 bbox_coder=dict(
>                     type='DeltaXYWHBBoxCoder',
>                     target_means=[0., 0., 0., 0.],
>                     target_stds=[0.05, 0.05, 0.1, 0.1]),
>                 reg_class_agnostic=True,
>                 loss_cls=dict(
>                     type='CrossEntropyLoss',
>                     use_sigmoid=False,
>                     loss_weight=1.0),
>                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
>                                loss_weight=1.0)),
>             dict(
>                 type='Shared2FCBBoxHead',
>                 in_channels=256,
>                 fc_out_channels=1024,
>                 roi_feat_size=7,
>                 num_classes=1,
>                 bbox_coder=dict(
>                     type='DeltaXYWHBBoxCoder',
>                     target_means=[0., 0., 0., 0.],
>                     target_stds=[0.033, 0.033, 0.067, 0.067]),
>                 reg_class_agnostic=True,
>                 loss_cls=dict(
>                     type='CrossEntropyLoss',
>                     use_sigmoid=False,
>                     loss_weight=1.0),
>                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
>         ],
>         mask_roi_extractor=dict(
>             type='SingleRoIExtractor',
>             roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
>             out_channels=256,
>             featmap_strides=[4, 8, 16, 32]),
>         mask_head=dict(
>             type='FCNMaskHead',
>             num_convs=4,
>             in_channels=256,
>             conv_out_channels=256,
>             num_classes=1,
>             loss_mask=dict(
>                 type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
>     # model training and testing settings
>     train_cfg=dict(
>         rpn=dict(
>             assigner=dict(
>                 type='MaxIoUAssigner',
>                 pos_iou_thr=0.7,
>                 neg_iou_thr=0.3,
>                 min_pos_iou=0.3,
>                 match_low_quality=True,
>                 ignore_iof_thr=-1),
>             sampler=dict(
>                 type='RandomSampler',
>                 num=256,
>                 pos_fraction=0.5,
>                 neg_pos_ub=-1,
>                 add_gt_as_proposals=False),
>             allowed_border=0,
>             pos_weight=-1,
>             debug=False),
>         rpn_proposal=dict(
>             nms_pre=2000,
>             max_per_img=2000,
>             nms=dict(type='nms', iou_threshold=0.7),
>             min_bbox_size=0),
>         rcnn=[
>             dict(
>                 assigner=dict(
>                     type='MaxIoUAssigner',
>                     pos_iou_thr=0.5,
>                     neg_iou_thr=0.5,
>                     min_pos_iou=0.5,
>                     match_low_quality=False,
>                     ignore_iof_thr=-1),
>                 sampler=dict(
>                     type='RandomSampler',
>                     num=512,
>                     pos_fraction=0.25,
>                     neg_pos_ub=-1,
>                     add_gt_as_proposals=True),
>                 mask_size=28,
>                 pos_weight=-1,
>                 debug=False),
>             dict(
>                 assigner=dict(
>                     type='MaxIoUAssigner',
>                     pos_iou_thr=0.6,
>                     neg_iou_thr=0.6,
>                     min_pos_iou=0.6,
>                     match_low_quality=False,
>                     ignore_iof_thr=-1),
>                 sampler=dict(
>                     type='RandomSampler',
>                     num=512,
>                     pos_fraction=0.25,
>                     neg_pos_ub=-1,
>                     add_gt_as_proposals=True),
>                 mask_size=28,
>                 pos_weight=-1,
>                 debug=False),
>             dict(
>                 assigner=dict(
>                     type='MaxIoUAssigner',
>                     pos_iou_thr=0.7,
>                     neg_iou_thr=0.7,
>                     min_pos_iou=0.7,
>                     match_low_quality=False,
>                     ignore_iof_thr=-1),
>                 sampler=dict(
>                     type='RandomSampler',
>                     num=512,
>                     pos_fraction=0.25,
>                     neg_pos_ub=-1,
>                     add_gt_as_proposals=True),
>                 mask_size=28,
>                 pos_weight=-1,
>                 debug=False)
>         ]),
>     test_cfg=dict(
>         rpn=dict(
>             nms_pre=1000,
>             max_per_img=1000,
>             nms=dict(type='nms', iou_threshold=0.7),
>             min_bbox_size=0),
>         rcnn=dict(
>             score_thr=0.05,
>             nms=dict(type='nms', iou_threshold=0.5),
>             max_per_img=100,
>             mask_thr_binary=0.5)))
> ```

what did you change ?

**Comment by jbwang1997** [comment]
> > Change the config file like this.
> > # model settings
> > ```
> > model = dict(
> >     type='CascadeRCNN',
> >     backbone=dict(
> >         type='ResNet',
> >         depth=50,
> >         num_stages=4,
> >         out_indices=(0, 1, 2, 3),
> >         frozen_stages=1,
> >         norm_cfg=dict(type='BN', requires_grad=True),
> >         norm_eval=True,
> >         style='pytorch',
> >         init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
> >     neck=dict(
> >         type='FPN',
> >         in_channels=[256, 512, 1024, 2048],
> >         out_channels=256,
> >         num_outs=5),
> >     rpn_head=dict(
> >         type='RPNHead',
> >         in_channels=256,
> >         feat_channels=256,
> >         anchor_generator=dict(
> >             type='AnchorGenerator',
> >             scales=[8],
> >             ratios=[0.5, 1.0, 2.0],
> >             strides=[4, 8, 16, 32, 64]),
> >         bbox_coder=dict(
> >             type='DeltaXYWHBBoxCoder',
> >             target_means=[.0, .0, .0, .0],
> >             target_stds=[1.0, 1.0, 1.0, 1.0]),
> >         loss_cls=dict(
> >             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
> >         loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
> >     roi_head=dict(
> >         type='CascadeRoIHead',
> >         num_stages=3,
> >         stage_loss_weights=[1, 0.5, 0.25],
> >         bbox_roi_extractor=dict(
> >             type='SingleRoIExtractor',
> >             roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
> >             out_channels=256,
> >             featmap_strides=[4, 8, 16, 32]),
> >         bbox_head=[
> >             dict(
> >                 type='Shared2FCBBoxHead',
> >                 in_channels=256,
> >                 fc_out_channels=1024,
> >                 roi_feat_size=7,
> >                 num_classes=1,
> >                 bbox_coder=dict(
> >                     type='DeltaXYWHBBoxCoder',
> >                     target_means=[0., 0., 0., 0.],
> >                     target_stds=[0.1, 0.1, 0.2, 0.2]),
> >                 reg_class_agnostic=True,
> >                 loss_cls=dict(
> >                     type='CrossEntropyLoss',
> >                     use_sigmoid=False,
> >                     loss_weight=1.0),
> >                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
> >                                loss_weight=1.0)),
> >             dict(
> >                 type='Shared2FCBBoxHead',
> >                 in_channels=256,
> >                 fc_out_channels=1024,
> >                 roi_feat_size=7,
> >                 num_classes=1,
> >                 bbox_coder=dict(
> >                     type='DeltaXYWHBBoxCoder',
> >                     target_means=[0., 0., 0., 0.],
> >                     target_stds=[0.05, 0.05, 0.1, 0.1]),
> >                 reg_class_agnostic=True,
> >                 loss_cls=dict(
> >                     type='CrossEntropyLoss',
> >                     use_sigmoid=False,
> >                     loss_weight=1.0),
> >                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
> >                                loss_weight=1.0)),
> >             dict(
> >                 type='Shared2FCBBoxHead',
> >                 in_channels=256,
> >                 fc_out_channels=1024,
> >                 roi_feat_size=7,
> >                 num_classes=1,
> >                 bbox_coder=dict(
> >                     type='DeltaXYWHBBoxCoder',
> >                     target_means=[0., 0., 0., 0.],
> >                     target_stds=[0.033, 0.033, 0.067, 0.067]),
> >                 reg_class_agnostic=True,
> >                 loss_cls=dict(
> >                     type='CrossEntropyLoss',
> >                     use_sigmoid=False,
> >                     loss_weight=1.0),
> >                 loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
> >         ],
> >         mask_roi_extractor=dict(
> >             type='SingleRoIExtractor',
> >             roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
> >             out_channels=256,
> >             featmap_strides=[4, 8, 16, 32]),
> >         mask_head=dict(
> >             type='FCNMaskHead',
> >             num_convs=4,
> >             in_channels=256,
> >             conv_out_channels=256,
> >             num_classes=1,
> >             loss_mask=dict(
> >                 type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
> >     # model training and testing settings
> >     train_cfg=dict(
> >         rpn=dict(
> >             assigner=dict(
> >                 type='MaxIoUAssigner',
> >                 pos_iou_thr=0.7,
> >                 neg_iou_thr=0.3,
> >                 min_pos_iou=0.3,
> >                 match_low_quality=True,
> >                 ignore_iof_thr=-1),
> >             sampler=dict(
> >                 type='RandomSampler',
> >                 num=256,
> >                 pos_fraction=0.5,
> >                 neg_pos_ub=-1,
> >                 add_gt_as_proposals=False),
> >             allowed_border=0,
> >             pos_weight=-1,
> >             debug=False),
> >         rpn_proposal=dict(
> >             nms_pre=2000,
> >             max_per_img=2000,
> >             nms=dict(type='nms', iou_threshold=0.7),
> >             min_bbox_size=0),
> >         rcnn=[
> >             dict(
> >                 assigner=dict(
> >                     type='MaxIoUAssigner',
> >                     pos_iou_thr=0.5,
> >                     neg_iou_thr=0.5,
> >                     min_pos_iou=0.5,
> >                     match_low_quality=False,
> >                     ignore_iof_thr=-1),
> >                 sampler=dict(
> >                     type='RandomSampler',
> >                     num=512,
> >                     pos_fraction=0.25,
> >                     neg_pos_ub=-1,
> >                     add_gt_as_proposals=True),
> >                 mask_size=28,
> >                 pos_weight=-1,
> >                 debug=False),
> >             dict(
> >                 assigner=dict(
> >                     type='MaxIoUAssigner',
> >                     pos_iou_thr=0.6,
> >                     neg_iou_thr=0.6,
> >                     min_pos_iou=0.6,
> >                     match_low_quality=False,
> >                     ignore_iof_thr=-1),
> >                 sampler=dict(
> >                     type='RandomSampler',
> >                     num=512,
> >                     pos_fraction=0.25,
> >                     neg_pos_ub=-1,
> >                     add_gt_as_proposals=True),
> >                 mask_size=28,
> >                 pos_weight=-1,
> >                 debug=False),
> >             dict(
> >                 assigner=dict(
> >                     type='MaxIoUAssigner',
> >                     pos_iou_thr=0.7,
> >                     neg_iou_thr=0.7,
> >                     min_pos_iou=0.7,
> >                     match_low_quality=False,
> >                     ignore_iof_thr=-1),
> >                 sampler=dict(
> >                     type='RandomSampler',
> >                     num=512,
> >                     pos_fraction=0.25,
> >                     neg_pos_ub=-1,
> >                     add_gt_as_proposals=True),
> >                 mask_size=28,
> >                 pos_weight=-1,
> >                 debug=False)
> >         ]),
> >     test_cfg=dict(
> >         rpn=dict(
> >             nms_pre=1000,
> >             max_per_img=1000,
> >             nms=dict(type='nms', iou_threshold=0.7),
> >             min_bbox_size=0),
> >         rcnn=dict(
> >             score_thr=0.05,
> >             nms=dict(type='nms', iou_threshold=0.5),
> >             max_per_img=100,
> >             mask_thr_binary=0.5)))
> > ```
> 
> what did you change ?

Github support the markdown syntax. I add ``` before and after the code.

**Comment by jbwang1997** [comment]
Hello. I am going to close this issue. Feel free to reopen it if you have any questions.
