### ISSUE TITLE
Can I set different optimizers  for different layers of the model? 

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#7577]
For example, I set Adam optimizer for Conv1, and set SGD optimizer for Conv2......
Thank you very much!

**Comment by RangiLyu** [comment]
You can implement an [OptimizerConstructor](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/optimizer/default_constructor.py) and an OptimizerWrapper to support multi optimizers.
