### ISSUE TITLE
Add Mask2Former to the Model Zoo

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#7580]
**Add Mask2Former to the Model Zoo**

**Motivation**
I see that with release 2.3.0 you added [Mask2Former](https://github.com/open-mmlab/mmdetection/tree/v2.23.0/configs/mask2former). That is great! However it would be nice to have an entry in Model Zoo, or at least a table with results, like you did for [EfficientNet](https://github.com/open-mmlab/mmdetection/pull/7514). Also, a short tutorial or even just a config on how to use it for instance segmentation, instead than panoptic (most datasets "in the wild" don't have panoptic labels), would be great. Thanks!

**Comment by RangiLyu** [comment]
Mask2Former is a pre-release version now, and the pre-trained weights will be released soon.

**Comment by rabiaedayilmaz** [comment]
Hi, I've been training Mask2Former w/ ResNet50 for more than 30 minutes but there is no output. I tried Mask R-CNN w/ ResNet50 and it works, though. Could you help me, please?

**Comment by Jingtao-Li-CVer** [comment]
> Mask2Former is a pre-release version now, and the pre-trained weights will be released soon.

Have you released the checkpoints?
