### ISSUE TITLE
How to change saved checkpoints between different devices easily?

### ISSUE THREAD

**Issue by bzfather** [open-mmlab/mmdetection#7583]
For example, I trained on cuda:1 in a multi-gpu device and I want to run it on other device with one gpu.
When it runs `model.init_weights()`, it shows that **Attempting to deserialize object on CUDA device 1 but torch.deivce_count is 1**
It truely can be solved by`map_location={cuda:1:cuda0}`, but it's need to edit the deep code. And when I change to the other devices, it needs to be edited again.
Is there some way I can save the checkpoints file in a general format?
ps. I directly used the checkpoints saved during trainning,i.e. xxxepoch_10.pth

**Comment by jbwang1997** [comment]
Sorry, I don't get your question. mmdetection will put the model to corresponding device according to the --gpu-id.

**Comment by jbwang1997** [comment]
Hello. I am going to close this issue. Feel free to reopen it if you have any questions.
