### ISSUE TITLE
about nms implementation 

### ISSUE THREAD

**Issue by Joll123** [open-mmlab/mmdetection#7587]
Since I couldn't find the NMS implementation details in your code, I wrote the NMS implementation. But the results are different, so very curious about your NMS implementation. I would be greatly appreciated if you could explain the NMS implementation in your code.

your nms code is located on line 26 of mmcv.ops.nms.py.
inds = ext_module.nms(
            bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)

**Comment by jbwang1997** [comment]
The `nms` is written by C++ in mmcv. you can refer to [CPU version nms](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/pytorch/cpu/nms.cpp) for details.
