### ISSUE TITLE
__init__() got an unexpected keyword argument 'pretrained'

### ISSUE THREAD

**Issue by lai-serena** [open-mmlab/mmdetection#7592]
**Describe the bug**
__init__() got an unexpected keyword argument 'pretrained'

**Environment**
Ubuntu 18.04
CUDA 10.1
mmdet 2.8.0
mmcv-full 1.2.7
pytorch 1.7.1

**Code**
```
from mmdet.models.backbones import ResNet
import torch

pretrained="torchvision://resnet101"

try:
    resnet101=ResNet(101,pretrained=pretrained)
    inputs = torch.rand(1, 3, 512, 512)
    level_outputs = resnet101.forward(inputs)
    for level_out in level_outputs:
        print(tuple(level_out.shape))
except Exception as e:
    print(e)
```
After running the above code:
```__init__() got an unexpected keyword argument 'pretrained'```
I don't know why such a mistake occurred.Because this keyword exists in the initialization function.
View function "/work/lyx_file/mmdetection/mmdet/models/backbones/resnet.py":
```
def __init__(self,
                 depth,
                 in_channels=3,
                 stem_channels=None,
                 base_channels=64,
                 num_stages=4,
                 strides=(1, 2, 2, 2),
                 dilations=(1, 1, 1, 1),
                 out_indices=(0, 1, 2, 3),
                 style='pytorch',
                 deep_stem=False,
                 avg_down=False,
                 frozen_stages=-1,
                 conv_cfg=None,
                 norm_cfg=dict(type='BN', requires_grad=True),
                 norm_eval=True,
                 dcn=None,
                 stage_with_dcn=(False, False, False, False),
                 plugins=None,
                 with_cp=False,
                 zero_init_residual=True,
                 pretrained=None,
                 init_cfg=None):
        super(ResNet, self).__init__(init_cfg)
        self.zero_init_residual = zero_init_residual
        if depth not in self.arch_settings:
            raise KeyError(f'invalid depth {depth} for resnet')
```

**Comment by RangiLyu** [comment]
Your environment shows that you are using mmdetection 2.8.0.
But in 2.8.0, ResNet has no `pretrained` argument.
See https://github.com/open-mmlab/mmdetection/blob/v2.8.0/mmdet/models/backbones/resnet.py#L363

Please make sure the mmdet you installed and the one you are editing are the same version.
You can try to run `pip install -e .` or `python setup.py develop` in your mmdetection folder to solve this problem.

**Comment by lai-serena** [comment]
Ok,Thank you!

**Comment by cccat-best** [comment]
@RangiLyu 旧版本的mmdet好像都安装不成功

**Comment by cccat-best** [comment]
> **描述错误** **init** () 获得了意外的关键字参数 'pretrained'
> 
> **环境** Ubuntu 18.04 CUDA 10.1 mmdet 2.8.0 mmcv-full 1.2.7 pytorch 1.7.1
> 
> **代码**
> 
> ```
> from mmdet.models.backbones import ResNet
> import torch
> 
> pretrained="torchvision://resnet101"
> 
> try:
>     resnet101=ResNet(101,pretrained=pretrained)
>     inputs = torch.rand(1, 3, 512, 512)
>     level_outputs = resnet101.forward(inputs)
>     for level_out in level_outputs:
>         print(tuple(level_out.shape))
> except Exception as e:
>     print(e)
> ```
> 
> 运行上面的代码后： `__init__() got an unexpected keyword argument 'pretrained'` 我不知道为什么会出现这样的错误。因为初始化函数中存在这个关键字。 查看函数“/work/lyx_file/mmdetection/mmdet/models/backbones/resnet.py”：
> 
> ```
> def __init__(self,
>                  depth,
>                  in_channels=3,
>                  stem_channels=None,
>                  base_channels=64,
>                  num_stages=4,
>                  strides=(1, 2, 2, 2),
>                  dilations=(1, 1, 1, 1),
>                  out_indices=(0, 1, 2, 3),
>                  style='pytorch',
>                  deep_stem=False,
>                  avg_down=False,
>                  frozen_stages=-1,
>                  conv_cfg=None,
>                  norm_cfg=dict(type='BN', requires_grad=True),
>                  norm_eval=True,
>                  dcn=None,
>                  stage_with_dcn=(False, False, False, False),
>                  plugins=None,
>                  with_cp=False,
>                  zero_init_residual=True,
>                  pretrained=None,
>                  init_cfg=None):
>         super(ResNet, self).__init__(init_cfg)
>         self.zero_init_residual = zero_init_residual
>         if depth not in self.arch_settings:
>             raise KeyError(f'invalid depth {depth} for resnet')
> ```

Hello, have you solved this problem?

**Comment by cccat-best** [comment]
@lai-serena
