### ISSUE TITLE
Script for converting weights for YOLOX-m and YOLOX-nano

### ISSUE THREAD

**Issue by excitohe** [open-mmlab/mmdetection#7593]
Hi, I check the YOLOX dirs and find yolo-x/yolo-l/yolo-s/yolo-tiny, I want to use YOLOX-Megvii training weight (YOLOX-m and YOLOX-nano), could you provide a script that can convert weights from Megvii to MMDet?
Thx.

**Comment by RangiLyu** [comment]
Sorry, we have no such script. You can try to convert the key in the state dict manually. It's not so hard.

**Comment by excitohe** [comment]
ok, i see thanks.

**Comment by LRY89757** [comment]
@excitohe Could you share your script with me? thx!

**Comment by haiyang-tju** [comment]
[``](https://github.com/haiyang-tju/dl_tools/blob/9b476231cb9ee4458e94cb31fbddfdec5c0a6059/megvii_nano_2_mmdet.py#L2)

ref

**Comment by ALPAHz** [comment]
I want to use YOLOX-m training weight ,could you share your script with me?Thanks! @excitohe
