### ISSUE TITLE
why xml_style is not return the key “masks” and “seg_map”，As a result, the VOC data type cannot be trained using instance segmentation mask_rcnn.

### ISSUE THREAD

**Issue by liuyunfeng2016** [open-mmlab/mmdetection#7596]
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/xml_style.py#L150，

I think he should be consistent with Coco.

https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L199

**Comment by RangiLyu** [comment]
Currently, the xml dataset does not support instance segmentation. It's better to convert to coco format if you want to train an instance segmentation model.

**Comment by liuyunfeng2016** [comment]
> Currently, the xml dataset does not support instance segmentation. It's better to convert to coco format if you want to train an instance segmentation model.

https://github.com/open-mmlab/mmdetection/blob/master/tools/dataset_converters/pascal_voc.py#L123

However, this conversion is problematic, only the rectangle box is converted, not the split point.
