### ISSUE TITLE
Need a kind of RPN Heads for different class in dataset do detection and regression

### ISSUE THREAD

**Issue by FarranYang** [open-mmlab/mmdetection#7600]
**Describe the feature**

**Motivation**
我想实现一个这样的功能，检测头一对A类别的物体进行分类和回归，检测头二对B类别的物体进行分类和回归
也就是不同的class走不同的RPNHead。如果没有这样的head，我应该从哪入手修改已有的head类呢？我打算自己实现一下。

**Related resources**
1.我目前想从basedensehead中修改数据类别的来源，以达到类别筛选的目的，您有什么可行性更高的解决方案吗？如果能有一些参考资料就更加好了！谢谢！

**Comment by RangiLyu** [comment]
At present, we have no similar cases for reference. Just have a try!
