### ISSUE TITLE
using my own custom dataset

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#7601]
Hello , 
I would like to ask regards using a custom dataset for detection objects. 
I have the dataset in one folder and i have one json file for annotation. 

I did the split of the dataset (images ) into three folders ; train,test and val but i still have the one json file to used in the training. 

unfortunately , when I run the following code of visualization the dataset  ,
`python tools/misc/browse_dataset.py`

 I faced this issue: 

![uuu](https://user-images.githubusercontent.com/10245810/161086987-a9ee7598-6ddd-4ac0-a193-29ee236f287e.jpg)

after compare it with my previous work , i understood that it happened because of having one json file for the three folders of images , (seems that it searching form image 00001.jpg in folder train which did not contain it). my new train folder contains only 2280 images ,and 2280 annotation xml files. while the whole dataset contains 2850 images. 

I am working on a dataset with COCO format , and i want to work with the json file . that means , i need to split the json file also according to images in each folder. 

any suggestion for help in this direction ? is there any way to split the json file similar to what i have done in images? 
or even is there a way to convert all xml files into jsons files that have similar form of coco dataset ,without making it by hand? 

thanks .

**Comment by zehranrgi** [comment]
For the coco format, you should create .json format separately for train val and set... 
You may try this one [CocoSplit](https://github.com/akarazniewicz/cocosplit). 

I didn't understand why you don't have enough XML files for your images.

**Comment by alaa-shubbak** [comment]
> 
it is not like i don't have enough XML files for annotation my images ,  I have them all within my image folders , but the point that i read the annotations from one json file for all images in three folders.

**Comment by alaa-shubbak** [comment]
thanks , I will try the split code that you have. I hope it will work.

**Comment by alaa-shubbak** [comment]
Thank you very much , It seems it is working now. I used it twice to create 3 splitted json files.

**Comment by zehranrgi** [comment]
You're welcome.
