### ISSUE TITLE
Fail to add 'score_thr' in detr and sparse r-cnn

### ISSUE THREAD

**Issue by dododo0611** [open-mmlab/mmdetection#7614]
I have used sparse r-cnn and detr model to achieve good AP in my own dataset. However, when I check the results, there are a bunch of false positive samples. I think this is because there are 100 proposals and I do not eliminate predictions with low confidence score. I try to add 'score_thr' in test_cfg but it doesn't work. What should I do to reduce FP? Thanks!

**Comment by chhluo** [comment]
You can pass a high value to `--show-score-thr` (defualt 0.3) in test.py to filter prediction with low confidence score. See, https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/tools/test.py#L65

**Comment by dododo0611** [comment]
> 

Thanks for your answer! But I do not need to visualize the results and I just want to count the number of false negative samples for a report. Can I filter those predictions with low confidence score in inference?

**Comment by dododo0611** [comment]
> You can pass a high value to `--show-score-thr` (defualt 0.3) in test.py to filter prediction with low confidence score. See,
> 
> https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/tools/test.py#L65

Thanks for your answer! But I do not need to visualize the results and I just want to count the number of false negative samples for a report. Can I filter those predictions with low confidence score in inference?

**Comment by chhluo** [comment]
For example, you can add some code to filter low confidence scores before return https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/dense_heads/detr_head.py#L683.
add `score_thr` in test_cfg and use it like https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/dense_heads/detr_head.py#L660

**Comment by dododo0611** [comment]
> For example, you can add some code to filter low confidence scores before return
> 
> https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/dense_heads/detr_head.py#L683
> 
> .
> add `score_thr` in test_cfg and use it like
> https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/dense_heads/detr_head.py#L660

Sorry for being late! It seems that I have succeeded to add `score_thr` for sparse r-cnn by using a index filter.
Before:
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/roi_heads/sparse_roi_head.py#L360-L362
After:
```
filter_idx = torch.squeeze(
                scores_per_img[:, None] > self.test_cfg.score_thr)
det_bboxes.append(
                torch.cat([bbox_pred_per_img, scores_per_img[:, None]], dim=1)[filter_idx])
det_labels.append(labels_per_img[filter_idx])
```
I think it's correct and it works for my project. Thanks!
