### ISSUE TITLE
How to init two models

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection#7615]
Hi. I am going to do some researches about distillation. I wonder how to initialize two networks and feed data into them separately?

**Comment by chhluo** [comment]
an immature idea：
suppose we have a KD class which contains a student network and teacher network:  1) we train a teacher model by train script provided in mmdet; 2) we pass the config and checkpoint of teacher model into the KD class, then build the teacher network and initialize the teacher network in a way like https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/tools/test.py#L221, 3) pass a sample to forward method of the KD class, do forward of teacher network and student network, then compute loss of student network.

**Comment by chhluo** [comment]
Kindly ping @Czm369 , Could you please provide any suggestions?

**Comment by Czm369** [comment]
Maybe you can refer to https://github.com/open-mmlab/mmrazor/blob/master/configs/distill/cwd/cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco.py

**Comment by CheungBH** [comment]
> Maybe you can refer to https://github.com/open-mmlab/mmrazor/blob/master/configs/distill/cwd/cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco.py

Thank you for your reply. In fact, I am still feeling confused about the steps. It means that I need to use mmrazor instead of mmdetection, right?

**Comment by CheungBH** [comment]
> an immature idea： suppose we have a KD class that contains a student network and teacher network: 1) we train a teacher model by train script provided in mmdet; 2) we pass the config and checkpoint of the teacher model into the KD class, then build the teacher network and initialize the teacher network in a way like
> 
> https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/tools/test.py#L221
> 
> , 3) pass a sample to forward method of the KD class, do forward of teacher network and student network, then compute the loss of student network.

Thank you. The steps may be: I initialized a DistillationDetector, which contains the teacher and student models; In its forward function, I finish the forwarding operations for the two networks, and computer the loss. Is it right?

**Comment by chhluo** [comment]
yes
