### ISSUE TITLE
[Serving Error] latest torchserve does not support torch<1.8.1

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmdetection#7623]
**Describe the bug**
Because torchserve uses torch.profiler since version 0.2.0, the current docker/serve/Dockerfile throws an error.
See https://github.com/pytorch/serve/issues/1548

**Bug fix**
There are three options below
1. Upgrade the version of torch>=1.8.1
2. Limit the version of torchserve==0.2.0
3. Wait for the latest torchserve to fix the issue.

I choose the second one for the PR in mmrotate https://github.com/open-mmlab/mmrotate/pull/160.

**Comment by ZwwWayne** [comment]
Should be fixed if torchserve is upgraded.
