### ISSUE TITLE
keep_empty logic in FilterAnnotations

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#7628]
Hi @hhaAndroid, sorry for bringing up a [merged PR](https://github.com/open-mmlab/mmdetection/pull/6443).

Can I understand why the `keep_empty` logic is [implemented as such](https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/pipelines/loading.py#L595-L599) in `FilterAnnotations`? 

What I understand from the code, if there are no ground truths left after the filtering, depending on `self.keep_empty` we will either: 
1) `return None`, this "erases" the image entirely, and will throw errors in downstream pipeline transformations.
2) `return results`, this basically returns the `results` without any modification/filtering. 

This does not really make sense to me, if anything, we should be returning the results dictionary with only the ground-truths (`gt_bboxes`, `gt_labels`, `gt_masks`, etc) set to empty lists?

**Comment by levan92** [comment]
I believe the errors other people faced like this: https://github.com/open-mmlab/mmdetection/pull/6282#issuecomment-1002887805 is due to this as well

**Comment by hhaAndroid** [comment]
@levan92 Thanks for your feedback, there is something wrong with this naming. Maybe we should rename it to `return_none_with_empty` ?  do you have a better suggestion？

**Comment by levan92** [comment]
Agree that it should be renamed to something like `return_none_if_empty`. 

`keep_empty` is a misnomer, which ironically the effect is that it will **not** keep empty images, when used with dataset wrapper `MultiImageMixDataset`, if None is returned from `FilterAnnotation`, it will keep repeating the same operation and eventually throw an error.  

The default behaviour of `keep_empty=True` does not really make sense to me anyway as well. I think by default `FilterAnnotation` should not return None and instead should return with `gt_bboxes`, etc as empty lists.
