### ISSUE TITLE
EfficientNet-b3 with RetinaNet pretrained model download link not exist

### ISSUE THREAD

**Issue by Jaisme** [open-mmlab/mmdetection#7632]
I would like to train with the newest released Backbone EfficientNet with the configuration provided, but the download link for the pretrained model weights in the [README file](https://github.com/open-mmlab/mmdetection/blob/master/configs/efficientnet/README.md) does not seem to exist. 

Is there a pretrained model weight? If so, could you please fix the link. Many thanks!!

**Comment by jbwang1997** [comment]
Hi @Jaisme. The pretrained model hasn't been released yet. We will upload the efficientnet+FPN model as soon as possible.

**Comment by Jaisme** [comment]
Ah ok, thanks for your reply!

**Comment by erwangccc** [comment]
@jbwang1997 @Jaisme 
Hi, there. Are there any updates on this issue. have you release the pretrained model?
