### ISSUE TITLE
How to apply Empirical Attention on Res2Net??

### ISSUE THREAD

**Issue by TalentedMUSE** [open-mmlab/mmdetection#7634]
![image](https://user-images.githubusercontent.com/39563262/161569019-be943056-ba1c-4dfd-8bbf-f06e8c8ec3f9.png)
When I plugged attention into Res2Net, like the above img shows, I got such error:
`RuntimeError: Given groups=1, weight of size [104, 104, 1, 1], expected input[2, 416, 50, 68] to have 104 channels, but got 416 channels instead`
How to apply it in Res2Net? Urgent!!! Thanks for your reply~~~~

**Comment by Czm369** [comment]
Maybe you can refer to https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/groie/mask_rcnn_r101_fpn_syncbn-backbone_r4_gcb_c3-c5_groie_1x_coco.py

**Comment by TalentedMUSE** [comment]
> Maybe you can refer to https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/empirical_attention/faster_rcnn_r50_fpn_attention_1111_dcn_1x_coco.py

Thank u, I managed to solve this problem. It seems that [Gen_Att] can only support 'after_conv3' for Res2Net.

**Comment by sanmulab** [comment]
Hi! How much has the accuracy improved after adding Empirical Attention?

> > Maybe you can refer to https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/empirical_attention/faster_rcnn_r50_fpn_attention_1111_dcn_1x_coco.py
> 
> Thank u, I managed to solve this problem. It seems that [Gen_Att] can only support 'after_conv3' for Res2Net.
