### ISSUE TITLE
/mmdetection/mmdet/core/visualization/image.py, line:353

### ISSUE THREAD

**Issue by JustDoItY** [open-mmlab/mmdetection#7636]
**bug description**
this is a bug , create one  mistake. height*wight*4 is not equaled to buffer.size.i don't know why make that. it lead a bug.

**fix**
i fill the left space with zeros.
    buffer = np.frombuffer(stream, dtype='uint8')
    size_image = height*width*4
    if (buffer.size < size_image):
        temp = np.zeros(size_image,)
        temp[:buffer.size] = buffer
        buffer = temp
    else:
        buffer = buffer[:size_image]
    img_rgba = buffer.reshape(height, width, 4)

**Comment by hhaAndroid** [comment]
@JustDoItY Please use the issue template.
