### ISSUE TITLE
How to calculate the AP50 of each category of coco dataset?

### ISSUE THREAD

**Issue by Y-M-Y** [open-mmlab/mmdetection#7637]
The current mmdet2.23 supports calculating map[0.5:0.95] for each class. The method is to set `classwise=true` under `mmdet/datasets/coco.py`. However, when I want to debug the `mmdet/datasets/coco.py` to calculate ap50 of each class, I found that the variable `precisions` in `line554` does not contain ap50. Is there a method to print the ap50 of each class?

**Comment by hhaAndroid** [comment]
@Y-M-Y You can set  classwise=true and iou_thrs=[0.5]
