### ISSUE TITLE
make `mmdet.apis.init_detector` work with pathlib

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmdetection#7649]
**Describe the feature**
make `mmdet.apis.init_detector` work with pathlib 
**Motivation**
Since mmcv works with pathlib, there is no reason to use str path only. (ref https://github.com/open-mmlab/mmcv/issues/3).
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/apis/inference.py#L31

**Comment by hubutui** [comment]
and mmseg, mmcls:
https://github.com/open-mmlab/mmclassification/blob/5a67bc8a1aefd5493732b8f6ab10ee8c04839773/mmcls/apis/inference.py#L27

https://github.com/open-mmlab/mmsegmentation/blob/4bd32f4c3dec15b54e64197570edc3ab3fdcf164/mmseg/apis/inference.py#L25

**Comment by jbwang1997** [comment]
Thanks for your valuable suggestion. we will plan to do this. It's also very appreciated if you would like to apply this function. Do you have a plan to make a pr in mmdetection?
