### ISSUE TITLE
Regarding custom instance segmentation pipelines, what to modify

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#7650]
Hello,

Based on what I am seeing from other augmentation pipelines already in mmdetection, it would appear that all we are interested in modifying is `results['img']`, `results['gt_masks'].masks`, `results['gt_labels']`, and `results['gt_bboxes']` when implementing custom augmentation for instance segmentation, correct?

The reason I ask is because it appears that `results['gt_masks']` contains the same masks encoded in different ways (i.e. binary masks in `results['gt_masks'].masks` and RLEs). I believe you are only using `results['gt_masks'].masks` to compute loss; is this correct? Is this due to a config setting?

Additionally, given that the mask/bboxs may change in my pipeline, I thought to change the area, RLEs etc. values, but I do not believe these have any effect on training, so I have been leaving them the same even after modifying my masks and bboxes (this also helps speed up my augmentation pipeline). I may be incorrect in doing so; any advice would be appreciated.

I appreciate any help you can provide on these questions.

**Comment by jbwang1997** [comment]
The type of `results['gt_masks']` can be `BitmapMasks` or `PolygonMasks` . They have different storage method in `results['gt_masks'].masks`. But, we provide the same io in `BitmapMasks` and `PolygonMasks` so that we can unify the operations in pipelines.

**Comment by pcicales** [comment]
@jbwang1997 I am not sure I understand. Currently, I am modifying `BitmapMasks` ; under what circumstances are `PolygonMasks` used?

**Comment by jbwang1997** [comment]
Sorry for missing understanding your question. The most basic items in pipeline results are `img`, `gt_bboxes`, `gt_masks`, `gt_masks`, 'gt_bboxes_ignore`. If you have handled those items in your custom augmentation, its function is most likely right. But in some cases, there are some other items like `gt_semantic_seg` in the results. Please pay attention.

As for the mask type, mmdetection loads masks as `BitmapMasks` or `PolygonMasks`. On most occasions, the mask type is BitmapMasks.
