### ISSUE TITLE
How to use fp16 to train a model?

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdetection#7652]
In mmdet, is it default to train a model in fp32? How can I train a model in fp16?

**Comment by RangiLyu** [comment]
You can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_fp16_1x_coco.py

You can also set `fp16 = dict(loss_scale='dynamic')` to enable auto loss scaling.
