### ISSUE TITLE
Any plans to implement WBF in MMDet?

### ISSUE THREAD

**Issue by boom109** [open-mmlab/mmdetection#7653]
I've already checked posts on **WBF(Weighted Box Fusion)** related topics in Problems, but couldn't find the answer I was looking for.

Do you currently have any plans to add a WBF solution within MMDet?

Our team are currently considering applying WBF with an ensemble model. However, I know that MMDet does not have features that consider ensemble models.
However, MMDet understands that TTA is possible, so it is considering applying WBF after TTA as an alternative method.

If I want to implement WBF myself, can I add it by referring to the bbox_nms code? Also are there any guidelines for doing this?

**Related resources**
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/post_processing/bbox_nms.py

thanks.

**Comment by RangiLyu** [comment]
It is not in our plan. 
The original implementation of [WBF](https://github.com/ZFTurbo/Weighted-Boxes-Fusion) is very easy to use. You can just convert the prediction box format in mmdet to a list of boxes, scores, and labels and pass them into the `weighted_boxes_fusion` function.

**Comment by boom109** [comment]
I understand that there are no plans to include that functionality in the framework.
We plan to apply what you described. Please refer to those who will use WBF in the future.
thanks~

[WBF](https://github.com/ZFTurbo/Weighted-Boxes-Fusion)

```python
from ensemble_boxes import *

# TODO: inference from model using MMDet

# TODO: convert format bbox, score, and labels ... 

# applying WBF
boxes, scores, labels = weighted_boxes_fusion([boxes_list], [scores_list], [labels_list], weights=None, method=method, iou_thr=iou_thr, thresh=thresh)
```

**Comment by diadestiny** [comment]
> I understand that there are no plans to include that functionality in the framework. We plan to apply what you described. Please refer to those who will use WBF in the future. thanks~
> 
> [WBF](https://github.com/ZFTurbo/Weighted-Boxes-Fusion)
> 
> ```python
> from ensemble_boxes import *
> 
> # TODO: inference from model using MMDet
> 
> # TODO: convert format bbox, score, and labels ... 
> 
> # applying WBF
> boxes, scores, labels = weighted_boxes_fusion([boxes_list], [scores_list], [labels_list], weights=None, method=method, iou_thr=iou_thr, thresh=thresh)
> ```

hi, can you show an example code to show how to get the boxes, scores, labels by your mmdetection model
now I am using swin-transformer as mmdetection model, and I hope to use WBF module, but I can't find the api to get boxes, scores, labels

**Comment by boom109** [comment]
@diadestiny 
please check the following documentation.
https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html

we can use the tools or code 

* tools
./tools/test.py
or
./tools/dist_test.sh

* code
using mmdet api
 https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html#high-level-apis-for-inference
