### ISSUE TITLE
Best way to measure inference time

### ISSUE THREAD

**Issue by Unlucky910** [open-mmlab/mmdetection#7660]
Hi Guys,

i am kinda new to mmdetection and i am wondering what is the best way to measure the inference time of a model?.

More specific, what script do i need to use to get the inference time from models like on this page
https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html#results-and-models

**Comment by RangiLyu** [comment]
For pytorch model, you can use tools/analysis_tools/benchmark.py
For ONNX model, you can try https://github.com/open-mmlab/mmdeploy. MMDeploy provides a script to measure the inference time with multi-backend support.

**Comment by Unlucky910** [comment]
When i use tools/analysis_tools/benchmark.py i get the follow Error:

i know you can specify the reank with ----local_rank if you start the script.

Can somebody please help me?

anaconda3/envs/open-mmlab/lib/python3.7/os.py", line 682, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

Kind regards

**Comment by RangiLyu** [comment]
Please follow the document https://mmdetection.readthedocs.io/en/latest/useful_tools.html#benchmark
