### ISSUE TITLE
Get  precision and recall of specific IoU

### ISSUE THREAD

**Issue by faruqsandi** [open-mmlab/mmdetection#7662]
Sorry, I am not familiar with mmdetection and IoU, and please forgive me for this dumb question.
How do I get these values (IoU, precision, recall) from mmdetection so that I can plot it?

![88AD8B0F-0334-4DDA-BFD3-FD8BB7873E15](https://user-images.githubusercontent.com/965723/162346010-d34a0891-59ce-4349-a1cf-236ebacb7629.png)

Thank you very much!

-------
edit: I am using coco dataset format.

**Comment by BIGWangYuDong** [comment]
Hi, seems that we are not supported yet. But I think you can follow `tools/anaysis_tools/coco_error_analysis.py`, `precision` and `recall` can get from `cocoEval.eval['precision']` and `cocoEval.eval['recall']`.
As for IoU, `cocoEval.params.iouThrs = xxx` can be used to set iou_thr

**Comment by faruqsandi** [comment]
Thank you very much for the swift reply @BIGWangYuDong! I will try to start with that.

**Comment by serser** [comment]
how is this pr going?
