### ISSUE TITLE
Possible error in mmdet/datasets/pipelines/transforms.py

### ISSUE THREAD

**Issue by nestiank** [open-mmlab/mmdetection#7665]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

In the file linked below, L265\~269 and L271\~L275 is same.
As L257 and L259 is different, maybe L273 should be changed alike L259. (**I am not sure!**)
If it shouldn't be changed, then removing `if` branch would make tiny increase of performance.
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L264

**Reproduction**

1. What command or script did you run?

```python
def _resize_masks(self, results):
    """Resize masks with ``results['scale']``"""
    for key in results.get('mask_fields', []):
        if results[key] is None:
            continue
        if self.keep_ratio:
            results[key] = results[key].rescale(results['scale'])        #L257
        else:
            results[key] = results[key].resize(results['img_shape'][:2]) #L259

def _resize_seg(self, results):
    """Resize semantic segmentation map with ``results['scale']``."""
    for key in results.get('seg_fields', []):
        if self.keep_ratio:
            gt_seg = mmcv.imrescale(     #L265
                results[key],            #L266
                results['scale'],        #L267
                interpolation='nearest', #L268
                backend=self.backend)    #L269
        else:
            gt_seg = mmcv.imresize(      #L271
                results[key],            #L272
                results['scale'],        #L273
                interpolation='nearest', #L274
                backend=self.backend)    #L275
        results[key] = gt_seg
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

(pass)

3. What dataset did you use?

(pass)

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

(pass; unnecessary)

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

(pass; unnecessary)

**Error traceback**
If applicable, paste the error trackback here.

(pass; as this is **not** a report of an explicit bug case)

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

```python
results['img_shape'][:2], # results['scale'], #L273
```

**Comment by BIGWangYuDong** [comment]
There are differences.
```python
if self.keep_ratio:
            gt_seg = mmcv.imrescale(     #L265
                results[key],            #L266
                results['scale'],        #L267
                interpolation='nearest', #L268
                backend=self.backend)    #L269
        else:
            gt_seg = mmcv.imresize(      #L271
                results[key],            #L272
                results['scale'],        #L273
                interpolation='nearest', #L274
                backend=self.backend)    #L275
```
keep ratio is using mmcv.imrescale, however, the other is using mmcv.imresize. 
imrescale: resize image while keeping the aspect ratio.
imresize:   resize image to a given size.

but here I think there still can update the code (maybe, I'm not sure)
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/pipelines/transforms.py#L233-L239
after resizing the image by using `_resize_img`, the `results['img_shape']` will update.

SO, I think only using resize(results['img_shape'][:2]) is OK?

**Comment by BIGWangYuDong** [comment]
Kindly ping @hhaAndroid and @zytx121 have a look

**Comment by nestiank** [comment]
Thanks for your kind explanation! I missed that difference.
