### ISSUE TITLE
can't understand exactly how TTA works in MMDet

### ISSUE THREAD

**Issue by boom109** [open-mmlab/mmdetection#7667]
we checked MMDet's documentation and some code, but it was hard to find how **TTA(Test Time Augmentation)** works in MMDet.

We want to combine the inference results of the following two images:
1. original image
2. Adjust image contrast

We have three questions.
**Q1. First of all, is it possible to register a custom class for adjust image contrast in TTA?**
**Q2. I am curious about how TTA works in MMDet.**
**Q3. Which of the following scenarios is equivalent to the actual TTA behavior? (please see below)**

---------------------

The TTA as I understand it is:
![](https://user-images.githubusercontent.com/31475037/123568577-94eb1a00-d7ff-11eb-8182-14abc59ce384.png)

we understood it as a way to input the original image and augmented image into the model and average the results as shown in the image above. but I can't expect how the config code below will work. 

```python
# in config file - yolox_s_8x8_300e_coco.py

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(1333, 400), (1333, 800)],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
```

---------------------------

Some scenarios of expected TTA behavior in MMDet are:
**Q3. Which of the following scenarios is equivalent to the actual TTA behavior?**

[way we expect it to behave]
* Expected Scenario1
  1. argmentation
  img0: original image
  img1:  img_scale (1333, 400), resize, random flip
  img2:  img_scale (1333, 800), resize, random flip
  2. inference
   : get three results including bbox, scores ...
  3. average result
  4. applying NMS
* Expected Scenario2
  1. argmentation
  img0: img_scale (1333, 400), resize, random flip
  img1:  img_scale (1333, 800), resize, random flip
  2. inference
   : get two results including bbox, scores ...
  3. average result
  4. applying NMS
* Expected Scenario3
  1. argmentation
  img0: original img
  img1: img_scale (1333, 400), resize, random flip
  img2: img_scale (1333, 400)
  img3: img_scale (1333, 800), resize, random flip
  img4: img_scale (1333, 800)
  2. inference
   : get five results including bbox, scores ...
  3. average result
  4. applying NMS

I posted a rather long question. 
Thanks for reading.

**Comment by BIGWangYuDong** [comment]
1. Seems it is possible, maybe you can use albu to adjust image contrast.
2. core code is here, you can have a look at the source code.
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/pipelines/test_time_aug.py#L98-L114
3. it depends on the `aug_data_dict` from `MultiScaleFlipAug`

**Comment by boom109** [comment]
```
3. it depends on the aug_data_dict from MultiScaleFlipAug
```

@BIGWangYuDong 
we have additional question to your answer #3 

does that mean we can only use 'MultiScaleFlipAug' and not replace our custom class?
in other words that we can only add the transformations we need to `MultiScaleFilpAug`?

**Comment by BIGWangYuDong** [comment]
I think that adding the transformations you need in the `MultiScaleFilpAug` is the easiest way.

**Comment by boom109** [comment]
okay! we will apply our transformation  in `MultiScaleFlipAug` following your instructions.
thanks for your kind reply.

**Comment by zhijiejia** [comment]
How make yoloxHead can have tta ? 
![image](https://user-images.githubusercontent.com/43838913/167622318-ec2e44c7-3b26-4a11-866d-08dd1a7de780.png)

**Comment by Classmate-Huang** [comment]
> we checked MMDet's documentation and some code, but it was hard to find how **TTA(Test Time Augmentation)** works in MMDet.
> 
> We want to combine the inference results of the following two images:
> 
> 1. original image
> 2. Adjust image contrast
> 
> We have three questions. **Q1. First of all, is it possible to register a custom class for adjust image contrast in TTA?** **Q2. I am curious about how TTA works in MMDet.** **Q3. Which of the following scenarios is equivalent to the actual TTA behavior? (please see below)**
> 
> The TTA as I understand it is: ![](https://user-images.githubusercontent.com/31475037/123568577-94eb1a00-d7ff-11eb-8182-14abc59ce384.png)
> 
> we understood it as a way to input the original image and augmented image into the model and average the results as shown in the image above. but I can't expect how the config code below will work.
> 
> ```python
> # in config file - yolox_s_8x8_300e_coco.py
> 
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(
>         type='MultiScaleFlipAug',
>         img_scale=[(1333, 400), (1333, 800)],
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='RandomFlip'),
>             dict(
>                 type='Pad',
>                 pad_to_square=True,
>                 pad_val=dict(img=(114.0, 114.0, 114.0))),
>             dict(type='DefaultFormatBundle'),
>             dict(type='Collect', keys=['img'])
>         ])
> ]
> ```
> 
> Some scenarios of expected TTA behavior in MMDet are: **Q3. Which of the following scenarios is equivalent to the actual TTA behavior?**
> 
> [way we expect it to behave]
> 
> * Expected Scenario1
>   
>   1. argmentation
>      img0: original image
>      img1:  img_scale (1333, 400), resize, random flip
>      img2:  img_scale (1333, 800), resize, random flip
>   2. inference
>      : get three results including bbox, scores ...
>   3. average result
>   4. applying NMS
> * Expected Scenario2
>   
>   1. argmentation
>      img0: img_scale (1333, 400), resize, random flip
>      img1:  img_scale (1333, 800), resize, random flip
>   2. inference
>      : get two results including bbox, scores ...
>   3. average result
>   4. applying NMS
> * Expected Scenario3
>   
>   1. argmentation
>      img0: original img
>      img1: img_scale (1333, 400), resize, random flip
>      img2: img_scale (1333, 400)
>      img3: img_scale (1333, 800), resize, random flip
>      img4: img_scale (1333, 800)
>   2. inference
>      : get five results including bbox, scores ...
>   3. average result
>   4. applying NMS
> 
> I posted a rather long question. Thanks for reading.

What does "3. average result" mean? How to average the different box result?

**Comment by boom109** [comment]
> How make yoloxHead can have tta ? ![image](https://user-images.githubusercontent.com/43838913/167622318-ec2e44c7-3b26-4a11-866d-08dd1a7de780.png)

I also failed to apply TTA to yolox. but as a result of testing, most of the other models were applicable.
recently, I have also increased the use of yolox, but it is a pity that TTA cannot be applied. If anyone has had success with this, please let me know.
