### ISSUE TITLE
How to make my own dataset in LVIS format

### ISSUE THREAD

**Issue by 781458112** [open-mmlab/mmdetection#7669]
I want to use my own dataset for modal segmentation. I see in the READme that I need to install dependencies. So how do I make my own LVIS dataset？

**Comment by BIGWangYuDong** [comment]
you can follow https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_dataset.md

**Comment by 781458112** [comment]
First of all, thank you for your answer. I see that the website you sent is based on coco data set as an example, how to convert their data into coco-like data set. However, I would like to ask whether there is any software that can support the production of LVIS data, or only modify the code to convert my annotations into LVIS data. And how can I fix the part of missing modal segmentation when I use Labelme annotation?

**Comment by BIGWangYuDong** [comment]
Sorry, I haven't tried to convert annotations into LVISdata. Maybe you need to find a script on the Internet that can support your task.
