### ISSUE TITLE
Eval Problem

### ISSUE THREAD

**Issue by zerok01** [open-mmlab/mmdetection#767]
Hi,
I trained my own dataset. Then I get the following error when I want to do eval my dataset. There is no clear solution to this error on the Internet. Have you encountered this error? Please help me...

![a](https://user-images.githubusercontent.com/34706028/59061413-1e8fbe00-88ac-11e9-90d8-89733cc31e08.png)

**Comment by hellock** [comment]
Your GUI is broken.
