### ISSUE TITLE
Maybe it's Bug,RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by luomi1024** [open-mmlab/mmdetection#7670]
1.运行：python .\tools\train.py .\configs\ld\ld_r101_gflv1_r101dcn_fpn_coco_2x.py
2.报错：
  File "D:\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python\Python39\lib\site-packages\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "e:xxxxxxx\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "e:\xxxxxxx\mmdet\models\detectors\kd_one_stage.py", line 69, in forward_train
    teacher_x = self.teacher_model.extract_feat(img)
  File "e:\xxxxxxx\mmdet\models\detectors\single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "D:\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\xxxxxxx\mmdet\models\backbones\resnet.py", line 636, in forward
    x = self.conv1(x)
  File "D:\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Python\Python39\lib\site-packages\torch\nn\modules\conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

3.环境为：
window10 专业版
TorchVision: 0.11.3+cu113
OpenCV: 4.5.5
MMCV: 1.4.5
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.3
MMDetection: 2.22.0+9958e6d

**Comment by BIGWangYuDong** [comment]
Maybe your model is not using cuda, please check whether use model.cuda() in your code

**Comment by luomi1024** [comment]
can Modify the “mmdet\models\detectors\kd_one_stage.py”

add: self.self.teacher_model.cuda()   solve this problem

def __init__(self,
                 backbone,
                 neck,
                 bbox_head,
                 teacher_config,
                 teacher_ckpt=None,
                 eval_teacher=True,
                 train_cfg=None,
                 test_cfg=None,
                 pretrained=None):
        super().__init__(backbone, neck, bbox_head, train_cfg, test_cfg,
                         pretrained)
        self.eval_teacher = eval_teacher
        # Build teacher model
        if isinstance(teacher_config, str):
            teacher_config = mmcv.Config.fromfile(teacher_config)
        self.teacher_model = build_detector(teacher_config['model'])
        if teacher_ckpt is not None:
            load_checkpoint(
                self.teacher_model, teacher_ckpt, map_location='cpu') 
            self.self.teacher_model.cuda()

**Comment by luomi1024** [comment]
> can Modify the “mmdet\models\detectors\kd_one_stage.py”
> 
> add: self.teacher_model.cuda() solve this problem
> 
> def **init**(self, backbone, neck, bbox_head, teacher_config, teacher_ckpt=None, eval_teacher=True, train_cfg=None, test_cfg=None, pretrained=None): super().**init**(backbone, neck, bbox_head, train_cfg, test_cfg, pretrained) self.eval_teacher = eval_teacher # Build teacher model if isinstance(teacher_config, str): teacher_config = mmcv.Config.fromfile(teacher_config) self.teacher_model = build_detector(teacher_config['model']) if teacher_ckpt is not None: load_checkpoint( self.teacher_model, teacher_ckpt, map_location='cpu') self.teacher_model.cuda()

**Comment by alaa-shubbak** [comment]
I am trying to use the same model, and it gave same error even though , i updated the code with using cuda. 

I am thinking that it could be related to the teacher model and number of classes there as my model not have same classes of COCO models.

**Comment by alaa-shubbak** [comment]
I am still confused , any help please. 
here are the error presented during running the training

```
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
srun: error: serv-3330: task 0: Exited with exit code 1
srun: Terminating job step 336042.0
```

**Comment by yyccphus** [comment]
> I am still confused , any help please. here are the error presented during running the training
> 
> ```
> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
> srun: error: serv-3330: task 0: Exited with exit code 1
> srun: Terminating job step 336042.0
> ```
I also encounted to this problem when I tried to modify FPN model, it happened in each conv in my custom block, I just add .cuda() after each submodule
