### ISSUE TITLE
Have question in image_demo.py

### ISSUE THREAD

**Issue by xuhao-anhe** [open-mmlab/mmdetection#7673]
Thank the author for his contribution. After training my own data set, I used test.py tested the model AP(iou=0.5) can reach 95%, but I use image_ demo.py for actual test,, the segmentation effect shows only one category. There are four categories in my dataset.

**Comment by BIGWangYuDong** [comment]
what code did you use? more details are needed.

**Comment by xuhao-anhe** [comment]
> what code did you use? more details are needed.

I use point_rend_r50_caffe_fpn_mstrain_3x_coco.py

**Comment by BIGWangYuDong** [comment]
what code did you change? I think this may be because the image does not have other categories, or your model did not detect other categories?

**Comment by xuhao-anhe** [comment]
I replaced the FPN in the mask_rcnn_r50_fpn with my own improved network. I trained the improved network and the AP(IOU=0.5) can reach 95%. Then I used pictures of different categories to test and found that there was only one category in the final display

**Comment by xuhao-anhe** [comment]
The model also misclassifies other categories into one category

**Comment by BIGWangYuDong** [comment]
what code did you change?

**Comment by xuhao-anhe** [comment]
pafpn.py

**Comment by BIGWangYuDong** [comment]
please use the issue template to ask the issue. More details are needed. Right now, I cannot help you fix your error

**Comment by xuhao-anhe** [comment]
okay, thank you

**Comment by BIGWangYuDong** [comment]
Also, is your evaluation and training seem normal?

**Comment by xuhao-anhe** [comment]
Yes, everything is normal and the indicators have reached a high level, but the effect of image detection with the generated model is very poor

**Comment by xuhao-anhe** [comment]
The data has been loaded successfully，i will check my code

**Comment by xuhao-anhe** [comment]
> It is suggested to check your code, for example, did you load your data successfully?

Hello, I have solved the above problem. When I train with my own dataset, the category order is not consistent in the label file and code. After modification, multiple categories can be displayed normally, but I encounter a new problem. Due to hardware constraints, I uniformly adjust my dataset to 604 * 604 size. During the training process, AP (medium and large) has always been - 1. Is this normal

**Comment by 15032390092** [comment]
> 我用自己改进的网络替换了 mask_rcnn_r50_fpn 中的 FPN。我训练了改进后的网络，AP(IOU=0.5)可以达到95%。然后我用不同类别的图片进行测试，发现最终显示的只有一个类别

可以留下联系方式一起互相交流吗？

**Comment by BIGWangYuDong** [comment]
@15032390092 @xuhao-anhe https://github.com/open-mmlab/mmdetection/blob/master/README_zh-CN.md#%E6%AC%A2%E8%BF%8E%E5%8A%A0%E5%85%A5-openmmlab-%E7%A4%BE%E5%8C%BA
