### ISSUE TITLE
Issue while integrating fasterrcnn mm model with gradcam..

### ISSUE THREAD

**Issue by sanjaypavo** [open-mmlab/mmdetection#7675]
Hi , I have tried implementing the fasterrcnn [model](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py) with [pytorch-gradcam](https://github.com/jacobgil/pytorch-grad-cam). I used the same layers(FPN layers) as in this [notebook](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.ipynb), but was not getting efficient results. Tried different versions of fasterrcnn and facing the same issue. What is the reason for this??
Attached some outputs of both mmmodel outputs and the outputs of torchvision models.

Thanks in advance..
![torch_model_output (1)](https://user-images.githubusercontent.com/93761297/162449773-c65bb35e-4d65-4831-8f53-89a48e884a6e.png)
![torch_model_output](https://user-images.githubusercontent.com/93761297/162449783-5f3ad18b-92a2-4098-bb23-30681f8321b9.png)
![mm_model_output (1)](https://user-images.githubusercontent.com/93761297/162449785-b2427435-5351-4d1f-8a12-11ba751e5436.png)
![mm_model_output](https://user-images.githubusercontent.com/93761297/162449787-fa21c7cf-9ea0-4988-a878-3c4e29073995.png)

**Comment by BIGWangYuDong** [comment]
I haven't used this before. I'll try this later.

**Comment by sanjaypavo** [comment]
> 

MMclassification comes with integrated gradcam which was really helpful. Need the comunity help to achieve more efficiency while combining MMdetection with gradcam.

**Comment by BIGWangYuDong** [comment]
MMDet-3.x Have support CAM, you can have a try

**Comment by YeahTOT** [comment]
Hello, I’m sorry, I didn’t find the implementation of CAM in MMDet-3.x. Can you tell me where it is?

> MMDet-3.x Have support CAM, you can have a try

**Comment by lwdmkzl** [comment]
> MMDet-3.x已经支持CAM了，你可以试试

2.0有个没并入主线的代码，3.0及以上的没找到。。。

**Comment by xyb1314** [comment]
i had spent so much time on searching implementation of CAM in MMDET3.X ,but in vain ,most of them were implementation on 2.x version which used mmcv 1.x version , it is hard for me to modify that code , because some apis had been removed ,and moved to other packages.
