### ISSUE TITLE
how to define a customer dataset for ssd with ssd300_coco.py?

### ISSUE THREAD

**Issue by ncut564227621** [open-mmlab/mmdetection#7677]
I want to finetune ssd300 with my customer dataset like Tutorial https://download.openmmlab.com/mmdetection/data/kitti_tiny.zip, how to difine Dataset with mmdet.datasets.custom import CustomDataset

**Comment by chhluo** [comment]
Refer to https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html 
And you should update the `num_classes` in config for SSDHead, https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/configs/_base_/models/ssd300.py#L24
