### ISSUE TITLE
Why dose the Deformable DETR only use the score of the first class to choose the topk proposals?

### ISSUE THREAD

**Issue by volcanolee4** [open-mmlab/mmdetection#7682]
In the two-stage mode of Deformable DETR, I notice that the code choose the topk foreground proposals only by the score of the first class (In cocodataset wo have 80 calss in total)? Although I notice that Deformable DETR uses sigmoid + BCE loss, I doubt if it is reasonable to choose topk foreground proposals only by the first class score?

               **topk_proposals = torch.topk(enc_outputs_class[..., 0], topk, dim=1)[1]**

**Comment by chhluo** [comment]
Although there are 80 classes in `enc_outputs_class`, but we only use the first element in `enc_outputs_class` which means foreground not the first class of 80 classes defined in coco. See https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/dense_heads/deformable_detr_head.py#L241 . `enc_outputs_class` can also be set to only one class.

**Comment by taiwuyouxu** [comment]
Hello, I am currently facing a problem with how to use the two-stage Deformable DETR in mmdetetcion. Do you know how to use it? I have already used the Deformable DETR Encoder to obtain the output of the encoder: memory.
memory = self.encoder(
            query=encoder_inputs,
            query_pos=level_positional_encodings,
            key_padding_mask=padding_masks,
            spatial_shapes=spatial_shapes,
            reference_points=reference_points,
            level_start_index=level_start_index,
            valid_ratios=valid_radios)
Now I want to pass the memory generated by this code to the gen_encoder_output_proposals method of Deformable DETR to generate the two-stage results. How can I do it
