### ISSUE TITLE
guassianBlur

### ISSUE THREAD

**Issue by googooroom** [open-mmlab/mmdetection#7684]
Hi,

would like to check how can i incorporate GaussianBlur in the data augmentation?  i am using mmsegmentation_tutorial.py to check for some data augmentation technique.  when i add  
dict(type='GaussianBlur',kernel_size=(5,9),sigma=(0.1,5)),  to the train_pipeline and data.train i encountered this error:
KeyError: "StanfordBackgroundDataset: 'GaussianBlur is not in the pipeline registry'"

kindly advise.

**Comment by nijkah** [comment]
Currently, you can use `Albu` class to use GaussianBlur like below.
https://github.com/open-mmlab/mmdetection/blob/a616886bf1e8de325e6906b8c76b6a4924ef5520/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py#L36-L42

Replace `Blur` with [GaussianBlur](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.GaussianBlur) with some appropriate parameters.

**Comment by googooroom** [comment]
Hi,

Thanks a lot.
