### ISSUE TITLE
Empty annotation support

### ISSUE THREAD

**Issue by weypro** [open-mmlab/mmdetection#7687]
Does mmdetection support empty annotation in coco dataset? The meaning of empty annotation is that the image is just a background and doesn't contain the object. The image is noted in the images portion , but has no data about that image in the annotations portion. For example:
```
 "images": [
        {
            "id": 0,
            "file_name": "0.png",
            "height": 416,
            "width": 416,
        },
]
```

**Comment by nijkah** [comment]
Yes, it does.
You may check this https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/coco.py#L121.
