### ISSUE TITLE
Data set size problem

### ISSUE THREAD

**Issue by xuhao-anhe** [open-mmlab/mmdetection#7689]
First of all, thank the author for his contribution. I encountered a problem when training my own dataset. Due to my low hardware configuration, I uniformly adjusted the size of my own dataset image to 604 * 604. During the training process, AP (medium) and AP (large) kept - 1, but AP (small) maintained a high level. So do I use AP (small) to measure my model performance or AP (all)

**Comment by Czm369** [comment]
Maybe you can refer to
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L509
