### ISSUE TITLE
Deploy Swin-Transformer on NVidia Jetson AGX Xavier

### ISSUE THREAD

**Issue by habjoel** [open-mmlab/mmdetection#7692]
Hi there, I would like to run the swin-transformer fom MMDetection (mmdetection/configs/swin) on a Jetson AGX Xavier. However I am having trouble installing MMDetection on the Jetson. Searching through the web I am starting to think that it is not suited for the arm64 architecture. Is that correct?

If yes, I would like to use ONNX/TensorRT for the deployment of the swin-transformer. I saw that the swin-transformer is not officially supported by MMDeploy yet. When will it be? Also, is there any way how I can convert the model nonetheless?

Thanks a lot for your help!

**Comment by Czm369** [comment]
MMDeploy will support swin-transformer in the future.
