### ISSUE TITLE
how to specify other port when i run dist_train.sh

### ISSUE THREAD

**Issue by TalonX1** [open-mmlab/mmdetection#7693]
In dist_train.sh i find
```
PORT=${PORT:-29500}
```

But i want to specify other by parameter passing
```
! CUDA_VISIBLE_DEVICES=1,2,3 bash ../tools/dist_train.sh queryinst_r50_fpn_300_proposals_crop_mstrain_480-800_3x_building.py 3
```

**Comment by Czm369** [comment]
Maybe you can set the environment variable `$PORT`

**Comment by Czm369** [comment]
! CUDA_VISIBLE_DEVICES=1,2,3 PORT=20 bash ../tools/dist_train.sh queryinst_r50_fpn_300_proposals_crop_mstrain_480-800_3x_building.py 3
