### ISSUE TITLE
CloudWatch progress monitoring

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmdetection#7695]
Hi, I'm using MMDetection with Amazon SageMaker and CloudWatch logging. The logs are formatted badly because CloudWatch can't handle the carriage return ASCII character. Examples:

SageMaker CloudWatch logs:
![image](https://user-images.githubusercontent.com/12224358/162828335-b3e68c64-93fb-480d-9015-ea936cc339b2.png)
SageMaker local logs (appears slightly more capable but still not ideal):
![Screenshot-20220411190031-2345x137](https://user-images.githubusercontent.com/12224358/162846941-1c14e87a-bfbb-48cf-bcaf-0702c062da88.png)

What's the simplest (or best) way to format my logs nicely in this case? Ideally I think it would be nice if I could just disable the ">>>" progress lines and keep the logging lines,

**Comment by Czm369** [comment]
Maybe you can rewrite evalhook
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/core/evaluation/eval_hooks.py#L56
https://github.com/open-mmlab/mmcv/blob/85b37e7ba43bc667af306f25de9a3b63c1c64d78/mmcv/engine/test.py#L30
