### ISSUE TITLE
which .py file and which function are the first to get gtbox in the head?

### ISSUE THREAD

**Issue by FarranYang** [open-mmlab/mmdetection#7696]

**Comment by FarranYang** [comment]
我在debug的阶段一直在logger文件里跳转，我想找到第一次模型得到一个batch里gtbox的函数文件。请问有啥好方法吗？

During the debug , I kept jumping in the logger file. I wanted to find the first model and get a function file of Gtbox in Batch. What good method does excuse me have?

**Comment by hhaAndroid** [comment]
@FarranYang This may require familiarity with the code. At present, gt_bbox is read in the dataset, and there is no practice of forming batch box.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 26 days.
