### ISSUE TITLE
Will model interpretability analysis be added?

### ISSUE THREAD

**Issue by 834799106** [open-mmlab/mmdetection#7697]
Hi, I often need to do model interpretability analysis when using MMDetection for research, as shown in the link below. I wish MMDetection had such a component as well, which would be a lot easier for me. Mmclassification seems to have a similar function, but that is based on classification tasks.
https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/EigenCAM%20for%20YOLO5.ipynb

**Comment by hhaAndroid** [comment]
@834799106 Yes. This is very important, we have already started to think about it. Are you interested in creating a PR？

**Comment by jacob-kang** [comment]
Grad-cam wanted

**Comment by hhaAndroid** [comment]
@jacob-kang OK

**Comment by hhaAndroid** [comment]
#7987

**Comment by dwj192** [comment]
+1

**Comment by laroui880** [comment]
+1

**Comment by laroui880** [comment]
Hi, has anything been implemented or not yet?
