### ISSUE TITLE
pytorch2onnx.py  error  'CenterNetHead' object has no attribute 'prior_generator'

### ISSUE THREAD

**Issue by jsh871456205** [open-mmlab/mmdetection#7698]
Hi there，I wish to convert pytorch to onnx and I execute cmd 
python ../../tools/deployment/pytorch2onnx.py   configs/centernet_resnet18_140e_coco.py 
 work_dirs/centernet_resnet18_140e_coco/epoch_200.pth  --out result.onnx  
error is:
AttributeError: 'CenterNetHead' object has no attribute 'prior_generator'
I am using CenterNet
Thanks a lot for your help!

**Comment by hhaAndroid** [comment]
@jsh871456205 For ONNXrelated issues, please go directly to [mmdeploy ](https://github.com/open-mmlab/mmdeploy)to create an issue
