### ISSUE TITLE
how to freeze specific layers  without replace common file？

### ISSUE THREAD

**Issue by accaa** [open-mmlab/mmdetection#7699]
Hi.
I want to freeze some layers ,but all the method I know need to change the common file,such as add requires_grad=Fasle in two_stage.py or modify optimizer definition in train.py.It's really inconvenient when you have some models need to freeze but others are not.
So is it possible to freeze layers in config files?

**Comment by hhaAndroid** [comment]
@accaa You can customize it by inheriting `DefaultOptimizerConstructor`. We should add a demo to tell the user how to rewrite？

**Comment by hhaAndroid** [comment]
@accaa
