### ISSUE TITLE
cannot train because some problem with 'rank'

### ISSUE THREAD

**Issue by aimhabo** [open-mmlab/mmdetection#77]
the error information is:

>   File "/home/wit/anaconda2/envs/py36/lib/python3.6/site-packages/mmdet-0.5.1+810b711-py3.6.egg/mmdet/apis/env.py", line 16, in init_dist
>     _init_dist_pytorch(backend, **kwargs)
>   File "/home/wit/anaconda2/envs/py36/lib/python3.6/site-packages/mmdet-0.5.1+810b711-py3.6.egg/mmdet/apis/env.py", line 27, in _init_dist_pytorch
>     rank = int(os.environ['RANK'])
>   File "/home/wit/anaconda2/envs/py36/lib/python3.6/os.py", line 669, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'RANK'

my train command has suffix ' --gpus 4 --seed 9527 --launcher pytorch --local_rank 0'.

Without 'seed', 'launcher', 'local_rank' sets, command can run success... but why?

**Comment by aimhabo** [comment]
another question, can mmdetection use gpu 1,2,3, just not use gpu 0? for some reason our gpu 0 cannot run any program

**Comment by hellock** [comment]
To train on multiple GPUs, you don't need to specify the `local_rank` manually. Just use the command
```
./tools/dist_train.sh <CONFIG_FILE> 4 --seed 9527
```
It will start 4 processes with expected arguments automatically.

If you want to skip GPU 0, you can use `CUDA_VISIBLE_DEVICES`.
```
CUDA_VISIBLE_DEVICES=1,2,3 ./tools/dist_train.sh <CONFIG_FILE> 3 --seed 9527
```

**Comment by aimhabo** [comment]
Thank you @hellock 
It works

**Comment by aimhabo** [comment]
The windows haven't any change for half an hour. Is this normal on 'mask_rcnn_r50_fpn_1x.py'? Can it show anything like loss, accuracy or other valid information?
![screenshot from 2018-10-25 20-44-37](https://user-images.githubusercontent.com/12708080/47501134-468b5d80-d897-11e8-9fd9-1f1a05cd771e.png)
