### ISSUE TITLE
Adopted Guided Anchor in Mask R-CNN

### ISSUE THREAD

**Issue by lcy0604** [open-mmlab/mmdetection#770]
Excuse me, I want to adopt ga in mask rcnn, I modify the config file by replace the RPNHead with GARPNHead, but when I run the code, I get:
 AttributeError: 'ConfigDict' object has no attribute 'center_ratio'

Do you know how to adopted it successfully? Thx

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/configs/guided_anchoring/ga_faster_r50_caffe_fpn_1x.py#L91

**Comment by lcy0604** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/configs/guided_anchoring/ga_faster_r50_caffe_fpn_1x.py#L91

Thx! I was not careful on the config file before.

**Comment by my-hello-world** [comment]
@lcy0604 
How is the performance？The effect of my fusion is not so ideal

**Comment by dimimal** [comment]
How do you connect the ROI type of the guided anchor with the mask head? 
I get an error when I try to do this.
