### ISSUE TITLE
How to train without bboxes?

### ISSUE THREAD

**Issue by dersugiritlioglu** [open-mmlab/mmdetection#7703]
Hi all! 

I am not sure if I can complete such a task but I would like to extract only **_image-level labels_** (multi) from an image for the object detection task. My data does not have the bounding box labels and I don't need them in the output as well. Can I use mmdetection for such a task, if so, how? 

I have tried disabling gt_bboxes in the config file but it seems like the code does not accept that.
And I am not sure how to set the evaluation metric (default is bbox).

Thanks in advance!

**Comment by hhaAndroid** [comment]
@dersugiritlioglu Sorry. Weakly supervised target detection tasks are not supported for the time being.

**Comment by dersugiritlioglu** [comment]
@hhaAndroid Thank you for your response. Just to be sure we are on the same page: I just don't want to use bboxes anywhere in the code - not in input or output. Hence my training is no longer weakly supervised but it is not a "detection" task either. This type of training is not possible here, right?

**Comment by nijkah** [comment]
@dersugiritlioglu You may check [mmclassification](https://github.com/open-mmlab/mmclassification).

**Comment by nijkah** [comment]
@dersugiritlioglu You may check [mmclassification](https://github.com/open-mmlab/mmclassification).
