### ISSUE TITLE
Change default name of checkpoint file in training

### ISSUE THREAD

**Issue by s185231** [open-mmlab/mmdetection#7704]
Hello!

I am training a lot of different models and I was wondering if there is a way to determine what the generated checkpoint files are called. Right now they are just being saved in my working directory as epoch_12.pth ect.

**Comment by hhaAndroid** [comment]
@s185231 This part of the information will be saved in ckpt, you can read it to judge. If you want to modify the default name of the saved ckpt, you may need to modify the corresponding code.
