### ISSUE TITLE
How to down-sample the dataset/ customize dataset_wrappers  is not subscriptable 

### ISSUE THREAD

**Issue by accaa** [open-mmlab/mmdetection#7708]
Hi.
I want to get a class-balanced dataset which every categories have same amount samples as the lowest one.I try to write my own datawrapper "Downsample" but it occurs "Downsample"is not subscriptable.
Here's my code,did i miss something?
`@DATASETS.register_module()
class Downsample:
    def __init__(self, dataset, num,filter_empty_gt=True):
        self.dataset = dataset
        self.num = num
        self.CLASSES = dataset.CLASSES
        self.filter_empty_gt = filter_empty_gt

        self.PALETTE = getattr(dataset, 'PALETTE', None)
        num_images = len(dataset)
        arr = {}
        repeat_indices = []
        i = 0
        flags = []
        while 1:
            idx = random.randint(0, num_images - 1)
            cat_ids = self.dataset.get_cat_ids(idx)
            if len(cat_ids) > 0:
                if cat_ids[0] in arr:
                    if arr[cat_ids[0]] != 2:
                        repeat_indices.append(idx)
                        i = i + 1
                        flags.append(self.dataset.flag[idx])
                        arr[cat_ids[0]] = arr[cat_ids[0]] + 1
                else:
                    arr[cat_ids[0]] = 1
                    repeat_indices.append(idx)
                    flags.append(self.dataset.flag[idx])
                    i = i + 1
            print(len(repeat_indices))
            if i == self.num * len(self.CLASSES):
                break

        self.repeat_indices = repeat_indices

        assert len(flags) == len(repeat_indices)
        self.flag = np.asarray(flags, dtype=np.uint8)

    def getitem__(self, idx):
        ori_index = self.repeat_indices[idx]
        return self.dataset[ori_index]

    def get_ann_info(self, idx):
        """Get annotation of dataset by index.

        Args:
            idx (int): Index of data.

        Returns:
            dict: Annotation info of specified index.
        """
        ori_index = self.repeat_indices[idx]
        return self.dataset.get_ann_info(ori_index)

    def __len__(self):
        """Length after repetition."""
        return len(self.repeat_indices)`

**Comment by jbwang1997** [comment]
The subscribable objects need to override the `__getitem__` magic function in its class. In your class, I see you override `getitem__`.
