### ISSUE TITLE
import error: import deform_conv_cuda

### ISSUE THREAD

**Issue by youzi260** [open-mmlab/mmdetection#7712]
Enviroment:
python:3.6.9
pytorch:1.6.0
torchvision:0.7.0
mmcv:1.4.8
mmcv-full:1.3.2
mmdet:1.0
I don't know how to check the mmdetection version.
I have the following problem, can you help me?

/home/wanghan/anaconda3/envs/open-mmlab/bin/python3.7 /home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/tools/train.py
Traceback (most recent call last):
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/tools/train.py", line 11, in <module>
    from mmdet.apis import (get_root_logger, set_random_seed,
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/apis/__init__.py", line 3, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdetection.mmdet.ops.nms import nms_wrapper
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/ops/dcn/deform_conv.py", line 10, in <module>
    from mmdetection.mmdet.ops.dcn import deform_conv_cuda
ImportError: /home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

Process finished with exit code 1

**Comment by jbwang1997** [comment]
It is very likely that your MMCV is compiled in an environment but ran in another environment. Please follow the [trouble shooting page](https://mmdetection.readthedocs.io/en/latest/faq.html) here.

**Comment by youzi260** [comment]
**I followed your suggestion, but I don't know how to solve it. Can you help me?**

python mmdet/utils/collect_env.py
fatal: not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.1.2
MMCV: 1.3.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 1.0.rc0+1c9afec+

**Comment by jbwang1997** [comment]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/32032453/163306386-db39791a-e2ca-4f8e-9eeb-888296c323cf.png">
It seems the CUDA version of pytorch and runtime is different. You can try to install pytorch with CUDA10.1

**Comment by youzi260** [comment]
I've taken care of it. Thank you very much indeed
