### ISSUE TITLE
# Support Conditional DETR on MMDetection

### ISSUE THREAD

**Issue by chhluo** [open-mmlab/mmdetection#7715]
## Steps
- First have a discuss with your teams about the development plan. We can divide the full algorithms into multiple modules and add each modules step by step in different PR.
- In each PR, add a sub-modules of Conditional DETR and add unit tests to test your code
- Benchmark the performance when all modules have all added
- Prepare and release the models

## Resources
https://github.com/Atten4Vis/ConditionalDETR

## Reviewers
@chhluo

**Comment by ZwwWayne** [comment]
Done in https://github.com/open-mmlab/mmdetection/pull/9405
