### ISSUE TITLE
A higher performance with faster rcnn c4 and faster rcnn fpn, both utilize r50 backbone，dataset is coco，not modify anything

### ISSUE THREAD

**Issue by MinggangZhao** [open-mmlab/mmdetection#772]
I find that with the fixed fater rcnn r50 c4config, I can get a higher mAP about 38 but it is  35 in Model ZOO, and about 40 when I use fpn r50 c4 while it is 37 in Model ZOO.

**Comment by hellock** [comment]
That's interesting. In our experiments we just get the results in the model zoo. Have you modified any configs? How about you command to run the training?

**Comment by MinggangZhao** [comment]
Have solved, thanks.
