### ISSUE TITLE
mmdetection训练自己的数据集，coco格式，预测结果为什么不正常？

### ISSUE THREAD

**Issue by wzr0108** [open-mmlab/mmdetection#7720]
试了mask rcnn和yolox，训练损失正常，验证损失和map正常，最后测试map也正常，AP0.5有0.6以上。最后尝试把预测结果画出来，用的是demo/image_demo.py这个脚本，发现预测的框基本正确，但是类别是错的。检查了config文件，没发现问题，又检查了mmdet/datasets/coco.py和mmdet/core/evaluation/class_names.py，类别已经改过了，两个文件都放到环境了。是不是还有什么需要改的地方我漏了吗，标签应该是没问题的，用其他模型(非mmdet)训练预测是没任何问题的，本人小白，求大神指点

**Comment by xuhao-anhe** [comment]
> 试了mask rcnn和yolox，训练损失正常，验证损失和map正常，最后测试map也正常，AP0.5有0.6以上。最后尝试把预测结果画出来，用的是demo/image_demo.py这个脚本，发现预测的框基本正确，但是类别是错的。检查了config文件，没发现问题，又检查了mmdet/datasets/coco.py和mmdet/core/evaluation/class_names.py，类别已经改过了，两个文件都放到环境了。是不是还有什么需要改的地方我漏了吗，标签应该是没问题的，用其他模型(非mmdet)训练预测是没任何问题的，本人小白，求大神指点

你生成的coco格式的标签文件里面，标签顺序需要和代码里的class_names里的标签顺序保持一致

**Comment by wzr0108** [comment]
> > 试了mask rcnn和yolox，训练损失正常，验证损失和map正常，最后测试map也正常，AP0.5有0.6以上。最后尝试把预测结果画出来，用的是demo/image_demo.py这个脚本，发现预测的框基本正确，但是类别是错的。检查了config文件，没发现问题，又检查了mmdet/datasets/coco.py和mmdet/core/evaluation/class_names.py，类别已经改过了，两个文件都放到环境了。是不是还有什么需要改的地方我漏了吗，标签应该是没问题的，用其他模型(非mmdet)训练预测是没任何问题的，本人小白，求大神指点
> 
> 你生成的coco格式的标签文件里面，标签顺序需要和代码里的class_names里的标签顺序保持一致

仔细看了一下，两者的顺序是一致的

**Comment by RangiLyu** [comment]
Try modify this line https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/coco.py#L25

**Comment by wzr0108** [comment]
> Try to modify this line
> 
> https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/datasets/coco.py#L25

I have modified this line
CLASSES = ['bingdundun', 'Sanyo', 'Eifini', 'PSALTER', 'Beaster', 'ON', 'BYREDO', 'Ubras', 'Eternelle',

**Comment by BIGWangYuDong** [comment]
`CLASSES` is suggested to be set as a tuple( use `( )`).
maybe, you can try to ues `python tools/test.py  YOUR-CONFIG-FILE  YOUR-CHECKPOINT --show` to have a look. If you still meet this problem. You need check the following step:

1. please check your train and val json file. maybe their categories are not same. For example, in train, the class sort is A,B,C but in val, the class sort is C,B,A. 
2. Also there is another thing that need to check, please check whether your training cat_ids is same as test.
