### ISSUE TITLE
Images2coco.py for customised data

### ISSUE THREAD

**Issue by maffinnn** [open-mmlab/mmdetection#7723]
**Describe the feature**
Hello,
I found the documentation for converting images to coco format is not very helpful (refering to the documentation screenshot below).

<img width="836" alt="image" src="https://user-images.githubusercontent.com/70844093/163379568-cbf684c9-ee3a-41ac-803e-b6af5355b192.png">

The ${CLASSES}  part does not specify the file type and it creates trouble for me.
I passed in a text file "path/to/classes.txt" which has one line of all classes. But it doesn't seem to work correctly (though in the end, I solved the problem by hard coding the classes I need into the Images2coco.py file)

Please update the documentation. Thank you.

**Comment by RangiLyu** [comment]
Thanks for your suggestion! We will update the document soon. Also, it would be really appreciated if you would like to create a PR to fix this.
