### ISSUE TITLE
Regarding Value Error 

### ISSUE THREAD

**Issue by mreece813** [open-mmlab/mmdetection#7724]
I am getting an error when trying to run the mmdet pcd_demo.py on my .bin files.
the file contains: x y z reflectance ring_index
the error is:
![image](https://user-images.githubusercontent.com/29603698/163458586-4c3b70e6-4bac-46a6-833a-b8a7f35f5d41.png)

Any help would be great thanks!

**Comment by RangiLyu** [comment]
Please transfer this issue to mmdetection3d.
