### ISSUE TITLE
Use the same configuration file(.py) to implement two tasks. Will the weight parameters of the two tasks conflict with each other?

### ISSUE THREAD

**Issue by NanCheng2001** [open-mmlab/mmdetection#7725]
I'm a little worried. When using the same configuration file to implement two tasks, because the weights of each layer are certainly different when they run, will the two tasks conflict? 
That is, will the weight parameters of each layer of the model corresponding to the two tasks affect each other when the two tasks are in progress?

**Comment by BIGWangYuDong** [comment]
I haven't got your point, but I think the config file will not affect the model parameters.
For example, if you run two python tasks by using `python tools/train.py configs/faster_rcnn/xxx.py --work-dir xxx`. They will not conflict with each other. During train, the two models (two task) are independent of each other.

**Comment by NanCheng2001** [comment]
> 



> I haven't got your point, but I think the config file will not affect the model parameters. For example, if you run two python tasks by using `python tools/train.py configs/faster_rcnn/xxx.py --work-dir xxx`. They will not conflict with each other. During training, the two models (two tasks) are independent of each other.

Thank you for your reply. In your example just now, faster_rcnn/xxx.py.Does it mean to complete two tasks with the same py file(faster_rcnn/xxx.py)? They share what you just said faster_rcnn/xxx.py.

**Comment by BIGWangYuDong** [comment]
the config file contains the settings that going to init models, datasets, and some other important parts that you will use in training or testing. This means if you start two (three, or even 100) python tasks, these tasks are independent of each other. 
For example, you use faster/xxx.py as a config file to start 2 training tasks. Each task will train their model independently, and you will get two models after training.

The config file is only used to set some important parameters in your python task, but will not affect each other.

Does that clear? or do you mean you want to use one config file to init two models and train them in one python task?

**Comment by NanCheng2001** [comment]
> the config file contains the settings that going to init models, datasets, and some other important parts that you will use in training or testing. This means if you start two (three, or even 100) python tasks, these tasks are independent of each other. For example, you use faster/xxx.py as a config file to start 2 training tasks. Each task will train their model independently, and you will get two models after training.
> 
> The config file is only used to set some important parameters in your python task, but will not affect each other.
> 
> Does that clear? or do you mean you want to use one config file to init two models and train them in one python task?

Thank you again for your patience.
Let me describe my specific situation to you: first, I added the attention mechanism to the FPN part of mask RCNN. At the same time, a parameter phi is defined in the configuration file, and it is specified that when phi = 0, the attention mechanism is not used, and when phi = 1, the attention mechanism is used.
These two configuration files are only different on phi. I first used phi = 0 in the configuration file and put it into the remote server for training; At the same time, I then modified phi = 1, used the attention mechanism, and also put it into the remote server.
Note: the phi parameter can select whether to use the attention mechanism. In the second task, I did not delete the option of phi=0 (in the FPN file)
According to what you just said, I don't think it will cause the conflict between the two tasks. At first, I was worried that doing so would make their model training parameters interfere with each other.
In addition, I think this should not be what you just worried about. Train them in the same Python file.

**Comment by NanCheng2001** [comment]
In addition, I also think that if I delete phi = 0 in the second task (in the FPN file), it will lead to errors in the training of the first task. Because I think they both share a model.

**Comment by NanCheng2001** [comment]
In addition, I also think that if I delete the code of phi = 0 in the second task (in the FPN file), it will lead to errors in the training of the first task. Because I think they both share a model.

**Comment by BIGWangYuDong** [comment]
When you start a python task, changing code in config files will not affect your task. But if you change some important code in the source code (in `mmdet` folder) it may affect your task.
