### ISSUE TITLE
convert List[NDArray] to NDArray before converting to a tensor

### ISSUE THREAD

**Issue by hubutui** [open-mmlab/mmdetection#7728]
**Describe the feature**
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/dense_heads/yolox_head.py#L252-L286
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/dense_heads/yolo_head.py#L238-L270

`scale_factors` is a list of `np.ndarray`, it would be better to convert it a `nd.array` before converted to tensor as the warning described.

**Additional context**
```text
/usr/lib/python3.10/site-packages/mmdet/models/dense_heads/yolo_head.py:269: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /build/python-pytorch/src/pytorch-1.11.0-cuda/torch/csrc/utils/tensor_new.cpp:207.)
```

**Comment by BIGWangYuDong** [comment]
yes, you are right. PR is welcomed.

**Comment by DLRook1e** [comment]
I also encountered the same problem. How can I solve it？

**Comment by austinmw** [comment]
@BIGWangYuDong #7921
