### ISSUE TITLE
the mAP of yolox-x reported in readme is different with the log.json

### ISSUE THREAD

**Issue by CarryHJR** [open-mmlab/mmdetection#7729]
in the [readme](https://github.com/open-mmlab/mmdetection/blob/master/configs/yolox/README.md)
| Backbone  | size   | Mem (GB) |   box AP | Config | Download |
|:---------:|:-------:|:-------:|:-------:|:--------:|:------:|
| YOLOX-x | 640 |   28.1      |   50.9  | [config](https://github.com/open-mmlab/mmdetection/tree/master/configs/yolox/yolox_x_8x8_300e_coco.py)       |[model](https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth) &#124; [log](https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254.log.json) |

but in the [log](https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254.log.json)
we can found the mAP
```
285 ['0.488 0.668 0.531 0.308 0.533 0.644']
286 ['0.497 0.677 0.541 0.316 0.543 0.656']
287 ['0.501 0.682 0.545 0.321 0.548 0.660']
288 ['0.504 0.683 0.549 0.323 0.551 0.660']
289 ['0.504 0.684 0.549 0.323 0.554 0.661']
290 ['0.505 0.684 0.548 0.320 0.555 0.664']
291 ['0.506 0.684 0.550 0.320 0.556 0.667']
292 ['0.506 0.684 0.550 0.322 0.556 0.665']
293 ['0.505 0.683 0.549 0.321 0.555 0.670']
294 ['0.505 0.682 0.548 0.318 0.555 0.667']
295 ['0.504 0.681 0.548 0.317 0.555 0.667']
296 ['0.504 0.680 0.547 0.314 0.553 0.667']
297 ['0.503 0.679 0.545 0.314 0.552 0.666']
298 ['0.502 0.677 0.544 0.312 0.551 0.665']
299 ['0.500 0.677 0.541 0.313 0.552 0.664']
300 ['0.499 0.675 0.540 0.310 0.550 0.662']
```
the best mAP should be 0.506 instead of 0.509

**Comment by hhaAndroid** [comment]
In order to align the source code, the threshold of the val phase is 0.01, and the threshold of the test phase is 0.001. The threshold in the log file is 0.01, but the prediction at test time is 0.001.

**Comment by CarryHJR** [comment]
thanks
