### ISSUE TITLE
When I do test on instance segmentation,can I cut the test image before input the network and predict ,and output the spliced results

### ISSUE THREAD

**Issue by TalonX1** [open-mmlab/mmdetection#7735]
my train datasets scales is far less than test dateset , so I hope do a patch cut on test image and hope the network do it automatically.

**Comment by TalonX1** [comment]
If mmdet have achieved it?

**Comment by chhluo** [comment]
This feature is not supported yet. https://github.com/obss/sahi may be helpful for  you.

**Comment by TalonX1** [comment]
> This feature is not supported yet. https://github.com/obss/sahi may be helpful for you.

Nice!Thank you for your suggest.
