### ISSUE TITLE
Is it default that nms is done on all levels?

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdetection#7741]
I am using mmcv-full 1.4.8 and mmdet 2.23.0. I am using mask_rcnn_r50_fpn.py to train a model. I would like to know if nms is done on all levels? If yes, how can I change it so that it will be done on different levels?

**Comment by Czm369** [comment]
Maybe you can 
breakpoint at
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L374
and
https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/core/post_processing/bbox_nms.py#L8

**Comment by nijkah** [comment]
NMS is performed in the sense of every predicted box from RoI Head or Dense Head.
I think that NMS in each feature pyramid level can be negligible because labels are already assigned to each level according to its size and ratio in the training phase.

**Comment by yeungkong** [comment]
> 
I see. When I use older version of mmdect v1.0.0, There is a parameter, nms_across_levels, and it is false in default.

> NMS is performed in the sense of every predicted box from RoI Head or Dense Head. I think that NMS done in each feature pyramid level can be negligible because labels are already assigned to each level according to its size and ratio in the training phase.

**Comment by nijkah** [comment]
I didn't know that history. Then, I may be wrong. It will be good if some of the maintainers explain it.
I will try digging into the history of this feature when I have enough time.
