### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by stevenwudi** [open-mmlab/mmdetection#7742]
**Describe the bug**

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Reproduction**

```
python demo/image_demo.py demo/demo.jpg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
```

**Environment**

` python mmdet/utils/collect_env.py`

```
sys.platform: linux
Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA RTX A5000
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.5.r11.5/compiler.30672275_0
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.11.0+cu115
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.5
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.5, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.12.0+cu115
OpenCV: 4.5.5
MMCV: 1.4.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.5
MMDetection: 2.22.0+70f6d9c

```

**Error traceback**
```
    result = inference_detector(model, args.img)
  File "/opt/conda/lib/python3.9/site-packages/mmdet/apis/inference.py", line 150, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mmdet/models/detectors/two_stage.py", line 179, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/opt/conda/lib/python3.9/site-packages/mmdet/models/dense_heads/dense_test_mixins.py", line 130, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas)
  File "/opt/conda/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 102, in get_bboxes
    results = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/opt/conda/lib/python3.9/site-packages/mmdet/models/dense_heads/rpn_head.py", line 185, in _get_bboxes_single
    return self._bbox_post_process(mlvl_scores, mlvl_bbox_preds,
  File "/opt/conda/lib/python3.9/site-packages/mmdet/models/dense_heads/rpn_head.py", line 231, in _bbox_post_process
    dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
  File "/opt/conda/lib/python3.9/site-packages/mmcv/ops/nms.py", line 326, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/opt/conda/lib/python3.9/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/mmcv/ops/nms.py", line 172, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/opt/conda/lib/python3.9/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by Czm369** [comment]
Maybe you can refer to
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/faq.md#pytorchcuda-environment

**Comment by gaobo25** [comment]
Hello, I have also encountered related problems. My environment configuration is as follows:

sys.platform: linux
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) [GCC 7.2.0]
CUDA available: True
GPU 0,1,2,3: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0+cu111
OpenCV: 4.5.1
MMCV: 1.3.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.6.0+

**Comment by FlinkRay** [comment]
> Hello, I have also encountered related problems. My environment configuration is as follows:
> 
> sys.platform: linux Python: 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) [GCC 7.2.0] CUDA available: True GPU 0,1,2,3: GeForce RTX 3090 CUDA_HOME: /usr/local/cuda NVCC: Build cuda_11.1.TC455_06.29069683_0 GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 PyTorch: 1.8.0+cu111 PyTorch compiling details: PyTorch built with:
> 
> * GCC 7.3
> * C++ Version: 201402
> * Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * NNPACK is enabled
> * CPU capability usage: AVX2
> * CUDA Runtime 11.1
> * NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
> * CuDNN 8.0.5
> * Magma 2.5.2
> * Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
> 
> TorchVision: 0.9.0+cu111 OpenCV: 4.5.1 MMCV: 1.3.0 MMCV Compiler: GCC 7.3 MMCV CUDA Compiler: 11.1 MMDetection: 2.6.0+

I have also encountered related problems.I also used RTX3090.Have you solved this problem?

**Comment by gaobo25** [comment]
> 
No solution has yet been found

**Comment by gaobo25** [comment]
> > 你好，我也遇到过相关问题。我的环境配置如下：
> > sys.platform: linux Python: 3.6.3 |Anaconda, Inc.| （默认，2017 年 10 月 13 日，12:02:49）[GCC 7.2.0] CUDA 可用：True GPU 0、1、2、3：GeForce RTX 3090 CUDA_HOME：/usr/local/cuda NVCC：构建 cuda_11.1。 TC455_06.29069683_0 GCC：gcc（Ubuntu 7.5.0-3ubuntu1~18.04）7.5.0 PyTorch：1.8.0+cu111 PyTorch 编译细节：PyTorch 内置：
> > 
> > * 海合会 7.3
> > * C++ 版本：201402
> > * 英特尔(R) 数学内核库版本 2020.0.0 产品构建 20191122 用于英特尔(R) 64 架构应用程序
> > * 英特尔(R) MKL-DNN v1.7.0 (Git 哈希 7aed236906b1f7a05c0917e5257a1af05e9ff683)
> > * OpenMP 201511（又名 OpenMP 4.5）
> > * NNPACK 已启用
> > * CPU能力使用：AVX2
> > * CUDA 运行时 11.1
> > * NVCC 架构标志：-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode ;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
> > * CuDNN 8.0.5
> > * 岩浆 2.5.2
> > * 构建设置：BLAS_INFO=mkl，BUILD_TYPE=Release，CUDA_VERSION=11.1，CUDNN_VERSION=8.0.5，CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++，CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing -field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused -result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error =redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping -math -Werror=format -Wno-stringop-overflow，LAPACK_INFO=mkl，PERF_WITH_AVX=1，PERF_WITH_AVX2=1，PERF_WITH_AVX512=1，TORCH_VERSION=1.8.0，USE_CUDA=ON，USE_CUDNN=ON，USE_EXCEPTION_PTR=1，USE_GFLAGS=OFF，USE_GLOG=OFF，USE_MKL=ON，USE_MKLDNN=ON，USE_MPI=OFF，USE_NCCL=ON，USE_NNPACK=ON， USE_OPENMP=ON，
> > 
> > TorchVision: 0.9.0+cu111 OpenCV: 4.5.1 MMCV: 1.3.0 MMCV Compiler: GCC 7.3 MMCV CUDA Compiler: 11.1 MMDetection: 2.6.0+
> 
> I have also encountered related problems.I also used RTX3090.Have you solved this problem?

But you can train with the latest version of MMET

**Comment by FlinkRay** [comment]
> 

I sloved this problem.You should reinstall mmcv-full by using `TORCH_CUDA_ARCH_LIST=8.6 pip install mmcv-full==1.3.0`

**Comment by FlinkRay** [comment]
> > > 你好，我也遇到过相关问题。我的环境配置如下：
> > > sys.platform: linux Python: 3.6.3 |Anaconda, Inc.| （默认，2017 年 10 月 13 日，12:02:49）[GCC 7.2.0] CUDA 可用：True GPU 0、1、2、3：GeForce RTX 3090 CUDA_HOME：/usr/local/cuda NVCC：构建 cuda_11.1。 TC455_06.29069683_0 GCC：gcc（Ubuntu 7.5.0-3ubuntu1~18.04）7.5.0 PyTorch：1.8.0+cu111 PyTorch 编译细节：PyTorch 内置：
> > > 
> > > * 海合会 7.3
> > > * C++ 版本：201402
> > > * 英特尔(R) 数学内核库版本 2020.0.0 产品构建 20191122 用于英特尔(R) 64 架构应用程序
> > > * 英特尔(R) MKL-DNN v1.7.0 (Git 哈希 7aed236906b1f7a05c0917e5257a1af05e9ff683)
> > > * OpenMP 201511（又名 OpenMP 4.5）
> > > * NNPACK 已启用
> > > * CPU能力使用：AVX2
> > > * CUDA 运行时 11.1
> > > * NVCC 架构标志：-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode ;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
> > > * CuDNN 8.0.5
> > > * 岩浆 2.5.2
> > > * 构建设置：BLAS_INFO=mkl，BUILD_TYPE=Release，CUDA_VERSION=11.1，CUDNN_VERSION=8.0.5，CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++，CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing -field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused -result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error =redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping -math -Werror=format -Wno-stringop-overflow，LAPACK_INFO=mkl，PERF_WITH_AVX=1，PERF_WITH_AVX2=1，PERF_WITH_AVX512=1，TORCH_VERSION=1.8.0，USE_CUDA=ON，USE_CUDNN=ON，USE_EXCEPTION_PTR=1，USE_GFLAGS=OFF，USE_GLOG=OFF，USE_MKL=ON，USE_MKLDNN=ON，USE_MPI=OFF，USE_NCCL=ON，USE_NNPACK=ON， USE_OPENMP=ON，
> > > 
> > > TorchVision: 0.9.0+cu111 OpenCV: 4.5.1 MMCV: 1.3.0 MMCV Compiler: GCC 7.3 MMCV CUDA Compiler: 11.1 MMDetection: 2.6.0+
> > 
> > 
> > I have also encountered related problems.I also used RTX3090.Have you solved this problem?
> 
> But you can train with the latest version of MMET

I sloved this problem.You should reinstall mmcv-full by using `TORCH_CUDA_ARCH_LIST=8.6 pip install mmcv-full==1.3.0`

**Comment by gaobo25** [comment]
> 
I downloaded the latest model and recompiled it

**Comment by rajnishrajput12** [comment]
I am getting RuntimeError: no kernel image is available for execution on this device. below if my config

python- 3.8
mmcv- 1.7.2(wheel file installation) (https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/mmcv_full-1.7.2-cp38-cp38-manylinux1_x86_64.whl)
mmdet-2.28.1
torch==2.1.0
torchvision=0.16.0
CUDA-12.1
NVIDIA A100-SXM4-80GB

the error starts from mmdet/api/inference.py(line 157) then it goes to mmcv/ops/nms.py(line 350)

error traceback
Traceback (most recent call last):
File "table_detection_server.py", line 46, in get_table_bbox
bboxes = worker.get_table_bbox(file_name, page_num, src_fname, bucket_nm)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/utils/gpu_handler.py", line 54, in get_table_bbox
bboxes = Worker.model.get_table_bbox(page)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/utils/nn_utils.py", line 137, in get_table_bbox
result = self.get_table_preds(temp_file)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/utils/nn_utils.py", line 42, in get_table_preds
return inference_detector(self.model, temp_file)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/apis/inference.py", line 157, in inference_detector
results = model(return_loss=False, rescale=True, **data)
File "/opt/app-root/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
return old_func(*args, **kwargs)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/models/detectors/base.py", line 174, in forward
return self.forward_test(img, img_metas, **kwargs)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
return self.simple_test(imgs[0], img_metas[0], **kwargs)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/models/detectors/two_stage.py", line 179, in simple_test
proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 130, in simple_test_rpn
proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas)
File "/opt/app-root/lib64/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 208, in new_func
return old_func(*args, **kwargs)
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 102, in get_bboxes
results = self._get_bboxes_single(cls_score_list, bbox_pred_list,
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 185, in _get_bboxes_single
return self._bbox_post_process(mlvl_scores, mlvl_bbox_preds,
File "/app/aafa/aafa_parser/aafa_parser_table_detection/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 231, in bbox_post_process
dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
File "/opt/app-root/lib64/python3.8/site-packages/mmcv/ops/nms.py", line 350, in batched_nms
dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg)
File "/opt/app-root/lib64/python3.8/site-packages/mmcv/utils/misc.py", line 340, in new_func
output = old_func(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/mmcv/ops/nms.py", line 175, in nms
inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
File "/opt/app-root/lib64/python3.8/site-packages/torch/autograd/function.py", line 539, in apply
return super().apply(*args, **kwargs) # type: ignore[misc]
File "/opt/app-root/lib64/python3.8/site-packages/mmcv/ops/nms.py", line 28, in forward
inds = ext_module.nms(
RuntimeError: CUDA error: no kernel image is available for execution on the device
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

Error - CUDA error: no kernel image is available for execution on the device
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
in parsing page 0 of file tmp/estorage_RG_kcl-2022-annual-ff1ea1.pdf
[2024-01-19 19:11:32,313] ERROR in app: Exception on /get_table_bbox [GET]
Traceback (most recent call last):
