### ISSUE TITLE
How can I use gpu_ids=5,6,7 to do distributed training(not from the gpu=0 to do distributed training)? 

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#7743]
I want to use CUDA_VISIBLE_DEVICES=5,6,7 to do distributed learning, however, I found it still run from the first gpu.

**Comment by Czm369** [comment]
`CUDA_VISIBLE_DEVICES=4, 5,6,7 GPUS=4 GPUS_PER_NODE=4 CPUS_PER_TASK=2 . tools/slurm_train.sh`

**Comment by puhan123** [comment]
![image](https://user-images.githubusercontent.com/24897773/163789696-546f1b9d-17dd-4c66-a1c0-f12322556dfd.png)

**Comment by hhaAndroid** [comment]
@puhan123 You can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/en/1_exist_data_model.md#training-on-multiple-gpus

**Comment by puhan123** [comment]
Thank you very much. This answer solves my confusion.
