### ISSUE TITLE
Yolox model : I get trouble in loading parameters after training. 

### ISSUE THREAD

**Issue by OuyangZhenqiu** [open-mmlab/mmdetection#7745]
**Describe the bug**
When we utilized Yolox model and optimized it in our dataset, we found that the parameters in checkpoint  mismatched with that of the model. We recognized that the character "_" in keys of parameters should be replaced with the character '.'  

**Bug fix**
It seems to be solved by commenting out the codes for the resumption of model:
```
# configs/yolox/yolox_s_8x8_300e_coco.py
custom_hooks = [
    dict(
        type='YOLOXModeSwitchHook',
        num_last_epochs=num_last_epochs,
        priority=48),
    dict(
        type='SyncNormHook',
        num_last_epochs=num_last_epochs,
        interval=interval,
        priority=48),
    # dict(
    #     type='ExpMomentumEMAHook',
    #     resume_from=resume_from,
    #     momentum=0.0001,
    #     priority=49)
]
```
But the bug needs to get settled really.

**Comment by Czm369** [comment]
Maybe you can refer to
https://github.com/open-mmlab/mmdetection/issues/7552
