### ISSUE TITLE
How to output predicted boxes or boxes during testing?

### ISSUE THREAD

**Issue by lyk595** [open-mmlab/mmdetection#7750]
How to output predicted boxes or boxes during testing?

**Comment by hhaAndroid** [comment]
For a single image test, you can use [image_demo.py](https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py) directly. The prediction boxes cannot be directly obtained in the testing phase. But you can save all predictions through out parameter.

**Comment by lyk595** [comment]
# Copyright (c) OpenMMLab. All rights reserved.
import asyncio
from argparse import ArgumentParser

from mmdet.apis import (async_inference_detector, inference_detector,
                        init_detector, show_result_pyplot)


def parse_args():
    parser = ArgumentParser()
    parser.add_argument('--img', default='000 (177).jpg', help='Image file')
    parser.add_argument('--config', default='../configs/pvt/retinanet_pvtv2-b0_fpn_1x_coco.py', help='Config file')
    parser.add_argument('--checkpoint', default='../tools/pvt/latest.pth', help='Checkpoint file')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument(
        '--palette',
        default='coco',
        choices=['coco', 'voc', 'citys', 'random'],
        help='Color palette used for visualization')
    parser.add_argument(
        '--score-thr', type=float, default=0.3, help='bbox score threshold')
    parser.add_argument(
        '--async-test',
        action='store_true',
        help='whether to set async options for async inference.')
    args = parser.parse_args()
    return args


def main(args):
    # build the model from a config file and a checkpoint file
    model = init_detector(args.config, args.checkpoint, device=args.device)
    # test a single image
    result = inference_detector(model, args.img)
    # show the results
    show_result_pyplot(
        model,
        args.img,
        result,
        palette=args.palette,
        score_thr=args.score_thr)


async def async_main(args):
    # build the model from a config file and a checkpoint file
    model = init_detector(args.config, args.checkpoint, device=args.device)
    # test a single image
    tasks = asyncio.create_task(async_inference_detector(model, args.img))
    result = await asyncio.gather(tasks)
    # show the results
    show_result_pyplot(
        model,
        args.img,
        result[0],
        palette=args.palette,
        score_thr=args.score_thr)


if __name__ == '__main__':
    args = parse_args()
    if args.async_test:
        asyncio.run(async_main(args))
    else:
        main(args)


 File "mmdetection-master/mmdet/core/visualization/palette.py", line 18, in palette_val
    for color in palette:
TypeError: 'NoneType' object is not iterable

**Comment by lyk595** [comment]
> For a single image test, you can use [image_demo.py](https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py) directly. The prediction boxes cannot be directly obtained in the testing phase. But you can save all predictions through out parameter.
import asyncio
from argparse import ArgumentParser

from mmdet.apis import (async_inference_detector, inference_detector,
init_detector, show_result_pyplot)

def parse_args():
parser = ArgumentParser()
parser.add_argument('--img', default='000 (177).jpg', help='Image file')
parser.add_argument('--config', default='../configs/pvt/retinanet_pvtv2-b0_fpn_1x_coco.py', help='Config file')
parser.add_argument('--checkpoint', default='../tools/pvt/latest.pth', help='Checkpoint file')
parser.add_argument(
'--device', default='cuda:0', help='Device used for inference')
parser.add_argument(
'--palette',
default='coco',
choices=['coco', 'voc', 'citys', 'random'],
help='Color palette used for visualization')
parser.add_argument(
'--score-thr', type=float, default=0.3, help='bbox score threshold')
parser.add_argument(
'--async-test',
action='store_true',
help='whether to set async options for async inference.')
args = parser.parse_args()
return args

def main(args):
# build the model from a config file and a checkpoint file
model = init_detector(args.config, args.checkpoint, device=args.device)
# test a single image
result = inference_detector(model, args.img)
# show the results
show_result_pyplot(
model,
args.img,
result,
palette=args.palette,
score_thr=args.score_thr)

async def async_main(args):
# build the model from a config file and a checkpoint file
model = init_detector(args.config, args.checkpoint, device=args.device)
# test a single image
tasks = asyncio.create_task(async_inference_detector(model, args.img))
result = await asyncio.gather(tasks)
# show the results
show_result_pyplot(
model,
args.img,
result[0],
palette=args.palette,
score_thr=args.score_thr)

if name == 'main':
args = parse_args()
if args.async_test:
asyncio.run(async_main(args))
else:
main(args)

File "mmdetection-master/mmdet/core/visualization/palette.py", line 18, in palette_val
for color in palette:
TypeError: 'NoneType' object is not iterable

**Comment by lyk595** [comment]
> For a single image test, you can use [image_demo.py](https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py) directly. The prediction boxes cannot be directly obtained in the testing phase. But you can save all predictions through out parameter.

  File "mmdetection-master/mmdet/core/visualization/palette.py", line 18, in palette_val
    for color in palette:
TypeError: 'NoneType' object is not iterable

**Comment by lyk595** [comment]
> For a single image test, you can use [image_demo.py](https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py) directly. The prediction boxes cannot be directly obtained in the testing phase. But you can save all predictions through out parameter.

这是为什么？

**Comment by hhaAndroid** [comment]
@lyk595 Please use issue template.
