### ISSUE TITLE
"ValueError: bbox_params must be specified for bbox transformations" when using albumentations（mmdet 2.23.0）

### ISSUE THREAD

**Issue by tcexeexe** [open-mmlab/mmdetection#7751]
Hello~

the error is
ValueError: bbox_params must be specified for bbox transformations 

the version of mmdetection is 2.23.0
and l follow the #7143 ,use `pip install -U albumentations --no-binary qudida,albumentations` install the albu

but an error still occurred

Checklist

I have searched related issues but cannot get the expected help.
I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
The bug has not been fixed in the latest version.
Describe the bug

Reproduction

What command or script did you run?

` bash tools/dist_train.sh ./configs/yolox/yolox_x_8x8_300e_coco.py 5`
```
train_pipeline = [
    dict(type="Albu", transforms=[
        dict(type="OneOf", transforms=[
            dict(type="VerticalFlip", p = 0.2),
            dict(type="HorizontalFlip", p = 0.2),
        ]),
        dict(type="CLAHE", clip_limit=4.0, tile_grid_size=(8, 8), p=0.2),
        dict(type="ChannelShuffle", p=0.2),
        dict(type="RGBShift", r_shift_limit=20, g_shift_limit=20, b_shift_limit=20, p=0.2),
        dict(type="RandomBrightnessContrast", brightness_limit=0.2, contrast_limit=0.2, p=0.2),
        dict(type="HueSaturationValue", hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.2),
        dict(type="OneOf", transforms=[
            dict(type="GaussianBlur", blur_limit=(3, 7), snimenigma_limit=0, p=0.2),
            dict(type="MedianBlur", blur_limit=7, p=0.2),
            dict(type="MotionBlur", p=0.5)], p=0.2)
    ]),
    dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(-img_scale[0] // 2, -img_scale[1] // 2)),
    dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    # According to the official implementation, multi-scale
    # training is not considered here but in the
    # 'mmdet/models/detectors/yolox.py'.
    dict(type='Resize', img_scale=img_scale, keep_ratio=True),
    dict(
        type='Pad',
        pad_to_square=True,
        # If the image is three-channel, the pad value needs
        # to be set separately for each channel.
        pad_val=dict(img=(114.0, 114.0, 114.0))),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
```

**Comment by hhaAndroid** [comment]
@tcexeexe you lost bbox_params. Please refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py#L52

**Comment by tcexeexe** [comment]
> Hello~
> 
> the error is ValueError: bbox_params must be specified for bbox transformations
> 
> the version of mmdetection is 2.23.0 and l follow the #7143 ,use `pip install -U albumentations --no-binary qudida,albumentations` install the albu
> 
> but an error still occurred
> 
> Checklist
> 
> I have searched related issues but cannot get the expected help. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help. The bug has not been fixed in the latest version. Describe the bug A clear and concise description of what the bug is.
> 
> Reproduction
> 
> What command or script did you run?
> 
> ```
> train_pipeline = [
>     dict(type="Albu", transforms=[
>         dict(type="OneOf", transforms=[
>             dict(type="VerticalFlip", p = 0.2),
>             dict(type="HorizontalFlip", p = 0.2),
>         ]),
>         dict(type="CLAHE", clip_limit=4.0, tile_grid_size=(8, 8), p=0.2),
>         dict(type="ChannelShuffle", p=0.2),
>         dict(type="RGBShift", r_shift_limit=20, g_shift_limit=20, b_shift_limit=20, p=0.2),
>         dict(type="RandomBrightnessContrast", brightness_limit=0.2, contrast_limit=0.2, p=0.2),
>         dict(type="HueSaturationValue", hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.2),
>         dict(type="OneOf", transforms=[
>             dict(type="GaussianBlur", blur_limit=(3, 7), snimenigma_limit=0, p=0.2),
>             dict(type="MedianBlur", blur_limit=7, p=0.2),
>             dict(type="MotionBlur", p=0.5)], p=0.2)
>     ]),
>     dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
>     dict(
>         type='RandomAffine',
>         scaling_ratio_range=(0.1, 2),
>         border=(-img_scale[0] // 2, -img_scale[1] // 2)),
>     dict(
>         type='MixUp',
>         img_scale=img_scale,
>         ratio_range=(0.8, 1.6),
>         pad_val=114.0),
>     dict(type='YOLOXHSVRandomAug'),
>     dict(type='RandomFlip', flip_ratio=0.5),
>     # According to the official implementation, multi-scale
>     # training is not considered here but in the
>     # 'mmdet/models/detectors/yolox.py'.
>     dict(type='Resize', img_scale=img_scale, keep_ratio=True),
>     dict(
>         type='Pad',
>         pad_to_square=True,
>         # If the image is three-channel, the pad value needs
>         # to be set separately for each channel.
>         pad_val=dict(img=(114.0, 114.0, 114.0))),
>     dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
> ]
> ```



> @tcexeexe you lost bbox_params. Please refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py#L52

thanks!
Is there any documentation about the "bbox_params"? Because l modify the config file like this, but another error occurred:
`ValueError: Expected x_max for bbox (0.42133333333333334, 0.503, 1.112, 1.172, 0) to be in the range [0.0, 1.0], got 1.112. `


_base_ = ['../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py']

img_scale = (768, 768)  # height, width

# model settings
model = dict(
    type='YOLOX',
    input_size=img_scale,
    random_size_range=(15, 25),
    random_size_interval=10,
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=50, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    # In order to align the source code, the threshold of the val phase is
    # 0.01, and the threshold of the test phase is 0.001.
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))

# dataset settings
data_root = '../data/raw/'
dataset_type = 'CocoDataset'

albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]

train_pipeline = [
   dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='coco',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_masks': 'masks',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(-img_scale[0] // 2, -img_scale[1] // 2)),
    dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    # According to the official implementation, multi-scale
    # training is not considered here but in the
    # 'mmdet/models/detectors/yolox.py'.
    dict(type='Resize', img_scale=img_scale, keep_ratio=True),
    dict(
        type='Pad',
        pad_to_square=True,
        # If the image is three-channel, the pad value needs
        # to be set separately for each channel.
        pad_val=dict(img=(114.0, 114.0, 114.0))),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]

train_dataset = [
    dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'train/annotations/instances_train2017.json',
        img_prefix=data_root + 'train/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline)
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    persistent_workers=True,
    train=train_dataset,
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'train/annotations/instances_train2017.json',
        img_prefix=data_root + 'train/images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'val/annotations/instances_val2017.json',
        img_prefix=data_root + 'val/images/',
        pipeline=test_pipeline))

# optimizer
# default 8 gpu
optimizer = dict(
    type='SGD',
    lr=0.01,
    momentum=0.9,
    weight_decay=5e-4,
    nesterov=True,
    paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.))
optimizer_config = dict(grad_clip=None)

max_epochs = 300
num_last_epochs = 15
resume_from = None
interval = 10

# learning policy
lr_config = dict(
    _delete_=True,
    policy='YOLOX',
    warmup='exp',
    by_epoch=False,
    warmup_by_epoch=True,
    warmup_ratio=1,
    warmup_iters=5,  # 5 epoch
    num_last_epochs=num_last_epochs,
    min_lr_ratio=0.05)

runner = dict(type='EpochBasedRunner', max_epochs=max_epochs)

custom_hooks = [
    dict(
        type='YOLOXModeSwitchHook',
        num_last_epochs=num_last_epochs,
        priority=48),
    dict(
        type='SyncNormHook',
        num_last_epochs=num_last_epochs,
        interval=interval,
        priority=48),
    dict(
        type='ExpMomentumEMAHook',
        resume_from=resume_from,
        momentum=0.0001,
        priority=49)
]
checkpoint_config = dict(interval=interval)
evaluation = dict(
    save_best='auto',
    # The evaluation interval is 'interval' when running epoch is
    # less than ‘max_epochs - num_last_epochs’.
    # The evaluation interval is 1 when running epoch is greater than
    # or equal to ‘max_epochs - num_last_epochs’.
    interval=interval,
    dynamic_intervals=[(max_epochs - num_last_epochs, 1)],
    metric='bbox')
log_config = dict(interval=50)
# load_from = '/home/tcexeexe/dataDisk4/tianchi/ICME2022/mmdetection/weights/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth'

**Comment by tcexeexe** [comment]
see #7756
