### ISSUE TITLE
Evaluation failing: AttributeError: 'list' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by HarryPeverell** [open-mmlab/mmdetection#7752]
**Describe the bug**
I got this error when I want to use "recall" EVAL_METRICS to test my retinanet model trained by VOC dataset.

**I ran this command**
```none
python D:\mmdet_test_shell\mmdet_test\tools\test.py D:\mmdet_test_shell\work_dirs\retinanet\retinanet_voc_selfdefin_1219.py D:\mmdet_test_shell\work_dirs\retinanet\epoch_4.pth --eval recall
```

**Environment**
PyTorch: 1.6.0
TorchVision: 0.7.0
MMCV: 1.2.7
MMCV Compiler: MSVC 192729112
MMCV CUDA Compiler: 10.2
MMDetection: 2.11.0+

**Error traceback**
```none
  File "D:\mmdet_test_shell\mmdet_test\tools\test.py", line 220, in <module>
    main()
  File "D:\mmdet_test_shell\mmdet_test\tools\test.py", line 216, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "C:\Program Files\Python36\lib\site-packages\mmdet\datasets\voc.py", line 82, in evaluate
    gt_bboxes, results, proposal_nums, iou_thr, logger=logger)
  File "C:\Program Files\Python36\lib\site-packages\mmdet\core\evaluation\recall.py", line 95, in eval_recalls
    if proposals[i].ndim == 2 and proposals[i].shape[1] == 5:
AttributeError: 'list' object has no attribute 'ndim'
```

**Comment by hhaAndroid** [comment]
@HarryPeverell Thanks for your feedback, we'll check it.

**Comment by HarryPeverell** [comment]
numpy : 1.18.0
is numpy version related to this error?

**Comment by hhaAndroid** [comment]
@HarryPeverell I'm guessing not.

**Comment by NicholasCG** [comment]
I have encountered the same error running with a custom dataset. The error has occurred no matter what architecture I run, so I believe it is related to that.

**Comment by hhaAndroid** [comment]
@NicholasCG Is it resolved now?

**Comment by dialogueeeeee** [comment]
@hhaAndroid I also encountered this problem. Have you updated the modified code?

**Comment by nidham-sony** [comment]
I have corrected this by flattening the `proposals` which where a list of lists, each of them of length 1, of arrays into a list of arrays.

Here is the code snippet I added to `mmdet/core/evaluation/recall.py` at the very beginning of function `eval_recalls`:
```python
def eval_recalls(
    gts,
    proposals,
    proposal_nums=None,
    iou_thrs=0.5,
    logger=None,
    use_legacy_coordinate=False,
):
    """Calculate recalls.

    Args:
        gts (list[ndarray]): a list of arrays of shape (n, 4)
        proposals (list[ndarray]): a list of arrays of shape (k, 4) or (k, 5)
        proposal_nums (int | Sequence[int]): Top N proposals to be evaluated.
        iou_thrs (float | Sequence[float]): IoU thresholds. Default: 0.5.
        logger (logging.Logger | str | None): The way to print the recall
            summary. See `mmcv.utils.print_log()` for details. Default: None.
        use_legacy_coordinate (bool): Whether use coordinate system
            in mmdet v1.x. "1" was added to both height and width
            which means w, h should be
            computed as 'x2 - x1 + 1` and 'y2 - y1 + 1'. Default: False.


    Returns:
        ndarray: recalls of different ious and proposal nums
    """

    img_num = len(gts)
    assert img_num == len(proposals)
    proposal_nums, iou_thrs = set_recall_param(proposal_nums, iou_thrs)

    # List of lists of length 1 of arrays must be flattened
    # into list of of arrays
    if all(isinstance(sublist, np.ndarray) for sublist in proposals):
        proposals = proposals
    else:
        proposals = [sublist[0] for sublist in proposals]  # flatten proposals
        
    [...]
    return recalls
  ```

**Comment by hehesangsj** [comment]
> I have corrected this by flattening the `proposals` which where a list of lists, each of them of length 1, of arrays into a list of arrays.
> 
> Here is the code snippet I added to `mmdet/core/evaluation/recall.py` at the very beginning of function `eval_recalls`:
> 
> ```python
> def eval_recalls(
>     gts,
>     proposals,
>     proposal_nums=None,
>     iou_thrs=0.5,
>     logger=None,
>     use_legacy_coordinate=False,
> ):
>     """Calculate recalls.
> 
>     Args:
>         gts (list[ndarray]): a list of arrays of shape (n, 4)
>         proposals (list[ndarray]): a list of arrays of shape (k, 4) or (k, 5)
>         proposal_nums (int | Sequence[int]): Top N proposals to be evaluated.
>         iou_thrs (float | Sequence[float]): IoU thresholds. Default: 0.5.
>         logger (logging.Logger | str | None): The way to print the recall
>             summary. See `mmcv.utils.print_log()` for details. Default: None.
>         use_legacy_coordinate (bool): Whether use coordinate system
>             in mmdet v1.x. "1" was added to both height and width
>             which means w, h should be
>             computed as 'x2 - x1 + 1` and 'y2 - y1 + 1'. Default: False.
> 
> 
>     Returns:
>         ndarray: recalls of different ious and proposal nums
>     """
> 
>     img_num = len(gts)
>     assert img_num == len(proposals)
>     proposal_nums, iou_thrs = set_recall_param(proposal_nums, iou_thrs)
> 
>     # List of lists of length 1 of arrays must be flattened
>     # into list of of arrays
>     if all(isinstance(sublist, np.ndarray) for sublist in proposals):
>         proposals = proposals
>     else:
>         proposals = [sublist[0] for sublist in proposals]  # flatten proposals
>         
>     [...]
>     return recalls
> ```

That's useful, thanks a lot
