### ISSUE TITLE
Use my own dataset to use the faster-rcnn model

### ISSUE THREAD

**Issue by hjw-0909** [open-mmlab/mmdetection#7753]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
when I use my own dataset to use the faster-rcnn model,  I meet progarm bug.
I found that many people have similar problems, **but I have tried other people's solutions and it still doesn't work.**
I changed it based on other people's videos, others are successful.

I changed the following code:
(1) `configs/_base_/models/faster_rcnn_r50_fpn.py`
![image](https://user-images.githubusercontent.com/56182057/163971588-850efe07-5a4a-4dc1-bcab-b158313c0a8a.png)

(2)`mmdet/core/evaluation/class_names.py`
![image](https://user-images.githubusercontent.com/56182057/163971769-02a0479d-f99b-441c-9b1a-3dcd7d6ec689.png)

(3)`mmdet/datasets/coco.py`
![image](https://user-images.githubusercontent.com/56182057/163971869-f9ef9a04-c265-4b94-b714-cff06256c2e4.png)

(4)`configs/_base_/datasets/coco_detection.py`
![image](https://user-images.githubusercontent.com/56182057/163972170-8655aee5-261b-4d69-a556-d190fb11388d.png)

![image](https://user-images.githubusercontent.com/56182057/163972131-f48c283f-64ad-499d-af77-3582668b1b4f.png)

(5)my own dataset
![image](https://user-images.githubusercontent.com/56182057/163972317-daf48477-2fd7-4625-8be8-2fbd7f336975.png)

**Reproduction**

I use  `python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py`

**Error traceback**

```
assert module.num_classes == len(dataset.CLASSES), \
AssertionError: The `num_classes` (5) in Shared2FCBBoxHead of MMDataParallel does not matches the length of `CLASSES` 80) in CocoDataset
```

**Comment by hhaAndroid** [comment]
@hjw-0909 ` roi_head.bbox_head.num_classes=5`

**Comment by hjw-0909** [comment]
@hhaAndroid  Where is this added please?

**Comment by hjw-0909** [comment]
@hhaAndroid 
Is this what you're talking about? it doesn't work
![image](https://user-images.githubusercontent.com/56182057/163987013-d89905c3-ef09-45b5-aff4-fb4c65841ca3.png)

**Comment by yellowjs0304** [comment]
did you fix the problem? @hjw-0909 I met same issue.
