### ISSUE TITLE
Please,How do I add attention to ResNet?

### ISSUE THREAD

**Issue by Alxx999** [open-mmlab/mmdetection#7755]

**Comment by Y-M-Y** [comment]
You can turn to [configs of empirical_attention](https://github.com/open-mmlab/mmdetection/tree/master/configs/empirical_attention) and [configs of gcnet](https://github.com/open-mmlab/mmdetection/tree/master/configs/gcnet) for some reference. It can be added as a ResNet plugin.

**Comment by hhaAndroid** [comment]
@Alxx999 Thank you very much for your feedback, we will improve the documentation.
