### ISSUE TITLE
Usage of tools/deployment/test.py

### ISSUE THREAD

**Issue by habjoel** [open-mmlab/mmdetection#7757]
Hi there, 

I would like to use tools/deployment/test.py in order to test my exported onnx model. However, I am not entirely sure how to use it.

Below is the readthedocs description. I am not entirely sure whar exactly is meant by CONFIG_FILE and MODEL_FILE. I am assuming that CONFIG_FILE refers to the exported .onnx file. But what does MODEL_FILE refer to? Thanks for your help.

python tools/deployment/test.py \
    ${CONFIG_FILE} \
    ${MODEL_FILE} \
    --out ${OUTPUT_FILE} \
    --backend ${BACKEND} \
    --format-only ${FORMAT_ONLY} \
    --eval ${EVALUATION_METRICS} \
    --show-dir ${SHOW_DIRECTORY} \
    ----show-score-thr ${SHOW_SCORE_THRESHOLD} \
    ----cfg-options ${CFG_OPTIONS} \
    ----eval-options ${EVALUATION_OPTIONS} \

**Comment by jbwang1997** [comment]
CONFIG_FILE is the cfg in `configs` and the MODEL_FILE is the exported .onnx file.
