### ISSUE TITLE
Since the computer is inferior, how to run the code on the CPU?/由于电脑比较差，如何将代码跑在CPU上？

### ISSUE THREAD

**Issue by wenjun2022** [open-mmlab/mmdetection#7769]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by wenjun2022** [comment]
运行demo的代码如下：

import mmcv
from mmdet.apis import init_detector
from mmdet.apis import inference_detector
from mmdet.apis import show_result_pyplot
# from mmdet.models.detectors.base import BaseDetector

# 模型配置文件
config_file = r'F:\pythonProject\mmdet\mmdetection-master\configs\faster_rcnn\faster_rcnn_r50_fpn_1x_coco.py'#1.改1，这里是你fork的文件夹里面的config文件
# 预训练模型文件
# url: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
checkpoint_file = r'F:\pythonProject\mmdet\checkpoint\faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'#改2，这里是刚刚下载的权重文件
# 通过模型配置文件与预训练文件构建模型
model = init_detector(config_file, checkpoint_file, device='cuda:0')
# 测试单张图片并进行展示
# img = '/home/cv/mmdetection/my_pictures/cars1.jpeg'
img=r'F:\pythonProject\mmdet\138_GroundTruth.jpg'#改3，这里是图片的地址
result = inference_detector(model, img)
show_result_pyplot(model, img, result)

# 测试一个图像列表并保存结果图像
# imgs = ['test1.jpg', 'test2.jpg', 'test3.jpg']
# for i, result in enumerate(inference_detector(model, imgs)):
#     show_result_pyplot(model, imgs[i], result)
"""
# 
# (3)测试视频和显示测试结果
video = mmcv.VideoReader('demo/Venice-2.mp4')
for frame in video:
    result = inference_detector(model, frame)
    show_result(frame, result, model.CLASSES, wait_time=1)
"""
运行结果：
File "C:\Users\wenjun.zhong\.conda\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by RangiLyu** [comment]
change this line 
```python
model = init_detector(config_file, checkpoint_file, device='cuda:0')
```

to
```python
model = init_detector(config_file, checkpoint_file, device='cpu')
```
