### ISSUE TITLE
How to add focal to faster-rcnn ?

### ISSUE THREAD

**Issue by ztyxd** [open-mmlab/mmdetection#777]
I just change the bbox_head config:
  
bbox_head=dict(
        type='SharedFCBBoxHead',
        num_fcs=2,
        in_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=16,
        target_means=[0., 0., 0., 0.],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        reg_class_agnostic=False,
        #TODO use focal head for rcnn
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)))

and i also change the following code in the bbox_head.py

`        if cls_score is not None:
            losses['loss_cls'] = self.loss_cls(
                cls_score, labels, label_weights, reduce=reduce)`
to 
    ` if cls_score is not None:
            losses['loss_cls'] = self.loss_cls(
                cls_score, labels, label_weights)` 

becuase I think the focal loss do not have parameters reduce and the class_nums in focal loss i also changed .

After this change , I can run the code, but the acc is too low

2019-06-10 16:26:17,280 - INFO - Epoch [1][100/4325]	lr: 0.00233, eta: 13:26:28, time: 0.911, data_time: 0.005, memory: 6392, loss_rpn_cls: 0.3528, loss_rpn_bbox: 0.0901, loss_cls: 0.0506, acc: 35.4297, loss_bbox: 0.1366, loss: 0.6301

Can U give me some suggesion about how to use the focal loss in the fatser-rcnn bbox_head

**Comment by bxhandhxb** [comment]
excuse me , I met the similar mistake.  Have you solved it??

**Comment by zhengjiawen** [comment]
> excuse me , I met the similar mistake. Have you solved it??

Have you solve the problem?

**Comment by ztyxd** [comment]
I think the focal loss in this code is sigmoid you should change it to the softmax focal loss when you use focal loss in the rcnn head



---Original---

**Comment by zhengjiawen** [comment]
> I think the focal loss in this code is sigmoid you should change it to the softmax focal loss when you use focal loss in the rcnn head
> […](#)
> ---Original--- From: "zhengjiawen"<notifications@github.com&gt; Date: Tue, Sep 17, 2019 13:09 PM To: "open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;; Cc: "State change"<state_change@noreply.github.com&gt;;"zty"<810289611@qq.com&gt;; Subject: Re: [open-mmlab/mmdetection] How to add focal to faster-rcnn ? (#777) excuse me , I met the similar mistake. Have you solved it?? Have you solve the problem? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks a lot.

**Comment by ztyxd** [comment]
change the CE loss with focal loss in the rcnn head



---Original---

**Comment by bxhandhxb** [comment]
thanks a lot

**Comment by wikiwen** [comment]
> change the CE loss with focal loss in the rcnn head

Dose it means to modify the config code in bbox_head?
```python
# loss_cls=dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
loss_cls=dict(type='FocalLoss', use_sigmoid=True, gamma=2.0, alpha=0.25, loss_weight=1.0),
```
This change still have the problem with low acc.

**Comment by wikiwen** [comment]
> I think the focal loss in this code is sigmoid you should change it to the softmax focal loss when you use focal loss in the rcnn head
If so, why Retinanet use the  sigmoid focal loss? The net also have multiclass.

**Comment by ztyxd** [comment]
use the focal loss in the rcnn head you should change the sigmoid focal loss to softmax focal loss.&nbsp;&nbsp;
because the loss in the rcnn head is softmax but the proposed focal loss is based on sigmoid&nbsp;





---Original---

**Comment by LoserSun** [comment]
Hi,  I also meet a similar mistake.  Have you solved it??
