### ISSUE TITLE
Role of IoU-Assigner durring Evaluation

### ISSUE THREAD

**Issue by Unlucky910** [open-mmlab/mmdetection#7772]
Hi guys,
i have a question regarding the ''assigner'' during Evaluation.
Because during evaluation we evaluate the model with different IoU-Values [0.5, 0.55, .... 0.95].
In the Config we specify a fixed IoU-Value for true positive or negative.

So how does it work during the evaluation process?

Kind regards

**Comment by RangiLyu** [comment]
Assigner is only used during training time.
