### ISSUE TITLE
How to link with the backbone which is NOT in mmdet package?

### ISSUE THREAD

**Issue by jacob-kang** [open-mmlab/mmdetection#7773]
To describe details,
I want to modify some part of renset.
So I modified the resnet backbone in mmdetection/mmdet/models/backbones/resnet.py

But when the train starts, It is linked the renet which is site-package/mmdet/models/backbones/resnet.py

The second resnet is in the package. And I don't want to modify the package. (I think It should stay original.)
How can I use selectively those resnet?

**Comment by RangiLyu** [comment]
You can install mmdetection with editing mode.
Just run `pip install -e .` in your mmdetection folder.

**Comment by jacob-kang** [comment]
Thanks. I just delete mmdet.
