### ISSUE TITLE
Why use img_norm in from scratch training?

### ISSUE THREAD

**Issue by Unlucky910** [open-mmlab/mmdetection#7774]
Hi i am wondering why you used image norm for ImageNet even if you train from scratch for COCO?

https://github.com/open-mmlab/mmdetection/blob/master/configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py

**Comment by ZwwWayne** [comment]
It is just a convention to normalize the image by the norm on ImageNet since it is large and the values should be representative and general.
