### ISSUE TITLE
How to change the size and color of the recognition box

### ISSUE THREAD

**Issue by hjw-0909** [open-mmlab/mmdetection#7777]
code I used:
`python demo/video_demo.py resources/b5_up_4_0240-0320.MP4 configs/faster_rcnn/faster_rcnn_r101_fpn_2x_coco.py work_dirs/faster_rcnn_r101_fpn_2x_coco/latest.pth --out results/2.mp4`

But the verification box of the final output video is not very clear, I want to change the color and font size of the box.
![image](https://user-images.githubusercontent.com/56182057/164429256-2f3695fb-4ab2-413c-90d8-1a56876b4ec4.png)

**Comment by RangiLyu** [comment]
You can modify this function https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/mmdet/core/visualization/image.py#L112

**Comment by hjw-0909** [comment]
@RangiLyu  I have tried it,but it not worked.

**Comment by RangiLyu** [comment]
Did you install mmdetection by editing mode? Try to run `pip install -e .` in your mmdetection folder again.

**Comment by hjw-0909** [comment]
@RangiLyu  Oh,it works, thank you very much.
