### ISSUE TITLE
update mmdetection, run x101 model,TypeError

### ISSUE THREAD

**Issue by GYxiaOH** [open-mmlab/mmdetection#778]
today , I upadate my mmdetection , but when i run x101,  TypeError: __init__() got multiple values for argument 'groups'.
why? i don't meet this question before,and when use old version(about one month ago), this question will not appear

**Comment by GYxiaOH** [comment]
change mmdet/models/backbones/resnext.py 14 lines    def __init__(self, groups=1, base_width=4, *args, **kwargs):
to
    def __init__(self,  *args,groups=1, base_width=4, **kwargs):

**Comment by eduramiba** [comment]
I had this problem today too. I think issue should be reopened.

**Comment by hellock** [comment]
Thanks for reporting! This bug was introduced in #730, and should be fixed in #780.

**Comment by eduramiba** [comment]
Thanks @hellock !
