### ISSUE TITLE
Any way to use inference_detector with multiple GPUs?

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#7787]
Hello,

I am currently working with a dataset that contains many gigapixel images (some of them 20+ gigapixels), for which I need to produce overlapping predictions. I do not want to save individual crops, as this will result in unreasonable storage requirements. I therefore cannot load these crops using traditional coco json files to then run dist_test.sh. For training, I realize I must use crops (unless you know of some clever solution, would be very much appreciated).

Currently my solution is to use the `inference_detector` functionality on batches of np arrays extracted from my gigapixel images; this works very well, but I can currently only use a single GPU. Is there any way to run `inference_detector` on multiple GPUs with np arrays as inputs?

**Comment by RangiLyu** [comment]
The inference_detector does not support parallel. And if you do not want to use the test.py, you may need to implement a distributed inference script.

**Comment by pcicales** [comment]
Thank you @RangiLyu I will look into it. Closing.

**Comment by sgw-ite** [comment]
Have the same problem, have you finished? Thanks~
