### ISSUE TITLE
RuntimeError: nms_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by jinyaxuan** [open-mmlab/mmdetection#7788]
这个是什么问题啊 卡好久了

**Comment by BIGWangYuDong** [comment]
Similar issue: https://github.com/open-mmlab/mmdetection/issues/6765
Please use the issue template.

**Comment by EmreOzkose** [comment]
Is it solved?

**Comment by EmreOzkose** [comment]
I found solution. I installed mmcv with only `pip install mmcv`. However when I uninstall and install with `pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html`, then problem is solved.

**Comment by ruler77** [comment]
> I found solution. I installed mmcv with only `pip install mmcv`. However I think it is wrong way to install.
> 
> Solution: When I uninstall and install with `pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html`, then problem is solved.

It works.

**Comment by rishabh279** [comment]
> I found solution. I installed mmcv with only `pip install mmcv`. However I think it is wrong way to install.
> 
> Solution: When I uninstall and install with `pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html`, then problem is solved.

Working for me as well!

**Comment by Hoteryoung** [comment]
Based on my experience, the Cuda version matters. If `pip install xxx -f xxx` would work, you'd better try a different Cuda version.

**Comment by zgerem** [comment]
> I found solution. I installed mmcv with only `pip install mmcv`. However I think it is wrong way to install.
> 
> Solution: When I uninstall and install with `pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html`, then problem is solved.

hey, I tried the same thing but kept getting the same error. I also use 

> I found solution. I installed mmcv with only `pip install mmcv`. However I think it is wrong way to install.
> 
> Solution: When I uninstall and install with `pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html`, then problem is solved.

Hey, I have the same environment and tried it but I keep getting the same error. which python do you use?
