### ISSUE TITLE
OpenAPI no response or respose 401

### ISSUE THREAD

**Issue by A971RM** [open-mmlab/mmdetection#7791]
Refer：https://platform.openmmlab.com/docs/zh-CN/open-api/guides/object-detection
Use myself access token，Test in PostMan, Results:
{
    "timestamp": "2022-04-23T01:35:37.422+0000",
    "error": "Internal Server Error",
    "msgCode": "A0202",
    "status": 401,
    "msg": "access denied"
}

Refer：https://platform.openmmlab.com/web-demo/demo/detection
Change Post Url：https://open.openmmlab.com/gw/model-inference/openapi/v1/detection
Reponse：
Could not send request
Error: Client network socket disconnected before secure TLS connection was established

**Comment by chhluo** [comment]
Your access_token is  expired. You should get a new access_token.

**Comment by A971RM** [comment]
> Your access_token is expired. You should get a new access_token.

I don't think so. I follow the https://platform.openmmlab.com/user/accesskey I don't see any expired information.

**Comment by chhluo** [comment]
Access Key and Secret Key are not expired, but the access_token are expired. I met the same problem with you when I use a old access_token. I solved the problem with a new access_token.

**Comment by A971RM** [comment]
> Access Key and Secret Key are not expired, but the access_token are expired. I met the same problem with you when I use a old access_token. I solved the problem with a new access_token.
The main functions:
if __name__ == '__main__':
    accessToken = get_access_token()
    ret = upload_file(accessToken=accessToken, tag="segmentation", files=[r'./data/fire.jpg'])
    print(ret)
    ret = classification_example(accessToken=accessToken)
    print(ret)

If the access_token is expired, do you help me check the get_access_token: 
def get_access_token():
    """
    第二步：获取令牌
    参考： https://platform.openmmlab.com/docs/zh-CN/open-api/steps/get-token
    :return:
    """
    ts = str(int(time.time()))
    nonce = get_nonce()
    accessKey = AccessKey
    secretKey = SecretKey

    uri = "/api/v1/openapi/auth"
    sign = get_sign(uri, ts, nonce, accessKey, secretKey)

    Host = r"https://platform.openmmlab.com"
    Path = r"/gw/user-service/api/v1/openapi/auth"

    Headers = dict(ts=ts, nonce=nonce, sign=sign, accessKey=accessKey)

    url = urljoin(Host, Path)
    response = requests.post(url, headers=Headers)
    if response.ok and response.json().get('msg', '') == 'ok':
        accessToken = response.json()['data']['accessToken'][len('Bearer'):].strip()
        return accessToken
    raise ValueError(f"Cannot get {response.url}")


The access_token is from the OpenAPI. I don't know why it is expired.

**Comment by A971RM** [comment]
def get_nonce():
    """
    得到nouce值
    :return:
    """
    population = string.digits + string.ascii_letters
    k = 10
    ret = random.choices(population, k=k)
    ret = ''.join(ret)
    return ret


def get_sign(uri, ts, nonce, accessKey, secretKey):
    """
    返回根据签名规则生成的签名
    :param uri:
    :param ts:
    :param nonce:
    :param accessKey:
    :param secretKey:
    :return:
    """
    sign_rule = OrderedDict(uri=uri, ts=ts, nonce=nonce, accessKey=accessKey, secretKey=secretKey)
    sign_strs = [f"{k}={v}" for k, v in sign_rule.items()]
    sign_str = "&".join(sign_strs)
    sign = hashlib.sha256(sign_str.encode("utf-8")).hexdigest()
    return sign

**Comment by chhluo** [comment]
Your problem is not the same with mine. Your access_token is not expired, but the method to get access_token is wrong.
"Bearer " is part of access_token.

`accessToken = response.json()['data']['accessToken'][len('Bearer'):].strip()` -> `accessToken = response.json()['data']['accessToken']`

**Comment by chhluo** [comment]
Sorry. This description is wrong.

![image](https://user-images.githubusercontent.com/26483343/165039774-aa5aca52-799b-499b-a5f8-9b882ac0ec4e.png)

**Comment by A971RM** [comment]
Thank you very much. I misunderstood.
