### ISSUE TITLE
[Bug] Bug in resnet's plugin

### ISSUE THREAD

**Issue by Mountchicken** [open-mmlab/mmdetection#7795]
**Describe the bug**
- In the ResNet implementation of MMDET, there seems to be a problem in function [forward_function](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L242)
```python
  def forward_plugin(self, x, plugin_names):
      out = x
      for name in plugin_names:
          out = getattr(self, name)(x)
      return 
```
- If we have multiple plugins at one position, then, only the last one is valid

**Bug fix**
```python
  def forward_plugin(self, x, plugin_names):
      out = x
      for name in plugin_names:
          out = getattr(self, name)(out)
      return 
```

**Comment by chhluo** [comment]
This is a bug. Thank you very much.
