### ISSUE TITLE
"KeyError: "FCOS: 'DWHead is not in the models registry'"

### ISSUE THREAD

**Issue by GF1447571253** [open-mmlab/mmdetection#7796]
I cloned the whole [DW](https://github.com/strongwolf/DW) code into a place which is outside the mmdet folders.I directly run the code and then I got a error which showed  "KeyError: "FCOS: 'DWHead is not in the models registry'"

**Comment by chhluo** [comment]
you should import these custom modules. Please add the following code in config file you run, refer to https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#.
```python
custom_imports=dict(
    imports=[
        'path to DWHead'
])
```
There is an example: https://github.com/ZwwWayne/K-Net/blob/5e50ee58957dce972f51096804ff69171c2f072e/configs/det/_base_/models/knet_s3_r50_fpn.py#L140

**Comment by GF1447571253** [comment]
It works, thank you for your help
