### ISSUE TITLE
CentripetalNet missing from the overview table in the readme

### ISSUE THREAD

**Issue by tikitong** [open-mmlab/mmdetection#7798]
**Checklist**

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
 - [x] 3. The bug has not been fixed in the latest version.

**Describe the bug**
The detector seems to be missing in the _object detection_ column in the [readme](https://github.com/open-mmlab/mmdetection#overview-of-benchmark-and-model-zoo).

**Comment by chhluo** [comment]
Thanks for reminding us, we'll add it soon.
