### ISSUE TITLE
How Can i apply Mask2former to instance segmentation?

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmdetection#7801]
Is there any config file for applying it to instance segmentation.

**Comment by chhluo** [comment]
If you want to do inference for instance segmentation, you can use the config for [panoptic segmentation](https://github.com/open-mmlab/mmdetection/tree/dev/configs/mask2former). And there is a pr for instance segmentation, which is almost finished (we are verifying its performance) https://github.com/open-mmlab/mmdetection/pull/7571.

**Comment by dsp6414** [comment]
已收到！

**Comment by dsp6414** [comment]
This really is a good news，thx you!
