### ISSUE TITLE
我想在atss中只把损失函数改成QualityFocalloss  但是发现代码能运行 mAP测试为0

### ISSUE THREAD

**Issue by sharp-xiang** [open-mmlab/mmdetection#7802]
[20220423_211131.log](https://github.com/open-mmlab/mmdetection/files/8547466/20220423_211131.log)

**Comment by chhluo** [comment]
![image](https://user-images.githubusercontent.com/26483343/164913898-8932bc8d-1cbb-446b-8e22-c8a3f0656244.png)

Your modification to atss to in favor of QualityFocalloss seems have problems. The loss_cls is 0 after some iterations.
