### ISSUE TITLE
Visual Attention Network (VAN) for objection

### ISSUE THREAD

**Issue by zkloveai** [open-mmlab/mmdetection#7805]
hello，can you support Visual Attention Network for objection，such as faster rcnn？

**Comment by zkloveai** [comment]
> hello，can you support Visual Attention Network for objection，such as faster rcnn？

thanks a lots！！！！！

**Comment by ZwwWayne** [comment]
Seems that they are supported in https://github.com/Visual-Attention-Network/VAN-Segmentation, which is based on MMSeg. It will be easy to copy the code in mmdet. For now, the team has limited resources, so PRs are welcomed.

**Comment by Ezra-Yu** [comment]
VAN backbone is under development in MMCLassification, here is [the PR](https://github.com/open-mmlab/mmclassification/pull/739).  

you can learn how to use 'MMCls.backbone' in MMDet from this [example](https://github.com/open-mmlab/mmdetection/blob/master/configs/timm_example/retinanet_timm_efficientnet_b1_fpn_1x_coco.py) .

**Comment by ZwwWayne** [comment]
Closed as it will be supported in mmcls.
