### ISSUE TITLE
How to apply Anchor Free onto Faster RCNN or Cascade RCNN?

### ISSUE THREAD

**Issue by TalentedMUSE** [open-mmlab/mmdetection#7809]
Hello, I want to apply anchor free mechanism onto two-stage detectors, but I found that only 【FreeAnchorRetinaHead】is provided in the config files. Could you please provide some example config files about the aforementioned issue? Thanks a lot~

**Comment by ZwwWayne** [comment]
For now, there will be some small issues when the anchor free detector is used in two-stage detectors. But we will support it in near future. Please stay tuned.
