### ISSUE TITLE
AssertionError:MixuporMosaic

### ISSUE THREAD

**Issue by ismeFUFU** [open-mmlab/mmdetection#7825]
I set up the data enhancement method of Mixup and Mosaic according to the official documentation and yolox.config, but it failed, and the following error occurred.
Traceback (most recent call last):
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/cdzk/PYC/code/fewmmdetection/mmdet/datasets/pipelines/transforms.py", line 2006, in __init__
    assert isinstance(img_scale, tuple)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 221, in <module>
    main()
  File "tools/train.py", line 197, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/cdzk/PYC/code/fewmmdetection/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = MultiImageMixDataset(**cp_cfg)
  File "/home/cdzk/PYC/code/fewmmdetection/mmdet/datasets/dataset_wrappers.py", line 380, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/cdzk/anaconda3/envs/fu-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: Mosaic:

**Comment by Czm369** [comment]
More details, such as configs.

**Comment by ismeFUFU** [comment]
train_pipeline = [
    dict(type='MixUp', img_scale=[(1720,1000),(1720,800)],ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='Resize', img_scale=[(1720,1000),(1720,800)],multiscale_mode='range', keep_ratio=True),

    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_train2017.json',
        img_prefix='data//train/images',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline
    )
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=train_dataset,
    val=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline),
    test=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline))

**Comment by ismeFUFU** [comment]
> More details, such as configs.

train_pipeline = [
dict(type='MixUp', img_scale=[(1720,1000),(1720,800)],ratio_range=(0.8, 1.6),
pad_val=114.0),
dict(type='Resize', img_scale=[(1720,1000),(1720,800)],multiscale_mode='range', keep_ratio=True),

dict(type='RandomFlip', flip_ratio=0.5),
dict(
    type='Normalize',
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True),
dict(type='Pad', size_divisor=32),
dict(type='DefaultFormatBundle'),
dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
train_dataset = dict(
type='MultiImageMixDataset',
dataset=dict(
type='CocoDataset',
ann_file='data//train/annotations/instances_train2017.json',
img_prefix='data//train/images',
pipeline=[
dict(type='LoadImageFromFile', to_float32=True),
dict(type='LoadAnnotations', with_bbox=True, with_mask=True)
],
filter_empty_gt=False,
),
pipeline=train_pipeline
)
data = dict(
samples_per_gpu=2,
workers_per_gpu=2,
train=train_dataset,
val=dict(
type='CocoDataset',
ann_file='data//train/annotations/instances_val2017.json',
img_prefix='data//train/images',
pipeline=test_pipeline),
test=dict(
type='CocoDataset',
ann_file='data//train/annotations/instances_val2017.json',
img_prefix='data//train/images',
pipeline=test_pipeline))

**Comment by ismeFUFU** [comment]
> More details, such as configs.
train_pipeline = [
    dict(type='MixUp', img_scale=[(1720,1000),(1720,800)],ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='Resize', img_scale=[(1720,1000),(1720,800)],multiscale_mode='range', keep_ratio=True),

    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_train2017.json',
        img_prefix='data//train/images',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline
    )
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=train_dataset,
    val=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline),
    test=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline))

**Comment by ismeFUFU** [comment]
> More details, such as configs.
train_pipeline = [
    dict(type='MixUp', img_scale=[(1720,1000),(1720,800)],ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='Resize', img_scale=[(1720,1000),(1720,800)],multiscale_mode='range', keep_ratio=True),

    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_train2017.json',
        img_prefix='data//train/images',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline
    )
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=train_dataset,
    val=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline),
    test=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline))

**Comment by Czm369** [comment]
It seems that you do not using Mosaic?

**Comment by ismeFUFU** [comment]
> 

Because mixup and mosaic are used in the same way

**Comment by ismeFUFU** [comment]
> It seems that you do not using Mosaic?

train_pipeline = [
    dict(type='Mosaic', img_scale=[(1720,1000),(1720,800)], pad_val=114.0),
    dict(type='Resize', img_scale=[(1720,1000),(1720,800)],multiscale_mode='range', keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_train2017.json',
        img_prefix='data//train/images',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline
    )
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=train_dataset,
    val=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline),
    test=dict(
        type='CocoDataset',
        ann_file='data//train/annotations/instances_val2017.json',
        img_prefix='data//train/images',
        pipeline=test_pipeline))

**Comment by littleduck007** [comment]
Did you solve this problem? I also encountered the same problem with you

**Comment by ismeFUFU** [comment]
Sorry,I didn't.Maybe you could refer to yolox in mmdetection.



At 2022-05-26 22:04:46, "littleduck007" ***@***.***> wrote:

Did you solve this problem? I also encountered the same problem with you
