### ISSUE TITLE
Any plans to add MobileNetV3, ShuffleNetV2？

### ISSUE THREAD

**Issue by TalentedMUSE** [open-mmlab/mmdetection#7828]
**Motivation**
Perform light-weight backbones for real-time object detection

**Comment by Czm369** [comment]
Maybe you can try to use backbone network implemented in MMClassification
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/how_to.md#use-backbone-network-implemented-in-mmclassification
