### ISSUE TITLE
does Faster RCNN have a version of the pre-training model in addition to the Coco dataset

### ISSUE THREAD

**Issue by will-wiki** [open-mmlab/mmdetection#7829]
Hi, does Faster RCNN have a version of the pre-training model in addition to the Coco dataset, such as the Visual Genome dataset? In addition, I have here the model of Faster RCNN_Resnet101 trained by other frameworks, how can I reuse it into this framework?

**Comment by hhaAndroid** [comment]
@will-wiki We do not yet support the Visual Genome dataset. If you want to use models from other frameworks, you just need to write a conversion script, for example https://github.com/open-mmlab/mmdetection/blob/master/tools/model_converters

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 13 days.
