### ISSUE TITLE
About using new custom dataset

### ISSUE THREAD

**Issue by 534145232** [open-mmlab/mmdetection#7830]
I have a question, If I use one new dataset, should I modify anywhere to fit the size of new images? For example, the size of image in my dataset is 1024 * 540, should I modify some configure of the existing model?
(I saw there is a resize-(1333, 800) in coco_detection.py, should I modify it?)

**Comment by hhaAndroid** [comment]
@534145232 This parameter can be modified. Different datasets are indeed different.

**Comment by 534145232** [comment]
> @534145232 This parameter can be modified. Different datasets are indeed different.

Yeah...I mean does this parameter **could** or **must** be modified?

**Comment by hhaAndroid** [comment]
@534145232 Can not be modified
