### ISSUE TITLE
How to fulluse the multi-gpus on a single machine

### ISSUE THREAD

**Issue by A971RM** [open-mmlab/mmdetection#7834]
We have a single machine with 8 GPUs, we want to train model to fulluse the 8 GPUs.
I have followed the command: refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/en/1_exist_data_model.md
bash ./tools/dist_train.sh \
    ${CONFIG_FILE} \
    ${GPU_NUM} \
    [optional arguments]
bash ./tools/dist_train.sh configs/faster_rcnn/faster_rcnn_r50_fpn_1x_didi.py 8
But output stucked as:
(ltp_py3.7) [yjs001@gpu05 mmdetection]$ bash ./tools/dist_train.sh configs/faster_rcnn/faster_rcnn_r50_fpn_1x_didi.py 8
/share/apps/anaconda3/envs/ltp_py3.7/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/share/home/yjs001/names/zyx/code62/mmdetection/mmdet/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '

**Comment by hhaAndroid** [comment]
@A971RM This is just a warning and will not affect training.

**Comment by A971RM** [comment]
Thanks, but is it normal that the output does not show anything more a very long time? I can't know whether the process is running or the single machine, mutli-gpus is waiting for network port to receive request? How I check？

**Comment by hhaAndroid** [comment]
@A971RM I suggest that you first verify whether it is normal with a single GPU. Then please post the log of multi-GPU training.

**Comment by A971RM** [comment]
Thank you very much.

**Comment by develop-productivity** [comment]
> Thanks, but is it normal that the output does not show anything more a very long time? I can't know whether the process is running or the single machine, mutli-gpus is waiting for network port to receive request? How I check？

have you solved this problems? I encounter the same problem as you.
Multi-gpus distributed training gets stuck below:
```
UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
```

**Comment by stas-polukeev** [comment]
@develop-productivity Hey there! faced the same problem. Have you found any solution?

**Comment by develop-productivity** [comment]
> have you solved this problems? I encounter the same problem as you.
> Multi-gpus distributed training gets stuck below:

Hi, it's just a warning and does not affect the normal runing of the program. Just ignore it.
Best!
