### ISSUE TITLE
test_robustness has error

### ISSUE THREAD

**Issue by jacob-kang** [open-mmlab/mmdetection#7835]
I just want to see the robustness result of my model.
But It can not operated 
`python tools/analysis_tools/test_robustness.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --eval bbox --corruptions all`

Due to 316th line of test_robustness, I must give arguments --out. Simply, I must create some pickle file and There is no where explanation about the Pickle out file. And I can't find where to use that pickle file.

If you don't give --out args,
In `if args.out and rank == 0:`, you have rank but no args.out. 
So it skips `aggregated_results[corruption][                                corruption_severity] = eval_results` 333,334th line.
Than you don't have `aggregated_results[corruptions[0]][0]` then you will severe the error from 255,256th line.

**Comment by hhaAndroid** [comment]
@jacob-kang  `out` is the output result parameter, you don't need to input the pickle file.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 12 days.
