### ISSUE TITLE
instance segmentation on ONNX Runtime error: unmatching input dimensions

### ISSUE THREAD

**Issue by habjoel** [open-mmlab/mmdetection#7836]
Hey!

I exported the Swin-S model using tools/deploy.py from MMDeploy (I know that  it is not supported yet but it worked flawlessly nonetheless). 

Now I am trying to get the whole thing running on ONNX Runtime (with Python API). I tried feeding the image to the model by converting it to an np.array and transposing it so that the data of the image is represented as [channel, height, width] but I keep getting the following error:

[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: input Got: 3 Expected: 4 Please fix either the inputs or the model.

So I guess the data of the provided image needs to have 4 dimensions. Looking at the configs of MMDeploy the image must be of shape [1, 3, height, width]. But what is the value that needs to be stored in this first dimension and how can I add it?

I would be very thankful if someone familiar with this could help me out! Thanks a lot.

Below the code in python to reproduce:

import numpy as np
import onnx
from onnx import numpy_helper
import onnxruntime as ort
from PIL import Image

img = Image.open('bottle.jpg')
'# Convert to BGR
img = np.array(img)[:, :, [2, 1, 0]].astype('float32')
'# HWC -> CHW
img = np.transpose(img, [2, 0, 1])

boxes, labels, scores, masks = ort_session.run(None, {
    ort_session.get_inputs()[0].name: img
})

**Comment by hhaAndroid** [comment]
@habjoel Please go to mmdeploy to create an issue

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 12 days.
