### ISSUE TITLE
robustness_eval.py question?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#7838]
Could you please tell me how to use robustness_eval.py?
And when i run the **train.py**, i couldn't get the **AP and each category AP**, how can i fix this? 
If i finish the train, do you have any method to get AP and each category AP?

**Comment by jbwang1997** [comment]
You can refer to [this document](https://github.com/open-mmlab/mmdetection/blob/b9fe21679f0cfa855fc5cb5ca12a1edf1f6d7b34/docs/en/robustness_benchmarking.md) for the usage of `test_robustness.py` which is more general using than `robustness_eval.py`.

For each category AP, if your use CocoDataset, you can set the the `classwise` as `True` at [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L597) to enable showing classwise AP.

**Comment by lijoe123** [comment]
Thank you!
I occur this situation! The result of train can't get the evaluation result,like that:
![solov2](https://user-images.githubusercontent.com/86214036/165668779-a2b2ab7d-0fab-4264-96b9-969f981347b0.jpg)

@jbwang1997

**Comment by jbwang1997** [comment]
Make sure you enable the eval_hook in config. `evaluation = dict(interval=1, metric=['bbox'])`

**Comment by lijoe123** [comment]
Thank you for your answer! @jbwang1997 
In this situation, may i use the **test_robustness.py** to evaluate my model? Could you please give me a demo, I have tried the **test_robustness.py**, but it can't work..

**Comment by jbwang1997** [comment]
Sorry, but I haven't got your questions. Do you mean using test_robustness.py in evaluation?

`test_robustness.py` is a script to test the model robustness under different corruptions. For now, it hasn't been supported in evaluation. You need to save the model of each epoch and run test_robustness.py separately.

**Comment by lijoe123** [comment]
Thank you! 
So how i can evaluate the model after i finish the train? i can't get the evaluate like the pic.

**Comment by jbwang1997** [comment]
This issue will be closed. Feel free to reopen this pr if you have any questions.
