### ISSUE TITLE
KeyError: 'ori_filename' in testing the config named centernet_resnet18_dcnv2_140e_coco.py

### ISSUE THREAD

**Issue by pure19990902** [open-mmlab/mmdetection#7842]
Maybe 'filename' should be corrected in 'ori_filename' in line 81 of the file named centernet_resnet18_dcnv2_140e_coco.py.

meta_keys=('filename', 'ori_shape', 'img_shape', 'pad_shape',
                           'scale_factor', 'flip', 'flip_direction',
                           'img_norm_cfg', 'border'),

corrected:
meta_keys=('ori_filename', 'ori_shape', 'img_shape', 'pad_shape',
                           'scale_factor', 'flip', 'flip_direction',
                           'img_norm_cfg', 'border'),

**Comment by pure19990902** [comment]
When I test the CenterNet model  and add the "--show-dir"  to visualize the detection results on images,  the error occur.
The erroe message is "KeyError: 'ori_filename'".
Is my solution reasonable?

**Comment by jbwang1997** [comment]
Oh, you are correct. this is a bug in showing results. We will fix it as soon as possible. Thank you very much for the bug report again.
