### ISSUE TITLE
The test error of centernet_resnet18_dcnv2...

### ISSUE THREAD

**Issue by pure19990902** [open-mmlab/mmdetection#7843]
According to my own dataset, I created my centernet_resnet18_dcnv2_1x_mydataset.py. I have trained it and there is no problem. The final AP is good.
However, when I test the model and want to visualize the final detection results in inages(by add the "--show-dir"), I found something went wrong in those tested images. The detection boxes do not match the targets in the images. I notice the whole image has shifted and black bands appear on the left and top of the image.
I think the detection boxes are right and the problem may happen in images in show_result.
I try to solve the problem but failed.

**Comment by hhaAndroid** [comment]
@pure19990902 This is because the revert logic is wrong when visualizing in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/test.py#L46

**Comment by youmingdeng** [comment]
@pure19990902 
just replace https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/test.py#L43 with
top, bottom, left, right = list(map(int, img_meta['border']))
img_show = img[top:bottom, left:right, :]
