### ISSUE TITLE
The grad_norm goes too big during the training of fcos_pvt_b2.

### ISSUE THREAD

**Issue by Y-M-Y** [open-mmlab/mmdetection#7845]
The value of grad_norm in some batches goes too big from 100 to 542434612635249.6250 to **inf** to **nan** (in epoch14).

changes:
1. my own dataset
2. change backbone to pvtv2_b2
3. samples per gpu=2 and workers per gpu=1

My own dataset worked well in other models.
I have tried to set the max_norm of grad_clip to 300 but it occurred the same problem.

Here's the config and training log.
[config and logjson.zip](https://github.com/open-mmlab/mmdetection/files/8572668/config.and.logjson.zip)

**Comment by jbwang1997** [comment]
You can refer to [this document](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/faq.md#training) for `loss goes Nan` question. In this case, it may be caused by having some illegal boxes in your dataset.

**Comment by Y-M-Y** [comment]
> You can refer to [this document](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/faq.md#training) for `loss goes Nan` question. In this case, it may be caused by having some illegal boxes in your dataset.

Thanks!
In fact, the loss converges well. The problem is that the grad_norm of several batches is very large. The most likely reason is Exploding Gradients.
The grad_clip is used in the config, but it didn't work.

**Comment by jbwang1997** [comment]
It's weird. Seems the loss is normal but some iterations' grad_norm explode. I consider that some boxes in the dataset are illegal. For example, the left-top point is at the right of the right-bottom point. Please first check the dataset and make sure all objects are correct.

**Comment by Y-M-Y** [comment]
@jbwang1997 Thanks a lot. I will try to visualize my own dataset to check. BTW, do MMdet offer tools to check whether the coco style dataset is valid?

**Comment by Y-M-Y** [comment]
I've visualized my dataset, and everything is ok. The error might not come from the dataset. I guess maybe the transformer backbone is just hard to train.

**Comment by zhaoyangwei123** [comment]
@Y-M-Y May I ask if you have solved this problem? I also have this problem.

**Comment by Y-M-Y** [comment]
> @Y-M-Y May I ask if you have solved this problem? I also have this problem.

I solved part of the problem :) The training process using pvtv2_b0/b1/b3 as backbone worked well. But it still didn't work with pvtv2_b2. So, I gave up using pvtv_b2.
