### ISSUE TITLE
The output .JSON file is full of [Object Object]

### ISSUE THREAD

**Issue by hustCYQ** [open-mmlab/mmdetection#7846]
I run the command:
./tools/dist_test.sh ./configs/_bases/swin_.py ./work_dir/20220427/swin_transformer/epoch_12.pth 4 --format-only --options "jsonfile_prefix=./results_4_"

But the output .JSON file is full of [Object Object]

The config file and .pth file  both exist. I can get .json file correctly using a GPU by command:
python ./tools/test.py ./configs/_bases/swin_.py ./work_dirs/swin_ali/latest.pth --format-only --options  "jsonfile_prefix=result.json"

I don't know what went wrong.

**Comment by jbwang1997** [comment]
Could you provide more information, like the config and the sample of the .JSON file.

**Comment by hustCYQ** [comment]
> Could you provide more information, like the config and the sample of the .JSON file.

![image](https://user-images.githubusercontent.com/39451786/165658741-c5deae94-d15e-4237-a776-81e029f0f694.png)
The whole file is like this [object object]

**Comment by jbwang1997** [comment]
https://github.com/open-mmlab/mmdetection/blob/bde7b4b7eea9dd6ee91a486c6996b2d68662366d/tools/dist_test.sh

Seems `dist_test.py` cannot add python arguments directly in the command line. The --fomat-only and --options "jsonfile_prefix=./results_4_" are not passed to program.

**Comment by jbwang1997** [comment]
This part needs to be improved. Thanks for your report.

**Comment by hustCYQ** [comment]
By the way, this problem occurs when I use the computing cluster. The output .pkl file is only partial, and the output .JSON file is all [object, object].My environment configuration is:
mmdet 2.22
mmcv  1.4.6
cuda 11.1
pytorch 1.9.0

There is no problem running on a single GPU personal computer, only in the computing cluster

**Comment by hustCYQ** [comment]
> Could you provide more information, like the config and the sample of the .JSON file.

**Comment by hustCYQ** [comment]
![image](https://user-images.githubusercontent.com/39451786/165889685-018f786b-2be7-4c94-868a-269f4fc3926d.png)
here is .json file

**Comment by BIGWangYuDong** [comment]
A new issue created, and I'll close this one
