### ISSUE TITLE
How to work with Cleanlab

### ISSUE THREAD

**Issue by weypro** [open-mmlab/mmdetection#7847]
https://github.com/cleanlab/cleanlab
What should I do if I want to add Cleanlab to the mmdetection model?

**Comment by jbwang1997** [comment]
I'm very sorry that MMDetection hasn't provided cleanlab support yet. You may need to explore the usage of cleanlab by yourself. It is very appreciated if you can make a pr to incorporate cleanlab in mmdetection.
