### ISSUE TITLE
'ConfigDict' object has no attribute 'device' with swin and sparse rcnn

### ISSUE THREAD

**Issue by asbt96** [open-mmlab/mmdetection#7848]
I'm trying to train sparse rcnn with swin backbone on my own dataset, I already trained for some epochs using this config but now I get this error and I don't understand why . Please help!

### config:
```
_base_ = '/content/mmdetection/configs/sparse_rcnn/sparse_rcnn_r50_fpn_1x_coco.py'

num_stages = 6
pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa
num_proposals = 300

model = dict(
    backbone=dict(
        _delete_=True, # Delete the backbone field in _base_
        type='SwinTransformer',
        embed_dims=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.2,
        patch_norm=True,
        out_indices=(0,1, 2, 3),
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)
        ),
    neck=dict(in_channels=[96,192, 384, 768], start_level=0, num_outs=4),
    roi_head=dict(bbox_head=[
            dict(
                type='DIIHead',
                num_classes=1,
                num_ffn_fcs=2,
                num_heads=8,
                num_cls_fcs=1,
                num_reg_fcs=3,
                feedforward_channels=2048,
                in_channels=256,
                dropout=0.0,
                ffn_act_cfg=dict(type='ReLU', inplace=True),
                dynamic_conv_cfg=dict(
                    type='DynamicConv',
                    in_channels=256,
                    feat_channels=64,
                    out_channels=256,
                    input_feat_shape=7,
                    act_cfg=dict(type='ReLU', inplace=True),
                    norm_cfg=dict(type='LN')),
                loss_bbox=dict(type='L1Loss', loss_weight=5.0),
                loss_iou=dict(type='GIoULoss', loss_weight=2.0),
                loss_cls=dict(
                    type='FocalLoss',
                    use_sigmoid=True,
                    gamma=2.0,
                    alpha=0.25,
                    loss_weight=2.0),
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    clip_border=False,
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.5, 0.5, 1., 1.])) for _ in range(num_stages)
        ]),
    rpn_head=dict(num_proposals=num_proposals),
    test_cfg=dict(_delete_=True, rpn=None, rcnn=dict(max_per_img=num_proposals))
    )

dataset_type = 'COCODataset'

classes = ('mass',)

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RandomFlip', flip_ratio=0.5,direction='horizontal'),
    # augmentation strategy originates from DETR / Sparse RCNN
    dict(type='AutoAugment',
        policies=[[
            dict(
                type='Resize',
                img_scale=[(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                           (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                           (736, 1333), (768, 1333), (800, 1333)],
                multiscale_mode='value',
                keep_ratio=True)
        ],
                  [
                      dict(
                          type='Resize',
                          img_scale=[(400, 1333), (500, 1333), (600, 1333)],
                          multiscale_mode='value',
                          keep_ratio=True),
                      dict(
                          type='RandomCrop',
                          crop_type='absolute_range',
                          crop_size=(384, 600),
                          allow_negative_crop=True),
                      dict(
                          type='Resize',
                          img_scale=[(480, 1333), (512, 1333), (544, 1333),
                                     (576, 1333), (608, 1333), (640, 1333),
                                     (672, 1333), (704, 1333), (736, 1333),
                                     (768, 1333), (800, 1333)],
                          multiscale_mode='value',
                          override=True,
                          keep_ratio=True)
                  ]]),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip',flip_ratio=0.0),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=2,  
    workers_per_gpu=2,  
    train=dict(
        pipeline=train_pipeline,
        img_prefix='/content/drive/MyDrive/OPTIMAM_7626/all_train/',
        classes=classes,
        ann_file='/content/drive/MyDrive/OPTIMAM_7626/Annotations/OPTIMAM_TRAIN.json',
        filter_empty_gt=False),
    val=dict(
        pipeline=test_pipeline,
        img_prefix='/content/drive/MyDrive/OPTIMAM_7626/all_val/',
        classes=classes,
        ann_file='/content/drive/MyDrive/OPTIMAM_7626/Annotations/OPTIMAM_VAL.json',
        filter_empty_gt=False),
    test=dict(
        pipeline=test_pipeline,
        img_prefix='/content/drive/MyDrive/OPTIMAM_7626/all_test/',
        classes=classes,
        ann_file='/content/drive/MyDrive/OPTIMAM_7626/Annotations/OPTIMAM_TEST.json',
        filter_empty_gt=False))

load_from = '/content/drive/MyDrive/OPTIMAM_7626/pretrained_checkpoints/sparse_rcnn_r50_fpn_300_proposals_crop_mstrain_480-800_3x_coco_20201223_024605-9fe92701.pth'

work_dir = '/content/drive/MyDrive/OPTIMAM_7626/to_save_files_and_logs_sparsercnn'

optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.0000125,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'relative_position_bias_table': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))

lr_config = dict(
    policy='step',
    gamma=0.1,
    warmup='linear',
    warmup_iters=8010,
    #warmup_ratio=1.0 / 3,
    step=[27,33])
    
checkpoint_config = dict(interval=5)

log_config = dict(
    interval=267,
    hooks=[
        dict(type='TextLoggerHook')
    ])
runner = dict(type='EpochBasedRunner', max_epochs=36)
evaluation = dict(  
    interval=1,  
    save_best='bbox_mAP',
    iou_thrs=[0.1, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
    )  
```
-------------------------------------------------------------------------------------------
Also in the notebook I add :
cfg.gpu_ids = range(1)
-----------------------------------------------------------------------------------------
**I get the following error:**
**_AttributeError: 'ConfigDict' object has no attribute 'device'_**

My mmdetection version is 2.24.0,  1.11.0+cu113

**Comment by jbwang1997** [comment]
Could provide the full error report on the command line?

**Comment by ct990912** [comment]
``2022-04-28 11:14:26,899 - mmdet - INFO - Set random seed to 269445298, deterministic: False
2022-04-28 11:14:27,263 - mmdet - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'open-mmlab://detectron/resnet50_caffe'}
2022-04-28 11:14:27,264 - mmcv - INFO - load model from: open-mmlab://detectron/resnet50_caffe
2022-04-28 11:14:27,264 - mmcv - INFO - load checkpoint from openmmlab path: open-mmlab://detectron/resnet50_caffe
2022-04-28 11:14:27,365 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias, layer1.0.conv1.bias, layer1.0.conv2.bias, layer1.0.conv3.bias, layer1.0.downsample.0.bias, layer1.1.conv1.bias, layer1.1.conv2.bias, layer1.1.conv3.bias, layer1.2.conv1.bias, layer1.2.conv2.bias, layer1.2.conv3.bias, layer2.0.conv1.bias, layer2.0.conv2.bias, layer2.0.conv3.bias, layer2.0.downsample.0.bias, layer2.1.conv1.bias, layer2.1.conv2.bias, layer2.1.conv3.bias, layer2.2.conv1.bias, layer2.2.conv2.bias, layer2.2.conv3.bias, layer2.3.conv1.bias, layer2.3.conv2.bias, layer2.3.conv3.bias, layer3.0.conv1.bias, layer3.0.conv2.bias, layer3.0.conv3.bias, layer3.0.downsample.0.bias, layer3.1.conv1.bias, layer3.1.conv2.bias, layer3.1.conv3.bias, layer3.2.conv1.bias, layer3.2.conv2.bias, layer3.2.conv3.bias, layer3.3.conv1.bias, layer3.3.conv2.bias, layer3.3.conv3.bias, layer3.4.conv1.bias, layer3.4.conv2.bias, layer3.4.conv3.bias, layer3.5.conv1.bias, layer3.5.conv2.bias, layer3.5.conv3.bias, layer4.0.conv1.bias, layer4.0.conv2.bias, layer4.0.conv3.bias, layer4.0.downsample.0.bias, layer4.1.conv1.bias, layer4.1.conv2.bias, layer4.1.conv3.bias, layer4.2.conv1.bias, layer4.2.conv2.bias, layer4.2.conv3.bias

2022-04-28 11:14:27,383 - mmdet - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2022-04-28 11:14:27,473 - mmdet - INFO - initialize FCOSHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01, 'override': {'type': 'Normal', 'name': 'conv_cls', 'std': 0.01, 'bias_prob': 0.01}}
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 209, in main
    train_detector(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/apis/train.py", line 163, in train_detector
    model = build_dp(model, cfg.device, device_ids=cfg.gpu_ids)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/config.py", line 513, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device

**Comment by ct990912** [comment]
> Could provide the full error report on the command line?

`2022-04-28 11:14:26,899 - mmdet - INFO - Set random seed to 269445298, deterministic: False
2022-04-28 11:14:27,263 - mmdet - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'open-mmlab://detectron/resnet50_caffe'}
2022-04-28 11:14:27,264 - mmcv - INFO - load model from: open-mmlab://detectron/resnet50_caffe
2022-04-28 11:14:27,264 - mmcv - INFO - load checkpoint from openmmlab path: open-mmlab://detectron/resnet50_caffe
2022-04-28 11:14:27,365 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias, layer1.0.conv1.bias, layer1.0.conv2.bias, layer1.0.conv3.bias, layer1.0.downsample.0.bias, layer1.1.conv1.bias, layer1.1.conv2.bias, layer1.1.conv3.bias, layer1.2.conv1.bias, layer1.2.conv2.bias, layer1.2.conv3.bias, layer2.0.conv1.bias, layer2.0.conv2.bias, layer2.0.conv3.bias, layer2.0.downsample.0.bias, layer2.1.conv1.bias, layer2.1.conv2.bias, layer2.1.conv3.bias, layer2.2.conv1.bias, layer2.2.conv2.bias, layer2.2.conv3.bias, layer2.3.conv1.bias, layer2.3.conv2.bias, layer2.3.conv3.bias, layer3.0.conv1.bias, layer3.0.conv2.bias, layer3.0.conv3.bias, layer3.0.downsample.0.bias, layer3.1.conv1.bias, layer3.1.conv2.bias, layer3.1.conv3.bias, layer3.2.conv1.bias, layer3.2.conv2.bias, layer3.2.conv3.bias, layer3.3.conv1.bias, layer3.3.conv2.bias, layer3.3.conv3.bias, layer3.4.conv1.bias, layer3.4.conv2.bias, layer3.4.conv3.bias, layer3.5.conv1.bias, layer3.5.conv2.bias, layer3.5.conv3.bias, layer4.0.conv1.bias, layer4.0.conv2.bias, layer4.0.conv3.bias, layer4.0.downsample.0.bias, layer4.1.conv1.bias, layer4.1.conv2.bias, layer4.1.conv3.bias, layer4.2.conv1.bias, layer4.2.conv2.bias, layer4.2.conv3.bias

2022-04-28 11:14:27,383 - mmdet - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2022-04-28 11:14:27,473 - mmdet - INFO - initialize FCOSHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01, 'override': {'type': 'Normal', 'name': 'conv_cls', 'std': 0.01, 'bias_prob': 0.01}}
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 209, in main
    train_detector(
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/apis/train.py", line 163, in train_detector
    model = build_dp(model, cfg.device, device_ids=cfg.gpu_ids)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/config.py", line 513, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device`

**Comment by asbt96** [comment]
@jbwang1997 , hi this is the error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-5b05e271aef2> in <module>()
     18 # Create work_dir
     19 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
---> 20 train_detector(model, datasets, cfg, distributed=False, validate=True)

2 frames
/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py in __getattr__(self, name)
     47         else:
     48             return value
---> 49         raise ex
     50 
     51 

AttributeError: 'ConfigDict' object has no attribute 'device'

**Comment by jbwang1997** [comment]
Thank you for your error report. I will check this error as soon as possible.

**Comment by jbwang1997** [comment]
Does your train.py script have this line of code? 
https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L196

It is added after 2.24.0. I guess you may update the new version of mmdet but not update the train.py script.

**Comment by asbt96** [comment]
Thank you!!! it was the new version, I fixed it by adding cfg.device='cuda'
