### ISSUE TITLE
How to fix the encode type of data images by using config files? (png and jpg)

### ISSUE THREAD

**Issue by BryantSuen** [open-mmlab/mmdetection#7850]
I'm training detection network using fast-cnn on VOC2012, and my dataset is encoded in png format, and I'm encounting an error as 
```shell
FileNotFoundError: [Errno 2] No such file or directory: 'street_voc/VOC2012/JPEGImages/004296.jpg'
```
I have ```street_voc/VOC2012/JPEGImages/004296.png```, so manually converting the encode format works, but I'm wondering if this problem can be tackled by adding some configurations.

**Comment by jbwang1997** [comment]
For now, the format of the image file is directly coded in `XMLDataset` and cannot be changed by cfg setting.
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/xml_style.py#L51

It's also very appreciated if you can make a pr to enable this feature.

**Comment by BryantSuen** [comment]
Thx and I'll take a deeper look. Closing this Issue
