### ISSUE TITLE
Removing a potentially unnecessary line

### ISSUE THREAD

**Issue by nestiank** [open-mmlab/mmdetection#7851]
**Describe the feature**

Is `while True:` necessary in the line below? How?
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L217

**Motivation**

This may make a tiny increase of performance.

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

(pass)

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

(pass)

**Comment by RangiLyu** [comment]
This line should not be removed. It is used to prevent the transforms in the pipeline from generating invalid data.
