### ISSUE TITLE
How to avoid automatic recovery of test time resize

### ISSUE THREAD

**Issue by nestiank** [open-mmlab/mmdetection#7852]
Hello, I use (512, 512) size images for training and testing, and I want to inference with (256, 256) size images because of the contest rules. However, it seems that adding Resize process into `test_pipeline` like the code below does not work, as inference size persisted as (512, 512).

I think adding Resize process into `test_pipeline` is a kind of TTA, and I know that mmdetection automatically recovers all TTAs just before inference to avoid change of inference size or something like that. However, now I need that change.

Is there any way to permanently change test time image size without actually resizing test images?

Thanks!

```python
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', img_scale=(256, 256)), # Does not work(size auto-recovered)
    dict(
        type='MultiScaleFlipAug',
        img_scale=(256, 256),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True), # Does not work(size auto-recovered)
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

**Comment by RangiLyu** [comment]
Do not add additional resize to the test pipeline. When the img_scale is a single tuple and flip is false in the MultiScaleFlipAug, it will only use a single scale to test. 
And if you set img_scale=(256, 256) in MultiScaleFlipAug, the inference shape should be 256.

**Comment by nestiank** [comment]
If you don't mind, can you review my code? This code prints "512 512" and returns at L9~L10.

```python
def make_predictions(output, cfg, loc: str) -> None:
    prediction_strings = []
    file_names = []

    coco = COCO(os.path.join(cfg.data_root, 'test.json'))

    for i, out in enumerate(output):
        if not (len(out) == 256 and len(out[0]) == 256):
            print(len(out), len(out[0])) # L9
            return # L10

if __name__ == '__main__':
    datasets = [build_dataset(cfg.data.train), build_dataset(cfg.data.test)]
    data_loader = build_dataloader(
        datasets[1],
        samples_per_gpu=1,
        workers_per_gpu=8,
        dist=False,
        shuffle=False
    )
    output = single_gpu_test(model, data_loader)
    make_predictions(output, cfg, f"./inference.csv")
```

**Comment by nestiank** [comment]
Is using `single_gpu_test()` inappropriate?

**Comment by RangiLyu** [comment]
The return type of the function `single_gpu_test` is not a list of images. It's a list of prediction results.

**Comment by nestiank** [comment]
Oops... I used mmsegmentation, and posted this issue here by mistake. I'm sincerely sorry, and reposted this issue there!
https://github.com/open-mmlab/mmsegmentation/issues/1530
