### ISSUE TITLE
How is SAC implemented in MMDetection

### ISSUE THREAD

**Issue by 781458112** [open-mmlab/mmdetection#7855]
It is found in the code that the realization of convolution has been encapsulated. In order to understand the structure of SAC and DCN V2, which part of the code should I refer to?

**Comment by RangiLyu** [comment]
The implementations are in MMCV https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/deform_conv.py https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/saconv.py
