### ISSUE TITLE
SUNRGBD dataset can't be processed correctly using the matlab script.

### ISSUE THREAD

**Issue by B5paper** [open-mmlab/mmdetection#7856]
SUNRGBD dataset can't be processed correctly using the matlab script.

When preparing SUNRGBD dataset, after running `matlab -nosplash -nodesktop -r 'extract_split;quit;'`, there is nothing generated. I download this dataset again and check out the md5 checksum, but the problem still exists.

It seems that three matlab scripts can't deal with this version of SUNRGBD correctly.

**Comment by RangiLyu** [comment]
SUNRGBD is supported in MMDetection3D. Please transfer this issue to https://github.com/open-mmlab/mmdetection3d

**Comment by B5paper** [comment]
Sorry for the confusion between two repos. I start a new issue in mmdet3d. And please delete this issue if necessary.
