### ISSUE TITLE
Wandb Documentation is outdated

### ISSUE THREAD

**Issue by MaxVanDijck** [open-mmlab/mmdetection#7859]
[Wandb Documentation](https://docs.wandb.ai/guides/integrations/mmdetection) for wandb logger hook is outdated. Should be changed to correctly reflect the current MMCV implementation https://github.com/open-mmlab/mmcv/blob/83df7c4b00197b40c3debdb7f388a256640e13b4/mmcv/runner/hooks/logger/wandb.py

**Comment by RangiLyu** [comment]
Thanks for your report! We will update the document asap. And it would be really appreciated if you would like to make a PR to help us fix it.

**Comment by morganmcg1** [comment]
Hi! I work at Weights and Biases and we're in the final stage of adding a dedicated MMDetection logger for wandb, [see this PR](https://github.com/open-mmlab/mmdetection/pull/7459)

Our docs were written in anticipation of this logger getting merged shortly, and we'll give them another review and polish once the PR is merged.

Thanks for your patience and glad that you're getting value out of wandb :)

**Comment by MaxVanDijck** [comment]
Excited for the new logger!!!
