### ISSUE TITLE
How to use the cuda ops that mmcv does not include?

### ISSUE THREAD

**Issue by LiWentomng** [open-mmlab/mmdetection#7866]
I need to complie one cuda operation that the mmcv does not include.   

Like old version, I put the source files in the `mmdet/ops` fold, and complie it successfully.  But when I use it, the error occured like `RuntimeError: CUDA error: invalid device function`.  The codes of this cuda operation is right and can be compiled and used successfully in mmdet1.0.

My mmdetection version is 2.23 and MMCV-full is 1.3.18.   Without using this cuda operation, the code can work well.

How to solve this problem? Thank a lot  in advance!

**Comment by RangiLyu** [comment]
One possible reason is that the cuda version you used to compile is different from the version you used to run the code.

**Comment by LiWentomng** [comment]
@RangiLyu  Thanks a lot！ You are right.   My problem is sloved.
