### ISSUE TITLE
How can I get the val_loss value when training?

### ISSUE THREAD

**Issue by hoya-cho** [open-mmlab/mmdetection#7871]
How can I get the val_loss value when training?

I know that when training in mmcv, the loss value is Validation, and Test returns the mAP value, not the loss value.

When I posted a question before, I was told to get the val_loss value through single_gpu_test() or multi_gpu_test() of eval_hooks.py, but I don't get a sense of it.

Then, I saw the answer in another question, it was a method to train the validation dataloader once more and return the loss value.
Reference link: https://github.com/open-mmlab/mmdetection/issues/7479

However, I haven't been able to find a way to modify the cfg pipeline.

Can you give me an example or method to get val_loss? It's so hard to know how to weave hooks

**Comment by BIGWangYuDong** [comment]
Similar: https://github.com/open-mmlab/mmdetection/issues/5694

You just need to set workflow = [('train', 1),('val', 1)] in the configuration

**Comment by hoya-cho** [comment]
Thanks!,

However, that error occurs.

`TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'`

I think I need to edit the config value of data.val.pipeline,
in epoch_based_runner.py

```
def run_iter(self, data_batch, train_mode, **kwargs):
         if self.batch_processor is not None:
             outputs = self.batch_processor(
                 self.model, data_batch, train_mode=train_mode, **kwargs)
         elif train_mode:
             outputs = self.model.train_step(data_batch, self.optimizer,
                                             **kwargs)
         else:
             outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
```

Is there a way to modify the model's data.val.pipeline before executing val_step() in ?

**Comment by David-Biggs** [comment]
> Thanks!,
> 
> However, that error occurs.
> 
> `TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'`
> 
> I think I need to edit the config value of data.val.pipeline, in epoch_based_runner.py
> 
> ```
> def run_iter(self, data_batch, train_mode, **kwargs):
>          if self.batch_processor is not None:
>              outputs = self.batch_processor(
>                  self.model, data_batch, train_mode=train_mode, **kwargs)
>          elif train_mode:
>              outputs = self.model.train_step(data_batch, self.optimizer,
>                                              **kwargs)
>          else:
>              outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
> ```
> 
> Is there a way to modify the model's data.val.pipeline before executing val_step() inside, other than to modify the pipeline value by externally modifying config.py?

I get the same error...

Has anyone managed to get this right?
