### ISSUE TITLE
.json file can't be generated. 

### ISSUE THREAD

**Issue by hustCYQ** [open-mmlab/mmdetection#7872]
I have posted an issue in #7846 . Now I post the output log.
[swin_ali_36705_stdout.txt](https://github.com/open-mmlab/mmdetection/files/8588462/swin_ali_36705_stdout.txt)

here is .json file generated:
[result.json.bbox.txt](https://github.com/open-mmlab/mmdetection/files/8588502/result.json.bbox.txt)

**Comment by BIGWangYuDong** [comment]
As we can see the code:
https://github.com/open-mmlab/mmdetection/blob/178b9fd422ae906185258a7b4f6453aa270985a7/mmdet/datasets/coco.py#L314-L319

After format, you will get `xxx.bbox.json` which is the format result. if you generate a `txt` file, seems you have change your code. Please check what code you have changed.

**Comment by BIGWangYuDong** [comment]
I have tried to get the format result, and I can successfully get the result

**Comment by hustCYQ** [comment]
> 

I generated a json file. I changed the suffix to txt in order to upload it to GitHub.

**Comment by hustCYQ** [comment]
> What code did you change?

I haven't encountered this problem before, but only in the cluster. I didn't modify the file anywhere. #7846

**Comment by leileilei2000** [comment]
but the new coco.py do not have "bbox.json" code
