### ISSUE TITLE
why doesn't the yolox configs have Normalize？

### ISSUE THREAD

**Issue by plastic0313** [open-mmlab/mmdetection#7873]
i cant't find the Normalize in yolox_s_8x8_300e_coco.py? does yolox need it?

**Comment by VincentZhao1992** [comment]
in the script pytorch2onnx.py, if use img_norm_cfg, can set img_norm_cfg = dict(mean=[0., 0., 0.], std=[1., 1., 1.], to_rgb=True), and add dict(type='Normalize', **img_norm_cfg) in test_pipeline
