### ISSUE TITLE
colab上运行训练自定义数据集的demo，训练时提示配置文件中没有device

### ISSUE THREAD

**Issue by nefusmzj** [open-mmlab/mmdetection#7877]
参考的这个视频：https://www.bilibili.com/video/BV1jy4y1W76V?p=4

参考的这个文件中的“Train A Detector on A Customized Dataset”章节内容和代码：https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb

完全采用记事本中的内容，运行到该步骤时出错如下图

![image](https://user-images.githubusercontent.com/10573790/165942008-d73957b3-d6b0-46de-8640-0b6f681f3919.png)

**Comment by MireniamuYuki** [comment]
参考 #7901 
在tools/train.py 196行处加上一句 `cfg.device='cuda'` 或者mmdet/apis/train.py 163行改成`model = build_dp(model, device_ids=cfg.gpu_ids)`

**Comment by naruto1007** [comment]
adding `cfg.device='cuda'` before the line `train_detector` will work.

I face the sam problem when I run **Train a detector for MOT** in MMTracking_Tutorial in Colab.

above solution works.

`import os.path as osp

from mmtrack.datasets import build_dataset
from mmdet.apis import train_detector as train_model
from mmdet.models import build_detector as build_model

mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
model = build_model(cfg.model.detector)
model.init_weights()
datasets = [build_dataset(cfg.data.train)]
model.CLASSES = datasets[0].CLASSES
cfg.device = 'cuda'
train_model(model, datasets, cfg)`
