### ISSUE TITLE
Modify config through script arguments

### ISSUE THREAD

**Issue by Tamiku** [open-mmlab/mmdetection#7878]
I have read tutorial 1 and learned how to modify config with `--cfg-options` . 
If I want to change multiple keys, should I separated them with comma or space ? Should I type `--cfg-options` twice?
Thank you for your help!

**Comment by PowderYu** [comment]
'override some settings in the used config, the key-value pair '
                        'in xxx=yyy format will be merged into config file. If the value to '
                        'be overwritten is a list, it should be like key="[a,b]" or key=a,b '
                        'It also allows nested list/tuple values, e.g. key="[(a,b),(c,d)]" '
                        'Note that the quotation marks are necessary and that no white space '
                        'is allowed.'

**Comment by batchfly** [comment]
@KostadinovShalon This is realllly helpful. Thank you!

**Comment by maxiuw** [comment]
did not really work for me but if you're using `dist_train.py` this will work 

```
$(dirname "$0")/train.py \
    $CONFIG \
    --cfg-options \
        train_dataloader.batch_size=$BSIZE \ # example of overwriting param vals
        base_batch_size=$BSIZE*$GPUS \ 
```
