### ISSUE TITLE
  How can i use timm's backbone in mmdet?

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmdetection#7880]
i want use backbone such as volo, vovnet, can i use timm's backbone in mmdet.

**Comment by dsp6414** [comment]
is there any plan to support cotNet backbone?

[Contextual Transformer Networks for Visual Recognition](https://arxiv.org/pdf/2107.12292.pdf)

**Comment by chhluo** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/tree/master/configs/timm_example

**Comment by dsp6414** [comment]
or Create CoT pluggin for resnet.

**Comment by chhluo** [comment]
For how to add plugin in backbone please refer to https://github.com/open-mmlab/mmdetection/issues/7419.

**Comment by dsp6414** [comment]
thx for your suggestion , i have read the doc.
