### ISSUE TITLE
Weight problem [64, 3, 7, 7] [1, 2, 3, 320, 416]

### ISSUE THREAD

**Issue by liang-k-b** [open-mmlab/mmdetection#7881]
When I run tools/train.py:
  python tools/train.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py --gpus 1 --work-dir aj_test

It reported:
  RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 5-dimensional input of size [1, 2, 3, 320, 416] instead

No matter what algorithm training, it will report this error. 
How to solve this problem？

**Comment by chhluo** [comment]
I think your modification to code or config file incured this error.

**Comment by liang-k-b** [comment]
I only modified the category information of coco dataset, and did not modify other files.
Can I use this command when I train on the CPU?

**Comment by chhluo** [comment]
I ran `CUDA_VISIBL_DEVICES="" python tools/train.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py` with cpu, and met the same problem as you.

Training on CPU is not sopported yet. But inference on cpu is supported.

Even with support for training models on cpu, training on cpu is not realistic unless you have a lot of cpus.

**Comment by chhluo** [comment]
Sorry, training on cpu is supported now except some ops depended on cuda. please refer to https://github.com/open-mmlab/mmdetection/blob/95747b18fc684491a7921deac1c619679ac6d3fb/docs/en/get_started.md.
