### ISSUE TITLE
Unexpected behaviour when I have multiple `custom_imports` in different config files.

### ISSUE THREAD

**Issue by YiqunChen1999** [open-mmlab/mmdetection#7883]
Hi, there, 
I recently find that `custom_imorts` in multiple config files may not work as expected: If I write `custom_imports` in multiple files (i.e., import module in the model config and import dataset in the dataset config), only one of them works. Is it a feature or a bug? Will `mmcv` fixes it?

Fortunately, I find that most (maybe all) config files inherit `default_runtime.py`. I then put all my modules there and they are all imported as expected. But documentation about `custom_imports` is too simple to find something more helpful. 

If you treat the `custom_imports` as a feature, you may need to consider updating the documentation about `custom_imports`.

**Comment by chhluo** [comment]
It's a feature. You should write `custom_imports` in  only one config file instead of multi config files, otherwise `custom_imports` will be overwritten.
