### ISSUE TITLE
CUDA out of memory swin and deformable detr

### ISSUE THREAD

**Issue by asbt96** [open-mmlab/mmdetection#7885]
Hi! I'm trying to train deformable detr with swin-tiny backbone, but I get the error : 

- **RuntimeError: CUDA out of memory. Tried to allocate 84.00 MiB (GPU 0; 14.76 GiB total capacity; 12.12 GiB already allocated; 83.75 MiB free; 13.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF** 

I've tried reducing the batch size, and using FP16 (But I think is not implemented?) and don't know if there's a way to get to train this model. 
Could I try something else or correct something?, this is my config:
----------------------------------------------------------------------------------------------------------------------

_base_ = [
    '../_base_/datasets/coco_detection.py', '../_base_/default_runtime.py'
]

#fp16 = dict(loss_scale=dict(init_scale=512))

pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa

model = dict(
    type='DeformableDETR',
     backbone=dict(
     type='SwinTransformer',
     embed_dims=96,
     depths=[2, 2, 6, 2],
     num_heads=[3, 6, 12, 24],
     window_size=7,
     mlp_ratio=4,
     qkv_bias=True,
     qk_scale=None,
     drop_rate=0.,
     attn_drop_rate=0.,
     drop_path_rate=0.2,
     patch_norm=True,
     out_indices=(0,1,2,3),
     with_cp=False,
     convert_weights=True,
     init_cfg=dict(type='Pretrained', checkpoint=pretrained)
     ),
 
    neck=dict(
        type='ChannelMapper',
        in_channels=[96, 192, 384, 768],
        kernel_size=1,
        out_channels=256,
        act_cfg=None,
        norm_cfg=dict(type='GN', num_groups=32),
        num_outs=4),
    bbox_head=dict(
        type='DeformableDETRHead',
        num_query=300,
        num_classes=1,
        in_channels=2048,
        sync_cls_avg_factor=True,
        as_two_stage=False,
        transformer=dict(
            type='DeformableDetrTransformer',
            encoder=dict(
                type='DetrTransformerEncoder',
                num_layers=6,
                transformerlayers=dict(
                    type='BaseTransformerLayer',
                    attn_cfgs=dict(
                        type='MultiScaleDeformableAttention', embed_dims=256),
                    feedforward_channels=1024,
                    ffn_dropout=0.1,
                    operation_order=('self_attn', 'norm', 'ffn', 'norm'))),
            decoder=dict(
                type='DeformableDetrTransformerDecoder',
                num_layers=6,
                return_intermediate=True,
                transformerlayers=dict(
                    type='DetrTransformerDecoderLayer',
                    attn_cfgs=[
                        dict(
                            type='MultiheadAttention',
                            embed_dims=256,
                            num_heads=8,
                            dropout=0.1),
                        dict(
                            type='MultiScaleDeformableAttention',
                            embed_dims=256)
                    ],
                    feedforward_channels=1024,
                    ffn_dropout=0.1,
                    operation_order=('self_attn', 'norm', 'cross_attn', 'norm',
                                     'ffn', 'norm')))),
        positional_encoding=dict(
            type='SinePositionalEncoding',
            num_feats=128,
            normalize=True,
            offset=-0.5),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=2.0),
        loss_bbox=dict(type='L1Loss', loss_weight=5.0),
        loss_iou=dict(type='GIoULoss', loss_weight=2.0)),
    # training and testing settings
    train_cfg=dict(
        assigner=dict(
            type='HungarianAssigner',
            cls_cost=dict(type='FocalLossCost', weight=2.0),
            reg_cost=dict(type='BBoxL1Cost', weight=5.0, box_format='xywh'),
            iou_cost=dict(type='IoUCost', iou_mode='giou', weight=2.0))),
    test_cfg=dict(max_per_img=100))
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RandomFlip', flip_ratio=0.5,direction='horizontal'),
    dict(
        type='AutoAugment',
        policies=[
            [
                dict(
                    type='Resize',
                    img_scale=[(480, 1333), (512, 1333), (544, 1333),
                               (576, 1333), (608, 1333), (640, 1333),
                               (672, 1333), (704, 1333), (736, 1333),
                               (768, 1333), (800, 1333)],
                    multiscale_mode='value',
                    keep_ratio=True)
            ],
            [
                dict(
                    type='Resize',
                    # The radio of all image in train dataset < 7
                    # follow the original impl
                    img_scale=[(400, 4200), (500, 4200), (600, 4200)],
                    multiscale_mode='value',
                    keep_ratio=True),
                dict(
                    type='RandomCrop',
                    crop_type='absolute_range',
                    crop_size=(384, 600),
                    allow_negative_crop=True),
                dict(
                    type='Resize',
                    img_scale=[(480, 1333), (512, 1333), (544, 1333),
                               (576, 1333), (608, 1333), (640, 1333),
                               (672, 1333), (704, 1333), (736, 1333),
                               (768, 1333), (800, 1333)],
                    multiscale_mode='value',
                    override=True,
                    keep_ratio=True)
            ]
        ]),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=1),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip',flip_ratio=0.0),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=1),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
dataset_type = 'COCODataset'
classes = ('mass',)
data = dict(
    samples_per_gpu=2,  # Batch size of a single GPU
    workers_per_gpu=2,  # Worker to pre-fetch data for each single GPU
    train=dict(
        pipeline=train_pipeline,
        img_prefix='/content/drive/MyDrive/OPTIMAM_7626/all_train/',
        classes=classes,
        ann_file='/content/drive/MyDrive/OPTIMAM_7626/Annotations/OPTIMAM_TRAIN.json',
        filter_empty_gt=True),
    val=dict(
        pipeline=test_pipeline,
        img_prefix='/content/drive/MyDrive/OPTIMAM_7626/all_val/',
        classes=classes,
        ann_file='/content/drive/MyDrive/OPTIMAM_7626/Annotations/OPTIMAM_VAL.json',
        filter_empty_gt=False),
    test=dict(
        pipeline=test_pipeline,
        img_prefix='/content/drive/MyDrive/OPTIMAM_7626/all_test/',
        classes=classes,
        ann_file='/content/drive/MyDrive/OPTIMAM_7626/Annotations/OPTIMAM_TEST.json',
        filter_empty_gt=False))
load_from ='https://download.openmmlab.com/mmdetection/v2.0/deformable_detr/deformable_detr_r50_16x2_50e_coco/deformable_detr_r50_16x2_50e_coco_20210419_220030-a12b9512.pth'
work_dir = '/content/drive/MyDrive/OPTIMAM_7626/to_save_files_and_logs_deformable_detr_swin'
optimizer = dict(
    type='AdamW',
    lr=2e-4/16,
    weight_decay=0.0001,
    paramwise_cfg=dict(
        custom_keys={
            'backbone': dict(lr_mult=0.1),
            'sampling_offsets': dict(lr_mult=0.1),
            'reference_points': dict(lr_mult=0.1)
        }))

optimizer_config = dict(grad_clip=dict(max_norm=0.2, norm_type=2))

lr_config = dict(
    policy='step',
    gamma=0.1,
    warmup='linear',
    warmup_iters=8010,
    #warmup_ratio=1.0 / 3,
    step=[40])
runner = dict(type='EpochBasedRunner', max_epochs=50)
checkpoint_config = dict(interval=5)
log_config = dict(
    interval=267,
    hooks=[
        dict(type='TextLoggerHook')
    ])
evaluation = dict( 
    interval=1,  # Evaluation interval
    save_best='bbox_mAP',
    iou_thrs=[0.1, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
    )  
auto_scale_lr = dict(base_batch_size=32)

- 1.11.0+cu113 True
MMDET version 2.24.1

**Comment by chhluo** [comment]
```python
dict(
type='Resize',
# The radio of all image in train dataset < 7
# follow the original impl
img_scale=[(400, 4200), (500, 4200), (600, 4200)],
multiscale_mode='value',
keep_ratio=True),
```
The  img_scale is too big. I think you should decrease img_scale or image_size in the pipeline.

**Comment by asbt96** [comment]
Thank you!! I decreased img_scale and image_size and it was able to train
