### ISSUE TITLE
How to add the evaluation index of map_s，map_m,map_l to voc dataset?

### ISSUE THREAD

**Issue by duange22** [open-mmlab/mmdetection#7893]
How to add the evaluation index of map_s，map_m,map_l to voc dataset?

**Comment by Czm369** [comment]
Maybe you can refer to
https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L509
