### ISSUE TITLE
Cann't get json results

### ISSUE THREAD

**Issue by learner-NKH** [open-mmlab/mmdetection#7894]
I want to convert a pkl file to json file by using tools.eval_metric, which should work by set '--format-only', but i don't get any outputs

**Comment by billfjj** [comment]
This happened to me too, I ran --format-only --options "jsonfile_prefix=. /maskresult" code, but it doesn't generate a json file

**Comment by learner-NKH** [comment]
> I changed args.eval_options = {'jsonfile_prefix' : '/content/'} to args.eval_options = {'jsonfile_prefix' : './results'} and it worked

**Comment by billfjj** [comment]
> 

Where is args.eval_options = {'jsonfile_prefix' : '/content/'}, please?

**Comment by Czm369** [comment]
More details are in https://github.com/open-mmlab/mmdetection/pull/2114

**Comment by Czm369** [comment]
The function is implemented in
https://github.com/open-mmlab/mmdetection/blob/73b4e65a6a30435ef6a35f405e3474a4d9cfb234/tools/test.py#L252

**Comment by billfjj** [comment]
> 

Thank you, I solved the problem
