### ISSUE TITLE
conn't use dist_test.sh

### ISSUE THREAD

**Issue by billfjj** [open-mmlab/mmdetection#7895]
I get SyntaxError: invalid syntax when I use the dist_test.sh command:
(swin_det) amax@admin:~/LJW/swin_transformer/Swin-Transformer-Object-Detection$ python ./tools/dist_test.sh configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py ./work_dirs/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco/latest.pth 2 --format-only --options “jsonfile_prefix=./results”
  File "./tools/dist_test.sh", line 3
    CONFIG=$1
           ^
SyntaxError: invalid syntax

**Comment by PowderYu** [comment]
you should use bash instead of python to run .sh file

**Comment by Czm369** [comment]
Maybe you can refer to 
https://github.com/open-mmlab/mmdetection/blob/master/.dev_scripts/test_benchmark.sh
