### ISSUE TITLE
如何利用dota数据集的测试集？

### ISSUE THREAD

**Issue by LowPassFilter-phil** [open-mmlab/mmdetection#7899]
博主，您好，DOTA数据集中的测试集里面只有图片，没有标注文件.txt，这样的test能用于mmdetection的test.py测试吗？我看见论文里面好多都有dota数据集测试的结果，他们用的是测试集吗？还是验证集？为什么dota数据集的测试集没有标注文件官网还提供了生成测试集的json文件？生产的测试集的json文件真的有用吗？

**Comment by hhaAndroid** [comment]
@LowPassFilter-phil Please use mmrotate
