### ISSUE TITLE
Choosing a different backbone network

### ISSUE THREAD

**Issue by adityaarun1** [open-mmlab/mmdetection#79]
Hi,

How can one change the backbone network, let's say for example VGG or ResNext etc? 

I see a closed issue marked for v0.6 release [here](https://github.com/open-mmlab/mmdetection/issues/3), and I can also see that `mmcv.cnn` already seem to have VGG. If this is a planned feature, when can we expect it to roll out?

**Comment by adityaarun1** [comment]
Hi @hellock, sorry to bug you again, do you have a fresh timeline for this feature?

**Comment by hellock** [comment]
We plan to add VGG for SSD only. For other models (Faster R-CNN, etc.), ResNet runs faster and performs better so we do not think it is necessary, but community contributions are welcome.
ResNeXt is expected to be released in one or two weeks.
