### ISSUE TITLE
'ConfigDict' object has no attribute 'device'

### ISSUE THREAD

**Issue by David-Biggs** [open-mmlab/mmdetection#7901]
I was recently able to successfully fine-tune mask r-cnn and mask scoring r-cnn on my costume dataset.  Training and inference both worked fine. However, three weeks down the line and suddenly I am getting an error: 
" 'ConfigDict' object has no attribute 'device' "

Here is a screen shot of the error printout:

![error](https://user-images.githubusercontent.com/64862726/166439978-98fac00e-12db-4d2d-b401-09df2d1df6a5.png)

Thanks in advance.

**Comment by sparshgarg23** [comment]
faced the same issue while training fasterrcnn on MOT 20,
adding  cfg.device='cuda' to https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L196  fixed it for me

**Comment by MireniamuYuki** [comment]
> faced the same issue while training fasterrcnn on MOT 20, adding cfg.device='cuda' to https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L196 fixed it for me

I got the same error again, It's not work for me
Is there any better solution?

**Comment by sparshgarg23** [comment]
@MireniamuYuki  i just followed the advice given in #7848 ,if this isn't working can you try changing your MMDetection to an older version like 2.23.
Also,would be nice if someone from MMdetection team could shed some light on this @shinya7y  any suggestions on how to resolve this.

**Comment by MireniamuYuki** [comment]
Thank you for your advice!
I tried the solution of #7841 and fixed it. Worked for me in MMDetection 2.24
In mmdet/apis/train.py:163 change it to:
`model = build_dp(model, device_ids=cfg.gpu_ids) `

**Comment by David-Biggs** [comment]
> faced the same issue while training fasterrcnn on MOT 20, adding cfg.device='cuda' to https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L196 fixed it for me

Thanks. This worked for me.

**Comment by mzohaibshafiq** [comment]
I just added this line as suggested by #

> faced the same issue while training fasterrcnn on MOT 20, adding cfg.device='cuda' to https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L196 fixed it for me

This solution worked for me by adding the cfg.device='cuda' just before these lines:

mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)

**Comment by Sdhir** [comment]
Add this to your cfg definition:
```
def is_mlu_available():
    """Returns a bool indicating if MLU is currently available."""
    return hasattr(torch, 'is_mlu_available') and torch.is_mlu_available()


def get_device():
    """Returns an available device, cpu, cuda or mlu."""
    is_device_available = {
        'cuda': torch.cuda.is_available(),
        'mlu': is_mlu_available()
    }
    device_list = [k for k, v in is_device_available.items() if v]
    return device_list[0] if len(device_list) == 1 else 'cpu'
cfg.device = get_device()
```
