### ISSUE TITLE
Why can I only generate a json file once?

### ISSUE THREAD

**Issue by billfjj** [open-mmlab/mmdetection#7902]
When I first used --eval-options {'jsonfile_prefix': '. /results'} it successfully generated the json file, but when I used the command again later it didn't seem to update the file anymore, I changed the jsonfile_prefix parameter like this {'jsonfile_prefix': '. /maskresults'}, but it doesn't generate a new json file anymore either.This problem has been bothering me for a long time

**Comment by hhaAndroid** [comment]
@billfjj It seems unlikely. I tried it and found it to be correct. can you provide some more log information?

**Comment by billfjj** [comment]
> @billfjj It seems unlikely. I tried it and found it to be correct. can you provide some more log information?

I tried this code python . /tools/test.py configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py . /work_dirs/epoch_2.pth --format-only --options "jsonfile_prefix=. /results", which successfully generated once on my Windows 10 computer, but did not generate any files on the Linux server, and then I changed "jsonfile_prefix=. /results" command several times, such as "jsonfile_prefix=. /maskresults", and no new files were generated on my computer or on the server. Then I directly modified the default parameter parser.add_argument('--eval-options', default={'jsonfile_prefix': '. /results'}, nargs='+', action=DictAction), which then successfully solved the problem.

**Comment by hhaAndroid** [comment]
@billfjj  So, have you found the reason?

**Comment by billfjj** [comment]
> @billfjj So, have you found the reason?

I didn't find out why this happened, I just debugged the code step by step and then changed the command line parameters and it worked

**Comment by hhaAndroid** [comment]
> > @billfjj So, have you found the reason?
> 
> I didn't find out why this happened, I just debugged the code step by step and then changed the command line parameters and it worked

OK
