### ISSUE TITLE
cannot pickle temp module on custom dataset

### ISSUE THREAD

**Issue by tempbrucefu** [open-mmlab/mmdetection#7903]
using custom dataset 

@DATASETS.register_module()
class ANewDataset(CustomDataset):
    CLASSES = ("one", "two", "yjtrr")

    def load_annotations(self, ann_file):
             # handling files

when I use it for training,

cfg = get_cfg()
datasets = [build_dataset(cfg.data.train)]
model = build_detector(
    cfg.model, train_cfg=cfg.get('train_cfg'), test_cfg=cfg.get('test_cfg'))
model.CLASSES = datasets[0].CLASSES
mmcv.mkdir_or_exist(os.path.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)

looks like the custom dataset files is converted to a temp file. but during train_detector, 
an error was reported:

Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'tmpbmscwqvw.ANewDataset'>: import of module 'tmpbmscwqvw' failed

**Comment by jbwang1997** [comment]
Could you provide more information, like the custom dataset code?

**Comment by tempbrucefu** [comment]
custom data code is above, 

@DATASETS.register_module()
class ANewDataset(CustomDataset):
     CLASSES = ("one", "two", "yjtrr")
     def load_annotations(self, ann_file):
         # handling files


for datasets = [build_dataset(cfg.data.train)]

it is okay to get the custom data and the calling load_annotations, but the break point in this function is not working
since from custom, 
calling self.data_infos = self.load_annotations(local_path)
it went to a temp py file, like 


    BUILD_MAP, LOAD_FAST(.0), FOR_ITER(to 20),  xxxxx
    xxx

========

for loading data, the temp file is still working, but for 
dump (reduction.py), ForkingPickler(file, protocol).dump(obj) cannot find the temp file.

**Comment by hhaAndroid** [comment]
@tempbrucefu Sorry, can you fill it out according to the issue template?

**Comment by jbwang1997** [comment]
This issue will be closed due to inactivity. Feel free to reopen this pr if you have any questions.
