### ISSUE TITLE
how to close mosaic in yolox

### ISSUE THREAD

**Issue by Pengyisheng** [open-mmlab/mmdetection#7909]
how to close mosaic in yolox

**Comment by RangiLyu** [comment]
Just modify the data pipeline:
```python
train_pipeline = [
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(0,0)),
    dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    # According to the official implementation, multi-scale
    # training is not considered here but in the
    # 'mmdet/models/detectors/yolox.py'.
    dict(type='Resize', img_scale=img_scale, keep_ratio=True),
    dict(
        type='Pad',
        pad_to_square=True,
        # If the image is three-channel, the pad value needs
        # to be set separately for each channel.
        pad_val=dict(img=(114.0, 114.0, 114.0))),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
```

**Comment by Pengyisheng** [comment]
> Just modify the data pipeline:
> 
> ```python
> train_pipeline = [
>     dict(
>         type='RandomAffine',
>         scaling_ratio_range=(0.1, 2),
>         border=(0,0)),
>     dict(
>         type='MixUp',
>         img_scale=img_scale,
>         ratio_range=(0.8, 1.6),
>         pad_val=114.0),
>     dict(type='YOLOXHSVRandomAug'),
>     dict(type='RandomFlip', flip_ratio=0.5),
>     # According to the official implementation, multi-scale
>     # training is not considered here but in the
>     # 'mmdet/models/detectors/yolox.py'.
>     dict(type='Resize', img_scale=img_scale, keep_ratio=True),
>     dict(
>         type='Pad',
>         pad_to_square=True,
>         # If the image is three-channel, the pad value needs
>         # to be set separately for each channel.
>         pad_val=dict(img=(114.0, 114.0, 114.0))),
>     dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
>     dict(type='DefaultFormatBundle'),
>     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
> ]
> ```
Thank you,I will change it ,but my  version is 2.18,1 ,Will this be a problem when I modify?can I only delete that line ?
