### ISSUE TITLE
pth to ONNX for YoloX models.

### ISSUE THREAD

**Issue by Pari-singh** [open-mmlab/mmdetection#7914]
**Describe the feature**
YoloX pipeline doesn't support ONNX conversion as the Yolox_head doesn't have YoloBBoxCoder which is expected in pytorch2onnx.py. Due to two separate heads in YoloX as opposed to single head output from Yolov3, we could not set Bbox_coder expected in file base_dense_head of mmdet (called from pytorch2onnx.py)

**Comment by RangiLyu** [comment]
pytorch2onnx.py is deprecated. Please use MMDeploy instead. And it already supports YOLOX. https://github.com/open-mmlab/mmdeploy
