### ISSUE TITLE
segmentation result

### ISSUE THREAD

**Issue by lcy0604** [open-mmlab/mmdetection#792]
Excuse me, when I test on my own dataset with mask rcnn, I get the format like 
{'image_id': 1, 
'bbox': [934.6126098632812, 252.9176483154297, 21.733642578125, 26.555191040039062], 'score': 0.8924519419670105, 
'category_id': 1, 
'segmentation': {'size': [720, 1280], 'counts':'n[bd0f0je01O1O00000000000000000000000001O0000d0ZO_aS7'}}

How can I transfer the segmentation to some coordinates of keypointss like maskrcnn-benchmark?

**Comment by lcy0604** [comment]
Sorry to bother you! I have solved it.

**Comment by luoyaqiao** [comment]
How do you decode the counts to binary mask? Thanks!

**Comment by tommyjiang** [comment]
@luoyaqiao  You can refer to [COCO API](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py#L87) for decoding the mask.

**Comment by jerpint** [comment]
For anyone looking for the specific part of the API that handles the decoding, here's a sample:

```
