### ISSUE TITLE
Modify config to None reports error

### ISSUE THREAD

**Issue by Tamiku** [open-mmlab/mmdetection#7923]
I want to change 'lr_config' and 'resume_from' to None by using  command `--cfg-options lr_config=None resume_from=None`,but it didn't work.I want to know how to write the command to make it work?Thank you!

**Comment by chhluo** [comment]
https://github.com/open-mmlab/mmdetection/blob/73b4e65a6a30435ef6a35f405e3474a4d9cfb234/configs/_base_/default_runtime.py#L15 `resume_from` is None by default. `lr_config` shouldn't be None, because training need a learning policy
