### ISSUE TITLE
How to use maskformer only for instance segmentation without semantic segmentation？

### ISSUE THREAD

**Issue by EstherJinyan** [open-mmlab/mmdetection#7925]
Hello, I see that you have implemented **maskformer** in mmdetection, but there are **num_stuff_classes** in it. I guess it should be used for instance segmentation and semantic segmentation at the same time. How can i modify the config implementation to only do instance segmentation?Thanks.

**Comment by Levine66** [comment]
Hey, I wonder if you have solved this problem? Can you share your config to me?
