### ISSUE TITLE
How to add other evaluations to tensorboard like mIOU

### ISSUE THREAD

**Issue by Ulricman** [open-mmlab/mmdetection#7926]

**Comment by chhluo** [comment]
Current supported matrics are bbox AP, mask AP, and PQ. mIoU is supported in mmdetection. The metrics will be add to tensorbord automatically when you add tensorboard in config file. https://github.com/open-mmlab/mmdetection/blob/73b4e65a6a30435ef6a35f405e3474a4d9cfb234/configs/_base_/default_runtime.py#L7

**Comment by Ulricman** [comment]
But when I train faster r-cnn, only acc and five losses are showed. And if I want the abscissa of the X axis to be epoch, what should I do?

**Comment by chhluo** [comment]
The metrics will be displayed in val part after the first evaluation. 

> And if I want the abscissa of the X axis to be epoch, what should I do?

This is not supported yet.

**Comment by Ulricman** [comment]
Thanks!
