### ISSUE TITLE
mmdetection 2.22 vs 2.24 GPU memory usage [mixed precision training, 16fp]

### ISSUE THREAD

**Issue by lolongcovas** [open-mmlab/mmdetection#7928]
I found higher GPU memory usage for mmdetection 2.24 vs 2.22. I could manage to train batch size of 14 samples per gpu and now 10 samples per gpu. I attach the differences [left 2.22 right 2.24]:

![image](https://user-images.githubusercontent.com/3662732/167247308-efd1e9d2-87ac-44fb-a7ec-e5e9c12c4878.png)
![image](https://user-images.githubusercontent.com/3662732/167247317-ca3a333f-3a36-4f8f-b433-fdb04cbd63af.png)
![image](https://user-images.githubusercontent.com/3662732/167247335-ec7abc00-dfd1-4ef1-aad4-7895efcc7fcf.png)

I am not sure if I set correctly the mixed precision training, I guess yes.

**Comment by chhluo** [comment]
If you turn on the fp16, it will be show in logs. The left fp16 was on, the right was not.

![image](https://user-images.githubusercontent.com/26483343/167249873-ad5736ad-4daa-4201-9208-fc1bb014aadd.png)

**Comment by lolongcovas** [comment]
Hi @chhluo, thanks for the response. I rechecked the loss_scale flag again, the cmd parameter is fp16.loss_scale instead of loss_scale. Now it worked.

**Comment by austinmw** [comment]
Hi, is this still true in v3.0?
