### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Tianhao-Qi** [open-mmlab/mmdetection#7933]
use cascade mask rcnn and add num_convs=2 to rpn_head, however, I get the following errors:
![image](https://user-images.githubusercontent.com/37017794/167287711-22fc8008-e3e9-41fe-bd00-d6beec0ffd54.png)

**Environment**
![image](https://user-images.githubusercontent.com/37017794/167287747-e7164ff9-a541-460c-b7d0-fabe2fdd0b99.png)

**Comment by ZwwWayne** [comment]
Could you provide a config so that we can reproduce the error?

**Comment by mitming** [comment]
> Could you provide a config so that we can reproduce the error?

Hi, @ZwwWayne 

I have same issue too, it fix by change [this line](https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/models/roi_heads/mask_heads/fused_semantic_head.py#L104) to:
```
x = x + self.lateral_convs[i](feat)
```

**Comment by Tianhao-Qi** [comment]
> Could you provide a config so that we can reproduce the error?

The config file I used is configs/simple_copy_paste/mask_rcnn_r50_fpn_syncbn-all_rpn-2conv_ssj_scp_32x2_270k_coco.py.

**Comment by shinya7y** [comment]
In my environment, the following fix resolves the error.
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/rpn_head.py#L65
```python
x = F.relu(x, inplace=False)
```

- `faster_rcnn_r50_fpn_1x_coco.py`: no error
- `faster_rcnn_r50_fpn_1x_coco.py`, `--cfg-options "model.rpn_head.num_convs=2"`: error
- `faster_rcnn_r50_fpn_1x_coco.py`, `--cfg-options "model.rpn_head.num_convs=2"`, `x = F.relu(x, inplace=False)`: no error

**Comment by AT1981** [comment]
Solov2 returns the same problem for me. Has anyone fixed that yet?

**Comment by mzillag** [comment]
> Solov2 head returns the same problem for me. Has anyone fixed that yet?

Yeap, [here](https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/solov2_head.py#:~:text=%2B%3D%20self.-,convs_all_levels,-%5Bi%5D( ) change to `feature_add_all_level = feature_add_all_level + self.convs_all_levels[i](input_p)`
