### ISSUE TITLE
yolox加载模型错误

### ISSUE THREAD

**Issue by star379814385** [open-mmlab/mmdetection#7936]
训练yolox_tiny保存模型后，使用该模型进行infer，报错unexpected key in source state_dict。yolox_tiny模型有462个权重，但保存checkpoint为924个权重。”backbone.stem.conv.conv.weight“会增加一个诸如”ema_backbone_stem_conv_conv_weight“的unexpected key。
使用mmdet版本为2.24.0.

**Comment by hhaAndroid** [comment]
@star379814385 which is reasonable since it used ema

**Comment by QiyuLuo** [comment]
> @star379814385 which is reasonable since it used ema
那应该怎么加载yolox的模型呢？能给个命令demo吗

**Comment by Bruce-Si** [comment]
同问，该怎么加载yolox模型呢...

**Comment by Errol-golang** [comment]
请问你现在解决这个问题了吗...

**Comment by Errol-golang** [comment]
> 同问，该怎么加载yolox模型呢...

请问你现在解决这个问题了吗...

**Comment by Bruce-Si** [comment]
> > 同问，该怎么加载yolox模型呢...
> 
> 请问你现在解决这个问题了吗...

好像不用管多的ema权重，直接加载就行。
