### ISSUE TITLE
what is the exact meaning of "level" and "prob" in transforms?

### ISSUE THREAD

**Issue by leesangjoon1** [open-mmlab/mmdetection#7941]
I have a questions about title.

In transforms, there are "level" and "prob".

but it is just said "shoud be in range [0,max_level], probability for performing color transformation.

So I don't know what is means exactly. please help me :)

**Comment by Czm369** [comment]
Additionally, each operation is also associated with two hyperparameters: 1) the probability of applying the operation, and
2) the magnitude of the operation.
Referring to https://arxiv.org/pdf/1805.09501.pdf
