### ISSUE TITLE
solo model output result is empty

### ISSUE THREAD

**Issue by Evoluange** [open-mmlab/mmdetection#7946]
Hello~
我在训练solo模型后测试效果，返回结果为空。
利用`python tools/train.py configs/solo/solo_r50_fpn_1x_coco.py`训练模型，其中训练数据为coco-val集
走完12轮测试效果，测试脚本demo.py代码如下：
`from argparse import ArgumentParser
import cv2

from mmdet.apis import (async_inference_detector, inference_detector,
                        init_detector)

def parse_args():
    parser = ArgumentParser()
    parser.add_argument('img', help='Image file')
    parser.add_argument('out', help='Image file')
    parser.add_argument('config', help='Config file')
    parser.add_argument('checkpoint', help='Checkpoint file')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument(
        '--score-thr', type=float, default=0.65, help='bbox score threshold')
    args = parser.parse_args()
    return args

def show_result_pyplot_own(model,
                       img,
                       result,
                       out_file, 
                       score_thr):
    if hasattr(model, 'module'):
        model = model.module
    res_img = model.show_result(
        img,
        result,
        score_thr=score_thr,
        show=False
        )
    cv2.imwrite(out_file, res_img)
    
def main(args):
    # build the model from a config file and a checkpoint file
    model = init_detector(args.config, args.checkpoint, device=args.device)
    # test a single image
    result = inference_detector(model, args.img)
    # show the results
    # print("res:",result)
    show_result_pyplot_own(model, args.img, result, args.out, score_thr=args.score_thr)

if __name__ == '__main__':
    args = parse_args()
    main(args)
`
执行
`python demo.py 000000007173.jpg 000000007173-res.jpg configs/solo/solo_r50_fpn_1x_coco.py work_dirs/solo_r50_fpn_1x_coco/epoch_11.pth`
得到的图片效果为空，和原图一样，如下所示：
![2345截图20220509183901](https://user-images.githubusercontent.com/25747262/167393972-62350959-3de7-459d-9759-09fe9d955a20.png)
训练日志如下：
[20220509_115210.log](https://github.com/open-mmlab/mmdetection/files/8651000/20220509_115210.log)
请问是什么原因呢？是因为训练数据量比较小导致没有收敛，迭代次数不够或者是学习率参数设置的问题？

**Comment by Czm369** [comment]
Looks like the losses haven't come down yet,  maybe you can increase the batch size.

**Comment by Evoluange** [comment]
好的，感觉是loss没有降下来的问题。我先把samples_per_gpu改成4试试，原来默认为2。

**Comment by Evoluange** [comment]
Hello~,我用solov2训练，训练数据为coco-val，gpu数目为1
[issue7441](https://github.com/open-mmlab/mmdetection/pull/7441)
> https://github.com/zhanggefan/mmdetection-1/tree/solov2
把samples_per_gpu从2改成4，batch size增大，运行
` python tools/train.py configs/solov2/solov2_r50_fpn_3x_coco.py`
进行训练，用demo.py测试结果，发现结果异常，满屏都被标识为人
`python demo.py 30208.jpg 30208-res.jpg configs/solov2/solov2_r50_fpn_3x_coco.py work_dirs/solov2_r50_fpn_3x_coco/epoch_36.pth`
如下图所示：
![2345截图20220510100525](https://user-images.githubusercontent.com/25747262/167528040-aae262a2-53fc-4948-9f96-cc38aaad31ca.png)
![2345截图20220510100807](https://user-images.githubusercontent.com/25747262/167528154-5c07eb05-4eb3-4bea-a840-f0f8311d464a.png)
或者结果为空，如下图：
![2345截图20220510100902](https://user-images.githubusercontent.com/25747262/167528250-d95b43f6-7543-423e-9181-224dc6302571.png)
训练日志如下：
[20220509_201330.log](https://github.com/open-mmlab/mmdetection/files/8656540/20220509_201330.log)
这是什么原因呢？

**Comment by BIGWangYuDong** [comment]
Your loss losses haven't come down. Dice Loss have this issue, you need to check whether your loss come down at the begining

**Comment by Evoluange** [comment]
OK ,I get it. Thank you !
