### ISSUE TITLE
mmdet_handler.py  and fuse_conv_bn

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmdetection#7949]
It seems that the `mmdet_handler.py` script used with TorchServe export does not include the use of `mmcv.cnn.fuse_conv_bn`. Is there any reason not to add this and also wrap the model in it? I just want to make sure I'm not missing a reason why it might have been intentionally left out.

**Comment by Czm369** [comment]
Maybe earlier implementations missed it
