### ISSUE TITLE
Why frozen_stages is 1 by default in many configs?

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#7950]
Hi, thanks for your contribution, I am wondering why `frozen_stages` is 1 by default in many configs? Can we get better performance by changing `frozen_stages` from 1 to -1?

**Comment by hhaAndroid** [comment]
@mitming This should be the result of tuning. Originally from [ResNet](https://github.com/facebookresearch/Detectron/blob/main/detectron/modeling/ResNet.py). If it is your dataset and on a longer epoch, it is possible that -1 is better.

**Comment by mitming** [comment]
> @mitming This should be the result of tuning. Originally from [ResNet](https://github.com/facebookresearch/Detectron/blob/main/detectron/modeling/ResNet.py). If it is your dataset and on a longer epoch, it is possible that -1 is better.

Thanks for your answer!
