### ISSUE TITLE
ClassBalancedDataset

### ISSUE THREAD

**Issue by yangxin6** [open-mmlab/mmdetection#7954]
想问一下，在做数据平衡的时候，oversample_thr 需要根据自己的数据进行设置吗

**Comment by hhaAndroid** [comment]
`oversample_thr` means the threshold of frequency. If an image contains the categories whose frequency below the threshold, it would be repeated. So this depends on your needs.

**Comment by yangxin6** [comment]
> `oversample_thr` means the threshold of frequency. If an image contains the categories whose frequency below the threshold, it would be repeated. So this depends on your needs. 

Thank you for you reply, I have understood.
