### ISSUE TITLE
How do I change the font_size of predicted box?? 

### ISSUE THREAD

**Issue by leesangjoon1** [open-mmlab/mmdetection#7955]
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv

config_file = '/home/sangjoon/realmmdetection/mmdetection/configs/swin/cascade_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py'
checkpoint_file = '/media/sensor-lab/sensor-lab/sangjoon/20220504_mmdet_swint/white2/best_bbox_mAP_epoch_160.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')

img = '/home/sangjoon/realmmdetection/mmdetection/test_result_0504/aedes53_white.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_detector(model, img)
show_result_pyplot(model, img, result,score_thr=0.5, out_file='result8.jpg')

I change the font_size in init_detector, inference in apis, draw_labes in visualization. but the font_size is not changed.

So How do I get that??

**Comment by hhaAndroid** [comment]
```python
    # mmdet/models/detectors/base.py
    def show_result(self,
                    img,
                    result,
                    score_thr=0.3,
                    bbox_color=(72, 101, 241),
                    text_color=(72, 101, 241),
                    mask_color=None,
                    thickness=2,
                    font_size=13,
                    win_name='',
                    show=False,
                    wait_time=0,
                    out_file=None):
```
You can change this file.
