### ISSUE TITLE
what it means of result in inference code? 

### ISSUE THREAD

**Issue by leesangjoon1** [open-mmlab/mmdetection#7956]
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv

config_file = '/home/sangjoon/realmmdetection/mmdetection/configs/swin/cascade_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py'
checkpoint_file = '/media/sensor-lab/sensor-lab/sangjoon/20220504_mmdet_swint/white2/best_bbox_mAP_epoch_160.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')

img = '/home/sangjoon/realmmdetection/mmdetection/test_result_0504/aedes53_white.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_detector(model, img)
print(result)
show_result_pyplot(model, img, result,score_thr=0.5, out_file='result8.jpg')

I want to know the result so I print it. but the result is printed like this.

load checkpoint from local path: /media/sensor-lab/sensor-lab/sangjoon/20220504_mmdet_swint/white2/best_bbox_mAP_epoch_160.pth
------------------------------------------------------------------------------------
[array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([[2.58407300e+03, 2.10433667e+03, 3.23126855e+03, 2.76259326e+03,
        9.98115301e-01],
       [3.21808154e+03, 1.76806506e+03, 3.61496802e+03, 2.25606348e+03,
        9.97614503e-01],
       [3.22050952e+03, 1.49609100e+02, 3.89842480e+03, 8.01991577e+02,
        9.97450292e-01],
       [2.02563428e+03, 1.20052258e+03, 2.30296191e+03, 1.50188538e+03,
        9.94220138e-01],
       [2.19514844e+03, 6.42477844e+02, 2.47515991e+03, 8.50240723e+02,
        8.96067619e-01],
       [2.69194385e+03, 6.62032593e+02, 3.01585229e+03, 1.12459119e+03,
        8.37097347e-01],
       [2.95001685e+03, 6.77757874e+02, 3.29493457e+03, 1.00104956e+03,
        6.01028860e-01],
       [2.01086804e+03, 1.75742285e+03, 2.15133838e+03, 1.95265588e+03,
        4.15365756e-01],
       [2.68181787e+03, 6.46592285e+02, 3.30367603e+03, 1.07376648e+03,
        1.10488474e-01]], dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([[2.0033392e+03, 1.7577284e+03, 2.1579434e+03, 1.9553176e+03,
        2.6439449e-01]], dtype=float32), array([], shape=(0, 5), dtype=float32), array([[2.68923120e+03, 6.41427246e+02, 3.05115796e+03, 1.12726489e+03,
        1.50827914e-01],
       [2.94998779e+03, 6.77278931e+02, 3.29742944e+03, 1.00485815e+03,
        5.37463166e-02],
       [2.19628638e+03, 6.43043640e+02, 2.47625830e+03, 8.52549561e+02,
        5.07708751e-02]], dtype=float32), array([], shape=(0, 5), dtype=float32)]

what is means of the numbers in numpy array??? 

and how does it match to box coordinates and class name?

**Comment by hhaAndroid** [comment]
```python
     if isinstance(result, tuple):
            bbox_result, segm_result = result
            if isinstance(segm_result, tuple):
                segm_result = segm_result[0]  # ms rcnn
        else:
            bbox_result, segm_result = result, None
        bboxes = np.vstack(bbox_result)
        labels = [
            np.full(bbox.shape[0], i, dtype=np.int32)
            for i, bbox in enumerate(bbox_result)
        ]
        labels = np.concatenate(labels)
```
