### ISSUE TITLE
from scratch loading. missing key.

### ISSUE THREAD

**Issue by jacob-kang** [open-mmlab/mmdetection#7960]
I don't want to use ImageNet pretrained model. So I downloaded the COCO from scratch model.
[from scratch](https://github.com/open-mmlab/mmdetection/tree/master/configs/scratch) docs.
It is 'scratch_faster_rcnn_r50_fpn_gn_6x_bbox_mAP-0.407_20200201_193013-90813d01.pth'.
And I load this pth file in config file.

`
init_cfg=dict(type='Pretrained', checkpoint='mmdetection/checkpoints/scratch_faster_rcnn_r50_fpn_gn_6x_bbox_mAP-0.407_20200201_193013-90813d01.pth')
`
It loaded but too much missing keys and unexpetec keys.

`
unexpected key in source state_dict: backbone.conv1.weight, backbone.gn1.weight, backbone.gn1.bias, backbone.layer1.0.conv1.weight, backbone.layer1.0.gn1.weight, backbone.layer1.0.gn1.bias, backbone.layer1.0.conv2.weight, backbone.layer1.0.gn2.weight, backbone.layer1.0.gn2.bias, backbone.layer1.0.conv3.weight, backbone.layer1.0.gn3.weight, backbone.layer1.0.gn3.bias, backbone.layer1.0.downsample.0.weight, backbone.layer1.0.downsample.1.weight, backbone.layer1.0.downsample.1.bias, backbone.layer1.1.conv1.weight, backbone.layer1.1.gn1.weight, backbone.layer1.1.gn1.bias, backbone.layer1.1.conv2.weight, backbone.layer1.1.gn2.weight, backbone.layer1.1.gn2.bias, backbone.layer1.1.conv3.weight, backbone.layer1.1.gn3.weight, backbone.layer1.1.gn3.bias, backbone.layer1.2.conv1.weight, backbone.layer1.2.gn1.weight, backbone.layer1.2.gn1.bias, backbone.layer1.2.conv2.weight, backbone.layer1.2.gn2.weight, backbone.layer1.2.gn2.bias, backbone.layer1.2.conv3.weight, backbone.layer1.2.gn3.weight, backbone.layer1.2.gn3.bias, backbone.layer2.0.conv1.weight, backbone.layer2.0.gn1.weight, backbone.layer2.0.gn1.bias, backbone.layer2.0.conv2.weight, backbone.layer2.0.gn2.weight, backbone.layer2.0.gn2.bias, backbone.layer2.0.conv3.weight, backbone.layer2.0.gn3.weight, backbone.layer2.0.gn3.bias, backbone.layer2.0.downsample.0.weight, backbone.layer2.0.downsample.1.weight, backbone.layer2.0.downsample.1.bias, backbone.layer2.1.conv1.weight, backbone.layer2.1.gn1.weight, backbone.layer2.1.gn1.bias, backbone.layer2.1.conv2.weight, backbone.layer2.1.gn2.weight, backbone.layer2.1.gn2.bias, backbone.layer2.1.conv3.weight, backbone.layer2.1.gn3.weight, backbone.layer2.1.gn3.bias, backbone.layer2.2.conv1.weight, backbone.layer2.2.gn1.weight, backbone.layer2.2.gn1.bias, backbone.layer2.2.conv2.weight, backbone.layer2.2.gn2.weight, backbone.layer2.2.gn2.bias, backbone.layer2.2.conv3.weight, backbone.layer2.2.gn3.weight, backbone.layer2.2.gn3.bias, backbone.layer2.3.conv1.weight, backbone.layer2.3.gn1.weight, backbone.layer2.3.gn1.bias, backbone.layer2.3.conv2.weight, backbone.layer2.3.gn2.weight, backbone.layer2.3.gn2.bias, backbone.layer2.3.conv3.weight, backbone.layer2.3.gn3.weight, backbone.layer2.3.gn3.bias, backbone.layer3.0.conv1.weight, backbone.layer3.0.gn1.weight, backbone.layer3.0.gn1.bias, backbone.layer3.0.conv2.weight, backbone.layer3.0.gn2.weight, backbone.layer3.0.gn2.bias, backbone.layer3.0.conv3.weight, backbone.layer3.0.gn3.weight, backbone.layer3.0.gn3.bias, backbone.layer3.0.downsample.0.weight, backbone.layer3.0.downsample.1.weight, backbone.layer3.0.downsample.1.bias, backbone.layer3.1.conv1.weight, backbone.layer3.1.gn1.weight, backbone.layer3.1.gn1.bias, backbone.layer3.1.conv2.weight, backbone.layer3.1.gn2.weight, backbone.layer3.1.gn2.bias, backbone.layer3.1.conv3.weight, backbone.layer3.1.gn3.weight, backbone.layer3.1.gn3.bias, backbone.layer3.2.conv1.weight, backbone.layer3.2.gn1.weight, backbone.layer3.2.gn1.bias, backbone.layer3.2.conv2.weight, backbone.layer3.2.gn2.weight, backbone.layer3.2.gn2.bias, backbone.layer3.2.conv3.weight, backbone.layer3.2.gn3.weight, backbone.layer3.2.gn3.bias, backbone.layer3.3.conv1.weight, backbone.layer3.3.gn1.weight, backbone.layer3.3.gn1.bias, backbone.layer3.3.conv2.weight, backbone.layer3.3.gn2.weight, backbone.layer3.3.gn2.bias, backbone.layer3.3.conv3.weight, backbone.layer3.3.gn3.weight, backbone.layer3.3.gn3.bias, backbone.layer3.4.conv1.weight, backbone.layer3.4.gn1.weight, backbone.layer3.4.gn1.bias, backbone.layer3.4.conv2.weight, backbone.layer3.4.gn2.weight, backbone.layer3.4.gn2.bias, backbone.layer3.4.conv3.weight, backbone.layer3.4.gn3.weight, backbone.layer3.4.gn3.bias, backbone.layer3.5.conv1.weight, backbone.layer3.5.gn1.weight, backbone.layer3.5.gn1.bias, backbone.layer3.5.conv2.weight, backbone.layer3.5.gn2.weight, backbone.layer3.5.gn2.bias, backbone.layer3.5.conv3.weight, backbone.layer3.5.gn3.weight, backbone.layer3.5.gn3.bias, backbone.layer4.0.conv1.weight, backbone.layer4.0.gn1.weight, backbone.layer4.0.gn1.bias, backbone.layer4.0.conv2.weight, backbone.layer4.0.gn2.weight, backbone.layer4.0.gn2.bias, backbone.layer4.0.conv3.weight, backbone.layer4.0.gn3.weight, backbone.layer4.0.gn3.bias, backbone.layer4.0.downsample.0.weight, backbone.layer4.0.downsample.1.weight, backbone.layer4.0.downsample.1.bias, backbone.layer4.1.conv1.weight, backbone.layer4.1.gn1.weight, backbone.layer4.1.gn1.bias, backbone.layer4.1.conv2.weight, backbone.layer4.1.gn2.weight, backbone.layer4.1.gn2.bias, backbone.layer4.1.conv3.weight, backbone.layer4.1.gn3.weight, backbone.layer4.1.gn3.bias, backbone.layer4.2.conv1.weight, backbone.layer4.2.gn1.weight, backbone.layer4.2.gn1.bias, backbone.layer4.2.conv2.weight, backbone.layer4.2.gn2.weight, backbone.layer4.2.gn2.bias, backbone.layer4.2.conv3.weight, backbone.layer4.2.gn3.weight, backbone.layer4.2.gn3.bias, neck.lateral_convs.0.conv.weight, neck.lateral_convs.0.gn.weight, neck.lateral_convs.0.gn.bias, neck.lateral_convs.1.conv.weight, neck.lateral_convs.1.gn.weight, neck.lateral_convs.1.gn.bias, neck.lateral_convs.2.conv.weight, neck.lateral_convs.2.gn.weight, neck.lateral_convs.2.gn.bias, neck.lateral_convs.3.conv.weight, neck.lateral_convs.3.gn.weight, neck.lateral_convs.3.gn.bias, neck.fpn_convs.0.conv.weight, neck.fpn_convs.0.gn.weight, neck.fpn_convs.0.gn.bias, neck.fpn_convs.1.conv.weight, neck.fpn_convs.1.gn.weight, neck.fpn_convs.1.gn.bias, neck.fpn_convs.2.conv.weight, neck.fpn_convs.2.gn.weight, neck.fpn_convs.2.gn.bias, neck.fpn_convs.3.conv.weight, neck.fpn_convs.3.gn.weight, neck.fpn_convs.3.gn.bias, rpn_head.rpn_conv.weight, rpn_head.rpn_conv.bias, rpn_head.rpn_cls.weight, rpn_head.rpn_cls.bias, rpn_head.rpn_reg.weight, rpn_head.rpn_reg.bias, roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias, roi_head.bbox_head.fc_reg.weight, roi_head.bbox_head.fc_reg.bias, roi_head.bbox_head.shared_convs.0.conv.weight, roi_head.bbox_head.shared_convs.0.gn.weight, roi_head.bbox_head.shared_convs.0.gn.bias, roi_head.bbox_head.shared_convs.1.conv.weight, roi_head.bbox_head.shared_convs.1.gn.weight, roi_head.bbox_head.shared_convs.1.gn.bias, roi_head.bbox_head.shared_convs.2.conv.weight, roi_head.bbox_head.shared_convs.2.gn.weight, roi_head.bbox_head.shared_convs.2.gn.bias, roi_head.bbox_head.shared_convs.3.conv.weight, roi_head.bbox_head.shared_convs.3.gn.weight, roi_head.bbox_head.shared_convs.3.gn.bias, roi_head.bbox_head.shared_fcs.0.weight, roi_head.bbox_head.shared_fcs.0.bias
missing keys in source state_dict: conv1.weight, bn1.weight, bn1.bias, bn1.running_mean, bn1.running_var, layer1.0.conv1.weight, layer1.0.bn1.weight, layer1.0.bn1.bias, layer1.0.bn1.running_mean, layer1.0.bn1.running_var, layer1.0.conv2.weight, layer1.0.bn2.weight, layer1.0.bn2.bias, layer1.0.bn2.running_mean, layer1.0.bn2.running_var, layer1.0.conv3.weight, layer1.0.bn3.weight, layer1.0.bn3.bias, layer1.0.bn3.running_mean, layer1.0.bn3.running_var, layer1.0.downsample.0.weight, layer1.0.downsample.1.weight, layer1.0.downsample.1.bias, layer1.0.downsample.1.running_mean, layer1.0.downsample.1.running_var, layer1.1.conv1.weight, layer1.1.bn1.weight, layer1.1.bn1.bias, layer1.1.bn1.running_mean, layer1.1.bn1.running_var, layer1.1.conv2.weight, layer1.1.bn2.weight, layer1.1.bn2.bias, layer1.1.bn2.running_mean, layer1.1.bn2.running_var, layer1.1.conv3.weight, layer1.1.bn3.weight, layer1.1.bn3.bias, layer1.1.bn3.running_mean, layer1.1.bn3.running_var, layer1.2.conv1.weight, layer1.2.bn1.weight, layer1.2.bn1.bias, layer1.2.bn1.running_mean, layer1.2.bn1.running_var, layer1.2.conv2.weight, layer1.2.bn2.weight, layer1.2.bn2.bias, layer1.2.bn2.running_mean, layer1.2.bn2.running_var, layer1.2.conv3.weight, layer1.2.bn3.weight, layer1.2.bn3.bias, layer1.2.bn3.running_mean, layer1.2.bn3.running_var, layer2.0.conv1.weight, layer2.0.bn1.weight, layer2.0.bn1.bias, layer2.0.bn1.running_mean, layer2.0.bn1.running_var, layer2.0.conv2.weight, layer2.0.bn2.weight, layer2.0.bn2.bias, layer2.0.bn2.running_mean, layer2.0.bn2.running_var, layer2.0.conv3.weight, layer2.0.bn3.weight, layer2.0.bn3.bias, layer2.0.bn3.running_mean, layer2.0.bn3.running_var, layer2.0.downsample.0.weight, layer2.0.downsample.1.weight, layer2.0.downsample.1.bias, layer2.0.downsample.1.running_mean, layer2.0.downsample.1.running_var, layer2.1.conv1.weight, layer2.1.bn1.weight, layer2.1.bn1.bias, layer2.1.bn1.running_mean, layer2.1.bn1.running_var, layer2.1.conv2.weight, layer2.1.bn2.weight, layer2.1.bn2.bias, layer2.1.bn2.running_mean, layer2.1.bn2.running_var, layer2.1.conv3.weight, layer2.1.bn3.weight, layer2.1.bn3.bias, layer2.1.bn3.running_mean, layer2.1.bn3.running_var, layer2.2.conv1.weight, layer2.2.bn1.weight, layer2.2.bn1.bias, layer2.2.bn1.running_mean, layer2.2.bn1.running_var, layer2.2.conv2.weight, layer2.2.bn2.weight, layer2.2.bn2.bias, layer2.2.bn2.running_mean, layer2.2.bn2.running_var, layer2.2.conv3.weight, layer2.2.bn3.weight, layer2.2.bn3.bias, layer2.2.bn3.running_mean, layer2.2.bn3.running_var, layer2.3.conv1.weight, layer2.3.bn1.weight, layer2.3.bn1.bias, layer2.3.bn1.running_mean, layer2.3.bn1.running_var, layer2.3.conv2.weight, layer2.3.bn2.weight, layer2.3.bn2.bias, layer2.3.bn2.running_mean, layer2.3.bn2.running_var, layer2.3.conv3.weight, layer2.3.bn3.weight, layer2.3.bn3.bias, layer2.3.bn3.running_mean, layer2.3.bn3.running_var, layer3.0.conv1.weight, layer3.0.bn1.weight, layer3.0.bn1.bias, layer3.0.bn1.running_mean, layer3.0.bn1.running_var, layer3.0.conv2.weight, layer3.0.bn2.weight, layer3.0.bn2.bias, layer3.0.bn2.running_mean, layer3.0.bn2.running_var, layer3.0.conv3.weight, layer3.0.bn3.weight, layer3.0.bn3.bias, layer3.0.bn3.running_mean, layer3.0.bn3.running_var, layer3.0.downsample.0.weight, layer3.0.downsample.1.weight, layer3.0.downsample.1.bias, layer3.0.downsample.1.running_mean, layer3.0.downsample.1.running_var, layer3.1.conv1.weight, layer3.1.bn1.weight, layer3.1.bn1.bias, layer3.1.bn1.running_mean, layer3.1.bn1.running_var, layer3.1.conv2.weight, layer3.1.bn2.weight, layer3.1.bn2.bias, layer3.1.bn2.running_mean, layer3.1.bn2.running_var, layer3.1.conv3.weight, layer3.1.bn3.weight, layer3.1.bn3.bias, layer3.1.bn3.running_mean, layer3.1.bn3.running_var, layer3.2.conv1.weight, layer3.2.bn1.weight, layer3.2.bn1.bias, layer3.2.bn1.running_mean, layer3.2.bn1.running_var, layer3.2.conv2.weight, layer3.2.bn2.weight, layer3.2.bn2.bias, layer3.2.bn2.running_mean, layer3.2.bn2.running_var, layer3.2.conv3.weight, layer3.2.bn3.weight, layer3.2.bn3.bias, layer3.2.bn3.running_mean, layer3.2.bn3.running_var, layer3.3.conv1.weight, layer3.3.bn1.weight, layer3.3.bn1.bias, layer3.3.bn1.running_mean, layer3.3.bn1.running_var, layer3.3.conv2.weight, layer3.3.bn2.weight, layer3.3.bn2.bias, layer3.3.bn2.running_mean, layer3.3.bn2.running_var, layer3.3.conv3.weight, layer3.3.bn3.weight, layer3.3.bn3.bias, layer3.3.bn3.running_mean, layer3.3.bn3.running_var, layer3.4.conv1.weight, layer3.4.bn1.weight, layer3.4.bn1.bias, layer3.4.bn1.running_mean, layer3.4.bn1.running_var, layer3.4.conv2.weight, layer3.4.bn2.weight, layer3.4.bn2.bias, layer3.4.bn2.running_mean, layer3.4.bn2.running_var, layer3.4.conv3.weight, layer3.4.bn3.weight, layer3.4.bn3.bias, layer3.4.bn3.running_mean, layer3.4.bn3.running_var, layer3.5.conv1.weight, layer3.5.bn1.weight, layer3.5.bn1.bias, layer3.5.bn1.running_mean, layer3.5.bn1.running_var, layer3.5.conv2.weight, layer3.5.bn2.weight, layer3.5.bn2.bias, layer3.5.bn2.running_mean, layer3.5.bn2.running_var, layer3.5.conv3.weight, layer3.5.bn3.weight, layer3.5.bn3.bias, layer3.5.bn3.running_mean, layer3.5.bn3.running_var, layer4.0.conv1.weight, layer4.0.bn1.weight, layer4.0.bn1.bias, layer4.0.bn1.running_mean, layer4.0.bn1.running_var, layer4.0.conv2.weight, layer4.0.bn2.weight, layer4.0.bn2.bias, layer4.0.bn2.running_mean, layer4.0.bn2.running_var, layer4.0.conv3.weight, layer4.0.bn3.weight, layer4.0.bn3.bias, layer4.0.bn3.running_mean, layer4.0.bn3.running_var, layer4.0.downsample.0.weight, layer4.0.downsample.1.weight, layer4.0.downsample.1.bias, layer4.0.downsample.1.running_mean, layer4.0.downsample.1.running_var, layer4.1.conv1.weight, layer4.1.bn1.weight, layer4.1.bn1.bias, layer4.1.bn1.running_mean, layer4.1.bn1.running_var, layer4.1.conv2.weight, layer4.1.bn2.weight, layer4.1.bn2.bias, layer4.1.bn2.running_mean, layer4.1.bn2.running_var, layer4.1.conv3.weight, layer4.1.bn3.weight, layer4.1.bn3.bias, layer4.1.bn3.running_mean, layer4.1.bn3.running_var, layer4.2.conv1.weight, layer4.2.bn1.weight, layer4.2.bn1.bias, layer4.2.bn1.running_mean, layer4.2.bn1.running_var, layer4.2.conv2.weight, layer4.2.bn2.weight, layer4.2.bn2.bias, layer4.2.bn2.running_mean, layer4.2.bn2.running_var, layer4.2.conv3.weight, layer4.2.bn3.weight, layer4.2.bn3.bias, layer4.2.bn3.running_mean, layer4.2.bn3.running_var
`

And I can't understand cleary the differeces between load_from vs pretrained. [issues](https://github.com/open-mmlab/mmdetection/issues/1247)
Is it right to use 'pretrianed' if I want to use the pretrained backbone only? and If want to use whole weight include backbone, neck, etc, Do I have to use load_from?

**Comment by hhaAndroid** [comment]
@jacob-kang 
- If you just want to not load ImageNet pretrained weights, you can set `init_cfg` to None. 
- If you want to load the whole weight, you can use` load_from`. 
- The pretrained will only load the weights of the backbone part.

**Comment by jacob-kang** [comment]
> @jacob-kang
> 
> * If you just want to not load ImageNet pretrained weights, you can set `init_cfg` to None.
> * If you want to load the whole weight, you can use` load_from`.
> * The pretrained will only load the weights of the backbone part.

Thanks for replying.
I wonder what parts checkpoints include (which are the result of train).
And I wonder why this checkpoint [scratch_faster_rcnn_r50_fpn_gn_6x_bbox_mAP-0.407_20200201_193013-90813d01.pth'](https://github.com/open-mmlab/mmdetection/tree/master/configs/scratch) doesn't work properly.
I loaded this model with using `init_cfg=dict(type='Pretrained', checkpoint='mmdetection/checkpoints/scratch_faster_rcnn_r50_fpn_gn_6x_bbox_mAP-0.407_20200201_193013-90813d01.pth')`
But too much missing keys and unexpected keys.

Is this different from other checkpoints?
