### ISSUE TITLE
Using the trained model outside of mmdetection

### ISSUE THREAD

**Issue by gabrielalexandre** [open-mmlab/mmdetection#7961]
Before starting, I apologize for my poor English.
I'm a beginner in this area and I'm doing an object detection project and I'm using mmdetection, the training is going well, but I would like to use the trained model to separate images that contain the searched objects from images that don't contain the objects (put them in different folders). I wanted to know if mmdetection supports this and if not if I can use the trained model in another code so that the separation can be done

**Comment by hhaAndroid** [comment]
@gabrielalexandre Sorry, no script for now. But you can judge the prediction result based on https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py, if there is no box, save it to a specific folder.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 8 days.
