### ISSUE TITLE
What is the difference between time and data_time in mmdetection train log?

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#7965]
![image](https://user-images.githubusercontent.com/25839884/167860977-510e4066-02a2-4884-b74d-ac7dd559499a.png)

**Comment by jbwang1997** [comment]
You can refer to [`IterTimerHook`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/iter_timer.py). `data_time` is the time of data processing in dataloader. `time` is the whole time of one iteration.
