### ISSUE TITLE
training with voc datasets error

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmdetection#7968]
data config:
 dataset=dict(
            type='VOCDataset',
            ann_file=[
                'datasets/Car_License_Plate/VOC2007/ImageSets/Main/trainval.txt'
            ],
            img_prefix=['datasets/Car_License_Plate/VOC2007/'],
            classes = classes,
            ...

dataset folder:
datasets/VOC2007
 --Annotations
 --JPEGImages #file with extension  *.png not .jpg
 --ImageSets

label:

the error imformation: 
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Car_License_Plate/VOC2007/JPEGImages/Cars4.jpg'

why does mmdet not to fetch Cars4.png?

**Comment by RangiLyu** [comment]
Because the image format in VOC dataset should be jpg.
Refer to this line https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/datasets/xml_style.py#L51

And if you want to load png files, just modify that code.
