### ISSUE TITLE
how can use def areas from .../mask/structures.py ? 

### ISSUE THREAD

**Issue by jwyng2000** [open-mmlab/mmdetection#7969]
I fount this issues(https://github.com/open-mmlab/mmdetection/issues/3418), so tried to calculate areas of mask. but always error had been occured.

my code is this

        `masks = np.where(result[1][0][0])

        maskss = masks[0:1]
        x_list=[]
        for i in maskss:
            x_list.append(maskss[0][i])
        
        masksss = masks[1:2]
        y_list=[]
        for i in maskss:
            y_list.append(masksss[0][i])

        areaaa = np.column_stack((x_list,y_list))

        area = PolygonMasks(areaaa, len(areaaa), 2).areas`

How can i get width, height of mask? It's very hard to gain the values... 

Can anyone helpme? Thank you!

**Comment by RangiLyu** [comment]
similar issue #7869. The sum of where mask>0 should be equal to the mask area.

**Comment by jwyng2000** [comment]
> similar issue #7869. The sum of where mask>0 should be equal to the mask area.

Thx for reply. I get into your link but still don't understand how to get it .. i'm real noob of this work.. 
I have two questions.

1. Can I use the function in 'structures.py/(bitmap or polygon).areas' to get the mask area?

2. If I can get it, how can I get the necessary parameters such as mask, height, and width from the result? i mean
this -> `result = inference_detector(model, frame)` 

I tried many different methods, but I didn't succeed. If you can help me it would be veru greatful. Thank you.
