### ISSUE TITLE
AttributeError: 'PartA2' object has no attribute 'test_cfg'

### ISSUE THREAD

**Issue by udnqv** [open-mmlab/mmdetection#7970]
Hi,
I'm trying to run an evaluation on the PartA2 model. However, when I try run it, I get following error:
![image](https://user-images.githubusercontent.com/51906480/168040272-77113d37-1a8c-4641-8f56-d335e39a028a.png)
Thanks in advance for the help!

**Comment by RangiLyu** [comment]
You are using MMDetection3D. Please transfer this issue to https://github.com/open-mmlab/mmdetection3d
