### ISSUE TITLE
Where is Progress of MMDetection v2.25.0 managed?

### ISSUE THREAD

**Issue by Keiku** [open-mmlab/mmdetection#7977]
Recently, I couldn't keep up with the version up of mmdetection, but I couldn't find out how the progress was managed. Does anyone know?

**Comment by BIGWangYuDong** [comment]
MMDet is now at v2.24.1, MMDet release the version monthly, so in theory, v2.25.0 will release before June.

**Comment by Keiku** [comment]
Sorry for the late reply. Did you stop using GitHub Projects for management? Personally, it was good that it was easy to understand.

> MMDet release the version monthly

I understand that it is monthly, but I cannot confirm the progress of the contents.

**Comment by ZwwWayne** [comment]
The team is a bit busy recently. We are also trying to find a better way to manage the action items but it need some time.

**Comment by Keiku** [comment]
I understand what the situation is. Thank you for your reply despite your busy schedule.

**Comment by ZwwWayne** [comment]
They will be managed through milestones.
