### ISSUE TITLE
bbox_color

### ISSUE THREAD

**Issue by yaofanji** [open-mmlab/mmdetection#7980]
How to make different prediction boxes have different colors?

**Comment by chhluo** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/core/visualization/image.py#L403

If you use image_demo.py to visulize, you can define your own palette and pass it into 
https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/demo/image_demo.py#L18

For how to define palette , please refer to https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/datasets/coco.py#L40

**Comment by yaofanji** [comment]
thanks
