### ISSUE TITLE
Annotation is wrong?

### ISSUE THREAD

**Issue by ycyinchao** [open-mmlab/mmdetection#7981]
In anchor_generator.py file line 280: should not be (0,1),(0,2) but should be (1,0),(2,0).right?

**Comment by chhluo** [comment]
No, (0,1),(0,2) is right. You can print the shift to verify that.

**Comment by ycyinchao** [comment]
![image](https://user-images.githubusercontent.com/105531816/168477924-ce202a5e-93f3-4f09-8a0e-411e3308f59d.png)
![image](https://user-images.githubusercontent.com/105531816/168478070-c8c6eb6c-e018-42cc-9f0f-ccd9ef0172db.png)
I printed the first three values of shifts as required (that is, the coordinates before the (0,0), (0,1), (0,2) anchors mentioned in the comment), and the mapping back to the original image is indeed the feature map Points on (0,0), (1,0), (2,0). The proof is as follows: 
(0,0)->(0,0);
(8,0)->(1,0);
(16,0)-(2,0)

**Comment by ycyinchao** [comment]
@chhluo

**Comment by chhluo** [comment]
But the order of columns in `shifts` is `[shift_xx, shift_yy, shift_xx, shift_yy]`.

**Comment by ycyinchao** [comment]
ok, i see what you mean, thanks
