### ISSUE TITLE
This problem occurs when training your own dataset with yolox

### ISSUE THREAD

**Issue by Luxiangxiang21** [open-mmlab/mmdetection#7982]
This problem occurs when training your own dataset with yolox：
![image](https://user-images.githubusercontent.com/101502967/168413566-103d4865-df17-4dda-a8b3-468026b126a2.png)
No solution after a long time of thinking.How do I resolve this?

**Comment by chhluo** [comment]
which dataset did you use?

**Comment by Luxiangxiang21** [comment]
> My own dataset, will this have an impact on the training results?

**Comment by chhluo** [comment]
This error occured while reading the image. So there may exits some bad images.

**Comment by Luxiangxiang21** [comment]
> This error occured while reading the image. So there may exits some bad images.

Will it have any effect on the outcome?

**Comment by chhluo** [comment]
This's a warning of cv2.imread. I think it has no effect the outcome If these bad images can be loaded successfully and visually normal.

**Comment by Luxiangxiang21** [comment]
> This's a warning of cv2.imread. I think it has no effect the outcome If these bad images can be loaded successfully and visually normal.
thanks！！
