### ISSUE TITLE
Does neck and roi head need Normalization to get better convergency ?

### ISSUE THREAD

**Issue by Haijunlv** [open-mmlab/mmdetection#7990]
i have found several model configs in repo with different Normalization strategy.
such like:
1. faster_rcnn_r50_fpn:   neck and roi head  **do not** apply bn.   [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/faster_rcnn_r50_fpn.py)
2. faster_rcnn_r50_fpn_crop640_50e_coco:  neck and roi head apply bn.   [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/fpg/faster_rcnn_r50_fpn_crop640_50e_coco.py#L9)
3. faster_rcnn_r50_fpn_gn_ws-all_1x_coco:   neck and roi head apply gn.   [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/gn%2Bws/faster_rcnn_r50_fpn_gn_ws-all_1x_coco.py#L10)
4. retinanet_r50_fpn: neck and roi head  **do not** apply bn. [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/retinanet_r50_fpn.py)
5. retinanet_r50_fpn_crop640_50e_coco:   neck and roi head apply bn,  [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/nas_fpn/retinanet_r50_fpn_crop640_50e_coco.py)

why some models apply Normalization in neck and roi head.  and some models do not apply Normalization in neck and roi head?
For one special situation, i found faster_rcnn_r50_fpn (without neck and roi head bn)   model convergency is **worse than** other model(with neck and roi head normlization).
and if add bn in  neck and roi head, the faster_rcnn_r50_fpn model convergency is better. but slight decrease map (coco map 37.4 -> 36.4) in 12epoch training pipeline. Like below
<img width="563" alt="image" src="https://user-images.githubusercontent.com/28926237/168462063-b8f2e487-bb55-4c40-850e-c3fa5cd60d0a.png">

the special situation is **training detection model with local sgd speedup strategy**. refer to [paper](https://arxiv.org/abs/1805.09767).  
This situation will train model in local for some iters(like 1-15 iter), and average all nodes  (like 16 nodes) model weight in certain iter(16iter).   This case need average certain layer weight of all nodes, like model weight ensemble.
In image classifcation with normalization, the convergency is ok.  
But in object detection, like neck and roi head with no bn, the convergency is very worse. 

So could you give some advice about the feasibility of adding norm layer in neck and roi head.

**Comment by ZwwWayne** [comment]
These config simply follows the original paper's implementation.
Adding BN leads to worse performance because the single GPU batch size is actually 2, which is too small. Simply adding BN will make it obtain inaccurate statistics which leads to worse performance. 
In the config of faster_rcnn_r50_fpn_crop640_50e_coco and retinanet_r50_fpn_crop640_50e_coco, you can see that the single GPU batch size is 8, thus BN can be add to improve the performance.

**Comment by ZwwWayne** [comment]
> great! your answer solved my problem. 
> 
> Maybe SYNCBN or GN or PreciseBN can improve the performance, but they are slower than BN.
> 
> Do you know any other method which can improve the performance and almost as quick as BN?
> 
> 

MMSyncBN implemented in mmcv-full is faster but still slower than BN. You can try increase the batch size
