### ISSUE TITLE
suggestion for supporting cpu inference

### ISSUE THREAD

**Issue by happog** [open-mmlab/mmdetection#80]
Thank you for your nice code. I strongly suggest for supporting CPU inference!

**Comment by hellock** [comment]
We will consider adding support for CPU inference, but maybe in November. A PR is welcome of course!

**Comment by yongtaoge** [comment]
Have mmdetection supported cpu inference?

**Comment by PumayHui** [comment]
The same issue~ 
Have mmdetection supported cpu inference? @hellock
