### ISSUE TITLE
download resnext101 pretrained model failed

### ISSUE THREAD

**Issue by k-miracle** [open-mmlab/mmdetection#800]
Hi, when I want to train focs by using fcos/fcos_mstrain_640_800_x101_64x4d_fpn_gn_2x.py,  i can't successfully download the pretrained model from the url you given, which is too slow, even one more days, how can I get the available place to get the model? thanks
(p.s I have tried these two urls but both failed: https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_64x4d-ee2c6f71.pth
or
https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnet101_caffe-3ad79236.pth)

**Comment by Maxfashko** [comment]
@hellock i have the same problem

**Comment by Maxfashko** [comment]
It seems this is solved by replacing the IP address. IP address from east europe allowed me to download weights

**Comment by hellock** [comment]
Seems to be some breakdown of AWS.

**Comment by louielu1027** [comment]
@Maxfashko Hi, how to  replace the IP address? Thanks.

**Comment by Maxfashko** [comment]
@louielu1027 I used vpn

**Comment by pingguokiller** [comment]
> @louielu1027 I used vpn

Hello. I could not download the weights even I use vpn. Could you share the pretrained weights on some open Cloud?

**Comment by CindyHuang23** [comment]
I meet the same problem, could you share the pretrained weights?

**Comment by YaoQ** [comment]
It is too hard to download the  resnext101 pretrained model, if it is possible, please share it on Google drive or Baidu Pan.
Thanks.

**Comment by guancheng817** [comment]
same question, it is hard to download resnext101 pretrained model, could you share it with another link, thanks..

**Comment by guotong1988** [comment]
Same question.
