### ISSUE TITLE
Error in the tutorial

### ISSUE THREAD

**Issue by fredericschmidt** [open-mmlab/mmdetection#8007]
Hi,

Thank you for sharing your fantastic tool.

I made the installation and the get_started is working fine.
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md

When I want to run the tutorial for learning, I get the following error :
https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb

===========
Traceback (most recent call last):
  File "/opt/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'times'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmdet_tuto3.py", line 298, in <module>
    datasets = [build_dataset(cfg.data.train)]
  File "/data/mmdetection/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: KittiTinyDataset: __init__() got an unexpected keyword argument 'times'
===========

This seemed to be related to the type, which should (or not) be "RepeatDataset". Could you help me please ?

Thank you !

Frédéric

**Comment by jbwang1997** [comment]
Thank you for your report. I have run the [MMDet_Tutorial.ipynb](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb) again. But I didn't find the same bug. Please check if you have 
 edited the original config or if you run the tutorial in the master branch.

What's more, when running this tutorial again, A new bug was found. I will fix this bug as soon as possible. You can first replace the codes in the section `Train a new detector` with the below codes.
```
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import train_detector
from mmdet.utils import get_device


# Build dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_detector(cfg.model)
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
cfg.device = get_device()
train_detector(model, datasets, cfg, distributed=False, validate=True)
```

**Comment by saadyousuf45** [comment]
same error for SSD training

**Comment by fredericschmidt** [comment]
Now it's working fine on my computer.

The only thing that is missing in the tutorial is to define the device before building dataset/detector:
cfg.device='cuda'

Thank you !

PS:
Please note that the inference is done with:
faster_rcnn_r50_caffe_fpn_mstrain_3x_coco.py
whereas the training is done with:
faster_rcnn_r50_caffe_fpn_mstrain_1x_coco.py

**Comment by lywang76** [comment]
I met same problem today. 

And the order of adding line 
cfg.device='cuda' into the demo file
impacts the bug fix.

Sincerely hope PR can fix the original demo file and avoid the same errors happening to others in the future.

**Comment by wanghonglie** [comment]
Hi, we noticed this problem and fixed it in [PR9112](https://github.com/open-mmlab/mmdetection/pull/9112)
