### ISSUE TITLE
Problem with Tood detector

### ISSUE THREAD

**Issue by dsp6414** [open-mmlab/mmdetection#8014]
when i train tood model with yymnist from scratch, cls_loss is 0 within 5 epoch(overfitting?), test result is nothing.while training with pretrained weights, i can obtain correct detected result. trying with other custom dataset remains the same situation.

**Comment by jbwang1997** [comment]
Maybe your dataset is too small. It's hard for detectors to be trained without overfitting from scratch. You can add more strong augmentations or extend the dataset.
