### ISSUE TITLE
RuntimeError:expected scalar type Half but found Float

### ISSUE THREAD

**Issue by Audrey528** [open-mmlab/mmdetection#8017]
I wanna use fp16 to train, Imy roi_head is d2det , which is added by myself, can u give me some advice? 
![1652941979(1)](https://user-images.githubusercontent.com/68552295/169225844-abffaf2b-509a-4e33-b841-06941a398793.png)

**Comment by RangiLyu** [comment]
If you want to use fp16 training, please add this to your config:
```
fp16 = dict(loss_scale='dynamic')
```

**Comment by Audrey528** [comment]
@RangiLyu I did this like you say, but it was wrong, please see the picture above.

**Comment by Audrey528** [comment]
@RangiLyu How can I add fp16 in d2et_roi_head.py, which I added by myself. I need u help, appreciate it!

**Comment by RangiLyu** [comment]
Maybe you need to add fp16_enabled flag in the head like:
https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L55

and add auto_fp16 and force_fp32 decorator to some of the functions.
