### ISSUE TITLE
YOLOv3- Losses are very large and validation mAP is zero

### ISSUE THREAD

**Issue by David-Biggs** [open-mmlab/mmdetection#8019]
I'm training YOLOv3 on a coco dataset, but the losses are very large, and the validation mAP are all zero. I successfully use the same dataset to train Mask R-CNN, HTC and Cascade Mask R-CNN. 

![image](https://user-images.githubusercontent.com/64862726/169260144-af1cc9fe-3f9b-4cb4-81dc-e1ee86eaeea9.png)

Yolov3 is a single-stage object detection model while the others are two-stage instance segmentation models. What do I need to change in the config for object detection?

Here is my config:
[yolov3_config.txt](https://github.com/open-mmlab/mmdetection/files/8727805/yolov3_config.txt)

Many thanks.

**Comment by RangiLyu** [comment]
It seems that you set samples_per_gpu=1 to train the model. But YOLOv3 requires larger batch to train. Please increase your batch size.

**Comment by David-Biggs** [comment]
Thanks, @RangiLyu. I will give that a try. 

Would it be possible if you could check out issue #7971, please?

**Comment by aizensousuke0413** [comment]
I had the same problem when training CenterNET，I tried to modify the dataset type and failed.

**Comment by David-Biggs** [comment]
> I had the same problem when training CenterNET，I tried to modify the dataset type and failed.

I increased the batch size (samples_per_gpu) I used during training and then seemed to increase the rate of convergence. I did not modify the dataset type ( I am using COCOdataset)

**Comment by Zoe-TAN** [comment]
> 
Would you mind telling us how large the batch size you used during training?
