### ISSUE TITLE
Initialization for bbox_embed bias in Deformable DETR

### ISSUE THREAD

**Issue by LukeCho-8810** [open-mmlab/mmdetection#8021]
Hi,
In Deformable DETR,  I'm curious about the initialization of biases (corresponding to w,h prediction) of bbox_embed to be -2.0? 
How is this parameter setted?

https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/models/dense_heads/deformable_detr_head.py#L92

**Comment by BIGWangYuDong** [comment]
I believe this is refer to the source paper and codes.

https://github.com/fundamentalvision/Deformable-DETR/blob/11169a60c33333af00a4849f1808023eba96a931/models/deformable_detr.py#L97-L107

**Comment by ZwwWayne** [comment]
it makes the box initialized as 0

**Comment by FL77N** [comment]
> it makes the box initialized as 0

so why not set -2 to 0
