### ISSUE TITLE
Could not export Python function call 'MultiScaleDeformableAttnFunction'

### ISSUE THREAD

**Issue by quyanqiu** [open-mmlab/mmdetection#8022]
Hi, I want to use deformable-detr in c++ project. So I use jit trace to save the torchscript model. I found that you implement two version of MultiScaleDeformableAttention. ie MultiScaleDeformableAttnFunction(GPU version) and multi_scale_deformable_attn_pytorch(cpu version). 
When I build model and move to cuda device, and use jit trace to get the torchscript model file, it is dead at torch.jit.trace.save() function and with: 
**Could not export Python function call 'MultiScaleDeformableAttnFunction'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:**

Any suggestion on how to fix this issue?Thx a lot!

**Comment by BIGWangYuDong** [comment]
Please use the issue template, I haven't met this issue before. 

Also, please check whether you installed mmcv or mmcv-full?

**Comment by ZwwWayne** [comment]
msdeformable atten has cuda operators and does not have the decorator of script. So it cannot be traced. You need to try to add it in your own mmcv to do that.

**Comment by quyanqiu** [comment]
@ZwwWayne Indeed,Thanks a lot
