### ISSUE TITLE
KeyError: 'KittiDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by Hoyyyaard** [open-mmlab/mmdetection#8025]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
------------------------------------------------------------
anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/utils/compat_config.py:30: UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
  'please set `runner` in your config.', UserWarning)
2022-05-22 13:13:09,253 - mmdet - INFO - Automatic scaling of learning rate (LR) has been disabled.
Traceback (most recent call last):
  File "tools/train.py", line 254, in <module>
    main()
  File "tools/train.py", line 250, in main
    meta=meta)
  File "/home/zhihongyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 224, in train_detector
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/home/zhihongyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 59, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'KittiDataset is not in the dataset registry'

**Reproduction**

1. What command or script did you run?

```none
 python tools/train.py configs/benchmark/hv_second_secfpn_4x8_80e_pcdet_kitti-3d-3class.py 
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? NO
3. What dataset did you use? KITTI

**Comment by ZwwWayne** [comment]
It seems that y
the file that implements kitti dataset is not correctly imported. Did you implement the kitti dataset? Please follow the documentation of customizing dataset and check whether there is any missing steps.

**Comment by Hoyyyaard** [comment]
> > It seems that y the file that implements kitti dataset is not correctly imported. Did you implement the kitti dataset? Please follow the documentation of customizing dataset and check whether there is any missing steps.
> 
> I think I just use official code in tools/train.py and follow the instructions in data_prepared.md for Kitti dataset ; And I just use the offiicial dataset of KITTI Does there any code should be added to some file?

The problem occuried when cteating the val dataset through"build_dataset(val_dataset)"

**Comment by ZwwWayne** [comment]
Seems that you are using mmdet3d？
