### ISSUE TITLE
About segm.json for mask-rcnn

### ISSUE THREAD

**Issue by aimengyisheng** [open-mmlab/mmdetection#8026]
When I output the test result in json file, the result in results.segm.json will looks like it:

{"image_id": 0, "bbox": [57.16876220703125, 217.72210693359375, 689.4974975585938, 208.8153076171875], "score": 0.9798983335494995, "category_id": 1, "segmentation": {"size": [434, 914], "counts": "Vmh0R1]<5L4K5L3M2O101N100O2O000O101O000O101O001N10001N2O0O2O001N101O00000O2O00000O2O000O2O000O2N101N1O2O0O1O2O000O101N1000001N100000001O00001O0O101O0HPMnEQ3Q:TMjEl2U:901N10001N1000001N100000010O0001hLoEn2P:QMRFn2o9oLTFP3l9oLWFP3i9mLZFT3R:0014K5K;E2M2O2M6KO0100O0010O0001O001UNbDa1^;\\NdDd1\\;YNgDg1c;O1O001O001O1O1O1O001O10O01O001O001O000001O0001O01O000000001O0001O00000001O000001O0000000000O1000000000000000000O100000000000000000000O100000000000000O100000000000000O100000000000000O10000000000001O00000000000000000000000000000000000000001O01O0001O001O00001O001O0000001O000000001O00000000000000001O0000000000001O0000000000001O0000000000000000000000000000000000000000000000000000000000O10000000000000O100000000000000000000000000000O100000000000000O10000000000O10000000000O1000000O10000O1O100O1O1O1O1O1N2O1O1O1O1N2O1O100O1O1O100O100O100N2O1O1N2O1O1O100O100O010O100O100O10000O100O1000O10O1000O10O1000O1000O10O10000000O010000000O1000O1000O100000O01000O0100O010OO2N1O2N2O0100O01000O1000O0100000O01000O010O100O00100O10O01000O0100000O10O10O100O00100O001N1000N3M2I8O010O10O010000O0100000O010000O010M3K401O0000001O000010O01O010O010O010O10O10O010O00010O01O0O1N3MGlMYEU2g:lMXES2h:PNUEP2l:QNSEo1l:SNREm1o:;00O010E_MeEa2Z:`MeEa2[:`MdE_2]:aMcE_2\\:cMcE]2]:dMbE\\2]:eMbE[2_:fM`EZ2_:hM`EX2_:jM_EV2b:=O000N2M3O10O1001O01O01O10O010O10O1000O010O10O01O001N1O2M2J6O2N2N10100O0010000O10O11N10000O100O100O1O1O1N2O1O1O100O100O10000O10000O10000O100O100O1O1O1O100O10000O100000000000O01000001O000000000O101O000O101M2N2fNPDP1Z<O1O10001N100O10000O1O2N1O1N3K4G:M3N1N3N2Mh\\W2"}}

So what is the mean of segmentation" part? If I want to get something like this, what should I do? 
"segmentation":[
[
1485.8382858000696,
497.0831564962864,
2538.697008928284,
431.28022196888924,
2696.6283068284392,
2681.7719365358353,
1643.7775838784873,
2747.574352309108,
1485.8382858000696,
497.0831564962864
]
]
By the way, can I calculate the measure（Number of pixels occupied by the result） by this result?

**Comment by ZwwWayne** [comment]
The segmentation part uses binarized coding to encode the mask. 
You can get the polygons, cocoapi provides functions to do that.

**Comment by aimengyisheng** [comment]
> The segmentation part uses binarized coding to encode the mask. You can use it tp calculate COCO mAP through cocoapi. You can get the polygons, cocoapi provides functions to do that.

I tried to write a script to translate the RLE code to polygons by using cocoapi like that.


import pycocotools.mask as mask
def main():
    compactRLESegmentation=["Vmh0R1]<5L4K5L3M2O101N100O2O000O101O000O101O001N10001N2O0O2O001N101O00000O2O00000O2O000O2O000O2N101N1O2O0O1O2O000O101N1000001N100000001O00001O0O101O0HPMnEQ3Q:TMjEl2U:901N10001N1000001N100000010O0001hLoEn2P:QMRFn2o9oLTFP3l9oLWFP3i9mLZFT3R:0014K5K;E2M2O2M6KO0100O0010O0001O001UNbDa1^;\\NdDd1\\;YNgDg1c;O1O001O001O1O1O1O001O10O01O001O001O000001O0001O01O000000001O0001O00000001O000001O0000000000O1000000000000000000O100000000000000000000O100000000000000O100000000000000O100000000000000O10000000000001O00000000000000000000000000000000000000001O01O0001O001O00001O001O0000001O000000001O00000000000000001O0000000000001O0000000000001O0000000000000000000000000000000000000000000000000000000000O10000000000000O100000000000000000000000000000O100000000000000O10000000000O10000000000O1000000O10000O1O100O1O1O1O1O1N2O1O1O1O1N2O1O100O1O1O100O100O100N2O1O1N2O1O1O100O100O010O100O100O10000O100O1000O10O1000O10O1000O1000O10O10000000O010000000O1000O1000O100000O01000O0100O010OO2N1O2N2O0100O01000O1000O0100000O01000O010O100O00100O10O01000O0100000O10O10O100O00100O001N1000N3M2I8O010O10O010000O0100000O010000O010M3K401O0000001O000010O01O010O010O010O10O10O010O00010O01O0O1N3MGlMYEU2g:lMXES2h:PNUEP2l:QNSEo1l:SNREm1o:;00O010E_MeEa2Z:`MeEa2[:`MdE_2]:aMcE_2\\:cMcE]2]:dMbE\\2]:eMbE[2_:fM`EZ2_:hM`EX2_:jM_EV2b:=O000N2M3O10O1001O01O01O10O010O10O1000O010O10O01O001N1O2M2J6O2N2N10100O0010000O10O11N10000O100O100O1O1O1N2O1O1O100O100O10000O10000O10000O100O100O1O1O1O100O10000O100000000000O01000001O000000000O101O000O101M2N2fNPDP1Z<O1O10001N100O10000O1O2N1O1N3K4G:M3N1N3N2Mh\\W2"]
    maskedArr = mask.decode(compactRLESegmentation)
    print(maskedArr)
if __name__=="__main__":
    main()


but unfortunately it doesn't work
![1](https://user-images.githubusercontent.com/105696188/169743683-ac3a2cf1-5eec-4578-b00c-b60c3d70a757.png)

so what should I do to use cocoapi? I mean what kind of input should I put into decode function. Much appreciated.

**Comment by wzr0108** [comment]
i met the same problem , have you sovled it?
