### ISSUE TITLE
Option "--validate" doesn't work while training RetinaNet with single GPU

### ISSUE THREAD

**Issue by chengcchn** [open-mmlab/mmdetection#803]
I have follow the "Getting started" to train RetinaNet with single GPU, and the CMD I used is "python tools/train.py configs/retinanet_r50_fpn_1x.py --validate". But I cann't get the validate result after every epoch.
![Snipaste_2019-06-15_10-23-50](https://user-images.githubusercontent.com/38886481/59545872-aeda9c80-8f57-11e9-8b23-386d85458154.png)
What is really weird is that when I train the RetinaNet with two GPU and use the CMD "./tools/dist_train.sh configs/retinanet_r50_fpn_1x.py 2 --validate", I can get the validate result after every epoch. Why is that?

**Comment by hellock** [comment]
Duplicated with #619

**Comment by chengcchn** [comment]
@hellock OK, I got it.
