### ISSUE TITLE
When running analyze_results.py

### ISSUE THREAD

**Issue by galaxyGGG** [open-mmlab/mmdetection#8035]
When running analyze_results.py, i met this problem:

_the data pipeline in your config file must include loading image and annotations related pipeline._

I don't know what went wrong, but everything(train or test) seems good so far, until i met this problem. I used the yolox-s config file and trained my own dataset. And in order to get the pickle file "results.pkl", i actually used the dist_test.sh.

**Comment by hhaAndroid** [comment]
@galaxyGGG This is a bug, we will fix it as soon as possible. If you are interested also create a PR to fix it.
