### ISSUE TITLE
mmcv-BN

### ISSUE THREAD

**Issue by wenguduo** [open-mmlab/mmdetection#8038]
I want to change 'BN' to 'IBN' in norm_cfg,  IBN is combined by normalization and instance normalization. How can I change it in norm.py? I have tried to add registory, but I don't know how to achieve it.

**Comment by hhaAndroid** [comment]
@wenguduo You can refer to https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_models.md#develop-new-components

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 15 days.
