### ISSUE TITLE
How to set different learning rate for different components?

### ISSUE THREAD

**Issue by Tianhao-Qi** [open-mmlab/mmdetection#8040]
Hello, I want to set different learning rate for backbone and roi_head, how can I achieve it?

**Comment by hhaAndroid** [comment]
@Tianhao-Qi You can implement Optimizer Constructor and you can refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/optimizers/layer_decay_optimizer_constructor.py#L79
