### ISSUE TITLE
How to get rid of FPN layer in Faster RCNN

### ISSUE THREAD

**Issue by will-wiki** [open-mmlab/mmdetection#8041]
hello，I have a Faster RCNN model without FPN layer. I would like to ask how to use mmdetection framework to load the Faster RCNN model without FPN layer

**Comment by will-wiki** [comment]
hello, anyone can help me

**Comment by ZwwWayne** [comment]
Please see example in https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_dc5_1x_coco.py
