### ISSUE TITLE
Attempt to get line out of bounds: 13 >= 13

### ISSUE THREAD

**Issue by wszhengjx** [open-mmlab/mmdetection#8044]
Hello,everyone！
I always meet this error,but i don't know why,can you help me,i will really apperacite
Code execution window A lot of numbers come up
and terminal show "Attempt to get line out of bounds: 13 >= 13"

**Comment by jbwang1997** [comment]
Hello @wszhengjx. Could you follow the issue template to provide more information like the environment, error report.

**Comment by jbwang1997** [comment]
This issue will be closed due to inactivity. Feel free to reopen it if you have any questions.
