### ISSUE TITLE
How mmdetection uses albumentations

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#8045]
How mmdetection uses albumentations

Hope to have a tutorial

**Comment by abdksyed** [comment]
The file albu_example looks like config file from mmdet2.x, since it has `dict(type='Collect'...)` which was removed in mmdet 3.x if I am not wrong.

Any updated config_file using Albumentations?

**Comment by qraleq** [comment]
@abdksyed Did you manage to get Albumentations to work with mmdet3.x?

**Comment by abdksyed** [comment]
Yes, I was able to use Albumentations in 3.x

Here is the sample code, how I was using them in a notebook
```python

albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.3,
        scale_limit=0.2,
        rotate_limit=30,
        interpolation=1,
        p=0.4),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='CLAHE',
                clip_limit=5.0,
                tile_grid_size=(11,11),
                p=1.0),
            dict(type='ColorJitter', brightness=0.4, contrast=0.4, saturation=0.4, hue=0.2,p=1.0),
            dict(type='RandomBrightnessContrast', brightness_limit=0.4, contrast_limit=0.4, p=1.0),
            dict(type='Equalize', p=1.0),
        ],
        p=0.2),
    dict(type='JpegCompression', quality_lower=65, quality_upper=95, p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=5, p=1.0),
        ],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(type='ElasticTransform', p=1, alpha=120, sigma=120 * 0.05, alpha_affine=120 * 0.03),
            dict(type='GridDistortion', p=1),
            dict(type='OpticalDistortion', distort_limit=2, shift_limit=0.5, p=1)
        ],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(type='CenterCrop', height = 448, width = 448, p=1),
            dict(type='CropNonEmptyMaskIfExists', height = 720, width = 720, p=1),
            dict(type='BBoxSafeRandomCrop', erosion_rate=0.1, p=1),
        ],
        p=0.3),
]

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(
        type='LoadAnnotations',
        with_bbox=True,
        with_mask=True),
        # poly2mask=True),
    dict(type='Resize', scale=(900, 720)),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_bboxes_labels', 'gt_ignore_flags'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_masks': 'masks',
            'gt_bboxes': 'bboxes'
        },
        skip_img_without_anno=True),
    # dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs', 
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape'))
]
  
cfg.train_pipeline = train_pipeline
```

**Comment by the-didi** [comment]
> Yes, I was able to use Albumentations in 3.x
> 
> Here is the sample code, how I was using them in a notebook
> 
> albu_train_transforms = [
>     dict(
>         type='ShiftScaleRotate',
>         shift_limit=0.3,
>         scale_limit=0.2,
>         rotate_limit=30,
>         interpolation=1,
>         p=0.4),
>     dict(
>         type='OneOf',
>         transforms=[
>             dict(
>                 type='CLAHE',
>                 clip_limit=5.0,
>                 tile_grid_size=(11,11),
>                 p=1.0),
>             dict(type='ColorJitter', brightness=0.4, contrast=0.4, saturation=0.4, hue=0.2,p=1.0),
>             dict(type='RandomBrightnessContrast', brightness_limit=0.4, contrast_limit=0.4, p=1.0),
>             dict(type='Equalize', p=1.0),
>         ],
>         p=0.2),
>     dict(type='JpegCompression', quality_lower=65, quality_upper=95, p=0.1),
>     dict(
>         type='OneOf',
>         transforms=[
>             dict(type='Blur', blur_limit=3, p=1.0),
>             dict(type='MedianBlur', blur_limit=5, p=1.0),
>         ],
>         p=0.2),
>     dict(
>         type='OneOf',
>         transforms=[
>             dict(type='ElasticTransform', p=1, alpha=120, sigma=120 * 0.05, alpha_affine=120 * 0.03),
>             dict(type='GridDistortion', p=1),
>             dict(type='OpticalDistortion', distort_limit=2, shift_limit=0.5, p=1)
>         ],
>         p=0.2),
>     dict(
>         type='OneOf',
>         transforms=[
>             dict(type='CenterCrop', height = 448, width = 448, p=1),
>             dict(type='CropNonEmptyMaskIfExists', height = 720, width = 720, p=1),
>             dict(type='BBoxSafeRandomCrop', erosion_rate=0.1, p=1),
>         ],
>         p=0.3),
> ]
> 
> train_pipeline = [
>     dict(type='LoadImageFromFile', backend_args=None),
>     dict(
>         type='LoadAnnotations',
>         with_bbox=True,
>         with_mask=True),
>         # poly2mask=True),
>     dict(type='Resize', scale=(900, 720)),
>     dict(
>         type='Albu',
>         transforms=albu_train_transforms,
>         bbox_params=dict(
>             type='BboxParams',
>             format='pascal_voc',
>             label_fields=['gt_bboxes_labels', 'gt_ignore_flags'],
>             min_visibility=0.0,
>             filter_lost_elements=True),
>         keymap={
>             'img': 'image',
>             'gt_masks': 'masks',
>             'gt_bboxes': 'bboxes'
>         },
>         skip_img_without_anno=True),
>     # dict(type='RandomFlip', prob=0.5),
>     dict(type='PackDetInputs', 
>          meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape'))
> ]
>   
> cfg.train_pipeline = train_pipeline

you are so smart,i love you!
