### ISSUE TITLE
os.symlink(src_relpath, tar_path) error

### ISSUE THREAD

**Issue by whffams2** [open-mmlab/mmdetection#8052]
Hello, when i run the **pip install -v -e .** 
The error happend
 OSError: [Errno 95] Operation not supported: '../../tools' -> '/linh/LinH/mmdetection/mmdet/.mim/tools'
ERROR: Command errored out with exit status 1: /root/anaconda3/envs/open-mmlab/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/linh/LinH/mmdetection/setup.py'"'"'; __file__='"'"'/linh/LinH/mmdetection/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
How should i solve this problem.

**Comment by ttt0666** [comment]
same error when I run the pip install -v -e .
OSError: [Errno 95] Operation not supported: '../../tools' -> '/aaa/VMamba-main/mmdetection-main/mmdet/.mim/tools'
error: subprocess-exited-with-error

**Comment by ttt0666** [comment]
my type of filesystem in ubuntu is cifs,which not supports to create symbolic link. What should I do to complete this install.
