### ISSUE TITLE
DETR input queries embedding is zeros_like

### ISSUE THREAD

**Issue by Chop1** [open-mmlab/mmdetection#8053]
in DETR, you make a distinction between input queries and input queries embedding, I dont know why.

Here, the input queries is initialised as a zeros_like vector, while the learned queries embedding is only added to K/Q. To my understanding, the DETR paper do not make the distinction between input queries and queries embedding. The paper state that the learned embedding is initialised as zero, but it refer to the initialization of the embedding to be learned ?

https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/models/utils/transformer.py#L610

**Comment by ZwwWayne** [comment]
This simply follows the official implementation in https://github.com/facebookresearch/detr/blob/master/models/transformer.py#L55.
