### ISSUE TITLE
How to ensemble multiple models in MMCV

### ISSUE THREAD

**Issue by raingstar** [open-mmlab/mmdetection#8056]
Some background related with issue #8055

I am trying to follow the kaggle challenge [sartorius-cell-instance-segmentation](https://www.kaggle.com/competitions/sartorius-cell-instance-segmentation) 1st place solution [Model description](https://www.kaggle.com/competitions/sartorius-cell-instance-segmentation/discussion/298869) and  [Github (using MMCV)](https://github.com/tascj/kaggle-sartorius-cell-instance-segmentation-solution).

The dataset is in coco format, and from [Github (using MMCV)](https://github.com/tascj/kaggle-sartorius-cell-instance-segmentation-solution).  I run data preparation.
```buildoutcfg
mkdir ../data/checkpoints/
python tools/prepare_kaggle.py
```

I summarize the model search as follows:
<img width="820" alt="model" src="https://user-images.githubusercontent.com/21976032/170411043-a6a596b9-3f66-4fc2-9034-d4531de42a5c.png">
The 1st place solution utilizes Yolox as the bbox detecor and swin as the mask detection. In order to learn how to use MMCV, I try to switch Yolox with mask_rcnn  and swin . So I would have three models : model1, model2, model3 to predict the bbox. 
# Question
What's the elegant way to support wbf out of the three predictions by model1-3? In my mind, I could only think about training 3 models separately and making 3 predictions.  I would have to manually combine three outputs into 1, and then feed to the down streaming segmentations.

**Comment by hhaAndroid** [comment]
@raingstar Thank you very much for your detailed description. Is the above process only for the testing process?
