### ISSUE TITLE
There is a problem when adding  args in YOLOX method

### ISSUE THREAD

**Issue by GF1447571253** [open-mmlab/mmdetection#8057]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by GF1447571253** [comment]
I try to add a return argument in _get_target_single(), and then I got a error shows 
ValueError: not enough values to unpack (expected 8, got 6)
here is the return code
![image](https://user-images.githubusercontent.com/23076399/170443541-be032043-f5cf-4241-84e9-89254dd42005.png)
below is the receive code
![image](https://user-images.githubusercontent.com/23076399/170443628-0cff83e5-99d9-46fc-942e-32e1cb2dc8d3.png)
any help would appreciate!

**Comment by RangiLyu** [comment]
When there is no ground truth, the _get_target_single will early-return a set of empty results. You need to modify that line too.
Refer to :
https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/models/dense_heads/yolox_head.py#L449-L456

**Comment by GF1447571253** [comment]
WOW , THANKS！
