### ISSUE TITLE
训练模型时减少内存的使用

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#8062]
您好。我正在使用mmdetection的mask-rcnn训练数据集。当前出现了一些问题。
本人的电脑配置GPU：3070, CPU: i7-10700, 内存：16GB*2 
我采用的数据的图像分辨率为1280*720.在训练集内图像为800张图像时，可以完成训练。但当训练集内图像数量增长到1700张时，在训练生成pth文件时电脑会重重启。我在网上查找了一些资料。猜测最有可能的原因就是内存溢出。
所以有什么办法能够降低训练时对内存的需求吗？（不计较训练速度）

**Comment by RangiLyu** [comment]
Try to reduce the workers_per_gpu in the config.
