### ISSUE TITLE
Getting assertion error while training YOLOACT (or Deformable Detr) with a single class data

### ISSUE THREAD

**Issue by aai-hassan** [open-mmlab/mmdetection#8064]
Hi,

I am getting assertion error while training YOLOX on a single class data. I have modified coco.py code ONLY at line number 25 (https://github.com/open-mmlab/mmdetection/blob/240d7a31c745578aa8c4df54c3074ce78b690c34/mmdet/datasets/coco.py). I changed the CLASSES = ('License plate'). I get the following error:

AssertionError: `CLASSES` in CocoDatasetshould be a tuple of str.Add comma if number of classes is 1 as CLASSES = (License plate,)

The dataset is already in a standard COCO style format. Looking forward for your response. Thank you.

**Comment by BIGWangYuDong** [comment]
Try to use CLASSES = ('License plate', ).

**Comment by aai-hassan** [comment]
@BIGWangYuDong thanks for reaching out. I tried using CLASSES = ('License plate',) but got no luck. However, the error disappears when I add classes=[License plate'] in the config file (of YOLOACT), as found here https://github.com/open-mmlab/mmdetection/issues/8012
