### ISSUE TITLE
TypeError: CocoDataset: __init__() got an unexpected keyword argument 'dataset'

### ISSUE THREAD

**Issue by aai-hassan** [open-mmlab/mmdetection#8069]
Hi, 

While calling 'datasets = [build_dataset(cfg.data.train)]' for the YOLOX 'yolox_x_8x8_300e_coco.py' file, I got the following error:

TypeError: CocoDataset: __init__() got an unexpected keyword argument 'dataset'

Any help shall be appreciated in this regard.

**Comment by hirotosuzuki** [comment]
I met the same error when I use CenterNet.
I can resolve this error by commenting out `RepeatDataset`.
But I'm not sure why `RepeadDataset` can't use...

https://github.com/open-mmlab/mmdetection/blob/master/configs/centernet/centernet_resnet18_dcnv2_140e_coco.py#L97

### before
```python
# Use RepeatDataset to speed up training
data = dict(
    samples_per_gpu=16,
    workers_per_gpu=4,
    train=dict(
        _delete_=True,
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=dataset_type,
            ann_file=data_root + 'annotations/instances_train2017.json',
            img_prefix=data_root + 'train2017/',
            pipeline=train_pipeline)),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))

```
### after
```python
data = dict(
    samples_per_gpu=16,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        ann_file=data_root + "annotations/instances_train2017.json",
        img_prefix=data_root + "train2017/",
        pipeline=train_pipeline,
    ),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline),
)
```

**Comment by shinya7y** [comment]
Duplicate https://github.com/open-mmlab/mmdetection/issues/7050 (for YOLOX)

Pasting the whole config enables for others to debug.
We can print the whole config using [print_config.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/print_config.py).

**Comment by aai-hassan** [comment]
@shinya7y thanks for the reply. Solved from here: https://github.com/open-mmlab/mmdetection/issues/7050#issuecomment-1017587378
