### ISSUE TITLE
SSD 512 - Loss Nan and training stops

### ISSUE THREAD

**Issue by saadyousuf45** [open-mmlab/mmdetection#8072]
**My Config file:**

input_size = 512
model = dict(
    type='SingleStageDetector',
    backbone=dict(
        type='SSDVGG',
        depth=16,
        with_last_pool=False,
        ceil_mode=True,
        out_indices=(3, 4),
        out_feature_indices=(22, 34),
        init_cfg=dict(
            type='Pretrained', checkpoint='open-mmlab://vgg16_caffe')),
    neck=dict(
        type='SSDNeck',
        in_channels=(512, 1024),
        out_channels=(512, 1024, 512, 256, 256, 256, 256),
        level_strides=(2, 2, 2, 2, 1),
        level_paddings=(1, 1, 1, 1, 1),
        l2_norm_scale=20,
        last_kernel_size=4),
    bbox_head=dict(
        type='SSDHead',
        in_channels=(512, 1024, 512, 256, 256, 256, 256),
        num_classes=162,
        anchor_generator=dict(
            type='SSDAnchorGenerator',
            scale_major=False,
            input_size=512,
            basesize_ratio_range=(0.1, 0.9),
            strides=[8, 16, 32, 64, 128, 256, 512],
            ratios=[[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[0.1, 0.1, 0.2, 0.2])),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.0,
            ignore_iof_thr=-1,
            gt_max_assign_all=False),
        smoothl1_beta=1.0,
        allowed_border=-1,
        pos_weight=-1,
        neg_pos_ratio=3,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        nms=dict(type='nms', iou_threshold=0.45),
        min_bbox_size=0,
        score_thr=0.02,
        max_per_img=200))
cudnn_benchmark = True
dataset_type = 'NewDataset'
data_root = 'data/'
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[1, 1, 1], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='Expand',
        mean=[123.675, 116.28, 103.53],
        to_rgb=True,
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(512, 512), keep_ratio=False),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[1, 1, 1],
        to_rgb=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[1, 1, 1],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=3,
    train=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type='NewDataset',
            ann_file='/content/mmdetection/data/train.txt',
            img_prefix=
            '/content/drive/MyDrive/Colab Notebooks/Rad_files/first_1000/',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(
                    type='Expand',
                    mean=[123.675, 116.28, 103.53],
                    to_rgb=True,
                    ratio_range=(1, 4)),
                dict(
                    type='MinIoURandomCrop',
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
                    min_crop_size=0.3),
                dict(type='Resize', img_scale=(512, 512), keep_ratio=False),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(
                    type='PhotoMetricDistortion',
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[1, 1, 1],
                    to_rgb=True),
                dict(type='DefaultFormatBundle'),
                dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
            ])),
    val=dict(
        type='NewDataset',
        ann_file='test.txt',
        img_prefix=
        '/content/drive/MyDrive/Colab Notebooks/Rad_files/first_1000/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        data_root='data/'),
    test=dict(
        type='NewDataset',
        ann_file='train.txt',
        img_prefix=
        '/content/drive/MyDrive/Colab Notebooks/Rad_files/first_1000/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        data_root='data/'))
evaluation = dict(interval=1, metric='mAP')
optimizer = dict(type='SGD', lr=2e-06, momentum=0.7, weight_decay=0.0005)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=2000,
    warmup_ratio=0.1,
    step=[16, 22])
runner = dict(type='EpochBasedRunner', max_epochs=24)
checkpoint_config = dict(interval=1)
log_config = dict(
    interval=50,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
custom_hooks = [
    dict(type='NumClassCheckHook'),
    dict(type='CheckInvalidLossHook', interval=50, priority='VERY_LOW')
]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = '/content/drive/MyDrive/Colab Notebooks/Rad_files/Pre-trained Model Checkpoint/ssd512_coco_20210803_022849-0a47a1ca.pth'
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
auto_scale_lr = dict(enable=False, base_batch_size=64)
work_dir = '/content/drive/MyDrive/Colab Notebooks/Rad_files/model_checkpoints_training_SSD/'
seed = 0
gpu_ids = range(0, 1)

**_My training Problem:_**

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:77: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:79: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
/content/mmdetection/mmdet/datasets/custom.py:180: UserWarning: CustomDataset does not support filtering empty gt images.
  'CustomDataset does not support filtering empty gt images.')
2022-05-27 15:48:03,500 - mmdet - INFO - Automatic scaling of learning rate (LR) has been disabled.
2022-05-27 15:48:03,865 - mmdet - INFO - load checkpoint from local path: /content/drive/MyDrive/Colab Notebooks/Rad_files/Pre-trained Model Checkpoint/ssd512_coco_20210803_022849-0a47a1ca.pth
2022-05-27 15:48:04,051 - mmdet - WARNING - The model and loaded state dict do not match exactly

size mismatch for bbox_head.cls_convs.0.0.weight: copying a param with shape torch.Size([324, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([652, 512, 3, 3]).
size mismatch for bbox_head.cls_convs.0.0.bias: copying a param with shape torch.Size([324]) from checkpoint, the shape in current model is torch.Size([652]).
size mismatch for bbox_head.cls_convs.1.0.weight: copying a param with shape torch.Size([486, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([978, 1024, 3, 3]).
size mismatch for bbox_head.cls_convs.1.0.bias: copying a param with shape torch.Size([486]) from checkpoint, the shape in current model is torch.Size([978]).
size mismatch for bbox_head.cls_convs.2.0.weight: copying a param with shape torch.Size([486, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([978, 512, 3, 3]).
size mismatch for bbox_head.cls_convs.2.0.bias: copying a param with shape torch.Size([486]) from checkpoint, the shape in current model is torch.Size([978]).
size mismatch for bbox_head.cls_convs.3.0.weight: copying a param with shape torch.Size([486, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([978, 256, 3, 3]).
size mismatch for bbox_head.cls_convs.3.0.bias: copying a param with shape torch.Size([486]) from checkpoint, the shape in current model is torch.Size([978]).
size mismatch for bbox_head.cls_convs.4.0.weight: copying a param with shape torch.Size([486, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([978, 256, 3, 3]).
size mismatch for bbox_head.cls_convs.4.0.bias: copying a param with shape torch.Size([486]) from checkpoint, the shape in current model is torch.Size([978]).
size mismatch for bbox_head.cls_convs.5.0.weight: copying a param with shape torch.Size([324, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([652, 256, 3, 3]).
size mismatch for bbox_head.cls_convs.5.0.bias: copying a param with shape torch.Size([324]) from checkpoint, the shape in current model is torch.Size([652]).
size mismatch for bbox_head.cls_convs.6.0.weight: copying a param with shape torch.Size([324, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([652, 256, 3, 3]).
size mismatch for bbox_head.cls_convs.6.0.bias: copying a param with shape torch.Size([324]) from checkpoint, the shape in current model is torch.Size([652]).
2022-05-27 15:48:04,057 - mmdet - INFO - Start running, host: root@120b4fdbb884, work_dir: /content/drive/MyDrive/Colab Notebooks/Rad_files/model_checkpoints_training_SSD
2022-05-27 15:48:04,058 - mmdet - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) NumClassCheckHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
(VERY_LOW    ) CheckInvalidLossHook               
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_val_epoch:
(NORMAL      ) NumClassCheckHook                  
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
2022-05-27 15:48:04,061 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
2022-05-27 15:48:04,064 - mmdet - INFO - Checkpoints will be saved to /content/drive/MyDrive/Colab Notebooks/Rad_files/model_checkpoints_training_SSD by HardDiskBackend.
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:780: UserWarning: Note that order of the arguments: ceil_mode and return_indices will changeto match the args list in nn.MaxPool2d in a future release.
  warnings.warn("Note that order of the arguments: ceil_mode and return_indices will change"
**2022-05-27 15:48:59,590 - mmdet - INFO - Epoch [1][50/4751]	lr: 2.441e-07, eta: 1 day, 11:08:42, time: 1.110, data_time: 0.065, memory: 7974, loss_cls: 24.2810, loss_bbox: 2.3530, loss: 26.6340, grad_norm: 74.6797
2022-05-27 15:49:54,376 - mmdet - INFO - Epoch [1][100/4751]	lr: 2.891e-07, eta: 1 day, 10:54:07, time: 1.096, data_time: 0.012, memory: 7974, loss_cls: 24.0601, loss_bbox: 2.3606, loss: 26.4207, grad_norm: 72.4616
2022-05-27 15:50:50,672 - mmdet - INFO - Epoch [1][150/4751]	lr: 3.341e-07, eta: 1 day, 11:07:45, time: 1.126, data_time: 0.012, memory: 7974, loss_cls: 23.9996, loss_bbox: 2.4082, loss: 26.4078, grad_norm: 68.9765
2022-05-27 15:51:43,668 - mmdet - INFO - Epoch [1][200/4751]	lr: 3.791e-07, eta: 1 day, 10:42:48, time: 1.060, data_time: 0.012, memory: 7974, loss_cls: nan, loss_bbox: nan, loss: nan, grad_norm: nan
2022-05-27 15:51:43,674 - mmdet - INFO - loss become infinite or NaN!**
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-60-53e843aca0b3> in <module>()
     23 cfg.device='cuda'
     24 
---> 25 train_detector(model, datasets, cfg, distributed=False, validate=True)

4 frames
/content/mmdetection/mmdet/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
    242     elif cfg.load_from:
    243         runner.load_checkpoint(cfg.load_from)
--> 244     runner.run(data_loaders, cfg.workflow)

/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py in run(self, data_loaders, workflow, max_epochs, **kwargs)
    125                     if mode == 'train' and self.epoch >= self._max_epochs:
    126                         break
--> 127                     epoch_runner(data_loaders[i], **kwargs)
    128 
    129         time.sleep(1)  # wait for some hooks like loggers to finish

/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py in train(self, data_loader, **kwargs)
     49             self.call_hook('before_train_iter')
     50             self.run_iter(data_batch, train_mode=True, **kwargs)
---> 51             self.call_hook('after_train_iter')
     52             self._iter += 1
     53 

/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py in call_hook(self, fn_name)
    307         """
    308         for hook in self._hooks:
--> 309             getattr(hook, fn_name)(self)
    310 
    311     def get_hook_info(self):

/content/mmdetection/mmdet/core/hook/checkloss_hook.py in after_train_iter(self, runner)
     22         if self.every_n_iters(runner, self.interval):
     23             assert torch.isfinite(runner.outputs['loss']), \
---> 24                 runner.logger.info('loss become infinite or NaN!')

AssertionError: None

Guidance would be really appreciated.

**Comment by saadyousuf45** [comment]
Is there a way to keep the training active and bypass this error? because I have noticed that the loss will return after some epochs.

**Comment by chhluo** [comment]
For loss goes Nan, see https://mmdetection.readthedocs.io/en/latest/faq.html

**Comment by saadyousuf45** [comment]
How would I do this??
Any code to filter them out.?

**Comment by saadyousuf45** [comment]
Check if the dataset annotations are valid: zero-size bounding boxes will cause the regression loss to be Nan due to the commonly used transformation for box regression. Some small size (width or height are smaller than 1) boxes will also cause this problem after data augmentation (e.g., instaboost). So check the data and try to filter out those zero-size boxes and skip some risky augmentations on the small-size boxes when you face the problem.


How can I do this?

**Comment by chhluo** [comment]
load the dataset and check whether the gt_bboxes is valid

```python
from mmcv.utils import Config

from mmdet.datasets import build_dataset

# replace path of config file with yours
cfg_path = "configs/fcos/fcos_center_r50_caffe_fpn_gn-head_1x_coco.py"
cfg = Config.fromfile(cfg_path)
dataset = build_dataset(cfg.data.train)

for x in dataset:
    print(x['gt_bboxes'])
```
