### ISSUE TITLE
Training failed after increasing the number of images in the dataset

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#8073]
Hardware gpu:3070 cpu:i7-10700 memory:96gb power supply: 750W

The image resolution in my dataset is 1280*720 Previously, it worked well when there were 850 images in the dataset. When the number of images in the dataset is increased to 1900, an error will occur in the training. You can see that you can train normally at the beginning, but the Ubuntu system will restart immediately when the PTH file (the first one) is generated. Why?

**Comment by chhluo** [comment]
Could you please provide any other information about this error?

**Comment by isyangshu** [comment]
I guess the memory is out of bounds, use htop to monitor the memory.
