### ISSUE TITLE
No training info in log.json

### ISSUE THREAD

**Issue by miscal** [open-mmlab/mmdetection#8075]
Hello, I was traning the model in this repo (https://github.com/ViTAE-Transformer/ViTDet) with a customized dataset. The log.json file I got looks like this:
`{"mode": "val", "epoch": 1, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 2, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 3, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 4, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 5, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 6, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 7, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 8, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 9, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 10, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 11, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 12, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 13, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 14, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 15, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 16, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 17, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 18, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 19, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 20, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 21, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 22, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 23, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 24, "iter": 890, "lr": 0.0}
{"mode": "val", "epoch": 25, "iter": 890, "lr": 0.0}`

So how can I output training losses like `{"mode": "train", "epoch": 1, "iter": 50, "lr": 0.0, "memory": { }, "loss_rpn_cls": { }, "loss_rpn_bbox": { } ...}` into my log.json file?

By the way, I got this error while evaluating: `- mmdet - ERROR - The testing results of the whole dataset is empty.` So maybe my model is simply not trained?

I'm new to this framework. Can anyone give me some help?

**Comment by chhluo** [comment]
Yes, your model was not trained, this problem may be caused by the dataset. Please check your customized dataset, whether the loaded data is valid, whether you convert the dataset currectly?

**Comment by miscal** [comment]
> Yes, your model was not trained, this problem may be caused by the dataset. Please check your customized dataset, whether the loaded data is valid, whether you convert the dataset currectly?
> 
> And there is script to browse dataset (replace path of config file with yours) python tools/misc/browse_dataset.py configs/retinanet/retinanet_r18_fpn_1x_coco.py --output-dir ./show


Thanks for the quick reply. 
My num_classes parameter didn't match with the number of classes in my customized dataset. After I fixed it everything's fine.
