### ISSUE TITLE
how to feed tensors (with shape of [NCHW]) to the detectors of MMdetection?

### ISSUE THREAD

**Issue by zhangyu13a** [open-mmlab/mmdetection#8079]
Generally,  users are allowed to enter to a path of images to _**inference_detector(model, img_path)**_, where the path are packaged into a dict of **Data_Containers** by **_test_pipeline(XXX)_** (one Data_Containers is about 'img_metas' and another is 'img').
However, I have to deal with the image tensors firstly with pytorch and  it is quite difficult to feed  image tensors with shape of [N,C,H,W] to detectors directly.  So I wonder how to solve this problem?

**Comment by ZwwWayne** [comment]
In this case, you need to pad the images manually and form them as a batch. We will have better solution in the future
