### ISSUE TITLE
Why DyHead in neck?

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#8080]
```python
    neck=[
        dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            start_level=1,
            add_extra_convs='on_output',
            num_outs=5),
        dict(type='DyHead', in_channels=256, out_channels=256, num_blocks=6)
    ]
```

**Comment by shinya7y** [comment]
Papers and official implementations do not necessarily adopt the same components classification (backbone, neck, dense head, ...) as MMDetection. In fact, DyHead doesn't use the term `neck`, the paper considers DyHead as a head, and the official implementation [includes DyHead in backbones](https://github.com/microsoft/DynamicHead/blob/master/extra/resnet.py).
Thus, we need to consider where to reimplement DyHead in MMDetection based on its function and usability.

DyHead is a plugin module between FPN and other heads (please see Figure 1 and "We evaluate the generalization ability of the dynamic head by plugging it to popular object detectors, such as FasterRCNN [23], RetinaNet [16], ATSS [35], FCOS [28], and RepPoints [33]." in the [DyHead paper](https://arxiv.org/abs/2106.08322)). The whole architecture is `backbone -> FPN -> DyHead -> head (e.g., ATSS)`.
By implementing DyHead as a neck, we can use it with various other heads by just editing configs.
If we implemented DyHead as a head, we would have to implement many combined heads (e.g., `RetinaHead+DyHead`, `ATSSHead+DyHead`, `FCOSHead+DyHead`, ...).
