### ISSUE TITLE
How to visualize TOOD Figure 1?

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmdetection#8084]
![image](https://user-images.githubusercontent.com/69593462/170917763-04d9539f-8aca-4621-8ee7-4dc18108d5fc.png)
TOODHead doesn't have a IoU branch, how can I visualize the IoU heat map like that

**Comment by Czm369** [comment]
Visual heatmaps are not yet supported.

**Comment by iumyx2612** [comment]
> Visual heatmaps are not yet supported.

Can you guide me to produce the image above from TOOD?
