### ISSUE TITLE
do you support googles objectrons data format?

### ISSUE THREAD

**Issue by sivaguru-pat** [open-mmlab/mmdetection#8087]
hey

i went through this repo https://github.com/google-research-datasets/Objectron looks interesting, do you support 3d object detection in 2d image?

**Comment by Czm369** [comment]
There are currently no plans to support the dataset.

**Comment by ZwwWayne** [comment]
> hey
> 
> i went through this repo https://github.com/google-research-datasets/Objectron looks interesting, do you support 3d object detection in 2d image?

Please refer to mmdetection3d
