### ISSUE TITLE
results.json to results.pkl  ?

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#8093]
Hi, @ZwwWayne @hhaAndroid 

Thanks for your effort and contribution.

I tested my datasets and saved all the json files with `--format-only`. Now I want to transfer these results from json format into pkl format, just like the `--out` command.

How could I achieve that? Due to the large amount of test dataset, I do not want to run test command again to obtain the pkl file.

**Comment by hhaAndroid** [comment]
@mitming Sorry, no conversion script is provided at the moment.

**Comment by mitming** [comment]
> @mitming Sorry, no conversion script is provided at the moment.

Thanks a lot
