### ISSUE TITLE
[Feature Suggestion] Refactor `datasets.samplers` to use registry

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmdetection#8094]
**Describe the feature**
How about adding the feature `build_dataset_sampler`

**Motivation**
`samplers` for datasets are becoming diverse and complicated.
It makes the logic of `build_dataloader` messy.

So how about refactoring `samplers` modules to use `build_dataset_sampler`?

**Comment by hhaAndroid** [comment]
@nijkah  Thank you very much for your suggestion, we are already refactoring and expect to release it next month.
