### ISSUE TITLE
Visualizing the wrong predictions only

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#8096]
Hi, @hhaAndroid 

For some bad cases, maybe visualizing the wrong predictions only, instead of visualizing all the predictions can help us to analyze the reasons better.

Is there any code to implement this function? If not, how can I achieve this more elegantly?

**Comment by hhaAndroid** [comment]
@mitming You can try https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/analyze_results.py

**Comment by mitming** [comment]
> @mitming You can try https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/analyze_results.py

Got it, thanks for your reply
