### ISSUE TITLE
New strong baseline for RetinaNet and Cascade-RCNN

### ISSUE THREAD

**Issue by zhtmike** [open-mmlab/mmdetection#8097]
**Describe the feature**

Based on the paper [Simple Training Strategies and Model Scaling for Object Detection](https://arxiv.org/pdf/2107.00057v1.pdf), by adding SE-block, SiLU activation function, strong scale jittering, etc. , RetinaNet has a 7.7% AP improvement, which is significant.
The change should be minimal, and I am wondering if anyone is interested in implementing this paper.

**Comment by hhaAndroid** [comment]
@zhtmike Thank you very much for your feedback, are you interested in creating a PR ?

**Comment by zhtmike** [comment]
@hhaAndroid  I hope I can but currently my GPU resources is very limited. It would be nice if anyone can help to implement it. If not, I may create a PR in future.

**Comment by hhaAndroid** [comment]
@zhtmike OK
