### ISSUE TITLE
How to add a custom module in the backhone (for example, in 'resnet50')?

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [open-mmlab/mmdetection#8099]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
1. The bug is reported as "RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. ..."  only when distributed training.
2. **I know that set the 'find_unused_parameters = True' can solve the problem, but I am really confused about why there is such a problem. I just added a very simple module.**
3. It seems that I added the module by mistake, but I don't know how to modify it.

**Reproduction**

1. What command or script did you run?

```
CUDA_VISIBLE_DEVICES=2 ./tools/dist_train.sh configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py 1
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes. I only modified the 'mmdet/models/backbones/resnet.py'. The modification is adding a new class "edge_attention".
![image](https://user-images.githubusercontent.com/26215859/171184705-5c1c6c14-a1f6-4a16-8ff8-b1b51a26adfa.png)

![image](https://user-images.githubusercontent.com/26215859/171184841-dd4b1651-0e90-463f-bf44-be3d69a69869.png)
![image](https://user-images.githubusercontent.com/26215859/171184932-cbca98af-7656-482f-bbe5-7d35077f87fc.png)

3. What dataset did you use?
COCO

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
![image](https://user-images.githubusercontent.com/26215859/171186338-a55f3b81-d052-4560-a2d0-c99860d45837.png)

```RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indica
tes that your module has parameters that were not used in producing loss. You can enable unused parameter detection b
y (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2)
making sure all `forward` function outputs participate in calculating loss. If you already have done the above two st
eps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your m
odule's `forward` function. Please include the loss function and the structure of the return value of `forward` of yo
ur module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last)
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@Ixiaohuihuihui The bias parameter of the edge module is wrong, you should inputs in True instead of 1

**Comment by Ixiaohuihuihui** [comment]
Hi, I don't think the key is the bias parameter. When I set bias=false, there will still be related problems. In addition, the code can run without distributed training.  And I find when I use the output of edge module, it can work. But if I only add the output to the final outputs, it fails.
![image](https://user-images.githubusercontent.com/26215859/171547815-ae219ab8-c44f-46fc-a9f3-92f7e35bff32.png)
![image](https://user-images.githubusercontent.com/26215859/171547928-387f9aac-9c0f-4deb-9b6a-ef8044994f71.png)

**Comment by Ixiaohuihuihui** [comment]
It seems that I must use the output of edge module, instead of simply appending it to the output value.🤣🤣🤣

**Comment by Ixiaohuihuihui** [comment]
Hi, I found the key to the bug and solved it. This problem must be caused by output not participating in loss calculation. In my problem, the edge module is only calculateed on the C1 stage of FPN. But in the neck head, we use the C2-C4 stages. Thus the output of edge moudle didn't used in producing loss.

![image](https://user-images.githubusercontent.com/26215859/171604796-29429905-2f27-452c-9c56-d5474a3ab9f5.png)

Hope it can be helpful to solve this problem in the future.
