### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'assigner'

### ISSUE THREAD

**Issue by Kongsea** [open-mmlab/mmdetection#81]
When I train a FasterRCNN using my own custom dataset, it raised the following error:

> 2018-10-26 16:21:43,169 - INFO - Start running, host: kong@Kong, work_dir: /home/kong/mmdetection/work_dirs/faster_rcnn_r101_fpn_1x
> 2018-10-26 16:21:43,169 - INFO - workflow: [('train', 1)], max: 12 epochs
> Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7ff3ecaed9b0>>
> Traceback (most recent call last):
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
>     self._shutdown_workers()
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
>     self.worker_result_queue.get()
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/multiprocessing/queues.py", line 344, in get
>     return _ForkingPickler.loads(res)
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
>     fd = df.detach()
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
>     return reduction.recv_handle(conn)
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
>     return recvfds(s, 1)[0]
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/multiprocessing/reduction.py", line 153, in recvfds
>     msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))
> ConnectionResetError: [Errno 104] Connection reset by peer
> Traceback (most recent call last):
>   File "tools/train.py", line 81, in <module>
>     main()
>   File "tools/train.py", line 77, in main
>     logger=logger)
>   File "/home/kong/mmdetection/mmdet/apis/train.py", line 59, in train_detector
>     _non_dist_train(model, dataset, cfg, validate=validate)
>   File "/home/kong/mmdetection/mmdet/apis/train.py", line 117, in _non_dist_train
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/4T/kong/data/mmcv/mmcv/runner/runner.py", line 349, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/4T/kong/data/mmcv/mmcv/runner/runner.py", line 255, in train
>     self.model, data_batch, train_mode=True, **kwargs)
>   File "/home/kong/mmdetection/mmdet/apis/train.py", line 37, in batch_processor
>     losses = model(**data)
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/kong/anaconda/envs/pt341/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/kong/mmdetection/mmdet/models/detectors/base.py", line 79, in forward
>     return self.forward_train(img, img_meta, **kwargs)
>   File "/home/kong/mmdetection/mmdet/models/detectors/two_stage.py", line 95, in forward_train
>     rpn_losses = self.rpn_head.loss(*rpn_loss_inputs)
>   File "/home/kong/mmdetection/mmdet/models/rpn_heads/rpn_head.py", line 159, in loss
>     self.target_means, self.target_stds, cfg)
>   File "/home/kong/mmdetection/mmdet/core/anchor/anchor_target.py", line 41, in anchor_target
>     img_metas, means_replicas, stds_replicas, cfg_replicas)
>   File "/home/kong/mmdetection/mmdet/core/utils/misc.py", line 24, in multi_apply
>     return tuple(map(list, zip(*map_results)))
>   File "/home/kong/mmdetection/mmdet/core/anchor/anchor_target.py", line 83, in anchor_target_single
>     _, sampling_result = assign_and_sample(anchors, gt_bboxes, None, None, cfg)
>   File "/home/kong/mmdetection/mmdet/core/bbox/sampling.py", line 25, in assign_and_sample
>     bbox_assigner = BBoxAssigner(**cfg.assigner)
>   File "/4T/kong/data/mmcv/mmcv/utils/config.py", line 27, in __getattr__
>     raise ex
> AttributeError: 'ConfigDict' object has no attribute 'assigner'

Please give me some advice to fix it. Thanks.

**Comment by hellock** [comment]
What is the config file you used? It seems that there is a missing key `assigner` in training configs.

**Comment by Kongsea** [comment]
This is my config:

> # model settings
> model = dict(
>     type='FasterRCNN',
>     pretrained='modelzoo://resnet101',
>     backbone=dict(
>         type='ResNet',
>         depth=101,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         style='pytorch'),
>     neck=dict(
>         type='FPN',
>         in_channels=[256, 512, 1024, 2048],
>         out_channels=256,
>         num_outs=5),
>     rpn_head=dict(
>         type='RPNHead',
>         in_channels=256,
>         feat_channels=256,
>         anchor_scales=[8],
>         anchor_ratios=[0.5, 1.0, 2.0],
>         anchor_strides=[4, 8, 16, 32, 64],
>         target_means=[.0, .0, .0, .0],
>         target_stds=[1.0, 1.0, 1.0, 1.0],
>         use_sigmoid_cls=True),
>     bbox_roi_extractor=dict(
>         type='SingleRoIExtractor',
>         roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
>         out_channels=256,
>         featmap_strides=[4, 8, 16, 32]),
>     bbox_head=dict(
>         type='SharedFCBBoxHead',
>         num_fcs=2,
>         in_channels=256,
>         fc_out_channels=1024,
>         roi_feat_size=7,
>         num_classes=141,
>         target_means=[0., 0., 0., 0.],
>         target_stds=[0.1, 0.1, 0.2, 0.2],
>         reg_class_agnostic=False))
> # model training and testing settings
> train_cfg = dict(
>     rpn=dict(
>         pos_fraction=0.5,
>         pos_balance_sampling=False,
>         neg_pos_ub=256,
>         allowed_border=0,
>         crowd_thr=1.1,
>         anchor_batch_size=256,
>         pos_iou_thr=0.7,
>         neg_iou_thr=0.3,
>         neg_balance_thr=0,
>         min_pos_iou=0.3,
>         pos_weight=-1,
>         smoothl1_beta=1 / 9.0,
>         debug=False),
>     rcnn=dict(
>         pos_iou_thr=0.5,
>         neg_iou_thr=0.5,
>         crowd_thr=1.1,
>         roi_batch_size=512,
>         add_gt_as_proposals=True,
>         pos_fraction=0.25,
>         pos_balance_sampling=False,
>         neg_pos_ub=512,
>         neg_balance_thr=0,
>         min_pos_iou=0.5,
>         pos_weight=-1,
>         debug=False))
> test_cfg = dict(
>     rpn=dict(
>         nms_across_levels=False,
>         nms_pre=2000,
>         nms_post=2000,
>         max_num=2000,
>         nms_thr=0.7,
>         min_bbox_size=0),
>     rcnn=dict(score_thr=0.05, max_per_img=100, nms_thr=0.5))
> # dataset settings
> dataset_type = 'MaDataset'
> data_root = 'data/ma/'
> img_norm_cfg = dict(
>     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> data = dict(
>     imgs_per_gpu=2,
>     workers_per_gpu=2,
>     train=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/train.json',
>         img_prefix=data_root + 'images/',
>         img_scale=(800,),
>         img_norm_cfg=img_norm_cfg,
>         size_divisor=32,
>         flip_ratio=0.5,
>         with_mask=False,
>         with_crowd=True,
>         with_label=True),
>     val=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/test.json',
>         img_prefix=data_root + 'images/',
>         img_scale=(1080, 800),
>         img_norm_cfg=img_norm_cfg,
>         size_divisor=32,
>         flip_ratio=0,
>         with_mask=False,
>         with_crowd=True,
>         with_label=True),
>     test=dict(
>         type=dataset_type,
>         ann_file=data_root + 'annotations/test.json',
>         img_prefix=data_root + 'images/',
>         img_scale=(1080, 800),
>         img_norm_cfg=img_norm_cfg,
>         size_divisor=32,
>         flip_ratio=0,
>         with_mask=False,
>         with_label=False,
>         test_mode=True))
> # optimizer
> optimizer = dict(type='SGD', lr=0.00125, momentum=0.9, weight_decay=0.0001)
> optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
> # learning policy
> lr_config = dict(
>     policy='step',
>     warmup='linear',
>     warmup_iters=500,
>     warmup_ratio=1.0 / 3,
>     step=[8, 11])
> checkpoint_config = dict(interval=1)
> # yapf:disable
> log_config = dict(
>     interval=50,
>     hooks=[
>         dict(type='TextLoggerHook'),
>         # dict(type='TensorboardLoggerHook')
>     ])
> # yapf:enable
> # runtime settings
> total_epochs = 12
> dist_params = dict(backend='nccl')
> log_level = 'INFO'
> work_dir = './work_dirs/ma_faster_rcnn_r101_fpn_1x'
> load_from = None
> resume_from = None
> workflow = [('train', 1)]

Please take a look. Thank you @hellock .

**Comment by Kongsea** [comment]
As you said, it seems the config indeed missed this key. I wrote the config through modifing an old version config file.

**Comment by neomukul** [comment]
how you solved this error, I tried different config file but still getting the error.

**Comment by addicter2017** [comment]
Could you tell us how didi you switch to the new config file?
