### ISSUE TITLE
Adaptive Feature Pooling for PANet

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#8102]
Hi! Will like to check if [Adaptive Feature Pooling](https://paperswithcode.com/method/adaptive-feature-pooling#:~:text=Adaptive%20Feature%20Pooling%20pools%20features,feature%20grids%20from%20each%20level.) is implemented for PANet? I can't seem to find it within mmdet/models/necks/pafpn.py, it seems to only return a list of features (N2 to N5).

**Comment by jbwang1997** [comment]
For now, there is only PAfpn in mmdetection.
