### ISSUE TITLE
bbox_mAP_s: -1.0000

### ISSUE THREAD

**Issue by champagne-yellow** [open-mmlab/mmdetection#8106]
On my own dataset, the bbox_mAP_s is -1.0000 regardless of the method.

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/faq.md#evaluation

**Comment by JUSTM0VE0N** [comment]
> On my own dataset, the bbox_mAP_s is -1.0000 regardless of the method.

I also ran into this issue, if you solve it please reply to me, my email is isliuch@126.com
