### ISSUE TITLE
HOW to froze a special stage？

### ISSUE THREAD

**Issue by FarranYang** [open-mmlab/mmdetection#8107]
**https://zhuanlan.zhihu.com/p/473707171 In this link, you guys show how to froze the stage.**

![image](https://user-images.githubusercontent.com/71055115/171355560-6954b61e-56cc-4571-8078-2906ccf775a0.png)

I want to kown how to set requires_grad as False and change to  eval  model . **could you give a example like froze the rpn head in faster_RCNN?which file should I change ?**

I want to froze the stage0 in cascadeRPN。

**Comment by jbwang1997** [comment]
In this case, you can directly set `paramwise_cfg` in your config. set dict(lr_mult=0.1) to the parameters you want to freeze.

example:
```
optimizer = dict( 
    _delete_=True, 
    type='AdamW', 
    lr=0.0001, 
    betas=(0.9, 0.999), 
    weight_decay=0.05, 
    paramwise_cfg=dict( 
        custom_keys={ 
            'rpn_head.0': dict(decay_mult=0.)
        })) 
```

**Comment by FarranYang** [comment]
Thank you very much!
