### ISSUE TITLE
How to interpret the test results?

### ISSUE THREAD

**Issue by aai-hassan** [open-mmlab/mmdetection#8109]
Hi, 

While evaluating my object detector trained on a single-class using YOLOX-x architecture, I get the following test results (attached). The question is:
1. what is maxDets=100, 300, 100?
2. How do area = all, small, medium, and large correlate to the maxDets?
3. Assuming a multi-class dataset, can I calculate average precision and recall for each individual class?
![Screenshot from 2022-06-01 15-43-03](https://user-images.githubusercontent.com/75657788/171386690-243a2d33-2e06-4d05-bca4-bb3d6f30db3d.png)

**Comment by jbwang1997** [comment]
For classwise results, you can set `classwise=True` at https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L597.
