### ISSUE TITLE
Issue in `init_weights` for SwinTransformer Backbone 

### ISSUE THREAD

**Issue by PeterQiu0516** [open-mmlab/mmdetection#8112]
**Describe the bug**

Here `self.init_cfg` is supposed to be a `dict()` and it has no attribute `checkpoint`.
https://github.com/open-mmlab/mmdetection/blob/bd460fe48ebc6fc33abd3d99acdae7e50a9305c0/mmdet/models/backbones/swin.py#L690

**Reproduction**

1. What command or script did you run?

```none
import torch
import torch.nn.functional as F
from mmdet.models.backbones.swin import SwinTransformer

pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'
model = SwinTransformer(
                embed_dims=96,
                depths=(2, 2, 6, 2),
                convert_weights=True,
                init_cfg=dict(
                    type='Pretrained',
                    checkpoint=pretrained))
model.init_weights()
```

**Error traceback**
If applicable, paste the error trackback here.

```none
Exception has occurred: AttributeError       (note: full exception trace is shown but execution is paused at: <module>)
'dict' object has no attribute 'checkpoint'
```

**Comment by jbwang1997** [comment]
Usually, the model's arguments come from cfg loaded from .py file. The type usually is a ConfigDict defined at https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/config.py#L35. ConfigDict can use cfg.key finding value, but the original dictionary cannot.

**Comment by PeterQiu0516** [comment]
Thank you for your feedbacks!
