### ISSUE TITLE
How to get predictions as raw tensors from inference_detector()

### ISSUE THREAD

**Issue by FHarhammer** [open-mmlab/mmdetection#8113]
I'm trying to get the results of inference_detector() as raw tensors on the gpu (so without copying them on the cpu)
I want to do some more postprocessing to the instance masks on the gpu before copying them to the cpu. Is this somehow possible?

**Comment by jbwang1997** [comment]
inference_detector() get the results on CPU from the model. If you want to do other operations, you can modify the code in simple_test of model head.
