### ISSUE TITLE
SOLOv2 models are missing

### ISSUE THREAD

**Issue by hysts** [open-mmlab/mmdetection#8114]
There are links to models and logs in the [SOLOv2 README.md](https://github.com/open-mmlab/mmdetection/blob/v2.25.0/configs/solov2/README.md) and [metafile.yml](https://github.com/open-mmlab/mmdetection/blob/v2.25.0/configs/solov2/metafile.yml), but it seems they are missing. I get 404 Not Found error.

**Comment by jbwang1997** [comment]
Hello, thank you for pointing it out. We have uploaded the solov2 pretrain models. Now the link is correct.

**Comment by hysts** [comment]
Thanks a lot!

**Comment by DoubleChuang** [comment]
Hi @jbwang1997  ,
[SOLOv2 light R34 ](https://github.com/open-mmlab/mmdetection/blob/master/configs/solov2/metafile.yml#L106)pre-trained model is missing, could you correct it? 
Thank you
