### ISSUE TITLE
conversion from epoch based runner to iteration based

### ISSUE THREAD

**Issue by iuliaalda** [open-mmlab/mmdetection#8121]
hello! 
i wanted to modify the runner type from epoch based to iteration and my question is, is there any conversion formula that i must respect when setting the maximum number of iterations (and the lr step)? for example, if i initially had 10 epochs, i need 10*len(dataset) iterations? 
i've seen config files with 90k iterations on coco and that seemed quite little to me. thank you!

**Comment by RangiLyu** [comment]
iteration = epoch * len(dataset) / batch_size

**Comment by iuliaalda** [comment]
thanks!
