### ISSUE TITLE
Verification of installation fails - KeyError: 'Cascade Mask R-CNN'

### ISSUE THREAD

**Issue by pgaston** [open-mmlab/mmdetection#8122]
Followed installation instructions/Best Practices -https://mmdetection.readthedocs.io/en/stable/get_started.html

On Verify your Installation - the 'mim download mmdet ...' command failed, with the following:

(openmmlab) pg@pg-MS-7A59:~/repos/mmdetection$ mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .
/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/pg/miniconda3/envs/openmmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 43, in cli
    download(package, configs, dest_root)
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 74, in download
    model_info = get_model_info(
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/search.py", line 169, in get_model_info
    dataframe = convert2df(metadata)
  File "/home/pg/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/search.py", line 392, in convert2df
    for key, value in name2collection[collection_name].items():
KeyError: 'Cascade Mask R-CNN'

**Comment by bulingda** [comment]
Have you found a solution? I had a similar problem.

**Comment by Hezhexi2002** [comment]
same to you,here is my figure:
![image](https://user-images.githubusercontent.com/53631206/172598311-4a0711d5-766c-410c-a6b6-b9148170cd45.png)

**Comment by bulingda** [comment]
> same to you,here is my figure: ![image](https://user-images.githubusercontent.com/53631206/172598311-4a0711d5-766c-410c-a6b6-b9148170cd45.png)

One lower version would be fine

**Comment by Hezhexi2002** [comment]
> > same to you,here is my figure: ![image](https://user-images.githubusercontent.com/53631206/172598311-4a0711d5-766c-410c-a6b6-b9148170cd45.png)
> 
> One lower version would be fine

the version of what?

**Comment by bulingda** [comment]
> > > same to you,here is my figure: ![image](https://user-images.githubusercontent.com/53631206/172598311-4a0711d5-766c-410c-a6b6-b9148170cd45.png)
> > 
> > 
> > One lower version would be fine
> 
> the version of what?

mmdetection

**Comment by Hezhexi2002** [comment]
> > > > same to you,here is my figure: ![image](https://user-images.githubusercontent.com/53631206/172598311-4a0711d5-766c-410c-a6b6-b9148170cd45.png)
> > > 
> > > 
> > > One lower version would be fine
> > 
> > 
> > the version of what?
> 
> mmdetection

But I install the mmdetection from source using these commands:
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -v -e .
# "-v" means verbose, or more output
# "-e" means installing a project in editable mode,
# thus any local modifications made to the code will take effect without reinstallation.
what should I do to install a lower version?

**Comment by bulingda** [comment]
> > > > > same to you,here is my figure: ![image](https://user-images.githubusercontent.com/53631206/172598311-4a0711d5-766c-410c-a6b6-b9148170cd45.png)
> > > > 
> > > > 
> > > > One lower version would be fine
> > > 
> > > 
> > > the version of what?
> > 
> > 
> > mmdetection
> 
> But I install the mmdetection from source using these commands: git clone https://github.com/open-mmlab/mmdetection.git cd mmdetection pip install -v -e .
> 
> # "-v" means verbose, or more output
> # "-e" means installing a project in editable mode,
> # thus any local modifications made to the code will take effect without reinstallation.
> what should I do to install a lower version?

I'm not sure. I downloaded the zip package to install it.

**Comment by Hezhexi2002** [comment]
> > > > > > same to you,here is my figure: ![image](https://user-images.githubusercontent.com/53631206/172598311-4a0711d5-766c-410c-a6b6-b9148170cd45.png)
> > > > > 
> > > > > 
> > > > > One lower version would be fine
> > > > 
> > > > 
> > > > the version of what?
> > > 
> > > 
> > > mmdetection
> > 
> > 
> > But I install the mmdetection from source using these commands: git clone https://github.com/open-mmlab/mmdetection.git cd mmdetection pip install -v -e .
> > # "-v" means verbose, or more output
> > # "-e" means installing a project in editable mode,
> > # thus any local modifications made to the code will take effect without reinstallation.
> > what should I do to install a lower version?
> 
> I'm not sure. I downloaded the zip package to install it.

I searched the error on bing and found a solution，here is the link:https://blog.csdn.net/suiyingy/article/details/125097873
but after I done that,it threw another error like this：
![image](https://user-images.githubusercontent.com/53631206/172601742-0f7eeeba-3cae-484d-87bb-ecc7112aec1c.png)

**Comment by Hezhexi2002** [comment]
I have solved that error by installing opencv-python:
![image](https://user-images.githubusercontent.com/53631206/172602688-18400a00-8ab0-40bb-ac51-eab88f8e7488.png)
However,I'm so confused why the mmcv-full doesn't have opencv-python installed before，that's so wired!

**Comment by MathijsNL** [comment]
For me the problem persists even with opencv installed

**Comment by ByeByeBaByBlue1999** [comment]
Error message:
```
File "/opt/conda/envs/mmdetection/lib/python3.6/site-packages/mim/commands/search.py", line 396, in convert2df
    for key, value in name2collection[collection_name].items():
KeyError: 'Cascade Mask R-CNN'
```
I solved the Problem by changing line 396 of file
'/opt/conda/envs/mmdetection/lib/python3.6/site-packages/mim/commands/search.py'.

From
```
if collection_name:
            model_info['model'] = cast2lowercase(collection_name)
            for key, value in name2collection[collection_name].items():
                model_info.setdefault(key, value)
```
To
```
if collection_name and collection_name in name2collection.keys():
            model_info['model'] = cast2lowercase(collection_name)
            for key, value in name2collection[collection_name].items():
                model_info.setdefault(key, value)
```
The idea is from https://blog.csdn.net/suiyingy/article/details/125097873 
My mmdetection version is 2.25.0.

**Comment by ice-tong** [comment]
related issues in mim: https://github.com/open-mmlab/mim/issues/125

**Comment by ZwwWayne** [comment]
Fixed in https://github.com/open-mmlab/mmdetection/pull/8240

**Comment by jingzhang0909** [comment]
> Fixed in #8240

[github/workflows/test_mim.yml](https://github.com/open-mmlab/mmdetection/pull/8240/files/0f00fa5b047dd34870ae8aae2224e2b0ef9838fa#diff-bc11cdc37aa8cbb5ce8da62c0cfe2884c269327875c55db4415c004bdb7f6e8f)
could you tell me this file's position? why I cannot find it

**Comment by WentingDu** [comment]
You can try this way introduces by the blog --- [https://blog.csdn.net/suiyingy/article/details/125097873](url) :

1. Run this command `mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .` And the error  **KeyError: 'Cascade Mask R-CNN'** will present. 
2. Then the terminal will point you the error's location :  

> File "/home/dwt/anaconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/search.py", line 401, in convert2df
>     for key, value in name2collection[collection_name].items():

3. So we find the file **"/home/dwt/anaconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/search.py"** and find the line 399 , and place the code` if collection_name:` by `if collection_name and collection_name in name2collection.keys():` . 
4. Rerun the command `mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .` And the error will not happen again.

**Comment by Zhuzi24** [comment]
> You can try this way introduces by the blog --- [https://blog.csdn.net/suiyingy/article/details/125097873](url) :
> 
> 1. Run this command `mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .` And the error  **KeyError: 'Cascade Mask R-CNN'** will present.
> 2. Then the terminal will point you the error's location :
> 
> > File "/home/dwt/anaconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/search.py", line 401, in convert2df
> > for key, value in name2collection[collection_name].items():
> 
> 3. So we find the file **"/home/dwt/anaconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/search.py"** and find the line 399 , and place the code` if collection_name:` by `if collection_name and collection_name in name2collection.keys():` .
> 4. Rerun the command `mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .` And the error will not happen again.

Thanks，it has worked.
