### ISSUE TITLE
DCN_v2 implementation question

### ISSUE THREAD

**Issue by anshkumar** [open-mmlab/mmdetection#8126]
Hi,
I was going through the DCN code [here](https://github.com/open-mmlab/mmdetection/blob/3c021b1167095767c7be32d3007b57ed71753f80/mmdet/ops/dcn/src/cuda/deform_conv_cuda_kernel.cu).
I've two questions in this:
1) In the [line](https://github.com/open-mmlab/mmdetection/blob/3c021b1167095767c7be32d3007b57ed71753f80/mmdet/ops/dcn/src/cuda/deform_conv_cuda_kernel.cu#L594), it is written that
```
const int h_in = h_col * stride_h - pad_h;
const int w_in = w_col * stride_w - pad_w;
``` 
I guess this comes from the formula relating input to the output after convolution `[h_col,w_col] = [floor((h_in + 2*pad_h - kernel_h)/stride_h + 1), floor((w_in + 2*pad_w - kernel_w)/stride_w + 1)]`, assuming `(h_in + pad_h)` is divisible by `stride_h` and dilation=1. So, my question is, why is the dilation was considered as 1 ?

2) In the [line](https://github.com/open-mmlab/mmdetection/blob/3c021b1167095767c7be32d3007b57ed71753f80/mmdet/ops/dcn/src/cuda/deform_conv_cuda_kernel.cu#L615), it is written that
```
const scalar_t h_im = h_in + i * dilation_h + offset_h;
const scalar_t w_im = w_in + j * dilation_w + offset_w;
``` 
Why was dilation considered here? What does `h_im` and `w_im` represent here and where does this equation come from ?

**Comment by BIGWangYuDong** [comment]
I don't know much about this, but I'm guessing if the first formula is the default configuration for the initial calculation of the convolution, and the second formula is the formula for calculation with diation and deformbal?
