### ISSUE TITLE
TensorboardLoggerHook epoch-based output frequency

### ISSUE THREAD

**Issue by chekhovana** [open-mmlab/mmdetection#8128]
Is it possible to configure TensorboardLoggerHook to log information not every n iterations but every epoch? And save epoch number instead of iteration number correspondingly.

**Comment by chhluo** [comment]
This's not supported yet, but you can read the source code and try to implement it, https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/tensorboard.py 
https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/base.py

**Comment by chekhovana** [comment]
I see that `LoggerHook` has `by_epoch` attribute that indicates whether `EpochBasedRunner` is used. I suggest to also use this attribute to define whether to log information every n iterations (`by_epoch=False`) or every n epochs (`by_epoch=True`). Frequency in both cases should be defined by `interval` attribute value. What do you think?

**Comment by chhluo** [comment]
I remember there is a way to log by epoch in tensorboard. `LoggerHook` logs information every `interval` interations regardless by_epoch. So if you want to log by epoch, just set interval = `len(dataset) * num_epoch / (samples_per_gpu * num_gpus)`

**Comment by chekhovana** [comment]
This will work, but it's a bit uncomfortable to change logger settings every time when dataset or batch size changes. And epoch number still won't not be visible on horizontal axes.

**Comment by chhluo** [comment]
There is a issue related which may be helpful, see https://github.com/open-mmlab/mmdetection/issues/7543.

Supporting logging by epoch in tensorboardhook is in our plan now, it will be done in the next one or two month.
