### ISSUE TITLE
How to set different optimizers (e.g., SGD and AdamW) for various modules (e.g., backbone, neck, and head)?

### ISSUE THREAD

**Issue by STAR-ALG** [open-mmlab/mmdetection#8130]
Hi, 
as described in my topic, I want to set up different optimizers for different modules. How can I achieve this effectively?
I would be really appreciative if you could help me. Thank you very much!

**Comment by chhluo** [comment]
This is not supported now, you can to write some code to implement this. And the following information may be hlepful:

1. The runner in mmcv support multi optimizer,  https://github.com/open-mmlab/mmcv/blob/ea0e8cdb418e4593b7691baf68e033ae7e830288/mmcv/runner/base_runner.py#L36. There is an an example: [biggan](https://github.com/open-mmlab/mmgeneration/blob/eba26af33e9f630a9506b227a35af3c8f1edc9c1/configs/_base_/models/biggan/biggan-deep_128x128_cvt_hugging-face_rgb.py#L33) in MMGeneration which use two different opimizers for the generator and the  discriminator.
2. To use two opimizers to update params separately, you can implement a hook to achieve it. Please read the source code https://github.com/open-mmlab/mmcv/blob/ea0e8cdb418e4593b7691baf68e033ae7e830288/mmcv/runner/hooks/optimizer.py#L23 https://github.com/open-mmlab/mmcv/blob/ea0e8cdb418e4593b7691baf68e033ae7e830288/mmcv/runner/hooks/optimizer.py#L153
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/core/optimizers/layer_decay_optimizer_constructor.py#L79
