### ISSUE TITLE
🔥Can not classify symmetrical object correctly. Need help🙏

### ISSUE THREAD

**Issue by yfq512** [open-mmlab/mmdetection#8133]
I have train 15 classes datasets base on faster-rcnn and get the model and it work well, but it can't classify symmetrical object correctly, such as them. Can you help me or give me your suggest?
![11](https://user-images.githubusercontent.com/52442277/172048157-3ee0a709-e581-42ce-90d3-00ea1b388fa9.jpg)
![22](https://user-images.githubusercontent.com/52442277/172048158-bb2bc2a3-e0e9-4f2c-9d3b-1acf2b6e54b3.jpg)

**Comment by MiXaiLL76** [comment]
You chose not the best pictures =)
+ No code to repeat.

**Comment by yfq512** [comment]
@MiXaiLL76  Two symmetrical logos are different classes in train datasets, but predict the same classes and Accuracy is about 0.5
