### ISSUE TITLE
How can I infer using fp16 inside mmdet apis?

### ISSUE THREAD

**Issue by iAhmedMaher** [open-mmlab/mmdetection#8134]
Hello!

I am using the mmdet apis of init_detector and inference_detector to infer on images. I wanted to try half-precision to speedup the model even at the cost of performance loss, but I can't see an interface for that. I tried to change the model returned by init_detector to fp16 using half(), but that caused errors inside inference_detector. What am I missing?

I am looking for a solution that will work across the openmm suite, and I am aware that there are model conversion tools, but I don't want to do that.

Thanks in advance.

**Comment by MiXaiLL76** [comment]
not all models support fp16.
For more accurate information, look at the zoo of models

**Comment by iAhmedMaher** [comment]
@MiXaiLL76 I tried looking at the zoo of models, but all I see is mixed precision training which isn't my goal. Also, even after mixed-precision training, how do I choose fp16 mode inference? Additionally, excuse my limited knowledge, but why does this need support? Doesn't Pytorch automatically support this?

**Comment by MiXaiLL76** [comment]
> 
FP16=yes
If models do not support fp16 by default, they cannot be run in this mode after. At least I didn't see that option.

https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/swin/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco.py

https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/swin/README.md

**Comment by ZwwWayne** [comment]
Please see the code in test.py. You can simply use `wrap_fp16_model(model)` to convert the model to FP16 status.
However, this might not give satisfactory performance. https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L225
