### ISSUE TITLE
How to train faster-rcnn pytorch style with C4 backbone

### ISSUE THREAD

**Issue by VectorYoung** [open-mmlab/mmdetection#814]
Hi, I want to train faster-rcnn with C4 backbone(without FPN), but there is only a config file 'faster_rcnn_r50_caffe_c4_1x.py'. Is it correct to only modify the style from 'caffe' to 'pytorch', and use the imagenet pretrained model for FPN backbone? Thanks.

**Comment by hellock** [comment]
- style
- pretrained
- img_norm_cfg

**Comment by VectorYoung** [comment]
Hi @hellock , 
1. so for pretrained model I can use `pretrained='model://resnet50'`, and `img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)`, just the same with FPN-backbone, right?
2. Why do we need to set BN require_grad=True. I think the BN shoul be frozen, right?

**Comment by hellock** [comment]
1. Yes.
2. You may refer to the Section 5.2 in our [technical report](https://arxiv.org/abs/1906.07155).

**Comment by my-hello-world** [comment]
@hellock ：
Isn't this the case like this?
norm_cfg = dict(type='BN', **requires_grad=False**)
and with pytorch-style like：
1.   pretrained=“”
2.  style='pytorch'
3.  
  norm_cfg = dict(type='BN', requires_grad=True),
  norm_eval= False,
 or the following and so on.
  norm_cfg = dict(type='GN', num_groups=32, requires_grad=True)
  norm_eval= False,
4. img_norm_cfg = dict(
   mean=[123.675, 116.28, 103.53], std = [58.395, 57.12, 57.375], to_rgb = True)

right?

**Comment by hellock** [comment]
`norm_eval` should be True if you use BN.

**Comment by TonojiKiobya** [comment]
Is it OK to use the config file that has fpn but just removing fpn as a neck and tune the config to use the last layer feature map from resnet?
