### ISSUE TITLE
data['category_id'] = self.cat_ids[label] IndexError: list index out of range

### ISSUE THREAD

**Issue by L-xiaolu** [open-mmlab/mmdetection#8140]
I got an error while training my dataset with the Deformable DETR model. I changed num_classes in deformable_detr_r50_16x2_50e_coco.py according to the documentation and changed CLASS in configs/_base_/datasets/coco_detection.py and coco.py files. I still get an error. The strange thing is that the error occurred during the evaluation of the 9th epoch. There was no problem in the first 0~8 epoch. I tried to output label and self.cat_ids[label], and their values ​​are 0. please help me

**Comment by DICPZhou** [comment]
hello, How did you solve the problem?

**Comment by L-xiaolu** [comment]
这个是我当时定义的类别列表有问题，你可以检查一下是不是一样的，我重写的类别列表就好了
