### ISSUE TITLE
How can I get the proposals' level0 feature without ROI_Align or ROI_pooling?

### ISSUE THREAD

**Issue by FarranYang** [open-mmlab/mmdetection#8141]
I want to get the original feature map of a proposal, I found the ROI_head code and mmcv/ops/roi_align.py, but I can't tell where is the original feature map of a proposal. Could you tell me where it is?

**Comment by Czm369** [comment]
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/roi_heads/standard_roi_head.py#L121

**Comment by FarranYang** [comment]
Thank you， I should explain it more in detail，I want to get the feature map without ROI_align. [https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/roi_align.py#L93](url) . It goes with Align,I don't want Align, I want the original feature of proposals.

**Comment by Czm369** [comment]
You can rewrite ` self.bbox_roi_extractor`, x is the feats, and rois is available.
Referring to https://github.com/open-mmlab/mmcv/blob/0230fc3bc09d160fde228cea35609c8e327d6978/mmcv/ops/roi_align.py#L65
