### ISSUE TITLE
cannot import name 'SENet' from 'mmdet.models'

### ISSUE THREAD

**Issue by xiaopan999** [open-mmlab/mmdetection#8143]
我已经在mmdet/models/backbones中建立了senet50.py,里面也对SENet进行了register
并且在mmdet/models/__init__.py中导入了SENet类
不过运行from mmdet.models import SENet出现上面这个错误,请问怎样解决？
![image](https://user-images.githubusercontent.com/43646121/172139672-7ed463ce-cd50-4e04-9125-43dc04894b46.png)

**Comment by Czm369** [comment]
Maybe you can try
`from mmdet.models.backbones import SENet`
