### ISSUE TITLE
Not clear about the learning rate config note in the README

### ISSUE THREAD

**Issue by yl1991** [open-mmlab/mmdetection#815]
Hi MMLab members,
There is a note in your GETTING_STARTED.md:
> *Important*: The default learning rate in config files is for 8 GPUs. If you use less or more than 8 GPUs, you need to set the learning rate proportional to the GPU num, e.g., 0.01 for 4 GPUs and 0.04 for 16 GPUs.

Then, following this note it starts with the "Train with a single GPU" section.  
This feels confusing to me. Do you mean this _important note_ applies for for both single- and multiple-GPU training? Do I need to change the learning rate accordingly whenever I am not using a 8-GPU machine? Where is the relating code located and why can not this process be automated?
Many thanks.

**Comment by hellock** [comment]
You need to change the learning rate accordingly whenever you are not using a 8-GPU machine and 2 img/gpu.
Please refer to the **Linear Scaling Rule** proposed in [Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour](https://arxiv.org/abs/1706.02677) for details.

**Comment by yl1991** [comment]
Thank you for the reference! It is very helpful maybe you could add the reference after the note.
