### ISSUE TITLE
Implementing a Custom Runner

### ISSUE THREAD

**Issue by barisbatuhan** [open-mmlab/mmdetection#8150]
Hi,

In my project, I have 2 datasets that include different objects in them and I have to train a detector that alternatingly processes one dataset and the other. Thus, I modified the Faster RCNN detector to have 2 RoI and RPN heads but one common backbone and neck. The required pipeline pseudocode is given below:

```
def train_one_iter():
   model.set_head(1)
   data1 = dataloader1.next()
   loss = model(data1)
   loss.backward()
   optimizer.step()

   model.set_head(2)
   data2 = dataloader2.next()
   loss = model(data2)
   loss.backward()
   optimizer.step()
```

However, the current runners that I observed do not allow for custom head changes and alternating dataset pass together. Is there any module that makes this kind of a pipeline applicable? If not, how can I modify the current runners to have this kind of training structure? Are there any examples for this purpose?

Thanks.

**Comment by hhaAndroid** [comment]
@barisbatuhan We are refactoring the runner, which will be released next month. You can wait until release time to implement it will be easier.
