### ISSUE TITLE
Log file question when using load_from

### ISSUE THREAD

**Issue by jacob-kang** [open-mmlab/mmdetection#8151]
Hello mmlab!
Thanks for your great tools.

I have a question about using `load_from` in `config` file.

When I use `pretrained`, the log file is `PretrainedInit: load from torchvision://resnet50`
But I want to use my checkpoint file. so I used `load_from`.
But there were `KaimingInit: a=0, mode=fan_out, nonlinearity=relu, distribution =normal, bias=0 `, `The value is the same before and after calling 'init_weights' of FasterRCNN `  etc, not `PretrainedInit: ~~~`

Is it applied my checkpoint file???

thanks.

**Comment by jbwang1997** [comment]
Hello @jacob-kang. Could you provide the config you use?

**Comment by jacob-kang** [comment]
> Hello @jacob-kang. Could you provide the config you use?


_base_ = '../configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'

model = dict(
    backbone=dict(
        #init_cfg=None)   
)

# 1. dataset settings
dataset_type = 'CocoDataset'
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
       img_prefix='data/coco/train2017',
        ann_file='coco-mini/annotations/instances_minitrain2017.json'),
    val=dict(
        type=dataset_type,
        img_prefix='data/coco/val2017',
        ann_file='data/coco/annotations/instances_val2017.json'),
    test=dict(
        type=dataset_type,
        img_prefix='data/coco/val2017',
        ann_file='data/coco/annotations/instances_val2017.json')
    )

load_from = '/home/newjacob19/mmdetection/checkpoints/COCO-mini_shape_stylized_SIN_CNN_ALL_Norm/epoch_12.pth'

**Comment by jbwang1997** [comment]
load_from is called after network initialization. The initialization is called [here](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L216) and the load_from is called [here](https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/apis/train.py#L243). The load_from weights will override the original initialization weights.

**Comment by jacob-kang** [comment]
> load_from is called after network initialization. The initialization is called [here](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L216) and the load_from is called [here](https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/apis/train.py#L243). The load_from weights will override the original initialization weights.

That means It was working!
Thanks.
