### ISSUE TITLE
How to implement mosaic augmentation along with multi-scale training?

### ISSUE THREAD

**Issue by Tianhao-Qi** [open-mmlab/mmdetection#8152]
As the title mentioned, I want to achieve mosaic augmentation along with multi-scale training, but the how_to.md doesn't include. Besides, if I want to set the prob of mosaic augmentation to 0.5, will the RandomAffine operation affect normal training?

**Comment by jbwang1997** [comment]
1. For multi-scale training, you can add `Resize` pipeline after `Mosaic` to resize the image into different scales. Besides,  `RandomAffine` also can randomly scale the image.
2. The prob of `Mosaic` have little influence on the normalization. You can keep the original setting.
