### ISSUE TITLE
How can I adjust query_instnum_proposals?

### ISSUE THREAD

**Issue by junho-choi-div** [open-mmlab/mmdetection#8154]
![image](https://user-images.githubusercontent.com/88411307/172739932-6fd0e21f-12e5-4bbc-adff-1d4a6c0637a6.png)

I am using query_inst model and I want to train by stretching the num_proposal is fixed at 300.

I defined it as 1000 in the config as follows, but the loss becomes negative as below.

![image](https://user-images.githubusercontent.com/88411307/172739981-4b093bba-3019-401e-aa48-52726e7f1eef.png)

If you know how to adjust num_proposal while the loss converges normally, I would appreciate your help.

Thanks!

**Comment by RangiLyu** [comment]
QueryInst is based on Sparse R-CNN which requires sparse proposals. 1000 seems to be dense, which may be not suitable for this model.
