### ISSUE TITLE
Using point rend with 101 resnet backbone

### ISSUE THREAD

**Issue by optimaltaskin** [open-mmlab/mmdetection#8162]
Hello, 

I want to train a model which implements point_rend and also has a resnet101 or resneXt 101 backbone. I'm using the configuration file below:

```
_base_ = '../point_rend/point_rend_r50_caffe_fpn_mstrain_3x_coco_downloaded.py'
model = dict(
    backbone=dict(
        depth=101,
        norm_cfg=dict(requires_grad=False),
        norm_eval=True,
        style='caffe',
        init_cfg=dict(
            type='Pretrained',
            checkpoint='open-mmlab://detectron2/resnet101_caffe')),
    roi_head=dict(
        bbox_head=dict(
            num_classes=1,
        ),
        mask_head=dict(
            num_classes=1,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)
        ),
        point_head=dict(
            num_classes=1,
            loss_point=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))
        ),
    test_cfg=dict(
        rpn=dict(
            max_per_img=100, ),
        rcnn=dict(
            max_per_img=10, ),
    ),
)

dataset_type = 'COCODataset'
classes = ('card',)
log_config = dict(interval=4)
checkpoint_config = dict(interval=4)
runner = dict(type='EpochBasedRunner', max_epochs=12)

optimizer = dict(_delete_=True, type='AdamW', lr=0.0001, weight_decay=0.0001)

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        img_prefix='data/cocoset/training/images/',
        classes=classes,
        ann_file='data/cocoset/training/coco_instances.json'),
    test=dict(
        img_prefix='data/cocoset/testing/images/',
        classes=classes,
        ann_file='data/cocoset/testing/coco_instances.json'),
    val=dict(
        img_prefix='data/cocoset/testing/images/',
        classes=classes,
        ann_file='data/cocoset/testing/coco_instances.json'),
)

load_from = 'checkpoints/point_rend_r50_caffe_fpn_mstrain_3x_coco-e0ebb6b7.pth'

```

Since point_rend has checkpoint trained with resnet 50 backbone, I can only use such a checkpoint to initialize my weights by setting load_from  = 'checkpoints/point_rend_r50_caffe_fpn_mstrain_3x_coco-e0ebb6b7.pth'. But in this case I do initialize my resnet 101 backbone model with a resnet 50 backbone model. Does this have any negative impact on the performance of the model? Should I leave load_from unset or is this configuration good to go? Thanks in advance.

**Comment by RangiLyu** [comment]
It's not a good idea to load a ResNet50 weight into a ResNet101 model. The extracted features from the backbone may be different. But you can still do some experiments about this.

**Comment by optimaltaskin** [comment]
@RangiLyu first of all thanks for your response. So in this case since there is no pretrained resnet 101 backbone point rend model file that I can download with mim download command, I should leave load_from field blank for the first run. And if I can train a good resnet 101 point_rend inference model, perhaps I can use my trained model to initialize(by my trained model to load_from field) further training runs weights, am I right?

**Comment by RangiLyu** [comment]
you are right

**Comment by optimaltaskin** [comment]
thanks @RangiLyu
