### ISSUE TITLE
adding features

### ISSUE THREAD

**Issue by mingkan** [open-mmlab/mmdetection#8163]
I would like to try to add some attributes between bounding boxes myself, such as lines and calculations (like the existing probabilities). Which files can I do that? What are the general algorithms or procedures can be done? Many Thanks.

**Comment by RangiLyu** [comment]
Sorry for the late reply. In MMDetection 2.x, it maybe really hard to add more attributes to the detection results. But in MMDetection 3.x, we introduce the new data structure of instances https://github.com/open-mmlab/mmdetection/blob/7b492550ddddaebf1880402465e6cbd77ec97d9b/mmdet/models/dense_heads/base_dense_head.py#L410
Now you can add any kind of attributes to the detection results. Just have a try!
