### ISSUE TITLE
Some question about the analysis speed of model with fp16 ?

### ISSUE THREAD

**Issue by Audrey528** [open-mmlab/mmdetection#8172]
I have tested the loaded speed and analysis speed of model with fp16 and without fp16, the result sees below. I am confused the speed of model with fp16 is slower.
![1b896edcbdc02daab71f6601ac14011](https://user-images.githubusercontent.com/68552295/173220846-6fb3dbb5-89b6-45bd-b394-e6316edf172b.png)

**Comment by Audrey528** [comment]
> I have tested the loaded speed and analysis speed of model with fp16 and without fp16, the result sees below. I am confused the speed of model with fp16 is slower. ![1b896edcbdc02daab71f6601ac14011](https://user-images.githubusercontent.com/68552295/173220846-6fb3dbb5-89b6-45bd-b394-e6316edf172b.png)

**Comment by MiXaiLL76** [comment]
I have the same issues with resnet50

**Comment by shiyongde** [comment]
same problem, bug mvg_yolox works well

**Comment by ZwwWayne** [comment]
The speed is dependent on the device and might also includes data loading. This issue should have been resolved in MMDet 3.x.

**Comment by ZwwWayne** [comment]
Please @hhaAndroid  to take a look.
