### ISSUE TITLE
How to set adaptive learning rate based on loss？

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#8174]
the runner doesn't have the loss info，So I can't set an adaptive learning rate based on loss, how to get loss info in the runner?

![image](https://user-images.githubusercontent.com/25839884/173242812-c1c68146-7a11-4061-b5c5-1541e1477dea.png)

**Comment by PeterVennerstrom** [comment]
The runner should hold loss information in [self.outputs after each iteration](https://github.com/open-mmlab/mmcv/blob/30f305810702f47525a28e6a58d52414ecb79d0f/mmcv/runner/epoch_based_runner.py#L24-L38).  

The [detector base class](https://github.com/open-mmlab/mmdetection/blob/ff9bc39913cb3ff5dde79d3933add7dc2561bab7/mmdet/models/detectors/base.py#L221-L254) shows how the losses are consolidated and structured into outputs.
