### ISSUE TITLE
Initialize custom layer / module

### ISSUE THREAD

**Issue by jacob-kang** [open-mmlab/mmdetection#8177]
Hello! mmlab!

I'm wondering how does this model initialize new layer?
I added my own module or layer. And I don't set specifin initialization onto my layer.

I want to know how this model initialize layer which is not included in model basically. (So it should be missing keys ~~ blah blah~~)

thanks

**Comment by Czm369** [comment]
Take `RoIAlign` as an example, 
config is https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/_base_/models/faster_rcnn_r50_fpn.py#L39 
and layer is
https://github.com/open-mmlab/mmcv/blob/45fa3e44a22cd0b74071237304bdfef97b5b9bd6/mmcv/ops/roi_align.py#L177

**Comment by jacob-kang** [comment]
> 

Oh I mean.... What kind of initialization does this tool initialize to new layer?
When I don't set specific initialization, It initializes `NormalInit` or `XavierInit` or etc..

I added some CNN and normalization into ResNet.

And it might be inited **something**!

Thanks

**Comment by jacob-kang** [comment]
> Take `RoIAlign` as an example, config is
> 
> https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/_base_/models/faster_rcnn_r50_fpn.py#L39
> 
> 
> and layer is
> https://github.com/open-mmlab/mmcv/blob/45fa3e44a22cd0b74071237304bdfef97b5b9bd6/mmcv/ops/roi_align.py#L177

Oh I mean.... What kind of initialization does this tool initialize to new layer?
When I don't set specific initialization, It initializes NormalInit or XavierInit or etc..

I added some CNN and normalization into ResNet.

And it might be inited something!

Thanks
