### ISSUE TITLE
Generalized Attention with config 0100 and 0001 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#8179]
Hello all , 

I would like to thank you first for such effort. second i would like to ask regards the Generalized Attention which is one of spatial attention mechanism as i noticed. 

I try to use it with different models rather than faster rcnn , it works perfectly when i did the config to be 1111 or 0010 (similar to what you already have in this repository ) but when i try another config like 0100 it does not working at all . 
it gave me such error massage : 

`RuntimeError: The size of tensor a (84) must match the size of tensor b (48) at non-singleton dimension 2
`

Actually , I did not get on with this error ,and did not understand the reason of it . 

can you please help ?

**Comment by Czm369** [comment]
The concrete implementation of  `GeneralizedAttention` is in 
https://github.com/open-mmlab/mmcv/blob/45fa3e44a22cd0b74071237304bdfef97b5b9bd6/mmcv/cnn/bricks/generalized_attention.py#L39

**Comment by alaa-shubbak** [comment]
I tried the same structure , my config is as bellow : 
`
_base_ ='fsaf_r50_fpn_1x_coco_CIOU.py'

# model settings
model = dict(
    backbone=dict(plugins=[
        dict(
            cfg=dict(
                type='GeneralizedAttention',
                spatial_range=-1,
                num_heads=8,
                attention_type='0100',
                kv_stride=2),
            stages=(False, False, True, True),
            position='after_conv2')
    ]))

runner = dict(
    type='EpochBasedRunner', max_epochs=200)  


#check points
load_from='checkpoints/fsaf_r50_fpn_1x_coco-94ccc51f.pth'

`
but i did not get any results, the model was unable to train ,which was weird as I used both (1111) and (0010) component of this attention mechanism and it works perfectly.
