### ISSUE TITLE
Getting something wrong when replacing backbone of mask_rcnn to mobilenetv2

### ISSUE THREAD

**Issue by mZhenz** [open-mmlab/mmdetection#8186]
Hi, I try to replace the backbone of mask rcnn to mobilenetv2. And I firstly get the error like that.

```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 7: 153 154 155
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
```

Therefore, I add `find_unused_parameters = True` in my config file. Well, it can train normally. But it get all evaluation metric equals to 0 when evalution like below.

```
2022-06-14 23:38:30,272 - mmdet - INFO - 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000

2022-06-14 23:38:30,273 - mmdet - INFO - Evaluating segm...
2022-06-14 23:38:41,259 - mmdet - INFO - 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000
```

And here is my config files. Is there anything wrong?

```
_base_ = [
    "../_base_/datasets/coco_instance.py",
    "../_base_/schedules/schedule_1x.py",
    "../_base_/default_runtime.py"
]

# model settings
model = dict(
    type='MaskRCNN',
    backbone=dict(
        type='MobileNetV2',
        out_indices=(2, 4, 6),
        act_cfg=dict(type='LeakyReLU', negative_slope=0.1),
        init_cfg=dict(
            type='Pretrained', checkpoint='open-mmlab://mmdet/mobilenet_v2')),
    neck=dict(
        type='FPN',
        in_channels=[32, 96, 320],
        out_channels=256,
        num_outs=3),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=80,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=80,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))
    ),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)
        # soft-nms is also supported for rcnn testing
        # e.g., nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05)
    ))

```

**Comment by jbwang1997** [comment]
Seem there is no mistake in your config. I consider it's because the training schedule is too short or the model doesn't converge.

**Comment by mZhenz** [comment]
> Seem there is no mistake in your config. I consider it's because the training schedule is too short or the model doesn't converge.

This is the evaluation result of the first epoch, and seem it is not because training schedule is too short. Is there any suggestion to check this bug. Thanks a lot!
I just modify this config file and do not modify the  config file below.
 "../_base_/datasets/coco_instance.py",
 "../_base_/schedules/schedule_1x.py",
 "../_base_/default_runtime.py"

btw, could there be something problem with the setting `find_unused_parameters = True`?

**Comment by mZhenz** [comment]
Here is my [training log](https://github.com/mZhenz/Work-Tencent/blob/main/20220616_141122.log). If anyone could give me some suggestion?

**Comment by jbwang1997** [comment]
`find_unused_parameters = True` is necessary because the final conv of moblienet isn't used in producing loss. The config of YOLOv3+ MoblieNet also adds `find_unused_parameters = True`.

I read the structure of moblienetv2, the strides should be [8, 16, 32] since the first layer has stride 2. You can first try to modify the strides in anchor_generator and roi_align. Then you can try to reduce the learning rate to see if the loss can decrease normally.

**Comment by mZhenz** [comment]
@jbwang1997 Problem solved. Thanks you so much!

Here is the config file of `mask_rcnn_mobilenetv2_fpn_1x_coco.py` for the convenience of others.
```
_base_ = [
    "../_base_/datasets/coco_instance.py",
    "../_base_/schedules/schedule_1x.py",
    "../_base_/default_runtime.py"
]

# model settings
model = dict(
    type='MaskRCNN',
    backbone=dict(
        type='MobileNetV2',
        out_indices=(2, 4, 6),
        act_cfg=dict(type='LeakyReLU', negative_slope=0.1),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='open-mmlab://mmdet/mobilenet_v2',
        )),
    neck=dict(
        type='FPN',
        in_channels=[32, 96, 320],
        out_channels=256,
        num_outs=3),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[8, 16, 32]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=80,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[8, 16, 32]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=80,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))
    ),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)
        # soft-nms is also supported for rcnn testing
        # e.g., nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05)
    ))
```

**Comment by noreenanwar** [comment]
> @jbwang1997 Problem solved. Thanks you so much!
> 
> Here is the config file of `mask_rcnn_mobilenetv2_fpn_1x_coco.py` for the convenience of others.
> 
> ```
> _base_ = [
>     "../_base_/datasets/coco_instance.py",
>     "../_base_/schedules/schedule_1x.py",
>     "../_base_/default_runtime.py"
> ]
> 
> # model settings
> model = dict(
>     type='MaskRCNN',
>     backbone=dict(
>         type='MobileNetV2',
>         out_indices=(2, 4, 6),
>         act_cfg=dict(type='LeakyReLU', negative_slope=0.1),
>         init_cfg=dict(
>             type='Pretrained',
>             checkpoint='open-mmlab://mmdet/mobilenet_v2',
>         )),
>     neck=dict(
>         type='FPN',
>         in_channels=[32, 96, 320],
>         out_channels=256,
>         num_outs=3),
>     rpn_head=dict(
>         type='RPNHead',
>         in_channels=256,
>         feat_channels=256,
>         anchor_generator=dict(
>             type='AnchorGenerator',
>             scales=[8],
>             ratios=[0.5, 1.0, 2.0],
>             strides=[8, 16, 32]),
>         bbox_coder=dict(
>             type='DeltaXYWHBBoxCoder',
>             target_means=[.0, .0, .0, .0],
>             target_stds=[1.0, 1.0, 1.0, 1.0]),
>         loss_cls=dict(
>             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
>         loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
>     roi_head=dict(
>         type='StandardRoIHead',
>         bbox_roi_extractor=dict(
>             type='SingleRoIExtractor',
>             roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
>             out_channels=256,
>             featmap_strides=[8, 16, 32]),
>         bbox_head=dict(
>             type='Shared2FCBBoxHead',
>             in_channels=256,
>             fc_out_channels=1024,
>             roi_feat_size=7,
>             num_classes=80,
>             bbox_coder=dict(
>                 type='DeltaXYWHBBoxCoder',
>                 target_means=[0., 0., 0., 0.],
>                 target_stds=[0.1, 0.1, 0.2, 0.2]),
>             reg_class_agnostic=False,
>             loss_cls=dict(
>                 type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
>             loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
>         mask_roi_extractor=dict(
>             type='SingleRoIExtractor',
>             roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
>             out_channels=256,
>             featmap_strides=[8, 16, 32]),
>         mask_head=dict(
>             type='FCNMaskHead',
>             num_convs=4,
>             in_channels=256,
>             conv_out_channels=256,
>             num_classes=80,
>             loss_mask=dict(
>                 type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))
>     ),
>     # model training and testing settings
>     train_cfg=dict(
>         rpn=dict(
>             assigner=dict(
>                 type='MaxIoUAssigner',
>                 pos_iou_thr=0.7,
>                 neg_iou_thr=0.3,
>                 min_pos_iou=0.3,
>                 match_low_quality=True,
>                 ignore_iof_thr=-1),
>             sampler=dict(
>                 type='RandomSampler',
>                 num=256,
>                 pos_fraction=0.5,
>                 neg_pos_ub=-1,
>                 add_gt_as_proposals=False),
>             allowed_border=-1,
>             pos_weight=-1,
>             debug=False),
>         rpn_proposal=dict(
>             nms_pre=2000,
>             max_per_img=1000,
>             nms=dict(type='nms', iou_threshold=0.7),
>             min_bbox_size=0),
>         rcnn=dict(
>             assigner=dict(
>                 type='MaxIoUAssigner',
>                 pos_iou_thr=0.5,
>                 neg_iou_thr=0.5,
>                 min_pos_iou=0.5,
>                 match_low_quality=True,
>                 ignore_iof_thr=-1),
>             sampler=dict(
>                 type='RandomSampler',
>                 num=512,
>                 pos_fraction=0.25,
>                 neg_pos_ub=-1,
>                 add_gt_as_proposals=True),
>             mask_size=28,
>             pos_weight=-1,
>             debug=False)),
>     test_cfg=dict(
>         rpn=dict(
>             nms_pre=1000,
>             max_per_img=1000,
>             nms=dict(type='nms', iou_threshold=0.7),
>             min_bbox_size=0),
>         rcnn=dict(
>             score_thr=0.05,
>             nms=dict(type='nms', iou_threshold=0.5),
>             max_per_img=100,
>             mask_thr_binary=0.5)
>         # soft-nms is also supported for rcnn testing
>         # e.g., nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05)
>     ))
> ```
Hi, 
I am also facing the same issue but with HRNET backbone .Any idea how to solve this?
