### ISSUE TITLE
about the pretrained models of V1

### ISSUE THREAD

**Issue by liupersever** [open-mmlab/mmdetection#8188]
I downloaded a code based on mmdetection，but it is using the V1 version.I have been searching for a long time and have not found these pretrained models.So I would like to ask if you have the V1 version of the pre-trained model, thank you very much.
Below is the pretrained model I need：
Faster R-CNN
R-50-FPN pytorch 2x
R-101-FPN pytorch 2x
X-101-64x4d-FPN pytorch 2x

RetinaNet
R-50-FPN pytorch 2x
R-101-FPN pytorch 2x
X-101-64x4d-FPN pytorch 2x

Cascade R-CNN
R-50-FPN pytorch 20e
R-101-FPN pytorch 20e
X-101-64x4d-FPN pytorch 20e

Thank you very much!

**Comment by jbwang1997** [comment]
You can find some legacy model at https://github.com/open-mmlab/mmdetection/tree/master/configs/legacy_1.x.
