### ISSUE TITLE
mosaic，train slowly

### ISSUE THREAD

**Issue by EdisionWew** [open-mmlab/mmdetection#8196]
Hi， thanks for your work. I use  the mosaic method of mmdetection in piplines, but I found it cost a lot of time vs. yolov5. How to get it optimized？Could you give me some suggestion?
![image](https://user-images.githubusercontent.com/23101204/173794229-38c49647-df98-46f4-9d6d-cf800a9d81f9.png)
![image](https://user-images.githubusercontent.com/23101204/173794021-383c0c43-b26c-4a55-a6a0-73495c956c6c.png)

**Comment by jbwang1997** [comment]
The pipeline is called in dataloader. You can increase the workers_per_gpu to speed up it.
