### ISSUE TITLE
'Cannot set locale modifiers' while test.py

### ISSUE THREAD

**Issue by aimhabo** [open-mmlab/mmdetection#82]
I use it like 'CUDA_VISIBLE_DEVICES=1,2,3 python ./tools/test.py --config ./configs/mask_rcnn_r50_fpn_1x.py --checkpoint ../workspace/mask_rcnn_r50_fpn_1x/epoch_12.pth --out ./workspace/out/maskrcnn.pkl --eval {segm,bbox} --gpus 1 --show'

An image in the sample is displayed, and only a box and its classification are marked on image. And then it is stuck in the state like the picture.

bash test-mmdetection.sh 
loading annotations into memory...
Done (t=0.34s)
creating index...
index created!
[                              ] 0/13486, elapsed: 0s, ETA:Qt: Cannot set locale modifiers: 

![20181026173856](https://user-images.githubusercontent.com/12708080/47559351-da1c6700-d947-11e8-82dd-b45218a52647.png)

Where's the error come from? and how could I pass this?

**Comment by hellock** [comment]
Since you specified `--show`, opencv is required to show images and bboxes. The error comes from the GUI backend of opencv. Maybe you need to make your opencv work first.

**Comment by aimhabo** [comment]
是这样... 看了下，用pip安装的跑到外部环境去了，用conda安装的才能用。
