### ISSUE TITLE
how did you get these anchor base size?

### ISSUE THREAD

**Issue by youmingdeng** [open-mmlab/mmdetection#8203]
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/yolo/yolov3_mobilenetv2_320_300e_coco.py#L7

**Comment by RangiLyu** [comment]
We use https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/optimize_anchors.py to optimize the anchor sizes.
