### ISSUE TITLE
I can't deal with this AttributeError: 'ConfigDict' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by grwal** [open-mmlab/mmdetection#8207]
`
Traceback (most recent call last):
  File "E:/Baseline/Train/train.py", line 28, in <module>
    cfg.data.train.dataset.ann_file = 'E:/Baseline/Data/Train_label.json'
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\utils\config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dataset'
`

**This is my error code.
Is it possible that config doesn't have a dataset...?
I can't understand what's the missing point.

Below is my train.py code's config part.
Can you help me to complete this?**

`
from mmdet.datasets.builder import DATASETS
from mmdet.datasets.coco import CocoDataset
from mmcv import Config
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import train_detector
from mmdet.apis import set_random_seed
from mmdet.datasets import (build_dataloader, build_dataset,
                            replace_ImageToTensor)

@DATASETS.register_module(force=True)
class ParkingDataset(CocoDataset):
    CLASSES = ('sedan','SUV','van','bus','school bus','truck','taxi',
               'adult','kid','motorcycle','electric scooter','bicycle',
               'stroller','cart')

config_file = '../Train/mmdetection/configs/dynamic_rcnn/dynamic_rcnn_r50_fpn_1x_coco.py' 
cfg = Config.fromfile(config_file)

cfg.dataset_type = 'ParkingDataset'
cfg.data_root = 'E:/Baseline/Data/'

cfg.data.train.type = 'ParkingDataset'
cfg.data.train.dataset.ann_file = 'E:/Baseline/Data/Train_label.json'
cfg.data.train.dataset.img_prefix = 'E:/Baseline/Data/Train_imgs/'

cfg.data.val.type = 'ParkingDataset'
cfg.data.val.ann_file = 'E:/Baseline/Data/Valid_label.json'
cfg.data.val.img_prefix = 'E:/Baseline/Data/Valid_imgs/'

cfg.data.test.type = 'ParkingDataset'
cfg.data.test.ann_file = 'E:/Baseline/Data/Valid_label.json'
cfg.data.test.img_prefix = 'E:/Baseline/Data/Valid_imgs/'

cfg.model.roi_head.bbox_head.num_classes = 14
cfg.load_from = './dynamic_rcnn_r50_fpn_1x-62a3f276.pth'

cfg.work_dir = '../runs/train/'

cfg.lr_config.warmup = None
cfg.log_config.interval = 10

cfg.evaluation.metric = 'bbox'
cfg.evaluation.interval = 12
cfg.checkpoint_config.interval = 12

cfg.runner.max_epochs = 30
cfg.seed = 0
cfg.gpu_ids = range(1)
set_random_seed(9999, deterministic=False)
cfg.device = 'cuda'
cfg.dataset = 'CocoDataset'
`

**Comment by BIGWangYuDong** [comment]
Please check your config file, seems you did not add `dataset` init

**Comment by grwal** [comment]
> Please check your config file, seems you did not add `dataset` init

Oh I thought config file is about base of the models so if I change it will occur problems.
But I'm really new to this mmd model, so I'm so sorry but can you give me an example of adding dataset init?

**Comment by James606240** [comment]
Hi @grwal could you teach me how to fix this problem？ could email me：foxy606240@gmail.com？Appreciate I had this problem so many times.

**Comment by grwal** [comment]
> Hi @grwal could you teach me how to fix this problem？ could email me：[foxy606240@gmail.com](mailto:foxy606240@gmail.com)？Appreciate I had this problem so many times.

Sorry for sooo late :( I hope you already fixed problem though, if not still I will happily let you know what was my simple method

**Comment by asdspal** [comment]
Hi @grwal, can you please share your solution?

**Comment by saadyousuf45** [comment]
?
