### ISSUE TITLE
How to use copypaste augmentation in classbalanced dataset?

### ISSUE THREAD

**Issue by Kyfafyd** [open-mmlab/mmdetection#8209]
How to use copypaste augmentation in classbalanced dataset?

**Comment by Kyfafyd** [comment]
any update?
@RangiLyu @ZwwWayne

**Comment by BIGWangYuDong** [comment]
Sorry for the late reply, we haven't tried on classbalance dataset before, please @Czm369 have a look at this issue.

**Comment by Czm369** [comment]
You can try to wrap `ClassBalancedDatas` with  `MultiImageMixDatase`.
More details depend on your design.

**Comment by Kyfafyd** [comment]
@Czm369 , many thanks for your response!
As I am new to mmdetection, could you please give me more instructions on how to warp? or how to set in the config?

**Comment by Kyfafyd** [comment]
any update?
@Czm369

**Comment by Czm369** [comment]
load_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=file_client_args),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
        type='Resize',
        img_scale=image_size,
        ratio_range=(0.8, 1.25),
        multiscale_mode='range',
        keep_ratio=True),
    dict(
        type='RandomCrop',
        crop_type='absolute_range',
        crop_size=image_size,
        recompute_bbox=True,
        allow_negative_crop=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1e-2, 1e-2)),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Pad', size=image_size),
]
train_pipeline = [
    dict(type='CopyPaste', max_num_pasted=100),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='ClassBalancedDataset',
        oversample_thr=1e-3,
        dataset=dict(
            type='MultiImageMixDataset',
            dataset=dict(
                type=dataset_type,
                ann_file=data_root + 'annotations/instances_train2017.json',
                img_prefix=data_root + 'train2017/',
                pipeline=load_pipeline),
            pipeline=train_pipeline)))
