### ISSUE TITLE
How to freeze the backbone?

### ISSUE THREAD

**Issue by leondada** [open-mmlab/mmdetection#8210]
I set dict(lr_mult=0,decay_mult=0.0) for backbone, but the parameters are still trained, why?

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/how_to.md#unfreeze-backbone-network-after-freezing-the-backbone-in-the-config

**Comment by BIGWangYuDong** [comment]
sorry for the late reply, 
lr = 0 is not equal to freeze, if you want to freeze the backbone, you can refer to https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/backbones/resnet.py#L325-L326
