### ISSUE TITLE
centernet neck

### ISSUE THREAD

**Issue by javalier** [open-mmlab/mmdetection#8216]
can i use other neck network inplace the ct_resnet without change anything ？sorry ,i am confuse about this network.

**Comment by chhluo** [comment]
It's better to figure out that what is input and output shape of `CTResNetNeck`, then replace it with other neck (need modify the config)

https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/necks/ct_resnet_neck.py#L93
