### ISSUE TITLE
What is the proper way to deal with Ultra High Resolution images?

### ISSUE THREAD

**Issue by justlike-prog** [open-mmlab/mmdetection#8217]
I would like to resize them before doing the inference otherwise I run into CUDA OOM. In Detectron2 you can do a resize using `detectron2.data.transforms.ResizeShortestEdge`. Is there a way to do the resizing such that resizing back is also automatically taken care of after the inference?

**Comment by chhluo** [comment]
It is automatically taken care of after the inference. See, https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/detectors/single_stage.py#L93

https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/apis/test.py#L29

**Comment by justlike-prog** [comment]
Where do I set the size? From what I tried using Mask-RCNN and the normal `inference_detector` I am running into CUDA OOM. if the image is too big. @chhluo

**Comment by chhluo** [comment]
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/_base_/datasets/coco_instance.py#L20

**Comment by chhluo** [comment]
Inference on a image of shape (1333, 800) with mask rcnn will not cost 4 GB. Are there many instances in the image?
