### ISSUE TITLE
How to use mosaic in cascade mask rcnn?

### ISSUE THREAD

**Issue by lijinrun** [open-mmlab/mmdetection#8218]
I add 'mosaic' and 'randomaffine'
![image](https://user-images.githubusercontent.com/49092533/174463531-37ba585b-26e7-4018-bfd4-2fc86c7051d9.png)
and 'MultiImageMixDataset'.
![image](https://user-images.githubusercontent.com/49092533/174463557-e3e6fd0d-95dc-4a7f-bcf1-c8ebe2af61d8.png)
And then 
![image](https://user-images.githubusercontent.com/49092533/174463577-df8b4b27-8821-4474-ae23-166edba0dfa8.png)
How to solve it?

**Comment by ZwwWayne** [comment]
For now, Mosaic does not support instance segmentation. You need to support it first.
