### ISSUE TITLE
Fix a bug:UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.   warnings.warn('Class names are not saved in the checkpoint\'s '

### ISSUE THREAD

**Issue by PanJinquan** [open-mmlab/mmdetection#822]
Hi ,I found a bug in `mmdet/apis/inference.py->init_detector()`, when I run the demo  with the checkpoint from pre-train model and show UserWarning msg:
`UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
`
So I debug inference source code and found the :
```python
def init_detector(config, checkpoint=None, device='cuda:0'):
    """Initialize a detector from config file.

    Args:
        config (str or :obj:`mmcv.Config`): Config file path or the config
            object.
        checkpoint (str, optional): Checkpoint path. If left as None, the model
            will not load any weights.

    Returns:
        nn.Module: The constructed detector.
    """
    if isinstance(config, str):
        config = mmcv.Config.fromfile(config)
    elif not isinstance(config, mmcv.Config):
        raise TypeError('config must be a filename or Config object, '
                        'but got {}'.format(type(config)))
    config.model.pretrained = None
    model = build_detector(config.model, test_cfg=config.test_cfg)
    if checkpoint is not None:
        checkpoint = load_checkpoint(model, checkpoint)
        if 'CLASSES' in checkpoint['meta']:
            model.CLASSES = checkpoint['meta']['classes']
        else:
            warnings.warn('Class names are not saved in the checkpoint\'s '
                          'meta data, use COCO classes by default.')
            model.CLASSES = get_classes('coco')
    model.cfg = config  # save the config in the model for convenience
    model.to(device)
    model.eval()
    return model

````
Problem may come from ` if 'CLASSES' in checkpoint['meta']:
            model.CLASSES = checkpoint['meta']['classes']`, need to rename `CLASSES` to `classes`,finally it worked out

**Comment by hellock** [comment]
Thanks for the report! There was a short time when we save the class names in the checkpoint with the key `classes`, and now we use `CLASSES` for consistency. See https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L85 for details.

Which checkpoint are you using? We may update the checkpoint accordingly.

**Comment by 2448845600** [comment]
faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth

I meet the same error, please update soon, thank you!

**Comment by Ruofei520** [comment]
> Thanks for the report! There was a short time when we save the class names in the checkpoint with the key `classes`, and now we use `CLASSES` for consistency. See https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L85 for details.
> 
> Which checkpoint are you using? We may update the checkpoint accordingly.

faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
when I use this model, it appeared this problem.

**Comment by Wiger123** [comment]
I have same problem.
`(mmdetection) F:\BaiduNetdiskDownload\mmdetection\mmdetection-1.1.0>python demo.py                                      F:\BaiduNetdiskDownload\mmdetection\mmdetection-1.1.0\mmdet\apis\inference.py:40: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.                                                              warnings.warn('Class names are not saved in the checkpoint\'s '                                                       Traceback (most recent call last):                                                                                        File "demo.py", line 17, in <module>                                                                                      show_result(img, result, model.CLASSES)                                                                               File "F:\BaiduNetdiskDownload\mmdetection\mmdetection-1.1.0\mmdet\apis\inference.py", line 179, in show_result            out_file=out_file)                                                                                                    File "f:\baidunetdiskdownload\mmdetection\mmcv-0.4.4\mmcv\visualization\image.py", line 133, in imshow_det_bboxes         label] if class_names is not None else 'cls {}'.format(label)                                                       IndexError: list index out of range         `

**Comment by Fanthers** [comment]
> Hi ,I found a bug in `mmdet/apis/inference.py->init_detector()`, when I run the demo with the checkpoint from pre-train model and show UserWarning msg:
> `UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default. warnings.warn('Class names are not saved in the checkpoint\'s ' `
> So I debug inference source code and found the :
> 
> ```python
> def init_detector(config, checkpoint=None, device='cuda:0'):
>     """Initialize a detector from config file.
> 
>     Args:
>         config (str or :obj:`mmcv.Config`): Config file path or the config
>             object.
>         checkpoint (str, optional): Checkpoint path. If left as None, the model
>             will not load any weights.
> 
>     Returns:
>         nn.Module: The constructed detector.
>     """
>     if isinstance(config, str):
>         config = mmcv.Config.fromfile(config)
>     elif not isinstance(config, mmcv.Config):
>         raise TypeError('config must be a filename or Config object, '
>                         'but got {}'.format(type(config)))
>     config.model.pretrained = None
>     model = build_detector(config.model, test_cfg=config.test_cfg)
>     if checkpoint is not None:
>         checkpoint = load_checkpoint(model, checkpoint)
>         if 'CLASSES' in checkpoint['meta']:
>             model.CLASSES = checkpoint['meta']['classes']
>         else:
>             warnings.warn('Class names are not saved in the checkpoint\'s '
>                           'meta data, use COCO classes by default.')
>             model.CLASSES = get_classes('coco')
>     model.cfg = config  # save the config in the model for convenience
>     model.to(device)
>     model.eval()
>     return model
> ```
> 
> Problem may come from ` if 'CLASSES' in checkpoint['meta']: model.CLASSES = checkpoint['meta']['classes']`, need to rename `CLASSES` to `classes`,finally it worked out

could you please tell me that how you solved it.
