### ISSUE TITLE
TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by kimlia545** [open-mmlab/mmdetection#8228]
torch version : 1.10.1+cu111
mmdet version : 2.24.1

```
from mmdet.apis import single_gpu_test
from mmdet.datasets import (build_dataloader, build_dataset,
                            replace_ImageToTensor)

dataset = build_dataset(cfg.data.val)
samples_per_gpu = 1
distributed = False
data_loader = build_dataloader(
    dataset,
    samples_per_gpu=samples_per_gpu,
    workers_per_gpu=cfg.data.workers_per_gpu,
    dist=distributed,
    shuffle=False)
single_gpu_test(model, data_loader, show=False, out_dir=None, show_score_thr=0.3)
```

loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
[                                                  ] 0/81, elapsed: 0s, ETA:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-eba8c5aad2bd> in <module>
     12     dist=distributed,
     13     shuffle=False)
---> 14 single_gpu_test(model, data_loader, show=False, out_dir=None, show_score_thr=0.3)

~/Desktop/mmdetection/mmdet/apis/test.py in single_gpu_test(model, data_loader, show, out_dir, show_score_thr)
     27     for i, data in enumerate(data_loader):
     28         with torch.no_grad():
---> 29             result = model(return_loss=False, rescale=True, **data)
     30 
     31         batch_size = len(result)

~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/.local/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py in new_func(*args, **kwargs)
    108                                 f'method of those classes {supported_types}')
    109             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
--> 110                 return old_func(*args, **kwargs)
    111 
    112             # get the arg spec of the decorated method

~/Desktop/mmdetection/mmdet/models/detectors/base.py in forward(self, img, img_metas, return_loss, **kwargs)
    172             return self.forward_train(img, img_metas, **kwargs)
    173         else:
--> 174             return self.forward_test(img, img_metas, **kwargs)
    175 
    176     def _parse_losses(self, losses):

~/Desktop/mmdetection/mmdet/models/detectors/base.py in forward_test(self, imgs, img_metas, **kwargs)
    135             batch_size = len(img_meta)
    136             for img_id in range(batch_size):
--> 137                 img_meta[img_id]['batch_input_shape'] = tuple(img.size()[-2:])
    138 
    139         if num_augs == 1:

TypeError: 'DataContainer' object is not subscriptable

**Comment by siddharthKatageri** [comment]
Hi @kimlia545, did you get a solution to this issue yet?
Thanks.

**Comment by kimlia545** [comment]
@siddharthKatageri 
I solved it, thanks for asking.

**Comment by AArchLichKing** [comment]
Hi @kimlia545 ,

I encountered the same issue. Can you please indicate how did you fix the problem? 

Thank you very much!

**Comment by kimlia545** [comment]
I'm sorry for the late reply.
I'm not sure because it was a long time ago, but I think I modified this part.
```
test_pipeline 
dict(
                type="ImageToTensor", keys=["img"]
            ),  # dict(type='DefaultFormatBundle')

```
