### ISSUE TITLE
Bottleneck in the `_do_paste_mask` function?

### ISSUE THREAD

**Issue by justlike-prog** [open-mmlab/mmdetection#8232]
I am running into some OOM errors when running Mask RCNN with MMDetection while I don't have any problems when using Detectron2:

With Image 1 which is about 2000x2000:

`line 4011, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 986.00 MiB`

With Image 2 which is about 8000x4000:

`line 404, in _do_paste_mask
    grid = torch.stack([gx, gy], dim=3)
RuntimeError: CUDA out of memory. Tried to allocate 1.91 GiB`

Both errors stem from the `_do_paste_mask` function, which seems to be some postprocessing function. Internally the images get resized to (1333, 800) in Mask-RCNN. It seems that Detectron2 doesn't run in such problems although the `_do_paste_mask` function seems to be more or less the same as in MMDetection.

Could anyone explain me what this function does and what the possible bottleneck could be?

**Comment by PeterVennerstrom** [comment]
When [rescale=True ](https://github.com/open-mmlab/mmdetection/blob/2cd24a2e2173c85922bfdea083f25556b12acccf/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py#L250-L252)_do_paste_mask resizes the instance masks to the original image shape on the same device the masks reside on when input to the function.

MaskRCNN outputs masks as ROIs, _do_paste_mask places the masks on the image at the corresponding ROI's location.  

You could try moving the masks to cpu before calling _do_paste_mask

**Comment by hhaAndroid** [comment]
@justlike-prog Probably because of `retry_if_cuda_oom`
