### ISSUE TITLE
How to add a new convolutional layer in head?

### ISSUE THREAD

**Issue by austin1900** [open-mmlab/mmdetection#8244]
When I add a convolution layer to the head, the following error is prompted：
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

**Comment by RangiLyu** [comment]
It seems that the layer you added does not participate in loss calculation.

You can add `detect_anomalous_params=True` to the `optimizer_config` in your config file to find out which layer is not used.

**Comment by ruoshuichengyang** [comment]
if i find that module.panoptic_head_r_embed.weight is not in the computational graph, what can i do to include it in the computational graph?

**Comment by ruoshuichengyang** [comment]
> It seems that the layer you added does not participate in loss calculation.
> 
> You can add `detect_anomalous_params=True` to the `optimizer_config` in your config file to find out which layer is not used.
I add a linear layer to the head and meet the same issue as above.And I add detect_anomalous_params=True to the optimizer_config inmy config file to find out that module.panoptic_head_r_embed.weight is not in the computational graph, what can i do to include it in the computational graph or what can I do to solve the problem? Thank you for your reply?
