### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 3, 3, 3], but got 5-dimensional input of size [1, 24, 3, 320, 320] instead

### ISSUE THREAD

**Issue by baoguomalaoshi** [open-mmlab/mmdetection#8246]
I just run command like this:
python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py             or
python tools/train.py configs/ssd/ssdlite_mobilenetv2_scratch_600e_coco.py
and got a traceback as follow
**Error traceback**
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 3, 3, 3], but got 5-dimensional input of size [1, 24, 3, 320, 320] instead
the error was in the first layer of backbone.The data can't pass down in the first layer.

**Comment by RangiLyu** [comment]
Did you modify the config or the code? Could you provide more detailed information?

**Comment by BIGWangYuDong** [comment]
Feel free to re-open this issue if you still meet this problem

**Comment by huangfuhuijie** [comment]
After a whole afternoon wondering why this happened, and after code check carefully, i still wonder why there is an additional dimension in training data and how this goes wrong suddenly.
Until i found command nvidia-smi failed in my machine. After reinstall nvidia driver, everything goes well.
check if your nvidia driver and cuda version if you encounter this problem.
