### ISSUE TITLE
Do you still need to pre-process and normalize the image for converted ONNX?

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#8255]
I've trained the FAster-RCNN model and it was trained with normalization mean and std. 

After the model is converted to ONNX, is it still necessary to normalize the image prior to inference or is the normalization built-in the converted model?

**Comment by RangiLyu** [comment]
You still need to normalize the image. We do not add the normalization node into the ONNX graph by default.
