### ISSUE TITLE
i have question about ./compile.sh

### ISSUE THREAD

**Issue by nuist-xinyu** [open-mmlab/mmdetection#826]
Building roi align op...
running build_ext
building 'roi_align_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/roi_align_cuda.cpp -o build/temp.linux-x86_64-3.7/src/roi_align_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-9.0/bin/nvcc -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/roi_align_kernel.cu -o build/temp.linux-x86_64-3.7/src/roi_align_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_align_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
Building roi pool op...
running build_ext
building 'roi_pool_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/roi_pool_cuda.cpp -o build/temp.linux-x86_64-3.7/src/roi_pool_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-9.0/bin/nvcc -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/roi_pool_kernel.cu -o build/temp.linux-x86_64-3.7/src/roi_pool_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
Building nms op...
Compiling src/soft_nms_cpu.pyx because it changed.
[1/1] Cythonizing src/soft_nms_cpu.pyx
running build_ext
building 'soft_nms_cpu' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/soft_nms_cpu.cpp -o build/temp.linux-x86_64-3.7/src/soft_nms_cpu.o -Wno-unused-function -Wno-write-strings
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/soft_nms_cpu.cpp:643:
/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
src/soft_nms_cpu.cpp: In function ‘PyObject* __pyx_pf_12soft_nms_cpu_soft_nms_cpu(PyObject*, PyArrayObject*, float, unsigned int, float, float)’:
src/soft_nms_cpu.cpp:2498:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
src/soft_nms_cpu.cpp:3009:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
g++ -pthread -shared -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -L/home/xinyu/anaconda3/envs/open-mmlab/lib -Wl,-rpath=/home/xinyu/anaconda3/envs/open-mmlab/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/soft_nms_cpu.o -o /home/xinyu/mmdetection/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
running build_ext
building 'nms_cuda' extension
gcc -pthread -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/nms_cuda.cpp -o build/temp.linux-x86_64-3.7/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-9.0/bin/nvcc -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/nms_kernel.cu -o build/temp.linux-x86_64-3.7/src/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
Building dcn...
running build_ext
building 'deform_conv_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/deform_conv_cuda.cpp -o build/temp.linux-x86_64-3.7/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-9.0/bin/nvcc -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/deform_conv_cuda_kernel.cu -o build/temp.linux-x86_64-3.7/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
Building sigmoid focal loss op...
running build_ext
building 'sigmoid_focal_loss_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/sigmoid_focal_loss.cpp -o build/temp.linux-x86_64-3.7/src/sigmoid_focal_loss.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sigmoid_focal_loss_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/sigmoid_focal_loss.cpp: In function ‘at::Tensor SigmoidFocalLoss_forward(const at::Tensor&, const at::Tensor&, int, float, float)’:
src/sigmoid_focal_loss.cpp:25:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/sigmoid_focal_loss.cpp: In function ‘at::Tensor SigmoidFocalLoss_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, int, float, float)’:
src/sigmoid_focal_loss.cpp:36:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
:/usr/local/cuda-9.0/bin/nvcc -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/sigmoid_focal_loss_cuda.cu -o build/temp.linux-x86_64-3.7/src/sigmoid_focal_loss_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sigmoid_focal_loss_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1
Building masked conv op...
running build_ext
building 'masked_conv2d_cuda' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/xinyu/anaconda3/envs/open-mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/masked_conv2d_cuda.cpp -o build/temp.linux-x86_64-3.7/src/masked_conv2d_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=masked_conv2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
:/usr/local/cuda-9.0/bin/nvcc -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/TH -I/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/include/THC -I:/usr/local/cuda-9.0/include -I/home/xinyu/anaconda3/envs/open-mmlab/include/python3.7m -c src/masked_conv2d_kernel.cu -o build/temp.linux-x86_64-3.7/src/masked_conv2d_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=masked_conv2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute ':/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command ':/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

**Comment by hellock** [comment]
I believe your environment variable is wrong. You can refer to the error log.
