### ISSUE TITLE
`KeyError: 'conv1_w'` When converting from Detectron2 to MMDetection

### ISSUE THREAD

**Issue by justlike-prog** [open-mmlab/mmdetection#8260]
Hi I would like to convert a Detectron2 into a MMDetection model. Running the `detectron2pytorch.py` script leads to an error though,

`python detectron2pytorch.py model_final_f10217.pkl test123.pth 50
Traceback (most recent call last):
  File "detectron2pytorch.py", line 83, in <module>
    main()
  File "detectron2pytorch.py", line 79, in main
    convert(args.src, args.dst, args.depth)
  File "detectron2pytorch.py", line 47, in convert
    convert_conv_fc(blobs, state_dict, 'conv1', 'conv1', converted_names)
  File "detectron2pytorch.py", line 26, in convert_conv_fc
    state_dict[torch_name + '.weight'] = torch.from_numpy(blobs[caffe_name +
KeyError: 'conv1_w'`

**Comment by BIGWangYuDong** [comment]
what checkpoints did you use?

**Comment by kowshikthopalli** [comment]
Hi @BIGWangYuDong is detectron2pytorch.py for converting models trained in original Detectron or Detectron2?
I have trained few object detection models in detectron2. I have recently seen that you include robustness checking as a part of your toolbox. Is there a possibility for me to directly evaluate my detectron2 models for benchmarking for robustness either by converting it to mmdet or other means?
