### ISSUE TITLE
I want to plot the ROC curve，has anyone done that yet? Now only PR curve function.

### ISSUE THREAD

**Issue by Xuchangsheng1** [open-mmlab/mmdetection#8266]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when \[....\].
Ex2. There is a recent paper \[....\], which is very helpful for \[....\].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by Czm369** [comment]
It is not implemented yet, you can try to submit a PR, we will review it as soon as possible.
 Or you can use confusion matrix：
https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/confusion_matrix.py
