### ISSUE TITLE
How to use the GPU fully?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#8268]
Hello! My GPU is 3090ti, i want to use the GPU fully, so how to set the parameter.

**Comment by Czm369** [comment]
Maybe you can set `samples_per_gpu=8`
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/configs/_base_/datasets/coco_detection.py#L32

**Comment by lijoe123** [comment]
@Czm369 so could you please tell me the relationship of batch_size, epoch,  iteration,  and samples_per_gpu? And how to set them?

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/issues/8342
