### ISSUE TITLE
[Feature Request]Official Dockerfile or Docker Images?

### ISSUE THREAD

**Issue by ideaRunner** [open-mmlab/mmdetection#827]
As there is a very simple conda installation command guide: 
https://gist.github.com/hellock/bf23cd7348c727d69d48682cb6909047
It looks very simple to be installed.

But actually I faced some problems:
1. ` conda install -c pytorch pytorch torchvision -y` 
    Very slow network speed as I am in China mainland and conda mirror source is not able to use.
    Sometimes even <10KB/s and interrupt by network error. I installed it several times an it finally success.

2. `gcc` version doesn't match.
    in [install.md](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md) the gcc version must be  `GCC: 4.9/5.3/5.4/7.3`, however the newest version of gcc is above 9.1 at now. 
    I speed some time to install gcc and it‘s dependencies.

All the problem I have solved but it cost me several hours which doesn't make sense and can be saved and improved by a docker mirror and a Dockerfile. 

For example an official base mmdetection image in docker hub, and a editable Dockerfile which we can see how it built and we can install more dependencies from this Dockerfile and docker image.

I have searched in [dockerhub_images](https://hub.docker.com/search/?q=mmdetection&type=image) but found the quality is low even cannot to use.

I would like something like 
https://github.com/facebookresearch/Detectron/blob/master/docker/Dockerfile in Detecron.

Do you have any plan to do this?

**Comment by hellock** [comment]
Thanks for your advice. This is what we have planned to do, but just do not have time to.
Maybe #701 can help, though it is not officially maintained.

**Comment by ideaRunner** [comment]
Yes, thank you for your response.
I found a little way to improve his PR: Reuse pytorch official images.
So It will not need to use pip install the requirements and it is easy to change pytorch version and cuda version by change the base pytorch images.

For example:
```Dockerfile
FROM pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime
 
# Set locale
ENV LANG en_US.UTF-8

# Install torchvision 
conda install torchvision -y

# Install mmdetection
RUN conda install cython -y && \
  git clone https://github.com/open-mmlab/mmdetection.git && \
  cd mmdetection

RUN ./compile.sh && \
  python setup.py develop && \
  mkdir data
```

It looks simpler right?  : )  a copy version of [install.md](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md)
 
Another opinion, don't use `python3` command anymore as python2 will be not supported. 
`python` should be equal to Python3

That is my two suggestion

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile

**Comment by csachs** [comment]
@hellock Thanks for the Dockerfile.
Would it be possible to create official Docker Hub images? It just needs signing up and linking the repository, and Docker Hub will take care of building a new image per commit/tag/release…
