### ISSUE TITLE
Bounding box prediction (x, y) coordinates

### ISSUE THREAD

**Issue by alejopaullier96** [open-mmlab/mmdetection#8275]
After running the [inference_demo](https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/demo/inference_demo.ipynb) I noticed that output predictions consists of arrays of 5 elements. Each element corresponds to: 

`(x_coordinate, y_coordinate, width, height, prob)`. 

However after printing a marker in the image on the `(x_coordinate, y_coordinate)` I noticed the marker was displayed on the **upper left corner**. On [COCO dataset](https://cocodataset.org/#format-results):  "Bounding box coordinates are floats measured from the top left image corner (and are 0-indexed). We recommend rounding coordinates to the nearest tenth of a pixel to reduce resulting JSON file size. A bounding box is described by the pixel coordinate (x_min, y_min) of its **lower left corner** within the image together with its width and height in pixels." 

Is this right?

Thanks

**Comment by PeterVennerstrom** [comment]
Inference bbox output is `(x1, y1, x2, y2, prob)` marking the top left and bottom right of the box.  

This differs from the COCO convention as you described.

**Comment by alejopaullier96** [comment]
Thanks for the answer.

I have realized that they are technically correct assuming you see the image from their axis. If the top left corner of the image has the center of coordinates then the pixel coordinate (x_min, y_min) is lower left corner.  Imaging seeing an image and tilt your head 90 degrees to the right.  Then what we normally consider the upper left corner would then become the lower left corner.

Idk, that's the best explanation I have come up with according to their statement. 🤷🏼

**Comment by mykeysid10** [comment]
@PeterVennerstrom bbox output (x1, y1, x2, y2, prob) indicates marking the bottom left & top right of the box.
