### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'device'

### ISSUE THREAD

**Issue by ccsimp1e** [open-mmlab/mmdetection#8278]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@ccsimp1e Please complete the information, thank you.

**Comment by Hiyao-yy** [comment]
AttributeError: 'ConfigDict' object has no attribute 'device'

**Comment by ModestYjx** [comment]
![image](https://user-images.githubusercontent.com/42560039/183802445-c6b30cd6-a7f7-4016-9122-9fd7e5d5c64d.png)

**Comment by Hiyao-yy** [comment]
谢谢你，以后要常联系哦

**Comment by ModestYjx** [comment]
repo
```
https://github.com/hunto/LightViT         （based on mmdetection）
```

command
```
bash ./dist_train.sh /home/yjxun/code/LightViT/detection/configs/mask_rcnn_lightvit_b
ase_fpn_3x_ms_coco.py 4
```

mmdet version:
```
TorchVision: 0.13.0
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.25.1+e2452a1
```

other log
```
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[27, 33])
runner = dict(type='EpochBasedRunner', max_epochs=36)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
find_unused_parameters = True
total_epochs = 36
work_dir = './work_dirs/mask_rcnn_lightvit_base_fpn_3x_ms_coco'
gpu_ids = range(0, 4)
```

**Comment by ModestYjx** [comment]
In short:
On the basis of LightViT, I use my 'human vehicle non' data set to reduce the number of categories and category names of the coco data set to its subset 'person', 'car', 'motor cycle'. This problem arises.

**Comment by BIGWangYuDong** [comment]
this error occurred here https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/tools/train.py#L201
please update your train.py file before running the code

**Comment by BIGWangYuDong** [comment]
If you still meet the same problem, please feel free to re-open this issue

**Comment by ding19980201** [comment]
@BIGWangYuDong  dear sir ，what does update your train.py mean i still can not fix even i add cfg.device='cuda'
