### ISSUE TITLE
The problem of package SDK

### ISSUE THREAD

**Issue by linquanxu** [open-mmlab/mmdetection#828]
hi,Thank you for contributing such a great project. I want to use mmdetection to package SDK(such 
 as .dll, .so etc.) for detecting, how to finish it?

**Comment by hellock** [comment]
Sorry we cannot offer help on it.

**Comment by linquanxu** [comment]
thank you for your reply. @hellock

**Comment by linquanxu** [comment]
hi,  @hellock ，I have another question is whether mmdetection models can be converted to CAFFE2 models.

**Comment by hellock** [comment]
We have not tried that, but it should be similar to other pytorch models with custom cuda extensions.

**Comment by linquanxu** [comment]
thanks @hellock
