### ISSUE TITLE
How to parse more parameters to custom loss fuction?

### ISSUE THREAD

**Issue by ImmortalSdm** [open-mmlab/mmdetection#8282]
I'm trying to parse more parameters to my custom loss fuction, instead of only 'pred, target'. But i don't know where to change. Any ideas?

**Comment by RangiLyu** [comment]
You can modify the loss module in `mmdet/models/losses`, and pass more parameters when you call these loss in the `loss` method of the detection head in `mmdet/models/dense_heads` or `mmdet/models/roi_heads`

**Comment by ImmortalSdm** [comment]
> You can modify the loss module in `mmdet/models/losses`, and pass more parameters when you call these loss in the `loss` method of the detection head in `mmdet/models/dense_heads` or `mmdet/models/roi_heads`

Thanks for your advise.
