### ISSUE TITLE
How to get loss,acc in code?

### ISSUE THREAD

**Issue by jacob-kang** [open-mmlab/mmdetection#8283]
Hello mmdet!

I want to map mmdetection to Neptune AI.
And I need some information which is loss, acc, loss_cls etc. of log file.
I've tried to find where those numbers come from and where the code is. But I failed finding.

Where can I get the numbers from code?
There must be resulting function or..... something

Thanks.
kind regards.

**Comment by jacob-kang** [comment]
It might not deliver my question. XD.
I just found `losses` in standard_roi_head.py.
And `losses` contains loss_cls, acc, loss_bbox.

I wonder where is it returned toward??
That code area where the losses be returned is what I want to know.

Thanks.

**Comment by RangiLyu** [comment]
We already support NeptuneAI logger, you can refer to  https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/neptune.py

To use the NeptuneAI logger, just modify the config `configs/_base_/default_runtime.py`
```
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='NeptuneLoggerHook')
    ])
```

**Comment by jacob-kang** [comment]
Thanks!
I think, It would be useful to describe 'How to use Neptune AI in mmdetection' in docs.
