### ISSUE TITLE
Get stuck when import mmcv before import torch.

### ISSUE THREAD

**Issue by Bruce-Si** [open-mmlab/mmdetection#8284]
I have installed the environment successfully, but when I run any script, I get stuck if `import mmcv` before `import torch`. After reversed these two line it works well. I want to know why this happend?  Thank you.
The environemt is:
```
Ubuntu: 18.04
python: 3.7.13
cuda: 10.2
mmcv-full==1.4.8,
torch==1.9.0
```

**Comment by RangiLyu** [comment]
Duplicated with https://github.com/open-mmlab/mmcv/issues/2086
