### ISSUE TITLE
Error in inference of Panoptic Segmentation in mmdetection 2.19

### ISSUE THREAD

**Issue by austin1900** [open-mmlab/mmdetection#8287]
When I perform Panoptic Segmentation with the following code, I encounter the following error：

Code:
config_file = './panoptic_fpn_r50_fpn_1x_coco.py'
checkpoint_file = './epoch_12.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = './data/coco/test2017/000000121758.jpg'
result = inference_detector(model, img)
model.show_result(img, result, out_file='./results/result.jpg', score_thr=0.5)

Error:
UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
Traceback (most recent call last):
  File "./tools/single_inference.py", line 66, in <module>
    model.show_result(img, result, out_file='./results/result.jpg', score_thr=0.5)
  File "/data/zhouzz1/mmdetection_2.19/mmdet/models/detectors/base.py", line 323, in show_result
    for i, bbox in enumerate(bbox_result)
  File "/data/zhouzz1/mmdetection_2.19/mmdet/models/detectors/base.py", line 323, in <listcomp>
    for i, bbox in enumerate(bbox_result)
AttributeError: 'str' object has no attribute 'shape'

**Comment by chhluo** [comment]
See https://github.com/open-mmlab/mmdetection/issues/8292#issuecomment-1173094464
