### ISSUE TITLE
Wrong gt to bbox assignment  in max_iou_assigner (assign_wrt_overlaps) for zero overlaps.

### ISSUE THREAD

**Issue by beckerio** [open-mmlab/mmdetection#8289]
Wrong gt to bbox assignment  in max_iou_assigner  (assign_wrt_overlaps/ match_low_quality==True) for zero overlaps.

In case a gt_max_overlaps  value is zero,  all proposals are wrongly assigned to a ground truth box.
 max_iou_inds = overlaps[i, :] == gt_max_overlaps[i]

add condition for preventing 
if gt_max_overlaps[i] > 0:
                            assigned_gt_inds[max_iou_inds] = i + 1

Best

**Comment by BIGWangYuDong** [comment]
did not get your points, more details are needed

**Comment by beckerio** [comment]
Overlaps stores the IoU values between gt bounding boxes and predicted bounding boxes.

In order to assign the gt indices of all prediction, the overlaps values are compared against the max overlaps values.
In case gt_max_overlaps or gt_max_overlaps gt_max_overlaps[i] are/is zero, all (zero valued) overlaps are equal to the gt_max_overlap value.
Accordingly, all max_iou_inds are set to True, although there is no overlap.

I am not sure why gt_max_overlaps can sometimes result with only zeros, but this results in wrong positve assigned gt indices.  In contrast to the pos_inds assignment before the max_low_quality conditions, no max overlaps threshold is applied.   
I hope, this helps.

**Comment by BIGWangYuDong** [comment]
I probably understand what you mean, but the situation you said is too special, and there are also min_pos constraints, so I guess min_pos can be adjusted appropriately to avoid the situation you said?

**Comment by beckerio** [comment]
Not sure if the min_pos constraints really prevents this from happening. Nevertheless, the problem is special and for most users not critical. In my case , including a guard helped.
