### ISSUE TITLE
运行DW代码出现RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation 

### ISSUE THREAD

**Issue by sharp-xiang** [open-mmlab/mmdetection#8292]
错误类型：![image](https://user-images.githubusercontent.com/84016975/177003838-0dfe8592-b4b9-42f4-8a89-41f4d310a81f.png)
环境：
![image](https://user-images.githubusercontent.com/84016975/177003865-bee61ddd-8f7d-43d0-9ffd-69790bf5f56e.png)

**Comment by chhluo** [comment]
Some ops in the model are not supported in pytorch 1.10+. It's okay with pytorch 1.9.
Also you can fix it, please refer to https://github.com/open-mmlab/mmdetection/issues/8221.
By the way, what is DW?

**Comment by sharp-xiang** [comment]
> 
![image](https://user-images.githubusercontent.com/84016975/177030816-26c8bbd8-1367-4b1e-90c9-1467ec601939.png)
我把pytorch降低到1.9.0 又出现这个错误了 
DW是A Dual Weighting Label Assignment Scheme for Object Detection

**Comment by chhluo** [comment]
mmcv-full is not installed properly.

**Comment by austin1900** [comment]
Sorry to disturb you. I want to use mmdetection 2.19 to perform panoptic segmentation on a single image, but the following error occurs. The code and error reports are as follows：

Code:
config_file = './panoptic_fpn_r50_fpn_1x_coco.py'
checkpoint_file = './epoch_12.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = './data/coco/test2017/000000121758.jpg'
result = inference_detector(model, img)
model.show_result(img, result, out_file='./results/result.jpg', score_thr=0.5)

Error:
UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
'data pipeline in your config file.', UserWarning)
Traceback (most recent call last):
File "./tools/single_inference.py", line 66, in
model.show_result(img, result, out_file='./results/result.jpg', score_thr=0.5)
File "/data/zhouzz1/mmdetection_2.19/mmdet/models/detectors/base.py", line 323, in show_result
for i, bbox in enumerate(bbox_result)
File "/data/zhouzz1/mmdetection_2.19/mmdet/models/detectors/base.py", line 323, in
for i, bbox in enumerate(bbox_result)
AttributeError: 'str' object has no attribute 'shape'.

What should I do to perform panoptic segmentation of the image？Thanks

**Comment by austin1900** [comment]
> mmcv-full is not installed properly.

Sorry to disturb you. I want to use mmdetection 2.19 to perform panoptic segmentation on a single image, but the following error occurs. The code and error reports are as follows：

Code:
config_file = './panoptic_fpn_r50_fpn_1x_coco.py'
checkpoint_file = './epoch_12.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img = './data/coco/test2017/000000121758.jpg'
result = inference_detector(model, img)
model.show_result(img, result, out_file='./results/result.jpg', score_thr=0.5)

Error:
UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
'data pipeline in your config file.', UserWarning)
Traceback (most recent call last):
File "./tools/single_inference.py", line 66, in
model.show_result(img, result, out_file='./results/result.jpg', score_thr=0.5)
File "/data/zhouzz1/mmdetection_2.19/mmdet/models/detectors/base.py", line 323, in show_result
for i, bbox in enumerate(bbox_result)
File "/data/zhouzz1/mmdetection_2.19/mmdet/models/detectors/base.py", line 323, in
for i, bbox in enumerate(bbox_result)
AttributeError: 'str' object has no attribute 'shape'.

What should I do to perform panoptic segmentation of the image？Thanks

**Comment by chhluo** [comment]
There is a script to do inference on single image in mmdet v2.25.0, https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py.

you can checkout to the lastest master branch with git.

```
git fetch origin -v
git checkout v2.25.0
```

**Comment by austin1900** [comment]
> @austin1900 There is a script to do inference on single image in mmdet v2.25.0, https://github.com/open-mmlab/mmdetection/blob/master/demo/image_demo.py.
> 
> you can checkout to the lastest master branch with git.
> 
> ```
> git fetch origin -v
> git checkout v2.25.0
> ```

Hear me say thank you for warming the seasons with you.

**Comment by sharp-xiang** [comment]
> mmcv-full is not installed properly.

感谢你的回复和帮助  一开始使用的 pip install mmcv--full所以报错 后面改成mim install mmcv--full
也希望我的问题能帮助后来者
