### ISSUE TITLE
Could FCOS-based detector use softmax classifier?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#8293]
Actually, I don't know why most one stage detectors use sigmoid classifier even though COCO is a multi-classification task. Do you have a more reasonable explanation？I'm really confused about it. And could FCOS-based detector use softmax classifier? I'm applying FCOS-based detector to logo detection ( the num of categories could be 1000). But I get many false positives at the same position(with different categories). I think this might be the reason for using the sigmoid classifier(instead of softmax classifier).
![alfaromeo5](https://user-images.githubusercontent.com/26771037/177004282-c929a86d-bcac-4a0e-9f8a-ed517e5dbe71.jpg)

**Comment by chhluo** [comment]
You can set a high value for confidence score https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py#L58 to filter those false positive bboxes.

**Comment by Icecream-blue-sky** [comment]
> You can set a high value for confidence score
> 
> https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py#L58
> 
> to filter those false positive bboxes.

The AP drops when I set a high confidence score.

**Comment by chhluo** [comment]
Yes, Ap drops with a high score. There is a trade off between false positive and AP. Please try to different confidence score and find the one with acceptable AP and false positive rate.
