### ISSUE TITLE
Towards Open World Object Detection ？

### ISSUE THREAD

**Issue by wwwbq** [open-mmlab/mmdetection#8297]
请问目前有计划复现这篇cvpr2021工作的吗

**Comment by ZwwWayne** [comment]
Recently, we do not have plans to support this paper. Seems that the community cannot fully reproduce the results.

**Comment by zhongqiu1245** [comment]
> Recently, we do not have plans to support this paper. Seems that the community cannot fully reproduce the results.

Hello, could you release the PR about Towards Open World Object Detection?
