### ISSUE TITLE
processing speed

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#8298]
You mentioned here that the processing speed of mask RCNN can reach 16fps. But when I try to detect the images obtained by the camera, I find that the speed of outputting the detection results is extremely slow. Close to 2fps (even if wait_time=0.1 is modified). Is there any other way to improve the processing speed of mask RCNN in the image obtained by the camera?

**Comment by Czm369** [comment]
Maybe you can speed up mask RCNN by MMDeploy
https://github.com/open-mmlab/mmdeploy
