### ISSUE TITLE
How to mark only the ’person‘ label in the video？thanks

### ISSUE THREAD

**Issue by zhaowuyao** [open-mmlab/mmdetection#83]

**Comment by hellock** [comment]
Could you give more specific descriptions on this question?

**Comment by zhaowuyao** [comment]
I just want to mark the label about people in the image，Other object labels do not display.

**Comment by hellock** [comment]
`person` is the first class in COCO labels. If you mean the visualization, you can simply modify the `show_result` method in detectors to ignore other classes. Otherwise you can obtain the results and only use the first class for further purposes.

**Comment by Curry1201** [comment]
Hi @zhaowuyao, I want to know in which code do you specifically modify show_result to mark only the "person" tag? Can you tell me about this?

**Comment by zhaowuyao** [comment]
I modified many points,but it did not work

**Comment by hellock** [comment]
I though this issue should have been addressed by the comment above. Feel free to reopen it if there are any further questions.

**Comment by martian1231** [comment]
> I modified many points,but it did not work

Here is the code for those who are searching for the same.

`new_label = []
new_bboxes = []
new_segm_result = []

# select only "person" labels
for idx, label in enumerate(labels):
  # '0 is for "person" class'
  if label == 0:
    new_label.append(0)
    new_bboxes.append(bboxes[idx])
    if segm_result is not None and len(labels) > 0:
      new_segm_result.append(segms[idx])

labels = np.array(new_label)
bboxes = np.array(new_bboxes)
if new_segm_result:
  segms = np.array(new_segm_result)`

add these line just before calling "imshow_det_bboxes" in file "base.py" located at "mmdetection\mmdet\models\detectors". Here is what it should look like:
![image](https://user-images.githubusercontent.com/52612816/106358450-490c7580-6332-11eb-9ca9-85f568d68e97.png)
