### ISSUE TITLE
How to suppress log messages in log file when evaluating?

### ISSUE THREAD

**Issue by patrolli** [open-mmlab/mmdetection#8300]
I'm new to use mmdetection. I sucessfully run my custom dataset with standard models. However, I found my log file is filled with printed progress bar line, which makes me hard to find usefule messages from log. So my question is how to disable this progress bar in the code?

![image](https://user-images.githubusercontent.com/25717445/177099120-4bddbd97-a7d9-4689-8ac7-df8ba411db05.png)

**Comment by Czm369** [comment]
The code is at https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/mmdet/apis/test.py#L105
but it seems not to provide a closed flag, maybe you can delete some code.
