### ISSUE TITLE
Usage of centerness branch.

### ISSUE THREAD

**Issue by austin1900** [open-mmlab/mmdetection#8306]
In ATSS model, where is the output value of the centerness branch called during inference?
In the inference process of ATSS, the final predicted value should be: score*centerness, but I can't find the file where this process is implemented.
Could you help me to point out where this process is implemented? Thanks

**Comment by PeterVennerstrom** [comment]
The ATSS head inherits AnchorHead which inherits [BaseDenseHead](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/base_dense_head.py).  The BaseDenseHead handles score*centerness.  Centerness is called score_factors in BaseDenseHead.

**Comment by austin1900** [comment]
Thank you very much for your guidance!
