### ISSUE TITLE
why the ssd has roi_shape

### ISSUE THREAD

**Issue by andeyeluguo** [open-mmlab/mmdetection#832]
I run the ssd module and print the img_metas in the forward_train function. What confuses me is that the img_metas has roi_shape......
(Pdb) img_metas
[{'ori_shape': (241, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.30864197, 0.8196721 , 0.30864197, 0.8196721 ], dtype=float32), 'flip': False}, {'ori_shape': (425, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.6651885, 0.7614213, 0.6651885, 0.7614213], dtype=float32), 'flip': True}, {'ori_shape': (480, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.28846154, 0.20661157, 0.28846154, 0.20661157], dtype=float32), 'flip': False}, {'ori_shape': (479, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.46875  , 0.6263048, 0.46875  , 0.6263048], dtype=float32), 'flip': False}, {'ori_shape': (375, 500, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.20120725, 0.26833633, 0.20120725, 0.26833633], dtype=float32), 'flip': False}, {'ori_shape': (480, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.86455333, 0.65217394, 0.86455333, 0.65217394], dtype=float32), 'flip': False}, {'ori_shape': (427, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.30612245, 0.2570694 , 0.30612245, 0.2570694 ], dtype=float32), 'flip': False}, {'ori_shape': (344, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.19582245, 0.36452004, 0.19582245, 0.36452004], dtype=float32), 'flip': True}]

**Comment by andeyeluguo** [comment]
is the roi_shape is the original shape of image? And then it resized to the img_shape(300,300)？
I am also wondering what the scale_factor means。。。The scale_factor has three values. As a new user for the mmdetection, what is the best way to know the meaning of some value in code?

**Comment by hellock** [comment]
It is `ori_shape`, not roi_shape, and it means the original shape of the image.
`scale_factor` has 4 values instead of 3 values, which is [w_scale, h_scale, w_scale, h_scale]. You may refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/transforms.py#L37).
We are improving the documentation.

**Comment by andeyeluguo** [comment]
you are right, I am blind. But {'ori_shape': (241, 640, 3), 'img_shape': (300, 300, 3), 'pad_shape': (300, 300, 3), 'scale_factor': array([0.30864197, 0.8196721 , 0.30864197, 0.8196721 ], dtype=float32), 'flip': False}
300/241 is not 0.3086 or 0.8196, how does it compute?

**Comment by hellock** [comment]
[here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L208-L217) and [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L242).
