### ISSUE TITLE
How to  set dynamic match cost during the training process?

### ISSUE THREAD

**Issue by exiawsh** [open-mmlab/mmdetection#8334]
Hello, if I want to make the regression cost of the bounding box gradually increase during the training process, how could I do it?
That's mean How could I get the current and total num of epochs during the training process and calculate  the regression cost when match the sample and predictions.

**Comment by chhluo** [comment]
The iteration and epoch information are in the runner https://github.com/open-mmlab/mmcv/blob/f4167fe1e3d106cd641708d269ddbff568393437/mmcv/runner/base_runner.py#L131,
and https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py

You can pass the information into model, them pass them to the match cost.
