### ISSUE TITLE
where is pafpn.py?

### ISSUE THREAD

**Issue by ujsyehao** [open-mmlab/mmdetection#834]
In TECHNICAL_DETAILS.md, 
`1. create a new file in mmdet/models/necks/pafpn.py`.
But I cannot find pafpn.py in mmdet/models/necks directory.

**Comment by hellock** [comment]
This is just a guide about how to develop your own components.
Please refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#develop-new-components) since TECHNICAL_DETAILS is quite outdated now.

**Comment by ujsyehao** [comment]
@hellock Thank you for your reply. I ignore `create a new file`.
I just started using mmdetection, it is a nice detection framework!
I asked the issue#830, I think you should add `python3 setup.py build_ext --inplace in mmdet/ops/* direcory` in INSTALL.md.

**Comment by hellock** [comment]
It is already in `compile.sh`.

**Comment by ujsyehao** [comment]
Maybe I first execute compile.sh failure, But I didn't notice it, I just noticed setup.py failure.
