### ISSUE TITLE
could you please tell me the relationship of batch_size, epoch, iteration, and samples_per_gpu? And how to set them?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#8342]
could you please tell me the relationship of batch_size, epoch, iteration, and samples_per_gpu? And how to set them?

**Comment by Leon-Brant** [comment]
I think there must be a calculation method between the values such as batch_size, epoch and Iteration.  I am also interested in this calculation method. Looking forward to an official reply!

**Comment by BIGWangYuDong** [comment]
In mmdet, 
samples per gpu * GPUs = batch size
epoch is training epoch, that you are setting
total_iteration per epoch = total_sample / batch_size
