### ISSUE TITLE
Code location for calculating mask IOU

### ISSUE THREAD

**Issue by kankanzheli** [open-mmlab/mmdetection#8344]
Where does your code calculate mask IOU. Because I want to know how you transform the annotation data in the coco dataset and the result obtained by mmdetection into the same type of data.

**Comment by Czm369** [comment]
https://github.com/open-mmlab/mmdetection/blob/d81990802cbd80f6d49fc35cdd255ebc353e4541/mmdet/datasets/coco.py#L386
