### ISSUE TITLE
 How do I change the name displayed on the masked object?

### ISSUE THREAD

**Issue by dohyeonYoon** [open-mmlab/mmdetection#8345]
hello
I inference with coins using mask-rcnn.

here is my code

    `img_name = path_dir + '/' + file_list[i]
    img_arr= cv2.imread(img_name, cv2.IMREAD_COLOR)
    img_arr_rgb = cv2.cvtColor(img_arr, cv2.COLOR_BGR2RGB)
    fig= plt.figure(figsize=(12, 12))
    plt.imshow(img_arr_rgb)
    
            
    results = inference_detector(model, img_arr)
    
    ##save result
    model.show_result(img_arr, results, score_thr=0.8, title=  bbox_color=(0,0,255),thickness=0.5,font_size=7, out_file= f'{save_dir1}{file_list[i]}')
`
 
What I am curious about is that
I want to change the name of the bounding box
I want to assign random variables instead of class name and confidence score.

How can I do this?

Do I have to change mmdetection/mmdet/apis/inference.py/inference_detector function? or show_result_pyplot function?

I would be very grateful if you could give me example code.

thank you
![image](https://user-images.githubusercontent.com/66056440/178220999-35a781fd-ad80-4000-9c8d-2d1eea46467d.png)

**Comment by dohyeonYoon** [comment]
I want to put the variable value in my code into the title.

**Comment by Czm369** [comment]
The name of the bounding box depends on https://github.com/open-mmlab/mmdetection/blob/d81990802cbd80f6d49fc35cdd255ebc353e4541/mmdet/datasets/coco.py#L25
