### ISSUE TITLE
DeformableDETR+ResNext+noncal_block error?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#8349]
I do some refine in the deformable-detr like this: but it occur some error
![2](https://user-images.githubusercontent.com/86214036/178396738-0779436c-5e17-4d44-8218-d1c3b8b0a8a3.jpg)
![1](https://user-images.githubusercontent.com/86214036/178396770-36280691-89f3-4c1d-9c05-d034f4d70f62.jpg)
![3](https://user-images.githubusercontent.com/86214036/178396780-6c2c016d-15dc-4afe-9654-9a37ba1c5e87.jpg)
![error](https://user-images.githubusercontent.com/86214036/178396798-e5646bb9-d67e-4d9f-8f13-97711e8b8441.jpg)

**Comment by RangiLyu** [comment]
outputs of the backbone is 4 levels' feature maps, but the ChannelMapper's `in_channels` only has 3 levels.

**Comment by lijoe123** [comment]
@RangiLyu so how can i use Resnext to replace Resnet in the Deformable DETR? Could you please give me a demo?

**Comment by hhaAndroid** [comment]
@lijoe123 Modify the `in_channels` parameter of `ChannelMapper` so that it can also receive 4 inputs
