### ISSUE TITLE
Inconsistent ROI Pooling results from PyTorch

### ISSUE THREAD

**Issue by farleylai** [open-mmlab/mmdetection#835]
It seems like the ROI Pooling is done differently from PyTorch's implementation.
Here is a minimal sample code to test:

```
import numpy as np
import torch as th
from torch import nn
from torchvision.ops import roi_pool as roipool_pth
from mmdet.ops import roi_pool as roipool_mm

dev = th.device(0)
img = th.rand(1, 3, 720, 1280).to(dev)
feats = th.rand(1, 1, img.shape[-2] // 16, img.shape[-1] // 16).to(dev)
output_size = (3, 3)
rois = th.Tensor([
    [0, 11, 19, 40, 31], 
    [0, 10, 11, 71, 17], 
]).to(dev)

fh, fw = list(feats.shape)[-2:]
h, w = list(img.shape)[-2:]
scales = (fw/w, fh/h)
print(f"img: {tuple(img.shape)}, feats: {tuple(feats.shape)}, scales: {tuple(scales)}")
print(f"rois: {rois.tolist()}")

with th.no_grad():
    res_pth = roipool_pth(feats, rois, output_size, sum(scales) / 2)
    res_mm  = roipool_mm(feats, rois, output_size, sum(scales) / 2)

print(f"th:{res_pth.squeeze()}")
print(f"mm:{res_mm.squeeze()}")
```

Both roi_pool implementations compute different results as follows:
```
img: (1, 3, 720, 1280), feats: (1, 1, 45, 80), scales: (0.0625, 0.0625)
rois: [[0.0, 11.0, 19.0, 40.0, 31.0], [0.0, 10.0, 11.0, 71.0, 17.0]]
th:tensor([[[0.2396, 0.4171, 0.3229],
         [0.5441, 0.5225, 0.3229],
         [0.5441, 0.5225, 0.1398]],

        [[0.4171, 0.4171, 0.8178],
         [0.4171, 0.4171, 0.8178],
         [0.4171, 0.4171, 0.8178]]], device='cuda:0')
mm:tensor([[[0.6127, 0.2396, 0.4171],
         [0.6127, 0.2396, 0.4171],
         [0.6127, 0.2396, 0.4171]],

        [[0.9671, 0.9350, 0.9350],
         [0.9671, 0.9350, 0.9350],
         [0.9671, 0.9350, 0.9350]]], device='cuda:0')
```
Any justifications for the inconsistence?

**Comment by hellock** [comment]
Yes the implementation of RoI Pooling and RoI Align is different and it's intended. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/ops/roi_pool/src/roi_pool_kernel.cu#L35-L36) for details.
This is a historical issue. We have tested two versions and the performance is almost the same.

**Comment by farleylai** [comment]
I know RoI Align is to address the boundary/rounding issues of RoI Pooling but here I am just comparing RoI pooling between different implementations to figure out the rationale behind the difference.

After reviewing the CUDA code of both, it seems like PyTorch rounds the scaled RoI coordinates first while mmdet keeps float types until later floor/ceil. I also compare with the original author's repo ([caffe-fast-rcnn](https://github.com/rbgirshick/caffe-fast-rcnn/blob/bcd9b4eadc7d8fbc433aeefd564e82ec63aaf69c/src/caffe/layers/roi_pooling_layer.cu)) and found that is exactly what PyTorch's implementation is based on. 

So it turns out that mmdet's version deviates from the original author's a bit though I do think your version also makes sense. However, if it is necessary to validate the output of some derived work based RoI pooling, the numerical difference may induce unexpected confusion.

**Comment by hellock** [comment]
Thanks for your followups.
I meant that the implementations of both RoI Pooling and RoI Align are different from torchvision. When we were implementing RoI Pooling/Align, we also considered [Position Sensitive RoI Pooling](https://github.com/msracver/Deformable-ConvNets/blob/master/faster_rcnn/operator_cxx/psroi_pooling.cu) in R-FCN, which is different from the original implementation like in torchvision.

Since we have released around 200 models trained with our own RoI Align implementation, it is expensive to migrate to the official version and we need to retrain all these models.
I agree with you that it is necessary to have the same implementation as the official version. Maybe keeping both is a feasible solution. Do you have any other suggestions?

**Comment by farleylai** [comment]
I agree retraining all the models could be very expensive.
Maybe just a distinct name or some caveat would be sufficient?

**Comment by hellock** [comment]
Does adding two more ops named `RoIPoolOfficial` and `RoIAlignOfficial` sounds reasonable?

**Comment by farleylai** [comment]
Sounds good. Or something like RoIPoolMM if you may implement other related roi pooling methods in the future?

**Comment by hellock** [comment]
Naming current implementation as `RoIPool` can spare the efforts to update existing config files.
It would be great if you'd like to create a PR to add them.

**Comment by hellock** [comment]
Hi @farleylai, are you interested in adding the operators? I can do that if you happen to be unavailable now.

**Comment by farleylai** [comment]
Sorry, I got a bit busy over the week. For now, I am thinking it's actually some configuration of RoIPooling variants. Maybe you can create a configuration option for this and make it default to your RoIPooling implementation to ensure the consistence with all the trained models but still allow the user to change to the original one or even others in the future if the user needs to reproduce the numerical results. What do you think?

**Comment by goolhanrry** [comment]
Hi @farleylai @hellock ! Thanks a lot for your detailed description of the inconsistency between different versions of ROIPooling and ROIAlign. May I ask that which version would have better performance? It seems that the mmdet version is the same as in [detectron2](https://github.com/facebookresearch/detectron2/blob/master/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu) and works better than in torchvision.

**Comment by hellock** [comment]
@goolhanrry Setting `use_torchvision` to True or False should have similar performance. BTW, mmdet, torchvision, detectron2 versions are all different, although they can be compatible by setting some parameters.

**Comment by goolhanrry** [comment]
> @goolhanrry Setting `use_torchvision` to True or False should have similar performance. BTW, mmdet, torchvision, detectron2 versions are all different, although they can be compatible by setting some parameters.

Thank you so much! I'll take further look on their source code :)
