### ISSUE TITLE
How to quantize a mmdet model with MQBench

### ISSUE THREAD

**Issue by hych2020** [open-mmlab/mmdetection#8350]
**Describe the feature**

**Motivation**
I want to quantize mmdet model with MQBench 

**Related resources**
MQBench repo:  https://github.com/ModelTC/MQBench

**Additional context**
I try to quantize a mmdet model with MQBench but failed, It seems that there has some problems when tracing the model

#### code
```
from mqbench.prepare_by_platform import prepare_by_platform, BackendType
qmodel = prepare_by_platform(model, BackendType.Tensorrt)
```
#### error
![图片](https://user-images.githubusercontent.com/108866107/178431651-71aafc80-cf38-4ca8-863e-1f4addee80a0.png)

**Comment by hhaAndroid** [comment]
@hych2020 Sorry, no support for now. But we plan to support it in https://github.com/open-mmlab/mmrazor, welcome to pay attention.
