### ISSUE TITLE
there's no train information

### ISSUE THREAD

**Issue by dgl547437235** [open-mmlab/mmdetection#8351]
![image](https://user-images.githubusercontent.com/31400928/178495110-e8196b40-ed44-4546-83a5-7d83b6e43e08.png)
hello,如图，我使用了自制的labelme数据转成的数据，使用mmdetection训练的时候发现只有保存模型的信息输出，没有损失相关的信息输出，我debug进源码发现每个epoch都有损失，但不知道为什么没有打印出来，求解惑

**Comment by BIGWangYuDong** [comment]
it is default print log every 50 iters, maybe you can change the iter to 10 to get logs

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/configs/_base_/default_runtime.py#L3-L4
