### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

### ISSUE THREAD

**Issue by WangYuze1** [open-mmlab/mmdetection#8352]
![image](https://user-images.githubusercontent.com/83161073/178509128-1dff70f4-f044-486e-97d8-74aaa22f1596.png)

Help!!
how to solve this proplem!

**Comment by hehongjie** [comment]
same error

**Comment by hehongjie** [comment]
Problem solved by checking and modifying annotation files.
