### ISSUE TITLE
Heatmap question?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#8360]
Hello! Could you please tell me how to get the heatmap

**Comment by lijoe123** [comment]
@jbwang1997 thank you. I had saw the web (https://github.com/open-mmlab/mmdetection/pull/7987) you proposed. But my demo/ don't have the vis_cam.py

**Comment by jbwang1997** [comment]
It still a developing feature and hadn't been merged into master branch, you can checkout to this branch and try this feature.
