### ISSUE TITLE
How to see augmented images& 

### ISSUE THREAD

**Issue by Travvy88** [open-mmlab/mmdetection#8366]
I want to train network on my data using completed config, how I can see what images after augmentation in training pipeline?

**Comment by Tamiku** [comment]
There is a browse_dataset.py file in tools/misc. You can use `python tools/misc/browse_dataset  {Your config} ` to view your images after augmentation.

**Comment by Travvy88** [comment]
Thank you!

**Comment by sibet-lb** [comment]
@RangiLyu @Tamiku How can I view an annotated image without enhancement?

**Comment by DominikFilipiak** [comment]
> @RangiLyu @Tamiku How can I view an annotated image without enhancement?

[Here](https://mmdetection.readthedocs.io/en/latest/user_guides/visualization.html) you have an example
