### ISSUE TITLE
VOC的评价指标mAP@.5:.95

### ISSUE THREAD

**Issue by dapiaoGe** [open-mmlab/mmdetection#8367]
您好，请问如果训练用mmdetection训练VOC数据集，怎样才能得到mAP@.5:.95这个指标的结果呢？期待您的回复谢谢

**Comment by RangiLyu** [comment]
You can use https://github.com/open-mmlab/mmdetection/blob/master/tools/dataset_converters/pascal_voc.py to convert VOC dataset to COCO format. And then you can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712_cocofmt.py to train and evaluate the dataset with COCO's mAP@.5:.95 metric.

**Comment by dapiaoGe** [comment]
ok,thanks

**Comment by dapiaoGe** [comment]
> You can use https://github.com/open-mmlab/mmdetection/blob/master/tools/dataset_converters/pascal_voc.py to convert VOC dataset to COCO format. And then you can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712_cocofmt.py to train and evaluate the dataset with COCO's mAP@.5:.95 metric.

**Comment by dapiaoGe** [comment]
> You can use https://github.com/open-mmlab/mmdetection/blob/master/tools/dataset_converters/pascal_voc.py to convert VOC dataset to COCO format. And then you can refer to https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712_cocofmt.py to train and evaluate the dataset with COCO's mAP@.5:.95 metric.

ok,thanks
