### ISSUE TITLE
The error of FileNotFoundError is reported after customizing the dataset class

### ISSUE THREAD

**Issue by zhenbangW** [open-mmlab/mmdetection#8371]
**Describe the bug**

Because my dataset format is a little special, I need to inherit the customdataset class and rewrite load_ Annotations and get_ ann_ Info method, and then FileNotFoundError will be reported during training: '/tmp/tmplidaiclf/tmpy0ftodzt Py 'error. I'm not sure what's wrong? Is there any special registration method or my code is wrong?

**Reproduction**

1. What command or script did you run?
Here is my config file. my_dataset  is the customdataset class that I inherited and rewritten
_base_ = [
  './mmdet/datasets/my_dataset.py',
  './configs/_base_/models/cascade_rcnn_r50_fpn.py',
  './configs/_base_/schedules/schedule_1x.py',
  './configs/_base_/default_runtime.py'
]

data = dict(
  train = dict(
    type = 'MyDataset',
    ann_file = '/data/home/scv6924/mmdetection-master/mmdetection-master/work_dirs/dataset/train',
    img_prefix = '/data/home/scv6924/mmdetection-master/mmdetection-master/work_dirs/dataset/train',
    classes = ('rare','rareAft','build'),
  ),
  val = dict(
    type = 'MyDataset',
    ann_file = '/data/home/scv6924/mmdetection-master/mmdetection-master/work_dirs/dataset/val',
    img_prefix = '/data/home/scv6924/mmdetection-master/mmdetection-master/work_dirs/dataset/val',
    classes = ('rare','rareAft','build'),
  ),
  test = dict(
    type = 'MyDataset',
    ann_file = '/data/home/scv6924/mmdetection-master/mmdetection-master/work_dirs/dataset/test',
    img_prefix = '/data/home/scv6924/mmdetection-master/mmdetection-master/work_dirs/dataset/test',
    classes = ('rare','rareAft','build'),
  ),
)

here is my my_dataset.py
@DATASETS.register_module()
class MyDataset(CustomDataset):
    def __init__(self,
                 min_size=None,
                 img_subdir='JPEGImages',
                 ann_subdir='Annotations',
                 **kwargs):
        assert self.CLASSES or kwargs.get(
            'classes', None), 'CLASSES in `XMLDataset` can not be None.'
        self.img_subdir = img_subdir
        self.ann_subdir = ann_subdir
        super(MyDataset, self).__init__(**kwargs)
        self.cat2label = {cat: i for i, cat in enumerate(self.CLASSES)}
        self.min_size = min_size

    def load_annotations(self, ann_file):
       
        data_infos = []
        # img_ids = mmcv.list_from_file(ann_file)
        img_ids = os.listdir(ann_file)
        print(ann_file,"ann_file")
        # img_ids = mmcv.list_from_file(ann_file)
        for img_id in img_ids:
            img_id   = img_id.split('.')[0]
            file_path = osp.join(self.img_subdir, img_id + '.txt')
            f = open(file_path, encoding='utf-8')
            temp = f.readline().split()

            filename = temp[0]
            # if len(temp) > 1:
            #   xml_path = f.split()[1:]
            data_infos.append(
                dict(id=img_id, filename=filename, width=320, height=320))
            f.close()
        return data_infos

    def _filter_imgs(self, min_size=32):
        """Filter images too small or without annotation."""
        valid_inds = []
        for i, img_info in enumerate(self.data_infos):
            if min(img_info['width'], img_info['height']) < 2:
                continue
            
            else:
                valid_inds.append(i)
        return valid_inds

    def get_ann_info(self, idx):
       
        img_id = self.data_infos[idx]['id']
        file_path = osp.join(self.img_prefix, img_id + '.txt')
        f = open(file_path, encoding='utf-8')
        temp = f.readline().split()

        bboxes = []
        labels = []
        bboxes_ignore = []
        labels_ignore = []

        if len(temp) > 1:
          box = f.readline().split()[1:]
        
          for i in box:
            temp_box = list(map(int, i.split(',')))
            bbox     = temp_box[0:4]
            label    = temp_box[4]
            bboxes.append(bbox)
            labels.append(label)
       
        if not bboxes:
            bboxes = np.zeros((0, 4))
            labels = np.zeros((0, ))
        else:
            bboxes = np.array(bboxes, ndmin=2) - 1
            labels = np.array(labels)
        if not bboxes_ignore:
            bboxes_ignore = np.zeros((0, 4))
            labels_ignore = np.zeros((0, ))
        else:
            bboxes_ignore = np.array(bboxes_ignore, ndmin=2) - 1
            labels_ignore = np.array(labels_ignore)
        ann = dict(
            bboxes=bboxes.astype(np.float32),
            labels=labels.astype(np.int64),
            bboxes_ignore=bboxes_ignore.astype(np.float32),
            labels_ignore=labels_ignore.astype(np.int64))
        return ann

**Comment by chhluo** [comment]
Please provide the full traceback information.

**Comment by chhluo** [comment]
```python
_base_ = [
'./mmdet/datasets/my_dataset.py', # This is not right.
'./configs/base/models/cascade_rcnn_r50_fpn.py',
'./configs/base/schedules/schedule_1x.py',
'./configs/base/default_runtime.py'
]
```
'./mmdet/datasets/my_dataset.py' should not be added in `_base_`. Please refer to https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html

**Comment by zhenbangW** [comment]
This problem has been solved, thank you
