### ISSUE TITLE
ImportError: libavcodec, error 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#8373]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?
this happens when i try any function in mmdetection, such as:
```
python mmdet/utils/collect_env.py
```
and 
```
python tools/train.py configs/HuMda/lad_r50_paa_r101_fpn_coco_1x_4.py

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?
my custom dataset which has same format to coco dataset
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
i got same error
3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
ImportError: libavcodec-65fa80df.so.58.134.100: cannot open shared object file: No such file or directory
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by chhluo** [comment]
It's related to ffmpeg which is required by opencv.  There may be something wrong with the installation of opencv.

**Comment by alaa-shubbak** [comment]
okay, so i shall try to reinstall opencv ,and try again with my training comands?

**Comment by alaa-shubbak** [comment]
I try to reinstall opencv , but it gives me same error and some downloads are not working ..what shall I do?

**Comment by chhluo** [comment]
https://github.com/jabelone/OpenCV-for-Pi/issues/10 this may helps.

**Comment by alaa-shubbak** [comment]
Thank you , I try there work , but still get the same problem. 
I still get the same error. 

![error mmdetection i can not ](https://user-images.githubusercontent.com/10245810/179418674-02015283-c7bc-4ee2-b684-460a93bcb60d.jpg)


I try to downgrade the ffmpeg from version 4.3 to version 2.8.6 but i don't know how to achieve that

**Comment by alaa-shubbak** [comment]
please notice that , in the basic env, i have downloaded the opencv2 and it is working, while in my openmmlab envi, i try to download it in same way ,and it does not work and give me an error as bellow. 

![opencv2 problem](https://user-images.githubusercontent.com/10245810/179429186-1b1873e2-b4de-4e98-ba35-fe02c85916f0.jpg)


any help or suggestion?

**Comment by chhluo** [comment]
opencv is installed in base, but not installed in openmmlab.
