### ISSUE TITLE
How to perform semantic segmentation with semantic_head?

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#8374]
Hi, @chhluo @BIGWangYuDong 

By adding semantic_head, we can introduce semantic segmentation tasks at training time, however there seems to be no tutorial and config that let us output semantic segmentation results at test time as well?

Update:
I found an [closed PR](https://github.com/open-mmlab/mmdetection/pull/4969), but it did not get pulled.

**Comment by BIGWangYuDong** [comment]
Sorry for the late reply, we will update docs and other important think ASAP
