### ISSUE TITLE
A question about comment in `mask2former_head`

### ISSUE THREAD

**Issue by pixeli99** [open-mmlab/mmdetection#8377]
Hi,

Maybe the `shape` here should be `(batch_size, num_queries, c)`?
https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/mmdet/models/dense_heads/mask2former_head.py#L331

**Comment by BIGWangYuDong** [comment]
@chhluo

**Comment by chhluo** [comment]
@pixeli99 yes, you are right. I will update it later.
