### ISSUE TITLE
How to test new set of images

### ISSUE THREAD

**Issue by ibrahim1611** [open-mmlab/mmdetection#8378]
I am running test.py after training the model. However, when issuing the following command it says test.json is required. 

python tools/test.py configs/_base_/default_runtime.py work_dirs/default_runtime/epoch_50.pth --show-dir work_dirs/result

My question is how can we run new images (that don't have any ground truth boxes) using the test.py file 

PS: I already tested images that contain their corresponding bounding boxes.

**Comment by BIGWangYuDong** [comment]
you should not use configs in \_base\_, you need use full config file
