### ISSUE TITLE
what is difference role of  between MaskTransform and SegMapTransform

### ISSUE THREAD

**Issue by andeyeluguo** [open-mmlab/mmdetection#838]
I don't understand why there are two transform: MaskTransfrom and SegMapTransform.  As far as I know,  the mask and the segmap is the same thing.

**Comment by andeyeluguo** [comment]
The config file has no with_seg usage example， so you just use the instance mask.

**Comment by hellock** [comment]
SegMapTransform is designed for the full-image segmentation maps, e.g., COCO-Stuff.
[Here](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_r50_fpn_20e.py) is an example you may refer to.
