### ISSUE TITLE
IndexError: Caught IndexError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by ChristopherCao** [open-mmlab/mmdetection#8380]
I tried to implement mmdet v2.0 with Swin Transformer backbone to detect 1 class of shale oil lands. After modifying the basic configs and paths and build my own dataset from COCO dataset, there is a rarely happening problem that stuck me.
![截屏2022-07-19 上午11 13 30](https://user-images.githubusercontent.com/48756688/179656573-44c09c28-84fa-4d6d-a4af-68e22135cb87.png)
In this project, I am sure that the annotations and training and validation images are correct, using COCO annotation. This problem really confuses me a lot. Hope someone else could help me out, thanks a lot!

**Comment by BIGWangYuDong** [comment]
seems this is an annotation error, please check whether your annotation is correct.
