### ISSUE TITLE
Instance segmentation, mask,predicting how to crop pictures

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#8382]
Identified object

To crop

Height and width depend on the size of the object

Background white

![111](https://user-images.githubusercontent.com/6490927/179661581-3bd69852-0a29-4c46-b30d-0c08e6e8a266.png)

**Comment by BIGWangYuDong** [comment]
mmdet did not support this, but I think maybe you can use the mask image to deal with the original image. because usually mask image is tensor.bool(or np.bool) and the image size is same as original image
