### ISSUE TITLE
Is there a Open MMLab package for Anomaly Detection in Computer Vision?

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#8386]
Hi all,

is there a Open MMLab package that supports methods such as Google's [CutPaste](https://arxiv.org/abs/2104.04015)?

https://github.com/LilitYolyan/CutPaste

Today there are a lot of Anomaly Detection models for Computer Vision, and these are extremely useful in the Manufacturing sector, where images are abundant, but labels are **very** scarce. Do you have any package that can support methods such as CutPaste, or do you plan to create one?

**Comment by hhaAndroid** [comment]
@AndreaPi Sorry. We don't have this plan at the moment.

**Comment by AndreaPi** [comment]
Thanks for the answer. Should I close the issue for now?

**Comment by austinmw** [comment]
+1 would also be very interested in visual anomaly detection
