### ISSUE TITLE
Where can I get this checkpoint?

### ISSUE THREAD

**Issue by xiaoyuan0203** [open-mmlab/mmdetection#8390]
https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html

`load_from = 'checkpoints/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth'`

Where can I get this checkpoint?

It seems not mentioned in this doc

**Comment by BIGWangYuDong** [comment]
https://download.openmmlab.com/mmdetection/v2.0/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth
