### ISSUE TITLE
I want to know how to set Epoch and Batch_size, when I train my custom model

### ISSUE THREAD

**Issue by JimXu1989** [open-mmlab/mmdetection#8398]
Hi!
Thanks for the great sharing!
I want to know how to set Epoch and Batch_size, when I train my custom model
I search all the .py file in configs related to my config python file, 
I did not find any word relative to "epoch" or "batch_size"

Thanks a lot!!

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/config.md 

the main codes are in configs/_base_, for example:

https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/configs/_base_/schedules/schedule_1x.py#L11
https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/configs/_base_/datasets/coco_detection.py#L32

**Comment by JimXu1989** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/config.md
> 
> the main codes are in configs/_base_, for example:
> 
> https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/configs/_base_/schedules/schedule_1x.py#L11
> 
> 
> https://github.com/open-mmlab/mmdetection/blob/56e42e72cdf516bebb676e586f408b98f854d84c/configs/_base_/datasets/coco_detection.py#L32

Thanks

**Comment by GuJasper** [comment]
I'm encountering a problem that the epoch always show [50/15033] whatever I modified it
