### ISSUE TITLE
cannot import name 'roi_align_cuda'

### ISSUE THREAD

**Issue by qiangruoyu** [open-mmlab/mmdetection#84]
I want to run a demo,but I meet an error.
my code is just one line。
python tools/train.py configs/faster_rcnn_r50_fpn_1x.py --gpus 1 --validate
why？
Did I not install it successfully?

**Comment by hellock** [comment]
Have you successfully compiled the extensions and is there any error message? You may refer to [installation guide](https://github.com/open-mmlab/mmdetection#install-mmdetection) for details.

**Comment by qiangruoyu** [comment]
which version of gcc do you use?

**Comment by hellock** [comment]
We have tested gcc 5.4 and 5.3 with PyTorch installed with conda and gcc 4.8 with PyTorch built from source.

**Comment by qiangruoyu** [comment]
@hellock Thanks.I find I install pytorch twice。I uninstall and install pytorch  again。It succeeded。
