### ISSUE TITLE
Question about Multi Training Scales

### ISSUE THREAD

**Issue by VectorYoung** [open-mmlab/mmdetection#840]
Hi, I have some questions about the training scale after reading the technical report.
1. The default training scale is 1333 x 800, so it means resize the shorter edge to 800 without changing the aspect ratio. So 1333 is the upper bound for longger edge?
2. For multi-scale, e.g. 1333 x [640:800:32], it says the longger edge is fixed to 1333 and randomly choose shorter edge from the {640,672,704,736,768,800}. So in this case the aspect ratio will be changed? If yes, why not just resize the shorter edge to the random scale and keep the ratio, just like the single scale?

**Comment by hellock** [comment]
1. Yes, 1333 is the upper bound of the longer edge and 800 is the upper bound of the shorter edge.
2. "fixed to 1333" means the upper bound of the longer edge is always 1333, and the aspect ratio is unchanged.

**Comment by vadik6666** [comment]
@hellock 
When I try  
```
img_scale=[(1333, 800), (1333, 480)] 
multiscale_mode='range'
```
instead of 
`img_scale=[(1333, 800)]`
Speed din't change, but I got two times more GPU memory consumption - ~10Gb vs ~5Gb on my own dataset similar to COCO.
Is it ok?
