### ISSUE TITLE
Mixup, Cutmix augmentation in the hook?

### ISSUE THREAD

**Issue by author31** [open-mmlab/mmdetection#8403]
**Describe the feature**
Mixup, Cutmix augmentations are executed inside the training loop through the hook mechanism (before_train_iter)
Is that a good idea to implement this kind of augmentations inside the training loop without the need to wrap with a MultiImageMixDataset?

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. Without wrapping the dataset with MultiImageMixDataset
`custom_imports = dict(imports=['mmcls.models', 'mmdet.core.hook.mixup_hook'], allow_failed_imports=False)
custom_hooks=[dict(type='MixupHook', alpha=0.4)]`
overriding the before_train_iter in order to implement the mixup augmentation.
``` 
def before_train_iter(self, runner):
      data_batch = runner.data_batch
      xb = self._get_data(data_batch)
      mixed_xb = self.mixup(xb)
      runner.data_batch['img'].data[0]=mixed_xb
```

**Comment by hhaAndroid** [comment]
@author31 `MultiImageMixDataset` is really not very easy to use, we have plans to refactor it in mmdet 3.0.

**Comment by author31** [comment]
Hi! thanks for your response. Should I make a pull request for my implementation?

**Comment by ccomkhj** [comment]
> @author31 `MultiImageMixDataset` is really not very easy to use, we have plans to refactor it in mmdet 3.0.

any plan in mmdet?
