### ISSUE TITLE
How to achieve multi-model result fusion?

### ISSUE THREAD

**Issue by yaofanji** [open-mmlab/mmdetection#8405]
![6P3{Y0FVN~ SAUHQ@HKPBLR](https://user-images.githubusercontent.com/94046113/180296437-216a4fe5-2fba-48cb-8b21-0e4e28f58749.png)

How to implement a similar fusion model, you can train two models at the same time, thank you very much for your answer

**Comment by RangiLyu** [comment]
Maybe you can implement a new Detector class that has two models inside it. Also, you need to overwrite the `forward_train` and `simple_test` methods.
