### ISSUE TITLE
About the section 5.2 of the tech report 

### ISSUE THREAD

**Issue by LightToYang** [open-mmlab/mmdetection#842]
First, thank you for the exellent project.

In Section5.2, the extensive studies of Normalization layers are presented. however, only two-stage detectors like mask-rcnn are evaluted. How about the one-stage detectors like retinanet and ssd, would these detectors be benefitted more from SBN or GN ?

**Comment by hellock** [comment]
GN or SBN can improve almost all models. You may refer to [FCOS](https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/README.md) results.

**Comment by LightToYang** [comment]
I am sure that the detectors can gain the improvement from GN or SBN. I am just curious whether the one-stage methods can gain more AP from  GN or SBN than the two-stage methods.

**Comment by hellock** [comment]
According to my experience, the gain from GN/SBN of RetinaNet is comparable to or smaller than two-stage detectors. I have not tried other single-stage detectors.
