### ISSUE TITLE
Is it possible to run mmdetection without a NVIDIA GPU?

### ISSUE THREAD

**Issue by kalpazidis** [open-mmlab/mmdetection#8422]
I have an AMD GPU and when I am trying to python setup.py develop I get the OSError: CUDA is required to compile MMDetection! error. I have installed the cuda toolkit and I can see it in the conda list. So my question is, if there is any way to run mmdetection with my current hardware. I am sorry if my question is stupid and thank you in advance for your help.

**Comment by BIGWangYuDong** [comment]
similar issue: https://github.com/open-mmlab/mmdetection/issues/6311
I think if you have installed mmcv successfully, you can install mmdet without any error.

**Comment by yxxxxxhh111** [comment]
I met same question!How can I solve it?

**Comment by yxxxxxhh111** [comment]
I met same question!How can I solve it?
