### ISSUE TITLE
Convert mmdet into open-world?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#8429]
Hello, dear authors!
Is it possible to convert mmdet into an open world object detector?(like 《Towards Open World Object Detection》or 《Learning Open-World Object Proposals without Learning to Classify》)
Thank you！

**Comment by BIGWangYuDong** [comment]
I think that mmdet can support open-world object detection, but we don't have plans to support it recently. PRs are welcome to support open-world detector

**Comment by zhongqiu1245** [comment]
Thank you!
