### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by jiangxiaoyan** [open-mmlab/mmdetection#843]
Run `python tools/train.py configs/mask_rcnn_r50_fpn_1x.py`
And It shows:
![image](https://user-images.githubusercontent.com/29242090/59907366-7ea26a80-943d-11e9-9877-555912123ddc.png)

Does anyone meet this problem? And the environment is:
```
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
Python 3.6.7
Torch 1.2.0.dev20190617
```

**Comment by jiangxiaoyan** [comment]
The problem has been fixed after re-installing torch 1.1.0

**Comment by zimenglan-sysu-512** [comment]
i meet this problem by torch-1.2.0.dev

**Comment by hellock** [comment]
Please refer to #1160

**Comment by zimenglan-sysu-512** [comment]
it works !!! thanks.

btw, when i test the model `configs/mask_rcnn_r50_fpn_1x.py` from model zoo, i meet this problem
```
Traceback (most recent call last):
  File "tools/test.py", line 14, in <module>
    from mmdet.core import coco_eval, results2json, wrap_fp16_model
ImportError: cannot import name wrap_fp16_model
```

any help is appreciated.

**Comment by hellock** [comment]
@zimenglan-sysu-512 I cannot reproduce this error.

**Comment by zimenglan-sysu-512** [comment]
i make a mistake, i should use python3.6 instead of python.
sorry.
