### ISSUE TITLE
class_agnostic nms in rpn

### ISSUE THREAD

**Issue by christinaionescu** [open-mmlab/mmdetection#8432]
Hi!

We train a instance segmentation network for multiple classes. For testing I found out that I need to set the **nms** to `class_agnostic=True` in order to perform nms among classes. This worked fine.
However, what about the nms during training in `rpn_proposal`? Here, I could also set `class_agnostic=True` but what does this mean in case of RPN? In my understanding the RPN only differentiates between object/no object and does not consider classes.
What would you recommend?

In our use case the Object Masks cannot overlap, however the bounding boxes could overlap partially.

Thank you!
Best regards

**Comment by BIGWangYuDong** [comment]
The rpn set fake labels according to feature map levels

**Comment by BIGWangYuDong** [comment]
you can find details at https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/models/dense_heads/rpn_head.py#L180-L183
