### ISSUE TITLE
pytorch2onnx has  unsupport type: numpy.ndarray

### ISSUE THREAD

**Issue by azongjie** [open-mmlab/mmdetection#8438]
when run pytorch2onnx, show that "Only tuples, Lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray". what should i do?

**Comment by jbwang1997** [comment]
We are guaranteed some modes can be transformed to ONNX by pytorch2onnx.py. The model list can refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/pytorch2onnx.md#list-of-supported-models-exportable-to-onnx). For more general feature, you can try [mmdepoly](https://github.com/open-mmlab/mmdeploy).
