### ISSUE TITLE
Testing speed is influenced by the total imgs?

### ISSUE THREAD

**Issue by ll490187880** [open-mmlab/mmdetection#844]
Testing HTC with 16gpus in two nodes(--gres=gpu:8 --ntasks=16 --ntasks-per-node=8):
with 4K imgs loaded, the speed is about 20 task/s
but with 100K imgs loaded, the speed is about 11 task/s
Why the speed is influenced by the total imgs?

**Comment by hellock** [comment]
The inference time includes all preparing time including data and annotation loading. I guess there maybe two reasons. 1. Loading annotations of 100k images is slow, which happens at the beginning of the testing.  2. The multiprocessing communication is slower since the queue is larger.
