### ISSUE TITLE
How can i get the AR?

### ISSUE THREAD

**Issue by gzxy-0102** [open-mmlab/mmdetection#8441]
I configured metric as bbox and proposal, but the evaluation method only prints AR parameters, and there are no AR parameters in the returned dict

![image](https://user-images.githubusercontent.com/8954610/181207919-7935946d-ac0e-4827-b417-4f75d10f256e.png)

![image](https://user-images.githubusercontent.com/8954610/181207950-abaf00e3-8d99-4aed-a89d-61630e4b027f.png)

**Comment by jbwang1997** [comment]
Oh, It may be a bug for the `evaluate` function of coco. The metric_items will be set as a not empty list when doing `bbox` evaluation. When doing the `proposal` evaluation, [This code](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L520) will not make effects.

In this situation, you can directly set `metric=['proposal']`. Or, delete the `if metric_items is None:` in  CocoDataset.

**Comment by gzxy-0102** [comment]
> Oh, It may be a bug for the `evaluate` function of coco. The metric_items will be set as a not empty list when doing `bbox` evaluation. When doing the `proposal` evaluation, [This code](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L520) will not make effects.
> 
> In this situation, you can directly set `metric=['proposal']`. Or, delete the `if metric_items is None:` in CocoDataset.

But when I set it to proposal, it will not return AP and bbox_mAP

I need these data
