### ISSUE TITLE
[BUG] With new versions of torch many of model heads needs to be changed like that

### ISSUE THREAD

**Issue by mzillag** [open-mmlab/mmdetection#8443]
> Solov2 head returns the same problem for me. Has anyone fixed that yet?

Yeap, [here](https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/solov2_head.py#:~:text=%2B%3D%20self.-,convs_all_levels,-%5Bi%5D( ) change to `feature_add_all_level = feature_add_all_level + self.convs_all_levels[i](input_p)`

_Originally posted by @mzillag in https://github.com/open-mmlab/mmdetection/issues/7933#issuecomment-1196629481_

**Comment by jbwang1997** [comment]
Thanks for your bug report. We are repairing this bug at #8439
