### ISSUE TITLE
Loading a lot of images as a single sample

### ISSUE THREAD

**Issue by Divadi** [open-mmlab/mmdetection#8449]
Hello, for my application, I need to load perhaps a 100~ images as part of a single sample. I find that the dataloading time of a batch size of 4 samples (each sample 100 images) is much slower (10x) than a batch size of 100 samples (each sample 4 images). Is there any way to speed up the former, perhaps by parallelizing image loading or augmentation within the image loading class (part of the pipeline) itself (as one option)? The images within a single sample are meaningfully related, so 4x100 batch and 100x4 batch are different.

Any guidance would be much appreciated; thank you!

**Comment by jbwang1997** [comment]
If you can convert your images into a more efficient data format like hdf5 or directly load all images into memory?

**Comment by Divadi** [comment]
The # of images are too large in my case unfortunately
