### ISSUE TITLE
How to fine-tune the pre-trained model

### ISSUE THREAD

**Issue by bzha5848** [open-mmlab/mmdetection#8454]
Hi there,

I'm doing some few-shot object detection, which requires me to freeze layers and fine-tune like last couple of layers? Just wondering how can I achieve this in mmdetection with config?

Thanks so much!!

**Comment by RangiLyu** [comment]
You can follow the tutorial https://mmdetection.readthedocs.io/en/latest/tutorials/finetune.html?highlight=finetune#tutorial-7-finetuning-models

And if you want to do few-shot, you can use MMFewshot https://github.com/open-mmlab/mmfewshot

**Comment by ritmininglab** [comment]
The tutorial link does not work anymore, could you share the latest link for that, please?

**Comment by DominikFilipiak** [comment]
@ritmininglab [link to the tutorial](https://mmdetection.readthedocs.io/en/latest/user_guides/finetune.html)
