### ISSUE TITLE
show_result_pyplot() does not plot the mask, only bbox

### ISSUE THREAD

**Issue by Robotatron** [open-mmlab/mmdetection#8456]
In your [tutorial ](https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_InstanceSeg_Tutorial.ipynb)`show_result_pyplot()` shows a mask

However for me it plots only bboxes, although the model I am using is for instance segmentation:
![image](https://user-images.githubusercontent.com/95919873/181837486-232dd532-ec32-4540-800d-4c58e1fdc1b0.png)

Also for some reason the [config ](https://github.com/open-mmlab/mmdetection/blob/master/configs/detectors/detectors_cascade_rcnn_r50_1x_coco.py)located in GitHub differs from the config of the same name that I downloaded with `mim`. Which config is the correct one and why do they differ?
![image](https://user-images.githubusercontent.com/95919873/181837875-66ac1073-330d-4e58-9816-0f5d7bc11473.png)

**Comment by BIGWangYuDong** [comment]
Seems you did not use mask_head in roi_head?
