### ISSUE TITLE
Tensorboard can not show the AR/AP info

### ISSUE THREAD

**Issue by kuangxiaoye** [open-mmlab/mmdetection#8459]
**Describe:training log have the AP/AR info,but that can not show on the tesnorboard.**

Datasets:coco

Model:faster-rcnn

![18081659238532_ pic](https://user-images.githubusercontent.com/43713316/182008793-bd57ac0a-c624-4781-b9d4-c01c6b1c51b2.jpg)

![image](https://user-images.githubusercontent.com/43713316/182008804-45a642a1-d2c8-42e4-ac38-adc3cf055317.png)

Thank you very much for your help！

**Comment by BIGWangYuDong** [comment]
I haven't tried this before, but I think you can set `metric_items` to get other information https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/datasets/coco.py#L621-L626
