### ISSUE TITLE
A question about confidence score in mmdet?(confidence score vs p-values)

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection#8470]
Hi, dear authors!
Thank you for your amazing job!
I have a question about confidence score in mmdet?(confidence score vs p-values)
What is the difference between confidence score and p-value in mmdet?
Why use confidence scores instead of p-values? Which is better or worse?
In the object detection, is the p-value necessary to calculate?
Thank you!

**Comment by hhaAndroid** [comment]
@zhongqiu1245 It seems that p-values are rarely used in the field of object detection, probably because it is not as intuitive as confidence, but I am not sure.
