### ISSUE TITLE
UnicodeDecodeError when using subprocess module

### ISSUE THREAD

**Issue by JCab09** [open-mmlab/mmdetection#8473]
Hello Everyone, 

I'm trying to run mmdetection via subprocess.Popen.

When I use `python D:/mmdetection/tools/train.py C:/Users/jcab/Documents/project/config.py` from the terminal, everything works fine.

However, when I use it like this:
```
import os
from subprocess import Popen

lib_path = 'D:/mmdetection/'
exec_file = os.path.join(lib_path, 'tools', 'train.py')
config_file = 'C:/Users/jcab/Documents/project/config.py'

stderr_log = './log_stderr_train.txt'
stdout_log = './log_stdout_train.txt'

exec_statement = ['python', exec_file, config_file]
with open(stdout_log, "wb") as out, open(stderr_log, "wb") as err:
    process = Popen(exec_statement, stdout=out, stderr=err, encoding="utf-8")
    return_code = process.wait()
```
I get the following error:
```
Traceback (most recent call last):
  File "D:\mmdet\mmdetection\tools\train.py", line 240, in <module>
    main()
  File "D:\mmdet\mmdetection\tools\train.py", line 188, in main
    env_info_dict = collect_env()
  File "c:\users\jcab\documents\mmdetection\mmdet\utils\collect_env.py", line 10, in collect_env
    env_info = collect_base_env()
  File "C:\Users\jcab\Anaconda3\envs\mmdet\lib\site-packages\mmcv\utils\env.py", line 93, in collect_env
    env_info['MSVC'] = cc.decode(encoding).partition('\n')[0].strip()
  File "C:\Users\jcab\Anaconda3\envs\mmdet\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 62: character maps to <undefined>
```
So far I've tried:
- Using different encodings when opening the files and calling Popen
- set `errors='ignore'` when opening the files
- using the codecs module when opening the files, e.g. `codecs.open(...)`

But I just can't get it to work.  Does anyone have a solution for my problem? 
Thanks in advance!

<details>
  <summary>Environment Info</summary>

sys.platform: win32
Python: 3.9.11 (main, Mar 30 2022, 02:45:55) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1660 SUPER
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
NVCC: Cuda compilation tools, release 11.2, V11.2.67
MSVC: Microsoft (R) C/C++-Optimierungscompiler Version 19.27.29111 für x64
GCC: n/a
PyTorch: 1.8.0+cu111
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.9.0+cu111
OpenCV: 4.6.0
MMCV: 1.5.1
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMDetection: 2.25.0+240d7a3
</details>

**Comment by hhaAndroid** [comment]
@JCab09 This seems to be a problem with `mmcv` and `window`, you can go to `mmcv` to create an issue.

**Comment by JCab09** [comment]
As stated here https://github.com/open-mmlab/mmcv/issues/2185#issuecomment-1210770302 this is a bug and will be fixed in the following weeks. 

The current workaround is to comment out this line: 

`C:\Users\jcab\Anaconda3\envs\mmdet\lib\site-packages\mmcv\utils\env.py line93`

I'm closing this issue, since it is not related to mmdetection.

**Comment by duduzai2019** [comment]
> 如此处所述[open-mmlab/mmcv#2185（评论）](https://github.com/open-mmlab/mmcv/issues/2185#issuecomment-1210770302)这是一个错误，`mmcv`将在接下来的几周内修复。
> 
> 当前的解决方法是注释掉这一行：
> 
> `C:\Users\jcab\Anaconda3\envs\mmdet\lib\site-packages\mmcv\utils\env.py line93`
> 
> 我正在关闭这个问题，因为它与 mmdetection 无关。


when i close it , other problem occurred!!!
![image](https://user-images.githubusercontent.com/96464964/185563623-5cf472ab-1646-4a2b-be99-1a2b0fda1c09.png)
