### ISSUE TITLE
Will yolov7 be supported in the future？

### ISSUE THREAD

**Issue by ixxxiu** [open-mmlab/mmdetection#8475]
Yolov7 and yolov5 support higher resolution image input, which is very good. Yolov5 cannot support it because of copyright problems. Will yolov7 be supported in the future？

**Comment by hhaAndroid** [comment]
Yes, yolov5 and yolov7 we will release soon.

**Comment by wqh17101** [comment]
@hhaAndroid Watch out that yolov5 is GPL license which is not a friendly license for users,which will make your project GPL license,too.

**Comment by ixxxiu** [comment]
Coooool！Thank u

**Comment by ahmedanis03** [comment]
> Yes, yolov5 and yolov7 we will release soon.

@hhaAndroid any expected date? or time frame?

**Comment by abcliguanxi** [comment]
@hhaAndroid any expected date? or time frame?

**Comment by Zhengfei-0311** [comment]
任何预计日期？或时间框架？
