### ISSUE TITLE
A typo about function name

### ISSUE THREAD

**Issue by pixeli99** [open-mmlab/mmdetection#8489]
https://github.com/open-mmlab/mmdetection/blob/7646ac48f2ff6b850a3afa6234eabd25e06f7b7d/mmdet/models/dense_heads/mask2former_head.py#L172

Maybe the func name should be `_get_targets_single`?

**Comment by chhluo** [comment]
Yes, better to be `_get_targets_single`

**Comment by RangiLyu** [comment]
We have renamed the function name in v3.x branch.
