### ISSUE TITLE
Result mismatch in cascade-rcnn

### ISSUE THREAD

**Issue by duanduanduanyuchen** [open-mmlab/mmdetection#8497]
I use the config [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py) to train the model and found something unusual. The final bbox_mAP is 35.5 but not 40.3 in the [table](https://github.com/open-mmlab/mmdetection/tree/master/configs/cascade_rcnn#results-and-models). Then I found that the default pre-trained weight of r50 has changed in the new version. New pre-trained weights have a higher top-1 acc in classification(76.130%->80.858%) (check [here](https://pytorch.org/vision/stable/models/generated/torchvision.models.resnet50.html#torchvision.models.ResNet50_Weights)) but caused a worse performance in detection(40.3%->35.5%). When I change the pre-trained weight back to the older one, I finally get 40.3% mAP.

I think the default config should change the link of pre-trained weight to adapt to the new version of torchvision.

Does anyone know the reason why the worse performance was caused by the better pre-trained weights?

**Comment by shinya7y** [comment]
> I think the default config should change the link of pre-trained weight to adapt to the new version of torchvision.

The latest mmcv seems to load old weights for backward compatibility.
https://github.com/open-mmlab/mmcv/pull/1867

**Comment by duanduanduanyuchen** [comment]
Thanks for letting me know that!
