### ISSUE TITLE
About detr and deformal detr

### ISSUE THREAD

**Issue by cxq1** [open-mmlab/mmdetection#8498]
Can DETR or Deformal DETR use the R50-DC5 feature? Some code that is not the MMdetection version can use DC5 by using the parameter 'dilation'

replace stride with dilation in the last convolutional block (DC5)

**Comment by RangiLyu** [comment]
Of course, you can modify the resnet config like this:
```python
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        # ------DC5---------
        strides=(1, 2, 2, 1),
        dilations=(1, 1, 1, 2),
        out_indices=(3, ),
        # --------------------
        frozen_stages=1,
        norm_cfg=norm_cfg,
        norm_eval=True,
```

**Comment by cxq1** [comment]
> Of course, you can modify the resnet config like this:
> 
> ```python
>     backbone=dict(
>         type='ResNet',
>         depth=50,
>         num_stages=4,
>         # ------DC5---------
>         strides=(1, 2, 2, 1),
>         dilations=(1, 1, 1, 2),
>         out_indices=(3, ),
>         # --------------------
>         frozen_stages=1,
>         norm_cfg=norm_cfg,
>         norm_eval=True,
> ```

Thank you for your reply!
