### ISSUE TITLE
How to draw pr curve? Thanks

### ISSUE THREAD

**Issue by guanbin1994** [open-mmlab/mmdetection#85]
I have finished test procedure and get a .pkl file.

If I want to draw a pr curve based on my  .pkl file, what should I do?
Thanks!

**Comment by hellock** [comment]
There is no exposed api to plot a pr curve, but you can refer to [mean_ap.py](https://github.com/open-mmlab/mmdetection/blob/HEAD/mmdet/core/evaluation/mean_ap.py). Computing the precision and recall is already included.

**Comment by guanbin1994** [comment]
do you have plan to add this api?
