### ISSUE TITLE
Where is the code to tell other rank processes that it is early stopping?

### ISSUE THREAD

**Issue by hoya-cho** [open-mmlab/mmdetection#8502]
I am doing early stopping based on validation loss value or mAP value on multi-GPU.
I receive mAP from rank 0 and store the best ckpt, at this time, I wonder how to recognize the early stopping of the remaining ranks (1,2,3...).

**Comment by BIGWangYuDong** [comment]
Seems at here: 
https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/apis/test.py#L103-L104

https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/apis/test.py#L123-L126
