### ISSUE TITLE
TypeError: <class 'mmcv.utils.config.Config'> is unsupported for json dump 

### ISSUE THREAD

**Issue by hoya-cho** [open-mmlab/mmdetection#8504]
In train_detector(), why "TypeError: <class 'mmcv.utils.config.Config'> is unsupported for json dump " error occurs?

in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta, runner, progress_callback)
    258 elif cfg.load_from:
    259     runner.load_checkpoint(cfg.load_from)
--> 260 runner.run(data_loaders, cfg.workflow)

 in EpochRunner.run(self, data_loaders, workflow, max_epochs, **kwargs)
    136 self.logger.info('Hooks will be executed in the following order:\n%s',
    137                  self.get_hook_info())
    138 self.logger.info('workflow: %s, max: %d epochs', workflow,
    139                  self._max_epochs)
--> 140 self.call_hook('before_run')
    142 while self.epoch < self._max_epochs:
    143     for i, flow in enumerate(workflow):

File /opt/conda/lib/python3.8/site-packages/mmcv/runner/base_runner.py:317, in BaseRunner.call_hook(self, fn_name)
    310 """Call all hooks.
    311 
    312 Args:
    313     fn_name (str): The function name in each hook to be called, such as
    314         "before_train_epoch".
    315 """
    316 for hook in self._hooks:
--> 317     getattr(hook, fn_name)(self)

File /opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/logger/text.py:107, in TextLoggerHook.before_run(self, runner)
    104 self.json_log_path = osp.join(runner.work_dir,
    105                               f'{runner.timestamp}.log.json')
    106 if runner.meta is not None:
--> 107     self._dump_log(runner.meta, runner)

File /opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/logger/text.py:193, in TextLoggerHook._dump_log(self, log_dict, runner)
    191 if runner.rank == 0:
    192     with open(self.json_log_path, 'a+') as f:
--> 193         mmcv.dump(json_log, f, file_format='json')
    194         f.write('\n')

File /opt/conda/lib/python3.8/site-packages/mmcv/fileio/io.py:132, in dump(obj, file, file_format, file_client_args, **kwargs)
    130             file_client.put(f.getvalue(), file)
    131 elif hasattr(file, 'write'):
--> 132     handler.dump_to_fileobj(obj, file, **kwargs)
    133 else:
    134     raise TypeError('"file" must be a filename str or a file-object')

File /opt/conda/lib/python3.8/site-packages/mmcv/fileio/handlers/json_handler.py:32, in JsonHandler.dump_to_fileobj(self, obj, file, **kwargs)
     30 def dump_to_fileobj(self, obj, file, **kwargs):
     31     kwargs.setdefault('default', set_default)
---> 32     json.dump(obj, file, **kwargs)

File /opt/conda/lib/python3.8/json/__init__.py:179, in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    173     iterable = cls(skipkeys=skipkeys, ensure_ascii=ensure_ascii,
    174         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    175         separators=separators,
    176         default=default, sort_keys=sort_keys, **kw).iterencode(obj)
    177 # could accelerate with writelines in some versions of Python, at
    178 # a debuggability cost
--> 179 for chunk in iterable:
    180     fp.write(chunk)

File /opt/conda/lib/python3.8/json/encoder.py:431, in _make_iterencode.<locals>._iterencode(o, _current_indent_level)
    429     yield from _iterencode_list(o, _current_indent_level)
    430 elif isinstance(o, dict):
--> 431     yield from _iterencode_dict(o, _current_indent_level)
    432 else:
    433     if markers is not None:

File /opt/conda/lib/python3.8/json/encoder.py:405, in _make_iterencode.<locals>._iterencode_dict(dct, _current_indent_level)
    403         else:
    404             chunks = _iterencode(value, _current_indent_level)
--> 405         yield from chunks
    406 if newline_indent is not None:
    407     _current_indent_level -= 1

File /opt/conda/lib/python3.8/json/encoder.py:438, in _make_iterencode.<locals>._iterencode(o, _current_indent_level)
    436         raise ValueError("Circular reference detected")
    437     markers[markerid] = o
--> 438 o = _default(o)
    439 yield from _iterencode(o, _current_indent_level)
    440 if markers is not None:

File /opt/conda/lib/python3.8/site-packages/mmcv/fileio/handlers/json_handler.py:22, in set_default(obj)
     20 elif isinstance(obj, np.generic):
     21     return obj.item()
---> 22 raise TypeError(f'{type(obj)} is unsupported for json dump')

TypeError: <class 'mmcv.utils.config.Config'> is unsupported for json dump

**Comment by BIGWangYuDong** [comment]
`r('"file" must be a filename str or a file-object')`
please check your dumped file name
