### ISSUE TITLE
How to customize to save the best-performing model for a particular category of AP instead of the best model for mAP

### ISSUE THREAD

**Issue by hjfdsssdg** [open-mmlab/mmdetection#8506]
Could you help me with the following questions, please?
——————————————————————————————————————————————————————————
How to customize to save the best-performing model for a particular category of AP instead of the best model for mAP

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmcv/blob/bb7106755ec78561152a4273b27298e9c9b76e86/mmcv/runner/hooks/evaluation.py#L34-L41

**Comment by hjfdsssdg** [comment]
> 

Thanks~
