### ISSUE TITLE
How to trace tensor ops in one iteration?

### ISSUE THREAD

**Issue by hbhflw2000** [open-mmlab/mmdetection#851]
Hello,

To better understand how mmdetection works (modules' flow charts), I tried to trace its operations step by step.

However, just as you mentioned in tech details,  it is highly modularized, I found that at each iteration it will just call a batch processor with headers (faster rcnn for example) as input variables. However, I couldn't go deeper to check how the tensor is processed (or transformed) to reach the final result.

Could you give me any advice to trace mmdetection's basic operations on tensors, for example, faster rcnn(I did it using pycharm debug mode)? Thanks in advance for your patience and help.

**Comment by hellock** [comment]
The main pipeline consists of two parts, data preprocessing and network forward.

You can trace the data preprocessing in the specified dataset, mostly in [`prepare_train_img()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/custom.py#L175), and trace the network flow in the forward method of the module, e.g. [`TwoStageDetector.forward_train()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/two_stage.py#L90).

**Comment by hbhflw2000** [comment]
Thank you for your helpful advice! I've looked into these functions and found the information I wanted.
