### ISSUE TITLE
mmdetection version 2.23.0 fitting ability worse than 1.0.0

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdetection#8510]
Hi developers of mmdetection. I am switching my model from version 1.0.0 to version 2.23.0 and I am pretty sure that the neural network models in 1.0.0 and 2.23.0 are the same. The model trained in 1.0.0 fits well with the data and the model trained in 2.23.0 does not fit as well as its counterpart does in 1.0.0. 

So to me, it seems that some regularization technique is added to version 2.23.0?! mmdetection of version 2.23.0 corresponds to pytorch of version 1.11.0 while mmdetection of version 1.0.0 corresponds to pytorch of version 1.4. Is this a mmdetection problem or a pytorch problem? How can I solve this? Really appreciate if some guidance is given. Thank you in advance.

**Comment by chhluo** [comment]
Could you provide some evidence to illustrate that?
