### ISSUE TITLE
Set FocalLoss to DETR

### ISSUE THREAD

**Issue by fabiogeraci** [open-mmlab/mmdetection#8515]
I would like to set and/or change the loss function to FocalLoss, so i looked at the config 

{'cfg_options': {'model.bbox_head.loss_cls.type': 'FocalLoss'}})

but i get the following error
TypeError: DETR: DETRHead: FocalLoss: __init__() got an unexpected keyword argument 'class_weight'

so it seems that the default function is not overwritten.

**Comment by Li-Qingyun** [comment]
@fabiogeraci 
I guess the reason of your error is that you modified the configuration file incorrectly

You might directly change the type 'CrossEntropyLoss' of loss_cls in DETR to 'Focal Loss', but this would cause other parameters not matching the FocalLoss class. For example, FocalLoss.__init__() has not the class_weight parameter but CrossEntropyLoss.__init__() has.

You can refer to [Deformable DETR](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/configs/deformable_detr/deformable_detr_r50_16x2_50e_coco.py#L68-L73) to configure your Focal loss.
```Python
loss_cls=dict(
    type='FocalLoss',
    use_sigmoid=True,
    gamma=2.0,
    alpha=0.25,
    loss_weight=2.0),
```

**Comment by fabiogeraci** [comment]
I understand now, I need to pass all the arguments of the loss_cls. Thank you
