### ISSUE TITLE
docker mmvc hard coded pytorch and cuda version

### ISSUE THREAD

**Issue by antoinefalisse** [open-mmlab/mmdetection#8520]
You might want to consider making [this line](https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile#L21) dependent on the [args](https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile#L1). I had errors when using an image built with `ARG PYTORCH="1.9.0"` and `ARG CUDA="11.1"` while keeping the mmvc install line as is. When changed to `RUN pip install --no-cache-dir mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`, it worked great.

**Comment by Czm369** [comment]
Thanks for your suggestions.
