### ISSUE TITLE
训练中遇到问题

### ISSUE THREAD

**Issue by zhaoguoqing12** [open-mmlab/mmdetection#8521]
loss_mask: 0.0084, loss: 0.9420
2022-08-09 12:50:19,608 - mmdet - INFO - Epoch [1][1812/1950]   lr: 1.000e-04, eta: 17:07:52, time: 2.203, data_time: 0.733, memory: 17367, loss_rpn_cls: 0.2027, loss_rpn_bbox: 0.0440, loss_cls: 0.2284, acc: 91.6016, loss_bbox: 0.2649, loss_mask: 0.0194, loss: 0.7595
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 20277) of binary: /local_data/li/anaconda3/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=19997
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_21195b1e/none__bsqzk__/attempt_1/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_21195b1e/none__bsqzk__/attempt_1/1/error.json

**Comment by hhaAndroid** [comment]
@zhaoguoqing12 Sorry.  Little information is provided, and it's hard to tell what the problem is.
