### ISSUE TITLE
 Is there a fixed maximum number of objects that can be detected?

### ISSUE THREAD

**Issue by dohyeonYoon** [open-mmlab/mmdetection#8522]
Hello sir,

When I instance segmenting a house from a satellite image using the Mask R-CNN model, only 100 objects are always detected.

At least 200 houses are shown in the photo, and most of the photos are similar.

**Is there a maximum number of detectable objects in the Mask R-CNN parameter?**

thank you

**Comment by Li-Qingyun** [comment]
@dohyeonYoon 

I think it was set [here](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/configs/_base_/models/mask_rcnn_r50_fpn.py#L110-L120) in `model.test_cfg.rcnn`.
```Python3
test_cfg=dict(
    rpn=dict(
        nms_pre=1000,
        max_per_img=1000,
        nms=dict(type='nms', iou_threshold=0.7),
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.5),
        max_per_img=100,  # the maximum number of detectable objects
        mask_thr_binary=0.5)))
```

You can append options on your command to modify it like:
`python tools/test.py config.py checkpoint.pth --options model.test_cfg.rcnn.max_per_img=500`

**Comment by dohyeonYoon** [comment]
> @dohyeonYoon
> 
> I think it was set [here](https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/configs/_base_/models/mask_rcnn_r50_fpn.py#L110-L120) in `model.test_cfg.rcnn`.
> 
> ```python
> test_cfg=dict(
>     rpn=dict(
>         nms_pre=1000,
>         max_per_img=1000,
>         nms=dict(type='nms', iou_threshold=0.7),
>         min_bbox_size=0),
>     rcnn=dict(
>         score_thr=0.05,
>         nms=dict(type='nms', iou_threshold=0.5),
>         max_per_img=100,  # the maximum number of detectable objects
>         mask_thr_binary=0.5)))
> ```
> 
> You can append options on your command to modify it like: `python tools/test.py config.py checkpoint.pth --options model.test_cfg.rcnn.max_per_img=500`

Thank you so much I fixed it!!
