### ISSUE TITLE
How to extract feature with Faster RCNN?

### ISSUE THREAD

**Issue by dinhanhx** [open-mmlab/mmdetection#8525]
the following code gives bounding boxes, classes, probabilities of the objects 
```
from mmdet.apis import init_detector, inference_detector

config_file = 'faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco.py'
checkpoint_file = 'faster_rcnn_x101_64x4d_fpn_mstrain_3x_coco_20210524_124528-26c63de6.pth'
model = init_detector(config_file, checkpoint_file, device='cpu')  # or device='cuda:0'
result = inference_detector(model, 'cat.jpg')
```

Now I want to get the feature vectors of each object. Or is there any way that I can partially execute the model? Like this one https://detectron2.readthedocs.io/en/latest/tutorials/models.html#partially-execute-a-model

**Comment by hhaAndroid** [comment]
@dinhanhx There is no good way for now, you can open the source code directly, and then save the desired vector.

**Comment by dinhanhx** [comment]
> you can open the source code directly,

Not sure I have time to read code. However, can you give me a sequence of files that I should follow?
