### ISSUE TITLE
Simple copy paste giving errors during inference

### ISSUE THREAD

**Issue by kailasdayanandan** [open-mmlab/mmdetection#8528]
Inference is not working for Simple Copy Paste config below. 
https://github.com/open-mmlab/mmdetection/tree/master/configs/simple_copy_paste

I have reproduced on a Google Colab below. It is working for other models like detr, mask-rcnn
https://colab.research.google.com/drive/1C3pUiaOnjBRZal98997uXPjpV03c-v0-#scrollTo=0k5_iiBUaviK

@Czm369 @sudz123 @ZwwWayne @Johnson-Wang @BIGWangYuDong @torchmyheart

**Comment by Czm369** [comment]
It seems like the problem of `MMSyncBN`.

**Comment by kailasdayanandan** [comment]
Thanks for finding the root cause. 
Is it possible to have a work around for single gpu.
Can you help me to get it to run on Google Colab.

@Czm369 @sudz123 @ZwwWayne @Johnson-Wang @BIGWangYuDong @torchmyheart

**Comment by Czm369** [comment]
Maybe you can use `SyncBN` to replace `MMSyncBN`.
