### ISSUE TITLE
The loss suddnely change to NAN

### ISSUE THREAD

**Issue by theidealist2** [open-mmlab/mmdetection#8530]
When I change the optimizer configure file with the     
"""
step=[28, 34])
runner = dict(type='EpochBasedRunner', max_epochs=36)
“”“
to 
"""
step=[30, 45])
runner = dict(type='EpochBasedRunner', max_epochs=50)
"""
the loss will change to NAN after the "warmup_iters"
Does the epoch shouldn't set like this?
Please tell me the right way to set it, Thanks.

**Comment by theidealist2** [comment]
But when I set the step and max_epochs to the multiples of their original value(Such as step=(56,68). max_epoch=72 to step=[28, 34], max_epochs=36), It run without NAN.

**Comment by BIGWangYuDong** [comment]
Haven't met this before, seems it will not affect warmup. Maybe you can set a seed to re-try these two configs?
