### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'device'

### ISSUE THREAD

**Issue by PuneetMadan9** [open-mmlab/mmdetection#8535]
I am trying to train a custom dataset for instance segmentation with single class. I am using the Colab notebook provided on github.
Link  https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_InstanceSeg_Tutorial.ipynb
While training a new detector. This command is giving the error.

train_detector(model, datasets, cfg, distributed=False, validate=True)

**Comment by jbwang1997** [comment]
This is a new feature since mmdet2.24 and the Colab tutorial hasn't been updated.
You can try to add this part to the notebook and see if the bug still exists.
```
from mmdet.utils import get_device
cfg.device = get_device()
```

**Comment by LnSCV** [comment]
> This is a new feature since mmdet2.24 and the Colab tutorial hasn't been updated. You can try to add this part to the notebook and see if the bug still exists.
> 
> ```
> from mmdet.utils import get_device
> cfg.device = get_device()
> ```

Solved my problem. Thank you. I installed mmdet==2.25.0 and I put the above two lines of code in the mmdet/apis/train.py file before using cfg.device
 
![image](https://github.com/user-attachments/assets/360e99e3-c873-42f2-ab5d-d06791bf2b07)
