### ISSUE TITLE
Bugs of inference_detector (about NMS) ?

### ISSUE THREAD

**Issue by zhwp** [open-mmlab/mmdetection#8539]
**Describe the bug**
The result of inference_detector contains identical bboxs with differenct class scores. When I use different score threshold, the results are as follows. 

![result1](https://user-images.githubusercontent.com/3414945/184051449-cb5c729a-7cb4-4efc-b09a-e18834f8b9fc.jpg)

![result2](https://user-images.githubusercontent.com/3414945/184051415-33e23074-e4a6-4663-8f26-90fe9e819ebf.jpg)

**Reproduction**

1. What command or script did you run?

```python
import pdb
from mmdet.apis import init_detector, inference_detector

config_file = 'yolov3_mobilenetv2_320_300e_coco.py'
checkpoint_file = 'yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth'
model = init_detector(config_file, checkpoint_file, device='cpu')  # or device='cuda:0'
img = 'catdog.jpg'
result = inference_detector(model, img)
import pdb; pdb.set_trace()
model.show_result(img, result, 0.5, out_file='result2.jpg')

```

**Comment by RangiLyu** [comment]
This is because the NMS we use is class-aware, which only do NMS within the same category.
If you want to use class-agnostic NMS, you can set test_cfg like this:
```python
    test_cfg=dict(
        ...
        nms=dict(type='nms', iou_threshold=0.45, class_agnostic=True),
        ...)
```
