### ISSUE TITLE
我安装了mmdet 打了from mmdet.apis import inference_detector, init_detector 报错ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by zhengxindi1231** [open-mmlab/mmdetection#8540]
我安装了mmcv-full再装mmdet，mmdet环境都按照官网的教程安装完了但一直都有引入不了 inference_detector, init_detector

**Comment by BIGWangYuDong** [comment]
please use the issue template to ask the issue. also please make sure you have successfully installed mmcv-full

**Comment by RangiLyu** [comment]
Try to uninstall mmcv first then reinstall mmcv-full.

**Comment by Alasile** [comment]
最后怎么解决的 我和你一样的问题

**Comment by PeizheZhao** [comment]
+1 how to solve this problem

**Comment by sinopec** [comment]
+1 how to solve this problem

**Comment by Alasile** [comment]
mmcv and pytorch version issues. Check the official pytorch website to see if the correct version is installed. Switching to the correct version can resolve conflicts.



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月18日(星期三) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] 我安装了mmdet 打了from mmdet.apis import inference_detector, init_detector 报错ModuleNotFoundError: No module named 'mmcv._ext' (Issue #8540)





 
+1 how to solve this problem
