### ISSUE TITLE
mmdet复现的TOOD算法比TOOD论文发布的代码推理速度不一致

### ISSUE THREAD

**Issue by qiufeng099** [open-mmlab/mmdetection#8542]
mmdet复现的TOOD算法比TOOD论文发布的代码推理速度不一致，图片大小均为640*480，config为两者代码库默认的。区别基本只有mmdet复现的head和TOOD原论文的head不一样

**Comment by zhaohui-coder** [comment]
@qiufeng099 Do you reproduce TOOD to the accuracy of the paper? I am also trying to reproduce, but the accuracy has not been consistent

**Comment by RangiLyu** [comment]
The original version TOOD often encounters None gradient during backpropagation. We fixed this problem in these two PRs:
https://github.com/open-mmlab/mmdetection/pull/7090 & https://github.com/open-mmlab/mmdetection/pull/7567, which may slow down the inference speed.

**Comment by qiufeng099** [comment]
> @qiufeng099 Do you reproduce TOOD to the accuracy of the paper? I am also trying to reproduce, but the accuracy has not been consistent

我是在自己的数据集上跑的程序，没有跑coco数据集

**Comment by okt7760** [comment]
请问TOOD论文中代码推理速度是多少？
