### ISSUE TITLE
How to trian a VOC datasets?

### ISSUE THREAD

**Issue by wen0618** [open-mmlab/mmdetection#855]

**Comment by yhcao6** [comment]
#841

**Comment by wen0618** [comment]
Sorry for my poor English.
I want to train MyDataset,it's a VOC format,I set 3 folders:Annotations,ImageSets(/Main/..),JEPGImages.
I have changed mmdet folder and so on follow the Internet tutorial.
But I don't know how to modify the config file into VOC format ,for example : faster_rcnn_r50_fpn_1x.py
# dataset settings
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))
I'm sorry for not good at programming.So ask for you help.Thank you very much.

**Comment by LiDaiY** [comment]
There are my changes in cascade_rcnn_x101_64x4d_fpn_1x.py. I modified it according to the 'mmdetection\configs\pascal_voc\faster_rcnn_r50_fpn_1x_voc0712.py'. And it works in my computer. I hope it helps

# dataset settings
dataset_type = 'VOCDataset'
data_root = 'data/VOCdevkit/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=1,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/trainval.txt',
        img_prefix=data_root + 'VOC2007/',
        img_scale=(1000, 600),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        img_scale=(1000, 600),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        img_scale=(1000, 600),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))

**Comment by LiDaiY** [comment]
> Sorry for my poor English.
> I want to train MyDataset,it's a VOC format,I set 3 folders:Annotations,ImageSets(/Main/..),JEPGImages.
> I have changed mmdet folder and so on follow the Internet tutorial.
> But I don't know how to modify the config file into VOC format ,for example : faster_rcnn_r50_fpn_1x.py
> 
> # dataset settings
> dataset_type = 'CocoDataset'
> data_root = 'data/coco/'
> img_norm_cfg = dict(
> mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
> data = dict(
> imgs_per_gpu=2,
> workers_per_gpu=2,
> train=dict(
> type=dataset_type,
> ann_file=data_root + 'annotations/instances_train2017.json',
> img_prefix=data_root + 'train2017/',
> img_scale=(1333, 800),
> img_norm_cfg=img_norm_cfg,
> size_divisor=32,
> flip_ratio=0.5,
> with_mask=False,
> with_crowd=True,
> with_label=True),
> val=dict(
> type=dataset_type,
> ann_file=data_root + 'annotations/instances_val2017.json',
> img_prefix=data_root + 'val2017/',
> img_scale=(1333, 800),
> img_norm_cfg=img_norm_cfg,
> size_divisor=32,
> flip_ratio=0,
> with_mask=False,
> with_crowd=True,
> with_label=True),
> test=dict(
> type=dataset_type,
> ann_file=data_root + 'annotations/instances_val2017.json',
> img_prefix=data_root + 'val2017/',
> img_scale=(1333, 800),
> img_norm_cfg=img_norm_cfg,
> size_divisor=32,
> flip_ratio=0,
> with_mask=False,
> with_label=False,
> test_mode=True))
> I'm sorry for not good at programming.So ask for you help.Thank you very much.

I hope it helps. https://zhuanlan.zhihu.com/p/70545482

**Comment by LiDaiY** [comment]
I hope it helps. https://zhuanlan.zhihu.com/p/70545482
