### ISSUE TITLE
TypeError: 'DataContainer' object is not subscriptable'

### ISSUE THREAD

**Issue by jimuIee** [open-mmlab/mmdetection#8551]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
File "/mnt/home/lzk/Uodac_sonar/mmdet/models/anchor_heads/anchor_head.py", line 272, in get_bboxes
    img_shape = img_metas[img_id]['img_shape']
TypeError: 'DataContainer' object is not subscriptable

**Reproduction**

1. What command or script did you run?
./test_sonar.sh:

#!/bin/bash
export OMP_NUM_THREADS=4
export CUDA_VISIBLE_DEVICES=7 #,1,2,3,4,5,6,7
GPUS=1 #8

    
DIR=work_dirs/cascade_rcnn_dconv_c3-c5_r101_uncertain_MS_dufpn_1x
CONFIG=configs/cascade_rcnn_dconv_c3-c5_r101_uncertain_MS_dufpn_1x.py
./tools/dist_test.sh ${CONFIG} pretrain_model/cascade_rcnn_dconv_c3-c5_r101_uncertain_MS_dufpn_1x_sonar_final.pth 1 --out ${DIR}/bbox_predict.pkl --eval bbox 

2. Did you make any modifications on the code or config? Did you understand what you have modified?
```
# model settings
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained='pretrain_model/cascade_rcnn_dconv_c3-c5_r101_dufpn_1x.pth',
# model training and testing settings

    stage_loss_weights=[1, 0.5, 0.25])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(score_thr=0.001,
              nms=dict(type='soft_nms_variance_voting',
                       sigma_t=0.01, iou_thr=0.5, min_score=0.001,
                      ),     
              return_variance=False,
              max_per_img=80),)
# dataset settings
dataset_type = 'SonarDataset'
data_root = './data/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        ratio_scale=[[0.8, 0.9, 1.0, 1.1, 1.2], # 1.0, 1.1, 1.2, 1.3, 1.4
                     [0.8, 0.9, 1.0, 1.1, 1.2]],
        flip=True,
        ver_flip=True,
        filter_prefix=['gx'],
        transforms=[
            dict(type='AbjointResize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    imgs_per_gpu=1,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        # ann_file=data_root + 'annotation/instances_train.json',
        ann_file=data_root + 'annotation/instances_all.json',
        img_prefix=data_root + 'image/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotation/instances_val.json',
        img_prefix=data_root + 'image/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotation/a-test.json', # b-test
        img_prefix=data_root + 'a-test-img/', # b-test-image
        # ann_file=data_root + 'annotation/instances_val.json',
        # img_prefix=data_root + 'image/',
        pipeline=test_pipeline))

evaluation = dict(interval=4, metric='bbox')
# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=100,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=6)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 12
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/cascade_rcnn_dconv_c3-c5_r101_dufpn_1x'
load_from = 'pretrain_model/cascade_rcnn_dconv_c3-c5_r101_dufpn_1x.pth'
resume_from = None
workflow = [('train', 1)]
```
4. What dataset did you use?
sonardataset
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2
OpenCV: 4.6.0
MMCV: 0.6.0
MMDetection: 1.1.0+8d90765
MMDetection Compiler: GCC 9.4
MMDetection CUDA Compiler: 11.3
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
      conda
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
File "./tools/test.py", line 378, in <module>
    main()
  File "./tools/test.py", line 361, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir,
  File "./tools/test.py", line 65, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/lzk/mydata/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lzk/mydata/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/lzk/mydata/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/base.py", line 139, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/base.py", line 124, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/cascade_rcnn.py", line 417, in aug_test
    proposal_list = self.aug_test_rpn(
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/test_mixins.py", line 41, in aug_test_rpn
    proposal_list = self.simple_test_rpn(x, img_meta, rpn_test_cfg)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/test_mixins.py", line 34, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/anchor_heads/anchor_head.py", line 272, in get_bboxes
    img_shape = img_metas[img_id]['img_shape']
TypeError: 'DataContainer' object is not subscriptable

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by BIGWangYuDong** [comment]
I don't think there are `ratio_scale` in MultiScaleFlipAug, if you change your code, please check whether you have the same logic with the source code
