### ISSUE TITLE
How to choose a model to detect particular set of classes?

### ISSUE THREAD

**Issue by ingaluxemburg** [open-mmlab/mmdetection#8556]
Hi. I'm trying to use mmdetection to detect humans, faces, cars and car license plates! How to find a model from zoo which support this classes?

**Comment by BIGWangYuDong** [comment]
Seems we do not support this classes, but you can follow the tutorials to finetune your model.
finetune:
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/docs/en/tutorials/finetune.md
dataset:
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/docs/en/tutorials/customize_dataset.md
