### ISSUE TITLE
PoseConv3D pseudo heatmap volume

### ISSUE THREAD

**Issue by ahmed-nady** [open-mmlab/mmdetection#8558]
Thanks for your promising work (PoseConv3D). i am wandering  about the reason of stacking pseudo heatmap of joints along temporal dimension instead single image containing all joints for example if we have video clip of length 30 frame, the stacking heatmaps will produce matrix of 17 (num_joints) X 30 X 56 (height) X 56 (width) but putting all joints in single frame produce a matrix of 30X56X56.

**Comment by BIGWangYuDong** [comment]
Seems we do not support PoseConv3D in our official repo, but we are glad to support this method in the future. So right now, maybe you can ask the issue in the author source repo
