### ISSUE TITLE
Expected behavior of YOLOXModeSwitchHook?

### ISSUE THREAD

**Issue by voldemortX** [open-mmlab/mmdetection#8560]
I'm using a custom fork of MMDetection around v2.2x.

I find there is an arg called `num_last_epochs` in YOLOX configs.
https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/configs/yolox/yolox_s_8x8_300e_coco.py#L137

I expect it to mean the exact number of epochs that use L1 loss and no-mosaic training (in this case `15`). However, as shown in the logs, the actual epochs are 16 (15 + 1, [\[285, 300\]](https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254.log.json)). This is rather confusing, e.g., if I set `num_last_epochs=0`, it will still be executed for 1 epoch.

I don't know if this behavior is expected. As far as I know, the mmcv `_epoch` is updated after the execution of hooks, this `+1` should not have happened.

**Comment by shinya7y** [comment]
This issue is discussed in https://github.com/open-mmlab/mmdetection/pull/7322

**Comment by voldemortX** [comment]
@shinya7y Thanks! I didn't find that before.

I'll close this issue and make further discussions in that PR
