### ISSUE TITLE
How to identify the one-to-one correspondence between data and labels in custom pipeline

### ISSUE THREAD

**Issue by childi** [open-mmlab/mmdetection#8566]
I want to write a custom pipeline in mmdet.
so I print all the keys from the input parameter 'input_dict'
but I can't figure out how to determine which labels belong to which image

Let's say the shape of input_dict['gt_bboxes'] is (7, 4), and the shape of input_dict['img'] is (375, 1242, 3)

**Comment by Czm369** [comment]
More details, please.

**Comment by childi** [comment]
Sorry for the unclear expression.
if I want to write a custom pipeline function, I would use the parameter 'input_dict' of the function '__call__'. My question is: Does each input_dict contain only information from one sample? (such as input_dict['img'], input_dict['gt_boxes'])


在自定义的pipeline函数中，输入参数input_dict只是一个样本的信息吗？还是整个batch的信息？
因为在我设置batch_size等于2的时候，打印input_dict['img']的shape显示的是两个(375, 1242, 3) 而不是 (2, 375, 1242, 3)

**Comment by Czm369** [comment]
`input_dict` is just the information of one sample, each sample will pass through the pipeline, then form the batch.

**Comment by childi** [comment]
thank you so much for your kind answer.
