### ISSUE TITLE
about test/inference

### ISSUE THREAD

**Issue by frensher** [open-mmlab/mmdetection#8571]
你们好,我想问下
我只有一堆图片,能够批量进行推理test吗,生成框或者分割效果.没有对应的jsom注释啥的

**Comment by hhaAndroid** [comment]
@frensher You can use the https://github.com/open-mmlab/mmdetection/blob/master/tools/dataset_converters/images2coco.py script to convert to coco format, and then use the test script to keep the prediction results.
