### ISSUE TITLE
voc_datasets

### ISSUE THREAD

**Issue by ceasona** [open-mmlab/mmdetection#8591]
Hello! can I set `self.year = None`? 
![image](https://user-images.githubusercontent.com/37234316/185374972-6884d71e-438d-4795-b2e0-7aa568827a76.png)

**my config**
![image](https://user-images.githubusercontent.com/37234316/185377013-227d0dfe-dae3-4688-94c6-39a00ed21655.png)

**Comment by ceasona** [comment]
`img_prefix `and `ann_file `are same type, list or tuple is also OK. why `raise ValueError('Cannot infer dataset year from img_prefix')`

**Comment by RangiLyu** [comment]
Are you using the official VOC dataset? If you are using a custom xml format dataset, please use `XMLDataset` instead of `VOCDataset`.

**Comment by ceasona** [comment]
Thanks, I got it
