### ISSUE TITLE
very low PQ in the Mask2Former evaluation after 5k training itrations

### ISSUE THREAD

**Issue by susaha** [open-mmlab/mmdetection#8598]
I am training mask2former using 4 gpus,  and 8 gpus. For both the models, I am getting a very low PQ of 1.0 in the mask2former panoptic evaluation on COCO val after 5k training iterations. I am using this config file : https://github.com/open-mmlab/mmdetection/blob/master/configs/mask2former/mask2former_swin-l-p4-w12-384-in21k_lsj_16x1_100e_coco-panoptic.py.

**Comment by BIGWangYuDong** [comment]
Please @chhluo have a look

**Comment by chhluo** [comment]
@susaha  mask2former_swin-l trained with 16 GPUs and batch_size=1, PQ should be 24.31589 at 5k iters. If you trained the model with 4gpus and batch_size=1, then you should compare PQ at 10k iters.

**Comment by susaha** [comment]
@chhluo: thank you for your reply!

**Comment by susaha** [comment]
@chhluo: I have checked the PQ at 20k, and still, it is very low. If I use 4 GPUs and batchsize=1, do I need to change anything in the config? I did not change anything in the default config so far: https://github.com/open-mmlab/mmdetection/blob/master/configs/mask2former/mask2former_swin-l-p4-w12-384-in21k_lsj_16x1_100e_coco-panoptic.py

+--------+-------+-------+-------+------------+
|        | PQ    | SQ    | RQ    | categories |
+--------+-------+-------+-------+------------+
| All    | 1.218 | 2.485 | 1.429 | 133        |
| Things | 0.277 | 0.958 | 0.361 | 80         |
| Stuff  | 2.640 | 4.790 | 3.041 | 53         |
+--------+-------+-------+-------+------------+

**Comment by chhluo** [comment]
For 4 gpu and batch_size = 1, lr need to change to lr / 4. And did you use the pretrained weights of swin-l?

**Comment by susaha** [comment]
- I am using the default setting for auto_scale_lr, i.e., in in my configs/_base_/default_runtime.py, I have : auto_scale_lr = dict(enable=False, base_batch_size=16). Is this correct?
- I have now added the following line to the configs/mask2former/mask2former_swin-l-p4-w12-384-in21k_lsj_16x1_100e_coco-panoptic.py: optimizer = dict(lr=0.0001/4)
- From the training log, it seems I use the following pretrained
[20220820_083839.log](https://github.com/open-mmlab/mmdetection/files/9386787/20220820_083839.log)
 weights:
https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_large_patch4_window12_384_22k.pth
I have attached my old training log for your reference.
Please let me know if these look good.

**Comment by chhluo** [comment]
```
data = dict(samples_per_gpu=1, workers_per_gpu=2)

optimizer = dict(lr=0.0001 / 4)
lr_config = dict(step=[655556 * 4, 710184 * 4])

max_iters = 737500 * 4
runner = dict(max_iters=max_iters)
interval = 5000 * 4
dynamic_intervals = [(max_iters // interval * interval + 1, max_iters)]
evaluation = dict(
    interval=interval,
    dynamic_intervals=dynamic_intervals,
    metric=['PQ', ]) # 'bbox', 'segm' are optional

test_cfg=dict(instance_on=False) # test for instance segmentation is optioal
```

I'm not sure whether it convergences with 4 gpus and batch_size=1.

**Comment by congjianting** [comment]
@susaha  was it been solved?

**Comment by susaha** [comment]
@congjianting : no it is not solved. For a sanity check, I was trying to reproduce the results reported for the mask2former with resent-50 backbone - https://github.com/open-mmlab/mmdetection/tree/master/configs/mask2former#panoptic-segmentation.
I used the provided config: https://download.openmmlab.com/mmdetection/v2.0/mask2former/mask2former_r50_lsj_8x2_50e_coco-panoptic/mask2former_r50_lsj_8x2_50e_coco-panoptic_20220326_224516.log.json and trained the model on 8 GPUs with batch_size=2, i.e., I followed exactly the same setting as given in the config. I still get a very low PQ of 1.0 after 5k training iterations. Here is my training log attached: 
[20220822_014430.log](https://github.com/open-mmlab/mmdetection/files/9397325/20220822_014430.log).
I compared my training log with the one provided by mmdetection (https://download.openmmlab.com/mmdetection/v2.0/mask2former/mask2former_r50_lsj_8x2_50e_coco-panoptic/mask2former_r50_lsj_8x2_50e_coco-panoptic_20220326_224516.log.json), and I found the following:
mmdetection-log: at 5k - PQ=14.3, at 55k - PQ=42.1, my-log: at 5k - PQ=1.0, at 55k - PQ=24.4. I I also observed that, in my log, the total number of validation iteration is 5k, whereas in mmdetection log, it 625 (i.e., 8 * 625 = 5000). So, at the time of validation, mmdetection log shows that the batch_size = 8, but then why in my case the batch_size=1? And why my PQ is low,still not clear to me.

**Comment by chhluo** [comment]
I trained 5k with mmdet v2.25.1. Here is the log,
[20220823_093511.log](https://github.com/open-mmlab/mmdetection/files/9400461/20220823_093511.log)

**Comment by susaha** [comment]
I have downloaded the COCO datasets and annotations from the official website and using it as it is for training and validation. Do I need to preprocess the COCO datasets before training/validation?

**Comment by chhluo** [comment]
@susaha  No extra work needed

**Comment by susaha** [comment]
Does the batch size during validation somehow affect the PQ?

**Comment by chhluo** [comment]
batch_size = 1 during validation by default. `batch_size` in config file only affects training not validation.

**Comment by susaha** [comment]
@chhluo: thanks for sharing the log. I will compare the log files in detail and try to find out if there is any differences. There should not be any difference, though, since I am using the default config provided by "mmdetection," but it is very weird then why I get so low PQ.  I will check and update here soon.

**Comment by susaha** [comment]
I think I found the error. I was reserving 8 gpus on the GPU cluster, but due to the defualt config, it was using only one GPU, because I check my config and the only differences between my config and yours are:
my config: gpu_ids = [0], EvalHook
yours config: gpu_ids = range(0, 8), DistEvalHook.

Another quick question, when to explicitly mention --auto-scale-lr in the command line?

**Comment by susaha** [comment]
How to activate the distributed training? Do I need to pass the --gpu_ids=range(0,8) in the commandline?

**Comment by chhluo** [comment]
Please refer to https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html

**Comment by susaha** [comment]
Thank you! problem resolved!
