### ISSUE TITLE
./Compile.sh ERROR

### ISSUE THREAD

**Issue by hitlgy** [open-mmlab/mmdetection#86]
Hi, When I execute the ./compile.sh script.Here is an error  "command '/usr/local/cuda/lib64/bin/nvcc' failed with exit status 1".
And I don't find the nvcc on my computer path /usr/local/cuda/lib64/bin/nvcc.
But I find nvcc in the " /usr/local/cuda/bin/nvcc" on my computer.
What should I do. Thanks!

Building roi pool op...
runningbuild_ext
building 'roi_pool_cuda' extension
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/liguangya/mmenv/lib/python3.5/site-packages/torch/lib/include -I/home/liguangya/mmenv/lib/python3.5/site-packages/torch/lib/include/TH -I/home/liguangya/mmenv/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/local/cuda/lib64/include -I/usr/include/python3.5m -I/home/liguangya/mmenv/include/python3.5m -c src/roi_pool_cuda.cpp -o build/temp.linux-x86_64-3.5/src/roi_pool_cuda.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/lib64/bin/nvcc -I/home/liguangya/mmenv/lib/python3.5/site-packages/torch/lib/include -I/home/liguangya/mmenv/lib/python3.5/site-packages/torch/lib/include/TH -I/home/liguangya/mmenv/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/local/cuda/lib64/include -I/usr/include/python3.5m -I/home/liguangya/mmenv/include/python3.5m -c src/roi_pool_kernel.cu -o build/temp.linux-x86_64-3.5/src/roi_pool_kernel.o -DTORCH_EXTENSION_NAME=roi_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options '-fPIC' -std=c++11
unable to execute '/usr/local/cuda/lib64/bin/nvcc': No such file or directory
error: command '/usr/local/cuda/lib64/bin/nvcc' failed with exit status 1

**Comment by suica** [comment]
There may be a **dirty** solution using soft link.
Create necessary folders first, then run
(probably sudo)`ln -s /usr/local/cuda/bin /usr/local/cuda/lib64/bin`.
Or just `ln` the `nvcc` instead of whole bin folder.

**Comment by hellock** [comment]
Hi @hitlgy Do you have an environment variable `CUDA_HOME` or `CUDA_ROOT` set to `/usr/local/cuda/lib64` instead of `/usr/local/cuda` so that the wrong path is found?

**Comment by chelixuan** [comment]
thank you for your reply, I have solve this problem! Looking forward to your paper about this algorithm~~ @hellock

**Comment by Curry1201** [comment]
> thank you for your reply, I have solve this problem! Looking forward to your paper about this algorithm~~ @hellock

How did you solve this problem? I also encountered a similar problem. Looking forward to your reply.

**Comment by chelixuan** [comment]
vim compile.sh


1. check if your cuda_path is /usr/bin/env
    if not ,add 
    "CUDA_PATH=/your/path/"
    at the beginning of the compile.sh
2. after finish the 1st step, you can try ./compil.sh
    if failed ,try add the following at the beginning of the compil.sh
     ---------------------------------------------------------
      export CXXFLAGS="-std=c++11"
      export CFLAGS="-std=c99"
     ---------------------------------------------------------

it works well for me. Hope can help you~~
@Curry1201

**Comment by Curry1201** [comment]
> vim compile.sh
> 
>     1. check if your cuda_path is /usr/bin/env
>        if not ,add
>        "CUDA_PATH=/your/path/"
>        at the beginning of the compile.sh
> 
>     2. ## after finish the 1st step, you can try ./compil.sh
>        if failed ,try add the following at the beginning of the compil.sh
>        ## export CXXFLAGS="-std=c++11"
>        export CFLAGS="-std=c99"
> 
> 
> it works well for me. Hope can help you~~
> @Curry1201

I have solved this problem. But thank you for your kind response.
