### ISSUE TITLE
PointRend or Implicit PointRend based sampling for mask loss computation

### ISSUE THREAD

**Issue by susaha** [open-mmlab/mmdetection#8600]
Mask2Former uses PointRend or Implicit PointRend based sampling to calculate the mask loss, which reduces training memory by 3×, from 18GB to 6GB per image, making Mask2Former more accessible to users with limited computational resources (see Sec. 3.3. Improving training efficiency in the main paper). I am training mask2former using mmdetection and it takes 19GB of memory per GPU. My question is, does mmdetection has an implementation of the PointRend or Implicit PointRend based sampling for mask loss computation?

**Comment by BIGWangYuDong** [comment]
Kindly ping @chhluo have a look

**Comment by susaha** [comment]
@chhluo: could you please have a look?

**Comment by chhluo** [comment]
@susaha We did that, see https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/models/dense_heads/mask2former_head.py#L283

And there are some difference between Detectron2 and MMDetection, such as `FrozenBN` v.s. `BN` which is one of reasons for the memory difference (`FrozenBN` in Detectron2 saves more memory). Also the implementation of Mask2Former has room for improve such as https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/models/dense_heads/mask2former_head.py#L240, the copy is unnecessary and avoidable. And we will optimize the implementation later.

**Comment by susaha** [comment]
@chhluo Thanks for your reply. Have you checked the performance with the frozen BN layers? Are you using BN in place of FrozenBN due to a better performance or is there any other reason?

**Comment by chhluo** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/pull/7141.
