### ISSUE TITLE
How to a extract feature vector  from a pretrain model

### ISSUE THREAD

**Issue by David-Biggs** [open-mmlab/mmdetection#8608]
Thanks for the awesome framework!! 

I am trying to extract feature vectors from a pretrained model.  I have attached the `model` and I have indicated three locations from where I would like extract the feature vectors (lines 330,365,378).

I am unsure of what or where the code I write should be to extract the vectors at these locations? 

Any help will be appreciated. 
[model.txt](https://github.com/open-mmlab/mmdetection/files/9393703/model.txt)

**Comment by Czm369** [comment]
For example, you can get the feature map of FPN from here
https://github.com/open-mmlab/mmdetection/blob/e71b499608e9c3ccd4211e7c815fa20eeedf18a2/mmdet/models/detectors/two_stage.py#L127
