### ISSUE TITLE
RuntimeError: Expected to mark a variable ready only once.

### ISSUE THREAD

**Issue by puhan123** [open-mmlab/mmdetection#8609]
In my implemented algorithms, I need to backward the classification loss and location loss respectively to obtain the respective gradients, in other word, I need to backward twice for one forward. When I run it,  a single GPU run is normal, multiple GPUs run will report the following error:

"RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.3) Incorrect unused parameter detection. The return value of the `forward` function is inspected by the distributed data parallel wrapper to figure out if any of the module's parameters went unused. For unused parameters, DDP would not expect gradients from then. However, if an unused parameter becomes part of the autograd graph at a later point in time (e.g., in a reentrant backward when using `checkpoint`), the gradient will show up unexpectedly. If all parameters in the model participate in the backward pass, you can disable unused parameter detection by passing the keyword argument `find_unused_parameters=False` to `torch.nn.parallel.DistributedDataParallel`."

And I have set ' find_unused_parameters=False', however, it still doesn't work.
Thank you very much.

**Comment by Czm369** [comment]
This is the issue of the distributed torch. There are some operations during the distributed start of torch, which you can pay more attention to
