### ISSUE TITLE
Problem with yolox test

### ISSUE THREAD

**Issue by Chang-007** [open-mmlab/mmdetection#8613]
The yolox training is done, but I can't get the predicted boxes correctly at test time. It looks like it should be a problem with loading the model. I would like to know how to properly load the trained model.thanks！

**Comment by hhaAndroid** [comment]
@Chang-007 It is reasonable to suggest that the ema does not match, since in fact this part does not need.

**Comment by Chang-007** [comment]
Does yolox have requirements for img_scale?

**Comment by hhaAndroid** [comment]
@Chang-007 Hello. Did you solve it?
