### ISSUE TITLE
Some errors when testing Panoptic on MS COCO test-dev.

### ISSUE THREAD

**Issue by Cathy1900** [open-mmlab/mmdetection#8614]
**I want to test Panoptic on MS COCO test-dev dataset to generate JSON files and upload them to the official server.** 

**I used the following code with mmdetection 2.23:**
CUDA_VISIBLE_DEVICES=4,5,6,7 PORT=29529 ./tools/dist_test.sh work_dirs/Panoptic_fpn/panoptic_fpn_r101_fpn_1x_coco.py work_dirs/Panoptic_fpn/epoch_12.pth 4 --format-only --options "jsonfile_prefix=work_dirs/Panoptic_fpn/panoptic_fpn_r101_fpn_1x_coco_test-dev_results"

**I made the following changes to _panoptic_fpn_r50_fpn_1x_coco.py_ to make sure it runs on MS COCO test-dev.**
test=dict(
        type='CocoPanopticDataset',
        ann_file='data/coco/annotations/image_info_test-dev2017.json',
        img_prefix='data/coco/test2017/',
        seg_prefix=None,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ])

**However, when generating the JSON file, the following error is reported:**

File "./tools/test.py", line 268, in <module>
    main()
  File "./tools/test.py", line 250, in main
    dataset.format_results(outputs, **kwargs)
  File "/data/mmdetection_2.23/mmdet/datasets/coco.py", line 383, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/data/mmdetection_2.23/mmdet/datasets/coco_panoptic.py", line 487, in results2json
    pan_json_results = self._pan2json(pan_results, outfile_prefix)
  File "/data/mmdetection_2.23/mmdet/datasets/coco_panoptic.py", line 429, in _pan2json
    cat_id = label2cat[sem_label]
KeyError: 102
Traceback (most recent call last):
  File "/home/anaconda3/envs/mm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/mm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/mm/bin/python', '-u', './tools/test.py', '--local_rank=3', 'work_dirs/Panoptic_fpn/panoptic_fpn_r50_fpn_1x_coco_transv2_dcn_3x3/panoptic_fpn_r50_fpn_1x_coco.py', 'work_dirs/Panoptic_fpn/panoptic_fpn_r50_fpn_1x_coco_transv2_dcn_3x3/epoch_12.pth', '--launcher', 'pytorch', '--format-only', '--options', 'jsonfile_prefix=work_dirs/Panoptic_fpn/panoptic_fpn_r50_fpn_1x_coco_transv2_dcn_3x3/panoptic_fpn_r50_fpn_1x_coco_test-dev_results']' returned non-zero exit status 1.

How should I fix it? Thanks

**Comment by chhluo** [comment]
Please follow the steps in https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/test_results_submission.md.
