### ISSUE TITLE
what is the difference between "annotation_item['ignore']" and "annotation_item['iscrowd']"

### ISSUE THREAD

**Issue by XueZ-phd** [open-mmlab/mmdetection#8615]
I am using mmdetection to detect a person from an image.

In my annotation, there are three categories, i.e., "person", "people" and "person?", where "people" is a crowd of people and the human annotators can not exactly localize a single person in that region, "person?" denotes a person region but it is occluded. 

In this context, I want to ignore the loss generated by "people" and "person?", how can I do? It is worth mentioning that simply removing the "people" and "person?" annotations can lead to false positives.

Now, I use the following method and I want to know if it is correct.
![image](https://user-images.githubusercontent.com/58646903/186061040-9cf50a1c-b109-46ae-990b-4d57d9f9198e.png)

**Comment by hhaAndroid** [comment]
In CocoDataset  `iscrowd` will be treated as an ignore box and will not participate in the loss calculation, and the` ignore area`  will be considered as the background.  In VOCDataset  `iscrowd` is equivalent to `difficult`. At the same time, some algorithms do not support `iscrowd`.

**Comment by XueZ-phd** [comment]
@hhaAndroid Thank you for your reply. As time goes by, I have figured this out. You are right to some extent. If I want to ignore some annotations and not compute their loss, I should set those annotations to "iscrowd" and also set ignore_iof_thr>0.
Code is [here](https://github.com/open-mmlab/mmdetection/blob/e71b499608e9c3ccd4211e7c815fa20eeedf18a2/mmdet/core/bbox/assigners/max_iou_assigner.py#L113):
