### ISSUE TITLE
CICD support

### ISSUE THREAD

**Issue by manhtd98** [open-mmlab/mmdetection#8627]
I currently using MMDET in my project and want to log all things like training parameters, and evaluation results. I found that a framework like kubeflow can help me but mmdetection uses something deeper to understand. Did anyone do that?

**Comment by jbwang1997** [comment]
All training logs and evaluation results are collected under the work_dir. What's more mmdetection also support to use wandb backend to log important results. You can refer to [here](https://github.com/open-mmlab/mmdetection/issues/8358) for details to use wandb in mmdetection.
