### ISSUE TITLE
Performance improvement of PISA and baseline

### ISSUE THREAD

**Issue by zen-d** [open-mmlab/mmdetection#8630]
The PISA algorithm seems not to outperform the baseline counterpart obviously. When comparing https://github.com/open-mmlab/mmdetection/blob/master/configs/pisa/README.md and https://github.com/open-mmlab/mmdetection/blob/master/configs/retinanet/README.md, the RetineNet-R50-FPN results are  36.9% and 36.5%, which looks different from the conclusion of your paper (PISA improves a lot over a low baseline). I wonder where this gap comes from.

**Comment by RangiLyu** [comment]
As I know, the retinanet baseline in PISA is referred from Detectron https://github.com/facebookresearch/Detectron/blob/main/MODEL_ZOO.md.

**Comment by RangiLyu** [comment]
Maybe you need to ask the author. I wasn't involved in that work so I have no idea.

**Comment by RangiLyu** [comment]
kindly ping @yhcao6

**Comment by yhcao6** [comment]
@zen-d As mentioned in the ``note`` of [README.md](https://github.com/open-mmlab/mmdetection/blob/master/configs/pisa/README.md), 
```In the original paper, all models are trained and tested on mmdet v1.x, thus results may not be exactly the same with this release on v2.0```,
The implementation of PISA RetinaNet is based on mmdet v1.x, so you should compare with the RetinaNet baseline in mmdet v1.x. You can find [here](https://github.com/yhcao6/mmdetection/blob/fp16/MODEL_ZOO.md#retinanet).
You can also try to adapt it to the current version of mmdet but it may need some tuning of the hyper-parameters.
