### ISSUE TITLE
Can QFL be applied to YOLOX?

### ISSUE THREAD

**Issue by Chang-007** [open-mmlab/mmdetection#8632]
I want to make some improvements on YOLOX, but I don't know if QFL can be used on YOLOX. and how to modify the config file.

**Comment by RangiLyu** [comment]
If you want to use QFL in YOLOX, you need to modify the code of the YOLOX head, because YOLOX uses objectness and classification branches that are different from the GFL head.

**Comment by chl916185** [comment]
> I want to make some improvements on YOLOX, but I don't know if QFL can be used on YOLOX. and how to modify the config file.

QFL是啥啊

**Comment by RangiLyu** [comment]
> > I want to make some improvements on YOLOX, but I don't know if QFL can be used on YOLOX. and how to modify the config file.
> 
> QFL是啥啊

please refer to https://proceedings.neurips.cc/paper/2020/file/f0bda020d2470f2e74990a07a607ebd9-Paper.pdf
