### ISSUE TITLE
Segmentation fault when trying multiprocessing in mean average precision calculation

### ISSUE THREAD

**Issue by Balakumaran-kandula** [open-mmlab/mmdetection#8636]
When running mmdetection with custom dataset , at 7 th epoch while doing multiprocessing in mean average precision calculation on mean_ap.py  on line 
pool = Pool(nproc) 
segmentation fault is happening.

![image](https://user-images.githubusercontent.com/94863153/186666262-b232b361-c1e4-4ddd-8a74-2cc92f3b2039.png)

**Comment by RangiLyu** [comment]
I'm not sure if it's because of thread safety. Try to set mp_start_method = 'spawn' in 
https://github.com/open-configs/_base_/default_runtime.py
https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/configs/_base_/default_runtime.py#L21
