### ISSUE TITLE
GPU memory consumption gradually increases over time

### ISSUE THREAD

**Issue by susaha** [open-mmlab/mmdetection#8640]
I have noticed in the training log* that the GPU memory usage gradually increases over time. Initially, it is around 8 GB, and at the end, it reaches approximately 16 GB. May I ask why a gradual increase in GPU memory consumption?
*https://download.openmmlab.com/mmdetection/v2.0/maskformer/maskformer_r50_mstrain_16x1_75e_coco/maskformer_r50_mstrain_16x1_75e_coco_20220221_141956.log.json

**Comment by BIGWangYuDong** [comment]
Maybe because you used Random resize or some other Data Augs that may change the GPU memory?

**Comment by susaha** [comment]
Thanks for answering! :)
