### ISSUE TITLE
Add additional classification branch to mask2former

### ISSUE THREAD

**Issue by EstherJinyan** [open-mmlab/mmdetection#8641]
Hello, I want to add a additional classification branch to mask2former to learn the attributes of the instance (such as sharpness, etc.), but I see the code is more complicated, I don't know how to start, can you give some advice?

**Comment by BIGWangYuDong** [comment]
You can read the tutorials to first learn some examples of mmdet https://github.com/open-mmlab/mmdetection/tree/master/docs/en/tutorials
