### ISSUE TITLE
How to get the nn.Module type model to do the quantization aware training?

### ISSUE THREAD

**Issue by borninfreedom** [open-mmlab/mmdetection#8651]
I use a module to do the quantization aware training. And I need  a torch.nn.Module type model to get the quantization aware training config file.

**How to get the nn.Module type model using mmdetection?**

**Comment by chhluo** [comment]
What is the type of nn.Module? Could you provide an example?

**Comment by borninfreedom** [comment]
I use the (scrfd algorithm)[https://github.com/deepinsight/insightface/tree/master/detection/scrfd], it's built on the mmdetection.
I modified the code at line 81 in `mmdet/train.py` file.
```python
    # put model on gpus
    if distributed:
        find_unused_parameters = cfg.get('find_unused_parameters', False)
        # Sets the `find_unused_parameters` parameter in
        # torch.nn.parallel.DistributedDataParallel
        
        model = MMDistributedDataParallel(
            model.cuda(),
            device_ids=[torch.cuda.current_device()],
            broadcast_buffers=False,
            find_unused_parameters=find_unused_parameters)

            ##### This is the code I added #########
            dummy_input = torch.rand(1,3,600,600).cuda()
            ## some_function needs a torch.nn.Module type model ##
            i_used_the_function(model, dummy_input)
            ################################
    else:
        model = MMDataParallel(
            model.cuda(cfg.gpu_ids[0]), device_ids=cfg.gpu_ids)
```
But it will report an error. `TypeError: forward() missing 1 required positional argument: 'img_metas' `.  

I printed the `model type` in the above code snippet. 
```python
       model = MMDistributedDataParallel(
            model.cuda(),
            device_ids=[torch.cuda.current_device()],
            broadcast_buffers=False,
            find_unused_parameters=find_unused_parameters)
```
It is the `mmcv.parallel.distributed.MMDistributedDataParrallel` type. 

And I also printed the `model type` at line 154 in `tools/train.py`.
```python
    model = build_detector(
        cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
```
It is the `mmdet.models.detectors.scrfd.SCRFD`.

Finally, I found that the `class BaseDetector` in  `mmdet/models/detectors/base.py` file is inherited from the `nn.Module` type.

But I found that the `forward` function is not the regular definition.
```python
    @auto_fp16(apply_to=('img', ))
    def forward(self, img, img_metas, return_loss=True, **kwargs):
```

So I guess that because the `model type` is the `mmcv` and `mmdet` type, so when  I called the `i_used_the_function(model, dummy_input)` function, the torch will use the `forward` function defined by `mmdetection`. But `i_used_the_function(model, dummy_input)` only needs a `pure torch.nn.Module` model, so it doesn't need a `img_metas` parameter.

**If my analysis is right, my question is how to get the `pure torch.nn.Module` type model?**

**Comment by chhluo** [comment]
You can override the `BaseDetector.forward` if `img_metas` is unnecessray in the `forward` function.

**Comment by borninfreedom** [comment]
> You can override the `BaseDetector.forward` if `img_metas` is unnecessray in the `forward` function.

How to override the `img_metas` parameter?

**Comment by chhluo** [comment]
Pass the `pad_shape` `img_shape` in `img_meta` directly to `forward`, which means that you need to modify many apis.

**Comment by Ubivision** [comment]
Have you found a way to extract methods from torch.nn.Module? I am using MQBench and encountered the same issue.
