### ISSUE TITLE
A question about performance of FasterRCNN

### ISSUE THREAD

**Issue by Viczyf** [open-mmlab/mmdetection#866]
I noticed the performance of FasterRCNN using mmdetction is significantly higher than that of the paper. For example, box AP of FasterRCNN with ResNet-101-FPN backbone is only 36.2, but the test result of mmdetecton's FasterRCNN with same structure is about 38.8. 
Are there any extra tricks?

**Comment by hellock** [comment]
The official implementation (Detectron) is also higher than the number reported in the paper. This is normal since there may be bugs fixed or some other improvement since the paper is released.
