### ISSUE TITLE
OpenCV failed to load the ONNX model

### ISSUE THREAD

**Issue by Hone-Xu** [open-mmlab/mmdetection#8675]
OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [TopK@ai.onnx]:(onnx_node!TopK_210) parse error: OpenCV(4.6.0) d:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layer_internals.hpp:110: error: (-2:Unspecified error) Can't create layer "onnx_node!TopK_210" of type "TopK" in function 'cv::dnn::dnn4_v20220524::detail::LayerData::getLayerInstance'
![image](https://user-images.githubusercontent.com/96858577/187606273-8b0fe285-14e4-4e74-b6ac-e7545c5d29e4.png)

**Comment by jbwang1997** [comment]
This might be because your topk uses a dynamic value. Please refer to [here](https://forums.developer.nvidia.com/t/onnx-parse-problem-with-topk/165807/4) for details
