### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'url' and 'message'

### ISSUE THREAD

**Issue by LilySys** [open-mmlab/mmdetection#8680]
![1661936026733](https://user-images.githubusercontent.com/30501264/187639547-0b82d388-151d-4186-b990-0cad470eb3f5.png)

The above error is suddenly reported during the model training，Help!!
how to solve this proplem!

**Comment by jbwang1997** [comment]
Hello @LilySys. Could you follow the issue templete to provide more information, like the mmdet, mmcv, and pytorch version and your environment.
