### ISSUE TITLE
How to crop gt_bbox features from FPN features

### ISSUE THREAD

**Issue by Kyfafyd** [open-mmlab/mmdetection#8688]
Hi, I would like to learn how to crop gt_bbox features from FPN features?
For example, given pretrained faster_rcnn model and a VOC image as input, I want to obtain the corrsepoonding gt_bbox features from FPN features.

**Comment by RangiLyu** [comment]
You should use RoIAlign or other RoI feature extract operations. These modules are in https://github.com/open-mmlab/mmdetection/tree/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/models/roi_heads/roi_extractors

**Comment by Kyfafyd** [comment]
Thanks for your response! @RangiLyu 
I would like to extract gt_bbox features of VOC dataset using COCO pretrained model, could you give me some advice on how to implement?
BTW, I am using the latest mmdet

**Comment by RangiLyu** [comment]
use `load_from` in the config to load the coco pretrained model
