### ISSUE TITLE
Bug in guided_anchor_head.py, or missing param in config

### ISSUE THREAD

**Issue by chuong98** [open-mmlab/mmdetection#869]
line 409,
`center_ratio=cfg.center_ratio,`
AttributeError: 'ConfigDict' object has no attribute 'center_ratio'

**Comment by myownskyW7** [comment]
Do you run a config file in configs/guided_anchoring/?  And you can git pull the latest code since center_ratio=cfg.center_ratio is in Line 414 currently.

**Comment by chuong98** [comment]
thanks. I just figure out that my config is outdated
