### ISSUE TITLE
How to get precision and recall using specific IoU and confidence score?

### ISSUE THREAD

**Issue by ibrahim1611** [open-mmlab/mmdetection#8690]
Hi, many thanks for your contributions.

I have trained the model with the Coco dataset format. I am getting results in the following format

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.787
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.587
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.144
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.545
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.691
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.691
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.691
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.262
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.711

Is there any way to calculate only precision and recall using specific IoU and confidence scores? For example, I want to calculate precision and recall using a 0.5 IoU and a 0.8 confidence score.

**Comment by RangiLyu** [comment]
You can use `--eval-options iou_thrs=[0.5]` to use 0.5 iou threshold.
If you want to set the score threshold to 0.8, you need to modify the `score_thr` in the model's test_cfg.

**Comment by XinyueZ** [comment]
> score_thr



> You can use `--eval-options iou_thrs=[0.5]` to use 0.5 iou threshold. If you want to set the score threshold to 0.8, you need to modify the `score_thr` in the model's test_cfg.

@RangiLyu how then in 3.x?
