### ISSUE TITLE
Question about batched NMS

### ISSUE THREAD

**Issue by NielsRogge** [open-mmlab/mmdetection#8700]
Hi,

I'm looking into the Mask R-CNN implementation. I see that NMS postprocessing (in the RoI head) is applied to each image individually as seen [here](https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/models/roi_heads/test_mixins.py#L112). My question is, is it possible to do this in a batched fashion on all images in one go (in order to get a fixed size tensor as output, rather than a list)?

When looking at the `get_bboxes` [method](https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L316) in the bounding box head, it seems that this function is defined for a batch of examples. However, this method is called for each image in a batch individually. Is this because the `img_shape` and `scale_factor` differ per image?

The ONNX version of Mask R-CNN seems to do that (apply NMS in one go on all images of a batch), I'm wondering whether this is also possible with the native PyTorch implementation?

Thanks!

**Comment by NielsRogge** [comment]
Update:

it seems that one favors decoding one-by-one rather than in a batched fashion as seen by the deprecation warning [here](https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py#L102-L107):

> 'please use “delta2bbox” instead. In order to improve '
    'the decoding speed, the batch function will no '
    'longer be supported. '

**Comment by RangiLyu** [comment]
If you want to do postprocessing in a batch way, you need to modify the whole testing logic. Just have a try.

**Comment by NielsRogge** [comment]
I just tried out the ONNX version of Mask R-CNN by following the [guide](https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html). I see it outputs detections of shape `(batch_size, max_detections_per_image, 5)`, e.g. (1, 100, 5). This is ideal, as it outputs fixed size tensors.

I wonder, is the same feasible with the native PyTorch implementation? Cause the ONNX implementation relies on the [NonMaxSuppression](https://github.com/onnx/onnx/blob/main/onnx/backend/test/case/node/nonmaxsuppression.py) method, which outputs `selected_indices`, of shape [num_selected_indices, 3], where each row is of the format [batch_index, class_index, box_index].

However, the PyTorch implementation relies on [multiclass_nms](https://github.com/open-mmlab/mmdetection/blob/4bd4ace53a626659070204236da5b8e14ae9cd08/mmdet/core/post_processing/bbox_nms.py#L8), which I'm not sure supports batched inference.

**Comment by RangiLyu** [comment]
`multiclass_nms` does not support batched inference. We still need to use a for-loop to do post-processing for each image in MMDetection.
