### ISSUE TITLE
How to Caculate AP of VOC format

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#8703]
大佬们，请问如何计算VOC格式的AP,我使用tools/robustness_eval.py 来计算，报错

![image](https://user-images.githubusercontent.com/25839884/188044417-6d01230a-fbbb-47bf-b449-6ef0e9d98ff4.png)

![image](https://user-images.githubusercontent.com/25839884/188044480-8ccf635f-fada-4ce4-a176-9be7be916dc2.png)

**Comment by vansin** [comment]
1. .pkl文件 test.py生成的吗？
2. .pkl文件实例分割算法生成的还是目标检测算法生成的?

**Comment by wzh-why** [comment]
1. pkl文件生成命令：
python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_ciou_1x_coco.py work_dirs/faster_rcnn_r50_fpn_ciou_1x_coco/latest.pth --out results.pkl
2. 该pkl文件通过目标检测算法生成

**Comment by vansin** [comment]
>我跑跑试试~

**Comment by wzh-why** [comment]
使用的mmdet版本为：mmdet-2.17.0
