### ISSUE TITLE
How to build the same loss using different name？

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#8704]
![image](https://user-images.githubusercontent.com/25839884/188044820-494eaf0e-ee0b-494a-8842-f2e280aca91b.png)

![image](https://user-images.githubusercontent.com/25839884/188044851-910133c1-d093-40c4-9e4f-7cb436712111.png)

**Comment by BIGWangYuDong** [comment]
Can refer to cascade_iou_head or you can write a hard code to force set the losses name in the loss dict

**Comment by vansin** [comment]
thanks
