### ISSUE TITLE
multiple defination of the bbox_head in the example code under Prepare a config header (link in body)

### ISSUE THREAD

**Issue by Likhith-Sugganahalli** [open-mmlab/mmdetection#8708]
[Thanks](url) for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.  checked
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help. checked
3. The bug has not been fixed in the latest version. checked

**Describe the bug**
in the config write up of the 'prepare a config' section of the 3_exist_data_new_model.md doc,
the bbox_head attribute of the roi_head dict is repeated thrice.

**Reproduction**

1. What command or script did you run?
link to the doc: [link](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/3_exist_data_new_model.md#prepare-a-config)
```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No modification made
3. What dataset did you use?
None
**Environment**
No environment needed

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

would be willing to raise a PR for this

**Comment by BIGWangYuDong** [comment]
Hi, don't get your point, the cascade bbox_head should have 3 heads, so I think the config is normal.

**Comment by Likhith-Sugganahalli** [comment]
sorry, my bad
