### ISSUE TITLE
Why not implement DCN in ResNet18 and ResNet34?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#8709]

**Comment by BIGWangYuDong** [comment]
I think ResNet18 or 34 can use DCN, but there is no pre-trained backbone yet.

**Comment by Icecream-blue-sky** [comment]
> I think ResNet18 or 34 can use DCN, but there is no pre-trained backbone yet.

I try to add dcn to res18 by myself, just like below:
```python
class BasicBlock(BaseModule):
    expansion = 1

    def __init__(self,
                 inplanes,
                 planes,
                 stride=1,
                 dilation=1,
                 downsample=None,
                 style='pytorch',
                 with_cp=False,
                 conv_cfg=None,
                 norm_cfg=dict(type='BN'),
                 dcn=None,
                 plugins=None,
                 init_cfg=None):
        super(BasicBlock, self).__init__(init_cfg)
        assert plugins is None, 'Not implemented yet.'

        self.norm1_name, norm1 = build_norm_layer(norm_cfg, planes, postfix=1)
        self.norm2_name, norm2 = build_norm_layer(norm_cfg, planes, postfix=2)

        self.conv1 = build_conv_layer(
            conv_cfg,
            inplanes,
            planes,
            3,
            stride=stride,
            padding=dilation,
            dilation=dilation,
            bias=False)
        self.add_module(self.norm1_name, norm1)
        # add dcn to Basic Block
        self.dcn = dcn
        self.with_dcn = dcn is not None
        fallback_on_stride = False
        if self.with_dcn:
            fallback_on_stride = dcn.pop('fallback_on_stride', False)
        if not self.with_dcn or fallback_on_stride:
            self.conv2 = build_conv_layer(
                conv_cfg, planes, planes, 3, padding=1, bias=False)
        else:
            # get deformable conv
            self.conv2 = build_conv_layer(
                dcn, planes, planes, 3, padding=1, bias=False)
        self.add_module(self.norm2_name, norm2)

        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride
        self.dilation = dilation
        self.with_cp = with_cp
```
with config:
```python
backbone=dict(
        type='ResNetZ',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True),
        style='pytorch',
        init_cfg=dict(
            type='Pretrained',
            checkpoint='torchvision://resnet18')),
```
But I got the error: 
```basic
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    main()
  File "train.py", line 186, in main
    meta=meta)
  File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/apis/train.py", line 211, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    **kwargs)
  File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/base.py", line 256, in train_step
    losses = self(**data)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/single_stage.py", line 82, in forward_train
    x = self.extract_feat(img)
  File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/single_stage.py", line 45, in extract_feat
    x = self.neck(x)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/necks/fpn.py", line 159, in forward
    for i, lateral_conv in enumerate(self.lateral_convs)
  File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/necks/fpn.py", line 159, in <listcomp>
    for i, lateral_conv in enumerate(self.lateral_convs)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
    x = self.conv(x)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [256, 512, 1, 1], expected input[2, 128, 76, 128] to have 512 channels, but got 128 channels instead
```
Could you please tell me why this happen? Thanks!

**Comment by Icecream-blue-sky** [comment]
> > I think ResNet18 or 34 can use DCN, but there is no pre-trained backbone yet.
> 
> I try to add dcn to res18 by myself, just like below:
> 
> ```python
> class BasicBlock(BaseModule):
>     expansion = 1
> 
>     def __init__(self,
>                  inplanes,
>                  planes,
>                  stride=1,
>                  dilation=1,
>                  downsample=None,
>                  style='pytorch',
>                  with_cp=False,
>                  conv_cfg=None,
>                  norm_cfg=dict(type='BN'),
>                  dcn=None,
>                  plugins=None,
>                  init_cfg=None):
>         super(BasicBlock, self).__init__(init_cfg)
>         assert plugins is None, 'Not implemented yet.'
> 
>         self.norm1_name, norm1 = build_norm_layer(norm_cfg, planes, postfix=1)
>         self.norm2_name, norm2 = build_norm_layer(norm_cfg, planes, postfix=2)
> 
>         self.conv1 = build_conv_layer(
>             conv_cfg,
>             inplanes,
>             planes,
>             3,
>             stride=stride,
>             padding=dilation,
>             dilation=dilation,
>             bias=False)
>         self.add_module(self.norm1_name, norm1)
>         # add dcn to Basic Block
>         self.dcn = dcn
>         self.with_dcn = dcn is not None
>         fallback_on_stride = False
>         if self.with_dcn:
>             fallback_on_stride = dcn.pop('fallback_on_stride', False)
>         if not self.with_dcn or fallback_on_stride:
>             self.conv2 = build_conv_layer(
>                 conv_cfg, planes, planes, 3, padding=1, bias=False)
>         else:
>             # get deformable conv
>             self.conv2 = build_conv_layer(
>                 dcn, planes, planes, 3, padding=1, bias=False)
>         self.add_module(self.norm2_name, norm2)
> 
>         self.relu = nn.ReLU(inplace=True)
>         self.downsample = downsample
>         self.stride = stride
>         self.dilation = dilation
>         self.with_cp = with_cp
> ```
> 
> with config:
> 
> ```python
> backbone=dict(
>         type='ResNetZ',
>         depth=18,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=True,
>         dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
>         stage_with_dcn=(False, True, True, True),
>         style='pytorch',
>         init_cfg=dict(
>             type='Pretrained',
>             checkpoint='torchvision://resnet18')),
> ```
> 
> But I got the error:
> 
> ```basic
> Traceback (most recent call last):
>   File "train.py", line 190, in <module>
>     main()
>   File "train.py", line 186, in main
>     meta=meta)
>   File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/apis/train.py", line 211, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
>     self.run_iter(data_batch, train_mode=True, **kwargs)
>   File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
>     **kwargs)
>   File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
>     return self.module.train_step(*inputs[0], **kwargs[0])
>   File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/base.py", line 256, in train_step
>     losses = self(**data)
>   File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
>     return old_func(*args, **kwargs)
>   File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/base.py", line 174, in forward
>     return self.forward_train(img, img_metas, **kwargs)
>   File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/single_stage.py", line 82, in forward_train
>     x = self.extract_feat(img)
>   File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/detectors/single_stage.py", line 45, in extract_feat
>     x = self.neck(x)
>   File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
>     return old_func(*args, **kwargs)
>   File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/necks/fpn.py", line 159, in forward
>     for i, lateral_conv in enumerate(self.lateral_convs)
>   File "/gpfs/home/sist/tqzouustc/code/mmdetection_latest/mmdet/models/necks/fpn.py", line 159, in <listcomp>
>     for i, lateral_conv in enumerate(self.lateral_convs)
>   File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/sist/tqzouustc/.conda/envs/openmmlab_a100_latest/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
>     x = self.conv(x)
>   File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: Given groups=1, weight of size [256, 512, 1, 1], expected input[2, 128, 76, 128] to have 512 channels, but got 128 channels instead
> ```
> 
> Could you please tell me why this happen? Thanks!

Solve it!

**Comment by lanqz7766** [comment]
Hello, could you share how you solve this problem? Thank you very much! @Icecream-blue-sky

**Comment by Icecream-blue-sky** [comment]
> Hello, could you share how you solve this problem? Thank you very much! @Icecream-blue-sky

Just add the DCN conv to BasicBlock in resnet.py:
```python
class BasicBlock(BaseModule):
    expansion = 1

    def __init__(self,
                 inplanes,
                 planes,
                 stride=1,
                 dilation=1,
                 downsample=None,
                 style='pytorch',
                 with_cp=False,
                 conv_cfg=None,
                 norm_cfg=dict(type='BN'),
                 dcn=None,
                 plugins=None,
                 init_cfg=None):
        super(BasicBlock, self).__init__(init_cfg)
        assert plugins is None, 'Not implemented yet.'

        self.norm1_name, norm1 = build_norm_layer(norm_cfg, planes, postfix=1)
        self.norm2_name, norm2 = build_norm_layer(norm_cfg, planes, postfix=2)

        self.conv1 = build_conv_layer(
            conv_cfg,
            inplanes,
            planes,
            3,
            stride=stride,
            padding=dilation,
            dilation=dilation,
            bias=False)
        self.add_module(self.norm1_name, norm1)
        # add dcn to Basic Block
        self.dcn = dcn
        self.with_dcn = dcn is not None
        fallback_on_stride = False
        if self.with_dcn:
            fallback_on_stride = dcn.pop('fallback_on_stride', False)
        if not self.with_dcn or fallback_on_stride:
            self.conv2 = build_conv_layer(
                conv_cfg, planes, planes, 3, padding=1, bias=False)
        else:
            # get deformable conv
            self.conv2 = build_conv_layer(
                dcn, planes, planes, 3, padding=1, bias=False)
        self.add_module(self.norm2_name, norm2)

        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride
        self.dilation = dilation
        self.with_cp = with_cp
```
and chang the config to below (FPN in_channels should be changed when use res18 and res34:
```python
model = dict(
    type='FCOS',
    backbone=dict(
        type='ResNetZ',
        depth=34,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True),
        style='pytorch',
        init_cfg=dict(
            type='Pretrained',
            checkpoint='torchvision://resnet34')),
    neck=dict(
        type='FPN',
        in_channels=[64, 128, 256, 512],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5,
        relu_before_extra_convs=True),
```

**Comment by lanqz7766** [comment]
> > Hello, could you share how you solve this problem? Thank you very much! @Icecream-blue-sky
> 
> Just add the DCN conv to BasicBlock in resnet.py:
> 
> ```python
> class BasicBlock(BaseModule):
>     expansion = 1
> 
>     def __init__(self,
>                  inplanes,
>                  planes,
>                  stride=1,
>                  dilation=1,
>                  downsample=None,
>                  style='pytorch',
>                  with_cp=False,
>                  conv_cfg=None,
>                  norm_cfg=dict(type='BN'),
>                  dcn=None,
>                  plugins=None,
>                  init_cfg=None):
>         super(BasicBlock, self).__init__(init_cfg)
>         assert plugins is None, 'Not implemented yet.'
> 
>         self.norm1_name, norm1 = build_norm_layer(norm_cfg, planes, postfix=1)
>         self.norm2_name, norm2 = build_norm_layer(norm_cfg, planes, postfix=2)
> 
>         self.conv1 = build_conv_layer(
>             conv_cfg,
>             inplanes,
>             planes,
>             3,
>             stride=stride,
>             padding=dilation,
>             dilation=dilation,
>             bias=False)
>         self.add_module(self.norm1_name, norm1)
>         # add dcn to Basic Block
>         self.dcn = dcn
>         self.with_dcn = dcn is not None
>         fallback_on_stride = False
>         if self.with_dcn:
>             fallback_on_stride = dcn.pop('fallback_on_stride', False)
>         if not self.with_dcn or fallback_on_stride:
>             self.conv2 = build_conv_layer(
>                 conv_cfg, planes, planes, 3, padding=1, bias=False)
>         else:
>             # get deformable conv
>             self.conv2 = build_conv_layer(
>                 dcn, planes, planes, 3, padding=1, bias=False)
>         self.add_module(self.norm2_name, norm2)
> 
>         self.relu = nn.ReLU(inplace=True)
>         self.downsample = downsample
>         self.stride = stride
>         self.dilation = dilation
>         self.with_cp = with_cp
> ```
> 
> and chang the config to below (FPN in_channels should be changed when use res18 and res34:
> 
> ```python
> model = dict(
>     type='FCOS',
>     backbone=dict(
>         type='ResNetZ',
>         depth=34,
>         num_stages=4,
>         out_indices=(0, 1, 2, 3),
>         frozen_stages=1,
>         norm_cfg=dict(type='BN', requires_grad=True),
>         norm_eval=True,
>         dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
>         stage_with_dcn=(False, True, True, True),
>         style='pytorch',
>         init_cfg=dict(
>             type='Pretrained',
>             checkpoint='torchvision://resnet34')),
>     neck=dict(
>         type='FPN',
>         in_channels=[64, 128, 256, 512],
>         out_channels=256,
>         start_level=1,
>         add_extra_convs='on_output',
>         num_outs=5,
>         relu_before_extra_convs=True),
> ```

Thanks, it works!
