### ISSUE TITLE
mmdet 3.x: ImportError: cannot import name 'Sequence' from 'collections'

### ISSUE THREAD

**Issue by Chan-Sun** [open-mmlab/mmdetection#8711]
Looking forward to mmdet 3.x version! And when i try to reimplement semi-detector models, i found a small error regrading python compatibility.

My python version is 3.10 and the code concerned is below. 
https://github.com/open-mmlab/mmdetection/blob/a32574bbdcf1e8083c12fdfba8c73e0cea5d8f5d/mmdet/models/detectors/semi_base.py#L3

there is a bug when running  `./tools/train.py`
```python
Traceback (most recent call last):
  File "/home/sunchen/Projects/debug_train.py", line 126, in <module>
    main(args)
  File "/home/sunchen/Projects/debug_train.py", line 59, in main
    register_all_modules(init_default_scope=False)
  File "/home/sunchen/Packages/mmdetection3/mmdet/utils/setup_env.py", line 72, in register_all_modules
    import mmdet.models  # noqa: F401,F403
  File "/home/sunchen/Packages/mmdetectionv3/mmdet/models/__init__.py", line 9, in <module>
    from .detectors import *  # noqa: F401,F403
  File "/home/sunchen/Packages/mmdetectionv3/mmdet/models/detectors/__init__.py", line 35, in <module>
    from .semi_base import SemiBaseDetector
  File "/home/sunchen/Packages/mmdetectionv3/mmdet/models/detectors/semi_base.py", line 3, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/home/sunchen/anaconda3/envs/mmd3/lib/python3.10/collections/__init__.py)
```

According to the discussion [here](https://github.com/wireservice/agate/pull/737), I think it is better to use `from collections.abc import Sequence`, since `Python 3.3. A warning is printed starting with Python 3.7 and in Python 3.9 the new import location will be required.`

**Comment by BIGWangYuDong** [comment]
Hi, I haven't tried Python >=3.9. We will discussed this issue, and fix ASAP

**Comment by BIGWangYuDong** [comment]
I think you can use 
```
try:
    from collections.abc import Sequence
except ImportError:
    from collections import Sequence
```
to fix this error

**Comment by ZwwWayne** [comment]
> I think you can use
> 
> ```
> try:
>     from collections.abc import Sequence
> except ImportError:
>     from collections import Sequence
> ```
> 
> to fix this error

Then let's create a PR to fix that.

**Comment by Chan-Sun** [comment]
> > I think you can use
> > ```
> > try:
> >     from collections.abc import Sequence
> > except ImportError:
> >     from collections import Sequence
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to fix this error
> 
> Then let's create a PR to fix that.

Just review the code in the latest v3.0.0rc2. The semi_detector code has been optimized in the PR (https://github.com/open-mmlab/mmdetection/pull/8786) and this line of import code has been deleted

So, this bug no longer exists, and I will close this issue.
