### ISSUE TITLE
Mask problem

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#8715]
![QQ图片20220903115403](https://user-images.githubusercontent.com/6490927/188254853-90b9bbfa-c2b1-4d4a-8a81-93680f940fcc.png)

I need to get the mask width

The yellow line is the width I need

I don't know how to convert it into coordinates

**Comment by chhluo** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/core/mask/structures.py#L1075
