### ISSUE TITLE
frozen_stages doesn't work for Swin Backbone

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#8724]
Hi @BIGWangYuDong @RangiLyu @jbwang1997 

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
frozen_stages doesn't work for Swin Backbone

**Reproduction**

1. What command or script did you run?

```none
Any framework uses the swin backbone
```

**Comment by ZwwWayne** [comment]
It is not implemented because in practice the whole backbone is trained in Swin.
