### ISSUE TITLE
How to save predicted bounding boxes in XML

### ISSUE THREAD

**Issue by ibrahim1611** [open-mmlab/mmdetection#8725]
Hi,

I have trained the model with a custom dataset and tested it on images. Now I want to store the predicted bounding boxes of each image in XML format. Is it possible to do this in mmdetection?

**Comment by vansin** [comment]
You can use python third-party dependency library xml to save predicted bounding boxes of each image in MMDetection.

**Comment by chhluo** [comment]
@ibrahim1611 You can write a script to convert the pkl file generated by tools/test.py to xml format by `xml` package.
