### ISSUE TITLE
Train on Subset of Classes (VOC0712): AssertionError: The `num_classes` (1) in Shared2FCBBoxHead of MMDataParallel does not matches the length of `CLASSES` 20) in RepeatDataset

### ISSUE THREAD

**Issue by AlistairMcCutcheon** [open-mmlab/mmdetection#8726]
I am trying to train on just the person class on the VOC2007 and VOC2012 datasets - I've tried to follow the "Modify Dataset Classes" tutorial, found here: https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html

If I run train.py with config file 2 (shown below), it runs successfully.

I have not modified the annotation files in any way. 
I run train.py with config file 1 (shown below), getting the error:
```
AssertionError: The `num_classes` (1) in Shared2FCBBoxHead of MMDataParallel does not matches the length of `CLASSES` 20) in RepeatDataset
```

**Config file 1: (Uses config file 2 as a base).** 
```
_base_ = ["../../configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py"]
CLASSES = ("person",)
data = dict(
    train=dict(classes=CLASSES), val=dict(classes=CLASSES), test=dict(classes=CLASSES)
)
model = dict(roi_head=dict(bbox_head=dict(num_classes=1)))
```

**Config file 2: (Is a base to config file 1)**
```
_base_ = [
    "../_base_/models/faster_rcnn_r50_fpn.py",
    "../_base_/datasets/voc0712.py",
    "../_base_/default_runtime.py",
]
model = dict(roi_head=dict(bbox_head=dict(num_classes=20)))
# optimizer
optimizer = dict(type="SGD", lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
# actual epoch = 3 * 3 = 9
lr_config = dict(policy="step", step=[3])
# runtime settings
runner = dict(type="EpochBasedRunner", max_epochs=2)
```

**Comment by AlistairMcCutcheon** [comment]
The issue was solved by changing config file 1 to the following:

```
_base_ = ["../../configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py"]
CLASSES = ("person",)
data = dict(
    train=dict(
        dataset=dict(
            classes=CLASSES,
        ),
    ),
    val=dict(classes=CLASSES),
    test=dict(classes=CLASSES),
)
model = dict(roi_head=dict(bbox_head=dict(num_classes=1)))
```

**Comment by TonojiKiobya** [comment]
check this or the equivalent.

_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py', '../_base_/datasets/voc0712.py',
    '../_base_/default_runtime.py'
]

model = dict(roi_head=dict(bbox_head=dict(num_classes=10))) # change the class number accordingly
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
# actual epoch = 3 * 3 = 9
lr_config = dict(policy='step', step=[3])
# runtime settings
runner = dict(
    type='EpochBasedRunner', max_epochs=4)  # actual epoch = 4 * 3 = 12
