### ISSUE TITLE
question about the guided anchoring

### ISSUE THREAD

**Issue by alexwq100** [open-mmlab/mmdetection#873]
hi, I have a question, in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/guided_anchor_target.py#L103
to Line 119. The code set the regions in the all_ignore_map in the adjacent two feature maps of a gt region in a feature map between them to 1. I want to know the reason .thks very much.

anthor issue is , if the objects are occluded very seriously, I think this method is not very suitable theoretically ,right?

**Comment by alexwq100** [comment]
hi, I have a question, in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/anchor/guided_anchor_target.py#L103
to Line 119. The code set the regions in the all_ignore_map in the adjacent two feature maps of a gt region in a feature map between them to 1. I want to know the reason .thks very much.

**Comment by alexwq100** [comment]
@helloc

**Comment by alexwq100** [comment]
@hellock

**Comment by hellock** [comment]
For your first question, please refer to Section 3.4 of the paper.
For the second one, FPN can alleviate the occlusion issue to a great extent. If the center point of two objects are extremely close, there may be some missing detections.
