### ISSUE TITLE
Does slurm_train.sh support multi-machines and multi GPU ?

### ISSUE THREAD

**Issue by valuefish** [open-mmlab/mmdetection#874]
I found that there is no `--nodes` or `-N` option in `slurm_train.sh` script, does `slurm_train.sh` support multi-machines and multi GPU ?

**Comment by hellock** [comment]
It supports multiple nodes. The number of nodes are automatically specified.

**Comment by valuefish** [comment]
> It supports multiple nodes. The number of nodes are automatically specified.

Thanks for your reply! It's my misunderstanding. I have comprehended the magic under the hood after reviewing the code.
