### ISSUE TITLE
MMDetection installed in editable mode not detected

### ISSUE THREAD

**Issue by T0nepgi** [open-mmlab/mmdetection#8745]
Hello,

I am following the installation tutorial to install MMDetection in editable mode. I am not doing this in a conda environment though. 

I runned `pip install -v -e .` and the installation seems to be sucessfull. The command `pip list` displays mmdet.

But then verifying the installation using `mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .` shows :

```bash
File".../site-packages/mim/commands/download.py", line 75, in download
    raise RuntimeError(
RuntimeError: mmdet is not installed. Please install it first.
```

Any idea?

**Comment by ZwwWayne** [comment]
Please make sure that mmdet is correctly installed to the same environment as I'm.
You can simply try mim install mmdet.
