### ISSUE TITLE
ConcatDataset didn't have attribute `update_skip_type_keys` like MultiImageMixDataset

### ISSUE THREAD

**Issue by ykk648** [open-mmlab/mmdetection#8746]
When I trained yolox with 3 datasets, it fails when `num_last_epochs` starts, releated issue: #5997 #6055

`
No mosaic and mixup aug now!
train_loader.dataset.update_skip_type_keys(self.skip_type_keys)
raise AttributeError
`

**Comment by jbwang1997** [comment]
Only `MultiImageMixDataset` has update_skip_type_keys, please warp your dataset with `MultiImageMixDataset`.

**Comment by ykk648** [comment]
> 

that means only single dataset can be loaded during last aug-free epoches of yolox training, maybe `update_skip_type_keys` should added to `ConcatDataset`, I dont have time to do this so thank you for your reply.
