### ISSUE TITLE
Can’t upload new submissions to COCO evaluation server

### ISSUE THREAD

**Issue by HB-X** [open-mmlab/mmdetection#8750]
I want to test our model on COCO test-dev, but the old website (https://competitions.codalab.org/competitions/20794) is no longer available to submit new submissions. In the new website (https://codalab.lisn.upsaclay.fr/), I only find Robust Vision Challenge (COCO Box Detection) https://codalab.lisn.upsaclay.fr/competitions/6420, and this phase of the competition is closed. Is there another test method?

**Comment by jbwang1997** [comment]
The old website seems can still submit results.

**Comment by HB-X** [comment]
> 
I tried it again on the old website in participate (https://competitions.codalab.org/competitions/20794#participate), but it still can't submit submissions. 
![1662647335567](https://user-images.githubusercontent.com/74828078/189150466-4dcaa6a6-2bc2-462a-9e63-9279d4cf5e05.png)
![1662647767477](https://user-images.githubusercontent.com/74828078/189150585-0b0f17d4-7d7c-4aac-a8a1-61683b576047.png)

**Comment by jbwang1997** [comment]
I find a discussion [here](https://github.com/codalab/codalab-competitions/issues/3219). We need to wait for the organizers to transfer the competition to the new website.

**Comment by Cathy1900** [comment]
I had the same problem.

**Comment by HB-X** [comment]
The new website (https://codalab.lisn.upsaclay.fr/competitions/7384#participate) can submit the new submissions. 
This issue will be closed. Thank you.
