### ISSUE TITLE
RLE doesnt work for multiple masks per instance

### ISSUE THREAD

**Issue by FHarhammer** [open-mmlab/mmdetection#8751]
I am trying to train mask Rcnn using a COCO style dataset with masks in RLE format. For instances with multiple masks (because of occlusion) "iscrowd" is set to true to exclude it from the mAP calculation. Unfortunately mmdetection doesn't work with this setup for me. When i visualize my data with browse_dataset.py, all the masks which consists of multiple polygons are not displayed and also the training fails for this cases, so the network learns to not display objects which are partially occluded.

Is there a way to make this work?

I also tried to convert the RLE masks to Polygons. This works fine for most cases but not for cases where the mask has "Holes", so this is also not an option for me.

This is how my annotations look like if it consists out of multiple masks per instance:
` { 
   "id": 4,
   "image_id": 0,
   "category_id": 0,
   "segmentation": {
    "counts": [
     332906,
     7,
     737,
     ...,
     743,
     9,
     349007
    ],
    "size": [
     756,
     1008
    ]
   },
   "area": 0,
   "bbox": [
    440,
    218,
    107,
    111
   ],
   "iscrowd": 1,
   "extra": {}
  }`

**Comment by jbwang1997** [comment]
In CocoDataset, `iscrowd` objects will be ignored accoring to [this part of code](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L173-L179)

**Comment by FHarhammer** [comment]
Thanks a lot. I have used V7 Labs as an annotation tool and for some reason they mark all "complex" polygons which consist out of multiple parts or have holes as `iscrowd=1`. Another problem was that they, for some reason, don't provide the `area` for this type of polygons. After calculating the `area` for all polygons and setting them to `iscrowd=0` the training works fine.
