### ISSUE TITLE
Model return results slightly differ each inference

### ISSUE THREAD

**Issue by gggaugau** [open-mmlab/mmdetection#8759]
Hello. I use yolact model to infer on one image and notice slightly different results each time I run inference. However, I can not find any random code in test_pipeline or test_cfg. How do I stabilize the results for every inference, thanks in advance
```
1st infer:
... array([[2.8686313e+02, 1.2799496e+03, 6.9883295e+02, 1.7178850e+03,
        9.8540848e-01]], dtype=float32)], [[], [], [], [], [array([[0, 0, 0, ..., 0, 0, 0]
2nd infer:
... array([[2.8685156e+02, 1.2799402e+03, 6.9881934e+02, 1.7178893e+03,
        9.8541760e-01]], dtype=float32)], [[], [], [], [], [array([[0, 0, 0, ..., 0, 0, 0],
```

**Comment by hoya-cho** [comment]
i have same problem. In case of evaluation, the same result is confirmed, but in case of inference, different results are continuously coming out for the same image.

**Comment by BIGWangYuDong** [comment]
This maybe because of the random in PyTorch or CUDA ops, maybe you can try to set deterministic=True
