### ISSUE TITLE
cache_randomness explanation

### ISSUE THREAD

**Issue by levan92** [open-mmlab/mmdetection#8760]
Hi @ZwwWayne, saw that the latest release uses quite a bit of `cache_randomness` in the augmentation pipelines. May I know what is the function of these decorators and how it improves from previously without them? 

Why does some random augmentation use `cache_randomness` and some use `avoid_cache_randomness `?

**Comment by jbwang1997** [comment]
You can refer to the docstring in [mmcv.transforms.utils](https://github.com/open-mmlab/mmcv/blob/2.x/mmcv/transforms/utils.py#L15). Those decorators can cache the random number and apply them when you want to do the same operations again, like [TransformBroadcaster](https://github.com/open-mmlab/mmcv/blob/2.x/mmcv/transforms/wrappers.py#L353).

**Comment by levan92** [comment]
Just to clarify, does it mean that if decorated with `cache_randomness`, the random function/method will return the same value every single time, across every data iteration? 

From `TransformBroadcaster`, I understand that the main purpose of `cache_randomness` is so that the same random parameter in transformation can be propagated to other inputs. In this case, in the next data iteration (meaning another set of GTs/Imgs), will this random transformation parameter be sampled again or will the same cached value be used?

**Comment by jbwang1997** [comment]
The random parameter will be fixed only when `_cache_enabled` is set as True. `_cache_enabled` is controlled by `cache_random_params`.
