### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp89unhk4j/tmpklij7vey.py'

### ISSUE THREAD

**Issue by KingBigHandsome** [open-mmlab/mmdetection#8761]
When i start to train the model, it occur the problem
_`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp89unhk4j/tmpklij7vey.py'`_

I install the by the **installation**

**Comment by Likhith-Sugganahalli** [comment]
@KingBigHandsome check the entire output log, before this error, there will be other errors listed

**Comment by lijoe123** [comment]
This is the entire  @Likhith-Sugganahalli 
![image](https://user-images.githubusercontent.com/86214036/189324318-249fcb08-45ae-4cca-a8bd-f8c1808d2c1d.png)

**Comment by Likhith-Sugganahalli** [comment]
@lijoe123 the error is in the mask_rcnn_r50_fpn_2x_coco config file

**Comment by BIGWangYuDong** [comment]
What command did you use?  Please use the issue template
