### ISSUE TITLE
YOLOX_Head docs string

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmdetection#8764]
Hello, in label assignment step of YOLOX: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/yolox_head.py#L435  
shouldn't priors be [x_min, y_min, stride_w, stride_h] format, since [`offset_priors`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/dense_heads/yolox_head.py#L461) is [cx, cy, stride_w, stride_h] format?

**Comment by chhluo** [comment]
offset_priors are [cx + 0.5 * stride_w, cy + 0.5 * stride_h, stride_w, stride_h], priors are [cx, cy, stride_w, stride_h], see the comment https://github.com/open-mmlab/mmdetection/blob/f8bbba2fe777dd882a8da20625be858a98436703/mmdet/models/dense_heads/yolox_head.py#L459

**Comment by iumyx2612** [comment]
> offset_priors are [cx + 0.5 * stride_w, cy + 0.5 * stride_h, stride_w, stride_h], priors are [cx, cy, stride_w, stride_h], see the comment
> 
> https://github.com/open-mmlab/mmdetection/blob/f8bbba2fe777dd882a8da20625be858a98436703/mmdet/models/dense_heads/yolox_head.py#L459

thank you for the explanation, my bad!
