### ISSUE TITLE
two Resize in test_pipeline cause an error

### ISSUE THREAD

**Issue by zhangzscn** [open-mmlab/mmdetection#8767]
In the real world, the images are all produced by the same camera and are of the same size. Two times of Resize are required to simulate the impact of different model input sizes on model accuracy under the same picture size in the real environment.

For example, a Resize is first used to unify the annotated files to a resolution of 320*240, and then a Resize is used to unify the images to a resolution of 640*480 during model training for input into the model. Then test the accuracy of the model trained at 640*480 resolution when the annotated images are 320*240 resolution.

Some configuration files are as follows:

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', img_scale=(320,240), keep_ratio=False),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(640,480),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

The following error is displayed:
![微信图片_20220911101502](https://user-images.githubusercontent.com/13817275/189509059-d8bb9622-ff04-477e-a113-02abb427dab5.jpg)

真实环境中，图片都是一个相机出来的，图片大小一致。需要两遍Resize，模拟测试在真实环境中相同的图片大小的情况下，测试不同模型输入大小对模型精度的影响。
举个例子，先用一个Resize把标注文件都统一到320*240的分辨率下，再用一个Resize，把图片统一到模型训练时的分辨率640*480，用于输入到模型中，然后测试640*480分辨率下训练出来的模型在标注图片都为320*240分辨率下的一个精度情况。

**Comment by jbwang1997** [comment]
`Resize` pipeline will record `scale_factors`  in `results` in order to rescale the detected objects back to the original image scope.

I think the first `Resize` (resizing images into 320X240) can directly be applied to the dataset as preprocessing.

**Comment by ZwwWayne** [comment]
The written pipeline is equivelent to 
```
test_pipeline = [
dict(type='LoadImageFromFile'),
dict(
type='MultiScaleFlipAug',
img_scale=(640,480),
flip=False,
transforms=[
dict(type='Resize', keep_ratio=False),
dict(type='Normalize', **img_norm_cfg),
dict(type='ImageToTensor', keys=['img']),
dict(type='Collect', keys=['img']),
])
]
```
