### ISSUE TITLE
how to assign specific gpus in mmdetection during training?

### ISSUE THREAD

**Issue by GolvenDong** [open-mmlab/mmdetection#8768]
The documentation says I can use dist_trian.sh to train with mutiple gpus,but how to specify gpus? For example,I want to use gpu:2,3 to train my models.
The official tutorial can only specify the gpu numbers.

**Comment by jbwang1997** [comment]
You can add CUDA_VISIBLE_DEVICES="2,3" in the front of `dist_trainsh`
