### ISSUE TITLE
how to train with multiple GPUs？ errors occured，help，pls.

### ISSUE THREAD

**Issue by my-hello-world** [open-mmlab/mmdetection#877]
hi~，following is my nvidia-smi info，so i should train with 2GPUs or 3 GPUs?
```

> Every 10.0s: nvidia-smi                                 Wed Jun 26 17:27:55 2019
> 
> Wed Jun 26 17:27:55 2019
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.130                Driver Version: 384.130                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Quadro K4000        Off  | 00000000:01:00.0  On |                  N/A |
> | 30%   46C    P8    11W /  87W |    294MiB /  3016MiB |      8%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla K40c          Off  | 00000000:02:00.0 Off |                    0 |
> | 62%   71C    P0    69W / 235W |   1199MiB / 11439MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   2  Tesla K40c          Off  | 00000000:82:00.0 Off |                    0 |
> | 26%   49C    P8    25W / 235W |     11MiB / 11439MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+

```
**`  ./tools/dist_train.sh configs/guided_anchoring/ga_faster_x101_32x4d_fpn_1x.py 2`
 it was no response**
Wed Jun 26 17:46:10 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K4000        Off  | 00000000:01:00.0  On |                  N/A |
| 31%   48C    P8    11W /  87W |    284MiB /  3016MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40c          Off  | 00000000:02:00.0 Off |                    0 |
| 31%   68C    P0    67W / 235W |    667MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40c          Off  | 00000000:82:00.0 Off |                    0 |
| 31%   67C    P0    74W / 235W |    667MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
OR：
**`  ./tools/dist_train.sh configs/guided_anchoring/ga_faster_x101_32x4d_fpn_1x.py 3`**
get errors：
```
`index created!
Traceback (most recent call last):
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/hello/.conda/envs/torch1.1/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/guided_anchoring/ga_faster_x101_32x4d_fpn_1x.py', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>.
(torch1.1) hello@Server:/media/data/helloworld_/mmdetection$ Traceback (most recent call last):
  File "./tools/train.py", line 101, in <module>
    main()
  File "./tools/train.py", line 97, in main
    logger=logger)
  File "/media/data/helloworld_/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/media/data/helloworld_/mmdetection/mmdet/apis/train.py", line 144, in _dist_train
    model = MMDistributedDataParallel(model.cuda())
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/parallel/distributed.py", line 20, in __init__
    self._sync_params()
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/parallel/distributed.py", line 34, in _sync_params
    self.broadcast_bucket_size)
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/parallel/distributed.py", line 25, in _dist_broadcast_coalesced
    dist.broadcast(flat_tensors, 0)
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 806, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Broken pipe
`
```

**Comment by hellock** [comment]
Your GPU 0 is not suitable for training.

**Comment by my-hello-world** [comment]
> 
> 
> Your GPU 0 is not suitable for training.

Thanks Reply. i resoved it ,but i donnot kown how to close it.

**Comment by chiminhle** [comment]
> > Your GPU 0 is not suitable for training.
> 
> Thanks Reply. i resoved it ,but i donnot kown how to close it.

Hi. Could you please tell how to resolve it. I encounter the same error but dont know how to fix it. Thank you very much

**Comment by chiminhle** [comment]
> > > Your GPU 0 is not suitable for training.
> > 
> > 
> > Thanks Reply. i resoved it ,but i donnot kown how to close it.
> 
> Hi. Could you please tell how to resolve it. I encounter the same error but dont know how to fix it. Thank you very much

I resolved it. I realized that somewhere in my code that switch tensor computation to cpu that cause the error.
