### ISSUE TITLE
the channels of mask pred in mask-rcnn

### ISSUE THREAD

**Issue by UnmatchedKatana** [open-mmlab/mmdetection#8776]
My English is really poor and this is the first time I post an issue on github, so please forgive me for any confuse caused by my words. 
    Now this is the problem, when I debug the mask r-cnn, I find out that the mask_pred from fcn_mask_head doesn't have a background class. For example, I use a dataset which have 2 classes to debug mask r-cnn, then the mask_pred output from fcn_mask_head has 2 channels; while I switch to a 5 classes dataset, and the mask_pred has 5 channels. That confuse me beause if the mask_pred don't have a background class, then the "one-hot" gt of background pixels mast be a whole-zero veator, that will never be matched by mask_pred through a softmax, because softmax will make mask_pred normalizes rather than becoming an all zero vector. 
    So my question is how mask r-cnn in mmdetection deal with the background class exactly?

**Comment by jbwang1997** [comment]
The same question as https://github.com/open-mmlab/mmdetection/issues/8775.
