### ISSUE TITLE
如何实现 重叠滑窗预测,How to realize overlapping sliding window prediction,Add Sahi

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#8780]
**Describe the feature**

**Motivation**

比如9000*9000
不能直接滑窗裁剪

需要重叠裁剪 有重复部分
原图预测 自动裁剪

也可以批量对文件夹图片进行裁剪

建议增加 Sahi 重叠滑窗预测功能

For example, 9000 * 9000

You cannot directly slide the window to cut

If overlapping clipping is required, there will be duplicate parts

Automatic clipping of original image prediction

can also crop folder pictures in batches

It is suggested to add Sahi overlapping sliding window prediction function

**Related resources**
`https://github.com/obss/sahi`

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by hhaAndroid** [comment]
@monkeycc OK, let's investigate.

**Comment by monkeycc** [comment]
`https://github.com/PaddlePaddle/PaddleDetection/issues/6508`

PaddleDetection
Look at the efficiency of domestic framework

**Comment by hhaAndroid** [comment]
@monkeycc https://github.com/open-mmlab/mmyolo/blob/main/demo/large_image_demo.py
