### ISSUE TITLE
Reimplemented an NMS under mmdetection/mmdet/core/post_processing, and did not use the operation of mmcv.ops.nms. When called in the configuration file, it showed that it was not found.

### ISSUE THREAD

**Issue by 19990101lrk** [open-mmlab/mmdetection#8781]
Reimplemented an NMS under mmdetection/mmdet/core/post_processing, and did not use the operation of mmcv.ops.nms. When called in the configuration file, it showed that it was not found.

**Comment by 19990101lrk** [comment]
> This might because the file is not correctly imported.

It has been imported in _init_.py, but it is still not solved. What is the correct way to import?

**Comment by hhaAndroid** [comment]
@19990101lrk Thanks for your feedback, can you provide more details？
