### ISSUE TITLE
MMDet implement ATSS using anchor only?

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmdetection#8795]
`ATSSHead` is inherited from `AnchorHead`, which uses `anchor_generator` of type `AnchorGenerator`.  
However, `FCOSHead` is inherited from `AnchorFreeHead`, which uses `anchor_generator` of type `MlvlPointGenerator`, and this is the Anchor-free version.  
There is no implementation of `ATSSHead` Anchor-free version? ATSS paper has FCOS + ATSS Label Assignment, why don't MMDet implementation keep FCOS and implement extra label assignment step?

**Comment by jbwang1997** [comment]
For now, mmdetection only has implemented Anchor-based ATSS for benchmarking.

**Comment by iumyx2612** [comment]
> For now, mmdetection only has implemented Anchor-based ATSS for benchmarking.

Does mmdetection have any plan implementing Anchor-free ATSS soon? If no, can I make an issue in mmdeteciton to check my Anchor-free ATSS implementation when it finishes?

**Comment by ZwwWayne** [comment]
Sure, you can do that!

**Comment by ccomkhj** [comment]
Where can I find a sample of ATSS + FCOS?
