### ISSUE TITLE
How to convert the weights to detectron2 format for mask-rcnn pretrained on mmdetection?

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#8798]

**Comment by BIGWangYuDong** [comment]
There is a demo that can convert d2 faster rcnn to mmdet format.
https://github.com/BIGWangYuDong/mmdetection/blob/d2_tools/tools/misc/faster_rcnn_d2_to_mmdet.py

**Comment by RangiLyu** [comment]
Also, we will support training and testing detectron2 models in MMDetection soon. You can refer to this PR https://github.com/open-mmlab/mmdetection/pull/8672

**Comment by mitming** [comment]
Thanks a lot for all this.

**Comment by RangiLyu** [comment]
We have supported training Detectron2 models in dev-3.x branch. Welcome to try and feel free to open an issue if you met problems.
