### ISSUE TITLE
How to debug CUDA code?

### ISSUE THREAD

**Issue by arthur801031** [open-mmlab/mmdetection#880]
I've been modifying the code in `roi_align_kernel.cu`and wondering how to debug, setting a breakpoint, in this file. Please help. 

Thank you.

**Comment by arthur801031** [comment]
I've tried following this [guide](https://devtalk.nvidia.com/default/topic/1044724/debugger-for-python-amp-c-c-cuda/), but the program doesn't stop at any breakpoints.

**Comment by hellock** [comment]
Setting breakpoints in cuda codes may not be trivial, and usually I just use printf for debugging. Let's see if others can help with that.
