### ISSUE TITLE
COCO per Category evaluation problem

### ISSUE THREAD

**Issue by rohrii** [open-mmlab/mmdetection#8816]
I am currently training a custom dataset and everything works fine (training, config setup ...), but when i evaluate the results per category only 3 of 5 classes are achieving an AP above zero... :

`Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.296
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.565
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.272
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.144
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.298
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.345
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.345
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.345
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.209
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.347

+----------+-------+-------------+-------+----------+-------+
| category | AP    | category    | AP    | category | AP    |
+----------+-------+-------------+-------+----------+-------+
| PO1      | 0.468 | MobilePhone | 0.421 | PO2      | 0.000 |
| Laptop   | 0.000 | Tablet      | 0.592 | None     | None  |
+----------+-------+-------------+-------+----------+-------+
OrderedDict([('bbox_mAP', 0.296), ('bbox_mAP_50', 0.565), ('bbox_mAP_75', 0.272), ('bbox_mAP_s', 0.0), ('bbox_mAP_m', 0.144), ('bbox_mAP_l', 0.298), ('bbox_mAP_copypaste', '0.296 0.565 0.272 0.000 0.144 0.298')])`

I double checked my dataset (basic COCO format) and couldnt find any issues (negative values or something) so i dont know why those two classes (PO2 and Laptop) get an AP of zero... It also stays the same for multiple Epochs and it seems like only the other three classes get trained properly.

Can anyone help w this issue?

**Comment by BIGWangYuDong** [comment]
Have you checked the instance numbers of each class in your dataset? maybe PO2 and Laptop have a few instances, in which the detector cannot fully train these two classes.

**Comment by Robotatron** [comment]
Is there a way to output per class mAP scores to tensorboard?
