### ISSUE TITLE
Visualise and Fine-tuning model ATSS

### ISSUE THREAD

**Issue by bzha5848** [open-mmlab/mmdetection#8829]
### What is the problem this feature will solve?

fine-tuning the custom dataset and visualise the model network

### What is the feature you are proposing to solve the problem?

I need to freeze everything except the head of the model, and since currently the pre-trained model only trained 12 epoch for coco dataset, I also need either pre-trained model with 300 epoch on coco or pascal voc or do it by myself :(

**Comment by Czm369** [comment]
We have documentation tutorials that we hope will help you
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/finetune.md
