### ISSUE TITLE
How can I get the forward function of pretrain_RPN?

### ISSUE THREAD

**Issue by SuperCarryDFY** [open-mmlab/mmdetection#8836]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

Currently I am trying to use pretrain_RPN from mmdet to build my own model. However, what I need is not only the output of RPN, I also need image feature from ResNet( in RPN). So, I decide to decomposite the RPN model. I found it contains 3 modules, which is Resnet , FPN and RPN_head, repectively. I create 3 modules and assign them as ResNet, FPN, RPN_head. The problems is the output is different when I using pretrian_RPN model in a different ways.
> when I use what I learned from [Docs](https://mmdetection.readthedocs.io/en/latest/1_exist_data_model.html), I can get 1000 proposal coordinates and reliability rate.
> when I make a image go through 3 modules in sequence, I only get 2 tensor, their channel dimension is 12 and 3.

So, here is my question. How can I get 1000 proposal coordinates by using the second way( make images go through 3 module in squence)? I doubt there is some effort in the source code which can transfer the 2 tensor to proposal coordinates, but I can't found it. Other than that, what do channel dimension 12 and 3 means? How can I calculate 12 and 3?

### Environment

Python 3.8.13
mmdet 2.25.2
torch                   1.12.1
torch-summary           1.4.5
torchvision             0.13.1

**Comment by hhaAndroid** [comment]
@SuperCarryDFY Is it possible to use mmdet 3.x new version, that would be easier?

**Comment by SuperCarryDFY** [comment]
> @SuperCarryDFY Is it possible to use mmdet 3.x new version, that would be easier?

Sorry, I am not understand. It would be easier to find forward function in mmdet 3.x ?
