### ISSUE TITLE
multi gpu train is very imbalance

### ISSUE THREAD

**Issue by cizhenshi** [open-mmlab/mmdetection#884]
when I use cascade mask rcnn to train my data, I found that when I used single 1080ti, the imgs_per_gpu can set as 4, but when i used 2 1080ti, img_per_gpu can only set as 2, and the memory used for two gpu is 6000+mb and 3000+mb, which is very imbalance.
How can I do to use bigger batch size?

**Comment by hellock** [comment]
Are you using distributed training? Memory of each GPU should be similar.

**Comment by cizhenshi** [comment]
I follow the instruction and used ./tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM} [optional arguments] to train my model. The logger output"Distributed training: True". Is any other setting needed?

**Comment by cizhenshi** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 21%   24C    P8    10W / 250W |    511MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 21%   35C    P2    56W / 250W |   3639MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:83:00.0 Off |                  N/A |
| 21%   34C    P8    10W / 250W |   3207MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:84:00.0 Off |                  N/A |
| 28%   48C    P2    76W / 250W |   6547MiB / 11172MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
GPU1 and GPU3  I used.

**Comment by cizhenshi** [comment]
I think it is because my dataset, which have many objects, so the error "out of memory" occur. When out of memory occur, the training process seems to get stuck.
