### ISSUE TITLE
How to validate during training on a single GPU?

### ISSUE THREAD

**Issue by RocketFlash** [open-mmlab/mmdetection#885]
When I start training with --validate argument on a single GPU I don't get any validation result. Is it possible somehow get validation loss on each iteration ?

**Comment by hellock** [comment]
Validation is not supported in non-distributed training. Duplicated with #619.

**Comment by RocketFlash** [comment]
Thank you for quick response! 

Could you give some advice on how to train network without validation if there is only one GPU? By now I have only one idea : Make predictions on each epoch.pth and calculate losses and after that select model with lowest loss value. What do you think?

**Comment by hellock** [comment]
You may manually evaluate each checkpoint on the val set after the whole training process finishes.
