### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'get_targets'

### ISSUE THREAD

**Issue by baimuchu** [open-mmlab/mmdetection#8850]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

Traceback as follows
  
File "tools/train.py", line 244, in <module>
    main()
  File "tools/train.py", line 233, in main
    train_detector(
  File "/dataset/xx/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/xx/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xx/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/xx/.local/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/xx/.local/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/dataset/xxx/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xx/.local/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/dataset/xxx/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/dataset/xxx/mmdetection/mmdet/models/detectors/two_stage.py", line 147, in forward_train
    roi_losses = self.roi_head.forward_train(x, img_metas, proposal_list,
  File "/dataset/xxx/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 104, in forward_train
    bbox_results = self._bbox_forward_train(x, sampling_results,
  File "/dataset/xxx/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 137, in _bbox_forward_train
    bbox_targets = self.bbox_head.get_targets(sampling_results, gt_bboxes,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1094, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Sequential' object has no attribute 'get_targets'

### Environment

pip list
Package                          Version             Location
-------------------------------- ------------------- -------------------------------
absl-py                          1.2.0
addict                           2.4.0
alabaster                        0.7.12
apex                             0.1
appdirs                          1.4.4
argon2-cffi                      20.1.0
ascii-graph                      1.5.1
astunparse                       1.6.3
async-generator                  1.10
attrs                            20.3.0
audioread                        2.1.9
Babel                            2.9.0
backcall                         0.2.0
beautifulsoup4                   4.9.3
bleach                           3.3.0
blis                             0.7.4
boto3                            1.17.56
botocore                         1.20.56
brotlipy                         0.7.0
cachetools                       5.2.0
catalogue                        1.0.0
certifi                          2020.12.5
cffi                             1.14.3
chardet                          3.0.4
click                            7.1.2
codecov                          2.1.11
colorama                         0.4.5
commonmark                       0.9.1
conda                            4.10.1
conda-build                      3.21.4
conda-package-handling           1.7.2
coverage                         5.5
cryptography                     3.2.1
cxxfilt                          0.2.2
cycler                           0.10.0
cymem                            2.0.5
Cython                           0.28.4
DataProperty                     0.50.1
decorator                        5.0.6
defusedxml                       0.7.1
DLLogger                         0.1.0
docutils                         0.16
entrypoints                      0.3
filelock                         3.0.12
flake8                           3.7.9
Flask                            1.1.2
flatbuffers                      1.12
future                           0.18.2
gast                             0.4.0
glob2                            0.7
google-auth                      2.10.0
google-auth-oauthlib             0.4.6
google-pasta                     0.2.0
graphsurgeon                     0.4.5
grpcio                           1.37.0
h5py                             3.2.1
html2text                        2020.1.16
hypothesis                       4.50.8
idna                             2.10
imageio                          2.9.0
imagesize                        1.2.0
importlib-metadata               3.10.0
inflect                          5.3.0
iniconfig                        1.1.1
ipdb                             0.13.7
ipykernel                        5.5.3
ipython                          7.22.0
ipython-genutils                 0.2.0
itsdangerous                     1.1.0
jedi                             0.17.0
Jinja2                           2.11.3
jmespath                         0.10.0
joblib                           1.0.1
json5                            0.9.5
jsonschema                       3.0.2
jupyter-client                   6.1.12
jupyter-core                     4.7.1
jupyter-tensorboard              0.2.0
jupyterlab                       2.3.1
jupyterlab-pygments              0.1.2
jupyterlab-server                1.2.0
jupytext                         1.11.1
keras                            2.9.0
Keras-Preprocessing              1.1.2
kiwisolver                       1.3.1
libarchive-c                     2.9
libclang                         14.0.6
librosa                          0.8.0
llvmlite                         0.35.0
lmdb                             1.2.1
Mako                             1.1.4
Markdown                         3.3.4
markdown-it-py                   0.6.2
MarkupSafe                       1.1.1
maskrcnn-benchmark               0.1
matplotlib                       3.4.1
mbstrdecoder                     1.0.1
mccabe                           0.6.1
mdit-py-plugins                  0.2.6
mistune                          0.8.4
mlperf-compliance                0.0.10
mmcv-full                        1.6.1
mmdet                            2.25.2              /dataset/xxx/mmdetection
mock                             4.0.3
model-index                      0.1.11
msgfy                            0.1.0
murmurhash                       1.0.5
nbclient                         0.5.3
nbconvert                        6.0.7
nbformat                         5.1.3
nest-asyncio                     1.5.1
networkx                         2.0
nltk                             3.6.2
notebook                         6.2.0
numba                            0.52.0
numpy                            1.20.1
nvidia-dali-cuda110              1.0.0
nvidia-dlprof-pytorch-nvtx       1.1.0
nvidia-pyprof                    3.10.0
nvidia-tensorboard               1.15.0+nv21.4
nvidia-tensorboard-plugin-dlprof 1.2.0
oauthlib                         3.2.0
onnx                             1.8.0
onnxruntime                      1.7.0
openmim                          0.3.1
opt-einsum                       3.3.0
ordered-set                      4.1.0
packaging                        20.9
pandas                           1.1.4
pandocfilters                    1.4.3
parso                            0.8.2
pathvalidate                     2.4.1
pexpect                          4.8.0
pickleshare                      0.7.5
Pillow                           9.2.0
Pillow-SIMD                      7.0.0.post3
pip                              20.2.4
pkginfo                          1.7.0
plac                             1.1.0
pluggy                           0.13.1
polygraphy                       0.28.3
pooch                            1.3.0
preshed                          3.0.2
prettytable                      2.1.0
progressbar                      2.5
prometheus-client                0.10.1
prompt-toolkit                   3.0.17
protobuf                         3.15.8
psutil                           5.8.0
ptyprocess                       0.7.0
py                               1.10.0
pyasn1                           0.4.8
pyasn1-modules                   0.2.8
pybind11                         2.6.2
pycocotools                      2.0+nv0.5.1
pycodestyle                      2.5.0
pycosat                          0.6.3
pycparser                        2.20
pycuda                           2020.1
pydot                            1.4.2
pyflakes                         2.1.1
Pygments                         2.8.1
pynvml                           8.0.4
pyOpenSSL                        19.1.0
pyparsing                        2.4.7
pyrsistent                       0.17.3
PySocks                          1.7.1
pytablewriter                    0.47.0
pytest                           6.2.3
pytest-cov                       2.11.1
pytest-pythonpath                0.7.3
python-dateutil                  2.8.1
python-hostlist                  1.21
python-nvd3                      0.15.0
python-slugify                   4.0.1
pytools                          2021.2.3
pytorch-quantization             2.1.0
pytorch-transformers             1.1.0
pytz                             2021.1
PyWavelets                       1.1.1
PyYAML                           5.4.1
pyzmq                            22.0.3
regex                            2021.4.4
requests                         2.24.0
requests-oauthlib                1.3.1
resampy                          0.2.2
revtok                           0.0.3
rich                             12.5.1
rsa                              4.9
ruamel-yaml                      0.15.87
s3transfer                       0.4.2
sacrebleu                        1.2.10
sacremoses                       0.0.35
scikit-image                     0.15.0
scikit-learn                     0.24.1
scipy                            1.6.2
Send2Trash                       1.5.0
sentencepiece                    0.1.95
setuptools                       50.3.1.post20201107
six                              1.15.0
snowballstemmer                  2.1.0
SoundFile                        0.10.3.post1
soupsieve                        2.2.1
sox                              1.4.1
spacy                            2.3.5
Sphinx                           3.5.4
sphinx-glpi-theme                0.3
sphinx-rtd-theme                 0.5.2
sphinxcontrib-applehelp          1.0.2
sphinxcontrib-devhelp            1.0.2
sphinxcontrib-htmlhelp           1.0.3
sphinxcontrib-jsmath             1.0.1
sphinxcontrib-qthelp             1.0.3
sphinxcontrib-serializinghtml    1.1.4
srsly                            1.0.5
subword-nmt                      0.3.3
tabledata                        1.1.3
tabulate                         0.8.9
tensorboard                      2.9.1
tensorboard-data-server          0.6.1
tensorboard-plugin-wit           1.8.1
tensorflow                       2.9.1
tensorflow-estimator             2.9.0
tensorflow-io-gcs-filesystem     0.26.0
tensorrt                         7.2.3.4
termcolor                        1.1.0
terminado                        0.9.4
terminaltables                   3.1.10
testpath                         0.4.4
text-unidecode                   1.3
thinc                            7.4.5
threadpoolctl                    2.1.0
toml                             0.10.2
torch                            1.9.0a0+2ecb2c7
torchtext                        0.10.0a0
torchvision                      0.9.0a0
tornado                          6.1
tqdm                             4.53.0
traitlets                        5.0.5
typepy                           1.1.5
typing-extensions                4.3.0
uff                              0.6.9
Unidecode                        1.2.0
urllib3                          1.25.11
wasabi                           0.8.2
wcwidth                          0.2.5
webencodings                     0.5.1
Werkzeug                         1.0.1
wheel                            0.35.1
wrapt                            1.14.1
yacs                             0.1.8
yapf                             0.32.0
zipp                             3.4.1

**Comment by jbwang1997** [comment]
Would you provide more information, like the model you use?

**Comment by ZwwWayne** [comment]
Closed because of lack of necessary information to reproduce the error.

**Comment by bliblioscar** [comment]
It said that the  'Sequential' object has no attribute 'get_targets' in torch.nn.module.modules. It seems that the torch version is not support this task. I also face this question and check the requirement the author of mmdetectron mentioned. Even though, they claim that the torch version can be 1.3+, I still can not fix this problem. (my torch version is 1.7.0)
Can somebody tell me which torch version can solve this issue? Or how to refine the source code? Thx!

**Comment by bliblioscar** [comment]
I found the solution! You can try to remove the "[ ]" in bbox_head, so that the bbox_head will be the dict instead of list.

_________________________________________________________________
# 2. model settings

# explicitly over-write all the `num_classes` field from default 80 to 5.
model = dict(
    roi_head=dict(
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                # explicitly over-write all the `num_classes` field from default 80 to 5.
                num_classes=5),
            dict(
                type='Shared2FCBBoxHead',
                # explicitly over-write all the `num_classes` field from default 80 to 5.
                num_classes=5),
            dict(
                type='Shared2FCBBoxHead',
                # explicitly over-write all the `num_classes` field from default 80 to 5.
                num_classes=5)],
    # explicitly over-write all the `num_classes` field from default 80 to 5.
    mask_head=dict(num_classes=5)))
