### ISSUE TITLE
About yolox_head 'gt_bboxes_ignore'

### ISSUE THREAD

**Issue by paihuai0** [open-mmlab/mmdetection#8856]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

when I read yolox_head code I see "gt_bboxes_ignore" but in this code I don't find how I can use it,it only a parameter in this code，but I want know how to use "gt_bboxes_ignore" in yolox_head ,thakns!

### Environment

python=3.8

**Comment by RangiLyu** [comment]
YOLOX uses SimOTA assigner which does not process the `gt_bboxes_ignore`. If you want to use it, you need to modify the assigner.
