### ISSUE TITLE
how can i change detection model for semantic segmentation task such as mask_RCNN

### ISSUE THREAD

**Issue by Wanyidon** [open-mmlab/mmdetection#8891]
### Model/Dataset description

i want to change a detection model for semantic segmentation to test my tasks, but i have no idea now.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available.

**Comment by hhaAndroid** [comment]
@Wanyidon I don't think it's necessary. Maybe you can get the idea from `mmseg`
