### ISSUE TITLE
Found bug (by code inspection)

### ISSUE THREAD

**Issue by planaria158** [open-mmlab/mmdetection#8892]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

CascadeRoIHead(BaseRoIHead, BBoxTestMixin, MaskTestMixin)
BBoxTestMixin has method: simple_test_bboxes

It will likely crash on line 89:  bbox_results = self._bbox_forward(x, rois). 

CascadeRoIHead's implementation of this method shows this signature: def _bbox_forward(self, stage, x, rois):
(Note, the parameter 'stage' is missing from the BBoxTestMixin's call.

Note: the only other class that uses the above Mixin classes, is StandardRoIHead(BaseRoIHead, BBoxTestMixin, MaskTestMixin).  The implementation of _bbox_forward in this class agrees with the signature from BBoxTestMixin.

Therefore, I wonder is self._bbox_forward(x, rois) ever called?  (or perhaps not ever called when training CascadeRCNN?).  It should crash if it is called.

### Environment

Environment probably not relevant since I "found" the above bug candidate by code inspection.

**Comment by hhaAndroid** [comment]
@planaria158 This is correct, but it may be the static code cannot be checked. We will improve it in the 3.x branch.
