### ISSUE TITLE
faster_rcnn导出onnx模型时使用--verfiy参数报错

### ISSUE THREAD

**Issue by Chriost** [open-mmlab/mmdetection#8898]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

command:
`python tools/deployment/pytorch2onnx.py  configs/faster_rcnn/faster_rcnn_r50_fpn_2x_coco.py  work_dirs/faster_rcnn_r50_fpn_2x_coco/epoch_24.pth --verify`

load checkpoint from local path: work_dirs/faster_rcnn_r50_fpn_2x_coco/epoch_24.pth
load checkpoint from local path: work_dirs/faster_rcnn_r50_fpn_2x_coco/epoch_24.pth
/home/CaiYingJie/workshop/Swin-Transformer-Object-Detection-master/mmdet/models/dense_heads/rpn_head.py:124: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  nms_pre_tensor = torch.tensor(
/home/CaiYingJie/workshop/Swin-Transformer-Object-Detection-master/mmdet/models/dense_heads/rpn_head.py:129: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rpn_cls_score.size()[-2:] == rpn_bbox_pred.size()[-2:]
/home/CaiYingJie/workshop/Swin-Transformer-Object-Detection-master/mmdet/models/dense_heads/rpn_head.py:145: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nms_pre_tensor > 0:
/home/CaiYingJie/workshop/Swin-Transformer-Object-Detection-master/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:78: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/home/CaiYingJie/workshop/Swin-Transformer-Object-Detection-master/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:80: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/torch/tensor.py:587: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  warnings.warn('Iterating over a tensor might cause the trace to be incorrect. '
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/mmcv/ops/nms.py:298: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/mmcv/ops/nms.py:306: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if boxes_for_nms.shape[0] < split_thr or torch.onnx.is_in_onnx_export():
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/mmcv/ops/nms.py:159: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/mmcv/ops/nms.py:160: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/mmcv/ops/roi_align.py:80: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.size(1) == 5, 'RoI must be (idx, x1, y1, x2, y2)!'
/home/CaiYingJie/workshop/Swin-Transformer-Object-Detection-master/mmdet/core/post_processing/bbox_nms.py:36: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] > 4:
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:2620: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn("Exporting aten::index operator of advanced indexing in opset " +
/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:661: UserWarning: This model contains a squeeze operation on dimension 1. If the model is intended to be used with dynamic input shapes, please use opset version 11 to export the model.
  warnings.warn("This model contains a squeeze operation on dimension " + str(squeeze_dim) + ". If the model is " +
**Successfully exported ONNX model: tmp.onnx**
2022-09-28 14:25:22.000022872 [W:onnxruntime:, graph.cc:1220 Graph] Initializer 2416 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
onnxruntime output names: ['boxes', 'labels'],             output shapes: [(100, 5), (100,)]
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 231, in <module>
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 147, in pytorch2onnx
    np.testing.assert_allclose(
  File "/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/CaiYingJie/anaconda3/envs/swin/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 763, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

(shapes (1, 5), (0, 5) mismatch)
 x: array([[5.362104e+02, 4.808753e+02, 5.736962e+02, 5.813888e+02,
        1.238688e-02]], dtype=float32)
 y: array([], shape=(0, 5), dtype=float32)

### Environment

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) [GCC 10.3.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (GCC) 5.2.0
PyTorch: 1.8.1+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
 
TorchVision: 0.9.1+cu102
OpenCV: 4.6.0
MMCV: 1.4.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.11.0+

### Additional information

1，更改了输入图片的尺寸大小，其他配置文件没有改动
2，使用的是coco数据集

**Comment by ZwwWayne** [comment]
Changing the input size may cause the model cannot detect images, which is not guaranteed success. Please refer to MMDeploy for more details.
