### ISSUE TITLE
pos_assigned_gt_inds out of bounds of gt_mask when using my own data

### ISSUE THREAD

**Issue by Liu0329** [open-mmlab/mmdetection#890]
Hi, I am using my own data with instance masks. The new data I/O now works. But I have an error in function **mask_target_single** in **mask_target.py**.
```
File "/home/code/mmdetection/mmdet/core/mask/mask_target.py", line 27, in mask_target_single
    gt_mask = gt_masks[pos_assigned_gt_inds[i]]
IndexError: index 6 is out of bounds for axis 0 with size 6
```

By
```
print(gt_masks.shape)
print(pos_assigned_gt_inds)
```
I got
```
(6, 960, 800)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 4, 4, 4, 4, 4, 1, 4], device='cuda:0')
```
The reason is that the index is larger than the number of gt_masks.
But I don't know why this would happen... and the role of mask_target.py ?

**Comment by hellock** [comment]
Could you also print the gt bbox shape, I guess that the number of gt bboxes is different from masks.

**Comment by Liu0329** [comment]
@hellock You are right. Now I have solved it. Thanks !

**Comment by WangBoying** [comment]
How did you solve this problem? i met the same problem! @Liu0329
