### ISSUE TITLE
How to join SAHI while training and reasoning

### ISSUE THREAD

**Issue by shuoshuo09** [open-mmlab/mmdetection#8903]
### What is the problem this feature will solve?

Optimize the detection effect of small objects

### What is the feature you are proposing to solve the problem?

SAHI

**Comment by hhaAndroid** [comment]
@shuoshuo09 It is already in the plan, welcome to continue to pay attention.

**Comment by austinmw** [comment]
@hhaAndroid Hi, do you know if part of the plan is to add SAHI option for [mmdet2torchserve.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/mmdet2torchserve.py) and [mmdet_handler.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/mmdet_handler.py)?

**Comment by hhaAndroid** [comment]
> @hhaAndroid Hi, do you know if part of the plan is to add SAHI option for [mmdet2torchserve.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/mmdet2torchserve.py)/[mmdet_handler.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/mmdet_handler.py)?

Yes. Development this month

**Comment by austinmw** [comment]
@hhaAndroid Hi, thanks for your response! I'm having trouble finding this PR and how to enable this feature. Could you please add link when you get a chance?

**Comment by thiagoribeirodamotta** [comment]
Was Sahi support added for online training? Is there any examples demonstrating how to use it?

**Comment by thiagoribeirodamotta** [comment]
I ended up creating a feature request [over here](https://github.com/open-mmlab/mmengine/issues/1412) as well.
