### ISSUE TITLE
Coco Map Evaluation of results.json

### ISSUE THREAD

**Issue by barrendo** [open-mmlab/mmdetection#8912]
Hello,

![image](https://user-images.githubusercontent.com/39887076/193017391-0efde135-666e-45f1-b96e-d3f3ff1081f6.png)

The screenshot shows how I save my predictions as a json file. Is it possible to calculate the mAP with the results.json as input? Background is that I want to evaluate external predictions from darknet on MMdetection.

**Comment by RangiLyu** [comment]
You can use https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/coco_error_analysis.py

**Comment by barrendo** [comment]
thank you:)
