### ISSUE TITLE
3.x branch documentation is broken

### ISSUE THREAD

**Issue by JihwanEom** [open-mmlab/mmdetection#8914]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

Hi, I tried to access here: https://mmdetection.readthedocs.io/en/v3.0.0rc0/user_guides/semi_det.html but the page does not exist. The documentation for 3.x branch is broken now.

### Environment

No env

**Comment by RangiLyu** [comment]
Try again. I rebuild the doc and it should be available now.

**Comment by JihwanEom** [comment]
Works perfectly! Thank you :)
