### ISSUE TITLE
mmdetection uses only single gpu even though multiple gpus are available and visible (On Slurm)

### ISSUE THREAD

**Issue by echonax07** [open-mmlab/mmdetection#8915]
### Prerequisite

- [x] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

So I am trying to follow the tutorial on training with the [custom dataset](https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html). 

I submit the following script using `sbatch train_detector.sh` to submit on slurm

`
#!/bin/bash

#SBATCH --nodes=1

#SBATCH --gpus-per-node=v100l:2
#SBATCH --ntasks-per-node=1

#SBATCH --mem=32G

#SBATCH --time=02:00:00

#SBATCH --output=../output_logs/train-%j.out

module load python/3.7
module load scipy-stack

echo "Creating new virtualenv"
virtualenv --no-download ~/mmdet
source ~/mmdet/bin/activate

pip install --no-index --upgrade pip
pip install torch==1.10.0+computecanada torchvision==0.11.1+computecanada
pip install mmcv-full==1.4.4 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html
pip install mmdet
pip install wandb

cd /project/6075102/share/whale/mmwhale/

python -u tools/train.py configs/balloon/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_balloon.py --launcher="slurm"
`
I also log the runtime data to wandb by adding the following lines in the train.py file

`
cfg.log_config.hooks = [
    dict(type='TextLoggerHook'),
    dict(type='MMDetWandbHook',
         init_kwargs={'project': 'mmdetection'},
         interval=10,
         log_checkpoint=True,
         log_checkpoint_metadata=True,
         num_eval_images=100,
         bbox_score_thr=0.3)]
`
This is the system statistics from wandb. 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/48488272/193146913-148f4713-2a85-4de1-aff6-9c722e4e9ca3.png">

**I don't understand why the 2nd GPU is not utilized.** 

Any suggestion/help would be highly appreciated

### Environment

sys.platform: linux
Python: 3.8.10 (default, Jun 16 2021, 14:20:20) [GCC 9.3.0]
CUDA available: True
GPU 0,1: Tesla V100-SXM2-32GB
CUDA_HOME: None
GCC: gcc (GCC) 9.3.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.2  (built against CUDA 11.3)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=flexi, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.2.0, CXX_COMPILER=/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin/c++, CXX_FLAGS= -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=flexi, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1
OpenCV: 4.5.1
MMCV: 1.4.4
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.4
MMDetection: 2.25.2+f9b9ed8

### Additional information

I am attaching my output file from slurm if it's helpful
[train-45930117.txt](https://github.com/open-mmlab/mmdetection/files/9679242/train-45930117.txt)

**Comment by RangiLyu** [comment]
Please refer to the slurm_train script: https://github.com/open-mmlab/mmdetection/blob/3.x/tools/slurm_train.sh
