### ISSUE TITLE
How can I deal such imgaes and anns?

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmdetection#8918]
In myself data, I only have a ann file of images, but the images are in several dir like below, how can I deal such problem?
![image](https://user-images.githubusercontent.com/54987492/193177560-0d7c1518-d11b-4568-8faa-dee3041468f6.png)
![1664505228744](https://user-images.githubusercontent.com/54987492/193177657-449b88c4-43a7-40f6-a4ee-8a4e372f4298.png)

**Comment by BIGWangYuDong** [comment]
I think you can process your json file to deal with the image path.

**Comment by baibaidedongdong** [comment]
> I think you can process your json file to deal with the image path.
What does it mean?

**Comment by baibaidedongdong** [comment]
> I think you can process your json file to deal with the image path.

Oh, I know, I can make json‘s "img_name" to absolute path.
