### ISSUE TITLE
./tools/dist_train.sh is do bn operation cross multi gpus?

### ISSUE THREAD

**Issue by shuoshuoa** [open-mmlab/mmdetection#892]

**Comment by hellock** [comment]
"BN" indicates batchnorm within each GPU, and "SyncBN" indicates batchnorm across all GPUs. "BN" is used by default, e.g., https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/resnet.py#L375

**Comment by shuoshuoa** [comment]
i get, thanks!!!
