### ISSUE TITLE
mask padding problem using my own data

### ISSUE THREAD

**Issue by Liu0329** [open-mmlab/mmdetection#893]
I use my data with instance masks to train.  The problem occurs in **class MaskTransform** in **transforms.py** when padding masks. 
```
padded_masks = [
            mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
        ]
```
The error is
```
File "/home/code/mmdetection/mmdet/datasets/transforms.py", line 112, in <listcomp>
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/home/miniconda3/lib/python3.6/site-packages/mmcv/image/transforms/geometry.py", line 183, in impad
    assert shape[i] >= img.shape[i]
AssertionError
```
I found indeed some **pad_shape < mask.shape**. So when would this happen ? Maybe some of my data are wrong ?

**Comment by hellock** [comment]
This is usually caused by some images whose annotation (height and width) is different from the shape of the loaded images. Related to ##482.

**Comment by Liu0329** [comment]
@hellock You are right. I have used the actual shape of images and the problem is solved. Thanks for your constant help !

**Comment by sanli0** [comment]
你好，请问你是如何解决的呢，我的训练图片的size是每张都不一样的，也是报了跟你一样的错误。但是我在其他的网络中都能使用，我该如何更改这个code呢？

**Comment by xlim1996** [comment]
@sanli0  请问你解决这个问题了吗

**Comment by sanli0** [comment]
应该是解决了，但是具体的解决方法我有点忘了，老早嗯嗯问题



---- 回复的原邮件 ----
| 发件人 | Xiaolin ***@***.***> |
| 日期 | 2023年03月07日 20:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [open-mmlab/mmdetection] mask padding problem using my own data (#893) |

@sanli0 请问你解决这个问题了吗

**Comment by xlim1996** [comment]
@sanli0  ok 谢谢啦

**Comment by sanli0** [comment]
你那个还没解决的话可以找我我给你看一下



---- 回复的原邮件 ----
| 发件人 | Xiaolin ***@***.***> |
| 日期 | 2023年03月07日 20:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [open-mmlab/mmdetection] mask padding problem using my own data (#893) |

@sanli0 ok 谢谢啦
