### ISSUE TITLE
When test cascade_rcnn got unexpected key error

### ISSUE THREAD

**Issue by qiansi** [open-mmlab/mmdetection#894]
unexpected key in source state_dict: bbox_head.fc_cls.weight, bbox_head.fc_cls.bias, bbox_head.fc_reg.weight, bbox_head.fc_reg.bias, bbox_head.shared_fcs.0.weight, bbox_head.shared_fcs.0.bias, bbox_head.shared_fcs.1.weight, bbox_head.shared_fcs.1.bias

missing keys in source state_dict: bbox_head.0.fc_reg.weight, bbox_head.2.fc_cls.bias, bbox_head.2.fc_cls.weight, bbox_head.2.fc_reg.bias, bbox_head.0.shared_fcs.0.bias, bbox_head.1.fc_cls.weight, bbox_head.1.fc_reg.weight, bbox_head.1.shared_fcs.1.weight, bbox_head.1.shared_fcs.0.weight, bbox_head.0.shared_fcs.1.weight, bbox_head.1.shared_fcs.0.bias, bbox_head.1.fc_cls.bias, bbox_head.0.shared_fcs.0.weight, bbox_head.1.fc_reg.bias, bbox_head.0.fc_cls.bias, bbox_head.0.shared_fcs.1.bias, bbox_head.0.fc_cls.weight, bbox_head.2.shared_fcs.1.weight, bbox_head.2.shared_fcs.1.bias, bbox_head.1.shared_fcs.1.bias, bbox_head.2.fc_reg.weight, bbox_head.0.fc_reg.bias, bbox_head.2.shared_fcs.0.bias, bbox_head.2.shared_fcs.0.weight

**Comment by BlueBlueFF** [comment]
#644

**Comment by JasseurHadded1** [comment]
But that affects computation no?
