### ISSUE TITLE
TypeError: can only concatenate list (not "str") to list

### ISSUE THREAD

**Issue by LvAoAo** [open-mmlab/mmdetection#8943]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

 File ".../.conda/envs/my_env/lib/python3.7/site-packages/mmdet-2.25.2-py3.7.egg/mmdet/utils/collect_env.py", line 11, in collect_env
    env_info['MMDetection'] = mmdet.__version__ + '+' + get_git_hash()[:7]
TypeError: can only concatenate list (not "str") to list

So how this problem arises? I just followed the mmdetection installment, and then when Irun the train.py in mmdet/tools I got this  bug report

### Environment

mmdet                     2.25.2   
mmcv-full                 1.6.2 
pytorch                   1.12.1  
python                    3.7.13

**Comment by ZwwWayne** [comment]
Could you describe which command you use?

**Comment by LvAoAo** [comment]
> Could you describe which command you use?

Thank you for your reference.
I just use
python3 tools/train.py ...
,which is rewrited by other mmdetection user [FGD](https://github.com/yzd-v/FGD)

I've found the mistake caused by my extra operation in the file **mmdet.__init__.py**
So when I **reinstall the mmdetection** and pay more attention to using **the compatible version** .I got my program run successfully.
