### ISSUE TITLE
Model implementation is not in the models registry.

### ISSUE THREAD

**Issue by b-sia** [open-mmlab/mmdetection#8951]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [ ] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

I tried to implement my version of the UNet backbone. I added the class to the registry using @BACKBONES.register_module() function. 
mmdet/models/backbone/unet.py
```
# 
@BACKBONES.register_module()
class UNet(BaseModule):

    def __init__(self, n_channels, n_classes, bilinear=False):
        super(UNet, self).__init__()

        self.n_channels = n_channels
        self.n_classes = n_classes
        self.bilinear = bilinear
``` 

I then modified my config file with the new backbone.

```
# maskrcnn_unet.py

# some other config
model = dict(
    type='MaskRCNN',
    backbone=dict(
            type="UNet",
            n_channels=1,
            n_classes=1,
            bilinear=False
        ),
       # ...
)
```
# some other config
However, during training, the model could not find the backbone as it is not in the model registry.

```
Traceback (most recent call last):
  File "F:\tree_segmentation\train.py", line 242, in <module>
    main()
  File "F:\tree_segmentation\train.py", line 212, in main
    model = build_detector(
  File "C:\Users\Deployment\.conda\envs\mmdetection\lib\site-packages\mmdet\models\builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "C:\Users\Deployment\.conda\envs\mmdetection\lib\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Users\Deployment\.conda\envs\mmdetection\lib\site-packages\mmcv\cnn\builder.py", line 28, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\Deployment\.conda\envs\mmdetection\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "MaskRCNN: 'UNet is not in the models registry'"
```

### Environment

fatal: not a git repository (or any of the parent directories): .git
sys.platform: win32
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.8
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30145 for x64
GCC: n/a
PyTorch: 1.10.1+cu102
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.2+cu102
OpenCV: 4.6.0
MMCV: 1.6.1
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.2
MMDetection: 2.25.1+

### Expected results

Expected training epochs output to be printed.

### Additional information

No, I did not modify any other portions of the code. I only added unet.py into mmdet/models/backbones directory. The model implementation is taken from here (https://github.com/milesial/Pytorch-UNet/blob/master/unet/unet_model.py).

I replaced nn.module superclass with the BaseModule wrapper and I added the @BACKBONES.register_module() decorator to my backbone class.

**Comment by RangiLyu** [comment]
Did you import the module? Please follow the guide https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#import-the-module
