### ISSUE TITLE
What is the format for masks when using CustomDataset?

### ISSUE THREAD

**Issue by i-pan** [open-mmlab/mmdetection#896]
Hi, 

Thank you for the great documentation regarding training on custom datasets. I was unable to find the correct format for specifying masks in the annotations. My guess is that for each bounding box there should be a corresponding binary array in `annotation['ann']['masks']` with the same dimensions as the image. 

For example, a file with 4 bounding boxes on a 1200 x 800 image would have **binary** mask annotations of size 4 x 1200 x 800, even if they are each of different classes. 

Thanks for your help.

**Comment by hellock** [comment]
For COCO-style datasets, masks are annotated with polygons and stored in the json file after being encoded. In the dataset, these annotations will be decoded to binary masks, and you can refer to [_parse_ann_info()](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L56) for details.
For custom datasets with mask annotations, you can either (1) convert the mask annotation to the format compatible with COCO dataset, or (2) override the `get_ann_info` method as mentioned in the documentation. I prefer the second choice.

**Comment by dy2728** [comment]
@hellock  

Hi, 

I have the same question as @i-pan , and I looked up the founction "get_ann_info" in coco.py. However, it said "masks are raw annotations and not decoded into binary masks". I can not find where the polygon annotations has been converted to binary masks, could you tell me about it? 

Thanks!

**Comment by edk-bh** [comment]
It looks like native support for binary masks is no longer possible after a commit on July 4, 2019 (https://github.com/open-mmlab/mmdetection/commit/0d5233a32dac4288760f6d819ddfef9c1e020cf7).

Now it looks like annotations must be in COCO segmentation format. If you have binary masks, you can do a mask-to-COCO preprocessing step, or override `get_ann_info` to convert the mask to COCO dynamically.
