### ISSUE TITLE
YOLOX use base configs instead of hardcode

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmdetection#8961]
### What is the problem this feature will solve?

YOLOX configs hardcode the following:

`data_root`, `dataset_type`, `max_epochs`, `num_last_epochs`, `interval`

Which is different from other configs which use:

```python
_base_ = [
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
```

### What is the feature you are proposing to solve the problem?

Use the base definitions instead of hardcoding in yolox

### Additional

Also curious, why does is this warning needed?
https://github.com/open-mmlab/mmdetection/blob/d81990802cbd80f6d49fc35cdd255ebc353e4541/mmdet/core/utils/dist_utils.py#L119
Seems only might be used for yolox too

**Comment by RangiLyu** [comment]
YOLOX's data loading and schedule settings are totally different from the base configs. So we choose not to inherit the base data config. The base config of YOLOX series is yolox-s, you can modify the data path and epochs in that config.
