### ISSUE TITLE
Some questions about confusion_matrix.py

### ISSUE THREAD

**Issue by paihuai0** [open-mmlab/mmdetection#8974]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

When I use confusion_matrix.py, I print the dataset, for one of my categories, it shows that the number is 29072, but when I draw the confusion matrix, the overall number of the class becomes 30600, the number of tp + fn The number exceeds the total number of datasets, what is the reason for this? Is there any influences?

### Environment

Linux 
Python 3.8
PyTorch 1.3+
CUDA 9.2+
GCC 5+
MMCV

**Comment by ZwwWayne** [comment]
@RangiLyu please take a look.

**Comment by RangiLyu** [comment]
The number of "tp + fn" is the number of predictions. The number of the bboxes in the dataset represents ground truths. It's normal that there is a gap between the number of predictions and the number of ground truths.

**Comment by paihuai0** [comment]
I see, thank you

**Comment by sofpya** [comment]
> The number of "tp + fn" is the number of predictions. The number of the bboxes in the dataset represents ground truths. It's normal that there is a gap between the number of predictions and the number of ground truths.
 I have same the problem, i also have the one class with 950 GT. And i got the FP:274. Is there have wrong?
