### ISSUE TITLE
what's the purpose of +/-0.5 here in bbox/delta transform

### ISSUE THREAD

**Issue by liangyuandg** [open-mmlab/mmdetection#899]
https://github.com/open-mmlab/mmdetection/blob/c6544a72dfb55d14277f15a67087fba6121611a1/mmdet/core/bbox/transforms.py#L58

**Comment by hellock** [comment]
To be consistent with [`bbox2delta()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/transforms.py#L6).
