### ISSUE TITLE
model.show_result don't work without out_file param.

### ISSUE THREAD

**Issue by leonlee723** [open-mmlab/mmdetection#8997]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

I'm beginner. When I runned the first Demo of 1_exist_data_model.html model.show_result(img, result) didn't get any react. 
![image](https://user-images.githubusercontent.com/2637309/195041245-104b1a0a-55ba-4097-bec8-78f36392b999.png)

But when added out_file param (model.show_result(img, result, out_file='result2.jpg')), I got the correct file in folder. So I want to know What can I modify? 

### Environment

PyTorch 1.12.1 + cu116

**Comment by jbwang1997** [comment]
You can refer to [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L284-L310) for the details of the arguments of `model.show_result()`.

If you don't set `show=True` and `out_file='result2.jpg'`, `show_result` will directly return the image with results.

**Comment by leonlee723** [comment]
Thank you very much, resolve my problem.
