### ISSUE TITLE
Error occurred in modifying and reading image data

### ISSUE THREAD

**Issue by zhenbangW** [open-mmlab/mmdetection#9014]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

I want to read the four channel tif format image data. At present, I modify LoadImageFromFile, img=mmcv Imfrombytes (img_bytes, backend='tifffile '), but the following error was encountered, img=tifffile. imread (buff)
AttributeError: 'NoneType' object has no attribute 'imread'

![image](https://user-images.githubusercontent.com/44695439/195553362-ebca94ce-db4d-4cd4-bdc7-2687b90f604c.png)
![image](https://user-images.githubusercontent.com/44695439/195553463-cb5110ca-a662-4901-a68b-b773c6ab3066.png)

### Environment

fatal: Not a git repository (or any parent up to mount point /data)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-32GB
CUDA_HOME: /data/apps/cuda/10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.10
GCC: gcc (GCC) 7.5.0
PyTorch: 1.6.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0+cu101
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.24.1+

**Comment by RangiLyu** [comment]
Did you install tifffile? Try to run python and import tifffile to see if it is installed correctly.

**Comment by zhenbangW** [comment]
> Did you install tifffile? Try to run python and import tifffile to see if it is installed correctly.
First of all, thank you very much for your reply, but the tifffile is used in mmcv, not defined by me. I try to import tifffile and report ModuleNotFoundError: No module named 'tifffile'.

![b3136dfa1d253a2d98403068f74347c](https://user-images.githubusercontent.com/44695439/195562438-8962b743-9e94-4971-a736-b0f9609fa727.png)

**Comment by RangiLyu** [comment]
tifffile is a third part library. Try to run `pip install tifffile`.

**Comment by zhenbangW** [comment]
> tifffile is a third part library. Try to run `pip install tifffile`.

Thank you very much for your help. I really solved the problem by installing the tifffile package

**Comment by Armandase** [comment]
You can also provide "local" as backend in your train & test pipeline and "pillow" in imdecode_backend. Thoses params handle tifffile and pillow is used to read 32-bit data
