### ISSUE TITLE
two-stage Deformable DETR's enc_losses are different between mmdet3.0.0rc1 and given log

### ISSUE THREAD

**Issue by marsgravity** [open-mmlab/mmdetection#9021]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

case 1, I run configs/deformable_detr/deformable-detr_refine_twostage_r50_16xb2-50e_coco.py in mmdet3.0.0rc1 without changing any code , the enc_losses include enc_loss_cls, enc_loss_bbox, enc_loss_iou are unstable compared with the given log, such as in 50th epoch, the given log's enc_loss_cls is stable at 0.36-0.39, enc_loss_bbox is stable at 0.18, enc_loss_iou is stable at 0.41-0.43. But my training log's enc_loss_cls get max 1.82 min 0.08, enc_loss_bbox get max 0.64 min 0.03, enc_loss_iou get max 2.85 min 0.03.

### Environment

I use pytorch1.12 mmcv2.0.0rc1 mmengine0.0.1, ensure the normal operation of other algorithms.

**Comment by marsgravity** [comment]
[log.zip](https://github.com/open-mmlab/mmdetection/files/9782792/log.zip)
This is the complete log I training on mmdet3.0.0rc1.

**Comment by jshilong** [comment]
Does the performance drop after migrating to 3.0？

**Comment by marsgravity** [comment]
> Does the performance drop after migrating to 3.0？

No, it doesn't. The finally epoch's performance is as follows. 
`{"coco/bbox_mAP": 0.47, "coco/bbox_mAP_50": 0.66, "coco/bbox_mAP_75": 0.508, "coco/bbox_mAP_s": 0.294, "coco/bbox_mAP_m": 0.5, "coco/bbox_mAP_l": 0.624, "step": 50}`

**Comment by ZwwWayne** [comment]
Then this should be fine. In the early version of mmengine, xx_losses are not averaged over time in the logging,which is different from mmdet 2.x. This has been fixed in mmengine 0.2.0.
