### ISSUE TITLE
我跑自己的数据集  然后输出各个类别  结果会少一个 数据集的category从1开始的 会不会有什么影响

### ISSUE THREAD

**Issue by sharp-xiang** [open-mmlab/mmdetection#9031]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

test输出类别少1

### Environment

11

**Comment by ZwwWayne** [comment]
I do not quite get your question, could you be more specific?

**Comment by sharp-xiang** [comment]
> I do not quite get your question, could you be more specific?
![image](https://user-images.githubusercontent.com/84016975/195990305-1d4f3982-450d-441a-9f40-fef301dae389.png)

![image](https://user-images.githubusercontent.com/84016975/195990330-ae3fe268-ebf7-4cd7-ab57-0b0f043e5f70.png)
首先感谢你的关注。我有四个类别，但是输出的各个类别mAP只有三个  数据集中的注释它的cetegory是从1到4的

**Comment by ZwwWayne** [comment]
What modification did you made to the code? This might because some part is not updated.
