### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 7 (pid: 2192862) of binary: 

### ISSUE THREAD

**Issue by tcexeexe** [open-mmlab/mmdetection#9032]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

Hello~
       I use order `bash tools/dist_train.sh /home/tcexeexe/mmdetection/configs/yolox/yolox_l_8x8_300e_coco.py 8` to train the object365 dataset.
      When l use six 3090 graphics, every things is OK. But when l use seven or eight 3090 graphics, the error always occurred after 2~3 epoch,
![1665842802808](https://user-images.githubusercontent.com/28287196/195990843-f5cf9a32-8cbe-4f81-9a89-d60f2ff7616b.png)

Do anybody know how to locate the error?

### Environment

Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.112
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.13.1
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.6
MMDetection: 2.25.2+9d3e162

**Comment by BIGWangYuDong** [comment]
Seems this is a PyTorch error, you can try to degrade the torch version to 1.9.or 1.10, this error may be fixed

**Comment by progincline** [comment]
I have the same Error with 1.10.Maybe it needs 1.9 with cu111

**Comment by theksn** [comment]
怎么解决呢？

**Comment by GuHuangAI** [comment]
It seems to occured when your `workers_per_gpu` is inappropriate. Try set `workers_per_gpu=1`.

**Comment by GuHuangAI** [comment]
It seems to occured when your `workers_per_gpu` is inappropriate. Try to set `workers_per_gpu=1`.

**Comment by Franko9999** [comment]
Have the same problem with workers_per_gpu=1 and batch size = 2. This is not due to GPU memory limits as I have more than 24 GB and the model training uses only 9 GB.

**Comment by Franko9999** [comment]
> Have the same problem with workers_per_gpu=1 and batch size = 2. This is not due to GPU memory limits as I have more than 24 GB and the model training uses only 9 GB.

Have tried both pytorch 1.11 and 1.12, both with cuda 113

**Comment by GuHuangAI** [comment]
@Franko9999 ,Have you tried to change `woekers_per_gpu` ?

**Comment by GuHuangAI** [comment]
@Franko9999 , The smaller value may be suitable.

**Comment by Franko9999** [comment]
yes, I have tried both workers_per_gpu = 1 and workers_per_gpu = 2.

**Comment by GuHuangAI** [comment]
@Franko9999 If the problem occur after several epochs, you can set the `workers_per_gpu=0` and close the distribution training, just use `python ./tools/train.py $CONFIG_FILE` to see the true problem.

**Comment by Tao-Cute** [comment]
I have the same problem in my classification code based on deit. Training small model everything is ok，but when i training larger scale model，the process will end in any epochs.

**Comment by Franko9999** [comment]
Yes, now Im testing yolox-s and so far it runs fine without any problem (epoch 180, for yolox-x the problem appeared right after several epochs already).

Best regards,
Roberts
