### ISSUE TITLE
Support Vision Transformer Adapter for Dense Predictions

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mmdetection#9044]
### What is the problem this feature will solve?

support Vision Transformer Adapter for Dense Predictions
paper: https://arxiv.org/pdf/2205.08534.pdf
code: https://github.com/czczup/ViT-Adapter

We may need to implement some cuda ops. I would like you to consider this with the mmcv team.
https://github.com/czczup/ViT-Adapter/tree/main/detection/ops

### What is the feature you are proposing to solve the problem?

This work investigates a simple yet powerful dense prediction task adapter for Vision Transformer (ViT).

**Comment by okotaku** [comment]
I got it👍

"1st Place Solutions for the UVO Challenge 2022 | Papers With Code" https://paperswithcode.com/paper/1st-place-solutions-for-the-uvo-challenge

This model got 1st place on UVO.

**Comment by Czm369** [comment]
PRs are welcomed.. We will review it as soon as possible

**Comment by Czm369** [comment]
In addition，we have already support  Teacher-Student SSOD framework in mmdet 3.x ，which may be helpful for implementing the model. 
"1st Place Solutions for the UVO Challenge 2022 | Papers With Code" https://paperswithcode.com/paper/1st-place-solutions-for-the-uvo-challenge
