### ISSUE TITLE
ga_faster_rcnn._coco_1x.py问题

### ISSUE THREAD

**Issue by ova2ova** [open-mmlab/mmdetection#9050]
Hello, I would like to consult why I run ga_faster_rcnn framework without results

**Comment by ova2ova** [comment]
你好，我想咨询一下，为什么我运行ga_faster_rcnn框架没有结果
Hello, I would like to consult why I run ga_faster_rcnn framework without results

**Comment by ZwwWayne** [comment]
Could you follow the issue template to report what command did you use and what dataset did you run on?

**Comment by Czm369** [comment]
More details, please.
