### ISSUE TITLE
error with cascade_rcnn_mdconv_c3-c5_x101_64x4d_fpn_1x_0.py

### ISSUE THREAD

**Issue by chituma110** [open-mmlab/mmdetection#906]
Thanks for your bug report and we appreciate that a lot.

**Checklist**
- [ ] I have searched related issues but could not get the expected help.
- [ ] The bug has not been fixed in the latest version.

**Describe the bug**
RuntimeError: While copying the parameter named layer2.0.conv2.weight, whose dimensions in the model are torch.Size([512, 512, 3, 3]) and whose dimensions in the checkpoint are torch.Size([512, 8, 3, 3]).

**Error traceback**
1. What command or script did you run?
/home/mmdetection/configs/cascade_rcnn_mdconv_c3-c5_x101_64x4d_fpn_1x_0.py
--validate
--gpus
8
--launcher
pytorch
**Environment**
 - OS: [e.g., Ubuntu 16.04.6]
 - GCC [e.g., 5.4.0]
 - PyTorch version [e.g., 1.1.0]
- How you installed PyTorch [ conda]
- GPU model [e.g., TitanXp]
- CUDA 10.0

**Comment by hellock** [comment]
The command seems not complete. Could you provide the running command and config file (if you modified it)?

**Comment by chituma110** [comment]
**The full completed command is**
python /home/mmdetection/tools/train.py /home/mmdetection/configs/cascade_rcnn_mdconv_c3-c5_x101_64x4d_fpn_1x_0.py
--validate
--gpus
8
--launcher
pytorch

**And I got the following error**

RuntimeError: While copying the parameter named layer2.0.conv2.weight, whose dimensions in the model are torch.Size([512, 512, 3, 3]) and whose dimensions in the checkpoint are torch.Size([512, 8, 3, 3]).

The base net is resnext101 which is downloaded from
'resnext101_64x4d': 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_64x4d-ee2c6f71.pth',  # noqa: E501

**Comment by hellock** [comment]
I cannot even run with the provided command above (other errors were raised before loading checkpoints), are you sure about that?
BTW, have you checked the second item in the checklist?
