### ISSUE TITLE
deformable-detr 请问如何调整配置，可以在1060 6g显卡上跑起来训练？

### ISSUE THREAD

**Issue by Watebear** [open-mmlab/mmdetection#9063]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

把 batchsize设为1，只有1张卡，oom：

RuntimeError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 5.93 GiB total capacity; 4.28 GiB already allocated; 140.38 MiB free; 4.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

deformable detr 的标准训练是 2节点16卡，但训练资源比较紧张。 debug 的设备只有一台1060的台式机。请问如何修改配置，可以先在1060跑通？

### Expected results

修改config的建议

### Additional information

无

**Comment by hhaAndroid** [comment]
@Watebear  Hi, Only modify and reduce the batch size and reduce the image size.

**Comment by Watebear** [comment]
Can we just reduce channels or num queries to achieve the goal? I tried to reduce channel, but get some mis-match mistake

**Comment by hhaAndroid** [comment]
@Watebear OK
