### ISSUE TITLE
Using C1 or C2 of ResNet as the input featue map for FasterRCNN

### ISSUE THREAD

**Issue by lshangguan** [open-mmlab/mmdetection#908]
Hi, I have a question about feature map. Is it possible to replace the C4 with C2 or C1 as the input feature map for FasterRCNN? If yes, which part should I modify? Only the configuration file?

Thank you!

**Comment by hellock** [comment]
I suppose that, although we have not tried so.

**Comment by lshangguan** [comment]
> I suppose that, although we have not tried so.

Thanks, I will try and get back then.

**Comment by hellock** [comment]
Feel free to reopen it if there is any related issues.
