### ISSUE TITLE
See examples in empirical attention in https://github.com/wanghonglie/mmdetection/tree/master/configs/empirical_attention

### ISSUE THREAD

**Issue by ShaneCan** [open-mmlab/mmdetection#9082]
See examples in empirical attention in https://github.com/wanghonglie/mmdetection/tree/master/configs/empirical_attention

_Originally posted by @ZwwWayne in https://github.com/open-mmlab/mmdetection/discussions/9025#discussioncomment-3877033_
    
**could i add this plugin in yolox config to achieve same function？In addition, i wanna know which .py defined this 'GeneralizedAttention', thx for response!!!**

**Comment by RangiLyu** [comment]
YOLOX in mmdet cannot add attetion plugin.
But this feature is supported in MMYOLO https://mmyolo.readthedocs.io/en/latest/advanced_guides/how_to.html#add-plugins-to-the-backbone-network 
Welcome to try!

**Comment by ShaneCan** [comment]
> YOLOX in mmdet cannot add attention plugin. But this feature is supported in MMYOLO https://mmyolo.readthedocs.io/en/latest/advanced_guides/how_to.html#add-plugins-to-the-backbone-network Welcome to try!

thx, i'd like to try it
