### ISSUE TITLE
yolov4 and v5 needed！！！

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmdetection#9085]
### What is the problem this feature will solve?

那请问下mmdet实现了 yolov5或者v4吗？ 具体的代码和文档分别在哪呢？

### What is the feature you are proposing to solve the problem?

那请问下mmdet实现了 yolov5或者v4吗？ 具体的代码和文档分别在哪呢？

### What alternatives have you considered?

那请问下mmdet实现了 yolov5或者v4吗？ 具体的代码和文档分别在哪呢？

**Comment by RangiLyu** [comment]
Try MMYOLO https://github.com/open-mmlab/mmyolo
