### ISSUE TITLE
Same `Training Memory` for different size models of RTMDet?

### ISSUE THREAD

**Issue by RangeKing** [open-mmlab/mmdetection#9091]
### 📚 The doc issue

Why do different size models of RTMDet have the same `Training Memory (GB): 7.6` in https://github.com/open-mmlab/mmdetection/blob/3.x/configs/rtmdet/metafile.yml

**Comment by RangiLyu** [comment]
Sorry, forgot to update the memory info of RTMDet. I'll update it later.

**Comment by RangeKing** [comment]
> Sorry, forgot to update the memory info of RTMDet. I'll update it later.

Get it. Thanks for your reply.

**Comment by RangeKing** [comment]
Solved in https://github.com/open-mmlab/mmdetection/pull/9098
