### ISSUE TITLE
Mixed Precision Training

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#9092]
### What is the problem this feature will solve?

Hello , 
Thanks for your effort in developing such a huge library. 

I would like to ask about using mixed precision training within some sort of models . 

for examples , the anchor free models such as FoveaBox , FCOS and FSAF model. 
is that possible ? does such model support the using of Mixed Precision Training (fp16)? 

would it be possible to add the following line in my config of such models:

# fp16 settings
fp16 = dict(loss_scale=512.)

or that could cause me an error in configuration. 

I need it in order to increase up the training time , is there any other solution to increase up the training time ? as it cause me more that 3 days. 

looking forward to your help, and ideas 

### What is the feature you are proposing to solve the problem?

FP16 , is it works within all types of models , such as anchor free model (FSAF,FCOS ) even more with centriapetalNet ..

**Comment by alaa-shubbak** [comment]
I also have another question: 
would it be fine to combine Mixed Precision Training with spatial attention mechanism in same config for such anchor-free models?

**Comment by RangiLyu** [comment]
> fp16 = dict(loss_scale=512.)
> 
> or that could cause me an error in configuration.

What is the error message?

**Comment by alaa-shubbak** [comment]
the error is as bellow : 

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmplhpqcj_z/tmp9hvlz3w3.py'`

**Comment by RangiLyu** [comment]
the full error message please

**Comment by alaa-shubbak** [comment]
![error in using fp16 with fcos](https://user-images.githubusercontent.com/10245810/197396496-84f383da-6bb1-4396-b1b5-dbd160e251fe.jpg)

i used a model of FCOS  ResNeXt 101

**Comment by RangiLyu** [comment]
The warning shows that your CUDA is not available. Please check your environment.
![image](https://user-images.githubusercontent.com/12907710/197432687-a184724d-90f0-46bb-8b14-70e938830f7c.png)

**Comment by alaa-shubbak** [comment]
Thank you for reply and answer. 
I tested my model again with the presents of cuda. Unfortunately I got another error as bellow: 
 
![error runing fp16 2](https://user-images.githubusercontent.com/10245810/197871356-4cbbc7fa-8afe-4f12-b286-fb1dbff90d5e.jpg)

although  i have defined the train_pipeline 

see bellow my whole configuration: 

![config1](https://user-images.githubusercontent.com/10245810/197872393-792ee3f2-6be3-4874-b97c-0dcffbbed4cf.jpg)
![config2](https://user-images.githubusercontent.com/10245810/197872397-4ddc1ec6-f9fc-462a-9c3a-be17d8c4974c.jpg)
![config3](https://user-images.githubusercontent.com/10245810/197872524-14d13f83-625f-4dec-b04d-7902b0d95e80.jpg)
![config4](https://user-images.githubusercontent.com/10245810/197872399-c7ac71a2-a489-4c5e-b7d8-690dbf6a3697.jpg)
![config5](https://user-images.githubusercontent.com/10245810/197872400-8deb95b0-b10d-4f25-8b88-5d6204b07adb.jpg)

**Comment by RangiLyu** [comment]
Can you use `tools/misc/print_config.py` to check your config?
Or you can upload your config file so that we can take a look to find out what's wrong with it.

**Comment by alaa-shubbak** [comment]
after using the tool : `tools/misc/print_config.py`
I got same error as bellow 

![error after use instruction](https://user-images.githubusercontent.com/10245810/197995384-74224624-7192-4dae-a4ff-aa2b59451a90.jpg)


the full config that generate after start training the model within the dir folder is attached here: 
[my_config](https://drive.google.com/file/d/1PuKrzemHBWtkCoavChsrey0H5jH0geFq/view?usp=sharing)

**Comment by RangiLyu** [comment]
What is your environment? Can you run `python mmdet/utils/collect_env.py` and plot your env? My env is like this:

```
sys.platform: linux
Python: 3.8.10 (default, May 19 2021, 18:05:58) [GCC 7.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1660 SUPER
CUDA_HOME: /opt/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (GCC) 11.3.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1
OpenCV: 4.5.2
MMCV: 1.6.0
MMCV Compiler: GCC 8.5
MMCV CUDA Compiler: 11.7
MMDetection: 2.25.3+77e713b
```
