### ISSUE TITLE
Xavier_init bugs when normorlize is enable?

### ISSUE THREAD

**Issue by iceload123** [open-mmlab/mmdetection#91]
In fpn structure, the repo uses xavier_init for convs.
However, when normorlize is enable (I try to use nn.GroupNorm), It produces error "Nonetype object has no attribute fill_".
I found this occured when initializing bias which does not exist.
In face, it seems that in the model/utils/weight_init.py, the "hasattr(module, 'bias')" expression is always right

**Comment by hellock** [comment]
Thanks for reporting the bug! Initialization methods in [mmcv.cnn.weight_init](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/weight_init.py) is more reliable.
