### ISSUE TITLE
How to get change to iou_thr=0.5:0.95 in voc.py for PASCAL VOC evaluation

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmdetection#9110]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 💬 Describe the reimplementation questions

How to get change to iou_thr=0.5:0.95 in voc.py for PASCAL VOC evaluation?  I tried using `np.arange(0.5, 0.96, 0.05)` but it throws an error: `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

### Environment

N/A

### Expected results

mAP at IoU=0.5:0.95

### Additional information

N/A

**Comment by BIGWangYuDong** [comment]
You can try to set `[0.5 + 0.05 * i for i in range(10)]` or `[0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]` in the config file.

**Comment by SmallingCar** [comment]
Can you tell details for me? I can’t understand.Thank you very much.
