### ISSUE TITLE
make browse_dataset.py faster~

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#9126]
### What is the problem this feature will solve?

make browse_dataset.py fast~

### What is the feature you are proposing to solve the problem?

make browse_dataset.py fast~

### What alternatives have you considered?

make browse_dataset.py fast~

**Comment by Czm369** [comment]
Maybe you can set  `--not-show`.

**Comment by Czm369** [comment]
Some parallel or multilinear speedups are not currently supported in `browse_dataset.py`
