### ISSUE TITLE
train my own dataset

### ISSUE THREAD

**Issue by 666xiaohei666** [open-mmlab/mmdetection#913]
where shoule i modefy if i train my own dataset
![image](https://user-images.githubusercontent.com/22683832/60481201-00f12100-9cbf-11e9-9a7a-6eb876ee0b03.png)
just like this?

but i modefy the class_num in the config file, when i run the code, it will get an error:
"rTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [543,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed."

so where should i modefy?

**Comment by hellock** [comment]
Please refer to the [documentation](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md#use-my-own-datasets) for training on your own datasets.
