### ISSUE TITLE
May I know the process for image classification

### ISSUE THREAD

**Issue by Harish202** [open-mmlab/mmdetection#914]
Hi, Can someone please guide me through how to use the code repo for image classification task. I do not think that making loss_bbox or mask_loss as 0 will work out. Please help.

**Comment by hellock** [comment]
If you refer to image classification on ImageNet/CIFAR, maybe this [example](https://github.com/open-mmlab/mmcv/tree/master/examples) can help you.

**Comment by Harish202** [comment]
Thank you hellock. I will check out mmcv :)
