### ISSUE TITLE
[Reimplementation] the function python tools/test.py with more iteration 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#9148]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

it is not a bug , just i want to know if there is a possible to run the function 
` python tools/test.py` 
with more iteration , instead of 1 iteration , on another words instead of test each image dependently, i want to go through group of images , for examples 50 images at ones to decrease the time. 

![test iteration](https://user-images.githubusercontent.com/10245810/198104584-f590b2ba-4b01-418e-bc2b-f7bd36073c82.jpg)

here in yellow , i have 5000 images in test , and the code goes by each image ,which take a while . 

how can i do so? is that could increase the speed of getting a results  of mAP for boundary boxes ?

### Environment

my environment is totally correct as i already trained my model.

**Comment by wanghonglie** [comment]
Modify the number of images loaded by the dataloader:
https://github.com/open-mmlab/mmdetection/blob/e71b499608e9c3ccd4211e7c815fa20eeedf18a2/tools/test.py#L188

**Comment by ZwwWayne** [comment]
you can modify the samples_per_gpu to be 2 or 4 in the config of test_data

**Comment by alaa-shubbak** [comment]
![error when test with 4sample](https://user-images.githubusercontent.com/10245810/199251759-a8fb9d81-2c09-4650-a957-b1cb5171393a.jpg)

the error is `RuntimeError: stack expects each tensor to be equal size, but got [3, 800, 1216] at entry 0 and [3, 800, 1248] at entry 1`

this is the error i got when change the  `samples_per_gpu=4`  in the file  `test.py` file

**Comment by alaa-shubbak** [comment]
I keep it as it is 

```
test_dataloader_default_args = dict(
        samples_per_gpu=1, workers_per_gpu=2, dist=distributed, shuffle=False)
```

and try to run the test function (./tools/test.py) on my weight file, unfortunately i got such error : 

`RuntimeError: DataLoader worker (pid 49663) is killed by signal: Killed. `


<img width="1015" alt="image" src="https://user-images.githubusercontent.com/10245810/199581781-023b98e1-e177-4cb2-8de0-5d0c32aac19f.png">

as you may see , they mentioned some stuff within the (mmdet/utils/setup_env.py) , but i did not understand it well. 

i try to give the code one gpu and one core and 2 processors , could be this the reason for killing my job?

in case i make it 4 or 8 , would that get rid of this error ? as i don't want to have lots of changes within main codes  of mmdet. 

what do you think ? help please.
