### ISSUE TITLE
loading grayscale images

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmdetection#9188]
Hi,
My dataset consists of grayscale images in voc annotation style. If I want to train with mmdetection, where should I change in the original code to load grayscale images correctly?
Thanks!

**Comment by Czm369** [comment]
https://github.com/open-mmlab/mmdetection/blob/3221ecf33885bcf185e1ea63ac72a861403d81b0/mmdet/datasets/transforms/loading.py#L20

**Comment by Czm369** [comment]
Image will be loaded at
https://github.com/open-mmlab/mmcv/blob/5f58b9101f959a5794860b2737ab83b522d25915/mmcv/transforms/loading.py#L70
