### ISSUE TITLE
why is retinanet so slow? 

### ISSUE THREAD

**Issue by andeyeluguo** [open-mmlab/mmdetection#919]
only 12.5 fps in the model zoo.

**Comment by hellock** [comment]
How fast did you expect it to be? It is naturally slower than Faster R-CNN w/ FPN and the official code (Detectron) of RetinaNet is only 8 fps.

**Comment by andeyeluguo** [comment]
but the yolact for instance segment has been more than 40fps which is based on retinanet, I don't know why....

**Comment by hellock** [comment]
They are very different in architectures, input resolutions, etc. You need to read the paper or the code for the detailed difference.

**Comment by andeyeluguo** [comment]
can pytorch or cuda support 8bit inference? it is deemed faster if support.

**Comment by hellock** [comment]
There are better or specific frameworks than pytorch for deployment. And as far as I know, INT8 quantization is not just convert all model weights to INT8 for inference.
