### ISSUE TITLE
Problem with workflow = [('train', 1),('val',1)]

### ISSUE THREAD

**Issue by gabrielalexandre** [open-mmlab/mmdetection#9199]
I'm wanting to see the validation loss, so looking at previous issues, I added the `workflow = [('train', 1),('val',1)]` to this, but I'm getting the following error: **AttributeError: 'ConfigDict' object has no attribute 'dataset'**
What could be causing this?
Thanks

**Comment by Czm369** [comment]
Maybe you can check the config format for symbol errors.

**Comment by ipa-foj** [comment]
I had the same issue, was able to trace it back to this line here: https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L223

Here the validation set pipeline is set up as a copy of the train set pipeline.
`val_dataset.pipeline = cfg.data.train.get(
            'pipeline', cfg.data.train.dataset.get('pipeline'))`
            
The code tries to access `cfg.data.train.dataset`, which doesn't exist and thus throws this error. To fix it, I changed L225 to

`datasets.append(build_dataset(cfg.data.val))`

and deleted the previous lines that copy the train set config into the validation set config. Not sure why this was happening in the script anyways, but maybe I am missing something here?
