### ISSUE TITLE
[Bug] cpu 版的 mmdet.apis 接口是运行不了的会报错

### ISSUE THREAD

**Issue by HarleysZhang** [open-mmlab/mmdetection#9206]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

1. macos 系统+m1处理器
2. Python 3.8.13
3. mmcv-full: 1.6.0, mmdet: 2.25.0

### Reproduces the problem - code sample

```python
from mmdet.apis import init_detector, inference_detector
```

### Reproduces the problem - command or script

```shell
无
```

### Reproduces the problem - error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mmdet.api'
>>> import mmdet.apis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/apis/inference.py", line 8, in <module>
    from mmcv.ops import RoIPool
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-darwin.so, 0x0002): Library not loaded: @rpath/libtorch_cpu.dylib
  Referenced from: /opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-darwin.so
  Reason: tried: '/opt/anaconda3/envs/openmmlab/lib/libtorch_cpu.dylib' (no such file), '/opt/anaconda3/envs/openmmlab/bin/../lib/libtorch_cpu.dylib' (no such file), '/opt/anaconda3/envs/openmmlab/lib/libtorch_cpu.dylib' (no such file), '/opt/anaconda3/envs/openmmlab/bin/../lib/libtorch_cpu.dylib' (no such file), '/usr/local/lib/libtorch_cpu.dylib' (no such file), '/usr/lib/libtorch_cpu.dylib' (no such file)
```

### Additional information

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/37138671/199425752-7b026e0f-cf87-42fc-987a-b59e05d7e524.png">

**Comment by BIGWangYuDong** [comment]
Seems that you are not installed mmcv successfully. Hence, try to follow mmcv installation to re-install mmcv. If still meet this problem, it is suggested to create an issue in mmcv, which may help youi solve the problem

**Comment by HarleysZhang** [comment]
I have installed successfully! import mmcv is successful.
