### ISSUE TITLE
Question about testing one image

### ISSUE THREAD

**Issue by linquanxu** [open-mmlab/mmdetection#921]
hi, how to test one image such as using the path of image instead of instance_test2017.json?

**Comment by t-m-k** [comment]
from mmdet.apis import init_detector, inference_detector, show_result
import os
import argparse
import sys
import torch

def parse_args():
    parser = argparse.ArgumentParser(description='in and out imgs')
    parser.add_argument('--config', dest='config',help='config_file',default=None, type=str)
    parser.add_argument('--checkpoint', dest='checkpoint',help='checkpoint_file',default=None, type=str)

    if len(sys.argv) <= 1:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()
    return args

def main():

  args = parse_args()
  config_file = args.config
  checkpoint_file = args.checkpoint

  # build the model from a config file and a checkpoint file
  model = init_detector(config_file, checkpoint_file)
  print(model.CLASSES)

  root = '/mmdetection/work_dirs/needShowJPG/'
  savedir = '/mmdetection/mmdetection/'

  img = '/mmdetection/pic.jpg'
  result = inference_detector(model,img)
  savename = savedir + 'pic.png'
  show_result(os.path.join(root,img), result, model.CLASSES,out_file=savename)

if __name__ == '__main__':
    main()




you can use the code above

**Comment by linquanxu** [comment]
@t-m-k thank you very much!
