### ISSUE TITLE
.png

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#9214]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

How to change the default loading image to load. png？
![image](https://user-images.githubusercontent.com/43515926/199649649-3c9aa865-8871-45cb-aca4-d2e3a19fdf4b.png)

### Environment

python3.7

**Comment by RangiLyu** [comment]
The image format of VOC dataset should be jpeg. If you want to load png images, please modify the code here https://github.com/open-mmlab/mmdetection/blob/e71b499608e9c3ccd4211e7c815fa20eeedf18a2/mmdet/datasets/xml_style.py#L51

**Comment by BIGWangYuDong** [comment]
seems we can add a `suffix` parameter to avoid this problem
