### ISSUE TITLE
about  recall

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#9218]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

Hello, I used 400 pictures to train, 67 pictures to train, yolox, 200epoch, and printed the default parameters during the training process. I think recall is 1. What is the reason for this? thank you

![image](https://user-images.githubusercontent.com/43515926/199662434-2c79cd0b-b2af-48f9-bc0d-9af6b3f453b9.png)

### Environment

python3

**Comment by RangiLyu** [comment]
It means there is almost no False Negative. It is normal since your dataset is very small.

**Comment by zcswdt** [comment]
> It means there is almost no False Negative. It is normal since your dataset is very small.

How to calculate the accuracy rate?

**Comment by RangiLyu** [comment]
There is no 'accuracy' for single-stage detection models. The 'ap' in your log means 'average precision', you can use this metric.

**Comment by zcswdt** [comment]
> There is no 'accuracy' for single-stage detection models. The 'ap' in your log means 'average precision', you can use this metric.



> There is no 'accuracy' for single-stage detection models. The 'ap' in your log means 'average precision', you can use this metric.

I want to calculate the precision, but I don't know how to calculate it

**Comment by RangiLyu** [comment]
![image](https://user-images.githubusercontent.com/12907710/199866962-7a617911-5f7f-432d-93ac-2e7c3f7dc74c.png)
This is the precision. You already calculated it.

**Comment by zcswdt** [comment]
> This is the precision. You already calculated it.

So P is 0.783, R is 1, and map is 0.783. Why are P and map the same?I want to find the Percsion and recall

**Comment by RangiLyu** [comment]
You have only one class and only use one IoU threshold, mAP is equal to the precision.
