### ISSUE TITLE
Trace mmdetection error!!TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect

### ISSUE THREAD

**Issue by t-m-k** [open-mmlab/mmdetection#922]
**Question:**
_TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!_
**_if nms_pre > 0 and scores.shape[0] > nms_pre:_**

**Describe:**
Here nms_pre is a python value and **nms_pre = 1000**;
**scores** is a Tensor variable with different shape in a loop.
scores.shape[0] is a python value when it is in pytorch but a Tensor **in the trace process**.
From the question, we can know scores.shape[0] will be a **constant** in the c++ trace model.
But scores is a **variable** with different shape every time in a loop, if scores.shape[0] is a constant in the c++, we will get a out of range error.

How to solve this problem.
Thank you very much.

**Comment by LeLiu** [comment]
@t-m-k did you solve this problem? I am also facing the same issue, can you guide me a bit?

**Comment by t-m-k** [comment]
> @t-m-k did you solve this problem? I am also facing the same issue, can you guide me a bit?
In trace process, the forword should just contain the net operation without python native as much as possible. Otherwise, there will be some warnings. In this issue, i rewrite the python code to libtorch.
