### ISSUE TITLE
Why not load_from and resume_from to args in tools/train.py directly in mmdet3.0?

### ISSUE THREAD

**Issue by LYMDLUT** [open-mmlab/mmdetection#9221]
### What's the feature?

 "load_from and resume_from" are the most commomly used in mmdet3.0, but why not put it in train.py directly?Now if I need to change the file to load ckpt,I need to open the config and rewrite it, it is not convient.
In mmdet2.0, there still has  the args of "resume_from", but has not "load_from".
If there is no conflict, I hope to add it to args in train.py.

**Comment by RangiLyu** [comment]
You can use `--cfg-options load_from='YOUR_MODEL_PATH'`

**Comment by LYMDLUT** [comment]
I know,but I still want interface to these two args,as they are the most commonly used.

**Comment by BIGWangYuDong** [comment]
`--load-from xxx` is similar to ` --cfg-options load_from=xxx`. If you want to add these two args, you can add them in your code~
