### ISSUE TITLE
about recall？

### ISSUE THREAD

**Issue by zcswdt** [open-mmlab/mmdetection#9227]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

Is there any way to reduce recall and improve accuracy?
![image](https://user-images.githubusercontent.com/43515926/199750263-de622d41-1c99-4314-8332-2e58d37c8389.png)

### Environment

python3

**Comment by BIGWangYuDong** [comment]
Similar issue: https://github.com/open-mmlab/mmdetection/issues/9218
