### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Franko9999** [open-mmlab/mmdetection#9228]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

Hello,

When I try to parallelly run two trainings on same GPU (its not fully used so I tried to start another one to compare results) Im getting the error:

    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

![image](https://user-images.githubusercontent.com/47304445/199775017-831faf2f-5bc5-4903-9b73-c408a36a304c.png)

I have tried to run the second iteration with different port values and in distributed as well as simple way but no changes. Maybe there are some additional commands which needs to be given?

Environment information:

sys.platform: win32
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
GCC: n/a
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.12.0+cu113
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: MSVC 192829924
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.3+e71b499

Pytorch installed through pip.

Best regards,
Roberts

### Reproduces the problem - code sample

first training which runs fine:

python -m torch.distributed.launch --master_port 11224 --nproc_per_node 1 tools/train.py configs/retinanet/retinanet_r50_fpn_1x_coco_one_class.py

second training started in paralllel:
tried:
python -m torch.distributed.launch --master_port 29900 --nproc_per_node 1 tools/train.py configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco_one_class.py

as well as:
python tools/train.py configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco_one_class.py --gpu-id 0

### Reproduces the problem - command or script

first training which runs fine:

python -m torch.distributed.launch --master_port 11224 --nproc_per_node 1 tools/train.py configs/retinanet/retinanet_r50_fpn_1x_coco_one_class.py

second training started in paralllel:
tried:
python -m torch.distributed.launch --master_port 29900 --nproc_per_node 1 tools/train.py configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco_one_class.py

as well as:
python tools/train.py configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco_one_class.py --gpu-id 0

### Reproduces the problem - error message

    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

![image](https://user-images.githubusercontent.com/47304445/199775017-831faf2f-5bc5-4903-9b73-c408a36a304c.png)

**Comment by RangiLyu** [comment]
Seems you forgot to add `--launcher pytorch`. Please refer to the `tools/dist_train.sh` to launch a distributed training process.
