### ISSUE TITLE
[Feature]  404 docs

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmdetection#9238]
### What's the feature?

能不能干脆把所有还没指定跳转的 有跳转功能的都重定向到对应中文或英文文档的开头 （比如某个页面切换英文文档），省事也避免报错

Can you simply all have not specified the jump jump function (such as a page switch to the English document are redirected to the beginning of the English document to save time and avoid reporting errors)

### Any other context?

like this : https://mmdetection.readthedocs.io/zh_CN/3.x/advanced_guides/index.html#id2
if you use read the docs to change language,you can see 404 error page. If you try to change version,you will see the same things.

**Comment by BIGWangYuDong** [comment]
Thanks for your report. If you switch to Engilsh version, It will convert back to v2.x docs. An easy way to switch is change zh_CN to en.

**Comment by BIGWangYuDong** [comment]
Also you can click here: 
![image](https://user-images.githubusercontent.com/48282753/199920148-003b79b0-d5a6-499c-9644-14f94a3fd715.png)

**Comment by sanbuphy** [comment]
> Also you can click here: ![image](https://user-images.githubusercontent.com/48282753/199920148-003b79b0-d5a6-499c-9644-14f94a3fd715.png)

Yes, it's a solution what I've found, but if we need to change version, it also a little bit of Trouble(404)

**Comment by BIGWangYuDong** [comment]
That's a good question. But 2.x version's doc is all move to 3.x. which means you do not need to change the version.

**Comment by sanbuphy** [comment]
> That's a good question. But 2.x version's doc is all move to 3.x. which means you do not need to change the version.

Yes,we don't need to change the version in 3.x. I mostly meet the problem in 2.x documentation when i want to compared the difference between 2.x and 3.x. In general it's a minor problem.
.
