### ISSUE TITLE
[Bug] multiple deletion of best checkpoint while using dist_train.sh

### ISSUE THREAD

**Issue by RlChen0** [open-mmlab/mmdetection#9246]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

System environment:
    sys.platform: linux
    Python: 3.8.13 (default, Oct 21 2022, 23:50:54) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 429034773
    GPU 0,1,2,3,4,5,6,7: NVIDIA A40
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.5, V11.5.119
    GCC: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)
    PyTorch: 1.10.0
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.11.0
    OpenCV: 4.6.0
    MMEngine: 0.3.0

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: pytorch
    Distributed training: True
    GPU number: 8

### Reproduces the problem - code sample

```python
default_hooks = dict(
    logger=dict(type='LoggerHook', interval=interval),
    checkpoint=dict(
        interval=interval,
        max_keep_ckpts=3,
        save_best=['coco/bbox_mAP'],
          # only keep latest 3 checkpoints
    ))
```

### Reproduces the problem - command or script

```
bash tools/dist_train.sh configs/rtmdet/rtmdet_x_8xb16_300e_panicle.py 8 --cfg-options load_from='p_weights/rtmdet_x_8xb32-300e_coco_20220715_230555-cc79b9ae.pth'
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main()
  File "tools/train.py", line 116, in main
    runner.train()
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1661, in train
    model = self.train_loop.run()  # type: ignore
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.runner.val_loop.run()
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/runner/loops.py", line 351, in run
    self.runner.call_hook('after_val_epoch', metrics=metrics)
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1723, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/hooks/checkpoint_hook.py", line 297, in after_val_epoch
    self._save_best_checkpoint(runner, metrics)
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/hooks/checkpoint_hook.py", line 412, in _save_best_checkpoint
    self.file_client.remove(best_ckpt_path)
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/fileio/file_client.py", line 346, in remove
    self.client.remove(filepath)
  File "/data/home/rlchen/app/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/fileio/backends/local_backend.py", line 416, in remove
    raise FileNotFoundError(f'filepath {filepath} does not exist')
FileNotFoundError: filepath /data/home/rlchen/ProJect/mmdetection/work_dirs/rtmdet_x_8xb16_300e_panicle/best_coco/bbox_mAP_epoch_1.pth does not exist
11/05 14:56:10 - mmengine - INFO - The best checkpoint with 0.0020 coco/bbox_mAP at 7 epoch is saved to best_coco/bbox_mAP_epoch_7.pth.
```

**Comment by RangiLyu** [comment]
https://github.com/open-mmlab/mmengine/pull/682 has been merged. Please update mmengine to the latest.
