### ISSUE TITLE
modulated_deformable_im2col_cuda

### ISSUE THREAD

**Issue by qianlinjun** [open-mmlab/mmdetection#925]
hello，I‘m confused about ’modulated_deformable_im2col_cuda‘ and ’deformable_im2col‘ in ‘dcn/src/deform_conv_cuda.cpp’， I want to know what’s the difference about them，thank you！

**Comment by hellock** [comment]
Modulated deformable convolution is introduced in [DCNv2](https://arxiv.org/abs/1811.11168).

**Comment by qianlinjun** [comment]
ok, thanks!
