### ISSUE TITLE
ImportError: cannot import name 'SelfAttentionBlock' from 'mmdet.models.utils' (H:\SoftWare\Anaconda\envs\mmdt\lib\site-packages\mmdet-2.25.2-py3.8.egg\mmdet\models\utils\__init__.py)

### ISSUE THREAD

**Issue by hsp2454** [open-mmlab/mmdetection#9262]
### What's the feature?

Hello, I encountered an error while training faster mcnn with mmdetection. All the files in mmdet\models\utils could not find the module 'SelfAttentionBlock' in the error

**Comment by BIGWangYuDong** [comment]
Seems SelfAttentionBlock is not in the official mmdet.utils. If you add it in your own repo, remember to add it in `mmdet.utils.__init__.py` at the same time
