### ISSUE TITLE
Is it possible to increase mask size? 

### ISSUE THREAD

**Issue by StringBottle** [open-mmlab/mmdetection#927]
Hello, I have a question about resizing the size of mask head.

As far as I have tested so far, the original size of mask head, 28 x 28, is sometimes too small for other custom data sets. 

I looked into 'fcn_mask_head.py' and found that it can only adjust the upsampling ratio using deconv or whatsoever and it can increase the size only one time.

Is it possible to add one more upsampling layer so that I can increase the size of mask two times to make it 56 x 56?  

I am worried about other possible bugs if I add one more layer to the original code. 

Thanks.

**Comment by hellock** [comment]
You can try one more upsampling layer or just larger upsampling ratio, and the code should be fine.
