### ISSUE TITLE
Config file for htc required

### ISSUE THREAD

**Issue by ChandanVerma** [open-mmlab/mmdetection#928]
**Can Some provide me with the config file for htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py just for object detection and not semantic segmentation**

Thanks

**Comment by hellock** [comment]
There is already an [example](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_without_semantic_r50_fpn_1x.py) for no semantic segmentation branch, it should be easy to adapt it to what you want.

**Comment by ChandanVerma** [comment]
Thanks

**Comment by mosheliv** [comment]
Does it still need the semantic segmentation to train? it gives me 
```
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 10, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable
```
(my dataset has only bboxes)
