### ISSUE TITLE
推理部分无法进行

### ISSUE THREAD

**Issue by 52THANOS** [open-mmlab/mmdetection#9288]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

pytorch

### Reproduces the problem - code sample

import asyncio
import torch
from mmdet.apis import init_detector, async_inference_detector
from mmdet.utils.contextmanagers import concurrent

async def main():
    config_file = 'configs/faster_rcnn/faster-rcnn_r50_fpn_soft-nms_1x_coco.py'
    checkpoint_file = 'work_dir/epoch_120.pth'
    device = 'cuda:0'
    model = init_detector(config_file, checkpoint=checkpoint_file, device=device)

    # 此队列用于并行推理多张图像
    streamqueue = asyncio.Queue()
    # 队列大小定义了并行的数量
    streamqueue_size = 3

    for _ in range(streamqueue_size):
        streamqueue.put_nowait(torch.cuda.Stream(device=device))

    # 测试单张图片并展示结果
    img = 'test.png'  # or 或者 img = mmcv.imread(img)，这样图片仅会被读一次

    async with concurrent(streamqueue):
        result = await async_inference_detector(model, img)

    # 在一个新的窗口中将结果可视化
    model.show_result(img, result)
    # 或者将可视化结果保存为图片
    model.show_result(img, result, out_file='result.png')

asyncio.run(main())

### Reproduces the problem - command or script

python testDemo.py

### Reproduces the problem - error message

[Bug] KeyError: "class `FasterRCNN` in mmdet/models/detectors/faster_rcnn.py: 'DetDataPreprocessor is not in the model registry. Please check whether the value of `DetDataPreprocessor` is correct 

### Additional information

是版本问题吗

**Comment by sanbuphy** [comment]
这个是2.25的api 你应当用最新的api，在新分支的demo。
This is the 2.25 version API. You should use the 3.x API, in the new branch.

**Comment by 52THANOS** [comment]
> 这个是2.25的api 你应当用最新的api，在新分支的demo。 This is the 2.25 version API. You should use the 3.x API, in the new branch.

我就是在3.x里看的

**Comment by sanbuphy** [comment]
> > 这个是2.25的api 你应当用最新的api，在新分支的demo。 This is the 2.25 version API. You should use the 3.x API, in the new branch.
> 
> 我就是在3.x里看的

[这才是3.x的](https://github.com/open-mmlab/mmdetection/blob/3.x/demo/image_demo.py)

**Comment by BIGWangYuDong** [comment]
Should Update the documents. PRs are welecomed

**Comment by ZwwWayne** [comment]
> By the way，This function（visualizer.add_datasample(））uses the “out_file=args.out_file”，it will cause a save error，We should change the '--out-file' in the parse_args（） to '--out_file' 顺便说一下，”image_demo.py“这个参考文件里面用于可视化的”visualizer.add_datasample(）“部分使用了“out_file=args.out_file”，但是定义处仍然定义了'--out-file'，可能会导致保存错误，把定义里面的'--out-file'改成'--out_file'就能保存了。

using --out-file and --out_file are equivelent as args.out_file. We choose --out-file for simplicity.
