### ISSUE TITLE
increase the batch size to a value of 50 or 100 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#9289]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I am trying to increase the batch size of training my model to be 50 then try with 100 , 
but i got errors as bellow : 

for using batch size of 50 as this config : 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/10245810/200848901-4f78b9e5-aa48-4d4d-8251-cb22840e57c8.png">

 i got this error : 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/10245810/200849204-6a4228fa-5e29-46a3-b726-51a9c78326a8.png">

while using the batch_size of 100 , as bellow 
<img width="448" alt="image" src="https://user-images.githubusercontent.com/10245810/200847684-e1f871dd-caf7-4d52-b20f-5d50b222bc1a.png">

i got this error : 
<img width="742" alt="image" src="https://user-images.githubusercontent.com/10245810/200847923-cf8b9a3c-ef55-4c0f-8af9-65ef98f8b016.png">

### Environment

my environment is totally correct as i used to run same models with it but with less batch size (between 2 to 4 ) 

here the environment info :
![environment](https://user-images.githubusercontent.com/10245810/200846747-b9861c70-4862-4f3c-b484-00666969848c.jpg)

### Expected results

i expected that the model will train faster by increasing the batch size as above , but it was failed even with training .

**Comment by PeterVennerstrom** [comment]
MMDetection reports model memory usage in the logs.  This number is slightly less than the values reported by `nvidia-smi`.

For FSAF with Resnet 101 MMDetection reports per GPU 5.08 GB memory usage with per GPU batch size 2.  A batch size of 50 would require at least 125 GB GPU memory.
