### ISSUE TITLE
[New Models] SpareInst (a real-time instance segmentation algorithm)

### ISSUE THREAD

**Issue by WangZan0899** [open-mmlab/mmdetection#9293]
### Model/Dataset/Scheduler description

I'm happy to use mmdet. will you consider adding the **SpareInst** algorithm in the near future? I saw on github that there is already a reference solution for developing **SpareInst based on mmdet-3.x**: **https://github.com/ueanperfect/SparseInst_mmdet_dev3.x.git**

However, I think there are some problems in terms of accuracy and I am afraid that an official re-implementation of your mmdet is needed. It would be appreciated if you could provide an official implementation of this algorithm based on mmdet.

Finally attached is **the official repository of SpareInset**, they are based on **detectron2** implementation: **https://github.com/hustvl/SparseInst.git**

### Open source status

- [X] The model implementation is available
- [X] The model weights are available.

### Provide useful links for the implementation

official repository based on detectron2: https://github.com/hustvl/SparseInst.git
unofficial repository based on mmdet-3.x: https://github.com/ueanperfect/SparseInst_mmdet_dev3.x.git

**Comment by RangiLyu** [comment]
Thanks for your suggestion! We will consider taking this into our plan! Also, we would greatly appreciate it if anyone is willing to participate in reimplementing this algorithm.

**Comment by RangiLyu** [comment]
The latest MMDetection 3.0.0rc4 has supported SparseInst in the projects https://github.com/open-mmlab/mmdetection/tree/3.x/projects/SparseInst
