### ISSUE TITLE
about dataset/pipeline/formatting

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmdetection#9297]
在mmcls中https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/pipelines/formatting.py#L141
这里是加了对key值的判断的，但是mmdet中
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/formatting.py#L343
里面这个没有判断 如果我的result里面没有这个信息应该会出错

**Comment by RangiLyu** [comment]
We check the required keys in the pipeline to avoid potential errors in the models.
