### ISSUE TITLE
the loss_bbox is zero when training custom dataset in faster r-cnn.

### ISSUE THREAD

**Issue by lumosity4tpj** [open-mmlab/mmdetection#930]
`2019-07-05 11:04:50,991 - INFO - Epoch [1][2250/18654]	lr: 0.00250, eta: 2 days, 7:52:51, time: 1.009, data_time: 0.503, memory: 5589, loss_rpn_cls: 0.0000, loss_rpn_bbox: 0.0000, loss_cls: 0.0097, acc: 99.7949, loss_bbox: 0.0000, loss: 0.0097`

And the `bbox` exists in the `json` :

`    {
      "segmentation": [
        [
          0.2046875,
          0.42291668,
          0.2046875,
          0.515625015,
          0.2046875,
          0.60833335,
          0.26953125,
          0.60833335,
          0.334375,
          0.60833335,
          0.334375,
          0.515625015,
          0.334375,
          0.42291668,
          0.26953125,
          0.42291668
        ]
      ],
      "bbox": [
        0.2046875,
        0.60833335,
        0.12968749999999998,
        0.18541667
      ],
      "id": 230216,
      "area": 1.0,
      "iscrowd": 0,
      "image_id": 3815,
      "category_id": 292
    },
`

**Comment by hellock** [comment]
According to your logs, there is no positive samples because the RPN performs poor.

**Comment by Rajat-Mehta** [comment]
@hellock how to solve this RPN performance issue then?
