### ISSUE TITLE
excuse me how can i use mmcv.ops ? what are the changes that i should do it ?

### ISSUE THREAD

**Issue by prayagpawar** [open-mmlab/mmdetection#9306]
excuse me how can i use mmcv.ops ? what are the changes that i should do it ?

_Originally posted by @mathshangw in https://github.com/open-mmlab/mmdetection/issues/4475#issuecomment-863541357_

**Comment by BIGWangYuDong** [comment]
The ops are in the [MMCV](https://github.com/open-mmlab/mmcv) repo. You can have a look at here: https://github.com/open-mmlab/mmcv/tree/master/mmcv/ops

**Comment by prayagpawar** [comment]
Hey thanks for your help i tried installing latest version of mmdet still it says
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/home/pdrl/aerialdetection/AerialDetection/mmdet/ops/dcn/__init__.py)
could u please thanks & regards have a good day
________________________________

**Comment by BIGWangYuDong** [comment]
please check whether you have installed mmcv successfully. you can try to use python import mmcv.ops to have a look
