### ISSUE TITLE
[Feature] [3.x] Can  visualizer encapsulate a simpler way?

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmdetection#9312]
### What's the feature?

I think it's a good way to do it like mmseg. It's simple and easy for beginners to use.

https://github.com/open-mmlab/mmsegmentation/blob/7927591a22f901756d54dc2cad8a5f56ae01cf64/mmseg/apis/inference.py#L148

**Comment by ZwwWayne** [comment]
Thanks for your kind suggestion. Would appreciate it if the community can create a PR.

**Comment by sanbuphy** [comment]
> Thanks for your kind suggestion. Would appreciate it if the community can create a PR.
OK, I have finished it in 
https://github.com/open-mmlab/mmdetection/pull/9317
