### ISSUE TITLE
[Feature] Can we set the random seed in the mmdetection?

### ISSUE THREAD

**Issue by Agito555** [open-mmlab/mmdetection#9323]
### What's the feature?

I know the random seed can be set in the distributed training by setting the argument ``seed`` to any fix number you want. However, there is little information to set the random seed in single GPU training, which may have impact on the model performance (±0.6 AP in my experiments), making hard to compare models in a fair way.
I wonder whether to set the random seed in the single GPU training now ? 
If not, I think it is necessary to implement this to compare models in a fair way.

**Comment by Agito555** [comment]
> This is how i call training for single gpu:
> 
> ```shell
> python ./train.py /PATH_TO_MODEL_CFG/model_oct.py --gpu-id 0 --seed 42
> ```

Thanks for your help!! I miss the argument ``seed`` in the train.py.

**Comment by cpwan** [comment]
how about the 3.x version?

**Comment by Agito555** [comment]
> how about the 3.x version?

I haven't used the 3.x version mmdetection yet, and I don't see the argument ``seed`` in the train.py of 3.x mmdetection.
I will reopen the issue, hope somebody else will offer some help.

**Comment by cpwan** [comment]
I found it in mmengine's [code](https://github.com/open-mmlab/mmengine/blob/7e787d8ffa32c2bd26e8b826376020d287d6e3d5/mmengine/runner/runner.py#L262)
```shell
python ./tools/train.py /path/to/config.py --cfg-options randomness.seed=0 
```
The results for the same seed differ by a little.

When I add also `randomness.deterministic=True`, it gives me a cuda internal error :(
