### ISSUE TITLE
How to use backbone of DLA-34 of CenterNet?

### ISSUE THREAD

**Issue by Murray-Yin** [open-mmlab/mmdetection#9328]
### Model/Dataset/Scheduler description

Most original backbone of CenterNet is ResNet18. However, I don't know how to change and use the DLA34 to be the backbone of CenterNet. I am looking forward to some structural suggestions, thanks! 

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by BIGWangYuDong** [comment]
you can have a look at docs:
1. https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/how_to.md#use-backbone-network-implemented-in-mmclassification
2. https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_models.md
