### ISSUE TITLE
How many GPUs does Widerface run on by default?

### ISSUE THREAD

**Issue by Cathy1900** [open-mmlab/mmdetection#9338]
### What's the feature?

I would like to know how many GPUs the Widerface dataset is running on by default, because when I run ssd300_wider_face.py, the loss is always _nan_. I am running ssd300_wider_face.py on 4 GPUs with a batch size of 480 (i.e., 120 images per GPU).
The optimizer is configured as follows：
optimizer = dict(type='SGD', lr=0.012, momentum=0.9, weight_decay=0.0005)

**Comment by BIGWangYuDong** [comment]
Sorry for the late reply, I think you can follow PR: https://github.com/open-mmlab/mmdetection/pull/8468 
it gives an example that using 1gpu with bs 32.

**Comment by Cathy1900** [comment]
> Sorry for the late reply, I think you can follow PR: #8468 it gives an example that using 1gpu with bs 32.

Thank you for your response. With a batch size of 32, does the optimizer have to be modified to the following configuration?
optim_wrapper = dict(optimizer=dict(lr=0.002, momentum=0.9, weight_decay=5e-4))

**Comment by BIGWangYuDong** [comment]
Haven't run the Widerface before, so I don't sure about the default learning rate. But the learning rate should linear scale by batch size.
