### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by BainOuO** [open-mmlab/mmdetection#9339]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

It is feasible to extract key frames from 8-10 videos (each video lasts for two or three minutes, and the frame rate is 30), about 1500 pictures, as the target detection data set. Is it feasible, and will there be any over fitting phenomenon?

### Environment

test

**Comment by BIGWangYuDong** [comment]
It is recommended to refer to other papers. And it needs to be discussed based on the continuity of the video scene. It is hard to say whether it is suitable
