### ISSUE TITLE
Original research backbone  architecture missing！

### ISSUE THREAD

**Issue by 2050airobert** [open-mmlab/mmdetection#9347]
### Model/Dataset/Scheduler description

hi，
     Is there some original research backbone  architecture by MMLAB or sensetime？ Could you show some model like that or share the link with me？  
     Looking forward to your reply ~   

BR 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available.

**Comment by BIGWangYuDong** [comment]
MMDet can use MMCls's classifier as the backbone. You can have a try. (Especially MMDet 3.0 is easier to set mmcls model as the backbone.)
