### ISSUE TITLE
Get the IoU between predicted bounding boxes and GT.

### ISSUE THREAD

**Issue by Cathy1900** [open-mmlab/mmdetection#9348]
### What's the feature?

How can I get the IoU between the predicted bounding box and its corresponding GT when the model is inferred on the COCO _minival_ set? Thanks!

**Comment by BIGWangYuDong** [comment]
Try to use function: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/bbox_overlaps.py

Moreover, voc-type evaluation function will calculate IoUs, so you can have a look.
