### ISSUE TITLE
[AttributeError] : MultiImageMixDataset: 'ConfigDict' object has no attribute 'CLASSES'

### ISSUE THREAD

**Issue by Hshuqin** [open-mmlab/mmdetection#9360]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

mmcv-full 1.3.9
mmdet 2.11.0
torch 1.6

### Reproduces the problem - code sample

img_scale=(1333, 800)
train_pipeline = [
    dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(-img_scale[0] // 2, -img_scale[1] // 2)), # The image will be enlarged by 4 times after Mosaic processing,so we use affine transformation to restore the image size.
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
train_dataset = dict(
    _delete_=True, # remove unnecessary Settings
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline
)
data = dict(
    train=train_dataset
)

### Reproduces the problem - command or script

Hello, I want to apply mosaic enhancement to the model. I refer to the how_to.md document. However, I still encounter the following problem. How can I solve it?
I don't know if it's related to the mmcv version? Still; since my mmcv version can't be changed, I didn't try to do that; I'd like to ask the author if I'm missing any information.

### Reproduces the problem - error message

AttributeError: 'ConfigDict' object has no attribute 'CLASSES'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/xxx/disk/xxx/anaconda3/envs/vp/lib/python3.8/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: MultiImageMixDataset: 'ConfigDict' object has no attribute 'CLASSES'
python-BaseException

**Comment by Czm369** [comment]
`dataset_type` is ?

**Comment by Hshuqin** [comment]
> 

coco dataset

**Comment by ZwwWayne** [comment]
Invite @RangiLyu to have a look

**Comment by RangiLyu** [comment]
Please provide more information:
- Use `tools/misc/print_config.py` to show your full config.
- What code did you modify?
- What command did you run?

**Comment by vamoslc** [comment]
你好  请问问题解决了吗  怎样解决的呢？

**Comment by leenamx** [comment]
Same problem, how did you solve it? Thanks! @Hshuqin
