### ISSUE TITLE
[Docs] How to properly modify train_pipeline

### ISSUE THREAD

**Issue by masotrix** [open-mmlab/mmdetection#9361]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

I have followed the demo on https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb with a custom dataset successfully However when I modify the training_pipeline to use a higher/lower image size like this

```
#-- This code is part of the demo, not mine --#
# We can also use tensorboard to log the training process
cfg.log_config.hooks = [
    dict(type='TextLoggerHook'),
    dict(type='TensorboardLoggerHook')]
#---------------------------------------------#

#-- This is the code I added --#
cfg.train_pipeline[5].img_scale = (320, 320); # Already checked index 5 corresponds to Resize operation
cfg.test_pipeline[1].img_scale = (320, 320); # Already checked index 1 corresponds to MultiScaleFlipAug operation
#------------------------------#

#-- This code is part of the demo, not mine --#
# We can initialize the logger for training and have a look
# at the final config used for training
print(f'Config:\n{cfg.pretty_text}')
#---------------------------------------------#
```

the results are approximately the same, although they should be much worse
Also tried with other sizes (e.g (2666, 1600), (608, 608)) with approximately identical results (same loss curve, training time and memory usage) thus I believe the changes I am making are not being used by the training procedure

I read https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html for any clue but did not find any example showing the method to the one the customized pipeline should be given

### Suggest a potential alternative/fix

It is my thought that one of the following resources should contain an example/pointer for this use case
- The demo: https://github.com/open-mmlab/mmdetection/blob/master/demo/MMDet_Tutorial.ipynb
- The custom pipeline documentation: https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html
- Or a new file inside https://github.com/open-mmlab/mmdetection/blob/master/demo showing how to use different custom training/testing pipelines in an actual training example

**Comment by Czm369** [comment]
Thanks for your suggestions. Is it convenient for you to submit a pr to complete the document ? We will review it as soon as possible.

**Comment by masotrix** [comment]
If you explain me how to set the ```img_scale``` in the demo the PR would be easy (could do it myself)

**Comment by masotrix** [comment]
Closed by mistake

**Comment by masotrix** [comment]
I found appropriate documentation here https://mmdetection.readthedocs.io/en/latest/tutorials/config.html

Specifically the way is to do 
```
cfg.data.train.pipeline[5].img_scale = (320, 320);
```
Instead of
```
cfg.train_pipeline[5].img_scale = (320, 320);
```

Thanks for this amazing library
