### ISSUE TITLE
[Attention] 超级视客营 MMDetection

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmdetection#9364]
![image](https://user-images.githubusercontent.com/12907710/203212307-f06faf04-ea82-4eb4-a76e-74c7db33b638.png)

## 活动介绍
大家好，第一期 OpenMMLab 超级视客营实训活动开始啦！超级视客营实训活动提供十七个方向、上百个不同难度的任务供大家选择，不管你是初涉 AI 的新手还是资深炼丹师，都有适合你的任务供你选择。助力大家上手 OpenMMLab 开源算法库并参与项目建设。本期活动联合北京超级云计算中心，提供算力支持，为大家开发保驾护航。
活动参与方式：选择你感兴趣的任务，在 OpenMMLab 官网提交报名表。完成匹配后，即可和导师对接制定任务规划，开始上手开发。根据不同任务要求在对应的地址提交代码结果，出题方初步 review 通过后即可领取下一个任务或者坐等领奖。活动详情戳：[OpenMMLab 官网活动页](https://openmmlab.com/activity/codecamp)。

## 任务列表

任务题目 | 任务描述 | 技术标签 | 难易程度 | 积分数
-- | -- | -- | -- | --
支持半监督检测算法 DenseTeacher | 参考 https://github.com/Megvii-BaseDetection/DenseTeacher 中 DenseTeacher 的实现，在 MMDet 3.x 中支持 DenseTeacher | Python，PyTorch，半监督检测 | 高级任务 | 80
EQLv2 算法支持 | 参考 https://github.com/tztztztztz/eqlv2 中的实现，在 MMDet 3.x 中支持 EQLv2 Loss，并且在 LVIS 数据集上复现精度 | Python，PyTorch，长尾目标检测 | 进阶任务 | 30
ECMLoss 算法支持 | 参考 https://github.com/janghyuncho/ECM-Loss/blob/main/mmdet/models/losses/effective_class_margin_loss.py 中关于 ECMLoss 的实现，在 MMDet 3.x 中支持 ECMLoss，并在 LVIS 数据集上复现精度 | Python，PyTorch，长尾目标检测 | 进阶任务 | 30
添加 type hints | 选择链接中任一 part 代码添加 type hints，详见：https://github.com/open-mmlab/mmdetection/discussions/9234 | Python，PyTorch | 新手任务 | 10
中文文档翻译 | 选择链接中 “Docs translation or update” 中任一 part 进行翻译，详见：https://github.com/open-mmlab/mmdetection/discussions/9234 （位于链接内 issue 底部） | Python，PyTorch | 新手任务 | 10

活动报名地址：[报名表地址](https://openmmlab.com/activity/codecamp/apply)
根据任务难度可以获得对应积分，兑换不同奖品。另外完成任务后在知识社区发布学习心得即可获得额外积分（记得主动找小助手领取哦）。
活动交流群：群二维码
[图片]
有任何疑问欢迎大家加入群聊或者 Issue 下参与讨论，快来完成挑战，加入 [OpenMMLab 贡献者队伍](https://openmmlab.com/contributor/path)吧～

完成报名后请到[Discussion 页面](https://github.com/open-mmlab/mmdetection/discussions/9234)领取任务

**Comment by JosonChan1998** [comment]
@RangiLyu 你好，在报名填志愿的时候，中级任务里面好像没有对应的任务~

**Comment by RangiLyu** [comment]
> 

中级任务只有两个，应该是已经被认领完了

**Comment by RangiLyu** [comment]
> @RangiLyu 你好，在报名填志愿的时候，中级任务里面好像没有对应的任务~

中级任务只有两个，应该是已经被认领完了

**Comment by RangiLyu** [comment]
> @RangiLyu 你好，在报名填志愿的时候，中级任务里面好像没有对应的任务~

@JosonChan1998 Hi，我们打算在第二期活动中增加支持BoxInst的任务，你有兴趣来参加吗？

**Comment by JosonChan1998** [comment]
> > @RangiLyu 你好，在报名填志愿的时候，中级任务里面好像没有对应的任务~
> 
> @JosonChan1998 Hi，我们打算在第二期活动中增加支持BoxInst的任务，你有兴趣来参加吗？

有的~
