### ISSUE TITLE
Install mmcv-full gets stuck

### ISSUE THREAD

**Issue by arkerman** [open-mmlab/mmdetection#9368]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

I followed the [installation](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md/#Installation) instructions in the documentation to install mmcv-full.
And i wanna install mmcv-full without mim . So i used this command line : 
**_pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.1/index.html_**

But anaconda prompt was stuck , as the picture below shows . 
![image](https://user-images.githubusercontent.com/63221199/203242169-0245e1f0-757a-42a4-8603-779b65a1c848.png)

How can i install mmcv-full quickly by pip ? 

### Suggest a potential alternative/fix

Maybe something need to speed up ?

**Comment by arkerman** [comment]
Any help will be appreciated .

**Comment by ZwwWayne** [comment]
It is installing MMCV, you might only need to wait it. However, we have not fully tested it on ARM64 device with Windows OS.
