### ISSUE TITLE
[Bug] UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.   warnings.warn(

### ISSUE THREAD

**Issue by IECCLES4** [open-mmlab/mmdetection#9371]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

I installed PyTorch through conda.

### Reproduces the problem - code sample

```
# Adding a base config file
_base_ = '../faster_rcnn/faster_rcnn_r101_caffe_fpn_1x_coco.py'

# We also need to change the num_classes in head to match the dataset's annotation
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=1)))

# Modify dataset related settings
dataset_type = 'COCODataset'
classes = ('pantograph',)
data = dict(
    train=dict(
        img_prefix='configs/pantograph/train/',
        classes=classes,
        ann_file='configs/pantograph/train/result.json'),
    val=dict(
        img_prefix='configs/pantograph/val/',
        classes=classes,
        ann_file='configs/pantograph/val/result.json'),
    test=dict(
        img_prefix='configs/pantograph/val/',
        classes=classes,
        ann_file='configs/pantograph/val/result.json'))

# We can use the pre-trained Mask RCNN model to obtain higher performance
load_from = 'checkpoints/faster_rcnn_r101_caffe_fpn_1x_coco_bbox_mAP-0.398_20200504_180057-b269e9dd.pth'
```

### Reproduces the problem - command or script

```
python demo/image_demo.py configs/pantograph/black_sabbath.png configs/pantograph/faster_rcnn_pantograph.py checkpoints/faster_rcnn_r101_caffe_fpn_1x_coco_bbox_mAP-0.398_20200504_180057-b269e9dd.pth --device cpu
```

### Reproduces the problem - error message

```
The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).
size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([2]).
size mismatch for roi_head.bbox_head.fc_reg.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([4, 1024]).
size mismatch for roi_head.bbox_head.fc_reg.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([4]).
/home/dtl-admin/dev/repos/bitbucket/railsight/mmdetection-2.25.3/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
```

### Additional information

I'm trying to train a custom model and so far the training works but whenever I try to output an image I get something like this:
![result](https://user-images.githubusercontent.com/115797971/203362089-1cbecb10-5ec1-4a19-9c08-f0e1f76569a1.png)
I have trained this model with 600 images and about 400 images were in the val folder as well so I'm not sure what's going wrong here.
Any help is greatly appreciated!

**Comment by ZwwWayne** [comment]
The command of demo uses your own config to load a checkpoint pre-trained on COCO.
Because your model does not have the same number of classes, so the pre-trained model is not fully loaded, especially those prediction layers that are not loaded and thus randomly initialized.
