### ISSUE TITLE
errors when I replace the backbone of HTC with ConvNext

### ISSUE THREAD

**Issue by Skyninth** [open-mmlab/mmdetection#9379]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA A30
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0
OpenCV: 4.6.0
MMCV: 1.4.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.25.3+e71b499

### Reproduces the problem - code sample

there is my configs:

htc_without_semantic_r50_fpn_1x_coco.py:
_base_ = [
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
# model settings
model = dict(
    type='HybridTaskCascade',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    roi_head=dict(
        type='HybridTaskCascadeRoIHead',
        interleaved=True,
        mask_info_flow=True,
        num_stages=3,
        stage_loss_weights=[1, 0.5, 0.25],
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=1,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ],
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=[
            dict(
                type='HTCMaskHead',
                with_conv_res=False,
                num_convs=4,
                in_channels=256,
                conv_out_channels=256,
                num_classes=1,
                loss_mask=dict(
                    type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)),
            dict(
                type='HTCMaskHead',
                num_convs=4,
                in_channels=256,
                conv_out_channels=256,
                num_classes=1,
                loss_mask=dict(
                    type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)),
            dict(
                type='HTCMaskHead',
                num_convs=4,
                in_channels=256,
                conv_out_channels=256,
                num_classes=1,
                loss_mask=dict(
                    type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))
        ]),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='soft_nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.6,
                    neg_iou_thr=0.6,
                    min_pos_iou=0.6,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.7,
                    neg_iou_thr=0.7,
                    min_pos_iou=0.7,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='soft_nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.001,
            nms=dict(type='soft_nms', iou_threshold=0.5),
            max_per_img=1000,
            mask_thr_binary=0.5)))
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    val=dict(pipeline=test_pipeline), test=dict(pipeline=test_pipeline))

htc_without_semantic_connext-s.py:
 
_base_ = './htc_without_semantic_r50_fpn_1x_coco.py'

custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False)
checkpoint_file = 'https://download.openmmlab.com/mmclassification/v0/convnext/downstream/convnext-small_3rdparty_32xb128-noema_in1k_20220301-303e75e3.pth' # noqa

model = dict(
    backbone=dict(
        _delete_=True,
        type='mmcls.ConvNeXt',
        arch='small',
        out_indices=[0, 1, 2, 3],
        drop_path_rate=0.6,
        layer_scale_init_value=1.0,
        gap_before_final_norm=False,
        init_cfg=dict(
            type='Pretrained', checkpoint=checkpoint_file,
            prefix='backbone.')),
    neck=dict(in_channels=[96, 192, 384, 768]),
    roi_head=dict(bbox_head=[
        dict(
            type='ConvFCBBoxHead',
            num_shared_convs=4,
            num_shared_fcs=1,
            in_channels=256,
            conv_out_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=1,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            reg_decoded_bbox=True,
            norm_cfg=dict(type='SyncBN', requires_grad=True),
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='GIoULoss', loss_weight=10.0)),
        dict(
            type='ConvFCBBoxHead',
            num_shared_convs=4,
            num_shared_fcs=1,
            in_channels=256,
            conv_out_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=1,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.05, 0.05, 0.1, 0.1]),
            reg_class_agnostic=False,
            reg_decoded_bbox=True,
            norm_cfg=dict(type='SyncBN', requires_grad=True),
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='GIoULoss', loss_weight=10.0)),
        dict(
            type='ConvFCBBoxHead',
            num_shared_convs=4,
            num_shared_fcs=1,
            in_channels=256,
            conv_out_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=1,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.033, 0.033, 0.067, 0.067]),
            reg_class_agnostic=False,
            reg_decoded_bbox=True,
            norm_cfg=dict(type='SyncBN', requires_grad=True),
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='GIoULoss', loss_weight=10.0))
    ]))
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

optimizer = dict(
    _delete_=True,
    constructor='LearningRateDecayOptimizerConstructor',
    type='AdamW',
    lr=0.0002,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg={
        'decay_rate': 0.7,
        'decay_type': 'layer_wise',
        'num_layers': 12
    })

lr_config = dict(warmup_iters=1000, step=[27, 33])
runner = dict(max_epochs=36)

### Reproduces the problem - command or script

bash /ViT-Adapter-main/detection/dist_train.sh configs/htc++/htc_without_semantic_connext-s.py 4

### Reproduces the problem - error message

2022-11-24 08:08:28,212 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
2022-11-24 08:08:28,214 - mmdet - INFO - Checkpoints will be saved to /15041189167/ViT-Adapter-main/detection/work_dirs/htc_without_semantic_connext-t by HardDiskBackend.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [34,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [35,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [36,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [37,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [38,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [39,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [2,0,0], thread: [40,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator()/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu: block: [2:115,0: operator(),0: block: [3], thread: [20,0,0,0,0], thread: [32] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.
,0/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds":115` failed.
: operator()/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu: block: [2:115,0: operator(),0: block: [3], thread: [21,0,0,0,0], thread: [33] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.
,0/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds":115` failed.
: operator()/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu: block: [2:115,0: operator(),0: block: [3], thread: [22,0,0,0,0], thread: [34] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.
,0/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds":115` failed.
: operator()/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu: block: [2:115,0: operator(),0: block: [3], thread: [23,0,0,0,0], thread: [35] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.
,0/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds":115` failed.
: operator()/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu: block: [2:115,0: operator(),0: block: [3], thread: [24,0,0,0,0], thread: [36] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.
,0/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds":115` failed.
: operator()/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu: block: [2:115,0: operator(),0: block: [3], thread: [25,0,0,0,0], thread: [37] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.
,0/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds":115` failed.
: operator()/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu: block: [2:115,0: operator(),0: block: [3], thread: [26,0,0,0,0], thread: [38] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds",0` failed.
,0/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds":115` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115:115: operator(): operator(): block: [6: block: [3,0,0,0,0], thread: [15], thread: [58,0,0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
` failed.
/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu/opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115:115: operator(): operator(): block: [6: block: [3,0,0,0,0], thread: [16], thread: [59,0,0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
` failed.
Traceback (most recent call last):
  File "/15041189167/ViT-Adapter-main/detection/train.py", line 193, in <module>
    main()
  File "/15041189167/ViT-Adapter-main/detection/train.py", line 189, in main
    meta=meta)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/models/detectors/two_stage.py", line 150, in forward_train
    **kwargs)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/models/roi_heads/htc_roi_head.py", line 299, in forward_train
    bbox_results['bbox_pred'], pos_is_gts, img_metas)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 448, in refine_bboxes
    img_meta_)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 491, in regress_by_class
    rois, bbox_pred, max_shape=max_shape)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py", line 99, in decode
    self.ctr_clamp)
  File "/root/anaconda3/envs/vita/lib/python3.7/site-packages/mmcv/utils/parrots_jit.py", line 22, in wrapper_inner
    return func(*args, **kargs)
  File "/15041189167/ViT-Adapter-main/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py", line 230, in delta2bbox
    means = deltas.new_tensor(means).view(1, -1)
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1603729047590/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fc791b948b2 in /root/anaconda3/envs/vita/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7fc791de6982 in /root/anaconda3/envs/vita/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7fc791b7fb7d in /root/anaconda3/envs/vita/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5fbb7a (0x7fc7dbee5b7a in /root/anaconda3/envs/vita/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5fbc26 (0x7fc7dbee5c26 in /root/anaconda3/envs/vita/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x18103a (0x563e11c7e03a in /root/anaconda3/envs/vita/bin/python)
frame #6: <unknown function> + 0xfc359 (0x563e11bf9359 in /root/anaconda3/envs/vita/bin/python)
frame #7: <unknown function> + 0xfac88 (0x563e11bf7c88 in /root/anaconda3/envs/vita/bin/python)
frame #8: <unknown function> + 0xfac88 (0x563e11bf7c88 in /root/anaconda3/envs/vita/bin/python)
frame #9: <unknown function> + 0xfa6a8 (0x563e11bf76a8 in /root/anaconda3/envs/vita/bin/python)
frame #10: <unknown function> + 0xfb128 (0x563e11bf8128 in /root/anaconda3/envs/vita/bin/python)
frame #11: <unknown function> + 0xfb13c (0x563e11bf813c in /root/anaconda3/envs/vita/bin/python)
frame #12: <unknown function> + 0xfb13c (0x563e11bf813c in /root/anaconda3/envs/vita/bin/python)
frame #13: <unknown function> + 0xfb13c (0x563e11bf813c in /root/anaconda3/envs/vita/bin/python)
frame #14: <unknown function> + 0xfb13c (0x563e11bf813c in /root/anaconda3/envs/vita/bin/python)
frame #15: <unknown function> + 0xfb13c (0x563e11bf813c in /root/anaconda3/envs/vita/bin/python)
frame #16: <unknown function> + 0xfb13c (0x563e11bf813c in /root/anaconda3/envs/vita/bin/python)
frame #17: <unknown function> + 0x12b4a7 (0x563e11c284a7 in /root/anaconda3/envs/vita/bin/python)
frame #18: PyDict_SetItemString + 0x89 (0x563e11c34a19 in /root/anaconda3/envs/vita/bin/python)
frame #19: PyImport_Cleanup + 0xab (0x563e11ca9b8b in /root/anaconda3/envs/vita/bin/python)
frame #20: Py_FinalizeEx + 0x64 (0x563e11d1e714 in /root/anaconda3/envs/vita/bin/python)
frame #21: <unknown function> + 0x232e20 (0x563e11d2fe20 in /root/anaconda3/envs/vita/bin/python)
frame #22: _Py_UnixMain + 0x3c (0x563e11d3018c in /root/anaconda3/envs/vita/bin/python)
frame #23: __libc_start_main + 0xe7 (0x7fc80c0dfb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #24: <unknown function> + 0x1d803a (0x563e11cd503a in /root/anaconda3/envs/vita/bin/python)

**Comment by RangiLyu** [comment]
Try to set `reg_class_agnostic=True,`
