### ISSUE TITLE
[Feature] Does mmdet version 2.25 support one-stage detection head (e.g. yolo head) as RPN head in faster R-CNN?

### ISSUE THREAD

**Issue by hjfdsssdg** [open-mmlab/mmdetection#9382]
### What's the feature?

Is there a reference tutorial for this? I found that version 2.25 does not work properly after changing the configuration by referring to version 3.0.

TypeError: loss() missing 1 required positional argument: 'img_metas'

**Comment by RangiLyu** [comment]
MMDetection 2.x does not support single-stage as RPN. You need to use the 3.x version. Please refer to https://mmdetection.readthedocs.io/en/3.x/user_guides/single_stage_as_rpn.html

**Comment by hjfdsssdg** [comment]
@RangiLyu Okay, thank you!
