### ISSUE TITLE
[Bug] fps benchmark tool can't work

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmdetection#9387]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

ubuntu & windows

### Reproduces the problem - code sample

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3393788644214912403 skey=@crypt_63f5860_ba53861a4866d8019822a4f745fae64c mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/96160062/204078640-3a8bc15f-a401-464e-b866-20895ec99b81.jpeg)

### Reproduces the problem - command or script

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=584247836287114794 skey=@crypt_63f5860_ba53861a4866d8019822a4f745fae64c mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/96160062/204078541-dc207f8b-46cf-4c85-bf99-3a3f657e6d72.jpeg)

### Reproduces the problem - error message

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3135412850061144180 skey=@crypt_63f5860_ba53861a4866d8019822a4f745fae64c mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/96160062/204078648-669f4fa3-1dad-4e36-94db-bca8c7abbe03.jpeg)

### Additional information

It seems didn't update in 3.x

**Comment by RangeKing** [comment]
https://github.com/open-mmlab/mmdetection/blob/34462a1c358f369fec91d9a028bff3e3eeb8bd54/mmdet/utils/benchmark.py#L54

On windows, `psutil.Process.memory_full_info()` doesn't have `pss`. On linux, `psutil.Process.memory_full_info().pss` works well.

![image](https://user-images.githubusercontent.com/27466624/204079635-efd2befa-bdee-4b4f-8f1a-9b3da33474d4.png)

**Comment by Ghlerrix** [comment]
In this [PR #9865](https://github.com/open-mmlab/mmdetection/pull/9865), I fixed the bug. Maybe the method I used is not the best option, but it works fine.

The error I'm getting is as follows:
![image](https://user-images.githubusercontent.com/114851291/222652640-4e505391-6327-44cc-b450-3cce990ee3bc.png)

The result of the same command after repair is as follows:
![image](https://user-images.githubusercontent.com/114851291/222652845-60c1fd28-6fff-450b-9aa3-e85250a79d3a.png)

**Comment by okt7760** [comment]
[Ghlerrix](https://github.com/Ghlerrix) There is a new problem with the modified benchmark

**Comment by Ghlerrix** [comment]
I don't know what is causing this error. Maybe it's because we are using different versions. You can take a look at my environment configuration.
```
Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) [GCC 11.3.0]
    CUDA available: True
    numpy_random_seed: 1799939178
    GPU 0: NVIDIA GeForce RTX 3090
    CUDA_HOME: /usr/local/cuda-11.1
    NVCC: Cuda compilation tools, release 11.1, V11.1.105
    GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
    PyTorch: 1.10.0+cu111
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.11.0+cu111
    OpenCV: 4.7.0
    MMEngine: 0.6.0
```
```
Package             Version        Editable project location
------------------- -------------- ------------------------------
addict              2.4.0
attrs               22.2.0
certifi             2022.12.7
charset-normalizer  3.1.0
click               8.1.3
colorama            0.4.6
contourpy           1.0.7
coverage            7.2.1
cycler              0.11.0
exceptiongroup      1.1.1
fonttools           4.39.0
idna                3.4
imageio             2.26.1
importlib-metadata  6.0.0
importlib-resources 5.12.0
iniconfig           2.0.0
joblib              1.2.0
kiwisolver          1.4.4
lazy_loader         0.1
Markdown            3.4.1
markdown-it-py      2.2.0
matplotlib          3.7.1
mdurl               0.1.2
mmconfig            0.0.5
mmcv                2.0.0rc4
mmdet               3.0.0rc6       /home/ubuntu/mmlab/mmdetection
mmengine            0.6.0
model-index         0.1.11
networkx            3.0
numpy               1.24.2
opencv-python       4.7.0.72
openmim             0.3.6
ordered-set         4.1.0
packaging           23.0
pandas              1.5.3
Pillow              9.4.0
pip                 23.0.1
pluggy              1.0.0
psutil              5.9.4
pycocotools         2.0.6
Pygments            2.14.0
pyparsing           3.0.9
pytest              7.2.2
python-dateutil     2.8.2
PyTurboJPEG         1.7.0
pytz                2022.7.1
PyWavelets          1.4.1
PyYAML              6.0
requests            2.28.2
rich                13.3.2
scikit-image        0.20.0
scikit-learn        1.2.2
scipy               1.9.1
setuptools          67.6.0
shapely             2.0.1
six                 1.16.0
tabulate            0.9.0
termcolor           2.2.0
terminaltables      3.1.10
threadpoolctl       3.1.0
tifffile            2023.3.15
tomli               2.0.1
torch               1.10.0+cu111
torchaudio          0.10.0+rocm4.1
torchvision         0.11.0+cu111
typing_extensions   4.5.0
urllib3             1.26.15
wheel               0.38.4
yapf                0.32.0
zipp                3.15.0
```

**Comment by Ghlerrix** [comment]
> [Ghlerrix](https://github.com/Ghlerrix) There is a new problem with the modified benchmark!!!
> 
> AttributeError: 'DistributedDataParallel' object has no attribute 'test_step'

I don't know what is causing this error. Maybe it's because we are using different versions. You can take a look at my environment configuration.
```
Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) [GCC 11.3.0]
    CUDA available: True
    numpy_random_seed: 1799939178
    GPU 0: NVIDIA GeForce RTX 3090
    CUDA_HOME: /usr/local/cuda-11.1
    NVCC: Cuda compilation tools, release 11.1, V11.1.105
    GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
    PyTorch: 1.10.0+cu111
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.11.0+cu111
    OpenCV: 4.7.0
    MMEngine: 0.6.0
```
```
Package             Version        Editable project location
------------------- -------------- ------------------------------
addict              2.4.0
attrs               22.2.0
certifi             2022.12.7
charset-normalizer  3.1.0
click               8.1.3
colorama            0.4.6
contourpy           1.0.7
coverage            7.2.1
cycler              0.11.0
exceptiongroup      1.1.1
fonttools           4.39.0
idna                3.4
imageio             2.26.1
importlib-metadata  6.0.0
importlib-resources 5.12.0
iniconfig           2.0.0
joblib              1.2.0
kiwisolver          1.4.4
lazy_loader         0.1
Markdown            3.4.1
markdown-it-py      2.2.0
matplotlib          3.7.1
mdurl               0.1.2
mmconfig            0.0.5
mmcv                2.0.0rc4
mmdet               3.0.0rc6       /home/ubuntu/mmlab/mmdetection
mmengine            0.6.0
model-index         0.1.11
networkx            3.0
numpy               1.24.2
opencv-python       4.7.0.72
openmim             0.3.6
ordered-set         4.1.0
packaging           23.0
pandas              1.5.3
Pillow              9.4.0
pip                 23.0.1
pluggy              1.0.0
psutil              5.9.4
pycocotools         2.0.6
Pygments            2.14.0
pyparsing           3.0.9
pytest              7.2.2
python-dateutil     2.8.2
PyTurboJPEG         1.7.0
pytz                2022.7.1
PyWavelets          1.4.1
PyYAML              6.0
requests            2.28.2
rich                13.3.2
scikit-image        0.20.0
scikit-learn        1.2.2
scipy               1.9.1
setuptools          67.6.0
shapely             2.0.1
six                 1.16.0
tabulate            0.9.0
termcolor           2.2.0
terminaltables      3.1.10
threadpoolctl       3.1.0
tifffile            2023.3.15
tomli               2.0.1
torch               1.10.0+cu111
torchaudio          0.10.0+rocm4.1
torchvision         0.11.0+cu111
typing_extensions   4.5.0
urllib3             1.26.15
wheel               0.38.4
yapf                0.32.0
zipp                3.15.0
```

**Comment by sanbuphy** [comment]
> In this [PR #9865](https://github.com/open-mmlab/mmdetection/pull/9865), I fixed the bug. Maybe the method I used is not the best option, but it works fine.
> 
> The error I'm getting is as follows: ![image](https://user-images.githubusercontent.com/114851291/222652640-4e505391-6327-44cc-b450-3cce990ee3bc.png)
> 
> The result of the same command after repair is as follows: ![image](https://user-images.githubusercontent.com/114851291/222652845-60c1fd28-6fff-450b-9aa3-e85250a79d3a.png)

Thank you very much!

**Comment by GTrui6** [comment]
> [Ghlerrix](https://github.com/Ghlerrix) There is a new problem with the modified benchmark!!!
> 
> AttributeError: 'DistributedDataParallel' object has no attribute 'test_step'

Hi, i also came across with this problem, but when i delete the "--launcher pytorch " in the command, it  worked well

**Comment by 19990101lrk** [comment]
> ## Another issue in `benchmark.py`:
> On windows, `psutil.Process.memory_full_info()` doesn't have `pss`. On linux, `psutil.Process.memory_full_info().pss` works well.
> 
> https://github.com/open-mmlab/mmdetection/blob/34462a1c358f369fec91d9a028bff3e3eeb8bd54/mmdet/utils/benchmark.py#L54
> 
> ![image](https://user-images.githubusercontent.com/27466624/204079635-efd2befa-bdee-4b4f-8f1a-9b3da33474d4.png)

@RangeKing Is this bug solved? I had the same problem

**Comment by RangeKing** [comment]
> > ## Another issue in `benchmark.py`:
> > On windows, `psutil.Process.memory_full_info()` doesn't have `pss`. On linux, `psutil.Process.memory_full_info().pss` works well.
> > https://github.com/open-mmlab/mmdetection/blob/34462a1c358f369fec91d9a028bff3e3eeb8bd54/mmdet/utils/benchmark.py#L54
> > 
> > ![image](https://user-images.githubusercontent.com/27466624/204079635-efd2befa-bdee-4b4f-8f1a-9b3da33474d4.png)
> 
> @RangeKing Is this bug solved? I had the same problem

I think it's not solved yet. Maybe need to open a new issue.

**Comment by TheGreatTreatsby** [comment]
> [Ghlerrix](https://github.com/Ghlerrix) There is a new problem with the modified benchmark!!!
> 
> AttributeError: 'DistributedDataParallel' object has no attribute 'test_step'

try --launcher=‘none’
