### ISSUE TITLE
training with multi machine and multi gpus 

### ISSUE THREAD

**Issue by shuxp** [open-mmlab/mmdetection#941]
I have five ubuntu servers in local network, and each machine has 4GPUs. I want to fully use these GPUs. After I search pytorch document, I found  [torch.distributed](https://pytorch.org/docs/stable/distributed.html#launch-utility) may solve my problem. When I check mmdetection, I found [slurm_train.sh](https://github.com/open-mmlab/mmdetection/blob/master/tools/slurm_train.sh) may be more flexible. But data about pytorch+slurm maybe quiet little. 

So could you please provide some data about setup slurm with multi machines?

**Comment by hellock** [comment]
You may refer to your IT team for setting up slurm on your cluster, which is a problem of ops. All I can help is the [documentation url](https://slurm.schedmd.com/documentation.html), and honestly I do not think it's trivial.
Another option is to follow the [documentation](https://pytorch.org/docs/stable/distributed_deprecated.html#launch-utility) of pytorch launch utility, which is utilized by `tools/dist_train.sh`.

**Comment by shuxp** [comment]
> You may refer to your IT team for setting up slurm on your cluster, which is a problem of ops. All I can help is the [documentation url](https://slurm.schedmd.com/documentation.html), and honestly I do not think it's trivial.
> Another option is to follow the [documentation](https://pytorch.org/docs/stable/distributed_deprecated.html#launch-utility) of pytorch launch utility, which is utilized by `tools/dist_train.sh`.

so torch.distributed and slurm_train can both train with multi machines, right?
But torch.distributed must copy source code to all the machines.
But slutm_train can just use code in the main machine.

Do I understand it wrong?
