### ISSUE TITLE
[Feature] Any way to inference or train on mps device?

### ISSUE THREAD

**Issue by XWHtorrentx** [open-mmlab/mmdetection#9411]
### What's the feature?

I tested with several torchvision models on mps, they worked pretty well.
Is there any possibility for mmdet models on mps device? I tried 
`model = init_detector(config,ckpt,device='mps')`
`result = inference_detector(model,img)`
it showed that the model weights had already been on mps, but img is on cpu instead of mps. I guess it has something to do with the data processing pipeline.

### Any other context?

System Info
torch version is 1.13.0, 
torchvision 0.14,
mmcv 1.7.0,
mmdet with master branch
macOS Ventura 13.0.1
Apple M1 Pro

**Comment by ZwwWayne** [comment]
Because many operators in MMDet are implemented by CUDA in MMCV. MMDet do not support MPS inference for now.
