### ISSUE TITLE
请问咱们的mmdetection可以调用一个模型同时推理预测多个图片吗

### ISSUE THREAD

**Issue by jingmingtao** [open-mmlab/mmdetection#9412]
### Model/Dataset/Scheduler description

请问咱们的mmdetection可以调用一个模型同时推理预测多个图片吗，是要在预测前后加batch处理吗，具体可以有代码参考吗

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by BIGWangYuDong** [comment]
mmdet3.x support multi-batch, but AP may decrease sometime.

**Comment by jingmingtao** [comment]
ok, thanks

**Comment by jingmingtao** [comment]
Can you give a link to the specific py file of mmdet3. x

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmdetection/blob/34462a1c358f369fec91d9a028bff3e3eeb8bd54/configs/_base_/datasets/coco_detection.py#L43-L46

bs = 1 -> 2
