### ISSUE TITLE
Is there a error in Technical report for the mmdetecion?

### ISSUE THREAD

**Issue by wswday** [open-mmlab/mmdetection#942]
at https://arxiv.org/pdf/1906.07155.pdf
![Technical report](https://user-images.githubusercontent.com/13781208/60766609-a3097280-a0de-11e9-897f-bc6fee724769.png)

Is the unit iterations/second or seconds/iteration?

On the basis of "The training speed is faster than or comparable to other codebases, including Detectron, maskrcnn-benchmark and SimpleDet" on readme, the unit should be seconds/iteration.

Thanks!

**Comment by hellock** [comment]
It should be s/iter, thanks!
