### ISSUE TITLE
I want to use Retinanet as the model，but the softteacher.py get a error " 'ConfigDict' object has no attribute 'rpn' "

### ISSUE THREAD

**Issue by Lewisonez** [open-mmlab/mmdetection#9429]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

no environment issue

### Reproduces the problem - code sample

  File "/home/zf/semi-supervised/SoftTeacher/ssod/models/soft_teacher.py", line 50, in forward_train
    data_groups["unsup_teacher"], data_groups["unsup_student"]
  File "/home/zf/semi-supervised/SoftTeacher/ssod/models/soft_teacher.py", line 73, in foward_unsup_train
    else None,
  File "/home/zf/semi-supervised/SoftTeacher/ssod/models/soft_teacher.py", line 353, in extract_teacher_info

### Reproduces the problem - command or script

softteacher.py

        rpn_loss, proposal_list = self.rpn_loss(
            student_info["rpn_out"],
            pseudo_bboxes,
            student_info["img_metas"],
            student_info=student_info,
        )

      if proposals is None:
          proposal_cfg = self.teacher.train_cfg.get(
              "rpn_proposal", self.teacher.test_cfg.rpn
          )
          rpn_out = list(self.teacher.rpn_head(feat))
          proposal_list = self.teacher.rpn_head.get_bboxes(
              *rpn_out, img_metas=img_metas, cfg=proposal_cfg
          )

### Reproduces the problem - error message

AttributeError: 'ConfigDict' object has no attribute 'rpn'

### Additional information

I think the softteacher.py file request that the model must have the rpn module, but there is no rpn in Retinanet

**Comment by ZwwWayne** [comment]
SoftTeacher only works with two-stage detectors as we follow the original implementation in the paper. You can use the SemiBaseDetector for retinanet.
