### ISSUE TITLE
Is it possible to use htc with VOC format datasets?

### ISSUE THREAD

**Issue by ChandanVerma** [open-mmlab/mmdetection#943]
Is it posisible to train htc on my custom dataset on pascal voc format. If yes, could you suggest how it is possible

Thanks
Chandan verma

**Comment by hellock** [comment]
The dataset format is never a problem if you would implement your own dataset. You can train a HTC as if the annotation contains bboxes and masks (the minimum version). For the complete model, semantic segmentation is also needed.

**Comment by ChandanVerma** [comment]
I just have the bboxes and not the masks, want to use it for detection

**Comment by hellock** [comment]
You can adopt other models that require no mask annotation.

**Comment by ChandanVerma** [comment]
Sure thanks
