### ISSUE TITLE
compile.sh error about cuda path

### ISSUE THREAD

**Issue by luxinfeng** [open-mmlab/mmdetection#944]
My enviroments is : 
&emsp;&emsp;ubuntu 18.04.2
&emsp;&emsp;gcc 5.5
&emsp;&emsp;python 3.6.5
&emsp;&emsp;pytorch 1.0
&emsp;&emsp;cuda10.0
When i run compile.sh,it occurs that "**unable to execute '/usr/local/cuda-10.0:/usr/local/cuda-10.0:/usr/local/cuda-10.0:/bin/nvcc': No such file or directory
error: command '/usr/local/cuda-10.0:/usr/local/cuda-10.0:/usr/local/cuda-10.0:/bin/nvcc' failed with exit status 1**"
 And i have add the cuda to the path.In my bashrc,the path about cuda is : 
**export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH**

**export CUDA_HOME=/usr/local/cuda-10.0:$CUDA_HOME**

**export PATH=/usr/local/cuda-10.0/bin:$PATH**

I can't solve this problem.Could you help me?
Thank you very much!

**Comment by hellock** [comment]
Your `CUDA_HOME` is wrong, it should be `/usr/local/cuda-10.0` instead of `/usr/local/cuda-10.0:$CUDA_HOME`.

**Comment by luxinfeng** [comment]
OK,thank you very much

> Your `CUDA_HOME` is wrong, it should be `/usr/local/cuda-10.0` instead of `/usr/local/cuda-10.0:$CUDA_HOME`.
