### ISSUE TITLE
[Bug] Possibly false if-clause in dataset builder for distributed use

### ISSUE THREAD

**Issue by Maenansyn** [open-mmlab/mmdetection#9447]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

-

### Reproduces the problem - code sample

[Link to potential mixed up if-clause](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/builder.py#L128)

```
if dist:
        # When model is :obj:`DistributedDataParallel`,
        # `batch_size` of :obj:`dataloader` is the
        # number of training samples on each GPU.
        batch_size = samples_per_gpu
        num_workers = workers_per_gpu
else:
        # When model is obj:`DataParallel`
        # the batch size is samples on all the GPUS
        batch_size = num_gpus * samples_per_gpu
        num_workers = num_gpus * workers_per_gpu
```

### Reproduces the problem - command or script

not needed

### Reproduces the problem - error message

not existing

### Additional information

Shouldn't the parts be changed to:

```
if dist:
        # When model is :obj:`DistributedDataParallel`,
        # `batch_size` of :obj:`dataloader` is the
        # number of training samples on each GPU
        # multiplied by the number of used gpus.
        batch_size = num_gpus * samples_per_gpu
        num_workers = num_gpus * workers_per_gpu
else:
        # When model is obj:`DataParallel`
        # the batch size is samples on one GPU
        batch_size = samples_per_gpu
        num_workers = workers_per_gpu
```

I can create a PR for it, but first I wanted to let it be checked that it's actually mixed up.

**Comment by Czm369** [comment]
When model is :obj:`DistributedDataParallel`,  `batch_size` of :obj:`dataloader` is the  number of training samples on each GPU. When model is obj:`DataParallel`， the batch size is samples on one GPU. The calculation formula here is correct.
