### ISSUE TITLE
About relu in retinanet

### ISSUE THREAD

**Issue by LaoYang1994** [open-mmlab/mmdetection#945]
https://github.com/open-mmlab/mmdetection/blob/b8bcda671e742d5133c259e8db29f8622657acf7/mmdet/models/anchor_heads/retina_head.py#L34

The relu is defined in this place. But it seems that this relu isn't used in the subsequent part.
I wonder whether it has a effect on the performance.

**Comment by wangg12** [comment]
Hi @hellock  In the original RetinaNet paper, there is a relu before the conv after P6 of FPN, while in this repo the relu is  removed. Is this an intended behavior?
