### ISSUE TITLE
question about multiclass_nms in   forwardtest

### ISSUE THREAD

**Issue by alexwq100** [open-mmlab/mmdetection#946]
hi, @hellock :
  I found  that in the test.py , for the forward testing, in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/post_processing/bbox_nms.py#L6，the nms flow is : for each detected bbox in the top 1000 high possibility from rpn, we get a 81 class prob prediction vector in the rcnn box branch(for the coco dataset as example) . Then for each class , we pick the box this class prob of which is over “score_thr”. Then we do the nms for these boxes of this class. And repeat the process for all class. So each det box from rpn may contribute more than one box in the final result ,right?

   But , in my mind ,the nms is for each detection box from rpn, we pick the class with the highest prob reported by the rcnn. And then do the nms for the boxes of the same class respectively. 

   Do you have any reference to your way? I think , in your way ,the recall may be boosted ?Could you explain it a bit more ,thanks.

**Comment by hellock** [comment]
We just follow the typical convention of post-processing, Fast(er) R-CNN and most other frameworks do the same thing.

**Comment by yzl96** [comment]
@alexwq100 , have you figure out why do this, my understanding of NMS is the same with you, and I see the source code , for each class, mmdetection use all prediction, and use their prob of the class.

**Comment by alexwq100** [comment]
no ,I did not find out the reason from paper, what do you think about it, this can boost the recall?

**Comment by hellock** [comment]
The details are not in the paper, but in the released code by the authors, e.g., [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn), [Detectron](https://github.com/facebookresearch/Detectron).
