### ISSUE TITLE
[Feature] read geotiff image format

### ISSUE THREAD

**Issue by daofeng2007** [open-mmlab/mmdetection#9462]
### What's the feature?

The current mmcv.imread used by MMDetection is based on cv2.imread. However, cv2.imread can not read geotiff image, which is the only image format used by geospatial images. geotiff image usually has more than three bands. geotiff can be read by gdal or rasterio, but not cv2.imread. How to write custom dataloader? Inside the dataloader, gdal or rasterio can be used to read geotiff image.

**Comment by ZwwWayne** [comment]
You can implement a new LoadGeoImageFromFile pipeline similar to LoadImageFromFile, and support to load geotiff image there.
