### ISSUE TITLE
please set   it   to  your   cuda   install  root?

### ISSUE THREAD

**Issue by heartInsert** [open-mmlab/mmdetection#947]
In my  ubuntu , I  use  conda  to  create  the  virtual environment，but  the  shell  'conda install  pytorch  torchvision  cudatoolkit=9.0 '   has  been   assembled  cuda  and  cudnn   as  a    python  lib,  it  likes  stored   in  'conda/env/open-mmlab/lib' ,  that  I  don't  need  to    install   cuda  and  cudnn  twice, so  there  is  no   'CUDA_HOME'   in   ./bashrc    any  more   .
The  question  is , when  I  run  compile.sh  ,it  will   tell  me   
`CUDA_HOME  environment is  not  set, Please  set  it   to your  CUDA  install  root`
I  know  the 'compile.sh' program  can't   find  the  CUDA  environment  in  the conda  virtual  environment,but  I  don't know  how  to  solve  it.
Is  there  anyone  who meet  the  same  question  with me ?  Hopes  your  reply.

**Comment by syedmutti** [comment]
Yes , I met the same issue and I still don't know how to go around it.
Did you find any solution ?
