### ISSUE TITLE
[Feature] Iterable-style dataset support?

### ISSUE THREAD

**Issue by rorschachhb** [open-mmlab/mmdetection#9470]
### What's the feature?

The existing `CustomDataset` is limited to COCO style (annotations written in a file, limited number of images, stored on local disks). But sometimes the training data could be massive (terabytes of data) and stored on hdfs, making it hard to access with image-ids.

Is it possible to make a iterable-style dataset, like `IterableDataset` in `torch.utils.data`?
Thanks!

**Comment by BIGWangYuDong** [comment]
Thanks for your suggestion. Maybe you can discuss the design with us first, and create a PR

**Comment by KyanChen** [comment]
Any plan to integrate webdataset as another dataloader option?
