### ISSUE TITLE
[Bug] AttributeError: 'ConfigDict' object has no attribute 'dist_params'

### ISSUE THREAD

**Issue by yukaizhou** [open-mmlab/mmdetection#9471]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

(deformable_detr) root@workspace:/dfs/data/code_python/detection_2d/mmdetection# python mmdet/utils/collect_env.py
fatal: not a git repository (or any parent up to mount point /dfs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0,1: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0+cu113
OpenCV: 4.6.0
MMCV: 1.3.18
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.26.0+

### Reproduces the problem - code sample

(deformable_detr) root@workspace:/dfs/data/code_python/detection_2d/mmdetection# CUDA_VISIBLE_DEVICES=1 tools/dist_train.sh configs/deformable_detr/deformable_detr_r50_16x2_50e_coco.py 1

### Reproduces the problem - command or script

(deformable_detr) root@workspace:/dfs/data/code_python/detection_2d/mmdetection# CUDA_VISIBLE_DEVICES=1 tools/dist_train.sh configs/deformable_detr/deformable_detr_r50_16x2_50e_coco.py 1

### Reproduces the problem - error message
```
Traceback (most recent call last):
  File "tools/train.py", line 244, in <module>
    main()
  File "tools/train.py", line 172, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/mmcv/utils/config.py", line 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dist_params'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2441) of binary: /dfs/data/anaconda/envs/deformable_detr/bin/python
Traceback (most recent call last):
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-09_15:03:20
  host      : workspace
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2441)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by Li-Qingyun** [comment]
If only one GPU is used, why not use `python train.py config`

**Comment by BIGWangYuDong** [comment]
Feel free to re-open this issue if you still meet this error

**Comment by zhangye-zoe** [comment]
maybe your config file is wrong path

**Comment by Re-dot-art** [comment]
> Feel free to re-open this issue if you still meet this error

Hello, I have encountered this issue, mmdet=2.28.1, mmcv=1.7.1. How should I solve it?
![image](https://github.com/open-mmlab/mmdetection/assets/93500522/b57e474a-fc10-41c2-aa66-d8ddd19d2809)

**Comment by zhangye-zoe** [comment]
maybe your config path is wrong
---- Replied Message ----
| From | ***@***.***> |
| Date | 01/16/2024 11:29 |
| To | open-mmlab/mmdetection ***@***.***> |
| Cc | 张野 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [open-mmlab/mmdetection] [Bug] AttributeError: 'ConfigDict' object has no attribute 'dist_params' (Issue #9471) |

Feel free to re-open this issue if you still meet this error

Hello, I have encountered this issue, mmdet=2.28.1, mmcv=1.7.1. How should I solve it?
image.png (view on web)

**Comment by SanukiUra** [comment]
参数 `dist_params` 一般是从 `mmdetection3d/configs/_base_/default_runtime.py` 继承来的，确保你的这个文件中有类似
`dist_params = dict(backend='nccl')`
的语句
