### ISSUE TITLE
Training with custom dataset but it stuck in an infinite loop

### ISSUE THREAD

**Issue by MinHsuanYu** [open-mmlab/mmdetection#9474]
I try to train the mask2former for own dataset. The annotation format is same with coco format. Just resize the image size to (512, 512) and change normalize parameter.
It does print any error message so i can't find the problem. Have anyone get same problem? Thanks.
There's where the program stuck in an infinite loop.
![image](https://user-images.githubusercontent.com/74700686/206677410-d11b338e-e925-47b7-a029-4cc6862621c7.png)

**Comment by RangiLyu** [comment]
Can you set some breakpoints to locate where it gets stuck?

**Comment by satyajit-ink** [comment]
same here

**Comment by chenjw1009** [comment]
same here

**Comment by satyajitghana** [comment]
I fixed it, turns out the classes list has to be given to the dataset, also make sure the num classes are correct everywhere and defined in model and also in dataset config
