### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by rruixxu** [open-mmlab/mmdetection#9482]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

I would like to fork the repository and develop some features. However, I wonder if I should specify changes in "changelog.md" in the end, since I realize many pull requests did not modify "changelog.md".

**Comment by hhaAndroid** [comment]
@rruixxu Your own modifications don't need to be considered changelog.md
