### ISSUE TITLE
[Bug] I can't run DETR and deformable DETR

### ISSUE THREAD

**Issue by yuhua666** [open-mmlab/mmdetection#9485]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

# Copyright (c) OpenMMLab. All rights reserved.
from mmcv.utils import collect_env as collect_base_env
from mmcv.utils import get_git_hash

import mmdet

def collect_env():
    """Collect the information of the running environments."""
    env_info = collect_base_env()
    env_info['MMDetection'] = mmdet.__version__ + '+' + get_git_hash()[:7]
    return env_info

if __name__ == '__main__':
    for name, val in collect_env().items():
        print(f'{name}: {val}')

### Reproduces the problem - code sample

When I run them , such error occurs.
"DETR: 'DETRHead is not in the head registry'"
'DeformableDETR is not in the detector registry'

### Reproduces the problem - command or script

CUDA_VISIBLE_DEVICES=2,3 PORT=29502 python tools/analysis_tools/get_flops.py configs/deformable_detr/deformable_detr_r50_16x2_50e_coco.py

### Reproduces the problem - error message

"DETR: 'DETRHead is not in the head registry'"
'DeformableDETR is not in the detector registry'

**Comment by ZwwWayne** [comment]
Hi @yuhua666 ,
get_flops does not need two GPUs.
Can you get the error simply by running `python tools/analysis_tools/get_flops.py configs/deformable_detr/deformable_detr_r50_16x2_50e_coco.py`?

**Comment by yuhua666** [comment]
the same error occurs.
KeyError: 'DeformableDETR is not in the detector registry'

**Comment by Li-Qingyun** [comment]
> the same error occurs. KeyError: 'DeformableDETR is not in the detector registry'

Please try another detector, to determine whether it is the algorithm problem. 
Maybe it is your installation problem.
More details require to be provided~
