### ISSUE TITLE
[Docs] how to visualize the instance seg result

### ISSUE THREAD

**Issue by neverstoplearn** [open-mmlab/mmdetection#9486]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

After I trained the maskrcnn model, when I visualize the demo image, I got the same color of one class,how can I got the instance seg result, the instance of same classes have different color? thanks

**Comment by hhaAndroid** [comment]
The current design is really not considered and we will consider improving it.
