### ISSUE TITLE
how to use ConcatDataset in mmdet3.x

### ISSUE THREAD

**Issue by fdhyhtt** [open-mmlab/mmdetection#9491]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0rc1"
git clone https://github.com/open-mmlab/mmdetection.git -b 3.x
# "-b 3.x" means checkout to the `3.x` branch.
cd mmdetection
pip install -v -e .

### Reproduces the problem - code sample

#config file:
dataset_syn_train = dict(
        type=dataset_type,
        data_root='/gemini/data-1',
        metainfo=metainfo,
        ann_file='/gemini/linshi.json',
        data_prefix=dict(img='syn_images/'),
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        pipeline=train_pipeline)
#
dataset_render_train = dict(
        type=dataset_type,
        data_root='/gemini/data-1',
        metainfo=metainfo,
        ann_file='/gemini/linshi.json',
        data_prefix=dict(img='syn_images/'),
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        pipeline=train_pipeline)

train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='InfiniteSampler'),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(type='ConcatDataset', datasets=[dataset_syn_train, dataset_render_train]))
    # dataset=[dataset_syn_train, dataset_render_train]

### Reproduces the problem - command or script

python tools/train.py --configs

### Reproduces the problem - error message

Traceback (most recent call last):
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/registry.py", line 284, in switch_scope_and_registry
    yield registry
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: class `ConcatDataset` in mmdet/datasets/dataset_wrappers.py: __init__() got an unexpected keyword argument 'data_root'
python-BaseException

### Additional information

I directly copied the code of ConcatDataset implemented by MMEngine to mmdetection3. x, but it cannot be used. If the above problem occurs, please ask me how to use ConcatDataset in mmdetection3. x

**Comment by ZwwWayne** [comment]
This is a bit wierd because mmdet/datasets/dataset_wrappers do not have ConcatDataset as you can see here https://github.com/open-mmlab/mmdetection/blob/dev-3.x/mmdet/datasets/dataset_wrappers.py.
You do not need to copy concatdataset, you can directly use it with the same config.

**Comment by fdhyhtt** [comment]
> This is a bit wierd because mmdet/datasets/dataset_wrappers do not have ConcatDataset as you can see here https://github.com/open-mmlab/mmdetection/blob/dev-3.x/mmdet/datasets/dataset_wrappers.py. You do not need to copy concatdataset, you can directly use it with the same config.

Ok， I finally find my mistakes, I didn't use '_delete_=True' in configs' file.

**Comment by wjjjjyourFA** [comment]
please help me . how to solve it? I meet this : TypeError: __init__() got an unexpected keyword argument 'pipeline'


this is my `coco_detection.py`
`
train_dataloader = dict(
    batch_size=64,
    num_workers=10,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type='ConcatDataset',
        datasets=[
            dict(
                # type=dataset_type,
                type='CocoDataset',
                data_root=data_root,
                ann_file='macaquepose/annotations/macaque_train.json',
                data_prefix=dict(img='macaquepose/images/'),
                filter_cfg=dict(filter_empty_gt=True, min_size=32),
                # pipeline=train_pipeline,
                backend_args=backend_args
            ),
        ]
    ))
`
