### ISSUE TITLE
[Docs] Where do I find comprehensive list of available models?

### ISSUE THREAD

**Issue by decadenza** [open-mmlab/mmdetection#9504]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

I am looking for a comprehensive list of available parameters to be placed in the config file.
For example, the list of all the available model "type" and "backbones".

Reported example value for model type are `faster_rcnn` and `mask_rcnn`, but I don't seem to find a proper list in the documentation here https://mmdetection.readthedocs.io/en/latest/tutorials/config.html

d

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/model_zoo.md
