### ISSUE TITLE
[Docs] v26 mmdet.apis documentation is gone

### ISSUE THREAD

**Issue by Sylvexia** [open-mmlab/mmdetection#9506]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

The apis documentation is missing, we have to go back to last version to see something like how to "show_results" works.

### Suggest a potential alternative/fix

Copy and paste the missing parts from the last version, i guess.
[opinion: ]
Also the potentially if the document can specify what is the return detection result type may be, would make the documentation infinitely better.

**Comment by ZwwWayne** [comment]
Thanks for your report, we will fix the doc ASAP.

**Comment by ZwwWayne** [comment]
Resolved in the most recent mmdet.
