### ISSUE TITLE
[Reimplementation] module 'mmdet' has no attribute 'apis'

### ISSUE THREAD

**Issue by fourcake** [open-mmlab/mmdetection#9512]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

我的pip工具无法找到mmdet1.0rc1版本，在mmcv 1.0.5和mmdet 2.3的环境下运行mmskl.py的pose_demo报错，module 'mmdet' has no attribute 'apis'

My pip tool cannot find the mmdet1.0rc1 version. I run the pose_demo of mmskl.py in the environment of mmcv 1.0.5 and mmdet 2.3, and an error occurs: module 'mmdet' has no attribute 'apis'

### Environment

_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2022.10.11           h06a4308_0  
certifi                   2022.9.24        py37h06a4308_0  
cffi                      1.15.1           py37h5eee18b_3  
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cudatoolkit               9.2                           0  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
giflib                    5.2.1                h7b6447c_0  
idna                      3.4                      pypi_0    pypi
importlib-metadata        5.2.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jpeg                      9e                   h7f8727e_0  
kiwisolver                1.4.4                    pypi_0    pypi
lazy-import               0.2.2                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.8                  h7f8727e_5  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.4.0                hecacb30_2  
libwebp                   1.2.4                h11a3e52_0  
libwebp-base              1.2.4                h5eee18b_0  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.1                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
mmcv                      1.0.5                    pypi_0    pypi
mmdet                     2.3.0                    pypi_0    pypi
mmskeleton                0.7rc1+b4c076b            dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
nms                       0.0.0                     dev_0    <develop>
numpy                     1.21.5           py37h6c91a56_3  
numpy-base                1.21.5           py37ha15fc14_3  
opencv-python             4.6.0.66                 pypi_0    pypi
openmim                   0.3.3                    pypi_0    pypi
openssl                   1.1.1s               h7f8727e_0  
ordered-set               4.1.0                    pypi_0    pypi
packaging                 22.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pillow                    9.2.0            py37hace64e9_1  
pip                       22.3.1           py37h06a4308_0  
pycocotools               2.0.6                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.7.15               h7a1cb2a_1  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.2.0           py3.7_cuda9.2.148_cudnn7.6.2_0    pytorch
pytz                      2022.7                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.1                   pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.5.0           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.40.0               h5082296_0  
tabulate                  0.9.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torchvision               0.4.0                 py37_cu92    pytorch
typing-extensions         4.4.0                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.8                h5eee18b_0  
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.2                ha4553b6_0

**Comment by ZwwWayne** [comment]
You may set PYTHONPATH='.'$PYTHONPATH or pip install -e .
