### ISSUE TITLE
[Feature] best labeling method/ approach for instance segmentation. 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#9513]
### What's the feature?

Thank you for your effort and well organized 
such a wonderful and useful library for almost all deep neural network approaches is a great way to implement and do research in computer vision field. 

I am just interested to know if there is any automatically way to label (create ground truth) for my custom images in a form of instance segmentation.

either in form of coco or vascal 

thanks in advanced.

**Comment by ZwwWayne** [comment]
You can use a high-precision model to produce pseudo-labels, e.g., this one https://github.com/open-mmlab/mmdetection/tree/master/configs/htc#results-and-models
