### ISSUE TITLE
Regarding constant mAp values even after training for more epochs

### ISSUE THREAD

**Issue by JahnaviSatishShanbhag** [open-mmlab/mmdetection#9516]
I am using mmdetection framework to train the models. I used **faster_rcnn_r50_caffe_fpn_mstrain_90k_coco** for training. But even after 6-8 epochs the mAp (mean average precision) value is 48.5. In each epoch there are 6283 iterations. But at the same time when I trained the same model using detectron2 framework it gave 55 as mAp for only 20000 iterations. When I train more the mAp value is increasing also. But for mmdetection it wont cross more than 50. What is the issue?

![mmd](https://user-images.githubusercontent.com/71307702/208628584-19f08047-5458-4f88-aeb8-25273a3feddd.png)
![unnamed](https://user-images.githubusercontent.com/71307702/208628627-c33f9578-9062-4be5-b44c-7db8b18658c8.png)

**Comment by ZwwWayne** [comment]
What config did you use in detectron2? It might caused by the dataset format mismatch.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 15 days.
