### ISSUE TITLE
Any plans for rotating box or arbitrary quadrilateral box?

### ISSUE THREAD

**Issue by gfjiangly** [open-mmlab/mmdetection#952]
If the box format is not x1y1x2y2 or xywh, but x1y1x2y2x3y3x4y4, is there any plan support?

**Comment by hellock** [comment]
No recent plan yet, but community contribution is welcome.

**Comment by liushuchun** [comment]
You can transfer this poly style data to mask format,then you can get the last answer with cv2.minAreaRect.

**Comment by gfjiangly** [comment]
> You can convert this poly style data to mask format,then you can transfer th mask result to poly with cv2.minAreaRect.

Sounds like a good idea, your suggestion is very practical and useful. But sometimes, we might want to know the impact of different box forms on the results. I will try it. Thank you very much.

**Comment by jshilong** [comment]
The rotating box has been put to our recent plan.
