### ISSUE TITLE
[Feature]  When i use pretrained backbone , can i get missing keys or unexpected keys?

### ISSUE THREAD

**Issue by KimtaeHo3948** [open-mmlab/mmdetection#9521]
### What's the feature?

HI, thank you for great job 
i'm trying to use my own pretrained  backbone weight with maskrcnn
Here is my configure 
![스크린샷 2022-12-21 오후 5 10 37](https://user-images.githubusercontent.com/93563329/208853303-d5780c5f-08f1-4dd8-85c2-c442e5220dae.png)

as you see i build my own backbone which i call SelfPatch_ViT 

![스크린샷 2022-12-21 오후 5 03 34](https://user-images.githubusercontent.com/93563329/208853506-2de9af67-5e90-41ed-91c5-41b83780fa52.png)

when i run my config 
i got 
mmdet - info -load checkpoint form local path: ./dino_vissl.pth 

but i want to know every weights are loaded to model 
is there any way to i get message for this?
message like
Ex. missing keys = {...}
or unexpected keys = {....}

**Comment by ZwwWayne** [comment]
Yes, if there are mismatch of keys, they will show. Therefore, if you have not seen them yet, it means the keys are correctly loaded.
