### ISSUE TITLE
[Bug] Bug in analyze_results.py and browse_dataset.py

### ISSUE THREAD

**Issue by chhluo** [open-mmlab/mmdetection#9523]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

-

### Reproduces the problem - code sample

-

### Reproduces the problem - command or script

-

### Reproduces the problem - error message

-

### Additional information

analyze_results.py:

https://github.com/open-mmlab/mmdetection/blob/34462a1c358f369fec91d9a028bff3e3eeb8bd54/tools/analysis_tools/analyze_results.py#L155

-> `data_info['img'],`

browse_dataset.py:
should set `draw_pred=False` in https://github.com/open-mmlab/mmdetection/blob/34462a1c358f369fec91d9a028bff3e3eeb8bd54/tools/analysis_tools/browse_dataset.py#L77

**Comment by ZwwWayne** [comment]
Hi @chhluo ,
Thanks for your kind bug report, would you like to create a PR to fix it?

**Comment by chhluo** [comment]
These bugs were already fixed on branch dev-3.x.
