### ISSUE TITLE
Convention of bounding box for custom dataset

### ISSUE THREAD

**Issue by kirbiyik** [open-mmlab/mmdetection#954]
Is it (x1, y1, w, h) or (x1, y1, x2, y2) or else? Could not understand the convention from `'bboxes': <np.ndarray, float32> (n, 4)`

**Comment by hellock** [comment]
(x1, y1, x2, y2)

**Comment by boy977** [comment]
@hellock These are top left and bottom right, right?

**Comment by kirbiyik** [comment]
Yes.
