### ISSUE TITLE
Is AR calculated with proposals or final detections in COCO?

### ISSUE THREAD

**Issue by buncybunny** [open-mmlab/mmdetection#9571]
Hi guys,

Thanks a lot for the great work.

In COCO dataset, AP is calculated with at most top 100 highest score bboxes amongst final detected results(post-nms) based on what I've comprehended. (Let me know if I've misunderstood sth here)

In mmdetection, you guys give "proposals" option as --eval-options, and it seems to calculate AR of 100, 300, 1000 **proposals**. **Are they region proposals, not the final detected bboxes**?
**If so, how can I get AR with single-staged detectors like yolo or ssd as they don't have "proposals" in general.**

Looking forward to your answer.

**Comment by buncybunny** [comment]
My biggest wonder is the meaning of "proposal"( --eval) in one-stage detectors? I get different AR setting --eval as "bbox" and "proposal" in yolov3!

**Comment by RangiLyu** [comment]
For one stage model, the boxes used for calculating metrics are always the predicted boxes. There is no "proposal" for one-stage models. The meaning of  `--eval proposal` means using `'AR@100', 'AR@300', 'AR@1000', 'AR_s@1000', 'AR_m@1000', 'AR_l@1000'` as the `metric_items` and set `cocoEval.params.useCats = 0`(means ignore the categories of the boxes). You can refer to  https://github.com/open-mmlab/mmdetection/blob/94afcdc6aa1e2c849c9d8334ec7730bb52b17922/mmdet/datasets/coco.py#L509

**Comment by buncybunny** [comment]
Big thanks for the confirmation @RangiLyu!

I've checked the codes, but I still wonder why the reported AR values are different when `--eval bbox` and `--eval proposal`. According to what you said, shouldn't the numbers same as there are no "proposal"...? 

Does ignoring categories of the boxes causes the difference?

[results attained with --eval proposal]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/57431963/210946240-21888f57-ad17-4d71-89a2-e60460e94313.png">
[results attained with --eval bbox]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/57431963/210946563-d6146a2f-9fa6-416e-94a1-8cbeed031784.png">

I wonder what makes the difference between these two.
Thanks again!!

**Comment by RangiLyu** [comment]
> Does ignoring categories of the boxes causes the difference?

Yes.

**Comment by buncybunny** [comment]
Thanks a lot!!
