### ISSUE TITLE
How can I eval the model on the open category?

### ISSUE THREAD

**Issue by xishanhan** [open-mmlab/mmdetection#9572]
Hi, thank you for your excellent work. 
I splited the categories of COCO into 48 seen categories and 17 unseen categories (I use https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/001.ipynb to split the COCO dataset), and trained the faster rcnn model with the seen categories, then wanted to eval it on the unseen categories. 
When I trained the model, I modified the 'CLASSES' in 'mmdet/dataset/coco.py' to 48 seen categories, and I also modified the 'coco_classes return' in 'mmdet/core/evaluation/class_name.py' to 48 seen categories. Meanwhile, I set the ‘num_classes’ in the config to 48.
However, when I tried to eval the model on 17 unseen categories, I got this error：
Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 216, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/xsh/youtu_pedestrian_detection/object_localization_network/mmdet/datasets/coco.py", line 437, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/xsh/youtu_pedestrian_detection/object_localization_network/mmdet/datasets/coco.py", line 382, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/xsh/youtu_pedestrian_detection/object_localization_network/mmdet/datasets/coco.py", line 314, in results2json
    json_results = self._det2json(results)
  File "/home/xsh/youtu_pedestrian_detection/object_localization_network/mmdet/datasets/coco.py", line 251, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range
So, I want to know how to modify the config so that the model can be eval on the unseen categroies. Looking forward to your reply.

**Comment by RangiLyu** [comment]
Sorry, MMDetection currently does not support open vocabulary object detection tasks.

**Comment by xishanhan** [comment]
> For open-vocabulary testing, the number of classes in training and testing is different. You should use another class embeddings in tests and test on the dataset of 17 classes. You may refer to [DetPro](https://github.com/dyabel/detpro) for more details.

I see, what you mean is that I need to rewrite the test code, just like DetPro, right?

**Comment by xishanhan** [comment]
> For open-vocabulary testing, the number of classes in training and testing is different. You should use another class embeddings in tests and test on the dataset of 17 classes. You may refer to [DetPro](https://github.com/dyabel/detpro) for more details.

I now have the splited unseen coco ann format json and I want to use it directly for testing, how can I do it？

> For open-vocabulary testing, the number of classes in training and testing is different. You should use another class embeddings in tests and test on the dataset of 17 classes. You may refer to [DetPro](https://github.com/dyabel/detpro) for more details.



> For open-vocabulary testing, the number of classes in training and testing is different. You should use another class embeddings in tests and test on the dataset of 17 classes. You may refer to [DetPro](https://github.com/dyabel/detpro) for more details.

Sorry, I have not read the DetPro paper, do you know which py file specifically modified the test code in DetPro?

**Comment by xishanhan** [comment]
> For open-vocabulary testing, the number of classes in training and testing is different. You should use another class embeddings in tests and test on the dataset of 17 classes. You may refer to [DetPro](https://github.com/dyabel/detpro) for more details.

Sorry, I have not read the DetPro paper, do you know which py file specifically modified the test code in DetPro?

**Comment by corkiyao** [comment]
> Sorry, MMDetection currently does not support open vocabulary object detection tasks.

Have it supported? Looking for your reply.
