### ISSUE TITLE
How to get class probabilities for each detection

### ISSUE THREAD

**Issue by Rizhiy** [open-mmlab/mmdetection#958]
The api shown in `GETTING_STARTED` gives instructions on how to get final detections from a model.
These detections already pick the highest probability class for each detection.

Is there an easy way to get the predictions for each class for each detection?

**Comment by hellock** [comment]
You may dive into the testing method to get the class probabilities. See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/bbox_heads/bbox_head.py#L141) for details.

**Comment by Seiano** [comment]
when i click this 'here', the page is lost (404). can you help me where can i  looking for  the answere?  thanks!
