### ISSUE TITLE
numpy version error when install mmdet3d v0.17.1

### ISSUE THREAD

**Issue by 18lalala** [open-mmlab/mmdetection#9580]
I am using a model based on mmdet3d v0.17.1, but I meet an error when installing it
log:
Installed /home/puzek/anaconda3/envs/bevformer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg
Processing dependencies for mmdet3d==0.17.1
error: numpy 1.19.5 is installed but numpy>=1.20.3 is required by {'pandas'}

and my numpy version is 1.23.5

**Comment by BIGWangYuDong** [comment]
Hi, maybe you can check your pip list to check your numpy version. Haven't met this error before

**Comment by Gebixiaochen** [comment]
@BIGWangYuDong I met the same error as @18lalala . pip list and conda list shows the same version of numpy 1.19.5. But still reporting this error while running python setup.py install under mmdetection3d project.

**Comment by myteen2** [comment]
@BIGWangYuDong I also encountered the same error as @18lalala. 
I tried uninstall and install numpy according to the error message several times but I wasn't able to make it. 
At first, it wants numpy 1.19.5 so I downgraded it to 1.19.5 but then it wants numpy >=1.20.x. 
How can I resolve the conflict?

**Comment by BIGWangYuDong** [comment]
would you mind giving use your install command? Maybe the version of `pandas` does not match, try to down-grad your pandas version

**Comment by sujayb-nd** [comment]
Same issue

**Comment by sujaybabruwad** [comment]
I have the same issue. Has anyone got a fix for this issue with numpy version.

**Comment by weixi234** [comment]
error: numpy 1.19.5 is installed but numpy>=1.21 is required by {'plyfile'}

**Comment by jysh1214** [comment]
My solution:

1. Remove this egg in your PYTHONPATH:
```
numpy-1.19.5-py3.9-linux-x86_64.egg
```

2. Reinstall `numpy`:
```
pip uninstall numpy
pip install numpy>=1.21
```

3. Build mmdet3d without installing:
```
python setup.py build
```

4. Install mmdet3d without dependencies:
```
pip install --no-deps .
```

**Comment by ccblublu** [comment]
> error: numpy 1.19.5 is installed but numpy>=1.21 is required by {'plyfile'}

just downgrade plyfile==1.0.3
