### ISSUE TITLE
[Feature] Will VIT be supported？

### ISSUE THREAD

**Issue by majintao1994** [open-mmlab/mmdetection#9582]
### What's the feature?

Do you plan to support the vit model？

### Any other context?

Do you plan to support the vit model？

**Comment by BIGWangYuDong** [comment]
We are planning to support the VIT model.

**Comment by majintao1994** [comment]
Is it convenient to disclose the approximate time？

**Comment by BIGWangYuDong** [comment]
We are supporting ViTDet now. Will release soon
