### ISSUE TITLE
[Feature] Cross-platform deployment capability

### ISSUE THREAD

**Issue by leemayi** [open-mmlab/mmdetection#9585]
### What's the feature?

1）start a train on a linux machine
2）export the onnx model on a linux machine
3）infer on a window machine. you can export the trt model directly without installing the python environment.
Just like paddlepaddle‘s deployment

**Comment by BIGWangYuDong** [comment]
We give some documents for users, such as https://github.com/open-mmlab/mmdetection/blob/3.x/docs/en/user_guides/deploy.md

**Comment by leemayi** [comment]
> We give some documents for users, such as https://github.com/open-mmlab/mmdetection/blob/3.x/docs/en/user_guides/deploy.md

I know that, but we must install the python environment on Windows and export the model. I don't think this way is very convenient

**Comment by hhaAndroid** [comment]
@leemayi Deployment support is currently implemented via mmdeploy,  you can ask in the mmdeploy repo
