### ISSUE TITLE
CPU infer error

### ISSUE THREAD

**Issue by TheodoreG** [open-mmlab/mmdetection#959]
Hi, I use infer code in High-level APIs in GETTING_STARTED.md, and I changed device from 'cuda:0' to 'cpu' in 'init_detector' function.

But I got following error:
```
in delta2bbox
    gw = pw * dw.exp()
RuntimeError: expected backend CUDA and dtype Float but got backend CPU and dtype Float
```
Could you please help me ?

**Comment by LiChenyang-Github** [comment]
Hi, have you solved this problem? I met the same problem.

**Comment by wduo** [comment]
Hi, have you solved this problem? I met the same problem.
