### ISSUE TITLE
confusion matrix got the background FP: 100% TP0%

### ISSUE THREAD

**Issue by MARUIHAN123** [open-mmlab/mmdetection#9592]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

TorchVision: 0.9.1+cu101
OpenCV: 4.6.0
MMCV: 1.7.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.26.0+e4bf27c

### Reproduces the problem - code sample

i run the python tools/analysis_tools/confusion_matrix.py 

### Reproduces the problem - command or script

python tools/analysis_tools/confusion_matrix.py \ 
${CONFIG}  \ 
${DETECTION_RESULTS} \ 
${SAVE_DIR} \ 
--show 

### Reproduces the problem - error message

no erroe message

### Additional information

1. I only have one class in my dataset

**Comment by Holsonn** [comment]
@MARUIHAN123 I have the same problem. Please tell me how to fix it If you know. Thanks!
