### ISSUE TITLE
Any idea when the PAFPN neck will be released?

### ISSUE THREAD

**Issue by CrazySherman** [open-mmlab/mmdetection#96]
Just curious otherwise I can submit a PR myself on this.

**Comment by iceload123** [comment]
> Just curious otherwise I can submit a PR myself on this.

Do you achieve better results using Path Aggregation Network?
I also tried expect for adaptive ROI pooling, but got no gains on r50 baseline.

**Comment by hellock** [comment]
Sorry for the delay and our team is now busy with the CVPR deadline. We will release PAFPN as well as some other components (RetinaNet, Cascade R-CNN, etc.) after CVPR.

For the performance issue, we may need to seek help from the authors. Btw, the authors released an official [repo](https://github.com/ShuLiu1993/PANet) of PANet, which uses GroupNorm and achieves better performance.

**Comment by nemonameless** [comment]
@iceload123 @CrazySherman @hellock Have you reproduce the results of PANet on mmdetection ? 
It seems PAFPN  only bring 0.1 gain on bbox AP and mask AP,  how about your codes?  how much gain can PAFPN and  adaptive ROI pooling  bring respectively?

**Comment by cqliheping** [comment]
Any updates or any ideas about the performance of pafpn?
recently, I test the pafpn in my code, but get 0.1~0.2 gain on bbox, It confused me.
I noticed that, the resolution of the test image is bigger than usual, which is 1000 as the smaller input.

**Comment by engharat** [comment]
Hi, could anyone provide the pafpn implementation for mmdetection? I'm not able to find it on the official repo. thanks!

**Comment by ggjy** [comment]
@cqliheping I try to reproduce the PANet, but I get on gain on Faster RCNN. I add the bottom up path, 3x3 conv w/ GN, but still get on gain.

**Comment by ZwwWayne** [comment]
Already support PAFPN after https://github.com/open-mmlab/mmdetection/pull/2392.
