### ISSUE TITLE
when to save the ckpt

### ISSUE THREAD

**Issue by lazerliu** [open-mmlab/mmdetection#960]
Hello.A whole epoch is too too long,and if the dataset is pretty large ,the model's perfomance may change with a wide range,but I always just want the best or nearly best one.
So ,can I set when to save the model on my own in "xxxconfig.py" .Thks.

**Comment by hellock** [comment]
You can write your own checkpoint hook instead of using the [default one](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py#L5) which saves at the end of epochs.

**Comment by lazerliu** [comment]
> You can write your own checkpoint hook instead of using the [default one](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py#L5) which saves at the end of epochs.

soga,thank you!

**Comment by CamilleMaurice** [comment]
@lazerliu I'm interested to save only the best model, did you manage to save only the best model ?
