### ISSUE TITLE
[Bug] Case sensitivity bug in mmdet_handler

### ISSUE THREAD

**Issue by sanbuphy** [open-mmlab/mmdetection#9608]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

Latest dev-3.x branch

### Reproduces the problem - code sample

I use this to run the mmdet-server:
![image](https://user-images.githubusercontent.com/96160062/211564315-1dd289b2-c891-418a-8a48-79927f7eb5f4.png)
![image](https://user-images.githubusercontent.com/96160062/211564330-0bdd38e6-9c2f-48cd-b249-665e03e357c6.png)

### Reproduces the problem - command or script

pass

### Reproduces the problem - error message

![微信图片_20230110205501](https://user-images.githubusercontent.com/96160062/211564699-b2be2ca0-6f46-45d8-8b9e-8298b2cd9083.jpg)

### Additional information

but when i open the mmdet_handler.py in my mmdet. It looks good, and the dockerfile  version is also correct.
![微信图片_20230110205507](https://user-images.githubusercontent.com/96160062/211558267-151abd0c-5703-43a7-9541-f3cdaeaf021e.jpg)
![微信图片_20230110205512](https://user-images.githubusercontent.com/96160062/211558272-a17b949a-12fd-4122-9951-3e240e5abc14.jpg)

**Comment by hhaAndroid** [comment]
@sanbuphy Hi. Is it resolved now?

**Comment by sanbuphy** [comment]
> @sanbuphy Hi. Is it resolved now?
Yes, I solved all the problems, The reason may be that some resources have not been refreshed.
