### ISSUE TITLE
[Feature] When will feature 'auto_scale_lr' be available in master

### ISSUE THREAD

**Issue by 330205812** [open-mmlab/mmdetection#9617]
### What's the feature?

https://github.com/open-mmlab/mmdetection/pull/7482
We want to use the new 'auto_scale_lr' feature.
May I ask when this feature will be open?

**Comment by RangiLyu** [comment]
This feature has been merged into master https://github.com/open-mmlab/mmdetection/blob/94afcdc6aa1e2c849c9d8334ec7730bb52b17922/tools/train.py#L90

**Comment by Li-Qingyun** [comment]
@330205812  For example: when you want to run with a provided config, such as [detr_r50_8x2_150e_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/detr/detr_r50_8x2_150e_coco.py).
see the `8x2` in config file name, which means the model uses 8 GPUs and 2 samples_per_gpu. Total batch size is 16.

But if there is more or less GPUs in your experiment platform, or the memory of your GPU is limited, i.e., you can not ensure that the total batch size is still 16. The lr need to be scaled then. For example, if total batch size is 8, the lr should mult 0.5.

The `--auto-scale-lr` can be opened then, to auto scale the lr.
