### ISSUE TITLE
semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown

### ISSUE THREAD

**Issue by GYxiaOH** [open-mmlab/mmdetection#962]
my system is pytorch 1.1 + nvidia 418.67 + cuda 10.1 + Tesla V100
when i train, it will show:
"semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown"
what can i do for the problem?

**Comment by GYxiaOH** [comment]
I know the reson. because of version of gcc, when i change 4.85 to 5.3. the problem disappear

**Comment by zzapzzap** [comment]
@GYxiaOH 
Excuse me, did you solve this problem by changing simply version 4.85 to 5.3?
I got this problem too, but My gcc ver is 7.5.
