### ISSUE TITLE
[Bug] The project in mmdetection was written as a simple program and packaged into exe by pyinstaller. The program could run normally before packaging, and error was reported after the packaging into exe.

### ISSUE THREAD

**Issue by aibohang** [open-mmlab/mmdetection#9622]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

I packaged image_demo.py in mmdetection into exe. The test could run normally before packaging, but an error was reported after packaging.
![1](https://user-images.githubusercontent.com/45119898/212011633-e5b288ab-128e-4e90-a2a3-7be6eed1458f.png)

### Reproduces the problem - code sample

# Copyright (c) OpenMMLab. All rights reserved.
import asyncio
from argparse import ArgumentParser

from mmdet.apis import (async_inference_detector, inference_detector,
                        init_detector, show_result_pyplot)

def parse_args():
    parser = ArgumentParser()
    parser.add_argument('--img', help='Image file',default='./test_imgs/demos.jpg')
    parser.add_argument('--config', help='Config file',default='./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py')
    parser.add_argument('--checkpoint', help='Checkpoint file',default='./weight/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth')
    parser.add_argument('--out-file', default=None, help='Path to output file')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument(
        '--palette',
        default='coco',
        choices=['coco', 'voc', 'citys', 'random'],
        help='Color palette used for visualization')
    parser.add_argument(
        '--score-thr', type=float, default=0.3, help='bbox score threshold')
    parser.add_argument(
        '--async-test',
        action='store_true',
        help='whether to set async options for async inference.')
    args = parser.parse_args()
    return args

def main(args):
    # build the model from a config file and a checkpoint file
    model = init_detector(args.config, args.checkpoint, device=args.device)
    # test a single image
    result = inference_detector(model, args.img)
    # show the results
    show_result_pyplot(
        model,
        args.img,
        result,
        palette=args.palette,
        score_thr=args.score_thr,
        out_file=args.out_file)

async def async_main(args):
    # build the model from a config file and a checkpoint file
    model = init_detector(args.config, args.checkpoint, device=args.device)
    # test a single image
    tasks = asyncio.create_task(async_inference_detector(model, args.img))
    result = await asyncio.gather(tasks)
    # show the results
    show_result_pyplot(
        model,
        args.img,
        result[0],
        palette=args.palette,
        score_thr=args.score_thr,
        out_file=args.out_file)

if __name__ == '__main__':
    args = parse_args()
    if args.async_test:
        asyncio.run(async_main(args))
    else:
        main(args)

### Reproduces the problem - command or script

Package the image_demo.py as an exe using pyinstaller

### Reproduces the problem - error message

![1](https://user-images.githubusercontent.com/45119898/212012199-ca61bbc1-87b3-4bae-8813-46557bb465d2.png)

**Comment by RangiLyu** [comment]
The reason seems to be that the mmdetection can not be recognized as a python package after you pack it with pyinstaller.

One solution is to set the scope for the registry manually.
For example, modify the mmdet/models/builder.py
```
MODELS = Registry('models',
                  build_func=build_model_from_cfg,
                  parent=MMCV_MODELS,
                  scope='mmdet')
```
and maybe you need to modify all of the registries.

**Comment by aibohang** [comment]
Hello, I modified 
**MODELS = Registry('models',
                  build_func=build_model_from_cfg,
                  parent=MMCV_MODELS,
                  scope='mmdet')**
 in file mmdet/models/builder.py according to your prompt, but still reported the same error after packaging, may I ask what **and maybe you need to modify all of the registries.** needs to modify? I only found **MODELS = Registry('models', parent=MMCV_MODELS)** in mmdet/models/builder.py in the whole project?
![image](https://user-images.githubusercontent.com/45119898/212034370-37a23d71-a5f2-453d-b895-60a68cacb6f0.png)

**Comment by RangiLyu** [comment]
> what **and maybe you need to modify all of the registries.** needs to modify?

You may need to add `scope='mmdet'` to all the registries in the project. Please global search the "Registry". There are also dataset registry, anchor generator registry, etc.

**Comment by RangiLyu** [comment]
BTW, could you also report this issue to MMCV? Modifying the registry is just a workaround for now.
