### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by chenjw1009** [open-mmlab/mmdetection#9623]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

mask2former pytorch需要什么版本，我的是1.7.0 ,CUDA11.4
总报错 CUDA error: an illegal memory access was encountered

### Reproduces the problem - code sample

NO

### Reproduces the problem - command or script

NO

### Reproduces the problem - error message

NO 

### Additional information

NO

**Comment by RangiLyu** [comment]
Please provide more information. Illegal memory access maybe caused by many different reasons. One common reason is the number of classes is incorrect when you train your own dataset.
