### ISSUE TITLE
Log config file during training into work_dir

### ISSUE THREAD

**Issue by yl1991** [open-mmlab/mmdetection#963]
**Describe the feature**
Log the configs used for the experiment or simply just copy the config file into work_dir.

**Motivation**
When running different experiments with different configs, it is better to log the config for the specific experiment. This way we can track the parameters we have changed. It would be very helpful for those who forgot to note down the difference in the configs before training.

**Comment by hellock** [comment]
Configs are saved in the checkpoints. For each checkpoint we can track the config in its meta data.
