### ISSUE TITLE
How to train a new model on the original images and cropped images?

### ISSUE THREAD

**Issue by marsggbo** [open-mmlab/mmdetection#964]
**Describe the feature**

**Motivation**
For some dataset, the object is only a small part of the whole image, so it would be useful to train a classifier model on  the original images and cropped images. In some degree, the classifier can learn global and local features.

**Comment by hellock** [comment]
There is no out-of-the-box implementation, but you may refer to the augmentation of SSD, which adopts crop training.
We are considering making it plug and play, but it may take some time.

**Comment by marsggbo** [comment]
@hellock Thanks for your reply. I didn't find the related code of augmentation of SSD, can you tell me where the code is?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L595
