### ISSUE TITLE
[Bug] 'DetDataPreprocessor is not in the model registry.

### ISSUE THREAD

**Issue by bblumberg** [open-mmlab/mmdetection#9640]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: linux
Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Orin
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.4, V11.4.239
GCC: aarch64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 11.4
  - NVCC architecture flags: -gencode;arch=compute_72,code=sm_72;-gencode;arch=compute_87,code=sm_87
  - CuDNN 8.3.2
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CUDA_VERSION=11.4, CUDNN_VERSION=8.3.2, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=open, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0a0+9b5a3fe
OpenCV: 4.5.5
MMEngine: 0.4.0
MMDetection: 3.0.0rc5+

### Reproduces the problem - code sample

I was using the inference example code and got the error. I also got the error doing the demonstration code:
python demo/image_demo.py demo/demo.jpg yolov3_mobilenetv2_8xb24-320-300e_coco.py yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth --device cpu --out-file result.jpg

### Reproduces the problem - command or script

python demo/image_demo.py demo/demo.jpg yolov3_mobilenetv2_8xb24-320-300e_coco.py yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth --device cpu --out-file result.jpg

### Reproduces the problem - error message

python3 mmdetect/inference_v3.py 
01/16 22:33:50 - mmengine - WARNING - The "model" registry in mmdet did not set import location. Fallback to call `mmdet.utils.register_all_modules` instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mmdetection/mmdet/models/detectors/rtmdet.py", line 40, in __init__
    super().__init__(
  File "/mmdetection/mmdet/models/detectors/single_stage.py", line 28, in __init__
    super().__init__(
  File "/mmdetection/mmdet/models/detectors/base.py", line 31, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 78, in __init__
    self.data_preprocessor = MODELS.build(data_preprocessor)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 240, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DetDataPreprocessor is not in the model registry. Please check whether the value of `DetDataPreprocessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmdetect/inference_v3.py", line 18, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "/mmdetection/mmdet/apis/inference.py", line 57, in init_detector
    model = MODELS.build(config.model)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 240, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `RTMDet` in mmdet/models/detectors/rtmdet.py: 'DetDataPreprocessor is not in the model registry. Please check whether the value of `DetDataPreprocessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

### Additional information

I am installing mmdetection via best practices in a docker container that uses the same RUN as in the docker file. I have been able to successfully train and test models in v3, so it is only when I try to run the inference scripts that I run into problems. Any help would be greatly appreciated. Thanks.

**Comment by bblumberg** [comment]
Sorry, this was my issue: I added /mmdetection to my PYTHONPATH, and this must have interferred with the initialization. I am good to go. Thanks

**Comment by andrewcaunes** [comment]
Hello, I am encountering the same issue, can you explain more precisely what caused it and how you fixed it please ?

**Comment by bblumberg** [comment]
Hi

In my case, I followed the best practices and was doing this in my
dockerfile. The net result is that mmdetection is cloned into
/mmdetection in my container. I also thought that I needed to add
/mmdetection to my PYTHONPATH (e.g. export
PYTHONPATH=$PYTHONPATH:/mmdetection:...) , and immediately ran into this
issue. As it turned out, adding /mmdetection to PYTHONPATH was the cause of
the issue, because once I removed /mmdetection from PYTHONPATH, the problem
disappeared. In retrospect this makes sense since it felt like a pathing
issue all along, and the normal install does put files in the standard
python places.

Hope that helps.

**Comment by andrewcaunes** [comment]
Alright thank you for your answer !
I still feel weird about this since in my case (see https://github.com/open-mmlab/mmdetection/issues/9719) I also followed best practice and did not change anything about my PYTHONPATH. I also cloned mmdetection to my project but I don't think this should be an issue.
Following your comment, I tried to reproduce the issue in an IPython terminal but ever when removing /mmdetection from my sys.path the issue remains. Furthermore, I tried doing this process again but this time not even cloning /mmdetection (by only "running mim install mmdet" to get mmdet as a third party package, but the issue remained, so the issue shouldn't come from this path problem in my opinion.

I am currently trying to debug the issue by following the thread inside mmengine.
Thanks for your help !

**Comment by bblumberg** [comment]
It will be interesting to find out what you learn because it may that I
will run into the same problem again the moment I change my configuration.

It is odd because no one else had reported it and it is so basic, which did
lead me to think that it was a configuration issue of some sort. For what
it is worth, I am running it in a docker container on the agx_orin using
nvidia's pytorch container as the base.

Do let me know what you find out. I will say once I got past this issue, I
have been quite pleased with the system. So it is worth figuring out.

bb

**Comment by andrewcaunes** [comment]
Hey again, I have solved my issue !

Here is the answer : https://github.com/open-mmlab/mmdetection/issues/9719

The whole thing can be fixed by adding this to you inference script :
`from mmdet.utils import register_all_modules`
`register_all_modules()`

I explain some of what I understoor in the issue above, it's a problem of modules not being registered in mmengine MODELS registry (because they are in the mmdet MODELS registry) but the data preprocessors are initialized in mmengine scope so they are not found. I think this is an actual issue that could be fixed by using mmengine registry methods to search in the children of the MODELS registry in mmengine which contains the mmdet MODELS registry.

Anyway thank you very much for you help !

**Comment by bblumberg** [comment]
Cool. That seems like the right answer. So, thanks for your help as well.
Good luck!

bb

**Comment by k1dDing** [comment]
> Hey again, I have solved my issue !
> 
> Here is the answer : [#9719 (comment)](https://github.com/open-mmlab/mmdetection/issues/9719#issuecomment-1416100180)
> 
> The whole thing can be fixed by adding this to you inference script : `from mmdet.utils import register_all_modules` `register_all_modules()`
> 
> I explain some of what I understood in the issue above, it's a problem of modules not being registered in mmengine MODELS registry (because they are in the mmdet MODELS registry) but the data preprocessors are initialized in mmengine scope so they are not found. I think this is an actual issue that could be fixed by using mmengine registry methods to search in the children of the MODELS registry in mmengine which contains the mmdet MODELS registry.
> 
> Anyway thank you very much for you help !

Hi bro,I have met a similar registry issue but a little different.This is my key error.
KeyError: 'DetLocalVisualizer is not in the visualizer registry. Please check whether the value of `DetLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'.

**Comment by mac10-ai** [comment]
KeyError: 'RVSA_MTP is not in the opencd::model registry. Please check whether the value of `RVSA_MTP` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

solve this issue

**Comment by mac10-ai** [comment]
vis_backends = [
    dict(type='CDLocalVisBackend'),
]
visualizer = dict(
    alpha=1.0,
    name='visualizer',
    type='CDLocalVisualizer',
    vis_backends=[
        dict(type='CDLocalVisBackend'),
    ])
work_dir = '/content/drive/MyDrive/CD_Detection/OpenCD/BiT/LEVIR-CD_1st_time/Train_Workdir/'

Traceback (most recent call last):
  File "/content/open-cd/tools/train.py", line 104, in <module>
    main()
  File "/content/open-cd/tools/train.py", line 93, in main
    runner = Runner.from_cfg(cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/content/open-cd/opencd/models/change_detectors/siamencoder_decoder.py", line 94, in __init__
    self.backbone = MODELS.build(backbone)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
    KeyError: 'RVSA_MTP is not in the opencd::model registry. Please check whether the value of `RVSA_MTP` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
