### ISSUE TITLE
when I train ga-faster-rcnn-resnext101-32x4_fpn.py，I encounter out of memory

### ISSUE THREAD

**Issue by gittigxuy** [open-mmlab/mmdetection#965]
I already fix batch_size =1,and I call 2 1080ti gpus,but still out of memory.However,when I use single gpu,it just cost about 5GB memory.

my distrbute train command is:
CUDA_VISIBLE_DIVICES=0,2 ./tools/dist_train.sh ./configs/guided_anchoring/ga_faster_x101_32x4d_fpn_1x.py 2

how to fix this out of memory problem?

**Comment by hellock** [comment]
You mean memory or GPU memory? GPU memory should not increase with the number of GPUs.
