### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by Anurich** [open-mmlab/mmdetection#9658]
I am trying to run yolox with the coco dataset, when I call the train_detector I get an error as shown below:
`RecursionError: maximum recursion depth exceeded in comparison`
Does anyone, have an idea how we can resolve it?

**Comment by ZwwWayne** [comment]
Hi @Anurich ,
Could you follow the issue template to provide more details? For example, which mmdet version do you use?

**Comment by saadyousuf45** [comment]
anny progess on this

**Comment by Coronal-Halo** [comment]
I also had this problem, did anyone come up with a fix? I got this error trying to install mmdet 2.21 after running command "mim install mmdet==2.21"

**Comment by jerryjifjsdbf** [comment]
I have the same problem. Have you solved it? Can you teach me how to do it
