### ISSUE TITLE
how to ued the specified GPU train the model

### ISSUE THREAD

**Issue by aakunkun** [open-mmlab/mmdetection#966]
the gpu id is 0,1,2,3,4,5,6,7 , I ues the CUDA_VISIBLE_DEVICES=4,5,6,7 , but it doesn't work , it still ues the 0,1,2,3

**Comment by hellock** [comment]
Please use the `Error report` issue template.

**Comment by aakunkun** [comment]
thank you！I have solved the problem




| |
zekun0227
邮箱：zekun0227@163.com
|

Signature is customized by Netease Mail Master

On 07/11/2019 15:53, Kai Chen wrote:

Please use the Error report issue template.

**Comment by taoyang1122** [comment]
Hi, how do you solver the problem, I got the same issue.
