### ISSUE TITLE
How to train YOLOX with DarkNet53 ?[Reimplementation] 

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#9665]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I want to train YOLOX with DarkNet53. But I only find YOLOX-s, YOLOX-m, YOLOX-l and YOLOX-x.

### Environment

This is not important

**Comment by RangiLyu** [comment]
You can replace the backbone config with this:
```python
    backbone=dict(
        type='Darknet',
        depth=53,
        out_indices=(3, 4, 5),
        init_cfg=dict(type='Pretrained', checkpoint='open-mmlab://darknet53')),
```

**Comment by Icecream-blue-sky** [comment]
> You can replace the backbone config with this:
> 
> ```python
>     backbone=dict(
>         type='Darknet',
>         depth=53,
>         out_indices=(3, 4, 5),
>         init_cfg=dict(type='Pretrained', checkpoint='open-mmlab://darknet53')),
> ```

Got it ! Thanks !
