### ISSUE TITLE
mmcv._ext vs numpy.ufunc "Expected 192, got 216"

### ISSUE THREAD

**Issue by ggjy** [open-mmlab/mmdetection#968]
My numpy.__version__ is 1.16.4, the latest, but I find that every first time I run the test.py, the "version conflict" occurs, it seems that in my local environment, if  the "numpy.ufunc" occurs, I can just re-run (python test.py) to fix the error. But when I run the code in CLOUD, I can't re-run the code and fix the error (through methods like uninstall numpy; install numpy). Do you come across this issue? 

Traceback (most recent call last):
  File "mmdetection-master/test.py", line 47, in <module>
    from mmdet.apis import init_dist
  File "/home/work/user-job-dir/mmdetection-master/mmdet/apis/__init__.py", line 1, in <module>
    from .env import init_dist, get_root_logger, set_random_seed
  File "/home/work/user-job-dir/mmdetection-master/mmdet/apis/env.py", line 10, in <module>
    from mmcv.runner import get_dist_info
  File "/home/work/anaconda3/lib/python3.6/site-packages/mmcv/__init__.py", line 7, in <module>
    from .video import *
  File "/home/work/anaconda3/lib/python3.6/site-packages/mmcv/video/__init__.py", line 3, in <module>
    from .optflow import (flowread, flowwrite, quantize_flow,
  File "/home/work/anaconda3/lib/python3.6/site-packages/mmcv/video/optflow.py", line 6, in <module>
    from mmcv._ext import flow_warp_c
  File "__init__.pxd", line 872, in init mmcv._ext
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

**Comment by FishLikeApple** [comment]
I'm dealing with this too, it's weird that the function inference_detector used to be without any problem, but now it will run into the same problem as yours regardless of updating some packages like numpy.

**Comment by zhaopf1991** [comment]
i almost died for this question, waste me many many time and it's still there.

**Comment by ggjy** [comment]
It seems that numpy==1.15.0 can fix this. (Numpy==1.16.4 will incur this situation for me.)

**Comment by mosheliv** [comment]
The tricky part is that numpy can have multiple installations, so remove
numpy untill nothing happens and tgen install the right version

**Comment by olzhaskabdolov** [comment]
Do You have news on that? I am experiencing the same when trying to use mmdet on V100 GPUS. I have already tried different versions of Numpy.

**Comment by FishLikeApple** [comment]
I'm not sure my experience will help. I tried to use another python file to download and install modules and then run the main file by os.system("python main.py"), and it worked.
