### ISSUE TITLE
[Reimplementation] 

### ISSUE THREAD

**Issue by saadyousuf45** [open-mmlab/mmdetection#9684]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

Still trying to run SSD, tried different variations and settings over the months.
still getting the same error.
[SSD_training.e6640649.txt](https://github.com/open-mmlab/mmdetection/files/10529348/SSD_training.e6640649.txt)
[SSD_training.o6640649.txt](https://github.com/open-mmlab/mmdetection/files/10529349/SSD_training.o6640649.txt)
[SSD_HPC.py.txt](https://github.com/open-mmlab/mmdetection/files/10529351/SSD_HPC.py.txt)

Please advise what could be the issue?

### Environment

Using a singularity docker module.

### Expected results

training goes to Nan after a few iterations.

### Additional information

I have attached all files. Seriously have sent hours and hours debugging this code.
I cannot understand what could be the issue.

Is it possible to ignore a couple of Nan epoch runs (or increase it to by 10 epochs so that the training doesn't stop?)

**Comment by ZwwWayne** [comment]
Please see the notes in our doc https://mmdetection.readthedocs.io/en/latest/faq.html#training.

**Comment by saadyousuf45** [comment]
Hi thanks,
I have solved this issue.

Used this code.
https://github.com/open-mmlab/mmdetection/issues/3013#issuecomment-686416477
I would recommend this to everyone.
