### ISSUE TITLE
about “CHECKPOINT_FILE”

### ISSUE THREAD

**Issue by Curry1201** [open-mmlab/mmdetection#97]
I am sorry to ask such a low-level question, but for the time being I can't find someone who can help me solve this problem.
I just installed mmdetection according to your tutorial (README.md). When I was excited to try to run the code "python tools/test.py <CONFIG_FILE> <CHECKPOINT_FILE> --gpus <GPU_NUM> --out <OUT_FILE>" , I understand that <CONFIG_FILE> is xx.py under the folder 'configs', but i am not clear what should be entered in <CHECKPOINT_FILE> in the line of code that is running. Moreover, is <OUT_FILE> that I can name myself? Must this file be a .pkl file?

**Comment by hejiaget** [comment]
Your trained model file. xxx.pth

**Comment by Curry1201** [comment]
@hejiaget Thank you for your reply. I am sorry to see your message now. Besides, you turn me on.
