### ISSUE TITLE
mim install "mmdet>=3.0.0rc5,<3.1.0"报错 

### ISSUE THREAD

**Issue by yaofanji** [open-mmlab/mmdetection#9704]
Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
Looking in links: https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html
ERROR: Could not find a version that satisfies the requirement mmdet>=3.0.0rc5 (from versions: 0.6.0, 0.6.1, 0.6.2, 1.0rc2, 1.0rc3, 1.0rc4, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.10.0, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.15.1, 2.16.0, 2.17.0, 2.18.0, 2.18.1, 2.19.0, 2.19.1, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.24.1, 2.25.0, 2.25.1, 2.25.2, 2.25.3, 2.26.0, 3.0.0rc0, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc4)
ERROR: No matching distribution found for mmdet>=3.0.0rc5

**Comment by RangiLyu** [comment]
It seems that Huawei cloud hasn't synchronized the latest pypi. https://pypi.org/project/mmdet/3.0.0rc5/
