### ISSUE TITLE
python setup.py install error

### ISSUE THREAD

**Issue by ouguozhen** [open-mmlab/mmdetection#971]
when i run "python setup.py install" command in in my company's internal network, i got the issue that "distutils.DistutilsError：could not find suitable distribution for requirement.parse('pytest-runner'), is any offline way to setup the mmdetection?

**Comment by hellock** [comment]
You may try removing the [line](https://github.com/open-mmlab/mmdetection/blob/master/setup.py#L106).

**Comment by Weizhen-Fang** [comment]
Have u installed mmcv ?
