### ISSUE TITLE
[RuntimeError: CUDA error: an illegal memory access was encountered] in Azure ML

### ISSUE THREAD

**Issue by narencarbynetech** [open-mmlab/mmdetection#9711]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
fatal: not a git repository (or any parent up to mount point /mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

sys.platform: linux
Python: 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
CUDA available: True
GPU 0: Tesla K80
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.28.1+

### Reproduces the problem - code sample

import torch, torchvision
import mmcv
from mmcv.runner import load_checkpoint

from mmdet.apis import inference_detector, show_result_pyplot
from mmdet.models import build_detector

from mmcv import Config
cfg = Config.fromfile('mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py')

import copy
import os.path as osp
import json
import numpy as np

from mmdet.datasets.builder import DATASETS
from mmdet.datasets.custom import CustomDataset

from mmdet.datasets import build_dataset
from mmdet.apis import train_detector
import os

@DATASETS.register_module()
class TractorDataset(CustomDataset):
  CLASSES = ('1','2')
  def load_annotations(self, ann_file):
    cat2label = {k: i for i, k in enumerate(self.CLASSES)}
    with open(self.ann_file, 'r') as f:
      anno = json.load(f)
    # load image list from file
    image_list = anno['images']
    data_infos = []
    # convert annotations to middle format
    for image_id in image_list:
        # load annotations
        id=image_id['id']
        filename = image_id['file_name']
        #image = mmcv.imread(filename)
        height, width = image_id['height'], image_id['width']

        data_info = dict(filename=filename, width=width, height=height)

        gt_bboxes = []
        gt_labels = []

        for bbox_id in anno['annotations']:
            bbox_img_id=bbox_id['image_id']
            if bbox_img_id==id:
              bbox=bbox_id['bbox']
              label=bbox_id['category_id']
              gt_bboxes.append(bbox)
              gt_labels.append(label)
            
        data_anno = dict(bboxes=np.array(gt_bboxes, dtype=np.float32).reshape(-1, 4),
            labels=np.array(gt_labels, dtype=np.long))
        
        data_info.update(ann=data_anno)
        data_infos.append(data_info)

    return data_infos

from mmdet.apis import set_random_seed

cfg.dataset_type = 'TractorDataset'
cfg.data_root = ''

cfg.data.test.type = 'TractorDataset'
cfg.data.test.data_root = ''
cfg.data.test.ann_file = 'test/_annotations.coco.json'
cfg.data.test.img_prefix = 'test/'

cfg.data.train.type = 'TractorDataset'
cfg.data.train.data_root = ''
cfg.data.train.ann_file = 'train/_annotations.coco.json'
cfg.data.train.img_prefix = 'train/'

cfg.data.val.type = 'TractorDataset'
cfg.data.val.data_root = ''
cfg.data.val.ann_file = 'test/_annotations.coco.json'
cfg.data.val.img_prefix = 'test/'

cfg.model.roi_head.bbox_head.num_classes = 2

cfg.load_from = 'mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'

cfg.work_dir = './tractor'

cfg.optimizer.lr = 0.02 / 8
cfg.lr_config.warmup = None
cfg.log_config.interval = 10

cfg.evaluation.metric = 'mAP'

cfg.evaluation.interval = 4

cfg.checkpoint_config.interval = 12

cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.device = 'cuda'
cfg.gpu_ids = [0]

cfg.runner=dict(type='EpochBasedRunner', max_epochs=24)

datasets = [build_dataset(cfg.data.train)]

model = build_detector(cfg.model)

model.CLASSES = datasets[0].CLASSES

mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
cfg.dump(os.path.join(cfg.work_dir,'config.py'))

train_detector(model, datasets, cfg, distributed=False, validate=True)

### Reproduces the problem - command or script

python train.py

### Reproduces the problem - error message

/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
train-backup.py:56: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  labels=np.array(gt_labels, dtype=np.long))
/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/datasets/custom.py:181: UserWarning: CustomDataset does not support filtering empty gt images.
  warnings.warn(
2023-02-02 10:31:51,727 - mmdet - INFO - Automatic scaling of learning rate (LR) has been disabled.
2023-02-02 10:31:51,884 - mmdet - INFO - load checkpoint from local path: mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
2023-02-02 10:31:59,273 - mmdet - WARNING - The model and loaded state dict do not match exactly

size mismatch for roi_head.bbox_head.fc_cls.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([3, 1024]).
size mismatch for roi_head.bbox_head.fc_cls.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([3]).
size mismatch for roi_head.bbox_head.fc_reg.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([8, 1024]).
size mismatch for roi_head.bbox_head.fc_reg.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([8]).
2023-02-02 10:31:59,274 - mmdet - INFO - Start running, host: azureuser@naren-gpu, work_dir: /mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/tractor
2023-02-02 10:31:59,274 - mmdet - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) NumClassCheckHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(NORMAL      ) NumClassCheckHook                  
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2023-02-02 10:31:59,274 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
2023-02-02 10:31:59,275 - mmdet - INFO - Checkpoints will be saved to /mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/tractor by HardDiskBackend.
Traceback (most recent call last):
  File "train-backup.py", line 130, in <module>
    train_detector(model, datasets, cfg, distributed=False, validate=True)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/models/detectors/two_stage.py", line 135, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 335, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 93, in loss
    losses = super(RPNHead, self).loss(
  File "/anaconda/envs/mmdet_en2/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 208, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 483, in loss
    anchor_list, valid_flag_list = self.get_anchors(
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 188, in get_anchors
    multi_level_anchors = self.prior_generator.grid_priors(
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/core/anchor/anchor_generator.py", line 236, in grid_priors
    anchors = self.single_level_grid_priors(
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/naren-gpu/code/Users/narendradas.t/Object Detection/mmdetection files/mmdetection/mmdet/core/anchor/anchor_generator.py", line 263, in single_level_grid_priors
    base_anchors = self.base_anchors[level_idx].to(device).to(dtype)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Aborted (core dumped)

### Additional information

For some reason the model trains on google colab(even though the results are bad).
But on azure ml it fails even with a GPU.

even while using mmdetection/tools/train.py with a different config.py it fails.

Is this just a CUDA out of memory issue?

The images in my dataset are 640X320 in shape. So I dont think its CUDA out of memory error.

**Comment by RangiLyu** [comment]
CUDA errors can be caused by many different reasons. If the code is trainable on Colab but failed on Azure, please check the environment and make sure the mmcv version, pytorch version, cuda version, and gpu driver version are matched.

**Comment by narencarbynetech** [comment]
This is the COLAB environment. Can you please tell what difference is causing the error.


sys.platform: linux
Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.2, V11.2.152
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.1+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu116
OpenCV: 4.6.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.6
MMDetection: 2.28.1+c14dd6c

**Comment by RangiLyu** [comment]
There are many differences between these two environments, such as GPU type, cuda version, and pytorch version.
I'm not sure what caused this problem because I have no experience with Azure ML before. I suggest you use the same the same pytorch and cuda version with colab to see whether it is trainable.
