### ISSUE TITLE
[Bug] Registry error with 'DetDataPreprocessor'

### ISSUE THREAD

**Issue by andrewcaunes** [open-mmlab/mmdetection#9719]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

sys.platform: linux
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3070 Ti Laptop GPU
CUDA_HOME: /usr/local/cuda-12.0
NVCC: Cuda compilation tools, release 12.0, V12.0.76
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.6.0
MMEngine: 0.5.0
MMDetection: 3.0.0rc5+5155381

Installation process :
{
python3 -m venv new_env
source new_env/bin/activate
pip install torch torchvision
pip install -U openmim
mim install mmengine
mim intall "mmcv>=2.0.0rc1"
git clone https://github.com/open-mmlab/mmdetection.git -b 3.x
cd mmdetection
pip install -v -e .
}

### Reproduces the problem - code sample

from mmdet.apis import init_detector, inference_detector
config = "mmdetection/configs/tood/tood_r50_fpn_1x_cityscapes.py"

init_detector(config)

### Reproduces the problem - command or script

# fresh install
python3 -m venv new_env
source new_env/bin/activate
pip install torch torchvision
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0rc1"
git clone https://github.com/open-mmlab/mmdetection.git -b 3.x
cd mmdetection/
pip install -v -e .
cd ..

# run script above :
python3 test.py

### Reproduces the problem - error message

(new_env) ~/test_lab> python test.py 
02/03 12:10:01 - mmengine - WARNING - The "model" registry in mmdet did not set import location. Fallback to call `mmdet.utils.register_all_modules` instead.
Traceback (most recent call last):
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/andrew/test_lab/mmdetection/mmdet/models/detectors/tood.py", line 35, in __init__
    super().__init__(
  File "/home/andrew/test_lab/mmdetection/mmdet/models/detectors/single_stage.py", line 28, in __init__
    super().__init__(
  File "/home/andrew/test_lab/mmdetection/mmdet/models/detectors/base.py", line 31, in __init__
    super().__init__(
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 78, in __init__
    self.data_preprocessor = MODELS.build(data_preprocessor)
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 240, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DetDataPreprocessor is not in the model registry. Please check whether the value of `DetDataPreprocessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrew/test_lab/test.py", line 5, in <module>
    init_detector(config)
  File "/home/andrew/test_lab/mmdetection/mmdet/apis/inference.py", line 57, in init_detector
    model = MODELS.build(config.model)
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 240, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/andrew/test_lab/new_env/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `TOOD` in mmdet/models/detectors/tood.py: 'DetDataPreprocessor is not in the model registry. Please check whether the value of `DetDataPreprocessor` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

### Additional information

1. I followed every rule of the recommanded install method so this error shouldn't happen
2. I tried going into mmengine's code to fix it but was not able to for now
3. I saw https://github.com/open-mmlab/mmdetection/issues/9640 which is refering to the same bug but the closing message did not help me solving the issue and I think it is a real bug.
4. It is certainly linked to the mmengine warnings line about the registry not being defined the "normal" way but I saw no issue refering to these warnings.

**Comment by andrewcaunes** [comment]
I have solved my issue, it wasn't a bug :

#Short story :
It doesn't work to call mmdet.apis.inference.init_detector before adding the lines :
`from mmdet.utils import register_all_modules
register_all_modules()`

#Whole story :
The reason is that some modules such as DetDataPreprocessor (and all preprocessors) are intialized (built) in the detector constructor (__init__), which calls its parents constructors. This isn't a problem unless one of the parents is no longer defined in mmdet but in mmengine, such as BaseModule which is the remote parent of all detectors, located in mmengine, and therefore when the 'model' registry is asked to retrieve "DetDataPreprocessor", the scope is 'mmengine" and not "mmdet" at the time of the call to Registry.get(), therefore it returns an error.
I am not very familiar with mmengine and mmdet so I can't say for sure but I find this kind of weird, the mmengine registry.py seems designed to prevent this kind of errors (having methods to search modules in the children registries, and after debugging I discovered the mmdet MODELS registry IS a child of the mmengine MODELS registry and contains the desired modules).
So maybe that is a problem with the way mmdet is connected with mmengine that could be solved easily ?

Anyway this only applies to direct inference from mmdet and the issue doesn't occur when using a runner.

Sorry for the self-solved issue, thank you for your work !

**Comment by suekarry** [comment]
> I have solved my issue, it wasn't a bug :
> 
> #Short story : It doesn't work to call mmdet.apis.inference.init_detector before adding the lines : `from mmdet.utils import register_all_modules` `register_all_modules()`
> 
> #Whole story : The reason is that some modules such as DetDataPreprocessor (and all preprocessors) are intialized (built) in the detector constructor (**init**), which calls its parents constructors. This isn't a problem unless one of the parents is no longer defined in mmdet but in mmengine, such as BaseModule which is the remote parent of all detectors, located in mmengine, and therefore when the 'model' registry is asked to retrieve "DetDataPreprocessor", the scope is 'mmengine" and not "mmdet" at the time of the call to Registry.get(), therefore it returns an error. I am not very familiar with mmengine and mmdet so I can't say for sure but I find this kind of weird, the mmengine registry.py seems designed to prevent this kind of errors (having methods to search modules in the children registries, and after debugging I discovered the mmdet MODELS registry IS a child of the mmengine MODELS registry and contains the desired modules). So maybe that is a problem with the way mmdet is connected with mmengine that could be solved easily ?
> 
> Anyway this only applies to direct inference from mmdet and the issue doesn't occur when using a runner.
> 
> Sorry for the self-solved issue, thank you for your work !

excause me, I want to know 【from mmdet.utils import register_all_modules】in that,mmdetection 2.22 dont 't have register_all_modules .what I can do to slove this problem?

**Comment by mac10-ai** [comment]
KeyError: 'RVSA_MTP is not in the opencd::model registry. Please check whether the value of `RVSA_MTP` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
