### ISSUE TITLE
What do "with mask" and "with_semantic_seg" represent in the HTC model？

### ISSUE THREAD

**Issue by abing222** [open-mmlab/mmdetection#972]
with_mask=True,
        with_crowd=True,
        with_label=True,
        with_semantic_seg=True

mask_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=14, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    mask_head=dict(
        type='HTCMaskHead',
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=81,
        loss_mask=dict(
            type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)),
    semantic_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=14, sample_num=2),
        out_channels=256,
        featmap_strides=[8]),
    semantic_head=dict(
        type='FusedSemanticHead',
        num_ins=5,
        fusion_level=1,
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=183,
        ignore_label=255,
        loss_weight=0.2))

**Comment by hellock** [comment]
`with_mask` and `with_semantic_seg` correspond to the mask annotation and stuff annotation of COCO dataset.
