### ISSUE TITLE
[BUG] TypeError: MaskRCNN: __init__() got an unexpected keyword argument 'bbox_head'

### ISSUE THREAD

**Issue by lwttttt** [open-mmlab/mmdetection#9746]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1

### Reproduces the problem - code sample

I just use my own configs
which inherited the '/mask_rcnn/mask_rcnn_r50_fpn_mstrain-poly_3x_coco.py'

### Reproduces the problem - command or script

here is the code:
_base_ = ['/mask_rcnn/mask_rcnn_r50_fpn_mstrain-poly_3x_coco.py']
model = dict(
	bbox_head=dict(num_classes=1))
dataset_type ='COCODataset'
classes = ('balloon',)
data = dict(
	samples_per_gpu=32,
	workers_per_gpu=2,
	train = dict(
	type = 'COCODataset',
	ann_file = '../data/ballon/train/via_region_data.json',
	img_prefix = '../data/ballon/train'
	),
	val = dict(
	type = 'COCODataset',
	image_prefix = '../data/ballon/val',
        ann_file = '../data/ballon/val/via_region_data.json'
	)

### Reproduces the problem - error message

   test_cfg=cfg.get('test_cfg'))
  File "/data/run01/scz0ach/openmmlab1/mmdetection-master/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/HOME/scz0ach/.conda/envs/openmmlab1/lib/python3.7/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/HOME/scz0ach/.conda/envs/openmmlab1/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/HOME/scz0ach/.conda/envs/openmmlab1/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MaskRCNN: __init__() got an unexpected keyword argument 'bbox_head'

**Comment by RangiLyu** [comment]
MaskRCNN has no `bbox_head`. It is a two stage detector and your config should be like this:
```python
model = dict(
    roi_head=dict(bbox_head=dict(num_classes=1)))
```
please refer to `configs/_base_/models/mask-rcnn_r50_fpn.py`

**Comment by lwttttt** [comment]
> 

however, I just quote and inherited the base file offered by this project(why there is this error?)

**Comment by RangiLyu** [comment]
> however, I just quote and inherited the base file offered by this project(why there is this error?)

![image](https://user-images.githubusercontent.com/12907710/217750250-b4c5448f-6e89-4723-acbf-36541dbbdc1e.png)
Because you write the bbox_head config in the wrong place. Mask R-CNN does not have bbox_head, its roi_head does.

**Comment by lwttttt** [comment]
> > however, I just quote and inherited the base file offered by this project(why there is this error?)
> 
> ![image](https://user-images.githubusercontent.com/12907710/217750250-b4c5448f-6e89-4723-acbf-36541dbbdc1e.png) Because you write the bbox_head config in the wrong place. Mask R-CNN does not have bbox_head, its roi_head does.

thank you so much!!! ♥♥♥
