### ISSUE TITLE
Knowledge distillation[Reimplementation] 

### ISSUE THREAD

**Issue by yuhua666** [open-mmlab/mmdetection#9758]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I used other people's code based on mmdetection for knowledge distillation(https://github.com/ggjy/DeFeat.pytorch). I trained a teacher model, but I encountered this error during distillation. What should I do?

2023-02-12 12:01:28,423 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
kd_decay rate: 1.0
/home/micro/users/zjl/IDa-Det-main/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:159: UserWarning: This overload of addcmul is deprecated:
addcmul(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
addcmul(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out) (Triggered internally at /opt/conda/conda-bld/pytorch_1607370172916/work/torch/csrc/utils/python_arg_parser.cpp:882.)
gx = torch.addcmul(px, 1, pw, dx) # gx = px + pw * dx
dict_keys(['cls_score', 'bbox_pred', 'bbox_targets', 'sampling', 'neck', 'backbone', 'img_metas', 'gt_bboxes', 'gt_labels'])
Traceback (most recent call last):
File "tools/train_entropy.py", line 206, in
main()
File "tools/train_entropy.py", line 194, in main
train_detector_entropy(
File "/home/micro/users/zjl/IDa-Det-main/mmdet/multi_distillation/detector_entropy.py", line 511, in train_detector_entropy
runner.run(data_loaders, cfg.workflow, cfg.total_epochs, kd_cfg=cfg.model.hint_adapt)
File "/home/micro/users/zjl/IDa-Det-main/mmcv-0.5.1/mmcv/runner/runner_kd.py", line 405, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/micro/users/zjl/IDa-Det-main/mmcv-0.5.1/mmcv/runner/runner_kd.py", line 303, in train
outputs = self.batch_processor(
File "/home/micro/users/zjl/IDa-Det-main/mmdet/multi_distillation/detector_entropy.py", line 211, in batch_processor_entropy
proposal_list_s = head_det_s['proposal_list']
KeyError: 'proposal_list'

### Environment

mmdet 2.0.0, mmcv 0.5.1

### Expected results

training successfully

### Additional information

https://github.com/ggjy/DeFeat.pytorch

**Comment by ZwwWayne** [comment]
It seems that there are some key missing in the head_det_s, you might need to add a breakpoint in the file and see what is happening.

**Comment by yxzhang2017** [comment]
Your mmdet environment is 2.0.0,may I ask you that how can I get the specified version as 2.11.0. As I git the code following by readme, I can only download mmedt 2.28.1,which is the latset edition. Hope you can reply.

**Comment by yxzhang2017** [comment]
Your mmdet environment is 2.0.0,may I ask you that how can I get the specified version as 2.11.0. As I git the code following by readme, I can only download mmedt 2.28.1,which is the latset edition. Hope you can reply.

**Comment by ZwwWayne** [comment]
You can use  command `git checkout v2.11.0`.

**Comment by BonBon-Boom** [comment]
OK, thank you, I will try.
