### ISSUE TITLE
[Reimplementation] centripetalnet

### ISSUE THREAD

**Issue by saadyousuf45** [open-mmlab/mmdetection#9759]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I have a question. I am training this on 16 GB graphic card. The memory keeps on maxing out. 
Config:
checkpoint_config = dict(interval=10)
log_config = dict(
    interval=50,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = '/content/drive/MyDrive/Colab Notebooks/Rad_files/Pre-trained Model Checkpoint/centripetalnet_hourglass104_mstest_16x6_210e_coco_20200915_204804-3ccc61e5.pth'
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
auto_scale_lr = dict(enable=True, base_batch_size=16)
dataset_type = 'NewDataset'
data_root = 'data/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='RandomCenterCropPad',
        crop_size=(511, 511),
        ratios=(0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3),
        test_mode=False,
        test_pad_mode=None,
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Resize', img_scale=(511, 511), keep_ratio=False),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(
        type='MultiScaleFlipAug',
        scale_factor=1.0,
        flip=True,
        transforms=[
            dict(type='Resize'),
            dict(
                type='RandomCenterCropPad',
                crop_size=None,
                ratios=None,
                border=None,
                test_mode=True,
                test_pad_mode=['logical_or', 127],
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(
                type='Collect',
                keys=['img'],
                meta_keys=('filename', 'ori_shape', 'img_shape', 'pad_shape',
                           'scale_factor', 'flip', 'img_norm_cfg', 'border'))
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type='NewDataset',
        ann_file='/content/mmdetection/data/train.txt',
        img_prefix=
        '/content/drive/MyDrive/Colab Notebooks/Rad_files/Final_testing_images/',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                type='PhotoMetricDistortion',
                brightness_delta=32,
                contrast_range=(0.5, 1.5),
                saturation_range=(0.5, 1.5),
                hue_delta=18),
            dict(
                type='RandomCenterCropPad',
                crop_size=(511, 511),
                ratios=(0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3),
                test_mode=False,
                test_pad_mode=None,
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Resize', img_scale=(511, 511), keep_ratio=False),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        data_root='data/'),
    val=dict(
        type='NewDataset',
        ann_file='test.txt',
        img_prefix=
        '/content/drive/MyDrive/Colab Notebooks/Rad_files/Final_testing_images/',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(
                type='MultiScaleFlipAug',
                scale_factor=1.0,
                flip=True,
                transforms=[
                    dict(type='Resize'),
                    dict(
                        type='RandomCenterCropPad',
                        crop_size=None,
                        ratios=None,
                        border=None,
                        test_mode=True,
                        test_pad_mode=['logical_or', 127],
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(
                        type='Collect',
                        keys=['img'],
                        meta_keys=('filename', 'ori_shape', 'img_shape',
                                   'pad_shape', 'scale_factor', 'flip',
                                   'img_norm_cfg', 'border'))
                ])
        ],
        data_root='data/'),
    test=dict(
        type='NewDataset',
        ann_file='train.txt',
        img_prefix=
        '/content/drive/MyDrive/Colab Notebooks/Rad_files/Final_testing_images/',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(
                type='MultiScaleFlipAug',
                scale_factor=1.0,
                flip=True,
                transforms=[
                    dict(type='Resize'),
                    dict(
                        type='RandomCenterCropPad',
                        crop_size=None,
                        ratios=None,
                        border=None,
                        test_mode=True,
                        test_pad_mode=['logical_or', 127],
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(
                        type='Collect',
                        keys=['img'],
                        meta_keys=('filename', 'ori_shape', 'img_shape',
                                   'pad_shape', 'scale_factor', 'flip',
                                   'img_norm_cfg', 'border'))
                ])
        ],
        data_root='data/'))
evaluation = dict(interval=2, metric='mAP')
model = dict(
    type='CornerNet',
    backbone=dict(
        type='HourglassNet',
        downsample_times=5,
        num_stacks=2,
        stage_channels=[256, 256, 384, 384, 384, 512],
        stage_blocks=[2, 2, 2, 2, 2, 4],
        norm_cfg=dict(type='BN', requires_grad=True)),
    neck=None,
    bbox_head=dict(
        type='CentripetalHead',
        num_classes=162,
        in_channels=256,
        num_feat_levels=2,
        corner_emb_channels=0,
        loss_heatmap=dict(
            type='GaussianFocalLoss', alpha=2.0, gamma=4.0, loss_weight=1),
        loss_offset=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1),
        loss_guiding_shift=dict(
            type='SmoothL1Loss', beta=1.0, loss_weight=0.05),
        loss_centripetal_shift=dict(
            type='SmoothL1Loss', beta=1.0, loss_weight=1)),
    train_cfg=None,
    test_cfg=dict(
        corner_topk=100,
        local_maximum_kernel=3,
        distance_threshold=0.5,
        score_thr=0.05,
        max_per_img=100,
        nms=dict(type='soft_nms', iou_threshold=0.5, method='gaussian')))
optimizer = dict(type='Adam', lr=6.25e-05)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[190])
runner = dict(type='EpochBasedRunner', max_epochs=210)
work_dir = '/content/drive/MyDrive/Colab Notebooks/Final thesis implementation/testing for HPC/'
seed = 0
gpu_ids = range(0, 1)

### Environment

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Additional information

1. I have changed the batch size and sample per gpu and number of GPUS.

My question is what else can I do to make sure the cuda doesn't max out.

**Comment by saadyousuf45** [comment]
<ipython-input-7-dc767dd29248>:80: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  labels = np.array(gt_labels, dtype = np.long),
<ipython-input-7-dc767dd29248>:82: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  labels_ignore = np.array(gt_labels_ignore, dtype = np.long))
/content/mmdetection/mmdet/datasets/custom.py:181: UserWarning: CustomDataset does not support filtering empty gt images.
  warnings.warn(
2023-02-12 11:43:54,250 - mmdet - INFO - Training with 1 GPU(s) with 1 samples per GPU. The total batch size is 1.
2023-02-12 11:43:54,290 - mmdet - INFO - LR has been automatically scaled from 6.25e-05 to 7.8125e-06
2023-02-12 11:43:54,352 - mmdet - INFO - load checkpoint from local path: /content/drive/MyDrive/Colab Notebooks/Rad_files/Pre-trained Model Checkpoint/centripetalnet_hourglass104_mstest_16x6_210e_coco_20200915_204804-3ccc61e5.pth
2023-02-12 11:43:57,475 - mmdet - WARNING - The model and loaded state dict do not match exactly

size mismatch for bbox_head.tl_heat.0.1.conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([162, 256, 1, 1]).
size mismatch for bbox_head.tl_heat.0.1.conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([162]).
size mismatch for bbox_head.tl_heat.1.1.conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([162, 256, 1, 1]).
size mismatch for bbox_head.tl_heat.1.1.conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([162]).
size mismatch for bbox_head.br_heat.0.1.conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([162, 256, 1, 1]).
size mismatch for bbox_head.br_heat.0.1.conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([162]).
size mismatch for bbox_head.br_heat.1.1.conv.weight: copying a param with shape torch.Size([80, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([162, 256, 1, 1]).
size mismatch for bbox_head.br_heat.1.1.conv.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([162]).
2023-02-12 11:43:57,501 - mmdet - INFO - Start running, host: root@defd7d612227, work_dir: /content/drive/MyDrive/Colab Notebooks/Final thesis implementation/testing for HPC
2023-02-12 11:43:57,502 - mmdet - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) NumClassCheckHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_val_epoch:
(NORMAL      ) NumClassCheckHook                  
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
2023-02-12 11:43:57,505 - mmdet - INFO - workflow: [('train', 1)], max: 210 epochs
2023-02-12 11:43:57,509 - mmdet - INFO - Checkpoints will be saved to /content/drive/MyDrive/Colab Notebooks/Final thesis implementation/testing for HPC by HardDiskBackend.
2023-02-12 11:44:43,735 - mmdet - INFO - Epoch [1][50/267]	lr: 3.115e-06, eta: 13:46:54, time: 0.886, data_time: 0.050, memory: 5608, det_loss: 2086078.5616, off_loss: 0.1355, guiding_loss: 1.8417, centripetal_loss: 4.1235, loss: 2086084.6506, grad_norm: 23140752.8253
2023-02-12 11:45:25,171 - mmdet - INFO - Epoch [1][100/267]	lr: 3.635e-06, eta: 13:19:35, time: 0.829, data_time: 0.007, memory: 5608, det_loss: 2343720.5752, off_loss: 0.2090, guiding_loss: 1.6621, centripetal_loss: 2.0414, loss: 2343724.4511, grad_norm: 28860790.3106
2023-02-12 11:46:07,838 - mmdet - INFO - Epoch [1][150/267]	lr: 4.156e-06, eta: 13:17:41, time: 0.853, data_time: 0.010, memory: 5608, det_loss: 2047569.5397, off_loss: 0.1135, guiding_loss: 1.7654, centripetal_loss: 1.1191, loss: 2047572.5244, grad_norm: 40619034.9787
2023-02-12 11:46:49,428 - mmdet - INFO - Epoch [1][200/267]	lr: 4.677e-06, eta: 13:11:21, time: 0.832, data_time: 0.006, memory: 5608, det_loss: 2232150.2086, off_loss: 0.1471, guiding_loss: 1.8760, centripetal_loss: 1.4499, loss: 2232153.6975, grad_norm: 56373394.0277
2023-02-12 11:47:31,290 - mmdet - INFO - Epoch [1][250/267]	lr: 5.198e-06, eta: 13:08:18, time: 0.837, data_time: 0.009, memory: 5608, det_loss: 2103287.0247, off_loss: 0.1248, guiding_loss: 1.8527, centripetal_loss: 1.3259, loss: 2103290.2750, grad_norm: 36426636.5928
2023-02-12 11:48:29,359 - mmdet - INFO - Epoch [2][50/267]	lr: 5.896e-06, eta: 12:29:33, time: 0.877, data_time: 0.048, memory: 5608, det_loss: 1927522.8200, off_loss: 0.3334, guiding_loss: 1.9894, centripetal_loss: 3.0116, loss: 1927528.1380, grad_norm: 67334702.2778
2023-02-12 11:49:11,173 - mmdet - INFO - Epoch [2][100/267]	lr: 6.417e-06, eta: 12:32:37, time: 0.836, data_time: 0.005, memory: 5608, det_loss: 1334603.5056, off_loss: 0.2475, guiding_loss: 1.7669, centripetal_loss: 2.2110, loss: 1334607.7502, grad_norm: 27412358.3600
2023-02-12 11:49:52,996 - mmdet - INFO - Epoch [2][150/267]	lr: 6.937e-06, eta: 12:34:49, time: 0.836, data_time: 0.006, memory: 5608, det_loss: 1973109.4505, off_loss: 0.3420, guiding_loss: 1.8485, centripetal_loss: 4.4522, loss: 1973116.0530, grad_norm: 61579106.2800
2023-02-12 11:50:34,861 - mmdet - INFO - Epoch [2][200/267]	lr: 7.458e-06, eta: 12:36:28, time: 0.837, data_time: 0.006, memory: 5608, det_loss: 1596720.5911, off_loss: 0.1624, guiding_loss: 1.8463, centripetal_loss: 1.1101, loss: 1596723.6822, grad_norm: 54079553.3647
2023-02-12 11:51:16,618 - mmdet - INFO - Epoch [2][250/267]	lr: 7.813e-06, eta: 12:37:28, time: 0.835, data_time: 0.006, memory: 5608, det_loss: 1708596.8641, off_loss: 0.1886, guiding_loss: 1.7828, centripetal_loss: 1.5210, loss: 1708600.3754, grad_norm: 30750285.0729
[>>>>>>>>>>>>>                    ] 6/15, 0.6 task/s, elapsed: 10s, ETA:    15s
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
[<ipython-input-9-ce97554a7869>](https://localhost:8080/#) in <module>
     18 
     19 # set the meta to avoid errors for yolo f16
---> 20 train_detector(model, datasets, cfg, distributed=False, validate=True )

21 frames
[/content/mmdetection/mmdet/apis/train.py](https://localhost:8080/#) in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
    244     elif cfg.load_from:
    245         runner.load_checkpoint(cfg.load_from)
--> 246     runner.run(data_loaders, cfg.workflow)

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py](https://localhost:8080/#) in run(self, data_loaders, workflow, max_epochs, **kwargs)
    134                     if mode == 'train' and self.epoch >= self._max_epochs:
    135                         break
--> 136                     epoch_runner(data_loaders[i], **kwargs)
    137 
    138         time.sleep(1)  # wait for some hooks like loggers to finish

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py](https://localhost:8080/#) in train(self, data_loader, **kwargs)
     56             self._iter += 1
     57 
---> 58         self.call_hook('after_train_epoch')
     59         self._epoch += 1
     60 

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/base_runner.py](https://localhost:8080/#) in call_hook(self, fn_name)
    315         """
    316         for hook in self._hooks:
--> 317             getattr(hook, fn_name)(self)
    318 
    319     def get_hook_info(self) -> str:

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/hooks/evaluation.py](https://localhost:8080/#) in after_train_epoch(self, runner)
    269         """Called after every training epoch to evaluate the results."""
    270         if self.by_epoch and self._should_evaluate(runner):
--> 271             self._do_evaluate(runner)
    272 
    273     def _do_evaluate(self, runner):

[/content/mmdetection/mmdet/core/evaluation/eval_hooks.py](https://localhost:8080/#) in _do_evaluate(self, runner)
     58         # Changed results to self.results so that MMDetWandbHook can access
     59         # the evaluation results and log them to wandb.
---> 60         results = single_gpu_test(runner.model, self.dataloader, show=False)
     61         self.latest_results = results
     62         runner.log_buffer.output['eval_iter_num'] = len(self.dataloader)

[/content/mmdetection/mmdet/apis/test.py](https://localhost:8080/#) in single_gpu_test(model, data_loader, show, out_dir, show_score_thr)
     27     for i, data in enumerate(data_loader):
     28         with torch.no_grad():
---> 29             result = model(return_loss=False, rescale=True, **data)
     30 
     31         batch_size = len(result)

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.8/dist-packages/mmcv/parallel/data_parallel.py](https://localhost:8080/#) in forward(self, *inputs, **kwargs)
     49             return self.module(*inputs[0], **kwargs[0])
     50         else:
---> 51             return super().forward(*inputs, **kwargs)
     52 
     53     def scatter(self, inputs: ScatterInputs, kwargs: ScatterInputs,

[/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/data_parallel.py](https://localhost:8080/#) in forward(self, *inputs, **kwargs)
    167 
    168             if len(self.device_ids) == 1:
--> 169                 return self.module(*inputs[0], **kwargs[0])
    170             replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
    171             outputs = self.parallel_apply(replicas, inputs, kwargs)

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py](https://localhost:8080/#) in new_func(*args, **kwargs)
    117                                 f'method of those classes {supported_types}')
    118             if not (hasattr(args[0], 'fp16_enabled') and args[0].fp16_enabled):
--> 119                 return old_func(*args, **kwargs)
    120 
    121             # get the arg spec of the decorated method

[/content/mmdetection/mmdet/models/detectors/base.py](https://localhost:8080/#) in forward(self, img, img_metas, return_loss, **kwargs)
    172             return self.forward_train(img, img_metas, **kwargs)
    173         else:
--> 174             return self.forward_test(img, img_metas, **kwargs)
    175 
    176     def _parse_losses(self, losses):

[/content/mmdetection/mmdet/models/detectors/base.py](https://localhost:8080/#) in forward_test(self, imgs, img_metas, **kwargs)
    152             # TODO: support test augmentation for predefined proposals
    153             assert 'proposals' not in kwargs
--> 154             return self.aug_test(imgs, img_metas, **kwargs)
    155 
    156     @auto_fp16(apply_to=('img', ))

[/content/mmdetection/mmdet/models/detectors/cornernet.py](https://localhost:8080/#) in aug_test(self, imgs, img_metas, rescale)
     86             img_pair = torch.cat([imgs[ind], imgs[flip_ind]])
     87             x = self.extract_feat(img_pair)
---> 88             outs = self.bbox_head(x)
     89             bbox_list = self.bbox_head.get_bboxes(
     90                 *outs, [img_metas[ind], img_metas[flip_ind]], False, False)

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

[/content/mmdetection/mmdet/models/dense_heads/corner_head.py](https://localhost:8080/#) in forward(self, feats)
    276         """
    277         lvl_ind = list(range(self.num_feat_levels))
--> 278         return multi_apply(self.forward_single, feats, lvl_ind)
    279 
    280     def forward_single(self, x, lvl_ind, return_pool=False):

[/content/mmdetection/mmdet/core/utils/misc.py](https://localhost:8080/#) in multi_apply(func, *args, **kwargs)
     28     pfunc = partial(func, **kwargs) if kwargs else func
     29     map_results = map(pfunc, *args)
---> 30     return tuple(map(list, zip(*map_results)))
     31 
     32 

[/content/mmdetection/mmdet/models/dense_heads/centripetal_head.py](https://localhost:8080/#) in forward_single(self, x, lvl_ind)
    189         br_dcn_offset = self.br_dcn_offset[lvl_ind](br_guiding_shift.detach())
    190 
--> 191         tl_feat_adaption = self.tl_feat_adaption[lvl_ind](tl_pool,
    192                                                           tl_dcn_offset)
    193         br_feat_adaption = self.br_feat_adaption[lvl_ind](br_pool,

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1192         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194             return forward_call(*input, **kwargs)
   1195         # Do not call functions when jit is used
   1196         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.8/dist-packages/mmcv/ops/deform_conv.py](https://localhost:8080/#) in forward(self, x, offset)
    308             offset = F.pad(offset, (0, pad_w, 0, pad_h), 'constant', 0)
    309             offset = offset.contiguous()
--> 310         out = deform_conv2d(x, offset, self.weight, self.stride, self.padding,
    311                             self.dilation, self.groups, self.deform_groups,
    312                             False, self.im2col_step)

[/usr/local/lib/python3.8/dist-packages/mmcv/ops/deform_conv.py](https://localhost:8080/#) in forward(ctx, input, offset, weight, stride, padding, dilation, groups, deform_groups, bias, im2col_step)
     90         assert (input.size(0) % cur_im2col_step
     91                 ) == 0, 'batch size must be divisible by im2col_step'
---> 92         ext_module.deform_conv_forward(
     93             input,
     94             weight,

OutOfMemoryError: CUDA out of memory. Tried to allocate 3.59 GiB (GPU 0; 14.76 GiB total capacity; 6.39 GiB already allocated; 1.90 GiB free; 11.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ZwwWayne** [comment]
It seems that the error is caused by CUDA out of memory. You can try to reduce the image size or use smaller batch size to avoid the issue.
