### ISSUE TITLE
how to get the predicted box info during training

### ISSUE THREAD

**Issue by marsggbo** [open-mmlab/mmdetection#976]
I want to train a model on cropped images, how can I get the predicted box information during the training process?

**Comment by liushuchun** [comment]
you can register a Hook to predict out the box information in after_each_epoch method.

**Comment by marsggbo** [comment]
@liushuchun 哇，武大的吗？我是你隔壁大学的。想问一下这个Hook机制在哪里有教程啥的吗？不太清楚怎么用。
