### ISSUE TITLE
FileNotFoundError: img file does not exist: /mnt/data/anhtran/train2014/COCO_train2014_000000181946.png

### ISSUE THREAD

**Issue by anhtranhoang** [open-mmlab/mmdetection#977]
I don't know why this code auto convert my data into '.png' and so the program appear this error? pls help me , thank you very much !

**Comment by atmika-honnalgere** [comment]
@anhtranhoang  How did you fix the problem? I have a json that has jpg extension so do my images. But while training, the code is looking for .png. Help please!

**Comment by anhtranhoang** [comment]
in def prepare_train_img(self, idx):
find the line code :
if self.with_seg:
gt_seg = mmcv.imread(
osp.join(self.seg_prefix, img_info['file_name'].replace(
'jpg', 'png')),
flag='unchanged')
change png to jpg

Vào Th 3, 23 thg 7, 2019 lúc 14:09 Atmika Honnalgere <
notifications@github.com> đã viết:

**Comment by freepoet** [comment]
you can try this [jpg2png.py](https://github.com/freepoet/split_dataset/blob/main/jpg2png.py)
