### ISSUE TITLE
[Feature] About model upgrading

### ISSUE THREAD

**Issue by majintao1994** [open-mmlab/mmdetection#9779]
### What's the feature?

I want to migrate the project made on mmdetection2.0 to mmdetection3. x. What is the conversion method of the model that can make it run on mmdetection3. x, and whether there will be any loss of accuracy？

**Comment by ZwwWayne** [comment]
The model checkpoint does not need to be upgraded because the compatibility is fully kept. You only need to update the interface of your code.

**Comment by kasteric** [comment]
> The model checkpoint does not need to be upgraded because the compatibility is fully kept. You only need to update the interface of your code.

how to do this? Really different code bases and really complex
