### ISSUE TITLE
base abstract class for components

### ISSUE THREAD

**Issue by Ridhwanluthra** [open-mmlab/mmdetection#978]
**Describe the feature**
Like we have abstract class for the detectors does it make sense to have similar things for individual components such as the backbone, head, etc.

**Motivation**
I was working on building a new detector with new backbones and new heads and everything and i had to manually figure out what is needed by the pipeline and make the corresponding functions

**Related resources**
N/A

**Additional context**
I can work on this and submit a PR

**Comment by hellock** [comment]
That's a good idea. Maybe you can briefly list the apis for the abstract classes here for discussion.
