### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by chenhan1998** [open-mmlab/mmdetection#9781]
gpu：rtx3060
torch version：1.8.2cu111 +torchvision0.9.2+cu111
mmcv-full version: 1.4.0
mmdet version:2.23.0

**Comment by ZwwWayne** [comment]
Please see the FAQ https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment. 
It is caused by some mismatch between CUDA env and pytorch and GPU
