### ISSUE TITLE
Any plan for support torchscript model convertion? [Feature] 

### ISSUE THREAD

**Issue by congjianting** [open-mmlab/mmdetection#9785]
### What's the feature?

it will be very useful for support torchscript model in deployment. thanks for your reply.

**Comment by RangiLyu** [comment]
We already support torchscript deployment in [MMDeploy](https://github.com/open-mmlab/mmdeploy). Please refer to https://mmdeploy.readthedocs.io/en/latest/05-supported-backends/torchscript.html
