### ISSUE TITLE
[Docs] What is the format of result.pkl?

### ISSUE THREAD

**Issue by 24spiders** [open-mmlab/mmdetection#9788]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

I am unable to find the documentation of the format of ``result.pkl`` generated by ``tools/test.py`` in the docs.

I have trained a retinanet model. When using ``python tools/test.py {config} {weights} --show`` the images shown demonstrate the model is performing quite well on detection. When I add the ``--out results.pkl`` to the call, a ``results.pkl`` is printed. This pickle does not have the same boxes that are shown in the ``--show`` call. 

My test dataset has 3 classes and 392 images. When loading the ``results.pkl`` I get 392 entries with 3 lists each.

I am then assuming that this means the format is
```
[IMAGE 1 CLASS 1], [IMAGE 1 CLASS 2], [IMAGE 1 CLASS 3]

[IMAGE 2 CLASS 1], [IMAGE 2 CLASS 2], [IMAGE 2 CLASS 3]

[IMAGE 3 CLASS 1], [IMAGE 3 CLASS 2], [IMAGE 3 CLASS 3]

.

.

[IMAGE 392 CLASS 1], [IMAGE 392 CLASS 2], [IMAGE 392 CLASS 3]
```

With each entry as `[xmin, ymin, xmax, ymax, score]`

Again, the first entry in ``results.pkl`` contains 100+ boxes, though the output from ``--show`` draws only 2 boxes on the image. Even after applying torch's nms, the results do not look the same

**Comment by BIGWangYuDong** [comment]
`show` will filter some boxes with lower scores, you can have a look at the source code
