### ISSUE TITLE
show_result (inference mode) crashes jupyter notebook

### ISSUE THREAD

**Issue by garrettmsft7** [open-mmlab/mmdetection#979]
When using show_result for inference predictions, it will crash jupyter notebook.

I have isolated this to the lines:
```
 mmcv.imshow_det_bboxes(
        img.copy(),
        bboxes,
        labels,
        class_names=class_names,
        score_thr=score_thr,
        show=out_file is None,
        out_file=out_file)
```

It looks like mmcv.imshow doesn't play well with jupyter notebooks, and it's a known issue.
https://stackoverflow.com/questions/46236180/opencv-imshow-will-cause-jupyter-notebook-crash

Is there a workaround for this?

**Comment by hellock** [comment]
You may use matplotlib if you are using jupyter notebook to run the demo.
Related to https://github.com/open-mmlab/mmcv/issues/34
