### ISSUE TITLE
How to confirm which image the bbox and score in result.pkl belong to ?

### ISSUE THREAD

**Issue by xishanhan** [open-mmlab/mmdetection#9792]
Hello, I want to add an item in  the result.pkl(generated by RPN) to indicate the image name when eval bbox, so as to confirm which image the bbox and score in result.pkl belong to. How should I do it ?
Looking forward to your reply.

**Comment by BIGWangYuDong** [comment]
If you are using 3.x version, it will be a dict[img_name: result], which may answer your question

For 2.x version, it will be a list, and the sequence will be the annotation sequence.

**Comment by xishanhan** [comment]
> If you are using 3.x version, it will be a dict[img_name: result], which may answer your question
> 
> For 2.x version, it will be a list, and the sequence will be the annotation sequence.

Sorry, I don't really understand the meaning of 'annotation sequence'. If I choose 2000 images in COCO val2017 to eval, is the sequence of the result the sequence of these 2000 image names?

**Comment by xishanhan** [comment]
> For 2.x version, it will be a list, and the sequence will be the annotation sequence.

Does the annotation sequence refer to the image sequence contained in the 'images' field in coco instances_val2017.json?

**Comment by xishanhan** [comment]
I got it, thank you!
