### ISSUE TITLE
Replacing RPN with FCOS

### ISSUE THREAD

**Issue by shwoo93** [open-mmlab/mmdetection#980]
Hello,

Thanks for your nice work.

In the paper of FCOS, the authors have shown that FCOS can replace RPN with improved AR.
How can I use FCOS in that way?

Thanks

**Comment by hellock** [comment]
This is currently not available by just modifying a few lines in the config file. `FCOSHead` and `RPNHead` are generally the same but you may need to change some post-processing steps.

**Comment by runzeer** [comment]
So how to change the post-processing steps? Would you please share your opinions ?

**Comment by alexwq100** [comment]
@runzeer have you replaced? how about the performance, for fcos in my custom dataset,it is not good,very disappointed .
