### ISSUE TITLE
Use WBF

### ISSUE THREAD

**Issue by Grayfaner** [open-mmlab/mmdetection#9809]
### What's the feature?

I want to use WBF instead of NMS for detection and evaluation in mmdetection v2.22.0 version. How to operate it?

### Any other context?

I tried a few approaches, but was never able to integrate WBF into mmdetection.

**Comment by hhaAndroid** [comment]
https://github.com/open-mmlab/mmdetection/issues/9770

**Comment by thiagoribeirodamotta** [comment]
Was there any update to this?
