### ISSUE TITLE
HTC multi-mask stream module is not consistent with paper

### ISSUE THREAD

**Issue by Lucy0601** [open-mmlab/mmdetection#981]
In the HTC paper, I think you mean the multi mask stream is coming from the previous stage, but the code shows that the multi mask streams are belong to the same stage. I feel a little confused.

**Comment by hellock** [comment]
Not sure what "multi-task stream" is referred to. Could you be more specific? The code and paper should be consistent.

**Comment by Lucy0601** [comment]
As you mentioned in the paper 'Following similar principles, we
introduce an information flow between mask branches by
feeding the mask features of the preceding stage to the current stage, as illustrated in Figure 1c'.
But in the code I think the mask features are just belong to the specific stage.
Can you tell me where I don't notice?

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/htc.py#L141-L151

**Comment by Lucy0601** [comment]
Yeah, I have noticed this , but I think that the mask_feats are all come from the specific stage, not the preceding stage.

**Comment by hellock** [comment]
Maybe you have some misunderstandings about these lines? They clearly illustrate that the mask features come from the current stage and preceding stages.

**Comment by Lucy0601** [comment]
I'm not sure where the misunderstanding is,  my thought is:
mask_feats come from
mask_feats = mask_roi_extractor(x[:mask_roi_extractor.num_inputs],  pos_rois)
Then pos_rois come from
pos_rois = bbox2roi([res.pos_bboxes for res in sampling_results])
Then sampling_results come from the specific stage
Could you help me figure out the wrong place? Thank you very much.

**Comment by hellock** [comment]
It seems that you ignored the for-loop. The RoIs are stage-specific and the features comes from preceding stages as well.

**Comment by Lucy0601** [comment]
Thank you very much, I have understood what you mean, I think the preceding stages means the different mask_head. So the mask information flow can refine the preceding mask_head? 
Do I have the right understanding this time?

**Comment by hellock** [comment]
All mask heads in preceding stages are used. Features of previous stages help the current stage to obtain better mask predictions.

**Comment by Shi-Xiaoyu** [comment]
Almost the same question. According to Formula 6 of your paper, mask_feats should be updated in each stage by x_t = P(x,r_t)+P(S(x),r_t). But it seems that in your implementation mask_feats is only updated once at Line141, leading to x_t = P(x,r_1) + P(S(x),r_1). What is wrong with my understanding? Thx!
