### ISSUE TITLE
Regression cost for Label Assignment in RTMDet

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmdetection#9825]
### Branch

3.x branch https://mmdetection.readthedocs.io/en/3.x/

### 📚 The doc issue

In RTMDet paper, it is stated that "When using Generalized IoU [67] as regression cost, the maximum difference between the best match and the worst match is less than 1". However I think is not true. The best match has GIoU = 1, and the worst match has GIoU apprx -1. So the difference here should be 2?

**Comment by RangiLyu** [comment]
Yes, you are right.

**Comment by RangiLyu** [comment]
Thank you very much for pointing out the mistake in our technical report, we will correct it in subsequent version!
