### ISSUE TITLE
[Bug] Warning for ONNX model inference

### ISSUE THREAD

**Issue by torchmyheart** [open-mmlab/mmdetection#9828]
### Prerequisite

- [x] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
PyTorch: 1.7.0
  - CUDA Runtime 11.0
  - CuDNN 8.0.3

TorchVision: 0.8.0
OpenCV: 4.5.5
MMCV: 1.4.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.24.1+c14dd6c

### Reproduces the problem - code sample

none

### Reproduces the problem - command or script

python tools/deployment/pytorch2onnx.py    
mask_r50.py epoch_1.pth     
--output-file maskrcnn.onnx     
--input-img XX.jpg   
--test-img XX.jpg  
--shape 800 1333     
--show     
--verify     
--dynamic-export

### Reproduces the problem - error message

The model was successfully exported, but warned after the test.

[W:onnxruntime:, execution_frame.cc:835 VerifyOutputSizes] **Expected shape from model of {-1,-1,800,1333} does not match actual shape of {1,100,1184,1344} for output masks**
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 331, in <module>
    skip_postprocess=args.skip_postprocess)
  File "tools/deployment/pytorch2onnx.py", line 192, in pytorch2onnx
    o_res, p_res, rtol=1e-03, atol=1e-05, err_msg=err_msg)
  File "/databank/home/zhaohongke/anaconda3/envs/mmdet/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/databank/home/zhaohongke/anaconda3/envs/mmdet/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 763, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05
The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the exported ONNX model is problematic.
(shapes (100, 5), (1, 5) mismatch)
 x: array([[574.1901  , 279.54486 , 974.1198  , 850.34467 ,   0.999998],
       [ -1.      ,  -1.      ,  -1.      ,  -1.      ,   0.      ],
       [ -1.      ,  -1.      ,  -1.      ,  -1.      ,   0.      ],...
 y: array([[574.1901  , 279.54492 , 974.1198  , 850.3447  ,   0.999998]],
      dtype=float32)

### Additional information

I hope to import the onnx model of maskrcnn and pass the test, but there is a warning during the test. Is the output mask correct?

And there is an AssertionError. Are the outputs _x_ and _y_ correct? Generally, the results include coordinates, probability, and mask.

I sincerely hope you'll help me.

**Comment by BIGWangYuDong** [comment]
what code did you change? More details are needed.

**Comment by MorjanBAHAJI** [comment]
I've also had this error when exporting an onnx file for a yolov3 mobilenetv2 model. The ONNX should have been save somewhere in your workdir. I've just ignored the error and tested the exported model with tools/deployment/test.py and it gave me good enough results ! 
The deployement script is marked as "Experimental" in the doc. The recommanded behavior is to use MMDeploy to export models.

https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html#how-to-evaluate-the-exported-models

**Comment by torchmyheart** [comment]
@BIGWangYuDong 
> what code did you change? More details are needed.

I just changed _F.grid_sampler_ to _mmcv.ops.point_sample.bilinear_grid_sample_ in _mmdet/models/roi_heads/mask_heads/fcn_mask_head.py_

And I'm working on my own datasets.

**Comment by torchmyheart** [comment]
@MorjanBAHAJI 
Thanks a lot. I will try to use MMDeploy later.
