### ISSUE TITLE
How can i visualized the anchors generated and the gradient decent?

### ISSUE THREAD

**Issue by JackJWWong** [open-mmlab/mmdetection#983]
I want to draw a picture about the generated anchors on Guided anchoring and check out the gradient decent picture, I am studying about tiny object detection and i found my network is unable to study and the result remain 39%, so it could be really helpful and i will appreciate your advices

**Comment by hellock** [comment]
You can use [`mmcv.imshow_bboxes()`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L20) to visualize anchors/bboxes. Plotting the gradient is not specific to this repo, you can do as in other pytorch programs.

**Comment by JackJWWong** [comment]
> You can use [`mmcv.imshow_bboxes()`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L20) to visualize anchors/bboxes. Plotting the gradient is not specific to this repo, you can do as in other pytorch programs.

thanks, and which kind of feature map should I export in the program?

**Comment by hellock** [comment]
You need to decide which feature map to check.

**Comment by JackJWWong** [comment]
> You need to decide which feature map to check.

okay, thx so much, I will check the program.

**Comment by guanbin1994** [comment]
> You can use [`mmcv.imshow_bboxes()`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/visualization/image.py#L20) to visualize anchors/bboxes. Plotting the gradient is not specific to this repo, you can do as in other pytorch programs.

sorry to bother, but where can i add the code to visualize the feature map with the anchor while I was training?

**Comment by hellock** [comment]
@guanbin1994 I am not sure whether you referred to anchors or proposals. You can add the visualization code after the sliding window step ([`get_anchors()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L165)), but it is hard to see anything since the anchors are everywhere.

**Comment by guanbin1994** [comment]
> @guanbin1994 I am not sure whether you referred to anchors or proposals. You can add the visualization code after the sliding window step ([`get_anchors()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L165)), but it is hard to see anything since the anchors are everywhere.

yeah, I mean proposals, I want to see if the proposal is close to the Bounding Boxes

**Comment by guanbin1994** [comment]
> @guanbin1994 I am not sure whether you referred to anchors or proposals. You can add the visualization code after the sliding window step ([`get_anchors()`](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/anchor_heads/anchor_head.py#L165)), but it is hard to see anything since the anchors are everywhere.

with guiding anchors I mean
