### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kennyadelaide** [open-mmlab/mmdetection#9830]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

the functions named wrap_fp16_model and tensor2imgs from the latest version of mmdetection, then how to invoke them? 

### Reproduces the problem - code sample

ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (C:\Anaconda3\envs\mmdetection\lib\site-packages\mmdet\core\__init__.py)

### Reproduces the problem - command or script

ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (C:\Anaconda3\envs\mmdetection\lib\site-packages\mmdet\core\__init__.py)

### Reproduces the problem - error message

ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (C:\Anaconda3\envs\mmdetection\lib\site-packages\mmdet\core\__init__.py)

### Additional information

ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (C:\Anaconda3\envs\mmdetection\lib\site-packages\mmdet\core\__init__.py)

**Comment by BIGWangYuDong** [comment]
please make sure you have successfully install mmcv and mmdetection. And also, you need to check whether the version is match.
