### ISSUE TITLE
Questions about technical report

### ISSUE THREAD

**Issue by gfjiangly** [open-mmlab/mmdetection#984]
Questions about technical report：MMDetection: Open MMLab Detection Toolbox and Benchmark

**Comment by gfjiangly** [comment]
In Table 9, when we explore the effects of neg pos ub, why not use the better parameters smoothl1 beta=1/15

![image](https://user-images.githubusercontent.com/38396233/61168942-7c3cb780-a588-11e9-837f-fb847dd459eb.png)

**Comment by hellock** [comment]
1/9 is the default value in mmdetection as well as the official implementation of Faster R-CNN or FPN, so we use it as the baseline when studying the affects of other hyper-parameters.

**Comment by gfjiangly** [comment]
> 1/9 is the default value in mmdetection as well as the official implementation of Faster R-CNN or FPN, so we use it as the baseline when studying the affects of other hyper-parameters.

That's it. Thank you.
