### ISSUE TITLE
[Docs] How to calculate the area of the predicted object detection box?

### ISSUE THREAD

**Issue by qbs2021** [open-mmlab/mmdetection#9856]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

Hello! How can I calculate the area of the predicted object detection box? What should I do.

**Comment by RangiLyu** [comment]
Each predicted box is in format of "x0, y0, x1, y1", which means the top left and bottom right corner of the box.
You can calculate the area by `(x1 - x0) * (y1 - y0)`.

**Comment by qbs2021** [comment]
Thank you. When I execute test.py, I get a tif file to draw the box. Where can I get x0, y0, x1, y1 coordinate files?
