### ISSUE TITLE
'DetDataSample' object has no attribute '_gt_sem_seg'

### ISSUE THREAD

**Issue by zsc1220** [open-mmlab/mmdetection#9860]
![image](https://user-images.githubusercontent.com/36871680/222367933-4adc4875-313b-41ac-80a6-82571d2ad749.png)

could someone help me ? how to slove this problem?

**Comment by zsc1220** [comment]
![image](https://user-images.githubusercontent.com/36871680/222367728-ad57beb1-92c1-4343-ad16-849c44ad281f.png)
could someone help me ? how to slove this problem?

**Comment by RangiLyu** [comment]
Please follow the issue template to provide more information such as what command did you run and what config did you use?
