### ISSUE TITLE
Create multimodal training datasets and networks in version 3.x of mmdetection

### ISSUE THREAD

**Issue by qqq1521902442** [open-mmlab/mmdetection#9874]
I want to create multimodal training dataset and network in 3.x version of mmdetection and I want to know which files I need to modify?

**Comment by qqq1521902442** [comment]
The new version has modified many of the files internally and set up the DataSample in such a way that I am having a hard time getting past the 2.x version. Currently I am trying the way in the mmengine documentation to make the Base_dataset load to get a list with two images, but at the stage of modifying the dataset and model files, I am very confused about how to use the dataSample to train the two incoming data and to distinguish between the two data paths in the load_data_list method.

**Comment by qqq1521902442** [comment]
I modified the framework by referring to mmdet3d, but I found the problem that the dataset in mmdet3d still reads the file only once, while the multimodality I want to implement requires reading two images at a time.

**Comment by BIGWangYuDong** [comment]
Maybe you can follow this wrapper to create a wrapper to process two images simultaneously. Also, you can add another LoadImageFromFile to load the second image

https://github.com/open-mmlab/mmdetection/blob/bfdc5d5d90531f8309e04e26b5630b38941c2981/mmdet/datasets/transforms/wrappers.py#L176

**Comment by qqq1521902442** [comment]
> 

Thank you for your reply! Regarding the suggestion of adding another Loadimagefile, I'm wondering if you mean adding another LoadImgFile to the pipline? Or do you mean like mmdet3d redefining a LoadImgFile3D?

**Comment by BIGWangYuDong** [comment]
Each solution is OK, you only need add the image into the results, and the key is different from 'img' (e.g. ('img_2')). Also, you should keep the randomness same, and ProposalBroadcaster is an example to keep the randomness same

**Comment by qqq1521902442** [comment]
> Each solution is OK, you only need add the image into the results, and the key is different from 'img' (e.g. ('img_2')). Also, you should keep the randomness same, and ProposalBroadcaster is an example to keep the randomness same
Thank you for your help! I have now successfully input two images for the tensor, I named them 'inputs_r' and 'inputs_i', but I am having the problem in the figure. Also I checked this part of the code and didn't find a location where I can change the inputs input. This confuses me and I don't know where I should change it.
![image](https://user-images.githubusercontent.com/74524482/223075924-631d3cfc-1050-473f-9b27-0faf21abe820.png)
Maybe I should delete all 'inputs' after entering data?
![image](https://user-images.githubusercontent.com/74524482/223077573-b13cbeac-3926-418a-a968-4fe0ad309716.png)

![image](https://user-images.githubusercontent.com/74524482/223077103-94394430-6b18-4fc4-9588-766f9263c662.png)

**Comment by BIGWangYuDong** [comment]
Feel free to re-open the issue if you meet any problem

**Comment by Jongmin1991** [comment]
Hello, I am also trying to detect objects using RGB image & IR image.
I plan to extract feature from RGB image & IR image separately through a different backbone network and then fuse the values.

I think the code you created might be helpful in this regard. Could you please share it ?

Thank you.
