### ISSUE TITLE
[Bug] one_class detection config

### ISSUE THREAD

**Issue by keepgoing365** [open-mmlab/mmdetection#9875]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

ubuntu20

### Reproduces the problem - code sample

1

### Reproduces the problem - command or script

1

### Reproduces the problem - error message

[Errno 2] No such file or directory: "class_name"

if i want to detect  just one class object,then i must write in config file like this:
classes = ('balloon',)  and not classes = ('balloon').Otherwise the scripts throw above exception.It's  weird!

### Additional information

1

**Comment by BIGWangYuDong** [comment]
because classes must be a tuple or a list. if you simply write `classes=(xxx)`, It will feed as a string.
