### ISSUE TITLE
[Bug] VOCDataset print wrong class names in some cases

### ISSUE THREAD

**Issue by LoSealL** [open-mmlab/mmdetection#9878]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: win32
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1660 Ti
CUDA_HOME: C:\opt\CUDA\v11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.124
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32215 版
GCC: n/a
PyTorch: 1.13.1+cu116
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu116
OpenCV: 4.5.2
MMCV: 1.7.1
MMCV Compiler: MSVC 193431937
MMCV CUDA Compiler: 11.6
MMDetection: 2.28.2+e9cae2d

### Reproduces the problem - code sample
When specify a partial of class names in VOCDataset, during its evaluation the printed summary table somehow gives wrong names.

```python
dataset = VOCDataset(classes=("dog", "cat", "person"), **dataconfig)
# ...
dataset.evaluate(results)
```

### Reproduces the problem - command or script

modify the dataset arguments to customized a subclass names, such as `("dog", "cat", "person")`
```shell
python tools/train.py configs/pascal_voc/ssd300_voc0712.py
```

### Reproduces the problem - error message

```
2023-03-05 22:31:12,831 - mmdet - INFO - 
+--------+-----+------+--------+-------+
| class  | gts | dets | recall | ap    |
+--------+-----+------+--------+-------+
| aeroplane    | 4   | 184  | 0.000  | 0.000 |
| bicycle    | 3   | 571  | 0.000  | 0.000 |
| bird | 17  | 4045 | 0.588  | 0.003 |
+--------+-----+------+--------+-------+
| mAP    |     |      |        | 0.001 |
+--------+-----+------+--------+-------+
2023-03-05 22:31:12,910 - mmdet - INFO - Exp name: ssd300_voc0712.py
2023-03-05 22:31:12,911 - mmdet - INFO - Epoch(val) [4][24]     mAP: 0.0010, AP50: 0.0010
```

### Additional information

The root cause is `dataset` argument of function `eval_map` called in method `VOCDataset.evaluate`, where `ds_name="voc07"`.

When `dataset` is a string, it will get class names from file `mmdet.core.evaluation.class_names.py` rather than the actual class names of the dataset.

This bug will only affect the printed table, while the training and evaluation itself is still correct.

**Comment by BIGWangYuDong** [comment]
The logic need update, but #9878 is not a good way to fix this error
