### ISSUE TITLE
[benchmark regression] benchmark test

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmdetection#9884]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I test some models by banchmark ， but the my mAP results is 0.
the configs includes：
- deformable_detr/deformable-detr_r50_16xb2-50e_coco.py
- detr/detr_r50_8xb2-150e_coco.py
- mask2former/mask2former_r50_8xb2-lsj-50e_coco.py

### Environment

mmdet

- branch：dev-3.x
- commit_id: c3513a
- mmcv：2.0.0rc4
- mmdet：3.0.0rc6
- mmegine：0.5.0
- Base：Python3.7/Cuda11.3/Torch1.10

**Comment by hhaAndroid** [comment]
@pekopoke Thanks for your feedback, this is because the weight path in the metafile is not updated.
