### ISSUE TITLE
How to freeze backbone network layer

### ISSUE THREAD

**Issue by ibrahim014** [open-mmlab/mmdetection#9899]
I want to freeze the layers of backbone network, is there any way to do this in config file? Or we need to make changes in other files.

**Comment by zwhus** [comment]
In config file, you can set frozen_stages to freeze the layers of backbone network.

**Comment by SajjadPSavoji** [comment]
This a follow up on this topic, for the case of training with `dist_train.py` after setting the `frozen_stages=x` in model backbone dict, I get the following error. 

```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused param
eter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by                                                                                       
making sure all `forward` function outputs participate in calculating loss.                                                       
```

I did some digging and apparently it is cause by the fact that DistributedDataPipeline from torch does not support parameters with no effect on the loss function. 

One solution is to add `find_unused_parameters=True` in the train_config.py file, but it slows down the training. 

Does anybody have a solution for this?
