### ISSUE TITLE
the training process hangs 

### ISSUE THREAD

**Issue by wsnedy** [open-mmlab/mmdetection#99]
When i use mmdetection to training, it always hangs after several epoches. And there is no error messages in the terminal. I use `Ctrl+C` to interrupt the training, and i found the GPUs is still busy.
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   52C    P0    78W / 300W |   7579MiB / 16152MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1C:00.0 Off |                    0 |
| N/A   46C    P0    69W / 300W |   7513MiB / 16152MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:1D:00.0 Off |                    0 |
| N/A   44C    P0    72W / 300W |   9215MiB / 16152MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:1E:00.0 Off |                    0 |
| N/A   46C    P0    69W / 300W |   6411MiB / 16152MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    386582      C   ...ong/anaconda3/envs/torch_0.4/bin/python  7544MiB |
|    1    386583      C   ...ong/anaconda3/envs/torch_0.4/bin/python  7478MiB |
|    2    386584      C   ...ong/anaconda3/envs/torch_0.4/bin/python  9180MiB |
|    3    386585      C   ...ong/anaconda3/envs/torch_0.4/bin/python  6376MiB |
+-----------------------------------------------------------------------------+`

Then I kill the process, it gives me this message:
`/nfsdata1/home/qc/anaconda3/envs/torch_0.4/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 8 leaked semaphores to clean up at shutdown  len(cache))`
Looks like it is a bug of multiprocessing in PyTorch, and this [pull request](https://github.com/pytorch/pytorch/pull/9655) have already solve this problem, my torch version is `0.4.1` install using pip.
Have you met this before? What should i do in this version to avoid this situation?
Thanks

**Comment by hellock** [comment]
We have met this occasionally, especially on V100, but it never happens when we only use single machine. This seems a common issue of PyTorch and we are waiting for an official fix. **Maybe** compiling PyTorch from source can help.

**Comment by wsnedy** [comment]
Ok, i will try to compile PyTorch from source, thanks for replying

**Comment by ashnair1** [comment]
@hellock Has an official fix been implemented yet?
