### ISSUE TITLE
How to debug with multi-gpu training

### ISSUE THREAD

**Issue by VectorYoung** [open-mmlab/mmdetection#992]
Hi, I am trying to debug multi-gpu training with Pycharm. But the multi-gpu training directly called the module `torch.distributed.launch`. I didn't find out how to debug it on Pycharm. I configure it this way
![pycharmdebug](https://user-images.githubusercontent.com/20220449/61187900-87095200-a645-11e9-8b23-13df92905dfb.png)
But it threw out error 'no module named tools/train.py'

Could you please help, I am trying to understand the codes by debugging.

**Comment by hellock** [comment]
I suggest using single gpu for debugging. It is hard to debug in the distributed training mode.

**Comment by nahi27** [comment]
> Hi, I am trying to debug multi-gpu training with Pycharm. But the multi-gpu training directly called the module `torch.distributed.launch`. I didn't find out how to debug it on Pycharm. I configure it this way
> ![pycharmdebug](https://user-images.githubusercontent.com/20220449/61187900-87095200-a645-11e9-8b23-13df92905dfb.png)
> But it threw out error 'no module named tools/train.py'
> 
> Could you please help, I am trying to understand the codes by debugging.

Where you able to find out about this?

**Comment by Dejan1969** [comment]
Solution: Module name: /home/user/.local/lib/python3.6/dist-packages/torch/distributed/launcher.py
or wherever your module.distributed.launch is...

**Comment by purity77** [comment]
- I solve the bug by this in remote python interpreter

![image](https://user-images.githubusercontent.com/32607221/82396503-a56b8580-9a80-11ea-832b-17275db2f8ea.png)

**Comment by ghasemikasra39** [comment]
Dear @Dejan1969 
I am doing **remote** debugging. How can I apply this?

**Comment by muzi-8** [comment]
@ghasemikasra39 
Did you solve this problem？ Thanks！

**Comment by trinhvg** [comment]
> launch

Thank you, it works well.

**Comment by trinhvg** [comment]
> * I solve the bug by this in remote python interpreter
> 
> ![image](https://user-images.githubusercontent.com/32607221/82396503-a56b8580-9a80-11ea-832b-17275db2f8ea.png)

@purity77
Thank you, it works well for me

**Comment by forever208** [comment]
share a debugging with 'torchrun'

![Image](https://github.com/user-attachments/assets/43b755a6-37b5-4aa0-80dd-94ad900e4fb7)

**Comment by ChaoyiZh** [comment]
> share a debugging with 'torchrun'
> 
> ![Image](https://github.com/user-attachments/assets/43b755a6-37b5-4aa0-80dd-94ad900e4fb7)

You save my ass when debugging llamagen. Thank you so much!
