### ISSUE TITLE
请问模型训练时具体的forward代码是在哪个py文件里

### ISSUE THREAD

**Issue by qierrrrrrr** [open-mmlab/mmdetection#9920]
作者您好，我是使用mmdet的新手。我想具体的浏览一下模型训练时，输入一张图片执行的forward代码，但是train.py中都是一些封装的函数，请问方便解答在哪个python文件中吗，谢谢

**Comment by initiater** [comment]
Go to the mmdet folder and find the backbones in the models to see which of the backbones in your own model is used and which has the specific model implementation

**Comment by dsp6414** [comment]
去b站看下mmdetection精讲

**Comment by qierrrrrrr** [comment]
谢谢

**Comment by dsp6414** [comment]
已收到！
