### ISSUE TITLE
NotImplementedError: forward_dummy is not implemented in SOLOv2

### ISSUE THREAD

**Issue by comingsoon1204** [open-mmlab/mmdetection#9951]
NotImplementedError: forward_dummy is not implemented in SOLOv2

NotImplementedError: forward_dummy is not implemented in SOLOv2

Is solov2's parameter volume calculation not implemented yet? Any current ideas on this?

**Comment by hhaAndroid** [comment]
@comingsoon1204 I recommend that you use the mmdet 3.x branch
