### ISSUE TITLE
OW-DETR how can I fix an error:OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by KevinHuang1102** [open-mmlab/mmdetection#9954]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

When I run test.py, I get an error:
OutOfMemoryError: CUDA out of memory. Tried to allocate 1.88 GiB (GPU 0; 7.78 GiB total capacity; 5.65 GiB already allocated; 643.62 MiB free; 5.90 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

### Environment

https://github.com/akshitac8/OW-DETR
I use 3070 to run this project

### Expected results

none

### Additional information

I think that maybe I should change parameters of batch_size.
But I can not find where can I change.
Does anyone know how to solve this problem please.

**Comment by hhaAndroid** [comment]
@KevinHuang1102 You can go to the official repo and ask about it.
