### ISSUE TITLE
Can not find RTMDetSepBNHead

### ISSUE THREAD

**Issue by timlliu** [open-mmlab/mmdetection#9958]
https://github.com/open-mmlab/mmdetection/blob/61dd8d518b13c7ee4bdf609595b7e803f3ac0224/configs/rtmdet/rtmdet_l_8xb32-300e_coco.py#L31

I can't find RTMDetSepBNHead from mmdet.models

**Comment by RangiLyu** [comment]
You can find it in here https://github.com/open-mmlab/mmdetection/blob/c3200601832c9124a83df663b9234d4369adbd9e/mmdet/models/dense_heads/rtmdet_head.py#L530
