### ISSUE TITLE
RuntimeError: shape '[-1, 4]' is invalid for input of size 95 when testing yolo(filp=true)

### ISSUE THREAD

**Issue by Murray-Yin** [open-mmlab/mmdetection#9962]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

![2222222](https://user-images.githubusercontent.com/114552554/225578970-75b0ed6b-46bc-4ff3-a9a0-a060ed6a46aa.jpg)
![1111111](https://user-images.githubusercontent.com/114552554/225579009-4310eca8-521c-433a-bb6d-69b61b7ac4f1.jpg)
当我想在yolo上进行multiscaleFlipAug（flip=true）时，却出现了以上问题，如何解决，谢谢！

**Comment by RangiLyu** [comment]
Thanks for your bug report! The post processing of YOLOv3 has a bug during TTA. We will fix it in the next version.

**Comment by RangiLyu** [comment]
Fixed in https://github.com/open-mmlab/mmdetection/pull/9992. Please try the latest dev branch.
