### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GTrui6** [open-mmlab/mmdetection#9968]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

I set up the environment as the official instruction

### Reproduces the problem - code sample

python tools/train.py \
    /home/rui/rtmdet/mmdetection/configs/cityscapes/mask-rcnn_r50_fpn_1x_cityscapes.py \

### Reproduces the problem - command or script

   config_file: /home/rui/rtmdet/mmdetection/configs/cityscapes/mask-rcnn_r50_fpn_1x_cityscapes.py 

### Reproduces the problem - error message

TypeError: class `ValLoop` in mmengine/runner/loops.py: class `CityScapesMetric` in mmdet/evaluation/metrics/cityscapes_metric.py: __init__() got an unexpected keyword argument 'ann_file'

### Additional information

I didn't change any of the config file, but just run the model on standard datasets cityscapes

**Comment by BIGWangYuDong** [comment]
Seems this is a bug. you can delete ann_file in CityScapeMetric to fix this error.

**Comment by BIGWangYuDong** [comment]
Also, seems after #9709 this bug has been fixed

**Comment by GTrui6** [comment]
Appreciated your help, i have solved the problem.
